### ISSUE TITLE
Set up Travis CI for integration testing

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1]
Pretty self explanatory, we need to set up Travis CI to test all the PRs.

**Comment by gravyboat** [comment]
https://travis-ci.org/streamlink/streamlink is configured.

**Comment by gravyboat** [comment]
We'll need to modify the `.travis.yml` to modify the env environments, currently it's pulling from some S3 bucket we don't have control over: https://github.com/gravyboat/streamlink/blob/master/.travis.yml

**Comment by cdrage** [comment]
@gravyboat I agree. I guess we can create travis-only tests for now and ignore the Amazon credentials until we have things sorted.

**Comment by cdrage** [comment]
@gravyboat I made you an owner of the streamlink org, so feel free to create a separate if you wish!

**Comment by gravyboat** [comment]
This is complete via https://github.com/streamlink/streamlink/pull/6
