### ISSUE TITLE
RTMPdump when installed through pip?

### ISSUE THREAD

**Issue by ethanhlc** [streamlink/streamlink#100]
Where does rtmpdump get installed to if we installed streamlink through pip on windows?
The streamlinkrc file has an entry for specifying the location of rtmpdump, but I'm not sure where it should point to since I installed streamlink using pip.

**Comment by sbstp** [comment]
I don't think that the pip install gives you rtmpdump.

**Comment by ethanhlc** [comment]
So, should it be installed separately? Or does not having it not matter?

**Comment by sbstp** [comment]
It's required to play RTMP streams. If watch those, then you need to install it and have your config point to where it's installed. We're still working on making things smooth on windows.

**Comment by Junior1544** [comment]
is rtmpdump needed for viewing rtmp streams in linux (on a raspberry pi, raspian version of linux)?

Just a thought that this might be causing my issues with streamlink at the moment...

**Comment by sbstp** [comment]
Yes I think so. If you have rapsbian you can just install it with apt-get and it should work.

**Comment by Junior1544** [comment]
When I tried 
sudo apt-get install rtmpdump 
it said that it's already the newest version, but it's set to manually installed?

**Comment by sbstp** [comment]
Yea that's just how apt works. You already had rtmpdump installed, it was pulled because it's a dependency of something else you have installed. Running that command changed the package's flags to say "don't delete if the dependent package of rtmpdump is removed."

**Comment by Junior1544** [comment]
ok, but how do i tell Streamlink where it is?

--James

**Comment by sbstp** [comment]
Edit your config file in `~/.config/streamlinkrc`, [(template here)](https://github.com/streamlink/streamlink/blob/master/win32/streamlinkrc), and set the `rtmpdump` value to the path of rtmpdump. You can find it by using `which rtmpdump`.

**Comment by Junior1544** [comment]
ok, i did that and when i try to play the normal stream on it (livestream.com stream) it gives me the following error:

![image](https://cloud.githubusercontent.com/assets/20785288/19753357/aa2f67c8-9b9f-11e6-8027-719f64c2bc9b.png)

i'm looking to use the normal stream because the hls stream only plays for about 35 seconds (or so) then stops...

**Comment by Erk-** [comment]
Can you try to use the 270p_hls quality. I can play that on my end.

**Comment by beardypig** [comment]
@ethanhlc did you manage to set up rtmpdump?

**Comment by ethanhlc** [comment]
I haven't really needed it because I haven't watched streams that require it, but I also have livestreamer installed so I just set the config file to point to where rtmp was installed with livestreamer.

**Comment by beardypig** [comment]
OK. If you install it using the Windows installer (available in the releases) you'll get rtmpdump installed now. I'll close this as you have resolved the issue yourself :-)
