### ISSUE TITLE
how to play this

### ISSUE THREAD

**Issue by saki4u** [streamlink/streamlink#1000]
how to play this 
https://hls.ssh101.com/live/b4umovies/index.m3u8

**Comment by horacio9a** [comment]
Believe it or not I have plain to put a similar question.
I wanted to ask how to play this:

http://e15.voyeur-house.tv/realm9/stream/c30c61d3ca7031b498751681541e0b82.m3u8

The fact is there is no problem for ffmpeg/ffplay!

I try with: livestreamer "hlsvariant://http://e15.voyeur-house.tv/realm9/stream/c30c61d3ca7031b498751681541e0b82.m3u8" ... but no luck!

**Comment by back-to** [comment]
use `hls://`
https://streamlink.github.io/cli.html#supported-streaming-protocols

```
streamlink hls://URL best
```

works for both urls

**Comment by unlocKing** [comment]
@back-to 
off-topic, but did you close your repo?

**Comment by horacio9a** [comment]
@back-to 
Thanks for the link and advice. With this we get a correct MP4 files and that is fine.
I wonder if there is a possibility to get FLV file. The difference is seen in this 2 screen shots.

![fplay](https://user-images.githubusercontent.com/17076459/27094154-792d5354-5069-11e7-830e-398ef5594a5b.jpg)
![sl](https://user-images.githubusercontent.com/17076459/27094169-861f6ac0-5069-11e7-8660-fd6af607287c.jpg)


I try with:

STREAMLINK hls://"%URL%" best --ffmpeg-audio-transcode "aac"
STREAMLINK hls://"%URL%" best --ffmpeg-video-transcode "h264"

but result is same like with:

STREAMLINK hls://"%URL%" best

**Comment by beardypig** [comment]
@horacio9a in this case those `ffmpeg` options are not applied as they only apply to some stream type. The video and audio are already h264 and aac respectively so transcoding would have no effect anyway. HLS uses the TS container format rather than mp4 (which is a subset of flv). If you want to repackage it in to an flv you'll need to use ffmpeg or similar. 

Nb. HLS does actually support mp4, but it's not widely used, nor is it supported by Streamlink.

**Comment by johnthecracker** [comment]
@saki,

I haven't seen answer to your question here or I missed it.

I can play that with ffplay.exe like this:

"C:\AP\FF\ffplay.exe" -i "https://hls.ssh101.com/live/b4umovies/index.m3u8"


ffplay version 3.3.1 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --e
nable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --
enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-li
bfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug -
-enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enabl
e-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-li
bsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolam
e --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx
 --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable
-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, hls,applehttp, from 'https://hls.ssh101.com/live/b4umovies/index.m3u8'
:
  Duration: N/A, start: 1810.414667, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yu
vj420p(pc, bt470bg), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc

    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo,
 fltp
    Metadata:
      variant_bitrate : 0
[swscaler @ 0b1cd700] deprecated pixel format used, make sure you did set range
correctly
1822.04 A-V:  0.001 fd=  22 aq=    8KB vq=  104KB sq=    0B f=0/0
