### ISSUE TITLE
plugin request stripchat.com

### ISSUE THREAD

**Issue by tonybonykony** [streamlink/streamlink#1003]
Please create a plugin for this site thanks Streamlink

**Comment by gravyboat** [comment]
Can you please provide an example URL or any other data you've collected regarding network traffic?

**Comment by tonybonykony** [comment]
I do not know what I'm saying here is correct, but this is all I have
ex: https://stripchat.com/DisneyDee 
------------------------------------------------------------------------
=> streamlink : rtmp://b-eu5.stripcdn.com/eu2?sessionHash=b77648d1ecea0fe1c597d66476041cc561591f49eeb39d675d1913f0783b&domain=stripchat.com/617705_aac
------------------------------------------------------------------------
=> fetch from : https://cdne.stripchat.com/assets/cams/components/ui/Player/player.swf?bgColor=2829099&camId=&camProfileId=&isFullscreenEnabled=false&micId=&mirrorVideo=false&isModel=false&isCameraAccessDenied=false&previewUrl=https://c-eu2.stripcdn.com/previews/617705?1497544313255&localeData={%22backToShow%22:%22BACK%20TO%20SHOW%22,%22retryButton%22:%22Reload%22,%22startShow%22:%22START%20SHOW%22,%22settings_cameraCaption%22:%22Camera%22,%22settings_resolutionCaption%22:%22Resolution%22,%22settings_microphoneCaption%22:%22Microphone%22,%22settings_cameraPreviewCaption%22:%22Camera%20preview%22,%22settings_qualityProfileCaption%22:%22Stream%20quality%20profile%22,%22settings_modelStatusCaption%22:%22Current%20status%20for%20viewers:%22,%22profile_low%22:%22Low%22,%22profile_medium%22:%22Medium%22,%22profile_high%22:%22High%22,%22profile_hd%22:%22Widescreen%22}&version=2.7.1492&watermarkUrl=https://cdne.stripchat.com/assets/cams/components/ui/Watermark/watermark.png
=============================================================
ex2 : https://stripchat.com/mary_sexy 
--------------------------------------------------------------------------------------------------
=> Streamlink : rtmp://b-eu5.stripcdn.com/eu4?sessionHash=b77648d1ecea0fe1c597d66476041cc561591f49eeb39d675d1913f0783b&domain=stripchat.com/1110005_aac
---------------------------------------------------------------------------------------------------
=> fetch from : https://cdne.stripchat.com/assets/cams/components/ui/Player/player.swf?bgColor=2829099&camId=&camProfileId=&isFullscreenEnabled=false&micId=&mirrorVideo=false&isModel=false&isCameraAccessDenied=false&previewUrl=https://c-eu4.stripcdn.com/previews/1110005?1497544406435&localeData={%22backToShow%22:%22BACK%20TO%20SHOW%22,%22retryButton%22:%22Reload%22,%22startShow%22:%22START%20SHOW%22,%22settings_cameraCaption%22:%22Camera%22,%22settings_resolutionCaption%22:%22Resolution%22,%22settings_microphoneCaption%22:%22Microphone%22,%22settings_cameraPreviewCaption%22:%22Camera%20preview%22,%22settings_qualityProfileCaption%22:%22Stream%20quality%20profile%22,%22settings_modelStatusCaption%22:%22Current%20status%20for%20viewers:%22,%22profile_low%22:%22Low%22,%22profile_medium%22:%22Medium%22,%22profile_high%22:%22High%22,%22profile_hd%22:%22Widescreen%22}&version=2.7.1492&watermarkUrl=https://cdne.stripchat.com/assets/cams/components/ui/Watermark/watermark.png

**Comment by gravyboat** [comment]
Thanks for the additional details, if someone decides to work on this one they'll update the issue!

**Comment by tonybonykony** [comment]
Could you explain to me the rules of plugin ? I want  to learn about it, thanks Streamlink team

**Comment by Hunterek** [comment]
Maybe this will help, cam working on android device so i checked and get m3u8 link to stream. Link working also on PC browser https://hls-eu1.stripcdn.com/eu1/4273443_aac/playlist.m3u8?token=648210dfe0c93a73a68ffaaee426bdb8

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 5 - NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
