### ISSUE TITLE
2017-06-20 Douyu.com error

### ISSUE THREAD

**Issue by bupmc** [streamlink/streamlink#1004]
2017-06-20 new error:
streamlink https://www.douyu.com/17732 source -o "PATH & FILENAME"
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/17732
error: Unable to validate JSON: Unable to validate key 'data': {'hls_url': 'http://hlsa.douyucdn.cn/live/17732rtara_550/playlist.m3u8?wsSecret=25fea1e41c1af4dbf9f81b69b7ffa74e&wsTime=1497949895&did=&ver='} does not equal None or Key 'show_status' not found in {'hls_url': 'http://hlsa.douyucdn.cn/live/17732rtara_550/playlist.m3u8?wsSecret=25fea1e41c1af4dbf9f81b69b7ffa74e&wsTime=1497949895&did=&ver='}

**Comment by gravyboat** [comment]
Hello I'm not sure if you meant to write this in your dialect or not but typically we want to keep all language on this repo in English since there are people from all over the world working on this project. I tried throwing your sentence there into Google translate and it just came back with: `In the case of sufficient popularity, the medium_http and medium parameters are invalid` and I have absolutely no idea what that means. If you mean that medium quality doesn't work when a site is popular, there's nothing we can do about that. They should consider improving their infrastructure if they can't serve enough throughput. If you feel like rewriting this or finding someone who can help with the translation please do so we can better understand the issue.

**Comment by fozzysec** [comment]
it seems that douyu changed the LAPI app key again, we need a new key to get the correct json from LAPI url.
```
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/518512
{"error":0,"msg":"OK","data":{"room_id":"518512","tag_name":"\u6237\u5916","room_src":"https:\/\/rpic.douyucdn.cn\/a1706\/18\/14\/518512_170618142839.jpg","is_vertical":0,"vertical_src":"https:\/\/rpic.douyucdn.cn\/a1706\/18\/14\/518512_170618142839.jpg","cate2_id":124,"room_name":"\uff08\u5fae\u5c71\u6e56\uff09\u8fde\u64ad12\u5c0f\u65f6\u7684\u9f9f\u5b59","avatar":"https:\/\/apic.douyucdn.cn\/upload\/avanew\/face\/201703\/12\/02\/2f92572e205c1d863b36eed268f9dc7e_middle.jpg?rltime","show_status":"1","online":177424,"nickname":"\u5728\u77f3250\u8e6d\u7c89\u602a","hls_url":"http:\/\/hls3a.douyucdn.cn\/live\/518512rkfoQDgoCN_550\/playlist.m3u8?wsSecret=eec9f7f08bd3c20f937362b0d215f947&wsTime=1497764710","is_pass_player":0,"is_ticket":0,"show_details":""}}
{"error":1002,"data":[]}

error: Unable to validate JSON: Unable to validate key 'data': [] does not equal None or Type of [] should be 'dict' but is 'list'
```
The second JSON was returned by the following code.
```
110        cdn = "ws" #cdns: ["ws", "tct", "ws2", "dl"] 
111         ts = int(time.time()) 
112         sign = hashlib.md5("lapi/live/thirdPart/getPlay/{0}?aid=pcclient&cdn    ={1}&rate={2}&time={3}{4}".format(channel, cdn, rate, ts, LAPI_SECRET).encod    e("ascii")).hexdigest() 
113         headers = { 
114             "auth": sign, 
115             "time": str(ts), 
116             "aid": "pcclient" 
117         } 
118         res = http.get(LAPI_URL.format(channel, cdn, rate), headers=headers)
```

**Comment by bupmc** [comment]
上次是这位高手破解的
https://github.com/spacemeowx2/DouyuHTML5Player/commit/5065e5e8e60f1eddf2eb8370b6fcb9136c6685a4
https://github.com/spacemeowx2/DouyuHTML5Player/commit/97c72a8f4e63f9b17c176d9c36d4841b5951e478

**Comment by fozzysec** [comment]
@bupmc I use that API previously, but after I found a better API I turn to the better one. It seems that douyu just changed their API key and the new SWF player was encrypted and not easy to decrypt, you can use the following files temporarily. Just replace `douyutv.py` by the following `douyutv.py` and download the second file under the `plugins` directory it will work. https://raw.githubusercontent.com/fozzysec/streamlink/cc06ca9f4deb13a1bc8b21a13b46986d92c8ad9f/src/streamlink/plugins/douyutv.py
https://github.com/fozzysec/streamlink/blob/cc06ca9f4deb13a1bc8b21a13b46986d92c8ad9f/src/streamlink/plugins/douyutv_blackbox.py

**Comment by bupmc** [comment]
Thanks a lot!

**Comment by bupmc** [comment]
New error:
streamlink https://www.douyu.com/17732 source -o "D:\***"
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/17732
error: Unable to validate JSON: Unable to validate key 'data': {'hls_url': 'http://hlsa.douyucdn.cn/live/17732rtara_550/playlist.m3u8?wsSecret=25fea1e41c1af4dbf9f81b69b7ffa74e&wsTime=1497949895&did=&ver='} does not equal None or Key 'show_status' not found in {'hls_url': 'http://hlsa.douyucdn.cn/live/17732rtara_550/playlist.m3u8?wsSecret=25fea1e41c1af4dbf9f81b69b7ffa74e&wsTime=1497949895&did=&ver='}

**Comment by fozzysec** [comment]
@bupmc comment the following lines in `douyutv.py` can temporarily fix this issue.
```
114         #res = http.get(MAPI_URL.format(channel))
115         #room = http.json(res, schema=_room_schema)
116         #if not room:
117         #    self.logger.info("Not a valid room url.")
118         #    return
119 
120         #if room["show_status"] != SHOW_STATUS_ONLINE:
121         #    self.logger.info("Stream currently unavailable.")
122         #    return
```

**Comment by steven7851** [comment]
@fozzysec Thanks for reminding, I'll fix soon.

**Comment by fozzysec** [comment]
@steven7851 By the way, we also need an API to get those special urls with `/t/` such as https://www.douyu.com/t/lpl works. For those urls, room_id can not be found in the html source code.

**Comment by steven7851** [comment]
@fozzysec room_id still can be found in source, but it has changed name, I'll fix. Thanks.

**Comment by bupmc** [comment]
无效 0.0

**Comment by steven7851** [comment]
@bupmc Can you help me test this?
https://raw.githubusercontent.com/steven7851/streamlink/d9d7cabbf0767a6f80af2d5c9a9aff7b64e74e96/src/streamlink/plugins/douyutv.py

**Comment by gravyboat** [comment]
Please try to keep discussion in English when possible everyone, since we have a global audience it makes it much easier to communicate with each other.

**Comment by bupmc** [comment]
My comments aren't important， it's fozzysec & steven7851 contributing the code. :)

**Comment by gravyboat** [comment]
Closing this since it was fixed.
