### ISSUE TITLE
Feature Request: use Twitch stream title in player title bar / save filename

### ISSUE THREAD

**Issue by larryhastings** [streamlink/streamlink#1005]
### Checklist

- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description

Right now, when streaming a Twitch stream via streamlink, the vlc title bar is left with its default value, usually something mysterious like "http://127.0.0.1:46821/".

Twitch's API publishes the current "title" of a stream, which is metadata set by the streamer.  (I see it in the v5 API by querying "streams/?channel=<id>" and looking in response['streams'][0]['channel']['status'].)  This is usually relevant information, and it'd be nice if streamlink furnished it to the user.

I suggest two specific features:

* streamlink should set the title bar of vlc using the "--input-title-format" parameter.  The default value should be something like "{streamer_name} • {channel_status}".  Furthermore, It'd be nice if this were user-adjustable via streamlink's command line with some sort of template.
* streamlink should use the filename specified with -o as a template, parameterized with fields like the name of the streamer, the current title of the channel, and perhaps the current time.  Obviously this should use the same parameterization as the vlc title bar template, if you add that feature too.

**Comment by bastimeyer** [comment]
This is already being discussed at #623...
The conclusion right now is that it's difficult to fight all the edge cases on different OSes in combination with different players while having clean and intuitive CLI options.

The best alternative for now is using a shell wrapper script or a third party application (eg. Streamlink Twitch GUI) that reads the stream title from the Twitch.tv API and sets a custom player title.

**Comment by gravyboat** [comment]
@bastimeyer I think some of the more recent discussion in #623 is supporting it specifically for the player (VLC and MPV based on the latest comment) and fall back to nothing otherwise. Not sure what the status is though as the PR hasn't been updated for that change.

**Comment by bastimeyer** [comment]
@gravyboat These are just some suggestions, but this hasn't been implemented yet (see the last paragraph of my comment here: https://github.com/streamlink/streamlink/pull/623#issuecomment-298603780)

I'm closing this thread here, this it's a duplicate and if there's anything to add or discuss, then it should be done in the original thread, although I have to say that I hate these long and never ending threads.

**Comment by gravyboat** [comment]
@bastimeyer Yeah I know it's not supported yet, sorry if my wording caused any confusion, I was simply saying we've been discussing the potential ways it could be implemented. I also hate the never ending threads, you can be vice president of the club if you would like!
