### ISSUE TITLE
Schoolism plugin not working

### ISSUE THREAD

**Issue by ilfsn** [streamlink/streamlink#1009]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Schoolism plugin is not working, which i had subscription already.

### Environment details

Operating system and version: Windows 7 SP1
Streamlink and Python version: Windows Portable 0.6.0

### Comments, logs, screenshots, etc.

D:\TEST\Releases>Streamlink.exe --schoolism-email XXX@gmail.com --school
ism-password XXX https://www.schoolism.com/watchLesson.php?type=st&id
=399 best
[Streamlink for Windows v0.6.0 - Git 3cbf5b9]
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/wa
tchLesson.php?type=st
error: Unable to open URL: https://www.schoolism.com/watchLesson.php?type=st (50
0 Server Error: Internal Server Error for url: https://www.schoolism.com/watchLe
sson.php?type=st)
[End of Streamlink for Windows]
'id' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gravyboat** [comment]
Try wrapping the url in quotes?

**Comment by ilfsn** [comment]
Fanstatic, it working fine now.
But why command-line tutorial didn't mention about url must be with quotes ?

**Comment by gravyboat** [comment]
This is because not every URL needs to have quotes, that ampersand between `st` and `id` was breaking it. For the vast majority of URLs quotes are not required. I'm going to close this out now, thanks for confirming that worked!
