### ISSUE TITLE
Livestream.com plugin not working, or am i using it wrong?

### ISSUE THREAD

**Issue by Junior1544** [streamlink/streamlink#101]
I just installed Streamlink via pip on my raspberry pi.

then I tried to play a stream I watch all the time on livestream.com with the omxplayer and it gave me an error about needing a swf url?

here's a capture of what happened.

![image](https://cloud.githubusercontent.com/assets/20785288/19629102/bab74438-9908-11e6-8c9a-bce11f4942e4.png)

I'm tech oriented, but very heavily windows based, barely can open a terminal into the pi so am very much a beginner in this...

Thanks for any help or suggestions!

**Comment by scottbernstein** [comment]
@Junior1544 try changing the quality parameter from 270p to 270p_hls and it will work fine

**Comment by Junior1544** [comment]
Well, it's a start...   

It'll start playing the video but will stop after about 35 seconds or so.  I tried running it several times just to make sure it wasn't a fluke...

Any thoughts on that?  I need it to keep going, at least for some time because it's just plain annoying having to restart it every 30 seconds...   I can make it keep restarting, but i'll not watch it if it keeps stopping like that??

Thanks.


Thanks
--James

**Comment by scottbernstein** [comment]
OK, I have another solution for you:
- View the source of the page in your browser (CTRL+U in chrome)
- Use CTRL+F to search for this in the source of the page:  m3u8_url
- Directly after the "m3u8_url" there is will be a colon followed by a URL like this:
http://api.new.livestream.com/accounts/xxxxxx/events/yyyyyyy/videos/zzzzzzzz.m3u8

Or something similar to the above but with some additional parameters:
http://api.new.livestream.com/accounts/xxxxxx/events/yyyyyyy/videos/zzzzzzzz.m3u8?dw=100&hdnea=st=1457035319~exp=1457037119~acl=/i/9327206_4911353_57035375_1@124828/*~hmac=cb4d7b8fa90e5c932e594e353d352993ccacce55057e94acc391855b98e21f5b


If you take this full URL string and use it as the URL you pass into streamlink, and put hlsvariant:// in front of it, it will work for you

Also note that if your URL is of the second variety, there is a token with an expiration date and time that can vary depending on the stream, so you must refresh your page, view the source again and get a new URL with a fresh token every time you kick the stream off.

**Comment by Junior1544** [comment]
I'm trying to make an automated thing that'll play the video for me...   having to constantly update the code on it wont really help with that :)  For now, I'll just have it keep re-playing the video and hope someone with the right knowledge will get the livestream plugin to work better :)

Thank you so much for your help!  You've got me going, for now I'll move on to other parts of my project and come back to the video portion at a later time...

Thanks!
--James
