### ISSUE TITLE
Schoolism plugin not working with some part in playlist

### ISSUE THREAD

**Issue by ilfsn** [streamlink/streamlink#1013]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Schoolism plugin working fine but with some part of a Lesson ( playlist) it get error. I realize that some portion of error part exactly came from another course; maybe that is reason why plugin get error.

### Environment details

Operating system and version: Windows 7 SP1
Streamlink and Python version: Windows Portable 0.6.0

### Comments, logs, screenshots, etc.

D:\TEST\Releases>Streamlink.exe --schoolism-email XXX@gmail.com --schoolism-password XXX --schoolism-part 3 "https://www.schoolism.com/watchLesson.php?type=st&id=399" best -o 3.mp4
[Streamlink for Windows v0.6.0 - Git 3cbf5b9]
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=399
[plugin.schoolism][info] Attempting to play lesson Part 3
[cli][info] Available streams: 480p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://www.schoolism.com/video-html/key.php (403 Client Error: Forbidden for url: https://www.schoolism.com/video-html/key.php)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/31/1/part3_hd.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/31/1/part3_hd.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]

**Comment by ilfsn** [comment]
After login and logout a couple of times in Schoolism homepage, streamlink was able to download error part before. I don't know why but it seem all working good.

**Comment by beardypig** [comment]
If you login/logout a lot, or download too many parts using streamlink too fast you might get blocked temporarily by schoolism... You might be hitting a rate limit on their side, try to space out the downloads and see if it helps.

**Comment by ilfsn** [comment]
Great advice, I'm testing and seem working fine. Will report soon. Thanks so much.

**Comment by ilfsn** [comment]
Confirm that space out download work, 3-4 minutes between each download.

**Comment by gravyboat** [comment]
Thanks for the update @ilfsn and for the excellent idea @beardypig, I'm going to close this out.

**Comment by aeon3** [comment]
heyy @ilfsn  can you help me with grabbing those videos as well? I cant seem to make this work
