### ISSUE TITLE
Crunchyroll not working with Premium videos

### ISSUE THREAD

**Issue by xdextremex** [streamlink/streamlink#1014]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Maybe there was some update in the Premium videos API, and the streamlink can't reproduce then anymore, this message appears when i try to play it: " No playable streams found on this URL"

This problem started recently, i've always watched premium videos on it without any problems.

ps: I do have a premium account

### Reproduction steps / Explicit stream URLs to test

1. Try to open a premium video (with premium account)

http://www.crunchyroll.com/attack-on-titan/episode-37-scream-733267

http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285

http://www.crunchyroll.com/boruto-naruto-next-generations/episode-11-the-shadow-of-the-mastermind-732543

### Environment details

SO: Windows 10 Creators update
Streamlink and Python version: 0.6.0

### Comments, logs, screenshots, etc.

![2017-06-17_13-20-07](https://user-images.githubusercontent.com/13919114/27254546-e66a5a30-5360-11e7-9a82-7cdb7aba4a70.png)

**Comment by beardypig** [comment]
All the links you posted are working for me at the moment. Streamlink uses the mobile version of the streams, there could be a delay for the episodes to become available in mobile formats.

**Comment by xdextremex** [comment]
Still not working
![2017-06-19_19-06-22](https://user-images.githubusercontent.com/13919114/27307885-79db2444-5522-11e7-93e3-be9c2a60da04.png)

**Comment by beardypig** [comment]
And you're definitely logged in using `--crunchyroll-username`?

**Comment by xdextremex** [comment]
Yes, i can even watch in 1080p on non-premium videos

![2017-06-19_21-40-38](https://user-images.githubusercontent.com/13919114/27311565-25319ea8-5538-11e7-8e69-47298bbca7c5.png)

**Comment by beardypig** [comment]
OK. Could you try running streamlink with some extra options:

```
streamlink - ldebug --crunchyroll-purge-credentials --crunchyroll-username your_user http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285 best
```

And copy the output - with cmd you can right click, click mark (not sure what the Brazilian Portuguese translation will be), and drag to select text, the right click copy (or it might copy automatically). It's better to copy the text than to make a screenshot.

**Comment by xdextremex** [comment]
like this ?
`streamlink - ldebug --crunchyroll-purge-credentials --crunchyroll-username=lDet --crunchyroll-password=exemple http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285 best`

usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
streamlink-script.py: error: unrecognized arguments: http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285 best

**Comment by beardypig** [comment]
Ah, my bad. Should be `-ldebug` with out the space after `-`.

**Comment by xdextremex** [comment]
oh, and now the video is working

[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/berserk/episode-23-proclaimed-omens-734285
[plugin.crunchyroll][debug] Creating session with locale: pt_BR
[plugin.crunchyroll][debug] Session created
[plugin.crunchyroll][info] Attempting to login using username and password
[plugin.crunchyroll][info] Successfully logged in as 'lDet'
[plugin.crunchyroll][debug] Loading streams from adaptive playlist
[cli][info] Available streams: 480p_alt, 1080p_alt2, 240p_alt2, 480p_alt2, 720p_alt2, 360p_alt2, 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"

**Comment by gravyboat** [comment]
Could this potentially be a routing issue to whatever edge node you're hitting on Crunchyroll's end? If it starts happening again can you run the debug logging like you did before? I tested this last night on my Windows box and couldn't duplicate it.

**Comment by beardypig** [comment]
It could be the authentication token expiring, IIRC the plugin for crunchyroll stashes the authentication token away to use later and it is possible that the auth token expired but the plugin didn't refresh it... I would have to do some experiments to confirm that though. @xdextremex did you change your password recently?

**Comment by gravyboat** [comment]
@beardypig That actually seems plausible. The only thing I'm not sure about there is why 2 streams would work, but one would fail. If the authentication token was expired you think it would impact every stream...

**Comment by beardypig** [comment]
I understood than none of them worked?

**Comment by gravyboat** [comment]
@beardypig Hmm, I could definitely be confused, I was looking at https://github.com/streamlink/streamlink/issues/1014#issuecomment-309587396 which made me think that only that one wasn't working.

**Comment by gravyboat** [comment]
@xdextremex Have you been able to duplicate this? If not I'm going to close it since I still can't duplicate it.

**Comment by xdextremex** [comment]
Now is working fine after i did what beardypig said. you can close it.

Thank for the help guys

**Comment by gravyboat** [comment]
Good stuff, thanks for confirming!
