### ISSUE TITLE
What should we do with money people donate to the team via Bountysource or other tools (as oppossed to individuals)?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1016]
### Description

A few days ago @liamkennedy very generously donated $120 USD to the bountysource (thanks Liam!). As this is the first ever team donation I'd like to discuss how we want to handle this. Currently only myself and @beardypig are marked as bounty hunters for the project, and I'm the only actual member of the project. I see a few potential options and if anyone else has other ideas please voice them here:

1) We cash out as BTC and determine some kind of split for those interested.
2) We leave the money in the Bountysorce account in the event we want to post a bounty on a specific issue.
3) We set a default bounty for many issues and if people do them they can get paid out.
4) We cash out as USD/BTC and donate to other projects or charities.

Between option 1 and option 2 I prefer 2 simply because I don't know how we would determine a split that everyone thinks is fair, plus we have no way to pay out users like @bastimeyer, @melmorabity or @cdrage or a host of other users (please forgive me if I didn't tag you directly, but it would take far too much space!) who have contributed and it seems like there's potential for it to be a big hassle or for people to feel unfairly compensated since it's a team donation as opposed to a direct donation.

Option 3 is okay, but it just adds more management work as I don't think you can set a default value for all issues.

Option 4 is also a possibility, but seems kind of stupid to me because if we do this Liam just lost out on his tax deduction for donating to an org that actually counts as a charitable donation.

Anyways just wanted to bring this up for some discussion. @liamkennedy I'm assuming you donated to bountysource since most of our donation methods were kind of mediocre or hard to do via PayPal, did you have a specific way you wanted things to be split? If so let me know and I'll cash it out as BTC and pay out to people.

Looking forward to everyone's input!

Edit: A quick edit here, I would like to ensure we get @beardypig paid back for the money they had to spend hosting the nightly builds on S3, so if you can comment with those details @beardypig if everyone approves it we can make sure you get reimbursed.

**Comment by scowalt** [comment]
Another option I would like to add: can we invest this money somehow back into the development of streamlink? A couple of examples:

- Pay for nightly build hosting (or any other development service that would be helpful to all of the contributors that isn't free)
- Commission artwork / logo / design for the website or program (if we ever want to get rid of the doggo 😛 )

I'm not sure if this is in the spirit of BountySource donations though (this is the first I've heard of the service).

**Comment by liamkennedy** [comment]
Hi all.  Yes... I made the donation via bountysource as the three of you listed for donations to the project had different approaches to provide payment... and it would just take a lot of extra hassle on my side to handle things that way.  If you each posted a "paypal me" link I could have handled it that way - but the "project donation" via bountysource just seemed appropriate for my goals.    

I just want you to get something for what you have taken on with Streamlink.  The ustream fixes were of most relevance recently - but - really it's the whole team I wanted to recognize.   

I have no preference for how the money should be split - and feel free to do whatever you would like with it.  I'm sure I'll be sending more later too.

**Comment by gravyboat** [comment]
@scowalt These are both good ideas! Thanks for adding on to the discussion.

@liamkennedy I totally understand the annoyance in donation methods, I've been trying to find services that would make it easy for distributed teams like this for a while but have had no such luck finding ones that support payins via a variety of options, and payouts for people no matter where they live via services other than PayPal. We really do appreciate you donating to the project! Thanks again! We'll see where this discussion goes.

**Comment by gravyboat** [comment]
@beardypig Can you put together invoices from your S3 costs (and probably convert to USD)? I think I can only cash out part of the total funds, which I'll convert to bitcoin and pass your way if no one has any objections.

**Comment by beardypig** [comment]
Ok, I'll take a look and see how much it was, probably ~30-40USD.

**Comment by gravyboat** [comment]
Sounds good, just let me know and if there are no objections I'll get you paid. I'd just pay you now but I don't have any bitcoin currently.

**Comment by cdrage** [comment]
All this discussion is good with me :+1: 

I wish there was a service that's able to equally distribute donations based on maintainer commitment / contribution (this would be a good start-up idea! haha).

**Comment by gravyboat** [comment]
Thanks for weighing in @cdrage! I wish there was a tool like that as well. I thought about building one but research I did really didn't show a good market for it.

**Comment by beardypig** [comment]
I've been through the AWS invoices and added up everything, the storage costs are estimates because I have some files in S3 already :) The total is approx. 46.28 USD. @gravyboat if you send BTC to cover that please deduct any fees/commission, I don't want my choice of cryptocurrency reducing the left overs for everyone else :)

| Month | Transfer cost | Approx. Storage Cost | 
|---|---:|---:|
| Nov | $0.45 | $0.20 |
| Dec | $1.57 | $0.40 |
| Jan | $5.48 | $0.80 |
| Feb | $7.76 | $0.80 |
| Mar | $9.43 | $0.80 |
| Apr | $14.37 | $0.80 | 
| May | $2.62 | $0.80 |
| **Total** | **$41.68** | **$4.60** |

**Comment by gravyboat** [comment]
@beardypig Sounds good, I'll try to make time tonight to see what the cash out process looks like!

**Comment by beardypig** [comment]
@gravyboat thanks, no rush :)

**Comment by gravyboat** [comment]
Okay I think we should be good @beardypig. I had to cash out a few dollars more due to fees, but I sent it directly to your bitcoin address (I had to put my US address in for tax purposes so I have no idea how that will work but I should be fine since it's only after a certain amount). Here's the screenshot of the cash out request:

![beardypig_cash_out](https://user-images.githubusercontent.com/1396878/27414281-5f18424c-56b5-11e7-9601-2754b0802b85.PNG)

And here's the confirmation (note that they only process on Friday):


![beardypig_cash_out_pending](https://user-images.githubusercontent.com/1396878/27414295-7ea1ec08-56b5-11e7-90e3-6d9a091ab691.PNG)

**Comment by gravyboat** [comment]
Some nice discussion on this here: https://github.com/gratipay/inside.gratipay.com/issues/986 by the Gratipay team.

**Comment by gravyboat** [comment]
@beardypig Did you get paid?

**Comment by beardypig** [comment]
@gravyboat can you email me the bitcoin address you sent it to, I haven't seen anything yet...

**Comment by gravyboat** [comment]
@beardypig I just used the public one you have on the donation page.

**Comment by bastimeyer** [comment]
@gravyboat is there a transaction on the blockchain that is still pending or are you talking about something else? on the blockchain you can always check the current status and transactions without a fee can take several hours, even days if you're unlucky

**Comment by gravyboat** [comment]
@bastimeyer It's the transaction for the payout itself from within bountysource. The second screenshot I linked here: https://github.com/streamlink/streamlink/issues/1016#issuecomment-310255940

**Comment by gravyboat** [comment]
@rappo Sorry to tag you on this but are payouts still being processed on Bountysource? I submitted one for payout via BTC on June 21, 2017 but it still hasn't gone through. Just wanted to make sure I didn't screw something up.

**Comment by gravyboat** [comment]
@beardypig I just received confirmation via email that my cash out request to you was processed. If you can please confirm when you have a minute that would be great, I think it should be instant? I'm not sure how bitcoin processing works.

**Comment by beardypig** [comment]
@gravyboat got it :)
