### ISSUE TITLE
Twitch Plugin Recording Streams Hosted on a Twitch Users Channel

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#1017]
- [x] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

So, the problem is that when a streamer is hosting someone else on twitch, the plugin tends to record the hosted user. I think that this should have an option, such as --no-host to prevent this from happening.

1. Try to record anyone who is hosting someone else
2. The program will record the hosted person (e.g if this is a 24 hour stream they are hosting, it will record them), and this is an error in my eyes.

Operating system and version: Ubuntu 16.0.4
Streamlink and Python version: Newest Versions

**Comment by bastimeyer** [comment]
See the `--twitch-disable-hosting` parameter:
https://streamlink.github.io/cli.html#cmdoption-twitch-disable-hosting

**Comment by gravyboat** [comment]
Closing this since it's solved.
