### ISSUE TITLE
Constant Buffering on VODs

### ISSUE THREAD

**Issue by BogheanGratian** [streamlink/streamlink#102]
I'm trying to watch a twitch vod and it's constantly buffering every second. I've read some of the common issues but I have 0 understanding of how coding works, it says to put "--player cache=5000" to easy the buffering but I have no idea where on the "%appdata% streamlink" there is no configuration file only a "cli" file that says the version of the application. Could any one please help me?

**Comment by Erk-** [comment]
can you try this streamlink --player="vlc --file-caching 5000 --network-caching 5000" url quality. This is the correct doc you should look at https://streamlink.github.io/issues.html

**Comment by gravyboat** [comment]
I'm going to close this for now, there hasn't been any discussion in a while.
