### ISSUE TITLE
https://www.ustream.tv/embed/12858204 drops frequently - idea how to prevent?

### ISSUE THREAD

**Issue by FredThompsonII** [streamlink/streamlink#1022]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

https://www.ustream.tv/embed/12858204 - stream is dropped frequently.

### Expected / Actual behavior

Well, stream shouldn't be dropped...

### Reproduction steps / Explicit stream URLs to test

Assuming stream is being used (CreativeLive.com),

streamlink --retry-streams 1 --retry-open 200000 --stream-segment-threads 3 --stream-segment-attempts 4 -o "watch3 01.mkv" "https://www.ustream.tv/embed/12858204" best

### Environment details

Operating system and version: ... Win 8.1 x64
Streamlink and Python version: ... 0.6.0 python 3.5.2 - windows portable builder/installer

...

All other ustream channels used by CreativeLive.com appear to work properly.
Very nice to finally replace livestreamer. Bravo!
...

**Comment by beardypig** [comment]
How frequently does it drop? I'm coming up to the 10 minute mark recording, just wondering how long I have to wait for it to fail? :)

**Comment by FredThompsonII** [comment]
well, it goes for about 3-5 minutes then drops for me. Noticed that happening on https://www.ustream.tv/embed/952665 as well, starting tonight.

I use the portable exe for windows. 0.7.0 automated builder files claiming some needed dependencies are missing. Don't know if 0.7.0 no longer has this stuttering/restarting.

**Comment by joe-666** [comment]
This behaviour can be a normal part of the USTREAM experience. When using the "official" browser client, the stream often stops after an advertisement is inserted into the stream. (IE it's an ad-supported stream)

**Comment by gravyboat** [comment]
Can't duplicate and no further updates in a bit, if it's still happening we can reopen.

**Comment by liamkennedy** [comment]
Ustream seems to have become a little more unreliable than I've seen in the past and it's dropping frequently on this stream www.ustream.tv/channel/iss-hdev-payload.  This is running on Raspberry Pi platform and I've tried it with 0.6.0. 0.7.0 and 0.9.0.  It improves slightly if I drop from best down to 486p but it's still dropping more frequently than I've seen in the past.  As a comparison streaming from a youtube link (with the recent "hotfix" to youtube.py applied) works pretty flawlessly.  

Any idea what might be going on?  Over the years I've seen various issues with Ustream crop up (with the old livestreamer code).. so it would not surprise me if the Ustream api is acting up.  

Any idea what else I can try to diagnose / fix this?  Thanks all!!

**Comment by gravyboat** [comment]
@liamkennedy Nah let's leave it in this issue since it's basically the same problem and see if anyone weighs in.
