### ISSUE TITLE
Ustream plugin non-functional

### ISSUE THREAD

**Issue by mfrager** [streamlink/streamlink#1025]
The UstreamTV plugin is no longer able to access media streams.

$ streamlink http://ustream.tv/channel/iss-hdev-payload
[cli][info] Found matching plugin ustreamtv for URL http://ustream.tv/channel/iss-hdev-payload
[plugin.ustreamtv][warning] This stream is currently offline
error: No playable streams found on this URL: http://ustream.tv/channel/iss-hdev-payload

**Comment by beardypig** [comment]
That stream appears to be offline, I get a looping offline/repositioning video on the website.

**Comment by mfrager** [comment]
No that is typically part of the stream. I doesn't work when the cameras are active either.

**Comment by beardypig** [comment]
In this case the looping video is not part of the stream, it is a separate video being played as an offline placeholder. Unfortunately the stream is still offline so I haven't been able to test it when it is online, once the stream comes back I will see what is going wrong.

**Comment by mfrager** [comment]
I assure you that the offline video IS part of the regular stream. The problem I believe is that Ustream has redesigned their website and the video streams are no longer part of the HTML. Are there any other Ustream sources that are still working?

**Comment by beardypig** [comment]
Which version of streamlink are you using? You need at least `0.6.0` to be able to watch UStream streams. Most UStream channels work, there are a few that do not (ones that don't allow mobile streaming, which is what streamlink uses). I tested a few from the [top live streams](http://www.ustream.tv/explore/all), and they all worked. 

The [ISS HDEV channel](http://www.ustream.tv/channel/iss-hdev-payload) says "OFF AIR" on the website, and it is playing a [video](http://www.ustream.tv/recorded/104984964) in place of the live stream. The ustreamtv plugin only supports loading the live stream from a channel page - off air content is ignored, if you want to watch archived videos you need to pass the URL of the video to streamlink, eg. http://www.ustream.tv/recorded/104984964. The reason off air content is not played is because it would not be possible for streamlink to switch back to the live stream when it came back online.

**Comment by mfrager** [comment]
Yes, I'm using version 0.6.0 built from the latest master branch. Also, are you referring to the "Please stand by. The High Definition Earth Viewing experiment is either switching cameras, ..." slide that is often there? If that's the case, that slide is part of the usual video stream.

I am trying to access the live feed, not pre-recorded videos. Thanks for your help on this, I hope we can get it figured out.

**Comment by beardypig** [comment]
Yeah I'm referring to that message. It may well be the case that that message is normal in the live stream. In the case it is not part of the live stream - there is no live stream at the moment, it's offline. The video playing on the hdev channel is a pre-recording of that slide, it plays for 1 minute 46 seconds, then loops but it's not part of a live stream. 

I don't think anything else can be done until the stream is back online - if it still doesn't work in streamlink when it's back I will try to work out why.

**Comment by mfrager** [comment]
Just confirmed it's an upstream issue. No problem with the "ustream" plugin after all. Closing the ticket.

**Comment by beardypig** [comment]
Any specific reason why they are offline? I assume they are doing some work on the ISS that required them to be powered down, or maybe they need the bandwidth for something else?

**Comment by mfrager** [comment]
I read somewhere that the project was scheduled to end in 2017. I think it said they want to put some other experiment in the same place.

**Comment by beardypig** [comment]
Well that sucks :(

**Comment by liamkennedy** [comment]
To help anyone else who finds this post and wonders about this comment.

> I read somewhere that the project was scheduled to end in 2017. I think it said they want to put some other experiment in the same place.

The HDEV experiment was indeed scheduled to be replace by another (unrelated) experiment from ESA (European Space Agency) - that experiment has been delayed (multiple times) and HDEV is now safe for the foreseeable future (that other experiment seems to have been cancelled). 

There are indeed times when the video stream (encoded from Johnson Space Center) is actually offline - although thankfully that is very rare these days.  The longest that channel was offline was during Hurricane Harvey when much of JSC was shut down (except for critical systems in Mission Control and with the James Web telescope).  The building where this stream is encoded was not part of those critical systems and there was some water damage in the building.. which resulted in systems being shut down for about 5 days.
