### ISSUE TITLE
Plugin Request for UFC Fightpass

### ISSUE THREAD

**Issue by SeanDunford** [streamlink/streamlink#1029]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Not sure if this is possible but would be cool to have a plugin for ufc fightpass. Happy to contribute to developing the plugin but python isn't my primary language so would need some help.

### Description
I would like to be able to stream ufc fight pass. This is a "paid" service but they do have some free videos. Some that require a login and some that don't. It appears that there are existing "paid" services implemented already (crunchyroll)

Here is an example video that requires no login. 
https://www.ufc.tv/video/fight-night-oklahoma-city-michael-chiesa-vs-kevin-lee-preview

Here is an example of video that requires a paid account (30 day free trial available)
https://www.ufc.tv/video/ufc-fortaleza-2017

### Details
There's a similar project that exists for Kodi. I was actually looking at this to attempt to build a similar project before I found this repo. 

https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py

If you parse out the xbmc parts of the code you can very easily get stream urls. I was having issues pairing them with cookies in browser though. 

ufc.tv is using neulion and swfobject player to handle all the auth management. The code passed down from the server isn't minified but it's a nightmare to comprehend.

### Source URL 
From the above code I was able to parse out this source url. 
```
http://nlds277.cdnak.neulion.com/nlds_vod/ufc/vod/2017/06/17/28527/2_28527_cam1_cam0_2017_cam0_whole_1_ced.mp4.m3u8?hdnea=expires%3D1497944837%7Eaccess%3D%2Fnlds_vod%2Fufc%2Fvod%2F2017%2F06%2F17%2F28527%2F*%7Emd5%3D80b467247583fc329c2ba2767f552276&nltid=ufc&nltdt=8&nltnt=1&uid=2906116|User-Agent=Mozilla/5.0%20(Linux;%20Android%206.0.1;%20D6603%20Build/23.5.A.0.570;%20wv)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/56.0.2924.87%20Mobile%20Safari/537.36%20android%20mobile%20ufc%207.0310
```
The userAgent doesn't seem to be completely necessary as the `.m0_whole_1_ced.mp4.m3u8` downloads regardless. 

Contents to that file points to a bunch of smaller `mp4.m3u8` files.
### Stream file contents
```
Contents are this.
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000
2_28527_cam1_cam0_2017_cam0_whole_1_800_ced.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3000000
2_28527_cam1_cam0_2017_cam0_whole_1_3000_ced.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2400000
2_28527_cam1_cam0_2017_cam0_whole_1_2400_ced.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1600000
2_28527_cam1_cam0_2017_cam0_whole_1_1600_ced.mp4.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000
2_28527_cam1_cam0_2017_cam0_whole_1_1200_ced.mp4.m3u8
```
Appending one of thse files names to the above url produces a larger m3u8 file filled with smaller `.ts` files. I'm assuming those .ts files are encrypted as they don't play in any player.
```
http://nlds277.cdnak.neulion.com/nlds_vod/ufc/vod/2017/06/17/28527/2_28527_cam1_cam0_2017_cam0_whole_1_1200_ced.mp4.m3u8?hdnea=expires%3D1497944837%7Eaccess%3D%2Fnlds_vod%2Fufc%2Fvod%2F2017%2F06%2F17%2F28527%2F*%7Emd5%3D80b467247583fc329c2ba2767f552276&nltid=ufc&nltdt=8&nltnt=1&uid=2906116
```
Notice the bitrate before ced in the above uri. Alternatively, you can replace ced with android but doesn't seem to change much.

Without cookies and pairing with the aes key it doesn't do any good. 

Using Charles while playing on ufc.tv I was able to detect the stream.xml file which had these contents. 
### More Stream Details
```
<?xml version="1.0" encoding="utf-8" ?>
<channel version="3.5" currentTime="1488136644000" currentTimeDescription="2017-02-26 19:17:24" defaultStreamIndex="1">
    <streamDatas>
        <streamData url="/nlds/skysportsfanpass/skysports1/as/live/skysports1_hd_400" isLive="true" blockDuration="2000" bitrate="409600" liveStartupTime="1458138474000" liveDVRDuration="86400000" livePlayerDelay="25000" liveBlockDelay="16000">
            <encryption method="aes-128" keyUrl="/nlds/skysportsfanpass/skysports1/as/live/skysports1_hd_400" keyDuration="3600000" keySecure="false" keyTransfer="secure" token="NLAuth=40a77e36af54091f6442ea8b6e8530b3-0-32;serverKey_internal_ASV3=1b6f3532e8ee36cbcd1e1ba2d3536e32-d47043cd5ef615c8105f12567731d186-1488149269-32" />
            <video width="400" height="224" fps="25.000000" ccChannels="CC1,CC2,CC3,CC4" codec="avc1" />
            <audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="65536" />
            <httpservers>
                <httpserver name="nlds635.cdnaknl.oc.neulion.com" port="80" />
            </httpservers>
            <ranges>
                <range begin="2017-02-25 19:17:22" />
            </ranges>
        </streamData>
        ....
    </streamDatas>
    <ccStreamDatas>
        <streamData url="CC1" language="CC1" displayName="CC1" />
        <streamData url="CC2" language="CC2" displayName="CC2" />
        <streamData url="CC3" language="CC3" displayName="CC3" />
        <streamData url="CC4" language="CC4" displayName="CC4" />
    </ccStreamDatas>
</channel>
```

> `...` - Truncated, view full file [here](http://stream-recorder.com/forum/neul10n-livestreamer-capture-livestreamer-t22707.html?s=fec248f50809e33f379c3cb46b2ed2c7&amp;p=89946&mode=threaded)

**Notice**

> `<encryption method="aes-128" keyUrl="/nlds/skysportsfanpass/skysports1/as/live/skysports1_hd_4500" keyDuration="3600000" keySecure="false" keyTransfer="secure" token="NLAuth=40a77e36af54091f6442ea8b6e8530b3-0-32;serverKey_internal_ASV3=1b6f3532e8ee36cbcd1e1ba2d3536e32-d47043cd5ef615c8105f12567731d186-1488149269-32" />`

Neulion is used for hockey and NBA streams so there's some knowledge sprinkled through various forums related to the service. Though it's hard to tell what is old/new and some of it seems to be under wraps as they are attempting to bypass auth (not my intention).

### Grab-bag of links that I have collected. 
- [Python code to fetch stream url and cookie](https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py)
- [Kodi forum post detailing above python code](https://forum.kodi.tv/showthread.php?tid=213642&page=6)
- [Example of stream.xml with keys](http://stream-recorder.com/forum/neul10n-livestreamer-capture-livestreamer-t22707.html?s=fec248f50809e33f379c3cb46b2ed2c7&amp;p=89946&mode=threaded)
- [details on parsing neulion streams, possibly old, unrelated ]( https://www.reddit.com/r/NHLStreams/comments/2jz9kv/how_to_record_a_vlc_stream/)

**Comment by gravyboat** [comment]
Thanks for the detailed issue @SeanDunford! We'll see if someone is interested in picking this one up.

**Comment by SeanDunford** [comment]
@gravyboat - Cool! 

Yeah, the encryption seems to be the tricky part. Does that count as DRM? 

I actually spent a few hours today trying to capture the contents sent to chromecast but it doesn't do anything different than the swfobject. There's also an "isIos" flag that seems to make the video display differently but I haven't dug into it, yet.

**Comment by beardypig** [comment]
Looks like the Kodi plugin is using pretending to be the mobile client, the API behaves differently depending on the User-Agent string. I have made a quick plugin that supports free videos, I'll have to sign up for a trial to do the non-free ones. If you are around you can test it out here: [ufctv.py](https://github.com/beardypig/streamlink/blob/ufctv/src/streamlink/plugins/ufctv.py)

I don't know if there is any significant difference in the quality of the videos in mobile vs. desktop, but the desktop uses a custom adaptive video transport that isn't supported out of the box by Streamlink, so we'd have to add something to handle that. Might not be worth while though.

**Comment by SeanDunford** [comment]
Thank you @beardypig suprised with how quick you resolved this.

**Comment by jgilf** [comment]
Thanks for implementing this @beardypig 

It looks like the mobile version only pulls the videos at 1600k whereas the desktop version pulls 4500k. This is quite a significant difference. Any chance the plugin could be updated to support the desktop version's custom adaptive video transport?

**Comment by jgilf** [comment]
After a bit of investigation it also seems as though you can manually change the url to access the HLS 4500 stream. 

i.e. the highest quality the plugin can find is:

>http://nlds277.cdnak.neulion.com/nlds_vod/ufc/vod/2017/07/10/ufc_uff_07072017_maynard_ishihara/ufc_uff_07072017_maynard_ishihara_1_1600_iphone.mp4.m3u8 

However simply changing 1600 to 4500 nets you a new m3u8:

>http://nlds277.cdnak.neulion.com/nlds_vod/ufc/vod/2017/07/10/ufc_uff_07072017_maynard_ishihara/ufc_uff_07072017_maynard_ishihara_1_4500_iphone.mp4.m3u8 

However when I do this manually I have issues with accessing the key file. 

Any help with this is much appreciated!

**Comment by jgilf** [comment]
Thanks for the reply! 

The available qualities are 4500, 3000, 2400, 1600, 1200, 800 and 400.

I tried playing around with different UAs but iPhone and iPad only get 1600 whereas Android seems to get only 1200.

**Comment by beardypig** [comment]
Interesting, I wonder if Apple TV would get the higher qualities...

**Comment by jgilf** [comment]
I gave it a shot using this UA:

> AppleTV5,3/9.1.1

and I was was able to pull the 3000k stream.

> http://nlds277.cdnak.neulion.com/nlds_vod/ufc/vod/2017/07/08/213-joanna-jedrzejczyk-backstage-interview-fp/213-joanna-jedrzejczyk-backstage-interview-fp_1_3000_ced.mp4.m3u8

Is that the correct UA that I should be using?

**Comment by jgilf** [comment]
Just checked and Chromecast also pulls the 3000k stream.

**Comment by jgilf** [comment]
Great, that should work. 

I'm not entirely sure how to test it with my account as I get errors relating to parsing the key file. This is probably related the session being parsed incorrectly though.

**Comment by beardypig** [comment]
@jgilf are you able to modify the plugin python file to test/experiment?

**Comment by jgilf** [comment]
Sure I'll do it now.
