### ISSUE TITLE
Twitch.tv: use https only

### ISSUE THREAD

**Issue by stevek123** [streamlink/streamlink#103]
Since they support https now, I think the plugin should use the new url: https://usher.ttvnw.net instead of http://usher.twitch.tv (line 131), so every part of the connection would go securely.

**Comment by gravyboat** [comment]
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L131 is the line in question.

**Comment by stevek123** [comment]
Yes, that's the one. After replacing the URL, the plugin still works fine.

**Comment by stevek123** [comment]
Thank you!
