### ISSUE TITLE
Could i continue to output file? not just overwrite

### ISSUE THREAD

**Issue by myskn** [streamlink/streamlink#1035]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

https://streamlink.github.io/cli.html#file-output-options
Only force overwrite file.

feature request:
continue to output file or auto rename file(NAME_1, NAME_2, ......), if it already exists

**Comment by beardypig** [comment]
Appending would most likely result in an unplayable, or partly unplayable video. Auto renaming is something we could add though, I think it would be quite a useful feature.

**Comment by bastimeyer** [comment]
@beardypig 
Automatically using different output file names is not really intuitive, I think. Having something like file name templates would make much more sense if this should get implemented, something similar like yt-dl is doing.

@myskn 
Using a shell wrapper script for automatically generating dynamic file names is a simple alternative:
```bash
streamlink -o "$(date +"file_%Y%m%d%H%M%S.flv")" URL QUALITY
```

**Comment by CeruleanSky** [comment]
One way for people waiting on this feature could do, is the following, which handles filename extensions and multiple periods in the filename

1. replace check_file_output in Lib\site-packages\streamlink\streamlink_cli\main.py  or wherever that file is with the following:


```
def rename_file_output(filename, force):
    """Auto renames files  if file already exists"""
    log.debug("Checking file output")
    append_number = 1
    old_filename = filename
    while os.path.isfile(filename) and os.path.isfile(old_filename):
        if "." in old_filename:
            d = old_filename.rpartition(".")
            filename = d[0] + "_" + str(append_number) + d[1] + d[2]
        else:
            filename = old_filename + "_" + str(append_number)
        append_number += 1  
    return FileOutput(filename)


```
2. search and replace all check_file_output with rename_file_output in that file(should be only one occurrence below it)

Should be [more or less like this](https://github.com/CeruleanSky/streamlink/commit/ec19a443586da981ad84f97a67dae63cf4224f14?diff=split)

Just redo the "patch" whenever you upgrade until a real fix is made.  As this doesn't change the filename in the \[download\] status text or other things, it is really just a quick fix to keep applying until something official is done.
