### ISSUE TITLE
UFC.tv plugin cant get replays, 

### ISSUE THREAD

**Issue by DEDS3C** [streamlink/streamlink#1037]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

whenever i try to plug in an vod url for an ufc.tv replay or an right i get the following, [cli][info] Found matching plugin ufctv for URL https://www.ufc.tv/video/ufc-auckland-2017
error: Unable to open URL: https://www.ufc.tv/service/publishpoint (400 Client Error: Bad Request for url: https://www.ufc.tv/service/publishpoint) i think the issue might be the formatting of the  url_re in the plugin possibly since its using https?://(?:www\.)?ufc\.tv/(channel|video)/.+ which i think might be right for some but not all.

### Expected / Actual behavior

```
[cli][info] Found matching plugin ufctv for URL https://www.ufc.tv/video/ufc-auckland-2017
error: Unable to open URL: https://www.ufc.tv/service/publishpoint (400 Client Error: Bad Request for url: https://www.ufc.tv/service/publishpoint)
```

### Reproduction steps / Explicit stream URLs to test

1. https://www.ufc.tv/video/ufc-auckland-2017
2. https://www.ufc.tv/video/ufc-singapore-2017
3. https://www.ufc.tv/video/ufc-stockholm-2017

### Environment details

Operating system and version: Ubuntu 16.10
Streamlink and Python version: python 2.7.6 and Streamlink 0.6.0

**Comment by beardypig** [comment]
Can you run it again with the `-l debug` option so we can see more details. I assume that you supplied your username and password?

**Comment by DEDS3C** [comment]
i havent tried with -l debug but i will do that right now

**Comment by DEDS3C** [comment]
so here is what i get for output with -l debug `[cli][info] Found matching plugin ufctv for URL https://www.ufc.tv/video/cage-warriors-85
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.6.0', 'console_scripts', 'streamlink')()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 1027, in main
    handle_url()
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 328, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 236, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python2.7/dist-packages/streamlink/plugins/ufctv.py", line 82, in _get_streams
    self.logger.debug("Found {type}: {name}", **video)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/logger.py", line 58, in debug
    self.manager.msg(self.module, 4, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/streamlink/logger.py", line 33, in msg
    msg = msg.format(*args, **kwargs)
KeyError: 'type'
`

**Comment by DEDS3C** [comment]
@beardypig if you need more info just let me know

**Comment by beardypig** [comment]
Ah OK, that's useful. I will take a look when I can.

**Comment by Dedsec1** [comment]
sweet thanks

**Comment by back-to** [comment]
with the updated version from #1130 

it should most likely work with this `ufctv.py` file, or at least give you a different error

https://github.com/back-to/streamlink/blob/neulion1/src/streamlink/plugins/ufctv.py
