### ISSUE TITLE
Schoolism plugin not work anymore!

### ISSUE THREAD

**Issue by ilfsn** [streamlink/streamlink#1046]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

After a week working perfectly, now Schoolism not working anymore. At 2 times (lucky) it could download a worst ( 480p) video, I stopped download for 5 days in case the server block me but now the plugin stop working at all.

### Environment details

Operating system and version: Windows 7 SP1
Streamlink and Python version: portable Windows 0.6.0

### Comments, logs, screenshots, etc.

```
D:\TEST\Releases>Streamlink.exe --schoolism-email XXX --schoolism-password XXX --schoolism-part 1 -v "https://www.schoolism.com/watchLesson.php?type=st&id=420" best -o "Lesson 4\1.mp4"
[Streamlink for Windows v0.6.0 - Git 3cbf5b9]
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=420
[plugin.schoolism][info] Attempting to play lesson Part 1
[cli][info] Available streams: 480p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://www.schoolism.com/video-html/key.php (403 Client Error: Forbidden for url: https://www.schoolism.com/video-html/key.php)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/33/4/part1_hd.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/33/4/part1_hd.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]
```

**Comment by beardypig** [comment]
Does it still work on the website?

**Comment by ilfsn** [comment]
> Does it still work on the website?

Yes, video streaming on website working fine.

**Comment by beardypig** [comment]
@ilfsn what if you logout of the website, wait 20 mins or so and then try again - it could be that being logged in multiple times they might block you.

**Comment by ilfsn** [comment]
Update Situation
After a couple of days stop download, now the funny thing is Streamlink just able to download worst video (480p) ( and working fine with all links), with best (1080p) it just like logs I posted above.
I will update if I get anythings new. Anyway, better than nothing. ^^

**Comment by beardypig** [comment]
That is interesting, unfortunately I don't have a schoolism account so it's pretty hard to debug :-) Can you try again with the `-l debug` to see if that gives any more details (it probably won't though).

**Comment by narifi** [comment]
Hi! I was having a similar problem, but in my last try it worked fine. But, I'd like to ask: ilfsn, how did you download the lessons? I can stream them, but I have no clue how to keep them recorded exactly.

**Comment by ZooShu** [comment]
It's working for me when double quoting both the URL and output.

(screenshot)[https://i.imgur.com/Q6ywPXH.png]

**Comment by back-to** [comment]
looks like it solved itself

https://github.com/streamlink/streamlink/issues/1613
https://github.com/streamlink/streamlink/issues/1634

because I don't have an account, I can not confirm it,
but I close this for now.

**Comment by idealitystarts** [comment]
I use Allavsoft to download Schoolism videos
