### ISSUE TITLE
how to watch this

### ISSUE THREAD

**Issue by saki4u** [streamlink/streamlink#1052]
https://brittv.co.uk/watch/?channel=401

**Comment by gravyboat** [comment]
You're going to need to provide more info. Have you looked at the network requests made when watching one of these channels or anything? You've created a good number of issues recently that really don't have enough details. Please keep in mind this is a community driven project run by volunteers. We need people to provide as many details as possible (especially for plugin requests which I assume this is).

**Comment by saki4u** [comment]
i use snifer this comes out.
http://dev-live.ts.infinateblu.com/dag1.m3u8?sid=ezd&cid=nickjr&auth=c3RpbWU9MTQ5OTAxNTc5NyZ2YWxpZGl0eT0zJmFnbj0wJmNvbmY9dTAmc2lnbj1lMzcxMTE5YTYzZWVhMzMyZDVlNTEwNjE2MjBmZDE2OA==

on page source i see this
<script src='/js/brittv.player.js.php?key=aHR0cDovL2Rldi1saXZlLnRzLmluZmluYXRlYmx1LmNvbS9kYWcxLm0zdTg/c2lkPWV6ZCZjaWQ9bmlja2pyJmF1dGg9YzNScGJXVTlNVFE1T1RBeE5UZzFNU1oyWVd4cFpHbDBlVDB6Sm1GbmJqMHdKbU52Ym1ZOWRUQW1jMmxuYmowMk9ERTJORFExWVRSbE16Vm1NRGxrTW1VNU9ESXhZbVF3TTJZek1USmlZUT09'></script>

**Comment by beardypig** [comment]
@saki4u try out the plugin I created.

**Comment by saki4u** [comment]
do i have to update streamlink ?

**Comment by saki4u** [comment]
tnx mate it works...ty
