### ISSUE TITLE
Stops after 24 hours.

### ISSUE THREAD

**Issue by drejjmit** [streamlink/streamlink#1058]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Stops recording after exactly 24 hours.

Duration: 24 h 0 min

### Expected / Actual behavior

Should continue to record

### Reproduction steps / Explicit stream URLs to test

1. Should be easy to try out now that https://www.twitch.tv/gamesdonequick is streaming a week long marathon.

### Environment details

Operating system and version: Windows 10 x64
Streamlink and Python version: Streamlink for Windows v0.7.0

### Comments, logs, screenshots, etc.

https://i.snag.gy/B5a4En.jpg

**Comment by gravyboat** [comment]
Hmm, I wonder if this is an issue with some kind of expiry that occurs on the open session on the Twitch end. It seems unlikely that Streamlink would just die like that, but if I were an admin over there I would definitely terminate connections that were open for very long periods of time. Can you try it again but run with `-l debug` as an option when you run the command? We're going to need more information.

**Comment by drejjmit** [comment]
`
M:\twitchrip\livestreamer>streamlink -l debug -o 24test-2.ts https://www.twitch.tv/gamesdonequick 720p 
[Streamlink for Windows v0.6.0 - Git f60c40d]
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gamesdonequick
[plugin.twitch][debug] Getting live HLS streams for gamesdonequick
[cli][info] Available streams: 720p_alt, audio_only, 160p (worst), 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 297 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 298 to queue
[stream.hls][debug] Adding segment 299 to queue
[stream.hls][debug] Download of segment 297 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 298 complete
[stream.hls][debug] Download of segment 299 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 300 to queue
[stream.hls][debug] Adding segment 301 to queue
[stream.hls][debug] Adding segment 302 to queue
[stream.hls][debug] Download of segment 300 complete
[stream.hls][debug] Download of segment 301 complete
[stream.hls][debug] Download of segment 302 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 303 to queue
[stream.hls][debug] Adding segment 304 to queue
[stream.hls][debug] Download of segment 303 complete
[stream.hls][debug] Download of segment 304 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 305 to queue
[stream.hls][debug] Adding segment 306 to queue
[stream.hls][debug] Adding segment 307 to queue
[stream.hls][debug] Download of segment 305 complete
[stream.hls][debug] Download of segment 306 complete
[stream.hls][debug] Download of segment 307 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 308 to queue
[stream.hls][debug] Adding segment 309 to queue
[stream.hls][debug] Download of segment 308 complete
[stream.hls][debug] Download of segment 309 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 310 to queue
[stream.hls][debug] Adding segment 311 to queue
[stream.hls][debug] Download of segment 310 complete
[stream.hls][debug] Download of segment 311 complete

------------------------------------------------------------------

[stream.hls][debug] Adding segment 43504 to queue
[stream.hls][debug] Adding segment 43505 to queue
[stream.hls][debug] Download of segment 43504 complete
[stream.hls][debug] Download of segment 43505 complete
[download][24test-2.ts] Written 53.60 GB (23h59m48s @ 676.9 KB/s)              [stream.hls][debug] Download of segment 43505 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 43506 to queue
[stream.hls][debug] Adding segment 43507 to queue
[stream.hls][debug] Download of segment 43506 complete
[stream.hls][debug] Download of segment 43507 complete
[download][24test-2.ts] Written 53.60 GB (23h59m53s @ 681.6 KB/s)              [stream.hls][debug] Download of segment 43507 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 43508 to queue
[stream.hls][debug] Adding segment 43509 to queue
[stream.hls][debug] Adding segment 43510 to queue
[stream.hls][debug] Download of segment 43508 complete
[stream.hls][debug] Download of segment 43509 complete
[stream.hls][debug] Download of segment 43510 complete
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
[stream.hls][debug] Reloading playlist
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8 (403 Client Error: Forbidden for url: https://video-edge-c2b240.arn03.hls.ttvnw.net/v0/CuoBfyDtzRMMtGv7VtjqXQkThN0G7-wGsEbUNf6Zq-oM3yG6xzs5IahfeWvEIuI5l3nmD79Bg6Xh3Zm-MQPDk-1aOwipEknR8mwOvKIDDrfv95nTgE4mu1xlpkFUS6k4Mhv8PzyDPd3PyOqAy1ygfshB0HaIpbj4ZSnWaLIZ2H3xj8KLEOZYUjwTfEsp-fnDp3o6smvq2eUQKMVmqhlLUniVGMprgTZZBxdWQL4f7v2nKRhUa5fvBy6xNcJirRhKf85_-aHOsGzBvqgbnstOpBD6aJM_4umA84KDMZOY0ahxOGcOUT9fvxfpjIYQEhCxNB-kI4NJa0Dc3wJRwX8hGgwbzVG-C-kn_-8HPH4/index-live.m3u8)
error: Error when reading from stream: Read timeout, exiting
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows with ExitCode 1]
`

**Comment by gravyboat** [comment]
Thanks @drejjmit. Looking at the log output it definitely looks to me as though this falls into one of a couple scenarios. The first to me being the most unlikely, and that's a problem with the edge node you are connecting to. I don't believe this is the issue as you're able to stream for exactly 24 hours before the connection is terminated. The second and also less likely one to me is something between you and the edge node is terminating that open connection after 24 hours. Again I think this is unlikely. The third scenario (and one I believe to be the case, but without details from Twitch staff there's no way to know) is that they terminate connections after 24 hours. It seems to me as though that long string value after `/v0/` is most likely unique, and I bet if you ran it again you would see a different value there. The only thing I can think is Twitch is severing these connections and resetting those values after 24 hours (it's what I would do if I worked there to prevent abuse and really long running connections).

At this point everything on Streamlink's end looks good to me, it's doing exactly what it should, retrying until it can no longer reconnect to the URL source it was previously using, which triggers the read timeout and end of the process. Now with that being said we might want to add some sort of 'new' connection retry logic so that it attempts to retrieve a fresh connection instead of connecting to the source it already had. I think this would be a reasonable solution, though I'm not sure how it would impact the recording process because the segment values would change since we're technically establishing a new connection instead of an existing one.

**Comment by drejjmit** [comment]
Can't it sync the segments with a new connection since it know exactly when it will fail to get new segments from 24h old m3u8 connection? I mean if two connections are started at the same time they get the same segments from the server. http://i.imgur.com/J2KgibG.png

**Comment by gravyboat** [comment]
Sorry missed this one somehow. I don't think it's really realistic to have Streamlink handle that as this is kind of an edge case that could break and really falls into establishing a new connection. For the time being I'm going to close this as I doubt anyone will pick it up. I recommend some kind of wrapper script that will check if Streamlink is running and automatically retry, but that's kind of out of scope for us.

**Comment by testytrash** [comment]
I have experienced the same issue. Unfortunately 24 hour streams are pretty rare so its difficult to test. This a pretty old thread, so I'm just commenting to leave it registered that this persists.

It's possible that https://github.com/streamlink/streamlink/issues/2751 will fix this issue since it could be related to the connection retry regardless if its twitch's issue or not. Thank you!

**Comment by MrBrax** [comment]
```
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[plugin.twitch][info] Will skip ad segments
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <url>
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

This is what a 24 hour stream last night ended up as, cut off at exactly 24 hours.

**Comment by drag0n141** [comment]
I have that problem too, today with two streams exactly after 24 hours.
