### ISSUE TITLE
tvplayer plugin broken

### ISSUE THREAD

**Issue by saki4u** [streamlink/streamlink#1059]
https://tvplayer.com/watch/bbcone
Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (400 Client Error: Bad Request for url: http://api.tvplayer.com/api/v2/stream/live)

**Comment by saki4u** [comment]
i updated streamlink
now i see this
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/bbcone
error: Unable to open URL: http://tvplayer.com/watch/bbcone (403 Client Error: Forbidden for url: http://tvplayer.com/watch/bbcone)

**Comment by beardypig** [comment]
@saki4u I have only created a PR, it has not been merged yet - did you update the plugin manually from my branch?

If you are getting a 403 for the channel page then maybe you are not in the UK?, it is geo-blocked does it work in a browser. Also, you probably shouldn't be running it as root.

**Comment by unlocKing** [comment]
Working for me in UK

**Comment by saki4u** [comment]
i m in uk.
how to update streamlink for ubuntu?
