### ISSUE TITLE
Add PAC (proxy auto-config) support (feature request)

### ISSUE THREAD

**Issue by Ro-Den** [streamlink/streamlink#1061]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

At least 1/4 of supported websites use geo-restrictions to prevent users from undesirable countries to watch the content. Free reliable proxy servers are hard to find. Espesially located in small countries.

Some sites only restrict providing stream links, while streams themselves are accessible from around the world.

With PAC ( https://en.wikipedia.org/wiki/Proxy_auto-config ) file it is possible to use different scenarios, how given URLs or protocols are accessed. Thus, utilising proxies to find stream links only, would lower proxy servers load and make watching experience more comfortable with less disconnections, freezing and other difficulties.

There are a couple of Python projects relevant to the issue:
- PyPAC: http://pypac.readthedocs.io/en/latest/
- Pacparser: http://pacparser.manugarg.com/

**Comment by gravyboat** [comment]
We do currently support proxies via https://streamlink.github.io/cli.html#cmdoption-http-proxy but PAC is definitely worth discussing, though I don't know if others will see it as being out of scope. Personally I'm not sure how far we want to extent proxy support in regards to potential legal issues, but it's an interesting consideration.

**Comment by beardypig** [comment]
Sounds like a pretty good idea, PyPAC looks like it would fit in quite easily. Currently I use privoxy with custom rules for each site that has geo restrictions that I need to work around, which does the same thing by via a local http proxy.

**Comment by Ro-Den** [comment]
As for legal issues, let's say it's for load balancing and proxy use facilitation. I would redact the initial post if necessary.

By the way, in some cases it is possible to bypass geo-restrictions with Google Translate. Would they sue or block Google? Or configure their sites properly?

**Comment by karlo2105** [comment]
I already proposed Proxy feature for api access only : https://github.com/streamlink/streamlink/issues/594 ;)

**Comment by 10mins** [comment]
> As for legal issues, let's say it's for load balancing and proxy use facilitation.

> By the way, in some cases it is possible to bypass geo-restrictions with Google Translate. Would they sue or block Google? 

Why? Bypassing geo-block is not illegal.

**Comment by gravyboat** [comment]
@10mins You're right it's not illegal, but if someone tries to come after us even with a frivolous lawsuit we can't afford to fight it.

**Comment by beardypig** [comment]
I created a branch (https://github.com/beardypig/streamlink/tree/pac-proxy) that adds support for PAC, however the `pypac` module depends on quite a few thing and I'm not sure if we want to add all that to the dependency list :)

**Comment by Ro-Den** [comment]
@beardypig 

Thanks a lot! Everything works great as usual. You are the BEST !

**Comment by Ro-Den** [comment]
While testing in Python 3.4.4 with PyPac 0.9.0 , I got the following issue:
```
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\streamlink.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\streamlink_cli\main.py", line 984, in main
    setup_streamlink()
  File "c:\python34\lib\site-packages\streamlink_cli\main.py", line 756, in setup_streamlink
    pac_file = get_pac(js=resp.content)
  File "c:\python34\lib\site-packages\pypac\api.py", line 43, in get_pac
    return PACFile(js, **kwargs)
  File "c:\python34\lib\site-packages\pypac\parser.py", line 53, in __init__
    if 'pyimport' in pac_js:
TypeError: 'str' does not support the buffer interface
```

Fixed it in `main.py` with **`pac_file = get_pac(js=resp.content.decode('UTF-8'))`**

Is it right? Or have I messed up my PAC file in the first place?

**Comment by beardypig** [comment]
It should automatically be decoded if the headers are set correctly, if you are using `file://` then that might not work correctly...
