### ISSUE TITLE
npo.nl live streams stopped working

### ISSUE THREAD

**Issue by sophof** [streamlink/streamlink#1062]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

npo.nl/live streams stopped working. Looks like npo changed its player.

### Expected / Actual behavior

streamlink shows a 'no streams found' error since about last night.

### Reproduction steps / Explicit stream URLs to test

npo.nl/live/npo-1

### Environment details

Operating system and version: Windows 10 and Ubuntu linux
Streamlink and Python version: streamlink: 0.7.0, python 2.7 and 3.6

### Comments, logs, screenshots, etc.

Same issue for youtube-dl, sadly without a fix this time ;-)
https://github.com/rg3/youtube-dl/issues/13568

**Comment by karlo2105** [comment]
It looks like they enabled Widewine. I suppose decryption key is here : https://npo-drm-gateway.samgcloud.nepworldwide.nl/widevine_player_cert.bin

**Comment by back-to** [comment]
# LIVE

- **DASH**
not supported by streamlink
- **HDS**
I don't know if they use HDS, i only found a HLS and a DASH link
- **HLS**
`METHOD=SAMPLE-AES` and this is **not supported by streamlink** #354 #836

```
#EXTM3U
#EXT-X-VERSION:4
## Created with Unified Streaming Platform(version=1.7.25)
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://123",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-128",NAME="Dutch/Flemish",LANGUAGE="nl",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2"

# SUBTITLES groups
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="textstream",NAME="Dutch/Flemish",LANGUAGE="nl",AUTOSELECT=YES,DEFAULT=YES,URI="npo-1-tt888_nld=64000.m3u8"

# variants
#EXT-X-STREAM-INF:BANDWIDTH=453000,AVERAGE-BANDWIDTH=412000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=384x216,FRAME-RATE=25,AUDIO="audio-aacl-128",SUBTITLES="textstream",CLOSED-CAPTIONS=NONE
npo-1-audio_nld=128000-video=200000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=803000,AVERAGE-BANDWIDTH=730000,CODECS="mp4a.40.2,avc1.42C01E",RESOLUTION=480x270,FRAME-RATE=25,AUDIO="audio-aacl-128",SUBTITLES="textstream",CLOSED-CAPTIONS=NONE
npo-1-audio_nld=128000-video=500000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1036000,AVERAGE-BANDWIDTH=942000,CODECS="mp4a.40.2,avc1.42C01F",RESOLUTION=640x360,FRAME-RATE=25,AUDIO="audio-aacl-128",SUBTITLES="textstream",CLOSED-CAPTIONS=NONE
npo-1-audio_nld=128000-video=700000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1386000,AVERAGE-BANDWIDTH=1260000,CODECS="mp4a.40.2,avc1.42C028",RESOLUTION=768x432,FRAME-RATE=25,AUDIO="audio-aacl-128",SUBTITLES="textstream",CLOSED-CAPTIONS=NONE
npo-1-audio_nld=128000-video=1000000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1853000,AVERAGE-BANDWIDTH=1684000,CODECS="mp4a.40.2,avc1.42C029",RESOLUTION=1024x576,FRAME-RATE=25,AUDIO="audio-aacl-128",SUBTITLES="textstream",CLOSED-CAPTIONS=NONE
npo-1-audio_nld=128000-video=1400000.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=220000,AVERAGE-BANDWIDTH=200000,CODECS="mp4a.40.2",AUDIO="audio-aacl-128",SUBTITLES="textstream"
npo-1-audio_nld=128000.m3u8

# keyframes
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=30000,CODECS="avc1.42C01E",RESOLUTION=384x216,URI="keyframes/npo-1-video=200000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=73000,CODECS="avc1.42C01E",RESOLUTION=480x270,URI="keyframes/npo-1-video=500000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=103000,CODECS="avc1.42C01F",RESOLUTION=640x360,URI="keyframes/npo-1-video=700000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=146000,CODECS="avc1.42C028",RESOLUTION=768x432,URI="keyframes/npo-1-video=1000000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=205000,CODECS="avc1.42C029",RESOLUTION=1024x576,URI="keyframes/npo-1-video=1400000.m3u8"

```


# VOD

- **DASH**
not supported by streamlink
- **HLS**
this could work but i did not test it

```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.7.25)

# variants
#EXT-X-STREAM-INF:BANDWIDTH=400000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=320x180
VPWON_1268955-audio=128000-video=249000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=659000,CODECS="mp4a.40.2,avc1.77.31",RESOLUTION=480x270
VPWON_1268955-audio=128000-video=493000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=821000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=480x270
VPWON_1268955-audio=128000-video=646000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1425000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=768x432
VPWON_1268955-audio=128000-video=1216000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2106000,CODECS="mp4a.40.2,avc1.77.31",RESOLUTION=960x540
VPWON_1268955-audio=128000-video=1858000.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=136000,CODECS="mp4a.40.2"
VPWON_1268955-audio=128000.m3u8

```

**Comment by sophof** [comment]
So even though the stream is freely available it is somehow DRM'ed? I saw that the author of the uitzending-gemist plugin for Kodi claims to have this working (although that doesn't use streamlink obviously), but going through his code I couldn't really figure out what he changed.

**Comment by back-to** [comment]
ok it's **still working with streamlink**,

streamlink is using some **OLD API**
all livestreams are **GEO Blocked to NL** in the **OLD API**,

livestreams are not blocked in the **NEW API** but they are DRM protected, so **not usable** for streamlink

until they don't shut the **OLD API** down all livestreams should work for now.

---

can you test it https://github.com/back-to/streamlink/commit/08b763d097d9fc011cbb1cf70a81cf1b4bb9c407 🌵

**Comment by karlo2105** [comment]
@back-to 
I confirm everything is working fine. Thanks for fix. ;)

**Comment by sophof** [comment]
Can also confirm it works. Does look like the best resolution is lower than before, but that could be because of the change to DRM I guess? I must admit I can't really follow the discussion

**Comment by back-to** [comment]
the stream that you will get from this plugin are the same as before,

the new streams won't work with streamlink.

If you want the best resolution, you need to use your browser.

**Comment by IniDux** [comment]
Sorry to post this here, but haven't found any other place talking about this recent change in the stream.

I've tried changing the end of the stream to ' npo-1.isml/Manifest ' but it only plays a green screen with no sound. This method had worked for me with another TV channel from Belgium that also separated the video and audio. I'm still learning.

Here is the original Separate Video and Audio Streams that I tried to make work:

 - Video Stream - 
https://nl-ams-p4-am5.cdn.streamgate.nl/eyJ0..........pN1U/live/npo/u/npoplus/drm/dash/npo-1/0/0/0/npo-1.isml/dash/npo-1-video=1000000-37529300784.dash

- Audio Stream -
https://nl-ams-p4-am5.cdn.streamgate.nl/eyJ0.........pN1U/live/npo/u/npoplus/drm/dash/npo-1/0/0/0/npo-1.isml/dash/npo-1-audio_nld=128000-72056257599488.dash

- I Tried the following - it play only a green screen - 
 https://nl-ams-p4-am5.cdn.streamgate.nl/eyJ0.........pN1U/live/npo/u/npoplus/drm/dash/npo-1/0/0/0/npo-1.isml/Manifest

ANY Suggestions ?
