### ISSUE TITLE
plz add re-download function

### ISSUE THREAD

**Issue by cvcmv** [streamlink/streamlink#1064]
sometimes some segment download failed due to unstable network, but it resume download next segment, which had led to the final .ts file was not in synchronization. i tried set "--hls-segment-threads" (1 to 8), but it still failed

D:\streamlink.exe --hls-segm
ent-threads 2 "hls://http://144.217.68.106/live/3baf7db0d8f1d400816fb6166b297f46.m3u8" best
-o "C:\0.ts"
[cli][info] Found matching plugin stream for URL hls://http://144.217.68.106/liv
e/qPHe7CNagro79YoHoMNftA/1499285988/3baf7db0d8f1d400816fb6166b297f46.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[download][0.ts] Written 179.9 MB (23m18s @ 120.9 KB/s)                      [
stream.hls][error] Failed to open segment 261: Unable to open URL: http://144.21
7.68.106/hls/3baf7db0d8f1d400816fb6166b297f46-261.ts (500 Server Error: Internal
 Server Error)
[download][0.ts] Written 296.1 MB (38m5s @ 137.2 KB/s)                       [
stream.hls][error] Failed to open segment 386: Unable to open URL: http://144.21
7.68.106/hls/3baf7db0d8f1d400816fb6166b297f46-386.ts (timed out)
[download][0.ts] Written 475.9 MB (1h1m34s @ 200.3 KB/s)

**Comment by bastimeyer** [comment]
> D:\livestreamer-v1.12.2>livestreamer

You seem to be using Livestreamer... This is Streamlink, a fork of the dead Livestreamer project. Any bug reports, etc should be about Streamlink and not about Livestreamer. Please try running streamlink instead:
https://streamlink.github.io/install.html

> --hls-segment-threads

As you can read in the documentation, this parameter doesn't affect segment download attempts. This will only increase the number of parallel segment downloads. You are looking for `--hls-segment-attempts` and `--hls-segment-timeout`.

https://streamlink.github.io/cli.html#cmdoption-hls-segment-attempts
https://streamlink.github.io/cli.html#cmdoption-hls-segment-timeout

**Comment by gravyboat** [comment]
I'm going to close this for now as it appears @bastimeyer has provided details for what is supported. Thanks @bastimeyer!
