### ISSUE TITLE
arconaitv.me plugin broken

### ISSUE THREAD

**Issue by saki4u** [streamlink/streamlink#1067]
anconai made changes to there website streams not working....tnx
http://arconaitv.me/stream.php?id=69

**Comment by saki4u** [comment]
PLEASE FIX ARCONAI plugin too....tnx

**Comment by back-to** [comment]
here you can test it

```py
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream

_url_re = re.compile(r'''https?://(www\.)?arconaitv\.me/stream\.php\?id=\d+''')
_playlist_re = re.compile(r'''source\ssrc=["'](?P<url>[^"']+)["']''')


class ArconaiTv(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        headers = {
            'User-Agent': useragents.CHROME,
            'Referer': self.url
        }

        res = http.get(self.url, headers=headers)

        match = _playlist_re.search(res.text)
        if match is None:
            return

        url = match.group('url')

        if url:
            self.logger.debug('HLS URL: {0}'.format(url))
            yield 'live', HLSStream(self.session, url, headers=headers)

__plugin__ = ArconaiTv
```

**Comment by unlocKing** [comment]
C:\Users\j>streamlink http://arconaitv.me/stream.php?id=30 best
[cli][info] Found matching plugin arconai for URL http://arconaitv.me/stream.php?id=30
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://149.56.27.145/live/YXH3hmVh3Up6vr4DJ-_n0g/1499376775/a8107d2e6831bddc1fe8c05a804ca0c1.m3u8')> (Could not open stream: Unable to open URL: http://149.56.27.145/live/YXH3hmVh3Up6vr4DJ-_n0g/1499376775/a8107d2e6831bddc1fe8c05a804ca0c1.m3u8 (404 Client Error: Not Found for url: http://149.56.27.145/live/YXH3hmVh3Up6vr4DJ-_n0g/1499376775/a8107d2e6831bddc1fe8c05a804ca0c1.m3u8))
error: Could not open stream <HLSStream('http://149.56.27.145/live/YXH3hmVh3Up6vr4DJ-_n0g/1499376775/a8107d2e6831bddc1fe8c05a804ca0c1.m3u8')>, tried 1 times, exiting

**Comment by beardypig** [comment]
@saki4u when creating issues please following the instructions in the issue template, it is also unnecessary to post "bump" comments.

**Comment by back-to** [comment]
@unlocKing maybe unlucky ? did you try some other ?

```
[Streamlink for Windows v0.7.0 - Git 3a6547c]
[cli][info] Found matching plugin arconai for URL http://arconaitv.me/stream.php?id=30
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
```

**Comment by saki4u** [comment]
yes its working m8...ty

**Comment by unlocKing** [comment]
Yep, working..

Prob a site error when I tested earlier.


Cheers!
