### ISSUE TITLE
Vaughnlive.tv plugin no longer able to find playable streams

### ISSUE THREAD

**Issue by Neclord9** [streamlink/streamlink#1068]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Streamlink responds with "error: No playable streams found on this URL" when using any channels url.
```
streamlink  https://vaughnlive.tv/thirdparty best
[cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/thirdparty
error: No playable streams found on this URL: https://vaughnlive.tv/thirdparty
```
 (screenshot below)
...

### Expected / Actual behavior
It used to detect & play the stream from simply putting in 
```
streamlink  https://vaughnlive.tv/newzviewz best
```
now it gives the response of
```
error: No playable streams found on this URL: https://vaughnlive.tv/thirdparty
```
...

### Reproduction steps / Explicit stream URLs to test

1. https://vaughnlive.tv/newzviewz
2. https://vaughnlive.tv/thirdparty
3. https://vaughnlive.tv/416moviez

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: Streamlink version (0.7) & Python 2.7.13

...

### Comments, logs, screenshots, etc.
Seems vaughnlive.tv may have made some changes to their website breaking the streamlink support, sorry if I've left anything out, this is the first bug report I've done but I love streamlink.
![Streamlink/Vaughnlive plugin response](https://user-images.githubusercontent.com/16110072/27894885-0697e838-61dd-11e7-8490-8dead30d5e3a.png)

...

**Comment by gravyboat** [comment]
We're aware of the issue and it's being discussed here already: https://github.com/streamlink/streamlink/issues/1034 they swapped over to an html5 player from their flash player (which is good) but the plugin hasn't been updated yet. I'm going to close this since we already have an existing issue. Thanks for your detailed report!
