### ISSUE TITLE
Streamgaroo

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#1069]
- [ x ] This is a feature request.

### Description

Plugin request for streamgaroo.com:
http://www.streamgaroo.com/tv-stream/united-kingdom/bbc-1-live-stream

### Expected / Actual behavior

streamlink http://www.streamgaroo.com/tv-stream/united-kingdom/bbc-1-live-stream
error: No plugin can handle URL: http://www.streamgaroo.com/tv-stream/united-kingdom/bbc-1-live-stream

**Comment by back-to** [comment]
you can use other plugins for your bbc stream, from **official sources** and with better quality.

https://www.bbc.co.uk/iplayer/live/bbcone
https://tvplayer.com/watch/bbcone
http://www.tvcatchup.com/watch/bbcone
