### ISSUE TITLE
Traceback on stream open

### ISSUE THREAD

**Issue by tonybonykony** [streamlink/streamlink#1072]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I just got this error today when i upgraded to latest version. I tried to uninstall and reinstall Streamlink. but it's not working for me

C:\Users\admin>streamlink https://bongacams.com/colombiakinky best -o E:\output.
flv
[cli][info] Found matching plugin bongacams for URL https://bongacams.com/colomb
iakinky
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\packages\flashmedia\pa
cket.py", line 20, in deserialize
    return cls._deserialize(fd, **kw)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\packages\flashmedia\am
f.py", line 110, in _deserialize
    version = U16BE.read(io)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\packages\flashmedia\ty
pes.py", line 40, in read
    raise IOError("Unable to read required amount of data")
OSError: Unable to read required amount of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in
 <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 103
8, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482
, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394
, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 345, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", lin
e 248, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\bongacams.py",
 line 112, in _get_streams
    amf_response = AMFPacket.deserialize(BytesIO(r.content))
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\packages\flashmedia\pa
cket.py", line 22, in deserialize
    raise cls.exception(err)
streamlink.packages.flashmedia.error.AMFError: Unable to read required amount of
 data

### Environment details
Operating system and version: Win 7 64bit
Streamlink and Python version: Streamlink 0.7.0

Thanks Streamlink team

**Comment by Ro-Den** [comment]
It's BongaCams related issue.

Looks like they implemented wss protocol authorisation (close code 1006): [https://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed-with-close-code-1006](url). Try blocking wss and you won't be able to play streams even with Adobe Flash Player.

And without wss authorisation BongaCams refuses to send our beloved plugin required AMF data.

**Comment by tonybonykony** [comment]
Thanks @Ro-Den , I will close this issue and wait for updating of Streamlink team

**Comment by alec20114** [comment]
and what - when ready this ?

**Comment by roboscripts** [comment]
Any news, its been a while now with no answers what so ever. I clearly remember you guys coming onto the Livestreamer project saying: hey use streamlink its well maintained and regularly updated bla bla bla not like Livestreamer....

Well i started using u guys for Bonga and i disagree with those statements. If you cant do anything about it just say so. At least on the other project users come in and propose solutions...

**Comment by Doudlidou** [comment]
Any news? its been a while now with no answers what so ever. I clearly remember you guys coming onto the Livestreamer project saying: hey use streamlink its well maintained and regularly updated bla bla bla not like Livestreamer....

Well i started using u guys for Bonga and i disagree with those statements. If you cant do anything about it just say so. At least on the other project users come in and propose solutions...
