### ISSUE TITLE
Arconai.py  plugin broken ?

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#1073]
Well my plugin did not last long, can anyone confirm it is indeed broken and not just PEBKAC, cheers.
[edit] i see their site is going through a transition, and they have changed URL syntax so no doubt plugin is borken.

**Comment by unlocKing** [comment]
It was posted yesterday  #1067 by @back-to

Below is the fix:

import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream

_url_re = re.compile(r'''https?://(www\.)?arconaitv\.me/stream\.php\?id=\d+''')
_playlist_re = re.compile(r'''source\ssrc=["'](?P<url>[^"']+)["']''')


class ArconaiTv(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        headers = {
            'User-Agent': useragents.CHROME,
            'Referer': self.url
        }

        res = http.get(self.url, headers=headers)

        match = _playlist_re.search(res.text)
        if match is None:
            return

        url = match.group('url')

        if url:
            self.logger.debug('HLS URL: {0}'.format(url))
            yield 'live', HLSStream(self.session, url, headers=headers)

__plugin__ = ArconaiTv

**Comment by bastimeyer** [comment]
You should properly format code you're pasting in any comment section on Github before submitting it.
https://guides.github.com/features/mastering-markdown/
Let me fix this for you...

Btw, a better solution for posting code is using Github gists:
https://gist.github.com/

**Comment by unlocKing** [comment]
@bastimeyer that looks much better, thanks.

**Comment by cirrusUK** [comment]
cheers lads

**Comment by JourneyOver** [comment]
Honestly I could never get arconia to work all that great with livestreamer/streamlink anyways, streams would work for a while and then all of a sudden the stream would freeze because of how arconia has his site/stream setup. Does the same crap even if you are just on his site watching the stream instead of using livestreamer/streamlink.

**Comment by cirrusUK** [comment]
@JourneyOver  Works as expected here. if its that bad you could try using firefox and when playing chosen stream, hit  F12, then hit network tab and filter .m3u8 and/or .ts for source stream URL.

**Comment by JourneyOver** [comment]
@cirrusUK it doesn't seem to matter if it's done through the source stream url or not. 

If I watch through streamlink it'll work for several hours or so but then freeze (or vlc just shuts down with an error of the stream shutting down even though the stream never shut down or anything) even if I have streamlink try to restart the stream if vlc closes unexpectedly it'll just throw some random error until I close down cmd (can't remember the exact error at the moment but it's not to do with a stream being down). 

If I watch through the site it'll pretty much do the same thing (freezing on just some random part of the stream) minus errors.
