### ISSUE TITLE
I think we should apply for Open Collective

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1076]
I think it would be nice if we could take credit card payments for donations. Paying people out will still be problematic, but this would give users the ability to easily donate to us. This is Open Collective: https://opencollective.com/ it's a pretty good platform for us (though their fees are a bit steep) since it allows for recurring donations which is a realistic model for this software. It also allows us to add multiple contributors, so we can pay people out for on-off plugin additions and so forth without having to rely on a single person getting tax details and so forth. The more ways we can provide for users to donate the better. Even if it is a pain to determine splits, this makes things easier, and we don't have to rely on Bountysource paying out (which they seem to be behind on so I don't feel comfortable asking people to donate there).

**Comment by gravyboat** [comment]
No opinions on this? I think it gives us a good opportunity to get people involved who don't want to donate via our existing methods since they accept credit cards. Octobox has a good implementation in their readme: https://github.com/octobox/octobox#backers

**Comment by beardypig** [comment]
Sounds cool. I haven't had time to digest it yet, bountysource doesn't seem to have worked out to well...

**Comment by gravyboat** [comment]
Bountysource is good for bounties, it's not great for recurring or tip style payments because the infrastructure wasn't really designed for that (with Open Collective you could have just put in an invoice for your hosting costs). Unless someone has other opinions I'll probably apply in the next couple days, I'm not sure how long they take to approve an org, or if we'll even get approved.

**Comment by gravyboat** [comment]
Okay we're pending approval over here: https://opencollective.com/streamlink. I only added a few people to the list of contributors to start with so if you don't see your name on the list of contributors (I know there are other people who are doing plenty of contributions that I didn't add) I'm happy to add you if we get approved!

**Comment by bastimeyer** [comment]
An alternative to opencollective could be [Liberapay](https://liberapay.com/), which is a non-profit organization that doesn't take any fees, is open source, doesn't require paypal and is located in France. They only support recurring payments, though, but donations can be coordinated between team members.

**Comment by gravyboat** [comment]
@bastimeyer Very cool! I haven't heard of Liberapay. The more options we have the better!

**Comment by h1z1** [comment]
I think taking donations for code that for the most part enables viewing already copy-protected content, is really quite dangerous.   It's one thing to have a hobby, quite another to try making a profit off others.  Might draw more attention then you'd want.   *shrug*
