### ISSUE TITLE
WWE Network seeking + 3500K audio

### ISSUE THREAD

**Issue by NikoofDeath** [streamlink/streamlink#1081]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

1 (bug). For both first week VODs and live streams on WWE Network, the full quality 4500K versions are not available, as is discussed here: https://github.com/streamlink/streamlink/issues/636. While AFAIK this cannot be fixed, the greater issue is that, for me at least, these week one streams, regardless of quality selected, have no audio track. After the first week, when the 4500K versions are available, there is an audio track. 

2 (improvement). For all WWE VODs and streams, there is no support for seeking, at least on MPC-HC. The fast forward and skip functions work fine, but there is no way to navigate to a precise time, or to rewind. Seeing as this is fully support by WWE Network for both VODs and livestreams, and because there are often only certain matches one wants to watch in a VOD, having a seek option would be a huge improvement.

### Reproduction steps / Explicit stream URLs to test

1. An example of a pre-4500K VOD where the audio issue is apparent (for now) is the latest PPV, Great Balls of Fire (note that after a week this should become a 4500K, audio issueless VOD): http://network.wwe.com/video/v1579578383.
2. An example of a 4500K VOD with working audio is Wrestlemania 33: http://network.wwe.com/video/v1252266283

### Environment details

Operating system and version: Windows 10 Creators Update
Streamlink version: Streamlink 7.0+38e50b2 (July 5th nightly)
Video player: MPC-HC x64 1.7.11.13 x64

**Comment by beardypig** [comment]
@NikoofDeath streamlink does not currently support seeking in streams, there are a number of issues where this has been discussed before. Sometimes the `--player-passthrough hls` option can be used, but I don't think it will work in this case due to authentication. 

As for the lack of audio track that does sound like a bug that needs fixing; I did not experience that when creating the plugin so possibly something has changed since then. Unfortunately I do not have WWEN account any more as I used a free trial to develop the plugin and I no longer have access, without an account it will be hard to debug the audio issue.

**Comment by back-to** [comment]
As there are **no other complaints** or **any logs** in such a **long** time,
it is probably a **non issue**, just temporarily or player related.

**Closing**

**Comment by NikoofDeath** [comment]
I am unsure if this would be enough to determine what the problem is, but I did notice something from debug logs: Ones over a week old (aka ones with audio) the first sequence is 1, but for ones less than a week old (aka ones without audio) the first sequence is in the 700s (the number depends from video to video)
Here's the log from one with audio: https://pastebin.com/5HTwybR1
And one without audio: https://pastebin.com/vXf9bZrV
It is also notable that the no audio archives (live streams are still 3500K) appear as 5200K, whereas the latest ones with audio appear as 4945K, perhaps that has something to do with it?
One other thing to note is that this seems to only be an issue with the main weekly shows (NXT, NXT UK, 205 Live) and special events (PPVs, NXT Takeovers). "Originals" (documentaries, ride alongs, etc.), recap shows, and archival footage (For example, this "hidden gems" video was uploaded thursday but has working audio: http://network.wwe.com/video/v2525609383) work fine. I assume that there is some difference in how these videos are uploaded. It could be that the ones that do work are uploaded/processed in advance, while the ones that don't are uploaded as it airs/after it airs (NXT and NXT UK are taped shows, so theoretically they could be uploaded in advance, but maybe they wouldn't upload ahead of time so changes can be made, as they sometimes add things)?
I apologize for not being more active in updating with info on this issue beforehand, if there's anything else I can do please let me know.
