### ISSUE TITLE
tvplayer.com 404 Client Error [again?]

### ISSUE THREAD

**Issue by jabhq** [streamlink/streamlink#1085]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x ] I have read the contribution guidelines.

Having same symptoms as previous with TVPlayer Plugin (404 Client Error #988)
With some activity on new version i.e. ... 
plugins.tvplayer: fix bug with some channels not loading
plugins.tvplayer: fix bug with some channels when not authenticated
tvplayer: updated to match change token parameter name
... wondered if something had gone amiss

I tried version 0.7 and am **sure** I got a successful stream.
The following day however this happened ... 

### Reproduction steps / Explicit stream URLs to test
1. e.g. url submitted -->https://tvplayer.com/watch/yesterday (and http: too)
2. [cli][error] Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (400 Client Error: Bad Request for url: http://api.tvplayer.com/api/v2/stream/live)
3. This message is showing for other channels too e.g. "Drama"
4. Tried on subsequent days with same result.
5. email & password used accepted on TVPlayer site and submitted as --tvplayer-email <myemail> --tvplayer-password <myPW>

### Environment details
Windows 7 SP1
Streamlink 0.7.0 / Python version: 2.7

Is it just me ???

**Comment by beardypig** [comment]
Ah yeah, that has been fixed in #1070 but I broke the tests in the process... Need to fix them :-)

**Comment by beardypig** [comment]
@jabhq now that #1070 has been merged, this should be fixed.

**Comment by RedManMark86** [comment]
Hi Beardpig,

I have updated to the lastest script and this is the error I'm getting

"  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py", line 100, in _get_streams
    stream_data = self._get_stream_data(**stream_attrs)
TypeError: _get_stream_data() missing 1 required positional argument: 'channel_id'"

Any help would be appreciated,

Thanks,

Mark

**Comment by beardypig** [comment]
@RedManMark86 yeah, I saw the issue you created. I'll take a look when I can.

**Comment by RedManMark86** [comment]
Hi @beardypig , Thanks for looking at it when you can.

I don't know if this is of any help but the Kodi addon for it still works and uses the following to open the stream

https://live.tvplayer.com/stream.m3u8?id=300&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6XC9cL2xpdmUudHZwbGF5ZXIuY29tXC9zdHJlYW0ubTN1OD9pZD0zMDAiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1MDIwMDU5MTF9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiOTUuMTQ4LjI0LjI0OVwvMzIifX19XX0_&Signature=bruGAGtoSK08redeIMsYXxycTwfLY6vFruWDp0K~Qfy8Gy9rVIlNQahqhM04rJciVgs01hP4lK4ZUy5nMrPAlDIGuXuqCBfHwQ~5sa~cf8RDwHQ5p0Ke38sUEGs8BtzwpDDXGpW-8iaXHAX-i3l1Ken5b2k~58eyXqO97s8WfB-rvzAM99QFiZXZlqFiWs9OxZ17Q4L91DgvLdcMltfqDTNLOc5ocebCpNbGR2h69945CbUQR6Y8dPYMHLAIfYHE-6qugCGB4fyJctHTkVgmyqH0ElIRQgupFZBQLlXcYeihd7T7lNhAZWvAq8g9gbq9aISY2--7qCDGYNbrfZczjA__&Key-Pair-Id=APKAJGWDVCU5SXAPJELQ|Cookies=AWSELB=63316D9B04FDD8FC9F286A83E94C330481D5C56A9391ECC3678AC3EFC096E1D6548791D10024C467A35445F93CCBCDAD585435FD66E740FC015033D28B0C8E86598B9D91C4

Regards,

Mark
