### ISSUE TITLE
Plugin request : cytu.be streams

### ISSUE THREAD

**Issue by JourneyOver** [streamlink/streamlink#1088]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Dunno if this site will be possible or not tbh, but requesting a plugin non-the-less. If it's possible then great, if not then that is fine.

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. https://cytu.be/r/southparkhd
2. https://cytu.be/r/TrojanVirus
3. https://cytu.be/r/the_movie_lounge

### Comments, logs, screenshots, etc.

The streams should be accessible without needing the javascript file from their site. video code seems to always revolve around the
`class="vjs-tech" id="ytapiplayer_html5_api"` and the source is always changing when it loads the next video in the playlist.
one moment the src could be `https://2.bp.blogspot.com/1jeLPyXkxpePwE8ffGMQPeN8N-0UhCvxHC5BWXXDbhyEnH5Xb7S6hbGEzP2fKHVqacOvHlbDPz5Q=m22` and then on the next video it'll turn into something like `https://2.bp.blogspot.com/Xi7JGt3xt6tKzXat5hH0_pCUMDstCBWMlNUf1_7SpMvW-2K5B9dSgCpFA3gM9IL03PoNtmAq5skT=m22`

There are video sources like such as well `https://r2---sn-vgqseney.c.docs.google.com/videoplayback?id=19593b929dffc2d2&amp;itag=18&amp;source=webdrive&amp;requiressl=yes&amp;mm=30&amp;mn=sn-vgqseney&amp;ms=nxu&amp;mv=m&amp;pl=26&amp;ttl=transient&amp;ei=ghplWdnXI8LSqAWs04moCQ&amp;driveid=0B2gMuPtSdzi-aUVLOU5palBwcEk&amp;mime=video/mp4&amp;lmt=1479920771846091&amp;mt=1499798030&amp;ip=2601:243:8201:2427:48c6:9631:f7b6:2f5e&amp;ipbits=0&amp;expire=1499812546&amp;cp=QVJOQUlfUVVSR1hNOnVLN0V5c1VsRTNs&amp;sparams=ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cttl%2Cei%2Cdriveid%2Cmime%2Clmt%2Ccp&amp;signature=79D2ED2A2295B33E0FC58E3A9DEE0EE7812FBF69.0DE07A866998CF9C10AF32F180E75EFDC6268F87&amp;key=ck2&amp;app=explorer`

**Comment by MineRobber9000** [comment]
>Thanks for reporting an issue!
>Please read the contribution guidelines first! (see the link above)
>Also check the list of known issues before reporting an issue!
>Feel free to use the following template. Be as detailed as possible.
>Please see the text preview to avoid unnecessary formatting errors.
>Don't forget to remove this text before submitting.

gg

Real talk though, this would be cool. Maybe it couldn't be a continuous stream but even if it can only sync to one vid at a time that would be cool.

**Comment by back-to** [comment]
As this are only VODs which are synced between users in the browser,
probably not worth for a new plugin.
