### ISSUE TITLE
vaughnlive.tv plugin broken

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#1090]
Hi

[cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/columboseries
[plugin.vaughnlive][info] Found player_version=0.1.1.796, info_url_domain=mvn.vaughnsoft.net, info_url_path=None
[plugin.vaughnlive][error] Could not detect info_url_path
error: No playable streams found on this URL: https://vaughnlive.tv/columboseries

      I guess the http://vaughnlive.tv site has changed URL syntax as the plugin reports, no playable streams found on this URL, i tried around 6 streams all with same result, can someone confirm this is indeed broken ?

regards

**Comment by mmetak** [comment]
https://github.com/streamlink/streamlink/issues/1034

**Comment by cirrusUK** [comment]
thanks @mmetak 
sorry for the noise !
