### ISSUE TITLE
Dailymotion getting timeout errors

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#1093]
Hi
I use a direct dailymotion link to  restream

It worked only once, then I get this: I also tried others urls of live streams but seems like it's blocked?

```
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x2lefik
error: Unable to open URL: http://www.dailymotion.com/sequence/full/x2lefik (HTTPConnectionPool(host='www.dailymotion.com', port=80): Read timed out. (read timeout=20.0))
```

### Environment details

ubuntu 14.04 

### Comments, logs, screenshots, etc.

Since it works once, I assume the script is working,  I just can't understand why  it won't work at all after the first time.  Is that some kind of security they have implemented?

**Comment by gravyboat** [comment]
Can you try running Streamlink with `-l debug`? Also what version of Streamlink are you on?

**Comment by campones** [comment]
yes, it looks like they have some kind of protection system implemented. 
I can' t define what exactly.  Now,  I m trying to fetch only one stream per ip (server) but that doesn't seem to matter. I also logged with a browser to "whitelist" my ip but not working (I can watch on chrome browser without any problem from the  server but streamlink will keep timing out)

**Comment by campones** [comment]
the debug doesn't add anything
`[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x3b68jn
[plugin.dailymotion][debug] Found media ID: x3b68jn
error: Unable to open URL: http://www.dailymotion.com/sequence/full/x3b68jn (HTTPConnectionPool(host='www.dailymotion.com', port=80): Read timed out. (read timeout=20.0))
`

**Comment by scottbernstein** [comment]
Having nothing to do with restreaming, I view the live stream at the URL provided (/video/xb68jn) at will and don't seem to experience the problem you are having.

________________________________

**Comment by campones** [comment]
what does that mean? absolutely nothing...  I didn't say it was a problem related to restreaming, I cannot connect to the url, though I receive a timeout, when I grab the direct m3u8 in source code instead, then I see "403 forbidden" output     .. you understand?

**Comment by back-to** [comment]
looks like **your connection** is faulty

does ping and curl work for you?

```sh
ping www.dailymotion.com -c 20
curl -I https://www.dailymotion.com/video/x3b68jn
```

**Comment by campones** [comment]
of course it works since I have vncviewer on the server and I m able to watch directly live channels on chrome!

**Comment by back-to** [comment]
ok since it's a server,

can you run python with

```py
import requests
requests.get('https://www.dailymotion.com/video/x3b68jn')
```

will you get <Response [200]> ?

**Comment by campones** [comment]
`Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://www.dailymotion.com/video/x3b68jn')
<Response [200]>
`

**Comment by beardypig** [comment]
What if you try 

```
import requests
requests.get('http://www.dailymotion.com/sequence/full/x2lefik') 
```?

**Comment by campones** [comment]
doesn't seem to work, it's frozen. but one stream finally started with former livestreamer so maybe that's why..

**Comment by beardypig** [comment]
It could be a user agent issue, try adding `--http header "User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 AOL/9.8 AOLBuild/4346.2019.US Safari/537.36"` to your `streamlink` command and see if that helps? Might be a long shot though.

**Comment by campones** [comment]
if it was this , why would it works  randomly?  but yes ,adding the UA is always a good thing anyway, thanks for remembering me the code snippet

**Comment by beardypig** [comment]
@campones are you accessing the stream directly from France or are you using some kind of proxy? I haven't had any problems viewing the stream.

**Comment by campones** [comment]
I m using a server based in France.     from that server I can remotely use chrome and it works fine. if I try using streamlink I get this

`error: Unable to open URL: http://www.dailymotion.com/sequence/full/x3b68jn (HTTPConnectionPool(host='www.dailymotion.com', port=80): Max retries exceeded with url: /sequence/full/x3b68jn (Caused by <class 'socket.error'>: [Errno 110] Connection timed out))
`

**Comment by campones** [comment]
`root@server:~/admin/live# streamlink hls://https://stream-03.dc3.dailymotion.com/13/dm/3/x3b68jn/live-2.m3u8 -l info
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin stream for URL hls://https://stream-03.dc3.dailymotion.com/13/dm/3/x3b68jn/live-2.m3u8
Available streams: live (worst, best)


root@server:~/admin/live# streamlink https://www.dailymotion.com/video/x3b68jn -l info
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x3b68jn
error: Unable to open URL: http://www.dailymotion.com/sequence/full/x3b68jn (HTTPConnectionPool(host='www.dailymotion.com', port=80): Max retries exceeded with url: /sequence/full/x3b68jn (Caused by <class 'socket.error'>: [Errno 110] Connection timed out))
`

**Comment by beardypig** [comment]
Does it work with curl? What does `curl -v
https://www.dailymotion.com/video/x3b68jn` output? 
That's weird because I didn't have any problems playing it via a French proxy.

**Comment by campones** [comment]
`root@server:~/admin/live# curl -v https://www.dailymotion.com/video/x3b68jn
* Hostname was NOT found in DNS cache
*   Trying 195.8.215.136...
* Connected to www.dailymotion.com (195.8.215.136) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES128-GCM-SHA256
* Server certificate:
*        subject: C=FR; ST=Ile-de-France; L=Paris; O=Dailymotion SA; CN=*.dailymotion.com
*        start date: 2015-07-09 00:00:00 GMT
*        expire date: 2018-10-06 12:00:00 GMT
*        subjectAltName: www.dailymotion.com matched
*        issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*        SSL certificate verify ok.
> GET /video/x3b68jn HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.dailymotion.com
> Accept: */*
>
< HTTP/1.1 200 OK
* Server DMS/1.0.42 is not blacklisted
< Server: DMS/1.0.42
< X-DM-BackNode: web-621.adm.dc3.dailymotion.com:80
< Vary: Accept-Encoding
< Cache-Control: no-cache
< Content-Type: text/html; charset=utf-8
< Access-Control-Expose-Headers: X-DM-BackNode-Response-Time
< Strict-Transport-Security: max-age=0; includeSubDomains; preload
< Date: Sat, 22 Jul 2017 10:54:10 GMT
< Keep-Alive: timeout=60, max=4986
< X-DM-LB-IP: 195.8.215.136
< X-DM-LB-Name: lb-09
< Transfer-Encoding: chunked
< X-DM-BackNode-Response-Time: 64
< Connection: Keep-Alive
< Set-Cookie: ts=38526; expires=Wed, 22-Aug-2018 10:54:10 GMT; Max-Age=34214399; path=/; domain=.dailymotion.com
< Set-Cookie: clsu=1; expires=Wed, 22-Aug-2018 10:54:10 GMT; Max-Age=34214399; path=/
< Set-Cookie: dmvk=59732ed2f0022; path=/; domain=.dailymotion.com
< Set-Cookie: _csrf/link=29O22K3AbLqCCwv6sBX0Jo_-E8kRRuw05TFHvWxkElE; expires=Sat, 22-Jul-2017 16:54:10 GMT; Max-Age=21599; path=/
< Set-Cookie: ts=793670; Expires=Tue, 20 Jul 2027 10:54:10 GMT; Max-Age=315360000; Path=/; Domain=.dailymotion.com
< Set-Cookie: v1st=DA7E14104A428B5B6F472996C34495BF; expires=Sun, 22 Jul 2018 10:54:10 GMT; max-age=31536000; path=/; domain=.dailymotion.com
< X-Frame-Options: deny
< X-Dm-Page: fr.html.video_item
<
<!DOCTYPE html>
<html>
`

**Comment by bastimeyer** [comment]
@campones You need 3 \` in a row for multiline code blocks:
https://guides.github.com/features/mastering-markdown/
Let me fix that for you real quick... :smiley:

**Comment by beardypig** [comment]
Cool, what about the same for http://www.dailymotion.com/sequence/full/x3b68jn, can paste the full output in to a [gist](https://gist.github.com)?

**Comment by campones** [comment]
https://pastebin.com/U2nmg2Ae

**Comment by beardypig** [comment]
And once more with `curl -v -A "python-requests/1.2.3" http://www.dailymotion.com/sequence/full/x3b68jn`. I'm not seeing any reason for it to not work at the moment though...

**Comment by campones** [comment]
https://pastebin.com/9h49zDkD

**Comment by campones** [comment]
me neither, but it doesn't work..

**Comment by beardypig** [comment]
Are you familiar with any debugging proxies? `mitmproxy` for example? Or even `tcpdump`, it would be useful to see the actual request that streamlink is making. 
Have you tried doing a clean install and moving any configuration files out of the way, just incase your installation of streamlink is messed up somehow?

**Comment by campones** [comment]
I m trying on several servers,  all have the same result.  the only thing I know is I have been restreaming dailymotion since february  and it worked fine (I was using livestreamer btw) then they probably changed something, I discovered streamlink, which is randomly working ( I guess the plugin at streamlink is maintained unlike livestreamer)

**Comment by campones** [comment]
my installation is pretty straight forward..  pip install streamlink... and that's it

**Comment by campones** [comment]
getting worst it seems, now it's encrypted, tried both direct link and with the m3u8 url
 
`[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x3b68jn
[plugin.dailymotion][debug] Found media ID: x3b68jn
[plugin.dailymotion][debug] PLAYLIST URL: http://www.dailymotion.com/cdn/live/video/x3b68jn.f4m?dvr=true&auth=1501235858-2562-wtsg9kru-cde9ea4e86365cb8fd5c80d06995f945
[cli][info] Available streams: 180p_alt (worst), 180p, 288p_alt, 288p, 477p_alt, 477p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 1501055811 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1501055812 to queue
[stream.hls][debug] Adding segment 1501055813 to queue
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://livedrm.dailymotion.com/x3b68jn (hostname 'livedrm.dailymotion.com' doesn't match either of 'stream-01.dc3.dailymotion.com', 'stream-01.ix7.dailymotion.com', 'stream-01.nyc.dailymotion.com', 'stream-01.sg1.dailymotion.com', 'stream-01.sv6.dailymotion.com', 'stream-01.ty4.dailymotion.com', 'stream-02.dc3.dailymotion.com', 'stream-02.ix7.dailymotion.com', 'stream-02.nyc.dailymotion.com', 'stream-02.sg1.dailymotion.com', 'stream-02.sv6.dailymotion.com', 'stream-02.ty4.dailymotion.com', 'stream-03.dc3.dailymotion.com', 'stream-03.ix7.dailymotion.com', 'stream-03.nyc.dailymotion.com', 'stream-03.sg1.dailymotion.com', 'stream-03.sv6.dailymotion.com', 'stream-03.ty4.dailymotion.com', 'stream-04.dc3.dailymotion.com', 'stream-04.ix7.dailymotion.com', 'stream-04.nyc.dailymotion.com', 'stream-04.sg1.dailymotion.com', 'stream-04.ty4.dailymotion.com', 'stream-05.dc3.dailymotion.com', 'stream-05.ix7.dailymotion.com', 'stream-06.dc3.dailymotion.com', 'stream-06.ix7.dailymotion.com', 'stream-07.dc3.dailymotion.com', 'stream-07.ix7.dailymotion.com', 'stream-08.dc3.dailymotion.com', 'stream-08.ix7.dailymotion.com', 'stream-09.dc3.dailymotion.com', 'stream-09.ix7.dailymotion.com', 'stream-10.dc3.dailymotion.com', 'stream-10.ix7.dailymotion.com', 'stream-11.dc3.dailymotion.com', 'stream-11.ix7.dailymotion.com', 'stream-12.dc3.dailymotion.com', 'stream-12.ix7.dailymotion.com', 'stream-13.dc3.dailymotion.com', 'stream-14.dc3.dailymotion.com', 'stream-15.dc3.dailymotion.com')
[stream.hls][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('http://stream-06.dc3.dailymotion.com/06/dm/3/x3b68jn/live-4.m3u8#cell=lvty&hls_liveSyncDuration=24')> (No data returned from stream)
error: Could not open stream <HLSStream('http://stream-06.dc3.dailymotion.com/06/dm/3/x3b68jn/live-4.m3u8#cell=lvty&hls_liveSyncDuration=24')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[stream.hls][debug] Closing worker thread
`

**Comment by beardypig** [comment]
The encryption shouldn't be a problem... I have no problems loading that stream. Could you post the output of `curl -v https://livedrm.dailymotion.com/x3b68jn` (as before, in a gist/pastebin).

You could try adding the `--http-no-ssl-verify` to disable the cert verification.

**Comment by campones** [comment]
yes when I add --http-no-ssl-verify the stream starts.

**Comment by campones** [comment]
https://pastebin.com/3XAJrHz0

**Comment by beardypig** [comment]
It's weird that `curl` doesn't seem to have a problem loading the stream. Which version of Python are you using? Could you should us the output of `pip freeze` too?

**Comment by campones** [comment]
i have python 2.7.6

**Comment by beardypig** [comment]
Is it possible for you to update Python? I believe there are some ssl issues with earlier versions, I think anything greater than 2.7.13 would be sufficient.

**Comment by campones** [comment]
I have checked some tutorials to upgrade, but I won't be doing this in a prod environment

**Comment by beardypig** [comment]
Can you install `backports.ssl_match_hostname`, that might fix the issues.

**Comment by beardypig** [comment]
Or perhaps `pip install urllib3[secure]`...

**Comment by beardypig** [comment]
@campones, I believe that installing `urllib3[secure]` will resolve the issue.

**Comment by gravyboat** [comment]
No response in months, closing.

**Comment by campones** [comment]
"in months" well that was a month and a half.

I have testified something pretty curious for me yesterday.   I opened my google chrome on the server remotely via vncviewer.  And I couldn't make that particular stream work. I was receiving a 403 forbidden for the drm dailymotion url.  On livestreamer / streamlink I d get this . Note that I m using the m3u8 url as I still can't get regular url to be used as a source. 

`[stream.hls][error] Failed to create decryptor: Unable to open URL: https://livedrm.dailymotion.com/x5idxxp (hostname 'livedrm.dailymotion.com' doesn't match either of 'stream-01.dc3.dailymotion.com', 'stream-01.ix7.dailymotion.com', 'stream-01.nyc.dailymotion.com', 'stream-01.sg1.dailymotion.com', 'stream-01.sv6.dailymotion.com', 'stream-01.ty4.dailymotion.com', 'stream-02.dc3.dailymotion.com', 'stream-02.ix7.dailymotion.com', 'stream-02.nyc.dailymotion.com', 'stream-02.sg1.dailymotion.com', 'stream-02.sv6.dailymotion.com', 'stream-02.ty4.dailymotion.com', 'stream-03.dc3.dailymotion.com', 'stream-03.ix7.dailymotion.com', 'stream-03.nyc.dailymotion.com', 'stream-03.sg1.dailymotion.com', 'stream-03.sv6.dailymotion.com', 'stream-03.ty4.dailymotion.com', 'stream-04.dc3.dailymotion.com', 'stream-04.ix7.dailymotion.com', 'stream-04.nyc.dailymotion.com', 'stream-04.sg1.dailymotion.com', 'stream-04.ty4.dailymotion.com', 'stream-05.dc3.dailymotion.com', 'stream-05.ix7.dailymotion.com', 'stream-06.dc3.dailymotion.com', 'stream-06.ix7.dailymotion.com', 'stream-07.dc3.dailymotion.com', 'stream-07.ix7.dailymotion.com', 'stream-08.dc3.dailymotion.com', 'stream-08.ix7.dailymotion.com', 'stream-09.dc3.dailymotion.com', 'stream-09.ix7.dailymotion.com', 'stream-10.dc3.dailymotion.com', 'stream-10.ix7.dailymotion.com', 'stream-11.dc3.dailymotion.com', 'stream-11.ix7.dailymotion.com', 'stream-12.dc3.dailymotion.com', 'stream-12.ix7.dailymotion.com', 'stream-13.dc3.dailymotion.com', 'stream-14.dc3.dailymotion.com', 'stream-15.dc3.dailymotion.com')
[cli][error] Try 1/1: Could not open stream <HLSStream('https://stream-04.dc3.dailymotion.com/48/dm/3/x5idxxp/live-2.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://stream-04.dc3.dailymotion.com/48/dm/3/x5idxxp/live-2.m3u8')>, tried 1 times, exiting`

Locally on my computer, the stream was working though, and it also did in the server after I did a hard reload with cache clearing of the page.  Once I did that, stream worked on both chrome then on the streamlink command line.  I have hard time understanding why clearing cache on chrome would make it also work on terminal. I guess you need  the whitelist your IP with their encryption first

**Comment by gravyboat** [comment]
@campones It could be they are specifically blocking requests in some way to prevent people from downloading video from the site and I would imagine your assumption is correct. Let's open this one back up since the direct URLs aren't working.

**Comment by campones** [comment]
now I also get things like this

[stream.hls][error] Failed to create decryptor: Unable to open URL: https://www.dailymotion.com/cdn/key/video/x3b68jn.key (HTTPSConnectionPool(host='www.dailymotion.com', port=443): Max retries exceeded with url: /cdn/key/video/x3b68jn.key (Caused by <class 'socket.error'>: [Errno 110] Connection timed out))

Also, I cannot reach the website anymore using chrome via remote interface. I just timeout.. Could it be some kind of IP ban?

**Comment by gravyboat** [comment]
@campones An IP ban seems likely, most of these sites (understandably) don't want people downloading their videos.
