### ISSUE TITLE
Windows: python processes of external http player stays forever

### ISSUE THREAD

**Issue by sebseb7** [streamlink/streamlink#1094]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

streamlink.exe url best --player-external-http --player-external-http-port 50000

works, but when I press CRTL-C it returns to the shell, but the python process is still there. 
...

### Environment details

Operating system and version: Windows7
Streamlink and Python version: 

$ streamlink.exe  --version
streamlink-script.py 0.7.0

------
$ python
Python 2.7.13 (default, Mar 13 2017, 20:56:15)
[GCC 5.4.0] on cygwin

**Comment by gravyboat** [comment]
I tested this real quick during lunch on my Linux machine with Streamlink 0.7.0 and Python 2.7.12 and couldn't duplicate it. Could you run with `-l debug` for some debug logging to see if there's anything else? Is anything connected to that port that could be keeping the connection open somehow?

**Comment by sebseb7** [comment]
was cygwin mingw mixup
