### ISSUE TITLE
Feature request: Accept any M3U8 without needing to identify a plugin

### ISSUE THREAD

**Issue by Joshfindit** [streamlink/streamlink#1095]
----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Simply allow processing a plain M3U8 file the same as it's processed once a plugin finds it.

**Cons**

- Is not entirely 'on mission'
- May need a special cli flag, which would be non-intuitive
- May need some re-writing at a deeper level if the logic of everything goes through plugins

**Pros**

- Allows users to use streamlink no matter the source instead of first deciding whether it's a supported stream or an M3U8
- The flag could be as simple as `--bypass-plugins`, which opens the door to other possibilities in future

### Reproduction steps / Explicit stream URLs to test

1. `streamlink http://stream1.shopch.jp/HLS/out1/prog_index.m3u8`
`error: No plugin can handle URL: http://stream1.shopch.jp/HLS/out1/prog_index.m3u8`
2. `streamlink http://video3.earthcam.com:1935/fecnetwork/4717.flv/playlist.m3u8`
`error: No plugin can handle URL: http://video3.earthcam.com:1935/fecnetwork/4717.flv/playlist.m3u8`
3. `streamlink http://200.75.19.171/uoct/13/playlist.m3u8`
`error: No plugin can handle URL: http://200.75.19.171/uoct/13/playlist.m3u8`

### Environment details

Operating system and version: OSX
Streamlink and Python version: streamlink 0.7.0, Python 2.7.10

**Comment by bastimeyer** [comment]
See the CLI documentation:
https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly

Example:
`streamlink "hlsvariant://http://video3.earthcam.com:1935/fecnetwork/4717.flv/playlist.m3u8" best`

**Comment by c769214** [comment]
this is ticket can be closed

**Comment by beardypig** [comment]
As @bastimeyer pointed out, this feature is already available. However you do need to use the `hls`/`hlsvariant` prefix depending on the type. It's not possible to make a plugin that would handle URLs that end in `.m3u8` because it could possibly conflict with an existing or future plugin.

**Comment by Joshfindit** [comment]
Most excellent, apologies for requesting a feature that already existed. ☺️

I see now that I could have been more thorough with the documentation.
Not sure if it's interesting or not, but maybe adding something to the error message like 'No plugin can handle URL: <url> Did you mean to play it directly? (link to documentation)'?

**Comment by scottbernstein** [comment]
Indeed.


It took me hours to wrap my head around the different protocols the first time I used livestreamer (now streamlink).  It would certainly make everyone's life easier if we noticed an *.m3u8 URL and defaulted to hlsvariant protocol (then falling back to hls if that fails) and HDS for a *.f4m url.  Failing that, a much more friendly / prescriptive error message would work

________________________________
