### ISSUE TITLE
Afreeca Timer problem

### ISSUE THREAD

**Issue by nOLanSea** [streamlink/streamlink#1099]
Hello.
Well, sometimes streams are opening with 15 seconds timer.
This problem was in livestreamer and fixed by this way https://github.com/chrippa/livestreamer/issues/982#issuecomment-123748593
Looks like the changes above are not compatible with streamlink.

Can anyone make fix for streamlink please?

Thanks a lot in advance.
Best regards.

**Comment by trocknet** [comment]
don't use vlc ,try mpc.

**Comment by tyu38** [comment]
I'm using streamlink to record video, not to watching.  When stream is recording, this errors make broken files.

**Comment by tenminute** [comment]
@tyu38 Which player are you using?
