### ISSUE TITLE
FoxSportsGo stream

### ISSUE THREAD

**Issue by jrhessey** [streamlink/streamlink#1107]
I am trying to grab streams from https://www.foxsportsgo.com/

I watch the network tab in chrome and I see a couple m3u8 files come up.  I've tried them all, but only the first one returns anything in the command line.  Below is the output for the command.  I'm not sure what I'm doing wrong with this one.  I've done a number of sports sites, but I can't figure this one out.

streamlink "hlsvariant://http://hlslinear-l3c.med1.foxsportsgo.com/token=exp=1500573790~id=a3e0302d-3e2b-4c1a-8065-5edd4dceed24-313973-4fb9a908bdd3d89b1985076fc6dc7c680a28d35b~hash=d025f9173fac5c9e4956c52d88afcafcd9f37659/ls02/foxsports/FOXSPORTS_LINEAR_107/live/master_wired_web_ads.m3u8" best -o "P:\tbot\foxsportsgo\foxsportsgo.ts"

[cli][info] Found matching plugin stream for URL hlsvariant://http://hlslinear-l3c.med1.foxsportsgo.com/token=exp=1500573790~id=a3e0302d-3e2b-4c1a-8065-5edd4dceed24-313973-4fb9a908bdd3d89b1985076fc6dc7c680a28d35b~hash=d025f9173fac5c9e4956c52d88afcafcd9f37659/ls02/foxsports/FOXSPORTS_LINEAR_107/live/master_wired_web_ads.m3u8

[cli][info] Available streams: 224p (worst), 288p, 360p, 504p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)

[stream.hls][error] Failed to create decryptor: Unable to open URL: https://media-api.foxsportsgo.com/programs/231745/keys/id/1651876 (401 Client Error: Unauthorized for url: https://media-api.foxsportsgo.com/programs/231745/keys/id/1651876)

[cli][error] Try 1/1: Could not open stream <HLSStream('http://hlslinear-l3c.med1.foxsportsgo.com/token=exp=1500573790~id=a3e0302d-3e2b-4c1a-8065-5edd4dceed24-313973-4fb9a908bdd3d89b1985076fc6dc7c680a28d35b~hash=d025f9173fac5c9e4956c52d88afcafcd9f37659/ls02/foxsports/FOXSPORTS_LINEAR_107/live/2017/07/05/19073123/3500K/3500_slide_ads.m3u8')> (No data returned from stream)

error: Could not open stream <HLSStream('http://hlslinear-l3c.med1.foxsportsgo.com/token=exp=1500573790~id=a3e0302d-3e2b-4c1a-8065-5edd4dceed24-313973-4fb9a908bdd3d89b1985076fc6dc7c680a28d35b~hash=d025f9173fac5c9e4956c52d88afcafcd9f37659/ls02/foxsports/FOXSPORTS_LINEAR_107/live/2017/07/05/19073123/3500K/3500_slide_ads.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...

Thanks for any help!

Windows 10 64bit
streamlink version 0.7.0

**Comment by beardypig** [comment]
Looks like you have to be logged in to see the streams. That probably means it's using an authentication cookie to get the decryption key. If you find the cookies that are being sent by the browser with the request to `https://media-api.foxsportsgo.com/programs/231745/keys/id/1651876` you should be able to send them with streamlink using the [`--http-cookie`](--http-cookie) option (you can repeat it multiple times for multiple cookies).

**Comment by jrhessey** [comment]
Thanks for your reply beardypig!  I've gone through the cookies for the url that is returned in the error with no luck, I get the same error.  I've never had to use this switch before, so I'm probably doing something wrong.

Below is the new try
![url-error](https://user-images.githubusercontent.com/28300132/28780744-d9f5f556-75d5-11e7-9c38-5ea1971dc42e.png)
Here is the url in the network tab of chrome
![url from cmd](https://user-images.githubusercontent.com/28300132/28780748-dd6c4316-75d5-11e7-9feb-a6990e724e38.png)
here are all the cookies being passed for that specific url
![cookies](https://user-images.githubusercontent.com/28300132/28780753-df488316-75d5-11e7-8915-9503cd775386.png)

Here is the command I've tried.

streamlink "hlsvariant://http://hlslinear-akc.med1.foxsportsgo.com/hdnts=exp=1501593687~acl=/*~id=a3e0302d-3e2b-4c1a-8065-5edd4dceed24-313973-4fb9a908bdd3d89b1985076fc6dc7c680a28d35b~hmac=db12f54798b9c91abd3f21c34c574fc75fab54ca35b0a37da1c9289858d61e96/d395b2fba6c513daaf4447669cba086a/ls02/foxsports/FOX_SPORTS_1/live/master_wired_web_ads.m3u8" best --http-cookie "cookie=*******" -o "P:\tbot\foxsportsgo\foxsportsgo.ts"

I tried both the authorization and access_token cookies.  Should I be trying something else?  I assumed it should be one of these, given the name of them.

**Comment by beardypig** [comment]
Did you try with both cookies? You might need a combination from all of them... 

```
streamlink --http-cookie "access_token=*******" --http-cookie "Authorization=*******" "hlsvariant://.....m3u8" best
```

**Comment by jrhessey** [comment]
That works!!

I wasn't using the actual cookie names...

**Comment by thehritzinator** [comment]
How can I view the request cookies tab shown in jrhessey screenshot above?

**Comment by asevcik** [comment]
Has anyone attempted to connect to a stream from foxsports.com/foxsportsgo.com recently. The workflow as shown here seems to have changed a bit.

I can sniff a link like the below:

https://content-ausw2.uplynk.com/100ef55af85e4fb69a55f3be9445c4a1/h.m3u8?pbs=23d295a860c84b9ebbd58621fb14b2cb

And can connect to it using just

streamlink "hlsvariant://https://content-ausw2.uplynk.com/100ef55af85e4fb69a55f3be9445c4a1/h.m3u8?pbs=23d295a860c84b9ebbd58621fb14b2cb" best -o output.mp4

without any http cookies. But every attempt will reach approximately 1.4 GB and then return:

$ streamlink "hlsvariant://https://content-ausw2.uplynk.com/100ef55af85e4fb69a55f3be9445c4a1/h.m3u8?pbs=23d295a860c84b9ebbd58621fb14b2cb" best -o output.mp4
[cli][info] Found matching plugin hls for URL hlsvariant://https://content-ausw2.uplynk.com/100ef55af85e4fb69a55f3be9445c4a1/h.m3u8?pbs=23d295a860c84b9ebbd58621fb14b2cb
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[download][output.mp4] Written 1.42 GB (28s @ 23.8 MB/s)                        [stream.hls][error] Failed to create decryptor: Unable to open URL: https://content-ausw2.uplynk.com/check2?b=100ef55af85e4fb69a55f3be9445c4a1&v=100ef55af85e4fb69a55f3be9445c4a1&r=h&pbs=23d295a860c84b9ebbd58621fb14b2cb (403 Client Error: Forbidden for url: https://content-ausw2.uplynk.com/check2?b=100ef55af85e4fb69a55f3be9445c4a1&v=100ef55af85e4fb69a55f3be9445c4a1&r=h&pbs=23d295a860c84b9ebbd58621fb14b2cb)

[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by gravyboat** [comment]
@asevcik If you're encountering issues please open a new issue and provide the full debug output (`-l debug`) as well as the items requested in the template, this issue is pretty old.

**Comment by cwondercheck** [comment]
could you guys re-look into this as it seems to be no longer working at least for me

**Comment by cwondercheck** [comment]
downloading seems to work just not playing into vlc

**Comment by gravyboat** [comment]
@cwondercheck Try a different player such as MPV and see if that fixes it. We've seen some weird VLC issues in the past release or two. If not then open a new issue with full debug output. I'm going to lock this one for now.
