### ISSUE TITLE
Restart livestream downloads automatically

### ISSUE THREAD

**Issue by theredmanor** [streamlink/streamlink#1108]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Many times when I'm downloading a livestream I left it running without supervision. At times, livestream download suddenly "ends" thinking that livestream is already over when it's not, for some reason.

So I'm requesting a feature to be able to automatically restart and retry a livestream download a set number of times with a set duration of time inbetween each tries, once it detects that livestream have "ended". 

This is catastrophic when you're archiving a critical livestream, as you can be missing a huge chunk of time from the recording.

Please do consider my suggestion!

**Comment by gravyboat** [comment]
We've answered this question several times before: https://github.com/streamlink/streamlink/issues/1064#issuecomment-313191707 has more details, but the gist is using https://streamlink.github.io/cli.html#cmdoption-hls-segment-attempts and https://streamlink.github.io/cli.html#cmdoption-hls-segment-timeout I'm going to close this out for now.
