### ISSUE TITLE
Please add external audio track feature

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#111]
I dig up here some interesting question feature from original project : https://github.com/chrippa/livestreamer/issues/1464

There are more and more streams with separated audio track(s) from playlist which results in a picture without audio. It would be great it this feature could be implemented in streamlink project.

**Comment by beardypig** [comment]
I haven't looked, but as it's an HLS stream it's probably mpeg ts, which is a pain to mux. One workaround is to use the `--player-passthrough hls` and get VLC to handle it. Another option would be to add support for `ffmpeg`/`avconv` to mux streams - but that adds a dependency to `ffmpeg`.  
It might be worthwhile adding optional `ffmpeg` support to allow this...

**Comment by karlo2105** [comment]
Streamlink is just transporter not player itself. 
VLC 3.0 can handle multiaudio streams so streamlink should only be adapted with feature to forward multiaudio channels to vlc.

**Comment by beardypig** [comment]
I'm not suggesting that streamlink play the stream...  Only to use ffmpeg to mux the separate streams. Wouldn't it be better to support other players, not just VLC?

**Comment by karlo2105** [comment]
If you want to watch with other player there is a switch streamlink -p "other player playpath" "stream address" best

**Comment by beardypig** [comment]
I understand that. How do you suggest support multiple audio streams in streamlink?

**Comment by TheSneakySniper** [comment]
Take a look at this: https://github.com/senko/python-video-converter

**Comment by beardypig** [comment]
@TheSneakySniper yep, something like that :-) The downside is that you have to have ffmpeg installed separately :-)

**Comment by karlo2105** [comment]
In the beginning it would be great if streamlink could have feature to add manually audio track to stream address which includs separate audios. I don't think we would need ffmpeg for that.

**Comment by beardypig** [comment]
How do you mean @karlo2105? Do you have an example of how you would want it to work?

**Comment by karlo2105** [comment]
If I had examples I would just give them. I suppose VLC deals with it through libavcodec (ffmpeg).

**Comment by beardypig** [comment]
@karlo2105 do you have any examples of external audio streams (other than the francetv stream mentioned in chrippa/livestreamer/issues/1464), it would be useful for testing. Thanks.
