### ISSUE TITLE
9anime.to | Unable to validate JSON: Key 'grabber' not found in {u'error': u'token'}

### ISSUE THREAD

**Issue by sucht** [streamlink/streamlink#1110]
getting the following error with the newest streamlink,

streamlink https://9anime.to/watch/detective-conan.myz/9jo760 best
[cli][info] Found matching plugin nineanime for URL https://9anime.to/watch/detective-conan.myz/9jo760
error: Unable to validate JSON: Key 'grabber' not found in {u'error': u'token'}

**Comment by beardypig** [comment]
9anime.to have added some pretty clever anti-stream grabbing code - might be a while before this plugin works again :)

**Comment by deathsec** [comment]
Hey think i got the idea , look at the raw header.

https://9anime.to/ajax/episode/info?ts=1507888800&_=2574&id=pmk29q&server=30&update=0

ts = unknown
_  = unknown
id = episode id
server = 30 
update = 0

where ts and _ are the unknowns which i have no idea where it comes from.
even cross checked with the time stamp but still no use..

Any ideas @beardypig ?

**Comment by deathsec** [comment]
also found what is ts parameter.
its present in the body tag of the specific page
 <body class=" minimal" data-ts="1507892400">

**Comment by simonsankar** [comment]
Hey guys! Any luck on figuring out what the _= is, and how we get it? What I've gathered so far is that its some token for each episode/server combo and is unique to that episodeID. I've succeeded with scraping everything else, just this one token is holding up my electron app. :(

**Comment by beardypig** [comment]
I think we should close this as "won't fix". 9anime.to hosts videos on multiple other platforms that we do not support and some that require captchas, etc. If you are determined you can reverse engineer the JavaScript that protects the links quite easily.

**Comment by gravyboat** [comment]
@beardypig Agreed.

**Comment by beardypig** [comment]
Yeah, it’s marked as broken right now, but we can remove it :)
