### ISSUE TITLE
chaturbate (fixed, please close)

### ISSUE THREAD

**Issue by whitetop** [streamlink/streamlink#1111]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Chaturbate has changed their player, i have read on stream-recorder site that they changed it and no script works due to it, its got many settings and is said to have 2 players.
...

### Expected / Actual behavior
a fix for the updated players chaturbate did, script worked great till about 2 weeks ago due to the update they did on the site.
...

### Reproduction steps / Explicit stream URLs to test

1. changing code
2. testing other scripts to rip streams
3. tried the m3u8 links and still comes up can't find the model

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

latest one.

### Comments, logs, screenshots, etc.
http://i.imgur.com/0MQISc0.jpg
...

**Comment by back-to** [comment]
Not sure what your script there is,
but **streamlink** does only use **HLS** streams from chaturbate.

The script still works.

You can watch every **FREE** stream with **streamlink**

```
[Streamlink for Windows v0.7.0 - Git 5f658c8]
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/...
[cli][info] Available streams: 240p (worst), 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
```

**RTMP** streams **won't get added** because it won't work with the current rtmpdump version in streamlink

**Comment by karlo2105** [comment]
Why not use ksv patched version of rtmpdump or update streamlink rtmpdump with ksv patches which are available ?

**Comment by 0880** [comment]
Waste of time. Flash is dead.

**Comment by whitetop** [comment]
Sorry for late reply, email went to my spam folder.
I use this script and it worked great and fast.

> @echo off
setlocal enableDelayedExpansion

set USERNAME=topman666
set PASSWORD=pbkdf2_sha256$24000$gjxG9H2k353E$5WKLz1tLO5I5V03stM9MAVNyXPPofmh/cRURFflwPNs\u003D
set CB_VERSION=9
set OUT_DIR=captures
set SECONDS=15

set /p model=Enter username: 
set model=%model:https://chaturbate.com/=%
set model=%model:/=%

if not exist %OUT_DIR% (mkdir %OUT_DIR%)

for /L %%i in (1,1,99) do (
  set N=!time:~9,12!
  set /a N=10000!N! %% 10000
  set rand=!random!
  set /a rand=!rand!* 31/32768+1
  set /a rand=!N!+!rand!
  set /a rand=!rand!*31/131+1
)
set server=edge%rand%

:doCapture
set ts=%date:/=-%_%time::=-%
set ts=%ts: =%
set output=%OUT_DIR%\%model%_%ts%.flv
set PASSWORD=%PASSWORD:\u003D==%

color 2F && title %model% @ %time% - %server%
cls && echo Capturing: %model% @ %time% - %server% && echo.

rtmpdump --live --timeout 20 ^
-r "rtmp://%server%.stream.highwebmedia.com/live-edge" ^
-p "http://chaturbate.com/%model%" ^
-C S:%USERNAME% ^
-C S:%model% ^
-C S:%CB_VERSION% ^
-C S:%PASSWORD% ^
-y "playpath" -o %output%

for %%r in (%output%) do (
  if %%~zr lss 1 del %output%
  color 4F && title %model% - OFFLINE
)

set /a rand=%random%*31/32768+1
set server=edge%rand%

timeout %SECONDS%
goto doCapture

>

**Comment by back-to** [comment]
First **you are not using** https://streamlink.github.io/install.html,
so it's **irrelevant to this github project**.

---

Second your script works for me,
I used the **username** and the **password hash** from the website _(html code)_

try it with the login from the website _(html code)_

_AnonymousUser_ or _a useraccount_ both worked for me

```js
<script type='text/javascript'>
    $(document).ready(function() {
        
            if (HasFlash() && ('False' == '' || 'False' == 'False')) {
    EmbedViewerSwf(
        "/static/flash/CBV_2p670.swf",
        "laila_lorenn",
        "SERVER     ...stream.highwebmedia.com",
        "/xml/viewer.xml",
        "0",
        "login_required_true_if_loggedin",
        "0",
        "https://ssl-ccstatic.highwebmedia.com/flash/playerProductInstall.swf",
        "YOUR USERNAME", <------------------------------------------------
        "$.mydefchatconn('join_group_show')",
        "$.mydefchatconn('spy_on_private')",
        "registration_required()",
        "123",
        "https://ssl-ccstatic.highwebmedia.com/images/flashwatermark.png",
        "",
        "YOUR PASSWORD HASH", <------------------------------------------------
        "ABCABCABCABCABC",
        "123",
        "123",
        "123",
        "{\u0022username\u0022:",
        "123"
    );
}
```

**Comment by whitetop** [comment]
@back-to i used streamlink but that code is very simple so i never posted it, i just posted the single filed one above, but this is to do with the project as i get the same error while using streamlink.

I'll try the code you posted (i did edit my login out of the code i posted)

**Comment by back-to** [comment]
well if you used streamlink, post the error that you get from it

```
streamlink -l debug https://chaturbate.com/... best
```

but like i said your script work, streamlink works.

---

most likely your login is wrong or the channel is geo blocked for you.

The code that i posted is the way to find the login data from the website, 
if you inspect the html code in your Browser.

**Comment by AshleyUK1984** [comment]
Hi,
I also appear to be having an error with Streamlinks Chaturbate plugin.

Here is a picture of my error.

http://img29.imagetwist.com/i/16728/yze36a9tic78.PNG/chatur.PNG

Any help appreciated.
Thanks

**Comment by johnthecracker** [comment]
@ 0880,

A word about rtmp..

You were on stream-recorder forum ( nullacht ) before I was.

Numbers on that forum are speaking for themselves.

See how many posts are on rtmpdump and adult streaming videos forums = rtmp.

Take it away and stream-recorder forum is 50% smaller.

Each and every cam site runs on rtmp and hls in paralel on some sites.

I'mLive was booted from old rtmp host, now is on a new host and runs 2 rtmp streams
in parallel in addition to hls. Rtmp not dead yet.


By the way, why aren't back on stream-recorder?

I started streamlink thread ( j_cool ) and not a word from you.

You could give streamlink thread there at least "sticky" label 
as you did to livestreamer and youtube-dl.

**Comment by beardypig** [comment]
@whitetop you should be able to close an issue you created, but I can close it too :)

**Comment by whitetop** [comment]
@beardypig I tried too but it would not let me, the fix was i updated the rtmpdump so when i put the 2013 one back (once i found it) all worked.

**Comment by johnthecracker** [comment]
A lot of useless discussion could be moved from this forum to another forum:

If you want to consider more focus on the project and less on rtmp and what else you think less relevant,

I have a suggestion:

Post very visible link and find suitable description to shift some discussion there.

to streamlink from j_cool:

http://stream-recorder.com/forum/streamlink-up-date-fork-livestreamer-t22646.html
