### ISSUE TITLE
Don't require pycryptodome to build. 

### ISSUE THREAD

**Issue by Aonavan** [streamlink/streamlink#1112]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I can't build pycryptodome just with pip, i need to install python-dev and gcc and all dependencies from those just for this, can you make it recommended like rtmpdump? Only a few plugins need this.

**Comment by bastimeyer** [comment]
See the install documentation:
https://streamlink.github.io/install.html#using-pycrypto-and-pycountry

Or setup.py:
https://github.com/streamlink/streamlink/blob/0.7.0/setup.py#L28-L33

**Comment by beardypig** [comment]
It's for the greater good, it's easier (for us) to include it than to exclude it. The easier it is for us to maintain the better it is for everyone, in general. You can use `pycrypto` as @bastimeyer pointed out, which is probably available in your distro's package manager.

**Comment by gravyboat** [comment]
I'm going to close this out, we've had this discussion previously and the workaround is pretty easy.
