### ISSUE TITLE
Dailymotion parsing error

### ISSUE THREAD

**Issue by BjkGkh** [streamlink/streamlink#1114]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Since Dailymotion updated their website, player... streamlink seems to not working anymore and throws a parsing error.

### Expected / Actual behavior

Not working anymore

### Reproduction steps / Explicit stream URLs to test

1. Open a dailymotion live stream.

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: Last version for both.

### Comments, logs, screenshots, etc.

https://puu.sh/wSHA9/99230ea948.png

**Comment by back-to** [comment]
update your streamlink

https://github.com/streamlink/streamlink/releases/tag/0.7.0

if was fixed here #974

**Comment by BjkGkh** [comment]
Thank you it's working! Really appreciated, i was sure i had the last version...
