### ISSUE TITLE
Migrating from Livestreamer CLI to StreamLink CLI 

### ISSUE THREAD

**Issue by AshleyUK1984** [streamlink/streamlink#1116]
Hi,
This isn't an issue as such, but a request for a little bit of help.

So I've been using Livestreamer for the best part of probably 1 1/2 years, and it's been working fine - but I understand that sooner or later I need to make the jump to StreamLink because it's no longer supported as such.

I download streams using the command prompt window _(I'm just using one of my automatic batch scripts)_.
My script uses the following command to start downloading a stream.

"C:\Program Files (x86)\Livestreamer\livestreamer.exe" https://chaturbate.com/<Models Username>" / best -o E:\DownloadVids\<Models Username>" & ".avi")

This get's the job done. 
But now that I'm looking at Streamlink, I don't seem to have a **Streamlink.exe** file? Like I do with livestreamer.exe - So which file should I point to?

Thanks

**Comment by beardypig** [comment]
I take it you already installed Streamlink? Did you use the Windows installer, or some other method? If you used the installer then `streamlink.exe` should have been added your your `%PATH%` which means you should just be able to use `streamlink.exe` with not extra path information. However, if that doesn't work you should find `streamlink.exe` at `"C:\Program Files (x86)\Streamlink\bin\streamlink.exe"` :)

**Comment by AshleyUK1984** [comment]
Hi beardypig.
Yeah I used the Windows installer.

I could have swore I checked every folder within "C:\Program Files (x86)\Streamlink" for the "streamlink.exe" file... but obviously not. 

I found it in the bin folder as you mentioned above.

Thanks for your help, and sorry for my dodgy eyesight lol.

**Comment by beardypig** [comment]
No problemo.
