### ISSUE TITLE
Chaturbate Plugin Not Working

### ISSUE THREAD

**Issue by AshleyUK1984** [streamlink/streamlink#1118]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Hi,
I appear to be having an error with Streamlink's Chaturbate plugin.

I'm using Streamlink's CLI
Here is a picture of my error.

http://img29.imagetwist.com/i/16728/yze36a9tic78.PNG/chatur.PNG

Any help appreciated.
Thanks

Expected / Actual behavior

Picture of error above

### Reproduction steps / Explicit stream URLs to test

From command Prompt, enter this:
"C:\Program Files (x86)\streamlink\bin\streamlink.exe" https://chaturbate.com/<Username of model>/ best -o C:\RecordedVids\<Username of model>.avi"

### Environment details

Operating system and version: Windows Server 2012 R2
Streamlink 0.7.0 _(Using the latest version of Streamlink's Windows binaries (todays date - 26/07/2017))_

### Comments, logs, screenshots, etc.

Picture of error
http://img29.imagetwist.com/i/16728/yze36a9tic78.PNG/chatur.PNG

Thanks

**Comment by AshleyUK1984** [comment]
Hmmmm, seems like it works on my personal computer. But not on the server machine that I have?? Any ideas why that is?? Do you think the server machine has been blocked or something?

**Comment by beardypig** [comment]
Could be blocked, some sites do block VPN and VPS providers. I assume your server is remotely hosted? A VPS perhaps?

**Comment by AshleyUK1984** [comment]
Yeah it's a server that rent over in a NL datacenter. I connect to it remotely.
I've been on that server for probably nearly 2 years. Constantly downloading the streams etc. So I suspect that they've had enough and banned it finally. :( I'll have to look for another provider.

Thanks

**Comment by beardypig** [comment]
If you curl the URL from the server is there any additional message in returned? Or does it just give you the standard 403 message?

**Comment by AshleyUK1984** [comment]
The website loads OK. But the stream itself just won't load.

In Internet Explorer the website loads, but the stream doesn't appear at all.
In Google Chrome the website loads, and one frame of the stream is shown, but then an error appears

### Screenshots - NSFW!!!

**Internet Explorer:** 
http://img117.imagetwist.com/i/16734/frqhgf1c1kzb.PNG/IE.PNG

**Chrome:** 
http://img117.imagetwist.com/i/16734/aqxmgupm5m9n.PNG/chrome.PNG

Not sure if you've seen any of these errors before?

**Comment by back-to** [comment]
your IP is most likely blocked,

you could try to open this url's in your browser, see if this works

- http://highwebmedia.com **NSFW**
- http://stream.highwebmedia.com **NSFW**
- http://edge.58stream.highwebmedia.com/ **NSFW**

---

for streamlink you could **try** to add a header

```
streamlink https://chaturbate.com/.../ best --http-header X-Forwarded-For=8.8.8.8
```

_you can change the IP_

---

if none of this works, you would need a new IP probably

**Comment by AshleyUK1984** [comment]
Hi,
All websites open fine, but when I try to play a stream it gives me the same errors as previously mentioned.
I also tried the header option as you suggested, but unfortunately it didn't work.

Thanks anyway.
Sounds like I need a new IP.

**Comment by back-to** [comment]
since you can open highwebmedia.com in your browser,
can you open the stream url itself

_you can get it with_
```
streamlink https://chaturbate.com/.../ best --stream-url
```

it should be something like this in a txt editor
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:5946
#EXTINF:2.0,
media_w10279712 ...
#EXTINF:2.0,
media_w10279712 ....
#EXTINF:2.0,
media_w10279712 ...
```

this is maybe the better way to see if you are blocked or something else is wrong with your system

**Comment by AshleyUK1984** [comment]
Nope, I'm getting the same errors here too.
Here's a screenshot to help you see what I'm seeing.

http://img163.imagetwist.com/i/16747/egfc84ub4p5p.PNG/streamerror.PNG

On a side note, I've just ordered an extra IP Address. So once that takes effect, we can see if that resolves the issue or not.

**Comment by AshleyUK1984** [comment]
Just to give you an update.
It turns out that it was an IP Range ban.
Another server ordered, and all is good now. :)

Appreciate the support.
