### ISSUE TITLE
Piczel.tv support

### ISSUE THREAD

**Issue by Ketsuban** [streamlink/streamlink#112]
This is [something I requested](https://github.com/chrippa/livestreamer/issues/1205) when this was livestreamer, and the author made a little headway in determining that it defaults to HTTP-DASH but there's also a HLS stream available. I've since switched over to streamlink.

**Comment by Brainzyy** [comment]
Try this: https://raw.githubusercontent.com/intact/livestreamer/fe7bd9fc6ba50450e57af6dcd76cfe2400fb5ddc/src/livestreamer/plugins/piczel.py

But change every instance of "livestreamer" into "streamlink"

**Comment by Ketsuban** [comment]
Yeah, I got the notification when they posted it on the linked issue. I'll let you know how it goes the next time I watch something on Piczel.
