### ISSUE TITLE
New Streamlink logo

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#1123]
We had this discussion before in November 2016 (#179), but now since we're about to release `1.0.0` (#1115), we need a non-temporary and professional logo that fits Streamlink.

This is the current, temporary one:
![current Streamlink logo](https://avatars0.githubusercontent.com/u/22243823?v=4&s=200)
https://github.com/streamlink/streamlink/blame/0.7.0/docs/index.rst#L17
https://github.com/streamlink/streamlink/blob/0.7.0/NOTICE#L51-L102 

Suggestions and examples are welcome, but please only post stuff that is reasonable and doesn't violate any licenses.

If you are a graphics designer with a little bit of experience who wants to help out, please let us know.

Thanks a lot!

**Comment by gravyboat** [comment]
It's worth noting we should definitely pay whoever we get to do this art. We have some money available via Bountysource we can cash out to whoever does the work.

**Comment by bastimeyer** [comment]
@gravyboat 
I've just asked a friend who's a graphics designer and who I have worked with for several years. He would be interested in creating a new logo, but this depends on the time frame and payment. He asked me to get back to him once I know how much we are willing to spend and that the payment depends on the time frame. If we don't find anybody else, he'd be willing to help us with a new logo.

**Comment by gravyboat** [comment]
Sounds good, I'll approach my friend only if we really need him, he's super busy so I don't know if he realistically has time to take on this kind of project. We've got ~$70 USD to cash out from bountysource after fees and everything, which is definitely low for logo design.

**Comment by cdrage** [comment]
i like doggo

j/k

Yeah, a new logo would be better to reflect the project and show our professionalism, of course.. logo's are a hell-of-a-lot for design. If someone is willing to donate their time and help-out that'd be great! :100:

**Comment by c-r-r1983** [comment]
font and image are free for commercial use

http://i.imgur.com/Sf92y9x.jpg
http://i.imgur.com/VYL83pF.jpg

its a simple design and not too busy. Colours and font can be changed to suit whatever style you want

i personally like the 2nd logo the best

**Comment by gravyboat** [comment]
I've responded with this tweet for a potential lead for logo design, with an offer to pay of course: https://twitter.com/failvarez/status/900538321910210561

**Comment by jimaek** [comment]
Hey, if would be very helpful if you wrote here the requirements for your logo. What style you want, text, colors, examples of logos you like...

**Comment by gravyboat** [comment]
Thanks @jimaek. I'll provide some general ideas and then hopefully @bastimeyer, @beardypig, @cdrage  and @RosadinTV plus anyone else interested can weigh in.

Style wise I think something minimal would be the preference, this needs to work as both a logo, and a something that can scale down for being listed in menus so the simpler the better.

I personally don't see any reason for text, we have a very international audience so I would prefer a relatively universal design that looks in place on many operating systems/language setups over anything with text.

Color wise I'm not really sure here and would prefer others weigh in as I don't care a ton as long as it isn't garish.

Examples:

<img src="https://lh3.googleusercontent.com/uYQLNHtuzLKnyCFUA5CeAqaO6EcsTHXl6kI9D4xc1Rp67cxoTjXuvIJUycSLl2rLXw=w300" width="128"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/500px-Spotify_logo_without_text.svg.png" width="128"> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Wikimedia-logo.svg/2000px-Wikimedia-logo.svg.png" width="128"> <img src="http://vignette3.wikia.nocookie.net/logopedia/images/6/6f/Mozilla_Firefox_%282004-2005%29.png/revision/latest?cb=20160930224412" width="128">

**Comment by WolfganP** [comment]
Interesting times... another project I'm currently following also entered into a new icon selection recently (https://github.com/qbittorrent/qBittorrent/issues/6467 interesting issue to watch for style discussions)

**Comment by gravyboat** [comment]
@jimaek It doesn't seem like anyone else is going to weigh in, what else can I provide you with to help this along?

**Comment by jimaek** [comment]
Hey, I will able to start next Monday on this project and prepare a few drafts. Let me know if you can wait.

**Comment by gravyboat** [comment]
We're not in any rush. We've got about 70 USD we can pay out to you via bitcoin or a few other means, so we'll need details on where to send that eventually please.

**Comment by jimaek** [comment]
Ok, then I will provide a few drafts when they are ready. If you don't like them then you say so and we stop all work. If you like them and want to continue working then you will provide more feedback and I will keep sending different versions until you like something.

Also can we do the initial versions via private email before publishing anything here? I don't want people to judge half-finished work.

I don't want any money but I will ask for you to add a mention of https://prospectone.io/ in your readme and website.
Sounds good?

**Comment by gravyboat** [comment]
@jimaek Unfortunately one of the big things on this project is trying to keep discussion open as we step through processes so doing the drafts privately via email would be a no go for us. I also can't make a unilateral decision regarding the mention of your site on the readme and website but I don't think most of the maintainers (myself included) would be interested in doing that. This is one of the reasons regarding why we were trying to offer payment and our concerns up above about the costs involved past what funds are currently available. We'll see if anyone else has an opinion on this but I will apologize in advance for wasting your time @jimaek.

**Comment by jimaek** [comment]
When dealing with a community it makes things much harder and takes a lot more time.
Since you don't have to impress and listen for comments/changes from 1-2 people but from 10,50,200... 
And since we do this as a promotion for the company its important to optimize time spent, I hope you understand. 

So let me know what you think and what we should do next. Its not a problem if you cant do it, I totally understand

**Comment by bastimeyer** [comment]
Sorry for the late response(s), I've been busy with other stuff, was therefore unavailable and had to take a break from any Github related stuff.

----

I personally have nothing against referring to the logo creator's website instead of paying a couple of bucks. It is an open source project and a new logo contribution should be possible under its currently used license. The Streamlink project has to be the owner of the new logo though, no matter whether it was paid for or not.

I don't think that adding more links is a good idea. We're already linking to the creator of the current template logo on multiple locations and only those should be replaced, namely the top of the [index page of the Streamlink website](https://github.com/streamlink/streamlink/blame/0.7.0/docs/index.rst#L17), [NOTICE](https://github.com/streamlink/streamlink/blob/0.7.0/NOTICE#L51-L102) and [win32/LICENSE.txt](https://github.com/streamlink/streamlink/blob/0.7.0/win32/LICENSE.txt#L666-L717).

Regarding sharing first impressions of the logo design process, we could use the internal Streamlink IRC channel on Gitter, which is only accessible for members of the Streamlink github organization and explictly invited people (if anyone wants to complain here about Gitter, Gitter is now open source and owned by Gitlab).

**Comment by RosadinTV** [comment]
Sorry for the extreme late response.
In terms of style i agree with @gravyboat, something minimal without text.
Another idea could be using a mix of font-based open source icons (like [Material Icons](https://material.io/icons/), [Font Awesome](http://fontawesome.io/) or [IcoFont](http://icofont.com/))

**Comment by RosadinTV** [comment]
For example:
https://user-images.githubusercontent.com/13382316/30619070-c306bc3e-9d73-11e7-92de-d8662e25634b.png
A combination of "tv" and "link" using Material Icons, the possibilities are almost endless.

**Comment by gravyboat** [comment]
We've come to an agreement with an artist for the above logo since no one had concerns at a cost of about 65 USD after conversion which will be paid out via our opencollective.

**Comment by gravyboat** [comment]
Logo design has been paid for via Open Collective here: https://opencollective.com/streamlink/expenses/5259. Thanks to all our backers for making these sorts of expenses payable!

**Comment by cdrage** [comment]
@gravyboat 

This is wicked!! :) 

Let's update the org: https://github.com/streamlink and wherever else the logo is being used.

Good job everyone :+1: :100: :100: :100:

**Comment by cdrage** [comment]
I think we should also add the logo on the main homepage (above the "Streamlink" title) https://streamlink.github.io/

**Comment by gravyboat** [comment]
@cdrage Agreed, we're finalizing things up with the logo now and getting the correct formats needed, etc.

**Comment by bastimeyer** [comment]
Ok, cool, sounds good. Let's get the logo as an SVG once it's ready so we can automatically build the rasterized images ourselves. There really is no need to add rasterized images to the repo, especially ICO files. The necessary steps for building them can be added to the docs makefile and makeinstaller script. External PNGs can be built locally and are not needed in the repo.

----

This is what's needed (I think):

- Github / Opencollective / etc
  - png 500x500
- Streamlink website
  - main menu / general purpose
    - svg
  - favicon (it's a mess... every time...)
    https://github.com/audreyr/favicon-cheat-sheet
    - ico that embeds a 16x16 and 32x32 32bpp icon
    - png 152x152
    - png 32x32
    - png 16x16
    - svg
- Windows installer
  - ico that embeds a 16x16, 32x32, 48x48 and 256x256 32bpp icon
  - maybe even a png (or bmp?!) for the installer GUI

----

Building the ico files can very easily be automated, so that no files of this stupid format need to be added to the repo:
```bash
# inkscape, optipng and imagemagick should all be available on the Ubuntu version that TravisCI is using
for size in 16 32 48 256; do
  inkscape --no-gui --export-png="icon-${size}.png" -w ${size} -h ${size} icon.svg
  optipng -o7 -out "optimized-${size}.png" "icon-${size}.png"
done
convert optimized-{16,32,48,256}.png icon.ico
```

**Comment by bastimeyer** [comment]
Btw, we should publish a new stable release when this gets resolved. It's overdue...

**Comment by bastimeyer** [comment]
Any news regarding the status of the final logo?

**Comment by gravyboat** [comment]
The logo was finalized and the logo has been paid for. @beardypig and I discussed it about a week and a half ago but haven't done so since then.

**Comment by bastimeyer** [comment]
@gravyboat Let's get this done and publish a new stable release...

**Comment by gravyboat** [comment]
@bastimeyer Agreed. I updated the image on GitHub and Opencollective so we can mark those off the list. I've also converted the PNG to an SVG for use in the above formats (I can't attach it here because the file tyep is unsupported unfortunately).

**Comment by beardypig** [comment]
There is no original `svg`, it was not a vector to start with but a raster from Photoshop. There was an `svg` version, but it's just a base64 encoded png embedded in an `svg`. :)

**Comment by bastimeyer** [comment]
Only having a rasterized version is quite disappointing for a logo design... :disappointed:

**Comment by bastimeyer** [comment]
@gravyboat @beardypig Can one of you upload the icon in a higher res please? I want to see if I'll be able to properly vectorize it...

**Comment by gravyboat** [comment]
@bastimeyer How about this? I can send it to you if you want too.
![streamlink](https://user-images.githubusercontent.com/1396878/48523268-97f09200-e830-11e8-8638-00fa4fbe3235.png)
