### ISSUE TITLE
plugin request : artv.watch 

### ISSUE THREAD

**Issue by c769214** [streamlink/streamlink#1124]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

http://artv.watch/countries/japan/
URL Link (A) : http://artv.watch/countries/japan/nhk-general-tv-nhk%e7%b7%8f%e5%90%88/
or 
URL Link (B) : http://artv.watch/countries/japan/music-japan-tv/

after you open the link (A) ... it will generate the m3u8 link : 
link 1
http://162.244.80.80/jp-nhkgeneraltv/index.m3u8?dvr=false&token=a78d321e1bd94ea71d997e358341447935553908-0de3d27ef88f7b88c2a641e32c0956bd-1501219147-1501197547

then 
link 2 
http://162.244.80.80/jp-nhkgeneraltv/tracks-v1a1/index.m3u8?token=a78d321e1bd94ea71d997e358341447935553908-0de3d27ef88f7b88c2a641e32c0956bd-1501219147-1501197547

you can play via vlc with link 2 
but the token will change after several moments 

hope any guys to write a plugin for this website 

thanks !

**Comment by xemles** [comment]
Mh. No. I'm the owner of this website. It is free and I host it on my own servers. So please, don't do that because if you use that, my website will not be able to exist. (Sry for my english)

**Comment by gravyboat** [comment]
@xemles It appears you offer people a paid way to watch via VLC anyways so it seems like this would just be bypassing your setup. Can you pipe directly to VLC with what you have configured or is it KODI only? Would doing something like requiring a username/password be an acceptable way to do this to ensure only paid members are using the plugin?

**Comment by xemles** [comment]
But I can only pay my server with Subscriptions and ads on the website. Server costs around 1000$ per month for me so I can't permit something like that

**Comment by gravyboat** [comment]
@xemles I understand, that's why I was asking if only paid subscribers have logins or something to use your current VLC viewing process. If that isn't the case then we'll close this issue so you don't have to worry.

**Comment by xemles** [comment]
My subscribers have others links. It's not the website links. They have unique access ^^

**Comment by gravyboat** [comment]
Okay, we'll close this out then. @c769214, @xemles (owner of this site) has informed us they can't afford to continue running the site and has requested we do not support it, as such I am closing this out.
