### ISSUE TITLE
Youtube: Streams frozen and videos stopping too early

### ISSUE THREAD

**Issue by Crazy-KSK** [streamlink/streamlink#1125]
### Checklist

[Bugreport]

OS: win 7
Streamlink: beta version downloaded just now

1. 
All of these streams only show one frozen frame.
https://www.youtube.com/watch?v=TX-5Zwwji2A
https://www.youtube.com/watch?v=pWKBKzYA5fI
https://www.youtube.com/watch?v=7ntymKt-H0M
https://www.youtube.com/watch?v=ylESQLowUT0

2.
Youtube videos all seem to end a few seconds too soon it can turn into a few minutes on hour long videos and more if you have paused at any point.

3.
Oh and it would be nice if you could have it ignore anything after the initial part of the link so it doesn't error when the link has " &index=2&list= " etc at the end of it.

**Comment by beardypig** [comment]
1. Which player are you using? I would guess VLC2, try it with VLC3 or a different player and see if you have the same issue :)

2. I have also noticed this. I think it might affect all VOD stream types when not writing to a file. I will try and nail down exactly why this happens. It is likely because the stream ends, the streamlink process terminates, and the pipe that was transporting the data to the player is destroyed. This needs investigation. 

3. I don't have this issue; https://www.youtube.com/watch?foo=1&v=TX-5Zwwji2A&foo=2&foo=4 works just fine for me.

**Comment by skulblakka** [comment]
>I think it might affect all VOD stream types when not writing to a file.

I haven't looked at it right now, but I remember with livestreamer the problem was simply that it would close the player together with itself when it reached the end of a VOD. You had to use the `--player-no-close` option to prevent this.

**Comment by Crazy-KSK** [comment]
switching from VLC 2.2.5 to 3 fixed issue 1

could issue 3 be related to the way win 7 cmd differs from win 10? I assume you are on 10?

**Comment by beardypig** [comment]
Does it work if you put " around the URL? I use macOS and Linux, I haven't actually tested it on Windows 10 or 7 :-)

**Comment by Crazy-KSK** [comment]
Ah thats it! I'm only used to needing that with spaces in file names so I never thought of that. Thanks =)

If it isn't much hassle could you maybe change it so the plugin considers all input urls on windows as having " " around them? (then again that might cause issues in other cases idk)

**Comment by bastimeyer** [comment]
> could you maybe change it so the plugin considers all input urls on windows as having " " around them?

This is not how it works... The Windows command shell is responsible for parsing and tokenizing your input which is then passed on to Streamlink. Ampersand characters and many others need to be escaped or the whole parameter needs to be quoted.
https://stackoverflow.com/a/16018942

The Windows command shell and the Windows batch scripting is a total mess and absolutely ridiculous. This is part of the reason why software is being developed on Unix based systems.

**Comment by Crazy-KSK** [comment]
I see =/

**Comment by omperus** [comment]
Problem 2 happens on Periscope streams too.

**Comment by beardypig** [comment]
I think @skulblakka, not sure if there is a simple fix - but, `--player-no-close` should do it.

**Comment by c769214** [comment]
I have talked about this issue before....
If you using linux you can try to use the following command (just change the youtube URL link to yours and you need ffmpeg and VLC installed ):

`streamlink -O https://www.youtube.com/watch?v=kfTq_A9nBM0  best | ffmpeg -i - -vcodec copy -tune zerolatency -acodec copy -preset fast -f mpegts - 2>/dev/null | vlc -
`

I don't know how to "convert" the above command in windows environment....see if any guys helps ....

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/7f1492595613442869ea1d2a5e519b5a34f687f1/src/streamlink_cli/output.py#L164

changing this to `self.player.communicate()`

https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate

**would let the player play the full video.**

easily testable with a short video.

_currently streamlink won't even open the video._

but i don't know if this changes something for `--player-fifo` or `--player-http`

**Comment by amurzeau** [comment]
@back-to 
Does't the "player-no-close" already do a similar behavior, waiting the player to close before closing streamlink ?

**Comment by back-to** [comment]
true, i did only test it with mpv and it had a different behavior than vlc.

mpv always closes the player

---

https://streamlink.github.io/cli.html#cmdoption-player-no-close

```
By default Streamlink will close the player when the stream ends.
This is to avoid "dead" GUI players lingering after a stream ends.

It does however have the side-effect of sometimes closing a player
before it has played back all of its cached data.

This option will instead let the player decide when to exit.
```

Closing this issue,
**because it is intended to close the player immediately,
so it's more of an feature than a bug**.

`--player-no-close` should be used, if someone wants to watch the last seconds of a video.
