### ISSUE TITLE
Plugin request: vipbox.nu

### ISSUE THREAD

**Issue by systemsz** [streamlink/streamlink#1126]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

is it possible to have a plugin for https://www.vipbox.nu/

http://www.vipbox.nu/american-football/17387/1/espnu-live-stream-online.html

M3u8: http://ak-hls-brs-espnu.espn.go.com/hls/live/203627/p/espnu-p-3500/espnu-p-3500.m3u8

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

Recommend Ablocker due to pop ups.

**Comment by lki2019** [comment]
http://ak-hls-brs-espnu.espn.go.com/hls/live/203627/p/espnu-p-4500/espnu-p-4500.m3u8

AES-128,URI="https://broadband.espn.go.com/espn3/auth/espnnetworks/m3u8/v1/generateKey?channel=espnu&kid=/espnu-p_072517_221809929_244.key

Get the key file to download down, and then decrypt.

Key file seems to need cookies can be downloaded down?

**Comment by back-to** [comment]
same as https://github.com/streamlink/streamlink/issues/1361
