### ISSUE TITLE
Make HLS chunk-lists playable

### ISSUE THREAD

**Issue by Ro-Den** [streamlink/streamlink#1128]
### Checklist

- [x] This is a bug report.
- [x] This is a feature request.
- [x] This is an improvement request.
- [ ] I have read the contribution guidelines.

### Description

Instead of sending a playlist first some web sites immediately send chunk lists, like:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:666
#EXTINF:2.0,
video1.ts
#EXTINF:2.0,
video2.ts
#EXTINF:2.0,
video3.ts
```
Firefox addon ["Native HLS Playback"](https://addons.mozilla.org/en-US/firefox/addon/native-hls-0-7-10/) by [Gaetan Hervouet](https://addons.mozilla.org/en-US/firefox/user/graamk/) has no issue playing such files.

Streamlink gives an error: "No playable streams found on this URL: ..."

Hope it's possible to fix.

**Comment by beardypig** [comment]
If you prefix the URL with `hls://` it should just work. Eg `hls://http://example.com/stream/chunks.m3u8`.

**Comment by Ro-Den** [comment]
It worked!

So, hlsvariant:// is for playlists and hls:// is for chunk lists.

But can we just get rid of this nonsence and make the program play any file with m3u8 extention depending on its content without these hls:// or hlsvariant:// ?

**Comment by beardypig** [comment]
@Ro-Den what do you mean "How to put hls:// into a plugin? "prefix the URL" isn't working there."?

**Comment by Ro-Den** [comment]
@beardypig, thanks!

It's my fault. I was a little bit puzzled by this hls-hlsvariant mess and wasn't able to figure out the correct syntax.

`return {"live": HLSStream(self.session, urlnoproto, **params)}` is all I needed!

With your corrections it's more obvious now.
