### ISSUE TITLE
Plugin request: elevensports.tw / elevensportsnetwork.com

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1130]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Eleven Sports TW offers some great Taiwanese/Asian and other "premium sports" online (Premier League, NFL, NBA, Serie A, ATP, F1, etc). They're in six countries, so potentially what works for .tw would work for the others as well.

Alternatively, if there's a guide to how I might go about picking up the stream myself, I'd be keen to have a look. Login is required in order to access the streams, but could the --http-cookie argument potentially solve that...?

**Comment by karlo2105** [comment]
They operate channels in 6 following countries : 

1. Taiwan : `http://elevensports.tw/`
2. Singapore : `http://elevensportsnetwork.sg/`
3. Belgium : `http://elevensportsnetwork.be/`
4. Luxembourg :  `http://elevensports.lu/`
5. Poland : `http://elevensportsnetwork.pl/`
6. United States : `http://elevensportsusa.com/`

**Comment by ryanjgillies** [comment]
I spotted on the bottom of the website that ElevenSports streams are powered by NeuLion, which has been referenced in previous requests #613 and #1029 - I don't know if that bodes well for ElevenSports or not.

Chrome Inspector shows the videos coming through in small MP4 chunks, I can't quite tell how to get the m3u8 url though:

```
Channel Eleven:
http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/10/3450.mp4?nltid=elevensportstw&nltdt=0&uid=393442

Channel Eleven Sports:
http://nlds16.cdnaknl.ap.neulion.com/nlds/eleven/elevensports_tw/as/live/elevensports_tw_hd_400/20170803/10/4048.mp4?nltid=elevensportstw&nltdt=0&uid=393442

Channel Eleven Plus:
http://nlds1.cdnaknl.ap.neulion.com/nlds/eleven/elevenplus_tw/as/live/elevenplus_tw_hd_800/20170803/10/4332.mp4?nltid=elevensportstw&nltdt=0&uid=393442
```

I dug through the cookies and found the following:
```
Name: JSESSIONID
Content: 17216328212080~80042A755C75F110BB33ECA3168270C2
Path: /

Name: UserName
Content: xxx (my email address)
Path: /

Name: X-NL-DC
Content: nyc
Path: /

Name: X-NL-DC
Content: nyc
Path: /service

Name: X-NL-DC
Content: nyc
Path: /channel

Name: clientID
Content: 49032152.1500721203
Path: /

Name: locale
Content: en_US
Path: /

Name: nllinktoken
Content: 25184f7ea7070fbc779bf0631a802e1631a6a5417200d66fd95f5aa1feec6e0f
Path: /

Name: pnctest
Content: 1
Path: /

Name: sessionID
Content: 1501755705
Path: /

Name: userID
Content: 65-6e-58-64-26-61-62-67-69-65-63-73-3f-68-70-63-6d-72-33-6a-78-75
Path: /

Name: userID
Content: 65-6e-58-64-26-61-62-67-69-65-63-73-3f-68-70-63-6d-72-33-6a-78-75
Path: /channel
```

What should my next step be?

**Comment by beardypig** [comment]
Seems to be a good thing - I'd try doing 
```bash
streamlink -ldebug --http-cookie "nllinktoken= 25184f7ea7070fbc779bf0631a802e1631a6a5417200d66fd95f5aa1feec6e0f" --http-cookie "UserName=xxx" --http-cookie "userID=65-6e-58-64-26-61-62-67-69-65-63-73-3f-68-70-63-6d-72-33-6a-78-75" "hls://http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/10/3450.mp4?nltid=elevensportstw&nltdt=0&uid=393442"
```
(put your actual email address in) 
and see if anything useful happens :) 

All the sites appear to be geo-locked, and I don't have a suitable proxies - the US site needs a cable login (we won't be supporting that one).

**Comment by karlo2105** [comment]
With http user agent for ipad or android you can get m3u8 links from Neulion for elevensportsnetwork channels.

**Comment by ryanjgillies** [comment]
So I gave that a bash and I got the following 403 error back in response:
```
[cli][info] Found matching plugin stream for URL hls://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/14/5530.mp4?nltid=elevensportstw&nltdt=0&uid=393442
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/14/5530.mp4?nltid=elevensportstw&nltdt=0&uid=393442')> (Could not open stream: Unable to open URL: http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/14/5530.mp4?nltid=elevensportstw&nltdt=0&uid=393442 (403 Client Error: Forbidden for url: http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/14/5530.mp4?nltid=elevensportstw&nltdt=0&uid=393442))
error: Could not open stream <HLSStream('http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/14/5530.mp4?nltid=elevensportstw&nltdt=0&uid=393442')>, tried 1 times, exiting
```
I tried including all of the cookies as arguments to see if that helped at all, but same result.

And @karlo2105 I tried changing the user agent as you suggested, but the website won't display any feed in that instance, it simply provides a link to their app to watch it instead.

**Comment by beardypig** [comment]
@ryanjgillies when you see the request the Chrome network tab, right click and copy the URL as a cURL command and show us what it would run (remember to edit out emails, etc.).

**Comment by ryanjgillies** [comment]
@beardypig thanks for the quick response - this is the cURL command for the stream:
`curl 'http://nlds8.cdnaknl.ap.neulion.com/nlds/eleven/eleven_tw/as/live/eleven_tw_hd_4500/20170803/15/1054.mp4?nltid=elevensportstw&nltdt=0&uid=393442' -H 'Accept: */*' -H 'Connection: keep-alive' -H 'Accept-Encoding: gzip, deflate' -H 'X-Requested-With: ShockwaveFlash/26.0.0.137' -H 'Accept-Language: en-GB,en;q=0.8,zh-TW;q=0.6,zh;q=0.4' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36' --compressed`

**Comment by beardypig** [comment]
@ryanjgillies what OS are you using? Can you run that curl command and see if it works? There don't appear to be any cookies, but it doesn't work for me so it's probably geo-locked.

**Comment by ryanjgillies** [comment]
@beardypig I'm running Linux Mint 18.1 - the website is most certainly geo-locked. I tried executing that curl command in terminal but it just outputs a bunch of gibberish.

**Comment by beardypig** [comment]
Gibberish is good. Can you paste it in to a gist or pastebin?

**Comment by ryanjgillies** [comment]
I can't seem to get to the output, my terminal window can't display all of it, and my text editor refuses to open it because of an unknown encoding. I've output the results into a text file (attached).
[output.txt](https://github.com/streamlink/streamlink/files/1197744/output.txt)

**Comment by beardypig** [comment]
Try piping it in to vlc or mpv, it might actually be the video...

**Comment by ryanjgillies** [comment]
Not sure why I didn't think of that! VLC does indeed play the file (sort of). There's no video or audio content, but it instantly recognises the clip as being 2 seconds long, and plays from start to finish. When I copy and paste the stream url directly into the browser I get the same result.

**Comment by ryanjgillies** [comment]
I've played around with this a little more but regrettably not got far!

Would anyone like two month's subscription (courtesy of me!) to NordVPN and ElevenSports Taiwan to see if they can get a plugin up and running...?

**Comment by back-to** [comment]
**elevensports.tw** is the same as [UFCTV](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/ufctv.py)

i changed it a bit

https://gist.github.com/back-to/2ff7a363f0fcbccd806cbd47fde636ef

you can see the changed here https://gist.github.com/back-to/2ff7a363f0fcbccd806cbd47fde636ef/revisions

---

you need to edit your login data here

https://gist.github.com/back-to/2ff7a363f0fcbccd806cbd47fde636ef#file-elevensports-py-L48-L49

---

you maybe need to change this here to `http.post`
it was empty for me because of no login data

`http.get` works without a login for vods, but did not work for live streams

https://gist.github.com/back-to/2ff7a363f0fcbccd806cbd47fde636ef#file-elevensports-py-L60

---

`VODs` should work, Livestreams maybe too.

**Comment by ryanjgillies** [comment]
@back-to thank you so much, far more progress than I managed!

I've looked over the changes you made and attempted to use the plugin, adjusting the login credentials accordingly:
```
    options = PluginOptions({
        "username": 'my@email.com',
        "password": 'password'
    })
```
However the authentication doesn't appear to be working as intended, I keep receiving the following error (with both the livestreams and the VOD):

`error: Unable to open URL: https://www.elevensports.tw/secure/authenticate (('Connection aborted.', BadStatusLine("''",)))`

I thought maybe it might be the result of the user-agent, so I switched from iPhone to Chrome, but still no luck.

As a side note, whilst I've hardcoded my login credentials into the plugin, I was under the impression I could use --elevensports-username and --elevensports-password on the command line, but apparently not? It says they are unrecognized arguments.

**Comment by ryanjgillies** [comment]
Well what do you know. Having read a little deeper it turned out that this was a potential Python bug. Switched over to another machine with a different Python installation and the problem was resolved - changing Line 60 to `http.post` also gave me access to the livestreams as well.

I can only assume with a little more tweaking this plugin would work for the other regional ElevenSports sites (US excluded), so perhaps this a contender to become an additional plugin on streamlink?

**Comment by back-to** [comment]
the easy way would be to rename the **ufc plugin** into **neulion**
and
support different **domains** there

---

https://watch.nba.com/ would work aswell but requieres more changes

https://watch.nba.com/video/2017/08/07/all-access-nba-africa-2017
```js
var programId = 689825;
```

---

https://www.elevensports.tw/video/5/27-bologna-v-juventus-highlight
```js
var video = {
    id: "27687",
    name: "5/27 Bologna v Juventus highlight",
    description: "",
    image: "https://neulionsmbnyc-a.akamaihd.net/u/m...",
    type: "video"
};
```

https://www.elevensports.be
https://www.elevensports.lu
https://www.elevensports.pl
https://www.elevensports.sg
https://www.elevensports.tw

are all the same, that would already work with the `ufc.tv` plugin

---

not sure how i found the videoid yesterday,
but today everthing starts with `var video` instead of `program` or `g_channel`
maybe just some User-Agent issue

https://gist.github.com/back-to/2ff7a363f0fcbccd806cbd47fde636ef#file-elevensports-py-L28-L29

**Comment by trello3** [comment]
Hey. I'm new to Github and this. Can someone help me out to get my first url sniffed from neulion or some other source in m3u format? Thanks.

**Comment by potyt** [comment]
This would be excellent!

From reading this thread, it sounds like all that is required is to rename the UFC plugin, to a generic NeuLion one, and then parameterize it per domain. Are the parameters required the stream-url and the auth-url?

What else do people think is required? I have a Taiwanese VPN and suscription, so I can test a few things as required. Programmer by trade, Linux user at home, so might be able to make the odd useful contribution as well.

**Comment by ex0de** [comment]
I'm interested in this plugin as well. @back-to your links give both 404. Any luck we could get the code again?

**Comment by potyt** [comment]
This all looked quite promising, then went a bit quiet... Anyone looking at this?

**Comment by back-to** [comment]
@ex0de  @potyt 

it is only tested with free videos

i don't know if the livestream or other paid videos will work with your login data

but maybe you could test it, if it doesn't work `-l debug` would be nice

https://streamlink.github.io/cli.html#cmdoption-l

---

currently you need to use the **ufctv** cli commands

```
--ufctv-username USERNAME
--ufctv-password PASSWORD
```
https://streamlink.github.io/cli.html#cmdoption-ufctv-username

and you need to replace the `ufctv.py` file with

https://github.com/back-to/streamlink/blob/neulion1/src/streamlink/plugins/ufctv.py

_domains that should work for_

```
https://watch.nba.com
https://www.elevensports.be
https://www.elevensports.lu
https://www.elevensports.pl
https://www.elevensports.sg
https://www.elevensports.tw
https://www.ufc.tv
```

**Comment by trello3** [comment]
@back-to do you have skype or email I can contact you at, I need some help... If you don't mind that is.

**Comment by potyt** [comment]
Problem is, that the URL I provide is an elevensports one, and it 
doesn't know to load the ufc plugin (user/pass option doesn't seem to 
force this) and I can't seem to force the plugin to use.

Probably missing something basic...


On 12/12/17 09:11, back-to babbled:
> @ex0de  @potyt 
> 
> it is only tested with free videos
> 
> i don't know if the livestream or other paid videos will work with your login data
> 
> but maybe you could test it, if it doesn't work `-l debug` would be nice
> 
> https://streamlink.github.io/cli.html#cmdoption-l
> 
> ---
> 
> currently you need to use the **ufctv** cli commands
> 
> ```
> --ufctv-username USERNAME
> --ufctv-password PASSWORD
> ```
> https://streamlink.github.io/cli.html#cmdoption-ufctv-username
> 
> and you need to replace the `ufctv.py` file with
> 
> https://github.com/back-to/streamlink/blob/neulion1/src/streamlink/plugins/ufctv.py
> 
> _domains that should work for_
> 
> ```
> https://watch.nba.com
> https://www.elevensports.be
> https://www.elevensports.lu
> https://www.elevensports.pl
> https://www.elevensports.sg
> https://www.elevensports.tw
> https://www.ufc.tv
> ```
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/streamlink/streamlink/issues/1130#issuecomment-351119016

-- 
I like to dissect girls. Did you know I'm utterly insane?
  // pot

**Comment by back-to** [comment]
@potyt 
you need to replace your `src/streamlink/plugins/ufctv.py` file **or sideload this new file**.

- sideloading from default folder
https://streamlink.github.io/cli.html#sideloading-plugins
- sideloading from custom folder
https://streamlink.github.io/cli.html#cmdoption-plugin-dirs

New File:
- https://raw.githubusercontent.com/back-to/streamlink/neulion1/src/streamlink/plugins/ufctv.py

after you replaced or sideload the plugin this domains should work.

```
https://fanpass.co.nz - Tested
https://watch.nba.com
https://watch.rugbypass.com
https://www.elevensports.be
https://www.elevensports.lu
https://www.elevensports.pl
https://www.elevensports.sg - Tested
https://www.elevensports.tw - Tested
https://www.tennischanneleverywhere.com - Tested
https://www.ufc.tv - Tested
```

try to run the command with a debug loglevel like here.
```
streamlink https://www.elevensports.tw/channel/eleven-zh best -l debug --ufctv-username USERNAME --ufctv-password PASSWORD
```

**Comment by atk3K** [comment]
@back-to 

Thank you for your efforts to make the ufc plugin a more interoperable version for sites based on neulion.

Just wanted to let you know I tried your custom ufctv.py file as referenced above as well as your branch with latest commits of neulion.py but in both cases I get the same output.

**cli][info] Found matching plugin ufctv for URL https://www.elevensports.sg/channel/eleven
[plugin.ufctv][debug] Attempting login as _<username here>_
error: Unable to parse XML: not well-formed (invalid token): line 33, column 46 ('\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r ...)**

Hoping you can fix it. Can't wait for this to be released into the master branch. :-)

**Comment by back-to** [comment]
@atk3K 
i don't have an elevensports account, i can only test it with the nba account which works.

there password **length limit is 16** so don't enter more if you think your password is longer.
_(on nba at least)_

make sure to use the last version, **this won't change anything at the login** but it has some more fallback features.
https://github.com/streamlink/streamlink/pull/1406/files

---

if you change

https://github.com/back-to/streamlink/blob/ba893e618ba4167a6426ca50948e10b432ea50b8/src/streamlink/plugins/neulion.py#L137-L138

```diff
         })
+        print(res.text)
         login_status = http.xml(res, schema=self.auth_schema)
```
copy this **without the +** and show me the output when you run streamlink.

### **remove your account data if there will be something in the output**

**Comment by glockmaster** [comment]
how to use the login? --ufctv-username + password wont work

**Comment by bastimeyer** [comment]
@glockmaster 
The plugin got removed earlier this year.
#1493

Going to lock the thread...
