### ISSUE TITLE
douyu.py question

### ISSUE THREAD

**Issue by yoyosnart** [streamlink/streamlink#1131]
### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.
- [ X] I want to ask something

### Description

Hi ！ Nice to meet you
Fisrt , sorry for my poor English and I'm a beginner of reverse engineer

I have some question about douyutv api ,appkey.

        suffix = "room/{0}?aid=androidhd1&cdn={1}&client_sys=android&time={2}".format(channel, cdns[0], ts)
        sign = hashlib.md5((suffix + API_SECRET).encode()).hexdigest() 

I want to learn find these information . 
(I know I can just your project but I want to do this by myself )

I have tried using fiddle to catch packet with douyu android app but it's find nothing

and I access PC Website i get something like https://www.douyu.com/lapi/live/getPlay/676552

but I can't not access this url :(

Can you give me some suggestion ? 
I don't know what should I do and what should I learn to get the correct information (app secret key and his md5 formula)_

Thany you very much！

**Comment by gravyboat** [comment]
Hello, unfortunately we don't provide help with reverse engineering for sources outside of Streamlink as it places undo burden on the team in addition to the support we already do and we don't know what we might be supporting. I'm going to close this for now, if someone wants to provide help they can do so, but this isn't really the appropriate place to discuss this sort of issue in general terms.
