### ISSUE TITLE
Rename hitbox.py to smashcast.py

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#1132]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

And remove hitbox specific url code.

**Comment by gravyboat** [comment]
There are a few PRs here related to this topic: https://github.com/streamlink/streamlink/pulls?utf8=%E2%9C%93&q=is%3Apr%20hitbox%20is%3Aclosed%20 where we added support but didn't rename. @beardypig what do you think about renaming the plugin file, then reversing the order in the plugin matrix?

**Comment by beardypig** [comment]
Can do. No need to remove support for the hitbox urls though. I imagine people have them saved in batch scripts and stuff, the old urls will still work in most cases.

**Comment by gravyboat** [comment]
Yeah I definitely think we should keep the existing support! No reason to do work we don't need to.

**Comment by back-to** [comment]
It's not important, because there **old urls are still valid**.

**Closing** since **renaming** plugins will result **in some cases in errors** https://github.com/streamlink/streamlink/issues/1223 (when the plugin gets an update)
