### ISSUE TITLE
Hope to support the following website

### ISSUE THREAD

**Issue by lki2019** [streamlink/streamlink#1133]
http://www.laifeng.com/

http://www.bobo.com/

http://www.showself.com/

http://v.6.cn/

http://www.2339.com/

http://www.tuho.tv/

http://www.9xiu.com/

longzhu.com

http://www.vlive.tv/

**Comment by lki2019** [comment]
https://web.immomo.com

www.9158.com

**Comment by lki2019** [comment]
http://www.kktv5.com/
https://www.yizhibo.com/
http://fanxing.kugou.com/
https://chushou.tv/
http://cc.163.com/
http://egame.qq.com/

http://www.fyun.tv/

http://www.meipai.com/live

**Comment by lki2019** [comment]
All live platform

Streamlink is located in focus on live website, right?
Youtube-dll is located on a global video site

**Comment by gravyboat** [comment]
@lki2019 While we do focus on live content this is a huge number of sites. Each site needs to have a unique issue created and (hopefully) some initial investigation done regarding how the content can be pulled, how requests work, etc. To put it in perspective this is more sites than we've made plugins for in all of 2017!

**Comment by lki2019** [comment]
@gravyboat Well, do not worry, have time to add the support slowly

**Comment by gravyboat** [comment]
Feel free to create an issue for each of these and please provide as much network sniffing as you can. No promises someone will choose to work on these of course as we don't get paid and there are many pressing issues to address! I'm going to close this issue out since we don't support huge lists like this.

**Comment by fozzysec** [comment]
https://egame.qq.com/ is supported by a new plugin in PR #2070
