### ISSUE TITLE
Allow plugins to return regular video file links

### ISSUE THREAD

**Issue by MineRobber9000** [streamlink/streamlink#1137]
### Checklist

- [ ] This is a bug report.
- [X] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [X] I have read the contribution guidelines.

### Description

I'm working on a VOD plugin (of questionable legality on the source, so I won't submit it) and the VODs are stored as .mkv files. Would it be possible for my plugin to return video links as VOD streams? Looking at the source, it appears not. However, if I am mistaken, please let me know.

**Comment by beardypig** [comment]
What do you mean? They host mkv files on HTTP? If so you can use the `HTTPStream` class.

**Comment by MineRobber9000** [comment]
Thank you. That was what I was looking for.
