### ISSUE TITLE
SOCKS Support?

### ISSUE THREAD

**Issue by nwgat** [streamlink/streamlink#1138]
can we get socks support? way simpler than http, also requests supports it
https://github.com/requests/requests/issues/3172

**Comment by beardypig** [comment]
_Please follow the guidelines for creating issues in the future._

This is a good feature to have, I didn't realise they had add support in `requests` :) It should be pretty straight forward to add socks support.

**Comment by nwgat** [comment]
when i build streamlionk with steamlink-portable on windows, and try socks i get
`(Missing dependencies for SOCKS support.)`

**Comment by beardypig** [comment]
@nwgat that means that @RosadinTV will need to update the portable builder. In the mean time, you could try my portable version which should have SOCKS support: https://github.com/beardypig/streamlink-portable

**Comment by RosadinTV** [comment]
Ready, it should be working now.
Thanks for the notice @beardypig 🎁

**Comment by nwgat** [comment]
did you try it? i seem to get 
` (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x046640B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))))
[End of Streamlink for Windows with ExitCode 1]`

**Comment by RosadinTV** [comment]
@nwgat I didnt tested specifically with iplayer but on the other servers I tried seems to work correctly.
It may be due to a problem with the proxy.

**Comment by nwgat** [comment]
iplayer works in the same socks proxy in opera

**Comment by RosadinTV** [comment]
Maybe @beardypig can help, i don't know what else can cause the problem :(

**Comment by beardypig** [comment]
@nwgat are you able to try it using the installer version or on a different OS, macOS or some Linux distro?

**Comment by nwgat** [comment]
tried both the git dev version on ubuntu 16.04 and the streamlink for windows , both trow up errors :/
