### ISSUE TITLE
Pursuit Channel

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#1140]
### Checklist

- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Can someone help with a plugin for Pursuit Channel:

http://www.vidillion.tv/pursuitchannel/

Cheers!

**Comment by back-to** [comment]
here is an ugly solution

https://gist.github.com/back-to/7364372910146e32531a55ee77d8bf72

**Comment by unlocKing** [comment]
Cheers dude, that works!
