### ISSUE TITLE
Leftover version numbers from Livestreamer docs

### ISSUE THREAD

**Issue by MineRobber9000** [streamlink/streamlink#1141]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Some documentation still contains livestreamer version numbers, including the API reference. (things implemented in 1.6.0 when streamlink isn't even to 1.0.0)

### Suggested solution

Instead of removing these version numbers, we should prefix them so as to say that they are livestreamer versions. (i.e; "1.6.0"->"ls1.6.0" or "livestreamer 1.6.0")

**Comment by back-to** [comment]
removing it **completely** might be better than `ls tags`,
since tags like this are **not made for any streamlink changes**.

since running an **old version** of streamlink is **not** that **efficient**.
