### ISSUE TITLE
About the use of the streamlink command

### ISSUE THREAD

**Issue by lki2019** [streamlink/streamlink#1142]
<pre><code>streamlink.exe http://streams.yupptv.com/freechannelplayer.aspx?id=144 best
error: No plugin can handle URL: http://streams.yupptv.com/freechannelplayer.asp
x?id=144</code></pre>

<pre><code>ffmpeg -user_agent 'curl/7.51.0' -i https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501834337~exp=1501834697~acl=/i/ind3_asianetnews@393763/*~hmac=d21eef3d05cef0e2290832bad952a78bc2fd1b0ea386b21fa78914fc907af203 -c copy oooo.mp4

How to use the -user_agent 'curl / 7.51.0' command?

streamlink.exe -user_agent 'curl / 7.51.0' -ldebug HLS:https://ind3-lh.akamaihd.net/i/ind3_asianetnews@393763/master.m3u8?hdnea=st=1501834337~exp=1501834697~acl=/i/ind3_asianetnews@393763/*~hmac=d21eef3d05cef0e2290832bad952a78bc2fd1b0ea386b21fa78914fc907af203 -o 1.mp4
</code></pre>
such?

**Comment by bastimeyer** [comment]
See the `--http-header` parameter
https://streamlink.github.io/cli.html#cmdoption-http-header
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

Your stream URL also looks like it's invalid. See
https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly

Example:
```
streamlink --http-header "User-Agent=foo" "hlsvariant://https://host.tld/path?params" best
```

**Comment by lki2019** [comment]
Thank you, understand

**Comment by bastimeyer** [comment]
Closing the thread then...
