### ISSUE TITLE
TvPlayer 400 Error

### ISSUE THREAD

**Issue by RedManMark86** [streamlink/streamlink#1147]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

When trying to use the TVPlayer Plugin I get a "(400 Client Error: Bad Request for url: http://api.tvplayer.com/api/v2/stream/live)"

### Expected / Actual behavior

To open the stream

### Reproduction steps / Explicit stream URLs to test

Code being used is as follows:

streamlink --tvplayer-email mark.gould@outlook.com --tvplayer-password ******* https://tvplayer.com/watch/channel4 best

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: V0.7.0 installer version

...

### Comments, logs, screenshots, etc.

i also tried the nightly build which gives this error

[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/channel4
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 345, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 248, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py", line 100, in _get_streams
    stream_data = self._get_stream_data(**stream_attrs)
TypeError: _get_stream_data() missing 1 required positional argument: 'channel_id'
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Can try again adding `-l debug` to the `streamlink` command and post the output?

**Comment by RedManMark86** [comment]
Hi @beardypig 

This is what I get if I use the plugin included in the V0.7.0 release

[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/bbcone
[plugin.tvplayer][debug] Getting stream information for resource=bbcone
error: Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (400 Client Error: Bad Request for url: http://api.tvplayer.com/api/v2/stream/live)

This is what I get if I use your latest one on github

usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
streamlink-script.py: error: unrecognized arguments: https://tvplayer.com/watch/bbcone

**Comment by beardypig** [comment]
If you download [tvplayer.py](https://raw.githubusercontent.com/streamlink/streamlink/master/src/streamlink/plugins/tvplayer.py) and replace the existing one in `<install dir>\pkgs\streamlink\plugins\` and try that, it doesn't look like the latest version was included in 0.7.0 but it should be in the latest nightly...

**Comment by RedManMark86** [comment]
Hi @beardypig 

The second error message I posted is using the tvplayer.py that you modified about 28 days ago.

This is with your debug command

usage: streamlink-script.py [OPTIONS] [STREAM]
streamlink-script.py: error: unrecognized arguments: https://tvplayer.com/watch/bbcone

This is without

[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/channel4
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in 
main()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
handle_url()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482, in handle_url
streams = fetch_streams(plugin)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394, in fetch_streams
sorting_excludes=args.stream_sorting_excludes)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 345, in get_streams
return self.streams(*args, **kwargs)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 248, in streams
ostreams = self._get_streams()
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py", line 100, in _get_streams
stream_data = self._get_stream_data(**stream_attrs)
TypeError: _get_stream_data() missing 1 required positional argument: 'channel_id'

**Comment by beardypig** [comment]
Are you doing `streamlink -l debug --tvplayer-email mark.gould@outlook.com --tvplayer-password ******* https://tvplayer.com/watch/channel4 best`? The ordering of the options can be a bit strange...

**Comment by RedManMark86** [comment]
Hi @beardypig 

I ran it again and here is the correct debug, sorry

[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/channel4
[plugin.tvplayer][debug] Got stream attrs: {'token': 'ef3efd681012784d77c9a15387faa6866ed6ec1e62d46eeb786c5291132389d7', 'resource': 'channel4'}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 345, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 248, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\tvplayer.py", line 100, in _get_streams
    stream_data = self._get_stream_data(**stream_attrs)
TypeError: _get_stream_data() missing 1 required positional argument: 'channel_id'

**Comment by beardypig** [comment]
Does it make a difference if you run it without your username and password? Does it work in your browser? Can you view-source in your browser and copy the page source in to a gist/pastebin? BBCOne is working for me at the moment... Channel 4 has some programme they cannot show online at the moment.

**Comment by RedManMark86** [comment]
Hi @beardypig 

OK so I have tried it without using my login and BBC one did work, though I get some awful stutter on panning shots or movement? Do you get the same? I tried both VLC and Media Player Classic? I know it isn't my PC as I have an i7 and a GTX 1070.

So it seems to only not work with I'm using my login giving the error above which works fine on their site.

i have tried swapping it around so the site link comes before and after the tvplayer-email command

**Comment by beardypig** [comment]
Hmm weird. I don't have any trouble with or without credentials. Can you grab the source of the page in your browser? Not sure why it cannot find the `channel_id`...

**Comment by RedManMark86** [comment]
Hi @beardypig 

I'm not sure either, but my login works fine for the site and I can watch. Even tried changing my password.

Have done as you asked here

https://gist.github.com/RedManMark86/8813dab4b78c8998b88a5548aab11cd2

**Comment by RedManMark86** [comment]
Hi @beardypig  if you want to know something weirder.

I made a test account using a different email that I was going to put here and it actually worked, the only difference between the two is the original one provided is that one says it has an active subscription until the 15th August 2017 which was my Event Pass for (Eubank v Abraham) fight.

So maybe that is what is causing the issue?

**Comment by beardypig** [comment]
Yeah, that's interesting I haven't tried it with an account that has a subscription - that could be the key difference :)

**Comment by RedManMark86** [comment]
Hi @beardypig 

If you want I can give you my login if I can message it to you privately or give you 5.99 to upgrade yours?

**Comment by beardypig** [comment]
I should be able to work it out from the page source you uploaded :) If not I might take you up on the offer :)

**Comment by beardypig** [comment]
Can you try this version of [tvplayer.py](https://raw.githubusercontent.com/beardypig/streamlink/551fb34aad54603ff4488a550569c5a81a54664d/src/streamlink/plugins/tvplayer.py)? Might work :)

**Comment by RedManMark86** [comment]
Hi @beardypig 

That worked fine, thank you!

What is the chance you could get it to work with the DRM plus channels? I know that the Kodi addon is meant to support this? Again I can provide you with a test account that is subscribed to it if required?

**Comment by gravyboat** [comment]
@RedManMark86 We've pretty much taken the stance that we don't deal with DRM. It changes too often and is too big a hassle for our small team of part time devs.

**Comment by beardypig** [comment]
The DRMed channels use widevine (and others) which the latest version of Kodi is meant to support. It's not impossible for streamlink to support it, and I have had some success with play Channel 5 (also DRMed) with streamlink using a Python widevine wrapper. However, it's not complete, very reliable or easy to setup so it's pretty unlikely that streamlink will ever support DRM. Not to mention that circumventing DRM, as would be very easy if we added support, normally results in a big legal hammer being brought down on projects - not something we want :-D

**Comment by anniman** [comment]
i have just installed streamlink on windows 10 and can use powershell to open bbc iplayer. i've managed to work that out but when trying to use tvplayer to view a stream i get the exact same error as the original op.
I assume i have the latest plugin version.

**Comment by back-to** [comment]
@anniman 
do you still use windows? streamlink/streamlink#1417

---

- **2017-09-12** - 0.8.1
- **2017-10-23** - your comment https://github.com/streamlink/streamlink/issues/1147#issuecomment-338826537
- **2017-11-14** - 0.9.0
  plugins.tvplayer: extract the channel id when logged in as a subscriber

**your version was not uptodate**

---

there was a bug #1340 for updating streamlink on windows with version 0.9.0

if you are affected

__Uninstall 0.7.0__ (default location)
`C:\Program Files (x86)\Streamlink` use `uninstall.exe`

__Uninstall 0.9.0__ (default location)
`%LOCALAPPDATA%\Streamlink` use `uninstall.exe`

for an updated **0.9.0** version without this bug install from
https://bintray.com/streamlink/streamlink-nightly/streamlink/_latestVersion/#files

---

Closing, original issue was solved in #1154
