### ISSUE TITLE
LIVE YouTube stream freezes on windows VLC

### ISSUE THREAD

**Issue by RangerCoder99** [streamlink/streamlink#115]
The topic says it all when trying to open a YouTube live stream on windows 10 (VLC nightly build) it instantly freezes the video. :(

**Comment by gravyboat** [comment]
We're going to need more details, is there anything being logged via VLC that would indicate the problem? Is Livestreamer putting anything out? Did you try both http and https? How can the problem be duplicated, etc.

**Comment by scottbernstein** [comment]
Are you sure that you're using VLC Nightly Build for version 3?

________________________________

**Comment by RangerCoder99** [comment]
Ok sorry this seems to be a problem with the  VLC Nightly Build I had, I just downloaded the last version and now it works without a issue!

**Comment by gravyboat** [comment]
Sounds good! I'm going to close this. Thanks for your note @scottbernstein.

**Comment by sbstp** [comment]
Should probably setup a known issues section in a [`CONTRIBUTING.md`](https://github.com/blog/1184-contributing-guidelines) file.

**Comment by Jan-Zoudlik** [comment]
Any chance you can share exact version number and ideally download link for the version it works with?
I am trying to play msnbc live channel(https://youtu.be/RDYFuZ75QU4) and getting exact same issue...
I tried many different versions with no luck...
Thanks

**Comment by RangerCoder99** [comment]
Jan-Zoudlik I'm using the new 32 bits VLC Nightly build you can get it on https://nightlies.videolan.org and the last release of this plugin :)

**Comment by Jan-Zoudlik** [comment]
That was super speedy reply...
... suggested version works perfectly
Thank you


Kind regards

*Jan Zoudlik - *IT Administrator
Westcare Supply Zone

*T* 01752 695469
*F* 01752 695466
*E* jan@westcare.net
*W* www.westcare.net

Westcare Supply Zone is a trading name of Westcare Limited.
Company Registration Number 2680675. Partners with PLP, ExCo and CAPH.

[image: http://plpcic.co.uk/] <http://plpcic.co.uk/>[image:
http://exeterconsortium.com/] <http://exeterconsortium.com/>[image:
http://www.caph.org.uk/web] <http://www.caph.org.uk/web>
