### ISSUE TITLE
Audio is high pitched when watching twitch VODs

### ISSUE THREAD

**Issue by ajrc0re** [streamlink/streamlink#1150]
When running this command:
``streamlink --player-passthrough hls %TwitchURL% best``
The stream plays but with high pitched audio. 

When using this command:
``streamlink %TwitchURL% best``

Audio plays fine (but I cant skip ahead on the VOD)

Previously, when I used the first command, as I have for years (back when this was livestreamer) the audio worked just fine. Something must have recently changed.

 I am currently running streamlink 0.7.0, and VLC 2.2.6 umbrella, on windows 10.

**Comment by beardypig** [comment]
Sounds like a player issue if it only happens with `--player-passthrough`, try a different player or more up to date version of VLC (like the version 3 beta) :-)

**Comment by gravyboat** [comment]
I'm running Windows 10, VLC 2.2.6, and Streamlink 0.7.0 and I can't duplicate this with the command you provided.

**Comment by ajrc0re** [comment]
> I'm running Windows 10, VLC 2.2.6, and Streamlink 0.7.0 and I can't duplicate this with the command you provided on a live stream.

Sorry, maybe it wasnt clear in my post but this only happens when viewing VOD's on twich. 

This is the URL I was using when I first found the issue.
``https://www.twitch.tv/videos/164590314``

Updating to VLC 3 beta does not fix the issue, and playing a multitude of other files in VLC does not have the same issue.

**Comment by gravyboat** [comment]
@ajrc0re I just edited my post. I can skip ahead in the VOD I linked as well. I get the same issue on that VOD you linked, can you try mine?

**Comment by ajrc0re** [comment]
@gravyboat I tried your link, skipping all over to multiple sections and had no issues. I went back and tried the one I posted and it was high pitched. So it seems like theres something going on with specific twitch links causing this issue. Any ideas?

**Comment by gravyboat** [comment]
@ajrc0re I would say try a different player first, if it still happens then we know the VOD is the issue, otherwise we know it is VLC.

**Comment by gravyboat** [comment]
I tested this tonight with MPV to confirm what @bastimeyer said and it's definitely a VLC issue. No audio problems at all. As such I'm going to close this, please report it to the VLC team so they're aware.

**Comment by louisdx** [comment]
I have the same high-pitch problem with videos saved via youtube-dl and played in vlc, mpv and mplayer, for about the same amount of time as reported by the OP.
