### ISSUE TITLE
[ Douyu] Bug after pull request #1109

### ISSUE THREAD

**Issue by bupmc** [streamlink/streamlink#1151]
( 0.7.0 with pull request https://github.com/streamlink/streamlink/pull/1109 )
When viewers below 2000, Streamlink doesn't change stream quality from medium to source_http automatically after pull request https://github.com/streamlink/streamlink/pull/1109.

> [cli][info] Found matching plugin douyutv for URL https://www.douyu.com/[viewers below 2000]
> error: The specified stream(s) 'medium' could not be found.
>        Available streams: source_http, source (worst, best)

**Comment by gravyboat** [comment]
How would it change quality automatically? this functionality doesn't exist in Streamlink for dynamic adjustments. Also the plugin required a huge rework just to get it working properly again so I'm not surprised things changed a bit but I was never aware such logic existed on our end.

**Comment by bupmc** [comment]
Before pull request https://github.com/streamlink/streamlink/pull/1109 Streamlink works fine, it's new bug after pull request https://github.com/streamlink/streamlink/pull/1109 .
Many rooms use bitrate 3000K or even 5000K, record medium stream quality( 900K) is a good choice. 
1. Most rooms start below 2000 viewers, https://github.com/streamlink/streamlink/pull/1109 won't start recording until 2000
2. If a 3000 viewers room disconnected and drop to 1000, https://github.com/streamlink/streamlink/pull/1109 won't start recording until 2000

**Comment by fozzysec** [comment]
@bupmc I think the only thing that can explain that has happened is that we uses a new API in PR #1109, this API works only when the viewer of one room exceed some fix value(2000 here). Maybe this is the new policy of douyu's API. We can do nothing here because this API is the only one AFAIK.

**Comment by fozzysec** [comment]
I tried some room with few viewers, it works. Would you please provide me with some room that has this problem?

**Comment by bupmc** [comment]
您好！我说的是medium画质 :)

**Comment by fozzysec** [comment]
@bupmc When medium doesn't exist, this will not return the medium stream, but you can simply make it work by specifying `default-stream` to something like `medium,source`. Then call `streamlink` without specifying the quality, it uses medium when it is available. When you need the source stream, you need to explicitly pass `source` to it. also you can modify few lines of code to return the source stream and name it as medium when medium is not available. It is up to you.
Here is the modified script
https://gist.github.com/fozzysec/c479970867fe58b4bb6b237c0fee3808

**Comment by bupmc** [comment]
感谢！问了一个好蠢的问题，长期睡眠不足人真的会变蠢……

**Comment by gravyboat** [comment]
Closing, no discussion in a while and @fozzysec provided some good options.
