### ISSUE TITLE
ITV Player plugin no longer functioning (since rebrand?)

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1152]
- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Just thought I'd throw this in the mix as the ITV Player plugin is no longer functioning - I would presume ever since it was rebranded as ITV Hub. The error message is as follows:

```
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[cli][info] Available streams: 1200k (worst, best)
[cli][info] Opening stream: 1200k (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'playpath': 'itv1livefms_1200@s172940?auth=eaEczcvbTbVbPdQbHdobKcjcYaKc.aCbFcYb8cOd6bWdGdcbkcMdrcubMaDdKbib3da-bzIxWs-frG-fEFfHBukw1Cardyo&aifp=v001&slist=itv1livefms_1200@s172940', 'app': 'live', 'swfVfy': 'http://www.itv.com/mediaplayer/ITVMediaPlayer.swf', 'live': True, 'rtmp': 'rtmpe://cp274438.live.edgefcs.net/live', 'timeout': 10, 'flv': '-'}, redirect=False> (No data returned from stream)
error: Could not open stream <RTMPStream({'playpath': 'itv1livefms_1200@s172940?auth=eaEczcvbTbVbPdQbHdobKcjcYaKc.aCbFcYb8cOd6bWdGdcbkcMdrcubMaDdKbib3da-bzIxWs-frG-fEFfHBukw1Cardyo&aifp=v001&slist=itv1livefms_1200@s172940', 'app': 'live', 'swfVfy': 'http://www.itv.com/mediaplayer/ITVMediaPlayer.swf', 'live': True, 'rtmp': 'rtmpe://cp274438.live.edgefcs.net/live', 'timeout': 10, 'flv': '-'}, redirect=False>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

I don't know how much code streamlink still shares with linkstreamer, but this was flagged and resolved on their Github under [Issue 1233](https://github.com/chrippa/livestreamer/issues/1233), so perhaps there isn't much work involved in bringing streamlink's plugin up to speed...?

**Comment by beardypig** [comment]
I'm not having any trouble loading any of the ITV streams, VOD or Live. Can you run the command again with `-l debug` and post the output?

**Comment by ryanjgillies** [comment]
I don't even know what to say about this particular oddity.

I re-ran the same command just to double-check, same result. Then I ran it again but with `-l debug` and it streams successfully. Even now when I go back to the old command it opens. I have no explanation, but it does indeed work, so thank you!

**Comment by gravyboat** [comment]
Closing this out since we can't duplicate and it seems intermittent.
