### ISSUE TITLE
streamlink closes early when either my connection drops or occasionally when streamer's connection is poor

### ISSUE THREAD

**Issue by Terrafail** [streamlink/streamlink#1155]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

streamlink closes early when either my connection drops or occasionally when streamer's connection is poor.  Worth noting that this didn't happen with livestreamer.

### Expected / Actual behavior
streamlink closes early when either my connection drops or occasionally when streamer's connection is poor
When either the stream drops temporally or network connection drops streamlink should poll for a connection or stream continuously until either the connection returns, the stream returns, or the player is closed.  

As of right now when any of these things happen streamlink outputs the following...

`error: Error when reading from stream: Read timeout, exiting
[stream.hls][warning] Failed to reload playlist: Unable to open URL: <long link> (404 Client Error: Not for url: <long link>)
[cli][info] Stream ended
[cli][info] Closing currently open stream`

### Reproduction steps / Explicit stream URLs to test

1. Open any stream (It happens usually when I'm watching a twitch stream but I assume that this happens with any other stream service)
2. Disconnect network cable to simulate network connection drop
3. Watch as streamlink quits after trying to connect a couple times

**Comment by gravyboat** [comment]
We get this question a lo, try this: https://github.com/streamlink/streamlink/issues/1146#issuecomment-320471910

**Comment by Terrafail** [comment]
Sometimes my connection drops for a lot longer than a few seconds (like minutes or longer) and streamlink ends up quitting where as livestreamer recovers and starts the stream again even after a prolonged downtime.

**Comment by gravyboat** [comment]
Hmm, it might have been changed in a PR at some point in the past so you can look through those if you want, but there's quite a few at this point. I don't think we ever planned to have streams recover after multiple minutes of the network being unavailable, but I also don't recall discussing removing such functionality. Maybe try and take the Twitch plugin file from Livestreamer and drop it in instead of the Streamlink one and see if that's the culprit? There have been some major changes to that plugin.

**Comment by Terrafail** [comment]
Funny thing is that I've already previously updated livestreamer's twitch plugin to the current streamlink version of the twitch plugin so that livestreamer could play twitch streams.  

So I'm thinking maybe something got inadvertently fixed during the livestreamer update/maintenance to streamlink.

**Comment by gravyboat** [comment]
It's definitely a possibility. I don't know if it's something we would consider a bug at this point though since continually polling for minutes on end seems kind of counter productive. Let's see if anyone else pops in with some ideas.

**Comment by sou7611** [comment]
Seeing this constantly after upgrading to 0.8.1, on sites that use the generic "stream" plugin.

Same exact error : Error when reading from stream : Read timeout, exiting

Happens reliably on foxportsgo and watchespn.com

**Comment by Bluebuster116** [comment]
@sou7611 I'm also experiencing the same issue with vaughnlive. I'm not sure which code should be used to retry recording the stream. Can somebody please post a solution or whatever method they use to at least temporarly bypass this problem?. @gravyboat Can you please explain a bit how those parameters of retry segment works?. This part is not in the documentation though.

**Comment by back-to** [comment]
> streamlink closes early when either my connection drops

If you expect a bad connection, you will have to use
https://streamlink.github.io/cli.html#cmdoption-hls-timeout

`--hls-timeout 1200` for max 20 minutes downtime.

it might give you an **403 error** if the playlist is **locked** to your **previous IP**

> occasionally when streamer's connection is poor

If a twitch streamer has a poor connection and goes offline, a new vod/playlist will get started.
Your old playlist url will be invalid.

**404 Client Error** is correct here.

---

Closing.
