### ISSUE TITLE
Ustream plugin returns empty dictionary

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1156]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Installed streamlink through pip and imported streamlink to be used in my project. Tried to resolve this stream http://www.ustream.tv/decoraheagles and all I am gettings is empty dictionary.

### Expected / Actual behavior

Expected a dictionary with resolved streams and other items.

### Reproduction steps / Explicit stream URLs to test

1. ... Install through pip (current version 0.7.0)
2. ... Import to a project
3. ... streamlink.streams(url='http://www.ustream.tv/decoraheagles')

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: 0.7.0 & 2.7.12

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
That channel is currently offline, it is playing a recorded video (http://www.ustream.tv/recorded/106628613). Did it work correctly using the command line tool? 
Returning an empty dict is the expected result when the channel is offline.

**Comment by Twilight0** [comment]
I tried this: http://www.ustream.tv/channel/pluswebtv
Empty dictionary
But this instead worked: http://www.ustream.tv/channel/3535F2D3z99

**Comment by beardypig** [comment]
Both those work for me, albeit a bit slowly.
```python
import streamlink.session
import sys

session = streamlink.session.Streamlink()
session.set_loglevel("debug")
session.set_logoutput(sys.stdout)
plugin = session.resolve_url("http://www.ustream.tv/channel/pluswebtv")
streams = plugin.get_streams()
```

If you try that code snippet and check the log output there might be some info there...

**Comment by Twilight0** [comment]
Thanks I 'll keep this code and put it in the project.

**Comment by gravyboat** [comment]
Closing since this appears to be resolved.
