### ISSUE TITLE
NFL Game Pass

### ISSUE THREAD

**Issue by RedManMark86** [streamlink/streamlink#1157]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Any chance Streamlink could make a plugin for NFL Game Pass. I can provide a working login for it for testing.

They have switched over from Nuelion to what I think is WWD or akamaized?

I know the Kodi addon has got it working but I prefer using VLC as it handles the playback better.

This will be a dead link but here is what a request looks like from the Kodi Addon for a VOD game.

https://dvr-i-video-nfl.akamaized.net/dvr/5eafcfc3-c321-41ef-89d5-3dae620af468/5eafcfc3-c321-41ef-89d5-3dae620af468.ism/QualityLevels(4749952)/Manifest(video,format=m3u8-aapl-v3,audiotrack=audio,filter=hls)?hdnea=st=1502387482~exp=1502387507~acl=/*~hmac=5ff12587133807ed89fd959c331c25d4054b50902bc40df70fa4bba75d8d170a&hdcore=2.11.3|Connection=keep-alive&User-Agent=Safari%2F537.36+Mozilla%2F5.0+AppleWebKit%2F537.36+Chrome%2F31.0.1650.57

Regards,

Mark

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by jbarry786** [comment]
I second this request.

Streaming/capturing games through streamlink provides much better quality than through Kodi or through the website. It's kind of funny that I buy a subscription and then I want to watch the games using streamlink to download them.

This would be a tremendous plugin for me if it was possible to get done.

Last year it was very easy to sniff the urls and play the master.m3u8. These new ones I am afraid I am too much of a notice to know how to do it.

Even if a plugin isn't created, any lights on whether you can capture the streams from these new links would be great.

Currently, I get this:

`streamlink "hlsvariant://https://dvr-i-video-nfl.akamaized.net/dvr/5eafcfc3-c321-41ef-89d5-3dae620af468/5eafcfc3-c321-41ef-89d5-3dae620af468.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1502533038~exp=1502533063~acl=/*~hmac=a82a59bc1de3faed2b1
5e9b619188dcd9b798b889422952309e5a3b451b50137&hdcore=2.11.3" best
[cli][info] Found matching plugin stream for URL hlsvariant://https://dvr-i-video-nfl.akamaized.net/dvr/5eafcfc3-c321-41ef-89d5-3dae620af468/5eafcfc3-c321-41ef-89d5-3dae620af468.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1502533038~exp=1502533063~acl=/*~hmac=a82a59bc1de3faed2b15e9b619188d
cd9b798b889422952309e5a3b451b50137&hdcore=2.11.3
error: Unable to open URL: https://dvr-i-video-nfl.akamaized.net/dvr/5eafcfc3-c321-41ef-89d5-3dae620af468/5eafcfc3-c321-41ef-89d5-3dae620af468.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1502533038~exp=1502533063~acl=/*~hmac=a82a59bc1de3faed2b15e9b619188dcd9b798b889422952309e5a3b451b50137&
hdcore=2.11.3 (403 Client Error: Forbidden for url: https://dvr-i-video-nfl.akamaized.net/dvr/5eafcfc3-c321-41ef-89d5-3dae620af468/5eafcfc3-c321-41ef-89d5-3dae620af468.ism/manifest(format=m3u8-aapl-v3,filter=hls)?hdnea=st=1502533038~exp=1502533063~acl=/*~hmac=a82a59bc1de3faed2b15e9b619188dcd9b798b88
9422952309e5a3b451b50137&hdcore=2.11.3)`

**Comment by RedManMark86** [comment]
@beardypig or any other developer, I don't believe you can send a PM on here but I am happy to commission any of you to do this if you can contact me with the fee for your time. I can also provide an account for you to test with.

If the creating of this plugin would go against any of Streamlinks rules, then I'm happy to keep it as a private commission

**Comment by WolfganP** [comment]
There was a discussion on NFL Gamepass streams at http://stream-recorder.com/forum/rip-video-sub-xml-t20307.html?&highlight=nfl+gamepass last year, it may help to discover the stream links / methods, but I don't know if it works for 2017 season.

**Comment by RedManMark86** [comment]
I mean it must be possible. if you look at the NFLStreams subreddit at match time nearly all the streams are actually direct feeds from the NFL site. Some use http://jokertn.herokuapp.com/ before the start of the rest of the link but otherwise nearly all use a direct pull from the NFL site.
I have done some digging and I honestly don't think it would be hard for someone on with the knowledge to do it, sadly I'm know programmer.
But basically the plugin would login as you, select the stream and then access the DIVA player an exchange the key to then get the encrypted stream. In fact I don't think it is even encrypted, I think it is just a case of using the DIVA player API on the site so that the token is generated correctly.

Also on a side note, the Kodi addon was using an Apple user Agent which only gave 720p streams and had audio issues. They switched the Agent to Chromecast which gives 1080p and a 6.5Mbps bit.

Like I said, I'm happy to commission a dev to do this even if the plugiin has to remain private, just let me know your costs or I could make a sizeable donation to streamlink itself, it really is up to you

**Comment by beardypig** [comment]
@RedManMark86, if you still want this plugin it seems doable - just need an account to test with, feel free to drop me a mail: beardypig <swirly a> protonmail <period> com.

**Comment by RedManMark86** [comment]
@beardypig email sent as requested

**Comment by Metaphorce812** [comment]
I second this feature request.

**Comment by CraigMack69** [comment]
would also be happy to see this available You can play it as mentioned with kodi via this git. I have literally thousands of logins to test with if needed. https://github.com/aqw/xbmc-gamepass.

**Comment by Zafranp** [comment]
Last year I paid a lot of money for NFL network. NEVER AGAIN ! Now I am watching NFL online via  NFLHQTV .COM  . Probably you already know but I want to remind you that NFLHQTV .COM  has NFL games in their price. It's only $29/yearly so I suggest to go to  NFLHQTV .COM and buy subscription there.

**Comment by CraigMack69** [comment]
So is there any progress on this?

**Comment by gravyboat** [comment]
@CraigMack69 Not yet I don't think. There would have been a note updating this thread if there was.

**Comment by jgshier** [comment]
Any chance this is still being worked on for 2018?

**Comment by back-to** [comment]
Adding new plugins where it is **difficult to get an account**,
will make the new plugin impossible to maintain.

so adding it, is useless.

closing
