### ISSUE TITLE
Can't select 480p when playing YouTube videos

### ISSUE THREAD

**Issue by Techjar** [streamlink/streamlink#1158]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Every quality level is there, except for 480p (the best quality I can watch at, woo crap DSL). If I try to select 480p I just get a stream not found error. YouTube provides 480p so I would expect it to work, especially since everything else does.

### Expected / Actual behavior

It would expect 480p to work, but it just doesn't exist.

### Reproduction steps / Explicit stream URLs to test

1. Find any YouTube video that is 480p or higher.
2. Select 480p stream.

### Environment details

Operating system and version: Windows 10 Pro
Streamlink and Python version: Streamlink 0.7.0, Python 2.7.13

Not sure of any other particular details that would matter.

### Comments, logs, screenshots, etc.

I tried several different videos, same result. Really odd that *only* 480p is missing and nothing else.

**Comment by gravyboat** [comment]
480p isn't an option for me either for some reason, I'm using https://www.youtube.com/watch?v=VswlbnqCNsQ as a test video. Lower and higher qualities show up but this 480p is missing for me too even though it is available via the web player:
```
REDACTED> streamlink -p "path\to\mpv" https://www.youtube.com/watch?v=VswlbnqCNsQ 480p
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=VswlbnqCNsQ
error: The specified stream(s) '480p' could not be found.
Available streams: audio_webm, audio_mp4, 144p (worst), 240p, 360p, 720p, 720p60, 1080p60 (best)
```

**Comment by beardypig** [comment]
Interestingly it looks like 480p is only available as an adaptive stream. It's a relatively simple fix, but it won't work exactly like on the website. Because 480p is an adaptive stream quality the audio quality can be varied, in the YouTube plugin for Streamlink we always pick the _best_ audio source for adaptive video sources - so, you might not be able to stream the 480p video and the highest quality sound :)
