### ISSUE TITLE
Twitch streams stutter. 

### ISSUE THREAD

**Issue by devonak** [streamlink/streamlink#1167]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
 It's barely noticeable but once you see it you can't unsee it.  Every second of footage appears to stutter in.  It's like the stream is digesting the second by second chunks and each time it speeds into the repeat of the next stutter.  If I pull up the twitch website and watch the same stream at source I get fluid motion.  I'm using VLC.  I've read that people suggest buffering but either it does nothing or I'm not setting up buffering correctly.  
...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test
any twitch stream

### Environment details

Operating system and version: ...
Streamlink and Python version: ...
windows 10 64bit,  current version of streamlink and python. 

16 gigs of ram, gtx 970, i7 4790k.  
...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
This sounds like a rendering issue of your local player. Please try using a different player or upgrading VLC.

Streamlink and the Twitch.tv plugin are working correctly, as you can see here in the ffmpeg output:

```
$ streamlink -O twitch.tv/day9tv best | ffmpeg -hide_banner -i pipe:0 -f null -
[cli][info] Found matching plugin twitch for URL twitch.tv/day9tv
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
Input #0, mpegts, from 'pipe:0':
  Duration: N/A, start: 11319.023000, bitrate: N/A
  Program 1 
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 129 kb/s
    Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1920x1080, 60 fps, 60 tbr, 90k tbn, 120 tbc
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> wrapped_avframe (native))
  Stream #0:0 -> #0:1 (aac (native) -> pcm_s16le (native))
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf57.71.100
    Stream #0:0: Video: wrapped_avframe, yuv420p, 1920x1080, q=2-31, 200 kb/s, 60 fps, 60 tbn, 60 tbc
    Metadata:
      encoder         : Lavc57.89.100 wrapped_avframe
    Stream #0:1: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
    Metadata:
      encoder         : Lavc57.89.100 pcm_s16le
^Cframe= 2010 fps= 66 q=-0.0 Lsize=N/A time=00:00:33.59 bitrate=N/A speed=1.11x    
video:974kB audio:6296kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Exiting normally, received signal 2.
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

**Comment by ElectronicWar** [comment]
Can't confirm either, everything smooth (Windows 10 as well, using MPV and VLC).
What player are you using?
Try to increase, if available, buffer size in `streamlinkrc` for your player.

**Comment by Tharn** [comment]
Can't confirm this either, and I watch a lot of 60 FPS stuff with Streamlink and MPC-HC. I've set up the relevant bits in streamlinkrc (\Users\XX\AppData\Roaming\streamlink\streamlinkrc) like this:

```
hls-segment-threads=4
hds-segment-threads=4
stream-segment-threads=4
ringbuffer-size=32M
```

And I've also set up the queue (buffer) settings in LAV Filters to fill up 2000 packets (frames) and 50 MB maximum. AFAIK there are similar settings you can tweak in VLC.

**Comment by gravyboat** [comment]
It's been a month and no one can duplicate this and we have not received an update so I am closing this.

**Comment by gravyboat** [comment]
I've been seeing some minor stuttering the past few days always accompanied with a segment open error:
```
[stream.hls][error] Failed to open segment 3424: Unable to open URL: https://video-edge-7e8fbc.sea01.hls.ttvnw.net/v0/Cs
wBMjlaYRj6QUMKh26pETXhsbahyzQ7Omq8O5KY4TkhXBQUK-9sfqwVQD1dpJSYUTi9KLvKPXS1RfxvXbiUEIe0Sv1ADr0GbRBj2rc-Wlb42WDKtS2gfvFQzf
B37JmCgxmEWLeTQ2KlqFAIsBmkl9tawoD2zoKyfAo_K4m0c9QIvcGRgL4t-L7xSY5aABxSgsaGwFdSuwXarSGRRPHDo6VNFsj0223KC-SKNo2wQX0wbKA_m5
gwjyPSUYvgI-3FyPXvZHVColGr44FImz8MEhDbk37YvPKfIOVQtB2xGuOJGgxNxSeTNgFZfdDjSaY/index-0000003424-89GT.ts (504 Server Error
: Gateway Time-out for url: https://video-edge-7e8fbc.sea01.hls.ttvnw.net/v0/CswBMjlaYRj6QUMKh26pETXhsbahyzQ7Omq8O5KY4Tk
hXBQUK-9sfqwVQD1dpJSYUTi9KLvKPXS1RfxvXbiUEIe0Sv1ADr0GbRBj2rc-Wlb42WDKtS2gfvFQzfB37JmCgxmEWLeTQ2KlqFAIsBmkl9tawoD2zoKyfAo
_K4m0c9QIvcGRgL4t-L7xSY5aABxSgsaGwFdSuwXarSGRRPHDo6VNFsj0223KC-SKNo2wQX0wbKA_m5gwjyPSUYvgI-3FyPXvZHVColGr44FImz8MEhDbk37
YvPKfIOVQtB2xGuOJGgxNxSeTNgFZfdDjSaY/index-0000003424-89GT.ts)
```
It doesn't seem related as you were seeing stuttering every second so I still believe it is a player issue as was pointed out previously, but if anyone sees similar errors or stuttering every few second try to restart your connection to the stream to see if that helps.
