### ISSUE TITLE
Request Plugin: fujitv.live

### ISSUE THREAD

**Issue by maruparu** [streamlink/streamlink#1170]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I'm not sure if it is possible, but I came across this website called [Fujitv](https://fujitv.live/fujitv) that has both livestream and achieve for Japanese TV. 
It seems that you require a subscription, but somehow the you can continue to watch the video. I have tried to look at Requested URL from Network Traffic and I got something like

`http://live.fuji.live:9083/query/GyfRlTa-nHOMUo9FHJARfqJ_2-dXRTbRDYiA0TSyFbE=.json?type=vod&pageUrl=http%3A%2F%2Fplay.fujitv.live%2Ftvplayer%2Fmain.html&playerUrl=http%3A%2F%2Flive.fuji.live%3A9083%2Fglobal%2Fplayer.swf`

However I'm not sure how to identify the video URL and how to proceed from this...since I am quite new to this area. (but I do want to learn!)

### Expected / Actual behavior

Use Livestream to live-streaming the video from fujitv.live

### Environment details

Operating system and version: OSX 10.10.5
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by lki2019** [comment]
The flow analysis of this station seems to be difficult

**Comment by L2501** [comment]
if you want to record iptv buy one with normal m3u8 streams, not one of these chinese one that use malware packers like doswf and secneo

**Comment by back-to** [comment]
This won't work with streamlink.
