### ISSUE TITLE
Plugin request: kakaoTV

### ISSUE THREAD

**Issue by talizea** [streamlink/streamlink#1172]
### Checklist
- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description
http://tv.kakao.com/ <- some Koreans refuse to stream on twitch. In 2017. Anyway, kakao requires some flash-player-esque browser plugin in order to watch streams in high quality on their website. Would be really cool to simply use streamlink instead! :3

### Reproduction steps / Explicit stream URLs to test
1. http://tv.kakao.com/channel/2891562/livelink/1332449?metaObjectType=Channel

**Comment by lki2019** [comment]
<pre><code>
http://tv.kakao.com/channel/2653335/cliplink/376142568?bucket=toros_kakaotv_pc_home_base&where=kakaotv_pc_home


http://daumkakao-kbs-h.smartmediarep.com/smc/daumkakao/multi/eng/K02_PS-2017107453-01-000_SC07/2f6b62732f54323030302d303032372f54323031372d303633385f534330375f32303137303831355f50532d323031373130373435332d30312d3030305f4d344832373030305f7433342e6d7034/0-0-0/content.mp4?solexpire=1502920112&soltoken=cbaef8dbfbfaf9767d738ff7d92f881d&soltokenrule=c29sZXhwaXJlfHNvbHBhdGhsZW58c29sdXVpZA==&soluriver=2&soluuid=216955c6-2d9e-43bc-b7a6-671cf913f4d5&itemtypeid=34&tid=9a27525683363ff3e993992310927f25


http://tv.kakao.com/channel/2711620/cliplink/376142363?bucket=toros_kakaotv_pc_home_base&where=kakaotv_pc_home


http://cdn.videofarm.daum.net/vod/v48e4UFJPfUIsNwIgPMFVMs/mp4_720P_2M_T1/movie.mp4?px-time=1502887789&px-hash=0cf756031111e50a5ec7b5c3f9bc1f6b&px-bps=2826751&px-bufahead=10</code></pre>


MP4 straight chain. Very good to download

But there are geographical restrictions, need
