### ISSUE TITLE
Plugin Request: qcams.com

### ISSUE THREAD

**Issue by rykorb** [streamlink/streamlink#1174]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Adult webcam streaming website. Along the same lines of Chaturbate and MyFreeCams

### Reproduction steps / Explicit stream URLs to test

1. https://qcams.com/Val_Arango

**Comment by back-to** [comment]
they use **webrtc**

**it won't work with streamlink**
