### ISSUE TITLE
Google video streaming - is possible to make it seekable?

### ISSUE THREAD

**Issue by shawn1122** [streamlink/streamlink#1177]
Is there a way to make streaming from Google Video seekable? I was able to get the streams playing on MPV and VLC but they are not seekable. http passthrough does not work as both players will return a 403 forbidden error. I also tried transporting the stream via HTTP rather than named pipe and this did not work either. Is this currently possible with the utility?

**Comment by bastimeyer** [comment]
What do you mean with Google video? Youtube, Google Drive, etc?

Seeking is never available when using stdout/stdin or named pipes, as the player is unable to make any kind of requests.

Please see #134 for a discussion regarding seeking in streams/vods...

**Comment by gravyboat** [comment]
Closing since #134 has plenty of discussion on this.
