### ISSUE TITLE
man page lacking on linux.

### ISSUE THREAD

**Issue by Jenriksen** [streamlink/streamlink#1178]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Using "man streamlink" does not provide any manual page on linux.

### Expected / Actual behavior
Information regarding usage and common flags

### Environment details

Operating system and version: Raspbian Jessie latest
Streamlink and Python version: Streamlink 0.7 and Python 2.7.9

**Comment by bastimeyer** [comment]
This is an issue of your distro's streamlink package.
You should notify the package maintainer instead...

For example, on Arch, the man file is set up correctly:
```bash
$ pacman -Qo /usr/share/man/man1/streamlink.1.gz 
/usr/share/man/man1/streamlink.1.gz is owned by streamlink 0.7.0-1
```

**Comment by Jenriksen** [comment]
Thank you, I will try to reach out to the package maintainer of Raspberry Pi NOOBS and have it corrected.
