### ISSUE TITLE
Chaturbate: Invalid URL '': No schema supplied.

### ISSUE THREAD

**Issue by soredake** [streamlink/streamlink#1179]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
```
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/$regional blocked streamer/
error: Unable to open URL:  (Invalid URL '': No schema supplied. Perhaps you meant http://?)
```
...

### Expected / Actual behavior
Playing stream.
...

### Reproduction steps / Explicit stream URLs to test

1. streamlink $regional blocked streamer best
2. ...

### Environment details

streamlink 0.7.0
Python 3.4.5
...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Did you try using `http` as noted in the error?

**Comment by soredake** [comment]
Yes, same error.

**Comment by beardypig** [comment]
Have you tired putting quotes (`"`) around the url? What OS are you using?

**Comment by soredake** [comment]
@beardypig tried, error, Gentoo stable (with some unstable packages).

**Comment by soredake** [comment]
Seems streamlink cannot handle country blocks, youtube-dl returns 
`[ytdl_hook] ERROR: Access Denied. This room is not available to your region or gender.`
streamlink returns
`Invalid URL '': No schema supplied. Perhaps you meant http://?`

**Comment by beardypig** [comment]
Yep, sounds like a bug then, or at least a missing error message :-)

**Comment by foodtooth** [comment]
Same here when trying `$ streamlink -p vlc "http://www.huya.com/gege07" live`

- Latest Arch Linux
- streamlink 0.7.0

**Comment by gravyboat** [comment]
@foodtooth That should be a new issue if one doesn't exist since this is a different plugin.
