### ISSUE TITLE
svtplay forbidden : Solved

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#118]
Could anybody check whether or not svtplay plugin is working ?
I tried it with Swedish proxy and I get following result : 

`[cli][info] Found matching plugin svtplay for URL http://www.svtplay.se/kanaler/
svt24
[plugin.svtplay][error] Failed to extract HLS streams: Unable to open URL: https
://svt13-b.akamaized.net/u/svt13.m3u8 (403 Client Error: Forbidden)
error: No streams found on this URL: http://www.svtplay.se/kanaler/svt24`

**Comment by beardypig** [comment]
I was able to play all the streams on http://www.svtplay.se, the m3u8 files are loaded from an Akamai CDN so you need to make sure that those requests are also proxied. I added `svt*.akamaized.net` to my list of sites to be proxied through a Swedish proxy. 
This worked for me
```
streamlink --http-proxy localhost:8888 http://www.svtplay.se/kanaler/svt1 best
```
I was also able to stream VOD content eg. http://www.svtplay.se/video/10902313/uti-bogda/uti-bogda-sasong-1-avsnitt-4

**Comment by beardypig** [comment]
@karlo2105 did you get this to work in the end?

**Comment by karlo2105** [comment]
No way, because proxy doesn't get https. But if you could redirect plugin to http, it should work on proxy.

**Comment by beardypig** [comment]
@karlo2105 what if you use the `--https-proxy` option too? 
```
streamlink --http-proxy localhost:8888 --https-proxy localhost:8888 http://www.svtplay.se/kanaler/svt1 best
```
You'll need a proxy that supports https as well, but that should work.

**Comment by karlo2105** [comment]
Thanks for tip it's working fine with https-proxy switch. ;)
