### ISSUE TITLE
Question and feature request: return exit codes in the stdout

### ISSUE THREAD

**Issue by rebelvg** [streamlink/streamlink#1181]
----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Not sure if this is the right place to ask. But is there any way to detect and return why streamlink exited in the stdout? I'm making an app around streamlink. And I want to make sure the user actually closed the player and it wasn't an rtmpdump fault or connection or of something else. If it's not possible atm the idea is to add some list of codes and return them in the stdout. For example, 0 - player was closed. 1 - rtmpdump exited with code X. 2 - etc.

**Comment by gravyboat** [comment]
We provide exit codes already. When a player is closed properly (not a ctrl-c interrupt) we return a 0, when there is an error we output the error and return a 1. You can see the exit code with `$?` on all operating systems we support.

**Comment by rebelvg** [comment]
Is there a full list of codes anywhere? Thanks.

**Comment by gravyboat** [comment]
Not as far as I'm aware. I've only ever seen 0 and 1 with the associated error message.

**Comment by gravyboat** [comment]
No discussion in a while and this is out of scope for us.

**Comment by mlindner** [comment]
@gravyboat Bump. This is important. Streamlink doesn't do return codes.
