### ISSUE TITLE
Plugin request: bigo.tv

### ISSUE THREAD

**Issue by lki2019** [streamlink/streamlink#1182]
- [x] This is a feature request.
- [x] I have read the contribution guidelines.

Description

https://streamlink.github.io/plugin_matrix.html

bigo | live.bigo.tv  bigoweb.co | Yes | ---- | -- | -- | --

streamlink http://www.bigo.tv/kaimooknicha best
error: No plugin can handle URL: http://www.bigo.tv/kaimooknicha

streamlink http://www.bigo.tv/kaimooknicha best -o 1.flv
error: No plugin can handle URL: http://www.bigo.tv/kaimooknicha

Reproduction steps / Explicit stream URLs to test

http://www.bigo.tv/kaimooknicha

...

**Comment by gravyboat** [comment]
There is already a plugin for this: https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/bigo.py and an open issue that you commented on regarding it not working: https://github.com/streamlink/streamlink/issues/843
