### ISSUE TITLE
rugbypass.com plugin request

### ISSUE THREAD

**Issue by c-r-r1983** [streamlink/streamlink#1185]
Description

Rugbypass.com live streams rugby and other sports and also keeps the games as backups to play after the match has finished.

Content is geoblocked to certain countries. a Sweden IP will get you access to signup for free for National Rugby League Matches - https://watch.rugbypass.com/secure/subscription?sku=BNRL_PASS

Expected / Actual behavior

They seem to run off akamaihd.net servers but all the things i have tried isnt able to get the stream in one chunk, it wants to download thousands of 1mb or less mp4 files.

Reproduction steps / Explicit stream URLs to test

... http://watch.rugbypass.com/game/raiders-at-warriors-on-08122017
Environment details

Operating system and version: ... windows 10 x64
Streamlink and Python version: ... 0.7.0

...

Comments, logs, screenshots, etc.

screenshots - http://i.imgur.com/fbtykLw.jpg

if someone can get it to work, i owuld be happy to donate some cash to the streamlink project

**Comment by back-to** [comment]
this is **neulion** like #1130 

it should most likely work with this `ufctv.py` file

https://github.com/back-to/streamlink/blob/neulion1/src/streamlink/plugins/ufctv.py

_For more information_
https://github.com/streamlink/streamlink/issues/1130#issuecomment-351119016
