### ISSUE TITLE
Rtmpdump and streamlink can this code be translated into streamlink?

### ISSUE THREAD

**Issue by Bluebuster116** [streamlink/streamlink#1186]
Hi. I am using rtmpdump to record a stream and this is the code I use (see below):
`rtmpdump -v -r "rtmp://cdnp5.iblups.com/ptv/" -a "ptv/" -f "WIN 23,0,0,185" -W "http://p.iblups.com/ptv/jwplayer/jwplayer.flash.swf" -p "http://p.iblups.com/ptv/embedPTV.php?w=560&h=315" -y "ptv" -o record.flv`

Can this code be translated into something that can be used on streamlink?. I would like to use streamlink because it offers the option to use vlc to watch on the computer. I don't know if this question counts as an issue. Any help?

**Comment by gravyboat** [comment]
You'll have to play with the options to see if you can get it working, this doesn't really qualify as an issue with Streamlink unfortunately and we don't want to set the precedent of helping people convert their commands, especially when you are using it to download a copy of a stream.

**Comment by Bluebuster116** [comment]
@gravyboat It really does not help much with my question i thought i could use streamlink to watch that stream on vlc. Where should i ask for these kind of questions or related in the future, in some other forum perhaps?.

**Comment by gravyboat** [comment]
If you just want to watch that site you probably want to make a plugin request as I don't see a plugin entry for iblups. We don't have any kind of maintained IRC or chat/forum for those types of questions. The team simply isn't big enough to provide that level of support, and most of the time people do spend is put towards project improvements.

**Comment by RosadinTV** [comment]
@Bluebuster116 
Try this:
`"rtmp://cdnp5.iblups.com/ptv/ptv live=1 pageUrl=http://p.iblups.com/ptv/embedPTV.php swfVfy=http://p.iblups.com/ptv/jwplayer/jwplayer.flash.swf"`

**Comment by johnthecracker** [comment]
@Bluebuster116


You want to play this in a way: rtmpdump > streamlink > vlc, using streamlink where it is redundant.

This can be played in a simpler way: rtmpdump > vlc.

rtmpdump -v -r "rtmp://cdnp5.iblups.com/ptv/" -a "ptv/" -f "WIN 23,0,0,185" -W "http://p.iblups.com/ptv/jwplayer/jwplayer.flash.swf" -p "http://p.iblups.com/ptv/embedPTV.php?w=560&h=315" -y "ptv" | vlc.exe -


Your rtmpdump parameters and command as a whole are fine what makes me surprised that somebody of putting
it together perfectly fine has not heard about this forum:

http://stream-recorder.com/forum/rtmpdump-f54.html

http://stream-recorder.com/forum/tags/

**Comment by johnthecracker** [comment]
Issue is closed, so we talk in relaxed way.

Here are other ways to play this:

ffplay:

`ffplay.exe -i "rtmp://cdnp5.iblups.com/ptv/ptv app=ptv pageUrl=http://p.iblups.com/ptv/embedPTV.php swfUrl=http://p.iblups.com/ptv/jwplayer/jwplayer.flash.swf live=1"
`

**Comment by Bluebuster116** [comment]
@RosadinTV and @johnthecracker Thanks ありがとうございました ^_^ I was not sure how to use the code so had to wonder what way should i write the sentence to work with streamlink.

About stream-recorder forum, i am familiar with it but it has recently been filled with ads and nonsense threads with no replies, therefore it was a warning flag for me to skip it in advance. あなたは私の要求を無視しない。 ありがとうございました 

About ffmpeg when used for recording it generates this DTS message. Is it a bad thing?. Playing a live stream on vlc hides the error. I have met similar problems when converting from flv to mp4 some files using ffmpeg. :)

**Comment by johnthecracker** [comment]
You may search in google for answers on error messages and ignore them If program works.

It is to your disadvantage why you did not look at old posts on stream-recorder forum.

I am sure that all the answers to simple questions like yours are there.

http://stream-recorder.com/forum/tags/
