### ISSUE TITLE
vaughnlive plugin not working..

### ISSUE THREAD

**Issue by JourneyOver** [streamlink/streamlink#1187]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Vaughnlive streams are not working

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

seems to be a replica of the closed issue https://github.com/streamlink/streamlink/issues/1034

Every stream just comes back with "error: No playable streams found" 

### Environment details

Operating system and version: Windows 10 x64
Streamlink and Python version: 0.7.0 ( and the latest dev buld from https://dl.bintray.com/streamlink/streamlink-nightly/ ) 

### Comments, logs, screenshots, etc.

This is happening even on the latest night/dev build
Doing "-l debug" doesn't seem to produce anything at all either, just throws the same error: no playable streams found even though the streams are working just fine in browser..

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
@JourneyOver which channel? I tested a few and they still work for me ...

**Comment by JourneyOver** [comment]
I tested about 5-10 of them, all in the misc section, but as you say they are working now..so idk what was going on with vaughnlive when I was trying to watch something earlier..

**Comment by gravyboat** [comment]
@beardypig I'm waiting for the 500th change where we decide to stop supporting it (especially considering a lot of it is stolen content).. Closing since we can't duplicate.

**Comment by mmetak** [comment]
I tried a couple of channels and I get this:

```
$ streamlink -l debug https://vaughnlive.tv/atlantis4 worst
[cli][info] Found matching plugin vaughnlive for URL https://vaughnlive.tv/atlantis4
error: No playable streams found on this URL: https://vaughnlive.tv/atlantis4
```

Streams play in browser though. Maybe they changed something upstream again?

**Comment by fadster** [comment]
Seems changes have been made to the site today. The plugin was working this morning but all of a sudden I'm getting "No playable streams found" on all channels. Should I open a new issue?

**Comment by gravyboat** [comment]
@fadster No let's just open this one back up, there are already 25 vaughnlive issues...

**Comment by mmetak** [comment]
I get the "No playable streams found" after successfully opening and playing two or three times.

**Comment by gravyboat** [comment]
Could be that Vaughnlive is doing some kind of rate limiting now to potentially try to keep people from downloading multiple streams at once which has the side effect of prohibiting streamlink users?

**Comment by fadster** [comment]
I tracked down the problem to the `http.get()` call used to get the stream name in `_get_streams()`. By hardcoding the stream name instead of parsing the result of that call, I got it to work. The recent changes simply broke that part of the code so the fix should be trivial.

**Comment by c769214** [comment]
this the the problem now...

 streamlink -p "mpv --title=FUJI  --mute --screen=1 --geometry=400x225-0+770"  http://www.vaughnlive.tv/sherming5 best
[cli][info] Found matching plugin vaughnlive for URL http://www.vaughnlive.tv/sherming5
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'playpath': 'live_sherming5', 'pageUrl': 'http://www.vaughnlive.tv/sherming5', 'live': True, 'rtmp': 'rtmp://198.255.17.18/live?xKI2Dbx2rCpwXztBIhEENEmys4WgqqFZ', 'flv': '-'}, redirect=False> (No data returned from stream)
error: Could not open stream <RTMPStream({'playpath': 'live_sherming5', 'pageUrl': 'http://www.vaughnlive.tv/sherming5', 'live': True, 'rtmp': 'rtmp://198.255.17.18/live?xKI2Dbx2rCpwXztBIhEENEmys4WgqqFZ', 'flv': '-'}, redirect=False>, tried 1 times, exiting
[cli][info] Closing currently open stream...

**Comment by fadster** [comment]
@c769214 I assume you hardcoded the channel's name to get this message, otherwise you would've gotten the "No playable streams found" error. If so, all you need to do is retry the command until it plays, it's just timing out a lot at the moment.

**Comment by fadster** [comment]
I took a closer look at the result of that broken `http.get()` call. The site is now detecting the request as coming from a bot and isn't returning the channel's page. It appears to be using Distil scrape protection and spoofing the user agent isn't enough to circumvent it. Perhaps we could use something like this: https://github.com/Anorov/cloudflare-scrape

**Comment by lekans** [comment]
Thanks to this link and youtube tutorial:
https://www.youtube.com/watch?v=oNR5xKstlgY
posted in this thread 11 days ago:
https://github.com/streamlink/streamlink/issues/1034

I managed to get streamlink working again, this is example command which I'm using atm:
treamlink --http-header "Referer=https://vaughnlive.tv/unccharlie2" "hls://https://hls-ord-1a.vaughnsoft.net/nyc/live/live_unccharlie2/chunklist.m3u8" worst

I hope this will give you extra information needed to solve this problem :\

**Comment by beardypig** [comment]
It might be reasonable, as @fadster suggests, to use the channel name from the URL and have a mapping from domain to channel id prefix. That coudflare scraper is interesting, but it does execute JavaScript to get the tokens which makes me a be wary...

**Comment by beardypig** [comment]
If anyone wants to test out the changes you can take a look at my fork on the vaughnlive branch, specifically this commit: c799f38ddf41d264725d8ecaa6828cfa66e7703f.

**Comment by JourneyOver** [comment]
@beardypig looks to be working, tested a couple streams and had no issues with loading them up.

**Comment by JourneyOver** [comment]
@beardypig haven't had any issues the past 2 days since testing your changes, so think everything is good to go for now on your changes!

**Comment by fadster** [comment]
@JourneyOver Out of curiosity, have you been experiencing a lot of timeouts when trying to open a stream ("No data returned from stream" error, as posted by @c769214 above)? In the past couple of weeks, I've had to retry several times before streams finally play.

**Comment by JourneyOver** [comment]
@fadster not a lot but every now and then it'll throw that error, but whenever it does it'll always connect on the second go through on trying the stream.

**Comment by fadster** [comment]
The site is undergoing more changes, in particular to the RTMP server IPs. It seems the code hasn't been finalized yet as some channel pages require several reloads before the stream plays. At this time, the only server that has been working consistently is 66.90.93.42, so you may want to edit the `rtmp_server_map` variable accordingly. I expect this to change at any moment.

**Comment by JourneyOver** [comment]
can confirm, as of at least yesterday. 2 days ago I usually always had it connect on second go through of trying the steam, now it takes several tries before connecting completely.

**Comment by fadster** [comment]
The code has changed again. For the time being, this is working for me:

```python
    rtmp_server_map = {
        "594140c69edad": "66.90.93.42",
        "585c4cab1bef1": "198.255.17.34",
        "5940d648b3929": "198.255.17.34",
        "5941854b39bc4": "66.90.93.42"}
```

@JourneyOver Only one of these entries hasn't changed (the third one), so I imagine that's the one you're hitting when you eventually get it working after several tries.

**Comment by JourneyOver** [comment]
more than likely, will try with your server_map and see how things go over the next day or two.

**Comment by fadster** [comment]
One more thing. sapi-ws-1x05.vaughnlive.tv is not responding properly today ("Handshake status 522"), so the script fails when this wss server is randomly selected.

**Comment by Bluebuster116** [comment]
Has the hls source code been changed?. I've tried to pick up the stream from vaughnlive and it is not connecting. :(

**Comment by jshir** [comment]
c799f38 plus fadster's updated rtmp_server_map got me going today.

**Comment by Bluebuster116** [comment]
@fadster Can you look into those rtmp_server_map's again?. I am already using @beardypig plugin, the stream stops working after some minutes. It disconnects in intervals between 2~4 minutes requiring reconnect manually which is very inconvenient.

**Comment by jshir** [comment]
@Bluebuster116 If you are making a connection in the first place, the rtmp server map is correct. Perhaps there's a connectivity issue between you and the streaming provider, or even between the streamer and the streaming provider. I recorded a 2.5 hour long stream with no interruptions last night.

I have a script that loops the streamlink command up to 100 times in case of disconnects and that has served me well.

**Comment by Bluebuster116** [comment]
@jshir Vaughnlive is making constant changes thus I believe there is an issue with the rtmp's though. Can you post the script that were you referring?. That would come in handy if i can test it.

**Comment by jshir** [comment]
@Bluebuster116 Literally just a batch containing the streamlink command repeated 100 times with output filename 00, 01... 99.

**Comment by Bluebuster116** [comment]
@jshir Some users have reported streamlink (after upgrading to ver 0.8.1) is closing early when the connection is poor or is having some issues with hls sources. Can you share the batch file you created?.

**Comment by TimLChan** [comment]
Looks like there's new mapping

```
  var param1:* = param1.replace("594140c69edad","198.255.17.18");
         param1 = param1.replace("585c4cab1bef1","198.255.17.18");
         param1 = param1.replace("5940d648b3929","198.255.17.34");
         param1 = param1.replace("5941854b39bc4","198.255.17.34");
         this.Server = param1;
```

**Comment by beardypig** [comment]
Sorry I haven't been able to look at this yet. I'll get on it tomorrow :-) Thanks for the research @fadster!

**Comment by fadster** [comment]
@beardypig My pleasure! :simple_smile:

**Comment by fadster** [comment]
New server map:

```python
    rtmp_server_map = {
        "594140c69edad": "66.90.93.42",
        "585c4cab1bef1": "66.90.93.34",
        "5940d648b3929": "66.90.93.34",
        "5941854b39bc4": "66.90.93.42"}
```

**Comment by cloud90** [comment]
how to view vaughn channel? O.o

**Comment by beardypig** [comment]
@fadster are you working these out manually? Decompiling the flash client gives slightly different results. Looks like @TimLChan decompiled the flash client before to get that map. I have updated my branch with the latest rtmp server map.

**Comment by fadster** [comment]
@beardypig Yes, I've decompiled the flash client. Before the latest changes, there was a snippet of javascript code that effectively bypassed the flash code. This javascript code was removed three days ago and the map is now exclusively determined in flash.

**Comment by beardypig** [comment]
@fadster ah, ok. That explains that. I have the same map in my latest branch, however I replace the `192` address with one of the others as it might cause issues - although `5941854b39bc4` probably won't ever be returned (I imagine it's for testing).

**Comment by fadster** [comment]
@beardypig Actually, it gets returned about as often as the other three. I added some extra logging to keep track of this. This is probably part of some load balancing scheme. They seem to be currently experimenting with new servers and address spaces so the map is likely to keep changing for a while longer.

**Comment by TVGPlayer** [comment]
@beardypig It's working:

rtmpdump -r "rtmp://66.90.93.42/live" -a "live?hVU5bXP1IPZOox9hMvCmh8pZjJDi6BqK"
 -f "WIN 27,0,0,130" -W "https://vaughnlive.tv/4520191431/swf_v7/VaughnSoftPlaye
r.swf" -p "https://vaughnlive.tv/embed/video/lmshows_koq?viewers=true&autoplay=t
rue" --live -y "live_lmshows_koq" | "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe
" -


C:\Users\Lenovo\Documents\- RTMPDump\RTMP Dump>rtmpdump -r "rtmp://66.90.93.42/l
ive" -a "live?hVU5bXP1IPZOox9hMvCmh8pZjJDi6BqK" -f "WIN 27,0,0,130" -W "https://
vaughnlive.tv/4520191431/swf_v7/VaughnSoftPlayer.swf" -p "https://vaughnlive.tv/
embed/video/lmshows_koq?viewers=true&autoplay=true" --live -y "live_lmshows_koq"
   | "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" -
Closing connection... done!

**Comment by Bluebuster116** [comment]
Hls and m3u8 is not working for vaughnlive. Has it changed?. I'm trying to catch vaughnlive.tv/sherming6

**Comment by beardypig** [comment]
@Bluebuster116 yes, only rtmp is available at the moment.

**Comment by bobvargas** [comment]
hey @beardypig i was wandering whats the ip for vaughnlive sherming3 because streamlink showing up as no playable stream

**Comment by gravyboat** [comment]
@bobvargas That isn't something that @beardypig will know. It's not our job to keep track of vaughnlive IP addresses. There are a variety of tools you can use to find this information out.

**Comment by jshir** [comment]
@bobvargas FWIW, the recent IP map is working for me on that stream right now.
`    rtmp_server_map = {
        "594140c69edad": "66.90.93.42",
        "585c4cab1bef1": "66.90.93.34",
        "5940d648b3929": "66.90.93.34",
        "5941854b39bc4": "66.90.93.42"}`

**Comment by fadster** [comment]
@jshir You really should be using the map I posted for the sake of proper load balancing. It is still the one used in the latest flash client.

@beardypig You may want to update your branch to avoid any confusion. Thanks!

**Comment by bobvargas** [comment]
@jshir  then how to make it a command?

**Comment by wlerin** [comment]
@bobvargas I think you have to add them directly to the [vaughnlive.py plugin](https://github.com/streamlink/streamlink/blob/1b74cdaba7c274dbf7de85540216f5b057921937/src/streamlink/plugins/vaughnlive.py#L41). That said, doing so still leaves me with "No playable streams found".

**Comment by Bluebuster116** [comment]
@beardypig Has the hls option restored or is it still only by rtmp?. These constant map changes got me confused. Yet still trying to get vaughnlive.tv/sherming6 any help with this?.

**Comment by beardypig** [comment]
@Bluebuster116 still only RTMP. My latest version of the plugin is available on my fork: [vaughnlive.py](https://raw.githubusercontent.com/beardypig/streamlink/vaughnlive/src/streamlink/plugins/vaughnlive.py)

**Comment by cirrusUK** [comment]
@Bluebuster116 As a temp workaround for .m3u / .m3u8  you can use F12 on the browser, hit network tab and filter out .m3u or .m3u8 for source URL, which can then be played with 'mpv sourceurl.m3u8' or 'cvlc sourceurl.m3u'
good luck

**Comment by ringtvt** [comment]
@beardypig  I updated vaughnlive.py but error command:

![image](https://user-images.githubusercontent.com/29664904/31571708-0493c4a6-b0c2-11e7-82b9-84f9e799e3fc.png)

**Comment by gravyboat** [comment]
@ringtvt We do not support that sort of functionality. Why would we support restreaming a stream? It makes no sense and goes against the purpose of the project.

**Comment by ringtvt** [comment]
@gravyboat  thank u. i see. 
When i use command
 streamlink https://www.youtube.com/watch?v=In29IvQ-VxY best -o  "D:\lol.mp4"    it work
 but when i use command 
streamlink http://instagib.tv/kireita  best -o "D:\lol.mp4"   it not work
Comments, logs, screenshots.
![image](https://user-images.githubusercontent.com/29664904/31572572-b53bf966-b0d3-11e7-88dc-41f095db0b2d.png)
Please help me. Thank you

**Comment by fadster** [comment]
@beardypig I highly recommend updating your server map to include all three servers as I have posted above to correctly duplicate the load balancing behavior of the flash client.

**Comment by beardypig** [comment]
@fadster ah yeah, I read it before as being in one of the private reserved IP ranges... Updated now.

**Comment by Bluebuster116** [comment]
@gravyboat Do you mind telling me how can I get the rtmp address which has been posted above?. i'm referring to this one rtmpdump -r "rtmp://66.90.93.42/live" -a "live?hVU5bXP1IPZOox9hMvCmh8pZjJDi6BqK" I would like to obtain it from vaughnlive.tv/sherming6
I have already used rtmpdumphelper and in the command log appears the address but it cannot be played again as the network closes connection in the second attempt. It seems that it only works when the window with the flashplayer video is showing. Could it be that there is something I'm missing?. Need help.

**Comment by fadster** [comment]
@Bluebuster116 It would be much easier if you just grabbed the updated `vaughnlive.py` from beardypig's branch.

**Comment by TVGPlayer** [comment]
@Bluebuster116 Try using VLC as a streamer.

**Comment by Bluebuster116** [comment]
@fadster Okay I just did that and it works. But I'm confused which one is the "current" fork you were referring to?. Do you mean this [https://github.com/streamlink/streamlink/blob/c799f38ddf41d264725d8ecaa6828cfa66e7703f/src/streamlink/plugins/vaughnlive.py](url)? I have downloaded this version [https://github.com/streamlink/streamlink/releases/tag/0.8.1](url) but I don't know if its the one you guys are using.

**Comment by mmetak** [comment]
@Bluebuster116 https://github.com/beardypig/streamlink/blob/vaughnlive/src/streamlink/plugins/vaughnlive.py

**Comment by back-to** [comment]
@beardypig 
looks like it still works, maybe merge it?
