### ISSUE TITLE
Stadium plugin request

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#1188]
### Checklist

- [x ] This is a feature request.

### Description

Can anyone help with a plugin for Stadium TV here:

https://watchstadium.com/live/

Cheers!

**Comment by gravyboat** [comment]
Can you provide more details on the streams or what the network connection looks like etc.?

**Comment by unlocKing** [comment]
https://04476b7c682c4da8b8b4bfe23ef879c1.midas.us-east-1.amazonaws.com/v1/manifest 

m3u8 from amazon ends up to this playable:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:35988
#EXT-X-PROGRAM-DATE-TIME:2017-08-26T22:07:22.133Z
#EXTINF:6.006,
https://stadiumlivein-i.akamaihd.net/hls/live/522512/mux_4/20170824T060520/master_3000/00071/master_3000_00488.ts

**Comment by lki2019** [comment]
https://04476b7c682c4da8b8b4bfe23ef879c1.midas.us-east-1.amazonaws.com/v1/manifest/61a556f78e4547c8ab5c6297ea291d6350767ca2/Mux/ffe7bfb2-e4dc-4d43-8f8c-48868174d97c/0.m3u8

**Comment by unlocKing** [comment]
Already have that but when the stream changes a plugin will be able to get the correct stream again.

**Comment by gravyboat** [comment]
Did you mean to close this?

**Comment by unlocKing** [comment]
Actually no, not sure how that happened.. I only just noticed.. can you  please look into this new plugin. Thanks.

**Comment by RedPenguin2** [comment]
Just to let folks know, this is the exact same issue as this:

https://github.com/streamlink/streamlink/issues/687

It's a channel run by Sinclair and bearybig stated #EXT-X-DISCONTINUITY is an issue when the "We'll be right back" shows up instead of commercials.

**Comment by unlocKing** [comment]
@RedPenguin2 

What do you mean, this channel has been playing fine when you grab the end stream. I think you made a comment on the wrong issue.

I just wanted to know if a plugin was possible as the stream changes.
