### ISSUE TITLE
Create a known issues page

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#119]
As noted by @sbstp [here](https://github.com/streamlink/streamlink/issues/115#issuecomment-258031463) it might be a good idea to add a known issues page to the docs.

**Comment by sbstp** [comment]
I would just create contributing guidelines that mention known issues, so that people will see them before opening issues. We get the VLC+Youtube Live one pretty often.

**Comment by scottbernstein** [comment]
Yeah, that's true.  That comes up at least once a month

________________________________

**Comment by waseem18** [comment]
Hi,

I'm new to Streamlink and would love to work on this issue as it is a low-hanging-fruit.

Awaiting your reply.

Thank You.

**Comment by gravyboat** [comment]
@waseem18 Feel free to prep a PR and we'll review it.

**Comment by beardypig** [comment]
There is a list of known issues in the docs, albeit hidden in the [players](https://streamlink.github.io/players.html#known-issues-and-workarounds) page. Perhaps we should pull it out in to its own page?

**Comment by sbstp** [comment]
Most of the issues are related to players though.

**Comment by beardypig** [comment]
That is true, I just wonder how easy it is to find. I suppose as long as it's linked to it should be fine.

**Comment by gravyboat** [comment]
Do we want to close this now that #218 is merged?

**Comment by beardypig** [comment]
So, turns out there is also an issues page in the docs: https://streamlink.github.io/issues.html :) 

Should these pages be merged? Seems strange to have two different pages that are very similar, we could link from the players page to the issues page...

**Comment by back-to** [comment]
https://streamlink.github.io/issues.html#common-issues
https://streamlink.github.io/players.html#known-issues-and-workarounds
