### ISSUE TITLE
Plugin request:live.qq.com

### ISSUE THREAD

**Issue by kesdoputr** [streamlink/streamlink#1190]
### Checklist

- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description
I use streamlink to view china streams like douyu and huomao.
and live.qq.com is another china streams site for sports.
Could someone write a plugin for the site **live.qq.com**?

ex:
http://live.qq.com/10005384

**Comment by gravyboat** [comment]
Any additional details you can provide regarding what network traffic, etc. looks like would be appreciated.

**Comment by kesdoputr** [comment]
live.qq is like douyutv,and when stream is about sports will on it.
So maybe is similar with douyu.

**Comment by fozzysec** [comment]
live.qq.com uses the same structure like douyu.com there are similar APIs and actually douyu.com and live.qq.com has some co-operations. Some modify on the current Douyutv plugin can make it be able to stream live.qq.com. The only problem existing is that we need to reverse engineering the swf player of live.qq.com to get the API key.

**Comment by gravyboat** [comment]
@fozzysec Is the streaming on this site legitimate streams as opposed to stolen content? I just want to make sure we aren't adding more restream sites.

**Comment by fozzysec** [comment]
@gravyboat There are no legal problem with live.qq.com, I think all of their content are permitted such as some sports channel. But those license may only apply to Mainland China, but it is not what we concern about, watching streams on it out of Mainland China is ok.
