### ISSUE TITLE
[query] HTML Parsing

### ISSUE THREAD

**Issue by captn3m0** [streamlink/streamlink#1192]
I was working on a plugin for fmovies/mycloud and was wondering if there is an easy way for a plugin author to parse HTML? I don't see beautiful soup as a dependency so what is the recommended way of doing this?

I need to parse HTML to get a couple of parameters for fetching the stream URLs

**Comment by beardypig** [comment]
Generally we just use a regex to extract parts from HTML. You could use regex and then XML parsing if the HTML is suitably formatted...

**Comment by captn3m0** [comment]
I didn't want to use [regex for html](https://stackoverflow.com/a/1732454), but if that's recommended I'll go with that.

**Comment by beardypig** [comment]
There are some short comings when using regex to extract data from HTML, but usually it's sufficient as you normally only need to extract a URL or few tokens.

**Comment by captn3m0** [comment]
Thanks 👍
