### ISSUE TITLE
Trying to stream...

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#1197]
Hey @bastimeyer @beardypig @chrippa  I want to to see if anyone can figure out this address to play in streamlink:
http://185.2.83.186/jp-tvtokyo/embed.html?dvr=false&token=8510f9b9dcc754fc8a05e75b1400655a0d52f58b-5a477dbd548c91bd9d816eb4f416f59a-1504403321-1504381721 let me know if you got everything right because sherming66 just got banned on vaughnlive.tv and i need a stream to play again thanks!

**Comment by gravyboat** [comment]
Is this a restream of a tv tokyo stream? If they were banned why not just put in a plugin request for the actual site doing the streaming?

**Comment by bobvargas** [comment]
@gravyboat I don't know the actual site maybe jp-tvtokyo?

**Comment by TisIte** [comment]
Looks to be from http://artv.watch/countries/japan/, TV-Tokyo link at the bottom.
or http://artv.watch/countries/japan/tv-tokyo-%e3%83%86%e3%83%ac%e3%83%93%e6%9d%b1%e4%ba%ac/
#1124 was already closed out earlier from request of site owner.

**Comment by gravyboat** [comment]
Yeah if that is the case we can't support this @bobvargas. The site owner has requested we don't as they won't be able to pay for the costs if we bypass ads since they are a small operation.

**Comment by MickelCL** [comment]
@bobvargas The link you provided is working fine here. For you information i am using a [Singapore vpn](urlhttps://www.ivacy.com/singapore-vpn/) to access Geo restricted content and browse streams and torrents. 
Check it out.

**Comment by gravyboat** [comment]
I have edited the above comment by @MickelCL to remove a direct link to a VPN provider as it has been linked here as well as
