### ISSUE TITLE
no more "develop" branch.

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#12]
We should use the Github flow (https://guides.github.com/introduction/flow/) and no-longer have the development branch.

It's **much** easier to develop from from the master branch and split it off into weekly / monthly releases rather than further sharding our development from master and dev branches.

**Comment by fishscene** [comment]
Not that I have any real ownership over this branch, but I created the "develop" branch to model the workflow in livestreamer, but if that doesn't suit us, let's remove it.

Green light from me.

**Comment by gravyboat** [comment]
Agreed, not a fan of having a development branch, makes it way too confusing for people to contribute when we can just branch and tag releases.

**Comment by fishscene** [comment]
"develop" branch is no more. Marking completed.
