### ISSUE TITLE
vaughnlive plugin not see stream...

### ISSUE THREAD

**Issue by Vinizavr** [streamlink/streamlink#1202]
Hello. Need help with this problem:
![ng8citx](https://user-images.githubusercontent.com/20253710/30158450-90b15114-93ef-11e7-8602-7471b2491abc.png)
vaughnlive.tv/sherming3 working but streamlink not see him. How fix this problem?

P.S: Sorry for my bad english.

**Comment by gravyboat** [comment]
Duplicate of https://github.com/streamlink/streamlink/issues/1187.
