### ISSUE TITLE
Automatically store youtube live video and create a download link

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#1206]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
The youtube live video that I want to record is : https://www.youtube.com/watch?v=E1j6MMm_UuM

The problem is that I always have to sit in front of my computer at a fixed time and press the buttons to record it. Can there be any feature that a particular time of the live video is recorded everyday ( say from 9 am to 930 am) and I get a download link or some sort of that.

This would be so helpful

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This is way outside the scope of Streamlink. You would need to write some kind of wrapper code/application.
