### ISSUE TITLE
plugin request

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1207]
please create plugin for this website hls link expires in 60 seconds like filmon.
it has plenty of hd streams....tnx

</script><script>console.log('http://de.kineskop.tv/hlsx/426/426.m3u8?id=_STA511869&watch_time=60&watch_start=1504990771&p=e3d9e3a30495b79f');</script>
 
website link is below
http://kineskop.tv/?page=watch&ch=426

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 2 - Sites which are hosting stolen content as their main source of content
