### ISSUE TITLE
Option to see at what time of the VOD streamlink is stopped/interrupted

### ISSUE THREAD

**Issue by PrPierre** [streamlink/streamlink#1209]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

I use streamlink on my raspberry pi with VLC or Omxplayer. Both of these players on Raspberry don't have controls once the video starts (that means no video seeking).

Now that I use the experimental command "--hls-offset-start", I am finally able to start any VOD at a specified time. However, if the stream interrupts itself, or if I stop it, I have absolutely no idea of the time I have to specify to start again at the right time.

I don't think this is already possible with streamlink, but I think it could be really useful for this case, if there was an option that outputs the time of the VOD once streamlink stops.

Would it be a good idea ?

**Comment by gravyboat** [comment]
I'm not sure if the logic implementation for this would be that easy, but since you're on a pi you can use the `time` command to see how long a process runs, so just call `time streamlink --hls-offset-start VAL URL` or whatever you have been running. I'll leave this open for discussion, but there's a workaround at least.

**Comment by back-to** [comment]
**not** the **best solution**,
but it could be **easily** added after the Download debug message

```
[stream.hls][debug] Download of segment 156 complete 0:05:12
[cli][info] Starting player: /usr/bin/mpv
[stream.hls][debug] Download of segment 157 complete 0:05:14
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 158 complete 0:05:16
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 159 to queue
[stream.hls][debug] Adding segment 160 to queue
[stream.hls][debug] Download of segment 159 complete 0:05:18
[stream.hls][debug] Download of segment 160 complete 0:05:20
```

```diff
--- a/src/streamlink/stream/hls.py
+++ b/src/streamlink/stream/hls.py

+from datetime import timedelta

-        self.logger.debug("Download of segment {0} complete", sequence.num)
+        self.logger.debug("Download of segment {0} complete {1}", sequence.num,
+                          timedelta(seconds=sequence.num * sequence.segment.duration))

```

**Comment by beardypig** [comment]
@back-to that might make the debug messages more useful too :)

**Comment by back-to** [comment]
_it's a different code version than above_

it looks good if the hls file is setup correctly

```
[stream.hls][debug] Download of segment 7994 complete - Time 04:26:28
[stream.hls][debug] Download of segment 7995 complete - Time 04:26:30
[stream.hls][debug] Download of segment 7996 complete - Time 04:26:32
[stream.hls][debug] Download of segment 7997 complete - Time 04:26:34
[stream.hls][debug] Download of segment 7998 complete - Time 04:26:36
[stream.hls][debug] Download of segment 7999 complete - Time 04:26:38
[stream.hls][debug] Download of segment 8000 complete - Time 04:26:40
```

but it might be confusing if the hls file is not setup correctly

```
[stream.hls][debug] Download of segment 103988 complete - Time 291:09:59
[stream.hls][debug] Download of segment 103989 complete - Time 291:10:09

[stream.hls][debug] Download of segment 103990 complete - Time 284:14:21

[stream.hls][debug] Download of segment 103991 complete - Time 291:10:29
[stream.hls][debug] Download of segment 103992 complete - Time 291:10:39

[stream.hls][debug] Download of segment 103993 complete - Time 284:14:51

[stream.hls][debug] Download of segment 103994 complete - Time 291:10:59
[stream.hls][debug] Download of segment 103995 complete - Time 291:11:09

[stream.hls][debug] Download of segment 103996 complete - Time 284:15:20

[stream.hls][debug] Download of segment 103997 complete - Time 291:11:29
```
