### ISSUE TITLE
Streamlink without installation

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#1211]
Hi,
 ----- I know nothing about python-------
I have download the zip folder from here: https://github.com/streamlink/streamlink-portable/releases

And I am running the exe file and it asks me to input : "Type a valid command"
I am a giving command : streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "C:\Users\name\Videos\ok.ts" https://www.youtube.com/watch?v=E1j6MMm_UuM 144p

But after that nothing happens and it says : [ Streamlink for windows v.0.7.0] 

I am using windows 7 64 bit machine. **And  i am looking for a streamlink file in which I do not have to install the file and I can directly run streamlink.**
Do I have to install VLC for this?

----

### Checklist

- [x] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
@RosadinTV can probably answer your question best.

**Comment by rusty148** [comment]
@beardypig  
i) Do I need to post this question somewhere else?
ii) Do you know of any technique of using streamlink without installation, can you guide me doing that?

Thanks

**Comment by rusty148** [comment]
@beardypig
i) Do I need to post this question somewhere else?
ii) Do you know of any technique of using streamlink without installation, can you guide me doing that?

Thanks

**Comment by beardypig** [comment]
I provide an [alternative portable version](https://github.com/beardypig/streamlink-portable/releases) which gives you a `bat` file run from the command line which wraps all the python invocation and portable config file locations. You can give that a go, just use it as per the normal streamlink docs (from the command line: `cmd`).

**Comment by rusty148** [comment]
----I am a noobie----
So I open the zipped folder. What should I do next? Run the bat file?

This command will work? streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "C:\Users\name\Videos\ok.ts" https://www.youtube.com/watch?v=E1j6MMm_UuM 144p
Like if I want to record this: https://www.youtube.com/watch?v=E1j6MMm_UuM

**Comment by rusty148** [comment]
This thing helped. Thank you so much guys for your help.

Is there any page or document where I can read about the journey or streamlink/livestream?

**Comment by RosadinTV** [comment]
@rusty148 
You can find CLI documentation here:
https://streamlink.github.io/cli.html

**Comment by gravyboat** [comment]
Going to close this since it seems solved.

**Comment by rusty148** [comment]
Thank you so much guys. :)
