### ISSUE TITLE
Plugin request for http://webcast.gov.in/

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#1222]
Hi,

This is a plugin request for http://webcast.gov.in/.

There are following channels inside. 
http://webcast.gov.in/ddpunjabi/
http://webcast.gov.in/ddkisan/
http://www.webcast.gov.in/vyaslive
http://webcast.gov.in/

I am using streamlink portable downloaded from here:  https://github.com/streamlink/streamlink-portable/releases

I am looking for something like this : set url=http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD251L720P/playlist.m3u8
streamlink.exe --http-header "Referer=http://www.zengatv.com/live/f132cc60-7635-4b74-b4e9-ce8c43727635.html" hlsvariant://%url% best

source : https://github.com/streamlink/streamlink/issues/890

Thanks
----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by rusty148** [comment]
--http-header "Referer=http://webcast.gov.in/ddpunjabi/" --player "C:\Program Files (x86)\Windows Media Player\wmplayer.exe" -o "C:\ddb.mp4" hlsvariant://http://http://nicls3-lh.akamaihd.net/i/ddpunjabi_1@122402/master.m3u8 144p


I am using this command, please let me know what's missing

**Comment by sdfwv** [comment]
- you are using `http://` twice
- you don't need a Referer
- **144p** does not exists, it's **576p** for me or **best / worst**

```
streamlink hls://http://nicls3-lh.akamaihd.net/i/ddpunjabi_1@122402/master.m3u8 best
# or
streamlink hls://http://nicls3-lh.akamaihd.net/i/ddpunjabi_1@122402/master.m3u8 best -o 123.mp4
```
should work.

**Comment by rusty148** [comment]
Hi, I tried different combinations and finally this command worked for me:
--http-header "Referer=http://webcast.gov.in/ddpunjabi/" --player "C:\Program Files (x86)\Windows Media Player\wmplayer.exe" -o 123.mp4 hlsvariant://http://nicls3-lh.akamaihd.net/i/ddpunjabi_1@122402/master.m3u8 worst  

For the first channel. Now I am trying for other channels as well.

**Comment by rusty148** [comment]
@RosadinTV 
Can you please let me know what are you doing in #1224 . 

I am new to python, so That's why I am asking.

**Comment by RosadinTV** [comment]
@rusty148 Sure, untill PR is approved you can create a file named "webcast_india_gov.py" and place it inside "Releases\Streamlink\streamlink\plugins"
```
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http, useragents
from streamlink.stream import HLSStream

class WebcastIndiaGov(Plugin):
    _url_re = re.compile(r'https?://(?:www\.)?webcast.gov.in/.+')

    @classmethod
    def can_handle_url(cls, url):
        return cls._url_re.match(url)

    def _get_streams(self):
        try:
            url_content = ""
            http.headers = {'User-Agent': useragents.ANDROID}
            if "#channel" in self.url.lower():
                requested_channel = self.url.lower()[self.url.lower().index('#channel')+8 :]
                url_content = http.get('http://webcast.gov.in/mobilevideo.asp?id=div' + requested_channel).text
            else:
                url_content = http.get(self.url).text
            hls_url = url_content[: url_content.rindex('master.m3u8') +11]
            hls_url = hls_url[hls_url.rindex('"')+1 :]
            return HLSStream.parse_variant_playlist(self.session, hls_url)
        except:
            self.logger.error("The requested channel is unavailable.")

__plugin__ = WebcastIndiaGov
```
Then you can open/download the desired channel URL:
http://webcast.gov.in/ddpunjabi/ best -o "ddpunjabi.ts"
Or with channel number:
http://webcast.gov.in/#Channel1 best -o "ddnews.ts"
http://webcast.gov.in/#Channel3 best -o "loksabhatv.ts"

**Comment by rusty148** [comment]
I made the file and put it in the folder. But still there is problem with
http://webcast.gov.in/vyaslive/ worst -o "vyas.ts"

**Comment by rusty148** [comment]
Thank you, it is working.
