### ISSUE TITLE
plugin request - giniko.com

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1226]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

can some one make plugin for this site please..
http://www.giniko.com/watch.php?id=358
source of page shows sorce with key

file: "http://nimlive3.giniko.com/gemjunior/gemjunior/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OS8xNi8yMDE3IDE6MDk6NDcgUE0maGFzaF92YWx1ZT1TbWNQMUJYOGNuTkI5ZVNYSTc0eEhnPT0mdmFsaWRtaW51dGVzPTE0NDA="

**Comment by johnthecracker** [comment]
Until your plugin is ready you may consider this alternative.

http://stream-recorder.com/forum/watch-bbc-world-news-giniko-vlc-t23334.html

**Comment by dreamboxco** [comment]
There seems to have been a problem with the database.
Please try again by clicking the Refresh button in your web browser.

An E-Mail has been dispatched to our Technical Staff, who you can also contact if the problem persists.

We apologise for any inconvenience.

**Comment by back-to** [comment]
It does not match the requirements.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
