### ISSUE TITLE
Installation version issue?

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1228]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

I have an issue using the tvplayer.com plugin (although not the same as reported recently in #1227) but before posting I realised that I'm currently running on 0.7.0 - unless my eyes deceive me the current version on git is 0.8.1.

However using both the PPA and pip methods on the [install page](https://streamlink.github.io/install.html) show that my current version is the latest. Even stranger, when I clone git and install manually I still end up with 0.7.0! Am I missing something?

**Comment by ryanjgillies** [comment]
I finally got myself up to date when I spotted the command `pip install -U git+https://github.com/streamlink/streamlink.git` which has now got me up to version 0.8.1

**Comment by gravyboat** [comment]
The PPA probably hasn't been updated by the maintainer. Going to close this out for now since you resolved it.

**Comment by ryanjgillies** [comment]
Can I be a pain and ask who the maintainer is, and if I can beg them to update the PPA?

PIP is causing all manner of havoc with my distro, I'd much rather run off the PPA if at all possible!

**Comment by ryanjgillies** [comment]
Apologies, I spotted that @hotice / andrew@webupd8.org is the maintainer - I'll go beg him!

That'll teach me not to search for things first.

**Comment by gravyboat** [comment]
I'm surprised pip is causing an issue since Python is standard with all distros as far as I am aware. Do you have the latest version of pip?

**Comment by ryanjgillies** [comment]
Ever since I installed pip I've been receiving "BadStatusLine" errors on practically all plugins.

I had the same error occur on a different machine and briefly mentioned it in #1130 as after reading around the issue it appeared to be a potential python bug, I can only presume installing pip has now introduced that same bug onto the distro in question (Lubuntu 16.04).

I did notice in Synaptic that I have the python2 version of streamlink installed, but a python3-streamlink package is also available. Is there anyway I can use the python3 version of streamlink via the pip installation method...? Perhaps this could get around any potential python bug.

**Comment by gravyboat** [comment]
If your distro has Python 3 installed you can remove streamlink then reinstall via python3: https://docs.python.org/3/installing/index.html#work-with-multiple-versions-of-python-installed-in-parallel

**Comment by anniman** [comment]
i wondered why i couldnt get streamlink working with tvplayer plugin and came across this issue. i to have version 0.7.0 and input the command to update 
pip install -U git+https://github.com/streamlink/streamlink.git
but get errors 
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log
i'm using ubuntu 14.04. how can i update streamlink past 0.7.0
