### ISSUE TITLE
Plugin request: GloboPlay

### ISSUE THREAD

**Issue by magnot** [streamlink/streamlink#1229]
Hello,

I would like to request a plugin. GloboPlay now provides users (it requires login) live stream of their TV channel. Unfortunately, MPC can't handle the m3u8 link. Although watching the TV through the browser is totally OK, being able to stream via MPC would let me use SVP - 60fps videos. So basically people would be able to watch movies, sports, F1 sessions, local news etc with a SVP capable player.

I can't get to technical about it but these are the links I was able to get through Chrome:
- m3u8: https://live.video.globo.com/dvr/m/crypto/globo-rj/globo-rj_3475/playlist.m3u8 (3475 might be related to user current session)
- An .TS file is picked from the playlist
- Sometimes a .BIN file is retrieved, it might be some sort of key
- I believe there are two more links related to the stream which I really don't know what they actually mean.

I really appreciate if anyone can help.
Thanks in advance.

**Comment by back-to** [comment]
1. As **nobody has an Account** for this site, we can't take a quick look if it could work with streamlink
2. The Kodi Addon needs **DRM** for some live streams
    https://github.com/olavopeixoto/plugin.video.brplay
    which won't work with streamlink

**closing**, because of this points.
