### ISSUE TITLE
How to seek in an youtube live video

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#1233]
Hi,
This is a feature request. 
https://www.youtube.com/watch?v=E1j6MMm_UuM
This is the channel. So if I use -o at this time, it would start recording from the current time. Is there any feature through which I can record what was streamed an hour ago?

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

**Comment by scottbernstein** [comment]
use the --hls-live-edge parameter.  The higher the number you put in, the farther back into the stream it goes.  That said, I have not done the math to figure out how the numbers equate to time, but you can easily use some trial and error to get to the point in the video that you seek.
________________________________

**Comment by gravyboat** [comment]
This is also a duplicate: https://github.com/streamlink/streamlink/issues/884 so I'm going to close it.

**Comment by rusty148** [comment]
I have used this command : "--hls-live-edge 99999 --hls-segment-threads" but it is not working.

**Comment by rusty148** [comment]
@RosadinTV your take on this?
I have used this command : "--hls-live-edge 99999 --hls-segment-threads" but it is not working.
My full command is: 
--hls-live-edge 99999 --hls-segment-threads 5 --player "C:\Program Files (x86)\Windows Media Player\wmplayer.exe" -o "C:\Users\dd1.mp4" https://www.youtube.com/watch?v=E1j6MMm_UuM best

**Comment by RosadinTV** [comment]
@rusty148 For 1 hour "rewind" in a Youtube live stream i think --hls-live-edge 720 should work.
But unfortunately this video does not support live seeking 😞 
So, probably nothing can be done.
