### ISSUE TITLE
keyboard interrupt should not exit with code 0

### ISSUE THREAD

**Issue by AndCycle** [streamlink/streamlink#1234]
currently streamlink exit with 0 when hit by keyboard interrupt, 
it's hard to handle within automation script,

https://unix.stackexchange.com/questions/223189/what-does-exit-code-130-mean-for-postgres-command
 
 - if the process exited with exit(n) or return n from main(): the lower 8 bits of n (n & 0xFF).
 - if the process was killed by signal n: n + 128.

that do have some convention so people can handle them graceful with script

**Comment by bastimeyer** [comment]
Could you please send a PR with a fix here:
https://github.com/streamlink/streamlink/blob/0.8.1/src/streamlink_cli/main.py#L1041-L1057

Related issue: #781 (which btw looks like it has been closed by accident)
https://github.com/streamlink/streamlink/blob/0.8.1/src/streamlink_cli/main.py#L247-L257

**Comment by AndCycle** [comment]
@bastimeyer thanks for the head up, I will just left this here by now, will do PR if I have free time,
