### ISSUE TITLE
Error when writing to output: [WinError 10053]

### ISSUE THREAD

**Issue by Carrybag1** [streamlink/streamlink#1236]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description

When trying to open streams sometimes it will not open the stream and give the below error. Ever since I decided to update my streamlink from 0.5.0

"error: Error when writing to output: [WinError 10053] An established connection was aborted by the software in your host machine, exiting"

This completely stops happening when I uncheck "reconnect to stream" in streamlink settings

Unsure if this means it's something in the streamlink gui or streamlink itself

**Comment by skulblakka** [comment]
This has been reported before but sadly no progress was made. See #916 and #975
