### ISSUE TITLE
Spectrum Live TV m3u8 support?

### ISSUE THREAD

**Issue by Rick7C2** [streamlink/streamlink#1237]
I was just curious if streamlink can be used with Spectrum Live TV?

I was able to find links to the m3u8 files but they are encrypted with AES-128,URI="faxs://faxs.adobe.com

I tried this command, Got the cookie info from dev tools.

`streamlink --http-cookie "twc-user-profile={"city":"MyCity","state":"TX","zipcode":"zipcode","region":"TX","soaid":"CTX.1360","maxxEligible":"false","onNetwork":"true","hasBeenOnNetwork":"true","visitorType":"customer","customerStatus":"existing","hasTwcid":"true","hasTv":"false","hasInternet":"true","hasPhone":"false","hasHomeWifi":"false","modemModelNumber":"MCUSTMOD","accountType":"Residential","serviceVendorName":"","prevCluPath":""}; s_fid=6F4420297FA7C3FE-16A750BC08CAACF6; AMCV_5BB1123F5245AE4E0A490D45@AdobeOrg=793872103|MCIDTS|17431|MCMID|78856063516145419608061085082656075695|MCAID|NONE; ipAndDivision_v1="{\"ipAddress\":\"48.258.13.75\",\"soaDivisionId\":\"CTX.8260\"}"; s_lastvisit=1506018266166; s_nr=1506218666167-Repeat; s_v75=zFJ7vxnUY%2F4633s66i0rIYV5c5RQYj; device_id=eb2f70dd-1e9c-2db8-a022-4de3c9521cc0" "hlsvariant://http://linear-scope010.timewarnercable.com/LIVE/1024/hls/ae/ANE_HD/index.m3u8" best --player-external-http`

And got the following...

`[cli][info] Found matching plugin stream for URL hlsvariant://http://linear-scope010.timewarnercable.com/LIVE/1024/hls/ae/ANE_HD/index.m3u8
[cli][info] Available streams: 132k (worst), 180p_alt2, 180p_alt, 180p, 270p, 360p, 540p, 720p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.3.200.50:12862/
[cli][info]  http://127.0.0.1:12862/
[cli][info]  http://192.168.1.27:12862/
[cli][info] Got HTTP request from VLC/3.0.0-git LibVLC/3.0.0-git
[cli][info] Opening stream: 720p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: faxs://faxs.adobe.com (No connection adapters were found for 'faxs://faxs.adobe.com')
[cli][error] No data returned from stream`

Am I missing something? Can this type of stream be done?

I'm hoping to be able to let streamlink capture the stream so  I can play via tvheadend.

**Comment by beardypig** [comment]
It looks like the stream is protected by Adobe's DRM system, this means that streamlink cannot play stream. We don't support playing DRM streams, it's not possible. Sorry.

**Comment by Rick7C2** [comment]
That's what I was afraid of. Thanks anyways! :D

Closing.
