### ISSUE TITLE
camsoda plugin not working.

### ISSUE THREAD

**Issue by ls117** [streamlink/streamlink#1238]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

GETTING PLUGIN NOT FOUND ERROR, EVEN AFTER SAVING CAMSODA.PY TO PLUGINS FOLDER. WTF

### Reproduction steps / Explicit stream URLs to test

1.https://www.camsoda.com/charlie3x215

### Environment details

Operating system and version: windows 8.1
Streamlink and Python version: 1.5.7

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by ls117** [comment]
its working but the instructions are like braille. after i type the url and it tells me the available  streams, what exactly do i type next.

**Comment by sdfwv** [comment]
- https://github.com/streamlink/streamlink#quickstart
- https://streamlink.github.io/cli.html#tutorial

```
streamlink STREAMURL best
```

you need to choose a quality before you press enter

**Comment by ls117** [comment]
would like an answer. idm was my main workhorse, but yesterday it started catching .ts files instead of a continuous stream. so im without a reliable method to record. i refuse to pay for getflv and the cracks/patches wont work. kodi was good but it crashes sometimes for no perceivable reason, im hoping this or streamloader will do.

**Comment by gravyboat** [comment]
@ls117 This is free software and everyone volunteers their time to answer questions. You are not paying us for a subscription or license of any kind so expecting and demanding timely answers is both rude and ridiculous. Streamlink is designed for streaming and we happen to support recording. The documentation has covered every question you have posed so far in this issue: https://streamlink.github.io/cli.html#file-output-options. Please refer to the documentation prior to creating issues, and remember that anyone answering a question is doing so out of their own kindness. They are taking time out of their day to help you.

**Comment by ls117** [comment]
theres no need to act like you have a stick up your ass. just do your fucking job

**Comment by ls117** [comment]
like you types always act like that. its a support page for a reason, you dont wanna answer questions then dont have a support page.  miss me with that fucking attitude

**Comment by gravyboat** [comment]
@ls117 This is not a support page, nor is this my "job" (I make $0 working on this software). The issues page is for reporting problems with the software, or noting that you couldn't figure out how to do something because it didn't exist in the docs, etc. As I've linked to the answer to your question I'm going to close this.
