### ISSUE TITLE
bigo.tv streams fails

### ISSUE THREAD

**Issue by JohnDoh666** [streamlink/streamlink#1239]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

bigo.tv streams fails to load

### Expected / Actual behavior

`streamlink http://www.bigo.tv/32266506 best &

[cli][info] Found matching plugin bigo for URL http://www.bigo.tv/32266506
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://45.255.132.57:7783/list_3676193094_2104705102_0.m3u8')> (Could not open stream: Unable to open URL: http://45.255.132.57:7783/list_3676193094_2104705102_0.m3u8 (HTTPConnectionPool(host='45.255.132.57', port=7783): Read timed out. (read timeout=20.0)))
error: Could not open stream <HLSStream('http://45.255.132.57:7783/list_3676193094_2104705102_0.m3u8')>, tried 1 times, exiting

[2]-  Exit 1                  streamlink http://www.bigo.tv/32266506 best`

### Reproduction steps / Explicit stream URLs to test

Any bigo.tv streamer URL

### Environment details

MacOS 10.12.6
Python 2.7
Streamlink 0.81

...

### Comments, logs, screenshots, etc.

Also tested on Windows with same result. The weird thing is that bigo.tv streams doesnt load in any web browser for me either. I have also tried loading through a VPN without any luck. Did they block access through their website? Am I the only one with this issue?

**Comment by sdfwv** [comment]
yes it's geo blocked or very slow in some regions.

try a Japan vpn, it would load with it.

**Comment by JohnDoh666** [comment]
Thanks, I tried a Japanese VPN and it worked. Also, the mobile app works without a VPN, that might be a backdoor in for you guys in the know.

**Comment by gravyboat** [comment]
Going to close this out, thanks for providing an answer @sdfwv!
