### ISSUE TITLE
Twitch stream closing causes MPC-HC, Powershell to hang.

### ISSUE THREAD

**Issue by leamsifigs** [streamlink/streamlink#124]
While i viewing a twitch stream, it went offline for about 15 seconds. On my screen, the video froze then the application became unresponsive. Closing the MPC-HC window forcefully still leaves the powershell window hanging and repeating an error.

**Comment by beardypig** [comment]
Do you have a log of the error, or a screenshot of the Powershell output?

**Comment by leamsifigs** [comment]
I do not, but I think I can recreate it.



On Fri, Nov 4, 2016 at 6:57 AM -0700, "Beardypig" <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have a log of the error, or a screenshot of the Powershell output?

-

**Comment by leamsifigs** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7841769/20035256/7039cd26-a39a-11e6-8dfd-9a9b5e9839db.png)

This is the error I got previously when the stream went down. I've also had the same error when i take out my ethernet cable while a stream is playing. This still causes Powershell and MPC-HC to hang.

**Comment by gravyboat** [comment]
Hmm, I've been watching some streams lately (specifically beyondthesummit, but it really doesn't matter) and I haven't seen this error while using VLC. Can you try VLC and see if you get the same error? It would be nice to confirm if this issue is specific to MPC-HC, or if it's something specific going on with how Streamlink is working on your system.

**Comment by gravyboat** [comment]
@leamsifigs Have you had a chance to confirm whether this issue is unique to MC-HC or not?

**Comment by gravyboat** [comment]
I'm going to close this for now since I haven't heard back in several weeks. Please feel free to open it back up.

**Comment by leamsifigs** [comment]
I've tried it with VLC installed, and I got a similar error that repeated about 10 times.

![untitled](https://cloud.githubusercontent.com/assets/7841769/23282360/a960daa4-f9d5-11e6-8031-e7ea54e5d942.png)

This is the resulting log.
I can provide a pastebin copy if the exact log text is required.
