### ISSUE TITLE
Streamlink 0.8.1 not working, lacks PySocks

### ISSUE THREAD

**Issue by lazycrypt** [streamlink/streamlink#1240]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

When upgrading to Streamlink 0.8.1 is ceased to work. The error the command line would return said it was missing a requirement, PySocks, which has to be installed manually for Streamlink to continue working.

### Expected / Actual behavior

Try to start watching any stream with Streamlink 0.8.1 and a fresh install of Python 3.6.2.

### Reproduction steps / Explicit stream URLs to test

Error:
1. streamlink [any link] best
2. Get error

Remedy:
1. pip install PySocks
2. streamlink [any link] best
3. Works!

### Environment details

Operating system and version: Win10 x64
Streamlink and Python version: Streamlink 0.8.1 and Python 3.6.2 x64
Streamlink installed using pip (pip install streamlink).

### Comments, logs, screenshots, etc.

PySocks should probably be added as a requirement.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by skulblakka** [comment]
This is a PIP related issue and has been discussed here #1195

**Comment by gravyboat** [comment]
Closed as duplicate. As noted on that other issue we might just fix this ourselves...
