### ISSUE TITLE
Vaughnlive plugin is 50/50 works or not...

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#1241]
Hey guys vaughnlive plugin is starting to break again.

Sometimes the stream can go though.

other times the plugin may not detedt the url and gives you a no playable streams found message
even if the website version works. 

Please check the vaughnlive plugin @chrippa  @beardypig @gravyboat thanks again.

**Comment by gravyboat** [comment]
@bobvargas Please add to the existing open issue: https://github.com/streamlink/streamlink/issues/1187 and you'll need to provide actual data for what isn't working, whether it is specific streams, the output that fails versus succeeds, etc. I'm going to close this.
