### ISSUE TITLE
[Feature request]Auto split -o output files after certain time / size reached

### ISSUE THREAD

**Issue by 29988122** [streamlink/streamlink#1245]
Why is this feature needed:
I frequently use streamlink to record twitch / youtube live channel included esports and regular stream such as cat live cam.
When certain record session is like... 5 hours or longer, the file become incredibly huge. This is bad for moving / categorizing. 
And, the length of the file makes it difficult to seek for later watching.

tl;dr:
It could be very convenient when output file reached specified length / specified file size, it changed its output file name to... say, 2.mp4.

Thank you for your contributing! I love this project.

**Comment by gravyboat** [comment]
We've already discussed similar things in the past (https://github.com/streamlink/streamlink/issues/1035, https://github.com/streamlink/streamlink/issues/1242) and it's not something that is really worth adding to Streamlink as it is out of scope for the project (streaming, not downloading). I would suggest writing a wrapper script of some kind to achieve this functionality or you could see if an application like youtube-dl does what you need.

**Comment by skulblakka** [comment]
> I would suggest writing a wrapper script 

This has also already been discussed with livestreamer. @29988122 In theory you should be able to use the wrapper scripts we discussed [over there](https://github.com/chrippa/livestreamer/issues/1558).

**Comment by 29988122** [comment]
Thank you for all the info provided! Will look into them :)

**Comment by 29988122** [comment]
I'd like to contribute the windows batch script I wrote:
It produces a new file every hour for 10 hours.

```
set loopcount=10
set filename=1
:loop

start "streamlink-lol" streamlink -o "D:\%filename%.mp4" https://twitch.tv/riotgames best
set /a loopcount=loopcount-1
set /a filename=filename+1
timeout /t 3600
taskkill /FI "WINDOWTITLE eq streamlink-lol
if %loopcount%==0 goto exitloop
GOTO loop

:exitloop
```
