### ISSUE TITLE
python-iso3166 missing?

### ISSUE THREAD

**Issue by dimitry-ishenko** [streamlink/streamlink#1248]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Trying to install streamlink into openjdk docker container and get the following:

    root@316d203f7986:/# add-apt-repository -y ppa:nilarimogard/webupd8
    ...
    root@316d203f7986:/# apt-get install streamlink
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    streamlink : Depends: python-streamlink (= 0.8.1-1~webupd8~artful0) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

Next, trying this:

    root@316d203f7986:/# apt-cache search python-streamlink
    python-streamlink-doc - library to extract video streams from various services - documentation
    python-streamlink - library to extract video streams from various services - Python 2

Hmm, OK... Let's follow the white rabbit:

    root@316d203f7986:/# apt-get install python-streamlink
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
    python-streamlink : Depends: python-iso3166 but it is not installable
                        Recommends: rtmpdump but it is not going to be installed
                        Recommends: python-crypto but it is not going to be installed
                        Recommends: python-librtmp but it is not going to be installed
                        Recommends: ffmpeg but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

Next...

    root@316d203f7986:/# apt-cache search python-iso3166

Silence... Googling `apt get install python-iso3166`...

https://ubuntu.pkgs.org/16.04/webupd8-amd64/python-iso3166_0.8-1~webupd8~xenial_all.deb.html

Hello, Neo.

Downloading [python-iso3166_0.8-1-webupd8-xenial_all.deb](http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/p/python-iso3166/python-iso3166_0.8-1~webupd8~xenial_all.deb)

Running `dpkg -i python-iso3166_0.8-1-webupd8-xenial_all.deb`

Now:

    root@316d203f7986:~# apt-cache search iso3166
    python-iso3166 - Standalone ISO 3166-1 country definitions for Python 2

Mr. Anderson, welcome back. We missed you.

Retrying:

    root@316d203f7986:~# apt-get install streamlink         
    ...
    root@316d203f7986:~# streamlink 
    [cli][info] streamlink is running as root! Be careful!
    usage: streamlink [OPTIONS] <URL> [STREAM]
    
    Use -h/--help to see the available options or read the manual at https://streamlink.github.io
    root@316d203f7986:~#

Matrix rebooted.

### Expected / Actual behavior

    root@316d203f7986:~# apt-get install streamlink         
    ...
    root@316d203f7986:~# streamlink 
    [cli][info] streamlink is running as root! Be careful!
    usage: streamlink [OPTIONS] <URL> [STREAM]
    
    Use -h/--help to see the available options or read the manual at https://streamlink.github.io
    root@316d203f7986:~#

Matrix rebooted without all the intervening steps.

### Reproduction steps / Explicit stream URLs to test

See description.

### Environment details

Operating system and version: docker openjdk:latest image
Streamlink and Python version: streamlink 0.8.1, Python 2.7.13

### Comments, logs, screenshots, etc.

Screenshot:
![agent-smith-e1287599713720](https://user-images.githubusercontent.com/2858291/31025734-b58151dc-a511-11e7-8c3a-0408dd598a77.jpeg)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mmetak** [comment]
Based on your log output you're using ubuntu artful? Maybe @hotice can help with this one?
[As far as I can see there's no `python-iso3166` package available in that ppa for artful?](http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/p/python-iso3166/)

**Comment by dimitry-ishenko** [comment]
Thanks @mmetak. Something is funky about that openjdk image. I've switched to ubuntu:latest container and everything worked fine. Thanks for reading my bug report :smile:
