### ISSUE TITLE
No source option available when selecting a youtube stream?

### ISSUE THREAD

**Issue by ConHuevosGuey** [streamlink/streamlink#1249]
Using Streamlink 0.8.1 for windows.

When pointing Streamlink to a Youtube Live Stream there is no source option available, in fact there is never any 60FPS streams available for Youtube.  I don't think this is an issue with Streamlink itself, but is there some sort of workaround that can be performed to extract the 'source' format from a Youtube livestream?

**Comment by gravyboat** [comment]
60fps videos aren't currently supported because of the streaming format they use. We have discussed this before here: https://github.com/streamlink/streamlink/issues/213 so I'm going to close this for now.
