### ISSUE TITLE
Livestreamer will not download from TV3.ie Ireland 

### ISSUE THREAD

**Issue by perrywynkles** [streamlink/streamlink#1250]
Livestreamer will not download from TV3.ie Ireland anymore. They seem to have made changes. Older videos will download but newer ones wont. Can you fix it please so it works on tv3.ie player Ireland like https://www.tv3.ie/3player/show/1283/132731/0/Liar

For instance this one will download
```
livestreamer "hls://http://player.ooyala.com/player/ipad/8xOWNxeDpTVTkARQ3Rn80_xTAQ6TtwG__2200.m3u8" best -o video.ts
```

This one won't 
```
livestreamer "hls://http://player.ooyala.com/player/ipad/BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8" best -o video.ts 
```

I get

```
C:\Users\perry\\Downloads\PORTABLE\livestreamer-v1.12.2-win32\livestreamer-v1.12.2>
C:\Users\perry\\Downloads\PORTABLE\livestreamer-v1.12.2-win32\livestreamer-v1.12.2>livestreamer "hls://http://player.ooyala.com/player/ipad/BqOWR0YzE650YBh4R46D
5sXV44I2zwCp__2200.m3u8" best -o video.ts
[cli][info] Found matching plugin stream for URL hls://http://player.ooyala.com/player/ipad/BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Could not open stream: Unable to open URL: http://player.ooyala.com/player/ipad/BqOWR0YzE650YBh4R46D5sXV44I2zwCp__2200.m3u8 (404 Client Error: Not Found)
```

**It says 404 Client Error: Not Found but the video is here https://www.tv3.ie/3player/show/1283/132731/0/Liar**

I have win 7 64 bit
Thanks
perrywynkles@yahoo.com

**Comment by bastimeyer** [comment]
This is the **Streamlink** repo, not **Livestreamer**. We have forked Livestreamer a year ago and have changed a lot of things since then, so please don't ask Livestreamer specific questions.

The second URL you've posted is returning a 404 error, which indicates an invalid URL. This is not an issue of Streamlink (or Livestreamer).

I can tag this issue as a plugin request, since Streamlink doesn't have a tv3.ie plugin, but it's a region locked streaming service, so this might cause a bit of trouble for the devs to implement it.

**Comment by perrywynkles** [comment]
will a plug in download something that has drm?
P

----- Original Message -----

**Comment by gravyboat** [comment]
@perrywynkles We don't support bypassing DRM, it's too much work and not worth the effort.

**Comment by perrywynkles** [comment]
@gravyboat If you can't be bothered then  i will get rid of streamlink - no good to me

**Comment by gravyboat** [comment]
@perrywynkles Then you should get rid of Streamlink. Not spending time on bypassind DRM is a stance we aren't going to change. I'm going to close this out now.

**Comment by perrywynkles** [comment]
IT IS RUBBISH ANYWAY

----- Original Message -----

**Comment by bastimeyer** [comment]
The joys of maintaining community-driven open source projects and answering questions of people who can't behave themselves...

**Comment by perrywynkles** [comment]
YOUR MESSAGE TO PERRYWYNKLES@YAHOO.COM HAS BEEN [DELETED UNREAD]

----- Original Message -----
