### ISSUE TITLE
Chaturbate not working for some models..

### ISSUE THREAD

**Issue by mltr15** [streamlink/streamlink#1251]
- [x] This is a bug report.

### Description

Chaturbate plugin is not working for some urls.

### Reproduction steps / Explicit stream URLs to test

https://chaturbate.com/kittynaugthy_/

### Environment details

Operating system and version: ... Windows 7
Streamlink and Python version: ... streamlink_latest(02/10/2017)

### Comments, logs, screenshots, etc.

[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/kittynaugthy_/
error: Unable to open URL: https://edge77.stream.highwebmedia.com/live-edge/kittynaugthy_-sd-19716bb4e1168c2d84ff25719711533f5fddd04712d1b36eb2
3a6a4e52009dbf_fast_aac/playlist.m3u8?rp=83084cae78fd06cd7819a62cab6b1eb696890279eeda1c02c77a39432672ae52&u=AnonymousUser&t=%7B%22username%22%3
A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1506984938%2C%22sig%22%3A%22f59c4f8bf7cfe68710c9264f9fb1a5b0e1c987339929b1153a711325f15c8b78%2
2%2C%22room%22%3A%22kittynaugthy_%22%7D (403 Client Error: Forbidden for url: https://edge77.stream.highwebmedia.com/live-edge/kittynaugthy_-sd
-19716bb4e1168c2d84ff25719711533f5fddd04712d1b36eb23a6a4e52009dbf_fast_aac/playlist.m3u8?rp=83084cae78fd06cd7819a62cab6b1eb696890279eeda1c02c77
a39432672ae52&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1506984938%2C%22sig%22%3A%22f59c4f8bf7cfe68
710c9264f9fb1a5b0e1c987339929b1153a711325f15c8b78%22%2C%22room%22%3A%22kittynaugthy_%22%7D)

**Comment by gravyboat** [comment]
Only HLS streams are supported, we've had many issues opened on this topic: https://github.com/streamlink/streamlink/issues/1111. Closing as duplicate.
