### ISSUE TITLE
Streamlink stops downloading twitch video at 2:36:37

### ISSUE THREAD

**Issue by Jendrik3** [streamlink/streamlink#1252]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
When downloading [this twitch video](https://www.twitch.tv/videos/173238279), streamlink stops at 2:36:37

### Expected / Actual behavior
It should download the whole video.

### Reproduction steps / Explicit stream URLs to test

 `streamlink https://www.twitch.tv/videos/173238279 best -o /mnt/drive/Videos/factorio2-2.mp4
`
### Environment details

Operating system and version: Arch Linux, kernel 4.12.13-1
Streamlink and Python version: streamlink 0.8.1, python 3.6.2

### Comments, logs, screenshots, etc.

Full output of the given command:
```
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/173238279
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[download][factorio2-2.mp4] Written 23.04 GB (2h36m37s @ 3.0 MB/s)                       
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
How much of the video is missing? `2h36m37s @ 3.0 MB/s` indicates how long it has been downloading and the current speed.

**Comment by Jendrik3** [comment]
The video is 10:25:38 long, so around 8 hours are missing.

**Comment by beardypig** [comment]
@Jendrik3 please check how long the video you recorded is. `2h36m37s` is the amount of time it was downloading, as you're downloading a VOD it will go faster than realtime.

**Comment by Jendrik3** [comment]
Oops my bad. The video downloaded is complete. I was confused by the duration streamlink showed me and thought it represented the length of the downloaded video. Sorry for wasting your time.
