### ISSUE TITLE
WWE plugin for Clappr?

### ISSUE THREAD

**Issue by hijuuijj** [streamlink/streamlink#1253]
Is there any way to apply the WWE plugin for Clapp player?

**Comment by beardypig** [comment]
I don't know what Clapper is, but the answer is almost certainly no. If you want to request a plugin you need to include a lot more detail. For example, which website do you want a plugin for? http://network.wwe.com is already supported, is there another WWE site?

**Comment by gravyboat** [comment]
@beardypig I just checked and it's some sort of web player (aka stealing streams and restreaming them) so no we won't support this.
