### ISSUE TITLE
www.huya.com stream wont open

### ISSUE THREAD

**Issue by Rhyyn** [streamlink/streamlink#1256]
### Checklist

- [x] This is a bug report.

### Description

Works perfectly fine with twitch but any Huya streams does not work
Maybe it has something to do with the fact that you need an Huya account to see HD streams ?

### Expected / Actual behavior

Tried with " " , and without the http:// doesnt work either

### Reproduction steps / Explicit stream URLs to test

1. http://www.huya.com/xiaozhan
2. http://www.huya.com/s7

### Environment details

Operating system and version: Windows 10 / Version 1607 / 14393.1715
Streamlink and Python version: Latest Streamlink and 3.6.3 python
Country : France

### Comments, logs, screenshots, etc.

![streamlink](https://user-images.githubusercontent.com/32547725/31235870-d882b028-a9f2-11e7-9475-124f564682f9.png)

**Comment by gravyboat** [comment]
Closing since #1284 is merged.
