### ISSUE TITLE
Installation failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by philiprenich** [streamlink/streamlink#1257]
### Checklist

- [x] This is a bug report.

### Description

I am trying to install on an oDroid headless system running Ubuntu 16.04. Initially I tried using `sudo pip install streamlink` as shown in the Readme of this repo. That claimed to work, but when trying to load a Twitch stream or YouTube video, I would get the error `pkg_resources.UnknownExtra: requests 2.9.1 has no such extra feature 'socks'`

After seeing specific Ubuntu installation instructions on this page https://streamlink.github.io/install.html I removed streamlink with `pip` and followed the `apt` instructions instead. New repository added and updated, _check_. When running `sudo apt install streamlink` I received an error about unmet dependencies: `streamlink : Depends: python-streamlink (= 0.8.1-1~webupd8~xenial0) but it is not going to be installed` So I tried to install that and got the same issue for `python-cryptodomex`, and stepping down to install that said there was no installation candidate.

I feel like I may be missing an unexplained step or dependancy that is not installed on my system that is expected.

### Expected / Actual behavior

Apt install to just work (naive?)

### Environment details

Operating system and version: Ubuntu 16.04.1 LTS
Streamlink and Python version: No streamlink, Python 2.7.12

**Comment by mmetak** [comment]
With the latest version of streamlink in that ppa you need to enable ubuntu universe repos.
```
sudo add-apt-repository universe
sudo apt-get update
```

**Comment by philiprenich** [comment]
Apparently it's already enabled for all sources. Do I need higher than Python 2.7.12?

**Comment by mmetak** [comment]
I just installed minimal ubuntu xenial with debootstrap and it works.
- enable universe repo, update
- add ppa, update, install streamlink & mpv
- all working

> When running sudo apt install streamlink I received an error about unmet dependencies: streamlink :  Depends: python-streamlink (= 0.8.1-1~webupd8~xenial0) but it is not going to be installed

This is the part why I believe universe repo is not enabled/updated? Because I got that same error.
Could you please check your `/etc/apt/sources.list` file to make sure there is universe enabled?

**Comment by philiprenich** [comment]
I’m a bit new to this all, but here are the Contents of that file:


deb http://ports.ubuntu.com/ubuntu-ports/ xenial main universe restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial main universe restricted

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main universe restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main universe restricted

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted

deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security universe
deb http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ xenial-security multiverse

**Comment by mmetak** [comment]
Yeah... I'm blind. ;-) Sorry about that. There're are no packages for arm architecture in that ppa.

@beardypig , dumb question, but, shouldn't `requests` deps.append be set to >=2.10.0?
He installed streamlink with pip and it shows `requests 2.9.1`, but requests got support for socks in 2.10.0.

> 2.10.0 (2016-04-29)
+++++++++++++++++++
> **New Features**
> - SOCKS Proxy Support! (requires PySocks; ``$ pip install requests[socks]``)

**Comment by datzuma** [comment]
You'll need to install python-socks (on 17.10) to be able to launch streamlink without a problem.

**Comment by philiprenich** [comment]
@mmetak Ah ok, so currently the Odroid's ARM architecture isn't supported, at least for the apt-get method with the ppa?

@datzuma Can you be a little more detailed for me please as working in Linux is pretty new for me? Is that a `pip install python-socks` or something? If the 17.10 refers to Linux versions, I'm on 16.04

**Comment by datzuma** [comment]
@philiprenich open terminal and run: 

>  sudo apt install python-socks -y; sudo pip install streamlink

and then start watching streams: 

> streamlink URL QUALITY

:) sorry for late reply

**Comment by Hunterek** [comment]
Have the same problem with ubuntu server and streamlink stop working in some day. This what some other put are working pip install python-socks

**Comment by back-to** [comment]
This can be closed, same issue that is already fixed
https://github.com/streamlink/streamlink/issues/1341#issuecomment-346829178
