### ISSUE TITLE
error: EOF occurred in violation of protocol (_ssl.c:645)

### ISSUE THREAD

**Issue by dustycy** [streamlink/streamlink#1258]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I have got a wrapper command file that invokes streamlink on some models at CB. If the webcam of the model is one  streamlink starts saving the broadcast to a file. However, I have noticed that there are occasional "Unable to open URL" errors: (EOF occurred in violation of protocol (_ssl.c:645)).

### Expected / Actual behavior

If the webcam of a model is not on, streamlink should exit with a "No playable streams found on this URL":  

error: No playable streams found on this URL: https://chaturbate.com/little_mystery/

### Reproduction steps / Explicit stream URLs to test

1. streamlink "https://chaturbate.com/little_mystery/" best --hls-segment-threads 4 -o "little_mystery.flv"
2. ...
3. ...

### Environment details

Operating system and version: Windows 10 Pro 1703
Streamlink and Python version: Streamlink v0.8.1 and Python v3.5.2

### Comments, logs, screenshots, etc.

[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/little_mystery/
error: Unable to open URL: https://chaturbate.com/get_edge_hls_url_ajax/ (EOF occurred in violation of protocol (_ssl.c:645))
[End of Streamlink for Windows with ExitCode 1]

I think the nginx server at CB has TLS session reuse enabled for passive connections which was not supported until python3.6.

A google search reveals that there are other people who are also receiving similar error messages using different programs that are based on python, but I could not find a definitive solution to this problem. This should probably be resolved by the python people.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
it's not the python version,
it works with Python v3.5.2 and windows 10 from the .exe installer

---

it was probably some issue with **there servers** or some **outdated version on your system**

_not streamlink_

#1255  #1301 have most likely the same issue.

**Comment by bastimeyer** [comment]
Going to close this, since the source of the issue doesn't seem to be the plugin.
Feel free to reopen.

**Comment by gravyboat** [comment]
Thanks for closing all of these @bastimeyer!
