### ISSUE TITLE
Zattoo plugin even when provided both email & password tries logging in with password only

### ISSUE THREAD

**Issue by spookyahell** [streamlink/streamlink#1259]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I was trying to figure out what's wrong since I manage to log in with browser just fine and then I can't figure out what's wrong for a while - since I at first thought it is an issue with a header but--- No it is not.
This is the kind of error I like laughing at since it is so obvious that it can't work... it sends a login request without including the login email in the request body... and that's where I just thought... "LOL" but whatever that is definetly the problem - just wanting to enter with a password - well that won't ever work..

### Expected / Actual behavior

being able to log into Zatoo

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Windows 7
Streamlink and Python version: 0.8.1 streamlink (although it play no role whatsoever)

...

### Comments, logs, screenshots, etc.

I hope whoever reads this doesn't think I am being rude... I am only amused about this situation since it has happend to me before to while programming...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by spookyahell** [comment]
hmm.. weired after looking at the plugin source... it seems set up okay... I don't know what the issue then is...

**Comment by gravyboat** [comment]
Can you paste the command output with `-l debug` (but omit your password).

**Comment by spookyahell** [comment]
here it is:
`[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/vox--zattoo-email
[plugin.zattoo][debug] _hello ...
[plugin.zattoo][debug] _login ... Attempting login as None
error: Unable to open URL: https://zattoo.com/zapi/v2/account/login (400 Client Error: Bad Request for url: https://zattoo.com/zapi/v2/account/login)
`

**Comment by spookyahell** [comment]
command was: `C:\Users\Lucas Halbig\Downloads\wimpdl>streamlink -l debug "https://zattoo.com/w
atch/vox"--zattoo-email lucas.halbig@gmail.com --zattoo-password PASSWORD`

**Comment by bastimeyer** [comment]
You're missing a space between the `--zattoo-email` parameter name and the stream url. See the error message...

**Comment by spookyahell** [comment]
Okay you are right I overlooked that but it shouldn't be sending requests that expect a bad response anyway...

**Comment by bastimeyer** [comment]
The way you specified the parameters, you basically told streamlink to look for a different stream url without login credentials. The server response of the login request the plugin is making in this case is 400 (access restricted), which makes sense, because login credentials are missing.
I'm closing the thread since it's a user error.
