### ISSUE TITLE
Adulst Swim: support for live streams

### ISSUE THREAD

**Issue by stepshal** [streamlink/streamlink#126]
http://www.adultswim.com/videos/streams/
http://www.adultswim.com/videos/streams/toonami - subtitles available,
http://www.adultswim.com/videos/streams/toonami-pre-flight
http://www.adultswim.com/videos/streams/marathon
http://www.adultswim.com/videos/streams/last-stream-on-the-left

**Comment by stepshal** [comment]
Ahh, i couldn't watch them now, they probably geo-restircted now.

**Comment by beardypig** [comment]
Fixed in #139 :)
