### ISSUE TITLE
Bongacams fails to load stream

### ISSUE THREAD

**Issue by mrowen01** [streamlink/streamlink#1262]
Hi, the bongacams plugin doesn't seem to work.
Here's the error message:

[cli][error] Unable to open URL: https://bongacams.com/modelname (HTTPSConnectionPool(host='bongacams.com', port=443): Max retries exceeded with url: /modelname (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75f8c7b0>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by Damianonymous** [comment]
It seems that everything works without change.

https://s1.postimg.org/6t3nxcsgr3/Bonga_Cams.jpg

**Comment by mrowen01** [comment]
Ok sorry, I'm a moron.
I had to whitelist bongacams.com on my Pi-Hole.

**Comment by gravyboat** [comment]
I'm going to close this since it's resolved, thanks for the update.
