### ISSUE TITLE
vrt.nu plugin: delay between image and sound

### ISSUE THREAD

**Issue by lillet23** [streamlink/streamlink#1266]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

vrt.nu (Belgian Flemish television) plugin works fine, but after some time, there is a delay between image and sound, whatever the quality or the player you choose.

### Expected / Actual behavior

Image and sound should be synchronized.

### Reproduction steps / Explicit stream URLs to test

1. type command in terminal: streamlink https://www.vrt.be/vrtnu/kanalen/een/ best
2. Opens in player (VLC) and plays fine.
3. After some minutes, there is a delay between image and sound.

### Environment details

Operating system and version: Debian testing
Streamlink and Python version: 0.8.1-1 and 2.7.13-2

**Comment by gravyboat** [comment]
Can you try a different player such as MPV to see if it happens there as well?

**Comment by lillet23** [comment]
It happens with MPV as well.

**Comment by beardypig** [comment]
@lillet23 can you run the streamlink command with the `-l debug` option, to enable debug logging so we can get a better idea of where the issue might be.

**Comment by lillet23** [comment]
streamlink -l debug https://www.vrt.be/vrtnu/kanalen/een/ best
[cli][info] Found matching plugin vrtbe for URL https://www.vrt.be/vrtnu/kanalen/een/
[hls.parse_variant_playlist][debug] Using external audio track for stream 234p (language=en, name=English)
[hls.parse_variant_playlist][debug] Using external audio track for stream 270p (language=en, name=English)
[hls.parse_variant_playlist][debug] Using external audio track for stream 360p (language=en, name=English)
[hls.parse_variant_playlist][debug] Using external audio track for stream 432p (language=en, name=English)
[hls.parse_variant_playlist][debug] Using external audio track for stream 540p (language=en, name=English)
[cli][info] Available streams: 234p (worst), 270p, 360p, 432p, 540p (best)
[cli][info] Opening stream: 540p (hls-multi)
[stream.][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496596 to queue
[stream.][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496597 to queue
[stream.hls][debug] Adding segment 188496598 to queue
[stream.hls][debug] Adding segment 188496595 to queue
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-5210-935 -i /tmp/ffmpeg-5210-929 -c:v copy -c:a copy -map 0 -map 1 -f mpegts pipe:1
[stream.hls][debug] Adding segment 188496596 to queue
[stream.hls][debug] Adding segment 188496597 to queue
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: /tmp/ffmpeg-5210-935
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: /tmp/ffmpeg-5210-929
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Download of segment 188496595 complete
[stream.hls][debug] Download of segment 188496596 complete
[stream.hls][debug] Download of segment 188496597 complete
[stream.hls][debug] Download of segment 188496596 complete
[cli][info] Starting player: /usr/bin/vlc
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 188496597 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496599 to queue
[stream.hls][debug] Download of segment 188496598 complete
[stream.hls][debug] Adding segment 188496598 to queue
[stream.hls][debug] Download of segment 188496598 complete
[stream.hls][debug] Download of segment 188496599 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496600 to queue
[stream.hls][debug] Adding segment 188496601 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496599 to queue
[stream.hls][debug] Adding segment 188496600 to queue
[stream.hls][debug] Download of segment 188496599 complete
[stream.hls][debug] Download of segment 188496600 complete
[stream.hls][debug] Download of segment 188496600 complete
[stream.hls][debug] Download of segment 188496601 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496601 to queue
[stream.hls][debug] Download of segment 188496601 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496602 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 188496602 complete
[stream.hls][debug] Adding segment 188496602 to queue
[stream.hls][debug] Download of segment 188496602 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496603 to queue
[stream.hls][debug] Download of segment 188496603 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496603 to queue
[stream.hls][debug] Download of segment 188496603 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496604 to queue
[stream.hls][debug] Adding segment 188496605 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 188496604 complete
[stream.hls][debug] Adding segment 188496604 to queue
[stream.hls][debug] Download of segment 188496604 complete
[stream.hls][debug] Download of segment 188496605 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496605 to queue
[stream.hls][debug] Download of segment 188496605 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188496606 to queue
[cli][info] Player closed
[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.mp4mux-ffmpeg][error] Pipe copy aborted: /tmp/ffmpeg-5210-929
[stream.mp4mux-ffmpeg][error] Pipe copy aborted: /tmp/ffmpeg-5210-935
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams
[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams

**Comment by back-to** [comment]
@lillet23 
did you change anything in your settings?
i only get `hls` streams not `hls-multi`
or was it some special event?

**Comment by lillet23** [comment]
I'm having this right now, and it seems it's only `hls` : 
(note that I'm using the new version of VLC (3.0.0-rc2)

```
streamlink -l debug https://www.vrt.be/vrtnu/kanalen/een/ best
[cli][info] Found matching plugin vrtbe for URL https://www.vrt.be/vrtnu/kanalen/een/
[cli][info] Available streams: 234p (worst), 270p, 360p, 432p, 540p (best)
[cli][info] Opening stream: 540p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 189375576 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 189375577 to queue
[stream.hls][debug] Adding segment 189375578 to queue
[cli][info] Starting player: /usr/bin/vlc
[stream.hls][debug] Download of segment 189375576 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 189375577 complete
[stream.hls][debug] Download of segment 189375578 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 189375579 to queue
[stream.hls][debug] Download of segment 189375579 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 189375580 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 189375580 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
Everything seems OK now. There is no delay anymore like before. I think we can close the bug.

**Comment by lillet23** [comment]
Oh, and many many many thanks for this fantastic program! I loooove `streamlink`! Keep up the good work!
