### ISSUE TITLE
younow.com is broken

### ISSUE THREAD

**Issue by stevek123** [streamlink/streamlink#127]
They have changed the API url to this one: 
`https://api.younow.com/php/api/broadcast/info/curId=0/user=`
in:
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/younow.py#L9

It still needs rtmpdump.exe, so it will give you the following error, related to #56
`[cli][error] Could not open stream: Unable to find rtmpdump.exe command`
#81 fixes it, and the plugin works fine.

**Comment by stevek123** [comment]
@beardypig Can you make a pull request for this too? I'm not a github expert, so I don't know how to do it, but the proposed modification fixes the plugin.

**Comment by beardypig** [comment]
@stevek123 will do :-)

**Comment by stevek123** [comment]
Thank you!
