### ISSUE TITLE
Volume setting with command-line

### ISSUE THREAD

**Issue by woctezuma** [streamlink/streamlink#1270]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

There is no command-line option to set the volume of the player.

### Expected / Actual behavior

Expected: There exists a command-line keyword to allow to start the player with the preferred volume. One could choose to start streaming with VLC with any percentage for the sound volume, from 0% for muted to 100% for maximal volume.

Actual: There exists no command-line option related to the volume.

### Environment details

Operating system and version: Windows 10 64 bits
Streamlink and Python version: 0.8.1 and 3.6.1 respectively.

**Comment by skulblakka** [comment]
I think this is out of scope for streamlink. Especially considering that this has to be working with all kind of different players. (Except if streamlink would somehow change the volume of the actual stream)

You can however pass command line options to the player of your choice. For VLC for example you can use 

```--volume <integer> sets the level of audio output (between 0 and 1024). Also only applies to local playback (like --noaudio)``` ([Source](https://wiki.videolan.org/Documentation%3aPlay_HowTo/Advanced_Use_of_VLC))

**Comment by woctezuma** [comment]
So, Streamlink is actually able (in theory) to set the volume with VLC. It is a nice feature.

I have tried the command-line which you suggested (with `--volume 0`, `--volume=0`, and `--volume="0"`), but could not get it to work. I suspect it has to do with spaces and quotes with Windows command-line. However, I could use the `--no-audio` option, so it is all good for me for now.

Thank you.

**Comment by gravyboat** [comment]
This is already supported via player options in case anyone stumbles in here later. As long as the player has command line option support this should work fine: `streamlink --player "vlc --volume 512" <url> <quality>`

I'm going to close this out, thanks @skulblakka.
