### ISSUE TITLE
camsoda plugin 

### ISSUE THREAD

**Issue by ls117** [streamlink/streamlink#1271]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Unable to validate JSON: Key 'app' not found in {'message': 'Access Denied', 'status': 0}
as of 5PM the plugin no longer works as it once did. i can only record in free chat. Seems like camsoda changed something. I saw someone else had a similar issue with twitch back in february.

edit
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ()

now i get this when im logged in, so it seems they made a change forcing you to actually be logged in, which isnt the problem at all, its just an interesting change. but im hoping someone more experienced with this stuff can help figure it out. i think thats the issue with streamlink now, it doesnt log in as an actual user so you cant view/record anything in a gold show or private.

...

### Reproduction steps / Explicit stream URLs to test

https://www.camsoda.com/prettyangeleyez

### Environment details

Operating system and version:  windows 8.1
Streamlink and Python version:  0.8.1

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by ls117** [comment]
it may just be the site, other models in private or ticket shows are also not loading at all, on pc or my phone, and thats if i turn off wifi too. So i know its not an ip ban. i may just be panicking for nothing.

**Comment by ls117** [comment]
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ()

now i get this when im logged in, so it seems they made a change forcing you to actually be logged in, which isnt the problem at all, its just an interesting change. but im hoping someone more experienced with this stuff can help figure it out.

**Comment by ls117** [comment]
url snooper still works, so its technically possible to build a working link that i can save on my own, with rtmpdump. using streamlink/xstreamloader is far more convenient however, and when you're paying for something that you can't quite save, its best to be able to record with one click, as opposed to typing the path.

**Comment by ls117** [comment]
*since you wanted the issue isolated to one thread i deleted this comment from the most recent thread, and im posting it here*

there's a fine line between 'porn site ripping tool' and a backup tool. the way i see it, if im paying for a stream i should be able to save it. camsoda makes you pay extra to do so, and thats on top of the ticket show price. I dont see the point in not supporting a discussion/request on a plugin that already exists, and is only now having issues because of recent site changes. While I certainly understand the team being small and only able to focus on small things at a time, personal feelings on how the program is used shouldn't be part of the discussion. Why can't we have the same consideration someone would have with a youtube issue? This all might be considered a legal grey area, but the same potential for abuse is possible not just with a porn site, but with any site. So what's the issue that you have with nsfw plugin requests? Assuming that we're all adults here of course, obviously no one wants to help some 12 year old stream porn. I considered donating or being a sponsor because I wanted the plugin fixed in a timely manner, but I'm not sure if I should if the team considers nsfw plugin's distasteful. The way I see it, we just want to be able to stream and record, and have our issues treated with the same consideration as any other plugin. As far as requests for new plugins, I can't say much to disagree there. That's the kind of thing that can handled whenever someone has the time and intent to do so, but existing plugins shouldn't be treated with disdain.

**Comment by gravyboat** [comment]
@ls117 Let's break this down a bit, first note that the response here is in regards to a comment by @bastimeyer here: https://github.com/streamlink/streamlink/issues/1279#issuecomment-337079653 which I will paste below since it is vital to the discussion:

```
The amount of NSFW plugin requests/issues/discussions here is increasing rapidly and it's
getting too much for my taste. Especially from newly created github accounts. This is
slowly becoming a porn site ripping tool, which we should not let happen. Maybe
we should move NSFW plugins into a different repo or so.
```

For posterity here are (I believe) the current NSFW plugins we support:

**Comment by ls117** [comment]
Well I'm glad you owned what you're doing here as being on a high horse, because thats exactly what it comes across to me. Presumably the site also takes a cut out of every models earnings, but as far I'm concerned, I shouldnt have to pay extra for the copy. Thats a personal opinion of yours that shouldnt have any place in how the program is used. What I'm doing is no different from using tivo or something similar, and generally speaking(grey area) streams are ok to save as long as they're not distrubuted freely. The interesting thing about this program(or the plugin rather) is very few people actually know it even exists, and limiting the access of it to people who actually need it would help alleviate your fears of any repurcussions. But its an open source project so that's not really a solution, just an option. I just don't like seeing personal feelings and opinions on the forefront of matter, simply because the plugin was already available. Since @back-to is the one who originally made the plugin, he seems to be the only one I need to talk to. Is it possible to donate to team members individually?

**Comment by Ro-Den** [comment]
@ls117
Try adding "useragents". It's to change 3 lines of code. But I don't think it will resolve the issue with "private" shows. There was a bug that allowed to record them and now it seems to have been fixed.

@gravyboat
As for NSFW sites, the only people who loose money are "models". Site owners get half of their profit from ads, I suppose. Thus, as long as there's a constant inflow of fresh "models" they won't do anything to prevent illegal distribution of their content. Except for minor changes mentioned above and placing frightening legal notices and DMCA logos. By the way, such content is not protected by copyright laws in most countries.

**Comment by MrBlackMac** [comment]
@Ro-Den 

How would I add useragents to Streamlink or the camsoda.py file?

**Comment by Ro-Den** [comment]
@MrBlackMac 
Just examine other plugins, e.g. adultswim.py or, better, learn how the whole thing works. It's not so difficult, but time consuming. For at least later you won't have to write TLDR posts every time they'll change something.

**Comment by MrBlackMac** [comment]
@Ro-Den 

Sounds good buddy, i'll attempt it later on today, lol got work in 5 hours :) thanks

**Comment by beardypig** [comment]
@Ro-Den @MrBlackMac If you just wanna change the User-Agent normally adding `--http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"` or similar will work.

**Comment by MrBlackMac** [comment]
@beardypig

Thank you for the extra info buddy, will try later on

**Comment by ls117** [comment]
@Ro-Den definitely assume this is our first time doing this. i didnt know how to add user agent until beardypig cleared it up. And I agree, camsoda isn't gonna do anything about this. The reason being there was already an article about someone on reddit who recorded an obscene amount of camsoda content(among others), and he wrote a py plugin that would auto record whenever specified models were on. That was a few months ago, on a reddit sub. i believe they're still going, because that whole sub was literally dedicated to backing up obscene amounts of porn. amounts I would've never thought possible. I think a few tb is enough, and im probably under a tb as it is. They were up to PETABYTES and still going. the plugin was released publicly, and that sub where I found that plugin had many people commenting, so presumably many people are using that plugin, or just recording in general. the only issue they had was getting an ip ban from recording too much at the same time.

**Comment by thomaz1342** [comment]
I'm definitely in over my head here trying to fix this myself... I'll wait patiently hoping someone has time to look at it.

**Comment by ls117** [comment]
@thomaz1342  i've spent $150 on private shows on more than one occasion, not being able to back that up is a problem. hopefully someone can fix this

**Comment by ls117** [comment]
it would be great if someone actually explained how to add user agents to whatever it is we're editing. just saying "examine" doesn't help. guys gotta remember not everyone knows what you're talking about

**Comment by johnthecracker** [comment]
http://stream-recorder.com/forum/camsoda-com-t20972.html?s=36be50be1aa6cbafa0e13f7f99b323dd&p=90186#post90186

**Comment by johnthecracker** [comment]
RTMP Proxy Server v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu; license: GPL

Streaming on rtmp://0.0.0.0:1935
WARNING: Trying different position for client digest!
Processing connect
       app : cam?token=eyJpdiI6IkJGazdDeHNcL3hTU2ZcL0VoUlpiNitrZz09IiwidmFsdWUiOiJQYVwvM3lsTFhzMXg5dnh4QjYyYllIQT09IiwibWFjIjoiMGM2NzA0MGFlYzc0YzAyZTdiOGI1YThjODI1NDc5NjQzYWU4ZjhmZmE4MGIwYTRmYzJlZWZiZjQ1YjEyY2JmYiJ9/
  flashVer : WIN 27,0,0,170
    swfUrl : https://cachew.camsoda.com/lib/video-js/video-js.swf
     tcUrl : rtmp://vide3.camsoda.com:1935/cam?token=eyJpdiI6IkJGazdDeHNcL3hTU2ZcL0VoUlpiNitrZz09IiwidmFsdWUiOiJQYVwvM3lsTFhzMXg5dnh4QjYyYllIQT09IiwibWFjIjoiMGM2NzA0MGFlYzc0YzAyZTdiOGI1YThjODI1NDc5NjQzYWU4ZjhmZmE4MGIwYTRmYzJlZWZiZjQ1YjEyY2JmYiJ9/
   pageUrl : https://www.camsoda.com/paulinefox
ERROR: Handshake failed
ERROR: Handshake failed
ERROR: Handshake failed
Closing connection... done!

Closing connection... done!

Closing connection... done!

      live : no
  Playpath : ?mp4:paulinefox-enc6
 Saving as : 2017-10-19_01-51-27_mp4_paulinefox-enc6.flv
INFO: Metadata:
INFO:   bandwidth               0.00
INFO:   profile                 baseline
INFO:   x_bw                    0.00
INFO:   keyFrameInterval        10.00
INFO:   x_mic                   Micr├│fono (5- HD Pro Webcam C920)
INFO:   codec                   H264Avc
INFO:   bandwith                0.00
INFO:   x_version               v54
INFO:   x_cfps                  22.50
INFO:   x_is_splitter           TRUE
INFO:   x_jsbw                  0.00
INFO:   level                   3.1
INFO:   width                   640.00
INFO:   fps                     0.00
INFO:   height                  480.00
INFO:   x_cam                   VISIT-X Video Splitter
WARNING: ignoring too small audio packet: size: 0

**Comment by ls117** [comment]
without clear and concise directions all of that looks like braille to me. @johnthecracker 
are you using streamlink or something else?

**Comment by johnthecracker** [comment]
RTMPDUMP-RP-2015-03-18-Fixes-Win.zip

http://www.nirsoft.net/utils/rtmp_dump_helper.html

http://kmeleonbrowser.org

**Comment by ls117** [comment]
literally nothing is happening so far. dumphelper and the rtmpsuck.exe are open but its not catching anything. it just says successfully launched rtmpserver

**Comment by johnthecracker** [comment]
http://stream-recorder.com/forum/showpost.php?p=87828&postcount=102

**Comment by ls117** [comment]
i was using chrome since its my main browser, so i guess i'll actually install kmeleon.

**Comment by johnthecracker** [comment]
[CODE]
C:\>rtmpdump -r "rtmp://vide3.camsoda.com:1935/cam" -a "cam?token=eyJpdiI6IkJGazdDeHNcL3hTU2ZcL0VoUlpiNitrZz09IiwidmFsdWUiOiJQYVwvM3lsTFhzMXg5dnh4QjYyYllIQT09IiwibWFjIjoiMGM2NzA0MGFlYzc0YzAyZTdiOGI1YThjODI1NDc5NjQzYWU4ZjhmZmE4MGIwYTRmYzJlZWZiZjQ1YjEyY2JmYiJ9/" -f "WIN 27,0,0,170" -W "https://cachew.camsoda.com/lib/video-js/video-js.swf" -p "https://www.camsoda.com/paulinefox" -y "?mp4:paulinefox-enc6" -o "paulinefox_2017-10-19_14-40-19.flv"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO:   bandwidth               0.00
INFO:   profile                 baseline
INFO:   x_bw                    0.00
INFO:   keyFrameInterval        10.00
INFO:   x_mic                   Micr├│fono (5- HD Pro Webcam C920)
INFO:   codec                   H264Avc
INFO:   bandwith                0.00
INFO:   x_version               v54
INFO:   x_cfps                  22.50
INFO:   x_is_splitter           TRUE
INFO:   x_jsbw                  0.00
INFO:   level                   3.1
INFO:   width                   640.00
INFO:   fps                     0.00
INFO:   height                  480.00
INFO:   x_cam                   VISIT-X Video Splitter
INFO: Metadata:
INFO:   bandwidth               0.00
INFO:   profile                 baseline
INFO:   x_bw                    0.00
INFO:   keyFrameInterval        10.00
INFO:   x_mic                   Micr├│fono (5- HD Pro Webcam C920)
INFO:   codec                   H264Avc
INFO:   bandwith                0.00
INFO:   x_version               v54
INFO:   x_cfps                  22.50
INFO:   x_is_splitter           TRUE
INFO:   x_jsbw                  0.00
INFO:   level                   3.1
INFO:   width                   640.00
INFO:   fps                     0.00
INFO:   height                  480.00
INFO:   x_cam                   VISIT-X Video Splitter
2165.500 kB / 26.56 sec
[/CODE]

**Comment by johnthecracker** [comment]
https://sourceforge.net/projects/kmeleon/files/k-meleon/75.1/K-Meleon75.1.7z/download

**Comment by ls117** [comment]
unless im missing something this doesnt save the audio. not exactly a solution. i really need to learn how to use rtmpdump. but thanks for introducing me to a different way

**Comment by thomaz1342** [comment]
[camsoda.txt](https://github.com/streamlink/streamlink/files/1399277/camsoda.txt)


After getting the ticket show feature to work, I am attempting to fix the private bug and after tweaking the useragent data I have now moved from a 403 error to a 404 (I guess technically that's progress) - With my limited knowledge of this field I take that to mean that the video URL for the private shows has changed, but I am not able to decipher how, this is what I get running a test on a private show:

[plugin.camsoda][error] Error parsing stream: Unable to open URL: https://vide5.camsoda.com/cam/mp4:marieelen_private_mjpeg/playlist.m3u8?token=eyJpdiI6Ik9TdDZ5UHVnMHp0ZzBRSTJYNWhpSEE9PSIsInZhbHVlIjoiMjVSaFBYRjUycVY1NDlmMzc2RTJJZz09IiwibWFjIjoiODk2ZjM0N2I0OTRmMjE5MDYyMTE2MTU4NjI4ZGU3NDQwZTVjZmM3NjVhMGE2YTgxNDdkM2UwMDc2ODViM2IyZSJ9 (404 Client Error: Not Found for url: https://vide5.camsoda.com/cam/mp4:marieelen_private_mjpeg/playlist.m3u8?token=eyJpdiI6Ik9TdDZ5UHVnMHp0ZzBRSTJYNWhpSEE9PSIsInZhbHVlIjoiMjVSaFBYRjUycVY1NDlmMzc2RTJJZz09IiwibWFjIjoiODk2ZjM0N2I0OTRmMjE5MDYyMTE2MTU4NjI4ZGU3NDQwZTVjZmM3NjVhMGE2YTgxNDdkM2UwMDc2ODViM2IyZSJ9)
error: No playable streams found on this URL: https://www.camsoda.com/MarieElen

Any help would be greatly appreciated.

@ls117 I've attached my working Camsoda.py file here for you to use for now, I'm hoping we can get the private bug fixed so that we can properly add the changes to the master branch. 

Thanks.

**Comment by ls117** [comment]
rtmp://private1.camsoda.com/cam?token

i dont think its dynamic either

**Comment by thomaz1342** [comment]
Nearest I can figure, the current code puts e.g. https://vide1 instead of https://private1 in the URL for private and then it breaks...

**Comment by ls117** [comment]
precisely. and its definitely not dynamic, the server is always private1. thanks of course to @thomaz1342 @johnthecracker @Ro-Den , getting more help from you guys who dont even work on the project.

**Comment by beardypig** [comment]
@ls117 it's an open-source project - everyone can, and is encouraged to work on it, we accept nearly every contribution :) It's a shame @back-to hasn't been around to help out, they would know the most about about how to fix it. If the version that @thomaz1342 has posted it working, we can look at getting that merged in.

**Comment by thomaz1342** [comment]
This is getting interesting... The current fix now works on some private shows, but not all.

**Comment by Ro-Den** [comment]
@thomaz1342 
Yes, at first it was 'Access Denied'. Now it's back to "normal" except they are sending the wrong servers.

@johnthecracker @ls117 
Do you know the "correct" `Playpath : ?mp4:username_private`, if any?
I tried adding "_mjpeg" and got the same reencoded 406p bullsh*t...

**Comment by thomaz1342** [comment]
Hi @Ro-Den - I had ticket shows working yesterday, but now I'm getting the following for ticket shows:

[cli][info] Found matching plugin camsoda for URL https://www.camsoda.com/foreignmilan
error: Unable to validate JSON: Key 'stream_name' not found in {'status': 1, 'token': '', 'app': 'cam', 'edge_servers': [], 'mjpeg_server': '', 'private_servers': []}

Dunno if that's any help, but just in case.

**Comment by ls117** [comment]
@thomaz1342 im doubt thats an actual problem with the program. she has no one watching, its most likely on her end.

**Comment by thomaz1342** [comment]
@ls117 Not sure that's pertinent, there's still an active ticket stream that we should be able to grab. I get the same for any other ticket stream:

[cli][info] Found matching plugin camsoda for URL https://www.camsoda.com/sophieann
error: Unable to validate JSON: Key 'stream_name' not found in {'status': 1, 'token': '', 'app': 'cam', 'edge_servers': [], 'mjpeg_server': '', 'private_servers': []}

**Comment by ls117** [comment]
yeah, only thing that works is free chat now. it seems like they removed the 'feature' forcing you to log in for certain models. i swear i think they allowed them to close off their rooms to guests. but that doesnt really make sense for the long run, ultimately guests become users. they definitely made it a requirement to be logged in for a few days though. camsoda seems to periodically change things every 6 months or so, that was never really an issue for me until late august and last week.

**Comment by Ro-Den** [comment]
@ls117 @thomaz1342
Yes, the privates are gone again. Maybe, they are monitoring this thread now. Open-source projects are open for all.

Looks like they are changing their business model from selling live shows to selling videos. And that's the reason for the recent changes. If so, this time it won't be easy...

**Comment by ls117** [comment]
yeah i thought of that too but i didnt wanna believe it.

**Comment by ls117** [comment]
@back-to we need your expertise lol

**Comment by johnthecracker** [comment]
C:\>streamlink rtmp://vide5.camsoda.com:1935/cam?token=eyJpdiI6Ik1UbllDNHNoWjVTVFhVYXdhdTV1d1E9PSIsInZhbHVlIjoiZXNJZjU4NTZ4Vzg0anpKeWZxcjk4QT09IiwibWFjIjoiZjk5NTRmOThmOTljMGFkMWY2ZWZkM2FlNTViMWFlYzc3ZWU4NDIwYjRjNDJmMWNmYTJmNDQwNjAxOWU1NmJjYyJ9//?mp4:anierouse-enc1 best
[cli][info] Found matching plugin rtmp for URL rtmp://vide5.camsoda.com:1935/cam?token=eyJpdiI6Ik1UbllDNHNoWjVTVFhVYXdhdTV1d1E9PSIsInZhbHVlIjoiZXNJZjU4NTZ4Vzg0anpKeWZxcjk4QT09IiwibWFjIjoiZjk5NTRmOThmOTljMGFkMWY2ZWZkM2FlNTViMWFlYzc3ZWU4NDIwYjRjNDJmMWNmYTJmNDQwNjAxOWU1NmJjYyJ9//?mp4:anierouse-enc1
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by ls117** [comment]
@johnthecracker streamlink still works on regular links, the issue is ticket shows and privates.

**Comment by thomaz1342** [comment]
Now getting the following on ticket show: 

[plugin.camsoda][error] Error parsing stream: Unable to open URL: https:///cam/mp4:_mjpeg/playlist.m3u8?token=eyJpdiI6Impwb2dweldvRnhjR2dYK0I0R1dreHc9PSIsInZhbHVlIjoid1hEcHJDSmxEXC82ays3N0kxa25DQ3c9PSIsIm1hYyI6ImMwYTFiY2RkYjhiNGQ1M2QwNjk3MmEyNTU4ZDc0YWVjYTZjM2VkYmQ2NDQ2MjkyNTJkMmQwYTM4NWVjNjAyZTYifQ== (Invalid URL 'https:///cam/mp4:_mjpeg/playlist.m3u8?token=eyJpdiI6Impwb2dweldvRnhjR2dYK0I0R1dreHc9PSIsInZhbHVlIjoid1hEcHJDSmxEXC82ays3N0kxa25DQ3c9PSIsIm1hYyI6ImMwYTFiY2RkYjhiNGQ1M2QwNjk3MmEyNTU4ZDc0YWVjYTZjM2VkYmQ2NDQ2MjkyNTJkMmQwYTM4NWVjNjAyZTYifQ==': No host supplied)

I'm no expert, but isn't that one too many / here: https:/// ?

**Comment by Ro-Den** [comment]
@ls117 @thomaz1342 
There's absolutely no point in trying to fix it right now. They are constantly changing everything every day and may do it as long as they wish.

IMHO, this lousy website isn't worth the time: worst web interface, glitchy javascript, worst video quality, least number of "models", fake privates and so on. Just stumbled upon the high quality HLS streams, but sound is none. Hope they are reading this and would fix it as soon as possible.

**Comment by thomaz1342** [comment]
Hi @Ro-Den  Yeah, it seems you're right, everything seems to be changing right now on their end. I'm certainly not a fan of their site or the content, I'm using this exercise more as way of learning how streaming works in general and how streamlink handles it all. I am not familiar with HLS streams, is that not something the plugin would select today as the "best" option?

Thanks for your time.

**Comment by ls117** [comment]
im actually a fan of several women on there, so this matters to me.

**Comment by thomaz1342** [comment]
Well, it seems things have stabilized a bit over at CS, I am now consistently getting this: 

**For privates:**

hls_url = self._get_hls_url(data_user, data_video)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/streamlink-0.8.1-py3.6.egg/streamlink/plugins/camsoda.py", line 76, in _get_hls_url
    server = data_video["private_servers"][0]
IndexError: list index out of range

**For ticket shows:**

[plugin.camsoda][error] Error parsing stream: Unable to open URL: https:///cam/mp4:_mjpeg/playlist.m3u8?token=eyJpdiI6Im1xNUJlWHQrM01iMkpqU2I5SGJjNFE9PSIsInZhbHVlIjoiVjl3V2w2eWpuVWF6VEJxRmZ4dzZLZz09IiwibWFjIjoiOWYwMjBhZmVjNTlhOGU0ZWQ3ODFkYWNmMDI0N2E1NjI5YTU3NGU1NjQ4MjRhNTIwYzNjZmJjZjk3OGU5Y2MxNyJ9 (Invalid URL 'https:///cam/mp4:_mjpeg/playlist.m3u8?token=eyJpdiI6Im1xNUJlWHQrM01iMkpqU2I5SGJjNFE9PSIsInZhbHVlIjoiVjl3V2w2eWpuVWF6VEJxRmZ4dzZLZz09IiwibWFjIjoiOWYwMjBhZmVjNTlhOGU0ZWQ3ODFkYWNmMDI0N2E1NjI5YTU3NGU1NjQ4MjRhNTIwYzNjZmJjZjk3OGU5Y2MxNyJ9': No host supplied)
error: No playable streams found on this URL: https://www.camsoda.com/sophieann

I am equally stumped on both...

**Comment by dirk362** [comment]
If you examine the output of failues, you'll note
 
 - when private, the private_servers array is empty in the source of `https://www.camsoda.com/api/v1/video/vtoken/{0}?username=guest_{1}`
 - meaning no server is defined for connection. Hardcoding this to `private1.camsoda.com` will make no difference. Even assuming that is the correct server address 
 - for streamname, this also is blank. The json attribute is still known as `stream_name` but that isn't parsed correctly when in non-public session
 
It's worth noting that token isn't required for public shows. Ultimately token is just a base64 encoded set of additional attributes.
 
It's highly likely that further connection attributes and/or cookies are now required. Only with network trace or other information can the plugin be fixed, as we're missing information for a valid connection.

All that said, given private (including spy and ticket shows) are subscription elements to the site as in you need to pay to watch these, I see no reason why streamlink should 'fix' this.

**Comment by ls117** [comment]
Jesus. No one cares what your personal opinion is

**Comment by gravyboat** [comment]
@ls117 Please keep the discussion civil and respectful to everyone. We are all entitled to our own opinions, but there's no reason to be rude about it.

**Comment by dirk362** [comment]
HLS_URL_VIDEO - The stream name should use **_aac** rather than _mjpeg as the suffix.
The server name should use `origin_server` as the source of that attribute, and not try to read the `private_servers` array as it's empty. This attribute is correct for all show types, and can be obtained via the API_URL_USER URL.
Those two should make this work again.

As I said, it's a fairly simple fix in terms of what needs to be changed from the source attributes obtained via the two URLs that are defined in the plugin. They need to be adjusted to extract from the correct areas of the relevant json response.

By the way, I have a right to an opinion. It is after all an opinion and not a statement of fact. Whether you agree or not makes no difference to my opinion. I'm only providing this response because I really don't care about these sorts of sites, and am interested in understanding how things work. Hence why I bothered to look into this issue in the first place.

**Comment by Polizo** [comment]
Can you please upload the fixed file?
I was trying to changue it, but i cant make it work :(
Thanks

**Comment by youwouldnotcare** [comment]
@ls117 You sure do have a lot of opinions to be going around shouting down others' opinions.

**Comment by ls117** [comment]
How about keeping me out of the conversation, i already got help with it and since people wanna offer what I feel are useless opinions, I didn't even bother coming back to this thread. Close the issue if you want it's not a problem for me anymore. I ALSO have a right to an opinion, the point I was making was that it's nonsense to complain or refuse to fix something that was already part of the package. I already unsubscribed from this topic and wouldn't have returned to say anything but again, someone decided to tag me in yet another useless comment.

**Comment by thomaz1342** [comment]
Anyone able to get the instructions to work?

thx

**Comment by Polizo** [comment]
Yes please, update the fixed file on the code or upload here please. i cant make it work :(

**Comment by ls117** [comment]
definitely not the fix i was looking for.

**Comment by hakeemshafiq17-boop** [comment]
Solve
