### ISSUE TITLE
Python/compile errors when installing on Fedora 26 via dnf and pip

### ISSUE THREAD

**Issue by Larry456** [streamlink/streamlink#1272]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I tried installing streamlink via both 'sudo pip install streamlink' and 'sudo dnf install streamlink'.

https://pastebin.com/rvCHHfW9 Here is the log and errors I get when installing via pip.

When using dnf, it appears to install, but when trying to run it, it shows the following errors https://pastebin.com/UjTZVsJk

Edit: Installed 'redhat-rpm-config' manually because a forum post said it might relate to the pip error, however now there is another GCC error during pip installation 

    /bin/ld: cannot find -lpython2.7
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-MUc2MJ/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-OIePYM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-MUc2MJ/pycryptodome/

**Comment by melmorabity** [comment]
Hello,

I'm the maintainer of the streamlink package for Fedora. An update will be available in a few days which fixes the missing websocket-client error you got (in fact the current package is missing a dependency on the websocket-client package).
You can fix it now by installing websocket-client using the command
`   dnf install python3-websocket-client`

**Comment by avirunes** [comment]
I'm having the same issues in openSUSE Leap 42.3
https://pastebin.com/HM3UQHsj

**Comment by back-to** [comment]
```
Changelog 
* Tue Nov 14 2017 - 0.9.0-1
- Update to 0.9.0

* Tue Oct 10 2017 - 0.8.1-3
- Fix dependecy on python-websocket-client package
```

https://koji.fedoraproject.org/koji/packageinfo?packageID=23544
https://koji.fedoraproject.org/koji/buildinfo?buildID=998905

the install with `dnf` should work again

Closing.
