### ISSUE TITLE
Camsoda Plugin issue

### ISSUE THREAD

**Issue by thomaz1342** [streamlink/streamlink#1278]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Apologies if this is a duplicate of Bug # 1271, but the error message i am getting is slightly different when trying to output a CS stream to a file. 
...

### Expected / Actual behavior

Being able to output a stream to a file.

...

### Reproduction steps / Explicit stream URLs to test

I use the following command to grab a stream, e.g.:

streamlink -o "$(date +"file_%Y%m%d%H%M%S.mp4")" https://www.camsoda.com/KathieRose best
This would work like a charm up until a few days ago, but now I get the following message:

**"error: Unable to validate JSON: Key 'stream_name' not found in {u'status': 0, u'message': u'Access Denied'}"**

### Environment details

Mac 10.13.1. beta 
Streamlink 0.8.1
Python 3.6.3
...

Thanks a lot for taking a look, I'll be donating to this great project. 
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Let's keep all current issues of a certain plugin in one single thread...
Closing in favor of #1271
