### ISSUE TITLE
Goodgame moved to the new version of the site

### ISSUE THREAD

**Issue by flijloku** [streamlink/streamlink#128]
Goodgame moved to the new version of the site (https://github.com/chrippa/livestreamer/issues/1513 ; https://github.com/chrippa/livestreamer/issues/1518 ; https://github.com/chrippa/livestreamer/pull/1527). Fix the plugin please.

**Comment by storage627** [comment]
Now the plugin works only with old.goodgame.ru
Sooner or later they will close the old version of the site.
It would be nice to make a plugin for the current version of the site before it happens.

**Comment by beardypig** [comment]
@storage627 are you using the latest version of `streamlink` (0.1.0)? I just tried 
```sh
streamlink "https://goodgame.ru/channel/gegeboyz/#autoplay" best
```
and it worked fine.

**Comment by flijloku** [comment]
@storage627 Try it: https://github.com/streamlink/streamlink/issues/158
