### ISSUE TITLE
Add seeking support to BBC iPlayer plugin

### ISSUE THREAD

**Issue by kachelaqa** [streamlink/streamlink#1280]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

BBC iPlayer urls allow seeking to a postion in a video by adding a query string like this:

`?t10m30s`

which specifies a time 10 minutes and 30 seconds in.

The old get_iplayer-2.97 utility that I'm currently using to stream BBC content supports this feature. I would like to switch to using streamlink, but its bbciplayer plugin currently ignores the query string and I don't see any options that provide similar functionality.

Is there any way that this feature (or something equivalent) could be added?

### Environment details

streamlink 0.8.1

**Comment by gravyboat** [comment]
I assume the query string goes on the end of the URL? Did you wrap the full url in quotes? So `"www.domain.com/video?t10m30s"`.

**Comment by kachelaqa** [comment]
Yes, just like all query strings, it goes at the end of a standard BBC iPlayer url, like this:

`https://www.bbc.co.uk/iplayer/episode/b097rtmr/mastermind-2017-episode-10?t=10m30s`

And as I said, this **does** work with get_iplayer (I have been using it for many years), but not currently with the streamlink bbciplayer plugin. I assume this must be because it maps the video IDs to a `open.live.bbc.co.uk/mediaselector` url, so the query in the original url is lost. I have no idea whether mediaselector urls support the necessary query parameters, as I have been unable to find any information regarding their format.

**Comment by gravyboat** [comment]
The reason I asked is because there are a few special characters that get treated oddly, and `?` is one of them so anything containing them has to be wrapped in quotes.

**Comment by kachelaqa** [comment]
Okay - for the record, it makes no difference whether the url is quoted (single or double).

**Comment by beardypig** [comment]
@kachelaqa you are correct - any query string arguments are ignored. I will take a look at updating my [hls-skip](https://github.com/beardypig/streamlink/tree/hls-skip) branch - it only works for HLS sources though.

**Comment by back-to** [comment]
@kachelaqa 
it's not automatically but with the latest github version of streamlink

you could use `--hls-start-offset HH:MM:SS`

https://streamlink.github.io/cli.html#cmdoption-hls-start-offset

but **only** for **HLS** streams not HDS

**Comment by kachelaqa** [comment]
Thanks very much for implementing this.

I have now switched to using streamlink for all my daily bbc-iplayer viewing. So far, everything seems to be working as expected. If I encounter any problems, I will open a new issue.
