### ISSUE TITLE
BBC iPlayer cannot authenticate

### ISSUE THREAD

**Issue by jiangjiangflies** [streamlink/streamlink#1283]
Hi, I have specified my bbc account in config file but it still doesn't work.  Are there any restrictions for bbc account? The full outputs are as follows:
```
root@Debian7:~# streamlink https://www.bbc.co.uk/iplayer/live/bbctwo
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbctwo
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[cli][info] Available streams: 352k_alt2 (worst), 352k_alt, 352k, 544k_alt2, 544k_alt, 544k, 942k_alt2, 942k_alt, 942k, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p, 1700k_alt2, 1700k_alt, 1700k, 720p_alt2, 720p_alt, 720p, 2908k_alt2, 2908k_alt, 2908k, 5166k_alt2, 5166k_alt, 5166k (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:43551/
[cli][info] Got HTTP request from PotPlayer
[cli][info] Opening stream: 5166k (hds)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from WINAMP
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, could not find the authentication nonce
[plugin.bbciplayer][error] Could not authenticate, check your username and password
[cli][info] Stream not available, will re-fetch streams in 10 sec
```

**Comment by anniman** [comment]
i get this same fault if i request with external player. if i use vlc as external player it works ok but anything is authentication error
PS C:\WINDOWS\System32\WindowsPowerShell\v1.0> streamlink --player-external-http-port 9998 https://www.bbc.co.uk/iplayer
/live/bbcone best
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[cli][info] Available streams: 352k_alt2 (worst), 352k_alt, 352k, 544k_alt2, 544k_alt, 544k, 288p_alt2, 288p_alt, 288p, 942k_alt2, 942k_alt, 942k, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p, 1700k_alt2, 1700k_alt, 1700k (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:9998/
[cli][info]  http://192.168.0.3:9998/
[cli][info] Got HTTP request from Xtream-Codes IPTV Panel Pro
[cli][info] Opening stream: 1700k (hds)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from Xtream-Codes IPTV Panel Pro
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, could not find the authentication nonce
[plugin.bbciplayer][error] Could not authenticate, check your username and password
[cli][info] Stream not available, will re-fetch streams in 10 sec
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, could not find the authentication nonce
[plugin.bbciplayer][error] Could not authenticate, check your username and password
[cli][info] Stream not available, will re-fetch streams in 10 sec

**Comment by beardypig** [comment]
Are you waiting a long time before starting to play the stream, or does it happen right away?
