### ISSUE TITLE
panda.tv plugin doesn't work

### ISSUE THREAD

**Issue by fozzysec** [streamlink/streamlink#1285]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

On 24 Oct the panda.tv plugin doesn't work. I checked the plugin code, there seems no change on the API. The only thing that have changed is that panda.tv now use https on SD, HD and MD quality streams by default, but it seems not the cause of the problem. After tracing the network of the flash player and comparing it to the plugin, what makes a 403 is actually the CDN server. I tried to request the stream with referer and some other missing headers it still return a 403 error. Anyone has idea on how to solve this problem?

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. http://www.panda.tv/s7

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by fozzysec** [comment]
@steven7851 Do you have any idea on it?

**Comment by Erk-** [comment]
`streamlink --player=mpv http://www.panda.tv/s7 best
[cli][info] Found matching plugin pandatv for URL http://www.panda.tv/s7
[cli][info] Available streams: hq (worst), ehq (best)
[cli][info] Opening stream: ehq (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('http://pl3.live.panda.tv/live_panda/dd9f182bcec99d04099113e618cfc5b3.flv?sign=d6f74aca01d6c14a0e85f9c10c26247a&ts=59ef5700&rid=-27239751')> (Could not open stream: Unable to open URL: http://pl3.live.panda.tv/live_panda/dd9f182bcec99d04099113e618cfc5b3.flv?sign=d6f74aca01d6c14a0e85f9c10c26247a&ts=59ef5700&rid=-27239751 (403 Client Error: Forbidden for url: http://157.185.151.44/pl3.live.panda.tv/live_panda/dd9f182bcec99d04099113e618cfc5b3.flv?sign=d6f74aca01d6c14a0e85f9c10c26247a&ts=59ef5700&rid=-27239751&wshc_tag=0&wsts_tag=59ef5700&wsid_tag=82e1bc21&wsiphost=ipdbm))
error: Could not open stream <HTTPStream('http://pl3.live.panda.tv/live_panda/dd9f182bcec99d04099113e618cfc5b3.flv?sign=d6f74aca01d6c14a0e85f9c10c26247a&ts=59ef5700&rid=-27239751')>, tried 1 times, exiting`

**Comment by steven7851** [comment]
I think APIv3 need more param, maybe change to APIv2 will be fine.

**Comment by KamiOrz** [comment]
modify streamlink/plugins/pandatv.py   79 line  change ROOM_API to ROOM_API_V2

**Comment by jkfran** [comment]
I was going to look this problem but I think that it's already solved:
https://github.com/streamlink/streamlink/commit/cc72be10230f8ff1153c4ec1f1a1317a66144c9f

**Comment by fozzysec** [comment]
Thanks for fixing. @steven7851
