### ISSUE TITLE
setting external port, linux

### ISSUE THREAD

**Issue by anniman** [streamlink/streamlink#1288]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ x] I have read the contribution guidelines.

### Description
i;m trying to specify a specific port for the external player with the command 
--player-external-http-port 2223 but get the following error

streamlink --http-proxy "http://185.42.223.194:3128/" --player-continuous-http --player-external-http-port 2223 www.itv.com/hub/itv2 best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin itvplayer for URL www.itv.com/hub/itv2
[cli][info] Available streams: 1200k (worst, best)
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
 
i can make it work correctly with windows but not in linux with the same command.
...

### Expected / Actual behavior

[cli][info] Found matching plugin tvplayer for URL https://www.itv.com/hub/itv2
[cli][info] Available streams: 214k (worst), 564k, 1064k, 1864k, 2564k (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:2223/
[cli][info]  http://192.168.0.3:2223/
...

### Environment details

Operating system and version: ...ubuntu 14.04
Streamlink and Python version: ...8.0.1 python 3.2

**Comment by bastimeyer** [comment]
You have to set the `--player-external-http` parameter in addition to `--player-external-http-port`. Just using the `-port` parameter isn't enough.
https://streamlink.github.io/cli.html#cmdoption-player-external-http

**Comment by anniman** [comment]
so it is. thanks a lot. i have now changed it to 

streamlink  --http-proxy "http://185.42.223.194:3128/" --player-continuous-http --player-external-http-port 2223 --player-external-http  www.itv.com/hub/itv2 best

and the expected output is correct. i had that in the config file in windows but no config file in linux

**Comment by gravyboat** [comment]
@anniman I have modified both your comments to remove the IP address you originally provided to prevent potential abuse.

**Comment by anniman** [comment]
its ok it was made up anyway
