### ISSUE TITLE
Why are the files so huge? 

### ISSUE THREAD

**Issue by xDinomode** [streamlink/streamlink#1289]
9GB for a 3 hour Twitch VOD??? 

I'm running the command:
`streamlink <link here> best -o "title.mp4" `

**Comment by gravyboat** [comment]
That's pretty typical and will depend on the resolution and framerate the person is streaming at. I don't really see how this is a question for us, nor is this the place to talk about the details involved in how much space video takes based on a variety of factors so I'm going to close it. If you want smaller videos compress them after you download, or download at a lower quality setting.

**Comment by Erk-** [comment]
You can usually make it much smaller by reencoding the file.
