### ISSUE TITLE
Ustream stream ends repeatedly

### ISSUE THREAD

**Issue by aaronspence** [streamlink/streamlink#129]
I have the following code on a Raspberry Pi and for a while it's worked flawlessly but the past few weeks it's repeatedly rebooting the player.

`while true
do
    streamlink ustream.tv/channel/iss-hdev-payload mobile_720p --player omxplayer --player-fifo --player-no-close
done`

`[cli][info] Creating pipe streamlinkpipe-1730
[cli][info] Starting player: omxplayer
[cli][info] Player closed
[cli][info] Stream ended
`

Will do this maybe every minute or so.

**Comment by gravyboat** [comment]
Can you duplicate this issue with VLC or is it unique to omxplayer?

**Comment by aaronspence** [comment]
Hi there,

Never had any success getting VLC working on the Pi.

`[cli][info] Found matching plugin ustreamtv for URL http://ustream.tv/channel/iss-hdev-payload
[cli][info] Available streams: mobile_240p (worst), mobile_360p, mobile_480p, mobile_720p (best)
[cli][info] Opening stream: mobile_720p (hls)
[cli][info] Creating pipe streamlinkpipe-11961
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
`

Just instantly ends with no video

**Comment by aaronspence** [comment]
I may have had a clue.. I have just had this error before omxplayer stopped

`[stream.hls][error] Failed to open segment 24481: Unable to open URL: http://uhs-akamai.ustream.tv/sjc/sjc-uhs-omega04/live/17074538/1478413291476/plain/improved/1/chunk_24481_59b9cb06c3.ts (HTTPConnectionPool(host='uhs-akamai.ustream.tv', port=80): Read timed out. (read timeout=10.0))`

**Comment by gravyboat** [comment]
Closing this since #754 was merged.
