### ISSUE TITLE
showroom-live Unable to open URL

### ISSUE THREAD

**Issue by nakomaru** [streamlink/streamlink#1290]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Trying to use streamlink to open a showroom-live stream seems to fail due to 404, possibly due to site structure changes.

### Expected / Actual behavior

Running `streamlink <room url>`, in the case that the given room is live, should probably open a stream or ask for a quality setting, but reports 404 instead.

### Reproduction steps / Explicit stream URLs to test

1. Find a live room from here: https://www.showroom-live.com/onlive
2. Enter `streamlink <room url>`

### Environment details

Operating system and version: Win7x64
Streamlink and Python version: Streamlink 0.8.1, Prepackaged Python

### Comments, logs, screenshots, etc.

`streamlink https://www.showroom-live.com/misaki0719`

`[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/misaki0719`
`error: Unable to open URL: https://www.showroom-live.com/room/get_live_data?room_id=144710`
`(404 Client Error: Not Found for url: https://www.showroom-live.com/room/get_live_data?room_id=144710)`

**Comment by Antares31415** [comment]
This is due to an API change. The API location for room information is https://www.showroom-live.com/api/live/live_info?room_id={room_id} now. I don't know Python and rtmp well enough to fix this problem since the variable names have also changed.
Example of new API output:
{"age_verification_status":0,"video_type":0,"enquete_gift_num":0,"is_enquete":false,"bcsvr_port":8080,"live_type":0,"is_free_gift_only":false,"bcsvr_host":"online.showroom-live.com","live_id":0,"is_enquete_result":false,"live_status":1,"room_id":115516,"bcsvr_key":"","background_image_url":null}

**Comment by nakomaru** [comment]
@wlerin Sorry to bother you. It seems you are the original author of this plugin so I wanted to let you know.

**Comment by wlerin** [comment]
Ah, I forgot to update this. The `live_info` endpoint does not contain the necessary information, and I haven't found any other API endpoint that does. However, the html of the room page (not the profile) does. I can submit a patch to get it from there instead, but really we need to find the new endpoint.

**Comment by wlerin** [comment]
I have updated the showroom plugin on my fork here:
https://github.com/wlerin/streamlink/blob/showroom/src/streamlink/plugins/showroom.py

Basically all functionality besides getting a single streamable url is gone.

**Comment by back-to** [comment]
there is an api for hls and rtmp urls @wlerin 
`https://www.showroom-live.com/api/live/streaming_url?room_id={room_id}`

https://gist.github.com/back-to/a051c3e7bb450d323e4d1f07c1b1a6d6

here is a diff file, just the `is_live` is not fixed there

```
error: Unable to validate JSON: Key 'streaming_url_list' not found in {}
```
for offline streams

and some other cleanups could be done.

feel free to use it, if you want.

**Comment by wlerin** [comment]
The old api had an `is_live` endpoint (`...showroom-live.com/room/is_live?room_id={room_id}`) that is still active and could be queried, but it doesn't seem necessary.
