### ISSUE TITLE
Dailymotion : Nominative address support broken after recent changes

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#1292]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

After checking up with latest Dailymotion changes, I noticed nominative address support is missing. 

### Expected / Actual behavior

This channel is currently active : 

`http://www.dailymotion.com/televizijak23`

### Reproduction steps / Explicit stream URLs to test

1. Not working
---------------
```
streamlink "http://www.dailymotion.com/televizijak23" best
[cli][info] Found matching plugin dailymotion for URL http://www.dailymotion.com/televizijak23
Traceback (most recent call last):
  File "C:\Users\Ddr\Downloads\Temp\streamlink\\streamlink-script.py", line 12,
in <module>
    main()
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink_cli\main.py",
 line 1045, in main
    handle_url()
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink_cli\main.py",
 line 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink_cli\main.py",
 line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink\plugin\plugin
.py", line 385, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink\plugin\plugin
.py", line 288, in streams
    ostreams = self._get_streams()
  File "C:\Users\Ddr\Downloads\Temp\streamlink\packages\streamlink\plugins\daily
motion.py", line 236, in _get_streams
    match = _url_re.match(self.url)
TypeError: expected string or bytes-like object
```

2. Working
-----------
```
streamlink "http://www.dailymotion.com/video/x1jztwz_k23tv-serbia-subotica_tv" best
[cli][info] Found matching plugin dailymotion for URL http://www.dailymotion.com
/video/x1jztwz_k23tv-serbia-subotica_tv
[cli][info] Available streams: 176p (worst), 288p, 477p (best)
[cli][info] Opening stream: 477p (hls)
[cli][info] Starting player: C:\Users\Ddr\Downloads\Temp\VLCPortable\App\vlc\vlc

[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Environment details

W7 Pro
Streamlink portable nightlies / Python version: 3.6

...

### Comments, logs, screenshots, etc.

This feature has been implemented by @beardypig  a couple of months ago but it's broken after Dailymotion recent changes.

**Comment by back-to** [comment]
they removed
```
username_re = re.compile(r'''data-username\s*=\s*"(.*?)"''')
```
from there website

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/dailymotion.py#L44

---

if `match.group("channel_name")` gets used as the username it should work again

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/dailymotion.py#L234

but it would requiere to add some error messages to make it work well with `streamlink`

**Comment by karlo2105** [comment]
@back-to 
Could you please pull the request for Dailymotion changes?

**Comment by back-to** [comment]
i discovered that it will play the **Featured** video and **not the livestream**,
it would only work if the Featured video is the livestream

i don't know if there is an api for the livestream id,
direct from the website is not possible to much javascript 🗡 

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/dailymotion.py#L224

---

http://www.dailymotion.com/france24
- would work

http://www.dailymotion.com/televizijak23
- would play an old video

**Comment by karlo2105** [comment]
@back-to 
Just checked out it's fine. Much appreciated for your work. ;)
