### ISSUE TITLE
how to use the vpn function

### ISSUE THREAD

**Issue by anniman** [streamlink/streamlink#1294]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
i've tried all the ways i can find in here to bypass the geo restrictions trying to use a vpn and cannot get rid of the 403 error. i have tried in the command line and config file  `--https-proxy=https://username:password@ams.socks.ipvanish.com`
as ipvanish is what i use

### Expected / Actual behavior
to not get error 403 Client Error: Forbidden for url: http://mercury.itv.com/PlaylistService.svc?wsdl

### Reproduction steps / Explicit stream URLs to test

1. https://www.itv.com/hub/itv 
2. https://www.bbc.co.uk/iplayer/live/bbcone

### Environment details

Operating system and version: ubuntu 14,04
Streamlink and Python version: 0.8.1 

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Try adding `--http-proxy=https://username:password@ams.socks.ipvanish.com`, you need to use both the `http` and `https` proxy options when the requests use both `http` and `https` URLs (as is the case with your example).

**Comment by bastimeyer** [comment]
> ams.socks.ipvanish.com

If it's a socks proxy server, then a different syntax has to be used, as specified in the documentation...

**Comment by anniman** [comment]
thanks, i tried what was suggested and got a proxy error. i then tried with removing information from the config and using in the line directly this
streamlink --https-proxy=https://username:password@ams.socks.ipvanish
.com --player-external-http-port 2220 https://www.itv.com/hub/itv best

and this is the response

[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[plugin.itvplayer][error] Failed to retrieve playlist data (invalid geo region)
error: No playable streams found on this URL: https://www.itv.com/hub/itv

i cant be that far away but cant see the syntax error in the line.

**Comment by bastimeyer** [comment]
> cant see the syntax error in the line

https://streamlink.github.io/cli.html#proxy-support

**Comment by anniman** [comment]
ok so i've looked at that and changed it slighty to 
streamlink --http-proxy "http://user:password@ams.socks.ipvanish.com" --https-proxy "https://user:password@ams.socks.ipvanish.com" --player-external-http-port 2220  https://www.itv.com/hub/itv best 
and still get the 403 forbidden error. can anyone help shed some light on this please

**Comment by beardypig** [comment]
@anniman this might be a silly question, but is `ams.socks.ipvanish.com` the proxy for the UK?

**Comment by anniman** [comment]
that is a good question that i have been wondering myself. there is no mention of what it is from ipvanish and they only seem to have one proxy. i have emailed them.
Where would be a place to get a working uk proxy if anyone knows.

**Comment by ryanjgillies** [comment]
I'm also now receiving this error via my own provider NordVPN - I haven't changed any of my config settings, so something has seemingly happened on the BBC end of things - perhaps they've recently been on a bit of a spree black listing suspected VPN server addresses?

Here's my terminal output:

```
streamlink https://www.bbc.co.uk/iplayer/live/bbcone best --config /home/manager/scripts/streamlink.cfg -v -l debug
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][debug] Loading stream for live channel: bbcone
[plugin.bbciplayer][debug] Looking for tvip on https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][debug] Found TVIP: bbc_one_london
[plugin.bbciplayer][debug] Info API request: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/
error: Unable to open URL: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/ (403 Client Error: Forbidden for url: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/)
```

**Comment by ryanjgillies** [comment]
As a further follow-up note, I just spoke with my VPN provider's support team who confirm to me that their servers were blacklisted by the BBC today - they aim to resolve the issue within 3-4 hours.

@anniman you might want to confer with your VPN provider as well.

**Comment by bastimeyer** [comment]
So I guess this can be closed then, as it's an external issue.
Feel free to reopen...

Thanks for clarifying, @ryanbraganza
