### ISSUE TITLE
Fix BongaCams.py in Streamlink

### ISSUE THREAD

**Issue by webliftro** [streamlink/streamlink#1300]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

The streamlink plugin for bongacams no longer works.

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

https://en.bongacams.com/xxxSexyLexy

### Environment details

Operating system and version: ...
Ubuntu Server 16.04
Streamlink and Python version: ...

streamlink 0.7.0
Python 2.7.12

### Comments, logs, screenshots, etc.

streamlink https://en.bongacams.com/xxxSexyLexy best -o xxxSexyLexy.flv
[cli][info] Found matching plugin bongacams for URL https://en.bongacams.com/xxxSexyLexy
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.7.0', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 482, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 345, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/streamlink/plugin/plugin.py", line 248, in streams
    ostreams = self._get_streams()
  File "/usr/lib/python2.7/dist-packages/streamlink/plugins/bongacams.py", line 112, in _get_streams
    amf_response = AMFPacket.deserialize(BytesIO(r.content))
  File "/usr/lib/python2.7/dist-packages/streamlink/packages/flashmedia/packet.py", line 22, in deserialize
    raise cls.exception(err)
streamlink.packages.flashmedia.error.AMFError: Unable to read required amount of data

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
You are using an outdated Streamlink version. The bongacams plugin was fixed in one of the recent releases.
Please use the search function next time before opening a new issue:
https://github.com/streamlink/streamlink/issues?utf8=%E2%9C%93&q=bongacams

**Comment by webliftro** [comment]
Sorry about this, missed it somehow.
