### ISSUE TITLE
Chaturbate plugin don't work anymore

### ISSUE THREAD

**Issue by zanna7777** [streamlink/streamlink#1301]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Error:  Unabel to open url ......... bad packet lenght

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
There's nowhere near enough information on this issue for us to take any action, did you review the existing issues for this plugin related to certain models not working? I'm going to leave this open so you can add more information, if we don't see that I'll have to close it.

**Comment by wiemar7** [comment]
please add support for showup.tv
