### ISSUE TITLE
Restreaming dynamic HLS live stream

### ISSUE THREAD

**Issue by pavs** [streamlink/streamlink#1304]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
I am trying to use streamlink on this URL: http://www.bioscopelive.com/en/channel/maasranga-tv
...

### Expected / Actual behavior
It's a live tv with dynamic URL which changes on every refresh or after every 60 minutes. 
I want to know if I can use streamlink in some form to pipe stream to VLC or jwplayer, and auto-update when dynamic m3u8 link changes.   

...

### Reproduction steps / Explicit stream URLs to test

1. http://www.bioscopelive.com/en/channel/maasranga-tv

### Environment details

Operating system and version: OSX High Sierra
Streamlink and Python version: python 3.6 

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
To begin with we don't support that site via a plugin. On top of that looking at the site, Wikipedia, and the content you want to watch it's very clearly a stolen broadcast for sports (cricket in this case). As such I'm closing this.
