### ISSUE TITLE
Neulion stream with alternative language

### ISSUE THREAD

**Issue by stecooper** [streamlink/streamlink#1305]
I've modified the ufctv.py plugin to open a different Neulion stream - Eleven Sports Taiwan. It works fine but only provides the Mandarin language audio stream and not the alternative English option.

The M3u8 file is as follows:

```
 #EXTM3U
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="Default",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="def"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="Alternate",DEFAULT=NO,AUTOSELECT=NO,LANGUAGE="alt",URI="eleven_tw_audio_alt.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=150000,AUDIO="aac"
eleven_tw_hd_150.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=240000,AUDIO="aac"
eleven_tw_hd_240.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=400000,AUDIO="aac"
eleven_tw_hd_400.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=800000,AUDIO="aac"
eleven_tw_hd_800.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1200000,AUDIO="aac"
eleven_tw_hd_1200.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1600000,AUDIO="aac"
eleven_tw_hd_1600.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3000000,AUDIO="aac"
eleven_tw_hd_3000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4500000,AUDIO="aac"
eleven_tw_hd_4500.m3u8
```

Is there any way to select the alternative language feed and use that muxed with the video? I get "Available streams: 150k (worst), 240k, 400k, 800k, 1200k, 1600k, 3000k, 4500k (best)" but can't find a way to select English audio. One of those individual m3u8 files is included as an example below also

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1586272
#EXT-X-KEY:METHOD=AES-128,URI="https://nlsk3sg.neulion.com/nlsk3/hls/securekey?....[redacted]"
#EXTINF:10,
eleven_tw_hd_1200_20171102114650.ts
#EXTINF:10,
eleven_tw_hd_1200_20171102114700.ts
#EXTINF:10,
eleven_tw_hd_1200_20171102114710.ts
#EXTINF:10,
eleven_tw_hd_1200_20171102114720.ts
#EXTINF:10,
eleven_tw_hd_1200_20171102114730.ts
#EXTINF:10,
eleven_tw_hd_1200_20171102114740.ts
```

Alternative audio m3u8:

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:1581937
#EXT-X-KEY:METHOD=AES-128,URI="https://nlsk3sg.neulion.com/nlsk3/hls/securekey?...[redacted]"
#EXTINF:10,
eleven_tw_audio_alt_20171101234420.ts
#EXTINF:10,
eleven_tw_audio_alt_20171101234430.ts
#EXTINF:10,
eleven_tw_audio_alt_20171101234440.ts
#EXTINF:10,
eleven_tw_audio_alt_20171101234450.ts
#EXTINF:10,
eleven_tw_audio_alt_20171101234500.ts
#EXTINF:10,
eleven_tw_audio_alt_20171101234510.ts

```

Thanks

**Comment by beardypig** [comment]
What if you try adding `--hls-audio-select alt`?

**Comment by stecooper** [comment]
I've tried the following but no luck:

```
streamlink -l debug  --hls-audio-select Alternate  https://www.elevensports.tw/channel/eleven-zh 400k

streamlink -l debug  --hls-audio-select alt https://www.elevensports.tw/channel/eleven-zh 400k

streamlink -l debug  --hls-audio-select "alt" https://www.elevensports.tw/channel/eleven-zh 400k
```

I've confirmed on the ElevenSports site that the alternative language is currently "on-air" when I tried the above too.

**Comment by stecooper** [comment]
I've just looked at https://github.com/streamlink/streamlink/pull/684 and seen that --hls-audio-select=alt should be the syntax.  Unfortunately there isn't alternative language being broadcast at the moment.

Hopefully I'll confirm if this has worked later.

**Comment by stecooper** [comment]
Sorry for another reply. But this can be closed, streamlink couldn't find ffmpeg!

Thanks to beardypig for telling me about his --hls-audio-select ( should have read the docs!). I managed to debug through hls.py and find where I was coming unstuck.

I'll finish off an Eleven Sport plugin and publish it.

**Comment by karlo2105** [comment]
I confirm when I open Eleven Taiwan with switch --hls-audio-select=alt, VLC proposes two available audios (audio track 1=default and audio track 2=alternate), but audio track 1 is selected by default. --hls-audio-select switch muxes two audios simultaneously but you can start stream with alternate audio selected by default. 
Without switch only default audio track 1 is available. 

It would be interesting if --hls-audio-select switch could propose to start stream with selected audio by default and if all available audios could be proposed as ffmpeg can mux multiple audios. ;)

**Comment by ex0de** [comment]
Any news on the plugin?
