### ISSUE TITLE
Playlist/enqueuing streams

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1308]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Not really a Streamlink issue, rather I'm looking for some advice on how to use it in a certain way.

I would like to schedule a number of streams to play one after another from different sources (BBC iPlayer, YouTube and the like) - what would be the best way to go about it?

I've already made a small bash script to dynamically fetch the latest episode of whatever it is I'm looking for, now I want them to play back to back automatically. I could just cron each to start at a certain time, but I don't want to end up cutting videos short by a minute or two, or having gaps between them either.

I looked through the guide but couldn't seem to find anything applicable. Is there perhaps some sort of event that triggers when the stream ends so I can run another bash command directly after?

**Comment by beardypig** [comment]
streamlink should exit when the stream completes, so you should just be able to do
```
#!/bin/bash
streamlink youtube.com/w/56789 best 
streamlink youtube.com/w/98765 best 
streamlink youtube.com/w/58932 best 
```

**Comment by gravyboat** [comment]
I'm going to close this since @beardypig was kind enough to provide a relatively succinct solution.
