### ISSUE TITLE
Embedding HLS stream to player on website

### ISSUE THREAD

**Issue by StevoLopata** [streamlink/streamlink#1309]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would it be possible to send the stream instead of local player to player on my website? Some sort of m3u8 extraction, but without encryption?
...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: Python 3.5, Streamlink 0.8.1

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/908#issuecomment-300839545
