### ISSUE TITLE
Got size 0 size on disk >0 file

### ISSUE THREAD

**Issue by bupmc** [streamlink/streamlink#1310]
![1](https://user-images.githubusercontent.com/20588954/32471421-257f8ad6-c398-11e7-8dfb-1cd11e026cf7.PNG)

**Comment by gravyboat** [comment]
There is nowhere near enough information provided here for us to help you in any way. What does the command you are running look like that creates this error, and why did you not use the issue template? We expect some level of detail and information which this does not conform to at all.

**Comment by back-to** [comment]
**requires more details, not just a screenshot.**
