### ISSUE TITLE
How they play this NBA stream from 

### ISSUE THREAD

**Issue by fluffmilton** [streamlink/streamlink#1312]
Here the code:
======================================
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
<script src="https://cdn.jsdelivr.net/clappr.chromecast-plugin/latest/clappr-chromecast-plugin.js"></script>

<div id="vid"></div>
<script type="text/javascript">
          var data = {source:"http://nlds310.cdnllnwnl.neulion.com/nlds/nba/gsw/as/live/nlncp/gsw_hd.m3u8",replace:"http://nlds310.cdnllnwnl.neulion.com/key/nlsk3/nlsk4/hls/securekey?",keyurl:"/keys/nbabesa?"} 
            if(data.source != ""){
            if (data.source.indexOf('chashbrc') != -1) {
                flowplayer("#vid", {
                    embed: false,
                    fullscreen: true,
                    share:false,
                    allowfullscreen: true,
                    native_fullscreen: true,
                    autoplay: false,
                    hlsjs: { 
                      xhrSetup: function(xhr) {
                        xhr.withCredentials = true;
                      } 
                    },
                    clip: {
                      live: true,
                      sources: [
                        { type: "application/x-mpegURL",
                          src : data.source }
                      ]
                    }
                });
                document.cookie = "access=true";
            } else {
                player = new Clappr.Player({
                source: data.source,
                mimeType: "application/x-mpegURL",
                    autoPlay: false, 
                    height: '600',
                    width: '1024',
                plugins: {'core': [LevelSelector]},   
				mediacontrol: {seekbar: "#6fff00", buttons: "#FFF"},
                parentId: "#vid"});
                if(data.replace != ""){
                    (function (open) {
                    XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
                    if (url.toLowerCase().indexOf("besasport.top") >= 0) {
                      return;
                    }
                    var rewrittenUrl = url;
                    rewrittenUrl = rewrittenUrl.replace(data.replace, data.keyurl);
                    open.call(this, method, rewrittenUrl, async, user, pass);
                    };
                    })(XMLHttpRequest.prototype.open);
                }
            }
        } else {
            var img = new Image();
            var div = document.getElementById('vid');

            img.onload = function() {
              div.appendChild(img);
            };
            img.src = '';
            img.className = "hold";
}
</script>

============

I know its play because **keyurl:"/keys/nbabesa?"** how can i access that **keyurl** Hoping your help on this thank you...

**Comment by back-to** [comment]
well support for https://watch.nba.com/ could be easily added https://github.com/streamlink/streamlink/issues/1130#issuecomment-320956989


but that is not what you want

---

the keyfile is just rehosted on an **unofficial server**,
with this they just _bypass the authentication_ from the **official website**

i don't think streamlink is the right place for this https://github.com/streamlink/streamlink/issues/1304#issuecomment-341158555

**Comment by gravyboat** [comment]
@back-to Agreed, we aren't bypassing authentication or supporting these sorts of rehosts when we can avoid it, the risk is too great.

**Comment by fluffmilton** [comment]
they used a keys to restream it, i think they setup a keys in SSH Access but i have no idea... how?

**Comment by tandon** [comment]
It has nothing to do with SSH. As noted earlier, this is not something that should be discussed here.

**Comment by agadirian** [comment]
@fluffmilton Me too I want to know how ,did you find how they did that ?
