### ISSUE TITLE
Plugin Request: Rooster Teeth

### ISSUE THREAD

**Issue by DoomTay** [streamlink/streamlink#1320]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
This is one of those HLS types that are (sometimes) multiquality.

The file is gotten from the RT.currentVideo  object defined on the page itself

### Example URLs
http://www.roosterteeth.com/episode/rwby-season-1-red-trailer (This one seems to only have one quality setting)
http://www.roosterteeth.com/episode/rwby-volume-4-volume-4-chapter-1-shu39d
http://roosterteeth.com/episode/red-vs-blue-season-15-trailer

**Comment by techmouse** [comment]
I'm honestly not trying to shamelessly plug my own stuff, but I see you're making a request for something I've already got working.

If you use Linux, MacOS or any OS that supports BASH scripts, you can watch all 3 of those example videos you posted from your favorite player using this:
https://github.com/techmouse/livestreamlinkgui
