### ISSUE TITLE
Add python and possibly OS version to --version argument

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink#1323]
### Checklist

- [x] This is a feature request.
- [x] I have read the contribution guidelines.

### Description

Currently, `streamlink --version` only shows streamlink's version.
As for other programs, to make debugging/bug report easier and quicker, the command could also show the python's version it's running on, and possibly if not too complicated to figure out, the OS and OS version it's running on.

### Expected / Actual behavior

Have `streamlink --version` printing python and OS versions

### Reproduction steps / Explicit stream URLs to test

Just by using `streamlink --version`

### Environment details

Operating system and version: macOS 10.9
Streamlink and Python version: streamlink 0.8.1, probably running through system or homebrew's python (streamlink installed with homebrew).

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Nice idea, I like it 👍

**Comment by beardypig** [comment]
How about something like this
```
streamlink 0.8.1 (Python 3.6.1; Linux-4.4.0-97-generic-x86_64-with-debian-stretch-sid)
streamlink 0.8.1 (Python 3.6.0; macOS 10.12.6)
streamlink-script.py 0.8.1 (Python 3.5.2; Windows 10)
```

**Comment by Porkepix** [comment]
Looks good to me for Windows and macOS.
For Linux I think that not all the distributions provide their name in the kernel, and some users could use custom kernels. So, maybe is there some other way to access the information through Python libs?
Some distributions also have one file like `/etc/lsb_release`, `/etc/debian_version` and so on.

I found https://docs.python.org/3/library/platform.html#unix-platforms that seems to do the job with `platform.linux_distribution()`.

It seems you already came up with a patch so I'll let you with this :)

**Comment by Porkepix** [comment]
Oh, and I think that issue template could be updated after this.
Plus if there's common contributors between here and twitch GUI, adding something copyable and pastable there could be nice too. Otherwise I can open an issue there if you want.

**Comment by bastimeyer** [comment]
> How about something like this
> 
> streamlink 0.8.1 (Python 3.6.1; Linux-4.4.0-97-generic-x86_64-with-debian-stretch-sid)
> streamlink 0.8.1 (Python 3.6.0; macOS 10.12.6)
> streamlink-script.py 0.8.1 (Python 3.5.2; Windows 10)

I'm fine with this, @beardypig, as long as you don't break the regexp of the Twitch GUI for checking Streamlink's version:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/config/streamprovider.json#L16

> I think that issue template could be updated after this

Good idea, could you open a pull request then, @Porkepix? Thanks!

> adding something copyable and pastable there could be nice too

You mean from the Twitch GUI? Check the log files.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

**Comment by Porkepix** [comment]
Well I think issue should be opened for the template only once this one will be closed, so I'll try not to forget.
For the copyable and pastable part in Twitch GUI, I was thinking just inside the Application itself, not in log files, what do you think about this @bastimeyer

**Comment by bastimeyer** [comment]
@beardypig 
I forgot to add that the output should also be one single line, just like it is now...
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/services/StreamingService/provider/validate.js#L56-L60

@Porkepix 
It is showing you most of the errors, but not everything. AFAIK, the VLC issue on macOS is also only noticable if you're including the stdout of the player via the `--verbose-player` Streamlink option.
I haven't had the time and motivation yet to rewrite the stream launch dialog, which would be required for that. But that's an issue that should not be discussed here.

**Comment by Porkepix** [comment]
Oh, @bastimeyer  you may have mixed this issue with the other one I reported.
What I meant is that as you can do `streamlink --version`, you could have somewherein the Application, whether it is the About dialog or another place with just the GUI, streamlink and OS version to paste on an issue here.

For the validation part you're pointing out, I guess it's possible to adapt validation regexp according to changes here if there are some?

**Comment by bastimeyer** [comment]
> For the validation part you're pointing out, I guess it's possible to adapt validation regexp according to changes here if there are some?

That's an unnecessary breaking change and would require a new release of the Twitch GUI.
The regexp matches the suggested changes, but since there is no pull request opened yet, I just wanted to mention it (before a PR gets merged without me noticing it).

**Comment by bastimeyer** [comment]
Thinking about this feature request again, I'd say that these changes belong into the `1.0.0` release, because they might break other applications.

**Comment by beardypig** [comment]
@Porkepix the Linux one uses [`platform.platform()`](https://docs.python.org/3/library/platform.html#platform.platform), which returns a string with the most information available. `platform.linux_distribution()` is deprecated since version 3.5, and will be removed in version 3.7.

@bastimeyer your regex should still match, assuming the JS regex works like Python :) It is possible that it could break something, I guess...

**Comment by Porkepix** [comment]
My bad… didn't noticed the little deprecation line… :( (Although I did see the one about `platform.dist()` !)

**Comment by back-to** [comment]
if it could break other applications,
why not just add it to `-l debug` instead and force every github issue to have a debug log :fast_forward:

**Comment by beardypig** [comment]
@back-to that'd a good idea. Like if you specify `-l debug` it automatically adds the version info at the top?

**Comment by Porkepix** [comment]
Doing so wouldn't exclude having it `--version` I think?
If the plan would be this one, then this would be one more reason to have a full versions summary in overlays like the twitch one.

**Comment by back-to** [comment]
@beardypig yes at the top,
if you use `-l debug` it will always print the version about the os, python, streamlink ...
and maybe not that important the requests, PySocks, websocket version

**Comment by back-to** [comment]
```diff
diff --git a/src/streamlink_cli/main.py b/src/streamlink_cli/main.py
index bcc162a..c4c3993 100644
--- a/src/streamlink_cli/main.py
+++ b/src/streamlink_cli/main.py
@@ -1,6 +1,7 @@
 import errno
 import os
 import requests
+import platform
 import sys
 import signal
 import webbrowser
@@ -11,12 +12,17 @@ from functools import partial
 from itertools import chain
 from time import sleep
 
+from socks import __version__ as pysocks_version
+
+from streamlink import __version__ as streamlink_version
 from streamlink import (Streamlink, StreamError, PluginError,
                         NoPluginError)
 from streamlink.cache import Cache
 from streamlink.stream import StreamProcess
 from streamlink.plugins.twitch import TWITCH_CLIENT_ID
 
+from websocket import __version__ as websocket_version
+
 from .argparser import parser
 from .compat import stdout, is_win32
 from .console import ConsoleOutput
@@ -1024,6 +1030,14 @@ def main():
     setup_http_session()
     check_root()
 
+    if args.loglevel == 'debug':
+        console.logger.debug('OS version:         {0}'.format(platform.platform()))
+        console.logger.debug('PySocks version:    {0}'.format(pysocks_version))
+        console.logger.debug('Python version:     {0}'.format(platform.python_version()))
+        console.logger.debug('Requests version:   {0}'.format(requests.__version__))
+        console.logger.debug('Streamlink version: {0}'.format(streamlink_version))
+        console.logger.debug('Websocket version:  {0}'.format(websocket_version))
+
     if args.version_check or (not args.no_version_check and args.auto_version_check):
         with ignored(Exception):
             check_version(force=args.version_check)
```

```
$ streamlink https://www.twitch.tv/monstercat best -l debug
[cli][debug] OS version:         Linux-4.14.3-1-ARCH-x86_64-with-arch-17.11-ISO-Rolling
[cli][debug] PySocks version:    1.6.7
[cli][debug] Python version:     3.6.3
[cli][debug] Requests version:   2.18.4
[cli][debug] Streamlink version: 0.9.0
[cli][debug] Websocket version:  0.44.0
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/monstercat
[plugin.twitch][debug] Getting live HLS streams for monstercat
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
...
```

would this be enough
or
is this too much
or
should it still be used with `streamlink --version`

**Comment by Porkepix** [comment]
I guess it's fine. Debug log could also show the video player it's planning to use, but I'm not sure of the value this could have.
I think some versions could also be useful in `streamlink --version` if not all, or another version like a verbose version either by combining two options or having a verbose versions one if there's a risk to break other projects as mentioned earlier.

I'll let project maintainers decide on those though.

**Comment by beardypig** [comment]
@back-to `platform.platform()` for macOS and Windows is not so friendly, I made a little function that has a nicer output:

```python
def os_version():
    # MAC OS X
    if sys.platform == "darwin":
        return "macOS {0}".format(platform.mac_ver()[0])
    # Windows
    elif sys.platform.startswith("win"):
        return "{0} {1}".format(platform.system(), platform.release())
    # linux / other
    else:
        return platform.platform()
```
