### ISSUE TITLE
Streamlink giving unrecognized argument error when after entering command

### ISSUE THREAD

**Issue by Dalonomus** [streamlink/streamlink#1324]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Built a new computer to replace my old rig which was having all sorts of problems.  Installed streamlink and unfortunately im gettin a strange error

### Expected / Actual behavior
Expected behavior is stream launch just like on my old system
...
actual behavior is well......
C:\Users\Dale>streamlink.exe twitch.tv/leveluplive best
usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
streamlink-script.py: error: unrecognized arguments: twitch.tv/leveluplive best

### Environment details

Operating system and version: windows 10 pro 64bit ver:1703
Streamlink and Python version: Streamlink 0.8.1

Ive never seen this before and ive been using livestreamer and streamlink for a while on win7.  Is this a windows 10 thing??

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
How did you install Streamlink and which streamlink.exe are you executing?

**Comment by Dalonomus** [comment]
Ok so it seems streamlink portable works fine. Which means something is up with the python install on my system or maybe lack there of?? Ill have to go check this out but for now at least i have a working stream link in the form of portable so i guess this can be closed.
