### ISSUE TITLE
Plugin Request: video.sky.it/news/diretta

### ISSUE THREAD

**Issue by tigro7** [streamlink/streamlink#1325]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

The page to the live streaming of Sky Tg24 is video.sky.it/news/diretta
From HTML i've found this link to the video: blob:http://video.sky.it/777bd287-e872-40b8-a3e7-34329639a863

**Comment by johnthecracker** [comment]
http://video.sky.it/777bd287-e872-40b8-a3e7-34329639a863

You can find better link than that with firefox and httpfox plugin, and play the stream with streamlink.

http://skyianywhere2-i.akamaihd.net/hls/live/200275/tg24/playlist.m3u8?Origin=video.sky.it

C:\>streamlink.exe hlsvariant://"http://skyianywhere2-i.akamaihd.net/hls/live/200275/tg24/playlist.m3u8?Origin=video.sky.it" best
[cli][info] Found matching plugin hls for URL hlsvariant://http://skyianywhere2-i.akamaihd.net/hls/live/200275/tg24/playlist.m3u8?Origin=video.sky.it
[cli][info] Available streams: 202p (worst), 360p_alt, 360p, 404p_alt2, 404p_alt, 404p (best)
[cli][info] Opening stream: 404p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by tigro7** [comment]
thank you for your support, i didn't know about this alternative source.

**Comment by back-to** [comment]
It's one **static url**

you can get the static url, from here

http://videoplatform.sky.it/player/json/get_livestream_1.json

**it's changing very rarely**,
if they change it the whole website will change most likely as well.

not really worth a plugin for a static url without any session id requirements.

Just use the hls plugin with

`streamlink hls://http://skyianywhere2-i.akamaihd.net/hls/live/200275/tg24/playlist.m3u8 best`

Closing.
