### ISSUE TITLE
iconafricatv.com/gospel-tv plugin

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#1327]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

African gospel music website.

### Reproduction steps / Explicit stream URLs to test

http://www.iconafricatv.com/gospel-tv

temporary link:

https://str13.infomaniak.ch/dl/fca0a18052f7d02907dfae2d4421272e/5a0344f3/iconafricatv_vod/9/1/denamwana-nzambemoneneawesome_howgreatisourgodofficiel.32512.12.mp4?playlist=3333

### Comments

I don't have slightest problem downloading these videos but that is not really what I want.

It would be great to watch this program "as it goes" in a player. 

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
https://www.youtube.com/watch?v=y2upkT5X1ZU

**Comment by back-to** [comment]
same as #854 and #1088 

it's a **list of different video urls**

streamlink does not really has a _simple feature_,
that would **sync** the list as it plays in the browser

**Comment by johnthecracker** [comment]
Thank you for looking at possibility of this working with streamlink.

Similar issue is referenced in 2 other threads, so this can be closed.

**Comment by diksimo1** [comment]
streamlink does not really
