### ISSUE TITLE
Streamlink fails to record Smashcast HLS Streams

### ISSUE THREAD

**Issue by desaku** [streamlink/streamlink#1328]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Streamlink fails to record HLS streams from Smashcast with a `403 Client Error: Forbidden for this url`

I've found that not all streams on Smashcast fail, only the ones using HLS.

### Expected / Actual behavior
Streamlink succesfully records an HLS stream from Smashcast

### Reproduction steps / Explicit stream URLs to test

1. Run `streamlink smashcast.tv/mikecast best`
2. The command fails with:
```
[cli][info] Found matching plugin hitbox for URL smashcast.tv/mikecast
[cli][info] Available streams: 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://edge.hls.hitbox.tv/hls/ll/mikecast/index.m3u8?st=lEz8QprMVhKTK5fkkLYsEg;ci=0zTMpKgUs18jeenB1ZB8DQ')> (Could not open stream: Unable to open URL: http://edge.hls.hitbox.tv/hls/ll/mikecast/index.m3u8?st=lEz8QprMVhKTK5fkkLYsEg;ci=0zTMpKgUs18jeenB1ZB8DQ (403 Client Error: Forbidden for url: http://edge.hls.hitbox.tv/hls/ll/mikecast/index.m3u8?st=lEz8QprMVhKTK5fkkLYsEg;ci=0zTMpKgUs18jeenB1ZB8DQ))
error: Could not open stream <HLSStream('http://edge.hls.hitbox.tv/hls/ll/mikecast/index.m3u8?st=lEz8QprMVhKTK5fkkLYsEg;ci=0zTMpKgUs18jeenB1ZB8DQ')>, tried 1 times, exiting
```

### Environment details

Operating system and version: from `uname -a`:

`Linux arch 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux`

Streamlink and Python version: 

`streamlink  --version`: `streamlink 0.8.1`
`python --version`: `Python 3.6.3`

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by desaku** [comment]
After doing further research, this appears to be either an API issue, or Smashcast is no longer relying on `edge.hls.hitbox.tv`

**Comment by intact** [comment]
Try to change PLAYER_API to:

`PLAYER_API = "https://www.smashcast.tv/api/player/config/{0}/{1}?embed=false&showHidden=true&ssl=true"`

**Comment by desaku** [comment]
Thank you! That was the problem, and adding the flag `&ssl=true` fixes it

**Comment by gravyboat** [comment]
@intact Do you want to open a PR to swap the url ovre to the ssl version? It's over here: https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/hitbox.py#L13

**Comment by back-to** [comment]
it works again, ssl parameter is not required

```
$ streamlink smashcast.tv/--NAME--
[console][info] Found matching plugin hitbox for URL smashcast.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink www.smashcast.tv/--NAME--
[console][info] Found matching plugin hitbox for URL www.smashcast.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink http://www.smashcast.tv/--NAME--
[console][info] Found matching plugin hitbox for URL http://www.smashcast.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink https://www.smashcast.tv/--NAME--
[console][info] Found matching plugin hitbox for URL https://www.smashcast.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink hitbox.tv/--NAME--
[console][info] Found matching plugin hitbox for URL hitbox.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink http://www.hitbox.tv/--NAME--
[console][info] Found matching plugin hitbox for URL http://www.hitbox.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)

$ streamlink https://www.hitbox.tv/--NAME--
[console][info] Found matching plugin hitbox for URL https://www.hitbox.tv/--NAME--
[console][info] Available streams: 1080p (worst, best)
```
