### ISSUE TITLE
The latest nightly still says 0.8.1

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#1333]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Downloading the latest nightly https://dl.bintray.com/streamlink/streamlink-nightly/streamlink-latest.exe says it is 0.8.1+ and not 0.9+ But when I go here https://dl.bintray.com/streamlink/streamlink-nightly/ I can find the latest 0.9+ nightly If I download the one above streamlink-latest.exe

---

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Seems to be an issue with the way we use BinTray. You cannot replace a version that is over 180 days old - which is what we do with the "latest" version. We'll need to re-think how to publish the latest version.

**Comment by bastimeyer** [comment]
So according to https://bintray.com/docs/api/#_delete_content
streamlink-latest.exe can't be rewritten or deleted anymore?
You can't delete it by using their website either. That's stupid... I guess the docs need to be updated then.

**Comment by bastimeyer** [comment]
Can this be prevented by making a delete API call each time a new installer gets uploaded? Apparently, rewriting the file doesn't trigger a new expiration date.

Then we can just use a different name like streamlink-most-recent.exe or so...

**Comment by beardypig** [comment]
Yeah, annoying though :) 

I was trying to find out a better way to do it, to just download the latest file regardless of the version - but that seems to be a premium only option. I wonder if we could (ab)use github releases to make a nightly tag that we overwrite every night and upload a `streamlink-latest.exe`...

**Comment by bastimeyer** [comment]
> github releases

That'll generate a lot of spam. Everyone who's watching the repo gets notified of each new release. And the release list also becomes a bit messy with a "prerelease" on top. This would be quite confusing for casual users who've just landed on the releases site and don't expect to find a prerelease at the top of the releases list. Creating a new repo for that purpose sounds like a better option. It would still appear in the dashboard of each Streamlink team member, doesn't it?

**Comment by beardypig** [comment]
Maybe in the meantime, as we don't have a good solution we can link to https://bintray.com/streamlink/streamlink-nightly/streamlink/_latestVersion/#files ?
