### ISSUE TITLE
How to play this m3u8 source on my website

### ISSUE THREAD

**Issue by agadirian** [streamlink/streamlink#1335]
I try to copy this code but not working only loading... when i check this site its playing typefooty.com/vip/vip5.html because i think not playing because of this keyurl:"/keys/nbanew?" can you help me about this

<script type="text/javascript">
var data = {source:"http://neunlds289.akamaized.net/nlds/nba/mia/as/live/nlncp/mia_hd.m3u8",replace:"http://neunlds289.akamaized.net/key/nlsk3/nlsk4/hls/securekey?",keyurl:"/keys/nbanew?"} 
if(data.source != ""){
if (data.source.indexOf('chashbrc') != -1) {
flowplayer("#vid", {
embed: false,
fullscreen: true,
share:false,
allowfullscreen: true,
native_fullscreen: true,
autoplay: true,
hlsjs: { 
xhrSetup: function(xhr) {
xhr.withCredentials = true;
} 
},
clip: {
live: true,
sources: [
{ type: "application/x-mpegURL",
src : data.source }
]
}
});
document.cookie = "access=true";
} else {
player = new Clappr.Player({
source: data.source,
mimeType: "application/x-mpegURL",
autoPlay: true, 
height: '100%',
width: '100%',
watermark: '',
position: 'top-right',
watermarkLink: "/",
plugins: {'core': [LevelSelector]}, 
parentId: "#vid"});
if(data.replace != ""){
(function (open) {
XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
if (url.toLowerCase().indexOf("fwmrm.net") >= 0) {
return;
}
var rewrittenUrl = url;
rewrittenUrl = rewrittenUrl.replace(data.replace, data.keyurl);
open.call(this, method, rewrittenUrl, async, user, pass);
};
})(XMLHttpRequest.prototype.open);
}
}
} else {
var img = new Image();
var div = document.getElementById('vid');

img.onload = function() {
div.appendChild(img);
};
img.src = '';
img.className = "hold";
}

</script>

**Comment by gravyboat** [comment]
Looks similar to this issue: https://github.com/streamlink/streamlink/issues/1312 and as noted there we aren't bypassing auth or supporting rehosting. Closing and locking this since you were on the other thread and clearly saw we weren't going to support it, then went ahead and created a new issue any way.
