### ISSUE TITLE
How they play this NBA stream on website

### ISSUE THREAD

**Issue by agadirian** [streamlink/streamlink#1336]
**Here the code:**

html>
head>

<script type="text/javascript" src="https://cdn.jsdelivr.net/clappr/latest/clappr.min.js"></script> <script type="text/javascript" src="https://cdn.jsdelivr.net/clappr.level-selector/latest/level-selector.min.js"></script>
/head>
bod>

<script> var data = {source:"http://nlds316.cdnak.neulion.com/nlds/nba/lal/as/live/nlncp/lal_hd.m3u8",replace:"http://nlds316.cdnak.neulion.com/key/nlsk3/nlsk4/hls/securekey?",keyurl:"http://54.186.16.121/key/nlsk3/nlsk4/hls/securekey?"} player = new Clappr.Player({ source: data.source, mimeType: "application/x-mpegURL", autoPlay: false, height: '100%', width: '100%', plugins: {'core': [LevelSelector]}, parentId: "#w3lovesport"}); if(data.replace != ""){ (function (open) { XMLHttpRequest.prototype.open = function (method, url, async, user, pass) {
                var rewrittenUrl = url;
                rewrittenUrl = rewrittenUrl.replace(data.replace, data.keyurl);
                open.call(this, method, rewrittenUrl, async, user, pass);
                };
                })(XMLHttpRequest.prototype.open); 
            }
            document.cookie = "access=true";
</script>
/body>
/html>

**Comment by bastimeyer** [comment]
I think @gravyboat was clear enough with his answer in your previous (re)post:
https://github.com/streamlink/streamlink/issues/1335#issuecomment-345486340

This is now the third time this kind of low effort thread has been created here and the second thread posted by you in less than 18 hours. Stop it, or you'll get reported for abuse.
