### ISSUE TITLE
Mediaset (mitele.es) not work propperly

### ISSUE THREAD

**Issue by vk496** [streamlink/streamlink#1337]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

http://www.mitele.es not get the stream propperly

### Expected / Actual behavior

Expected: Get the stream link
...
Actual: `error: Unable to open URL: https://mdslivegeo.mediaset.es/out/u/3vkkbgnvsm2r5/104951/NmbWM5YjE6LAH8o-VL3vr3hw3JqSTnRU/cn/fb3d6852c1ac44c982aa727fe9e791cd.m3u8 (403 Client Error: Forbidden for url: https://mdslivegeo.mediaset.es/out/u/3vkkbgnvsm2r5/104951/NmbWM5YjE6LAH8o-VL3vr3hw3JqSTnRU/cn/fb3d6852c1ac44c982aa727fe9e791cd.m3u8)`
### Reproduction steps / Explicit stream URLs to test

`streamlink http://www.mitele.es/directo/boing best -l debug`

### Environment details

Operating system and version: Manjaro XFCE 17.1
Streamlink and Python version: streamlink 0.9.0 / Python 3.6.3

### Comments, logs, screenshots, etc.

```bash
$ streamlink http://www.mitele.es/directo/boing worst -l debug
[cli][info] Found matching plugin mitele for URL http://www.mitele.es/directo/boing
[plugin.mitele][debug] Using cached sessionKey
[plugin.mitele][debug] Got api key: tsbmYyOjRH6dK3rmGxeTP2uleUj_.VG0Ka
[plugin.mitele][debug] Got channel ID ZvOXRpODE6c__EQ05epWGBX6530x-EhS for channel boing
error: Unable to open URL: https://mdslivegeo.mediaset.es/out/u/3vkkbgnvsm2r5/104951/ZvOXRpODE6c__EQ05epWGBX6530x-EhS/cn/ddf752ff80af43709eabdf84e1d65366.m3u8 (403 Client Error: Forbidden for url: https://mdslivegeo.mediaset.es/out/u/3vkkbgnvsm2r5/104951/ZvOXRpODE6c__EQ05epWGBX6530x-EhS/cn/ddf752ff80af43709eabdf84e1d65366.m3u8)
```

**Comment by beardypig** [comment]
Are you streaming from Spain? Have you tried any other channels other than Boing?

**Comment by vk496** [comment]
Hello,

No, I'm not streaming from Spain. Maybe this is the problem (For example, "Cuatro", sometimes work, sometimes throw me the same error).

Also, would be great to include all others channels availabe in the web [(http://www.mitele.es/directo)](http://www.mitele.es/directo)

Salu2

**Comment by urnenfeld** [comment]
I am streaming from Spain the current error shown is:

```
oliver@lubuntu:~$ streamlink http://www.mitele.es/directo/boing worst -l debug
[cli][info] Found matching plugin mitele for URL http://www.mitele.es/directo/boing
[plugin.mitele][debug] Using cached sessionKey
[plugin.mitele][debug] Got api key: tsbmYyOjRH6dK3rmGxeTP2uleUj_.VG0Ka
error: Unable to validate JSON: Unable to validate key 'locations': Key 'yoo' not found in {u'gbn': None, u'gat': u'//gatekeeper.mediaset.es', u'pri': 1, u'gcp': u'MDAwMDQ0M3pUdnpyM3A2N1ZDNjFqbVY1NHJJWXUxNTQ1eDRUbFk=20b8d4625e7a273badf8ffb8640c95fad277add29c5414cbe35695eb9982ccbc6700ab94c250beb5643eb086870717f501384a18ab7d4d9ed6598e99a5410c3596c6befd20723a910757eb839f1b103dda8a8e7fee2cca7e924e502addcd16e5cc5051e235c2e8b5aca74c01a9e2c4', u'ogn': u'o0t6vboys4gf5myd/zPCDTrD4mngkRY2xpxAy2RZpc8YKMY/OXWaKkIdDCyb1JsIKjCZ1AX0ylNLwo7kPa/4h0j6jEXEzzq1zbN69Jz07zU=', u'ogk': u'YmJDMkgxOWxrVmJRRGZha3hjcnROTVFkZDBGbG9MeXc=', u'ask': None}
```

**Comment by vk496** [comment]
I confirm the same issue

Salu2

**Comment by back-to** [comment]
i can't really test it, you need to be in spain or have an **ip from spain**

i get **some valid ur**l's from the api, but sometimes there are **only** the **params**
i'm not sure if the url with the params would work

https://gist.githubusercontent.com/back-to/686bd4ae2e70ff263dbd8300db7c5505/raw/e671e6d012e69f209959ad80cd95643961695201/mitele.py

@vk496 @urnenfeld 
would be nice if you could test all the channel with it,
the best way is to sideload the plugin.

---

- Sideload the plugins in a ...
    - custom folder https://streamlink.github.io/cli.html#cmdoption-plugin-dirs
    - default folder https://streamlink.github.io/cli.html#sideloading-plugins

**Comment by urnenfeld** [comment]
Hello @back-to I have tested from Spain:

My investigations with wireshark were that the host streaming was *livehlsdai-i.akamaihd.net* the **key HTTP** request I got is similar to the one you are composing, but the parameters after the *master.m3u8?* differ... anyway you are some steps beyond I think:)

Let me know if I can dump some intermediate vars which could help.

The gist you posted is copied in the folder ./plugintest I am 99% it is fetching your version, the current error is the following:

```
oliver@oliver-lenmt:~$ streamlink --plugin-dirs ./plugintest --stream-url http://www.mitele.es/directo/cuatro -l debug
error: Unable to open URL: https://mdslivehls-i.akamaihd.net/hls/live/571643/cuatro/master.m3u8?hdnea=st=1515168963~exp=1515168971~acl=/hls/live/571643/cuatro/*~hmac=37df85b3e1ad56b0ae5faa44eef0da147adf6eaed3bb3a39b31369f91464a64f&ogn=NnWVN8fSWTgWTTEP0Hp0QAw7u+8vqVw3m4RzPdOReJUIHafEXVX3oRYjnN9yaty7YSYWFDDpYHyBUqmnxLwPRZGfMGZ5R9ybUNMSvxDxpHs= (403 Client Error: Forbidden for url: https://mdslivehls-i.akamaihd.net/hls/live/571643/cuatro/master.m3u8?hdnea=st=1515168963~exp=1515168971~acl=/hls/live/571643/cuatro/*~hmac=37df85b3e1ad56b0ae5faa44eef0da147adf6eaed3bb3a39b31369f91464a64f&ogn=NnWVN8fSWTgWTTEP0Hp0QAw7u+8vqVw3m4RzPdOReJUIHafEXVX3oRYjnN9yaty7YSYWFDDpYHyBUqmnxLwPRZGfMGZ5R9ybUNMSvxDxpHs=)

```

**Comment by back-to** [comment]
@urnenfeld 
i only know this domain "https://mdslivehls-i.akamaihd.net" 
it's from one of the channels where the full url returns, (i think http://www.mitele.es/directo/energy)

did you test some other channels?

---

if the channel has a different domain and i don't get the domain from the api,
i can't create the real m3u8 url

there should be an error msg `Might not work, only suffix - try to create a url.` in the terminal

---

it would be nice if you could check the not working channels which domain they use.

if you use Firefox, you could press `F12` and go to Network
then oben the url - http://www.mitele.es/directo/cuatro and press play

some of the urls should be a .m3u8 file from akamaihd.net,
i would need this domain if it's different than "https://mdslivehls-i.akamaihd.net"

**Comment by urnenfeld** [comment]
Hello @back-to we are almost there!

The logger functions do not work (despite the *-l debug*), Do you know why? however debugging your code the error prints out around the last loop.

Anyway, your code is **completely OK** for *energy* channel! Then I tried the hostname I mentioned which I got for *cuatro* in your code and works as well!

This patch(of your plugin) made it working for *cuatro* and *energy*:

https://gist.githubusercontent.com/urnenfeld/b1d9787893f285a9eee93b89385156ad/raw/79816345ed0129a68237154a4e04adef9efb6a0a/gistfile1.txt

I don't know the best practices & guidelines in streamlink so this could need rework. I will try to get the other domains(right now other channels are not broadcasting through the web)

**Comment by back-to** [comment]
@urnenfeld 
i updated the gist
https://gist.github.com/back-to/686bd4ae2e70ff263dbd8300db7c5505

just add the domains at the top, i did not test it.

**Comment by urnenfeld** [comment]
@back-to 
Turns out that the *livehlsdai* domain works will **all** channels.
With domain *mdslivehls* the plugin works as well for all channels except *cuatro* and *telecinco*

In any case once the operation works, all channels resolve to a *mdslivehls* URL, except *cuatro* and *telecinco* which resolve to a *livehlsdai* URL. Sort to say:

Channel | Domain livehlsdai|Domain mdslivehls|Resulting URL
------------ | -------------| -------------| -------------|
bemad|ok|ok|mdslivehls
boing|ok|ok|mdslivehls
divinity|ok|ok|mdslivehls
fdf|ok|ok|mdslivehls
energy|ok|ok|mdslivehls
telecinco|ok|nok|livehlsdai
cuatro|ok|nok|livehlsdai

So the setting for all the *livehlsdai* domain will make the plugin functional, but would be cool to have somehow the other domain as backup for the future.

Thanks a lot for your effort!
