### ISSUE TITLE
No such file or directory error when trying to use with QuickTime Player

### ISSUE THREAD

**Issue by ptkovsky** [streamlink/streamlink#1338]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Streamlink doesn't support QuickTime Player? We were talking about launching streams from GUI https://github.com/streamlink/streamlink-twitch-gui/issues/511 and I was told to open an issue since there is one and this has been present here for long time as I was testing this way back earlier too.  

```
streamlink -p "/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player" --player-passthrough hls https://www.twitch.tv/agentjkezoor best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/agentjkezoor
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player
error: Failed to start player: /Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player ([Errno 2] No such file or directory)
```

### Expected / Actual behavior

I can watch streams with any player?

### Comments, logs, screenshots, etc.

Specs and screens and other things irrelevant I guess?

**Comment by beardypig** [comment]
FYI, version information is important - particularly for other people looking at this issue in the future.

I was able to get `streamlink` to start QuickTime by escaping the spaces, eg.
```
streamlink -p "/Applications/QuickTime\ Player.app/Contents/MacOS/QuickTime\ Player" ...
```
However, it did not work playing the stream. Using the following did work, with some warning...
```
streamlink -p "open -a '/Applications/QuickTime Player.app'" ...
```

**Comment by ptkovsky** [comment]
Looks easy. Sorry, didn't think about the importance of version information this way at first. This sounds right. So my testing Streamlink version was 0.8.1 and I was encountering this issue with the previous versions too. Will update to the latest version ASAP btw. I've also tried to escape spaces in GUI but that didn't work either.

Maybe you can you advise here how co configure the GUI? Still having hard time with it... Stream either doesn't start or popup says ENOENT error. Thank you very much for your time here.

Thanks for teaching us the right syntax of this command and also for the help with text formatting in the OP.

**Comment by bastimeyer** [comment]
> Maybe you can you advise here how co configure the GUI?

The suggested workaround doesn't work this way in the Twitch GUI, because it expects a single executable path which gets validated first (is-file and is-executable). You're seeing an ENOENT error (no entity / non-existing file), because it interprets the whole string as a single file. What you can do, is setting the player to "open" (the macOS specific GUI app launcher tool) and use the --player-args parameter, like this:

```bash
streamlink --player "open" --player-args " -W -n -a '/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player' --args '{filename}'" --player-passthrough hls URL QUALITY
```
Notice the space at the beginning of the `--player-args` parameter value or else you'll encounter the error described in #971. `-W` lets `open` wait for the spawned process to exit, which is a requirement here. `-n` lets it always launch a new player instance.

I'm not sure though if this will work, but that's the correct way of preparing the player launch parameters in Streamlink. Unfortunately, I can't test this myself, since I'm unable to watch videos in my macOS VMs because of lack of GPU acceleration.

**Comment by ptkovsky** [comment]
Tested and when entering this in Terminal you get a popup message windows saying that: 
> The document …m3m8 could not be opened. The file does not exist.

but

``
streamlink -p "open -a '/Applications/QuickTime Player.app'" ...
``

still works fine.

Yeah and don't think that the GUI will work with this string either. 😄

**Comment by bastimeyer** [comment]
> m3m8 could not be opened. The file does not exist

Ok, so apparently, Quicktime itself does only accept local files as parameters (what a terrible player, ridiculous). But passing the HLS stream URL to the `open` command is working fine.

Try the following command (no --args inside the --player-args string this time):
```bash
streamlink --player "open" --player-args " -W -n -a 'quicktime player' '{filename}'" --player-passthrough hls URL QUALITY
```

In the Twitch GUI, select `/usr/bin/open` as player and `-W -n -a 'quicktime player' '{filename}'` (with a leading space which Github is removing here) as player params.

I'm referencing the Livestreamer issue from 2014 here in case someone's finding it via a search engine.
https://github.com/chrippa/livestreamer/issues/450

I guess this and the other thread can be closed then?!

**Comment by ptkovsky** [comment]
The result is different this time. Here It just finishes executing the command but player doesn't even start. Any other thoughts?
```
$ streamlink --player "open" --player-args " -W -n -a 'quicktime player' '{filename}'" --player-passthrough hls https://www.twitch.tv/imaqtpie best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/imaqtpie
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: open
$ 
```

**Comment by bastimeyer** [comment]
Then don't just copy and paste the command and instead set the explicit quticktime executable path instead of the shorthand name (which is btw working on my machine).

**Comment by ptkovsky** [comment]
So when `--args` is removed, looks like player starts but nothing happens or it gives errors. Tried mixing stuff in this command and got different results.

Tried this as an example (can have errors):

```
$ streamlink --player "open" --player-args " -W -n -a 'quicktime player' '/Applications/QuickTime Player.app'" --player-passthrough hls https://www.twitch.tv/imaqtpie best
```

Sorry, getting a little bit lost in all of this syntaxing and didn't fully understand the meaning of the part where it says ``'quicktime player' '{filename}'`` (can be seen several ways in different cases) and didn't read carefully so just blind copied the command at first lol.

I've seen the path here being `/Applications/QuickTime Player.app` or `/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player` so that's an option too. Can you try and give exact command please? Because it looks like something is still missing here. Thanks for your support btw yet again. And as I already said, a player preset should be very handy for casual viewers out there!

**Comment by bastimeyer** [comment]
You are doing it wrong... This is the correct way:

```bash
streamlink --player "open" --player-args " -W -n -a '/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player' '{filename}'" --player-passthrough hls URL QUALITY
```

If you don't understand the syntax, then you should read Streamlink's `--player-args` parameter documentation. `{filename}` is the variable that will be replaced with the stream URL when preparing the player parameter line. In the man pages of `open`, you can see that you can also use shorthand names for registered apps. This was working on my system, so I shortened the string, hoping to make it a bit more clear.

What I have posted is working 100%. As I've already explained, the issue with the player arguments I've posted first was that Quicktime does only accept file names as first parameter. Again, if you don't understand the difference between these two command posted by me, read the `open` manual (`man open`).

Before such a player preset you're requesting here can be added to the Twitch GUI, a couple of things need to be changed, because this is using some workarounds. But that's not the right place to discuss here, because it's not the Twitch GUI repo.

I'm closing this thread here now, since the question has been answered and a command line which can be used to watch streams via Streamlink and Quicktime on macOS has been provided.

**Comment by ptkovsky** [comment]
Tried this previously too:
```
$ streamlink --player "open" --player-args " -W -n -a '/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player' '{filename}'" --player-passthrough hls https://www.twitch.tv/imaqtpie best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/imaqtpie
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: open
$
```
In this case player doesn't even start.
> What I have posted is working 100%.

Nope, it's not working on my side at the moment. I've updated to the latest version too. Thanks for the detailed explanations though. Yeah I've read some documentation yesterday like `man open` too. As I said I've also tried setting the path as you used in your recent example earlier by myself an it still doesn't work.

Whatever I put in there doesn't work so I naturally start doubting myself like every other critically thinking person unless the software is bugged or something is missing.

I do understand the point about GUI so will not continue the discussion here. Sorry if somebody was bothered too much. Hope we make things simplier together!

**Comment by beardypig** [comment]
@ptkovsky I too could not get it to work. Which version of macOS are you guys running?

**Comment by ptkovsky** [comment]
Hey @beardypig thanks for taking interest in this issue yet again. It's 10.13.1 for me here atm. Also updated Streamlink to 0.9.0 yesterday after your reminder.

**Comment by beardypig** [comment]
I'm also on 10.13.1 (High Sierra), it only works for me using `-p "open -a 'quicktime player'"` on the command line - I dunno how to get it to work in the GUI though.

**Comment by bastimeyer** [comment]
I have just seen that quoting the `{filename}` variable doesn't work for some reason, so you need to remove that. Sorry about that.
Without the quotes, the command is working absolutely fine on Yosemite. It doesn't seem to be working on Sierra, though, and unfortunately I don't know what is causing this issue.

What I have posted is essentially the same as running
```bash
URL="$(streamlink --stream-url URL QUALITY)"
open -W -n -a "/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player" "${URL}"
```
If you're wondering how the ruby app you've posted in the other thread is launching quicktime, take a look at
https://github.com/jo-sm/twitch/blob/0.3.1/bin/twitch#L210

Remember that when using Streamlink, `--player-passthrough` needs to be set to `hls`. Here is the command again:
```bash
streamlink --player-passthrough hls --player "open" --player-args " -W -n -a '/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player' {filename}" URL QUALITY
```

**Comment by ptkovsky** [comment]
This works fine for me on High Sierra too.

**Comment by adriel** [comment]
Just a heads up, in macOS Catalina QuickTime was moved into /Systems/: `/System/Applications/QuickTime Player.app/Contents/MacOS/QuickTime Player`
