### ISSUE TITLE
Question about how to use API with swf stream.

### ISSUE THREAD

**Issue by dogrocker** [streamlink/streamlink#1339]
### Description

Hello,

I want to use API to download streaming on swf player that setting like this.

```
<object name="player" type="application/x-shockwave-flash" data="/live_player.swf" width="100%" height="100%">
<param name="movie" value="/live_player.swf">
<param name="quality" value="high">
<param name="play" value="true">
<param name="loop" value="true">
<param name="allowScriptAccess" value="sameDomain">
<param name="allowFullScreen" value="true">
<param name="FlashVars" value="ip=localhost&amp;port=7000&amp;name=teststream">
</object>
```

don't know what should I use on `set_option()`.

Thanks for help!

**Comment by zootboy** [comment]
Is this from an actual website? This line:
`<param name="FlashVars" value="ip=localhost&amp;port=7000&amp;name=teststream">`
looks like it should contain the info you need to build the stream's URL, but those values don't make sense.

**Comment by back-to** [comment]
your **data** looks **incomplete**

when you use the search function there are a lot of examples of working plugins 

Closing.

---

**plugins**

https://github.com/streamlink/streamlink/blob/a46c342b0d5db07c376c11d8177bedfbf5b5498f/src/streamlink/plugins/dailymotion.py#L159-L167
https://github.com/streamlink/streamlink/blob/922e169207862ae54f6d7f19d80783a77509866f/src/streamlink/plugins/streamlive.py#L36-L44

you can finde more examples at
https://github.com/streamlink/streamlink/search?utf8=%E2%9C%93&q=RTMPStream%28self.session%2C&type=

---

 **CLI**

https://github.com/streamlink/streamlink/issues/1186#issuecomment-324455010
https://github.com/streamlink/streamlink/issues/640#issuecomment-283290096
https://github.com/streamlink/streamlink/issues/252
https://github.com/streamlink/streamlink/issues/847
