### ISSUE TITLE
Upgrade to 0.9.0-1failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by highflux7** [streamlink/streamlink#1341]
### Checklist

- [x] This is a bug report.

### Description

Trying to upgrade streamlink and python-streamlink from `0.8.1-1~webupd8~xenial0` to `0.9.0-1~webupd8~xenial0` from the repository but am met with unmet dependency:

` python-streamlink : Depends: python-pysocks but it is not installable`

### Expected / Actual behavior

Expected streamlink & streamlink-python to upgrade to 0.9.0-1 without being 'held' because of unmet dependency.

doing an `sudo apt install python-pysocks` returns:

> Package python-pysocks is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-socks

Which one may install of course, but doesn't resolve the depend for streamlink-python.
I do not know where/how one obtains deprecated package python-pysocks for xenial 16.04.

OS  Ubuntu 16.04.03
Python 2.7.12
Streamlink 0.8.1 (`0.8.1-1~webupd8~xenial0`)

**Comment by mmetak** [comment]
Enable the universe repository and try again. In ubuntu xenial the package is `python-socks`?

**Comment by MarcJose** [comment]
Doesn't help at all:
```
> add-apt-repository universe                                                                                                                                                                                 
'universe' distribution component enabled for all sources.
>apt install streamlink 
Some packages could not be installed [...] 
The following information may help you to solve the situation:
The following packages have unresolved dependencies:
 streamlink : Depends on: python-streamlink (= 0.9.0-1~webupd8~xenial0) but should not be installed
E: Problems can not be solved. You have hold back, defect packages.
>apt install python-streamlink
Some packages could not be installed [...] 
The following information may help you to solve the situation:
The following packages have unresolved dependencies:
 python-streamlink : Depends on: python-pysocks but can not be installed
                     Recommends: rtmpdump should not be installed
                     Recommends: python-crypto should not be installed
                     Recommends: python-librtmp should not be installed
E: Problems can not be solved. You have hold back, defect packages.
```

**Comment by mmetak** [comment]
@MarcJose Did you run `apt update` after enabling universe repos?

**Comment by MarcJose** [comment]
Yes, forgot to copy that (had to translate everything first). It doesn't change anything. The python-pysocks package does not exist anymore (it was moved to python-socks).

**Comment by mmetak** [comment]
Maybe @hotice (the maintainer of that ppa) can help?

**Comment by highflux7** [comment]
Why does python-streamlink depend on (old) python-pysocks and not python-socks?

**Comment by scde** [comment]
Hello,

@highflux7 I was just writing the same thing.
I think you are right the [PySocks](https://pypi.python.org/pypi/PySocks)-dependency is using the wrong/old package name.

```
$ apt depends python-streamlink
python-streamlink
  Depends: python-backports-shutil-get-terminal-size
  Depends: python-backports-shutil-which
  Depends: python-concurrent.futures
  Depends: python-cryptodomex
  Depends: python-iso-639
  Depends: python-iso3166
  Depends: <python-pysocks>
  Depends: python-requests
  Depends: python-singledispatch
  Depends: python-websocket
  Depends: <python:any> (<< 2.8)
    python:i386
    python
  Depends: <python:any> (>= 2.7.5-5~)
    python:i386
    python
  Recommends: rtmpdump
  Recommends: python-crypto
  Recommends: python-librtmp
  Recommends: ffmpeg
    ffmpeg:i386
  Suggests: streamlink
```

The one in there (`python-pysocks`) was apparently [deleted](https://launchpad.net/ubuntu/xenial/amd64/python-pysocks).

>  Removal requested on 2016-01-11.
>
> Deleted on 2016-01-11 by Colin Watson
> 
> (From Debian) ROM; Duplicate package of python-socksipy incorrectly introduced into the archive; Debian bug #810306

[This one](https://launchpad.net/ubuntu/xenial/amd64/python-socks) looks like the correct one. And it is the one I actually find on the system.

```
$ apt search python pysocks
Sorting... Done
Full Text Search... Done
python-socks/xenial,xenial 1.5.0+dfsg-4 all
  Python 2 SOCKS client module

python3-socks/xenial,xenial 1.5.0+dfsg-4 all
  Python 3 SOCKS client module
```

**Comment by scde** [comment]
It looks to be fixed now. The dependency is now `python-socks`. Thanks @hotice.

```
$ apt depends python-streamlink
python-streamlink
  Depends: python-requests
  Depends: <python:any> (>= 2.7.5-5~)
    python:i386
    python
  Depends: python-concurrent.futures
  Depends: <python:any> (<< 2.8)
    python:i386
    python
  Depends: python-backports-shutil-which
  Depends: python-singledispatch
  Depends: python-backports-shutil-get-terminal-size
  Depends: python-cryptodomex
  Depends: python-iso-639
  Depends: python-iso3166
  Depends: python-websocket
  Depends: python-socks
  Recommends: rtmpdump
  Recommends: python-crypto
  Recommends: python-librtmp
  Recommends: ffmpeg
    ffmpeg:i386
  Suggests: streamlink
```

It installed correctly for me and is working. I think this can be closed.
