### ISSUE TITLE
Streamlink only working if I pass --verbose-player

### ISSUE THREAD

**Issue by HASJ** [streamlink/streamlink#1342]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

About a week ago Streamlink stopped working. I can not pinpoint the cause.
However, it DOES work normally if I give this command
`streamlink -v https://www.twitch.tv/videos/202880325 best`
Discovered this workaround 3 minutes ago.

### Expected / Actual behavior

Expected: For the stream to play normally.

Reality:
```
streamlink https://www.twitch.tv/videos/202880325 best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/202880325
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
Traceback (most recent call last):
  File "C:\Users\Dudu\AppData\Local\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Users\Dudu\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1047, in main
    handle_url()
  File "C:\Users\Dudu\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 506, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Users\Dudu\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 379, in handle_stream
    success = output_stream_passthrough(stream)
  File "C:\Users\Dudu\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 206, in output_stream_passthrough
    quiet=not args.verbose_player)
  File "C:\Users\Dudu\AppData\Local\Streamlink\pkgs\streamlink_cli\output.py", line 91, in __init__
    self.stdout = open(os.devnull, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'nul'
```

### Reproduction steps / Explicit stream URLs to test

1. Start streamlink
2. Wait for stream to start
3. It fails

### Environment details

Operating system and version: Windows 10 Pro v10.0.16299.64
Streamlink and Python version: Streamlink v0.9.0 (and 0.8.1) and Python v3.6.3

...

### Comments, logs, screenshots, etc.

Weirdly enough, `refreshenv`, a powershell script installed with Chocolatey (what I used to install streamlink), has stopped working. It is a tool to refresh the environment variables within the cmd without the need for restarting, which makes me think something in the environment vars got broken, since it returns me a bunch of "file not found" errors and seems to be what is plaguing streamlink.

Just a thought.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This definitely looks like a local configuration issue to me based on the error, and likely some sort of environment variable that refreshenv and other tools depend on. You could try running `refreshenv` from within whatever directory it resides in instead of just the shell to see if it can fix things, but there isn't much we're going to be able to assist with here unfortunately as Streamlink itself is fine.

**Comment by beardypig** [comment]
@HASJ are you running `streamlink` in powershell? If so, have you tried with regular old cmd?

**Comment by HASJ** [comment]
@beardypig It was ran from the cmd. Neither works.

**Comment by back-to** [comment]
this is a **windows issue**

try this
http://grasswiki.osgeo.org/wiki/WinGRASS_errors#The_startup_fails_with_a_IOerror:_.5BErrno_2.5D_No_such_file_or_directory_:_.27nul.27

---

chrippa/livestreamer#674
jupyter/notebook#2651
