### ISSUE TITLE
New Twitch API coming

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#1346]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Twitch API v5 is ending at the end of next year.  The new Twitch API is documented here https://dev.twitch.tv/docs/api    Might be a good idea to start testing it with Streamlink
...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Did we not already resolve this to a satisfactory point here: https://github.com/streamlink/streamlink/issues/377 via https://github.com/streamlink/streamlink/pull/484?

**Comment by bastimeyer** [comment]
No, Twitch has introduced a completely new API and already deprecated their stable one. Their new one hasn't even been finished and lacks several, if not almost all currently available endpoints, which is a very bad move by them. This was one or two months ago, maybe something has changed since then, all I know is that many devs were upset about these changes, including me. There's also rate limiting been added, so this might become an issue. My advice is to wait a few more weeks until things have stabilized. As @thinkpad4 already said, the current API (v5) is still supported until the end of 2018, so there's no need to rush.

**Comment by gravyboat** [comment]
@bastimeyer Whoops I misread it as 5 was becoming the primary, thanks for the clarification. I agree let's wait and see what they do. I really don't understand why they are rebuilding their API so often.

**Comment by bastimeyer** [comment]
It's October now. The v5 API will be shut down in 3 months. We should start thinking about migrating to the new API.

Technically, there shouldn't be too much of a difference, but the new API is still rate-limited by 120 requests per minute per application.
https://dev.twitch.tv/docs/api/guide/#rate-limits

This is definitely an issue for Streamlink and we will have to ask them to increase this limit. I will have to do the same for the Twitch GUI, which is using its own application client-id and also passes this ID to Streamlink, so it's an independent case.

You can file such a request here:
https://dev.twitch.tv/limit-increase/
I'm not sure though if Streamlink is an application which is "suitable" for this, as it's obviously not in their interest to support applications which bypass ads.

In case our request will be declined, we will have to add instructions to the docs and possibly even implement a notice into Streamlink itself on how one can register their own application on Twitch and use its generated client-id.

**Comment by gravyboat** [comment]
Thanks for getting the ball rolling here @bastimeyer.

Here's my plan for what to put in the limit increase at https://dev.twitch.tv/limit-increase/ for Streamlink:

```
Full Name: Streamlink Team

Email: streamlink email (redacted here to avoid bots but it's the one a few of us have access to)

Application Name: Streamlink

Service Request: API Request Rate

Detailed Description of your Application: Streamlink allows users to watch a stream directly on their computer via a local video player, allowing users with systems that cannot support the Twitch website or with limited bandwith to enjoy Twitch.

Client ID: Our client ID

New limit being requested: 10k requests per minute (I think this might be a bit high but without data from them we have no idea what the actual value is).
```

Thoughts on this as the request? My only real concern is the limit value which I feel like is pretty high, but during big events we have no idea how our user base is using the application, and we have at least 20k users at this point, so I'd rather ask high than too low.

**Comment by bastimeyer** [comment]
> My only real concern is the limit value

Yeah...

> we have at least 20k users at this point

The latest release of the Twitch GUI has been downloaded 36000 times from GitHub alone already, not including 3rd party builds.

```bash
$ curl -s 'https://api.github.com/repos/streamlink/streamlink-twitch-gui/releases/latest' | jq '.assets | map(.download_count) | add'
35955
```

The entire Streamlink user base is much higher than that. Users for all kinds of sites/plugins, of course.
```bash
$ curl -s 'https://api.github.com/repos/streamlink/streamlink/releases/latest' | jq '.assets | map(.download_count) | add'
31525
```
And that's just the latest stable release for Windows.

**Comment by gravyboat** [comment]
Yeah I didn't look at the latest stable, looks like numbers are higher since it's been a while since we released, yeesh. Since it's per minute maybe we should ask for 20k? 10k seems like it might not be enough.

**Comment by bastimeyer** [comment]
So it looks like Twitch has changed plans recently and v5 will be kept alive for now. I didn't notice that in the docs.
https://dev.twitch.tv/docs/v5/

This means that the plugin doesn't have to be changed for now. Regarding the request limits, these are only meant for the new `/helix` API namespace.

**Comment by back-to** [comment]
closing, as there will be probably a new issue when it breaks.

not worth to have this open yet.
