### ISSUE TITLE
Drop support for EOL Python 3.3

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1348]
### Checklist

- [x] This is a bug report.

### Description

**pytest** dropped support for python 3.3 pytest-dev/py#165

**appveyor** builds are failing because of that streamlink/streamlink#1345

https://ci.appveyor.com/project/beardypig/streamlink-4m1xi/build/1.0.1191

---

[Python 3.3.x has reached end-of-life.](https://www.python.org/downloads/release/python-337/) (2017-09-29)

maybe drop 3.3 support for **streamlink** aswell

**Comment by hugovk** [comment]
Drop it.

Here's the pip installs for streamlink from PyPI for the last month (via `pypinfo --percent --pip streamlink pyversion`), showing no Python 3.3.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   59.1% |          1,095 |
| 3.6            |   26.9% |            498 |
| 3.5            |    8.8% |            163 |
| 3.4            |    4.7% |             87 |
| 2.6            |    0.5% |             10 |
| 3.7            |    0.1% |              1 |
