### ISSUE TITLE
Plugin Request: 1tv.ru

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#1352]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Russia's main television channel

https://www.1tv.ru/live

**Comment by gravyboat** [comment]
If you can provide any additional details about what a request looks like that would be great. I'm not going to get a Russian proxy to check out this site.

**Comment by roshavagarga** [comment]
I can help out with information about this plugin request if it can be reopened @gravyboat

**Comment by gravyboat** [comment]
@roshavagarga Sure, is the content on this site legal? I don't speak Russian or have familiarity with video there.

**Comment by roshavagarga** [comment]
@gravyboat The content is legal but as far as I've seen, some of the content gets blocked as Russia-only, while other content doesn't. This is basically the main national tv station for the whole country.
They're using tokens as far as I can see for that. I don't really know Russian either, but Bulgarian is close enough as far as languages get.

**Comment by beardypig** [comment]
Looks legit, based on wikipedia anyway :)

**Comment by gravyboat** [comment]
Closing since #1687 was merged.
