### ISSUE TITLE
Plugin request flirt4free (nsfw)

### ISSUE THREAD

**Issue by Polizo** [streamlink/streamlink#1357]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Plugin to 
www.flirt4free.com

### Expected / Actual behavior

EXAMPLE:

https://www.flirt4free.com/rooms/baylee-moon/

https://manifest.vscdns.com/chunklist.m3u8?model_id=811981&host=wowza004.rs-tx.vs3.com&provider=edgecast&secure=true

https://ec-wowza004-rs-tx.vscdns.com/liveEgress/811981-wowza004.rs-tx.vs3.com.f4v/811981-wowza004.rs-tx.vs3.com.f4v/media-u0ydf8pwh_1467.ts

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I'll note that I'm really against adding any more cam sites. The users we get from these types of plugins are typically very demanding and extremely entitled/rude (not to say that you fall into that category Polizo).

**Comment by RosadinTV** [comment]
🤣

![simspons - computer guy](https://user-images.githubusercontent.com/13382316/33624725-0a2d253e-d9d4-11e7-8405-36b3170e4884.png)

**Comment by Polizo** [comment]
@gravyboat Ummm im sorry if you didnt like this plugins, i know that the streamlink was not created to see cam sites but is other use. Sorry if i demand so much. if anybody want to built the plugin its no problem. Thanks for your work. streamlink is awesome :)

**Comment by gravyboat** [comment]
@Polizo It's nothing against you at all! We've just been getting a lot of requests for NSFW sites recently and some of the people asking for them have been less than polite. Sorry if my response came off sounding rude.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 5 - NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
