### ISSUE TITLE
[QUESTION] Install Streamlink in QNAP NAS with "virtualenv"

### ISSUE THREAD

**Issue by nickiman** [streamlink/streamlink#1358]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Trying to install Streamlinks in a QNAP NAS with [Python 2.7](https://qnapclub.eu/index.php?act=detail&qpkg_id=259)

### Expected / Actual behavior

These are the steps followed:
```
mkdir /share/CACHEDEV1_DATA/.qpkg/Streamlink
./pip install virtualenv
```
Collecting virtualenv
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 356kB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-15.1.0
`./virtualenv /share/CACHEDEV1_DATA/.qpkg/Streamlink`
New python executable in /share/CACHEDEV1_DATA/.qpkg/Streamlink/bin/python2.7
Also creating executable in /share/CACHEDEV1_DATA/.qpkg/Streamlink/bin/python
Installing setuptools, pip, wheel...done.
`source /share/CACHEDEV1_DATA/.qpkg/Streamlink/bin/activate`
(Streamlink) [/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] #
```
cd /share/CACHEDEV1_DATA/.qpkg/Streamlink
pip install streamlink
```
Here the output of of the command: https://pastebin.com/Qc5gXULX

Since I don´t like the latest message about pycryptodome... I try to install it in Python´s NAS.
```
(Streamlink) [/share/CACHEDEV1_DATA/.qpkg/Streamlink] # deactivate
cd /share/CACHEDEV1_DATA/.qpkg/QPython2/bin
./pip install pycryptodome
```

And here is the output of the above command: https://pastebin.com/VSLTbfsb
It´s very similar to the previous one... so... I haven´t tested yet but,  I´m afraid that streamlink can´t be work normally.

Can someone give me a clue?

### Environment details

Operating system and version: 
NAS Firmware:
uname -a = Linux NAS 4.2.8 #1 SMP Fri Nov 17 01:08:55 CST 2017 x86_64 GNU/Linux
QTS version: 4.3.3.0378 (17/11/2017)
Streamlink and Python version:
Streamlink = **How to get the Streamlink version?????**
Python 2.7.14 (default, Oct  3 2017, 10:00:25)
[GCC 4.9.2] on linux2

My intention is use streamlink in combination with ffmpeg as stated here:
https://tvheadend.org/boards/5/topics/15853?r=16260#message-16260

Not sure if this will work with the errors in the pastebin links so, I would like some advices in order to make a clean installation.

Thank you and best regards.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
To install `pycryptodome` you need to compile some C extensions, to compile the C extensions you need a C compiler. 

I'm not expert but it looks like you need to use `ipkg` to install GCC and possibly the Python headers? Are you using `ipkg`?

**Comment by nickiman** [comment]
Hi,
I haven´t compiled Python. I´m using a Python package compiled for an user in the QNAP forum.
I don´t have the knowledge to compile it. Is there any way to bypass that? Maybe using pycrypto?
Best regards

**Comment by back-to** [comment]
If `pycrypto` works with QNAP, you can use it. @nickiman 

```sh
export STREAMLINK_USE_PYCRYPTO="true"
```

https://streamlink.github.io/install.html#using-pycrypto-and-pycountry

**Comment by nickiman** [comment]
Thanks @back-to and @beardypig for your suggestions/assistance
Let me detail what I´ve done till now...
Since it was impossible to run the virtual environment I´ve decided to install streamlink **directly in the QNAP´s OS** without any virtual environment running. These are the steps followed:

`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install pycrypto`
Requirement already satisfied: pycrypto in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages
`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install pycountry`
Collecting pycountry
Downloading pycountry-17.9.23.tar.gz (9.2MB)
    100% |████████████████████████████████| 9.2MB 71kB/s
Building wheels for collected packages: pycountry
  Running setup.py bdist_wheel for pycountry ... done
  Stored in directory: /root/.cache/pip/wheels/95/45/76/aa36bb308428b450eb1f51955b0f26911f00df3c85602c1da8
Successfully built pycountry
Installing collected packages: pycountry
Successfully installed pycountry-17.9.23

`$ export STREAMLINK_USE_PYCRYPTO="true"`
`$ export STREAMLINK_USE_PYCOUNTRY="true"`

`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install streamlink`

> Collecting streamlink
> Requirement already satisfied: backports.shutil-get-terminal-size in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/backports.shutil_get_terminal_size-1.0.0-py2.7.egg (from streamlink)
> Requirement already satisfied: backports.shutil-which in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/backports.shutil_which-3.5.1-py2.7.egg (from streamlink)
> Requirement already satisfied: pycrypto in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/PySocks-1.6.7-py2.7.egg (from streamlink)
> Requirement already satisfied: futures in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: pycountry in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: singledispatch in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: websocket-client in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from streamlink)
> Requirement already satisfied: six in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from singledispatch->streamlink)
> Requirement already satisfied: idna<2.7,>=2.5 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
> Requirement already satisfied: urllib3<1.23,>=1.21.1 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
> Requirement already satisfied: certifi>=2017.4.17 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from requests!=2.12.0,!=2.12.1,!=2.16.0,!=2.16.1,!=2.16.2,!=2.16.3,!=2.16.4,!=2.16.5,!=2.17.1,<3.0,>=2.2->streamlink)
> Requirement already satisfied: backports.ssl_match_hostname in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages (from websocket-client->streamlink)
> Installing collected packages: streamlink
> Successfully installed streamlink-0.9.0

Since is finishing saying ""Successfully installed streamlink-0.9.0""... I try to run streamlink:
`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./streamlink`
Traceback (most recent call last):
  File "./streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/main.py", line 14, in <module>
    from streamlink import (Streamlink, StreamError, PluginError,
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/__init__.py", line 83, in <module>
    from .api import streams
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/session.py", line 7, in <module>
    from streamlink.utils import update_scheme
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/utils/__init__.py", line 10, in <module>
    from streamlink.compat import urljoin, urlparse, parse_qsl, is_py2, urlunparse
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/compat.py", line 45, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which

Here starts the problems... I´ve installed these modules to try to solve the error.
`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install shutilwhich`
Collecting shutilwhich
  Downloading shutilwhich-1.1.0.tar.gz
Building wheels for collected packages: shutilwhich
  Running setup.py bdist_wheel for shutilwhich ... done
  Stored in directory: /root/.cache/pip/wheels/0e/28/70/d5cc6586f26d614b26901485f6f6072d35cbbb5bbeffb6ea43
Successfully built shutilwhich
Installing collected packages: shutilwhich
Successfully installed shutilwhich-1.1.0
`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install backports.shutil_which`
Requirement already satisfied: backports.shutil_which in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/backports.shutil_which-3.5.1-py2.7.egg

Even installing these two last modules... I´m getting the same error:
`[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./streamlink`
Traceback (most recent call last):
  File "./streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/main.py", line 14, in <module>
    from streamlink import (Streamlink, StreamError, PluginError,
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/__init__.py", line 83, in <module>
    from .api import streams
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/session.py", line 7, in <module>
    from streamlink.utils import update_scheme
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/utils/__init__.py", line 10, in <module>
    from streamlink.compat import urljoin, urlparse, parse_qsl, is_py2, urlunparse
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink/compat.py", line 45, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which

I'm completely stuck and I don't know how to go on with this... Could you please help me?

**Comment by back-to** [comment]
@nickiman 

I had some similar errors with Kodi on Android,
where it won't read the name `backports.shutil_which` i had to rename it.

---

But you could try to use `shutilwhich` instead of `backports.shutil_which`

change in `/opt/QPython2/lib/python2.7/site-packages/streamlink/compat.py`

https://github.com/streamlink/streamlink/blob/master/src/streamlink/compat.py#L42-L45

to

```py
try:
    from shutil import which
except ImportError:
    try:
        from backports.shutil_which import which
    except ImportError:
        from shutilwhich import which
```

**Comment by nickiman** [comment]
thanks @back-to I´ve made that changes in compat.py file running in this path:
/share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/streamlink

And now, that error message doesn´t appear anymore. This is the output when I run streamlink:
[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./streamlink
Traceback (most recent call last):
  File "./streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/main.py", line 20, in <module>
    from .argparser import parser
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/argparser.py", line 6, in <module>
    from .constants import (
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/constants.py", line 5, in <module>
    from .compat import is_win32
  File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/compat.py", line 15, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size

Next problem comes with the following message referring to also to compat.py file...
  **File "/opt/QPython2/lib/python2.7/site-packages/streamlink_cli/compat.py", line 15, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size**

I´ve tried to fix it in the same way as with the previous error...
[/share/CACHEDEV1_DATA/.qpkg/QPython2/bin] # ./pip install backports.shutil_get_terminal_size
Requirement already satisfied: backports.shutil_get_terminal_size in /share/CACHEDEV1_DATA/.qpkg/QPython2/lib/python2.7/site-packages/backports.shutil_get_terminal_size-1.0.0-py2.7.egg

But this time I can´t see any line in compat.py file referring about backports.shutil_get_terminal_size

May I have to add manually in it? I´ve tried to add this in compat.py:
`    try:
        from shutil_get_terminal_size import get_terminal_size
    except ImportError:
        from backports.shutil_get_terminal_size import get_terminal_size
    except ImportError:
        from shutil_get_terminal_size import get_terminal_size`

But still getting the same error...

**Comment by back-to** [comment]
@nickiman 

try:

```
pip install --upgrade setuptools pip

pip uninstall backports.shutil_get_terminal_size
pip install backports.shutil_get_terminal_size

pip uninstall backports.shutil_which
pip install backports.shutil_which
```
you can find other solutions in

https://github.com/ipython/ipython/issues/9656
https://github.com/chrippa/backports.shutil_get_terminal_size/issues/9

or if this doesn't work use **python3**

**Comment by nickiman** [comment]
@back-to thank you!!

That was the trick... I´ve followed your steps indicated and now, it works.

I´ll take note of this changes for future reference.

Again, thanks for your assistance.

**Comment by nickiman** [comment]
Hi again,
I´m having the need of use ffmpeg together with streamlink in order to remux some streams and use them in tvheadend.
I´ve been reading this issue #481 but, I haven´t find any file called **streamlinkrc** in my setup. 
Since my ffmpeg install it´s in this path: 
/share/CACHEDEV1_DATA/.qpkg/Qffmpeg/bin

How should I configure this path in streamlink to invoke always this binary?

**Comment by back-to** [comment]
@nickiman 
https://streamlink.github.io/cli.html#configuration-file
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg
