### ISSUE TITLE
Plugin Request: 720pstream.me

### ISSUE THREAD

**Issue by PickleJr** [streamlink/streamlink#1361]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

720pstream.me is a site that provides HD streams of American Professional Sports. Specifically, NHL, NBA, NFL, MLB, and some MMA streams. I think it would be cool if a plugin could be made for this site.

### Reproduction steps / Explicit stream URLs to test

1. http://www.720pstream.me/nfl-network-24/7-stream
2. http://www.720pstream.me/mlb-network-24/7-stream
3. http://www.720pstream.me/nba-tv-24/7-stream

**Comment by PickleJr** [comment]
I am not sure if this helps, but in each page that has a video, there is a script tag that has a "getVURL()" function that is declared, that returns the video's m3u8 file.

**Comment by gravyboat** [comment]
If these are restreams of paid services or sports matches you would need to pay to watch via we aren't going to be able to support it.

**Comment by PickleJr** [comment]
Shucks, I figured it was worth a shot. I'll see if I can figure out a workaround by myself. Thanks for the reply!

**Comment by gravyboat** [comment]
No problem, sorry I don't have a better answer, it's just too risky a gray area for us to participate in since what that site is doing is illegal and we want to avoid adding any plugins that could get us in trouble.
