### ISSUE TITLE
catch a simple bug of handling url

### ISSUE THREAD

**Issue by ctrngk** [streamlink/streamlink#1364]
### Checklist

- [x] This is a bug report.

### Description

catch a simple bug of returning url.  

### Version
streamlink 0.9.0

### Unexpected behavior
for example
```sh
streamlink http://www.huya.com/1547946968 "best"
```
it reports:
requests.exceptions.MissingSchema: Invalid URL '//ws.streamhls.huya.com/huyalive/30765679-2523417567-10837995924416888832-2789253832-10057-A-1512526581-1_1200/playlist.m3u8': No schema supplied. Perhaps you meant http:////ws.streamhls.huya.com/huyalive/30765679-2523417567-10837995924416888832-2789253832-10057-A-1512526581-1_1200/playlist.m3u8?

### Expected behavior
but if you replace with the m3u8 url above, by **removing // header**, it will work.
The equivalent successful example are as follows:
```sh
streamlink ws.streamhls.huya.com/huyalive/30765679-2523417567-10837995924416888832-2789253832-10057-A-1512526581-1_1200/playlist.m3u8 "best"
```

**Comment by gravyboat** [comment]
Thanks for the report, a PR has been merged which resolves this and will be available in the nightly build and next major release.
