### ISSUE TITLE
[Plugin Request] RTBF channels

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#1367]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

hello thank you for this great tool.
Please add support for rtbf channels located here https://www.rtbf.be/auvio/direct/ if it possible 

### Environment details

Operating system and version: Linux YS 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 i686 i686 i686 GNU/Linux
Streamlink and Python version: streamlink 0.9.0 / Python 3.5.2

**Comment by karlo2105** [comment]
If you don't fill in accurately template you shouldn't expect request to be fulfilled.

**Comment by BZHDeveloper** [comment]
don't forget that RTBF geo-blocks its videos (available in Brussels, not in Paris)
