### ISSUE TITLE
FirstOneTv. [Plugin request]

### ISSUE THREAD

**Issue by Ordval** [streamlink/streamlink#1369]
- [x] This is a plugin request.
- [x] I have read the contribution guidelines.

> @beardypig is it possible for a plugin for [firstonetv.net](https://www.firstonetv.net/Live) ?   cirrusUK commented on 11 Oct    #1187
<img width="1162" alt="i second that-a-notion - mindre" src="https://user-images.githubusercontent.com/8399361/33809234-f1e73ac2-ddf3-11e7-960e-f96f06823fe7.png">
but of course to anyone who is willing.  
         
Operating system: Windows 10 Home, ver.: 10.0.14393 Build 14393
Streamlink version: 0.9.0

**Comment by gravyboat** [comment]
This one is a definite no go for adding. It's just a ton of stolen content and restreams.

**Comment by Ordval** [comment]
Pity. I trust you ought to know, I have NO such knowledge.

**Comment by gravyboat** [comment]
@Ordval Are there any legit streams on that site? When I went to view US streams the first three were ESPN, CBS, and some other huge broadcasting company.

**Comment by Ordval** [comment]
I knew you were gonna go there, No, I totally agree!
but to make it short, I hope all this piracy business 
will make the owners (for lack of the proper term) to do 
what they should have started working towards already 
20 years ago; make something more on/ to the consumers term. 

Now, in Sweden it's just - 'Here's a bunch of channels: 
lik-ey, lik-ey ? to the pric-ey pric-ey ?'
 
Anyone who has followed how "Discovery" is managing it all 
in Sweden would know. 

If we're going to discuss what's legal or not where really 
entangling ourselves in a snake's nest, we could just go on and on 
with this... but if this would be more illegal than all other 
alternatives, I couldn't say,   
but no, just in case, I don't believe all should be free .
