### ISSUE TITLE
Douyu Client error 403 after 1hour +

### ISSUE THREAD

**Issue by fabiommc** [streamlink/streamlink#1370]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Douyu streams links are expiring i believe and that gives 403 client error or it can be related to something else too
...

### Expected / Actual behavior

Not expiring stream.

### Reproduction steps / Explicit stream URLs to test

1. .Start Douyu Stream
2. Wait 1h + 
3. Stream stops and the error appears

### Environment details

Operating system and version: Win10
Streamlink and Python version: 0.9.0 , Python 3.6.1

### Comments, logs, screenshots, etc.

Printscreen. https://i.imgur.com/8J96NjG.png

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by fozzysec** [comment]
Try to use source_http instead of hls for douyu.com, the http stream doesn't have such a problem.

**Comment by eleeeeeee** [comment]
hi,the problem that Douyu Client error after 1hour+  are solved?

**Comment by fozzysec** [comment]
@eleeeeeee Please try to use the `source_http` stream instead of `hls`. The hls stream expires after 1 hour. Just add `source_http` before other stream options for `default-stream` in your .streamlinkrc file to make it easy to use. Or try to run from terminal like
```
streamlink https://www.douyu.com/nado source_http -p mpv
```
