### ISSUE TITLE
TV3Play has changed domain to Viafree

### ISSUE THREAD

**Issue by eublem** [streamlink/streamlink#1376]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

TV3Play has changed their domain and probably API, so the plugin doesn't work.

(VIASAT Plugin)

**Comment by karlo2105** [comment]
If you want developers fix you should provide further details in template.

**Comment by eublem** [comment]
Viafree has quit adding the ID into the URL, making the plugin unable to find the correct video.

So a temporary fix is to check the thumbnail picture URL and copy its ID (6 integers), which is the same as the video. And add the video ID at the end.

EXAMPLE
**Original URL:**
https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1
**Thumbnail:**
https://playapi.mtgx.tv/imagecache/240x135-retina,lowquality/cloud/content-images/seasons/16372/**822763**/5cda7a5119f8919363666fc3dd097c64-llSqK5R.jpg
**Working Streamlink URL's** (doesn't actually work in the browser)**:**
https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1/822763
or
https://www.viafree.no/programmer/822763

**Comment by back-to** [comment]
duplicat of https://github.com/streamlink/streamlink/issues/727

https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/822763
is the working url in streamlink and browser
