### ISSUE TITLE
[QUESTION] Getting proper access token from Twitch

### ISSUE THREAD

**Issue by omenofdefeat** [streamlink/streamlink#1379]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x ] I have read the contribution guidelines.

### Description
Hi I was wondering if I could ask for some info from the people who did the work on the twitch plugin. I am kind of trying to make my own project that as part has pulling stream feed from Twitch into an m3u8 playlist but I cannot get a proper access token. I suspect because for some reason my token has user_id: null and device_id: null as JSON output. You don't seem to be passing any special arguments around https://github.com/streamlink/streamlink/blob/d6f1ce2ed7fb69f12d41bef234e999e316a614b1/src/streamlink/plugins/twitch.py#L238

and yet your access token works! I really need it otherwise usher.ttvnw doesnt work :/

Thank you!

(Sorry if somewhat off-topic)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Did you register your app with Twitch as noted here: https://dev.twitch.tv/docs/authentication?

**Comment by omenofdefeat** [comment]
Yup I have, the issue still persists :/ 

I get this as my JSON:
`Trying to get access token...
Our access token:  {"adblock":false,"player_type":"site","platform":"web","user_id":null,"channel":"lirik","channel_id":23161357,"expires":1513382414,"chansub":{"view_until":1924905600,"restricted_bitrates":[]},"private":{"allowed_to_view":true},"privileged":false,"https_required":false,"show_ads":true,"device_id":null,"turbo":false,"subscriber":false,"hide_ads":false,"partner":true,"game":"talk_shows","mature":false,"ci_gb":false}
Our playlist: undefined
`
and only after messing with URL parameters (there is more nulls without it). I then of course get `Bad auth token` errors from usher :/

Thank you for the speedy reply!

**Comment by back-to** [comment]
@omenofdefeat 

the **streamlink token** and your token are **the same**

only `"player_type": "site",  "platform": "web",` are different on your side

_**you are properly missing other params**_

sideload the twitch plugin in streamlink and add some **print**s to see what you are doing wrong or what you are missing.

```json
{
    "adblock": false,
    "player_type": null,
    "platform": null,
    "user_id": null,
    "channel": "itshafu",
    "channel_id": 30777889,
    "expires": 123123123,
    "chansub": {
        "view_until": 123123123,
        "restricted_bitrates": []
    },
    "private": {
        "allowed_to_view": true
    },
    "privileged": false,
    "https_required": false,
    "show_ads": true,
    "device_id": null,
    "turbo": false,
    "subscriber": false,
    "hide_ads": false,
    "partner": true,
    "game": "hearthstone",
    "mature": false,
    "ci_gb": false
}
```

**Comment by back-to** [comment]
_not streamlink related_
