### ISSUE TITLE
canalplus plugin no longer works

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#1381]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
since a few days the link to watch the live canalplus has changed so the plugin no longer works.
before: http://www.canalplus.fr/pid3580-live-tv-clair.html
now:     https://www.mycanal.fr/live/

### Expected / Actual behavior

Thank you so if it is possible to correct the plugin taking into account this change.

### Reproduction steps / Explicit stream URLs to test

1. streamlink -v -p mpv http://www.canalplus.fr/pid3580-live-tv-clair.html best
2. [cli][info] Found matching plugin canalplus for URL http://www.canalplus.fr/pid3580-live-tv-clair.html
error: No playable streams found on this URL: http://www.canalplus.fr/pid3580-live-tv-clair.html

### Environment details

Operating system and version: GNU/linux i386 Ubuntu 16.04 LTS
Streamlink and Python version: streamlink 9.0 / python 3.5

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
#1378

**Comment by bastimeyer** [comment]
Closing, since #1378 has been merged...
