### ISSUE TITLE
Can not execute streamlink with crontab

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#1382]
I added this crontab line to start a streamlink script at boot:
@reboot /bin/sh /home/TheSneakySniper/streamlinkscript.sh > /dev/null 2>&1

but instead of executing streamlink at login it tells me it can't find the streamlink command.

`/home/TheSneakySniper/streamlinkscript.sh: 6: /home/TheSneakySniper/streamlinkscript.sh: streamlink: not found

`
Any ideas as to why this is happening?

 OS: Ubuntu 16.04 xenial
Bash version 4.3

**Comment by fozzysec** [comment]
Make sure streamlink is in your $PATH or use absolute path(`/usr/local/bin/streamlink`) for me in your .sh script.

**Comment by TheSneakySniper** [comment]
Thanks fozzy!
