### ISSUE TITLE
Help to get the stream of Canal Parlamento

### ISSUE THREAD

**Issue by nickiman** [streamlink/streamlink#1385]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hi,
Could you please help me to get the video stream of this page?
http://www.congreso.es/portal/page/portal/Congreso/Congreso/CongresoTV/CanPar

### Actual behavior
I´ve tried several methods to get the stream without success:
`./streamlink -l debug --stream-url http://www.congreso.es/portal/page/portal/Congreso/Congreso/CongresoTV/CanPar`

> error: No plugin can handle URL: http://www.congreso.es/portal/page/portal/Congreso/Congreso/CongresoTV/CanPar

`./streamlink -l debug --stream-url hds://www.congreso.es/portal/page/portal/Congreso/Congreso/CongresoTV/CanPar`

> error: Unable to parse manifest XML: mismatched tag: line 254, column 2 ('<!DOCTYPE HTML PUBLIC "-//W3C//DTD ...)

### Environment details

Operating system and version: **QNAP NAS QTS 4.3.3.0404 Build 20171213**
uname -a
Linux -- 4.2.8 #1 SMP Wed Dec 13 01:08:09 CST 2017 x86_64 GNU/Linux

Streamlink and Python version:
./streamlink -V
streamlink 0.9.0
./python2
Python 2.7.14 (default, Oct  3 2017, 10:00:25)
[GCC 4.9.2] on linux2

If you need anything else apart of this don´t hesitate to tell me.

Thank you and best regards.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnpolite** [comment]
http://congresodirecto-f.akamaihd.net/z/congreso6_1@54665/manifest.f4m?hdcore=2.10.3&g=TEHQXGKBIFLE

[url=https://postimg.org/image/prq38bq0z/][img]https://s13.postimg.org/prq38bq0z/Screen_Shot.jpg[/img][/url]

**Comment by johnpolite** [comment]
http://congresodirecto-f.akamaihd.net/z/congreso6_1@54665/manifest.f4m

http://congresodirecto-f.akamaihd.net/i/congreso6_1@54665/master.m3u8

#EXTM3U

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1319000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"

http://congresodirecto-f.akamaihd.net/i/congreso6_1@54665/index_600_av-p.m3u8?sd=10&rebase=on

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1304000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2
"
http://congresodirecto-f.akamaihd.net/i/congreso6_1@54665/index_600_av-b.m3u8?sd=10&rebase=on

**Comment by nickiman** [comment]
Hi @johnpolite, first of all thank you very much for your posts. 
> http://congresodirecto-f.akamaihd.net/z/congreso6_1@54665/manifest.f4m?hdcore=2.10.3&g=TEHQXGKBIFLE

OK,  now I´m aware that the URL above is the produced when the streams starts for the first time.

I´m newbie with streamlink and I would like to learn about it so I have some questions...
What do you do with this URL?

> http://congresodirecto-f.akamaihd.net/z/congreso6_1@54665/manifest.f4m

And the most important... How did you get this URL?

> http://congresodirecto-f.akamaihd.net/i/congreso6_1@54665/master.m3u8

Could you please explain me to learn and understand it?
Thanks again and best regards.

**Comment by johnthecracker** [comment]
http://stream-recorder.com/forum/showpost.php?p=88000&postcount=4

**Comment by nickiman** [comment]
> http://stream-recorder.com/forum/showpost.php?p=88000&postcount=4

@johnthecracker now I see.
Thank you!
