### ISSUE TITLE
Getting streamdata directly into Python and opencv

### ISSUE THREAD

**Issue by DanielTea** [streamlink/streamlink#1386]
Hi, 

is it possible to stream twitch streamdata directly into opencv via streamlink? 
I'm looking for something like this (does not work but you'll get the concept):

```
streams = streamlink.streams("https://www.twitch.tv/grimmmz")
stream = streams["best"]
fd = stream.open()
bytes=''

while True:
    bytes+= fd.read(1024)

    a = bytes.find('\xff\xd8')
    b = bytes.find('\xff\xd9')

    if a!=-1 and b!=-1:
        jpg = bytes[a:b+2]
        bytes= bytes[b+2:]
        img = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8),cv2.CV_LOAD_IMAGE_COLOR)
        cv2.imwrite('messigray.png', img)
        cv2.imshow('cam2', img)

    else:
        continue

```

**Comment by gravyboat** [comment]
You could try https://streamlink.github.io/cli.html#cmdoption-stdout but I've never used that command so I'm not sure what the data output looks like. What would your use case be? Most of the opencv examples I've seen have been for modification of video in ways to try and circumvent automated takedown systems by making slight changes to videos so they avoid detection.

**Comment by DanielTea** [comment]
Hi gravyboart!

Thanks for your fast reply!
We try to do a realtime emotion analysis on streamers for a  university project, classifing them raging, laughing etc. That’s why we have to pipe the stream through openCV to do a face recognition.

I didn‘t try the stdout command yet. Will do. But I assume it will output a raw byte stream which we have to interpret or decode somehow. 

What works is creating a .ts file and read that file via openCV. But it is super Laggy and far from realtime.

**Comment by gravyboat** [comment]
No problem, if you don't have any luck with the stdout option, maybe give youtube-dl a try? They had a similar issue on this a while back: https://github.com/rg3/youtube-dl/issues/11291 that has some suggestions that might work, but it might produce the slowness issue you were encountering as well.

**Comment by beardypig** [comment]
Something similar was discussed in #857, might be a worth taking a look at that - if you didn't already :)

**Comment by AndyZhu1991** [comment]
```
streams = streamlink.streams('live.bilibili.com/1')
url = streams['best'].url
cap = cv2.VideoCapture(url)

while True:
    succ, frame = cap.read()
    if succ:
        # Do something here
    else:
        break

cap.release()
```
I have tried with `live.bilibili.com/xxx` and `www.panda.tv/xxx`

**Comment by gravyboat** [comment]
I'm going to close this since #1689 was merged.

**Comment by DanielTea** [comment]
Hi guys sorry for the late response but, I‘ve figured it out. Hope this helps some future folks.

It was quite tricky to accomplish with reasonable performance, though. 

Check out the project: https://github.com/DanielTea/rage-analytics/blob/master/README.md

**Comment by DanielTea** [comment]
Hi guys sorry for the late response but, I‘ve figured it out. Hope this helps some future folks.

It was quite tricky to accomplish with reasonable performance, though. 

Check out the project: https://github.com/DanielTea/rage-analytics/blob/master/README.md
