### ISSUE TITLE
Should we remove our money from Bountysource?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1388]
Recently Bountysource was acquired by a blockchain based marketplace, whatever that might mean so I think we should cash out since they aren't charging any fees for the next 60 days. We've got about $107 USD in the account, and unfortunately right now cash outs via bitcoin are disabled (not sure why they did this). Should we look at cashing this out and putting it towards something like a logo design from the person @bastimeyer knows? Or something else? I would rather we just spend it directly towards something than put it into the Opencollective because of their fees and the small amount of funds we currently have.

**Comment by bastimeyer** [comment]
Sure, let's use that 60 days time window. All I've read in the bountysource blogpost were a bunch of buzzwords, so I'm not sure what exactly will be happening to bountrysource and if it'll be a reliable platform in the future.

Regarding the logo, I can ask my friend again. #1123 doesn't seem to have helped finding someone else to work on a new logo. I'll need some definite numbers though, since all I could tell him last time were some wishy-washy things which he was not too happy about.

So if everybody else agrees to spend this on a logo design, I will ask him. I'm quite sure though that he'll also want a ref link to be added to the website, but I guess everybody will be okay with this. If he doesn't have time, we'll need to find somebody else.

**Comment by gravyboat** [comment]
@bastimeyer The current reason we have a reference link is because the logo we're using is free so it would be appropriate to give credit. If we're paying for the logo design would he still expect to be credited? I'm not really against it nor am I extremely familiar with the process, but in the past when I have paid for design work I have not credited since I (we in this case) would "own" the work. It doesn't seem as though we should have to credit if we don't want to since we own the artwork.

**Comment by beardypig** [comment]
What was the status of this in the end?

**Comment by gravyboat** [comment]
@beardypig I didn't end up cashing it out because they disabled bitcoin and didn't re-enable it within the window. I can still do so but I think it will have to be via USD unfortunately. It's only up to about $140 right now so we're going to lose some on the transfer out, then dumping it into the bountysource but I guess there isn't much we can do there to avoid that.

**Comment by gravyboat** [comment]
Okay so I received the following email from Bountysource today and this is pretty BS:

```
Bountysource is a community orientated platform with minimal operational overheads. Holding money for extended periods of time is causing costs to be incurred in accounting and maintaining the balance sheet. Bountysource management will be adding an inactivity fee to minimise costs in holding your money for long periods.

From 1st December 2018 we intend to start applying a monthly fee of $10 + 10% for unclaimed money over 90 days

You can avoid the inactivity fee by simply withdrawing your money regularly.

Note: All crypto bounties you earn are not affected as Bountysource incurs no cost in holding crypto bounties for you. Additionally there is currently no fees charged for crypto bounties. We encourage you to post crypto bounties instead.”

Thanks,
The Bountysource Team
```

So we need to cash out immediately. I tried to cash out today, but the only method it would allow was PayPal, and I don't use PayPal. @bastimeyer, @beardypig, @back-to, @cdrage does anyone use PayPal where we can do the cash out (minus the fees which I have a screenshot of below) then deposit into opencollective? I'm also sending them an email asking how I can cash out if I don't use PayPal.

![bounty_source_withdrawl](https://user-images.githubusercontent.com/1396878/45854624-e0904100-bd00-11e8-952b-3f41f605dde0.PNG)

**Comment by gravyboat** [comment]
Email is sent to their support team, waiting to see what their response is for how we can cash out.

**Comment by gravyboat** [comment]
Their support team has responded, they can't cash out crypto right now, and don't have a solution but said they will look into it for me.

**Comment by bastimeyer** [comment]
@gravyboat Ok, let's wait for them to look further into this. Otherwise, I can help with my paypal account, no big deal.

**Comment by beardypig** [comment]
Related to this, we probably all received this email today. 

>Bountysource is a community orientated platform with minimal operational overheads. Holding money for extended periods of time is causing costs to be incurred in accounting and maintaining the balance sheet. Bountysource management will be adding an inactivity fee to minimise costs in holding your money for long periods.
>
> From 1st December 2018 we intend to start applying a monthly fee of $10 + 10% for unclaimed money over 90 days
>
> You can avoid the inactivity fee by simply withdrawing your money regularly.
>
> Note: All crypto bounties you earn are not affected as Bountysource incurs no cost in holding crypto bounties for you. Additionally there is currently no fees charged for crypto bounties. We encourage you to post crypto bounties instead.”

Looks like it might be time to cash out via PayPal, dunno what we do with the cash. I wonder if @bastimeyer could cash it out and put the money back some how as Bitcoins? (Obviously minus the fees).

**Comment by gravyboat** [comment]
Quick update here, I am still waiting to hear back from their support.

**Comment by gravyboat** [comment]
Emailed them again last week, and they responded with the following:

> Not as yet.  We are still looking into the Bitcoin accounting for handling cases like yours.  I will try to give you an update by the end of week.

They did not update me by the end of the week, I will give them until the end of this week then email them again...

**Comment by gravyboat** [comment]
I've emailed them again asking about the status and suggesting that if they are unable to allow us to pull our money they can just zero the account and make an equivalent donation to our open collective.

**Comment by gravyboat** [comment]
They responded late Sunday and said they hope to have a resolution this week.

**Comment by gravyboat** [comment]
This has been resolved, cash out was submitted and minus fees the money has been donated directly to Opencollective: https://opencollective.com/johan1
