### ISSUE TITLE
[bug] BTV plugin not logging in (again)

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#1391]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
When attempting to watch the btv stream with a correct set of username+password, I continually get the "Login failed, a valid username and password is required". I've checked - both are correct and work within the website.

### Expected / Actual behavior
It should accept the valid username and password

And shouldn't the text be "Login failed, a valid username and password **are** required"?

### Environment details

Operating system and version: Win 7 64bit SP1
Streamlink and Python version: Latest windows nightly as of 28th Dec 2017

### Comments, logs, screenshots, etc.
I have noticed that there is a minituarized version of the live stream on the top right corner that's muted. If the btv website admins weren't smart about it, which is a possibility, that stream could give us a direct link which we could use to bypass the username/password requirement, would it not?

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/1333

@roshavagarga 
You are on an old streamlink version, install the latest nightly from this link

https://bintray.com/streamlink/streamlink-nightly/streamlink/_latestVersion/#files

---

don't use `https://dl.bintray.com/streamlink/streamlink-nightly/streamlink-latest.exe` it is outdated.

**Comment by roshavagarga** [comment]
@back-to 
Downloaded from said link, now I'm getting a "no playable streams found on this URL". Tried with http and https, checked and the stream is available on their website.

I'm guessing there's been a change to the player? I can give you an account and a password if you need one, as well as a proxy.

**Comment by back-to** [comment]
it works @roshavagarga 
make sure you are not geo blocked.

`streamlink http://www.btv.bg/live/ best --btv-password "PASSWORD" --btv-username "USERNAME" -l debug --http-proxy PROXY`

```
$ streamlink http://www.btv.bg/live/ best --btv-password "PASSWORD" --btv-username "USERNAME" -l debug --http-proxy PROXY
[cli][info] Found matching plugin btv for URL http://www.btv.bg/live/
[plugin.btv][debug] Found media id: 2110383625
[cli][info] Available streams: 400p (worst, best)
[cli][info] Opening stream: 400p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188565 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 188566 to queue
[stream.hls][debug] Adding segment 188567 to queue
[stream.hls][debug] Download of segment 188565 complete
[cli][info] Starting player: /usr/bin/mpv
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 188566 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 188568 to queue
[stream.hls][debug] Adding segment 188569 to queue
[stream.hls][debug] Download of segment 188567 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by roshavagarga** [comment]
Okay, I just noticed (hadn't closed the installer) that the installer from the link you gave me literally Skipped all of the files it should have installed. Running it as an administrator did not work either, which means I'll have to make a fresh install.

I'm guessing this is another bug we should note somewhere else @back-to?

**Comment by back-to** [comment]
run your command with `-l debug` you will see

```
[plugin.btv][debug] Found media id:
```

if the login worked.

---

the installer might install the files in a new location https://github.com/streamlink/streamlink/issues/1340 but it should work.
the files got skipped because you used the installer twice or?

**Comment by roshavagarga** [comment]
They were skipped on the very first install. Same deal on every other install, once I'm finished cooking I'll reinstall it completely I guess.

**Comment by roshavagarga** [comment]
@back-to Uninstalled, reinstalled, same problem.

I continue to get a combination of "invalid username/password" and afterwards "no valid streams found at this url". 

l debug does not show anything after these two, probably because of the failed login. The username and password are correct, as they work on the website, but not via streamlink. Any ideas on how to further debug this obviously weird problem?

**Comment by bastimeyer** [comment]
@roshavagarga Can you please use the `--version` parameter and tell us which version you are using when you run streamlink?

**Comment by roshavagarga** [comment]
Using "streamlink --version" gives out a message "streamlink-script.py 0.7.0".
I just installed the brand new one back-to linked me, only file that was skipped was the streamlinkrc file.

**Comment by bastimeyer** [comment]
When you're running `streamlink` the shell you're using first needs to resolve the absolute path of the executable you intend to run. This depends on the content of the `PATH` environment variable (and `PATHEXT` as well on Windows), which is a list of paths where the shell should look for.

Please use the absolute path of the newly installed streamlink executable, or make sure that your system is using the new one when you're just running "streamlink". Try uninstalling other streamlink installations or clean up the `PATH` env var.

**Comment by roshavagarga** [comment]
@bastimeyer - where is the PATH var? I uninstalled all of the previous installations (1?) and installed the new one. Could there have been leftover files from the uninstaller?

**Comment by bastimeyer** [comment]
That's a system configuration, which shouldn't be discussed here. Please use a search engine.

As @back-to has already pointed out, the recent installers are using a different installation path, so that's maybe the source of your misconfiguration here.

**Comment by roshavagarga** [comment]
@bastimeyer Okay, I'll try to, ahem, figure this out on my own then. I do feel that whether this is a system configuration or not, noobs like me should receive advice on stuff like this, so perhaps a segment should be added for this sort of problem to streamlink's online pages/knowledge repository.

**Comment by back-to** [comment]
@roshavagarga 
if the old files are still there, you can use them to uninstall it.

__Uninstall 0.7.0__ (default location)
`C:\Program Files (x86)\Streamlink` use `uninstall.exe`

__Uninstall 0.9.0__ (default location)
`%LOCALAPPDATA%\Streamlink` use `uninstall.exe`

---

if the __0.7.0__ is not there, just install it again and use the `uninstall.exe`
https://github.com/streamlink/streamlink/releases/tag/0.7.0

**Comment by roshavagarga** [comment]
@back-to Okay, found the old installation (no idea how it wasn't popping up in my installed applications) and removed it as instructed, problems seem to be resolved now.

**Comment by gravyboat** [comment]
Closing, thanks @back-to and @bastimeyer.
