### ISSUE TITLE
Error Douyu

### ISSUE THREAD

**Issue by meesudzu** [streamlink/streamlink#1393]
error: Unable to validate JSON: Unable to validate key 'data': u'' does not equal None or Type of u'' should be 'dict' but is 'unicode'
help me, pls.

**Comment by IsoaSFlus** [comment]
Douyu's UWP client also cannot open any room.

**Comment by meesudzu** [comment]
It still view stream on Douyu, yesterday.

**Comment by IsoaSFlus** [comment]
@meesudzu  In fact, it just happened several hours ago.

**Comment by meesudzu** [comment]
@IsoaSFlus can your repositories "QLivePlayer" work?

**Comment by IsoaSFlus** [comment]
@meesudzu  No, this project depends on streamlink to get stream.

**Comment by Vizards** [comment]
@IsoaSFlus I just installed your QLivePlayer a few minutes ago, and then I found that streamlink could not get Douyu's stream lol

**Comment by meesudzu** [comment]
lol, i hope they can fix soon.

**Comment by IsoaSFlus** [comment]
@Vizards  I think streamlink will fix it soon, because Douyu seems having most users in China.

**Comment by fozzysec** [comment]
The response from Douyu's API now return error message.
```
{"error":119,"data":""}
```

It seems that Douyu changed their app key several hours ago, we need someone to reverse engineer the new SWF player to get the new app key.

**Comment by meesudzu** [comment]
hey, it doesn't fix. I still have this error.
why??? 
![screenshot from 2017-12-29 20-44-52](https://user-images.githubusercontent.com/17334624/34438494-d4d3cba4-ecd9-11e7-8481-16f22b6e5ba0.png)
