### ISSUE TITLE
Can no longer download Openrec.tv VODS

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink#1397]
Im trying to download openrec VODS like I used to with the following command:
streamlink openrec.tv/live/t1T0kPCaEFA source -o D:\testing.mp4       no longer works.

Any possible solution would be appreciated!

### Checklist

- [x] This is a bug report.
- [x ] This is a plugin (improvement) request.

**Comment by back-to** [comment]
@jstrat231 
this is a **premium** video, you will need a **login**.

you can test this

https://gist.githubusercontent.com/back-to/b87db3ce1dbb0ea716e20ef182230d31/raw/4b5827276daa6dc5e476f35c5ff3dabc03640432/openrectv.py

you will have to edit the email and password there.

https://gist.github.com/back-to/b87db3ce1dbb0ea716e20ef182230d31#file-openrectv-py-L46-L47

**Comment by back-to** [comment]
**normal videos are working.**

---

for the premium/login videos ...

**OP hasn't responded in 2 months,**
the interest might be gone

Closing.

**Comment by MeteorVE** [comment]
Thanks for this issue.
After trying, I found this command work.

``streamlink https://www.openrec.tv/live/replace_to_your_url source -o D:\testing.mp4  --openrectv-email='your_account@gmail.com' --openrectv-password='your_pwd'``

Provide to those in need.
