### ISSUE TITLE
Streamlink 0.10.0 (any blockers)

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1399]
Monthly any-blockers release.

Haven't had one since November. Any blockers or can I go ahead with a new release?

**Comment by gravyboat** [comment]
I think we should be good for another release.

**Comment by thinkpad4** [comment]
Will this include this fix? https://github.com/streamlink/streamlink/issues/1340

**Comment by beardypig** [comment]
@thinkpad4 it's not fixed, and that should be a blocker. We can do it by pinning `pynsist<2` in the dev-requirements, but special care will have to be taken when building the release exe.

**Comment by gravyboat** [comment]
Good catch, I totally forgot about that one.

**Comment by bobvargas** [comment]
@gravyboat  @beardypig I hope that release would include ok.ru and the url https://www.ok.ru/live/412362939914 I would be happy if they make one

**Comment by gravyboat** [comment]
@bobvargas Definitely not going to happen. It would be an entirely new plugin to build and I already commented on https://github.com/streamlink/streamlink/issues/1404 where both you and the requester of the plugin showed me two examples, both of which were stolen Japanese TV station restreams.

**Comment by bastimeyer** [comment]
I think #1374 and the issue of the failing builds on TravisCI should be reviewed before releasing `0.10.0`.

**Comment by amurzeau** [comment]
Failed builds on TravisCI must be related to https://github.com/travis-ci/travis-ci/issues/9000 if you talk about connections timeouts.

**Comment by bastimeyer** [comment]
There were a couple of `could not create session key: disk quota exceeded` startup errors, which are super annoying, especially since the builds don't get restarted automatically.

But you're right, I've also seen a couple of network related issues in the past. Maybe dependency caches should be set, so that all the stuff doesn't need to get downloaded each time. Currently, pip dependencies don't get cached in the travis config:
https://github.com/streamlink/streamlink/blob/aa45712ee9919cd21dac758450ca06a0742bb2e4/.travis.yml
https://docs.travis-ci.com/user/caching/#pip-cache
Is there anything special which needs to be checked here?
https://docs.travis-ci.com/user/caching/#before_cache-phase
https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices

**Comment by gravyboat** [comment]
I really dislike caching builds if we don't absolutely need to do so. I know that it's primarily for dependencies but I've had issues with multiple setups where caching was the culprit and things weren't getting updated properly for the image even though only the dependencies were set to cache. We can give it a shot but we'll still have to restart builds occasionally as I've been seeing this issue for quite some time without a fix from Travis.

**Comment by amurzeau** [comment]
Maybe there is a way to retry dependencies download.
git clone sometimes fail to connect to github.com but there are 3 retries and it usually still works.
But I didn't found anything in setuptools documentation to retry dependencies downloads.

**Comment by cdrage** [comment]
@gravyboat @bastimeyer Should I push 0.10.0 now? (a few plugins broke (like every release, lol), so may be good to push another release while we wait for https://github.com/streamlink/streamlink/pull/1374 to be unblocked.

**Comment by bastimeyer** [comment]
What about the YouTube plugin?
Even if #1423 doesn't fix all the issues, at least it'll fix #1421, which is quite a popular issue which shouldn't be in the next release.

I think that we can't always wait so much with publishing new releases. I've already mentioned it in https://github.com/streamlink/streamlink/issues/1347#issuecomment-357467050, maybe a different release model needs to be chosen, but that discussion doesn't belong here.

**Comment by gravyboat** [comment]
@bastimeyer I've merged #1423. @unlocKing it definitely won't happen on this release, no one has even started to look at it and we're behind on releases as is.

**Comment by cdrage** [comment]
@gravyboat @amurzeau Okay all, I'm going to go ahead and do a release. I'm going to setup a calendar entry to try and get a release out every 3 weeks (on a Monday or Tuesday, Tuesday depending on blockers). This works out to be the same schedule as other open source projects I work on (see my GitHub), so it's not a problem to do all three releases on the same day / create the release docs.

**Comment by cdrage** [comment]
Like what @gravyboat said, issues be damned. We should do a time based release rather than feature-based. Especially since streamlink's plugins break *a lot* due to upstream API or URL changes.

**Comment by gravyboat** [comment]
@cdrage That sounds good to me, thanks!

**Comment by gravyboat** [comment]
@cdrage Can you add the opencollective link to your template for future releases please?

**Comment by bastimeyer** [comment]
Not sure whether @cdrage read @gravyboat's comment, but let's close this thread, since `0.10.0` is already out...

**Comment by cdrage** [comment]
Ah sorry, I'll get on that @bastimeyer I've been meaning to update the release script anyways :)
