### ISSUE TITLE
Web page for the project

### ISSUE THREAD

**Issue by sbstp** [streamlink/streamlink#14]
I think we could easily setup a website using Github Pages, (https://streamlink.github.io). We could update the docs, generate them using sphinx and push it to the repo. Maybe the docs should be in their own repo.

* `streamlink/streamlink` - main project
* `streamlink/docs` or `streamlink/streamlink/docs` - docs source
* `streamlink/streamlink.github.io` - generated html

**Comment by cdrage** [comment]
@sbstp agreed. let's put this on the todo.

Personally, I'm going to work on reorganizing the code before we work on the docs as we start to change things such as the CLI and such to a much-cleaner user experience.

**Comment by sbstp** [comment]
Can I get access to the organization? I'll add this to the todo.

**Comment by cdrage** [comment]
@sbstp Invite sent!

**Comment by sbstp** [comment]
I'm working right now on getting the docs to work. I'll send a PR once I'm done.

**Comment by sbstp** [comment]
I'm updating the links found on [http://docs.livestreamer.io/](http://docs.livestreamer.io/), should I remove the elements we don't have setup yet? Like the google groups and the IRC channel.

**Comment by gravyboat** [comment]
@sbstp Definitely. We don't want users confused if we can avoid it.

**Comment by WolfganP** [comment]
Good job to focus on docs early on, documentation is important :-)

As I proposed on https://github.com/chrippa/livestreamer/issues/1187 , if anyone knows of any "Primer on developing plugins", that may help on getting casual devs engagement and keep the project growing.

**Comment by gravyboat** [comment]
@WolfganP Feel free to create an issue over here (or a PR if you want). I think right now that stuff is a little lower on the priority list since we have a lot to fix to get this back to a good working state, but I also love docs and would like to see this.

**Comment by sbstp** [comment]
I think we should discuss wether to use github's wiki feature instead of using github pages + sphinx. I think that a lot more people are familiar with markdown than rst. It might help keeping high quality docs. The wiki is more accessible.

**Comment by sbstp** [comment]
Although thinking about it, a lot of projects have outdated and incomplete wikis. I've had a pretty bad experience browsing projects' wikis so far. It might be better to stick to sphinx.

**Comment by gravyboat** [comment]
Yeah that was what I was going to mention. Being able to just do a pull and update docs (especially in functions and so forth) is a lot easier than having to update the wiki. It just adds more work and a higher bar to entry.

**Comment by sbstp** [comment]
I pushed the docs, but there's an [issue](https://streamlink.github.io/). It fails to load the assets, but they're in the repo, so I'm not sure what's going on.
