### ISSUE TITLE
Support for ok.ru?

### ISSUE THREAD

**Issue by Bluebuster116** [streamlink/streamlink#1404]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Is Ok.ru supported by streamlink?. I have looked in different sources but there is no information which I could find on this matter. There is this stream http://ok.ru/videoembed/412346031626 which I would like to use with streamlink but I am unable to get it work.

### Expected / Actual behavior

I have only been able to catch this "source" from inspecting the player https://vsd0.mycdn.me/dash/stream_333533874698/stream.manifest/sig/La5bYbT_yFY/expires/1515003608246/srcIp/201.240.21.221/clientType/0/srcAg/CHROME/frag-medium-9937.dash but the fragments make it not possible to use it with the existing parameters on streamlink. Any suggestions or possibly support of ok.ru on streamlink?

### Reproduction steps / Explicit stream URLs to test

1. None

### Environment details

Operating system and version:  Windows 7
Streamlink and Python version: current

### Comments, logs, screenshots, etc.

None

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bobvargas** [comment]
Hopefully they can support urls for tv tokyo on ok.ru and the url https://www.ok.ru/live/412362939914

**Comment by gravyboat** [comment]
What kind of content do they stream on this site? Based on what @bobvargas is saying it looks like the site is kind of a Russian Facebook, but people are using their streaming function to restream illegal content, and the link from @Bluebuster116 is also restreaming a television station illegally.

**Comment by atykhyy** [comment]
ok.ru is indeed a sort of Russian Facebook (the other one being vk.com). Russians are using it for camshows and what-not (look at their [top page](https://ok.ru/live)) so it's no more inherently illegal than vaughnlive.tv or any other streaming network. Here is a plugin that does the job for live videos, feel free to add it or not:
```
import urllib3
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http, validate
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream
from streamlink.utils import parse_json
from bs4 import BeautifulSoup

class OK_live(Plugin):
    """
    Support for ok.ru live stream: http://www.ok.ru/live/
    """
    url_re = re.compile(r"https?://ok.ru/live/\d+")

    vod_hls_schema  = validate.Schema({u"hlsMasterPlaylistUrl": validate.url()},
                      validate.transform(lambda x: x["hlsMasterPlaylistUrl"]))
    vod_meta_schema = validate.Schema({u"flashvars": {u"metadata": validate.text}},
                      validate.transform(lambda x: x["flashvars"]["metadata"]))

    @classmethod
    def can_handle_url(cls, url):
        return cls.url_re.match(url) is not None

    def _get_streams(self):
        headers = {
            'User-Agent': useragents.CHROME,
            'Referer': self.url
        }

        soup = BeautifulSoup(http.get(self.url, headers=headers).text, 'html.parser')
        meta = parse_json(soup.find('div',attrs={'data-module':'OKVideo'})['data-options'], schema=self.vod_meta_schema)
        hls  = parse_json(meta, schema=self.vod_hls_schema)
        return HLSStream.parse_variant_playlist(self.session, hls, headers=headers)


__plugin__ = OK_live
```
Note: requires BeautifulSoup4 because really, parsing HTML with regular expressions?

**Comment by gravyboat** [comment]
@atykhyy I hate Vaughnlive and a bunch of the other plugins so I can't weigh in much there other than to try and avoid adding additional shady plugins.

**Comment by gravyboat** [comment]
#1451 is merged so I'm closing this.
