### ISSUE TITLE
BeIn Connect Streams

### ISSUE THREAD

**Issue by Ike348** [streamlink/streamlink#1405]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I am trying to grab streams from https://connect.beinsports.com/us/html/

### Expected / Actual behavior

BeIn Connect stream should open in VLC (or output to file with -o)

### Reproduction steps / Explicit stream URLs to test

I can grab a URL in this format:

https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=**this_is_my_ip**~st=1514946690~exp=1514953890~acl=/*~hmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6

I run

streamlink "akamaihd://https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip~st=1514946690~exp=1514953890~acl=/*~hmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6"

[cli][info] Found matching plugin akamaihd for URL akamaihd://https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip~st=1514946690~exp=1514953890~acl=/*~hmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6

[cli][info] Available streams: live (worst, best)

[cli][info] Opening stream: live (akamaihd)

[cli][error] Try 1/1: Could not open stream <AkamaiHDStream('https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip~st=1514946690~exp=1514953890~acl=/*~hmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6', swf=None)> (Could not open stream: Unable to open URL: https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd (403 Client Error: Forbidden for url: https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?v=2.5.8&fp=LNX+11%2C1%2C102%2C63&r=EFQNS&g=RFUFVRQHPGMC))
error: Could not open stream <AkamaiHDStream('https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip~st=1514946690~exp=1514953890~acl=/*~hmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6', swf=None)>, tried 1 times, exiting

I was reading [this](https://github.com/streamlink/streamlink/issues/1107) report for FoxSports Go which suggested that I include cookies (as accessing the stream does require login), but I can't figure out which cookies I'm supposed to include, or even if I'm using the right URL or format.

Running on a MacBook Pro 10.13.2

Thanks!

**Comment by gravyboat** [comment]
It looks like these streams are using DASH for the video? We aren't currently supporting DASH unfortunately (https://github.com/streamlink/streamlink/issues/990 is the related issue).

**Comment by Ike348** [comment]
I had a hunch, but I didn't know if these streams would be any different. Any word on if this will be implemented in the future?

Thanks!

**Comment by gravyboat** [comment]
@Ike348 No timeline unfortunately, it's a big task to implement DASH and dev time is pretty limited with how small our team is.

**Comment by karlo2105** [comment]
@Ike348 
Try with modified headers for Iphone, Android ou iPad. HLS is always available along to Dash.

**Comment by Ike348** [comment]
@karlo2105 I used a Chrome user agent switcher extension, but no matter what I switch to (iPhone 4, iPad, Galaxy tablet, etc.), the URL snooper still only comes up with the dash streams. The switcher is clearly working as intended because going to google.com takes me to the mobile site. Access to the stream on an actual mobile web browser is restricted as they force you to download their app.

I can play the dash streams in VLC 3, but I'm having trouble saving them to a file as cleanly as I can with streamlink or livestreamer

**Comment by karlo2105** [comment]
@Ike348 
If you want to carry on with streamlink on bein connect you can transform dash stream into hls.

`https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip%7Est=1514946690%7Eexp=1514953890%7Eacl=/*%7Ehmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6` to 

`https://besusad-i.akamaihd.net/hls/live/901484/besus01d_4/playlist.m3u8?hdnts=ip=this_is_my_ip%7Est=1514946690%7Eexp=1514953890%7Eacl=/*%7Ehmac=89c4000ebc6b549d0ca3888d8babb43031d5ea878eeaefdfacf4ccf9bf4af4e6`

**Comment by johnthecracker** [comment]
@Ike348

Your quote:

I can play the dash streams in VLC 3, but I'm having trouble saving them to a file as cleanly as I can with streamlink or livestreamer


I get good result with this command line and vlc 2.8:

vlc https://english.streaming.aljazeera.net/aljazeera/english2/index1296.m3u8 --demux=dump --demuxdump-file=c:\aljazeera.dump -I no_gui vlc://quit

https://wiki.videolan.org/Documentation:Streaming_HowTo/Receive_and_Save_a_Stream/

**Comment by Ike348** [comment]
@karlo2105 I tried, and I get a 404 error. I know I'm using a working URL as the stream plays in VLC 3, but when I try to run the HLS in streamlink, I get a 404. Just to be clear, the differences are besusad -> besuash, dash -> hls, besus01d -> besus01h, manifest.mpd -> playlist -> m3u8    ?

@johnthecracker Thanks for the suggestion. I have no experience with vlc command line, and I've tried variations on your code (I'm on a Mac) with both VLC 2 and 3, and none has worked. If I can't get streamlink working, some form of this has to be the solution.

**Comment by karlo2105** [comment]
@Ike348 
Take a look below. It's sorted by quality. Not sure how the end of m3u8 address look like. It's either playlist.m3u8 but it can be also master.m3u8 or index.m3u8.

```
#EXTINF:-1,beIN_SPORTS_News (360p)
http://besmenaah-i.akamaihd.net/hls/live/221906/besmena02h/02.m3u8
#EXTINF:-1,beIN_SPORTS_News (480p)
http://besmenaah-i.akamaihd.net/hls/live/221906/besmena02h/03.m3u8
#EXTINF:-1,beIN_SPORTS_News (600p)
http://besmenaah-i.akamaihd.net/hls/live/221906/besmena02h/04.m3u8
#EXTINF:-1,beIN_SPORTS_News (720p)
http://besmenaah-i.akamaihd.net/hls/live/221906/besmena02h/05.m3u8
#EXTINF:-1,beIN_SPORTS_News (1080p)
http://besmenaah-i.akamaihd.net/hls/live/221906/besmena02h/06.m3u8

```

**Comment by Ike348** [comment]
@karlo2105 Thanks, but I can't for the life of me seem to find an hls playlist. Everything either returns a 404 or 403 (even with the URL cookie). They might just not be included for this stream.

I'm working on cracking this, as I can record the stream using this VLC 3 command

`/Applications/VLC.app/Contents/MacOS/VLC -vvv https://besusad-i.akamaihd.net/dash/live/901484/besus01d_4/manifest.mpd?hdnts=ip=this_is_my_ip~st=1515171988~exp=1515179188~acl=/*~hmac=a22b93fdc23be8e98fbba55901d0dce889f5c66eaf28d034c0c9e545a86f4b87 --preferred-resolution 720 --sout=file/ts:filename.ts -I rc`

However, I'm still running into issues. VLC doesn't start recording the audio track until a few seconds in, so any conversion software doesn't recognize that there is audio at all. This means ffmpeg converts the ts to a video with no sound, and HandBrake actually crashes. When I try to convert the video through VLC, I get an M4V that is actually audio only. I can then throw the video only and audio only tracks back together in ffmpeg, to get a working mp4, but this means a 3-step conversion process instead of 1.

If anyone has any ideas on how to convert this file in one go (or prevent vlc from recording in the first place until it has an audio track), let me know. Here is an example file for anyone interested: https://www.mediafire.com/file/d86fur8s2ydyncc/bein+old.ts

I'm still hoping for a streamlink solution as I'm more familiar with it and the entire recording/converting process would be 10x easier, but that's looking less and less likely.

Thanks again for all of your help @johnthecracker @gravyboat @karlo2105

**Comment by back-to** [comment]
there are already good examples in this issue of how to get the m3u8 url, **if they are enabled**.

unlucky that it doesn't work for you, but it should work for the most of the akamaihd streams.

Closing.

---

from above

https://github.com/streamlink/streamlink/issues/1405#issuecomment-354956722
https://github.com/streamlink/streamlink/issues/1405#issuecomment-355106685

**Comment by seyf87shop** [comment]
What is the name of the program used in grab streams ?
