### ISSUE TITLE
Ok.ru support

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#1409]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...Hey Guys I love to watch ok.ru streams now because i have nothing to do

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
https://.ok.ru/live/375550844519
2. ...
https://ok.ru/live/412362939914
3. ...
https://ok.ru/live/484903624282

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...
Hopefully this plugin would be supported because it uses a rtmp stream thanks

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by d0tfile** [comment]
Why are you opening another issue?
Duplicate https://github.com/streamlink/streamlink/issues/1404

**Comment by gravyboat** [comment]
Closing since this is a duplicate. @bobvargas You need to stop posting all these duplicates and commenting on issues where it is inappropriate asking for plugins. If this continues I'm going to ban you from being able to post as you are not contributing in a positive way.

**Comment by HalowTV** [comment]
Hi guys big thx for all works  i ned ask how i can play playlist?
https://ok.ru/video/c11560750

**Comment by bastimeyer** [comment]
Don't necro-bump 5 year old and unrelated threads. If there is a plugin issue, then open a new plugin issue thread and fill in all the required details.

Locking...
