### ISSUE TITLE
cant update streamlink

### ISSUE THREAD

**Issue by anniman** [streamlink/streamlink#1417]
Write  Preview

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
i've installed streamlink on ubuntu 14.04 but couldnt get tvplayer plugin to work, getting 404 client error.
i came across the solution 998 and 1228 to use 
pip install -U git+https://github.com/streamlink/streamlink.git but get errors of 
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

any tvplayer stream

### Environment details

Operating system and version: ...
Streamlink and Python version: ...
0.7.0                       2.7 or 3
...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
i've installed streamlink on ubuntu 14.04 but couldnt get tvplayer plugin to work, getting 404 client error.
i came across the solution 998 and 1228 to use 
pip install -U git+https://github.com/streamlink/streamlink.git but get errors of 
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cryptography
Storing debug log for failure in /root/.pip/pip.log

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

any tvplayer stream

### Environment details

Operating system and version: ...
Streamlink and Python version: ...
0.7.0                       2.7 or 3
...

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by d0tfile** [comment]
Do you have package `libssl-dev` installed? Can you show full log? (pastebin, not plaintext here)

**Comment by back-to** [comment]
for the pip issue
```
pip install -U pip setuptools
```

but you might see an ssl error, install this aswell.

```
sudo apt-get install python-dev libffi-dev libssl-dev
```

**Comment by anniman** [comment]
tried that and now get https://pastebin.com/AvsUm3RH.
can the linux package be brought up to date for installation

**Comment by anniman** [comment]
what is the correct procedure ot commands to update from 0.7.0 to 0.9.0. i have tried all the commands i can see on here and i keep getting version 0.7.0.
ubuntu 14.04

**Comment by back-to** [comment]
the best way is **python3**

first **uninstall** your **old streamlink** version

```
sudo apt remove streamlink
sudo pip uninstall streamlink
```

`which streamlink` should return nothing

---

Now install **pip3**

```
$ sudo apt install python3-pip
$ pip3 --version
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
$ which pip3
/usr/bin/pip3
$ sudo pip3 install -U pip setuptools
$ pip3 --version
pip 1.5.4 from /usr/lib/python3/dist-packages (python 3.4)
$ which pip3
/usr/local/bin/pip3

```

open a new terminal / relog

```
$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages (python 3.4)
$ which pip3
/usr/local/bin/pip3
$ sudo -H pip3 install -U git+https://github.com/streamlink/streamlink.git
Successfully installed streamlink-0.9.0
$ streamlink --version
streamlink 0.9.0
```

---

if you don't want to use `sudo` use
https://streamlink.github.io/install.html#installing-without-root-permissions

@anniman

**Comment by anniman** [comment]
thanks backto, i now have 0.9.0 installed but for any channel on tvplayer i still get the 404 error. where is the tvplayer.py file stored in ubuntu ?
i can find it on the windows version ok

**Comment by back-to** [comment]
```
/usr/local/lib/python3.4/dist-packages/streamlink/plugins
```
but it should be up to date.

@anniman does it work on windows?

**Comment by anniman** [comment]
aha, that folder /usr/local/python3.4/dist-packages/ is empty

**Comment by anniman** [comment]
windows works fine

**Comment by back-to** [comment]
my path was from a fresh ubuntu 14.04 with the above guide

if you can't update your version correctly,
**you can sideload the plugin.**

- https://streamlink.github.io/cli.html#sideloading-plugins
- https://streamlink.github.io/cli.html#cmdoption-plugins

**Comment by anniman** [comment]
i was talking rubbish there. i had to renew my winscp session. the folders are there in dist-packages. the server is in the uk so should play the streams. what else can be wrong looking at the lig

**Comment by back-to** [comment]
@anniman 
if you have session errors thats might be it,
your system still thinks it's the old version.

you have to reload it and make sure you had uninstalled ever other different version of streamlink.

if it still doesn't run,
sideload the plugin
https://github.com/streamlink/streamlink/issues/1417#issuecomment-356338021

and run a `-l debug` command with your url

---

you could try to use the none root version, if it still doesn't work

https://streamlink.github.io/install.html#installing-without-root-permissions

```sh
ubuntu@ubuntu:~$ virtualenv ~/myenv
ubuntu@ubuntu:~$ source ~/myenv/bin/activate
(myenv)ubuntu@ubuntu:~$ pip install -U pip setuptools
(myenv)ubuntu@ubuntu:~$ pip install streamlink
# streamlink should be installed now
(myenv)ubuntu@ubuntu:~$ streamlink --version
streamlink 0.9.0
(myenv)ubuntu@ubuntu:~$ which streamlink
/home/ubuntu/myenv/bin/streamlink
# try a stream
(myenv)ubuntu@ubuntu:~$ streamlink https://tvplayer.com/watch/___ best -l debug
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/___
... DEBUG DATA ...
(myenv)ubuntu@ubuntu:~$ deactivate
ubuntu@ubuntu:~$ ~/myenv/bin/streamlink --version
streamlink 0.9.0
```

**Comment by earthtone2** [comment]
This is really driving me crazy because I tried these steps and they worked today to get the latest version, but it didn't have the plugin I wanted so I decided to go back to the old version. Now I can't get either version of streamlink to install.

This time, when I try 

`sudo -H pip3 install -U git+https://github.com/streamlink/streamlink.git`

I get

pkg_resources.DistributionNotFound: The 'pip==18.1' distribution was not found and is required by the application
