### ISSUE TITLE
Weird issue, youtube live stream starts playing 4 hours backwards?

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#1419]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description
Youtube live stream starts playing from 4 hours backwards into the live stream.

### Expected / Actual behavior
Play stream as it should, close as possible to real time.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink -p mpv https://www.youtube.com/watch?v=2TrGSO2ZQ_Q 480p`
2. `streamlink -p mpv https://www.youtube.com/watch?v=rGNNXg8YJoU 480p`

### Environment details

Operating system and version: Archlinux, up to date
Streamlink and Python version: 0.9.0.r55.gaa45712e and python-3.6.4-1

Edit: downgraded to stable version 0.9.0 and the issue was gone.

### Comments, logs, screenshots, etc.
Weird part is that livestreamer plays these same streams just fine. ;-)
Below is a screenshot with live stream playing in the background in Opera and in front of it is mpv window opened with streamlink. Look at the time stamp. Both were started second or two apart.

![screenshot_20180108_162259a](https://user-images.githubusercontent.com/6218030/34678329-1ea4c646-f493-11e7-92ab-0fefbfbaaffd.png)

**Comment by mmetak** [comment]
@beardypig this appers after this PR: Merge pull request #1303 from beardypig/hls-skip

**Comment by beardypig** [comment]
I'll take a look :) (unless @back-to beats me to it ;))

**Comment by back-to** [comment]
@beardypig 
it's because of
https://github.com/streamlink/streamlink/commit/3ff1fcd0fe50085e0f3b9c39f8fedb8ac319af56

but you need this for every normal vod.

---

https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/hls.py#L132-L137

`self.duration_offset_start` is **0** there for the livestream

changing it to **-1** when it's **0**, could be a workaround.

**Comment by mmetak** [comment]
@back-to That fixes it. 😅

**Comment by mmetak** [comment]
@gravyboat I think you merged #1424 too soon?

@back-to said this in that PR:
> streamlink/streamlink#1423 required for youtube.

**Comment by back-to** [comment]
@mmetak this issue here was not youtube related,
livestreams with a playback are fixed now.

---

But **youtube** itself is broken. #1421

so it's fine.
