### ISSUE TITLE
videos from the Fuji TV website

### ISSUE THREAD

**Issue by kenichi512** [streamlink/streamlink#1422]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

A few months ago it was possible to download the videos even though their links are temporary (token). But now no matter how many times I updated the links for each download attempt, the result is the same.

### Reproduction steps / Explicit stream URLs to test

http://www.fujitv.co.jp/b_hp/dragonball_super/index.html

### Environment details

Windows 10 Pro 64 bits
Python 2.7.13
Streamlink 0.9.0 (I used version 0.8.1 before but it was lost after reinstalling Windows)

### Comments, logs, screenshots, etc.
![26693198_1561378050622466_447676995_o](https://user-images.githubusercontent.com/25917998/34700031-b9920d42-f4ae-11e7-82ba-a58bc4ed2895.png)

**Comment by back-to** [comment]
your token expired, it works with a valid token.

**Comment by kenichi512** [comment]
I know that, although I'm not sure but I have two hypotheses.

* The duration of the token is now even shorter than before, very much that the obtaining of the link (I catch it with Internet Download Manager) and CLI execution is still relatively short. As I mentioned, I replaced the links in each download attempt, but the result is the same.
* I also suspect that now each token last only one play at a time. I say it because before when playing the video, pause the video, get the link and run the CLI to download, the time it took to do all this process was short (10-15 seconds approximately) and enough to get the file downloaded. But now even if it's the same link, the download does not work after the video has been played in the browser.

In fact now, due to several failed download retries, this appeared
![26732768_1562364640523807_691964070_o](https://user-images.githubusercontent.com/25917998/34724697-c5d5d584-f51c-11e7-899c-91288d809675.png)

**Comment by back-to** [comment]
your example video is only **14sec** long,
is it longer with a login?

```
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="movieid_50239816ufiE7KMsvbi-encryption-00001.key"
#EXTINF:10,
movieid_50239816ufiE7KMsvbi-00001.ts
#EXTINF:4,
movieid_50239816ufiE7KMsvbi-00002.ts
#ZEN-TOTAL-DURATION:14.20000
#ZEN-AVERAGE-BANDWIDTH:1140569
#ZEN-MAXIMUM-BANDWIDTH:1208614
#EXT-X-ENDLIST
```

**Comment by kenichi512** [comment]
That is the duration of the video and so it was uploaded to the site, neither they do not use the user account system.

I'm sorry for my ignorance but how could you extract that?

**Comment by back-to** [comment]
@kenichi512 

**Firefox** --> **Network Monitor** (press F12)--> **Response**

If you start the Video you will get the m3u8 url there

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor#Network_request_details

**Comment by kenichi512** [comment]
When the #EXTM3U header is already obtained, how do I use it with Streamlink? Because although I copy the link from the Firefox console, the result in Streamlink does not change.

Is not something related to plugins that needs to be improved so that the program can extract the token by itself for each download attempt?

**Comment by back-to** [comment]
If you want a plugin for this, you need to mention it and provide some more **example urls**
A 14 second video is not really worth it.

---

your origin question was why it won't play with streamlink,
well the **token expired**.

You need to **copy** the link **immediately** from the browser.

```
$ streamlink hls://"https://spot.v2.fujitv.co.jp/5023981/movieid_50239816ufiE7KMsvbi.m3u8?__token=XXX" best -l debug -o 123.ts
[cli][info] Found matching plugin hls for URL hls://https://spot.v2.fujitv.co.jp/5023981/movieid_50239816ufiE7KMsvbi.m3u8?__token=XXX
[plugin.hls][debug] URL=https://spot.v2.fujitv.co.jp/5023981/movieid_50239816ufiE7KMsvbi.m3u8?__token=XXX; params={}
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 0; Last Sequence: 1
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 1
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 0 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Closing writer thread
[download][123.ts] Written 1.4 MB (2s @ 624.0 KB/s)                                                                                                           
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by kenichi512** [comment]
About the plugin was just a small comment for how before and now the program tries to extract the video. But no matter how fast I copy the link and run the CLI, I do not get download.

**Comment by back-to** [comment]
user related issue

closing.
