### ISSUE TITLE
Question: Interact with no-GUI Player in mid stream

### ISSUE THREAD

**Issue by nichcuta** [streamlink/streamlink#1425]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Let say you start the player with no GUI and at a certain point in time during the stream you decide to mute/lower the volume. Is it possible to interact with the player through the CLI/python program?

If it is possible to interact with the player in mid stream, how can i call it?

Example player settings in config file: player="D:\Program Files\Mpv Player\mpv.exe" -no-video -cache 4096 --volume 30 --keep-open=no
...

**Comment by gravyboat** [comment]
No it's not possible and would require a pretty major rework to happen. What would be the use case for this? If you already have the player open why wouldn't you just modify the sound settings via the player itself?

**Comment by nichcuta** [comment]
Since i am only streaming Audio and no physical player is visible on screen i cant modify the sound settings via the player itself and wondered if its possible to do it via python by calling the player itself.

**Comment by gravyboat** [comment]
Ahh I see, yeah there's no way to do that via Streamlink. You might be able to somehow make a call directly to the player somehow for open sessions, but that's outside our scope of knowledge.

**Comment by nichcuta** [comment]
Thanks for the clarification mate :), you can go ahead and close the topic then.

PS: Keep up the great work!!

**Comment by beardypig** [comment]
@nichcuta MPV does have some ability to be remote controlled, not sure how easy it is in Windows though... See [JSON IPC](https://mpv.io/manual/master/#json-ipc) and [FIFO](https://mpv.io/manual/master/#options-input-file).
