### ISSUE TITLE
MPD Support

### ISSUE THREAD

**Issue by gthieleb** [streamlink/streamlink#1430]
I would like to use streamlink in conjunction with mpd (Music Player Daemon [1]).

For this to work streamlink should only perform the extraction job. Extracting I mean the mp3/vorbis/aac stream url (perhaps redirect url) from an m3u, pls, whatever playlist format.

The stream url could then be used as mpd input (via mpc add) either local or remote (by using the MPD_HOST environment).

Question: Is this a valid feature of streamlink? Is radio supported at all? Is browse/search of channels supported via the streamlink api?

[1] https://www.musicpd.org/

**Comment by bastimeyer** [comment]
> Extracting I mean the mp3/vorbis/aac stream url (perhaps redirect url) from an m3u, pls, whatever playlist format

See the [`--stream-url`](https://streamlink.github.io/cli.html#cmdoption-stream-url) parameter.

> Is radio supported at all?

I'm not sure if I understand this correctly, but if a stream does only contain audio, then yes, *radio* is supported.

> Is browse/search of channels supported via the streamlink api?

No, it is not Streamlink's job to browse or search channels or stream sources. You have to write a wrapper script/application if you want to do this.

**Comment by gthieleb** [comment]
@bastimeyer thanks for your answer. Do you recommend some further library for the browsing/searching part?

**Comment by bastimeyer** [comment]
This entirely depends on what you are trying to achieve. All that Streamlink requires is an input URL which matches one of its plugins. How you get this URL in your wrapper script/application is up to you. The options are endless here.

I guess this thread can be closed now...
