### ISSUE TITLE
VLC player/ MPV player doesn't launch to play the stream.

### ISSUE THREAD

**Issue by jameszue** [streamlink/streamlink#1431]
----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I am trying to play a downloaded stream but VLC doesn't launch after the stream downloads.
I have removed the # sign from : C:\Program Files (x86)\VideoLAN\VLC\vlc.exe in the config file at %APPDATA%\streamlink\streamlinkrc .

Is there a location of the output from where I could try to manually play the stream? 

Thanks for your help!
...

### Expected / Actual behavior
VLC player/ MPV player should play the stream after download.
...

### Environment details

Operating system and version:  Windows 10
Streamlink and Python version: streamlink-0.9.0
Players : vlc-2.2.8-win32, VLC nightly 3.0.0 , MPV player mpv-x86_64-20180112-git-2d6fdcc
...

### Comments, logs, screenshots, etc.

C:\Windows\system32>Streamlink.exe --schoolism-email XXX --schoolism-password XXX --schoolism-part 3 -v "https://www.schoolism.com/watchLesson.php?type=st&id=225" worst -o "Lesson 1.mp4"
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=225
[plugin.schoolism][info] Attempting to play lesson Part 3
[cli][info] Available streams: 480p (worst), 1024p (best)
[cli][info] Opening stream: 480p (hls)
[download][Lesson 1.mp4] Written 172.3 MB (4m33s @ 671.8 KB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by bastimeyer** [comment]
> I am trying to play a downloaded stream but VLC doesn't launch after the stream downloads.

Streamlink doesn't launch any player process when using the `-o` parameter. If you're writing a stream to the filesystem, you have to open that file in your player afterwards.
https://streamlink.github.io/cli.html#cmdoption-o

> I have removed the # sign from : C:\Program Files (x86)\VideoLAN\VLC\vlc.exe in the config file at %APPDATA%\streamlink\streamlinkrc

This is redundant, as this exact path (default VLC installation path) will be used by default.
https://github.com/streamlink/streamlink/blob/0.9.0/src/streamlink_cli/utils/player.py#L15-L31

> Is there a location of the output

If you don't specify a directory in the `-o` parameter (just a file name), then the current directory will be used, which in your case is `C:\Windows\system32`. The Streamlink installers on Windows add Streamlink's installation directory to your system's `PATH` environment variable, which means that you're able to call `streamlink` (or `streamlink.exe`, if you prefer that) from every directory of your system. So either `cd` into the intended directory or explicitly set it in the `-o` param like this `-o 'C:\foo\bar\baz.mp4'`.

**Comment by jameszue** [comment]
> Streamlink doesn't launch any player process when using the -o parameter.

Oh yes, as -o is a record function.

> If you don't specify a directory in the -o parameter (just a file name), then the current directory will be used, which in your case is C:\Windows\system32

Ah, I see. Thank you for the insight. However , wasn't able to find the downloaded file in that folder for some reason.


> explicitly set it in the -o param like this -o 'C:\foo\bar\baz.mp4'

This worked perfectly. Many Thanks @bastimeyer !

Is it possible to download the multiple parts of the stream (Part 1, part 2) automatically, one after the other in streamlink, with a code? Or is changing the 'part' name of the stream, the best way forward for downloading each part.

**Comment by bastimeyer** [comment]
Just execute Streamlink twice. You can do this in an interactive shell by simply executing two commands (`command1; command2; command2`) or by writing a shell script that translates parameters to multiple Streamlink commands.

Example in bash, which will run streamlink sequentially for each parameter (many input URLs):
```bash
#!/usr/bin/env bash
for url in "${@}"; do
  file="${HOME}/downloads/$(date +"recording_%Y%m%d%H%M%S.mp4")"
  streamlink -o "${file}" "${url}" best
done
```

On Windows, you need to write your own script in powershell or batch or install bash.

**Comment by jameszue** [comment]
> Example in bash, which will run streamlink sequentially for each parameter (many input URLs):

Thank you for the solution. Can you kindly explain how to implement it in a batch file. I only use Windows & I am, sadly, not much of a programmer.

**Comment by gravyboat** [comment]
@jameszue Unfortunately not, this is outside the kind of support we can reasonably provide to users. You'll have to do some research on your own.
