### ISSUE TITLE
Windows 0.9.0 hls-start-offset not being respected [Twitch]

### ISSUE THREAD

**Issue by LupusNoctis** [streamlink/streamlink#1433]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [X] I have read the contribution guidelines.

### Description
Attempting to start a Past Broadcast via Twitch URL at a specified time, VLC starts playback at start of VOD no matter what time offset is attempted.

Also for some reason, when loglevel=debug  is specified in  streamlinkrc   the expected output is not in the CMD window where the streamlink commandline was entered.
...

### Expected / Actual behavior
Playback should start at the indicated timestamp, much like direct twitch timestamp URLs would do
...

### Reproduction steps / Explicit stream URLs to test

1. https://www.twitch.tv/videos/218493234?t=07m37s
(player starts at expected timestamp)
2. running CMD:>>  streamlink https://www.twitch.tv/videos/218493234 Best -hls-start-offset=00:07:37 
(VLC then starts at beginning of VOD)

### Environment details

Operating system and version: Win10 x64 1709
Streamlink and Python version: 0.9.0 Windows Binary install (no other python installs)

...

### Comments, logs, screenshots, etc.
I cannot seem to locate the debug output in this configuration, pls halp with windows client debugging?
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> 0.9.0
> hls-start-offset

This feature has just been merged (#1303, 225193baf8b6f71ea57b276ef0fa869efd2a35e3) and was not yet included in the main 0.9.0 release. The documentation always shows the latest version on the master branch. This needs to be improved in the future.
If you want to use this feature, please try the nightly builds or install Streamlink from the master branch of the git repo.

> Also for some reason, when loglevel=debug is specified in streamlinkrc the expected output is not in the CMD window where the streamlink commandline was entered.

This might be a problem of Windows' terminal application, which is just utterly bad. The output is written to stdout, so nothing special is going on here.

**Comment by LupusNoctis** [comment]
I did also attempt this after running one of the nightly build installers (streamlink-0.9.0-20180114.exe)  but I didn't perform a clean install before hand.  I cleaned up the install and went back to the main 0.9.0 package for further reproductions.
Also took a few attempts to discover that the winCMD doesn't like --parameters  (wanted only single-dash).
Is there a guide handy for building from the master repo on the Windows platform?

**Comment by skulblakka** [comment]
>Is there a guide handy for building from the master repo on the Windows platform?

I would recommend installing a current version of python with pip on your machine and running
```pip install -U git+https://github.com/streamlink/streamlink.git```

**Comment by back-to** [comment]
**CMD**
```
C:\Users\user>streamlink https://www.twitch.tv/videos/218493234 best --hls-start-offset=00:07:37 --loglevel debug
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/218493234
[plugin.twitch][debug] Getting video HLS streams for cohhcarnage
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 2609
[stream.hls][debug] Start offset: 457; Duration: None; Start Sequence: 88; End Sequence: 2609
[stream.hls][debug] Adding segment 88 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 89 to queue
[stream.hls][debug] Adding segment 90 to queue
[stream.hls][debug] Adding segment 91 to queue
```

**PowerShell**
```
PS C:\Users\user> streamlink https://www.twitch.tv/videos/218493234 best --hls-start-offset=00:07:37 --loglevel debug
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/218493234
[plugin.twitch][debug] Getting video HLS streams for cohhcarnage
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 2609
[stream.hls][debug] Start offset: 457; Duration: None; Start Sequence: 88; End Sequence: 2609
[stream.hls][debug] Adding segment 88 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 89 to queue
[stream.hls][debug] Adding segment 90 to queue
[stream.hls][debug] Adding segment 91 to queue
```

without `--` before the command, it won't exist 

---

if you run the `streamlink-0.9.0-20180114.exe`

you will get asked where you want to install streamlink

```sh
# this was before 0.8.1 ...
Install for anyone using this computer.
```
```sh
# this was 0.9.0
Install just for me.
```

this was a bug #1340 so you might have two different versions installed

_How to uninstall an old version?_ https://github.com/streamlink/streamlink/issues/1391#issuecomment-354275115

use the `streamlink-0.9.0-20180114.exe` for the latest version.

---

> The documentation always shows the latest version on the master branch. This needs to be improved in the future.

#254
