### ISSUE TITLE
Streamlink for jailbroken iOS.

### ISSUE THREAD

**Issue by Spamm3r** [streamlink/streamlink#1434]
So is there an possibility to create an port for streamlink for iOS? I want to have it on my iOS 6.1.3 iPad Mini.
Is this even possible to achieve?

**Comment by gravyboat** [comment]
Nope. The code would have to be entirely rewritten in a different language to support this.

**Comment by bastimeyer** [comment]
You can still run Streamlink from your x86 based computer in the same network and use the `--player-external-http` parameter:
https://streamlink.github.io/cli.html#cmdoption-player-external-http
https://streamlink.github.io/cli.html#cmdoption-player-external-http-port

Then you're able to watch streams on any device using the progressive http stream of Streamlink, which should be supported by VLC on Android and iOS.

**Comment by gravyboat** [comment]
Good point @bastimeyer!
