### ISSUE TITLE
Need help for using it command not found

### ISSUE THREAD

**Issue by jirat-sumitanun** [streamlink/streamlink#1437]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I clone it and setup then add Streamlink's installation directory to the system's PATH environment variable. 
but when I open git bash and type streamlink https://www.pscp.tv/w/1nAKEWYwPkaJL best
it keep display bash : streamlink : command not found
screensot in ### Comments, logs, screenshots, etc.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: windows10 Pro
Streamlink and Python version: Streamlink(0.9.0) python 3.6

...

### Comments, logs, screenshots, etc.
https://imgur.com/FPhvX3d
https://imgur.com/cyWRa7R
https://imgur.com/vzOGCSr

**Comment by back-to** [comment]
this is the **default path** from the installer

```
C:\Program Files (x86)\Streamlink\bin
```

but you used `pip` so you will need to find the folder
where your streamlink got installed and select the `bin` file

**Comment by jirat-sumitanun** [comment]
Thank I pip it again and found it in python folder
