### ISSUE TITLE
Periscope: Could not open stream HLSStream, but HLS variant playlist directly succeeds

### ISSUE THREAD

**Issue by prech** [streamlink/streamlink#1438]
When loading live Periscope streams (archived/saved videos stream worked well without issue), I've recently encountered this error every time:

> streamlink https://www.pscp.tv/w/1MYGNjnkkBZGw?channel=sporting-green
[cli][info] Found matching plugin periscope for URL https://www.pscp.tv/w/1MYGNjnkkBZGw?channel=sporting-green
[cli][info] Available streams: replay (worst, best)
[cli][info] Opening stream: replay (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://prod-video-ap-southeast-2.periscope.tv/NQAp9dKjjTHgPqpT2JHARL75vd8T8nQxsMYlZWwJAbQqM7n3JS945oO1ExWxcUZyJ9UPKXYImGolqfXuD9n6vg/live/ap-southeast-2/master_hlsproducer.m3u8')> (Could not open stream: Attempted to play a variant playlist, use 'hlsvariant://https://prod-video-ap-southeast-2.periscope.tv/NQAp9dKjjTHgPqpT2JHARL75vd8T8nQxsMYlZWwJAbQqM7n3JS945oO1ExWxcUZyJ9UPKXYImGolqfXuD9n6vg/live/ap-southeast-2/master_hlsproducer.m3u8' instead)
error: Could not open stream <HLSStream('https://prod-video-ap-southeast-2.periscope.tv/NQAp9dKjjTHgPqpT2JHARL75vd8T8nQxsMYlZWwJAbQqM7n3JS945oO1ExWxcUZyJ9UPKXYImGolqfXuD9n6vg/live/ap-southeast-2/master_hlsproducer.m3u8')>, tried 1 times, exiting

> streamlink hlsvariant://https://prod-video-ap-southeast-2.periscope.tv/NQAp9dKjjTHgPqpT2JHARL75vd8T8nQxsMYlZWwJAbQqM7n3JS945oO1ExWxcUZyJ9UPKXYImGolqfXuD9n6vg/live/ap-southeast-2/master_hlsproducer.m3u8
[cli][info] Found matching plugin hls for URL hlsvariant://https://prod-video-ap-southeast-2.periscope.tv/NQAp9dKjjTHgPqpT2JHARL75vd8T8nQxsMYlZWwJAbQqM7n3JS945oO1ExWxcUZyJ9UPKXYImGolqfXuD9n6vg/live/ap-southeast-2/master_hlsproducer.m3u8
[cli][info] Available streams: 270p (worst), 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)

So essentially, the error instructs me to use the HLS variant M3U8 link directly, and that works well. Is there a simple fix to the Periscope plugin to recognize the HLS variant playlist and load that directly?

I've tried the latest stable build and the nightly, so the latest periscope.py plugin.

Thanks

**Comment by IsoaSFlus** [comment]
I got similar problem with my own plugin, and I successfully played that M3U8 link with streamlink directly, too. Did you find any way to deal with hlsvariant inside the plugin?

**Comment by pdyakov** [comment]
Same problem. Doesn't work with periscope link. Works with direct M3U8 link.

**Comment by IsoaSFlus** [comment]
@pdyakov  I have solved this problem, just use HLSStream.parse_variant_playlist().

**Comment by prech** [comment]
> @pdyakov I have solved this problem, just use HLSStream.parse_variant_playlist().

Great to hear, may I ask how to go about doing this -- what are the command line/flag parameters?

Thanks @IsoaSFlus

**Comment by IsoaSFlus** [comment]
@prech  There is a demonstrate [hinet.py](https://github.com/IsoaSFlus/streamlink/blob/master/src/streamlink/plugins/hinet.py).
