### ISSUE TITLE
Usage of streamlink from the API 

### ISSUE THREAD

**Issue by getpanoramic** [streamlink/streamlink#1439]
I'm trying to use streamlink as a python module, and I've been taking a look at the documentation
https://streamlink.github.io/api.html and https://streamlink.github.io/api_guide.html
But, I'm not finding an info on how to output the stream to a file, like I would do via cli with the `-o` or the `--output` arguments.
What is the method I could use to do that?

**Comment by back-to** [comment]
**streamlink** is just there to get the url / data
if you want to do something with this data, you will have to write the output part 

---

everything is in **streamlink_cli**
it's basically a second python module

https://github.com/streamlink/streamlink/blob/master/src/streamlink_cli/main.py
https://github.com/streamlink/streamlink/blob/master/src/streamlink_cli/output.py

**or**

use `subprocess` to run the cli command
https://docs.python.org/3.6/library/subprocess.html#subprocess.run
