### ISSUE TITLE
Plugin Youtube : error: No playable streams found on this URL

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#1440]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

After having done update with the latest build, I notice Youtube is no longer working.
I tested previous Youtube version, it's same. 

### Expected / Actual behavior

This is live channel currently on air.

`streamlink "https://www.youtube.com/watch?v=hL0sEdVJs3U"
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?
v=hL0sEdVJs3U
error: No playable streams found on this URL: https://www.youtube.com/watch?v=hL
0sEdVJs3U`

### Environment details

Operating system and version: Win 7 Pro
Streamlink and Python version: Streamlink portable nightlies build 0.9.0

### Comments, logs, screenshots, etc.

Even hosted videos don't work.

**Comment by back-to** [comment]
#1421 
#1423
