### ISSUE TITLE
No playable streams found for ongoing Youtube livestream(s)

### ISSUE THREAD

**Issue by usparvxj** [streamlink/streamlink#1441]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description

I've noticed this for the past few days. I've been trying to use Streamlink to view Ice Poseidon's livestreams on Youtube, but it always says the following: "error: No playable streams found on this URL: http://..."

https://www.youtube.com/channel/UCv9Edl_WbtbPeURPtFDo-uA/
https://gaming.youtube.com/ice_poseidon/live

Tried both of these URLs (the first one has definitely worked in the past)

It also gives the same error if I try the 'direct' video URL, in the current case:
https://www.youtube.com/watch?v=XlFhJbHta5c

I also tried a different channel who is livestreaming, with this url https://www.youtube.com/channel/UCo_IB5145EVNcf8hw1Kku7w and this doesn't work either. So it seems Youtube livestreams aren't working, but Twitch etc are.

### Expected / Actual behavior

It to say there is a stream and ask which quality to view at

### Environment details

Operating system and version: Debian Stretch
Streamlink and Python version: Streamlink 0.9.0 Python 2.7.14

**Comment by bastimeyer** [comment]
#1421
#1423
