### ISSUE TITLE
Schoolism plugin

### ISSUE THREAD

**Issue by rockmester** [streamlink/streamlink#1443]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Schoolism plugin seems to be working at first, it connects, but then fails.

### Environment details

Operating system and version: windows 10
Streamlink and Python version: 0.9.0

### Comments, logs, screenshots, etc.

streamlink --schoolism-email XXX --schoolism-password XXX --schoolism-part 2 URL best -o "2.mp4"

[cli][info] Found matching plugin schoolism for URL URL
[plugin.schoolism][info] Attempting to play lesson Part 2
[cli][info] Available streams: 480p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: URL (403 Client Error: Forbidden for url: https://www.schoolism.com/video-html/key.php)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/33/2/part2_hd.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://d2vcgbs9t7hqr9.cloudfront.net/33/2/part2_hd.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[End of Streamlink for Windows with ExitCode 1]

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
#1046
