### ISSUE TITLE
Live streams freeze after first few seconds

### ISSUE THREAD

**Issue by trade4599** [streamlink/streamlink#1444]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

This is in regards to livestream YouTube channels.  I use streamlink to write m3u8 files to an m3u playlist.   I followed the prior thread regarding "No playable streams found" with regards to YouTube streams, and it now produces an m3u8 file, but one that freezes almost immediately.  I edited youtube.py to the most recent edition in the "code" link.  When I use the m3u in a player such as Kodi, it shows the time elapsed/total time as something like 23:15:05/0:05 - in other words 23 hours, 15 minutes and 5 seconds of video played out of a total of 5 seconds.  For non-live stream YouTube channels, there seems to be no issue.

### Expected / Actual behvior

I have had no problem playing livestreams in the past - should get the livestream's m3u8 and play it appropriately.

### Reproduction steps / Explicit stream URLs to test

I am using a script (in ubuntu) to generate the m3u file I spoke of earlier.  An example of it is:

echo '#EXTINF:-1 tvg-name="Africanews" tvg-logo="http://www.mrteverett.com/TV/Congo_Africanews.png", group-title="news", Africanews' >>TVChannels.m3u

streamlink https://www.youtube.com/channel/UC1_E8NeF5QHY2dtdLRBCCLA/live --stream-url --best 1>>TVChannels.m3u

It wrote to the m3u file the following:

#EXTINF:-1 tvg-name="Africanews" tvg-logo="http://www.mrteverett.com/TV/Congo_Africanews.png", group-title="news", Africanews
https://manifest.googlevideo.com/api/manifest/hls_playlist/id/JkYQdcEHL6I.0/itag/95/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D136/hls_chunk_host/r2---sn-j5caxoxu-hh0e.googlevideo.com/playlist_type/DVR/ei/DA9kWqGLC4P28gSoybKACw/gcr/us/mm/32/mn/sn-j5caxoxu-hh0e/ms/lv/mv/m/pl/20/dover/8/keepalive/yes/mt/1516506791/ip/24.186.231.138/ipbits/0/expire/1516528492/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,ei,gcr,mm,mn,ms,mv,pl/signature/0E86AAD4D507E9F46DB40D38B4DDC7CDC7CB3BF6.12C119B1FE2566EA0410CFFFA4C3565BD377CC6D/key/dg_yt0/playlist/index.m3u8

Unfortunately, these m3u8 files change frequently which is why I run the script daily - the m3u8 above may expire by the time you read this.

### Environment details

Ubuntu 16.04 - but I've tried using Git Bash on Windows 7 too
I have streamlink 0.90 with an edited version of youtube.py...

### Comments, logs, screenshots, etc.

I have attached an image of the scenario when the m3u reads the m3u8 through Kodi for Euronews:
![untitled](https://user-images.githubusercontent.com/26032850/35191287-2ded57f6-fe45-11e7-9bd4-8422c007cf50.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by latel** [comment]
me too, you-get https://www.douyu.com/19223

**Comment by back-to** [comment]
It's just the time, when the youtube stream started

---

for the freeze

`streamlink https://www.youtube.com/channel/UC1_E8NeF5QHY2dtdLRBCCLA/live best -l debug --player-passthrough hls`

would be the same, because the player (Kodi) can't handle it.

---

you are **not using streamlink** at all, your player (**Kodi**) is **in charge of the stream**

**Comment by trade4599** [comment]
This was my point - I know the player is not using streamlink, but whatever player I use to play the m3u8 freezes quickly.

**Comment by back-to** [comment]
@Wishbringer 
**vlc** will freeze also with `--player-passthrough hls`
**mpv** won't freeze if you want to use `--player-passthrough hls`

---
@trade4599 

streamlink has options that will **help you to reload a playlist** better than some video players.

If you want that your player will do the same try to use **streamlink**

**or**

find the Issuetracker for your player and open a bug report there and see if they want to fix it or not.
