### ISSUE TITLE
Error douyu.com

### ISSUE THREAD

**Issue by latel** [streamlink/streamlink#1445]
streamlink https://www.douyu.com/3q3q source
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/3q3q
error: Unable to validate JSON: Unable to validate key 'data': '' does not equal None or Type of '' should be 'dict' but is 'str'

**Comment by back-to** [comment]
already fixed in #1394 

if you are on windows, you could install the `Development build`

https://streamlink.github.io/install.html#windows-binaries

or wait for

#1399
