### ISSUE TITLE
403 Client Error: Forbidden 

### ISSUE THREAD

**Issue by 10362227** [streamlink/streamlink#1446]
403 Client Error: Forbidden 
URL：https://gomostream.com/channel/57956
`streamlink --hls-segment-threads 5 "hlsvariant://https://freeuscache1.streamlive.to/edge/7uz4als3nigi0j3/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDE6Mjg6MDIgQU0maGFzaF92YWx1ZT1ZWXI0MDgydG95QTdUaGgvbmdGVU93PT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw" worst -p "D:\PotPlayerMini\PotPlayer.exe"`

error:
[cli][error] Unable to open URL: https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDY6MTg6MDEgQU0maGFzaF92YWx1ZT05NUNmclRmRW9hRy9HSms5TUx2alpnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuP
TIw (403 Client Error: Forbidden for url: https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDY6MTg6MDEgQU0maGFzaF92YWx1ZT05NUNmclRmRW9hRy9HSms5TUx2alpnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw)

**Comment by d0tfile** [comment]
Are you sure this is streamlink issue? I get 403 error when open this url.

**Comment by johnpolite** [comment]
It is not streamlink issue.

`
set agent="User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0"
set referer="Referer=https://paid.streamlive.to/embedplayer_putlive.php?width=640&height=400&channel=57956&autoplay=true"
set url="https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDc6NDI6MDggQU0maGFzaF92YWx1ZT1KS3RDdEhvS0IzbGxadGNkZUVjSDhnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw"
streamlink.exe --http-header %referer% --http-header %agent% hlsvariant://%url% best

`

`
C:\STREAMLINK>set agent="User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0"

C:\STREAMLINK>set referer="Referer=https://paid.streamlive.to/embedplayer_putlive.php?width=640&height=400&channel=57956&autoplay=true"

C:\STREAMLINK>set url="https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDc6NDI6MDggQU0maGFzaF92YWx1ZT1KS3RDdEhvS0IzbGxadGNkZUVjSDhnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw"

C:\STREAMLINK>streamlink.exe --http-header "Referer=https://paid.streamlive.to/embedplayer_putlive.php?width=640&height=400&channel=57956&autoplay=true" --http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0" hlsvariant://"https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDc6NDI6MDggQU0maGFzaF92YWx1ZT1KS3RDdEhvS0IzbGxadGNkZUVjSDhnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw" best
[cli][info] Found matching plugin hls for URL hlsvariant://https://freeuscache1.streamlive.to/edge/kjgkefh6la1di6g/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9MS8yMi8yMDE4IDc6NDI6MDggQU0maGFzaF92YWx1ZT1KS3RDdEhvS0IzbGxadGNkZUVjSDhnPT0mdmFsaWRtaW51dGVzPTMwJnN0cm1fbGVuPTIw
[cli][info] Available streams: 360p (worst, best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
`

https://s9.postimg.org/xp86qgue7/Screen_Shot.jpg
