### ISSUE TITLE
Plugin request: Tata.to

### ISSUE THREAD

**Issue by skilleek** [streamlink/streamlink#1447]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

Description
A plugin to catch streams from: https://www.tata.to/channel/sky-sport-1

I have found this [script](https://raw.githubusercontent.com/lastship/plugin.video.exodus/master/resources/lib/sources/de/tata.py) in case it is helpful. 

As always, many thanks for all your help!

**Comment by bastimeyer** [comment]
Sorry, but that's just another website with stolen content which we don't include here.

> Wenn Sie Kinofilme un TV Serien genauso mögen wie wir, dann sind Sie bei uns an richtiger Adresse. Denn auf tata.to können Sie Filme kostenlos online schauen werbefrei und ohne jegliche Anmeldung. Die Nutzung von unserem Streaming-Service ist für Sie anonym und völlig legal!

Nope, that's not *fully legal* at all, ridiculous claim...
