### ISSUE TITLE
Error: failed to create process

### ISSUE THREAD

**Issue by QeeWI** [streamlink/streamlink#1448]
### Checklist

- [x] This is a bug report.

### Description

When I try to start streamlink through the command line, I get an error "failed to create process".
In PATH streamlink there is.
I do not know how long this problem arose, because I use streamlink twitch gui.

### Environment details

Windows 10, 10.0.16299.192
Streamlink 0.9.0, Python 3.6.4 (and 3.5? in streamlink folder)

### Comments, logs, screenshots, etc.

![2018-01-23_141210](https://user-images.githubusercontent.com/35720134/35262492-7fe948a4-0047-11e8-899e-2352c1d86955.png)

**Comment by JonJaded** [comment]
I get this same issue too, where is your streamlink located?

I put it on my desktop and then it started working again.

**Comment by QeeWI** [comment]
C:\Users\123\AppData\Local\Streamlink - **Error**
C:\Users\123\Desktop\Streamlink - **Error**
C:\Program Files\Streamlink - **Error**

C:\Streamlink - **Working**

**Comment by JonJaded** [comment]
Yup, sometimes just keeping the location tree short helps.

Not sure why.

**Comment by JonJaded** [comment]
Lol now C:\streamlink giving me that stupid failed to create process again.

Losing my mind.

**Comment by QeeWI** [comment]
> did you install it twice ? exe and from pip ?
> Remove the double install.
Only exe.

**Comment by bastimeyer** [comment]
@QeeWI 
What's the output of
```batch
where streamlink
```
(shows you the resolved path of the executable when you "execute" the `streamlink` keyword)

**Comment by QeeWI** [comment]
![2018-02-04_013611](https://user-images.githubusercontent.com/35720134/35770355-f4cada04-094b-11e8-91c5-1c7c9926a2bc.png)
But now I already have no problem, I wrote above that after installing in C: folder everything began to work

**Comment by JonJaded** [comment]
Working again for me as well, thanks again.
