### ISSUE TITLE
Stream ended ,Closing currently open stream... How to fix that ?

### ISSUE THREAD

**Issue by xDyN** [streamlink/streamlink#1450]
This is my log when i use streamlink
`C:\Users\Luca\Desktop\New folder (2)\streamlink>streamlink https://www.youtube.com/watch?v=sMsYpOh-oT8 best -o "a.ts"
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=sMsYpOh-oT8
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[download][a.ts] Written 1.0 MB (0s @ 1.8 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...`

**Comment by johnpolite** [comment]
This is not live stream.

Download with youtube-dl and watch the video from hard disk.

C:\>youtube-dl.exe -v -F --no-check-certificate "https://www.youtube.com/watch?v=sMsYpOh-oT8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--no-check-certificate', 'https://www.youtube.com/watch?v=sMsYpOh-oT8']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.01.21
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.16299
[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] sMsYpOh-oT8: Downloading webpage
[youtube] sMsYpOh-oT8: Downloading video info webpage
[youtube] sMsYpOh-oT8: Extracting video information
[info] Available formats for sMsYpOh-oT8:
format code  extension  resolution note
140          m4a        audio only DASH audio  130k , m4a_dash container, mp4a.40.2@128k, 38.90MiB
160          mp4        256x144    144p  122k , avc1.4d400c, 30fps, video only, 30.59MiB
133          mp4        426x240    240p  286k , avc1.4d4015, 30fps, video only, 69.28MiB
134          mp4        640x360    360p  687k , avc1.4d401e, 30fps, video only, 166.49MiB
135          mp4        854x480    480p 1347k , avc1.4d401f, 30fps, video only, 308.08MiB
136          mp4        1280x720   720p 2716k , avc1.4d401f, 30fps, video only, 612.26MiB
298          mp4        1280x720   720p60 3550k , avc1.4d4020, 60fps, video only, 919.85MiB
137          mp4        1920x1080  1080p 4527k , avc1.640028, 30fps, video only, 1.19GiB
299          mp4        1920x1080  1080p60 5918k , avc1.64002a, 60fps, video only, 1.56GiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)

**Comment by xDyN** [comment]
When i setup streamlink version window ( .exe ) ! i can run , and stream from link youtube when they live ! But i get a issue is when i live , video ouput of me just is 480p

**Comment by xDyN** [comment]
This is my command:

> streamlink urlyoutubelive 720p -o - | ffmpeg -i - -c:v copy -c:a aac -ar 44100 -ab 128k -ac 2 -flags +global_header -bsf:a aac_adtstoasc -bufsize 5000k -f flv "rtmp://a.rtmp.youtube.com/live2/xxx"

>

**Comment by back-to** [comment]
>streamlink https://www.youtube.com/watch?v=sMsYpOh-oT8 best -o "a.ts"

**this works,**
maybe your internet connection is bad and the stream goes offline for you.

> video ouput of me just is 480p

could be https://github.com/streamlink/streamlink/issues/1158

> streamlink urlyoutubelive 720p -o - | ffmpeg -i - -c:v copy -c:a aac -ar 44100 -ab 128k -ac 2 -flags +global_header -bsf:a aac_adtstoasc -bufsize 5000k -f flv "rtmp://a.rtmp.youtube.com/live2/xxx"

you are restreaming a youtube video to youtube ?

---

**Closing, this issue makes no sense**, you are using 3 different commands without any context.
 
You will have to provide a **debug log** and **more details** about your final goal for support.

---

add `-l debug` to your streamlink command for a debug log

https://streamlink.github.io/cli.html#cmdoption-l
