### ISSUE TITLE
Vaughnlive changed IP's to break Streamlink

### ISSUE THREAD

**Issue by jshir** [streamlink/streamlink#1456]
This will be a very brief bug report... As of tonight the head vaughnlive.py references IPs which were disconnected by vaughn to thwart streamlinking. I've observed vaughn serving video now from "66.90.93.44","66.90.93.35" and have personally gotten it to work overwriting the IP's in rtmp_server_map with those two alternating. I would submit the commit but I think some more testing is needed as I only use streamlink with one occasional stream and don't know how far those IPs will get more frequent SL users.

 #1187 contains lengthy discussion on the history of the war vaughn has waged against streamlink, this is probably not the last time the IPs will change.

**Comment by gravyboat** [comment]
The question at this point is whether it's really worth maintaining the plugin. 99% of the content on Vaughn is stolen any way, so is it worth continuing? If someone wants to tackle it they can (I know @beardypig has been heading this up in the past), but I really don't care to keep wasting time on this site or a variety of others that are restreaming illegally.

**Comment by fadster** [comment]
@jshir These changes aren't made with the intention to break Streamlink. They are part of the ongoing migration to a HTML5-based player.

@gravyboat Why do you say it's stolen content? Most streams on the site's several subdomains are casts from personal cams. The casters send their streams directly to the vaughnlive servers. There are actually a bunch of other sites stealing streams from vaughnlive through unauthorized embeds.

The streaming server IPs have been changing frequently over the past few days. Currently, there is only one active server. Setting all entries in the `rtmp_server_map` to 66.90.93.36:1935 will resolve the issue until the next change, which could happen at any moment.

**Comment by gravyboat** [comment]
@fadster Last time I checked out the site there were a lot of restreams of news stations, cable broadcasts, sports events, etc. Maybe it has changed since then.

**Comment by karlo2105** [comment]
Is it possible to automate retrieving of rtmp server address ?

**Comment by e-ht** [comment]
@karlo2105 it should be. Seems like it could be retrieved on demand once, and only attempt another check if unable to contact again. I might fork and see what I can come up with.

**Comment by TVGPlayer** [comment]
I think it's easier to get vaughnlive now than before. Does anybody know how to use streamlink to get this streamlive? They just changed their codes. Thanks!

wss://freeeucache1.streamlive.to/edge/7yxirr4046nk5ca?wmsAuthSign=c2VydmVyX3RpbWU9Mi82LzIwMTggOTowOToxNSBQTSZoYXNoX3ZhbHVlPWk5dnhaOGUwYVJVdWd4dXpxbGFhclE9PSZ2YWxpZG1pbnV0ZXM9MjA=

**Comment by thinkpad4** [comment]
Any update on this?

**Comment by johnpolite** [comment]
If you want Fox News,

Change browser's user agent to iphone, get m3u8..

start mpv.exe -vf scale=854:480 https://clutch.vaughnsoft.net/ord/vl/newzviewz.m3u8

https://s14.postimg.org/4933v4a6p/Screen_Shot.jpg

**Comment by gravyboat** [comment]
@johnpolite I'm going to remove your comment as it refers to a direct way to watch stolen content and I don't want us to potentially get in trouble. In addition you should report this to the vaughnlive site owner so they can suspend that user for an illegal restream.

**Comment by johnthecracker** [comment]
Who knows what is legal or illegal on the internet?

Less spreading of fake news - Fox News, is not a bad idea though.

**Comment by johnpolite** [comment]
Fadster's proposal "Setting all entries in the rtmp_server_map to 66.90.93.36:1935" still works.

I have serious doubts that Streamlink is Vaugn's biggest problem.

**Comment by thinkpad4** [comment]
@johnpolite Can you show me how?  When I change it I get this [cli][info] Found matching plugin vaughnlive for URL vaughnlive.tv/aircrashmayda
y
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'live': True, 'playpath
': 'live_aircrashmayday', 'flv': '-', 'rtmp': 'rtmp://66.90.93.36:1935/live?U1L0
0gKds3mgk6p5Zr7pQ7GM1eGGESPi', 'pageUrl': 'http://vaughnlive.tv/aircrashmayday'}
, redirect=False> (No data returned from stream)
error: Could not open stream <RTMPStream({'live': True, 'playpath': 'live_aircra
shmayday', 'flv': '-', 'rtmp': 'rtmp://66.90.93.36:1935/live?U1L00gKds3mgk6p5Zr7
pQ7GM1eGGESPi', 'pageUrl': 'http://vaughnlive.tv/aircrashmayday'}, redirect=Fals
e>, tried 1 times, exiting
[cli][info] Closing currently open stream...

**Comment by ringtvt** [comment]
@johnpolite  how to check ips? tks pls help me

**Comment by johnpolite** [comment]
streamlink.exe --stream-url %url% best

**Comment by thinkpad4** [comment]
Is this still broken?

**Comment by gravyboat** [comment]
@thinkpad4 Probably. No one has updated the plugin as far as I'm aware.

**Comment by thinkpad4** [comment]
Damn.  Ok, thanks

**Comment by techmouse** [comment]
Did the server map change?

It looks like the new IP could be 66.90.93.42, but I'm still getting time outs. So maybe I'm missing the port?

**Comment by TVGPlayer** [comment]
192.240.105.171:1935 is working for me now.

**Comment by techmouse** [comment]
@TVGPlayer  Right on! Thanks man!

**Comment by TVGPlayer** [comment]
@techmouse Email me at bikiniscout@yahoo.com.
