### ISSUE TITLE
Working on Zattoo recordings

### ISSUE THREAD

**Issue by matthiasschulenburg** [streamlink/streamlink#1458]
Hi, according to #1263 request it would be great if streamlink works also on recordings in Zattoo. Trying Zattoo's url in streamlink results doesn't work on recordings. Eg

Streamlink.exe --zattoo-email="email@example.de" --zattoo-password="example" --output kultnacht.mp4 "https://zattoo.com/watch/zdf/133124024-die-zdf-kultnacht-das-beste-aus-der-hitparade/103203586/1514676000000/1514685000000/-287055" best

results in a file containing an episode from day before. Not the recording. Tried the zattoo.py refered from #1263 but doesn't work better.

Thanks & Regards
Matthias

**Comment by gravyboat** [comment]
Why open a new issue instead of commenting on the existing one? I'm going to mark this as a duplicate, please comment in the other thread.
