### ISSUE TITLE
Pscp.tv plugin request

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1460]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

A simple plugin request for PSCP.TV
Today with the lunar eclipse I visited this example page below and found this new website with live content. Nasa is broadcasting through this platform.

Example: https://www.pscp.tv/w/1OyKAdjzbowxb?channel=mission-space

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. https://www.pscp.tv/w/1OyKAdjzbowxb?channel=mission-space
2. ...
3. ...

### Environment details

Operating system and version: Windows 10
Streamlink and Python version: 0.10.0, 2.7.12

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/periscope.py

**Comment by Twilight0** [comment]
Thank you, I overlooked it.
