### ISSUE TITLE
HLS Seeking Not Working for Live Streams

### ISSUE THREAD

**Issue by poldon** [streamlink/streamlink#1461]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Specifying the new --hls-start-offset and --hls-live-edge command-line arguments has no effect.  The video still plays from the current live timestamp.

### Expected / Actual behavior

The live video should start from some time in the past, but it starts at the current time.  For example, a live feed will have the current time displayed on-screen (about a minute behind actual time normally).  When specifying the arguments, the time will be the same current time no matter how much offset is requested.

### Reproduction steps / Explicit stream URLs to test

1. Specify either --hls-start-offset and --hls-live-edge flags as desired.
2. Notice the live stream picks up at the current time always.

Some URLs:
- http://play-prod1.live.anvato.net/server/play/cbslocal-kmax-dfp/master.m3u8
- https://abclive1-lh.akamaihd.net/i/abc_live10@420897/master.m3u8

### Environment details

Operating system and version: Windows 10 x64 & Ubuntu 16.04
Streamlink and Python version: streamlink 0.10.0 (& master), Python 2.7.12

...

### Comments, logs, screenshots, etc.

I have tried several stream URLs and on both Windows and Linux.  Thanks for looking into this!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
you can try `--hls-live-restart`
> Skip to the beginning of a live stream, or as far back as possible.

https://streamlink.github.io/cli.html#cmdoption-hls-live-restart

but this only works for a playlist url with replay option

like https://www.youtube.com/watch?v=XOacA3RYrXk

your playlist url does not support replays

**Comment by poldon** [comment]
How do I know if a stream supports seeking?  Every stream I've tried (~20 so far) won't seek with the --hls-start-offset or --hls-live-edge or --hls-live-restart (including the ones I mentioned above).

**Comment by back-to** [comment]
@poldon 

**the website must support it**,

like in https://www.youtube.com/watch?v=XOacA3RYrXk you can go back 4h

if there is just a livestream, without going back it won't work.

**Comment by scottbernstein** [comment]
Most sites do not support it -- especially if they are "live".


The way you can tell is that you can "rewind" the live video in the player on the site.  Being able to rewind a live video of an HLS stream in your web browser indicates that you can likely use the seeking functionality

________________________________
