### ISSUE TITLE
Kanal7, dogan (teve2) plugins defective!

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#1463]
Hi beardypig,

kanal7 and teve2 (dogan.py) are not working since 1 month ago.

ecanlitvizle from the canlitv.py needs a little fix too (changing ecanlitvizle.net to ecanlitvizle.tv)

Hope you will read here :)

Greetings
rotarum

**Comment by mike8032** [comment]
hi, ecanlitvizle has changed the domain again and is now known as https://www.ecanlitvizle.live/
in this case canlitv.py needs to be altered again.

**Comment by dreamboxco** [comment]
i cant see anything from the website https://www.ecanlitvizle.live/ 
You do not have permission to acces this content

**Comment by Rotarum** [comment]
This has nothing to do with my thread!

Why do you spam here and in the other issue threads too? @dreamboxco

**Comment by dreamboxco** [comment]
Kanal 7 und teve2 zeigen wieder
