### ISSUE TITLE
Python: Streamlink dropping most frames of YouTube livestream 

### ISSUE THREAD

**Issue by shahar603** [streamlink/streamlink#1464]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I'm trying to get frames from a YouTube livestream to a python program using Streamlink and OpenCV.
Last week (Or maybe ever earlier) it stopped working properly.
Instead of getting continues frames from the _VideoCapture_ object, I get about 150 frames, then a pause of 10-15 seconds ( `cap.read()` hangs ) and then another 150 frames from the current point of the stream. 

Regular YouTube videos work properly.

**What I've tried so far**

- I've tried the solutions offered in issue #1421. When the issue described above started, the command line version of Streamlink stopped working as described in issue #1421. Modifing the youtube.py file fixed the issue with the command line version but did not affect the python version.

- I've tried reinstalling OpenCV and Streamlink. It didn't change anything.

### Expected / Actual behavior
Getting continues frames from the livestream using the `read` function of the _VideoCapture_ object.

### Reproduction steps / Explicit stream URLs to test

1. Any stream. Ex: [https://www.youtube.com/watch?v=wwMDvPCGeE0](https://www.youtube.com/watch?v=wwMDvPCGeE0)
2. The stream or quality used is irrelevent.
3. This python script demonstrates the problem:

```
import streamlink
import cv2

url = 'https://www.youtube.com/watch?v=wwMDvPCGeE0'

streams = streamlink.streams(url)
cap = cv2.VideoCapture(streams["best"].url)

while True:
    ret, frame = cap.read()

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) & 0xff == ord('q'):
        break
```

### Environment details

Operating system and version: Windows 10 Home 64 bit
Streamlink and Python version: 

- Python 3.5.1 32 bit
- Streamlink 0.10.0

### Comments, logs, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
**you are not using streamlink**

`streams["best"].url` is the **direct link from youtube**

https://github.com/streamlink/streamlink/issues/1444

---

there is already an issue for opencv https://github.com/streamlink/streamlink/issues/1386

**Comment by gargdevesh6** [comment]
The following code is working for live youtube streams but I want to use the following code for for a live video stream from my ip_webcam.

import streamlink
import cv2

url = 'http://192.168.43.1:8080/'

streams = streamlink.streams(url)
cap = cv2.VideoCapture(streams["best"].url)

while True:
    ret, frame = cap.read()

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) & 0xff == ord('q'):
        break

It gives an error like this

File "testing2.py", line 6, in <module>
    streams = streamlink.streams(url)
  File "C:\Python27\lib\site-packages\streamlink\api.py", line 13, in streams
    return session.streams(url, **params)
  File "C:\Python27\lib\site-packages\streamlink\session.py", line 436, in streams
    plugin = self.resolve_url(url)
  File "C:\Python27\lib\site-packages\streamlink\utils\__init__.py", line 196, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "C:\Python27\lib\site-packages\streamlink\session.py", line 413, in resolve_url
    raise NoPluginError
streamlink.exceptions.NoPluginError

Please help me to fix this error

**Comment by beardypig** [comment]
@gargdevesh6 don't highjack old thread, please create new ones. You can access your IP cam using `opencv` directly, there is no need to use `streamlink` - `streamlink` doesn't support any IP cams anyway.
