### ISSUE TITLE
plugin request livejasmin.com

### ISSUE THREAD

**Issue by justlookingaround12** [streamlink/streamlink#1465]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Hey all, i really like whats supported so far but i'd like to request one more. livejasmin.com, if it's at all possible i think it would be a useful add as their website is incredibly slow and buggy.

**Comment by gravyboat** [comment]
Sorry but we've discussed this several times recently and we're not going to support any more cam sites. The users of the existing plugins of this type have been extremely rude and demanding. Supporting one lead to a flood of many more requests for such plugins which we're not willing to deal with.
