### ISSUE TITLE
SLDP Websocket based streaming protocol

### ISSUE THREAD

**Issue by saunaants** [streamlink/streamlink#1466]
http://blog.wmspanel.com/2017/06/sldp-streaming-protection.html

https://softvelum.com/player/web/

New protocol that cant be downloaded

**Comment by johnpolite** [comment]
What website are you talking about "cant be downloaded" ?

**Comment by back-to** [comment]
@saunaants 

you will have to provide some example websites that uses this.

**Comment by Gujal00** [comment]
http://tvsod.tv/player?tv_id=158
