### ISSUE TITLE
cybergame.tv plugin not work for livestreams

### ISSUE THREAD

**Issue by flijloku** [streamlink/streamlink#147]
`[cli][info] Found matching plugin cybergame for URL http://cybergame.tv/sharkisfinetoo/`
`[cli][info] Available streams: 720p (worst, best)`
`[cli][info] Opening stream: 720p (rtmp)`
`[cli][error] No data returned from stream`
For stream http://cybergame.tv/<streamername> Internet Download Manager  produces a link like rtmp://cybergametv.cdnvideo.ru/cybergame//<streamername>.VODs fine.

**Comment by beardypig** [comment]
Does that stream URL work? I could not get it to work. 

With some wiresharking I managed to get it working with `rtmp://stream1.cybergame.tv:2936/live/<channel>`.

**Comment by flijloku** [comment]
Yes it work.

**Comment by beardypig** [comment]
OK, that's weird ... maybe they change it frequently? 

I found the RTMP URL in the end, it was in `http://api.cybergame.tv/p/embed.php?c=<channel>&type=embed&w=100pc&h=100pc&auto=true&advforced=true&nick=` eg. http://api.cybergame.tv/p/embed.php?c=op-mizantrop&type=embed&w=100pc&h=100pc&auto=true&advforced=true&nick=

**Comment by flijloku** [comment]
![111](https://cloud.githubusercontent.com/assets/14862821/20174529/acb3f8d8-a757-11e6-86ee-b605e7034cf4.JPG) - maybe it help? view-source:http://api.cybergame.tv/p/embed.php?c=ebrellika&type=embed&w=100pc&h=100pc&auto=true&advforced=true

**Comment by beardypig** [comment]
That's what i was referring to :)

**Comment by flijloku** [comment]
Sorry. I do not know much English:)

**Comment by beardypig** [comment]
No problem :D 

I will check it over the next few days as see if it changes, and make the necessary changes to the plugin.

**Comment by flijloku** [comment]
OK! Thanks!

**Comment by beardypig** [comment]
@flijloku I have created a PR to fix this, using that new RTMP URL (#163).

**Comment by flijloku** [comment]
@beardypig  Thanks for your work!
