### ISSUE TITLE
http headers cookie from file

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#1470]
Hi

Is it possible to load http haders from file? The reason i ask is because im using a site where the cookie changes often and it would be easier if i could read cookie from file mysql or remote url somehow.

This way i could create php script to keep file put contents into text file or to update mysql with new cookie often.

Thanks

**Comment by back-to** [comment]
**creating a streamlink plugin is probably easier** than doing this workaround with php/mysql

but it's already posible

---

- global config
https://streamlink.github.io/cli.html#configuration-file

- custom config
https://streamlink.github.io/cli.html#cmdoption-config

- http-cookies
https://streamlink.github.io/cli.html#cmdoption-http-cookie

---

in config file
```
http-cookie=foo=bar
http-cookie=bar=ff
```
will be in streamlinks http session
```
<RequestsCookieJar[<Cookie bar=ff for />, <Cookie foo=bar for />]>
```

**Comment by willbrow** [comment]
Thanks this is great will test tonight.

If i changed the cookie in the config file would streamlink start using that or would i uave to reload streamlink to use new cookie

**Comment by back-to** [comment]
it will only read the cookies at the start,
if you need new cookies in the middle you will have to reload streamlink

**Comment by willbrow** [comment]
Yeah cookie becomes invalid after certain ammount of time and stream will then not be received.

Is there option to automaticly reload if stream fails that could be used as work arround for me.

**Comment by back-to** [comment]
i have a session reload command for **hls streams**,

but without #1432 merged i would break my own pr :walking_man:

**Comment by willbrow** [comment]
With the session reload command this would then reload the cookie from file is that right ?

Ive read the link but i cant find the session reload command ?

Thanks for all your help btw its apreshiated

**Comment by bastimeyer** [comment]
I'm closing the thread, since the original question has been answered, thanks @back-to. The mentioned feature can be discussed in the appropriate thread if a PR has been submitted...
