### ISSUE TITLE
Update the release script with installation instructions as well as opencollective

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1471]
TODO for me (so I don't forget):

- Update release script with installation instructions (release notes)
- Add OpenCollective links

**Comment by back-to** [comment]
_reopen_

https://github.com/streamlink/streamlink/blob/f12becfffa14c53e9301ca6a40ec14ce4b3012b0/script/release.sh#L84-L101

markdown doesn't work for https://streamlink.github.io/changelog.html

**Comment by cdrage** [comment]
@beardypig @back-to thanks for catching on, I'm so used to writing in markdown.. I'll switch it to RST in a separate PR :+1:

**Comment by bastimeyer** [comment]
Can't we just add another parser for markdown to the sphinx/docutils config?
https://github.com/rtfd/recommonmark

**Comment by beardypig** [comment]
Yep, I was looking in to that too. There are some things we could improve in the release process, I was going to create an issue with some suggestions :)

**Comment by back-to** [comment]
https://streamlink.github.io/changelog.html is fixed in https://github.com/streamlink/streamlink/pull/1667
