### ISSUE TITLE
[youtube] error: No playable streams found

### ISSUE THREAD

**Issue by c769214** [streamlink/streamlink#1472]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Logs
streamlink --loglevel debug https://www.youtube.com/watch?v=vE58KB1AoiA 
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=vE58KB1AoiA
error: No playable streams found on this URL: https://www.youtube.com/watch?v=vE58KB1AoiA

Happens on other youtube live stream link

**Comment by gravyboat** [comment]
This was fixed on https://github.com/streamlink/streamlink/issues/1421 and https://github.com/streamlink/streamlink/pull/1423, you need to install the latest version of Streamlink (https://github.com/streamlink/streamlink/releases/tag/0.10.0), you may need to uninstall the old version and then reinstall the new version. I can't duplicate this.
