### ISSUE TITLE
Typo in -h under Stream transport options

### ISSUE THREAD

**Issue by JulioBBL** [streamlink/streamlink#1473]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

In the -h text there is a typo under Stream transport options, more specifically in the description of the --ffmpeg-video-transcode option.

### Expected / Actual behavior

It reads "Muxing" instead of "Mixing"

### Reproduction steps / Explicit stream URLs to test

`~ streamlink -h`

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
"Muxing" stands for multiplexing...
See https://en.wikipedia.org/wiki/Multiplexing#Video_processing

However, there are several (many) other spelling and grammar errors or bad phrasings in general which need to get fixed.
