### ISSUE TITLE
watch.rugbypass.com [Plugin Issues]

### ISSUE THREAD

**Issue by streameratwsrtv** [streamlink/streamlink#1477]
Hi i have a rugbypass.com account i want to no the command line to get m3u8 because i think it needs auth. please help me as i am not a developer. thanks

**Comment by karlo2105** [comment]
It's already covered. All you have to is to put Rugbypass credentials into following commands.

`streamlink --neulion-username=user --neulion-password=password "https://www.rugbypass.com/live/six-nations/scotland-vs-france-at-bt-murrayfield-on-11022018/2018" best`

**Comment by streameratwsrtv** [comment]
not work does it have to be email instead of username

**Comment by streameratwsrtv** [comment]
C:\Users\xxxx\Desktop\streamlink\Streamlink.exe streamlink --neulion-username=xxxxxx@gmail.com --neulion-password=xxxxx "https://www.rugbypass.com/live/six-nations/scotland-vs-france-at-bt-murrayfield-on-11022018/2018" best

**Comment by streameratwsrtv** [comment]
i put that in cmd

**Comment by streameratwsrtv** [comment]
[Streamlink for Windows v0.9.0 - Git f6708f1]
usage: Streamlink.exe [OPTIONS] <URL> [STREAM]
Streamlink.py: error: unrecognized arguments: --neulion-password=xxxx http:/
/watch.rugbypass.com/game/day2-at-brisbane-10s-on-02092018 best
[End of Streamlink for Windows with ExitCode 2]

Type another command or EXIT to end:

**Comment by back-to** [comment]
install version `0.10.0`

https://github.com/streamlink/streamlink/releases/tag/0.10.0

https://streamlink.github.io/install.html
