### ISSUE TITLE
Choosing H265 Output Codec

### ISSUE THREAD

**Issue by aviatoraway1** [streamlink/streamlink#1478]
Is there a way to output a H265 codec when recording through streamlink? I am trying to record some streams through twitch and would like to use H265 instead of the default. H265 saves about 65% file size vs the default.  Here is an example batch file that I use.

``streamlink https://www.twitch.tv/USER best --twitch-disable-hosting --ffmpeg-video-transcode h265 -o E:\Recs\Rec.mp4``

This does not seem to work, even though it would seem it would through the docs. Any hints?

**Comment by beardypig** [comment]
@bastimeyer going a bit off-topic, but I'd be interested to read about the industry killing h265, is there a news article about it?

**Comment by bastimeyer** [comment]
@beardypig 
http://blog.chiariglione.org/2018/01/28/
The founder of the MPEG has realized that their HEVC licencing model is bad and he's complaining about open source software development and the royalty free AV1 of the AOmedia, which the industry has shifted to. This post is the reaction to Apple joining AOmedia, as one of the last remaining tech giants, which might have killed the MPEG...
http://aomedia.org/aom-in-the-news/
