### ISSUE TITLE
Channel name update tf1

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#1479]
hi, they have been changing channels name, I thought just pointing to the new url would work but it doesn't

streamlink "https://www.tf1.fr/tfx/direct" best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tfx/direct
error: Unable to open URL: http://www.wat.tv/get/tfxlive/591997 (403 Client Error: Invalid delivery format. for url: http://www.wat.tv/get/tfxlive/591997?getURL=1)

(tfx is the replacement for nt1, nt1 was working fine till yesterday)

Also HD1 became https://www.tf1.fr/tf1-series-films/direct and no plugin can handle this url

`streamlink "https://www.tf1.fr/tf1-series-films/direct" best
[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: https://www.tf1.fr/tf1-series-films/direct
`

see https://github.com/streamlink/streamlink/issues/376 

update: the old url https://www.tf1.fr/nt1/direct still works

streamlink "https://www.tf1.fr/nt1/direct" best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/nt1/direct
[cli][info] Available streams: 64k (worst), 440k, 496k, 696k, 840k, 896k, 1240k (best)
[cli][info] Opening stream: 1240k (hls)

**Comment by melmorabity** [comment]
A pull request which handle TF1 channel renamings is under review: https://github.com/streamlink/streamlink/pull/1457

**Comment by campones** [comment]
good to hear, thanks

**Comment by gravyboat** [comment]
Closing since #1457 is merged.
