### ISSUE TITLE
M3U8 stream convert for VLC

### ISSUE THREAD

**Issue by iorange88** [streamlink/streamlink#1482]
Hi guys,

I want to ask you if there is a way to simple convert/transcode actual m3u stream to m3u8. I`m using VU boxes with VTI software. I want to stream my own payed TV channel over internet to my work PC or cellphone. M3U8 is much more effective for upload. So in fact I need less speed on upload than with normal m3u. Thanks John

**Comment by back-to** [comment]
m3u and m3u8 are basically the same.

**streamlink is not the software you are looking for**

---

You could try to find a solution with https://ffmpeg.org/

or

search on the VU+ forums, there might be an easy solution
