### ISSUE TITLE
plugin request onlinetvcanli.com

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#1483]
### Checklist

- [x ] This is a feature request.

### Description

On the page  https://onlinetvcanli.com/ are good streams played, could you please see if you could provide it as a plugin for the Livestreamer 

### Expected / Actual behavior

Watch livestream over livestreamers

**Comment by gravyboat** [comment]
Unless they have evidence of having legal licenses to restream many of these TV broadcasts we won't be able to add this site.

**Comment by dreamboxco** [comment]
How do you know that exactly?

**Comment by gravyboat** [comment]
I don't, that's why I asked about it. I just went to the site, saw that half of their front page is US/EU TV sites and couldn't find anything about them licensing with a quick Google search.

**Comment by dreamboxco** [comment]
you can read it here https://onlinetvcanli.com/gizlilik-ve-telif-hakki

With regard to copyright, "TURKISH RADIO TELEVISION AUTHORITY" and "Information and Communication Technologies Authority Presidency" According to the information received by the broadcast unencrypted over terrestrial and satellite television channels regarding; According to Web TV conditions, it is stated that these broadcasts can be provided without any permission from any institution or channel without the permission of our subscriber and Tv Channels' embed codes free of charge on our site. In addition, the publisher channel can not claim any rights to the broadcasts directly without giving any play on the broadcasts, and in addition, if the broadcasts are not recorded according to the "Europe Broadcast Union" in the "FTA ie Free To Air" broadcasts and are broadcast directly without broadcasting. Direct transmission is carried out without any changes to the publications at onlinetvcanli.com. There are no publications that are strictly paid platforms.

You can get the necessary information by communicating through http://www.tk.gov.tr/ and http://www.rtuk.org.tr/. Responsibility of publications belongs to publishers. Logo and publishing rights belong to the producer. However, in case channel owners do not want us to access and broadcast their broadcasts, we will remove the broadcasts of related channels through our website.

**Comment by gravyboat** [comment]
We won't be able to support that site in this case. These sorts of notices mean basically nothing and could get us in trouble so I'm going to close this one. We're really trying to avoid adding additional sites that could be problematic.

**Comment by dreamboxco** [comment]
ah ok and how do you recognize that the site does not cause any problems? 
What is the difference to canli tv?

**Comment by gravyboat** [comment]
Typically sites that are streaming original content aren't an issue, those that require user login for paid content, etc. (basically not a restream of some other provider). There isn't much of a difference between canli tv and if it was up to me I would remove it along with a lot of other sites but they are kind of grandfathered in at this point unfortunately.
