### ISSUE TITLE
watchnrl.com

### ISSUE THREAD

**Issue by puncy** [streamlink/streamlink#1487]
### Checklist

- [] This is a bug report.
- [] This is a feature request.
- [X] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Watchnrl.com.au provides live NRL matches to people in certain countries.
...

### Expected / Actual behavior
Service is geoblocked for certain countries and you need a login to gain access to play any videos.
...

### Reproduction steps / Explicit stream URLs to test

URLs i can pull from certain applications to see where the stream is coming from.

1. https://matchesliveottfs-i.akamaihd.net/hls/live/597624/18_7080/masters2-4000.m3u8?hdntl=exp=1518926958~acl=/hls/live/597624/18_7080/*~data=hdntl~hmac=802eeebbecc4bb8d7d728a7032c66ca18e1c27a4fd127728309e4126b97680c0

when trying to open this URL in the current streamlink i get a "found matching plugin", then "Error unable to open URL 403 forbidden"

===================

2. https://matchesliveottfs-i.akamaihd.net/hls/live/597624/18_7080/masters2-4000.m3u8

when trying to open this URL in the current streamlink i get a "found matching plugin", then "Error unable to open URL 403 forbidden"

3. https://matchesliveottfs-i.akamaihd.net/hls/live/597624/18_7080/20180217T125908/masters1-5000/00000/masters1-5000_00080.ts?hdntl=exp=1518926987~acl=/hls/live/597624/18_7080/*~data=hdntl~hmac=a921aefca264a3fe4a53cf7d48e22ab67b2b65fa57e724e68b4a82b0a2903a73

couldnt get this to go into streamlink

### Comments, screenshots, etc.

it seems to use akamaihd like just about every other service but i cannot get it to work

screenshots below
https://i.imgur.com/zVURiOb.jpg
https://i.imgur.com/J2ew4RC.jpg

**Comment by gravyboat** [comment]
Clear violation of their [TOS](https://www.watchnrl.com/terms-of-use) Under the Permitted Use of the Service Section. Closing.

**Comment by puncy** [comment]
really?

like any of the other plugins dont violate the TOS of the sites?

**Comment by gravyboat** [comment]
@puncy I'm sure that some of the other ones do, but if you look at the issues/PR history we've really been trying to curb that in the last few months as people kept asking for more and more problematic plugins. If it was up to me I would remove many of them.

**Comment by puncy** [comment]
i would like to see how many plugins in total streamlink has vs how many violate the TOS, im sure it would be 99% of them.

grow some balls would you.

**Comment by puncy** [comment]
better delete the twitch.tv plugin as well cause you violate their TOS...... oh wait, the majority of streamlink users need it..... better keep it

**Comment by gravyboat** [comment]
@puncy There's no need to be rude, feel free to fork the repo and write whatever plugins you feel like maintaining, it's open source after all! Regarding the Twitch plugin they've stated several times that they're okay with tools like ours and we specifically request that people support the services they consume to ensure they continue to exist.
