### ISSUE TITLE
France TV

### ISSUE THREAD

**Issue by novazur972** [streamlink/streamlink#1488]
I'm trying to use streamlink to watch FranceTV, but I get an error : 
`$ streamlink -l debug http://www.france.tv/france-2/direct.html 396p
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
error: Unable to open URL: http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE1MTg2ODQyOTR+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPTdiNTZlZmM0YzBmZmRlMDM3MWRiYWVhZGFlYmQwNDNhNTVlMGEwYjdhZGZkMTM4OTI0YjBhYzI4NWU3ZDJhNjc=/index.m3u8?hdnea=exp=1518663294~acl=%2fsimulcast%2fFrance_2%2fhls_v1*~hmac=4ea05dff8ba851bc86b796e5624efcb0c2b93601907626e0134e2d46d3e156aa (403 Client Error: Forbidden for url: http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE1MTg2ODQyOTR+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPTdiNTZlZmM0YzBmZmRlMDM3MWRiYWVhZGFlYmQwNDNhNTVlMGEwYjdhZGZkMTM4OTI0YjBhYzI4NWU3ZDJhNjc=/index.m3u8?hdnea=exp=1518663294~acl=%2fsimulcast%2fFrance_2%2fhls_v1*~hmac=4ea05dff8ba851bc86b796e5624efcb0c2b93601907626e0134e2d46d3e156aa)`

I can watch with a browser like Chrome or Firefox.
It worked several times with streamlink, but not anymore at all.

`$ streamlink -V
streamlink 0.9.0`
Gentoo Linux
`$ uname -a
Linux cored 4.14.8-gentoo-r1 #1 SMP Thu Dec 21 12:35:06 AST 2017 x86_64 Intel(R) Core(TM)2 Duo CPU E8400 @ 3.00GHz GenuineIntel GNU/Linux`

**Comment by back-to** [comment]
`exp=1518663294` = `02/15/2018 @ 2:54am (UTC)`
is your log old?

---

`streamlink 0.9.0` old version use
https://github.com/streamlink/streamlink/releases/tag/0.10.0

---

```
$ streamlink http://www.france.tv/france-2/direct.html worst -l debug
[cli][debug] Python:     3.6.4
[cli][debug] Streamlink: 0.10.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
[hls.parse_variant_playlist][debug] Using external audio track for stream 144p (language=fra, name=Francais)
[hls.parse_variant_playlist][debug] Using external audio track for stream 180p (language=fra, name=Francais)
[hls.parse_variant_playlist][debug] Using external audio track for stream 288p (language=fra, name=Francais)
[hls.parse_variant_playlist][debug] Using external audio track for stream 396p (language=fra, name=Francais)
[hls.parse_variant_playlist][debug] Using external audio track for stream 576p (language=fra, name=Francais)
[plugin.pluzz][error] Failed to access stream, may be due to expired content
[cli][info] Available streams: 144p_hls, 180p_hls, 288p_hls, 396p_hls, 576p_hls, 144p (worst), 180p, 288p, 396p, 576p (best)
[cli][info] Opening stream: 144p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 9881676; Last Sequence: 9881681
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 9881679; End Sequence: None
[stream.hls][debug] Adding segment 9881679 to queue
[stream.hls][debug] Adding segment 9881680 to queue
[stream.hls][debug] Adding segment 9881681 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Download of segment 9881679 complete
[cli][info] Starting player: /usr/bin/mpv
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 9881680 complete
[stream.hls][debug] Download of segment 9881681 complete
```

**works for me**

**Comment by novazur972** [comment]
same thing with 0.10.0.
As I said, it worked several times at the begining, but it doesn't work anymore.
Try it about 10 times, and may be you will have the same problem as me.
``$ streamlink -V``
``streamlink 0.10.0``
``$ streamlink http://www.france.tv/france-2/direct.html worst -l debug``
``[cli][debug] OS:         Linux-4.14.8-gentoo-r1-x86_64-Intel-R-_Core-TM-2_Duo_CPU_E8400_@_3.00GHz-with-gentoo-2.4.1``
``[cli][debug] Python:     3.5.4``
``[cli][debug] Streamlink: 0.10.0``
``[cli][debug] Requests(2.18.2), Socks(1.6.7), Websocket(0.37.0)``
``[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
error: Unable to open URL: http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE1MTg2ODQyOTR+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPTdiNTZlZmM0YzBmZmRlMDM3MWRiYWVhZGFlYmQwNDNhNTVlMGEwYjdhZGZkMTM4OTI0YjBhYzI4NWU3ZDJhNjc=/index.m3u8?hdnea=exp=1518663294~acl=%2fsimulcast%2fFrance_2%2fhls_v1*~hmac=4ea05dff8ba851bc86b796e5624efcb0c2b93601907626e0134e2d46d3e156aa (403 Client Error: Forbidden for url: http://live.francetv.fr/simulcast/France_2/hls_v1/ZXhwPTE1MTg2ODQyOTR+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzX3YxKn5obWFjPTdiNTZlZmM0YzBmZmRlMDM3MWRiYWVhZGFlYmQwNDNhNTVlMGEwYjdhZGZkMTM4OTI0YjBhYzI4NWU3ZDJhNjc=/index.m3u8?hdnea=exp=1518663294~acl=%2fsimulcast%2fFrance_2%2fhls_v1*~hmac=4ea05dff8ba851bc86b796e5624efcb0c2b93601907626e0134e2d46d3e156aa)
``

**Comment by back-to** [comment]
your **timestamp is already expired** `exp=1518663294`

and it's the same as before, you got some caching issue on your system.

**Comment by novazur972** [comment]
Oh ! Ok. Something about my proxy squid.
After restarting squid, it works. I'll search this way.
Thank you and sorry for the noise.
