### ISSUE TITLE
Can not play outputted files in VLC when saving from YouTube

### ISSUE THREAD

**Issue by Two-Tone** [streamlink/streamlink#149]
When doing `streamlink youtube-url best -o ./file` the resulting file does not play in VLC. It plays in MPC on Windows with CCCP installed and it plays in mplayer on Linux. For whatever reason VLC can not play the file. I'm not sure if it's specific to VLC or ffmpeg, but I was able to load the file into Blender without issue.

Semi related question: when saving a stream, is there any way to elegantly stop the download or do I have to just terminate the process?

Edit: This problem also occurs in Livestreamer.

**Comment by scottbernstein** [comment]
This question comes up perhaps once a week. The answer is that YouTube changed the format of their videos to a codec that VLC 2 doesn't support. Upgrade to the nightly build of VLC3 and your videos will play just fine.

On Nov 10, 2016, at 8:24 PM, Two-Tone <notifications@github.com<mailto:notifications@github.com>> wrote:


When doing streamlink youtube-url best -o ./file the resulting file does not play in VLC. It plays in MPC on Windows with CCCP installed and it plays in mplayer on Linux. For whatever reason VLC can not play the file. I'm not sure if it's specific to VLC or ffmpeg, but I was able to load the file into Blender without issue.

-

**Comment by gravyboat** [comment]
Feel free to open this back up if you @scottbernstein's solution doesn't work.
