### ISSUE TITLE
--verbose-player not working (mpv)

### ISSUE THREAD

**Issue by xse** [streamlink/streamlink#1490]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description

Hi,
So i'm trying to get mpv's output on my terminal using the "--verbose-output" option because mpv can be controled from cli inputs too, but streamlink behave just like this option wasn't there.
On debug logs i can clearly see "[cli][debug] Writing stream to output".
I tried it from different terminals, same issue.
I didn't try on other players i only have mpv installed.
Apparently this isn't a known issue, i'm curious to see if others can replicate.
relevant configuration ? : 

> player=mpv --border=no --cache=8192
> verbose-player

I'm using windows 10, mpv and streamlink both installed using chocolatey.

By the way ( this is totally irrelevant to this issue ) on that page https://streamlink.github.io/issues.html mpv's parameter should be "--cache=kbytes" and not "--cache kbytes".

### Expected / Actual behavior

Showing me mpv's output/Doesn't show me mpv's output.

### Reproduction steps / Explicit stream URLs to test

1. Watching a youtube stream with : 
`streamlink --verbose-player https://www.youtube.com/watch?v=Kl9pJaiUMms 720p`

### Logs

https://gist.github.com/xse/3c4f7faab30a46b9631eea812f88ca16

### Comments, screenshots, etc.

![](https://i.imgur.com/49JL04B.png)

**Comment by johnthecracker** [comment]
This will probably give you what you want:

mpv.com --msg-level=all=v --ytdl-raw-options=no-check-certificate= https://www.youtube.com/watch?v=Kl9pJaiUMms


You can find more information here:

https://mpv.io/manual/stable/


Look under:

Terminal

**Comment by tp0** [comment]
If you mean you want the debug log from mpv use this instead:

```streamlink --verbose-player -p="mpv --v" https://www.youtube.com/watch?v=Kl9pJaiUMms 720p```

You might need to fix that path to mpv if you're on Windows.

**Comment by xse** [comment]
Actually when using mpv directly without using streamlink it stops in about 5 seconds, i guess it reads the cache and then stops, i get socket errors and so on.

With streamlink it works perfectly that's why i use it for youtube/twitch streams.
I just thought that the --verbose-player option is supposed to display mpv's console output in the terminal in which i launched streamlink. Am i wrong ?

It's not that big of a deal obviously but i assume that's not an expected behavior.

**Comment by johnthecracker** [comment]
mpv works perfectly fine for me.

Try to specify resolution:

--ytdl-format=300

**Comment by johnthecracker** [comment]
Try this mpv:

https://sourceforge.net/projects/mpv-player-windows/files/32bit/

mpv-i686-20180217-git-0dbad95.7z

**Comment by xse** [comment]
Oh don't worry I'm fine with watching them with streamlink, this isn't that big of a deal and i'd prefer to keep all my applications using chocolatey that way i don't have to worry about updating them one by one.

**Comment by bastimeyer** [comment]
> I just thought that the --verbose-player option is supposed to display mpv's console output in the terminal in which i launched streamlink. Am i wrong ?

It does, but what you're seeing may be an issue on Windows with its terrible terminal program or with MPV. As you can see, stdout and stderr are being linked to the sub process (the player), if you're using the verbose-player option.
https://github.com/streamlink/streamlink/blob/0.10.0/src/streamlink_cli/output.py#L139-L142
https://github.com/streamlink/streamlink/blob/0.10.0/src/streamlink_cli/output.py#L90-L95
https://github.com/streamlink/streamlink/blob/0.10.0/src/streamlink_cli/main.py#L91-L94

```
$ streamlink --verbose-player -p mpv twitch.tv/CHANNEL best
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv
[osc] script-opts: unknown key duration, ignoring 
Playing: -
[file] Reading from stdin...
 (+) Video --vid=1 (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 1920x1080 vaapi[nv12]
[osd/libass] fontselect: Using default font family: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/Roboto-Medium.ttf, 0, Roboto-Medium
^C[cli][info] Stream ended


Exiting... (Quit)
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

@johnthecracker 
I understand that you're trying to help, but what you're suggesting here is using MPV's embedded yt-dl solution. Remember that this is the Streamlink issue tracker...

**Comment by johnthecracker** [comment]
Ask and you shall receive.

Here is streamlink solution:

`C:\MISC\STREAMLINK>streamlink --verbose-player -p "mpv.com" https://www.youtube.com/watch?v=Kl9pJaiUMms 360p
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=Kl9pJaiUMms
[cli][info] Available streams: audio_mp4, 144p (worst), 180p, 360p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 360p (http)
[cli][info] Starting player: mpv.com
Playing: -
[file] Reading from stdin...
 (+) Video --vid=1 (*) (h264 640x360 29.970fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
VO: [gpu] 640x360 yuv420p
AO: [wasapi] 44100Hz stereo 2ch float
AV: 00:00:41 / 07:39:38 (0%) A-V:  0.000
`
