### ISSUE TITLE
Reliable method of installation and usage with Raspberry PI 3? (Youtube Live)

### ISSUE THREAD

**Issue by looloosha** [streamlink/streamlink#1491]
### Checklist
- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Not sure if this is the right section to post this but has anyone installed streamlink and been able to get a Youtube Live Stream up on a raspberry pi with stream link and a player? I've been trying to use a bunch of players and had no luck. 

What's the best way to install Streamlink on a RPi with Raspian?

What's the best player to use with Streamlink on an RPi and how should it be configured?

Side note, does Streamlink default audio ouput to HDMI? Or how can I tell Pi to do that?

### Expected / Actual behavior

When trying to use OMXplayer, here's what I get:

streamlink -p omxplayer https://www.youtube.com/watch?v=RtU_mdL2vBM worst
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=RtU_mdL2vBM
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
[cli][info] Starting player: omxplayer
error: Failed to start player: omxplayer (Process exited prematurely)
[cli][info] Closing currently open stream...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> What's the best way to install Streamlink on a RPi with Raspian?

You should be using your distro's official streamlink package. If you don't want to use that, you can use `pip` instead.
https://streamlink.github.io/install.html#source-code
https://archive.raspbian.org/raspbian/pool/main/s/streamlink/

> What's the best player to use with Streamlink on an RPi and how should it be configured?

Any player can be used which can handle the specified stream input method and which can decode and render the stream data. See the streamlink docs.
https://streamlink.github.io/cli.html#player-options

> does Streamlink default audio ouput to HDMI? Or how can I tell Pi to do that

This has nothing to do with Streamlink. The chosen player is the output application, not Streamlink.

> error: Failed to start player: omxplayer (Process exited prematurely)

As you can see, the player has failed to start. This is not Streamlink's issue and you need to resolve this yourself. You can use Streamlink's `--loglevel debug` and `--verbose-player` parameters, though. Again, see the docs:
https://streamlink.github.io/cli.html#general-options
https://streamlink.github.io/cli.html#player-options

**Comment by Thuddwin** [comment]
@looloosha Any luck?  I have been trying the same thing but with https://youtube.com/user/channelName/live.
It takes streamlink forever to return something other than None. Tonight, it returned None throughout the entire webcast.  Not happy with this hack code, am moving on.

**Comment by beardypig** [comment]
As per the documentation (https://streamlink.github.io/players.html), it is recommended to use `--player-fifo` and `--player "omxplayer --timeout 20"` when using `omxplayer`. 

I would recommend trying the following
```
streamlink -p "omxplayer --timeout 20" --player-fifo https://www.youtube.com/watch?v=RtU_mdL2vBM worst
```

and see if that works better for you.

**Comment by Thuddwin** [comment]
Time to eat crow.  My sincerest apologies for the unprofessional trash-talk against Streamlink that I submitted here.  The problems I had, as noted above, were self-inflicted due to my gross lack of understanding of Youtube's dynamic URL management flow.  Having discovered the 'secret' and implementing the code changes, the Streamlink package works perfectly every time!
Please refer to https://github.com/streamlink/streamlink/issues/1500 for my 'hack' that solved this problem for me.

**Comment by bastimeyer** [comment]
Can we close this issue?

**Comment by looloosha** [comment]
Yes, the commands @beardypig posted here helped me out. 

Thanks for the support guys.

Close @bastimeyer
