### ISSUE TITLE
Neulion DMCA Takedown Notice

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#1493]
I received the following email today and in the spirit of transparency am providing it here below:

------------
Hi there,

I'm contacting you on behalf of GitHub Support because we've received a DMCA takedown notice regarding the following content:

https://github.com/streamlink/streamlink

You can view the notice and the details of the requested changes below.

In this case only certain files were identified as allegedly infringing. Since it's not possible to disable individual files within a GitHub repository, we're giving you a 24 hour opportunity to remove the content named in the takedown. Please follow the steps in the following article to remove the content from the history:

https://help.github.com/articles/remove-sensitive-data

Once you've done that, please reply to this message to confirm the change. If we don't hear from you that a change is made within the next 24 hours, we will need to disable the entire repository according to our GitHub DMCA Takedown Policy, which you can find here:

https://help.github.com/articles/dmca-takedown-policy/

If you believe your content on GitHub was mistakenly disabled by a DMCA takedown request, you have the right to contest the takedown by submitting a counter notice, as described on the DMCA Takedown Policy page.

PLEASE NOTE: It is important that you reply within 24 hours to confirm whether you have made the requested changes. If you do not, the repository will be disabled.

Are you the copyright owner or authorized to act on the copyright owner's behalf?

NeuLion is the sole owner of all intellectual property rights in the NeuLion® Digital Platform as well as the NeuLion SDK/API. The sole use of the files that should be taken down is to infringe upon NeuLion’s intellectual property rights in the NeuLion Digital Platform as well as to provide a means for those that use such files to do so.

Please provide a detailed description of the original copyrighted work that has allegedly been infringed. If possible, include a URL to where it is posted online.

https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py is meant to steal content and violate terms of service for ufc.tv, based on the NeuLion Digital Platform and hosted/managed by NeuLion on behalf of the UFC. This code enables piracy activity that increases our CDN traffic costs.

https://github.com/streamlink/streamlink includes plugins such as Neulion meant to steal content and violate the terms of services on the NeuLion digital Platform and hosted customers including ufc.tv, Fanpass.co.nz, http://elevensports.tw/, http://elevensportsnetwork.sg/, http://elevensportsnetwork.be/, http://elevensports.lu/, http://elevensportsnetwork.pl/, http://elevensportsusa.com/, http://watch.nba.com/ and more.

What files should be taken down? Please provide URLs for each file, or if the entire repository, the repository's URL:

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/neulion.py

https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py

Have you searched for any forks of the allegedly infringing files or repositories? Each fork is a distinct repository and must be identified separately if you believe it is infringing and wish to have it taken down.

Yes.

Is the work licensed under an open source license? If so, which open source license? Are the allegedly infringing files being used under the open source license, or are they in violation of the license?

No. This proprietary information is not subject to nor licensed under any open source license.

What would be the best solution for the alleged infringement? Are there specific changes the other person can make other than removal?

Removal is the only solution for addressing this infringement of NeuLion’s intellectual property rights.

Do you have the alleged infringer's contact information? If so, please provide it:

Type (or copy and paste) the following statement: "I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law. I have taken fair use into consideration."

I have a good faith belief that use of the copyrighted materials described above on the infringing web pages is not authorized by the copyright owner, or its agent, or the law. I have taken fair use into consideration.

Type (or copy and paste) the following statement: "I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed."

"I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

Please confirm that you have you have read our Guide to Submitting a DMCA Takedown Notice: https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/

I have read these guidlines.

So that we can get back to you, please provide either your telephone number or physical address:

[private]

Please type your full legal name below to sign this request:

[private] 

-----------

I have responded with the following:

Thank you for the notification, I have created an issue on the Streamlink repository (https://github.com/streamlink/streamlink/issues/1493) for discussion and remediation of this issue. Please note that https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py is not associated with this repository or project and we will be unable to take action on this repository. I will respond to this email within 24 hours with an update.

Regards,

Forrest

----------

I'm not really interested in fighting Neulion on this since they're well within their rights to request we take this down. We could argue that since the UFC site requires login it technically only works for subscribers, but I don't think it's really worth the time/risk to do so, nor do I care that much. I'm in favor of just removing this plugin/tests and scrubbing it from the history as noted in the email. Opinions @bastimeyer, @cdrage, @beardypig?

**Comment by cdrage** [comment]
I received the e-mail too.

I'd rather not get sued / fined, especially since it's an american & canadian company, plus we don't have the resource to fight this. Let's just take down the code.

**Comment by notr1ch** [comment]
This seems like a bogus DMCA, they misidentified the actual repository and there is no copyrighted content owned by Neulion at the URL provided. The claim that the plugin allows piracy is also false since it appears you still need a valid login to use the plugin.

The developer of the plugin may have violated the terms of service of Neulion if while developing the plugin he/she agreed to terms preventing reverse engineering for example. However the DMCA specifically covers copyright infringement and it doesn't make sense for enforcing terms of service violations.

**Comment by gravyboat** [comment]
@notr1ch Not all of the Neulion plugins require login since they do have some streams that are available for free but I assume ad supported. It's really not worth fighting for us since we don't have the funds/resources to make it happen.

**Comment by gravyboat** [comment]
@cdrage I'll take care of this tomorrow morning before work when I'm on my work machine unless someone else gets to it tonight. My plan is just to use BFG to scrub the plugin and the test file.

**Comment by bastimeyer** [comment]
I don't know if this DMCA takedown request is legit (this whole system is just so utterly stupid), but I don't want the repo to be disabled, so let's remove the plugin.

You don't have to just do a direct master push. The branch needs to get altered and its commit history changed and then force-pushed here. This will build new commit IDs and make open PRs which have been opened since then incompatible. All merged PRs since then will lose their references.

The plugin files were merged on January 15th in bcc7798ba75771c1ccca6804af2b57223423c0b3 (#1406), so the change of the master branch shouldn't be too dramatic, although annoying. The last *good* commit ID is 904ddf1545ea4bb1b02865be7f2a90de09c1c0a0 and dbab4ee + ba893e6 need to get dropped.

However, the neulion plugin is a rewrite of the old ufctv plugin. What does this mean here? Does the old one need to get removed, too? This one has been written and merged in June last year, quite a long time ago. A rebase would be really bad...
https://github.com/streamlink/streamlink/commits/904ddf1545ea4bb1b02865be7f2a90de09c1c0a0/src/streamlink/plugins/ufctv.py

People who have cloned the repo (either in a dev or build environment) will need to reset their master branch, otherwise further git pulls will be incompatible. Do we need to add a note somewhere?

We also need to discuss what we should do about other similar plugins.

**Comment by gravyboat** [comment]
@bastimeyer Yeah I agree that it's stupid, but I also don't want the repo to be disabled. I know I don't just have to do a master push, BFG is a tool that will automatically scrub the history for us then we'll have to do the push. It's going to be dirty for sure but I don't know what other choice we have in the matter. I think as long as we take care of it going forward we should be okay, or that is the good faith attitude I think we should adapt and respond back to GitHub support with. I'm not sure about adding a note. Regarding other plugins I'm not sure what can be done there, we've discussed in the past not adding more questionable plugins but there are some that already existed. It's a real mess.

**Comment by bastimeyer** [comment]
So are we going to remove the old plugin, too? As I've said, this one has been merged in June last year. It's not included in the takedown request, though.

I know this sounds silly, but if the old plugin also needs to get removed, do we want to take the opportunity and clean up some other stuff as well, like removing the large ffmpeg binaries (~54MiB), which have been added in January last year?

**Comment by gravyboat** [comment]
I don't think we need to remove the old plugin since it doesn't work any more if I remember correctly. If they want us to take it down they can file another DMCA request, we're not going to volunteer to remove extra stuff as that's a slippery slope, plus the request already looks shady as hell as multiple people have noted.

We could, if you want to remove them I'm fine with it. I just want to make sure the repo doesn't get shut down so removing that plugin and the history is my top priority.

**Comment by bastimeyer** [comment]
According to #1406, nothing was changed for the old URLs supported by this plugin. I guess that means that the entire file history needs to get removed...
- dbab4ee0736bf866ae5dda6db377e3dab92dd817
- ba893e618ba4167a6426ca50948e10b432ea50b8
- 49e305d7fa82d400baec84e9b78659528f62a48a
- 4938ad19a0961b17e139523c84dcdd732685a484
- 2a4095b5961e6bb0bb281e80558d1ef7aa301097

That would make 3df657d3cedc943adaf3d7b823e62335fc7344a7 (parent of 2a4095b5961e6bb0bb281e80558d1ef7aa301097) the last good commit ID (June 22nd, 2017) where the current master branch would need to get rebased onto.

**I'd like to hear some other opinions first.**
@streamlink/members 
**Just remove the latest plugin changes, or the entire plugin history?**

----

Regarding the ffmpeg binaries I mentioned, this would also require a modification of 97e7bafa3d2c77033656904aa4f410d4be7cd219 (#224) (removal of the `win32/ffmpeg/ffmpeg.exe` file). It's probably not worth the effort and too risky to break something else, however, rebasing a master branch and altering a commit/merge history of several months is something big and a rare opportunity to remove unwanted stuff.

It's a shitty situation and the 24h time frame doesn't really allow for well thought-out decisions, especially for projects with international collaborators. Argh, I hate this...

**Comment by gravyboat** [comment]
@bastimeyer I know the time limit really sucks, maybe if we don't have more input by tomorrow morning (in the states at least since I got the takedown notice around 11 AM) I'll email them asking if we can have more time? I linked them this issue so it's obvious we are trying to address the problem and operating in good faith. I'd still be against removing the file history, all they asked was for us to remove one file and the associated history. If they want more they're welcome to contribute...

**Comment by beardypig** [comment]
Probably we should remove the ufctv one too, it is the same file just renamed - we don't want to have to do two rebases... I don't have any interest is contesting it.

**Comment by karlo2105** [comment]
Damn I never thought they would gonna make a mess for something which only works with login. DMCA is really a shit. Why not just remove incriminated plugins and not others ? Let's not do something they didin't fill in notice. 
It would be good to think about if there is similar Github which is hosted outside of America. 
I wonder why do you want to remove ffmpeg mux from repository ? It means Mux audio and video won't be supported anymore ?

**Comment by bastimeyer** [comment]
@beardypig 
Absolutely... I've listed all the associated commits to that plugin, so everybody can see that it's not just a new plugin, but a continuation of the old one.

@karlo2105 
The reason why I mentioned the ffmpeg binary, is because it doesn't belong into the repo here and bloats it up from a few hundred KiB to more than 55 MiB. Since rebasing the master branch is something you don't ever want to do unless you really have to, like right now, I was suggesting to go a step further and remove it as well. It is only used by the Windows installers and can be moved to a different, external location and then loaded in while building the installers. We had a discussion about this a few months ago. As I've said, this requires a change of the commit where it was added and another one (which can be done later) in order to fix the builds. I know it's stupid to discuss it here now and rush the whole thing, but we are forced to act and could at least try to make the best out of this situation. It's optional, though.

**Comment by cdrage** [comment]
@bastimeyer @gravyboat They link the DMCA notice to the "master" branch. Wouldn't it be good faith from us if we simply create a PR / merge removing the mentioned code?

Since they're only asking for the code from master to be removed, not the entire history :smile:

**Comment by bastimeyer** [comment]
@cdrage 
According to [https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/](https://help.github.com/articles/guide-to-submitting-a-dmca-takedown-notice/), the issuer of a DMCA takedown request needs to be as specific as possible when telling the other party what needs to be removed. You're right, only those two links were provided, which doesn't necessarily mean that the entire file history needs to get purged:
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/neulion.py
https://github.com/portse/plugin.video.ufcfightpass/blob/master/default.py

I'm not sure if we will see another report in the future, but simply deleting the files should be okay for now, I guess. Btw, why did I not get any contact information of the takedown issuer? The Github guidelines require that.

**Comment by karlo2105** [comment]
@bastimeyer 
Strange. I wonder whether or not @gravyboat did get any contact information with takedown issuer.

**Comment by gravyboat** [comment]
@bastimeyer I posted the entire contents of the message I received from GitHub, and didn't redact any information. I'll send an email noting that we have merged a PR to remove the code here in a minute and will paste the contents of the body here.

**Comment by gravyboat** [comment]
The following email was sent as of 9:23 AM PST:

--------------------

Hello,

We have removed the offending code via the following PR: https://github.com/streamlink/streamlink/pull/1497 and continuing discussion is available here: https://github.com/streamlink/streamlink/issues/1493

Regards,

Forrest

**Comment by gravyboat** [comment]
I received the following response from GitHub support:

------------

Hello,

Thanks for letting us know you've made changes! We'll pass them along to the copyright holder, and let you know if they have any other concerns.

Best,
Payton

**Comment by puncy** [comment]
grow some balls

**Comment by RosadinTV** [comment]
I hope they don't ask to also remove the files from releases, that would take a lot of work (or lose all the old versions). 😟

**Comment by johnpolite** [comment]
@RosadinTV 

You provide new ideas to whoever is about this, I didn't think about this untill you said it.

If this is "neulion", they are begging for DDOS here.

**Comment by guixxx** [comment]
What the... This is so stupid. Americans and their stupid IP laws for fucks sake. I doubt they would spend time and money to legally go after you or the people who created this plug-in.

**Comment by karlo2105** [comment]
@guixxx 
I agree but problem is then repository would be disabled and you will have to find alternative to GITHUB.
Their country is run by companies who make laws for their interests.

**Comment by johnpolite** [comment]
@puncy


Your balls are god's gift to you, but...

can you give DDOS to neulion?

That might make a difference.

**Comment by Lanboost** [comment]
I agree, only take down the files exactly specified.

Fun how they use a law that has nothing to do with this....Please file a claim to remove FF and adblock to. As everything that can open a HLS stream is apperetly doing c-r-i.

Anyway keep up the good work.

**Comment by puncy** [comment]
@johnpolite 

im sure with the spare dollars in the account here, they can pay someone in the blackhat world to DDOS neulion

**Comment by johnpolite** [comment]
neulion knows the law, but do they know about IT more than people on github ?

Why should somebody more stupid than you be allowed to threaten you ?

**Comment by johnpolite** [comment]
If they get DDOS, they may consider hiring themself an IT specialist instead of a lawyer.

**Comment by johnthecracker** [comment]
streamrecorder forum is down, this may go down, all of this stinks..

**Comment by 10mins** [comment]
This is a bogus notice. The plugin does not contain any code (or other "intellectual properties") owned by Neulion.  Submit a counter notice.

**Comment by cdrage** [comment]
I'm going to lock this conversation.

We'd be more than happy to fight this, however, we don't have the resources. We're just a small community of developers dedicated to streaming.

If people wish to continue to use the Neulion code, it's as easy as installing a previous version of `streamlink`:

```sh
pip install streamlink=0.10.0
```

Or forking the Streamlink repository from commit: 

https://github.com/streamlink/streamlink/commit/418a41d5412a97f42b74fbd326b853e2320fd68e

**Comment by beardypig** [comment]
Here's my 2¢ (*Not a lawyer*).

This is almost certainly a bogus claim. Streamlink does not violate the copyright of NeuLion, as there is no **_copyrighted_** material owned by NeuLion in Streamlink (it's the DM**C**A after all). If anything, NeuLion is violating Streamlink's and the developers' copyright by requesting it be removed. 

The use of their API may be controlled by their terms and conditions, but Streamlink does not interact with their API directly that is handled via the specific content provider (nba, ufc, etc.). Streamlink is not intended to circumvent copy protection, region restrictions, or other restrictions; Streamlink is indented to provide interoperability. The developer could have violated the Ts&Cs, as they prohibit reverse engineering of their code - but, if it was done by observing the behaviour (ie. black box), then that is not reverse engineering the code. 
If there are any Ts&Cs or copyright violations they are down to the users of the software, not the software. 

That being said, I don't want to deal with an letters from lawyers :)
