### ISSUE TITLE
bgonair.bg (cdnbg) doesn't work on https

### ISSUE THREAD

**Issue by anchev** [streamlink/streamlink#1494]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Perhaps something has been updated on the sites which needs update of the plugin too.

The site www.bgonair.bg/tvonline redirects to HTTPS now, so perhaps it would be good to have the plugin work with that too:
```
[~]: streamlink https://www.bgonair.bg/tvonline
[cli][info] Found matching plugin cdnbg for URL https://www.bgonair.bg/tvonline
error: Unable to open URL: https://lb-hls.cdn.bg/2006/fls/bonair.stream/playlist.m3u8?at=209d5fd672fca2f8e082d4f52d87bdf0 ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600))
```
Using plain http works fine:
```
[~]: streamlink http://www.bgonair.bg/tvonline 404p
[cli][info] Found matching plugin cdnbg for URL http://www.bgonair.bg/tvonline
[cli][info] Available streams: 404p (worst, best)
[cli][info] Opening stream: 404p (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by johnthecracker** [comment]
Using https works fine too:

C:\>streamlink.exe --http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0" --http-no-ssl-verify "https://www.bgonair.bg/tvonline" best
[cli][info] Found matching plugin cdnbg for URL https://www.bgonair.bg/tvonline
[cli][info] Available streams: 576p (worst, best)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by anchev** [comment]
But why do you need to specify additional options? For example https://www.btv.bg/live works without them.

**Comment by johnthecracker** [comment]
you need only this one really...

--http-no-ssl-verify

**Comment by anchev** [comment]
The docs say:
```
  --http-no-ssl-verify
    Don't attempt to verify SSL certificates.
    
    Usually a bad idea, only use this if you know what you're doing.
```
And I tend to agree. The site has a valid SSL certificate. If the program doesn't recognize it there must be some problem which needs fixing.

**Comment by johnthecracker** [comment]
be politically correct, fine.

**Comment by gravyboat** [comment]
`certificate verify failed` means that the cert is bad, it's not a problem with Streamlink, it's a problem with their CDN having an invalid SSL certificate. I'm closing this since there's nothing we can do.

**Comment by anchev** [comment]
But when I visit the site https://www.bgonair.bg/tvonline through a browser I see a valid certificate?
```
Common Name (CN)	RapidSSL SHA256 CA
Organization (O)	GeoTrust Inc.
```

**Comment by gravyboat** [comment]
It's not the same, look at the log for where the actual stream is coming from and the error line:
`https://lb-hls.cdn.bg/2006/fls/bonair.stream/playlist.m3u8?at=209d5fd672fca2f8e082d4f52d87bdf0` rit's from `lb-hls.cdn.bg`

**Comment by anchev** [comment]
When I visit in browser https://lb-hls.cdn.bg/ I also see a valid certificate. Doesn't that work for you?

**Comment by gravyboat** [comment]
Yeah but since it's a CDN we don't know how their routing works, it could be one specific server that you hit on that request in the log that is the problem. You can contact them about it if you want.

**Comment by anchev** [comment]
There seems to be incomplete certificate chain:

https://www.ssllabs.com/ssltest/analyze.html?d=lb-hls.cdn.bg

Yes, it is their issue, perhaps wrong configuration. Not related to routing or streamlink.
