### ISSUE TITLE
Fox.com.tr not work with Streamlink

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#1495]
## **Checklist**

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

##  **Description**

 i cant see anything at fox.com.tr 
 i have test it with this links but i became black screen 

## **Reproduction steps / Explicit stream URLs to test**

https://www.fox.com.tr/canli-yayin

**Comment by gravyboat** [comment]
This is not the livestreamer repo.

**Comment by dreamboxco** [comment]
thats right but its a plugin from streamlink look here 

Plugins

This is a list of the currently built in plugins and what URLs and features they support. Streamlink's primary focus is live streams, so VOD support is limited.

Name | URL(s) | Live | VOD | Notes
foxtr | fox.com.tr | Yes | No

https://streamlink.github.io/plugin_matrix.html

**Comment by beardypig** [comment]
It should be supported, and isn't working. I'll PR a fix :)

**Comment by mike8032** [comment]
beardypig, i just tested it too, and confim that it does not work. thank you upfront for the fix.
