### ISSUE TITLE
Support for more Bulgarian TVs

### ISSUE THREAD

**Issue by anchev** [streamlink/streamlink#1496]
- [x] This is a plugin (improvement) request.

### Description

Can you please add plugins also for the TV programs which are available on http://bul-tv.com/ and http://www.bg-gledai.tv?

Suggested to be filed in a new issue in: https://github.com/streamlink/streamlink/pull/392#issuecomment-367218691

**Comment by gravyboat** [comment]
Doesn't seem like these are original streams but are rebroadcasts of other streams which is something we don't want to support.

**Comment by anchev** [comment]
> rebroadcasts of other streams

I am not aware how exactly it works but these are good streams.

> which is something we don't want to support.

Why?

**Comment by gravyboat** [comment]
"Good" and legally allowed to rebroadcast are not the same. We don't want to support illegal restreams when possible because it can get us in trouble.

**Comment by anchev** [comment]
Oh, I see. Well, I am not aware if it is illegal (and vice versa).

Maybe I can try to make a custom plugin for my own use only if that is not very difficult. Any docs for how to do it please?

**Comment by back-to** [comment]
There is no guide for new plugins, https://github.com/streamlink/streamlink/issues/117
the easiest way is to copy a similar plugins and change it.

https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

Everything in the **.py** file is just python

https://www.python.org/doc/

**Comment by anchev** [comment]
Thanks.

> There is no guide for new plugins

Perhaps there should be, so that more people can easily contribute :)

**Comment by gravyboat** [comment]
@anchev We've talked about documenting this in the past (there's a really old issue on it) and just haven't gotten around to it. We're a pretty small team so other items have taken priority with our limited personal time sadly.
