### ISSUE TITLE
Youtube Live stream is playing up to 5 minutes before session.streams() stops returning None

### ISSUE THREAD

**Issue by Thuddwin** [streamlink/streamlink#1500]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x ] I have read the contribution guidelines.

### Description
Platform: Raspberry Pi 3 - Stretch
Encoder: Adobe Flash Media Live Encoder 3.2
Encoder Setup URL I: As per Youtube recommendations for 720p video H264 streams.
Encoder Setup URL II: 30 fps, 320x240 USB2.0 Webcam, 500Kbps, H264 streams.
Streamlink: 0.10.0
Python: 2.7
URL I: https://youtube.com/user/ApostolicFaithHQ/live
Live Sundays 11AM and 6PM, Tues and Fri 7:30PM
URL II: https://www.youtube.com/channel/UC6Q5UfqUUsmsW59m8xZSc8Q/live
Injection site for test. Time is intermittent throughout the day.

Code flow overview:
Python script uses the Streamlink API to query either of the URLs above every 15 seconds until session.streams() returns other than None.  The script then searches for a certain key in the streams object  to determine if the stream is Live or is something Youtube seems to put at the URL when a recent Live video has ended and at the time it is stored to the video archive.  If the key is not found the process repeats indefinitely.
When the key is found, the script launches a subprocess.Popen to start a CLI version of Streamlink with omxplayer (because I am a bit of a NOOB and haven't figured out how to stream to omxplayer with the API).  When the Live stream has ended, the python script does some cleanup and repeats the infinite query.

Use Case A: Happy
The video stream has been started for sometime _before_ streamlink/python script is started.  The query of the URL at 15 second intervals, 'finds' a live stream within 30 seconds (sooner if the interval timer is reduced). The video plays perfectly for the entire session without freeze, jitter, etc.

Use Case B: Sad
The video stream is started any time _after_ the streamlink/python script begins its query of the URL at 15 second intervals.  In this case, session.streams() returns None for upto 5.5 minutes after the video stream has started.  Once the video finally starts, it plays perfectly for the entire session without freeze, jitter, etc.

In either Use Case, a browser (on Windows 7) will begin showing the live stream immediately.

### Expected / Actual behavior
The expectation is that Use Case B stops returning None within a few seconds of a Live stream starting.

### Reproduction steps / Explicit stream URLs to test
1. Start the streamlink/python script _before_ the Live stream begins, using URL I or URL II and 'best' as parameters. ie: AFC_Streamer.py URL I  best
2. Start the Live stream using the Encoder noted above..
3. Observe that a typical interval before session.streams() returns data other than None is 2.5 to 5.5 minutes.

### Logs
[afc_streamer_Sad.log](https://github.com/streamlink/streamlink/files/1746333/afc_streamer_Sad.log)
[afc_streamer_Happy.log](https://github.com/streamlink/streamlink/files/1746334/afc_streamer_Happy.log)
Python Script

[GitHub Bug Filing.zip](https://github.com/streamlink/streamlink/files/1746376/GitHub.Bug.Filing.zip)

### Comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Thuddwin** [comment]
In Reproduction steps / Explicit stream URLs to test, line item 1. should say: 'Start the strealink/python script before the Live stream begins, using as parameters URL I or URL II and 'best'.

**Comment by alfredoivan** [comment]
can you explain how you did exactly for use case A : happy ?
I am having problems playing youtube live streams with 0.10.0 version of streamlink.
Probably the same as this issue.

**Comment by Thuddwin** [comment]
@alfredoivan The steps to reproduce the Happy results is the same as in the 'Reproduction Section' with the exception that the python script is started X minutes _AFTER_ the video stream has been started, where X is a minimum of 0.5. ie: Launch encoder, wait for Youtube LIVE injection to settle and video is running, then launch streamlink script.  In my case, the streamlink script will 'find' the stream and begin playing within 30 seconds, as noted above.
If by 'exactly' you are asking for code, it is in the "Github Bug Filing.zip" file.  Be warned, I'm a bit of a noob, ergo the code may result in you having nightmares for the next month, or so.

**Comment by Thuddwin** [comment]
We have several devices out there that physically and mentally challenged folks can use to watch our webcasts.  Tonight, none of them worked.  Am dumping streamlink, it's too much trouble and there isn't any help when needed.

**Comment by beardypig** [comment]
Sorry you weren't able to get the help you wanted @Thuddwin. If you're still interested in getting some help, albeit a bit late... 
When the stream starts how long until you can manually run streamlink and have it start playing? Is it still 5 minutes or so? It is possible that this delay is because of streamlink only support the HLS Streams, where as in a browser it will most likely use a DASH stream. Also, do you have `ffmpeg` installed, as this might affect the available streams for YouTube?

**Comment by Thuddwin** [comment]
@beardypig My sincerest apologies for my comment above.  The 'problem' was due to my lack of understanding and wrong assumptions regarding Youtube's URL management flow.
As noted in the problem description above, I am using a hard-coded URL that ends with '/live' with the naive assumption that at the time a video stream is injected to Youtube, what Streamlink requires would automatically be there within a few seconds as well.  That isn't always the case, and in the 'final straw' above, what Streamlink was looking for, apparently never showed up.  In fact, that night, our website, web app, and desktop browsers did not work....only the Youtube site.
I solved the random, to no streamlink acquisition times by this hack:
Using Python:
* urllib2 to read whatever is at the '/live' URL and then store in 'content' (for example)
* regex 'content' for VIDEO_ID using re.search('\'VIDEO_ID\':\s\"(.+?)\"' then store in 'vid' (for example)
* Build a new URL: https://youtube.com/watch?v=vid
* Start a Streamlink session with the new URL using 'best' for quality.
* Even on a Raspberry Pi Zero, Streamlink acquires its needed HLS data within 10 seconds and the video begins, determinately 30 seconds later (it takes a while to buffer up).
The above is executed in an infinite loop which is blocked during video play.  After the encoder has stopped streaming, usually within a couple of minutes, Youtube will update the content at the '/live' URL and the value found at VIDEO_ID will be changed in anticipation of the FUTURE incoming stream.
The new URL is created, as noted above, and that is used, in the infinite loop, to periodically query the '/watch?v=vid' URL.
If you have ANY questions, comments, or suggestions, please know that they are very welcomed by me.
Thank you for your help and your valuable contributions to the Streamlink project!

Repentantly, Thuddwin
