### ISSUE TITLE
Arconaitv plugin outdated?

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#1506]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Seems like the pugin needs to be updated? When I try playing a stream I get this error:
```
error: No plugin can handle URL: https://www.arconaitv.us/stream.php?id=80
```

After changing `.co`to `.us`in `arconai.py` I get:
```
error: No playable streams found on this URL: https://www.arconaitv.us/stream.php?id=80
```
### Expected / Actual behavior

Stream to play.

**Comment by back-to** [comment]
#1243
