### ISSUE TITLE
Streamlink 0.11.0 release

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1508]
Any blockers?

Would like to push a new release since we've got 31 commits since the last release (January).

@gravyboat @beardypig

**Comment by cdrage** [comment]
Hey @gravyboat I'm going to push a release. I'm thinking of doing a time-based release of the 1st and 15th of every month (whatever lands on weekday) for releases.

Does that work with you?

Only reason I ask is instead of feature-based released, a time-based release would work better with the amount of plugins that break and need updating quickly :+1:

**Comment by cdrage** [comment]
I'd like to push a release today if that's good :+1:

**Comment by gravyboat** [comment]
Let's go for it, open PRs will just have to wait, we keep getting behind because of "just one more" syndrome. Let's just keep to your schedule from now on.

**Comment by cdrage** [comment]
Released! I'll setup a calendar entry so I try to remember to release Streamlink twice a month :)
