### ISSUE TITLE
Format of buffer returned from HLSStreamReader.Read()

### ISSUE THREAD

**Issue by Werror** [streamlink/streamlink#1510]
I am building a custom player to process the bytes received from HLSStreamReader.Read(), I am struggling to find out the format of the buffer that it returns. I thought initially this was a .ts segment, however I am unable to confirm it myself.

Is there a documentation showing what kind of buffer is this?

**Comment by beardypig** [comment]
The `HLSStreamReader` is a stream of all the concatenated `ts` segments, when you call `read` you get the next `n` bytes in the buffer.

**Comment by Werror** [comment]
Thanks for the explanation, I think I figured out that I am not using the right size so that the binary blob I get is not a valid .ts segment.
Any information, where can i obtain correct size when using `read` ?

**Comment by beardypig** [comment]
You won't be able to read the correct size, the segments are variable sizes. You will need to parse the MPEG-TS packets to work it out. What are you trying to do?

**Comment by Werror** [comment]
Apologies for not being familiar with streaming technology, basically, I want to take screenshot of the stream.
I started to look into gstream which you included in your example, but not getting any where.

**Comment by beardypig** [comment]
It depends on your requirement, but we've covered taking screenshots before: https://github.com/streamlink/streamlink/issues/738#issuecomment-290363913 this is using ffmpeg. You might be able to get it to work with `opencv` too if you want to use the Python API. You can read some bytes then decode the frame with `opencv`.

**Comment by Werror** [comment]
Thank you very much.
