### ISSUE TITLE
[Plugin Request] http://karwan.tv/

### ISSUE THREAD

**Issue by mike8032** [streamlink/streamlink#1512]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. http://karwan.tv/
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.
there are many channels on the page. it would be awesome if someone could create a plugin for it
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This just looks like a ton of stolen satellite feeds and TV channels to me.

**Comment by mike8032** [comment]
i understand how it can look for someone not familiar with this channels. kurdish channels are devided in multiple countries and have multiple languages. there is not a real kurdistan with kurdish law therefore the copyright is not very restrictive. :-)

**Comment by dreamboxco** [comment]
lot ot stolen links!

**Comment by back-to** [comment]
It does not match the requirements.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
