### ISSUE TITLE
[Plugin Request] pixiv Sketch

### ISSUE THREAD

**Issue by Gameplayer9198** [streamlink/streamlink#1515]
- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

I'm requesting a plugin for pixiv sketch 

its streamed via HLS it serves a generated .m3u8(for 30ish seconds) along with its 3ish second chunk every second or so

| xhr | https://hls4.pixivsketch.net/2018022718/15197228728388594847a96103176027c0811ead7c5788b1297/4000000_1920x1080/506579247.ts
| xhr | https://hls4.pixivsketch.net/2018022718/15197228728388594847a96103176027c0811ead7c5788b1297/4000000_1920x1080/index.m3u8

hls4.pixivsketch.net: fixed gen'd server*
2018022718: stream start time (YYYYMMDDHH)
1519...1297: fixed UID*
4000000_1920x1080: video quality (low = 365000_480x270)

*Until the api regens (The streamers internet drops)

a look at the .m3u8
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:506579247
#EXT-X-TARGETDURATION:6
#EXT-X-START:TIME-OFFSET=-3.00,PRECISE=NO
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:21.000741924+09:00
#EXTINF:3.000000,
506579247.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:24.000744924+09:00
#EXTINF:3.000000,
506579248.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:27.000747924+09:00
#EXTINF:3.000000,
506579249.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:30.000750924+09:00
#EXTINF:3.000000,
506579250.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:33.000753924+09:00
#EXTINF:3.000000,
506579251.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:36.000756924+09:00
#EXTINF:3.000000,
506579252.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:39.000759924+09:00
#EXTINF:3.000000,
506579253.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:42.000762924+09:00
#EXTINF:3.000000,
506579254.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:45.000765924+09:00
#EXTINF:3.000000,
506579255.ts
#EXT-X-PROGRAM-DATE-TIME:2018-02-27T22:22:48.000768924+09:00
#EXTINF:3.000000,
506579256.ts
```
**Update** found hlsvariant://... and it works but a proper plugin is appreciated

**Comment by brachna** [comment]
Thanks for pointing out his site, didn't know about it.
Can't get live status and useful information using requests. It's missing in response when using requests, but is there when using real browser.

**Comment by gravyboat** [comment]
This seems like a pretty small site, what kind of financial support model do they have for the artists? You already get pretty screwed as an artist so I would hate for Streamlink to steal a chance at them earning ad revenue.

**Comment by brachna** [comment]
Ok, so it uses JavaScript all over the place. Personally, I'm trying to experiment with headless browser. Something like that is way heavy for streamlink though.

**Comment by back-to** [comment]
> This seems like a pretty small site

> the site consists of over 20 million members, over 43 million submissions,
and receives over 3.7 billion page views monthly
https://en.wikipedia.org/wiki/Pixiv

---

@brachna #1550 there is a working plugin

**Comment by brachna** [comment]
@back-to thanks, but it doesn't seem to work.
https://sketch.pixiv.net/@mettauti_33 (SFW link) was tested and nothing was found while he was streaming.
Are you sure the plugin was working for you?
data["LiveStore"]["lives"] can't be found using requests, because of no JS runtime, that's why it shows up for me in browser only. I would be glad to be wrong.

**Comment by back-to** [comment]
yes @brachna 

```
streamlink -l debug "https://sketch.pixiv.net/@mettauti_33" best

[cli][debug] Python:     3.6.4
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@mettauti_33
[plugin.pixiv][debug] Not a videopage
[plugin.pixiv][debug] Found new path: /@mettauti_33/lives/9150240836817284495
[plugin.pixiv][info] Owner ID: 10285380
[plugin.pixiv][debug] HLS URL: https://hlsa3.pixivsketch.net/.../index.m3u8
[cli][info] Available streams: 270p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 507013410; Last Sequence: 507013419
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 507013417; End Sequence: None
[stream.hls][debug] Adding segment 507013417 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 507013418 to queue
[stream.hls][debug] Adding segment 507013419 to queue
[stream.hls][debug] Download of segment 507013417 complete
[cli][info] Starting player: /usr/bin/mpv
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 507013418 complete
[stream.hls][debug] Download of segment 507013419 complete
[stream.hls][debug] Reloading playlist
```

**Comment by brachna** [comment]
Interesting.
What happens when you do something like
```
import streamlink
url = "https://sketch.pixiv.net/@mettauti_33"
streams = streamlink.streams( url )
print( str( streams ) )
```
Does it find it?

**Comment by brachna** [comment]
I now understand what happened.
What works are SFW streams, but not NSFW streams. You have to be logged-in to see them.
I was logged-in to Pixiv in my browser, so I could see all streams.

**Comment by gravyboat** [comment]
@back-to Huh, when I went on the site there was barely anyone watching the most popular stream and it only went down from there.

**Comment by hatabbich** [comment]
no, this is not for a stealing or something.. for me, it's a lesson for draw.. they have a REALLY awesome artists, whos make in stream wonderful work from sketch to final stage, it can be long 6-8 hour
and i really glad that i can saw and learn from it.. im trying to draw guro pics so NSFW is 1 source of this lessons, where you can see how to properly draw pu*sy, p*nis, internal organs and other stuff.

**Comment by back-to** [comment]
@brachna 

you only need a login for the userpage,
if you try to open an url with `/lives/--ID--` it should work

but I added a Login option for the userpage.
https://github.com/back-to/streamlink/commit/8d7a5c6afd832e26af3cb162991c181c71318443

**Comment by brachna** [comment]
@back-to thanks man, I solved the issue by logging-in to Pixiv. I use streamlink api inside my own scripts, but I'm sure people will find this option useful.
