### ISSUE TITLE
URL building in plugins

### ISSUE THREAD

**Issue by amurzeau** [streamlink/streamlink#1519]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [X] This is a plugin (improvement) request.
- [X] I have read the contribution guidelines.

### Description

Many plugins manipulate URLs to retrieve the underlying stream url.
An example: https://github.com/streamlink/streamlink/blob/b839cfd76b63eec3646a58ca19d7be560c422592/src/streamlink/plugins/dailymotion.py#L235

While uploading the previous version of streamlink to Debian, Paul Wise suggested to improve URL handling using something to manipulate URL safely which would understand, for example, query parameters and encode them.

What do you think about adding a URL utility class that would take care of URL handling ?
I though about something like `string.format` or `%` but urlencoding every parameters. I'm not sure though that this URL handling improvement can be used in every URL manipulations.

As an example, if the first string contains query parameters, the concatenation with `/videos` won't work (the result would be like `https://dailymotion.com/first_path?param1=data/videos`).
In this very case, `USER_INFO_URL` does not contains query parameters, but `username` might contains special characters.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
In this case, `urljoin` is probably the correct method. However, I'm sure we could whip up a nice `urlformat` method that could be used here :)

**Comment by beardypig** [comment]
A review of all the plugins and how they build URLs needs to be done. We should have some guidelines on how to implement this kind of URL building. Most of the plugins are offenders, so we should sort it out. I have it on my todo list :)

**Comment by back-to** [comment]
closing as https://github.com/streamlink/streamlink/pull/1675 is already merged

new plugins or plugin updates can use the new tools,
but updating every old plugin is to much work for a low value.

https://github.com/streamlink/streamlink/blob/cd6f94a5a4ee83cb5b61a295df9e13956bcfcb27/tests/test_utils_url.py#L39-L48
