### ISSUE TITLE
Youtube Livestream download starts then instantly closes

### ISSUE THREAD

**Issue by Zenostop** [streamlink/streamlink#1520]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Youtube livestream download starts then instantly closes. Playing the file shows that it only downloaded about 1 second. The video and audio for that 1 second are fine though.

```
streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "video.ts" https://www.youtube.com/watch?v=mwhZ5C-Z1I8 best
```
This command has worked before dozens of time on the same channel. Thought it has been a few months since I last used it.
### Expected / Actual behavior

Supposed to download the entire livestream from the start but only downloads 1 second at the current moment before quitting.

### Reproduction steps / Explicit stream URLs to test

1. https://www.youtube.com/watch?v=mwhZ5C-Z1I8

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
[Streamlink for Windows v0.10.0 - Git b839cfd]
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=mwhZ5C-Z1I8
[plugin.youtube][debug] get_video_info - 1: Found data
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[stream.][debug] Opening http substream
[stream.][debug] Opening http substream
[stream.mp4mux-ffmpeg][debug] ffmpeg command: \streamlink-portable-master\Streamlink for Windows (Compiled)\Releases\Streamlink\Dependencies\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\ffmpeg-7860-872 -i \\.\pipe\ffmpeg-7860-444 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-7860-872
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-7860-444
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.mp4mux-ffmpeg][debug] Pipe copy complete: \\.\pipe\ffmpeg-7860-444
[stream.mp4mux-ffmpeg][debug] Pipe copy complete: \\.\pipe\ffmpeg-7860-872

[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams
[End of Streamlink for Windows with ExitCode 0]
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
the HTTPStream url is just 5 sec long,
it won't continue without a refresh but the refresh is 5 sec as well.

https://github.com/streamlink/streamlink/blob/5d81d68c7a47e931f050632ae7cddb3b044971b4/src/streamlink/plugins/youtube.py#L288-L289

the behavior was maybe different before.

---

the `muxed stream` _1080p60_ won't work,
but you could try a `hls stream` _1080p_ for now.
