### ISSUE TITLE
Feature request: Merge both streamlink and youtube-dl

### ISSUE THREAD

**Issue by timofonic** [streamlink/streamlink#1522]
**_NOTE: Feature request replicated at [streamlink issue tracker](https://github.com/rg3/youtube-dl/issues/15741) too!_**

Why merging @streamlink and @youtube-dl?

### Pros:
- [X] Both projects are developed in Python. There would be a lot of code sharing over time after the merge.
- [X] Both projects have complementary goals. Merging them would make it a definitive media stream solution/library.
- [X] Users would find easier to use only one solution for media streaming and popularity may rise.
- [X] One project would mean program would integrate it easier than both. Currently youtube-dl is integrated in many media players, but streamlink not
### Cons:
- [ ] Need to massively merge bothj projects, potentially refactoring and rewriting lots of stuff.
- [ ] Need to reach a consensus in new project code style.
- [ ] Need to reach a consensus in what project name to use.

## (Old) related discussions

- [youtube-dl?](https://github.com/streamlink/streamlink/issues/7) - 17 Sep 2016 / 19 Nov 2016

(please mention more of them if you find these, just for research, archival and historical purposes)

**Comment by beardypig** [comment]
Not really anything that either team of developers would entertain, effectively you'd be creating a new project - or porting the plugins and some of the features of streamlink over to youtube-dl. Can't see this happening :)

**Comment by gravyboat** [comment]
I'm going to close this as @beardypig has brought up most of the points. Not only would the work not really be worth it, the apps serve different groups of users.
