### ISSUE TITLE
Content.uplynk (ESPN) streams not playing in video player

### ISSUE THREAD

**Issue by Ike348** [streamlink/streamlink#1528]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Streams from content.uplynk.com (usually ESPN) do not stream properly to a video player.

### Expected / Actual behavior

Expected behavior: Stream should open in the default video player (in my case, VLC) and play smoothly.

Actual behavior: Only the current frame opens in the video player, and the stream does not play.

### Reproduction steps / Explicit stream URLs to test

1. Any streams from WatchESPN fail, for example, this [link](http://www.espn.com/watch/player?id=3303583). To get the direct link to the stream, use a URL snooper to get something like https://content.uplynk.com/event/ext/d09b16c953aa40c98dd8c513526aca5a/a110278784.m3u8?ad.kv=_fw_ae,null,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&exp=1520034034&ptid=ESPN3_Events_VDMS&rn=456880232&tc=1&oid=d09b16c953aa40c98dd8c513526aca5a&linearv=4&ad=espnlive&ad.csid=watchespn:web:espn3:live:en&ad.caid=a110278784&eid=a110278784&euid=ESPN3_VDMS&ct=e&sig=7d240c98dd892c4388e4e1e045f51ee090077e3d675af1a811e1be35f9eb305f

Note that the above link will not work, but it should look like something similar.

2. Running this basic code creates the issue: `streamlink "hlsvariant://https://content.uplynk.com/event/ext/d09b16c953aa40c98dd8c513526aca5a/a110278784.m3u8?ad.kv=_fw_ae,null,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&exp=1520034034&ptid=ESPN3_Events_VDMS&rn=456880232&tc=1&oid=d09b16c953aa40c98dd8c513526aca5a&linearv=4&ad=espnlive&ad.csid=watchespn:web:espn3:live:en&ad.caid=a110278784&eid=a110278784&euid=ESPN3_VDMS&ct=e&sig=7d240c98dd892c4388e4e1e045f51ee090077e3d675af1a811e1be35f9eb305 best`

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
streamlink "hlsvariant://https://content-aeui1.uplynk.com/event/6533f88b1ef244c59aa6215394a89740/d.m3u8?ad.kv=_fw_ae,null,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&exp=1520034215&ptid=ESPN3_Events_VDMS&rn=308854181&tc=1&oid=d09b16c953aa40c98dd8c513526aca5a&linearv=4&ad=espnlive&ad.csid=watchespn:web:espn3:live:en&ad.caid=a110278784&eid=a110278784&euid=ESPN3_VDMS&ct=e&sig=2ee5492a186a4ad1dd978fd97a9a2ce82479cba5a3806a809310fc9baa337623&pbs=a9870951977e4304a7df5e460724147c" best -l debug
[cli][info] Found matching plugin hls for URL hlsvariant://https://content-aeui1.uplynk.com/event/6533f88b1ef244c59aa6215394a89740/d.m3u8?ad.kv=_fw_ae,null,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&exp=1520034215&ptid=ESPN3_Events_VDMS&rn=308854181&tc=1&oid=d09b16c953aa40c98dd8c513526aca5a&linearv=4&ad=espnlive&ad.csid=watchespn:web:espn3:live:en&ad.caid=a110278784&eid=a110278784&euid=ESPN3_VDMS&ct=e&sig=2ee5492a186a4ad1dd978fd97a9a2ce82479cba5a3806a809310fc9baa337623&pbs=a9870951977e4304a7df5e460724147c
[plugin.hls][debug] URL=https://content-aeui1.uplynk.com/event/6533f88b1ef244c59aa6215394a89740/d.m3u8?ad.kv=_fw_ae,null,_fw_euid,41D65629-4BD2-4779-A7E2-85FF9405478E&exp=1520034215&ptid=ESPN3_Events_VDMS&rn=308854181&tc=1&oid=d09b16c953aa40c98dd8c513526aca5a&linearv=4&ad=espnlive&ad.csid=watchespn:web:espn3:live:en&ad.caid=a110278784&eid=a110278784&euid=ESPN3_VDMS&ct=e&sig=2ee5492a186a4ad1dd978fd97a9a2ce82479cba5a3806a809310fc9baa337623&pbs=a9870951977e4304a7df5e460724147c; params={}
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 16 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.hls][debug] Download of segment 16 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 17 complete
[stream.hls][debug] Download of segment 18 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Download of segment 19 complete
[stream.hls][debug] Download of segment 20 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[stream.hls][debug] Download of segment 21 complete
[stream.hls][debug] Download of segment 22 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 23 to queue
[stream.hls][debug] Adding segment 24 to queue
[stream.hls][debug] Download of segment 23 complete
[stream.hls][debug] Download of segment 24 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 25 to queue
[stream.hls][debug] Adding segment 26 to queue
[stream.hls][debug] Download of segment 25 complete
[stream.hls][debug] Download of segment 26 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 27 to queue
[stream.hls][debug] Adding segment 28 to queue
[stream.hls][debug] Download of segment 27 complete
[stream.hls][debug] Download of segment 28 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 29 to queue
[stream.hls][debug] Adding segment 30 to queue
[stream.hls][debug] Download of segment 29 complete
[stream.hls][debug] Download of segment 30 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 31 to queue
[stream.hls][debug] Adding segment 32 to queue
[stream.hls][debug] Adding segment 33 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 31 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

It is also worth noting that if instead of actually playing the stream, I want to output it to a file, `-o file.ts` works perfectly

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
it's maybe the same as with youtube live,
it won't work with vlc 2 but should work with vlc 3

could you try to use vlc 3 or a different player

**Comment by johnmaxtexas** [comment]
share some basic step to install streamlink in my windows pc 
![streamlink](https://user-images.githubusercontent.com/37410053/37470615-e401e350-288d-11e8-81af-9036da2fdd6e.png)
here will see youtube video facing error how to fix it

**Comment by bastimeyer** [comment]
@johnmaxtexas what you are posting here is completely unrelated to this issue thread. Please open a new issue and follow the issue template if you think that there is a Streamlink bug which needs to be resolved. Your youtube link however is working fine on my machine using the latest Streamlink version, so you should try to reinstall Streamlink first. I'm not going to delete that post, but please don't comment in this thread again.
Sorry about the noise to everyone else...

**Comment by Ike348** [comment]
@back-to Sorry I've been late to respond to this, but using VLC 3 works. Thanks!
