### ISSUE TITLE
Make some basic documentation on making Plugins

### ISSUE THREAD

**Issue by Brainzyy** [streamlink/streamlink#153]
I would really appreciate it if someone could make a list of basic pointers on how to start with this. It is, at least for me, a difficult process to analyze other plugins to figure out how it works.

**Comment by BeMaXa** [comment]
I agree with Brainzyy. I guess you need to have a lot of experience in programming etc but some examples, of present plugins, with explanations of the code related to the source of the webpage would be nice to have. Then I guess the number of pugins can increase when more people understand the syntax.. But thanks for a very nice software. I use it to feed some IP channels into my TV server (tvheadend).  The performance and reliability is excellent..

**Comment by gravyboat** [comment]
This is already discussed here: https://github.com/streamlink/streamlink/issues/117 can you please add any additional comments/concerns in that one? I'm going to close this one out.

**Comment by Brainzyy** [comment]
Sorry about that @gravyboat, I must've looked over that one, because I looked over all the issues... My bad

**Comment by gravyboat** [comment]
@Brainzyy Hah no worries, I've done the exact same thing myself!

**Comment by nickiman** [comment]
Hi,
Sorry if I re-open a closed discussion but, I would like to know how @BeMaXa or someone else does to integrate streamlink with tvheadend.
I´ve been googling that question but no success...
Thanks
