### ISSUE TITLE
[Plugin Request] http://www.xemtvhd.com/2016/01/vtv1-online-kenh-vtv1-truc-tuyen.html

### ISSUE THREAD

**Issue by 314pi** [streamlink/streamlink#1535]
----

### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Thank you for your efforts to make a great tool. I tried to figure out how to create a plugin but not much knowledge. I hope you add a plugin for this site. Thank you !

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. http://www.xemtvhd.com/2016/01/vtv1-online-kenh-vtv1-truc-tuyen.html 
2. http://www.xemtvhd.com/2016/01/vtv3-online-kenh-vtv3-truc-tuyen.html 
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Can anyone with more familiarity with Vietnamese stations give some insight into this site? I went to it and based on some quick Googling it looks like a bunch of stolen TV stations to me.

**Comment by 314pi** [comment]
I am Vietnamese and regularly watch TV via internet. In Vietnam, copyright law is not complete and not close so some sites like this still work.

**Comment by 314pi** [comment]
I suggest using the new web is: http://vtvgo.vn/xem-truc-tuyen-kenh-vtv3-3.html (and http://vtvgo.vn/xem-truc-tuyen-kenh-vtv1- 3.html). This is the official web site of Vietnam Television. And another site is: http://vtv.vn/truyen-hinh-truc-tuyen/vtv1.htm
