### ISSUE TITLE
ustream closes connection after some time

### ISSUE THREAD

**Issue by etam** [streamlink/streamlink#1545]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

When playing ustream live video it closes after few minutes.

### Reproduction steps / Explicit stream URLs to test

Platform: RaspberryPI 3, Raspbian Strech
Command line:
```
streamlink \
    -v -l debug \
    http://www.ustream.tv/channel/live-iss-stream best \
    --player "omxplayer --adev hdmi --no-keys --live" \
    --player-continuous-http
```

### Logs

[play_iss.log](https://github.com/streamlink/streamlink/files/1799454/play_iss.log)

**Comment by back-to** [comment]
@etam  could you try this
https://github.com/streamlink/streamlink/issues/1491#issuecomment-369190030

**Comment by etam** [comment]
@back-to 
Seems to be working. Thanks!

It would be good idea to add this to https://streamlink.github.io/players.html

**Comment by gravyboat** [comment]
@etam It's already part of the documentation.
