### ISSUE TITLE
Missing #EXTM3U error

### ISSUE THREAD

**Issue by Johnny-Smithy** [streamlink/streamlink#1548]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Streamlink provides a Missing #EXTM3U error

### Expected / Actual behavior

Expected: Streamlink saves m3u8 to file

Actual: Stream is found but stops immediately and displays error

### Reproduction steps / Explicit stream URLs to test

1.  Inspect website source and search for m3u8 
2. Given link is "http://nlds20.dal.neulion.com/play?url=%2Fnlds_vod%2Fbtn2go%2Fvod%2F2018%2F03%2F10%2F10862%2F2_10862_albany_btn2_2017_b_whole_1_pc.mp4&plid=76bc8160bdbd9674f06a8d1bf69e1be0&auth_key=4fd5eb40f886be64b07a8a01ae9a6b1f-1520835703-32-*.m3u8;*.ts;*.mp4&nltid=btn2go&nltdt=0"
3. Using streamlink.exe "hlsvariant://(Link here)" 540p -o copy.ts pasted into CMD

Opening the m3u8 link directly provides this text

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <channel version="3.5" currentTime="0" defaultStreamIndex="3"><streamDatas><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_3000.mp4" blockDuration="2000" bitrate="3072000" duration="6623950"><video width="1280" height="720" fps="29.970030" bitrate="2983936" codec="avc1"/><audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="124928" codec="mp4a"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_1600.mp4" blockDuration="2000" bitrate="1638400" duration="6623950"><video width="960" height="540" fps="29.970030" bitrate="1521664" codec="avc1"/><audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="93184" codec="mp4a"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_1200.mp4" blockDuration="2000" bitrate="1228800" duration="6623950"><video width="640" height="360" fps="29.970030" bitrate="1175552" codec="avc1"/><audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="56320" codec="mp4a"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_800.mp4" blockDuration="2000" bitrate="819200" duration="6623950"><video width="640" height="360" fps="29.970030" bitrate="787456" codec="avc1"/><audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="56320" codec="mp4a"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_400.mp4" blockDuration="2000" bitrate="409600" duration="6623950"><video width="400" height="224" fps="29.970030" bitrate="382976" codec="avc1"/><audio channelCount="2" samplesRate="44100" sampleBitSize="16" bitrate="56320" codec="mp4a"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData></streamDatas><imageStreamDatas><streamData url="/nlds_vod/btn2go/vod/2018/03/10/10862/2_10862_albany_btn2_2017_b_whole_1_thumbnail.images" duration="6625013"><image width="112" height="86" format="jpg" interval="5000"/><httpservers><httpserver name="nlds20.cdnl3nl.dal.neulion.com" port="80"/><httpserver name="nlds20.cdnak.dal.neulion.com" port="80"/></httpservers></streamData></imageStreamDatas></channel>`

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

Microsoft Windows [Version 10.0.16299.248]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\*****>streamlink.exe "hlsvariant://http://nlds20.dal.neulion.com/play?url=%2Fnlds_vod%2Fbtn2go%2Fvod%2F2018%2F03%2F10%2F10862%2F2_10862_albany_btn2_2017_b_whole_1_pc.mp4&plid=c5cbaa15e329cfd2fac4cd5d56610493&auth_key=69b49c746b9b696037371ae358f63cba-1520831983-32-*.m3u8;*.ts;*.mp4&nltid=btn2go&nltdt=0" 540p -o copy.ts
[cli][info] Found matching plugin stream for URL hlsvariant://http://nlds20.dal.neulion.com/play?url=%2Fnlds_vod%2Fbtn2go%2Fvod%2F2018%2F03%2F10%2F10862%2F2_10862_albany_btn2_2017_b_whole_1_pc.mp4&plid=c5cbaa15e329cfd2fac4cd5d56610493&auth_key=69b49c746b9b696037371ae358f63cba-1520831983-32-*.m3u8;*.ts;*.mp4&nltid=btn2go&nltdt=0
error: Failed to parse playlist: Missing #EXTM3U header

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
@Johnny-Smithy We had to remove the neulion plugin due to a DMCA takedown: https://github.com/streamlink/streamlink/issues/1493.

**Comment by back-to** [comment]
your url is **not a hls (m3u8) file**

Example of an m3u8 file
```
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
http://example.com/movie1/fileSequenceA.ts
#EXTINF:10.0,
http://example.com/movie1/fileSequenceB.ts
#EXTINF:10.0,
http://example.com/movie1/fileSequenceC.ts
#EXTINF:9.0,
http://example.com/movie1/fileSequenceD.ts
#EXT-X-ENDLIST
```
https://developer.apple.com/library/content/technotes/tn2288/_index.html

---

if you find the m3u8 url,
you will most likely need cookies and headers to use it with `hls://`
