### ISSUE TITLE
kablowebtv.com

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#1549]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

members can register via the page and watch livestreams in hd, legal ! 

### Expected / Actual behavior

Silverlight is required to run on windows machines when the page is called

 https://www.kablowebtv.com/WebTV/canli_tv

**Comment by dreamboxco** [comment]
if i give you account login, can you make  a plugin?
The Site work only with silverlight

**Comment by back-to** [comment]
if they only use silverlight, it probably won't work

or

can you get some m3u8 files with different User-Agents *Android / IPhone*?

**Comment by back-to** [comment]
@dreamboxco 
If you want, you can send me an email with your login informations
and I will take a look if there are m3u8 urls.

you can find the email here
https://gist.github.com/back-to/febd930985447e07d95345c0d5a7cf93

**Comment by beardypig** [comment]
The question is, is it SmoothStreaming? I started work on supporting that too :)

**Comment by back-to** [comment]
No response received.
