### ISSUE TITLE
No Audio Manifest Two Audio Sources

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#1552]
Hi when i open the below stream is opens the video and pipes to vlc but there is no audio.Looking below at the manifest it looks like they have separate chinease and english audio streams.

What command would i need to use to open this video and play with the eng audio track please.

Thanks 

#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="chi",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="chi",URI="Stream(05)/index.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="eng",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="eng",URI="Stream(06)/index.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=420765,RESOLUTION=480x270,AUDIO="audio"
Stream(01)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=870330,RESOLUTION=640x360,AUDIO="audio"
Stream(02)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1892069,RESOLUTION=1280x720,AUDIO="audio"
Stream(03)/index.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3485982,RESOLUTION=1920x1080,AUDIO="audio"
Stream(04)/index.m3u8

**Comment by dubl1n** [comment]
--hls-audio-select

https://streamlink.github.io/cli.html#cmdoption-hls-audio-select

**Comment by willbrow** [comment]
Thank you.
