### ISSUE TITLE
Best practices for storing a livestream in mp4 using ffmpeg (for a website)?

### ISSUE THREAD

**Issue by TPME** [streamlink/streamlink#1555]
### Checklist

- [x] This is a question.
- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hi everyone. I am currently capturing some livestreams and store them in an mp4 using ffmpeg. Later those mp4's are then served to visitors on a site using HTML 5's video player. Currently I am using this command:

`streamlink STREAM_URL "720p,480p,best" --hls-start-offset 00:02:00 --stdout | ffmpeg -i pipe:0 -c copy -bsf:a aac_adtstoasc -t 00:02:00 -y -movflags +faststart -threads 0 video.mp4`

The time parameter is on purpose to capture the last 2 minutes of the stream.. Still, I am quite new to codecs and formats/containers, so I am not exactly sure why I need `-bsf:a aac_adtstoasc`. Is my current configuration optimal for creating mp4's that are stored and served o nthe web? I've read online that I should use the H.264 codec for creating mp4 files - why is that not in the code (I got the code from somewhere here in the issues section)?

### Expected / Actual behavior

Expected: I can easily download, encode, format, store and serve a video on the web.

Actual: I am not sure if my current setup is the best practice.

### Reproduction steps / Explicit stream URLs to test

See the command above.

**Comment by bastimeyer** [comment]
#1175
