### ISSUE TITLE
http://live.kuaishou.com

### ISSUE THREAD

**Issue by huskyyyyy** [streamlink/streamlink#1558]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.
I got an error when I tried to stream this website
"error: No plugin can handle URL: ""
Is it possible to have support for this website? thank you very much!
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This is an absolutely trash plugin request(?) if that's what it is. You're a brand new user who created an account just to make this issue, you've provided absolutely no troubleshooting or attempts to help us, and haven't even modified the template. You have done less than the bare minimum when you're asking us to do work for free, please improve the request and actually try to do some digging regarding how the site works.

**Comment by huskyyyyy** [comment]
If you cant do it then don't, no need to post a lame post venting about new users not doing this or that. You don't like my post just delete it or close it. Really shows the shitty attitude of yours. Heck I was even thinking of donating to you guys just like I donate on stream sites, but after seeing your attitude I take that back. 

P.S 
You want to me contribute? Fine, here:
The portable exe does not work on windows 10.
![capture](https://user-images.githubusercontent.com/37466173/37553032-348d06b6-297d-11e8-9677-a271d97d04fb.PNG)
