### ISSUE TITLE
Streamlink + DeepSpeech (or other text-to-speech) for live auto-subtitles

### ISSUE THREAD

**Issue by hpr** [streamlink/streamlink#1561]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
It would be nice, if possible, to optionally integrate Streamlink with [mozilla/DeepSpeech](https://github.com/mozilla/DeepSpeech) via a command-line flag to get live subtitles on streams for video players that support subtitles. Aside from being more convenient for many, it would also help those who are hearing-impaired.

### Expected / Actual behavior
If provided a command-line flag, Streamlink should try to feed audio to DeepSpeech, and return the output as live subtitles which are then handled by the video player. If necessary, it could be done in chunks for computers where the realtime factor is greater than 1. The Python library for deepspeech could be used.

Keywords for searchers: TTS, text to speech, transcription, transcribe.

**Comment by bastimeyer** [comment]
This kind of feature doesn't belong into Streamlink. You have to build your own application around Streamlink if you want to do anything with video/audio analysis or manipulation. You can use Streamlink's Python API or CLI for that...
