### ISSUE TITLE
can't catch pixiv url

### ISSUE THREAD

**Issue by hatabbich** [streamlink/streamlink#1566]
Hello, im newbie in this kind of app so, how can i catch stream in some video player??
my step; open cmd with shift inside streamlink folder >> put in cmd "streamlink --pixiv-username=******@yahoo.com --pixiv-password=SA23d****** https://sketch.pixiv.net/@obfx-totan/lives/937164925631538376" (without "") pls help me :(
My system WIndows 8.1 x64 have a VLC or GOM player

**Comment by gravyboat** [comment]
The pixiv plugin isn't live yet other than in the nightly build, it was only merged into master 4 days ago: https://github.com/streamlink/streamlink/pull/1550. You can add it manually if you want, or wait for the next release in a few weeks.
