### ISSUE TITLE
some vaughnlive.tv site cannot work, VLC close immediately

### ISSUE THREAD

**Issue by c769214** [streamlink/streamlink#157]
streamlink  http://www.vaughnlive.tv/wtt001 best
[cli][info] Found matching plugin vaughnlive for URL http://www.vaughnlive.tv/wtt001
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended

but some links are normal without problem .... please check 
this link is ok : 
streamlink  http://www.vaughnlive.tv/al_history best

**Comment by mmetak** [comment]
Tried your first link and it works just fine. Vlc opens it and plays.
(vlc-3.0.0 & vlc-2.2.4)

**Comment by c769214** [comment]
@mmetak  @gravyboat 

I don't know what is exactly the problem .... one link is okay but another link was closed immedidately, but they are same from vaughnlive.tv 

not just one got failed... but just one example : 

streamlink http://www.vaughnlive.tv/wtt001 best
using --stream-url you can see : 

streamlink --stream-url http://www.vaughnlive.tv/wtt001 best
rtmp://50.7.188.2:1935/live playpath=live_wtt001 swfUrl=http://vaughnlive.tv/4436546790/swf/VaughnSoftPlayer.swf app=live?s4u4n7HNn0vZm2pGVRckxRn2tow79b2Z swfVfy=1 live=1 pageUrl=http://www.vaughnlive.tv/wtt001

and it seems normal . ...but if you using mplayer and changed the command into..... 
streamlink -p "mplayer " http://www.vaughnlive.tv/wtt001 best

then it will be okay to play
Maybe this is VLC issue.... so how can I troubleshoot this in Ubuntu environment ?

**Comment by mmetak** [comment]
I mostly use mpv player and streamlink plays all the vaughnlive.tv streams for me.
Try running: `streamlink -p 'vlc --verbose=2 --file-logging --logfile=/tmp/vlc-log.txt' http://www.vaughnlive.tv/wtt001 best`  and check the log file if there's a clue?

**Comment by c769214** [comment]
@mmetak 

Thanks for your information, will try and let you know.... 

BTW... in the dmesg, I found the following error :  (i tried vlc and mpv and they got the same error)

[  616.072132] vlc[3951]: segfault at 7f0929ca2ac0 ip 00007f0929f25a96 sp 00007f09681e6110 error 6 in libavcodec.so.54.35.0[7f0929eb0000+5b7000]
[  653.417520] mpv[3982]: segfault at 7fe787392ac0 ip 00007fe786685a96 sp 00007ffc2a0419a0 error 6 in libavcodec.so.54.35.0[7fe786610000+5b7000]

**Comment by mmetak** [comment]
Are you running Ubuntu 14.04 LTS with old outdated versions of vlc, mpv, etc.?

Basically you can play vaughnlive.tv streams, but not in the same media player?
Some work in vlc and some in mplayer? They play fine for me in different players and different versions of them... and based on the output you pasted above it's most likely an issue on your pc. Could be a bug in libav?

You could try downloading new vlc appimage and give it a quick test?
1. https://bintray.com/probono/AppImages/download_file?file_path=VLC-3.0.0.gitfeb851a.glibc2.17-x86-64.AppImage
2. make it executable  `chmod a+x VLC*.AppImage`
3. `streamlink -p '/home/you/VLC-3.0.0.gitfeb851a.glibc2.17-x86-64.AppImage' http://www.vaughnlive.tv/wtt001 best`

**Comment by c769214** [comment]
@mmetak 

My VLC is 2.2.1 but not upgraded to 3.0 yet (as seems still too many bugs/errors in this moment)

Maybe you're right... the method you mentioned works with problem links
So seems some libav files may have corrupted/problem..... so how can I fix this? ("IF" is still stuck on vlc 2.2.1..... I have tried reinstall in the synapic package manager but seems not working)

**Comment by mmetak** [comment]
Which release of ubuntu are you currently on? I've looked at http://packages.ubuntu.com/search?arch=amd64&searchon=names&keywords=vlc  and none of the ubuntu releases have that version of vlc-2.2.1 in their official repos. You should really make sure your system is up to date first. Do you have some unofficial ppa enabled? Post more details about your system.

**Comment by mmetak** [comment]
@gravyboat this one can probably be closed. Streamlink+vaughnlive.tv work as they should and streams play fine in different players (and different versions of them) and no one else is having the same issue? The problem @c769214 seems to have is probably an outdated system.

**Comment by gravyboat** [comment]
Good stuff, I'll close this out for now.

**Comment by c769214** [comment]
@gravyboat  
Thanks and OK. Keep this closed first , tried to reinstall a new system and it still occurs sometimes (not 100% sure what's going on as I'm not sure it is a hardware / software / setting problem)
