### ISSUE TITLE
[Plugin] Motor Trend on Demand

### ISSUE THREAD

**Issue by luastoned** [streamlink/streamlink#1573]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Since [Motor Trend](https://www.motortrendondemand.com/) moved off of YouTube it's a pain to watch, so streaming would be nice.
HLS provided via kaltura.com

### Reproduction steps / Explicit stream URLs to test

1. https://www.motortrendondemand.com/detail/2005-dodge-magnum-dad-rod-build-perfect-for-hauling-kids-and-hauling-ass/0_yr0j2lme/

**Comment by back-to** [comment]
Adding new plugins where it is **difficult to get an account**,
will make the new plugin impossible to maintain.

closing
