### ISSUE TITLE
Media lookup error for specific Crunchyroll show only

### ISSUE THREAD

**Issue by Atemu** [streamlink/streamlink#1574]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

When I try to play any episode of Nekomonogatari Kuro, streamlink gives me a media lookup error.  

### Expected / Actual behavior

Fetch the available formats for any episode of Nekomonogatari Kuro from Crunchyroll.

/

```
[atemu@localhost ~]$ streamlink http://www.crunchyroll.com/nekomonogatari-black/episode-1-tsubasa-family-part-1-677667
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/nekomonogatari-black/episode-1-tsubasa-family-part-1-677667
[plugin.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
error: Media lookup error: You don't have permission to do this.
[atemu@localhost ~]$ streamlink http://www.crunchyroll.com/nekomonogatari-black/episode-2-tsubasa-family-part-2-677669
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/nekomonogatari-black/episode-2-tsubasa-family-part-2-677669
[plugin.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
error: Media lookup error: You don't have permission to do this.
[atemu@localhost ~]$ streamlink http://www.crunchyroll.com/nekomonogatari-black/episode-3-tsubasa-family-part-3-677671
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/nekomonogatari-black/episode-3-tsubasa-family-part-3-677671
[plugin.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
error: Media lookup error: You don't have permission to do this.
[atemu@localhost ~]$ streamlink http://www.crunchyroll.com/nekomonogatari-black/episode-4-tsubasa-family-part-4-677673
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/nekomonogatari-black/episode-4-tsubasa-family-part-4-677673
[plugin.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
error: Media lookup error: You don't have permission to do this.
```

### Reproduction steps / Explicit stream URLs to test

Be in the US (either physically or through VPN) or pass a US session ID to streamlink and use one of the following URLs:

1. http://www.crunchyroll.com/nekomonogatari-black/episode-1-tsubasa-family-part-1-677667
2. http://www.crunchyroll.com/nekomonogatari-black/episode-2-tsubasa-family-part-2-677669
3. http://www.crunchyroll.com/nekomonogatari-black/episode-3-tsubasa-family-part-3-677671
4. http://www.crunchyroll.com/nekomonogatari-black/episode-4-tsubasa-family-part-4-677673

### Log

```
[atemu@localhost ~]$ streamlink http://www.crunchyroll.com/nekomonogatari-black/episode-1-tsubasa-family-part-1-677667 -l debug
[cli][debug] OS:         Linux-3.4.113-lineageos-gbe73925-armv7l-with-arch
[cli][debug] Python:     3.6.4
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/nekomonogatari-black/episode-1-tsubasa-family-part-1-677667
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created
[plugin.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
error: Media lookup error: You don't have permission to do this.
```

### Comments, screenshots, etc.

The show is geo blocked in my country (DE), so I have to use a US session ID and that worked with every other geoblocked Crunchyroll show so far.   
I've also tried using a US VPN but that didn't make a difference either.

I have tested other geoblocked and non geoblocked Crunchyroll shows under the same conditions and they worked without any issues.

The show does not require CR Premium and plays in both the Official app and through youtube-dl.

**Comment by Risebell** [comment]
I had a similar issue as yours recently. As strange as it might sound, it seems like changing the locale settings of my system from DE to US fixed the problem. What is yours set to? Might be worth a try.

**Comment by Atemu** [comment]
My whole system uses en_US.UTF-8

**Comment by beardypig** [comment]
Try the option `--locale en_US`, to be sure - it appears the locale is set correctly, but worth a go perhaps.

**Comment by Atemu** [comment]
It's giving me the same error unfortunately.

Do the links work for you? I want to make sure this isn't on my end.

**Comment by gravyboat** [comment]
Doesn't work for me with the same error. Are we sure this is a Streamlink problem? There have been issues with certain crunchyroll content in the past, though it hasn't been this specific error.

**Comment by Atemu** [comment]
Is there a way to find out what exactly goes wrong?   
The error message isn't very specific and the debug output doesn't tell you anything either.

**Comment by gravyboat** [comment]
@beardypig You don't need one, this is a publicly available video (I don't have one either).

**Comment by Risebell** [comment]
Atleast the first link does work for me.
That said, I first tried with a command from my shell history, which gave me the same "Media lookup error". I had to get a new session id to get it working again, as the other one was a few days old and seems to be expired.

So, did you try using a new session id?

**Comment by Atemu** [comment]
I'm always generating a new session ID using the CR API, so that could a source of error, but those session IDs have worked for all other Geo blocked shows I've watched so far (including the previous seasons of this Anime) and letting streamlink create a new session by itself while I'm in the US through a VPN doesn't work either.

**Comment by beardypig** [comment]
Some shows are very picky for some reason, you need to have a session ID generated from the US and access the stream from an IP in the US (doesn't have to be the same IP though). 
There does seem to be an issue with this particular show where it doesn't work with the session IDs generated by streamlink.
