### ISSUE TITLE
Twitch Streams not supporting --hls-start-offset of >30 seconds?

### ISSUE THREAD

**Issue by TPME** [streamlink/streamlink#1580]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

When using --hls-start-offset on a twitch live stream, it only respects values up to 30 seconds.

### Expected / Actual behavior

Expected behavior: Twitch Live stream starts with desired offset of 60 seconds.
Actual behavior: Twitch Live stream starts with offset of 30 seconds.

### Reproduction steps / Explicit stream URLs to test

streamlink https://www.twitch.tv/sodapoppin "720p,480p,best" --hls-segment-threads 10 --hls-start-offset 00:01:00 --stream-priority "hls,hds,rtmp,http,akamaihd,*" --loglevel debug --force --output fetch.mp4

### Logs

```
[cli][debug] OS:         Linux-4.14.17-x86_64-linode99-x86_64-with-centos-6.9-Final
[cli][debug] Python:     3.6.1
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/sodapoppin
[plugin.twitch][debug] Getting live HLS streams for sodapoppin
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Time offsets negative for live streams, skipping back 60 seconds
[stream.hls][debug] First Sequence: 6209; Last Sequence: 6223
[stream.hls][debug] Start offset: -60; Duration: None; Start Sequence: 6209; End Sequence: None
[stream.hls][debug] Adding segment 6209 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 6210 to queue
[stream.hls][debug] Adding segment 6211 to queue
[stream.hls][debug] Adding segment 6212 to queue
[stream.hls][debug] Adding segment 6213 to queue
[stream.hls][debug] Adding segment 6214 to queue
[stream.hls][debug] Adding segment 6215 to queue
[stream.hls][debug] Adding segment 6216 to queue
[stream.hls][debug] Adding segment 6217 to queue
[stream.hls][debug] Adding segment 6218 to queue
[stream.hls][debug] Adding segment 6219 to queue
[stream.hls][debug] Adding segment 6220 to queue
[stream.hls][debug] Adding segment 6221 to queue
[stream.hls][debug] Adding segment 6222 to queue
[stream.hls][debug] Adding segment 6223 to queue
[stream.hls][debug] Download of segment 6209 complete
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 6210 complete
[stream.hls][debug] Download of segment 6211 complete
[stream.hls][debug] Download of segment 6212 complete
[stream.hls][debug] Download of segment 6213 complete
[stream.hls][debug] Download of segment 6214 complete
[stream.hls][debug] Download of segment 6215 complete
[stream.hls][debug] Download of segment 6216 complete
[stream.hls][debug] Download of segment 6217 complete
[stream.hls][debug] Download of segment 6218 complete
[stream.hls][debug] Download of segment 6219 complete
[stream.hls][debug] Download of segment 6220 complete
[stream.hls][debug] Download of segment 6221 complete
[stream.hls][debug] Download of segment 6222 complete
[stream.hls][debug] Download of segment 6223 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6224 to queue
[stream.hls][debug] Adding segment 6225 to queue
[stream.hls][debug] Adding segment 6226 to queue
[stream.hls][debug] Download of segment 6224 complete
[download][fetch.mp4] Written 7.7 MB (5s @ 1.5 MB/s)                                                                                      [stream.hls][debug] Download of segment 6225 complete
[stream.hls][debug] Download of segment 6226 complete
```

### Comments, screenshots, etc.

Segments 6209-6223 are downloaded instantly and work as intended, however those *probably* (did not verify this) only sum up to 30 seconds of duration. After that (segment 6224-6226), streamlink waits and occasionally downloads new segments. I exited the program at segment 6226 manually, then checked the saved video file for its duration: only 36 seconds (instead of >60 seconds).

The same commands works fine on other livestreaming sites, going back in time for 60 seconds at the start.

**Comment by back-to** [comment]
> [stream.hls][debug] Time offsets negative for live streams, skipping back 60 seconds

Twitch does not support **Instant Replay** from Livestreams,
some **segments** are already **not available**.

---

You will have to use the VOD url and the time you want there.

and you can automatically close the stream after X time with `--hls-duration 00:01:00`

https://streamlink.github.io/cli.html#cmdoption-hls-duration

---

`streamlink https://www.twitch.tv/videos/243515460 best --hls-start-offset 03:11:00 --hls-duration 00:01:00 -l debug -o test.ts`
