### ISSUE TITLE
VK VoD play is broken

### ISSUE THREAD

**Issue by OneCrazyRussian** [streamlink/streamlink#1584]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
VK plugin doesn't support current URLs for VK.com videos/VoDs
### Reproduction steps / Explicit stream URLs to test
https://vk.com/video44031131_456239067
https://vk.com/video?z=video44031131_456239067

```
PS C:\Program Files (x86)\Streamlink\bin> ./streamlink https://vk.com/video?z=video44031131_456239067%2F best
error: No plugin can handle URL: https://vk.com/video?z=video44031131_456239067%2F
PS C:\Program Files (x86)\Streamlink\bin> ./streamlink https://vk.com/video44031131_456239067 best
error: No plugin can handle URL: https://vk.com/video44031131_456239067
```

**Comment by Alexandr1235** [comment]
In Streamlink\pkgs\streamlink\plugins\vk.py
  _url_re = re.compile(r"http(?:s)?://(\w+\.)?vk.com/video-[0-9]*_[0-9]*")   
replace with
 _url_re = re.compile(r"http(?:s)?://(\w+\.)?vk.com/video[-,0-9]*_[0-9]*")
