### ISSUE TITLE
MTV.co.uk not downloading? Not even from the hls address.

### ISSUE THREAD

**Issue by mystic17z** [streamlink/streamlink#1585]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Can't download from mtv.co.uk, mtv.la, mtvbase.com, etc. Regular USA mtv doesn't have music videos oddly. If I am doing it wrong, how do I do it right? lol. 

### Expected / Actual behavior

I used this command 
`streamlink http://www.mtv.co.uk/white-town/videos/your-woman` 
and it says 
`error: No plugin can handle URL: http://www.mtv.co.uk/white-town/videos/your-woman`

Ok fine lol so then I did this smh 
```
streamlink hls://https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/index_4_av.m3u8?null=0&id=AgBLtAziFzDRBx6evlpU2BVX2X3SAJ7dBtbA6%2f7KfpbFQYC9akL8Es8kedPyOiXe1Ym+xUcM1GTKEg%3d%3d&hdntl=exp=1522528158~acl=%2fi%2fmtviestor%2f_*%2fintlod%2fMTVInternational%2fwmg_int%2fgb0309%2f600180%2fGB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil%2f*~data=hdntl~hmac=e24348036975987da1d94784bcae212bef30ab7d642d4205bf7f312396f90bee
```
and that didn't work lol becuase it return with 
```
[cli][info] Found matching plugin hls for URL hls://https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/index_4_av.m3u8?null=0
error: Unable to open URL: https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/index_4_av.m3u8?null=0 (403 Client Error: Forbidden for url: https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/index_4_av.m3u8?null=0)
'id' is not recognized as an internal or external command, operable program or batch file.
'hdntl' is not recognized as an internal or external command, operable program or batch file.
```

So then what am I doing wrong? haha

I copied these links from IDM directly, so I don't know? If that was the wrong way, then how do you find the correct links, etc. Lol, helps.

I'm in the USA

Thank you, come again lol.

### Reproduction steps / Explicit stream URLs to test

1. ```
    streamlink http://www.mtv.co.uk/white-town/videos/your-woman
    ```
2. ```
    streamlink hls://https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/index_4_av.m3u8?null=0&id=AgBLtAziFzDRBx6evlpU2BVX2X3SAJ7dBtbA6%2f7KfpbFQYC9akL8Es8kedPyOiXe1Ym+xUcM1GTKEg%3d%3d&hdntl=exp=1522528158~acl=%2fi%2fmtviestor%2f_*%2fintlod%2fMTVInternational%2fwmg_int%2fgb0309%2f600180%2fGB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil%2f*~data=hdntl~hmac=e24348036975987da1d94784bcae212bef30ab7d642d4205bf7f312396f90bee
    ```

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
```

### Comments, screenshots, etc.

...

**Comment by bastimeyer** [comment]
> 403 Client Error: Forbidden for url

You're using an URL which you don't have access to...
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

You also need to use quotation marks for the URL parameter if it contains an ampersand character, otherwise, your shell will interpret it as a command delimiter.

**Comment by mystic17z** [comment]
Ah I see, quotation marks, got it. Hhmm, are there any URL's in there that I might have access to, or is it the whole website? Lol, and if I do have access, how do I know which ones? Thank you.

**Comment by mystic17z** [comment]
Ah got it my fran, compared it with another software that does it automatically, and found that is needed a master.m3u8 file. Which is found under the Network tab and then XHR tab, I paused the video because so many segment files were coming out. Thank you.

`https://cp450888-vh.akamaihd.net/i/mtviestor/_!/intlod/MTVInternational/wmg_int/gb0309/600180/GB0309600180_,384x288_400_m30,448x336_600_m30,480x360_900_m30,576x432_1200_m30,640x480_1600_m30,.mp4.csmil/master.m3u8?hdnea=st%3D1522450613%7Eexp%3D1522465013%7Eacl%3D%2Fi%2Fmtviestor%2F_*%2Fintlod%2FMTVInternational%2Fwmg_int%2Fgb0309%2F600180%2FGB0309600180_%2C384x288_400_m30%2C448x336_600_m30%2C480x360_900_m30%2C576x432_1200_m30%2C640x480_1600_m30%2C.mp4.csmil%2F*%7Ehmac%3Dc7da5dbbf75cdc09ebbaeb24390ee992db1db528825577fa9d2ab57b62b33329&__a__=off&__b__=450&__viacc__=NONE`
