### ISSUE TITLE
Unable to launch any streams because of some misconfiguration 

### ISSUE THREAD

**Issue by SuvigyMishra** [streamlink/streamlink#1586]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Cannot launch any streams. Reinstalled streamlink and streamlink twitch gui multiple times.

![image](https://user-images.githubusercontent.com/36672039/38160192-260f62ae-34d7-11e8-884e-e84a854ba4c5.png)

![image](https://user-images.githubusercontent.com/36672039/38160197-403cb5d2-34d7-11e8-8f52-eccb87ac7353.png)

**Comment by bastimeyer** [comment]
Wrong repo. You're looking for this repo:
https://github.com/streamlink/streamlink-twitch-gui

And to answer your question, try uninstalling and installing Streamlink again. Simply reinstalling (currently) doesn't replace some of the files, which is a bug in Streamlink's installer.

If this doesn't help, see the Streamlink Twitch GUI wiki and check its log files, which should include more detailed error informations...
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel

Closing the thread... If you have further questions, please open a new issue on the Streamlink Twitch GUI repo.

**Comment by SuvigyMishra** [comment]
Sorry about that. I haven't used GitHub much. 
For any who might find this post with similar problem, I uninstalled the streamlink v 0.11.0 and went on to install v 0.10.0. Worked like a charm.
