### ISSUE TITLE
TVP Stream

### ISSUE THREAD

**Issue by remek30** [streamlink/streamlink#1590]
I would like to kindly ask you to add support for http://tvpstream.vod.tvp.pl/ via streamlink. There are Polish regional and information and general channels that do not require logging.

**Comment by beardypig** [comment]
Is this an official website for the TV broadcasters? It appears to be geo-blocked to Poland (I cannot read Polish, so it's hard to say exactly).

**Comment by remek30** [comment]
Yes, this is the official website nadawcy.stream TV channels with this page there is no lock geo.geoblocked are only materials VOD.

**Comment by Vangelis66** [comment]
> It appears to be geo-blocked to Poland (I cannot read Polish, so it's hard to say exactly).

> with this page there is no lock geo.geoblocked are only materials VOD.

... I can confirm the live streams of **TVP** * are not geo-fenced in my territory (Greece); though to get them working, you'd have to completely disable adblocker (uBlock Origin in my case) in that page; Firefox 52.7.3 warns me I have to enable **DRM** "_to play some audio or video on this page_", in any case, I haven't enabled (Widevine) DRM, AFAICT the live streams use a proprietary HTML5 embedded player with AppleHLS streams, e.g. for TVP3 Warszawa

`http://rsdt-waw501-228.tvp.pl/token/video/live/14812858/20180405/1332161763/c81252e6-a58e-4887-9101-6a71bdbff606/warszawa2.isml/warszawa2.m3u8`

**Comment by remek30** [comment]
I would love to streamlink TVP Stream. I live in Germany and all the streams of these local channels work without a problem. I have the IPTVPlayer plugin installed in my tuner and all these channels work there, but of course it would be a dream that they would work via streamlink and that they could be on the channel list. Here I am giving you to download the TVP Stream host to IPTVPlayer: https://ufile.io/eip8p. Maybe this will help you to add to streamlink.

**Comment by beardypig** [comment]
@filko always best to open a new one :) Can always be closed if it’s a duplicate, but it won’t get lost.
