### ISSUE TITLE
[Plugin Request] Support for bis tv online

### ISSUE THREAD

**Issue by NeySlim** [streamlink/streamlink#1592]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would it be possible to support bis tv online:
http://www.abweb.com/BIS-TV-Online/

You need an account, and without paying you can access to lucky jack tv.

It works with flowplayer, tested on linux, it works.

You can catch the manifest, for example:
http://luckyjack.akamaized.net/luckyjack.isml/manifest.m3u8?hdnts=ip=xxx.xxx.xxx.xxx~exp=1523013621~acl=/*~hmac=7a049f91e0e8af2d44edabfc3380f2fb5a37289fb197edb8d916632c8119221a

Manifest content:

```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.7.16)

# variants
#EXT-X-STREAM-INF:BANDWIDTH=775000,AVERAGE-BANDWIDTH=704000,CODECS="mp4a.40.5,avc1.77.30",RESOLUTION=426x240
luckyjack-audio101_fra=64000-video=600000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1241000,AVERAGE-BANDWIDTH=1128000,CODECS="mp4a.40.5,avc1.77.30",RESOLUTION=640x360
luckyjack-audio101_fra=64000-video=1000000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1824000,AVERAGE-BANDWIDTH=1658000,CODECS="mp4a.40.5,avc1.77.30",RESOLUTION=768x432
luckyjack-audio101_fra=64000-video=1500000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2407000,AVERAGE-BANDWIDTH=2188000,CODECS="mp4a.40.5,avc1.77.31",RESOLUTION=1280x720
luckyjack-audio101_fra=64000-video=2000000.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=75000,AVERAGE-BANDWIDTH=68000,CODECS="mp4a.40.5"
luckyjack-audio101_fra=64000.m3u8
```

If you need more info, please tell.

**Comment by back-to** [comment]
your example is from a different website

`http://www.luckyjack.tv/offre-live.aspx`

creating an account there, is not user friendly

---

do they share the same user database or does you need a different account for every website?

---

do they embed the stream in the same way on all the different websites?

**Comment by NeySlim** [comment]
You don't need a different account for every channel.
The example I gave is from the bis tv online website.
It's all embedded the same way I think, will double check today.

I can provide you a paid account.
