### ISSUE TITLE
Public IP

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#1593]
Hi,

Normally when i use streamlink on vps or dedicated server with --player-external-http --player-external-http-port=2621 i can access the stream from home with the servers ip and port but on the vps im currently using it does not work.

When i start stream it only shows local ip address 127.0.0.1 and not public ip address and i cant access stream using public ip address and port.

Can anyone advise what the change in the vps it is ubuntu and guessing its something to do with interfaces ?

**Comment by willbrow** [comment]
Its a new vps mate so its never worked from the start but normally on other vps it works.
Im having to uses ffmpeg to push as rtmp to make it work.

I will update here if i find anything as later im going to check through the interfaces and ports in detail as it seems to me that the interface is not being picked up correctly or the port is closed.

**Comment by gravyboat** [comment]
I'm going to close this since it's off-topic. We can't help with server configurations or anything along those lines.
