### ISSUE TITLE
Live 1080p60 Youtube streams don't work in 0.11

### ISSUE THREAD

**Issue by MorningLightMtn** [streamlink/streamlink#1594]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Live 1080p60 (Dash) Youtube videos can not be played or recorded using streamlink 0.11

### Expected / Actual behavior

streamlink https://www.youtube.com/watch?v=rotvUfejBoI best -o C:\str\yt2.mp4 -f should write the 1080p60 stream from youtube to the specified path. 

Instead it closes immediately upon creating a file. 

PS C:\Users\user> streamlink https://www.youtube.com/watch?v=rotvUfejBoI best -o C:\str\yt2.mp4
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=rotvUfejBoI
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
File C:\str\yt2.mp4 already exists! Overwrite it? [y/N] y

[cli][info] Stream ended
[cli][info] Closing currently open stream...

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://www.youtube.com/watch?v=rotvUfejBoI best -o C:\str\yt2.mp4

### Logs

PS C:\Users\user> streamlink https://www.youtube.com/watch?v=rotvUfejBoI best -o C:\str\yt2.mp4 -f -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=rotvUfejBoI
[plugin.youtube][debug] get_video_info - 1: Found data
[cli][info] Available streams: audio_mp4, 144p (worst), 240p, 360p, 480p, 720p, 1080p, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[stream.][debug] Opening http substream
[stream.][debug] Opening http substream
[stream.mp4mux-ffmpeg][debug] ffmpeg command: C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\ffmpeg-69204-831 -i \\.\pipe\ffmpeg-69204-360 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-69204-831
[stream.mp4mux-ffmpeg][debug] Starting copy to pipe: \\.\pipe\ffmpeg-69204-360
[stream.mp4mux-ffmpeg][debug] Pipe copy complete: \\.\pipe\ffmpeg-69204-831
[cli][debug] Pre-buffering 8192 bytes
[cli][error] Try 1/1: Could not open stream <Stream()> (No data returned from stream)
error: Could not open stream <Stream()>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[stream.mp4mux-ffmpeg][debug] Closing ffmpeg thread
[stream.mp4mux-ffmpeg][debug] Closed all the substreams

**Comment by gravyboat** [comment]
We don't currently support DASH streaming (https://github.com/streamlink/streamlink/pull/225#issuecomment-263821938), closing as duplicate.

**Comment by MorningLightMtn** [comment]
May I suggest disabling automatic selection of dash then?

**Comment by back-to** [comment]
bintray doesn't work currently https://github.com/streamlink/streamlink/issues/1476

---

you don't need the nightly just use `1080p` instead of `best`

---

but if you want it there is a way to build a portable nightly version

https://github.com/streamlink/streamlink-portable

**Comment by gravyboat** [comment]
Thanks for the note @back-to, I forgot you fixed it for HLS streams.

**Comment by mtcjayne** [comment]
Is there a reason "best" selects a stream that cannot be successfully used? Is it nontrivial to make that not happen?

**Comment by beardypig** [comment]
@mtcjayne this was fixed for live streams with #1556 and should work fine for non-live videos. This fix was release in the 0.12.1 stable version. Are you experiencing this issue with 0.12.1, if so please create a new issue so that we can work on fixing it.

**Comment by mtcjayne** [comment]
I'm using 0.11.0 so I'll upgrade.

**Comment by mtcjayne** [comment]
This works with 0.12.1
