### ISSUE TITLE
TV Player Plugin Issue

### ISSUE THREAD

**Issue by slimy1234** [streamlink/streamlink#1597]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ x] I have read the contribution guidelines.

### Description
Trying to use the tvplayer plugin for the free channels non drm.
Issue without login and with.

error: Unable to open URL: http://tvplayer.com/watch/itv ([Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure)

using these commands
streamlink https://tvplayer.com/watch/itv best

streamlink --player-continuous-http --player-external-http --player-external-http-port=12345 --tvplayer-email ********@gmail.com --tvplayer-password ***** https://tvplayer.com/watch/now90s best

Seem to get a SSL error have tried updating plugin and streamlink any ideas?

**Comment by back-to** [comment]
SSL is not a streamlink issue it's an requests/openssl issue

**You did not provide enough details about your system to get help**
you will have to find your solution at

https://github.com/requests/requests/issues/2022
