### ISSUE TITLE
Chaturabe don't record now

### ISSUE THREAD

**Issue by marabu88** [streamlink/streamlink#1598]
Plug-in for chaturbate show this error now: error: Unable to open URL: https://chaturbate.com/get_edge_hls_url_ajax/ (403 Client Error: Forbidden for url: https://chaturbate.com/get_edge_hls_url_ajax/)

**Comment by back-to** [comment]
the streamlink plugin works,

you are probably blocked by them.

```
$ streamlink "https://chaturbate.com/---/" best
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/---/
[cli][info] Available streams: 240p (worst), 360p, 480p, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by marabu88** [comment]
what me need to do?

**Comment by marabu88** [comment]
you can open this URL in your browser https://chaturbate.com/get_edge_hls_url_ajax/ ? no any errors?

**Comment by back-to** [comment]
**403** in the **Browser is correct**,
it's not meant for a Browser `GET` request

you will need to use a Browser `POST` request and add all required parameters with it.
