### ISSUE TITLE
i24 NEWS LIVE and streamlink question

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#1602]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [X ] I have read the contribution guidelines.

### Description

Streamlink will open and play this stream, but not without mpv.exe

### Expected / Actual behavior

streamlink plays the stream with mpv.exe, and I look for a solution to save the stream as well

### Reproduction steps / Explicit stream URLs to test

https://www.dailymotion.com/video/x29atae

streamlink.exe --player-passthrough=http -p "mpv.exe -vf scale=854:480" httpstream://%url% best

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

I would like to use this argument or some similar with streamlink in order to save the stream.

mpv.exe %url% --stream-dump=file

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
My main question here would be:

How can streamlink pass the stream to mpv.exe so that I can dump the stream with mpv.exe ?

mpv.exe %url% --stream-dump=file

 does not work with this url:

https://www.dailymotion.com/video/x29atae

Streamlink works with this url, I want to use this url if possible.

**Comment by back-to** [comment]
try

`streamlink https://www.dailymotion.com/video/x29atae best -O | mpv - --stream-dump=myfile`

**Comment by johnthecracker** [comment]
Doesn't work.

C:\>streamlink https://www.dailymotion.com/video/x29atae best -O | mpv - --stream-dump=myfile
Playing: -
[file] Reading from stdin...
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

Exiting... (End of file)


I get the stream playing like this with vlc-3.0.2-20180412-0409-win32, how to save the stream ?

C:\>streamlink.exe --player-passthrough=http httpstream://https://www.dailymotion.com/video/x29atae best
[cli][info] Found matching plugin http for URL httpstream://https://www.dailymotion.com/video/x29atae
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by back-to** [comment]
> error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

make sure that streamlink works for you

```
$ streamlink "https://www.dailymotion.com/video/x29atae" best -l debug
[cli][debug] OS:         Linux
[cli][debug] Python:     3.6.4
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
[plugin.dailymotion][debug] Found media ID: x29atae
[cli][info] Available streams: 180p (worst), 288p, 477p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1523662378; Last Sequence: 1523667177
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1523667175; End Sequence: None
[stream.hls][debug] Adding segment 1523667175 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1523667176 to queue
[stream.hls][debug] Adding segment 1523667177 to queue
[cli][info] Starting player: /usr/bin/mpv
[stream.hls][debug] Download of segment 1523667175 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1523667176 complete
[stream.hls][debug] Download of segment 1523667177 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1523667178 to queue
[stream.hls][debug] Adding segment 1523667179 to queue
[stream.hls][debug] Download of segment 1523667178 complete
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

after streamlink works, it should work.

record the stream

```
$ streamlink https://www.dailymotion.com/video/x29atae best -O | mpv - --stream-dump=myfile
Playing: -
[file] Reading from stdin...
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
[cli][info] Available streams: 180p (worst), 288p, 477p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...


Exiting... (Quit)
```

opening the file

```
$ mpv myfile 
Playing: myfile
 (+) Video --vid=1 (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:49 / 00:00:51 (97%) A-V:  0.001


Exiting... (Quit)
```

**Comment by johnthecracker** [comment]
You are right. I cannot figure out why it doesn't work.


C:\>streamlink "https://www.dailymotion.com/video/x29atae" best -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
[plugin.dailymotion][debug] Found media ID: x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

C:\>

**Comment by back-to** [comment]
i'm not on **0.11.0** I use the **github** version,

this PR is not in your version https://github.com/streamlink/streamlink/pull/1543
thats the fail.

**Comment by johnthecracker** [comment]
Thanks.

By the way, can we use some tweak to save the stream without -o switch,
when I have my streamlink playing with --player-passthrough=http ?

streamlink.exe --player-passthrough=http httpstream://https://www.dailymotion.com/video/x29atae best

**Comment by johnthecracker** [comment]
I try to save the stream with the player without -o switch.

This plays the stream:

C:\>streamlink.exe --player-passthrough=http httpstream://https://www.dailymotion.com/video/x29atae best
[cli][info] Found matching plugin http for URL httpstream://https://www.dailymotion.com/video/x29atae
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: C:\P\VLC\vlc.exe

I tried -p switch with parameters it didn't work.

C:\>streamlink https://www.dailymotion.com/video/x29atae best --player="vlc --demux=dump --demuxdump-file=1.dump"
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

C:\>streamlink https://www.dailymotion.com/video/x29atae best --player-passthrough=hls --player="vlc --demux=dump --demuxdump-file=2.dump"
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

C:\>streamlink https://www.dailymotion.com/video/x29atae best --player="mpv --stream-dump=myfile2"
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)

**Comment by back-to** [comment]
First update your **dailymotion.py** file if you want to use streamlink

---

`--player-passthrough=http httpstream://`

with this command your are bypassing streamlink, it uses some build in resolver from vlc / mpv

`vlc https://www.dailymotion.com/video/x29atae` will open the stream

same as

```
mpv https://www.dailymotion.com/video/x29atae
Playing: https://www.dailymotion.com/video/x29atae
[ffmpeg] Invalid return value 0 for stream protocol
[ffmpeg] Invalid return value 0 for stream protocol
[ffmpeg] Invalid return value 0 for stream protocol
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (1)...
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (2)...
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (3)...
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (4)...
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (5)...
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Connection lost! Attempting to reconnect (6)...
 (+) Video --vid=1 (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
AO: [pulse] 44100Hz stereo 2ch float
[ffmpeg] https: HTTP error 416 Requested Range Not Satisfiable
[ffmpeg] Seek failed
[ffmpeg] Invalid return value 0 for stream protocol
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:00 / 00:00:00 A-V:  0.000 Cache:  2s+443KB
[ffmpeg] Invalid return value 0 for stream protocol
[ffmpeg] Invalid return value 0 for stream protocol
AV: 00:00:01 / 00:00:00 A-V:  0.000 Cache:  1s+443KB
[ffmpeg] Seek failed


Exiting... (Quit)
```

**Comment by johnthecracker** [comment]
This works like this on LiveJasmin...

I am getting somewhere...

C:\>streamlink hls://https://ip-109-71-162-192.dditscdn.com/KarinaWeavey best --player-passthrough=hls --player="vlc --demux=dump --demuxdump-file=2.dump"
[cli][info] Found matching plugin hls for URL hls://https://ip-109-71-162-192.dditscdn.com/KarinaWeavey
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: vlc --demux=dump --demuxdump-file=2.dump

**Comment by johnthecracker** [comment]
It apperas to be plugin issue with my streamlink.

Playing main url with players works as well. It didn't work for me yesterday when I was on another computer.

I tried this on some other site with hls url, it worked as well.

streamlink hls://%url% best --player-passthrough=hls --player="vlc --demux=dump --demuxdump-file=2.dump"

It is possible to dump the stream without -o switch, using vlc or mpv.

Thank you for help.

**Comment by johnthecracker** [comment]
I can confirm that this worked on other sites than i24 NEWS LIVE, without plugin:

streamlink httpstream://%url% best --stdout | mpv - --stream-dump=myfile

streamlink httpstream://%url% best --stdout | vlc - --demux=dump --demuxdump-file=myfile.dump

With functioning plugin (one that I updated just now) this works for i24 NEWS LIVE:

streamlink %url% 477p --stdout | mpv - --stream-dump=myfile

**Comment by johnthecracker** [comment]
A word about benefit saving a raw stream. Fine for pre-recorded video, but not for live stream.

Some processing with ffmpeg returns better file.

streamlink.exe %url% best --stdout | ffmpeg.exe -i pipe:0 -c:v copy -c:a aac file.flv

**Comment by campones** [comment]
with old plugin 

```
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to open URL: https://www.dailymotion.com/sequence/full/x29atae (404 Client Error: Not Found for url: https://www.dailymotion.com/sequence/full/x29atae)
```

with new plugin

`[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x29atae
error: Unable to validate JSON: Key 'qualities' not found in {u'audience_url': u'https://am-01.dc3.dailymotion.com/vx29atae', u'title': u'i24NEWS Live', u'url': u'https://www.dailymotion.com/video/x29atae', u'view_id': u'1cepd4eak2sd4281fr2', u'error': {u'code': u'DM003', u'title': u'Live d\xe9connect\xe9', u'status_code': 403, u'raw_message': u'Suivre i24news-en pour ne pas rater ses prochains live streams.', u'refresh': 0, u'message': u'Suivre <a target="_top" href="http://www.dailymotion.com/i24news-en" class="highlight">i24news-en</a> pour ne pas rater ses prochains live streams.'}, u'owner': {u'username': u'i24news-en', u'verified': True, u'parent': u'x1al6kw', u'url': u'http://www.dailymotion.com/i24news-en', u'partner': True, u'id': u'x1g218p', u'screenname': u'i24NEWS (English)'}, u'access_id': u'x29atae', u'advertising': {u'ima': {u'url': None, u'enable': False, u'timeout': {u'video': 8000, u'vast': 5000}}, u'ad_url': u'https://dmxleo.dailymotion.com/cdn/manifest/video/x29atae.m3u8?auth=1527886311-2562-0qkzfd8p-9ea4089ad12f0cee617d28bf2b06cdafOU0nv3Ou_NhtCOJc5gylmCi_6GccOYGKCgjNc-EhWk4VlXDXRlthGcVr5cejhDdzs3wBLPXB_jPNk6sBSKJokjDcBwnPXti9CrZmcIoSxF3fimJYOhkg3KQiPn8o66Hqh73T53Sb_Hh-LgucqBC8DXLIU5sOtljWFp07L7AogfawCluYlxebfuLhkjNAvMSpXECFp-rkj87em90DUa72yI7U0sPeGJ88b2aoZIHTqHAFwpHrE1Aa_V333bhH6xVydOC7j6Puv-BYdU6_P_yAIYJbDvo_gw9mrt92NxAbNu96c050l9DKLw-66mNokY0x62nr0_Fv9Y6bfwjMyztty1iU6AncxWhBJyfflUT0aavRk563wGij3OJYraYjTEmgbnjQHMhHWkPAYt02ZKv-ItAcMoUke88N_JHrK0uRoWtF_81fRDqXCz3U6Eul1JW73w1hlrfBGEQ0kOb165rCP66WGeniVWoHgEYD6Lhwz7MXPe4u9HyMmGWFsolFfiAaeZMDCL9hJLoubO2AqbGKLEIwb_XjGyRkiqEyClFUwbS9RN6ukml11XVSj6_lpcWxge33TNerV_eC5exg75ErMcIHSRdr5viyA2OdkWB9SrPkZze_BIV9ZF5wT5q3rYe07VXv46iUUzwmdTTi07xF4ASr1ijfHn49_YuoEqPmRxXH6s6pK8JeJKHXnsIV-D-9grmjEeFRTK6RTqi7HT7EeNDPMIfmjDtueHc5emq91XF0HXaJiXDWSBZT2Qcpe2xTEiwYLrLYSkobnmmkQ9biMk7ESakZOjuxg5v53AewFbo2UP67Aitmz_uzsXae8egdZ2vmNEjkjYXYk9aJ4TZK7M9786NOdHprxXM4ckvAI0EnVm_SC0lUoLdYseyqm7ergktQQviXWD4ls1ySKV608C2S8L2DJor8Bqg4PQKBVTjKR3pDinTclfK3TKOBAQtQbJwfNBYSLcXPJdvS7V65yCJXOm25VFRYJ4rNRSRmxFXc9DU12v8M4xHp701RfXanluVaIlkA7vFmzmoVmOsLAJOcSm8mCQQGJGJcdeIlZQL27eg6uegYKg6eJz2E8Vawm1bHKX7rXjvcoHXDND60SDTrAGSed7P3ZKBIXQlok0nTXynNxfarTbGn4VmarFDmobZ2kl2WlkR8nATzcUjkX97_WNXhZJelmn-JzWz3RLwhIb0JCGyD-DWZDGQlT-jSNiPqnx3Szqwj7xrXMik9MRAIzys1_yiDgbluy9FxeaFfnw-ZuF46hDkwg77-tdqhaV1bPJIeE53pm5-fTRYAsXhFP9mow6Sl5XAmXkABRNw-YJHGVCAFZxtNx4R2UsM10Mco8jIKIpk1UN0ve1aYml_7_MmgOWkBTtzJQiAVaA22SI4C2EdvwtVCHwHDf7k4-oh44CAjmos0eaZZ3HaqdqOQ5MGAmkZ2dshVyQisPGmOJHUIKimJ6FM7m9AEg3EC7uOrT_16lXp6yjYNJdjms0A9QgU3HQxsSb0vKJSuT7NM-1Bf1tkSWvyvKw_Y6jnUYWPbkrH1WjaukZo10ClER_zA1iY4TfIAWzPMDDQ0wPLaimfc3HmylqeUp1clzmtqP6x9anlxntp2WLElXK1xo-1CxcPNLKSobhffDwGm8_hCUCAxXcaQNFPpvKkRVOu-oNC1IWoZUXykxx-HpRBRAeYZ6qAAZK_GL3RyXfxY-ofDxS4-1TzVt5L0NZ9dBW4VPaV6wINgZWpnD_R50Fpm0VnJ9efSdtNIGRTj9bXNfxCjcIgjzz0XUucM9egKN8IWfsbKoqvkwwST8iV2nImh_np3aTBMyAlU7FLX004hAamYDDs7eAPllYX8OnH_xQD0cyvt-EdC-swYO0uxMlo60_9RN6Wpo6L__LjGkS6GyArJXSc22WSdaboSakHOwK9hGlLA4HytrTMbPX9seMJbJ5w', u'ad_error_url': u'https://dmxleo.dailymotion.com/cdn/manifest/video/x29atae.m3u8?auth=1527886311-2688-8wkimzox-89f69e17a2570b3eeafdc69e27d42d78ZXkVCD0bE7fx0KNUZaqlL9WfxxEIqNoCl3ohBfFn1EpwzWyy8dGbywXG73oSHw7qXnMDMHop0q5hsX0zZGYQQeSJzqd2Aaao4ccyR9f1wrHl7QNG3McrxDOuZ05_3e6YgroP-n4qB3Ed88UcC5JUs1m1gahdz6D2aLdAHEY48w_fMdffQHdc7r2rdzYkdHVmnuTfHrXeZAlgG-g4J8Rc5WuTEgPtMDPB04EZpan5-G1_kXHXCzZG-Bw_BoZxLuD-wSbb9DQGlPRiKhoLItWxGhi4XYPwRijmF89Bu8c387FBTNLmm6B5hhLtK6CFqp4Aev1b8H3K9z8aWVncEC0LEm3_nJwhk_eJn9nvbiFc4FmqJfOST42e6EjvvxKUzJWS35L-_Uk0CRwgwDjWCqF0gMfE2wmfADxprRHCvLTylNgZ6BbDCLcupge-udjRPzFANWhFR24q6PLzN27mtLvUbotZBnSOx6cv2jYLzUBthfoLj_NdVESsHD0UDWPu8sTSGFBdBTKImAcF5eze86fpRj80zVzr7gb3tHgJDiSiVpIran6eY3IhEGAJ_5sNQOOVax7rsV5X2sxLJznu4ucqrkWEDvG2YyzsDtI_7zCCnbu11ZetSsWQKL08WXDE7SgpL99p6YFY5Akho9e9GJdzd-1MZ9UGFaMi5JkkRpYGkQW8crZBTF_2CalBtxQa-L6I6ZC307wH2VPir_-_MAmsZ9-5x-vEFPChYbkFC3ZJJ0JrP_p57hNmb3lmaI7cnoYgfWLH8jPDcUyTXs6tJAfaiDyAlU55sHWiQM4cjvDQJli9ToiUhOPozxsbyFSDoFa9W7owjS4SO8v-RucFF4aQEMqve2GmiPCQ5r8yNTwmcoWZMb94XjPBURfJMs2Ih7fBDGDjzWl7tWARyJ4WHB7jY301K-qCsPyDO8fWkMPZ7LQL5JyRXnUJHf285LudKGDce-t_lARJcM3DpDwKyFF0OOyd3rZgiFFRIYJJl3IimwZAQpUSmrCV3Mi_U0-kELF0nDlA8T0kScdh0YxeRCQbwME3js8ctZbc2KdWeWZuXID-dumhUhdn5kYXS0kI-H4DUg4y40l6MG6Kc6qfZqlAqruY3RM9l6yf0vvjyGQrwNZdgND-zVRygp26p1mnXpFkDTsJLB5mlpVcGLtEHGGe1jIgKDEDCv9smXx6n19W5w1zjmfQ42a9mDLyS1WzsUxA3CIM_YDyf2fZHl-Toulb2igD-ZLW3w-VbOeU9a9KoceoWKmiopq9_z1iPtZq-8lvtRIw60qChSYjgVYMcMwiQ45a_PK1fGh71o9GrEY_U24T8Q_zhjznETWJfkvoZbP229zclg-hctoM9vhiXShvf_PrOrXahf4UANZYK8GAj7Xy_GxhB0kw_c8pq8Srs5zXDz1WiLAb8op900Va9fSyaVp7u3iDIl0Td8GW1MxC2o-qxoUQjC5f-0I0CpQq6zNEbRW5v4yhpaL1nfz-kkMmauQMMuHmc3k9jk9PmomlDQIWOdek91lkFrmDGGpgnZAM6mZ1gnsuJibsk7MdmDLPnYmZG-6aJJBDNFzSZdlx9JiIuU0dIyeXHiHX6PUOsh79rxQXJSJe8Qf5am6uQtofgVdWXYKEcnB9Ht7sqI6IdpTj_50FG1_5cWIAHg_MGYoL2KdPpI9_RJEbgJVcjwHXqOs4ZLg341dQhQaFfSQj0B9l2g4LadQfnIfmCAEZ8bmPHgxF92b2qHk6_afdg_TqhQ7xKuGFWTQG9q9BKr22wgmCKyv_9qReYycTbipOJuPNEnkIytroaiIP6mEmWmmvD9jMgiwFCQd2XqD_ZKG_AXVmwOc-2NByQwRZBfB5Qs_YcIhJf7oal931UMJ7DbrlORG1VSV1X2hZRV5dlBkR3-BJGYKWBlSEHMFb01mu7rqn-W9-qiMsHXlk-CeY0LPDwetx3EF3Ctrv58y6xfpquLyE&error=[ERRORCODE]', u'fb_placement_id': u'1250440894970236_1303434513004207'}, u'poster_url': u'https://s2-ssl.dmcdn.net/hOONk.png', u'duration': 0, u'posters': {u'120': u'https://s2-ssl.dmcdn.net/hOONk/x120-png/itG.jpg', u'1080': u'https://s2-ssl.dmcdn.net/hOONk/x1080-png/MAC.jpg', u'60': u'https://s2-ssl.dmcdn.net/hOONk/x60-F-l.png', u'180': u'https://s2-ssl.dmcdn.net/hOONk/x180-png/eji.jpg', u'240': u'https://s2-ssl.dmcdn.net/hOONk/x240-png/JEF.jpg', u'720': u'https://s2-ssl.dmcdn.net/hOONk/x720-png/ZeU.jpg', u'360': u'https://s2-ssl.dmcdn.net/hOONk/x360-png/7wm.jpg', u'480': u'https://s2-ssl.dmcdn.net/hOONk/x480-png/Eeh.jpg'}, u'id': u'x29atae'}
`

**Comment by campones** [comment]
ok sorry I guess it's because the channel he provided is actually offline.  So yes it works (I also removed the streamlink installed with pip to install manually with the github release).

**Comment by beardypig** [comment]
@campones I just opened a PR (#1716) to give some better error output in this case :)

**Comment by campones** [comment]
yes that could be useful indeed :)

**Comment by johnthecracker** [comment]
> the channel he provided is actually offline

Sad.

We won't know the truth without Israeli news.

I will be missing Netanjahu a lot, for sure.

He was better than any other clown on the internet.

**Comment by johnthecracker** [comment]
This will play i24NEWS Live:

streamlink.exe http://play.tv/live-tv/908/i24-news-english/ best

C:\>streamlink.exe http://play.tv/live-tv/908/i24-news-english/ best
[cli][info] Found matching plugin playtv for URL http://play.tv/live-tv/908/i24-news-english/
[cli][info] Available streams: 300k (worst), 800k (best)
[cli][info] Opening stream: 800k (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe

It is puzzling that it was **I** who came first with this answer.

If playtv plugin stops working for i24NEWS Live like dailymotion plugin did, visit here:

http://stream-recorder.com/forum/i24news-live-t23954.html
