### ISSUE TITLE
Possible to download by batch?

### ISSUE THREAD

**Issue by Lumenlul** [streamlink/streamlink#1617]
Hi,

So I've gotten Streamlink to work with Schoolism in order to watch lessons locally, however, it's tedious to download part by part, so is there a way to have the parts queue up automatically/download by batch?

For instance, what I'm using now is: 

Streamlink.exe --schoolism-email [OMITTED] --schoolism-password [OMITTED] --schoolism-part 4 -v "https://www.schoolism.com/watchLesson.php?type=st&id=514" best -o "desktop\4.mp4"

Using this, I have to go part by part, is there a way I can enter multiple commands at the same time or download by batch?

Thanks.

**Comment by bastimeyer** [comment]
This can be easily done via a shell wrapper script or in the interactive shell. I already answered the question here:
https://github.com/streamlink/streamlink/issues/1431#issuecomment-357538507

**Comment by beardypig** [comment]
@Lumenlul don't download them too fast either, you need to wait ~5 minutes between downloads otherwise you'll be blocked temporarily.
