### ISSUE TITLE
aliez.tv not working

### ISSUE THREAD

**Issue by morturio** [streamlink/streamlink#1627]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
no aliez-streams can b found

### Reproduction steps / Explicit stream URLs to test

streamlink http://aliez.tv/live/68g7q8qkqw7bqswda9q8/
[cli][info] Found matching plugin aliez for URL http://aliez.tv/live/68g7q8qkqw7bqswda9q8/
error: No playable streams found on this URL: http://aliez.tv/live/68g7q8qkqw7bqswda9q8/

**Comment by gravyboat** [comment]
Can you add `-l debug` to your command? Then we can get some more error output.

**Comment by skulblakka** [comment]
> where do i have to place -l debug?

There are multiple possible locations. For example:

```
>streamlink -l debug http://aliez.tv/live/68g7q8qkqw7bqswda9q8/
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.2), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin aliez for URL http://aliez.tv/live/68g7q8qkqw7bqswda9q8/
error: No playable streams found on this URL: http://aliez.tv/live/68g7q8qkqw7bqswda9q8/
```

**Comment by morturio** [comment]
i tried it that way but i got no debug messages.
my version WAS 0.9 so i updated streamlink to 0.11 but now it doenst work at all ;D
i will fix this and then i will try the debug command again

fyi:
os: linux mint 18.3
kernel: 4.15.0-15-generic
Python 2.7.12
Python 3.5.2

thx 4 help so far
