### ISSUE TITLE
How to watch multiple Twitch streams in the same VLC player window?

### ISSUE THREAD

**Issue by socalfusions** [streamlink/streamlink#1631]
Is it possible to watch multiple twitch streams in the same VLC player window? I'd like to do this to avoid having many players open at the same time as having one would be more convenient.

**Comment by johnpolite** [comment]
You want pizza on top of bread..

**Comment by bastimeyer** [comment]
Your question is unrelated to Streamlink, and no, this is not possible. I doubt that there is even a player which provides this kind of feature. If you want to watch multiple streams at once, you have to launch multiple instances (of Streamlink and) your player. On Linux, you can use tiling window managers which will arrange all of player windows automatically. If you also disable window decorations, you can have the same experience you've described here.
