### ISSUE TITLE
[Plugin Request] Ividion live cams video service.

### ISSUE THREAD

**Issue by VadimK60** [streamlink/streamlink#1633]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I would like to ask you to add a new plug-in to the Streamlink.

Plugin for **Ivideon** -- video service with hundreds live cameras over the world:

https://www.ivideon.com/tv/map

Camera link examples:

on map view:
https://www.ivideon.com/tv/map/50.39495/30.606628/12/camera/100-4e64b1e32103c19f205bd630fddaefee/393216

full screen view:
https://open.ivideon.com/embed/v2/?server=100-4e64b1e32103c19f205bd630fddaefee&camera=393216&width=2304&height=1296&lang=ru&ap=&fs=&noibw=

standard view:
https://www.ivideon.com/tv/camera/100-4e64b1e32103c19f205bd630fddaefee/393216
---
As you can see, common parts of this links are server name (100-4e64b1e32103c19f205bd630fddaefee in selected example) and camera number (393216).

___
In Chrome (F12 - developers tools view -> Network (All)) you can see link like this [example]:

https://msk212.extcam.com/hls/playlist.m3u8?hlsId=d5833f13697f43c880f0d81d46d8841c_100000671632_393216

(.M3U8 link viewable with FFplay or VLC, but valid only a few minutes...)

Content of M3U8 [example]:

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:230
#EXT-X-ALLOW-CACHE:NO
#EXTINF:2.450,
segments/d5833f13697f43c880f0d81d46d8841c_100000671632_393216/segment_230.ts
#EXTINF:2.450,
segments/d5833f13697f43c880f0d81d46d8841c_100000671632_393216/segment_231.ts
#EXTINF:2.450,
segments/d5833f13697f43c880f0d81d46d8841c_100000671632_393216/segment_232.ts
#EXTINF:2.450,
segments/d5833f13697f43c880f0d81d46d8841c_100000671632_393216/segment_233.ts
#EXTINF:2.450,
segments/d5833f13697f43c880f0d81d46d8841c_100000671632_393216/segment_234.ts

Thank you for Streamlink!!!
Regards!

**Comment by back-to** [comment]
similar to https://github.com/streamlink/streamlink/pull/1525#issuecomment-372066475
