### ISSUE TITLE
Streamlink hangs on MacOS HS 10.13.3

### ISSUE THREAD

**Issue by aeon3** [streamlink/streamlink#1634]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

In MacOS HS 10.13.3, Streamlink hangs after I paste code and hit enter.

### Expected / Actual behavior

After pasting the correct code it should start downloading the stream or at least acknowledging it, but in reality nothing happens at all. 

 
### Reproduction steps / Explicit stream URLs to test

1. Paste the following in Terminal: streamlink --schoolism-email EMAIL --schoolism-password PASSWORD --schoolism-part 1 ”LINK" best -o "part1.mp4"

2. Press enter

### Logs

The use of -l debug does not make any difference.

### Comments, screenshots, etc.

The exact same syntax works flawlessly on Windows 10 under virtualbox.

**Comment by aeon3** [comment]
Hi!

Yes, no output.

1- That is a tricky question. I had issues when I first installed it so I went over a couple of times back and forth, several lines after and got it to work. This is the guide I used with all the commands: 
```
Step by step explanation:

Install brew:

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Install streamlink using brew:

brew install streamlink
Install python:

brew install python
Install wget:

brew install wget
Get pip installer:

wget -O ~/Downloads/get-pip.py  "https://bootstrap.pypa.io/get-pip.py"
Install pip:

sudo -H python ~/Downloads/get-pip.py
Delete pip installer:

rm ~/Downloads/get-pip.py
Install requests:

sudo -H pip install requests
Instal pycryptodome:

sudo -H pip install pycryptodome
Install singledispatch:

sudo -H pip install singledispatch
Install futures:

sudo -H pip install futures
Install pysocks:

sudo -H pip install PySocks
Install backports.ssl-match-hostname:

sudo -H pip install backports.ssl-match-hostname
permalinkembedunsavegive gold
```
https://www.reddit.com/r/LazyMan/comments/720mbm/could_not_find_streamlink_fix_mac/

2- python --version: = Python 2.7.14

3- Apparently yes. But again, when using that exact same line in Windows 10 under VM, it works flawlessly. I tested in MacOS with twitch and this is what it spit: 
```
streamlink twitch.tv/day9tv best -l debug
[cli][debug] OS:         macOS 10.13.3
[cli][debug] Python:     2.7.14
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/day9tv
[plugin.twitch][debug] Getting live HLS streams for day9tv
error: No playable streams found on this URL: twitch.tv/day9tv
```

4- streamlink --version = streamlink 0.11.0

**Comment by beardypig** [comment]
OK, thanks for the info... Silly question, but can you open the same link in a browser? 
Another to try would be to do 
```
streamlink -ldebug --can-handle-url-no-redirect "LINK"
```
and see what the output for that is.

**Comment by aeon3** [comment]
Sure sure I can open it in any browser no problem. It is an online class which I have to login with my credentials to watch the videos.

Here's that output:

streamlink -ldebug --can-handle-url-no-redirect "LINK"

[cli][debug] OS:         macOS 10.13.3
[cli][debug] Python:     2.7.14
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)

**Comment by beardypig** [comment]
Can you try
```
streamlink -ldebug --can-handle-url "LINK"
```
as well? If you could post the output from 
```
curl -I "LINK"
```
that might help too. 

It's hard to debug without a schoolism username/password or which URL exactly you are requesting.. :)

**Comment by aeon3** [comment]
mannnn it worked. I have zero clue why. Besides doing what I just did with you here, nothing else. 

For confirmation sake though here are those outputs:

curl -I "LINK" 
```
HTTP/1.1 302 Found
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: text/html; charset=UTF-8
Date: Wed, 02 May 2018 15:32:03 GMT
Location: 
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Transfer-Encoding: chunked
Connection: Keep-Alive
Set-Cookie: X-Mapping-fjhppofk=16FAAECECB8A1DF7732E7D538726C899; path=/
Set-Cookie: PHPSESSID=paffteso7mls5o20qo7psaf3d3; path=/
X-Powered-By: PHP/5.4.16
```

and 

streamlink -ldebug --can-handle-url "LINK"

```
[cli][debug] OS:         macOS 10.13.3
[cli][debug] Python:     2.7.14
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
```

**Comment by beardypig** [comment]
No problem. 
It could have been a temporary error for the redirect, that was being generated (the 302 Found message in the `curl` command).

Glad it resolved itself.
