### ISSUE TITLE
Is it possible to configure stream output in file&player ?

### ISSUE THREAD

**Issue by agentqwe** [streamlink/streamlink#164]

**Comment by gravyboat** [comment]
Could you clarify what you mean? Streamlink has a large number of command line options. If you mean output to a file and a player at the same time I don't believe so. To accomplish that you should simply run two instances of Streamlink.

**Comment by bastimeyer** [comment]
see #105

**Comment by gravyboat** [comment]
Good call, thanks @bastimeyer!

**Comment by agentqwe** [comment]
i want run 2 output(file&player) but throu 1 instance.  thx u )  sorry for my bad eng,pls
one more quest pls guys, how to config streamlinks to write stream segments in file(example 4sec each) more often?cos now im playing writing file of stream and data in file updates about in8-12 sec, but i want in4sec evry segments with no dalay, to minimize delay to broadcast

**Comment by gravyboat** [comment]
Take a look at the segment options: https://streamlink.github.io/cli.html#stream-transport-options
