### ISSUE TITLE
[Plugin Request] https://plexstorm.com/

### ISSUE THREAD

**Issue by RyokoAsakura** [streamlink/streamlink#1641]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [X] This is a plugin (improvement) request.
- [X] I have read the contribution guidelines.

### Description
Plexstorm.com is a service like Twitch but with no constraints on adult content.

### Reproduction steps / Explicit stream URLs to test
1. https://plexstorm.com/stream/nerdyjessie (which leads upon inspection to...)
2. https://wowzaprod152-i.akamaihd.net/hls/live/619153/0P0p1OEFUT2VmVXh5T1BOQUs1Smp5c4d/chunklist.m3u8
3. If the above example isn't online, their front page will have example streams that are online available to test.

### Comments, screenshots, etc.
Screenshot of Firefox dev console network tab with stream URL highlighted: 
![image](https://user-images.githubusercontent.com/29420880/39683737-24b85382-5185-11e8-82c0-7eda32437dd1.png)

If broken, image can also be found at https://i.imgur.com/beUTJAU.jpg

Thanks for all you guys do! Streamlink helps us users more than you probably realize!

**Comment by gravyboat** [comment]
We've had some discussion about this in the past and come to the consensus that we're not going to support any more NSFW streaming sites like this so I'm going to close this request.

**Comment by ibigfire** [comment]
Simply because they are NSFW?  Obviously that's your decision to make, but it does seem fairly prudish.

**Comment by gravyboat** [comment]
@ibigfire Please review https://github.com/streamlink/streamlink/pull/1838#issuecomment-459184294 for our reasoning behind not allowing NSFW plugins. It has nothing to do with being prudish.
