### ISSUE TITLE
Streamlink doesn't work for any site

### ISSUE THREAD

**Issue by GrayFace** [streamlink/streamlink#1645]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Streamlink fails without an error message after discovering available streams. This happens for every site I've tried.

### Expected / Actual behavior

After "Available streams" message it just silently exits. On my main computer the same command line shows "Opening stream" message and download happens.

### Reproduction steps / Explicit stream URLs to test

1. This occurs only on a specific PC for me.
2. "c:\Program Files (x86)\Streamlink\bin\streamlink.exe" https://www.youtube.com/watch?v=YzRlga2-Hho -o test.mp4 -l debug >o

### Logs

```
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YzRlga2-Hho
[plugin.youtube][debug] get_video_info - 1: Found data
Available streams: audio_webm, audio_mp4, 144p (worst), 180p, 360p, 720p (best)
```

### Comments, screenshots, etc.

Github releases servers are pretty much down, so I can't check with the new Streamlink version.

**Comment by d0tfile** [comment]
You should specify quality: `Available streams: audio_webm, audio_mp4, 144p (worst), 180p, 360p, 720p (best)`
You can use `best` and `worst` (streamlink detects best and worst quality) or named `720p`, `360p`, etc.

**Comment by GrayFace** [comment]
Thank you, I probably added quality to config file and forgot it.
