### ISSUE TITLE
ANKA TV 

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#1648]
### Checklist
- [ x] This is a plugin (improvement) request.

### Description

Over the Website http://anka.tv/ can we see TV Channels in good Quality
Can you please check if you can make a plugin for streamlink 

Thanks

**Comment by bastimeyer** [comment]
That doesn't look like a legal site for watching these channels. It looks similar to other ones which have already been declined here.

You are also once again opening an issue with a plugin request with basically zero details.

**Comment by dreamboxco** [comment]
I had read only on the edge that you can look over it iptv. if it is not legal, the request can be closed.

Thanks for the hint
