### ISSUE TITLE
how to config streamlinks to write stream segments in file more often ?

### ISSUE THREAD

**Issue by agentqwe** [streamlink/streamlink#165]
now im playing writing file of stream and data in file updates about in8-12 sec, but i want in4sec every segments with no delay(segments from twitch is 4sec, shows ff addon for twitch), to minimize delay to broadcast. maybe writing delay is coz i allowed disk cache in my win10?

**Comment by gravyboat** [comment]
Was your question not answered in the other issue that you opened on this topic where I linked the segment details?

**Comment by agentqwe** [comment]
In stream transport options dont see anything about writing in file. I tested segment-threads from 1 to 10 and speed didnt change no one times: always like in one thread(about 4mbps-download, my inet connect is 6mbps) I think twitch actually lets download one segment in one thread. Problem is that all looks like windows write in file 2-3segments,  but i want to each 1segment when it will be download, it ll let me watch stream with minimum delay about (4downlsegment+4bufferbroadcaster=8sec) to broadcaster :)
need to add that https://github.com/streamlink/streamlink/issues/105 (I didnt install yet) solves problem of delay to broadcast, but its interesting what is reason delay of writing in file: streamlink or system(win10)
