### ISSUE TITLE
API Key and Quota

### ISSUE THREAD

**Issue by mtcjayne** [streamlink/streamlink#1652]
I have an application of Streamlink that checks for live YouTube streams every 5 seconds so that if a stream is live it will be downloaded, and so that if a download is interrupted it will pick up again more or less where it left off. It was using way too much of your key's quota (or any key's quota) to be reasonable and have fixed that. First of all, I want to apologize. I'm newly exploring the API myself so I didn't understand how much of a finite resource I was using. I've moved to my own key to prevent that from happening again.

It seems the only API call Streamlink makes is search, and it uses the get_video_info non-API URL to get additional info. Is this correct?

**Comment by back-to** [comment]
It is only used once to get the **livestream video id** from an account

https://github.com/streamlink/streamlink/blob/b50f86e454158f6d6d7cd6103d81ce3fd5318469/src/streamlink/plugins/youtube.py#L215-L224

---

closing

**Comment by beardypig** [comment]
I guess it depends on which methods were used :)
