### ISSUE TITLE
Need a option for DNS through proxy

### ISSUE THREAD

**Issue by sayakadead** [streamlink/streamlink#1654]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Steamlink can't resolve hostnames through the proxy server. If you receive a incorrect ip of the host via DNS spoofing, the option --http-proxy and --https-proxy may not work correctly.

### Expected / Actual behavior
Expected: Steamkink connect to youtube server through proxy and work fine.
Actual: Read timed out.

### Reproduction steps / Explicit stream URLs to test
1. Run a socks5 proxy server on port 1080
2. streamlink --hls-live-restart --http-proxy "socks5://127.0.0.1:1080" --https-proxy "socks5://127.0.0.1:1080" https://www.youtube.com/watch?v=fO8x9MZ8m9g

### Logs
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=fO8x9MZ8m9g
error: Unable to open URL: https://youtube.com/get_video_info (SOCKSHTTPSConnectionPool(host='youtube.com', port=443): Read timed out. (read timeout=20.0))

### Comments, screenshots, etc.
This is the log of my socks5 proxy when I run the step 2:
[2018-05-15 21:26:52] connect to 8.7.198.45:443

And this is the log when I visit https://youtube.com on firefox(Use the same socks5 proxy and it works fine)
[2018-05-15 21:28:51] connect to youtube.com:443

And this is the ping log to youtube.com on my pc
Pinging youtube.com [8.7.198.45] with 32 bytes of data:
Request timed out.
Request timed out.

Stramlink resolve the hostname 'youtube.com' direct and receive the incorrect ip '8.7.198.45' via DNS spoofing. Firefox works fine because it send the DNS request through the proxy.

**Comment by beardypig** [comment]
Thanks for the detailed report @sayakadead. I can confirm this issue as well. It only appears to affect SOCKS proxies, which probably means it's an issue `PySocks` or the way that `requests` invokes `PySocks` when creating a connecting using a SOCKS proxy. 

I will investigate :)

**Comment by beardypig** [comment]
Spoke too soon :)

If you use `socks5h://` then it will use the SOCKS proxy to look up the host name, eg.
```
--http-proxy "socks5h://127.0.0.1:1080" --https-proxy "socks5h://127.0.0.1:1080"
```

**Comment by sayakadead** [comment]
@beardypig Thanks! I have tried socks5h and it works. I think it's better to add a remark about socks5h at https://streamlink.github.io/cli.html#proxy-support

**Comment by beardypig** [comment]
Yep, totally :)
