### ISSUE TITLE
youtube stream download starts with the last 4 hours

### ISSUE THREAD

**Issue by artofsound** [streamlink/streamlink#1657]
### Description

Stream starts with segment 53560 instead of 0. The stream has already ended and the length is 74hours.
`--hls-live-edge` and `--hls-live-restart` options don't work

```
[Streamlink for Windows v0.12.1 - Git ce6de2c]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=FqGAASKonlo
[plugin.youtube][debug] get_video_info - 1: Found data
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 53560; Last Sequence: 56439
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 53560; End Sequence: 56439
[stream.hls][debug] Adding segment 53560 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 53561 to queue
[stream.hls][debug] Adding segment 53562 to queue
[stream.hls][debug] Adding segment 53563 to queue
[stream.hls][debug] Adding segment 53564 to queue
[stream.hls][debug] Adding segment 53565 to queue
[stream.hls][debug] Adding segment 53566 to queue
[stream.hls][debug] Adding segment 53567 to queue
```

With the build-in browser developer tools, i can manage to get single segments before the 4 hour limit.

![networkanalysis](https://user-images.githubusercontent.com/39335345/40114868-c26a2ee4-590e-11e8-9368-58105f204ba2.jpg)

>`
https://r5---sn-h0jeen7k.googlevideo.com/videoplayback?id=FqGAASKonlo.1&itag=137&source=yt_live_broadcast&requiressl=yes&playlist_type=DVR&gcr=de&ei=WBj8Wr32FIj91wKL1pyABQ&force_finished=1&ratebypass=yes&cmbypass=yes&mime=video%2Fmp4&live=1&gir=yes&noclen=1&dur=5.000&cpn=pc3EhHaKRiCWagkV&mpd_version=5&ip=2003:6:638c:8b35:840e:e241:d3cd:f760&ipbits=0&expire=1526492344&sparams=cmbypass,dur,ei,expire,force_finished,gcr,gir,id,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pl,playlist_type,ratebypass,requiressl,source&signature=4D4FCE6963E6C337AB3C2603653FD322CB5E1281.529B269FECFFABA6D1ECD8EE2BC2BA6F8FE780E5&key=cms1&mm=32&mn=sn-h0jeen7k&ms=lv&mt=1526470378&mv=u&pl=52&alr=yes&c=WEB&cver=2.20180510&sq=53563&rn=6&rbuf=13403`

So you can change `&sq=53563` to a lower value like `&sq=40000` and get an older segment.

`&itag=137` is for video and `&itag=140` the ones for audio.

### stream URLs to test

1. https://www.youtube.com/watch?v=FqGAASKonlo
2. https://www.youtube.com/watch?v=NxOzJPBhlVY

Maybe related to this #1637 because it is downloading a mpg.

> `https://manifest.googlevideo.com/api/manifest/dash/expire/1526492344/id/FqGAASKonlo.1/signature/AB991FAB6D4F6964995C290F822746AA447E507E.E33CCDDF0601E02BCC2C6830EC70FA69E4695603/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/source/yt_live_broadcast/sparams/as%2Cei%2Cforce_finished%2Cgcr%2Cid%2Cip%2Cipbits%2Citag%2Cplaylist_type%2Crequiressl%2Csource%2Cexpire/playlist_type/DVR/ipbits/0/requiressl/yes/ip/2003%3A6%3A638c%3A8b35%3A840e%3Ae241%3Ad3cd%3Af760/key/yt6/itag/0/gcr/de/ei/WBj8Wr32FIj91wKL1pyABQ/force_finished/1?cpn=pc3EhHaKRiCWagkV&mpd_version=5&pacing=0`

**Comment by beardypig** [comment]
The way the YouTube plugin works is that it gets the HLS playlist (m3u8 file) from YouTube, and that tells it where to start - in this case the earliest segment they give in the playlist is 53560.

It is working as expected. We probably could make it work, but it wouldn't be a simple fix :)

FWIW the DASH stuff (#1637) is unrelated :)

**Comment by artofsound** [comment]
Yea, I thought there is a way around the m3u8 playlist file, like getting the full playlist with all segments.

> FWIW the DASH stuff (#1637) is unrelated :)

I thought the Youtube 1080p browser stream is delivered through DASH. Audio and video are also seperated.

The first lines of the mpg file.

```
<MPD xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd" minBufferTime="PT1.500S" profiles="urn:mpeg:dash:profile:isoff-main:2011" type="static" availabilityStartTime="2018-05-12T11:28:13" timeShiftBufferDepth="PT14400.000S" mediaPresentationDuration="PT14400.000S" yt:earliestMediaSequence="53560" yt:mpdRequestTime="2018-05-16T13:38:09.556" yt:mpdResponseTime="2018-05-16T13:38:09.566">
<Period start="PT186423.931S" yt:segmentIngestTime="2018-05-13T10:04:00.010">
<SegmentTemplate presentationTimeOffset="186424111" startNumber="53560" timescale="1000" media="sq/$Number$">
<SegmentTimeline>
```
`yt:earliestMediaSequence="53560"`
`startNumber="53560"`
`media="sq/$Number$"`

**Comment by back-to** [comment]
because this is the **normal behavior**, I will close this issue.

**Comment by artofsound** [comment]
You don't want to improve streamlink? I manage to get the mpd list and downloaded all segments with an easy approach. Even the ones that aren't in the HLS source.

**Comment by mjarraya** [comment]
@artofsound mind sharing your approach?

**Comment by gravyboat** [comment]
Issue is super old. Locking.
