### ISSUE TITLE
LCI not covered by TF1 home page anymore

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#1659]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I pointed out since a while that tf1 plugin doesn't cover anymore LCI from tf1.fr home website. It did before. 

### Expected / Actual behavior

Here I point out result with older tf1 plugin : 

```
streamlink "https://www.tf1.fr/lci/direct"
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/lci/direct
error: Unable to open URL: http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@30158
5/manifest.f4m?hdnea=st=1526479986~exp=1526481786~acl=/*~hmac=207f41547435bb3422
e9f51af166cae855bdbb387ac875524827deb528999d9e (403 Client Error: Forbidden for
url: http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=s
t=1526479986~exp=1526481786~acl=/*~hmac=207f41547435bb3422e9f51af166cae855bdbb38
7ac875524827deb528999d9e&g=DSCLJVQYJHGR&hdcore=3.1.0)
```

The latest tf1 plugin gives such result : 

```
streamlink "https://www.tf1.fr/lci/direct"
[cli][info] Found matching plugin resolve for URL https://www.tf1.fr/lci/direct
[plugin.resolve][info] Found iframes:
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\streamlink-script.py", line 11, in <mo
dule>
    load_entry_point('streamlink==0.12.1+8.ge2a5546', 'console_scripts', 'stream
link')()
  File "c:\program files\python27\lib\site-packages\streamlink_cli\main.py", lin
e 1113, in main
    handle_url()
  File "c:\program files\python27\lib\site-packages\streamlink_cli\main.py", lin
e 505, in handle_url
    streams = fetch_streams(plugin)
  File "c:\program files\python27\lib\site-packages\streamlink_cli\main.py", lin
e 402, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "c:\program files\python27\lib\site-packages\streamlink\plugin\plugin.py"
, line 385, in get_streams
    return self.streams(*args, **kwargs)
  File "c:\program files\python27\lib\site-packages\streamlink\plugin\plugin.py"
, line 288, in streams
    ostreams = self._get_streams()
  File "c:\program files\python27\lib\site-packages\streamlink\plugins\resolve.p
y", line 480, in _get_streams
IndexError: list index out of range
```

### Reproduction steps / Explicit stream URLs to test

1. ` streamlink "https://www.tf1.fr/lci/direct"`

### Logs

```
streamlink -l debug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0.12.1+8.ge2a5546
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
```

Both tests were made with the latest streamlink build, I just replaced newer tf1 plugin with older. 
Thanks for up.

**Comment by back-to** [comment]
The url is hard coded in

https://github.com/streamlink/streamlink/blob/b340b1e3dbb5b8dca59fcd01c224fc31f80f7402/src/streamlink/plugins/tf1.py#L12

it can't find the `lci` part

Ref https://github.com/streamlink/streamlink/pull/1457

---

and you should use the path `%APPDATA%\streamlink\plugins` for any custom plugins.

https://streamlink.github.io/cli.html#sideloading-plugins

**Comment by karlo2105** [comment]
@back-to 
Thanks for sideloading plugins hint. 
I used your tf1 plugin pre 28.03 which worked for testing so if it can help you : 

https://github.com/livecli/livecli/commit/2a8f531f898be9d8de3d76494de6a033e60c9888#diff-0ca5d3d0553ece57a01fc5b72111cf43

**Comment by beardypig** [comment]
@karlo2105 looks like the second error is from the `resolve` plugin from `livecli`. I have created a PR to fix the issue in streamlink.
