### ISSUE TITLE
Start playing stream immediately

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#166]
It would be cool if stream start playing before waiting to download a whole segment, i mean if you directly play a stream using a player in about 2 seconds loads but with livestreamer/streamlink we have to wait until the first segment (i guess) is downloaded and this can take a time in some connections.
In summary it will be cool to start playing when some data is available instead of waiting for whole download, the same happens with downloads, the state report only refresh when a whole segment is downloaded (maybe like #165 reported)

**Comment by agentqwe** [comment]
Exactly! 
for examp twitch broadcasting mpeg-ts video, so what is problem play segment immidiatly?(im not programmer?so maybe my words sound stupid...))

**Comment by RosadinTV** [comment]
@agentqwe I think the problem is the program wait for download the whole segment before start playing or refreshing download.
For example if a stream using HLS have 10 segments of 15 mb each, instead of playing the segment when 1 mb is downloaded Streamlink wait until the 15 mb is downloaded.
The same goes for the cache, i mean .. the cache is only added to the player when the whole next segment is downloaded.

**Comment by agentqwe** [comment]
for example when i use ff for twitch and this - https://addons.mozilla.org/ru/firefox/addon/twitch_5/ in statistics of addon i saw segments of 2 and 4sec with bitrait 3-4mbps(forexpl) so its about 1-1.5mb every segment, i set in twitch addon playerbiffer 1sec, it was like in player sometimes buffer left less than 1sec )), its not bad coz it let see stream with almost no delay to broadcaster, but if next downloading segment will play immidiatly - buffer will never clear even buffer length will be 1 or 0 sec  :) am i right?

**Comment by RosadinTV** [comment]
@agentqwe I dont know if i understand you but you if you have a good internet connection you can watch a stream almost without delay because the buffer can maintain in a few seconds from live, with livestreamer you can use --hls-live-edge 1 to stay as close as possible to live.
The difference is that if the segment is for example 6 seconds each you cant stay 1 second close to buffer with streamlink like with playing directly with a player.
In my case i dont care about stay close to live, in fact the best thing of the Project for me is the ability to store good amount of cache without issues, only that i will preffer to dont wait to whole segment download to start viewing a stream and the thing goes worst when you use --hls-live-edge with a big number because the stream only start when download the x specified ammount of segments.

**Comment by agentqwe** [comment]
yes, i use --hls-live-edge 1, yep for up to 5mbps streams my inet work good
we just say about different segments, u want to play immediately(undownloaded full) big segments, and for big segments it is need,  but i told about small 2-4sec segments and wanted play it(undownloaded full:) immediately too :) but it sounds little crazy and the result willnot be so big as programmers will spend much time for this

**Comment by RosadinTV** [comment]
@agentqwe Exactly, there are many possible bugs around this with a hipotetic modification, also think about some other things but i think they could never be done, for example if we use  --hls-live-edge 5 the program should prioritize the segment download by order (i mean download the first segment with full speed and limit the speed of the the queued segments) because otherwise is likely that the queued segments will be downloaded earlier and then we have to delay the playback until the first ones are done .. and this can go worst if we had multiple threaded download.
For example we have a HLS with 10 segments and hls-live-edge with 5:
1 > (Actual)Downloading at 40kbps - Should be > 10kbps
2 > (Actual)Downloading at 60kbps - Should be > 10kbps
3 >(Actual)Downloading at 80kbps - Should be > 10kbps
4 >(Actual)Downloading at 60kbp - Should be > 90kbps
5 >(Actual)Downloading at 100kbps - Should be > 220kbps

**Comment by RosadinTV** [comment]
I will close the issue until some progress is made.

**Comment by beardypig** [comment]
This is actually extremely simple to fix for unencrypted HLS streams :) I'll open a PR once I fix it for encrypted streams too ;)

**Comment by gravyboat** [comment]
Closing this out since #260 is merged.

**Comment by RosadinTV** [comment]
@beardypig Really appreciated, thanks ❤️
