### ISSUE TITLE
[plugin issue] plugin.vidio.com / can't handle stream URLs anymore

### ISSUE THREAD

**Issue by akiwatti** [streamlink/streamlink#1669]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
plugin handling of https://www.vidio.com/live  URls not working anymore due to changes at provided stream structure

### Expected / Actual behavior
streamlink -l debug www.vidio.com/live/665-rcti-tv-stream
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin vidio for URL www.vidio.com/live/665-rcti-tv-stream
[plugin.vidio][debug] HLS URL: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/master.m3u8
error: Unable to open URL: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/master.m3u8 (403 Client Error: Forbidden for url: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/master.m3u8)

**Comment by beardypig** [comment]
Looks like there are some extra steps required to get the actual stream url. Seems pretty straightforward though :)

**Comment by beardypig** [comment]
@akiwatti I have submitted a PR to fix this, hopefully it will be merged soon and available in the nightly version.

**Comment by akiwatti** [comment]
@beardypig ..can confirm for Win10/VLC is working. Many thanks,
But would appreciate if also for enigma2 openatv..but get this...

root@ax51:~# streamlinksrv manualstart
[streamlinksrv][info] Sun May 20 07:45:10 2018 Server started - Host: ax51, Port: 8088
[streamlinksrv][info] Python:     2.7.13
[streamlinksrv][info] Streamlink: 0.12.1 / 07.05.2018
[streamlinksrv][info] Requests(2.18.4), Websocket(0.44.0)
[streamlinksrv][info] ffmpeg is usable.
127.0.0.1 - - [20/May/2018 07:45:14] "GET /https://www.vidio.com/live/204-sctv-tv-stream HTTP/1.1" 200 -
127.0.0.1 - - [20/May/2018 07:45:14] URL: https://www.vidio.com/live/204-sctv-tv-stream Quality: best
[streamlinksrv][error] Plugin error: Unable to validate response text: Unable to validate key 'token': Type of u'TZzVyVuQ29mE73sNlQk0BQmd0hvYVz8QDc3QcnmGbG2TezIRe7jskHx9m+LekhvAwwqOCSir/ZDuu40A8eS92w==' should be 'str' but is 'unicode'

**Comment by akiwatti** [comment]
many thanks to  @beardypig regarding this patch #1672
The stream URL is picked out, but it's then seems unmanageable by VLC, isn't it?

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.12.1
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/665-rcti-tv-stream
[plugin.vidio][debug] Getting stream tokens
[plugin.vidio][debug] HLS URL: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/master.m3u8
[plugin.vidio][debug] Tokens: hdnts=st=1527835389~exp=1527835439~acl=/i/*~hmac=90a9784e858970c3cf5e53af0c15c157aebac23df0ffa9fa048bba4ddc3d03a4
[cli][info] Available streams: 144p_alt (worst), 144p, 270p_alt, 270p, 360p_alt, 360p (best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
----
> VLC error message:
Your input can't be opened:
VLC is unable to open the MRL 'https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/index_360_av-b.m3u8?sd=10&rebase=on&hdntl=exp=1527921789~acl=%2fi%2f*~data=hdntl~hmac=0d7d3abaa953baa33c9b4f63be9fb10af0f9c446a6a393e6f19f95dfabbf2352'. Check the log for details.

######################
even stream URL handed over to VLC seems now different?  any hints? or even how to use it at KODI by "iptv simple" with complement plugin "Twilight0/script.module.streamlink.base" as before?
 
Thanks in advance.

**Comment by akiwatti** [comment]
@beardypig 
streamlinrc ... win10:
# VLC
#player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
player="C:\Program Files\VideoLAN\VLC\vlc.exe"
# Using --file-caching is recommended, but is only supported in VLC 2.0+
#player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=5000
#player="C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000

# MPC-HC, must be at least version 1.7 to be used
#player="C:\Program Files (x86)\MPC-HC\mpc-hc.exe"
#player="C:\Program Files\MPC-HC\mpc-hc64.exe"


# Use this if you want to transport the stream to the player via a named pipe.
#player-fifo

# Use this if you want to transport the stream to the player via HTTP.
#player-http

# Use this if you want streamlink to only pass a URL to your player and
# let it handle the transport of the stream itself.
player-passthrough=http,hls,rtmp

# By default streamlink will close the player when stream is over.
# Use this option to let the player stay or close itself instead.
#player-no-close

# Use this option if you want streamlink to keep trying to access
# the stream even if it goes offline or disconnects. Your player must
# support HTTP and its playlist should be set to repeat mode.
#player-continuous-http

# Show console output from the video player
#verbose-player

# RTMP streams are downloaded using rtmpdump. Full path or relative path
# to the rtmpdump exe should be specified here.
#rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

# FFMPEG is used to mux separate video and audio streams in to a single
# stream so that they can be played. The full or relative path to ffmpeg
# or avconv should be specified here.
#ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe

# Log level, default is info
#loglevel=debug

# Number of threads to use when streaming HLS streams
#hls-segment-threads=1

# Number of threads to use when streaming HDS streams
#hds-segment-threads=1

**Comment by akiwatti** [comment]
@beardypig
...and just a user at Kodi/Pi3 - libreelec, therefore "streamlink plugin" settings not obvious for me to find/to adapt...

**Comment by beardypig** [comment]
@akiwatti You have `player-passthrough=http,hls,rtmp`, this will not work with vidio, you need to remove this setting to get it to work.
