### ISSUE TITLE
Bintray deploy won't work because of an invalid includePattern

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1679]
### Checklist

- [x] This is a bug report.

### Description

Ref https://github.com/streamlink/streamlink/pull/1413#issuecomment-389561062
https://bintray.com/streamlink/streamlink-nightly/streamlink

the `includePattern` won't work with the new version name,

https://github.com/streamlink/streamlink/blob/416c8347b394c9b1cbaff150450d51a75509dd24/script/bintrayconfig.sh#L32-L36

`/home/travis/build/streamlink/streamlink/dist/nsis/streamlink-0.12.1+8.ge2a5546.exe`

it won't match because of the `+`

> includePattern: Pattern in the form of Ruby regular expression

https://docs.travis-ci.com/user/deployment/bintray

**Comment by beardypig** [comment]
I think bbe6674 will fix it.

**Comment by back-to** [comment]
yes the fix works, maybe merge it into master

https://travis-ci.org/streamrepo/streamlink/jobs/382262907#L2872
https://bintray.com/back-to/Test/streamlink

**Comment by beardypig** [comment]
Thanks for testing @back-to, I didn't have time to test it yet :)

**Comment by gravyboat** [comment]
Closing since #1681 is merged.
