### ISSUE TITLE
Schoolism Video Feedbacks Plugins Compatibility?

### ISSUE THREAD

**Issue by Lumenlul** [streamlink/streamlink#1683]
Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

With the Schoolism plugin, you can download lessons with Streamlink.exe --schoolism-email XXXX --schoolism-password XXXX --schoolism-part 1 -v "https://www.schoolism.com/watchLesson.php?type=st&id=506" best -o "LOCATION"

Is there a way to download the video feedbacks from urls such as https://www.schoolism.com/viewAssignment.php?type=st&courseID=44&id=506&notSubmitted=true as well? If there isn't, I'd greatly appreciate a modification to the plugin to allow for one to download the video feedbacks.

**Comment by beardypig** [comment]
It's not supported by the plugin, it could be added - but I don't have access to schoolism, when I wrote it the first time I borrowed someones credentials. 

You can check using your browsers dev tools to find the m3u8 URL and use that along with the auth cookies (not sure of the their names though) with streamlink.

**Comment by back-to** [comment]
**just for your interest, nobody here has an account**

if someone wants this feature,
the person must share it with someone who wants to add this feature

---

**at some point** it's not worth to have an **unfixable issue** open
like some of the other Schoolism issues https://github.com/streamlink/streamlink/issues/1046#issuecomment-386712317 _(over one year)_
and it will be closed, so it can disappear in the shadows

**Comment by back-to** [comment]
No response received.
