### ISSUE TITLE
Zoom Player support

### ISSUE THREAD

**Issue by Bilge** [streamlink/streamlink#1697]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Any chance of supporting [Zoom Player](https://www.inmatrix.com/)?

**Comment by gravyboat** [comment]
Did you already try the player options from the docs? https://streamlink.github.io/cli.html#player-options Most players should be supported unless they don't accept the output, and if that's the case we'll need debug logging from you to confirm whether this is a Streamlink problem or a player problem.

**Comment by Bilge** [comment]
Yes, I launched the program with `--player`, if that's what you mean. The player started but nothing played.

**Comment by beardypig** [comment]
If you could try with the --player-fifo option and see if that works, if not try the --player-http option. It looks like Zoom Player doesn’t support reading from stdin, which is why it doesn’t work by default.

**Comment by Bilge** [comment]
`--player-fifo` does not work, and frustratingly, hangs the console.

`--player-http` seems to cause the video window to resize, as if it is about to play a video, and even shows a message in the playback bar "Live Stream - Connecting", but then closes itself before any playback begins and yields back to the console with the following messages:

```
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: c:\Program Files (x86)\Zoom Player\zplayer.exe
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

It certainly seems Zoom Player 9.4 is not supported.

**Comment by beardypig** [comment]
Could you run it again with `--player-http` and `-l debug`, and show us the output.
You might also have some success with `--player-passthrough hls`, however it won’t work for every stream.

**Comment by back-to** [comment]
@Bilge 
**it works** with `--player-http` on win7 and 10,
you will have to select `Install Codec pack` when you install this player.

```
streamlink -l debug --player "C:\Program Files (x86)\Zoom Player\zplayer.exe" https://twitch.tv/twitch best --player-http
```

**Comment by back-to** [comment]
closing, as there is a solution.
