### ISSUE TITLE
does not install PIP2/Python2 on Temux

### ISSUE THREAD

**Issue by markosjal** [streamlink/streamlink#1698]
Termux is a stand alone Linux terminal that runs on top of android (as Iunderstand it) . It apparently does not use the Android OS. It is its own OS.

I am trying to install Streamlink on Termux 

I execute  (pip2 refers to pip for Python 2, as Python 2 and 3 are available)
pip2 install streamlink 

installation  fails

WIll post the installer log file as soon as I can but it will be a little work to get it here from there

I sure hope there is a fix for this!

**Comment by gravyboat** [comment]
Did you try to install it into a virtualenv? I'm not super familiar with Termux but that might be worth a shot, logs would also be nice to see when you get them. I'm not sure it's something we'll be interested in supporting if things are really messed up, but I'd still like to see what the output looks like. It's worth noting if you're specifically trying to watch Twitch streams Pocket Plays is a great native Android option.

**Comment by markosjal** [comment]
I want to see if I can resolve YouTube links to a m3u file . That is my
objective. I want android to refresh  those links when they expire.


Will get the logs posted ii believe the error has to do with cpu
architecture

On May 26, 2018 5:43 PM, "Forrest" <notifications@github.com> wrote:

Did you try to install it into a virtualenv? I'm not super familiar with
Termux but that might be worth a shot, logs would also be nice to see when
you get them. I'm not sure it's something we'll be interested in supporting
if things are really messed up, but I'd still like to see what the output
looks like. It's worth noting if you're specifically trying to watch Twitch
streams Pocket Plays is a great native Android option.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/streamlink/streamlink/issues/1698#issuecomment-392292590>,
or mute the thread

**Comment by beardypig** [comment]
It’s trying to compile the cryptography libraries, you need a compiler. In theory `apt install clang` should should be sufficient, but you might have to install `gcc` too...

**Comment by Billy2011** [comment]
@markosjal 
There is a solution for the cryptography package [here](https://github.com/termux/termux-packages/issues/2430).

**Comment by mfr84** [comment]
It works !!!

Now the only problem is this error when I try to launch a stream:

_error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with -- player._

How to solve this issue ?

**Comment by back-to** [comment]
as it's solved https://github.com/termux/termux-packages/issues/2456

closing

**Comment by younpharma** [comment]
Change pip2 to pip3
