### ISSUE TITLE
Option to keep a stream running if player fails to start.

### ISSUE THREAD

**Issue by Daniel41550** [streamlink/streamlink#1699]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
-  [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Is it possible to keep a non-passthrough stream running if it can't start the player? I have a .bat file that it runs, but it always immediately closes the stream since the bat file closes itself after it is done running.

Here is the output, if it matters:
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/0
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Creating pipe streamlinkpipe-9060
[cli][info] Starting player: "C:\Path\removequotestoclipboard.bat"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

and for http:
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/0
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Path\removequotestoclipboard.bat"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by bastimeyer** [comment]
> keep a non-passthrough stream running

Depending on your preferred player input method, you can either use

- [`--stdout`](https://streamlink.github.io/cli.html#cmdoption-stdout)
  and pipe Streamlink's stdout data into the player process's stdin channel on your own, or use
- [`--player-external-http`](https://streamlink.github.io/cli.html#cmdoption-player-external-http)
  and let Streamlink launch a local http server and let the player connect to it at a later time.

By using `--fifo` (according to your first log output), the player will always be launched.

> but it always immediately closes the stream since the bat file closes itself after it is done running

https://stackoverflow.com/questions/13257571/call-command-vs-start-with-wait-option

**Comment by beardypig** [comment]
There is a `--player-no-close` option too, might work :)

**Comment by Daniel41550** [comment]
The external option is what I needed, thanks.
