### ISSUE TITLE
[REQ] Plugin for Stream.me

### ISSUE THREAD

**Issue by Brainzyy** [streamlink/streamlink#17]
This site is getting used more and more.
They have an API available: https://developers.stream.me/
On that page you can find info regarding Auth, OAuth, Broadcast and Live Stream.
It should contain any info needed to forge a plugin.

**Comment by Brainzyy** [comment]
I just tried out their api.
With `urllib.request.urlopen("https://www.stream.me/api-live/v1/streams").read()` you can get a JSON object with all currently available streams in it. They provide an RTMP and a M3U8 (HLS) stream link.
If someone more skilled in RegEx and Python could check this out, that would be awesome.
I tested some streams and using hlsvariant:// and the links that are in the JSON object works perfectly.
It should be possible to get the correct hls stream through the link the user provides with their command.

**Comment by sbstp** [comment]
I took a look, and I think there's an easier way. The urls are formatted like so, `https://stream.me/<username>`. You can use the API to access the channel directly, like so `https://www.stream.me/api-user/v1/<username>/channel`, which is much easier than downloading the entire list of live users and grepping for the one in the source url.

**Comment by Brainzyy** [comment]
Thanks for pointing that out, I'm really new to this stuff, sorry about that :p

**Comment by Brainzyy** [comment]
I just wrote a little script that fetches the hls stream from the given url: http://pastebin.com/cT5issHN

**Comment by sbstp** [comment]
I just finished work on a plugin I needed, I'll take a shot at this now.

**Comment by sbstp** [comment]
Alright, take a look at #23! If you want to try it, clone my fork of the repository (https://github.com/sbstp/streamlink) and checkout the `streamme` branch.

**Comment by Brainzyy** [comment]
It works perfectly, thank you @sbstp, closing.

**Comment by Brainzyy** [comment]
It works perfectly, thank you @sbstp, closing.
