### ISSUE TITLE
How to write streams automaticly (as they starts)

### ISSUE THREAD

**Issue by agentqwe** [streamlink/streamlink#170]
just tell me pls right direction where to search

**Comment by beardypig** [comment]
What do you mean @agentqwe, which stream are you trying to play? 

Maybe you want `--retry-stream` ?

```
  --retry-streams DELAY
    Will retry fetching streams until streams are found while
    waiting DELAY (seconds) between each attempt.
```

**Comment by agentqwe** [comment]
actually i want to automaticly found streams if there will be in my twitch followings, and start writing in file

**Comment by beardypig** [comment]
Like a twitch DVR? Sounds like a cool idea, but I don't think it's something `streamlink` will support directly. 

You could write a python script to do it for you though... You'd need to talk to the twitch API to get your list of followers, then periodically check if they have an online stream (be sure to check that they aren't hosting), and then could use the `streamlink` API to get the twitch stream and write it to a file :)

**Comment by agentqwe** [comment]
i thought the same,checkfollows,writes :) but problem is i dont know anything  in writing python script and any other scripts, i thought anybody give me "free" "open-source" script :)
anyway thx for --retry-streams, i started 1-2 cmd in background to wait new streams

**Comment by beardypig** [comment]
No problem, sorry I couldn't be more helpful.

**Comment by beardypig** [comment]
Maybe someone else knows if a Twitch DVR script :)

**Comment by bastimeyer** [comment]
https://askubuntu.com/questions/546548/twitch-livestream-downloading

You will need to modify the Twitch API requests, though, as it will now require a Client-ID since july (hence the issue with livestreamer).

**Comment by flijloku** [comment]
You can try to create such bat file(replace the output directory and the path to the livestreamer.exe if necessary ):

@
@echo off
::The requested URL
set /p param=The requested URL:

::Output directory
E:
cd E:\VODs

:loop
::Insert the date and time in the name of file
set h=%TIME:~0,2%
set m=%TIME:~3,2%
set s=%TIME:~6,2%
set curtime=%h%-%m%-%s%
::Replace 0 space arises if the time is less than 10:00
set curtime=%curtime: =0%
set dd=%DATE:~0,2%
set mm=%DATE:~3,2%
set yyyy=%DATE:~6,4%
set curdate=%yyyy%-%mm%-%dd%
set curdatetime=%curdate%__%curtime%
::Form the name of file
set vodname=%curdatetime%

livestreamer.exe --output %vodname%.flv   %param% best
timeout /t 60 /nobreak
goto loop

You can find some example here https://yadi.sk/d/dlmlpbl9xVucA (in БАТНИКИ.rar names beginning "ЗАПИСЬ"). There used nircmd program(google it) to assign variable values  of clipboard.

**Comment by gravyboat** [comment]
There hasn't been any discussion on this in a few days so I'm going to close it for now to try and keep the issues list clean.
