### ISSUE TITLE
Can i use streamlink on my project ?

### ISSUE THREAD

**Issue by aykuter** [streamlink/streamlink#1702]
Hey guys. I couldn't find any documentation or any info about that. I'm beginner python user so i want to try something on my own. If i install streamlink with pip can i use it for twitch ? If yes, how ? Can you give me short example code please ?  Thanks!

**Comment by beardypig** [comment]
This is a bit of info in the [API Guide](https://streamlink.github.io/api_guide.html) section in the docs. But if you have something specific that you want to do, maybe we can provide more specific guidance :)

**Comment by aykuter** [comment]
Ahh i couldn't see api section thanks for the info! I read it and i manage to fetch url. It's look like this:

`<HTTPStream('https://clips-media-assets2.twitch.tv/BN-cm%7C2464678215.mp4')>`

But i couldn't find any detailed info. Is there any built in method for download directly from this url ?

**Comment by beardypig** [comment]
`HTTPStream` behaves kind of like a file object, you can called `open()` and then `read()` to get data from the stream. So you could use `shutil.copyfileobj` to copy the stream to a file.

Something like this might work:
```python
stream.open()
with open("output.ts", "wb") as of:
    shutil.copyfileobj(stream, of)
```

**Comment by aykuter** [comment]
It's throw me error if i try it like this `shutil.copyfileobj(fd, of)`. But i checked api section and tried something like that. It's worked perfectly. Thank you soo much for your guidince! Really appreciated! :)

`   fd = stream.open()
    with open("output.mp4", "wb") as of:
        shutil.copyfileobj(fd, of)`

**Comment by beardypig** [comment]
No problem, glad you got it working :)

**Comment by gravyboat** [comment]
Closing since this seems resolved.
