### ISSUE TITLE
Available streams: 500k (worst), 800k, 1000k (best) and ...nothing

### ISSUE THREAD

**Issue by Texnozaur** [streamlink/streamlink#1719]
Hello ,sir!
What is wrong in this situaton: 
Newbie@cygnus-x:~# streamlink  "hlsvariant://http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8" 
[cli][info] Found matching plugin hls for URL hlsvariant://http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8
Available streams: 500k (worst), 800k, 1000k (best)
Newbie@cygnus-x:
If I`m paste the  http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8 link into ,Firefox open/save dialogue box appears. If I`m use /stream1,/stream2 or /stream3 found in google,404
Any ideas are welcomed

**Comment by johnthecracker** [comment]
You are starting from the end, not from the beginning, that may be the wrong.

What is the main url from where you sniffed 

http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8 ?

**Comment by beardypig** [comment]
Looks like you found an out of date source, is this what you were looking for?
```
streamlink --http-header "Referer=http://reshet.tv/live/" -l debug https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8  best
```

**Comment by Texnozaur** [comment]
Thanks for your reply.These urls are totally different,even two different languages
http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8
 https://besttv1.aoslive.it.best-tv.com/reshet/studio/index.m3u8
2 johntecracker -both urls are main,and how I`m can start from beginning,by your opinion,please
2 beardypig - 2nd  stream works like a charm
Regards

**Comment by beardypig** [comment]
@Texnozaur the link in your original post no longer works, it is broken. Probably best to say which stream you want to watch as the m3u8 url doesn't give a lot of information.

**Comment by Texnozaur** [comment]
@beardypig Thanks for your patience with me.I`m want to watch 9,12 and 13 Israeli channels.13 works already.

**Comment by Texnozaur** [comment]
Let`s start with more order.
Stream for 9 is [http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8](url),it allows me to download/save .m3u8,but streamlink stops on 
**Newbie@cygnus-x:~# streamlink "hlsvariant://http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8"
[cli][info] Found matching plugin hls for URL hlsvariant://http://besttv199.aoslive.it.best-tv.com/hls-live/contactgbs-gostreaming1/_definst_/live.m3u8
Available streams: 500k (worst), 800k, 1000k (best).
Stop.

**Comment by beardypig** [comment]
You need to specify the quality you want, eg `best` - `streamlink http://... best`. However, that stream is broken, it not longer exists - for some reason the `live.m3u8` file is still there but not the others.

**Comment by Texnozaur** [comment]
@beardypig -Understood,Sensey.You`re very first person,who tolled me this important moment.
Now,if you isn`t tired of my incompetence-yes I`m real noob  can you tell me,how can I fix this
` streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 AOL/9.8 AOLBuild/4346.2019.US Safari/537.36" --http-header "Referer=https://google.com/" "hlsvariant://https://keshethlslive-i.akamaihd.net/hls/live/512033/CH2LIVE_HIGH/index_3100.m3u8 best
`Thanks

**Comment by beardypig** [comment]
This is not really the forum for this kind of support. If you have an official website that has a stream for the channels you want, you should create a plugin request issue describing the site that you want Streamlink to support.

**Comment by Texnozaur** [comment]
@beardypig Thank you!

  &#127866
