### ISSUE TITLE
Support for Steam Broadcasting

### ISSUE THREAD

**Issue by desperation123** [streamlink/streamlink#173]
Hey boys and girls, 
Recently jumped ship over to streamlink and was wondering if you guys could figure out how to enable support for Steam Broadcasting.

The folks over at livestreamer gave it a crack, but development for it soon died out.
(Here's the link to the livestreamer issue thread: https://github.com/chrippa/livestreamer/issues/621)

This may be a bit of an ask because it requires the user to be logged in but I'm fully happy to enter in my steam information to get it working.

Here's a link to the directory of live broadcasts: http://steamcommunity.com/?subsection=broadcasts

Hope this isn't too much of a challenge for you guys.
Cheers.

**Comment by RosadinTV** [comment]
@desperation123 Only some streams requires the user to be logged in? Because i tried some of thems and Works without logging.

**Comment by desperation123** [comment]
@RosadinTV Oh right, I'm guessing it's due to this option setting.

http://i.imgur.com/OHpNGgk.png

I've got a mate who I always watch and I always have to log in. 
Must have his setting on one of the friends settings.

**Comment by RosadinTV** [comment]
@desperation123 Got it, the problem here (asides of the plugin) is that Streamlink currently dont support this type of streaming method, the stream is based in separated audio and video chunks.
@beardypig This may work with pymp4? (Video= video/mp4 with avc1.4d4032 codec and Audio= audio/mp4 with mp4a.40.2 codec)

**Comment by beardypig** [comment]
I will take a look. DASH isn't currently supported, but I am working on it :-)

**Comment by beardypig** [comment]
Took a look a the steam broadcasts, it seems pretty easy to get the public stream URLs. Once I finish working on supporting DASH streams it won't be too hard to complete the plugin. I'll have to get a friend to broadcast something to get that bit working though.

**Comment by desperation123** [comment]
Is that for public broadcasts though?
Are there no issues with some broadcasts being friend only?

**Comment by beardypig** [comment]
I haven't tried a friend's only stream yet, or requesting a stream. I will go authentication a go in the next few days.

**Comment by gravyboat** [comment]
@beardypig Let me know if you need someone to test this with, I have enough bandwidth to handle the streaming process.

**Comment by beardypig** [comment]
I have made some progress with this, authentication is working and I was able to stream a friends stream. Just gotta get the DASH Stream stuff in a more stable state :)

**Comment by desperation123** [comment]
@beardypig mate, that's great news! let me know if you need people to help test it out.
I'd be happy to help and keep up the great work :D

**Comment by gravyboat** [comment]
@desperation123 Just as a heads up beardypig is on vacation so he won't be around for a bit, I'm sure he'll update you when he gets back!

**Comment by chriscapetown** [comment]
Hi @beardypig - Would love to hear more about your solution - are you back from vacation yet ? :)

**Comment by Reusable-Box** [comment]
Curious about this. Would love to see this plugin get added to streamlink.

**Comment by beardypig** [comment]
I have the plugin working. The only outstanding issue is two factor authentication, specifically how to ask the user for their 2FA code without breaking the code separation of `streamlink` and `streamlink_cli`. If you have 2FA disabled it works great, but I do not want to release a plugin that would force people to reduce the security of their steam account to use.
