### ISSUE TITLE
Vaughnlive RTMP port changed from 1935 to 2935

### ISSUE THREAD

**Issue by jshir** [streamlink/streamlink#1730]
Very brief bug, very simple fix.

rtmp_server_map for all requests uses 192.240.105.171:1935 and doesn't work. (No data returned from stream)
rtmp_server_map change all requests to 192.240.105.171:2935 works for me.

**Comment by beardypig** [comment]
Thanks for the info @jshir, did you want to create a PR?

**Comment by jshir** [comment]
Sure, can you authorize me on this repository then?

**Comment by jshir** [comment]
Never mind, I was doing something wrong. Check PR 1731.
