### ISSUE TITLE
How to play VOD @ Afreeca TV ?

### ISSUE THREAD

**Issue by nOLanSea** [streamlink/streamlink#1733]
Good day.

Please advise is there possible to watch VOD from Afreeca?
For example like this http://vod.afreecatv.com/PLAYER/STATION/33963812

If yes, please show how.

Thanks a lot in advance.
Best regards.

**Comment by nOLanSea** [comment]
No one knows ?

**Comment by back-to** [comment]
you could use https://mpv.io/

```
$ mpv http://vod.afreecatv.com/PLAYER/STATION/33963812
Playing: http://vod.afreecatv.com/PLAYER/STATION/33963812
 (+) Video --vid=1 (h264 1920x1080)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 06:23:34 / 13:44:42 (46%) A-V:  0.000 Dropped: 4 Cache:  1s+1MB
```

the video is split into **14 m3u8 urls**, so it's a bit ugly for streamlink

**Comment by nOLanSea** [comment]
Many thanks.

**Comment by back-to** [comment]
closing,
VOD support is getting reduced in Streamlink and I don't think this will be added in the near future.
