### ISSUE TITLE
Support for facebook VOD?

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1738]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would like to be able to playback vod type of streams from facebook

### Expected / Actual behavior

Same as above

### Reproduction steps / Explicit stream URLs to test

1. Installed streamlink via pip
2. Typed in windows poweshell
3. Video: https://www.facebook.com/TheReplayShow/videos/202429560572428/

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
streamlink -l debug https://www.facebook.com/TheReplayShow/videos/202429560572428/
[console][debug] OS:         Windows 10
[console][debug] Python:     3.6.4
[console][debug] Streamlink: 0.12.1+98.g4924b8a
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin facebook for URL https://www.facebook.com/TheReplayShow/videos/202429560572428/
error: No playable streams found on this URL: https://www.facebook.com/TheReplayShow/videos/202429560572428/
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/pull/1740

**Comment by beardypig** [comment]
Thanks for the report @Twilight0, this has been resolved in #1740 :)

**Comment by Twilight0** [comment]
This one doesn't play, however: https://www.facebook.com/prokolgotki/videos/1032870746862832/

**Comment by back-to** [comment]
> You must log in to continue.

you could try to use cookies

**Comment by Twilight0** [comment]
Facebook plugin doesn't support login, yet, as far as I understand. As for cookies where do I find them in the first place to load them into streamlink.

**Comment by Twilight0** [comment]
Well, thank you to say the least for adding VOD support.

**Comment by beardypig** [comment]
You'll need to login to Facebook and look at the cookies and work out which ones you need. You can set them using `--http-cookie`.
