### ISSUE TITLE
vidio plugin [https://www.vidio.com]

### ISSUE THREAD

**Issue by rollykaunang** [streamlink/streamlink#1741]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Hello Admin Could you guys take a look vidio plugin it is broken now.

Unable to open url
403 Client Error Forbidden for url
Here is the the link https://www.vidio.com/live/204-sctv-tv-stream

Https://www.vidio.com

...

### Expected / Actual behavior
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/777-metro-tv-stream
[plugin.vidio][debug] HLS URL: https://kmklive-lh.akamaihd.net/i/metrotv_ta_regular@577566/master.m3u8
error: Unable to open URL: https://kmklive-lh.akamaihd.net/i/metrotv_ta_regular@577566/master.m3u8 (403 Client Error: Forbidden for url: https://kmklive-lh.akamaihd.net/i/metrotv_ta_regular@577566/master.m3u8)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)
@beardypig beardypig

**Comment by beardypig** [comment]
Could you provide a debug log too (`-l debug`)? The `vidio` plugin was fixed recently, so you'll need to be running the [latest dev version](https://streamlink.github.io/install.html#source-code) for it to work.

**Comment by rollykaunang** [comment]
@beardypig 
I installed the latest dev version. 
It is work..
Thank You so much Mr Beardpig.
So this issue is closed now.
