### ISSUE TITLE
Problem with '--quiet' or '--json' options

### ISSUE THREAD

**Issue by BZHDeveloper** [streamlink/streamlink#1742]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

With previous versions, add '--json' option to command line print JSON information without traditional debug info : `[console][info] ....`
Today, these debug lines are constantly present, whether the '--quiet' option is there or not

### Expected / Actual behavior

print desired information with the correct options

### Reproduction steps / Explicit stream URLs to test

1. `streamlink "https://rmcsport.bfmtv.com/mediaplayer/live-bfm-sport/" --json`
2. observe first line in the console output `[console][info] Found matching plugin bfmtv for URL https://rmcsport.bfmtv.com/mediaplayer/live-bfm-sport/`

**Comment by BZHDeveloper** [comment]
ok. I've to specify `-l none` ...

**Comment by beardypig** [comment]
Thanks for the report @BZHDeveloper, I've submitted a PR that should resolve it.
