### ISSUE TITLE
Streamlink execution takes 13 seconds

### ISSUE THREAD

**Issue by majuss** [streamlink/streamlink#1743]
My raspberry pi 3 b is working as a webserver which serves twitch .m3u URLs from a given channel. It takes a significant time to get back the .m3u stream. Version of python is 3.5, Raspbian is up to date.

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
When I want to parse the m3u URL from a Twitch stream, the program takes 13 seconds to get the stream URL back.

### Expected / Actual behavior
Why is it so slow? Any way to speed it up? CPU usage is 100 % on one core.

### Reproduction steps / Explicit stream URLs to test

1.  Run `date; streamlink https://www.twitch.tv/beyondthesummit best --stream-url; date` on a raspberry.

**Comment by beardypig** [comment]
Would you be willing to run some commands to help benchmark it?

First `time treamlink http://example.com/no-stream-here`

**Comment by majuss** [comment]
Of course I will :) 

`real: 0m19.294s; user: 0m9.892s; sys: 0m1.167s`

I'am just asking myself whats so performance intensive? Streamlink is not calculating quantum physical equations :D

**Comment by Erk-** [comment]
I ran it on a faster machine to get:
```
real    0m2,970s
user    0m0,691s
sys     0m0,083s
```

**Comment by beardypig** [comment]
OK, maybe a better test is
```
time streamlink http://google.com/404
```

**Comment by back-to** [comment]
the twitch plugin can be speedup
with changing the way of `self.options.get("disable_hosting")`
`hosted_channel` runs every time

https://github.com/streamlink/streamlink/blob/c1489782cf2644e9194c4d2fdcc3f6198e49a538/src/streamlink/plugins/twitch.py#L579

normal

```
$ time streamlink https://www.twitch.tv/beyondthesummit best --stream-url

real	0m2,461s
user	0m0,544s
sys	0m0,049s
```

removed

```
$ time streamlink https://www.twitch.tv/beyondthesummit best --stream-url

real	0m1,407s
user	0m0,546s
sys	0m0,026s
```

**Comment by beardypig** [comment]
There are a few cases to consider:

with up-front check:
 - If channel is not hosting, 3 API calls (get hosted, get stream)
 - If channel is hosting, 3 API calls (get hosted, get stream)
 - If channel is hosting and `disable-hosting`, 1 API call (get hosted)

without up-front check:
 - If channel is not hosting. 2 API calls (get stream)
 - If channel is hosting, 5 API calls (get stream, get hosted, get stream)
 - If channel is hosting and `disable-hosting`, 2 API call (get stream)


With out the up-front check, the "normal" case of a channel not hosting is one API call faster - this might be an improvement if this is the most common use case. Any case where the channel is hosting, there will be more API calls.

**Comment by Erk-** [comment]
Could the `disable-hosting` value be exposed to the commandline somehow.

**Comment by beardypig** [comment]
@Erk- `--twitch-disable-hosting` is already available.

**Comment by majuss** [comment]
So I did some benchmarks with the hosting disabled and enabled. Here are the results:

With hosting:
```
real	0m12.444s
real	0m13.286s
real	0m12.023s
real	0m13.063s
real	0m11.882s
real	0m12.442s
real	0m17.041s
real	0m13.531s
real	0m13.296s
real	0m12.409s
real	0m12.279s
real	0m15.075s
real	0m11.942s
real	0m11.771s
real	0m16.949s
real	0m12.812s
real	0m12.607s
real	0m11.920s
real	0m12.039s
real	0m12.598s
```

WIthout hosting:
```
real	0m12.042s
real	0m14.046s
real	0m12.416s
real	0m11.888s
real	0m12.423s
real	0m15.663s
real	0m12.064s
real	0m12.142s
real	0m11.967s
real	0m12.354s
real	0m12.539s
real	0m11.990s
real	0m12.491s
real	0m14.931s
real	0m16.512s
real	0m12.095s
real	0m11.932s
real	0m12.609s
real	0m11.843s
real	0m15.085s
```

As you can see, it doesn't make any difference. I still ask myself why the parsing is so heavily depended on the CPU power. I don't see how something so simple can take up a so long time.

**Comment by beardypig** [comment]
@majuss could you try with a different plugin, for example with a YouTube video and see if that takes a long time too?

**Comment by WolfganP** [comment]
Just an idea. As streamlink is using 'logging' module for the logs, isn't there any way to allow it print the timestamp of the events in debug level and use the logs as a basic profiler for initial troubleshooting? (as in logging.basicConfig example at https://docs.python.org/2/library/logging.html)

**Comment by beardypig** [comment]
@WolfganP a good idea :)

**Comment by WolfganP** [comment]
I have no access to my system right now, so I'm not sure if code needs to be modified, but with the logging.basicConfig formatting example seems to be only needing to be changed once and globally, then it applies to each debug call.

**Comment by beardypig** [comment]
@WolfganP pretty much, there is some slightly customised logging logic to handle backward compatibility with the old logger module and differences between Python 2 and 3. But mostly it's straight forward. I would not add the time option when debug logging is enabled, as this could possibly break some other peoples scripts. We added a new logging level, trace, which could be used as a signal to turn on timestamps.

**Comment by beardypig** [comment]
I added a time stamp when using the `-l trace` option.

@majuss are you able to install the latest version from git and run it again with `-l trace`, and post the output?

**Comment by majuss** [comment]
Stupid question: how can I view the logs? When I use: `-v -l trace` its still shows nothing in the terminal and I couldn't find a filepath in the source.

**Comment by beardypig** [comment]
@majuss `-l trace’ should do it. If you update to 0.13.0 it should work now, previously you needed the dev version from git. You can double check the specific version you have with `--version`.

**Comment by majuss** [comment]
`streamlink -l trace https://www.twitch.tv/beyondthesummit best --stream-url` is resulting in just the .m3u URL.

**Comment by beardypig** [comment]
@majuss Ah, OK! :) Drop the `--stream-url` as that is silencing the logs :) You can drop `best` too as it should take the same amount of time.

**Comment by beardypig** [comment]
Could try 

```
date +"[%T,%3N] GO!"; time streamlink -l trace https://www.twitch.tv/beyondthesummit
```

too see if start-up is slow...

**Comment by majuss** [comment]
```
date +"[%T,%3N] GO!"; time streamlink -l trace https://www.twitch.tv/beyondthesummit
[21:37:14,993] GO!
[21:37:18,653][console][debug] OS:         Linux-4.14.34-v7+-armv7l-with-debian-9.4
[21:37:18,654][console][debug] Python:     3.5.3
[21:37:18,654][console][debug] Streamlink: 0.13.0
[21:37:18,655][console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[21:37:18,655][console][info] Found matching plugin twitch for URL https://www.twitch.tv/beyondthesummit
[21:37:18,656][plugin.twitch][debug] Getting live HLS streams for beyondthesummit
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)

real	0m7.794s
user	0m5.633s
sys	0m0.210s
```

I watched with the IO with `iotop -aoP` but python doesn't r/w anything.

**Comment by beardypig** [comment]
We could probably add a bit more trace logs, for loading plugins - I imagine that is slow on the RPi. Maybe you can delete all the plugins except twitch and see then.

**Comment by majuss** [comment]
So I cloned the repo, deleted all plugins except twitch and ran the setup.

```
time streamlink -l trace https://www.twitch.tv/beyondthesummit
[15:12:36,782][console][debug] OS:         Linux-4.14.34-v7+-armv7l-with-debian-9.4
[15:12:36,782][console][debug] Python:     2.7.13
[15:12:36,783][console][debug] Streamlink: 0.13.0+8.gcc51537.dirty
[15:12:36,783][console][debug] Requests(2.12.4), Socks(1.6.7), Websocket(0.48.0)
[15:12:36,784][console][info] Found matching plugin twitch for URL https://www.twitch.tv/beyondthesummit
[15:12:36,784][plugin.twitch][debug] Getting live HLS streams for beyondthesummit
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)

real	0m6.420s
user	0m3.511s
sys	0m0.591s
```

**Comment by beardypig** [comment]
That's about the same speed as on my VM, and my PC does it in around 4 seconds. I don't think 6-7 seconds is too bad for a Pi :)

**Comment by back-to** [comment]
closing, as said above most of it is hardware related.
