### ISSUE TITLE
Let's have a celebratory 1.0.0 release!

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#1745]
We've got a new release script, awesome work done by @beardypig and @gravyboat including a HUGE contribution with MPEG DASH support.

In my opinion, streaming / using Streamlink has been super-stable. No major API changes / CLI changes, nor any negative feedback from the community.

Should we celebrate this milestone and finally push a 1.0.0 release out?

**Comment by beardypig** [comment]
I'm all for it. Need to closely monitor the process though, with all the release changes :) 
Does anyone have any features that are blocking 1.0.0? 

I would say that #1744 is blocking this.

**Comment by gravyboat** [comment]
Most of the work was done by @beardypig I've just been reviewing all the work! I think we need a new logo before we do a 1.0.0 release personally which we own all rights to. This means we can use it on stickers, t-shirts, or whatever else may be needed in the future to support continued development and pay for any fees that may come up without having to worry about someone claiming ownership. In Bountysource we have $149.69 (which they will take a cut of when we cash out), and $165.73 in Open Collective for a total of $315.42 USD. Surely we can get someone to design a logo which we own the rights to for a few hundred dollars. We've previously discussed this here: https://github.com/streamlink/streamlink/issues/1123 regarding ideas. If we're going to do a big release like this we might as well go big with it.

**Comment by roshavagarga** [comment]
@gravyboat - Have you considered reaching out to supporters through Reddit? You could very well have one that's an illustrator/graphical artist that would be willing to make a logo for free, that way enabling the team to save the cash and use it towards something else.

**Comment by mmetak** [comment]
I agree with @roshavagarga , all the moniez to @beardypig !  ;-)   He definitely deserves it.
Couldn't care less about the logo, it's more important to get that money to devs who spend their time and energy to keep this project alive. Keep it up everyone.

**Comment by gravyboat** [comment]
@roshavagarga In terms of which subreddits? We don't maintain the Streamlink subreddit and there's barely anyone subscribed there any way. If you have ideas I'm open to them, but the key issue we've had with people offering design services (as discussed in #1123) is they either want to be credited in more ways than we're willing, or people have wanted to retain rights to the image which could place become a problem in the future.

@mmetak I agree, but it's important we own all rights to the logo so we can do things like print stickers, make t-shirts, or whatever else to continue supporting development. We have over 15k users and there's somewhere between 10-15 people who have donated so about 0.1% of people who use Streamlink support us (and we really appreciate those who have donated). If we can bump that number up even 1% by offering alternative options for support it's worth the investment. More than anything though it's about image ownership and ensuring we won't encounter any problems in the future.

**Comment by gravyboat** [comment]
@Ike348 Thanks for the kind words. I'm definitely of the same mind that money should go to contributors and I really hate to spend it in this sort of way but we haven't had luck finding someone to create a logo for us that's willing to do it for free and give us ownership of the image without various requirements. For me we have to make sure we own things like the logo so we can try other methods to get people involved in supporting the software so that we can pay contributors instead of just skirting by hoping we don't have some random cost we can't afford.

At this point we've tried quite a few things (supporting bounties on issues, another platform which people can pay into in various ways, updating release notes providing ways people can support us, making it so the issue template notes that people can support us, direct documentation notes saying how people can pay each individual, etc.) and we've had very little luck there. I will never be okay with adding any kind of message or log within the software itself asking people to support us financially as I personally hate when software includes such messages but I'm running out of ideas. As I noted before I am open to suggestions.

**Comment by beardypig** [comment]
@Ike348 glad you’re find the dash support useful :) 

@gravyboat @cdrage maybe we should do a 0.13.0 release to test the script, and get the dash stuff in to the hands of more people for more testing :)

**Comment by gravyboat** [comment]
@beardypig I'd be down for that. It would be kind of funny if the 1.0.0 release was messed up due to some sort of release script bug and we had to do another release. There are some major changes though so I'm not sure how @bastimeyer would feel about doing a release that wasn't a major bump.

**Comment by beardypig** [comment]
I don't think anything API-wise changed that doesn't remain backward compatible (at least, that's the intention) and in terms of console output it's mostly the same too.

**Comment by cdrage** [comment]
@beardypig @gravyboat No problem! Should I go ahead with a 0.13.0 release? Any blockers?

**Comment by beardypig** [comment]
Nothing from me :)

**Comment by bastimeyer** [comment]
@gravyboat 
AFAIK, there were no breaking changes. The only changes that could break the Twitch GUI are some of the log outputs, but none of them got changed. A major version bump would be an opportunity though for changing the log format, as I've suggested [here](https://github.com/streamlink/streamlink/pull/1635#issuecomment-392619939), which would make applications relying on log output resistant to the rewording of any log output lines. Maybe this could be added to the new trace loglevel @beardypig has added, or a new one.

Regarding the 1.0.0 release, I'm also in favor of another minor bump first.

**Comment by beardypig** [comment]
Reading the log output is pretty fragile... how much does the Twitch GUI do? It would be better to define some json-based communication protocol, it would also allow for plugins to communicate (twitch delay??) ;-)

**Comment by bastimeyer** [comment]
That would be an even better solution, because it could add data to it.

**Comment by cdrage** [comment]
I'm going to try and push a 0.13.0 release today. Hopefully nothing breaks :heart:

**Comment by cdrage** [comment]
Pushed: https://github.com/streamlink/streamlink/releases/tag/0.13.0

Hopefully Travis CI builds this correctly / pushes it :+1: @beardypig @bastimeyer @gravyboat

**Comment by cdrage** [comment]
@beardypig @gravyboat 

Looks like it's missing the previous CHANGELOG? https://travis-ci.org/streamlink/streamlink/jobs/388850835#L3035

I tried debugging this locally but no luck. Was there a step I was missing on adding a new CHANGELOG.md?

**Comment by cdrage** [comment]
@beardypig Ahh.

So what should the steps be? Do I create a tag as well as push a PR that updates the CHANGELOG or just CHANGELOG?

**Comment by beardypig** [comment]
You should do like you did before, create a PR to update CHANGELOG - then we merge that, then create a tag :)

**Comment by cdrage** [comment]
Ahhhh okay.

**Comment by beardypig** [comment]
Just to update; the `wheel` for `0.13.0` has been remove from PyPI and from the GitHub release, this is because it is broken on Python 2.7.

**Comment by gravyboat** [comment]
#1758 is now merged.

**Comment by unlocKing** [comment]
@gravyboat 

How far have you got with the new logo, was anything ever presented?

If not I can recommend the dude that does the artwork for most of the top Kodi addons..

His work is always great and he never charges open source projects.

Let me know and I'll ask him to present some ideas :)

**Comment by gravyboat** [comment]
@unlocKing We haven't gotten anywhere with a new logo unfortunately. None of us are designers, and the few people who were interested wanted to either keep the rights to the image, or they wanted additional advertising for their site/company past what we currently are willing to do. We had a lot of discussion on it here: https://github.com/streamlink/streamlink/issues/1123, and we are willing to pay someone but it's crucial that we own the rights to the image so we can use it however we see fit without paying any royalties or allowing it to be used in projects we may not endorse.

**Comment by unlocKing** [comment]
@gravyboat The artwork he has always provided is always given to us to do with as we please, he has never asked for anything in return which is cool.. obviously at the same time, don't be rude by not saying thanks publicly! :)

Only thing I ask is that we be allowed to use the artwork for our streamlink-kodi addon icon or a variation of it depending on the final image.

If you're cool with that, let me know and I'll arrange the intros.

**Comment by gravyboat** [comment]
@unlocKing We would of course thank/pay the person, it's just been an issue in the past so I like to be up front as to not waste their time. I don't want it to become an issue in the future if we make stickers or something and the creator of the art wasn't aware we would potentially use it for that purpose and feels slighted in some way.

I don't have any issue with the artwork being used for the streamlink-kodi addon but that would also need approval from people like @beardypig, @cdrage, @back-to, and @bastimeyer. If they're also okay with then let's proceed. I'd really like to get this done.

**Comment by beardypig** [comment]
@unlocKing which `streamlink-kodi` addon is that???

**Comment by unlocKing** [comment]
@gravyboat He is reachable on Keybase.. I'm sure he would be happy for a payment if that's what you want to do, but that'll be between you and him to decide.

@beardypig We're a small group of 3rd party Kodi developers who have some some of the most popular addons in the past. We now have just taken on the work started by @Twilight0 and started to make several enhancements with a focus on crypto and function to be used on the Kodi platform. We will be releasing this by the end of the month.

If you would like to discuss the work carried out so far in detail or in general about the project, you are more than welcome to join our secure Streamlink Keybase group where all development is being discussed.

If either of you are not familiar with Keybase, you can join here: https://keybase.io - Once you have joined, search for my GitHub username to connect with me or search for the streamlink team and I'll add you into the group.

**Comment by back-to** [comment]
if you want to release `1.0.0`,
some dependencies should probably be updated for the Windows installer

https://github.com/streamlink/streamlink/blob/e5995ee1a9c329d7ec9f0ac16fcf740aa24433e2/script/makeinstaller.sh#L36
https://github.com/streamlink/streamlink/blob/e5995ee1a9c329d7ec9f0ac16fcf740aa24433e2/script/makeinstaller.sh#L69
https://github.com/streamlink/streamlink/blob/master/win32/ffmpeg/README.md

**Comment by beardypig** [comment]
`ffmpeg` we need to remove from the repo...

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/pull/2199
