### ISSUE TITLE
Small update issue with Windows installer

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#1750]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
After wondering for a day or so why Facebook live streams were only giving me 360p, I finally discovered that even though I'd been installing new versions for several days (nightlies), my current version was stuck at 0.9.0

Quick uninstall and reinstall fixed the problem which I believe occurred because the Windows installer defaults to "Install for everyone on this machine" instead of the "Install only for me" which I previously used. It is sort of my fault for not noticing that it had switched, but it seems installing it in one way does not update the program if you installed it the other way beforehand.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/1340
https://github.com/streamlink/streamlink/issues/1391#issuecomment-354275115
