### ISSUE TITLE
How can i get this (look inside)

### ISSUE THREAD

**Issue by PostMalone** [streamlink/streamlink#1751]
So i had a look arround the web and i saw that some people are Streaming on their website ESPN2 for free. With just HLS (.m3u8), their hls looks like this: http://ak-hls-brs-espn2.espn.go.com/hls/live/218615/p/espn2-p.m3u8

And a lot of people can watch it. How is it possible? Also i noticed that i need some "Keys". Is this right?

Here is a screenshot of the website Source code: http://prntscr.com/jr2iuo

Thanks

**Comment by beardypig** [comment]
They are sharing one ESPN account by rewrite the encryption key path in the M3U8. 

This is not something that we will support in Streamlink.
