### ISSUE TITLE
[Plugin] FirstOneTV

### ISSUE THREAD

**Issue by erich-b** [streamlink/streamlink#1763]
### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Website https://www.firstonetv.eu offers lots of channels in good quality.

### Expected / Actual behavior

The site generates m3u8 URLs when beeing accessed by a user agent that does not seem to allow embedded videos. These m3u8 URLs are only valid for a few minutes and only for the requesting IPaddress.
Would be great to see a plugin that can work with URLs like https://www.firstonetv.net/Live/United-Kingdom/BBC-One--4 to generate the current m3u8 URL and play it.

### Reproduction steps / Explicit stream URLs to test

1. https://www.firstonetv.net/Live/United-Kingdom/BBC-One--4
2. https://www.firstonetv.eu/Live/United-Kingdom/BBC-News-2
3. https://www.firstonetv.eu/Live/United-Kingdom/ITV1-21

**Comment by gravyboat** [comment]
This site is just hosting stolen content and we've been taking the stance to avoid adding any more sites like this.

**Comment by erich-b** [comment]
So Filmon doing the same thing in worse quality and also charging money for most channels is ok, but firstonetv is not?!

**Comment by gravyboat** [comment]
Filmon has existed as a plugin for quite some time. As I noted above we want to avoid adding any MORE plugins like this. Not adding new plugins is a lot easier than removing old ones that are already supported.

**Comment by johnthecracker** [comment]
Sadly, there are too few developers here and too many demands.

There are streamlink forks starting to emerge, you may find it if you look for it.

You may ask the same thing there, who knows.

Your provided some good information in Expected / Actual behavior.

Cheers.

**Comment by beardypig** [comment]
The legality of this type of website is a bit of a grey area. TV companies have tried to remove channels from FilmOn, but have mostly be denied by the courts (in the US). It seems like channels that are broadcast “free to air” are fair game, encrypted channels (without license) are not.

@gravyboat I think we should write up a policy for which type of sites we want to support. It would be good to get some input from the other core contributors - @back-to, for sure and @bastimeyer.

**Comment by Twilight0** [comment]
Most streams if not all are legit as I can see because they are public ones. A good chance to try and make my first plugin, although this site does not "host" plain m3u8 only, they have youtube ones, like this:
https://www.firstonetv.net/Live/Greece/ERT1-(EPT1)-3

**Comment by gravyboat** [comment]
@beardypig Yeah we definitely need to get some sort of policy out regarding this. My issue with many sites like this the streams are already available fro free elsewhere (and a lot of the time supported by other plugins) so why do we need to support a site that is simply streaming content that's already available? It's just a waste of time and bloats Streamlink while providing almost no benefit. We're already seeing examples of the bloat negatively impacting users when they have to load in tons of plugins on devices with limited resources.

**Comment by maxj88** [comment]
@gravyboat 
Yeah, FirstOne TV has many official or public streams, but they also have some quite good and stable HD streams on their own servers.
Like BBC, ITV, France, Italy, German... channels

I found a access token for their API:
https://www.firstonetv.net/api/?action=channel&ctoken=apptest&c=uk&id=4
c is the country code, id is the channel id which can be found on the end of the link.

example:
https://www.firstonetv.net/Live/United-Kingdom/BBC-One--4
country code is uk, id is 4

**Comment by beardypig** [comment]
They are re-hosting a bunch of streams, the BBC streams for example. They also include a lot of subscription channels, which I cannot believe they have license for... This website is almost certainly *not* legit. It is a simple site to write a plugin for though.

**Comment by Ordval** [comment]
I've come with this Plug-In request myself (#1369), but got rejected. 
If most of its content is available in already existing Plug-Ins
I'd like to know which channels to which Plug-Ins, 
but who'd want to make that kind of list ?  

On the subject to "subscription channels" 
I got the answer to a request made by me to FirstOneTV   
(marked as X here):
" 'X' Channels are not possible due to legal reasons, sorry".

**Comment by jasonalshamary** [comment]
maxj88

can you till me how did you found a access token for their API

**Comment by jasonalshamary** [comment]
@maxj88

can you till me how did you found a access token for their API

**Comment by gravyboat** [comment]
Locking this as the issue is quite old.
