### ISSUE TITLE
ustream plugin broken

### ISSUE THREAD

**Issue by sokkycakes** [streamlink/streamlink#1767]
Ustream plugin cannot get a stream, it returns this error:

```
Traceback (most recent call last):
  File "C:\Users\sokky\AppData\Local\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 1055, in main
    handle_url()
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 486, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink_cli\main.py", line 398, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 385, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugin\plugin.py", line 294, in streams
    ostreams = list(ostreams)
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugins\ustreamtv.py", line 253, in _get_streams
    for s in self._api_get_streams(media_id, application):
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugins\ustreamtv.py", line 181, in _api_get_streams
    for s in self._do_poll(media_id, application, cluster, referrer, retries):
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugins\ustreamtv.py", line 195, in _do_poll
    referrer, retries):
  File "C:\Users\sokky\AppData\Local\Streamlink\pkgs\streamlink\plugins\ustreamtv.py", line 210, in handle_module_info
    yield q, UStreamHLSStream(self.session, s.url, self.api)
AttributeError: 'MuxedHLSStream' object has no attribute 'url'
```

**Comment by beardypig** [comment]
Looks like something has changed with their m3u8 playlists, I will take a look. Thanks for the report @sokkycakes.

**Comment by tgmasterx1987** [comment]
Same Problem on Desktop, but on Android works all fine...
Solution: uninstall ffmpeg, then ustream links working again. But Video only! It seems to be ibm stream audio over different stream... :/
If the stream over the site the chunk files are no hls files. they are mov (e.g. Quicktime) files...

**Comment by beardypig** [comment]
@sokkycakes Could you give an example of the streams that fail with this error? I have tried a few, but I cannot find one that doesn't work.

**Comment by back-to** [comment]
http://www.ustream.tv/channel/18525677  from https://github.com/streamlink/streamlink/issues/1653

```
   src/streamlink/plugins/ustreamtv.py", line 221, in handle_module_info
    yield q, UStreamHLSStream(self.session, s.url, self.api)
AttributeError: 'MuxedHLSStream' object has no attribute 'url'
```

---

and http://www.ustream.tv/channel/live-iss-stream works only for 20 sec or won't start at all

```
error: Error when reading from stream: Read timeout, exiting
```
because `[stream.hls][debug] Reloading playlist` won't get any new data

**Comment by beardypig** [comment]
Thanks @back-to

**Comment by jshir** [comment]
#1777 does not seem to resolve the problem of no audio stream being output. I have the same problem as tgmasterx1987. 
Testing http://www.ustream.tv/channel/rdaextra and http://www.ustream.tv/channel/rainbowtownfm and they both do this.
Don't know if it warrants a separate issue.

**Comment by liamkennedy** [comment]
Looks like this is the issue that is most related to mine (I think).  Ustream channels quit after 15 seconds or so.  Let me know if I can help with testing a fix (wish I could help actually come up with the FIX.. but alas.. that's a little out of my capabilities).  The PR for #1777 definitely does not fix the "reloading playlist"  issue for me (I implemented the PR for ustreamtv.py on 0.13.0 just to see if it helped).

**Comment by gravyboat** [comment]
@liamkennedy Are you getting any useful output if you run Streamlink with `-l debug` or is it just the typical stuff that then shows the playlist failing to reload?

**Comment by liamkennedy** [comment]
@gravyboat Yeah.. just getting the usual stuff showing a few segments loading.. then goes in to the "Reloading playlist" loop

repost of my comment on #1777 

> Does this issue explain why I can only play out about 15 seconds of a Ustream channel before it freezes? Youtube live streams seem to be ok.
> 
> Testing this on 0.13.0 (and tried it on some older versions too just to see)
> 
> These are example streams to see the issue - Ustream and Youtube
> 
> TWiT / Leo Laporte
> Ustream (**freezes**)
> `streamlink http://ustream.tv/leolaporte best --player omxplayer --fifo -l debug`
> Youtube (works)
> `streamlink https://www.youtube.com/watch?v=Zs5Z2EGqJFw best --player omxplayer --fifo -l debug
> `
> Or NASA's HDEV stream (will be blank regularly - and no audio so a little more difficult to use to help figure this out).
> Ustream (**freezes**)
> `streamlink http://www.ustream.tv/channel/iss-hdev-payload best --player "omxplayer" --fifo -l debug`
> Youtube (works) - By the way... yes.. NASA is now streaming this via Youtube - just added last week.
> `streamlink https://www.youtube.com/watch?v=625ZC_KpweI best --player omxplayer --fifo -l debug`
> 
> The debug output is as expected. For Ustream you see a few successful segment downloads initially followed by Reloading playlist messages.. then it eventually quits. For Youtube.. nothing unexpected.. it just keeps loading the segments as expected.

**Comment by tmladek** [comment]
Hi, can confirm all symptoms (works only w/ ffmpeg uninstalled, etc.), any progress on the issue? :)

**Comment by bastimeyer** [comment]
@tmladek https://github.com/streamlink/streamlink/issues/2161#issuecomment-437628039

**Comment by tmladek** [comment]
Oh sorry, didn't see that, thank you!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
