### ISSUE TITLE
PIP or Git Clone for installing on Raspberry Pi?

### ISSUE THREAD

**Issue by Junior1544** [streamlink/streamlink#177]
Which will be better for my situation..  I'm not a real linux user at all, but i've been playing with raspberry pi's and have a project I'm working on that will use streamlink....

Should I use PIP or GIt Clone to install?  Which will be easier to maintain and upgrade for me going forward?

Thanks!

**Comment by gravyboat** [comment]
Definitely pip. With a git clone you're going to have to do more system calls, with pip you can just spin a virtualenv for it (or just install to system if that's all you're using the Pi for) and then you're done.

**Comment by gravyboat** [comment]
@Junior1544 Can we close this?

**Comment by Junior1544** [comment]
Thanks guys and gals!

I hit close here.
