### ISSUE TITLE
Usage of ustv plugin ?

### ISSUE THREAD

**Issue by aykuter** [streamlink/streamlink#1772]
Hey guys! I'm struggling with ustvnow plugin and i couldn't figure it out. Username checked password checked but what is station code ? How can i find it ? Is that enough to use it ? Thanks.

**Comment by beardypig** [comment]
Unfortunately you need to know the station code, which is the internal name for the channel. They are a bit cryptic, but if you the url and don’t give a station code it should print them out.

**Comment by aykuter** [comment]
Thanks for the reply. I don't get it should i enter url to streamlink for print them out ? I can't actually get any link ustvnow made you watch all channels in home screen. Can you please give me a little more detail ?

**Comment by beardypig** [comment]
Did you try anything? `streamlink http://watch.ustvnow.com/` with the username and password?

**Comment by Ordval** [comment]
O.K. , really, really sorry to bother you **beardypig**,  but put in a command line (argument?) 
how would it (precisely) look ?
```
C:\Users\Ordval>call streamlink.exe "http://watch.ustvnow.com/" best
Enter ustvnow username: xxxxx@xxx.xx
Enter USTV Now account password:
[console][info] Frdvalound matching plugin ustvnow for URL http://watch.ustvnow.com/
[plugin.ustvnow][error] Station code not provided, use --ustvnow-station-code.
[plugin.ustvnow][error] Available stations are: discovery, whtm, animalplanet, tlchd, espntwo, whvl, sndnc, foxnews, wlyh, nickelodeon, whphd, syfy, natgeo, bbca, wpmt, fxhd, usahd, wpsu, frfrm, amchd, bravo, comedycentral, spiketv
error: No playable streams found on this URL: http://watch.ustvnow.com/ 
```
The input in cmd won't accept a password so I had to leave the field empty.

--ustvnow-email=xxx --ustvnow-password=xxx 
 ustvnow username: xxx  USTV Now account password: xxx  etc., etc. won't work, 
 so how ?

**Comment by beardypig** [comment]
@Ordval that should work, could you file a bug ?

**Comment by Ordval** [comment]
I've never written a bug file nor a report, however, the "Submit new issue"-button is greyed out,
also for the form in its original state.

**Comment by aykuter** [comment]
I tried this one (i see this arguments on streamlink's webpage) :
`streamlink http://watch.ustvnow.com/ --ustvnow-username xxxx@xxxx.com --ustvnow-password xxxxx`
but it's giving me error :
`streamlink-script.py: error: unrecognized arguments: --ustvnow-username xxx@xxxxx --ustvnow-password xxxxxx`    

And i tried @Ordval suggestions too but failed.

`error: No plugin can handle URL: http://watch.ustvnow.com/watch/whphd `

Whats the correct usage of plugin ? I will try it like that so i will tell you if anything wrong

**Comment by beardypig** [comment]
@aykuter looks like you are not using the latest version, you should upgrade to 0.13.0 to get the ustvnow plugin.

**Comment by beardypig** [comment]
@Ordval this link doesn’t work? https://github.com/streamlink/streamlink/issues/new

**Comment by aykuter** [comment]
@beardypig I updated it and i'm taking this output:
```
C:\Program Files (x86)\Streamlink\bin>streamlink http://watch.ustvnow.com/ --ustvnow-username xxxx@xxxxxx --ustvnow-password xxxxx --ustvnow-station-code whtm --best
[console][warning] The option --best-stream-default is deprecated since version 1.9.0, use '--default-stream best' instead.
[console][info] Found matching plugin ustvnow for URL http://watch.ustvnow.com/
[console][info] Available streams: 136p (worst), 270p, 360p, 720p_alt, 720p (best)
[console][info] Opening stream: 720p (hls)
[console][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
```
It's starts playing but saying me stream ended after 4-5 seconds

**Comment by Ordval** [comment]
@**beardypig**

> @Ordval this link doesn’t work? https://github.com/streamlink/streamlink/issues/new

Still greyed out. Do the acceptance of cookies play any role in this ? Well, restarted  Firefox.
Reload of the page makes the button highlight for a moment, then greys down.

**Comment by Ordval** [comment]
Following **aykuter**'s example, with and without `--default-stream`, I also get it to open 
but only with the worst quality:
```
C:\Users\Ordval>call streamlink.exe "http://watch.ustvnow.com/" --ustvnow-username xxxxx@xxx.xx --ustvnow-password xxxx --ustvnow-station-code whtm --default-stream best
[console][info] Found matching plugin ustvnow for URL http://watch.ustvnow.com/
[console][info] Available streams: 270p (worst, best)
[console][info] Opening stream: 270p (hls)
[console][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[console][info] Player closed
[console][info] Stream ended
[console][info] Closing currently open stream...
```

```
C:\Users\Ordval>call streamlink.exe "http://watch.ustvnow.com/" 720p --ustvnow-username xxxxx@xxx.xx --ustvnow-password xxxx --ustvnow-station-code whphd
[console][info] Found matching plugin ustvnow for URL http://watch.ustvnow.com/
error: The specified stream(s) '720p' could not be found.
       Available streams: 270p (worst, best)
```
I usually use “Video Download Helper” to get maximum quality,
We have installed Streamlink to different directories, does that play any role ? 
I just let S. install itself where it wants to, doing it: uninstall, reinstall.

@**aykuter** Do you have a paid for subscription ?

**Comment by bastimeyer** [comment]
You have to enter a title and edit the template in order to be able to submit an issue.

**Comment by Ordval** [comment]
Embarrassing.  Could you see my awkward mistake with the title ? 
Seems perhaps **aykuter** have rectified this topic's problem 
so I'll have to wait and see if **beardypig**  still want the, I suppose, Bug report.

**Comment by beardypig** [comment]
@Ordval better to file a report, otherwise you’re issue will get lost :)

**Comment by beardypig** [comment]
Only some streams are available at 720p, and some channels you need to subscribe. From what I saw (don’t have a subscription) I could only get pretty low quality streams.

**Comment by aykuter** [comment]
@Ordval I created my account 1 week ago and it's free not paid.  
@beardypig I tried this script too with my free account. It's creating m3u8 file but i can't watch it with vlc player. Owner of script says : 

> USTVnow blocks the default VLC user-agent string

So when i try to watch it with another m3u8 player it's working perfectly on 720p quality without any freeze problem. I don't have much experience but streamlink's problem will be user-agent for ustvnow script.

**Comment by Ordval** [comment]
@**aykuter** 
Most likely your account will change to lower quality's after a month or so. 
Now I suspect, you can use all of their channels ?

**Comment by aykuter** [comment]
@Ordval Nope i only have 6 channels available. I will create new account after a month it's no big deal for me.

**Comment by Ordval** [comment]
Do you use a new e-mail address each time ?

**Comment by Ordval** [comment]
What is the station code for ABC ? 
`Invalid station-code: wgal`

**Comment by beardypig** [comment]
Here is what I get...

```text
"ABC" = whtm
"CBS" = whphd
"CW" = wlyh
"FOX" = wpmt
"My9" = whvl
"PBS" = wpsu
"Paramount Network" = spiketv
"AMC" = amchd
"Animal Planet" = animalplanet
"BBCA" = bbca
"Bravo" = bravo
"Comedy Central" = comedycentral
"Discovery Channel" = discovery
"ESPN2" = espntwo
"Fox News Channel" = foxnews
"Freeform" = frfrm
"FX" = fxhd
"National Geographic Channel" = natgeo
"Nickelodeon" = nickelodeon
"SundanceTV" = sndnc
"Syfy" = syfy
"The Learning Channel" = tlchd
"USA" = usahd
```

**Comment by Ordval** [comment]
You truly go out of your way to do it even more profound, Thank you, 
but I was quite tired when I wrote my question.  
“wgal” should of course have referred to NBC as it says on its URL 
[http://m.ustvnow.com/images/WGAL.png]. 

I can get a quality 4 stream with V. D. H. as I wrote higher up, 
(just alter the now1) so shouldn't there be a station code here to ?

**Comment by beardypig** [comment]
@Ordval these are the codes I see with my free account (over 2 years old) ... not sure if there are more that I don't see :)

**Comment by Ordval** [comment]
Try open it plainly in your browser.

**Comment by Ordval** [comment]
No, try opening NBC just by clicking on either its icon or allowed TV program item.

**Comment by beardypig** [comment]
I still only get the one stream quality. Maybe you can be more specific and give some more details @Ordval.

**Comment by Ordval** [comment]
My new raised question is (sorry **bastimeyer**): 
What is NBC's  station code, if it won't open with `wgal` through the Plug-In ?
Because as you could see, it would open with a free account in the Browser, right ?

(You can lose the quality issue unless you want to make the Plug-In add any change(-s) 
to the quality like **d3n1s** did with his “USTVNow” app. 
Today his gone Pay-for, but if he still would have supported it freely, 
we could have received a stream, that in its first part could look like this:
`http://ilvc05.ec.ustvnow.com/ilv01/mp4:67F85WGALUSTVNOW4/chunklist.m3u8?f1a2823da53acb9b9d72...` etc.
observe the `NOW4` part, 
but unless you want to make any such modification, drop that particular subject).

**Comment by beardypig** [comment]
NBC missing looks like a bug. But we don’t want to circumvent their premium content protection - I assume you can only get the HD streams with a subscription?

**Comment by Ordval** [comment]
I would assume the same, but it has become a habit using it.
I mean, there is something strangely monophonic-like with the sound
so I haven't considered it to be the full premium quality even at the 4th level.

@**bastimeyer**  Well, ... aren't I'm being "off topic" ?

**Comment by gravyboat** [comment]
I think we've exhausted all the discussion for this topic and have gone above and beyond in terms of support so I'm going to close it now. We can't get the HD streams since we don't circumvent DRM I don't think there's anything else to discuss on the topic of usage. Thanks for all the assistance @beardypig.

**Comment by beardypig** [comment]
Well, there is a bug here. NBC is missing and should be available :)

**Comment by gravyboat** [comment]
@beardypig Yeah but let's open a new issue for that, this one is getting off-topic.

**Comment by Ordval** [comment]
Thank You  **beardypig** for the new update  !
