### ISSUE TITLE
401 forbidden when on ubuntu

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#1774]
[x] I have read the contribution guidelines und used the search function to find already existing threads.

Description

When I try to restream an iptv channel, a demo link that is supposed to work only on vlc (I setup user agent vlc), then I tried on the shell of my ubuntu server, and I get a 401 client forbidden. While doing the same with the windows run command, it works just fine.

```
streamlink "httpstream://http://xxx.ts" best --http-header "User-Agent=VLC media player - version 0.7.0 Bond - (c) 1996-2003 VideoLAN"-O | /usr/local/bin/ffmpeg -re -i pipe:0 -c:v copy -c:a libfdk_aac -f flv "rtmp://stream.vkuserlive.com:443/live?srv=xxxxx"
(401 Client Error: Unauthorized for url: h
```

Is there anything I can do to use that link from a linux server?

**Comment by beardypig** [comment]
Looks like you don't have a space between `VideoLAN"` and `-O`, linux will read this as part of the User-Agent, where as Windows will not. So, I think if you put in a space it should work.

**Comment by campones** [comment]
Yes I should try to correct this.  Thanks

**Comment by campones** [comment]
Nope, that wasn't the reason.  I guess he banned ip range (datacenter) to use his service..  I m trying from a small swiss vps and it works with the following command

` livestreamer --yes-run-as-root "httpstream://http://xxx:8080/live/xxx/xx/xx.ts" best --http-header "User-Agent=VLC/3.0.3 LibVLC/3.0.3" -O | /usr/local/bin/ffmpeg -re -i pipe:0 -c:v copy -c:a libfdk_aac -f flv "rtmp://xxxx"`

**Comment by campones** [comment]
(I couldn't install streamlink for some odd reason on the vps reason I used livestreamer but this is unrelated)

**Comment by beardypig** [comment]
I will close this, as you seem to have fixed it yourself :)
