### ISSUE TITLE
[Feature Request] Option to play/output audio only from a video stream

### ISSUE THREAD

**Issue by ischmidt20** [streamlink/streamlink#1776]
----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I think a great additional feature would be to add an option to only play the audio track from a given stream. This would be a great option for someone who just wants to listen to say, a sports game, but he's on low bandwidth so he doesn't want to waste it on a video stream that he doesn't need. Of course, we can always use the `worst` option now, but that still requires playing video. Or maybe someone wants to watch a stream in 1080p, but in a different language that's only available with a 480p stream. With audio only, they could play the two side-by-side without wasting the additional resources on playing the video from the lower-quality stream. VLC or ffmpeg always recognizes two distinct streams (audio and video), so that might make it easier to only send the one stream to the player. This could be simply implemented in command line with a parameter like `--audio-only`.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
This would only be possible with a small subset of streams. Most streams have the video and audio muxed together (that is, combined in the same data stream) and to discard one you still need to download both. 

This is changing now though, as streaming providers move towards DASH streams which generally have a separate audio and video track - for these streams (and some HLS streams), it would work quite well. However, it would not be available for every stream.

**Comment by gravyboat** [comment]
@beardypig For the time being I'd say we close this since there's nothing we can do until the stream itself supports it (Twitch is a good example of a site that does support audio only). It's a feature request that is blocked by providers and an individual issue should probably be opened for each item.

**Comment by Ike348** [comment]
@gravyboat @beardypig Fair enough. I forgot that it doesn't really matter that VLC or ffmpeg distinguishes streams when a lot of times all you can do to get any stream is download a segment file that already has both.

**Comment by srd424** [comment]
I have a slightly different need that might be possible already - I'd like to download a BBC live TV stream, but just make the audio available to a client on the network. I'm fine with "wasting" the bandwidth for the video part on the download ... just trying to work out if I can persuade streamlink to remux and throw it away before relaying via http..?
