### ISSUE TITLE
What is the command to parse the live source address?

### ISSUE THREAD

**Issue by lki2019** [streamlink/streamlink#1778]
What is the command to parse the live source address?

For example: I want to parse https://www.douyu.com/520 this live source and export it to local e://1.txt

**Comment by back-to** [comment]
this https://streamlink.github.io/cli.html#cmdoption-stream-url ?

**Comment by lki2019** [comment]
@back-to 
Not。

streamlink --stream-url https://www.douyu.com/nvliu >e:\1.txt

The result of the export is：Available streams: source_http, low (worst), medium, source (best)

This is not what I want

==========================

http://hls3.douyucdn.cn/live/156277rT0JMz7x1A/playlist.m3u8?wsSecret=1aa057a292704da5ed61811cb5d281a8&wsTime=1528758481&ct=app-wp

What I want is the resolved address。。Export the parsed live broadcast source address to e://1.txt

**Comment by back-to** [comment]
you have to provide a quality

`streamlink URL best --stream-url > 1.txt`

you can also use `--json`

`streamlink URL best --json > 1.txt`

**Comment by lki2019** [comment]
I get it, thank
