### ISSUE TITLE
plugins : CanalPlus / CNEWS split

### ISSUE THREAD

**Issue by BZHDeveloper** [streamlink/streamlink#1781]
Hi all.

- I am writing a plugin for cnews, changes in the CanalPlus plugin would be too ugly and complex, so I split plugin and move the CNEWS part in a new plugin.
- Can someone test my work ? https://github.com/BZHDeveloper/streamlink . There seems to be a 403 error with any URL that is supposed to be compatible ( example : http://www.cnews.fr/emission/2018-06-12/toute-lactu-2e-debat-du-12062018-784707 )

**Comment by beardypig** [comment]
Probably best to create a PR for the changes, then we can all directly review/suggest improvements :) Don’t be shy about opening incomplete PRs - you/we can add the WIP tag too.

**Comment by BZHDeveloper** [comment]
ok :)
