### ISSUE TITLE
Twitch closed captions support

### ISSUE THREAD

**Issue by IgelRM** [streamlink/streamlink#1789]
Support for [Twitch closed captions](https://help.twitch.tv/customer/portal/articles/2564215) (subtitles) would be nice.

----

### Checklist

- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

**Comment by beardypig** [comment]
I could only find one stream with closed captions was Twitch Presents showing Doctor Who. The closed captions are muxed in to the stream and are picked up by mpv. 

Did you have a counter example where the closed captions do not work?

**Comment by back-to** [comment]
works also with vlc, you will have to **enable it manually** or with player args automatically

> Live

```
streamlink https://www.twitch.tv/twitch -p 'vlc --sub-track 0'
streamlink https://www.twitch.tv/twitch -p 'mpv --sub-create-cc-track=yes'
```

> VODs

```
streamlink https://www.twitch.tv/videos/272158978 -p 'vlc --sub-track 0' --hls-start-offset 00:56:00
streamlink https://www.twitch.tv/videos/272158978 -p 'mpv --sub-create-cc-track=yes' --hls-start-offset 00:56:00
```

**Comment by IgelRM** [comment]
Thanks for the helpful information.

It seems I didn't wait long enough for subtitles to appear when I went through the different subtitle channels that are selectable in VLC 3.0.3 64-bit for Windows (The first in the list is also the third channel which doesn't contain anything for some reason). 

There is no information about subtitles in the documentation.

This is the command I used (needed to specify the full path):
`C:\Program Files (x86)\Streamlink\bin>streamlink --player "C:\Program Files\Vide
oLAN\VLC\vlc.exe --sub-track 0" twitch.tv/twitch best`

**Comment by philiprenich** [comment]
Is this still working? Using streamlink on [this live stream](https://www.twitch.tv/criticalrole), both with and without `--mux-subtitles`, no subtitles tracks seem to exist when selecting them in VLC.

I'm using `-o` to stream to a file rather than directly in to the player if that makes a difference

**Comment by gravyboat** [comment]
`--mux-subtitles` doesn't work with Twitch: https://streamlink.github.io/cli.html?highlight=subtitle#cmdoption-mux-subtitles. I don't use VLC but with MPV `streamlink twitch.tv/criticalrole --player-args "--sub-create-cc-track=yes"` works fine with the Twitch stream you noted.

**Comment by philiprenich** [comment]
@gravyboat Yeah, I didn't think so, but was hoping the docs were just outdated after seeing this thread :) 
I'll play around a little bit more when I get some time and a stream with subs, but since I'm saving the stream direct to a file instead of sending it to a player, I'm not sure it will work. Unless that command you used above works with `-o` and no `--player` specified?
Thanks for the help

**Comment by gravyboat** [comment]
`-o` bypasses the player so you're correct it won't work. Looks like VLC does have some [sort of option to save the output from the player](https://wiki.videolan.org/Documentation:Streaming_HowTo/Receive_and_Save_a_Stream/#Save_a_stream_with_VLC) but I have no idea if this works.

**Comment by philiprenich** [comment]
I'll take a look at that. Hopefully the extra step doesn't take a lot of processing.

Is adding `--mux-subtitles` a future possibility for Twitch since the data exists within the stream and can be passed to players?

**Comment by gravyboat** [comment]
I don't know. I have no familiarity with how `--mux-subtitles` works.

**Comment by bastimeyer** [comment]
`--mux-subtitles` is used for *muxing an external subtitle track* into the output stream container which usually only contains a video and audio stream. Some sites optionally provide external subtitle tracks which this is used for.

On Twitch, subtitles are always muxed into the MPEG-TS stream if they exist.
https://help.twitch.tv/s/article/guide-to-closed-captions?language=en_US

Since Streamlink doesn't touch any of the HLS stream data and only concatenates the segments according to the spec, there is nothing the user needs to do as the subtitles are already embedded in the output.

Here's a random example VOD with subtitles:
https://www.twitch.tv/videos/304219144

If you simply open the stream via streamlink and enable subtitles in your player, eg. MPV, you will see subtitles.
```sh
streamlink -p mpv -v --hls-start-offset 33:00 'https://www.twitch.tv/videos/304219144' best
```
```
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/304219144
[cli][info] Available streams: audio, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[plugins.twitch][info] This is not a low latency stream
[file] Reading from stdin...
 (+) Video --vid=1 (h264 1920x1080 59.940fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
 (+) Video --vid=1 (h264 1920x1080 59.940fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
     Subs  --sid=1 (*) (eia_608)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
Track switched:
 (+) Video --vid=1 (h264 1920x1080 59.940fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
 (+) Subs  --sid=1 (*) (eia_608)

Exiting... (Quit)
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Or you can pass the HLS stream URL to your player to let it fetch and parse the HLS stream on its own via `--player-passthrough=hls` or `--stream-url`.
```sh
mpv "$(streamlink --stream-url 'https://www.twitch.tv/videos/304219144' best)"
```
```
 (+) Video --vid=1 (h264 1920x1080)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
 (+) Video --vid=1 (h264 1920x1080)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
     Subs  --sid=1 (*) (eia_608)
Track switched:
 (+) Video --vid=1 (h264 1920x1080)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
 (+) Subs  --sid=1 (*) (eia_608)

Exiting... (Quit)
```

Or you can analyze Streamlink's output with `ffprobe` and see that there are three streams in the MPEG-TS container:
```sh
streamlink -l none -O 'https://www.twitch.tv/videos/304219144' best \
  | ffprobe -v error -show_format -show_streams -print_format json - \
  | jq
```
```json
{
  "streams": [
    {
      "index": 0,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_tag_string": "[15][0][0][0]",
      "codec_tag": "0x000f",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "id": "0x100",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 4984146341,
      "start_time": "55379.403789",
      "bit_rate": "160093",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "Main",
      "codec_type": "video",
      "codec_tag_string": "[27][0][0][0]",
      "codec_tag": "0x001b",
      "width": 1920,
      "height": 1080,
      "coded_width": 1920,
      "coded_height": 1080,
      "closed_captions": 0,
      "has_b_frames": 1,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "16:9",
      "pix_fmt": "yuv420p",
      "level": 42,
      "chroma_location": "left",
      "field_order": "progressive",
      "refs": 1,
      "is_avc": "false",
      "nal_length_size": "0",
      "id": "0x101",
      "r_frame_rate": "60000/1001",
      "avg_frame_rate": "60000/1001",
      "time_base": "1/90000",
      "start_pts": 4984146700,
      "start_time": "55379.407778",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 2,
      "codec_name": "timed_id3",
      "codec_long_name": "timed ID3 metadata",
      "codec_type": "data",
      "codec_tag_string": "ID3 ",
      "codec_tag": "0x20334449",
      "id": "0x102",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 4984145260,
      "start_time": "55379.391778",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    }
  ],
  "format": {
    "filename": "pipe:",
    "nb_streams": 3,
    "nb_programs": 1,
    "format_name": "mpegts",
    "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
    "start_time": "55379.391778",
    "probe_score": 50
  }
}
```

**Comment by philiprenich** [comment]
My apologies, it does seem to be working. I have 1 file that the player shows no closed captions for, but the others do. I think I just didn't wait long enough for the file with CC to render the next line I thought it wasn't working (if you start in the middle of a line it won't show up until the next part of the CC track).

The VOD you posted works for me, and looking at some of my previously recorded streams do also. Sorry for the run around, but really appreciate the detail and quick responses! <3
