### ISSUE TITLE
Icon/Logo for streamlink

### ISSUE THREAD

**Issue by sbstp** [streamlink/streamlink#179]
We need a logo for the Windows installer and the website.

**Comment by gravyboat** [comment]
Do we own the rights to this guy? https://avatars2.githubusercontent.com/u/22243823?v=3&s=200 It's being used for the main repo right now.

**Comment by sbstp** [comment]
@cdrage might know about it. I'm not the one what picked that logo. Google reverse image search yields only a few results, most being this project.

**Comment by RosadinTV** [comment]
@gravyboat According to this https://www.flickr.com/photos/phploveme/27078045626 uses this type of license: https://creativecommons.org/licenses/by-sa/2.0/

**Comment by gravyboat** [comment]
@RosadinTV Good find, I think we should be alright as long as we give appropriate attribution (and should probably do that anyways since we're using it currently).

**Comment by cdrage** [comment]
@RosadinTV @gravyboat when i searched for it i found it cute as well as 8-pixel to fix the "streaming" vibe. specifically searched for it / used it due to creativecommons license. so all good for using it as an icon :+1: maybe in the future we can commission someone to create a unique logo for us.

**Comment by sbstp** [comment]
Alright, let's use the dog then.

**Comment by gravyboat** [comment]
I'm going to close this out for now. If we want to commission something down the line we can.

**Comment by DragonzMaster** [comment]
Can we use something (icon) relative to what streamlink do , may be like this [Icon ](http://www.flaticon.com/free-icon/streaming_213506)!?

**Comment by cdrage** [comment]
:+1: for doggo

**Comment by RosadinTV** [comment]
@cdrage I love this doggo, really cute.

**Comment by gravyboat** [comment]
Yeah I also like the dog. Seems more memorable to me.

**Comment by DragonzMaster** [comment]
I will compile it and use icon above 😜 And you compile it and use the dog icon, so it is fair 😂

**Comment by RosadinTV** [comment]
@DragonzMaster An easy way to do this is replacing the "Streamlink Logo.ico" file located in "Files\Resources" inside of my release builder.
The result is Streamlink.exe with the custom icon (Works for both Portable and Standalone flavors):
![streamlink_custom_icon](https://cloud.githubusercontent.com/assets/13382316/20502844/ae4eb08c-b01e-11e6-8af1-d9e539ceee6a.JPG)
