### ISSUE TITLE
PyCharm complains of invalid syntax for Python 2.7.15, plugin btsports

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#1793]
### Description

PyCharm complains of invalid syntax for Python 2.7.15, plugin btsports, i.e. super() must have arguments,  [line #38](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/btsports.py#L38)

    def __init__(self, url):
        try:
            super().__init__(url)
        except SyntaxError:  # This is my input for the forked sl implementation on Kodi.
            super(BTSports, self).__init__(url)
        http.headers = {"User-Agent": useragents.FIREFOX}

**Comment by beardypig** [comment]
Yeah, should have the arguments - works in Python 2 and 3.

**Comment by Twilight0** [comment]
My point is that they don't have any arguments now. Can we change that? The except statement I have in the comment is only found in my fork.

**Comment by beardypig** [comment]
Yeah, I’m saying it correct to change it - it’s currently broken. Do you want to open a PR? You don’t need the try..except as with the arguments will work in both python 2/3.

**Comment by Twilight0** [comment]
Done https://github.com/streamlink/streamlink/pull/1796
