### ISSUE TITLE
multiple instances to stdout

### ISSUE THREAD

**Issue by e2pluginss** [streamlink/streamlink#1799]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

trying to pipe multipal streams in to ffmpeg
...

### Expected / Actual behavior
works with 1 instance but when i try to run more than 1 instance i get error

[cli][info] Opening stream: 1200k (hls)
error: Error when writing to output: [Errno 32] Broken pipe, exiting
[cli][info] Stream ended

...

### Reproduction steps / Explicit stream URLs to test

streamlink --player="ffmpeg " http://tvcatchup.com/watch/five best --stdout |./ffmpeg -y  -i pipe:0  -loglevel warning -err_detect ignore_err  -copyts -vsync 0 -correct_ts_overflow 0 -avoid_negative_ts disabled -max_interleave_delta 0 -probesize 5000000 -analyzeduration 5000000 -vcodec copy -scodec copy -acodec copy -individual_header_trailer 0 -f segment -segment_format mpegts -segment_time 10 -segment_list_size 6 -segment_format_options mpegts_flags=+initial_discontinuity:mpegts_copyts=1 -segment_list_type m3u8 -segment_list_flags +delete+live -segment_list /streams/five_.m3u8 /streams/five_%d.ts

streamlink --player="ffmpeg " http://tvcatchup.com/watch/channel4 best --stdout |./ffmpeg -y  -i pipe:0  -loglevel warning -err_detect ignore_err  -copyts -vsync 0 -correct_ts_overflow 0 -avoid_negative_ts disabled -max_interleave_delta 0 -probesize 5000000 -analyzeduration 5000000 -vcodec copy -scodec copy -acodec copy -individual_header_trailer 0 -f segment -segment_format mpegts -segment_time 10 -segment_list_size 6 -segment_format_options mpegts_flags=+initial_discontinuity:mpegts_copyts=1 -segment_list_type m3u8 -segment_list_flags +delete+live -segment_list /streams/channel4_.m3u8 /streams/channel4_%d.ts

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvcatchup for URL http://tvcatchup.com/watch/five
[cli][info] Available streams: 550k (worst), 900k, 1200k (best)
[cli][info] Opening stream: 1200k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1090584; Last Sequence: 1090586
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1090584; End Sequence: None
[stream.hls][debug] Adding segment 1090584 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1090585 to queue
[stream.hls][debug] Adding segment 1090586 to queue
[stream.hls][debug] Download of segment 1090584 complete
[cli][debug] Writing stream to output
error: Error when writing to output: [Errno 32] Broken pipe, exiting
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 1090585 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Comments, screenshots, etc.

I can get 1 instance working but second fails with pipe error
...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Can you do two instances without `ffmpeg`?
```
streamlink http://tvcatchup.com/watch/five best --stdout > /dev/null
streamlink http://tvcatchup.com/watch/channel4 best --stdout > /dev/null
```

Which version of `ffmpeg` are you using?

**Comment by e2pluginss** [comment]
yes this works

**Comment by beardypig** [comment]
What about piping it to a simple ffmpeg invocation, `ffmpeg -y -i pipe:0 -f mpegts /dev/null` for example - I cannot replicate this issue.

**Comment by bastimeyer** [comment]
The issue here is that ffmpeg is stopping due to invalid arguments and not because of a Streamlink related issue (see `[Errno 32] Broken pipe, exiting`). If the second process of the pipe fails, so does Streamlink.

This also looks like a re-broadcast/distribution of the streams stolen from tvcatchup.com on a private server (being run as root) which then get published via HLS (https://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment). We don't want to support anyone using Streamlink for this kind of activity, as it's not the intended usage of Streamlink.

@gravyboat Do you know if tvcatchup is even a legit site and whether this plugin falls into the category of "already added, don't want to remove it for now"? Btw, I was contacted via email today by someone who wanted to pay me for private support of this plugin, because my GitHub profile is showing my public email address. Maybe someone else was contacted as well, don't know. Anyway, this looks like it's related to that (same plugin, same channel, same environment and still a non-up2date Streamlink version).

**Comment by beardypig** [comment]
I think tvcatchup is legit :) I also think this is a perfectly valid use case for ffmpeg on an e2 box. 

@e2pluginss double check your ffmpeg command :)

**Comment by bastimeyer** [comment]
I don't know what an e2 box is, but we've got similar questions in the past and every time I receive those mails from people trying to pay for something they don't want to discuss publicly, it just sounds fishy, you know.

**Comment by beardypig** [comment]
@e2pluginss you might want to look at the [LiveProxy](https://github.com/back-to/liveproxy) project from @back-to as well.

**Comment by e2pluginss** [comment]
Was just looking for some tuitions as i didn't think this was a software issue and im quite a noob at this stuff, so didn't think it was appropriate to use the issue tracker

**Comment by back-to** [comment]
This is **not a streamlink issue**,
your **ffmpeg** script has an error.

**ffmpeg forums**
https://www.ffmpeg.org/contact.html#Forums

closing
