### ISSUE TITLE
--player-external-http only supports one connection

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#180]
This is just a way to more efficiently track the note here: https://github.com/streamlink/streamlink/issues/133#issuecomment-258727205 so we can eventually add support for this.

**Comment by beardypig** [comment]
It should be noted that some container formats are not designed to be streamed in that way. MP4 requires some header data (moov box) to establish which tracks there are, etc. FLV is similar and has some metadata at the front of the file. MPEG(2)-TS is the only container that I can think of off the top of my head that might work, but you'd probably have issues with TS continuity.

**Comment by gravyboat** [comment]
Yeah I saw your note from the other issue but I didn't want to let this slip through the cracks if it works for some players. We'll just have to note that most players don't work and we aren't going to troubleshoot it for people if we do add this feature.

**Comment by beardypig** [comment]
I suppose it depends how it should work, does each client of the http server start a new connection to the stream or should additional clients get the existing stream? The former would work, but would download the stream twice. The latter, might be tricky...

**Comment by gcormier** [comment]
Just wanted to add some feedback - for me one of the biggest usecases would be for audio-only broadcasts. So one server could pull down the appropriate data and stream audio to multiple clients. Would this be a simple enough use-case to start with?

**Comment by gravyboat** [comment]
@gcormier I'm just curious but in what instance would you use this? Does it not work if you combine it with the `audio_only` stream quality? I'm at work so I can't try it right now.

**Comment by gcormier** [comment]
@gravyboat My use case would be for audio streaming a cast in audio only to my phone to reduce bandwidth needs. So PC at home runs streamlink, and my cell tunes in to the stream, pointing at the IP of my home computer.

**Comment by gravyboat** [comment]
@gcormier Gotcha.

**Comment by WolfganP** [comment]
If multi-client native support involves much effort, maybe optimizing Streamlink output for **ffserver** (https://trac.ffmpeg.org/wiki/ffserver , already installed with ffmpeg package) or something like **OpenVCX** (http://openvcx.com/vsxformats.php) may be a simpler solution? (it may be that no development is actually needed, just testing and proper documentation)

**Comment by gcormier** [comment]
![image](https://user-images.githubusercontent.com/8388983/28935873-debaa99e-7853-11e7-949d-0c5b2ec209b9.png)

:/

**Comment by beardypig** [comment]
You can also use `vlc` to transcode/retransmit. I think that a multi-client server is out of scope for this project, there are other tools that will handle it better that can use streamlink as an input. 
Perhaps we can create a section in the docs for "recipes" as a place to include snippets to do this kind of thing. I remember an issue a while back about bringing a streamlink stream in to OpenCV - would be nice to keep those little tidbits around :-)

**Comment by gcormier** [comment]
@beardypig Interesting.. I'll do some fiddling. I'm basically interested in hosting an audio server for the community for DOTA2 TI2017 going on at the moment.

**Comment by mjevans** [comment]
I accidentally posted this on #133 

ffmpeg's tee pseudo-muxer seems to be broken... HOWEVER this seems to do what I want:

streamlink -O ... | \\
        ffmpeg \\
        -i - \\
        -bsf:a aac_adtstoasc \\
        -map 0:0 -map 0:1 \\
        -c:a copy -c:v copy \\
        -c copy rip-$(date +%Y%m%d-%H%M%S).mkv \\
        -y -f mpegts -c copy - | \\
        mpv --cache=64 -

The reason for using numeric IDs in the map is that matroska files don't seem to support saving a timed ID3 stream XD.

mpegts might not be the best output format, but none of the others that are listed in the ffmpeg documentation (that looked remotely fitting anyway) actually worked.

-y is an artifact from when I was using /dev/stdout as the output... but it should be harmless.

-c can be invoked a seemingly unlimited number of times, each output is it's own muxing stage; from ffmpegs output, -c is actually some syntax sugar for a more complex filtergraph that's duplicating the inputs and assigning outputs to many files.

**Comment by WolfganP** [comment]
Thanks @mjevans. Reading @beardypig's vlc suggestion in https://github.com/streamlink/streamlink/issues/133#issuecomment-258790669 it seems your cmd line is just optimized for a pipe to a player (mpv in your case) and not for http serving multiple clients, or is there any way to use ffmpeg as the suggested vlc command?

`streamlink <stream_url> best -p "vlc -I dummy stream:///dev/stdin -vvv --http-port 8080 --sout '#standard{access=http,mux=ts}'"`

**Comment by back-to** [comment]
There are some examples above,
but Streamlink shouldn't be there for more than one connection.
