### ISSUE TITLE
No streams found for newest CR episodes that are only available to premium users

### ISSUE THREAD

**Issue by Orsidus** [streamlink/streamlink#1808]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
I'm not sure if its fair to call this a bug as it might be an issue on Crunchyroll's end either purposeful or not. I'm not able to watch the latest episode in a series if it's only available to premium users using Streamlink, even logged in as a premium user as there are no streams available according to Streamlink.

error: No playable streams found on this URL: http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957

I can't find any recent issues that match this behaviour and I used to be able to play the latest episode with Streamlink though the last time I used Streamlink was about a month or so ago for new episodes I've mainly been rewatching older shows.

URL Tested with http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
Tested watching other URLs which are not exclusive to premium users and they work fine.

...

### Expected / Actual behavior
A stream should be found and playable using Streamlink as there is no CR related issues open at present.
...

### Reproduction steps / Explicit stream URLs to test

1. Grab a URL (E.G http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957) for a new episode which is only available to premium users at present.
2. Use URL with Streamlink as usual.

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
[console][debug] OS:         Windows 10
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
[console][debug] Plugin specific arguments:
[console][debug]  --crunchyroll-username=howdlej (username)
[console][debug]  --crunchyroll-password=******** (password)
[plugin.crunchyroll][debug] Creating session with locale: en_GB
[plugin.crunchyroll][debug] Session created
[plugin.crunchyroll][debug] Using saved credentials
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
error: No playable streams found on this URL: http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
```

### Comments, screenshots, etc.

If this is a known issue and something CR is doing specifically to counter Streamlink then please feel free to delete or mark as closed but I couldn't see anything about this specific issue or any other related CR issues.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I will take a look. Are you in the correct region? It’s not a geoblocked episode is it?

**Comment by Orsidus** [comment]
Nope, I'm able to watch it fine through the website.

**Comment by gravyboat** [comment]
We've had this happen in the past @beardypig: https://github.com/streamlink/streamlink/issues/1014. @Orsidus Can you try this: `streamlink --crunchyroll-purge-credentials --crunchyroll-username=USER --crunchyroll-password=PASSWORD http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best`

**Comment by Orsidus** [comment]
Excluding the initial line for password reasons.

```
[console][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.crunchyroll][warning] Session ID does not match account, resetting session ID
[plugin.crunchyroll][info] Successfully logged in as 'howdlej'
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
error: No playable streams found on this URL: http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
```

**Comment by Orsidus** [comment]
@gravyboat Don't take this personally, but unfortunately I don't feel comfortable doing that. However, my suspicion of it being directly linked to the fact the episode is currently not available to free users yet and only to premium users. The issue you referred to earlier the person claimed it said it was working over 2 weeks later than when he made his post.

Episodes on CR switch from being premium to free after 1 week.  I've tried a number of currently premium-only episodes on CR and not a single one is playing. I will check Food Wars Episode 22 tomorrow after the new episode comes to see if it plays and that should confirm that its linked directly to that.

URLs Tested:
http://www.crunchyroll.com/darling-in-the-franxx/episode-21-for-you-my-love-769615
http://www.crunchyroll.com/boruto-naruto-next-generations/episode-62-the-otsutsuki-invasion-765641
http://www.crunchyroll.com/food-wars-shokugeki-no-soma/episode-22-to-the-final-battleground-769065 (This episode specifically is listed as becoming free tomorrow (Jun 17th))
http://www.crunchyroll.com/megalobox/episode-11-a-deadmarch-768819

**Comment by back-to** [comment]
you could try to change your locale settings with `--locale en_US`
https://streamlink.github.io/cli.html#cmdoption-locale

but reset your session with `--crunchyroll-purge-credentials`

maybe it changes something.

**Comment by Orsidus** [comment]
```
streamlink --crunchyroll-purge-credentials --locale en_US --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best
```

Same result.

**Comment by beardypig** [comment]
Seems like a similar issue to #1574. @Orsidus, do you have an Android smart phone? If so, could you test out the Android App and see if those premium streams play?

**Comment by Orsidus** [comment]
@beardypig The error I get only ever gets is "No playable streams found on this URL". To update, the link for Food Wars Episode 22 now works but the rest do not as predicted. I have an android phone and just tested that all episodes linked earlier work on the android app.

**Comment by beardypig** [comment]
Thanks @Orsidus. It believe it is related to the session ID generation - which was the root cause of #1574 :)

**Comment by Orsidus** [comment]
@beardypig Fingers crossed! Thanks for the helped so far, let me know if there's anything else you need testing wise.

**Comment by beardypig** [comment]
@Orsidus are you able to test out a new version of the plugin? 

You will have to replace two files [src/streamlink/cache.py](https://raw.githubusercontent.com/beardypig/streamlink/5b519e863d7f383f7f28dd13ab7d6191678dbec2/src/streamlink/cache.py) and [src/streamlink/plugins/crunchyroll.py](https://raw.githubusercontent.com/beardypig/streamlink/5b519e863d7f383f7f28dd13ab7d6191678dbec2/src/streamlink/plugins/crunchyroll.py), I see you are using Windows so I don't know if it will just work by replacing the files...

**Comment by Orsidus** [comment]
@beardypig I have updated the python files in my Streamlink installation with the ones you linked and I have tested the following command lines:

```
streamlink --crunchyroll-purge-credentials --locale en_US --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best
```

and

```
streamlink --crunchyroll-purge-credentials --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best
```

The first one using --locale en_US now works with all of the premium links though it does spam my console a little with https warnings a few times that's not a big issue.

The second however without the --locale en_US results in the no playable streams found error

**Comment by Orsidus** [comment]
Apologies for the double post. I ran another test using the following command line

```
streamlink --locale en_US --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best
```

and this results in the following python error

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 18, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 999, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 530, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 412, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 396, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 298, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 361, in _create_api
    api.start_session()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 192, in start_session
    session_id = self._api_call("start_session", params, schema=_session_schema)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 168, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

**Comment by beardypig** [comment]
@Orsidus thanks, can you include the debug logs for those? If you are concerned about credentials you can PM me on gitter.im with some private gists.

**Comment by Orsidus** [comment]
Log for the commandline without --crunchyroll-purge-credentials and with --locale en_US:
```
C:\Users\Hayden>streamlink --locale en_US --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best -l debug
[console][debug] OS:         Windows 10
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
[console][debug] Plugin specific arguments:
[console][debug]  --crunchyroll-username=howdlej (username)
[console][debug]  --crunchyroll-password=******** (password)
[plugin.crunchyroll][debug] Creating session with locale: en_US
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 18, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 999, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 530, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 412, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 396, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 298, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 361, in _create_api
    api.start_session()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 192, in start_session
    session_id = self._api_call("start_session", params, schema=_session_schema)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 168, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

Log for with both --crunchyroll-purge-credentials and --locale en_US:
```
streamlink --crunchyroll-purge-credentials --locale en_US --crunchyroll-username=howdlej --crunchyroll-password=<Ommited> http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957 best -l debug
[console][debug] OS:         Windows 10
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/my-hero-academia/episode-49-one-for-all-768957
[console][debug] Plugin specific arguments:
[console][debug]  --crunchyroll-username=howdlej (username)
[console][debug]  --crunchyroll-password=******** (password)
[console][debug]  --crunchyroll-purge-credentials=True (purge_credentials)
[plugin.crunchyroll][debug] Creating session with locale: en_US
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.crunchyroll][debug] Session created with ID: oq6mxp561lrgupko4hz0hu5vdl6ersgj
[plugin.crunchyroll][debug] Attempting to login using username and password
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.crunchyroll][info] Logged in as 'howdlej'
C:\Program Files (x86)\Streamlink\pkgs\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[plugin.crunchyroll][debug] Loading streams from adaptive playlist
[console][info] Available streams: 240p_alt2 (worst), 240p_alt, 240p, 360p_alt2, 360p, 480p_alt2, 480p_alt, 480p, 720p_alt2, 720p, 1080p_alt2, 1080p_alt, 1080p (best)
[console][info] Opening stream: 1080p (hls)
[console][info] Starting player: "C:\Program Files (x86)\MPC-HC\mpc-hc.exe"
```

There seems to be something odd going on, now all of sudden it is also working with --locale en_US but every attempt without purging the credentials first fails with unauthenticated request despite having my credientials in the config and inside the commandline.

**Comment by beardypig** [comment]
I think caching the session ID is the problem, I will remove that. I will also update it so that when using a session ID, no login happens.

**Comment by beardypig** [comment]
@Orsidus can you try again (you'll have to replace both those files): [src/streamlink/plugins/crunchyroll.py](https://raw.githubusercontent.com/beardypig/streamlink/4751c57e8c40dc134fa5c2b9d19e45c328af799d/src/streamlink/plugins/crunchyroll.py) [src/streamlink/cache.py](https://raw.githubusercontent.com/beardypig/streamlink/4751c57e8c40dc134fa5c2b9d19e45c328af799d/src/streamlink/cache.py)

**Comment by Orsidus** [comment]
Sorry for the late reply. Can confirm that any combination of the previously tried command lines is working now for all premium links. There is no longer any errors when attempting to login without purging the credentials and both with and without --locale en_US works.

**Comment by Orsidus** [comment]
I'm going to close this issue as you've seemed to fix the bug and haven't noticed any new bugs since. Feel free to message me should you need anything else.

**Comment by beardypig** [comment]
We'll leave this open until #1820 is closed :)

**Comment by joaohqs** [comment]
it's a problem for those who speak portuguese

**Comment by beardypig** [comment]
@joaohqs if you have a problem with the Crunchyroll plugin, please open a new issue.
