### ISSUE TITLE
Specific streamer can't be played

### ISSUE THREAD

**Issue by confusionx** [streamlink/streamlink#1809]
## Description
I'm trying to streamlink for shroud, who streams on Twitch. When I put his link into my Terminal, this is what pops up: 
I type in: streamlink twitch.tv/shroud
This comes up:
[console][info] Found matching plugin twitch for URL twitch.tv/shroud
error: No playable streams found on this URL: twitch.tv/shroud

When I try it with other streamers, it works, but not with shroud.
Is it that only live streams can be played? I am trying to watch previous streams.

**Comment by back-to** [comment]
> I am trying to watch previous streams.

which stream url?

> I type in: streamlink twitch.tv/shroud

works for me

```
$ streamlink twitch.tv/shroud
[cli][info] Found matching plugin twitch for URL twitch.tv/shroud
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: /usr/bin/mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**could you run**

```
streamlink https://www.twitch.tv/shroud best -l debug
```

**Comment by gravyboat** [comment]
I can't duplicate this either, stream works fine for me.

**Comment by confusionx** [comment]
Thanks, it works now. I guess there was a weird error before or something.
Could I ask how you get to a specific stream of his? I typed in the name, but this pops up: 
$ streamlink twitch.tv/shroud JURASSSIC PAAARRKK
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: PAAARRKK
Could you help me with this, or should I start a new post?

**Comment by back-to** [comment]
you will have to use the url from your browser

https://www.twitch.tv/videos/272865827

```
streamlink https://www.twitch.tv/videos/272865827 best
```

**Comment by confusionx** [comment]
Thank you so much!
