### ISSUE TITLE
eltaott.tv plugin request

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1810]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Taiwan has a TV station called ELTA which also has online streams. One of their streams is (legitimately) free World cup coverage at the following URL: https://eltaott.tv/channel/play/110/6

I was able to pull out the following source from the website as follows:
`https://eltafifa-cds.cdn.hinet.net/live/pool/hamitv-fifa008/hls-ae-tv/hamitv-fifa008-video=1872000-audio_AACL_zho_128000_3132=128000.m3u8?token=SJagsbYSQ9YV2hrqpQr7CA&expires=1529272690`

Punching this into streamlink works without issue, but it naturally won't function without the token and expires element of the request, so it means going in every time to find it - I'd like my staff here to be able to do it a little more easily.

I'm unsure if the station is geo-blocked or not (since I'm in Taiwan), but if someone fancied taking a bash at a plugin for it I would be forever appreciative (and happy to donate again to the cause!)

**Comment by back-to** [comment]
> free World cup coverage

it ended anyways, closing for now.
