### ISSUE TITLE
Error with nos.nl plugin

### ISSUE THREAD

**Issue by RyuzakiKK** [streamlink/streamlink#1811]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
When I try to open a nos.nl live stream this is the output I get:
```
$ streamlink https://nos.nl/livestream/2236311
[cli][info] Found matching plugin nos for URL https://nos.nl/livestream/2236311
error: Unable to open URL: http://www-ipv4.nos.nl/livestream/resolve/ (404 Client Error: Not Found for url: http://www-ipv4.nos.nl/livestream/resolve/)
```

### Expected / Actual behavior
I have a Netherlands IP and I expect to see the stream like in the web browser.

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://nos.nl/livestream/2236311
2. streamlink https://nos.nl/livestream/npo-politiek.html

### Logs
```
[cli][debug] OS:         Linux-4.16.13-2-ARCH-x86_64-with-arch-Arch-Linux
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.13.0+35.g933126d6
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin nos for URL https://nos.nl/livestream/2236311
error: Unable to open URL: http://www-ipv4.nos.nl/livestream/resolve/ (404 Client Error: Not Found for url: http://www-ipv4.nos.nl/livestream/resolve/)
```

**Comment by beardypig** [comment]
@RyuzakiKK you can try out the update plugin from my PR: [nos.py](https://raw.githubusercontent.com/beardypig/streamlink/e217004b4df48b01be79c448f5a94cc6e030adbb/src/streamlink/plugins/nos.py)

**Comment by RyuzakiKK** [comment]
@beardypig I can confirm that with your fix now it works, thanks.
