### ISSUE TITLE
[plugn request] lrt.lt

### ISSUE THREAD

**Issue by for-coursera** [streamlink/streamlink#1812]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would it be possible to add a plugin for the Lithuanian National Television? Video streams are located [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-televizija), [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-kultura) and [here](https://www.lrt.lt/mediateka/tiesiogiai/lrt-lituanica).

Thanks.

**Comment by beardypig** [comment]
You can test out the plugin by downloading and [sideloading](https://streamlink.github.io/cli.html#sideloading-plugins) this file [lrt.py](https://raw.githubusercontent.com/beardypig/streamlink/573e3144025bb73ee73a25fe4a3c316aa367e318/src/streamlink/plugins/lrt.py)

**Comment by for-coursera** [comment]
That was very impressive, @beardypig, thank you so much :).
