### ISSUE TITLE
[plugin request] delfi.lt

### ISSUE THREAD

**Issue by for-coursera** [streamlink/streamlink#1815]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

[And just one more, please... :)] 

Would it be possible to add a plugin for the [Delfi](https://en.wikipedia.org/wiki/Delfi_(web_portal)) web portal? Video streams' examples can be found [here](http://www.delfi.lt/video/sportas/kroatiska-tvarka-kaliningrade-laisvai-liejosi-gerimai-dainos-sokiai-ir-ziezirbos.d?id=78322857), [here](https://www.delfi.lt/video/sportas/zalgiris-atsidure-per-pergale-nuo-lkl-aukso.d?id=78321125), and [here](https://www.delfi.lt/video/laidos/nba/warriors-cempioniskomis-tapusios-ketvirtos-finalo-rungtynes.d?id=78246059).

Thank you in advance :).

**Comment by beardypig** [comment]
We'll leave this open until #1817 is merged.
