### ISSUE TITLE
Streaming in vlc

### ISSUE THREAD

**Issue by pshotsf** [streamlink/streamlink#1818]
### Checklist

- [ ] This is a bug report.
- [x ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Ability to stream in HTTP with vlc

### Expected / Actual behavior

I want to stream the live video i get from streamlink with vlc.but i don't find any way to do so

**Comment by back-to** [comment]
No sure what you really want,
maybe give us some more details.

---

you can select a player with `--player vlc`
https://streamlink.github.io/cli.html#cmdoption-p

**or** 

create a HTTP stream with ` --player-external-http`
https://streamlink.github.io/cli.html#cmdoption-player-external-http

**Comment by pshotsf** [comment]
Ya,it is like the --player-external-http option.But use vlc to start the HTTP stream instead of streamlink

**Comment by back-to** [comment]
I can imagine what you maybe want,
but could you give us more details about the expected behavior.

**The current description is just not enough.**
