### ISSUE TITLE
Plugin(s) subject to DMCA takedown notice

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1819]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I was saddened to read after catching up on the latest streamlink issues that a certain plugin has been removed due to a DMCA notice. I do however totally understand and agree with the developers' decision to avoid a major legal headache and comply with the notice.

My query is, would anyone be interested in maintaining the plugin in a separate code repo...?

I'm sure we all know which plugin I refer to, and it was the most life-saving plugin for me ever!

I understand the most recent version is still freely available in the v10 branch, ready to forked and picked up if anyone chose to do so... again, happy to donate to the cause if anyone needs it!

**Comment by beardypig** [comment]
If that plugin still works you can [sideload](https://streamlink.github.io/cli.html#sideloading-plugins) it in to the latest version of Streamlink. 

If it doesn't work, and anyone wants to fix it they can. However, do not link to it on the issue tracker.

**Comment by ryanjgillies** [comment]
@beardypig the current plugin isn't working for me when sideloading, but given the DMCA notice I didn't want to tempt fate by mentioning the name of it or asking for suggestions on how to fix it!

Alternatively if someone else were to sideload and test it, and then feedback whether or not it works for them, I could at least know if its an issue local to me or a problem with the plugin itself.

**Comment by gravyboat** [comment]
@ryanjgillies I'd rather not discuss circumventing a DMCA notice by suggesting someone else work on it so I'm going to close and lock this. I really don't feel like dealing with anything else related to that plugin, and I don't want to give them any sort of ammunition against us by saying we are trying to circumvent.
