### ISSUE TITLE
vrt.nu plugin: doesnt works anymore

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#1821]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
vrt.nu (Belgian Flemish television) plugin doesnt works anymore

### Expected / Actual behavior
is there a way to fix this issue ?

### Reproduction steps / Explicit stream URLs to test
1.  type command in terminal: `streamlink https://www.vrt.be/vrtnu/kanalen/een/ best`

### Logs
https://paste.ubuntu.com/p/PcTCH29Pq7/

### Environment details
  - OS                    : Ubuntu 18.04 bionic 32bits
  - Python version : 3.6.5
  - Streamlink        : 0.13.0

**Comment by beardypig** [comment]
@uNouss I have created a PR to fix this issue. 

In the meantime, you can test it out by [sideloading](https://streamlink.github.io/cli.html#sideloading-plugins) the [vrtbe.py](https://raw.githubusercontent.com/beardypig/streamlink/e70053511331db579e4adde085ebf049d34e4ecf/src/streamlink/plugins/vrtbe.py) plugin file.
