### ISSUE TITLE
RTS and TVC

### ISSUE THREAD

**Issue by kenichi512** [streamlink/streamlink#1825]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

I'm requesting a plugin for cloudfront.net

its streamed it serves a generated .m3u8 (for 30ish seconds) along with its 1ish second chunk every second or so

Sites that use this server to stream:
http://www.rts.com.ec/envivo
http://www.tvc.com.ec/envivo

XHR:
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/playlist.m3u8
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/media-u5wu5zzkr_b899152_3340.ts
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/media-u5wu5zzkr_b899152_3341.ts
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/media-u5wu5zzkr_b899152_3342.ts
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/media-u5wu5zzkr_b899152_3343.ts

These links were captured with IDM:
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/chunklist_b899152.m3u8 (360p)
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/chunklist_b249152.m3u8 (160p)
http://d36zvzlneynve1.cloudfront.net/liverts/smil:liverts.smil/chunklist_b1073152.m3u8 (480p)

A look at the .m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=899152,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=640x360
chunklist_b899152.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=249152,CODECS="avc1.66.21,mp4a.40.2",RESOLUTION=284x160
chunklist_b249152.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1073152,CODECS="avc1.77.32,mp4a.40.2",RESOLUTION=854x480
chunklist_b1073152.m3u8
```
When I tried to download the stream, usually Streamlink says "Error 403", but other times Streamlink says it does not have the plugin.

**Comment by beardypig** [comment]
You want plugins for http://www.rts.com.ec/envivo and http://www.tvc.com.ec/envivo? Rather than cloudfront, cloudfront is just the CDN they use.

**Comment by kenichi512** [comment]
I would like it to work for both sites. But what would happen if would there be more sites that also use cloudfront for their streams? For example these two web pages

http://www.elnueve.com.ar/envivo
http://www.repretel.com/envivo

There are other sites that are part of the same international network (Albavisión) and they use the same server, but have geoblocking.

**Comment by beardypig** [comment]
So, you want a plugin for all the Albavisión sites? :)

**Comment by kenichi512** [comment]
I'm interested in RTS and TVC :)

I just set the example other similar streams that are from other countries in case someone could be useful in the future.

**Comment by kenichi512** [comment]
I guess nobody has worked on the plugin yet

**Comment by bastimeyer** [comment]
Streamlink is an open source software project. You and anyone else can work on this. This is a community effort. Simply requesting a plugin (and asking for it again) doesn't mean that it'll be added.
