### ISSUE TITLE
Kodi add-on dead?

### ISSUE THREAD

**Issue by gitfamhub** [streamlink/streamlink#1828]
https://github.com/beardypig/plugin.video.streamlink

Hasn't been updated since May 2017, which means Ustream support is probably broken (and that's what I'd like to use it on). Also I'm having the same issues installing it as someone else in the issues, but they've gotten no reply. Any word on what's going on with it?

**Comment by Twilight0** [comment]
First of all here you can ask support only for the Streamlink cli utility/library, not other software.
@beardypig has enough burden maintaining streamlink itself along with a couple of other developers, wouldn't it be a pain to maintain yet another one?
I took the liberty to package streamlink into a module myself by removing some dependencies [like pycountry](https://github.com/Twilight0/script.module.streamlink.base).
I have a tester addon which is also capable of playing MPEG-DASH: [plugin.video.streamlink-tester](https://github.com/Twilight0/plugin.video.streamlink-tester)

**Comment by gitfamhub** [comment]
Thank you, sorry, just wanted to know if it was still maintained, no pressure! Thanks for all your hard work.

**Comment by beardypig** [comment]
I don't have a Kodi box at the moment, so no real motivation to maintain it I'm afraid. 

@back-to also maintains a version of `streamlink` for Kodi (but Leia only, I think), as well as another plugin ([liveproxy](https://liveproxy.github.io/) which has some cool features for using `streamlink` in Kodi.
