### ISSUE TITLE
br omini vista app alot of latino request for plugin

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1830]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by maanich** [comment]
a request for the app it has alot for everyone

**Comment by gravyboat** [comment]
There's not enough detail in this issue for us to do anything with, it's basically blank minus the title. What's the website that you're looking to see supported? I Googled the title and don't see anything useful.

**Comment by maanich** [comment]
https://www.google.co.uk/url?sa=t&source=web&rct=j&url=https://www.azforum.com.br/2018/04/novo-aplicativos-cinebox-omni-vista-e.html%3Fm%3D1&ved=2ahUKEwiF5IeZu-PbAhXUasAKHYvkDm4QFjAAegQIAhAB&usg=AOvVaw1m4cG4t5Q2KvRSAaX6PZrz


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Forrest <notifications@github.com> Date: 21/06/2018  00:19  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] br omini vista app alot of latino request for plugin (#1830) 
There's not enough detail in this issue for us to do anything with, it's basically blank minus the title. What's the website that you're looking to see supported? I Googled the title and don't see anything useful.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-398927380","url":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-398927380","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gravyboat in #1830: There's not enough detail in this issue for us to do anything with, it's basically blank minus the title. What's the website that you're looking to see supported? I Googled the title and don't see anything useful."}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-398927380"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] br omini vista app alot of latino request for plugin (#1830)",
"sections": [
{
"text": "",
"activityTitle": "**Forrest**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gravyboat",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1830,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1830\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1830#issuecomment-398927380"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 348125541\n}"
}
],
"themeColor": "26292E"
}

**Comment by maanich** [comment]
here is the android app for cinebox omnivista
https://www.google.co.uk/url?sa=t&source=web&rct=j&url=https://www.azforum.com.br/2018/04/novo-aplicativos-cinebox-omni-vista-e.html%3Fm%3D1&ved=2ahUKEwiF5IeZu-PbAhXUasAKHYvkDm4QFjAAegQIAhAB&usg=AOvVaw1m4cG4t5Q2KvRSAaX6PZrz

**Comment by gravyboat** [comment]
We don't support streaming from apps. If there is a website you can go to in your browser where you can access the streams we'll take a look at it, but otherwise this is out of scope.

**Comment by maanich** [comment]
Thanks dear there is mjunoon.tvgoonj.pk live webstreams

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Forrest <notifications@github.com> Date: 21/06/2018  19:56  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] br omini vista app alot of latino request for plugin (#1830) 
We don't support streaming from apps. If there is a website you can go to in your browser where you can access the streams we'll take a look at it, but otherwise this is out of scope.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-399207930","url":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-399207930","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gravyboat in #1830: We don't support streaming from apps. If there is a website you can go to in your browser where you can access the streams we'll take a look at it, but otherwise this is out of scope."}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1830#issuecomment-399207930"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] br omini vista app alot of latino request for plugin (#1830)",
"sections": [
{
"text": "",
"activityTitle": "**Forrest**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gravyboat",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1830,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1830\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1830#issuecomment-399207930"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 348125541\n}"
}
],
"themeColor": "26292E"
}

**Comment by gravyboat** [comment]
Closing as https://github.com/streamlink/streamlink/issues/1834 has been opened.
