### ISSUE TITLE
Python 3.6: DeprecationWarning: inspect.getargspec() is deprecated

### ISSUE THREAD

**Issue by amurzeau** [streamlink/streamlink#1831]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Running tests with python 3.6 triggers a deprecation warning on inspect.getargspec().
I'm not sure there are better way to handle this and still support python 2.7 though.

Maybe waiting this function to be removed or removal of python 2.7 support in streamlink is enough.

```
.pybuild/cpython3_3.6/build/tests/test_log.py::TestDeprecatedLogger::test_deprecated_session_logger
  /<<BUILDDIR>>/streamlink-0.13.0+dfsg/.pybuild/cpython3_3.6/build/streamlink/packages/flashmedia/types.py:1051: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    amfcls.__members__ = getargspec(amfcls.__init__).args[1:]
  /<<BUILDDIR>>/streamlink-0.13.0+dfsg/.pybuild/cpython3_3.6/build/streamlink/packages/flashmedia/types.py:1051: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    amfcls.__members__ = getargspec(amfcls.__init__).args[1:]
```

### Expected / Actual behavior

No python warning about this while running streamlink tests.

### Reproduction steps / Explicit stream URLs to test

Run `PYTHONPATH=src/ pytest-3 tests` on root directory with python 3.6 installed.

### Logs

See here: https://travis-ci.org/amurzeau/debian-travis/builds/393389349#L2492

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
@amurzeau I've opened a PR that should fix it :)

**Comment by back-to** [comment]
there are also some other warnings

with `python setup.py test` (#1833 streamlink version)

```
test_builtin_plugins (tests.test_session.TestSession)
... src/streamlink/plugin/api/support_plugin.py:34: DeprecationWarning:
Use importlib.util.find_spec() instead.

test_bool_str (tests.streams.test_dash_parser.TestMPDParsers)
... tests/streams/test_dash_parser.py:22: DeprecationWarning:
Please use assertEqual instead.

test_hls_encryted_aes128 (tests.test_hls.TestHLS)
... src/streamlink/session.py:91: DeprecationWarning:
Logger class has been deprecated, use the standard logging module

test_catch_warnings_record (tests.test_meta.TestMeta)
... tests/test_meta.py:30: DeprecationWarning:
Please use assertEqual instead.

test_open_player_extra_args_in_player (tests.test_cmdline.TestCommandLineInvocation) 
... src/streamlink/plugin/api/support_plugin.py:34: DeprecationWarning:
Use importlib.util.find_spec() instead.
```

**Comment by beardypig** [comment]
Which version of Python was that on @back-to?

**Comment by back-to** [comment]
Python 3.6.5

**Comment by beardypig** [comment]
Hmm, that's what I was using for my tests - seems like some of these warnings don't always appear ... maybe it's some option I inadvertently have set...

**Comment by back-to** [comment]
they don't appear with `pytest` only with `python setup.py test`
