### ISSUE TITLE
Vod from bilibili.com

### ISSUE THREAD

**Issue by jiahaoliang** [streamlink/streamlink#1832]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Currently streamlink doesn't have plugin to play vod from bilibili.com

Youtube-dl is able to download video from bilibili.com. Maybe we could borrow the idea how they implemented the [plugin](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/bilibili.py) 

> \# youtube-dl "https://www.bilibili.com/video/av12168252"
> [BiliBili] 12168252: Downloading webpage
> [BiliBili] 12168252: Downloading video info page
> [download] Downloading playlist: 【纪录片/空难】空中浩劫（共116集/中文字幕）
> [BiliBili] playlist 【纪录片/空难】空中浩劫（共116集/中文字幕）: Collected 11 video ids (downloading 11 of them)
> [download] Downloading video 1 of 11
> [download] Destination: 【纪录片_空难】空中浩劫（共116集_中文字幕）-12168252_part1.flv
> [download]  17.8% of 22.46MiB at  2.63MiB/s ETA 00:07
> 

### Expected / Actual behavior

Expected: 
\# streamlink https://www.bilibili.com/video/av12168252 best
(Player starts to play the video)
...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by fozzysec** [comment]
This project focus on streams rather than videos. It has plugin for live.bilibili.com

**Comment by back-to** [comment]
closing,
VOD support is getting reduced in Streamlink and I don't think this will be added in the near future.
