### ISSUE TITLE
plugin rerquest for mjunoon

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1834]
https://www.mjunoon.tv/

streamlink https://www.mjunoon.tv/a-tv-live
[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: https://www.mjunoon.tv/a-tv-live

**Comment by maanich** [comment]
live streeams
https://www.mjunoon.tv/urdu-1-live

https://www.mjunoon.tv/filmazia-live

https://www.mjunoon.tv/aruj-live

and more vod stream

https://www.mjunoon.tv/watch/tonight-with-jasmeen-21june2018-kanwar-dilshad-amjad-shoaib-khawaja-fareed-u913yoexxyg

https://www.mjunoon.tv/watch/tax-aur-aap-ep-28-10-feb-2017-opnbtxuuzxu

anything else required lett me know

**Comment by back-to** [comment]
some details about the website, it looks **legal** to me.

> mjunoon: Powered by Convex Interactive ...
https://www.mjunoon.tv/about-us

> Watch licensed Live TV & Radio channels for Free.
https://play.google.com/store/apps/details?id=com.convex.mjunoon.TV&hl=en_US

> PEMRA (Pakistan Electronic Media Regulatory Authority)
Grants Mobile TV License to Convex Interactive
https://propakistani.pk/2016/04/01/pemra-grants-mobile-tv-license-to-convex-interactive/

**Comment by maanich** [comment]
yeah its hundread percent legal

**Comment by maanich** [comment]
any update on these web streams any hope we get in near future.

**Comment by beardypig** [comment]
@maanich https://github.com/streamlink/streamlink/pull/1857

**Comment by maanich** [comment]
just tested and found this error streams not up with player.

streamlink -l debug https://www.mjunoon.tv/channel-24ive  best --player vlc
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 0.14.0+12.g0cf6ce0
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin mjunoon for URL https://www.mjunoon.tv/channel-24-live
[plugin.mjunoon][debug] Found the playerScript script tag
[cli][info] Available streams: 270p (worst), 480p (best)
[cli][info] Opening stream: 480p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 2220; Last Sequence: 2225
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2223; End Sequence: None
[stream.hls][debug] Adding segment 2223 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2224 to queue
[stream.hls][debug] Adding segment 2225 to queue
[cli][info] Starting player: vlc
[stream.hls][debug] Download of segment 2223 complete
[stream.hls][debug] Download of segment 2224 complete
[stream.hls][debug] Download of segment 2225 complete
[cli][debug] Writing stream to output
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...

**Comment by beardypig** [comment]
Seems to play fine for me with `mpv 0.28.2 (ffmpeg 4.0.1)`, I watched for 3 minutes without problem. With `mpv 0.14.0 (ffmpeg 2.8.14-0ubuntu0.16.04.1)` I get some errors, but it seems to play fine.

**Comment by maanich** [comment]
Thanks  its working actually i was doin it with debug command.  great  work.

**Comment by maanich** [comment]
like neotv  and many others we can fixed to best its pixilating i f any way to fix bitrate.

**Comment by maanich** [comment]
streamlink https://www.mjunoon.tv/neo-tv-live best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin mjunoon for URL https://www.mjunoon.tv/neo-tv-live
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[cli][info] Available streams: 270p (worst), 480p (best)
[cli][info] Opening stream: 480p (hls)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
[cli][info] Closing currently open stream...
how to  verify https cert

**Comment by beardypig** [comment]
@maanich SSL verification is disable for this host, even the latest versions of Python will not verify it. To remove this warning you may need to update `requests` or `urllib3`. Alternatively, you can try 
```
env PYTHONWARNINGS="ignore:Unverified HTTPS request" streamlink mjunoon.tv/neo-tv-live best
```
