### ISSUE TITLE
plugin request poovee net 

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1835]
http://poovee.net/video/140444/ary-digital/

**Comment by bastimeyer** [comment]
This is, once again, a very low effort plugin request from you.
You should at least provide some information about the website and the streams you would like to see being supported. Posting a single link is not enough.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by maanich** [comment]
i think there is a huge data in website n links  if u need more links i will send a list of it. thanks

**Comment by maanich** [comment]
this site has many good original free to air streams related to live pakistan channels and alot of recorded programms to watch. no stolen or restream website.

**Comment by back-to** [comment]
The frontpage of these website has dead streams.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 8 - Sites which are unmaintained.
