### ISSUE TITLE
Can't play live stream with mpv

### ISSUE THREAD

**Issue by exxfzc** [streamlink/streamlink#1836]
os:mac os 12.1
mpv:0.28.2(install with homebrew)
streamlink:0.13.0(install with homebrew)

I didn't install vlc,mpv is useful for me.After installing streamlink,I did not find a configuration file on my
mac.I can't edit the config by myself.
When i want to open the url in the ternimal,show"The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player"

How can i set mpv to the default player?

**Comment by beardypig** [comment]
You can just create the config file at `~/.streamlinkrc` and add a line with `player=mpv` line - it's what I have :)

**Comment by exxfzc** [comment]
Enter ~/.streamlinkrc at the terminal?It show "No such file or directory''

**Comment by exxfzc** [comment]
Enter ~/.streamlinkrc at the terminal?It show "No such file or directory''

**Comment by exxfzc** [comment]
Enter ~/.streamlinkrc at the terminal?It show "No such file or directory''

**Comment by exxfzc** [comment]
Enter ~/.streamlinkrc at the terminal?It show "No such file or directory''

**Comment by exxfzc** [comment]
Enter ~/.streamlinkrc at the terminal?It show "No such file or directory''

**Comment by beardypig** [comment]
@exxfzc try doing this in a terminal
```console
$ touch ~/.streamlinkrc 
$ open -e ~/.streamlinkrc
```

**Comment by exxfzc** [comment]
Thank you very much!!

**Comment by beardypig** [comment]
You're quite welcome.
