### ISSUE TITLE
Update Plugin requests policy

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1837]
**I opened this so it won't go under.**

---

### Description

as discussed in https://github.com/streamlink/streamlink/issues/1763

The **Plugin requests** Guide should be updated with some rules about plugins.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

in https://github.com/streamlink/streamlink/issues/1763 were mentioned

- stolen content
- rehosted content
- NSFW sites

---

## My opinion

> stolen content / rehosted content

---

1. sites which **only focus** on stolen content should **not be added**

**Example:** _just a website with a lot of ads and some rehosted streams_

https://github.com/streamlink/streamlink/issues/603
https://github.com/streamlink/streamlink/issues/1207
https://github.com/streamlink/streamlink/issues/1243

---

2. sites where the **User takes advantage** of the streaming site,
but it's **not** the **main focus** of the website they **could be added**.

**Example:** _a lot of people abuse youtube/twitch for sports streams, there are some other similar sites where this happens._

https://github.com/streamlink/streamlink/issues/701
https://github.com/streamlink/streamlink/issues/1176

---

> VOD in general which I would not add

I for one don't care for vods on smaller websites,

https://github.com/streamlink/streamlink/issues/1321

or if they need a lot of changes in compare to the livestream

https://github.com/streamlink/streamlink/issues/1733

Website with only stolen vod content

https://github.com/streamlink/streamlink/issues/1110

---

And every new plugin request should have a explanation about the website which is requested,
sometimes a simple wikipedia link is enough.

If this is not given, the **plugin request should be closed** or in general if there are not details.

**Comment by gravyboat** [comment]
I like this a lot, I'll take a crack at putting something together this afternoon for consideration. Thanks @back-to.
