### ISSUE TITLE
streamlink not work anymore since i updated it

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#1841]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I have been using streamlink for a while.
I updated it to the latest version this morning and can not launch it anymore.

### Expected / Actual behavior
I wish I could use it again and if this version does not work at home how to go back to an older version.

### Reproduction steps / Explicit stream URLs to test

1. `sudo -H pip3 install --user -U streamlink`
2. `streamlink -p mpv -l debug arte.tv/fr/direct/ best`

### Logs
```python
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/usr/local/lib/python3.6/dist-packages/streamlink_cli/main.py", line 25, in <module>
    from streamlink.stream import StreamProcess
  File "/usr/local/lib/python3.6/dist-packages/streamlink/stream/__init__.py", line 6, in <module>
    from streamlink.stream.hls import HLSStream
  File "/usr/local/lib/python3.6/dist-packages/streamlink/stream/hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "/home/unouss/.local/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 36, in <module>
    from Crypto.Cipher._mode_gcm import _create_gcm_cipher
  File "/home/unouss/.local/lib/python3.6/site-packages/Crypto/Cipher/_mode_gcm.py", line 47, in <module>
    from Crypto.Util import _cpuid
ImportError: dynamic module does not define module export function (PyInit__cpuid)
```
### Comments, screenshots, etc.
[![asciicast](https://asciinema.org/a/zy7Pk0a3PteeLhHqhJVo8z8SP.png)](https://asciinema.org/a/zy7Pk0a3PteeLhHqhJVo8z8SP)

### Environment details
- OS: Ubuntu 18.04 bionic 32bits
- Python version : 3.6.5
- Streamlink : 0.13.0

**Comment by bastimeyer** [comment]
> sudo -H pip3 install --user -U streamlink
> streamlink -p mpv -l debug arte.tv/fr/direct/ best
> File "/usr/local/bin/streamlink", line 7, in <module>

If you're using pip's `--user` parameter, it'll install the module and its dependencies into your home directory, more precisely `$XDG_DATA_HOME`, or if it isn't defined `$HOME/.local`.

If you're simply running `streamlink`, the used shell (eg. bash) will try to resolve executable paths with the same name in one of the directories listed in `$PATH`, which are by default just system-wide paths, like `/usr/bin`, `/usr/local/bin`, etc. This is what is happening here, see the error log message.

So if you're installing anything via pip and are using the `--user` parameter, you have to call the generated executable files from the `~/.local/bin` directory (eg. `~/.local/bin/streamlink`) or add this path to your `$PATH` env variable.

Your system's Streamlink / Python config probably got messed up earlier while installing stuff via pip without using the `--user` param and then updating packages regularly from your distro. It is generally not recommended using pip system-wide, as many Linux distros have the necessary packages available in their repos and using both will result in conflicts sooner or later.

https://streamlink.github.io/install.html

**Comment by uNouss** [comment]
@bastimeyer thank you for answer. It helps me to better understand how it works. I added `~/.local/bin` in my `$PATH` and it works now.

**Comment by bachoo786** [comment]
> @bastimeyer thank you for answer. It helps me to better understand how it works. I added `~/.local/bin` in my `$PATH` and it works now.

Hi @uNouss how did you add `~/.local/bin` in my `$PATH`?

**Comment by bastimeyer** [comment]
https://wiki.archlinux.org/title/Environment_variables#Defining_variables
