### ISSUE TITLE
Question: How to rename the stream name/title when it is passed to VLC

### ISSUE THREAD

**Issue by djkanoko** [streamlink/streamlink#1842]
### Checklist

- [x] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
 Recording a stream in VLC  will use the title/name of the stream in the recorded file's filename which is just "0" when using the default streamlink arguments:
streamlink (stream name) (stream quality)
Is it possible via  command-line arguments in streamlink or VLC to specify what the input stream should be labeled when it is loaded in VLC?  I'd like the stream title/name to  be the same as the stream URL that is used as the first command-line argument to streamlink.

**Comment by bastimeyer** [comment]
> specify what the input stream should be labeled when it is loaded in VLC

- **VLC**
  ```
  streamlink -p vlc -a '--input-title-format "this will be the new VLC window title" {filename}' URL QUALITY
  ```
- **MPV**
  ```
  streamlink -p mpv -a '--title "this will be the new MPV window title" {filename}' URL QUALITY
  ```

Depending on your OS and the parser of the used shell, the quotation marks (single / double) have to be escaped.
https://streamlink.github.io/cli.html#cmdoption-a

If you just want to record the stream, why don't you simply use Streamlink's `--output` parameter?
https://streamlink.github.io/cli.html#file-output-options

**Comment by djkanoko** [comment]
I'm getting an error:
Streamlink.py: error: unrecognized arguments: <the stream URL>

Could you perhaps give a literal example (no text placeholders) with a working twitch link perhaps?

**Comment by djkanoko** [comment]
I'm having trouble getting this to work.  In my case, I don't need to specify the filename, just the tite.  If I try this:
streamlink -p  vlc -a "--input-title-format test1" https://www.twitch.tv/gamesdonequick best
VLC is loaded but no stream is loaded
If I do this:
streamlink -a "--input-title-format test1 {test2}" https://www.twitch.tv/gamesdonequick best
I get the following error:
Traceback (most recent call last):
  File "C:\Portable\streamlink\Streamlink\Streamlink.py", line 7, in <module>
    main()
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\main.py", line 1045, in main
    handle_url()
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\main.py", line 502, in handle_url
    handle_stream(plugin, streams, stream_name)
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\main.py", line 384, in handle_stream
    success = output_stream(stream)
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\main.py", line 262, in output_stream
    output.open()
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\output.py", line 23, in open
    self._open()
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\output.py", line 124, in _open
    self._open_subprocess()
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\output.py", line 139, in _open_subprocess
    self.player = subprocess.Popen(self._create_arguments(),
  File "C:\Portable\streamlink\Streamlink\streamlink_cli\output.py", line 112, in _create_arguments
    args = self.args.format(filename=filename)
KeyError: 'test2'
[End of Streamlink for Windows with ExitCode 1]

**Comment by djkanoko** [comment]
OK, so I used this command-lin string to change the title:
streamlink https://www.twitch.tv/ninja worst -p "C:\Program Files\VideoLAN\VLC\vlc.exe --input-title-format TITLE"
But when I record from  this stream the file is still saved using the "fd://0" identifier.  The title says "TITLE" but under media information the title is still  ilsted as "fd://0".  I think I need to modify a different parameter to get the recorded filename to use it.

**Comment by bastimeyer** [comment]
There are also the `--meta-title` and `--video-title` VLC parameters, maybe you can try one of these.
https://wiki.videolan.org/VLC_command-line_help

But again, if you just want to record, use Streamlink's `--output` / `-o` parameter instead of using VLC:
https://streamlink.github.io/cli.html#file-output-options

The question about viewing and recording at the same time has been answered dozens of times here on this issue tracker. If you want to do that, please use the search function. Other than that, there's also a pull request for making this easier #920.

**Comment by djkanoko** [comment]
Great!  It looks like --meta-title is used in the recorded filename.  However in my case, I found that using --input-record-path worked better for my particular scenario.  

Thanks for your help!
