### ISSUE TITLE
Atresplayer

### ISSUE THREAD

**Issue by DjUnknown** [streamlink/streamlink#1843]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Links Live:
https://www.atresplayer.com/directos/antena3/
https://www.atresplayer.com/directos/lasexta/
https://www.atresplayer.com/directos/neox/
https://www.atresplayer.com/directos/nova/
https://www.atresplayer.com/directos/mega/
https://www.atresplayer.com/directos/atreseries/

```
 streamlink.exe https://www.atresplayer.com/directos/antena3/ best --player ffplay -l debug
 [console][debug] OS:         Windows 7
 [console][debug] Python:     3.5.2
 [console][debug] Streamlink: 0.13.0
 [console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
 error: No plugin can handle URL: https://www.atresplayer.com/directos/antena3/
```

*I have executed the same command with the six links.

Sorry for English, I do not speak it.

**Comment by beardypig** [comment]
Thanks for bug report, there is a fix PR pending.

**Comment by DjUnknown** [comment]
@beardypig
Thanks to you ! ;)

**Comment by DjUnknown** [comment]
Thanks very much beardypig. ;)

Greetings from Spain !!!
