### ISSUE TITLE
Mitele

### ISSUE THREAD

**Issue by DjUnknown** [streamlink/streamlink#1845]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

Channel Energy:
https://www.mitele.es/directo/energy
```
streamlink.exe https://www.mitele.es/directo/energy best --player ffplay -l debug
[console][debug] OS:         Windows 7
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin mitele for URL https://www.mitele.es/directo/energy
error: Unable to validate JSON: Unable to validate key 'locations': Unable to validate key 'ogn': Type of None should be 'str' but is 'NoneType'
```

Channel Be Mad:
https://www.mitele.es/directo/bemad
```
streamlink.exe https://www.mitele.es/directo/bemad best --player ffplay -l debug
[console][debug] OS:         Windows 7
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin mitele for URL https://www.mitele.es/directo/bemad
[plugin.mitele][debug] HLS URL: https://mdslivehls-i.akamaihd.net/hls/live/571646/bemad/master.m3u8?hdnea=st=1529962765~exp=1529962773~acl=/hls/live/571646/bemad/*~hmac=479d365ee94787ee2b8589af0481965e7d9db7b64f221e972e9ae700a4dbc511&ogn=o0t6vboys4gf5myd/zPCDTrD4mngkRY2xpxAy2RZpc8YKMY/OXWaKkIdDCyb1JsI6lgjrjbG62fAz0QlSA7PGYLbDOCkr17OPEswGGPi3Hk=
[console][info] Available streams: 360p (worst), 480p, 720p_alt, 720p (best)
[console][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[console][error] Try 1/1: Could not open stream <HLSStream('https://mdslivehls-i.akamaihd.net/hls/live/571646/bemad/bitrate_3.m3u8')> (Could not open stream: Unable to open URL: https://mdslivehls-i.akamaihd.net/hls/live/571646/bemad/bitrate_3.m3u8 (404 Client Error: Not Found for url: https://mdslivehls-i.akamaihd.net/hls/live/571646/bemad/bitrate_3.m3u8))
error: Could not open stream <HLSStream('https://mdslivehls-i.akamaihd.net/hls/live/571646/bemad/bitrate_3.m3u8')>, tried 1 times, exiting
```

Channel Boing:
https://www.mitele.es/directo/boing
```
streamlink.exe https://www.mitele.es/directo/boing best --player ffplay -l debug
[console][debug] OS:         Windows 7
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[console][info] Found matching plugin mitele for URL https://www.mitele.es/directo/boing
[plugin.mitele][debug] HLS URL: https://mdslivehls-i.akamaihd.net/hls/live/571647/boing/master.m3u8?hdnea=st=1529963719~exp=1529963727~acl=/hls/live/571647/boing/*~hmac=a4496414861bffafc289305413248f581d26478a6a1680dc14b0c0d628ff185a&ogn=o0t6vboys4gf5myd/zPCDTrD4mngkRY2xpxAy2RZpc8YKMY/OXWaKkIdDCyb1JsIKjCZ1AX0ylNLwo7kPa/4h0j6jEXEzzq1zbN69Jz07zU=
[console][info] Available streams: 360p (worst), 480p, 720p_alt, 720p (best)
[console][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[console][error] Try 1/1: Could not open stream <HLSStream('https://mdslivehls-i.akamaihd.net/hls/live/571647/boing/bitrate_3.m3u8')> (Could not open stream: Unable to open URL: https://mdslivehls-i.akamaihd.net/hls/live/571647/boing/bitrate_3.m3u8 (404 Client Error: Not Found for url: https://mdslivehls-i.akamaihd.net/hls/live/571647/boing/bitrate_3.m3u8))
error: Could not open stream <HLSStream('https://mdslivehls-i.akamaihd.net/hls/live/571647/boing/bitrate_3.m3u8')>, tried 1 times, exiting
```

**Comment by Ordval** [comment]
@**DjUnknown** 
For me Energy opens now (with the update) but only with X-F-F. 
If you don't know what that is I'd rather PM you.
(Para mí, Energy abre ahora (con la actualización) pero solo con X-F-F. 
Si no sabe qué es eso, prefiero que le envíe un PM).
(Está en España ? si en ese caso, no se necesita añadir nada).

**Comment by DjUnknown** [comment]
@Ordval 
Vivo en españa, el Be Mad y Boing funciona con la actualización de beardypig pero no el energy, le estaré eternamente agradecido si me dice como lo ha conseguido ver.

**Comment by Ordval** [comment]
> Vivo en españa, el Be Mad y Boing funciona con la actualización de beardypig pero no el energy, le estaré eternamente agradecido si me dice como lo ha conseguido ver.
(I live in Spain, the Be Mad and Boing works with beardypig's update but not the energy one, 
I would be eternally grateful if you'd tell me how you've managed to see it).

Si empieza con estos tres, ¿qué sucede?
(If you'd start with these three, what happens ?)
`call streamlink.exe  --player-passthrough hls --player-continuous- --retry-streams 1 --retry-open 86400 "https://www.mitele.es/directo/energy" best`

`call streamlink.exe  hls://"http://www.radiosargentina.com.ar/php/tvm3u.php?id=DIES0007" best`

`call streamlink.exe  hls://"https://mdslivehlsb-i.akamaihd.net/hls/live/623617/energy/bitrate_4.m3u8" best`
y pruebalos a través de un cmd (Símbolo del sistema?)
(and try them through a cmd [Command prompt])
Volveré mañana por la tarde.
(I'll be back tomorrow afternoon).

**Comment by DjUnknown** [comment]
@Ordval 
Funcionan los tres, el comando "streamlink.exe https://www.mitele.es/directo/energy best --player ffplay" ahora si me funciona.

**Comment by Ordval** [comment]
Genial.

Translating for Moderators and members:
(**DjUnknown**:) All three work, the command "`streamlink.exe https://www.mitele.es/directo/energy best --player ffplay`" also work for me now.
