### ISSUE TITLE
Pipe ffmpeg output to streamlink

### ISSUE THREAD

**Issue by thomasschmiedl** [streamlink/streamlink#1854]
Hello,

I transfer this MPEG-DASH-stream 'https://live.idnes.cz/slow/slowtv7_720p/manifest.mpd' in ffmpeg (output as MP4 in ffmpeg's listen mode) via xupnpd2 media-server (or gerbera as open-source alternative) to my TV. Everything run on a router. I try to overlay the map from [1] as an image [2]. The router is too slow for the ffmpeg's overlay video-filter, because of the re-encoding. My idea is to mux a bitmap-subtitle (e.g. vobsub idx/sub) containing the map-image in ffmpeg without re-encoding.

The ffmpeg listen mode works in VLC on the pc (directly and indirectly via media-server), but not on the TV. I contacted the ffmpeg maliling-list without getting help. My idea is to pipe the ffmpeg's output to streamlink. Is this possible? Then, Streamlink should forward the stream using '--player-external-http' and '--player-external-http-port 1234'.

Thanks and best regards,
Thomas

[1] https://slowtv.playtvak.cz/prave-ted-mazaci-tramvaj-jede-prahou-d73-/mazaci-tramvaj.aspx?c=A150908_111659_mazaci-tramvaj_plap

[2] http://staticmap.openstreetmap.de/staticmap.php?center=50.05619,14.43873&zoom=15&size=865x512&maptype=mapnik&markers=50.05619,14.43873,ol-marker

**Comment by back-to** [comment]
http://www.ffmpeg-archive.org/bitmap-subtitle-in-stream-td4684135.html

> ffmpeg ... to restream a DASH-stream ... to a local
htdocs-folder as HLS on the router ...

They have hls URLs, you can probably skip this
 
your **example** is **dead** but all the other streams have normal **HLS streams**,
just change the URL

`http://` and `master.m3u8`

```
http://live.idnes.cz/slow/slowtv2_720p/master.m3u8
```

---

if your ffmpeg script creates a local file, streamlink could play it. 

https://streamlink.github.io/cli.html#supported-streaming-protocols

```
$ streamlink hls://file://C:/hls/playlist.m3u8
```

---

**but all of this is more of a ffmpeg question**

**Comment by gravyboat** [comment]
Agreed, this question is ffmpeg related, not Streamlink related so I'm going to close this.
