### ISSUE TITLE
Any chance for a plugin for fanat.tv?

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#1861]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Would be grateful if someone could code a plugin for http://fanat.tv. Streams are [like this](http://fanat.tv/channels/france-24-english) or [like this](http://fanat.tv/channels/lyubimoe-kino).

EDIT: just in case, my email is 097115 at gmail dot com :).

**Comment by gravyboat** [comment]
I don't think so. This site is hosting a lot of content that you would get with a cable subscription or would normally need to pay for. I'll leave it open in case anyone else wants to weigh in but there's a lot of questionable content.

**Comment by beardypig** [comment]
I couldn’t find any information to suggest it was legit either.
