### ISSUE TITLE
No playable streams with youtube live streams

### ISSUE THREAD

**Issue by Billy2011** [streamlink/streamlink#1865]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. www.youtube.com/user/euronewsde/live
2. www.youtube.com/user/deutschewelle/live
3. www.youtube.com/user/ROCKETBEANSTV/live

### Logs

streamlink www.youtube.com/user/euronewsde/live best -l debug
[cli][debug] OS:         Windows 8
[cli][debug] Python:     2.7.9
[cli][debug] Streamlink: 0.14.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin youtube for URL www.youtube.com/user/euronewsde/live
error: No playable streams found on this URL: www.youtube.com/user/euronewsde/live

Many thanks for your support

**Comment by mmetak** [comment]
It works just fine if you use the direct links:  

for euronewsde: https://www.youtube.com/watch?v=uEiyA-V9IHM   
for deutschewelle: https://www.youtube.com/watch?v=mEB8WDOOF_4  
etc.

**Comment by beardypig** [comment]
These pages seem to have slightly different layouts. The YouTube plugin is kind of a mess and could do with some major refactoring :)

**Comment by Billy2011** [comment]
Yes, that's why I did not start to fix it :)

**Comment by back-to** [comment]
**1. quick fix**
remove the __/live__ part

**2.**

this part could be used for the streamlink plugin

```py
    'currentVideoEndpoint': {
        'clickTrackingParams': 'XXX=',
        'commandMetadata': {
            'webCommandMetadata': {
                'url': '/watch?v=uEiyA-V9IHM',
                'webPageType': 'WEB_PAGE_TYPE_WATCH'
            }
        },
        'watchEndpoint': {
            'videoId': 'uEiyA-V9IHM'
        }
    },
```

**Comment by beardypig** [comment]
@back-to does **2.** appear on every page with a video (it seems to be)? This could be used for a more concise implementation.

**Comment by back-to** [comment]
idk, only tested for `/live` urls

i would just use it as a fallback if this fails
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L224-L225

---

and maybe the api fallback should be removed completely
**or**
at least the `else:` or it won't work most of the time

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L231-L240

**Comment by beardypig** [comment]
Yeah I was thinking that too when I looked at it again. `currentVideoEndpoint. watchEndpoint.videoId` exists for all the videos I checked, so far.

**Comment by karlo2105** [comment]
It's working to me with this build : `streamlink 0.12.1+8.ge2a5546`

```
streamlink "http://www.youtube.com/user/euronewsde/live" best
[cli][info] Found matching plugin youtube for URL http://www.youtube.com/user/euronewsde/live
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

**Comment by karlo2105** [comment]
OK since I upgraded to latest streamlink build, Youtube this link above doesn't work for me either. 

```
streamlink -l debug "https://www.youtube.com/user/euronewsde/live"
[cli][debug] OS:         Windows 7
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0.14.2+8.g8d20fbcb
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/e
uronewsde/live
error: No playable streams found on this URL: https://www.youtube.com/user/euronewsde/live
```

But this one is working fine : 

```
streamlink -l debug "https://www.youtube.com/user/euronewsde/live?disable_polymer=1" best
[cli][debug] OS:         Windows 7
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0.14.2+8.g8d20fbcb
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/e
uronewsde/live?disable_polymer=1
[plugin.youtube][debug] No channel data, falling back to API
[plugin.youtube][debug] Found channel_id: UCACdxU3VrJIJc7ujxtHWs1w
[plugin.youtube][debug] Found video_id: uEiyA-V9IHM
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
```
