### ISSUE TITLE
playtv some streams gives error

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1867]
some stream gives 404 error while most works ok.

streamlink -l debug  --http-no-ssl-verify http://playtv.fr/television/ntd  best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 0.13.0+35.g933126d
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin playtv for URL http://playtv.fr/television/ntd
error: Unable to open URL: http://edge-01.playmedia-cdn.net/origin01/ntd-tv_800/playlist.m3u8?dar=sd&t=18ddf1b11ff0fbb27659a265b39d112682c0d61962b62eacd7f69f98b392579cedb609bb3033b737a26dd88d3f316d997be5684443c209f0b053be53649946abf706455f5949daf34ec8225e2fca4f6d6a0d0da51e1c6d49531df27a1f9057a54af22170978e176682bc4d04116029b660446ee52bbee7a9 (404 Client Error: Not Found for url: https://edge-01.playmedia-cdn.net/origin01/ntd-tv_800/playlist.m3u8?dar=sd&t=18ddf1b11ff0fbb27659a265b39d112682c0d61962b62eacd7f69f98b392579cedb609bb3033b737a26dd88d3f316d997be5684443c209f0b053be53649946abf706455f5949daf34ec8225e2fca4f6d6a0d0da51e1c6d49531df27a1f9057a54af22170978e176682bc4d04116029b660446ee52bbee7a9

streamlink  -l debug http://playtv.fr/television/inspiration-tv/  best

streamlink  --http-no-ssl-verify http://playtv.fr/television/nasa/  best
streamlink  --http-no-ssl-verify http://playtv.fr/television/arab-woman-tv/

**Comment by beardypig** [comment]
For me, they do not work on the website either - doesn't seem to be a streamlink issue.

**Comment by back-to** [comment]
This is **not a streamlink issue**,
the streams **won't work on there website**, they are unavailable at the moment.

closing.

**Comment by maanich** [comment]
some stream not included in play tv and reffer to direct website of channel which are mostly works without user pass  but no plugin supported. i will try to mention stream links here to be helpful for all
