### ISSUE TITLE
tfc.tv plugin requested

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1869]
http://tfc.tv/live/details/41623/anc-live-streaming

http://tfc.tv/live/details/87039/its-showtime-live

http://tfc.tv/live/details/41729/tv-patrol-live

100 % legal and liceneced site

**Comment by maanich** [comment]
@beardypig i will email you now

**Comment by gravyboat** [comment]
@maanich Can you please not create so many plugin requests so quickly? You are creating a lot of requests with very few details and I have a hard time believing that you are using all of these sites. While we consider requests it's getting to a point where you are simply making too many requests for plugins. It's also not fair to abuse @beardypig's kindness in terms of implementation and expecting that they will implement every plugin request that you have.

**Comment by maanich** [comment]
noted. i replied as plugin has notification account needed so i sent.  will
take care of it  Regards

Raja Imran Aslam

**Comment by back-to** [comment]
Adding new plugins where it is **difficult to get an account**,
will make the new plugin impossible to maintain.

so adding it, is useless.

closing
