### ISSUE TITLE
Youtube issues started recently

### ISSUE THREAD

**Issue by markosjal** [streamlink/streamlink#1876]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
youtube streams that previously worked, not working now
...

### Expected / Actual behavior
running rthe following I expcet to get the resulting stream
streamlink youtube.com/watch?v=8DASJw1wMDQ --stream-url --default-stream best

instead I get
error: 'ascii' codec can't encode characters in position 10-11: ordinal not in range(128)

...

### Reproduction steps / Explicit stream URLs to test

1.streamlink youtube.com/watch?v=8DASJw1wMDQ --stream-url --default-stream best
2. streamlink youtube.com/watch?v=JQVb0zHP1VA --stream-url --default-stream best
3. confirmed on termux and ubuntu x86 with python 2.x

### Logs

_Logs are always required for a bug report, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l)
Make sure to **remove username and password**
You can upload your logs to https://gist.github.com/ or_

```
I have no idea whered to look for said log. I tried several things looked in several places
```

### Comments, screenshots, etc.

might be helpful to have some advice on where to find said logs

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by markosjal** [comment]
Please ignore previous post .

URLS all changed!

**Comment by beardypig** [comment]
@markosjal are you experiencing this issue on other videos?

**Comment by back-to** [comment]
it's a `Python2.7` - `UnicodeEncodeError`

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L311-L313
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L262-L263

the message from Youtube can contain `ü` or similar and this would error on python2

the `maybe_encode()` from https://github.com/streamlink/streamlink/pull/1576 could be used

for all log messages at
https://github.com/streamlink/streamlink/blob/master/src/streamlink/logger.py#L35

**Comment by beardypig** [comment]
Ah yeah, that’s where it is @back-to. It has weird encoding too though, need to update the scheme. I’m preparing a PR for the YouTube plugin, using that property for the video you suggested. It works for everything except embed URLs, but if you get the canonical URL from the embed page then it works too. Completely avoids using the API.

**Comment by karlo2105** [comment]
Youtube recently adopted new layer. To make Youtube plugin workins you have to add this at the end of address : `?disable_polymer=1`
