### ISSUE TITLE
[Update] TV4 Play.

### ISSUE THREAD

**Issue by Ordval** [streamlink/streamlink#1882]
- [x] This is a plugin (improvement) request. 

### Description
tv4play.py needs an update.  
They now separate audio and picture. 
### Log
```
C:\Users\Ordval>call streamlink.exe -l debug "https://www.tv4play.se/program/monk/3938989" best -o "E:\Documents\Monk S 3 E  2.mp4"
[console][debug] OS:         Windows 10
[console][debug] Python:     3.5.2
[console][debug] Streamlink: 0.13.0
[console][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
error: No plugin can handle URL: https://www.tv4play.se/program/monk/3938989
```
also tried with Streamlink: 0.14.2
but could this easily be accomplished in the old Plug-In with the [`--ffmpeg-ffmpeg FILENAME`](https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg) commands ?
If so as usual, I need a very hands on command line example to it:
```
C:\Users\Ordval>call streamlink.exe --ffmpeg-ffmpeg hls://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8" best
error: No plugin can handle URL: best -o "E:\Documents\Monk S 3 E  1.mp4"
```
```
call streamlink.exe hls://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8" best --ffmpeg-ffmpeg
usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
streamlink-script.py: error: argument --ffmpeg-ffmpeg: expected one argument
```
`call streamlink.exe --ffmpeg-ffmpeg hls://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8" best -o --ffmpeg-video-transcode mp4 --ffmpeg-audio-transcode aac --ffmpeg-verbose-path "E:\Documents\Monk S 3 E  1.mp4"`
```
C:\Users\ORD>call streamlink.exe --ffmpeg-ffmpeg  --ffmpeg-video-transcode h264 --ffmpeg-audio-transcode aac --ffmpeg-verbose-path hls://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8" best -o "E:\Documents\Monk S 3 E  1.mp4"
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: argument --ffmpeg-ffmpeg: expected one argument
```
### Comment 
Is DASH new to this one too ? 

```
C:\Users\Ordval>call streamlink.exe dash://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8" best
[console][info] Found matching plugin dash for URL dash://https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m3u8
error: Unable to parse XML: syntax error: line 1, column 0 (b'#EXTM3U\n#EXT-X-VERSION:4\n## Cre ...)
```

**Comment by back-to** [comment]
> tv4play.se

the last change for this plugin is **3 years old**, this plugin is **99.9%** broken

https://github.com/streamlink/streamlink/blame/master/src/streamlink/plugins/tv4play.py

---

> https://www.tv4play.se/program/monk/3938989

a login is requiered which is not supported by streamlink

---

what are you doing with `--ffmpeg-ffmpeg` ?
remove it and read the description
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

---

> Is DASH new to this one too ?

`.m3u8` is `hls://` not `dash://`

**Comment by Ordval** [comment]
Thanks for the answer. 

> a login is requiered which is not supported by streamlink

so with an added  login what do you reckon about  an update ? 
> ….and read the description

I have, hence the link:  [`--ffmpeg-ffmpeg FILENAME`](https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg)
```
--ffmpeg-verbose
    Write the console output from ffmpeg to the console.
--ffmpeg-verbose-path PATH
    Path to write the output from the ffmpeg console.
```
console,  verbose ? I'm sorry but I don't understand, 
that's why I wrote:  

> I need a very hands on command line example to it:

but I've come as far as this:
```
call streamlink.exe --ffmpeg-video-transcode copy --ffmpeg-audio-tr
anscode copy hls://"https://lbs-usp-hls-vod.cmore.se/vod/efeaa/pid500519856_3939
062(3939062_ISMUSP).ism/pid500519856_3939062(3939062_ISMUSP)-video_eng=4340000.m
3u8" best -o "E:\Documents\Monk S 3 E  1.mp4"
[cli][info] Found matching plugin hls for URL hls://https://lbs-usp-hls-vod.cmor
e.se/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/pid500519856_3939062(393
9062_ISMUSP)-video_eng=4340000.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[download][Monk S 3 E 1.mp4] Written 1.27 GB (3m52s @ 2.6 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

still without any sound. Maybe if fluent in English it's a given, but I'm not

> .m3u8` is `hls://` not `dash://``

The thing is, the (Danish) Chrome Plug-in "TV4ever" says "DASH video format is not yet
supported." to a TV4 video, but I've noted your comment.

**Comment by back-to** [comment]
there is no audio because you are using the wrong url,

you are only using the video url, try this.

```
streamlink "https://cmoreseusphlsvod69.akamaized.net/vod/efeaa/pid500519856_3939062(3939062_ISMUSP).ism/master.m3u8"
```

**Comment by bastimeyer** [comment]
> ….and read the description
> I have, hence the link

You've read something else... Read again (from the top of the link-anchor):
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

> `--ffmpeg-ffmpeg FILENAME`
> FFMPEG is used to access or mux separate video and audio streams. **You can specify the location of the ffmpeg executable** if it is not in your PATH.
> Example: "/usr/local/bin/ffmpeg"

If you're using the `--ffmpeg-ffmpeg` parameter, the next parameter will be used as `FILENAME` value. Your command didn't include a value, so the URL was used as value and was not interpreted as the actual URL. The error message of both of your commands is telling you that.

> If so as usual, I need a very hands on command line example to it:

If you read the documentation carefully, figuring out which parameters and URL formats you actually need should be quite simple, unless it lacks some information and needs to be improved. Figuring out which URL you need when there is no plugin available is a bit more complex, but @back-to should have (hopefully) already given you the correct URL. However, helping people download streams/VODs is usually not being done here, because this project is not intended to do that (for obvious reasons).

**Comment by Ordval** [comment]
@**back-to** 
That did it, and I can of course use your model stream string for their other videos, 
won't find it out though using V.D.H. #1772 (just getting the seperate aac and video) nor “URL Helper”, 
what did you use ?
@**bastimeyer**
> You've read something else... Read again.... 

I'm reading, I'm reading. 
Figuring out how to make the system work (Chinese), if I'll be needing it again,
is going to take an exceedingly amount of time and the end result is usually; I get nowhere.  
> (just getting the separate acc and video)

Seems the end result of those two would render a larger file/ video.

> However, helping people download streams/VODs is usually not being done here, 
because this project is not intended to do that (for obvious reasons).

but a bit chunk of the project (Livestreamer) has always been to be able to also download videos (?!?).
I do it regularly from the old Pluzz. 
Did you mean, not helping people _find out_ the actual streams (MRL) ? 
I understand that.

**Comment by Ordval** [comment]
@**back-to**        Still wouldn't mind that update. 
What I _can_ find following your example is this bit: `/efeaa/pid500519856_3939062(3939062_ISMUSP)` 
What I can't find is: `cmoreseusphlsvod69`  
But perhaps with the adequate device.....

**Comment by Ordval** [comment]
Thank You very, very much **back-to** for taking the time to update. 
TV 4 is our third biggest/(largest?) TV station in the country, 
so there ought to have been a greater response. 

Should anyone make a search ending up here, 
I can confirm that there is a gradual delay of audio in the video if you click-through it, 
which probably can't be adjusted by a Plug-In here,
but there's an apparent reason for Tv 4 to separate picture from audio
already in the first place so the side effect of it is only to be expected.

I have yet to play-back a video from start to finish with this update being so recent, 
maybe that will render a different result.
