### ISSUE TITLE
OK.ru broken : solved credits to back-to

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#1884]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines. 

### Reproduction steps / Explicit stream URLs to test

1. `streamlink "https://ok.ru/video/266205792931" best`

### Logs

```
streamlink -l debug "https://ok.ru/video/266205792931" best
[cli][debug] OS:         Windows 7
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0.14.2+8.g8d20fbcb
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.46.0)
error: No plugin can handle URL: https://ok.ru/video/266205792931

```

**Comment by bastimeyer** [comment]
This is not a broken plugin, VODs are simply not supported:
https://github.com/streamlink/streamlink/blob/0.14.2/src/streamlink/plugins/ok_live.py#L8
https://github.com/streamlink/streamlink/blame/0.14.2/docs/plugin_matrix.rst#L137

**Comment by back-to** [comment]
I have a better custom version for this plugin
https://raw.githubusercontent.com/back-to/plugins/master/plugins/ok_live.py
if you want to use it ...

**Comment by karlo2105** [comment]
@back-to 
Sure yours works fine. ;))

Normally I don't use streamlink for VOD but I can't play nor save video from this hoster with VLC and Firefox add-ons. 
Thanks very much. ;)

**Comment by ringtvt** [comment]
> I have a better custom version for this plugin
> https://raw.githubusercontent.com/back-to/plugins/master/plugins/ok_live.py
> if you want to use it ...
Can you give me "ok_live.py". When i enter "https://raw.githubusercontent.com/back-to/plugins/master/plugins/ok_live.py" is close. Tks
