### ISSUE TITLE
Detect name

### ISSUE THREAD

**Issue by DjUnknown** [streamlink/streamlink#1893]
## Feature Request

- [ ] I have read the contribution guidelines. 

### Description

They are going to implement a similar command like this one that is used for youtube-dl "-o %(title)s.%(ext)s", I tried to download the video https://www.atresplayer.com/antena3/series/el-secreto-de-puente-viejo/julieta-y-los-hermanos-ortega/29-06-18_5b3107d47ed1a8a40d941e4f/ but the name does not detect it, it has to be put manually.

**Comment by back-to** [comment]
there is currently no `title` support in streamlink,
it might be possible with https://github.com/streamlink/streamlink/pull/1576

But this issue is a **duplicate** of https://github.com/streamlink/streamlink/issues/791 **not directly**, **but** it requires the **same steps**.

closing
