### ISSUE TITLE
DASHStream - TypeError - 'NoneType' and 'int' - t += tsegment.d

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1895]
## Bug Report

- [x] I have read the contribution guidelines.

### Description

DASHStream is **not valid for streamlink**,
the stream **works with vlc and mpv**

### Reproduction steps / Explicit stream URLs to test

1. https://zattoo.com/ondemand any vod there
    free account required,
    but the url is probably different in the webbrowser (drm)
    use the logs.

### Logs

**error**

https://gist.github.com/back-to/5ce300951242872552c21ebb2591c67d#file-error-txt

**mpd**

https://gist.github.com/back-to/5ce300951242872552c21ebb2591c67d#file-zattoo_vod-mpd-xml

**Comment by beardypig** [comment]
I’d say the problem is on line 633. Should check `if tsegment.t is not None` before swapping them :)

**Comment by back-to** [comment]
yes this works.
