### ISSUE TITLE
bbciplayer ok with v13 but v14 error

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1896]
v13 log on home pc with 3 mb upload..
```
$ streamlink --http-no-ssl-verify --bbciplayer-username xxxx@gmail.com --bbciplayer-password xxxxxx https://www.bbc.co.uk/iplayer/live/bbcone 1700k  --player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /mnt/hls/bbconehd.m3u8
ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[cli][info] Available streams: 540p_dash_alt, 396p_dash, 540p_dash_alt2, 288p_dash_alt, 396p_dash_alt2, 396p_dash_alt, 288p_dash_alt2, 540p_dash, 288p_dash, 352k_alt2 (worst), 352k_alt, 352k, 544k_alt2, 544k_alt, 544k, 216p_alt2, 216p_alt, 216p, 288p_alt2, 288p_alt, 288p, 942k_alt2, 942k_alt, 942k, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p, 1700k_alt2, 1700k_alt, 1700k (best)
[cli][info] Opening stream: 1700k (hds)
[flv @ 0x6adbd00] Negative cts, previous timestamps might be wrong.
[flv @ 0x6adbd00] Invalid timestamps stream=1, pts=40, dts=80, size=4639
[flv @ 0x6adbd00] Invalid timestamps stream=1, pts=80, dts=120, size=6969
[flv @ 0x6adbd00] Invalid timestamps stream=1, pts=120, dts=160, size=5493
```

best u get 1700k

but v14 on  vps 1gb

```
$ streamlink --http-no-ssl-verify --bbciplayer-username xxx@gmail.com  --bbciplayer-password xxxxhttps://www.bbc.co.uk/iplayer/live/bbcone best  --player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /mnt/hls/bbconehd.m3u8
ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[cli][info] Available streams: 540p_dash_alt2, 288p_dash_alt2, 396p_dash_alt, 540p_dash, 288p_dash, 396p_dash_alt2, 540p_dash_alt, 396p_dash, 288p_dash_alt, 216p_alt2 (worst), 216p_alt, 216p, 288p_alt2, 288p_alt, 288p, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p (best)
[cli][info] Opening stream: 540p (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8')> (Could not open stream: Unable to open URL: http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8 (403 Client Error: Forbidden for url: http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8))
error: Could not open stream <HLSStream('http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8')>, tried 1 times, exiting
pipe:0: Invalid data found when processing input
```

**Comment by maanich** [comment]
sorry its not the version issue just tested stream again in vps with local pc proxy  and it got 1700k but vps i found 540p

**Comment by maanich** [comment]
vps server 

streamlink -l debug --bbciplayer-username xxxx@gmail.com --bbciplayer-password xxxxx https://www.bbc.co.uk/iplayer/live/bbcone best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     3.4.3
[cli][debug] Streamlink: 0.14.2+14.g0e48e2f
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[cli][debug] Plugin specific arguments:
[cli][debug]  --bbciplayer-username=xxxxx@gmail.com (username)
[cli][debug]  --bbciplayer-password=******** (password)
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][debug] Loading stream for live channel: bbcone
[plugin.bbciplayer][debug] Looking for  tvip on https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][debug] Found TVIP: bbc_one_london
[plugin.bbciplayer][debug] Info API request: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/
[plugin.bbciplayer][debug] Info API request: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/iptv-all/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/
[plugin.bbciplayer][debug] 4 hls streams
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/ak/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/aks/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/llnw/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/llnws/bbc_one_london.m3u8
[plugin.bbciplayer][debug] 8 dash streams
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/ak/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/llnws/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/llnw/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/aks/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/llnw/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/llnws/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/ak/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/aks/bbc_one_london.mpd
[plugin.bbciplayer][debug] 4 hds streams
[plugin.bbciplayer][debug]   FAIL: https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/llnws/bbc_one_london.f4m
[plugin.bbciplayer][debug]   FAIL: http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/ak/bbc_one_london.f4m
[plugin.bbciplayer][debug]   FAIL: http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/llnw/bbc_one_london.f4m
[plugin.bbciplayer][debug]   FAIL: https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/aks/bbc_one_london.f4m
[cli][info] Available streams: 288p_dash_alt, 396p_dash, 396p_dash_alt, 540p_dash, 396p_dash_alt2, 288p_dash_alt2, 540p_dash_alt2, 540p_dash_alt, 288p_dash, 216p_alt2 (worst), 216p_alt, 216p, 288p_alt2, 288p_alt, 288p, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p (best)
[cli][info] Opening stream: 540p (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8')> (Could not open stream: Unable to open URL: http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8 (403 Client Error: Forbidden for url: http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8))
error: Could not open stream <HLSStream('http://vs-hls-uk-live.akamaized.net/pool_902/live/bbc_one_london/bbc_one_london.isml/bbc_one_london-pa4%3d128000-video%3d1604032.m3u8')>, tried 1 times, exiting


not working as got 540p

from local ubuntu all ok

streamlink -l debug --bbciplayer-username xxxxx@gmail.com --bbciplayer-password xxxx https://www.bbc.co.uk/iplayer/live/bbcone best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.14.0-041400-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     3.4.3
[cli][debug] Streamlink: 0.14.2+14.g0e48e2f
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/live/bbcone
[cli][debug] Plugin specific arguments:
[cli][debug]  --bbciplayer-username=xxxx@gmail.com (username)
[cli][debug]  --bbciplayer-password=******** (password)
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][debug] Loading stream for live channel: bbcone
[plugin.bbciplayer][debug] Looking for  tvip on https://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][debug] Found TVIP: bbc_one_london
[plugin.bbciplayer][debug] Info API request: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/pc/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/
[plugin.bbciplayer][debug] Info API request: http://open.live.bbc.co.uk/mediaselector/6/select/version/2.0/mediaset/iptv-all/vpid/bbc_one_london/format/json/atk/78ca5063d64bb5b308d1d87f737b610aa2db0f3f/asn/1/
[plugin.bbciplayer][debug] 4 hds streams
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/aks/bbc_one_london.f4m
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/ak/bbc_one_london.f4m
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/llnw/bbc_one_london.f4m
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hds/uk/pc/llnws/bbc_one_london.f4m
[plugin.bbciplayer][debug] 4 hls streams
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/llnws/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/ak/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/llnw/bbc_one_london.m3u8
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_tv/aks/bbc_one_london.m3u8
[plugin.bbciplayer][debug] 8 dash streams
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/ak/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/ak/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/llnws/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/llnw/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/aks/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/llnw/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_abr_tv/llnws/bbc_one_london.mpd
[plugin.bbciplayer][debug]   OK:   https://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/dash/uk/dash_pc/aks/bbc_one_london.mpd
[cli][info] Available streams: 540p_dash, 288p_dash_alt, 540p_dash_alt, 396p_dash_alt, 288p_dash_alt2, 540p_dash_alt2, 396p_dash_alt2, 288p_dash, 396p_dash, 352k_alt2 (worst), 352k_alt, 352k, 544k_alt2, 544k_alt, 544k, 216p_alt2, 216p_alt, 216p, 288p_alt2, 288p_alt, 288p, 942k_alt2, 942k_alt, 942k, 396p_alt2, 396p_alt, 396p, 540p_alt2, 540p_alt, 540p, 1700k_alt2, 1700k_alt, 1700k (best)
[cli][info] Opening stream: 1700k (hds)
[stream.hds][debug] Updating bootstrap
[stream.hds][debug] Live edge buffer 10.0 sec is 3 fragments
[stream.hds][debug] Current timestamp: 1530571645.44
[stream.hds][debug] Current segment: -1
[stream.hds][debug] Current fragment: 398586364
[stream.hds][debug] First fragment: 398584493
[stream.hds][debug] Last fragment: 398586366
[stream.hds][debug] End fragment: None
[stream.hds][debug] Adding fragment 1-398586364 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hds][debug] Adding fragment 1-398586365 to queue
[stream.hds][debug] Adding fragment 1-398586366 to queue
[cli][info] Starting player: /usr/bin/vlc
[stream.hds][debug] Download of fragment 1-398586364 complete
[stream.hds][debug] Download of fragment 1-398586365 complete
[stream.hds][debug] Download of fragment 1-398586366 complete
[cli][debug] Writing stream to output
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by maanich** [comment]
i think vps looks  banned but the issue comes in both itv and bbciplayer on that  ovh server. i am confused how i newly bought uk based server ip blocked.

**Comment by bastimeyer** [comment]
> 403 Client Error: Forbidden

This is not a Streamlink error

**Comment by maanich** [comment]
but i f u see bitrates on top one and bottom  [cli][info] Opening stream: 540p (hls)
[cli][info] Opening stream: 1700k (hds)

**Comment by pshotsf** [comment]
@beardypig just some off-topic question. If i keep seeing  "Invalid timestamps stream=1" when using streamlink+ffmpeg, is it normal?Thanks

**Comment by pshotsf** [comment]
@maanich try this 
"streamlink http://a.files.bbci.co.uk/media/live/manifesto/audio_video/simulcast/hls/uk/abr_hdtv/ak/bbc_one_hd.m3u8 best

**Comment by beardypig** [comment]
@maanich & @pshotsf, [--bbciplayer-hd](https://streamlink.github.io/cli.html#cmdoption-bbciplayer-hd).

@maanich, the range of IPs from ovh will be blocked, doesn't matter if it's new or old (well, you might get lucky with a new one if it's in another IP block). The HDS streams are hosted by a different company with different IP blocking rules. Not a streamlink issue as far as I can tell.

@pshotsf, from bbciplayer? It depends on the stream, not every stream is well formed and `ffmpeg` will complain - not much can be done about that.

I will close this issue as it the question has been answered.
