### ISSUE TITLE
Funimationnow plugin failing: no exp. ID

### ISSUE THREAD

**Issue by vinnyA3** [streamlink/streamlink#1899]
## Bug Report

- [x] I have read the contribution guidelines. 

### Description

The funimation plugin is failing to play content when authenticating

### Expected / Actual behavior

**Expected behavior**:  mpv opens a video via the funimation api

**Instead got**:  the error via console ...
```
[plugin.funimationnow][info] Attempting to by-pass Incapsula...
[plugin.funimationnow][error] Could not find experience ID?!
error: No playable streams found on this URL: https://www.funimation.com/shows/fairy-tail/turbulent-showdown-natsu-vs-laxus/uncut/?lang=english
``` 

### Reproduction steps / Explicit stream URLs to test

1. `streamlink --loglevel debug -p mpv --funimation-email="<my-email>" https://www.funimation.com/shows/fairy-tail/turbulent-showdown-natsu-vs-laxus/uncut/?lang=english
`
2. `Enter funimationnow password: <my-password>`

### Logs

[(debug log)](https://gist.github.com/vinnyA3/c23d228d12c34f9f34ba5b16cfeb5d7e)

**Comment by beardypig** [comment]
Thanks you for the report - I will investigate.

**Comment by beardypig** [comment]
The Incapsula protection has improved since the original plugin was implemented. Without included a lot of dependencies this might be too tricky to solve.

**Comment by gravyboat** [comment]
I'd rather not bloat Streamlink with additional dependencies if we can help it for a single plugin.

**Comment by vinnyA3** [comment]
I agree, it's not worth it.  It's all good though!  Does this mean that the funimation plugin should be removed?

**Comment by beardypig** [comment]
I will create a PR to mark is as broken, and create new issue explaining the problem. Perhaps there is a better way to fix it, I just didn't find it yet :)

**Comment by beardypig** [comment]
Instead of marking it as broken I have proposed a workaround.

**Comment by vinnyA3** [comment]
@beardypig Sweet! works perfectly!  I tested with the following parameters:

`streamlink --player='mpv' --funimation-email="<email>" --funimation-password='<password>' --http-cookie "<incap_ses cookie>" https://www.funimation.com/shows/my-hero-academia/deku-vs-kacchan-part-2/simulcast/?lang=english 720p`

Where the *incap_ses cookie* was extracted from local storage via Chrome Dev tools.  Now, it may be cumbersome to open dev tools each time to extract the cookie value, but there are lightweight plugins in the Chrome Plugin Store that could make this process seamless.

https://github.com/streamlink/streamlink/issues/2088

**Comment by gravyboat** [comment]
I think this is a pretty fair workaround, it's a bit more work, but having the plugin work in some way is better than not having it at all. Good idea @beardypig.

**Comment by beardypig** [comment]
OK. I'm going to close this issue.

Please refer to #2088.
