### ISSUE TITLE
Support for non-ASCII display names

### ISSUE THREAD

**Issue by lewisje** [streamlink/streamlink#19]
I've been using an OAuth token in Livestreamer for well over a year, ever since I learned it could be done, to help out the stream viewer counts; today, after seeing the latest beta of Chatty could handle localized display names accurately, I decided to finally get one for myself, and then whenever I tried to launch Livestreamer, I got this error:

```
error: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
```

I couldn't go back to the old completely anonymous way, because Twitch no longer allows anonymous API requests, so instead I tried this workaround that has been floating around, the following line in my livestreamerrc:

```
http-header=Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6
```

It allowed me to watch streams, but I would like to be able to be logged in via the stream-viewer again.

**Comment by sbstp** [comment]
Was the error message bigger than this? Was there a stack trace? That would help us trace where the issue was. Also were you using Python 2 or Python 3?

**Comment by lewisje** [comment]
I believe I was using Python 2, and I didn't see a stack trace, just that error followed by termination.

**Comment by gravyboat** [comment]
This appears to have been fixed in #122, I'm going to close it for now, if it's still a problem please re-open the issue.

**Comment by steveooo9** [comment]
This still exists in default DigitalOcean 18.04 with Python2 and Python3

**Comment by beardypig** [comment]
@steveooo9 can you create a new issue with all the details?
