### ISSUE TITLE
Error with using --twitch-oauth-authenticate

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#190]
Using that causes a browser to open to http://livestreamer.tanuki.se/en/develop/twitch_oauth.html?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI   In the main.py file this link is show http://streamlink.tanuki.se/en/develop/twitch_oauth.html when it should link to this https://streamlink.github.io/twitch_oauth.html  https://github.com/streamlink/streamlink/blob/master/src/streamlink_cli/main.py#L536

https://github.com/streamlink/streamlink/issues/4#issuecomment-261737748

**Comment by gravyboat** [comment]
Good catch @thinkpad4, I've prepped a PR to address this.

**Comment by thinkpad4** [comment]
Glad to help

**Comment by thinkpad4** [comment]
@gravyboat Strange thing, I manually changed the link in the main.py file, and using that command it still goes to http://livestreamer.tanuki.se/en/develop/twitch_oauth.html?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI.  Could there be a sneak code somewhere else that is overriding the one in main.py?

**Comment by bastimeyer** [comment]
> Could there be a sneak code somewhere else that is overriding the one in main.py?

Check the redirect URI (also) of the app's settings. Twitch may ignore the url parameter and use this instead. I'm not sure, though.

![screenshot from 2016-11-22 03-00-14](https://cloud.githubusercontent.com/assets/467294/20508154/dcf5508a-b05f-11e6-993d-6783325e50fb.png)

**Comment by gravyboat** [comment]
Hmm, I grepped through the entire repo and changed it in the only location it wasn't compiled. I think @bastimeyer might have the right idea.

**Comment by thinkpad4** [comment]
https://discuss.dev.twitch.tv/t/redirect-mismatch/1695/6

**Comment by thinkpad4** [comment]
@cdrage I would say, needs to register Streamlink on Twitch http://i.imgur.com/4x3C0vt.jpg and put Name - Streamlink Redirect URL - https://streamlink.github.io/twitch_oauth.html then replace the Client ID in Twitch.py with the new Client ID then --twitch-oauth-authenticate will correctly work

**Comment by beardypig** [comment]
@thinkpad4 is correct, a lot of this was discussed on #4 but got lost down the cracks...

**Comment by beardypig** [comment]
Who wants to create a twitch app to get ya new client id with an updated redirect url? @gravyboat, @cdrage?

**Comment by cdrage** [comment]
@gravyboat @sbstp @beardypig feel free to create it! Perhaps distribute the username/pass when you create it to the maintainers. Then do a PR with the new key :)

**Comment by thinkpad4** [comment]
Just making sure this doesn't get lost in the ether again

**Comment by thinkpad4** [comment]
Now I don't know how to make a PR request but I did try my hand this.  I made a Twitch account and set up streamlink in it and got the Client-ID if you wanna use it.  If there is a discord or email I can use to post the twitch account and the temp email I used to make the account let me know.  As for the Client-ID, it is pwkzresl8kj2rdj6g7bvxl9ys1wly3j

**Comment by gravyboat** [comment]
Thanks @thinkpad4! We'll have to get this updated here: https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L31 regarding the email creds and twitch account, let's see what people weigh in with, it might be best to just send the details to a few people directly.

**Comment by thinkpad4** [comment]
@gravyboat I emailed @cdrage with the account info for the twitch channel and email I used to create the Twitch channel

**Comment by thinkpad4** [comment]
@gravyboat Can I email you what I sent @cdrage can I email you using the email on your website?

**Comment by gravyboat** [comment]
@thinkpad4 Yep that's fine!

**Comment by thinkpad4** [comment]
Sent

**Comment by gravyboat** [comment]
Thanks I got it!

**Comment by thinkpad4** [comment]
If you wanna make the PR please do, I don't know how to make one.  You can change the twitch password too, the temp email is set to expire after a year

**Comment by gravyboat** [comment]
I'll update it shortly, not sure I will have time tonight.

**Comment by gravyboat** [comment]
I've proposed a PR to update this.

**Comment by thinkpad4** [comment]
No worries, you did make sure to change the Twitch password right?

**Comment by gravyboat** [comment]
Yeah I took care of it. @cdrage @beardypig what's the best way to get these details to you? I would prefer that at least 3 of us have the creds. We'll have to come to some sort of conclusion regarding the email as well, I propose we use a shared protonmail account.

**Comment by beardypig** [comment]
@gravyboat you can get me at beardypig at protonmail dot com :-) Bus factor 3, good.

**Comment by cdrage** [comment]
@gravyboat personal email on my github would be best:)

**Comment by gravyboat** [comment]
@cdrage Do you have a publicly available key I can encrypt the password with?

**Comment by beardypig** [comment]
Will close this once @cdrage confirms he has a copy of the credentials.

**Comment by cdrage** [comment]
@gravyboat 
charliedrage.com/contact

**Comment by gravyboat** [comment]
@cdrage I've sent that over to you, once you have confirmed you have them we'll be all set on that aspect. We still need to come to a conclusion regarding the email address, any suggestions or preferences?

**Comment by thinkpad4** [comment]
I would suggest use a agreed upon protonmail for the email.  Keep it simple.  Also the temp email I used I set to expire in 1 year, just saying

**Comment by gravyboat** [comment]
@thinkpad4 Yep I remember that note from your original email, no worries we'll get it sorted shortly!

**Comment by cdrage** [comment]
@gravyboat received and :+1: my side!

**Comment by beardypig** [comment]
We good to close this now that a few people have the credentials?

**Comment by cdrage** [comment]
@beardypig all good from me, let's close this :)

**Comment by chiefstank** [comment]
Still not fixed. What could I be doing wrong? Still taking me to http://livestreamer.tanuki.se/en/develop/twitch_oauth.html?error=redirect_mismatch&error_description=Parameter+redirect_uri+does+not+match+registered+URI. Really need this feature.

**Comment by beardypig** [comment]
@chiefstank have you tried the latest version / nightly?

**Comment by chiefstank** [comment]
@beardypig sorry for late response and happy holidays. I have the latest version but have not tried nightly.
