### ISSUE TITLE
plugin pluzz for URL https://www.france.tv issue

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1900]
```
$ streamlink -l debug https://www.france.tv/france-o/direct.html  best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     3.4.3
[cli][debug] Streamlink: 0.14.2+17.g4e2f64b
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-o/direct.html
[stream.hls][debug] Using external audio tracks for stream 144p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 180p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 288p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 396p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 576p (language=fra, name=Francais)
[plugin.pluzz][error] Failed to access stream, may be due to expired content
[cli][info] Available streams: 180p_hls, 576p_hls, 396p_hds, 288p_hls, 144p_hls, 180p_hds, 396p_hls, 144p_hds, 288p_hds, 576p_hds, 65k (worst), 144p, 144p+a66k, 180p, 180p+a66k, 288p, 288p+a66k, 396p, 396p+a66k, 576p, 576p+a66k (best)
[cli][info] Opening stream: 576p+a66k (dash)
[stream.dash][debug] Opening DASH reader for: video=1404000.track_id=10004 (video/mp4)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=None))
[stream.dash][debug] Opening DASH reader for: audio_20001=65600.track_id=20001 (audio/mp4)
[stream.dash][debug] Reloading manifest (video=1404000.track_id=10004:video/mp4)
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-video=1404000.track_id=10004-init.mp4 complete
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist (id=None))
[stream.dash][debug] Reloading manifest (audio_20001=65600.track_id=20001:audio/mp4)
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-init.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990549848.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990614360.mp4 complete
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-3056-814 -i /tmp/ffmpeg-3056-59 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-3056-814
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-3056-59
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990677849.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990742361.mp4 complete
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990805850.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990870363.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990933852.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538990998364.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991061853.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991126365.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991189854.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991254367.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991317856.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991382368.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-audio_20001=65600.track_id=20001-3538991445857.mp4 complete
[stream.dash][debug] Download of segment: http://live.francetv.fr/simulcast/France_O/dash/ZXhwPTE1MzA2ODU0OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV9PJTJmZGFzaCp+aG1hYz03ZmE1MzFlZmM3MGViYTRmZGU1Y2JhZjcxYWFkNjMzOTQ1YTE0NTg5MzM2ZWU1MDc5ODc4NjY2M2I0NTgyYmQw/dash/France_O-video=1404000.track_id=10004-2764837066.mp4 complete
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Closed all the substreams
```

tried but not working

**Comment by maanich** [comment]
withh ffmpeg   log

streamlink --http-no-ssl-verify https://www.france.tv/france-o/direct.html best --player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /mnt/hls/fro.m3u8
root@dedi-par-Vod:~# streamlink  --http-no-ssl-verify https://www.france.tv/france-o/direct.html  best --player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /mnt/hls/fro.m3u8^[[H^C
root@dedi-par-Vod:~# streamlink https://www.france.tv/france-o/direct.html  best --player-no-close --stdout | /var/tmp/youtube/ffmpeg -y -i pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /mnt/hls/fro.m3u8     ffmpeg version 4.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-libxml2 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-o/direct.html
[plugin.pluzz][error] Failed to access stream, may be due to expired content
[cli][info] Available streams: 144p_hds, 288p_hds, 288p_hls, 180p_hds, 396p_hds, 396p_hls, 576p_hds, 180p_hls, 576p_hls, 144p_hls, 65k (worst), 144p, 144p+a66k, 180p, 180p+a66k, 288p, 288p+a66k, 396p, 396p+a66k, 576p, 576p+a66k (best)
[cli][info] Opening stream: 576p+a66k (dash)
[matroska,webm @ 0x5996d00] Could not find codec parameters for stream 0 (Video: h264, none(tv, bt470bg), 1024x576): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from 'pipe:0':
  Metadata:
    COMPATIBLE_BRANDS: iso6dash
    MAJOR_BRAND     : iso6
    MINOR_VERSION   : 0
    ENCODER         : Lavf57.82.100
  Duration: N/A, start: 110593824.700000, bitrate: N/A
    Stream #0:0: Video: h264, none(tv, bt470bg), 1024x576, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      HANDLER_NAME    : Video Handler
      ENCODER         : AVC Coding
    Stream #0:1(qad): Audio: aac (LC), 32000 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : Sound Handler
[hls @ 0x59a05c0] Opening '/mnt/hls/fro0.ts' for writing
Output #0, hls, to '/mnt/hls/fro.m3u8':
  Metadata:
    COMPATIBLE_BRANDS: iso6dash
    MAJOR_BRAND     : iso6
    MINOR_VERSION   : 0
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264, none(tv, bt470bg), 1024x576 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 1k tbc (default)
    Metadata:
      HANDLER_NAME    : Video Handler
      ENCODER         : AVC Coding
    Stream #0:1(qad): Audio: aac (LC), 32000 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : Sound Handler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
[hls @ 0x59a05c0] Opening '/mnt/hls/fro1.ts' for writing
[hls @ 0x59a05c0] Opening '/mnt/hls/fro.m3u8.tmp' for writing
[hls @ 0x59a05c0] Invalid DTS: 2536200 PTS: 2525400 in output stream 0:0, replacing by guess
[hls @ 0x59a05c0] Non-monotonous DTS in output stream 0:0; previous: 2532601, current: 2525400; changing to 2532602. This may result in incorrect timestamps in the output file.
[hls @ 0x59a05c0] Non-monotonous DTS in output stream 0:0; previous: 2532602, current: 2529000; changing to 2532603. This may result in incorrect timestamps in the output file.
frame=   44 fps= 11 q=-1.0 size=N/A time=00:00:29.72 bitrate=N/A speed=7.56x

**Comment by bastimeyer** [comment]
> error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.

You have not specified a player, as the error message is telling you.
The stream is working fine via Streamlink, just tested it with my French socks5 proxy...

This is your 10th issue now within the past two weeks and most of them were no real issues/bugs and just caused by user errors. Asking questions or requesting new plugins is absolutely fine, but I guess it's not only me who would really appreciate it, if you could at least read your own log output or do a little bit of research on your own before opening a new issue. Also, the issue template is there for a reason, so that people (hopefully) read before submitting, so that most non-issues can be prevented and the amount of *spam* can be reduced. Thank you!

**Comment by maanich** [comment]
> i m using ffmpeg n nginx not vlc if u see my last log.

**Comment by bastimeyer** [comment]
> see my last log

Your last command is using the `--stdout` parameter, which lets Streamlink output the data to stdout instead of launching a player. If you don't use this parameter, the default player has to be launched and if the executable of the default player in its default location can not be found, Streamlink will output this error message and exit.

**Comment by beardypig** [comment]
@maanich what is the issue? You just posted logs. What exactly are you expecting to happen. If you don’t follow the template and answer the questions, how can we help you?

**Comment by maanich** [comment]
well i use it to get it as hls m3u8 and then use it in remote server through nginx http stream . reason of showing u all is that stream itself gives error while before three days all is well with the same command .

**Comment by maanich** [comment]
leave it as alot of guy start commenting for nothing  log clearly showed stream not working. with errors shown keeps connect disconnect.
