### ISSUE TITLE
Generic Stream Detector

### ISSUE THREAD

**Issue by hpmueller1971** [streamlink/streamlink#1901]
## Feature Request

- [x] I have read the contribution guidelines. 

### Description

For Firefox (original-non-quantum-fatfox-flavor) there is an addon "[HLS Stream Detector"](https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/?src=api) which can detect any HLS Streams on a website like i.e.

http://www.livenewson.com/american/cnn-news-usa.html, it detects one HLS Stream,

http://212.8.253.29:1935/cnew/myStream/chunklist_w660325334.m3u8

This stream/link works fine in VLC, but is pretty dynamic and only valid vor a few hours.

On some sites, multiple streams are detected

"HLS Stream Detector" works on a lot of websites that streamlink does not support yet.

### Expected / Actual behavior

Currently, if no plugin machtes, streamlink just exits. If there's no matching plugin, it should search for streams; if multiple streams are found, they could simply be numbered and used as "quality"

### Additional comments, screenshots, etc.

My programming skills are zero, i have no idea how the firefox addon works, if it requires a full html-engine, this FR probably should be tagged out-of-scope ;)

**Comment by Ordval** [comment]
Good luck to you if you get this one through ! (Member)
The normal procedure here is to request for a plug-in for that particular site etc.
you know this already, right ? 
But Hey, you just promoted an Add-On for me !

**Comment by beardypig** [comment]
@back-to has a plugin called `resolve` that does some of what you want. However, it doesn’t execute any JavaScript, etc., for the sites where the stream is hidden behind JavaScript you would need a specific plugin.

**Comment by johnthecracker** [comment]
Sounds like 2 or 3 more plugins like resolve.py

makes 200 fewer plugins like my_wish_plugin.py

**Comment by back-to** [comment]
you can take a look at
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor
this is basically your Firefox plugin.

---

yes, I have a generic plugin

https://github.com/back-to/plugins/blob/master/plugins/resolve.py

but adding it directly to streamlink might **confuse** to many **people**,

as there are **false positives**

**Comment by johnthecracker** [comment]
You made plugins that (Member) doesn't want here, and I appreciate that.

false positives ?

fc2.py and likes work.

**Comment by beardypig** [comment]
@johnthecracker it's not that the `resolve` plugin is not wanted, it's about usability. `resolve` is a complex and advanced plugin - it can be very useful, but what I think @back-to is saying is that it would put extra support burden on us if it were included with vanilla streamlink. By all means use it, but you probably own't get much support :)

**Comment by johnthecracker** [comment]
(Member) is gravyboat, not you.

If it was his way, streamlink would be for twitch only.

**Comment by Ordval** [comment]
Well there **hpmueller197**, 
who knows what you might find if you dig real deep. 
Tell us it it helped.

**Comment by gravyboat** [comment]
I'm going to close and lock this as there's nothing more to discuss on this topic. A generic stream detector isn't something we're going to support as it would be way too problematic and open us up to too many issues both from users and potential DMCA claims. It would be nothing for a headache and we're already stretched thin.
