### ISSUE TITLE
tvp.py 

### ISSUE THREAD

**Issue by remek30** [streamlink/streamlink#1904]
I noticed a problem with the tvp.py plugin consisting of freezing the image and sound every 2-3 seconds - a similar problem was in the toya.py plugin, which has already been solved. Please fix the tvp.py plugin so that it will not jam every 2-3 seconds while watching.

**Comment by back-to** [comment]
There is no issue with the streamlink plugin or there streams,
if you have locally lags you can use commands such as

https://streamlink.github.io/cli.html#cmdoption-hls-live-edge

or cache the stream with using the pause button.

**Comment by bastimeyer** [comment]
@remek30 
@back-to already anwsered your question and told you to configure Streamlink's HLS options if you're experiencing lags. This is not a plugin issue. Same as your other issue #1880

**Comment by remek30** [comment]
I know that this is not a problem with the plugin but I have too little knowledge and I ask you why, if you can edit this TVP plugin for me, I do not have problems with you interrupting the picture every 2-3 seconds. I apologize for the inconvenience, but I am asking you for help.

**Comment by beardypig** [comment]
`streamlink --hls-live-edge 10 <url> <quality>`

**Comment by remek30** [comment]
in which place should I paste it - and should it be pasted into the TVP.py plugin or streamlink itself? Sure, I am asking for help.

**Comment by gravyboat** [comment]
@remek30 This is the command you would run on the command line when you invoke Streamlink, it does not need to be added to the plugin, we support a large number of command line options specifically for instances like this. You should take a look at the [documentation](https://streamlink.github.io/index.html#quickstart), and especially the [command line interface documentation](https://streamlink.github.io/cli.html) as they're pretty thorough.

**Comment by back-to** [comment]
@remek30 

As you are **not using streamlink from the command line**,
we don't know what your third party application supports or how it works.

**Changing plugins is bad**, when you **update** Streamlink it **will be overwritten**.

The best way is to use plugin specific config files

https://streamlink.github.io/cli.html#plugin-specific-configuration-file

new file

```
/home/root/.config/streamlink/config.tvp
```

with this text

```
hls-live-edge=10
```

but I don't know if this is supported where you use Streamlink with.

You will have to rely on the third party for this, not directly with Streamlink.
