### ISSUE TITLE
Playtv uk

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1905]
playtv.fr working fine is there any possibility to run http://uk.play.tv/    looks like both sites france and uk owned by same  company. As streamlink support tvplay.fr. hope u get support for uk playtv.
http://uk.play.tv/live-tv/363/pick-tv/
http://uk.play.tv/live-tv/752/itv4-1/
http://uk.play.tv/live-tv/1106/itv3-1/
http://uk.play.tv/live-tv/1105/itv-1/

**Comment by gravyboat** [comment]
This doesn't meet the plugin request template requirements and I believe you were notified of this before on another issue, so why are you not using the template and including the required information?

**Comment by maanich** [comment]
@gravyboat i m happy to do it mate. any donation link here. and please if u add link of tel=mplaye i m happy to do it throught that process. regards.

**Comment by back-to** [comment]
All of these streams are just embedded, just use the source website.
