### ISSUE TITLE
AES-128 decryption

### ISSUE THREAD

**Issue by limiteddi** [streamlink/streamlink#1906]
Streamlink is complaining about a decryptor. I was able to get the contents of the m3u8 file but now I am not sure whether I need to be able to download the key file or there is a workaround?

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:16248
#EXT-X-TARGETDURATION:6
#EXT-X-KEY:METHOD=AES-128,URI="https://49.40.0.166/streams_live/BBC_World_News/BBC_World_News_1200-1530833376000.key",IV=0x0000000000000000000001646CC79300
#EXTINF:6.000,
BBC_World_News_1200-1530837266000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837272000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837278000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837284000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837290000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837296000.ts
#EXTINF:6.000,
BBC_World_News_1200-1530837302000.ts
```
Here is what streamlink returns:

```
streamlink --http-header "User-Agent=ExoPlayerDemo/5.1.6 (Linux;Android 4.4.2) ExoPlayerLib/2.3.0" "hlsvariant://http://49.40.0.166/BBC_World_News/BBC_World_News_1200.m3u8?jct=QmYBMdq_hJwTySmBum-_3w&pxe=1530842838&st=AQIC5wM2LY4Sfcw2TWd1XaBOHvbp9r0nECMh6Oz5GRLcRKQ.*AAJTSQACMDIAAlNLABQtNjAxODQxNDMwMjg2MzA3NDM3MAACUzEAAjM1*" best --player-external-http --player-external-http-port 10007
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin hls for URL hlsvariant://http://49.40.0.166/BBC_World_News/BBC_World_News_1200.m3u8?jct=QmYBMdq_hJwTySmBum-_3w&pxe=1530842838&st=AQIC5wM2LY4Sfcw2TWd1XaBOHvbp9r0nECMh6Oz5GRLcRKQ.*AAJTSQACMDIAAlNLABQtNjAxODQxNDMwMjg2MzA3NDM3MAACUzEAAjM1*
[cli][info] Available streams: live (worst, best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:10007/
[cli][info]  http://127.0.1.1:10007/
[cli][info] Got HTTP request from VLC/3.0.3 LibVLC/3.0.3
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://49.40.0.166/streams_live/BBC_World_News/BBC_World_News_1200-1530840578000.key (405 Client Error: Not Allowed for url: https://49.40.0.166/streams_live/BBC_World_News/BBC_World_News_1200-1530840578000.key)
[cli][error] No data returned from stream
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://49.40.0.166/streams_live/BBC_World_News/BBC_World_News_1200-1530840578000.key (405 Client Error: Not Allowed for url: https:/49.40.0.166/streams_live/BBC_World_News/BBC_World_News_1200-1530840578000.key)
[cli][error] No data returned from stream
[cli][info] Opening stream: live (hls)
```

**Comment by bastimeyer** [comment]
Can you please follow the issue template and provide a debug log?

**Comment by gravyboat** [comment]
We've discussed a very similar issue before as well: https://github.com/streamlink/streamlink/issues/618. You can try to take a look in the contents of that `EXT-X-KEY` file and if it looks like DRM there's nothing we can do as Streamlink doesn't support streams that use DRM.

**Comment by limiteddi** [comment]
I can't download the .key file, returns 401 message. I am assuming I am not passing enough parameters to authorize my request? So without the key file the .ts files are all encrypted?

**Comment by gravyboat** [comment]
Yeah if you can't download/access the key and pass it over then there's nothing that can be done if the actual stream is encrypted in some way. As I said before even the key may not be enough if it uses some sort of DRM.

**Comment by limiteddi** [comment]
If I manage to get the key, what would be the next step to play the link in streamlink?

**Comment by gravyboat** [comment]
Maybe send the key along with the header or decrypt the files after download somehow? I'm not really sure as I don't watch any encrypted streams.

**Comment by beardypig** [comment]
You probably net to set the correct auth cookies using the `--http-cookie` option.

**Comment by back-to** [comment]
You already opened **exactly the same Issue** for a different website,
it is still the same as before you will have to add http headers/cookies

https://github.com/streamlink/streamlink/issues/1557
https://github.com/streamlink/streamlink/issues/1557#issuecomment-373911892
