### ISSUE TITLE
Mjunoon plugin issue

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1907]
Hi  first all of all extreme sorry if i am publishing in wrong area.

mjunoon plugin while running gives continous error which makes streamlink crash at the end

/streamlink -l debug --player-continuous-http --player-external-http --player-external-http-port=2000 https://www.mjunoon.tv/express-news-live best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-149-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.2.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin mjunoon for URL https://www.mjunoon.tv/express-news-live
[plugin.mjunoon][debug] Found the playerScript script tag
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
[cli][info] Available streams: 270p (worst), 480p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:2000/
[cli][info]  http://127.0.1.1:2000/

it works fine forsome time in vlc player when i add link in vlc but crash after some time.
no clue with me  how it crash as ssl warning continously shown.

**Comment by back-to** [comment]
you cut the logs where you opened the stream

**Comment by maanich** [comment]
i was afraid of previous statements so i make it short . i able to get it done with uninstalling streamlink completly installed  pip3 install certifi
pipenv install "urllib3[secure]"
pipenv shell
and then reinstalled streamlink look smooth. will update if it still crash.

**Comment by maanich** [comment]
. . drew x  ?? lb.?.  vtc. t ?  7  7.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: back-to <notifications@github.com> Date: 06/07/2018  18:05  (GMT+00:00) To: streamlink/streamlink <streamlink@noreply.github.com> Cc: maanich <manigorgeous@gmail.com>, Author <author@noreply.github.com> Subject: Re: [streamlink/streamlink] Mjunoon plugin issue (#1907) 
you cut the logs where you opened the stream

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/streamlink/streamlink","title":"streamlink/streamlink","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/streamlink/streamlink"}},"updates":{"snippets":[{"icon":"PERSON","message":"@back-to in #1907: you cut the logs where you opened the stream"}],"action":{"name":"View Issue","url":"https://github.com/streamlink/streamlink/issues/1907#issuecomment-403092677"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/streamlink/streamlink/issues/1907#issuecomment-403092677",
"url": "https://github.com/streamlink/streamlink/issues/1907#issuecomment-403092677",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [streamlink/streamlink] Mjunoon plugin issue (#1907)",
"sections": [
{
"text": "",
"activityTitle": "**back-to**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@back-to",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1907,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"streamlink/streamlink\",\n\"issueId\": 1907\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/streamlink/streamlink/issues/1907#issuecomment-403092677"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353807670\n}"
}
],
"themeColor": "26292E"
}
]
