### ISSUE TITLE
douyu plugin broken

### ISSUE THREAD

**Issue by bupmc** [streamlink/streamlink#1909]
https://www.douyu.com/directory/subCate/yz/773
地址为http://9699.liveplay.myqcloud.com/live/9699_*
为了不浪费您的时间，连麦前的直播流不用中断。

**Comment by back-to** [comment]
some more details would be helpful and and please in English.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
https://raw.githubusercontent.com/streamlink/streamlink/master/.github/ISSUE_TEMPLATE/Plugin_Issue.md

**Comment by bupmc** [comment]
If english is my first language, I won't use chinese.
There is no 连麦 in recorded file, because 连麦 is in another stream, stream url is http://9699.liveplay.myqcloud.com/live/9699_*

**Comment by steven7851** [comment]
@bupmc 现在 streamlink 用的 API 没有连麦串流网址，新的 API 才有，但目前没有人解密出算法

**Comment by bastimeyer** [comment]
Please stick to English. This is an international community and it is almost impossible to properly moderate these kind of issues if you're not using English.

> But new API's sign algorithm is difficult to decrypt

So is this some kind of DRM?
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by bupmc** [comment]
您好，第一次尝试，提示403。
C:\save>"C:\Program Files (x86)\Streamlink\bin\streamlink.exe" https://www.douyu.com/4597051?cdn=ws mix -o "c:\00\4597051_20180813_1541_53_693.flv"
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/4597051?cdn=ws
[plugin.douyutv][info] Available cdns: ['ws', 'tct', 'ws2']
[plugin.douyutv][info] Now channel: 4597051, CDN: ws
[cli][info] Available streams: mix, low (worst), medium, high, source (best)
[cli][info] Opening stream: mix (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('http://9699.liveplay.myqcloud.com/live/9699_9ccfdec5fb936bc8e20813617243e931.flv?txSecret=4f191d08cef91e5799f9a9ee24d6285f&txTime=5b713783')> (Could not open stream: Unable to open URL: http://9699.liveplay.myqcloud.com/live/9699_9ccfdec5fb936bc8e20813617243e931.flv?txSecret=4f191d08cef91e5799f9a9ee24d6285f&txTime=5b713783 (403 Client Error: Forbidden for url: http://9699.liveplay.myqcloud.com/live/9699_9ccfdec5fb936bc8e20813617243e931.flv?txSecret=4f191d08cef91e5799f9a9ee24d6285f&txTime=5b713783))
error: Could not open stream <HTTPStream('http://9699.liveplay.myqcloud.com/live/9699_9ccfdec5fb936bc8e20813617243e931.flv?txSecret=4f191d08cef91e5799f9a9ee24d6285f&txTime=5b713783')>, tried 1 times, exiting

**Comment by bupmc** [comment]
感谢 取消代理正常了 奇怪ssr bypass china都不行

**Comment by back-to** [comment]
seems like all Livestreams from this category work now with the old API,
the other API is not required anymore.

**closing**

**Comment by bupmc** [comment]
@back-to this issue isn't solved, please open
@bastimeyer the title you changed to is wrong
