### ISSUE TITLE
405 Not allowed for AES-128 stream

### ISSUE THREAD

**Issue by jtechpro** [streamlink/streamlink#1910]
## Issue

- [x] I have read the contribution guidelines. 

### Description

I tried loading a live stream m3u8 which has AES-128 encryption with appropriate headers.
Streamlink tried to open the stream, but it is not able to pass the full parameters that is in the m3u8 file as a result I got 405 Not allowed error.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:5754
#EXT-X-TARGETDURATION:6
#EXT-X-KEY:METHOD=AES-128,URI="https://stream.xyz.com/live_stream/live_400-1830959036000.key?**jac**=7_8LB9JXvgix28Vr76VjUA&**pde**=1830967504&**st**=cyLKrjztJPXPgENepxYOwrWJJxDJHU8bW2h2dnvGimnZ-Po.*DmLcOHJa6039XSbQwCAo6JCIpteRIGQaZF9zl7RxkJLxADeEFFKdc54X*",IV=0x0000000000000000000001647444FE60
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964762000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964768000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964774000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964778000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964786000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964790000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964796000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964802000.ts
#EXTINF:6.000,
http://abc.xyz.com/live_stream/live_400-1830964810000.ts

```

I get the error 
**405: Not allowed for URL: 
stream.xyz.com/live_stream/live_400-1830959036000.key**

It is clear that the arguments jac, pde, and st are not passed to it

### Expected / Actual behavior

The whole url must pass along with its arguments i.e.

`https://stream.xyz.com/live_stream/live_400-1830959036000.key?**jac**=7_8LB9JXvgix28Vr76VjUA&**pde**=1830967504&**st**=cyLKrjztJPXPgENepxYOwrWJJxDJHU8bW2h2dnvGimnZ-Po.*DmLcOHJa6039XSbQwCAo6JCIpteRIGQaZF9zl7RxkJLxADeEFFKdc54X*`

instead of 

`https://stream.xyz.com/live_stream/live_600-1830959036000.key`

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
same as

https://github.com/streamlink/streamlink/issues/1557#issuecomment-373911892
https://github.com/streamlink/streamlink/issues/1906
