### ISSUE TITLE
Crunchyroll Plugin fails to load some links with error "error: Media lookup error: You don't have permission to do this."

### ISSUE THREAD

**Issue by mlindner** [streamlink/streamlink#1912]
streamlink http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883 -v
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883
[plugin.crunchyroll][info] Successfully logged in as 'censored'
error: Media lookup error: You don't have permission to do this.

**Comment by back-to** [comment]
**You will have to provide way more details**, use this template for plugin issues

https://raw.githubusercontent.com/streamlink/streamlink/master/.github/ISSUE_TEMPLATE/Plugin_Issue.md
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by mlindner** [comment]
There isn't any more information to provide. This is the full logs. I listed reproduction steps. I gave which plugin is affected.

**Comment by mlindner** [comment]
Here's a bit more (was unaware of the -l debug option) (I edited it to censor some info):

streamlink http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883 -l debug
[cli][debug] OS:         macOS 10.10.5
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883
[cli][debug] Plugin specific arguments:
[cli][debug]  --crunchyroll-username=******** (username)
[cli][debug]  --crunchyroll-password=******** (password)
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created with ID: ********
[plugin.crunchyroll][debug] Using saved credentials
[plugin.crunchyroll][info] Successfully logged in as 'ergZay'
error: Media lookup error: You don't have permission to do this.

**Comment by mlindner** [comment]
Here's some more info (I was unaware of the -l debug option) (I edited it to censor some fields):

streamlink http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883 -l debug
[cli][debug] OS:         macOS 10.10.5
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/cells-at-work/episode-1-pneumococcus-774883
[cli][debug] Plugin specific arguments:
[cli][debug]  --crunchyroll-username=******** (username)
[cli][debug]  --crunchyroll-password=******** (password)
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created with ID: ********
[plugin.crunchyroll][debug] Using saved credentials
[plugin.crunchyroll][info] Successfully logged in as '********'
error: Media lookup error: You don't have permission to do this.

**Comment by mlindner** [comment]
This is very easy to reproduce, please follow the steps I gave and any needed information can be easily obtained.

**Comment by beardypig** [comment]
@mlindner what region are you in?

**Comment by mlindner** [comment]
Continental United States (lower 48).

**Comment by beardypig** [comment]
OK, I will take a look when I can.

**Comment by mlindner** [comment]
To be clear, other links play without issue. Just specifically this one (at least so far that I've seen) has an issue.

**Comment by gravyboat** [comment]
@mlindner Can you try using the `--crunchyroll-purge-credentials` to see if you still get the same error?

**Comment by mlindner** [comment]
I had already tried that. It made no difference.

**Comment by mlindner** [comment]
I just tried playing the video again. It appears something changed on Crunchyroll's end and the video is now playable. I'm sure not coincidentally, it now also appears in http://www.crunchyroll.com/videos/anime/updated (from 1 day ago) when it did not before, but was still accessible directly from their page.

**Comment by mlindner** [comment]
If I see this again I'll report it again to this same issue (I suggest that its left open) and a reproduction is tried quickly.

**Comment by gravyboat** [comment]
@mlindner I'm going to close the issue for now since it seems to be an issue on their end. If it does crop up again we can just re-open the issue since it still accepts comments. Thanks for the update.

**Comment by mlindner** [comment]
To be clear, the video plays fine in their player even during this and others have managed to rip the stream during that period. So it's something that streamlink should be able to support.

**Comment by gravyboat** [comment]
@mlindner I thought your comment was referring to being able to play it with Streamlink, are you still unable to do so?

**Comment by mlindner** [comment]
No, I am now able to play it with streamlink. I was saying that I previously was unable to play it with streamlink despite it being playable with things that are not streamlink.

**Comment by gravyboat** [comment]
Ahh okay gotcha. Yeah I agree it should be playable, I'll open this back up and we can see if it crops up next week since we'll need to be able to duplicate it to troubleshoot anything.

**Comment by beardypig** [comment]
Sounds like a time sensitive thing, difficult to debug :)

**Comment by gravyboat** [comment]
I ran into this again as well for a show that's been out for several weeks. No additional details in the debug/trace log past what was provided already unfortunately. This was for: https://www.crunchyroll.com/en-gb/mob-psycho-100/episode-1-ripped-apart-someone-is-watching-780920
