### ISSUE TITLE
Can't open CCTV Live 

### ISSUE THREAD

**Issue by ScienceZone** [streamlink/streamlink#1920]
Why can't play this video? http://tv.cctv.com/live/

**Comment by johnthecracker** [comment]
I can't play it in Europe as well.

<a href='https://postimg.cc/image/mnuojht4n/' target='_blank'><img src='https://s15.postimg.cc/mnuojht4n/Screen_Shot.jpg' border='0' alt='Screen_Shot'/></a>

If you can get playlist, m3u8, it works.

<a href='https://postimg.cc/image/k6ixca6o7/' target='_blank'><img src='https://s15.postimg.cc/k6ixca6o7/Screen_Shot2.jpg' border='0' alt='Screen_Shot2'/></a>

Maybe this information helps.

**Comment by johnthecracker** [comment]
<a href='https://postimg.cc/image/y39j7ejo7/' target='_blank'><img src='https://s15.postimg.cc/y39j7ejo7/Screen_Shot.jpg' border='0' alt='Screen_Shot'/></a>

**Comment by johnthecracker** [comment]
``
[cli][info] Found matching plugin hls for URL http://cctv1-lh.akamaihd.net/i/cctv1_1@619500/master.m3u8?contentid=2820180516001
[cli][info] Available streams: 46k (worst), 360p, 540p (best)
[cli][info] Opening stream: 540p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
 ``

**Comment by ScienceZone** [comment]
Different URLs, different experiences！！It can play online, but it is said to use encryption. Flashplayer can play it, why  streamlink can't?

**Comment by back-to** [comment]
> Flashplayer can play it, why streamlink can't?

because there is no plugin

closing, as I don't know if you want one.

**Comment by johnthecracker** [comment]
@ScienceZone,

You can watch this broadcast on youtube:

https://www.youtube.com/embed/live_stream?channel=UCviqjOZN3ZvDEmZfHuUKCIQ

```
C:\>streamlink.exe --player=mpv.exe --http-no-ssl-verify "https://www.youtube.com/embed/live_stream?channel=UCviqjOZN3ZvDEmZfHuUKCIQ" best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/live_stream?channel=UCviqjOZN3ZvDEmZfHuUKCIQ
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: mpv.exe
```

Drop a comment if you have a way to play CNC World Live in a player:

http://www.xinhuanet.com/2015wlds/enindex.htm

https://github.com/back-to/generic/issues/4
