### ISSUE TITLE
plugin request for a (free) government channel

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#1922]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines. 

### Description
I want to record the live stream here : 
http://m.nexgtv.com/dd-ne.html
This is a free channel aired by Government of India. Although the streaming here is not done by the government, but some person. 
Also, is there any post on how can I make plugins on my own? I would like to learn that. 

P.S.: 
Using Streamlink since more than a year. And have learnt the basics of python in the last 2-3 months. (basics only) 

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH YOUR LOG
```

### Comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by rusty148** [comment]
@RosadinTV 
Could you please help me, like you did in https://github.com/streamlink/streamlink/issues/1222

**Comment by RosadinTV** [comment]
@rusty148 
Hi, i'm a little busy lately .. so the code is far for perfect but it should work.

**nexgtv.py**
```
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http, useragents
from streamlink.stream import HLSStream

class nexGTv(Plugin):
    _url_re = re.compile(r'https?://(?:www\.)?m.nexgtv.com/.+')

    @classmethod
    def can_handle_url(cls, url):
        return cls._url_re.match(url)

    def _get_streams(self):
        try:
            http.headers = {'User-Agent': useragents.ANDROID}
            url_content = http.get(self.url)
            http.cookies = url_content.cookies
            url_content_text = url_content.text
            authtoken = url_content_text[url_content_text.index('headers: {"authtoken": ')+24 :]
            authtoken = authtoken[: authtoken.index("'")]
            http.headers.update({'authtoken': authtoken})
            channel_id = url_content_text[url_content_text.index("getSecurePlayUrl('")+18 :]
            channel_id = channel_id[: channel_id.index("'")]
            hls_url = http.get("http://m.nexgtv.com/users/getsecureplayurl/" + channel_id).text
            hls_url = hls_url[hls_url.index('"finalUrl":"')+12 :]
            hls_url = hls_url[: hls_url.index('"')]
            hls_url = hls_url.replace("\/", "/")
            return HLSStream.parse_variant_playlist(self.session, hls_url)
        except:
            self.logger.error("The requested channel is unavailable.")

__plugin__ = nexGTv
```

**Comment by rusty148** [comment]
It's working, Thank you so much
