### ISSUE TITLE
URL Decode in --http-query-param

### ISSUE THREAD

**Issue by devwhatsapp** [streamlink/streamlink#1923]
Hi

HLS Stream

When adding a key value inside --http-query-param

The * changes into %2A and this causes the link to change completely which shows 404 not found or any other error.

How can this be fixed that the request sent out does not change * into %2A and keeps it * only.

Regards

**Comment by gravyboat** [comment]
Did you wrap the query param value in quotes?

**Comment by devwhatsapp** [comment]
Yes of course

**Comment by beardypig** [comment]
@devwhatsapp can you give an example of the `--http-query-param`?

**Comment by back-to** [comment]
This is the **normal** and the **expected behavior**,
see https://github.com/requests/requests/issues/3899

There is also a workaround  for this,
put the the query directly in the URL.

https://github.com/requests/requests/issues/3899#issuecomment-283223303

```
$ streamlink http://127.0.0.1 --http-query-param "foo=**"
error: Unable to open URL: http://127.0.0.1 (HTTPConnectionPool(host='127.0.0.1', port=80):
Max retries exceeded with url: /?foo=%2A%2A
```
```
$ streamlink http://127.0.0.1?foo=**
error: Unable to open URL: http://127.0.0.1?foo=** (HTTPConnectionPool(host='127.0.0.1', port=80):
Max retries exceeded with url: /?foo=**
```

**Comment by devwhatsapp** [comment]
So it says the server needs to be fixed to properly URL Decode special chars.

Thanks
