### ISSUE TITLE
0.1.0 for Windows not changed from 0.0.2?

### ISSUE THREAD

**Issue by cyluss** [streamlink/streamlink#193]
I guess packaging gone wrong.

Checked with 0.1.0 Windows installer downloaded from https://github.com/streamlink/streamlink/releases/tag/0.1.0.
Source codes are modified at 2016-10-13, which does not have changes for 0.1.0.
Also, fix for #120 is not included in installer.

**Comment by DragonzMaster** [comment]
I can confirm this, I have the same problem.

**Comment by beardypig** [comment]
Also confirmed. After upgrade `streamlink --version` reports `streamlink-script.py 0.0.2` and `streamlink.__version__` is `0.0.2`. 

@cdrage Did you run `python setup.py install` or `pip install .` before building the installer? I would recommend using a fresh `virtualenv` to build it.

**Comment by cdrage** [comment]
@beardypig Yeah, something may have gone wrong. Hence the reason why I created the PR: https://github.com/streamlink/streamlink/pull/187

I'll re-create it! Thank you :)

**Comment by gravyboat** [comment]
@cdrage Did you rebuild this yesterday and modify the release executable? I'm still seeing 0.0.2 like @beardypig did.

**Comment by cdrage** [comment]
@gravyboat @beardypig I've updated the release, can you guys double check that it's 0.1.0 now?

**Comment by gravyboat** [comment]
@cdrage I'll be able to tonight when I'm back on my Windows system, thanks!

**Comment by cyluss** [comment]
0.1.0 confirmed.

**Comment by gravyboat** [comment]
I can also confirm that I'm seeing 0.1.0. Thanks @cdrage.
