### ISSUE TITLE
teleboy.ch

### ISSUE THREAD

**Issue by teleboy5** [streamlink/streamlink#1936]
## Feature Request
Any idea (maybe challenging) to create plugin "teleboy" as seems similiar to zattoo, requires also account with email and password 
- teleboy-email=....
- teleboy-password=....

### Description
https://www.teleboy.ch/player/live

- HLS-streaming

### Additional comments, screenshots, etc.
- free account (prereq: Swiss IP)
- service georestricted to Schwitzerland

**Comment by bastimeyer** [comment]
Going to close this due to the lack of necessary information.
