### ISSUE TITLE
MTA channel live streams 

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#1937]
mta.tv
mta/live   https://ooyalahd2-f.akamaihd.net/i/mtaorigin_delivery@353498/index_3000_av-p.m3u8?sd=10&rebase=on
1- http://www.mta.tv/live
2- http://www.mta.tv/mta2live
3- http://www.mta.tv/mta3live
4- http://www.mta.tv/mta-africa
5- http://www.mta.tv/live-audio-only

if we can dd this to streamlink as all r free  and registered licenced streams offered by mta.tv
http://www.mta.tv/legal

**Comment by gravyboat** [comment]
Once again you have created an issue that doesn't meet the requirements of a plugin request after having been told to fill it out properly multiple times. In addition this is yet another request after we specifically asked you not to make so many. You have been requesting plugins while not providing enough details, saying you would fix it, and then doing nothing.

**Comment by maanich** [comment]
i read everything and stated the sthings which required as per my understanding. if i m still wrong please let me know as example wher ei am wrong. 5 r the streamlinks i added and the webiste and its free legal website with no restream or illegal streams.  need ur supoort regarding what i didnot follow in imy  request.

**Comment by gravyboat** [comment]
When you create a new request you need to use the correct template, the one labeled `plugin request`. There are a list of issue templates here (which are present immediately after clicking `New issue`: https://github.com/streamlink/streamlink/issues/new/choose

**Comment by maanich** [comment]
yeah i went to new issue then plugin request and added my details and removed the old informative content. this is what i did.

**Comment by maanich** [comment]
let me know i f i need to add some extra information.

**Comment by back-to** [comment]
**A plugin is not required**,
since you already found the m3u8 URL you can see there
that it does not need any special api or session calls.

Just use these URLs with the built in hls plugin or directly in VLC

`streamlink hls://URL best`
https://streamlink.github.io/cli.html#supported-streaming-protocols

**Comment by maanich** [comment]
thanks.

Raja Imran Aslam
