### ISSUE TITLE
I figured out the --twitch-oauth-authenticate error

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#194]
@cdrage I would say, needs to register Streamlink on Twitch http://i.imgur.com/4x3C0vt.jpg and put Name - Streamlink  Redirect URL - https://streamlink.github.io/twitch_oauth.html  then replace the Client ID in Twitch.py with the new Client ID then --twitch-oauth-authenticate  will correctly work

**Comment by cyluss** [comment]
Is this an extensive discussion on #190?

**Comment by thinkpad4** [comment]
Yes sorry, I got a little excited when I figured out the problem and made a new issue since the other one was closed

**Comment by gravyboat** [comment]
@thinkpad4 Do you want to close this one out and move the discussion back to #190 (and open it) then we keep everything in one place.

**Comment by thinkpad4** [comment]
Please, if it is not too much trouble.  Thanks

**Comment by gravyboat** [comment]
@thinkpad4 You can just close it out and copy paste over there if you want!

**Comment by thinkpad4** [comment]
@gravyboat now #190 just need to be reopened since I didn't close it

**Comment by gravyboat** [comment]
@thinkpad4 Odd, you should still be able to open it back up, either way I opened it. Thanks!
