### ISSUE TITLE
Subtitle Atresplayer

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#1940]
The video is downloaded without subtitle ¿Why?
```
streamlink https://geodeswowa3player.akamaized.net/vcg/_definst_/assets4/2018/07/06/83CCD249-2559-4D35-8454-C29093277ECA/hls.smil/playlist.m3u8?pulse=assets4%2F2018%2F07%2F06%2F83CCD249-2559-4D35-8454-C29093277ECA%2F%7C1531828036%7Cc2b9fe5f5ff7bf96437beace88c3d6a3 best --npo-subtitles -o "VOD.mp4"
```
the subtitle works for me when I open the playslist.m3u8 in vlc directly.

the master link of the subtitle in vtt (es_subt.vtt) format is set in the playlist.m3u8 , the subtitle It's cut into several parts (0.vtt, 1.vtt.......)

**Comment by beardypig** [comment]
The atresplayer plugin does not support subtitles at the moment. It could be added for hls streams in general.

**Comment by Toni195** [comment]
If I added it in hls I could download an video with subtitle just by putting the link atresplayer.com or would I have to put the playlist.m3u8 link?

**Comment by beardypig** [comment]
If subtitles were supported for HLS streams it would work with the atresplayer link.

**Comment by beardypig** [comment]
Correct, this would only be for HLS stream.

I find some of the options per stream type quite annoying. We should have `--audio-select` and `--mux-subtitles` and they just apply to all stream types (where supported and available) - but this is a separate issue :)

**Comment by Toni195** [comment]
This series has two audios (Spanish and English) and subtitled in Spanish, maybe there is more series, I don't know 100x100.
```
https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/
```

**Comment by Toni195** [comment]
```
streamlink https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-8-el-jezabel_5b3f9be87ed1a839c9fb9e0d/ best --player ffplay --hls-subtitle
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 17, in
 <module>
    from streamlink_cli.main import main
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 30,
 in <module>
    from streamlink.utils import LazyFormatter
ImportError: cannot import name 'LazyFormatter'
```

**Comment by beardypig** [comment]
You will need to update some more files as other things have changed since the last release. Best to install the latest version from git using pip (see the installation docs on how to do this).

**Comment by Toni195** [comment]
I don't know how to manually install streamlink via Python, I'm afraid that if I don't update the exe I'm going to be left with the desire to try it.

**Comment by beardypig** [comment]
If you install [streamlink-0.14.2-20180717.exe](https://bintray.com/streamlink/streamlink-nightly/download_file?file_path=streamlink-0.14.2-20180717.exe) and then update those files it should work.

**Comment by Toni195** [comment]
The video is downloaded with subtitle but does not match, however when viewed via streamlink in the player ffplay, vlc, etc.... gives codec error, also the word WEBVTT appears on screen when it should not appear, in the player atresplayer does not appear, the end of the first part is the same as the beginning of the second part of the subtitle so it is repeated on screen.

0.vtt
```
https://geodeswowa3player.akamaized.net/vcg/_definst_/assets7/2018/07/16/9C5AE9A3-7B8B-4922-9F2E-DF630DE21F7B/vtt/0.vtt
```

1.vtt
```
https://geodeswowa3player.akamaized.net/vcg/_definst_/assets7/2018/07/16/9C5AE9A3-7B8B-4922-9F2E-DF630DE21F7B/vtt/1.vtt
```

**Comment by beardypig** [comment]
Doesn't match? The subtitles are wrong?

**Comment by Toni195** [comment]
The subtitle is correct, I mean that in the atresplayer player this chapter ends on the minute 00:45:59 while the downloaded file the subtitle ends on the minute 00:43:12.

**Comment by beardypig** [comment]
@Toni195 have you tried a different player? I don't see WEBVTT in the output though, and it appears to work fine for me... perhaps the `ffmpeg` version bundled with streamlink is too old.

**Comment by Toni195** [comment]
Look at the capture, there is a phrase loop, the phrase loop does not appear in the atresplayer player and also the word WEBVTT appears.
https://i.imgur.com/Gxzyayr.png

**Comment by beardypig** [comment]
That is strange, I cannot reproduce this behaviour. Seems like it might be an `ffmpeg` issue. If you have another version of `ffmpeg` installed, you can point stream to that using the `--ffmpeg-ffmpeg` option. 

It worked for me with `2.8.14-0ubuntu0.16.04.1` and `4.0.1`.

**Comment by Toni195** [comment]
Try this command and then play the video with vlc, check the 29:57 minute, that's when the phrase is repeated and the word WEBVTT appears..
```
streamlink https://www.atresplayer.com/antena3/series/el-cuento-de-la-criada/temporada-1/capitulo-9-el-puente_5b4c74207ed1a86504a705cf/ best --hls-subtitles -o "VOD.mp4"
```

**Comment by beardypig** [comment]
@Toni195 I was able to reproduce your issue. However, it is quite difficult to fix.

**Comment by Toni195** [comment]
Invest your free time in more important things, in fact this problem, it's a shame that it can't be completely solved, I'll still be eternally grateful for it, friend.
