### ISSUE TITLE
Live-edge always delayed

### ISSUE THREAD

**Issue by NotYannickverc** [streamlink/streamlink#1942]
On Twitch.tv I can get a stable 2s latency to broadcaster, but Streamlink is always at least 10 seconds behind!

If I use hls-live-edge 1, it's still 3-5 seconds behind Twitch, AND it stutters! Meanwhile the Twitch player works flawlessly.. why can't Streamlink keep up?

**Comment by bastimeyer** [comment]
Because Twitch is using a custom, non-standardized version of the HLS streaming protocol for having a lower streaming delay. Streamlink doesn't support this yet.
Duplicate of #1676
