### ISSUE TITLE
QUESTION: Streamlink versions vs Python versions ana pip

### ISSUE THREAD

**Issue by markosjal** [streamlink/streamlink#1943]
First a big thank you for streamlink. ALthough I have had to learn a lot along the way it is a very useful tool in my arsenal.

I see "questions" posted here but do not see how to post a question.

My question has to do with streamlink versions vs python versions. 

I am using termux on android.

First not sure if I can legitimately have python 2 and 3 installed on same system.

If I install streamlink from pip2 with python 2 , I see during the install that a streamlink version 0.28.x is installed. This does not seem to conform to versions here at all. 

If I install streamlink from pip python3 , I see during the install that streamlink version 0.14.x is installed. I only assume that this is streamlink 14.x?

would these two streamlik versions have different capabilities? I run another script out of python 2 that does not seem to run from python 3 , so would like to use python 2 but if that gives me a less capable versin of streamlink I would like to know. 

The remaing part of this question has to do with updating streamlink via pip. Are new versions autmatically available via pip after updates propgate?

Maybe there is a place where all of this is already clarified??

**Comment by beardypig** [comment]
Updates are available via `pip`, regardless of the version of python. There is no streamlink `0.28.0`, are you sure it was streamlink? Under most usual conditions python 2 and 3 can coexist, I do not know about termux though.

**Comment by bastimeyer** [comment]
These are the available versions when installing Streamlink via pip:
https://pypi.org/project/streamlink/#history

What is the output of `pip show streamlink`, `which streamlink` and `streamlink --version`?

> would these two streamlik versions have different capabilities?

no

**Comment by bastimeyer** [comment]
No response. Going to close it...
