### ISSUE TITLE
[macOS] Error when trying to upgrade

### ISSUE THREAD

**Issue by Smultie** [streamlink/streamlink#195]
~ $ sudo pip install streamlink
The directory '/Users/Smultie/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Smultie/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: streamlink in /Library/Python/2.7/site-packages
Requirement already satisfied: futures in /Library/Python/2.7/site-packages/futures-2.2.0-py2.7.egg (from streamlink)
Requirement already satisfied: singledispatch in /Library/Python/2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg (from streamlink)
Requirement already satisfied: requests<3.0,>=1.0 in /Library/Python/2.7/site-packages/requests-2.5.1-py2.7.egg (from streamlink)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from singledispatch->streamlink)

What am I doing wrong?

**Comment by gravyboat** [comment]
I didn't get that error when I upgraded. Did you try `sudo pip install --upgrade streamlink`?

**Comment by DragonzMaster** [comment]
Use  `pip install https://github.com/streamlink/streamlink/archive/master.zip`

**Comment by beardypig** [comment]
It's just telling you it won't cache wheels because you're running pip as sudo, which it doesn't like for some reason... It's also telling you that streamlink is already installed and as @gravyboat suggested, you should use --upgrade to get the latest version.

**Comment by Brainzyy** [comment]
It worked for me on macOS with what @gravyboat suggested.

**Comment by beardypig** [comment]
@Smultie did you manage to update streamlink?

**Comment by Smultie** [comment]
Woops, sorry for my lack of feedback!
I did manage to update with the suggested solution!

**Comment by beardypig** [comment]
@Smultie excellent, I'll close this issue then :)

**Comment by Smultie** [comment]
Apparently I'm really dumb, cause once again I'm having troubles upgrading (or installing) for that matter on macOS.

When using 'sudo pip install https://github.com/streamlink/streamlink/archive/master.zip'
-- Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-sLvoL4/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RhlexV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-sLvoL4/pycryptodome/

When using 'sudo pip install --upgrade streamlink'
-- Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-SJp5ZX/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8syS2p-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-SJp5ZX/pycryptodome/

When using '
