### ISSUE TITLE
Python process stays after closing streamlink

### ISSUE THREAD

**Issue by chudy111** [streamlink/streamlink#1951]
Hi
I wrote an app in QT to play streams (on windows), but after i do process.kill() (which uses TerminateProcess) streamlink.exe is closed, but python process stays. I added debugging and this is what i got (logs are from my app which reads the process output)

16:38:27: [stream.hls][debug] Download of segment 7963 complete
16:38:27: [stream.hls][debug] Download of segment 7964 complete
16:38:27: [stream.hls][debug] Download of segment 7965 complete
16:38:27: [stream.hls][debug] Download of segment 7966 complete
16:38:27: [console][info] HTTP connection closed
16:38:27: [stream.segmented][debug] Closing worker thread
16:38:27: [stream.segmented][debug] Closing writer thread
16:38:27: [console][info] Stream ended

so nothing really interesting here.

I tried using process.terminate() which posts WM_CLOSE message, but then streamlink.exe doesn't close and python process also stays.

Maybe someone else had similar issue?

**Comment by bastimeyer** [comment]
Which `streamlink.exe` is this? The one generated by pip, Streamlink's Windows installer or Streamlink portable?

If you're writing an application which runs Streamlink as a child process, it might be wiser to execute `python.exe` (`pythonw.exe`) instead and use `streamlink-script.py` as first parameter. Sending SIGTERM/SIGINT/SIGKILL/etc to the python process will work 100%.

**Comment by chudy111** [comment]
streamlink.exe is from windows installer.

When i try to use streamlink-script.py from the bin directory i get following errors:
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\streamlink.exe\__main__.py", line 5, in <module>
  File "c:\python\lib\site-packages\streamlink_cli\main.py", line 26, in <module>
    from streamlink.stream import StreamProcess
  File "c:\python\lib\site-packages\streamlink\stream\__init__.py", line 6, in <module>
    from streamlink.stream.hls import HLSStream
  File "c:\python\lib\site-packages\streamlink\stream\hls.py", line 6, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

if from streamlink directory, i get:
C:\Program Files (x86)\Streamlink>python bin\streamlink-script.py https://www.twitch.tv/urqueeen best
Traceback (most recent call last):
  File "bin\streamlink-script.py", line 17, in <module>
    from streamlink_cli.main import main
  File "pkgs\streamlink_cli\main.py", line 26, in <module>
    from streamlink.stream import StreamProcess
  File "pkgs\streamlink\stream\__init__.py", line 6, in <module>
    from streamlink.stream.hls import HLSStream
  File "pkgs\streamlink\stream\hls.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "pkgs\Crypto\Cipher\__init__.py", line 78, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "pkgs\Crypto\Cipher\_mode_ecb.py", line 46, in <module>
    """
  File "pkgs\Crypto\Util\_raw_api.py", line 168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

i also tried with pip version but had the same issue with:
ModuleNotFoundError: No module named 'Crypto'

**Comment by bastimeyer** [comment]
> from windows installer
> `python bin\streamlink-script.py`

Then you also have to use the bundled python executable and libs from the Windows installer directory and not your system's own/different python environment which is being used when you simply run `python`.

**Comment by chudy111** [comment]
Oh yes, that worked like a charm. 

Thank you very much :)

**Comment by bastimeyer** [comment]
Ok, good, no problem.
Can this issue be closed then?

**Comment by chudy111** [comment]
sure
