### ISSUE TITLE
ceskatelevize plugin broken

### ISSUE THREAD

**Issue by remek30** [streamlink/streamlink#1955]
the plugin ceskatelewize.py has not been working for several days. When you try to enable any channel from this plugin, there is only the "OFFLINE" screen. I would like to ask you to fix this plugin.

**Comment by beardypig** [comment]
@remek30 

> Logs are always required for a plugin issue, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l) and avoid using `--stream-url` as that will suppress log output.

**Comment by remek30** [comment]
@beardypig 
I would like to ask you for help. What command should I issue through PUTTY to get logs. I have little knowledge and I can not cope alone.

**Comment by remek30** [comment]
Here are my logs : 


openpli 6.2-release vuultimo4k

vuultimo4k login: root
Last login: Thu Jul 26 15:08:20 CEST 2018 on pts/0
root@vuultimo4k:~#
root@vuultimo4k:~# /usr/sbin/streamlinksrv manualstart
pidfile /var/run/streamlink.pid does not exist. Daemon not running?
[streamlinksrv][info] Thu Jul 26 15:14:42 2018 Server (1.0.7) started
[streamlinksrv][info] Host:          vuultimo4k
[streamlinksrv][info] Port:          8088
[streamlinksrv][info] OS:            Linux-3.14.28-1.12-armv7l-with-glibc2.4
[streamlinksrv][info] Python:        2.7.12
[streamlinksrv][info] Streamlink:    0.14.2 / 06.07.2018
[streamlinksrv][info] Requests(2.11.1), Websocket(0.44.0)
[streamlinksrv][info] Processing URL: http://www.ceskatelevize.cz/ct24
[streamlinksrv][info] Found matching plugin ceskatelevize for URL http://www.ceskatelevize.cz/ct24
[streamlinksrv][error] Plugin error: Unable to open URL: https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=04ec70b2d01ad80b233877174eee9d259ffb644c&contentType=live&expiry=1532614498&id=2402&playerType=flash&quality=web&region=1&skipIpAddressCheck=false&userId=f4a70f9b-bb5b-4cf1-87bb-4e8ab1d1242b (("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",))
[streamlinksrv][info] Processing URL: http://decko.ceskatelevize.cz/zive
[streamlinksrv][info] Found matching plugin ceskatelevize for URL http://decko.ceskatelevize.cz/zive
[streamlinksrv][error] Plugin error: Unable to open URL: https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=cd7dc5ebab7965370e7733997814926319323812&contentType=live&expiry=1532614511&id=502&playerType=flash&quality=web&region=1&skipIpAddressCheck=false&userId=838a124c-6c15-48e6-9678-55cb1156546c (("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",))
[streamlinksrv][info] Processing URL: http://www.ceskatelevize.cz/art/zive
[streamlinksrv][info] Found matching plugin ceskatelevize for URL http://www.ceskatelevize.cz/art/zive
[streamlinksrv][error] Plugin error: Unable to open URL: https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=11b6607e77c632e3a4796e5866b2441e386dbf72&contentType=live&expiry=1532614517&id=602&playerType=flash&quality=web&region=1&skipIpAddressCheck=false&userId=61fe9445-4250-4459-9c06-1c8d1753a43f (("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",))

**Comment by beardypig** [comment]
Have you tried adding the `--http-no-ssl-verify` option? As you are using `streamlinksrv` I do not know how you do that, you should ask the author of that script :)

**Comment by remek30** [comment]
how to add this option  to this link : 


#SERVICE 4097:0:1:65:1:48:0:0:0:0:http%3a//127.0.0.1%3a8088/q=720p/https%3a//ct24.ceskatelevize.cz/#live:ČT24 HD
#DESCRIPTION ČT24 HD
