### ISSUE TITLE
plugin request

### ISSUE THREAD

**Issue by kark445** [streamlink/streamlink#1956]
## Issue

- [x] This is not a bug report, feature request, or plugin (improvement) request.
- [ ] I have read the contribution guidelines. 

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
```
https://opus.re/iptv-english-tv-channels

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
First, this is not a proper plugin request what you have submitted here.
Second, this is an illegal streaming platform which only lists stolen content.
Closing...
