### ISSUE TITLE
OPENREC plugin broken

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink#1960]
The following command no longer works:

streamlink openrec.tv/live/ddsEf14ETTVFl  <-- random url

Even though the stream is live it will say "no playable streams found".
It seems like openrec has changed something. Could someone please take a look? 

Thank you

**Comment by beardypig** [comment]
@jstrat231 This does not conform to the Plugin issue template

> Logs are always required for a plugin issue, use `-l debug` [(help)](https://streamlink.github.io/cli.html#cmdoption-l) and avoid using `--stream-url` as that will suppress log output.

**Comment by jstrat231** [comment]
I'm not quite sure what these -1 debug options mean.
If I was to modify the link mention in the OP how would I do it with your recommendation?

**Comment by beardypig** [comment]
@happapa `-l debug` will give useful information to us, that is why we ask for it. For example version of streamlink, operating system, various library versions, and perhaps some information about the plugin error. 

@jstrat231 run streamlink again but add `-l debug` to the command: eg. `streamlink -l debug http://... best`.

**Comment by jstrat231** [comment]
Seem to be getting the following error:
https://imgur.com/a/dgF7cX2

That streamer is currently live but no whatever what I type, it keeps saying "no playable streams found"/

OpenRec recently made big changes to their website and player so I wouldn't be surprised if it somehow broke the previous plugin. Everything was working fine before the website changes.

**Comment by jstrat231** [comment]
My bad.

Just tried this livestream of PUBG with the -l and got the same no playable streams found:
https://www.openrec.tv/live/Ved7VSqUVVC

Doesn't seem to provide any additional info. Just says "searching the page for live stream URLS" followed by no playable streams found.

**Comment by beardypig** [comment]
@jstrat231 it may not look like it provides any useful information, but it does for us. So please include the logs :)

**Comment by beardypig** [comment]
@ydixon you’re using a pretty old version of streamlink, you should update it. However, the last change was February 2017 so I imagine it’s stillness broken. Always best to use the latest version though.

**Comment by ydixon** [comment]
```
[root@localhost ~]$ streamlink -l debug https://www.openrec.tv/live/4jbzAvK5Or8 best
[cli][debug] OS:         Linux-4.14.18-300.fc27.x86_64-x86_64-with-fedora-27-Twenty_Seven
[cli][debug] Python:     2.7.14
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin openrectv for URL https://www.openrec.tv/live/4jbzAvK5Or8
[plugin.openrectv][debug] Searching the page for live stream URLs
error: No playable streams found on this URL: https://www.openrec.tv/live/4jbzAvK5Or8
```
My apologies, I was using my own script for this week before it failed. I just updated streamlink, this is the log.

**Comment by beardypig** [comment]
@ydixon thanks. I’ll take a look tomorrow and let you know.

**Comment by beardypig** [comment]
@ydixon it should be fix in #1968. 

You can [side-load](https://streamlink.github.io/cli.html#sideloading-plugins) the new plugin ([openrectv.py](https://raw.githubusercontent.com/beardypig/streamlink/openrectv-fix/src/streamlink/plugins/openrectv.py)) if you want to test it out.

**Comment by ydixon** [comment]
@beardypig  I didn't know there was an API (not much info from google), probably due to lack of knowledge of Japanese. I ended up using wireshark to find the m3u8 url.

I am not a web programmer, I always wondered how to perform tasks such as auto-login, finding these login forms, search through javascript generated data. It seemed so trivial and easy for you considering the speed you solved this problem. Which knowledge domain (keywords to google/links) should I study to get a good hang of this?

Sorry for going a bit off topic. I'll test the plugin when I get home. Thanks for the work.

**Comment by happapa** [comment]
I don't think the plugin should require login. Even when logged out, I can easily find the stream playlist by searching for "m3u8" in the raw html source.

**Comment by beardypig** [comment]
@ydixon I gathered all the information needed to update the plugin using the development tools in my browser. It is simple to inspect what the browser does when you perform certain actions, eg. play a video, or login. For that you just re-create what the browser did, eg. for login you just need to post the username and password, etc.

@happapa please provide a counter example.

**Comment by happapa** [comment]
@beardypig 
For [this stream](https://www.openrec.tv/live/mENfxqvRMrI) (currently live), the raw html has a block called `<script id='ssr-script'>` which contains this playlist `https://d3cfw2mckicdfw.cloudfront.net/891d1564a3b00fab4181f52ae58d0a94a818ff0530/playlist.m3u8`. Giving this playlist directly to streamlink bypasses the plugin and plays the stream just fine. I viewed the page logged out and in private browser tab, so it shouldn't require login.

**Comment by beardypig** [comment]
@happapa cool. I have updated the plugin to avoid requiring the login details.

**Comment by ydixon** [comment]
Right, you only need to login for downloading archived videos. Not sure if its under the scope of streamlink.

**Comment by beardypig** [comment]
@ydixon everything should be supported with the latest plugin, if it's not I'll see if I can fix it :)
