### ISSUE TITLE
Problem Plugin Raireplay

### ISSUE THREAD

**Issue by Jigsaw10** [streamlink/streamlink#1976]
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.

### Description

I have problem used up until yesterday it worked the plugin now no longer goes you have news thanks to everyone

### Reproduction steps / Explicit stream URLs to test

```
streamlink -ldebug  https://www.raiplay.it/dirette/rai1 best
```

### Log output

```
$ streamlink -ldebug  https://www.raiplay.it/dirette/rai1 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[plugin.raiplay][debug] Found channel: rai1
error: Failed to parse playlist: Missing #EXTM3U header
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
@Jigsaw10 

These Livestreams are **only available in Italy**.

Try it in your Browser https://www.raiplay.it/dirette/rai1 ,
it will also not work.

```
$ streamlink https://www.raiplay.it/dirette/rai1
[cli][debug] OS:         Linux
[cli][debug] Python:     3.5.5
[cli][debug] Streamlink: 0.14.2+60.gb84dc88.dirty
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[plugin.raiplay][debug] Found channel: rai1
[cli][info] Available streams: 288p (worst), 396p, 522p (best)
[cli][info] Opening stream: 522p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 302874; Last Sequence: 302876
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 302874; End Sequence: None
[stream.hls][debug] Adding segment 302874 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 302875 to queue
[stream.hls][debug] Adding segment 302876 to queue
[stream.hls][debug] Download of segment 302874 complete
[cli][info] Starting player: /usr/bin/mpv
[cli.output][debug] Opening subprocess: /usr/bin/mpv --title "Unknown Title" -
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 302877 to queue
[stream.hls][debug] Download of segment 302875 complete
[stream.hls][debug] Reloading playlist
```

**Comment by back-to** [comment]
@Jigsaw10 

well try a different IP, your IP is blocked or not detected as an Italian IP

---

what does this command return for you

```
curl "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=45&pl=mon,native"
```

or **if you don't have curl installed**

```
python -c "import requests;print(requests.get('https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=45&pl=mon,native').text)"
```

probably this or ?

```xml
<url type="content">http://download.rai.it/video_no_available.mp4</url>
```

**Comment by Jigsaw10** [comment]
hi back.to

<Mediapolis>
<url type="content">http://download.rai.it/video_no_available.mp4</url>
<url type="bumper"></url>
<url type="bumperend"></url>
<ct></ct>
<bitrate></bitrate>
<smooth>N</smooth>
<is_live>N</is_live>
<description>Rai</description>
<geoprotection>N</geoprotection>
<category></category>
<plVod></plVod>
<plLive></plLive>
<logo></logo>
<poster></poster><duration></duration>
<krpano></krpano>
<channel></channel>
<ads_tecnico></ads_tecnico>

**Comment by Jigsaw10** [comment]
@back-to 
curl "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803&output=45&pl=mon,native"
<Mediapolis>
<url type="content">http://download.rai.it/video_no_available.mp4</url>
<url type="bumper"></url>
<url type="bumperend"></url>
<ct></ct>
<bitrate></bitrate>
<smooth>N</smooth>
<is_live>N</is_live>
<description>Rai</description>
<geoprotection>N</geoprotection>
<category></category>
<plVod></plVod>
<plLive></plLive>
<logo></logo>
<poster></poster><duration></duration>
<krpano></krpano>
<channel></channel>
<ads_tecnico></ads_tecnico>

**Comment by back-to** [comment]
your IP is blocked or not detected as italian,
nothing Streamlink can do about it.

closing

**Comment by robustini** [comment]
Raspberry 3, streamlink installed with "sudo apt install streamlink".
The result for this channel:

streamlink -ldebug  https://www.raiplay.it/dirette/rai1 best
[cli][debug] OS:         Linux-5.10.92-v8+-aarch64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/rai1.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803
[utils.l10n][debug] Language code: en_US
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 33, in <module>
    sys.exit(load_entry_point('streamlink==2.0.0', 'console_scripts', 'streamlink')())
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1052, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 580, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 459, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/usr/lib/python3/dist-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/raiplay.py", line 49, in _get_streams
    yield from HLSStream.parse_variant_playlist(self.session, stream_url).items()
  File "/usr/lib/python3/dist-packages/streamlink/stream/hls.py", line 493, in parse_variant_playlist
    if not default_audio and (media.autoselect and locale.equivalent(language=media.language)):
  File "/usr/lib/python3/dist-packages/streamlink/utils/l10n.py", line 155, in equivalent
    equivalent = equivalent and (not language or self.language == self.get_language(language))
  File "/usr/lib/python3/dist-packages/streamlink/utils/l10n.py", line 169, in get_language
    return Language.get(language)
  File "/usr/lib/python3/dist-packages/streamlink/utils/l10n.py", line 73, in get
    return Language(lang.alpha_2, lang.alpha_3, lang.name, getattr(lang, "bibliographic", None))
  File "/usr/lib/python3/dist-packages/pycountry/db.py", line 29, in __getattr__
    raise AttributeError
AttributeError

**Comment by bastimeyer** [comment]
> Streamlink: 2.0.0

out of date

https://streamlink.github.io/install.html

also please don't comment on old threads. If there's an issue with the **most recent version**, which is currently 3.1.1, then please open a new issue or comment on an already open one.
