### ISSUE TITLE
mycujoo.tv plugin request

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#1981]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

[mycujoo.tv](https://mycujoo.tv/) is a free online streaming website for smaller football (soccer) league/tournaments around the world that want to broadcast their matches online. A large number of domestic leagues, plus tournaments and football variants such as beach football are included.

There is no geo-blocking on their website, and its a great site for watching grassroots, amateur and semi-pro football.

### Example stream URLs

1. https://mycujoo.tv/video/beach-soccer?id=22792 (live stream starts in 35 min of this posting)
2. https://mycujoo.tv/video/guamfa?id=22868 (vod of a just completed match)
3. https://mycujoo.tv/calendar (link to all upcoming streams)

**Comment by back-to** [comment]
Not worth for a new plugin.
