### ISSUE TITLE
wwe network help

### ISSUE THREAD

**Issue by rellik31** [streamlink/streamlink#1983]
hello, can someone please type out the command in the correct order to be able to download videos in .mp4 format if someone can type it out for the 720p stream and just tell me how and where to type my email & password and if ffmpeg is need 

thank you

**Comment by rellik31** [comment]
hi, i have now worked out how to download them but there mpeg-ts files how do i mux it to a real mp4?
what command do i use for ffmpeg?

thanks

**Comment by back-to** [comment]
here are some **examples** how ffmpeg can be used

https://github.com/streamlink/streamlink/issues/1527#issuecomment-370151934

**Comment by gravyboat** [comment]
I'm going to close this. @back-to has provided some direction to go in but we aren't going to be able to provide support for ffmpeg.

**Comment by HammadWH** [comment]
> 
> 
> hi, i have now worked out how to download them but there mpeg-ts files how do i mux it to a real mp4?
> what command do i use for ffmpeg?
> 
> thanks

how can u get MPG.ts Files from WWE Network bro
