### ISSUE TITLE
stream name is inconsistent for dash dynamic playlists

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1984]
## Bug / Feature Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

A dash dynamic playlist has **different bandwidths** all the time,
which makes the stream name inconsistent.

If you want to switch to the dash stream you can't guess the stream name.

`streamlink URL 2500k,2400k` would be easier than `2500k,2499k,2498k ...`

It is not a big issue for streams with only one stream,
but if you want the lower stream there is a big chance that you won't guess the right stream name.

### Expected / Actual behavior

**V**ideo and **A**udio bandwidth from `self.bandwidth`
https://github.com/streamlink/streamlink/blob/71a327ae4c053ddda0f842c3f0e38ddac3e31c4f/src/streamlink/stream/dash_manifest.py#L559

1. Actual behavior

```
V 2514.252
A 61.436

[cli][info] Available streams: 2514k
```

1. **Expected**

```
V 2500.0
A 60.0

[cli][info] Available streams: 2500k
```

---

2. Actual behavior

```
V 2433.165
A 61.439

[cli][info] Available streams: 2433k
```

2. **Expected**

```
V 2400.0
A 60.0

[cli][info] Available streams: 2400k
```

### Reproduction steps / Explicit stream URLs to test

1. DASHStream from https://ltv.lsm.lv/lv/tieshraide/visiemltv.lv/live.1480/

### Additional comments, screenshots, etc.

**The bandwidth should be rounded,**

here is an **example** of how it could be rounded,
but it is a bit long and maybe it could be shortened.

```py
        x = self.bandwidth
        if x >= 1000:
            x = round(x, -2)
        elif 1000 > x <= 100:
            x = round(x, -1)
        else:
            x = round(x)
```

it could be added to

https://github.com/streamlink/streamlink/blob/71a327ae4c053ddda0f842c3f0e38ddac3e31c4f/src/streamlink/stream/dash_manifest.py#L559

or

https://github.com/streamlink/streamlink/blob/71a327ae4c053ddda0f842c3f0e38ddac3e31c4f/src/streamlink/stream/dash.py#L204-L206

**Comment by beardypig** [comment]
I'll added a rounded bandwidth attribute or something.

**Comment by oxxxxxo** [comment]
@back-to
Please check the plugin rtve, it does not work,

**Comment by beardypig** [comment]
@oxxxxxo do not post off topic comments, you already posted twice about the `rtve` plugin. If you have an issue with it, create a new issue.
