### ISSUE TITLE
picarto updated streamlink no longer works

### ISSUE THREAD

**Issue by bluesaphiresky** [streamlink/streamlink#199]
Hey guys picarto no longer works because they said they updated the player so html5 can be default soon.
when you run  the program it says found matching plugin picarto for url https:// https://picarto.tv/picknamehere
then the it says error: no stream on this URL: https://picarto.tv/picknamehere.
thanks guys for the awesome program hopefully it gets solved soon!

**Comment by Keisonne** [comment]
I'm glad im not the only one have the same problem, picarto also no longer works for me.
