### ISSUE TITLE
Teleboy.ch

### ISSUE THREAD

**Issue by AdamNo** [streamlink/streamlink#1990]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
almost all german speaking tv channels at one site: https://www.teleboy.ch/player/live.
- Germany
- Austria
- Swiss

plus, it has also News, Kids, Comedy and other english speaking TV stations.
Over > 100 Channels!

Having a plugin for teleboy would be great!

### Example stream URLs

1. https://www.teleboy.ch/player/live/255/itv2 
2. https://www.teleboy.ch/player/live/351/4plushd
3. https://www.teleboy.ch/player/live/356/rtlchhd

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by dreamboxco** [comment]
There is no teleboy for streamlink ?

**Comment by AdamNo** [comment]
check out zatto

**Comment by cbadoud** [comment]
The quality of teleboy is much higher! I also would like to have this plugin implemented! Thanks!

**Comment by gravyboat** [comment]
We aren't adding any additional sources that are just TV restreams: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
