### ISSUE TITLE
macOS 10.13 - Unable to install Streamlnk (pip or easy_install)

### ISSUE THREAD

**Issue by Phoenix100k** [streamlink/streamlink#1991]
## Issue

- [x] This is not a bug report, feature request, or plugin (improvement) request.
- [x] I have read the contribution guidelines. 

### Description

macOS 10.13 (High Sierra) fresh install. Using sudo -H to easy_install Streamlink fails with setup script errors. Decided to try Python installation method with sudo -H instead though unfamiliar with Python. Had to install several prerequisites, got to a point where six package needed to be updates but denied being updated due to being a distutils project and finally gave up because I have no idea what I'm doing.

### Expected / Actual behavior

Expecting easy_install and python pip install to install streamlink, both fail with errors.

### Reproduction steps / Explicit stream URLs to test

1. `sudo -H easy_install -U streamlink`
2. `sudo -H pip install streamlink` (after installing latest python and dependencies that I know of)
3. ...

### Logs

When using easy_install:
```
Reading https://pypi.python.org/simple/streamlink/
Best match: streamlink 0.14.2
Downloading https://files.pythonhosted.org/packages/04/cc/3ce3dfa6fa485c3e06c6e12ec585357b6e08b24000401541dcb30e8e9e22/streamlink-0.14.2.tar.gz#sha256=a8c7f9a758ade056a35d439f78408e9e43ce1069dde9289d322702d35c214150
Processing streamlink-0.14.2.tar.gz
Writing /tmp/easy_install-GKmqqJ/streamlink-0.14.2/setup.cfg
Running streamlink-0.14.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-GKmqqJ/streamlink-0.14.2/egg-dist-tmp-jCPXc2
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
error: Setup script exited with error in streamlink setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in futures;python_version<"3.0" at ;python_version<"3.0"
```

When using pip:
```
pyopenssl 18.0.0 has requirement six>=1.5.2, but you'll have six 1.4.1 which is incompatible.
Installing collected packages: pyOpenSSL, certifi, urllib3, pycryptodome, PySocks, singledispatch, backports.shutil-which, isodate, backports.shutil-get-terminal-size, futures, iso-639, iso3166, websocket-client, chardet, requests, streamlink
  Found existing installation: pyOpenSSL 0.13.1
Cannot uninstall 'pyOpenSSL'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

When trying to upgrade pyOpenSSL or six:
```
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

### Additional comments, screenshots, etc.
I hope this was enough information. I'm not a programmer by any stretch of the imagination, but I love using Streamlink on Windows.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Try updating pip via `pip install --upgrade pip` then see if you can get the update for the dependencies.

**Comment by Phoenix100k** [comment]
Good thought, but this was the result:
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages (18.0)

**Comment by back-to** [comment]
@Phoenix100k 

this is because of a change in `pip 10` 
> pip cannot properly uninstall packages installed by "pure" distutils, because distutils doesn't record enough metadata

https://github.com/pypa/pip/issues/5247#issuecomment-381550610
https://github.com/pypa/pip/issues/4805

---

there are some solutions that could work

```
python -m pip install -U streamlink
```
(might need to change **python** to **python2** **python27** ...)

or just for six `python -m pip install -U six`

---

there is also

```
--ignore-installed
```

for **pip**

---

you can also use a virtual environment,
_might be not that usefull if it is not configured correctly_
https://streamlink.github.io/install.html#installing-without-root-permissions

---

there is also a Homebrew package

https://streamlink.github.io/install.html#other-platforms

**Comment by kikuyan** [comment]
Which version of setuptools are you using?
If you are using macOS bundle version 18.5, update setuptools and try.
You can see the version like this:
`python -c "import setuptools; print(setuptools.__version__)"`

Though I'm not using easy_install or pip, I had a similar error to your easy_install log when installing streamlink-0.14.0 before.
I updated setuptools to 39.2.0 at that time and could successfully install streamlink.
