### ISSUE TITLE
I had to leave

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#1992]
Thank you for allowing me the opportunity to be part of this awesome project.
After almost two years i have to leave for personal reasons. 
Best wishes.
❤️

**Comment by gravyboat** [comment]
Thanks for all your help @RosadinTV! Contributors like you are what make this project amazing and we appreciate all the time you've dedicated! Best of luck out there.

**Comment by jalba69** [comment]
Sad to hear that, I hope everything is well for you, wish you the best for the future.

Thank you very much for all you done.

**Comment by RosadinTV** [comment]
Update: Today I will definitely leave the project.
Best wishes ❤️
