### ISSUE TITLE
TeleclubZoom.ch

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#1993]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

[Teleclub Zoom](https://www.teleclubzoom.ch/), being a part of [Teleclub TV network](https://de.wikipedia.org/wiki/Teleclub), is a free TV station, which internet streaming is restricted to Swiss IPs.

### Example stream URLs

I can't really get the direct url to the streaming popup because it's hidden under the Javascript button "WATCH NOW!" (see below for the sreenshot). Looking through the page source gives me [this url](https://media10.simplex.tv/content/765/4041/57419/index.html) but I'm not sure if it's not a temporary one.

### Additional comments, screenshots, etc.

Here's a screenshot of the top of the page showing the button for the player:

![](https://i.imgur.com/9e9vtp8.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by 097115** [comment]
Also, its broadcasting is not 24/7, and for example today, on the 5 of August, it starts at 12:30 CET. So, in order to check the stream, checking its [schedule](https://www.teleclubzoom.ch/programm/) beforehand may be helpful.

**Comment by back-to** [comment]
@097115 

Are there any benefits compare to the stream on Zattoo? _(quality, format ...)_

https://zattoo.com/watch/teleclub_zoom

**Comment by 097115** [comment]
Zattoo looks nice, thanks. However, it can't be tricked with `--http-header "X-Forwarded-For=SomeSwissIP"` as far as I can tell :).
