### ISSUE TITLE
clarify which Streamlink Plugins are supported

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#1997]
## Issue

- [x] This is not a bug report, feature request, or plugin (improvement) request.
- [x] I have read the contribution guidelines. 

### Description

Ref https://github.com/streamlink/streamlink/pull/1972#issuecomment-410530312

Having Plugins in the **master branch** which won't receive any updated when they break
does not make that much sense.

**They should all be removed,** if they are not supported for any future updates.

---

Here is a list of some plugins that might not match this

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

and could be removed.

---

**This issue is there to decide**
- if they should be removed
- which should be removed
- which can stay (for example some of the broken plugins at the end)

---

> Sites which are hosting stolen content as their main source of content

- Aliez
- ArconaiTv
- SeeTV
- StreamBoat
- Weeb

---

> NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
- bongacams
- Cam4
- Camsoda
- Chaturbate

---

> Sites which are mostly hosting VODs (stolen or legitimate)

- Antenna (broken old plugin)
- Dplay (broken old plugin, youtube-dl could be for this if someone wants this)

of course there are more, but this sentence should probably been changed if the other should stay.

https://raw.githubusercontent.com/streamlink/streamlink/master/docs/plugin_matrix.rst

---

old plugins that are broken,
which most likely won't get fixed in the near future
some of them might work with youtube-dl.

- Aftonbladet
- BritTV
- Expressen
- Mips
- VGTV

---

useless plugins
- SpeedRunsLive (twitch could be used directly)

**Comment by beardypig** [comment]
@back-to for SpeedRunsLive, it already hands off to the twitch plugin. What do you that "twitch could be used directly"?

**Comment by back-to** [comment]
I mean it is just used to redirect a username without doing anything else,
wouldn't really call it a needed plugin.

`https://www.twitch.tv/USERNAME` can be used directly,
or if the domain is really wanted the **url_re** could be just added in **twitch.py** instead of its own file.

**Comment by gravyboat** [comment]
Had some time to review these this morning. I'm fine with removing all of these. I also agree about SpeedRunsLive since it's just a Twitch redirect and I've stated before that I don't like sites which "rehost" content since it's pointless and makes Streamlink slower. Regarding the broken plugins, if no one has opened an issue regarding the fact they are broken I don't see any reason to keep them. Since we don't collect any sort of plugin usage statistics it's hard to say what is in use but this list looks good to me.

**Comment by beardypig** [comment]
@johnthecracker there are ~190 plugins, removing 17 is hardly just leaving Twitch and hlsvariant (not sure what you mean by that exactly)...

**Comment by spencerthayer** [comment]
I don't understand why was Arconaitv removed @back-to and @gravyboat. Can you explain?

**Comment by bastimeyer** [comment]
> > Sites which are hosting stolen content as their main source of content
> 
> * ArconaiTv

**Comment by johnthecracker** [comment]
You don't need plugin for site like ArconaiTV
```
[cli][info] Found matching plugin hls for URL https://videoserver1.org/live/CdTJvwxa0gVbSibBRF_3oA/1580345100/03c66ee368fa1cc51798648a72e7be15.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: mpv.exe
```

**Comment by spencerthayer** [comment]
@bastimeyer what is wrong with stolen content? I don't see how that's relevant to the function of Streamlink.

**Comment by spencerthayer** [comment]
I don't understand @johnthecracker, when I type `streamlink https://www.arconaitv.us/stream.php\?id\=192` for example I get `error: No plugin can handle URL: https://www.arconaitv.us/stream.php?id=192`.

**Comment by johnthecracker** [comment]
Get playlist .m3u8 in some way, depending on your skills. http sniffer, script..
For this example I used firefox extension "the stream detector".

**Comment by gravyboat** [comment]
@spencerthayer We've taken the stance these sites are not worth supporting and their plugins aren't worth maintaining. It adds too much work for us without providing enough gain and many of the users who requests these types of sites are very demanding and don't contribute in any way. People can always fork or manually side load plugins if they want to.
