### ISSUE TITLE
Set up Coveralls

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#2]
I'm a big fan of Coveralls for test coverage details (https://coveralls.io/), would be nice if we set that up on this repository.

**Comment by fishscene** [comment]
I don't have an opinion one way or the other, but if @gravyboat thinks this will help and can take ownership of this, let's do it.
Does anyone have further thoughts on this?

**Comment by gravyboat** [comment]
I'll take care of it if no one has concerns, was going to do it this weekend and didn't review the docs enough to figure out how to handle it for an org.

**Comment by cdrage** [comment]
@gravyboat if you set it up with third-party support, i'll get a notification about allowing it and I can accept it. +1 for coveralls support

**Comment by cdrage** [comment]
@gravyboat there we go! i set it up, should get notifications on each PR opened now

**Comment by gravyboat** [comment]
@cdrage Good stuff, I looked in the coveralls interface this weekend and it wasn't showing up for some reason. Glad to see you got it!

**Comment by gravyboat** [comment]
This is now working as per the example PR here: https://github.com/streamlink/streamlink/pull/13#event-794486121, closing as resolved.

**Comment by gravyboat** [comment]
Looks like there is a minor configuration issue causing the coverage to show as no data even though it is being sent, there are several errors within Travis which I'll investigate. Opening back up for right now.

**Comment by cdrage** [comment]
@gravyboat I think `--cov livestreamer` needs to be added

**Comment by gravyboat** [comment]
@cdrage More than likely that is the issue, previously I ran it through nosetests so it operated a bit differently. I'll prep a PR later today, as well as adding in a `.coveragerc` file so we don't get so much garbage.

**Comment by gravyboat** [comment]
Here are some pretty good instructions, will implement this later today: https://github.com/audreyr/how-to/blob/master/python/use_coverage_with_unittest.rst#set-up-coveralls

**Comment by cdrage** [comment]
@gravyboat found the issue, here's the PR: https://github.com/streamlink/streamlink/pull/16
