### ISSUE TITLE
Streamlink only detects resolutions up to 720p on youtube, even though the youtube video has a 1080p resolution option.

### ISSUE THREAD

**Issue by Victolabs** [streamlink/streamlink#200]
Here is a photo: http://i.imgur.com/nEuwV6G.png

Here is the video in question: https://www.youtube.com/watch?v=Og5-Pm4HNlI

Computer specs: http://speccy.piriform.com/results/xhFwWmULlvynuOQQ0Ms8spD

**Comment by beardypig** [comment]
The 1080p option is only available from adaptive streaming formats. Unfortunately, this is not currently supported by `streamlink`, however it is something that we are working towards supporting.

**Comment by Victolabs** [comment]
Thanks for the fast response! :)

**Comment by tp0** [comment]
Until the Streamlink plugin is improved, you can use [mpv video player](https://mpv.io/installation/).

`mpv --ytdl https://www.youtube.com/watch?v=Og5-Pm4HNlI`

It also supports 60 fps for VOD videos (not live videos), unlike Streamlink.

**Comment by flijloku** [comment]
@tp0  You forgot to mention, that for this method also  youtube-dl must be installed.

**Comment by beardypig** [comment]
streamlink should support 1080p on these videos now, the video in the original post (https://www.youtube.com/watch?v=Og5-Pm4HNlI) now lists 1080p as an option in streamlink.
