### ISSUE TITLE
Streamlink "Bugs out" when i try to seek on a youtube video.

### ISSUE THREAD

**Issue by Victolabs** [streamlink/streamlink#201]
I'm not going to try and describe it in text so I recorded a video of it happening. It should be attached the the post.

[SkyShare_20161123_122528_0.zip](https://github.com/streamlink/streamlink/files/609707/SkyShare_20161123_122528_0.zip)

**Comment by gravyboat** [comment]
We are discussing this feature over here: https://github.com/streamlink/streamlink/issues/134 I'm going to close this one out, feel free to comment over there if you would like!
