### ISSUE TITLE
How to bypass region

### ISSUE THREAD

**Issue by lianquan** [streamlink/streamlink#2012]
Hi,
This is the first time I use streamlink and I am quite confused, I don't know if I used it the wrong way or it does not work.

This is a livestream and it is only available in Korea: https://www.youtube.com/watch?v=Dk2VaObQ8eg

And I used this code to bypass the area block (This is a Korean proxy):
`streamlink --http-proxy "socks5h://119.196.18.50:8080" --https-proxy "socks5h://119.196.18.50:8080" h
ttps://www.youtube.com/watch?v=Dk2VaObQ8eg best`

But it failed, and I got this message:
`[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=Dk2VaObQ8eg
error: Unable to open URL: https://youtube.com/get_video_info (SOCKSHTTPSConnectionPool(host='youtube.com', port=443): Max retries exceeded with url: /get_video_info?el=detailpage&video_id=Dk2VaObQ8eg (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x04808BF0>, 'Connection to youtube.com timed out. (connect timeout=20.0)')))`

Can someone give me an exact example?
Thanks.

**Comment by d0tfile** [comment]
Try use proxy without leading socks5h. I'm able to play with `--http-proxy 119.196.18.50:8080`

**Comment by d0tfile** [comment]
Please, close issue
