### ISSUE TITLE
request for cwtv  plugin

### ISSUE THREAD

**Issue by rellik31** [streamlink/streamlink#2016]
## Plugin Issue  cwtv.com web site not coded for this software

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

website for tv show episodes for the cw channel in the usa
https://en.wikipedia.org/wiki/The_CW

### Reproduction steps / Explicit stream URLs to test

http://www.cwtv.com/shows/the-100/the-warriors-will/?play=d7857786-f312-45d3-a63b-c36ba8401138

1. ... http://www.cwtv.com/shows/the-outpost/
2. ... http://www.cwtv.com/shows/the-flash/
3. ... http://www.cwtv.com/shows/dcs-legends-of-tomorrow/

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.
shows 5 episodes of each tv show and has around 15 different shows
that are in 720p @ 2000kbps

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by PlaceboPRS** [comment]
Works fine if you use something like the Firefox addon Video download helper to grab the URL for you :)

**Comment by gravyboat** [comment]
Site is only VODs which we don't support per the plugin guidelines: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
