### ISSUE TITLE
Twitch stream is not 1080p in VLC

### ISSUE THREAD

**Issue by woctezuma** [streamlink/streamlink#2019]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

The Twitch stream appears really tiny in VLC.

### Expected / Actual behavior

The Twitch stream should appear in the requested resolution.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink https://www.twitch.tv/dota2ti best`

### Log output

```
$> streamlink --loglevel debug https://www.twitch.tv/dota2ti best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/dota2ti
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-oauth-token=******** (oauth_token)
[plugin.twitch][debug] Getting live HLS streams for dota2ti
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as MYTWITCHUSERNAME
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 20279; Last Sequence: 20294
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 20292; End Sequence: None
[stream.hls][debug] Adding segment 20292 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 20293 to queue
[stream.hls][debug] Adding segment 20294 to queue
[stream.hls][debug] Download of segment 20292 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[stream.hls][debug] Download of segment 20293 complete
[stream.hls][debug] Download of segment 20294 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 20295 to queue
[stream.hls][debug] Adding segment 20296 to queue
[stream.hls][debug] Download of segment 20295 complete
[stream.hls][debug] Download of segment 20296 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 20297 to queue
```

### Additional comments, screenshots, etc.

![VLC](https://i.imgur.com/fbe1I37.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I can't duplicate this. VLC 3 is working for me without issue. Are you using the latest version of VLC? Can you try another player like MPV and see if it occurs there as well?

**Comment by woctezuma** [comment]
> Are you using the latest version of VLC?

I'm using VLC 3.0.3.

I have installed streamlink 0.14.2 via `pip`, but the issue is still there if I install it via the installer provided in the `releases` section.

**Comment by woctezuma** [comment]
Alright, problem solved by resetting to default the configuration of VLC.

![VLC config](https://i.imgur.com/P0lxzVp.png)

Sorry for bothering.
