### ISSUE TITLE
Add support for steam.tv

### ISSUE THREAD

**Issue by lunks** [streamlink/streamlink#2020]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

steam has launched its own streaming website for Dota 2 TI. I'm unsure if it relates to [Steam Brodcast](https://github.com/streamlink/streamlink/pull/1717).

### Expected / Actual behavior

Allow steam.tv links to be handled by streamlink.

Currently it does not.

**Comment by acz13** [comment]
I think this is just a fancy page for steam broadcast

**Comment by acz13** [comment]
Close this
