### ISSUE TITLE
Videoplayer closes almost instantly while trying to open youtube/twitch clips

### ISSUE THREAD

**Issue by Terr2** [streamlink/streamlink#2022]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Hi, I'm using latest streamlink installed from the weupd8 ppa (using the official installation guide for ubuntu found at https://streamlink.github.io/install.html#linux-and-bsd-packages) on 32-bit Lubuntu 18.04. When I try to open any youtube or twitch clip streamlink seems to start working normally but after it opens chosen videoplayer the videoplayer closes almost instantly and I don't get to see any video. I tried vlc (version 3.0.3-1-1ubuntu1 from Lubuntu universe repository) and mpv (from the https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests ppa) and the behavior is the same. Normal twitch/youtube livestreams work as you would expect.

### Expected / Actual behavior

Expected:
Streamlink should play youtube/twitch clips.
What is happening:
The chosen videoplayer closes almost instantly.

### Reproduction steps / Explicit stream URLs to test

1. enter "streamlink https://www.youtube.com/watch?v=F7ElMOiAOBI 720p --player=vlc -l debug" in console
(alternatively you could try watching a twitch clip "streamlink https://clips.twitch.tv/RenownedElegantDurianTF2John 720 --player=vlc -l debug")

### Log output

console log:
```
lol@lubuntu:~$ streamlink https://www.youtube.com/watch?v=F7ElMOiAOBI 720p --player=vlc -l debug
[cli][debug] OS:         Linux-4.15.0-32-generic-i686-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=F7ElMOiAOBI
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 251 = 1080p
[cli][info] Available streams: audio_mp4, audio_webm, 144p (worst), 180p, 360p, 720p, 1080p (best)
[cli][info] Opening stream: 720p (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: vlc
[cli][debug] Writing stream to output
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

vlc log:
https://gist.github.com/Terr2/e4f32fb59c0964dad492b557b416858e
mpv debug log (--player='mpv --msg-level=all=debug --log-file=mpvlog' option instead of vlc)
https://gist.github.com/Terr2/9083c1cd3e6f6c5850229f6c8290c3d1
mpv trace log (--player='mpv --msg-level=all=trace --log-file=mpvlog' option instead of vlc)
https://gist.github.com/Terr2/28f9072aaafac5dc3c48251794b62cb2
### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Hmm, I tried duplicating this on my Windows machine and both of your links work fine with MPV (and I was able to watch the entire thing). I'm running the same Python and Streamlink versions (though 64 bit). VLC did instantly close for me with the Youtube video, and the Twitch clip only played about 75% of the way through so there's definitely an issue with VLC, but that's most likely a player problem. I'm running the stable release of MPV which is older than what you're running. I didn't see anything particularly helpful in the debug log either when VLC closed. I also don't see much in the MPV logs that you've provided that would be helpful. Maybe try the stable release of MPV and see if you still encounter the issue?

**Comment by bastimeyer** [comment]
@Terr2
This looks like a local issue with the player's video rendering/decoding and not like a Streamlink issue. When the player process terminates (on its own or by a user interaction) Streamlink itself will also stop. Please make sure that your player is working correctly on your system. You can try to write the stream to your file system and then open it with your player afterwards. See the `-o` parameter for that.

**Comment by bastimeyer** [comment]
Any response? Otherwise, this thread should be closed, as it's a local user error...

**Comment by back-to** [comment]
Normal behavior of Streamlink, you can use `--player-no-close`

https://streamlink.github.io/cli.html#cmdoption-player-no-close

```
By default Streamlink will close the player when the stream ends.
This is to avoid "dead" GUI players lingering after a stream ends.

It does however have the side-effect of sometimes closing a player
before it has played back all of its cached data.

This option will instead let the player decide when to exit.
```

**Comment by VPaulV** [comment]
I am using streamlink 6.2.0, for some reason --player-no-close, doesn't work properly. Are there any logs I could provide to debug this? 
```
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/name
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
I need to restart it like 4-5 times before stream actually starts

**Comment by bastimeyer** [comment]
@VPaulV You are commenting on an unrelated issue that was closed 5 years ago. Going to lock this thread now...

Check your player's error output/logs. Streamlink only sees that the player process has exited, so it terminates its own process. This might have something to do with your player configuration when trying to play back the content or when trying to render the window in your desktop environment. See [`--verbose-player`](https://streamlink.github.io/cli.html#cmdoption-verbose-player).
