### ISSUE TITLE
Add support for ustreamix

### ISSUE THREAD

**Issue by 10362227** [streamlink/streamlink#2026]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Example stream URLs

1. https://ssl.ustreamix.com/stream.php?id=bbc-america
2. https://ssl.ustreamix.com/stream.php?id=abc-tv
3. https://ssl.ustreamix.com/stream.php?id=comedy-central

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 2. Sites which are hosting stolen content as their main source of content

That doesn't look like a legit streaming site and it seems to just provide stolen content/streams from various countries. Contact link in the header is just a gmail address and the SSL certificate is issued by Let's-Encrypt.

Closing...
