### ISSUE TITLE
ImportError: No module named shutil_which

### ISSUE THREAD

**Issue by Wrsanches** [streamlink/streamlink#2029]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
When i trying to use the plugin, returns: "ImportError: No module named shutil_which"

### Reproduction steps / Explicit stream URLs to test

1. Just typing `streamlink http://twitch.tv/yoda best`

### Log output

```
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/usr/local/lib/python2.7/dist-packages/streamlink/__init__.py", line 86, in <module>
    from .api import streams
  File "/usr/local/lib/python2.7/dist-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/usr/local/lib/python2.7/dist-packages/streamlink/session.py", line 9, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/usr/local/lib/python2.7/dist-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/usr/local/lib/python2.7/dist-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which

```

### Additional comments, screenshots, etc.
https://user-images.githubusercontent.com/13179450/44610669-908e8f00-a7d3-11e8-90ef-97ce6e572429.png

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Can you provide a debug log? How did you install streamlink?

**Comment by Wrsanches** [comment]
I installed via pip (sudo pip install streamlink). How can i provide a debug log?

**Comment by beardypig** [comment]
Add `-l debug` to your streamlink command :)

**Comment by back-to** [comment]
no response.

**Comment by rponline** [comment]
I've got the same error

```
user@debianlinux:~/Downloads$ streamlink
Traceback (most recent call last):
  File "/home/user/.local/bin/streamlink", line 7, in <module>
    from streamlink_cli.main import main
  File "/home/user/.local/lib/python2.7/site-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/home/user/.local/lib/python2.7/site-packages/streamlink/__init__.py", line 86, in <module>
    from .api import streams
  File "/home/user/.local/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/home/user/.local/lib/python2.7/site-packages/streamlink/session.py", line 9, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/home/user/.local/lib/python2.7/site-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/home/user/.local/lib/python2.7/site-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which
user@debianlinux:~/Downloads$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
user@debianlinux:~/Downloads$ python -c "import setuptools;print(setuptools.__version__)"
40.4.3
user@debianlinux:~/Downloads$ streamlink^C
user@debianlinux:~/Downloads$ uname -a
Linux debianlinux 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux
user@debianlinux:~/Downloads$ python -m pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
user@debianlinux:~/Downloads$ pip --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
user@debianlinux:~/Downloads$ python -c "import pip;print(pip.__version__)"
9.0.1
user@debianlinux:~/Downloads$ python -c "import setuptools;print(setuptools.__version__)"
40.4.3
user@debianlinux:~/Downloads$ 
```

**Comment by Chazzz** [comment]
@rponline Assuming your problem hasn't been resolved, can you please give me the output of `python -c "import backports;print backports.__path__"` and `pip show backports.shutil_which` on your machine?

**Comment by tonyrh** [comment]
I have the same problem on Ubuntu 18.10:

```
> python -c "import backports;print backports.__path__"
['/usr/lib/python2.7/dist-packages/backports']

> pip show backports.shutil_which
Name: backports.shutil-which
Version: 3.5.1
Summary: Backport of shutil.which from Python 3.3
Home-page: https://github.com/minrk/backports.shutil_which
Author: Min RK
Author-email: benjaminrk@gmail.com
License: Python Software Foundation License
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

**Comment by back-to** [comment]
> I have the same problem on Ubuntu 18.10:

it is just an issue with the `backports` name as you can see above

try this or read the other links
 
https://github.com/streamlink/streamlink/issues/1358#issuecomment-351976956

---

the best way is to **use Python3 instead of Python2**

---

there is also a solution with including the `backports` packages directly into Streamlink as compat versions,
but they already got removed once in https://github.com/streamlink/streamlink/pull/355 so i asume this is not wanted.

**Comment by Chazzz** [comment]
I found it! The package python-configparser (which is a dependency of python-pip) is to blame for the malformed backports directory at the system level! I can't wait to get this fixed!

**Comment by Chazzz** [comment]
**If you are experiencing this problem here is how I fixed it**

1. Changed /usr/lib/python2.7/dist-packages/backports/\_\_init\_\_.py to have extend_path code (as described at [https://pypi.org/project/backports/](https://pypi.org/project/backports/) or PEP 420)
2. Deleted /usr/lib/python2.7/dist-packages/configparser-3.5.0b2-nspkg.pth

Exact paths may vary based on system.

**Comment by zxosazx** [comment]
Xbuntu 19.04 have this problem. Install from pip.
