### ISSUE TITLE
Unable to play protected youtube videos?

### ISSUE THREAD

**Issue by Cervoxx** [streamlink/streamlink#203]
So I decided to try and play [this video](https://www.youtube.com/watch?v=a5FkPFzyKs0) and I got [this error message.](http://i.imgur.com/sPYZfbP.png)

So I'm wondering when/if streamlink will be able to play protected videos?

**Comment by tp0** [comment]
This won't help if you want to use Streamlink only, but mpv plays that fine. `'mpv --ytdl <URL>`

I've seen videos like this before. What does the "protected" mean in this case?

**Comment by Twilight0** [comment]
Is there any plan to support "protected" videos? I am packing streamlink for Kodi and I cannot use it for playing various videos scraped from web pages.

**Comment by vienntbna** [comment]
What does "protected" means ? I can ask the uploader to remove that

**Comment by back-to** [comment]
We will probably not add a JavaScript interpreter for this.
