### ISSUE TITLE
metube.id plugin request

### ISSUE THREAD

**Issue by akiwatti** [streamlink/streamlink#2031]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
www.metube.id
- serveral Indonesia TV channels / legal streaming portal, see TERMS & CONDITIONS
link to live channel selection:
- https://www.metube.id/live

### Example stream URLs
1.  https://www.metube.id/live/METROTV
2.  https://www.metube.id/live/GTV
3.  https://www.metube.id/live/RCTI
4.  https://www.metube.id/live/TRANS7
5. ...

### Additional comments, screenshots, etc.
sample embeded stream: m3u8 / accessing: HTTP 502 bad Gateway

1. https://cdn-livetv1.metube.id/hls/metrotv.m3u8  / 
    https://cdn-livetv1.metube.id/hls/metrotv_480/index.m3u8
2. https://cdn-livetv2.metube.id/hls/globaltv.m3u8 / 
    https://cdn-livetv2.metube.id/hls/globaltv_480/index.m3u8
3. https://cdn-livetv2.metube.id/hls/rcti.m3u8
    https://cdn-livetv2.metube.id/hls/rcti_480/index.m3u8
4. https://cdn-livetv1.metube.id/hls/trans7.m3u8
    https://cdn-livetv1.metube.id/hls/trans7_480/index.m3u8
5. .....

######

**Comment by rollykaunang** [comment]
I think there is some indonesian want plugin for this site, Hope someone could help us to make plugin for us. High demand please consider it. Thank You So Much.

**Comment by back-to** [comment]
@akiwatti 

> HTTP 502 bad Gateway

if you send a **User-Agent** and **Origin** http header, it should work

```
streamlink https://cdn-livetv1.metube.id/hls/metrotv.m3u8 best --http-header "Origin=https://www.metube.id" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0"
```

**Comment by addies** [comment]
Hi There,
 
I am developer from meTube.id and on behalf of my team, I would like to say thanks to give attention to meTube.id and we are really proud to develop this site. I want honesty from you to be able to appreciate the work of others as a form of appreciation for intellectual properties. You are still able to watch the LiveTV to your site by embedding the link. meTube.id team really appreciate if you can do it in a good way. Last, If you need something, you may contact meTube.id support. Thank you

Regards
meTube.id
