### ISSUE TITLE
f1tv.formula1.com plugin

### ISSUE THREAD

**Issue by Jigsaw10** [streamlink/streamlink#2033]
## Plugin Request

f1tv.formula1.com plugin

### Description

 "https://f1tv.secure.footprint.net/live/50826045738/master.m3u8?nva=1535288890&ttl=86400&cc=DE&token=0e633ccec04c310925902"

### Example stream URLs

1. ... "hls://https://f1tv.secure.footprint.net/live/50826045738/master.m3u8?nva=1535288890&ttl=86400&cc=DE&token=0e633ccec04c310925902"
2. ...https://f1tv-cdn-cent-live.formula1.com"
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> You need to have an F1 subscription to watch exclusive content

@gravyboat Should this request be closed or can it be kept? I'm not sure...

**Comment by Jigsaw10** [comment]
Hi, I have your login details if any of you need to
in practice the on demand work but if there is a live during the transmission does not start with the software it would be nice to have a plugin that system all this is available

**Comment by back-to** [comment]
Adding new plugins where it is **difficult to get an account**,
will make the new plugin impossible to maintain.

so adding it, is useless.

closing
