### ISSUE TITLE
Is it possible to stream to a buffer headless?

### ISSUE THREAD

**Issue by strich** [streamlink/streamlink#2040]
## Issue
- [x ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description
I want to do some load testing using streamlink for a livestream we have coming up. Is there a way to run streamlink without an active player? I tried using the http server option but it only starts streaming in data if a player connects to it.

**Comment by bastimeyer** [comment]
> Is there a way to run streamlink without an active player?

`--stdout`
https://streamlink.github.io/cli.html#cmdoption-stdout

**Comment by strich** [comment]
Interesting. Though that means I can no longer use stdout to read off any errors or info about the setup of th stream. :/

**Comment by bastimeyer** [comment]
The log output is being logged to `stderr` then...
```bash
$ streamlink -l debug --stdout URL QUALITY 1>/dev/null 2>debug.txt
```

Alternatively, by using `--output` and writing it to `/dev/null`, the debug log will be kept at `stdout`:
```bash
$ streamlink -l debug --output /dev/null URL QUALITY 1>debug.txt
```
