### ISSUE TITLE
How to Stream Akamai (?) Video from Senate Foreign Relations Committee Website

### ISSUE THREAD

**Issue by LampaGJ** [streamlink/streamlink#2042]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I am attempting to load archived video and live video streams of the US Senate Foreign Relations Committee ([Example](https://www.foreign.senate.gov/hearings/business-meeting-082218)) in VLC via streamlink. It appears their video streaming is done via Akamai and AMP v4.90.9 from right-clicking the player embedded in provided examples.

### Expected / Actual behavior

Ideally, pointing streamlink to the hearing page containing an embedded player would automagically identify available streams and open the best quality stream in VLC:

`streamlink "https://www.foreign.senate.gov/hearings/business-meeting-082218" best`   

What actually happens is that streamlink fails with an error `error: No plugin can handle URL: https://www.foreign.senate.gov/hearings/business-meeting-082218`

### Reproduction steps / Explicit stream URLs to test

I have discovered that the URL for their embedded player gets a little closer ([Example](http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218)), but streamlink still doesn't find any streams at this URL. That is, until I replace https:// with *akamaihd://*:

`streamlink "akamaihd://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218"`   

Results in:

```[cli][info] Found matching plugin akamaihd for URL akamaihd://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218
Available streams: live (worst, best)
```

When I specify "best" and run the command again, the result is:

```[cli][info] Found matching plugin akamaihd for URL akamaihd://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (akamaihd)
[cli][error] Try 1/1: Could not open stream <AkamaiHDStream('http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218', swf=None)> (Could not open stream: Unable to open URL: http://www.senate.gov/isvp/ (503 Server Error: Service Unavailable for url: http://www.senate.gov/isvp/?fp=LNX+11%2C1%2C102%2C63&r=PPJRC&g=VFVQOIITOQRF&v=2.5.8))
error: Could not open stream <AkamaiHDStream('http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218', swf=None)>, tried 1 times, exiting
```
### Logs

```
[cli][debug] OS:         macOS 10.13.6
[cli][debug] Python:     2.7.15
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin akamaihd for URL akamaihd://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218
[plugin.akamaihd][debug] URL=http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218; params={}
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (akamaihd)
[stream.akamaihd][debug] Opening host=http://www.senate.gov streamname=isvp/
[cli][error] Try 1/1: Could not open stream <AkamaiHDStream('http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218', swf=None)> (Could not open stream: Unable to open URL: http://www.senate.gov/isvp/ (503 Server Error: Service Unavailable for url: http://www.senate.gov/isvp/?fp=LNX+11%2C1%2C102%2C63&r=VREJP&g=JOHWJGPLHFNA&v=2.5.8))
error: Could not open stream <AkamaiHDStream('http://www.senate.gov/isvp/?comm=foreign&type=live&filename=foreign082218', swf=None)>, tried 1 times, exiting
```

### Additional comments, screenshots, etc.

It appears the Senate Foreign Relations Committee uses the date of the hearing as the main reference ID. Since the committee only meets once a day, there's only ever one stream on any given day.

There's possibly useful information in the source of each player page. In the source code for the example link I've used above, there's this snippet:

```
<a id="watch-live-now" class="small btn" href="javascript:openVideoWin('/hearings/watch?hearingid=AA0FF459-5056-A066-60A0-8B11F704E85E');">Open New Window</a>
```

Also, from the source code the video player code can have a lot of parameters specified:

```
https://www.senate.gov/isvp/?comm=foreign&type=arch&stt=21:50&filename=foreign082218&auto_play=false&wmode=transparent&poster=https%3A%2F%2Fwww%2Eforeign%2Esenate%2Egov%2Fthemes%2Fforeign%2Fimages%2Fvideo%2Dposter%2Dflash%2Dfit%2Epng
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
You can watch this directly, stream url appears to be static.

https://foreign-f.akamaihd.net/i/foreign082218_1@76451/master.m3u8?

```
[cli][info] Found matching plugin hls for URL https://foreign-f.akamaihd.net/i/foreign082218_1@76451/master.m3u8?" best
Available streams: 360p_alt (worst), 360p (best)
```

```
C:\>youtube-dl.exe -v --hls-prefer-native --no-check-certificate --no-overwrites "https://foreign-f.akamaihd.net/i/foreign082218_1@76451/master.m3u8?"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--hls-prefer-native', '--no-check-certificate', '--no-overwrites', 'https://foreign-f.akamaihd.net/i/foreign082218_1@76451/master.m3u8?']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.08.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg n4.0.2-ffmpeg-windows-build-helpers, ffprobe n4.0.2-ffmpeg-windows-build-helpers, rtmpdump 2.4
[debug] Proxy map: {}
[generic] master: Requesting header
WARNING: Could not send HEAD request to https://foreign-f.akamaihd.net/i/foreign082218_1@76451/master.m3u8?: HTTP Error 405: Method Not Allowed
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://foreign-f.akamaihd.net/i/foreign082218_1@76451/index_356_av-b.m3u8?sd=10&rebase=on'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 734
[download] Destination: master-master.mp4
[download]   2.5% of ~300.16MiB at  1.77MiB/s ETA 04:51    [download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 19 (attempt 10 of 10)...
[download] Skipping fragment 19...
[download]   7.5% of ~300.27MiB at  1.59MiB/s ETA 05:02
```

<a href='https://postimg.cc/image/ehaqjlf5t/' target='_blank'><img src='https://s8.postimg.cc/ehaqjlf5t/Screen_Shot.jpg' border='0' alt='Screen_Shot'/></a>

**Comment by LampaGJ** [comment]
This is helpful and works—could you explain how you arrived at this being the static URL? I want to reverse engineer this into an Automator action if possible—to convert a URL of pages with the embedded player into the appropriate stream URL to load in VLC via streamlink. Specifically, where does "76451" come from in your working URL? What function does that serve in loading the stream? And the _01 after the date of the hearing? Why does the URL end with master.m3u8?

**Comment by beardypig** [comment]
@LampaGJ I created a PR that adds a plugin that should handle your use case. The plugin doesn't handle all of the streams, but I can add to that later.
