### ISSUE TITLE
Redundant HLS manifest support

### ISSUE THREAD

**Issue by ariselseng** [streamlink/streamlink#2043]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Support for failover to redudant server in HLS.
HLS in master manifests has support for redundant variant manifests that the client can switch to if the chosen manifest goes down.

### Expected / Actual behavior

When a variant manifest goes down, a backup variant could be switched to without any downtime.
Currently even if the master manifest has multiple variants of the same level/quality. The player stops.

**Comment by back-to** [comment]
#2626
