### ISSUE TITLE
How to enable progress bar for twitch videos (not live stream)?

### ISSUE THREAD

**Issue by terrytw** [streamlink/streamlink#2046]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description
Twitch stores videos of past streams for users to playback. When playing videos instead of watching live stream, twitch shows a progress bar so you can jump to a certain time point. 

I'm wondering if it is possible to do the same with streamlink + local video players?

I have read the guidelines, and did not find anything relating to this. Maybe I missed something. Can someone please enlighten me here?

Thank you!

**Comment by gravyboat** [comment]
What you're thinking of is seeking, and we have an old issue for this: https://github.com/streamlink/streamlink/issues/134, unfortunately it's not as simple a problem to solve as one would hope due to the way video is streamed to the player and pulled by Streamlink.

**Comment by terrytw** [comment]
Thank you! That post gave me a  workaround which is already enough!
