### ISSUE TITLE
Eurosport Player

### ISSUE THREAD

**Issue by Jigsaw10** [streamlink/streamlink#2051]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Example stream URLs

1. ...streamlink hls://https://hlslinear-akc.ams1.media.eurosportplayer.com/hdnts=exp=1536071759~acl=/*~id=71bb5017-3ddd-48d5-b531-6c57872b4bc6~hmac=aee36a1e7fc06fbcf44a3351e80952c7524ad69d0fbbeae43fdab3012b0473ff/d40226a075fe9f39a5fc2546c060734b/ls01/eurosport/linear/channel/EUROSPORT_1_ITALY-1531844084560/master_desktop_slide.m3u8 best
[cli][info] Found matching plugin hls for URL hls://https://hlslinear-akc.ams1.media.eurosportplayer.com/hdnts=exp=1536071759~acl=/*~id=71bb5017-3ddd-48d5-b531-6c57872b4bc6~hmac=aee36a1e7fc06fbcf44a3351e80952c7524ad69d0fbbeae43fdab3012b0473ff/d40226a075fe9f39a5fc2546c060734b/ls01/eurosport/linear/channel/EUROSPORT_1_ITALY-1531844084560/master_desktop_slide.m3u8
[cli][info] Available streams: 180p (worst), 216p, 288p, 360p, 504p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://drm-api.svcs.eurosportplayer.com/programs/e4f76a91-c5f6-43c0-ad5c-e7eee1ad0e22/media/6ce653e2-3ab6-4eb5-a149-33c04823455f/keys/81bc0fe5-ebd8-43bd-8cda-e8543dcd61d9 (401 Client Error: Unauthorized for url: https://drm-api.svcs.eurosportplayer.com/programs/e4f76a91-c5f6-43c0-ad5c-e7eee1ad0e22/media/6ce653e2-3ab6-4eb5-a149-33c04823455f/keys/81bc0fe5-ebd8-43bd-8cda-e8543dcd61d9)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://hlslinear-akc.ams1.media.eurosportplayer.com/hdnts=exp=1536071759~acl=/*~id=71bb5017-3ddd-48d5-b531-6c57872b4bc6~hmac=aee36a1e7fc06fbcf44a3351e80952c7524ad69d0fbbeae43fdab3012b0473ff/d40226a075fe9f39a5fc2546c060734b/ls01/eurosport/linear/channel/EUROSPORT_1_ITALY-1531844084560/3500K/3500_slide.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://hlslinear-akc.ams1.media.eurosportplayer.com/hdnts=exp=1536071759~acl=/*~id=71bb5017-3ddd-48d5-b531-6c57872b4bc6~hmac=aee36a1e7fc06fbcf44a3351e80952c7524ad69d0fbbeae43fdab3012b0473ff/d40226a075fe9f39a5fc2546c060734b/ls01/eurosport/linear/channel/EUROSPORT_1_ITALY-1531844084560/3500K/3500_slide.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
2. ...
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by 10mins** [comment]
> Stream is DRM protected, it won't work with Streamlink

Check your "facts". There is no DRM just AES-128 and streamlink can handle eurosport streams just fine. Please re-open.

**Comment by 10mins** [comment]
`streamlink --http-header "authorization=[your authorization header goes here]" hlsvariant://"https://hlslinear-l3c.ams1.media.eurosportplayer.com/token=exp=1537945345[...your token goes here]/ls01/eurosport/linear/channel/EUROSPORT_2_UK-1531770734333/master_desktop_slide.m3u8" best
![eu](https://user-images.githubusercontent.com/11040529/45998687-45a2b880-c0ac-11e8-986a-03d25245ad36.PNG)
`

**Comment by tp0** [comment]
Above is the solution. You need to get the authorization cookie via e.g. browser developer tools. It is an a file called "drm".

**Comment by tp0** [comment]
> Forgive me for being ignorant, but I see no such file/value. I have found the Eurosport cookie via the developer tools in Chrome, but it has several keys and values, none of which seem to pertain to DRM. Am I looking in the wrong place, or should I be using one of these values as my authorization? (I am a massive beginner, so please bear with me.)

* open Chrome developer tools and click the network tab
* type "drm" in the filter text field
* refresh page/load stream
* one or two results will show up, if two, the thing you're looking for is in the second one under Headers > Request Headers > authorization

I don't know if there is some even easier/faster way but this is the method I use.

![untitled](https://user-images.githubusercontent.com/5863551/46445123-e31d7c80-c77d-11e8-8d64-355a2e310478.png)

**Comment by furkyto** [comment]
Can someone help me download from NBA League pass witch is mpeg-dash with drm encryption

**Comment by gravyboat** [comment]
@furkyto We don't support videos with DRM encryption, and this is also off-topic. Since there's been no response in a month for this, closing and locking.
