### ISSUE TITLE
chaturbate 403 Client Error: Forbidden

### ISSUE THREAD

**Issue by weigeloveu** [streamlink/streamlink#2056]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

403 Client Error: Forbidden

### Reproduction steps / Explicit stream URLs to test
zh.chaturbate.com/natasha_foxx/

### Log output

C:\Users\li>streamlink -l debug zh.chaturbate.com/natasha_foxx/
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin chaturbate for URL zh.chaturbate.com/natasha_foxx/
[plugin.chaturbate][info] Stream status: public
error: Unable to open URL: https://edge198.stream.highwebmedia.com/live-hls/amlst:natasha_foxx-sd-9a33fc9c899651629ecdb5cb9646f247d30ea457ed233cef0c95e5142c950efb_trns_h264/playlist.m3u8 (403 Client Error: Forbidden for url: https://edge198.stream.highwebmedia.com/live-hls/amlst:natasha_foxx-sd-9a33fc9c899651629ecdb5cb9646f247d30ea457ed233cef0c95e5142c950efb_trns_h264/playlist.m3u8)

**Comment by johnthecracker** [comment]
```
C:\>youtube-dl.exe -v -F --hls-prefer-native --no-check-certificate "https://chaturbate.com/masha_sexy/"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--hls-prefer-native', '--no-check-certificate', 'https://chaturbate.com/masha_sexy/']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2018.09.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg n4.0.2-ffmpeg-windows-build-helpers, ffprobe n4.0.2-ffmpeg-windows-build-helpers, rtmpdump 2.4
[debug] Proxy map: {}
[Chaturbate] masha_sexy: Downloading webpage
[Chaturbate] masha_sexy: Downloading m3u8 information
[info] Available formats for masha_sexy:
format code  extension  resolution note
slow-0       mp4        320x240     488k , avc1.66.13, mp4a.40.2
slow-1       mp4        480x360     928k , avc1.66.30, mp4a.40.2
slow-2       mp4        640x480    1258k , avc1.77.30, mp4a.40.2
slow-3       mp4        768x576    2076k , avc1.77.31, mp4a.40.2
slow-4       mp4        960x720    3396k , avc1.77.31, mp4a.40.2 (best)
```

**Comment by Asynchr0nous** [comment]
The issue here is NOT with the plugin but sometimes the stream is not stable enough (generally because of poor connection on either streamers end or yours) so it ends up giving random errors. Also on so many occasions chaturbate has these issues popup from time to time so there is not much anyone except chaturbate can do about it

**Comment by emanruse** [comment]
I experience a 403 error *only when using socks (TOR) proxy*. Here is the output:
```
[~]:  streamlink -l debug --http-proxy socks5h://127.0.0.1:9050/ --https-proxy socks5h://127.0.0.1:9050/ --rtmp-proxy socks5h://127.0.0.1:9050/ https://chaturbate.com/ramonatorres/ best
[cli][debug] OS:         Linux-4.12.14-lp150.12.16-default-x86_64-with-glibc2.3.4
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/ramonatorres/
error: Unable to open URL: https://chaturbate.com/get_edge_hls_url_ajax/ (403 Client Error: Forbidden for url: https://chaturbate.com/get_edge_hls_url_ajax/)
```
If I remove the proxy options everything works fine. Also: the same channel stream plays fine in TOR browser. If it was Chaturbate blocking TOR it would not be possible.

Is my issue the same as that of the OP or should I report it separately?

**Comment by emanruse** [comment]
If I copy the m3u8 link from the HTML source of the Chaturbate page and give it to `streamlink` using the above command line - everything works as expected: the video plays through TOR just fine. A problem occurs after a few minutes:
```
[stream.hls][warning] Failed to reload playlist: Unable to open URL: ...
```
which I suppose means that the link needs to be refreshed (makes sense). This doesn't happen with some TV channels for which there are supported plugins.

I hope someone can look into this. This really looks like a plugin issue.

**Comment by emanruse** [comment]
More observations:

Setting system wide:
```
[/tmp/download]: printenv | grep proxy
https_proxy=socks5://127.0.0.1:9050/
http_proxy=socks5://127.0.0.1:9050/
no_proxy=localhost,127.0.0.1
socks_proxy=socks://127.0.0.1:9050
gopher_proxy=
ftp_proxy=
```
and then starting `streamlink https://chaturbate.com/raacy best` successfully opens the stream and plays it. And again after some seconds messages appear:
```
[stream.hls][error] Failed to open segment 7346: Unable to open URL: https://edge99.stream.highwebmedia.com/live-hls/amlst:raacy-sd-93fb515956bc4f87e0c7962a0d4332afb6b0b4c2cec303996d89815432ac8ef0_trns_h264/media_w505782926_b3096000_7346.ts (404 Client Error: Not Found for url: https://edge99.stream.highwebmedia.com/live-hls/amlst:raacy-sd-93fb515956bc4f87e0c7962a0d4332afb6b0b4c2cec303996d89815432ac8ef0_trns_h264/media_w505782926_b3096000_7346.ts)
```
Even `--player-continuous-http` doesn't help to auto refresh the stream.

**Comment by bastimeyer** [comment]
> This really looks like a plugin issue

NSFW plugins have been removed and are not supported anymore.
#2003 

`--player-continuous-http` is an output option and has nothing to do with fetching the stream data.

**Comment by gravyboat** [comment]
I'm going to lock this since we aren't even supporting the plugin any more to avoid too much notification noise.
