### ISSUE TITLE
Arconaitv.us stopped working

### ISSUE THREAD

**Issue by techmouse** [streamlink/streamlink#2058]
## Plugin Issue
- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
Arconaitv.us appears to have stopped working. I don't know when it stopped working, but it hasn't worked for the past several days at least.

I'm guessing it's an SSL issue?

### Reproduction steps / Explicit stream URLs to test
https://www.arconaitv.us/stream.php?id=75

### Log output
```
[cli][info] Found matching plugin arconai for URL https://www.arconaitv.us/stream.php?id=75
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://videoserver1.org/live/_1XtoXGVgpSDwhgQ6rRMMQ/1536630586/3a2d7564baee79182ebc7b65084aabd1.m3u8')> (Could not open stream: Unable to open URL: https://videoserver1.org/live/_1XtoXGVgpSDwhgQ6rRMMQ/1536630586/3a2d7564baee79182ebc7b65084aabd1.m3u8 (HTTPSConnectionPool(host='videoserver1.org', port=443): Max retries exceeded with url: /live/_1XtoXGVgpSDwhgQ6rRMMQ/1536630586/3a2d7564baee79182ebc7b65084aabd1.m3u8 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))))
error: Could not open stream <HLSStream('https://videoserver1.org/live/_1XtoXGVgpSDwhgQ6rRMMQ/1536630586/3a2d7564baee79182ebc7b65084aabd1.m3u8')>, tried 1 times, exiting
```

**Comment by back-to** [comment]
The plugin itself is not supported by Streamlink anymore.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

but you can use `--http-no-ssl-verify` for **SSL errors**.

https://streamlink.github.io/cli.html#cmdoption-http-no-ssl-verify

**Comment by spencerthayer** [comment]
Why is Arconaitv no longer supported @back-to?

> The plugin itself is not supported by Streamlink anymore.
> 
> https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
> 
> but you can use `--http-no-ssl-verify` for **SSL errors**.
> 
> https://streamlink.github.io/cli.html#cmdoption-http-no-ssl-verify

**Comment by gravyboat** [comment]
@spencerthayer You already commented on the other issue and this doesn't add anything plus Bastimeyer already responded there. Going to lock this since it's very old.
