### ISSUE TITLE
VLC: opening a Twitch stream with the newest VLC (3.0.4) causes the video feed to be messed up

### ISSUE THREAD

**Issue by aldelaro5** [streamlink/streamlink#2060]
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Description

When opening a twitch stream via streamlink using the VLC player, streamlink reports nothing, but the video feed on vlc is messed up.  It appears mostly green with no audio, it is not watchable.

### Expected / Actual behavior

I expected to have the correct Twitch stream being displayed on VLC, not to see a messed up feed.

### Reproduction steps / Explicit stream URLs to test

1. enter the following command: `streamlink [twitch] best` where `[twitch]` is any stream's URL of a currently live stream. 
2. Observe the feed on vlc not looking correctly.

### Log output

```
[cli][debug] OS:         Linux-4.18.5-arch1-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.7.0
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL https://twitch.tv/liquidwifi
[plugin.twitch][debug] Getting live HLS streams for liquidwifi
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 526; Last Sequence: 539
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 537; End Sequence: None
[stream.hls][debug] Adding segment 537 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 538 to queue
[stream.hls][debug] Adding segment 539 to queue
[stream.hls][debug] Download of segment 537 complete
[cli][info] Starting player: /usr/bin/vlc
[stream.hls][debug] Download of segment 538 complete
[stream.hls][debug] Download of segment 539 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 540 to queue
[stream.hls][debug] Adding segment 541 to queue
[stream.hls][debug] Adding segment 542 to queue
[stream.hls][debug] Download of segment 540 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Additional comments, screenshots, etc.
Here's how VLC looks when launching the stream above when it was live:

![screenshot from 2018-09-12 06-47-30](https://user-images.githubusercontent.com/8932978/45420282-bfbc5180-b657-11e8-9d07-228566af16fd.png)

**Comment by gravyboat** [comment]
Going to close this since there's nothing we can do, if you open an issue with the VLC team please link it here in case others encounter the same issue.

**Comment by aldelaro5** [comment]
I opened an issue on VLC's end, it can be accessed here: 

https://trac.videolan.org/vlc/ticket/21200#ticket

**Comment by RenaKunisaki** [comment]
VLC version is 3.0.4. It is working in mplayer; I thought it wasn't, but I was just using it wrong.

**Comment by gravyboat** [comment]
@aldelaro5 Seems like there is a workaround for some people: https://github.com/streamlink/streamlink/issues/2072#issuecomment-422929293
