### ISSUE TITLE
[Afreecatv] Since yesterday frequently pause timer and broken files

### ISSUE THREAD

**Issue by stefan327** [streamlink/streamlink#2061]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Since yesterday, streams often open with pause timer. This happens with about 90% of streams at first streaming. The saved stream files are broken.

Streamlink 0.14.2

### Reproduction steps / Explicit stream URLs to test

This occours on all streams.

### Log output
NA

### Additional comments, screenshots, etc.
NA

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)
:-) OK

**Comment by tenminute** [comment]
I can confirm the 15 second countdown is back. 

This https://github.com/streamlink/streamlink/issues/837#issuecomment-336813730 isn't working anymore.

C:\Users\User>streamlink play.afreeca.com/brainzerg7 best
[cli][info] Found matching plugin afreeca for URL play.afreeca.com/brainzerg7
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

The annoyance of having wait for the countdown, close it, and re-open it again.

**Comment by Sdeck37** [comment]
Similiar to #837 ,you can fix this for now by replacing
`    def write(self, sequence, res, chunk_size=8192):
        if sequence.segment.key and sequence.segment.key.method != "NONE":`
with
`    def write(self, sequence, res, chunk_size=8192):
        if sequence.segment.uri.find("afreeca")!= -1 and (sequence.segment.uri.find("preloading.TS")!= -1):
            return
        if sequence.segment.key and sequence.segment.key.method != "NONE":`

**Comment by stefan327** [comment]
Thank you Sdeck37!

Your fix works. :-)
