### ISSUE TITLE
Possible to restream a twitch stream to another service?

### ISSUE THREAD

**Issue by strich** [streamlink/streamlink#2063]
## Feature Request
- [x ] This is a feature request and I have read the contribution guidelines.

### Description
We'd like to have the ability to restream an existing Twitch stream, with the streamers' permission, to another service, such as Restream.IO. Is this possible?

**Comment by gravyboat** [comment]
I'm pretty sure this is something we've discussed before and something we can't support. This is a slippery slope type issue with the potential to support illegal restreams even if the intentions are good unfortunately.

**Comment by strich** [comment]
I found that the easiest way is to simply let VLC pop up then capture the window with OBS. Though I'd prefer a headless solution, I could not work out how to pipe livestream to a protocol that OBS supported.

**Comment by Erk-** [comment]
If you need to have any overlay on it yes then it is the weasiest way if you don't need to reencode or anything you should be able to restream with ffmpeg directly.
