### ISSUE TITLE
[plugins.pandatv] support for new url pattern (subdomain) not work anymore

### ISSUE THREAD

**Issue by stefan327** [streamlink/streamlink#2065]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I think since some days the solution #1822 for subdomain url pattern is not working anymore.

Example:

```
streamlink.exe" -o test.flv "https://xingyan.panda.tv/52168" best
[cli][info] Found matching plugin pandatv for URL https://xingyan.panda.tv/52168

error: Unable to open URL: https://xingyan.panda.tv/52168 (HTTPSConnectionPool(host='xingyan.panda.tv', port=443): Read timed out. (read timeout=20.0))
```
Still works without subdomain.
(example: https://www.panda.tv/2201108)

**Comment by fozzysec** [comment]
It works well for me, according to your log I think this is your network issue.

```
PS D:\Users\fozzy> streamlink https://xingyan.panda.tv/1895885
[cli][info] Found matching plugin pandatv for URL https://xingyan.panda.tv/1895885
[cli][info] Available streams: source_http, low (worst), medium, source (best)
[cli][info] Opening stream: source_http (http)
[cli][info] Starting player: mpv --cache 2048
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Would you please check your network and try again? Feel free to provide further information and I will try to help you.

**Comment by gravyboat** [comment]
Yep it's clearly a network issue: `Read timed out.`. There's nothing we can do so I'm going to close this.
