### ISSUE TITLE
Plugin ran.de livestream

### ISSUE THREAD

**Issue by kJLRtqYn** [streamlink/streamlink#2069]
## Plugin Request

- [ x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

ran.de is a free online streaming website for all kinds of sports events. There are a lot of VoDs which can be viewed easily with e.g mpv or youtube-dl. Sadly the **livestreams** seem to be more complicated. There is a kodi plugin (3rd link) but it isn't working for me. It would be great if it were possible to watch the livestreams with mpv etc.
You can find livestreams by scrolling down on the second link and search for red "Livestream"-Buttons to the right of the current sport events.

### Example stream URLs

1. https://www.ran.de
2. https://www.ran.de/datenbank
3. https://github.com/kodinerds/repo/tree/master/plugin.video.ran_de

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
They now use DRM for some Livestreams.

```js
{
    'property_name': 'ran',
    'is_protected': True,
    'protocols': {
        'dash': {
            'drm': ['playready', 'widevine']
        },
        'hls': {
            'drm': ['fairplay']
        },
        'hss': {
            'drm': ['playready']
        }
    },
}
```
