### ISSUE TITLE
crunchyroll - weird glitching

### ISSUE THREAD

**Issue by d7lovato** [streamlink/streamlink#2087]
## Issue

- [x ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

I play a crunchyroll stream via streamlink using PotPlayer, as I like to watch on two screens. I can watch the first 2 minutes or so, and then it'll totally glitch out and skip uncontrollably. 

### Expected / Actual behavior

I expect to watch my stream in full till the end smoothly.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Please provide a proper debug log, like the issue template is asking you to do. Also, please see whether this is just a player related issue by opening the stream in another player, like VLC or MPV for example.

**Comment by bastimeyer** [comment]
No response in almost two weeks.
Closing.
