### ISSUE TITLE
FunimationNow Incapsula protection workaround

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#2088]
### Description

Incapsula have changed the way they limit automated access to the website. Their JavaScript has been obfuscated even more than before, as requires evaluating the JavaScript to be able to determine the authentication URL. 

It is now not possible for the Plugin to automatically bypass this protection. 

Originally reported in #1899.

### Workaround

As a workaround you can provide the `incap_ses` cookie to Streamlink. The cookies have unique names for each session. You will need to use your web browser to [find the cookie name and value](http://www.whatarecookies.com/view.asp), it will be for `.funimation.com` or `.funimationnow.uk`. 
For example you may see the cookie called `incap_ses_123_9321243` with a value of `SGVsbG8gdGhpcyBpcyBzb21lIGdhcmJhZ2UgZGF0YSE=`. To provide that to Streamlink you need to use the [`--http-cookie`](https://streamlink.github.io/cli.html#cmdoption-http-cookie) option, eg.

```
streamlink --http-cookie "incap_ses_123_9321243=SGVsbG8gdGhpcyBpcyBzb21lIGdhcmJhZ2UgZGF0YSE=" https://www.funimation.com/shows/fairy-tail/turbulent-showdown-natsu-vs-laxus/uncut/?lang=english
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by comath11** [comment]
It seems like the work around might not be working anymore.  I followed the instructions very carefully, but I still get the same error.  I even cleared out all of the cookies and signed in again to get a new one, but still no success.  However, there is still a chance that I am just doing something wrong, so maybe someone can verify if it works for them or not.  I can provide more information if needed.  I notice there was a commit recently related to this issue, so could that have possibly broke something?

**Comment by DevonMorris** [comment]
I'm running streamlink 1.1.1 that I installed yesterday and It's definitely working with funimation.

**Comment by thecsapprentice** [comment]
I've been experimenting with streamlink (v1.1.1) and funimation for the past 48 hours or so. Following the cookie recommendations, thus far I've experienced the following behaviors:

- Sometimes everything works great. The plugin's script is getting back good responses from the server and can correctly parse and download stream data.
- Sometimes (most times, in fact), it only receives the Incapsula page, triggering the early bail out. 

I have not successfully determined what is triggering this difference in response from the server. Watching the cookies sent, I've tried to recreate the conditions using my browser (Chrome). This has been difficult. Even with javascript disabled via the dev tools, loading the url simply returns the page for the episode. This is leading me to believe that the server is watching something other than the cookies being sent. I've also attempted to duplicate the user agent, just in case, but this seems to have no effect. 

The end result as far as I can tell is that the recommendations for cookies are unreliable at best. Either they are wrong, or there is more to it. Successfully using the tool to retrieve an episode fails more often than it succeeds and I have no way of knowing what I can do to improve success rates.

@DevonMorris I'd love to know more about what you're doing to rate a "definitely working with funimation" comment. I don't think, given what I'm seeing, that I can do the same.

**Comment by DevonMorris** [comment]
@thecsapprentice I tried it today and it seemed to be working. I just ran

```bash
streamlink --http-cookie "incap_ses_284_998813=GO0sCRJRhiLZcLM1K/rwA/5o+FwAAAAA08xVMOoTyRXRkdLakWh4Rg==" https://www.funimation.com/shows/one-piece/im-luffy-the-man-whos-gonna-be-king-of-the-pirates best &
```
and it just worked. I then tried switching videos and at first I got 
```
[plugin.funimationnow][error] Exceeded stream limit. : Uh oh! Your account is being accessed by too many devices. You can only stream to 1 screens at a time. To continue watching this video, stop playing video on one of the devices below:
Web
```
as an error. But after ~1 minute of waiting I tried again and it worked. :man_shrugging:

**Comment by thecsapprentice** [comment]
@DevonMorris That is so strange. I've never seen the second error. It either works, rarely, or gives me the Incapsula error message. Out of curiosity, do you have problems if you request multiple streams, one after another? 

After posting yesterday, I tried dumping all cookies from funimation and passing them all into streamlink. It didn't seem to make any difference, yet the session inside the browser worked fine yet ( no change to the incap_ses* cookies). Do you have any other environmental conditions I might be missing? VPN, etc? What browser are you using?

**Comment by thecsapprentice** [comment]
```
$ streamlink --http-cookie "incap_ses_976_998813=NEMUN+5+sHAIN1WAgHOLDU2e91wAAAAAHAhnOtifsDc6+RAZ/4jQAg=="  https://www.funimation.com/shows/fairy-tail/celestial-skirmish/ best
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/fairy-tail/celestial-skirmish/
[plugin.funimationnow][error] https://www.funimation.com/shows/fairy-tail/celestial-skirmish/
[plugin.funimationnow][error] This page is protected by Incapsula, please see https://github.com/streamlink/streamlink/issues/2088 for a workaround.
error: No playable streams found on this URL: https://www.funimation.com/shows/fairy-tail/celestial-skirmish/
```

I just tried it again, getting the above as the result.

**Comment by thecsapprentice** [comment]
After some research, I'm now wondering if I'm being caught by fingerprinting, as described here: It's possible that they are somehow tying specific characteristics of my browser's communication patterns into the session cookie. And when the python script attempts to use them, it looks... different... somehow, thus rendering the cookie useless, while still allowing it to work fine in the browser session.

https://docs.imperva.com/bundle/cloud-application-security/page/introducing/api-protection.htm

Honestly, it's the only thing I can think of right now..

**Comment by death-angel-141** [comment]
This thing is still not working

**Comment by gravyboat** [comment]
I'm going to close and lock this, it's been open for 2 years and the workaround no longer works.
