### ISSUE TITLE
I downloaded a new updated version of streamlink portable for windows. I ran it once. My windows command line font settings changed. The old setting is not an option to go back to anymore, ever, it seems.

### ISSUE THREAD

**Issue by left1000** [streamlink/streamlink#2093]
I downloaded a new updated version of streamlink portable for windows. I ran it once. My windows command line font settings changed. The old setting is not an option to go back to anymore, ever, it seems.

So running streamlink, the newest version, for the first time changed my font in the current command line windows on windows 7. I thought, oh, no big deal, my other command line windows still have the old font setting I like. After having closed all my command lines in windows, and also having rebooted, I don't have the chance to go back.

The original font was "Raster Fonts" 10x twenty something and the new font is "Raster Fonts" 10x18 10x18 is as big as it goes now, it won't let me select large font anymore, this makes it very hard to read my command line. It doesn't even make sense to me how streamlink could've changed my system in such a way as to remove/delete several basic default font options from my computer.... but uh it probably shouldn't've done that, now I have to either go blind or live with Consolas or Lucida Console which can still go large.

I'm sure I'll get over having my large font be fat and stylized instead of thin and simple. Still, whatever caused this is a flaw in my mind and my old copy of streamlink never did this.

Here's the exact version of the version in question:
"
v0.14.2 - Git 215d789
"

**Comment by gravyboat** [comment]
Can you recreate your issue over here on streamlink-portable please if you're using the portable installer? https://github.com/streamlink/streamlink-portable/issues/new Right now we don't have anyone actively maintaining the portable release unfortunately. I've never seen anyone have this issue though so I'm not sure what would have caused it. As far as I'm aware it doesn't modify any user settings like that. I'm going to close this and discussion can happen over there for better tracking.
