### ISSUE TITLE
ok.ru VODs

### ISSUE THREAD

**Issue by ringtvt** [streamlink/streamlink#2095]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description
i enter link in #1884 but "https://raw.githubusercontent.com/back-to/plugins/master/plugins/ok_live.py" 404: Not Found. Thanks

### Reproduction steps / Explicit stream URLs to test

1. D:\my\Streamlinkl\bin>streamlink -l debug "https://ok.ru/video/266205792931" best

### Log output

```
[cli][debug] OS:         Windows 8.1
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
error: No plugin can handle URL: https://ok.ru/video/266205792931

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> No plugin can handle URL

As already mentioned in #1884, Streamlink's ok.ru plugin doesn't support VODs.

> 404: Not Found

This was a link to a custom version of the plugin from an external repository maintained by @back-to, which is not (publicly) available anymore, hence the 404 error message. I don't know why, but he will have his reasons. I'll tag this thread as plugin enhancement request.

**Comment by ringtvt** [comment]
@bastimeyer 
Thanks for the support
So now what can I do to run the code without error?
