### ISSUE TITLE
pynsist 2.2 issue - windows installer won't build

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#2097]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

There is a new version of **pynsist**.

- new version `2.2` breaks the installer build,
- old version ` 2.1` works.

might be a bug of **pynsist**

https://github.com/takluyver/pynsist
https://pypi.org/project/pynsist/#history

### Reproduction steps / Explicit stream URLs to test

1. `./script/makeinstaller.sh`

looks like `File /r "streamlinkrc"` is the issue

http://nsis.sourceforge.net/Docs/Chapter4.html#file

### Log output

```
~~~ Running makensis ~~~
Processing config: /etc/nsisconf.nsh
Processing script file: "nsis/installer.nsi" (UTF8)
File: "streamlinkrc" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "nsis/installer.nsi" on line 174 -- aborting creation process
```

https://travis-ci.org/streamlink/streamlink/jobs/437722955#L2917-L2921

**Comment by bastimeyer** [comment]
Looks like `build/nsis/streamlinkrc` gets deleted when `pynsist` is run in [`script/makeinstaller.sh`](https://github.com/streamlink/streamlink/blob/65cedca30ec93cf3fca5cd8192fbf23189e37b73/script/makeinstaller.sh#L251-L257). Is there a file-whitelist in pynsist that prevents additional files from existing in the generated pynsist build dir?

**Comment by bastimeyer** [comment]
Ok, got confused for a sec... So it seems like pynsist is deleting the entire `build/nsis` directory before it builds its config files instead of just adding them to the existing dir.

**Comment by bastimeyer** [comment]
https://github.com/takluyver/pynsist/commit/af33ff6ea40de52caa5d79cb27061fa84ed7f016#diff-fee17e545c9246230253cc9102d3a6cc
