### ISSUE TITLE
Plugin Request  www.zee5.com

### ISSUE THREAD

**Issue by Internet2249** [streamlink/streamlink#2101]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

site:-www.zee5.com
ZEE5  is a video on demand website run by Zee Entertainment Enterprises Limited At Zee5, the online video streaming Over The Top (OTT) platform.this provide free and subscription based contents.
Please add plugin for free contents offer by zee5.com in india.

### Example stream URLs

1. ...https://www.zee5.com/tvshows/details/title/0-6-tvshow_1591012925/aap-ke-aa-jane-se-episode-183-october-5-2018-full-episode/0-1-142870
2. ...https://www.zee5.com/tvshows/details/title/0-6-127/kumkum-bhagya-episode-1203-october-5-2018-full-episode/0-1-142859
3. ...https://www.zee5.com/tvshows/details/title/0-6-366/kundali-bhagya-episode-324-october-5-2018-full-episode/0-1-142860

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
They use DRM, this won't work with Streamlink.

```
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://...",
  KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```
