### ISSUE TITLE
twitter events no longer work

### ISSUE THREAD

**Issue by sou7611** [streamlink/streamlink#2103]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Previously working Twitter Event video links no longer work.  See log clip below.

### Expected / Actual behavior

Video should play

### Reproduction steps / Explicit stream URLs to test

```
streamlink.exe --verbose "https://prod-video-eu-west-1.pscp.tv/5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw/replay_transcode/eu-west-1/periscope-replay-direct-prod-eu-west-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16907881229169821541.m3u8" best
[cli][info] Found matching plugin hls for URL https://prod-video-eu-west-1.pscp.tv/5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw/replay_transcode/eu-west-1/periscope-replay-direct-prod-eu-west-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16907881229169821541.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://twitter.com/i/live_video_stream/key?stream_name=5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw (400 Client Error: Bad Request for url: https://twitter.com/i/live_video_stream/key?stream_name=5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://prod-video-eu-west-1.pscp.tv/5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw/replay_transcode/eu-west-1/periscope-replay-direct-prod-eu-west-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16907881229169821541.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://prod-video-eu-west-1.pscp.tv/5nxOetQ9WyvLjPl2mJMAZLZoT-SHU_B-jgKdXQObJfs9_GLP_YsE7pnibzBPy9_KvOcmE3tbGGovw5Hq7rYokw/replay_transcode/eu-west-1/periscope-replay-direct-prod-eu-west-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16907881229169821541.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
> [stream.hls][error] Failed to create decryptor
> 400 Client Error: Bad Request

The server is returning an error while requesting the keys to decrypt the HLS segments. This is not a Streamlink issue. It's possible that you need to send certain headers (eg. a `Referer` or `User-Agent` header or auth data) with each request. See the `--http-header` parameter for that.

**Comment by back-to** [comment]
@sou7611 
is the web url still avaliable? `https://twitter.com/i/events/...`

you might need to sent some cookies with the m3u8 url
https://github.com/rg3/youtube-dl/issues/10806#issuecomment-253679319

**Comment by back-to** [comment]
if you ever see this issue again,
post the `CURL` data from your browser here

closing, as there are no examples to every solve this issue.

**Comment by jrhessey** [comment]
I am getting the same error as above for twitter.  I've tried passing various headers and cookies separate, together, upside down and inside out (joking about the later) to no avail...

Here is the broadcast link
[https://twitter.com/i/broadcasts/1YqKDBgoqWVJV](https://twitter.com/i/broadcasts/1YqKDBgoqWVJV)

Here is the M3U8 link
[https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/1xNh8ajo-28KxXQtiq2lcF43jfjVhsitiU4Dnu5yhdSFXcyTZn0JHivL-ASZmae0NTuYlkOKB6-NyoAeubl-7g/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16881184567750375944.m3u8?type=replay](https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/1xNh8ajo-28KxXQtiq2lcF43jfjVhsitiU4Dnu5yhdSFXcyTZn0JHivL-ASZmae0NTuYlkOKB6-NyoAeubl-7g/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16881184567750375944.m3u8?type=replay)

I believe I have found the key link as well
[https://twitter.com/i/live_video_stream/key?stream_name=1xNh8ajo-28KxXQtiq2lcF43jfjVhsitiU4Dnu5yhdSFXcyTZn0JHivL-ASZmae0NTuYlkOKB6-NyoAeubl-7g](https://twitter.com/i/live_video_stream/key?stream_name=1xNh8ajo-28KxXQtiq2lcF43jfjVhsitiU4Dnu5yhdSFXcyTZn0JHivL-ASZmae0NTuYlkOKB6-NyoAeubl-7g)

Is there anything else you would need?
