### ISSUE TITLE
 Plugin Request www.voot.com

### ISSUE THREAD

**Issue by Internet2249** [streamlink/streamlink#2105]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Voot, launched in March 2016, forms the digital arm of Viacom 18. It is Viacom 18's advertising-led video-on-demand platform that offer free and subscription based contents.Voot is available only in India, and hosts over 40,000 hours of video content that includes shows from channels  Colors TV, MTV India etc.
please add support for free contents available  in this website.

### Example stream URLs

1. ...https://www.voot.com/shows/silsila/1/606786/mauli-nandini-at-the-same-place-/640071
2. ...https://www.voot.com/shows/bigg-boss-s12/12/602865/-jasleenjalota-out-/640820
3. ...https://www.voot.com/shows/roop/1/605354/ranveer-consoles-roop/640274

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
As per the plugin guidelines, we aren't supporting sites that are mostly VODs. Maybe take a look at youtubedl and see if they support the site.
