### ISSUE TITLE
Plugin Request www.sonyliv.com

### ISSUE THREAD

**Issue by Internet2249** [streamlink/streamlink#2106]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

SonyLIV is an Indian general entertainment, Video on demand service that is owned by Sony Pictures Networks India Pvt. Ltd. based in Mumbai, Maharashtra, India.SonyLIV's Library consists of 18 years of content from the Sony Entertainment Network Channels in India Sony TV, SAB TV,Sony MIX, Sony Max, Sony MAX 2, SET PIX, AXN and Animax .they provide free and subscription based premium contents.
sonyliv Indian content are free.

### Example stream URLs

1. ...https://www.sonyliv.com/details/episodes/5846054799001/8-October-2018---Beechwale-Bapu-Dekh-Raha-Hai---Tax-Rebate
2. ...https://www.sonyliv.com/details/episodes/5846008851001/8-October-2018---Porus---The-Magadha-Empire
3. ...https://www.sonyliv.com/details/episodes/5843415455001/2-October-2018---Beechwale-Bapu-Dekh-Raha-Hai---Meet-The-Beechwale

### Additional comments, screenshots, etc.
I'm sure adding Sonyliv plugin to streamlink would increase its users.

**Comment by gravyboat** [comment]
Please slow down on the plugin requests. We have limited resources and your first request was closed due to DRM. Please confirm if both this and the other site use DRM and update the request with that information.

**Comment by Internet2249** [comment]
I don’t think Sonyliv & Voot use DRM Even Zee5 don’t use DRM In chrome 
Following are the M3U8 Links Extracted From browser (Chrome)


Website:-www.Sonyliv.com
 Link:-https://www.sonyliv.com/details/episodes/5847001830001/10-October-2018---Main-Maayke-Chali-Jaaungi-Tum-Dekhte-Rahiyo---The-Outing
 M3u8 Link Extracted From Chrome Browser:-https://streaming.sonyliv.com/show_set_mainmaaykechalijaaungitumdekhterahiyo_ep22.m3u8
C:\Users\dell>streamlink.exe -f -v -l debug -h https://streaming.sonyliv.com/show_set_mainmaaykechalijaaungitumdekhterahiyo_ep22.m3u8
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin hls for URL https://streaming.sonyliv.com/show_set_mainmaaykechalijaaungitumdekhterahiyo_ep22.m3u8
[plugin.hls][debug] URL=https://streaming.sonyliv.com/show_set_mainmaaykechalijaaungitumdekhterahiyo_ep22.m3u8; params={}
Available streams: 144p (worst), 216p, 288p, 360p, 540p, 720p (best)

Website:-www.Voot.com
Link:-https://www.voot.com/shows/tu-aashiqui/1/538833/randhir-confesses-his-love/641000
M3u8 Link Extracted From Chrome Browser:-https://vootvideo.akamaized.net/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_,e1swaxzu,djbmbdwq,qhvka3p8,y3qbk7dw,kmazugay,/name/a.mp4/index.m3u8.urlset/master.m3u8?__hdnea__=st=1539200821~exp=1539204421~acl=/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_*~hmac=fffda3ecd7e4623adb01a9d7bc5a5a8a197bba1d7e557eec4ecb237bdad5a21c
C:\Users\dell>streamlink.exe -f -v -l debug -h https://vootvideo.akamaized.net/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_,e1swaxzu,djbmbdwq,qhvka3p8,y3qbk7dw,kmazugay,/name/a.mp4/index.m3u8.urlset/master.m3u8?__hdnea__=st=1539200821~exp=1539204421~acl=/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_*~hmac=fffda3ecd7e4623adb01a9d7bc5a5a8a197bba1d7e557eec4ecb237bdad5a21c
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin hls for URL https://vootvideo.akamaized.net/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_,e1swaxzu,djbmbdwq,qhvka3p8,y3qbk7dw,kmazugay,/name/a.mp4/index.m3u8.urlset/master.m3u8?__hdnea__=st=1539200821~exp=1539204421~acl=/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_*~hmac=fffda3ecd7e4623adb01a9d7bc5a5a8a197bba1d7e557eec4ecb237bdad5a21c
[plugin.hls][debug] URL=https://vootvideo.akamaized.net/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_,e1swaxzu,djbmbdwq,qhvka3p8,y3qbk7dw,kmazugay,/name/a.mp4/index.m3u8.urlset/master.m3u8?__hdnea__=st=1539200821~exp=1539204421~acl=/s/enc/hls/p/1982551/sp/198255100/serveFlavor/entryId/0_92kxjc69/v/2/pv/1/ev/12/flavorId/0_*~hmac=fffda3ecd7e4623adb01a9d7bc5a5a8a197bba1d7e557eec4ecb237bdad5a21c; params={}
Available streams: 64k (worst), 272p, 360p_alt2, 360p (best)

Website:-www.Zee5.com
These link are extreacted from chrome Browser 
if Mozila firefox use then DRM is in play and get link:-https://zee5vod.akamaized.net/drm/1080p/tvshows/ONAIR_SHOWS/And_Tv/October2018/10102018/Agnifera_Ep406_10102018_hi.mp4/audio/en/mp4a/init.mp4
Link:-https://www.zee5.com/tvshows/details/agnifera/0-6-316/agnifera-episode-406-october-10-2018-full-episode/0-1-143774

M3u8 Link Extracted From Chrome Browser:-https://zee5vodnd.akamaized.net/hls/1080p/tvshows/ONAIR_SHOWS/And_Tv/October2018/10102018/Agnifera_Ep406_10102018_hi.mp4/index.m3u8?hdnea=st=1539197696~exp=1539200696~acl=/*~hmac=887c6480e361c50c91d38e0e0ba706e3b53040197b5db69bbc530c9a4eabbce2

C:\Users\dell>streamlink.exe -f -v -l debug -h https://zee5vodnd.akamaized.net/hls/1080p/tvshows/ONAIR_SHOWS/And_Tv/October2018/10102018/Agnifera_Ep406_10102018_hi.mp4/index.m3u8?hdnea=st=1539197696~exp=1539200696~acl=/*~hmac=887c6480e361c50c91d38e0e0ba706e3b53040197b5db69bbc530c9a4eabbce2
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin hls for URL https://zee5vodnd.akamaized.net/hls/1080p/tvshows/ONAIR_SHOWS/And_Tv/October2018/10102018/Agnifera_Ep406_10102018_hi.mp4/index.m3u8?hdnea=st=1539197696~exp=1539200696~acl=/*~hmac=887c6480e361c50c91d38e0e0ba706e3b53040197b5db69bbc530c9a4eabbce2
[plugin.hls][debug] URL=https://zee5vodnd.akamaized.net/hls/1080p/tvshows/ONAIR_SHOWS/And_Tv/October2018/10102018/Agnifera_Ep406_10102018_hi.mp4/index.m3u8?hdnea=st=1539197696~exp=1539200696~acl=/*~hmac=887c6480e361c50c91d38e0e0ba706e3b53040197b5db69bbc530c9a4eabbce2; params={}
[stream.hls][debug] Using external audio tracks for stream 144p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 240p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 360p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 480p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 576p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 720p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 1080p (language=en, name=English)
Available streams: 144p (worst), 240p, 360p, 480p, 576p, 720p, 1080p (best)

**Comment by qkolj** [comment]
Both this and #2105 should be closed because as per [plugin request guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests), VoD-only websites are out of scope of this project.
