### ISSUE TITLE
Support for SHOW Webtv

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#211]
Hi,

this is from the official SHOW TV (FTA Channel) Livestream:

http://www.showtv.com.tr/canli-yayin/showtv

Would be very nice :)

Greetings

**Comment by Rotarum** [comment]
Beardypig can you have a look please ?

You are my hope 👍

**Comment by gravyboat** [comment]
@Rotarum No need to ping people again in issues like this, people will get around to it if they can!

**Comment by Rotarum** [comment]
Ok np 👍
