### ISSUE TITLE
tvplayer.com 401 Unauthorized since yesterday (2018-10-10)

### ISSUE THREAD

**Issue by mkbloke** [streamlink/streamlink#2110]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Since sometime yesterday, I think the website must have changed at tvplayer.com, as the plugin can now no longer obtain any streams. It was working fine the day before (2018-10-09).

### Reproduction steps / Explicit stream URLs to test

$ streamlink --config ./streamlinkrc tvplayer.com/watch/itv2
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/itv2
error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'status': '401 Unauthorized' does not equal '200 OK'

### Log output

```
$ streamlink --config ./streamlinkrc --loglevel debug tvplayer.com/watch/itv2
[cli][debug] OS:         Linux-4.9.0-6-amd64-x86_64-with-debian-9.5
[cli][debug] Python:     3.5.3
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.12.4), Socks(1.6.5), Websocket(0.37.0)
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/itv2
[cli][debug] Plugin specific arguments:
[cli][debug]  --tvplayer-email=user@email.com (email)
[cli][debug]  --tvplayer-password=******** (password)
[plugin.tvplayer][debug] Logging in as user@email.com
[plugin.tvplayer][debug] Got stream attributes: {'resource': 'itv2', 'channel_id': '556', 'token': '958fdd7772e479fce26b6c6bcdb9b2df0e7074c9991c68b18abf16eff92d9d03'}
[plugin.tvplayer][debug] Getting stream information for resource=itv2
[plugin.tvplayer][debug] Context data: {'platform': {'key': 'chrome'}, 'validate': 'eyJ0b2tlbiI6IjliZTQwNDI3ZjIxZDIyZjhhZGE3NzJkNzk4MzEwZDY3IiwiZXhwaXJ5IjoiMjAxOC0xMC0xMVQwOTowNjowOSswMDAwIn0=', 'token': 'jOmSI3IYyPzL1nvfOBl3Z29vLnzsXVL2ZZKwnjwiPQj7cwnbkaTiwv1O116F4yqt5ARFkTOeTpVJTEks'}
error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'response': Unable to validate result: Key 'stream' not found in {'error': 'Stream request could not be verified, if the error persists please contact support.'}

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
This works right now:

streamlink.exe --tvplayer-email jadranx@xxxx.com --tvplayer-password xxxxxxxx https://tvplayer.com/watch/bbcfour best

**Comment by mkbloke** [comment]
Interesting.  It's not working for me, even if I specify email/password on the command line and try BBC Four on best quality, as you have above.  I still get the same result:

$ streamlink --tvplayer-email email+mbox@gmail.com --tvplayer-password xxxxxxxx https://tvplayer.com/watch/bbcfour best
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/bbcfour
error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'status': '401 Unauthorized' does not equal '200 OK'

I wonder if it's not logging in properly.  The streamlinkrc file I've been using hasn't changed though and I can log into tvplayer.com on the website with the same credentials.  The only slight difference between my set up and yours is perhaps my use of the Gmail email+mbox@gmail.com format.

Perhaps another issue could be my use of IPv6.  My IPv4 address is UK, whereas the IPv6 address is US (via Hurricane Electric tunnel).  It's been working before though.  Having said that, my laptop can play via the website using the same IPv4 address and an IPv6 block also via HE.

I will try a network dump to see if I can get any more information.

Thanks for your response.

**Comment by mkbloke** [comment]
I created another account on tvplayer.com with the basic user@email.com format, but I still get the same result testing with that account too.

**Comment by beardypig** [comment]
From the logs it looks like a format change. I will take a look when I can...

**Comment by mkbloke** [comment]
Thank you for checking.  It's rather infuriating that two people have now stated they have no problem!

Here's another interesting thing - I can get different error responses from the same command invocation at different times:

```
$ streamlink --loglevel debug --tvplayer-email user@email.com --tvplayer-password xxxxxxxx tvplayer.com/watch/itv2 best
[cli][debug] OS:         Linux-4.9.0-6-amd64-x86_64-with-debian-9.5
[cli][debug] Python:     3.5.3
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.12.4), Socks(1.6.5), Websocket(0.37.0)
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/itv2
[cli][debug] Plugin specific arguments:
[cli][debug]  --tvplayer-email=user@email.com (email)
[cli][debug]  --tvplayer-password=******** (password)
[plugin.tvplayer][debug] Logging in as user@email.com
[plugin.tvplayer][debug] Got stream attributes: {'resource': 'itv2', 'channel_id': '556', 'token': '7ef4114708aea7403890a4631b52e9ec95bf44f838562b15bf0b0b9fea223343'}
[plugin.tvplayer][debug] Getting stream information for resource=itv2
[plugin.tvplayer][debug] Context data: {'validate': 'eyJ0b2tlbiI6Ijc2ZDJlNDdiNDBjYTA5NDEzMDM2YWUwZjZhMDgwZDgzIiwiZXhwaXJ5IjoiMjAxOC0xMC0xMVQxODozODoxMyswMDAwIn0=', 'platform': {'key': 'chrome'}, 'token': 'eGm0Uk5P52Cbwa0B0tUHtmfbcC0rVjGTf8kFCMdQkgBAR5RZGXt7UoNL52Kpjpi7jKs9HCExtk9OXqDD'}
error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'response': Unable to validate result: Key 'stream' not found in {'error': 'Stream request could not be verified, if the error persists please contact support.'}

$ streamlink --loglevel debug --tvplayer-email user@email.com --tvplayer-password xxxxxxxx tvplayer.com/watch/itv2 best
[cli][debug] OS:         Linux-4.9.0-6-amd64-x86_64-with-debian-9.5
[cli][debug] Python:     3.5.3
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.12.4), Socks(1.6.5), Websocket(0.37.0)
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/itv2
[cli][debug] Plugin specific arguments:
[cli][debug]  --tvplayer-email=user@email.com (email)
[cli][debug]  --tvplayer-password=******** (password)
[plugin.tvplayer][debug] Logging in as user@email.com
[plugin.tvplayer][debug] Got stream attributes: {'channel_id': '556', 'resource': 'itv2', 'token': '26c752674c790b7e08d334c7fde848b36d7ffa23e7be0faf27931e63db6c478b'}
[plugin.tvplayer][debug] Getting stream information for resource=itv2
[plugin.tvplayer][debug] Context data: {'validate': 'eyJ0b2tlbiI6IjBjY2Q0YzcyOTA5ZDg1NGFhYzY4ODQ3ZmIxZjZkOTE2IiwiZXhwaXJ5IjoiMjAxOC0xMC0xMVQxODozODoxOSswMDAwIn0=', 'token': 'A3fZQzVLlmyNH8143wN6UpbdYB0mrqrZHXXG7mDv2oVyTNVM7DDaqHgp7Gs4zS2ltJWWP1Mk8B0pJWFp', 'platform': {'key': 'chrome'}}
error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'status': '401 Unauthorized' does not equal '200 OK'
```

**Comment by mkbloke** [comment]
The latest news is that this problem is now appearing on the tvplayer.com website as well, but only since today - the website was OK yesterday.

I have emailed their support people.  I'll update here when I hear back from them.

![screenshot from 2018-10-12 14-00-09](https://user-images.githubusercontent.com/1661072/46871310-e58c7000-ce28-11e8-963e-74ad46095122.png)

**Comment by mkbloke** [comment]
OK, so after a fair bit of messing around and after saying previously that I didn't think it was an issue with the Hurricane Electric IPv6 block, it turned out to be the IPv6 block!

I turned off IPv6 on the laptop as a full test and streamlink started working again.  I guess tvplayer.com have very recently changed their geo-IP checking for IPv6 addresses.  The website player must make use of IPv4 only as part of the initial player set-up for dual stack clients that default to preferring IPv6 first and then fall back to IPv4, as mine does.

As a workaround, I am now starting streamlink with a wrapper shared object library via LD_PRELOAD, which replaces the libc getaddrinfo() function with one that doesn't return IPv6 addresses.

https://github.com/mkbloke/libwrapper-getaddrinfo

**Comment by beardypig** [comment]
Thanks for the update @mkbloke

**Comment by mkbloke** [comment]
Just one last update for you, @beardypig.

I've received a reply from support, confirming that the issue "was the result of a third party validation method, which was only able to recognise old IPv4 IP addresses".

Playing over IPv6 with streamlink is now working again.  Yay!

I think I'll leave my IPv4 only solution in place for now though.
