### ISSUE TITLE
streamlink and audacious

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#2111]
### Description

This is question about using streamlink with a player with audio equalizer.

### Expected / Actual behavior

Without audio equalizer my "M-Audio Audiophile 24/96 2496 PCI Soundcard" is just another audio card.

I can get radio broadcast ( audio only stream ) flowing with streamlink which I cannot get with mplayer.exe.
This is why streamlink + mplayer.exe.

I don't know if it is realistic to expect Audacious to work with Streamlink 
Audacious just hangs saying: Buffering ...

Has anyone an idea if and how Audacious could be used with Streamlink ?
____________________

### Reproduction steps / Explicit stream URLs to test

```
streamlink.exe http://radio.pauta.cl/playlist/stream.m3u8 best --stdout| mplayer.exe - -af equalizer=8:4:-3:-1:0:1:2:3:2:3
```

### Additional comments, screenshots, etc.
```

C:\>streamlink.exe http://radio.pauta.cl/playlist/stream.m3u8 best --stdout| mplayer.exe - -af equalizer=8:4:-3:-1:0:1:2:3:2:3
MPlayer Redxii-SVN-r38116-6.2.0 (i686) (C) 2000-2018 MPlayer Team
Using FFmpeg N-91792-g17c635e605 (2018-09-04 21:47:56 +0200)
Compiled on 2018-09-05 02:35:02 EDT (rev. 1)

Playing -.
Reading from stdin...
libavformat version 58.17.106 (internal)
[cli][info] Found matching plugin hls for URL http://radio.pauta.cl/playlist/stream.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
Cannot seek backward in linear streams!
Seek failed
TS file format detected.
Cannot seek backward in linear streams!
Seek failed
NO VIDEO! AUDIO AAC(pid=256) NO SUBS (yet)!  PROGRAM N. 1
Cannot seek backward in linear streams!
Seek failed
Load subtitles in ./
Load subtitles in C:/P/M/mplayer/sub/
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 58.27.101 (internal)
AUDIO: 44100 Hz, 2 ch, floatle, 0.0 kbit/0.00% (ratio: 0->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
AO: [dsound] 44100Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> If somebody knows how to translate mplayer's numbers into VLC's please comment on this post

How is this question related to Streamlink? You should ask this somewhere else, eg. on a VLC support forum or so.
https://wiki.videolan.org/VLC_command-line_help/

> how to set audio equalizer with mpv

Another question which is totally unrelated to Streamlink.
https://mpv.io/manual/stable/#audio-filters
https://github.com/mpv-player/mpv/issues

> I don't know if it is realistic to expect Audacious to work with Streamlink

As long as your chosen player is able to read from the selected transport method (`stdin` by default), there shouldn't be any problems.
https://streamlink.github.io/cli.html#cmdoption-n
https://streamlink.github.io/cli.html#cmdoption-player-continuous-http
https://streamlink.github.io/cli.html#cmdoption-player-external-http
https://streamlink.github.io/cli.html#cmdoption-player-passthrough

btw, posting text output as a screenshot is never a great idea...
> [*If your report includes log output, please provide it as text in multi-line code blocks if possible for better readability.*](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues)

**Comment by johnthecracker** [comment]
These are all streamlink players so I think that it is related.

I looked at vlc and mpv links you posted earlier but was not good enough to make equalizer working exactly like mplayer's.

I have to look more at audacious to see if I work something out.

**Comment by johnthecracker** [comment]
I worked something out...

Here are more details for others who might be interested in the same topic.

streamlink.exe --player-continuous-http --player=audacious.exe http://radio.pauta.cl/playlist/stream.m3u8 best

```
[cli][info] Found matching plugin hls for URL http://radio.pauta.cl/playlist/stream.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Starting player: audacious.exe
[cli][info] Got HTTP request from Audacious/3.10 neon/0.30.2
[cli][info] Opening stream: live (hls)
```
<a href='https://postimg.cc/tsb5NYVt' target='_blank'><img src='https://i.postimg.cc/tsb5NYVt/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by bastimeyer** [comment]
> Can someone post one example of usage please

?
The player has to support reading its input from a named pipe. There is no special usage. You either set the parameter and let Streamlink create a named pipe and write its data there, or you don't.
https://en.wikipedia.org/wiki/Named_pipe

I'm closing the thread, since Audacious seems to be working when choosing one of the HTTP transport methods.
