### ISSUE TITLE
Widevine DRM not work with dash plugin

### ISSUE THREAD

**Issue by idealsat** [streamlink/streamlink#2117]
I using dash mpd link with streamlink but its not working because its protected with Widevine DRM ..streamlink support Widevine DRM .?

thanks

**Comment by back-to** [comment]
> ..streamlink support Widevine DRM .?

No

**Comment by savskii** [comment]
Hi guys, any update on this? If dash is working and we have valid license keys for Widevine which is linked to .mpd stream why cant we have Widevine  DRM working? all we need is like --http-header  "licenseurl=" or something :-)  as it works perfect here hxxp://bitmovin.com/demos/drm
