### ISSUE TITLE
[Assertion Failed] Trying to get Streamlink working with OpenCV

### ISSUE THREAD

**Issue by remcova** [streamlink/streamlink#2123]
## Plugin Issue
- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description
I'm trying to get streamlink working with opencv, unfortunately it seems streamlink can't put the input into the frame. I get the assertion failed error from OpenCV. Or did I miss something here in my code?

### Reproduction steps / Explicit stream URLs to test
1. Code
[youtube_test.txt](https://github.com/streamlink/streamlink/files/2496136/youtube_test.txt)

2. `python youtube_test.py https://www.youtube.com/watch?v=IFMzbFyv0sY`

### Log output

>  info:__main__:Loading stream https://manifest.googlevideo.com/api/manifest/hls_playlist/id/IFMzbFyv0sY.0/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r1---sn-25ge7nse.googlevideo.com/playlist_type/DVR/gcr/us/ei/99_JW87WDJSQ1wbihZ2oDQ/mm/32/mn/sn-25ge7nse/ms/lv/mv/u/pl/23/dover/11/keepalive/yes/mt/1539956537/ip/35.241.130.76/ipbits/0/expire/1539978327/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,ei,mm,mn,ms,mv,pl/signature/270644DCB50A64616DF68375A3BDE0FF795D1192.4F99BE92EF339860BDAFD1EED8D7F2036D07DE10/key/dg_yt0/playlist/index.m3u8
waiting 10 secondes
Traceback (most recent call last):
  File "youtube_test.py", line 59, in <module>
    main(opts.url, opts.quality, opts.fps)
  File "youtube_test.py", line 34, in main
    cv2.imshow('frame', frame)
cv2.error: OpenCV(3.4.3) /io/opencv/modules/highgui/src/window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'

**Comment by back-to** [comment]
**You are at the wrong place,**
Streamlink is only there for the `stream_url` it doesn't do anything else.

You might find some help here http://answers.opencv.org/questions/

also your test file doesn't match your error output.
