### ISSUE TITLE
Request:  Twitch Chat IN VLC Player

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink#2124]
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Is there any command to include twitch chat in VLC player? Perhaps something that allows us to adjust where we want it (top left, top right, top middle, bottom middle etc) and opacity levels?

**Comment by gravyboat** [comment]
VLC (and every other video player as far as I'm aware) doesn't support the protocol for the chat. In addition when you are playing the stream the chat data isn't even downloaded, it's just the video. You may want to take a look at https://github.com/streamlink/streamlink-twitch-gui as it has integration for various chat tools (https://github.com/streamlink/streamlink-twitch-gui/wiki/Chat-configuration). But it's not going to operate like the Twitch page does.
