### ISSUE TITLE
Azerbaycan stations 

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#2125]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

I want see the LiveStream over Streamlink Plugin 

### Expected / Actual behavior

The livestreams can be played on the page http://www.idmantv.az via the Firefox browser.
The site includes the broadcasters AZTV, Idman TV and Medeniyet TV
About the VLC player, it is not possible because the transmitter permanently tokens changes, the Streamlinkplugin should be able to handle it.

### Additional comments, screenshots, etc.

 
![idman tv](https://user-images.githubusercontent.com/36420635/47272680-7bdb3700-d589-11e8-99ec-39b7a683bedc.JPG)

 AZ TV 
http://185.102.219.82/5929820/tracks-v1a1/index.m3u8?token=
http://player.tvibo.com/aztv/5929820

Medeniyet
http://185.102.219.82/6858270/tracks-v1a1/index.m3u8?token=
http://player.tvibo.com/aztv/6858270/

Idman TV 
http://185.102.219.82/3977238/tracks-v1a1/index.m3u8?token=
http://player.tvibo.com/aztv/3977238/

**Comment by qkolj** [comment]
Are there different URLs for these three channels? How would a user choose which channel to watch? Also, if you extract `.m3u8` URL from your browser, running `streamlink http://185.102.219.82/6858270/index.m3u8?token=... best` can play the stream without dropping.

**Comment by dreamboxco** [comment]
in first Post now with the stream links
