### ISSUE TITLE
Bilibili Live error

### ISSUE THREAD

**Issue by aliofwind** [streamlink/streamlink#2126]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Bilibili Live error

### Reproduction steps / Explicit stream URLs to test

1. https://live.bilibili.com/3
2. https://live.bilibili.com/14047
3. https://live.bilibili.com/*

### Log output

```
C:\Users\aliof>streamlink -p potplayermini64 https://live.bilibili.com/3 best
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/3
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ()
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by qkolj** [comment]
I cannot reproduce your issue, `streamlink https://live.bilibili.com/3 best` works for me without any problems. Are you sure you are using the latest version?

**Comment by aliofwind** [comment]
bililive team said that they modified the address of the playurl yesterday, but the original address was restored after the test. thanks

**Comment by undeadking** [comment]
same problem again

```
streamlink https://live.bilibili.com/3 best -l debug
[cli][debug] OS:         macOS 10.13.6
[cli][debug] Python:     3.7.0
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/3
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ()
```
