### ISSUE TITLE
Huomao plugin not work

### ISSUE THREAD

**Issue by kesdoputr** [streamlink/streamlink#2132]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
I found huomao plugin seems not work, i can use browser to watch stream but
streamlink says no playable stream

### Reproduction steps / Explicit stream URLs to test

1. https://www.huomao.com/9755
2. https://www.huomao.com/777777
3. https://www.huomao.com/888

### Log output

```
[cli][info] Found matching plugin huomao for URL https://www.huomao.com/888
[plugin.huomao][error] Failed to extract stream_info.
error: No playable streams found on this URL: https://www.huomao.com/888
```

**Comment by kesdoputr** [comment]
Thanks for the quickly fix, tested and all ok.

**Comment by bastimeyer** [comment]
Let's keep this thread open until the PR gets merged...
