### ISSUE TITLE
Facebook Live Broken for some Streams?

### ISSUE THREAD

**Issue by TPME** [streamlink/streamlink#2133]
- [x] This is a bug report and I have read the contribution guidelines.

### Log output

When trying to use streamlink v0.14.2 with a Facebook Live stream (namely ESL, https://www.facebook.com/WatchESLOne/videos/796813817377003/), it returns the following:

```
[cli][debug] OS:         Linux-4.15.0-34-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/WatchESLOne/videos/796813817377003/
[plugin.facebook][debug] Falling back to playlist regex
error: No playable streams found on this URL: https://www.facebook.com/WatchESLOne/videos/796813817377003/
```

### Expected / Actual behavior

Streamlink should be able to fetch the playable stream.

### Reproduction steps / Explicit stream URLs to test

1. Try and use streamlink on https://www.facebook.com/WatchESLOne/videos/796813817377003/

### Comments

I'm wondering why this happens. The stream from ESL does not require the user to be logged in. A technical reason? Maybe because of the provided high quality?

**Comment by back-to** [comment]
> The stream from ESL does not require the user to be logged in

it does, `You must log in to continue.`

closing as this is not supported by Streamlink

**Comment by leio** [comment]
You don't need to be logged in to view this in the browser. These live streams are routinely shown on main page as well, without such dialog, and cancelling the dialog in the specific place will result in the stream still playing - the login is for the comments on the side probably.
There might be technical issues on how it's streamed, to not work with streamlink existing support, but the assert that user needs to be logged in is false.

**Comment by leio** [comment]
I mean, yes, it might want you to log in now for watching it afterwards (when the live stream has ended), but the live stream doesn't, while it's still running, currently https://www.facebook.com/WatchESLOne/videos/112851819618116/

**Comment by TPME** [comment]
I didn't know you can still comment while the issue is closed - thanks for defending me @leio , as I originally stated in the OP "The stream from ESL does not require the user to be logged in." and got my thread closed nonetheless.

@back-to please reconsider. Thank you.

**Comment by xMikasa** [comment]
esl live stream is available for view without being logged in. Its a valid issue.

**Comment by xMikasa** [comment]
i found posts that have included ways to watch these streams on vlc. one is this one https://www.reddit.com/r/DotA2/comments/9s2zb8/i_know_esl_facebook_stream_is_hated_but_im_really/e8m46fb/

the other one is https://www.reddit.com/r/GlobalOffensive/comments/7xufbp/how_to_watch_the_esl_facebook_stream_in_vlc_to/

same method but can view the stream without having to login. I think stream link should be capable of this too.

**Comment by back-to** [comment]
> I didn't know you can still comment while the issue is closed

since you are the author, you should also be able to reopen this issue yourself.

> "The stream from ESL does not require the user to be logged in."  and got my thread closed nonetheless.

well, it does when the stream is offline.

**your first post just doesn't have enough details**

---

_summary_

- different player `tahoe` for livestreams, currently not supported
- vod might be private if the stream is offline
