### ISSUE TITLE
Streamlink - plugin Zattoo Error 403 - Question

### ISSUE THREAD

**Issue by granthammerha** [streamlink/streamlink#2135]
Two E2 boxes stop streaming with the same error message  "client error 403". What could be the cause ? 

........., yesterday_uk, yourfamily, zdf, zdf-info, zdfneo, zee_one
[plugin.zattoo][debug] CHANNEL ID: 3plus
[plugin.zattoo][error] Unable to open URL: https://zattoo.com/zapi/watch (403 Client Error: Forbidden for url: https://zattoo.com/zapi/watch)
[streamlinksrv][error] No playable streams found on this URL: https://zattoo.com/watch/3plus
127.0.0.1 - - [24/Oct/2018 17:26:39] "GET /https://zattoo.com/watch/3plus HTTP/1.1" 200 -

**Comment by back-to** [comment]
try a newer plugin version

https://raw.githubusercontent.com/streamlink/streamlink/master/src/streamlink/plugins/zattoo.py

also your issue doesn't have enough details

**Comment by granthammerha** [comment]
I use the following original version: 

streamlinksrv][info] Port:          8088
[streamlinksrv][info] OS:            Linux-3.14.28-1.12-armv7l-with-glibc2.4
[streamlinksrv][info] Python:        2.7.9
[streamlinksrv][info] Streamlink:    0.14.2 / 06.07.2018
[streamlinksrv][debug] Options Parser: 0.1.7
[streamlinksrv][info] Requests(2.12.4), Websocket(0.48.0)

The newer version (in your link) is installed now on one Enigma2 device and I can confirm that this works fine. Many thanks , I was trying to find out the root cause but w/o any success.
This support work is very much appreciated.
