### ISSUE TITLE
Streamlink decrypt error

### ISSUE THREAD

**Issue by Mrconfusedasshit** [streamlink/streamlink#2138]
This is completely kicking my a$$. Trying the following syntax I keep getting an error that I have shown below, I have read a previous issue that there should be a Key that you can snoop out, that seems to have changed and the only thing I found was a UNID in the cookies. I keep passing that along but obviously some other information is needed. Any help is appreciated at this point I dont even care about the game anymore  just want to see how this works.

Syntax:
streamlink -ldebug --http-cookie "UNID=c25ba936-3b9b-476d-8ee8-1d5e29dca02d" "hls://https://content-auso2.uplynk.com/67420362790f4dc9bff310fe2e5dd49e/c.m3u8" best -o "c:\desktop\1.mp4"

Output error:
Failed to create decryptor: Unable to open URL: https://content-auso2.uplynk.com/check2?b=67420362790f4dc9bff310fe2e5dd49e&v=67420362790f4dc9bff310fe2e5dd49e&r=c (403 Client Error: Forbidden for url: https://content-auso2.uplynk.com/check2?b=67420362790f4dc9bff310fe2e5dd49e&v=67420362790f4dc9bff310fe2e5dd49e&r=c)

**Comment by 10mins** [comment]
You are missing some header or cookie. It is impossible to help without the login information and the original source url....

**Comment by Mrconfusedasshit** [comment]
Yes I agree that some header or cookie for authentication is missing. Problem is I have no idea what else to look for, only thing resembling an authorization that i could find was that UNID cookie which I am passing along, I was trying to get some help and see if anybody has any idea what else I need to include or keywords to look for with the snooper.
Here is the link to the stream:
http://www.espn.com/watch/player?id=4f3cbfca-a40d-496a-88b4-702cf354fd8b

Thanks,

**Comment by Mrconfusedasshit** [comment]
alright this can be closed. HTTP headers solved the problem.

**Comment by besweeet** [comment]
@Mrconfusedasshit Which headers did you end up using? Having the same problem for a similar platform.
