### ISSUE TITLE
Streamlink on Archlinux, quick update. ;-)

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#214]
So `python-requests-2.12.1-1` entered the extra repo and I had to revert https://github.com/streamlink/streamlink/pull/186  so it would build and start.

That breaks youtube and I've opened an issue for 'requests' package in arch.
https://bugs.archlinux.org/task/51951

Either until that idna PR I liked above is merged in next release of requests or the package is patched in archlinux, I've made a patched package for myself if anyone needs working youtube.
[streamlink-0.1.0-3-any.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/streamlink-0.1.0-3-any.pkg.tar.xz)
[streamlink-git-0.1.0.r20.g2808eb6-0-any.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/streamlink-git-0.1.0.r20.g2808eb6-0-any.pkg.tar.xz)
[idna_bypass patched python-requests-2.12.1-1.1-any.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/python-requests-2.12.1-1.1-any.pkg.tar.xz)
[python-pycryptodome-3.4.3-1-x86_64.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/python-pycryptodome-3.4.3-1-x86_64.pkg.tar.xz)

Also `streamlink-git` in AUR got a new dependency `python-pycryptodome` I had to create so if there are any issues with it please report them.

**Comment by gravyboat** [comment]
Thanks for the update @mmetak!

**Comment by mmetak** [comment]
With https://github.com/streamlink/streamlink/commit/2b052ad1e32ca31384d8ec3fd6ebde44ba24b112 merged and `python-requests` latest moved to extra repo, I've updated the `streamlink-git` package in the AUR.

**Comment by beardypig** [comment]
Good news! Thanks.
