### ISSUE TITLE
Integrate with SeedAndDew

### ISSUE THREAD

**Issue by ageorgie** [streamlink/streamlink#2142]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

Hi everyone,

I'm Alex from SeedAndDew. I was wondering if you would be interested in a project I'm working on. We're building a common subscription platform that allows users to contribute to a number of projects at the same time with a single subscription. The idea here is that it's a lot easier to get people to contribute $10/month to every open source project they work with than it is to get them to contribute $5/month for a specific project. The subscription revenue will be distributed based on the amount of time users spend reading documentation of the respective project which I anticipate will correspond well with actual use. So if a user spends 10% of their time reading the Streamlink documentation, you get 10% of the subscription revenue.

Just to be clear, this isn't a paywall. If a user isn't part of the service, they still see the documentation without any visual cues or any indication that they are missing anything. Our goal is merely to make it easy for people to contribute to open source projects like Streamlink.

We think we have an MVP ready and are in the process of getting projects onboard before a  launch sometime in the next month. We have 14 projects including projects like SQLAlchemy, RSpec, Bundler and Gorm fully integrated so far

I chatted briefly with @beardypig and @gravyboat via email and they mentioned I should create an issue to gauge the community's interest in this.

Any thoughts or concerns about this?

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I did some preliminary investigation after @beardypig informed me of the email they received regarding this project, and at this point I'm all for giving it a try (minus the caveats below) but will bring up a few things that might be points of contention for some people including myself:

- User privacy is one of my paramount concerns. This was shot down for RTD (https://github.com/rtfd/readthedocs.org/pull/3730) due to the fact they host all of their own content minus links to GitHub. Since we use GitHub.io for our doc hosting we're already allowing a fair number of third party trackers but it's still a valid concern to bring up. I'd like to know a bit more about what information is stored about users as it seems to me like there isn't anything needed but their "subscriber ID" or whatever it may be to confirm they were indeed the user reviewing the docs.

  If other details are tracked such as IP, browser, etc. I'm not sure if this is something we can support, especially depending on the data retention policies and methods. On the other hand we have some pretty large and relatively respected projects giving this a shot, so I would hope these questions were already answered to some degree and we can review that information.

- This uses a tracker built into the docs page to track how a user spends their time which is checked every 2 seconds, then marks the user as inactive after 5 minutes of inactivity. You can block SeedAndDew like any other domain by using noscript, ublockorigin, etc. The tracker script (pulled from the sqlalchemy site) looks like this:

```
<script>
  var SeedAndDewConfig = {};
  (function() {
    SeedAndDewConfig['adClass'] = "snd-ad";
    /* * * DON'T EDIT BELOW THIS LINE * * */
    SeedAndDewConfig['projectId'] = '433644b6-8850-4de8-a4e0-3aab1f25c57a';
    SeedAndDewConfig['loadStartTime'] = performance.now();
    SeedAndDewConfig['apiVersion'] = '2018-05-28'
    SeedAndDewConfig['sessionId'] = Math.random().toString(36).substring(2, 15);
    var snd = document.createElement('script');
    snd.type = 'text/javascript';
    snd.async = true;
    snd.src = 'https://www.seedanddew.com/static/embed.min.js';
    (document.getElementsByTagName('head')[0] ||
    document.getElementsByTagName('body')[0]).appendChild(snd);
  })();
</script>
```

- Non-users of SeedAndDew will still be checked to (I assume) see if the appropriate cookie which handles their data exists. Again this falls into my concern noted above about user privacy.

- SeedAndDew takes a 30% cut of all of the subscription fees (including processing fees) which is high, but 70% of 0 is still 0 so I'm okay with it though I would hope these fees are reduced in the future as they gain traction. As an example right now with Open Collective they take 5% which doesn't include processing fees, so it's more like 8%-10% if you include that.

As I originally noted I think it's worth giving a shot depending on the privacy concerns. I don't know how many people will end up using SeedAndDew but it's a similar idea to the Brave browser minus having to use an entirely different browser which is a pretty big plus to me. If anyone has specific concerns please voice them so they can be discussed.

**Comment by bastimeyer** [comment]
I'm sorry, but I don't like the idea of adding some kind of tracking tool to the Streamlink docs that also affects unrelated users, which will be 99.9%+ of all visitors.

IMO, a better solution for such an origanization would be providing a browser extension to its users. A browser extension has to be installed by an individual user and can evaluate the doc reading behavior without having the need of embedding a tracking tool into each supported site.
Also, what about man pages? You can't track people reading those...

I feel like this isn't a well thought out idea. I appreciate the efforts though. Reminds me of flattr.

---

Btw, this is the "prettified" code (un-minified via UglifyJS and a bit reformatted by me) which gets loaded by a second script that gets loaded by the actual tracking script.

```js
!function() {
	var t;
    var b = true;
	var o = 300000;

	function s() {
		if (!b) { return; }
		var r = new XMLHttpRequest;
		r.onreadystatechange = function() {
			if (r.readyState == XMLHttpRequest.DONE && 200 == r.status && "true" == r.response.toLowerCase()) {
				function(c) {
					var n = document.getElementsByClassName(c);
					for (; n.length > 0;) n[0].parentNode.removeChild(n[0]);
				}(window.SeedAndDewConfig.adClass);
			}
		};
		r.open("POST", "https://www.seedanddew.com/drop", true);
		r.withCredentials = true;
		var d = new FormData;
		d.append("projectId", window.SeedAndDewConfig.projectId); 
		d.append("sessionId", window.SeedAndDewConfig.sessionId);
		d.append("apiVersion", window.SeedAndDewConfig.apiVersion);
		r.send(o);
	}

	function h() {
		b = true;
		clearTimeout(t);
		t = window.setTimeout(function() {
			return b = false;
		}, o);
	}
	s();
	document.onmousemove = h;
	document.onscroll = h;
	setInterval(s, 2e3);
}();
```

As you can see, it makes a POST request every 2 seconds as long as the user is active (mouse move or scroll) and stops on inactivity after 5 mins until the user becomes active again.

**Comment by ageorgie** [comment]
I'm going to try to answer some of these concerns. Let me know if I missed any:

>I'd like to know a bit more about what information is stored about users as it seems to me like there isn't anything needed but their "subscriber ID" or whatever it may be to confirm they were indeed the user reviewing the docs.

We provide a cookie for each subscriber and track them using that cookie. This purely opt-in since they would need to create an account and pay $10/month for this to happen. 

For completeness, although non-subscribers won't have a cookie, we also get the IP/User Agent from non-subscribers by virtue of making a request on their behalf. We store this for statistical/debugging purposes (what browsers do I need to support, etc) but remove the raw data periodically (every month).

>IMO, a better solution for such an origanization would be providing a browser extension to its users

The goal behind this project is to allow people to easily donate to all the projects they use on a daily basis and remove the friction inherent in the current donation system. Asking a user to download another browser extension instead of the current way of just registering an account is just adding more friction to this process and is less than ideal. Flattr is actually an interesting example of this - they tried to do this and they failed. It's just asking for too much from a user that has other priorities in their lives.

As an aside, a browser extension also give me access to every site a user accesses. Granted we don't need to do anything with that information, but my ideal solution is one where we get the least amount of info and thus need the least amount of trust.

Frankly, I don't see the IP/User Agent combo as particularly privacy invasive. A user using a particular device and browser can go from his house to a coffee shop, use the same device and browser but now looks like a completely different user. That isn't a particularly good way to track users. Not to mention that info is already being sent out by virtue of the site being on Github (now Microsoft). We can see this by the fact that all other projects that do want to track users (Ad-tech, Twitter, Facebook, Google) don't consider IP's at all and mostly just stick with standard cookies and other variants of them.

>Also, what about man pages? You can't track people reading those...

I'm making a guess here that you're talking about the Github readme page? Indeed, we don't currently have a way to track people there. We can provide an image that delivers a fixed amount of drops but that is something I'm still thinking about. That said, I've heard this request from a few places so it's on the backlog of things I need to consider.

**Comment by ageorgie** [comment]
>Then you need the consent of all European users to store this kind of data due to the GDPR. 🇪🇺

GDPR allows for aggregated data as long as the underlying raw data is deleted - https://gdpr-info.eu/recitals/no-162/. 

>But that's just my suggestion. I personally think that aggressively gathering data from everyone else (the vast majority of people) is a terrible idea and I'm very much against this, even if Streamlink's documentation site is hosted by GitHub (Microsoft).

I suspect the point of contention here is how aggressive making a request is. My point of view is that it isn't and that any data I can get from that request isn't very good at identifying a user over time anyway. The trade off though is that it makes life materially easier for the user that wants to contribute to StreamLink and other projects. There's a pretty big difference between register an account and you're done and register an account, download another piece of software, make everything work and now you're done. It doesn't sound like a lot but that extra step is where we lose people and it's important.

>Streamlink as a free and open source software project benefits from GitHub's free (and proprietary) hosting because it provides information to everyone using the software. However, if we include a 3rd party tracker that gathers everyone's data while also being closed source with only little (potential) benefits for the project, that would be quite an unethical choice for us to make.

This is fair. You've made the decision that the trade off of the information that Github collects is reasonable given the benefit of free hosting. The only question is whether SeedAndDew would be similarly valuable to your project. I think we want to do for project sustainability of open source what Github did for collaboration and hosting. I don't know how far we can take that - that will depend on how many users you have, how much they use your project and how willing they are to contribute back to open source but I think this is an experiment worth trying. I admit I am biased here though :)

>No, I'm talking about man pages.

Yea we don't support that and probably won't for a bit.

**Comment by back-to** [comment]
I think such scripts are **rude to the end user**,
basically just a tracker for users who don't know how to block scripts.

this might be useful for them ...
- https://github.com/gorhill/uBlock
- https://github.com/gorhill/uMatrix

**Comment by bastimeyer** [comment]
I'm going to close this since pretty much everyone is against it. There are only very little benefits for the project if we integrate a tracker of this kind into the documentation.
