### ISSUE TITLE
oz.com/CONCACAFgo.com

### ISSUE THREAD

**Issue by mikedevoss** [streamlink/streamlink#2145]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Apologies in advance if I am missing information. I have read the plugin request requirements and the contribution guidelines but I am a novice here.

oz.com has many live and VOD football and other sporting events, both free and PPV. Most events require a free account login.

### Example stream URLs

Example URL:https://www.oz.com/hntv/video/3d6e43fa-a858-4e46-ab1e-61eb6b8fdafa
HLS: https://d54ncncg5b9ab.cloudfront.net/content/f739337e-eb46-4a82-86b7-62da9769b273/3d6e43fa-a858-4e46-ab1e-61eb6b8fdafa/playlist.m3u8?ssl=true

### Additional comments, screenshots, etc.

If you pass the cookies found in the key URL <https://playlist.oz.com/key/f739337e-eb46-4a82-86b7-62da9769b273/3d6e43fa-a858-4e46-ab1e-61eb6b8fdafa/973c1a9d4d384808409f2305544fedb7> through to streamlink, it will access the HLS.

```
$ streamlink \
  --http-cookie "_ga=GA1.2.946834334.1536431511" \
  --http-cookie "ajs_group_id=null" \
  --http-cookie "ajs_anonymous_id=%225220275b-a458-4572-bb90-38a97a3dc7b0%22" \
  --http-cookie "intercom-id-r6awlz52=0b168d5f-aee6-45e5-aee2-75c60be9d0c6" \
  --http-cookie "access_token=d8662ac41d183874cbb13dae500c7831a4cc1a35" \
  --http-cookie "ajs_user_id=%22d8f1a02b-86f5-40e1-b470-cf8ce94bf4c6%22" \
  --http-cookie "intercom-lou-r6awlz52=1; token-3ba2a3d0=a7c82a86065c8483827965f1272874" \
  --http-cookie "token-03a18e03=193158f67978f1c95a1483a979dc3e" \
  --http-cookie "token-4eaf8471=ffd3aeb4387c88e2ef2a02db03a027" \
  --http-cookie "_gid=GA1.2.1508686647.1540917902" \
  --http-cookie "token-25a624be=11a83391d3ef604523afb37d9c55cb" \
  --http-cookie "token-97ecab1b=58dba77aa7ffd3ba4e20a430948790" \
  --http-cookie "token-2815febf=00c6cf5c2198a0f10620e5a1f714fb" \
  --http-cookie "oz-accepted-cookies=true" \
  --http-cookie "_gat=1" \
  --http-cookie "intercom-session-r6awlz52=bEswd2hPRkw4STJ5cnc1ZHROYUhZdDdQdW5yWm9zT29MQnFaNzZ1WW5CWmJkamU0dGhCY1lTNFV1MVdtTFQ1QS0tYlo4MnpkVVNtVU5BV096L3A0UVBnUT09--3bcf9e55f0c7d0f3f5d7bdae40d17b5064e27907" \
  --http-cookie "token-6109a11a=1cac248b1b04ca58829813cc9d884f" \
  "hlsvariant://https://d54ncncg5b9ab.cloudfront.net/content/f739337e-eb46-4a82-86b7-62da9769b273/3d6e43fa-a858-4e46-ab1e-61eb6b8fdafa/playlist.m3u8?ssl=true" \
  best
```

Is there a way to build a plugin that would require the user login info, but then load the page URL, sniff the key URL, and feed the cookies into streamlink all in one command? It also seems that not all of those cookies are necessary, but I'm not sure which are required and which aren't.

Additionally, concacafgo.com is built on the oz.com platform, but the key files from concacafgo.com don't seem to include all of the necessary cookies to access the HLS URL. Any help figuring out the difference there would be greatly appreciated.

Thank you, all!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Can you please provide a few details about the streaming platform? I can't find any informations about whether it is legal or not. The company behind it is registered in Iceland, but its address doesn't seem to exist. And according to the download counts and comments of the Android and iOS apps, this looks rather shady.

**Comment by mikedevoss** [comment]
I'm not sure what information I can provide, but it seems to be just a relatively new platform. They certainly are the official OTT broadcaster for content owners such as CONCACAF football, Dominican Republic baseball, HNTV/Croatian football, etc. CONCACAF.com for instance links to it at https://www.concacaf.com/en/video with their "Live" button.

Here is their corporate page: http://corp.oz.com/

**Comment by asevcik** [comment]
Or in the case that a plugin doesn't make sense, is there someone who could help format the streamlink command?

Page URL: https://www.concacafgo.com/cu20c/video/1f98e1f7-7c9b-4e63-b039-062fb60b7485
m3u8 URL: https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true
key URL: https://playlist.oz.com/key/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/dba8bd41c6e97542e8ba94ee2c200346

Potentially useful snippets from key URL:

 "startedDateTime": "2018-11-04T18:46:54.677Z",
        "time": 64.4385010303813,
        "request": {
          "method": "POST",
          "url": "https://core.oz.com/pusher/auth",
          "httpVersion": "http/1.1",
          "headers": [
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
            },
            {
              "name": "Referer",
              "value": "https://www.concacafgo.com/cu20c/video/1f98e1f7-7c9b-4e63-b039-062fb60b7485"
            },
            {
              "name": "Origin",
              "value": "https://www.concacafgo.com"
            },
            {
              "name": "Authorization",
              "value": "Bearer 90921df4a6521d29b9a88db97bbd2b416da3c0bb"
            },
            {
              "name": "Content-Type",
              "value": "application/x-www-form-urlencoded"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0,
          "postData": {
            "mimeType": "application/x-www-form-urlencoded",
            "text": "socket_id=244923.24885546&channel_name=private-0a2aa4c3-9d41-4140-9df4-5add2b76406e",
            "params": [
              {
                "name": "socket_id",
                "value": "244923.24885546"
              },
              {
                "name": "channel_name",
                "value": "private-0a2aa4c3-9d41-4140-9df4-5add2b76406e"
              }
            ]
          }
        },
-----
"name": "Cookie",
              "value": "_ga=GA1.2.1177067252.1538717531; intercom-id-r6awlz52=b1a7dd59-7263-43ae-a703-c30995617288; ajs_group_id=null; ajs_anonymous_id=%22dc29ffc7-7f3e-4c0c-af23-d9af8cf84bac%22; access_token=90921df4a6521d29b9a88db97bbd2b416da3c0bb; ajs_user_id=%220a2aa4c3-9d41-4140-9df4-5add2b76406e%22; access_token=1c3073e1c2ca789052b8a53f1f9dd4b844f1396a; _gid=GA1.2.930197232.1541352229; oz-accepted-cookies=true; intercom-session-r6awlz52=VG12L3p3Q21BdVNld3g3eXBDYVVhMTJ6MHMzNzdrVWVQQVNyMWo4SVU5aFZ1dS9way9pZTFuWmdyTFpJY2VORi0tM3MvK3ExYXNKU3hIWk1jNkRJSXJRdz09--dda70f1dffde554a9d42e4d867129e86c9350ab2"

Steamlink command and result:

$ streamlink --http-header "Authorization=Bearer 90921df4a6521d29b9a88db97bbd2b416da3c0bb" --http-cookie "_ga=GA1.2.1177067252.1538717531" --http-cookie "intercom-id-r6awlz52=b1a7dd59-7263-43ae-a703-c30995617288" --http-cookie "ajs_group_id=null" --http-cookie "ajs_anonymous_id=%22dc29ffc7-7f3e-4c0c-af23-d9af8cf84bac%22" --http-cookie "access_token=90921df4a6521d29b9a88db97bbd2b416da3c0bb" --http-cookie "ajs_user_id=%220a2aa4c3-9d41-4140-9df4-5add2b76406e%22" --http-cookie "access_token=1c3073e1c2ca789052b8a53f1f9dd4b844f1396a" --http-cookie "_gid=GA1.2.930197232.1541352229" --http-cookie "oz-accepted-cookies=true" --http-cookie "_gat=1; intercom-session-r6awlz52=VWVTb3U4TDRVUnZ2eWphbG5ZZ2pJR2RHamRia0JUeWg0L1RPTWdVd3RFMHFoU3FDbUp0aFRtbXlQYWpRTzFyMi0taE8vaDdIeFA3cDNZcmwvK0NYanRnUT09--439d70b4a31d516951a95a8be591abd216e41024" "hlsvariant://https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true" best -o filename.mp4
[cli][info] Found matching plugin hls for URL hlsvariant://https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true
[cli][info] Available streams: 750k (worst), 1150k, 2850k, 5350k (best)
[cli][info] Opening stream: 5350k (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://playlist.oz.com/key/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/dba8bd41c6e97542e8ba94ee2c200346 (403 Client Error: Forbidden)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/5000/playlist.m3u8?ssl=true')> (No data returned from stream)
error: Could not open stream <HLSStream('https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/5000/playlist.m3u8?ssl=true')>, tried 1 times, exiting
[cli][info] Closing currently open stream...

**Comment by mikedevoss** [comment]
Or in the case that a plugin doesn't make sense, is there someone who could help format the streamlink command?

Page URL: https://www.concacafgo.com/cu20c/video/1f98e1f7-7c9b-4e63-b039-062fb60b7485
m3u8 URL: https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true
key URL: https://playlist.oz.com/key/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/dba8bd41c6e97542e8ba94ee2c200346

Potentially useful snippets from key URL:

```
"startedDateTime": "2018-11-04T18:46:54.677Z",
"time": 64.4385010303813,
"request": {
"method": "POST",
"url": "https://core.oz.com/pusher/auth",
"httpVersion": "http/1.1",
"headers": [
{
"name": "User-Agent",
"value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
},
{
"name": "Referer",
"value": "https://www.concacafgo.com/cu20c/video/1f98e1f7-7c9b-4e63-b039-062fb60b7485"
},
{
"name": "Origin",
"value": "https://www.concacafgo.com"
},
{
"name": "Authorization",
"value": "Bearer 90921df4a6521d29b9a88db97bbd2b416da3c0bb"
},
{
"name": "Content-Type",
"value": "application/x-www-form-urlencoded"
}
],
"queryString": [],
"cookies": [],
"headersSize": -1,
"bodySize": 0,
"postData": {
"mimeType": "application/x-www-form-urlencoded",
"text": "socket_id=244923.24885546&channel_name=private-0a2aa4c3-9d41-4140-9df4-5add2b76406e",
"params": [
{
"name": "socket_id",
"value": "244923.24885546"
},
{
"name": "channel_name",
"value": "private-0a2aa4c3-9d41-4140-9df4-5add2b76406e"
}
]
}
},
```
```
"name": "Cookie",
"value": "_ga=GA1.2.1177067252.1538717531; intercom-id-r6awlz52=b1a7dd59-7263-43ae-a703-c30995617288; ajs_group_id=null; ajs_anonymous_id=%22dc29ffc7-7f3e-4c0c-af23-d9af8cf84bac%22; access_token=90921df4a6521d29b9a88db97bbd2b416da3c0bb; ajs_user_id=%220a2aa4c3-9d41-4140-9df4-5add2b76406e%22; access_token=1c3073e1c2ca789052b8a53f1f9dd4b844f1396a; _gid=GA1.2.930197232.1541352229; oz-accepted-cookies=true; intercom-session-r6awlz52=VG12L3p3Q21BdVNld3g3eXBDYVVhMTJ6MHMzNzdrVWVQQVNyMWo4SVU5aFZ1dS9way9pZTFuWmdyTFpJY2VORi0tM3MvK3ExYXNKU3hIWk1jNkRJSXJRdz09--dda70f1dffde554a9d42e4d867129e86c9350ab2"
```

Steamlink command and result:

```
$ streamlink --http-header "Authorization=Bearer 90921df4a6521d29b9a88db97bbd2b416da3c0bb" --http-cookie "_ga=GA1.2.1177067252.1538717531" --http-cookie "intercom-id-r6awlz52=b1a7dd59-7263-43ae-a703-c30995617288" --http-cookie "ajs_group_id=null" --http-cookie "ajs_anonymous_id=%22dc29ffc7-7f3e-4c0c-af23-d9af8cf84bac%22" --http-cookie "access_token=90921df4a6521d29b9a88db97bbd2b416da3c0bb" --http-cookie "ajs_user_id=%220a2aa4c3-9d41-4140-9df4-5add2b76406e%22" --http-cookie "access_token=1c3073e1c2ca789052b8a53f1f9dd4b844f1396a" --http-cookie "_gid=GA1.2.930197232.1541352229" --http-cookie "oz-accepted-cookies=true" --http-cookie "_gat=1; intercom-session-r6awlz52=VWVTb3U4TDRVUnZ2eWphbG5ZZ2pJR2RHamRia0JUeWg0L1RPTWdVd3RFMHFoU3FDbUp0aFRtbXlQYWpRTzFyMi0taE8vaDdIeFA3cDNZcmwvK0NYanRnUT09--439d70b4a31d516951a95a8be591abd216e41024" "hlsvariant://https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true" best -o filename.mp4
[cli][info] Found matching plugin hls for URL hlsvariant://https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/playlist.m3u8?ssl=true
[cli][info] Available streams: 750k (worst), 1150k, 2850k, 5350k (best)
[cli][info] Opening stream: 5350k (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://playlist.oz.com/key/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/dba8bd41c6e97542e8ba94ee2c200346 (403 Client Error: Forbidden)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/5000/playlist.m3u8?ssl=true')> (No data returned from stream)
error: Could not open stream <HLSStream('https://d54ncncg5b9ab.cloudfront.net/content/0a02c43d-213d-4de4-8aa1-961de41af166/1f98e1f7-7c9b-4e63-b039-062fb60b7485/5000/playlist.m3u8?ssl=true')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment]
well, nobody has an account for this, I don't think we can maintain/support this plugin request.

closing
