### ISSUE TITLE
NPO plugin needs an update.

### ISSUE THREAD

**Issue by tmatthews5511** [streamlink/streamlink#2153]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When trying to use streamlink on www.npostart.nl, the following happens:

streamlink https://www.npostart.nl/nos-studio-voetbal/04-11-2018/POW_03963080
 
error: No plugin can handle URL: https://www.npostart.nl/nos-studio-voetbal/04-11-2018/POW_03963080

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://www.npostart.nl/nos-studio-voetbal/04-11-2018/POW_03963080
2. ...
3. ...

### Log output

```
[cli][debug] OS:         Linux-4.15.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.20.0), Socks(1.6.7), Websocket(0.53.0)
error: No plugin can handle URL: https://www.npostart.nl/nos-studio-voetbal/04-11-2018/POW_03963080
```

### Additional comments, screenshots, etc.

The current plugin just has the following:

Supports:
   VODs:
    - https://www.npo.nl/nos-journaal/07-07-2017/POW_03375651
    - https://www.zapp.nl/topdoks/gemist/VPWON_1276930
    - https://zappelin.nl/10-voor/gemist/VPWON_1271522
   Live:
    - https://www.npo.nl/live/npo-1
    - https://zappelin.nl/tv-kijken

Thus, a quick update would be needed since the page has changed. 

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by karlo2105** [comment]
Done.
https://github.com/streamlink/streamlink/pull/2147

**Comment by gravyboat** [comment]
#2147 is merged.
