### ISSUE TITLE
Vidio Login Support

### ISSUE THREAD

**Issue by Stemp2** [streamlink/streamlink#2155]
## Feature Request
- [ x] This is a feature request and I have read the contribution guidelines.

### Description

Hi,could you add login support for vidio plugin?
It is necessary to use it to watch in https://www.vidio.com/premier

### Expected / Actual behavior

[Streamlink for Windows v0.14.2 - Git 215d789]
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/6317-
bein-2
[cli][info] Available streams: 270p (worst), 360p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}',
 'SAMPLE-AES')
[cli][error] Try 1/1: Could not open stream <HLSStream('https://production.premi
um.bein2-a.vidio.static6.com/out/v1/8ce83c7cd434445398381f990f03dbf2/index_1.m3u
8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://production.premium.bein2-a.vidi
o.static6.com/out/v1/8ce83c7cd434445398381f990f03dbf2/index_1.m3u8')>, tried 1 t
imes, exiting
[cli][info] Closing currently open stream...

**Comment by back-to** [comment]
> [stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', 'SAMPLE-AES')

this is DRM which is not supported by Streamlink
