### ISSUE TITLE
How to stream RTC Liège ?

### ISSUE THREAD

**Issue by Sylvebois** [streamlink/streamlink#2162]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I would like to stream the live video from https://www.rtc.be/live

On this site, there is a html video tag and the source of it is :
http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355&tokenstarttime=1542116555&tokenhash=2nWF92Asytdskphujx6-_UfRoasz5EzHMpg6a0YZNA8= 

No login nor password are needed but, when executing the command, I receive a 

> 403 Client Error: Forbidden

 and streamlink stay open until I do a Ctrl + C

So what should I do to make it work ?

Thank you for your help ^^

N.B. : The same link works in VLC

### Expected / Actual behavior

Opening the stream in the console

### Reproduction steps / Explicit stream URLs to test

1. Simply type ` streamlink http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355&tokenstarttime=1542116555&tokenhash=2nWF92Asytdskphujx6-_UfRoasz5EzHMpg6a0YZNA8=`

### Logs

```
streamlink --loglevel debug http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355&tokenstarttime=1542116555&tokenhash=2nWF92Asytdskphujx6-_UfRoasz5EzHMpg6a0YZNA8=
[1] 3985
[2] 3986
user@pc:~$ [cli][debug] OS:         Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin hls for URL http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355
[plugin.hls][debug] URL=http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355; params={}
error: Unable to open URL: http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355 (403 Client Error: Forbidden for url: http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by qkolj** [comment]
You are getting this:
```
[1] 3985
[2] 3986
```
because you have unescaped ampersand (`&`) symbols in the URL, which are job control operators for running jobs in background.

You should try putting the extracted `m3u8` URL in the quotation marks, i.e.
```
streamlink "http://media.webtvlive.eu/rtc/_definst_/smil:live.smil/playlist.m3u8?tokenendtime=1542127355&tokenstarttime=1542116555&tokenhash=2nWF92Asytdskphujx6-_UfRoasz5EzHMpg6a0YZNA8="
```

Of course, this URL has expired so you'd have to get a new one, but running it as such with a fresh one should work without a problem.

**Comment by Sylvebois** [comment]
Hello,

Thanks, it was indeed the problem ... It's working now (with a fresh link)
