### ISSUE TITLE
Facebook video does not offer 1080p option

### ISSUE THREAD

**Issue by scottbernstein-zz** [streamlink/streamlink#2168]
[x ] This is a plugin issue and I have read the contribution guidelines.

Description
Facebook video offers 1080p option but the "best" quality only delivers 720p video

Reproduction steps / Explicit stream URLs to test
https://www.facebook.com/PigeonsPlayingPingPong/videos/477345006006079/

Go to this video. You can see that among the options for resolution is 1080. When I point streamlink at the URL to download and select "best", it only streams the 720p version. The only 2 resolution options presented are "sd" and "hd" (but there are actually 6 distinct resolution options available on the page)

Log output
c:>streamlink https://www.facebook.com/PigeonsPlayingPingPong/videos/477345006006079/ -l debug
[cli][debug] OS: Windows 7
[cli][debug] Python: 3.6.6
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/PigeonsPlayingPingPong/videos/47734500600607
9/
Available streams: sd (worst), hd (best)

**Comment by back-to** [comment]
> (but there are actually 6 distinct resolution options available on the page)

these are DASHStreams, they are currently not parsed for the Facebook plugin.

See https://github.com/streamlink/streamlink/issues/2179 for some more details

**Comment by back-to** [comment]
They use custom dash streams, adding them to streamlink is just to much work.

closing
