### ISSUE TITLE
Pls support MSN video!!!

### ISSUE THREAD

**Issue by zhouhounan** [streamlink/streamlink#2173]
## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.

### Additional comments, screenshots, etc.

Example URL 
msn.com/en-us/video/lifestyle?ocid=BHEA000

it shows
error: No plugin can handle URL: http://msn.com/en-us/video/lifestyle?ocid=BHEA000

**Comment by gravyboat** [comment]
This isn't a livestream, it's just videos so it's not something we will support.
