### ISSUE TITLE
aeaweb.org

### ISSUE THREAD

**Issue by aosavi** [streamlink/streamlink#2174]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Website of the American Economic Association, with great webcasts. Webcasts seem to be powered by Sonicfoundry's Mediasite.

### Example stream URLs

1. https://www.aeaweb.org/conference/cont-ed/2018-webcasts
2. https://www.aeaweb.org/webcasts/2018/machine-learning-and-econometrics-part-1

**Comment by gravyboat** [comment]
Webcasts aren't livestreams, these are just videos so it's not something we would add a plugin for.
