### ISSUE TITLE
AUTHORS Sorting

### ISSUE THREAD

**Issue by frenchja** [streamlink/streamlink#2175]
Came across a tiny observation to discuss.  Currently, `./script/authors.sh` uses an alphabetical, case-sensitive sorting mechanism. I thought this behavior might be a discrepancy between the `sort` bundled with macOS and GNU, but version of `sort` provided by `coretools` in Homebrew also seems to have a `-f` option to ignore case.  This is a bit weird since the [current AUTHORS file](https://github.com/streamlink/streamlink/blob/master/AUTHORS) appears to be case insensitive.  I might be missing something... 

Does it makes sense to change this to case-insensitive?

```bash
git log --format='%aN' | sort -uf
```

Alternatively, the file could present authors by their commit amounts: 

```bash
git shortlog -s -n | awk '{$1="";print}'
```

**Comment by back-to** [comment]
**the script is not used, it was only used once.**

there are a lot of **duplicates** if you want to do it automatically

it might be easier to update it **manually** when a `First-time contributor` PR gets merged

of course the current list could be updated with your first command,
but the duplicates should be removed from it.

```
git log --format='%aN' | sort -uf
```

---

also this part `__credits__` and/or `__author__`

https://github.com/streamlink/streamlink/blob/cd6f94a5a4ee83cb5b61a295df9e13956bcfcb27/src/streamlink/__init__.py#L17-L71

could be changed with a link to https://raw.githubusercontent.com/streamlink/streamlink/master/AUTHORS
