### ISSUE TITLE
[Facebook]: Videos cut off

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2176]
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

When opening some videos (for instance https://www.facebook.com/TheHookOfficial/videos/372608690145123/) both the sd and hd versions cut off and/or end prematurely.

### Reproduction steps / Explicit stream URLs to test

1. Open the link
2. Watch Cumberwhatshisname
3. Enjoy VLC shutting down for you

### Log output

Could not get any log output.

### Additional comments, screenshots, etc.

Windows 7, 64 bit, using latest nightly version, installed as 'only for me'. Checked with --version after I reinstalled, using the latest nightly and still no cigar.

**Comment by gravyboat** [comment]
Can you try a different video player (mpv for example)? We've been seeing some issues with the latest release of VLC.

**Comment by gravyboat** [comment]
@roshavagarga Will do, thanks for the update. I haven't been using VLC for a while, but we started getting a lot of reports like this once the 3.0.0 version was released. You could try to roll back to 2.9.X if they still have those available for download.
