### ISSUE TITLE
vidio.com plugin [https://www.vidio.com], stream stops playing

### ISSUE THREAD

**Issue by akiwatti54** [streamlink/streamlink#2177]
## Plugin Issue
- [ x] This is a plugin issue and I have read the contribution guidelines.

### Description
stream stops playing after around 1 minute

### Reproduction steps / Explicit stream URLs to test
1.) https://www.vidio.com/live/205-indosiar-tv-stream
2.) same for others , e.g. https://www.vidio.com/live/204-sctv-tv-stream

### Log output
[streamlinksrv][info] Python:        2.7.15
[streamlinksrv][info] Streamlink:    0.14.2 / 27.10.2018
[streamlinksrv][debug] Options Parser: 0.1.7
[streamlinksrv][info] Requests(2.19.1), Websocket(0.48.0)
[streamlinksrv][info] Processing URL: https://www.vidio.com/live/205-indosiar-tv-stream
[streamlinksrv][debug] URL Args: []
[streamlinksrv][info] Found matching plugin vidio for URL https://www.vidio.com/live/205-indosiar-tv-stream
[plugin.vidio][debug] Getting stream tokens
[plugin.vidio][debug] HLS URL: https://kmklive-lh.akamaihd.net/i/indosiar_ta_regular@94479/master.m3u8
[plugin.vidio][debug] Tokens: hdnts=st=1543130333~exp=1543130383~acl=/i/*~hmac=59cfc0d008564617c68e31eac8d5065ba6375044737ddb719922c091b34ba5f3
[utils.l10n][debug] Language code: en_US
[streamlinksrv][info] Available streams:
270p_alt (worst), 270p, 360p_alt, 360p, 720p_alt, 720p (best)
[streamlinksrv][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 154313030; Last Sequence: 154313032
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 154313030; End Sequence: None
[streamlinksrv][debug] Writing stream to player
127.0.0.1 - - [25/Nov/2018 08:18:55] "GET /https://www.vidio.com/live/205-indosiar-tv-stream HTTP/1.1" 200 -
[stream.hls][debug] Adding segment 154313030 to queue
[stream.hls][debug] Adding segment 154313031 to queue
[stream.hls][debug] Adding segment 154313032 to queue
[stream.hls][debug] Download of segment 154313030 complete
[stream.hls][debug] Download of segment 154313031 complete
[stream.hls][debug] Download of segment 154313032 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 154313033 to queue
[stream.hls][debug] Download of segment 154313033 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 154313034 to queue
[streamlinksrv][info] Processing URL: https://www.vidio.com/live/205-indosiar-tv-stream
[streamlinksrv][debug] URL Args: []
[streamlinksrv][info] Found matching plugin vidio for URL https://www.vidio.com/live/205-indosiar-tv-stream
[streamlinksrv][info] Stream ended
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[streamlinksrv][info] Closing currently open stream...
[stream.hls][debug] Download of segment 154313034 complete
[plugin.vidio][debug] Getting stream tokens
[plugin.vidio][debug] HLS URL: https://kmklive-lh.akamaihd.net/i/indosiar_ta_regular@94479/master.m3u8
[plugin.vidio][debug] Tokens: hdnts=st=1543130358~exp=1543130408~acl=/i/*~hmac=8c74a65cd62f8f32c17ae06bdbf9bfaeed8bcf02cdd850b37eb8f34ac9289087
[utils.l10n][debug] Language code: en_US
[streamlinksrv][info] Available streams:
270p_alt (worst), 270p, 360p_alt, 360p, 720p_alt, 720p (best)
[streamlinksrv][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 154313032; Last Sequence: 154313034
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 154313032; End Sequence: None
[streamlinksrv][debug] Writing stream to player
127.0.0.1 - - [25/Nov/2018 08:19:18] "GET /https://www.vidio.com/live/205-indosiar-tv-stream HTTP/1.1" 200 -
[stream.hls][debug] Adding segment 154313032 to queue
[stream.hls][debug] Adding segment 154313033 to queue
[stream.hls][debug] Adding segment 154313034 to queue
[streamlinksrv][info] Stream ended
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Download of segment 154313032 complete
[streamlinksrv][info] Closing currently open stream...

**Comment by Billy2011** [comment]
This is not a streamlink problem, but a problem of the player.You can try to download the m3u playlist from the bouquet via OpenWebif and open the streams on your PC with the MPV or VLC player.

**Comment by back-to** [comment]
you could try a different Service Type

- IPTV(4097) default IPTV player
- GSTREAMER (5001) additional plugin (Serviceapp)
- EXTPLAYER (5002) additional plugin (Serviceapp)

---

closing, as this is not related to Streamlink

**Comment by tuancreb32** [comment]
percuma ngak bisa live bola..

**Comment by bastimeyer** [comment]
This is an English-only issue tracker. If you want to submit an issue, please open a new thread and don't bump old threads. The vidio plugin has already been fixed on the master branch, see #4002.
https://streamlink.github.io/latest/install.html
