### ISSUE TITLE
VaughnLive Changed URL

### ISSUE THREAD

**Issue by Krazy-Tom** [streamlink/streamlink#2178]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

The VaughnLive website changed their URL from vaughnlive.tv to vaughn.live so the plugin for Streamlink doesn't work.

### Reproduction steps / Explicit stream URLs to test

1. ... Executing the command "streamlink vaughnlive.tv/*CHANNEL* brings an error

### Log output

```
C:\Users\Tommy>streamlink vaughnlive.tv/qinteresting --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin vaughnlive for URL vaughnlive.tv/qinteresting
[plugin.vaughnlive][info] Stream powered by VaughnSoft - remember to support them.
error: Unable to open URL: https://mp4.vaughnsoft.net/live?stream=live_qinteresting&port=2935&app=live (HTTPSConnectionPool(host='mp4.vaughnsoft.net', port=443): Max retries exceeded with url: /live?stream=live_qinteresting&port=2935&app=live (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x044B9350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
The format of their streaming API has changed. They now generate a token that you need to include, you can see it in the page source if you look for `mp4StreamUrl`.

**Comment by fadster** [comment]
Any hope for a fix?

**Comment by techmouse** [comment]
I came up with this fix a day or two ago.

Note: I am **NOT** a python programmer (what with mandatory whitespace and all) so it could be buggy or have some logical oversights in it. So someone more experienced should go over it. But so far it's been working as well for me as the vaughnlive.tv plugin did.

"vaughn.py":
https://pastebin.com/ZBcZiDtx

**Comment by fadster** [comment]
@techmouse I confirm your fix is indeed working. Thank you! :smiley:

**Comment by Krazy-Tom** [comment]
@techmouse As far as I have tested this, it works. Great job!

**Comment by RuKeBo** [comment]
For other sites I believe you would replace line 10 which is " (?P<domain>vaughn).live" with "(?P<domain>vaughn|breakers|instagib|vapers|pearltime).live".  I'm no python programmer as well and this fix is a bit buggy for me.  I think it still needs some work.

**Comment by techmouse** [comment]
@Toberu This is what I've got so far.

Name it "vaughnlive.py":
https://pastebin.com/FhwTxnC5

It's fickle, temperamental, and may take a few attempts to get working, but when it works, it works.

@RuKeBo Did that work for you? I didn't have any success by changing that line.

**Comment by bastimeyer** [comment]
@techmouse Thanks for providing a fix for the plugin. Would you please be so kind and open a regular pull request with your changes, so that it can be properly tested by everyone without having to use pastebin and swap the entire plugin code by hand? Thanks!

**Comment by Toberu** [comment]
@techmouse Thank you. That seems to work.

**Comment by techmouse** [comment]
@bastimeyer Ugh I hate doing pull requests! I've been messing with this thing for almost an hour now and I can never figure out what I'm supposed to do. I know the whole point of github is to better facilitate collaboration but honestly it takes such a bureaucratic approach, and that last thing programming and open source projects need is bureaucracy. It's like it's trying to filter out more work through convolution and catch 22's. Can you imagine how much faster projects would evolve if submitting changes wasn't such a convoluted mess and didn't turn people away? I can't possibly be the only one choosing to be the sole user of a more functional version of something because github is unnecessarily difficult to use.

I can't figure it out, so I guess I can't submit a pull request. If somebody else wants to do it, go for it.

/rant

**Comment by RuKeBo** [comment]
@techmouse My suggestion for changing that one line was incomplete and your fix solves it.  I didn't realize the other domains were not ".live".  Anyway, I think this plugin still needs some work and I am not suggesting you be the one to do it, but it is buggy and does not function as smoothly as before.  Using VLC works ok most times and takes a few tries to get working.  Trying to save to an output file is where it really has issues.

**Comment by cirrusUK** [comment]
cheers @techmouse if you dont wanna submit pull request maybe a MOD can if no one else wants to i will try find the time (if i remember how)  thank you for the fix cousin
Regards
![2018-12-05-223229_427x85_scrot](https://user-images.githubusercontent.com/1867245/49548475-bdc40080-f8dd-11e8-810d-0a65e74ed267.png)

**Comment by ringtvt** [comment]
> @bastimeyer Ugh I hate doing pull requests! I've been messing with this thing for almost an hour now and I can never figure out what I'm supposed to do. I know the whole point of github is to better facilitate collaboration but honestly it takes such a bureaucratic approach, and that last thing programming and open source projects need is bureaucracy. It's like it's trying to filter out more work through convolution and catch 22's. Can you imagine how much faster projects would evolve if submitting changes wasn't such a convoluted mess and didn't turn people away? I can't possibly be the only one choosing to be the sole user of a more functional version of something because github is unnecessarily difficult to use.
> 
> I can't figure it out, so I guess I can't submit a pull request. If somebody else wants to do it, go for it.
> 
> /rant

i can;t not enter your link. please send me. thanks @techmouse

**Comment by tgmasterx1987** [comment]
The URL of VaughnLive changed again....
For all User they need the New Code of vaughnlive.py, here my Pastebin:

https://pastebin.com/sWCwES3E

Have fun...
MfG

**Comment by johnthecracker** [comment]
This works, at least for foxnews, https://vaughn.live/newzviewz

**Comment by johnthecracker** [comment]
@tgmasterx1987,

you are good at streams like this one:

http://www.xinhuanet.com/2015wlds/enindex.htm

Can you get this working? (if you like watching Chinese news)
If you say yes, I'll make plugin request for CNC World News Live.
Here is more info:

http://livecdn1.news.cn/www/cncen.html

https://github.com/back-to/generic/issues/4

**Comment by RuKeBo** [comment]
Is anyone else having issues with this (VaughnLive) again.  Now it just shows a static image when trying to play any stream.

**Comment by cirrusUK** [comment]
> Is anyone else having issues with this (VaughnLive) again. Now it just shows a static image when trying to play any stream.

Works ok here !

**Comment by RuKeBo** [comment]
That's strange.  Was working with new file above but hasn't for the last few weeks.  Is there a new version of the plug-in?  It connects but just shows an image that says "Tech Corner".

**Comment by fadster** [comment]
The server changed. In the file above, change `stream_url = "https://mp4-rem.vaughnsoft.net` to `stream_url = "https://mp4v.vaughnsoft.net"`.

@RuKeBo Make sure you're using the file posted by tgmasterx1987 on Feb. 17. I had the same problem with previous versions.

**Comment by RuKeBo** [comment]
Yeah,  I just found that the URL changed, thanks for the confirmation.  It appears to be working again.

**Comment by cirrusUK** [comment]
merged

**Comment by nestukh** [comment]
they changed it again 
from
`mp4v.vaughnsoft.net`
to 
`v4pm.vaughnsoft.net`

comment:
hello _Random Acts of Management_, my old friends
(cue Dilbert)

**Comment by fadster** [comment]
It's ```v4pm2.vaughnsoft.net``` now.

**Comment by nestukh** [comment]
quick installing in `$HOME/streamlink_env` folder:

```
sudo apt-get install -y libffi-dev libssl-dev python-dev virtualenv
sudo pip uninstall -y streamlink  
python3 -m virtualenv $HOME/streamlink_env --python=$(ls -1 /usr/bin/python3* | grep -P "\d$" | tail -n1)
source $HOME/streamlink_env/bin/activate
pip install --upgrade streamlink
wget -q -O $HOME/streamlink_env/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py https://pastebin.com/raw/sWCwES3E
sed -i -e "s/https:..mp4-rem.vaughnsoft.net/https:\/\/v4pm2.vaughnsoft.net/g" $HOME/streamlink_env/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py
deactivate
cd
echo -e "#\041/bin/bash
source $HOME/.bashrc
source $HOME/streamlink_env/bin/activate
streamlink \"\$@\"
deactivate
exit 0" > $HOME/streamlink_env/streamlink
chmod a+x $HOME/streamlink_env/streamlink
if [[ "$(cat $HOME/.bashrc | grep "streamlink_env/streamlink")" == "" ]]; then
  echo -e "alias streamlink=\"$HOME/streamlink_env/streamlink\"\n" >> $HOME/.bashrc
fi
```
.
.
quick updating in `$HOME/streamlink_env` folder:
```
source $HOME/streamlink_env/bin/activate
pip install --upgrade pip
pip install --upgrade streamlink
# https://github.com/streamlink/streamlink/issues/2178 # keep this link in a comment, will come handy...
wget -q -O $HOME/streamlink_env/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py https://pastebin.com/raw/sWCwES3E
sed -i -e "s/https:..mp4-rem.vaughnsoft.net/https:\/\/v4pm2.vaughnsoft.net/g" $HOME/streamlink_env/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py
deactivate
```

**Comment by nestukh** [comment]
I'm expecting `8k265hvec2πr.vaughnsoft.net` at some point in the future <sup>1</sup>

<sup>1</sup>It's a joke, /s

**Comment by nestukh** [comment]
`403 error`
they've changed something else, it just won't play, 
the` stream_url` is correct, 
maybe is the port this time?

**Comment by fadster** [comment]
Yes, there have been several changes. In particular, it seems the secure token and expiry are now generated using Google reCAPTCHA. The ones printed in the page source are invalid, hence the 403 Forbidden error. This makes it harder to generate a working ```stream_url``` automatically. It's still possible to get the correct values using something like Fiddler and then manually entering them. However, at the moment, I'm not sure how to automate the process. The code that solves the captcha is in ```channel_footer_html5.js```. It stores the token and expiry in ```window.vs_rct``` and ```window.vs_rct_e```, respectively. We need to implement this logic in the plugin.

**Comment by techmouse** [comment]
Why are they more focused on fighting streamlink than on making their site more accessible? People with weak hardware, old hardware, 4:3 aspect ratio monitors, and things like that have a significantly worse experience when using web browsers. Media players are simply better suited for playing media. It would be wise to integrate and take advantage of them. Even twitch is putting ads directly into the streams. Collaboration is clearly the smart move here.

**Comment by gravyboat** [comment]
@techmouse The owner of Vaughnlive commented in an issue a while back (I don't have time to find it right now, but if you search `vaughnlive` and go look at the old closed issues it is there) and since it's a small organization we're bypassing ads so they aren't making any money even though it's pretty clear that people use Streamlink because their website experience is awful. I'm very against the site any way since it's almost exclusively stolen content so complaining about lost ad revenue on streams that clearly aren't legit is a bit hypocritical, but that's not the issue here.

**Comment by fadster** [comment]
I advise those who still want to use this plugin to keep a local copy. You simply have to pass in the required info (token and expiry) manually. This can probably be done programmatically using something like Selenium if anybody is familiar enough with it and is willing to give it a try.

**Comment by TaoziDB** [comment]
website changes since plugin remove due to google reCAPTCHA, now no google reCAPTCHA any more, just a simple cloudflare protection, can some one take a look again?

**Comment by mkbloke** [comment]
@TaoziDB, although I have not looked at the site, typically, the Cloudflare protection is just as much a problem as Google reCAPCHA to get around.  I doubt there is much interest from any maintainers in reinstating this plugin, as the site was changed continually to thwart things like Streamlink in the past and will probably continue to do so if Streamlink were to reinstate the plugin.

**Comment by gravyboat** [comment]
This issue is 4 years old. I'm locking it. As @mkbloke there's nothing we can do about Cloudflare protection.
