### ISSUE TITLE
HLS: New command to use stream=True from requests for segments

### ISSUE THREAD

**Issue by back-to** [streamlink/streamlink#2180]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Add an option to use `stream=True` for HLS Streams Stream

https://github.com/streamlink/streamlink/blob/cd6f94a5a4ee83cb5b61a295df9e13956bcfcb27/src/streamlink/stream/hls.py#L106-L110

Example `--hls-segment-stream-data` or another name
which will turn `stream=True` or `stream=False`

### **HLSStreams**

It was already added in https://github.com/streamlink/streamlink/pull/260
but removed in https://github.com/streamlink/streamlink/pull/522 because it had some issues.

it might be better with a command where you can turn it on and off

_there might be still some issues with it, but it can be ignored see below for an example_

basically required for Twitch low latency https://github.com/streamlink/streamlink/issues/1676
to get the same delay as the browser or better, you can't get the same time as the browser without _stream=True_

### Expected / Actual behavior

New command to use `stream=True` from requests for HLS segments as an optional option.

### Example Code

_ChunkedEncodingError_ might skip a segment but the latency should be more important for some livestreams than a missing frame,
also this issue is very rare.

this code is only used for normal hls streams

```diff
diff --git a/src/streamlink/stream/hls.py b/src/streamlink/stream/hls.py
index 8a67f564..fecc54f4 100644
--- a/src/streamlink/stream/hls.py
+++ b/src/streamlink/stream/hls.py
@@ -4,6 +4,7 @@ import struct
 
 from collections import defaultdict, namedtuple
 from Crypto.Cipher import AES
+from requests.exceptions import ChunkedEncodingError
 
 from streamlink.exceptions import StreamError
 from streamlink.stream import hls_playlist
@@ -45,6 +46,8 @@ class HLSStreamWriter(SegmentedStreamWriter):
         self.byterange_offsets = defaultdict(int)
         self.key_data = None
         self.key_uri = None
+        self.stream_data = options.get("hls-segment-stream-data")
+
         if self.ignore_names:
             # creates a regex from a list of segment names,
             # this will be used to ignore segments.
@@ -104,6 +107,8 @@ class HLSStreamWriter(SegmentedStreamWriter):
                 return
 
             return self.session.http.get(sequence.segment.uri,
+                                         stream=(self.stream_data
+                                                 and not sequence.segment.key),
                                          timeout=self.timeout,
                                          exception=StreamError,
                                          retries=self.retries,
@@ -134,8 +139,12 @@ class HLSStreamWriter(SegmentedStreamWriter):
 
             self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
         else:
-            for chunk in res.iter_content(chunk_size):
-                self.reader.buffer.write(chunk)
+            try:
+                for chunk in res.iter_content(chunk_size):
+                    self.reader.buffer.write(chunk)
+            except ChunkedEncodingError:
+                log.error("Download of segment {0} failed", sequence.num)
+                return
 
         log.debug("Download of segment {0} complete", sequence.num)
```

---

**EDIT**: Removed DASH, HLS is enough

**Comment by beardypig** [comment]
Could do this as an intermediate solution. I started work on a rewrite of the Stream classes to support this behaviour with retries, resume, etc. However I have not had time to finish it...
