### ISSUE TITLE
Twitch failure - WinError 10061 - No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by sqz** [streamlink/streamlink#2183]
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Description

> streamlink.exe twitch.tv/drjayfisto

[Streamlink for Windows v0.11.0 - Git 64c22e0]
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /kraken/users.json?as3=t&login=drjayfisto (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x035A09F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
[End of Streamlink for Windows with ExitCode 1]

### Expected / Actual behavior

I expect a VLC video window to open with the requested Twitch stream video content. Actually get the above command line error.

### Reproduction steps / Explicit stream URLs to test

1. Microsoft Windows 7 or higher. Start Menu. Type "cmd". 
2. Type "streamlink twitch.tv/drjayfisto"

### Log output

```
[Streamlink for Windows v0.11.0 - Git 64c22e0]
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/drjayfisto
[plugin.twitch][debug] Getting live HLS streams for drjayfisto error: Unable to open URL: https://api.twitch.tv/kraken/users.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /kraken/users.json?as3=t&login=drjayfisto (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x035A19B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
[End of Streamlink for Windows with ExitCode 1]
```

### Additional comments, screenshots, etc.

Above command fails with any streamer name, i.e. the part after the final forward slash in "twitch.tv/drjayfisto"

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by sqz** [comment]
Same error occurs with latest version:

[Streamlink for Windows v0.14.2 - Git 215d789]
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.14.2+215d789
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/drjayfisto
[plugin.twitch][debug] Getting live HLS streams for drjayfisto
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (HTTPSConnectionPool(host='api.tw
itch.tv', port=443): Max retries exceeded with url: /kraken/users.json?as3=t&login=drjayfisto (Cause
d by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A32FF0>: Failed t
o establish a new connection: [WinError 10061] No connection could be made because the target machin
e actively refused it',)))
[End of Streamlink for Windows with ExitCode 1]

**Comment by sqz** [comment]
[Streamlink for Windows v0.11.0 - Git 64c22e0]
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/drjayfisto
[plugin.twitch][debug] Getting live HLS streams for drjayfisto error: Unable to open URL: https://api.twitch.tv/kraken/users.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /kraken/users.json?as3=t&login=drjayfisto (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x035A19B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
[End of Streamlink for Windows with ExitCode 1]

**Comment by sqz** [comment]
Same error occurs with the most recent release version of Streamlink for Windows:

[Streamlink for Windows v0.14.2 - Git 215d789]
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.14.2+215d789
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/drjayfisto
[plugin.twitch][debug] Getting live HLS streams for drjayfisto
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /kraken/users.json?as3=t&login=drjayfisto (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A32FF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)))
[End of Streamlink for Windows with ExitCode 1]

**Comment by bastimeyer** [comment]
> Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03A32FF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)

Check your system's network connection. This is not an issue of Streamlink or its dependencies.

https://stackoverflow.com/questions/20437701/winerror-10061-no-connection-could-be-made
https://www.google.com/search?q=winerror+10061+python

**Comment by sqz** [comment]
It has worked for years and nothing has changed on my PC at all in months.

Now it has just started working again.

I'm starting to believe it is something at Twitch server end.
