### ISSUE TITLE
please add a argument for not checking protected stream

### ISSUE THREAD

**Issue by ghoshben** [streamlink/streamlink#2184]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Normally whenever a mpeg dash is proteceted with DRM streamlink avoids to download the stream, (as we cannt play the encrypted stream) .However is it possible to download the DRM protected mpd and marge video to mp4 and audio to aac or any other container (I know it will be encrypted )

### Expected / Actual behavior

Currently I am on a project for decrypting some stream , It would be better if stream link could handle the download part

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
you probably need

- the MPD file with the Content Keys
- all segments or Video + Audio

which is more than 1 file

looks like this is **out of scope for Streamlink**,
if you can't use your decrypter directly with Streamlink like RTMPDump

**Comment by ghoshben** [comment]
made my own modified streamlink. thank u for this amazing tool

**Comment by 3Letters9** [comment]
@ghoshben streamlink is not able to get mpd getting error protected by drm any solution

**Comment by 3Letters9** [comment]
> made my own modified streamlink. thank u for this amazing tool



> made my own modified streamlink. thank u for this amazing tool

streamlink is not able to get mpd getting error protected by drm any solution

**Comment by 10362227** [comment]
> modified streamlink

please send me modified streamlink, thanks
