### ISSUE TITLE
URL parameters (via &) are lost

### ISSUE THREAD

**Issue by jackyaz** [streamlink/streamlink#2185]
## Bug Report
- [x ] This is a bug report and I have read the contribution guidelines.

### Description
0.14.2 on Windows 10
Attempting to pass an RTMP URL from an IP Camera, results in Streamlink splitting on the & character

### Expected / Actual behavior

Expected - RTMP stream will be played
Actual - Error is thrown

### Reproduction steps / Explicit stream URLs to test

streamlink rtmp://10.14.16.81:1935/bcs/channel0_main.bcs?token=[TOKEN]&channel=0&stream=0&user=admin&password=redacted

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin rtmp for URL rtmp://10.14.16.81:1935/bcs/channel0_main.bcs?token=[TOKEN]
[plugin.rtmp][debug] params=rtmp
Available streams: live (worst, best)
'channel' is not recognized as an internal or external command,
operable program or batch file.
'stream' is not recognized as an internal or external command,
operable program or batch file.
'user' is not recognized as an internal or external command,
operable program or batch file.
'password' is not recognized as an internal or external command,
operable program or batch file.
```

### Additional comments, screenshots, etc.

Apologies if this has been reported previously, or already patched

**Comment by bastimeyer** [comment]
This is a feature and normal behavior of the command shell on Windows. Other shells have similar, but more sane behaviors. This is unrelated to Streamlink or any other program you're executing from the command shell.

If there are special characters in a parameter string, you either need to put the parameter into quotation marks, or escape the special characters.

https://stackoverflow.com/questions/1327431/how-do-i-escape-ampersands-in-batch-files

**Comment by jackyaz** [comment]
D'oh - sorry, forgot to check if it was Windows being awkward :(
