### ISSUE TITLE
Support starting twitch VODs from a specified time

### ISSUE THREAD

**Issue by Diazonium** [streamlink/streamlink#219]
Twitch vods can be very annoying to watch, if you want to start from say 2 hours in. Right now the best way to seek in a vod is to speed up the video as much as feasible and wait.
It would be very convenient to be able to specify a start time for vods in the CLI. Does not need to be accurate, it is fine if it snaps to the following keyframe/stream chunk.

**Comment by bastimeyer** [comment]
See #134 or my answer https://github.com/streamlink/streamlink/issues/134#issuecomment-258955841

**Comment by gravyboat** [comment]
Closing this for now, plenty of discussion over in #134.
