### ISSUE TITLE
can some one till me how to finde https://www.firstonetv.net  the api like this please

### ISSUE THREAD

**Issue by jasonalshamary** [streamlink/streamlink#2190]
_Originally posted by @gravyboat in https://github.com/streamlink/streamlink/issues/1763#issuecomment-429577383_

**Comment by jasonalshamary** [comment]
https://www.firstonetv.net/api/?action=channel&ctoken=apptest&c

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues?utf8=%E2%9C%93&q=is%3Aissue+firstonetv
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
