### ISSUE TITLE
ustvnow stream-url not valid

### ISSUE THREAD

**Issue by masterix83** [streamlink/streamlink#2191]
i was trying to use the stream-url feature on USTVNOW. It showed up a proper url but when i used copy+paste into VLC, the stream url is not valid. i also sent some http requests via curl and it said 403 forbidden. any ideas why this does not work? thank you.

**Comment by beardypig** [comment]
You likely need the authentication cookies as well, the `--stream-url` option is not always guaranteed to give you a playable stream URL if there is authentication involved.

**Comment by back-to** [comment]
> i also sent some http requests via curl and it said 403 

you can find more details about the headers / cookies with [--json](https://streamlink.github.io/cli.html#cmdoption-j) instead of --stream-url

---

closing, make sure to send all needed headers / cookies
https://github.com/streamlink/streamlink/issues/2191#issuecomment-444255624
