### ISSUE TITLE
Specify manually the network interface to use in a multi-homed setup?

### ISSUE THREAD

**Issue by rkkoszewski** [streamlink/streamlink#2192]
## Feature Request
Add the possibility to manually specify the network interface to use. Which can be very useful for multi-homed networks with multiple network interfaces.

### Description

In Streamlink you can specify the proxy to use for streaming. Similar to that it would be also very useful if it would be possible to specify which network interface to use for streaming.

### Expected / Actual behavior

Be able to specify for example "--interface eth1" to use the eth1 interface for streaming.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
closing,
this feature is not really important for Streamlink.
