### ISSUE TITLE
Chaturbate error: No plugin can handle URL

### ISSUE THREAD

**Issue by earthtone2** [streamlink/streamlink#2197]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ... Open a Chaturbate link with streamlink, such as https://chaturbate.com/vany_love

### Log output

```
streamlink https://chaturbate.com/vany_love best -o test.mp4 --loglevel debug
[cli][debug] OS:         Linux-4.4.0-31-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 0.14.2+170.g3946184
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
error: No plugin can handle URL: https://chaturbate.com/vany_love
```

### Additional comments, screenshots, etc.

The version of streamlink from the Ubuntu repository, 0.9, worked for me before. I've just now upgraded to 0.14.2 and this is happening.

The main reason I upgraded is I really want the `retry-max=1` option, which is new, or I would just use the old version.

**Comment by back-to** [comment]
NSFW plugins are not supported anymore

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

if you still want to use it,
you can **sideload** the last available version

https://streamlink.github.io/cli.html#sideloading-plugins

Folder for user plugins `~/.config/streamlink/plugins/`

last available version
https://raw.githubusercontent.com/streamlink/streamlink/2cfa2110f90b1cd6e65a7010b4cf3b692dd9202d/src/streamlink/plugins/chaturbate.py

**Comment by earthtone2** [comment]
Thanks very much. I saw that link about sideloading before, but there was no instructions on how to find the plugin itself.

Maybe NSFW plugins should be removed from the list of plugins? https://streamlink.github.io/plugin_matrix.html

Because that's ultimately why I opened this; I assumed that must be the list of plugins in the current release.

**Comment by gravyboat** [comment]
@earthtone2 The reason they're still in there is because we haven't done a release in a while so the old stable docs still have them. Once we push a new release out they will be gone from the plugin matrix. Sorry about the confusion.

**Comment by tipplerty** [comment]
Trying to sideload the plugin into docker but still get error: No plugin can handle.  Not sure what the correct path should be?  Any help is appreciated.
```
FROM python:3-alpine

RUN apk add gcc musl-dev --no-cache \ 
	&& pip install streamlink \ 
	&& apk del gcc musl-dev --no-cache \ 
	&& rm -Rf /tmp/* 
	
ADD https://gist.githubusercontent.com/tipplerty/f98ec98a554c76ee4de6230bcbde9503/raw/c7c1fb751fab0597eb00c2a4c069164e195b781c/chaturbate.py /home
ADD https://gist.githubusercontent.com/tipplerty/3d7de56547b98e078e8e2c64f7508478/raw/6dbfd3ed21bc91481223fb22d5359f3408fa2fd3/streamlink-recorder.py /

CMD python ./streamlink-recorder.py ${streamLink} ${streamQuality} ${streamName} ${streamOptions}
CMD python ./streamlink-recorder.py ${streamLink1} ${streamQuality} ${streamName1} ${streamOptions}```

**Comment by beardypig** [comment]
[Sideloading Plugins](https://streamlink.github.io/cli.html#sideloading-plugins) the path where the plugins need to be to be side loaded is outlined in the docs.

**Comment by tipplerty** [comment]
> [Side-loading Plugins](https://streamlink.github.io/cli.html#sideloading-plugins): the path where the plugins need to be to be side loaded is outlined in the docs.

New to Python & Docker.  
Did some research and found it using `pip show streamlink`
Location is `/usr/local/lib/python3.7/site-packages/streamlink/plugins/`
