### ISSUE TITLE
Maintain a connection, even when the connection is over

### ISSUE THREAD

**Issue by DonPepeSun** [streamlink/streamlink#2200]
I use windows
What i should to do to streamlink doesnt finish a conection hls ?
For example, i was saving a live stream,them the live finished, but that connection would return time later,maybe un hours ,minutes .. and I had to record the transmission again

I do not know if I did well, but i tried --hls-timeout option,and doesnt work for me.
I tried this: 

`Streamlink [URL] best --hls-timeout 200-o Example.ts`

I really dont know i should use --hls-timeout
Please a i need help

**Comment by back-to** [comment]
> but that connection would return time later,maybe un hours ,minutes ..

there are **some other issues** with a different wording which would make sense,
but this here is just out of scope for this project.
