### ISSUE TITLE
WWE Network broken on latest nightly

### ISSUE THREAD

**Issue by NikoofDeath** [streamlink/streamlink#2201]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description
Recently (I forget exactly when, somewhere in the last 4-6 months) the WWE Network plugin stopped working, giving an error `Unable to open URL: None (Invalid URL 'None': No schema supplied. Perhaps you meant http://None?)` when trying to use it. I can only assume this is due to a change on WWE's end, as it had stopped working while I was using a streamlink version that it had previously worked on.

### Reproduction steps / Explicit stream URLs to test

1. Install latest streamlink nightly (same issue occurred on earlier versions)
2. Configure for WWE Network (set wwenetwork-email and wwenetwork-password)
3. Try to launch any WWE Network video (i.e. `streamlink http://network.wwe.com/video/v1873366483 best`)

### Log output

```
streamlink http://network.wwe.com/video/v1873366483 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 0.14.2+170.g3946184
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/video/v1873366483
[cli][debug] Plugin specific arguments:
[cli][debug]  --wwenetwork-email= (email)
[cli][debug]  --wwenetwork-password= (password)
[plugin.wwenetwork][debug] Found content ID: 1873366483
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: None (Invalid URL 'None': No schema supplied. Perhaps you meant http://None?)
```

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/fb6a00c86bbf752b578ea317cdede242a2b4e836/src/streamlink/plugins/wwenetwork.py#L163-L165

`url` might be `None` here,
but it is not possible to debug it without an account.

make sure that this is not just a temporary error,
do other videos work?

**Comment by back-to** [comment]
impossible to debug without any response or account
