### ISSUE TITLE
Output video to Windows 10 "Movies & TV" app?

### ISSUE THREAD

**Issue by besweeet** [streamlink/streamlink#2202]
Not sure if it's even possible due to the way Windows 10 works, but is it possible to output streamlink feeds to the Windows 10 "Movies & TV" app? I'd like to see how it compares to VLC and MPC in terms of CPU & GPU utilization, hoping it could be better optimized, allowing for better battery life.

**Comment by back-to** [comment]
it doesn't look like that there is a direct `.exe` path which is accessible as a normal User,
closing as this is out of scope for this project.
