### ISSUE TITLE
Afreecatv not working again?

### ISSUE THREAD

**Issue by tenminute** [streamlink/streamlink#2203]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Seems to have stopped working some odd hours ago. It was working this morning but I've been getting an error the past hour. Maybe they're redoing stuff again?

### Reproduction steps / Explicit stream URLs to test
http://play.afreeca.com/user best

### Log output

```
C:\Users\User>streamlink http://play.afreeca.com/user best
[cli][info] Found matching plugin afreeca for URL http://play.afreeca.com/user
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.SwKSrXv6ItOFi5pR1fJb8AIpawXGUhzWZWS0TZhvegqQUewAVNAFbTZYH0uIKZaRe9KCWUo--B9Cu7aZnQAyN1OqyPT4DTB362QBwR6wrVQ')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.SwKSrXv6ItOFi5pR1fJb8AIpawXGUhzWZWS0TZhvegqQUewAVNAFbTZYH0uIKZaRe9KCWUo--B9Cu7aZnQAyN1OqyPT4DTB362QBwR6wrVQ (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.SwKSrXv6ItOFi5pR1fJb8AIpawXGUhzWZWS0TZhvegqQUewAVNAFbTZYH0uIKZaRe9KCWUo--B9Cu7aZnQAyN1OqyPT4DTB362QBwR6wrVQ&aid=.A32.7bbT56vyHM9fKZk.SwKSrXv6ItOFi5pR1fJb8AIpawXGUhzWZWS0TZhvegqQUewAVNAFbTZYH0uIKZaRe9KCWUo--B9Cu7aZnQAyN1OqyPT4DTB362QBwR6wrVQ))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.SwKSrXv6ItOFi5pR1fJb8AIpawXGUhzWZWS0TZhvegqQUewAVNAFbTZYH0uIKZaRe9KCWUo--B9Cu7aZnQAyN1OqyPT4DTB362QBwR6wrVQ')>, tried 1 times, exiting
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by ChocolateThunder69** [comment]
Same problem here also

**Comment by ZenWalk3r** [comment]
Same problem, cant solve using back-to's commit

**Comment by ZenWalk3r** [comment]
Same, cant load the stream

**Comment by tenminute** [comment]
Couldn't get @back-to's commit to work, but Afreeca's server is/was messed up today. A lot of streams and functionality were not working on both the site and on mobile.  There was supposed to be a larger scale update/change scheduled for the site today (or the 20th in Korea), but it's being postponed until next month. But then, the server issue happened. So not only will there maintenance some time in January, Afreeca will be down for maintenance/server reboot on the 20th, from 6am-7am (Korean time, which is in the next two hours of this post).

**Comment by sephadox** [comment]
@back-to's commit works. It messes with the login script but there's really no point in logging in unless you're watching questionable 19+ streams.

**Comment by back-to** [comment]
> Couldn't get ... commit to work, but Afreeca's server is/was messed up today.

@tenminute share your **URL** which won't work and a **debug log**.

---

> It messes with the login script

@sephadox share a **debug log**, login works for me

make sure that there are **no** spaces or other characters added to your username/password

**Comment by tenminute** [comment]
I just reinstalled the latest stable version on both my laptop and PC, but it's still not working. All I do is replace "afreeca.py" plugin with this one, correct? Or am I doing something wrong?
https://github.com/streamlink/streamlink/blob/8600b9a968c47892ca20eb7f2f5ec234a71717ce/src/streamlink/plugins/afreeca.py

WITHOUT the login, I get the same error on both laptop and PC. WITH the login, I can only log in on PC.


**On my laptop without login (error):**
```
C:\Users\User>streamlink play.afreeca.com/battle8807 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin afreeca for URL play.afreeca.com/battle8807
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-02/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.xpBD8nB_og7FlS_nQmJrgqycULZ-NIABA83ZTtUtTwpiFLykd1yW767UrJYp-jHf3peCo8fa0lF60RxuPXCeFJXWnTi0-speVEG5N0ChaXA')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/livestream-east-02/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.xpBD8nB_og7FlS_nQmJrgqycULZ-NIABA83ZTtUtTwpiFLykd1yW767UrJYp-jHf3peCo8fa0lF60RxuPXCeFJXWnTi0-speVEG5N0ChaXA (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/livestream-east-02/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.xpBD8nB_og7FlS_nQmJrgqycULZ-NIABA83ZTtUtTwpiFLykd1yW767UrJYp-jHf3peCo8fa0lF60RxuPXCeFJXWnTi0-speVEG5N0ChaXA&aid=.A32.7bbT56vyHM9fKZk.xpBD8nB_og7FlS_nQmJrgqycULZ-NIABA83ZTtUtTwpiFLykd1yW767UrJYp-jHf3peCo8fa0lF60RxuPXCeFJXWnTi0-speVEG5N0ChaXA))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-02/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.xpBD8nB_og7FlS_nQmJrgqycULZ-NIABA83ZTtUtTwpiFLykd1yW767UrJYp-jHf3peCo8fa0lF60RxuPXCeFJXWnTi0-speVEG5N0ChaXA')>, tried 1 times, exiting
```

**On my laptop with login (error):**
```
C:\Users\User>streamlink --afreeca-username=******** --afreeca-password=******** play.afreeca.com/battle8807 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin afreeca for URL play.afreeca.com/battle8807
[cli][debug] Plugin specific arguments:
[cli][debug]  --afreeca-username=******** (username)
[cli][debug]  --afreeca-password=******** (password)
[plugin.afreeca][debug] Attempting login as ********
error: Unable to open URL: https://member.afreecatv.com:8111/login/LoginAction.php (404 Client Error: Not Found for url: https://member.afreecatv.com:8111/login/LoginAction.php)
```

**On my PC with login (able to log in):**
```
C:\Users\User>streamlink --afreeca-username=******** --afreeca-password=******** play.afreeca.com/battle8807 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin afreeca for URL play.afreeca.com/battle8807
[cli][debug] Plugin specific arguments:
[cli][debug]  --afreeca-username=******** (username)
[cli][debug]  --afreeca-password=******** (password)
[plugin.afreeca][debug] Attempting login as ********
[plugin.afreeca][info] Successfully logged in as ********
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.MtPFSMRGozqkVCvfUqtN4IKp-pwWKf4_VKtEDquZKwhNUryCnYZ-pQBbNgCXrE0LpmfxdU4OhgyST8n5UuBUKM9otVoRXYxXhV4zcd00wrU')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/livestream-east-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.MtPFSMRGozqkVCvfUqtN4IKp-pwWKf4_VKtEDquZKwhNUryCnYZ-pQBbNgCXrE0LpmfxdU4OhgyST8n5UuBUKM9otVoRXYxXhV4zcd00wrU (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/livestream-east-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.MtPFSMRGozqkVCvfUqtN4IKp-pwWKf4_VKtEDquZKwhNUryCnYZ-pQBbNgCXrE0LpmfxdU4OhgyST8n5UuBUKM9otVoRXYxXhV4zcd00wrU&aid=.A32.7bbT56vyHM9fKZk.MtPFSMRGozqkVCvfUqtN4IKp-pwWKf4_VKtEDquZKwhNUryCnYZ-pQBbNgCXrE0LpmfxdU4OhgyST8n5UuBUKM9otVoRXYxXhV4zcd00wrU))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-05/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.MtPFSMRGozqkVCvfUqtN4IKp-pwWKf4_VKtEDquZKwhNUryCnYZ-pQBbNgCXrE0LpmfxdU4OhgyST8n5UuBUKM9otVoRXYxXhV4zcd00wrU')>, tried 1 times, exiting
```

**Comment by nOLanSea** [comment]
Same, afreeca stopped worked.
Please fix it.

**Comment by back-to** [comment]
@tenminute 

I can't access `afreeca.com` it's `afreecatv.com` for me

could you confirm that it's `afreeca.com` for you or if you can access  `afreecatv.com`

---

also could you check which domain is used for the other paths in your browser

**api**

https://github.com/streamlink/streamlink/blob/7d3b55dad7f93e5cc6e8bff4ea2dc8341755f207/src/streamlink/plugins/afreeca.py#L8

**login**

https://github.com/streamlink/streamlink/blob/7d3b55dad7f93e5cc6e8bff4ea2dc8341755f207/src/streamlink/plugins/afreeca.py#L49

you can see them with the Network requests _(press F12 and reload)_

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Network_request_list

**Comment by tenminute** [comment]
@back-to Hmmm... I've always used `afreeca.com` rather than `afreecatv.com` and never had a problem (since, I believe it was just `afreeca.com` back in the day).

Anyway... works! Login works, too. Appreciate it!

**Comment by ZenWalk3r** [comment]
@back-to Everything working fine now, recopied the script then login started working.

Thanks a bunch! Much appreciated.

**Comment by back-to** [comment]
@ZenWalk3r 

your url is wrong it must be `play.afreeca.com/user` not `afreecatv.com/user`

---

I will update my PR where only `play.afreecatv.com` can be used and everything else is not allowed.

**Comment by nOLanSea** [comment]
So how to fix it ?

**Comment by tastyminerals** [comment]
Replacing `afreeca.py` does not fix the issue.
Please, invest 1 minute and explain how to fix it. Seriously.

**Comment by bastimeyer** [comment]
Follow the instructions on the Streamlink website and install the latest unstable release / daily build.

**Comment by crunchor** [comment]
Doesn't work for me like a month so far, any idea how to fix this?

**Comment by bastimeyer** [comment]
In case you're using the **latest** Streamlink version and it's still failing, please open a [new plugin issue](https://github.com/streamlink/streamlink/issues/new?template=plugin_issue.md) and fill in the necessary details.
