### ISSUE TITLE
[QUESTION] - AES-128 vs SAMPLE-AES

### ISSUE THREAD

**Issue by Ike348** [streamlink/streamlink#2212]
## Issue

- [x ] This is not a bug report, feature request, or plugin issue/request.
- [ x] I have read the contribution guidelines.

### Description

The following doesn't necessarily pertain to streamlink, but I have not seen a resource with the information I'm looking for, so I figured I'd use this platform to confirm what I have gathered, and get the answers I'm looking for. If this is not the right place, please don't lock/close this thread without directing me to some other forum where this discussion would be more appropriate.

Here's what I've gathered, please correct me if this is wrong.

A lot of streams that people feed into streamlink are encrypted, meaning the program can't just download a segment and save it or send it to a player without decrypting it somehow. With HLS streams that are encrypted with AES-128, this is relatively straightforward. The necessary key is linked to in the .m3u8 file, so streamlink can download that easily. Sometimes some cookies or headers are required to avoid a 401 Unauthorized error, but streamlink is good at telling the user exactly what it needs, and once the header is supplied, streamlink can download the key. Then, streamlink feeds the key and the segment into some other module (pycryptodome?) and then that other module decrypts the segment, and then returns it to streamlink who will then send it over to a player or cat it on to the saved file. This is the process for AES-128 streams. However, when I try to record a stream that is encrypted with SAMPLE-AES, streamlink tells me it can't do anything with SAMPLE-AES. Other applications like ffmpeg or youtube-dl are even more unhelpful with these streams—youtube-dl tells me "no video formats found," and ffmpeg spits out a bunch of garbled nonsense.

Why is this the case? I haven't found much info out there on SAMPLE-AES out there, but one [page](http://bitmovin.com/docs/encoding/faqs/what-is-hls-aes-encryption) tells me this:

> AES-128 encrypts the whole segment with the Advanced Encryption Standard (AES) using a 128 bit key.

> SAMPLE-AES encrypts each individual media sample (e.g., video, audio, etc.) by its own with AES. SAMPLE-AES allows fine grained encryption modes, e.g., just encrypt I frames, just encrypt 1 out of 10 samples, etc.

Why does this seemingly minute difference cause so much trouble? I _think_ the answer is that streamlink and youtube-dl really have _nothing to do with video_. Again, correct me if I'm wrong, but really all streamlink does is read a text file, look for links to files, downloads those files, and pipes them to stdout or whatever the user chooses. All of the command line arguments really only affect how often streamlink looks for files (delay, timeouts, etc.) or what files to look for (resolution). This means the decrypting process also has nothing to do with video either—the decrypting module would work just the same if you gave it a key and a .docx file as opposed to a key and a .ts file. This is why AES-128 encrypted streams work fine with all of these tools, as the entire segment is encrypted.

However, for SAMPLE-AES, the process is much more complex, as SAMPLE-AES is a **video/audio-only** encryption method. Decrypting a SAMPLE-AES stream involves reading the actual video and audio streams to find the encrypted blocks and frames. Only then can you use the key information to decrypt and play. Streamlink or youtube-dl can't do this because they don't really "do" anything with video, and applications that do work with video like ffmpeg can't do this simply because the process is very tricky, and there's not much demand for it because it only applies to video/audio streams. Is this correct?

Now, for my final question, which probably has quite a simple answer but not one that I've been able to find:

**Why can my browser play a SAMPLE-AES encrypted stream, but no other standalone software can?**

From my experience, all the information that my browser uses to be able to play a stream (such as authorization headers, user agents, cookies, etc.), I have access to as well, and I can feed them into another application. When I look into a SAMPLE-AES m3u8 file, I see `#EXT-X-FAXS`, `#EXT-X-KEY:METHOD=SAMPLE-AES,KEYFORMAT=...` and so on. The player in Google Chrome or any other browser clearly reads and uses this information to play the stream just fine. Why is this so difficult to do outside of a browser?

I just have these questions really for my own knowledge, and I want to get answers recorded for anyone else wondering the same things. I can supply a ZIP file with a sample ts file, m3u8 file, and even a key that I attempted to download with cURL. Again, if this doesn't belong here, please direct me somewhere else. I love streamlink for what it does, and I hope you guys are knowledgable and patient enough to help me out here.

Thank you so much!

**Comment by back-to** [comment]
`SAMPLE-AES` **is DRM most of the time.** (see https://github.com/streamlink/streamlink/issues/354)

https://en.wikipedia.org/wiki/Digital_rights_management
https://bitmovin.com/what-is-drm/

> Why can my browser play a SAMPLE-AES encrypted stream, but no other standalone software can?

you can turn off DRM in Firefox and all these type of streams will not work.

https://support.mozilla.org/en-US/kb/enable-drm

> I hope you guys are knowledgable and patient enough to help me out here.

basically just search about DRM 

---

It can be decrypted, but I don't think there is any **user friendly open source software** for this.

---

Kodi can play some DRM https://github.com/peak3d/inputstream.adaptive
if someone wants to play it without a browser on a TV.
