### ISSUE TITLE
dogus.py KRAL TV Plugin error: Unable to open URL:

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#2213]
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description dogus.py

Normally the picture and the sound should come, none of it will come

### Reproduction steps / Explicit stream URLs to test

1. https://www.kralmuzik.com.tr/tv/kral-pop-tv

### Log output
                                                                       
streamlink http://www.kralmuzik.com.tr/tv/kral-pop-tv best
[cli][info] Found matching plugin dogus for URL http://www.kralmuzik.com.tr/tv/kral-pop-tv
error: Unable to open URL: https://dygvideo.dygdigital.com/live/hls/kralpop?token= :  (403 Client Error: Forbidden for url: https://dygvideo.dygdigital.com/live/hls/kralpop?token=%20:%20)

**Comment by beardypig** [comment]
Many of the dogus channels have migrated to YouTube for live streaming.
