### ISSUE TITLE
adultswim claims unsupported URL

### ISSUE THREAD

**Issue by soulofmischief** [streamlink/streamlink#2218]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

In 0.14.2, attempting to load a stream of the form `http://adultswim.com/streams/path/to/stream` or similar syntactic variations returns `No plugin can handle URL`.

Running `--can-handle-url` returns nothing.

### Reproduction steps / Explicit stream URLs to test

1. Try to download an adultswim stream.
2. Nope.

### Log output

```
[cli][debug] OS: Windows 7
[cli][debug] Python: 3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
error: No plugin can handle URL: [redacted]
```

**Comment by beardypig** [comment]
Any reason to not share the stream path? Could be helpful in debugging.

**Comment by soulofmischief** [comment]
Wasn't sure if I was 100% legally protected were I to mention trying to download a particular piece of content on an open forum, due to the DRM involved. Obviously I'm breaking TOS but I don't want to open myself up to any lawsuits. Any clarification on that?

**Comment by beardypig** [comment]
@soulofmischief, no idea. But without the link, I cannot fix it ;)

**Comment by soulofmischief** [comment]
Here's one, I just checked and it didn't work: https://www.adultswim.com/streams/assembly-line-yeah/monday-december-17th-2018

**Comment by beardypig** [comment]
Thanks @soulofmischief, I will take a look.

**Comment by gravyboat** [comment]
I can confirm this is a problem for me as well:

```
streamlink http://www.adultswim.com/videos/space-dandy/a-merry-companion-is-a-wagon-in-space-baby
[cli][info] Found matching plugin adultswim for URL http://www.adultswim.com/videos/space-dandy/a-merry-companion-is-a-wagon-in-space-bab
[plugin.adultswim][error] Couldn't find the stream data for this stream: space-dandy
error: No playable streams found on this URL: http://www.adultswim.com/videos/space-dandy/a-merry-companion-is-a-wagon-in-space-baby
```

**Comment by soulofmischief** [comment]
I was able to download a stream the other day. Closing this issue.

**Comment by gravyboat** [comment]
Reopened because I'm still encountering the same error that I noted before.
