### ISSUE TITLE
pluzz France.tv Failed to access stream

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#2220]
## Error Report

- [X] This is a bug report and I have read the Posting Guidelines.

### Description

pluzz.py should be able to play the France.fr stations

### Expected / actual behavior

Inserting the page in the streamlink does not play the stream. About my web browser Firefox I see the picture and hear the sound 

### Reproduction steps / Explicit stream URLs to test

<! - How can we reproduce that? Please note the exact steps based on the specified list format. If you need further steps, please add them. ->

1.https://www.france.tv/
2.https: //www.france.tv/france-2/direct.html

### log output

streamlink http://www.france.tv/france-2/direct.html best
[cli] [info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
[plugin.pluzz] [error] Failed to access stream, may be due to geo-restricted content
[plugin.pluzz] [error] Failed to access stream, may be due to expired content
error: No playable streams found on this URL: http://www.france.tv/france-2/direct.html
PS C: \ WINDOWS \ system32>

### Additional comments, screenshots, etc.

 Screenshot

https://i.ibb.co/g99nXC0/france.jpg

**Comment by beardypig** [comment]
Do you have a proxy set up in your browser/OS that you have not configured for streamlink?

**Comment by back-to** [comment]
the plugin works,
if you are not in france you will need a proxy for streamlink.

```
Pour des raisons de droits, cette vidéo n'est pas disponible depuis votre position
géographique. Prochaine vidéo disponible le ...

Ce direct est terminé.
```
