### ISSUE TITLE
Add {url} argument to window --title 

### ISSUE THREAD

**Issue by RomanKornev** [streamlink/streamlink#2225]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description
We have {title}, {author}, {category}, {game}.
https://github.com/streamlink/streamlink/blob/94a8a7301c45dfdee89dd7d4d14043438dda4b38/src/streamlink_cli/argparser.py#L409
If no title format was provided it defaults to `args.url` so it clearly is supported.
https://github.com/streamlink/streamlink/blob/94a8a7301c45dfdee89dd7d4d14043438dda4b38/src/streamlink_cli/main.py#L137-L148
But what if I want a custom title and a url?

### Expected / Actual behavior
`$ streamlink twitch.tv/CHANNEL best --title "{title} - {game} - {url}"`
Actual: `KeyError: 'url'`
Expected: Window title to change to `STREAM_NAME - GAME - twitch.tv/CHANNEL`

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by john2545** [comment]
how about this?
streamlink -p vlc -a "--title abc" twitch.tv/CHANNEL best
