### ISSUE TITLE
Livestream.com with stuttering sound

### ISSUE THREAD

**Issue by niwi-hh** [streamlink/streamlink#2226]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I want to watch  https://livestream.com/accounts/22300522/events/6680139 (Rockland TV) without sound problems.

### Expected / Actual behavior

When I watch https://livestream.com/accounts/22300522/events/6680139 (Rockland TV) the sound stutters depending on the music video currently playing. With some videos the sound is completely free of stutters. Others have constant stutters. There is nothing in between.

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://livestream.com/accounts/22300522/events/6680139 best

### Log output

1. Output while the sound is ok:
https://gist.github.com/niwi-hh/9a170336e7ab7588626eeb874787bcb5

2. Output while the sound is stuttering:
https://gist.github.com/niwi-hh/8b03f947831e8e3c9725646e85a0b9ba

### Additional comments, screenshots, etc.

The problem can be reproduced with all available streams of this channel.

**Comment by gravyboat** [comment]
What video player are you using? If you're using VLC can you try MPV? I listened to a couple songs and I couldn't duplicate the problem.

**Comment by niwi-hh** [comment]
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332) under Ubuntu Bionic 64bit.
I tried it again with media player "parole" version 1.0.1 and have the problem there too.

**Comment by niwi-hh** [comment]
Sorry, I forgot to mention MPV. Same problem there. Version 0.27.2. I could send you a small Mp4-File with the problem recorded. I don't know if I am allowed to publish it here directed for copyright reasons.

**Comment by back-to** [comment]
the issue is **not related to Streamlink**

the video in a webbrowser had the same issue,
but it seems like they fixed it, at least the current DVR has no issues.
