### ISSUE TITLE
API key daily quota exceeded

### ISSUE THREAD

**Issue by omen23** [streamlink/streamlink#2240]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. since my streamlink runs in an hourly cronjob I can only show log output

### Log output

```
[plugin.youtube][error]   Daily Limit Exceeded. The quota will be reset at midnight Pacific Time (PT). You may monitor your quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/youtube.googleapis.com/quotas?project=397735358914 (dailyLimitExceeded)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
the api key got removed from Streamlink in https://github.com/streamlink/streamlink/pull/1888

this issue is already fixed and will be available with a new Streamlink version https://github.com/streamlink/streamlink/pull/2199
