### ISSUE TITLE
Add plugin for tntendirect.com

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#2251]
Hello all,
I was wondering if it was possible to add a plugin for the following tv channel from this website: https://www.tntendirect.com/

Thank you for the consideration :)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Sites which are hosting stolen content as their main source of content
> Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)

This doesn't look like a legal/legit site. There is no contact information to be found and the domain registration entries seem to be faked.

> Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.

https://github.com/streamlink/streamlink/issues/new?template=plugin_request.md
