### ISSUE TITLE
plugin streamcraft.com reqest

### ISSUE THREAD

**Issue by zxosazx** [streamlink/streamlink#2258]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Suddenly I found a streaming service https://streamcraft.com. Is it possible to add a plugin for it?

### Example stream URLs

1. https://streamcraft.com/user/2020018130
2. https://streamcraft.com/user/2013999333/video/777514
3. https://streamcraft-sa.akamaized.net/m3u8/live_rel_WeLive-Ext-OL_14426111_1008_935378.m3u8
4. https://streamcraft.com/user/2011569544

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
This site is full of fake content. Most sections listed on the start page don't have any live streams, although there are allegedly thousands of people watching. Overall there are only 8 streams available.
https://streamcraft.com/videos

I don't think it's worth the effort implementing a plugin here. Also, the company behind it doesn't even have its own site, which makes it a bit questionable.

**Comment by NeoFahrenheit** [comment]
Hmm, I would like it too. :)
Sure, it's unpopular now, but some streamers I follow are there. 

Thank you.

**Comment by back-to** [comment]
Not worth for a new plugin.
