### ISSUE TITLE
Support FacebookLive streaming

### ISSUE THREAD

**Issue by scottbernstein** [streamlink/streamlink#226]
My own research shows that Facebook Live streams are MPEG-DASH format with the audio and video in separate streams that need to be remuxed.  Once this project supports DASH video, we should also be able to support Facebook Live streams.

**Comment by stevek123** [comment]
They also generate RTMP and HLS versions at the same time

**Comment by scottbernstein** [comment]
interesting -- I hadn't noticed that @stevek123


Still would probably be a worthwhile plugin for someone to look into

________________________________

**Comment by stevek123** [comment]
They use different versions in different browsers. I think they also have this habit that you have to log in to get the higher quality (at least for videos, but it's maybe true for streams as well)

**Comment by scottbernstein** [comment]
Yep -- seems like a plugin would be super useful in this case given the complexity of their streaming logic.  I consider myself to be very advanced at tracking down the source link URLs and protocols for most videos, but Facebook has eluded me

________________________________

**Comment by zp** [comment]
Here's a quick script I made for livestreamer back when I found out facebook started live streams.

https://gist.github.com/zp/c461761565dba764c90548758ee5ae9f

There's no validation or anything like that, but it seems to work fairly decently (I don't use the plugin that much), somebody might be able to take this base and make a more robust plugin.

**Comment by roshavagarga** [comment]
Any update on a plugin for FB Live videos? :)

**Comment by besweeet** [comment]
@zp This worked for me. Looks like they cap the HLS quality at 360p. Will streamlink ever support MPD / DASH playback?

**Comment by scottbernstein** [comment]
Yep, HD streaming seems to be DASH only.

________________________________

**Comment by gravyboat** [comment]
Beardypig has been looking at some DASH support but it seems like a pain in the ass. If anyone wants to grease the wheels feel free to post a bounty: https://www.bountysource.com/teams/streamlink/issues otherwise the status right now is that it is being worked on but there is no time frame.

**Comment by WolfganP** [comment]
Wouldn't https://github.com/rg3/youtube-dl/blob/624c4b92ffaa5586dd821db6d10106aa1a067a2e/youtube_dl/extractor/facebook.py help?

**Comment by DawgNewb** [comment]
@zp 

I wonder whats the problem because sometime I tried difference URL and its work fine.

[Streamlink for Windows v0.4.0 - Git 4f7416d]
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/xxxxxx/videos/xxxxxxxx
error: Failed to parse playlist: Missing #EXTM3U header
[End of Streamlink for Windows]

**Comment by roshavagarga** [comment]
@gravyboat Any chance of getting the plugin @zp made to be committed to streamlink? 360p quality is still better than nothing.

**Comment by gravyboat** [comment]
I don't see why not, do you want to open a PR @zp?

**Comment by roshavagarga** [comment]
@gravyboat If he doesn't answer within a set amount of time am I free to post a new issue on this topic, since he clearly said he does not use the plugin much and would like said plugin to be used and expanded on by streamlink

**Comment by gravyboat** [comment]
@roshavagarga Yeah of course, I just want to make sure they get the credit if they desire it.

**Comment by Invictaz** [comment]
@stevek123 yes. When you select a video you get 360P at best on live video. Might have to login to get 720P. Don't know if that is currently supported?

**Comment by gravyboat** [comment]
@Invictaz If you search through the issues you can see we've discussed this several times already. No DASH support at this time. It's a big undertaking to implement, you're welcome to post a bounty if you want to help fund doing so however!

**Comment by Invictaz** [comment]
@gravyboat Yeah I've seen that. I already retrieved the mpd file but cannot play that in VLC. Seems VLC does not support raw mpd files without login.
