### ISSUE TITLE
DASH: Multiple audio streams and subtitles stream (Zattoo Live TV)

### ISSUE THREAD

**Issue by sunsettrack4** [streamlink/streamlink#2260]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I'm currently using my own Zattoo script to pipe the streams to tvHeadend - see here:
https://github.com/sunsettrack4/zattoo_tvh

This script allows me to pipe the streams to tvHeadend - and I can enjoy Zattoo Live TV, combined with PVR features such as timeshift and timer option for recordings.

However, I just discovered the capabilities of streamlink and I would like to use **Zattoo DASH** streams instead of HLS to improve the user experience - **by adding multiple audio streams and the subtitles stream to stdout/stdin**.

### Expected / Actual behavior

In the current version of streamlink, I'm able to set the --hls-audio-select with the "*" option. Of course, this parameter works for HLS streams only. **Zattoo provides all related streams via mpd file.**

There should be an option to pipe the video stream (e.g. best), all audio streams (e.g. German and English) and the subtitles stream to stdout/stdin (for VLC and tvHeadend).

### Additional comments, screenshots, etc.

[manifest.mpd](https://github.com/streamlink/streamlink/files/2775630/manifest.mpd.txt)

**Comment by back-to** [comment]
> I'm able to set the --hls-audio-select with the "*" option. Of course, this parameter works for HLS streams only.

the DashStream's work differently, which makes it unnecessarily complicated.

---

closing, the feature is not really important.

**Comment by popy2k14** [comment]
Tried to record orf-1 with hls and dash but dont get the dolby audio track.
Here is my cmd:

`streamlink.exe https://zattoo.com/channels?channel=orf-1 best --hls-audio-select=* --zattoo-email="XXX" --zattoo-password="XXX" --zattoo-stream-types hls5 -o video_hls.mkv -l debug
`
and

streamlink.exe https://zattoo.com/channels?channel=orf-1 best --zattoo-email="XXX" --zattoo-password="XXX" -o video_dash.mkv -l debug

Does streamlink actually support saving of all audio streams?

**Comment by TheRealBlazeKing** [comment]
> closing, the feature is not really important.

Not important to you, but important to others that need it. This attitude from devs kills me... Years later I need an answer for the solution I have to use and I see this!
