### ISSUE TITLE
Add user agent to hls plugin

### ISSUE THREAD

**Issue by WuvorWenda** [streamlink/streamlink#2261]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

Please add a user-agent to the hls stream plugin.
Its now: User-Agent: python-requests/2.19.1
Some stream sites are protected, i use the browser to extract the m3u8 url, if the user-agent not matches i get a 403 error. I have changed the hls.py plugin, it works now but i am not a python programmer.
My changes are attached as a zip file.
I do not know of my changes are correct. 
Thank you.

[hls.zip](https://github.com/streamlink/streamlink/files/2781850/hls.zip)
.

**Comment by beardypig** [comment]
You can do this on the command line using the [`--http-header`](https://streamlink.github.io/cli.html#cmdoption-http-header) option. eg.

```
streamlink --http-header "User-Agent=some-user-agent" mystream.com/cats best 
```

**Comment by WuvorWenda** [comment]
tested with --http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.116"
Error i get is
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.116

**Comment by gravyboat** [comment]
Closing as this has been answered.
