### ISSUE TITLE
vk.com: support for a permament url

### ISSUE THREAD

**Issue by niwi-hh** [streamlink/streamlink#2262]
## Bug Report
- [x ] This is a bug report and I have read the contribution guidelines.

### Description
I want to watch streams from vk.com without having to change the URL several times a month. For this a constantly available URL should be supported.

### Expected / Actual behavior
I would expect it be enough to give Streamlink permanent URL for a needed stream. It would be Streamlinks task to find out the actual current stream address and stream it. This is the known behavior for most or all other stream-sites supported by Streamlink.

For example I would expect the following to work:
`streamlink https://vk.com/viva_channel best`

Currently I can start a stream with giving Streamlink the URL of the embedded video. E.g.:
`streamlink https://vk.com/video-104514649_456239174`

But since this address doesn't seem to be used permanently a truely permanent is needed. With
`streamlink https://vk.com/viva_channel best`
I get the message
`error: No plugin can handle URL: https://vk.com/viva_channel`

### Reproduction steps / Explicit stream URLs to test
`streamlink https://vk.com/viva_channel best`

### Log output
```
$ streamlink --loglevel debug https://vk.com/viva_channel best
[cli][debug] OS:         Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.15rc1
[cli][debug] Streamlink: 0.14.2+201.g965c375
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
error: No plugin can handle URL: https://vk.com/viva_channel
niwi@TVHeadend:~$ 
```

**Comment by bastimeyer** [comment]
> This is the known behavior for most or all other stream-sites supported by Streamlink.

No, it's not. Pretty much every plugin requires you to provide an unambiguous stream URL. A social media platform with news feeds like this does not work for canonical URLs like you've described above.

The reason behind this is that Streamlink has to know which data to request from the available service API. A URL that points towards a set of posts of different types, eg. links, texts, images or videos, like you can see on basically every social media platform, is not a precise information. Some of the posts you're seeing in your web browser may be hidden for the public eye or may be ordered differently when being requested by Streamlink. This could lead to something you'd not expect when trying to open a video in Streamlink with your proposed method. And in the case that there's no API endpoint/method available for querying only streams/videos from the channel/feed, then you'll have to make as many API requests until you've found the first matching post. In the worst case, you'd have to request every available post, which is incredibly inefficient.

After a quick google search, I've found these API endpoints which VK provides:
https://vk.com/dev/wall.get
https://vk.com/dev/wall.search
https://vk.com/dev/video.search
As far as I can tell, there don't seem to be any video filter parameters for the user/community walls or user/community filter parameters for global video search results.

**Comment by augustgerro** [comment]
I have try to watch this stream. Originaly link works from ok.ru, stream has id 1034940980745. 

`streamlink https://ok.ru/live/1034940980745 best`
It`s Works good for me. 
But I suspect thak if live go down and stream owner will restart this stream, it will receice new ID.
