### ISSUE TITLE
Bigo.tv Plugin broken

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#2263]
Hi,

the bigo.tv plugin (bigo.py) is not working anymore.

"error: No plugin can handle URL"

Someone can have a look please?

Greetings

**Comment by Rotarum** [comment]
Hi beardypig,

nice to meet you 👍 

If you open bigo.tv there is a random livestream video running already.

It's a standard flash video with only one quality preset as i can see so far...

Thanks for the answer :)

Greetings

**Comment by beardypig** [comment]
Please provide a URL that you are trying to use with Streamlink.

**Comment by Rotarum** [comment]
For example:

http://www.bigo.tv/97442962

**Comment by beardypig** [comment]
You should provide the debug logs as well so we can see what version of streamlink you are running. This works for me, so I suspect you are using an old version - install a nightly/dev build or wait until version 1.0.0 is released.
