### ISSUE TITLE
Video recorded from MFC skips and loses footage

### ISSUE THREAD

**Issue by Gimpoid** [streamlink/streamlink#2264]
## Bug Report

- [ x] This is a bug report and I have read the contribution guidelines.

### Description

When recording live shows from https://www.myfreecams.com/ the output video has a lot of skipping and missing data. I have viewed the video via the site and the video is perfectly smooth there.

### Expected / Actual behavior

I expect the captured video to be the same as the video on the website. The video captured skips a lot and has a lot of gaps in the recording.

### Reproduction steps / Explicit stream URLs to test

Using the following you can download any stream for a few hours then view the footage and how it skips.

1. https://github.com/horacio9a/mfc-node

### Log output

```
none
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We are no longer supporting NSFW plugins so we won't be able to help you: https://github.com/streamlink/streamlink/issues/1997
