### ISSUE TITLE
url link to m3u8 , convert

### ISSUE THREAD

**Issue by faghiharff** [streamlink/streamlink#2266]
Dear friends,
I found a link of a channel for my smart TV, it needs to convert to m3u8 domain. 

> http://5.255.90.242:5000/play/a002
it's my url. How can I convert it to m3u8?

**Comment by bastimeyer** [comment]
You're looking for ffmpeg if you want to remux streams:
https://ffmpeg.org/ffmpeg-formats.html#hls-2
