### ISSUE TITLE
Canal group 

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2272]
[x ] This is a plugin issue and I have read the contribution guidelines.

### Description

I m trying to use the canal plugin, but I can't make it work

### Reproduction steps / Explicit stream URLs to test

well for example I just point out to the url of the stream I want

'/usr/local/bin/streamlink --loglevel debug "https://www.mycanal.fr/live/?epgId=513"
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.4.0-139-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 0.14.2+84.ga91e134
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
error: No plugin can handle URL: https://www.mycanal.fr/live/?epgId=513
'

**Comment by back-to** [comment]
DRM, not possible with streamlink 

Ref https://github.com/streamlink/streamlink/pull/1378

https://github.com/streamlink/streamlink/blob/fb6a00c86bbf752b578ea317cdede242a2b4e836/src/streamlink/plugins/canalplus.py#L8-L9
