### ISSUE TITLE
Add a CLI option to end the stream (or create a new output file) after the first output file has reached a certain size limit

### ISSUE THREAD

**Issue by omen23** [streamlink/streamlink#2273]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

When using `-o <output.ext>` you can limit stream duration by setting a specific time like `08:00:00 for 8 hrs with --hls-duration HH:MM:SS` - I would like to see a command line switch that ends the recording after a certain amount of data is written to the file. *(e.g.: 10GB)*
Would give finer control over filesize
### Expected / Actual behavior
E.g.: if you entered `--stream-maxsize 10GB` and `--stream-maxfiles 2` *(default would be 1)* the streamlink process would end writing to `<output.ext>` and create `<outfile2.ext>` from the stream when it has written 10GB to the first file.   

with `--hls-duration HH:MM:SS` I can only approximate the file size and as we all know livestreams are not CBR so it would be nice to have this option for people who want to record long streams split up in 5 or 10 GB parts for uploading to services that restrict filesize (without the need to reencode or split).

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This is outside the scope of Streamlink. You could write a wrapper script which polls the file to see how large the size is, then ends the Streamlink process and starts a new one.
