### ISSUE TITLE
TV8 not Work 

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#2275]
## Bug Report

 [ x] This is a bug report and I have read the contribution guidelines.

### Description

The livestream from the Homepage page will not play through Streamlink

### Expected / Actual behavior

Normally the image is transmitted via E2 this does not take place via E2 as well as Streamlink over Windows

About Firefox is all ok 

https://i.ibb.co/JzVRCL9/tv8.jpg

### Reproduction steps / Explicit stream URLs to test

1.https://www.tv8.com.tr/canli-yayin
### Log output

**Enigma2:**

[streamlinksrv][info] Python:        2.7.13                                    
[streamlinksrv][info] Streamlink:    0.14.2 / 27.10.2018                       
[streamlinksrv][debug] Options Parser: 0.1.7                                   
[streamlinksrv][info] Requests(2.13.0), Websocket(0.48.0)                      
                                                                                                                                                       
[streamlinksrv][info] Processing URL: http://www.tv8.com.tr/canli-yayin        
[streamlinksrv][debug] URL Args: []                                            
[streamlinksrv][info] Found matching plugin tv8 for URL http://www.tv8.com.tr/c
nli-yayin                                                                      
[utils.l10n][debug] Language code: en_GB                                       
[streamlinksrv][error] No playable streams found on this URL: http://www.tv8.co
.tr/canli-yayin                                                                
127.0.0.1 - - [27/Jan/2019 18:46:04] "GET /http://www.tv8.com.tr/canli-yayin HT
P/1.1" 200 -                                                                   
[streamlinksrv][info] Processing URL: http://www.tv8.com.tr/canli-yayin        
[streamlinksrv][debug] URL Args: []                                            
[streamlinksrv][info] Found matching plugin tv8 for URL http://www.tv8.com.tr/c
nli-yayin                                                                      
[utils.l10n][debug] Language code: en_GB                                       
[streamlinksrv][error] No playable streams found on this URL: http://www.tv8.co
.tr/canli-yayin                                                                
127.0.0.1 - - [27/Jan/2019 18:46:05] "GET /http://www.tv8.com.tr/canli-yayin HT
P/1.1" 200 -                                                                   
[utils.l10n][debug] Language code: en_GB                                       
[streamlinksrv][error] No playable streams found on this URL: http://www.tv8.co
.tr/canli-yayin                                                                
127.0.0.1 - - [27/Jan/2019 18:46:05] "GET /http://www.tv8.com.tr/canli-yayin HT
P/1.1" 200 -                                                                   

**Windows** 

PS C:\WINDOWS\system32> streamlink http://www.tv8.com.tr/canli-yayin:TV8 best
[cli][info] Found matching plugin tv8 for URL http://www.tv8.com.tr/canli-yayin:TV8
error: Unable to open URL: http://www.tv8.com.tr/canli-yayin:TV8 (404 Client Error: Not Found for url: https://www.tv8.com.tr/canli-yayin:TV8)
PS C:\WINDOWS\system32>

**Comment by beardypig** [comment]
`http://www.tv8.com.tr/canli-yayin` works fine for me, possible an issue with `streamlinksrv`.

`http://www.tv8.com.tr/canli-yayin:TV8` does not contain a stream, it gives a 404 error.

**Comment by back-to** [comment]
**without** Turkish IP
```
error: No playable streams found on this URL
```

**with** Turkish IP

```
$ streamlink https://www.tv8.com.tr/canli-yayin
[cli][debug] OS:         Linux
[cli][debug] Python:     3.6.7
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin tv8 for URL https://www.tv8.com.tr/canli-yayin
[cli][info] Available streams: 576p (worst), 864p (best)
[cli][info] Opening stream: 864p (hls)
```

---

you might be geo-blocked

**Comment by ahmedtds** [comment]
> 
> 
> **without** Turkish IP
> 
> ```
> error: No playable streams found on this URL
> ```
> 
> **with** Turkish IP
> 
> ```
> $ streamlink https://www.tv8.com.tr/canli-yayin
> [cli][debug] OS:         Linux
> [cli][debug] Python:     3.6.7
> [cli][debug] Streamlink: 1.0.0
> [cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
> [cli][info] Found matching plugin tv8 for URL https://www.tv8.com.tr/canli-yayin
> [cli][info] Available streams: 576p (worst), 864p (best)
> [cli][info] Opening stream: 864p (hls)
> ```
> 
> you might be geo-blocked

I have Turkish IP and I can watch it via browser but streamlink says "No playable streams found on this URL"

**Comment by beardypig** [comment]
@ahmedtds could you make a new issue for this?
