### ISSUE TITLE
Problem while upgrading

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2288]
this happens when I try upgrading streamlink 

pip install --upgrade streamlink 

Collecting streamlink
  Downloading https://files.pythonhosted.org/packages/65/c2/07da2836739da1b878ebe86a5a534bbb4548d149ef98d50d58963c497af8/streamlink-1.0.0-py2.py3-none-any.whl (369kB)
    100% |████████████████████████████████| 378kB 2.2MB/s
Collecting PySocks!=1.5.7,>=1.5.6 (from streamlink)
  Downloading https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 6.3MB/s
Requirement already up-to-date: isodate in /usr/local/lib/python2.7/dist-packages/isodate-0.6.0-py2.7.egg (from streamlink)
Collecting urllib3[secure]>=1.23; python_version < "3.0" (from streamlink)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 14.2MB/s
Collecting requests<3.0,>=2.21.0 (from streamlink)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 17.6MB/s
Collecting backports.shutil-which; python_version < "3.3" (from streamlink)
  Downloading https://files.pythonhosted.org/packages/3d/1b/136e8ffa98ce077e12afde6c333eb2b61266e0de0e404ec7a0c47b8f8a8b/backports.shutil_which-3.5.2-py2.py3-none-any.whl
Requirement already up-to-date: singledispatch; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from streamlink)
Collecting websocket-client (from streamlink)
  Downloading https://files.pythonhosted.org/packages/26/2d/f749a5c82f6192d77ed061a38e02001afcba55fe8477336d26a950ab17ce/websocket_client-0.54.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 9.1MB/s
Requirement already up-to-date: backports.shutil-get-terminal-size; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from streamlink)
Collecting futures; python_version < "3.0" (from streamlink)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Requirement already up-to-date: iso-639 in /usr/local/lib/python2.7/dist-packages (from streamlink)
Collecting iso3166 (from streamlink)
  Downloading https://files.pythonhosted.org/packages/f2/f6/985e5b174786e93aff77ec055a4b7ba55ebc95a3f8b5880f845d7bbd253e/iso3166-0.9.tar.gz
Collecting pycryptodome<4,>=3.4.3 (from streamlink)
  Downloading https://files.pythonhosted.org/packages/29/68/0ee43d649a2f748f805c427558e3ec8d832faa34ca1f369195b274266e1d/pycryptodome-3.7.3-cp27-cp27mu-manylinux1_x86_64.whl (7.5MB)
    100% |████████████████████████████████| 7.5MB 248kB/s
Collecting six (from isodate->streamlink)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.14; extra == "secure" (from urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 18.6MB/s
Collecting idna>=2.0.0; extra == "secure" (from urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 13.8MB/s
Collecting cryptography>=1.3.4; extra == "secure" (from urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/17/fd/4c2c8953a9dfe38fbe0c3adafb6355540bd98cef70cc82734acb0a4c0e2f/cryptography-2.5-cp27-cp27mu-manylinux1_x86_64.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 777kB/s
Collecting certifi; extra == "secure" (from urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 11.7MB/s
Collecting ipaddress; extra == "secure" (from urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests<3.0,>=2.21.0->streamlink)
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407kB)
    100% |████████████████████████████████| 409kB 3.3MB/s
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "secure"->urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 16.0MB/s
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "secure"->urllib3[secure]>=1.23; python_version < "3.0"->streamlink)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 11.6MB/s
Installing collected packages: PySocks, six, enum34, pycparser, cffi, asn1crypto, ipaddress, cryptography, pyOpenSSL, idna, certifi, urllib3, requests, backports.shutil-which, websocket-client, futures, iso3166, pycryptodome, streamlink
  Found existing installation: PySocks 1.6.7
    Uninstalling PySocks-1.6.7:
      Successfully uninstalled PySocks-1.6.7
  Running setup.py install for PySocks ... done
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Rolling back uninstall of six
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/dist-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 318, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 726, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2639, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2369, in parse_map
    for group, lines in data:
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2967, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1458, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1818, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1698, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1638, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/PySocks-1.6.7-py2.7.egg'
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/PySocks-1.6.7-py2.7.egg'

**Comment by gravyboat** [comment]
Did you fix this?

**Comment by campones** [comment]
well yea somehow, I donno i just run the same command again and it worked? , that's weird actually

**Comment by campones** [comment]
the script uninstall pysocks

"Uninstalling PySocks-1.6.7:
Successfully uninstalled PySocks-1.6.7"

then complain pysocks can't be found.

**Comment by gravyboat** [comment]
Hmm, well I'm glad it works at least. As far as I know this is a pip issue we've seen a few times before: https://github.com/streamlink/streamlink/issues/1240. You might need to upgrade pip via `pip install --upgrade pip`, but there was also a pip bug a while back so if you're on a very old version it might break your pip. If that happens check out https://stackoverflow.com/questions/49836676/error-after-upgrading-pip-cannot-import-name-main for some solutions.

**Comment by campones** [comment]
yes I also updated pip but I can't remember now if it was before running the command a second time , or after

**Comment by campones** [comment]
my pip was pretty old indeed
