### ISSUE TITLE
NPO livestream broken

### ISSUE THREAD

**Issue by WuvorWenda** [streamlink/streamlink#2289]
## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.

### Description

NPO livestream does not playanymore:
URL: https://www.npostart.nl/live/npo-1

### Expected / Actual behavior

Play stream 
404 not found

### Reproduction steps / Explicit stream URLs to test

1. goto https://www.npostart.nl/live/npo-1

### Log output

```
[12:28:28,231][cli][debug] OS:         Windows 7
[12:28:28,247][cli][debug] Python:     3.5.2
[12:28:28,247][cli][debug] Streamlink: 0+unknown
[12:28:28,247][cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[12:28:28,263][cli][info] Found matching plugin npo for URL https://www.npostart.nl/live/npo-1
[12:28:29,938][plugin.npo][debug] Found asset id: LI_NL1_4188102
error: Unable to open URL: https://livestreams.omroep.nl/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=702a9fd64db5b950e7e78287a73e48d8&token=7569d9b625acf839c40b1edd5836ad97&type=
json&protection=url (404 Client Error: Not Found for url: https://livestreams.omroep.nl/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=702a9fd64db5b950e7e78287a73e48d8&token=7569d9b
625acf839c40b1edd5836ad97&type=json&protection=url)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by WuvorWenda** [comment]
Is it possible to make a MPD parser to stream the DASH and decrypt the content?
MPD file:
--------
<?xml version="1.0" encoding="utf-8"?>

<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  xmlns:mspr="urn:microsoft:playready"
  xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
  type="dynamic"
  availabilityStartTime="1970-01-01T00:00:00Z"
  publishTime="2019-02-02T00:38:10.028944Z"
  minimumUpdatePeriod="PT2S"
  timeShiftBufferDepth="PT28.800S"
  maxSegmentDuration="PT2S"
  minBufferTime="PT10S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264">
  <Period
    id="1"
    start="PT0S">
    <BaseURL>dash/</BaseURL>
    <AdaptationSet
      group="1"
      contentType="audio"
      lang="nl"
      minBandwidth="128000"
      maxBandwidth="128000"
      segmentAlignment="true"
      audioSamplingRate="48000"
      mimeType="audio/mp4"
      codecs="mp4a.40.2">
      <AudioChannelConfiguration
        schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
        value="2">
      </AudioChannelConfiguration>
      
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="8D3C85FA-3073-0FDC-39EF-C09DE476415F">
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>AAACqnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAoqKAgAAAQABAIACPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAG8AVQA4AGoAWABNAHcAMwBBADgANQA3ADgAQwBkADUASABaAEIAWAB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AEwARwAvAEQAZQBYAGIAYwA1ADYARQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAHMAdAByAGUAYQBtAGcAYQB0AGUALgBuAGwALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>+oU8jXMw3A8578Cd5HZBXw==</mspr:kid>
<mspr:pro>igIAAAEAAQCAAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AKwBvAFUAOABqAFgATQB3ADMAQQA4ADUANwA4AEMAZAA1AEgAWgBCAFgAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBMAEcALwBEAGUAWABiAGMANQA2AEUAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcABsAGEAeQByAGUAYQBkAHkALgBzAHQAcgBlAGEAbQBnAGEAdABlAC4AbgBsAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQjTyF+jBzD9w578Cd5HZBXxoIdXNwLWNlbmMiGGpUeUYrakJ6RDl3NTc4Q2Q1SFpCWHc9PSoAMgA=</cenc:pssh>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:8d3c85fa30730fdc39efc09de476415f</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <SegmentTemplate
        timescale="48000"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="74355257009408" d="92160" r="14" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="audio_nld=128000"
        bandwidth="128000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      group="3"
      contentType="text"
      lang="nl"
      minBandwidth="64000"
      maxBandwidth="64000"
      mimeType="application/mp4"
      codecs="stpp">
      <Role
        schemeIdUri="urn:mpeg:dash:role:2011"
        value="caption">
      </Role>
      <SegmentTemplate
        timescale="1000"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="1549067854320" d="1920" r="15" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="tt888_nld=64000"
        bandwidth="64000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="200000"
      maxBandwidth="1800000"
      minWidth="384"
      maxWidth="1024"
      minHeight="216"
      maxHeight="576"
      segmentAlignment="true"
      frameRate="25"
      mimeType="video/mp4"
      startWithSAP="1">
      
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="8D3C85FA-3073-0FDC-39EF-C09DE476415F">
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>AAACqnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAoqKAgAAAQABAIACPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAG8AVQA4AGoAWABNAHcAMwBBADgANQA3ADgAQwBkADUASABaAEIAWAB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AEwARwAvAEQAZQBYAGIAYwA1ADYARQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAHMAdAByAGUAYQBtAGcAYQB0AGUALgBuAGwALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>+oU8jXMw3A8578Cd5HZBXw==</mspr:kid>
<mspr:pro>igIAAAEAAQCAAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AKwBvAFUAOABqAFgATQB3ADMAQQA4ADUANwA4AEMAZAA1AEgAWgBCAFgAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBMAEcALwBEAGUAWABiAGMANQA2AEUAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcABsAGEAeQByAGUAYQBkAHkALgBzAHQAcgBlAGEAbQBnAGEAdABlAC4AbgBsAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQjTyF+jBzD9w578Cd5HZBXxoIdXNwLWNlbmMiGGpUeUYrakJ6RDl3NTc4Q2Q1SFpCWHc9PSoAMgA=</cenc:pssh>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:8d3c85fa30730fdc39efc09de476415f</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <SegmentTemplate
        timescale="25"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="38726696358" d="48" r="15" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=200000"
        bandwidth="200000"
        width="384"
        height="216"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=499968"
        bandwidth="499968"
        width="480"
        height="270"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1000000"
        bandwidth="1000000"
        width="768"
        height="432"
        codecs="avc1.42C02A"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1800000"
        bandwidth="1800000"
        width="1024"
        height="576"
        codecs="avc1.42C033"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
--------

**Comment by WuvorWenda** [comment]
Is it possible to make a MPD parser and decrypt the DASH content?
`<?xml version="1.0" encoding="utf-8"?>

<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
  xmlns:cenc="urn:mpeg:cenc:2013"
  xmlns:mspr="urn:microsoft:playready"
  xmlns:mas="urn:marlin:mas:1-0:services:schemas:mpd"
  type="dynamic"
  availabilityStartTime="1970-01-01T00:00:00Z"
  publishTime="2019-02-02T00:38:10.028944Z"
  minimumUpdatePeriod="PT2S"
  timeShiftBufferDepth="PT28.800S"
  maxSegmentDuration="PT2S"
  minBufferTime="PT10S"
  profiles="urn:mpeg:dash:profile:isoff-live:2011,urn:com:dashif:dash264">
  <Period
    id="1"
    start="PT0S">
    <BaseURL>dash/</BaseURL>
    <AdaptationSet
      group="1"
      contentType="audio"
      lang="nl"
      minBandwidth="128000"
      maxBandwidth="128000"
      segmentAlignment="true"
      audioSamplingRate="48000"
      mimeType="audio/mp4"
      codecs="mp4a.40.2">
      <AudioChannelConfiguration
        schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
        value="2">
      </AudioChannelConfiguration>
      
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="8D3C85FA-3073-0FDC-39EF-C09DE476415F">
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>AAACqnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAoqKAgAAAQABAIACPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAG8AVQA4AGoAWABNAHcAMwBBADgANQA3ADgAQwBkADUASABaAEIAWAB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AEwARwAvAEQAZQBYAGIAYwA1ADYARQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAHMAdAByAGUAYQBtAGcAYQB0AGUALgBuAGwALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>+oU8jXMw3A8578Cd5HZBXw==</mspr:kid>
<mspr:pro>igIAAAEAAQCAAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AKwBvAFUAOABqAFgATQB3ADMAQQA4ADUANwA4AEMAZAA1AEgAWgBCAFgAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBMAEcALwBEAGUAWABiAGMANQA2AEUAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcABsAGEAeQByAGUAYQBkAHkALgBzAHQAcgBlAGEAbQBnAGEAdABlAC4AbgBsAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQjTyF+jBzD9w578Cd5HZBXxoIdXNwLWNlbmMiGGpUeUYrakJ6RDl3NTc4Q2Q1SFpCWHc9PSoAMgA=</cenc:pssh>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:8d3c85fa30730fdc39efc09de476415f</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <SegmentTemplate
        timescale="48000"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="74355257009408" d="92160" r="14" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="audio_nld=128000"
        bandwidth="128000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      group="3"
      contentType="text"
      lang="nl"
      minBandwidth="64000"
      maxBandwidth="64000"
      mimeType="application/mp4"
      codecs="stpp">
      <Role
        schemeIdUri="urn:mpeg:dash:role:2011"
        value="caption">
      </Role>
      <SegmentTemplate
        timescale="1000"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="1549067854320" d="1920" r="15" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="tt888_nld=64000"
        bandwidth="64000">
      </Representation>
    </AdaptationSet>
    <AdaptationSet
      group="2"
      contentType="video"
      par="16:9"
      minBandwidth="200000"
      maxBandwidth="1800000"
      minWidth="384"
      maxWidth="1024"
      minHeight="216"
      maxHeight="576"
      segmentAlignment="true"
      frameRate="25"
      mimeType="video/mp4"
      startWithSAP="1">
      
      <ContentProtection
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="8D3C85FA-3073-0FDC-39EF-C09DE476415F">
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
        <cenc:pssh>AAACqnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAAoqKAgAAAQABAIACPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgArAG8AVQA4AGoAWABNAHcAMwBBADgANQA3ADgAQwBkADUASABaAEIAWAB3AD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AEwARwAvAEQAZQBYAGIAYwA1ADYARQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBwAGwAYQB5AHIAZQBhAGQAeQAuAHMAdAByAGUAYQBtAGcAYQB0AGUALgBuAGwALwByAGkAZwBoAHQAcwBtAGEAbgBhAGcAZQByAC4AYQBzAG0AeAA8AC8ATABBAF8AVQBSAEwAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
<mspr:IsEncrypted>1</mspr:IsEncrypted>
<mspr:IV_Size>8</mspr:IV_Size>
<mspr:kid>+oU8jXMw3A8578Cd5HZBXw==</mspr:kid>
<mspr:pro>igIAAAEAAQCAAjwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADAALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsARQBZAEwARQBOAD4AMQA2ADwALwBLAEUAWQBMAEUATgA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwALwBQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAD4AKwBvAFUAOABqAFgATQB3ADMAQQA4ADUANwA4AEMAZAA1AEgAWgBCAFgAdwA9AD0APAAvAEsASQBEAD4APABDAEgARQBDAEsAUwBVAE0APgBMAEcALwBEAGUAWABiAGMANQA2AEUAPQA8AC8AQwBIAEUAQwBLAFMAVQBNAD4APABMAEEAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AcABsAGEAeQByAGUAYQBkAHkALgBzAHQAcgBlAGEAbQBnAGEAdABlAC4AbgBsAC8AcgBpAGcAaAB0AHMAbQBhAG4AYQBnAGUAcgAuAGEAcwBtAHgAPAAvAEwAQQBfAFUAUgBMAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=</mspr:pro>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
        <cenc:pssh>AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwIARIQjTyF+jBzD9w578Cd5HZBXxoIdXNwLWNlbmMiGGpUeUYrakJ6RDl3NTc4Q2Q1SFpCWHc9PSoAMgA=</cenc:pssh>
      </ContentProtection>
      
      <ContentProtection
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
<mas:MarlinContentIds>
  <mas:MarlinContentId>urn:marlin:kid:8d3c85fa30730fdc39efc09de476415f</mas:MarlinContentId>
</mas:MarlinContentIds>
      </ContentProtection>
      <SegmentTemplate
        timescale="25"
        initialization="npo-1-$RepresentationID$.dash"
        media="npo-1-$RepresentationID$-$Time$.dash">
        
        <SegmentTimeline>
          <S t="38726696358" d="48" r="15" />
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation
        id="video=200000"
        bandwidth="200000"
        width="384"
        height="216"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=499968"
        bandwidth="499968"
        width="480"
        height="270"
        codecs="avc1.42C01E"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1000000"
        bandwidth="1000000"
        width="768"
        height="432"
        codecs="avc1.42C02A"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1800000"
        bandwidth="1800000"
        width="1024"
        height="576"
        codecs="avc1.42C033"
        scanType="progressive">
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
`

**Comment by WuvorWenda** [comment]
Is it possible to decrypt the DASH content?
see attached mpd file
The key must be in the file.
[dash.zip](https://github.com/streamlink/streamlink/files/2823856/dash.zip)

**Comment by gravyboat** [comment]
@WuvorWenda Unfortunately anything with DRM we've decided not to work on. It's too big of a time investment with our small development team.

**Comment by WuvorWenda** [comment]
@gravyboat 
Please do not remove the plug-in, only the live-streams are affected.

**Comment by gravyboat** [comment]
@WuvorWenda Thanks for the heads up, I've removed the plugin label for now. It's still somewhat of a gray area regarding VOD only sites like this, but I don't see any reason at this time (unless there are other opinions) to remove it, we probably just won't fix it.

**Comment by WuvorWenda** [comment]
@gravyboat 
strange...
It works again...
streamlink https://www.npostart.nl/live/npo-1
[cli][info] Found matching plugin npo for URL https://www.npostart.nl/live/npo-1
[cli][info] Available streams: 136k (worst), 216p, 270p, 432p, 576p (best)
[cli][info] Opening stream: 576p (hls)
just tested it.
