### ISSUE TITLE
Chaturbate plugin removed...

### ISSUE THREAD

**Issue by dustycy** [streamlink/streamlink#2290]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.

### Description

It seems that the CB plugin has been removed in the latest stable release.

### Reproduction steps / Explicit stream URLs to test

1.  Streamlink emits a "No plugin can handle URL" error when you try to capture a model.
2. ...
3. ...

### Log output

```
D:\Downloads\streamLinkTest>streamlink.exe --loglevel debug https://chaturbate.com/lovemegentle/ best
[Streamlink for Windows v1.0.0 - Git f7ac894]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.0.0+f7ac894
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
error: No plugin can handle URL: https://chaturbate.com/lovemegentle/
[End of Streamlink for Windows with ExitCode 1]
```

### Additional comments, screenshots, etc.
I could capture CB streams by copying the chaturbate.py from previous stable release into the plugins directory. It seems the plugin has been removed in the latest stable relase.

D:\Downloads\streamLinkTest>streamlink.exe --loglevel debug https://chaturbate.com/lovemegentle/ best
[Streamlink for Windows v1.0.0 - Git f7ac894]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.0.0+f7ac894
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin chaturbate for URL https://chaturbate.com/lovemegentle/
[plugin.chaturbate][info] Stream status: public
[utils.l10n][debug] Language code: tr_TR
[cli][info] Available streams: 240p (worst), 480p, 720p_alt, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 5062; Last Sequence: 5064
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5062; End Sequence: None
[stream.hls][debug] Adding segment 5062 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 5063 to queue

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
We are no longer supporting NSFW sites, please see #2003 and https://github.com/streamlink/streamlink/pull/1838#issuecomment-459184294.
