### ISSUE TITLE
Named m3u8/hls output

### ISSUE THREAD

**Issue by SheinH** [streamlink/streamlink#2294]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I would like for a way to name the m3u8 file that gets passed when using `--player-passthrough=hls`. 

### Expected / Actual behavior

When using Quicktime Player with streamlink, the title gets set to the m3u8 file which is usually just a sequence of random characters. This is quite ugly. If the m3u8 file can be named, the title on quicktime can be set to whatever the user wants.

### Additional comments, screenshots, etc.

![3jdg7pz](https://user-images.githubusercontent.com/5853497/52168861-7a2f1c80-26fd-11e9-9a7f-3484731c862b.png)

![image](https://user-images.githubusercontent.com/5853497/52168866-8a46fc00-26fd-11e9-9272-1042aabfd13c.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
The player you're using needs to have command line parameters available for setting custom window titles. If it does, you can use the `--player-args`/`-a` or `--player`/`-p` Streamlink parameters to set custom player parameters.
https://streamlink.github.io/cli.html#player-options

In case of Quicktime Player, I don't think there are any.

An alternative for macOS users who want something similar could be IINA, which is based on MPV and may support setting custom window titles:
https://github.com/iina/iina
https://github.com/iina/iina/blob/v1.0.1/iina-cli/main.swift#L48-L70

**Comment by SheinH** [comment]
So is it currently impossible to change the name of the m3u8 that gets passed?

**Comment by bastimeyer** [comment]
No, quicktime player doesn't support this.

**Comment by SheinH** [comment]
I'm asking if it's possible to name the m3u8 file that gets outputted to {filename}. I believe this is handled by streamlink and not quicktime; am i wrong?

**Comment by bastimeyer** [comment]
> name the m3u8 file that gets outputted to {filename}

The `{filename}` variable is just a placeholder for the input URL that gets set by Streamlink. This can be an external HLS URL when using the passthrough=hls method, a local HTTP server address when using the `--player-http` option, or a `-` when using the default `stdin` stream transport method.

> Is it quicktime that's deciding to name the file to be gibberish?

Quicktime player will set its window title from the input, which means there is nothing you can do (unless there is some other IPC/scripting way). The "gibberish" is just the HLS URL format from the streaming provider.

**Comment by SheinH** [comment]
Ah, I understand, thank you so much for enlightening me. That makes sense.

So then a script for curling the URL, renaming it, and then opening it with quicktime would serve my purposes, correct?

**Comment by bastimeyer** [comment]
I'm not sure, this depends on the HLS master playlist and whether other requests are relative to the input. You might need to write an entire HLS proxy server for that (which Streamlink is kinda looking for) just to change the window title of the quicktime player.
