### ISSUE TITLE
Add Quicktime configuration guide to the wiki

### ISSUE THREAD

**Issue by SheinH** [streamlink/streamlink#2295]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

The wiki currently states that quicktime does not work but I've gotten it to work using this `.streamlinkrc`:

```
player=/usr/bin/open
player-args=-W -n -a 'Quicktime Player' {filename}
player-passthrough=hls
```

Works by passing the hls stream as an m3u8 file and then using 'open' on the file with the application parameter set to Quicktime. I think this would be useful info for the wiki.

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/5853497/52169082-a8622b80-2700-11e9-8464-e3945377870b.png)
![image](https://user-images.githubusercontent.com/5853497/52169048-2a9e2000-2700-11e9-81d3-df9441db8bc3.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Similar to this question:
https://github.com/streamlink/streamlink-twitch-gui/issues/511

> player-passthrough=hls

By using the `player-passthrough=hls` parameter, you are bypassing Streamlink and instead **passing through** the HLS stream URL to the player and using it as its first launch parameter. This means that the Player will do all the downloading and buffering on its own. Streamlink won't do anything and will just wait until the player gets closed. It's the same as running this:
```bash
# launching the player executable directly
/path/to/player "$(streamlink --stream-url URL QUALITY)"
# or macOS specific app launcher
open --wait-apps --new -a "Some Player.app" --args "$(streamlink --stream-url URL QUALITY)"
```

Quicktime Player doesn't support reading from `stdin`, which makes it useless in combination with Streamlink (the regular way).

**Comment by gravyboat** [comment]
@bastimeyer has been kind enough to explain why Quicktime doesn't support Streamlink so I'm going to close this as there isn't anything for us to document in relation to Streamlink itself.
