### ISSUE TITLE
Youtube plugin: No playable streams found on this URL

### ISSUE THREAD

**Issue by xolodno** [streamlink/streamlink#2296]
15-20 days ago everything worked just fine but now, when I try to watch/download live streams I see only this:
C:\Users\xolodno>streamlink --hls-live-restart https://www.youtube.com/watch?v=DSGyEsJ17cI best -o "F:\Strim\testt.mp4"
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=DSGyEsJ17cI
error: No playable streams found on this URL: https://www.youtube.com/watch?v=DSGyEsJ17cI

I updated streamlink to the last version 1.0. (.exe) - still the same
Cloned and installed from [https://github.com/streamlink/streamlink](https://github.com/streamlink/streamlink) - same error
Tried to modify youtube.py somehow, nothing helped...

I need your help, upload for me your youtube.py, don't know how to fix.

**Comment by back-to** [comment]
> I updated streamlink to the last version 1.0. (.exe) - still the same

you are probably not on 1.0.0, try `streamlink -l debug` and `streamlink --version`

**Comment by gravyboat** [comment]
I can't duplicate this on 1.0.0. Try what @back-to has suggested, seems like you're still on an old version.

**Comment by xolodno** [comment]
Wow yes, command `streamlink -l debug` still shows me streamlink version 0.14.2 (installed/uninstalled 1.0. version few times but seems like all that time in command line it used 014.2, why?!)
But I uninstalled streamlink with standart win10 "Apps & features"
Then manually deleted folders: 
C:\Program Files (x86)\Streamlink
C:\UserNames\UserName\AppData\Roaming\streamlink
Deleted everything about "streamlink" in regedit,
and I can still use it in command line
How to fully uninstall 0.14.2 ?
![2019-02-03_12-40-55](https://user-images.githubusercontent.com/47280793/52175171-051d1f00-27b1-11e9-8747-16b1bd380e14.png)

**Comment by back-to** [comment]
```
Then manually deleted folders:
C:\Program Files (x86)\Streamlink
C:\UserNames\UserName\AppData\Roaming\streamlink
Deleted everything about "streamlink" in regedit,
```

use the **uninstall.exe** instead of deleting stuff

there are two streamlink versions installed on your system
one as admin _(C:\Program Files (x86)\Streamlink)_
and one as user _(C:\UserNames\UserName\AppData\Roaming\streamlink)_

if you don't have an `uninstall.exe` just reinstall streamlink as a current user or admin
and run the uninstall

here are some similar issues

https://github.com/streamlink/streamlink/issues/1391#issuecomment-354275115
https://github.com/streamlink/streamlink/issues/1340

**Comment by xolodno** [comment]
ooooooh, finally I found it, will try to explain (sorry for my broken english)
I installed 0.14.2 then uninstalled it with uninstall.exe - I was still able to use streamlink in command line :)
I realized that something is f*cked up and streamlink 014.2. for sure still installed somewhere on my HDD..
Before I will show you how I found it, I can say that streamlink (any version) was NOT in win10 "Apps & features" or when I used any other programms like CCleaner (that's why I thought that I uninstalled it already, seems like a bug)
I forgot that long time ago I installed streamlink in some random directory
So there is the solution:
Streamlink add a directory to the User Path Variable from the Command Line, and if you will open all paths your command line uses - you will find where is your streamlink :)
Here is how to do it on english [http://johnatten.com/2014/12/07/adding-and-editing-path-environment-variables-in-windows/](http://johnatten.com/2014/12/07/adding-and-editing-path-environment-variables-in-windows/)
And I also screened it on my computer:
![streamlink_uninstall](https://user-images.githubusercontent.com/47280793/52229607-6256c480-28c6-11e9-8e46-1888e4a8c1e5.jpg)

**Comment by xolodno** [comment]
Thank you guys, problem solved 
![2019-02-04_21-52-35](https://user-images.githubusercontent.com/47280793/52229987-4f90bf80-28c7-11e9-95bc-33b641ae5e16.png)
