### ISSUE TITLE
Avast and AVG flagged streamlink-1.0.0.exe as infected by Win32:MdeClass

### ISSUE THREAD

**Issue by ciapistess** [streamlink/streamlink#2298]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.

### Description

Avast and AVG flagged streamlink-1.0.0.exe (Windows) as infected by Win32:MdeClass

This is also reported by virustotal.com: 
https://www.virustotal.com/#/file/af6b201638deb7dbf97b4a8bbc0cf951baa3a9e21f12612b0511d9b3a0aab8f0/detection

### Expected / Actual behavior

streamlink-1.0.0.exe should run, but is instead blocked by AVG antivirus

### Reproduction steps / Explicit stream URLs to test

1. prerequisite: installed AVG antivirus  
2. download https://github.com/streamlink/streamlink/releases/download/1.0.0/streamlink-1.0.0.exe
3. execute it - ACG will block execution claiming an infection by Win32:MdeClass

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
There's nothing which can be done here. Report it as a false positive.

It's a regular [NSIS](https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System) installer built with the help of [pynsist](https://github.com/takluyver/pynsist/):
https://github.com/streamlink/streamlink/blob/1.0.0/script/makeinstaller.sh
If you want to see the build logs, go here
https://travis-ci.org/streamlink/streamlink/jobs/486649914
