### ISSUE TITLE
Missing executable after install

### ISSUE THREAD

**Issue by mironmizrahi** [streamlink/streamlink#2299]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

There does not seem to be an executable to run after running the 1.0.0 installation.

### Expected / Actual behavior

I downloaded the install package from https://github.com/streamlink/streamlink/releases/download/1.0.0/streamlink-1.0.0.exe and ran the install. I was expecting an executable to exist under the streamlink program directory but there isn't one. So unless I got something very basic wrong, I cannot run it. Simply typing 'streamlink' in a CMD window results in "'streamlink' is not recognized as an internal or external command operable program or batch file.".

I tried looking for any info on how to run it, in case Windows is different to Linux but could not see any

### Reproduction steps / Explicit stream URLs to test

1. download install package
2. run install

### Logs

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> I was expecting an executable to exist under the streamlink program directory but there isn't one.

try `"C:\Program Files (x86)\Streamlink\bin\streamlink.exe" --version`

>  Simply typing 'streamlink' in a CMD window results in "'streamlink' is not recognized as an internal or external command operable program or batch file.".

- is this the first streamlink version on your pc or did you run some other versions before ?
- did you try to uninstall und install again?

**Comment by mironmizrahi** [comment]
> try `"C:\Program Files (x86)\Streamlink\bin\streamlink.exe" --version`
> 
precisely my point. there is no streamlink.exe anywhere under C:\Program Files (x86)\Streamlink. I just installed it again and checked the list of files listed in the install progress window and it is not listed. I also extracted the archive using 7-zip and it is not there. I can only surmise it has not been packaged.

>     * is this the first streamlink version on your pc or did you run some other versions before ?
first. I removed and tried an earlier version, removed and tried 1.0.0 again ... same result

> 
>     * did you try to uninstall und install again?

yes

**Comment by bastimeyer** [comment]
> there is no streamlink.exe anywhere under C:\Program Files (x86)\Streamlink

`C:\Program Files (x86)\Streamlink\bin\streamlink.exe`

or if you've installed Streamlink for the system's current user instead:

`%LOCALAPPDATA%\Streamlink\bin\streamlink.exe`

> it has not been packaged.

Maybe you're having some kind of software running in the background which prevents the installer from writing the exe file, eg. an antivius software, which is not unusual on Windows.

If the file was indeed missing, you'd probably not be the only one reporting this. The installer is working fine in my Windows VMs and it properly generates the `streamlink.exe` executable.
