### ISSUE TITLE
log-level not as helpful as livestreamers one

### ISSUE THREAD

**Issue by jwallet** [streamlink/streamlink#2303]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] This may also be a discussion more than a bug report.

### Description

I'm coding my own `--http-proxy` `--https-proxy` to use with streamlink and hls streams. I had my media players closing before the stream ends, live stream or archived, it was having trouble getting the playlist back (or more likely a new one from the proxy) I though for some times that the issue came from `VLC` but it was the proxy.

Streamlink, even with `--debug-level=trace` or `--debug-level=debug` did not have much to say
```
Error when reading from stream : Read timeout, exiting
stream ended
```
...and sometimes it added `worker stopped`

So, I decided to use Livestreamer in debug mode to see if any error will come up, and it did. 

So I'm wondering when does Streamlink actually removed that kind of log info that helped me found that __my proxy was not handling websockets at all__. 

Livestreamer logged many warning about
```
cannot connect to proxy.
socket error: [errno 10054] an existing connection was forcibly closed by the remote host
```
```
[stream.hls][debug] adding segment 1440 to queue
[stream.hls][error] failed to create decryptor: unable to open url: 
https://domain.com/ws/media/mf/v1.1/key/silk/mediaid/1234567890/kid/9876543210
cannot connect to proxy.
socket error: [errno 10053] an established connection was aborted by the software in your host machine.
[stream.hls][debug] closing writer thread
```

I'm not asking Streamlink to catch and report what my proxy did not implemented correctly, but I just want to let you know that the project used to report these kind of info that were helpful for me

### Expected / Actual behavior

To get more helpful logs when in debug/trace mode. Not just helpful for me, but also for other that may use a proxy that is incompatible with streaming files. 
Throwing and logging as many exceptions as possible when they occur.

### Reproduction steps / Explicit stream URLs to test

Use streamlink with an undone/incompatible proxy

**Comment by back-to** [comment]
the error output seems unrelated to each other

---

> Error when reading from stream : Read timeout, exiting stream ended

**this is just a misconfiguration on your side**

https://github.com/NHLGames/NHLGames/blob/782b4f452294c83ef8df68d5f51f228557d7192e/NHLGames/Objects/GameWatchArguments.vb#L29-L31

---

>  {"--hls-segment-threads", "4"},

depends on the length of the segments, but this seems already to high if used with livestreams

`1` should be fine or maybe `2`

https://streamlink.github.io/cli.html#cmdoption-hls-segment-threads

---

this is the timeout command

https://streamlink.github.io/cli.html#cmdoption-hls-timeout
`--hls-timeout` _Default is: 60.0._

with your settings

`--hls-segment-timeout` is the same length in your config, so if a segment fails streamlink will close

> {"--hls-segment-attempts", "30"}, {"--hls-segment-timeout", "60"}}

if one segment lags, the stream will timeout for you

30 x 60s = 1800s

but streamlink closes after 60s, so this is imposible

---

just rethink your configuration

**Comment by jwallet** [comment]
when debugging the app I removed those settings to see what happened with default values, and the stream closes after 10 seconds. also if I disconnect from the Internet streamlink already stop and no request if sent to the proxy, but if I don't use the proxy it's fine. Still wondering if the proxy does not timeout/is in a deadlock or streamlink stopped trying to reload

**Comment by jwallet** [comment]
it does work using the proxy and the env var http_proxy with mpv but when i use vlc if i disconnect from the internet vlc or streamlink won't be able to connect back to the opened stream, even if i see requests and responses from the proxy, it just waits for the timeout 180 to end before closing. without the proxy it works, so like the issue says, 

it will be nice to get more logs from streamlink, even with the verbose flag for the player vlc does not log anything useful

**Comment by back-to** [comment]
as said the main difference between the log output is an outdated requests version of livestreamer.

Streamlink doesn't really do anything with the proxy ip,
it is handled by the **requests** python package.
