### ISSUE TITLE
sort streams by title and play if keyword is in title?

### ISSUE THREAD

**Issue by Maddensplayers** [streamlink/streamlink#2305]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

 I would like to be able to search multiple twitch streamers but only pull down the stream with a certain keyword. for example if stream A was streaming and the title had the word Cool is it, i would want to search to look in his stream title and if the word Cool is in it then produce the stream, but if the word Cool is not in it, do not produce it. 

### Expected / Actual behavior

 I have not found documentation that does this yet. 

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Any kind of logic regarding which stream you want to watch from any kind of source has to be built/implemented by yourself around Streamlink, eg. in a python or shell wrapper script or application which executes Streamlink. This is out of scope of the project.

In case of Twitch, see their developer documentation:
https://dev.twitch.tv/docs/
