### ISSUE TITLE
How record from Telerium.TV?

### ISSUE THREAD

**Issue by SafarVid** [streamlink/streamlink#2306]
How record from Telerium.TV? For example, http://www.fulltelevisionhd.li/directv-sports-en-vivo-por-internet/ or any channel on this page. Thank you in advance!

**Comment by bastimeyer** [comment]
That's an illegal streaming site with an entire catalog of stolen streams.
And this here is also a very low effort thread.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md
