### ISSUE TITLE
open stream if {title} had "keyword" 

### ISSUE THREAD

**Issue by Maddensplayers** [streamlink/streamlink#2309]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

 I want to be able to pull up a certain stream ONLY if it have a keyword in the {title} of the stream / if not i want it to be ignored.  If this is in there how do i implement this as the current feature only sorts quality. I want it to see the stream title and if my keyword is in the stream title then play otherwise do not play. 

### Expected / Actual behavior

Pull Stream from Stream link
see {title}
if Title has keyword Play
if not ignore. 

I end up loading the correct stream but I only want it displayed if it has my keyword. I want to use this for when I do my league streams, there are 30 streams and I want it to notify me via the keyword when they stream a game in MY league. 

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
As I've already told you in the other thread, any kind of custom logic around which stream you want to watch and which not, like for example filtering for specific stream titles (which btw is plugin-specific stuff and doesn't make any sense in a global context), is none of Streamlink's business.

You need to write your own wrapper script/application (pseudo code):

```pseudo
channels = [a list of various channel names from a specific streaming site]
keyword = "foo"

data = query_streams_data_from_site_API( channels )
for stream in data.streams
  if ( stream.title contains keyword )
    match = stream.url
    break

if ( match )
  launch_streamlink( stream.url )
else
  show_error( "No matching streams" )
```

> as the current feature only sorts quality

These are qualities from the single input stream. There is no support for multiple inputs in Streamlink.
