### ISSUE TITLE
Streamlink removed itself

### ISSUE THREAD

**Issue by makedir** [streamlink/streamlink#2311]
I wasnt using Streamlink for the past 10 days or so, last time maybe 30.1.2019 and today I noticed the folder under programs (x86) was gone... how is this possible? I totally not removed it by myself.

**Comment by Erk-** [comment]
Are you using avast or avg antivirus? it currently gives a false positive for streamlink

**Comment by makedir** [comment]
No I am not, I was using Windows Defender and Bitdefender during the past 2 weeks. But then wouldnt just the exe file missing and not the entire folder? It seems it was removed or de-installed by Windows.

**Comment by bastimeyer** [comment]
There is no way for Streamlink to remove its files from the file system on its own, unless you've executed the uninstaller. This is either an unintentional user error or an issue with 3rd party software on your Windows machine. Make sure that your system is working properly. We can't help you with that, especially not with such a vague description.

Also please note that there are two different installation methods:
- **all users** (default), where it writes the files into `%PROGRAMFILES(X86)%` / `%PROGRAMFILES%`
- **current user**, where it writes the files into `%LOCALAPPDATA%`

**Comment by makedir** [comment]
But I promise... I didnt uninstall it by myself. No one else has access to the computer. It was installed like I said for all users in the programs (x86) folder, for over 1 year. I have a Windows shortcut using Streamlinkg and saving flv files on my desktop and I wanted to use it just the other day... and POOF. Error, looked into the folder, and Streamlink folder was gone, the entire folder. Where it was still there ~10 days ago.

The only possibilites I see are:
- antivirus deleted the folder (very unlikey, just the EXE would missing then)
- MS installer confused (somehow, is this even possible) the wrong installation and removed Streamlink, wanted to remove something else

I actually tried to looked in Windows logs for Uninstallation events Event ID of 11724 or 1034, and there were none in the past 14 days.

**Comment by beardypig** [comment]
The only code to remove streamlink is in the uninstaller, if the uninstaller was not run then it must have been deleted manually. I think (but I don't remember for sure) that the installer creates some shortcuts for the uninstall and docs in the Start Menu, are they still there?
