### ISSUE TITLE
Is there a way for this one ?

### ISSUE THREAD

**Issue by Ordval** [streamlink/streamlink#2314]
- [x] This is not a bug report or feature request.
- [x] Perhaps a plugin issue.
- [x] I have read the contribution guidelines.

Is there a possibility to play this through Streamlink ? :

`http://163.172.89.151:1234/live/1/2/1112.m3u8`

I'm suspecting the MRL to be a generator of temporary streams for a certain channel. 

I've found it, and others like it, through the APK e-Doctor with URL Snooper.

For anyone willing to help me, can you find what you need from this ?  : 
```
http://certs.godaddy.com/repository/1301
http://crl.godaddy.com/gdig2s1-837.crl0]
http://certificates.godaddy.com/repository/0
http://ocsp.godaddy.com/0@
http://certificates.godaddy.com/repository/gdig2.crt0
http://ocsp.godaddy.com/05
http://crl.godaddy.com/gdroot-g2.crl0F
https://certs.godaddy.com/repository/0
http://ocsp.godaddy.com/02
http://crl.godaddy.com/gdroot.crl0F
http://apien.ldmnq.com/statisticsMnqEvent?sv=03390000&openid=100&m=5-5eaf45cbb67982653b22932d41bada75&event_key=co.wuffy.player&event_value=active&event_type=app&z=1549593864
https://secure.comodo.com/CPS0
Chttp://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl0
Chttp://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt0$
http://ocsp.comodoca.com01
http://crl.usertrust.com/AddTrustExternalCARoot.crl05
http://ocsp.usertrust.com0
http://crl.comodoca.com/COMODORSACertificationAuthority.crl0q
http://crt.comodoca.com/COMODORSAAddTrustCA.crt0$
http://ocsp.comodoca.com0
http://crl3.digicert.com/ssca-sha2-g6.crl0
http://crl4.digicert.com/ssca-sha2-g6.crl0L
https://www.digicert.com/CPS0
http://ocsp.digicert.com0F
http://cacerts.digicert.com/DigiCertSHA2SecureServerCA.crt0
http://www.digicert.com1
http://ocsp.digicert.com0{
http://crl3.digicert.com/DigiCertGlobalRootCA.crl07
http://crl4.digicert.com/DigiCertGlobalRootCA.crl0=
http://163.172.89.151:1234/live/1/2/1112.m3u8
http://localhost
http://certs.starfieldtech.com/repository/1402
http://crl.starfieldtech.com/sfig2s1-79.crl0c
http://certificates.starfieldtech.com/repository/0
http://ocsp.starfieldtech.com/0F
http://certificates.starfieldtech.com/repository/sfig2.crt0
http://ocsp.starfieldtech.com/0;
http://crl.starfieldtech.com/sfroot-g2.crl0L
https://certs.starfieldtech.com/repository/0
http://iptvreseller.xyz:1234/token.php
http://pki.goog/gsr2/GTSGIAG3.crt0)
http://ocsp.pki.goog/GTSGIAG30
http://crl.pki.goog/GTSGIAG3.crl0
http://ocsp.pki.goog/gsr202
http://crl.pki.goog/gsr2/gsr2.crl0?
https://pki.goog/repository/0
http://163.172.89.151:1234/live/iptvrestream.net/wC5Qtu9Zbl/1112.m3u8
http://163.172.89.151:1234/hls/iptvrestream.net/wC5Qtu9Zbl/1112/e08a82cc77e11835f829a7d056868dd5/1112_0.ts
http://163.172.89.151:1234/hls/iptvrestream.net/wC5Qtu9Zbl/1112/1d6da607ac7497eaa1d70b31e8dd6bfa/1112_1.ts
http://www.goo.gl
```
`--http-header User-Agent=android` don't work. 
`--player-passthrough hls --player-continuous- --retry-streams 1 --retry-open 86400`
makes no difference. 
I suspect it not to be Geo-restricted, there's no mentioning of it anyway on the APK itself,
and of course it opens through my LDPlayer (APK emulator), but plays poorly there,
like anything else (on any of/ from the different APK's). 

If this is another loopy one I can't say but at least they're stable (consistent).
The Wuffy player seems to be restricted only for Mobile phones.

I'm on Windows 10.

**Comment by beardypig** [comment]
I would imagine you'd need some kind of authorization token in a header, cookie or url parameter, to go along with the URL.

**Comment by Ordval** [comment]
That is what I'm supposing.  
Would this be possible to put `http://iptvreseller.xyz:1234/token.php`  in somehow  ? 
(Quoted from the code above).
The examples on the [Command-Line Interface](https://streamlink.github.io/cli.html) page seem to refer to already known token(-s).

**Comment by beardypig** [comment]
@Ordval seems like that is the URL that generates the token. However, you cannot tell how the token is meant to be sent from this list alone. If you wanna email me the apk I can take a look. Solve this "puzzle" to get my email address:
<github username> <at> protonmail <dot> com

**Comment by Ordval** [comment]
**beardypig** has looked into what I asked for, 
unfortunately the long lasting streams have stopped working.
I'm letting this stay open for a while to see if they resume.
