### ISSUE TITLE
Can't watch sponsored streams - Example: Crunchyroll Anime Awards

### ISSUE THREAD

**Issue by ZMOT7S** [streamlink/streamlink#2316]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
I try to watch the Crunchyroll twitch stream using Streamlink Twitch GUI but it doesn't play. I receive the following error.

`Unable to open URL: https://usher.ttvnw.net/api/channel/hls/crunchyroll.m3u8?player=twitchweb&p=471099&type=any&allow_source=true&allow_audio_only=true&allow_spectre=false&sig=4f56f50be640af765f3de0cd2a2d5b4066b04abf&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22crunchyroll%22%2C%22channel_id%22%3A90912711%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Atrue%2C%22geoblock_reason%22%3A%22anonymizer_blocked%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1550106720%2C%22game%22%3A%22Crunchyroll+Anime+Awards%22%2C%22hide_ads%22%3Atrue%2C%22https_required%22%3Afalse%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3Anull%2C%22player_type%22%3Anull%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22server_ads%22%3Afalse%2C%22show_ads%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Atrue%2C%22user_id%22%3A25113776%2C%22user_ip%22%3A%22192.64.24.117%22%2C%22version%22%3A2%7D&fast_bread=True (403 Client Error: ERROR for url: https://usher.ttvnw.net/api/channel/hls/crunchyroll.m3u8?player=twitchweb&p=471099&type=any&allow_source=true&allow_audio_only=true&allow_spectre=false&sig=4f56f50be640af765f3de0cd2a2d5b4066b04abf&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22crunchyroll%22%2C%22channel_id%22%3A90912711%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Atrue%2C%22geoblock_reason%22%3A%22anonymizer_blocked%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1550106720%2C%22game%22%3A%22Crunchyroll+Anime+Awards%22%2C%22hide_ads%22%3Atrue%2C%22https_required%22%3Afalse%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3Anull%2C%22player_type%22%3Anull%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22server_ads%22%3Afalse%2C%22show_ads%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Atrue%2C%22user_id%22%3A25113776%2C%22user_ip%22%3A%22192.64.24.117%22%2C%22version%22%3A2%7D&fast_bread=True)`

### Expected / Actual behavior
I expect the video to play

### Reproduction steps / Explicit stream URLs to test
Try to play https://www.twitch.tv/crunchyroll in VLC with Streamlink and/or Streamlink Twitch GUI

### Log output
I did the command but I don't know where the log file is located...

**Comment by gravyboat** [comment]
You're being geoblocked (and it also notes an anonymizer), it says so right in the log output and there's nothing we can do about that. I also can't duplicate.
