### ISSUE TITLE
How to set my default player such as potplayer?

### ISSUE THREAD

**Issue by IRISlMaple** [streamlink/streamlink#232]
I'm confused~~
Please advise.
Thank you~~~

**Comment by IRISlMaple** [comment]
I got it~!
Thank you~~!

**Comment by Junior1544** [comment]
@IRISlMaple 
When you post a thing like this and fix it yourself, it's always nice to include the fix you did so that when the next person has the same issue they search and they can see your fix instead of posting the same thing again :)

Glad you got it fixed!

**Comment by stevek123** [comment]
The answer is: https://streamlink.github.io/cli.html#configuration-file

**Comment by Junior1544** [comment]
Wonderful!  Thanks!  I'm going to look to see if this'll be a benefit to me :D
