### ISSUE TITLE
drdk plugin is not working anymore

### ISSUE THREAD

**Issue by nedkellddv** [streamlink/streamlink#2323]
## Plugin Issue

- [drdk.py ] This is a plugin issue and I have read the contribution guidelines.

### Description

When I try to use streamlink for VOD, I get an error message, as if the webpage source has changed

### Reproduction steps / Explicit stream URLs to test

1. ...copy any VOD url like https://www.dr.dk/tv/se/xxxxxx 
2. ...in a terminal use streamlink with the url
3. ... error message

The output I get in the terminal is
```
error: Unable to validate JSON: Unable to validate key 'Data': Unable to validate key 'Assets': Unable to validate key 'Links': Unable to validate key 'Uri': Type of None should be 'str' but is 'NoneType'

```

**Comment by back-to** [comment]
> Unable to validate key 'Data':

your version is outdated

`streamlink --version`

https://streamlink.github.io/latest/install.html

**Comment by nedkellddv** [comment]
I am sorry I do not believe I have an outdated version `streamlink --version` say 0.14.2

**Comment by beardypig** [comment]
Latest version is currently `1.0.0` (https://github.com/streamlink/streamlink/releases)

**Comment by nedkellddv** [comment]
You're right now installed version 1.0.0 but still get this error

 `error: Unable to validate JSON: Unable to validate key 'Data': Unable to validate key 'Assets': Unable to validate key 'Links': Unable to validate key 'Uri': Type of None should be 'basestring' but is 'NoneType'`

**Comment by bastimeyer** [comment]
> now installed version 1.0.0

what is the output of
```
streamlink --version
```

**Comment by nedkellddv** [comment]
`streamlink 1.0.0`

**Comment by back-to** [comment]
@nedkellddv 

it is just a misunderstanding,
because your first post doesn't have enough details

you are talking about a VOD not a Livestream

**Live**

```
$ streamlink -l debug https://www.dr.dk/tv/live/dr1 best
[cli][debug] OS:         Linux
[cli][debug] Python:     3.6.7
[cli][debug] Streamlink: 1.0.0+21.g34abc43
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin drdk for URL https://www.dr.dk/tv/live/dr1
[cli][info] Available streams: 364k (worst), 400k, 270p, 928k, 360p, 1020k, 432p, 1228k, 1350k, 576p, 1827k, 2010k, 720p, 3128k, 3440k (best)
[cli][info] Opening stream: 3440k (hls)
```

**VOD**

```
$ streamlink -l debug https://www.dr.dk/tv/se/integration/ali-og-hans-broedre/dr1-dokumentar-ali-og-hans-broedre best
[cli][debug] OS:         Linux
[cli][debug] Python:     3.6.7
[cli][debug] Streamlink: 1.0.0+21.g34abc43
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin drdk for URL https://www.dr.dk/tv/se/integration/ali-og-hans-broedre/dr1-dokumentar-ali-og-hans-broedre
error: Unable to validate JSON: Unable to validate key 'Data':
Unable to validate key 'Assets':
Unable to validate key 'Links':
Unable to validate key 'Uri': Type of None should be 'str' but is 'NoneType'
```

**Comment by nedkellddv** [comment]
I am sorry, a nob at posting bug reports

**Comment by mkbloke** [comment]
Thanks for merging, @back-to.  I see you have added the ```wontfix``` label to this issue.  If I do eventually get around to successfully adding VOD support back for this plugin, is that code likely to be merged?  Cheers.
