### ISSUE TITLE
How to stream Crunchyroll to VLC first time using streamlink

### ISSUE THREAD

**Issue by xZangetsuxX** [streamlink/streamlink#2329]
hello i need help how can i stream crunchyroll to vlc ? 
because the webplayer is really bad and lagging for me.
i tried to type in command prompt streamlink https://www.crunchyroll.com/de/xxxx/xxxx
but its not working i get this error: no plugin can handle this URL.
what do i have to do now ? pls help thanks

**Comment by skulblakka** [comment]
Please follow the template for Plugin Issues. Especially the output when running streamlink with ```-l debug```

**Comment by xZangetsuxX** [comment]
now it works but why can i fast forward? pls help

**Comment by beardypig** [comment]
@xZangetsuxX fast-forward is not supported by Streamlink.
