### ISSUE TITLE
Caffeine.TV

### ISSUE THREAD

**Issue by besweeet** [streamlink/streamlink#2335]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Caffeine.TV is a new, first-party streaming site. I know that it doesn't use HLS nor DASH but perhaps RTMP as discovered in a few files, namely the "FoxSports" ones that show up in Chrome.

### Example stream URLs

1. https://www.caffeine.tv/foxsports

### Additional comments, screenshots, etc.

This site might be geoblocked for people outside of the U.S., so a VPN may be needed.

**Comment by gravyboat** [comment]
It's not publicly available as it's in pre-release so we don't know how the site may change in the coming months. I'm going to close this one for now. When they go public we can see about adding them.
