### ISSUE TITLE
[MITELE] Movies

### ISSUE THREAD

**Issue by An0nima** [streamlink/streamlink#2336]
```
streamlink https://www.mitele.es/peliculas/ocho-apellidos-vascos/57ab5b33c915da951a8b46af/player best -l debug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.0.0+29.gacdefee
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
error: No plugin can handle URL: https://www.mitele.es/peliculas/ocho-apellidos-vascos/57ab5b33c915da951a8b46af/player
```

**Comment by An0nima** [comment]
Don't require account to know the mpd link ;) , youtube-dl tells you the mpd link in some movies, in others you get token error,  try this command...

`youtube-dl -g https://www.mitele.es/peliculas/un-monstruo-viene-a-verme/587e176dc915da8c908b458f/player`

**Comment by An0nima** [comment]
@bastimeyer 

Don't require account to know the mpd link ;) , youtube-dl tells you the mpd link in some movies, in others you get token error,  try this command...

`youtube-dl -g https://www.mitele.es/peliculas/un-monstruo-viene-a-verme/587e176dc915da8c908b458f/player`

**Comment by gravyboat** [comment]
This isn't a live stream. We're not adding more functionality to play VODs or pre-recorded content.

**Comment by bastimeyer** [comment]
@An0nima if you would include at least some information in your very sparse issues, then it wouldn't have to be mislabeled. The issue template and contribution guides ask everyone to provide as much detail as possible and you've been ignoring this so far in all of your opened issues here.
