### ISSUE TITLE
Huomao plugin do not work

### ISSUE THREAD

**Issue by BlacK201** [streamlink/streamlink#2341]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I tried on two computers but the huomao plugin seems not work,it looks like same as issue#2132,maybe the website updated again.

### Reproduction steps / Explicit stream URLs to test

1. https://www.huomao.com/9418

### Log output

```
[cli][debug] OS:         Linux-4.20.7-1.el7.elrepo.x86_64-x86_64-with-centos-7.6.1810-Core
[cli][debug] Python:     2.7.5
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin huomao for URL https://www.huomao.com/9418
[plugin.huomao][error] Failed to extract stream_info.
error: No playable streams found on this URL: https://www.huomao.com/9418

```
And here is my streamlink version, I think it's the latest version.
```
[root@ live]# pip show streamlink
Name: streamlink
Version: 1.0.0

```

**Comment by unnutricious** [comment]
I took a quick look at a random stream and I think the regex just needs to be updated. The current regex assumes the source url ends in playlist.m3u8, but that was not the case for the one I looked at.

Just go to http://www.huomao.com/mobile/mob_live/<id> for a live stream and search for m3u8 and you can use that as a basis for updating the stream_info_pattern.

**Comment by kesdoputr** [comment]
How can i use http://www.huomao.com/mobile/mob_live/ for the m3u8?

I want to watch https://www.huomao.com/9755
But get the same error like the first post, thank you

**Comment by mkbloke** [comment]
There is now a fix in master for this plugin, available at:

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/huomao.py

Select raw, then file/save as in your browser to download it.  You can then replace the old plugin with the newly downloaded one.
