### ISSUE TITLE
1.1.0 release

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#2349]
With #2326 being merged, I would appreciate if we could have a new minor release in the next couple of days. This is important for streamlink/streamlink-twitch-gui#618, which relies on a new Streamlink release.

Another thing to consider is the EOL of Python 3.4 next week (2019-03-16). Would it make sense waiting for that to happen first and then removing its support from Streamlink? Or are there any reasons for keeping it?

> DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).

https://www.python.org/dev/peps/pep-0429/

**Comment by gravyboat** [comment]
New release sounds like a good plan. I'd say we just remove support. for 3.4 even before it is EOL. No reason to keep it. People should keep their Python install up to date.

**Comment by campones** [comment]
I m still using python 2.7 on my ubuntu server

**Comment by skulblakka** [comment]
> I m still using python 2.7 on my ubuntu server

Well the end of life for Python 2.7 is not reached yet. (It was pushed to 2020).

**Comment by bastimeyer** [comment]
Python 2.7 is a totally different case. Its official EOL is 2020-01-01 (extended from 2015-01-01)

https://pythonclock.org/
https://python3statement.org/

A couple of posts regarding how Linux distros handle the transition

https://lwn.net/Articles/756628/
https://lwn.net/Articles/750833/
https://utcc.utoronto.ca/~cks/space/blog/python/Python2AndLTSLinuxes
https://www.phoronix.com/scan.php?page=news_item&px=RHEL-8-No-Python-2
https://www.archlinux.org/todo/die-python2-die/

**Comment by campones** [comment]
good to hear, thanks

**Comment by beardypig** [comment]
I imagine it will take a while before 2.7 becomes unsupported in streamlink - even if we don’t officially support it after then EOL it, I imagine it will keep on working. Unless we start stripping out the compatibility stuff, which would actually be rather cathartic...

**Comment by karlo2105** [comment]
@beardypig 
Please don't strip support for the latest Python 2.7 version released before EOL, nor the latest Python 3 version released for Windows 7, because I don't want to be forced to upgrade to Windows 10 in next 4 years in order to use the newest streamlink. ;-)

**Comment by gravyboat** [comment]
@karlo2105 While we may allow an old Python 2.7 install to exist (unless some sort of issue comes up regarding security, compatibility annoyances, etc.) we won't support it, and we definitely won't provide support for whatever 3.x releases are EoL past that expiration date. I understand you may not want to upgrade, but that's not something we're going to support. Running EoL software is a security risk.

Keeping compatibility is absolutely costly in terms of work hours, configuration support, testing support, etc. When we have to support old versions via code workarounds or whatever else it makes the code harder to read and annoying for both old and new contributors. If it's worth it to us to remove something so that it's easier for us to maintain we're going to do it for sure.

**Comment by gravyboat** [comment]
@bastimeyer I attempted to do a 1.1.0 release this morning real quick via `sh scripts/release.sh` (looked at the old instructions) and got some `pushd` errors even though it's installed accompanied with the changelog not being generated and placed into the updated release file. I'll try to troubleshoot it some more if @cdrage isn't around. I thought the changelog updates were supposed to automatically be generated...

**Comment by bastimeyer** [comment]
No need to run that script, it's enough if you copy the format of the previous release in the changelog file and then simply push a new tag.
https://github.com/streamlink/streamlink/blob/1.0.0/script/release.sh#L65-L70
dcd7ed015c5317f24f20882bb5bac1f3b0922d64

**Comment by bastimeyer** [comment]
@gravyboat do you want me to open a release PR with a changelog? #2360 needs to be merged before that though

**Comment by gravyboat** [comment]
@bastimeyer Yeah sure go for it. Sorry it's been a busy week. #2360 is merged.
