### ISSUE TITLE
support/plugin for http://www.17app.co/ possible?

### ISSUE THREAD

**Issue by eccccco** [streamlink/streamlink#235]
http://www.17app.co/

is a chinese periscope "clone". Is it possible to write a plugin for this? I don't know if there is a web UI for their streams or if you can only watch them with the corresponding phone app?

**Comment by unnutricious** [comment]
You can view a stream via the web @ http://17.media/share/live/<id>

You can find the rtmp url in the source, but when I try to stream it directly, it stops working after a few seconds, I don't know why.

**Comment by fozzysec** [comment]
@unnutricious I tried the rtmp url from the page with mpv, it works and has no such a problem, would anyone else try the rtmp url?

**Comment by beardypig** [comment]
This was added in #502 :)
