### ISSUE TITLE
Locast.org

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#2350]
## Plugin Request

- [X ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Locast.org

This site only requires that you are in a certain geo area such as NYC.

It provides various online local channels as live streams.

It would allow users in areas that Locast serves to record not just watch content live.

### Example stream URLs

1. ... https://locast.org (Currently unable to find individual links to a certain channel in code)
2. ...
3. ...

### Additional comments, screenshots, etc.
I know they are definitely using variable bitrate m3u8 files that are compatiable with Streamlink.

So in reality all that would be needed to be done would be to have streamlink process a login than just fetch the m3u8 for the desired channel and then rip the m3u8.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This site is throwing an issue with their SSL being invalid which is sketchy so I'm going to close this. If it gets addressed we can consider it at that time.

**Comment by RedPenguin2** [comment]
Strange, since they are a considered a legit website, wouldn't think they'd have a bad SSL cert.

**Comment by gravyboat** [comment]
Looks like they just fixed it? Very odd. There was definitely something wrong with it earlier. I'll reopen this.

**Comment by back-to** [comment]
> SSL being invalid ... Looks like they just fixed it?

it is **still invalid**, only if you use `www` it will be valid

`8. Sites which are unmaintained.`
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> they are a considered a legit website,

well depends on how you are seeing it, but they are just using a **loophole**

`2. Sites which are hosting stolen content as their main source of content`

---

> I know they are definitely using variable bitrate m3u8 files that are compatiable with Streamlink.

yeah, but they play an AD at the start `#EXT-X-DISCONTINUITY` and **close the session after 15 minutes**

Not really worth to support this site as it will probably end up in more created issues.
