### ISSUE TITLE
RTS - SRG SSR plugin

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2355]
I didn't realize there was a plugin for the swiss television, so I coudn't resist to try it since I also have a physical server based in Switzerland.. 

But it looks like only the info channel is working fine but not rts1 and rts2 that are drm'ed?
If so I guess nothing can be done and previous thread  I have read (from 2017) is outdated.

RTS2

streamlink -l debug https://www.rts.ch/play/tv/direct?tvLiveId=3608517 best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin srgssr for URL https://www.rts.ch/play/tv/direct?tvLiveId=3608517
[plugin.srgssr][debug] Found rts video ID 3608517
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 180p (language=fra, name=audio1)
[stream.hls][debug] Using external audio tracks for stream 272p (language=fra, name=audio1)
[stream.hls][debug] Using external audio tracks for stream 360p (language=fra, name=audio1)
[stream.hls][debug] Using external audio tracks for stream 544p (language=fra, name=audio1)
[stream.hls][debug] Using external audio tracks for stream 138k (language=fra, name=audio1)
[cli][info] Available streams: 138k (worst), 180p, 272p, 360p, 544p (best)
[cli][info] Opening stream: 544p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 308944; Last Sequence: 308952
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 308950; End Sequence: None
[stream.hls][debug] Adding segment 308950 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 308951 to queue
[stream.hls][debug] Adding segment 308952 to queue
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 308935; Last Sequence: 308943
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 308941; End Sequence: None
[stream.hls][debug] Adding segment 308941 to queue
[stream.hls][debug] Adding segment 308942 to queue
[stream.hls][debug] Adding segment 308943 to queue
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-2751-639 -i /tmp/ffmpeg-2751-771 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-2751-639
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-2751-771
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', u'SAMPLE-AES')
[stream.segmented][debug] Closing writer thread
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', u'SAMPLE-AES')
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/ffmpeg-2751-639
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing worker thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][error] Try 1/1: Could not open stream <Stream()> (No data returned from stream)
error: Could not open stream <Stream()>, tried 1 times, exiting
[cli][info] Closing currently open stream...
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams

RTS INFO

streamlink -l debug https://www.rts.ch/play/tv/direct?tvLiveId=1967124 best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.4.0-128-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin srgssr for URL https://www.rts.ch/play/tv/direct?tvLiveId=1967124
[plugin.srgssr][debug] Found rts video ID 1967124
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 56k_alt (worst), 56k, 180p_alt, 180p, 270p_alt, 270p, 360p_alt, 360p, 540p_alt, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 258763413; Last Sequence: 258763415
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 258763413; End Sequence: None
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 258763413 to queue
[stream.hls][debug] Adding segment 258763414 to queue
[stream.hls][debug] Adding segment 258763415 to queue
[stream.hls][debug] Download of segment 258763413 complete
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
[cli][info] Closing currently open stream...
[stream.segmented][debug] Closing worker thread

**Comment by campones** [comment]
hi back-to where is the other thread? can't see anything mentioning this plugin recently

**Comment by gravyboat** [comment]
Pretty sure it's this one: https://github.com/streamlink/streamlink/issues/1825

**Comment by back-to** [comment]
> If so I guess nothing can be done and previous thread I have read (from 2017) is outdated.

you already explained yourself, why this is a duplicate

> [stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', u'SAMPLE-AES')

this won't work with Streamlink
