### ISSUE TITLE
Issues with the Windows Installer for Streamlink 1.0.0

### ISSUE THREAD

**Issue by PmmaGit** [streamlink/streamlink#2356]
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description

I installed Streamlink 1.0.0 today on Windows 10 Pro x64 (Build 1803) and noticed a few issues with the installation, in a sense they are more recommendations towards improving the installation process than actual bugs but i'll get into that shortly.

**Smart Screen Warning**
So the first issue is that running the installer prompts a Windows Smart Screen warning blocking the launch of it. I'm not sure if whether this is a false flag by the system or there's issues with the installer's signature (if any). I'll give it credit that SmartScreen goofs up sometimes but i can see this as something that can discourage potential less tech savvy users from installing Streamlink.

**Conflict with previous installations**
The second issue, and this one is the one that can be potentially be the root of some problems, if upgrading from a previous installation of Streamlink (myne was 0.14.2 if i'm not mistaken), the installer will not remove the previous ones. This is more specifically attached to the option ```Install for all users``` available on the installer as i believe the previous installations didn't consider this.

The problem here is that installing Strealink for all users, by default, will put it into ```C:\Program Files (x86)``` and a single user installation will put it into ```C:\Users\<user>\Appdata\Local```, so conflicting installations will result in having two installations and two paths loaded into the PATH variable. As such, whenever i popped Streamlink on my command line i was still getting the old one.

Perhaps a simple solution would be including a warning on the downloads page to uninstall the previous version, which in the end is what i had to do.

### Note
I didn't include the other sections from the template because i didn't see them as relevant, nor there's a malfunction in streamlink itself.

**Comment by bastimeyer** [comment]
> Smart Screen Warning

That's because the installer isn't signed by MS or one of their partners. You have to buy a certificate for that purpose, which costs hundreds of dollars per year. Quite ridiculous, just like this whole "security" idea on Windows.

Just ignore this warning, there's nothing which can be done here. If one doesn't trust the installer, they should consider installing Streamlink in their system's default Python env via pip, etc.

> Conflict with previous installations

This is a known issue and somewhat a limitation of the libs which are being used for creating the installer (pynsist+NSIS). Custom uninstall logic needs to be added here but regarding the two different install methods, this makes it even more difficult.

**Comment by gravyboat** [comment]
@bastimeyer has explained pretty thoroughly about why it should just be ignored, but even if we could afford to purchase one (which we can't and reasonably keep the budget) we wouldn't. It's really just security theater by Microsoft to try and keep their stranglehold on the app marketplace and make as much money as they can. ANYONE can buy one of these certs so scammers could buy them and Microsoft would have no issue.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2356#issuecomment-473461426

closing, there is not much we can do about it.
