### ISSUE TITLE
Streamlink for centos

### ISSUE THREAD

**Issue by bigggbang** [streamlink/streamlink#2359]
Could you help me with installing streamlink to centos? have problems with pip

**Comment by kodlayanzi** [comment]
@bigggbang did you find any solution?

**Comment by bigggbang** [comment]
@kodlayanzi no, just trying to find it

**Comment by bastimeyer** [comment]
You haven't posted any details at all of your issue. How are people here supposed to help you?

**Comment by bigggbang** [comment]
i understand, that it should be installed through pip
so, i have problem when i trying to install pip
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
                                    ^
SyntaxError: invalid syntax
```
CentOS 6

**Comment by gravyboat** [comment]
We don't support Python 2.6, upgrade to at least 2.7 or preferably 3.x. 2.6 has been EOL for years. Your distro should have updated packages available.
