### ISSUE TITLE
DirecTV Now (HLS / M3U8)

### ISSUE THREAD

**Issue by besweeet** [streamlink/streamlink#236]
On desktop via web browsers, DirecTV Now uses Smooth Streaming, while on mobile, it uses HLS. Both methods support resolutions of up to 1080p and frame rates of up to 60FPS (at least from what the playlist files are telling me).

I tried an M3U8 with livestreamer / streamlink, VLC opens, but it acts as though it's permanently buffering. No cookie was used as sniffing software says that the M3U8 and .TS requests didn't have any. The only non-standard headers as "X-NewRelic-ID" and "ETag," neither of which gets video to play when using --http-header.

index.m3u8 contents:

> #EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="eng_1",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="eng",URI="04.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="eng_2",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="eng",URI="05.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="eng_3",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="eng",URI="06.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="caption_1",DEFAULT=NO,AUTOSELECT=YES,LANGUAGE="ENG",URI="107.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3263306,CODECS="avc1.64002A",RESOLUTION=1280x720,FRAME-RATE=59.940,AUDIO="audio",SUBTITLES="subs"
03.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=67985,CODECS="avc1.64002A",RESOLUTION=1280x720,URI="03-iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=6073089,CODECS="avc1.64002A",RESOLUTION=1280x720,FRAME-RATE=59.940,AUDIO="audio",SUBTITLES="subs"
02.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=126522,CODECS="avc1.64002A",RESOLUTION=1280x720,URI="02-iframe.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=8882871,CODECS="avc1.64002A",RESOLUTION=1920x1080,FRAME-RATE=59.940,AUDIO="audio",SUBTITLES="subs"
01.m3u8
#EXT-X-I-FRAME-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=185059,CODECS="avc1.64002A",RESOLUTION=1920x1080,URI="01-iframe.m3u8"

01.m3u8 (1080p60):

> #EXTM3U
#EXT-X-TARGETDURATION:7
#EXT-X-MEDIA-SEQUENCE:246828310
#EXT-X-VERSION:3
#EXT-X-KEY:METHOD=NONE
#EXT-X-PROGRAM-DATE-TIME:2016-12-01T01:39:55.6429290Z
#EXTINF:6.5732,
20161122T033033-246828310-01-20161201T013955.ts
#EXT-X-SPLICEPOINT-SCTE35:/DA2AAAAAAAAAP/wBQb+i1ELPAAgAh5DVUVJAAAAAX+/AQ8wMDAwOTM5MTYzNzI3MDcBAQFQ9UDj
#EXTINF:5.4388,
20161122T033033-246828311-01-20161201T014002.ts
#EXTINF:4.5712,
20161122T033033-246828312-01-20161201T014007.ts
#EXT-X-SPLICEPOINT-SCTE35:/DA2AAAAAAAAAP/wBQb+i17KYAAgAh5DVUVJAAAAAX+/AQ8wMDAwOTM5MTYzNzI3MDcBAQGAx/cT
#EXTINF:7.4408,
20161122T033033-246828313-01-20161201T014012.ts
(etc.)

Of course, the .TS files don't play in any media play I tried (VLC / WMP / MPC).

Is encryption to blame?

**Comment by beardypig** [comment]
```
#EXT-X-KEY:METHOD=NONE
```
Suggests that it is not encrypted, but that seems unlikely. Perhaps there is some external encryption that isn't obvious from the m3u8 files. Would need an account to see exactly what is going on. Might be able to sign up for the free trial and give it a go. 

Did you try an run the ts files through ffmpeg?

**Comment by scottbernstein** [comment]
Also, are you sure it's not the old "Need VLC3.0 nightly build" problem for watching current YouTube videos cropping up again here?

**Comment by besweeet** [comment]
@beardypig I did not try FFmpeg yet. I've had it for a while, but have only used for a few basic things. I'm not sure what I would do with it in this case.

@scottbernstein I've actually been running VLC 3.0 nightlies for a while now (yay for the non-broken YouTube streams again), but they don't seem to do anything for DTVN.

**Comment by L2501** [comment]
this is HLS v4 playlist, is that even currently supported by the python downloader?

**Comment by beardypig** [comment]
@L2501, no that is not _currently_ supported... Give it a couple of weeks ;)

**Comment by besweeet** [comment]
NBC Sports Live Extra uses HLS v4 playlists (at least that's what their JS manifest shows):
``"videoSources": [
    {
      "id": "101617",
      "sourceUrl": "http://[snipped]/manifest.f4m",
      "sourceUrlAlt": "http://[snipped]/manifest.f4m",
      "sourceURLComcast": "",
      "hlsv4Url": "http://[snipped]/master.m3u8",
      "hlsv4UrlAlt": "http://[snipped]/master.m3u8",
      "iossourceUrl": "http://[snipped]/master.m3u8",
      "iossourceUrlAlt": "http://[snipped]/master.m3u8",
      "ottStreamUrl": "http://[snipped]/master.m3u8",
      "ConnectedUrl1:": "http://[snipped]/connected1/master.m3u8",
      "ConnectedUrl2:": "http://[snipped]/connected2/master.m3u8",
      "hdsStreamUrl": "http://[snipped]/manifest.f4m",

Sample of their hlsv4Url M3U8 file:

Well, I was going to send it, but it looks like NBC may have changed a few things. None of those M3U8 files are found anywhere, just the HDS F4M ones (which also aren't working -- livestreamer / streamlink says no streams are found -- here's the F4M dump: http://pastebin.com/raw/2LSvEc8u). I may need to see what links their Android and Windows 10 apps are using.

I'm pretty sure their hlsv4Url links played fine, but may be mistaken. But that's a different topic, I guess.

**Comment by beardypig** [comment]
All the DirecTV streams are encrypted, and you need a DRM module (Widevine, PlayReady or FairPlay) to decrypt them. This is likely something that will not be supported.

**Comment by gravyboat** [comment]
I'm going to close this for now since it's not really feasible.
