### ISSUE TITLE
ok.ru - does not work!

### ISSUE THREAD

**Issue by dmitrylc** [streamlink/streamlink#2364]
![image](https://user-images.githubusercontent.com/2939460/54556728-9398d900-49ca-11e9-93cb-a55856e07882.png)

ok.ru - does not work!

**Comment by alex-zed** [comment]
[cli][debug] OS:         Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.15rc1
[cli][debug] Streamlink: 1.0.0+46.g42105d8
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin ok_live for URL ok.ru/live/1149468679758
[utils.l10n][debug] Language code: ru_RU
error: Unable to open URL: https://vsd24.mycdn.me/hls/542637296206.m3u8/sig/RxGJVgZoWNQ/expires/1553187068279/srcIp/x.x.x.x/clientType/0/srcAg/CHROME/video.m3u8?p (403 Client Error: Forbidden for url: https://vsd24.mycdn.me/hls/542637296206.m3u8/sig/RxGJVgZoWNQ/expires/1553187068279/srcIp/x.x.x.x/clientType/0/srcAg/CHROME/video.m3u8?p)

**Comment by Bluebuster116** [comment]
@dmitrylc I'm also having this problem. Tried to update to the nightly build but still the problem persists. So far the plug in has not been updated. I'm still unsure what might be happening.

**Comment by c769214** [comment]
@dmitrylc I have the same issue, waiting for any updates for this plugin
