### ISSUE TITLE
different xml.etree.elementtree import statements cause exception

### ISSUE THREAD

**Issue by jairoxyz** [streamlink/streamlink#2366]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

When using streamlink in python and calling plugins that use xml parsing with elementtree, such as RTVE, repeated calls of the plugin throws exception in `utils\__init__.py` (see log below). Note that the first call to the plugin works as expected. Second and consecutive calls throw error.

### Expected / Actual behavior

Stream should play again but exception is thrown.

### Reproduction steps / Explicit stream URLs to test

Test with http://www.rtve.es/directo/canal-24h

### Log output

```
DEBUG: [StreamLink] Found matching plugin rtve for URL http://www.rtve.es/directo/canal-24h
DEBUG: Traceback (most recent call last):
DEBUG:   ".\streamlink\utils\__init__.py", line 95, in parse_xml
DEBUG:     tree = ET.fromstring(data)
DEBUG:   File "<string>", line 123, in XML
DEBUG: TypeError: 'NoneType' object is not callable
```

### Additional comments, screenshots, etc.
I pinned the problem down to the elementtree import statement used in `utils\__init__.py` vs the statement used in `plugin\api\validate.py` and can fix the problem by changing the import in `__init__.py` from:

```
try:
    import xml.etree.cElementTree as ET
except ImportError:  # pragma: no cover
    import xml.etree.ElementTree as ET
```
to

```
from xml.etree import ElementTree as ET
```

Obviously the two differing import statements bite in some way and using the same import in both modules fixes it.

Cheers,

Jx-

**Comment by beardypig** [comment]
What about changing them both to 

```python
try:
    import xml.etree.cElementTree as ET
except ImportError:  # pragma: no cover
    import xml.etree.ElementTree as ET
```

Does that still work? In theory `cElementTree` will be faster as it is implemented in C.

**Comment by back-to** [comment]
> Note that the first call to the plugin works as expected. Second and consecutive calls throw error.

does it play once, but not twice?

---

the error might depend on how you use Streamlink,
how do you embed it?

**Comment by jairoxyz** [comment]
@beardypig I tried that but get that strange error again upon repeated play of the stream. So I guess it's the compiled version cElementTree that's causing the error.

@back-to I am using it inside Kodi in a proxy similar to your LiveProxy addon. So, probably the error is related to my proxy or Kodi.

According to https://docs.python.org/2/library/xml.etree.elementtree.html that version of xml.etree is quite outdated and therefore I am actually using the recommended https://kodi.wiki/view/Add-on:Elementtree_XML_parser which seems to be a bit newer and works fine for me without errors.

So, no problem, but thanks for worrying :)

**Comment by back-to** [comment]
you shouldn't use any `script.module.elementtree`

https://forum.kodi.tv/showthread.php?tid=173887

make sure to use updated python, kodi versions etc.

---

closing, the issue is not Streamlink related

**Comment by jairoxyz** [comment]
Well, yes and no. The 2.x lib should not be used for untrusted xml. They rather recommend using defusedxml: https://docs.python.org/2/library/xml.html#xml-vulnerabilities
