### ISSUE TITLE
Twitch Pre-Roll ads (even on audio_only) -- Yes, tested using git snapshot post "fix"

### ISSUE THREAD

**Issue by mjevans** [streamlink/streamlink#2368]
- [x] This is a bug report and I have read the contribution guidelines.

The previously closed issue #2357 is still happening and I have reproduced it after manually installing a git checkout from about 10 min before this bug report.

Current test URL:

Even audio only (though the example was captured at another resolution)

```
streamlink twitch.tv/zisteau audio_only
```

Will display an actual VIDEO ad, also completely ignoring resolution or bandwidth use desires.

Occasionally the mismatch between the ad and the stream also causes the audio to playback in an oddly corrupted way (the streamer sounded down-pitch shifted, and the audio was very studdery, but that was a result of the ad invasion).

```
streamlink --loglevel=debug twitch.tv/zisteau 480p 2>&1 | tee streamlog.txt
[cli][debug] OS:         Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 1.0.0+46.g42105d8
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/zisteau
[plugin.twitch][debug] Getting live HLS streams for zisteau
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 900p60 (best)
[cli][info] Opening stream: 480p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 4
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2; End Sequence: None
[stream.hls][debug] Adding segment 2 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Download of segment 2 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format twitch.tv/zisteau -
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Download of segment 4 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Download of segment 5 complete
[stream.hls][debug] Download of segment 6 complete
[stream.hls][debug] Download of segment 7 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Download of segment 8 complete
[stream.hls][debug] Download of segment 9 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Download of segment 11 complete
[stream.hls][debug] Download of segment 12 complete
[stream.hls][debug] Download of segment 13 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Download of segment 14 complete
[stream.hls][debug] Download of segment 15 complete
```

### Additional comments, screenshots, etc.

I also had streamlink dump a --stream-url and ran wget on the the result:

Contents (longer hex strings [REDACTED]):

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:28232.000
#EXT-X-TWITCH-TOTAL-SECS:28242.010
#EXT-X-DATERANGE:ID="stitched-ad-[REDACTED]-[REDACTED]",CLASS="twitch-stitched-ad",START-DATE="2019-03-20T05:17:07.821Z",DURATION=15.164,X-TV-TWITCH-AD-ROLL-TYPE="PREROLL",X-TV-TWITCH-AD-POD-LENGTH="2",X-TV-TWITCH-AD-POD-POSITION="0",X-TV-TWITCH-AD-URL="https://www.hersheys.com/icebreakers/en_us/home.html"
#EXT-X-DISCONTINUITY
#EXT-X-SCTE35-OUT:URL="https://www.hersheys.com/icebreakers/en_us/home.html"
#EXT-X-PROGRAM-DATE-TIME:2019-03-20T05:17:07.821Z
#EXTINF:2.002,[REDACTED]-01-02-2019-23.49.14
https://video-edge-7e9300.sea01.abs.hls.ttvnw.net/v1/segment/[REDACTED].ts
#EXT-X-PROGRAM-DATE-TIME:2019-03-20T05:17:09.822999999Z
#EXTINF:2.002,[REDACTED]-01-02-2019-23.49.14
https://video-edge-7e9300.sea01.abs.hls.ttvnw.net/v1/segment/[REDACTED].ts
#EXT-X-PROGRAM-DATE-TIME:2019-03-20T05:17:11.824999998Z
#EXTINF:2.002,[REDACTED]-01-02-2019-23.49.14
https://video-edge-7e9300.sea01.abs.hls.ttvnw.net/v1/segment/[REDACTED].ts
#EXT-X-PROGRAM-DATE-TIME:2019-03-20T05:17:13.826999997Z
#EXTINF:2.002,[REDACTED]-01-02-2019-23.49.14
https://video-edge-7e9300.sea01.abs.hls.ttvnw.net/v1/segment/[REDACTED].ts
#EXT-X-PROGRAM-DATE-TIME:2019-03-20T05:17:15.828999996Z
#EXTINF:2.002,[REDACTED]-01-02-2019-23.49.14
https://video-edge-7e9300.sea01.abs.hls.ttvnw.net/v1/segment/[REDACTED].ts
```

Some of the redacted streams appear likely to be either session or user-login specific, so to err on the safeside I've [REDACTED] them.

Of also note, the EXTINF date-stamp appears to be referencing one that is wildly divergent from current timestamps.

**Comment by fantom8** [comment]
This is happening to me as well and beyond the annoyance of ads that don't respect your resolution or audio settings (always loads 1080p), it absolutely destroys streamlink audio and video settings when the ad ends.

I constantly have to close and re-open the stream, which plays another ad each time, just crossing my fingers that the audio won't be glitched out or the playback speed messed up. I suspect this might also be introducing even more stream delay too, based on comparing timestamps in chat (pulled through Chatty) to when the streamer reacts to the message on screen.

Also the player closes ("stream ended" message) very often when a streamer plays an ad. Both big and small channels.

Glitched audio takes different forms. Sometimes it "stutters": half second of audio and a half second of silence, constantly. Other times it plays at an increased speed, "chipmunk syndrome."

**Comment by bastimeyer** [comment]
Are you by any chance using VLC?
These are glitches caused by your player while reading the MPEG-TS stream of Streamlink's concatenated HLS segments. Since ads don't necessarily share the same format as the live stream, this can cause issues in certain players like VLC. MPV has been working fine for me, so you might want to try that instead...

In the HLS stream, the start and end of an ad sequence is annotated with the `#EXT-X-DISCONTINUITY` tag. This is meant for telling the player to reset its decoding/rendering state. That does of course only work if a player is reading the HLS stream directly and implements it correctly. I'm not sure how this can be translated into the way Streamlink currently works. Would remuxing the MPEG-TS stream into a different format help, or do you have any other ideas here, @beardypig?

----

Unless somebody finds a way to request HLS streams which are not using their 
"SureStream" stuff or unless someone finds a way to (re-)request the live segments during an ad sequence, I fear that we won't be able to fix this. Twitch has the upper hand here...
Regarding simply ignoring the ad segments, I don't think this is an option unless we're fine with potentially long gaps in the stream output. It would fix the player issues, though.

**Comment by beardypig** [comment]
It is possible to ignore the **pre-roll** ads, but it would delay the start of the stream by a bit - until twitch starts sending the actual stream data. 

I stream ads are more complicated, we can ignore those too - but it might cause the stream to stop if the ad break to too long. 

I'll take a look at filtering our pre-roll ads.

**Comment by MancV21** [comment]
Same here. Worked for a day or so but it's back again.

**Comment by collinsurvive** [comment]
Also happening for me

**Comment by bastimeyer** [comment]
**Please stop posting "me too"**, this doesn't help and only bloats up this thread. We are looking for solutions here...

If you want to get notified on an update, you can subscribe to the thread (the button on the right) or watch the entire repository (the button on top).

**Comment by mule42** [comment]
I've whipped up a fragile kludge that hides the preroll ads for the moment, based on [back-to's work](https://github.com/streamlink/streamlink/issues/1676#issuecomment-430304591).
```
4d3
< import time
174,199d172
<         reee = re.compile('stitched-ad.*,DURATION=([0-9.]+),')
<         m = reee.search(res.text)
<         n = 1
<         t=0.0
<         tee=0.0
<         while m:
<             if tee > 600.0:
<                 log.error("10 minutes of ads is too long. screw this.")
<                 raise StreamError("ad waiting timeout.")
<             elif n > 10:
<                 log.error("10 ads in a row is too much. screw this.")
<                 raise StreamError("ad waiting tolerance exceeded.")
<             else:
<                 t=float(m.group(1))
<                 log.info("waiting out ad playlist #%02d for %.2f seconds" % (n,t))
<                 time.sleep(t)
<                 tee+=t
<                 res = self.session.http.get(self.stream.url,
<                                             exception=StreamError,
<                                             retries=self.playlist_reload_retries,
<                                             **self.reader.request_params)
<                 m = reee.search(res.text)
<                 n+=1
<         if tee > 0.0:
<             n-=1
<             log.info("waited %.2f seconds on %2d ads." % (tee,n))
990c963
< __plugin__ = Twitch
---
> __plugin__ = Twitch
\ No newline at end of file
```

Works in the latest streamlink development version, at least. Make sure to not use any form of player passthrough, so the TwitchM3U8Parser can do it's thing.

**Comment by MancV21** [comment]
Does that work with in-stream ads?

**Comment by spencerhakim** [comment]
> Are you by any chance using VLC?

Not the OP, but I'm seeing the same behavior with MPV opening a video window despite using `audio_only`. Is this really two separate issues (video opening despite `audio_only`, and ads causing issues with stream playback)?

**Comment by beardypig** [comment]
@spencerhakim when they injects the ads they always have video, I guess this violates the HLS standard - but that's a twitch.tv issue :) 

They inject whatever video ads they like which disrupts the steam with their adverts - if you have chosen audio_only it's the same thing, but you get unexpected video. As a workaround you can set the video output on `mpv` to null (`--vo null`). Alternatively you can test out my fix, but it's slightly more difficult to apply.

**Comment by RenaKunisaki** [comment]
Seeing this too, not just with Streamlink but also with Twitched app on Roku starting yesterday. So I guess they finally started injecting into the actual video stream.

**Comment by camjac251** [comment]
It is possible to fix previously recorded streams with an ad in front using ffmpeg.
You can use something like `ffmpeg -r 60 -ss 00:00:06 twitchlink.mp4 -c:v copy -c:a copy output.mp4`. The ad in front of my test recording was only 5 seconds so starting it after and forcing the framerate to the stream can help fix playback.

**Comment by YxY-CHN** [comment]
@camjac251 Thank you for providing ffmpeg's solution, but it seems that there is no way to solve the advertisement in the middle of the video.

**Comment by bastimeyer** [comment]
See #2372, which adds the `--twitch-disable-ads` parameter to Streamlink and skips all advertisement segments in the HLS stream.
