### ISSUE TITLE
get stream file size before downloading ?

### ISSUE THREAD

**Issue by patugo** [streamlink/streamlink#2377]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Is there a way to have the stream file size before downloading the stream ?

**Comment by beardypig** [comment]
Generally speaking no, Streamlink is geared towards live streams and as such the size of the stream is not limited. It would be possible for VOD, however that is not the focus of this project so I am tempted to mark this as "out of scope". 

You could write your own script to do it, by getting the stream URL from Streamlink and parsing the information provided by that URL - however, you may or may not find it easy. HTTP streams could be simple, M3U8 stream more difficult as would HDS and DASH, but I don't know about RTMP.

**Comment by gravyboat** [comment]
@beardypig Has been kind enough to note this is out of scope so I'm going to close it.
