### ISSUE TITLE
m3u8 giving 406 not acceptable error when i try to watch on vlc

### ISSUE THREAD

**Issue by jameswil2** [streamlink/streamlink#2378]
Hi.

can anyone give me an example how to use this header info to stream it on vlc player

thanks :)

GET /cdn.site.com/jasmintv.live.cdn.site.com/gogo/gogo_HD_600.m3u8?jct=ZVN94wWPcSyLdscrOCyYpw&pxe=1433456832&st=d82dywgwdijwkGfxp1I7A HTTP/1.1
os: android
subscriberId: 2087154251
deviceId: 94AS5170c4b6721
userId: jameswilson-26
versionCode: 188
devicetype: phone
crmid: 7123193622
osVersion: 8.1.0
srno: 190327162016
usergroup: tvYR7NSNn7rymo3F
appkey: GzHSKSWQIQyNjJm
lbcookie: 1
uniqueId: d8bdd028-4c3a-4af7-be03-040737d159af
ssotoken: eyJ0eXAiOiJKV1QiWUKFGWIQUKFHW.QKLHNmbdliyeiwqfvlkUiOiJkOGJjYzA2OS00YzNhLTRhZjctYmUwMi0wMzcWEOFHWEUFEUFHEWOFWEPJPEJEKHEWOFEWKNWELKNGWEL;KNNTNiZGQ2NGIyMjU4ZDcxYzI5ZWE4YzkwNzA3NzBkZGI1ZDRlMmExYzMzYzNlNSIsImp0aSI6ImM3Y2FhNzczLTQxZWQtNGYxZC1iNTI3LWIyZjM4NGYFHVEWPSWH827DY3NzU3Nn0.2P57XqflW3v8bPdO9MMDLWppBMJEEnDRgnBcVTxBSWY
channelid: 233
User-Agent: plaYtv/5.6.0 (Linux;Android 8.1.0) ExoPlayerLib/2.8.0
Accept-Encoding: identity
Host: cdn.something.com
Connection: Keep-Alive

**Comment by back-to** [comment]
`streamlink URL best --http-header "KEY=VALUE" --http-header "KEY=VALUE" --http-header "KEY=VALUE"`

https://streamlink.github.io/cli.html#cmdoption-http-header

**Comment by jameswil2** [comment]
Hi @back-to thanks for the reply

streamlink URL best --http-header "userId=jameswilson-26" --http-header "appkey=GzHSKSWQIQyNjJm" --http-header "User-Agent=plaYtv/5.6.0 (Linux;Android 8.1.0) ExoPlayerLib/2.8.0"

is this above format is correct?

**Comment by back-to** [comment]
@jameswil2 yes, but you might need to send more http-headers and a valid URL

**Comment by jameswil2** [comment]
thank u @back-to will try it

**Comment by jameswil2** [comment]
hi @back-to 
tried all included http-headers still gives me this error 

Failed to create decryptor: Unable to open URL: https://tv.media.jasmin.com/streams_live/CHN_HD/CHN_HD_600-1553856730000.key (405 Client Error: Not Allowed for url: https://tv.media.jio.com/streams_live/HBO_HD/HBO_HD_600-1553856730000.key)

**Comment by jameswil2** [comment]
hi @back-to
tried all included http-headers still gives me this error

Failed to create decryptor: Unable to open URL: https://tv.media.jasmin.com/streams_live/CHN_HD/CHN_HD_600-1553856730000.key (405 Client Error: Not Allowed for url: https://tv.media.jasmin.com/streams_live/CHN_HD/CHN_HD_600-1553856730000.key)
