### ISSUE TITLE
ustreamix support

### ISSUE THREAD

**Issue by kodlayanzi** [streamlink/streamlink#2383]
https://ssl.ustreamix.com/

how can we parse this website m3u8 urls?

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Requests should be as detailed as possible and dedicated to only a single streaming service. Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.

> 2. Sites which are hosting stolen content as their main source of content
