### ISSUE TITLE
Feature Request : Expose user-agents from API to CLI

### ISSUE THREAD

**Issue by mason362** [streamlink/streamlink#2385]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

The API makes use of 'short codes' for common user-agents for headers, as defined in src/streamlink/plugin/api/useragents.py

The CLI relies on end user to define the full strings via use of `--http-header "user-agent=whatever"`

### Expected / Actual behavior

- Maintain use of current `--http-header` parameters for complex or non-standard strings
- Provide new CLI parameter, such as `--user-agent`, allowing use of 'short codes'

Example of current might be
`--http-header "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"`

Example of new CLI might be
`--user-agent chrome`

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I like the idea :)

**Comment by back-to** [comment]
with https://github.com/streamlink/streamlink/pull/2795
**Firefox** is used as the default User-Agent instead of `python-requests`
which results in less robot detection for Streamlink.

> The CLI relies on end user to define the full strings via use of --http-header "user-agent=whatever"

just use a config file, if this is to complicated.

closing
