### ISSUE TITLE
Youtube plugin work incorrectly in some computers

### ISSUE THREAD

**Issue by MaximVol** [streamlink/streamlink#2389]
## Plugin Issue

- [X] This is a plugin issue and I have read the contribution guidelines.

### Description

I have two servers with identical OS and Python version. On both computers Streamlink is upgraded to latest version by command pip install -U streamlink
Despite this fact Streamlink cannot handle some YouTube streams on one of servers.

### Reproduction steps / Explicit stream URLs to test

streamlink -l debug https://www.youtube.com/watch?v=5avbHxRppxo

### Log output

Streamlink output from the first server (YouTube link cannot be handled):

[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=5avbHxRppxo
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: 5avbHxRppxo
[plugin.youtube][debug] get_video_info - 1: Video unavailable
[plugin.youtube][debug] get_video_info - 2: Video unavailable
[plugin.youtube][debug] get_video_info - 3: Video unavailable
[plugin.youtube][error] Could not get video info: Video unavailable
error: No playable streams found on this URL: https://www.youtube.com/watch?v=5avbHxRppxo

Streamlink output from the second server (YouTube link can be handled):

[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.9.0-8-amd64-x86_64-with-debian-9.8
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=5avbHxRppxo
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: 5avbHxRppxo
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)

### Additional comments, screenshots, etc.

I made comparison of Streamlink folder on these servers. All uncompiled ".py" files are the same, but I see a lot of differences in compiled ".pyc" files. Thus maybe this is some compilation issue?

**Comment by liamkennedy** [comment]
I cannot view that youtube video due to content (location) restrictions.  Is one of your servers "located" in a different country?

**Comment by MaximVol** [comment]
Yes, this issue is really related to regional restrictions. Thank you a lot for explanations!
It would be good if YouTube plugin could display more specific error message in this case.
