### ISSUE TITLE
Haberturk not play

### ISSUE THREAD

**Issue by dreamboxco** [streamlink/streamlink#2390]
## Error Report

- [x] This is a bug report and I have read the Posting Guidelines.

### Description

Haberturk TV is not played via the streamlink.

### Expected / actual behavior

I expect it to be played through the cinergroup.py

### Reproduction steps / Explicit stream URLs to test

1. https://www.haberturk.com/tv/canliyayin

### log output

[streamlinksrv] [info] Sun Mar 31 20:29:26 2019 Server (1.1.0) started
[streamlinksrv] [info] OS: Linux-4.10.6-mips-with-glibc2.0
[streamlinksrv] [info] Python: 2.7.13
[streamlinksrv] [info] Streamlink: 1.0.0.r0_mod / 30.01.2019
[streamlinksrv] [debug] Options Parser: 0.1.8
[streamlinksrv] [info] Requests (2.13.0), Websocket (0.48.0)
[streamlinksrv] [info] Processing URL: http://www.haberturk.tv/canliyayin
[streamlinksrv] [debug] URL Args: []
[streamlinksrv] [info] Found matching plugin cinergroup for URL http://www.haber
urk.tv/canliyayin
[streamlinksrv] [error] No playable streams found on this URL: http: //www.habert
rk.tv/canliyayin
127.0.0.1 - - [31 / Mar / 2019 20:29:31] "GET /http://www.haberturk.tv/canliyayin H
TP / 1.1 "200 -
[streamlinksrv] [info] Processing URL: http://www.haberturk.tv/canliyayin
[streamlinksrv] [debug] URL Args: []
[streamlinksrv] [info] Found matching plugin cinergroup for URL http://www.haber
urk.tv/canliyayin
[streamlinksrv] [error] No playable streams found on this URL: http: //www.habert
rk.tv/canliyayin
127.0.0.1 - - [31 / Mar / 2019 20:29:33] "GET /http://www.haberturk.tv/canliyayin H
TP / 1.1 "200 -

`` `
Windows:

PS C: \ WINDOWS> streamlink https://www.haberturk.com/tv/canliyayin best
error: No plugin can handle URL: https://www.haberturk.com/tv/canliyayin
`` `

**Comment by back-to** [comment]
use the URL `https://www.haberturk.com/canliyayin/embed`
no need to fix this for now

```
$ streamlink https://www.haberturk.com/canliyayin/embed -l info
[cli][info] Found matching plugin cinergroup for URL https://www.haberturk.com/canliyayin/embed
[cli][info] Available streams: 360p (worst), 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/mpv
```
