### ISSUE TITLE
Piczel Multistream

### ISSUE THREAD

**Issue by panhartstuff** [streamlink/streamlink#2396]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Currently, there's no way to select which host to watch in a Piczel multistream, so it would be nice if a feature would be implemented. Something similar to `--pixiv-performer`

### Expected / Actual behavior

This feature would allow you to select hosts, when watching a Piczel multistream

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> Currently, there's no way to select which host to watch in a Piczel multistream

just use the other username `https://piczel.tv/watch/USERNAME`

---

closing, not really worth to update the plugin for this.

**Comment by panhartstuff** [comment]
@back-to It doesn't work when you use the other username. It simply says that no stream is found.
