### ISSUE TITLE
Allow streamlink to be a gstreamer plugin

### ISSUE THREAD

**Issue by etam** [streamlink/streamlink#2398]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I'd like to use streamlink as a gstreamer plugin. It should be possible with gst-python package (https://github.com/GStreamer/gst-python/tree/master/examples/plugins/python)

### Actual behavior

Right now I use it this way (it's a simplified example, full one is here: https://gitlab.com/etam/iss_tv_wall/blob/master/iss_tv_wall.sh):

```bash
gst-launch-1.0 filesrc location=<(streamlink $channel_url best -O) ! decodebin ! autovideosink
```
It works, as long as network connection is stable and fast enough to download stream on time. Gstreamer has a notion of a "live source" (https://gstreamer.freedesktop.org/documentation/design/live-source.html), but `filesrc` element does not provide it. This makes the pipeline very unstable, likely to get stuck or not start at all.

### Expected behavior

With streamlink being a gstreamer plugin I could use it this way:

```bash
gst-launch-1.0 streamlink url=$channel_url quality=best ! decodebin ! autovideosink
```

**Comment by back-to** [comment]
there is https://github.com/streamlink/streamlink/blob/master/examples/gst-player.py

but it might be outdated https://github.com/streamlink/streamlink/issues/2055

**Comment by etam** [comment]
I didn't notice "duplicate" label. I want to disagree. This is not a duplicate.

`gst-player.py` example, while also uses gstreamer, is not what I'm asking for. The example is an application running a gstreamer pipeline and feeds the data into it through `appsrc` element.

This feature request is about making streamlink an independent gstreamer element. Probably some of the code could be shared.
