### ISSUE TITLE
Feature Request: Proxy AES segments when using player-passthrough

### ISSUE THREAD

**Issue by andrewmackrodt** [streamlink/streamlink#2399]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Streamlink supports consuming HLS from many VOD providers. However, providers which require authentication do not work when using `--player-passthrough hls` as players do not have a valid session to fetch AES segment keys.

I would like an option that can be combined with `--player-passthrough hls` which will proxy requests for AES key segments through Streamlink. This should allow players such as VLC or a standard HTML5 player to still retrieve chunks from a CDN where there is typically no authentication (fast) yet still be able to decode and seek through streams. A handy feature when wishing to resume a long stream.

More specifically, I wish to use this with the `wwenetwork` plugin due to a couple of issues with their official solution, i.e. their Flash player does not properly support full-screen with non 16:9 monitors nor is there support for Linux.

Additionally, this could lead to some very nice integrations with custom Plex channels where once again, end users can improve upon library management that official services have no motivation to improve.

### Expected Behavior

Adding a new boolean option such as `--enable-hls-key-proxy` will make Streamlink serve a proxied `.m3u8` file which has been modified to rewrite requests for AES segments to itself.

```sh
streamlink --player-passthrough hls,http --enable-hls-key-proxy <url> [stream]
```

This should allow support for `--player-passthrough hls` with full seeking capabilities for VOD content from providers which require an authentication mechanism.

### Related Issues

- [HLS streaming does not give current time or total duration [#1616]](#1616)

**Comment by back-to** [comment]
> this could lead to some very nice integrations with custom Plex channels

there is also `--json` https://streamlink.github.io/cli.html#cmdoption-j

---

this seems **out of scope** for `--player-passthrough`
