### ISSUE TITLE
NPO plugin unable to open stream URL

### ISSUE THREAD

**Issue by joopmartens** [streamlink/streamlink#2400]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

NPO plugin unable to open stream URL.

streamlink http://www.npo.nl/live/npo-1
[cli][info] Found matching plugin npo for URL http://www.npo.nl/live/npo-1
error: Unable to open URL: http://ida.omroep.nl/app.php/LI_NL1_4188102 (500 Server Error: Internal Server Error for url: http://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=yes&token=2tap7477ib3kpqusr9t6gqs6s4)

### Expected / Actual behavior

Play stream
500 Server Error

### Reproduction steps / Explicit stream URLs to test

1. streamlink http://www.npo.nl/live/npo-1

### Logs

N/A

### Additional comments, screenshots, etc.

N/A

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
DRM

**Comment by beardypig** [comment]
Are there other streams that work? If not we should mark it as broken and consider removing it. If there are other streams that work then a better error message is needed for the ones that don’t :)

**Comment by joopmartens** [comment]
It seems that they completely removed the "old"API:
error: Unable to open URL: http://ida.omroep.nl/app.php/auth (410 Client Error: Gone for url: https://ida.omroep.nl/app.php/auth)

I'm afraid that no content from NPO is accessible anymore.
