### ISSUE TITLE
Stream ended, Closing currently open stream... for specific videos

### ISSUE THREAD

**Issue by mvrozanti** [streamlink/streamlink#2404]
## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.

### Description

Stream is cut off after a few seconds. I've read about this issue in this repo (#1563 and others), but there doesn't seem to be enough information so I'm gonna try my best:

### Expected / Actual behavior

Log error message if it's a fatal error or lag in the video if it's a buffering/network problem.
/
Player closes with very little debugging information, even with `-l debug --verbose-player` flags.

### Reproduction steps / Explicit stream URLs to test

`streamlink -l debug --verbose-player  https://www.youtube.com/watch\?v\=mnajoIRtkZ4 best -o /dev/null`

### Log output

```
[cli][debug] OS:         Linux-5.0.2-arch1-1-ARCH-x86_64-with-arch
[cli][debug] Python:     3.7.2
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=mnajoIRtkZ4
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: mnajoIRtkZ4
[plugin.youtube][debug] get_video_info - 1: Found data
[cli][info] Available streams: audio_mp4, audio_webm, 360p (worst), 720p (best)
[cli][info] Opening stream: 720p (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[download][null] Written 25.9 MB (3s @ 7.8 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

It's interesting that it's always a few videos that get cut off, everytime they're played. Maybe there's an identifiable reason for the video not being able to be played and it might need logging.

**Comment by back-to** [comment]
use this https://streamlink.github.io/cli.html#cmdoption-player-no-close

---

```
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

this means the stream was fully downloaded

**Comment by mvrozanti** [comment]
I see. Is there any way to detect the player has finished playing the selected video? Streamlink should close the player once the video has finished _playing_ and not when it's finished downloading.

**Comment by darkguy2008** [comment]
Same thing happened to me today on a live stream. What is the solution for this?
