### ISSUE TITLE
Teamliquid plugin best quality detector has an issue, Afreeca behaves properly under the same conditions

### ISSUE THREAD

**Issue by ptkovsky** [streamlink/streamlink#2407]
## Plugin Issue

Not sure if this is a plugin issue or not. Maybe I misunderstood something here. But guess it is.

### Description

Just wanted to check the stream real quick but was too lazy to copy the original afreeca stream link (in fact, this is why the appropriate plugin exists) so tried copying the teamliquid's one instead. It opened up but looked kind of wrong in terms of the quality. Later, tested the teamliquid plugin a little bit more, and noticed that it kept behaving kind of strange. It kept opening 540p stream as the `best` option, while 1080p 60fps was still available. My guess is that it happened because of the urls being embedded.

### Reproduction steps / Explicit stream URLs to test

1. try to open a stream with the specified commands in the log output, for example: `streamlink https://www.teamliquid.net/video/streams/byflash best`
2. observe the actual results

### Log output

Here is some of the actual output of `teamliquid` plugin that I was getting:

```
streamlink https://www.teamliquid.net/video/streams/byflash best
[cli][info] Found matching plugin teamliquid for URL https://www.teamliquid.net/video/streams/byflash
[plugin.teamliquid][info] Attempting to play streams from https://play.afreecatv.com/byflash
[cli][info] Available streams: original, sd (worst), hd (best)
[cli][info] Opening stream: hd (hls)
```

And here's the same stream output when playing it from the direct link, using `afreeca` plugin:

```
streamlink https://play.afreecatv.com/byflash best
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/byflash
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
```

### Additional comments, screenshots, etc.
Environment: guess it's irrelevant here and not platform dependent either, but this case was tested using Windows 7 Ultimate 32 bit, and the Streamlink version is current, 1.1.1.

The expected result: both commands should equally open the `best`, highest quality stream, in the case, playing at 1080p 60fps.

The actual result: when trying to play video using teamliquid url and invoking `teamliquid` plugin, the `best` video is falsely detected as `hd`, which, in the case, appears to be a 540p stream at 31fps.

`afreeca` plugin, though, behaves adequately, as it detects the `best` output as the `original` one, and the correct 1080p 60fps video starts playing.

**Comment by jacobmalmberg** [comment]
Thank you for this. It looks like an excellent bug report! I am busy with school but will give it a quick go this weekend and if I fail, will fix this in 2 months after school's out.

**Comment by back-to** [comment]
it is just the limitation of Streamlink if you embed a plugin into another with `self.session.streams(stream_url)`

it can't use plugin specified settings etc.
