### ISSUE TITLE
slow Download speeds using cmd ?

### ISSUE THREAD

**Issue by adwa21** [streamlink/streamlink#2409]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Hello guys 

I am trying to download from camtu be using  cmd with this command  ( I am using streamlink 1.0.0 ) 

`
streamlink -l debug --http-cookie session="mysession" --http-header referer="https://camtube.co" --http-header origin="https://camtube.co" "https://api.camtube.co/recordings/f55502c1-55ad-41a8-ba4f-8e848739afe1/manifest.m3u8" best -o "video.ts"`

### Expected / Actual behavior

I normally get around 2-4MBps download per second  However with CMD the speeds fluctuate and it's between 30 kbps - 1MB .  How can I increase the speed ?? thank you for your help .

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://streamlink.github.io/cli.html#cmdoption-hls-segment-threads
