### ISSUE TITLE
1.0.0 on Ubuntu 18.04.2 relies on a version of python3-pycountry that is not available in the package repo

### ISSUE THREAD

**Issue by Scefing** [streamlink/streamlink#2411]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I tried to install streamlink from the Ubuntu PPA, but could not because of the following error:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 streamlink : Depends: python3-streamlink (= 1.0.0+dfsg-1~bpo9+1~bintray1) but it is not going to be installed
```
This lead me to try to install `python3-steamlink` manually:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-streamlink : Depends: python3-pycountry (<= 1.15)
```
However, a version of `python3-pycountry` below 1.15 isn't available:
```
$ sudo apt-cache madison python3-pycountry
python3-pycountry | 17.5.14+ds1-0ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
python3-pycountry | 17.5.14+ds1-0ubuntu1 | http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages
```

### Expected / Actual behavior

I expected the dependencies to resolve correctly and allow me to install version `1.0.0` of streamlink.

### Reproduction steps / Explicit stream URLs to test
Try to install streamlink from the PPA on Ubuntu `18.04.2` (Bionic Beaver).

### Log output

```
This is an installation issue, a log wouldn't help.
```

### Additional comments, screenshots, etc.

I had to install `streamlink` version `0.10` instead from the Ubuntu main repository for Bionic.

**Comment by back-to** [comment]
> I tried to install streamlink from the Ubuntu PPA

No, you used the **Debian** PPA
https://bintray.com/package/release/amurzeau/streamlink-debian/streamlink

there is no 1.0.0 for the **Ubuntu** PPA 
http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/s/streamlink/


https://streamlink.github.io/install.html#linux-and-bsd

**Comment by Scefing** [comment]
Ugh, I shouldn't submit bug reports when I'm sick. Sorry!
