### ISSUE TITLE
HLSVariant not reloading variant playlist

### ISSUE THREAD

**Issue by zhenyahacker** [streamlink/streamlink#2412]
## Plugin Issue
I am not sure is it really an issue or it should be classified as feature request, so I will mark both.

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

I have an hls stream which has its own, not very straight-standart, behavour:
I have an **hlsvariant** link with constaint paid access key. I will call it "master playlist". URL address of master playlist is constant and does not change. I am allowed to request it as much as I want.
`http://someserver.com/channelid/paidkey.m3u8`

This master playlist contains hls variants (may be only one variant), and URL to this playlist contains session id. I will call it "variant playlist".
```
#EXTM3U
#EXT-X-STREAM-INF:CLOSED-CAPTIONS=NONE,RESOLUTION=1920x1080,FRAME-RATE=25.000,AVERAGE-BANDWIDTH=7204640,BANDWIDTH=9005800
http://streams1.someserver.com/paidkey/session/_sessionid_/securitytoken/_securitytoken_.m3u8
```

This variant playlist contains
```
#EXTM3U
#EXT-X-TARGETDURATION:8
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:275760
#EXT-X-PROGRAM-DATE-TIME:2019-04-07T21:37:01Z
#EXTINF:5.360,
http://streams1.someserver.com/paidkey/session/_anotherlongrandomstring_/securitytoken/_anotherlongrandomstring_.ts
#EXTINF:7.200,
http://streams1.someserver.com/paidkey/session_anotherlongrandomstring_/securitytoken/_anotherlongrandomstring_.ts
#EXTINF:6.320,
http://streams1.someserver.com/paidkey/session/_anotherlongrandomstring_/securitytoken/_anotherlongrandomstring_.ts
#EXTINF:6.560,
http://streams1.someserver.com/paidkey/session/_anotherlongrandomstring_/securitytoken/_anotherlongrandomstring_.ts
```

The problem is that variant playlist lives only 10 minutes, after that session expires and server starts to return 404. Variant playlist url is meant to be refreshed by requesting new master playlist and taking new variant playlist from it. Streamlink doesn`t try to do that, it makes some retries to reload variant playlist, and after several 404s thinks that stream is ended.

I propose to make a command to **hlsvariant** plugin to refresh variant playlist once per some time, like `--hls-variant-playlist-refresh-rate=300`. With such command applied streamlink every 5 minutes will forcefully reload master playlist, extract again a link to variant playlist, and replace it in running **hls** plugin. Hls chunk flow can be synched by handling EXT-X-MEDIA-SEQUENCE id in some way.

### Log output

https://gist.github.com/zhenyahacker/8930104f5aa8e2ff1f36534a6dba7f49

**Comment by back-to** [comment]
#2626
