### ISSUE TITLE
[SOLVED - Result commited and merge requested, but not properly integrated] Calling plugins from witthin plugins. 

### ISSUE THREAD

**Issue by dgoiko** [streamlink/streamlink#2413]
## Issue

- [ X] This is not a bug report, feature request, or plugin issue/request.
- [ X] I have read the contribution guidelines.

### Description

This is not an issue, it is a call for a little help developing.
I need to know how to call a plugin from within a plugin. I'm creating a plugin for Canal Sur, which is a simple http webpage with an iframe to youtubve which changes every few hours. There's only ONE link you youtube on the page, so the ideal plugin would be:

1.- Check if url matches
2.- Find YouTube URL in HTML body using very simple RegExp
3.- Execute built-in YouTube plugin on that extracted url to get and return the actual streams.

### Example URL

http://www.canalsur.es/tv_directo-1193.html

I'm attacking what I've got to far, however, it fails as soon as it tries to load the plugin.

```
from __future__ import print_function
import re

from streamlink.plugin import Plugin
from streamlink.plugins.youtube import YouTube


class CanalSur(Plugin):

    url_re = re.compile(r"(?:https?://)?(?:www\.)?canalsur\.es/tv_directo-.*\.html")
    match_youtube = re.compile(r"src=\"(?P<url>(?:https?://)?(?:www\.)?youtube.com/embed/live_stream\?channel=[^\"]*)\"")

    @classmethod
    def can_handle_url(cls, url):
        return cls.url_re.match(url) is not None

    def _get_streams(self):
        res = self.session.http.get(self.url)
        #print(res.text)
        m = self.match_youtube.search(res.text)
        if m:
            stream_url = m.group("url")
            #print(stream_url)
            ytPlugin = YouTube(stream_url)
            yield ytPlugin.streams()


__plugin__ = CanalSur
```

Excuse me for not having checked every existing plugin, I found another plugin which does the same I wanted to do, "DOMMUNE", so I inspired on them to solve my problem:

```
from __future__ import print_function
import re

from streamlink.plugin import Plugin

class CanalSur(Plugin):

    url_re = re.compile(r"(?:https?://)?(?:www\.)?canalsur\.es/tv_directo-.*\.html")
    match_youtube = re.compile(r"src=\"(?P<url>(?:https?://)?(?:www\.)?youtube.com/embed/live_stream\?channel=[^\"]*)\"")

    @classmethod
    def can_handle_url(cls, url):
        return cls.url_re.match(url) is not None

    def _get_streams(self):
        res = self.session.http.get(self.url)
        #print(res.text)
        m = self.match_youtube.search(res.text)
        if m:
            yt_url = m.group("url")
            print(yt_url)
            if yt_url:
                self.logger.debug("Deferring to YouTube plugin with URL: {0}".format(yt_url))
                return self.session.streams(yt_url)

__plugin__ = CanalSur
```

You have full permission to commit this as a plugin, I'm not used to python coding and I dont have the knowledge needed to add this to your integration tests and so on. I feel like the youtube regexp should be a bit more paramretrized so it only extracts the channel and so on, but I'm not sure about youtube's url policies, so I just take the full working url.
The matching against YT should be made against a specific html tag, not the entire body, but this actually works.

I made this in a rush, and it is my first working plugin. I tried to follow your plugin programming style, however, it is kinda obscure, so I had to follow existing's pluging style.

[This](https://github.com/streamlink/streamlink/pull/2415) is my pull request, but as I said, I'm almost sure it'll fail on every integration test because I didn't added the plugin anywhere, just pushed it to the plugins folder. If you tell me what needs to be done swith plugins I can do it myself.

**Comment by dgoiko** [comment]
shame on me, didn't check existing plugins for something similar. Editted my original question to reflect the solution

**Comment by dgoiko** [comment]
@bastimeyer I'm not used to github interface. Was it possible for me to add the question label the question label on the first place to avoid anoying contributors in following commits/questions? If so, how?
Pardon my ignorance :p

**Comment by bastimeyer** [comment]
Only accounts with special rights can set tags on an issue tracker on Github. This is for avoiding spam, as it's up to the project how tags are set and defined.

Regarding asking questions, this is totally fine here. Other projects have different rules, though.

You can however always close and re-open your own issues / pull requests. I've closed it for you, because you've changed the title to "SOLVED" and because the question was about creating a new plugin which you've already submitted in another pull request.
