### ISSUE TITLE
dlive.tv plugin request

### ISSUE THREAD

**Issue by jwc529** [streamlink/streamlink#2417]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
d-live is a live streaming platform that many twitch and youtube streamers are trying out recently after pewdiepie signed with them this week.  

### Example stream URLs

https://dlive.tv/ is the homepage
sample streams that are live now and might run 24/7:
1. ...https://dlive.tv/PewDiePie
2. ...https://dlive.tv/FearBumper76
3. ...https://dlive.tv/DoorLess_YT

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Erk-** [comment]
So as far as I can see it should not be a big problem supporting this site, but you have to extract json from the body of the html page, under the name `__APOLLO_STATE__` in that there is username, though it may be annoying to extract as it uses the username in the name of the entry in the json eg for PewDiePie it is: (extract)
```json
{
  "defaultClient": {
    "user:pdp": {
      "id": "user:pdp",
      "avatar": "https://images.prd.dlivecdn.com/avatar/6c1fccb3-5a6c-11e9-97a3-12567f05983b",
      "__typename": "User",
      "displayname": "PewDiePie",
      "partnerStatus": "VERIFIED_PARTNER",
      "username": "pdp",
```
So the username is pdp after that you will be able to get the page `https://live.prd.dlive.tv/hls/live/<username>.m3u8` for example `https://live.prd.dlive.tv/hls/live/pdp.m3u8` which looks something like this:
```m3u8
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="360p",NAME="360p",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=550000,CODECS="avc1.4d000a,mp4a.40.2",RESOLUTION=640x360,VIDEO="360p"
https://5g9s179kfgx9wn8tqwj9-cul47i.p5cdn.com/dlive/transcode-72-20/pdp/1555035117/360p/live.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="480p",NAME="480p",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1300000,CODECS="avc1.4d000a,mp4a.40.2",RESOLUTION=858x480,VIDEO="480p"
https://5g9s179kfgx9wn8tqwj9-cul47i.p5cdn.com/dlive/transcode-72-20/pdp/1555035117/480p/live.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="720p",NAME="720p",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2100000,CODECS="avc1.4d000a,mp4a.40.2",RESOLUTION=1280x720,VIDEO="720p"
https://5g9s179kfgx9wn8tqwj9-cul47i.p5cdn.com/dlive/transcode-72-20/pdp/1555035117/720p/live.m3u8
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="src",NAME="src",DEFAULT=YES,AUTOSELECT=YES,LANGUAGE="en"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4500000,CODECS="avc1.4d000a,mp4a.40.2",RESOLUTION=1920x1080,VIDEO="src"
https://5g9s179kfgx9wn8tqwj9-cul47i.p5cdn.com/dlive/transcode-72-20/pdp/1555035117/src/live.m3u8
```
which has all the information that you need to extract the formats.

**Comment by omen23** [comment]
hey there, when will the plugin get incorporated into the master branch? 
Regards

**Comment by skulblakka** [comment]
We have to wait until I fixed the plugin so it can be approved by back-to. However you can [sideload](https://streamlink.github.io/cli.html#sideloading-plugins) the [plugin](https://raw.githubusercontent.com/streamlink/streamlink/b59fe61f679b602f74a048db417e664ceea1f5f9/src/streamlink/plugins/dlive.py) to test it.
