### ISSUE TITLE
video mediaset 

### ISSUE THREAD

**Issue by Jigsaw10** [streamlink/streamlink#2418]
## Bug Report

[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-26281-557

### Description

the vision stops after a long time and you have to load it

### Reproduction steps / Explicit stream URLs to test

1. ...https://www.grandefratello.mediaset.it/diretta/?live=B1
2. ...https://www.mediasetplay.mediaset.it/diretta/italia1_cI1
3. ...https://www.mediasetplay.mediaset.it/diretta/grandefratello_cB1

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
give us some more details, what is your actual issue here?

**Comment by Jigsaw10** [comment]
Hi back-to

does not work

if I take the direct link it is immediately closed

can you give me a hand take the direct that is not closed

**Comment by Jigsaw10** [comment]
Back-to you have email.?

**Comment by back-to** [comment]
```
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-26281-557
Description

the vision stops after a long time and you have to load it
```

if you used the mpd url, it will expire after 4h.

but without any **debug logs** there is no way to tell what you are actually doing

**Comment by Jigsaw10** [comment]
yes I have an mpd link
is there no way to remedy this problem?

**Comment by back-to** [comment]
4h should be enough

also there are already some duplicate issues about something like this.
