### ISSUE TITLE
CPU Requirement for 720p?

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#2424]
## Bug Report

- [X ] This is a bug report and I have read the contribution guidelines.

### Description
Just trying to figure out if there is a CPU requirement.

I have PC that is a Single Core 2.4GHZ Vista 32-bit with streamlink.

It rips a 720p and before a 1080p YouTube Live Stream with rarely any issue.

I now am getting a 720P HLS Stream and most days it records just fine but other days, I get a bunch of "6.4MB" files instead of the 750MB or so expected file.

I am recording a stream that requires an SSL certificate, so not sure how to easily provide the link here as it's a private not public SSL key.
### Expected / Actual behavior

Just to record the stream as one piece and not multiple 6.4mb segments.

### Reproduction steps / Explicit stream URLs to test

1. ... Record a 720p HLS stream with or without extra threads and other HLS options
2. ...
3. ...

### Log output

```

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
- no logs
- no example URLs
- no example commands

not sure how you expect some help here,
probably some issue with a weird private hls stream
