### ISSUE TITLE
Reuters.tv Plugin

### ISSUE THREAD

**Issue by sebastiandoe5** [streamlink/streamlink#2427]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Hello there,

I think it would be useful to have Reuters TV (reuters.tv) as a channel services on Streamlink as they have some great live streams of events. It's run by the press company Reuters and it would be really useful to be able to see these from the command line. The links on the Example Stream URLs have probably expired by the time you're reading this, but some example streams are easily accessible by going to reuters.tv. It also has VoD, but as this Streamlink is meant for streams, I would understand if you didn't support that. Thanks for considering adding it, and thanks for your continued development.

### Example stream URLs

1. https://www.reuters.tv/l/PFyV/2019/04/15/migrants-walk-along-highway-in-mexico
2. https://www.reuters.tv/l/PFyC/2019/04/15/notre-dame-cathedral-on-fire-in-paris
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by my-password-is-password** [comment]
Did reuters.tv site change something that it work anymore with streamlink or is it just me?
