### ISSUE TITLE
Zattoo is starting to use widevine

### ISSUE THREAD

**Issue by devenator** [streamlink/streamlink#2429]
Zattoo is starting to use widevine (currently for HD only, not SD). Now, shockingly, i'm actually someone who DID read the guidelines, and noticed the

 "Any kind of streaming service that uses DRM protection" [will be rejected]-Rule.

So, i'm asking if it would be acceptable to add a generic-decryption-plugin-api that can be used by 3rd-party content decryption modules, or support for a thirdparty-library [not distributed in the streamlink-repo] directly in the zattoo-plugin. Kodi-dev just added such code, so they do not seem to have a problem with it: https://github.com/rbuehlma/pvr.zattoo/pull/44/commits/4a66803be9f5366a74bb447cdb8ba9e6dd4e49b9

If that's inacceptable, i think it would be good to add at least a cleartext-error-message in case someone tries to subscribe to a channel that uses widevine (to avoid people opeing $plugin-not-working-bugreports because someone added widevine)...?

If even TALKING about such things is not allowed, please delete this bug, or close it and i will edit the text away...

**Comment by back-to** [comment]
> Zattoo is starting to use widevine (currently for HD only, not SD).

And you got an example URL, Channel and **logs** for this?

---

Also they are not starting, they had widevine for a log time already.

---

> i think it would be good to add at least a cleartext-error-message

what is the current error?
