### ISSUE TITLE
Crunchyroll can't find 1080p streams

### ISSUE THREAD

**Issue by SirFireNewt** [streamlink/streamlink#243]
The current plugin seems to only find streams up to 720p.
However I tested the old plugin and it seems to be working again I tested the links I used in #70 and a few more but couldn't reproduce the issue with the old plugin.
More testing may be needed but it's more than likely safe to revert back.

**Comment by beardypig** [comment]
Yep, that's a bug... Not having accounts for all the subscription services makes it hard to test subscriber only content :) Should be fixed over in #249 :)

**Comment by SirFireNewt** [comment]
That fixes it thank you.
