### ISSUE TITLE
Zattoo streaming to file stops early

### ISSUE THREAD

**Issue by awj100** [streamlink/streamlink#2432]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

While streaming from Zattoo the stream records only 14m54s of a 1hr video/program. The video in question has been previously recorded in Zattoo and I'm now hoping to download this recording.  
  
In the browser console I can see my list of recordings being fetched, and this is the JSON for the program I'm attempting to download:

```
{
	"series_recording_eligible": true,
	"end": "2019-04-06T21:55:00Z",
	"level": "sd",
	"title": "Follow the Money",
	"cid": "bbc-four",
	"program_id": 158562144,
	"tv_series_id": 28167,
	"start": "2019-04-06T20:55:00Z",
	"image_url": "http://images.zattic.com/system/images/17c8/fc99/d35e/cc6c/bf60/format_480x360.jpg",
	"position": "2019-04-06T20:55:01Z",
	"partial": false,
	"image_token": "17c8fc99d35ecc6cbf60",
	"id": 160182057,
	"episode_title": null
}
```
  
I have copied the URL from the zattoo website:  
https://zattoo.com/watch/bbc-four/158562144-follow-the-money/160182057/1554584100000/1554587700000/196000
I can see that "158562144-follow-the-money" is an encoding of the `program_id` with the `title` attached. The next two numbers are a mystery to me (can't find them at all in the JSON) and that third number appears to be the number of milliseconds after the `start` property that the video should start playing.
  
  
However, using the following command and switches, I can see that the stream coming from Zattoo records around 14:54 (of a 1-hour recording) before stopping at the conclusion. If I use the same URL in the browser will play the entire recording ( _i.e._, more than 14m54s).

> streamlink "https://zattoo.com/watch/bbc-four/158562144-follow-the-money/160182057/1554584100000/1554587700000/199180" best --zattoo-email ----@----.-- --zattoo-password ----- -r "C:\Users\-----\ftm-s03e02.mkv"
  
  
Can anyone explain why the stream is not receiving the entire video, or suggest a correction to my above command? I have now tried it several times and always receive exactly the same downloaded data.

### Log output

```
[Streamlink for Windows v1.0.0 - Git f7ac894]
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/bbc-four/158562144-follow-the-money/160182057/1554584100000/1554587700000/199180
[cli][info] Available streams: 600k_alt (worst), 600k, 900k, 1500k (best)
[cli][info] Opening stream: 1500k (hls)
[download][ftm-s03e02.mkv] Written 920.8 MB (14m54s @ 1014.3 KB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows with ExitCode 0]
```

**Comment by back-to** [comment]
> I can see that the stream coming from Zattoo starts mid-way through the video and records around 14:54 (of a 1-hour recording)

> [download][ftm-s03e02.mkv] Written 920.8 MB (14m54s @ 1014.3 KB/s)

**14m54s** is the time the download took, not the time of the outputfile.

did you even open the output file?

**Comment by awj100** [comment]
Ah, ok. My mistake. My understanding was that the file would only be saved as it was being streamed/watched, and as the default cache isn't large I assumed it would take almost as long to stream as it takes to watch.
  
But now that I check the video file, yes, it's all there. What confused me when I previously checked was Zattoo's habit of starting recording 5 minutes early and 20 minutes after the program finishes, which, as it's a series, made the start and end of the video file appear as if they were in the middle of the stream.
  
Anyway, sorry for the confusion.
