### ISSUE TITLE
CElementTree causes exception when xml_parser is called in plugin

### ISSUE THREAD

**Issue by jairoxyz** [streamlink/streamlink#2435]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

When trying to call a plugin that parses XML with ElementTree, it breaks on Windows when calling the compiled version CElelementTree in utils_init_.py.

### Expected / Actual behavior

Stream should play again but exception is thrown.

### Reproduction steps / Explicit stream URLs to test

Test with http://www.rtve.es/directo/canal-24h

```
sl = Streamlink()
sl.set_option('http-headers', {"User-Agent": useragents.CHROME})
plugin = sl.resolve_url(url)
streams = plugin.streams()
stream = streams.get('best')
url = stream.url
```

### Log output

```
DEBUG: [StreamLink] Found matching plugin rtve for URL http://www.rtve.es/directo/canal-24h
DEBUG: Traceback (most recent call last):
DEBUG:   ".\streamlink\utils\__init__.py", line 95, in parse_xml
DEBUG:     tree = ET.fromstring(data)
DEBUG:   File "<string>", line 123, in XML
DEBUG: TypeError: 'NoneType' object is not callable
```

### Additional comments, screenshots, etc.
It can be fixed by commenting out the CElelementTree import in utils\__init__.py:
```
try:
    import xml.etree.cElementTree as ET
except ImportError:  # pragma: no cover
    import xml.etree.ElementTree as ET
```
to

```
import xml.etree.ElementTree as ET
```

As @back-to  found out, cElementTree seems like just an alias, which might be broken on Windows. See https://github.com/python/cpython/blob/3.7/Lib/xml/etree/cElementTree.py.
He recommends me to make a PR and request to have the CElelementTree imports removed, but I wonder if should also replace elementtree with  defusedxml (https://docs.python.org/3/library/xml.html#the-defusedxml-and-defusedexpat-packages)?

Cheers,

Jx-

**Comment by back-to** [comment]
> but I wonder if should also replace elementtree with defusedxml

same as https://github.com/streamlink/streamlink/pull/2425

adding more **3rd party dependencies** makes Streamlink **unnecessary harder** to repack on some OS

**Comment by jairoxyz** [comment]
I totally agree to trying to avoid 3rd party dependencies. Most of the xml parsing could be done with regex anyway. This defusedxml is a pure python lib like elementtree and just eliminates some of the major xml vulnerabilities but no speed gains, I believe. https://pypi.org/project/defusedxml/

**Comment by back-to** [comment]
> major xml vulnerabilities

shouldn't be important, don't use Streamlink with shady websites.
