### ISSUE TITLE
streamlink to pipe and then ffmpeg -c copy

### ISSUE THREAD

**Issue by TheFatal** [streamlink/streamlink#2436]
hi guys, im trying to rip my stream with streamlink and then send it to my local rtmp server by using
`streamlink https://www.twitch.tv/mytwitch best -O | ffmpeg -i pipe: -c copy -f flv rtmp://127.0.0.1/live`

im geting an error
 `error: Error when writing to output: [Errno 32] Broken pipe, exiting`

what am i doing wrong guys ?

**Comment by back-to** [comment]
Ref https://github.com/streamlink/streamlink/issues/1799
Ref https://github.com/streamlink/streamlink/issues/1799#issuecomment-397321312
Ref https://www.ffmpeg.org/contact.html#Forums

**Comment by johnthecracker** [comment]
Try this:

streamlink URL -O | ffmpeg -i pipe:0 -c copy -f flv rtmp://127.0.0.1/live

reference:

https://github.com/streamlink/streamlink/issues/791#issuecomment-294139953

**Comment by peditx** [comment]
streamlink https://www.twitch.tv/mytwitch best -O | ffmpeg -re -i pipe:0 -c:v libx264 -c:a aac -strict -2 -f flv rtmp://127.0.0.1/live

Worked for me and i think you can using it without any errors
