### ISSUE TITLE
Livestream: No playable streams found on this URL

### ISSUE THREAD

**Issue by mmehrle** [streamlink/streamlink#2439]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I am getting the an error playing a livestream.com URL. 

### Reproduction steps / Explicit stream URLs to test

Here's the command for recreating it:

streamlink https://livestream.com/accounts/16429256/events/4572869/videos/114993551/player best --loglevel debug

Disclaimer: This a URL I fished from an embedded page, where the stream just plays nicely. Also tried to simply copy/paste this URL into a browser:

https://livestream.com/accounts/16429256/events/4572869/videos/114993551/player

That also works. So this is something with streamlink.

### Log output

[cli][debug] OS:         macOS 10.14.4
[cli][debug] Python:     3.6.0
[cli][debug] Streamlink: 1.1.1+12.ge1829c7
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin livestream for URL https://livestream.com/accounts/16429256/events/4572869/videos/114993551/player
error: No playable streams found on this URL: https://livestream.com/accounts/16429256/events/4572869/videos/114993551/player

**Comment by Braunson** [comment]
I'm having the same error with a different livestream account.

**Comment by back-to** [comment]
there are not enough details,
but if you meant a VOD and not a Livestream they are not supported.

see https://streamlink.github.io/latest/plugin_matrix.html
