### ISSUE TITLE
urllib3

### ISSUE THREAD

**Issue by mcvons** [streamlink/streamlink#2446]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Have updated streamlink to 1.1.1 and this is the message i get:
requests 2.21.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25 which is incompatible.

How do i fix it? 

### Expected / Actual behavior

What i expect to happen is that once i did this install via easyinstall on mac osx i would get streamlink success as per always prior to this update.

### Reproduction steps / Explicit stream URLs to test

 

1. ... do ANY streamlink request 
2. ... see the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25 (/usr/local/lib/python2.7/site-packages/urllib3-1.25-py2.7.egg), Requirement.parse('urllib3<1.25,>=1.21.1'), set(['requests']))
```

3. ... nothing -

no idea how to fix this (pretty much a newb here)

Have checked and not seen this as a "known issue" - thank you

m.c.

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Not sure what exactly is going on here, but the dependency versions are not matching for some reason.

This seems to be related to Python 2.7. Same issue which I have described here a few minutes ago in a thread regarding Streamlink on Linux Mint 18.3
https://github.com/streamlink/streamlink-twitch-gui/issues/636#issuecomment-486317912

> no idea how to fix this

Please try to install Streamlink via homebrew
https://streamlink.github.io/install.html#macos
or pip while using python3
https://streamlink.github.io/install.html#source-code

**Comment by mcvons** [comment]
Thank you for checking this - i did in fact try homebrew and pip and got the same thing. WIll however try to rip everything out and reinstall again from scratch.

Thank you for beind so fast in the reply

**Comment by mcvons** [comment]
sorry for coming back to this - perhaps this is small issue now:

i have python three 
 $python returns:
Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

i then used pip that is using python3 to install streamlink following the above instructions 
have also restarted 

However, the install seems still to be using python 2.73 as per this traceback

So is there something i need to do (on osx) to uninstall anything or fix the set up so that it's using python 3? 

Thank you 

m.c.

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.25 (/usr/local/lib/python2.7/site-packages/urllib3-1.25-py2.7.egg), Requirement.parse('urllib3<1.25,>=1.21.1'), set(['requests']))

**Comment by skulblakka** [comment]
You mentioned you previously had streamlink installed via homebrew and pip. You should be able to remove streamlink from brew by running `brew uninstall streamlink` and from pip using `pip uninstall streamlink` 

Make sure you are uninstalling from python2 pip. If you are unsure do 
`python2 -m pip uninstall streamlink` instead. 

Also test if running `streamlink` return "command not found" or something along the lines to make sure that streamlink is no longer present on your system.

**Comment by mcvons** [comment]
Thank you skulblakka - it's now working! yay (but this string  streamlink https://www.ustream.tv/embed/12858195 best -o /Users/here/Desktop/c1-12Vid1.mpg) no longer seems to be storing vids from the stream...BUT THANK YOU THERe's progress!

**Comment by sg4e** [comment]
Uninstalling via `sudo python2 -m pip uninstall streamlink` and forcing python3 with
```sh
virtualenv -p /usr/bin/python3 py3env
source py3env/bin/activate
sudo pip install streamlink
```
"fixed" the issue for me. However, I still get this warning everything I run streamlink:
```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
```
which unfortunately does affect the related `streamlink-twitch-gui` project because it outputs
```
Error: Couldn't launch the stream.
Unexpected version check output
```
I deduce from this that `streamlink-twitch-gui` runs a version check by parsing the output of `streamlink --version` and the warning message botches the parsing. Running `streamlink` from console does launch the stream despite the warning. Hope this dependency issue can be sorted out :+1:

**Comment by Vrakfall** [comment]
I believe this all originates from [an issue with `python-requests`][1]. It doesn't support `python-urllib3` yet but the latter got pushed on most distros nonetheless. This resulted in a warning being output by all programs using the former (but not breaking them).

As said before, I also deduced `streamlink-twitch-gui` uses the text output of `streamlink` to deduce its version but also the available sub-streams (like `720p30`, `1080p60`,...), sees an error and doesn't try to go further even tho it's just a warning and `streamlink` still works as usual.

I think that even if the problem gets solved upstream, it would be best to try to proceed when encountering a warning and not an error and wait for a complete process stop from `streamlink` to consider an error or give it an amount of time before it gets timed out. The reason to handle it that way would make so if, in the future, another one of those "non-breaking" warning could happen again and this time it wouldn't break `streamlink-twitch-gui` by the time a fix is found upstream.

Another possibility is also to run `streamlink` while specifying to python no warning is wanted (with the `-W ignore` flag).

On a side note, here's a related [Archlinux's bug ticket about `python-requests`][2] on this matter.

[1]: https://github.com/kennethreitz/requests/issues/5065
[2]: https://bugs.archlinux.org/task/62592

**Comment by Odel** [comment]
Having this issue as well, just holding back urllib to 1.24 for now.  I agree with @Vrakfall, it would be nice if it was handling this better

**Comment by Vrakfall** [comment]
I must add that I wrote my previous comment thinking I was in the `streamlink-twitch-gui` repo and not just `streamlink`, sorry about that. Of course the handling I described was aimed at the former. Tho, I guess that can be alleviated by making changes in the latter.

**Comment by bastimeyer** [comment]
Closing... See https://github.com/streamlink/streamlink/issues/2448#issuecomment-493506676

----

@Vrakfall 
There is a reason why the Twitch GUI has a strict Streamlink output parser, especially in the validation phase. Ignoring warnings is not a good idea, but maybe an option could be added in the future for making python to suppress them. This wouldn't work on Windows, though, as it's using the single `streamlinkw` executable now, which doesn't accept python specific parameters.
