### ISSUE TITLE
Yahoo Finance

### ISSUE THREAD

**Issue by MaximVol** [streamlink/streamlink#2447]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

It'd be great if StreamLink will be able to obtain live streams of Yahoo Finance website.

### Example stream URLs

https://finance.yahoo.com/

**Comment by gravyboat** [comment]
This is missing quite a bit of information and I don't even see any live streams on the site, where are they?

**Comment by MaximVol** [comment]
Yahoo Finance does not have 24x7 broadcasting, it has active live streams during several hours in daytime only (USA ET timezone):

https://www.mediapost.com/publications/article/330186/yahoo-finance-expands-live-programming-lineup.html

But Yahoo Finance content is really unique and high-quality.

**Comment by back-to** [comment]
They also use Youtube, no plugin needed.

https://www.youtube.com/channel/UCEAZeUIeJs0IjQiqTCdVSIg/
