### ISSUE TITLE
Add chocolatey release to docs and release notes

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#245]
With the creation of a [chocolatey package](https://github.com/streamlink/streamlink/issues/244) this needs to be added to the docs and release notes.

**Comment by lawli3t** [comment]
I'm taking a look on this today

**Comment by scowalt** [comment]
Sure thing! Thanks for checking

**Comment by beardypig** [comment]
Closing this as #380 is merged, thanks @lawli3t :)
