### ISSUE TITLE
Failed to open segmemt / Failed to reload playlist limit retries

### ISSUE THREAD

**Issue by m1975michael** [streamlink/streamlink#2451]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description
I did look at a couple other posts that seemed similar but I didn't see a clear answer.

When the stream either ends or there is an network issue I receive several "FFailed to open segment" and or "Failed to reload playlist".
I have attempted to modify this command:
streamlink.exe VideoLink best  -o FileName

With:
streamlink.exe VideoLink best --hls-segment-attempts 1 --hls-playlist-reload-attempts 1 -o FileName

I still get the same result.  Is there different switches I should use or are these not working as expected.

### Expected / Actual behavior

I would expect after one segment/playlist error the program to terminate with the new command I tried.

### Reproduction steps / Explicit stream URLs to test
Connect to any stream and then disconnect your network connection.

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by LunarPenguin** [comment]
I have a script which uses streamlink and i also often get failed to reload playlist errors when the stream drops, only difference is i would like to either catch it as an exception or suppress it using the log-level.

**Comment by back-to** [comment]
#2198 #2626
