### ISSUE TITLE
Plugin for servustv (https://servus.com/tv)

### ISSUE THREAD

**Issue by jkirk** [streamlink/streamlink#2452]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

ServusTV is a TV station in Austria. The station contains news, documentaries, entertainment, culture, and sports. The main language is German.

There is a live stream and an media archive.

### Example stream URLs

1. https://www.servus.com/tv/jetzt-live/
2. https://www.servus.com/tv/videos/aa-1y7dknjdd2112/
3. https://www.servus.com/tv/videos/aa-1yma9r4952112/

### Additional comments, screenshots, etc.

There used to be a [plugin](https://github.com/streamlink/streamlink/blob/a6ceedc4e7bb1f17be888dc5ee36f19114e103f7/src/streamlink/plugins/servustv.py) but it stopped working and was disabled in the meanwhile. I tried to fix the issues in the given plugin, but failed so far. I hope someone with more skills can help me with that.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by jkirk** [comment]
If it helps, [youtube-dl](https://github.com/ytdl-org/youtube-dl/) has an extractor for it: [servus.py](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/servus.py).

**Comment by back-to** [comment]
**static** url for the livestream, a plugin is not needed

`streamlink https://rbmn-live.akamaized.net/hls/live/2002830/geoSTVDEweb/master.m3u8 best`

maybe geoblocked, not sure if there is still a 2nd AT stream or if they switched to only one stream.

**Comment by jkirk** [comment]
@back-to: Thx for the feedback and for providing the static link. 

A few things though:
* You provided the static link for the Servus TV Deutschland (Germany)
* How can I stream Servus TV (Austria)?
* How am I (read: a user) supposed to have found the link?

**Comment by bastimeyer** [comment]
@jkirk 
Open your browser's dev tools (F12), go to the "Network" tab and then load/refresh the website. Since you're expecting an HLS stream, you can filter the HTTP requests by "m3u8", which will give you a list of all playlist requests.

Try to look for the master playlist first, which should only be requested once at the beginning, as it contains a list of other playlist URLs. If there is no such request, you can get the URL of the most recently requested playlist, which should be the playlist of the HLS stream the browser is currently showing.

If you notice that the playlist requests don't include dynamic parameters and are static between different sessions, then no plugin is necessary and you can directly use that static URL as Streamlink's input.

Sometimes this doesn't work and you will have to add additional HTTP parameters, like a "User-Agent" or "Referer". But this doesn't seem to be the case here.

**Comment by jkirk** [comment]
@bastimeyer: Cool! Your description worked well! Thank you!
Shouldn't this be part of the documentation? (Maybe it already is, but I didn't find it?)

Now I also understand that a plugin is "not needed" for a static link, but wouldn't it be much more convenient for an user to let **streamlink** extract the static url for the livestream without doing it manually? I mean, extracting the stream url via the dev tools should be a "workaround" for streaming services which are not supported yet and should be used by plugin-contributors, but IMHO the end user should not have to go this path. But maybe I am just not fully aware of the scope of **streamlink**...

What do you, @back-to  and @bastimeyer, think?

**Comment by back-to** [comment]
> but wouldn't it be much more convenient for an user to let streamlink extract the static url for the livestream without doing it manually?

**sure**, but it also takes time to create a new plugin for streamlink
and if the url is static it is _basically wasted time_

for this special case here you would also need an Austrian proxy/vpn, which is also difficult to get.

---

> extracting the stream url via the dev tools should be a "workaround"

yes, but for static urls most of the time you can just find them somewhere on the internet without using the dev tool.

**DE example**

https://github.com/search?q=https%3A%2F%2Frbmn-live.akamaized.net%2Fhls%2Flive%2F2002830%2FgeoSTVDEweb%2Fmaster.m3u8&type=Code

you could also share the **AT** url for other users who also wants to get the livestream url.

**Comment by jkirk** [comment]
Ok. JFTR, the static link for the AT "servus.com/tv" stream is: https://rbmn-live.akamaized.net/hls/live/2002825/geoSTVATweb/master.m3u8

Do we have a *static*link collection file or is it ok to start one? (If you tell me where, I would be happy to create a PR for it).

Same goes for a FAQ-section to extract the static link.
