### ISSUE TITLE
TVplayer.com login failing

### ISSUE THREAD

**Issue by nicr4wks** [streamlink/streamlink#2456]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

As of yesterday (4/5/2019) tvplayer.com has been failing with "Failed to login" error.
I can login with my account OK directly to the tvplayer website.
I have tried creating a second account to verify it is not an account or user/pass issue.

### Reproduction steps / Explicit stream URLs to test

1. Run streamlink (streamlink "https://tvplayer.com/watch/clubland" best --tvplayer-email user@gmail.com --tvplayer-password password)
2. Check log output for "[plugin.tvplayer][warning] Failed to login as user@gmail.com"

### Log output

```
streamlink --loglevel debug "https://tvplayer.com/watch/clubland" best --tvplayer-email user@gmail.com --tvplayer-password password
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1+20.gc8ed1da
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/clubland
[cli][debug] Plugin specific arguments:
[cli][debug]  --tvplayer-email=user@gmail.com (email)
[cli][debug]  --tvplayer-password=******** (password)
[plugin.tvplayer][debug] Logging in as user@gmail.com
[plugin.tvplayer][warning] Failed to login as user@gmail.com
[plugin.tvplayer][debug] Got stream attributes: {'channel_id': '225'}
[plugin.tvplayer][debug] Missing 'resource' from stream attributes
[plugin.tvplayer][debug] Missing 'token' from stream attributes
error: No playable streams found on this URL: https://tvplayer.com/watch/clubland
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Tvplayer.com has now implemented reCAPCHA on the website login page.  Sadly, I think this has just killed the tvplayer plugin for streamlink. :(

**Comment by nicr4wks** [comment]
Well that's a bummer!

I've got it working again by pulling the cookie data from chrome and using --http-cookie on streamlink. Don't know how long until this will need to be refreshed but guess I'll find out.

**Comment by mkbloke** [comment]
Yes, it's a huge bummer.  :-(

I was wondering about using the cookie data, but didn't test it.  It is encouraging to hear that it's working for you.  I see that the cookies are set to expire at end of session in the browser, but as to how long you can really continue to use them I guess you will find out!

If it's currently working for you, my thoughts are that tvplayer.com has probably only implemented reCAPTCHA on the login web page and not elsewhere on the site.  If they had implemented it in the background elsewhere on the site, I would have thought streamlink would be scored as a bot by it and either get rejected or a request for a reCAPTCHA test to the user would be made.

**Comment by nicr4wks** [comment]
Thought I'd just post an update that 24hrs in the cookie is still working.

**Comment by chrisarnott86** [comment]
I found the same problem, what exactly was the cookie data that you used in the http-cookie argument. Inspecting my cookie data shows a number of parameters but I'm not sure what's needed. What was the exact command you used for a working stream?

**Comment by chrisarnott86** [comment]
I worked it out, it's only the `persistence-v2` value that seems to be required, so the additional parameter for the stream is `--http-cookie persistence-v2="ABC...123`, with the actual value taken from the cookie data. Hopefully this hack will continue to work...

**Comment by nicr4wks** [comment]
The cookie seems to expire every 3 or so weeks. PITA but you can just grab new one from the browser and add to streamlink command line.

**Comment by tmatthews5511** [comment]
It would be nice to have a little more documentation on the 'cookie' hack. I could not figure it out.

Since the BBC plugin has stopped working as well, this would be a nice workaround until the BBC plugin is fixed.

**Comment by chrisarnott86** [comment]
I can only advise with regards to Linux and Firefox, if you're on a different OS/browser you'd need to figure things out a bit yourself, although the general idea will be the same.

1. Browse to tvplayer and make sure you're logged in and test watching a live channel.
1. Go to main Firefox menu button -> Web Developer -> Storage inspector (or just Shift +F9)
1. Look in the presented cookie data for line with name `persistencce-v2`
1. Double click on the 'valiue' box for that line to highlight it then copy
1. Paste into the command line, as I mentioned above, so using `--http-cookie persistence-v2="ABC...123"`, where the value is what was just copied
1. Run command!

I've also created a script that extracts the data automatically from the cookies database (requires sqlite3 package installed on Ubuntu). It uses a temporary copy of the database because the original file is locked if the browser is open. The script is here https://gist.github.com/chrisarnott86/3e55ca7edf39a358f9375964539d77fb

**Comment by tmatthews5511** [comment]
@chrisarnott86 ... you're a real star. Thanks so much. At my next geeking out  session, I'll give it a go.

**Comment by mkbloke** [comment]
It looks like tvplayer.com has changed its login system again.  You now get taken to:
```
https://v1-auth.tvplayer-cdn.com/login?responseType=redirect&redirectUri=https%3A%2F%2Ftvplayer.com%2Flogin&lang=en
```
For credentials, then there's a redirect back to tvplayer.com upon success with an access token included:
```
POST: HTTP/2.0 302 Found
content-type: text/html; charset=UTF-8
location: https://tvplayer.com/login?access_token=someLongTokenString
```

**Comment by mkbloke** [comment]
Login patch:

[tvplayer.py.patch.txt](https://github.com/streamlink/streamlink/files/4200862/tvplayer.py.patch.txt)

Now goes as far as:
```
$ streamlink/bin/streamlink -l debug tvplayer.com/watch/bbcone
[cli][debug] OS:         Linux-4.5.1-040501-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     2.7.12
[cli][debug] Streamlink: 1.3.1+11.g7f4f8f0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/bbcone
[cli][debug] Plugin specific arguments:
[cli][debug]  --tvplayer-email=******** (email)
[cli][debug]  --tvplayer-password=******** (password)
[plugin.tvplayer][debug] Logging in as ********
[plugin.tvplayer][debug] Got stream attributes: {'channel_id': None}
[plugin.tvplayer][debug] Missing 'resource' from stream attributes
[plugin.tvplayer][debug] Missing 'token' from stream attributes
error: No playable streams found on this URL: tvplayer.com/watch/bbcone
```

**Comment by tmatthews5511** [comment]
I applied the patch, and then I reinstalled streamlink (using git, python
setup.py install).

I am getting this error:

[cli][info] Found matching plugin tvplayer for URL
https://tvplayer.com/watch/bbcone
error: No playable streams found on this URL:
https://tvplayer.com/watch/bbcone

I have updated the cookie in the script which was working fine in Firefox.

Version = streamlink 1.3.1+11.g7f4f8f0.dirty

ta, t.

**Comment by tmatthews5511** [comment]
Just one more note:

streamlink -l debug tvplayer.com/watch/bbcone
[cli][debug] OS:
Linux-4.15.0-74-generic-x86_64-with-LinuxMint-19.2-tina
[cli][debug] Python:     2.7.17
[cli][debug] Streamlink: 1.3.1+11.g7f4f8f0.dirty
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin tvplayer for URL tvplayer.com/watch/bbcone
[plugin.tvplayer][debug] Got stream attributes: {'channel_id': None}
[plugin.tvplayer][debug] Missing 'resource' from stream attributes
[plugin.tvplayer][debug] Missing 'token' from stream attributes
error: No playable streams found on this URL: tvplayer.com/watch/bbcone

**Comment by nicr4wks** [comment]
@tmatthews5511 this is not fixed, @mkbloke made good progress but it's not a complete patch.

Also over my head i'm afraid.

It seems the video is now stored:
https://live.tvplayer.com/live/bbctwo/3/prog_index.m3u8
https://live.tvplayer.com/live/bbctwo/3/3_2020-02-14_06-55-47_241871.ts

Authentication is required to access this, not sure if cookie/referrer based.

Everytime a new chunk is loaded a URL similar to the following is also accessed, not sure if this is coincidental or required to stream to continue:

https://infinity-c8.youboranqs01.com/ping?diffTime=5001&bitrate=-1&throughput=-1&droppedFrames=0&playrate=1&cdnDownloadedTraffic=8989032&p2pDownloadedTraffic=0&uploadTraffic=0&timemark=1581663369331&system=alchimie&sessionRoot=U_20001429_9kaj44una7kp2ayw_1581663329314&pingTime=5&code=U_20001429_9kaj44una7kp2ayw_1581663329314
 
The entire website now seems to be geoblocked, previously it was only the m3u8 & ts chunks that were blocked outside of UK.

**Comment by mkbloke** [comment]
I'm currently making some headway with extracting the right stream attributes and using those to get access to the M3U8 resources to build the list of available qualities for selection.

**Comment by mkbloke** [comment]
OK, I think this is all working again...

If anybody wants to test it, you can grab the whole tvplayer.py script that I've submitted via a PR from:

https://raw.githubusercontent.com/streamlink/streamlink/b5fe4acf8a098f0b0c07cfadf10e8d907ed96e2f/src/streamlink/plugins/tvplayer.py

**Comment by tmatthews5511** [comment]
Firstly, thanks for the great work, Ian. I wish I could be a python guru as
well.

And it is working very well for me. I have been watching BBC 1 on tvplayer
for the last half hour.

I'll keep abusing it and trying to break it.

**Comment by nicr4wks** [comment]
Nice work!

Confirmed working as well.

**Comment by mkbloke** [comment]
Great, thanks for the feedback.
