### ISSUE TITLE
TV1 Plugin - new player being used

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2457]
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description
 TV1 won't start, because they're using a different player now.

### Expected / Actual behavior

Should have worked?

### Reproduction steps / Explicit stream URLs to test

1. streamlink http://tv1channel.org/ best
2. ? ? ?
3. profit

**Comment by back-to** [comment]
static url

```
streamlink "https://stream.bittubeapp.com/bittubelive/tv1channebg/playlist.m3u8" best --http-no-ssl-verify
```
