### ISSUE TITLE
How to make a splitting broadcast into pieces of video?

### ISSUE THREAD

**Issue by danilshik** [streamlink/streamlink#2459]
### Description

How can you make the division of video into pieces during the broadcast?

### Expected / Actual behavior

While the broadcast is going to divide the entire traslation into segments of the video in order to start assembling these pieces while the broadcast is in progress. Ie expected sections of the video, which follow each other on the timeline.
/
Video pieces are made of 5 minutes each (my segment), but they don’t follow each other. Of course, I understood that it would take some time to turn on streamlink and search for a channel / broadcast. But I did not expect that the next segment will capture the previous segment, and now between these segments it is necessary to synchronize at some point in the broadcast.
Is there any function in streamlink that would divide the broadcasts into sections?

### CMD Code
```
:loop
set day=%DATE:~0,2%
set month=%DATE:~3,2%
set year=%DATE:~6,4%
set hour=%TIME:~0,2%
set minute=%TIME:~3,2%
set second=%TIME:~6,2%
set YYYYMMDD=%hour%_%minute%_%second%_%day%_%month%_%year%
streamlink --hls-live-edge 99999 --hls-segment-threads 10 --ringbuffer-size 1024M --hls-duration 00:05:00 -o %YYYYMMDD%.ts https://www.twitch.tv/makatao best
goto loop

```

**Comment by back-to** [comment]
you can use **FFMPEG** https://ffmpeg.org/ with segment options

Streamlink is the wrong Software for this

```
streamlink URL best -O | ffmpeg -i pipe:0 <YOUR FFMPEG COMMAND>
```
https://streamlink.github.io/cli.html#cmdoption-stdout
