### ISSUE TITLE
"failed to create process" when launching Streamlink in Chocolatey test environment

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink#246]
Ran into this trying to validate the `streamlink-twitch-gui` Chocolatey package. The [Chocolatey test environment](https://github.com/chocolatey/chocolatey-test-environment) is a Windows Server 2012 virtual machine that allows package maintainers to test packages in an isolated environment.

After running the windows installer in this environment, trying to execute `streamlink.exe` gives the following error:
```
failed to create process
```

As a work-around, I tried running `Python\python.exe bin\streamlink-script.py`. This gave me the following error:
![image](https://cloud.githubusercontent.com/assets/1100550/20870286/1f050284-ba3a-11e6-84ad-ab43f17680c1.png)

Some quick research led me to believe that the VC++ 2015 redistributable might be necessary to run streamlink. After installing this redistributable and restarting the virtual machine, I get a different error running `Python\python.exe bin\streamlink-script.py`:
```
C:\Program Files (x86)\Streamlink>Python\python.exe bin\streamlink-script.py
Failed to load plugin viagame:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "pkgs\streamlink\plugins\viagame.py", line 7, in <module>
    from streamlink.plugin.api.support_plugin import viasat
  File "pkgs\streamlink\plugin\api\__init__.py", line 27, in __getattr__
    return load_support_plugin(name)
  File "pkgs\streamlink\plugin\api\support_plugin.py", line 39, in load_support_
plugin
    raise ImportError("No module named '{0}'".format(name))
ImportError: No module named 'viasat'


usage: streamlink-script.py [OPTIONS] [URL] [STREAM]

Use -h/--help to see the available options or read the manual at http://docs.streamlink.io/
```

I'm not sure why this is happening. Perhaps someone more knowledgeable knows what's going on here. If you need to get a local repro going, the [Chocolatey test environment](https://github.com/chocolatey/chocolatey-test-environment#requirements) is pretty easy to set up and is cross platform.

**Comment by Vangelis66** [comment]
@scowalt wrote: 

> Some quick research led me to believe that 
> the VC++ 2015 redistributable 
> might be necessary to run streamlink.

Not streamlink (the script) per se, but it's needed 
on the system because the embedded Windows version 
of Python 3.5.2 (used in the installer) was built 
with VC14 (Visual Studio 2015 compiler). 
This requirement isn't mentioned in the 
[releases](https://github.com/streamlink/streamlink/releases) page, however the author of the 
[windows portable installation generator ](https://github.com/streamlink/streamlink-portable)
mentions this as a requirement for his app 
in [this](https://github.com/streamlink/streamlink/issues/86#issue-182928541) closed issue... 

As for your "viagame.py" issue, sorry, 
I have no clue, a dev will have to drop by... :wink:

**Comment by RosadinTV** [comment]
@Vangelis66 Yes, Python 3.5.2 requirements are:
-Windows Vista SP2 or later
-Visual C++ Redistributable 2015 (Not required in Windows 10 or later)
https://www.microsoft.com/en-US/download/details.aspx?id=48145
@scowalt Can you paste here the complete console log?
Also it seems like viagame.com is deprecated .. the website redirects to tv.eslgaming.com

**Comment by scowalt** [comment]
Full error log (will edit original post as well):
```
C:\Program Files (x86)\Streamlink>bin\streamlink.exe
failed to create process.
```
```
C:\Program Files (x86)\Streamlink>Python\python.exe bin\streamlink-script.py
Failed to load plugin viagame:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "pkgs\streamlink\plugins\viagame.py", line 7, in <module>
    from streamlink.plugin.api.support_plugin import viasat
  File "pkgs\streamlink\plugin\api\__init__.py", line 27, in __getattr__
    return load_support_plugin(name)
  File "pkgs\streamlink\plugin\api\support_plugin.py", line 39, in load_support_
plugin
    raise ImportError("No module named '{0}'".format(name))
ImportError: No module named 'viasat'


usage: streamlink-script.py [OPTIONS] [URL] [STREAM]

Use -h/--help to see the available options or read the manual at http://docs.streamlink.io/
```

Minimally, I'll need to add Visual C++ Redistributable 2015 as a dependency of Streamlink in the Chocolatey package. Would be nice to figure out this other issue as well. My goal is to get this fully working in the VM to help validate future packages.

**Comment by beardypig** [comment]
Did you try reinstalling streamlink after installing the VC runtime? 

We should consider adding the runtime installer to the main installer, shouldn't be a problem...

**Comment by scowalt** [comment]
That did the trick!

I'll create a bug on the the streamlink-chocolatey repo to add `vcredist2015` as a dependency, so everyone installing through Chocolatey will have this work automatically.

I'll leave this bug open, as we should consider adding the VC redistributable to the main installer.

**Comment by ceceita** [comment]
Hi all , 
I got the same problem tryng to install it on a winxp sp3 , visual studio 2015 runtime installed ..
Reading RosadinTV post i saw that Vista SP2 is required for Python 3.5 , and Python site say "if you require Window XP support then please install Python 3.4 ".
What to do ? is there a workaround ? are you going to support win XP ?

I was using livestreamer twitch guy to stream on that old machine and all was working ..
Thanks and sry for my english ..

**Comment by RosadinTV** [comment]
@ceceita Sorry but i think XP support is not planned on the Project.
Maybe later i will release a unofficial build compatible with XP (also probably unstable)
PS: Just curious, what is your native language?

**Comment by scowalt** [comment]
@ceceita I would open a separate bug regarding XP sp3 support so it can be separately prioritized and investigated.

I'm closing this bug out. In PR #250 we determined this issue was caused by not having the VC++ runtime (and the relevant Windows updates) installed on the machine. https://github.com/streamlink/streamlink-chocolatey/issues/1 will cover adding the dependency to the chocolatey package.

For anyone in the future running into this issue, I would try to following steps:

1. Uninstall Streamlink
2. Install the Visual C++ 2015 redistributable
3. Restart the machine
4. Install Streamlink

If those steps don't solve your problem, then I would imagine something else has gone wrong and you should file a separate bug.

**Comment by ceceita** [comment]
@RosadinTV  it's italian

@scowalt  since streamlink twitch guy will not support Xp  , and reading that in february twitch will change the api making old version not compatibile , i think is better not to open the bug if there are no people using it , it's just a "end of support" .
I keep using old version till they work , then i will try to change to a different operating system like linux , the pc is very old and used only for music or twitch streaming.

**Comment by RosadinTV** [comment]
@ceceita Cool, i speak Spanish but my ancestors were Italians.
In relation to Windows XP it's a pity but it will get less and less support.
This is mainly because Microsoft ended the support (Although it is also logical since it is 15 years old OS) 
As you say, in your case (i mean with a very old pc) using Linux is a great alternative.

**Comment by Vangelis66** [comment]
@ceceita

I have no clue whether it would work at all, 
no clue either whether it will even work with 
streamlink-twitch-gui (I don't use it...), but it 
wouldn't hurt to try, I suppose...

1. Install the last XP compatible full blown Python 3.4.3 package
2. Try to install streamlink via pip
`pip install streamlink`

Even if streamlink-twitch-gui doesn't work in this scenario, 
you could still stream twitch (to an XP compatible player) 
via the CLI...

**Comment by RosadinTV** [comment]
@Vangelis66 You are right, Streamlink is supposed to support Python 2.7>
I always forget the simplest things, but fortunately you are here ❤️
