### ISSUE TITLE
Feature request: Be able to change stream on the fly

### ISSUE THREAD

**Issue by ZeRaler** [streamlink/streamlink#2462]
## Issue

- [x] This is a feature request and I have read the contribution guidelines.

### Description
It would be nice to be able to change stream url on the fly by any kind of IPC/RPC.
I use streamlink to be able to watch stream on TV that else dont support main media. I'm using the `--player-external-http` option on my NAS and connect TV on it. It works fine but each time I want to change stream I have to stop streamlink, disconnect TV and restart again.

### Expected behavior

- start streamlink, connect player.
- later, send new url, player connection still alive and working on new stream.

### Note

I dont know what whould be the better IPC/RPC to do the job. I dont know if streamlink use currently one.

**Comment by back-to** [comment]
you could try https://github.com/back-to/liveproxy it's basically doing what you want.

https://liveproxy.github.io/url.html#tutorial

one custom URL per Streamlink command (you can create a playlist with different channels)

Example

```
http://127.0.0.1:53422/base64/c3RyZWFtbGluayBodHRwczovL3d3dy55b3V0dWJlLmNvbS91c2VyL2ZyYW5jZTI0IGJlc3Q=/
```

https://liveproxy.github.io/url.html#base64

---

> IPC/RPC

this is probably out of scope for Streamlink

**Comment by bastimeyer** [comment]
I'm closing this, as it's pretty much out of scope of Streamlink.
@back-to's liveproxy seems like a good solution for that.

If one wants to add stream-switching logic to Streamlink, they can submit a pull request.
