### ISSUE TITLE
Streamlink not processing specific httpstream

### ISSUE THREAD

**Issue by dgoiko** [streamlink/streamlink#2464]
### Description

I found an online mp3 file which streamlink is not able to reproduce, not even using httpstream://. It is in a shoutcast server, however, as far I know it is just mp3 over http, is not that the same than the httpstream Streamlink supports? SHOUTCast does things lie counting listeners and so, but for the client it is the same, isn't it??

Those are url examples which fail (; is important, if you dont use it it doesnt work on browser either):

```
http://188.93.73.98:8118/;
http://188.93.73.98:8118/;stream.mp3
```

I'm using the latest streamlink release (1.1.1), and have tried all listed protocols (rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// hds:// akamaihd:// hls:// dash:// httpstream://)

### Expected / Actual behavior

Streamlink should be able to find live streams and play it in vlc by using httpstream:// protocol handler.

### Reproduction steps / Explicit stream URLs to test

1. execute the following command:
`streamlink httpstream://http://188.93.73.98:8118/; live`

You can test that the url is actually working by inserting it into your broser:
`http://188.93.73.98:8118/;`

### Log output

```
[cli][info] Found matching plugin http for URL httpstream://http://188.93.73.98:8118/;
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('http://188.93.73.98:8118/;')> (Could not open stream: Unable to open URL: http://188.93.73.98:8118/; (('Connection aborted.', BadStatusLine('ICY 200 OK\r\n'))))
error: Could not open stream <HTTPStream('http://188.93.73.98:8118/;')>, tried 1 times, exiting
```

### Additional comments, screenshots, etc.

**EDIT:**

I've been digging a bit into shoutcast, and it seems not to be very different to normal http mp3 streams:

[Python Shoutcast player](https://www.reddit.com/r/Python/comments/971uuw/created_a_small_program_to_play_streaming_audio/)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> SHOUTcast D.N.A.S. - Copyright Nullsoft Inc. 1998-2004

the software seems pretty old, **this is basically the issue here.**

---

it return an invalid http code for **python**

it returns `ICY 200 OK` but it should be `HTTP/1.0 200 OK`

https://github.com/python/cpython/blob/7e200e0763f5b71c199aaf98bd5588f291585619/Lib/http/client.py#L286-L288

---

there is a **python3** monkey patch

https://stackoverflow.com/questions/4247248/record-streaming-and-saving-internet-radio-in-python/41338150#41338150
