### ISSUE TITLE
HEVC wont play

### ISSUE THREAD

**Issue by savskii** [streamlink/streamlink#2465]
Hello, I have some HEVC stream which won;t play 

FFMPEG looks like this : 
Program 1
    Metadata:
      variant_bitrate : 12000000
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      major_brand     : M4A
      minor_version   : 0
      compatible_brands: hev1iso6iso4iso5dash
      comment         : en
    Stream #0:2: Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 11996 kb/s, 59.94 fps, 59.94 tbr, 1000k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 12000000
      major_brand     : iso6
      minor_version   : 0
      compatible_brands: hvc1iso6iso4iso5dash

In Streamlink my command is like: 

streamlink "hls://http://127.0.0.1:4482/test/4K/playlist.m3u8" best --loglevel debug --player-external-http --player-external-http-port 54406

Debug dont show any errors but stream wont play either

[cli][info] Got HTTP request from VLC/3.0.6 LibVLC/3.0.6
[cli][info] Opening stream: 2160p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 311225090; Last Sequence: 311225099
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 311225097; End Sequence: None
[stream.hls][debug] Adding segment 311225097 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 311225098 to queue
[stream.hls][debug] Adding segment 311225099 to queue
[stream.hls][debug] First Sequence: 311225091; Last Sequence: 311225100
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 311225098; End Sequence: None
[stream.hls][debug] Adding segment 311225098 to queue
[stream.hls][debug] Adding segment 311225099 to queue
[stream.hls][debug] Adding segment 311225100 to queue
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-727-804 -i /tmp/ffmpeg-727-841 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-727-804
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-727-841
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Download of segment 311225098 complete
[stream.hls][debug] Download of segment 311225099 complete
[stream.hls][debug] Download of segment 311225100 complete
[stream.hls][debug] Download of segment 311225097 complete
[stream.hls][debug] Download of segment 311225098 complete
[stream.hls][debug] Download of segment 311225099 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 311225100 to queue
[stream.hls][debug] Adding segment 311225101 to queue
[stream.hls][debug] Reloading playlist

Could i get some help please

Kind Regards

**Comment by bastimeyer** [comment]
Try a different player, eg. MPV.

As you can see, Streamlink doesn't re-encode the stream(s) and just remuxes them (hls-multi stream):
`ffmpeg -nostats -y -i /tmp/ffmpeg-727-804 -i /tmp/ffmpeg-727-841 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1`

And since you're using an input from `127.0.0.1`, nobody will be able to help you here, as we don't have access to it.
