### ISSUE TITLE
Issue with mpv and --title

### ISSUE THREAD

**Issue by krathalan** [streamlink/streamlink#2467]
### Description
mpv-specific property expansion in the window title doesn't work. When using the official example from the Streamlink man pages to try and get ${mpv-version} in the title: 
`streamlink --player mpv --title "\${{mpv-version}}" https://example.stream/url quality`

mpv shows a literal "${mpv-version}" string in the title, not the properly expanded mpv version.

### Expected / Actual behavior
Streamlink should be able to show mpv-specific variables in the title of an mpv window.

### Reproduction steps / Explicit stream URLs to test
1. Install mpv.
2. Try and use property expansion for mpv in the Streamlink --title argument, for example with the command `streamlink --player mpv --title "\${{mpv-version}}" https://twitch.tv/overwatchleague best`.

### Log output
Recommended usage as per Streamlink man pages: `streamlink --player mpv --title "\${{mpv-version}}" https://twitch.tv/overwatchleague best` https://gist.github.com/krathalan/7f348cc6723881674c21a1ba894605e1

### Additional comments, screenshots, etc.
I noticed with `--loglevel debug`, Streamlink was opening mpv with `mpv --title $${mpv-version}`. Streamlink should be opening mpv with `mpv --title ${mpv-version}` -- only one $. 

No matter what combination of characters I tried, I could not get Streamlink to open mpv with `mpv --title ${mpv-version}`, the proper sequence of characters -- only one $, and `mpv-version` surrounded by braces.

Combinations I tried:

Command | Gist
--- | ---
`streamlink --player mpv --title "\${{mpv-version}}" https://twitch.tv/overwatchleague best` | https://gist.github.com/krathalan/7f348cc6723881674c21a1ba894605e1
`streamlink --loglevel debug --player mpv --title "\${mpv-version}" https://twitch.tv/overwatchleague best` | https://gist.github.com/krathalan/fd9bda18ffe2c3911f031c62b3ee62e2
`streamlink --loglevel debug --player mpv --title "{{mpv-version}}" https://twitch.tv/overwatchleague best` | https://gist.github.com/krathalan/c49e41b3413c9dafde2872aac4e98b62

**Comment by back-to** [comment]
you might need to escape it, if you are using it with a terminal

like `\${{mpv-version}}` to `\\\${{mpv-version}}`

**Comment by krathalan** [comment]
Thanks for the quick reply, that fixed it! That should be added to the documentation.

**Comment by bastimeyer** [comment]
There's a difference between single and double quotes in shell syntax:
https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

If you're using double quotes, then your command line shell will escape the dollar sign before passing the parameter content to Streamlink. If you're however using single quotes, then it won't be escaped by your command line shell and Streamlink will receive the correct character sequence for performing its own escape logic:
https://github.com/streamlink/streamlink/blame/1.1.1/src/streamlink_cli/output.py#L134-L169

`--title '\${{mpv-version}}'`
or
`--title "\\\${{mpv-version}}"`
