### ISSUE TITLE
can we have a zip archive of streamlink in addition to the .exe file?

### ISSUE THREAD

**Issue by jacobs0n** [streamlink/streamlink#247]
livestreamer has this option. mainly for users of laptops/pcs with no admin rights.

**Comment by RosadinTV** [comment]
@jacobs0n What do you mean?
Something like this?
https://github.com/chrippa/livestreamer/releases/download/v1.12.2/livestreamer-v1.12.2-win32.zip

**Comment by jacobs0n** [comment]
@RosadinTV  yes. :)

**Comment by RosadinTV** [comment]
@jacobs0n 
You can download this:
https://github.com/streamlink/streamlink-portable/archive/master.zip
Extract and open "Streamlink for Windows.exe" located inside the "Streamlink for Windows (Compiled)" folder, with this you can build a portable build of Streamlink (based on the latest commit) with no admin rights required.

**Comment by gravyboat** [comment]
I'm going to close this since @RosadinTV has provided a solution!
