### ISSUE TITLE
Youtube plugin: Can Video auto-replaying event a few minutes after live event is over, be disabled?

### ISSUE THREAD

**Issue by DavidOfOregon** [streamlink/streamlink#2472]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

Python 3 application loop launches streamlink/omxplayer every 10 seconds in an attempt to acquire a live stream at a fixed URL.  When successful, streamlink/omxplayer will play the entire streaming event, and end as expected, when the live event is over.  The loop resumes as noted, indefinitely.
However, typically within 5 minutes after playing a Live Stream event on Youtube, the event will start auto-playing again from the beginning.  As a developer, I would like to know if this can be disabled.
There usually is a minimum of about 39 hours between Live Stream events, in this use case.

### Expected / Actual behavior
Expected behavior:
 -- is that the event will not begin auto-replaying after the Live Stream has ended and/or that a switch, (or?) is provided to override this behavior?

### Reproduction steps / Explicit stream URLs to test
1. Test Url: https://youtube.com/user/ApostolicFaithHQ/live
1b.  Preferably, a Url to a Youtube ingestion site where the stream can be started and stopped manually for testing purposes.

2. Streamlink config file: (/home/pi/.config/streamlink/config)
      player=omxplayer
      verbose-player
      retry-streams=10
      retry-open=30
      hls-segment-threads=4
      fifo

3. Python 3 snippet:
while True:
    sl_omx = Popen( \
            ['streamlink', \
            'https://youtube.com/user/ApostolicFaithHQ/live', \
            'best', \
            ], \
            stdout = PIPE, \
            stderr = STDOUT, \
            universal_newlines = True \
    )
    sl_omx.communicate()
    print('Live Event has ended.')
    time.sleep(10)

### Logs
No logs because there are no errors and no problems. Streamlink/omxplayer seems to be working normally (my assumption).

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Since this isn't an issue with Streamlink I'm going to close this. We don't provide support for third party scripts. You may however wish to explore exit codes and potentially acting on those.

**Comment by DavidOfOregon** [comment]
TY Grayboat for confirming that Streamlink cannot prevent a completed Live Stream from re-starting.  This confirms that I will need to start figuring out what to do to fix this problem for my clients.  Take care!
