### ISSUE TITLE
How do I get DASH Manifest url of YouTube  using Python ?

### ISSUE THREAD

**Issue by 20183300** [streamlink/streamlink#2474]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.

### Description

I want to get MPD, but I'm not familiar with Streamlink for the first time.
How do I get YouTube's DASH Manifest using python?

import streamlink
streams = streamlink.streams("https://www.youtube.com/watch?v=ITxH111QQ")
url=streams.stream.mpd.url
print(url)

This is code that does not work.
Please let me know if it is not enough for me.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> How do I get YouTube's DASH Manifest using python?

Streamlink does not use any DASH Manifests from YouTube
