### ISSUE TITLE
Error: No playable streams found on this URL

### ISSUE THREAD

**Issue by Rzeznik1** [streamlink/streamlink#2475]
How to fix?
![streamlink](https://user-images.githubusercontent.com/33949523/58190104-16d0f680-7cbc-11e9-929a-586d3665a3ee.png)

**Comment by Rzeznik1** [comment]
[url=https://postimg.cc/Cd1Fb2Gk][img]https://i.postimg.cc/Cd1Fb2Gk/streamlink.png[/img][/url]

**Comment by Rzeznik1** [comment]
[https://postimg.cc/Cd1Fb2Gk](url)

**Comment by Rzeznik1** [comment]
[](https://postimg.cc/Cd1Fb2Gk)

**Comment by Rzeznik1** [comment]
![streamlink](https://user-images.githubusercontent.com/33949523/58190087-0e78bb80-7cbc-11e9-99ca-71ec19972d84.png)

**Comment by gravyboat** [comment]
I can't duplicate this. It's working fine for me. Are you sure you're on the latest version of Streamlink?

**Comment by budiarno** [comment]
I also face the same problem with the same kind of error:

```
streamlink https://www.youtube.com/watch?v=MP5QUuLDIAE
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MP5QUuLDIAE
error: No playable streams found on this URL: https://www.youtube.com/watch?v=MP5QUuLDIAE
```

**Comment by budiarno** [comment]
Sorry, after reinstall to the latest version, everything just runs fine:

> streamlink -l debug https://www.youtube.com/watch?v=MP5QUuLDIAE
> Failed to load plugin filmon:
>   File "/usr/local/lib/python2.7/dist-packages/streamlink-1.1.1+33.gee10883-py2.7.egg/streamlink/plugins/filmon.py", line 223
>     <<<<<<< HEAD
>                ^
> IndentationError: expected an indented block
> 
> [cli][debug] OS:         Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
> [cli][debug] Python:     2.7.12
> [cli][debug] Streamlink: 1.1.1+33.gee10883
> [cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.47.0)
> [cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MP5QUuLDIAE
> [plugin.youtube][debug] Video ID from URL
> [plugin.youtube][debug] Using video ID: MP5QUuLDIAE
> [plugin.youtube][debug] get_video_info - 1: Found data
> [plugin.youtube][debug] This video is live.
> [utils.l10n][debug] Language code: en_US
> Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)

**Comment by beardypig** [comment]
Looks like this have been solved. Closing. Please reopen if I'm wrong.

**Comment by andmer** [comment]
having this problem now

streamlink -l debug https://www.youtube.com/watch?v=YfduDq5gLnE
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YfduDq5gLnE
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: YfduDq5gLnE
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=YfduDq5gLnE

**Comment by andmer** [comment]
any clues?

**Comment by gravyboat** [comment]
There's already a new issue for this here: https://github.com/streamlink/streamlink/issues/2750 Locking.
