### ISSUE TITLE
Eleven Sports (Taiwan)

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#2477]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Before anyone groans too quickly at the resurfacing of this particular website and plugin, there's been a fundamental change in how this website operates!

Streams for Eleven Sports were previously provided by Neulion and the plugin was subsequently removed due to a DMCA takedown notice (#1493).

However the Taiwan version of Eleven Sports has announced their old website is being deprecated in favour of a new website www.tw-elevensports.com, which having looked at it, now seems to be using streams from vascreative.com instead of the neulion servers. I haven't been able to verify whether or not this is the case for other Eleven Sports sites due to geo-blocking.

### Example stream URLs

1. http://www.tw-elevensports.com/vod.html (VOD streams)
2. http://www.tw-elevensports.com/onNow.html (Live streams)

### Additional comments, screenshots, etc.

The live streams and VOD all seem to be dynamically loaded into a placeholder div using this [javascript](http://www.tw-elevensports.com/js/onNow.js?v=4), but I haven't been able to get my head around the sources.

The Taiwan site is geoblocked, but they're currently giving new signups a 30 day free subscription.

**Comment by ryanjgillies** [comment]
I had a few more minutes spare to investigate some more, so I started digging a little more. Oddly whilst before the streams seemed to coming from vascreative.com, they're not coming via hinet.net instead (a local ISP and cloud provider).

The streams previously came in small mp4 chunks, but they're now showing as ts files.

**Eleven Sports 1**

Example stream addresses:
https://esnc-vas.cdn.hinet.net/tsft/ch01/video2.m3u8
https://esnc-vas.cdn.hinet.net/tsft/ch01/aud1.m3u8
https://esnc-vas.cdn.hinet.net/tsft/ch01/video2-1466.ts
https://esnc-vas.cdn.hinet.net/tsft/ch01/aud1-1760.ts

```
**General Headers:**
Request URL: https://esnc-vas.cdn.hinet.net/tsft/ch01/video2.m3u8
Request Method: GET
Status Code: 200 
Remote Address: 202.39.67.5:443
Referrer Policy: no-referrer-when-downgrade

**Response Headers:**
accept-ranges: bytes
access-control-allow-origin: http://www.tw-elevensports.com
content-length: 9867
content-type: application/vnd.apple.mpegurl
date: Wed, 29 May 2019 07:11:37 GMT
server: HiNetCDN/1808
status: 200
vary: Origin
x-cache: -

**Request Headers:**
Provisional headers are shown
Origin: http://www.tw-elevensports.com
Referer: http://www.tw-elevensports.com/onNow.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
```
**Eleven Sports 2**
https://esnc-vas.cdn.hinet.net/tsft/ch02/video3.m3u8
https://esnc-vas.cdn.hinet.net/tsft/ch02/aud1.m3u8
https://esnc-vas.cdn.hinet.net/tsft/ch02/video3-2011.ts
https://esnc-vas.cdn.hinet.net/tsft/ch02/aud1-1746.ts
```
**General:**
Request URL: https://esnc-vas.cdn.hinet.net/tsft/ch02/video2.m3u8
Request Method: GET
Status Code: 200 
Remote Address: 210.242.210.67:443
Referrer Policy: no-referrer-when-downgrade

**Response Headers:**
accept-ranges: bytes
access-control-allow-origin: http://www.tw-elevensports.com
content-length: 9867
content-type: application/vnd.apple.mpegurl
date: Wed, 29 May 2019 07:14:13 GMT
server: HiNetCDN/1808
status: 200
vary: Origin
x-cache: -

**Request Headers:**
Provisional headers are shown
Origin: http://www.tw-elevensports.com
Referer: http://www.tw-elevensports.com/onNow.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
```

Eleven Sports Prime is currently not broadcasting so I can't get any info on that one.

I tried checking out the cookies, but the Chrome inspector isn't showing any cookies issued by the tw-elevensports.com domain, only google.com.

However local storage is showing the following:
```
    "UUid": "d86c19f9-1bc6-4493-88f9-a4e2a735ebed"
```

And session storage is showing the following:
```
    "programStartTime": "15:30",
    "programCategory": "ELEVEN SPORTS 1",
    "programTitle": "World Archery 2019 Magazine HL_Compound",
    "memberId": "5824",
    "loginType": "1",
    "onNowMenuId": "3",
    "lang": "en-US",
    "userEmail": "ryan@notmyrealemail.com",
    "epgContentId": "1",
    "onNowUuid": "31460075-c5c7-4b24-8134-122f4aa3c76d",
    "sxt-user": "8:live:1a941e10e0ab06b5",
    "fullName": "Ryan Gillies",
    "onNowContentId": "1",
    "onNowProgramName": "World Archery 2019 Magazine HL_Compound",
    "programEndTime": "16:00",
    "memberLevelId": "2",
    "platform": "WEB",
    "channelSelect": "0"
```

Apart from the obvious changes to program specific data, I've noticed that channelSelect changes to 0, 1, 2 respectively when selecting Eleven Sports 1, Eleven Sports 2 and Eleven Sports Prime.

**Comment by ryanjgillies** [comment]
A slightly odd development, I gave the following two commands a bash...
```
streamlink "hls://https://esnc-vas.cdn.hinet.net/tsft/ch01/video2.m3u8" best
streamlink "hls://https://esnc-vas.cdn.hinet.net/tsft/ch02/video2.m3u8" best
```
...and it straight up gave me the streams in question, albeit without audio and only in 480p. I don't know if those URLs are geoblocked or not, maybe someone else could give them a try for me...?

**Comment by ryanjgillies** [comment]
I've updated the title, as it seems that Eleven Sports in Taiwan is the only version of the website that is changing stream providers. I used my VPN to check the other [regional websites](http://elevensports.com/territories/) and they all still seem to be with neulion/endeavour (the company that purchased neulion) with no indication that they plan to change.

**Comment by bastimeyer** [comment]
> I used my VPN to check the other [regional websites](http://elevensports.com/territories/) and they all still seem to be with neulion/endeavour (the company that purchased neulion) with no indication that they plan to change.

That's a no-go then. We won't implement plugins which will lead to another false DMCA takedown notice which we can't and won't fight (as it would require Github to take the repo down for that time).

**Comment by ryanjgillies** [comment]
To clarify, its not the neulion powered sites I'm interested in, only the Taiwan version which is now powered by www.vascreative.com - did the DMCA takedown notice not come from Neulion and relate to all of their streamed content (UFCTV, NBA, Eleven Sports, etc)? So presumably a different provider would be ok?

Having gone back to look at the streams again, the streams have reverted back to vascreative.com from hinet. HOWEVER the Hinet streams are still working perfectly fine, and appear to use variable resolution based on connection speed - on a faster connection I can usually get 720p or 1080p streams.

The audio is still missing, but I also note for every `video2.m3u8` stream there is a corresponding `aud1.m3u8` and `aud2.m3u8` stream (presumably for the Chinese and English audio languages. Can streamlink accept both streams somehow to give me video and audio?

**Comment by back-to** [comment]
> but I also note for every video2.m3u8 stream there is a corresponding aud1.m3u8 and aud2.m3u8 stream

search for `master.m3u8` or `playlist.m3u8`

---

closing,
I don't think there is somebody with **an account** and the required location **to even look into this** plugin request.

Not really worth to have this issue open and let people think this will be added.
