### ISSUE TITLE
Younow: Cant play VODs

### ISSUE THREAD

**Issue by timofonic** [streamlink/streamlink#248]
streamlink -p mpv https://www.younow.com/kirateachings/147611664/33750459/1e2d787d/b
[cli][info] Found matching plugin younow for URL https://www.younow.com/kirateachings/147611664/33750459/1e2d787d/b
User offline or invalid
error: No streams found on this URL: https://www.younow.com/kirateachings/147611664/33750459/1e2d787d/b

Why?

**Comment by gravyboat** [comment]
Seems to be that it doesn't see a stream on that URL, are you sure it's correct?

**Comment by stevek123** [comment]
It's a VoD/highlight, but streamlink only supports live streams.

**Comment by back-to** [comment]
they use the same url for different highlights,
this is not the best way for streamlink.

It would be very ugly and this is not really worth the effort.

Closing
