### ISSUE TITLE
France TV doesn't work anymore

### ISSUE THREAD

**Issue by novazur972** [streamlink/streamlink#2483]
$ streamlink -l debug http://www.france.tv/france-2/direct.html
[cli][debug] OS:         Linux-4.20.17-gentoo-x86_64-Intel-R-_Core-TM-_i5-8600K_CPU_@_3.60GHz-with-gentoo-2.6
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
error: No playable streams found on this URL: http://www.france.tv/france-2/direct.html

I used it sucessfully several monthes ago.

**Comment by karlo2105** [comment]
Please update to the latest streamlink build.

**Comment by novazur972** [comment]
$ streamlink -l debug http://www.france.tv/france-2/direct.html
[cli][debug] OS:         Linux-4.20.17-gentoo-x86_64-Intel-R-_Core-TM-_i5-8600K_CPU_@_3.60GHz-with-gentoo-2.6
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin pluzz for URL http://www.france.tv/france-2/direct.html
error: No playable streams found on this URL: http://www.france.tv/france-2/direct.html

**Comment by novazur972** [comment]
last build on gentoo

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.0.0

You are not using the latest version of Streamlink.
