### ISSUE TITLE
Commandline timestamps or current download duration?

### ISSUE THREAD

**Issue by Abalieno** [streamlink/streamlink#2484]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Until today I was using youtube-dl, but this time I needed to restart a stream from the beginning and that program would only idle at the end of the stream.

I tried streamlink today and it all works fine after I reformatted some options and used "--hls-live-restart"

So all is working fine. The problem is that youtube-dl was showing the time of the video during its download, something like this:
frame=1224428 fps= 78 q=-1.0 Lsize=14977407kB time=06:48:08.50 bitrate=5010.3kbits/s speed=1.57x

There's the timestamp in the middle, so I could check that and manually stop the download when it reached a certain point.

Streamlink in the command prompt only tells me how much data it has written. I can VAGUELY estimate the amount of time through the size of the file, but isn't there something more precise available?

I read the help pages and I see that I can give a proper starting time (for hls streams, with a start offset), something that wasn't possible in youtube-dl, so I wonder if there's a way to set a proper end time as well.

So I'm looking either a way to print the timestamps while downloading, so I can stop it manually when desired, or a way to set an end time.

**Comment by gravyboat** [comment]
[`--hls-duration`](https://streamlink.github.io/cli.html#cmdoption-hls-duration) is the closest you're going to get to that. Past those HLS options we don't support anything and don't plan to do to.

**Comment by Abalieno** [comment]
Well, it seems to work well.

I thought the command would work only while watching the stream through a player, but it works fine when downloading.
