### ISSUE TITLE
Httpstream fails to download next segment of longer videos

### ISSUE THREAD

**Issue by Alucard28** [streamlink/streamlink#2486]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I use Streamlink to extract httpstreams from filehosters using external http player (Openload for example), however when trying to extract longer videos, like 40 minutes+ it freezes after the first segment, always around 1:40-2:00, with shorter videos around 20 minutes however it works just fine. 
Using player-passthrough fixes the issue, but I want to use the external http player because I want to watch these videos on a device that doesn't support any media player besides the browsers integrated mp4 player. I also noticed that it occurs more often with HD videos (720p+) while lower quality videos of the same length work just fine again.

The network log of the browser shows that it downloads the first segment but then fails, it's not an issue with the device I'm using as I have tested it on multiple modern browsers with the same issue, so I'm guessing the issue is related to streamlink.

### Expected / Actual behavior

Expected to stream all segments of longer httpstreams normally just like how it works with shorter videos.

### Reproduction steps / Explicit stream URLs to test

1. Grab a direct file link from a filehoster (preferably a video over 40 minutes in length and in HD)
2. httpstream it using streamlink over external http player
3. Open it in any browser that supports mp4, check network log

### Log output

log shows nothing besides:

[cli][info] Opening stream: live (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Writing stream to player

after which nothing happens anymore.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Does it work if you use a regular player or save the file to disk, or only fails when using the http player?

**Comment by Alucard28** [comment]
It only fails when using the http player.

**Comment by back-to** [comment]
> extract httpstreams from filehosters using external http player (Openload for example)

you got an example?

**Comment by beardypig** [comment]
It might be trying to seek to the end of the file to get the metadata, or something. Can you post the full debug log, what my look insignificant might be useful for us to debug the issue.
