### ISSUE TITLE
Plugin ine found, but not playable stream 

### ISSUE THREAD

**Issue by m4rek22** [streamlink/streamlink#2489]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

I am using INE plugin, but I cant download video that needs an INE account, as it says: 

streamlink "https://streaming.ine.com...../"
[cli][info] Found matching plugin ine ...
error: No playable streams found on this URL

When I try to download video that is free (you dont need and account to watch it) it works. So is it possible to somewhere set login credentials or how can I download a video that need account ? (I have account)

### Reproduction steps / Explicit stream URLs to test

As you need an account to try, I will not add URL here.

### Log output

streamlink "https://streaming.ine.com...../"
[cli][info] Found matching plugin ine ...
error: No playable streams found on this URL

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
You won't be able to download those videos, the plugin doesn't support logging in. It's only able to play publicly available videos.

**Comment by m4rek22** [comment]
I found solution with cookie.

**Comment by xflyboy** [comment]
Please advice what is the valid cookie to be used.
