### ISSUE TITLE
[Plugin Request] ATV Peru

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#2494]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
ATV (known as Andina de Televisión), is a southamerican, Peruvian television network founded in 1959 and relaunched in 1983.

### Example stream URLs
https://www.atv.pe/envivo   (there are two channels 'ATV' and 'ATV +' 

https://dqsz3cincv704.cloudfront.net/pe/smil:canal_atv.smil/playlist.m3u8
https://dqsz3cincv704.cloudfront.net/pe/smil:atv_mas.smil/playlist.m3u8

### Additional comments, screenshots, etc.
doesn't seem to be geoblocked in Europe.

**Comment by malvinas2** [comment]
After reading the documentation ([https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly](https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly)), it works perfectly via: 

streamlink --player "C:\Program Files\VideoLAN\VLC\vlc.exe" "hlsvariant://dqsz3cincv704.cloudfront.net/pe/smil:canal_atv.smil/playlist.m3u8" best 
respectively: 
streamlink --player "C:\Program Files\VideoLAN\VLC\vlc.exe" "hlsvariant://dqsz3cincv704.cloudfront.net/pe/smil:atv_mas.smil/playlist.m3u8" best

**Comment by malvinas2** [comment]
The last two months the links have been
`https://pe-atv-atv-live.ned.media/atv/smil:atv.smil/playlist.m3u8`
respectively
`https://pe-atv-atv-mas-live.ned.media/atv/smil:atv-mas.smil/playlist.m3u8`
and could be opened using the hlsvariant-argument. 
But now they introduced some kind of token: 
`https://pe-atv-atv-live.ned.media/atv/smil:atv.smil/playlist.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNTY1OTAzMjk4LCJzZXNzaW9uIjoiNzcuMjIuMTQxLjIyNSIsIndoaXRlbGlzdCI6WyI3Ny4yMi4xNDEuMjI1Il19LCJzaWduYXR1cmUiOiI1NWQ1YWQwZGM4NDliMTRmOGUwYzZkMTU4NjZiOGMzZTYyZmFjY2MwIn0=`
so that streamlink doesn't work without a corresponding plugin.

**Comment by johnthecracker** [comment]
This works with my everyday script.

https://www.atv.pe/envivo

```
C:\>streamlink.exe --player=mpv.exe --http-no-ssl-verify --stream-sorting-excludes ">720p" hls://"https://pe-atv-atv-mas-live.ned.media/atv/smil:atv-mas.smil/playlist.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNTY1OTA4MDkwLCJzZXNzaW9uIjoiODYuMTgyLjU0LjE2NCIsIndoaXRlbGlzdCI6WyI4Ni4xODIuNTQuMTY0Il19LCJzaWduYXR1cmUiOiI3MGE3Mjg1OGZmNjBhYWMzNjYyODcyZjg3YjllYzJkNjJkNWY3MmM4In0=" best,best-unfiltered
[cli][info] Found matching plugin hls for URL hls://https://pe-atv-atv-mas-live.ned.media/atv/smil:atv-mas.smil/playlist.m3u8?iut=eyJwYXJhbXMiOnsiZXhwIjoxNTY1OTA4MDkwLCJzZXNzaW9uIjoiODYuMTgyLjU0LjE2NCIsIndoaXRlbGlzdCI6WyI4Ni4xODIuNTQuMTY0Il19LCJzaWduYXR1cmUiOiI3MGE3Mjg1OGZmNjBhYWMzNjYyODcyZjg3YjllYzJkNjJkNWY3MmM4In0=
[cli][info] Available streams: 160p (worst), 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: mpv.exe
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by johnthecracker** [comment]
some kind of token:

https://www.base64decode.org/

```
eyJwYXJhbXMiOnsiZXhwIjoxNTY1OTA4MDkwLCJzZXNzaW9uIjoiODYuMTgyLjU0LjE2NCIsIndoaXRlbGlzdCI6WyI4Ni4xODIuNTQuMTY0Il19LCJzaWduYXR1cmUiOiI3MGE3Mjg1OGZmNjBhYWMzNjYyODcyZjg3YjllYzJkNjJkNWY3MmM4In0=
```

```
{"params":{"exp":1565908090,"session":"85.181.54.124","whitelist":["85.181.54.124"]},"signature":"70a72858ff60aac3662872f87b9ec2d62d5f72c8"}

```

http://www.onlineconversion.com/unix_time.htm

UNIX TimeStamp: 

1565908090

Thu, 15 Aug 2019 22:28:10 GMT


Playlist is good for 24 hours for one IP address, even if it is fake ( 85.181.54.124 ).
