### ISSUE TITLE
[Plugin Request] TV Pública Argentina

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#2495]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
Televisión Pública Argentina (Argentine Public Television, abbreviated TPA) is a publicly owned Argentine television network, the national public broadcaster. It began broadcasting in 1951, when LR3 Radio Belgrano Television channel 7 in Buenos Aires, its key station and the first television station in the country, signed on the air.

Until a few days ago a live-stream was available via youtube, but they changed it and are now transmitting on their own website. 

### Example stream URLs
https://www.tvpublica.com.ar/
http://chunks01.tvpublica.com.ar/streams/BJQRNMF6b.m3u8
https://chunks01.tvpublica.com.ar/video/BJQRNMF6b_480/index.m3u8

### Additional comments, screenshots, etc.
Shouldn't be geoblocked at all.

**Comment by malvinas2** [comment]
well, it is geoblocked most of the times... 

`streamlink --player "C:\Program Files\VideoLAN\VLC\vlc.exe" "hlsvariant://chunks01.tvpublica.com.ar/streams/BJQRNMF6b.m3u8" best ` results in the following error message: 
```
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://vody
-auth.tvpublica.com.ar/server01/BJQRNMF6b_1080/54864639000.key (403 Client Error
: Forbidden for url: https://vody-auth.tvpublica.com.ar/server01/BJQRNMF6b_1080/
54864639000.key)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://chunks01.tvpubli
ca.com.ar/video/BJQRNMF6b_1080/index.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://chunks01.tvpublica.com.ar/video
/BJQRNMF6b_1080/index.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by beardypig** [comment]
Seems like it back on YouTube? https://www.youtube.com/watch?v=8XCKNdLEzas

**Comment by malvinas2** [comment]
They are indeed back on YouTube, but some programs are not shown on YouTube due to legal restrictions (e.g. 'Festival de Cine Argentino').  It only concerns a handful of programs, so I don't know if it is worth the effort. 
Personally I would like to understand what is behind their 'protective measures', this time they seem to having invest a considerable effort (?).

**Comment by beardypig** [comment]
Can you point me to where the live stream on the website is? I could only see a YouTube popup when I click "Vivo".

**Comment by malvinas2** [comment]
You're right. Several weeks ago there was some kind of co-existence between the YouTube-channel and their own stream (most of the time both broadcasted the same content).

**Comment by back-to** [comment]
https://api.tvpublica.com.ar/wp-json/acf/v3/streaming?slug=streamings-sitio-web

```json
[
  {
    "id": 1207,
    "acf": {
      "Streamings": [
        {
          "titulo": "Televisión Pública",
          "iframe_url": "https://www.youtube.com/embed/8XCKNdLEzas?&autoplay=1",
          "activo": false
        },
        {
          "titulo": "Televisión Pública",
          "iframe_url": "https://vmf.edge-apps.net/embed/live.php?streamname=c7live01-20034&autoplay=true",
          "activo": true
        },
        {
          "titulo": "Serenata a Cafayate",
          "iframe_url": "https://www.youtube.com/embed/3SE1fmeKIQg",
          "activo": false
        },
        {
          "titulo": "Fiesta Provincial del Río",
          "iframe_url": "https://www.youtube.com/embed/LajQImeU60I",
          "activo": false
        }
      ],
      "desplegado": false
    }
  }
]
```

even with `"activo": false` the Youtube URL is online
https://www.youtube.com/channel/UCs231K71Bnu5295_x0MB5Pg

closing, as a new plugin is not needed with a working Youtube URL.
