### ISSUE TITLE
USTVnow plugin stopped working

### ISSUE THREAD

**Issue by devenator** [streamlink/streamlink#2498]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

USTVnow plugin stopped working; it reports "invalid station code" / empty list of Available Stations

### Log output

-- start without station code --
[cli][debug] OS:         Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.8
[cli][debug] Streamlink: 1.1.1+28.gd655cbd
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin ustvnow for URL http://watch.ustvnow.com/watch/
[cli][debug] Plugin specific arguments:
[cli][debug]  --ustvnow-username=******** (username)
[cli][debug]  --ustvnow-password=******** (password)
[plugin.ustvnow][debug] CSRF: None
[plugin.ustvnow][error] Station code not provided, use --ustvnow-station-code.
[plugin.ustvnow][info] Available stations are: 
 
error: No playable streams found on this URL: http://watch.ustvnow.com/watch/
-- stop --

-- start with station code --
[cli][debug] OS:         Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.8
[cli][debug] Streamlink: 1.1.1+28.gd655cbd
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin ustvnow for URL http://watch.ustvnow.com/watch/whtm
[cli][debug] Plugin specific arguments:
[cli][debug]  --ustvnow-username=******** (username)
[cli][debug]  --ustvnow-password=******** (password)
[plugin.ustvnow][debug] CSRF: None
[plugin.ustvnow][error] Invalid station-code: whtm
error: No playable streams found on this URL: http://watch.ustvnow.com/watch/whtm
-- stop --

## Additional Information
They seem to have changed the urls, on watch.* i'm getting a not-available-in-your-region-error, but i.e. https://www.ustvnow.com/live/cwwpix/-53 seems to work

**Comment by beardypig** [comment]
They completely changed the website layout - look much better now. But will require a significant rewrite to make it work again.
