### ISSUE TITLE
France 2

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2499]
Hello

Well this is not really a bug report or a plugin issue. It's more me asking for information. 
For some days I have issue with that stream and I noticed some "no stat" thingy that I d never seen before, I m wondering what it means

![3ef4489b59181bc4d36b264e959b4464](https://user-images.githubusercontent.com/7072524/59329520-bdc31400-8cf7-11e9-8b22-be9993dfce8e.png)

**Comment by campones** [comment]
maybe it's more a case to be asked at ffmpeg forum I d reckon

**Comment by bastimeyer** [comment]
This is the ffmpeg child process for muxing the audio and video streams of the input into one single output stream. See here:
https://github.com/streamlink/streamlink/blob/1.1.1/src/streamlink/stream/ffmpegmux.py#L103-L121

**Comment by campones** [comment]
I see ,thanks

however I came to look at it because many times, the stream has no audio anymore, which never happened before. this is especially weird as I m using streamlink along this plugin for quite a long time now

**Comment by bastimeyer** [comment]
> the stream has no audio anymore

Not true, the output stream does have audio. I've tested it with my french proxy server and checked multiple stream qualities.

You seem to be piping Streamlink's output into another ffmpeg process where you are re-encoding the audio, remuxing it into FLV and serving it via rtmp. Whatever you're doing here (not even sure if what you are doing it legal), it's the cause of your issue and not Streamlink's.

```
$ streamlink --version
streamlink 1.1.1+3.g27f75bf
$ streamlink \
  --http-proxy socks5://localhost:1920 \
  --https-proxy socks5://localhost:1920 \
  --stdout \
  --loglevel none \
  https://www.france.tv/france-2/direct.html \
  best \
  | ffprobe -v error -show_format -show_streams -print_format json - \
  | jq
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "Main",
      "codec_type": "video",
      "codec_time_base": "1/50",
      "codec_tag_string": "[27][0][0][0]",
      "codec_tag": "0x001b",
      "width": 1280,
      "height": 720,
      "coded_width": 1280,
      "coded_height": 720,
      "has_b_frames": 1,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "16:9",
      "pix_fmt": "yuv420p",
      "level": 31,
      "color_range": "tv",
      "color_space": "bt709",
      "color_transfer": "bt709",
      "color_primaries": "bt709",
      "chroma_location": "left",
      "field_order": "progressive",
      "refs": 1,
      "is_avc": "false",
      "nal_length_size": "0",
      "id": "0x100",
      "r_frame_rate": "25/1",
      "avg_frame_rate": "25/1",
      "time_base": "1/90000",
      "start_pts": 129600,
      "start_time": "1.440000",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_time_base": "1/44100",
      "codec_tag_string": "[15][0][0][0]",
      "codec_tag": "0x000f",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "id": "0x101",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 129600,
      "start_time": "1.440000",
      "bit_rate": "93023",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      },
      "tags": {
        "language": "fra"
      }
    }
  ],
  "format": {
    "filename": "pipe:",
    "nb_streams": 2,
    "nb_programs": 1,
    "format_name": "mpegts",
    "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
    "start_time": "1.440000",
    "probe_score": 50
  }
}
```

**Comment by campones** [comment]
hmm well I d rather say that their stream is the cause of the problem, and not my setup since it has worked for months, or even years now. 

also please don't compare someone doing a one time test with someone that is using this in production 24/7.  different problems may happen on a long term use.

**Comment by campones** [comment]
well seeing this, i m not so surprised it works randomly 
![db17643200e08e528a5ee90e0a66e396](https://user-images.githubusercontent.com/7072524/59392284-c19a7900-8d7f-11e9-959a-400369a80c2e.png)

**Comment by bastimeyer** [comment]
This thread was about your question regarding the ffmpeg child processes, which has been answered.

If you think that Streamlink or the plugin is broken, open a new bug report or plugin issue with a proper **text debug log** and post the result of the missing audio stream. You can use ffprobe for this, like I did for example.

> using this in production 24/7

If I may ask, what are you doing with that stream which you are remuxing and outputting via RTMP?
