### ISSUE TITLE
Cleanup the Windows build

### ISSUE THREAD

**Issue by sbstp** [streamlink/streamlink#25]
The current build tools in `win32/build-with-bootstrap.sh` use an older version of livestreamer and injects a new egg into it. It looks like it might be a mess to fix to our needs, so we might have to rewrite the build process for windows.

I've looked at the options, and it looks like [cx_Freeze](http://cx-freeze.readthedocs.io/en/latest/index.html) could fit our needs, it creates a standalone .exe from a python package and can even [create an installer](http://cx-freeze.readthedocs.io/en/latest/distutils.html#bdist-msi) for it.

**Comment by gyvess** [comment]
I'm not a knowledgeable person but I am a Windows user.

While a standalone .exe would be neater, the way livestreamer is currently built I am able to directly edit .py files.  Therefore allowing me to separately update the plugin files independent of a new livestreamer release.  Without building the program myself to boot.  It's helped me to get ustream, periscope, and lately twitch working properly.

Assuming the standalone .exe means what I think, that'd be at least one drawback to consider.  While it's been a boon with livestreamer having been abandoned, it shouldn't be a problem as long as streamlink is reliably updated and improved.

**Comment by sbstp** [comment]
This is a really good point. I think that the files should be modifiable. Like you said, you can write a fix for a plugin without having to wait on the project maintainers. I'll look at the options of `cx_Freeze` and see if this can be done.

**Comment by sbstp** [comment]
I've tried `cx_freeze` and couldn't even get it to build properly. I don't think we'll be able to use it. I found a tool called `pyinstaller` that looks pretty good, and is well documented, but it doesn't create an installer. So we'd have to use InnoSetup or NSIS to create an installer. Also, we need a Windows machine to use pyinstanner and InnoSetup/NSIS.

**Comment by cdrage** [comment]
@sbstp i've used pyinstaller in other apps, it's freakin' great. I'd be :+1: to get the current installer converted to pyinstaller.

**Comment by sbstp** [comment]
@cdrage Do you know if there's a way of keeping the source files, like @gyvess mentioned? Based on what I read, they only package the .pyc files.

**Comment by cdrage** [comment]
@sbstp source files no, but you can explicitly include data files. I did this within another project called atomicapp here: https://github.com/projectatomic/atomicapp/blob/master/atomicapp.spec

It'll take a lot of trial-and-error to get working, but once it does, it's quite stable / works well.

**Comment by skulblakka** [comment]
>you can write a fix for a plugin without having to wait on the project maintainers

You can always [sideload](http://docs.livestreamer.io/cli.html#sideloading-plugins) the plugin while you wait for the official one to update (of course you would need to remove the sideloaded version again after updating)

**Comment by sbstp** [comment]
Thank you @skulblakka, this is a good solution. I think we can move forward with pyinstaller.

**Comment by sbstp** [comment]
I'm gonna try the bdist tool of setuptools, with a [post install](https://docs.python.org/2/distutils/builtdist.html#the-postinstallation-script) script to modify the PATH variable before trying pyinstaller.
Also does anyone know what rtmpdump is used for?

**Comment by sbstp** [comment]
bdist doesn't package the dependencies and doesn't bundle the interpreter, so it's pointless.

**Comment by SpootDev** [comment]
+1 to pyinstaller 3.2 as well.  :)

**Comment by sbstp** [comment]
I've been trying to get pyinstaller to work for a couple hours now and it's a pretty internal experience.

**Comment by sbstp** [comment]
So I asked around and was referred to a tool called [pynsist](http://pynsist.readthedocs.io/en/latest/index.html). It does everything we need. The format is incredibly simple easy easy to maintain, it produces an installer and allows us to add programs to the PATH. I tested it on my Windows install and it works perfectly.

**Comment by gravyboat** [comment]
That would be awesome!

**Comment by sbstp** [comment]
It can also create incredibly small files using [Python 3.5's embedded build](http://pynsist.readthedocs.io/en/latest/cfgfile.html#python-section). Another reason to support Python 3 fully.

**Comment by gravyboat** [comment]
I think we can close this to keep things clean in the issues unless you have concerns @sbstp.
