### ISSUE TITLE
how can i output file to direct my Harddisk?

### ISSUE THREAD

**Issue by ninosel** [streamlink/streamlink#2500]
any code for this? thanks

**Comment by malvinas2** [comment]
[https://streamlink.github.io/cli.html#file-output-options](https://streamlink.github.io/cli.html#file-output-options)

**Comment by ninosel** [comment]
**streamlink (link) best -o out.mp4** this code saving my document file help

**Comment by ninosel** [comment]
**streamlink (link) best -o out.mp4** this code recording to my documents file which i should add code?

**Comment by johnthecracker** [comment]
streamlink (link) best -o C:\Users\ninosel\Documents\out.mp4
