### ISSUE TITLE
 Extract video from streaming application with AES-128 decryption key

### ISSUE THREAD

**Issue by aandronikakis** [streamlink/streamlink#2504]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I am using a streaming application (executable program) that works only on windows. I've managed to find the log [file](https://justpaste.it/6sbac),  in order to get the streaming link: http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8

In order to run the application, I have to login via Chrome (via Greek VPN)  to the website (password/username) and find the link that I want to watch, which forwards me to the application for the streaming. So the video streams from the app. I give you down all the information that I managed to get from the website.

```Request URL: wss://tvgoplayer.gr:9498/command
Request Method: GET
Status Code: 101 Web Socket Protocol Handshake
Connection: Upgrade
Sec-WebSocket-Accept: v5Au35sHicAHbRkq0FrpHGBK7EM=
Upgrade: websocket
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: no-cache
Connection: Upgrade
Host: tvgoplayer.gr:9498
Origin: http://www.cosmotetvgo.gr
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: dAn9Wd41ptPuFTxrCUYxcg==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
```

```
GlobaleConfig = {
    culture: 'en',
    version: 'IPTV_EPG_V100R003C03LOTE96B003',
    ssh_enable: 1,
    versionDate: 20161205,
    defaultAvater: '0',
    batchlimit: 10,
    macPlugType: 'HUAWEI',
    profilelimit: 10,
    ifShowWhatsNew: false,
    boardType: 2,
    //SocialUrl:'http://173.18.1.200:9002'
    SocialUrl: 'https://socialtv.hybrid.otenet.gr:9002',
    //https端口与http端口的映射定义
    protocolPortMap: {
        "443": "80",
        "8443": "8080",
        "33207": "33200"
    }
};

if (/windows|win32/i.test(navigator.userAgent)) {
    GlobaleConfig.macPlugType = 'HW';
}

GlobaleConfig.getHttpsPort = function(){
    if (location.protocol == 'https') {
        return location.port;
    }
    
    for (prop in GlobaleConfig.protocolPortMap) {
        if (GlobaleConfig.protocolPortMap[prop] == location.port) {
            return prop;
        }
    }
    
    return location.port;
}

GlobaleConfig.getHttpPort = function(){
    if (location.protocol == 'http') {
        return location.port;
    }
    
    for (prop in GlobaleConfig.protocolPortMap) {
        if (prop == location.port) {
            return GlobaleConfig.protocolPortMap[prop];
        }
    }
    return location.port;
}
```
and 

```
POST http://www.cosmotetvgo.gr/EPG/JSON/ExecuteBatch?PlayRecord HTTP/1.1
Host: www.cosmotetvgo.gr
Connection: keep-alive
Content-Length: 100
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://www.cosmotetvgo.gr
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://www.cosmotetvgo.gr/EPG/jsp/webtv/index.jsp
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: JSESSIONID=A92503198A49B82F4E78F50A265C1219

{"requestList": [{"name": "PlayRecord", "param":{"recordtype":5,"playtype":"3","channel":"23082"}}]}
```

I firstly run the `streamlink http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8 best` command but i got the following:
```
[stream.hls][error] Failed to create decryptor: Unable to open URL: [url]https://ipca.ott.otenet.gr/CAB/keyfile?s=1096&r=OTE0000014487OTT&t=VOD&p=0&Kd=6E6ACC8659C593E6192C45C209911172&Kc=50D4944C8E8A11E9A52DF403435AD960[/url] (HTTPSConnectionPool(host='ipca.ott.otenet.gr', port=443): Max retries exceeded with url: /CAB/keyfile?s=1096&r=OTE0000014487OTT&t=VOD&p=0&Kd=6E6ACC8659C593E6192C45C209911172&Kc=50D4944C8E8A11E9A52DF403435AD960 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)))
[cli][error] Try 1/1: Could not open stream <HLSStream('http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8')>, tried 1 times, exiting
```
I've also tried later

`streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" --http-cookie "JSESSIONID=A92503198A49B82F4E78F50A265C1219" http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8 best`
    
and
` streamlink --https-proxy "socks5://212.205.188.85:80" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" --http-cookie "JSESSIONID=A92503198A49B82F4E78F50A265C1219" --hls-segment-key-uri "https://ipca.ott.otenet.gr/CAB/keyfile?s=1096&r=OTE0000014492OTT&t=VOD&p=0&Kd=587 9DD71890FA532E32285E3B30C4F99&Kc=9F25015A8E9811E9A 52DF403435AD960" http://212.205.188.205:80/88888888/16/20190614/268481879/5.m3u8 best`

I think I am close, any clue how to pass my username and password, maybe that's the problem... or any other clues, how to get the key??

**Comment by beardypig** [comment]
Have you tried adding the `--http-no-ssl-verify` option?

**Comment by back-to** [comment]
> I am using a streaming application (executable program)
> that works only on windows.
> I have to login via Chrome (via Greek VPN)
> to the website (password/username)

closing, too many different components to get help in this issue tracker.
