### ISSUE TITLE
How to break the broadcast into sections

### ISSUE THREAD

**Issue by danilshik** [streamlink/streamlink#2506]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] I asked this question on stackoverflow, but no one could help me with anything
- [x] I do not know English well, so I use a translator, so that meaning may be distorted

### Description

I want the live video to be divided into pieces of 10 minutes during the online broadcast.
Therefore, I used the command `streamlink --hls-live-edge 99999 --hls-segment-threads 10 --ringbuffer-size 1024M -o test123.ts https://www.youtube.com/watch?v=XWwW1l_Ciwk best`

I found a command to break the video into pieces: `ffmpeg -i test123.ts -f segment -segment_time 360 -vcodec copy -acodec copy stream%%05d.ts`

The problem arises in the fact that if you run these commands sequentially, the resulting file will be broken into pieces of 10 minutes only when the translation is complete.

You can put the second command in another file that you can run manually, and it will create files for 10 minutes. But I need to do this automatically,

As an option in this file, you can execute this command in an infinite loop, and it will work, but the files will be constantly recreated, which prevents you from starting the installation.
Example:
```
:loop
ffmpeg -i test123.ts -f segment -segment_time 360 -vcodec copy -acodec copy stream%%05d.ts
goto loop
```

I tried to shove the streamlink command in ffmpeg. Example:
`ffmpeg -i streamlink --hls-live-edge 99999 --hls-segment-threads 10 --ringbuffer-size 1024M -o test123.ts https://www.youtube.com/watch?v=XWwW1l_Ciwk best -f segment -segment_time 10 -vcodec copy -acodec copy stream%%05d.ts
`
But he writes on the error of the parameters::
```
Unrecognized option '-hls-live-edge'.
Error splitting the argument list: Option not found
```
Which indicates that I am doing wrong

How can you implement splitting the online broadcast into pieces of 10 minutes? For example, 11 minutes passed, 1 file was created, 21 minutes passed, 2 file was created

And please do not close the question with the wording that it refers to ffmpeg, I know, but no one helped me on stackoverflow, and on github ffmpeg it’s not possible to ask a question at all

I will be glad to any help. You can use any channel on Youtube or Twitch as a broadcast source.

**Comment by back-to** [comment]
> ffmpeg -i streamlink

wrong command

---

see https://github.com/streamlink/streamlink/issues/2459#issuecomment-491487100

```
streamlink URL best -O | ffmpeg -i pipe:0 <YOUR FFMPEG COMMAND>
```

don't set `ffmpeg -i test123.ts` use it with **pipe**
