### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by jrodonnell909** [streamlink/streamlink#251]
Whenever I try to uninstall the program, I get a pop-up saying

> Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.

I have tried running the uninstaller with administrative permissions. It also seems to trip my anti-virus, which is curious since I downloaded the installer directly from the releases page.

**Comment by beardypig** [comment]
Try to use Add/Remove Program from the Control Panel. Depending on your version of Windows it will be somewhere like Control Panel -> Programs -> Programs and Features, then you should be able to Streamlink from there.

**Comment by jrodonnell909** [comment]
I've tried that and I got the same result. I then tried adding the uninstaller to the my antivirus's exceptions list, and it caught all of the temporary files that the uninstaller adds as "generic viruses."

**Comment by beardypig** [comment]
Do you have a list of the temporary files that it lists as generic viruses? Which AV are you using?

**Comment by jrodonnell909** [comment]
Here's the list:

> "Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Xu_.exe";"Secured";"12/5/2016, 11:46:47 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Wu_.exe";"Secured";"12/5/2016, 11:46:47 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Yu_.exe";"Secured";"12/5/2016, 11:46:47 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Uu_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Tu_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Su_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Vu_.exe";"Secured";"12/5/2016, 11:46:47 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Qu_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Pu_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Ou_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Nu_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Mu_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Lu_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Ku_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Ju_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Iu_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Hu_.exe";"Secured";"12/5/2016, 11:46:45 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"
"Found Win32/DH{NYJcA4EPgiZY?}, c:\Users\Alex\AppData\Local\Temp\~nsu.tmp\Ru_.exe";"Secured";"12/5/2016, 11:46:46 AM";"File or Directory";"c:\Program Files (x86)\Streamlink\uninstall.exe"

I'm using AVG for anti-virus.

**Comment by RosadinTV** [comment]
Virustotal detects 3/56:
https://www.virustotal.com/es/file/bc09fde81cf6142b711e7dd0f936206c9926694090266d48b29a1f5b0710aafa/analysis/1480957148/
Almost always happens that about 3 or 4 antivirus detects applications as false-positive 😅 
(Is less common in 'serious' AV like AVG but sometimes it happens)

**Comment by beardypig** [comment]
It does appear to be a false positive as @RosadinTV points out :) I don't know how you can get around it though, I'm not an AVG user.

**Comment by RosadinTV** [comment]
@beardypig Sometimes AV's are really painful, I tested building literally empty applications with Visual Studio and that are detected as a threat by multiple AV's.
Another one of the greatest things of Open Source is we can provide confidence to users in cases like these.

**Comment by gravyboat** [comment]
I've been unable to install Streamlink via Add/Remove programs but I'm also not using AVG.

**Comment by beardypig** [comment]
@gravyboat install or uninstall? I've never installed it with add/remove, only uninstalled... countless times now.

**Comment by gravyboat** [comment]
@beardypig Ugh I fat fingered and typed UNable when I meant ABLE....

**Comment by beardypig** [comment]
@gravyboat, that makes sense :-)

**Comment by Vangelis66** [comment]
@jrodonnell909 

You may have to temporarily disable your AV suite in order to uninstall streamlink; 
or might try to also add to its exceptions list your %TEMP% folder.
In any case, you should report the false positive on their site. 

I am on Kaspersky myself, in the past I did come across NSIS installers 
or NSIS created uninstallers that were flagged by my AV; 
I contacted them, attaching the culprit file, and the false positive 
was lifted some days later, via a definitions update...

**Comment by gravyboat** [comment]
I'm going to close this for now since it appears to be resolved.
