### ISSUE TITLE
Dailymotion 403 forbidden

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2512]
Hello

When I try to use the dailymotion plugin I get a 403 error. this happens on others servers I own
could this be an ip range ban?

 /usr/local/bin/streamlink "http://www.dailymotion.com/video/xgz4t1" 477p
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin dailymotion for URL http://www.dailymotion.com/video/xgz4t1
[cli][info] Available streams: 180p_alt (worst), 180p, 288p_alt, 288p, 477p_alt, 477p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 477p (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://stream-04.ix7.dailymotion.com/sec(4cextmXq8crpVEOecERE_uLvfQvdMemulgwp1ZLz4oc)/dm/3/xgz4t1/d/live-2.m3u8#cell=lcore&comment=CATCHALL+bc00000&qos_vpart=1&qos_stail=1')> (Could not open stream: Unable to open URL: https://stream-04.ix7.dailymotion.com/sec(4cextmXq8crpVEOecERE_uLvfQvdMemulgwp1ZLz4oc)/dm/3/xgz4t1/d/live-2.m3u8#cell=lcore&comment=CATCHALL+bc00000&qos_vpart=1&qos_stail=1 (403 Client Error: Forbidden for url: https://stream-04.ix7.dailymotion.com/sec(4cextmXq8crpVEOecERE_uLvfQvdMemulgwp1ZLz4oc)/dm/3/xgz4t1/d/live-2.m3u8#cell=lcore&comment=CATCHALL+bc00000&qos_vpart=1&qos_stail=1))
error: Could not open stream <HLSStream('https://stream-04.ix7.dailymotion.com/sec(4cextmXq8crpVEOecERE_uLvfQvdMemulgwp1ZLz4oc)/dm/3/xgz4t1/d/live-2.m3u8#cell=lcore&comment=CATCHALL+bc00000&qos_vpart=1&qos_stail=1')>, tried 1 times, exiting

**Comment by johnthecracker** [comment]
works here in windows:
```
C:\>streamlink.exe --player=mpv.exe --http-no-ssl-verify --http-timeout 1 "https://www.dailymotion.com/video/xgz4t1" best
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/xgz4t1
[cli][info] Available streams: 180p_alt (worst), 180p, 288p_alt, 288p, 477p_alt, 477p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv.exe
```
streamlink-1.1.1-20190525.exe

**Comment by campones** [comment]
well yea, obviously, since your ip isn't banned.   I also works for me in my home computer

**Comment by campones** [comment]
what was interesting here is to have feedback from other users that might have hosting at online to see if this is a specific ban or a complete datacenter ip range ban. I guess another time

also note that the --http-header "X-Forwarded-For=x.x.x.x" doesn't work in that case as a workaround

**Comment by bastimeyer** [comment]
This is a bug tracker. Streamlink itself is working fine and there's nothing which can be done if you have connection issues or have been blocked by the streaming provider.

Also, we are not supporting any kind of re-hosting streams, which you seem to be doing here, whether it's legal or not.

**Comment by campones** [comment]
first , I am not on ovh datacenter. 
second, if you can't take the pressure, do something else
three: you might as well do that kind of jobs, since you look like the justice guy in most of your answers, instead of providing technical answers.

what I said is they are banning entire well known ip range, that doesn't concern only me.  simply I have many servers that never even used streamlink and they are also 403 forbidden.  period.
