### ISSUE TITLE
Cannot allocate write+execute memory for ffi.callback()

### ISSUE THREAD

**Issue by craigerl** [streamlink/streamlink#2514]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

 streamlink --stream-url --stream-types hls  'https://livestream.com/KTXL/live' best

error: Unable to open URL: https://livestream.com/KTXL/live (Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks)

This is on a hosted system, likely a container.

### Expected / Actual behavior

output a url

### Reproduction steps / Explicit stream URLs to test

streamlink --stream-url --stream-types hls  'https://livestream.com/KTXL/live' best

**Comment by back-to** [comment]
probably not enough memory

there are not enough details to determine it,
but Streamlink itself can't do anything about it.
