### ISSUE TITLE
Can't login Pixiv account

### ISSUE THREAD

**Issue by hat3l0v3** [streamlink/streamlink#2515]
**Hello, Can't login in Pixiv account**

typing:
```
streamlink --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@tuvai1031 best
```
result:
```
[plugin.pixiv][error] Failed to log in.
error: No playable streams found in this URL: sketch.pixiv.net/@tuvai1031
```
[Screenshot](https://i.imgur.com/rUhWRqZ.png)

**If I change artist that not requires you to login (not R18) - plugin works fine!**

typins the same with other stream link:
```
streamlink --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@irodori-ace best
```
Result:
```
[plugin.pixiv][error] Failed to log in.
[cli][info] Avaliable streams: 720p (worst), 1080p (best)
[cli][info] Openins stream: 1080p (hls)
[cli][info] Starting player: D:\Program Files\vlc\vlc.exe
```
[Screenshot](https://i.imgur.com/lr2aco8.png)

**So problem is login/password I guess. I tried typing** `--pixiv-username=*******, --pixiv-username="*******"`, **adding** `;` **, double check my login/password to be sure. Nothing helps. Maybe im typing something wrong? I will be grateful for any help**

**Comment by casmithyother** [comment]
I started having this issue the other day. It appears to be caused by a captcha system that may have been added recently.

I made modifications to my plugin script to use OAuth via https://oauth.secure.pixiv.net/auth/token. Here is where I took example from: https://github.com/Nandaka/PixivUtil2/blob/master/PixivOAuth.py

 I do not know if there is a more ideal solution.

**Comment by brachna** [comment]
That might be the best solution for now. For my script I just use cookies from my browser.

**Comment by hat3l0v3** [comment]
I

> That might be the best solution for now. For my script I just use cookies from my browser.

Is there some kind of guide how to fix problem like you? For people who know nothing about coding (like me).

**Comment by brachna** [comment]
It does require a bit of coding, but if you don't have it and don't want to wait for a proper fix here's how to do it (I assume you're on Windows and using Firefox browser):
1. download browsercookie: 
[richardpenman-browsercookie-aab350c45967.zip](https://github.com/streamlink/streamlink/files/3342411/richardpenman-browsercookie-aab350c45967.zip)
install it by executing install.bat
2. download modded pixiv.py:
[pixiv-modded.zip](https://github.com/streamlink/streamlink/files/3342412/pixiv-modded.zip)
backup the original pixiv.py and replace it with modded one
on my machine its path is C:\Python37\Lib\site-packages\streamlink\plugins
3. make sure you're login to pixiv in your Firefox
4. should be fine now, if not try to clean cookies first with --pixiv-purge-credentials

ps. if you're on Chrome you can change the line in modded pixiv.py
from
```
def _login_with_browser_cookies(self, username):
        cj = browsercookie.firefox()
```
to
```
def _login_with_browser_cookies(self, username):
        cj = browsercookie.chrome()
```

**Comment by hat3l0v3** [comment]
> It does require a bit of coding, but if you don't have it and don't want to wait for a proper fix here's how to do it (I assume you're on Windows and using Firefox browser):
> 
> 1. download browsercookie:
>    [richardpenman-browsercookie-aab350c45967-fix.zip](https://github.com/streamlink/streamlink/files/3342421/richardpenman-browsercookie-aab350c45967-fix.zip)
>    install it by executing install.bat
> 2. download modded pixiv.py:
>    [pixiv-modded.zip](https://github.com/streamlink/streamlink/files/3342412/pixiv-modded.zip)
>    backup the original pixiv.py and replace it with modded one
>    on my machine its path is C:\Python37\Lib\site-packages\streamlink\plugins
> 3. make sure you're login to pixiv in your Firefox
> 4. should be fine now, if not try to clean cookies first with --pixiv-purge-credentials
> 
> ps. if you're on Chrome you can change the line in modded pixiv.py
> from
> 
> ```
> def _login_with_browser_cookies(self, username):
>         cj = browsercookie.firefox()
> ```
> 
> to
> 
> ```
> def _login_with_browser_cookies(self, username):
>         cj = browsercookie.chrome()
> ```

I tried, but [that what I have](https://i.imgur.com/vc1ym7S.png)
Can't understand in which step I made mistake or something :(

**Comment by brachna** [comment]
It seems that browsercookie indeed wasn't installed. What message you got when you installed it?
Also it's better to move backup pixiv.py away from plugins folder.

**Comment by hat3l0v3** [comment]
> It seems that browsercookie indeed wasn't installed. What message you got when you installed it?
> Also it's better to move backup pixiv.py away from plugins folder.

I run it as administrator and get this: [link](https://i.imgur.com/Uazouil.png)
Its says somethink like "this command is not internal/external or batch file". something like that (cant translate it properly). After pause is says "press any key to continue". 
Guess the problem is that I did not extract this files from archive to proper place?

**Comment by brachna** [comment]
Oh, it looks like you don't have Python installed at all. Or you don't have it in path.

**Comment by hat3l0v3** [comment]
> Oh, it looks like you don't have Python installed at all. Or you don't have it in path.

Sorry, didnt know about that. My program knowlage are full 0.
So i need to install Python? after installing browsercookie can I just delete him? or its required to use it?

**Comment by brachna** [comment]
No, you can't delete Python, scripts simply won't work without it.
Install latest Python 3.7.3.

**Comment by hat3l0v3** [comment]
> No, you can't delete Python, scripts simply won't work without it.
> Install latest Python 3.7.3.

I have installed Python 3.7.3. but if I run that .bat it says the same. What should I do?

**Comment by brachna** [comment]
Launch command prompt and type:
python --version
Does it work? If yes - show your messages you get when installing browsercookie. If not - you installed Python incorrectly, it should have "Add Python 3.7 to PATH" box checked when installing.

**Comment by hat3l0v3** [comment]
> Launch command prompt and type:
> python --version
> Does it work? If yes - show your messages you get when installing browsercookie. If not - you installed Python incorrectly, it should have "Add Python 3.7 to PATH" box checked when installing.

yea, i didnt check that box. i found that on youtube guide videos. allready installed that .bat. gona test now pixiv plugin.

**Comment by hat3l0v3** [comment]
well, its not working. same problem (failed to load pixiv plugin)
Running that .bat gives me this - [link](https://i.imgur.com/bITASPm.png) . on first time it was installing something.
Any clue?

**Comment by hat3l0v3** [comment]
> Launch command prompt and type:
> python --version
> Does it work? If yes - show your messages you get when installing browsercookie. If not - you installed Python incorrectly, it should have "Add Python 3.7 to PATH" box checked when installing.

If I run not as administrator that .bat gives a bit different message - [link](https://i.imgur.com/s4LpcQ0.png)

**Comment by brachna** [comment]
Don't launch install.bat as administrator.

**Comment by hat3l0v3** [comment]
> Don't launch install.bat as administrator.

But the problem is the same 
1. failed to load plugin pixiv
2. no module named "browsercookie"

**Comment by brachna** [comment]
Browsercookie is installed, but streamlink you're using doesn't see it.
In command prompt type:
pip install streamlink

That will install streamlink for your Python.
Then change pixiv.py to modded one in your Python's streamlink plugin directory (depends where you installed Python, mine is C:\Python37\Lib\site-packages\streamlink\plugins).
It now looks to me that you're using a standalone streamlink.

**Comment by hat3l0v3** [comment]
> Browsercookie is installed, but streamlink you're using doesn't see it.
> In command prompt type:
> pip install streamlink
> 
> That will install streamlink for your Python.
> Then change pixiv.py to modded one in your Python's streamlink plugin directory (depends where you installed Python, mine is C:\Python37\Lib\site-packages\streamlink\plugins).
> It now looks to me that you're using a standalone streamlink.

done. but its says same. how do i run it? from command prompt right?

**Comment by brachna** [comment]
You can run it either from command prompt or write a .bat file.
Try running it as a Python script: add python before streamlink:
```
python streamlink --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@tuvai1031 best
```
Please show errors you get.

**Comment by hat3l0v3** [comment]
> You can run it either from command prompt or write a .bat file.
> Try running it as a Python script: add python before streamlink:
> 
> ```
> python streamlink --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@tuvai1031 best
> ```
> 
> Please show errors you get.

It says " cant open file "streamlink" : [Errno 2] No such file or directory

**Comment by brachna** [comment]
What happens when you try a usual command - same error?
I have a feeling that standalone Streamlink messes with a path.
Do you have streamlink.exe in you Python scripts directory? (mine is C:\Python37\Scripts)

**Comment by hat3l0v3** [comment]
> What happens when you try a usual command - same error?
> I have a feeling that standalone Streamlink messes with a path.
> Do you have streamlink.exe in you Python scripts directory? (mine is C:\Python37\Scripts)

yes, its there. 
[with and without python](https://i.imgur.com/8syQRFX.png)

**Comment by brachna** [comment]
Don't try with python, it was just a wild guess of mine.
So you have it there, good. Let's try this then, make a .bat file and write it like this:
```
C:\Python37\Scripts\streamlink.exe --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@tuvai1031 best
```
Change to your "Python37\Scripts" path though and don't launch as administrator.

**Comment by hat3l0v3** [comment]
> Don't try with python, it was just a wild guess of mine.
> So you have it there, good. Let's try this then, make a .bat file and write it like this:
> 
> ```
> C:\Python37\Scripts\streamlink.exe --pixiv-username "*******" --pixiv-password "*******" --player="D:\Program Files\vlc\vlc.exe" sketch.pixiv.net/@tuvai1031 best
> ```
> 
> Change to your "Python37\Scripts" path though and don't launch as administrator.

I tried. Its open window, show [this](https://i.imgur.com/WP2C2k8.png) and then close and nothing happens.
btw do I need type login/password there? I thought its getting from browser cookies?

**Comment by hat3l0v3** [comment]
I found if I change channel to not r18 required, its works. So problem is that it cant take account cookies or what?

**Comment by brachna** [comment]
Yes, with login and password, it just for compatibility sake, however your username is used to determine if login even worked.

**Comment by hat3l0v3** [comment]
> Yes, with login and password, it just for compatibility sake, however your username is used to determine if login even worked.
> If you won't provide them then it won't even try to use cookies.

with login/password i cant see what it shows. its disappearing too fast . but there is tons of text

**Comment by brachna** [comment]
In your .bat file write pause on the next line

**Comment by hat3l0v3** [comment]
> In your .bat file write pause on the next line
> ps. just blur/mask your credentials or cut them off picture.

here  [log](https://i.imgur.com/bMZEbKA.png)

**Comment by brachna** [comment]
It would be easier to install Firefox and do a login there (you don't have to use it of course).
For Chrome it wants win32crypt.
However you can try:
pip install pypiwin32
Then try again. If doesn't work, try installing Firefox.

**Comment by hat3l0v3** [comment]
> It would be easier to install Firefox and do a login there (you don't have to use it of course).
> For Chrome it wants win32crypt.
> However you can try:
> pip install pypiwin32
> Then try again. If doesn't work, try installing Firefox.

After installing pypiwin32 its finnaly WORK! im very happy.
Thank you very much for this programming courses!!! \ (•◡•) /

So it's basically temporary solution for people like me who waiting fix.

**Comment by brachna** [comment]
Glad we sorted it out. Yes, it's a workaround for now.
The reason you can't just use streamlink and have to use "C:\Python37\Scripts\streamlink.exe" is because your standalone Streamlink have a PATH variable.
Even when update will come out I'd recommend to stick with Python version. Standalone is more trouble in the end.

**Comment by hat3l0v3** [comment]
> Even when update will come out I'd recommend to stick with Python version. Standalone is more trouble in the end.

Okay, as you say

**Comment by YuuichiMizuoka** [comment]
here's a slightly different modded version that also might be useful for some people.
It allows you to specify the sessionid and devicetoken manually using "--pixiv-sessionid" and "--pixiv-devicetoken". 

Maybe we could try to add this into the pixiv plugin as an alternative login option? (I personally use if for some automation scripts)

[pixiv_modded_sessionid_and_devicetoken.zip](https://github.com/streamlink/streamlink/files/3342554/pixiv_modded_sessionid_and_devicetoken.zip)

**Comment by hat3l0v3** [comment]
A bit after using plugin I've got 2 question:

1. Is possible to fix [this](https://i.imgur.com/rUQyfAm.png) lags (artifacts)? 
Never got such lags on twitch or somewhere else. Tried increase buffer size by using commands: --file-caching=20000 --network-caching=20000 , but it didn't give a shit :(

2. I have command like "blablabla blablabla url:@ID blablabla". Is possible to make .bat file in such way so I require to enter only ID after opening it. Not making different .bat to different ID.

Will be very grateful for anyone who reply.

**Comment by YuuichiMizuoka** [comment]
i cant help with the 1. question.

regarding the 2. question... try:
```
set /p id=Please enter the ID you want to download
blablabla blablabla url:%id% blablabla
```

**Comment by hat3l0v3** [comment]
> i cant help regarding the 1. question.
> 
> regarding the 2. question... try:
> 
> ```
> set /p id=Please enter the ID you want to download
> blablabla blablabla url:%id% blablabla
> ```

thanks very much! Its saves alot of time ^.^

**Comment by hat3l0v3** [comment]
For some reason browsercookie doesn't work for me now. I didn't touch anything, all was fine, and then [THIS](https://i.imgur.com/yKOc2BX.png).
   Tried with firefox - same shit. Seems my browser not the reason of it. Anyone know what that can be? Maybe there is new ways to login pixiv?

**Comment by Replictica** [comment]
I have the same issue
I tried to use sessionid and devicetoken but I have some issues using them.
First, I can't write anything when the comand asks me the pixiv devicetoken.
Then, I get an error when streamlink tries to open a pixiv stream (even the ones that doesn't requires authentification)
I get:
error: Unable to open URL: https://sketch.pixiv.net/api/lives.json (400 Client Error: Bad Request for url: https://sketch.pixiv.net/api/lives.json)

**Comment by hatabbich** [comment]
can't login in R18 streams, error message every time.. non R18 works perfect =(

**Comment by YuuichiMizuoka** [comment]
@Replictica did you try to add the device token directly using the cli parameters?
(--pixiv-sessionid and --pixiv-devicetoken)

@hatabbich  good to hear it works again ^^

**Comment by Replictica** [comment]
@YuuichiMizuoka I tried to add the device token by addind the value in my bat file
I tried: 
--pixiv-sessionid "_value_" -> got streamlink: error: unrecognized arguments: best
--pixiv-sessionid"_value_" -> got enter pixiv device token
--pixiv-sessionid="_value_" -> got enter pixiv device token
I think i messed up a bit, i don't know how to add the value properly in the parameters

**Comment by Replictica** [comment]
@YuuichiMizuoka Thanks for the reply
it seems to work better but i still have the first error:

error: Unable to open URL: https://sketch.pixiv.net/api/lives.json (400 Client Error: Bad Request for url: https://sketch.pixiv.net/api/lives.json)

**Comment by YuuichiMizuoka** [comment]
@Replictica 
that's weird... could you please post the command you are using? 
(don't forget to censor your sessionid and device token)

**Comment by Replictica** [comment]
![error](https://user-images.githubusercontent.com/61726135/75923709-c37e0c80-5eb9-11ea-9d50-1e68d6b1e477.png)

Here is the error. I use the modded pixiv sessionid. it was directly pasted into the plugins foldder.

**Comment by YuuichiMizuoka** [comment]
oh, the mod i published above? It was accepted to the main stream link branch with https://github.com/streamlink/streamlink/pull/2529

so you can now just use the newest streamlink version without any modding ^^
Could you please try to download the newest version and use it without the mod?

And if that doesen't work, please also try to add "--pixiv-purge-credentials" before "--pixiv-sessionid" just in case your old credentials where cached

**Comment by Replictica** [comment]
It finally works after purge-credentials ^^
Thanks for the help !

**Comment by YuuichiMizuoka** [comment]
ah that's good to know, so it probably just cached some weird values from the earlier attempts ^^
I'm happy i could help xD

**Comment by cykac04** [comment]
@YuuichiMizuoka There is no more devicetoken value in the pixiv cookies. Do you know how to solve it?
