### ISSUE TITLE
Auto Detect File Name or Auto Rename

### ISSUE THREAD

**Issue by Daringbaaz** [streamlink/streamlink#2516]
Hello i am New With Streamlink, and I Don't Know Much More About CLI Tools,  Because I am Noob.

I am Using Streamlink Because Someone Helped Me to Download My Desired Videos, But The Issue Was Renaming option, 

streamlink URL "720p" -o  output.mp4

But I Always Need to Write, So I Created a .bat for Just Paste and Relax,
but there is issue with output name, it ask for overwite,
is there any command that will auto generate title name of Output video, or randomly use any text without Promorting overwrite

**Comment by bastimeyer** [comment]
There's the `--force` or `-f` parameter, which lets you automatically overwrite the specified output file.
https://streamlink.github.io/cli.html#cmdoption-f

If you don't want to overwrite the output, then simply add the current date to the output file via shell syntax.

**Comment by Daringbaaz** [comment]
Hello, as i am Noob, i Don't Know More Much about How to auto put dates,

Will You Please Provide me How the File will be auto Rename

I am using Streamlink %URL% %quality% -o Outputname.mp4

Will You Please Give me an, what code i need to use,

**Comment by bastimeyer** [comment]
https://superuser.com/questions/512163/using-date-and-times-in-a-batch-file-to-create-a-file-name
