### ISSUE TITLE
how to download aes-128 ky

### ISSUE THREAD

**Issue by Doktor-X** [streamlink/streamlink#2519]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

ok so i'm trying to download files that have encryption on them but im geting problem that i cant find key to decrypt them

### Reproduction steps / Explicit stream URLs to test

so this is first m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subs",NAME="Croatian",FORCED=NO,AUTOSELECT=YES,URI="subtitlelist_lhrv_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8",LANGUAGE="hrv"
#EXT-X-STREAM-INF:BANDWIDTH=3928000,RESOLUTION=1280x720,SUBTITLES="subs"
chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8

this m3u8 redirect to this "chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8"

this chunklist m3u8 have this inside
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="oma://drmtoday/hrtvodorigin_DBDE6C64-7BD7-4.smil?variantId=&keyId=6FE19A1271E93B21B5F9AA76563F7D2E",IV=0x098342c261738377ddb9b0373d1e9c72,KEYFORMATVERSIONS="1"
#EXTINF:10.0,
media_b3928000_0.ts
....................
media_b3928000_270.ts
#EXT-X-ENDLIST

now when i try to download all of this in ffmpeg, streamlink or in any other program i get stop by  
AES-128
### Logs

```
streamlink https://cdn1.oiv.hr/hrtvodorigin/DBDE6C64-7BD7-4.smil/chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8 best
[cli][info] Found matching plugin hls for URL https://cdn1.oiv.hr/hrtvodorigin/DBDE6C64-7BD7-4.smil/chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: oma://drmtoday/hrtvodorigin_DBDE6C64-7BD7-4.smil?variantId=&keyId=6FE19A1271E93B21B5F9AA76563F7D2E (No connection adapters were found for 'oma://drmtoday/hrtvodorigin_DBDE6C64-7BD7-4.smil?variantId=&keyId=6FE19A1271E93B21B5F9AA76563F7D2E')
[cli][error] Try 1/1: Could not open stream <HLSStream('https://cdn1.oiv.hr/hrtvodorigin/DBDE6C64-7BD7-4.smil/chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://cdn1.oiv.hr/hrtvodorigin/DBDE6C64-7BD7-4.smil/chunklist_b3928000_cfREJERTZDNjQtN0JENy00X3AxLnR0bWw=.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> #EXT-X-KEY:METHOD=AES-128,URI="oma://drmtoday/hrtvodorigin_DBDE6C64-7BD7-4.smil?

if you get a valid `https://` url instead of `oma://`,
you can use this command

https://streamlink.github.io/cli.html#cmdoption-hls-segment-key-uri

there might be some DRM protection to even get this url.

---

closing as there is nothing we can do about it,
with just the plain m3u8 informations.
