### ISSUE TITLE
Error when playing VOD RTMP

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#252]
Input:
`"rtmp://draco.streamingwizard.com:1935/wizard/_definst_/demo/sample.mp4" best`
Output:
```
[cli][info] Found matching plugin stream for URL rtmp://draco.streamingwizard.com:1935/wizard/_definst_/demo/sample.mp4
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] No data returned from stream
```

Edit: It seems like is a RTMPDump bug:
https://lists.mplayerhq.hu/pipermail/rtmpdump/2014-January/002334.html
The stream plays well when using:
`"rtmp://draco.streamingwizard.com:1935/wizard/_definst_/demo/sample.mp4 -y=mp4:demo/sample" best`

**Comment by beardypig** [comment]
Cool. Do you know if it is fixed in a newer version of rtmpdump? Maybe we can update the version we distribute.

**Comment by beardypig** [comment]
Having said that, it doesn't look like it will be fixed. 

Howard Church writes (https://lists.mplayerhq.hu/pipermail/rtmpdump/2013-May/002304.html) 
> Users should just learn to explicitly pass the app and playpath and not rely on the builtin parser at all.

This looks like an wont-fix issue to me :-(

**Comment by RosadinTV** [comment]
@beardypig Yes, i also tried RTMPDump v2.4 GIT-2015-12-14 and not fixed.
I will close the issue because is not a problem of the Project.
Besides this we can update rtmpdump.exe binary, we are currently using a 3 years old one, but i dont know if is any real advantage with the new ones.

**Comment by RosadinTV** [comment]
@beardypig Also as noted in 'pipermail' with this really old build (2011) Works well:
http://www.videohelp.com/download/rtmpdump-20110925-git-6230845-win32.zip
😆 😅

**Comment by Vangelis66** [comment]
That rtmpdump [bug](https://lists.mplayerhq.hu/pipermail/rtmpdump/2014-January/002334.html) withstanding, it seems there's something peculiar in the way that stream is configured 
on the RTMP server; I have visited the webpage that hosts this stream, [jwplayer-setup](http://www.streamingwizard.com/faq/jwplayer-setup.asp), and then used the RTMPdumphelper windows utility to sniff the full rtmpdump parameters: 

`rtmpdump -r "rtmp://draco.streamingwizard.com/wizard/_definst_/" -a "wizard/_definst_/" -f "WIN 23,0,0,207" -W "http://www.streamingwizard.com/faq/jwplayer6.7/jwplayer.flash.swf" -p "http://www.streamingwizard.com/faq/jwplayer-setup.asp" -y "mp4:demo/sample.mp4" -o "sample.flv"`

If you execute the above command, stream download aborts at 10.9%: 
```
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO: trackinfo:
INFO:   language              eng
INFO:   timescale             24.00
INFO:   length                14315.00
INFO: sampledescription:
INFO:   sampletype            avc1
INFO:   language              eng
INFO:   timescale             48000.00
INFO:   length                28628992.00
INFO: sampledescription:
INFO:   sampletype            mp4a
INFO:   audiochannels         2.00
INFO:   audiosamplerate       48000.00
INFO:   videoframerate        24.00
INFO:   aacaot                2.00
INFO:   avclevel              30.00
INFO:   avcprofile            66.00
INFO:   audiocodecid          mp4a
INFO:   videocodecid          avc1
INFO:   width                 424.00
INFO:   height                240.00
INFO:   frameWidth            424.00
INFO:   frameHeight           240.00
INFO:   displayWidth          424.00
INFO:   displayHeight         240.00
INFO:   framerate             24.00
INFO:   moovposition          38774932.00
INFO:   duration              596.46
4082.887 kB / 65.25 sec (10.9%)
INFO: Metadata:
INFO: trackinfo:
INFO:   language              eng
INFO:   timescale             24.00
INFO:   length                14315.00
INFO: sampledescription:
INFO:   sampletype            avc1
INFO:   language              eng
INFO:   timescale             48000.00
INFO:   length                28628992.00
INFO: sampledescription:
INFO:   sampletype            mp4a
INFO:   audiochannels         2.00
INFO:   audiosamplerate       48000.00
INFO:   videoframerate        24.00
INFO:   aacaot                2.00
INFO:   avclevel              30.00
INFO:   avcprofile            66.00
INFO:   audiocodecid          mp4a
INFO:   videocodecid          avc1
INFO:   width                 424.00
INFO:   height                240.00
INFO:   frameWidth            424.00
INFO:   frameHeight           240.00
INFO:   displayWidth          424.00
INFO:   displayHeight         240.00
INFO:   framerate             24.00
INFO:   moovposition          38774932.00
INFO:   duration              596.46
```
However, the stream is downloaded in full if the -R switch is passed: 
```
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
  in approximately realtime (disabled BUFX speedup hack)
INFO: Metadata:
INFO: trackinfo:
INFO:   language                eng
INFO:   timescale               24.00
INFO:   length                  14315.00
INFO: sampledescription:
INFO:   sampletype              avc1
INFO:   language                eng
INFO:   timescale               48000.00
INFO:   length                  28628992.00
INFO: sampledescription:
INFO:   sampletype              mp4a
INFO:   audiochannels           2.00
INFO:   audiosamplerate         48000.00
INFO:   videoframerate          24.00
INFO:   aacaot                  2.00
INFO:   avclevel                30.00
INFO:   avcprofile              66.00
INFO:   audiocodecid            mp4a
INFO:   videocodecid            avc1
INFO:   width                   424.00
INFO:   height                  240.00
INFO:   frameWidth              424.00
INFO:   frameHeight             240.00
INFO:   displayWidth            424.00
INFO:   displayHeight           240.00
INFO:   framerate               24.00
INFO:   moovposition            38774932.00
INFO:   duration                596.46
38610.530 kB / 596.42 sec (99.9%)
Download complete
```
However, issuing:
`streamlink -o sample.flv "rtmp://draco.streamingwizard.com/wizard/_definst_/demo/sample.mp4  -y=mp4:demo/sample -R" best` 
fails prematurely:
```
[cli][info] Found matching plugin stream for URL rtmp://draco.streamingwizard.co
m/wizard/_definst_/demo/sample.mp4  -y=mp4:demo/sample -R
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[download][sample.flv] Written 1.2 MB (2s @ 478.1 KB/s)                        [
cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended
```

**Comment by RosadinTV** [comment]
@Vangelis66 You are right, what a crazy bug haha, in both old and latest rtmpdump builds rtmpdump ends prematurely with Streamlink, probably is better to ignore this one 😝

**Comment by Vangelis66** [comment]
@RosadinTV 

You were quicker than I; I just finished testing with the 2011 rtmpdump build you linked to: 
```
[cli][info] Found matching plugin stream for URL rtmp://draco.streamingwizard.co
m:1935/wizard/_definst_/demo/sample.mp4
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[download][sample.flv] Written 1.1 MB (2s @ 552.9 KB/s)                        [
cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended
```
However, this old build does not even support the -R switch: 
```
rtmpdump: invalid option -- R
unknown option: ?
```
Instead, one should use the --live (-v) one (with standalone rtmpdump) ...

**Comment by RosadinTV** [comment]
@Vangelis66 Yes, also if we use -v the 'stream' is 100% downloaded.
It seems like if we use "rtmp://draco.streamingwizard.com/wizard/_definst_/demo/sample.mp4 -v=1" best Works well (probably because Streamlink requires RTMPDump parameters to be in this format: -x=y)

**Comment by Vangelis66** [comment]
@RosadinTV said: 

> @beardypig 
> Maybe is a good idea to add -v=1 parameter by default? 
> (Because this one Works well in both builds)

**Not at all**; making `-v=1` the default will mean ALL RTMP streams 
will be fetched as if they were LIVE, i.e. IN REAL TIME; this setting will, 
among other things, break user experience when the -o switch is deployed 
with VOD streams; by default, rtmpdump downloads non-live streams 
at full speeds (bandwidth limited), so a 1hr stream can be fetched in 10mins; 
making -v the default would mean the same stream would need 1 full hour 
to be dumped on disk :cry:  
I, for one, am against it - feel free to add some info on the -R=1 (for VOD) 
switch in the documentation; and **REALLY LIVE** RTMP streams do not need 
the -v switch by default anyway (only in rare occasions where the stream is 
misconfigured on the FMS server and rtmpdump fails to identify it correctly!)

**Comment by RosadinTV** [comment]
@Vangelis66 Hell yes, I completely forgot about that, me and my mental loopholes haha 😛 
Here is another VOD example, for some reason without -v=1 or R=1 freezes too.
rtmp://158.42.9.94:1935/vod/media/paellaplayer/belmar-demo/a5bf5ad2-1386-4229-a8d1-c0b59436a1b1/presenter_cut.mp4

**Comment by beardypig** [comment]
I think it's fine the way it is, rtmp is funny beast and many streams will need different options. Maybe we should add a link to the rtmpdump docs to highlight the fact that you can configure rtmpdump to get streams working.

**Comment by Vangelis66** [comment]
@RosadinTV 

With regards to the second VOD stream you referenced, 
yes, one has to issue: 

`streamlink -o "presenter_cut.flv" "rtmp://158.42.9.94:1935/vod/media/paellaplayer/belmar-demo/a5bf5ad2-1386-4229-a8d1-c0b59436a1b1/presenter_cut.mp4 -y=mp4:paellaplayer/belmar-demo/a5bf5ad2-1386-4229-a8d1-c0b59436a1b1/presenter_cut.mp4 -R=1" best`

to make it work (in quasi real time); let's hope most ordinary RTMP 
links streamlink has to deal with aren't that peculiar :wink:

**Comment by RosadinTV** [comment]
@beardypig Yes, it will be better to leave everything as it is.
@Vangelis66 Exactly, Works well with that arguments.
The funny thing is that newer builds requires to manual put playpath (It's supposed that updates should make things better)
Thanks to both for worrying about the issue ❤️
