### ISSUE TITLE
TNT en Direct - regarder la TV en direct

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#2520]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Over tntendirect you can see live streams in top quality 

RTS Un
RTS Deux
TF1
France 2
France 4
France 3
France 5
M6
Arte
C8
W9
Bones
TMC
NRJ12
BFM TV
CStar
Gulli
France O
TF1 Séries Films
L'Équipe 21
6ter
Numéro 23
RMC Découverte
Chérie 25

### Example stream URLs

https://www.tntendirect.com/
 
### Additional comments, screenshots, etc.

https://i.ibb.co/zhnRdRx/tnt.jpg

**Comment by back-to** [comment]
#2251
