### ISSUE TITLE
Ubuntu 16.04 / PPA_install / Streamlink won't play link

### ISSUE THREAD

**Issue by mrkapqa** [streamlink/streamlink#2522]
## Issue

Hello ,

i have installed Streamlink on Ubuntu 16.04 via PPA as suggested here

sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
sudo apt install streamlink

The player would then complain of "no playable stream" if i try to play some.

-----------------
```
git clone https://github.com/streamlink/streamlink
cd streamlink
sudo python setup.py install

would fail with

Installed /usr/local/lib/python2.7/dist-packages/certifi-2019.6.16-py2.7.egg
error: idna 2.0 is installed but idna<2.9,>=2.5 is required by set(['requests'])
```
--------------------
```
sudo pip install streamlink

would fail with

sudo pip install streamlink
[sudo] password di rich: 
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/base_command.py", line 20, in <module>
    from pip._internal.download import PipSession
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/download.py", line 15, in <module>
    from pip._vendor import requests, six, urllib3
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
 
```
--------

Do i need to upgrade python or is there a newer (functional) build avaiable for fairly recent Ubuntu 16.04?

Thanks

### Expected / Actual behavior

play livestream with mpv player withouth lag.

### Reproduction steps / Explicit stream URLs to test

https://www.youtube.com/watch?v=OuAwDTsvQ3M

**Comment by mrkapqa** [comment]
with the above player from ppa:nilarimogard/webupd8

 streamlink -p mpv  https://www.youtube.com/watch?v=OuAwDTsvQ3M
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=OuAwDTsvQ3M
error: No playable streams found on this URL: https://www.youtube.com/watch?v=OuAwDTsvQ3M

**Comment by beardypig** [comment]
Please could you run it again with the `--loglevel debug` argument?

**Comment by mrkapqa** [comment]
streamlink -p mpv https://www.youtube.com/watch?v=OuAwDTsvQ3M --loglevel debug
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=OuAwDTsvQ3M
error: No playable streams found on this URL: https://www.youtube.com/watch?v=OuAwDTsvQ3M

**Comment by mrkapqa** [comment]
streamlink --version
streamlink 0.9.0

**Comment by bastimeyer** [comment]
> Ubuntu 16.04
> webudp8 PPA

http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/s/streamlink/

There are no builds for newer Streamlink releases in this PPA for Ubuntu 16.04 (xenial). You will have to install it via pip:
https://streamlink.github.io/install.html#source-code

----

Regarding your issue with pip, this looks like a dependency issue of pip on your system, which is unrelated to Streamlink. Just google the error message. I found these threads:
- https://stackoverflow.com/questions/45188413/python-pip-install-is-failing-with-attributeerror-module-object-has-no-att
- https://stackoverflow.com/questions/43267157/python-attributeerror-module-object-has-no-attribute-ssl-st-init
- https://askubuntu.com/questions/955546/pip-attributeerror-module-object-has-no-attribute-ssl-st-init

**Comment by mrkapqa** [comment]
Thank you for your help,

i must have seriously messed somthing up.

Found that it was possible to install python-pip (my python2.7.12) but then pip

 pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by mrkapqa** [comment]
Hello ,

thanks, this was very helpful.

I installed pip via

sudo apt-get python-pip

and

pip install --upgrade --user streamlink

(which gave me)

streamlink --version
streamlink 1.1.1

Now playback is functioning!

**Comment by mrkapqa** [comment]
The above gave also warning

You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

but for now i won't mess around with this functioning streamlink version.

**Comment by mrkapqa** [comment]
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Streamlink is functioning so will disregard the above warning as i didn't need pip so far for anything else in particular on this computer.
