### ISSUE TITLE
Need help! reconnect (loop) .bat file

### ISSUE THREAD

**Issue by hat3l0v3** [streamlink/streamlink#2526]
Hello. I wanna make loop (some kind of reconnect) for streamlink. 

I know there is a command like ` --retry-open 1000 --retry-streams 10` but im not sure its gonna work properly coz pixiv link (if streams goes done and then up it has differend url), and also i'm not a programer (my program knowledge = 0).

So I wanna make loop with `:start, goto start` commands.
What it looks like to me : 
```
set /p URL=<"D:\***\*.txt"

:start
"D:\***\streamlink.exe"  --player="D:\***\mpv.exe" %URL% best 

<if stream goes down>  then <goto start + LOOP (X times, with Y interval)>
<if after LOOP stream still down> then <goto end>

:end
```
I know there are a lot of mistakes. My main problem is how to check stream is down or not.
Also will be great to make  `--player mvp.exe` run minimized.
Will be grateful for any help, I already know there is a good people.

**Comment by gravyboat** [comment]
This is out of scope for the Streamlink issues section as it doesn't relate to Streamlink itself. You'll need to do some research on your own and figure out how to implement this.
