### ISSUE TITLE
Stream from local m3u8 playlist file or stdin?

### ISSUE THREAD

**Issue by zacklb** [streamlink/streamlink#253]
Is it possible to give streamlink as input an m3u8 on disk or piped in from stdin?

The following didn't work
```
streamlink hls://file.m3u8 best -o out.ts
streamlink hls://file://file.m3u8 best -o out.ts
streamlink hls:///mnt/g/file.m3u8 best -o out.ts
```
It would also be nice if you could pipe in the url to an m3u8 or it's contents directory via stdin.
For example
```
echo $some_url | streamlink hls://stdin best -o out.ts
streamlink hls://stdin best -o out.ts < file.m3u8
curl ... | streamlink hls://stdin best | ffmpeg ...
```

**Comment by beardypig** [comment]
Neither are currently possible, but local file opening would be a cool addition. 

Would you want to pipe the contents of the file or the URL. If you want to do the URL you can do it easily with a bit of scripting. I think piping the contents would be more useful, and would go hand in hand with local file operations. 

Related: chrippa/livestreamer/issues/1514

**Comment by zacklb** [comment]
> I think piping the contents would be more useful, and would go hand in hand with local file operations.

I agree. Maybe a unified `file://` handler, where if it's empty (or `-`), the handler looks at stdin, otherwise it interprets the rest as a filepath. Although, streamlink would then have to figure out what protocol the stream is. Or one could nest the protocol prefixes on input: `hls://file://...`, but this is pretty messy.

**Comment by beardypig** [comment]
It would have to include the protocol prefix, the default would still be http though. I think it might be doable with some relatively small changes to regular http functions, which are wrappers around `requests`. Possibly something along the lines of https://pypi.python.org/pypi/requests file.

**Comment by beardypig** [comment]
@zacklb do you have an test cases that you could provide?

**Comment by beardypig** [comment]
@zacklb I have a WIP if you want to check it out. I have not tested it on Windows, but it should support relative paths, absolute paths and reading from stdin. https://github.com/beardypig/streamlink/tree/local-files

For example
```
streamlink hlsvariant://file://./playlist.m3u8 best
streamlink hlsvariant://file://../playlist.m3u8 best
streamlink hlsvariant://file:///path/to/playlist.m3u8 best
cat playlist.m3u8 | streamlink hlsvariant://file://- best
```

Not the most attractive URIs but it works.

**Comment by zacklb** [comment]
This looks great. I can test it on Windows in a few hours. I'll find a way to mock an environment to test this new functionality.

**Comment by scottbernstein** [comment]
Ooh, nice @beardypig!  I like this syntax a lot......Totally sensible given the syntax of our other methods of invoking HLSVARIANT streams.


It will probably require some new documentation to explain how to invoke.


________________________________

**Comment by zacklb** [comment]
@beardypig there's a str != bytes issue with Python3 somewhere with the stdin feature:

```
[cli][info] Found matching plugin stream for URL hlsvariant://file://-
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==0.1.0', 'console_scripts', 'streamlink')()
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink_cli/main.py", line 899, in main
    handle_url()
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink_cli/main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink_cli/main.py", line 392, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink/plugin/plugin.py", line 316, in get_streams
    return self.streams(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink/plugin/plugin.py", line 230, in streams
    ostreams = self._get_streams()
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink/plugins/stream.py", line 73, in _get_streams
    streams = cls(self.session, urlnoproto, **params)
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink/stream/hls.py", line 282, in parse_variant_playlist
    res = session_.http.get(url, exception=IOError, **request_params)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.5/site-packages/streamlink-0.1.0-py3.5.egg/streamlink/plugin/api/http_session.py", line 156, in request
    *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 628, in send
    r.content
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by beardypig** [comment]
@zacklb good catch, I didn't test it in python 3 hehe

**Comment by beardypig** [comment]
@zacklb I updated the branch if you wanna test it out in Python3 again :)

**Comment by zacklb** [comment]
Python3 stdin feature now works on Linux (and Linux on Windows).

I got around to testing it on Windows and it doesn't work with either local files or stdin. I tried relative paths using either Windows path separators (\) or Unix-style (/). All attempts produce this error message:

```
> streamlink hls://file://G:\ts\1280x720.m3u8 best -o G:\bleh.mp4
[cli][info] Found matching plugin stream for URL hls://file://G:\ts\1280x720.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Could not open stream: Unable to open URL: http://file//G:%5Cts%5C1280x720.m3u8 (HTTPConnectionPool(host='file', port=80): Max retries exceeded with url: //G:%5Cts%5C1280x720.m3u8 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000025059B4FA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))
```

**Comment by beardypig** [comment]
Cool. Thanks for testing that. I haven't had much time to work on it, so I was only able to quickly do the Python 3 stuff :)

**Comment by beardypig** [comment]
OK. So Windows URL are even more ugly :) You still need the leading `/` so it becomes, and as it's a URL all the separators should be `/`.  

Full paths worked fine with the extra `/`:
```
streamlink hlsvariant://file:///Y:/playlist.m3u8 best
```

Relative and stdin not so good, I'll add a couple of patches to fix those a bit :)

**Comment by beardypig** [comment]
@zacklb pushed a couple of changes that should improve the Windows situation. 

This should work without the extra `/` now :)
```
streamlink hls://file://G:/ts/1280x720.m3u8 best -o G:\bleh.mp4
```

**Comment by zacklb** [comment]
I can't get any of these features to work in Windows with either py2 or py3, using the syntax you provided above. I tried commits 6c0a563 (preceding /) and 3424b8f (no preceding /). Same error as my comment above.

**Comment by beardypig** [comment]
Hmm, weird. How did you install it on Windows? With pip? 
Which version of Windows did you use? I tested it on Vista installed using a freshly built version of the installer (using the scripts/make installer.sh script) .

Did you use all `/` in the URL? It has to be `/` cos it's a URL, rather than a file path :-)

**Comment by zacklb** [comment]
My mistake. I had dirty python environments. The local-files features works on both py2 and py3 on Windows. Thanks!

**Comment by fishscene** [comment]
What is the status of this? I think this is a great feature to add.

**Comment by beardypig** [comment]
@fishscene I have it working on a branch: [https://github.com/beardypig/streamlink/tree/local-files](https://github.com/beardypig/streamlink/tree/local-files). I need to update the docs to explain how to use it, but otherwise it seems to work pretty well...

**Comment by beardypig** [comment]
@zacklb @fishscene this has been merged now :)
