### ISSUE TITLE
Cannot watch USTREAM via Streamlink

### ISSUE THREAD

**Issue by tailorbrands1** [streamlink/streamlink#2530]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I cannot watch USTREAM via Streamlink when the USTREAM link is only viewable on a specific website.

For example, if a channel installs only allows the www.example.com website to embed that channel, you can only watch it when you visit that site to watch it.

Is there any way to bypass?

Thank you.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
@tailorbrands1 

you have to share an example url

**Comment by tailorbrands1** [comment]
I'm sorry, the issue was resolved when I updated to the latest version, help me close this topic.
Thanks.
