### ISSUE TITLE
plugins.ustreamtv: Proxy and Socks do not work

### ISSUE THREAD

**Issue by tailorbrands1** [streamlink/streamlink#2531]
Hi,
I noticed Proxy and Socks no longer work on Streamlink.
The channel I want to watch blocks all countries except the United States and I use US IP to see it.

```
streamlink --http-proxy xxx.xxx.xxx.xxx:xxxx https://www.ustream.tv/embed/23259921 best
```

And it doesn't work

```
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/embed/23259921
[plugin.ustreamtv][error] This content is not available in your area
```

Meanwhile, I use the Proxy SwitchyOmega extension and the same IP, I can watch it on the browser.
Please help me, Thanks.

**Comment by beardypig** [comment]
Try setting `--https-proxy` too, to the same thing. For legacy reasons they are different. It might be worth defaulting the `https-proxy` to the same as `http-proxy`, but for now you gotta do it yourself.

**Comment by tailorbrands1** [comment]
I tried it all but it didn't work.

**Comment by beardypig** [comment]
You're right, WebSocket connections are not proxied - we'll have to update that.
