### ISSUE TITLE
youtube: 429 Client Error: unknown for url

### ISSUE THREAD

**Issue by limiteddi** [streamlink/streamlink#2537]
/usr/local/bin/streamlink -l debug https://www.youtube.com/watch?v=VqjmhQ_qfhk best --player-external-http --player-external-http-port 10001

```
[cli][debug] OS:         Linux-4.4.0-154-generic-x86_64-with-Ubuntu-16.04-xenial
[cli][debug] Python:     3.7.4
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=VqjmhQ_qfhk
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: VqjmhQ_qfhk
error: Unable to open URL: https://youtube.com/get_video_info (429 Client Error: unknown for url: https://youtube.com/get_video_info?video_id=VqjmhQ_qfhk&el=detailpage)
```
Does anyone experience anything similar with youtube?

**Comment by beardypig** [comment]
Looks like it might be rating limiting you, do you get the error all the time? If you wait a bit does it work? Are you on a shared network, for example a university, or are you connected to a VPN?

**Comment by Media182** [comment]
Got the same problem today. YouTube started to ban IP that are making too many requests it seems. Haven't found any good solution for this yet.

**Comment by gravyboat** [comment]
Closing since this isn't our problem. People should stop abusing Youtube so that they aren't rate-limited.

**Comment by mtcdood** [comment]
@gravyboat it's not the users' fault. I attempted to download a stream yesterday, first one in days, and was blocked. I generally download one stream every couple of days.

**Comment by inthinks** [comment]
@mtcdood What is tool do you use?
