### ISSUE TITLE
youtube error when linking channel's live with unknown YT Video ID

### ISSUE THREAD

**Issue by jwc529** [streamlink/streamlink#2541]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When linking a channel's live link without knowing the Video ID, you get "error: Could not find a video on this page"  It stopped working today.  It works with the YT link with a video ID but this is for a script with an unknown video ID.

### Reproduction steps / Explicit stream URLs to test

1. ...Try command "streamlink https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ/live"   (Sky News Broadcast)
2. ...Try command "streamlink https://www.youtube.com/channel/UCUMZ7gohGI9HcU9VNsr2FJQ/live
3. ...

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ/live
error: Could not find a video on this page

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Only `muxed-streams` have this issue and there's already an issue open for it here: https://github.com/streamlink/streamlink/issues/2539. Closing as duplicate.
