### ISSUE TITLE
Youtube now supports 12 hours of live playback

### ISSUE THREAD

**Issue by ethaniel** [streamlink/streamlink#2542]
I've noticed that Streamlink can access maximum last 2 hours of the Youtube's live playback with --hls-live-offset or --hls-live-edge 9999. However, if I go through their website, I can scroll back 12 hours: https://www.youtube.com/watch?v=ADqneC6Bi18

Is it possible to extend Streamlink as well?

**Comment by back-to** [comment]
the **hls streams** used for the Livestreams with Streamlink **do not support such a long playback**

> Is it possible to extend Streamlink as well?

everything is possible, but this is not worth it.

related to https://github.com/streamlink/streamlink/issues/1520
