### ISSUE TITLE
Crunchyroll subtitle language

### ISSUE THREAD

**Issue by Arcbeat** [streamlink/streamlink#2547]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

Using Streamlink to play Crunchyroll content in VLC is not possible to change the subtitle language. there is no information on this problem in the guide. Can you help me with this? Thank you.

### Expected / Actual behavior

Update Crunchyroll plugin options for language change in subtitles
### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Try using the `--locale` option to change it, you will only get one subtitle track at a time though.

**Comment by Arcbeat** [comment]
ty beardypig the option locale works. if anyone wants how to write:

example:
`streamlink --locale es_LA https://www.crunchyroll.com/es-es/myriad-colors-phantom-world/episode-9-the-strange-tale-of-the-bakumatsu-phantom-691705 best`
now i will close this thread ty beardy
