### ISSUE TITLE
Command-Line Interface problem

### ISSUE THREAD

**Issue by PrinceKaro** [streamlink/streamlink#255]
when I try to run the program at the command prompt it gives the error:
'streamlink' is not recognized as an internal command, operable program or batch file.

attempting to run the program through the 'Run' window (as I used to do with livestreamer) gives a an error as well.

tried both stable and latest releases.

please help?

**Comment by thatlinuxfur** [comment]
You'll probably need to add the streamlink binary dir to your PATH. See this page for pointers:

https://www.java.com/en/download/help/path.xml

**Comment by beardypig** [comment]
@PrinceKaro which OS are you using?

**Comment by beardypig** [comment]
Yeah, but I mean which specific version of Windows :-)

**Comment by PrinceKaro** [comment]
@beardypig  windows 7

**Comment by PrinceKaro** [comment]
also I tried what @thatlinuxfur suggested and it just gives a new error ' failed to create process'

**Comment by beardypig** [comment]
@PrinceKaro right. It sounds like you need to install the [Visual C++ 2015 Runtimes](https://www.microsoft.com/en-gb/download/details.aspx?id=48145) (you need the x86 one, and you might need both if you have a 64 bit version of Windows), and then re-install Streamlink.

**Comment by PrinceKaro** [comment]
@beardypig I tried installing it and it didn't help. there was these errors during the installation though.
[0914:0C5C][2016-12-06T09:18:24]e000: Error 0x80240017: Failed to execute MSU package.
[0618:0AC4][2016-12-06T09:18:24]e000: Error 0x80240017: Failed to configure per-machine MSU package.

also keep in mind that I never had any problems running livestreamer which is very similar.

**Comment by Vangelis66** [comment]
@PrinceKaro said: 

> also keep in mind that I never had any problems 
> running livestreamer which is very similar.

livestreamer on Windows uses Python 2.7, 
whereas streamlink is using an embedded 
edition of Python 3.5.2; this fact alone 
changes minimum system requirements 
and adds the dependency to which @beardypig 
directed you.

It might be that an overzealous A-V suite is 
blocking the streamlink NSIS installer. 
First re-install the MSVC++2015u3 runtime 
(file vc_redist.x86.exe) with your A-V temporarily 
disabled - this is a MS file, IT'S SAFE. Then reboot. 

Then try to re-install latest nightly version from [here](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe), 
again with your A-V suite temporarily disabled - 
I think you can trust the dev team in that 
they have not packaged anything neferious...

Post here any eventual errors during installation - 
then reboot again for your registry and PATH 
to be updated. 

One last thing that I've seen it happen on 
[another project](https://squarepenguin.co.uk/forums/thread-1113-post-4978.html) is that your PATH may already be overcrowded or corrupt; 
in a command prompt execute `echo %PATH%` 
and kindly post here for the devs to inspect; 
it may be that some leftovers need be removed...
Again, many overzealous antivirus apps, through 
their "system-monitoring" modules, have been known 
to deny other apps from modifying PATH; AFAIK, 
even MS's Windows Defender / MSE do the same 
and you have to OK manually the modification...

**Comment by PrinceKaro** [comment]
@Vangelis66 I do have an admin account. I tried everything you said but still got the same errors on the C++ install and when trying to run streamlink

my path is C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Skype\Phone\;C:\Program Files\Livestreamer\;C:\Program Files\Streamlink\bin\

note the last part was added by me, the streamlink installer still does not add anything as it should.

honestly I'm leaning towards it being some weird compatibility issue due to my computer being so old and crappy, it may be there is nothing to be done.

**Comment by beardypig** [comment]
@PrinceKaro do you have all of the updates for Windows installed? There might be something missing stopping you from installing the VC++ runtime.

**Comment by Vangelis66** [comment]
@PrinceKaro said: 

> the streamlink installer still does not add anything as it should

That's a bad sign, not directly related to the VC++ Runtime issue; 
I am not familiar with NSIS,  the language in which the streamlink 
installer is written, perhaps @beardypig could help more here to 
explain the installer's failure... 
Your PATH looks OK to me; you are on Windows 7 32bit then? 

A long shot here, but is your system fully patched with regards 
to Windows Update? **vc_redist.x86.exe** requires some updates 
to be present, for Windows 7 32bit it's **KB2999226**; - if not 
found on the system, the Runtime installer tries to install file 
`Windows6.1-KB2999226-x86.msu` 
The errors you posted [here](https://github.com/streamlink/streamlink/issues/255#issuecomment-265215441) probably come from this attempt. 
MSU package requires the "wsau.exe" process to be able 
to start and run on your system; often times, 
for a successful installation of a .msu update through "wsau.exe" 
one has to temporarily stop **wuauserv** service and retry; 
or stop wuauserv completely through services.msc, reboot, 
install the .msu package and finally re-enable wuauserv.

> due to my computer being so old and crappy

A very old, 2007 bought, Vista laptop here, 
but it is being taken good care of, with all MS 
updates installed, HDD recently replaced, RAM 
increased to 3GB and cleaned internally once a 
year - both MSVC++2015u3 runtime and streamlink 
install (and run) fine here.

> it may be there is nothing to be done. 

If we can get past the MSVC++2015u3 installation issue, 
you could try the portable flavour of streamlink 
(does not modify PATH/registry).

> Edit: for some reason being posted removes some of the backslashes 
> before the ;C:, they are actually there in the real path

Have you used the "Insert Code" button in the post editor header?
This is my %PATH% (Vista SP2 x86)
```
C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\Sy
stem32\Wbem;C:\PROGRA~1\COMMON~1\ULEADS~1\MPEG;C:\Program Files\QuickTime\QTSyst
em\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Bitvise SSH Cli
ent;C:\Program Files\Common Files\Nero\Lib\
```

**Comment by beardypig** [comment]
The installer won't be successful without the VC++ runtime, as it tries to "precompile" the python files using the python binary it just installed. I'm not sure that the PATH would be updated in that case... 

Try the Windows update KB2999226 as @Vangelis66 suggests :-)

**Comment by PrinceKaro** [comment]
@Vangelis66 I do not have widows update on currently partially due to frustration on how long it takes to update on my computer, and partially due to worry that microsoft would try and foist windows 10 upon my computer without permission. I do not see KB2999226 on the list of updates.

due to the ungodly amount of time it would take for my computer to catch up (running the standalone update doesn't work) it is not something I really want to set in motion right at this time, but I'm pretty sure we have found what the problem is.

the original livestreamer still fills my needs for the time being, but when it should cease to function I now know what I likely need to do to get streamlink running.

thank you all for the time you took out of your days to help :)

**Comment by Vangelis66** [comment]
@PrinceKaro wrote: 

> I do not have widows update on currently

Of course, **you** are the ruler of your machine, but running an unpatched OS 
and connecting to the internet with it leaves you vulnerable to attacks made possible 
because loopholes at the OS level have been made public when Microsoft posted their 
updates to patch said loopholes... 
This threat is still real even if all apps you are using have been updated to their latest 
versions and you are running a fully up-to-date Security suite on the machine...

> partially due to frustration on how long it takes to update on my computer

I am the maintainer of my sister's Win7SP1 x64 laptop (she knows nada beyond 
facebook and twitter), indeed what you said had been plaguing the Win7 OS for 
many months, but they have fixed it now by distributing un updated "Update Agent" 
for Win7; visit Dalai's latest [page](http://wu.krelay.de/en/2016-11.htm) and download manually the updates 
on the **Win7 x86** column (that is if you are indeed on 32bit); 
make sure that wuauserv isn't running (Task Manager -> Services Tab) 
and install those downloaded .msu updates manually 
(double-clicking and waiting), one by one, followed by a reboot between them; 
if you are met with trouble, read troubleshooting instructions inside 
Great White North's post in this [link](https://answers.microsoft.com/en-us/windows/forum/windows_vista-update/updates-not-working-it-has-been-searching-for/92cd6922-17f6-4730-b46b-91a480b95dd3) - it's for Vista initially, but same principle apply. 

After you have successfully installed the updates on Dalai's page, 
re-enable Windows Update, reboot, then launch **Check for Updates**;
it shouldn't take more than two hours to find all Important 
and Recommended. BTW, Microsoft have also changed the format of updates 
on Win7+ and instead of many standalone ones they are now 
issuing cumulative ones (Rollups); so it isn't that bad now... 

> due to worry that microsoft would try and foist 
> windows 10 upon my computer without permission

Not applicable now; the free Win7 => Win10 update offer 
expired at the end of last July (29th to be exact), so no more 
GWX stuff is pushed through Windows Update currently. 

> due to the ungodly amount of time it would take for my computer to catch up

Read above...

> (running the standalone update doesn't work)

How so? if it seems to have stuck forever at the "Searching..." stage, 
then, again, read above; plus, KB2999226 has SP1 as a prerequisite...

> but when it should cease to function 
> I now know what I likely need to do 
> to get streamlink running.

Make yourself and everyone else a favour 
and fully update your OS soon, rather than later; 
don't let it become yet another bot!

> thank you all for the time you took out of your days to help

You are welcome; this is an Open Source project, 
all work involved is purely on a voluntary basis...

**Comment by Vangelis66** [comment]
@PrinceKaro wrote:

> [0618:0AC4][2016-12-06T09:18:24]e000: Error 0x80240017: Failed to configure per-machine MSU package.

I found a very interesting discussion on [Stackoverflow](http://stackoverflow.com/questions/31536606/while-installing-vc-redist-x64-exe-getting-error-failed-to-configure-per-machi) explaining this in detail; 
originally created by a Win8.1 user, but contains references to other Win <10 OSes. 

@gravyboat, @beardypig 

I think it'd be wise to add to the documentation that 
for the MSVC++2015u3 runtime installation to succeed 
(on XP<Win<10), you need [Windows 10 Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48234) 
to be installed on the system (it should be, 
if you have Windows Update enabled!).

**Comment by beardypig** [comment]
Ah cool. Maybe that is the magic key to it :-D

**Comment by PrinceKaro** [comment]
@Vangelis66 I'll look into that. Thanks again

**Comment by beardypig** [comment]
@PrinceKaro try out this version of the installer [streamlink-0.1.0-vcredist-7a50314.exe](https://s3.amazonaws.com/streamlink-builds/beardypig/streamlink-0.1.0-vcredist-7a50314.exe) and see if it fixes your issue!

**Comment by PrinceKaro** [comment]
@beardypig yeah both the path installation and actual program work for me now as they should, even though I haven't fully updated windows yet. will still probably do that as some point as Vangelis showed me the patch for the windows update issue.

you guys are the greatest, thanks for all your help! :)
