### ISSUE TITLE
ITV Player unable to open URL

### ISSUE THREAD

**Issue by TIGHazard1** [streamlink/streamlink#2555]
- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

ITV Player/Hub for the main ITV channel do not open and give an error message.

### Reproduction steps / Explicit stream URLs to test

Type "streamlink itv.com/hub/itv".

Other ITV Hub URL's such as hub/itv2 or hub/citv continue to work.

### Log output

[cli][info] Found matching plugin itvplayer for URL itv.com/hub/itv
error: Unable to open URL: http://cdn.dar.itv.com/private/aHR0cDovL2NzbS1lLnBsYXkuZGFyLml0di5jb20vY3NtL2V4dGxpdmUvMjQ3MTYyMTUubTN1OD95by5hYz10cnVlJnlvLmFkPWZhbHNlJnBtPWZyZWUmcmFuZG9tPTU2OTk0ODU2ODc0ODA1NzE0MjAmYXJlYT1pdHZwbGF5ZXIuc2ltdWxjYXN0JnNvdXJjZT1zaW11bGNhc3QmaGRldmlkPXgmc2l6ZT1wYXR0ZXJuJnN1cGVydGFnPWRmbHQsc2ltJnVzPWFubyZzaXRlPWl0diZvc3Zlcj0xMCZjaGFuYnJhbmQ9aXR2MSZvcz13aW5kb3dzJmhtb2Q9NjYmcHY9YnJvd3Nlci40LjEmcGxheWVyPWh0bWw1LmRlc2t0b3AmZG09bmxpJmhtYW49Y2hyb21lJnRkdXI9MjE2MDAmdHBhcnRzPTEmYXJwPXgmZGVmYXVsdD1EZWZhdWx0UGF0dGVybiZwbGlzdD1zaW1hZHJlcGxhY2VtZW50JnBsZmNpZD1zaW1hZHJlcGxhY2VtZW50/endpoint?hdnea=st=1563543051~exp=1563564651~acl=/*~data=nohubplus~hmac=0ebaf6d4f22f101378a6c7ed3903c1999f6b28efd29ee05763e5ec7bf0d27896&yo.channel=24716215 (404 Client Error:  for url: http://csm-e.play.dar.itv.com/csm/extlive/24716215.m3u8?yo.ac=true&yo.ad=false&pm=free&random=5699485687480571420&area=itvplayer.simulcast&source=simulcast&hdevid=x&size=pattern&supertag=dflt,sim&us=ano&site=itv&osver=10&chanbrand=itv1&os=windows&hmod=66&pv=browser.4.1&player=html5.desktop&dm=nli&hman=chrome&tdur=21600&tparts=1&arp=x&default=DefaultPattern&plist=simadreplacement&plfcid=simadreplacement)

### Additional comments, screenshots, etc.

I have noticed the site plays a ITV Hub promo when starting a livestream on the website itself before loading that stream. This does not occur for the other channels.

**Comment by beardypig** [comment]
Confirmed. I get the same error, will take a look a bit later.

**Comment by johnthecracker** [comment]
Your stream:

https://www.youtube.com/watch?v=YlJHBJNJu-0

```
C:\>streamlink.exe --player=mpv.exe --http-no-ssl-verify "https://www.youtube.com/watch?v=YlJHBJNJu-0" best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=YlJHBJNJu-0
error: This plugin does not support protected videos, try youtube-dl instead
```

I can watch this directly with mpv.

**Comment by johnthecracker** [comment]
if I made a comment here it was in my error. 
I have nothing to comment on this issue.

**Comment by nacorv** [comment]
Is there anything to differentiate getting the ad roll m3u8 and the livestream? I'd like to fix this but all I can think of doing is excluding elements in the playlist array (line 75+ of the plugin). I'm replying to ask for more information about the problem than I've been able to ascertain by myself.

**Comment by beardypig** [comment]
Seems like only the flash stream is supported for ITV1 at the moment...

**Comment by nacorv** [comment]
itv.com/hub/itv does point to the flash stream? it must be possible to skip over that segment of the playlist but i am unsure how to implement this.

**Comment by ReeceFarmerHGA** [comment]
@beardypig Hi, was any progress made on this issue? Still getting it when I try to stream ITV1

**Comment by ryanjgillies** [comment]
I too was wondering if any progress has been made. On the latest development version I receive this error for all ITV channels.

ITV is showing every match of the Rugby World Cup, so it would be handy to find a solution!

**Comment by mkbloke** [comment]
I'm getting the same issue with ITV1 and now ITV4 as well.  All other channels on ITV Hub play OK though.

**Comment by beardypig** [comment]
Looks like they have DRM'd the ITV1 and ITV4 streams now and they aren't available without DRM anymore.

**Comment by ryanjgillies** [comment]
I seem to be posting in a lot of closed topics - apologies.

Just a note for others really who might stumble onto this. I downloaded the updated itvplayer plugin, but started receiving an `rtmpdump` error - it seems for some reason or another this wasn't installed on my distro up until this point. A quick and simple `sudo apt install rtmpdump` solved the problem.

```
streamlink "https://www.itv.com/hub/itv" best --config /home/imperial/.scripts/streamlink.uk -l debug
[session][debug] Plugin bbciplayer is being overridden by /home/imperial/.config/streamlink/plugins/bbciplayer.py
[session][debug] Plugin itvplayer is being overridden by /home/imperial/.config/streamlink/plugins/itvplayer.py
[cli][debug] OS:         Linux-4.15.0-1057-oem-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.15+
[cli][debug] Streamlink: 1.2.0+22.g6ac9ee0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'live': True, 'playpath': 'itv1static@45475', 'rtmp': 'rtmpe://cp532701.live.edgefcs.net/live', 'flv': '-', 'swfVfy': 'https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf'}, redirect=False> (Could not open stream: Unable to find `rtmpdump' command)
error: Could not open stream <RTMPStream({'live': True, 'playpath': 'itv1static@45475', 'rtmp': 'rtmpe://cp532701.live.edgefcs.net/live', 'flv': '-', 'swfVfy': 'https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf'}, redirect=False>, tried 1 times, exiting
```

**Comment by beardypig** [comment]
Weird, it should check that RTMP is installed... should double check that :)
