### ISSUE TITLE
Streams wont launch anymore since today

### ISSUE THREAD

**Issue by Magciool** [streamlink/streamlink#256]
Hey since today I have the problem that streams don't launch anymore. 
Streamlink gets stuck at "Found matching plugin twitch for URL twitch.tv/XXXXX" for around 30 seconds.
Then the python cmd windows just closes. 
http://i.imgur.com/DF9YyVv.png
When I turned off my PC yesterday it was runing all fine.

Using Win7 64bit
Streamlink 0.1.0

**Comment by thatlinuxfur** [comment]
Have you tried the latest nightly build?

https://streamlink.github.io/install.html#windows-binaries
