### ISSUE TITLE
France TV 

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2562]
hi there, 

I m still unable to use francetv streams for a while, it seems their streams are splitted , some are audio, other videos.  

happens with youtube-dl also

 /usr/local/bin/youtube-dl https://www.france.tv/france-2/direct.html -F
[FranceTVSite] direct: Downloading webpage
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading video JSON
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
[info] Available formats for 006194ea-117d-4bcf-94a9-153d999c59ae:
format code                          extension  resolution note
hls-audio-aacl-98-Audio_Description  mp4        audio only [qad]
hls-audio-aacl-98-Francais           mp4        audio only [fra]
hls-audio-aacl-98-Version_Originale  mp4        audio only [qaa]
hls-235                              mp4        256x144     235k , avc1.42C01E, 25.0fps, video only
hls-534                              mp4        384x216     534k , avc1.42C01E, 25.0fps, video only
hls-1117                             mp4        640x360    1117k , avc1.42C01E, 25.0fps, video only
hls-1594                             mp4        960x540    1594k , avc1.4D401F, 25.0fps, video only
hls-2866                             mp4        1280x720   2866k , avc1.4D401F, 25.0fps, video only (best)

streamlink https://www.france.tv/france-2/direct.html best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-2/direct.html
[cli][info] Available streams: 144p (worst), 216p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)

Is there any solution to get a stream that include the audio?

**Comment by back-to** [comment]
provide a proper debug log

**Comment by campones** [comment]
streamlink --loglevel debug https://www.france.tv/france-2/direct.html best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.13.0-170-generic-x86_64-with-Ubuntu-14.04-trusty
[cli][debug] Python:     2.7.6
[cli][debug] Streamlink: 1.0.0+34.ge96c725
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-2/direct.html
[plugin.pluzz][debug] Country: FR
[plugin.pluzz][debug] Video ID: 006194ea-117d-4bcf-94a9-153d999c59ae
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 144p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 216p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 360p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 540p (language=fra, name=Francais)
[stream.hls][debug] Using external audio tracks for stream 720p (language=fra, name=Francais)
[cli][info] Available streams: 144p (worst), 216p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 14406480; Last Sequence: 14406484
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 14406482; End Sequence: None
[stream.hls][debug] Adding segment 14406482 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 14406483 to queue
[stream.hls][debug] Adding segment 14406484 to queue
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 14406480; Last Sequence: 14406484
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 14406482; End Sequence: None
[stream.hls][debug] Adding segment 14406482 to queue
[stream.hls][debug] Adding segment 14406483 to queue
[stream.hls][debug] Adding segment 14406484 to queue
[stream.mp4mux-ffmpeg][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-7675-84 -i /tmp/ffmpeg-7675-85 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-7675-84
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-7675-85
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Download of segment 14406482 complete
[stream.hls][debug] Download of segment 14406483 complete
[stream.hls][debug] Download of segment 14406484 complete
[stream.hls][debug] Download of segment 14406482 complete
[stream.hls][debug] Download of segment 14406483 complete

**Comment by bastimeyer** [comment]
> Is there any solution to get a stream that include the audio?

I have already told and shown you that the streams do have audio:
https://github.com/streamlink/streamlink/issues/2499#issuecomment-501225372

> [cli][debug] OS: Linux-3.13.0-170-generic-x86_64-with-Ubuntu-14.04-trusty
> [cli][debug] Python: 2.7.6
> [cli][debug] Streamlink: 1.0.0+34.ge96c725

Neither your OS (whose LTS support has already stopped), nor Python or Streamlink are up-to-date. You are probably using an old ffmpeg build as well, which could be the cause of your issue. And AFAIK, Ubuntu 14.04 doesn't come with ffmpeg in its own repos (the libav issue), so it's unknown which ffmpeg version you are using here. Get the version output by running `ffmpeg -version`.

**Comment by campones** [comment]
ffmpeg version N-76159-gda43e9e Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-postproc --enable-libfaac --enable-libfdk_aac --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libvpx --enable-librtmp --enable-libass --enable-libfreetype --extra-libs=-ldl --enable-openssl
  libavutil      55.  4.100 / 55.  4.100
  libavcodec     57.  8.100 / 57.  8.100
  libavformat    57. 10.101 / 57. 10.101
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 12.100 /  6. 12.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.100 /  2.  0.100
  libpostproc    54.  0.100 / 54.  0.100

**Comment by xaltsc** [comment]
VoidLinux here with latest versions of everything. I had the same problem up until I installed `ffmpeg`. Perhaps it should be made clearer that `streamlink` depends on `ffmpeg` if that is well the case ? The void package itself doesn't depend on `ffmpeg`, not even as an optional package as the arch one does.

**Comment by campones** [comment]
apparently I have ffmpeg, which I compiled myself but quite some years ago. I have my own reasons not to update it.  
I ll try with an up to date version of ffmpeg on a dev box

**Comment by beardypig** [comment]
@xaltsc it doesn’t strictly depend on ffmpeg, but there might be some streams that will not work without it. This is a more recent thing, where more and sites use dash or separate video and audio streams. For example, the higher resolution videos on YouTube require ffmpeg, but the lower resolution ones do not. So, it depends... 

It might need to be highlighted more clearly in the docs though, or we could add a log message if there are streams missing because they require ffmpeg. 

If you know who maintains the void package, I would suggest to them to make ffmpeg optional at least :)

**Comment by campones** [comment]
ironically I installed a new box last month with up to date ffmpeg and streamlink.  and the output stream has sound, yes, but it's not sync..

**Comment by campones** [comment]
so yea, it's actually extremely weird but when I launch the command in a shell, it's working normally, I see the
ffmpeg -nostats -y -i /ffmpeg/tmp/xxxx in htop as ffmpeg is muxing the audio and the video, but in a cronjob, it just won't work.  Really I don't get it. 

here is a log of the cronjob 

ffmpeg version N-95098-gb9f8ab3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-libfdk_aac --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libass --enable-libfreetype --extra-libs=-ldl --enable-openssl
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.100 / 58. 59.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-3/direct.html
[cli][info] Available streams: 144p (worst), 216p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 540p (hls)
Input #0, mpegts, from 'pipe:0':
  Duration: N/A, start: 11502.203256, bitrate: N/A
  Program 16727 
    Stream #0:0[0x21]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, progressive), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc

there is no audio

and here the same command from the shell 

ffmpeg version N-95098-gb9f8ab3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --enable-libfdk_aac --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libass --enable-libfreetype --extra-libs=-ldl --enable-openssl
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 59.100 / 58. 59.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 59.100 /  7. 59.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-3/direct.html
[cli][info] Available streams: 144p (worst), 216p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 540p (hls-multi)
Input #0, mpegts, from 'pipe:0':
  Duration: N/A, start: 1.400000, bitrate: N/A
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt470bg, progressive), 960x540 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101](fra): Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 121 kb/s

**Comment by campones** [comment]
it's actually an issue.. that I do not really understand.

When I run the stream as root (the script that trigger the stream) it works fine but when running it with cronjob (using webmin for example) it doesn't. (well no sound) 
If I put the cron line in the crontab in /etc/crontab then it works. Must be some kind of users permissions issues.

Be still the issue with synchronization audio/video persist sadly

**Comment by gravyboat** [comment]
@campones https://github.com/streamlink/streamlink/issues/3438#issuecomment-751124859 has the solution for the desync. I'm going to lock this now since it's very old.
