### ISSUE TITLE
Updated WWEN plugin PLZ

### ISSUE THREAD

**Issue by whitetop** [streamlink/streamlink#2564]
## Plugin Issue

WWE have now gone to 2.0 and is doing 1080p VOD, plugin needs updating PLZ

### Description

WWE have now gone to 2.0 and is doing 1080p VOD, plugin needs updating PLZ I have tried letmeatit and still same problem and adownloader. uses index.m3u8 and not bitrate.m3u8 master has added code as well.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by NikoofDeath** [comment]
I'd be willing to provide my WWE Network account temporarily if needed (although I'd recommend the devs who made free trial accounts for the development of the plugin check to see if they have any email offers from WWE, they've been offering 3 months for 99 cents lately).
The site has had a complete redesign and moved to a different streaming provider (used to use BAMTech, moved to Endeavor), so I imagine very little of the existing code will be of use (even the URL structure has changed, for example, Wrestlemania 20 used to be http://network.wwe.com/video/v31362293, and is now https://watch.wwe.com/episode/WrestleMania-20-5563)

**Comment by beardypig** [comment]
99¢!? OUTRAGEOUS! Unfortunately they didn't give me that offer, but I'll see if I can get another free trial...

**Comment by whitetop** [comment]
I would give my login details but its not mine as i used a friends account and don't think they would be happy. but @NikoofDeath is right.

**Comment by rgoro** [comment]
I have a network account and am also a passable developer, I could try to hack in support for the new version, if someone is willing to mentor me a bit.

I won't be able to do this before next weekend (first of august) so if someone can get there first, go for it

**Comment by PerilousTheGreat** [comment]
I made a program in python that allows you to download videos from the WWE network. I finished it today, it's not robust so you have to be very careful when downloading, one mistake and it'll crash.

**Comment by whitetop** [comment]
> I made a program in python that allows you to download videos from the WWE network. I finished it today, it's not robust so you have to be very careful when downloading, one mistake and it'll crash.

I use the python way but like it simple or when i want to run a batch code so wanted this plugin fixed.

I don't see any harm on your app.

**Comment by beardypig** [comment]
I have put together an updated plugin that should work. I haven't tested it too much (only started writing it a few hours ago), but it seems to work got all VOD and the current live stream. It would be good to get some people to test it out :)

**Comment by whitetop** [comment]
> I have put together an updated plugin that should work. I haven't tested it too much (only started writing it a few hours ago), but it seems to work got all VOD and the current live stream. It would be good to get some people to test it out :)

I can test if you like

**Comment by rgoro** [comment]
> I have put together an updated plugin that should work. I haven't tested it too much (only started writing it a few hours ago), but it seems to work got all VOD and the current live stream. It would be good to get some people to test it out :)

I'll test it when I get back home tonight

**Comment by beardypig** [comment]
To test the new plugin, grab [wwenetwork.py](https://raw.githubusercontent.com/streamlink/streamlink/0605ba67487399fdbdc63401fb939fb78e09b282/src/streamlink/plugins/wwenetwork.py) and sideload it. Check in the docs for how to [Sideload a Plugin](https://streamlink.github.io/cli.html?highlight=sideload#sideloading-plugins) :)

**Comment by NikoofDeath** [comment]
Found one weird bug, for NXT Takeover XXV (https://watch.wwe.com/episode/WWE-NXT-TakeOver-XXV-95224), the normal show link plays the preshow (https://watch.wwe.com/program/WWE-NXT-TakeOver-XXV-Pre-Show-95222) in streamlink, and vice versa. Haven't noticed this with any other shows with preshows though.

**Comment by beardypig** [comment]
Thanks @NikoofDeath, I'll take a look... weird, probably something to do with the contentId being misidentified :)

**Comment by whitetop** [comment]
> Thanks @NikoofDeath, I'll take a look... weird, probably something to do with the contentId being misidentified :)

LetMeAtIt has sorted the plugin for his app, might be good to check and see what is missing?

**Comment by beardypig** [comment]
@whitetop I dunno what that is, I might be useful- but the issues is likely a small bug, I just didn’t have time to look yet.

**Comment by whitetop** [comment]
> @whitetop I dunno what that is, it might be useful- but the issues is likely a small bug, I just didn’t have time to look yet.

Its a app that people use to download from the WWEN.

No rush as life comes first.

**Comment by NikoofDeath** [comment]
@beardypig Another issue (and one that I had with the old plugin), might just be a player issue on my end - when using streaming mode, the playback ends prematurely (about 15 seconds or so), issue doesn't happen when using an output file. I believe this is due to streamlink loading the last part of the stream, recognizing the end of stream, and closing before finishing playback of the loaded content.

**Comment by beardypig** [comment]
@NikoofDeath, try the `--player-no-close` option and see if that helps. Your assessment sounds correct and is probably a bug in streamlink in general, are you using Windows?

**Comment by rgoro** [comment]
> @NikoofDeath, try the `--player-no-close` option and see if that helps. Your assessment sounds correct and is probably a bug in streamlink in general, are you using Windows?

I had that same issue and I'm using linux, will test this too later today

**Comment by NikoofDeath** [comment]
@beardypig Yup, that fixes it!

**Comment by PerilousTheGreat** [comment]
https://videos2.sendvid.com/49/a7/kgk7nipa.mp4?validfrom=1564425757&validto=1564432957&rate=200k&burst=1000k&ip=82.8.55.93&hash=ZK5XJBmN3NqoRU5AeCeRONWVUak%3D

Just as you man get the fix I finished making the program 😂

**Comment by PerilousTheGreat** [comment]
Just as you guys fix it I finish making my program xd

https://streamable.com/mt7ep

**Comment by beardypig** [comment]
@NikoofDeath I believe I have resolved the issue where the preshow played instead of the actual show: [wwenetwork.py](https://raw.githubusercontent.com/beardypig/streamlink/wwenetwork-fix/src/streamlink/plugins/wwenetwork.py)

**Comment by Kamakzie** [comment]
Hey guys I got this working but when I run it just plays on demand Smackville. How do I change to the live stream?

**Comment by beardypig** [comment]
@Kamakzie, what URL did you put? Can you show me the out of of 
```
streamlink -l debug YOUR_URL_HERE
```
?

**Comment by Kamakzie** [comment]
D:\Program Files (x86)\Streamlink>streamlink -l debug watch.wwe.com
[Streamlink for Windows v1.0.0 - Git f7ac894]
[session][debug] Plugin wwenetwork is being overridden by D:\Program Files (x86)\Streamlink\plugins\wwenetwork.py
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.0.0+f7ac894
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)

**Comment by beardypig** [comment]
@Kamakzie update the plugin to this one [wwenetwork.py](https://raw.githubusercontent.com/beardypig/streamlink/wwenetwork-fix/src/streamlink/plugins/wwenetwork.py), and use the URL of the show you want to watch eg.
```
streamlink https://watch.wwe.com/episode/WWE-NXT-TakeOver-XXV-95224 best
```

**Comment by Kamakzie** [comment]
Do you know what the URL as for live programming?

**Comment by beardypig** [comment]
You can find it on the website, normally on the "Featured" tab: `https://watch.wwe.com/channel/2026`

**Comment by Kamakzie** [comment]
Thanks for the tip.

**Comment by Kamakzie** [comment]
I wish there was a way to fast-forward and rewind but beggars can't be choosers LOL

**Comment by beardypig** [comment]
@Kamakzie you can probably use `--player-passthrough hls` for this plugin, its kinda defeats the purpose of streamlink, because it just hands the HLS URL over to your player. There is also the [--hls-start-offset](https://streamlink.github.io/cli.html#cmdoption-hls-start-offset) option, if you just wanna skip the first 5 mins or something.

**Comment by NikoofDeath** [comment]
@beardypig Would it be possible to integrate support for WWE Network's timestamping? For shows with timestamps, the site includes links at the bottom bar, for example https://watch.wwe.com/episode/WrestleMania-20-5563?startPoint=13997.4. Obviously --hls-start-offset can achieve this same purpose, but it would be nice to be able to use the links directly.

**Comment by beardypig** [comment]
@NikoofDeath `13997.4` is in seconds? ie. 3 hours 53 minutes and 17.4 seconsds?

**Comment by whitetop** [comment]
I guys i'm stumped on this matter since the update, i like to save the files so i can watch on my tv in the bedroom but since the update i've had a problem,

I keep getting this error as i save as a ts file then lossless to mp4 after so i can batch download

"Error parsing ADTS frame header!
[AVBSFContext @ 0000000002f7d780] Failed to send packet to filter aac_adtstoasc for stream 0
av_interleaved_write_frame(): Invalid data found when processing input"

I've tried many things, dex muxing and remuxing and nothing, i can download as mp4 but audio is playing up after 00.06.00 on the time after that its way out of sync, ts files are fine but will not play on my player.

Any help?

**Comment by beardypig** [comment]
How are you converting the files? Works for me using ffmpeg.

**Comment by whitetop** [comment]
I use 
"streamlink --user --pass  https://watch.wwe.com/episode/WWE-NXT-UK-102121 360p -o test.ts"

And use a bat file with
"for %%a in ("*.ts") do ffmpeg -i "%%a" -vcodec copy -acodec copy "%%~na.mp4"

**Comment by whitetop** [comment]
Update, seems even on updating ffmpeg its still the same, from reading letmeatit twitter the problems seems to be set on wwe site a 30fps but is meant to be 29.7fps could this be why the header problem is happening?

**Comment by PerilousTheGreat** [comment]
I got a GUI for the network, not sure if this is related
I'd be glad to give it out

https://streamable.com/qpuzi

**Comment by dadho** [comment]
i tryied today and it gave error downloading 

[Streamlink for Windows v1.0.0 - Git f7ac894]
[cli][info] Found matching plugin wwenetwork for URL https://watch.wwe.com/episode/Prime-Target-TakeOver-Toronto-2019-102365
error: No playable streams found on this URL: https://watch.wwe.com/episode/Prime-Target-TakeOver-Toronto-2019-102365
[End of Streamlink for Windows with ExitCode 1]

can anyone confirm, that is not working? and how to fix

**Comment by whitetop** [comment]
> i tryied today and it gave error downloading
> 
> [Streamlink for Windows v1.0.0 - Git [f7ac894](https://github.com/streamlink/streamlink/commit/f7ac8947b80822c5cbfbf9d6f13e314e53865507)]
> [cli][info] Found matching plugin wwenetwork for URL https://watch.wwe.com/episode/Prime-Target-TakeOver-Toronto-2019-102365
> error: No playable streams found on this URL: https://watch.wwe.com/episode/Prime-Target-TakeOver-Toronto-2019-102365
> [End of Streamlink for Windows with ExitCode 1]
> 
> can anyone confirm, that is not working? and how to fix

I am just having sync problems which i have emailed beardypig about and am awaiting on a reply from him!!!!

I know WWEN are tweaking the site and has done since 2.0 was released and is making big problems on downloading,audio sync and downloading wrong titles.

**Comment by bastimeyer** [comment]
> Streamlink for Windows v1.0.0

You are obviously not using the latest version. You need to run the **latest development version**, or else you will be using the old plugin.

**Comment by dadho** [comment]
> > Streamlink for Windows v1.0.0
> 
> You are obviously not using the latest version. You need to run the **latest development version**, or else you will be using the old plugin.


its was working until monday, last time i used..
the only improvement i made was changing the code in wwenetwork.py to:

from __future__ import print_function

import json
import logging
import re

from streamlink import PluginError
from streamlink.cache import Cache
from streamlink.plugin import Plugin, PluginArguments, PluginArgument
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream

log = logging.getLogger(__name__)


class WWENetwork(Plugin):
    url_re = re.compile(r"https?://watch.wwe.com/(channel)?")
    content_id_re = re.compile(r'''"DiceVideoId"\s*:\s*(\d+)''')
    stream_url = "https://dce-frontoffice.imggaming.com/api/v2/stream/{id}"
    live_url = "https://dce-frontoffice.imggaming.com/api/v2/event/live"
    login_url = "https://dce-frontoffice.imggaming.com/api/v2/login"
    API_KEY = "cca51ea0-7837-40df-a055-75eb6347b2e7"

    customer_id = 16
    arguments = PluginArguments(
        PluginArgument(
            "email",
            required=True,
            metavar="EMAIL",
            requires=["password"],
            help="""
        The email associated with your WWE Network account,
        required to access any WWE Network stream.
        """
        ),
        PluginArgument(
            "password",
            sensitive=True,
            metavar="PASSWORD",
            help="""
        A WWE Network account password to use with --wwenetwork-email.
        """
        )
    )

    def __init__(self, url):
        super(WWENetwork, self).__init__(url)
        self.session.http.headers.update({"User-Agent": useragents.CHROME})
        self.auth_token = None

    @classmethod
    def can_handle_url(cls, url):
        return cls.url_re.match(url) is not None

    def request(self, method, url, **kwargs):
        headers = kwargs.pop("headers", {})
        headers.update({"x-api-key": self.API_KEY,
                        "Origin": "https://watch.wwe.com",
                        "Referer": "https://watch.wwe.com/signin",
                        "Accept": "application/json",
                        "Realm": "dce.wwe"})
        if self.auth_token:
            headers["Authorization"] = "Bearer {0}".format(self.auth_token)

        kwargs["raise_for_status"] = False
        log.debug("API request: {0} {1}".format(method, url))
        res = self.session.http.request(method, url, headers=headers, **kwargs)
        data = self.session.http.json(res)

        if "status" in data and data["status"] != 200:
            log.debug("API request failed: {0}:{1} ({2})".format(data["status"], data.get("code"), "; ".join(data.get("messages", []))))
        return data

    def login(self, email, password):
        self.logger.debug("Attempting login as {0}", email)
        # sets some required cookies to login
        data = self.request('POST', self.login_url,
                            data=json.dumps({"id": email, "secret": password}),
                            headers={"Content-Type": "application/json"})
        if "authorisationToken" in data:
            self.auth_token = data["authorisationToken"]

        return self.auth_token

    def _get_media_info(self, content_id):
        """
        Get the info about the content, based on the ID
        :param content_id: contentId for the video
        :return:
        """
        info = self.request('GET', self.stream_url.format(id=content_id))
        return self.request('GET', info.get("playerUrlCallback"))

    def _get_vod_id(self):
        #  check the page to find the contentId
        res = self.session.http.get(self.url)
        m = self.content_id_re.search(res.text)
        if m:
            return "vod/{id}".format(id=m.group(1))

    def _get_live_id(self):
        res = self.request('GET', self.live_url)
        for event in res.get('events', []):
            return "event/{sportId}/{propertyId}/{tournamentId}/{id}".format(**event)

    def _get_streams(self):
        if not self.login(self.get_option("email"), self.get_option("password")):
            raise PluginError("Login failed")

        if self.url_re.match(self.url).group(1):
            content_id = self._get_live_id()
        else:
            content_id = self._get_vod_id()

        if content_id:
            self.logger.debug("Found content ID: {0}", content_id)
            info = self._get_media_info(content_id)
            if info.get("hlsUrl"):
                for s in HLSStream.parse_variant_playlist(self.session, info["hlsUrl"]).items():
                    yield s
            else:
                log.error("Could not find the HLS URL")


__plugin__ = WWENetwork
