### ISSUE TITLE
Request for plugin for Zee News (India)

### ISSUE THREAD

**Issue by kumarpranay** [streamlink/streamlink#2566]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

This is a news channel from India. It provides news in India and is free to watch on the official website But this does not resolve in Streamlink (tried with v1.1.1)

### Example stream URLs

1. https://zeenews.india.com/live-tv

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by snake24564** [comment]
Use inspect element:

https://z5ams.akamaized.net/zeenews/index.m3u8?hdnts=st=1566282319~exp=1566285319~acl=/*~hmac=5104d3b0797c209c63b06bfc28b22827535caf9242ea39688148c5876457f6b8

and 

https://z5ams.akamaized.net/zeenews/tracks-v1a1/exp=1566370364~acl=%2f*~data=hdntl~hmac=f25935770abcd0edb647bb7bd8ecbd32f665fefe3c6ae86ee2d5561800ef8bee/mono.m3u8

Your Welcome!
