### ISSUE TITLE
Live news channel "HABER GLOBAL" Support

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#2567]
Hi,

hopefully you can add Plugin support for the HQ Live News Channel Haber Global from Turkey.

https://www.haberglobal.com.tr

Greetings
Rotarum

**Comment by beardypig** [comment]
This site appears to use Daily Motion to host the video, which streamlink already supports. If the URL doesn't change you should just be able to use `https://www.dailymotion.com/embed/video/x7df5ih`.

**Comment by gravyboat** [comment]
Even if it does change this would just be a wrapper and we've discussed multiple times about not supporting those so I'm closing this.

**Comment by beardypig** [comment]
I don't actually see the problem with wrappers, although @back-to did have a cool plugin that would do it automatically.. Maybe we could have a universal plugin that handles all the wrappers, like a mapping for URL to proxied plugin or sutin.

**Comment by gravyboat** [comment]
@beardypig If there were some kind of universal wrapper that might work. My only issue with wrappers is that it makes plugins take longer to load, and we have users on very low resource devices where this negatively impacts them. There was relatively large discussion about this some time last year.
