### ISSUE TITLE
--hls-live-restart isn't working

### ISSUE THREAD

**Issue by channelmars** [streamlink/streamlink#2572]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

--hls-live-restart no longer grabs YouTube live streams from the very beginning.

### Expected / Actual behavior

--hls-live-restart used to grab YouTube live streams from the beginning every time.

### Reproduction steps / Explicit stream URLs to test

1. ... streamlink --hls-live-restart -o 'outfile' url best 
2. ... https://www.youtube.com/watch?v=hHW1oY26kxQ
3. ... https://www.youtube.com/watch?v=IFAcqaNzNSc

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
What happens now?

**Comment by channelmars** [comment]
It just downloads the live stream in progress, not from the very beginning.

**Comment by beardypig** [comment]
Does it go back 5 minutes, 1 minute, 2 hours, anything like that?

**Comment by channelmars** [comment]
Nope, it only starts at the point where you begin downloading.

**Comment by beardypig** [comment]
OK. I will take a look.

**Comment by channelmars** [comment]
Thanks a lot!

**Comment by back-to** [comment]
#2542

**Comment by megapro17** [comment]
> #2542

It's not duplicate

**Comment by megapro17** [comment]
It just downloads one second of present time and stops

**Comment by back-to** [comment]
@megapro17 

**share a debug log**, because it works normally here.

```
$ streamlink "https://www.youtube.com/watch?v=hHW1oY26kxQ" -l debug --hls-live-restart
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.1.1+59.g8bf450a
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1415539; Last Sequence: 1418418
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1415539; End Sequence: None
[stream.hls][debug] Adding segment 1415539 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1415540 to queue
[stream.hls][debug] Adding segment 1415541 to queue
[stream.hls][debug] Adding segment 1415542 to queue
[stream.hls][debug] Adding segment 1415543 to queue
```

**Comment by megapro17** [comment]
@back-to Sorry stream ended, I'll share debug log next time

**Comment by scottbernstein** [comment]
It still works for me -- for any stream that allows for "rewinding".  There are plenty of streams that intentionally don't.
________________________________

**Comment by megapro17** [comment]
That stream is allowed rewinding. Maybe problem that it was restarted
couple times (same url).

пн, 5 авг. 2019 г. в 07:37, scottbernstein <notifications@github.com>:

**Comment by scottbernstein** [comment]
Yes, if a youtube stream restarts, there is no guarantee that the previous content will remain.
________________________________

**Comment by megapro17** [comment]
I could it watch on YouTube

пн, 5 авг. 2019 г., 18:18 scottbernstein <notifications@github.com>:

**Comment by deadwilder** [comment]
Also not working here. The output file begins at the point where the live video was currently on, not from the beginning.

**Comment by gravyboat** [comment]
@deadwilder We can't do anything with the info you're providing. Some streams don't even allow rewinding. We'll need a full debug log (`-l debug` on your command) to see any sort of details.

**Comment by deadwilder** [comment]
Here is the debug log:

`[Streamlink for Windows v1.2.0 - Git 12f1e99]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.2.0+12f1e99
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://youtu.be/RjeHeyUbBus
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: RjeHeyUbBus
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[End of Streamlink for Windows with ExitCode 0]`

**Comment by gravyboat** [comment]
@deadwilder Did it work at some point in the past? Does this stream even allow rewinding to the beginning? Some don't.

**Comment by deadwilder** [comment]
The stream does allow rewinding and I'm able to see the start if I open the url on the browser.
