### ISSUE TITLE
plugin request: LINE LIVE (live.line.me)

### ISSUE THREAD

**Issue by ssaqua** [streamlink/streamlink#2573]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Japanese live streaming platform from LINE corporation

### Example stream URLs

1. https://live.line.me 
2. https://live.line.me/channels/520/

### Additional comments, screenshots, etc.

PR to follow which adds support for live broadcasts only, no archived broadcasts.
Don't believe there is any geo-restriction. Some broadcasts may need a channel follow or require payment/subscription judging from the API response (keys `isOAFollowRequired`, `paidLive`, `subscriptionLive` in the JSON).

Separately, just have a question about supporting --hls-live-restart. An example m3u8 chunklist during a broadcast might look like this:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1012
#EXTINF:1.837,
media-u964gtsk9_1012.ts
#EXTINF:1.87,
media-u964gtsk9_1013.ts
#EXTINF:3.714,
media-u964gtsk9_1014.ts
#EXTINF:1.829,
media-u964gtsk9_1015.ts
#EXTINF:1.876,
media-u964gtsk9_1016.ts
#EXTINF:1.876,
media-u964gtsk9_1017.ts
```
The filenames for all the media segments are predictable, so we could go back and download from media-u964gtsk9_1.ts to the current media sequence. The m3u8 is continuously updated so it contains only this limited number of parts. Is there a way to make --hls-live-restart try to get segments earlier than the first segment in the playlist?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Interesting question regarding live restart, at the moment it’s not something that is very easy. I’m working on a major refactor of the stream downloading code, we can make the classes easier to extend for custom behaviour like that.
