### ISSUE TITLE
Plugin development

### ISSUE THREAD

**Issue by 88kfn** [streamlink/streamlink#2578]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Im working at plugin developing for russian tv channels for personal use.
At the moment im done with number of them, but having trouble with last one (https://ren.tv/live) 

### Expected / Actual behavior

As i already recognized there is no any documentation for plugin developing so im trying to 
work with existed ones. The problem is half of them are not working now and each of wbpages has individual structure. Some of them are having m3u8 playlist in webpage structure so its not too difficult to output it and get stream.
The question is what should i do if webpage doesnt have anything except iframe
In my code i already output iframe and then im trying to get stream from it (using parts of existed plugins) but eventually there is no playable strems found.

### Additional comments, screenshots, etc.
The only possibly usefull thing that i found in webpage structure is hls stream, it looks like list of stings such as:
`https://mobdrm.mediavitrina.ru/hls-live9/streams/ren-tv/ren-tv.m3u8?cdn=https://edge02r.mediavitrina.ru&netprav=/hls-vod1/streams/netprav/nmg_ren-tv_16x9_v1/index.m3u8&e=1564990796`

But when im trying to input it somewhere im getting 403 error Access denied

Looking for avice, what should i pay attention to?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Hey @88kfn, that the kind of thing you could be using your browsers dev tools for. I see there is a request to `https://media.mediavitrina.ru/api/v1/nmg/playlist/ren-tv_as_array.json?rnd=12345678` (the `rnd` parameter looks like unix epoch time in millis), and it returns a list of HLS and DASH streams. There is a reference to DRM in the page source too, so I don't know if they will be DRM'd - they are geo-locked, and I don't have a proxy in Russia. 

Feel free to submit PRs if you want the plugins added to Streamlink, you'll also probably get some tips on how to improve them :)

**Comment by back-to** [comment]
`https://ren.tv/live` is the same as the `onetv.py` plugin
it would just need a small update

https://github.com/streamlink/streamlink/blob/fb6a00c86bbf752b578ea317cdede242a2b4e836/src/streamlink/plugins/onetv.py

**Comment by malvinas2** [comment]
> Looking for avice, what should i pay attention to?
+1 

Maybe it would be possible to write some kind of tutorial explaining the devolopment of a plugin for e.g. the most frequently used options to unveil the actual stream link? 
And/or perhaps it is possible to categorize the existing plugins according the used technique, so that they could be used as a kind of template?

**Comment by back-to** [comment]
#117
