### ISSUE TITLE
Using streamlink to a browser on a website

### ISSUE THREAD

**Issue by nsmith1024** [streamlink/streamlink#2584]
Hello,

I wanted to make a website where a user could visit, type in a twitch streamers name into a box on my website, and be able to watch that LIVE stream in their browser using HLS.js HTML5 player in the browser. This is like a regular website where the browser is not on the same LAN as streamlink, its a regular website where streamlink resides on the webserver.

To do all that, I would use a HTML form that would accept the steamers name, when submit is pressed in the browser, the form would call a php script on my server which would pass that stream name to steamlink, then streamlink would fetch the stream corresponding to the twitch streamers name, and forward the LIVE stream to the browser to be played.

Is all this possible with streamlink? to forward LIVE M3U8 HLS stream to a browser from a web server? Anybody knows how i can do this? maybe with HLS proxy maybe?

What about CORS errors. If steamlink gives the browser the URL of a stream on a different website it will result in a CORS error because the browser will be on my site, while  the browser is trying to access a stream on an different site resulting in CORS error.

**Comment by bastimeyer** [comment]
Streamlink is not an HLS proxy and what you are asking for was never the purpose of Streamlink/Livestreamer, so no, this won't work. I'm also pretty sure that this is against Twitch's or any other streaming provider's ToS.

**Comment by nsmith1024** [comment]
Oh sorry, didnt know it would go against their terms of service to play their stream. Oh well, it was just an idea.... but .... isnt this what streamlink is doing playing their stream?

**Comment by bastimeyer** [comment]
There is a difference between watching a stream on your own by using a tool like Streamlink and re-distributing (stolen) content on your own site. There's also a difference between embedding streams via official methods and re-hosting (stolen) content on your own.

**Comment by nsmith1024** [comment]
Yes of course your obviously correct, so people are in real trouble then 
https://twitchls.com/

**Comment by beardypig** [comment]
Both those sites use the [official Twitch Embedding method](https://dev.twitch.tv/docs/embed/video-and-clips/). 

What you are asking is out of scope for what Streamlink is trying to achieve. You can of course look at the Twitch plugin and see how to extract the HLS URLs, or even use the `--stream-url` option to get the HLS URL - the rest is up to you.
