### ISSUE TITLE
New WWE Network Plugin stopped working

### ISSUE THREAD

**Issue by NikoofDeath** [streamlink/streamlink#2585]
## Plugin Issue
- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

Presumably due to updates to the website (I know they have been working on fixing some issues with the new site), the WWE Network plugin is no longer able to find streams.

### Reproduction steps / Explicit stream URLs to test

1. Install latest streamlink nightly
2. Try using any WWE Network link (i.e. https://watch.wwe.com/episode/NXT-TakeOver-Toronto-2019-102316)

### Log output

streamlink https://watch.wwe.com/episode/NXT-TakeOver-Toronto-2019-102316 best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.1.1+74.g0f011ae
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin wwenetwork for URL https://watch.wwe.com/episode/NXT-TakeOver-Toronto-2019-102316
[cli][debug] Plugin specific arguments:
[cli][debug]  --wwenetwork-email= (email)
[cli][debug]  --wwenetwork-password= (password)
[plugin.wwenetwork][debug] Attempting login as 
[plugin.wwenetwork][debug] API request: POST https://dce-frontoffice.imggaming.com/api/v2/login
[plugin.wwenetwork][debug] Searching for content ID
[plugin.wwenetwork][debug] Loading page config
error: No playable streams found on this URL: https://watch.wwe.com/episode/NXT-TakeOver-Toronto-2019-102316

### Additional comments, screenshots, etc.

There had been audio sync problems with the network, although I believe this was across all sources and not a streamlink issue, and their solution for this issue might have caused the plugin to break.

**Comment by beardypig** [comment]
@NikoofDeath I've PR'd a fix for this :)
