### ISSUE TITLE
Quest and Quest Red

### ISSUE THREAD

**Issue by trancer1994** [streamlink/streamlink#2588]
## Plugin Request

- [ ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Quest and Quest Red are two UK TV channels which provide general entertainment on Sky and Freeview. They have streams of their channels on their website as well as the ability for you to watch their shows on-demand. Their on-demand service is called Quest OD. The streams aren't drm-protected and they're not geoblocked as far as I know, but they do use dash (.mpd) and they do have expiry tokens and things like that. See example stream URLs below. I will provide one for you to get a flavour of what you're up against. 

### Example stream URLs

1. https://dplaynordics-live-01.akamaized.net/questuk/14/1/dash/Quest/exp=1565976092~acl=%2f*~data=hdntl~hmac=0b05372952a581153c490defbd8d645ea7f2843a217dfb725adf0a941db2cfbe/303307114-init?version_hash=5661745a
2. The page which streams Quest is https://www.questod.co.uk/channel/quest
3. https://dplaynordics-live-01.akamaized.net/questuk/17/1/dash/Quest_Red/exp=1565976312~acl=%2f*~data=hdntl~hmac=23f289e11aae3bf2ab093d187d8d9c1a54ea097d865d4681e01b03db50fd31bb/168355500-init?version_hash=17790acfa3 (Quest Red Stream)
4. The streaming page for Quest Red is https://www.questod.co.uk/channel/quest-red

However, when trying to open the streaming url in Firefox, I get the error message 'Video can't be played because the file is corrupt'. I am trying to get the URL from the page so I can listen to it in an external player like VLC, and Streamlink has said there is no plugin to handle the url. 

### Additional comments, screenshots, etc.

[I am new and this is my first issue so if I'm not doing something right please don't go off on one at me)

**Comment by beardypig** [comment]
They both seems to be protected by DRM (a problem) and be geoblocked (not a problem) :) 

Maybe sometimes they are not DRMed?

**Comment by trancer1994** [comment]
I’m not sure if they’re drm-ed all the time. What I do know though is that they have /exp/xxxxxxxxx (xxxxxxx replaced by numbers) in the urls which means the links expire within a certain amount of time, and I think they do it in millions of seconds. Can’t be sure though. If it can’t be supported though due to the drm protection, I would at least be content with a URL I can actually play, since everytime I open the URL in a browser I get the error message in the post above.

**Comment by beardypig** [comment]
The reason you get that error when trying to play it in firefox is because it is DRMed. You can also just give Streamlink the URL, but it will say something along the lines of "This stream is protected by DRM". I have check throughout the day and I not seen any time where it has not beed protected by DRM.

I'm afraid you're out of luck on this one.

**Comment by trancer1994** [comment]
Awwww. It’s ok anyway. It did the same on ITV but I was able to bypass that by removing some stuff from the URL, but it hasn’t worked here it seems. The least I can probably expect from this is to get a URL that I can play, even if you can’t implement it in Streamlink.

**Comment by beardypig** [comment]
I'm going to close this for now. I've added a new label for DRMed streams - just in case we want to review them at a later date.
