### ISSUE TITLE
Douyu（斗鱼）request 401 Client Error

### ISSUE THREAD

**Issue by aliofwind** [streamlink/streamlink#2589]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Can't watch douyu stream using streamlink

### Reproduction steps / Explicit stream URLs to test

1. https://www.douyu.com/30

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin douyutv for URL https://www.douyu.com/30
error: Unable to open URL: https://capi.douyucdn.cn/api/v1/room/30?aid=wp&cdn=ws&client_sys=wp&time=1566025999&auth=1e637147e6e09c5dfe5163c3ad719771 (401 Client Error: Unauthorized for url: https://capi.douyucdn.cn/api/v1/room/30?aid=wp&cdn=ws&client_sys=wp&time=1566025999&auth=1e637147e6e09c5dfe5163c3ad719771)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
#2328

**Comment by Erk-** [comment]
The only downloader I know of that currently works with douyu is https://github.com/zhangn1985/ykdl
