### ISSUE TITLE
vk.com No playable streams

### ISSUE THREAD

**Issue by viperdriver2000** [streamlink/streamlink#2595]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

cant download video.

### Reproduction steps / Explicit stream URLs to test

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat https://vk.com/video-75371233_456246230
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

### Log output

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat --loglevel debug https://vk.com/video-75371233_456246230 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230
PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink>

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat -p vlc --loglevel debug https://vk.com/video-75371233_456246230 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat -p vlc --loglevel debug https://vk.com/video-75371233_456246230 best --output video-75371233_456246230
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat -p vlc --loglevel debug https://vk.com/video-75371233_456246230 best --output video-75371233_456246230 --force
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink> .\streamlink.bat -p vlc --loglevel debug https://vk.com/video-75371233_456246230 best --output video-75371233_456246230 --force --record video-75371233_456246230
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230
PS E:\Downloads\web\streamlink-portable-1.1.1-py3.6.5-amd64\streamlink>

### Additional comments, screenshots, etc.

-

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by viperdriver2000** [comment]
hi, 
for my problem it isnt fixed :(

```
PS C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe https://vk.com/video-75371233_456246230
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe --loglevel debug https://vk.com/video-75371233_456246230 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe -p vlc --loglevel debug https://vk.com/video-75371233_456246230 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
[plugin.vk][debug] video ID: -75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230

PS C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe https://vk.com/video-75371233_456246230 -l info
[cli][info] Found matching plugin vk for URL https://vk.com/video-75371233_456246230
error: No playable streams found on this URL: https://vk.com/video-75371233_456246230
```

i tryed another vk video an this works.
```
PS C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe https://vk.com/videos-75371233?z=video-75371233_456246412%2Fpl_-75371233_-2 best
[cli][info] Found matching plugin vk for URL https://vk.com/videos-75371233?z=video-75371233_456246412%2Fpl_-75371233_-2
[cli][info] Available streams: 240p (worst), 360p, 480p (best)
[cli][info] Opening stream: 480p (http)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
PS C:\Program Files (x86)\Streamlink\bin>
```

anyone more idears?

**Comment by gravyboat** [comment]
Doesn't seem like you're using the nightly build, this isn't in the stable yet.
