### ISSUE TITLE
RTHK TV 31 & 32

### ISSUE THREAD

**Issue by fhoshino** [streamlink/streamlink#2598]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

A local public broadcasting television station from Hong Kong. RTHK TV31/32 is one of a few disinterested news channel which provide fare perspective reports compared to major aired television in Hong Kong.

### Example stream URLs

1. https://www.rthk.hk/tv
(No distinct url for different channel, only button below the video feed to switch channel)

### Additional comments, screenshots, etc.
![chrome_2019-08-22_20-54-51](https://user-images.githubusercontent.com/771955/63516200-2233f800-c51f-11e9-8460-bb368a8ec4f2.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Seems like these channels are available as static streams

https://www.rthk.hk/feeds/dtt/rthktv31_https.m3u8
https://www.rthk.hk/feeds/dtt/rthktv32_https.m3u8
