### ISSUE TITLE
Muted audio in M3U8 file 

### ISSUE THREAD

**Issue by Doriloran** [streamlink/streamlink#2599]
- [] I have read the contribution guidelines.
- [x] This is a feature request

### Description

I'm dealing with an M3U8 file where my audio file is muted in select areas and I'm trying to unmute it. I cannot read the file itself and don't know what to edit and what to leave as it is. Can anyone help me unmute this file? (the only thing I have left out of the below M3U8 is the address to the vod itself) 

?player=twitchweb&nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3A%22ef9ac289e81ca1d3%22%2C%22expires%22%3A1566606078%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A470818051%7D&nauthsig=ef1a68fa28251da9e7bf1282a74e1cda18bb8f99&allow_audio_only=true&allow_source=true

**Comment by gravyboat** [comment]
This is out of scope for Streamlink so we won't be able to help you.
