### ISSUE TITLE
pixiv sketch R18 login error

### ISSUE THREAD

**Issue by smilebombx** [streamlink/streamlink#2606]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Howdy, so, my streamlink script broke when trying to record a pixiv sketch live stream today on August 28th. Before, my script was fine and working since July 21st, however, when I restarted my recording PC today, and  restarted the script, I got an error stating "failed to login."  This applies only to pixiv sketch R18  (adult) streams; normal R15 and under streams present the same error, however, streamlink still successfully records and writes them to my hard drive. 

### Expected / Actual behavior

Usually, whenever I restart my PC, all I have to do is edit the file output name as to not over write previous broadcasts, and it records perfectly fine.

### Reproduction steps / Explicit stream URLs to test

1. Login to pixiv, and the pixiv sketch live, and enable your account to be able to view adult (R18) content within your profile settings
2. run streamlink on any streams online labeled "R18" which require a valid pixiv login to record

### Log output

```
C:\Users\****\Desktop\stream switch>streamlink https://sketch.pixiv.net/@katsurai/lives/284594448891186512 best --pixiv-username **** --pixiv-password **** -o  "e:\stream vods\enoy -2019-7-10-.mp4"
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@katsurai/lives/284594448891186512
[plugin.pixiv][error] Failed to log in.
error: No playable streams found on this URL: https://sketch.pixiv.net/@katsurai/lives/284594448891186512
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
#2515
