### ISSUE TITLE
new VOD links not handled by plugin

### ISSUE THREAD

**Issue by matthiasschulenburg** [streamlink/streamlink#2608]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Zattoo changed url for vod. These new url are not handled correct. Saving of vod files not longer possible.

### Reproduction steps / Explicit stream URLs to test

1. start zattoo website
2. change to recordings
3. start playback of a recording
4. copy url
5. use zattoo plugin to save recording to a file -> doesn't work

### Log output

[Streamlink for Windows v1.0.0 - Git f7ac894]
error: No plugin can handle URL: https://zattoo.com/tc/ptc_recordings_all_recordings?recording=182845765
[End of Streamlink for Windows with ExitCode 1]

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
there are to many different URLs, just use the normal URL.
https://github.com/streamlink/streamlink/blob/2c1affcdcd8890357a0584df017de26d7657ff4b/tests/plugins/test_zattoo.py#L42-L43

Ref https://github.com/streamlink/streamlink/pull/2887
