### ISSUE TITLE
plugin-request for https://www.muenchen.tv/livestream/

### ISSUE THREAD

**Issue by jpfl** [streamlink/streamlink#2609]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Web livestream of private TV station in Munich Germany covering each year every day of the Octoberfest with a live show from a beerhal for 3 hours a day with reruns.
rest of the year local info, news, shows about Munich and Bavaria

### Example stream URLs

1. https://www.muenchen.tv/livestream/
2. ...
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
they have static urls, for 1080p

```
streamlink hls://https://muenchentv.iptv-playoutcenter.de/muenchentv/muenchentv.stream_1/playlist.m3u8 best
```
