### ISSUE TITLE
Streamlink 0.2.0 release

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#261]
Quite a bit of activity past couple of weeks.

:+1: for another release? Any blockers?

**Comment by beardypig** [comment]
I'm all for a new release! 

With all the changes and additions maybe `0.2.0` is a more worthy version number? :D

**Comment by cdrage** [comment]
@beardypig since this release is mostly bug fixes / plugin fixes, I think 0.1.1 would be better, since 0.2.0 indicates a major feature was implemented.

**Comment by beardypig** [comment]
5 new plugins were added :) I personally like to see the minor version incremented when new features are added, and the patch version incremented with only bug fixes.

**Comment by cdrage** [comment]
@beardypig Ahh yeah, you're right. Let's do a 0.2.0 release then since more plugins were added :)

**Comment by beardypig** [comment]
Didn't mean to browbeat you in to it ;)

**Comment by gravyboat** [comment]
I'll need to change the milestones since they're all set to 0.1.1 right now. Do we want to wait until your PRs are merged @beardypig?

**Comment by fishscene** [comment]
Could we also include instructions on the Github front page on how to upgrade to a new release? Something like:
---------------------------------------
pip install streamlink --upgrade
or
pip install streamlink --u
---------------------------------------

Also, do we have pre-built installers or packages for Windows/Mac/Linux?
[Issue 84](https://github.com/streamlink/streamlink/issues/84)
A pre-built installer would go a long way to helping folks get it installed on various systems. 
Note: Some would like to install streamlink without a separate install of Python.
Thoughts?

**Comment by gravyboat** [comment]
@fishscene The source code install docs already note the process for upgrading: https://streamlink.github.io/install.html#source-code though that could probably be less obtuse. Regarding pre-built installers we have them for Windows, and there are some packages for Linux (though none for Mac). The Windows installer doesn't require a separate Python installation (https://streamlink.github.io/install.html#other-platforms) as it has a binary available.

**Comment by fishscene** [comment]
@gravyboat Perfect! Any way to link to this page on the front-page? I'd like to push for making it _really_ easy to find and install streamlink from the front page. Let's add this link to the front page in the Installation section:
https://streamlink.github.io/install.html
Maybe something like:

> Windows/Mac/Linux Installation and Upgrade Instructions can be found [here](https://streamlink.github.io/install.html).

Thoughts?

**Comment by gravyboat** [comment]
From the main page of the repo? I don't see any reason not to include it. We link to the docs but it could be more obvious.

**Comment by fishscene** [comment]
Yes. Let's definitely make it obvious on the main page of the Repo such that at a glance, it is super-easy to get started with installing and updating. :)

We can make this a part of the 0.2.x release - not necessarily a blocker for the 0.2.0 release. Thanks!

**Comment by fishscene** [comment]
I'll attempt to do so. I've never used a git before and I attempted my hand at it in the early days of streamlink, but I'll definitely try again. :)

Am I correct in that this is the file that needs to be modified?
https://github.com/streamlink/streamlink/blob/master/README.md

**Comment by gravyboat** [comment]
Yeah that's the one! Make sure that you fork the repo first (this will create a personal copy for you that you can work on then create a PR for review).

**Comment by beardypig** [comment]
Now that more people are installing Streamlink, we are getting quite a few issues relating to installing Streamlink on earlier versions of Windows, particularly XP/Vista/7. 

The current installer does not support Windows XP, we should make this clear in the docs (relates to #84).
We need to resolve the problem with the VC++ runtime issue too (see #250), this could be a potential blocker, if not, it's certainly an important issue. It's going to keep coming up. Either we change the installer or update the docs, there is ongoing discussion on #250.

**Comment by gravyboat** [comment]
Agreed, we should clarify in the docs that we don't support XP, and I'm against supporting XP in any way going forward, it's just too much to maintain and test. I think we should hold off on a new build until #250 is resolved. Personally I would like to hold off on 0.2.0 until the 5 currently open PRs are resolved and merged in, but I can understand if we don't want to wait that long.

**Comment by fishscene** [comment]
https://github.com/streamlink/streamlink/pull/265
Done I think. I made the subsections under "Installation" bold, which made it pop a bit, but I'm not sure if that's what is wanted. Feedback welcome. :) Also, first ever pull request.

**Comment by bastimeyer** [comment]
Is there anything that is still blocking the `0.2.0` release?

I'm asking because I'm seeing a ton of issues regarding the Windows installer which have already been fixed (missing runtime libs and install dir not set in the PATH env var).
#250
#255 
#267 
#275 
#279 
#284 
streamlink/streamlink-twitch-gui#347
streamlink/streamlink-twitch-gui#348

**Comment by beardypig** [comment]
I don't of anything blocking `0.2.0`, there are a couple of pending PRs but they can wait. I think it would be good to get `0.2.0` out of the door sooner rather than later. As @bastimeyer said, there are quite a few Windows installer issues being reported that have been fixed since the last release, and I suspect that means plenty more people get the error that don't report it.

**Comment by cdrage** [comment]
@gravyboat Sorry for the delay! Was skiing in Banff, but I'll push out 0.2.0 sometime today or tomorrow :)

**Comment by beardypig** [comment]
Alright for some... ;)

**Comment by beardypig** [comment]
On a more serious note, there is currently a `print` statement in the `master` branch (see #297, 'twas my bad), it's been fixed in #292 so should merge that before the release, or I/someone can create a PR specifically for that.

**Comment by gravyboat** [comment]
@beardypig I merged it.

**Comment by beardypig** [comment]
Well, I missed it in the first case, so... :)

**Comment by cdrage** [comment]
@beardypig @gravyboat Uploaded what should be the correct installer now to the release page.. Don't know *what* happened before.

**Comment by gravyboat** [comment]
@cdrage Good stuff, I'll check it when I'm back on my windows machine tonight. Thanks!

**Comment by beardypig** [comment]
Cool. We can get the travis builds set up for the next release :-)

**Comment by gravyboat** [comment]
I just checked on my Windows machine via the download from the release page and I'm still seeing `0.1.0` for the version report.

**Comment by gravyboat** [comment]
Can anyone else confirm they're seeing what I am seeing on Windows? I've done a clean install and ensured any related files are purged but I'm still seeing `0.1.0` as the version.

**Comment by bastimeyer** [comment]
It's still showing `0.1.0`...

**Comment by cdrage** [comment]
Okay, hopefully it's fixed _once and for all_. Screw-up on the build script from my end.

But this is the output, so the newest .exe on the release page should work:

```
Output: "/home/wikus/dropbox/dev/streamlink/build/nsis/streamlink-0.2.0.exe"
Install: 5 pages (320 bytes), 2 sections (1 required) (2096 bytes), 1753 instructions (49084 bytes), 1061 strings (19323 bytes), 1 language table (302 bytes).
Uninstall: 2 pages (128 bytes), 
1 section (1048 bytes), 34 instructions (952 bytes), 69 strings (1235 bytes), 1 language table (198 bytes).
Datablock optimizer saved 98387 bytes (~0.6%).

Using lzma compression.

EXE header size:               82944 / 70144 bytes
Install code:                  11992 / 71501 bytes
Install data:               14549653 / 33875794 bytes
Uninstall code+data:           13191 / 18749 bytes
CRC (0x6923191C):                  4 / 4 bytes

Total size:                 14657784 / 34036192 bytes (43.0%)
Installer written to /home/wikus/dropbox/dev/streamlink/build/nsis/streamlink-0.2.0.exe
Success!
The installer should be in /home/wikus/dropbox/dev/streamlink/build/nsis.
```

**Comment by bastimeyer** [comment]
Just tested it 20 secs ago and it's still showing `0.1.0`.

**Comment by cdrage** [comment]
Really odd..

I checked streamlink.cfg when using `makeinstaller.sh` and it shows 0.2.0:
```
[Application]                                                                                                                                                                                                                                                                     
name=Streamlink                                                                                                                                                                                                                                                                   
version=0.2.0                                                                                                                                                                                                                                                                     
entry_point=streamlink_cli.main:main                                                                                                                                                                                                                                              
icon=../win32/doggo.ico                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
[Python]                                                                                                                                                                                                                                                                          
version=3.5.2                                                                                                                                                                                                                                                                     
format=bundled                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
[Include]                                                                                                                                                                                                                                                                         
packages=requests                                                                                                                                                                                                                                                                 
         streamlink                                                                                                                                                                                                                                                               
         streamlink_cli                                                                                                                                                                                                                                                           
pypi_wheels=pycryptodome==3.4.3                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                  
files=../win32/rtmpdump > $INSTDIR                                                                                                                                                                                                                                                
      ../win32/LICENSE.txt > $INSTDIR                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                  
[Command streamlink]                                                                                                                                                                                                                                                              
entry_point=streamlink_cli.main:main                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                  
[Build]                                                                                                                                                                                                                                                                           
directory=nsis                                                                                                                                                                                                                                                                    
nsi_template=installer_tmpl.nsi                                                                                                                                                                                                                                                   
installer_name=/home/wikus/dropbox/dev/streamlink/build/nsis/streamlink-0.2.0.exe  
```

**Comment by bastimeyer** [comment]
Try deleting the `build/nsis` folder before creating a new installer.

**Comment by cdrage** [comment]
@bastimeyer 

done. updated again.

**Comment by bastimeyer** [comment]
Nope...

```
basti@basti-VM-Win7 MINGW64 /c/Program Files (x86)/Streamlink/pkgs/streamlink
$ cat __init__.py | grep __version__
__version__ = "0.1.0"
```

**Comment by beardypig** [comment]
Did you do a `pip install .` or `python setup.py install` before building it?

**Comment by cdrage** [comment]
@beardypig Yup... Seems odd that it doesn't update. May be something wrong with a previous installation on my side.

**Comment by Junior1544** [comment]
I've never had streamlink or livestreamer installed on my windows 10 computer...   if you give me a link to download (or how you want me to install) what you want tested, I'd be happy to install it on my computer for you to see??

**Comment by beardypig** [comment]
Maybe it doesn't upgrade unless you did `pip install -e .` originally and the same to upgrade.

**Comment by beardypig** [comment]
@Junior1544 it's the installer on the release page.

**Comment by Junior1544** [comment]
I downloaded the 2.0 .exe install from 
https://github.com/streamlink/streamlink/releases
and installed it.
Windows Smart Screen tried to block it from running, but I installed it anyway.
it installed into the Program Files (x86) directory, I used the default.  

From the command prompt, I ran:
streamlink -V
and it told me I am running 0.1.0

and that's from a fresh install with no previous streamlink install on my computer at all...

--James

**Comment by gravyboat** [comment]
@cdrage Can you try another build if you have time in the next couple of days?

**Comment by beardypig** [comment]
I can upload a build of the installer if you want @gravyboat

**Comment by gravyboat** [comment]
@beardypig Can you modify the release page with the newest version? If not I can do it, just don't have time to do the build right now since I'm working.

**Comment by beardypig** [comment]
Yep, updated it. Do you have time to test it?

**Comment by gravyboat** [comment]
@beardypig Yeah I have time this evening, will do so right now.

**Comment by gravyboat** [comment]
@beardypig I'll check it later tonight when I'm on my Windows box.

**Comment by gravyboat** [comment]
@beardypig I'm seeing `0.2.0` now so the clean rebuild did the trick!

**Comment by beardypig** [comment]
OK. Well, we got there in the end... 

I was going to suggest that we get the automatic release builds set up (#328) and release a 0.2.1 version as a fix for the installer before merging anything else. Some people will have the old incorrect installer still, and it would probably remove some confusion to put out a 0.2.1 release :-) That  way everyone will have the same latest version.

**Comment by gravyboat** [comment]
@beardypig I merged one PR last night since we said we would after we packaged up `0.2.0`. I'm fine with releasing a `0.2.1` release anyways.

**Comment by gravyboat** [comment]
I'm going to close this since the release is working correctly. If we want to do another one we can open a new issue.

**Comment by bastimeyer** [comment]
Can we get a new release?
I'm relying on the output of `--version` in the Twitch GUI and would like to be able to have a working output, so I can have `>=0.2.1` as a dependency (because of #293, it's currently set to `>=0.2.0`).
I'm also intending on publishing a new release today there, so I'd really appreciate having a new release here if possible. 😄
