### ISSUE TITLE
plugin-request for https://www.bigtexan.com/live-stream/

### ISSUE THREAD

**Issue by jpfl** [streamlink/streamlink#2610]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

live stream from americas most famous streakhouse on route 66 where people can order a 72oz steak and if they make it in 1 hour time it's a free meal.
this stream is live 24/7 and during restaurant opening hours shows the raised on a stage table where contestants try to conquer this steak meal.
the website own stream often crashes and does not run very smooth with their plugin.
it's hosted on angelcam streaming service

### Example stream URLs

1. https://www.bigtexan.com/live-stream/
2. https://v.angelcam.com/iframe?v=9klzdgn2y4
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This as well as https://github.com/streamlink/streamlink/issues/2609 seem like ads and (to me) area far too specific.

**Comment by back-to** [comment]
It is just a webcam, not really worth it.
