### ISSUE TITLE
Question about user-agent/differencies from youtube-dl

### ISSUE THREAD

**Issue by Abalieno** [streamlink/streamlink#2611]
## Issue

- [ x] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

I'm just trying to understand what is going on. I used both youtube-dl and streamlink to download some HLS videos, and by passing them manually authorization keys.

Until today they both worked fine, now instead youtube-dl starts downloading, but after a few minutes it stops with the timer simply not progressing anymore. Meanwhile streamlink still works (with the exact same parameters being passed on the same videos).

What could be the differences between the two? Is it possible that the site is trying to block youtube-dl but streamlink works around it?

I suppose their behavior is very similar, so I initially thought it might be an issue of user agent, but changing the user agent in youtube-dl didn't fix anything.

So what else could differentiate them from the perspective of the server that is serving those files (and breaking youtube-dl somehow)?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Abalieno** [comment]
Can't I have an hint? You surely know if the user agent is the only element that differs.

**Comment by gravyboat** [comment]
@Abalieno We are not youtube-dl support, nor do we provide support for questions like this. If we did all of our time would be spent on this sort of issue instead of improving Streamlink.
