### ISSUE TITLE
Crunchyroll plugin no longer works

### ISSUE THREAD

**Issue by KingChaka** [streamlink/streamlink#2619]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Crunchyroll website seems to have been reconfigured.
Plugin returns: "streamlink.plugin.crunchyroll.CrunchyrollAPIError: user could not be found"

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://www.crunchyroll.com/dr-stone/episode-8-stone-road-786948 best
2. ...
3. ...

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/dr-stone/episode-8-stone-road-786948
[utils.l10n][debug] Language code: en_US
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created with ID: 69de80c3427a689b9d91992f445eb05a
[plugin.crunchyroll][debug] Using saved credentials
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Works fine for me on that exact episode. Try [purging your credentials](streamlink https://www.crunchyroll.com/dr-stone/episode-8-stone-road-786948 best).

**Comment by KingChaka** [comment]
Purging absolutely worked. My mistake.
