### ISSUE TITLE
Packaging streamlink for different linux distributions.

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#262]
What we have:
- Archlinux (stable and -git packages in AUR)
- Gentoo
- NixOS
- openSUSE
- Solus
- Ubuntu (webupd8 ppa)
- Void

WIP:
- openSUSE (I've modified the livestreamer rpm `.spec` file and [submitted a request](https://build.opensuse.org/request/show/444737) to upstream)
- Fedora (with small tweak to the above mentioned rpm `.spec` file it builds fine and it should also build on other rpm-based distributions)

**Comment by mmetak** [comment]
Seems my rpm `.spec` was [accepted upstream](https://build.opensuse.org/request/show/444737) and streamlink should appear in openSUSE repositories soon. ;-)

**Comment by Junior1544** [comment]
This is wonderful!

**Comment by mmetak** [comment]
Hey @beardypig. How would that look like? Wouldn't that be a bit too much to track?
Distros usually have their own way to flag an outdated package in some way?

**Comment by beardypig** [comment]
Just a list of the names and email address of the maintainers. Every time there is a release, we just send a mail to all of them notifying them of the new release. They can do whatever with the information :)

**Comment by mmetak** [comment]
@beardypig something like this https://github.com/mmetak/streamlink/commit/ca18b556eb05f4112e8fc4a1949676021af0999c ?

**Comment by beardypig** [comment]
@mmetak, you know, just like that :)

**Comment by bastimeyer** [comment]
@mmetak You've said in a different thread a while ago that you were talking to the maintainer of the livestreamer package of the arch community repo. Is he willing to add the streamlink package into the official repo or how does this process work? What's the current status of this?
The AUR packages are not that nice to install... On my old laptop with a core2duo@1.3ghz, the python-pycryptodome dependency alone takes almost 10mins to build and test. We need precompiled packages in the official repos.

**Comment by mmetak** [comment]
@bastimeyer I've sent an email to the maintainer of livestreamer package and I also asked another TU before if he's willing to import it. Waiting for maintainers reply and I had no luck with the other TU because he doesn't use it he already maintains a shitload of packages. ;-)

In the meantime you can get the binaries from my obs repo...
[streamlink-0.2.0-1-any.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/streamlink-0.2.0-1-any.pkg.tar.xz)
[streamlink-git-0.2.0.r0.g2358e7a-0-any.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/streamlink-git-0.2.0.r0.g2358e7a-0-any.pkg.tar.xz)
[python-pycryptodome-3.4.3-1-x86_64.pkg.tar.xz](http://download.opensuse.org/repositories/home:/metakcahura/Arch_Extra/x86_64/python-pycryptodome-3.4.3-1-x86_64.pkg.tar.xz)

**Comment by Techwolf** [comment]
I am currently working on an updated ebuild for my gentoo overlay. The current one, version 0.1.0, is broken on my system with an requests depend error even though I have the right requests depend install. I am currentelly upto the new pycryptodome depends. It apears that streamlink can only handle pycryptodome and not pycryptodomex that can be install along side distro supplied pycrypto. While I could do a "move" feature in gentoo to rename pycrypto to pycryptodome, it would break all the packages that depend on pycrypto. Al tho now I think about it, there is a way around that via a virtual ebuild, but that still breaks existing ebuilds. And PROVIDES is banned in gentoo portage.

**Comment by mmetak** [comment]
Fedora also doesn't have `pycryptodome` in their repos and they apply this [patch](http://pkgs.fedoraproject.org/cgit/rpms/python-streamlink.git/tree/python-streamlink-0.3.0-pycrypto.patch) for streamlink to use `pycrypto` instead. Gentoo has `pycrypto` so, maybe that could help?

**Comment by Techwolf** [comment]
Thanks for the tip. I might just go that route and test it.

**Comment by mmetak** [comment]
@Techwolf also check [here](https://github.com/gentoo/gentoo/pull/2975) if you haven't already. ;-)

**Comment by saboya** [comment]
@Techwolf I have a working ebuild in my overlay if it helps: https://github.com/saboya/saboya-overlay

It has a patch to use the namespaced pycryptodome since it clashes with the old pycrypto in Gentoo.

**Comment by Techwolf** [comment]
@saboya I just commit one to my overlay, I just needed a working streamlink for my system. What I did was created an updated one that did not add any new depends. I use the one patch and configure it to use pycountry instead of iso*

**Comment by mmetak** [comment]
@bastimeyer & other archlinux users

Good news. Giancarlo Razzolini (archlinux TU) contacted me and said that he would like to import the `streamlink` stable package to community repo while dropping the `livestreamer` package to aur. With this it should be much easier & faster to install `pacman -S streamlink`. ;-)

**Comment by beardypig** [comment]
@mmetak nice!

**Comment by gravyboat** [comment]
This is fantastic @mmetak! Thanks for the update.

**Comment by mmetak** [comment]
@grazzolini Do you still plan on importing this package to community repo?
I won't update it in aur as you asked.

**Comment by grazzolini** [comment]
@mmetak 
Yes, I plan. But I wasn't able fo fix an issue I had and I'll need to also add the python-iso3166 and python-iso639 packages to the repos. Feel free to update your PKGBUILD for now.

**Comment by beardypig** [comment]
`pycountry` is also an option if you set the `STREAMLINK_USE_PYCOUNTRY` env variable :)

**Comment by grazzolini** [comment]
@beardypig 
Yes. And I substituted cryptodome for python-crypto. But the issues were manifesting themselves on the chroot that is uses to build archlinux packages. Also, if I recall correctly, even when setting the variable, the tests don't use pycountry. Anyway, I'll probably fix those issues soon enough.

**Comment by beardypig** [comment]
The tests use which ever package is available, if both are available then it runs both sets of tests otherwise only one. If you are having difficulty building streamlink reliably and easily let us know and we can work to fix it!

**Comment by mmetak** [comment]
@grazzolini What kind of issues are you having? I made a quick modified pkgbuild file that uses `python-crypto` and `python-pycountry` and it builds fine in clean chroot. [Here's the log.](https://build.opensuse.org/package/live_build_log/home:metakcahura/streamlink/Arch_Extra/x86_64)
[PKGBUILD](https://build.opensuse.org/package/view_file/home:metakcahura/streamlink/PKGBUILD?expand=1)

**Comment by grazzolini** [comment]
@mmetak
Using a slightly different PKGBUILD + patch than yours I can make it work: [PKGBUILD](https://paste.xinu.at/wv50e9/)

I expect it to be soon on archlinux repos.

**Comment by mmetak** [comment]
It's in the `community` repo! ;-)

**Comment by beardypig** [comment]
Would it be useful for us to add a `STREAMLINK_USE_PYCRYPTO` option as well? Might be better than a patch?

**Comment by grazzolini** [comment]
@beardypig
It would certainly be better than a patch, yes. I have been testing the package so far and I had no issues with it.

**Comment by beardypig** [comment]
OK @grazzolini I'll add that to the TODO list :)

**Comment by mmetak** [comment]
@beardypig something like this?
```python
# for encrypted streams
if environ.get("STREAMLINK_USE_PYCRYPTO"):
    deps.append("pycrypto")
else:
    # this version of pycryptodome is known to work and has a Windows wheel for py2.7, py3.3-3.6
    deps.append("pycryptodome>=3.4.3,<4")
```

**Comment by beardypig** [comment]
Yep, almost exactly what I was planning. I would set a minimum version for `pycrypto` though, for edge cases :) 
Maybe `pycrypto>=2,<3`, not sure if there are bugs in earlier versions.

**Comment by beardypig** [comment]
Actually, just that will be perfect. Will you create a PR?

**Comment by mmetak** [comment]
https://github.com/streamlink/streamlink/pull/713 and I also added info to docs about it https://github.com/streamlink/streamlink/pull/715.

**Comment by gravyboat** [comment]
The only thing we're missing at this point is opensuse in the docs but https://build.opensuse.org/request/show/444737 was approved so I'm going to close this out.
