### ISSUE TITLE
http server binds to all hosts rather than localhost

### ISSUE THREAD

**Issue by alok0** [streamlink/streamlink#2622]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Not specifying `player-external-http` does not stop streamlink from listening on all interfaces.

This causes a problem on a system where interfaces might change or go down while streamlink is running, where somehow streamlink has passed an ip other than 127.0.0.1 to the player

### Expected / Actual behavior

according to the documentation for  `player-external-http` 
> the server will listen on all available connections instead of just in the local (loopback) interface.

according to the comments `create_http_server` in `main.py`
> If host is empty, listen on all available interfaces, 

which it does do, and in turn when not in external mode, the http server is still listening on all interfaces.

**Comment by beardypig** [comment]
Looks like this has been the behaviour since livestreamer. 

I believe the following change would resolve it, and should work on all supported operating systems.

```diff
diff --git a/src/streamlink_cli/main.py b/src/streamlink_cli/main.py
index 56fb5be9..821ea354 100644
--- a/src/streamlink_cli/main.py
+++ b/src/streamlink_cli/main.py
@@ -185,7 +185,7 @@ def output_stream_http(plugin, initial_streams, external=False, port=0):
                          "executable with --player.")

         title = create_title(plugin)
-        server = create_http_server()
+        server = create_http_server("127.0.0.1")
         player = output = PlayerOutput(args.player, args=args.player_args,
                                        filename=server.url,
                                        quiet=not args.verbose_player,
```
