### ISSUE TITLE
Fetch automatically current URL of YouTube-Livestream

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#2624]
## Feature Request
- [x] This is a feature request and I have read the contribution guidelines.

### Description
Within Youtube Livestreams do not have some kind of static URL, but the address changes dynamically. Sometimes it stays the same for some weeks, sometimes it changes already after a few days. It would be nice if streamlink could detect the current valid URL by a given channel name. 

Manually one can get it in three steps: 

1) Get the channel id using the known channel name: 
`https://www.googleapis.com/youtube/v3/channels?key={your_google_api_here}&{name_of_youtubube_channel_here}&part=id`
This returns some kind of json(?)-data, containing amongst other things the channel id. 

2) Get the video id using the known channel id
`https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={channel_id_here}&eventType=live&type=video&key={your_google_api_here}`
This returns some kind of json(?)-data, containing amongst other things the video id. 

3) Put data together to obtain final url: 
`https://www.youtube.com/watch?v= + {videoID}`

A call could be something like this: 

`streamlink www.youtube.com --name {channel_name_here} --api {your_google_api_here}`

**Comment by back-to** [comment]
> It would be nice if streamlink could detect the current valid URL by a given channel name.

already there

```
$ streamlink "https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ" worst -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
```
