### ISSUE TITLE
refresh the stream after xx hours to stop cookies expiring

### ISSUE THREAD

**Issue by IceBear01** [streamlink/streamlink#2626]
## Issue

- [ x] This is not a bug report, feature request, or plugin issue/request.
- [ x] I have read the contribution guidelines.

### Description

apologies if its already been answered but i have looked and didnt find a clear answer, so here goes...

using BT plugin, streams successfully run for 12 hours then stop due to cookies expiring.
is it possible to rerun the command automatically so a new cookie is added to the stream, or so the stream quickly restarts with new cookies lasting another 12 hours and repeat every 12 hours as to keep the stream alive for an extended amount of time without having to manually run it via cmd/ssh 

this obviously doesnt just apply to bt. this could apply to any time restricted plugin or stream url (HLS/HTTP) but seemed like a good example.  

using default player (vlc) on pc. and using external http on linux for this if it makes a difference

streamlink --player-external-http "https://sport.bt.com/btsportplayer/bt-sportespn-01363810201883" best --btsports-email xxxxxxxxxxx --btsports-password yyyyyyyyyy

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by voidtemp** [comment]
Hello!

Any progress on this?

**Comment by back-to** [comment]
This function should be handled **plugin specified**, if it even is needed.

Streamlink makes things different on many Plugins, where this won't work correctly.
