### ISSUE TITLE
[plugins.youtube]: Youube plugin stopped working

### ISSUE THREAD

**Issue by highflux7** [streamlink/streamlink#2627]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by highflux7** [comment]
Youtube plugin fails to find (most) youtube video streams.

`
$ streamlink -l trace https://www.youtube.com/watch?v=GIwCGk-ABNQ
[14:26:41,76][cli][debug] OS:         Linux-5.0.0-27-generic-x86_64-with-Ubuntu-18.04-bionic
[14:26:41,76][cli][debug] Python:     3.6.8
[14:26:41,77][cli][debug] Streamlink: 1.1.1
[14:26:41,77][cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[14:26:41,78][cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=GIwCGk-ABNQ
[14:26:41,78][plugin.youtube][debug] Video ID from URL
[14:26:41,78][plugin.youtube][debug] Using video ID: GIwCGk-ABNQ
[14:26:41,912][plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=GIwCGk-ABNQ

`


Apparently affecting many projects, i.e. youtube-dl, etc:

 "YouTube has removed adaptive_fmts and url_encoded_fmt_stream_map from the player response, which I expect causes this code to fail. YouTube has moved both of these into playerResponse as streamingData.adaptiveFormats and streamingData.formats, respecitively."

**Comment by gravyboat** [comment]
Reopening since this will still have to be closed, thanks for the heads up with your note regarding the move.

**Comment by thinkpad4** [comment]
Youtube-dl is reporting that Youtube cancelled what they changed: https://github.com/ytdl-org/youtube-dl/issues/22381

**Comment by uknetfreak** [comment]
Can I just enquire as to whether the issue with livestreams is still being addressed. The only livestreams that seem to work are those that are in the format https://www.youtube.com/watch?v=Rwm0wWsmOEc whereas https://www.youtube.com/user/NASAtelevision doesn't work. For streams that have a constant broadcast this isn't a major problem, however, for such streams that operate an occasional schedule, I have got use to using streamlink and having it get the link dynamically as required.

**Comment by malvinas2** [comment]
@uknetfreak 
You have to use the 'channel-id' instead of 'user', see [Fetch automatically current URL of YouTube-Livestream #2624](https://github.com/streamlink/streamlink/issues/2624#issuecomment-529507697)
