### ISSUE TITLE
Unable to download getting this error: TypeError: ord() expected a character, but string of length 0 found

### ISSUE THREAD

**Issue by TheMamba12** [streamlink/streamlink#2631]
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description

Hi everybody, I'm new posting here, I've been using streamlink for a year without any problem using the same platform to download content but now I'm always getting the same error last week. I read other issues and didn't find anything similar. I usually get the URL of the content I want to download with a couple of Firefox add-ons, Video Download Helper and Stream Detector if the URL requires a cookie authorization. I don't know if the problem is that cookies expire too soon or that now the streams I want to download from that platform are very long, like minimum 6 hours. Streamlink open the URLs correctly and start downloading but always stop when it's more or less the half of the stream downloaded showing an error that I've never seen before.

Any help, suggestion will be appreciated.

### Reproduction steps / Explicit stream URLs to test

Account needed to access the site
https://www.fubo.tv/signin
Any stream

### Log output

```
xception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 140, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 29, in pkcs7_decode
    val = ord(paddedData[-1:])
TypeError: ord() expected a character, but string of length 0 found


[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.
Maybe it's just a Python error, at least the errors I get say .py files. Could it be a solution to uninstall and reinstall the application?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by TheMamba12** [comment]
I think found the solution.

**Comment by jbarry786** [comment]
> 
> 
> I think found the solution.

What was the possible solution?

**Comment by jbarry786** [comment]
> 
> 
> Before saying anything, my question may not be well formulated and I have to say that my knowledge about programming is limited. I just found a link from another forum in which a user said that strings that start with this character _ remove them all. This character appears many times when I get the cookie authorization, which is essential to download streams on the site that I usually use. I tried a couple of streams and it worked.

I asked because I get a similar error on some random streams. And in my case it's not because of cookies having to be refreshed or the streams being long. The error may show up a couple of minutes into the stream.

And it's also this error
`TypeError: ord() expected a character, but string of length 0 found`

So what was the actual fix in your case? Did you change anything on streamlink's .py files or was it something else?

**Comment by beardypig** [comment]
This error would occur when there is no data. It is possible that this is a bug in Streamlink, or it might be an issue with the stream. 

It is possible that the following change could fix it. It would at least remove that specific error.

```diff
diff --git a/src/streamlink/stream/hls.py b/src/streamlink/stream/hls.py
index b243b228..4e2eea74 100644
--- a/src/streamlink/stream/hls.py
+++ b/src/streamlink/stream/hls.py
@@ -136,8 +136,8 @@ class HLSStreamWriter(SegmentedStreamWriter):
                 decrypted_chunk = decryptor.decrypt(data[:-garbage_len])
             else:
                 decrypted_chunk = decryptor.decrypt(data)
-
-            self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
+            if decrypted_chunk:
+                self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
         else:
             for chunk in res.iter_content(chunk_size):
                 self.reader.buffer.write(chunk)
```

**Comment by jbarry786** [comment]
@beardypig I bumped into this error again and tried that possible fix.

Still originated an error, this is the error message:
```> [download][test2.ts] Written 710.4 MB (8m43s @ 1.5 MB/s)                                                                            [stream.hls][debug]
> Exception in thread Thread-HLSStreamWriter:
> Traceback (most recent call last):
>   File "threading.py", line 916, in _bootstrap_inner
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 167, in run
>     self.write(segment, result)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 141, in write
>     self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 31, in pkcs7_decode
>     raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
> streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 66
```
Running on,
> 
> `[cli][debug] OS:         Windows 7
> [cli][debug] Python:     3.6.6
> [cli][debug] Streamlink: 1.2.0+22.g6ac9ee0
> [cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
>`

The hls.py in use: [hls.py.txt](https://github.com/streamlink/streamlink/files/3657821/hls.py.txt)
![image](https://user-images.githubusercontent.com/30951795/65691038-17add680-e068-11e9-8952-9d42958944fc.png)

Looks like the error message changed a bit from the error that I got with the 'default' hls.py(by the way, can you have the hls.py in the new nightly releases incorporate your changes?):

> 
[stream.hls][debug] Download of segment 391967548 complete
> [download][test1.ts] Written 31.9 MB (17s @ 1.5 MB/s)[stream.hls][debug] Adding segment 391967570 to queue
>                                      Exception in thread Thread-HLSStreamWriter:
> Traceback (most recent call last):
>   File "threading.py", line 916, in _bootstrap_inner
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 167, in run
>     self.write(segment, result)
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 140, in write
>     self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
>   File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 29, in pkcs7_decode
>     val = ord(paddedData[-1:])
> TypeError: ord() expected a character, but string of length 0 found

I am not sure if it's a streamlink issue (I recall youtube-dl returning a 'no data' error, while when I used youtube-dl + ffmpeg as 'downloader', it actually worked for the very same streams that were failing), but if this rings any bells as what could possibly "fix it" or just tell streamlink to "skip those errors" and move ahead, that'd work --- I tested with hls-offset, past some of the errors and it works, meaning, the stream doesn't 'end'. It just likely has some sections where as you said SL reads "no data". Thanks for all you do.

**Comment by TheMamba12** [comment]
I got the same error as jbarry786 again, I thought removing those lines would fix the problem but the site I use changed the urls. I'm trying to change hls.py as beardypig suggested but I don't know how to do it.

**Comment by sou7611** [comment]
I'll chime in and say I'm seeing the same exact thing.

**Comment by ischmidt20** [comment]
I have now started seeing this on ESPN+ streams. I assume this is somewhat related to my older ESPN+ issue which @jbarry786 already linked here.

**Comment by bastimeyer** [comment]
Could you please give #3446 a try and see whether this fixes the input padding issue?

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/pull/3768
https://github.com/streamlink/streamlink/pull/3770
