### ISSUE TITLE
Ustream for ISS Live not working?  (UPDATE: Now working)

### ISSUE THREAD

**Issue by liamkennedy** [streamlink/streamlink#2633]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Running this on Raspberry Pi / a bit of an older version of Streamlink (0.11.0).

The ISS Live stream here->
streamlink https://www.ustream.tv/channel/live-iss-stream
produces this error:
error: No playable streams found on this URL: https://www.ustream.tv/channel/live-iss-stream

EDIT: The desktop version of this stream works just fine in any browser - it's just the Streamlink side which didn't work

Earlier today all was working fine.  

As a comparison

This other NASA "live" stream still works.  (same with NASATV)
streamlink http://www.ustream.tv/channel/iss-hdev-payload
Available streams: 252p (worst), 360p, 486p, 720p (best)

### Log output

```
pi@issabove:~ $ streamlink https://www.ustream.tv/channel/live-iss-stream --loglevel debug
[cli][debug] OS:         Linux-4.14.34-v7+-armv7l-with-debian-9.4
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0.11.0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/channel/live-iss-stream
[plugin.ustreamtv][debug] Searching for media ID on the page
[plugin.ustreamtv][debug] Connecting to UStream API: media_id=9408562, application=channel, referrer=https://www.ustream.tv/channel/live-iss-stream, cluster=live, app_id=11, app_ver=2
[plugin.ustream.apiclient][debug] Got new host=http://c742eca4-lp-omega.ums.services.video.ibm.com, and connectionId=rjpm8rptmjm6kig46l21johusu-6
[plugin.ustream.apiclient][debug] poll took 0.20s
[plugin.ustreamtv][debug] Retrying moduleInfo request
[plugin.ustream.apiclient][debug] poll took 7.54s
[plugin.ustreamtv][debug] Retrying moduleInfo request
[plugin.ustream.apiclient][debug] poll took 2.00s
[plugin.ustreamtv][debug] Retrying moduleInfo request
[plugin.ustream.apiclient][debug] poll took 10.07s
[plugin.ustreamtv][debug] Retrying moduleInfo request
[plugin.ustream.apiclient][debug] poll took 1.34s
[plugin.ustreamtv][debug] Retrying moduleInfo request
error: No playable streams found on this URL: https://www.ustream.tv/channel/live-iss-stream
```

### Additional comments, screenshots, etc.

I recall something like this happening previously.  I asked a contact at NASA to request "they" restart their encoder sending this to Ustream.  Eventually it cleared up but I don't know if that was because of an encoder issue.  

Is there any other diagnosis I can run to show why this one isn't working but the other live stream(s) are working (e.g. the old HDEV one - and also the main NASA TV channel).   

Thanks!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by liamkennedy** [comment]
Note:  As of a few minutes ago this stream (ISS Live) is now working again.  No real clue as to what may have happened to fix it - be that on Ustream or via something at the source encoding point at NASA JSC

**Comment by back-to** [comment]
> [cli][debug] Streamlink: 0.11.0

outdated version

**Comment by gravyboat** [comment]
@back-to I think @liamkennedy is locked to that version and unable to update (is this still the case @liamkennedy?). I'm not too familiar with stream analysis in terms of video footage. Maybe try and directly grab some of the stream when it's working and use something other than Streamlink when it's not working to see if there's any difference in the video itself? I don't know...
