### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by 10362227** [streamlink/streamlink#2634]
`streamlink --http-header "User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.25 Safari/537.36" "hls://https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190926T192016_1080p7500.m3u8?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31" best -o "111.mp4"`

error: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190926T192016_1080p7500.m3u8?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190926T192016_1080p7500.m3u8?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)

then I use URL Shortener (it works fine in WIN8, but doesn't work in CentOS 7 x64)
`[root@vultr ~]# streamlink --http-header "User-Agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.25 Safari/537.36" "hls://http://gg.gg/fam0r" best -o "111.mp4"
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin hls for URL hls://http://gg.gg/fam0r
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to open segment 19360: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T033807_1080p7500_19360.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T033807_1080p7500_19360.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][error] Failed to open segment 19361: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T033813_1080p7500_19361.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T033813_1080p7500_19361.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
`

**Comment by 10362227** [comment]
OS: CentOS 7 x64
livestream site: http://gg.gg/fames

**Comment by back-to** [comment]
> (it works fine in WIN8, but doesn't work in CentOS 7 x64)

what version of streamlink are you even using?

are the win8 and centos in the same network?

---

share a debug log and some more details

**Comment by 10362227** [comment]
latest version! the same network. I changed my ip and the m3u8 link (http://gg.gg/fam0r) still works


CentOS log:
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21444 to queue
[stream.hls][error] Failed to open segment 21444: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070644_1080p7500_21444.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070644_1080p7500_21444.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21445 to queue
[stream.hls][debug] Adding segment 21446 to queue
[stream.hls][error] Failed to open segment 21445: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070650_1080p7500_21445.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070650_1080p7500_21445.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][error] Failed to open segment 21446: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070656_1080p7500_21446.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070656_1080p7500_21446.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21447 to queue
[stream.hls][error] Failed to open segment 21447: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070702_1080p7500_21447.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070702_1080p7500_21447.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21448 to queue
[stream.hls][error] Failed to open segment 21448: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070708_1080p7500_21448.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070708_1080p7500_21448.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21449 to queue
[stream.hls][error] Failed to open segment 21449: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070714_1080p7500_21449.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070714_1080p7500_21449.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21450 to queue
[stream.hls][error] Failed to open segment 21450: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070720_1080p7500_21450.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070720_1080p7500_21450.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21451 to queue
[stream.hls][debug] Adding segment 21452 to queue
[stream.hls][error] Failed to open segment 21451: Unable to open URL: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070726_1080p7500_21451.ts?hdntl=exp=1569662252~acl=%2fhls%2flive%2f2004856*%2frockinrio_v1%2f*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31 (403 Client Error: Forbidden for url: https://livexlive.akamaized.net/hls/live/2004856/rockinrio_v1/index20190928T070726_1080p7500_21451.ts?hdntl=exp=1569662252~acl=%2Fhls%2Flive%2F2004856*%2Frockinrio_v1%2F*~hmac=a08b4c82589963612ef640d990d0a7218eab0ab8cd1b1c6d007ce4c45205ac31)
^CInterrupted! Exiting...
[cli][info] Closing currently open stream...

livestream site: http://gg.gg/fames

**Comment by back-to** [comment]
> CentOS log:

you removed the **important** first part of the log with the versions,
also share the win8 log.

**Comment by 10362227** [comment]
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.10.0-1062.1.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[cli][debug] Python:     2.7.5
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin hls for URL hls://http://gg.gg/fam0r
[plugin.hls][debug] URL=http://gg.gg/fam0r; params={}
[utils.l10n][debug] Language code: en_US


[Streamlink for Windows v0.14.2 - Git 215d789]
[cli][debug] OS:         Windows 8.1
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 0.14.2+215d789
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin hls for URL hls://https://tiny.cc/xfnjdz
[plugin.hls][debug] URL=https://tiny.cc/xfnjdz; params={}

**Comment by back-to** [comment]
>  [cli][debug] Python: 2.7.5

@10362227 could you try it with an updated version of **python2**
 or even better with a **python3** version instead

this is probably an outdated dependencies issue

---

does it work on windows with `Streamlink: 1.2.0` or does it fail?
