### ISSUE TITLE
Audios / Subtitle

### ISSUE THREAD

**Issue by 0OOOOOOO0** [streamlink/streamlink#2635]
In this link mpd appear two audios (Spanish and English) and a subtitle ¿Is it possible to put both audios and subtitle in the video?

`https://geodasha3player.akamaized.net/vcgdash/_definst_/assets17/2019/05/05/393F1C7E-55E9-4A80-A4F8-C07039C7302D/dash.smil/manifest_mvlist.mpd`

**Comment by beardypig** [comment]
Streamlink only supports a single audio track and a single subtitle track. Streamlink is built for live streaming, you need to chose which audio track you want before you start. You could download it twice and take the audio from one, and mux the audio from one with the other... But if you're doing that, you probably want to use another program more suited to that.

**Comment by 0OOOOOOO0** [comment]
@beardypig
I can add the two audios in the video with the --hls-audio-select "es,en" command using a m3u8 link but I can't do it with the mpd, the subtitles neither with the mpd nor with the m3u8.

**Comment by beardypig** [comment]
Ah OK, the DASH stuff is separate to the HLS stuff - we might be able to added it to DASH too. Do you want to mux multiple subtitles streams as well as multiple audio streams?

**Comment by 0OOOOOOO0** [comment]
I would love to have this command --dash-audio-select "es,en" to be able to put in the video all the available audios and I would also love to add all the subtitles available in the mpd link, the link I mentioned contains two audios and a subtitle.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2260

**Comment by 0OOOOOOO0** [comment]
@back-to @beardypig

Are you going to implant it?

**Comment by gravyboat** [comment]
@0OOOOOOO0 If someone wants to work on it they will, if not they won't. We don't promise that we'll work on anything. If you want to work on it we'd be happy to review a PR.
