### ISSUE TITLE
Plugin request: Seirsanduk

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2637]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
The website called Seirsanduk provides a multitude of Bulgarian channels.
Links:
seirsanduk.com
seirsanduk.us
seirsanduk.online

### Example stream URLs
http://www.seirsanduk.com/hd-diema-sport-hd-online

### Additional comments, screenshots, etc.
Not sure if this is restricted to Bulgarian IPs only.

**Comment by beardypig** [comment]
Not sure how legitimate this website is, they appear to be re-streaming subscription channels...

**Comment by roshavagarga** [comment]
I agree, but as far as I can tell it's using the gray area within the country's laws which state that it can only be prosecuted if it's hosted within the confines of the country or a country that would act based on an official complaint by the government and/or companies.

I'm closing this request then, as I forgot about the implications it might have on streamlink.

**Comment by beardypig** [comment]
The problem is if someone (Eurosport/Discovery/etc) decides that we are facilitating copyright infringement they might report it to GitHub (it's happened before).
