### ISSUE TITLE
copyts / mpegts

### ISSUE THREAD

**Issue by 0OOOOOOO0** [streamlink/streamlink#2639]
Why are all the video formats (avi, mkv, mp4...) downloaded to as if they were ts? It's really annoying this stupid format, please delete it and have the videos downloaded correctly.

**Comment by 0OOOOOOO0** [comment]
@beardypig
The command copyts and mpegts kills subtitles delete please or tell me which file to modify and what to put.

**Comment by beardypig** [comment]
Can you give an example. If there is a subtitle stream muxed in maybe we need to update the ffmpeg command to fix it.

**Comment by 0OOOOOOO0** [comment]
@beardypig 
It's not a subtitle problem, it's a problem of the damn command copyts and mpegts, I have in  folder a subtitle that has the same name as the video file It turns out that the subtitle detects me if I convert the video into any format without the damn copyts and mpegts but as soon as it has this stupid ts in any format it doesn't let me see the video.

**Comment by beardypig** [comment]
Are you grabbing an HLS stream? Because if it is then it will be MPEG-TS and if you want it as something else you will need to convert it yourself.

**Comment by 0OOOOOOO0** [comment]
@beardypig
It is stupid to put a ts in any format for this reason it is impossible to visualize the videos with subtitles, Using an mpd link if I detect the subtitle and I see the video because it does not have the stupid format ts in all video formats but does not allow me to see the video when I use a m3u8 link, please close this topic.

**Comment by 0OOOOOOO0** [comment]
@beardypig
It is stupid to put a ts in any format for this reason it is impossible to visualize the videos with subtitles, Using an mpd link if I detect the subtitle and I see the video because it does not have the stupid format ts in all video formats but does not allow me to see the video when I use a m3u8 link, please close this topic.

**Comment by 0OOOOOOO0** [comment]
@beardypig
It is stupid to put a ts in any format for this reason it is impossible to visualize the videos with subtitles, Using an mpd link if I detect the subtitle and I see the video because it does not have the stupid format ts in all video formats but does not allow me to see the video when I use a m3u8 link.

**Comment by beardypig** [comment]
HLS is MPEG-TS. Streamlink re-packages the FASH streams in to MKV. That's how it is I'm afraid. You can blame Apple for MPEG-TS with HLS.
