### ISSUE TITLE
Documentation on how to run the application locally

### ISSUE THREAD

**Issue by Integralist** [streamlink/streamlink#2644]
This is a request for information on how to run the streamlink application locally so I may test some behaviours I want to help open a PR for. I have read the contribution guidelines but it doesn't have information on how to get the application running locally.

**Comment by Integralist** [comment]
I had attempted to do `python3 src/streamlink_cli/main.py` thinking that might start up the cli program but I had a dependency error...

```
Traceback (most recent call last):
  File "src/streamlink_cli/main.py", line 18, in <module>
    from socks import __version__ as socks_version
ModuleNotFoundError: No module named 'socks'
```

I attempted to install the socks dependency with `pip3 install socks` but that didn't help.

I'm likely just misunderstanding the structure of the program, so any guidance you can give me would be appreciated. Thanks.

**Comment by back-to** [comment]
example on linux with a virtual environment

```sh
# clone streamlink
git pull https://github.com/streamlink/streamlink.git
cd streamlink/

# install virtual environment
python3 -m venv venv
source venv/bin/activate

# update virtual environment
python -m pip install -U pip setuptools
pip install -U -r dev-requirements.txt
pip install -U -r docs-requirements.txt

# install dev streamlink
pip install -e .
# streamlink should now work with every change you make
streamlink

# you can also run the test files locally
pytest tests/
# or for a plugin
pytest tests/plugins/test_youtube.py
```

you can now use streamlink locally in the folder with
`source venv/bin/activate`

**Comment by Integralist** [comment]
This worked perfectly! Thank you. 🙂
