### ISSUE TITLE
--player-external-http download file without extension

### ISSUE THREAD

**Issue by oussemamw** [streamlink/streamlink#2660]
hello

this my command **streamlink https://ql8eqt6a.faselhdstream.com/stream/hls/4/99cc53f31baa961899e817fdf9839d94/,720,p.mp4.urlset/index-v1-a1.m3u8 best --player-external-http --player-external-http-port 8080**

it work perfectly to download file but the file with out extension

**Comment by tp0** [comment]
I don't understand your issue.

Why are you using `--player-external-http` to download (and how exactly) instead of `-o`?

In any case, you can just rename to tile to `whatever.ts`.

**Comment by bastimeyer** [comment]
Closing the issue. Please take a look at Streamlink's CLI documentation before asking questions like this.
https://streamlink.github.io/cli.html

Thanks for answering, @tp0!
