### ISSUE TITLE
Streamlink possible malware? 

### ISSUE THREAD

**Issue by gimli520** [streamlink/streamlink#2661]
I am really sorry if this isn't allowed but I am not sure where else to ask.

I use to use Livestreamer, but recently it broke and I think it broke for good. I downloaded Streamlink from this page https://github.com/streamlink/streamlink/releases/tag/1.2.0 that I got from a google search.

When I went to install it, windows smartscreen gave me gripes about it. I forced it through and it installed fine. When I tried to start a stream, Avast hardened mode freaked out about it and asked me to add an exception. I also noticed that it installed its path into Appdata/local and not regular C:/path

Here I am 2 days later and I have scanned with a few different second opinion scanners, they have all turned up nothing, multiple times. Nothing seems out of the ordinary either, but I suppose you never know.

Again I am sorry if this is not the right place to post this, I just want to be safe and would like to continue to use streamlink. Thank you.

**Comment by skulblakka** [comment]
There were reports about false positives (especially with Avast) with earlier versions of streamlink. 

>I also noticed that it installed its path into Appdata/local and not regular C:/path

This is probably because you installed streamlink only for you instead of all users (there should be an option during installation)

**Comment by gimli520** [comment]
> 
> 
> There were reports about false positives (especially with Avast) with earlier versions of streamlink.
> 
> > I also noticed that it installed its path into Appdata/local and not regular C:/path
> 
> This is probably because you installed streamlink only for you instead of all users (there should be an option during installation)

Ah you are right, I did install it only for myself, I forgot that I did that.

Alright so can I assume that streamlink is safe and keep on using it then? Sorry I can be really on edge when it comes to malware.

**Comment by gravyboat** [comment]
@gimli520 This concern is totally valid. Our software isn't signed (and we're never going to pay for a MS license to avoid that warning because we don't make enough money and it's not really worth it any ways). All of the code is open source so you're free to analyze as you like, and sites such as [VirusTotal](https://www.virustotal.com/gui/) also allow you to run it through a bunch of different checks. Sometimes on new releases it will trigger certain virus software simply because it hasn't been installed much so it isn't in their database yet.

**Comment by bastimeyer** [comment]
> When I went to install it, windows smartscreen gave me gripes about it.

See my comment regarding that here:
https://github.com/streamlink/streamlink/issues/2356#issuecomment-473461426

> When I tried to start a stream, Avast hardened mode freaked out about it

Not sure what this is about. It's probably related to the access of the system's network interface by Streamlink's Python process while reading the stream or related to the subprocess creation of the player. What else is there for an "Anti virus" tool on Windows to monitor? Maybe the accessed file names on the file system, but Streamlink does only read its own (precompiled) module files and the user's config file stored in the user's home directory. Other than that it's a regular Python 3.5 environment with launcher wrapper executables created by the [`simple_launcher`](https://bitbucket.org/vinay.sajip/simple_launcher/src/default/) library.

**Comment by gimli520** [comment]
Thank you both for your answers. I also figured once it started a network connection, that is probably what Avast probably just freaked out a little. 

Again thank all of you for your hard work. Streamlink/livestreamer is one of the best programs i've ever used. I hope to one day contribute to all the hard work.
