### ISSUE TITLE
Failed to Parse "@" Character

### ISSUE THREAD

**Issue by munfaqqiha** [streamlink/streamlink#2662]
I am getting: `(Failed to parse: http://usr@max:proxy@192.121.66.131:8080/)`. I've tried to convert `@` to unicode `a%40`. 

Full log :

> treamlink -f -l debug --http-proxy "http://usr@max:proxy@192.121.66.131:8080/" --url "http://link.com:7899/live/myuser/mypass/stream.m3u8" --default-stream best -o "out.ts"
> 
> [cli][debug] OS: Linux-4.9.0-9-amd64-x86_64-with-debian-9.11
> [cli][debug] Python: 3.5.3
> [cli][debug] Streamlink: 1.2.0
> [cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
> [cli][info] Found matching plugin hls for URL http://link.com:7899/live/myuser/mypass/stream.m3u8
> [plugin.hls][debug] URL=http://link.com:7899/live/myuser/mypass/stream.m3u8; params={}
> [utils.l10n][debug] Language code: en_US
> error: Unable to open URL: http://link.com:7899/live/myuser/mypass/stream.m3u8 (Failed to parse: http://usr@max:proxy@192.121.66.131:8080/)

**Comment by bastimeyer** [comment]
> http://usr@max:proxy@192.121.66.131:8080/

That's a malformed URL, see the syntax definition:
https://tools.ietf.org/html/rfc3986#section-3

> I've tried to convert `@` to unicode `a%40`

It's just `%40`, not `a%40`.
https://tools.ietf.org/html/rfc3986#section-2.1

**Comment by munfaqqiha** [comment]
> It's just `%40`, not `a%40`.
> https://tools.ietf.org/html/rfc3986#section-2.1

That's what I meant. Sorry, I made a typing error. I think it's  a bug, thank you.

**Comment by beardypig** [comment]
@munfaqqiha did you try `"http://usr%40max:proxy@192.121.66.131:8080/"`? I use a proxy server where the username has an `@` character just fine.

**Comment by munfaqqiha** [comment]
> @munfaqqiha did you try `"http://usr%40max:proxy@192.121.66.131:8080/"`? I use a proxy server where the username has an `@` character just fine.

Yup with same errors.

**Comment by bastimeyer** [comment]
> 401 Client Error: Unauthorized for url

This looks like you're using an invalid stream input URL. There are no error messages in regards to the http proxy.

Does your http proxy work when you're using a different proxy client, like curl with its `--proxy` parameter for example?

**Comment by munfaqqiha** [comment]
> > 401 Client Error: Unauthorized for url
> 
> This looks like you're using an invalid stream input URL. There are no error messages in regards to the http proxy.
> 
> Does your http proxy work when you're using a different proxy client, like curl with its `--proxy` parameter for example?

You're right. It works now, thank you.
