### ISSUE TITLE
specify the path to my player

### ISSUE THREAD

**Issue by Octave1201** [streamlink/streamlink#2663]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description
Hi everyone!
Minor problem. I need to specify the path to my player (VLC) but I don't know how to do it

Error: The default player <VLC> does not seem to be installed. You must specify the path to a player executable with --player

How do I do that? I've search in the documentation but I did found anything... Please help

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by skulblakka** [comment]
>How do I do that? I've search in the documentation but I did found anything... Please help

Its right [here](https://streamlink.github.io/cli.html#cmdoption-p).

**Comment by gravyboat** [comment]
A default player can also be set in the [configuration file](https://streamlink.github.io/cli.html#configuration-file).
