### ISSUE TITLE
Streamlink with a Raspberry pi

### ISSUE THREAD

**Issue by Octave1201** [streamlink/streamlink#2664]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Hi everyone!

Is it possible to run Streamlink with a raspberry pi?

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Please use the search function next time. This has already been answered here:
https://github.com/streamlink/streamlink/issues/1491#issuecomment-366850493

If you're talking about Raspbian, then simply install the streamlink package, as Raspbian is based on Debian and uses (most of) its packages.
https://streamlink.github.io/install.html#linux-and-bsd
https://archive.raspbian.org/raspbian/pool/main/s/streamlink/
https://packages.debian.org/sid/streamlink

If you're using a different OS, then look for available streamlink packages in its package management system. If this doesn't exist, then make sure that python3 and pip are correctly installed on your system and install streamlink via pip. Additionally, you can also use a virtual environment, which is described here as well:
https://streamlink.github.io/install.html#source-code
