### ISSUE TITLE
Line TV Taiwan

### ISSUE THREAD

**Issue by nain311** [streamlink/streamlink#2665]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
This is a streaming site.
I really want to get video file of this site, because many people want to watch that, But they can't.
Please carete Plugin for me?

### Example stream URLs

1. Homepage https://www.linetv.tw
2. https://www.linetv.tw/drama/10804/eps/1

### Additional comments, screenshots, etc.
You can connect this website, But you can't watch video
Because They only give some service for Taiwan people.
So if you can use VPN service, You can connect as Taiwan by VPN...
Thank you.

And I try connect directly URL 'https://d3c7rimkq79yfu.cloudfront.net/10802/1/v2/1080/10802-eps-1_1080p.m3u8' by Edge Broswer and I can't watch
But I had connected this page 'https://www.linetv.tw/drama/10802/eps/1' before. I can!
So, I research Request infomations.

![123](https://user-images.githubusercontent.com/56753015/67140487-efe01600-f295-11e9-86df-783adfca2404.png)

If you need to request infomation, so i write tham.
Accept: text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR
Cache-Control: max-age=0
Host: d3c7rimkq79yfu.cloudfront.net
If-Modified-Since: Wed, 16 Oct 2019 03:18:17 GMT
If-None-Match: "a1e0e033fad8f21dd06c191764bd711e"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

And I think it is needed too.
About 'keydeliver.linetv.tw'
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR
Cache-Control: max-age=0
Cookie: connect.sid=s%3A987JZN_H4eIniOJfweDUYjTloerHAryO.ek9fXtSi15LwD4U%2FdCPkNhAXFdClLvO%2FcjLHK6Orn4s; _gat=1; _gid=GA1.2.1415329604.1571471783; _ga=GA1.2.1988975891.1571471783; view.id=10802_1
GetContentFeatures.DLNA.ORG: 1
Host: keydeliver.linetv.tw
Range: bytes=0-
Referer: https://d3c7rimkq79yfu.cloudfront.net/10802/1/v2/1080/10802-eps-1_1080p.m3u8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Thank you for the detailed plugin request. While this is a legitimate website, it only offers video on demand content. The focus of the Streamlink project is on _live_ streaming content, as such we would probably not include a plugin for this site in Streamlink.

**Comment by gravyboat** [comment]
Yep I'm going to close this because as @beardypig said the focus is on live streaming content.

**Comment by nain311** [comment]
Oh.. I'm sorry...
I didn't thinj about that...
Thank you for your answer ^^
