### ISSUE TITLE
hls-live-restart downloads 2 hours from current time but, the live stream is 4 hours long

### ISSUE THREAD

**Issue by NairasLT** [streamlink/streamlink#2667]
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Expected / Actual behavior

Expected to download from the very beginning, not 2 hours back from now

### Reproduction steps / Explicit stream URLs to test

is used both of these commands but neither of them downloaded from the very beginning
1. streamlink --hls-live-restart -o 'outfile' 'url' best
2. streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "[FILE NAME].ts" [URL] best
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.
when im watching the livestream on youtube I can go back 4 hours and watch the footage.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2542
