### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by hiepga1122** [streamlink/streamlink#267]
![capture](https://cloud.githubusercontent.com/assets/24440457/20981781/8dbbe9ee-bce8-11e6-9fb5-c65cb5c680e8.JPG)
how can i fix this issue , i have tried editing the configuration file but it didn't work

**Comment by beardypig** [comment]
What version of Windows are you using? 

The installer may have failed, try this one: [streamlink-0.1.0-vcredist-7a50314.exe](https://s3.amazonaws.com/streamlink-builds/beardypig/streamlink-0.1.0-vcredist-7a50314.exe).

**Comment by hiepga1122** [comment]
it works , thanks mate

**Comment by beardypig** [comment]
Great, I'll close this issue then :-)
