### ISSUE TITLE
Twitter broadcasts failing now

### ISSUE THREAD

**Issue by jrhessey** [streamlink/streamlink#2672]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I used to be able to grab the twitter broadcasts, with the last season of DRL I now get a decryptor failed.

I posted to this closed ticket yesterday, but I'm not sure if that one still shows up for users to see.
[https://github.com/streamlink/streamlink/issues/2103](https://github.com/streamlink/streamlink/issues/2103) 

### Expected / Actual behavior

The video should download

### Reproduction steps / Explicit stream URLs to test

Here are the links I'm using

Broadcast
[https://twitter.com/i/broadcasts/1DXGypZjzbeKM](https://twitter.com/i/broadcasts/1DXGypZjzbeKM)

M3U8
[https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay](https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay)

Here is the key file link
[https://twitter.com/i/live_video_stream/key?stream_name=lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA](https://twitter.com/i/live_video_stream/key?stream_name=lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA)
Here are the headers I've tried passing (they are variables in my batch script)

```
set "authorization=Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"

set "x-csrf-token=804c6a9d679608d643b8543fcc4ef066"
set "X-Idempotence=1572010608453--c7b980fa-8cd8-4d65-8053-d0704f7aad42"
set "x-twitter-active-user=yes"
set "x-twitter-auth-type=OAuth2Session"
set "x-twitter-client-language=en"
set "life_cycle_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJicm9hZGNhc3RfaWQiOiIxWXFLREJnb3FXVkpWIiwiY3JlYXRlZCI6MTU3MjAxMDYxMCwiZXhwIjoxNTcyMDk3MDEwLCJpZ25vcmUiOmZhbHNlLCJpc19oaWdobGlnaHRzIjpmYWxzZSwiaXNfbGl2ZSI6ZmFsc2UsInBhcnRpY2lwYW50X2luZGV4Ijo2OTM4NDU2MDgsInRva2VuX3ZlcnNpb24iOjF9.lUeUj-SDcnT5q6iLE7L-NZYxUkgaamnO85daGgP2Th4"

set "Sec-Fetch-Mode=cors"
set "Origin=https://twitter.com"
set "Referer=https://twitter.com/i/broadcasts/1YqKDBgoqWVJV"
set "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
set "Accept=*/*"

```
Here is the cookie I also tried passing
set "auth_token=510875e3f0214c5d1246d8fa41524fcde750230c"

### Logs

```
streamlink "hlsvariant://https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay" best --loglevel debug --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" -o "P:\tbot\drone.racing.league\Drone.Racing.League.S04E02.mp4"
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin hls for URL hlsvariant://https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay
[plugin.hls][debug] URL=https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay; params={}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 270p (worst), 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 0; Last Sequence: 5356
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 5356
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://twitter.com/i/live_video_stream/key?stream_name=lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA (400 Client Error: Bad Request for url: https://twitter.com/i/live_video_stream/key?stream_name=lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA)
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[cli][error] Try 1/1: Could not open stream <HLSStream('https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16875482745446058136.m3u8?type=replay')> (No data returned from stream)
error: Could not open stream <HLSStream('https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjcyMCwiS2JwcyI6MjAwMCwiV2lkdGgiOjEyODB9.RYzh5rWQLNy-ZB1zO_EREmt9fkjSnJS2If9o7Ls4vOM/tw_playlist_16875482745446058136.m3u8?type=replay')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

One of the posts asked for the curl command

`curl "https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay" -H "Sec-Fetch-Mode: cors" -H "Referer: https://twitter.com/i/broadcasts/1DXGypZjzbeKM" -H "Origin: https://twitter.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed`

Here's the curl command option for the ts chunks

`curl "https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsInZlcnNpb24iOiIyIn0.eyJIZWlnaHQiOjQ4MCwiS2JwcyI6MTAwMCwiV2lkdGgiOjg0OH0.RFzmPpRYVt-M5xPGoWoifZwAR5Wj0QbokQ2FVsxVt9c/k0_chunk_1571245636963756625_135_a.ts" -H "Sec-Fetch-Mode: cors" -H "Referer: https://twitter.com/i/broadcasts/1DXGypZjzbeKM" -H "Origin: https://twitter.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" --compressed`

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> Broadcast
https://twitter.com/i/broadcasts/1DXGypZjzbeKM

This broadcast is not available in your location.

> One of the posts asked for the curl command

could you post the curl command from the browser for the key url
`https://twitter.com/i/live_video_stream/key`

**Comment by jrhessey** [comment]
Is this what you're looking for?  

`curl "https://twitter.com/i/live_video_stream/key?stream_name=lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA" -H "sec-fetch-mode: cors" -H "accept-encoding: gzip, deflate, br" -H "accept-language: en-US,en;q=0.9" -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" -H "accept: */*" -H "referer: https://twitter.com/i/broadcasts/1DXGypZjzbeKM" -H "authority: twitter.com" -H "cookie: personalization_id=^\^"v1_rr9T5ts1WXX8/jnODfcFlg==^\^"; guest_id=v1^%^3A152404915302469360; _ga=GA1.2.465407636.1524104366; kdt=rmtC5B2VI8iegpQuhrxoDjPJ7555jcj6kQnvoXKe; syndication_guest_id=v1^%^3A152430946102910503; dnt=1; csrf_same_site_set=1; csrf_same_site=1; ads_prefs=^\^"HBISAAA=^\^"; remember_checked_on=1; auth_token=fa9fc21800bae3b5be0fdf55cb6438d61360581c; rweb_optin=side_no_out; twid=u^%^3D169514738; tfw_exp=0; lang=en; _gid=GA1.2.490692571.1572098795; gt=1188552249057918976; ct0=c0d5bbe6de64a871975067a86d7d331f; external_referer=0Z2yCZ8K5BC23CfHfGPfAbYyWpM12X6X2VcSzf6^%^2FB6Sbiak^%^2BBEXVvyyw11FCAKO^%^2BgQ3B3c6jR1nzdrNlGrK65zbZmv0Xg^%^2B0Nva^%^2BmM909T0w^%^3D^|0^|8e8t2xd8A2w^%^3D; _gat=1; lv-uid=AAAAEIAuupFT6gEsSBns9vYVwK2s5u6cbamMWVmmGaSBGW8n1YCswj26NDM" -H "sec-fetch-site: same-origin" --compressed`

**Comment by back-to** [comment]
@jrhessey 

you need the `lv-uid` cookie

```
streamlink "https://prod-fastly-us-east-1.video.pscp.tv/Transcoding/v1/hls/lcT9QRKE4k0sbQ1fegNQp5e3okZT6vvIoerE6YGz2dpqaETtBsf9W-qTOTq4KpNuging-SQ-O87nJbkyZb2TyA/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/tw_master_dynamic_16875482745446058136.m3u8?type=replay" \
--http-cookie "lv-uid=AAAAEIAuupFT6gEsSBns9vYVwK2s5u6cbamMWVmmGaSBGW8n1YCswj26NDM" \
--http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```

**Comment by jrhessey** [comment]
Can you tell me how you figured that out?  or was it just plugging in all the cookies/headers from the curl command you asked for and seeing what worked?

**Comment by back-to** [comment]
> was it just plugging in all the cookies/headers from the curl command you asked for and seeing what worked?

basically yes

---

also there a 2nd method for this example,
download the key file with the curl command and use it with `--hls-segment-key-uri `
https://streamlink.github.io/cli.html#cmdoption-hls-segment-key-uri

> streamlink "https://....m3u8..." best --hls-segment-key-uri file:///home/user/x.key
