### ISSUE TITLE
dcs-live.apis.anvato.net (live news broadcasts)

### ISSUE THREAD

**Issue by craigerl** [streamlink/streamlink#2675]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Many news sites are leveraging dcs-live.apis.anvato.net for streaming content.  xls/hls playlists quickly expire here and didn't before.

### Example stream URLs

https://gooddaysacramento.cbslocal.com/live/
https://sacramento.cbslocal.com/live/

### Additional comments, screenshots, etc.

Love streamlink!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by arcooke** [comment]
In addition to CBS, many Fox affiliates also use anvato streams.  

* https://www.fox4news.com/live
* https://www.fox10phoenix.com/live
* https://www.fox5atlanta.com/live

And many others.  A plugin for this would cover a lot of live news streams.  

I have the same issue with the playlists quickly expiring.  I can get them to stream, but only for a few seconds.

**Comment by CEWaffles** [comment]
I too have this issue.
