### ISSUE TITLE
Youtube Live can only be downloaded less than 70MB when using streamlink as API. 

### ISSUE THREAD

**Issue by Miloxing** [streamlink/streamlink#2683]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Youtube live streams can only be downloaded less than 70MB when using streamlink as API,and then they stopped until timed out. But they can be downloaded well by using streamlinkcli at the command line.

### Reproduction steps / Explicit stream URLs to test

1. ...https://www.youtube.com/watch?v=1Xo7brY9o-8
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.
s = Streamlink()
astreams = s.streams(url)
stream = astreams['best']
fd = stream.open()
f = open(sPath+filename,'wb+')
while 1:
            data = fd.read(1024*8)
            if data:
                f.write(data)
[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Miloxing** [comment]
streamlink version 1.2.0

**Comment by back-to** [comment]
> Youtube live streams can only be downloaded less than 70MB when using streamlink as API,

It is not really clear what you do with it or which system you are using it with,

but your script loads more than 70MB for me.

> But they can be downloaded well by using streamlinkcli at the command line.

so not an issue

---

just some bad settings on your end
