### ISSUE TITLE
What YouTube streams will require muxing support?

### ISSUE THREAD

**Issue by mtcdood** [streamlink/streamlink#2687]
Can someone clarify what YouTube streams won't work until there's some kind of muxing support so people know for future reference?

When pointing to an example 1440p60 stream neither `1440p60` nor `1080p60` are displayed as an option but 1080p60 is downloaded when selecting `1080p` or `best`. I thought 1080p60 required muxing support but I guess it might not.

**Comment by back-to** [comment]
> Can someone clarify what YouTube streams won't work until there's some kind of muxing support so people know for future reference?

Not really, Youtube uses so many different formats, you can't specifie it with the resolution.

**HLS** streams work without muxing, **DASH** streams needs muxing.

> I thought 1080p60 required muxing support but I guess it might not.

it was, but this is an outdated information.
Some 1080p60 will work without muxing.

**Comment by mtcdood** [comment]
Why can't `--ffmpeg-ffmpeg` be used to mux the HLS streams into one output?

**Comment by beardypig** [comment]
@mtcdood I think it could, DASH support has not been added to the YouTube plugin (as far as I remember).

**Comment by mtcdood** [comment]
I did some experimentation with ffmpeg by pointing it to YouTube live stream's DASH manifest.

The ffmpeg input showed all of the quality options available on the website and some (for example it showed 30 FPS versions of the high qualities where the website does not) but the output, even just copying, was some kind of garbage video with no resolution or framerate and a miniscule bitrate. The resulting file only registered as 2-3 seconds regardless of how long I let the process download and is a split moment of recognizable but garbled audio.
