### ISSUE TITLE
Facebook plugin is broken

### ISSUE THREAD

**Issue by snoopy-coder** [streamlink/streamlink#2688]
Suddenly stopped opening regular links like:
```
streamlink https://www.facebook.com/ChampionOfChampionsSnooker/videos/769503486826281/
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/ChampionOfChampionsSnooker/videos/769503486826281/
error: No playable streams found on this URL: https://www.facebook.com/ChampionOfChampionsSnooker/videos/769503486826281/
```
I guess that for _facebook.com_ should add the ability to specify a username and password, by analogy with other sites. How realistic is it to do this? Thanks a lot.

**Comment by beardypig** [comment]
As you alluded to, this link requires a login - and login to Facebook is not supported. That is the reason the link does not work in Streamlink. Adding support for login could be tricky, you'll have to wait to see if anyone wants to add support. I don't use Facebook, so it won't be me I'm afraid.

**Comment by boygiandi** [comment]
I tried this link :
`streamlink 'https://www.facebook.com/thiennguyentinthac/videos/493435874716936/' best`

It show

> [cli][info] streamlink is running as root! Be careful!
> [cli][info] Found matching plugin facebook for URL https://www.facebook.com/thiennguyentinthac/videos/493435874716936/
> [cli][info] Available streams: 144p+a66k_alt (worst), 144p+a66k, 240p+a66k_alt, 240p+a66k, 360p+a66k_alt, 360p+a66k, 480p+a66k_alt, 480p+a66k, 720p+a66k_alt, 720p+a66k (best)
> [cli][info] Opening stream: 720p+a66k (dash)
> [stream.dash][error] Failed to open segment https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT: Unable to open URL: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT (404 Client Error: Not Found for url: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT)
> [stream.dash][error] Failed to open segment https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-hd1-v/997463547278251_0-4495366.m4v?ms=m_CT: Unable to open URL: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-hd1-v/997463547278251_0-4495366.m4v?ms=m_CT (404 Client Error: Not Found for url: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-hd1-v/997463547278251_0-4495366.m4v?ms=m_CT)
> [stream.dash][error] Failed to open segment https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT: Unable to open URL: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT (404 Client Error: Not Found for url: https://video-frt3-1.xx.fbcdn.net/hvideo-frc3-ftw/_nc_cat-1/v/rkuW1UJUfj4OmH_qzzsjs/live-dash/live-ld-a/997463547278251_0-4495366.m4a?ms=m_CT)

**Comment by beardypig** [comment]
@boygiandi that is a separate issue.

**Comment by back-to** [comment]
@boygiandi 

your Streamlink version is outdated, the log output is incorrect.

**Comment by snoopy-coder** [comment]
I'm sorry, but I can not find a `duplicate` of this issue. Could you point it? Thanks a lot.
