### ISSUE TITLE
Twitch issue

### ISSUE THREAD

**Issue by casillias** [streamlink/streamlink#2689]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
Launching any stream via streamlink gives error

Error says "error: Unable to open URL: https://api.twitch.tv/api/channels/dreadztv/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/dreadztv/access_token.json?as3=t&platform=_)"

### Reproduction steps / Explicit stream URLs to test

1. Paste streamlink https://www.twitch.tv/dreadztv best (for example) in cmd
2. Wait for it
3. Get an error

### Log output

```
C:\Windows\system32>streamlink https://www.twitch.tv/dreadztv best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/dreadztv
[plugin.twitch][debug] Getting live HLS streams for dreadztv
error: Unable to open URL: https://api.twitch.tv/api/channels/dreadztv/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/dreadztv/access_token.json?as3=t&platform=_)
```

### Additional comments, screenshots, etc.
Is it my provider isse or....?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
#2680
