### ISSUE TITLE
PROCESS ENDED

### ISSUE THREAD

**Issue by irontempura** [streamlink/streamlink#2690]
Just curious when the mickey mouse patching regarding functionality will end. I do not see the point in having this software installed if mistakes and errors are preventing operation. Not sure why a stream would result in PROCESS ENDED in command line when said stream is obviously online. It is a shame that something so simple and functional has become such an unmaintained mess.

**Comment by gravyboat** [comment]
Without providing any information we can't help you in any way. On top of that being rude or denigrating is totally pointless. This is open source software that we all work on for free. You're welcome to contribute patches and we will review them, feel free to help us maintain the software if you have the skill to do so. Until that time however you are simply benefiting from the time and effort a large number of people put in to this software that you are using for free.

Feel free to provide the required logs and other information on this issue and we'll try to help you if we can.

**Comment by beardypig** [comment]
@irontempura if you are having a specific issue please elaborate. I'm not sure what you mean by "mickey mouse patching", often websites change and plugin have to be updated to support those changes.
