### ISSUE TITLE
Afreecatv plugin issue

### ISSUE THREAD

**Issue by JohnDoh666** [streamlink/streamlink#2691]
- [ x] This is a plugin issue and I have read the contribution guidelines.

### Description

The afreecatv plugin fails with a connection error. The issue started yesterday for me.

### Log output

```
streamlink --loglevel debug http://play.afreecatv.com/lshooooo/218715636 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.2
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.54.0)
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/lshooooo/218715636
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Skipping segment 1
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Skipping segment 2
[stream.hls][debug] Skipping segment 3
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.KICjfUHK1ONK6ROKR_WW5Yfcp92eupFPIZ1VdnMOWyV4ZZJDjBca6OLYZbD9DmCcnbmZ22YM5KT78IZC5gdKpmum4cT-2GznqgDuVQtFvjY')> (Failed to read data from stream: Read timeout)
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/livestream-east-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.KICjfUHK1ONK6ROKR_WW5Yfcp92eupFPIZ1VdnMOWyV4ZZJDjBca6OLYZbD9DmCcnbmZ22YM5KT78IZC5gdKpmum4cT-2GznqgDuVQtFvjY')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Erk-** [comment]
Can you play the stream in the browser?

**Comment by JohnDoh666** [comment]
No, I cant't. When I choose the lowest quality stream, it sometimes loads, but the stream is very choppy. I'm starting to believe it is a regional issue. Does it work for you @Erk- ?

**Comment by Erk-** [comment]
Looks like I can watch in non source quality through a vpn to korea, but if I try source/hd it shows a popup to install HD-Streamer. Will look into it a bit and see if I can figure out what have changed.

**Comment by JohnDoh666** [comment]
The afreecatv app for iOS seems to be running into the same issue. 

Thanks for looking into this @Erk-

**Comment by Erk-** [comment]
![billede](https://user-images.githubusercontent.com/3659684/68882952-6abf1400-0710-11ea-818c-80ac7643e129.png)
It appers that the issue is on their end with cloudflare.

**Comment by Erk-** [comment]
Looking at [Clouldflare status](https://www.cloudflarestatus.com/) it looks like their seoul datacenter is currently rerouted, I am not completely sure what that means but that could course an error.

![billede](https://user-images.githubusercontent.com/3659684/68883198-d43f2280-0710-11ea-975c-0f526683825e.png)

**Comment by JohnDoh666** [comment]
Yeah, I ran into the same 502 error. This is a CloudFront error message though, which is a similar service from Amazon AWS.

**Comment by Erk-** [comment]
Oh I just totally misread that, sorry.

**Comment by JohnDoh666** [comment]
No worries man.

So I signed up for my VPN service for a month again and connected to a Hong Kong server and afreeca works like a charm from there. I guess this is a regional issue then. I dont know if this is something temporary or if it is something the wizards in here can overcome though.

**Comment by back-to** [comment]
works normal, doesn't seems a Streamlink issue.
