### ISSUE TITLE
Plugin request: fite.tv

### ISSUE THREAD

**Issue by katktv** [streamlink/streamlink#2693]
###  Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

fite.tv, run by Flipps Media, is a website specialized in legal live streaming and VOD service for pro wrestling, MMA and boxing promotions/events. It is particularly popular for having lesser known/watched wrestling promotions such as Impact Wrestling and Ring of Honor.

Recently they've made a deal with All Elite Wrestling, an emerging promotion that many see as the biggest competitor to WWE as of recently, to provide access to the weekly show Dynamite worldwide outside of America, so the value and the popularity of the service is increasing with more ppl hopping onto the AEW train. Given that there is Streamlink support for WWE Network, it would be great to see support for fite here as well.

### Example stream URLs

1. https://www.fite.tv/watch/aew-dynamite-episode-7/2p4k0/ (paid, $5/mo subscription)
2. https://www.fite.tv/watch/roh-wrestling-episode-425/2p4sa/ (free)
3. *here should be any livestream, but i think the url is the same*

**Comment by Shadesss** [comment]
Would love this! Routinely stream events on fite.

**Comment by codehound-00** [comment]
No need for a plugin. Filter URL for 'Playlist' (without quotes.) In Edge - Right click - Copy value - always begins =ey...xxx...xxx

Pass as a cookie.

streamlink --hls-live-restart --http-header "Cookie=CloudFront-Policy=ey...xxx...xxx...etc" -o output fite.ts "https://www.fite.tv/embed/play/2oxfp.m3u8?ref=other&tsxxx...xxx" 720p

**Comment by back-to** [comment]
> 4. Sites which require any sort of cable login or subscription

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

closing, this would end up like the WWE Network plugin.
**Livestreams are not maintainable without an Account.**
