### ISSUE TITLE
Cant record with VLC

### ISSUE THREAD

**Issue by Turbokek-life** [streamlink/streamlink#2699]
Hey, I started using streamlink recently because of reappearing problems on Twitch side, I suppose, that prevent me from watching streams using just VLC. It worked like a charm for me earlier, I was just using open media -> network, pasted stream url and it played a stream with me being able to record any part of it using VLC record feature. But then, after Twitch API issues, I went to google and found out about streamlink. Great product, btw, I really like how it works. But my issue is that I cant record anything with VLC now. I press record button and VLC says "Recording" and says that recording is complete after I hit that button once again, but no files appear on my disk at all. I checked, VLC still records anything just fine but doesnt when its open via streamlink. Im not a IT person, I had to sign up to Github just to ask this question here. Sorry if it's a wrond place or I use some tags wrong, but please, help me out with this. Is VLC working differently via streamlink? I found out that with -o option I can record anything that is being streamed via streamlink, but I really dont need full stream VODs, I want to be able to records part of it when needed. That's it, thanks alot in advance.

**Comment by bastimeyer** [comment]
Use Streamlink's [`--player-passthrough=hls`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough) parameter, so it'll pass the resolved HLS stream URL to your chosen player as launch argument instead of downloading and piping the concatenated HLS stream into it. This way, you should be able to do everything you've been previously doing in VLC. You can't use any Streamlink parameters related to stream downloading / buffering though.

**Comment by Turbokek-life** [comment]
> Use Streamlink's [`--player-passthrough=hls`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough) parameter, so it'll pass the resolved HLS stream URL to your chosen player as launch argument instead of downloading and piping the concatenated HLS stream into it. This way, you should be able to do everything you've been previously doing in VLC. You can't use any Streamlink parameters related to stream downloading / buffering though.

Sorry if my questions sound dumb to you, but do I just add "--player-passthrough=hls" to my line in cmd (Im using windows 10) like "streamlink twitch.tv/channelname best --player-passthrough=hls" or do I change that line in the streamlinkrc file? Just did both, nothing changed. And also, thank you for being so fast with response.

**Comment by bastimeyer** [comment]
> to my line in cmd
> or do I change that line in the streamlinkrc file

Like every other Streamlink parameter, you can do both, depending on your use case
https://streamlink.github.io/cli.html

> nothing changed

If you're using the `--player-passthrough=hls` parameter, Streamlink won't download the stream by itself and just pass through the resolved HLS stream URL to your player as launch argument. This means that your player is doing all of the downloading instead. And this further means that you are not limited by reading a progressive stream from the input pipe and instead can freely seek through a VOD.

It is essentially the same as using the `--stream-url` parameter and opening the URL returned by Streamlink in your player.

Keep in mind that until the Twitch issue is properly fixed, you also need to apply one of the two workarounds (or both - unnecessary though) mentioned in #2680.

**Comment by Turbokek-life** [comment]
Keep in mind that until the Twitch issue is properly fixed, you also need to apply one of the two workarounds (or both - unnecessary though) mentioned in #2680.

Thats exactly how I found streamlink in the first place, I already did those. Streamlink plays a stream just fine now, but VLC is still not recording anything even with --player-passthrough=hls parameter.
![image](https://user-images.githubusercontent.com/57844132/68998703-072b1700-08c7-11ea-97c7-0fb0aae6c23c.png)

**Comment by Turbokek-life** [comment]
I even get this line in cmd now as stream starts playing but still no recording in VLC 
![image](https://user-images.githubusercontent.com/57844132/68998770-a5b77800-08c7-11ea-928e-de8c6fb27b44.png)

**Comment by skulblakka** [comment]
I just tested this with 
`streamlink twitch.tv/dansgaming best --player "D:\Program Files\VideoLAN\VLC\vlc.exe"` (works with and without passthrough). Hitting record correctly produces a video under "My documents". 

Using current streamlink and VLC 2.2.6. Whatever issue you are experiencing is not caused by streamlink.

**Comment by Turbokek-life** [comment]
> I just tested this with
> `streamlink twitch.tv/dansgaming best --player "D:\Program Files\VideoLAN\VLC\vlc.exe"` (works with and without passthrough). Hitting record correctly produces a video under "My documents".
> 
> Using current streamlink and VLC 2.2.6. Whatever issue you are experiencing is not caused by streamlink.

I was using VLC 3.0.9, downgraded it to 2.2.6 now and deleted a passthrough line in streamlinkrc file. Not sure exactly what helped, but now it works and I can record using VLC once again. Thank you!
