### ISSUE TITLE
stream/hls.py: name prefix is ignored when checking for alternate stream qualities

### ISSUE THREAD

**Issue by pmrowla** [streamlink/streamlink#2703]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

https://github.com/streamlink/streamlink/blob/074c270d85c8da1581146671dd652704fc922069/src/streamlink/stream/hls.py#L442-L450

This code block will not be executed properly if `name_prefix` was passed into `parse_variant_playlist`.

### Expected / Actual behavior

The `if` conditional should be checking if `streams` contains `name_prefix + stream_name`

### Reproduction steps / Explicit stream URLs to test

Pass any `name_prefix` into `parse_variant_playlist()` for an HLS playlist containing multiple url's for a single stream name (quality)

### Log output

```
N/A
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> stream/hls.py: name prefix is ignored when checking for alternate stream qualities

it checks only the current `parse_variant_playlist` not other `parse_variant_playlist`

https://github.com/streamlink/streamlink/blob/074c270d85c8da1581146671dd652704fc922069/src/streamlink/stream/hls.py#L387

if you set `name_prefix` it will be `Available streams: test720p, test432p, test288p, test224p`

> The if conditional should be checking if streams contains name_prefix + stream_name

wouldn't do anything different as it only uses the current playlist and just adds the prefix at the end,
it would be the same if you add it beforehand.

---

not sure what you really what with this issue, but `name_prefix` doesn't do that much in HLSStream

maybe you got an example how you would use it.

**Comment by pmrowla** [comment]
I noticed it when I was submitting PR #2702 

The m3u8 playlists for that source include two separate entries for 720p (one for 30fps and one for 60). That plugin needs to parse up to 5 separate m3u8 playlists (as one NHL game will have multiple TV broadcasts available) and each one of those m3u8 playlists will have the two 720p entries. I was using `name_prefix` to prepend `home_`, `away_`, etc. prefixes to differentiate the broadcasts.

The expected behavior would be that `parse_variant_playlist` would return a dict containing `home_720p` and `home_720p_alt` (where the `_alt` stream is the second 720p 60fps entry from the m3u8 playlist).

What happens right now is that the first stream is encountered, named `home_720p` and inserted into `streams`. When the second stream is encountered, that function checks to see if `720p` exists in `streams`, and then skips the code for handling an alternate stream (since `streams` contains `home_720p` and not `720p`). At the end of the function, the prefix is added, and inserts `home_720p` into `streams` - replacing the first entry entirely, instead of adding a second `_alt` entry.

**Comment by pmrowla** [comment]
As I said in that PR, it's a one-liner fix, but I didn't make the change in my PR since I was unsure whether or not modifying non-plugin related code in a plugin PR was kosher

**Comment by back-to** [comment]
> As I said in that PR, it's a one-liner fix

well **share it** would make stuff easier and a **m3u8 example**

**Comment by pmrowla** [comment]
m3u8:
```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="captions",LANGUAGE="en",INSTREAM-ID="CC1",NAME="English Closed Captions"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="en",NAME="English"
#EXT-X-STREAM-INF:RESOLUTION=896x504,BANDWIDTH=2140000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
1800K/1800_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=384x216,BANDWIDTH=670000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
450K/450_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=512x288,BANDWIDTH=1000000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
800K/800_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=640x360,BANDWIDTH=1450000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
1200K/1200_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=960x540,BANDWIDTH=2900000,CODECS="avc1.4d001f,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
2500K/2500_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1280x720,BANDWIDTH=4100000,CODECS="avc1.640028,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
3500K/3500_complete-trimmed.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1280x720,BANDWIDTH=6600000,FRAME-RATE=59.94,CODECS="avc1.640028,mp4a.40.2",CLOSED-CAPTIONS="captions",AUDIO="audio"
5600K/5600_complete-trimmed.m3u8
```

The fix is just:
line 442:
``` 
if stream_name in streams:  # rename duplicate streams
```
should be
```
 if name_prefix + stream_name in streams:  # rename duplicate streams 
```

**Comment by back-to** [comment]
> edit: alternatively, stream_name should maybe just be updated to add the prefix earlier in the function before this check even occurs, instead of only adding the prefix when a stream is actually inserted into the streams dict

yes, something like this.

```diff
diff --git a/src/streamlink/stream/hls.py b/src/streamlink/stream/hls.py
index b243b228..6e216b76 100644
--- a/src/streamlink/stream/hls.py
+++ b/src/streamlink/stream/hls.py
@@ -439,6 +439,10 @@ class HLSStream(HTTPStream):
 
             if not stream_name:
                 continue
+
+            if name_prefix:
+                stream_name = '{0}{1}'.format(name_prefix, stream_name)
+
             if stream_name in streams:  # rename duplicate streams
                 stream_name = "{0}_alt".format(stream_name)
                 num_alts = len(list(filter(lambda n: n.startswith(stream_name), streams.keys())))
@@ -481,6 +485,6 @@ class HLSStream(HTTPStream):
                              start_offset=start_offset,
                              duration=duration,
                              **request_params)
-            streams[name_prefix + stream_name] = stream
+            streams[stream_name] = stream
 
         return streams
```

```
       Available streams: away_720p, away_720p_alt, home_720p, home_720p_alt
```
