### ISSUE TITLE
Is it possible to use internet download manager to have resume support with streamlink?

### ISSUE THREAD

**Issue by RaXorX** [streamlink/streamlink#2704]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

As the title says, is it possible to use streamlink and download through internet download manager to give resume support for the downloads?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
No it is not.
