### ISSUE TITLE
clarification of what need to be done to get 13.0 to work

### ISSUE THREAD

**Issue by Baerht** [streamlink/streamlink#2708]
I have installed the latest version  of Streamlinks and I am still getting the 410 client error .Do I need to grab the token from the cookie used by the browser and replace that in the streamlinkrc file or should I " streamlink --twitch-oauth-authenticate " as stated in the installation webpage.

**Comment by bastimeyer** [comment]
> I have installed the latest version of Streamlink

You haven't included a debug log, which is required for posting issues. Post the output of Streamlink with the `--loglevel debug` parameter. You are probably not using the latest version.
