### ISSUE TITLE
Convert changelog to rst

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#271]
As discussed in #238, we should convert the changelog.md file to rst so that it plays nice with the rest of the docs.

**Comment by mmetak** [comment]
@beardypig I kinda already did that in that #238 PR? Or are you looking for a way to automatically generate rst changelog beside the md with the release?

**Comment by beardypig** [comment]
Yeah. It needs to be automated, which requires changing the release script, which @cdrage volunteered to do ;) 

This is blocking your PR #238 :)

**Comment by mmetak** [comment]
`pandoc CHANGELOG.md --from markdown --to rst -s -o docs/changelog.rst`

BTW is 0.2.0 any closer to release? ;)

**Comment by beardypig** [comment]
Easier and more reliable to just generate rst, rather than converting from my :-P

I think there are a few PRs that people want to be merged before the release of 0.2.0 :)

**Comment by joshka** [comment]
I noticed that the changelog contains a lot of information that for an end user to use (and that a dev can usually find more easily by hitting github). Would you maybe consider using a format somewhat like: http://keepachangelog.com/ suggests?

**Comment by gravyboat** [comment]
The suggested items based on keepachangelog.com versus what we have here: https://github.com/streamlink/streamlink/releases:

* It’s made for humans, not machines, so legibility is crucial. - We already do this when we note the major features of the release so non-technical users can easily review them. 
* Easy to link to any section (hence Markdown over plain text). - We don't currently do this, and the changelog isn't usually such a long list that we currently need this
* One sub-section per version. - We fulfill this though not perfectly, each release has a different area on the page (though this could be condensed into a version specific changelog that has multiple releases).
* List releases in reverse-chronological order (newest on top). - We already do this.
* Write all dates in YYYY-MM-DD format. (Example: 2012-06-02 for June 2nd, 2012.) It’s international, sensible, and language-independent. - We do this automatically via the GitHub release details noting when the build was released, though the formatting isn't perfect.
* Explicitly mention whether the project follows Semantic Versioning. - We already follow semantic versioning, I don't really feel like this needs to be explicitly noted, those who don't follow semantic versioning should probably note this instead. ;)
* Each version should:
  * List its release date in the above format. - As noted above we kind of do this.
  * Group changes to describe their impact on the project, as follows: - Currently we simply group all of these together as we don't have enough changes to really justify categories. If we did that we would have more categories than changes in many cases.
    * Added for new features.
    * Changed for changes in existing functionality.
    * Deprecated for once-stable features removed in upcoming releases.
    * Removed for deprecated features removed in this release.
    * Fixed for any bug fixes.
    * Security to invite users to upgrade in case of vulnerabilities.

Overall there are definitely a few changes we could implement to provide a better changelog. I would actually say we should leave the existing changelog as is for the releases, and create a new user centric changelog for the docs specifically (though that does take some visibility away from contributors in the event people wish to donate to them or thank them in some way).

**Comment by beardypig** [comment]
I like the up to date "Unreleased" list of changes, cool for the nightlies :-)

**Comment by beardypig** [comment]
They has been merged now and we have an `rst` changelog :)
