### ISSUE TITLE
Issues for Linux server

### ISSUE THREAD

**Issue by Dreammer12138** [streamlink/streamlink#2710]
Linux server cannot be used properly after installation

```
error: Unable to validate JSON: Unable to validate key 'data': {'current_quality': 0, 'accept_quality': None, 'current_qn': 0} does not equal None or Key 'durl' not found in {'current_quality': 0, 'accept_quality': None, 'current_qn': 0}
```

How to fix？

**Comment by back-to** [comment]
https://raw.githubusercontent.com/streamlink/streamlink/master/.github/ISSUE_TEMPLATE/plugin_issue.md

**Comment by Dreammer12138** [comment]
---
name: Bug Issue
about: Not working properly
---




## Not working properly




### Linux server cannot be used properly after installation








```
streamlink url best -o test.mp4
error: Unable to validate JSON: Unable to validate key 'data': {'current_quality': 0, 'accept_quality': None, 'current_qn': 0} does not equal None or Key 'durl' not found in {'current_quality': 0, 'accept_quality': None, 'current_qn': 0}
```





[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)
