### ISSUE TITLE
plugins.twitch: not recognizing end of hosting

### ISSUE THREAD

**Issue by Mr-J** [streamlink/streamlink#2711]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Automatic recording from twitch channel is failing since the end of the hosted stream (with --twitch-disable-hosting option) is not recognized.

### Reproduction steps / Explicit stream URLs to test

1. Start waiting for a stream with following command: streamlink http://www.twitch.tv/somechannel 720p --twitch-disable-hosting --player-continuous-http --retry-streams 20 --retry-open 5 --hls-timeout 300 --player D:/Programme/videolan/vlc/vlc.exe -o \"f:/target.file"
2. The channel must be hosting another channel currently.
3. After the hosting ends, streamlink still displays "[plugin.twitch][info] hosting was disabled by command line option" and will not start recording the channel if it starts streaming.

### Log output

```
F:\                                                                                                                                    
λ streamlink http://www.twitch.tv/royalphunk 720p --loglevel debug --twitch-disable-hosting --player-continuous-http --retry-streams 20
--retry-open 5 --hls-timeout 300 --player D:/Programme/videolan/vlc/vlc.exe -o "f:/some.file"                                          
[cli][debug] OS:         Windows 10                                                                                                    
[cli][debug] Python:     3.6.6                                                                                                         
[cli][debug] Streamlink: 1.3.0                                                                                                         
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)                                                                         
[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/royalphunk                                                       
[cli][debug] Plugin specific arguments:                                                                                                
[cli][debug]  --twitch-disable-hosting=True (disable_hosting)                                                                          
[plugin.twitch][debug] Getting live HLS streams for royalphunk                                                                         
[plugin.twitch][info] royalphunk is hosting carnage64                                                                                  
[plugin.twitch][info] hosting was disabled by command line option                                                                      
```

**Comment by bastimeyer** [comment]
You can't use any of the retry or timeout parameters in combination with the `--twitch-disable-hosting` option. The stream hosting has to be resolved before acquiring the HLS stream URL with an access token. Retry and timeout parameters only affect the HLS streaming logic afterwards. If a channel is hosting another one, you'll either have to let streamlink's process terminate and try again or use a wrapper script that checks the live/hosting status on the Twitch API before launching streamlink. The `--twitch-disable-hosting` parameter itself is working correctly.

```
$ streamlink -l debug --twitch-disable-hosting twitch.tv/royalphunk
[cli][debug] OS:         Linux-5.4.0-rc7-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0+4.gc1a146f
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/royalphunk
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-disable-hosting=True (disable_hosting)
[plugin.twitch][debug] Getting live HLS streams for royalphunk
[plugin.twitch][info] royalphunk is hosting carnage64
[plugin.twitch][info] hosting was disabled by command line option
[utils.l10n][debug] Language code: en_US
error: No playable streams found on this URL: twitch.tv/royalphunk

$ streamlink -l debug twitch.tv/royalphunk
[cli][debug] OS:         Linux-5.4.0-rc7-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0+4.gc1a146f
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/royalphunk
[plugin.twitch][debug] Getting live HLS streams for royalphunk
[plugin.twitch][info] royalphunk is hosting carnage64
[plugin.twitch][info] switching to carnage64
[plugin.twitch][debug] Getting live HLS streams for carnage64
[utils.l10n][debug] Language code: en_US
Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
```

**Comment by Mr-J** [comment]
So, if i combine the --twitch-disable-hosting with the --retry-streams 20 and --retry-open 5 options this will basicaly result in an endless loop? I find this a bit strange since sometimes it seems to work, the end of hosting mode is recognized and the recording of the stream on the channel afterwards works but sometimes not.

A simple alternativ would be a wrapper python script waiting for 2-5 seconds and launching the command again like this? -> streamlink http://www.twitch.tv/royalphunk 720p --twitch-disable-hosting --player-continuous-http --player D:/Programme/videolan/vlc/vlc.exe -o "f:/some.file"

**Comment by testytrash** [comment]
A similar issue also appears when you lose internet connection (and recover) as well as changing to a VPN while the process is running.
Streamlink will not recognize the new scenario and therefore stop working properly.

I'd like to ask @bastimeyer if it's possible to at least make it close the process in this case instead of a "misleading" loop that won't work.

Thanks in advance!

**Comment by bastimeyer** [comment]
> So, if i combine the --twitch-disable-hosting with the --retry-streams 20 and --retry-open 5 options this will basicaly result in an endless loop?

You should set the [`--retry-max=count`](https://streamlink.github.io/cli.html#cmdoption-retry-max) parameter if you don't want an infinite loop.

> the end of hosting mode is recognized and the recording of the stream on the channel afterwards works but sometimes not.

Streamlink can not detect when a channel has stopped hosting another one while you're watching that hosted stream. Once a stream has been resolved, it'll continue using it.

When a channel is hosting another one, you're essentially watching a different stream with a different access token. You have to understand the difference between watching a resolved HLS stream and reading stream-hosting data from the API and redirecting the user to a different stream before aquiring a stream access token.

-----

> A similar issue also appears when you lose internet connection (and recover) as well as changing to a VPN while the process is running.

This has nothing to do with the topic of this issue. If you're having a questing regarding Streamlink's HLS logic, you can open a new thread.
