### ISSUE TITLE
A small question about video recording

### ISSUE THREAD

**Issue by Murloc111** [streamlink/streamlink#2714]
I wanted to understand how the process of recording video to a file happens (option -o), but I could not find a specific file where it happens. Please tell me where it is.

**Comment by back-to** [comment]
> I wanted to understand how the process of recording video to a file happens (option -o), but I could not find a specific file where it happens. Please tell me where it is.

it is basically `FileOutput`, there is not much to say about it.

https://github.com/streamlink/streamlink/blob/9253fc5128da0c7fb01375de9c0d051f7f835b61/src/streamlink_cli/main.py#L53-L96
https://github.com/streamlink/streamlink/blob/9253fc5128da0c7fb01375de9c0d051f7f835b61/src/streamlink_cli/output.py#L49-L75
