### ISSUE TITLE
Youtube __init__() Breaks for some videos in Python 3.6.1

### ISSUE THREAD

**Issue by gdmurray** [streamlink/streamlink#2715]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
Streamlink Version: `streamlink-1.3.0`
Python Version: `3.6.1`

When using streamlink to download videos through youtube on the new version of streamlink, the init line breaks for _some_ videos. [Line in Question](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L180)

After changing the line to `super().__init__(url)`, the error no longer occurs for any videos.

### Expected / Actual behavior
The expected behavior is for this to not happen. Additionally, this bug did not appear until I updated streamlink to 1.3.0.

### Reproduction steps / Explicit stream URLs to test

In my case, I am using a multithreaded process to download multiple videos simultaneously. I am using these urls
1. https://www.youtube.com/watch?v=Cl2l-PQOKyM
2. https://www.youtube.com/watch?v=Ng6nflV3Vxw **breaks**
3. https://www.youtube.com/watch?v=dRkWhTnrEeQ
4. https://www.youtube.com/watch?v=jmP1DQnXezU **breaks**

### Log output

```
Traceback (most recent call last):
  File "C:/Users/GD-Mu/Projects/rainbow6bot/multi_test/main.py", line 30, in process_video
    stream = streamlink.streams(url)
  File "C:\Users\GD-Mu\Envs\r6bot\lib\site-packages\streamlink\api.py", line 13, in streams
    return session.streams(url, **params)
  File "C:\Users\GD-Mu\Envs\r6bot\lib\site-packages\streamlink\session.py", line 441, in streams
    plugin = self.resolve_url(url)
  File "C:\Users\GD-Mu\Envs\r6bot\lib\site-packages\streamlink\utils\__init__.py", line 149, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "C:\Users\GD-Mu\Envs\r6bot\lib\site-packages\streamlink\session.py", line 402, in resolve_url
    return available_plugins[0](url)
  File "C:\Users\GD-Mu\Envs\r6bot\lib\site-packages\streamlink\plugins\youtube.py", line 180, in __init__
    super(YouTube, self).__init__(url)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I cannot reproduce this, all URLs work fine for me. I think you will have to give some more details about how you are invoking the plugins. 

In Python 3 `super(__class__, self)`, `super(YouTube, self)` and `super()` are all equivalent in this case. However, only `super(YouTube, self)` will work in Python 2.7.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/3089
