### ISSUE TITLE
BBC iPlayer authentication error

### ISSUE THREAD

**Issue by ryanjgillies** [streamlink/streamlink#2716]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When attempting to stream from iplayer I'm receiving the following error:
```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.4
[cli][debug] Streamlink: 1.2.0+22.g6ac9ee0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin bbciplayer for URL https://www.bbc.co.uk/iplayer/episode/b03wc5kx/andys-dinosaur-adventures-2-diplodocus-and-fern
[cli][debug] Plugin specific arguments:
[cli][debug]  --bbciplayer-username=********@gmail.com (username)
[cli][debug]  --bbciplayer-password=******** (password)
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, check your username and password
```

### Reproduction steps / Explicit stream URLs to test

This is affecting me with all iplayer streams. My config file hasn't changed and I am still able to login via the BBC website using the same credentials.

**Comment by mkbloke** [comment]
It seems that ptrt_url is no longer found via the history search in auth_check() after the login data has been sent.

The login process itself still appears to be working correctly.  If I change the code to just return true at the end of login(), I can successfully get a live programme stream or stream an iPlayer programme via catch up.

**Comment by kachelaqa** [comment]
> The login process itself still appears to be working correctly, as far as I can see. If I change the code to just return true at the end of login(), I can successfully get a live programme stream.

Yes, I also used the same work-around. However, whilst experimenting, I discovered something strange about the login process. If I change the username / password to something random like `foo@total.junk.com / 123`, it still logs in (although sometimes only after a long delay).

**Comment by mkbloke** [comment]
> Yes, I also used the same work-around. However, whilst experimenting, I discovered something strange about the login process. If I change the username / password to something random like `foo@total.junk.com / 123`, it still logs in (although sometimes only after a long delay).

That's interesting.  I did wonder if it was in fact logging in correctly and wanted to try to verify that.  I tried printing res.content and res.text via log.debug(), but in both cases I ran into issues regarding encoding, despite trying to set res.encoding = 'utf-8'.  Not knowing how to resolve that, I gave up.  What I was hoping to see was that the relevant `<span></span>` part of the page had changed from 'Sign in' to 'Ian'.

I wonder if a login bypass is occurring?

**Comment by kachelaqa** [comment]
> I wonder if a login bypass is occurring?

Is authentication obligatory, or is streamlink just paying lip-service? A [BBC Account](https://www.bbc.co.uk/usingthebbc/account/what-is-a-bbc-account/) is needed to use some services through their website, but regsistering is obviously not sufficient - a licence is also required. The registration info is shared with TV Licencing, but I'm not sure whether this comes into play when accessing streams outside the website. On the face of it, it would seem not.

**Comment by mkbloke** [comment]
> > I wonder if a login bypass is occurring?
> 
> Is authentication obligatory, or is streamlink just paying lip-service? A [BBC Account](https://www.bbc.co.uk/usingthebbc/account/what-is-a-bbc-account/) is needed to use some services through their website, but regsistering is obviously not sufficient - a licence is also required. The registration info is shared with TV Licencing, but I'm not sure whether this comes into play when accessing streams outside the website. On the face of it, it would seem not.

I don't know the answers to any of that, really, other than the requirement - I believe - to possess a TV licence for live TV viewing.

**Comment by ryanjgillies** [comment]
@mkbloke your solution worked for me too, thanks.

As a side note can we update the [manual on sideloading plugins](https://streamlink.github.io/cli.html#sideloading-plugins) ?  It took me a while to realise on Windows that plugins are loaded from `%APPDATA%\Roaming\streamlink\plugins` rather than the quoted `%APPDATA%\streamlink\plugins`

**Comment by bastimeyer** [comment]
> can we update the [manual on sideloading plugins](https://streamlink.github.io/cli.html#sideloading-plugins) ?

https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink_cli/constants.py#L20-L23

**Comment by mkbloke** [comment]
> @mkbloke your solution worked for me too, thanks.

Just to point out, it's not a solution!  I was just trying to see if the login process was still working.  I thought it likely that it must be, but as per above, I have not fully verified that.  The comments above by kachelaqa suggest the code might not be logging in at all...

**Comment by tmatthews5511** [comment]
> > > I wonder if a login bypass is occurring?
> > 
> > 
> > Is authentication obligatory, or is streamlink just paying lip-service? A [BBC Account](https://www.bbc.co.uk/usingthebbc/account/what-is-a-bbc-account/) is needed to use some services through their website, but regsistering is obviously not sufficient - a licence is also required. The registration info is shared with TV Licencing, but I'm not sure whether this comes into play when accessing streams outside the website. On the face of it, it would seem not.
> 
> I don't know the answers to any of that, really, other than the requirement - I believe - to possess a TV licence for live TV viewing.

Nowadays for the BBC in the UK,  one must have a TV Licence for live viewing and for using the BBC iPlayer.

**Comment by tmatthews5511** [comment]
I would like to confirm that this is happening on Linux (Linux Mint 19.3)

streamlink --version
streamlink 1.3.0

streamlink http://www.bbc.co.uk/iplayer/live/bbcone best --bbciplayer-username xxx@xxx --bbciplayer-password xxxxx
[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, check your username and password
error: No playable streams found on this URL: http://www.bbc.co.uk/iplayer/live/bbcone

**Comment by mkbloke** [comment]
This *might* be the right fix...

[bbciplayer.py.patch.txt](https://github.com/streamlink/streamlink/files/3957891/bbciplayer.py.patch.txt)

**Comment by tmatthews5511** [comment]
Yes, that patch works very well. I can now sleep again.

Thanks Ian!
