### ISSUE TITLE
What is the correct commend line ??

### ISSUE THREAD

**Issue by hamza-mostakim** [streamlink/streamlink#2717]
Hello All ☺

I need help please 🙂 

What is the correct commend line to play this link : 

[https://ksa1.aflamyz.net/player/hls.php?id=844f6f7449fa7365758833656c8c2f04](url)

and Thank you so much in advanced ❤️

**Comment by bastimeyer** [comment]
This is a bug/issue tracker and not a help forum.

If you want to request a plugin for Streamlink for the website you're trying to access, you'll have to open a plugin request issue and fill in the required informations. This here however is not a plugin request and the site you've linked doesn't look legit and neither does the site of the stream source.

**Comment by hamza-mostakim** [comment]
OK bro I'm so sorry 😢 and Thank you for request ❤️
