### ISSUE TITLE
Twitch VOD ID of live stream

### ISSUE THREAD

**Issue by EnterGin** [streamlink/streamlink#2719]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Can I get a VOD ID of live stream? Or get a VOD ID of past or present streams?

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
What you are asking for has nothing to do with Streamlink.

https://dev.twitch.tv/docs/
