### ISSUE TITLE
Streamlink orga permissions

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#272]
Now that there are more repos in this orga, a change of the default permissions was necessary.
After talking to @cdrage, the permissions are now all set in the registered teams instead of the global orga settings. This way we have more control over who has access to certain repos.

Just drop a note if there's anything wrong, or if anybody has been missed, or if new permissions are required.

Also, please don't forget to use two factor authentication on Github if possible, just to be sure. 😜 😄

**Comment by gravyboat** [comment]
I'm going to close this out since it's historical at this point. I would just like to reiterate that if you don't have 2FA enabled please do so.
