### ISSUE TITLE
tvplayer.com plugin with --http-cookie persistence-v2 addition not working anymore

### ISSUE THREAD

**Issue by tmatthews5511** [streamlink/streamlink#2720]
Streamlink no longer works with tvplayer.com, using the --http-cookie persistence-v2 from Firefox.

Streamlink was working with tvplayer.com, using the --http-cookie persistence-v2 from Firefox.

Now it gives this error:

[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/bbcone
[plugin.tvplayer][warning] Failed to login as xxx@xxx.blah
error: No playable streams found on this URL: https://tvplayer.com/watch/bbcone

Reproduction:

Use tvplayer.com with Firefox (will need an UK ip-address). This is to obtain the lastest cookie. 

Use this script to get the cookie from Firefox:

https://gist.githubusercontent.com/chrisarnott86/3e55ca7edf39a358f9375964539d77fb/raw/e3c97884de2d2afe19e59acf6c34210a3216b392/cookie-fetch.sh

With the --http-cookie persistence-v2 option (using the latest Firefox cookie) it was working, but seems not to be the case anymore.

**Comment by mkbloke** [comment]
I renewed my tvplayer.com cookie today - less than two and a half hours ago - which I do about every two weeks.  I have just tested it by streaming BBC One and had no problem with it.

Maybe the cookie-fetch.sh script is failing.  I'd suggest you try manually copying the cookie from Firefox and insert that by hand into the command line with streamlink to test it.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2720
