### ISSUE TITLE
Twitch disable reruns

### ISSUE THREAD

**Issue by EnterGin** [streamlink/streamlink#2721]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

There are disabling hosts (--twitch-disable-hosting), can you also add disabling reruns?

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I don't think the reruns are actually public like the hosting is since the host is simply a redirect right? Try running with the debug log on and see if it mentions anything about a rerun like it does for a host. If it doesn't there probably isn't anything we can do.

**Comment by EnterGin** [comment]
Nothing about reruns in log. Sad :(
