### ISSUE TITLE
410 Client Error: Gone for url again with twitch plugin

### ISSUE THREAD

**Issue by GodSponge** [streamlink/streamlink#2723]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The error I'm getting seems to be fairly well known, but I thought it was fixed in 1.3.0. It was documented in https://github.com/streamlink/streamlink/issues/2680.
I've gotten the newest version of streamlink that is supposed to fix (410 Client Error: Gone for url)
but it seems to either still be happening, or has started happening again. I don't even care about logging in. It was nice, but the plugin isn't working at all again. I have an oauth token in my config, but it fails whether that is there or not.

### Reproduction steps / Explicit stream URLs to test

try to start any stream on twitch

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.5.2
[cli][debug] Streamlink: 0.14.2
[cli][debug] Requests(2.19.1), Socks(1.6.7), Websocket(0.48.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/streamname
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-oauth-token=******** (oauth_token)
[plugin.twitch][debug] Getting live HLS streams for streamname
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as username
error: Unable to open URL: https://api.twitch.tv/api/channels/streamname/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/streamname/access_token.json?oauth_token=4egps85j23zcfsb2bb9fnoydo98zfv&as3=t)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> Streamlink: 0.14.2

You are not using 1.3.0

See this comment if you need help figuring this out:
https://github.com/streamlink/streamlink/issues/2709#issuecomment-557855770

**Comment by GodSponge** [comment]
That is what the 1.3.0 installer installed

**Comment by gravyboat** [comment]
@GodSponge Depending on how your machine is set up you may need to uninstall Streamlink first and potentially delete the file directory, then run the installer again.

**Comment by bastimeyer** [comment]
No, when you are executing `streamlink` from your command line shell, it has to look up the executable first and this depends on the order of the paths listed in the `PATH` environment variable. This means that an older Streamlink install path can still be there and you're using it if you don't specify an absolute or relative path to the `streamlink` executable.

**Comment by GodSponge** [comment]
I did exactly that. I deleted the whole directory and i ran streamlink from the directory it was just installed in.
I just typed the full path instead of just streamlink.exe and it did run 1.3.0, but i have no idea where the old one could be hiding. I've always installed it in D:\Programs\Streamlink and that is what is in my PATH also... guess I'm going hunting.

**Comment by GodSponge** [comment]
Looks like it got installed to program files on C at some point in the past and it's been using that old version since then. I feel rather stupid that I didn't find this earlier. Thanks for the help. The reason it got past me was apparently the old streamlink added to the USER path and not the SYSTEM path. I only checked in the SYSTEM path.
