### ISSUE TITLE
SHOWROOM: Questions about missing segments in Showroom-live.com

### ISSUE THREAD

**Issue by CplSgt82** [streamlink/streamlink#2726]
## Issue

- [x ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

Problem: Streamlink will "skip" segments when downloading live streams (m3u8 playlist) from https://www.showroom-live.com/ 

There is no error msg, the log displayed "adding segment 500 to the queue" and then it will jump to "adding segment 502 to the queue" but i know that a segment is skipped because the video will freeze for a few seconds during playback. 

Addition info: Each segment is very short (less than 4s in playback) , and i have a very high ping to the server.
This "missing segment problem" occurs very frequently only on all hls playlist I download from this website, about 40 times average in a 2hr live stream. I have no such issue from other sites like youtube and bilibili.

Options tried: 
streamlink --loglevel debug --hls-segment-threads 10 --hls-segment-timeout 60.0 --hls-segment-attempts 60 --hls-live-edge 3 --ringbuffer-size 100M --hls-playlist-reload-attempts 3 https://hls-cdn17-showroom.cdn-dena.com/liveedge/7e41091a3cd59397262028d1c90bce30c6824df276d4e91b425fe0b72bfd0803/chunklist_v2.m3u8 best  -o file.mp4

I tried setting --hls-live-edge from 1 to 9, but the missing segments problem is still there. 

### Expected / Actual behavior

Questions: 
1. Any solutions to solve this missing segments problem? for eg, Is there any options in streamlink to force it to download segments in order without skipping? 
2. Is there any options to add more than 2 segments to the queue?
3. Any options in streamlink to keep hammering the server for 1 particular segment until it fetches it? 

### Reproduction steps / Explicit stream URLs to test

1. ...go to https://www.showroom-live.com/
2. ...Enter anyone of the live stream channels and fetch the m3u8 playlist. (i use stream detector FF plugin)
3. ...start streamlink and download to file 

### Logs

```
streamlink --loglevel debug --hls-segment-threads 10 --hls-segment-timeout 60.0 --hls-segment-attempts 60 --hls-live-edge 3 --ringbuffer-size 100M --hls-playlist-reload-attempts 3 https://hls-cdn17-showroom.cdn-dena.com/liveedge/7e41091a3cd59397262028d1c90bce30c6824df276d4e91b425fe0b72bfd0803/chunklist_v2.m3u8 best  -o file.mp4
.
.
.
.
.
stream.hls][debug] Download of segment 942 complete
[download][file.mp4] Written 1.6 MB (17s @ 98.1 KB/s)
stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 943 to queue
[stream.hls][debug] Adding segment 944 to queue
[stream.hls][debug] Download of segment 943 complete
[download][file.mp4] Written 1.8 MB (20s @ 84.0 KB/s)
stream.hls][debug] Download of segment 944 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 945 to queue
[stream.hls][debug] Download of segment 945 complete
[download][file.mp4] Written 2.2 MB (25s @ 93.8 KB/s)
stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 946 to queue
[stream.hls][debug] Adding segment 947 to queue
[stream.hls][debug] Download of segment 946 complete
[download][file.mp4] Written 2.4 MB (30s @ 75.7 KB/s)[stream.hls][debug] Download of segment 947 complete
                                                                                           [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 948 to queue
[stream.hls][debug] Adding segment 949 to queue
[stream.hls][debug] Download of segment 948 complete
[download][file.mp4] Written 2.9 MB (33s @ 88.7 KB/s)
stream.hls][debug] Download of segment 949 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 950 to queue
[stream.hls][debug] Adding segment 951 to queue
[stream.hls][debug] Download of segment 950 complete
[download][file.mp4] Written 3.3 MB (37s @ 83.7 KB/s)
stream.hls][debug] Download of segment 951 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 952 to queue
[stream.hls][debug] Adding segment 953 to queue
[stream.hls][debug] Download of segment 952 complete
[download][file.mp4] Written 3.7 MB (41s @ 93.0 KB/s)
stream.hls][debug] Download of segment 953 complete
[download][file.mp4] Written 3.9 MB (42s @ 106.0 KB/s)
stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 954 to queue
[stream.hls][debug] Adding segment 955 to queue
[stream.hls][debug] Download of segment 954 complete
[download][file.mp4] Written 4.1 MB (45s @ 116.3 KB/s)[stream.hls][debug] Download of segment 955 complete
                                                                                          [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 957 to queue
[stream.hls][debug] Adding segment 958 to queue



```

### Additional comments, screenshots, etc.
In the above example, segment 956 has been skipped.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
Streamlink uses the `TARGETDURATION` from the playlist as the _reload time_

https://github.com/streamlink/streamlink/blob/4d9d285c953f329a5ae7424d675b428d859ad73f/src/streamlink/stream/hls.py#L224

which is `5 sec` here, but this is **false** as there are only `4 sec` of videodata

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:1318
#EXTINF:1.986,
media_v2_1318.ts
#EXTINF:1.999,
media_v2_1319.ts
```

basically this website sends wrong data,
in order to fix it Streamlink would need to calculate it differently.

**Comment by wlerin** [comment]
> which is 5 sec here, but this is false as there are only 4 sec of videodata

It's worse than that, the `TARGETDURATION` should be `2 sec` because that's the (maximum) length of *one* segment. I'll have to look into this a bit.

**Comment by Billy2011** [comment]
There is a clear definition in the apple hls drafts: [https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.1](url)

**Comment by wlerin** [comment]
By that section alone the above playlist is conforming. But it's not, because this is also in the spec

> The server MUST NOT remove a Media Segment from a Playlist file without an EXT-X-ENDLIST tag if that would produce a Playlist whose duration is less than three times the target duration.  Doing so can trigger playback stalls.

**Comment by Billy2011** [comment]
I only referred to the **TARGETDURATION** or your interpretations for it and not to the entire playlist.

With such large download latencies, freezers are predictable and it will hardly be possible to make an error-free download. The strong reduction of the playlist reloadtime only produces a high server load and this contradicts the sense of the HLS protocol.

In my opinion, all the changes to the HLS parameters are ineffective and you should rather try to lower the resolution or work with the RTMP streams that the plugin also uses (this was always the case in my attempts).

**Comment by wlerin** [comment]
> With such large download latencies

The problem is that there is minimal latency even for the regular HLS playlist. It's only delayed about 5 seconds from real time, as can be seen in how swiftly new comments are answered.

Their in-browser player seems to ignore the TARGETDURATION and refresh at about a rate of once per 3 seconds.

> work with the RTMP streams that the plugin also uses

Certain streams only have HLS available, and they have made several abortive attempts to replace RTMP with "LHLS". There've been several periods in the last 2 months where the majority of streams had only HLS and LHLS available, and in those cases recordings were full of skips and gaps.

**Comment by Billy2011** [comment]
> The in-browser player thus seems to ignore the TARGETDURATION and refresh at a rate of about once per 3 seconds.

I think that is not the case, the browser player is probably specially adapted and uses half of the playlist reloadtime, round (TARGETDURATION / 2) = 3s and this is still HLS compliant, but this time is normally only used after a failed reload attempt.
If the TARGETDURATION were set to 3s, then this is no longer HLS compliant.

**Comment by wlerin** [comment]
So, I've been looking into this more, and I have a question. How well does streamlink's HLS implementation handle EXT-X-DISCONTINUITY? Because that's at least one of the issues at play here.

**Comment by zack9911** [comment]
what the best command for showroom live? 
im new using streamlink so i record when the streamer poor connection my file is broken cant play 
how make auto reconect when the stremer restream

**Comment by wlerin** [comment]
> im new using streamlink so i record when the streamer poor connection my file is broken cant play

Output to .ts not .mp4 (you can convert it to mp4 once it finishes using ffmpeg). For example:

    streamlink https://www.showroom-live.com/48_Megu_Taniguchi best -o MeguRoom.ts

> how make auto reconect when the stremer restream

I'm not exactly sure, but you might try one of the retry options listed in the documentation:
https://streamlink.github.io/cli.html#command-line-usage
