### ISSUE TITLE
ITV :: AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by ezbik** [streamlink/streamlink#2727]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Recently ITV plugin has started throwing an error.

### Expected / Actual behavior

Correct stream handle.

### Reproduction steps / Explicit stream URLs to test

```
streamlink https://www.itv.com/hub/ibiza-weekender/2a3296a0039
```

### Log output

```
 # /opt/streamlink.git/bin/streamlink https://www.itv.com/hub/im-a-celebrity-get-me-out-of-here/1a7103a0246  
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/im-a-celebrity-get-me-out-of-here/1a7103a0246
Traceback (most recent call last):
  File "/opt/streamlink.git/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.3.0+1.g11370e5', 'console_scripts', 'streamlink')()
  File "/opt/streamlink.git/lib/python3.4/site-packages/streamlink-1.3.0+1.g11370e5-py3.4.egg/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/opt/streamlink.git/lib/python3.4/site-packages/streamlink-1.3.0+1.g11370e5-py3.4.egg/streamlink_cli/main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "/opt/streamlink.git/lib/python3.4/site-packages/streamlink-1.3.0+1.g11370e5-py3.4.egg/streamlink_cli/main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/opt/streamlink.git/lib/python3.4/site-packages/streamlink-1.3.0+1.g11370e5-py3.4.egg/streamlink/plugin/plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "/opt/streamlink.git/lib/python3.4/site-packages/streamlink-1.3.0+1.g11370e5-py3.4.egg/streamlink/plugins/itvplayer.py", line 95, in _get_streams
    if video_info_url.endswith(".xml"):
AttributeError: 'NoneType' object has no attribute 'endswith'


```

### Additional comments, screenshots, etc.

```
# /opt/streamlink.git/bin/streamlink -V
streamlink 1.3.0+1.g11370e5
# /opt/streamlink.git/bin/python -V
Python 3.4.10
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by jeanwalm** [comment]
i have the same issue when will this be fixed?

**Comment by gravyboat** [comment]
@jeanwalm Someone will have to pick it up who is interested in the plugin, we're a small team so I don't have any sort of timeline for you. If you want to dive in feel free!

**Comment by mkbloke** [comment]
I'm not sure the ITV player plugin is fixable now.  They appear to have implemented Widevine DRM:

https://help.itv.com/hc/en-us/articles/360004308253-I-m-having-trouble-streaming-the-live-channels

Also, the website is currently not working in non Google browsers on Linux, even with the option to enable the playing of DRM content ticked.  There are a few threads about this issue on various forums, with a number of people having emailed ITV Hub support, who say they are looking into getting it fixed.  That's nothing to do with streamlink of course, but I'm just mentioning it for info.

It *looks* like DRM is now enabled on the VoD service and all live channels.  That makes me think the ITV player plugin may have reached the end of its life...

**Comment by gravyboat** [comment]
@mkbloke Yep if this is the case we'll have to deprecate it. We've taken the stance that we are not going to try and deal with or circumvent DRM.

**Comment by mkbloke** [comment]
@gravyboat, yes, I'm aware of the policy and can't say I disagree with it.  It's unfortunate, of course...

I've also duplicated my above comment in: https://github.com/streamlink/streamlink/issues/2718

In the event that the plugin is deprecated, both issues can be closed.

**Comment by gravyboat** [comment]
@mkbloke Yeah it's unfortunate but DRM is just such a headache to deal with it's not tenable for us. Thanks for being understanding.

**Comment by Vangelis66** [comment]
Hello Forrest, I hope all's well with you 😄 

I am fully aware that `streamlink` focuses _mainly_ on **live** streams, and it is highly unfortunate that a vast plethora of media providers now succumb to Google/Apple and implement **full DRM** (cenc with **Widevine CDM** for MPEG-DASH streams and/or FairPlay for HLS streams), but the OP was trying an ITVHub **catch-up (VOD) stream**... 

While it is, sadly, also true that in desktop browsers **ITVHub** have recently switched, for on-demand streams, from **ClearKey encryption** to **fully fledged DRM** (WidevineCDM), for a certain type of their VOD streams, targetting mainly older iPhones, they're still (at the time of this writing) using **HLSe** (AES-128 encrypted) streams which, AFAIK, are streamlink compatible... These are the kind of streams that `yt-dl` currently has support for... 

So I feel it's kinda premature to abandon completely the itvhub plugin, perhaps there's some interest out there by someone wanting to fork/port `yt-dl`'s `itv.py` code to streamlink, just for ITVHub VOD? 
I've seen stranger things happen... 

However, I'm not very optimistic about those ITVHub HLSe streams being available for very long... The trend is, as it's been manifested already in other SL/yt-dl issues, of **everyone going DRM **everywhere****; and that is something the media consumers themselves (users) have allowed, by accepting willy-nilly the abomination that is DRM and NOT voicing their opposition to it in an "audible" fashion... 😞 

I am old enough to remember the era of **Windows Media DRM** and **iTunes DRM**, these are now mostly bad memories, but with mighty Google conquering the whole web, **Widevine** (bought up and owned by Google) is here to STAY 😠 ...
Apologies for the rant, my best wishes to the whole streamlink organisation 👍
