### ISSUE TITLE
Iam getting 403 Error..

### ISSUE THREAD

**Issue by kishan167** [streamlink/streamlink#2728]
## Feature Request

- [] This is a feature request and I have read the contribution guidelines.

### Description

Hi there when i try to download iam getting 403 Client Error: Forbidden for url
### Expected / Actual behavior

Tired all the code Below

> streamlink --loglevel=debug --player=mpv "https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e"

> streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko" "hlsvariant://https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e"

> streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko" "https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e"

> streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko" "hls://https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e"

### Additional comments, screenshots, etc.

[Streamlink for Windows v1.3.0 - Git 478013b]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.3.0+478013b
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin hls for URL hlsvariant://https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e
[plugin.hls][debug] URL=https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e; params={}
[utils.l10n][debug] Language code: en_AU
error: Unable to open URL: https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e (403 Client Error: Forbidden for url: https://hses1.akamaized.net/videos/movies/tamil/uyirullavaraikaadhal/1260014342/1575109364727/7b8565dd37555beb901334f4378ffdec/master-phone.m3u8?ladder=phone&hdnea=st=1575668215~exp=1575671815~acl=/*~hmac=14e6948372eac5e72efc6c9d101a201df20503e333fc37597733b0205447d12e)
[End of Streamlink for Windows with ExitCode 1]

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> 403 Client Error

**Not much that we can help you with,**
it is just an issue with missing required _headers / cookies_ which you have to provide to Streamlink.

https://streamlink.github.io/cli.html#cmdoption-http-cookie
https://streamlink.github.io/cli.html#cmdoption-http-header
