### ISSUE TITLE
Getting Proxy Error 

### ISSUE THREAD

**Issue by kishan167** [streamlink/streamlink#2730]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Iam getting (Failed to parse: http://Username:Password@in35.nordvpn.com:80/)

I tired 
--http-proxy "http://Username:Password@in35.nordvpn.com:80/" --https-proxy "socks5://Username:Password@in35.nordvpn.com:80"

My Username is Email ID so i have @ Sign and Password has # sign

>Streamlink --http-proxy "http://Username:Password@in35.nordvpn.com:80/" --http-cookie "exp=1575794321~acl=/*~data=hdntl~hmac=91f509c416956c81d084246c250e59d481ac62e6bc1c03e30d697e861cb5af3e" --http-header "Referer=https://www.hotstar.com/in/movies/comali/1260011507/watch" --http-header "Origin=https://www.hotstar.com" "https://hses1.akamaized.net/videos/movies/tamil/comali/1260011507/1574166016954/9121969f18793908463be004eb916cce/master-phone.m3u8?ladder=phone&hdnea=st=1575767293~exp=1575770893~acl=/*~hmac=6fb9b3acfbb5c25fb5ce9e2cd3c2b3f211d5af62dd1e8ab84f21996fbdb6afa0"
[cli][info] Found matching plugin hls for URL https://hses1.akamaized.net/videos/movies/tamil/comali/1260011507/1574166016954/9121969f18793908463be004eb916cce/master-phone.m3u8?ladder=phone&hdnea=st=1575767293~exp=1575770893~acl=/*~hmac=6fb9b3acfbb5c25fb5ce9e2cd3c2b3f211d5af62dd1e8ab84f21996fbdb6afa0
error: Unable to open URL: https://hses1.akamaized.net/videos/movies/tamil/comali/1260011507/1574166016954/9121969f18793908463be004eb916cce/master-phone.m3u8?ladder=phone&hdnea=st=1575767293~exp=1575770893~acl=/*~hmac=6fb9b3acfbb5c25fb5ce9e2cd3c2b3f211d5af62dd1e8ab84f21996fbdb6afa0 (Failed to parse: http://Username:Password@in35.nordvpn.com:80/)
### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
use `%40` for the `@` in your username

see https://github.com/streamlink/streamlink/issues/2662#issuecomment-541879972

and `%23` for the `#` if it makes issues.

---

just `--http-proxy "socks5://..."` without `--https-proxy` should also work

**Comment by kishan167** [comment]
Thank you soo much it worked jst one more question before i close this iam getting slow Speed on the Download anyways to make it faster or do multi threaded and is not the proxy i have attached pic of the Speed test below

Please View the  Streamlink Download ScreenShot http://prntscr.com/q7sayo

Please View the Speed Test of the Proxy http://prntscr.com/q7sbpi

**Comment by back-to** [comment]
> slow Speed on the Download

there is only `--hls-segment-threads 5`

https://streamlink.github.io/latest/cli.html#cmdoption-hls-segment-threads
https://github.com/streamlink/streamlink/issues/553#issuecomment-278730337
