### ISSUE TITLE
Funimation: "Pipe copy aborted" error when using the "best" stream

### ISSUE THREAD

**Issue by thanhtoan1196** [streamlink/streamlink#2731]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Funimation: "Pipe copy aborted" error when using the "best" stream

### Reproduction steps / Explicit stream URLs to test

If I use "worst" then it is okay
If I use "best", it will fail

```
streamlink --config ./streamlinkrc https://www.funimation.com/shows/samurai-champloo/tempestuous-temperaments/\?qid\= -o 1.mp4
```

streamlinkrc
```
http-cookie=incap_ses_163_998813=1w/1DEJjmTGerECeiRlDAsCm7V0AAAAAWe/qE7+HdOKsx+Q4xNFqdQ==
default-stream=best
player-passthrough=http,hls,rtmp
funimation-mux-subtitles
ffmpeg-audio-transcode=aac
funimation-email=email1xx@mail.com
funimation-password=mypasswordxx
```

### Log output

```
streamlink --config ./streamlinkrc https://www.funimation.com/shows/samurai-champloo/tempestuous-temperaments/\?qid\= -o 1.mp4
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/samurai-champloo/tempestuous-temperaments/?qid=
[plugin.funimationnow][info] Logged in to Funimation as toan@yopmail.com
[cli][info] Available streams: 234p_alt2 (worst), 234p_alt, 234p, 270p_alt2, 270p_alt, 270p, 360p_alt2, 360p_alt, 360p, 480p, 540p_alt2, 540p_alt, 540p, 720p_alt2, 720p_alt, 720p, 810p_alt2, 810p_alt, 810p, 1080p_alt2, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
File 1.mp4 already exists! Overwrite it? [y/N] y
[download][1.mp4] Written 213.8 MB (1m43s @ 1.4 MB/s)
[stream.ffmpegmux][error] Pipe copy aborted: /var/folders/w8/6t_xwpjx2x12q2w_8rtgvlv40000gn/T/ffmpeg-4756-164
```

**Comment by Zerocrick** [comment]
Same issue

**Comment by back-to** [comment]
> Log output

use `--loglevel debug`

---

is FFmpeg installed?

https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

**Comment by scottbernstein** [comment]
I'm just now seeing this error myself, and indeed have ffmpeg installed (it took 20+ minutes for the error to appear)

[download][.., CA 2020-05-23-redo.ts] Written 1.96 GB (1m48s @ 20.9 MB/s)                                              [stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\ffmpeg-9584-118
[stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\ffmpeg-9584-197

**Comment by beta2k** [comment]
was this ever resolved? got the same issue. still need to give it another try with --loglevel debug
