### ISSUE TITLE
Abematv live does not work

### ISSUE THREAD

**Issue by LoveCany** [streamlink/streamlink#2734]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

I have used streamlink with VLC player to play abematv live, but it shows that current device cannot play the contents. I have confirmed that the VOD can perform normally, but the live cannot.

After that, I tried to download the stream directly, and it is the same.

### Reproduction steps / Explicit stream URLs to test

1. ... I have tried with this channel:https://abema.tv/now-on-air/abema-anime-2
2. ... use with this command on both Windows and Ubuntu: streamlink https://abema.tv/now-on-air/abema-anime-2 best

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/19379111/70553853-4e9f7d00-1bbf-11ea-80e8-cc8d32de9713.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> Log output

use Streamlink with `--loglevel debug`

---

also it works for me with a _Japanese IP_

**Comment by LoveCany** [comment]
It is weird that it can work normally now, but I haven't changed anything of my PC and Ubuntu server. I will test later at the same time of the day when the problem first appears_(I think maybe abematv limit the usage at different time of the day)_ and post the log soon.

**Comment by LoveCany** [comment]
The problem appeared at this time...

And here is the log:

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.4
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin abematv for URL https://abema.tv/now-on-air/abema-anime-2
[plugin.abematv][debug] URL=https://ds-linear-abematv.akamaized.net/channel/abema-anime-2/playlist.m3u8
[utils.l10n][debug] Language code: zh_CN
[cli][info] Available streams: 180p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1104227; Last Sequence: 1104230
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1104228; End Sequence: None
[stream.hls][debug] Adding segment 1104228 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1104229 to queue
[stream.hls][debug] Adding segment 1104230 to queue
[stream.hls][debug] Download of segment 1104228 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format https://abema.tv/now-on-air/abema-anime-2 -
[stream.hls][debug] Download of segment 1104229 complete
[stream.hls][debug] Download of segment 1104230 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104231 to queue
[stream.hls][debug] Download of segment 1104231 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104232 to queue
[stream.hls][debug] Download of segment 1104232 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104233 to queue
[stream.hls][debug] Download of segment 1104233 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104234 to queue
[stream.hls][debug] Download of segment 1104234 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104235 to queue
[stream.hls][debug] Download of segment 1104235 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104236 to queue
[stream.hls][debug] Download of segment 1104236 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104237 to queue
[stream.hls][debug] Download of segment 1104237 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104238 to queue
[stream.hls][debug] Adding segment 1104239 to queue
[stream.hls][debug] Download of segment 1104238 complete
[stream.hls][debug] Download of segment 1104239 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104240 to queue
[stream.hls][debug] Download of segment 1104240 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104241 to queue
[stream.hls][debug] Download of segment 1104241 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104242 to queue
[stream.hls][debug] Download of segment 1104242 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104243 to queue
[stream.hls][debug] Download of segment 1104243 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104244 to queue
[stream.hls][debug] Download of segment 1104244 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104245 to queue
[stream.hls][debug] Download of segment 1104245 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104246 to queue
[stream.hls][debug] Download of segment 1104246 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1104247 to queue
[stream.hls][debug] Download of segment 1104247 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
By the way, I have tried to flush my router and got a new IP _(Japanese IP)_ , and the problem still exists. It seems like the problem is associated with time, but the browser player can normally run all the time.

**Comment by back-to** [comment]
>  but it shows that current device cannot play the contents.

1. is this the full translation of the error screen?

> The problem appeared at this time...

2. is it time based or based on the movie which is played ?

> but the browser player can normally run all the time.

3. does your browser use DRM for the movie or does it work without?

---

a bit difficult to debug as it is geoblocked

**Comment by LoveCany** [comment]
> is this the full translation of the error screen?
It is the full translation.
> is it time based or based on the movie which is played ?
I tried at the same time on other channels, and they all cannot be played. I think is is time-based.
> does your browser use DRM for the movie or does it work without?
I am using Chrome, and it uses Widevine from the document of abematv, but the code of streamlink(in my view) does not use anything from Widevine.

Besides, I tried different IP address using VPNGate and the problem showed again. 
Does Abematv limit non-DRM devices usage at midnight? I am not sure.

**Comment by back-to** [comment]
it is just some kind of blocking from their side,
with just a vpn it is impossible to debug.

There is nothing that we can do about it, as you need someone from Japan.

**Comment by Provissy** [comment]
I encountered the same problem too, after researching, I figured out that this is AbemaTV's DRM. 

Abema has several streaming schemes depending on different contents. Some of them (like Anime) are strongly DRMed, which use a different encrypting method and the built-in python script plugin will not be able to handle it.
