### ISSUE TITLE
[Plugin Request] sliver.tv

### ISSUE THREAD

**Issue by Goustoulos** [streamlink/streamlink#2743]
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

sliver.tv is an esports live streaming platform, similar to twitch. It does *not* have VOD support. It's only HLS livestreaming.

### Example stream URLs

1. https://www.sliver.tv/perfectbalance
2. https://www.sliver.tv/risingflame
3. https://www.sliver.tv/oxyroth

### Additional comments, screenshots, etc.
I'm not entirely sure what this means, but sliver.tv is on blockchain.
I do realize that the information i provided might not be enough, but i do not know info like "who runs it" etc.

**Comment by bastimeyer** [comment]
> SLIVER.tv is the next generation Esports entertainment platform on blockchain which features 24/7 live streaming content from top games like Fortnite, League of Legends, CSGO, and more. Viewers can watch top Twitch streamers like NICKMERCS, Method, and FaZe on SLIVER to further interact with the stream and earn Theta tokens, open themed crates, and win a wide variety of gaming gear.
> 
> Based in San Jose, CA the company is backed by top-tier Silicon Valley VCs and Hollywood media investors and is on a mission to transform the interactive Esports entertainment industry.

Looks like another gaming live streaming site without any actual viewers to me (that also mines crypto currency in the background).
https://www.sliver.tv/browse
I don't think it's worth implementing it.
