### ISSUE TITLE
question about use of 'value' in many of your validate functions

### ISSUE THREAD

**Issue by boulderob** [streamlink/streamlink#2744]
fyi: this needs to tagged with label question but i don't have write access to this repo:

i'm diving your code base to learn how to potentially write a plugin.  i'm using an existing plugin for 'ard' as a model.  in this ard plugin reference is made to what appears like an instance method of `stream_` called `endswith`

https://github.com/streamlink/streamlink/blob/25308b628e4c327f234deea936339ff8aa83c214/src/streamlink/plugins/ard_mediathek.py#L103

however when i look at the definition of `endswith` in validate.py, it appears to just be a "plain old function".

https://github.com/streamlink/streamlink/blob/25308b628e4c327f234deea936339ff8aa83c214/src/streamlink/plugin/api/validate.py#L132

```
def endswith(string):
    """Checks if the string value ends with another string."""
    def ends_with(value):
        validate(text, value)
        if not value.endswith(string):
            raise ValueError("'{0}' does not end with '{1}'".format(value, string))
        return True

    return ends_with
```

it's a wrapper around a function of basically the same name with the two "keywords" "ends" and "with" being separated by an "underscore".  

in this particular case, the call to the parent function `endswith` provides the `string` argument variable of ".f4m".   **but how / where does the argument variable of `value` get passed / set for the child function `ends_with` since it's not passed to the parent function `endswith`?**.  `value` obviously becomes the object instance from which `ends_with` method is called so it's almost as if `value` is somehow referring to the `_stream` instance but if that's the case i don't know how that's actually working.   if `value` is a global var somewhere why use a global and where is it set?  

also, `endswith` basically returns a function reference back to `ends_with` that appears to "stand in" for the original `_stream.endswith` method that originally called it????   it's like recursion with obfuscation on an instance which kind of has an instance method that kind of isnt' an instance method that is being overriden / polymorphed but not really ;)

i'm having trouble with

- `_stream.endswith` appears to be an object instance of `_stream` which is calling a method `endswith` that is not defined on the `_stream` object as far as i can tell but simply as a vanilla function in validate.py.  **how does a 'plain old function' some how get 'attached' and work as a method of `_stream` and why do it this way?**  

-  once the `endswith` returns `end_with` it has no args passed to it including `value` as described above, so how does this do anything that effects the original `_stream` instance?

**mind you that i know the goal of the code is to simply check the extension of the different streams.  that's easy.  what i don't know is HOW this is being implemented here in terms of the python and oops?**

anyway, it seems like there is a lot of "circular motion" going on here and some of it lacking context to me.   i'm not an oops guru so i'm obviously missing somethimg but so far i've generally been able to figure out most things oops when inspecting other people's code.

if you don't have the time to get too into details, can someone point me to what oops keywords and phrases i should search for online or perhaps a good link(s) with a how / why context of a similar example that might help me understand the implemention here?

many similar validate functions follow the same pattern described above so it's key to understanding what and how they are doing what they are doing in streamlink.  

super thanks

**Comment by boulderob** [comment]
ok to clarify these look like typical closures.  but i still don't understand how this works because 

- the returned function `ends_with` never actually gets called (so what good is it?)
- the returned function is still never supplied a `value` arg from what i can tell???
- the _stream appears to be a json dictionary vs a class instance so i'm not sure how the `endswith` or `ends_with` can be used as an instance method here? 

any thoughts welcome

**Comment by back-to** [comment]
you are on a completely wrong way

here is the `endswith`
https://docs.python.org/3.7/library/stdtypes.html?highlight=endswith#str.endswith

**Comment by beardypig** [comment]
@back-to is correct, `stream_` is a `string`.

To use the `validate.endswith` function you'd do it similar to the documentation in `validate`. You can verify it works quite easily in a Python REPL. To see more about how it works you can look in to the `validate` function.

```python
>>> from streamlink.plugin.api.validate import *
>>> validate({"item": endswith(".f4m")}, {"item": "stream"})
   ValueError: Unable to validate key 'item': 'stream' does not end with '.f4m'
```

**Comment by boulderob** [comment]
ahhh! :)  thx to you both.

so these two `endswith` methods are two completely different things - one comes with the std library as a string method and the other one is related to streamlink validate, yes?  which means 
this line

```
if stream_.endswith(".f4m"): 
```

has nothing to do with the validate method.  stream_ is just a string and `endswith` is the stock string method and there's no connection between the two! yes?

so to explain.  i was using the new code nav features of github.  when i hovered over `stream_.endswith` it gave me the local streamlink definition for `endswith`.  i didn't even know there was a std library method by the same name.  hence i went down the rabbit hole here.

i'll play around with validate as you suggest to confirm i understand what it's doing.  thx!

**Comment by bastimeyer** [comment]
> one comes with the std library as a string method and the other one is related to streamlink validate, yes?
> stream_ is just a string and endswith is the stock string method and there's no connection between the two! yes?

yes

Methods from the streamlink.plugin.api.validate module are meant for validating data structures like JSON or XML data in a validation schema that's attached to a HTTPS request for example.

> i was using the new code nav features of github

Github only does static code analysis, not semantic analysis (or just very basic one). This means that it only tries to match method names and stuff for the most part, which doesn't necessarily make sense.

**Comment by boulderob** [comment]
thx @bastimeyer for the followup.   i'm clear on this now and hopefully i'll never make the same mistake with the github codenav tool in the future again
