### ISSUE TITLE
Streams are broken

### ISSUE THREAD

**Issue by armsdealer** [streamlink/streamlink#2749]
Hello streamlink guys,

How could I play these ones in streamlink?

https://www.bbc.co.uk/sounds/play/live:bbc_radio_one
https://www.538.nl/radio-luisterenplayer

Any help would be appreciated

```
Name            : streamlink
Version         : 1.2.0-2.0
Description     : CLI program that launches streams from various streaming services in a custom video player
                  (livestreamer fork)
Architecture    : any
URL             : https://streamlink.github.io/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python-pycryptodome  python-isodate  python-pycountry  python-requests  python-pysocks
                  python-websocket-client  rtmpdump
Optional Deps   : ffmpeg: Required to play streams that are made up of separate audio and video streams, eg. YouTube
                  1080p+ [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 2.90 MiB
Packager        : Andreas Baumann <mail@andreasbaumann.cc>
Build Date      : X
Install Date    : X
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

```
streamlink -p vlc --default-stream best http://bbcradio1.radio.net
[cli][info] Found matching plugin radionet for URL http://bbcradio1.radio.net
[cli][info] Available streams: 128k (worst, best)
[cli][info] Opening stream: 128k (http)
[cli][info] Starting player: vlc
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

```
streamlink -p vlc --default-stream best http://radio538.radio.net
[cli][info] Found matching plugin radionet for URL http://radio538.radio.net
[cli][info] Available streams: 128k (worst), 133k (best)
[cli][info] Opening stream: 133k (http)
[cli][error] Try 1/1: Could not open stream <HTTPStream('https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538AAC.aac?dist=radionet')> (Could not open stream: Unable to open URL: https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538AAC.aac?dist=radionet (HTTPSConnectionPool(host='playerservices.streamtheworld.com', port=443): Max retries exceeded with url: /api/livestream-redirect/RADIO538AAC.aac?dist=radionet (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))))
error: Could not open stream <HTTPStream('https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538AAC.aac?dist=radionet')>, tried 1 times, exiting
```

streamlink-git giving the same errors too

```
Name            : streamlink-git
Version         : 1.3.0.r17.g25308b62-1
Description     : CLI program that launches streams from various streaming services in a custom video player (livestreamer fork)
Architecture    : any
URL             : https://streamlink.github.io/
Licenses        : BSD
Groups          : None
Provides        : streamlink
Depends On      : python-pycryptodome  python-iso3166  python-iso639  python-isodate  python-pysocks  python-requests  python-websocket-client  rtmpdump
Optional Deps   : ffmpeg: Required to play streams that are made up of separate audio and video streams, eg. YouTube 1080p+ [installed]
Required By     : None
Optional For    : None
Conflicts With  : streamlink
Replaces        : None
Installed Size  : 2.97 MiB
Packager        : Unknown Packager
Build Date      : X
Install Date    : X
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by bastimeyer** [comment]
The radio.net plugin is working fine.

```
$ streamlink -l debug 'https://radio538.radio.net' best
[cli][debug] OS:         Linux-5.5.0-rc1-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0+19.gad276c4
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin radionet for URL https://radio538.radio.net
[cli][info] Available streams: 128k (worst), 133k (best)
[cli][info] Opening stream: 133k (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --title https://radio538.radio.net --no-cache -
[cli][debug] Writing stream to output
^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

```
$ streamlink -l debug 'https://bbcradio1.radio.net' best
[cli][debug] OS:         Linux-5.5.0-rc1-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0+19.gad276c4
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin radionet for URL https://bbcradio1.radio.net
[cli][info] Available streams: 128k (worst, best)
[cli][info] Opening stream: 128k (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --title https://bbcradio1.radio.net --no-cache -
[cli][debug] Writing stream to output
^C[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...
```

----

As you can see from your error message

> Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))

you're having issues with your system's TLS certificates.

> Build Date      : X
> Install Date    : X

Not sure if this "X" is a feature of pacman or if you've removed the date from the package info output, but it could be an indicator that your system time is not properly set up and that the certificates are invalid because of that.

**Comment by armsdealer** [comment]
> The radio.net plugin is working fine.
> 
> ```
> $ streamlink -l debug 'https://radio538.radio.net' best
> [cli][debug] OS:         Linux-5.5.0-rc1-1-git-x86_64-with-glibc2.2.5
> [cli][debug] Python:     3.8.0
> [cli][debug] Streamlink: 1.3.0+19.gad276c4
> [cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
> [cli][info] Found matching plugin radionet for URL https://radio538.radio.net
> [cli][info] Available streams: 128k (worst), 133k (best)
> [cli][info] Opening stream: 133k (http)
> [cli][debug] Pre-buffering 8192 bytes
> [cli][info] Starting player: mpv
> [cli.output][debug] Opening subprocess: mpv --title https://radio538.radio.net --no-cache -
> [cli][debug] Writing stream to output
> ^C[cli][info] Stream ended
> Interrupted! Exiting...
> [cli][info] Closing currently open stream...
> ```
> 
> ```
> $ streamlink -l debug 'https://bbcradio1.radio.net' best
> [cli][debug] OS:         Linux-5.5.0-rc1-1-git-x86_64-with-glibc2.2.5
> [cli][debug] Python:     3.8.0
> [cli][debug] Streamlink: 1.3.0+19.gad276c4
> [cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
> [cli][info] Found matching plugin radionet for URL https://bbcradio1.radio.net
> [cli][info] Available streams: 128k (worst, best)
> [cli][info] Opening stream: 128k (http)
> [cli][debug] Pre-buffering 8192 bytes
> [cli][info] Starting player: mpv
> [cli.output][debug] Opening subprocess: mpv --title https://bbcradio1.radio.net --no-cache -
> [cli][debug] Writing stream to output
> ^C[cli][info] Stream ended
> Interrupted! Exiting...
> [cli][info] Closing currently open stream...
> ```
> 
> As you can see from your error message
> 
> > Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))
> 
> you're having issues with your system's TLS certificates.
> 
> > Build Date      : X
> > Install Date    : X
> 
> Not sure if this "X" is a feature of pacman or if you've removed the date from the package info output, but it could be an indicator that your system time is not properly set up and that the certificates are invalid because of that.

Thank you for your reply man

It isn't a feature of pacman. I've put an X.

```
Build Date      : Thu 19 Dec 2019 12:11:46 AM
Install Date    : Thu 19 Dec 2019 12:13:19 AM
```

It's weird I can play this one but bbc 1/538

```
streamlink -p vlc --default-stream best http://radioxlondon.radio.net
[cli][info] Found matching plugin radionet for URL http://radioxlondon.radio.net
[cli][info] Available streams: 47k (worst), 128k (best)
[cli][info] Opening stream: 128k (http)
[cli][info] Starting player: vlc
```

What could possibly go wrong?

**Comment by back-to** [comment]
> It's weird I can play this one but bbc 1/538

radio.net does not host the stream, they **just redirect you to the radio stream**

you will see it, if you use the command `--stream-url` 

https://streamlink.github.io/latest/cli.html#cmdoption-stream-url

```
$ streamlink -l debug 'https://radio538.radio.net' best --stream-url
https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3?dist=radionet
```


can you open this link in your browser?

```
https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3?dist=radionet
```

---

> Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))

you can try `--http-no-ssl-verify`

https://streamlink.github.io/latest/cli.html#cmdoption-http-no-ssl-verify

---

could you run streamlink with `-l debug`

**Comment by armsdealer** [comment]
> > It's weird I can play this one but bbc 1/538
> 
> radio.net does not host the stream, they **just redirect you to the radio stream**
> 
> you will see it, if you use the command `--stream-url`
> 
> https://streamlink.github.io/latest/cli.html#cmdoption-stream-url
> 
> ```
> $ streamlink -l debug 'https://radio538.radio.net' best --stream-url
> https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3?dist=radionet
> ```
> 
> can you open this link in your browser?
> 
> ```
> https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3?dist=radionet
> ```
> 
> > Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')))
> 
> you can try `--http-no-ssl-verify`
> 
> https://streamlink.github.io/latest/cli.html#cmdoption-http-no-ssl-verify
> 
> could you run streamlink with `-l debug`

Sorry for the late reply man

I appreciate you taking the time to comment. Thank you very much man

`--http-no-ssl-verify` did the trick

It's weird but now I can play both:

```
streamlink -p vlc --default-stream best http://bbcradio1.radio.net --http-no-ssl-verify
[cli][info] Found matching plugin radionet for URL http://bbcradio1.radio.net
[cli][info] Available streams: 128k (worst, best)
[cli][info] Opening stream: 128k (http)
[cli][info] Starting player: vlc
```

```
streamlink -p vlc --default-stream best http://radio538.radio.net --http-no-ssl-verify
[cli][info] Found matching plugin radionet for URL http://radio538.radio.net
[cli][info] Available streams: 97k (worst), 128k (best)
[cli][info] Opening stream: 128k (http)
[cli][info] Starting player: vlc
```

Happy Merry Christmas in advance

Cheers
