### ISSUE TITLE
Could not find python script.

### ISSUE THREAD

**Issue by k3lt** [streamlink/streamlink#275]
Error from the title happens every time i try to play any stream, i redownloaded and reinstalled streamlink (x64 installer)
I tried with python 2.7.x and 3.5.x (installed with PATH), none worked, i cannot find the script manually either.. basically it's pain the ass. Windows 10 x64.
Any ideas?

**Comment by TrollOutOfControl** [comment]
exactly the same problem

**Comment by beardypig** [comment]
@k3lt which installer did you use, can you post the link? You can try the [nightly installer](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe).

**Comment by k3lt** [comment]
@beardypig https://github.com/streamlink/streamlink-twitch-gui/releases/download/v1.0.0/streamlink-twitch-gui-v1.0.0-win64-installer.exe

**Comment by beardypig** [comment]
@k3lt that's for the twitch front-end, I have not used it before. Did you install Streamlink as well, using the installer from here: [streamlink/streamlink/releases/tag/0.1.0](https://github.com/streamlink/streamlink/releases/tag/0.1.0)?

**Comment by k3lt** [comment]
That's third Streamlink i'm going to install.. fine then.. is this python the correct one atleast? python-3.5.2-amd64

**Comment by beardypig** [comment]
Streamlink comes bundled with Python so you should not need a separate installation of Python (it won't interfere either). 

Which other Streamlinks have you installed?

**Comment by k3lt** [comment]
Right now i have installed https://github.com/streamlink/streamlink/releases/tag/0.1.0
And i cannot even run it.
Launching Streamlink.launch says Requested Python version 3.5-32 is not installed.

**Comment by beardypig** [comment]
Streamlink is a command line application, once it's installed you can run it via the command prompt (cmd). See the [documentation](https://streamlink.github.io/cli.html). 

If you want to use the Twitch front-end, then you need to configure that to use Streamlink. You can read the documentation for the front-end here: [streamlink/streamlink-twitch-gui/wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki).

**Comment by k3lt** [comment]
Ok disregard this question, actually i didn't realize Streamlink and Streamlink-Twitch-Gui are 2 different things..

**Comment by beardypig** [comment]
No problem, glad you sorted it out.
