### ISSUE TITLE
Youtube plugin not working with some vods

### ISSUE THREAD

**Issue by Maqken** [streamlink/streamlink#2750]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

On some vods i get no playable streams found and cant seem to identify why.

### Reproduction steps / Explicit stream URLs to test

1. Try to load streamlink https://www.youtube.com/watch?v=FmDUUGOTFCM

### Log output

```
streamlink https://www.youtube.com/watch?v=jXg93FFZXWk -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=jXg93FFZXWk
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: jXg93FFZXWk
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 251 = 1080p
Available streams: audio_mp4, audio_webm, 360p (worst), 720p, 1080p (best)

streamlink https://www.youtube.com/watch?v=FmDUUGOTFCM -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=FmDUUGOTFCM
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: FmDUUGOTFCM
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=FmDUUGOTFCM
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Infernion** [comment]
I've faced with similar issue with following link: https://www.youtube.com/watch?v=UhkgggX_-QE&feature=youtu.be

**Comment by phytoporg** [comment]
+1, repro here as well using 1.3.0+19.gad276c4 and video link https://www.youtube.com/watch?v=fCZsk0E-Y5A

Had a chance to poke around at this today. Completely new to the code base and domain so forgive me if this is not a useful observation. I dumped `parse_qsl(res.text)` just following https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L326 and found that the video info response text for each problematic link provided so far has no `fmt_list` or `url_encoded_fmt_stream_map` entries, so the plugin's `_get_streams()` call returns an empty dict.

These same videos all download properly in youtube-dl 2020.01.01 FWIW.

**Comment by franticflux** [comment]
Its getting worse.

E:\tmp2\London>streamlink -l debug https://www.youtube.com/watch?v=c6RpWivuEoY 480p
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=c6RpWivuEoY
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: c6RpWivuEoY
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=c6RpWivuEoY

**Comment by biet1234** [comment]
Having the same issue on Manjaro(linux)

$ streamlink https://www.youtube.com/watch?v=RG4IXfTMGSM best -l debug
[cli][debug] OS:         Linux-5.4.6-2-MANJARO-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.1
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=RG4IXfTMGSM
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: RG4IXfTMGSM
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=RG4IXfTMGSM

**Comment by bartvastgoed** [comment]
Same for Raspian :
```streamlink -l debug 'https://www.youtube.com/watch?v=oSmUI3m2kLk' best
[cli][debug] OS:         Linux-4.19.42-v7+-armv7l-with-debian-9.9
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=oSmUI3m2kLk
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: oSmUI3m2kLk
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=oSmUI3m2kLk
```

**Comment by cubimon** [comment]
Doesn't work for me either

**Comment by wickedplayer494** [comment]
Verifying, having similar "No playable streams" difficulties. Originally encountered with a 4K video and chalked it up to Google being weird and splitting video and audio at super-high (>=1440p) qualities, but I've also run into this in run-of-the-mill 720p max videos too that don't have strict Content ID protection that usually spits out the "use youtube-dl instead" fallback message.

**Comment by Phistr90** [comment]
same problem on raspbian (I replaced ID with ABC for privacy reasons):

[cli][debug] OS:         Linux-4.19.93-v7l+-armv7l-with-debian-10.2
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=ABC
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: ABC
[plugin.youtube][debug] get_video_info - 1: Found data
error: No playable streams found on this URL: https://www.youtube.com/watch?v=ABC

**Comment by liamkennedy** [comment]
Getting the same thing here - Raspbian.  Seems any VOD link I try to play fails with "no playable streams" as above.

**Comment by liamkennedy** [comment]
Any word from the Streamlink team  (@back-to) on this issue?  Thanks!

**Comment by gravyboat** [comment]
I don't even know if we're going to consider this an issue as livestreams are fine. It's just VODs that don't work so I don't know if anyone will pick this up since we've been moving further and further from VOD support. I don't have time to look at it currently but if anyone wants to investigate feel free to do so.

**Comment by liamkennedy** [comment]
@gravyboat - I had no idea about the VOD vs Live stream priority - thanks for clarifying that.  

Unfortunately although the live stream part of streamlink has historically been my primary use - I've begun using the VOD capability with Youtube quite extensively.  I can see that may have been a mistake in view of the priorities for this project.  

I'll do my best to dig through the problem and find a solution - but I don't have full faith in my programming capabilities to pull out the solution.  Wish me luck!

**Comment by liamkennedy** [comment]
@Maqken - do you have any luck with any VOD now?  The VOD from your original post that WAS working is not working now either.   

@phytoporg - do you have any (still) working examples of a VOD video link?   

I'm looking for a working VOD so I can compare some additional debug dumps of working vs non-working VOD.  Although I am thinking the issue now is something has changed with the youtube API that is now making this an issue will all VOD's with streamlink.  

Thanks!

**Comment by Maqken** [comment]
@liamkennedy it was too random so i´m not using it for youtube vods anymore, i´m trying out youtube-dl for the time being and it's working fine. It has the downside that i have to teach my homebrew ui to use it instead of streamlink but it's a nice exercise.
You might want to try older vods, my last experience with youtube vods was that newer vods didn't work and older did. but i suppose that if they are spreading the change backwards eventually none will.

**Comment by liamkennedy** [comment]
@Maqken thanks for the response.  I have tried out some 10-year-old videos on my YT Channel - and the problem is happening with those too - so it does look like it's maybe on all VOD's now.  

In my case I have a quite large installed base of users worldwide running as a console application on Raspbian (mostly stretch - but some are still on Jessie) - so there are a few more challenges I have to work out before I could switch to youtube-dl for this.  I may very well have to go that route - although my highest priority would be to keep with streamlink and just work out what the fix it.  

Thanks again

**Comment by gravyboat** [comment]
@liamkennedy Sure no problem. It's mostly just a stance we've had to take against adding new VOD only sites since that kind of defeats the purpose of Streamlink and we were getting a lot of requests for sites that already exist in tools like youtube-dl so I have to make sure to say that it's the main focus so no one comes back to quote this issue going "well you fixed youtube!". All the maintainers have been pretty busy with real life stuff sadly so we've only been hitting more critical issues as of late.

**Comment by seagull** [comment]
Streamlink just doesn't work for any youtube video anymore.

**Comment by mqmq0** [comment]
I just noticed, lot of stuff does not work that connected to youtube. Like playing youtube videos in VLC.
Unless... I did some digging and found this:
https://addons.videolan.org/p/1154080/
or rather this:
https://raw.githubusercontent.com/videolan/vlc/master/share/lua/playlist/youtube.lua

Its fixes the issue for VLC. Maybe there are something in it which helps to fix streamlink aswell.
