### ISSUE TITLE
Argument in CLI to overwrite an existing file.

### ISSUE THREAD

**Issue by Xonshiz** [streamlink/streamlink#2753]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

An option to be passed with the CLI to "overwrite" a file if it already exists. Just like in `ffmpeg`, we can pass `-y` or `-n` in parameters to decide whether to overwrite an existing file or not.
Suppose I'm downloading a file with name "My File.mp4". Now, there already exists a file with the same name in the same directory where I'm trying to download the current file. So, streamlink interrupts me and asks whether it should overwrite a file or not.
This is fine when I'm downloading 1 video, I can type in `Y`, when Streamlink interrupts. But, some times I just put a list of files to be downloaded and go out and when I come back, streamlink waits for me to input.

I couldn't find any argument like this in the documentation or the already opened/closed issues. Hence, I opened a new one. So, if anyone's got anything, let me know.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#cmdoption-f
https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink_cli/main.py#L91
https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink_cli/main.py#L59-L70
