### ISSUE TITLE
Available Streams (worst , best) and live HLS

### ISSUE THREAD

**Issue by Octave1201** [streamlink/streamlink#2756]
Hi everyone! And Happy new year 2020!

I've got a question... When I open a stream, I've got 2 quality available: Worst and Best..

When I select "worst", the stream always starts in HLS?

Is there a way to force VLC to launch in worst instead of the best quality?

Btw, what does HLS stand for?

 Available streams: live (worst, best)
 Opening stream: live (hls)

**Comment by gravyboat** [comment]
[There's a wikipedia article about HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming), it has nothing to do with the quality, and [you can set the default quality via the config file](https://streamlink.github.io/cli.html?highlight=quality#configuration-file).
