### ISSUE TITLE
streamlink --stdout issue

### ISSUE THREAD

**Issue by osscombat** [streamlink/streamlink#2757]
Hi!
Sorry if this is not a real issue, but I see no other help topics. I'm trying to redirect the stream to the stdout on a headless machine, I see no problems with the URL with a Windows desktop with VLC client, but in Linux I get this output, maybe I misundersood some switches?

` streamlink --loglevel debug --stdout --locale ru_RU dash://"http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash.mpd" best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
[cli][debug] Python:     2.7.5
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dash for URL dash://http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash.mpd
[plugin.dash][debug] Parsing MPD URL: http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash.mpd
[utils.l10n][debug] Language code: ru_RU
[stream.dash][debug] Available languages for DASH audio streams: rus (using: rus)
[cli][info] Available streams: 90p+a64k (worst), 90p+a128k, 360p+a64k, 360p+a128k, 720p+a64k, 720p+a128k (best)
[cli][info] Opening stream: 720p+a128k (dash)
[stream.dash][debug] Opening DASH reader for: 2 (video/mp4)
[stream.dash][debug] Opening DASH reader for: 8 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=2)
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-4914-387 -i /tmp/ffmpeg-4914-755 -c:v copy -c:a copy -copyts -start_at_zero -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-4914-387
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=None)
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-4914-755
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash1-12hFrag-hd-4-20191210T120400init.mp4 complete
[stream.dash][error] Failed to open segment http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash1-12hFrag-hd-4-20191210T120400_000411555.mp4: Unable to open URL: http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash1-12hFrag-hd-4-20191210T120400_000411555.mp4 (404 Client Error: Not Found for url: http://edge1.1internet.tv/dash-live11/streams/1tv/1tvdash1-12hFrag-hd-4-20191210T120400_000411555.mp4)
`

**Comment by back-to** [comment]
@osscombat
make sure that your system time is set correctly

**Comment by bastimeyer** [comment]
> 404 Client Error: Not Found for url: ...

That's not a stdout issue.

Another reason could be that your IP is blocked by the stream hoster. The stream URL is working fine on my system.

You're also using Python 2 which is finally officially unsupported since the beginning of this year.

**Comment by osscombat** [comment]
> 
> 
> > 404 Client Error: Not Found for url: ...
> 
> That's not a stdout issue.
> 
> Another reason could be that your IP is blocked by the stream hoster. The stream URL is working fine on my system.
> 
> You're also using Python 2 which is finally officially unsupported since the beginning of this year.

You're right, python3 solved the issue, thanks a lot for the prompt response!
