### ISSUE TITLE
NHK Streams unable to open

### ISSUE THREAD

**Issue by anikun2k10** [streamlink/streamlink#2766]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When launching `streamlink nhk.or.jp/nhkworld` I get the following 404 error:

`[cli][error] Try 1/1: Could not open stream <HLSStream('https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8')> (Could not open stream: Unable to open URL: https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8 (404 Client Error: Not Found for url: https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8))
error: Could not open stream <HLSStream('https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8')>, tried 1 times, exiting`

Do note, that this is with all of the stream resolutions and alt streams.

### Reproduction steps / Explicit stream URLs to test

1. Open Command Prompt (Either Admin or non-Admin, doesn't matter)
2. run the `streamlink nhk.or.jp\nhkworld 720p` command
3. repeat changing the stream resolution among all available

### Log output

```
C:\WINDOWS\system32>streamlink --loglevel debug nhk.or.jp/nhkworld 720p
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin nhkworld for URL nhk.or.jp/nhkworld
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 180p_alt2 (worst), 180p_alt, 180p, 360p_alt2, 360p_alt, 360p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8')> (Could not open stream: Unable to open URL: https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8 (404 Client Error: Not Found for url: https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8))
error: Could not open stream <HLSStream('https://nhkwlive-xjp.akamaized.net/hls/live/2003458/nhkwlive-xjp/index_1180.m3u8')>, tried 1 times, exiting
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> Streamlink: 1.3.0

This was already fixed on Streamlink's master branch in #2733. Please use the latest development version.
https://streamlink.github.io/install.html
