### ISSUE TITLE
[Piczel] API changed?

### ISSUE THREAD

**Issue by panhartstuff** [streamlink/streamlink#2767]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Downloading livestreams from Piczel is no longer possible. It seems that they have changed the API.

### Reproduction steps / Explicit stream URLs to test

1. Attempt to download any active or inactive livestreams
2. Receive error
Example:
`streamlink --loglevel debug https://piczel.tv/watch/AllyKuma`

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.1
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin piczel for URL https://piczel.tv/watch/AllyKuma
error: Unable to open URL: https://piczel.tv:3000/streams/AllyKuma?&page=1&sfw=false&live_only=true (HTTPSConnectionPool(host='piczel.t
v', port=3000): Max retries exceeded with url: /streams/AllyKuma?&page=1&sfw=false&live_only=true (Caused by SSLError(SSLError(1, '[SSL
: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))))
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by panhartstuff** [comment]
I fixed it by changing the STREAMS_URL and HLS_URL to the following:
```
STREAMS_URL = "https://piczel.tv/api/streams/{0}?&page=1&sfw=false&live_only=true"
HLS_URL = "https://piczel.tv/hls/{0}.m3u8"
```
I don't know how to do a proper pull request, so I'll leave that to someone else

**Comment by panhartstuff** [comment]
Actually I was wrong.
The HLS URL is valid, but `parse_variant_playlist` can't seem to parse it correctly so streamlink doesn't return any of the HLS options.
Looking into the [HLS file](https://github.com/panhartstuff/dump/blob/master/1654.m3u8), it doesn't seem to contain any information about the stream names, so I don't really know how this works.
Can anyone help me out?

**Comment by bastimeyer** [comment]
> Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)'))

Looks like a TLS misconfiguration on their end. The plugin is trying to access the API endpoint via HTTPS, but only plain text HTTP seems to be properly supported by the server.

**Comment by panhartstuff** [comment]
Nah, I've contacted the admin and the API simply changed to the ones I mentioned above. They're correct and have nothing to do with HTTPS.

But the problem is streamlink isn't returning any of the HSL options, only the RTMP ones.

The `parse_variant_playlist` function is simply not parsing the m3u8 correctly for some reason.

`streams.update(HLSStream.parse_variant_playlist(self.session, HLS_URL.format(stream["id"])))`

There must be something wrong with this line, but I don't know what.

**Comment by mkbloke** [comment]
I have a fix for this (see below).

HLS streaming works on various URLs that I've tested.

I have not been able to establish a working RTMP URL, so I have removed support for it.

If anybody would like to test it, you can get the code from:

https://github.com/mkbloke/streamlink/blob/piczel-site-change-2020-03/src/streamlink/plugins/piczel.py

You can download the whole plugin by clicking on "Raw", then saving via your browser.
