### ISSUE TITLE
Discord live streaming

### ISSUE THREAD

**Issue by qome** [streamlink/streamlink#2768]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Discord introduced live streaming direct from the desktop app a while back. It would be nice to be able to send these streams to a player of your choice.

### Example stream URLs

It is not possible to post a URL for a Discord stream as it is in-app only at this time, which is the whole point of this plugin request.

### Additional comments, screenshots, etc.

None.

**Comment by qome** [comment]
I believe Discord is using web sockets which makes this impossible but I'm not sure.

**Comment by back-to** [comment]
> It is not possible to post a URL for a Discord stream as it is in-app only at this time

Streamlink needs an URL

> The Go Live feature gives you an easy way to stream in a server voice channel for up to 10 of your friends. 

https://support.discordapp.com/hc/en-us/articles/360030714312-Go-Live-FAQ

only 10 viewer max

---

**Not worth it.**

**Comment by qome** [comment]
Just FYI, that was while it was in beta. It is now up to 100.

**Comment by gravyboat** [comment]
@qome Even 100 is still ridiculously low and not worth it.

**Comment by Erk-** [comment]
@gravyboat People who do not have a larger audience, for example classes or similar.

----

@qome Discord does use websockets and I believe that the information needed is sent over it. A specialized userbot would likely work better than incorporating it into streamlink. (Note that it is a breach if the Discord ToS though)

**Comment by Emzi0767** [comment]
WebSockets are only a control channel though, the actual data is transmitted over WebRTC protocol, which itself runs over UDP. Ignoring violations of terms of service for a moment, you just cannot generate a link for this.
