### ISSUE TITLE
filmon plugin 504 Server Error: Gateway Time-out

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#2775]
## Bug Report

filmon plugin, 504 Server Error: Gateway Time-out

### Description

Here is filmon plugin bug for streamlink's team attention
in case somebody would be willing to fix the plugin.

Error is intermittent and occurs about once in every half an hour.
To replicate this error would require watching the stream for up to 30 minutes
and player would freeze at some point in time.
Player must be killed as a process, otherwise it hangs on desktop.
It happens with vlc, mpv and ffplay.

### Reproduction steps / Explicit stream URLs to test

https://www.filmon.tv/channel/bbc-world-news

```
$url = 'https://www.filmon.tv/channel/bbc-world-news'
run('streamlink.exe --http-no-ssl-verify --player=ffplay.exe ' & $url & '  best','',@SW_MINIMIZE)
```

### Log output

```
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay.exe
Exception in thread Thread-FilmOnHLSStreamWorker:
Traceback (most recent call last):
  File "C:\P\STREAMLINK\pkgs\streamlink\plugin\api\http_session.py", line 166, in request
    res.raise_for_status()
  File "C:\P\STREAMLINK\pkgs\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\P\STREAMLINK\pkgs\streamlink\stream\segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "C:\P\STREAMLINK\pkgs\streamlink\stream\hls.py", line 280, in iter_segments
    self.reload_playlist()
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 24, in reload_playlist
    parsed = urlparse(self.stream.url)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 104, in url
    for stream in self._get_stream_data():
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 91, in _get_stream_data
    data = self.api.channel(self.channel)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 152, in channel
    res = self.session.http.get(self.channel_url.format(channel))
  File "C:\P\STREAMLINK\pkgs\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugin\api\http_session.py", line 175, in request
    raise err
streamlink.exceptions.PluginError: Unable to open URL: http://www.filmon.com/api-v2/channel/3268?protocol=hls (504 Server Error: Gateway Time-out for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls)
```

### Comment

streamlink-1.3.0-20200118.exe
windows 10

**Comment by bastimeyer** [comment]
> 504 Server Error: Gateway Time-out

`5xx` HTTP responses are server errors (as the message already tells you), so the plugin isn't necessarily broken and the streaming service needs to fix their stuff. All that Streamlink can do is implement a workaround, if possible.

> Error is intermittent and occurs about once in every half an hour.

You're seeing this error because Streamlink's [`HLSStreamWriter.fetch`](https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink/stream/hls.py#L100-L118) method which is responsible for downloading the HLS segments [doesn't define a list for those error codes to be ignored](https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink/plugin/api/http_session.py#L165-L166). This means that by default, server errors will cause the stream to end because the raised exception from the requests lib will not get caught.

The FilmOn plugin has already [implemented an override](https://github.com/streamlink/streamlink/blob/1.3.0/src/streamlink/plugins/filmon.py#L33-L47) for some request errors, but only when reloading the HLS playlist. In order to "fix the plugin" and ignore these random server side issues as a whole, the `fetch` method needs to be changed with custom logic as well, similar to the `reload_playlist` method. However, a better solution would probably be an improvement of the `HTTPSession` class, so that the `acceptable_status` and `retries` (etc) parameters can be configured globally. Then the individual HLSStreamWriter methods don't need to be monkeypatched.

**Comment by johnthecracker** [comment]
I can't close the player by clicking on close button.
I have to kill the process to close the player.
ffplay hangs for about 30 seconds before it closes.
It is the same case in linux and windows.

I tried running ffplay with -autoexit switch and it didn't make any difference.

```
$url = 'https://www.filmon.tv/channel/bbc-world-news'
run('streamlink.exe --http-no-ssl-verify --player="ffplay.exe -autoexit " ' & $url & '  best','',@SW_MINIMIZE)
```

Is there any switch in streamlink to terminate the player if it hangs after the stream ends ?
If yes, I can start a new instance of streamlink after player's PID terminates.
It is not a perfect solution but it is better than having player hanging on desktop for 30 seconds
which will not close when cliked on it's close button.

**Comment by johnthecracker** [comment]
quote:


--player-no-close

    By default Streamlink will close the player when the stream ends. This is to avoid "dead" GUI players lingering after a stream ends.

    It does however have the side-effect of sometimes closing a player before it has played back all of its cached data.

    This option will instead let the player decide when to exit.

**Comment by johnthecracker** [comment]
how about switch --player-force-close ?

**Comment by mkbloke** [comment]
I see the same problem with FilmOn, but did not report it because it's a server side issue, as mentioned above.  I wondered about mitigation, but ultimately thought that even with something in place, allowing for server-side time-outs and then making another request, it will still likely mean a fair gap in the viewable stream, I would have thought...

**Comment by johnthecracker** [comment]
As of now gap is 30 seconds.
If player closed traight, I would restart streamlink with a loop and gap would be the time 
it takes the stream to start.
If you know how to check if the stream still exists you may kill the player's PID and restart
streamlink and minimize the gap.
Not ideal solution, but better than the gap of 30 seconds.

**Comment by johnthecracker** [comment]
I looked at streamlink's PID as well to see if streamlink terminates earlier than the player (ffplay).
No, they hang together for 30 seconds before they close together.

How to test if streamlink hangs apart from lookig at the player?

Had I known that, I could kill streamlink and player and restart them with minimal waste of time.

**Comment by mkbloke** [comment]
It's really way beyond the scope of things that should appear on this issue tracker, but a possible suggestion would be to monitor the bytes coming from streamlink via a stdin/stdout shim.  I don't know how you'd accomplish it on Windows, but on Linux you could send the stream to stdout using the -O option to streamlink, via dd and then on to the stdin of the player.  Having launched that and backgrounded it, you would then have a loop periodically checking the dd stats via kill -USR1 <pid of dd> and parsing the output to see if the 'records in' value has increased each time.  If not, you would kill streamlink and exec the whole script that does this again.  I don't know how well this would work in reality.  It is a kludge and there may be some edge cases you'd have to work through to get it to work as intended...

**Comment by johnthecracker** [comment]
I don't see why it's way beyond the scope. Streamlink hangs and player hangs, and plugin hangs,
and I look for relevant working solution just on a lower level than these developers.

Right now I am puzzled why last script I posted here ends at it's start ???

--http-timeout 1 worked for me in other situations:

https://github.com/back-to/generic/issues/5#issue-427469627

Could it be something to do with https vs http ?

So long for now.

**Comment by bastimeyer** [comment]
This player issue has nothing to do with the plugin.

As already said, it's caused by an unexpected exception that doesn't get caught and thus ends Streamlink's process, which means that Streamlink won't be able to terminate/kill the player child process.

This thread is about the plugin and not about any other Streamlink issues, so please stop posting about that. However, if you want to have a workaround, just launch the player yourself and pipe Streamlink's stdout into the player's stdin. Then you won't have any issues with left behind child processes.

**Comment by johnthecracker** [comment]
UPDATE:

here is output in Ubuntu, this time error message 502.
Yesterday I could watch the stream in browser, streamlink was returning error 404 with my script.
I could watch the stream directly with VLC.
Today my script works again without any modification and new error 502..

```
#!/bin/bash
#set -x #echo on
url="https://www.filmon.tv/channel/bbc-world-news"
streamlink --http-no-ssl-verify --player=ffplay $url best
```

``
j@j:~/LINUX/news$ ./bbcworld.sh
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay
Exception in thread Thread-FilmOnHLSStreamWorker:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 166, in request
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/streamlink/stream/segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "/usr/lib/python3/dist-packages/streamlink/stream/hls.py", line 280, in iter_segments
    self.reload_playlist()
  File "/usr/lib/python3/dist-packages/streamlink/plugins/filmon.py", line 24, in reload_playlist
    parsed = urlparse(self.stream.url)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/filmon.py", line 104, in url
    for stream in self._get_stream_data():
  File "/usr/lib/python3/dist-packages/streamlink/plugins/filmon.py", line 91, in _get_stream_data
    data = self.api.channel(self.channel)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/filmon.py", line 152, in channel
    res = self.session.http.get(self.channel_url.format(channel))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/streamlink/plugin/api/http_session.py", line 175, in request
    raise err
streamlink.exceptions.PluginError: Unable to open URL: http://www.filmon.com/api-v2/channel/3268?protocol=hls (502 Server Error: Bad Gateway for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls)

error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
j@j:~/LINUX/news$ 
```


Here is log from windows, looks a little different maybe because my ubuntu streamlink is a bit older than windows one.


```
$url = 'https://www.filmon.tv/channel/bbc-world-news'
run('cmd.exe /c streamlink.exe --http-no-ssl-verify --player=ffplay.exe ' & $url & ' best & pause','',@SW_MINIMIZE)
```

```
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay.exe
Exception in thread Thread-FilmOnHLSStreamWorker:
Traceback (most recent call last):
  File "C:\P\STREAMLINK\pkgs\streamlink\plugin\api\http_session.py", line 166, in request
    res.raise_for_status()
  File "C:\P\STREAMLINK\pkgs\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\P\STREAMLINK\pkgs\streamlink\stream\segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "C:\P\STREAMLINK\pkgs\streamlink\stream\hls.py", line 280, in iter_segments
    self.reload_playlist()
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 24, in reload_playlist
    parsed = urlparse(self.stream.url)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 104, in url
    for stream in self._get_stream_data():
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 91, in _get_stream_data
    data = self.api.channel(self.channel)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 152, in channel
    res = self.session.http.get(self.channel_url.format(channel))
  File "C:\P\STREAMLINK\pkgs\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugin\api\http_session.py", line 175, in request
    raise err
streamlink.exceptions.PluginError: Unable to open URL: http://www.filmon.com/api-v2/channel/3268?protocol=hls (502 Server Error: Bad Gateway for url: http://www.filmon.com/api-v2/channel/3268?protocol=hls)
```

**Comment by mkbloke** [comment]
My logs show that FilmOn can emit 502, 503 and 504 errors for the same request URL, which in my case is: http://www.filmon.com/api-v2/channel/65?protocol=hls

**Comment by johnthecracker** [comment]
and 404..

**Comment by johnthecracker** [comment]
Here is the latest update about filmon plugin:

doesn't work, for who knows what reason:

```
$url = "https://www.filmon.tv/channel/bbc-world-news"
run('cmd.exe /c streamlink.exe --http-no-ssl-verify --player=ffplay.exe ' & $url & '  best & pause','',@SW_MINIMIZE)
```

```
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/channel/bbc-world-news
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\P\STREAMLINK\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\P\STREAMLINK\pkgs\streamlink_cli\main.py", line 1038, in main
    handle_url()
  File "C:\P\STREAMLINK\pkgs\streamlink_cli\main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "C:\P\STREAMLINK\pkgs\streamlink_cli\main.py", line 458, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugin\plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 245, in _get_streams
    data = self.api.channel(_id)
  File "C:\P\STREAMLINK\pkgs\streamlink\plugins\filmon.py", line 161, in channel
    return self.session.http.json(res, schema=self.api_schema)
UnboundLocalError: local variable 'res' referenced before assignment
```

Now, read this:

https://www.filmon.com/channel/bbc-world-news broadcast hangs in firefox and chromium, 
works in internet explorer without sound, works properly with seamonkey.
The only instance of this broadcast working on my PC is with seamonkey browser.
This is in London, UK.

I can watch the stream directly with VLC.

https://www.filmon.com/api-v2/channel/bbc-world-news?protocol=hls

```
{"code":200,"message":"OK","data":{"id":3268,"title":"BBC World News","alias":"bbc-world-news","description":null,"group":"NEWS TV","group_id":1,"group_alias":"news-tv","type":"standard","is_free":false,"is_free_sd_mode":false,"is_adult":false,"is_interactive":false,"is_vod":false,"is_vox":false,"is360":false,"watch_free_time":90,"is_local":false,"seekable":false,"user_subscribed":false,"streams":[{"is_free":false,"name":"3268.low.stream/playlist.m3u8","quality":"low","url":"https://edge-1183-ch-gv.filmon.com/live/3268.low.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbea51cbc96ddfe5b9ed3f8fe3286df6a738d3dbd4ae152ee38d8f229f3f0be5596a3bf31399ab08b0420d7569db2bd58a06f8ac0863eab669e035e8be4142d80084519a9b6782be719154ba4f079d4ceebb2f8e70b7ebdf21c93860281983f5573bcfc812d1340a316917bc370171105bd22c5e9cb6f488312516e9f07aa486fca99b54fb4281f38dc5cc","watch-timeout":90},{"is_free":false,"name":"3268.high.stream/playlist.m3u8","quality":"high","url":"https://edge-1183-ch-gv.filmon.com/live/3268.high.stream/playlist.m3u8?id=035bca1a71b11fce016d28acd3dbea51cbc96ddfe5b9ed3f8fe3286df6a738d3dbd4ae152ee38d8f229f3f0be5596a3bf31399ab08b0420d7569db2bd58a06f8ac0863eab669e035e8be4142d80084519a9b6782be719154ba4f079d4ceebb2f8e70b7ebdf21c93877529b37a6e76044f46b41405a6fcee8ad23b658807d6e80e5ffc10987cf68369febfe2f51405aa3fd1ed3f1d346020d","watch-timeout":90}],"server_time":1581369665,"jwplatform_media_id":"auSBboze","is_favorite":false}}
```

**Comment by mkbloke** [comment]
It would appear that /channel/ no longer works within streamlink right now.  Try /tv/ instead, that works for me, i.e.:
```
streamlink filmon.tv/tv/bbc-world-news <quality>
streamlink filmon.com/tv/bbc-world-news <quality>
```

Both URLs are working in-browser correctly for me, however:
```
filmon.tv/channel/bbc-world-news
filmon.com/channel/bbc-world-news
```

So I think that must be another problem entirely.

**Comment by johnthecracker** [comment]
Thanks mkbloke,

all urls you posted work with streamlink so it isn't streamlink's bug.
With my browsers all remains the same with filmon, whatever filmon url.
 

```
[cli][info] Found matching plugin filmon for URL filmon.tv/tv/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: mpv.exe
```
```
[cli][info] Found matching plugin filmon for URL filmon.com/tv/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: mpv.exe
```
```
[cli][info] Found matching plugin filmon for URL filmon.tv/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: mpv.exe
```
```
[cli][info] Found matching plugin filmon for URL filmon.com/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: mpv.exe
```

This appears to be working today and it didn't yesterday:

```
$url = "https://www.filmon.tv/channel/bbc-world-news"
run('cmd.exe /c streamlink.exe --http-no-ssl-verify --player=ffplay.exe ' & $url & '  best & pause','',@SW_MINIMIZE)

```

```
[cli][info] Found matching plugin filmon for URL https://www.filmon.tv/channel/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay.exe
```

**Comment by mkbloke** [comment]
Interesting, /channel/ wasn't working for me just before posting my previous message, but it is now.
