### ISSUE TITLE
Support {title}, {author} and other metadata in file name.

### ISSUE THREAD

**Issue by GrayFace** [streamlink/streamlink#2777]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Weirdly, metadata variables are supported only for rarely used "--title" parameter. They would be very useful for output parameter.

### Expected / Actual behavior

Proposal:
- Add a new parameter, say "-ox", that would act like "-o", but with variables support.
- Expose {title}, {author}, {category} etc. to it.
- Also, at some point in the future having upload data/time as a variable(s) would be very useful. I suspect there was no incentive for adding them, because there's not much need for them in "--title" parameter.

**Comment by GrayFace** [comment]
Duplicate of what???

**Comment by back-to** [comment]
@GrayFace 

https://github.com/streamlink/streamlink/issues/791 and 5 other issues
