### ISSUE TITLE
New release to fix mpv 0.32.0

### ISSUE THREAD

**Issue by geeseven** [streamlink/streamlink#2778]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
The folks over at mpv, just released [0.32.0][0].  This new release breaks the current release of Streamlink, 1.3.0.  The issue was reported in #2764 and fixed in #2765.  Arch already has updated mpv packages in their repositories (how I discovered this issue).  Any chance we could get a new release?  While I had no problems applying the fix manually, some users might not. 

Thanks for a great project. 

[0]: https://github.com/mpv-player/mpv/releases/tag/v0.32.0

**Comment by gravyboat** [comment]
@geeseven We have a new release ready to go in https://github.com/streamlink/streamlink/pull/2772, we were hoping some other fixes would get in prior to doing that but I'll try to remember to review things later this week and if there's no new PRs for fixes I'll just merge it and start the release process.

**Comment by geeseven** [comment]
@gravyboat, thanks for the timely reply.  I look forward to the new release.

**Comment by bastimeyer** [comment]
> Arch already has updated mpv packages in their repositories (how I discovered this issue)

The maintainer of Arch's streamlink package has applied the MPV patch and bumped the pkgrel, so you should be fine by using the regular packages:
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/streamlink&id=f018f65f71c4ee79614ecd8dcafb273da0d698ac

We should publish a patch release though. We can't expect every package distributor to apply patches like this and users of different platform to be using dev builds.
