### ISSUE TITLE
Need support for creating a plugin, here: www.latina.pe

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#2782]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements. See also #https://github.com/streamlink/streamlink/issues/2493

### Description
Latina (formerly Frecuencia Latina) is a Peruvian television network

### Example stream URLs
http://www.latina.pe/tvenvivo

### Additional comments, screenshots, etc.
I am trying to write a plugin for the site mentioned above, latina.pe. 
In my layman's understanding the address of the stream url is generated by the server and embedded in the sites source. At least with the developer tools of a browser you can easily search for "`manifest.m3u8`" and you will find something like: 
`http://live-normal-internacional-hls.latina.pe/egress/bhandler/cialatina/live/manifest.m3u8?nva=1588004680&ttl=432000&ip=5.62.58.163&hash=0e0b786c0ba8669cc29cd`

**Problem:** The site is geo-blocked. To avoid this I am using 'Hidemyass' which gives me an peruvian ip like e.g. 5.62.58.162. All websites which show your actual ip confirm this adress as well as for example 'curl ipinfo.io'. I am also able to play a live stream from a browser like Chrome or Firefox, in this case the stream url contains the correct ip as shown in the url above. 

But every time I am using my plugin I get a completely different ip, hence the stream url is rejected. 
(**EDIT**: even when I don't use a VPN, a different ip than the real one is returned by the plugin. So it seems to be a plugin-issue, not just a pure geo restriction)

I tried using a referer/user-agent, in this case Chrome, but this doesn't help. 
Could it be some cookie? And how would I handle this within the plugin? 
Or anything else? 

You may find my attempt at: [https://textuploader.com/16kpy](https://textuploader.com/16kpy)

**Comment by back-to** [comment]
> The site is geo-blocked.

actually the biggest problem.

---

might be a VPN/Proxy misconfiguration issue, if you get different IPs.

the plugin should _work_

---

> But every time I am using my plugin I get a completely different ip

with VPN or without?

**Comment by malvinas2** [comment]
> > But every time I am using my plugin I get a completely different ip
> 
> with VPN or without?

In both cases, that's the problem.... 

**Without VPN**

Original ip: 77.22.103.xyz (Germany)

Output plugin: 79.10.73.103        (stream not working)

Output Chrome: 77.22.103.xyz    (stream working and exceptionally I catched a non-blocked program, showing Daddy Yankee :-)  )

**Comment by back-to** [comment]
@malvinas2 
if you open the website twice, it will work

add `self.session.http.get(self.url)`

```py
    def _get_streams(self):
        self.session.http.headers.update({"User-Agent": useragents.CHROME})
        self.session.http.get(self.url)
```

**Comment by malvinas2** [comment]
Yes,that work's! 

Sixty-four-thousand-dollar question: How did you figure this out?

**Comment by back-to** [comment]
@malvinas2 

> How did you figure this out?

**compared network traffic** of Streamlink vs Firefox and got a bit lucky there.

**Comment by malvinas2** [comment]
And how do you analyze the network traffic caused by Streamlink? Using a debugger or wireshark or ... ? 
I will prepare a pr for the new plugin.

**Comment by malvinas2** [comment]
Can be considered as semi-broken: 
The plugin itself is working, but several days ago latina.pe obviously started to blacklist ip-addresses of vpn service provider. E.g. ExpressVPN or HMA are not working any more.
