### ISSUE TITLE
I need help on saving livestreams automatically

### ISSUE THREAD

**Issue by kwbr1** [streamlink/streamlink#2786]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

First of all sorry for my English level :)

So, I'm currently using the following command to keep a broadcaster on "watch mode" and start downloading the livestream when they go live:
`streamlink https://www.website.tv/username best --retry-max 99999999 -o filename.ts, --output filename.ts`

The problem is that I can only capture a single live per broadcaster at time. If the person starts a livestream, ends it and then starts a new livestream minutes later, Streamlink will only capture the first one.

I would like to know if is there command which after the livestream ends Streamlink will automatically start searching again for a new live from the same person.
Every new livestream has a different .m3u8 url so I can't use a command to keep trying to reconnect to the old livestream source :( I have to get the new one.

There's a list of codes but I couldn't find a way to make any of them work: https://streamlink.github.io/cli.html

Thanks in advance.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by yeahjack** [comment]
I think the easiest way is to use python and write a main.py which contains:
while True:
    streamlink https://www.website.tv/username best --retry-max 99999999 -o filename.ts, --output filename.ts
    time.sleep(1)

**Comment by kwbr1** [comment]
It is not a duplicate as I couldn't find any other topic with the same issue.
There is none on how to automatically capture different transmissions from the same person (with different .m3u8s), there's only a few on how to reconnect to the same source after a after an unexpected end.

**Comment by kwbr1** [comment]
> I think the easiest way is to use python and write a main.py which contains:
> while True:
> streamlink https://www.website.tv/username best --retry-max 99999999 -o filename.ts, --output filename.ts
> time.sleep(1)

Thanks for the idea but unfortunately I don't know how to do that :(

**Comment by yeahjack** [comment]
You mean the m3u8 link changes when the person starts the stream for the next time?

**Comment by kwbr1** [comment]
> You mean the m3u8 link changes when the person starts the stream for the next time?

Exactly, every new stream has a different id.
There is a command which after the stream ends makes Streamlink keep trying to reconnect to the same .m3u8, but this does not work for me as I need to get the new source.

**Comment by yeahjack** [comment]
How do you get the first m3u8? By visiting some websites and grab it?

**Comment by kwbr1** [comment]
> How do you get the first m3u8? By visiting some websites and grab it?

I'm not 100% sure I understand what you mean (sorry) but I don't need to get the .m3u8 link manually, when I use the command `streamlink https://www.website.tv/username best --retry-max 99999999 -o filename.ts, --output filename.ts`  the app starts downloading the stream automatically.

I know that every new stream has a different .m3u8 url because I used Inspect elements.

Example:
1st stream source: http://199.91.72.220:7782/list_3455734135_2437722899_0.m3u8
Then the person ends the stream and starts a new one: http://128.1.80.101:7778/list_3455741183_2363253981_0.m3u8

**Comment by yeahjack** [comment]
Oh sorry I made a mistake. But since you donnot need the m3u8, just use a loop so that the streamlink process can be run all the time. I wonder whether it is ok, and I use ffmpeg to record m3u8 the same way to get videos when losing Internet connections.
