### ISSUE TITLE
Problem changing Twitch stream volume through VLC

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink#2787]
## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.

### Description

When changing the volume of a Twitch stream in VLC, I can't do the normal scroll with the mouse wheel and have a big change. Even if I scroll several times, the volume may still only change by 5% in either direction. However, things work normally when watching a Youtube video in VLC, or a Twitch stream in MPC.

### Expected / Actual behavior

I try to change the volume, but it barely does. When it does, the change itself is delayed. Note, the sound is not delayed, only the change in volume.

### Reproduction steps / Explicit stream URLs to test

1. Launch stream, twitch.tv/shivfps. I normally use Twitch GUI, but I tried _streamlink twitch.tv/shivfps best_ too.
2. Once the stream is loaded, start scrolling the mouse wheel.
3. Where VLC normally can change the volume from 50% to 90% in one scroll, for me it only does 5%. If I keep scrolling, it can go to 55%, maybe 60%. The easiest way to change the volume by a lot is to click in the VLC GUI. Same issue with up/down arrow keys.

### Log output

C:\Users\User>streamlink twitch.tv/shivfps best --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.0
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/shivfps
[plugin.twitch][debug] Getting live HLS streams for shivfps
[utils.l10n][debug] Language code: sv_SE
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 900p60 (best)
[cli][info] Opening stream: 900p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 7099; Last Sequence: 7105
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 7103; End Sequence: None
[stream.hls][debug] Adding segment 7103 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 7104 to queue
[stream.hls][debug] Adding segment 7105 to queue
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[stream.hls][debug] Download of segment 7103 complete
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format twitch.tv/shivfps -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 7104 complete
[stream.hls][debug] Download of segment 7105 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7106 to queue
[stream.hls][debug] Download of segment 7106 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7107 to queue
[stream.hls][debug] Download of segment 7107 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7108 to queue
[stream.hls][debug] Adding segment 7109 to queue
[stream.hls][debug] Download of segment 7108 complete
[stream.hls][debug] Download of segment 7109 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7110 to queue
[stream.hls][debug] Adding segment 7111 to queue
[stream.hls][debug] Download of segment 7110 complete
[stream.hls][debug] Download of segment 7111 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7112 to queue
[stream.hls][debug] Download of segment 7112 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7113 to queue
[stream.hls][debug] Download of segment 7113 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7114 to queue
[stream.hls][debug] Adding segment 7115 to queue
[stream.hls][debug] Download of segment 7114 complete
[stream.hls][debug] Download of segment 7115 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7116 to queue
[stream.hls][debug] Download of segment 7116 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7117 to queue
[stream.hls][debug] Adding segment 7118 to queue
[stream.hls][debug] Download of segment 7117 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7118 complete
[stream.hls][debug] Adding segment 7119 to queue
[stream.hls][debug] Adding segment 7120 to queue
[stream.hls][debug] Download of segment 7119 complete
[stream.hls][debug] Download of segment 7120 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7121 to queue
[stream.hls][debug] Download of segment 7121 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7122 to queue
[stream.hls][debug] Adding segment 7123 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7122 complete
[stream.hls][debug] Adding segment 7124 to queue
[stream.hls][debug] Download of segment 7123 complete
[stream.hls][debug] Download of segment 7124 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7125 to queue
[stream.hls][debug] Adding segment 7126 to queue
[stream.hls][debug] Download of segment 7125 complete
[stream.hls][debug] Download of segment 7126 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7127 to queue
[stream.hls][debug] Download of segment 7127 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7128 to queue
[stream.hls][debug] Adding segment 7129 to queue
[stream.hls][debug] Download of segment 7128 complete
[stream.hls][debug] Download of segment 7129 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7130 to queue
[stream.hls][debug] Adding segment 7131 to queue
[stream.hls][debug] Download of segment 7130 complete
[stream.hls][debug] Download of segment 7131 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7132 to queue
[stream.hls][debug] Download of segment 7132 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7133 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7133 complete
[stream.hls][debug] Adding segment 7134 to queue
[stream.hls][debug] Adding segment 7135 to queue
[stream.hls][debug] Download of segment 7134 complete
[stream.hls][debug] Download of segment 7135 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7136 to queue
[stream.hls][debug] Adding segment 7137 to queue
[stream.hls][debug] Download of segment 7136 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7138 to queue
[stream.hls][debug] Adding segment 7139 to queue
[stream.hls][debug] Download of segment 7137 complete
[stream.hls][debug] Download of segment 7138 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7139 complete
[stream.hls][debug] Adding segment 7140 to queue
[stream.hls][debug] Download of segment 7140 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7141 to queue
[stream.hls][debug] Adding segment 7142 to queue
[stream.hls][debug] Download of segment 7141 complete
[stream.hls][debug] Download of segment 7142 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7143 to queue
[stream.hls][debug] Download of segment 7143 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7144 to queue
[stream.hls][debug] Adding segment 7145 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7144 complete
[stream.hls][debug] Adding segment 7146 to queue
[stream.hls][debug] Adding segment 7147 to queue
[stream.hls][debug] Download of segment 7145 complete
[stream.hls][debug] Download of segment 7146 complete
[stream.hls][debug] Download of segment 7147 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7148 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7149 to queue
[stream.hls][debug] Adding segment 7150 to queue
[stream.hls][debug] Download of segment 7148 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7151 to queue
[stream.hls][debug] Adding segment 7152 to queue
[stream.hls][debug] Download of segment 7149 complete
[stream.hls][debug] Download of segment 7150 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7153 to queue
[stream.hls][debug] Adding segment 7154 to queue
[stream.hls][debug] Download of segment 7151 complete
[stream.hls][debug] Download of segment 7152 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7153 complete
[stream.hls][debug] Adding segment 7155 to queue
[stream.hls][debug] Adding segment 7156 to queue
[stream.hls][debug] Download of segment 7154 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7157 to queue
[stream.hls][debug] Download of segment 7155 complete
[stream.hls][debug] Download of segment 7156 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7158 to queue
[stream.hls][debug] Adding segment 7159 to queue
[stream.hls][debug] Download of segment 7157 complete
[stream.hls][debug] Download of segment 7158 complete
[stream.hls][debug] Download of segment 7159 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7160 to queue
[stream.hls][debug] Download of segment 7160 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7161 to queue
[stream.hls][debug] Adding segment 7162 to queue
[stream.hls][debug] Download of segment 7161 complete
[stream.hls][debug] Download of segment 7162 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7163 to queue
[stream.hls][debug] Download of segment 7163 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7164 to queue
[stream.hls][debug] Adding segment 7165 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 7164 complete
[stream.hls][debug] Adding segment 7166 to queue
[stream.hls][debug] Adding segment 7167 to queue
[stream.hls][debug] Download of segment 7165 complete
[stream.hls][debug] Download of segment 7166 complete
[stream.hls][debug] Download of segment 7167 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7168 to queue
[stream.hls][debug] Adding segment 7169 to queue
[stream.hls][debug] Download of segment 7168 complete
[stream.hls][debug] Download of segment 7169 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7170 to queue
[stream.hls][debug] Download of segment 7170 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7171 to queue
[stream.hls][debug] Adding segment 7172 to queue

### Additional comments, screenshots, etc.

Here's a comparison of what changing the volume looks like with Streamlink/Twitch and Youtube in VLC. 'key' 0xf00000 = mouse wheel.

**Streamlink/Twitch:**

main debug: VoutDisplayEvent 'mouse button' 0 t=8
main debug: VoutDisplayEvent 'mouse button' 0 t=9
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.274625, muting disabled
mmdevice debug: simple volume changed: 0.274625, muting disabled
main debug: auto hiding mouse cursor
main debug: VoutDisplayEvent 'mouse button' 0 t=8
main debug: VoutDisplayEvent 'mouse button' 0 t=9
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.216000, muting disabled
mmdevice debug: simple volume changed: 0.216000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.166375, muting disabled
mmdevice debug: simple volume changed: 0.166375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.125000, muting disabled
mmdevice debug: simple volume changed: 0.125000, muting disabled
main debug: auto hiding mouse cursor
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.091125, muting disabled
mmdevice debug: simple volume changed: 0.091125, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.064000, muting disabled
mmdevice debug: simple volume changed: 0.064000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.042875, muting disabled
mmdevice debug: simple volume changed: 0.042875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.027000, muting disabled
mmdevice debug: simple volume changed: 0.027000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.015625, muting disabled
mmdevice debug: simple volume changed: 0.015625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf00000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.008000, muting disabled
mmdevice debug: simple volume changed: 0.008000, muting disabled
main debug: auto hiding mouse cursor

**Youtube:**

main debug: VoutDisplayEvent 'mouse button' 0 t=8
main debug: VoutDisplayEvent 'mouse button' 0 t=9
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.274625, muting disabled
mmdevice debug: simple volume changed: 0.274625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.343000, muting disabled
mmdevice debug: simple volume changed: 0.343000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.274625, muting disabled
mmdevice debug: simple volume changed: 0.274625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.343000, muting disabled
mmdevice debug: simple volume changed: 0.343000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.421875, muting disabled
mmdevice debug: simple volume changed: 0.421875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.512000, muting disabled
mmdevice debug: simple volume changed: 0.512000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.614125, muting disabled
mmdevice debug: simple volume changed: 0.614125, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.729000, muting disabled
mmdevice debug: simple volume changed: 0.729000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.857375, muting disabled
mmdevice debug: simple volume changed: 0.857375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.857375, muting disabled
mmdevice debug: simple volume changed: 0.857375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.729000, muting disabled
mmdevice debug: simple volume changed: 0.729000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.614125, muting disabled
mmdevice debug: simple volume changed: 0.614125, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.512000, muting disabled
mmdevice debug: simple volume changed: 0.512000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.421875, muting disabled
mmdevice debug: simple volume changed: 0.421875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.343000, muting disabled
mmdevice debug: simple volume changed: 0.343000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.274625, muting disabled
mmdevice debug: simple volume changed: 0.274625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.216000, muting disabled
mmdevice debug: simple volume changed: 0.216000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.166375, muting disabled
mmdevice debug: simple volume changed: 0.166375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.125000, muting disabled
mmdevice debug: simple volume changed: 0.125000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.091125, muting disabled
mmdevice debug: simple volume changed: 0.091125, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.064000, muting disabled
mmdevice debug: simple volume changed: 0.064000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.042875, muting disabled
mmdevice debug: simple volume changed: 0.042875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.027000, muting disabled
mmdevice debug: simple volume changed: 0.027000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf10000
mmdevice debug: simple volume changed: 0.015625, muting disabled
mmdevice debug: simple volume changed: 0.015625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.027000, muting disabled
mmdevice debug: simple volume changed: 0.027000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.042875, muting disabled
mmdevice debug: simple volume changed: 0.042875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.064000, muting disabled
mmdevice debug: simple volume changed: 0.064000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.091125, muting disabled
mmdevice debug: simple volume changed: 0.091125, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.125000, muting disabled
mmdevice debug: simple volume changed: 0.125000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.166375, muting disabled
mmdevice debug: simple volume changed: 0.166375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.216000, muting disabled
mmdevice debug: simple volume changed: 0.216000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.274625, muting disabled
mmdevice debug: simple volume changed: 0.274625, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.343000, muting disabled
mmdevice debug: simple volume changed: 0.343000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.421875, muting disabled
mmdevice debug: simple volume changed: 0.421875, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.512000, muting disabled
mmdevice debug: simple volume changed: 0.512000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.614125, muting disabled
mmdevice debug: simple volume changed: 0.614125, muting disabled
main debug: auto hiding mouse cursor
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.729000, muting disabled
mmdevice debug: simple volume changed: 0.729000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 0.857375, muting disabled
mmdevice debug: simple volume changed: 0.857375, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: VoutDisplayEvent 'key' 0xf00000
mmdevice debug: simple volume changed: 1.000000, muting disabled
mmdevice debug: simple volume changed: 1.000000, muting disabled
main debug: auto hiding mouse cursor

**Comment by back-to** [comment]
vlc issue, not much that we can help you with.

https://trac.videolan.org/vlc/ticket/21436#comment:5
