### ISSUE TITLE
Support for Australian free-to-air television (ABC, SBS, 7, 9, 10, NITV, C31, etc)

### ISSUE THREAD

**Issue by Stuntaneous** [streamlink/streamlink#2789]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

It'd be great to have support for Australian television, i.e.:

1. ABC (and ABC News 24, ABC Comedy/Kids, ABC Me)
2. SBS (and SBS Viceland, SBS World Movies, SBS Food, NITV)
3. 7 (and 7mate, 7food, 7flix, and possibly also Pac-12, Outdoor Channel, Fuel TV)
4. 9 (and 9Gem, 9Go!, 9Life)
5. 10 (and Peach, Bold)
6. ACCTV
7. C31 (Melbourne community station)
8. C44 (Adelaide community station)
9. WTV / C44 (Perth community station. Note: not the same as the Adelaide one) 

The HD channels where possible. Where stations broadcast in many locations, metropolitan areas are preferred, e.g. Sydney, Melbourne, Adelaide, Brisbane, Perth.

### Example stream URLs

1. Not sure how to obtain (https://iview.abc.net.au/show/abc-live-stream/video/IV1512H001S00)
2. https://sbs-live.akamaized.net/hls/live/2002827/channel1/geo/master_2500K.m3u8
3. https://npc.cdn.7livecloud.io/hls/live/SYD1/master.m3u8
4. https://9now-live.akamaized.net/hls/live/708951-b/ch9-syd/master.m3u8
5. https://network10sec-dai-live.akamaized.net/linear/hls/pb/event/dIeXGR9pRFym4BwLSOpBdg/stream/e3ec4786-1c0a-4431-a3be-fe8e7724ff33:SIN/master.m3u8?hdnea=st=1580839816~exp=1580840116~acl=*~hmac=7b8e3e20fd456009fe9e6378435faa05eee84b59b9a7247c3b365bc7b7c5c8a6
6. http://live-mobile.cdn01.net/hls-live/202E1F/default/mobile/stream_14949_1.m3u8
7. https://dcunilive47-lh.akamaihd.net/i/dclive_1@739220/master.m3u8
8. https://bdz47wk-lh.akamaihd.net/i/bdz47wkxwmnlsh_1@54040/master.m3u8
9. https://dcunilive73-lh.akamaihd.net/i/dclive_1@800758/master.m3u8?hdnea=st=1580839685~exp=1580839805~acl=/i/dclive_1@800758*~hmac=1a040d93f19b9aa0fcf21a93d37aad2d25cf5bdea410d9f3e347b46fb2416fb5

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
**there is no point in adding plugins for static m3u8 urls**

---

closing, create one github issue per _website or service_ with a valid website url,
not one big list in one github issue.
