### ISSUE TITLE
MLG.tv plugin doesn't work

### ISSUE THREAD

**Issue by FrancisGuindon** [streamlink/streamlink#2798]
## Plugin Issue

- [X] This is a plugin issue and I have read the contribution guidelines.

### Description

MLG.tv plug-in doesn't work, and I've tried many URLs. I'm only trying OverwatchLeague.

### Reproduction steps / Explicit stream URLs to test
- blob:https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f
- https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f
- https://www.mlg.com/watch/HcznebkEf4Y/featured-overwatch-videos/overwatch-league-2020-opening-day-starts-now
- https://www.mlg.com/watch/HcznebkEf4Y/

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
usage: streamlink [OPTIONS] <URL> [STREAM]

C:\Users\USERNAME>streamlink blob:https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f
error: No plugin can handle URL: blob:https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f

C:\Users\USERNAME>streamlink https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f
error: No plugin can handle URL: https://www.mlg.com/57fe0c76-73c8-41cb-b10c-6d548198e80f

C:\Users\USERNAME>streamlink https://www.mlg.com/watch/HcznebkEf4Y/featured-overwatch-videos/overwatch-league-2020-opening-day-starts-now
error: No plugin can handle URL: https://www.mlg.com/watch/HcznebkEf4Y/featured-overwatch-videos/overwatch-league-2020-opening-day-starts-now

C:\Users\USERNAME>streamlink https://www.mlg.com/watch/HcznebkEf4Y/
error: No plugin can handle URL: https://www.mlg.com/watch/HcznebkEf4Y/
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by FrancisGuindon** [comment]
Would it be because it is "mlg.com" instead of "mlg.tv" now?

**Comment by gravyboat** [comment]
Correct, right now the plugin only supports [`mlg.tv` and `majorleaguegaming.com`](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/mlgtv.py#L22).

**Comment by FrancisGuindon** [comment]
Okay. Just know both those URLs don't exist anymore and redirect to "mlg.com".

**Comment by reisinfawkes** [comment]
> Correct, right now the plugin only supports [`mlg.tv` and `majorleaguegaming.com`](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/mlgtv.py#L22).

Please could you update it to support mlg.com?

My use case is that I need to view the live MLG Overwatch League stream in VLC and record it. YouTube also streams the Overwatch League stream but it's poorer quality.

This would be greatly appreciated. Thanks.

**Comment by gravyboat** [comment]
@reisinfawkes If someone wants to pick it up to fix they will do so. The team is small and our time is limited.

**Comment by reisinfawkes** [comment]
It's a simple fix surely...

**Comment by mkbloke** [comment]
> It's a simple fix surely...

It looks to be a bit more complicated than just adding .com to the URL match...

**Comment by reisinfawkes** [comment]
I will pay $10 to whoever can do it.

And maybe others can also chip in.

**Comment by back-to** [comment]
Livestreams are protected with DRM
