### ISSUE TITLE
Can dash.py plugin produce literal concatenated binary output of server files?

### ISSUE THREAD

**Issue by stinkteeth** [streamlink/streamlink#2799]
The streamlink dash.py plugin does an excellent job of parsing dash mpd manifests.  It can produce segment urls from even the less common mpd manifest formats that youtube-dl chokes on every time.

However, the dash.py plugin for streamlink, for some reason, containerizes (when using the -o option to save to a file) the init and the segments by creating a new container (mkv or mp4) rather that simply concatenating the native dash init with all of the fragments.

Is there some switch that I'm missing that will allow streamlink to produce file output in the form of merely concatenating the init with all of the fragments, rather than making a new container?  Is there no way to save the literal server content of the init and fragments without streamlink making a new container for them?

**Comment by back-to** [comment]
> Is there some switch that I'm missing that will allow streamlink to produce file output in the form of merely concatenating the init with all of the fragments, rather than making a new container? 

No

>  Is there no way to save the literal server content of the init and fragments without streamlink making a new 

No

---

https://github.com/streamlink/streamlink/issues/2184
https://github.com/streamlink/streamlink/issues/2546
