### ISSUE TITLE
Invidious

### ISSUE THREAD

**Issue by fabianski7** [streamlink/streamlink#2807]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

[Invidious](
https://github.com/omarroth/invidious) is opensource front-end to youtube with focus on privacy.

### Example stream URLs

The only difference between the url of a youtube video is the domain.

Youtube: https://www.youtube.com/watch?v=M9BNoNFKCBI
Invidious: https://www.invidio.us/watch?v=M9BNoNFKCBI

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/1.3.1/CONTRIBUTING.md#plugin-requests

> 2. Sites which are hosting stolen content as their main source of content

> 3. Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)

> 6. Sites which are mostly hosting VODs (stolen or legitimate), or require large changes to existing code to watch VODs

Apart from that, there is no benefit in having this plugin, as you're not using a web frontend with Streamlink, and this site/software is simply is a frontend alternative for youtube. Videos are still (obviously) loaded from Youtube.
