### ISSUE TITLE
Request to add plugin for https://rotana.net/

### ISSUE THREAD

**Issue by Link4K** [streamlink/streamlink#2808]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Rotana TV is a free to air TV channel provider. General programming stations include Khalijia (خليجية), LBCSat (al-Fadaʼīyah al Lubnānīyah الفضائية اللبنانية). Rotana film channels include Rotana Cinema KSA and Rotana Cinema Egypt and Rotana Classic (for classic movies)Rotana Afalam, Rotana America, Rotana Afalam+ HD, Rotana HD, M+. Rotana also runs a number of music channels including Rotana Clip, Rotana Music, and an Islamic religious channel Al-Resala. It is run by Rotana Media Group. This plugins allows watching their channels using streamlink.

### Example stream URLs

curl -s https://rotana.net/live-lbc/       | grep -Eo 'https://[^ >]+.m3u8'
curl -s https://rotana.net/live-drama/     | grep -Eo 'https://[^ >]+.m3u8'
curl -s https://rotana.net/live-music/     | grep -Eo 'https://[^ >]+.m3u8'
curl -s https://rotana.net/live/           | grep -Eo 'https://[^ >]+.m3u8'
curl -s https://rotana.net/live-cinema/    | grep -Eo 'https://[^ >]+.m3u8'

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/1.3.1/CONTRIBUTING.md#plugin-requests

> Plugin submissions and requests are a great way to improve Streamlink. Requests should be as detailed as possible and dedicated to only a single streaming service. **Information about the service** as well as explicit URLs for live streams are required, as are **details regarding the website, what it is, who runs it,** how it adds to Streamlink, etc. This allows for easier plugin review and implementation.

**Comment by Link4K** [comment]
Sorry, added
