### ISSUE TITLE
Icecast not working authentication issue.

### ISSUE THREAD

**Issue by bachoo786** [streamlink/streamlink#2810]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

I have installed streamlink on my raspberry pi. When I try to stream a http link which requires authentication, I suppose it uses icecast. Here is my command line on my raspberry pi:

streamlink --http-proxy "http://bachoo786:XXXXXXXXXXXXX@XXX.X.XX.XX:8080/tv4.nsv"

it returns the following with nothing been played:

```
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
I can play the link on VLC but on VLC I have to input my username and password everytime I try to play the link.
```

### Expected / Actual behavior

I expect it to play the stream but it returns nothing.

**Comment by bastimeyer** [comment]
> I expect it to play the stream but it returns nothing.

Which stream? You have not passed a stream URL as parameter. Instead, you have tried to set the `http-proxy` parameter+value (while using an invalid http-proxy value). The output you're seeing is therefore correct.

https://streamlink.github.io/cli.html#tutorial

https://streamlink.github.io/cli.html#cmdoption-http-proxy
https://2.python-requests.org/en/v1.1.0/user/advanced/#proxies

**Comment by bachoo786** [comment]
Hi @bashtech 
Thanks for the reply.

I thought I put the streaming link i.e. streamlink --http-proxy `"http://bachoo786:XXXXXXXXXXXXX@XXX.X.XX.XX:8080/tv4.nsv"`

I am a little noob on this and I am only trying to access a streaming link which requires me to input my username and password. Can you help please? Thanks.

**Comment by mkbloke** [comment]
You should probably be using VLC for this, since none of the streamlink plugins will match that URL.

In VLC, select "Open Network Stream..." from the "Media" menu and enter the URL into the text box within the "Open Media" dialog window.

**Comment by bachoo786** [comment]
I tried vlc but I still get the authorisation box asking me to enter my username and password. I want to run it directly without any interruption.

**Comment by bastimeyer** [comment]
> Can you help please?

https://streamlink.github.io/cli.html#tutorial

It's all documented here.

**Comment by bachoo786** [comment]
@bastimeyer I understand it's all documented in the link you been sending me but none of what is written on that link works for me.

Perhaps I am missing something which you know better? If you do then maybe you could guide me to the command I am meant to be using?

Thanks for helping though :)

**Comment by bastimeyer** [comment]
> but none of what is written on that link works for me.

The documentation explains pretty clearly how Streamlink's CLI works. It just looks like you've been copying a string from the proxy support section of the docs without actually reading the docs.

The syntax, as already explained in your previously posted output message and also on the CLI tutorial, is `streamlink [OPTIONS] <URL> [STREAM]`, while `[...]` being optional and `<...>` a required parameter. Options can be passed in different ways (POSIX style), eg. `-k`, `-k "value"`, `"-kvalue"`, `--key`, `--key "value"`, or `"--key=value"`.

> streamlink --http-proxy "http://bachoo786:XXXXXXXXXXXXX@XXX.X.XX.XX:8080/tv4.nsv"

As you can see, the actual input stream URL is missing from your command. That's because you've tried to set the `--http-proxy` parameter/option, which expects a value as next parameter if you don't use the `--param=value` syntax. Simple as that.

Regarding the input URL you want to watch, we can't help, as you've omitted pretty much everything.

**Comment by bachoo786** [comment]
Thanks for your reply. I have no clue on how to sort this.

**Comment by mkbloke** [comment]
This works for me:
```
streamlink httpstream://http://user:password@host/path/file.ext live
```

**Comment by bachoo786** [comment]
Hey @mkbloke you saved me. Thank you for that command. I can confirm it works for me however it vlc keeps on searching for the streaming. I tried smplayer and it does the same.

Finally I tried mplayer and it works perfectly with it.

I was wondering if I could play the stream in fullscreen? Is that possible?

Thanks

**Comment by mkbloke** [comment]
I would imagine, using the option ```-p 'mplayer -fs'``` to streamlink.

**Comment by bachoo786** [comment]
You mean streamlink --player 'mplayer -fs' httpstream .....

**Comment by mkbloke** [comment]
Yes, that's basically the same thing.

**Comment by bachoo786** [comment]
perfect works for me thanks alot
