### ISSUE TITLE
[Question] How to export Twitch video to M3U file to play on the TV. 

### ISSUE THREAD

**Issue by CyberPoison** [streamlink/streamlink#2812]
Hi, everyone i would like to extract multiple streams twitch and get it like this...

```
#EXTM3U
#EXTINF:-1 tvg-name="|EN| Streamer name"
https://video-weaver.fra05.hls.ttvnw.net/v1/playlist/Cq8D8r6sm
#EXTINF:-1 tvg-name="|EN| Streamer name2"
https://video-weaver.fra05.hls.ttvnw.net/v1/playlist/Cq8D8r6sm
.
.
.
```
there is any way to get the output like this and get static m3u8 links from twtich videos ?
I would like to export it to watch on my tv the Twitch videos unfortunatelly my tv doesn't support Twitch app so this is my only work arround, any idea how i can get this working, without need to upgrade the m3u list again and again ?

I also thought in recording the video and broadcasting it again by streamlink if this is possible
and get a way to have a m3u8 static and able to get the m3u8 from twitch again when the streams comes back after the streams is back alive 

Any Suggestions 
Kind Regards

**Comment by bastimeyer** [comment]
> there is any way to get the output like this

no, you'll have to build custom stuff yourself

> get static m3u8 links from twtich

Twitch.tv m3u8 URLs are not static. They are bound to an access token which has to be aquired from an API endpoint and it also has an expiration time. This means you'll have to always get a new m3u8 link when you want to watch a Twitch.tv stream.

See [`--stream-url`](https://streamlink.github.io/cli.html#cmdoption-stream-url)

----

You could try out @back-to's LiveProxy project, which is essentially a Streamlink wrapper which lets you run Streamlink from other devices on your local network. You can also create your own m3u8 playlists.
https://github.com/back-to/liveproxy
https://liveproxy.github.io/

**Comment by CyberPoison** [comment]
Thanks for the response can you explain me more in details what is liveproxy there is no documentation to how start it, I know that command ```--stream-url``` but it's a temporary url so there is a way to run streamlink to re scrap the link again when the live is back ?
So as far I can see the only way possible is to use streamlink (Scrap my url and get a new url every 20/30 minutes ) - - > live proxy - - > my TV
This is wath I expect to do so any suggestion?
This is possible to do?

Kind regards

**Comment by bastimeyer** [comment]
> there is no documentation to how start it

https://liveproxy.github.io/url.html#url-guide
This here however is the Streamlink issue tracker, so if you have any questions or issues with other projects which are built on top of Streamlink, you'll have to ask there, not here.

> I know that command `--stream-url` but it's a temporary url so there is a way to run streamlink to re scrap the link again when the live is back

You'll have to run Streamlink in a loop then (with a delay on success and/or failure), since the URL resolving is done only once.

> Wish one is more friendly usable?

What you are describing can be solved via LiveProxy easily without the need of writing any custom scripts around Streamlink.

**Comment by back-to** [comment]
there is also `--player-external-http`

https://streamlink.github.io/cli.html#cmdoption-player-external-http
https://streamlink.github.io/cli.html#cmdoption-player-external-http-port

**Comment by dailylama** [comment]
at the moment spatial audio for AirPods is not supported in vlc, only available for Music.app and few others, so I'm trying this:

`streamlink --player /System/Applications/Music.app URL audio_only
[cli][info] Opening stream: audio_only (hls)
[cli][info] Starting player: /System/Applications/Music.app
error: Failed to start player: /System/Applications/Music.app ([Errno 13] Permission denied: '/System/Applications/Music.app')
[cli][info] Closing currently open stream...
`
