### ISSUE TITLE
Dump

### ISSUE THREAD

**Issue by hatabbich** [streamlink/streamlink#2813]
Delete pls, all fine now, thank you for the great app ^^

**Comment by bastimeyer** [comment]
> TEXT LOG OUTPUT IS REQUIRED for a plugin issue!
> Use the `--loglevel debug` parameter  avoid  parameters which suppress log output.
> https://streamlink.github.io/cli.html#cmdoption-l

> livecli

Not Streamlink. Post a proper Streamlink debug log and plugin issue description.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues

**Comment by hatabbich** [comment]
oh, sorry my mistake.
