### ISSUE TITLE
Steam plugin does not work

### ISSUE THREAD

**Issue by zhenyahacker** [streamlink/streamlink#2814]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
### Description
Steam plugin does not work and just crashes.

### Expected / Actual behavior
Expacted: watch stream.
Obtained: steam plugin crash.

### Reproduction steps / Explicit stream URLs to test
My friend in steam stream game privately.
My account email address contains dot in username, and steam password contains special chartacters such as @ and (
OTP is also enabled on my steam account.
I`ve tried to play stream with streamlink using my account, but it did not even request an OTP code, and just crashed.

### Log output
```[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.3.1+42.g7d8106b
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin steam for URL https://steamcommunity.com/broadcast/watch/********/
[cli][debug] Plugin specific arguments:
[cli][debug]  --steam-email=********@gmail.com (email)
[cli][debug]  --steam-password=******** (password)
[plugin.steam][info] Attempting to login to Steam as ********@gmail.com
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1043, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 583, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 463, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\steam.py", line 194, in _get_streams
    if self.login(self.get_option("email"), self.get_option("password")):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\steam.py", line 180, in login
    return self.dologin(email, password)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\steam.py", line 164, in dologin
    raise SteamLoginFailed(resp[u"message"])
streamlink.plugin.steam.SteamLoginFailed: Incorrect account name or password.  Remember that your email address may not match your account name.```

**Comment by bastimeyer** [comment]
> Incorrect account name or password.  Remember that your email address may not match your account name.

The error you're seeing is a response from the Steam API, not Streamlink.

Are you trying to use your Steam "Account name" or its "Contact Email" address? (check the main steam settings menu)

The `--steam-email` parameter requires a Steam account name as value, not a Steam contact email address or Steam community name, etc. Old Steam accounts were named after the email address you were using, but Valve changed this at some point and you could create accounts with any name.

The Steam plugin is working fine when I'm using my account data (with a 2FA code).

**Comment by zhenyahacker** [comment]
I`m trying an email address, not an "account name". That`s why in log output I replaced only part of it and leaved an "@gmail.com" part untouched.

I will try to investigate deeper situation about non-alphanumeric characters.

**Comment by bastimeyer** [comment]
If you're having troubles correctly escaping special characters of your password or account email address, you can also add the parameters and values in a plugin specific config file:
https://streamlink.github.io/cli.html#configuration-file
https://streamlink.github.io/cli.html#plugin-specific-configuration-file
