### ISSUE TITLE
Plugin bilibili how to change stream routes?

### ISSUE THREAD

**Issue by StevenRCE0** [streamlink/streamlink#2816]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

It seems that there’s no support for switching stream routes yet…?

**Comment by gravyboat** [comment]
This issue has nowhere near enough details, what do you mean by routes? Do you mean choosing the actual server that content is downloaded from? If that's what you mean we're not going to do that. It almost always violates ToS and more importantly it may negatively impact these services which we try to avoid to be good internet citizens.

**Comment by StevenRCE0** [comment]
> This issue has nowhere near enough details, what do you mean by routes? Do you mean choosing the actual server that content is downloaded from? If that's what you mean we're not going to do that. It almost always violates ToS and more importantly it may negatively impact these services which we try to avoid to be good internet citizens.

There are alternative routes, and it’s provided in bilibili’s API.

**Comment by back-to** [comment]
@StevenRCE0 

could you test, if this would work for you

sometimes none of the URLs work, but after a retry one would work.

---

changes

https://github.com/back-to/streamlink/commit/2b9b264dda991219debb4538e6713ad656522b66

raw plugin file

https://raw.githubusercontent.com/back-to/streamlink/2b9b264dda991219debb4538e6713ad656522b66/src/streamlink/plugins/bilibili.py

**Comment by StevenRCE0** [comment]
> @StevenRCE0
> 
> could you test, if this would work for you
> 
> sometimes none of the URLs work, but after a retry one would work.
> 
> changes
> 
> [back-to@2b9b264](https://github.com/back-to/streamlink/commit/2b9b264dda991219debb4538e6713ad656522b66)
> 
> raw plugin file
> 
> https://raw.githubusercontent.com/back-to/streamlink/2b9b264dda991219debb4538e6713ad656522b66/src/streamlink/plugins/bilibili.py

Sure, I'll try that, thanks a lot! 
I do not read python, but does it mean to go through those available streams on cut?

**Comment by back-to** [comment]
@StevenRCE0 

it opens the available stream URLs first and checks if they are accessible,
if not they will be removed and not listed as a stream `source`

I always have only one working stream and 3 not accessible.

---

I just want to know if this works for you or if streamlink would lag when it opens them.

**Comment by StevenRCE0** [comment]
It worked fine, but I didn’t notice much of difference since it’s been kept running in a NAS 😂
