### ISSUE TITLE
LookupError: unknown encoding: utf-8

### ISSUE THREAD

**Issue by tsuNammi** [streamlink/streamlink#2817]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

After updating to 1.3.1 something broke. I've messed around a bit, but it seemed like it was looking for Python@3.8, so I installed Python@3.8 with Homebrew (on MacOS).

When I got it to work with Python 3.8, I came onto this error. Log output below.

### Reproduction steps / Explicit stream URLs to test

1. Update to 1.3.1
2. Install Python 3.8
3. Trying streamlink --version

### Log output

```
Python path configuration:
  PYTHONHOME = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
  PYTHONPATH = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/bin'
  program name = '/usr/local/Cellar/streamlink/1.3.1/libexec/bin/python3.8'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/local/Cellar/streamlink/1.3.1/libexec/bin/python3.8'
  sys.base_prefix = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
  sys.base_exec_prefix = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
  sys.executable = '/usr/local/Cellar/streamlink/1.3.1/libexec/bin/python3.8'
  sys.prefix = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
  sys.exec_prefix = '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
  sys.path = [
    '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/bin',
    '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
    '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
    '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: unknown encoding: utf-8

Current thread 0x000000010e9bcdc0 (most recent call first):
<no Python frame>
```

### Additional comments, screenshots, etc.
Anyone having the same issue?
MacOS Python 3.8 system lang ENG

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
seems like an issue with your python 3.8,
if you are only using it for streamlink delete it also delete streamlink and reinstall it

**Comment by tsuNammi** [comment]
It works with Streamlink Twitch GUI after reinstalling both, but I still get this if I run using command line:

```

Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'streamlink==1.3.1' distribution was not found and is required by the application

```

**Comment by back-to** [comment]
> The 'streamlink==1.3.1' distribution was not found and is required by the application

well, there is something not correctly installed or some paths are set incorrectly

**Comment by bastimeyer** [comment]
> * Update to 1.3.1
> * Install Python 3.8

Python 3.8 is a keg-only package dependency of Streamlink's homebrew package, which means that it uses its own environment.

The streamlink homebrew package shouldn't load anything in
```
/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/
```
On a clean system with correctly installed packages, it loads modules from here
```
/usr/local/Cellar/streamlink/1.3.1_1/libexec/lib/python3.8/site-packages/
```

> It works with Streamlink Twitch GUI

The Twitch GUI first looks up the `streamlink` entry script file from the paths set in your system's `$PATH` environment variable and then gets the python executable path from the shebang of that entry script. This is what your command line shell also does when executing `streamlink` without a relative or absolute path.

Make sure that you are not mixing up different python environments or streamlink installations. Or if you're working with multiple environments, better install streamlink via pip in a dedicated virtualenv.
https://streamlink.github.io/install.html#virtual-environment
