### ISSUE TITLE
add option for hls-segment-key "host proxy"

### ISSUE THREAD

**Issue by tarkah** [streamlink/streamlink#2820]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

The `--hls-segment-key-uri` option works great when needing to proxy the key from somewhere else, until the segment key URI changes for the stream.  It'd be great for there to be an option to be able to pass an IP address / hostname to Streamlink, that will get used instead of the host in whatever the source URI is / updates to throughout the stream.

I'd love to help contribute to make this happen, but would just need to be pointed in the right direction on where the HLS segment key is being handled.

### Expected / Actual behavior

Whenever Streamlink goes to download the segment key URI, update the Uri object / string to replace the host with the specified hostname / IP address.

**Comment by back-to** [comment]
basically the same as https://github.com/streamlink/streamlink/issues/2806
