### ISSUE TITLE
Random print "Failed to open segment" message

### ISSUE THREAD

**Issue by james901** [streamlink/streamlink#2824]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

start recording a stream sometimes this message is printed on the console
`Failed to open segment 3512: Unable to open URL: m3u8 url (404 Client Error: Not Found for url: m3u8 url)`

I don't want to know how to avoid it, but the correct way to catch the exception to avoid printing it.
from your guides https://streamlink.github.io/api_guide.html, on "Opening streams to read data", it should throw the exception StreamError but even if I catch it a message is printed anyway

My code
```
streamlink = Streamlink()
try:
    streams = streamlink.streams(m3u8_url)
    stream_url = streams['480p']
    
	fd = stream_url.open()
    out = open(fileName,"wb")
	
	while True:
        file_size = os.path.getsize(fileName)
        if file_size > 5000000:
            break
        data = fd.read(1024)
        if data is None or data == -1 or data == 0:
		break
        else:
	    out.write(data)
        
	fd.close()
        out.flush()
        out.close()

except NoPluginError:
    fd.close()
    out.flush()
    out.close()
except PluginError:
    fd.close()
    out.flush()
    out.close()
            
except StreamError:
    fd.close()
    out.flush()
    out.close()
            
except Exception as e:
	fd.close()
    out.flush()
    out.close()
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> Failed to open segment

> I don't want to know how to avoid it, but the correct way to catch the exception to avoid printing it

It gets caught immediately in the HLSStreamWriter's fetch method and an error message gets logged via the default logging module:
https://github.com/streamlink/streamlink/blob/8ef3c73480f172f1535d549a1a6c85c7da1c0c1f/src/streamlink/stream/hls.py#L120-L122

You could add a logging filter or use a different logging handler and filter there.
