### ISSUE TITLE
Only return the URL, don't download or start anything

### ISSUE THREAD

**Issue by ahmedtds** [streamlink/streamlink#2827]
Hi, this is not a bug report, just a question. I searched docs and such and couldn't find an answer.

My question is, is there an equivalent of youtube-dl's --get-url option on streamlink?

`-g, --get-url  - Simulate, quiet but print URL`

If I want to use streamlink only to extract HLS url, how can I achieve that?

Currently, I'm ussing `--player-passthrough` option and look what url was passed to the video player but this is not a good solution.

Thanks

**Comment by bastimeyer** [comment]
[`--stream-url`](https://streamlink.github.io/cli.html#cmdoption-stream-url)
> If possible, translate the stream to a URL and print it.

**Comment by ahmedtds** [comment]
@bastimeyer Thanks a lot, don't know how I missed that :\
