### ISSUE TITLE
Documentation to create a plugin

### ISSUE THREAD

**Issue by PCarlsson** [streamlink/streamlink#2828]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

This is not a request for a specific plugin but instead a request on documentation for creating a new plugin. I have seen older similar requests but I have tried to find any documentation on how to write a new plugin but could not find any.

I could of course learn by looking at existing plugins but I was hoping that at least a small guideline would be available.

What I like to know is the basics of how a plugin work, the common structure of a plugin, what is mandatory and any other details needed to write my own plugin.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/117
