### ISSUE TITLE
cdnbg doesn't find playable streams for BNT1-4

### ISSUE THREAD

**Issue by nchv** [streamlink/streamlink#2831]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

BNT1 - BNT4 don't play.

### Log output

```
streamlink --loglevel debug http://tv.bnt.bg/bnt1/16x9/ best
[cli][debug] OS:         Linux-4.12.14-lp151.28.40-default-x86_64-with-glibc2.3.4
[cli][debug] Python:     3.6.10
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt1/16x9/
error: No playable streams found on this URL: http://tv.bnt.bg/bnt1/16x9/
```

**Comment by back-to** [comment]
> http://tv.bnt.bg/bnt1/16x9/

`The page is not found`

use http://tv.bnt.bg/bnt1 which is GEO-Blocked

http://tv.bnt.bg/bnt4 is not GEO-Blocked and it works normal

```
$ streamlink http://tv.bnt.bg/bnt4 -l info
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt4
[plugin.cdnbg][warning] SSL Verification disabled.
[cli][info] Available streams: 576p (worst, best)
[cli][info] Opening stream: 576p (hls)
```

**Comment by nchv** [comment]
> > http://tv.bnt.bg/bnt1/16x9/  
> 
> `The page is not found`

This is a URL from:

https://github.com/streamlink/streamlink/blob/master/tests/plugins/test_cdnbg.py

> use http://tv.bnt.bg/bnt1 which is GEO-Blocked

For proxies to unblock perhaps check: https://github.com/streamlink/streamlink/issues/1164

> http://tv.bnt.bg/bnt4 is not GEO-Blocked and it works normal

Yes, 4 works. However 1-3 don't.

With nqma.net you can have a look at the main site bnt.bg

**Comment by back-to** [comment]
> Yes, 4 works. However 1-3 don't.

1-3 do work,
but **your IP is GEO-Blocked** so it can't work for you.

```
$ streamlink http://tv.bnt.bg/bnt1
[cli][debug] OS:         Linux
[cli][debug] Python:     3.7.5
[cli][debug] Streamlink: 1.3.1+51.geb72826
[cli][debug] Requests(2.23.0), Socks(1.6.7), Websocket(0.56.0)
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt1
[plugin.cdnbg][debug] Found iframe: http://cdn.bg/live/4eViE8vGzI
[plugin.cdnbg][warning] SSL Verification disabled.
[cli][info] Available streams: 360p (worst), 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 109611; Last Sequence: 109613
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 109611; End Sequence: None
[stream.hls][debug] Adding segment 109611 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 109612 to queue
[stream.hls][debug] Adding segment 109613 to queue
[stream.hls][debug] Download of segment 109611 complete
[cli][info] Starting player: /usr/bin/mpv
[cli.output][debug] Opening subprocess: /usr/bin/mpv "--title=Unknown Title" -
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 109614 to queue
[stream.hls][debug] Adding segment 109615 to queue
[stream.hls][debug] Adding segment 109616 to queue
```

**Comment by nchv** [comment]
> 1-3 do work,
> but **your IP is GEO-Blocked** so it can't work for you.

Wow. Now that you point that out I tested and indeed I cannot connect to e203-ts.cdn.bg on any port. That's very weird because I am in the country, i.e. there should be no reason for "geo" based blocking.

Could you please tell me: How do you access it? IOW: how can I "unblock" myself (perhaps using a proxy which you use)?

**Comment by nchv** [comment]
@back-to

OK, I found the issue - it's the URL.

You are using: http://tv.bnt.bg/bnt1
I was trying (what worked earlier): http://tv.bnt.bg/bnt1/16x9/

The former is not listed in:

https://github.com/streamlink/streamlink/blob/master/tests/plugins/test_cdnbg.py

but it works (for me too).

Does this mean that test_cdnbg.py needs an update?

**Comment by back-to** [comment]
> Does this mean that test_cdnbg.py needs an update?

it could be updated, but for the function of Streamlink it is **unimportant**.
so **no need for an update**.

_don't copy URLs blindly, make sure they work in your Browser._
