### ISSUE TITLE
Growing video delay (audio desync) on ZDF Live-TV.

### ISSUE THREAD

**Issue by cobrafast** [streamlink/streamlink#2832]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Playing ZDF Live TV works but has growing/accumulating video delay, meaning audio and video go increasingly out of sync over time.

Tested and happens with MPV and Windows Media Player.

### Expected / Actual behavior

Video and audio stay in sync.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink.exe 'https://www.zdf.de/live-tv' best`

**Comment by back-to** [comment]
update your FFmpeg

https://ffmpeg.org/download.html
https://ffmpeg.zeranoe.com/builds/

**Comment by cobrafast** [comment]
Thanks, that seems to fix the problem.
However, I had to update the `ffmpeg.exe` that came bundled with the Streamlink installer.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2872
