### ISSUE TITLE
[plugin.streann] Unable to parse JSON

### ISSUE THREAD

**Issue by oriolcorroto** [streamlink/streamlink#2834]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I've tried to use the plugin for the stream allowed in this website (http://crc.cr./estaciones/103-radio/), but reports the following issue:

### Reproduction steps / Explicit stream URLs to test

1. `streamlink "https://ott.streann.com/streaming/player.html?U2FsdGVkX19A0y3QLMfBRLTDTQIjXLQgG//MAizTRSaknjVDT/W29YBXPdULo79hrcbmUzEA7LSq2BmVXxr7zwTyjCP89gltIhQAu5oRFH4AZbtrv84YImKsEmVb58PiEAunM9fi2chYKO9I4xSneTBWN5VhPB7hnNtFb3OI8PQONqiPwblVt+xuWwpsf/VeOl5mxJPT2iFT4fbxcH1IhqbZl5PkyYC2fi9EfQz4SJStI2kFLJygYUI+K7Pgi5I1wHbkc5lf+Stu4Fu4mn8KjiQ1eywgVQWvCWTMYG6Q5QZWHwL7DrpCoIuY7eU+iQUiM0M3guP67WsOoDCwGqm4mA3jYnhkpr3Fify95Ah6+sf3Y9ORIc4VX7L/bGK+7QAcrgDDvsYInu4c+PIVVfB61g==" -l debug`

### Log output

```
[cli][debug] OS:         Linux-5.3.0-40-generic-x86_64-with-Ubuntu-19.10-eoan
[cli][debug] Python:     3.7.5rc1
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin streann for URL https://ott.streann.com/streaming/player.html?U2FsdGVkX19A0y3QLMfBRLTDTQIjXLQgG//MAizTRSaknjVDT/W29YBXPdULo79hrcbmUzEA7LSq2BmVXxr7zwTyjCP89gltIhQAu5oRFH4AZbtrv84YImKsEmVb58PiEAunM9fi2chYKO9I4xSneTBWN5VhPB7hnNtFb3OI8PQONqiPwblVt+xuWwpsf/VeOl5mxJPT2iFT4fbxcH1IhqbZl5PkyYC2fi9EfQz4SJStI2kFLJygYUI+K7Pgi5I1wHbkc5lf+Stu4Fu4mn8KjiQ1eywgVQWvCWTMYG6Q5QZWHwL7DrpCoIuY7eU+iQUiM0M3guP67WsOoDCwGqm4mA3jYnhkpr3Fify95Ah6+sf3Y9ORIc4VX7L/bGK+7QAcrgDDvsYInu4c+PIVVfB61g==
[plugin.streann][debug] passphrase ...
[plugin.streann][debug] Found passphrase
[plugin.streann][debug] get_token ...
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ()

```

### Additional comments, screenshots, etc.

Thanks in advance for your time and great job!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
the plugin was only tested with http://www.ellobo106.com/index.php/vivo/solo-3audio
doesn't seems like that they use it there.

https://github.com/streamlink/streamlink/blob/b325aff98d4002101b51b89246150d8d6f94dc99/src/streamlink/plugins/streann.py#L61

for your Website, the URL would need to change from `www.ellobo106.com` to `crc.cr`

**Comment by oriolcorroto** [comment]
Hi @back-to , you're right, changing the URL works perfectly.

Thanks a lot for your time and help, and have nice day! :)
