### ISSUE TITLE
Streamlink not showing up at command prompt after installation

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#284]
Hey everyone! 
I really need help with streamlink because after I installed it on my windows 7 pc I went to the command prompt and type streamlink with a twitch link to see if it working, But insted I got a message stating
"streamlink is not recognized as an internal or external command operable program or batch file" Even
after installing streamlink really need your help for this thanks!

**Comment by beardypig** [comment]
@bobvargas did you try the latest nightly version? [streamlink-latest.exe](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe), it might fix it for you :-)

**Comment by bobvargas** [comment]
@beardypig Wow latest nightly version works! Thx @beardypig
