### ISSUE TITLE
[picarto] Unable to open API URL, timeout after 20 seconds.

### ISSUE THREAD

**Issue by KynikossDragonn** [streamlink/streamlink#2841]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The picarto plugin appears to time out trying to access the API URL, this used to work just fine last week I'm not entirely sure what happened to cause this. I saw someone had opened a issue about this but then closed it almost immediately. nslookup and traceroute doesn't show any problems reaching the domain though. The website itself also appears to load the stream fine as well but this wastes a lot of resources on my system and makes the browser slow to a crawl.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink -l debug https://picarto.tv/ratte`
2. It detects it as a picarto URL and uses the picarto plugin.
3. Times out after 20 seconds waiting for a response from `api.picarto.tv`

### Log output

```
$ streamlink -l debug https://picarto.tv/ratte
[cli][debug] OS:         Linux-4.4.0-22-generic-x86_64-with-LinuxMint-17.3-rosa
[cli][debug] Python:     3.4.3
[cli][debug] Streamlink: 1.2.0
[cli][debug] Requests(2.21.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin picarto for URL https://picarto.tv/ratte
error: Unable to open URL: https://api.picarto.tv/v1/channel/name/ratte (HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0))

```

```
$ nslookup api.picarto.tv
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	api.picarto.tv
Address: 104.20.71.13
Name:	api.picarto.tv
Address: 104.20.70.13
```

```
$ traceroute api.picarto.tv
traceroute to api.picarto.tv (104.20.70.13), 64 hops max
  1   192.168.1.254  0.743ms  1.033ms  0.613ms 
  2   108.255.34.1  15.824ms  20.425ms  26.578ms 
  3   76.200.2.150  12.826ms  11.757ms  12.002ms 
  4   12.123.240.122  25.563ms  23.986ms  23.931ms 
  5   12.123.18.229  18.567ms  23.629ms  23.940ms 
  6   4.68.39.1  23.293ms  31.785ms  19.699ms 
  7   *  *  * 
  8   4.16.234.182  19.413ms  18.200ms  21.212ms 
  9   104.20.70.13  17.401ms  17.700ms  17.424ms 
```

**Comment by skulblakka** [comment]
> [cli][debug] Streamlink: 1.2.0

You are running an outdated version of streamlink. Try updating.

**Comment by KynikossDragonn** [comment]
Stupid me didn't realize I only had updated streamlink on the other system drive not on this one, it's updated here and working now but I'm confused why this worked just fine a week ago on 1.2.0 but after a AT&T U-Verse outage it stopped working...?

It must of been a weird coincidence. Should I close the issue then?

**Comment by bastimeyer** [comment]
> HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0)
> `nslookup api.picarto.tv`
> `traceroute api.picarto.tv`

Making HTTP(S) requests and waiting for a server response is not the same as making a simple DNS lookup or checking the routing. As you can see in the error message, it's a read timeout, which means that an HTTP request was made, but the server didn't send a (full) response in time.

The Streamlink version is probably irrelevant here, since the plugin was not updated in between these two versions and neither has something dramatically changed in Streamlink's internals.
https://github.com/streamlink/streamlink/commits/master/src/streamlink/plugins/picarto.py

This was probably just an issue on the site's end if API requests were timing out instead of erroring out.
