### ISSUE TITLE
mcloud stream download help

### ISSUE THREAD

**Issue by dru1507** [streamlink/streamlink#2842]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I am trying to download a vid from https://ffmovies.to/film/the-hunt.xv6lq/n3o0npk and I do not think i am using the correct commands

### Expected / Actual behavior

I expected it to download as it has done so previously however i just get an error

### Reproduction steps / Explicit stream URLs to test

1. C:\Users\Dru>streamlink --http-header "Referer=https://ffmovies.to/film/the-hunt.xv6lq/n3o0npk" "hls://https://bzkbx.mcloud.to/8/3a1f34b62f0ac5da/46fe09b6a18862383b54dd5a885cf2119e5a541c9b84c6331978da277964e3d4eba698987849fe80b282722cf6c170503260fc69b6f549db397ed07b1020f0a27d3d5ec408616c1b613d058ef051e7ee69b04e7099040570897a89ea53e61d10/hls/720/720.m3u8" best -o output.ts
This is all i entered
see log for result

### Logs

```
streamlink --http-header "Referer=https://ffmovies.to/film/the-hunt.xv6lq/n3o0npk" "hls://https://bzkbx.mcloud.to/8/3a1f34b62f0ac5da/46fe09b6a18862383b54dd5a885cf2119e5a541c9b84c6331978da277964e3d4eba698987849fe80b282722cf6c170503260fc69b6f549db397ed07b1020f0a27d3d5ec408616c1b613d058ef051e7ee69b04e7099040570897a89ea53e61d10/hls/720/720.m3u8" best -o output.ts
[cli][info] Found matching plugin hls for URL hls://https://bzkbx.mcloud.to/8/3a1f34b62f0ac5da/46fe09b6a18862383b54dd5a885cf2119e5a541c9b84c6331978da277964e3d4eba698987849fe80b282722cf6c170503260fc69b6f549db397ed07b1020f0a27d3d5ec408616c1b613d058ef051e7ee69b04e7099040570897a89ea53e61d10/hls/720/720.m3u8
error: Unable to open URL: https://bzkbx.mcloud.to/8/3a1f34b62f0ac5da/46fe09b6a18862383b54dd5a885cf2119e5a541c9b84c6331978da277964e3d4eba698987849fe80b282722cf6c170503260fc69b6f549db397ed07b1020f0a27d3d5ec408616c1b613d058ef051e7ee69b04e7099040570897a89ea53e61d10/hls/720/720.m3u8 (404 Client Error: Not Found for url: https://bzkbx.mcloud.to/8/3a1f34b62f0ac5da/46fe09b6a18862383b54dd5a885cf2119e5a541c9b84c6331978da277964e3d4eba698987849fe80b282722cf6c170503260fc69b6f549db397ed07b1020f0a27d3d5ec408616c1b613d058ef051e7ee69b04e7099040570897a89ea53e61d10/hls/720/720.m3u8)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
This is a bug tracker, not a help forum for illegally downloading movies from sites like this.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md
