### ISSUE TITLE
New release for Windows?

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink#2844]
Hi, when are you gonna release a new Windows release?

I want to be able to start to use twitch low latency mode support finally.

Thanks

**Comment by back-to** [comment]
@fenopa you can use the latest developer version

https://bintray.com/streamlink/streamlink-nightly/streamlink/_latestVersion/#files

**Comment by fenopa** [comment]
@back-to thanks a lot, installed and works great, finally can use low latency mode
