### ISSUE TITLE
Python 2.7.* issue

### ISSUE THREAD

**Issue by Oloko0** [streamlink/streamlink#285]
I just installed streamlink and I had this error when trying to launch a stream:

```
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 11, in <module>
from streamlink_cli.main import main
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 17, in <module>
from streamlink.stream import StreamProcess
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\__init__.py", line 5, in <module>
from .hds import HDSStream
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hds.py", line 16, in <module>
from .segmented import (SegmentedStreamReader,
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 1, in <module>
from concurrent import futures
ImportError: No module named concurrent
```

I had Python 2.7.* (I don't remember the exact version) and installing Python 3.5.2 fixed the issue. Maybe it was an error on my end, just wanted to point it out in case it might help someone.

**Comment by beardypig** [comment]
How did you install Streamlink (it looks like you used the installer) and how did you run it? If you used the Windows installer it comes with Python 3.5 and should put streamlink.exe in your PATH.

**Comment by Oloko0** [comment]
I used the Windows installer and I had Python 2.7 per-installed. When I looked at my programs installed on my PC, there was only Python 2.7, not 3.5. So I uninstalled Python 2.7 and manually installed 3.5.2 and it worked.

**Comment by beardypig** [comment]
That is weird, how are you running streamlink? 

When you use the installer Python 3.5.2 is installed to `C:\Program Files (x86)\Streamlink\Python\python.exe`. To run it you should be using the `streamlink.exe` that should be in your PATH, ie. by running `streamlink` from any directory.

**Comment by Oloko0** [comment]
I'm not sure what happened, I'm not able to reproduce the error again even when I install Python 2.7 again. I was launching it via "Streamlink Twitch GUI" so I'm not sure if the error was coming from there.
Maybe I had something weird in my PATH that caused this, sorry for the trouble.

**Comment by Shywim** [comment]
I'm using Streamlink Twitch GUI too (downloaded from Chocolatey) and I got the same error, I have Python2 and Python3 installed (before installing streamlink).
In my PATH I had Python2 folders before Python3, the error is gone after removing Python2 from my PATH, so streamlink is using the Python from the PATH.

**Comment by bastimeyer** [comment]
> the problem doesn't occur when running from the commandline

Because the streamlink pythonscript is using a different shebang, linking to the python3 executable.

> it seems the error comes from the Streamlink GUI

No, this is not an error. The Twitch GUI is looking up python independently, so if python2 is listed before python3 in the system's PATH env var, it will choose this instead. This is all documented in the wiki and also stated in the settings menu next to the input fields. The user is responsible for making sure that streamlink is working with the *selected* python version.

**Comment by Oloko0** [comment]
This would make sense, then I think there might be something wrong with the information displayed in Streamlink GUI settings since it says that Python version ">=2.6 <3 || >=3.3" is supported. So you would think that Python 2.7 works for it.

**Comment by skulblakka** [comment]
>So you would think that Python 2.7 works for it.

It does. As far as I understand it the problem here is that with the way your configuration was setup, the GUI tried to start the python3 version of streamlink with python2.

**Comment by beardypig** [comment]
Seems like this has resolved itself, if there is a continuing issue please reopen this :)
