### ISSUE TITLE
Instagram rewind

### ISSUE THREAD

**Issue by Jmart10** [streamlink/streamlink#2852]
Is it possible to add Instagram Live streams to have rewinding capabilities?

## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This isn't something Streamlink directly supports. You may be able to modify the player or player options to cache previously downloaded segments, or just download the video itself instead of streaming it via other options in the documentation. It's not something we're going to add though.
