### ISSUE TITLE
[Plugin] Picarto plugin timeouts on initial API request

### ISSUE THREAD

**Issue by NHOrus** [streamlink/streamlink#2853]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Attempts to connect to working picarto stream with streamlink return error:
```
https://api.picarto.tv/v1/channel/name/AssasinMonkey (HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0))
```
similar to closed tissues #2841 and #2790 

### Reproduction steps / Explicit stream URLs to test

1. Open stream in progress in browser ( I used https://picarto.tv/AssasinMonkey ).
2. Check that stream works in browser.
3. Attempt to open stream in video player on Linux, through `streamlinks https://picarto.tv/AssasinMonkey best`

### Log output

```
streamlink -l debug https://picarto.tv/yeougui
[cli][debug] OS:         Linux-5.5.7-1-default-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin picarto for URL https://picarto.tv/yeougui
error: Unable to open URL: https://api.picarto.tv/v1/channel/name/yeougui (HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0))
```

### Additional comments, screenshots, etc.

Stream was visible in Chrome and Firefox. Attempts to connect with streamlink failed from IP in Russia and in Netherlands.

**Comment by back-to** [comment]
same as https://github.com/streamlink/streamlink/issues/2841#issuecomment-602116474
