### ISSUE TITLE
get direct streamlink

### ISSUE THREAD

**Issue by shayegan1988** [streamlink/streamlink#2855]
Hi guys 
I am completely new in this section . I want to know is it possible to get direct hls link from "alkamai" ?
for example I have follow link 
`https://dcunilive89-lh.akamaihd.net/i/dclive_1@827634/master.m3u8?hdnea=st=1585567295~exp=1585567695~acl=/i/dclive_1@827634*~hmac=6da10bf91ae87e5efd9cef66435de4ebfb21236e1e9a3e465cedecebde08565f`

how I can get the link without expiration ?
Thanks in advance

**Comment by malvinas2** [comment]
Nope, you can't resp. a link without expiration won't be accepted by the server. 
That is one of the reasons this project exists, to deliver complete addresses.

**Comment by shayegan1988** [comment]
could you guide me how I can get complete link ? I install streamlink on my windows and set the path.
also I run follow code 
`streamlink https://dcunilive89-lh.akamaihd.net/i/dclive_1@827634/master.m3u8?hdnea=st=1585567295~exp=1585567695~acl=/i/dclive_1@827634*~hmac=6da10bf91ae87e5efd9cef66435de4ebfb21236e1e9a3e465cedecebde08565f`

now it is expired but before expiration it show it is available . Whats more steps I should follow?

**Comment by malvinas2** [comment]
_could you guide me how I can get complete link ?_
Your link just contains the URL of akamai, which is a content delivery network. What you need is the link of the content provider itself. Something like www.youtube.com or www.cnn.com/livetv etc.

**Comment by shayegan1988** [comment]
for example I have this link :
`https://playback2.akamaized.net/streams/5901056_4455330_lsi4nl1lwfj5uytcxzt_1/master.m3u8?dw=14400&hdnts=exp=1585573911~acl=/streams/5901056_4455330_lsi4nl1lwfj5uytcxzt_1/master.m3u8*~hmac=73562d71d3a46e7249d369186271bed924648202d24ae651dd9a669df5008d63`

from follow provider 
`https://parstv.tv/golive/`

Then what should I do with it ?
Thanks

**Comment by johnthecracker** [comment]
url="https://turnerlive.akamaized.net/hls/live/586497/cnngo/cnni/master.m3u8"
streamlink --player=ffplay $url 480p

**Comment by johnthecracker** [comment]
j@j:~/LINUX$ streamlink https://player-api.new.livestream.com/accounts/5901056/events/4455330/broadcasts/203760220.secure.m3u8 best
[cli][info] Found matching plugin hls for URL https://player-api.new.livestream.com/accounts/5901056/events/4455330/broadcasts/203760220.secure.m3u8
[cli][info] Available streams: 288p_alt (worst), 288p (best)
[cli][info] Opening stream: 288p (hls)
[cli][info] Starting player: /usr/bin/vlc

**Comment by back-to** [comment]
> https://parstv.tv/golive/

```
$ streamlink https://livestream.com/accounts/5901056/events/4455330/player best -l info
[cli][info] Found matching plugin livestream for URL https://livestream.com/accounts/5901056/events/4455330/player
[cli][info] Available streams: 288p_hls, 288p_hls_alt, 288p (worst, best)
[cli][info] Opening stream: 288p (akamaihd)
[cli][info] Starting player: /usr/bin/mpv
```

**Comment by johnthecracker** [comment]
https://parstv.tv/golive/


I get this from firefox network monitor:

```
https://player-api.new.livestream.com/accounts/5901056/events/4455330/broadcasts/203760220.secure.m3u8?dw=14400&hdnea=st%3D1585603263~exp%3D1585605063~acl%3D%2Fi%2F5901056_4455330_lsi4nl1lwfj5uytcxzt_1%40390046%2F%2A~hmac%3D910912e8a277946849ecf18f4afb3d4070f11a375c6525963ae08c1031cf43fc&token=5e8263eb_686f49a3e5ee25099e7d0afc447439fd76d0e34b
```

this plays in player directly:

```
https://player-api.new.livestream.com/accounts/5901056/events/4455330/broadcasts/203760220.secure.m3u8
```

<a href='https://postimg.cc/F7JjWtmm' target='_blank'><img src='https://i.postimg.cc/F7JjWtmm/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>


https://postimg.cc/F7JjWtmm

**Comment by bastimeyer** [comment]
Closing, since the site is wrapping a livestream.com stream, which is already supported by Streamlink, as @back-to has pointed out.
