### ISSUE TITLE
TF1 geoblocking

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#2863]
Hello

I noticed recently tf1 is banning entire ip range, mostly from well known french datacenter. though even with french IP, you are denied access to the streams, ex:

/usr/local/bin/streamlink https://www.tf1.fr/hd1/direct 576p
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/hd1/direct
[plugin.tf1][error] Failed to get dash stream for hd1: Désolé, cette vidéo n'est pas accessible depuis votre zone géographique (403)
[plugin.tf1][error] Failed to get hls stream for hd1: Désolé, cette vidéo n'est pas accessible depuis votre zone géographique (403)
error: No playable streams found on this URL: https://www.tf1.fr/hd1/direct

I tried to add an http header  x-forward but it isn't working . 

Any work around beside having a different ip?

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2512#issuecomment-505957791

**Comment by bastimeyer** [comment]
> from well known french datacenter

You are probably absuing their service by rehosting their content and have therefore been blocked. I've already pointed it out here:
https://github.com/streamlink/streamlink/issues/2499#issuecomment-501225372
https://github.com/streamlink/streamlink/issues/2499#issuecomment-501897347

Using a proxy from one of my OVH servers (which you are probably referring to with well known french datacenter) still works:

```
$ streamlink --https-proxy 'socks5://localhost:1920' 'tf1.fr/hd1/direct' best
[cli][info] Found matching plugin tf1 for URL tf1.fr/hd1/direct
[cli][info] Available streams: 234p (worst), 234p+a97k, 234p+a129k, 360p, 360p+a97k, 360p+a129k, 576p_alt, 576p, 576p+a97k, 576p+a129k, 720p, 720p+a97k, 720p+a129k (best)
[cli][info] Opening stream: 720p+a129k (dash)
[cli][info] Starting player: mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
