### ISSUE TITLE
Problem with a live stream

### ISSUE THREAD

**Issue by mfat** [streamlink/streamlink#2868]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Expected / Actual behavior

Download the livestream from https://www.irinn.ir/fa/live

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8SOMESTRING best
2. ...
3. ...

### Log output

```
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=x6-14mg_zvFnM-wvxNfwZA
[plugin.hls][debug] URL=https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=x6-14mg_zvFnM-wvxNfwZA; params={}
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=x6-14mg_zvFnM-wvxNfwZA (403 Client Error: Forbidden for url: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=x6-14mg_zvFnM-wvxNfwZA)
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
you are missing a few parameters:

```
[cli][info] Found matching plugin hls for URL https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064
[cli][info] Available streams: 240p (worst, best)
[cli][info] Opening stream: 240p (hls)
[cli][info] Starting player: mpv.exe
```

**Comment by mfat** [comment]
Which parameters are missing?  Here is the output: (I'm using a Macbook)

`streamlink "https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064" best
[cli][info] Found matching plugin hls for URL https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064
error: Unable to open URL: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064 (403 Client Error: Forbidden for url: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064)`

**Comment by johnthecracker** [comment]
here is output from ubuntu, I don't use mac.
this output is self explanatory:

```
j@j:~$ streamlink "https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064" best
[cli][info] Found matching plugin hls for URL https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064
error: Unable to open URL: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064 (410 Client Error: Gone for url: https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=t4S_13NSj8fVA2mdGB5hFg&t=1586257064)
j@j:~$ 
```

and here is one working now:

```
j@j:~$ streamlink "https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=ZuP-KmghNEyPjN_1H4Ca1A&t=1586271832" best
[cli][info] Found matching plugin hls for URL https://cdn1live.irib.ir/live-channels/smil:irinn/playlist.m3u8?s=ZuP-KmghNEyPjN_1H4Ca1A&t=1586271832
[cli][info] Available streams: 240p (worst, best)
[cli][info] Opening stream: 240p (hls)
[cli][info] Starting player: /usr/bin/vlc
```

**Comment by johnthecracker** [comment]
you must be quick to use url

**Comment by mfat** [comment]
Did you manage to play it? I copied and pasted URLs quickly. No luck!

**Comment by johnthecracker** [comment]
Yes I did. If you get url with script, it will certainly work.
I got this url from browser's network monitor, copied url to terminal and there it goes.
This was the time it took stream to work.
On some sites you have just few seconds to use the url.

**Comment by mfat** [comment]
Sorry what do you mean by "script"?

**Comment by johnthecracker** [comment]
you have to write a script, small program that will do for you so you don't have to do it manually.
There are many programming languages you can use to write a script.
Doesn't matter which one, as long as your code is good any scripting language will work.
In mac you can start by learning shell scripting.
To write a script you need programming skills. If you don't want to learn programming skills,
it is to your disadvantage.
By the way, I'm not that bad with programming..

**Comment by johnthecracker** [comment]
you are on streamlink's site and probably know basics about how streamlink works.
It is a program that is used on command line or in script, and has plugins for legit sites.
If you can't program and your site is legit, you may ask these developers kindly if they
would be willing to write a plugin for you.
This is done by making "plugin request" by following guidance on streamlink's website.
I personally don't need plugin for site like this one.

Cheers.

**Comment by mfat** [comment]
Thanks I know how it works. I just grabbed the playlist url from the browser's network monitor, and pasted in VLC. It worked.

The same URL in streamlink causes 403 errors! 

Another interesting fact: youtube-dl returns a similar error!

**Comment by johnthecracker** [comment]
You didn't provide enough details as required by this issue tracker.
How old is your streamlink?
New streamlink uses firefox user agent while old ones use some python request string as user agent.
Do some research what causes error 403. One of the causes may be user agent string.

youtube-dl is irrelevant, it is for vod's while streamlink is for live streams.

**Comment by mfat** [comment]
Thank you I just read your first reply more carefully and learned I had forgotten the "" marks at the beginning and end of URL.

However it's weird because for other URLs I didin't use any "" and they worked. Thanks for your help and time.
