### ISSUE TITLE
Support for Fox TR Web

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#287]
Hey there,

from the official Fox TR Website:

http://www.fox.com.tr/canli-yayin

Hopefully a little fix will do magic 👍 

Greetings

**Comment by Rotarum** [comment]
Something has changed on their Website. Tried the foxtr Plugin but no luck...

Can you have a look ?

**Comment by beardypig** [comment]
Working fine from here... what error did you get?
