### ISSUE TITLE
[plugin:afreeca.py] broken

### ISSUE THREAD

**Issue by ukoz** [streamlink/streamlink#2874]
- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
The link, transferred to [player] via Streamlink is broken in some way.
Stream can be opened in browser and working.

### Reproduction steps / Explicit stream URLs to test

1. Open http://www.afreecatv.com/
2. There lots of streams, choose any live stream (not vod), right click, copy link.
3.  >Streamlink http://play.afreecatv.com/wocc1125/222659413 (it example link from random channel that was active at moment). Only live channels are supported.

### Log output

No errors with live youtube and twitch channels.
Stream can be viewed via browser and live at moment of writing report. It really important to not copy link from log output and take link to any other live channel instead.
Same error if I run "Streamlink http://play.afreecatv.com/wocc1125/222659413 sd".
>Streamlink --loglevel debug http://play.afreecatv.com/wocc1125/222659413
[Streamlink for Windows v1.3.1 - Git W/5effc]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.3.1+W/5effc
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/wocc1125/222659413
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: hd (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.84GNo2ISh2b_Mz5VWYr4Jl1_cXWaWQEsWcfZw9uDpMr1B3yLLjmg2awNuX9mPa8dXqdRXrgLO0e2HK50BzfZ1ZyXGj_qJlBzHvhDwXk7K-w')> (Could not open stream: Unable to open URL: http://live-hls-local-cf.afreecatv.com/ko-livestream-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.84GNo2ISh2b_Mz5VWYr4Jl1_cXWaWQEsWcfZw9uDpMr1B3yLLjmg2awNuX9mPa8dXqdRXrgLO0e2HK50BzfZ1ZyXGj_qJlBzHvhDwXk7K-w (403 Client Error: Forbidden for url: http://live-hls-local-cf.afreecatv.com/ko-livestream-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.84GNo2ISh2b_Mz5VWYr4Jl1_cXWaWQEsWcfZw9uDpMr1B3yLLjmg2awNuX9mPa8dXqdRXrgLO0e2HK50BzfZ1ZyXGj_qJlBzHvhDwXk7K-w&aid=.A32.7bbT56vyHM9fKZk.84GNo2ISh2b_Mz5VWYr4Jl1_cXWaWQEsWcfZw9uDpMr1B3yLLjmg2awNuX9mPa8dXqdRXrgLO0e2HK50BzfZ1ZyXGj_qJlBzHvhDwXk7K-w))
error: Could not open stream <HLSStream('http://live-hls-local-cf.afreecatv.com/ko-livestream-04/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.84GNo2ISh2b_Mz5VWYr4Jl1_cXWaWQEsWcfZw9uDpMr1B3yLLjmg2awNuX9mPa8dXqdRXrgLO0e2HK50BzfZ1ZyXGj_qJlBzHvhDwXk7K-w')>, tried 1 times, exiting
[End of Streamlink for Windows with ExitCode 1]

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2850

use a User-Agent or wait for the next Streamlink release
