### ISSUE TITLE
[Plugin Request] ustvgo.tv

### ISSUE THREAD

**Issue by fhoshino** [streamlink/streamlink#2876]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

If you are bored at home, you can watch these US Channels LIVE on your computer.  They just made it available to promote Stay At Home

### Example stream URLs

1. https://ustvgo.tv/

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
I believe the legitimate version of the site is https://www.ustvnow.com/
