### ISSUE TITLE
Picarto 'live' flash support (sometimes) broken

### ISSUE THREAD

**Issue by mjevans** [streamlink/streamlink#288]
During the failed case, the value of the match group is:

"REDACTED",1,0, 0, 1, "public", 1

the value of channel_server_res.text is:

edge4-us-east.picarto.tv

Unfortunately I can't collect any more data at this time.

streamlink -l debug https://picarto.tv/REDACTED best
[cli][info] Found matching plugin picarto for URL https://picarto.tv/REDACTED
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][error] No data returned from stream
Fatal Python error: could not acquire lock for <_io.BufferedReader name=7> at interpreter shutdown, possibly due to daemon threads

Thread 0x00007f0bc1002700 (most recent call first):
  File "/usr/lib/python3.5/site-packages/streamlink/stream/wrappers.py", line 85 in stop
  File "/usr/lib/python3.5/site-packages/streamlink/stream/wrappers.py", line 77 in run
  File "/usr/lib/python3.5/threading.py", line 914 in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 882 in _bootstrap

Current thread 0x00007f0bca470400 (most recent call first):
  File "/usr/lib/python3.5/site-packages/streamlink/stream/wrappers.py", line 85 in stop
  File "/usr/lib/python3.5/site-packages/streamlink/stream/wrappers.py", line 105 in close
  File "/usr/lib/python3.5/site-packages/streamlink/stream/streamprocess.py", line 27 in close
Aborted (core dumped)

---

However some other random adult/clean streams I tried do work...

[cli][info] Found matching plugin picarto for URL https://picarto.tv/B
[cli][info] Available streams: 1295k (worst, best)
[cli][info] Opening stream: 1295k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 624 to queue
[stream.hls][debug] Adding segment 625 to queue
[stream.hls][debug] Adding segment 626 to queue
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv --cache 256
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 624 complete
[stream.hls][debug] Download of segment 625 complete
[stream.hls][debug] Download of segment 626 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 627 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 627 complete
[cli][info] Stream ended

[cli][info] Found matching plugin picarto for URL https://picarto.tv/C
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv --cache 256
[cli][debug] Writing stream to output
[cli][info] Player closed
[cli][info] Stream ended

[cli][info] Found matching plugin picarto for URL https://picarto.tv/D
[cli][info] Available streams: 880k (best, worst)
[cli][info] Opening stream: 880k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2018 to queue
[stream.hls][debug] Adding segment 2019 to queue
[stream.hls][debug] Adding segment 2020 to queue
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv --cache 256
[stream.hls][debug] Download of segment 2018 complete
[stream.hls][debug] Download of segment 2019 complete
[stream.hls][debug] Download of segment 2020 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2021 to queue
[stream.hls][debug] Adding segment 2022 to queue
[stream.hls][debug] Download of segment 2021 complete
[stream.hls][debug] Download of segment 2022 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2023 to queue
[stream.hls][debug] Adding segment 2024 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 2023 complete
[cli][info] Stream ended

**Comment by beardypig** [comment]
Weird, does it happen consistently with the same stream?

**Comment by mjevans** [comment]
Yes, if the problem happens it does happen consistently with the same stream.   That's why I suspected it might depend on which server was providing the feed.

Additional telemetry under debug would probably be a good idea in case others experience the same issue, but I didn't see any logging examples within the picarto plugin to mirror so I just grabbed sys.stderr.

**Comment by beardypig** [comment]
OK, good idea to add some extra debug logging. I will try to recreate the bug. Which version of which OS are you using? And which minor version of Python are you using?

**Comment by mjevans** [comment]
ArchLinux (a rolling release Linux)

The streamlink-git package (which, more or less, automates rebuilds from git checkout).

python --version
Python 3.5.2

**Comment by mjevans** [comment]
Adding some quick and dirty things to dump data...

        for ix in [channel, player_id, product, offline_image, online, visibility, is_flash]:
          iz.append(str(ix))
        print("_gsa: {}".format("\t".join(iz)), file=sys.stderr)

        print("_gs_res: {}".format(channel_server_res.text), file=sys.stderr)

USer vs UserD, same server, similar other things, but something not presently captured appears to be different.


(Of a 'sampling' only USer appears to fail, this is consistent, but I don't want to identify which user this is; I am willing to collect generic data and review it to make sure it doesn't contain personally identifying data before submission)

[cli][info] Found matching plugin picarto for URL https://picarto.tv/USer
_gsa: USer    True    False   False   True    public  True
_gs_res: edge5-us-east.picarto.tv
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][error] No data returned from stream


[cli][info] Found matching plugin picarto for URL https://picarto.tv/UserB
_gsa: UserB  True    False   False   True    public  True
_gs_res: edge4-us-east.picarto.tv
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv --cache 256
[cli][debug] Writing stream to output
[cli][info] Player closed
[cli][info] Stream ended


[cli][info] Found matching plugin picarto for URL https://picarto.tv/UserC
_gsa: UserC   True    False   False   True    public  False
_gs_res: edge4-us-east.picarto.tv
[cli][info] Available streams: 730k (best, worst)
[cli][info] Opening stream: 730k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3495 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 3496 to queue
[stream.hls][debug] Adding segment 3497 to queue
[cli][info] Starting player: mpv --cache 256
[stream.hls][debug] Download of segment 3495 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 3496 complete
[stream.hls][debug] Download of segment 3497 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3498 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[stream.hls][debug] Download of segment 3498 complete
[cli][info] Stream ended


_gsa: UserD   True    False   False   True    public  True
_gs_res: edge5-us-east.picarto.tv
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv --cache 256
[cli][debug] Writing stream to output
[cli][info] Player closed
[cli][info] Stream ended

**Comment by beardypig** [comment]
@mjevans UserD worked but USer failed? 

If you want to, you can email (beardypig at protonmail dot com) the failing stream and I will test it out.

**Comment by mjevans** [comment]
Following up on this.

ONE time it happened to work after I did something else, but that isn't repeatable.

Interestingly, when I look at the control interface in the web browser I now see that it seems to claim the stream type is 'HTML5' instead of flash.

Would an HTML5 type stream still use rtmp, or is it possible that Picarto's detection is broken?

**Comment by beardypig** [comment]
@mjevans, yeah it could be a bug in the html5/flash detection. If you get an html5 player but streamlink thinks it's flash could you grab the source for the page an post it on pastebin (or similar)?

**Comment by mjevans** [comment]
It's not documented well in the picarto plugin, but I think the part your interested in is here...

			
			<script> placeStream("REDACTED",1,0, 0, 1, "public", 1 ); </script>

I added some code just to save the streamlink get result, and that looks like where the stream is actually created, it also matches the existing regular expression.


In my browser (which I have to use at the moment since streamlink still hates me for this artist, and livestreamer... I don't even bother trying anymore), in the control bar I see the fullscreen popout button, HTML5, viewer count, and the gear which yields:

Player Options
Please give us Feedback.
HTML5 Feedback
You don't like what you see?
Report
Popout


For versions:

pacaur -Qs rtmp
python-librtmp 0.3.0-1
    Python interface to librtmp (python3 version)
rtmpdump 1:2.4.r96.fa8646d-2
    Tool to download rtmp streams

streamlink --version
streamlink 0.2.0 (rebuilt from git this morning via the streamlink-git package)

**Comment by beardypig** [comment]
Looks like something else has changed in the page layout. I'm on holiday at the moment and only have my phone to see the sites, but it looks like this is the data for the html5 player (the pop out anyway). 

```html
<div class="bot5 displayBlock btnBase btn-sm settingsBtn popoutStream" data-playerid="1" data-channel="SharpeCostumes" data-token="public">
```

**Comment by beardypig** [comment]
@mjevans can you check out this version of [picarto.py](https://github.com/beardypig/streamlink/blob/d13219209782c6b8fd5d7355e32854e919ef0568/src/streamlink/plugins/picarto.py) and see if it solves your issue. I could not find a stream that didn't work with the HTML5 player... I tested a lot of them :)

**Comment by mjevans** [comment]
Thank you for the update.  I can confirm that it works on the streamer that I was having issues with as well as on another artist that I checked out.

**Comment by beardypig** [comment]
Great, I'll reopen this issue until those changes are merged though :-)

**Comment by gravyboat** [comment]
Closing since the associated PR has been merged.
