### ISSUE TITLE
[README] Flash is coming to an end

### ISSUE THREAD

**Issue by brouxco** [streamlink/streamlink#2880]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Some information in this README is not up to date.

> Streamlink is a CLI utility that pipes **flash videos** from online streaming services to a variety of video players such as VLC.

> The main purpose of streamlink is to convert CPU-heavy **flash plugins** to a less CPU-intensive format.

Adobe Flash Player is coming to an end (see [Adobe's blog post](https://theblog.adobe.com/adobe-flash-update/)) and the vast majority of website are using HTML5.

We should change the wording.

**Comment by bastimeyer** [comment]
Thanks for the suggestion.

The docs were already updated a few days with a better description, but the README did once again not get any attention. :man_facepalming: 
https://github.com/streamlink/streamlink/blame/master/docs/index.rst#L4-L11

Would you please be so kind and open a new pull request with a quick fix for the README.md, similar to the docs? Thank you.
