### ISSUE TITLE
bbc iplayer does not work

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [streamlink/streamlink#2883]
Iplayer plugin does not play bbc stream complains that user and password is wrong. I have it right for sure. Seems to be pausing over the tv licence question on the website?

streamlink http://www.bbc.co.uk/iplayer/live/bbcone best --bbciplayer-username xxx --bbciplayer-password xxx
[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/live/bbcone
[plugin.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugin.bbciplayer][error] Could not authenticate, check your username and password
error: No playable streams found on this URL: http://www.bbc.co.uk/iplayer/live/bbcone

**Comment by bastimeyer** [comment]
Post a **full debug log** (`--loglevel debug`), just like the issue template asks you to do. This debug log should also include your Streamlink version.

There was a bbc iplayer auth issue fix in #2755, which is included in the 1.3.1 release.
https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L23

**Comment by bachoo786** [comment]
The login issue has come up again with streamlink 2.4.0. Here is my full debug log:

```
streamlink http://www.bbc.co.uk/iplayer/live/bbcone best --bbciplayer-username XXX --bbciplayer-password XXX --loglevel debug
[cli][debug] OS:         Linux-5.10.52-v7l+-armv7l-with-debian-10.10
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 2.4.0+20.ga0437c2
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=http://www.bbc.co.uk/iplayer/live/bbcone
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --bbciplayer-username=zahrahmed@hotmail.co.uk
[cli][debug]  --bbciplayer-password=********
[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/live/bbcone
[plugins.bbciplayer][info] A TV License is required to watch BBC iPlayer streams, see the BBC website for more information: https://www.bbc.co.uk/iplayer/help/tvlicence
[plugins.bbciplayer][error] Could not authenticate, check your username and password
error: No playable streams found on this URL: http://www.bbc.co.uk/iplayer/live/bbcone
```

**Comment by bastimeyer** [comment]
Again, please don't comment on old issues. PR here now: #4041
