### ISSUE TITLE
youtube live retrieval fails to get start but only current recent segments

### ISSUE THREAD

**Issue by Wingzzzzz** [streamlink/streamlink#2891]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
youtube live hls time/segment retrieval fails to get start but only recent segments and going on

### Expected / Actual behavior
expected: used to download youtube live(rewind enabled) from start until it ends 
actual: download current recent few live segments until it ends

### Reproduction steps / Explicit stream URLs to test

using following command:
streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "[file].ts" [url] best

### Additional comments, screenshots, etc.
tried other hls related option but not succeed
streamlink --hls-start-offse [time] -o "[file].ts" [url] best
streamlink --hls-live-restart -o "[file].ts" [url] best

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Wingzzzzz** [comment]
this is a thread same as https://github.com/streamlink/streamlink/issues/2890
please close after clarifying if it is the correct conclusion:
there is not much we can do about it from back-to.
and i'd like to correct https://github.com/streamlink/streamlink/issues/2890#issuecomment-612657410 that this function does not work even rewind enabled

**Comment by back-to** [comment]
@Wingzzzzz 

we use the **HLS** livestream,
youtube changed something recently and now there might be no rewind available with **HLS** streams.

Ref https://github.com/streamlink/streamlink/issues/2542

they use there **DASH** streams for rewind,
but we removed them for livestreams because we got problems with them.

Ref https://github.com/streamlink/streamlink/issues/1520
Ref https://github.com/streamlink/streamlink/pull/1556

---

so currently it is not possible to use rewind with Streamlink

**Comment by hanbule** [comment]
This is very very bad news.

**Comment by gravyboat** [comment]
It's only bad news for a very small percentage of people. If you want to fix the DASH streams @hanbule feel free to do so.

**Comment by L33Tech** [comment]
This isn't bad news for a small percentage, this is bad for a lot of users. This feature was the whole reason I used streamlink and now it doesn't work at all.

**Comment by scottbernstein** [comment]
Yep, this is a really big feature to be broken for me as well, unfortunately.
________________________________

**Comment by gravyboat** [comment]
I understand this is a big feature for a few people but the install base for Streamlink is something around 30,000-50,000 users based on the GitHub download statistics and this is a pretty minor feature that would require a lot of work. I don't really think there's anything else to be gained by adding on to these comments disapproving of my comment or back-to's.

We're not stating this out of some sort of personal animosity towards this feature. We can't help that Youtube changed how their systems work and it's broken now. We've tried to make DASH work in the past but it hasn't worked out and there's not much drive to try and spend more personal time from contributors to make it work. Like every other feature or plugin if someone wants to work on it they will, if not the work simply won't get done. This is one of the downsides and benefits of open source and free tools like Streamlink. Anyone can contribute if they want to, but people contribute in ways they want.

If you want to work on the issue you're free to do so and we'll happily review a PR, but just complaining it doesn't work simply clutters notifications and doesn't provide any value.
