### ISSUE TITLE
Instagram Live Support (Livestream via PC Browser)

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#2893]
Hi,

since a few days instagram.com (Web Site) is finally supporting Livestreams.

You can watch with Firefox or other Browser.

Is it possible to add a plugin for it?

Would appreciate it very much :)

Greetings

**Comment by back-to** [comment]
> since a few days instagram.com (Web Site) is finally supporting Livestreams.

how do I even find a Livestream?
Add some more details.

**Comment by scottbernstein** [comment]
I don't think that you can watch them "archived" -- you have to catch them while they are happening.  They are using DASH MPD manifests
________________________________

**Comment by Rotarum** [comment]
Just open www.instagram.com on your Windows Computer Browser and you will find the Livestreams @ right side under "Stories"

**Comment by Rotarum** [comment]
Hi scott,

under "IGTV" on the Website Browser you can find the archived ones. These are downloadable with any Video Download Browser Addon.

For the LIVE Stream we need a working streamlink plugin.

Possible to create one?

Greetings
:)

**Comment by Rotarum** [comment]
Hello again,

instagram has changed the format.

It's now directly accessable on the website.

instagram.com/*username*/live

**Comment by Piiuzinho** [comment]
up

**Comment by Piiuzinho** [comment]
up

**Comment by KanzakiRanko1** [comment]
@back-to does it still count as `does not meet requirements`? Those streams are in instagram.com/*username*/live as @Rotarum mentioned, and only available while the livestream is ongoing.

Glad to provide a HAR log of a test livestream playback in case it helps.

**Comment by Rotarum** [comment]
Hi,

the format is still the same: username slash live

Is it not possible to make it work with Streamlink?

Greetings

**Comment by back-to** [comment]
@KanzakiRanko1 

> instagram.com/username/live

it is not that simple, you can't view the stream without a login

> Glad to provide a HAR log of a test livestream playback in case it helps.

you should first check if the stream URL works with the Streamlink **hls or dash plugin**,
but with the facebook login requirement it is just a bit annoying to create a plugin.

---

@Rotarum 

> Is it not possible to make it work with Streamlink?

it could be, but there are no details if the streams are even working with Streamlink

**Comment by Rotarum** [comment]
It's not possible to add user/pass Authentication? So we can enter the Instagram username password into command line for successful login?

**Comment by jzvi12** [comment]
@Rotarum Have you checked if the stream URL works with the Streamlink hls or dash plugin?

**Comment by Rotarum** [comment]
Hi jzvi12,

checked again:

"error: No plugin can handle URL: https://www.instagram.com/username/live/"

I see facebook.py in the Plugins list but why is Instagram not supported??

**Comment by back-to** [comment]
@Rotarum 
> I see facebook.py in the Plugins list but why is Instagram not supported??

You don't need an account for Facebook, but you need an account for Instagram.

There is no way to access the Stream without an account.

Also we still don't know what Streams there are used, if they are compatible with Streamlink or not.

**Comment by Rotarum** [comment]
Thanks for answer.

Is it not possible to add user/pass authentication to the plugin?

**Comment by back-to** [comment]
closing

- Impossible to find Livestreams on the Desktop version.
- Login is basically the same as Facebook, which won't be added.
- Using cookies won't work, because people will probably lock themselves out.
