### ISSUE TITLE
Zoom (video conferencing)

### ISSUE THREAD

**Issue by heinrich5991** [streamlink/streamlink#2897]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

[https://en.wikipedia.org/wiki/Zoom_Video_Communications](Zoom) is a videoconferencing platform. Some people also use it as a teaching platform. In order to be able to watch lectures (which are generally one-way), it would be nice if it was supported by streamlink. It is run by a company of the same name from the US.

### Example stream URLs

Example URLs for streams are required. Plugin requests which do not have example URLs will be closed.

I understand the above, but it is hard to find test URLs of always-online streams (because free meetings are closed after 40min). Feel free to close the issue due to that. **I'd be interested in knowing whether a pull request adding this site would be accepted.** You can create a test meeting by going to https://zoom.us/test and creating a test meeting (open it in Chrome/Chromium, needs an account and you need to dodge the app download, you can select "share screen" and share a Chromium tab afterwards, creating a video feed)

1. https://zoom.us/j/99732331748 (probably outdated by the time you read this issue).

### Additional comments, screenshots, etc.

This is me sharing a Google tab from Chromium:

![Zoom meeting with a shared Google tab](https://user-images.githubusercontent.com/366230/79459174-29020480-7ff3-11ea-94bf-4aab87f60e8d.png)

**If you close this issue because of lacking stream URLs, please also say whether a PR with a plugin for this site would be accepted.**

**Comment by bastimeyer** [comment]
I think this falls into the same category as #2768.

**Comment by heinrich5991** [comment]
@bastimeyer Would that mean that a PR adding a plugin for Zoom would not be accepted?

From #2768:

>>It is not possible to post a URL for a Discord stream as it is in-app only at this time
>
>Streamlink needs an URL

Zoom does have URLs (of the form https://zoom.us/j/99732331748).

>>The Go Live feature gives you an easy way to stream in a server voice channel for up to 10 of your friends.
>
>https://support.discordapp.com/hc/en-us/articles/360030714312-Go-Live-FAQ
>only 10 viewer max

It has a maximum of 100 viewers in the free plan, but institutions using this to stream lectures can have non-free plans with much more viewers.

**Comment by mkbloke** [comment]
Is this info useful?

https://techcrunch.com/2020/03/23/one-neat-plug-in-to-join-a-zoom-call-from-your-browser/

As far as I can tell, Zoom allows a basic web client now, although the link is hidden by default unless it's changed in the host settings, but I *think* from reading this that link still actually works even when hidden.

The link is apparently of the form ```zoom.us/wc/join/{your-meeting-id}```

I guess it could be worth checking out...

**Comment by jzvi12** [comment]
> 
> The link is apparently of the form `zoom.us/wc/join/{your-meeting-id}`
> 

There is Chrome extension (https://chrome.google.com/webstore/detail/zoom-redirector/fmaeeiocbalinknpdkjjfogehkdcbkcd?hl=en) that forces to use the Zoom web client without downloading anything

`https://zoom.us/wc/join/{meeting-id}?tk=&prefer=0&track_id=&meeting_result=&jmf_code=&wpk=xxxxxxx`

**Comment by back-to** [comment]
Not worth it.
