### ISSUE TITLE
[bug] BTV plugin needs updating

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2899]
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description
The location of the BTV livestream has moved to https://btvplus.bg/live/
**Edit**: Livestreaming no longer requires a user to login, so that can be removed from the plugin info page.

### Expected / Actual behavior
Streamlink should be able to handle the link.

### Reproduction steps / Explicit stream URLs to test
1. streamlink https://btvplus.bg/live/ best 
2. error: No plugin can handle URL: https://btvplus.bg/live/

**Comment by mkbloke** [comment]
Hi @roshavagarga 

I've submitted a plugin fix for this.  If you could possibly test it for me, you can get it from:

https://github.com/mkbloke/streamlink/blob/btv-site-change-2020-06/src/streamlink/plugins/btv.py

Just select Raw and then save it via your browser and place it into your plugins dir.

Many thanks.

**Comment by roshavagarga** [comment]
Hey @mkbloke 
Replaced the old plugin, tested it out, works a-okay for me.

Thank you very much for the work you put in!

**Comment by mkbloke** [comment]
That's great.  Thanks for testing it and getting back to me - that was a super-quick response! :-)

**Comment by roshavagarga** [comment]
The pandemic has that effect on communication I'd say :P
