### ISSUE TITLE
crunchyroll download

### ISSUE THREAD

**Issue by simonrule** [streamlink/streamlink#290]
is there anyway we can download crunchyroll series?

**Comment by gravyboat** [comment]
Streamlink has a variety of [file output options](https://streamlink.github.io/cli.html#file-output-options)

**Comment by simonrule** [comment]
can you please how the command will look like i want to download this episode http://www.crunchyroll.com/izetta-the-last-witch/episode-11-fin-720973 best quality

**Comment by gravyboat** [comment]
No, the documentation has examples of how to use the options. If you review them you can figure it out.

**Comment by simonrule** [comment]
i was able to open the same stream last night but i can't get it work today i get this error
"No streams found on this URL: http://www.crunchyroll.com/izetta-the-last-witch/episode-11-fin-720973"

**Comment by gravyboat** [comment]
Closing this out since it's rather old and there hasn't been an update in a while.
