### ISSUE TITLE
[bug] Nova doesn't handle archival videos

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2900]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
Archival video links can not be opened by the nova plugin.

### Reproduction steps / Explicit stream URLs to test
https://play.nova.bg/video/otkradnat-zhivot/season-9/stolen-life-2020-04-16

**Comment by gravyboat** [comment]
Is this really a bug @bastimeyer? I thought we've taken the stance we don't really care about VODs?

**Comment by bastimeyer** [comment]
@gravyboat Well, the site is already supported by a plugin and the VOD looks like a *simple* HLS stream (with encryption key).
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/cdnbg.py

Had another look at it just now and the HLS playlist seems to contain the following comment:

> NeuLion Adaptive Streaming Server Version: 5.1.20190416.24856

Not sure how to interpret this. I don't want to see another nonsense dmca takedown notice.

If you want to close it, go ahead. I was just tagging these 10 requests from today and trying to respond.

**Comment by gravyboat** [comment]
@bastimeyer Yeah I understand, I almost just closed all 10 of those requests and may still do so since we've shut that behavior down in the past. I'm going to close this one. We don't care about VODs and there are plenty of other tools out there that handle VODs.
