### ISSUE TITLE
[removal] Eurocom plugin no longer required

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2901]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
When opening the main link, nothing happens.

### Reproduction steps / Explicit stream URLs to test
https://eurocom.bg/live

**Comment by bastimeyer** [comment]
They are using a static HLS address now instead of a rtmp stream, which means the plugin can/should be removed now:

```
$ streamlink -l debug https://eurocom.bg/hls/stream.m3u8
[cli][debug] OS:         Linux-5.6.0-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1+113.g1b287a6
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin hls for URL https://eurocom.bg/hls/stream.m3u8
[plugin.hls][debug] URL=https://eurocom.bg/hls/stream.m3u8; params={}
[utils.l10n][debug] Language code: en_US
Available streams: live (worst, best)
```

**Comment by roshavagarga** [comment]
Didn't notice they'd done that, I agree that the plugin is no longer required.
