### ISSUE TITLE
[bug] CDNBG - multiple issues

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2902]
## Bug Report
1. BITelevision should be removed from the plugin and/or wiki/info pages, as it no longer exists.
2. Inlife.bg shouldn't be listed as supported under CDNbg.
3. Tvbulgare.bg should be listed as supported in inlife.bg's place (latter shares the former's stream)
4. Mu-vi.tv gives an error.
5. CDNBG should cover VTK - the national military channel
6. Kanal3's livestream is not found.
7. CDNBG should cover Cherno More - the regional channel for Varna, Bulgaria.

### Reproduction steps / Explicit stream URLs to test
1. https://bitelevision.com/ is not a thing anymore.
2. Inlife.bg can't be opened and shouldn't be listed - it is a 'media partner' that restreams https://tvbulgare.bg/, which could be put in as a replacement for it.
3. https://tvbulgare.bg/ - No playable streams found.
4. http://mu-vi.tv/LiveStreams/pages/Live.aspx - Error: Unable to open URL.
5. https://www.armymedia.bg/
6. https://kanal3.bg/live
7. https://www.chernomore.bg/

**Comment by bastimeyer** [comment]
> gives an error

post a debug log for each of them, as the **plugin issue** template asks you to do

**Comment by roshavagarga** [comment]
@bastimeyer Logs:
1. https://hastebin.com/oleticofab.md
2. https://hastebin.com/oxosufawad.md
3. https://hastebin.com/piwugiroto.md
4. https://hastebin.com/hotisuqoxu.md
5. https://hastebin.com/inikusovuq.md

**Comment by beardypig** [comment]
Inlife.bg, tvbulgare.bg and kanal3 are on cdn.netbadgers.com now, so I assume they have a static URL like the other channels in those other issues :)

**Comment by beardypig** [comment]
I cannot get http://mu-vi.tv/LiveStreams/pages/Live.aspx to work in my browser, does it work for you?

**Comment by roshavagarga** [comment]
It opens up for me, which probably means it's geolocked now? You can try using the nqma.net proxy.
A cursory glance didn't allow me to find the hls links in the page source, but either way if they've migrated they should be removed, yeah. Thanks for the hard work as always @beardypig
