### ISSUE TITLE
[bug] TVN new links not openable

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2903]
- [x] This is a bug report and I have read the contribution guidelines.

### Description
TVN.bg has moved its livestream links and the new ones can't be opened by the plugin.

### Reproduction steps / Explicit stream URLs to test
https://play.tvn.bg/TVNweb/embed.html?realtime=true

**Comment by bastimeyer** [comment]
Site uses websockets now. Requires a plugin rewrite.

**Comment by back-to** [comment]
static URL
`https://play.tvn.bg/TVNweb/index.m3u8`

**Comment by mkbloke** [comment]
That static URL is still working and it's not geo-IP blocked.  Does this mean the tvn plugin should be scheduled for removal, @back-to?
