### ISSUE TITLE
[bug] Tv1channel plugin no longer works

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2904]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

http://tv1channel.org/index.php/livetv fails to open. Stream seems to have moved away to a m3u8 link - either a quick fix or just remove the plugin as it is covered by one of the main plugins.

**Comment by bastimeyer** [comment]
This looks like it's a static HLS address, but I'm not sure because of the numbers:

```
$ streamlink -l debug 'https://tv1.cdn.netbadgers.com/bg060/bg061/bg061.m3u8'
[cli][debug] OS:         Linux-5.6.0-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1+113.g1b287a6
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin hls for URL https://tv1.cdn.netbadgers.com/bg060/bg061/bg061.m3u8
[plugin.hls][debug] URL=https://tv1.cdn.netbadgers.com/bg060/bg061/bg061.m3u8; params={}
[utils.l10n][debug] Language code: en_US
Available streams: 576p (worst, best)
```

The site you're linking is just embedding an iframe with this URL:
`https://tv1.cdn.netbadgers.com/`
The plugin was apparently built for that, but the content of the embedded site must have changed.

**Comment by roshavagarga** [comment]
It should bea static HLS address, I am a bit dubious about the numbers too, but I'm guessing that's just the 61st livestream they host? Maybe I can check back in X days and if the link is still the same - the plugin can be removed?

**Comment by roshavagarga** [comment]
@bastimeyer The links should be permanent. I managed to find another hosted channel, so I think this means the Tv1Channel plugin is no longer required.

Example: https://eurofolk.cdn.netbadgers.com/bg040/bg041/bg041.m3u8
