### ISSUE TITLE
[New Plugin] Add TV999

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2905]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
Bulgarian TV channel that mainly features Russian content with Bulgarian subtitles.

### Example stream URLs
http://tv999.bg/live.html

**Comment by mkbloke** [comment]
@roshavagarga, if you can test this and report back, it would be much appreciated, thanks.

https://github.com/streamlink/streamlink/blob/f2c98030a91b73b714c5295e3ca0cfe7f8308388/src/streamlink/plugins/tv999.py
