### ISSUE TITLE
[New Plugin] Add DTV

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2906]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
DTV, a.k.a. Diyana TV is a regional TV station (Yambol, Bulgaria). It can be considered a polythematic channel - featuring news, tv shows, documentaries, etc.

### Example stream URLs
1. http://dk-tv.com/dtv-%D0%BD%D0%B0-%D0%B6%D0%B8%D0%B2%D0%BE/
2. http://live.dk-tv.com

### Additional comments, screenshots, etc.
It seems to be using an HLS address, but opening that directly with streamlink doesn't work.
https://hastebin.com/ejejexirur.xml

**Comment by mkbloke** [comment]
You closed?  I thought this was probably a reasonable request and likely to be approved by the devs if a plugin was created...

**Comment by roshavagarga** [comment]
@mkbloke Honestly it's a small channel compared to TV999, isn't even available on satellite unlike the latter. I could open this up, but not sure it's worth the work :)

**Comment by mkbloke** [comment]
Fair enough.  There certainly isn't a shortage of new plugin requests.  :-D
