### ISSUE TITLE
[New Plugin] Add RMtv

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2908]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
RMtv is a regional cable television station for the region of Vratsa, Bulgaria. It features documentaries, news, tv shows, music videos and others.

### Example stream URLs
http://www.rmtv.bg/bg/gleday-na-zhivo

### Additional comments, screenshots, etc.
Event listener shows hls being used?

**Comment by back-to** [comment]
static livestream URL

`http://transcoder1.bitcare.eu/streaming/rimextv/rmtv.m3u8`
