### ISSUE TITLE
Support for live.me streams and VODs

### ISSUE THREAD

**Issue by clagnuts** [streamlink/streamlink#291]
Hi,

Not sure about the feasibility of this one since it's primarily an app for mobile/tablet devices. By sharing streams/VODs it's possible to obtain a link to view on the web (e.g. http://www.liveme.com/media/play/?videoid=14816926678104238297&area=A_US&countryCode=US&kid=2&shareto=twitter), though I believe that the video quality is lower than when streaming using the app. It'd be great to be able to watch streams and VODs using a desktop player, in full quality and without the garbage overlaid when following the links as above.

Anything you can do would be greatly appreciated.

**Comment by beardypig** [comment]
I can't ever get any to work on the website...

**Comment by beardypig** [comment]
Worked in Safari, nevermind...

**Comment by beardypig** [comment]
@clagnuts there is a liveme.com plugin in the latest nightly/git.

**Comment by clagnuts** [comment]
Thanks for your work on this. I've tried it on a few streams with generally positive results. There's a lot of buffering on the VODs (even using 5000ms buffer) but I suspect that's a site issue rather than a software one.

One issue I have run into is that when you copy links as they appear when opened via Twitter etc. and paste them into the command prompt, cmd will try to interpret the additional parameters as commands and return a bunch or errors before failing. It's fine as long as you know to delete everything after the videoid, but could throw some users.

To give one random example from Twitter pasted into cmd:

streamlink http://www.liveme.com/media/play/?videoid=14821048461820941579&area=A_US&countryCode=CA&kid=1&shareto=Twitter best
[cli][info] Found matching plugin liveme for URL http://www.liveme.com/media/play/?videoid=14821048461820941579
Available streams: live_alt, live (best, worst)
'area' is not recognized as an internal or external command,
operable program or batch file.
'countryCode' is not recognized as an internal or external command,
operable program or batch file.
'kid' is not recognized as an internal or external command,
operable program or batch file.
'shareto' is not recognized as an internal or external command,
operable program or batch file.

**Comment by beardypig** [comment]
Try with some quotes around the URL 

```
streamlink "http://www.liveme.com/media/play/?videoid=14821048461820941579&area=A_US&countryCode=CA&kid=1&shareto=Twitter" best
```

**Comment by gravyboat** [comment]
Yeah this seems like an issue with the `&` getting interpreted as some sort of break.
