### ISSUE TITLE
[New Plugin] Tiankov.com

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#2910]
## Plugin Request
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
Tiankov.com features two music livestreams for:
1. Traditional Bulgarian music
2. Orient-influenced Bulgarian music

### Example stream URLs
1. http://tiankov.com/watch-online/
2. http://tiankov.com/watch-online-2/

### Additional comments, screenshots, etc.
iframes for both streams: https://hastebin.com/adariyicex.js

**Comment by bastimeyer** [comment]
These requests are so specific that it's hardly useful to anyone (else), making implementation and maintenance of such a plugin highly questionable.

From what it looks like though, it also embeds an iframe with a simple player that requires a `Referer` header to be able to access it, just like the other Bulgarian channels covered by the cdnbg plugin, so it's possible that a simple regex and scheme addition could work. Whether it makes sense, I don't know.

**Comment by roshavagarga** [comment]
If the implementation would be incredibly tedious, consider it a dropped request. The only reason I thought that this could be added was because Bulgarian tv channels rarely change their websites and/or hosting, so plugins for them should not require maintenance that often.

**Comment by roshavagarga** [comment]
Request being dropped as nonessential.

**Comment by back-to** [comment]
@roshavagarga 

if you still want to use it with Streamlink,
you could try my generic plugin which will find most of the easy embed streams

```
$ streamlink -l info http://tiankov.com/watch-online/
[cli][info] Found matching plugin generic for URL http://tiankov.com/watch-online/
[plugin.generic][info]   1. URL=http://tiankov.com/watch-online/
[plugin.generic][info]   2. URL=https://player.neterra.tv/tiankov/tiankov-folk.php
[plugin.generic][info] Found Playlists: 1 (valid)
[cli][info] Available streams: 360p (worst, best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: /usr/bin/mpv

$ streamlink -l info http://tiankov.com/watch-online-2/
[cli][info] Found matching plugin generic for URL http://tiankov.com/watch-online-2/
[plugin.generic][info]   1. URL=http://tiankov.com/watch-online-2/
[plugin.generic][info]   2. URL=https://player.neterra.tv/tiankov/tiankov-orient.php
[plugin.generic][info] Found Playlists: 1 (valid)
[cli][info] Available streams: 360p (worst, best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: /usr/bin/mpv
```

https://raw.githubusercontent.com/back-to/generic/master/plugins/generic.py
https://github.com/back-to/generic/blob/master/plugins/generic.py

**Comment by roshavagarga** [comment]
@back-to Seems to work so well it even covers the other still-open plugin requests. I'm guessing this isn't included in the main repo because of possible DMCAs?
