### ISSUE TITLE
Twitch Gone for URL 401

### ISSUE THREAD

**Issue by 161134050** [streamlink/streamlink#2914]
Default install of streamlink returns 401 for Twitch.tv

Seems like it needs an access token,

Why doesn't streamlink include the default token (the one on twitch page?)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L44-L47
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L310
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L343

```
$ streamlink -l debug twitch.tv/esl_dota2
[cli][debug] OS:         Linux-5.6.0-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1+117.g1809c8f
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/esl_dota2
[plugin.twitch][debug] Getting live HLS streams for esl_dota2
[utils.l10n][debug] Language code: en_US
Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
```

**Comment by 161134050** [comment]
I just stood up a new EC2 instance running Ubuntu 16 and installed via apt-get

**Comment by 161134050** [comment]
Oh fantastic, it works!
