### ISSUE TITLE
plugins.twitch: fix API issue - 410 gone error

### ISSUE THREAD

**Issue by 161134050** [streamlink/streamlink#2915]
Expected result:
Streamlink works with twitch.tv by default

Actual result:
Streamlink doesn't work with twitch.tv by default

**Comment by pablos91** [comment]
same here

[cli][info] Found matching plugin twitch for URL twitch.tv/xxxxx
error: Unable to open URL: https://api.twitch.tv/api/channels/xxxxx/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xxxxxx/access_token.json?as3=t)

**Comment by bastimeyer** [comment]
> TEXT LOG OUTPUT IS REQUIRED for a plugin issue!
Use the `--loglevel debug` parameter and avoid using parameters which suppress log output.

https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/plugin_issue.md#L42-L49

> A bug is a *demonstrable problem* that is caused by the **latest version** of the code in the repository.

https://github.com/streamlink/streamlink/blame/master/CONTRIBUTING.md#L8

From your other comment:

> Ubuntu 16 and installed via apt-get

Packages for old distos will be outdated.

> If a package is not available on your platform, or if it's out of date, Streamlink can be installed via pip, the Python package manager.

https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

**Comment by pablos91** [comment]
```
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.19.76-linuxkit-x86_64-with-debian-9.8
[cli][debug] Python:     3.7.2
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/xxxx
[plugin.twitch][debug] Getting live HLS streams for xxxxx
error: Unable to open URL: https://api.twitch.tv/api/channels/xxxxx/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xxxxx/access_token.json?as3=t)
```

**Comment by bastimeyer** [comment]
> Streamlink: 1.0.0

Outdated. Use the **latest** release, which is currently `1.3.1`.
