### ISSUE TITLE
Twitch Collections (VOD Playlists)

### ISSUE THREAD

**Issue by zouhair** [streamlink/streamlink#2923]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Twitch for sometimes now has a playlist system they call Collections, which are just playlists of vods that the streamer creates.

[How to Use Collections](https://help.twitch.tv/s/article/how-to-use-collections?language=en_US) (Twtich Collections help page)

### Example stream URLs

1. https://www.twitch.tv/collections/ih0W0Ay7yxUK1Q?filter=collections
2. https://www.twitch.tv/collections/2tt-luNUuRWVOQ?filter=collections

**Comment by bastimeyer** [comment]
Streamlink isn't built for having multiple stream inputs, so implementing Twitch collections or similar playlist features doesn't make sense. It's also VOD based, which means it'll have limited usefulness anyway.

If you still want to use Twitch collections with Streamlink, you can write a wrapper script or application which selects the video you want to watch. See the Twitch API docs:
https://dev.twitch.tv/docs/v5/reference/collections#get-collection

related:
https://github.com/streamlink/streamlink/issues/2517#issuecomment-506883860
https://github.com/streamlink/streamlink/issues/444#issuecomment-273464290
