### ISSUE TITLE
Unknown signing key for release 1.4.0

### ISSUE THREAD

**Issue by amurzeau** [streamlink/streamlink#2929]
## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.

### Description

The latest release 1.4.0 is signed with the key `C85DFC2B93847AB978BB1476D70949F46BA8C77B` but it was `0xE3DB9E282E390FA0` for previous releases.

I'm being a bit picky here, but I can't find anything about that new key.
As part of the packaging for Debian, I'm verifying the signing key, so I would need the public key of the signing key (which I can't find on keyservers).

Is this release key change expected ?

### Expected / Actual behavior

Expected: the release 1.4.0 to be signed with the gpg key `0xE3DB9E282E390FA0 `
Actual behavior: the release is signed with a key `0xD70949F46BA8C77B` for which I can't find its public key for authentication.

### Reproduction steps / Explicit stream URLs to test

```
$ gpg --verify streamlink-1.4.0.tar.gz.asc streamlink-1.4.0.tar.gz
gpg: Signature made Wed Apr 22 19:56:35 2020 CEST
gpg:                using RSA key C85DFC2B93847AB978BB1476D70949F46BA8C77B
gpg: Can't check signature: No public key
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by amurzeau** [comment]
As I see on github actions logs for the release:

https://github.com/streamlink/streamlink/runs/609506084?check_suite_focus=true#step:8:54
```
 build: Signing sdist and wheel files
gpg: all values passed to '--default-key' ignored
set build/lib/streamlink/_version.py to '1.4.0'
gpg: keybox '/tmp/tmp.xoAXLRiBig/pubring.kbx' created
gpg: /tmp/tmp.xoAXLRiBig/trustdb.gpg: trustdb created
gpg: key D70949F46BA8C77B: public key "Streamlink <streamlink@protonmail.com>" imported
gpg: key D70949F46BA8C77B: secret key imported
```

So the key seems the expected new one but could you upload its public key somewhere ?

**Comment by bastimeyer** [comment]
> Is this release key change expected ?

No, the only change that was supposed to be done during the CI change in #2656 was a re-encryption of the old signing key that was created in #1701.

Unfortunately, I don't have this key, which is the reason why @beardypig has replaced the old encrypted key file with a new one in 7c044b0484ec7f409f909befc99089b57e79778f (as part of #2656).

https://github.com/streamlink/streamlink/pull/2656#discussion_r401669038

The signing scripts themselves haven't changed functionality-wise and the same key ID is set. So what's going on here? Is this a new subkey, @beardypig?

- 1.4.0
  - Key ID: https://github.com/streamlink/streamlink/runs/609506084?check_suite_focus=true#step:8:6
  - Key usage: https://github.com/streamlink/streamlink/blob/1.4.0/script/build-and-sign.sh#L54
  - Key import: https://github.com/streamlink/streamlink/runs/609506084?check_suite_focus=true#step:8:60
- 1.3.1
  - Key ID: https://github.com/streamlink/streamlink/blob/1.3.1/script/sdistsign.sh#L5
  - Key usage: https://github.com/streamlink/streamlink/blob/1.3.1/script/sdistsign.sh#L36
  - Key import: https://travis-ci.org/github/streamlink/streamlink/jobs/642601180#L3416

**Comment by bastimeyer** [comment]
I should have noticed that during the deploy test :disappointed: 

Test with custom keys:
https://github.com/bastimeyer-test/streamlink-test/runs/517255438?check_suite_focus=true#step:8:6

Test with real keys:
https://github.com/bastimeyer-test/streamlink-test/runs/555233316?check_suite_focus=true#step:8:6

----

https://github.com/streamlink/streamlink/runs/609506084?check_suite_focus=true#step:8:65

> gpg: all values passed to '--default-key' ignored

`$ man gpg`
>       --default-key name
>              Use name as the default key to sign with. If this option is not used, the default key is the first key  found  in  the  secret
>              keyring.   Note  that  -u  or --local-user overrides this option.  This option may be given multiple times.  In this case, the
>              last key for which a secret key is available is used.  If there is no secret key available for any of  the  specified  values,
>              GnuPG will not emit an error message but continue as if this option wasn't given.

So is this an entirely different key then, @beardypig?

**Comment by beardypig** [comment]
It should have been the same key.

**Comment by beardypig** [comment]
Of course, the key I have, that I thought was the real key is 
```
gpg: key D70949F46BA8C77B: public key "Streamlink <streamlink@protonmail.com>" imported
gpg: key D70949F46BA8C77B: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1

pub   rsa4096 2018-05-28 [SC]
      C85DFC2B93847AB978BB1476D70949F46BA8C77B
uid           [ unknown] Streamlink <streamlink@protonmail.com>
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/runs/616440947?check_suite_focus=true#step:8:58

https://github.com/streamlink/streamlink/releases/tag/1.4.1

**Comment by amurzeau** [comment]
Thanks !
