### ISSUE TITLE
itv player fails

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [streamlink/streamlink#2933]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When using itv player to stream I get the error Error while executing subprocess also error not found

### Reproduction steps / Explicit stream URLs to test

1. .../usr/local/bin/streamlink https://www.itv.com/hub/itv worst --player-external-http --player-external-http-port 23599 -l debug
2. .../usr/local/bin/streamlink https://www.itv.com/hub/itv2 worst --player-external-http --player-external-http-port 23599 -l debug
3. ...

### Log output

```
/usr/local/bin/streamlink https://www.itv.com/hub/itv worst --player-external-http --player-external-http-port 23599 -l debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.17
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Available streams: live (worst, best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:23599/
[cli][info]  http://185.247.117.123:23599/
[cli][info] Got HTTP request from VLC/3.0.8 LibVLC/3.0.8
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
[plugin.itvplayer][debug] XML data path: https://mediaplayer.itv.com/flash/playlists/ukonly/itv1.xml
[cli][info] Opening stream: live (rtmp)
[stream.streamprocess][debug] Spawning command: /usr/bin/rtmpdump --flv - --live --playpath itv1static@45475 --rtmp rtmpe://cp532701.live.edgefcs.net/live --swfVfy https://mediaplayer.itv.com/2.19.5%2Bbuild.a23aa62b1e/ITVMediaPlayer.swf
[cli][error] Could not open stream: Error while executing subprocess, error output logged to: /dev/null
^CInterrupted! Exiting...
```
LOG2
/usr/local/bin/streamlink https://www.itv.com/hub/itv2 worst --player-external-http --player-external-http-port 23599 -l debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-50-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     2.7.17
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin itvplayer for URL https://www.itv.com/hub/itv2
[plugin.itvplayer][debug] Video ID info response: {'AdditionalInfo': {'Message': None}, 'Playlist': {'VideoType': u'SIMULCAST', 'Video': {'Base': u'https://dotcom-itv2-hls.akamaized.net/hls/live/', 'MediaFiles': [{'Href': u'626380/itvlive/itv2/master.m3u8?hdnea=st=1587839941~exp=1587861541~acl=/*~data=nohubplus~hmac=af7ac8d7952154581bf47d17286d7feb2b3e5d0b42f5e66731a69159e6676473', 'KeyServiceUrl': None}], 'Subtitles': None}}, 'StatusCode': 200}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 615k (worst), 660k, 818k, 880k, 1222k, 1320k, 1526k, 1650k, 1830k, 1980k (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:23599/
[cli][info]  http://185.247.117.123:23599/
[cli][info] Got HTTP request from VLC/3.0.8 LibVLC/3.0.8
[cli][info] Opening stream: 615k (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Could not open stream: Unable to open URL: https://dotcom-itv2-hls.akamaized.net/hls/live/626380/itvlive/itv2/master_Main600.m3u8 (404 Client Error: Not Found for url: https://dotcom-itv2-hls.akamaized.net/hls/live/626380/itvlive/itv2/master_Main600.m3u8)
[plugin.itvplayer][debug] Video ID info response: {'AdditionalInfo': {'Message': None}, 'Playlist': {'VideoType': u'SIMULCAST', 'Video': {'Base': u'https://dotcom-itv2-hls.akamaized.net/hls/live/', 'MediaFiles': [{'Href': u'626380/itvlive/itv2/master.m3u8?hdnea=st=1587839973~exp=1587861573~acl=/*~data=nohubplus~hmac=e537ef1486198e2ff2dba0f0cc85cd35d45577339975ef433418121d8493b02d', 'KeyServiceUrl': None}], 'Subtitles': None}}, 'StatusCode': 200}
[utils.l10n][debug] Language code: en_US
[cli][info] Opening stream: 615k (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Could not open stream: Unable to open URL: https://dotcom-itv2-hls.akamaized.net/hls/live/626380/itvlive/itv2/master_Main600.m3u8 (404 Client Error: Not Found for url: https://dotcom-itv2-hls.akamaized.net/hls/live/626380/itvlive/itv2/master_Main600.m3u8)
[plugin.itvplayer][debug] Video ID info response: {'AdditionalInfo': {'Message': None}, 'Playlist': {'VideoType': u'SIMULCAST', 'Video': {'Base': u'https://dotcom-itv2-hls.akamaized.net/hls/live/', 'MediaFiles': [{'Href': u'626380/itvlive/itv2/master.m3u8?hdnea=st=1587839976~exp=1587861576~acl=/*~data=nohubplus~hmac=cebdac4a123cd01c330c1546575c92814b6b4326770ce2ddb0926fbef604be54', 'KeyServiceUrl': None}], 'Subtitles': None}}, 'StatusCode': 200}
[utils.l10n][debug] Language code: en_US
[cli][info] Opening stream: 615k (hls)
[stream.hls][debug] Reloading playlist

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Unfortunately, the ITV player plugin has been broken for some time now, due to their implementation of DRM on the streams.  See:

https://github.com/streamlink/streamlink/issues/2718
https://github.com/streamlink/streamlink/issues/2727

**Comment by gravyboat** [comment]
Yep as mkbloke noted they added DRM and we don't circumvent DRM so I'm going to close this one out, we should probably remove the plugin from the next release.
