### ISSUE TITLE
Integration into website

### ISSUE THREAD

**Issue by nOLanSea** [streamlink/streamlink#2940]
Hello.

The main problem API afreeca most probably has been changed, so embed doesn't work. For example https://tl.net/video/streams/rlaxordyd (or stream stream online)

I'd like, afreeca stream to be opened in website by integrated vlc player (or other) via streamlink.
Is it possible to integrate streamlink into website ?

Thx in advance for help.

**Comment by bastimeyer** [comment]
> stream to be opened in website by integrated vlc player (or other) via streamlink

This is not how either VLC or Streamlink works. Streamlink is built for watching streams in your local player and not in your web browser.

> Is it possible to integrate streamlink into website ?

A client could connect to a streamlink HTTP server via --player-external-http (#2525), but this is very limited, will result in a poor experience and you'd certainly violate the site's ToS by rehosting content.
