### ISSUE TITLE
support for rtsp protocol

### ISSUE THREAD

**Issue by j00zek** [streamlink/streamlink#2942]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Many web services (E.g. webcamera's) is using rtsp protocol to stream the video. The rtsp protocol can be easily catch by ffmpeg. 
The example:
ffmpeg -i 'rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov'

### Expected / Actual behavior

Is there any chance to implement support for the rtsp protocol?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Can you explain some use cases for this? Seems pretty problematic to me for anyone who is maliciously scanning for open web cam streams that weren't securely set up and we don't want to be involved in that. We primarily want to support sites that offer live streaming, if it's an embedded webcam for a site that makes more sense, but I'm having a hard time understanding valid use cases for this that fall in to Streamlink's stated goals.

**Comment by j00zek** [comment]
Imagine the situation you own a camera which scans area arround entry gate to your house or  parking nearby your house. Currently, the only way to check what's happening is to use a dedicated app on a computer or mobile. Somehow works, but is not convenient to use if you need to frequently look at it. (E.g. you're waiting for guests) Much better would be to have an option to see the camera stream on the TV (E.g. in PIP window), by choosing it from the list, like other streams.

Makes sense?

**Comment by gravyboat** [comment]
It makes sense, I just don't see how it fits in to what Streamlink is focused on.

**Comment by j00zek** [comment]
Isn't streamlink an utility to pipe  video streams from various services into a video player?
Isn't mainpurpose of it to allow the user to enjoy various streamed content?

If so, I do see perfect fit, because support for rtsp protocol is missing at the moment. As for other sources, it's the first step with probable need to have a plugin for logins or so, but without having working rtsp source all is blocked, unfortunatelly. :(

**Comment by back-to** [comment]
you are trying to do easy stuff complicated by using streamlink
your example don't make any sense for me

---

just use the rtsp stream with your TV or setup a PC with a VMS camera software

example for **DAHUA** cams
https://dahuawiki.com/Remote_Access/RTSP_via_VLC
other cams have similar features

**Comment by j00zek** [comment]
Thanks for your rejection. I made it myself. It wasn't so hard and so complicated as you think.

**Comment by creited** [comment]
@j00zek I would be very grateful to hear from you your workaround.

**Comment by KnIfER** [comment]
Simply use https://github.com/AlexxIT/go2rtc  to get stream.m3u8 for your rtsp url.

This way, combined with my flv downloader script,  I can download the steam and preview it at any time. The seek speed would be very fast because the flv header is handled by the flv downloader.
