### ISSUE TITLE
BT Sports plugin error

### ISSUE THREAD

**Issue by chipgomez** [streamlink/streamlink#2946]
## Plugin Issue
The link of the BT Sports livestream has changed.
https://sport.bt.com/btsportplayer/bt-sport-1-01363810201090
to
https://www.bt.com/sport/watch/live-now/bt-sport-1
BT Sports plugin not able to handle the new link.

### Description
Plugin not able to handle the new link.

### Additional comments, screenshots, etc.
https://i.imgur.com/sWwisTv.png
Can someone fix and update the bt sports plugin?

**Comment by whittinghamj** [comment]
This issue is not even worse because the login process no longer works either.

**Comment by mkbloke** [comment]
I don't have a BT Sports subscription, so I'm pretty limited as to what I can do to help fix this, but I have made some changes which might help things along a bit.  The plugin is here:

https://github.com/mkbloke/streamlink/blob/btsports/src/streamlink/plugins/btsports.py

It would be a bit of a miracle if it just works.  Hopefully it might be useful for others to build on.  If anybody with a BT Sports subscription can test and report back, I'd be interested to hear about it.  Cheers.

**Comment by mkbloke** [comment]
I've marked the above comment as outdated.  Just ignore it for now, while I figure things out...

**Comment by mkbloke** [comment]
OK, I've unhidden the comment above now that I've pushed a small fix to get it working correctly on both Py2 and Py3.

**Comment by jbarry786** [comment]
> 
> 
> OK, I've unhidden the comment above now that I've pushed a small fix to get it working correctly on both Py2 and Py3.

Thanks for the work on this. Is the plugin currently working?

I can login fine on the site and play the streams, trying the following link: https://www.bt.com/sport/watch/live-now/bt-sport-1

But I get this error using the plugin:
```> 
C:\Windows\system32>streamlink "https://www.bt.com/sport/watch/live-now/bt-sport-1"
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.6.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin btsports for URL https://www.bt.com/sport/watch/live-now/bt-sport-1
[cli][debug] Plugin specific arguments:
[cli][debug]  --btsports-email=XXX (email)
[cli][debug]  --btsports-password=******** (password)
[plugin.btsports][debug] Logging in as XXX
[plugin.btsports][debug] Redirected to: https://strongauth.secure.bt.com/arcotafm/cap/master.jsp?profile=afmpcapo
skANdDXthAcYq1jTffg7Qz76TLWzWsmfX4Vw6VnhEsCgv&TARGET=$SM$https%3a%2f%2fhome.bt.com%2fss%2fSatellite%2fsecure%2flo
[plugin.btsports][debug] Login successful, getting SAML token
[plugin.btsports][error] Login failed.
error: No playable streams found on this URL: https://www.bt.com/sport/watch/live-now/bt-sport-1
```

**Comment by mkbloke** [comment]
@jbarry786, thanks for coming back on this.  I don't have a BT Sports subscription, but even without one, it's possible I can fix this a bit more.  I'll have another look at it and post here when I push changes to the branch.  Thanks.

**Comment by back-to** [comment]
create a pull request if it is fixed,
if it can't be fixed because there is no account the plugin can be removed.

**Comment by mkbloke** [comment]
It's not fixed and it's likely I cannot fully fix it.  I have a BT account, but not a BT Sports subscription.  I was hoping to get the plugin back to the point where it would at least login properly with BT account credentials, but that still needs some work and I've just not got back to it working on it.
