### ISSUE TITLE
Plugin 'Atresmedia' broken

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#2954]
The plugin `atresmedia` can be considered broken as they are using tokens and a 'premium membership' now. They are also detecting VPNs, leading to the message: 
_You are browsing with a VPN service
Deactivate it and subscribe to PREMIUM INTERNACIONAL now to enjoy ATRESplayer outside of Spain._

:-(

Example: 
[https://www.atresplayer.com/directos/antena3/](https://www.atresplayer.com/directos/antena3/)

**Comment by back-to** [comment]
the plugin itself works, try using cookies for premium content

**Comment by malvinas2** [comment]
Spanish mates step forward! 
I am located in Germany and can't verify anything here as I won't pay 5 Euros per month.

**Comment by back-to** [comment]
@malvinas2 
you don't really need a Streamlink Plugin for this, they use static URLs which can be used

https://github.com/jorgemitcom/multipantalla/blob/475ba4ff8100771a4b59e81bca9844ba417ed26a/multipantalla_a3.html#L27

https://github.com/search?q=https%3A%2F%2Flivestartover.atresmedia.com%2Fgeo&type=Code

`https://livestartover.atresmedia.com/` is there domain

**Comment by malvinas2** [comment]
You're right, until now the limitations just concern _Atreseries_; probably it will be only a matter of time before more and more channels of the media group get restricted access. 
[https://github.com/LaQuay/TDTChannels/blob/master/TELEVISION.md](https://github.com/LaQuay/TDTChannels/blob/master/TELEVISION.md)

**Comment by malvinas2** [comment]
_Unfortunately, Mediaset has added token protection to its streams. This implies that they will not be available from now on the M3U / M3U8 lists, it is not our fault, call Mediaset, not us. In addition, they have closed streams to Geolocalized, so that from the web it can only be seen in Spain.
In addition, Atresmedia is also making changes. It has completely closed the M3U8 streams from Mega and Atreseries. Now only available through its website and also georeferenced._

Source (translated by Google): [Canal no funciona: Mediaset (Telecinco, Cuatro,BeMad,etc) #734](https://github.com/LaQuay/TDTChannels/issues/734)
