### ISSUE TITLE
Can't find configuration file or folder

### ISSUE THREAD

**Issue by OLucasZanella** [streamlink/streamlink#2955]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I want to set _mpv_, _best_ and _--player-passthrough hls_ as the default, but I can't, for the life of me, find the configuration file or folder. There's no "streamlinkrc" in my computer and there's no "streamlink" folder inside .config.

I also tried using "--config FILENAME", but all it does is say the "usage" line. When, on a whim, I decided to keep the "filename" part and add the file path afterwards, it just says "no plugin can handle it".

### Log output

```
[cli][debug] OS:         Linux-5.6.10-3-MANJARO-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
```

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#configuration-file

> Streamlink will look for config files in different locations depending on your platform:
> 
> Platform | Location
> -- | --
> Unix-like (POSIX) | $XDG_CONFIG_HOME/streamlink/config
> Windows | %APPDATA%\streamlink\streamlinkrc

> Note
> **On Windows there is a default config created by the installer but on any other platform you must create the file yourself.**

----

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by OLucasZanella** [comment]
If I understand that correctly, it's saying I should find what I'm looking for inside $HOME/.config, but there's nothing there, as I've said. Creating the directory and putting a file called "streamlinkrc" there didn't do anything, unless I'm doing something wrong.

**Comment by bastimeyer** [comment]
The file inside `$XDG_CONFIG_HOME/streamlink` or `$HOME/.config/streamlink` is called `config`, not `streamlinkrc`. You have to follow the documentation precisely, hence why I quoted it.

`$HOME/.streamlinkrc` is the legacy config file path and should not be used, as it violates the XDG base directory specification and may get removed in a future release.

https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink_cli/constants.py#L27-L31

**Comment by OLucasZanella** [comment]
Thanks. I thought `config` would be another folder, so there's that.

Everything's working now. Can't find a way to automatically choose best quality, if it exists, but that's minor.
