### ISSUE TITLE
Plusgin throwing SSL Error: [SSL: DH_KEY_TOO_SMALL]

### ISSUE THREAD

**Issue by davidyu0728** [streamlink/streamlink#2959]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.

### Description

I am using the streamlink on a raspberry pi 4, and by some websites have the error about ssl. And It seems a common problem on raspberry pi.

### Reproduction steps / Explicit stream URLs to test

1. streamlink https://www.showroom-live.com/018d71447406 -l debug

(The url is only for testing. It can be replace by any Live on Showroom)

### Log output

```
[cli][debug] OS:         Linux-4.19.97-v7l+-armv7l-with-debian-10.3
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.4.1+5.g3f24fde
[cli][debug] Requests(2.21.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin showroom for URL https://www.showroom-live.com/018d71447406
error: Unable to open URL: https://www.showroom-live.com/018d71447406 (HTTPSConnectionPool(host='www.showroom-live.com', port=443): Max retries exceeded with url: /018d71447406 (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)'))))
```

### Additional comments, screenshots, etc.
I think this problem only on raspberry pi with some website. On normal Linux or Windows is working fine. It seems can be solved by setting some parameter for ssl.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by davidyu0728** [comment]
I try to modify the source code in /streamlink/plugin/api/http_session.py add the

```
urllib3.util.ssl_.DEFAULT_CIPHERS += 'HIGH:!DH:!aNULL'
```
after 
```
try:
    from requests.packages import urllib3

    # We tell urllib3 to disable warnings about unverified HTTPS requests,
    # because in some plugins we have to do unverified requests intentionally.
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
except (ImportError, AttributeError):
    pass
```
and seems the problem is solved.

**Comment by karlo2105** [comment]
No need to change anything just add this command --http-disable-dh
