### ISSUE TITLE
Add streamlink portable download links to the docs and readme

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#296]
We need to add the portable release link to the docs and the main streamlink readme so people know they can install that if they want.

**Comment by mmetak** [comment]
https://github.com/mmetak/streamlink/commit/8e2a3991f0637ebb0ac243a1ab3ad413ed0121a4    what should be changed @gravyboat?

**Comment by beardypig** [comment]
@mmetak looks accurate to me :) 

As a side note, I created a bash version of a portable Streamlink builder: [beardypig/streamlink-portable](https://github.com/beardypig/streamlink-portable), it builds with travis daily, and uploads zips to s3.

**Comment by gravyboat** [comment]
@beardypig Do you want to move that repo to the main streamlink organization under something like `streamlink-portable-nightly` or something? Or do you need to keep it on your page due to S3 upload creds?
