### ISSUE TITLE
Download m3u8 using Python API

### ISSUE THREAD

**Issue by mightymercado** [streamlink/streamlink#2960]
I understand that you can download m3u8 streams and convert them to, say, mkv using streamlink CLI. I want to know if this is possible using the Python API? So far I only know how to setup streamlink session with the desired options using `set_options` and print the stream URL. However I don't know how to "download" the stream into a file, the same way the CLI version does.

``` 
from streamlink import Streamlink
import streamlink

session = Streamlink()
session.set_option('https-proxy', '...')
session.set_option('http-cookies', '...')
streams = session.streams("https://.....m3u8")
print(streams['best'])
```

**Comment by mightymercado** [comment]
I figured how to do it using functions from streamlink_cli. 

```
stream_fd, prebuffer = open_stream(streams['best'])

output = FileOutput('output.ts')
output.open()
read_stream(stream_fd, output, prebuffer)

stream_fd.close()
output.close()
```

**Comment by swivelsoftware-hong** [comment]
@mightymercado how to import those methods, seems like both streamlink_cli and streamlink is not exporting those
