### ISSUE TITLE
[New Plugin] Add Viki.com

### ISSUE THREAD

**Issue by marlenexxx** [streamlink/streamlink#2961]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Its streaming site just like abematv.

### Example stream URLs

1. https://www.viki.com/videos/1162022v-a-virgin-woman-of-literature-episode-1
2. https://www.viki.com/videos/1165864v-is-this-love-checkmate-meeting-episode-1

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.
