### ISSUE TITLE
DLive plugin error

### ISSUE THREAD

**Issue by Colbix** [streamlink/streamlink#2965]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

When using streamlink, version 1.4.1, I receive an error with the DLive plugin. It doesn't matter which link is provided from what I can determine. I suspect a format change may have occurred which is affecting the parsing.

The reproduction URL is just a random link all links appear to produce the same error.

### Reproduction steps / Explicit stream URLs to test

1. Open the command prompt 
2. Type streamlink https://dlive.tv/MemesDidit worst
3. Receive an error: [cli][info] Found matching plugin dlive for URL https://dlive.tv/MemesDidit
error: Could not find username.

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dlive for URL https://dlive.tv/MemesDidit
error: Could not find username
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Can you test the URL you provided above again, please, @Colbix?

I've tested the URL you provided and cannot reproduce the error.  I have also tested other URLs on dlive and all seem to be working OK right now.  I did run into issues with vlc as a player, where mpv worked instead, but that's a completely different thing.  I'm using streamlink master, but as the dlive plugin has not changed at all since release 1.4.1, in theory that shouldn't make any difference.

Cheers.

**Comment by Colbix** [comment]
Odd, it's working now. Maybe an issue on the server end. Sorry to bother you, can marked as resolved.

**Comment by Robby-** [comment]
Seems this issue is happening again, as I'm getting the following error:
`error: Could not find username`

Not sure how long this has been an issue again though, since I do not watch DLive much.

I'm using Streamlink version 1.6.0 on Windows 10.

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

As requested in the plugin issue template:

- [ ] Description and/or reproduction steps are insufficiently detailed
- [ ] Streamlink version in use not specified
- [ ] Full ```--loglevel debug``` log output not provided
- [x] Research of prior issues/fixes appears to be insufficient [1]

Other feedback:
- [ ] Issue is out of scope and/or should be reported/help sought elsewhere
- [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
- [ ] User appears to be using an outdated Streamlink version/plugin [2] [3]
- [x] Other (see below)

- Other: Please don't report issues on previously closed issues.

See: #3239

~~Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.~~

[1] [Search all open/closed issues/pull requests](https://github.com/streamlink/streamlink/issues?q=)
[2] [Install the most recent version of Streamlink](https://streamlink.github.io/install.html)
[3] [Check the master branch for plugin updates](https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins)
