### ISSUE TITLE
filmon plugin broken not related to the url issue

### ISSUE THREAD

**Issue by jamiejacksoncumbria** [streamlink/streamlink#2966]
## Plugin Issue

<Filmon plugin does not work anymore. Say channel sleep and then come up with an error.>
- [ ] This is a plugin issue and I have read the contribution guidelines.

### Description
Filmon plugin does not work anymore. Say channel sleep and then come up with an error.
<Filmon plugin does not work anymore. Say channel sleep and then come up with an error. >

### Reproduction steps / Explicit stream URLs to test

1.  streamlink http://www.filmon.com/tv/itv1 high --player-external-http --player-external-http-port 23555 --player-continuous-http -l debug
2. ...
3. ...

### Log output

```
streamlink http://www.filmon.com/tv/itv1 high --player-external-http --player-external-http-port 23555 --player-continuous-http -l debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin filmon for URL http://www.filmon.com/tv/itv1
[plugin.filmon][debug] Found cached channel ID: 11
[plugin.filmon][debug] channel sleep 0
[plugin.filmon][debug] channel sleep 1
[plugin.filmon][debug] channel sleep 2
[plugin.filmon][debug] channel sleep 3
[plugin.filmon][debug] channel sleep 4
[plugin.filmon][debug] Reset cached channel: itv1
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/streamlink_cli/main.py", line 1024, in main
    handle_url()
  File "/usr/local/lib/python3.6/dist-packages/streamlink_cli/main.py", line 585, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python3.6/dist-packages/streamlink_cli/main.py", line 465, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "/usr/local/lib/python3.6/dist-packages/streamlink/plugin/plugin.py", line 323, in streams
    ostreams = list(ostreams)
  File "/usr/local/lib/python3.6/dist-packages/streamlink/plugins/filmon.py", line 245, in _get_streams
    data = self.api.channel(_id)
  File "/usr/local/lib/python3.6/dist-packages/streamlink/plugins/filmon.py", line 161, in channel
    return self.session.http.json(res, schema=self.api_schema)
UnboundLocalError: local variable 'res' referenced before assignment```


### Additional comments, screenshots, etc.
on stream link 1.3.1 i get this error looks like they may of changed the api.
jamie@jamie-Lenovo-Yoga-500-15IHW:~$ streamlink https://www.filmon.com/channel/itv1 low --player-external-http --player-external-http-port 23555 --player-continuous-http -l debug
[cli][debug] OS:         Linux-4.15.0-20-generic-x86_64-with-debian-buster-sid
[cli][debug] Python:     3.7.1
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.57.0)
[cli][info] Found matching plugin filmon for URL https://www.filmon.com/channel/itv1
[plugin.filmon][debug] Found channel ID: 11
[plugin.filmon][debug] Reset cached channel: itv1
error: Unable to open URL: http://www.filmon.com/api-v2/channel/11?protocol=hls (504 Server Error: Gateway Time-out for url: http://www.filmon.com/api-v2/channel/11?protocol=hls)
jamie@jamie-Lenovo-Yoga-500-15IHW:~$ 


[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by worldmediaman** [comment]
i have add the new file from here https://raw.githubusercontent.com/streamlink/streamlink/fe7228e804d3764ec5dc2147ab1e6cec99ff8e71/src/streamlink/plugins/filmon.py

 and have this output here:

[cli][info] Found matching plugin filmon for URL https://www.filmon.com/tv/itv1
error: Unable to find 'self.api.channel' for 11

**Comment by mkbloke** [comment]
It would seem there are consistent gateway time-outs on ```http://www.filmon.com/api-v2/channel/{0}?protocol=hls``` now.

**Comment by jamiejacksoncumbria** [comment]
Confirmed 
Unable to open URL: http://www.filmon.com/api-v2/channel/itv1?protocol=hls (504 Server Error: Gateway Time-out for url: http://www.filmon.com/api-v2/channel/itv1?protocol=hls)

**Comment by mkbloke** [comment]
The substituted value is a number, by the way.  For ITV1 that number is currently 11.

I've tried some different URLs, but they all seem to present the same issue.

For the time being, you can get most of the free to view channels you're watching with FilmOn via the tvplayer plugin (tvplayer.com).

**Comment by jamiejacksoncumbria** [comment]
Thanks for the advice.

 Many Thanks

**Comment by mkbloke** [comment]
I think FilmOn may have fixed whatever it was that broke.  I've tried a few channels and it seems all is working again.  Is it working for any of you now?

**Comment by jamiejacksoncumbria** [comment]
I can confirm all seems to be working again. Seems it must of been an issue
from filmon's side. This bug should be closed. It's not a bug any more.
