### ISSUE TITLE
cache aljazeera

### ISSUE THREAD

**Issue by OrionRandD** [streamlink/streamlink#2967]
When I open Aljazeera with streamlink it does not play the live session, but cached sessions. How do I solve this issue?

$ streamlink 'https://www.aljazeera.com/live/'

My ~/.config/streamlinkrc    is:

-> Player options
player=mpv --cache 2048 --ontop --no-border --force-window --autofit=500x280 --geometry=-15-60
-> player=mpv --cache 2048
player-no-close
-> default-stream=720p,1080p,420p,medium,best
default-stream=420p

-> equals commented lines

**Comment by bastimeyer** [comment]
> ~/.config/streamlinkrc

Not a valid config path.
Valid paths are `${XDG_CONFIG_HOME:-$HOME}/streamlink/config` or `$HOME/.streamlinkrc`.
https://streamlink.github.io/cli.html#configuration-file

> does not play the live session, but cached sessions

Post a **debug log** of the stream URL and quality you're trying to watch, just like the **plugin issue** template asks you to do.
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/plugin_issue.md#L31-L54

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
