### ISSUE TITLE
tvplayer.com

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#2968]
## plugin request

<! - Replace [] with [x] to activate the check box ->
- [#] This is a plugin request and I have read the post guidelines and plugin request requirements.

### Description

<! - Explain the plugin and the site as clearly as possible. What is the website about? Who runs it? What content does it offer? What is the value of Streamlink? Etc. ->

As an alternative for FilmON to watch English speaking channels

### Example of stream URLs

<! - Sample URLs for streams are required. Plugin requests without sample URLs are closed. ->

1. https://tvplayer.com/watch/bbctwo
 

### Additional comments, screenshots, etc.

Account must be created, live streaming is free

[Love streamlink? Please remember to support our collective. Thanks!] (Https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/tvplayer.py

**Comment by worldmediaman** [comment]
@bastimeyer Thanks
