### ISSUE TITLE
Using the latest nightly and noticed this double url thing happening

### ISSUE THREAD

**Issue by thinkpad4** [streamlink/streamlink#297]
http://i.imgur.com/mY5eUcH.jpg It doesn't happen every time, I would guess 60% to 70% of the time it DOES happen.  I noticed the double url after installing the latest nightly.  It started yesterday Dec 13th

It goes like this, I type
streamlink twitch.tv/crream best
then it prints
http://twitch.tv/crream
http://twitch.tv/crream 
then starts loading the plugin

**Comment by beardypig** [comment]
Ah, the perils of the bleeding edge... It's been fixed as part of #292 :)

**Comment by gravyboat** [comment]
Going to close since I've merged the associated PR. Thanks for catching this @thinkpad4, and thanks for the update @beardypig.
