### ISSUE TITLE
Showroom [stream.hls][error] and sync issues

### ISSUE THREAD

**Issue by bandicootdancing** [streamlink/streamlink#2972]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I'm getting this error multiple times throughout all showroom streams I want to download using streamlink 1.4.1+5.g3f24fde. Oddly enough a few random profiles I've tried have worked with a usable output file.
``
[stream.hls][error] Failed to open segment 1137: Unable to open URL: https://hls
-cdn240-showroom.cdn-dena.com/liveedge/17b4b6a7fb6d7c6da9b7932ea97af277dffcd79697a6833928b38a1a6cb30e09/media_1137.ts (404 Client Error: Not Found for url: https://hls-cdn240-showroom.cdn-dena.com/liveedge/17b4b6a7fb6d7c6da9b7932ea97af277dffcd79697a6833928b38a1a6cb30e09/media_1137.ts)``

Streamlink starts the capture but every few minutes I see the error above. After about 30 seconds the capture will start again. In a single stream the error comes up between 5-15 times resulting in an equal amount of output videos for the stream. After the stream is done each video gradually de-syncs. 

### Expected / Actual behavior

Download the stream all the way through with synced video and audio. 

### Reproduction steps / Explicit stream URLs to test

1. Use streamlink to download ``streamlink https://www.showroom-live.com/twinklemisaki best --output "$(date +%Y%m%d_%H%M%S)-み〜ちゃんビーム♡.ts"``
2. Monitor console - Some streams complete with a usable file and others fail every few minutes resulting in 5-10 parts.
3. Streams that result in multiple parts have de-synced audio so it's not even worth merging the files with ffmpeg. 

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
there servers are to slow for your location

use `--hls-segment-thread 10`

https://streamlink.github.io/cli.html#command-line-usage

**Comment by bandicootdancing** [comment]
Thanks for the tip. I'll try that out and report back with any issues.
