### ISSUE TITLE
Chatterino/macos: Unable to find streamlink executable

### ISSUE THREAD

**Issue by NatalieGates** [streamlink/streamlink#2975]
## Issue

- [x ] This is not a bug report, feature request, or plugin issue/request.
- [ x] I have read the contribution guidelines.

### Description

I want to use chatterino to open a twitch stream. In chatterino, when I click on "open in streamlink" I am given a popup that says "unable to find streamlink executable Make sure your custom path is pointing to the DIRECTORY where the streamlink executable is located." I'm using macos and am not sure what to do. I do not know how to create a config file or even what that means. I am able to open a stream using terminal. I simply type `streamlink twitch.tv/my-fav-stream best` and it works magically. 

I realize I could simply open terminal each time, but like the ideal of having chatterino do that work for me.

I'm not very tech savvy so I'm wondering if someone could give me step-by-step instructions how to get this working in macos?

<img width="344" alt="Screen Shot 2020-05-14 at 9 59 12 AM" src="https://user-images.githubusercontent.com/47909481/81945954-c3427180-95cc-11ea-8373-f6bda538d842.png">

**Comment by bastimeyer** [comment]
Not a Streamlink issue. Streamlink has nothing to do with Chatterino. If you're having a problem with Chatterino, you need to ask the Chatterino devs.
