### ISSUE TITLE
Terminate Stream when segment fails downloading?

### ISSUE THREAD

**Issue by mightymercado** [streamlink/streamlink#2977]
Is there a way to terminate m3u8 stream download when at least one segment fails to download? Instead of just continuing to stream the following segments?

**Comment by back-to** [comment]
> Is there a way to terminate m3u8 stream download when at least one segment fails to download? 

there is none

**Comment by mightymercado** [comment]
Is there a possible solution if I needed to this?

**Comment by back-to** [comment]
> Is there a possible solution if I needed to this?

You can change some timeout settings to close Streamlink faster

https://streamlink.github.io/cli.html#stream-options

but **Streamlink is doing the opposite** of your wish,
it will try to reload playlists as long as possible and skip broken segments.

closing, probably not possible.
