### ISSUE TITLE
[Plugin]youtube is broken

### ISSUE THREAD

**Issue by jjsly11** [streamlink/streamlink#2978]
thanks for reading !
LOG:
root@iZt4nh6f07nqgx0vjhuedwZ:~# streamlink --loglevel debug https://www.youtube.com/watch?v=MJDrNi6fJbw best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.14.129-bbrplus-x86_64-with-debian-9.6
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MJDrNi6fJbw
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: MJDrNi6fJbw
error: Unable to open URL: https://youtube.com/get_video_info (429 Client Error: unknown for url: https://youtube.com/get_video_info?video_id=MJDrNi6fJbw&el=detailpage)

**Comment by back-to** [comment]
```
$ streamlink https://www.youtube.com/watch?v=MJDrNi6fJbw -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=MJDrNi6fJbw
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: /usr/bin/mpv
```

> HTTP Error 429: Too Many Requests

your IP is just blocked by Youtube.
