### ISSUE TITLE
ABEMA

### ISSUE THREAD

**Issue by lidoworld** [streamlink/streamlink#2986]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

It seems that support for ABEMA has failed

### Reproduction steps / Explicit stream URLs to test

https://abema.tv/now-on-air/special-plus

### Log output

```
C:\Users\*\Desktop>streamlink https://abema.tv/now-on-air/special-plus best -o output.ts
[cli][info] Found matching plugin abematv for URL https://abema.tv/now-on-air/special-plus
[cli][info] Available streams: 180p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: abematv-license://APmuyv5mw96QD9uBNwNMgTii8tKxouAFEAr3N3Hvb5of (Unable to open URL: https://license.abema.io/abematv-hls (403 Client Error: Forbidden for url: https://license.abema.io/abematv-hls?t=3BergSCzQsuUPEU5MC6DYTmy6foVcxe5nP7yW8QJhqmV3XU7YU38MmwLfSVJ6qqBE7joinr3q4iqqU4qktV7dWaj54Y3eh9SH2zsxZytVueSR4D9sLqMK1dDBrEcDCApSq1zsrg4))
[cli][error] Try 1/1: Could not open stream <HLSStream('https://ds-linear-abematv.akamaized.net/channel/special-plus/1080/playlist.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://ds-linear-abematv.akamaized.net/channel/special-plus/1080/playlist.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://abematv.akamaized.net/region
https://ds-glb-linear-abematv.akamaized.net/region

can you open both websites?

---

works for me, maybe it was a temporary issue.

```
$ streamlink https://abema.tv/now-on-air/special-plus worst -l debug
[cli][debug] OS:         Linux-5.4.0-33-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin abematv for URL https://abema.tv/now-on-air/special-plus
[plugin.abematv][debug] URL=https://ds-linear-abematv.akamaized.net/channel/special-plus/playlist.m3u8
[utils.l10n][debug] Language code: en_GB
[cli][info] Available streams: 180p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 180p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 150010; Last Sequence: 150013
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 150011; End Sequence: None
[stream.hls][debug] Adding segment 150011 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 150012 to queue
[stream.hls][debug] Adding segment 150013 to queue
[stream.hls][debug] Download of segment 150011 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format https://abema.tv/now-on-air/special-plus -
```

**Comment by lidoworld** [comment]
> https://abematv.akamaized.net/region
> https://ds-glb-linear-abematv.akamaized.net/region
> 
> can you open both websites?
> 
> works for me, maybe it was a temporary issue.
> 
> ```
> $ streamlink https://abema.tv/now-on-air/special-plus worst -l debug
> [cli][debug] OS:         Linux-5.4.0-33-generic-x86_64-with-glibc2.29
> [cli][debug] Python:     3.8.2
> [cli][debug] Streamlink: 1.4.1
> [cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
> [cli][info] Found matching plugin abematv for URL https://abema.tv/now-on-air/special-plus
> [plugin.abematv][debug] URL=https://ds-linear-abematv.akamaized.net/channel/special-plus/playlist.m3u8
> [utils.l10n][debug] Language code: en_GB
> [cli][info] Available streams: 180p (worst), 240p, 360p, 480p, 720p, 1080p (best)
> [cli][info] Opening stream: 180p (hls)
> [stream.hls][debug] Reloading playlist
> [stream.hls][debug] Segments in this playlist are encrypted
> [stream.hls][debug] First Sequence: 150010; Last Sequence: 150013
> [stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 150011; End Sequence: None
> [stream.hls][debug] Adding segment 150011 to queue
> [cli][debug] Pre-buffering 8192 bytes
> [stream.hls][debug] Adding segment 150012 to queue
> [stream.hls][debug] Adding segment 150013 to queue
> [stream.hls][debug] Download of segment 150011 complete
> [cli][info] Starting player: /usr/bin/vlc
> [cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format https://abema.tv/now-on-air/special-plus -
> ```

No problem now. Thanks.
