### ISSUE TITLE
List returned from `streamlink.streams` sometimes empty

### ISSUE THREAD

**Issue by theodoretliu** [streamlink/streamlink#2988]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Hi, I'm using `streamlinks` to pull frames from Twitch streams, and it's been generally great. However, I've been running into intermittent issues with it. I have a simple Flask app set up similar to below
```python
app = Flask(__name__)
session = Streamlink()

@app.route('/')
def index():
    user = request.args.get('user')
    streams = session.streams(f"https://twitch.tv/{user}")
    # streams is sometimes length 0 here ...
```
I'm positive that the stream that's being fetched is online. I recognize that `streamlink` will return 0 if the stream is offline, but that is definitely not the case.

Once I restart the web server, it usually goes back to normal and returns the correct number of streams.

### Expected / Actual behavior

I expect `streamlink` to return a list of streams exactly when the stream is online and empty otherwise.

### Reproduction steps / Explicit stream URLs to test

The code above is the best I can do. I've tried to recreate the behavior by running the `session.streams` function in an infinite loop while I manually have my own Twitch channel go online and offline, but it seems to work as expected. It's only in this long running web server that I see the issue. Some of the bread crumbs from Sentry say there are underlying 404s going on when requesting the HLS stream, but that's all I really know.

**Comment by beardypig** [comment]
Hi @theodoretliu. There is some state stored in the streamlink sessions between invocations of the `index` call. I suggest you create a new streamlink session in `index` and see if that resolves the issue.

**Comment by theodoretliu** [comment]
@beardypig thanks for the tip! I've actually tried that before, but that also caused a crazy memory leak on my web server; it seems like the session object (or something within it) is not getting garbage collected because of some circular references. Any tips on that?

**Comment by theodoretliu** [comment]
@beardypig @back-to could I get a follow-up on the potential cause of a memory leak?

**Comment by back-to** [comment]
@theodoretliu 

> could I get a follow-up on the potential cause of a memory leak?

well we don't know what you are doing, your code in the first post do not work.

**Comment by theodoretliu** [comment]
@back-to  here's a really short reproducible example
```python
from streamlink import Streamlink

while True:
    session = Streamlink()

    stream = session.streams("https://www.twitch.tv/mrsavage")
```
If you run this program, the memory consumption will slowly but steadily rise.

**Comment by back-to** [comment]
@theodoretliu 

seems like python doesn't remove all the garbage data fast enough

**Comment by theodoretliu** [comment]
@back-to I think there's some sort of memory leak happening with circular references. When I force garbage collection by adding `gc.collect()` to the bottom of the loop, I'm still seeing an explosion in memory usage.

**Comment by bastimeyer** [comment]
#3486
