### ISSUE TITLE
[New Plugin] Add viu.tv VOD Service

### ISSUE THREAD

**Issue by jibaketa** [streamlink/streamlink#2990]
## Plugin Request

Add viutv VOD Service Because Official Closed HLS.

### Description

Exist Plugin Only Livestream. 

### Example stream URLs

https://viu.tv/encore/kamen-rider-zi-o/kamen-rider-zioe19jan-geng-dik-gaai-tai-2040

https://viu.tv/encore/invest-smarter-2-02-0/invest-smarter-2020e5720200526

### Additional comments, screenshots, etc.

but in 5/26/2020 later closed HLS and changed to MPEG-DASH(Protected).

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We aren't adding any VOD support which you should have read if you looked through the guidelines before creating this: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

Closing.
