### ISSUE TITLE
Facebook `No playable sreams found for this URl` plugin error

### ISSUE THREAD

**Issue by CDFN** [streamlink/streamlink#2992]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Hi, I'm trying to save livestream to file. Everytime I want to save facebook livestream, output is 
`error: No playable streams found on this URL: facebook.com/CarlosCastleYT/videos/2601466663503213`

### Reproduction steps / Explicit stream URLs to test

1. $ streamlink -o "test.mp4" facebook.com/CarlosCastleYT/videos/2601466663503213 best -l debug
### Log output

```
PS C:\Users\CDFN> streamlink -o "test.mp4" facebook.com/CarlosCastleYT/videos/2601466663503213 best -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL facebook.com/CarlosCastleYT/videos/2601466663503213
[plugin.facebook][debug] Falling back to playlist regex
[plugin.facebook][debug] Falling back to tahoe player
error: No playable streams found on this URL: facebook.com/CarlosCastleYT/videos/2601466663503213
```

### Additional comments, screenshots, etc.
-

**Comment by johnthecracker** [comment]
This is not live stream. Use youtube-dl for VODs.


```
C:\>youtube-dl.exe --verbose --no-check-certificate --no-overwrites --no-part "https://www.facebook.com/CarlosCastleYT/videos/2601466663503213"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--no-check-certificate', '--no-overwrites', '--no-part', 'https://www.facebook.com/CarlosCastleYT/videos/2601466663503213']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3, rtmpdump 2.4
[debug] Proxy map: {}
[facebook] 2601466663503213: Downloading webpage
[facebook] 2601466663503213: Downloading webpage
[facebook] 2601466663503213: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://video.flhr4-2.fna.fbcdn.net/v/t42.1790-29/10000000_637521356843833_2829711423922404091_n.mp4?_nc_cat=102&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfbGl2ZV9oZDFfZnJhZ18yX3ZpZGVvIn0=&_nc_ohc=nZHHCo70wiIAX9-RUAR&_nc_ht=video.flhr4-2.fna&oh=7546acc73dcc7c4a0cb1935aea53aa98&oe=5ED04A4C'
[download] Destination: Terminamos MINECRAFT DUNGEONS en DIRECTO!  Hazte colaborador de la pagina par...-2601466663503213.f3254625877902295v.mp4
[download]   0.4% of 2.32GiB at 520.57KiB/s ETA 01:17:39
```

**Comment by CDFN** [comment]
It has ended, you should try reproduce using any Facebook livestream from [gaming section](https//facebook.com/gaming)

**Comment by johnthecracker** [comment]
When I click on this:

https://github.com/streamlink/streamlink/issues/https//facebook.com/gaming

I see:

404 This is not the web page you are looking for.

You must have working url if you want to see anything.

**Comment by CDFN** [comment]
Sorry, I was writing it on mobile. https://www.facebook.com/gaming/
Link above is proper

**Comment by johnthecracker** [comment]
This plays with streamlink.

Get url with firfox extension "The Stream Detector"

```
streamlink.exe --http-no-ssl-verify --player=mpv.exe "https://video.flhr4-1.fna.fbcdn.net/hvideo-cln1-odn/_nc_cat-1/v/rxIJ_FaaURMcFmAJa8aOc/live-dash/dash-abr5/2692075710897978.mpd?_nc_rl=AfCVp9VmLW7uiWKB&ms=m_CN&oh=710b4b6a5ee918c794540a935239f3f6&oe=5ED232D1" best
```
```
[cli][info] Found matching plugin dash for URL https://video.flhr4-1.fna.fbcdn.net/hvideo-cln1-odn/_nc_cat-1/v/rxIJ_FaaURMcFmAJa8aOc/live-dash/dash-abr5/2692075710897978.mpd?_nc_rl=AfCVp9VmLW7uiWKB&ms=m_CN&oh=710b4b6a5ee918c794540a935239f3f6&oe=5ED232D1
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
[cli][info] Starting player: mpv.exe

**Comment by CDFN** [comment]
Basically im receiving data from external API about streams to download (I am making it by script, not by hand). I am not receiving stream url, but only link to "watch site" (?) - for example https://www.facebook.com/KamykHD/videos/274489493746785.

**Comment by johnthecracker** [comment]
I can't look into games, no interest in games.
If firefox extension can get url and you can program you can find a way to get url.
Once you have url, it plays with streamlink.

```
 Found matching plugin dash
```

**Comment by CDFN** [comment]
Facebook plugin should search for stream on this site (as far as i know). I won't close this issue. Maybe someone else will be able to help me with that.

**Comment by evanfrawley** [comment]
I'm also consistently getting `No playable streams found for this URl` for any Facebook live streams, with the same `falling back` verbose debug logs

**Comment by boygiandi** [comment]
I have the same issue. Please take a look at it

**Comment by boygiandi** [comment]
When I used facebook link. It show `No playable streams found for this URl`. 
But if I use the mpd link direct with streamlink, it works fine.
Please check, may be it's just a minor change to make it work

**Comment by evanfrawley** [comment]
@boygiandi what was the command you used that worked?

**Comment by evanfrawley** [comment]
@boygiandi what was the command you used that worked?

**Comment by boygiandi** [comment]
> @boygiandi what was the command you used that worked?

I use youtube-dl to get the direct link, then use streamlink to download it.

```youtube-dl -g "video_link"```

**Comment by CDFN** [comment]
It still doesn't help us in this thread. @johnthecracker told us about this way. Also we want to download live stream, not video.

**Comment by evanfrawley** [comment]
It might be a few line fix. I'll take a look this weekend. Running 
```
curl ENTER_A_LIVE_URL_FROM_FB |                                             
grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*'
```
gives me this output: 
![Screen Shot 2020-06-05 at 11 38 35 AM](https://user-images.githubusercontent.com/13992385/83911525-45800a80-a721-11ea-8ee5-bccaffc1867c.png)

to get a live url from fb, go to https://fb.gg, then click any live stream, then click the view so you're on a webpage that has a url of roughly `facebook.com/username/videos/123456789videoID`. **DO NOT RUN THIS ON A NON-LIVE VIDEO**, as that is not the problem of this issue.

**Comment by evanfrawley** [comment]
Some new info

`res.text` when sent into the `_parse_streams` function yields this locally:

```
for (;;);{"__ar":1,"error":1357005,"errorSummary":"Your Request Couldn't be Processed","errorDescription":"There was a problem with this request. We're working on getting it fixed as soon as we can.","payload":null,"bootloadable":{},"ixData":{},"bxData":{},"gkxData":{},"qexData":{},"lid":"6834983421709621636"}
```

**Comment by evanfrawley** [comment]
so @CDFN seems like streamlink is working again with facebook? Can you confirm on your end if it is working on livestreams

**Comment by CDFN** [comment]
On official release (latest pip package) it still doesn't work. I'm cloning your repo and I'll check if its working.
