### ISSUE TITLE
The stream.hls seems to overwrite the --http-header configuration

### ISSUE THREAD

**Issue by vuhadung** [streamlink/streamlink#2997]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
I try to get the stream as follow

`streamlink --http-header sec-fetch-dest=empty --http-header sec-fetch-mode=cors --http-header sec-fetch-site=cross-site --hls-segment-key-uri "https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCQXBCd2JqWmc5dThRWE9VIiwiY29udGVudElkIjoiNDdhN2FiYWItZGIxZi00OGMwLTg5MzEtZTJiZmJkNTg0ZTczIiwiaWF0IjoxNTkwNzcxNjg5LCJleHAiOjE1OTA3NzI1ODl9.ULwAXUd3BP0ce_bcERRPW791kd3fh8iBWWJ-XPbXwb4" https://hls.mediacdn.vn/vtv/2020/5/29/2905cayxanh192848-1590755023005236763935-fc5391590755249563.mp4/1080.m3u8?v=1798ca40 best -o G:/hls/output.mp4`

I can get the key via Postman call with the headers as above. But when streamlink runs, it returns 403 forbidden error when getting the key, as because it does not pass the above headers. 

### Expected / Actual behavior

The HTTP request to get the key should add 3 headers: sec-fetch-dest, sec-fetch-mode, sec-fetch-site and returns status 200

### Reproduction steps / Explicit stream URLs to test

Please see the above command

### Log output

```
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCQXBCd2JqWmc5dThRWE9VIiwiY29udGVudElkIjoiNDdhN2FiYWItZGIxZi00OGMwLTg5MzEtZTJiZmJkNTg0ZTczIiwiaWF0IjoxNTkwNzcxNjg5LCJleHAiOjE1OTA3NzI1ODl9.ULwAXUd3BP0ce_bcERRPW791kd3fh8iBWWJ-XPbXwb4 (403 Client Error: Forbidden for url: https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCQXBCd2JqWmc5dThRWE9VIiwiY29udGVudElkIjoiNDdhN2FiYWItZGIxZi00OGMwLTg5MzEtZTJiZmJkNTg0ZTczIiwiaWF0IjoxNTkwNzcxNjg5LCJleHAiOjE1OTA3NzI1ODl9.ULwAXUd3BP0ce_bcERRPW791kd3fh8iBWWJ-XPbXwb4)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://hls.mediacdn.vn/vtv/2020/5/29/2905cayxanh192848-1590755023005236763935-fc5391590755249563.mp4/1080.m3u8?v=1798ca40')> (No data returned from stream)
error: Could not open stream <HLSStream('https://hls.mediacdn.vn/vtv/2020/5/29/2905cayxanh192848-1590755023005236763935-fc5391590755249563.mp4/1080.m3u8?v=1798ca40')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by Billy2011** [comment]
> I can get the key via Postman call with the headers as above. But when streamlink runs, it returns 403 forbidden error when getting the key, as because **it does not pass the above headers**.

You are wrong, this are the passed headers:
```
METHOD: GET
URL
https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCQXBCd2JqWmc5dThRWE9VIiwiY29udGVudElkIjoiNDdhN2FiYWItZGIxZi00OGMwLTg5MzEtZTJiZmJkNTg0ZTczIiwiaWF0IjoxNTkwNzcxNjg5LCJleHAiOjE1OTA3NzI1ODl9.ULwAXUd3BP0ce_bcERRPW791kd3fh8iBWWJ-XPbXwb4
HEADERS
accept:
*/*
accept-encoding:
gzip, deflate
connection:
keep-alive
host:
kms.sohatv.vn
sec-fetch-dest:
empty
sec-fetch-mode:
cors
sec-fetch-site:
cross-site
user-agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
```

**Comment by vuhadung** [comment]
Then why when I use curl or postman it does work, but streamlink gets 403 error?
For the link, the token will be updated then the link is now invalid. I am trying to get the video from [this site](https://vtv.vn/trong-nuoc/so-phan-cua-hang-cay-tren-duong-kim-ma-gio-ra-sao-20200529180344469.htm), when you do inspect you will get the link that has the form of
`https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=...`
where dt is the token which refreshes after some interval

> > I can get the key via Postman call with the headers as above. But when streamlink runs, it returns 403 forbidden error when getting the key, as because **it does not pass the above headers**.
> 
> You are wrong, this are the passed headers:
> 
> ```
> METHOD: GET
> URL
> https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key?h=U2FsdGVkX19rZkrOvOKJFst9eFPudTwEmsPwva0AF%2Bc%3D&alg=1&dt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCQXBCd2JqWmc5dThRWE9VIiwiY29udGVudElkIjoiNDdhN2FiYWItZGIxZi00OGMwLTg5MzEtZTJiZmJkNTg0ZTczIiwiaWF0IjoxNTkwNzcxNjg5LCJleHAiOjE1OTA3NzI1ODl9.ULwAXUd3BP0ce_bcERRPW791kd3fh8iBWWJ-XPbXwb4
> HEADERS
> accept:
> */*
> accept-encoding:
> gzip, deflate
> connection:
> keep-alive
> host:
> kms.sohatv.vn
> sec-fetch-dest:
> empty
> sec-fetch-mode:
> cors
> sec-fetch-site:
> cross-site
> user-agent:
> Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
> ```

**Comment by Billy2011** [comment]
I am not interested in the videos, but I am interested in how long this drm token is valid, is it always valid for the whole video? 

Back to your problem, I think you only need to add a referer header to streamlink, for example:
`--http-header "Referer"="https://vtv.vn/video/lo-ngai-tinh-trang-hoc-sinh-hut-thuoc-la-440888.htm"`

**Comment by bastimeyer** [comment]
> The stream.hls seems to overwrite the --http-header configuration

As @Billy2011 already said, this is not true. Neither streamlink-cli, nor the Session and HTTPSession classes, nor the HLSPlugin, nor HLSStreamWriter override any HTTP headers set by the user.

1.  https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink_cli/main.py#L713-L714
2. https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/session.py#L287
3. https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/plugin/api/http_session.py#L67-L68
4. https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/plugins/hls.py
5.  https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/stream/hls.py#L97-L113

And as you can see here, the key request uses the same headers you've set:
https://github.com/streamlink/streamlink/blob/1.4.1/src/streamlink/stream/hls.py#L83-L85

Make sure that you have set **exactly** the same headers which your web browser sends. This can also be the `User-Agent` or `Referrer` header for example.

**Comment by vuhadung** [comment]
Thanks for your support. I think @Billy2011 were correct. When I set the Referer, it worked perfectly. 
The command was
`
streamlink --http-header "sec-fetch-dest"="empty" --http-header "sec-fetch-mode"="cors" --http-header "sec-fetch-site"="cross-site" --http-header "Referer"="https://vtv.vn/trong-nuoc/so-phan-cua-hang-cay-tren-duong-kim-ma-gio-ra-sao-20200529180344469.htm" --hls-segment-key-uri "https://kms.sohatv.vn/drm/47a7abab-db1f-48c0-8931-e2bfbd584e73.key" https://hls.mediacdn.vn/vtv/2020/5/29/2905cayxanh192848-1590755023005236763935-fc5391590755249563.mp4/1080.m3u8?v=1798ca40 best -o G:/hls/output.mp4
`
But another error occurred as below
```
Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 141, in write
    sequence.num)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 95, in create_decryptor
    return AES.new(self.key_data, AES.MODE_CBC, iv)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\AES.py", line 202, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\AES.py", line 92, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (48 bytes)
```
Is this error caused by the server or streamlink itself?

**Comment by Billy2011** [comment]
I think that the drm token `dt` is no longer valid - that's why I asked for it.
