### ISSUE TITLE
1spotmedia.com

### ISSUE THREAD

**Issue by speakerboar** [streamlink/streamlink#2998]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
1spotmedia.com, contain Jamaican and Caribbean channels.

### Example stream URLs

1. https://www.1spotmedia.com/#!/live-stream/79336998495
2. https://www.1spotmedia.com/#!/live-stream/77999142467
3. https://www.1spotmedia.com/#!/live-stream/79336998577

### Additional comments, screenshots, etc.
Requires registering for free account but viewing only free from Jamaican IP
[When accessing in Jamaica](https://i.imgur.com/po5szL3.png)
[Outside of  Jamaica](https://i.imgur.com/ybAiuaf.png)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
@speakerboar Unfortunately this site violates a lot of the rules outlined in Our [plugin request guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests). @back-to opened a PR with the plugin here: https://github.com/streamlink/streamlink/pull/3389/files if you want to [sideload it](https://streamlink.github.io/cli.html?highlight=side%20load#sideloading-plugins).

**Comment by mkbloke** [comment]
Off-topic for this issue, but this is the reason I'm reluctant to take on any of the existing plugin requests.  Most of the rules are straightforward; it's number 10 that's most problematic.  Not all sites will have viewer figures (if they can be trusted anyway) and what constitutes an acceptable number to justify the inclusion of a new plugin into master...

**Comment by gravyboat** [comment]
@mkbloke This is one of the big problems since we don't track user install or usage stats at all. There's no way to even see if a plugin will be widely used, or if it's just one person who wants a website. Viewer numbers are the easiest way to track that, but as you said a lot of sites don't include these details. Maybe we should consider a new repo of side load plugins that don't meet these requirements?

**Comment by bastimeyer** [comment]
> Maybe we should consider a new repo of side load plugins that don't meet these requirements?

I'd suggest creating a new orga `streamlink-contrib` (or something similar) for this purpose. Then you can decide whether there should be repos for individual plugins or one plugin for a collection of community plugins.

By moving such plugins to a different orga, this protects Streamlink from invalid/incorrect DMCA takedown notices and the likes. And it makes it immediately clear to the user that it's nothing official.

**Comment by gravyboat** [comment]
@bastimeyer Yeah that's a good idea, my only concern is managing more repos...

**Comment by mkbloke** [comment]
@gravyboat, yeah, I get that it's hard to know how many people might use a new plugin at first or in the future.  I just look at the issues with the "plugin request" label and find it hard to know which ones might be worth bothering with.  It wouldn't be so bad if I had a personal interest in using any of them, but I don't and naturally, nobody wants to expend time writing a plugin that could be consigned to the bin.  Streamlink already supports the biggest sites that people use, so it's unsurprising that new requests are more often than not going to be niche by comparison.

In terms of viewer numbers, even if they can be obtained and presumed to be accurate, I for example, have no idea what the acceptable number might be and that's what makes rule number 10 a bit of a problem.  I might start digging into the current plugin requests to find more info and posting that into each issue - at least then it could help to ascertain if it's worth keeping as a possibility or closing as "does not meet requirements".

A separate repo for side loadable plugins sounds like a good idea in theory, it just depends on your conclusion as to how much additional work it might create.
