### ISSUE TITLE
Rewinding youtube doesn't seem to work anymore

### ISSUE THREAD

**Issue by jancoow** [streamlink/streamlink#2999]
## Bug Report

- [x ] This is a bug report and I have read the contribution guidelines.

### Description
I've used streamlink for a very long time, however suddenly --hls-live-restart doesn't work anymore on rewindable youtube streams. This is really annoying, because of all the festival live streams I want to record lately. It's hard to keep track on the correct time, and I'm sometimes 5 minutes late which I'm unable to record anymore, while I'm allowed to go back when opening youtube in the browser. 

It did work a few times today, but not always, and I'm not sure why. 

### Expected / Actual behavior

Start recording from the beginning of the stream

### Reproduction steps / Explicit stream URLs to test
Get a youtube livestream which can rewind, and try to record it with  --hls-live-restart

**Comment by mkbloke** [comment]
See: https://github.com/streamlink/streamlink/issues/2936

**Comment by gravyboat** [comment]
Yep this is a duplicate so I've closed it.
