### ISSUE TITLE
Create Projects for streamlink

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#3]
We'll need to review some of the main items that need to be done. At this time some of the big ones should include:
- Update all instances of livestreamer to be streamlink - COMPLETE (via #15)
- Set up automation tooling for tests (Travis CI, coveralls) - COMPLETE  (via #6, and #16)
- Set up automation tooling for package builds
- Set up a plan to review existing PRs and talk to their authors about what is worth getting in - MOSTLY COMPLETE (via #9)
- Confirm test coverage is 100% - 35% currently, requires additional work with how tox is currently used.
- Set up documentation page that is under our control - COMPLETE (via #26 and #36)

**Comment by alphapapa** [comment]
Could you please document the reasons for the fork?  I am a happy livestreamer user, but I haven't followed internal issues to the project, so I just happened to come across this fork when looking for info on the client-ID changes.

**Comment by cdrage** [comment]
@alphapapa feel free to send a PR to update the README / etc :)

**Comment by alphapapa** [comment]
@cdrage I'm asking because I don't know the answers.

**Comment by SpootDev** [comment]
@alphapapa, IMHO livestreamer is dead on the vine.  8 months since last merge to develop, 1 year since master update....and no communication from main dev.  500 issues and 50 PR's just sitting there.

**Comment by cdrage** [comment]
@alphapapa I created a PR to address this.

**Comment by gravyboat** [comment]
@alphapapa In addition to what @SpootDev and @cdrage have mentioned, I have tried to contact @chrippa via all public channels I could find and have not received any response. I additionally asked if he would continue working on it if we donated some money (to at least get the most essential patches in) and there was no response. I agree with @SpootDev, the project is dead. The owner is still active on GitHub, but has not reviewed anything related to this repo in quite some time.

**Comment by alphapapa** [comment]
Okay, thanks, that makes sense.  I'll make another issue to discuss the youtube-dl thing.  (Not that I want this project to be abandoned.  I very much appreciate you picking up the torch!)

**Comment by sbstp** [comment]
Can we get a gitter channel too?

**Comment by TheSneakySniper** [comment]
FIX USTREAM!!!!!! PLEASE!!!!!!

**Comment by gravyboat** [comment]
@TheSneakySniper This really isn't the right venue to make this request. Please create a new issue explaining exactly how to duplicate the issue, and in what way it is broken. If you're able to troubleshoot and debug the issue please submit a PR with the fix.

**Comment by martinth** [comment]
@TheSneakySniper as far as I can tell, UStream seems to work at least partially. If you want to help you can simply open a "New Issue" (button on the top right). The more details you can provide that better (i.e. concrete link that is not working, console output, etc.).

**Comment by TheSneakySniper** [comment]
I have made a post

**Comment by gravyboat** [comment]
Going to close this out.
