### ISSUE TITLE
Audio not synchronized using hls-multistream

### ISSUE THREAD

**Issue by j00zek** [streamlink/streamlink#3002]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I've ported Kodi plugin for pilot.wp.pl website to streamlink. All seems to work properly, but the audio and video are out of sync in output stream/file.

### Log output

```
/usr/lib/python2.7/site-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-3.14.28-1.8-armv7l-with-glibc2.4
[cli][debug] Python:     2.7.13
[cli][debug] Streamlink: 0+unknown
[cli][debug] Requests(2.13.0), Socks(1.6.6), Websocket(0.56.0)
[cli][info] Found matching plugin _pilotwppl for URL https://pilot.wp.pl/api/v1/channel/3
[plugin._pilotwppl][debug] PilotWPpl._get_streams() >>>
[plugin._pilotwppl][debug] Response: {u'data': {u'stream_channel': {u'channel_name': u'TVP 1 HD', u'streams': [{u'url': [u'https://stream-cdn-1.videostar.pl/3/amlst:basic/manifest.mpd?t2=74a81896766641319034287fc2efeec2&t3=97e8af78f94844c29cfce9249edec06f&t5=&device=android&type=free&ts=cb87b2a46cb7666854c610dae38965e9f6f90dc369279aa49fc4ecbc5e936d7e', u'https://stream-cdn-2.videostar.pl/3/amlst:basic/manifest.mpd?t2=74a81896766641319034287fc2efeec2&t3=97e8af78f94844c29cfce9249edec06f&t5=&device=android&type=free&ts=cb87b2a46cb7666854c610dae38965e9f6f90dc369279aa49fc4ecbc5e936d7e'], u'type': u'dash@live:abr', u'balance': u'50/50', u'quality': u'AUTO'}, {u'url': [u'https://stream-cdn-1.videostar.pl/3/amlst:basic/playlist.m3u8?t2=74a81896766641319034287fc2efeec2&t3=97e8af78f94844c29cfce9249edec06f&t5=&device=android&type=free&ts=da2969c215b86b8c8c8de32edfda0ba2873b156ea4a74f35862a7870bc8bc0cf', u'https://stream-cdn-2.videostar.pl/3/amlst:basic/playlist.m3u8?t2=74a81896766641319034287fc2efeec2&t3=97e8af78f94844c29cfce9249edec06f&t5=&device=android&type=free&ts=da2969c215b86b8c8c8de32edfda0ba2873b156ea4a74f35862a7870bc8bc0cf'], u'type': u'hls@live:abr', u'balance': u'50/50', u'quality': u'AUTO'}], u'url_base': u''}, u'distractUser': {u'since': 1591079741, u'interval': 1800000}}, u'_meta': None}
[plugin._pilotwppl][debug] Prefer HLS stream:
         https://stream-cdn-1.videostar.pl/3/amlst:basic/playlist.m3u8?t2=74a81896766641319034287fc2efeec2&t3=97e8af78f94844c29cfce9249edec06f&t5=&device=android&type=free&ts=da2969c215b86b8c8c8de32edfda0ba2873b156ea4a74f35862a7870bc8bc0cf
[utils.l10n][debug] Language code: en_GB
[stream.hls][debug] Using external audio tracks for stream 480p (language=pl, name=polski)
[stream.hls][debug] Using external audio tracks for stream 360p (language=pl, name=polski)
[stream.hls][debug] Using external audio tracks for stream 144p (language=pl, name=polski)
[cli][info] Available streams: 144p (worst), 360p, 480p (best)
[cli][info] Opening stream: 480p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 5459443; Last Sequence: 5459447
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5459443; End Sequence: None
[stream.hls][debug] Adding segment 5459443 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5459444 to queue
[stream.hls][debug] Adding segment 5459445 to queue
[stream.hls][debug] Adding segment 5459446 to queue
[stream.hls][debug] Adding segment 5459447 to queue
[stream.hls][debug] First Sequence: 5459443; Last Sequence: 5459447
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5459443; End Sequence: None
[stream.hls][debug] Adding segment 5459443 to queue
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-30873-109 -i /tmp/ffmpeg-30873-2 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-30873-109
[stream.hls][debug] Adding segment 5459444 to queue
[stream.hls][debug] Adding segment 5459445 to queue
[stream.hls][debug] Adding segment 5459446 to queue
[stream.hls][debug] Adding segment 5459447 to queue
....
```

### Additional comments, screenshots, etc.

Playing with hls options doesn't help.
The same stream works properly from Kodi.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
As other issues on the issue tracker have already pointed out, this may be caused by an outdated FFMpeg version. Make sure to be using the latest version.

**Comment by j00zek** [comment]
thanks for your advice. I used ffmpeg version 4.2.2 Unfortunatelly the issue still exists. 
Log:
[plugin._pilotwppl][debug] Found streams:
         dash: https://stream-cdn-1.videostar.pl/174/amlst:basic/manifest.mpd?t2=74a81896766641319034287fc2efeec2&t3=c306a35aa28f4f79a29ad79208084e05&t5=&device=android&type=free&ts=9acdea21eb5e2c55a7564a31f405bb9a50aee304f544142226754af87ef72ae1
         hls: https://stream-cdn-2.videostar.pl/174/amlst:basic/playlist.m3u8?t2=74a81896766641319034287fc2efeec2&t3=c306a35aa28f4f79a29ad79208084e05&t5=&device=android&type=free&ts=1245f1d2ed90d6e79c9bb494c904ed633e4769cdf66eeca156c3f8c8a61f6d26
[utils.l10n][debug] Language code: en_GB
[stream.hls][debug] Using external audio tracks for stream 480p (language=pl, name=polski)
[stream.hls][debug] Using external audio tracks for stream 360p (language=pl, name=polski)
[stream.hls][debug] Using external audio tracks for stream 144p (language=pl, name=polski)
[cli][info] Available streams: 144p (worst), 360p, 480p (best)
[cli][info] Opening stream: 480p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 5506242; Last Sequence: 5506246
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5506244; End Sequence: None
[stream.hls][debug] Adding segment 5506244 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5506245 to queue
[stream.hls][debug] Adding segment 5506246 to queue
[stream.hls][debug] First Sequence: 5506242; Last Sequence: 5506246
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 5506244; End Sequence: None
[stream.hls][debug] Adding segment 5506244 to queue
[stream.hls][debug] Adding segment 5506245 to queue
[stream.ffmpegmux][debug] ffmpeg command: /usr/bin/ffmpeg442 -nostats -y -i /tmp/ffmpeg-13137-840 -i /tmp/ffmpeg-13137-136 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-13137-840
[stream.hls][debug] Adding segment 5506246 to queue
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-13137-136
[cli][debug] Pre-buffering 8192 bytes
ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libxml2 --enable-libxvid
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[stream.hls][debug] Download of segment 5506244 complete
[stream.hls][debug] Download of segment 5506245 complete
[stream.hls][debug] Download of segment 5506246 complete
[stream.hls][debug] Download of segment 5506244 complete
[stream.hls][debug] Download of segment 5506245 complete
Input #0, mpegts, from '/tmp/ffmpeg-13137-840':
  Duration: N/A, start: 43429.711600, bitrate: N/A
  Program 1
    Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 90k tbn, 50 tbc
[stream.hls][debug] Download of segment 5506246 complete
Input #1, mpegts, from '/tmp/ffmpeg-13137-136':
  Duration: N/A, start: 43429.413933, bitrate: 89 kb/s
  Program 1
    Stream #1:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
    Stream #1:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 89 kb/s
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 854x480 [SAR 1:1 DAR 427:240], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 89 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #1:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mpegts @ 0x2a321a0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[cli][debug] Checking file output
[mpegts @ 0x2a424a0] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5506247 to queue
[stream.hls][debug] Download of segment 5506247 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5506247 to queue
[stream.hls][debug] Adding segment 5506248 to queue
[stream.hls][debug] Download of segment 5506247 complete
[stream.hls][debug] Download of segment 5506248 complete
[download][test.mp4] Written 1.9 MB (8s @ 219.1 KB/s)                                                                                                                                            [stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5506248 to queue

**Comment by j00zek** [comment]
I resolved the issue on my own by modifying fmmpemux stram script

**Comment by campones** [comment]
I have had this issue for years , whatever versions of ffmpeg I m using, compiled or standalone binary like the one you used. 
after  a while  (can't predict , can be 30 min or 3 hours) the audio will be out of sync , over 10 s sometimes. 
In my case I have seen this with francetv plugin  which is also an hls-multi stream.

I would be interested if you could share more details of the modification you did on ffmpeg

**Comment by campones** [comment]
> I resolved the issue on my own by modifying ffmpemux stream script

Could you please share your modified version of ffmpemux with me?  I m facing this issue too for long time. 
Thanks

**Comment by campones** [comment]
I don't want to claim victory but for the last 2 days I don't seem to have anymore audio video  desync 

I m not 100% sure what did the trick and I also have a cron restarting hourly the streams. 

So I m using a static build of ffmpeg now in streamlink command, instead of my git compiled ffmpeg and I removed the option " --ffmpeg-start-at-zero" that I had. for some reason, with this setting even right after restarting it was out of sync!

/usr/local/bin/streamlink --ffmpeg-ffmpeg "/usr/local/bin/ffmpeg5" --ffmpeg-audio-transcode "aac" --ffmpeg-copyts --ffmpeg-fout "flv" "https://www.france.tv/france-3/direct.html" 540p
