### ISSUE TITLE
FOX TR not working anymore

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#3006]
Plugin foxtr.py not working since a few days.

Can someone have a look please?

Greetings

**Comment by gravyboat** [comment]
This issue doesn't meet any of the requirements. Provide them like the issue template said to do.

**Comment by Rotarum** [comment]
The command line is giving the following error message:

" [cli][info] Found matching plugin foxtr for URL https://www.fox.com.tr/canli-yayin
error: No playable streams found on this URL: https://www.fox.com.tr/canli-yayin "

**Comment by Rotarum** [comment]
Works again!

Thank you 👍
