### ISSUE TITLE
Add PK mode support for Bigo Live

### ISSUE THREAD

**Issue by el-lsan** [streamlink/streamlink#3008]
## Feature Request

- [X] This is a feature request and I have read the contribution guidelines.

### Description
Bigo.tv has one feature where two users are streaming together and it is called PK mode.
So when two users are going on PK mode you would see them both side to side. However streamlink is only capturing the initial user. So basically the PK mode is not supported by the current plugin.

### Expected / Actual behavior
Add PK mode support to bigo plugin.

### Additional comments, screenshots, etc.
PK mode has been explained in details [on this post](https://medium.com/@laurenhallanan/live-streaming-101-understanding-the-battles-or-pk-feature-49e7d7bc2ff2) and it includes many screenshots.

**Comment by bastimeyer** [comment]
> two users are streaming together

These look like two or more separate streams. Unless both streams are merged into one single stream by the server, this won't be supported. Streamlink doesn't support multiple outputs.
