### ISSUE TITLE
Streamlink Python 3 Installation 

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#3020]
## Feature Request

Streamlink Python 3 Installation to be detailed here:
https://streamlink.github.io/install.html

### Description

Installation with pip3 doesn't work the way I do it.
Obviously, I do something wrong and look here to get it clear.

### Expected / Actual behavior

Install Streamlink with pip3

### Additional comments, screenshots, etc.

Python2 is getting phased out and replaced with Python3.
I have Python 3.8 installed on Ubuntu 20.04

Can somebody tell me how can I install Streamlink in Ubuntu 20.04 with pip3 ?

I want to run pip function because this is the only way of installing Streamlink
in Ubuntu without getting Streamlink's Rtmpdump, if I am right.
If I am wrong, I am all eyes to read how to install Streamlink without
forcing Streamlink's Rtmpdump on my Ubuntu 20.04.

These both pip ways result in non working Streamlink:

sudo pip3 install --upgrade streamlink
sudo pip3 install --upgrade git+https://github.com/streamlink/streamlink.git

This option works, with "PythonDeprecatedWarning" message:

https://streamlink.github.io/install.html
Development version (pip) 	
system wide
sudo pip install --upgrade git+https://github.com/streamlink/streamlink.git

```
j@j:~/LINUX/news$ ./bbc.sh
/usr/local/lib/python2.7/dist-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: 
Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. 
Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][info] Found matching plugin filmon for URL https://www.filmon.com/tv/bbc-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay
```

**Comment by bastimeyer** [comment]
Since Ubuntu 20.04 doesn't come with `python2` installed by default (and it also doesn't symlink `/usr/bin/python3` to `/usr/bin/python`, unless the `python-is-python3` package is installed), you have to explicitly execute `python3` or `pip3` to do stuff with Python 3. By installing python packages via `pip3`, there is no way for it to install packages based on Python 2, because it's a totally different environment.

So if you have a Streamlink install based on python2.7, you must have done something else earlier. Since I don't know what you have done, all I can tell you is to check whether the python2 based streamlink package belongs to your system's package manager or whether you were using python2 based pip earlier. Either way, you must have installed python2, according to `/usr/local/lib/python2.7/dist-packages/`.

Also, as you can read on the install docs page, you should not be using `sudo` when installing python packages via `pip`, as it can or will introduce conflicts with your system's regular package manager. That's why the `--user` parameter should be set or packages installed in a separate virtual environment.

> Can somebody tell me how can I install Streamlink in Ubuntu 20.04 with pip3 ?

```bash
$ sudo apt install python3-pip
$ pip3 install --user streamlink
$ ~/.local/bin/streamlink --version
```

**Comment by johnthecracker** [comment]
```
sudo apt install python3-pip
pip3 install --user streamlink
~/.local/bin/streamlink --version
```

Here is pip3 streamlink on newly installed ubuntu 20.04:

``` 
j@j:~$ echo $PATH
/home/j/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
```
j@j:~$ streamlink
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```
```
j@j:~$ streamlink -V
streamlink 1.4.1
```
```
j@j:~$ /home/j/LINUX/news/./bbcw.sh
[cli][info] Found matching plugin filmon for URL https://www.filmon.com/tv/bbc-world-news
error: Unable to open URL: https://www.filmon.com/tv/bbc-world-news (HTTPSConnectionPool(host='www.filmon.com', port=443): 
Max retries exceeded with url: /tv/bbc-world-news (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] 
wrong signature type (_ssl.c:1108)'))))
j@j:~$ 
```
```
j@j:~/LINUX/news$ ./sky.sh
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCoMdktPbSTixAyNGwb-UYkQ
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: ffplay
```
```
+ model=blazingeve
+ :
++ date +%Y-%m-%d_%H-%M-%S
+ d=2020-06-11_08-21-47
+ file=blazingeve_2020-06-11_08-21-47.ts
+ streamlink generic://https://chaturbate.com/blazingeve/ best -o blazingeve_2020-06-11_08-21-47.ts
error: No plugin can handle URL: generic://https://chaturbate.com/blazingeve/
+ sleep 60
```

This is puzzling.
I can say something for sure for the last run:
generic plugin was updated yesterday and it works in windows.
Here you read for yourself what I get from beautiful linux desktop system.
bbc world news ( filmon ) works in windows as well.

If anybody can explain why I get this sometimes working ( sky news )
and sometimes not working please comment here.

This one works as well:

```
j@j:~/LINUX/news$ ./sbnd.sh
+ url=https://sonlife7-i.akamaihd.net/hls/live/585011/ch7/ch71/ch71.m3u8
+ streamlink '--player=mplayer -af equalizer=8:4:-3:-1:0:1:2:3:2:3' https://sonlife7-i.akamaihd.net/hls/live/585011/ch7/ch71/ch71.m3u8 best
[cli][info] Found matching plugin hls for URL https://sonlife7-i.akamaihd.net/hls/live/585011/ch7/ch71/ch71.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: mplayer -af equalizer=8:4:-3:-1:0:1:2:3:2:3
```

I wish Jesus was here to fix this pip3 on ubuntu 20.04

**Comment by johnthecracker** [comment]
Or you may consider implementing snap installation for streamlink,
as somebody proposed in another issue, might just happen to work.

But without forcing streamlink's rtmpdump together with streamlink if possible, please.

In windows installation of streamlink, streamlink's rtmpdump installation is made optional.

in ubuntu, apt will mercilessly install whatever it wants to giving me only y/n?

Linus, where are you today?

**Comment by bastimeyer** [comment]
> error: Unable to open URL: https://www.filmon.com/tv/bbc-world-news

The filmon plugin was fixed in #2962, which happened after the 1.4.1 release. This means you have to install streamlink from git (via pip) to get the latest dev version. This is all described on the install page in Streamlink's docs.

> streamlink generic://

Steamlink doesn't come with a "generic" plugin. If you are using 3rd party stuff, then this is up to you to fix. Not Streamlink's problem.

> But without forcing streamlink's rtmpdump together with streamlink

Both the Streamlink debian and Ubuntu PPA packages have `rtmpdump` listed in the "recommends" list, not in the "depends" list:
- https://github.com/amurzeau/streamlink-debian/blob/master/debian/control#L32
- https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=streamlink&field.status_filter=published&field.series_filter=

> apt will mercilessly install whatever it wants

https://askubuntu.com/questions/179060/how-to-not-install-recommended-and-suggested-packages

**Comment by johnthecracker** [comment]
I fixed generic plugin problem and have to redo streamlink installation to test filmon plugin.
Information you provided is helpful and greatly appreciated.

**Comment by johnthecracker** [comment]
Thanks again @bastimeyer,

It appears that for now I can't get dev version with pip3. As you said, python2 and 3 conflict.

I followed your instructions and got working streamlink without streamlink's rtmpdump.
This is the most important.

Here is procedure step by step, this is to other guys reading this issue:

installed with su:

apt install python
apt install python-setuptools

no su or sudo, run get-pip.py script from disk:

( https://github.com/pypa/get-pip )

python get-pip.py

pip install --upgrade --user git+https://github.com/streamlink/streamlink.git

```
j@j:~$ streamlink -V
streamlink 1.4.1+19.g5059d64
```

Here is document that shows (pip) dev version working, let aside nuisance python2.7 messages.

```
j@j:~/LINUX/news$ ./bbcw.sh
/home/j/.local/lib/python2.7/site-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][info] Found matching plugin filmon for URL https://www.filmon.com/tv/bbc-world-news
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][info] Starting player: ffplay

j@j:~$ streamlink generic://https://chaturbate.com/hannahjames710/ best
/home/j/.local/lib/python2.7/site-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][info] Found matching plugin generic for URL generic://https://chaturbate.com/hannahjames710/
[plugin.generic][info] Version 2020-06-10 - https://github.com/back-to/generic
[plugin.generic][info]   1. URL=https://chaturbate.com/hannahjames710/
[plugin.generic][info] Found Playlists: 1 (valid)
[cli][info] Available streams: 240p (worst), 480p, 720p, 1080p, 1440p, 2160p (best)
[cli][info] Opening stream: 2160p (hls)
[cli][info] Starting player: /usr/bin/vlc
```

```
j@j:~$ pip install --upgrade --user git+https://github.com/streamlink/streamlink.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/streamlink/streamlink.git
  Cloning https://github.com/streamlink/streamlink.git to /tmp/pip-req-build-bUs1Zk
  Running command git clone -q https://github.com/streamlink/streamlink.git /tmp/pip-req-build-bUs1Zk
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py27-none-any.whl (16 kB)
Collecting iso-639
  Using cached iso-639-0.4.5.tar.gz (167 kB)
Collecting iso3166
  Using cached iso3166-1.0.1-py2.py3-none-any.whl (8.2 kB)
Collecting isodate
  Downloading isodate-0.6.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 685 kB/s 
Collecting pycryptodome<4,>=3.4.3
  Downloading pycryptodome-3.9.7-cp27-cp27mu-manylinux1_x86_64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 481 kB/s 
Collecting requests<3.0,>=2.21.0
  Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.0 MB/s 
Collecting websocket-client
  Using cached websocket_client-0.57.0-py2.py3-none-any.whl (200 kB)
Collecting singledispatch
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl (12 kB)
Collecting backports.shutil_get_terminal_size
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl (6.5 kB)
Collecting backports.shutil_which
  Downloading backports.shutil_which-3.5.2-py2.py3-none-any.whl (2.7 kB)
Collecting futures
  Downloading futures-3.3.0-py2-none-any.whl (16 kB)
Collecting urllib3[secure]>=1.23
  Downloading urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 454 kB/s 
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from isodate->streamlink==1.4.1+19.g5059d64) (1.14.0)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.4.5.2-py2.py3-none-any.whl (157 kB)
     |████████████████████████████████| 157 kB 1.6 MB/s 
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests<3.0,>=2.21.0->streamlink==1.4.1+19.g5059d64) (3.0.4)
Collecting idna<3,>=2.5
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 483 kB/s 
Collecting cryptography>=1.3.4; extra == "secure"
  Downloading cryptography-2.9.2-cp27-cp27mu-manylinux2010_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 430 kB/s 
Collecting pyOpenSSL>=0.14; extra == "secure"
  Downloading pyOpenSSL-19.1.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 705 kB/s 
Collecting ipaddress; python_version == "2.7" and extra == "secure"
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting enum34; python_version < "3"
  Downloading enum34-1.1.10-py2-none-any.whl (11 kB)
Collecting cffi!=1.11.3,>=1.8
  Downloading cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl (387 kB)
     |████████████████████████████████| 387 kB 689 kB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 917 kB/s 
Building wheels for collected packages: streamlink, iso-639
  Building wheel for streamlink (setup.py) ... done
  Created wheel for streamlink: filename=streamlink-1.4.1+19.g5059d64-py2.py3-none-any.whl size=383557 sha256=a7f509be2a727f49afd0717bce6f3d716d70bb8588d76e7d2eea191264ace724
  Stored in directory: /tmp/pip-ephem-wheel-cache-IxhbNA/wheels/f1/0d/2b/20df1a579b1bc92e8d9082f8d5ac46f2494b04a0a1aa2a111e
  Building wheel for iso-639 (setup.py) ... done
  Created wheel for iso-639: filename=iso_639-0.4.5-py2-none-any.whl size=169061 sha256=5979ef553262af316bf59a77defc389f36ca0b932ccb689d074b449404b8752c
  Stored in directory: /home/j/.cache/pip/wheels/b1/7b/28/d8b4e69899ae1058d9bc532b0757fd75caf379befcfa22f8d7
Successfully built streamlink iso-639
Installing collected packages: PySocks, iso-639, iso3166, isodate, pycryptodome, certifi, idna, enum34, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, urllib3, requests, websocket-client, singledispatch, backports.shutil-get-terminal-size, backports.shutil-which, futures, streamlink
Successfully installed PySocks-1.7.1 backports.shutil-get-terminal-size-1.0.0 backports.shutil-which-3.5.2 certifi-2020.4.5.2 cffi-1.14.0 cryptography-2.9.2 enum34-1.1.10 futures-3.3.0 idna-2.9 ipaddress-1.0.23 iso-639-0.4.5 iso3166-1.0.1 isodate-0.6.0 pyOpenSSL-19.1.0 pycparser-2.20 pycryptodome-3.9.7 requests-2.23.0 singledispatch-3.4.0.3 streamlink-1.4.1+19.g5059d64 urllib3-1.25.9 websocket-client-0.57.0
```
```
j@j:~$ streamlink
/home/j/.local/lib/python2.7/site-packages/streamlink_cli/main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```
```
j@j:~$ streamlink -V
streamlink 1.4.1+19.g5059d64
```

**Comment by johnthecracker** [comment]
This works on my linux box:

sudo apt install python3-pip
pip3 install --upgrade --user git+https://github.com/streamlink/streamlink.git
export PATH="${HOME}/.local/bin:${PATH}"
cp -v *.py /home/j/.local/lib/python3.8/site-packages/streamlink/plugins/

```
j@j:~$ streamlink -V
streamlink 1.4.1+30.gd17f725
```

As filmon plugin and BBC are concerned, this works:

```
url="https://filmon.com/tv/channel/export?channel_id=3268"
streamlink --player=ffplay "$url" best
```

**Comment by bachoo786** [comment]
hey @johnthecracker  thanks for your instructions it works for me too. Just a quick question: is it possible to make the video play into full screen with ffplay? and also I get a title bar saying "pipe" in the video player is it possible to remove it?

thanks

**Comment by gravyboat** [comment]
This issue is getting derailed with off-topic comments so I'm going to lock it.
