### ISSUE TITLE
Can't retrieve certain Youtube stream/qualities

### ISSUE THREAD

**Issue by LuddeFro** [streamlink/streamlink#3021]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

For certain Youtube streams some or all stream qualities are not available.

### Reproduction steps / Explicit stream URLs to test

1. install streamlink 1.4.1
2. install ffmpeg 4.2.3_1  (latest) (cause I read ffmpeg was required for some streams)
3. Find streams by running `streamlink https://www.youtube.com/watch?v=52AQFTuXr84`
4. Only 360p and 720p are available rather than the expected 6 stream qualities ranging from 144p up to 1080p60 that are available on youtube.

### Log output

```
$ streamlink https://www.youtube.com/watch?v=52AQFTuXr84 --loglevel debug
[cli][debug] OS:         macOS 10.13.6
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=52AQFTuXr84
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: 52AQFTuXr84
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
Available streams: 360p (worst), 720p (best)
```

### Additional comments, screenshots, etc.
Other youtube VoDs work fine, but this one specifically does not.
Doesn't work with latest streamlink@master either.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by LuddeFro** [comment]
found another VoD with same issue
https://www.youtube.com/watch?v=36X17Zj8v3E

**Comment by ybekirov** [comment]
I am also experiencing this issue, most videos do not provide any streams at all.

**Comment by LuddeFro** [comment]
If I'm not mistaken further reading suggests that the ones with no streams at all may be "protected" which is also documented as unsupported. But the ones where only some of the streams are available I find more curious.

**Comment by ybekirov** [comment]
@LuddeFro Yeah the videos didn't appear to be private or protected, wonder what that is all about.
