### ISSUE TITLE
Two timecode-related features request

### ISSUE THREAD

**Issue by zhenyahacker** [streamlink/streamlink#3022]
I would like to request two minor improvmenets related to timecodes.

1) Make milliseconds value at log with loglevel trace to be three-digit at all time. Now this value is being represented with two or one digit when event happend at the start of second. Please, make it to append zeroes, like 20:20:29,003. At latest version same timecode will be shown as 20:20:29,3.
This change will make log file more easily human-readable.
2) Make streamlink to set time-date of file being written to disk based not on time when script was executed, but based on time-date of last segment provided by server. Each writing of new segment to output file should update time-date of output file to match to time-date of this written segment. So, for example, complete and finished downloading of VOD video should create a file with same time-date as last segment of VOD had.

**Comment by back-to** [comment]
> At latest version same timecode will be shown as 20:20:29,3.
This change will make log file more easily human-readable.

it is **300** not **003**,
there is not really a big benefit for showing zeros

it is already readable because there are only 3 digits

> Make streamlink to set time-date of file being written to disk based not on time when script was executed, but based on time-date of last segment provided by server. Each writing of new segment to output file should update time-date of output file to match to time-date of this written segment. So, for example, complete and finished downloading of VOD video should create a file with same time-date as last segment of VOD had.

seems totally out of scope for streamlink

**Comment by zhenyahacker** [comment]
> seems totally out of scope for streamlink
It`s out of scope of stream mediaprocessor, but I hope that python`s http(s) downloader gives remote file`s timecode as it`s output data and it can be passed to python`s file output part.
