### ISSUE TITLE
[New Plugin] Add MGTV

### ISSUE THREAD

**Issue by mike8032** [streamlink/streamlink#3023]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Hunan Television or Hunan TV is sometimes referred to as Mango TV, is a provincial satellite TV station. It launched in January 1997 and is currently China's second-most-watched channel.

### Example stream URLs

https://www.mgtv.com/live/

there are 4 channels comming in flv.
for example: https://pcws.qing.mgtv.com/nn_live/nn_x64/cWlkPSZzPTZkZDZlYzBkOTkxOTQzZWVmNDRkMWUzODZlNWFmZjFkJmVzPTE1OTE5ODE0NzAmdXVpZD0wYzI3YmYzNzRhYzlhZjllNGEwYTJmOTMzNTFkNGFiMS0yZTdlYjQyOCZ2PTImYXM9MCZjZG5leF9pZD13c19wYzM,/HNGJMPP360.flv

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
The website is very slow outside of china,
it is unmaintainable for Streamlink.

closing
