### ISSUE TITLE
[New Plugin] Add cl-live.com

### ISSUE THREAD

**Issue by SGRK901** [streamlink/streamlink#3029]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

cl-live.com is a new video streaming service under LDH entertainment company, providing artist live streams, variety shows on demand and live concerts.

### Example stream URLs

1. https://www.cl-live.com/programs/ondemand/uaTj4ds5VuZVsCMva7C7Hv
2. https://www.cl-live.com/programs/cast/3Sb3i75Y1KDDRhriMxoTsW

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by wiresp33d** [comment]
Hi all,

I found that cl-live is using AES-128 to encrypt the streaming file. Is there any reference to check?

**Comment by back-to** [comment]
> I found that cl-live is using AES-128 to encrypt the streaming file. Is there any reference to check?

nothing special, you just need the correct cookies and headers

for this website you will need to open an api for some cookies

```json
            "api": {
                "url": "https:\u002F\u002Fapi.cl-live.com",
                "key": "AAAAAAAA",
                "authDomain": "cl-live.com"
            },
```

```py
        self.session.http.get('https://api.cl-live.com/v1/license/ondemand/AAAAAAA',
                              headers={
                                  'X-Api-Key': 'AAAA',
                              })
```

**Comment by wiresp33d** [comment]
Thanks @back-to 

I have retrieved the key and relevant cookie, but I am not sure how to put that cookie when I use HLSStream, plus each segment of stream seems encrypted by aes.key. 

I tried to use aes as key to find the clue. There are few example in plugins and I still cannot verified how to decrypt the stream after downloading xxx.ts. 
```
grep -ir aes * ./src/streamlink/plugins/*
```

Once again, thank you for your help!

**Comment by back-to** [comment]
@wiresp33d 
you don't need to do anything besides the cookies,
just use HLSStream with it.

>  how to put that cookie when I use HLSStream,

you don't need to, it is a session.

**Comment by wiresp33d** [comment]
@back-to
I will take time to look at it! Thank you, friend! You are the best!!

**Comment by wiresp33d** [comment]
Hi all,

Thanks to @back-to, I finally done! However, I haven'y found any entry point to live video.
So, I cannot parse any info from https://www.cl-live.com/programs/cast/3Sb3i75Y1KDDRhriMxoTsW

Fortunately, the new plugin can play recorded video smoothly.
If it is fine to you, I will send the PR.

Cheers.

**Comment by SGRK901** [comment]
> Hi all,
> 
> Thanks to @back-to, I finally done! However, I haven'y found any entry point to live video.
> So, I cannot parse any info from https://www.cl-live.com/programs/cast/3Sb3i75Y1KDDRhriMxoTsW
> 
> Fortunately, the new plugin can play recorded video smoothly.
> If it is fine to you, I will send the PR.
> 
> Cheers.

Thanks!! The live videos don't have playback option just yet. I think that feature will be provided later on.

**Comment by wiresp33d** [comment]
Hi @back-to ,

PR had sent. Sorry to bother you. During develop plugin, I found that two questions need your enlightenment. ^^

1. I am not sure how to run the unit test or mock test. I move the test script near the plugin and execute it. It pops up "No Module ... : streamlink" etc. Is there any reference to check?

2. After completing portion of plugin, I always replace the original plugin with new prototype for testing. Is there better way to do that rather copy & paste?

Thank you in advance!!

**Comment by back-to** [comment]
>  I haven'y found any entry point to live video.

are there even livestreams on this website?
