### ISSUE TITLE
twitch login

### ISSUE THREAD

**Issue by Mylo17** [streamlink/streamlink#3031]
is there a way to log in twitch,none of the plugins listed in the documentation seem to be able t do that.
thans a lot

**Comment by bastimeyer** [comment]
Maybe you should search before asking questions...
https://github.com/streamlink/streamlink/issues?q=twitch+login
- #2846
- https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

It's also noted in the release changelog:
https://github.com/streamlink/streamlink/blame/1.4.1/CHANGELOG.md#L26
https://github.com/streamlink/streamlink/blame/1.4.1/CHANGELOG.md#L217-L219
