### ISSUE TITLE
Picarto - broken - infra update or change suspected

### ISSUE THREAD

**Issue by mjevans** [streamlink/streamlink#3040]
- [X] This is a plugin issue and I have read the contribution guidelines.

Attempt to play any picarto.tv stream fails with

(HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0))

```
streamlink -l trace https://picarto.tv/ishoka
[13:41:12,435][cli][debug] OS:         Linux-5.7.1-arch1-1-x86_64-with-glibc2.2.5
[13:41:12,435][cli][debug] Python:     3.8.3
[13:41:12,436][cli][debug] Streamlink: 1.4.1+22.gbc3951a
[13:41:12,436][cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[13:41:12,436][cli][info] Found matching plugin picarto for URL https://picarto.tv/ishoka
error: Unable to open URL: https://api.picarto.tv/v1/channel/name/ishoka (HTTPSConnectionPool(host='api.picarto.tv', port=443): Read timed out. (read timeout=20.0))
```

Just before running this test I switched to the archlinux streamlink-git package, which pulled in the latest source just in case a fix was already committed.

In browser, debug inspection shows a series of xhr requests from iv.js to endpoints on 1-edge5-us-east.picarto.tv for vnd.apple.mpegurl and mp2t fragments.

The default HLS connection type is in use, but mp4 and RTML Flash are also stream types.

**Comment by back-to** [comment]
seems like a temporary issue
https://github.com/streamlink/streamlink/issues/2841#issuecomment-602116474

**Comment by mjevans** [comment]
Broken the same way today only now they have a CDN endpoint closer to me: 1-edge1-us-west.picarto.tv

I think the prior time was probably an A / B test, unsure if this is the new normal.

**Comment by mjevans** [comment]
30 min later, it's working the old way again @.@

> Broken the same way today only now they have a CDN endpoint closer to me: 1-edge1-us-west.picarto.tv
> 
> I think the prior time was probably an A / B test, unsure if this is the new normal.
