### ISSUE TITLE
Pixiv has removed device_token cookie

### ISSUE THREAD

**Issue by cykac04** [streamlink/streamlink#3047]
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.

### Description

Pixiv has removed device_token cookie. Cannot login with the current plugin.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
They did not.

**Comment by Mokou** [comment]
I couldn't find it for the life of me. Putting something random there did the trick though.
