### ISSUE TITLE
Abematv login requirement?

### ISSUE THREAD

**Issue by gnatg** [streamlink/streamlink#3065]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Unable to download a paid vod stream on abema.tv, maybe login is required but I can't find the way to log in abema.tv.

### Reproduction steps / Explicit stream URLs to test

1. Try to use the link(https://abema.tv/channels/payperview-1/slots/AREWQprbaghuBV) for a file output and failed.
2. Try to use other free stream and it's alright.

### Log output

```
streamlink abema.tv/channels/payperview-1/slots/AREWQprbaghuBV bes
t -o output.ts
[cli][info] Found matching plugin abematv for URL abema.tv/channels/payperview-1
/slots/AREWQprbaghuBV
error: Unable to open URL: https://api.abema.io/v1/media/slots/AREWQprbaghuBV (4
04 Client Error: Not Found for url: https://api.abema.io/v1/media/slots/AREWQprb
aghuBV)
```

### Additional comments, screenshots, etc.

Thank you very much and sorry if this is stupid since I'm new to github:)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> maybe login is required but I can't find the way to log in abema.tv.

this is not supported by streamlink
