### ISSUE TITLE
[New Plugin] trovo.live

### ISSUE THREAD

**Issue by ChristophKrause** [streamlink/streamlink#3069]
## Plugin Request

- [X ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
Trovo (https://trovo.live/) is a new streaming platform for PC & mobile games by Tencent.
readmore: https://www.dexerto.com/entertainment/what-is-trovo-live-tencents-streaming-platform-for-pc-mobile-games-1386428
Short: It is a Twitch/Mixxer clone from china, which might get very successfull in asia.
Trovo is currently beta

### Example stream URLs
1. https://trovo.live/ (not really an example, but shows default content)
2. https://trovo.live/MineyCODM (a user there)
3. https://trovo.live/Eirphire (another user)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by tr0n64** [comment]
Please guys add Trove

**Comment by gravyboat** [comment]
@tr0n64 I noted that we aren't going to do so and why here: https://github.com/streamlink/streamlink/pull/3076#issuecomment-660692992. Spamming issues is pointless and just wastes your time and ours. You can copy the code from that other PR and sideload it using the instruction here if you really want to: https://streamlink.github.io/cli.html?#sideloading-plugins When Trovo actually gets out of beta and if they get their act together on the way they do streaming we'll consider asking them at that time. Closing and locking.
