### ISSUE TITLE
Twitch plugin issue

### ISSUE THREAD

**Issue by squidee100** [streamlink/streamlink#3073]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
Windows 64x
Never used this software before.
Is this maybe an incorrect API URL?

### Reproduction steps / Explicit stream URLs to test

1. Fresh install
2. Run `livestreamer twitch.tv/xqcow source` in cmd
3. Error

### Log output

```
[cli][info] Found matching plugin twitch for URL twitch.tv/xqcow
error: Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> livestreamer

https://streamlink.github.io/
