### ISSUE TITLE
Functionality to watch protected Facebook streams

### ISSUE THREAD

**Issue by buradpujan** [streamlink/streamlink#3075]
## Feature Request

- [ x] This is a feature request and I have read the contribution guidelines.

### Description

For Facebook live streams which are location specific ( is streamed with custom visibility), Facebook login is required to ensure stream can be viewed. Add a feature for Facebook plugin to enter login credentials to watch the streams.
Example of such stream :  https://www.facebook.com/LaLiga/videos/935733536899425/
The above stream can be viewed from South-Asia( Indian Subcontinent).
On trying to use "The Stream Detector" on Firefox, and running the stream, the output is :
"Found matching plugin dash for URL https://video.fbom4-1.fna.fbcdn.net/hvideo-0cln-1atn/_nc_cat-1/v/rT2OP7ufBB7aAA2UzwlwK/live-dash/dash-abr5/3304514022918467.mpd?_nc_rl=AfAGADuhPkCpSHPP&aaf=1&ms=m_CN&replica=0&oh=45a40ab627c64bbbb1583b54f450fd4f&oe=5F1240B0
error: https://video.fbom4-1.fna.fbcdn.net/hvideo-0cln-1atn/_nc_cat-1/v/rT2OP7ufBB7aAA2UzwlwK/live-dash/dash-abr5/3304514022918467.mpd?_nc_rl=AfAGADuhPkCpSHPP&aaf=1&ms=m_CN&replica=0&oh=45a40ab627c64bbbb1583b54f450fd4f&oe=5F1240B0 is protected by DRM"

### Expected / Actual behavior

If a login feature was enabled, it would enable StreamLink to catch the stream and play it on media player.
Current Response: No playable streams found on this URL: https://www.facebook.com/LaLiga/videos/935733536899425/

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This is unneeded. Noted back in [2018](https://github.com/streamlink/streamlink/issues/1738#issuecomment-394748034), set your login cookies via `--http-cookie`.

**Comment by LinkTree3** [comment]
Be very careful of trying to watch protected Facebook streams! I tried to do it myself a few weeks ago and my Facebook account was locked out immediately for suspicious behavior. I still haven't been able to restore it to this day.

All I did was take the cookies from my browser session and paste them in the `--http-cookie` arg. It fetched the stream but locked me out right after.
