### ISSUE TITLE
Continued retries

### ISSUE THREAD

**Issue by mewnm** [streamlink/streamlink#3078]
I use this command, but it only download the first vod, if the stream disconnect and another one is started it won't download:
streamlink --retry-streams 10 https://www.twitch.tv/user best -o E:\1.mp4

**Comment by bastimeyer** [comment]
Use the search function, this has been answered at least a dozen times.

> if the stream disconnect and another one is started it won't download

When a channel restarts their stream on Twitch, a new stream URL with a new access token needs to be aquired. This means that the already running Streamlink process can't be used anymore, as every retry/timeout/buffering related parameter only affects the already resolved HLS stream URL of the old session. These parameters are meant for client side connection issues where the source stream is still live and accessible. Just run Streamlink in a loop.

**Comment by mewnm** [comment]
> Use the search function, this has been answered at least a dozen times.
> 
> > if the stream disconnect and another one is started it won't download
> 
> When a channel restarts their stream on Twitch, a new stream URL with a new access token needs to be aquired. This means that the already running Streamlink process can't be used anymore, as every retry/timeout/buffering related parameter only affects the already resolved HLS stream URL of the old session. These parameters are meant for client side connection issues where the source stream is still live and accessible. Just run Streamlink in a loop.

can you say what command to loop? coudn't find

**Comment by johnthecracker** [comment]
repeat
	streamlink %url% best
until 1 = 2

**Comment by mewnm** [comment]
> ```
> repeat
> ```

Got this error: https://i.imgur.com/bcyXnoM.png

**Comment by johnthecracker** [comment]
"repeat until" is just a principle you have to implement.
You need to know basic programming principles and what loops are and how to use them.

Bastimeyer had said run streamlink i a loop.
I tried to be a little more descriptive, but as I see I was unsuccessful.

repeat until are specific keywords from Pascal, and yes, I can program.

**Comment by mewnm** [comment]
> "repeat until" is just a principle you have to implement.
> You need to know basic programming principles and what loops are and how to use them.
> 
> Bastimeyer had said run streamlink in a loop.
> I tried to be a little more descriptive, but as I see I was unsuccessful.
> 
> repeat until are specific keywords from Pascal, and yes, I can program.

that would be a good feature

**Comment by gravyboat** [comment]
@mewnm It's outside the scope for Streamlink, we've discussed it before and it's not a feature we're going to add. People can easily write loops to handle this.

**Comment by mewnm** [comment]
> @mewnm It's outside the scope for Streamlink, we've discussed it before and it's not a feature we're going to add. People can easily write loops to handle this.

Ok you can write this for me in 1min

**Comment by gravyboat** [comment]
@mewnm That's not going to happen, the internet is full of resources, give your favorite search engine a shot and you can learn to do it yourself. There's nothing left to discuss in regards to this issue so I'm locking it now.
