### ISSUE TITLE
tv8 broken

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink#3079]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Looks like something is changed, tv8 plugin doesn't work anymore

### Reproduction steps / Explicit stream URLs to test

1. `streamlink --http-no-ssl-verify https://www.tv8.com.tr/canli-yayin`

### Log output

```
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin tv8 for URL https://www.tv8.com.tr/canli-yayin
error: No playable streams found on this URL: https://www.tv8.com.tr/canli-yayin
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
This may help temporarily:

```
C:\>streamlink hls://"https://tv8.personamedia.tv/tv8hls?sid=fa38c288-e97e-495c-8154-f29d11d355e3&fmt=hls" best
[cli][info] Found matching plugin hls for URL hls://https://tv8.personamedia.tv/tv8hls?sid=fa38c288-e97e-495c-8154-f29d11d355e3&fmt=hls
[cli][info] Available streams: 360p (worst), 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
```

**Comment by fenopa** [comment]
@johnthecracker 
Thanks, it works. That sid= does not change right, it's same for everyone?

**Comment by johnthecracker** [comment]
It worked in last hour... I don't know for how long it lasts.

**Comment by fenopa** [comment]
Ok will do user agent thing if it doesn't work, thank you for your help

**Comment by fenopa** [comment]
thank you so much for fixing this so quickly! <3 using dev build for it, works great!

**Comment by fenopa** [comment]
@back-to
Sorry for bothering you for this again, I noticed when using it that it doesn't ignore the ad segments when streaming.

I observed it a llitle and got this playlist file when an ad started:

```
#EXTM3U
#EXT-X-TARGETDURATION:8
#EXT-X-VERSION:6
#EXT-X-DISCONTINUITY-SEQUENCE:0
#EXT-X-MEDIA-SEQUENCE:10
#EXTINF:4.000,10-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575418204.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:4.000,11-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575458204.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:4.000,12-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575498204.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:4.000,13-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575538204.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:4.000,14-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575578204.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:4.000,15-0-f:0
https://persona-tv8-live.ercdn.net/hls/v_r1/seg15960575618204.ts?st={redactedtoken]&e={redactedtoken]
#EXT-X-DISCONTINUITY
#EXTINF:5.360,16-1-f:27
https://persona-tv8-ad.ercdn.net/3727/hls/v_r1/0.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:5.320,17-1-f:26
https://persona-tv8-ad.ercdn.net/3727/hls/v_r1/53600.ts?st={redactedtoken]&e={redactedtoken]
#EXTINF:7.960,18-1-f:26
https://persona-tv8-ad.ercdn.net/3727/hls/v_r1/106800.ts?st={redactedtoken]&e={redactedtoken]
```

**Normal stream segment url structure:** https://persona-tv8-live.ercdn.net/hls/v_r1/
**Ad segment URL structure after #EXT-X-DISCONTINUITY:** https://persona-tv8-ad.ercdn.net**/3727/**hls/

That 3727 is probably variable to different ads.

Would it possible to ignore these segments if there's a variable between root url and /hls/ in the segment URL?

I saw this when looking for it but I think that was transitioned from a general option to twitch only option? https://github.com/streamlink/streamlink/pull/2369

Sorry to bother you again, if it's too much work just ignore this.
