### ISSUE TITLE
Twitch get Live Stream urls in PHP

### ISSUE THREAD

**Issue by mittultechnobrave** [streamlink/streamlink#3087]
I am trying to get live streaming urls in response based on Twitch video URL something like this https://pwn.sh/tools/streamapi.py?url=https://www.twitch.tv/sypherpk in PHP. 

So I have found this URL https://pwn.sh/tools/getstream.html in which I came to know that they are using Streamlink (https://streamlink.github.io/) hence I have installed Streamlink and I am then I have added below code in my php file. 

`echo exec('streamlink https://www.twitch.tv/sypherpk');`

Here I am able to get the response saying 

> Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60,
> 1080p60 (best)

So I am clear that Streamlink is installed and working fine. 

Hence now I am trying to get list of urls in response based on my Twitch live stream URL to get stream urls something like this https://pwn.sh/tools/streamapi.py?url=https://www.twitch.tv/sypherpk , hence I have researched in Streamlink APIs and found out  that `--stream-url` is helpful hence I pasted below code in my php file. 

`echo exec('streamlink --stream-url https://www.twitch.tv/sypherpk ');` 

but it keeps giving me same response 

> Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60,
> 1080p60 (best)

I even tried below command ...

`echo exec('streamlink --stream-url https://www.twitch.tv/sypherpk source');`

But still same response. 

Can someone guide me what I am doing wrong here ? What am I missing ? 

Any help or hint will be highly appreciated. 

Thanks

**Comment by bastimeyer** [comment]
> Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60,
1080p60 (best)
> `streamlink --stream-url https://www.twitch.tv/sypherpk source`
> But still same response.

You are specifying an invalid quality and the output is definitely not the same.
https://streamlink.github.io/cli.html

Also, using Streamlink for what you're trying to achieve here is rather questionable in terms of re-streaming/re-hosting content, so I will close this thread now. Not to mention that using Streamlink for two simple API calls is totally unnecessary and slow.
