### ISSUE TITLE
[Twitch] TypeError when downloading multiple streams

### ISSUE THREAD

**Issue by Instinctlol** [streamlink/streamlink#3089]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

I've got this [small application (automatic-twitch-recorder)](https://github.com/Instinctlol/automatic-twitch-recorder/tree/webhooks) that checks whether a twitch streamer is online and records them (aka downloads the stream) if they are currently streaming. However, a `TypeError` is thrown in `TwitchHLSStreamWorker` whenever a streamer is currently being recorded and another streamer goes online that also is about to be recorded. Recording a single streamer at the same time seems to work fine.

### Reproduction steps / Explicit stream URLs to test

1. Download my [app](https://github.com/Instinctlol/automatic-twitch-recorder/tree/webhooks), install requirements, .. you know the deal.
2. Start atr_cmd.py and daemon.py (you will be asked for your client id and client secret)
3. In atr_cmd.py, add any twitch streamer that is currently online and streaming by typing `add <random online streamer #1>`, then type `start` to start the checking & recording routine
4. wait an indefinite amount of time so the download of the stream starts (a folder named `<random online streamer #1>` will be created next to the *.py scripts)
5. In atr_cmd.py, add another twitch streamer that is currently streaming by typing `add <random online streamer #2>`
6. Now observe the daemon.py log, see Log output (I added a print statement in process_sequences to log self)

### Log output

```
info:root:POST request,
Path: /cmd/
Headers:
Host: 127.0.0.1:1234
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 34
Content-Type: application/json



Body:
{"cmd": "add", "args": ["forsen"]}

info:root:POST request,
Path: /cmd/
Headers:
Host: 127.0.0.1:1234
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 28
Content-Type: application/json



Body:
{"cmd": "start", "args": []}

forsen is live. Saving stream in best quality to E:\Downloads\automatic-twitch-recorder\forsen\2020-07-27 18.50.01 - forsen - @forsen, Games and shit!.ts.
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, initial daemon)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 11392)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 11392)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 11392)>
info:root:POST request,
Path: /cmd/
Headers:
Host: 127.0.0.1:1234
User-Agent: python-requests/2.24.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 32
Content-Type: application/json



Body:
{"cmd": "add", "args": ["nymn"]}

<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 11392)>
NymN is live. Saving stream in best quality to E:\Downloads\automatic-twitch-recorder\nymn\2020-07-27 18.50.32 - NymN - NYMN'S NEWS NETWORK   @nymnion on twitterinstayoutube.ts.
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, initial daemon)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 11392)>
Exception in thread Thread-TwitchHLSStreamWorker:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\segmented.py", line 59, in run
    for segment in self.iter_segments():
  File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\hls.py", line 307, in iter_segments
    self.reload_playlist()
  File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\hls.py", line 235, in reload_playlist
    self.process_sequences(playlist, sequences)
  File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\plugins\twitch.py", line 212, in process_sequences
    return super(TwitchHLSStreamWorker, self).process_sequences(playlist, sequences)
TypeError: super(type, obj): obj must be an instance or subtype of type

<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 17796)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 17796)>
<TwitchHLSStreamWorker(Thread-TwitchHLSStreamWorker, started daemon 17796)>

Process finished with exit code -1
```

### Additional comments, screenshots, etc.

I tried this on Windows while using Python 3.6, Python 3.8. I also tried using the [Session object](https://streamlink.github.io/api_guide.html#session-object) with no luck, though I didn't use any options. If you're wondering where I'm using streamlink: [see watch method in Watcher.py](https://github.com/Instinctlol/automatic-twitch-recorder/blob/webhooks/watcher.py#L28).

Any help is appreciated, thank you.

**Comment by bastimeyer** [comment]
I'm not sure why this is happening, but when reading a stream from the [`TwitchHLSStreamReader`](https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink/plugins/twitch.py#L219-L221), something is wrong with the internal stream writer+worker threads when making consecutive `open()` calls to the reader. The regular `HLSStreamReader` doesn't have this problem for some reason.

I don't think though that it's a problem with the `TwitchHLSStream{,Reader,Writer,Worker}` classes themselves, as they simply override/extend logic that's independent of how the threads work. The Twitch plugin is however the only plugin which overrides the stream writer with custom logic, so it's possible that something is not working correctly in the parent classes and it got unnoticed so far.

----

This is a simple error reproduction:

```python
import sys
from streamlink import Streamlink

for i in range(2):
    try:
        print(f"Opening stream {i}")
        stream = Streamlink().streams(sys.argv[1])["best"].open()
        stream.read(8)
    except Exception as e:
        print(e)
    finally:
        stream.close()
```

Works when using the regular `HLSStreamReader` (HLS playlist input):
```bash
python ./reproduction.py "$(streamlink --stream-url twitch.tv/CHANNEL best)"
```
```
Opening stream 0
Opening stream 1
```

Breaks when using the `TwitchHLSStreamReader` (Twitch plugin input):
```bash
python ./reproduction.py twitch.tv/CHANNEL
```
```
Opening stream 0
Opening stream 1
Exception in thread Thread-TwitchHLSStreamWriter:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/basti/repos/streamlink/src/streamlink/stream/segmented.py", line 169, in run
    self.write(segment, result)
  File "/home/basti/repos/streamlink/src/streamlink/plugins/twitch.py", line 216, in write
    return super(TwitchHLSStreamWriter, self).write(sequence, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

----

As the error message implies, something is wrong with the class inheritance of the thread, but I don't understand why the inheriting `TwitchHLSStreamWriter` is causing problems here and the regular `HLSStreamWriter` not, as both inherit from the `SegmentedStreamWriter` where the thread logic is defined.

The error also doesn't occur all the time. Modifying any content and triggering a recompilation of the byte code cache makes it work for some reason. Same when setting the `PYTHONDONTWRITEBYTECODE=1` env var.

**Comment by bastimeyer** [comment]
I've spent a bit more time finding the cause of this issue...

First off, the reason why the regular HLS subclasses aren't running into this issue is because they are simply overriding the abstract methods of the SegmentedStream classes, whereas the TwitchHLS subclasses need to call their HLS super methods via the py2-supported `super(TheClass, self)` bound-super-proxy call:
https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink/plugins/twitch.py#L216

Replacing these calls with simple `super()` calls or directly referencing the parent classes would "fix" the issue, but that's not what I want to do here.

The error message says `TypeError: super(type, obj): obj must be an instance or subtype of type`, which means that for some reason, the class instance of the called method does not inherit from its supposed parent class, which is weird, especially if it works just fine when just one streamlink session is being used at once, and only fails sometimes when two or more Streamlink sessions are run at the same time.

That's why I've added debug messages (check diff below) to the writer thread's `write()` method with information about its name (with a unique ID added to it) and the class's unique object-ID, so that I can let it run in parallel without using debug tools and setting breakpoints.

By comparing the IDs of the referencing class of each running thread, you can see that when `TwitchHLSStreamWriter.write` gets called in the first thread and it tries to call its super method, the `TwitchHLSStreamWriter` reference it uses surprisingly does have a different ID as soon as the second thread starts running. That's why it's not considered the parent of the current instance anymore and the TypeError gets raised. `self.reader.__writer__` on the other hand, which is the stored class reference on the reader, stays the same. Check the log below.

This might be something obvious which I'm not seeing as an inexperienced python developer, but it doesn't make any sense to me why the reference gets changed by the second thread, and that only sometimes.

So the third way of fixing the issue would be replacing all the class references with their reader's stored references, but that doesn't seem right.

@back-to, do you have any idea why this is happening?

```
Opening stream 0
TwitchHLSStreamReader.open(): self.__writer__ = 000055f764e6ee80
Thread-TwitchHLSStreamWriter-46735.write(): TwitchHLSStreamWriter = 000055f764e6ee80
Thread-TwitchHLSStreamWriter-46735.write(): self.reader.__writer__ = 000055f764e6ee80
Opening stream 1
Thread-TwitchHLSStreamWriter-46735.write(): TwitchHLSStreamWriter = 000055f765345260
Thread-TwitchHLSStreamWriter-46735.write(): self.reader.__writer__ = 000055f764e6ee80
Exception in thread Thread-TwitchHLSStreamWriter-46735:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/basti/repos/streamlink/src/streamlink/stream/segmented.py", line 168, in run
    self.write(segment, result)
  File "/home/basti/repos/streamlink/src/streamlink/plugins/twitch.py", line 218, in write
    return super(TwitchHLSStreamWriter, self).write(sequence, *args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
TwitchHLSStreamReader.open(): self.__writer__ = 000055f765345260
Thread-TwitchHLSStreamWriter-388.write(): TwitchHLSStreamWriter = 000055f765345260
Thread-TwitchHLSStreamWriter-388.write(): self.reader.__writer__ = 000055f765345260
```

```diff
diff --git a/src/streamlink/plugins/twitch.py b/src/streamlink/plugins/twitch.py
index 3f602d01..51cc3c94 100644
--- a/src/streamlink/plugins/twitch.py
+++ b/src/streamlink/plugins/twitch.py
@@ -213,6 +213,8 @@ class TwitchHLSStreamWorker(HLSStreamWorker):
 class TwitchHLSStreamWriter(HLSStreamWriter):
     def write(self, sequence, *args, **kwargs):
         if not (self.stream.disable_ads and sequence.segment.ad):
+            print("%s.write(): TwitchHLSStreamWriter = %016x" % (self.name, id(TwitchHLSStreamWriter)))
+            print("%s.write(): self.reader.__writer__ = %016x" % (self.name, id(self.reader.__writer__)))
             return super(TwitchHLSStreamWriter, self).write(sequence, *args, **kwargs)
 
 
diff --git a/src/streamlink/stream/segmented.py b/src/streamlink/stream/segmented.py
index d33cc9e4..60e58b83 100644
--- a/src/streamlink/stream/segmented.py
+++ b/src/streamlink/stream/segmented.py
@@ -94,7 +94,8 @@ class SegmentedStreamWriter(Thread):
         self.executor = futures.ThreadPoolExecutor(max_workers=threads)
         self.futures = queue.Queue(size)
 
-        Thread.__init__(self, name="Thread-{0}".format(self.__class__.__name__))
+        from random import randint
+        Thread.__init__(self, name="Thread-{0}-{1}".format(self.__class__.__name__, randint(1, 100000)))
         self.daemon = True
 
     def close(self):
@@ -188,6 +189,7 @@ class SegmentedStreamReader(StreamIO):
     def open(self):
         buffer_size = self.session.get_option("ringbuffer-size")
         self.buffer = RingBuffer(buffer_size)
+        print("%s.open(): self.__writer__ = %016x" % (self.__class__.__name__, id(self.__writer__)))
         self.writer = self.__writer__(self)
         self.worker = self.__worker__(self)
 

```

**Comment by back-to** [comment]
with the current version, it seems to be fixed.

**Comment by Instinctlol** [comment]
It seems the [reproduction script](https://github.com/streamlink/streamlink/issues/3089#issuecomment-664832118) made by @bastimeyer is working with 1.7.0, but my app is now experiencing another, possibly related, error:

> Exception in thread Thread-TwitchHLSStreamWorker:
> Traceback (most recent call last):
>   File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\segmented.py", line 84, in run
>     for segment in self.iter_segments():
>   File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\hls.py", line 321, in iter_segments
>     self.reload_playlist()
>   File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\stream\hls.py", line 241, in reload_playlist
>     self.playlist_reload_time = self._playlist_reload_time(playlist, sequences)
>   File "E:\Downloads\automatic-twitch-recorder\virtualenv\lib\site-packages\streamlink\plugins\twitch.py", line 88, in _playlist_reload_time
>     return super(TwitchHLSStreamWorker, self)._playlist_reload_time(playlist, sequences)
> TypeError: super(type, obj): obj must be an instance or subtype of type

**Comment by back-to** [comment]
@Instinctlol 
try the git version of streamlink

**Comment by Instinctlol** [comment]
Thanks, git version seems to work 👍
