### ISSUE TITLE
Streamlink session no_plugins option (because of high RAM usage)

### ISSUE THREAD

**Issue by brachna** [streamlink/streamlink#3095]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

Add option to disable loading of plugins for Streamlink session when using API.
Can be used like this:
```session = streamlink.Streamlink( no_plugins=True )```
The feature can be useful to those who use Streamlink API inside their own scripts, who don't care about plugins as it will lower RAM usage.

### Expected / Actual behavior

The option will significantly reduce memory footprint (see screenshots below).
By default Session object eats additional ~240MB of RAM. In my case I have several scripts each with Streamlink Session inside, so it adds up to several GBs of RAM usage.
Current workaround is to manually remove all plugins from "<PythonDir>\Lib\site-packages\streamlink\plugins".

### Additional comments, screenshots, etc.

Default Streamlink session object:
![streamlink_with_plugins](https://user-images.githubusercontent.com/5756107/89080495-b6464a80-d391-11ea-8b34-702c6295aecb.jpg)

Streamlink session object after all plugins were removed:
![streamlink_no_plugins](https://user-images.githubusercontent.com/5756107/89080450-88f99c80-d391-11ea-834b-65e573192362.jpg)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> By default Session object eats additional ~240MB of RAM

I can't reproduce this. In a clean environment, it's about 38MiB on my system(s) using Python 3.8.5 while reading a stream. And Streamlink with streamlink-cli uses ~41MiB while reading a stream.

> Current workaround is to manually remove all plugins from

Just subclass Streamlink's Session class and override the `load_builtin_plugins` method:
https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink/session.py#L464
Then only load the plugin(s) you need.

**Comment by brachna** [comment]
Ah, I had streamlink 1.4.1, silly me. Thanks for subclass suggestion.
