### ISSUE TITLE
[Question] How do i increase the number of viewers?

### ISSUE THREAD

**Issue by PedroHFranco** [streamlink/streamlink#3100]
Hi, i 'm new using StreamLink, how do i increase the number of viewers?
I have found this project from livestreamer and there was explaim to set a proxylist in script folder, is here the same way ?

**Comment by bastimeyer** [comment]
What do you mean with "increase the number of viewers"?
Are you trying to view-bot your streams? This is explicitly unsupported.

**Comment by PedroHFranco** [comment]
Yes, i was trying to view-bot.
What about i run this in a docker image and run N containers ?

Do u know any view-bot ? In Phyton, Node or C#?
