### ISSUE TITLE
Crunchyroll stopped authenticating again 

### ISSUE THREAD

**Issue by KBD20** [streamlink/streamlink#3101]
It appears that issue #2785 is repeating, so Crunchyroll changed their access token again.

Does anyone know how to find the access token in the first place? As a temporary measure.

**Comment by locknet11** [comment]
Yes, I can confirm this issue, not working again.

**Comment by KBD20** [comment]
@alzamer2 How did you find the auth token last time?

**Comment by alzamer2** [comment]
let me check

**Comment by alzamer2** [comment]
i just checked my code and I can use access_token "WveH9VkPLrXvuNm"
are you sure it's not working with you?

**Comment by locknet11** [comment]
@KBD20 I fixed it using --crunchyroll-purge-credentials

**Comment by alzamer2** [comment]
@locknet11 what does --crunchyroll-purge-credentials do?

**Comment by locknet11** [comment]
@alzamer2 Sorry, don't know why but it seems to be working fine again. Yesterday I couldn't open streamings from crunchyroll and today in the morning neither. It's working as usual again. Thanks for check!

**Comment by KBD20** [comment]
Yeah purge credentials worked for me, Crunchyroll must have changed something that requires it.
