### ISSUE TITLE
Adding login username/password to Chaturbate plugin?

### ISSUE THREAD

**Issue by jonmdev** [streamlink/streamlink#3102]
I am using the Chaturbate plugin which works fine, but I am wondering how one could add their username and password so as to be able to access ticketed/private streams via Streamlink. I see someone created a simple Javascript version here which claimed to do it but that was 2017 and I'm not sure how to adapt it:

https://github.com/streamlink/streamlink/issues/1111

Would there be any simple code modification that would allow this plugin to work with username/password info?

I know this is no longer formally a plugin but I'm still wondering how one could go about doing it and I'm hoping you can give me some pointers nonetheless on how it might be made to work.

Thanks.

```
import re
import uuid

from streamlink.plugin import Plugin
from streamlink.plugin.api import validate
from streamlink.stream import HLSStream

API_HLS = "https://chaturbate.com/get_edge_hls_url_ajax/"

_url_re = re.compile(r"https?://(\w+\.)?chaturbate\.com/(?P<username>\w+)")

_post_schema = validate.Schema(
    {
        "url": validate.text,
        "room_status": validate.text,
        "success": int
    }
)


class Chaturbate(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        match = _url_re.match(self.url)
        username = match.group("username")

        CSRFToken = str(uuid.uuid4().hex.upper()[0:32])

        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "X-CSRFToken": CSRFToken,
            "X-Requested-With": "XMLHttpRequest",
            "Referer": self.url,
        }

        cookies = {
            "csrftoken": CSRFToken,
        }

        post_data = "room_slug={0}&bandwidth=high".format(username)

        res = self.session.http.post(API_HLS, headers=headers, cookies=cookies, data=post_data)
        data = self.session.http.json(res, schema=_post_schema)

        self.logger.info("Stream status: {0}".format(data["room_status"]))
        if (data["success"] is True and data["room_status"] == "public" and data["url"]):
            for s in HLSStream.parse_variant_playlist(self.session, data["url"]).items():
                yield s


__plugin__ = Chaturbate

```

**Comment by bastimeyer** [comment]
Plugins of that kind are unsupported and questions regarding that don't belong here. You'll have to figure it out yourself.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
