### ISSUE TITLE
Video and audio not in sync for Periscope plugin stream

### ISSUE THREAD

**Issue by waldyd** [streamlink/streamlink#3103]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

The stream file (*.ts) generated by this plug-in has the audio and video not in sync. Here it is the command used and the output is attached.

`streamlink -p mplayer https://www.pscp.tv/w/1DXxyALBdMbxM best --hls-segment-threads 5 --hls-segment-attempts 99999 --hls-timeout 99999 -o CC_CabinFever_20.ts`

[CC_CabinFever_20.zip](https://github.com/streamlink/streamlink/files/5046065/CC_CabinFever_20.zip)

### Reproduction steps / Explicit stream URLs to test

1. streamlink -p mplayer https://www.pscp.tv/w/1DXxyALBdMbxM best --hls-segment-threads 5 --hls-segment-attempts 99999 --hls-timeout 99999 -o CC_CabinFever_20.ts
2. ...
3. ...

### Log output

```
[cli][debug] OS:         Linux-5.7.11-100.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
[cli][debug] Python:     3.7.8
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.57.0)
[cli][info] Found matching plugin periscope for URL https://www.pscp.tv/w/1DXxyALBdMbxM
[plugin.periscope][info] Live Stream ended, using replay instead
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 224p (worst), 320p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 1958
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 1958
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Download of segment 0 complete
[stream.hls][debug] Download of segment 1 complete
[cli][debug] Checking file output

```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
As you can see here, the periscope plugin is returning a regular HLS stream:
https://github.com/streamlink/streamlink/blob/1.5.0/src/streamlink/plugins/periscope.py#L60-L64

This means that Streamlink doesn't do any muxing, which further means that if there are sync issues, it's not caused by Streamlink, because all Streamlink is doing is concatenating HLS stream segments (MPEGTS chunks) into a single output stream. You could do this yourself manually and see the same result.

Also, the file you've posted is not saying anything about any video/audio sync issues, as it's just a still image with a countdown timer and music playing. That's why I've downloaded the entire video and checked for audio sync at the end (~01:04:40), and there were no audio sync issues at all.

Try using a more modern player than mplayer, as it's pretty much outdated and dead.

```bash
streamlink --hls-segment-threads 10 -o foo.ts 'https://www.pscp.tv/w/1DXxyALBdMbxM' best
ffprobe -v error -show_format -show_streams -print_format json foo.ts | jq
```

```json
{
  "streams": [
    {
      "index": 0,
      "codec_name": "timed_id3",
      "codec_long_name": "timed ID3 metadata",
      "codec_type": "data",
      "codec_tag_string": "ID3 ",
      "codec_tag": "0x20334449",
      "id": "0x102",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 5524110,
      "start_time": "61.379000",
      "duration_ts": 353310030,
      "duration": "3925.667000",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High",
      "codec_type": "video",
      "codec_time_base": "1/60",
      "codec_tag_string": "[27][0][0][0]",
      "codec_tag": "0x001b",
      "width": 1280,
      "height": 720,
      "coded_width": 1280,
      "coded_height": 720,
      "closed_captions": 0,
      "has_b_frames": 2,
      "pix_fmt": "yuv420p",
      "level": 31,
      "chroma_location": "left",
      "field_order": "progressive",
      "refs": 1,
      "is_avc": "false",
      "nal_length_size": "0",
      "id": "0x100",
      "r_frame_rate": "30/1",
      "avg_frame_rate": "30/1",
      "time_base": "1/90000",
      "start_pts": 5530050,
      "start_time": "61.445000",
      "duration_ts": 353313030,
      "duration": "3925.700333",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 2,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_time_base": "1/44100",
      "codec_tag_string": "[15][0][0][0]",
      "codec_tag": "0x000f",
      "sample_fmt": "fltp",
      "sample_rate": "44100",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "id": "0x101",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 5525370,
      "start_time": "61.393000",
      "duration_ts": 353300869,
      "duration": "3925.565211",
      "bit_rate": "162274",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    }
  ],
  "format": {
    "filename": "foo.ts",
    "nb_streams": 3,
    "nb_programs": 1,
    "format_name": "mpegts",
    "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
    "start_time": "61.379000",
    "duration": "3925.766333",
    "size": "942245660",
    "bit_rate": "1920125",
    "probe_score": 50
  }
}
```

**Comment by waldyd** [comment]
Here it is the output of mplayer to your command:

MPlayer 1.4-9 (C) 2000-2019 MPlayer Team
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing foo.ts.
libavformat version 58.29.100 (external)
TS file format detected.
VIDEO H264(pid=256) AUDIO AAC(pid=257) NO SUBS (yet)!  PROGRAM N. 1
**FPS seems to be: 2000.000000**
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 58.54.100 (external)
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
Load subtitles in ./
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
AUDIO: 44100 Hz, 2 ch, floatle, 0.0 kbit/0.00% (ratio: 0->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
AO: [pulse] 44100Hz 2ch floatle (4 bytes per sample)
Starting playback...
Movie-Aspect is undefined - no prescaling applied.
VO: [vdpau] 1280x720 => 1280x720 Planar YV12 
A:  81.1 V:  98.8 **A-V:-17.768** ct: -0.056 1122/1122 1711% 1709% 13.3% 1119 0   `

Please notice the A-V difference and the FPS.
`

**Comment by back-to** [comment]
@waldyd 

this is an issue with **MPlayer**, try **MPV** instead.

**Comment by bastimeyer** [comment]
If your player can't properly process the MPEG-TS output, then you can try remuxing it via ffmpeg to a different container format with proper metadata for the length/duration of the content, like MKV or MP4 (maybe even with faststart movflags). As already said, Streamlink is simply concatenating MPEG-TS chunks of a simple HLS stream here, so if there are any issues with the playback, it's either the player, or the content.
