### ISSUE TITLE
plugin turkuvaz broken

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3107]
## Error Report

<! - Replace [] with [x] to activate the check box ->
- [x] This is a bug report and I have read the contribution guidelines.

### Description

Unfortunately, live streams cannot be started via Turkuaz
ATV is affected

### Expected / actual behavior

I usually see the live stream, it doesn't happen here anymore

### Replication Steps / Explicit Stream URLs to Test

1.www.atv.com.tr/webtv/canli-yayin

### Log output

/ usr / sbin / streamlinksrv: 336: PythonDeprecatedWarning: Python 2.7 has reached the end of its life. A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink2 ()
Failed to load plugin ustvnow:
  File "/usr/lib/python2.7/site-packages/streamlink/plugins/ustvnow.py", line 12, in <module>
    from Crypto.Util.Padding import pad, unpad
ImportError: No module named Padding

[streamlinksrv] [info] Processing URL: http://www.atv.com.tr/webtv/canli-yayin
[streamlinksrv] [debug] url args: []
[streamlinksrv] [info] Found matching plugin turkuvaz for URL http://www.atv.com.tr/webtv/canli-yayin
[plugin.turkuvaz] [debug] Found HLS URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=j5n-GHNVZ6dEjMLMN9cuJQ&e=1597219664
[utils.l10n] [debug] Language code: en_GB
[streamlinksrv] [error] Unable to open URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=j5n-GHNVZ6dEjMLMN9cuJQ&e=1597219664 (401 Client Error: Unauthorized for url: https: // trkvz -live.ercdn.net/atvhd/atvhd.m3u8?st=j5n-GHNVZ6dEjMLMN9cuJQ&e=1597219664)
[streamlinksrv] [info] Processing URL: http://www.atv.com.tr/webtv/canli-yayin
[streamlinksrv] [debug] url args: []
[streamlinksrv] [info] Found matching plugin turkuvaz for URL http://www.atv.com.tr/webtv/canli-yayin
[plugin.turkuvaz] [debug] Found HLS URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=an1_mqiSx2LtmcV02zAWJw&e=1597219666
[utils.l10n] [debug] Language code: en_GB
[streamlinksrv] [error] Unable to open URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=an1_mqiSx2LtmcV02zAWJw&e=1597219666 (401 Client Error: Unauthorized for url: https: //. trkvz-live .ercdn.net / atvhd / atvhd.m3u8? st = an1_mqiSx2LtmcV02zAWJw & e = 1597219666)

**Comment by heathmanms** [comment]
This is working in my recent download of the latest version. I'm running Python 3.7.8. I feel maybe OP has changed a file and should re-download the git repo and perform setup.py install again.

Python 3.7.8 Works
>streamlink http://www.atv.com.tr/webtv/canli-yayin best -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 0+unknown
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin turkuvaz for URL http://www.atv.com.tr/webtv/canli-yayin
[plugin.turkuvaz][debug] Found HLS URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=WknuWMP9yYo9wcRT046S3g&e=1597614071
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 288p (worst), 432p, 576p, 864p (best)
[cli][info] Opening stream: 864p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 69363; Last Sequence: 69368
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 69366; End Sequence: None
[stream.hls][debug] Adding segment 69366 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 69367 to queue
[stream.hls][debug] Adding segment 69368 to queue
[stream.hls][debug] Download of segment 69366 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format http://www.atv.com.tr/webtv/canli-yayin -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 69367 complete
[stream.hls][debug] Download of segment 69368 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 69369 to queue
[stream.hls][debug] Adding segment 69370 to queue
[stream.hls][debug] Download of segment 69369 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

Python 2.7.18 Output
>C:\Python27\Scripts\streamlink.exe http://www.atv.com.tr/webtv/canli-yayin best -l debug
C:\Python27\lib\site-packages\streamlink-0+unknown-py2.7.egg\streamlink_cli\main.py:760: PythonDeprecatedWarning: Python 2.7 has reached the end of its life.  A future version of streamlink will drop support for Python 2.7. Please upgrade your Python to at least 3.5.
  streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(console)})
[cli][debug] OS:         Windows 10
[cli][debug] Python:     2.7.18
[cli][debug] Streamlink: 0+unknown
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin turkuvaz for URL http://www.atv.com.tr/webtv/canli-yayin
[plugin.turkuvaz][debug] Found HLS URL: https://trkvz-live.ercdn.net/atvhd/atvhd.m3u8?st=-nXkWzjpDZdu0GJmlFwAPQ&e=1597614588
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 288p (worst), 432p, 576p, 864p (best)
[cli][info] Opening stream: 864p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 69415; Last Sequence: 69420
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 69418; End Sequence: None
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 69418 to queue
[stream.hls][debug] Adding segment 69419 to queue
[stream.hls][debug] Adding segment 69420 to queue
[stream.hls][debug] Download of segment 69418 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format http://www.atv.com.tr/webtv/canli-yayin -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 69419 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by mkbloke** [comment]
It works for me too with a Turkish IP address, but not from a UK IP address, which results in the same error.  @heathmanms, are you using a Turkish IP address?

> 401 Client Error: Unauthorized for url:

Suggests it's a geo-IP restricted site.

**Comment by heathmanms** [comment]
I just used my US ip address.

**Comment by mkbloke** [comment]
Interesting.  There is definitely some geo-IP restriction in play here too though.  Cheers.

**Comment by heathmanms** [comment]
This could also be related to identifying potential proxy services or known data centers.
 
 
  On Sun, Aug 16, 2020 at 2:57 PM, Ian Cameron<notifications@github.com> wrote:   


Interesting. There is definitely some geo-IP restriction in play here too though. Cheers.

**Comment by mkbloke** [comment]
> So, in respect I would probably close this as invalid. Plug-in works as advertised

Agreed.
