### ISSUE TITLE
How to record video without playing them?

### ISSUE THREAD

**Issue by snowman** [streamlink/streamlink#3109]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

I want to download/record online streaming for later playback, without playing it now cause maybe you are busy now.  But i check the documentation, somewhat you have to give it `--player` option to specify the player to play it.

### Expected / Actual behavior

 so how to download/record it in background without using player playing them? for now, i come up a workaround that maybe using player options that do not play it or run it in background.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by MrBrax** [comment]
`streamlink -o output.ts <url>`

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#file-output-options
