### ISSUE TITLE
TV Rain (Dozhd / Дождь)

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#3110]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

TV Rain is a Russian independent television channel. [Wikipedia](https://en.wikipedia.org/wiki/Dozhd).

### Example stream URLs

1. https://tvrain.ru/teleshow/vechernee_shou/linkjavichjus-514186/
2. https://tvrain.ru/teleshow/here_and_now/burko-514286/

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 4. Sites which require any sort of cable login or subscription

the **Livestream is hidden behind a paid account**, which makes it difficult in creating and maintaining a plugin.

> 6. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

we don't add new plugins which are mostly focused on VODs
