### ISSUE TITLE
MyMusicTaste

### ISSUE THREAD

**Issue by Thorbenl** [streamlink/streamlink#3111]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Kpop is big nowadays, and the VODs are only available for a couple of months, even tho we purchased them as users lol. Its verzy shady but I dont want the content i paid for to disappear randomly. MyMusticTaste focusses on Kpop artists. It mainly provides a platform for organising concerts and wishing for an artist to come to your country, as well as live concerts since Covid hit.

### Example stream URLs

1. https://www.mymusictaste.com/live/2ee04e5214654efb81ab0e949d472bb1/
2. https://bcbolt3bf711a4-a.akamaihd.net/media/v1/hls/v4/clear/6156229721001/b7e6dc66-e4d4-48a5-b864-d762a4fb90c1/b94fa97d-c0c8-4260-bde2-bcd869ff31c6/5x/segment1.ts?akamai_token=exp=1597382702~acl=/media/v1/hls/v4/clear/6156229721001/b7e6dc66-e4d4-48a5-b864-d762a4fb90c1/b94fa97d-c0c8-4260-bde2-bcd869ff31c6/*~hmac=d55ff7079ce02835c1ebe4e53d4de22f39d06444b05a2ad74507e09199c6427d

this example starts at `segment4.ts` and ends at `segment591.ts` 

### Additional comments, screenshots, etc.

Stream seems to be seperated in `segment(x).ts` AND a `.hmac` file in the en. It also needs the `?akamai_token` as query param 👍 You also need to be logged in to view the content, but auth header should be easy to pass hopefully

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
What percentage of the streams on this site are from live events? We've been moving away from VOD support and sites that are mostly VODs for a while now as it doesn't really mesh with the goal of the project and there are tons of apps out there which support this already.

**Comment by Thorbenl** [comment]
> What percentage of the streams on this site are from live events? We've been moving away from VOD support and sites that are mostly VODs for a while now as it doesn't really mesh with the goal of the project and there are tons of apps out there which support this already.

I'd say now during corona it has risen to around 95% live events, and they expressed they wanna keep that up even after corona

**Comment by back-to** [comment]
It is **not worth** it to create a plugin for this website

- mostly VODs
- paid account needed
