### ISSUE TITLE
Olympic Channel: no plugin can handle

### ISSUE THREAD

**Issue by viannaricardo** [streamlink/streamlink#3117]
**Plugin Issue**

- [X] This is a plugin issue and I have read the contribution guidelines.

**Description**
Streamlink cannot load Olympic Channel website live streams, returning the error "No plugin can handle URL".

**Reproduction steps / Explicit stream URLs to test**

None of the Olympic Channel live stream works. Commands tested:
1. streamlink https://www.olympicchannel.com/en/live/
2. streamlink https://www.olympicchannel.com/en/live/video/detail/olympic-ceremonies-channel/
3. streamlink https://www.olympicchannel.com/en/live/video/detail/great-olympic-moments-channel/

**Log output**
streamlink https://www.olympicchannel.com/en/live/ --loglevel debug
[cli][debug] OS:         Linux-5.4.0-40-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.4.1
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
error: No plugin can handle URL: https://www.olympicchannel.com/en/live/

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.4.1

You are not using the latest version. The latest stable release is 1.5.0. The plugin was recently fixed in #2981, which is included in 1.5.0.

```
$ streamlink -l debug 'https://www.olympicchannel.com/en/live/'
[cli][debug] OS:         Linux-5.8.0-1-git-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.5.0+10.g00fd4d2
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.56.0)
[cli][info] Found matching plugin olympicchannel for URL https://www.olympicchannel.com/en/live/
[utils.l10n][debug] Language code: en_US
Available streams: 192p (worst), 288p, 432p, 720p, 1080p (best)
```
