### ISSUE TITLE
Twitch.tv stream exits immediately

### ISSUE THREAD

**Issue by richardtatum** [streamlink/streamlink#3118]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Loading a Twitch.tv stream exits immediately.

### Expected / Actual behavior

The stream to display in MPV

### Reproduction steps / Explicit stream URLs to test

1. Install streamlink from the Arch Community repo `yay streamlink`
2. Set config file to `player=mpv --cache=yes --demuxer-max-bytes=8092`
3. Attempt to stream something from twitch with `streamlink -l debug https://www.twitch.tv/bikinibodhi 720p60 --player-no-close`
4. MPV pops open for a split second then closes

### Log output

```
[cli][debug] OS:         Linux-5.8.1-arch1-1-x86_64-with-glibc2.2.5
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/bikinibodhi
[plugin.twitch][debug] Getting live HLS streams for bikinibodhi
[utils.l10n][debug] Language code: en_GB
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 6405; Last Sequence: 6419
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 6417; End Sequence: None
[stream.hls][debug] Adding segment 6417 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 6418 to queue
[stream.hls][debug] Adding segment 6419 to queue
[stream.hls][debug] Download of segment 6417 complete
[cli][info] Starting player: mpv --cache=yes --demuxer-max-bytes=8092
[cli.output][debug] Opening subprocess: mpv --cache=yes --demuxer-max-bytes=8092 --title=https://www.twitch.tv/bikinibodhi -
[stream.hls][debug] Download of segment 6418 complete
[stream.hls][debug] Download of segment 6419 complete
[cli][debug] Writing stream to output
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.
Things I have tried
- Setting multithreaded
- Setting best quality
- Removing all config settings other than `player=mpv`
- Using `--player-no-close`

Happy to provide any further information that may help.

**Comment by bastimeyer** [comment]
> [cli][info] Starting player: mpv --cache=yes --demuxer-max-bytes=8092
> [cli.output][debug] Opening subprocess: mpv --cache=yes --demuxer-max-bytes=8092 --title=https://www.twitch.tv/bikinibodhi -
> [stream.hls][debug] Download of segment 6418 complete
> [stream.hls][debug] Download of segment 6419 complete
> [cli][debug] Writing stream to output
> [cli][info] Player closed

This looks like a player issue on your system. You can use the [`--verbose-player` / `-v`](https://streamlink.github.io/cli.html#cmdoption-verbose-player) parameter to see the player's log output and maybe figure out what's wrong.

**Comment by richardtatum** [comment]
Thank you @bastimeyer, adding `--verbose-player` gives me the following:

```
[stream.hls][debug] Download of segment 7827 complete
[stream.hls][debug] Download of segment 7828 complete
[cli][debug] Writing stream to output
 (+) Video --vid=1 (h264 1280x720)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
[lavf] Too many packets in the demuxer packet queues:
[lavf]   audio/0: 9 packets, 9136 bytes
[lavf]   video/1: 0 packets, 0 bytes
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:00 / 00:00:00 (68%) A-V:  0.000 Cache: 0.0s/11KB
[ffmpeg/video] h264: co located POCs unavailable
AV: 00:00:00 / 00:00:00 (76%) A-V:  0.000 Cache: 0.0s/8KB


Exiting... (End of file)
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

May be worth noting that I don't have any issues when just running `mpv https://stream.link/here`

**Comment by bastimeyer** [comment]
> Too many packets in the demuxer packet queues

Try removing the `--demuxer-max-bytes=8092` MPV parameter or set it to a higher value. This value is ridiculously low and chokes MPV's demuxer.
https://mpv.io/manual/stable/#options-demuxer-max-bytes

**Comment by richardtatum** [comment]
Thanks, looks like that has now worked.

Worth noting that the recommendation for `--demuxer-max-bytes=8092` for MPV comes from the [documentation for Streamlink](https://streamlink.github.io/issues.html#common-issues), it may want updating.

**Comment by bastimeyer** [comment]
It recommends 8192 Bytes because that's the initial size of Bytes (8 KiB) Streamlink tries to read before it outputs something.

The docs were upgraded earlier this year in
https://github.com/streamlink/streamlink/pull/2771/files
due to the MPV 0.30.0 release and the affected `--cache` parameter change:
https://mpv.io/manual/stable/#options-cache

But a demuxer that gets choked by a way too low read value is indeed a problem with the documentation. The values should have been updated as well, as they don't translate directly from the old `--cache` parameter. Thanks for the hint.
