### ISSUE TITLE
Installed streamlink 0.2.0 but says streamlink-script.py 0.1.0

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#312]
Hey guys I found another bug this time after I installed streamlink 0.2.0 I take a look at the command prompt and guess what it says streamlink-script.py 0.1.0 and when I do a version check it says a new version of streamlink 0.2 is available even though I installed 0.2.0 is this a glitch or a bug? Help me please thank you.

**Comment by bastimeyer** [comment]
This is a bug caused by an corrupted/invalid build of the `0.2.0` Windows installer.
See #310... There's a bit of confusion going on right now, sorry for that.
This will be resolved soon. The nightly builds are still working correctly.

**Comment by bobvargas** [comment]
so wait for the nightly build for the bug to be resolved?

**Comment by bobvargas** [comment]
Update: the nightly version just installed says streamlink-script.py 0.2.0 so yeah the nightly version is resolved.

**Comment by gravyboat** [comment]
Thanks for confirming @bobvargas, we'll work on getting this resolved ASAP for the stable.

**Comment by gravyboat** [comment]
This has been resolved, the latest download on the Releases page is now correctly labeling the package as `0.2.0`.
