### ISSUE TITLE
Youtube livestream recordings not starting at the beginning of the video

### ISSUE THREAD

**Issue by InternationalYamAgain** [streamlink/streamlink#3122]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Until recently, after a YouTube livestream finished, if it was sufficiently long, only a clipped portion of it was available. Generally you could watch only the last 2 hours in a browser but depending on the stream settings that duration might be increased to 4 or longer. Streamlink likewise only grabbed this clipped portion. After a period of time (which could be a couple hours or several days) the livestream would be processed and replaced by an uncut, re-encoded single (unfragmented) video.

Roughly a week ago, YouTube made changes that allow the full video to be viewed in browsers (at least chrome and firefox but I suspect all browsers) starting from the beginning in the interim period when the stream is over but not yet processed. However, streamlink still only gets the "clipped" segment of the video in spite of the fact that the full video is now viewable in browsers.

### Expected / Actual behavior

I would expect that streamlink would begin the livestream recording at the same point that a browser does, which with the recent changes to YouTube's pipeline is now the beginning of the livestream. However, the actual output from streamlink seems to be the same as it was before YouTube's recent changes; that is, it only gets the clipped (usually 2 hour) version. That behavior no longer seems to make sense since browsers start at the beginning of the video.

### Reproduction steps / Explicit stream URLs to test

1. Locate any long YouTube livestream video which has recently finished but is not yet processed. You can tell that the processing has not yet occured if the stream is encoded as an m3u8 playlist. Additionally, the chat log only becomes available after processing finishes, so recordings without one are often (but not always) unprocessed. As far as I know, anything over 5 hours will always get clipped, and most livestreams over 2 hours will if they used low latency settings and/or stream at high resolution+60 fps.

2. Run `streamlink youtu.be/video-id worst -o out.ts` (with `video-id` replaced by the ID of the video). The resulting video will not be the full duration; it will start midway through the video and go to the end. The same behavior would be found if you pipe the output directly to VLC or do anything else with it.

(Due to the nature of this issue, any individual URL for testing is likely to become invalid within a relatively short period of time. For testing I used http://youtu.be/QmP420bvs30. You may be able to find more examples in the future browsing this channel or from other livecam channels.)

### Log output

The log is below. Nothing interesting happens once the stream actually gets going so I redacted most of those lines. Clearly the issue is `Start Sequence: 2105`. This leads to streamlink starting about 2h55m into the actual video (the fragments are 5s each).

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL youtu.be/QmP420bvs30
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: QmP420bvs30
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] MuxedStream: v 137 a 140 = 1080p
[plugin.youtube][debug] MuxedStream: v 135 a 140 = 480p
[plugin.youtube][debug] MuxedStream: v 133 a 140 = 240p
[plugin.youtube][debug] MuxedStream: v 160 a 140 = 144p
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_mp4a, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 2105; Last Sequence: 4983
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2105; End Sequence: 4983
[stream.hls][debug] Adding segment 2105 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2106 to queue
[stream.hls][debug] Adding segment 2107 to queue
[stream.hls][debug] Adding segment 2108 to queue
[stream.hls][debug] Adding segment 2109 to queue
[stream.hls][debug] Adding segment 2110 to queue
[stream.hls][debug] Adding segment 2111 to queue
[stream.hls][debug] Adding segment 2112 to queue
[stream.hls][debug] Adding segment 2113 to queue
[stream.hls][debug] Adding segment 2114 to queue
[stream.hls][debug] Adding segment 2115 to queue
[stream.hls][debug] Adding segment 2116 to queue
[stream.hls][debug] Adding segment 2117 to queue
[stream.hls][debug] Adding segment 2118 to queue
[stream.hls][debug] Adding segment 2119 to queue
[stream.hls][debug] Adding segment 2120 to queue
[stream.hls][debug] Adding segment 2121 to queue
[stream.hls][debug] Adding segment 2122 to queue
[stream.hls][debug] Adding segment 2123 to queue
[stream.hls][debug] Adding segment 2124 to queue
[stream.hls][debug] Adding segment 2125 to queue
[stream.hls][debug] Adding segment 2126 to queue
[stream.hls][debug] Download of segment 2105 complete
[cli][debug] Checking file output
[stream.hls][debug] Adding segment 2127 to queue
[stream.hls][debug] Download of segment 2106 complete
[stream.hls][debug] Adding segment 2128 to queue
[stream.hls][debug] Download of segment 2107 complete
[stream.hls][debug] Adding segment 2129 to queue
[stream.hls][debug] Download of segment 2108 complete
[stream.hls][debug] Adding segment 2130 to queue
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 2109 complete
[stream.hls][debug] Adding segment 2131 to queue
[stream.hls][debug] Download of segment 2110 complete
[stream.hls][debug] Adding segment 2132 to queue

           === 5698 lines removed ===

[stream.hls][debug] Download of segment 4960 complete
[stream.hls][debug] Adding segment 4982 to queue
[stream.hls][debug] Download of segment 4961 complete
[stream.hls][debug] Adding segment 4983 to queue
[stream.hls][debug] Download of segment 4962 complete
[stream.hls][debug] Download of segment 4963 complete
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Download of segment 4964 complete
[stream.hls][debug] Download of segment 4965 complete
[stream.hls][debug] Download of segment 4966 complete
[stream.hls][debug] Download of segment 4967 complete
[stream.hls][debug] Download of segment 4968 complete
[stream.hls][debug] Download of segment 4969 complete
[stream.hls][debug] Download of segment 4970 complete
[stream.hls][debug] Download of segment 4971 complete
[stream.hls][debug] Download of segment 4972 complete
[stream.hls][debug] Download of segment 4973 complete
[stream.hls][debug] Download of segment 4974 complete
[stream.hls][debug] Download of segment 4975 complete
[stream.hls][debug] Download of segment 4976 complete
[stream.hls][debug] Download of segment 4977 complete
[stream.hls][debug] Download of segment 4978 complete
[stream.hls][debug] Download of segment 4979 complete
[stream.hls][debug] Download of segment 4980 complete
[stream.hls][debug] Download of segment 4981 complete
[stream.hls][debug] Download of segment 4982 complete
[stream.hls][debug] Download of segment 4983 complete
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Additional comments, screenshots, etc.

The same problem currently exists in youtube-dl, which is documented here: https://github.com/ytdl-org/youtube-dl/issues/26330. 

[Aside: Normally I prefer youtube-dl for downloading because it is more powerful, but unless you need features specific to one or the other, using streamlink makes more sense specifically for these unprocessed videos (at least in the sort of time-sensitive operations where you cannot just wait for the processing to happen and then grab that version). youtube-dl gets each fragment in series and then composes them. This increases the bandwidth and CPU requirements and adds latency between each fragment. I ran both simultaneously on another video to test. Streamlink finished in about half the duration of the video in question, while youtube-dl took more than twice the duration of the video to download. Your results might differ depending on many factors but streamlink will pretty much always be faster.]

**Comment by gravyboat** [comment]
Have you confirmed that the streams you're seeing this on aren't DASH based? It's not identical but we've had issues with [rewind support](https://github.com/streamlink/streamlink/issues/2936) with DASH and I'm wondering if this is an evolution of that problem and how Youtube is handling making the beginning of the stream available. From what I recall youtube-dl hadn't resolved the DASH issue either so it could be related.

**Comment by InternationalYamAgain** [comment]
It is still DASH, yes. I have actually seen some formats available in youtube-dl for archived videos being hls though. As I said above the change is very recent (past week). The results for what formats are available, etc, which have made it difficult to figure out what is actually happening. It could be that the update is still rolling out.

What has clearly changed on YouTube's end is that the DASH video could only be rewound by (usually) 2 hours previously, and the archived version had the same restriction. This no longer seems to be the case. Browsers can safely get the full video immediately, starting with fragment 0 rather than 2105 in my example. You can also (assuming the stream is set up to do so) rewind to the beginning of a stream while it is live even if it has been ongoing a long time (probably up to 12 hours). Another user on the ytdl issue page reported success in manually adding the missing fragments at the beginning of the video to a youtube-dl call, but I don't know if that is a robust approach. But surely the missing part must be available *somehow* since browsers don't have any problem getting it. 

In any event, if it is not trivial to get this working, feel free to treat it as a feature request rather than a bug report.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2936
