### ISSUE TITLE
Playing inside python

### ISSUE THREAD

**Issue by RaVenInTheDark** [streamlink/streamlink#3128]
Is it possible to play streams directly inside python? Eg not requiring vlc etc.

**Comment by back-to** [comment]
sure you can get the data and do whatever you want with it.

https://streamlink.github.io/api_guide.html#opening-streams-to-read-data

**Comment by RaVenInTheDark** [comment]
To clarify, I know how to get the stream data, but I'm not sure what to actually do with it. Do you know of any modules etc that'll be useful? I'm looking to make something that's pure-python.
