### ISSUE TITLE
Can't watch YouTube live streams [stream.hls][error]...(URL has an invalid label.)

### ISSUE THREAD

**Issue by adreporter** [streamlink/streamlink#313]
In the latest version of Streamlink (0.2.0) I can't watch YouTube live streams because of a lot of these error messages in console:
> [stream.hls][error] Failed to open segment 391301: Unable to open URL: http://r6---sn-f5f7ln7z.googlevideo.com/videoplayback/id/vZEdhLGBfbA.1/itag/94/source/yt_live_broadcast/sq/391301/file/seg.ts?ratebypass=yes&cmbypass=yes&goi=160&sgoap=gir=yes;itag=140&sgovp=gir=yes;itag=135&hls_chunk_host=r6---sn-f5f7ln7z.googlevideo.com&playlist_type=DVR&gcr=pl&mm=32&mn=sn-f5f7ln7z&ms=lv&mv=m&nh=IgpwcjAyLndhdzAyKg4yMTMuNDYuMTc4LjEwOQ&pl=13&upn=TCDmWMRGfH0&mt=1482050411&ip=ideletedmyiphere&ipbits=0&expire=1482072049&sparams=ip,ipbits,expire,id,itag,source,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,playlist_type,gcr,mm,mn,ms,mv,nh,pl&signature=2B549FFC78C5D6A3AC56BEBB12E265FDCA49EB9C.4B56A0C9B0008AAF2DD40CACA096B8833B319790&key=dg_yt0&playlist=index.m3u8&live=1&goap=clen=80499;lmt=1482050482243978&govp=clen=492542;lmt=1482050482276773&dur=5.000 (URL has an invalid label.)

I'm using PotPlayer as default media player.
Installing the version 0.1.0 of Streamlink solves the problem, but could you please fix these errors messages in the next version so I may watch some YT streamings? Or it is a PotPlayer issue? Thank you.

PS. If you want, you can download my .bat file: [livestreaming.zip](https://github.com/streamlink/streamlink/files/659325/livestreaming.zip)

**Comment by beardypig** [comment]
Do it occur with the latest nightly? https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe

**Comment by adreporter** [comment]
No, it doesn't. The latest nightly solves the problem, thank you.
