### ISSUE TITLE
Unable to play bloomberg with streamlink - No playable streams found on this URL

### ISSUE THREAD

**Issue by homeless2** [streamlink/streamlink#3130]
## Plugin Issue

- [X] This is a plugin issue and I have read the contribution guidelines.

### Description

I am attempting to use streamlink to play bloomberg live.  However, when attempting to load the URL https://www.bloomberg.com/live/us I receive an error stating there are no playable streams found on this URL.  

### Reproduction steps / Explicit stream URLs to test

1. I am running this command: streamlink https://www.bloomberg.com/live/us

### Log output

```
C:\Windows\system32>streamlink https://www.bloomberg.com/live/us -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
[plugin.bloomberg][debug] Found liveId: PHOENIX_US
[plugin.bloomberg][debug] Player URL: https://cdn.gotraffic.net/projector/v0.11.192/app.js
[plugin.bloomberg][debug] Webpack module ID: 203
error: No playable streams found on this URL: https://www.bloomberg.com/live/us
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by PlaceboPRS** [comment]
Try capturing the specific m3u8 that works:

streamlink --hls-segment-threads "10" --hls-segment-attempts "5" --hls-playlist-reload-attempts "5" --hls-audio-select "*" --hls-timeout "180" --http-timeout "60" --retry-streams "8"  --hls-live-restart -o "test.mp4" "hlsvariant://https://liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-02-81ykIWnsMsg_live.m3u8" best

![image](https://user-images.githubusercontent.com/23120453/91453753-6e2b2280-e880-11ea-9e30-dd6395a2d058.png)

**Comment by bastimeyer** [comment]
See #3131 

The site's structure has changed slightly, breaking the regex used for extracting the stream URLs.
As you can see in the linked pull request, the stream URLs seem to be static, and you can use these in the mean time or wait for the PR to be merged and then rebuild streamlink from the master branch.

> liveprodusphoenixeast.akamaized.net/USPhx-HD/Channel-TX-USPhx-AWS-virginia-1/Source-USPhx-16k-1-s6lk2-BP-07-02-81ykIWnsMsg_live.m3u8

`https://www.bloomberg.com/live/us`
translates to
`https://www.bloomberg.com/media-manifest/streams/phoenix-us.m3u8`
