### ISSUE TITLE
[New Plugin] Add eja.tv

### ISSUE THREAD

**Issue by richard173** [streamlink/streamlink#3134]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

3620 live iptv channels tested today from around the world.

### Example stream URLs

1. https://eja.tv/

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 2. Sites which are hosting stolen content as their main source of content
