### ISSUE TITLE
[New Plugin] Ozolio.com

### ISSUE THREAD

**Issue by richard173** [streamlink/streamlink#3144]
- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Ozolio: Live Video Streaming

### Example stream URLs

1. https://www.ozolio.com/explore
2. https://relay.ozolio.com/pub.cgi?cmd=iframe&oid=CID_HQKO00000499&app_mode=control
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 11. Sites which are static cameras of a physical location
