### ISSUE TITLE
Any way to schedule a record?

### ISSUE THREAD

**Issue by knightdea** [streamlink/streamlink#3146]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

Is there a way to schedule to record a stream, like streamlink constantly checking for the stream 24/7, and once the stream is closed, keep trying. The idea is not to have multiple instances of Streamlink recording the same thing, but rather individual files.

### Expected / Actual behavior

Schedule the recording of the stream to always be looking automatically for the stream.
If the stream is found, start recording.
Stop trying to look for the stream since it's already recording the stream.
If the stream goes down or connection failure, keep trying for X amount of minutes.
If the stream is not up again, stop trying, save the recorded file and...
Open a new retry to find the stream.
Once the stream is found, start recording.
Rinse, repeat.

**Comment by gravyboat** [comment]
You could write some sort of wrapper script around Streamlink to do this but it's not a feature we'll add nor something we'll help you do. You'll have to figure it out yourself.
