### ISSUE TITLE
*.cdn.netbadgers.com

### ISSUE THREAD

**Issue by nickerejv** [streamlink/streamlink#3149]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description
Some Bulgarian TV channels are now on cdn.netbadgers.com

### Example stream URLs

1. https://kanal3.cdn.netbadgers.com/  links to https://kanal3.cdn.netbadgers.com/bg030/bg031/bg031.m3u8
2. https://eurofolk.cdn.netbadgers.com/ links to https://eurofolk.cdn.netbadgers.com/bg040/bg041/bg041_sd.m3u8
3. https://bulgare.cdn.netbadgers.com/ links to https://bulgare.cdn.netbadgers.com/bg050/bg051/bg051_hd720.m3u8

### Additional comments, screenshots, etc.
There might be more TV streams broadcasted from *.cdn.netbadgers.com
Accessing the streams from Bulgarian IP's is not required.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
just use the **static URLs** with Streamlink, no plugin required.
You might need to set a Referer

```
streamlink https://kanal3.cdn.netbadgers.com/bg030/bg031/bg031.m3u8 best --http-header "Referer="https://kanal3.cdn.netbadgers.com/
```
