### ISSUE TITLE
streamlive.to plugin not working :(

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#315]
Hey guys I found yet another bug on streamlink  one of the plugins streamlive.to is having problems when I go to the site for espn (http://www.streamlive.to/view/69029/ESPN) it worked however when I tried it on streamlink (latest night build) it says no streams found on this URL:http://www.streamlive.to/view/69029/ESPN I said to myself is this plugin broken? or the link? Please help me thank you.

**Comment by bobvargas** [comment]
@beardypig when streamlive.to plugin is going to fixed? I want to enjoy espn & usa network on streamlive.to & I did test it on the latest nightly build and no luck.

**Comment by beardypig** [comment]
@bobvargas I don't know. I personally don't have any time to fix it right now, as it's Christmas. Maybe someone else will fix it though.

**Comment by bobvargas** [comment]
Hopefully the streamlive.to plugin would be fixed by the time the next streamlink stable build update around next year. Til then merry Christmas @beardypig, @bastimeyer  and the crew working hard for streamlink as it continues to grow thank you.

**Comment by bobvargas** [comment]
1 last thing @beardypig  after the holidays will anyone fix this streamlive.to bug so we can watch espn anytime? please answer.

**Comment by beardypig** [comment]
livestream.to have added some extra protections to there streams (similar to this https://iiibuntu.wordpress.com/2011/06/22/testing-wowza-vod-media-security-to-protect-vod-contents/), and in doing so have made is much more difficult to extract the streams. It may be a while before this plugin is working again.

**Comment by gravyboat** [comment]
@beardypig I wouldn't worry about it then, if companies are actively trying to protect their content it's not really worth our time to get into an arms race with them to circumvent it.

**Comment by beardypig** [comment]
We can mark the plugin as broken, there is a decorator @broken if I remember correctly. We should annotate the plugin with that and reference this ticket if you can have a message.

**Comment by beardypig** [comment]
Like this #339 :)

**Comment by gravyboat** [comment]
Good stuff, I'm going to close this.

**Comment by Chris230291** [comment]
Is there any chance of getting this fixed?

**Comment by bastimeyer** [comment]
This thread is 5 years old. If you're having an issue with one of streamlink's plugins, then please open a new issue and fill out all the required details from the issue template.

However, the plugin you are asking about has been removed and is no longer supported.
See #2003
