### ISSUE TITLE
m3u8 / segments files location

### ISSUE THREAD

**Issue by whittinghamj** [streamlink/streamlink#3154]
This question didn't fit any of the four options available.

Where does streamlink store the m3u8 / segment files for incoming streams? or does it not?

**Comment by bastimeyer** [comment]
> Where does streamlink store the m3u8 / segment files for incoming streams?

HLS segment contents get written to / read from memory (Streamlink's RingBuffer):
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/stream/segmented.py#L190
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/stream/hls.py#L161
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/stream/segmented.py#L202-L207
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/buffers.py#L72-L161
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/buffers.py#L18-L69
- https://github.com/streamlink/streamlink/blob/c30a59f9a72947cd1a4129d250274149fb1cd847/src/streamlink/buffers.py#L6-L15

> or does it not?

I guess, you're referring to offloading the data onto the filesystem. There's no such buffer type here.

**Comment by whittinghamj** [comment]
Ah ok, I was hoping the .ts and m3u8 was stored somewhere on the FS or a ramFS.

Thanks for the question reply.

**Comment by bastimeyer** [comment]
> I was hoping the .ts and m3u8 was stored somewhere on the FS

Why? For Streamlink's purposes as an HLS client that outputs a single stream, this doesn't make sense, unless the data is too large to be stored in memory at once.

If you want to download/store segments individually, you'll have to get the HLS playlist URL from Streamlink and use a different tool, or write yourself a little script that parses and refreshes the playlist and then downloads the segments to your FS, which should be fairly simple and straightforward. What you'd gain from this however is questionable.

> ramFS

That would be a feature of your OS/kernel, not Streamlink.

**Comment by ischmidt20** [comment]
Just want to add a comment here and state that this feature does have some practical use. For example, one service that I use streamlink to record from has weird behavior with timestamps when going to/from commercial breaks. When I use streamlink, the segments just get catted together I believe, and it's really hard for me to work with the resulting .ts file in almost any application (including ffmpeg or VLC), without going through a full re-encode, which I'd rather avoid. So ideally, what I'd like is a solution where streamlink could just download all of the segments individually, and then I go through after the fact and delete the offending ones before catting the rest together to get a clean stream. I know streamlink has filters to avoid downloading certain segments at all, but I'm not sure if I can use them in my situation.
