### ISSUE TITLE
Pluto.TV Live

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#3156]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Pluto.TV has really changed since it was suggested back in 2017.

Originally they just basically threw a bunch of YouTube and similar VoD into a linear playing m3u8.

Yet they have since changed to regular live streams that aren’t just mushed together VoDs so I figured maybe streamlink can look at it again.

Pluto has a decent library of VOD as well but it would be mainly nice to at least see the Live Streams better supported.

### Example stream URLs

1. ... https://pluto.tv/live-tv/court-tv-1
2. ... https://pluto.tv/live-tv/tyt-network
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by RedPenguin2** [comment]
Well, maybe Pluto won’t be as easy as I thought.

I did a test recording of Court TV and I don’t know what happened.

It’s the correct size of 1GB for 60 min as expected compared to Court TV’s own feed.

Yet when I try to play it, all I can get out of it the Pluto Tv Logo Screen and injected commercials, I can’t even see the actual program that Court TV had on at the time.

Even ffmpeg won’t fix it, when it always fixes the CTV official stream.

ffmpeg -I file.ts -c copy fixed.ts just spit out an 18 min file of Pluto Commercials only....

Tried avconv and it still is 18 min, so I have no idea what happened to the recordede ts file.

Oddly the stream plays fine in VLC.

**Comment by mkbloke** [comment]
I don't know if you're already aware of it and I certainly don't know if it'll be of any use to you at all, but there's already a plugin for Pluto (seemingly abandoned) in PR #2747.  That PR seems to have failed some checks under Py 3.8 by the look of it, although unfortunately the full results data is no longer available.

**Comment by RedPenguin2** [comment]
Yes, I did see that and I tried it somewhat and it mostly worked but not completely.

I seems like it grabs the url from an old api of Pluto's and results in a "Bad Request".

I think the issue with the TS file is was shown by ffplay.

It seems to do a lot EXT-X-DISCONTINUITY and ffplay says it's trying to switch hosts even which ffplay errored out saying "cannot switch hosts".

**Comment by RedPenguin2** [comment]
Here is a direct m3u8 URL as an example:

**Comment by mkbloke** [comment]
~~Is the above URL causing problems for you or is that working OK?  I can play it directly through streamlink with no obvious problems.~~  It seemed to play, the first few times, but then I started getting the Pluto logo you mentioned after that... and now it's playing OK again.  Strange.

```
streamlink 'hls://https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?deviceType=web&deviceMake=Chrome&deviceModel=Chrome&sid=0c9d9262-bcd4-4b33-a78f-afea1ee4a67e&deviceId=781d4c79-fb21-4162-97a4-9f543683f22a&deviceVersion=74.0.3729.131&appVersion=2.5.1-f9a6096b469cfe5e4f1cc92cc697e8500e57891c&deviceDNT=0&userId=&advertisingId=&deviceLat=38.8177&deviceLon=-77.1527&app_name=&appName=&appStoreUrl=&architecture=&serverSideAds=true' 480p
[cli][info] Found matching plugin hls for URL hls://https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?deviceType=web&deviceMake=Chrome&deviceModel=Chrome&sid=0c9d9262-bcd4-4b33-a78f-afea1ee4a67e&deviceId=781d4c79-fb21-4162-97a4-9f543683f22a&deviceVersion=74.0.3729.131&appVersion=2.5.1-f9a6096b469cfe5e4f1cc92cc697e8500e57891c&deviceDNT=0&userId=&advertisingId=&deviceLat=38.8177&deviceLon=-77.1527&app_name=&appName=&appStoreUrl=&architecture=&serverSideAds=true
[cli][info] Available streams: 240p (worst), 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: mpv
```

**Comment by RedPenguin2** [comment]
It plays but then once it goes to commercial break it seems to get wonky.

Also the file recorded by streamlink after using -o file.ts seems severly broken.

**Comment by whittinghamj** [comment]
I was writing a script for Pluto for another platform of mine and ran into the same issue.

Once the commercial break hits - it all goes tits up. They are messing with the streams and cutting stuff together in a way that breaks the timestamps and ffmpeg ends up throwing a wobler - its really annoying !!!

**Comment by mkbloke** [comment]
I see one of the streamlink devs has committed some changes to the existing PR for Pluto.  Might be worth seeing if that also exhibits the same problem.

**Comment by RedPenguin2** [comment]
Wow, this actually is getting more progress than I could have hoped for.

I wasn't sure the way around Pluto's weird ad breaks but I know they have some really good channels now worth watching if it's possible to straighten out their cut jobs.

**Comment by RedPenguin2** [comment]
Well, I tried the code already in the pull request to rather surprising results.

Trying out the “Laughing Out Loud Network”, it actually worked great as long as you “ffmpeg -c copy” the file to fix all the timestamps.

The only weird part is that Pluto seems to break at strange times, not at what would be a natural break.

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug

[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by mule42** [comment]
Mine's not working.
`
$ ~/.pyvirt/streamlink/devel/bin/streamlink https://pluto.tv/live-tv/court-tv-1 best -p vlc -l debug
`
`
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-debian-10.1
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.5.0+25.g5a4a200
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pluto for URL https://pluto.tv/live-tv/court-tv-1
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId= (400 Client Error: Bad Request for url: https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dae0b4841a7d0000938ddbd/master.m3u8?advertisingId=&appName=&appVersion=unknown&architecture=&buildVersion=&clientTime=&deviceDNT=0&deviceId=unknown&deviceLat=41.6622&deviceLon=-91.5149&deviceMake=&deviceModel=&deviceType=&deviceVersion=unknown&includeExtendedEvents=false&marketingRegion=US&sid=d6e1c691-6f29-4e0c-8e52-bcdafc589042&userId=)
`

**Comment by Leatherface75** [comment]
Anyone working for working solution also for services like Stirr and the new Samsung Plus?
Many channels there have same problem as Pluto.

**Comment by pcolmer** [comment]
> Trying out the “Laughing Out Loud Network”, it actually worked great as long as you “ffmpeg -c copy” the file to fix all the timestamps.

This certainly fixes the duration of the file as far as various player applications are concerned. However, what I'm finding is that if the stream is programme, adverts, programme then the *video* playback stops at some point in the adverts although the audio continues. Do I need to use any other flags with ffmpeg to fix the created file?

This is the output I got when using `ffmpeg -c copy` on a Pluto recording:

```
$ ffmpeg -i 2021-11-26-streamlink.mp4 -c copy foo.mp4
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mpegts @ 0x56254a838280] PES packet size mismatch
Input #0, mpegts, from '2021-11-26-streamlink.mp4':
  Duration: 03:00:35.86, start: 1.466667, bitrate: 194 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 97 kb/s
Output #0, mp4, to 'foo.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 97 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x56254aa41880] Non-monotonous DTS in output stream 0:1; previous: 17361472, current: 17360000; changing to 17361473. This may result in incorrect timestamps in the output file.
[mp4 @ 0x56254aa41880] Non-monotonous DTS in output stream 0:1; previous: 17361473, current: 17361024; changing to 17361474. This may result in incorrect timestamps in the output file.
[mp4 @ 0x56254aa41880] Non-monotonous DTS in output stream 0:1; previous: 17605760, current: 17604493; changing to 17605761. This may result in incorrect timestamps in the output file.
[mp4 @ 0x56254aa41880] Non-monotonous DTS in output stream 0:1; previous: 17605761, current: 17605517; changing to 17605762. This may result in incorrect timestamps in the output file.
[mpegts @ 0x56254a838280] PES packet size mismatch2:22:02.21 bitrate= 194.2kbits/s speed=5.68e+03x
frame=11898 fps=6344 q=-1.0 Lsize=  230955kB time=03:00:35.94 bitrate= 174.6kbits/s speed=5.78e+03x
video:105003kB audio:127083kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```
