### ISSUE TITLE
streamlink as a proxy

### ISSUE THREAD

**Issue by lawin1** [streamlink/streamlink#316]
Server <-> Streamlink <-> Client PC. This is default scheme for everyone. After you start Streamlink, it begins constantly download from Server even if no connection exists with client PC. In this case the bandwidth usage is pointless. Can Streamlink wait for an incoming connection from Client PC and only then make contact to Server?

**Comment by beardypig** [comment]
Do you have an example of how you have set up streamlink? If you are using the `--player-external-http` option, it should only start downloading the stream when you connect.

**Comment by lawin1** [comment]
Server (livestream.com) <-> Streamlink with --player vlc output to port 8080 <-> VLC http://ip_of_streamlink:8080

For example:

`streamlink --player "vlc --file-caching=2000 --loop --sout=#gather:std{access=http,mux=ts,dst=:8080} --sout-keep"  https://livestream.com/accounts/12654794/live best --player-continuous-http`

I would like to force streamlink to connect to livestream.com only then I access http://ip_of_streamlink:8080 with VLC.

**Comment by scottbernstein** [comment]
@lawin1 -- you should not need to have VLC player involved to restream as you describe.


Check out the command line options:

--player-external-http

--player-external-http-port PORT

________________________________

**Comment by lawin1** [comment]
Thank you all, now it works as I wanted:

`streamlink https://livestream.com/accounts/12654794/live 720p --player-external-http --player-external-http-port 8080`
