### ISSUE TITLE
ADs on subbed Twitch streams.

### ISSUE THREAD

**Issue by shadowofdarkness** [streamlink/streamlink#3164]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

I am not worried about ADs on non subbed channels But for channels I pay for and should not get ADs on officially, which I don't get them on the actual website, it is annoying.

### Expected / Actual behavior

Expected no ADs on subscribed channels
Actual I get the placeholder ad screen for 15 seconds everytime I go to the channel

### Reproduction steps / Explicit stream URLs to test

To reproduce load a channel you are subscribed to. I can't give ones to test as that is on a per account basis

### Log output

```[cli][debug] OS:         Linux-5.4.0-47-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/hannahbart
[plugin.twitch][debug] Getting live HLS streams for hannahbart
[plugin.twitch][info] hannahbart is hosting jimmy
[plugin.twitch][info] switching to jimmy
[plugin.twitch][debug] Getting live HLS streams for jimmy
[utils.l10n][debug] Language code: en_CA
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60_alt, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: None
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Download of segment 0 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format twitch.tv/hannahbart -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Download of segment 2 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Download of segment 3 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...


```

### Additional comments, screenshots, etc.

I think my system must of updated streamlink in the background because I never had this problem before and when searching for info it looks like you removed any Twitch oauth support so it does not know I'm subbed anymore. Is that being replaced and I don't know the new way?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Please use the search function next time. I really don't want to repeat myself every time Twitch re-enables embedded ads.
Last duplicate issue: #3120

**Use the [`--twitch-disable-ads`](https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads) parameter to filter out embedded ads.**

> But for channels I pay for and should not get ADs on officially, which I don't get them on the actual website, it is annoying.

Streamlink (and any other 3rd party Twitch application which is accessing streams) doesn't support logins anymore due to a change by Twitch in November last year, so it is irrelevant if you're subscribed to a channel or if you're paying for Twitch prime, etc.
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851
