### ISSUE TITLE
Twitch.tv preload ads (prolly new header)

### ISSUE THREAD

**Issue by yyhplrvstudvmyvarc** [streamlink/streamlink#3166]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Today ~11.Sept 2020 twitch prolly change header for preloaded ads, so EVERY stream I enter now start with puprle/pink twitch logo tellin me that "commercial break is in progress" and VLC closes itself right after, caused by difference in codecs of break screen and real stream. Auto-close of VLC can be "kinda" work around by output to file, but this way audio still get nuked and every muxer also shit itself over the change of codecs, formats and size within the file.

### Reproduction steps / Explicit stream URLs to test

1. streamlink twitch.tv/relaxbeats best
2. ... or any other stream ...
3. streamlink -o %USERPROFILE%/desktop/twitch.plugin.issue.test.mp4 twitch.tv/relaxbeats best

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

Also I'm just a pleb working in Windows. So exe with a fix would be much obliged.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
#3120
