### ISSUE TITLE
Unable to find and fully uninstall old streamlink versions

### ISSUE THREAD

**Issue by noodle-** [streamlink/streamlink#3175]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Unable to fully uninstall old streamlink versions

### Expected / Actual behavior

streamlink was already installed, no idea what version but I recently started using this system again and wanted to install the latest version.
I installed the latest streamlink version 1.5.0, tried to use it for Twitch but constantly got 401 or 410 errors
I tried various configurations related to Twitch OAuth but none worked.
`streamlink -V` returns `streamlink-script.py 0.9.0`, so it must be outdated?
I uninstalled streamlink through the windows control panel, no error messages showed up
the command `streamlink -V` still works and still returns the same result: `streamlink-script.py 0.9.0`

So there's an installation leftover somewhere but I have no Idea where to look. The Program Files (x86 and default) folders don't contain any streamlink directories.

I've since tried reinstalling the latest streamlink version but the results stay the same.

### Reproduction steps / Explicit stream URLs to test

Not sure honestly, see explanation above

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

I hope this is the right place to post this as this is probably not a current issue, rather just a mess of old outdated installations.

Thanks in advance!

**Comment by mkbloke** [comment]
Have you tried a full file system search for ```streamlink``` or ```*streamlink*``` in file explorer (I forget what the default matching might be now, exact or wild card) to find it?

**Comment by noodle-** [comment]
> 
> 
> Have you tried a full file system search for `streamlink` or `*streamlink*` in file explorer (I forget what the default matching might be now, exact or wild card) to find it?

Oh my. I did not.

For others with similar problems:
Windows will find the `streamlink` command if you enter the full name into the start menu. `streamli` and other partial entries somehow return no results..
If you rightclick it you can select `go to file location` which will bring you to the install directory.

I found an installation of streamlink in the AppData\Local\ folder. I'll try to uninstall and report back with the results.

**Comment by noodle-** [comment]
Yup, that worked.

I used the uninstaller located in the AppData/Local/streamlink folder 
Installed the latest version of streamlink again
`streamlink -V` now returns `streamlink 1.5.0`

So it's working just fine now. Thanks for the help!

**Comment by mkbloke** [comment]
By the way, as you mentioned Twitch above, you might want to consider installing the nightly Windows build until the next release of streamlink is out, as there have been some very recent code merges in relation to the Twitch plugin that have fixed some issues.
