### ISSUE TITLE
Update Debian repo to 1.5.0

### ISSUE THREAD

**Issue by ZwiebelTVDE** [streamlink/streamlink#3176]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

When I install streamlink for debain like mentioned [here](https://streamlink.github.io/install.html#linux-and-bsd) I get the version 1.0.0 which is pretty old at this point

### Expected / Actual behavior

I expect the current version of streamlink installed.

### Reproduction steps / Explicit stream URLs to test

1. Get a pc with debian installed
2. Follow the steps from the documentation [here](https://streamlink.github.io/install.html#linux-and-bsd)
3. in debian console type `streamlink --version`
4. the version should be 1.5.0 but is 1.0.0

### Logs

```
root@streamlink:~# streamlink --version
streamlink 1.0.0
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Packaging is independent of the development here and is done by other people, so if you have any issues with packages of your distro, you have to ask there.

If you're on debian and are getting Streamlink 1.0.0, then you are on **buster** (stable):
https://packages.debian.org/buster/streamlink

**Bullseye** (testing) and **sid** (unstable) are on the latest Streamlink version, which is currently 1.5.0:
https://packages.debian.org/bullseye/streamlink
https://packages.debian.org/sid/streamlink

There is also the **buster-backports** repository with the latest Streamlink version:
https://packages.debian.org/buster-backports/streamlink

And this is all properly described on the install page of Streamlink's docs.
https://github.com/streamlink/streamlink/blame/1.5.0/docs/install.rst#L91-L97

**Comment by mkbloke** [comment]
What version of Debian are you using?  If Buster, did you follow the instructions to enable buster-backports?  For buster-backports it should be version 1.5.0+dfsg-1~bpo10+1.  If you're running older than Buster, you should look at installing via pip in a virtual environment as detailed lower down in the page you linked to.
