### ISSUE TITLE
Beginner Help:  New Twitch ads on VLC player causing constant audio stuttering

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink#3177]
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.

### Description

hello,
I dont know anything about coding. I keep getting the 'Commercial is in progress' whenever  I fire up a stream in VLC player and it cause audio desync and constant audio stuttering.

Could someone do me the favor of perhaps sending me an updated text file or something I can easily copy and paste to fix this?
I don't know a single thing about the stuff thats being talked about on the gifthub website. All I want to do is watch streams on VLC player again in peace.

I tried looking around for a fix but I dont understand any of it. Its too complicated :(
### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
You don't have to replace any files and this has nothing to do with coding. Just install the latest development version, as described here.
https://github.com/streamlink/streamlink/issues/3120#issuecomment-692309197
