### ISSUE TITLE
Plex "Free Live TV" support

### ISSUE THREAD

**Issue by vexorian** [streamlink/streamlink#3179]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

Recently Plex have released 'free Live TV' channels, looks like they are hls streams the ones I found are hosted in aws, but the urls are possibly hidden behind some authentication magic from Plex's side, and it wouldnt' surprise me if it picks different hosts for different channels. It would be nice to make streamlink able to take a plex access token and play one of these channels

### Example stream URLs

1. https://54d4596f49b947b987be6175b1a7a3f7.mediatailor.us-west-2.amazonaws.com/v1/manifest/6b8beeb9ed833d048c8c8155a25a28fe617c5474/80s_party_plex/13340758-beee-467c-8a73-8dd142a82fc8/1.m3u8
2. ...
3. ...

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
I've had a look at https://app.plex.tv/desktop yesterday and it doesn't seem there are canonical stream URLs for the available live channels (eg. Reuters). Posting the resolved HLS stream URL in the plugin request doesn't archieve much, as it's the job of the plugin to do this automatically from the given input URL.

Plugin requests also usually require a small description of the streaming platform. I, for example, didn't/don't know what/who plex.tv is.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by RedPenguin2** [comment]
Redbox, the movie kiosk company also has:
https://www.redbox.com/stream-free-live-tv

I was going to request Plex & RedBox but wasn't sure if I better wait until Pluto & XUMO were looked at. I hated to put 4-5 requests in at once.

All 4 services seem to basically be the same thing but different offerings.

The Roku Channel (https://therokuchannel.roku.com/) also has Live TV but you must login first and not sure if that would work well with streamlink.

**Comment by bastimeyer** [comment]
Don't post plugin requests for different sites into existing requests. I'm going to mark your post as offtopic. If you want to request a plugin, open a new issue and post the necessary details according to the contribution guides. And btw, this site is showing a 403 error, so it's not very promising.

**Comment by mkbloke** [comment]
The only way this seems feasible right now is by adding plugin parameters to allow for channel listing and selection.  If that's an acceptable way to do it, then it could perhaps be done.  If not, this request may as well be closed.

**Comment by back-to** [comment]
- it seems to difficult to get the `X-Plex-Token` as a Guest, without creating a account.
- there is also no separately URL for every channel.

this makes it a bit complicated for Streamlink

closing

**Comment by ReenigneArcher** [comment]
@back-to 

I found an easier way to get the urls for each channel.

There is a separate url for each channel. Plex provides the urls in their api. Opening the guide as so, provides all the programs. It needs to be parsed to find the channels.

`https://epg.provider.plex.tv/grid?type=movie&sort=beginsAt&endsAt%3E=1609266600&beginsAt%3C=1609353000&X-Plex-Token=<yourplextoken>&X-Plex-Language=en`

![image](https://user-images.githubusercontent.com/42013603/103308330-3a077000-49e0-11eb-8070-0eacb537e97f.png)
['MediaContainer']['Metadata'][x]['Media'][y]['channelIdentifier'] (1) is always equal to ['MediaContainer']['Metadata'][x]['Media'][y]['Part'][z]['id'] (2).

2 is used to build 3 (['MediaContainer']['Metadata'][x]['Media'][y]['Part'][z]['key'])

3 is the stream url if you append it to "https://epg.provider.plex.tv" and add the token.

for example `https://epg.provider.plex.tv/library/parts/5e20b730f2f8d5003d739db7-5fd2759bc8634d002d9ff9bc?X-Plex-Token=<yourplextoken>`

... not sure how to automate getting a guest token though. Most python plex scripts the user provides the token or credentials as an alternative.

**Comment by mkbloke** [comment]
@ReenigneArcher that rather goes back to my comment, above, i.e. that the plugin would need something like a `--plex-list-channels` parameter to be implemented and an accompanying `--plex-channel` parameter, which rather goes against the way most Streamlink plugins work, that being with a canonical URL.  However, I never did get an answer as to whether or not it would be an acceptable solution, so who knows...

**Comment by ReenigneArcher** [comment]
@mkbloke in my opinion that would be acceptable. I don't know if this will be re-opened or if this will help but I have a python (2) script here that creates an m3u list from plex. https://github.com/ReenigneArcher/web2tv/blob/main/plex.py

Feel free to strip it down or use it as reference.

**Comment by mkbloke** [comment]
I'm on a break from tonight till early new year.  Perhaps some more feedback might be forthcoming between now and then.

It sounds like assessing the token situation first might be the best bet as well.  I've not looked at that at all.
