### ISSUE TITLE
TVCatchup addon not working anymore

### ISSUE THREAD

**Issue by yhs4260** [streamlink/streamlink#318]
root@ovh2:/data# streamlink http://tvcatchup.com/watch/channel4
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvcatchup for URL http://tvcatchup.com/watch/channel4
error: No streams found on this URL: http://tvcatchup.com/watch/channel4
root@ovh2:/data# streamlink --plugins
[cli][info] streamlink is running as root! Be careful!
Loaded plugins: adultswim, afreeca, afreecatv, aftonbladet, alieztv, antenna, ard_live, ard_mediathek, artetv, atresplayer, azubutv, bambuser, beam, beattv, bigo, bilibili, bliptv, chaturbate, cinergroup, connectcast, crunchyroll, cybergame, dailymotion, dingittv, disney_de, dmcloud, dmcloud_embed, dogan, dogus, dommune, douyutv, dplay, drdk, euronews, expressen, filmon, filmon_us, foxtr, furstream, gaminglive, gomexp, goodgame, hitbox, itvplayer, kanal7, letontv, livecodingtv, livestation, livestream, media_ccc_de, mediaklikk, meerkat, mips, mlgtv, nhkworld, nineanime, nos, npo, nrk, oldlivestream, openrectv, orf_tvthek, pandatv, periscope, picarto, piczel, powerapp, rtlxl, rtve, ruv, seemeplay, servustv, speedrunslive, sportschau, ssh101, stream, streamboat, streamingvideoprovider, streamlive, streamme, streamupcom, svtplay, tga, tigerdile, trt, turkuvaz, tv360, tv3cat, tv4play, tv8, tvcatchup, tvplayer, twitch, ustreamtv, vaughnlive, veetle, vgtv, viagame, viasat, viasat_embed, vidio, wattv, webtv, weeb, younow, youtube, zdf_mediathek

**Comment by beardypig** [comment]
Looks like they have changed the site a bit. Unfortunately I can't look at it at the moment, I'm on holiday, but I'll take a look next week. Maybe someone else will have time to fix it before that. Sorry :-)

**Comment by yhs4260** [comment]
No hurry, enjoy your holiday :)

**Comment by beardypig** [comment]
@yhs4260 I submitted a PR to fix this :)

**Comment by kirkydman** [comment]
Beardypig whats happened to tvcatchup mate?

**Comment by gravyboat** [comment]
@kirkydman What do you mean? A PR to fix it was merged back in December of last year.

**Comment by kirkydman** [comment]
yeah but its not working right now

**Comment by kirkydman** [comment]
not even with a vpn

**Comment by gravyboat** [comment]
@kirkydman In that case please open a new issue with full logging details regarding what you are seeing when you try to open a stream.
