### ISSUE TITLE
problem with youtube when rewinding

### ISSUE THREAD

**Issue by Caeliiaa** [streamlink/streamlink#3180]
hi, i started using streamlink recently and it's not that i know much about programming, but i was using streamlink to watch a couple of youtube videos or streams and i found that just when i try to rewind a video or stream on youtube, the player (vlc) closes and stops playing the video in question. SW.

streamlink --player-no-close https://www.youtube.com/watch?v=BC9n5PDpV6E 720p

[cli] [info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=aFSkt92TOXA
[cli] [info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli] [info] Opening stream: 720p (http)
[cli] [info] Starting player: "C: \ Program Files \ VideoLAN \ VLC \ vlc.exe"
[cli] [info] Player closed
[cli] [info] Stream ended
[cli] [info] Closing currently open stream ...

It may be a silly question, but it would be helpful
sorry to bothering :u

**Comment by gravyboat** [comment]
Youtube rewinding isn't supported in Streamlink currently. There's an open issue about it here: https://github.com/streamlink/streamlink/issues/2936
