### ISSUE TITLE
Nicolive can't get the actual best and second best quailty again and can't login.

### ISSUE THREAD

**Issue by LzNOHentai** [streamlink/streamlink#3181]
- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
This is an issue of the latest commit version of streamlink.

Nicolive can't get the actual best quailty and second best again.
It just showed '345k (worst), 691k, 1800k (best)' now.

Actually the stream has '3600k, 5400k (best)'.

And, I found I can't login.
### Additional comments, screenshots, etc.

![QQ截图20200917193633](https://user-images.githubusercontent.com/22359967/93465268-20ed1e80-f91d-11ea-9a27-5de7387fb2ae.jpg)
![QQ截图20200917195940](https://user-images.githubusercontent.com/22359967/93467456-5810ff00-f920-11ea-8322-346b63d9e085.jpg)
![QQ截图20200917195228](https://user-images.githubusercontent.com/22359967/93466841-6e6a8b00-f91f-11ea-9f00-a947ba7862ee.jpg)
![QQ截图20200917195309](https://user-images.githubusercontent.com/22359967/93466848-71657b80-f91f-11ea-9887-885c07e0b6ac.jpg)

**Comment by bastimeyer** [comment]
You've already opened #3151 two weeks ago which got then fixed in #3152. 

Which Streamlink version are you running?
Add a **full debug log as text** (not a screenshot) to your plugin issue report, just like the template asks you to do.

**Comment by LzNOHentai** [comment]
> You've already opened #3151 two weeks ago which got then fixed in #3152.
> 
> Which Streamlink version are you running?
> Add a **full debug log as text** (not a screenshot) to your plugin issue report, just like the template asks you to do.

It is an issue of the latest commit version of streamlink.
I have uploaded more log screenshots.

**Comment by back-to** [comment]
> And, I found I can't login.

delete `"$HOME/.cache/streamlink/plugin-cache.json"` and try again

> I have uploaded more log screenshots.

screenshots makes it unnecessarily complicated, just use normal text

**Comment by LzNOHentai** [comment]
> delete `"$HOME/.cache/streamlink/plugin-cache.json"` and try again

After delete plugin-cache.json, all looks like running normally.

Maybe the login problem is due to the cache. 
But I have no idea why it can't get the best and second best quaility during streaming just like the screenshots showed, and now it works well to get the timeshift archive.

Anyway, Thanks!
