### ISSUE TITLE
tv8.com.tr no playable source

### ISSUE THREAD

**Issue by itasli** [streamlink/streamlink#3183]
## Bug Report
- [x] This is a bug report and I have read the contribution guidelines.

### Description

can't find playable source.

### Expected / Actual behavior

hls file is supposed to be find

### Reproduction steps / Explicit stream URLs to test

``` 1. streamlink https://www.tv8.com.tr/canli-yayin ```

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.2
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin tv8 for URL tv8.com.tr/canli-yayin
error: No playable streams found on this URL: tv8.com.tr/canli-yayin
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/plugin_issue.md#L42-L53
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/bug_report.md#L47-L58

Post a **full debug log**. It is unclear which version you are using. The TV8 plugin was already fixed in #3080 recently

**Comment by itasli** [comment]
edited

**Comment by bastimeyer** [comment]
> Streamlink: 1.5.0

You are not using the **latest** version.
https://streamlink.github.io/install.html

As you can see here, there is a fix on the master branch since the last stable release:
https://github.com/streamlink/streamlink/compare/1.5.0...master

**Comment by itasli** [comment]
1.5.0 is the last stable release right ?

**Comment by mkbloke** [comment]
Yes, 1.5.0 is the latest release, but streamlink does not create a new release every time a plugin breaks and is then subsequently fixed.  If you rely on the stable releases only you could be waiting a while until a release is made that contains the fixed plugin.

As you seem to be using Windows, you could just grab the most recent nightly build of master if a plugin fix has been made to a plugin that you use.

See: https://github.com/streamlink/streamlink/actions?query=event%3Aschedule+is%3Asuccess+branch%3Amaster

If the plugin you are using doesn't work after that, then having checked for an existing issue report beforehand, you can create a new issue detailing the problem with the streamlink invocation command and debug log output.
