### ISSUE TITLE
Twitch stream closes when an ad is played

### ISSUE THREAD

**Issue by rustwo** [streamlink/streamlink#3186]
Bug Report
- [X] This is a bug report and I have read the contribution guidelines.

### Description
Whenever a twitch stream plays an ad the default player (VLC) crashes and ends the stream.

The only unusual option I have is providing an oauth token so that I look like a web viewer instead of a streamlink viewer (fix that I applied early this year when they tried to pull some shenanigans on 3rd party tool users).

When this started happening (within the last week) I checked the other issues here and added the following commands to my config:
twitch-disable-ads
twitch-low-latency

Neither of these stopped or changed the crash behavior when an ad was played by the streamer.

### Expected / Actual behavior

The twitch stream should either continue to play the content while the ad runs or at least resume playing content after the ad ends. Instead I have to restart streamlink and wait for another preroll to play.

### Reproduction steps / Explicit stream URLs to test

1. Open a twitch stream
2. Wait for streamer to play an ad

### Log output

Can't find the log file but this is the end of the output that was produced in the command prompt window:
C:\Windows\System32>streamlink twitch.tv/[streamname] 720p --loglevel debug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/[streamname]
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-disable-ads=True (disable_ads)
[cli][debug]  --twitch-low-latency=True (low_latency)
[plugin.twitch][debug] Getting live HLS streams for [streamname]
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p6
0, 1080p60 (best)
[cli][info] Opening stream: 720p (hls)
[plugin.twitch][info] Will skip ad segments
[plugin.twitch][info] Low latency streaming (HLS live edge: 2)
[stream.hls][debug] Reloading playlist
[plugin.twitch][info] Waiting for pre-roll ads to finish, be patient
[plugin.twitch][info] This is not a low latency stream
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequ
ence: None
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 10 to queue
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files (x86)\VideoLAN\VLC\vlc
.exe" --input-title-format twitch.tv/[streamname] -
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Download of segment 11 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Download of segment 12 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Download of segment 13 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Download of segment 14 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Download of segment 15 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Download of segment 16 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 18 to queue

### ### ### ### ### ### snipped ### ### ### ### ### ### ### 

[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 536 to queue
[stream.hls][debug] Download of segment 535 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 537 to queue
[stream.hls][debug] Download of segment 536 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 538 to queue
[stream.hls][debug] Download of segment 537 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 539 to queue
[stream.hls][debug] Download of segment 538 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 540 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 541 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 542 to queue
[stream.hls][debug] Adding segment 543 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 544 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 545 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 546 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 547 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 548 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 549 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 550 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 551 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 552 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 553 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 554 to queue
[stream.hls][debug] Adding segment 555 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 556 to queue
[stream.hls][debug] Adding segment 557 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 558 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 559 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 560 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 561 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 562 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 563 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 564 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 565 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 566 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 567 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 568 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 569 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 570 to queue
error: Error when reading from stream: Read timeout, exiting
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/3178#issuecomment-692979927
