### ISSUE TITLE
packages.flashmedia.AMFMessage: incorrect message body length

### ISSUE THREAD

**Issue by xkbd** [streamlink/streamlink#319]
```python
class AMFMessage(Packet):
    @property
    def size(self):
        size = 4
        size += AMF0String.size(self.target_uri)
        size += AMF0String.size(self.response_uri)
        size += AMF0Value.size(self.value)

        return size
```

Why size is set that way? And what is 4?
According to AMF specification length - property of **message body** without target-uri and response-uri:
(http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/amf/pdf/amf0-file-format-specification.pdf)
"The third field of an AMF message is the byte length of the message body"

It should be at least as follows:
```python
class AMFMessage(Packet):
    @property
    def size(self):
        size = AMF0Value.size(self.value)

        return size
```

**Comment by beardypig** [comment]
It's the size of the full packet: `target_uri`, `response_uri`, length of `value`, plus the size of the int to store the length of `value`. The size of the int that stores the length of `value` is 4, which is where that 4 comes from. It's not at all well commented, but you can see it in the `_serialise` method, [amf.py+155](https://github.com/streamlink/streamlink/blob/master/src/streamlink/packages/flashmedia/amf.py#155).

**Comment by xkbd** [comment]
It's absolutely clear, thanks :)
And not working in my case. AMF-gate does not properly handle messages with this length. 
Flash-apps also follow the specification.
Obviously it is a bug.

**Comment by beardypig** [comment]
OK, It's a bug in the `_serialise` method, it should be

```
packet += U32BE(AMF0Value.size(self.value)) 
```

`size` still refers to the size of the full message. 

You should report this on the flashmedia issues page, not that it's being maintained anymore... But maybe you'll find a fork or alternative. 

I'll make a PR for this next week, generally we aren't maintaining any of the vendor packages, updating when necessary of course. As this one is appears to be abandoned we'll probably want to replace it with a maintained package :-) It works fine for the existing plugins so it hasn't been a problem yet.

**Comment by xkbd** [comment]
Not difficult just to override method.
Then mark it as known issue.

**Comment by beardypig** [comment]
That's one way to do it. The class is not actually used anywhere in streamlink though.

**Comment by beardypig** [comment]
This has be fixed in the included `flashmedia` package.
