### ISSUE TITLE
Closing currently open stream

### ISSUE THREAD

**Issue by dexter101010** [streamlink/streamlink#3190]
## Issue

- [x] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by dexter101010** [comment]
>streamlink --http-cookie "Cookie= c_user=6b44436f0c96d44723b79e94d9c89d96uZPD1PcOpdMpB5ybt0YEfyOyRZ+KTgEoPSNRoyCuULecgYhp4Qaw7xI2gRyjCyQN0d389f01577dd02b48486a3c06e382ca; c_p=750a2eb812e03f6d101332dd0a5ae78164tAiu/VHh3q+5gkhLq3Sg==5fbf5358fced1a3ab8b9584edcdcb790; id=bd8fc496-c34d-49c4-9340-bc4cc647b880; JSESSIONID=2332991D56145AB6B9B5D659F316E219; __extfc=1" https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8 best
[cli][info] Found matching plugin spayee for URL https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/k/timestamp (502 Server Error: Bad Gateway for url: https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/k/timestamp)
[cli][error] Try 1/1: Could not open stream <HLSStream('https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...

**Comment by mkbloke** [comment]
You appear to be using your own plugin, presumably the one from issue #2253.  I don't know why you are doing that, given that you can access playlist URLs directly using the ```hls://``` prefix.  Using:

```streamlink hls://https://vcdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5cb05002e4b00db56cfb383a/u/5cd933e1e4b0c2b0f7965a3b/t/e5e97682c266459ecc0188ffbccc1feb/p/assets/videos/2019/04/12/5cb05002e4b00db56cfb383a/hls_1M_.m3u8 live```

still gives the same error (502 Server Error: Bad Gateway) when attempting to access the key URI.  This is a remote configuration issue and not something anybody here can help you with.  As it is, spayee.in is dreadfully mis-configured with regards to its SSL certificate, although that's not the prolem here.

**Comment by bastimeyer** [comment]
> [stream.hls][error] Failed to create decryptor: Unable to open URL:
> 502 Server Error: Bad Gateway

That's a server error, and not an issue with Streamlink.
Also, as @mkbloke has already said, you seem to be using a custom plugin with special key decryption logic. If you're having issues with custom plugins, then you need to ask where you've got it from, but not here. The cause of your issue however is an error response while trying to request the stream decryption key, and not the data of the decryption key itself.
