### ISSUE TITLE
Update codecov/coverage config and add lgtm.com check

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3191]
As an improvement to the code coverage reports, I'm proposing the following changes:

1. **Remove codecov-bot comment from pull requests**
   The comment with the status table nowadays gets added to the PR **checks** page ([example](https://github.com/streamlink/streamlink/pull/3187/checks?check_run_id=1144194464)) and can be read there. This will reduce the spamming (notifications as well) and also the audit log spamming when the bot usually updates its comment. The report page on codecov.io should be linked in the **checklist** next to the merge button, but for some reason it doesn't do that on the repo here and just links to their homepage. I don't see this behavior on the Twitch GUI repo and it correctly links to the generated report. That's probably a configuration issue here.
2. **Add branch coverage**
   `pytest-cov` currently only generates line coverage data, which isn't that detailed and useful. Branch/partial coverage data can be generated by adding [`--cov-branch`](https://pytest-cov.readthedocs.io/en/latest/config.html) to the [`pytest` command](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/.github/workflows/main.yml#L39).
3. **Split the coverage scopes**
   The coverage reports can be [split up by codecov into different "projects"](https://docs.codecov.io/docs/commit-status), eg. "overall" (default - should be disabled), "streamlink", "streamlink_cli", "plugins", "tests".
   This helps checking which parts are tested well enough and which are not (plugins for example), and different targets + thresholds can be defined. The split coverage projects will be listed separately in the PR checklist and commit status, but differentiating between "streamlink", "streamlink_cli" and "tests" is what we should do at least IMO. The tests [need to be added](https://github.com/streamlink/streamlink/blob/3a57a3ac6211b22843505c53a3466f8719dc3bdf/.coveragerc#L1-L3) by the coverage generator of course.
4. **Rename `codecov.yml` to `.codecov.yml`**
   CI provider config files should be a dotfile.

----

Regarding lgtm.com, this is a CI service which semantically analyzes the code ("AI based" :roll_eyes:) in addition to the code-linter's static analysis. This helps finding more potential issues and the service is free for open source projects.

We currently have over 50 unnoticed alerts, most of them being issues with regexes in plugins:
https://lgtm.com/projects/g/streamlink/streamlink/alerts/?mode=list

I already have this service enabled on the Twitch GUI repo, so all it takes selecting the Streamlink repo from the drop-down in the [Streamlink orga settings](https://github.com/organizations/streamlink/settings/installations/11010222).

Enabling it will add another entry to the checklist of PRs and pushed/merged commits.

----

But let's wait for the next release first before changing anything.

**Comment by gravyboat** [comment]
I'm in favor of all 4 points you noted.

**Comment by bastimeyer** [comment]
I don't want to submit a PR for this yet, but I have applied the changes to my test-account's fork here:
https://github.com/bastimeyer-test/streamlink-test/compare/master...ci/coverage/improvement-2020-09
This will make the CI fail once because of the codecov config which instead of an overall coverage **target** now has a **threshold** value of 1%, and due to the split, the percentage delta will be unusually high. You'll have to scroll down in the commit status popup to see the coverage status checks.

On the next commit though, a random code change demonstration, you can see a regular code change threshold and it succeeds:
https://github.com/bastimeyer-test/streamlink-test/compare/ci/coverage/improvement-2020-09...ci/coverage/improvement-2020-09-change-demo

And the random change commit as a PR (includes duplicates for push and pull_request events):
https://github.com/bastimeyer-test/streamlink-test/pull/5
https://github.com/bastimeyer-test/streamlink-test/pull/5/checks?check_run_id=1154464281

It looks like though that I've misconfigured the codecov details on the PR checks, because with the current config, the check looks like this:
https://github.com/streamlink/streamlink/pull/3194/checks?check_run_id=1149754683
The details are configured on the `comment` property which is also responsible for making a comment on the PR which we don't want. There must be a different config flag for the PR checks somewhere instead.

As you can see, I have split the coverage statuses into "streamlink", "streamlink_cli", "plugins" and "tests". The reason why I've made "plugins" its own status is that plugins are very rarely tested, because it requires stubbing/mocking network requests and simulating the plugin's site, and it doesn't make sense that the lack of proper tests should affect the coverage results of the regular streamlink modules. Also, the threshold value is not set on this status, because it would otherwise make almost all plugin PRs fail.

If you go to the report(s) on codecov.io, you can now also see the branch coverage. Line hit counts are unfortunately still wrong, because the python module which instruments the code for the coverage gathering doesn't support hit counting (yet), so it's either 0 or 1, regardless of how often a line/branch was hit.

----

What about the lgtm.com integration? Can this be turned on here? All it does is check for new alerts in PRs and fail if there's a new alert.

**Comment by gravyboat** [comment]
@bastimeyer The fork changes look good. We can always make some blank commits to the master branch if needed to get us pushed past that initial phase. Codecov also seems fine, I'm not too concerned about the line count.

I enabled the lgtm.com nitegration just now.

**Comment by bastimeyer** [comment]
The CI / commit status failure doesn't really matter and can be ignored when splitting up the reports. Blank commits don't solve this. The only way to make it not fail would be opening two PRs with separate build statuses, where only the second one sets the coverage thresholds and the first one doesn't have any success conditions at all. That's just unnecessary.

The line count is something we don't have control over and it has always been like this. I just wanted to mention it, since it's different from what I know from properly instrumented code in the JS world.

Regarding the issue which I thought was a misconfiguration, that might actually be a bug. I've already opened a thread on their support forum to ask about it. The PR checks don't have a summary when split up into projects. Only the overall default project, the one which combines everything, has a PR check summary. What I mean with summary is basically the content of the PR comment made by the codecov bot. This means that when we disable the comment, which I really want to do as it is too noisy, then we need to keep the default project. And this means that there will be one more entry in the commit status, making it 5 in total, "default", "streamlink", "streamlink_cli", "plugins" and "tests". Not sure how to feel about that. I want to keep the tests and plugins separate, so the only option if we want to reduce the number would be combining the "streamlink" and "streamlink_cli" coverage reports, but that isn't a great idea either if we already split up the reports.

Let me fix up the current config real quick and then open a PR with the changes here.

**Comment by bastimeyer** [comment]
The LGTM check needs an additional config, so that the useless JS PR check gets removed. It shows it by default, because we have minified JS code in the docs. We can either ignore the entire docs directory, among others, or just filter by file extension.

LGTM also has "extraction" phases, where it tries to build the app and sets up dependencies, etc., and there's a default config for various languages. Everything except python needs to be disabled.
https://lgtm.com/projects/g/streamlink/streamlink/logs/languages/lang:python

I will submit a config after I have successfully tested this on my fork.

**Comment by bastimeyer** [comment]
I was just checking the lgtm.com config today and was struggling a bit setting it up correctly (it's a real mess and PITA) and then found this new Github blogpost - what a great timing:
https://github.blog/2020-09-30-code-scanning-is-now-available/

I already knew that GH acquired Semmle (the company behind lgtm.com) last year, but didn't know that they already had their native code scanning in beta, otherwise I wouldn't have suggested the lgtm integration here. According to the blog post, GH just made code scanning available to public repos yesterday. It's basically the same as lgtm with the CodeQL queries they've provided over there by default, but now it can be integrated as a regular actions workflow and the configuration is much better.

This means we can remove the lgtm.com integration again.

https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/automatically-scanning-your-code-for-vulnerabilities-and-errors
