### ISSUE TITLE
Hello, ask for help with plugin dev

### ISSUE THREAD

**Issue by sadovsf** [streamlink/streamlink#3195]
Hello, i was trying to reach you (to be specific @back-to contributor) to ask how do you find out details for loading stream links from web page.I would like to be able to maintain some of the deprecated myself but when i open pretty much any plugin (obsolete or not) there are often details to get to stream i have no idea how i could find out. Is there some place you could send me to learn or could you maybe contact me with some hints? Contact details are in my github profile.

I'am really sorry for choosing this way to contact you but i failed to find any other :-(

**Comment by mkbloke** [comment]
It mostly involves opening your browser debugger (in Chrome and Firefox with key F12).  You need to find something that links the given page with an eventual stream/playlist URL.  That could involve looking at API requests in the network tab or extracting the relevant JSON from the page source.  It's a matter of reverse engineering a sequence of events if API requests are made, for example, and then implementing those in the plugin with the necessary values extracted from the page as part of the API request.

Unfortunately, I don't have any links to hand which might help you to learn this.  Perhaps other people might have links to some tutorials about it though.

I can only suggest you start to look at your browser debugger while visiting a streaming site and try to learn from that, perhaps in unison with looking at a working streamlink plugin so that you can see how the plugin implements the necessary logic to mimic what happens in your browser when you visit a site.

**Comment by sadovsf** [comment]
I see, that is what I was mostly trying but usually it seems like these links are just appearing out of nowhere 😁

I will try to reverse ingeneer some stream based on existing plugin that is I good point. Maybe you could add page into documentation a ou some usual steps you are going through when working with new stream? Along with some not so trivial example? I believe this would help a lot to community to make their own plugins and lift up some of the implementations or fixes from your back.

**Comment by bastimeyer** [comment]
There is no point in documenting this, as it's different for every site implementing live streams. There are standards for different streaming protocols, but that's about it and Streamlink implements those standards. You'll have to debug it to the point where those standardized protocols are being used on the site and then plug them into the available interfaces in Streamlink while reverse engineering the required steps in a plugin, if it's necessary. If something deviates from those standards, sometimes this can be worked around with custom logic. Everything else requires knowledge in web development and modern web standards, so if you don't have that, you're out of luck.

And if you want to write a plugin without any prior knowledge of the Streamlink APIs, take a look at other plugins first which were recently updated and see how it's done.

**Comment by sadovsf** [comment]
It is not much about documenting specific process rather about writing down the general idea. Where you usually look for entry points. Maybe link to some good javascript reverse engineering source. What to look for etc... Essentially lower learning curve a bit at the start. I believe more people would get into it this way and so they would be able to help with dev generally as i mentioned before

**Comment by bastimeyer** [comment]
> Maybe link to some good javascript reverse engineering source.

As I've said, there is none. If you don't know web development, guides won't help you.

However, this is the general way of debugging the stream source:
Open your web browser's dev tools, go to the networks tab, enable request recording, reload the page and look for the request(s) of the stream entry point. In case of HLS streams, you'll be looking for the first ".m3u8" request or one which has a 3xx status code and points towards the HLS (master) playlist. Either figure it out on your own how these requests were made, or walk down the browser's (async) call stack and dig through the site's code. If the JS code is minified/obfuscated and the site doesn't have JS sourcemaps available (some actually do for whatever reason), then you'll have to use your browsers unminify/beautify feature and deal with the resulted nonsense code. Then set necessary breakpoints in the code where you think you'll need to read the contents of some variables from and reverse engineer it. If there are geo-locks or auth data required, this will make it more difficult for you. And in case of DRM, you don't have a chance. Once you've figured out how what's required to get to the stream URL and which parameters / data / HTTP headers are required, you can write the necessary python code in a Streamlink plugin and use the available Streamlink APIs and utility methods, similar to the already existing plugins.

**Comment by sadovsf** [comment]
This is exactly what i was talking about 👍
Sprinkle it with few examples from real life existing plugin and pretty simple entry point for new plugins is done and can be put into documentation. I believe something similar could be prepared for other types of streams as well. I believe that it looks like nothing to you as you are working with it quite a long time but for someone who just started having these few sentences is like day and night
