### ISSUE TITLE
aljazeera error

### ISSUE THREAD

**Issue by OrionRandD** [streamlink/streamlink#3198]
[cli][info] Found matching plugin aljazeeraen for URL https://www.aljazeera.com/live/
[plugin.aljazeeraen][error] Could not find a video ID on this page
error: No playable streams found on this URL: https://www.aljazeera.com/live/

**Comment by OrionRandD** [comment]
How can I fix this? I like aljazeera news very much through streamlink...

**Comment by johnthecracker** [comment]
Playlist hasn't changed. 
If in doubt, you can find it in browsers network monitor or with Telerik fiddler.
Or you can simply copy it from here and use it as I do.

```
C:\>streamlink https://live-hls-web-aje.getaj.net/AJE/03.m3u8 best
[cli][info] Found matching plugin hls for URL https://live-hls-web-aje.getaj.net/AJE/03.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by OrionRandD** [comment]
@johnthecracker 
This line worked for me here -> streamlink https://live-hls-web-aje.getaj.net/AJE/03.m3u8 best
thx a lot :+1:

**Comment by mkbloke** [comment]
You can also use the master index for live:
```
streamlink https://live-hls-web-aje.getaj.net/AJE/index.m3u8
[cli][info] Found matching plugin hls for URL https://live-hls-web-aje.getaj.net/AJE/index.m3u8
Available streams: 240p (worst), 360p, 420p, 540p, 720p, 1080p (best)
```
There's also: https://www.youtube.com/channel/UCNye-wNBqNL5ZzHSJj3l8Bg

**Comment by OrionRandD** [comment]
@mkbloke Thx a lot :+1:
