### ISSUE TITLE
Cant stream a live stream (youtube)

### ISSUE THREAD

**Issue by spartacruz** [streamlink/streamlink#320]
Hi guys, I was using 'livestream' before and there's no probs at all. Since I migrate to 'streamlink', I couldn't play a live stream. 

I can apply the same methods to the 'streamlink', as well as im using 'livestream', right?

My command is simple : streamlink.exe www.youtube.com/watch?v=ZWU009d5i7c 360p

And, this what I get (looping result).
![Loop](http://i67.tinypic.com/34gsq6q.png)

So, Is there any method or something? Am I do a mistake?
Please help

Thanks.

ps : I'm using Nightly version of VLC, the same thing when I'm  using 'livestream'

**Comment by beardypig** [comment]
The latest nightly of Streamlink will likely resolve your issue :-)

You can get it from here [streamlink-latest](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe)

**Comment by Vangelis66** [comment]
Merry Christmas, all! :santa: 

Isn't this technically a duplicate of #313 ?

**Comment by beardypig** [comment]
@Vangelis66 you're right.

**Comment by spartacruz** [comment]
@beardypig Oh thanks for the advice! You can close the thread now.

@Vangelis66 and Happy Holiday also! Yeah you're right. I missed to look on that issue. Sorry
