### ISSUE TITLE
New wasd.tv plugin can't load VODs

### ISSUE THREAD

**Issue by aditorens** [streamlink/streamlink#3203]
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.
Hi there.
Since new 1.6.0 streamlink version I noticed that wasd.tv plugin can't load VODs from site.
Why was it done? It was very helpful.
But now I can only record online-streams from wasd.tv (supportable url-format now is only wasd.tv/nickname).
Is it possible to expand wasd.tv-plugin functionality (make vod-links (wasd.tv/nickname/videos?record=123456, for example) supportable)?

Thanks in advance.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
VOD support was dropped on purpose in the PR: https://github.com/streamlink/streamlink/pull/3139. Probably didn't work and we've been moving away from supporting VODs. There are plenty of tools out there already for that and we want to focus on live streams.

**Comment by yo8z6gv** [comment]
> VOD support was dropped on purpose in the PR: #3139. Probably didn't work and we've been moving away from supporting VODs. There are plenty of tools out there already for that and we want to focus on live streams.

does not recognize private links:
eg:
https://wasd.tv/private-stream
( error: No plugin can handle URL )
