### ISSUE TITLE
stream.RTMPStream. Specify multiple arguments with same names for rtmpdump

### ISSUE THREAD

**Issue by xkbd** [streamlink/streamlink#321]
From `streamlink.stream.RTMPStream` i need to pass rtmpdumps params with same names:
`--conn A:0 
--conn B:1 
--conn C:2 `

As a workflow i use crunch 
```python
"conn" : "value --conn value --conn value"
```
But i would like to do it correctly.

**Comment by beardypig** [comment]
There isn't a correct/good way to do this, `RTMPStream` uses the `pbs` package to run `rtmpdump` and I don't think that it supports multiple arguments with the same name. `pbs` is also not maintained anymore, `sh` is suggested as an alternative so maybe we can migrate to that and improve the API for `RTMPStream`. 

It looks like all of the vendored packages might need reviewing/updating, I'd personally like to remove a couple of them and just add them as regular dependencies (unless they have streamlink only patches, but it's better to avoid those or subclass, as you suggested in the other issue for flashmedia).

**Comment by beardypig** [comment]
Without a complete rewrite of the StreamProcess class it won't be possible to affect this. `pbs` has been replaced by `sh`, however `sh` does not support Windows so is not a viable alternative. `pbs` also has some patches made to it for `streamlive` (from `livestreamer` days)...

**Comment by gravyboat** [comment]
@beardypig I would say it isn't worth investigating further then since Windows compatibility is a deal breaker. This might be adding to known issues, then closing this issue.

**Comment by beardypig** [comment]
Yep. Not that rewriting the StreamProcess is a big piece of work... I'll add it to the TODO list ;-)

I'll do some more work on the Plugin Writing guide and I'll make a note of this in there :-) Suppose you'd need to do something similar to give multiple connect parameters on the command line too.

**Comment by xkbd** [comment]
> `"conn" : "value --conn value --conn value"`

Unfortunately it does not work. rtmpdump encodes it as one.

**Comment by beardypig** [comment]
Since #441 has been merged this is now possible.
