### ISSUE TITLE
ok.ru has an issue

### ISSUE THREAD

**Issue by jalalsfs** [streamlink/streamlink#3211]
Hello there,

Before, I was playing the videos from ok.ru website with streamlink without any issue,
today, when I try I get this missage:

`$ streamlink https://ok.ru/video/1963340008068
[cli][info] Found matching plugin okru for URL https://ok.ru/video/1963340008068
[plugin.okru][error] unable to validate _data_schema for https://ok.ru/video/1963340008068
error: No playable streams found on this URL: https://ok.ru/video/1963340008068`

I am using 1.6.0 version package from official Fedora 32 repo.
Thank you.

**Comment by johnthecracker** [comment]
Try on another PC for a test, it may work. 
```
j@j:~$ streamlink https://ok.ru/video/1963340008068 best
[cli][info] Found matching plugin okru for URL https://ok.ru/video/1963340008068
[cli][info] Available streams: 144p_http, 240p_http, 360p_http, 480p_http, 144p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: /usr/bin/vlc
```

**Comment by mkbloke** [comment]
Are you continuing to get the error for that URL?  As per johnthecracker, I can also access the URL you provided.

**Comment by jalalsfs** [comment]
I see when I use VPN, it works normally, but while accessing from the local ISP, it refused most the time.
Thank you so much.

**Comment by mkbloke** [comment]
In which country is your local ISP and in which country is your VPN IP?

**Comment by jalalsfs** [comment]
> In which country is your local ISP and in which country is your VPN IP?

India, VPN is in Germany

**Comment by mkbloke** [comment]
Not that I can see anything can be done about the problem, unfortunately, but it's interesting that it happens a lot from an Indian IP and not from a European IP.
