### ISSUE TITLE
--hls-start-offset flag appears to be broken for Youtube Livestreams?

### ISSUE THREAD

**Issue by stalkerrs** [streamlink/streamlink#3212]
So I'm using "--hls-duration 00:00:30 --hls-start-offset 00:05:00" to capture 30 seconds, 5 minutes ago on a Youtube livestream. Although it only ends up capturing 30 seconds of the current livestream. 

Am I using the wrong combination of flags? 

Edit:

This also only gets the current time:
streamlink YouTubeURL 480p --hls-start-offset 00:06:03 -o outputFile

**Comment by bastimeyer** [comment]
#2936
