### ISSUE TITLE
Chunk duration command-line option so downloaded streams are automatically split into separate file of X minutes long each.

### ISSUE THREAD

**Issue by holdingsllc** [streamlink/streamlink#3214]
## Feature Request

- [ ] Chunk duration or chunk size command-line option to chunk large stream into smaller files either by duration or file size.

### Description

Often video streams will have 10 hours of uninteresting content with just a few minutes of something happening on the live video so having the option to chunk a stream into separate videos of 5-10 minutes would make it so much easier to just delete the uninteresting videos than having to edit and trim every single giant video file.

### Expected / Actual behavior

The following would seamlessly stop the streamlink stream as soon as the chunk limit is reached and start a new file without any data gaps in between:

    $ streamlink --chunk-duration 5m --output "%d.mkv" URL

or

    $ streamlink --chunk-size 50MB --output "%d.mkv" URL

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/1245
