### ISSUE TITLE
i24News Live

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#3218]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

This is live broadcast at its original source.
It is mostly in arabic and sometimes in english.
Player is Brightcove.

### Example stream URLs

https://www.i24news.tv/ar/%D9%85%D8%A8%D8%A7%D8%B4%D8%B1

### Additional comments, screenshots, etc.

Playlist:
```
https://i24alive2.akamaized.net/773a2fa387914315ad11e6957cd54f6e/eu-central-1/5377161796001/playlist-all_dvr.m3u8?__nn__=5476555825001&hdnea=st=1601641800~exp=1601645400~acl=/773a2fa387914315ad11e6957cd54f6e/eu-central-1/5377161796001/*~hmac=d2f324e1c23c157fc00d61490e95d4eaf79f9128abf01721d7fcb40cc6b6e5b4&__nn__=5476555825001&hdnea=st=1593502200~exp=1593505800~acl=/773a2fa387914315ad11e6957cd54f6e/eu-central-1/5377161796001/*~hmac=e10085a246c4608e9f04e7d4b925449af4c8477024068d6ca8e4e3f9de7364b1&__nn__=5476555825001&hdnea=st=1579100400~exp=1579104000~acl=/773a2fa387914315ad11e6957cd54f6e/eu-central-1/5377161796001/*~hmac=c186cee77d80e35d26659b79813e3945270ce3339b49292ac0a39914dba1ffc5
```
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2347008,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=1280x720
profile_0/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
#EXT-X-STREAM-INF:BANDWIDTH=2083840,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=960x540
profile_1/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
#EXT-X-STREAM-INF:BANDWIDTH=1323008,CODECS="avc1.77.32,mp4a.40.2",RESOLUTION=854x480
profile_2/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
#EXT-X-STREAM-INF:BANDWIDTH=1015808,CODECS="avc1.77.31,mp4a.40.2",RESOLUTION=640x360
profile_3/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
#EXT-X-STREAM-INF:BANDWIDTH=657408,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=480x270
profile_4/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
#EXT-X-STREAM-INF:BANDWIDTH=452608,CODECS="avc1.77.21,mp4a.40.2",RESOLUTION=320x180
profile_5/chunklist_dvr.m3u8?hdnea2=exp=1601670060~acl=%2f773a2fa387914315ad11e6957cd54f6e%2feu-central-1%2f5377161796001%2f*~hmac=1460bf3d490964975f14aab5f990573f75201c377c543d1bff19af95ff121840
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
Before you edited the comment you noted "for people who want this". I'd like to see a request from someone who is actually going to use this before we consider doing the work to add it. There's no viewer count so we have no idea about the popularity of the stream, there could be 0 people actually watching for all we know.

I hate to harp on this again but it feels like I have to lately with the abundance of plugin requests for niche sites with very few or an unknown number of viewers. We aren't adding plugins just to add them, that's pointless work and just leads to bloat that makes Streamlink harder to maintain and slows down the plugin loading on devices. I'm closing this for now. When someone comes around that is going to watch this and can show me some stats that people are truly viewing this site we'll reconsider.

**Comment by johnthecracker** [comment]
Right now I am watching this in english. This is the fact that I can post.
I don't know if they have timed schedule for broadcast in one language and another,
arabic and english.

I thought to close this thread myself when I discovered they broadcast in arabic
and then later on I noticed broadcast in english again so I deleted about 10 comments.
Site is hard to watch in player directly and plugin request is justified for myself.
Who else will watch it is very good point as well.
If broadcaster wanted wider audience themselves they wouldn't demand 
"membership" for their englih only broadcast.

**Comment by johnthecracker** [comment]
3 persons can't write plugins for all the planet.
It would be helpful to have some list of other people's plugins in one place to find them
and who wants them load them as desired.

As of now you could do 50% - 50% with your existing plugins.
It is possible to offload streamlink even more and place less relevant plugins to link somewhere else
and make them available to minority who is interested in them to download from there.

For example, if I would know how to write a plugin for i24News live arabic
I would write one and how can I inform other streamlink users that I can
give them a plugin if they want one as you don't want it with streamlink ?
I can think of "fork" as the only option and if I "fork" 
how to find all "forked" plugins in one list.
