### ISSUE TITLE
Youtube authentication support

### ISSUE THREAD

**Issue by vil33** [streamlink/streamlink#3219]
## Feature Request

- [ x] This is a feature request and I have read the contribution guidelines.

### Expected / Actual behavior
Support for private youtube livestreams/videos(membership streams). Currently not supported. Something similar to yt-dl where youtube password and username can be passed in.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I don't use yt-dl so I'm not that familiar with it but I thought they supported outputting to players instead of just a file now?

**Comment by back-to** [comment]
you could try to use `--http-cookie`
https://streamlink.github.io/cli.html#cmdoption-http-cookie

but otherwise it is not really worth to deal with a google login.
