### ISSUE TITLE
Streamlink docs site https://streamlink.github.io/  Freezes the browser ?

### ISSUE THREAD

**Issue by DBARUNNER** [streamlink/streamlink#322]
I am trying to get the documentation and API guid for streamlink to stream videos
when i go to Streamlink docs site : https://streamlink.github.io/ the browser hangs for a while and it freezes
what is the Issue behind this? or please provide an alternative site to the docs,thank you for your work

**Comment by xkbd** [comment]
https://github.com/streamlink/streamlink/tree/master/docs

**Comment by gravyboat** [comment]
It's hosted on the freebie github.io hosting. No one has ever reported such an issue, did you try a different browser?

**Comment by DBARUNNER** [comment]
@gravyboat Did you opened the link yourself ? i am using Firfox in Linux?

**Comment by gravyboat** [comment]
@DBARUNNER The docs work fine for me running Firefox on both Linux and Windows 7.

**Comment by RosadinTV** [comment]
For me works fine even in Internet Explorer & MS Edge.
(Also tried in Opera, Chrome and Firefox)

**Comment by beardypig** [comment]
No issues on macOS with Firefox, Chrome or Safari. 
No issues on Windows 10 with Firefox, Chrome or Edge. 
No issues on Ubuntu 14.04/16.10 with Firefox or Chrome.

**Comment by gravyboat** [comment]
I'm going to close this out, definitely seems like a local issue. If you determine it happens in multiple browsers or review the logs and determine it's a bug on the site that we can fix please reopen the issue.
