### ISSUE TITLE
Crunchyroll without subtitles

### ISSUE THREAD

**Issue by nexcit** [streamlink/streamlink#3222]
## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.

### Description

Want to download videos from crunchyroll raw/without hardsub i have checked the https://streamlink.github.io for info but have not found any is it possible to get videos without subtitles. The closet i found in #621 that the videos download in hardsub of the code design is that so?

Sorry if i post in the wrong section havent use "issues" tab before.

### Additional comments, screenshots, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
This is not possible using the current method. As you pointed out, #621 has relevant details.
