### ISSUE TITLE
zattoo - plugin broken

### ISSUE THREAD

**Issue by matthiasschulenburg** [streamlink/streamlink#3225]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

Using zattoo plugin fails since some days during init/logn phase

### Expected / Actual behavior

init/login should work with provided credentials - this doesn't work

### Reproduction steps / Explicit stream URLs to test
start a streamlink session using zattoo plugin
streamlink 1.6.0 on Win10

start streamlink

c:\Daten\Streamlink>c:\Users\msg\OneDrive\Portable\streamlink\streamlink.bat --output c:\daten\Streamlink\ZDF_test.mp4 --zattoo-email email --zattoo-password passwd https://zattoo.com/channels?channel=zdf best

### Logs

```
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/channels?channel=zdf
error: Unable to open URL: https://zattoo.com/zapi/session/hello (403 Client Error: Forbidden for url: https://zattoo.com/zapi/session/hello)
```

### Additional comments, screenshots, etc.
can test a fix

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Please provide ```-l debug``` logging as requested in the issue template, otherwise it's likely this will just get closed.

**Comment by mkbloke** [comment]
Also, have you checked previous issues like #3197 which was fixed in #3202?

**Comment by matthiasschulenburg** [comment]
ok, problem seems to be fixed since some days, sorry for circumstances. Got & tested the fix, works. Great.

**Comment by popy2k14** [comment]
Sorry to hijack this thread but don't want to open another.
How do you get the urls for zattoo live tv, recordings and replay tv?

Tried to copy from the website without success.

Thx

**Comment by matthiasschulenburg** [comment]
Hi,

 

live tv (station view, see below) & recordings from website, replay tv doesn’t work from there, don’t have a solution here.

 

Regards Matthias

**Comment by popy2k14** [comment]
Hey Matthias.

Thanks a lot for your answer.
Cant see any screenshot above, should there be one?

thx a lot

**Comment by matthiasschulenburg** [comment]
Hi,

 

email again as pdf.

 

Regards

Matthias
