### ISSUE TITLE
Vaughnlive freeze with MPV

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#324]
Open "http://vaughnlive.tv/mega_simpson" with Streamlink via MPV result in a freezed output.
Almost sure the problem is related to the end time of the stream.
With other streams end time is 00:00 but with this stream is 1193:00:13 (kinda strange because is a live stream)

**Comment by beardypig** [comment]
Does the fix in #311 help? Or does it only happen with mpv? If it's just mpv I'd say that it'd a "won't fix" issue and we add a note on the known player issues.

**Comment by RosadinTV** [comment]
@beardypig I found a way to fix this, adding the --no-initial-audio-sync parameter to MPV
For example:
"Streamlink.exe" "http://vaughnlive.tv/mega_simpson" best --player "MPV\mpv.exe" --player-args "--no-initial-audio-sync {filename}"
So definitely a MPV problem.

**Comment by beardypig** [comment]
OK, maybe we should add that to the players page known issues :-)
