### ISSUE TITLE
error starting stream on twitch

### ISSUE THREAD

**Issue by Caeliiaa** [streamlink/streamlink#3242]
Hello,

I have installed streamlink on my linux distribution, but when I was going to run it to watch a stream, it constantly gave me an error.

code:

> $ streamlink --loglevel debug twitch.tv/rubius 720p
[cli][debug] OS:         Linux-4.19.0-9-amd64-x86_64-with-MX-19.2-patito_feo
[cli][debug] Python:     3.7.3
[cli][debug] Streamlink: 1.0.0
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/rubius
[plugin.twitch][debug] Getting live HLS streams for rubius
error: Unable to open URL: https://api.twitch.tv/api/channels/rubius/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/rubius/access_token.json?as3=t)

It is exactly the same with any twitch channel. :u

**Comment by mkbloke** [comment]
As requested in the plugin issue template:

- [ ] Description and/or reproduction steps are insufficiently detailed
- [ ] Streamlink version in use not specified
- [ ] Full ```--loglevel debug``` log output not provided
- [ ] Research of prior issues/fixes appears to be insufficient [1]

Other feedback:
- [ ] Issue is out of scope and/or should be reported/help sought elsewhere
- [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
- [x] User appears to be using an outdated Streamlink version/plugin
- [ ] Other (see below)

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[1] [Search all open/closed issues/pull requests](https://github.com/streamlink/streamlink/issues?q=)

**Comment by Caeliiaa** [comment]
when I run the streamlink version the result is this:

> $ streamlink --version
streamlink 1.0.0

I don't understand it, I have already uninstalled and reinstalled streamlink as it says on the page, any suggestions? or is it that for linux the version is 1.0.0?

**Comment by mkbloke** [comment]
If you've installed it via your system package manager, it's out of date.  You either need to find a repository that contains current builds or install via the virtual env method as detailed on the install page.  Doing an install in a virtual env of the master branch will mean you're using the most recent version of Streamlink and its plugins.

**Comment by Caeliiaa** [comment]
nstall streamlink from terminal, when you run

> sudo apt update

it did not require any update so then run the command
sudo apt install streamlink and this is the code that came out

> $ sudo apt install streamlink
Reading package list ... Done
Creating dependency tree
Reading the status information ... Done
The packages listed below were installed automatically and are no longer required.
  python3-pypdf2 socat xsel
Use "sudo apt autoremove" to remove them.
The following NEW packages will be installed:
  streamlink
0 updated, 1 new will be installed, 0 to remove, and 0 not updated.
69.3 kB of files need to be downloaded.
172 kB of additional disk space will be used after this operation.
Des: 1 http://deb.debian.org/debian buster / main amd64 streamlink all 1.0.0 + dfsg-1 [69.3 kB]
Downloaded 69.3 kB in 0s (313 kB / s)
Selecting the previously unselected streamlink package.
(Reading the database ... 350343 files or directories currently installed.)
Preparing to unpack ... / streamlink_1.0.0 + dfsg-1_all.deb ...
Unpacking streamlink (1.0.0 + dfsg-1) ...
Setting streamlink (1.0.0 + dfsg-1) ...
Processing triggers for man-db (2.8.5-2) ...

(It is in Spanish because it is my native language sorry)

but then, download the .deb file from the streamlink page, and this way it works for me now when I run

> streamlink --version
streamlink 1.5.0

yes, what is it :)
thanks
