### ISSUE TITLE
Is it possible to add a flag to record stream as soon as it ends?

### ISSUE THREAD

**Issue by Deep0d0** [streamlink/streamlink#3248]
## Feature Request

- [x ] This is a feature request and I have read the contribution guidelines.

### Description

 Basically, since Youtube switched to DASH, we cannot record from the beginning, so I was thinking. Is is possible to add a flag to record a live stream AS SOON as it ends?

### Expected / Actual behavior

 Display a message similar to that of --retry-streams, and then wait for the live stream to end. Then begin recording it once it has ended. Currently, something like this is not possible, to my knowledge, and would be a temporary fix for #2936 

### Additional comments, screenshots, etc.
![Screenshot 2020-10-12 203158](https://user-images.githubusercontent.com/60404672/95801941-031b9b00-0cca-11eb-88cf-1c1192e733fa.png) 
Message that would show when this flag is activated

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This isn't functionality we'd support in Streamlink. You could write some sort of wrapper script but this is outside the scope of the project.
