### ISSUE TITLE
Support for nbcsports.com?

### ISSUE THREAD

**Issue by yhs4260** [streamlink/streamlink#325]
Hi guys I wonder if this plugin would support streams from nbcsports.com?

I would love to see this feature if it is possible.

**Comment by beardypig** [comment]
The video on demand stuff that is free and not geo-restricted should be simple enough. They appears to be plain HLS streams. However, the live streaming stuff requires a cable subscription, which I don't have, so I cannot test if it will be possible or not...

**Comment by gravyboat** [comment]
@beardypig I don't know if we should support that anyways, the cable subscription stuff seems to change regularly and be a pain in the ass for most of these sites. Seems like it's more work than it's worth and we don't want them trying to take us down.

**Comment by gravyboat** [comment]
We've done what we can over in #760 to support to support the freely available streams. I'm going to close this out for now.
