### ISSUE TITLE
Show text indicating a sideloaded Plugin

### ISSUE THREAD

**Issue by Skibicki** [streamlink/streamlink#3252]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description
To avoid using an outdated sideloaded plugin instead of a default plugin, there should be a line indicating when the currently used plugin is a sideloaded version.
### Expected / Actual behavior
Show indicator line below "Found matching plugin" line.

**Comment by back-to** [comment]
you can already see it if you use `-l debug`

```
[session][debug] Plugin twitch is being overridden by twitch.py
```
