### ISSUE TITLE
Dlive error: Could not find username.

### ISSUE THREAD

**Issue by Frankthetankk** [streamlink/streamlink#3253]
> Seems this issue is happening again, as I'm getting the following error:
> `error: Could not find username`
>
> Not sure how long this has been an issue again though, since I do not watch DLive much.
>
> I'm using Streamlink version 1.6.0 on Windows 10.
>
> Edit: Replays seem to work fine though, but live streams is where I'm getting this error.

_Originally posted by @Robby- in https://github.com/streamlink/streamlink/issues/2965#issuecomment-707434757

Same problem as Robby

**Comment by bastimeyer** [comment]
> I'm using Streamlink version 1.6.0

You are not using the **latest** version. The plugin has just been fixed: #3239
https://github.com/streamlink/streamlink/commits/master

Apart from that, a **debug log** is required for plugin issues.

You can install the latest version as described here:
- https://streamlink.github.io/install.html#pypi-package-and-source-code
- https://streamlink.github.io/install.html#windows-binaries
