### ISSUE TITLE
TV-TOYA

### ISSUE THREAD

**Issue by Landser88** [streamlink/streamlink#3256]
Hello, is it possible to make a plugin for this page https://go.toya.net.pl/25-kamery or update it.

**Comment by Landser88** [comment]
> 
> 
>Hello, is it possible to make a plugin for this page https://go.toya.net.pl/25-kamery or update it.

**Comment by bastimeyer** [comment]
> make a plugin

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/tvtoya.py

> or update it

- https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
- https://github.com/streamlink/streamlink/issues/new?template=plugin_issue.md
