### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3258]
I'd like to have a new release this weekend, as there are important changes on the master branch for a few weeks now which should be published as a stable release.

Do we have any PRs which need to be merged first? Any other blockers or important changes still missing?

After this next release, the py2 removal and preparation for `2.0.0` can begin (#3235).

**Comment by gravyboat** [comment]
I don't believe there are any blockers. Maybe let's get https://github.com/streamlink/streamlink/pull/3251 merged (not sure why you didn't just merge after you approved @bastimeyer). I'd say that https://github.com/streamlink/streamlink/pull/3255 is worth adding, but that seems like there is some conflicting thought

**Comment by Billy2011** [comment]
I would like to add a few more webcam plugins for wetter.com, ozolio.com and attheshore.com, but if they not be merged, then I leave it.

**Comment by gravyboat** [comment]
@Billy2011 We've actually decided against adding any additional static webcam plugins [(see #11 here)](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests) like this so they wouldn't be merged. We're concerned about plugin bloat and without enough data to back up actual viewership on these sorts of plugins we don't want to add more niche streams.

**Comment by gravyboat** [comment]
@bastimeyer I looked again this morning and https://github.com/streamlink/streamlink/pull/3255 is the only PR left open that I see as valid discussion for inclusion in this release, after a decision is made there I think we're good to go.
