### ISSUE TITLE
[Facebook] No playable streams found on this URL.

### ISSUE THREAD

**Issue by DawgNewb** [streamlink/streamlink#3271]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description

Feel like they changing something for the last couple day. I couldn't do anything with facebook.

### Reproduction steps / Explicit stream URLs to test

1. Copy plain live's facebook link or changing from facebook.com/watch/live/?v=xxxxxxxxxxx&ref=watch_permalink to normal video link.
2. Usually even without any command it will show me the resolution.
3. Now it's only "No playable streams found on this" debug log below

### Log output

```
[Streamlink for Windows v1.7.0 - Git 8bc84d0]
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.3
[cli][debug] Streamlink: 1.7.0+8bc84d0
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
[cli][info] Found matching plugin facebook for URL facebook.com/xxxxxxx/videos/xxxxxxxxx/
[plugin.facebook][debug] No meta og:video:url
[plugin.facebook][debug] Falling back to playlist regex
[plugin.facebook][debug] Falling back to tahoe player
[plugin.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: facebook.com/xxxxxxx/videos/xxxxxxx/
```

### Additional comments, etc.

Love yall it's been 2 years since I last report fb issues.

I'm not testing with COOKIES yet if you could tell me about which one I need would be great! [sb datr c_user spin wd xs fr]
But so far as long as I can run the vid without my account I guess it wouldn't need cookie.
Thank you.

**Comment by back-to** [comment]
it should work when you remove `self.session.http.headers.update({'User-Agent': useragents.CHROME})` from the file

https://github.com/streamlink/streamlink/pull/3272

```
streamlink https://www.facebook.com/Firerecordingstudio/videos/405703290823328/
[cli][debug] OS:         Linux-5.4.0-51-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.7.0+2.gdf6ab12.dirty
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/Firerecordingstudio/videos/405703290823328/
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[cli][info] Available streams: 144p+a66k (worst), 144p+a98k, 144p+a130k, 240p+a66k, 240p+a98k, 240p+a130k, 360p+a66k, 360p+a98k, 360p+a130k, 480p+a66k, 480p+a98k, 480p+a130k, 720p+a66k, 720p+a98k, 720p+a130k (best)
[cli][info] Opening stream: 720p+a130k (dash)
```

**Comment by scottbernstein** [comment]
Opening a new issue because even after making this change I have one URL that still refuses to work

**Comment by hiepnhl** [comment]
It's pretty weird. The fb plugin worked last week but now it doesn't. Does anyone have the same issue?

**Comment by bastimeyer** [comment]
Don't necro-bump. Open a new issue with an appropriate debug log if you think it's indeed a plugin issue.
https://github.com/streamlink/streamlink/issues/new/choose
