### ISSUE TITLE
It only clips the end

### ISSUE THREAD

**Issue by DogePlayz-Dev** [streamlink/streamlink#3283]
## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.

### Description

 
I downloaded the stream on youtube, Then it only captured the complete end

### Expected / Actual behavior

I tried to download the WHOLE stream (youtube) to move it to vimeo

### Reproduction steps / Explicit stream URLs to test

1. ...Make it support the whole stream
2. ...Please get it fixed. I want to use this.

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the plugin issue template:
* - [x] Description and/or reproduction steps are insufficiently detailed
* - [x] Streamlink version in use not specified
* - [x] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[1]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[2]] [[3]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Search all open/closed issues/pull requests][1]
[[2]] [Install the most recent version of Streamlink][2]
[[3]] [Check the master branch for plugin updates][3]

[1]: https://github.com/streamlink/streamlink/issues?q=
[2]: https://streamlink.github.io/install.html
[3]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

**Comment by gravyboat** [comment]
Not enough information and likely to do with https://github.com/streamlink/streamlink/issues/2936, closing.
