### ISSUE TITLE
Aqstream.com support

### ISSUE THREAD

**Issue by cameololm** [streamlink/streamlink#3289]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

This site broadcasts Korean and Japanese TV channels for free.

### Example stream URLs

1. https://aqstream.com/
2. https://aqstream.com/kor
3. RTMP channel: https://aqstream.com/kor/sbs/SBS-Stream-4
4. HLS channel: https://aqstream.com/kor/sbs/SBS-Stream-5

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
This site was returning an "Error 520" yesterday already and I've checked it again now, and it's still failing.

Also
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
> Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.

When searching for "aqstream" on Google, one of the top results is this thread. This makes me believe that this site is not legit at all. Closing...
