### ISSUE TITLE
Facebook - no found stream

### ISSUE THREAD

**Issue by erwanlenagard** [streamlink/streamlink#3292]
Hello,

I think the Facebook plugin is broken. I'm not able to download any video from posts for few days.

### Reproduction steps / Explicit stream URLs to test

streamlink -o test.mp4 https://www.facebook.com/franceinfo/videos/700550637220022 720p

### Log output

[cli][info] Found matching plugin facebook for URL https://www.facebook.com/franceinfo/videos/700550637220022
error: No playable streams found on this URL: https://www.facebook.com/franceinfo/videos/700550637220022

Am I missing something ?

**Comment by bastimeyer** [comment]
Duplicate of #3271
Fixed by #3272
