### ISSUE TITLE
[Twitch] Make it possible to acquire and redeem channel points

### ISSUE THREAD

**Issue by txtsd** [streamlink/streamlink#3297]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

When watching streams on twitch, it is possible to passively earn channel points on channels that have them enabled. Additionally, there are extra channel points that are redeemable by clicking a button that appears occasionally.

### Expected / Actual behavior
Currently, when watching streams via streamlink, no channel points are acquired even if the stream page is open with the video on it paused.
I'd like for streamlink itself to do the redeeming, both for the passive channel points and the clickable ones.

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We removed the ability to log in due to issues it was creating so you won't be able to earn channel points via Streamlink (same with being unable to view private streams, etc). This feature is out of scope.

**Comment by txtsd** [comment]
Can you link me to discussions about the login issues?

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851

**Comment by txtsd** [comment]
Thanks. It's unfortunate. I'll just have to make my own tool to grab channel points.
