### ISSUE TITLE
How download all segments not concat ？

### ISSUE THREAD

**Issue by nonoandre** [streamlink/streamlink#3298]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.

### Description

I want download all original segments files from a m3u8 file，and save as many ts files as 1.ts, 2.ts, 3.ts……  not concat，how should i do？ Thanks !

### Additional comments, etc.
Thanks !

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/3154#issuecomment-688296077
