### ISSUE TITLE
problem playing twitch streams

### ISSUE THREAD

**Issue by Caeliiaa** [streamlink/streamlink#3302]
Hello,

I am using streamlink on windows, and until now it was working correctly, but for a while now when I use the added command --twitch-disable-ads, the direct reproduction through vlc stops or stops playing.

I don't know why, but this is what I found while playing a stream:
> C:\Users\******>streamlink --twitch-low-latency --twitch-disable-ads --loglevel debug twitch.tv/rubius 720p60
> [cli][debug] OS: Windows 10
> [cli][debug] Python: 3.6.6
> [cli][debug] Streamlink: 1.7.0
> [cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
> [cli][info] Found matching plugin twitch for URL twitch.tv/rubius
> [cli][debug] Plugin specific arguments:
> [cli][debug] --twitch-disable-ads=True (disable_ads)
> [cli][debug] --twitch-low-latency=True (low_latency)
> [plugin.twitch][debug] Getting live HLS streams for rubius
> [utils.l10n][debug] Language code: es_CO
> [cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
> [cli][info] Opening stream: 720p60 (hls)
> [plugin.twitch][info] Will skip ad segments
> [plugin.twitch][info] Low latency streaming (HLS live edge: 2)
> [stream.hls][debug] Reloading playlist
> [stream.hls][debug] First Sequence: 3538; Last Sequence: 3546
> [stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3545; End Sequence: None
> [stream.hls][debug] Adding segment 3545 to queue
> [cli][debug] Pre-buffering 8192 bytes
> [stream.hls][debug] Adding segment 3546 to queue
> [cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
> [cli.output][debug] Opening subprocess: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --input-title-format twitch.tv/rubius -
> [cli][debug] Writing stream to output
> [stream.hls][debug] Download of segment 3545 complete
> [stream.hls][debug] Reloading playlist
> [stream.hls][debug] Adding segment 3547 to queue
>
>
>
> (a lot of code afterwards with nothing relevant)
>
>
>
> [stream.hls][debug] Download of segment 4094 complete
> [stream.hls][debug] Reloading playlist
> [stream.hls][debug] Adding segment 4096 to queue
> [stream.hls][debug] Download of segment 4095 complete
> [stream.hls][debug] Reloading playlist
> Exception in thread Thread-TwitchHLSStreamWriter:
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 436, in _error_catcher
> yield
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 766, in read_chunked
> chunk = self._handle_chunk(amt)
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 710, in _handle_chunk
> value = self._fp._safe_read(amt)
> File "http\client.py", line 612, in _safe_read
> File "socket.py", line 586, in readinto
> File "ssl.py", line 1009, in recv_into
> File "ssl.py", line 871, in read
> File "ssl.py", line 631, in read
> socket.timeout: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 751, in generate
> for chunk in self.raw.stream(chunk_size, decode_content=True):
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 571, in stream
> for line in self.read_chunked(amt, decode_content=decode_content):
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 792, in read_chunked
> self._original_response.close()
> File "contextlib.py", line 99, in exit
> File "C:\Program Files (x86)\Streamlink\pkgs\urllib3\response.py", line 441, in _error_catcher
> raise ReadTimeoutError(self._pool, None, "Read timed out.")
> urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='video-edge-7ea530.mia02.abs.hls.ttvnw.net', port=443): Read timed out.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "threading.py", line 916, in _bootstrap_inner
> File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 190, in run
> self.write(segment, result)
> File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls_filtered.py", line 17, in write
> return super(FilteredHLSStreamWriter, self).write(sequence, *args, **kwargs)
> File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 160, in write
> for chunk in res.iter_content(chunk_size):
> File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 758, in generate
> raise ConnectionError(e)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-7ea530.mia02.abs.hls.ttvnw.net', port=443): Read timed out.
> 
> [stream.hls][debug] Adding segment 4097 to queue
> [stream.hls][debug] Adding segment 4098 to queue
> [stream.hls][debug] Adding segment 4099 to queue
> [stream.hls][debug] Adding segment 4100 to queue

any idea what happens? ;u

**Comment by gravyboat** [comment]
There is nothing we can do about this. It's a problem with the connection between you and that edge server you're trying to get data from.

**Comment by Terra-B-Welch** [comment]
This wouldn't happen to be related to the recent change twitch made in order to counter adblockers would it?

**Comment by gravyboat** [comment]
@Terra-B-Welch While it may be due to the ad segments that's not the root cause of the problem. I'm running identical options using MPV with no issue which is why I suggested trying a different player.

**Comment by Caeliiaa** [comment]
ok, i tried the suggestion to switch video player, and it worked.

I have used mpv as a player, and so far it has worked perfectly compared to the performance of vlc, I don't know if it will be a problem with my connection or with vlc, but with mpv at the same quality it works very well ^^^.

**Comment by bastimeyer** [comment]
As you can see in the log output, there's a timeout while downloading an HLS segment. This isn't even an ad segment, so the `--twitch-disable-ads` parameter is completely unrelated to that. It is also completely unrelated to the used player, as the player consumes Streamlink's output (unless certain other parameters are used, which is not the case here) and has nothing to do with the HLS stream.

I am not sure why there's an uncaught exception though. A timeout should usually be caughed and handled properly, either with attempts of re-downloading that segment, or with a regular process termination and proper logging.

- https://github.com/streamlink/streamlink/blob/f2cd9e854f37b75eb3619072354aa18dae5f6316/src/streamlink/stream/hls.py#L124-L130
- https://github.com/streamlink/streamlink/blob/f2cd9e854f37b75eb3619072354aa18dae5f6316/src/streamlink/plugin/api/http_session.py#L161-L183
