### ISSUE TITLE
Bug with --can-handle-url

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#331]
For example if we use:
Streamlink.exe --can-handle-url "http://ThisLinkMagic.hahaha/TEST" 
The program tries to HEAD the url, i think with --can-handle-url the only thing the program must do is check if the url matches with an associated plugin regex, with current method a long latency can be produced by waiting for HEAD task on a non-streamlink compatible url, what is really painfull in external excripting.
I mean for example i have a program that check if a URL is compatible with Streamlink, if not the link is played directly with a player, if HEAD for non-compatible urls is removed, the waiting will be really lower.
Edit: HEAD can be usefull in redirect cases, like this: http://cor.to/1RVk (that redirects to vaughnlive)
But i think this a really less common used way to enter urls, also an alternative parameter like --can-handle-url-nohead can be really cool if preserve of head function is wanted.

**Comment by RosadinTV** [comment]
I fixed this, soon i'll post a PR

**Comment by gravyboat** [comment]
Do you want to get this into the main repo? Right now it's just in the portable repo.
