### ISSUE TITLE
Streaming www.huya.com/kpl results in only one frozen frame

### ISSUE THREAD

**Issue by RasmusJohns** [streamlink/streamlink#3317]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description

Last week, using streamlink on huya.com/kpl was not an issue. However, since last night is has not been working for me on any machine. The stream launches, but does not seem to generate any new frames -- it is simply stuck showing a rather old frame.

Logs suggest packages are not sent (if I understand TS discontinuity correctly), but running the stream in the browser works fine for me.

### Expected / Actual behavior

Should generate a videostream with valid frames

### Reproduction steps / Explicit stream URLs to test

run `streamlink https://www.huya.com/kpl best`

### Log output

Here are two logs: one using `--verbose` and one using `--loglevel debug`

```
 % streamlink --verbose https://www.huya.com/kpl best
[cli][info] Found matching plugin huya for URL https://www.huya.com/kpl
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
VLC media player 3.0.10 Vetinari (revision 3.0.10-0-g7f145afa84)
[00007ffd0d104950] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007ffd122495e0] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007ffd1211eea0] mpeg4audio packetizer: AAC channels: 1 samplerate: 22050
[00007ffd122495e0] videotoolbox decoder: Using Video Toolbox to decode 'h264'
[00007ffd122495e0] videotoolbox decoder: vt cvpx chroma: 420v
[00007ffd0bdee710] ts demux error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 17
[00007ffd0bdee710] ts demux error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 17
[00007ffd0bdee710] ts demux error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 17
[00007ffd0bdee710] ts demux error: libdvbpsi error (PSI decoder): TS discontinuity (received 0, expected 4) for PID 17
...
```

```
% streamlink --loglevel debug https://www.huya.com/kpl best
[cli][debug] OS:         macOS 10.15.5
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 1.5.0
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin huya for URL https://www.huya.com/kpl
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1604432444; Last Sequence: 1604432448
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1604432446; End Sequence: None
[stream.hls][debug] Adding segment 1604432446 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1604432447 to queue
[stream.hls][debug] Adding segment 1604432448 to queue
[stream.hls][debug] Download of segment 1604432446 complete
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[cli.output][debug] Opening subprocess: /Applications/VLC.app/Contents/MacOS/VLC --input-title-format https://www.huya.com/kpl -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1604432447 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1604432449 to queue
[stream.hls][debug] Adding segment 1604432450 to queue
[stream.hls][debug] Download of segment 1604432448 complete
[stream.hls][debug] Download of segment 1604432449 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 1604432450 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1604432451 to queue
...
```

### Additional comments, etc.

Thanks for an overall awesome tool.

**Comment by stefan327** [comment]
> The stream launches, but does not seem to generate any new frames -- it is simply stuck showing a rather old frame.

I can confirm this. The same for me since a few days.

**Comment by back-to** [comment]
@RasmusJohns @stefan327 
could you test if this works stable enough

https://gist.githubusercontent.com/back-to/175fc4fc7599a953da56243c0a80187a/raw/631958968b0ac8a64cc38b921ad3119662b1095e/huya.py

**Comment by stefan327** [comment]
@back-to 

I have tested with several streams. Unfortunately it does not work for me. 

The streams all hang after 3..4 seconds. I guess the working part are the segments of the first playlist. If i save the streams, then further segments are appended.  But the content is corrupted after 3..4 seconds (tested with ffmpeg).

Maybe it helps if we adjust parameters ... timeout, attempt count and so on (streamlinkrc)?!

**Comment by back-to** [comment]
@stefan327 

could you also try

https://gist.githubusercontent.com/back-to/175fc4fc7599a953da56243c0a80187a/raw/018366e57a2fdbb4a0b2ef48b122f719f52aa92f/huya.py

**Comment by stefan327** [comment]
@back-to 

Thanks for your effort. Unfortunately it does not work with this either.

**Comment by back-to** [comment]
@stefan327 

I changed the **stream type** and added more **mirrors**,
the huya server seems unstable for some user regions.

you can try different mirros now, maybe one will work.

https://raw.githubusercontent.com/streamlink/streamlink/c4e42d96bc5aa718b695e141bfa9c7a615d7ae32/src/streamlink/plugins/huya.py

```
$ streamlink https://www.huya.com/kpl
[cli][info] Found matching plugin huya for URL https://www.huya.com/kpl
[cli][info] Available streams: source_al13, source_al (worst), source_tx, source_bd, source_tx15 (best)
[cli][info] Opening stream: source_tx15 (http)

$ streamlink https://www.huya.com/longdd
[cli][info] Found matching plugin huya for URL https://www.huya.com/longdd
[cli][info] Available streams: source_al, source_bd, source_tx (worst, best)
[cli][info] Opening stream: source_tx (http)
```

**Comment by RasmusJohns** [comment]
@back-to I can confirm that your fix works!
