### ISSUE TITLE
Youtube Live - Could not find a video on this page for Euronews DE Channel

### ISSUE THREAD

**Issue by chpasha** [streamlink/streamlink#3320]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.

### Description
Since a week or so, I cannot grab a live stream video from euronews germany youtube channel anymore. Tried all url combinations I know (see below). The links when pasted in browser DO work. The youtube plugin also DOES work for any other live channel videos I tried INCLUDING euronews russia.  

### Reproduction steps / Explicit stream URLs to test
```
/usr/local/bin/streamlink --loglevel debug --http-no-ssl-verify https://www.youtube.com/channel/UCACdxU3VrJIJc7ujxtHWs1w/live --stdout
[cli][debug] OS:         Linux-5.9.0-arm-64-aarch64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCACdxU3VrJIJc7ujxtHWs1w/live
error: Could not find a video on this page
```

```
/usr/local/bin/streamlink --loglevel debug --http-no-ssl-verify https://www.youtube.com/watch?v=h85l-AZmeNY --stdout
[cli][debug] OS:         Linux-5.9.0-arm-64-aarch64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=h85l-AZmeNY
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: h85l-AZmeNY
[plugin.youtube][debug] get_video_info - 1: Video unavailable
[plugin.youtube][debug] get_video_info - 2: Video unavailable
[plugin.youtube][debug] get_video_info - 3: Video unavailable
error: No playable streams found on this URL: https://www.youtube.com/watch?v=h85l-AZmeNY
```

```
/usr/local/bin/streamlink --loglevel debug --http-no-ssl-verify https://www.youtube.com/embed/live_stream?channel=UCACdxU3VrJIJc7ujxtHWs1w --stdout
[cli][debug] OS:         Linux-5.9.0-arm-64-aarch64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/embed/live_stream?channel=UCACdxU3VrJIJc7ujxtHWs1w
error: Could not find a video on this page
```

I also tried the youtube plugin from master branch (just replaced the one in distro folder - maybe that is not enough though) without success.

**Comment by back-to** [comment]
it is not an issue with streamlink

```
$ streamlink https://www.youtube.com/channel/UCACdxU3VrJIJc7ujxtHWs1w/live -l info
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCACdxU3VrJIJc7ujxtHWs1w/live
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
```

**Comment by chpasha** [comment]
that is true, something must have been wrong with my vpn provider - the funny thing is that other channels did work and I also tried to reconnect to different endpoints multiple times. Maybe Euronews Germany has some geo restrictions and falsely detects my IP as some that is not eligible for live content (in spite of connection to german server). Sorry for bothering :(

**Comment by Robby-** [comment]
I'm encountering this exact issue with a live stream as I'm typing this. So, this most certainly *is* an issue with Streamlink. YouTube must have changed something on their end I guess.
This issue occurs when using this style of URL: `https://www.youtube.com/channel/<channelid>/live`.
It does however work when using this style of URL: `https://www.youtube.com/embed/live_stream?channel=<channelid>`

**Comment by gravyboat** [comment]
@Robby- run with `-l debug` and provide some debug logging if you're encountering this please. That is the same URL scheme that worked perfectly fine a few weeks ago.

**Comment by ErAzOr2k** [comment]
https://www.youtube.com/user/<channelid>/live doesn't also work since a few days

**Comment by gravyboat** [comment]
A PR has been merged that will fix this. You can manually update the plugin from the master branch, wait for the nightly build, or wait for the next release.
