### ISSUE TITLE
streamlink.exceptions.NoPluginError

### ISSUE THREAD

**Issue by wang19951120** [streamlink/streamlink#3321]
hello,I want to use the streamlink library to write an exe software。

    My code is as follows：

`import streamlink`
`streams = streamlink.streams("https://www.youtube.com/watch?v=63RmMXCd_bQ")`
`print(streams)`

Then I packaged through pyinstaller.Everything went well, but appeared during execution
![image](https://user-images.githubusercontent.com/36093522/98287229-0875b800-1fe0-11eb-97e1-fcda265197d6.png)
Why does this error occur and how to solve it

**Comment by back-to** [comment]
> @wang19951120 
Then I packaged through pyinstaller. Everything went well, but appeared during execution

well `pyinstaller` there is your issue, this won't work with streamlink.

https://github.com/streamlink/streamlink/issues/669#issuecomment-441469413
