### ISSUE TITLE
Installer incompatible with Windows 7

### ISSUE THREAD

**Issue by gallegoz** [streamlink/streamlink#3323]
Tried latest development build (streamlink-1.7.0_52.gf0b35b6-win32), issue is installer doesn't add the path environment variable. latest stable (1.7.0) adds it without a problem.

second issue is python 3.9+ does not work on Windows 7 anymore. 3.8 branch still works on Windows 7, maybe using 3.8.6 instead of 3.9 would be better? or at least specify in docs that streamlink windows installer won't work on Win7 anymore.
But is 3.9 really needed?

**Comment by gravyboat** [comment]
I haven't tested the latest development build so I can't speak to the path environment variable issue but this is the first I've heard of it.

In regards to the second portion we're not going to use Python 3.8.6. Windows 7 is EoL as of January 14th 2020, if Microsoft is done supporting it we're definitely done supporting it. It would be irresponsible of us to continue supporting an operating system that isn't getting security patches.

**Comment by bastimeyer** [comment]
It's possible that something broke in #3312, which bumped NSIS to 3. I will take a look at this later once I've finished some other stuff.

Is `streamlink-1.7.0_34.gf2cd9e8-win32` from the previous commit working on your system?
https://github.com/streamlink/streamlink/actions/runs/336849507

Regarding Python 3.9 and Windows 7, as @gravyboat already said, if your OS is unsupported, then it's not our problem and I don't see any reason for downgrading the installer's Python version. The next release will be a major version bump, which means we're removing deprecated and unsupported stuff, and if Python 3.9 happens to not support Windows 7, so be it. Either upgrade/switch your OS or install Streamlink via Python 3.8 by using pip in a separate Python environment.

**Comment by skulblakka** [comment]
I also just tested it. After running the current installer streamlink is not found in path and directly running the program does also not work (as expected with the incompatibility with Python 3.9 and Windows 7). The same installer works fine on Windows 10 and streamlink is added to the path. 

The previous installer linked by @bastimeyer works fine on Windows 7.

**Comment by bastimeyer** [comment]
The reason why it's not working correctly on W7 is the way `pynsist` adds/removes the `PATH` env var entry. It needs to run an included python script for this and it uses the bundled python version. Since py39 is incompatible with W7, adding/removing the `PATH` env var entry won't work.
- https://github.com/takluyver/pynsist/blob/2.6/nsist/pyapp.nsi#L115-L128
- https://github.com/streamlink/streamlink/blob/f0b35b64d4b070c29d6ac3e30fc565a71bb9508a/script/makeinstaller.sh#L249-L255

This is however a non-issue, as you won't be able to run Streamlink via Python 3.9 on W7 anyway.

If somebody wants to add a line to the install docs that the installer won't work on W7 anymore, please go ahead, otherwise I'll open a PR myself later today.

**Comment by bobvargas** [comment]
@bastimeyer  how do you install streamlink via pip on python 3.8? Since the newer nightly builds of streamlink uses python 3.9 in which windows 7 doesn't support. Plus I'm on windows 7.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/install.html#pypi-package-and-source-code

**Comment by bobvargas** [comment]
thx

**Comment by gallegoz** [comment]
ok, whatever, if you say so. thanks for responding and investigating.
using 3.8 for a while wouldn't hurt anybody, you still used 3.6 when 3.7 and 3.8 was around after all. but whatever.

**Comment by Vangelis66** [comment]
> using 3.8 for a while wouldn't hurt anybody, you still used **3.6** 
> when **3.7** and **3.8** was around after all

+1 ...
FWIW, the jump from **py3.6.6** to **py3.9** in the installer also EOLs Vista SP2...
Vista SP2 EOL: py3.7.9
Win7 SP1 EOL: py3.8.6

**Comment by gravyboat** [comment]
@gallegoz It hurts us as it makes maintenance more annoying and then we have to do another full dot release when we EoL another version of Python which is extra unpaid work.

@Vangelis66 Vista was EOL'd in 2017. The fact it was supported at all was pure luck. Again, we are not supporting EoL operating systems. If you're still using Vista that's your choice but we're not going to enable people to continue running systems which are security vulnerabilities.

I'm not sure why people are expecting us to freely support these old operating systems when the billion dollar company that made them isn't doing so. If people want to go down that road they can fork Streamlink and keep maintaining but we will not do so.

@bastimeyer I've opened a PR with proposed language, let me know what you think.

**Comment by gallegoz** [comment]
ok calm down nobody pays you we get it. you can't wait for py3.9 to mature when you passed two major versions when it wouldn't actually had a huge effect like this but now it's a matter of life or death. ok whatever.

**Comment by beardypig** [comment]
While I do not think we should be supporting older versions of Windows (the maintenance burden would be extraordinary), I do think we should be supporting the oldest version of Python official released on Windows by PSF. 

I think it makes sense to use the latest maintenance versions of earliest officially supported version of Python (3.8.6 at the time of writing), 3.7 is in the security-fix only release cycle and will only continue with source releases so should not be supported on Windows. We would switch to 3.9 when 3.8 enters the security-fix only release cycle.  

This would mean that Windows 7 would be compatible until 3.8 is no longer in the maintenance/bugfix release cycle. But I'm afraid the boat has sailed on Windows Vista, you can still use pip to install `streamlink` though. 

It should be made clear that we **only support** Windows 10, if it works on an older version that is just a happy coincide.

**Comment by WolfganP** [comment]
Probably the best way to move forward is list/announce/note in the readme the last streamlink version compatible with Windows 7, Vista, and the like, like other apps do.
Whoever runs an old and unsupported operating system (for whatever reason), also needs to accept that apps may become obsolete and unsupported as well.
