### ISSUE TITLE
Modern fmp4 HLS Incompatibility

### ISSUE THREAD

**Issue by gabbyendo** [streamlink/streamlink#3328]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.

### Description
Streamlink is unable to playback modern fmp4 HLS playlists referenced from a master playlist because it doesn't load the initialization mp4 specified on the `#EXT-X-MAP:URI="init_0.mp4"` line. This support was introduced several years ago and seems to be the only type of HLS container Apple is moving forward with. The tested HLS stream works in VLC, videojs, hls.js, and mpv, but fails in streamlink.

### Expected / Actual behavior

I expected HLS support. The documentation could also be improved with specification of what version of HLS is supported by streamlink, although fmp4 HLS is some years old now.

### Reproduction steps / Explicit stream URLs to test

1. Generate an fmp4 HLS playlist with a master playlist with ffmpeg. The key option is `-hls_segment_type fmp4` to generate the fmp4 playlist, and `-master_playlist_name` to make a master playlist for it.
2. Try to load the stream with streamlink
3. Observe the logged failure indicating the init.mp4 wasn't loaded first. Manual inspection of the playlist file shows the `#EXT-X-MAP:URI="init_0.mp4"` is correctly set, the file exists, and the playlist works in VLC, videojs, hls.js, and mpv.

### Log output

```
[cli][debug] OS:         Linux-5.8.18-gentoo-x86_64-Intel-R-_Core-TM-_i7-8750H_CPU_@_2.20GHz-with-gentoo-2.7
[cli][debug] Python:     3.7.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://streamurl.net/hls/stream.m3u8
[plugin.hls][debug] URL=https://streamurl.net/hls/stream.m3u8; params={}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 720p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 35; Last Sequence: 40
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 38; End Sequence: None
[stream.hls][debug] Adding segment 38 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 39 to queue
[stream.hls][debug] Adding segment 40 to queue
[cli][info] Starting player: mpv --cache=yes --demuxer-max-bytes=2048k
[stream.hls][debug] Download of segment 38 complete
[cli.output][debug] Opening subprocess: mpv --cache=yes --demuxer-max-bytes=2048k --title=https://streamurl.net/hls/stream.m3u8 -
[stream.hls][debug] Download of segment 39 complete
[file] Reading from stdin...
[cli][debug] Writing stream to output
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 1
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 2
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding trex (id 1)
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 0
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: trun track id unknown, no tfhd was found
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 1
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 2
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding trex (id 1)
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 0
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: trun track id unknown, no tfhd was found
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[lavf] avformat_open_input() failed
Failed to recognize file format.

Exiting... (Errors when loading file)
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Download of segment 40 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Additional comments, etc.
I have no problem getting the exact same playlist generation command in ffmpeg working in streamlink if I remove `-hls_segment_type fmp4` to generate the older mpegts playlists, but I'd like to move to fmp4 for the lower overhead and new codec support Apple is specifying for it.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
It should be relatively straightforward to add basic support for this type of HLS playlist, there are some extra features added alongside it that would require more work.

**Comment by GBeauregard** [comment]
You can use ffmpeg's DASH muxer to generate HLS playlists that aren't supported as well (this is an option because it can be done in a way that the HLS/DASH playlists use the same files).
