### ISSUE TITLE
Mixing separate video and audio stream possibility

### ISSUE THREAD

**Issue by myhobby2** [streamlink/streamlink#3337]
## Feature Request

Create parameters to Mix an external legal audio stream to a video stream

### Description

I'm using streamlink to stream live youtube webcams to my TV. If there is already sound included, it is most of the time not very interesting. Why not add an audio source that is interesting (local audio stream like a radio station).

### Expected / Actual behavior

#NAME Streamlinkserver/YouTube
#SERVICE 5002:0:1:1:0:0:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//youtu.be/2uznaTjvb7I < :http://audiostream >
#DESCRIPTION Live Webcam Saint-Malo

Add an additional parameter to the SERVICE5002 for the audio stream and overrule the existing audio embedded in the video stream by merging the audio source in streamlink so it is presented at the same time with the video

### Additional comments, etc.

None

**Comment by beardypig** [comment]
Looks like you are using some other piece of software... I have no idea what `SERVICE5002` is. This feature should be added to that piece of software because it is out of scope for Streamlink.
