### ISSUE TITLE
plugins.twitch: switch access token API request to GQL

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3341]
As mentioned in #3210, Twitch has begun switching the access token requests on their website to their GQL API a few weeks ago. The transition seems to have been completed by them and no API requests on their old and private `api.twitch.tv/api` API namespace are being made anymore on their website.

Since the old API is still available, the Twitch plugin is still working fine, but once it gets shut down, which can be any time now, it'll break completely. This means we'll have to switch to the GQL API eventually.

I've opened this thread, so this can be monitored and documented, in case Twitch makes further changes.

----

There seem to be two GQL request methods available for the access token acquirement and both return the same response:

1. `PlaybackAccessToken` with the persistedQuery extension (which is a static sha256 of the request, so their servers can use caching when requests are more complicated - variables don't affect the hash):

   ```json
   {
     "operationName": "PlaybackAccessToken",
     "variables": {
       "isLive": true,
       "login": "**CHANNELNAME**",
       "isVod": false,
       "vodID": "",
       "playerType": "site"
     },
     "extensions": {
       "persistedQuery": {
         "version": 1,
         "sha256Hash": "0828119ded1c13477966434e15800ff57ddacf13ba1911c129dc2200705b0712"
       }
     }
   }
   ```

2. `PlaybackAccessToken_Template`

   ```json
   {
     "operationName": "PlaybackAccessToken_Template",
     "query": "query PlaybackAccessToken_Template($login: String!, $isLive: Boolean!, $vodID: ID!, $isVod: Boolean!, $playerType: String!) {  streamPlaybackAccessToken(channelName: $login, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isLive) {    value    signature    __typename  }  videoPlaybackAccessToken(id: $vodID, params: {platform: \"web\", playerBackend: \"mediaplayer\", playerType: $playerType}) @include(if: $isVod) {    value    signature    __typename  }}",
     "variables": {
       "isLive": true,
       "login": "**CHANNELNAME**",
       "isVod": false,
       "vodID": "",
       "playerType": "site"
     }
   }
   ```

Response:

```json
{
  "data": {
    "streamPlaybackAccessToken": {
      "value": "**access-token-string**", 
      "signature": "**signature-string**",
      "__typename": "PlaybackAccessToken"
    }
  },
  "extensions": {
    "durationMilliseconds": 63,
    "operationName": "PlaybackAccessToken",
    "requestID": "**some-random-ID**"
  }
}
```

**Comment by gravyboat** [comment]
@bastimeyer Just to address your comment from the other thread. I don't think we should rely on any API endpoint until it's stable. They may also change the naming of the query or the variables which would mean extra work without any benefit. I also have concerns over the fact that it's not actually public. I don't know if this is an error on Twitch's end, or if they aren't updating the documentation.

**Comment by bastimeyer** [comment]
The reason why I thought that they had made changes is that I wasn't aware that there are two methods for requesting the access token. Both are essentially the same (no idea though why they would keep the "template" request) and since they've fully rolled out the changes globally now, there is not reason to think that it's "unstable". Apart from that, the access token requests have never been public API requests and thus never been documented or considered "stable".

I will open a PR for this now, but if you want to wait with merging, I'm fine with that, because the old API endpoint is still working. Just remember that it can be shut down at any time.

Just in case that it'll be shut down, the 2.0.0 release should be pretty much ready with the essential changes, so at least that's nothing we have to worry about.

**Comment by gravyboat** [comment]
Yeah I've never seen a template request like that in any GraphQL setup I've seen so I'm not sure either. Maybe they have some sort of internal templating system to make resolver changes easier? I don't know. Let's merge for now, we can update again if needed.
