### ISSUE TITLE
Queue Stream in VLC Playlist

### ISSUE THREAD

**Issue by EntranceJew** [streamlink/streamlink#3345]
## Feature Request
- [x] This is a feature request and I have read the contribution guidelines.

### Description
I attempted to queue the result of streamlink in VLC rather than have it create or assume control over an existing instance and I'm finding that it may not be possible at present.

### Expected / Actual behavior
I attempted to use streamlink to pipe a twitch stream directly to VLC, which I usually have open and running already, but instead it opens a new VLC instance with a media item named `fd://0`. I attempted to manually add/move that to the existing and already running VLC instance and it did not work. I also attempted to pass the command line arguments that one would typically use to queue something in VLC:
```
streamlink "https://www.twitch.tv/rifftrax" 720p -a "--one-instance --playlist-enqueue" --player-no-close
```
But this didn't work, I also tried this:
```
streamlink https://www.twitch.tv/rifftrax 720p -a "--one-instance --playlist-enqueue {filename}" --player-no-close
```
This time it does add the item to VLC's queue but because streamlink is no longer running it isn't there to serve data when the playlist eventually gets to it. I also tried:
```
M:\media> streamlink https://www.twitch.tv/rifftrax 720p -a "--one-instance {filename}" --player-no-close
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/rifftrax
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
error: Failed to start player: "C:\Program Files\VideoLAN\VLC\vlc.exe" (Process exited prematurely)
[cli][info] Closing currently open stream...
M:\media>
```
Which I expected to just assume control of my existing instance like when you set something to play instantly (add it to the end of the playlist and play it immediately) but still it had problems. I tried a different approach by running output to a file:
```
streamlink https://www.twitch.tv/rifftrax 720p -o rifftrax.ts
```
And then I queued it into VLC manually (although this could be automated I'm sure) and it worked to some extent but after VLC caught up with the stream it reset to the beginning of the entire file which isn't the most ideal situation.

It's possible that there's some fancy incantation I can do to broadcast from one VLC instance to the other but I'm hoping that either I'm missing something here or that there's a better way to go about this.

### Additional comments, etc.
Love the work, appreciate the software.

**Comment by back-to** [comment]
you could do it with this

` --player-external-http --player-external-http-port 33333`

https://streamlink.github.io/latest/cli.html#cmdoption-player-external-http
https://streamlink.github.io/latest/cli.html#cmdoption-player-external-http-port
