### ISSUE TITLE
Help install streamlink on fedora

### ISSUE THREAD

**Issue by Koisell** [streamlink/streamlink#335]
I just discover and install streamlink on my fedora 25(I used livestreamer before).
Because pip didn't directly work, I put here instruction for fedora users.

For the installation on a fedora OS you need to install the python-devel package before ;)
$ sudo dnf install python-devel
$ sudo pip install -U streamlink

I see their is a package project in WIP: #262 
If I can give my help :)

**Comment by Koisell** [comment]
I just see that a guy melmorabity make a build in the fedora Copr. I uninstall streamlink with pip and re install it using:
$ sudo dnf copr enable melmorabity/streamlink
$ sudo dnf install streamlink

It works fine.
So if your using fedora  23, 24, 25 I recommand you this way.
But the way explained above should work on fedora, CentOS and REHL (replace dnf by yum).

**Comment by beardypig** [comment]
Strange that `pip` is installed without `python-devel`, on debian `pip` depends on `python-dev` :-)

**Comment by Koisell** [comment]
pip is installed by default on fedora ;)

**Comment by melmorabity** [comment]
I submitted streamlink for inclusion in Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1405271

**Comment by gravyboat** [comment]
I'm going to close this out since it's resolved.
