### ISSUE TITLE
Please support plugin Mtv.com

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#336]
Hey guys I wanted to watch my favorite tv shows on mtv via Vlc. Can you make a plugin to support mtv.com to use on future version of streamlink thanks.

**Comment by gravyboat** [comment]
Is there a URL where you would currently stream MTV content?

**Comment by bobvargas** [comment]
@gravyboat yes like http://www.mtv.com/full-episodes/8xqewl/true-life-i-have-misophonia-season-22-ep-misphon

**Comment by beardypig** [comment]
Looks like you need a cable subscription to get that series? The conent is likely protected by DRM as well as requiring a cable subscription login, which means it probably not something we'd be able to support. If there is other free content on MTV we can take a look at that if you can provide a URL :-)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/1656
