### ISSUE TITLE
Shared resolution streams undetected by dash plugin

### ISSUE THREAD

**Issue by GBeauregard** [streamlink/streamlink#3365]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.
confirmed in master

### Description

When multiple DASH entries share a resolution (w/o extra metadata to distinguish?), streamlink won't be able to play the highest quality/highest bitrate stream because it doesn't list it.

### Expected / Actual behavior
Streamlink to play the highest bitrate/highest quality stream

### Reproduction steps / Explicit stream URLs to test
Generate a dash playlist with ffmpeg's dash muxer (may need to use master, there's been some changes with the dash muxer) with two different bitrates encoded at the same resolution. The ffmpeg dash muxer was contributed by those invested in the dash forum so it's all up to spec. Try to play the "best" quality with streamlink, you'll note it will play the lower quality of the two bitrates in the dash muxer playlist and the dash plugin will only list one stream at the given resolution, preventing playing high quality stream. If there's a way to workaround this bug in streamlink by adding metadata in ffmpeg I haven't discovered it yet, but I'll update if I do.

### Log output

Here's an example of a stream being loaded where manual inspection of the mpd shows there's two streams at 800p. Note one is listed, and the one that gets loaded is the lower quality of the two. This is relevant not just for multiple bitrates at the same resolution, but situations where you transcode from e.g. HEVC into H264 for varying platform support.

```
❯ ~/.scripts/loadstream.sh
[cli][debug] OS:         Linux-5.8.18-gentoo-x86_64-Intel-R-_Core-TM-_i7-8750H_CPU_@_2.20GHz-with-gentoo-2.7
[cli][debug] Python:     3.7.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dash for URL https://example.com/stream/stream.mpd
[plugin.dash][debug] Parsing MPD URL: https://example.com/stream/stream.mpd
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[cli][info] Available streams: 212p (worst), 320p, 426p, 532p, 746p, 800p (best)
[cli][info] Opening stream: 800p (dash)
```

**Comment by beardypig** [comment]
Any chance you could post an minimal example MPD?

**Comment by GBeauregard** [comment]
> Any chance you could post an minimal example MPD?

https://stream.gably.net/example/stream.mpd

**Comment by back-to** [comment]
it's an issue because a `dict` is used without the `_alt` stuff like in hlsstream

https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/hls.py#L493-L506

---

a list could also fix it

```diff
diff --git a/src/streamlink/stream/dash.py b/src/streamlink/stream/dash.py
index 6f8e1c26..51bf7fa7 100644
--- a/src/streamlink/stream/dash.py
+++ b/src/streamlink/stream/dash.py
@@ -174,7 +174,7 @@ class DASHStream(Stream):
         :param url_or_manifest: URL of the manifest file or an XML manifest string
         :return: a dict of name -> DASHStream instances
         """
-        ret = {}
+        ret = []
 
         if url_or_manifest.startswith('<?xml'):
             mpd = MPD(parse_xml(url_or_manifest, ignore_ns=True))
@@ -241,7 +241,9 @@ class DASHStream(Stream):
                 stream_name.append("{:0.0f}{}".format(vid.height or vid.bandwidth_rounded, "p" if vid.height else "k"))
             if audio and len(audio) > 1:
                 stream_name.append("a{:0.0f}k".format(aud.bandwidth))
-            ret['+'.join(stream_name)] = stream
+            ret.append(('+'.join(stream_name), stream))
+
+        print(f'ret: {ret!r}')
         return ret
 
     def open(self):
```

```
ret: [('804p', <Stream()>), ('804p', <Stream()>), ('750p', <Stream()>), ('536p', <Stream()>), ('428p', <Stream()>), ('322p', <Stream()>), ('214p', <Stream()>)]
[cli][info] Available streams: 214p (worst), 322p, 428p, 536p, 750p, 804p_alt, 804p (best)
```

**Comment by GBeauregard** [comment]
> it's an issue because a `dict` is used without the `_alt` stuff like in hlsstream
> 
> https://github.com/streamlink/streamlink/blob/master/src/streamlink/stream/hls.py#L493-L506
> 
> a list could also fix it
> 
> ```diff
> diff --git a/src/streamlink/stream/dash.py b/src/streamlink/stream/dash.py
> index 6f8e1c26..51bf7fa7 100644
> --- a/src/streamlink/stream/dash.py
> +++ b/src/streamlink/stream/dash.py
> @@ -174,7 +174,7 @@ class DASHStream(Stream):
>          :param url_or_manifest: URL of the manifest file or an XML manifest string
>          :return: a dict of name -> DASHStream instances
>          """
> -        ret = {}
> +        ret = []
>  
>          if url_or_manifest.startswith('<?xml'):
>              mpd = MPD(parse_xml(url_or_manifest, ignore_ns=True))
> @@ -241,7 +241,9 @@ class DASHStream(Stream):
>                  stream_name.append("{:0.0f}{}".format(vid.height or vid.bandwidth_rounded, "p" if vid.height else "k"))
>              if audio and len(audio) > 1:
>                  stream_name.append("a{:0.0f}k".format(aud.bandwidth))
> -            ret['+'.join(stream_name)] = stream
> +            ret.append(('+'.join(stream_name), stream))
> +
> +        print(f'ret: {ret!r}')
>          return ret
>  
>      def open(self):
> ```
> 
> ```
> ret: [('804p', <Stream()>), ('804p', <Stream()>), ('750p', <Stream()>), ('536p', <Stream()>), ('428p', <Stream()>), ('322p', <Stream()>), ('214p', <Stream()>)]
> [cli][info] Available streams: 214p (worst), 322p, 428p, 536p, 750p, 804p_alt, 804p (best)
> ```

Great. My users will be happy about this fix since between this and the fmp4 HLS they weren't able to use streamlink.

**Comment by GBeauregard** [comment]
@back-to  From compiling master I can confirm that appeared to be the issue and it fixes it

**Comment by beardypig** [comment]
@back-to want to PR that change, it looks good to me.
