### ISSUE TITLE
api upload video

### ISSUE THREAD

**Issue by verhaye** [streamlink/streamlink#3367]
How can you upload video to http://tvpot.daum.net I see it's closed at the moment
Can anyone help me with this problem?
I need api automatically uploading this page

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the plugin issue template:
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[1]]
* Other feedback:
* - [x] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[2]] [[3]]
* - [x] Other (see below)
* Other: Streamlink is not a video uploading tool.

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Search all open/closed issues/pull requests][1]
[[2]] [Install the most recent version of Streamlink][2]
[[3]] [Check the master branch for plugin updates][3]

[1]: https://github.com/streamlink/streamlink/issues?q=
[2]: https://streamlink.github.io/install.html
[3]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

**Comment by gravyboat** [comment]
This has nothing to do with Streamlink. Closing.
