### ISSUE TITLE
How do I see request and response headers when I run a streamlink command?

### ISSUE THREAD

**Issue by Abhi-akamai** [streamlink/streamlink#3369]
## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by johnthecracker** [comment]
With any HTTP sniffer. At leas I see it like that.

**Comment by bastimeyer** [comment]
There's currently no generic HTTP-request/response specific logging implemented.
https://github.com/streamlink/streamlink/blob/d1062fc28573a064774567771bee256b975a80de/src/streamlink/plugin/api/http_session.py#L161-L170

If we're going to add logging information here, then it would probably make sense adding another logging level on top of `trace`, but it could also be added to the `trace` level.

For now, you can see the HTTP request parameters and headers that will be used by of some of the resolved streams by using the `--json` parameter.

Or debug the python process and observe the requests yourself and/or set breakpoints at the specific code lines.

----

@johnthecracker This doesn't work well with HTTP over TLS aka HTTPS, as it's E2EE, and you will need the parameters and keys for decrypting the requests and responses, which you usually don't have.

**Comment by mkbloke** [comment]
> @johnthecracker This doesn't work well with HTTP over TLS aka HTTPS, as it's E2EE, and you will need the parameters and keys for decrypting the requests and responses, which you usually don't have.

If you're going that route, [mitmproxy](https://mitmproxy.org/) might be a better solution.

**Comment by Abhi-akamai** [comment]
I was going through my origin logs but couldn't differentiate between a player requests and streamlink requests. Is there any unique param that are being set by Streamlink that would help me identify a streamlink request?

**Comment by mkbloke** [comment]
No.
