### ISSUE TITLE
Support Cookies.txt

### ISSUE THREAD

**Issue by Craeckie** [streamlink/streamlink#3370]
## Feature Request

In order to prevent blocking by Youtube, .. support for a cookie jar would be helpful.

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.

### Description

Youtube-DL supports this and has a class to load&save cookies in the "cookies.txt" format. It's derived from MozillaCookieJar:
https://github.com/ytdl-org/youtube-dl/blob/f9f9699f2fa87ec54d59b1834cc56adb6147fec6/youtube_dl/utils.py#L2739

### Implementation

The initialization is pretty easy:
```
self.cookiejar = YoutubeDLCookieJar(cookie_file_path)
if os.access(cookie_file_path, os.R_OK):
  self.cookiejar.load(ignore_discard=True, ignore_expires=True)
```

In order to add the cookies to a request, just use
`self.cookiejar.add_cookie_header(req)`

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
You can already achieve this with config files and the `--http-cookie` parameter.

1. [`--http-cookie KEY=VALUE`](https://streamlink.github.io/cli.html#cmdoption-http-cookie)
   > A cookie to add to each HTTP request.
   > Can be repeated to add multiple cookies.
2. - https://streamlink.github.io/cli.html#configuration-file
   - https://streamlink.github.io/cli.html#plugin-specific-configuration-file
   - https://streamlink.github.io/cli.html#cmdoption-config

----

```ini
# cookies.txt
http-cookie=foo=bar
http-cookie=baz=qux
```


```sh
streamlink --config cookies.txt URL STREAM
```

**Comment by CetaceanNation** [comment]
If you were also looking for a cookies.txt solution and want a shortcut for adding the `--http-cookie` params, you can use the following perl replace on a standard Netscape HTTP Cookie File:

`streamlink $(perl -p -e "s/(?P<site>.*?)\t(TRUE|FALSE)\t\/\t(TRUE|FALSE)\t([0-9]{1,})\t(?P<cookiename>.+)\t(?P<cookievalue>.+)/--http-cookie \5=\'\6\'/g" netscape-cookies.txt | tail -n +3)`

`tail` at the end assumes that there is a comment and two newlines at the top of the file, adjust as necessary.

**Comment by hugeblank** [comment]
Necro-ing this to say that I think that throwing away a common, compatible format with a custom one that has to pass every cookie individually is a bad design decision. Especially considering how many cookies services like youtube expect.
