### ISSUE TITLE
How to locate Streamlink dev after a python install

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#3374]
Hi I would like to know where I can locate streamlink atfer I installed from python via pip? i'm using windows 7 and since the windows installer fails. I would like to know where the python version of streamlink is located after the install? Thanks

**Comment by johnthecracker** [comment]
```
C:\>dir streamlink.exe /s
 Volume in drive C has no label.
 Volume Serial Number is F26D-FE20

 Directory of C:\P\STREAMLINK\bin

25/11/2020  22:26            97,467 streamlink.exe
               1 File(s)         97,467 bytes

     Total Files Listed:
               1 File(s)         97,467 bytes
               0 Dir(s)  453,693,972,480 bytes free

C:\>
```

**Comment by bobvargas** [comment]
@johnthecracker so that's where the python version of streamlink is located?

**Comment by bastimeyer** [comment]
The Python installer will automatically add the path of its root directory **and** its `Scripts` subdirectory to the system's `PATH` env var, just like the Streamlink installer does with its `bin` subdirectory. (Run `echo %PATH%` to see the full env var value)

Packages (python wheels, etc.) which get installed by `pip` and which have ["entry_points"](https://github.com/streamlink/streamlink/blob/0f12b520d18d715db54e25922b8570aaa5b6e703/setup.py#L58-L63) defined will have binaries built in the environment's `Scripts` subdirectory.

**This means that when installing Streamlink via pip, there will be a `streamlink.exe` and a `streamlinkw.exe` in the `Scripts` subdirectory of the used Python environment.**

To resolve the full path(s), you can simply run `where streamlink` from the command shell.

**Comment by bobvargas** [comment]
I don't see streamlinkw.exe in my directory after install and how you add streamlink to the path via python?

**Comment by johnthecracker** [comment]
You know how to find the file. If you don't find it it doesn't exist.

Read this about PATH

https://www.robvanderwoude.com/path.php

If you run windows, windows installation file is the way to go and not from python via pyp.
If you think otherwise, you get what you are into now.

https://streamlink.github.io/install.html
