### ISSUE TITLE
[Plugin Request] Add SkylineWebcams

### ISSUE THREAD

**Issue by wnmwi** [streamlink/streamlink#3376]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Skylinewebcams is a website that broadcasts scenery from all over the world. This website contains live broadcasts of many famous attractions such as Duomo di Milano and Eiffel Tower. Skylinewebcams are maintained by an Italian company and used to promote tourist destinations, cultural heritage, etc.

### Example stream URLs

1. https://www.skylinewebcams.com/zh/webcam/italia/lombardia/milano/duomo-milano.html
2. https://www.skylinewebcams.com/zh/webcam/france/ile-de-france/paris/tour-eiffel.html
3. https://www.skylinewebcams.com/zh/webcam/maldives/lhaviyani-atoll/kurendhoo/maldives-kuredu.html

### Additional comments, etc.
I like streamlink very much and thanks to the developers.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the plugin issue template:
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[1]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[2]] [[3]]
* - [x] Other (see below)
* Other: Plugin requests item number 11: Sites which are static cameras of a physical location

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Search all open/closed issues/pull requests][1]
[[2]] [Install the most recent version of Streamlink][2]
[[3]] [Check the master branch for plugin updates][3]

[1]: https://github.com/streamlink/streamlink/issues?q=
[2]: https://streamlink.github.io/install.html
[3]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins

**Comment by WolfganP** [comment]
Nice site. I tried it and is actually supported by the generic plugin https://github.com/back-to/generic

**Comment by wnmwi** [comment]
> Nice site. I tried it and is actually supported by the generic plugin https://github.com/back-to/generic

Thanks.
