### ISSUE TITLE
Plugin request for balticlivecam.com

### ISSUE THREAD

**Issue by 097115** [streamlink/streamlink#3377]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

**Balticlivecam** site is a collection of webcams that spreads throughout the whole Baltic region (and not limited to that, covering 80 countries and 445 cities), providing a variety of different locations. They also use only the best quality cameras in order to capture the places of stream in all of their beauty.

### Example stream URLs

1. https://balticlivecam.com/cameras/latvia/riga/panorama-of-riga/
2. https://balticlivecam.com/cameras/russia/vladivostok/vladivostok-city-view/
3. https://balticlivecam.com/cameras/lithuania/vilnius/vilnius-cathedral-square/

**Comment by gravyboat** [comment]
We're not adding any more static webcams for locations at this point in time per the [Plugin request guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests).
