### ISSUE TITLE
VK-plugin can't load some videos

### ISSUE THREAD

**Issue by aditorens** [streamlink/streamlink#3378]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Hi there. I have streamlink 1.7.0 on my win 10. And vk-plugin can't load videos.
I noticed, that streamlink can (!) load video when I use url from "streamlink/blob/master/tests/plugins/test_vk.py" (https://vk.com/video-24136539_456241176 for example). This is an old video (uploaded in 2017).
But new videos (for example https://vk.com/video-192739729_456240636) are not supported by vk-plugin.

### Reproduction steps / Explicit stream URLs to test

1. Run CMD
2. Exec. command: streamlink --loglevel debug https://vk.com/video-192739729_456240636

### Log output

```
C:\>streamlink --loglevel debug https://vk.com/video-192739729_456240636

[cli][debug] OS: Windows 10
[cli][debug] Python: 3.6.6
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin vk for URL https://vk.com/video-192739729_456240636
[plugin.vk][debug] video ID: -192739729_456240636
error: No playable streams found on this URL: https://vk.com/video-192739729_456240636
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
`Please log in or sign up to view this page.`

You need an account, but we don't support this.
