### ISSUE TITLE
I was going through my WebServer logs but couldn't differentiate between a player requests and streamlink requests. Is there any unique param that are being set by Streamlink that would help me identify a streamlink request?

### ISSUE THREAD

**Issue by Abhi-akamai** [streamlink/streamlink#3384]
## Feature Request

- [ ] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
- https://github.com/streamlink/streamlink/blob/fd1affa75c6c77e268b874219041c89d694c7534/src/streamlink/plugin/api/http_session.py#L67-L68
- https://streamlink.github.io/cli.html#http-options
