### ISSUE TITLE
Help enhancing my plugins to make them fit for streamlink inclusion

### ISSUE THREAD

**Issue by Twilight0** [streamlink/streamlink#3386]
## Plugin Request

- [X] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [ ] I am using the latest development version from the master branch.

### Description
Various sites, regexes inside respective modules: https://github.com/Twilight0/unofficial-streamlink-plugins
Except of course those which are not "official" sources.

### Example stream URLs

1. https://www.skaitv.gr/episode/enimerosi/ta-nea-tou-ska-stis-2000/2020-12-01-19
2. https://www.antenna.gr/Live

### Additional comments, etc.

Willing to provide more links which include videos, as the discussion goes. I have only tested above plugins with my own streamlink implementation for Kodi.

**Comment by back-to** [comment]
you need to remove some stuff

- remove `parse_hls`
- remove py2 compat
- remove unneeded `headers = {'User-Agent': CHROME}` `headers=headers`
- remove unneeded new lines after every new line
- don't use `json.loads` use `parse_json` or `self.session.http.json(...)`

some of the plugins are not needed https://github.com/streamlink/streamlink/pull/3308

---

you just need to clean it up first, before any can be added here.

**Comment by Twilight0** [comment]
1) Parse_hls: I have this only for Kodi, but upon submission here I will remove it
2) I bet python 2 compatibility has been completely phazed out? Oh my.. OK, I will remove it, after all these plugins are three months old.
3) Headers, ok..
4) New lines.. I am comfortable having new lines blank for readability, is it so mandatory to remove them?
5) Json loads, yes, ok

Do I need to add logging as well?

**Comment by back-to** [comment]
> Do I need to add logging as well?

not necessary, but sometimes it's better.

> New lines.. I am comfortable having new lines blank for readability, is it so mandatory to remove them?

it's a bit much sometimes

https://github.com/Twilight0/unofficial-streamlink-plugins/blob/master/opentv.py#L24-L58

**Comment by Twilight0** [comment]
Do I need to do a separate pull request for each plugin?

**Comment by bastimeyer** [comment]
> Do I need to do a separate pull request for each plugin?

Yes
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by back-to** [comment]
also install `flake8` `flake8-import-order` and run it

config https://github.com/streamlink/streamlink/blob/master/setup.cfg#L12-L53 if you don't use the Streamlink folder directly

**Comment by Twilight0** [comment]
I am using PyCharm, therefore I do not need separate linting.

**Comment by beardypig** [comment]
@Twilight0 you need to have PyCharm configured correctly for it to match the streamlink linting rules, even then it sometimes misses some things.

**Comment by gravyboat** [comment]
Which of these plugins doesn't violate the rules outlined in https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests? It seems like a lot of them are simply rebroadcasting television stations, dailymotion seems to have limited live streams (or I can't find any on their site from the main page), clipwatching requires a login.

**Comment by Twilight0** [comment]
These plugins were made for my own use because I needed the parse_hls boolean. All plugins except dailymotion and clipwatching has websites with content produced by themselves, they are all from greek television stations.

**Comment by gravyboat** [comment]
> they are all from greek television stations.

Right which we specifically had to disallow: `Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)` because we were seeing so many requests or plugin PRs for random TV stations all over the world without any way to determine actual viewership.

I proposed this on the 1spotmedia.com PR, but maybe it's time we consider a second repo for plugins that don't meet the requirements for core Streamlink inclusion but do for side loading? Seems like more management work but I don't know if there's another solution to avoid bloat.

**Comment by Twilight0** [comment]
None of the ones I mentioned (ert, skai, ant1, open, alpha, mega, omega, rik, sigma) "rehosts" on their own website, all content is original.

**Comment by back-to** [comment]
most of them should be valid requests,
create a new pull request per plugin, with example urls when you cleaned up the plugin.
