### ISSUE TITLE
smplayer doesn't play the stream

### ISSUE THREAD

**Issue by qupwen** [streamlink/streamlink#3388]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Smplayer doesn't play the stream.

### Expected / Actual behavior

Expect that smplayer play the stream.

### Reproduction steps / Explicit stream URLs to test

-Windows 7 64-bit
-Streamlink portable build by Beardypig
-Smplayer portable 20.6.0.0 x64 (multimedia engine: MPV)
-In cmd.exe: streamlink https://www.youtube.com/watch?v=21X5lGlDOfg 240p --loglevel debug --player "C:\xxxxxx\smplayer-portable-20.6.0.0\smplayer.exe"
-Smplayer launches and python.exe begins downloading but smplayer doesn't begin playback.

### Log output

```
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?
v=21X5lGlDOfg
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: 21X5lGlDOfg
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 240p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 6895785; Last Sequence: 6895791
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 6895789; En
d Sequence: None
[stream.hls][debug] Adding segment 6895789 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 6895790 to queue
[stream.hls][debug] Adding segment 6895791 to queue
[stream.hls][debug] Download of segment 6895789 complete
[cli][info] Starting player: C:\foreign\portables\smplayer-portable-20.6.0.0\smp
layer.exe
[cli.output][debug] Opening subprocess: C:\foreign\portables\smplayer-portable-2
0.6.0.0\smplayer.exe -
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 6895790 complete
[stream.hls][debug] Download of segment 6895791 complete
[stream.hls][debug] Reloading playlist
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)
<3

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#cmdoption-verbose-player

**Comment by qupwen** [comment]
__In cmd.exe:__ streamlink https://www.youtube.com/watch?v=21X5lGlDOfg 240p --loglevel debug --verbose-player --player "C:\xxxxxx\smplayer-portable-20.6.0.0\smplayer.exe"
__Output:__
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.6.5
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?
v=21X5lGlDOfg
[plugin.youtube][debug] Video ID from URL
[plugin.youtube][debug] Using video ID: 21X5lGlDOfg
[plugin.youtube][debug] get_video_info - 1: Found data
[plugin.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 240p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 6895942; Last Sequence: 6895948
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 6895946; En
d Sequence: None
[stream.hls][debug] Adding segment 6895946 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 6895947 to queue
[stream.hls][debug] Adding segment 6895948 to queue
[stream.hls][debug] Download of segment 6895946 complete
[cli][info] Starting player: C:\foreign\portables\smplayer-portable-20.6.0.0\smp
layer.exe
[cli.output][debug] Opening subprocess: C:\foreign\portables\smplayer-portable-2
0.6.0.0\smplayer.exe -
[stream.hls][debug] Download of segment 6895947 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 6895948 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6895949 to queue

**Comment by mkbloke** [comment]
Have you tried another player such as VLC or MPV, as this is very likely a player issue and not a Streamlink issue.

I have no problem playing that YouTube stream under Linux with Streamlink master and MPV.

**Comment by mkbloke** [comment]
Right, so it's an SMPlayer issue.  You should be asking about this in their forums/issue tracker.

Also, try testing for reading stdin from a file based video.  Something like `smplayer < videofile.ext` might do it.

**Comment by bastimeyer** [comment]
According to the following thread, smplayer doesn't support reading from `stdin`:
https://forum.smplayer.info/viewtopic.php?f=2&t=11737

You can try using a different player input method via [`--player-fifo`](https://streamlink.github.io/cli.html#cmdoption-n), [`--player-http`](https://streamlink.github.io/cli.html#cmdoption-player-http), or [`--player-passthrough`](https://streamlink.github.io/cli.html#cmdoption-player-passthrough), but other than that, this is not supported and not a Streamlink issue.

I'd recommend using a different player though, eg. MPV or VLC, because from looking at the smplayer project, its source code (via SVN in 2020 :roll_eyes:), and its binary distribution via SF, it doesn't seem to be in a good shape.
