### ISSUE TITLE
Facebook plugin not working anymore

### ISSUE THREAD

**Issue by scottbernstein** [streamlink/streamlink#3400]
## Bug Report

- [ x] This is a bug report and I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description
Streamlink is currently unable to play publicly available Facebook videos.  This used to work at some point, but Facebook must have changed their APIs.

### Expected / Actual behavior
The application should stream the Facebook videos

### Reproduction steps / Explicit stream URLs to test

1. https://www.facebook.com/BUSKINGDOWNTHEHOUSE/videos/205817704330664
2. https://www.facebook.com/jim.loughlin.5494/videos/188199372936189
3. https://www.facebook.com/AndersOsborne/videos/2822708501298940

### Log output
C:\Downloads\fix>streamlink "https://www.facebook.com/BUSKINGDOWNTHEHOUSE/videos/205817704330664" -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.7
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/BUSKINGDOWNTHEHOUSE/videos/205817704330664
[plugin.facebook][debug] No meta og:video:url
[plugin.facebook][debug] Falling back to playlist regex
[plugin.facebook][debug] Falling back to tahoe player
[plugin.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/BUSKINGDOWNTHEHOUSE/videos/205817704330664

^^^ This log output is the same for all 3 of the above URLs except that, obviously, the URL mentioned in the logs changes

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/3271
https://github.com/streamlink/streamlink/pull/3272
