### ISSUE TITLE
Facebook plugin still breaks on certain URLs even after applying change to remove User Agent from request

### ISSUE THREAD

**Issue by scottbernstein** [streamlink/streamlink#3401]
## Bug Report

- [ x] This is a bug report and I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description
Even after applying this change https://github.com/streamlink/streamlink/issues/3271 to the Facebook plugin manually, I have a URL that still doesn't work.

### Expected / Actual behavior
All Facebook URLs should play

### Reproduction steps / Explicit stream URLs to test
1. https://www.facebook.com/AndersOsborne/videos/2822708501298940

### Log outputC:\Downloads\fix>streamlink https://www.facebook.com/AndersOsborne/videos/2822708501298940 -l debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.7
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/AndersOsborne/videos/2822708501298940
[plugin.facebook][debug] No meta og:video:url
[plugin.facebook][debug] Falling back to playlist regex
[plugin.facebook][debug] Falling back to tahoe player
[plugin.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/AndersOsborne/videos/2822708501298940

### Additional comments, etc.
Even after I manually applied the code change to remove the USER AGENT from the request from the Facebook plugin (most URLs work now, thank you!), I still have one video URL that no longer works.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> You must log in to continue.

**Comment by scottbernstein** [comment]
Here is an alternative version of the same URL https://www.facebook.com/295261317100/videos/2822708501298940/

**Comment by llacb47** [comment]
![image](https://user-images.githubusercontent.com/16567977/101519337-11480980-3951-11eb-8c04-4c2282f9af84.png)

**Comment by scottbernstein** [comment]
![anders](https://user-images.githubusercontent.com/75334845/101519549-46ecf280-3951-11eb-8452-10af904c58a9.PNG)

**Comment by scottbernstein** [comment]
note no login and video is playing

**Comment by llacb47** [comment]
It works for me now. Strange.

**Comment by back-to** [comment]
> note no login and video is playing

and it works with Streamlink.

```
$ streamlink https://www.facebook.com/295261317100/videos/2822708501298940/
[cli][debug] OS:         Linux
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 1.7.0+97.g156d870
[cli][debug] Requests(2.25.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/295261317100/videos/2822708501298940/
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][error] Skipped DASH manifest with SegmentBase streams
[cli][info] Available streams: sd (worst, best)
[cli][info] Opening stream: sd (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: /usr/bin/mpv
```

**Comment by scottbernstein** [comment]
This is strange.  Upon retrying, it seems to work only about 50% of the time for me (50% of the time it gives me the error).  And when it does it only offers me the SD stream while the video itself has a 720p option.
