### ISSUE TITLE
i updated streamlink on my raspberry pi and now it does not work anymore

### ISSUE THREAD

**Issue by zerger3** [streamlink/streamlink#3406]
## Bug Report

- [ x] This is a bug report and I have read the contribution guidelines.
- [ x] I am using the latest development version from the master branch.

### Description

i think the issue is that the old version worked with python 2 and the new with 3

### Expected / Actual behavior

after checking the debian package i noticed its a old version so i uninstalled via apt
i installed first with
sudo pip install --upgrade streamlink
which didnt work and i noticed its python 2, so i uninstalled it with pip and then used 

sudo pip3 install --upgrade streamlink
which was succesful
`Successfully installed isodate-0.6.0 streamlink-1.7.0 websocket-client-0.57.0
`
now when i try to start streamlink i get the error

Traceback (most recent call last):
  File "/home/pi/.local/bin/streamlink", line 6, in <module>
    from streamlink_cli.main import main
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink_cli/main.py", line 21, in <module>
    from streamlink import __version__ as streamlink_version
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/__init__.py", line 21, in <module>
    from .api import streams
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/api.py", line 1, in <module>
    from .session import Streamlink
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/session.py", line 12, in <module>
    from streamlink.logger import StreamlinkLogger, Logger
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/logger.py", line 7, in <module>
    from streamlink.compat import is_py2
  File "/home/pi/.local/lib/python2.7/site-packages/streamlink/compat.py", line 48, in <module>
    from backports.shutil_which import which
ImportError: No module named shutil_which

how can i fix that?

"

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> sudo pip install --upgrade streamlink
> sudo pip3 install --upgrade streamlink

You should **never** install python packages globally with pip, as it'll introduce conflicts with your native package manager at some point. You're supposed to use the `--user` flag, which writes into `$HOME/.local`, or use a virtual environment.

This is explicitly pointed out in the docs:
https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

> sudo pip3 install --upgrade streamlink
> which was succesful

Since you've installed globally, the entry script will be found in `/usr/bin` (or `/usr/local/bin`), not in `$HOME/.local/bin`.

> /home/pi/.local/bin/streamlink
> /home/pi/.local/lib/python2.7/site-packages/streamlink_cli/main.py

You have **locally installed** a different streamlink version based on python 2.7, and `$HOME/.local/bin` is set before `/usr/bin` in your `PATH` environment variable, which means by running `streamlink`, you command line shell will resolve the incorrect path first.

Take a look at the `PATH` env var value:
```
echo $PATH
```

and clean up / uninstall the old local streamlink python27 install
```
pip --user uninstall streamlink
```

**Comment by zerger3** [comment]
thank you for your reply. i only understood 75% but:

pip uninstall  streamlink
pip3 uninstall  streamlink
pip3 install --upgrade --user streamlink
and adding
export PATH="${HOME}/.local/bin:${PATH}" at the end of ~/.profile 
fixed it.
could you please also help me with the config file?
it will look in one or both directories
$XDG_CONFIG_HOME/streamlink/config
~/.streamlinkrc

do i then create a "config" file in
/home/pi/streamlink ?

**Comment by bastimeyer** [comment]
https://streamlink.github.io/latest/cli.html#configuration-file

> Platform          | Location
> --                | --
> Unix-like (POSIX) | $XDG_CONFIG_HOME/streamlink/config
>                   |  ~/.streamlinkrc
> Windows           | %APPDATA%\streamlink\streamlinkrc

> Note
> `$XDG_CONFIG_HOME` is `~/.config` if it has not been overridden

Streamlink's main config file is located at `${XDG_CONFIG_HOME:-$HOME/.config}/streamlink/config`, which means `$HOME/.config/streamlink/config` on most systems, as `$XDG_CONFIG_HOME` is empty by default. See the ["XDG Base Directory Specification"](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) ([arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory)) if you have questions about this variable.
`$HOME/.streamlinkrc` is an old and deprecated fallback path.
