### ISSUE TITLE
Chat method: Custom application not working.

### ISSUE THREAD

**Issue by bititanb** [streamlink/streamlink#341]
I use Chatty, but wrapped it in .ps1 script just to hide a few interface elements on Chatty startup (the only way I found). But for some reason nothing passed to  "custom chat application command" field in the chat settings does not getting executed when I'm trying to open chat ("chat method: chatty" works perfectly however). Tried 'C:\...\powershell.exe ...\chatty.ps1 args', even tried to open cmd.exe with full path to it and without any arguments - doesn't work.

streamlink-twitch-gui 1.0.0 from chocolatey, win10 (default system language is russian).

**Comment by skulblakka** [comment]
This is the streamlink repository. Please post your issue on the [streamlink-twitch-gui](https://github.com/streamlink/streamlink-twitch-gui) issue tracker.

**Comment by bititanb** [comment]
Omg, I'm sorry, my bad.
