### ISSUE TITLE
kanald broken

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink#3416]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

Example link 1 (VOD): https://www.kanald.com.tr/sadakatsiz/fragmanlar/sadakatsiz-10-bolum-fragmani
Example link 2 (Live): https://www.kanald.com.tr/canli-yayin

### Log output

```
streamlink 'https://www.kanald.com.tr/sadakatsiz/fragmanlar/sadakatsiz-10-bolum-fragmani'
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/sadakatsiz/fragmanlar/sadakatsiz-10-bolum-fragmani
[plugin.dogan][error] Could not find the contentId for this stream
error: No playable streams found on this URL: https://www.kanald.com.tr/sadakatsiz/fragmanlar/sadakatsiz-10-bolum-fragmani
```

### Additional comments, etc.
Thanks in advance

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
I have work in progress on this.  I'll just need to validate the changes I've made across all the supported sites for the plugin.

**Comment by fenopa** [comment]
> 
> 
> I have work in progress on this. I'll just need to validate the changes I've made across all the supported sites for the plugin.

Thank you, I can help with test if you want.

**Comment by mkbloke** [comment]
@fenopa, many thanks for offering to help test.  I'll just do some preliminary tests and then post something up here for you to try.

**Comment by mkbloke** [comment]
@fenopa, many thanks for helping to test.  Here's the fixed/updated plugin:

https://raw.githubusercontent.com/mkbloke/streamlink/dogan/src/streamlink/plugins/dogan.py

I've done some validation to make sure my changes work on the below sites/URL paths before pushing the branch to GitHub (which turned out to be very necessary), so hopefully you will not have any issues.  The plugin supports the following sites/URL paths now:

- cnnturk.com/canli-yayin
- cnnturk.com/video/*
- dreamturk.com.tr/canli
- dreamturk.com.tr/canli-yayin-izle
- kanald.com.tr/*
- teve2.com.tr/canli-yayin
- teve2.com.tr/filmler/*
- teve2.com.tr/programlar/*

Thanks.

**Comment by fenopa** [comment]
@mkbloke thank you so much <3, my feedback is below. note that this is just feedback, it's fine if you don't want to bother with it anymore.

- all live links worked fine, all kanald links worked great, supported paths for cnnturk and teve2 worked great but some paths lacking, details below.

**-teve2:**
you could add _teve2.com.tr/diziler*_ path too I think.
example url: https://www.teve2.com.tr/diziler/guncel/oyle-bir-gecer-zaman-ki/bolumler/oyle-bir-gecer-zaman-ki-1-bolum

**-cnnturk:**
_cnnturk.com/tv-cnn-turk*_ path could be supported too I think.
example urls:
https://www.cnnturk.com/tv-cnn-turk/belgeseller/bir-zamanlar/bir-zamanlar-90lar-belgeseli
https://www.cnnturk.com/tv-cnn-turk/programlar/5n1k/abd-neden-yaptirim-uyguluyor-yaptirimlar-gelirse-neler-yasanir-asi-cesitleri-ve-farklari-neler-5n1kda-konusuldu

**-dreamturk:**
some vod urls:
- https://www.dreamturk.com.tr/programlar/t-rap/bolumler/t-rap-keisan-ozel
- https://www.dreamturk.com.tr/programlar/desarj/bolumler/desarj-hande-unsal-ozel

- https://www.dreamturk.com.tr/dream-turk-ozel/radyo-d/ilyas-yalcintas-radyo-dnin-konugu-oldu
- https://www.dreamturk.com.tr/dream-turk-ozel/canli-performanslar/gulsah-tutuncuden-sev-diyemem

similar to last two one, from dreamtv.com.tr:
- https://www.dreamtv.com.tr/dream-ozel/konserler/acik-sahne-dream-ozel
- https://www.dreamtv.com.tr/dream-ozel/festivaller/k-pop-world-festival-2019-turkiye-on-elemesi

and lastly, these embed urls can be retrieved with "share" dialogs, might be supported?
- https://teve2.com.tr/embed/55f6d5b8402011f264ec7f64
- https://www.kanald.com.tr/embed/5fda41a8ebc8302048167df6
- https://www.cnnturk.com/action/embedvideo/5fa56d065cf3b018a8dd0bbc

Thank you so much again, it's totally fine in its current state too since my main concern was kanald and it works fully so I'm more than happy, this is just feedback for your consideration.

**Comment by mkbloke** [comment]
@fenopa, OK, I've updated my last comment, so everything you have mentioned above should now be supported.  You can download the updated plugin from the same link in my previous comment.  Cheers.

**Comment by fenopa** [comment]
@mkbloke using it for two weeks and everything works great. forgot to thank you again, cheers <3
