### ISSUE TITLE
Earthcam plugin on streamlink

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#342]
Happy new year streamlink team! Listen I want everyone to make a plugin for earthcam so I can look at the live camera around NYC and the world thanks.

**Comment by gravyboat** [comment]
Can you please provide details regarding what the URL looks like for specific cameras/streaming?

**Comment by beardypig** [comment]
I started work on a plugin, it's not too hard. A few things to work out, detecting offline/unavailable streams etc.

**Comment by bobvargas** [comment]
@gravyboat  Cameras such as times square, Midtown, Rio, And Japan

**Comment by beardypig** [comment]
@bobvargas I have created an earthcam plugin that you can test out: [earthcam.py](https://github.com/beardypig/streamlink/blob/3934df79739e96a2f8152e0796ba2e5aba247989/src/streamlink/plugins/earthcam.py).

**Comment by stevek123** [comment]
@beardypig It works on the website, but the plugin always exits with either 

> [cli][error] Failed to read data from stream: Read timeout

or

> [cli][error] No data returned from stream

**Comment by stevek123** [comment]
@beardypig The issue seems to be that the wrong parameters get passed in the end

**Comment by beardypig** [comment]
Some appears to have changed since I created that first version of the plugin. I'll take a look at it.
