### ISSUE TITLE
Youtube-Plugin:  Could not find a video on this page for Live-Videos

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#3426]
YouTube-plugin still doesn't work for some live-channels here. 
The example Deutsche Welle is working, but e.g. Todo Noticias [http://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw](http://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw) just works using `https://www.youtube.com/embed/live_stream?channel=<channelid>` as mentioned in [https://github.com/streamlink/streamlink/issues/3320](https://github.com/streamlink/streamlink/issues/3320). It does not work with `http://www.youtube.com/channel/UCj6PcyLvpnIRT_2W_mwa9Aw` nor `https://www.youtube.com/user/todonoticias/live`
(another channel would be C5N: [http://www.youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w](http://www.youtube.com/channel/UCFgk2Q2mVO1BklRQhSv6p0w)

(using Streamlink 1.7-Win10 and youtube.py from the master branch)

**Comment by gravyboat** [comment]
There were several fixes that will be available in the upcoming stable release. If you can't wait you can install the nightly. We're going to try and get the 2.0 release out in the next few days.
