### ISSUE TITLE
plug-in request https://www.tango.me

### ISSUE THREAD

**Issue by cesaroscesars** [streamlink/streamlink#3436]
https://www.tango.me Peiscope It is a similar live chat application, please bring a plug-in for it.

1. ...https://www.tango.me 
2. ...
3. ...

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
This doesn't meet the requirements for plugin requests. Please add the required information.

**Comment by cesaroscesars** [comment]
When I say necessary information, what exactly do you need and where can I find what you need?

**Comment by cesaroscesars** [comment]
In fact, the information I have is very similar to the logic of Periscope or Bigo. With the m3u8 method, stream can be taken for 6-8 seconds, but then another m3u8 code is activated.Also, I could not see the m3u8 code because I could not enter premium publications.When I try it on Steam Link, I get the error that there is no plug-in.

**Comment by cesaroscesars** [comment]
There is also a sample broadcast link below.
https://www.tango.me/stream/s--GiQGIu-oLNCAZcpKuFw

**Comment by cesaroscesars** [comment]
Frankly, I have no idea what exactly we should do, but my head is always going to m3u8 codes, as if they are combined but of course because we cannot see premium broadcasts without paying m3u8 I'm not sure if we can get your code

**Comment by cesaroscesars** [comment]
I'm closing this because a request has been opened that can explain the topic more properly
