### ISSUE TITLE
Support for OpenCaster.com/Clappr

### ISSUE THREAD

**Issue by opm0** [streamlink/streamlink#3443]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Venezuelan public TV channel TVes uses the opencaster.com platform for its internet stream.

### Example stream URLs

1. https://www.tves.gob.ve/en-vivo/
2. http://opencaster.com/tves-100
3. https://www.opencaster.com/tves-100-100
4. https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj.m3u8
5. https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj-258287.ts

### Additional comments, etc.

I get an error when I try to use the m3u8 link outside the player.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
the URL seems static, a plugin is not needed.

just add a header
https://streamlink.github.io/cli.html#cmdoption-http-header

```
streamlink "https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj.m3u8" best --http-header "Origin=https://www.opencaster.com"


[cli][info] Found matching plugin hls for URL https://edge1o.live.opencaster.com/caster/erCkqDzdGzpj.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
```
