### ISSUE TITLE
https://www.micous.com/ Site closing webcasts

### ISSUE THREAD

**Issue by wilheamdash** [streamlink/streamlink#3455]
## Plugin Issue

- [ ] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description
I was checking the m3u8 codes for Tango Live so that it would benefit people and maybe we can bring plugins but now I have checked and the mico.us plugin does not work because mico.us is no longer working. It looks like it has turned off broadcasting and playback, I guess only broadcasts can be followed through the application and need to be checked. 

### Reproduction steps / Explicit stream URLs to test
this? Please note the exact steps below using the list format supplied. If you need more steps please add them. -->

1. ...https://www.micous.com/
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by wilheamdash** [comment]
I am happy to help with this problem thank you

**Comment by mkbloke** [comment]
If you want to work on this, i.e. by reverse engineering one of the apps, then please feel free to do so.  I am not really inclined to work on plugins for this type of site though.  I don't believe there's a huge user-base for such plugins within Streamlink users, so it doesn't really seem like it's worth the effort for me.

**Comment by wilheamdash** [comment]
> Bunun üzerinde çalışmak istiyorsanız, yani uygulamalardan birine tersine mühendislik uygulayarak, lütfen bunu yapmaktan çekinmeyin. Yine de bu tür siteler için eklentiler üzerinde çalışmaya gerçekten meyilli değilim. Streamlink kullanıcıları içinde bu tür eklentiler için büyük bir kullanıcı tabanı olduğuna inanmıyorum, bu yüzden benim için gerçekten çabaya değecek gibi görünmüyor.
 

You have been receiving tango live requests very often lately and this caught my attention and my interest. For this, I succeeded in streamlink with m3u8 links.I think the mass of this application has increased because most of the bigo publishers have started this application.I don't know how to write a plug-in but I was thinking of opening an extension request in the future with the m3u8 codes.
