### ISSUE TITLE
After installing v0.2.0, the --version command still returns v.0.1.0

### ISSUE THREAD

**Issue by Skarablood** [streamlink/streamlink#346]
I'm using the Streamlink Twitch GUI, whose developers recently decided to implement a version check, requiring the newest version of Streamlink, v0.2.0, to be installed. I therefore downloaded that version (Windows 10 user, so streamlink-0.2.0.exe) and installed it. Afterwards, the Streamlink Twitch GUI threw the same error, claiming the version was still v.0.1.0.

I checked myself to be sure:
`C:\Program Files (x86)\Streamlink\bin>streamlink.exe --version`
`streamlink-script.py 0.1.0`

Now I'm kinda at a loss here... . Whats wrong?

**Comment by skulblakka** [comment]
Did you try removing and reinstalling streamlink? There also was a problem with a previous version of the 0.2.0-installer causing the package still reporting version 0.1.0 (see #310).

**Comment by Skarablood** [comment]
I downloaded the installer again and tried removing and reinstalling as well as removing, restarting and reinstalling, but it didn't help.

**Comment by skulblakka** [comment]
I just tried it myself and it works as expected (returning 0.2.0). If you enter ```where streamlink``` into cmd what is the result?

**Comment by Skarablood** [comment]
It returns
`C:\>where streamlink`
`C:\Program Files (x86)\Streamlink\bin\streamlink.exe`

**Comment by skulblakka** [comment]
That looks correct to me. 

As it works for me I'm still guessing that the old version was not correctly removed when uninstalling. Did you make sure that no files remain in ```C:\Program Files (x86)\Streamlink``` after you uninstalled it?

**Comment by Skarablood** [comment]
I did, the whole folder was gone after removing Streamlink. Maybe I'll just try a different folder once I get home from work, just to be sure.

**Comment by gravyboat** [comment]
Can you try the nightly build from here: https://streamlink.github.io/install.html#windows-binaries

**Comment by Skarablood** [comment]
Works like a charm! Thank you!

**Comment by gravyboat** [comment]
Awesome glad to hear it! I'm going to close this for now. We'll try to get a new release out which should hopefully address the versioning issue. We had to re-release 0.2.0 and it seems like it has caused a few oddities.
