### ISSUE TITLE
TRT plugin not working anymore

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#3469]
Hello,

previous versions supported trt.py and trtspor.py for the sports channel. They have been removed since a while.

TRT has moved from http://www.trt.net.tr to https://www.trtizle.com

Click on top of site "CANLI IZLE" to get the whole channel list.

For example "https://www.trtizle.com/canli/tv/trt-1" for TRT-1 and so on...

Can you recreate an updated version for trt.py plugin?

Greetings

**Comment by bastimeyer** [comment]
#2928

**Comment by gravyboat** [comment]
@Rotarum Spamming across multiple issues is not acceptable, as such I've locked all of those. The error is a [403](https://en.wikipedia.org/wiki/HTTP_403), aka access is forbidden. `https://tv-trt1.live.trt.com.tr/master.m3u8` as an example still works fine. You probably need to find the new URL if one exists for that specific channel.

**Comment by Rotarum** [comment]
With option hls:// in front of the static m3u8 its working fine yes.

I experienced very often in the past that turkish tv stations are changing the static url. That's why i request a plugin for it :)

**Comment by gravyboat** [comment]
> I experienced very often in the past that turkish tv stations are changing the static url. 

If the URL is constantly changing the plugin won't work though since we would have to change what we are searching for repeatedly when we parse it. This is specifically the kind of plugin we don't want to maintain because it requires a lot of work as the service provider can't make up their mind about where to put the content.

**Comment by back-to** [comment]
@Rotarum 

all the URLs from https://github.com/streamlink/streamlink/issues/2928#issuecomment-653745121 will work.

you are just **GEO blocked** 
```
403 ERROR
The Amazon CloudFront distribution is configured to block access from your country. 
```


you will need a **turkish IP (Proxy/VPN)** for the sport channels.

```
$ streamlink https://tv-trtspor2.live.trt.com.tr/master.m3u8
[cli][debug] OS:         Linux
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://tv-trtspor2.live.trt.com.tr/master.m3u8
[plugins.hls][debug] URL=https://tv-trtspor2.live.trt.com.tr/master.m3u8; params={}
[cli][info] Available streams: 360p (worst), 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
```
