### ISSUE TITLE
Should we set up methods by which people can donate?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#347]
I've modified this based on some discussion below. Should we set up either a donation page with individuals and their donation information, or set up something like bountysource as mentioned by @bastimeyer?

Edit: I should note I would like to run team donations, but pretty much every service requires PayPal which I personally am very against using since they're a scummy organization. The other option is to do like @bastimeyer does where the donation links are available on the releases page (or maybe we could just make another donation page with links for people since there are multiple people working on this and it might become cluttered). The main issue I see with this also is how you determine who gets paid what amount, as well as transfers to other countries. The more I think about it the more a donation page makes sense.

**Comment by bastimeyer** [comment]
For projects where multiple people work on, bountysource is a better alternative. Individual bugfixes, feature requests, plugin requests, etc. can be supported with donations this way instead of using a single service for multiple devs.

https://www.bountysource.com/
https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

**Comment by gravyboat** [comment]
Yeah I've got an account over on bountysource so that's definitely an option. I'm not sure how much traction we would get for people posting bounties over there, but it's a good idea.

**Comment by BarryCarlyon** [comment]
Given that Streamlink prevents Adverts on Twitch playing, that means that the use of Streamlink is against Twitch TOS (theres a clause about advert bypassing buried somewhere)

So, therefore, why would Twitch partner something against Twitch TOS when, Curse, which Twitch bought, has a Twitch player built into it. And thus Streamlink is _technically_ a competing product.

**Comment by gravyboat** [comment]
@BarryCarlyon Thus why I started the discussion of if it's even worth approaching Twitch about since we fall into a weird gray area (as we don't purposefully circumvent ads). I'm not willing to get into a discussion about Streamlink versus Curse as I believe they serve completely different markets, plus we support way more sites. I'll modify the topic of this issue however to move more in a direction of donations, thanks for your input.

**Comment by BarryCarlyon** [comment]
@gravyboat all good. I was skimming past projects on git and was perusing the Issues list. :-) Was just using Curse as an example.

On a side note, donations are tax deductable and go to charity. Which this project is not, the correct terminology is "Tip" but I aint no lawyer. Yay for weird words and meanings
