### ISSUE TITLE
Add Poland plugin TawizjaTV

### ISSUE THREAD

**Issue by azman26** [streamlink/streamlink#3472]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x ] I have read the contribution guidelines.

### Description

This is an official page for local channels from Poland.

### Expected / Actual behavior

Add plugin 

### Reproduction steps / Explicit stream URLs to test

https://www.tawizja.pl/na-zywo

### Logs

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, etc.

import re

from streamlink.exceptions import PluginError
from streamlink.plugin import Plugin
from streamlink.plugin.api import http
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream
from streamlink.stream import HTTPStream

_url_re = re.compile(r"http(s)?://(www\.)?popler.tv/live/TawizjaTV")
_RE_PLAYLIST = re.compile(r'src:\s*"([^"]+)"') 

class Tawizja(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        res = http.get(self.url)
        text = res.text 
        playlist_url = _RE_PLAYLIST.search(text).group(1) 
        if playlist_url.startswith("//"): playlist_url='http:'+playlist_url
        hls_streams = HLSStream.parse_variant_playlist(
            self.session,
            playlist_url,
            headers={'Referer': self.url, 'User-Agent': useragents.ANDROID}
        )
        for s in hls_streams.items():
            yield s

__plugin__ = Tawizja

**Comment by bastimeyer** [comment]
> 10. Sites which have no way to determine viewership numbers

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
