### ISSUE TITLE
param for source address or IPv4/IPv6 

### ISSUE THREAD

**Issue by lekoOwO** [streamlink/streamlink#3474]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Is it possible to add parameters to select which ip to use on recording?

Like `curl`'s `-4 -6 --interface`, `youtube-dl`'s `-4 -6 --source-address`

If it can be implemented, we can prevent 429 errors at many cases.

### Expected / Actual behavior

I get 429 error on some cases because of IPv4 NAT, although a dedicated IPv6 address is available. 

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
While `--interface` would be fairly straightforward to implement for http(s) requests in the `Session` class, changing the socket address family via `-4` or `-6` would be a bit more difficult, as it seems that it requires overriding [`urllib3.util.connection.allowed_gai_family`](https://github.com/urllib3/urllib3/blob/1.26.2/src/urllib3/util/connection.py#L109-L117). A bit of refactoring would probably also be necessary.

In addition to that, all other network connections, like websockets for example, are currently set up by the plugins individually, so there's no clean way of implementing these features for non-HTTP stuff.

----

The interface can be changed in `Session.set_option` like this, without having to call `requests.adapters.HTTPAdapter.init_poolmanager` twice:

```py
for scheme, adapter in self.http.adapters.items():
    if scheme not in ("http://", "https://"):
        continue
    adapter.poolmanager.connection_pool_kw.update(
        source_address=(value, 0)
    )
```

See [`socket.create_connection`](https://docs.python.org/3/library/socket.html#socket.create_connection) for the `source_address` format.

----

Examples from my local changes:

```
$ streamlink IPv4-INPUT best -l none -o /dev/null --interface 192.168.178.99
$ ss -npt | grep streamlink | head -n1 | awk '{print $4}'
192.168.178.99:53557
```
```
$ streamlink IPv4-INPUT best -l none -o /dev/null --interface 192.168.100.1
$ ss -npt | grep streamlink | head -n1 | awk '{print $4}'
192.168.100.1:37027
```
```
$ streamlink IPv4-INPUT best -l none -o /dev/null --interface invalid
error: No playable streams found on this URL: IPv4-INPUT
```

**Comment by back-to** [comment]
similar to https://github.com/streamlink/streamlink/issues/2192
