### ISSUE TITLE
Turkuvaz Plugin missing Streams

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#3475]
Hi,

first of all to be sure installed Streamlink 2.0.0 via Python3 again.

After that tested all streams one by one with the turkuvaz.py

Most of them are working, only 2 of 9 channels missing, "error: No plugin can handle URL"

A2 and A Haber TV:

https://www.atv.com.tr/a2tv/canli-yayin
https://www.ahaber.com.tr/video/canli-yayin

**Comment by mkbloke** [comment]
Probably just needs a regex update. I'll take a look at it tomorrow if nobody else does before.

**Comment by mkbloke** [comment]
@Rotarum, here's an updated plugin for turkuvaz:

https://raw.githubusercontent.com/mkbloke/streamlink/turkuvaz/src/streamlink/plugins/turkuvaz.py

That should support the two missing URLs you have listed above.  If you can test those and - if you have time - also test some of the other existing sites to make sure I have not broken anything, that would be much appreciated, thanks.

**Comment by back-to** [comment]
create a pull request
