### ISSUE TITLE
Dogus.py missing stream

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#3476]
https://www.ntvspor.net/ntvspor-canli-yayin

This is normally handled by dogus.py but it seems to be outdated. The other streams are working ok only this one.

**Comment by mkbloke** [comment]
I'll take a look tomorrow.

**Comment by gravyboat** [comment]
@Rotarum Make sure to provide all the information required by the template. You didn't here, you didn't on https://github.com/streamlink/streamlink/issues/3477, and you didn't on https://github.com/streamlink/streamlink/issues/3475. You've also been commenting multiple times on closed issues generating unnecessary noise. If this continues I'll have to ban you from the repo in the future. This is an open source project and you're doing less than the bare minimum to help the people trying to fix issues.

**Comment by Rotarum** [comment]
@gravyboat Oh i'm generating "unnecessary noise".

So this will be the last time i report bugs or other stuff.

I am out of this project 👎

**Comment by mkbloke** [comment]
@Rotarum, here's an updated plugin for dogus:

https://raw.githubusercontent.com/mkbloke/streamlink/dogus/src/streamlink/plugins/dogus.py

That should support the missing URL you have listed above. If you can test it and - if you have time - also test some of the other existing sites to make sure I have not broken anything, that would be much appreciated, thanks.

**Comment by back-to** [comment]
create a pull request

**Comment by mkbloke** [comment]
@Rotarum, can you confirm that https://www.ntvspor.net/ntvspor-canli-yayin plays OK for you with the updated plugin?

The problem is, I can only use open proxies or Tor to test and I get 404 for the playlist in a browser and with this updated plugin.  It could be that it's a strange way that they deal with geo-restriction, but I cannot determine that.  Thanks.

**Comment by back-to** [comment]
there is no livestream on this website, URL can be removed from the plugin.

https://en.wikipedia.org/wiki/NTV_Spor

**Comment by mkbloke** [comment]
Thanks, @back-to.  It looks like that was a waste of time then.  I'll create a PR with the channel removal...

**Comment by Rotarum** [comment]
It is online at moment:

https://www.ntvspor.net/ntvspor-canli-yayin

**Comment by back-to** [comment]
it is just the same as ntv https://www.ntv.com.tr/canli-yayin/ntv not a 2nd channel

**Comment by Rotarum** [comment]
ntv is a embedded youtube stream.

ntvspor is not yt, it's their own stream from www.ntvspor.net

**Comment by mkbloke** [comment]
OK, so the plugin appears to be working.  I now have two branches, the original that updates the channel path and a channel removal branch.  Just let me know which one you want...

**Comment by back-to** [comment]
@Rotarum 

> ntv is a embedded youtube stream.

only when you are **geo blocked**,
it is not for turkish IPs.

```
streamlink https://www.ntv.com.tr/canli-yayin/ntv
[cli][debug] OS:         Linux
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0+18.g1d5fb3a.dirty
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogus for URL https://www.ntv.com.tr/canli-yayin/ntv
[plugins.dogus][debug] Found mobile stream: "https://dygvideo.dygdigital.com/live/hls/ntv?token="
[cli][info] Available streams: 240p (worst), 360p, 720p (best)
[cli][info] Opening stream: 720p (hls)
```

---

@mkbloke 

it can be removed, it is just a duplicate.

**Comment by Rotarum** [comment]
Very interesting info thx!

Foreigners can only watch via Youtube. Other TV providers do not geoblock or something else.

The channels in dogus.py are FTA (Free-to-Air) with normal Satellite Television
