### ISSUE TITLE
Turkish TV Stations

### ISSUE THREAD

**Issue by Rotarum** [streamlink/streamlink#3477]
Hi,

there is a site streaming all categories of turkish livestreams:

**https://izle.canlitvlive.io/**

It is so interesting because they encode and stream on their own and not just post youtube live url or similar!

Hopefully you can add this one because i get crazy of this geoblocking and offline messages :(

Greetings

**Comment by gravyboat** [comment]
Issue doesn't meet requirements outlined in the issue template and also violates [3 and 10](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests).
