### ISSUE TITLE
Twitch.tv -- error: No playable streams found on this URL

### ISSUE THREAD

**Issue by edwinjue** [streamlink/streamlink#3488]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

On a linux terminal, I execute the following command: 
   streamlink --http-header Client-ID=ewvlchtxgqq88ru9gmfp1gmyt6h2b93 twitch.tv/markettraderstv --loglevel debug

I receive the following error message: 
    error: No playable streams found on this URL: twitch.tv/markettraderstv

However, there is a playable stream when I visit the live stream from a web browser

Note: twitch.tv/markettraderstv is live 24/7 so you can try this yourself

### Reproduction steps / Explicit stream URLs to test

1. On a linux terminal, execute: "streamlink --http-header Client-ID=ewvlchtxgqq88ru9gmfp1gmyt6h2b93 twitch.tv/markettraderstv --loglevel debug"
2. I receive the response in the console: "error: No playable streams found on this URL: twitch.tv/markettraderstv"
3. Visit twitch.tv/markettraderstv from web browser. The stream is clearly live

### Log output

```
streamlink --http-header Client-ID=ewvlchtxgqq88ru9gmfp1gmyt6h2b93 twitch.tv/markettraderstv --loglevel debug
[cli][debug] OS:         Linux-4.15.0-128-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/markettraderstv
[plugin.twitch][debug] Getting live HLS streams for markettraderstv
error: No playable streams found on this URL: twitch.tv/markettraderstv
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.7.0

You are not using the **latest version**, which is currently `2.0.0`.

See
https://github.com/streamlink/streamlink/pull/3344#issuecomment-760552521

Twitch has shut down the old API endpoint that was used prior to `2.0.0` when acquiring the streaming access token. Streamlink `2.0.0` has switched to the GraphQL API, where the access tokens now have to be acquired from.

**Comment by bastimeyer** [comment]
Keep it open for a bit, because there will be lots of duplicates otherwise...

**Comment by gravyboat** [comment]
Okay, let's pin it as well.

**Comment by edwinjue** [comment]
Hi, I tried removing and then re-installing the latest version for Ubuntu using the command on the installation page:

sudo apt-get remove streamlink
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
sudo apt install streamlink

However, it still defaults to 1.7.0

I also tried the python pip installation, which also defaults to 1.7.0

Please advise. Thanks guys!

**Comment by bastimeyer** [comment]
> Ubuntu

The official packages are very much outdated, as always (which is why I don't recommend using Ubuntu on the desktop):
https://packages.ubuntu.com/groovy/streamlink

> ppa:nilarimogard/webupd8
> Ubuntu-18.04-bionic

Streamlink `2.0.0` is only available on groovy (Ubuntu 20.10) on the webupd8 PPA, as you can see here:
http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/s/streamlink/

> I also tried the python pip installation, which also defaults to 1.7.0

Then you are still running the old version by accident. I've answered a similar question here already:
https://github.com/streamlink/streamlink/discussions/3406

Uninstall Streamlink from your native package manager and install Streamlink via pip as user. See the section on the docs site and read about the `--user` flag and what it does:
https://streamlink.github.io/latest/install.html#pypi-package-and-source-code

**Comment by edwinjue** [comment]
removed streamlink form native package manager

installed streamlink via pip as user:
   pip install --user --upgrade streamlink

received the following error message (segmentation fault, and still seems to be grabbing streamlink-1.7.0 per **bold** below):
   Installing collected packages: iso3166, pycryptodome, six, enum34, pycparser, cffi, ipaddress, cryptography, pyOpenSSL, idna, certifi, urllib3, chardet, requests, isodate, websocket-client, singledispatch, backports.shutil-get-terminal-size, iso-639, futures, PySocks, backports.shutil-which, streamlink
Successfully installed PySocks-1.7.1 backports.shutil-get-terminal-size-1.0.0 backports.shutil-which-3.5.2 certifi-2020.12.5 cffi-1.14.4 chardet-4.0.0 cryptography-3.3.1 enum34-1.1.10 futures-3.3.0 idna-2.10 ipaddress-1.0.23 iso-639-0.4.5 iso3166-1.0.1 isodate-0.6.0 pyOpenSSL-20.0.1 pycparser-2.20 pycryptodome-3.9.9 requests-2.25.1 singledispatch-3.4.0.3 six-1.15.0 **streamlink-1.7.0** urllib3-1.26.2 websocket-client-0.57.0
**Segmentation fault (core dumped)**

**Comment by edwinjue** [comment]
ok, fixed it by using pip3 instead of pip:

pip**3** install --user --upgrade streamlink

pip was executing the install using Python 2.*

Thanks guys!

**Comment by edwinjue** [comment]
just thought I'd let you know twitch is giving the following screen when I execute the following command in streamlink 2.0.0:

streamlink https://www.twitch.tv/markettraderstv 720p60

![image](https://user-images.githubusercontent.com/1448719/104679002-8968c400-56a1-11eb-8ae4-75f1e8647a4d.png)

**Comment by bastimeyer** [comment]
- https://github.com/streamlink/streamlink/issues/3210
- https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads
