### ISSUE TITLE
Add support for Tango.me

### ISSUE THREAD

**Issue by Ultrapower-OBS** [streamlink/streamlink#3493]
## Plugin Request

Is there a possibility to add a new plugin for www.tango.me ?

Thank you very much.

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [x] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [x] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [x] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues?q=tango

**Comment by Ultrapower-OBS** [comment]
Sorry i did not see the previous issue thread.

The site is like periscope. It's free and no nude is allowed.... see 4. and 5.

So it would be great to have a plugin support for tango.me

**Comment by gravyboat** [comment]
@Ultrapower-OBS We're not going to add it.
