### ISSUE TITLE
 streamlink would suddenly be closed

### ISSUE THREAD

**Issue by mooczhou** [streamlink/streamlink#3494]
Hello, Sebastian Meyer! 
                After I used streamlink to pull the stream on the website, I used some ffmpeg and srs to push the stream. I found that at a certain point in time, streamlink would suddenly be closed. I want to ask what is going on? The following is my entire push command:
nohup streamlink  https://www.twitch.tv/lcs best -o - | ffmpeg -re -i pipe:0 -c:v copy -c:a aac -f flv rtmp://localhost:1935/live/livestream/lcs > /dev/null 2>&1 &

## Bug Report

- [ ] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
Please provide debug log output, I recommend redirecting all the output to a file instead of `/dev/null`.
