### ISSUE TITLE
wwe network 

### ISSUE THREAD

**Issue by mr-uk-me** [streamlink/streamlink#3498]
noticed today wee network stopped working, and IP address banned.

after changing ip and firing back up

[cli][info] Found matching plugin wwenetwork for URL http://watch.wwe.com/channel/2026
error: Login failed

but login is correct and works fine, after a attempts ip gets banned again.

not sure if login fields have changed

**Comment by back-to** [comment]
every request from streamlink is a **new login**,
don't spam the server or you will get banned there.
