### ISSUE TITLE
Installed along side Livestreamer?

### ISSUE THREAD

**Issue by Junior1544** [streamlink/streamlink#35]
Can this program be installed on a computer right along side Livestreamer?

I have a raspberri Pi and would like to try installing this on it but I currently use Livestreamer and don't want to mess that up in case this isn't up to snuff yet?

Also, is the command line updated from this from being livestreamer to streamlink yet?

Mahalo!

**Comment by OkanEsen** [comment]
Yes, this should be possible.

**Comment by sbstp** [comment]
Yes, the command line program and the package were renamed to `streamlink`. The config file is named `streamlinkrc` as well.

**Comment by gravyboat** [comment]
Yep, closing as this has been answered.
