### ISSUE TITLE
[PL] New Plugin "TaWizja" Add

### ISSUE THREAD

**Issue by azman26** [streamlink/streamlink#3500]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

It is a general-thematic television with materials ranging from feature films, through documentaries, to journalistic programs (conversations with interesting people). Film materials are interwoven with modern music videos, interesting in form.

### Example stream URLs

1. https://www.tawizja.pl/na-zywo
2. https://www.popler.tv/TawizjaTV#autor
3. ...

### Additional comments, etc.
I have a plugin that worked on streamlink not long ago.
Unfortunately, there were some changes in broadcasting and the plugin stopped working.
Maybe it will not be difficult for you to correct the plugin code and restore its functionality.

`import re

from streamlink.exceptions import PluginError
from streamlink.plugin import Plugin
from streamlink.plugin.api import http
from streamlink.plugin.api import useragents
from streamlink.stream import HLSStream
from streamlink.stream import HTTPStream

_url_re = re.compile(r"http(s)?://(www\.)?popler.tv/live/TawizjaTV")
_RE_PLAYLIST = re.compile(r'src:\s*"([^"]+)"') 

class Tawizja(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        res = http.get(self.url)
        text = res.text 
        playlist_url = _RE_PLAYLIST.search(text).group(1) 
        if playlist_url.startswith("//"): playlist_url='http:'+playlist_url
        hls_streams = HLSStream.parse_variant_playlist(
            self.session,
            playlist_url,
            headers={'Referer': self.url, 'User-Agent': useragents.ANDROID}
        )
        for s in hls_streams.items():
            yield s

__plugin__ = Tawizja
`

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I looked at the "live" stream and it falls under several of the [categories for plugins we won't add](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests). Specifically 3, 6, and 10.

**Comment by bastimeyer** [comment]
> I have a plugin that worked on streamlink not long ago.
> `from streamlink.plugin.api import http`

https://github.com/streamlink/streamlink/issues/3460#issuecomment-751719069
