### ISSUE TITLE
Python API breaks when creating executable with pyinstaller

### ISSUE THREAD

**Issue by teiserse** [streamlink/streamlink#3501]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [x] I have read the contribution guidelines.

### Description

The main `streamlink.streams()` function works when used in a script, but breaks when it is compiled using pyinstaller.
My main guess is that the `load_plugins` function in `src/streamlink/session.py` which looks over the plugins using pkgutil simply doesn't see the plugins as they're not included in the executable.

I do not know if the issue comes from the code of the project or a lack of pyinstaller configuration on my end. If there's some additional pyinstaller configuration I need to make streamlink compatible with pyinstaller, please let me know (and preferably add the information into the docs for others to know)

### Expected / Actual behavior

Expected: The code runs without issue and the list of streams is retreived on both cases.
Actual behaviour: The code throws a NoPluginError on attempting to get the streams of any URL in the case of the executable created with pyinstaller.

### Reproduction steps / Explicit stream URLs to test

Here is my test script `main.py`:
```
import streamlink

if __name__ == '__main__':
    try:
        print(list(streamlink.streams("https://www.youtube.com/watch?v=huxQs2PCUTU")))
    except streamlink.exceptions.NoPluginError:
        print("NoPluginError caught.")
    input()
```

running `python main.py` gives you a list of stream types.
running pyinstaller and then the resulting executable prints the message on catching the exception.

pyinstaller is called by:
```
pyinstaller --noconfirm --onefile --console  "main.py"
```

**Comment by back-to** [comment]
> I do not know if the issue comes from the code of the project or a lack of pyinstaller configuration on my end.

**depends on how you want to fix it.**

you can make Streamlink compatible with pyinstaller or
you can make pyinstaller compatible with Streamlink

you can also search for some duplicates or maybe scripts to fix it

https://github.com/streamlink/streamlink/search?q=pyinstaller&type=issues
https://github.com/pyinstaller/pyinstaller/search?q=pkgutil&type=issues

---

> If there's some additional pyinstaller configuration I need to make streamlink compatible with pyinstaller

we can't help you with this, since we don't use pyinstaller here

---

Ref https://github.com/streamlink/streamlink/issues/669

**Comment by whdnjsgml** [comment]
You can porting a project containing streamlink with PyInstaller in the following way:

1. create spec file
```shell
pyi-makespec --console --onefile main.py
```

2. edit spec file
Open main.spec file and edit it as follows.
My streamlink is version 2.4.0, but it also conflicts with the iso639 package, so I added it.
```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules  # append

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas = collect_data_files('streamlink.plugins', include_py_files=True) + collect_data_files('iso639'), # edit
    hiddenimports = collect_submodules('streamlink.plugins'),   # edit
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
```

3. porting exe file
```shell
pyinstaller --clean main.exe.spec
```

**Comment by RTFM90172155** [comment]
You can porting a project containing streamlink with PyInstaller in the following way:

1. create spec file
```shell
pyi-makespec --console --onefile main.py
```

2. edit spec file
Open main.spec file and edit it as follows.
My streamlink is version 2.4.0, but it also conflicts with the iso639 package, so I added it.
```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules  # append

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas = collect_data_files('streamlink.plugins', include_py_files=True) + collect_data_files('iso639'), # edit
    hiddenimports = collect_submodules('streamlink.plugins'),   # edit
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico',
)
```

3. porting exe file
```shell
pyinstaller --clean main.exe.spec
```
