### ISSUE TITLE
Inclusion of prebuilt manpages in release tarballs

### ISSUE THREAD

**Issue by leio** [streamlink/streamlink#3507]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

This request is specifically for releases, not master branch, for downstream benefits.

### Description

It would be very good for me as a downstream packager of streamlink if release tarballs would contain prebuilt manpages (currently `streamlink.1`), that could simply be installed without depending on the whole sphinx stack for a mostly static rendering of a manpage. Perhaps a release tarball generating script could just build it during any CI or other steps and include it in the tarball?
Without this, I need to do this step manually for each version bump and host the prebuilt manual page myself, which can significantly delay the delivery of the new version package in the future, as more time needs to be allotted for the process.

### Expected / Actual behavior

A prebuilt `streamlink.1` is shipped inside release tarballs.

**Comment by bastimeyer** [comment]
I'm currently in the process of improving the man page situation (#3499). #3459 has already added the man page to the wheels which get uploaded to pypi, and you're right, it should be included in the tarballs as well. I'll take a look at it later today.
