### ISSUE TITLE
Can't record the video on the pandatv(https://www.pandalive.co.kr/live), is there a way to solve it? 

### ISSUE THREAD

**Issue by wei4430018** [streamlink/streamlink#3509]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
The plugin has been removed in #3071 after the site went offline. Is this a reboot or what is this?
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by mangopengo** [comment]
I think that this is a different site. I think the original pandatv was a Chinese streaming site. Pandalive.co.kr looks like a Korean streaming site with a similar name.
