### ISSUE TITLE
Youtube live stream

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#3511]
Hello

I was wondering if it would be possible to make the plugin fetch the stream when using the permanent url because the channel url seems to change every day or so. 

Example: 

France 24 channel : 
https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g
France 24 live channel 
https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live

Typical channel url (that streamlink is able to use but changes constantly) 
https://www.youtube.com/watch?v=A_fiWUjP6UI

streamlink -l debug https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.6.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live
error: Could not find a video on this page

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.6.0

Outdated

#3372

```
$ streamlink -l debug 'https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live'
[cli][debug] OS:         Linux-5.11.0-rc4-2-git-x86_64-with-glibc2.32
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0+24.gc5791f7
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCCCPCZNChQdGa9EkATeye4g/live
[plugins.youtube][debug] Video ID from currentVideoEndpoint
[plugins.youtube][debug] Using video ID: A_fiWUjP6UI
[plugins.youtube][debug] get_video_info - 1: Found data
[plugins.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
```

**Comment by campones** [comment]
thank you
