### ISSUE TITLE
Kanal D Stream not played (dogan: fix/update?)

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3515]
## Error Report

<! - Replace the space between the square brackets with an x ​​to activate the check boxes ->
- [x] This is a bug report and I have read the contribution guidelines.
- [x] I am using the latest development version from the main branch.

### Description

<! - Explain the mistake as thoroughly as possible. Do not leave out any information that is necessary to reproduce and correct this problem. ->

I would like to play the live stream from the channel D site via Streamlink. The broadcaster Kanal D transmits the live broadcast via this address https://www.kanald.com.tr/canli-yayin.

I ca nplay this via Firefox but no with Streamlink. There I get an erro

### Expected / actual behavior

<! - What do you expect and what will actually happen? ->

Screen stays black and does not display anything

### Replication Steps / Explicit Stream URLs to Test

<! - How can we reproduce that? Please note the exact steps in the specified list format. If you need further steps please add them. ->

Test the Site https: //www.kanald.com.tr/canli-yayin

### Log output

Last login: Tue Jan 26 10:50:30 CET 2021 on pts / 0
root @ dm920: ~ # / usr / sbin / streamlinksrv manualstart
[streamlinksrv] [info] Tue Jan 26 10:54:51 2021 Server (1.5.0) started
[streamlinksrv] [info] Streamlink: 1.27.1.0 / 2020-12-22
[streamlinksrv] [info] Processing URL: http://www.kanald.com.tr/canli-yayin
[streamlinksrv] [info] Found matching plugin dogan for URL
[streamlinksrv] [error] Unable to validate JSON: Unable to validate key 'data': Unable to validate key 'media': Unable to validate key 'link': Unable to validate key 'securePath': Type of u'https: / /kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true 'should be' str 'but is' unicode'
[streamlinksrv] [info] Processing URL: http://www.kanald.com.tr/canli-yayin
[streamlinksrv] [info] Found matching plugin dogan for URL
[streamlinksrv] [error] Unable to validate JSON: Unable to validate key 'data': Unable to validate key 'media': Unable to validate key 'link': Unable to validate key 'securePath': Type of u'https: / / kdliv ^ C [streamlinksrv] [info] Tue Jan 26 10:55:23 2021 Server stopped - Host: dm920, Port: 8088 but is' uniroot @ dm920: ~ #

**Comment by mkbloke** [comment]
The most recent update to the dogan plugin is working fine for me.
```
streamlink -l debug http://www.kanald.com.tr/canli-yayin 331k
[cli][debug] OS:         Linux-5.4.0-64-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.0.0+21.g92d7554
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogan for URL http://www.kanald.com.tr/canli-yayin
[plugins.dogan][debug] Found contentId by contentId regex
[plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[utils.l10n][debug] Language code: en_GB
[cli][info] Available streams: 331k (worst), 492k, 775k, 1013k (best)
[cli][info] Opening stream: 331k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 234292; Last Sequence: 234297
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 234295; End Sequence: None
[stream.hls][debug] Adding segment 234295 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 234296 to queue
[stream.hls][debug] Adding segment 234297 to queue
[stream.hls][debug] Download of segment 234295 complete
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --force-media-title=http://www.kanald.com.tr/canli-yayin -
[cli][debug] Writing stream to output
```

**Comment by bastimeyer** [comment]
```
$ streamlink -l debug 'https://www.kanald.com.tr/canli-yayin'
[cli][debug] OS:         Linux-5.11.0-rc5-1-git-x86_64-with-glibc2.32
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0+25.g7a74e18
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
[plugins.dogan][debug] Found contentId by contentId regex
[plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[utils.l10n][debug] Language code: en_US
Available streams: 331k (worst), 492k, 775k, 1013k (best)
```

**Comment by worldmediaman** [comment]
look here!

Dogan.py not work

PS C:\Users> streamlink https://www.kanald.com.tr/canli-yayin
[cli][info] Found matching plugin dogan for URL
https://www.kanald.com.tr/canli-yayin
error: Unable to open URL:
https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true
(404 Client Error: Not Found for url:
https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true
)
PS C:\Users> streamlink -l debug 'https://www.kanald.com.tr/canli-yayin'
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogan for URL
https://www.kanald.com.tr/canli-yayin
[plugins.dogan][debug] Found contentId by contentId regex
[plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[utils.l10n][debug] Language code: de_DE
error: Unable to open URL:
https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true
(404 Client Error: Not Found for url:
https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true
)

Am Di., 26. Jan. 2021 um 18:22 Uhr schrieb Sebastian Meyer <
notifications@github.com>:
