### ISSUE TITLE
Streaming huya.com to file - corrupt timecode

### ISSUE THREAD

**Issue by stefan327** [streamlink/streamlink#3519]
## Plugin Issue
(maybe it is a generel bug or broken and unrecoverable streams)

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Streaming huya.com to flv file.

In the resulting flv file the timecode is corrupt (with 9 of 10 streams), so it is not possible to seek the video with VLC media player.
Playing from start works. Using seekbar results in restart the video.

I use ffmpeg to create new timecodes (copy video and audio), after that I can seek the video perfectly.

Is it possible that streamlink creates the timecode correct while streaming to file, so that i dont have to repair the saved video flv file?

### Reproduction steps / Explicit stream URLs to test

1. save a stream from huya.com (some few streams have correct timecodes resp. seeking works)
2. play the flv file with VLC Player (or other player) and use seekbar or analyze the stream with ffmpeg (shows also wrong duration time)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> Is it possible that streamlink creates the timecode correct while streaming to file

only if you want to use ffmpeg with it

see https://github.com/streamlink/streamlink/issues/1527#issuecomment-370151934
