### ISSUE TITLE
MacOS homebrew install borked

### ISSUE THREAD

**Issue by thenameisdavid** [streamlink/streamlink#3520]
The given installation steps for installing on MacOS fail. Attempted multiple times.

ran: 

`brew install streamlink`

results:

```Downloading https://homebrew.bintray.com/bottles/streamlink-2.0.0_1.catalina.bottle.tar.gz

curl: (7) Couldn't connect to server
Error: Failed to download resource "streamlink"
Download failed: https://homebrew.bintray.com/bottles/streamlink-2.0.0_1.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://files.pythonhosted.org/packages/06/a9/cd1fd8ee13f73a4d4f491ee219deeeae20afefa914dfb4c130cfc9dc397a/certifi-2020.12.5.tar.gz

curl: (7) Couldn't connect to server
Error: Failed to download resource "streamlink--certifi"
Download failed: https://files.pythonhosted.org/packages/06/a9/cd1fd8ee13f73a4d4f491ee219deeeae20afefa914dfb4c130cfc9dc397a/certifi-2020.12.5.tar.gz

```

**Comment by bastimeyer** [comment]
Streamlink packages are maintained by third parties. This also includes the homebrew package, so if you're having a problem with installing it, open an issue on their issue tracker if you are sure that there's indeed a problem with the package:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/streamlink.rb

I don't see a problem here though, as the package is installing perfectly fine in a clean macOS VM on my system.

Make sure that your homebrew setup is working correctly and that your connection to the servers where the package resources are hosted is fine.
