### ISSUE TITLE
AnimeLab plugin not saving streams

### ISSUE THREAD

**Issue by PanopticEmu** [streamlink/streamlink#3521]
## Plugin Issue

- [x ] This is a plugin issue and I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description

When using the AnimeLab plugin on "best", streams close immediately after login is confirmed, causing the saved file to be about 2kb and have no content.

The other quality options work fine, just not "best". (where the available streams are 360p (worst), 480p, sd, 720p, 1080p, hd (best))

### Reproduction steps / Explicit stream URLs to test

1. open cli in your folder of choice
2. type `streamlink (animelab link) best -o "filename.mp4"` and hit enter.

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin animelab for URL https://www.animelab.com/player/by-the-grace-of-the-gods-trailer
[cli][debug] Plugin specific arguments:
[cli][debug]  --animelab-email=myemailaddress@email.com (email)
[cli][debug]  --animelab-password=******** (password)
[plugins.animelab][debug] Attempting to log in as myemailaddress@email.com
[plugins.animelab][info] Successfully logged in as myemailaddress@email.com
[plugins.animelab][debug] Found Japanese version with hard-subs
[cli][info] Available streams: 360p (worst), 480p, sd, 720p, 1080p, hd (best)
[cli][info] Opening stream: hd (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output

[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

### Additional comments, etc.
haven't used streamlabs in a few months, so I'm not sure when this actually broke, but I updated to the latest version of streamlabs and it still doesn't work. all I get is a 2kb file and then the stream crashes.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
`[cli][debug] Streamlink: 1.2.0` Can you provide logs using the latest release of Streamlink? This is very out of date.

**Comment by PanopticEmu** [comment]
weird. I made sure to install the latest version before testing... no idea why it's still using the old version. give me a bit to uninstall/reinstall and try again.

**Comment by PanopticEmu** [comment]
> `[cli][debug] Streamlink: 1.2.0` Can you provide logs using the latest release of Streamlink? This is very out of date.

@gravyboat any idea why it keeps using 1.2.0 when I uninstalled, deleted all the %appdata% stuff, and reinstalled using the latest installer?

**Comment by gravyboat** [comment]
@PanopticEmu Make sure after uninstalling that the `Streamlink` folder wherever you installed is fully deleted. It might not be getting totally removed.

**Comment by PanopticEmu** [comment]
@gravyboat found it. there was an old python script hiding away somewhere. same issue though: the HD (best) option still doesn't work.

**Comment by gravyboat** [comment]
@PanopticEmu Okay, let's see what the debug log output is then, modify your command to look like this: `streamlink -l debug (animelab link) best -o "filename.mp4"

**Comment by PanopticEmu** [comment]
@gravyboat 
`[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin animelab for URL https://www.animelab.com/player/by-the-grace-of-the-gods-trailer
[cli][debug] Plugin specific arguments:
[cli][debug]  --animelab-email=***@email.com (email)
[cli][debug]  --animelab-password=******** (password)
[plugins.animelab][debug] Attempting to log in as ***@email.com
[plugins.animelab][info] Successfully logged in as ***@email.com
error: Unable to open URL: https://www.animelab.com/player/by-the-grace-of-the-gods-trailer (503 Server Error: Service Temporarily Unavailable for url: https://www.animelab.com/player/by-the-grace-of-the-gods-trailer)`

works fine at other quality selections, just not that one

**Comment by gravyboat** [comment]
@PanopticEmu Something is wrong on their end: `error: Unable to open URL: https://www.animelab.com/player/by-the-grace-of-the-gods-trailer (503 Server Error: Service Temporarily Unavailable for url: https://www.animelab.com/player/by-the-grace-of-the-gods-trailer)`
 
A 503 means the server isn't handling the request properly, maybe they don't have the `hd` option set up properly somehow? I'm not really sure. This definitely isn't a Streamlink problem though, it's something going on with the animelab servers.

**Comment by PanopticEmu** [comment]
cool. thanks for the help.
