### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3522]
Let's create a Flatpak package for Streamlink.
https://docs.flatpak.org/en/latest/index.html

There have been lots of questions and issues regarding installing Streamlink on Ubuntu and Ubuntu-based Linux distros over the past couple of days/weeks, as the native packages are always outdated and the available PPA doesn't help on older distro releases. Also issues with py2/py3, which is confusing to some users, and `pip --user` is as well. A flatpak package could help here, as everything would be integrated into the package's environment/container.

----

I've already been working on a flatpak package build config and an initial version can be found here:
https://github.com/bastimeyer/io.github.streamlink.streamlink

#### Todo

- fix package issues
- bundle ffmpeg
- add CI build config
- add sign+deploy config

#### Issues

- Streamlink loses its version information when the package gets installed, but is working correctly when run from the build directory.
- Not sure how to work around the `/usr/bin/` filesystem portal limitation, so that system-wide players can be run by Streamlink from within the flatpak container. Can the system's `/usr/bin/` path be mapped to a different one and `PATH` extended?

Since I don't have much (or basically any) experience with Flatpak, I'd appreciate any kind of help.

**Comment by lekoOwO** [comment]
For the second issue, I used to be using `flatpak-spawn` to run commands outside the flatpak sandbox.
