### ISSUE TITLE
youtube url error

### ISSUE THREAD

**Issue by mooczhou** [streamlink/streamlink#3523]
When I used the command to get the video, I found some URLs, some URLs can successfully pull data, and some cannot successfully pull data. The command is as follows:
       streamlink  https://www.youtube.com/watch?v=WfXtXCQaN3Q best -o telnet2.mp4
error url：
       https://www.youtube.com/watch?v=WfXtXCQaN3Q
correct url:  
       https://www.youtube.com/watch?v=W_m16svIwFM
The error message is as follows:
       error: Unable to open URL: https://youtube.com/get_video_info (429 Client Error: unknown for url: https://youtube.com/get_video_info?video_id=WfXtXCQaN3Q&el=detailpage)

log:
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=lavDo9kGhVo
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[cli][error] Try 1/1: Could not open stream <Stream()> (Could not open stream: Unable to open URL: https://r3---sn-un57sn7z.googlevideo.com/videoplayback?expire=1612009175&ei=d_oUYOOxCMj2qAHShITwCA&ip=34.80.243.175&id=o-AFLwfrbdwuuC41xLx6jJm9vPdcHZzqWQ-BURqzxcjWUZ&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=Nw&mm=31%2C26&mn=sn-un57sn7z%2Csn-5go7yne6&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=3932500&vprv=1&mime=video%2Fmp4&ns=XRdKS_VL1mNcsGSa8lBByi4F&otf=1&otfp=1&dur=0.000&lmt=1602640100511563&mt=1611987401&fvip=3&keepalive=yes&c=WEB&n=0N18YyEaru0odTF5v&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgfsrOkTqpZnt_cgy1SidKgL9ItI0v06JAl6HxHRdyGscCIQCk4N5jHXmNKsNdTLVsT5UwAPbAZx69IC5w6GzixzrMbw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgFXJyVGDE4Pm_kZYSYUwBJ0W0T9wr8z6C70p5rr3plZkCICGnds1Qakn0GESeRSlQ1MPvXHITEZDhY5RyIAPwFK_2 (404 Client Error: Not Found for url: https://r3---sn-un57sn7z.googlevideo.com/videoplayback?expire=1612009175&ei=d_oUYOOxCMj2qAHShITwCA&ip=34.80.243.175&id=o-AFLwfrbdwuuC41xLx6jJm9vPdcHZzqWQ-BURqzxcjWUZ&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=Nw&mm=31%2C26&mn=sn-un57sn7z%2Csn-5go7yne6&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=3932500&vprv=1&mime=video%2Fmp4&ns=XRdKS_VL1mNcsGSa8lBByi4F&otf=1&otfp=1&dur=0.000&lmt=1602640100511563&mt=1611987401&fvip=3&keepalive=yes&c=WEB&n=0N18YyEaru0odTF5v&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgfsrOkTqpZnt_cgy1SidKgL9ItI0v06JAl6HxHRdyGscCIQCk4N5jHXmNKsNdTLVsT5UwAPbAZx69IC5w6GzixzrMbw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgFXJyVGDE4Pm_kZYSYUwBJ0W0T9wr8z6C70p5rr3plZkCICGnds1Qakn0GESeRSlQ1MPvXHITEZDhY5RyIAPwFK_2))
error: Could not open stream <Stream()>, tried 1 times, exiting

**Comment by gravyboat** [comment]
Please provide the full debug log output as noted in the issue template.

**Comment by mooczhou** [comment]
Related detailed logs have been provided, and comparison logs can also provide:
error:
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=lavDo9kGhVo
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[cli][error] Try 1/1: Could not open stream <Stream()> (Could not open stream: Unable to open URL: https://r3---sn-un57en7e.googlevideo.com/videoplayback?expire=1612184243&ei=U6YXYL2rIZmMs8IPn8ytoAg&ip=34.80.243.175&id=o-ACxRT7ea_ya2y3skFCSL2sslOge_uB_oZKD8wpsQ2nsw&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=Nw&mm=31%2C26&mn=sn-un57en7e%2Csn-5go7yne6&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=15355000&vprv=1&mime=video%2Fmp4&ns=UWXHAzDzuYGhatKo0Wr0Zb8F&otf=1&otfp=1&dur=0.000&lmt=1602640100511563&mt=1612162361&fvip=3&keepalive=yes&c=WEB&n=q6qeH4wmnQphkHHq0&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALdblReVdgN04-ZTKFn_nbgAj9lYoR8EWWpA_jnBMzFfAiAlxfmWyEeautsFlMUQWOn5fWzQtzsGx6q5vAsKzDuQFw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIga04Gk6Q_PT7BsVuJdByAr1v8C9vfJ7w_WJ0zG0dYxLYCIQDB-na7FvwDv-weJ5PgCnFTRQ8jc-ewyu0we_ue1Cef1A%3D%3D (404 Client Error: Not Found for url: https://r3---sn-un57en7e.googlevideo.com/videoplayback?expire=1612184243&ei=U6YXYL2rIZmMs8IPn8ytoAg&ip=34.80.243.175&id=o-ACxRT7ea_ya2y3skFCSL2sslOge_uB_oZKD8wpsQ2nsw&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=yt_otf&requiressl=yes&mh=Nw&mm=31%2C26&mn=sn-un57en7e%2Csn-5go7yne6&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=15355000&vprv=1&mime=video%2Fmp4&ns=UWXHAzDzuYGhatKo0Wr0Zb8F&otf=1&otfp=1&dur=0.000&lmt=1602640100511563&mt=1612162361&fvip=3&keepalive=yes&c=WEB&n=q6qeH4wmnQphkHHq0&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cotf%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALdblReVdgN04-ZTKFn_nbgAj9lYoR8EWWpA_jnBMzFfAiAlxfmWyEeautsFlMUQWOn5fWzQtzsGx6q5vAsKzDuQFw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIga04Gk6Q_PT7BsVuJdByAr1v8C9vfJ7w_WJ0zG0dYxLYCIQDB-na7FvwDv-weJ5PgCnFTRQ8jc-ewyu0we_ue1Cef1A%3D%3D))
error: Could not open stream <Stream()>, tried 1 times, exiting

correct
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=W_m16svIwFM
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[cli][error] File telnet1.mp4 already exists, use --force to overwrite it.
[cli][info] Closing currently open stream...
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-10778-68
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-10778-116

**Comment by lekoOwO** [comment]
This happens in my case too.

[20210202 【85万人耐久】85万人めざして歌うのをやめない！にぇ _ Karaoke aiming for 850,000 subs【ホロライブ_さくらみこ】 (XZFZzLqzmKU).1.log](https://github.com/streamlink/streamlink/files/5917533/20210202.85.85._.Karaoke.aiming.for.850.000.subs._.XZFZzLqzmKU.1.log)

**Comment by mooczhou** [comment]
The following error was encountered when pulling the live stream:

[stream.hls][error] Failed to open segment 13767: Unable to open URL: https://video-edge-7e9c84.hkg01.abs.hls.ttvnw.net/v1/segment/CuIEVZiVjRYO8OGfDWtrp4fpF2PVYT-YqoVQo_JYKmSwsG4dL4XWX46liM--joTngbLOboSx69gLpMXPpURcP_7FchkhFt-Fstavip3TTYMQ3xwSzlgALwnraDVCvqFVBLIn3LzwttUz1-5C5P7XIQG2AM4QlNCb6O5FZdjU3x5OR19TmhVwMYCrcTDvZ6ssChrfqJvyyqzrdSUN0ZI0p8KQc9O6wZcgXmI-cDp9vQ0A8MhDFfzQqutw2zcCOBSpEWpLWmqWqdttEfe1QFERCvpiiqbalU8hzs8Aeha1ofux22nOwm_fP07XYBg6d4st65QaTQymcLR-duQ_geUPz-WC2sX0RlZ_12cQ6weifbeYMM7TMVd8uoB4SUbQ3E-XYyIrEW7DSF02WVAO46_l7wPZPvGbMoY3S3kxeCErWkjV6TbTKkTE-3jLnE6K8uTAxtCHojAmHuLKUkPgX4vfMPFanfnYnPZ2JHSKQkOwuRLeUC6Df1h39RY6g_Fgk4aUymo-A7cjU0tELN2uXi0NxGLXyCjGTeX6kekUESruyrEUqX9ilTbeWp3U79abhfWvfY0TvXQ-2QFIjkdhZa3t5S0WGnFA_c4Ow_5HETYj-ersD980DRAQ2svdu_JaF29EBKGV_PhMOu9j-xEG_x4Pjccvsq7mH1cCKYqPxUgZTK3OZxVptfkdZcE9vr4aKmvla_QFyvp6INlD9W39BehGOfVmJ7wXPsiZi3qHcF6G_X0hpViAS-yrHc8maYjNdeCHj4YSIJYlZb3IeenLHi3cTFlOSLFTROqkeQWsVOXSgfsavD1gTRIQgApI7AP7Gl_KPkcBGi2N-RoM2VSTGDTu0oyPY5vc.ts (404 Client Error: Not Found for url: https://video-edge-7e9c84.hkg01.abs.hls.ttvnw.net/v1/segment/CuIEVZiVjRYO8OGfDWtrp4fpF2PVYT-YqoVQo_JYKmSwsG4dL4XWX46liM--joTngbLOboSx69gLpMXPpURcP_7FchkhFt-Fstavip3TTYMQ3xwSzlgALwnraDVCvqFVBLIn3LzwttUz1-5C5P7XIQG2AM4QlNCb6O5FZdjU3x5OR19TmhVwMYCrcTDvZ6ssChrfqJvyyqzrdSUN0ZI0p8KQc9O6wZcgXmI-cDp9vQ0A8MhDFfzQqutw2zcCOBSpEWpLWmqWqdttEfe1QFERCvpiiqbalU8hzs8Aeha1ofux22nOwm_fP07XYBg6d4st65QaTQymcLR-duQ_geUPz-WC2sX0RlZ_12cQ6weifbeYMM7TMVd8uoB4SUbQ3E-XYyIrEW7DSF02WVAO46_l7wPZPvGbMoY3S3kxeCErWkjV6TbTKkTE-3jLnE6K8uTAxtCHojAmHuLKUkPgX4vfMPFanfnYnPZ2JHSKQkOwuRLeUC6Df1h39RY6g_Fgk4aUymo-A7cjU0tELN2uXi0NxGLXyCjGTeX6kekUESruyrEUqX9ilTbeWp3U79abhfWvfY0TvXQ-2QFIjkdhZa3t5S0WGnFA_c4Ow_5HETYj-ersD980DRAQ2svdu_JaF29EBKGV_PhMOu9j-xEG_x4Pjccvsq7mH1cCKYqPxUgZTK3OZxVptfkdZcE9vr4aKmvla_QFyvp6INlD9W39BehGOfVmJ7wXPsiZi3qHcF6G_X0hpViAS-yrHc8maYjNdeCHj4YSIJYlZb3IeenLHi3cTFlOSLFTROqkeQWsVOXSgfsavD1gTRIQgApI7AP7Gl_KPkcBGi2N-RoM2VSTGDTu0oyPY5vc.ts)

**Comment by mooczhou** [comment]
When I pulled my live broadcast on twitch through live streaming, I found that the internet speed was not very stable when I pushed through local streaming. How can I optimize this situation?

**Comment by gravyboat** [comment]
You're getting a 404 client error on both Twitch and Youtube, this seems as though you're likely configuring something wrong. Are you using a proxy or some sort of non-standard setup? Try what @lekoOwO suggested with `-4`, but we're getting in to the weeds here from the original issue topic. I can't duplicate the Youtube problem nor the Twitch problem, and your issues related to having unstable internet speed when pushing through local streaming isn't something we can do anything about, that's a network or bandwidth issue.

**Comment by mooczhou** [comment]
> You're getting a 404 client error on both Twitch and Youtube, this seems as though you're likely configuring something wrong. Are you using a proxy or some sort of non-standard setup? Try what @lekoOwO suggested with `-4`, but we're getting in to the weeds here from the original issue topic. I can't duplicate the Youtube problem nor the Twitch problem, and your issues related to having unstable internet speed when pushing through local streaming isn't something we can do anything about, that's a network or bandwidth issue.

No proxy is used, the service is on Google Cloud

**Comment by back-to** [comment]
just use the `720p (http)` stream

it is an issue how Streamlink uses the DASH streams `1080p (muxed-stream)`,
but the issue would be fixed with https://github.com/streamlink/streamlink/issues/2936
