### ISSUE TITLE
Pixiv cookie issue

### ISSUE THREAD

**Issue by mythoRim** [streamlink/streamlink#3527]
## Bug Report

- [ X] This is a bug report and I have read the contribution guidelines.
- [ X] I am using the latest development version from the master branch.

### Description

There is a bug where age restricted streams can no longer be recorded which I believe is due to the change of the JSON. However, public streams are still recordable which I believe the issue might be something that involves the --pixiv-sessionid SESSIONID and --pixiv-devicetoken DEVICETOKEN.

### Expected / Actual behavior
note: 'userid' is a placeholder

**Expected**
Recording Streamlink
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@userid/lives
[cli][info] Available streams: 720p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[download][..userid-210131080750.mkv] Written 559.7 KB (0s @ 1.1 MB/s)

**Happening:**
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@userid/lives
error: No playable streams found on this URL: https://sketch.pixiv.net/@userid/lives

### Reproduction steps / Explicit stream URLs to test

1. Choose an r-15 or r-18 streamer that is currently livestreaming
2. streamlink --pixiv-sessionid {sessionid} --pixiv-devicetoken {devicetoken} https://sketch.pixiv.net/@{userid}/lives best --output output/{fileName}.mkv
3. It shows that it found the streamer but can't record it

### Log output
[plugins.pixiv][debug] Restored cookies: PHPSESSID, __cfduid, device_token, p_ab_d_id, p_ab_id, p                    _ab_id_2
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@userid/lives
[cli][debug] Plugin specific arguments:
[cli][debug]  --pixiv-sessionid=******** (sessionid)
[cli][debug]  --pixiv-devicetoken=******** (devicetoken)
[plugins.pixiv][debug] Attempting to authenticate using cached cookies
[plugins.pixiv][debug] Found 66 streams
error: No playable streams found on this URL: https://sketch.pixiv.net/@userid/lives

### Additional comments, etc.
I believe that something changed in the session id and device token in the end of January. I am still new to coding but I hope I got everything needed to find the issue. If it has anything relating to --pixiv-purge-credentials, then I did use it on one streamer but it didn't help me. I am new so I might be using --pixiv-purge-credentials wrongly and this might not even relate to this bug report. Thanks!

EDIT: I also tried using my other session ID and device token just to be sure as well as used the new one generated when I logged in but still same issue.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
**it works**,
get **new valid** cookies and run `--pixiv-purge-credentials`

```
$ streamlink --pixiv-sessionid 123456789_ABCDEFABCED --pixiv-devicetoken e123456 https://sketch.pixiv.net/@../lives/123 --pixiv-purge-credentials
[plugins.pixiv][debug] Restored cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
[cli][debug] OS:         Linux
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0+32.ga03f7bf
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@../lives/123
[cli][debug] Plugin specific arguments:
[cli][debug]  --pixiv-sessionid=******** (sessionid)
[cli][debug]  --pixiv-devicetoken=******** (devicetoken)
[cli][debug]  --pixiv-purge-credentials=True (purge_credentials)
[plugins.pixiv][info] All credentials were successfully removed.
[plugins.pixiv][debug] Saved cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
[plugins.pixiv][info] Successfully set sessionId and deviceToken
[plugins.pixiv][debug] Found 91 streams
[plugins.pixiv][debug] URL=https://hls.pixivsketch.net/././index.m3u8
[utils.l10n][debug] Language code: de_DE
[cli][info] Available streams: 720p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
```

**Comment by mythoRim** [comment]
> **it works**,
> get **new valid** cookies and run `--pixiv-purge-credentials`
> 
> ```
> $ streamlink --pixiv-sessionid 123456789_ABCDEFABCED --pixiv-devicetoken e123456 https://sketch.pixiv.net/@../lives/123 --pixiv-purge-credentials
> [plugins.pixiv][debug] Restored cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
> [cli][debug] OS:         Linux
> [cli][debug] Python:     3.8.6
> [cli][debug] Streamlink: 2.0.0+32.ga03f7bf
> [cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
> [cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@../lives/123
> [cli][debug] Plugin specific arguments:
> [cli][debug]  --pixiv-sessionid=******** (sessionid)
> [cli][debug]  --pixiv-devicetoken=******** (devicetoken)
> [cli][debug]  --pixiv-purge-credentials=True (purge_credentials)
> [plugins.pixiv][info] All credentials were successfully removed.
> [plugins.pixiv][debug] Saved cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
> [plugins.pixiv][info] Successfully set sessionId and deviceToken
> [plugins.pixiv][debug] Found 91 streams
> [plugins.pixiv][debug] URL=https://hls.pixivsketch.net/././index.m3u8
> [utils.l10n][debug] Language code: de_DE
> [cli][info] Available streams: 720p (worst), 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> ```

May I ask how you use --pixiv-purge-credentials the right way? I might have typed it wrongly.

**Comment by mythoRim** [comment]
> **it works**,
> get **new valid** cookies and run `--pixiv-purge-credentials`
> 
> ```
> $ streamlink --pixiv-sessionid 123456789_ABCDEFABCED --pixiv-devicetoken e123456 https://sketch.pixiv.net/@../lives/123 --pixiv-purge-credentials
> [plugins.pixiv][debug] Restored cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
> [cli][debug] OS:         Linux
> [cli][debug] Python:     3.8.6
> [cli][debug] Streamlink: 2.0.0+32.ga03f7bf
> [cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
> [cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@../lives/123
> [cli][debug] Plugin specific arguments:
> [cli][debug]  --pixiv-sessionid=******** (sessionid)
> [cli][debug]  --pixiv-devicetoken=******** (devicetoken)
> [cli][debug]  --pixiv-purge-credentials=True (purge_credentials)
> [plugins.pixiv][info] All credentials were successfully removed.
> [plugins.pixiv][debug] Saved cookies: PHPSESSID, __cf_bm, __cfduid, device_token, p_ab_d_id, p_ab_id, p_ab_id_2
> [plugins.pixiv][info] Successfully set sessionId and deviceToken
> [plugins.pixiv][debug] Found 91 streams
> [plugins.pixiv][debug] URL=https://hls.pixivsketch.net/././index.m3u8
> [utils.l10n][debug] Language code: de_DE
> [cli][info] Available streams: 720p (worst), 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> ```

Thanks @back-to! It works now and seem like maybe I used the --pixiv-purge-credentials the wrong way.
