### ISSUE TITLE
(afreecatv) could not find broadcast number.

### ISSUE THREAD

**Issue by dreamsparkbit** [streamlink/streamlink#3528]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

For some broadcasters (like http://play.afreecatv.com/ywfgeessd and http://play.afreecatv.com/dnjsdmsql94), an error message [plugins.afreeca][error] Could not find broadcast number. is displayed when trying to record.

### Reproduction steps / Explicit stream URLs to test

Due to large time differences, I use --retry-open and --retry-streams to check & record some broadcasters who stream when I am unable to watch. This works great for most broadcasters, but for one or two I get the "could not find broadcast number" error nonstop when Streamlink is checking to see if they are online.

### Log output

```
[cli][debug] OS:         macOS 10.16
[cli][debug] Python:     3.8.3
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.23.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin afreeca for URL http://play.afreecatv.com/ywfgeessd/
[cli][debug] Plugin specific arguments:
[cli][debug]  --afreeca-username=******** (username)
[cli][debug]  --afreeca-password=******** (password)
[plugins.afreeca][debug] Attempting to authenticate using cached cookies
[plugins.afreeca][error] Could not find broadcast number.
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> [plugins.afreeca][error] Could not find broadcast number. is displayed when trying to record.

The message might not be important for you, just ignore it.
