### ISSUE TITLE
error: Unable to open URL, (Caused by ProxyError

### ISSUE THREAD

**Issue by chenjy1** [streamlink/streamlink#3529]
### Description

I tried to get start with steamlink but, it does not work. I followed the installation guide, and failed when I try the command "streamlink twitch.tv/day9tv best"

System: Windows 10 64bit
Version: streamlink 2.0.0
Config: Default

### Log output

```
PS C:\Users\Administrator> streamlink twitch.tv/day9tv best
[cli][info] Found matching plugin twitch for URL twitch.tv/day9tv
error: Unable to open URL: https://gql.twitch.tv/gql (HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory'))))
```

**Comment by gravyboat** [comment]
@chenjy1 Please rerun your command with `-l debug` and provide the full debug output.

**Comment by bastimeyer** [comment]
> Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

https://urllib3.readthedocs.io/en/latest/reference/urllib3.exceptions.html#urllib3.exceptions.ProxyError

- https://github.com/urllib3/urllib3/blob/1.26.3/src/urllib3/connectionpool.py#L750-L751
- https://github.com/urllib3/urllib3/blob/1.26.3/src/urllib3/exceptions.py#L134-L137

Not a Streamlink issue. Fix your proxy settings.
