### ISSUE TITLE
plugin for https://www.popler.tv/live

### ISSUE THREAD

**Issue by richard173** [streamlink/streamlink#3531]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [ ] I am using the latest development version from the master branch.

### Example stream URLs

https://www.popler.tv/portal.php

https://www.popler.tv/tvdisco

1. ...
2. ...
3. ...

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [x] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugin submissions and requests are a great way to improve Streamlink. Requests should be as detailed as possible and dedicated to only a single streaming service. Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc. This allows for easier plugin review and implementation.

I only see stationary web cams on this site, and those kinds of sites won't be added to Streamlink:

> 11. Sites which are static cameras of a physical location

There have also been two other threads already regarding this site, although as questions for a 3rd party plugin:
https://github.com/streamlink/streamlink/issues?q=popler

----

Closing this until the necessary details have been provided.
