### ISSUE TITLE
WWE plugin no sound and 403 error

### ISSUE THREAD

**Issue by whitetop** [streamlink/streamlink#3536]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description
Started streamlinks again after dev of letmeatit hating bug reports, on server i get a 403 forbidden error but can rip on my home pc but no audio downloads just the video. 

### Reproduction steps / Explicit stream URLs to test

1. Does not work on proxy or server
2. works on main connection at home but still not from a uk proxy on main connection at home

### Log output

```

C:\Users\....\Desktop\streamlink-portable-master\Streamlink for Windows (Com
piled)\Releases>streamlink --wwenetwork-email  --wwenetwork-passw
ord  http://watch.wwe.com/episode/157384 504p -o wwe 205 .mp4
[Streamlink for Windows v2.0.0 - Git 8399986]
[cli][info] Found matching plugin wwenetwork for URL http://watch.wwe.com/episod
e/157384
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<html>\
r\n<head><title>403 Forbidd ...)
[End of Streamlink for Windows with ExitCode 1]

C:\Users\.....\Desktop\streamlink-portable-master\Streamlink for Windows (Com
piled)\Releases>timeout 30

Waiting for 28 seconds, press a key to continue ...
```
```
### Additional comments, etc.
(i'm not sure if cmd changed to rip)


[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
There's nothing we can do about you getting blocked while using a proxy or from some server, they probably blocked you on purpose. I don't know if anyone still has a WWE login to confirm the delay issue so we may be unable to confirm what is going on. Make sure to provide debug logging per the template requirements via `-l debug` in the command from the working connection.

**Comment by whitetop** [comment]
The debug gave me this, there is also no delay stated in my post its saying no audio. Hoping that is the debug stuff below.


C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Streamlink f
or Windows (Compiled)\Releases>streamlink --wwenetwork-email  --w
wenetwork-password  https://watch.wwe.com/episode/205-Live-157380 1080p
 -o 205.mp4 -l debug
[Streamlink for Windows v2.0.0 - Git 8399986]
Traceback (most recent call last):
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\Streamlink.py", line 10, in <m
odule>
    main()
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink_cli\main.py", line
1013, in main
    setup_streamlink()
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink_cli\main.py", line
749, in setup_streamlink
    streamlink = Streamlink({"user-input-requester": ConsoleUserInputRequester(c
onsole)})
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink\session.py", line 7
2, in __init__
    self.load_builtin_plugins()
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink\session.py", line 4
10, in load_builtin_plugins
    self.load_plugins(plugins.__path__[0])
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink\session.py", line 4
23, in load_plugins
    mod = load_module(module_name, path)
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink\utils\__init__.py",
 line 25, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Stre
amlink for Windows (Compiled)\Releases\Streamlink\streamlink\plugins\wwenetwork.
py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[End of Streamlink for Windows with ExitCode 1]

C:\Users\whitetop\Desktop\New folder\New streamlink-portable-master\Streamlink f
or Windows (Compiled)\Releases>timeout 30

Waiting for 28 seconds, press a key to continue ...

**Comment by back-to** [comment]
> on server i get a 403 forbidden error

streamlink is outdated or you are blocked.

> but can rip on my home pc

well, it works.

> but no audio downloads just the video.

don't use `streamlink-portable-master` it is unmaintained, **use something else**.
`ffmpeg` for your audio issue is missing there.

**Comment by whitetop** [comment]
> > on server i get a 403 forbidden error
> Yes i know that and ever proxy don't work
> streamlink is outdated or you are blocked.
> Nope it was the new version
> > but can rip on my home pc
> 
> well, it works.
> 
> > but no audio downloads just the video.
> 
> don't use `streamlink-portable-master` it is unmaintained, **use something else**.
> `ffmpeg` for your audio issue is missing there.
I am using something else, run a local proxy server then a ffmpeg script to rip, i was hoping streamlinks would work better but seems its still bugged and never to be fixed.
