### ISSUE TITLE
afreecatv.com 'Could not open stream' message

### ISSUE THREAD

**Issue by tdi2020** [streamlink/streamlink#3538]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Hi Guys,
It's my first time writing a post.I read the notice well, but I might be a little clumsy. Please understand.

Until now, I have created a bat file and downloaded afreecatv without any problems. 
However, from February 5, 2021, the error message as below appeared and it is no longer working. 
May I know what kind of problem this is and how to solve it?

I'm most curious about why it's not working well without any problems.
I swear I've never modified or touched anything since it worked.

The account I tested for this download is afreecatv.com/ayoona
But she doesn't have a constant broadcasting time.

### Reproduction steps / Explicit stream URLs to test

1. afreecatv.com/ayoona
2. ...
3. ...

### Log output

```
Checking for ayoona every 1.0 seconds. Record with best quality.
ayoona online. Stream recording in session.
[cli][info] Found matching plugin afreeca for URL play.afreecatv.com/ayoona
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.7FMfo2l7EMdIWtAZuuXvEBQQd_q-YyjRGX62o1ATvi-ToW2ayCpw8OuLDH-0PY5Qvj0kQQ98bpZN7IT0FBpd46hdh00hx0uBuxwd2YuynX8', None)> (Could not open stream: Unable to open URL: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.7FMfo2l7EMdIWtAZuuXvEBQQd_q-YyjRGX62o1ATvi-ToW2ayCpw8OuLDH-0PY5Qvj0kQQ98bpZN7IT0FBpd46hdh00hx0uBuxwd2YuynX8 (404 Client Error: Not Found for url: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.7FMfo2l7EMdIWtAZuuXvEBQQd_q-YyjRGX62o1ATvi-ToW2ayCpw8OuLDH-0PY5Qvj0kQQ98bpZN7IT0FBpd46hdh00hx0uBuxwd2YuynX8&aid=.A32.7bbT56vyHM9fKZk.7FMfo2l7EMdIWtAZuuXvEBQQd_q-YyjRGX62o1ATvi-ToW2ayCpw8OuLDH-0PY5Qvj0kQQ98bpZN7IT0FBpd46hdh00hx0uBuxwd2YuynX8))
error: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.7FMfo2l7EMdIWtAZuuXvEBQQd_q-YyjRGX62o1ATvi-ToW2ayCpw8OuLDH-0PY5Qvj0kQQ98bpZN7IT0FBpd46hdh00hx0uBuxwd2YuynX8', None)>, tried 1 times, exiting
Recording stream is done. Going back to checking..
ayoona online. Stream recording in session.
[cli][info] Found matching plugin afreeca for URL play.afreecatv.com/ayoona
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.OZiEZm4u7gvqcY7SwiEp-WXbrPqnVLE8nqsROUF3YLTyTHaV3LVb2wTGXZ3yVSKhtfLoUR-3MAxT4WBs9nl67Ou7IWt291mOoSqHg7HpC1Q', None)> (Could not open stream: Unable to open URL: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.OZiEZm4u7gvqcY7SwiEp-WXbrPqnVLE8nqsROUF3YLTyTHaV3LVb2wTGXZ3yVSKhtfLoUR-3MAxT4WBs9nl67Ou7IWt291mOoSqHg7HpC1Q (404 Client Error: Not Found for url: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.OZiEZm4u7gvqcY7SwiEp-WXbrPqnVLE8nqsROUF3YLTyTHaV3LVb2wTGXZ3yVSKhtfLoUR-3MAxT4WBs9nl67Ou7IWt291mOoSqHg7HpC1Q&aid=.A32.7bbT56vyHM9fKZk.OZiEZm4u7gvqcY7SwiEp-WXbrPqnVLE8nqsROUF3YLTyTHaV3LVb2wTGXZ3yVSKhtfLoUR-3MAxT4WBs9nl67Ou7IWt291mOoSqHg7HpC1Q))
error: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.OZiEZm4u7gvqcY7SwiEp-WXbrPqnVLE8nqsROUF3YLTyTHaV3LVb2wTGXZ3yVSKhtfLoUR-3MAxT4WBs9nl67Ou7IWt291mOoSqHg7HpC1Q', None)>, tried 1 times, exiting
Recording stream is done. Going back to checking..
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
run Streamlink with `--loglevel trace`

**Comment by pulbitz** [comment]
I have the same problem.
All afreecatv do not work.

Log output
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin afreeca for URL play.afreecatv.com/ayoona
[cli][debug] Plugin specific arguments:
[cli][debug]  --afreeca-username=******** (username)
[cli][debug]  --afreeca-password=******** (password)
[plugins.afreeca][debug] Attempting to login using username and password
[plugins.afreeca][debug] Saved cookies: AbroadChk, AbroadVod, PdboxBbs, PdboxSaveTicket, PdboxTicket, PdboxUser, RDB, _au, _ausa, _ausb, isBbs
[plugins.afreeca][info] Login was successful
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.En8xQ-95nT7jhiDnR2PoyJeHBxy3up125kUvA4NHwImqHYK7-dmf3hAnYaFc2i4RNE_ndFBAUjOnO-KYpvfQUsyBMsvECuvGt9EoR3yUY24', None)> (Could not open stream: Unable to open URL: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.En8xQ-95nT7jhiDnR2PoyJeHBxy3up125kUvA4NHwImqHYK7-dmf3hAnYaFc2i4RNE_ndFBAUjOnO-KYpvfQUsyBMsvECuvGt9EoR3yUY24 (404 Client Error: Not Found for url: http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.En8xQ-95nT7jhiDnR2PoyJeHBxy3up125kUvA4NHwImqHYK7-dmf3hAnYaFc2i4RNE_ndFBAUjOnO-KYpvfQUsyBMsvECuvGt9EoR3yUY24&aid=.A32.7bbT56vyHM9fKZk.En8xQ-95nT7jhiDnR2PoyJeHBxy3up125kUvA4NHwImqHYK7-dmf3hAnYaFc2i4RNE_ndFBAUjOnO-KYpvfQUsyBMsvECuvGt9EoR3yUY24))
error: Could not open stream <HLSStream('http://chromecast.afreeca.gscdn.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.En8xQ-95nT7jhiDnR2PoyJeHBxy3up125kUvA4NHwImqHYK7-dmf3hAnYaFc2i4RNE_ndFBAUjOnO-KYpvfQUsyBMsvECuvGt9EoR3yUY24', None)>, tried 1 times, exiting

**Comment by Taemni** [comment]
change the domain (m3u8 url)
http://chromecast.afreeca.gscdn.com -> http://pc-web.stream.afreecatv.com

add header (referer)
referer=http://play.afreecatv.com/{username}/{bno}

it work for me. (I am not good at English.)

**Comment by Taemni** [comment]
change the domain (m3u8 url)
http://chromecast.afreeca.gscdn.com -> http://pc-web.stream.afreecatv.com

-------------------------------------------------

CHANNEL_API_URL return CDN = 'gs_cdn', replace to 'gs_cdn_pc_web'

just my test code. it work. (I'm sorry. I am not good at English.)
```python
    def _get_stream_info(self, broadcast, quality, cdn, rmd):
        params = {
            # "return_type": cdn,
            "return_type": 'gs_cdn_pc_web',
            "broad_key": "{broadcast}-flash-{quality}-hls".format(**locals())
        }
        res = self.session.http.get(STREAM_INFO_URLS.format(rmd=rmd), params=params)
        return self.session.http.json(res, schema=_stream_schema)
```

**Comment by YoonHo-Lee** [comment]
I using Streamlink 2.0.0.
It's different from your code.

I tried to follow your code, but I failed... 
because print() or log.info() commands did not works in CMD.


How to fix it?



```Python
def _get_stream_info(self, broadcast, quality, cdn, rmd):
        params = {
            "return_type": cdn,
            "broad_key": f"{broadcast}-flash-{quality}-hls",
        }
        res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)

        print(res)                    # did not work
        log.info(res)               # did not work

        return self.session.http.json(res, schema=self._schema_stream)
```

**Comment by Taemni** [comment]
> I using Streamlink 2.0.0.
> It's different from your code.
> 
> I tried to follow your code, but I failed...
> because print() or log.info() commands did not works in CMD.
> 
> How to fix it?
> 
> ```python
> def _get_stream_info(self, broadcast, quality, cdn, rmd):
>         params = {
>             "return_type": cdn,
>             "broad_key": f"{broadcast}-flash-{quality}-hls",
>         }
>         res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)
> 
>         print(res)                    # did not work
>         log.info(res)               # did not work
> 
>         return self.session.http.json(res, schema=self._schema_stream)
> ```

I tried to install Streamlink 2.0.0 windows version. (I'm sorry. I am not good at English.)

change code on streamlink-2.0.0\pkgs\streamlink\plugins\afreeca.py
return_type: cdn -> 'gs_cdn_pc_web'
```python
    def _get_stream_info(self, broadcast, quality, cdn, rmd):
        params = {
            # "return_type": cdn,
            "return_type": 'gs_cdn_pc_web',
            "broad_key": f"{broadcast}-flash-{quality}-hls",
        }
        res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)
        return self.session.http.json(res, schema=self._schema_stream)
```

![work](https://user-images.githubusercontent.com/48712000/107139995-7d031e80-6962-11eb-972a-eecd41ede18d.png)

**Comment by YoonHo-Lee** [comment]
@Taemni 
oh, man!!! You are my savior!!! 😍

**Comment by tdi2020** [comment]
OMG I Love You Man!!!!! That's Work!!!!

> They changed the streaming domain. (m3u8 url)
> http://chromecast.afreeca.gscdn.com -> http://pc-web.stream.afreecatv.com
> 
> Changed code on streamlink-2.0.0\pkgs\streamlink\plugins\afreeca.py
> 
> CHANNEL_API_URL return CDN = 'gs_cdn', replace to 'gs_cdn_pc_web'
> 
> just my test code. it work. (I'm sorry. I am not good at English.)
> 
> ```python
>     def _get_stream_info(self, broadcast, quality, cdn, rmd):
>         params = {
>             # "return_type": cdn,
>             "return_type": 'gs_cdn_pc_web',
>             "broad_key": f"{broadcast}-flash-{quality}-hls",
>         }
>         res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)
>         return self.session.http.json(res, schema=self._schema_stream)
> ```

**Comment by chance473** [comment]
I changed the code and it works for short time but now I get Unable To Open URL and streamlink stops

`[stream.hls][error] Failed to open segment 5025: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/230872482-flash-original-hls_5024_0000001400DE00359414893BBE4456FE.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/230872482-flash-original-hls_5024_0000001400DE00359414893BBE4456FE.TS?aid=.A32.7bbT56vyHM9fKZk.AZx1U7tp_eIT8A5L5Pih7cl3Xc69XjodPzV77_vEI0YkN0QSzMNzSI-TDLm2WGXDnbVw3PU4NKFsDXRSqlVFlr7XqEJnVnyzxT-Sze-sCkI)
[stream.hls][error] Failed to open segment 5024: Unable to open URL: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/230872482-flash-original-hls_5023_000000D200A900068A5B4C64CC3289FD.TS (400 Client Error: Bad Request for url: http://pc-web.stream.afreecatv.com/live-stm-09/1920x1080/230872482-flash-original-hls_5023_000000D200A900068A5B4C64CC3289FD.TS?aid=.A32.7bbT56vyHM9fKZk.AZx1U7tp_eIT8A5L5Pih7cl3Xc69XjodPzV77_vEI0YkN0QSzMNzSI-TDLm2WGXDnbVw3PU4NKFsDXRSqlVFlr7XqEJnVnyzxT-Sze-sCkI)
[cli][info] Stream ended
[cli][info] Closing currently open stream...`

> They changed the streaming domain. (m3u8 url)
> http://chromecast.afreeca.gscdn.com -> http://pc-web.stream.afreecatv.com
> 
> Changed code on streamlink-2.0.0\pkgs\streamlink\plugins\afreeca.py
> 
> CHANNEL_API_URL return CDN = 'gs_cdn', replace to 'gs_cdn_pc_web'
> 
> just my test code. it work. (I'm sorry. I am not good at English.)
> 
> ```python
>     def _get_stream_info(self, broadcast, quality, cdn, rmd):
>         params = {
>             # "return_type": cdn,
>             "return_type": 'gs_cdn_pc_web',
>             "broad_key": f"{broadcast}-flash-{quality}-hls",
>         }
>         res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)
>         return self.session.http.json(res, schema=self._schema_stream)
> ```
