### ISSUE TITLE
Isvicre TV  inquiry 

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3540]
<! -
## Feature request

<! - Replace the space between the square brackets with an x to activate the check boxes ->
- [X] This is a feature request and I have read the contribution guidelines.
- [X] I'm using the latest development version from the main branch.

### Description

<! - Explain the function as clearly as possible. What is it, how would you expect it to work, and what value does it bring to Streamlink? ->

Turkish LIVESTREAM channel from Switzerland

### Expected / actual behavior

<! - What do you expect with this new function and what is currently happening that does not meet this need? ->

would like to play the swiss station via streamlink

https://www.isvicretv.com/canliyayin.html

### Additional comments etc.

[Dear Streamlink? Please remember to support our collective. Thanks!] (Https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
It's not a livestream, it's pre-recorded content that is being streamed on a schedule. It doesn't meet the requirements for a plugin.
