### ISSUE TITLE
dogan.py not work

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3543]
dogan.py not work 

PS C:\Users> streamlink https://www.kanald.com.tr/canli-yayin
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
error: Unable to open URL: https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true (404 Client Error: Not Found for url: https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true)
PS C:\Users> streamlink -l debug 'https://www.kanald.com.tr/canli-yayin'
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
[plugins.dogan][debug] Found contentId by contentId regex
[plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[utils.l10n][debug] Language code: de_DE
error: Unable to open URL: https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true (404 Client Error: Not Found for url: https://kdlive.duhnet.tv/S2/HLS_LIVE/kanaldnp/playlist.m3u8?&app=com.kanald&live=true)

_Originally posted by @worldmediaman in https://github.com/streamlink/streamlink/issues/3424#issuecomment-774559836_

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [ ] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [x] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [x] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [x] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [x] Other (see below)
* Other: Please do not post in multiple places such as closed issues or pull requests.  Opening a new issue is all that is necessary.  I see that you posted in a pull request that updated this plugin, yet you have not (it would appear) actually tried the updated plugin.
```
$ streamlink -l debug --locale de_DE https://www.kanald.com.tr/canli-yayin 331k
[cli][debug] OS:         Linux-5.4.0-65-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.0.0+26.g5bc29b1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin dogan for URL https://www.kanald.com.tr/canli-yayin
[plugins.dogan][debug] Found contentId by contentId regex
[plugins.dogan][debug] Loading content: 542410a361361f36f4c3fcf1
[utils.l10n][debug] Language code: de_DE
[cli][info] Available streams: 331k (worst), 492k, 775k, 1013k (best)
[cli][info] Opening stream: 331k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 332694; Last Sequence: 332699
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 332697; End Sequence: None
[stream.hls][debug] Adding segment 332697 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 332698 to queue
[stream.hls][debug] Adding segment 332699 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332700 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332701 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332702 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332703 to queue
[stream.hls][debug] Download of segment 332697 complete
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --force-media-title=https://www.kanald.com.tr/canli-yayin -
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332704 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 332705 to queue
[stream.hls][debug] Adding segment 332706 to queue
```

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by gravyboat** [comment]
Works perfectly fine for me. @worldmediaman I've deleted your spam from the other issues and am going to close this. There's nothing wrong with Streamlink, it's an incorrect with your setup that you need to fix.
