### ISSUE TITLE
How to streamlink download Youtube members only videos 

### ISSUE THREAD

**Issue by pammseyy** [streamlink/streamlink#3545]
## Bug Report

- [ x ] This is a bug report and I have read the contribution guidelines.
- [ x ] I am using the latest development version from the master branch.

### Description

How to streamlink download Youtube members only videos ? I've tried downloading it but it says " No playable streams found on this URL "

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
You can't because we don't support logins. Youtube-dl might support this.
