### ISSUE TITLE
live-tennis

### ISSUE THREAD

**Issue by musm** [streamlink/streamlink#3552]
## Plugin Request

- [x ] This is a plugin request and I have read the contribution guidelines and plugin request requirements.

### Description

https://live-tennis.stream

### Example stream URLs

1. https://live-tennis.stream/watch/egor-gerasimov-live-free.html

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 2. Sites which are hosting stolen content as their main source of content
> 3. Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)

----

> Disclaimer: None of the videos are hosted by this site. Streams hosted on external sites like Youtube and embedded here. This site is not responsible for the legality of the content. For legal issues, please contact appropriate media file owners/hosters.

https://live-tennis.stream/partners

**Comment by musm** [comment]
My bad!
