### ISSUE TITLE
Zattoo: error: No playable streams found on this URL:

### ISSUE THREAD

**Issue by AdamNo** [streamlink/streamlink#3553]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

since yesterday evening 09.02.2021 ~19:00 i am getting for all streams i.e.: "error: No playable streams found on this URL: https://zattoo.com/watch/orf-2"

### Reproduction steps / Explicit stream URLs to test

[tvheadend@tvheadend-4-2 ~/tmp]$ streamlink --zattoo-email=xxxXXXxxx --zattoo-password=xxxXXXxxx https://zattoo.com/watch/rt-doc best -o out.ts 
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/rt-doc
error: No playable streams found on this URL: https://zattoo.com/watch/rt-doc

### Log output

[tvheadend@tvheadend-4-2 ~/tmp]$ streamlink --zattoo-email=xxxXXXxxx --zattoo-password=xxxXXXxxx https://zattoo.com/watch/rt-doc best -o out.ts --loglevel debug
[cli][debug] OS:         FreeBSD-11.3-RELEASE-p14-amd64-64bit-ELF
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.0.0+40.gda0bfe9
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.56.0)
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/rt-doc
[cli][debug] Plugin specific arguments:
[cli][debug]  --zattoo-email=xxxXXXxxx (email)
[cli][debug]  --zattoo-password=******** (password)
[cli][debug]  --zattoo-stream-types=['hls'] (stream_types)
[plugins.zattoo][debug] _hello ...
[plugins.zattoo][debug] _login ... Attempting login as 5tu_sqoh9b6fp3kq@byom.de
[plugins.zattoo][debug] New Session Data
[plugins.zattoo][debug] Saved cookies: beaker.session.id, pzuid, zattoo.session
[plugins.zattoo][debug] _watch ...
[plugins.zattoo][debug] get channel ID for rt-doc
[plugins.zattoo][debug] Available zattoo channels in this country: 1fltv_li, 20_mediaset_it, 24h, 3plus, 3sat, 4plus, 4seven_uk, 5plus_ch, 5select, 5usa, 6plus_ch, 6ter, DE_arte, al-jazeera, al-jazeera-arabic, alma_tv_it, anixe_hd, anixe_plus, arirang_kr, arte-france, automotorsporttv, bbc-arabic, bbc-four, bbc-one, bbc-parliament, bbc-world-service, bbc2, bbc_news, becurioustv, bfmtv, bibeltv, bloomberg-europe, bloomberg_ht_tr, bntv, boing, br, br-alpha, bvn, canal9, canalalpha, canalalphajura, canale-5, canale_italia, cartoonito_it, cbbc, cbeebies, cem_tv_tr, challenge_uk, channel-4, chart_show_tv_uk, cherie25, cielo, class_tv_moda, clubland_tv, cmc, cmc, cnbc, cnn-international, cnn_turk, comedycentral, d17, daringtv, daserste, dave_uk, de_sixx, deluxe-music, deraktionaertv, deutsche-welle, deutschesmusikfernsehen, deutschewelle_ar, deutschewelle_de, deutschewelle_es, direct-8, disney, dmax, dmaxitalia, dmsat, drama_uk, dream_turk, e4, eotv, euronews-en, euronews-fr, euronews_italian, euronewsgerman, eurosport1, fashiontv, film4, five, focus_it, folx_tv_at, food_network_uk, france-2, france-24-en, france-24-fr, france-3, france-4, france-5, france_info, freesports_uk, frisbee_it, giallo_it, god-channel-tv, goldstar_tv, gotv_austria, gulli, gute_laune_tv, haber_turk, halk_tv, health_tv_de, heimatkanal, helvetia_one_tv_ch, hgtv_de, hr, hrt1, hrt4, hrt5, hse24, hse24_extra, hse24_trend, hustlerblue, hustlertv, i24news_english, i24news_french, i_tele, iris, italia-1, italia_2, itv-1-london, itv-2, itv-3, itv-4, itvbe, itvn, itvn_extra_pl, jukebox, k2_it, kabel-eins, kabel1_doku, kabel_eins_classics, kanal7avrupa, kanal9, kika, kinowelt, kiss_tv, klasik_tv_hr, klasik_tv_hr, kto, ktv, kuriakos_tv, la-7, la1, la2, la_5, la_7_d, latele, lci, lemanbleu, lequipe, lfm_tv_ch, m6-suisse, mdr-sachsen, melodie_tv_at, more4, motorvision_tv, mtv, mtvitalia, n-tv, n24_doku, nasa_tv, ndr-niedersachsen, netviet_vn, nick, nove_it, now90s, nrj-12, one, one_tv_ch, orf-1, orf-2, orf3, paramount_channel_it, paramount_network_uk, pbs_america, phoenix, pick_uk, pink_koncert_rs, pink_serije_rs, pink_world_rs, pinkextra, pinkfilm, pinkfolk, pinkkids, pinkmusic, pinkplus, pinkreality, planet, pro7_fun, pro7maxx_ch, prosieben, puls8, qs24_ch, r9_at, radio-bremen-tv, rai-due, rai-tre, rai-uno, rai_4, rai_5, rai_movie, rai_premium, rai_scuola, rai_sport, rai_sport_plus, rai_storia, rai_yoyo, raigulp, rainews, rbb, real_time_it, record_news, recordtv, rete-4, ric, rmc_story, rmcdecouverte, rocketbeans, romance_tv, rougetv, rt_doc, rtl, rtl-2, rtl102_5, rtl_plus, rtlnitro, rtp_3, rtp_internacional, rts_deux, rts_un, s1, s4c, sat1, sat1_emotions, sat1gold, servus_tv_deutschland, showmax_tr, sky_sport_news_de, sky_tg24_it, skynews-intl, sonlife, spiegel_geschichte, spiegeltvwissen, spike_italia, sport1, sr-fernsehen, srf1, srf_info, srf_zwei, startv, stingray_cmusic, super-rtl, super_it, supertennis_it, swiss_1, swr-fernsehen-bw, tagesschau24, tele-5, tele1, tele_top, telebaern, telebasel, telebielingue, teleclub_zoom, teleclub_zoom_fr, telem1, telepace, telesuedostschweiz, teleticino, telez, telezueri, tf1, tf1_series_films, tfx, tlc, tmc, toggo_plus, tr_euro_d, tr_euro_star, tr_show_turk, tv2000_it, tv24, tv25, tv5-monde, tv5mondefbs, tv8, tv8-mont-blanc, tv_oberwallis, tv_suisse_plus_ch, tve, tvm3, tvn24, tvo, uninettuno_it, vox, vox_up_de, w9suisse, wdr-koeln, welt, weltderwunder, wetter_tv, yesterday_uk, yourfamily, zdf, zdf-info, zdfneo
[plugins.zattoo][debug] CHANNEL ID: rt-doc
[plugins.zattoo][debug] Force session reset for watch_url
error: No playable streams found on this URL: https://zattoo.com/watch/rt-doc

### Additional comments, etc.

how to debug from here?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by AdamNo** [comment]
i just discovered that hls5 still works:

[tvheadend@tvheadend-4-2 ~/tmp]$ streamlink --zattoo-email=xxxXXXxxx --zattoo-password=xxxXXXxxx --zattoo-stream-type hls5 https://zattoo.com/watch/sf-1 best -o out.ts   
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/sf-1
[cli][info] Available streams: 224p_alt2 (worst), 224p_alt, 224p, 288p_alt2, 288p_alt, 288p, 432p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
File out.ts already exists! Overwrite it? [y/N] ^CInterrupted! Exiting...
[cli][info] Closing currently open stream...

[tvheadend@tvheadend-4-2 ~/tmp]$ streamlink --zattoo-email=xxxXXXxxx --zattoo-password=xxxXXXxxx --zattoo-stream-type hls https://zattoo.com/watch/sf-1 best -o out.ts 
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/sf-1
error: No playable streams found on this URL: https://zattoo.com/watch/sf-1

**Comment by treki1** [comment]
For me works the option:
--zattoo-stream-type dash

**Comment by NoWhere2Go19** [comment]
If I'm using the CLI it is working with `--zattoo-stream-type hls5`. However how would initiate it in the API? I tried
`SLSESSION = Streamlink()
SLSESSION.set_plugin_option("zattoo", "email", options.LOGIN)
SLSESSION.set_plugin_option("zattoo", "password", options.LOGINPW)
SLSESSION.set_plugin_option("zattoo", "stream-types", ['hls5', 'dash'])`

but I always get if logged `Available streams: OrderedDict()` or when not using the `set_plugin_option `then I get an empty streams dict `{}`

Any ideas?

**Comment by dober2** [comment]
I have the same issue since about a month now. Is there any workaround?

**Comment by back-to** [comment]
@dober2 

`--zattoo-stream-types dash`

https://streamlink.github.io/latest/cli.html#cmdoption-zattoo-stream-types
