### ISSUE TITLE
test_cmdline: use unittest.mock instead of mock if possible

### ISSUE THREAD

**Issue by Coacher** [streamlink/streamlink#356]
test_plugin_api_http_session does this right: https://github.com/streamlink/streamlink/blob/f29b08c58cc2a83c09f1bf1100a190ff68e4d616/tests/test_plugin_api_http_session.py#L6

Please do the same here: https://github.com/streamlink/streamlink/blob/f29b08c58cc2a83c09f1bf1100a190ff68e4d616/tests/test_cmdline.py#L9

**Comment by beardypig** [comment]
A sensible suggestion.

**Comment by beardypig** [comment]
Updated for ya.
