### ISSUE TITLE
Plugin request: HRT Croatia

### ISSUE THREAD

**Issue by jkfa2** [streamlink/streamlink#3561]
## Issue

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

HRT is the national public broadcaster of Croatia. Their online streams are available after logging in on their platform.

### Example stream URLs

1. https://hrti.hrt.hr/live/tv

**Comment by worldmediaman** [comment]
i want this too, but not work in germany

Sadržaj nije dostupan zbog ograničenih autorskih prava!
