### ISSUE TITLE
Plugin for bilibili returns unusable url.

### ISSUE THREAD

**Issue by Ivanfangsc** [streamlink/streamlink#3564]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

1. `streamlink --stream-url https://live.bilibili.com/545072 best` returns a url.
2. `ffmpeg -i "{the url}" -codec copy -f mpegts xxx.ts` raises `HTTP error 403 Forbidden`.
3. The problem appears consistently over multiple room ids and multiple hosts both in and out of Mainland China.

### Log output

```
root@xxx:~# streamlink --stream-url https://live.bilibili.com/545072 best --loglevel debug
https://d1--cn-gotcha05.bilivideo.com/live-bvc/260982/live_9838560_5622882.flv?cdn=cn-gotcha05&expires=1613204993&len=0&oi=2632587632&pt=web&qn=10000&trid=60e11c5b6913434da6850c17cdae3f4c&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=7b19bb5de709ed65214e808893842128&ptype=0&src=5&sl=2&order=1
```

**Comment by back-to** [comment]
well you don't use Streamlink for the stream

```
  "headers": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "Accept-Encoding": "gzip, deflate",
    "Accept": "*/*",
    "Connection": "keep-alive",
    "Referer": "https://live.bilibili.com/545072"
  },
```

but you will need to use **http headers** with your ffmpeg command

you can get them with the `--json` command
