### ISSUE TITLE
Booyah.live

### ISSUE THREAD

**Issue by potterface** [streamlink/streamlink#3567]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Booyah.live is a gaming streaming platfmorm, just like Twitch. It also hosts the official broadcast of the Loading TV channel online.

### Example stream URLs

1. https://booyah.live/loading52x
2. https://booyah.live/nfa
3. https://booyah.live/levelup

### Additional comments, etc.

No login required, no DRM, no geo-block.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by tnafele** [comment]
Does it also handle this kind of links: https://booyah.live/vods/xxxxx ?
Since a few weeks Booya is recording most streams and you can watch them later on from URLs like above...
