### ISSUE TITLE
TLC.py not work

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3569]
## Error Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] I am using the latest development version from the main branch.

### Description

I would like to play the TLC Turkey live stream via Streamlink in Germany

### Expected / actual behavior

<! - What do you expect and what will actually happen? ->

When I open the page via Firefox I can see the live stream
Unfortunately not via Streamlink.

### Replication Steps / Explicit Stream URLs to Test

<! - How can we reproduce that? Please note the exact steps in the specified list format. If you need further steps please add them. ->

Open https: //www.tlctv.com.tr/canli-izle

Please look through a browser, I can see the live stream.

Then via Streamlink

### Log output

streamlink -l debug https://www.tlctv.com.tr/canli-izle
[cli] [debug] OS: Windows 10
[cli] [debug] Python: 3.8.6
[cli] [debug] Streamlink: 2.0.0
[cli] [debug] Requests (2.25.1), Socks (1.7.1), Websocket (0.57.0)
[cli] [info] Found matching plugin tlctr for URL https://www.tlctv.com.tr/canli-izle
[plugins.tlctr] [debug] URL = https: //dygvideo.dygdigital.com/live/hls/tlctv? token = VGcxK0ptK2dQbURrNVpxS3JtVDNtSnNqYkhvVjdrL25zTlJ4dUUzcGNiND0 = & toslND0e =
[utils.l10n] [debug] Language code: de_DE
Available streams: 180p (worst), 270p, 576p, 720p (best)

streamlink -l debug https://www.tlctv.com.tr/canli-izle best
[cli] [debug] OS: Windows 10
[cli] [debug] Python: 3.8.6
[cli] [debug] Streamlink: 2.0.0
[cli] [debug] Requests (2.25.1), Socks (1.7.1), Websocket (0.57.0)
[cli] [info] Found matching plugin tlctr for URL https://www.tlctv.com.tr/canli-izle
[plugins.tlctr] [debug] URL = https: //dygvideo.dygdigital.com/live/hls/tlctv? token = Vk9QZHhaWjBRN0NmVDJxZG96Vm1YUkVrVG95ZjFrSm1MOE1QSHF0ZHhQlcz0e = & opens token_type = & opens token_type =
[utils.l10n] [debug] Language code: de_DE
[cli] [info] Available streams: 180p (worst), 270p, 576p, 720p (best)
[cli] [info] Opening stream: 720p (hls)
[stream.hls] [debug] Reloading playlist
[stream.hls] [debug] First Sequence: 0; Last Sequence: 9
[stream.hls] [debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: 9
[stream.hls] [debug] Adding segment 0 to queue
[cli] [debug] Pre-buffering 8192 bytes
[stream.hls] [debug] Adding segment 1 to queue
[stream.hls] [debug] Adding segment 2 to queue
[stream.hls] [debug] Adding segment 3 to queue
[stream.hls] [debug] Adding segment 4 to queue
[stream.hls] [debug] Adding segment 5 to queue
[stream.hls] [debug] Adding segment 6 to queue
[stream.hls] [debug] Adding segment 7 to queue
[stream.hls] [debug] Adding segment 8 to queue
[stream.hls] [debug] Adding segment 9 to queue
[stream.segmented] [debug] Closing worker thread
[stream.hls] [debug] Download of segment 0 complete
[cli] [info] Starting player: "C: \ Program Files \ VideoLAN \ VLC \ vlc.exe"
[cli.output] [debug] Opening subprocess: "C: \ Program Files \ VideoLAN \ VLC \ vlc.exe" - input-title-format https://www.tlctv.com.tr/canli-izle -
[stream.hls] [debug] Download of segment 1 complete
[stream.hls] [debug] Download of segment 2 complete
[stream.hls] [debug] Download of segment 3 complete
[stream.hls] [debug] Download of segment 4 complete
[stream.hls] [debug] Download of segment 5 complete
[stream.hls] [debug] Download of segment 6 complete
[stream.hls] [debug] Download of segment 7 complete
[cli] [debug] Writing stream to output
[stream.hls] [debug] Download of segment 8 complete
[stream.hls] [debug] Download of segment 9 complete
[stream.segmented] [debug] Closing writer thread
[cli] [info] Stream ended
[cli] [info] Closing currently open stream ...

### Additional comments etc.

Please take a look Thank you

**Comment by gravyboat** [comment]
Can't duplicate this from the US, it works perfectly fine for me. Try a different video player.

**Comment by bastimeyer** [comment]
The site is showing a region-locked content placeholder. This is not a Streamlink issue. Try using a proxy server via the available options.

**Comment by worldmediaman** [comment]
thas not correct! I can see the live stream in germany!

Am Di., 16. Feb. 2021 um 21:40 Uhr schrieb Sebastian Meyer <
notifications@github.com>:

**Comment by worldmediaman** [comment]
[image: LIVESTREAM.JPG]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Di., 16. Feb. 2021 um 21:58 Uhr schrieb Sanal Dünya <
worldmediaman@gmail.com>:

**Comment by mkbloke** [comment]
It looks like the current web player is using a different master playlist URL and params to the existing plugin:
```
https://dogus.daioncdn.net/tlc/tlc.m3u8?ce=3&app=1aca0aa1-06e3-41ff-a8e5-38d7df475469&token=<val>=&dfp_paln=<val>
```
I'll have a look at it...

**Comment by worldmediaman** [comment]
danke

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Di., 16. Feb. 2021 um 22:22 Uhr schrieb Ian Cameron <
notifications@github.com>:

**Comment by mkbloke** [comment]
@worldmediaman, can you still play the content via the web player from a German IP?  I can no longer play content with AR or UK IPs, although I could before...

**Comment by bastimeyer** [comment]
German IPs now also show the region lock screen on their site. I'm closing the thread.
Thanks for trying to fix the plugin though, @mkbloke!

**Comment by ramazansancar** [comment]
https://github.com/streamlink/streamlink/commits/master/src/streamlink/plugins/tlctr.py

https://github.com/streamlink/streamlink/pull/4432

The relevant PR and git history show that tlc and dmax have been removed.

Static links were provided, but they are no longer valid.
