### ISSUE TITLE
SSH101 TV

### ISSUE THREAD

**Issue by worldmediaman** [streamlink/streamlink#3571]
## Error Report

- [X] This is a bug report and I have read the contribution guidelines.
- [X] I'm using the latest development version from the main branch.

### Description

I want to play live streams from SSH101

### Expected / actual behavior

As soon as I play a live stream from the SSH101 , the picture / sound stops after 30 seconds.

### Replication Steps / Explicit Stream URLs to Test

<! - How can we reproduce that? Please note the exact steps in the specified list format. If you need further steps please add them. ->

Example:

Go to https://ssh101.com/detail.php?id=shovvplus

test the link there:

https://www.ssh101.com/securelive/index.php?id=shovvplus'

### Log output

streamlink https://www.ssh101.com/securelive/index.php?id=shovvplus best
[cli] [info] Found matching plugin ssh101 for URL https://www.ssh101.com/securelive/index.php?id=shovvplus
[cli] [info] Available streams: live (worst, best)
[cli] [info] Opening stream: live (hls)
[cli] [info] Starting player: "C: \ Program Files \ VideoLAN \ VLC \ vlc.exe"
error: Error when reading from stream: Read timeout, exiting
[cli] [info] Stream ended
[cli] [info] Closing currently open stream ...

another stream:

[streamlinksrv] [info] Processing URL: https://www.ssh101.com/securelive/index.php?id=ABTelevision2020
[streamlinksrv] [debug] url args: []
[streamlinksrv] [info] Found matching plugin ssh101 for URL
[plugin.ssh101] [debug] URL = https: //tna5.bozztv.com/ABTelevision2020/index.m3u8
[utils.l10n] [debug] Language code: en_US
[streamlinksrv] [info] Available streams:
live (worst, best)
[streamlinksrv] [info] Opening stream: live (hls) '
[stream.hls] [debug] Reloading playlist
[stream.hls] [debug] Segments in this playlist are encrypted
[stream.hls] [debug] First Sequence: 160; Last Sequence: 167
[stream.hls] [debug] Start offset: 0; Duration: None; Start Sequence: 165; End Sequence: None
[stream.hls] [debug] Adding segment 165 to queue
[streamlinksrv] [debug] Pre-buffering 8192 bytes
[stream.hls] [debug] Adding segment 166 to queue
[stream.hls] [debug] Adding segment 167 to queue
[stream.hls] [debug] Download of segment 165 complete
[streamlinksrv] [debug] Writing stream to player
[stream.hls] [debug] Download of segment 166 complete
[stream.hls] [debug] Download of segment 167 complete
[stream.hls] [debug] Reloading playlist
[stream.hls] [debug] Segments in this playlist are encrypted
[stream.hls] [debug] Adding segment 168 to queue
[stream.hls] [debug] Reloading playlist
[stream.hls] [debug] Segments in this playlist are encrypted
[stream.hls] [debug] Adding segment 169 to queue
[stream.hls] [debug] Reloading playlist
[stream.hls] [debug] Segments in this playlist are encrypted

### Additional comments etc.

Yesterday it still worked, since today the picture and sound no longer work.

**Comment by mkbloke** [comment]
> error: Error when reading from stream: Read timeout, exiting

That would seem to indicate a network or server issue.  I've played both streams for >5 minutes each without any problems.

**Comment by worldmediaman** [comment]
strange that many users write that it doesn't work. it doesn't work with me either. how did you play the stream and what is your address like?

**Comment by mkbloke** [comment]
I just played them with:
```
streamlink -l debug https://www.ssh101.com/securelive/index.php?id=shovvplus best
streamlink -l debug https://www.ssh101.com/securelive/index.php?id=ABTelevision2020 best
```
I'm on an Argentine IP address via broadband that I have not seen go over ~20Mbit/s, so nothing special.

**Comment by gravyboat** [comment]
> strange that many users write that it doesn't work.strange that many users write that it doesn't work.

I don't see a single report of this on our issue tracker in the last 2 years. If you're using Streamlink in your own application it is not our job to help maintain your software, Streamlink works fine so I'm closing this.

**Comment by worldmediaman** [comment]
look here https://www.dreamosat-forum.com/board/index.php?thread/9446-streamlink-27-installer/&postID=123291#post123291
