### ISSUE TITLE
plugins.onetv: All channels except 1tv don't work

### ISSUE THREAD

**Issue by mgibert-bmat** [streamlink/streamlink#3587]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Want to get stream from onetv channels in Russia. With a Russian IP, so geobocked issue is discarded.
The only channel I manage to record is 1tv.ru. The rest don't work.

### Reproduction steps / Explicit stream URLs to test

1. streamlink "https://chetv.ru/online/"
2. streamlink "https://ctc.ru/online/"
3. streamlink "https://domashniy.ru/online/"
4. 

### Log output

```
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-136-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin onetv for URL https://chetv.ru/online/
[plugins.onetv][debug] Loading live stream for ctc-che...
error: Unable to open URL: https://media.1tv.ru/api/v1/ctc/playlist/ctc-che_as_array.json (404 Client Error: Not Found for url: https://media.1tv.ru/api/v1/ctc/playlist/ctc-che_as_array.json)
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Post a debug log
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/1_plugin_issue.md#L47-L58

**Comment by mgibert-bmat** [comment]
Hi @bastimeyer , 
Debug log is updated now. 
Thanks!
