### ISSUE TITLE
plugins.euronews:  the stream replaced with youtube

### ISSUE THREAD

**Issue by vstavrinov** [streamlink/streamlink#3589]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

The plugin doesn't work now as the stream on https://www.euronews.com/live is replaced with youtube embedded https://youtu.be/sPgqEHsONK8 . I don't know is it a permanent or a temporary decision. There are cases of moving back. So I don't think the plugin should be removed but rather suspended in some way or temporarily disabled. 
### Reproduction steps / Explicit stream URLs to test

```
streamlink euronews.com/live
```
### Log output

```
[cli][info] Found matching plugin euronews for URL euronews.com/live
error: Unable to validate JSON: Unable to validate key 'url': Type of None should be 'str' but is 'NoneType'
```

### Additional comments, etc.

You can watch this TV channel on youtube or with streamlink:
```
streamlink youtube.com/EuronewsUSA/live
```
It exists for a long time and the only regret is that resolution reduced from 1080p to 720p.

**Comment by bastimeyer** [comment]
Only the live stream has moved to YT, VODs are still hosted on their site, which means the plugin can't be removed.
