### ISSUE TITLE
Streamlink dropping frames after

### ISSUE THREAD

**Issue by alvv-z** [streamlink/streamlink#3591]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch. - I can't find a place to download it, or how to compile it to a binary

### Description

When watching 60fps streams, after a few minutes (sometimes sooner or after buffering) the framerate in mpv gets choppy, drops to about half and stays there.

### Expected / Actual behavior

To run at 60fps

### Reproduction steps / Explicit stream URLs to test

1. Open a 60fps link (e.g. a twitch stream)
2. Wait
3. Playback gets choppy

### Log output

```
[cli][debug] OS:         Linux-5.8.0-44-generic-x86_64-with-glibc2.32
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.23.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL https://twitch.tv/northernlion
[plugins.twitch][debug] Getting live HLS streams for northernlion
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 1181; Last Sequence: 1187
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1185; End Sequence: None
[stream.hls][debug] Adding segment 1185 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1186 to queue
[stream.hls][debug] Adding segment 1187 to queue
[cli][info] Starting player: mpv
[stream.hls][debug] Download of segment 1185 complete
[cli.output][debug] Opening subprocess: mpv --force-media-title=https://twitch.tv/northernlion -
[stream.hls][debug] Download of segment 1186 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1187 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1188 to queue
[stream.hls][debug] Adding segment 1189 to queue
[stream.hls][debug] Download of segment 1188 complete
[stream.hls][debug] Download of segment 1189 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1190 to queue
[stream.hls][debug] Download of segment 1190 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1191 to queue
[stream.hls][debug] Adding segment 1192 to queue
[stream.hls][debug] Download of segment 1191 complete
[stream.hls][debug] Download of segment 1192 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1193 to queue
[stream.hls][debug] Download of segment 1193 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1194 to queue
[stream.hls][debug] Adding segment 1195 to queue
[stream.hls][debug] Download of segment 1194 complete
[stream.hls][debug] Download of segment 1195 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1196 to queue
[stream.hls][debug] Download of segment 1196 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1197 to queue
[stream.hls][debug] Adding segment 1198 to queue
[stream.hls][debug] Download of segment 1197 complete
[stream.hls][debug] Download of segment 1198 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1199 to queue
[stream.hls][debug] Download of segment 1199 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1200 to queue
[stream.hls][debug] Adding segment 1201 to queue
[stream.hls][debug] Download of segment 1200 complete
[stream.hls][debug] Download of segment 1201 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1202 to queue
[stream.hls][debug] Download of segment 1202 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1203 to queue
[stream.hls][debug] Adding segment 1204 to queue
[stream.hls][debug] Download of segment 1203 complete
[stream.hls][debug] Download of segment 1204 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1205 to queue
[stream.hls][debug] Download of segment 1205 complete
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
I can't duplicate this on a Windows system. I'm watching a Twitch stream right now that is 1080p60. What does your full Streamlink command look like? Do you encounter the same issue on 720p60? I've seen this happen before when the system isn't buffering segments quickly enough though usually it's immediately apparent.

**Comment by bastimeyer** [comment]
> When watching 60fps streams, after a few minutes (sometimes sooner or after buffering) the framerate in mpv gets choppy, drops to about half and stays there.

Streamlink is not a video renderer. If you're having framerate issues while decoding/rendering a video, then check your player, its settings and your system configuration. Streamlink is only responsible for the data transport, and network issues of regular unmuxed HLS streams don't affect the video framerate.

https://streamlink.github.io/cli.html#cmdoption-verbose-player

Closing, since it's not a Streamlink issue.

**Comment by alvv-z** [comment]
I think it is a streamlink issue. It slows down my system quite a bit. There are no dropped frames and no slow down of my system when watching youtube or twitch vods in 60fps, only twitch streams as far as I can tell. I tried with `--verbose-player` and that only shows the amount of dropped frames. I suspect the framedrops are a consequence of the system slowdown.

**Comment by alvv-z** [comment]
Might this be a plugin issue?

**Comment by bastimeyer** [comment]
Streamlink doesn't do any transcoding or remuxing of the stream data. It only appends HLS segments according to the HLS spec and outputs a progressive stream, which is piped into your player's stdin.

Once again, if you're having decoding or rendering issues (as in framerate issues for example), then try writing Streamlink's output to the filesystem (see `--output` or `--stdout`) and then check the file with your player afterwards.

**Comment by alvv-z** [comment]
I will try that, thanks!
