### ISSUE TITLE
can we have a trojan-free release please ?

### ISSUE THREAD

**Issue by skywalk1411** [streamlink/streamlink#3593]
https://www.virustotal.com/gui/file/999e3cb4c4cb1015d845a21c1429740f8e78b1cf3e65ca1c1696d5f803c748e1/detection

why even bother release something when its filled with trojan.

even if the reply I bet I will have is... false positive!!!

dont release false positives shit either.

regards
someone who want to use that app

**Comment by Tsaukpaetra** [comment]
So two out of 67 antivirus thinks it *might be* malware and you say therefore it is a trojan? That's quite funny!

**Comment by skywalk1411** [comment]
> 
> 
> So two out of 67 antivirus thinks it _might be_ malware and you say therefore it is a trojan? That's quite funny!

Well, Ive been into cryptocurrency for a while, '09 to be precise, and I wont under any circumstance install something on my windows box with anything flagged as malicious. positive, false positive, false negative, I dont care what the gender trend of positive or negative it is nowadays with liberals, but a positive is a positive in my book,s and when you get two positive, it doesnt cancel itself like math 101.

**Comment by bastimeyer** [comment]
- https://github.com/streamlink/streamlink/blob/2.0.0/script/makeinstaller.sh
- https://github.com/streamlink/streamlink/runs/1594102579

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/discussions/3449#discussioncomment-241939
