### ISSUE TITLE
plugins.ine: No plugin can handle URL

### ISSUE THREAD

**Issue by xflyboy** [streamlink/streamlink#3606]
## Plugin Issue
- [ x ] This is a plugin issue and I have read the contribution guidelines.
### Description

Trying to download INE.COM cources. (my user id already have valid license)
For instance: https://my.ine.com/INE/courses/9e5b2567/introduction-to-networking-technologies
The videos are opened on same page.
using "streamlink https://my.ine.com/INE/courses/9e5b2567/introduction-to-networking-technologies --http-cookie laravel_session=REMOVED" gives following worning: "error: No plugin can handle URL: https://my.ine.com/INE/courses/9e5b2567/introduction-to-networking-technologies"

### Reproduction steps / Explicit stream URLs to test

Listed above.

### Log output

```
streamlink https://my.ine.com/INE/courses/9e5b2567/introduction-to-networking-technologies --http-cookie laravel_session=REMOVED --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
error: No plugin can handle URL: https://my.ine.com/INE/courses/9e5b2567/introduction-to-networking-technologies
```

**Comment by bastimeyer** [comment]
> No plugin can handle URL

This has nothing to do with the cookies you've set. The plugin simply expects a different input URL. If this URL scheme/format doesn't exist (anymore), then the site has made changes which broke the plugin.

- https://github.com/streamlink/streamlink/blob/a2b97c99e4ee3d009822b2742618fc9af0e0f7f4/src/streamlink/plugins/ine.py#L14-L16
- https://github.com/streamlink/streamlink/blob/a2b97c99e4ee3d009822b2742618fc9af0e0f7f4/src/streamlink/plugins/ine.py#L33-L35

**Comment by xflyboy** [comment]
It seems like so, The videos are shown on my.ine.com site. Tired to inspect element and was not able to get direct link.
not sure if that will help: _https://github.com/Jayapraveen/INE-courses-downloader

Please ask INE plugin developers to assist. Thanks.

**Comment by artiction** [comment]
```
streamlink -l debug 'https://www.youtube.com/watch?v=Uxxt_LnUIR4

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url='https://www.youtube.com/watch?v=Uxxt_LnUIR4
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
error: No plugin can handle URL: 'https://www.youtube.com/watch?v=Uxxt_LnUIR4
```

**Comment by gravyboat** [comment]
@artiction This is totally off topic and has nothing to do with this issue so I've hidden it. In addition I can't duplicate it with other videos. If you can provide a reproducible use case with a publicly available URL create a new issue with the appropriate logging and details.
