### ISSUE TITLE
Add new command line option to ignore DRM protected 

### ISSUE THREAD

**Issue by 10362227** [streamlink/streamlink#3614]
some video (****.m3u8  / ***.mpd) are DRM-Protected, i can crack them, i need to download, but streamlink download failed,

**Comment by gravyboat** [comment]
We're not going to support DRM circumvention.

**Comment by 10362227** [comment]
> We're not going to support DRM circumvention.

i know, I mean i can crack DRM, but i need to download video with streamlink first

**Comment by mkbloke** [comment]
I don't think what you're asking for is even possible with a lot of the DRM schemes.  With things like key rotation, you'd have to download the encryption metadata and associate it with the relevant segments, so I do not believe it's possible to just download all the segments to one video file that you can later decrypt with a simple 'DRM crack'.  It's not something Streamlink will support, as gravyboat has already told you.

**Comment by 10362227** [comment]
> I don't think what you're asking for is even possible with a lot of the DRM schemes. With things like key rotation, you'd have to download the encryption metadata and associate it with the relevant segments, so I do not believe it's possible to just download all the segments to one video file that you can later decrypt with a simple 'DRM crack'. It's not something Streamlink will support, as gravyboat has already told you.

I downloaded segments and cracked using mp4decrypt
