### ISSUE TITLE
facebook plugin not working

### ISSUE THREAD

**Issue by jordonia** [streamlink/streamlink#3615]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

facebook plugin not finding playable streams anymore

### Reproduction steps / Explicit stream URLs to test

```
streamlink -l debug https://www.facebook.com/disguisedtoast/videos/1373769286324573
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0+52.ga2b97c9
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/disguisedtoast/videos/1373769286324573
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/disguisedtoast/videos/1373769286324573
```

### Log output

```
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.0.0+52.ga2b97c9
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
Hmm, kind of strange, as it's working for me right now with exactly the same version as you from master:
```
$ streamlink -l debug https://www.facebook.com/disguisedtoast/videos/1373769286324573 
[cli][debug] OS:         Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.0.0+52.ga2b97c9
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/disguisedtoast/videos/1373769286324573
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
[utils.l10n][debug] Language code: en_GB
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
[utils.l10n][debug] Language code: en_GB
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
Available streams: 144p_alt (worst), 144p, 240p_alt, 240p, 360p_alt, 360p, 480p_alt, 480p, 720p_alt2, 720p_alt, 720p (best)
```

It plays OK too.

**Comment by mkbloke** [comment]
Seems like it might be region specific.  The above was from a UK IP, but with an AR IP:
```
$ streamlink -l debug https://www.facebook.com/disguisedtoast/videos/1373769286324573 
[cli][debug] OS:         Linux-5.4.0-66-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.0.0+52.ga2b97c9
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/disguisedtoast/videos/1373769286324573
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/disguisedtoast/videos/1373769286324573
```

**Comment by jordonia** [comment]
Whew I'm not going crazy

**Comment by mkbloke** [comment]
It looks like:
https://github.com/streamlink/streamlink/blob/c51ab2f623a0cc22a949e487bc88ad790d21b27b/src/streamlink/plugins/facebook.py#L129-L133
returns:
```
[plugins.facebook][debug] for (;;);{"__ar":1,"error":1357005,"errorSummary":"Your Request Couldn't be Processed","errorDescription":"There was a problem with this request. We're working on getting it fixed as soon as we can.","payload":null,"hsrp":{"hblp":{"sr_revision":1003481094,"consistency":{"rev":1003481094}}},"lid":"6941468047634899055"}
```
for some IPs, but is working with a UK IP for now...

**Comment by jordonia** [comment]
This appears to be resolved for me
`streamlink -l debug https://www.facebook.com/VaderLive/videos/887308278851573 
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 2.2.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.facebook.com/VaderLive/videos/887308278851573
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/VaderLive/videos/887308278851573
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: NONE (using: n/a)
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p_alt, 1080p (best)`

**Comment by mkbloke** [comment]
Good to know, thanks for coming back on this.  It continues to be an issue for others playing other videos, unfortunately.

**Comment by Deadstreamer** [comment]
I was doing some testing and ran into this issue when I tried downloading too many streams within a short time period from the same ip. It resolves after a few hours or after you change IP address.
