### ISSUE TITLE
streamline configuration file options

### ISSUE THREAD

**Issue by emacs25** [streamlink/streamlink#3623]
## Issue

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [ ] I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

platform:        windows 
streamlink:     python3 pip installation newest version

  1. can not read the configuration file created by hand in default location
  2. can the proxy option be wrote into configuration file?

### Expected / Actual behavior

  1.  is there a way to customize location of configration file freely on windows platform?
  2.  how to add proxy option into configuration file?

### Reproduction steps / Explicit stream URLs to test

1.  as default steps
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
All log output should go between two blocks of triple backticks (grave accents) for proper formatting.
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by beardypig** [comment]
proxy can be set in a config, for example:

```
http-proxy=http://localhost:8118
https-proxy=http://localhost:8118
```

You can set the configuration path with the [`--config`](https://streamlink.github.io/cli.html#cmdoption-config) option. 

Can you tell me where you created the config file that it is not reading?

**Comment by emacs25** [comment]
the config file path i create is %APPDATA%\streamlink\streamlinkrc

and i use:

```
streamlink.exe --config "d:\streamlink\myconfig" http://xxx.xx/xxxxxx best
```
it still doesn't work!

**Comment by gravyboat** [comment]
@emacs25 You're using 2 different paths for the config file.

**Comment by emacs25** [comment]
sorry i describe it clearly again!

the config file path i create is %APPDATA%\streamlink\streamlinkrc which streamlink.exe cannot read it.

the config file include play path and http proxy option

so i move the streamlinkrc to d:\streamlink\myconfig, then use the command:

```
streamlink.exe --config "d:\streamlink\myconfig" http://xxx.xx/xxxxxx best
```

 it still can't play the stream url, and the reason is that streamlink does not find http proxy

**Comment by bastimeyer** [comment]
> the config file path i create is %APPDATA%\streamlink\streamlinkrc which streamlink.exe cannot read it.

As you can see here, the default config location hasn't been changed in years and is working correctly:
https://github.com/streamlink/streamlink/blame/10470c3586d28de83ac59aa2b97568778635376f/src/streamlink_cli/constants.py#L23-L26

> the config file includes player path and http proxy option
> it still can't play the stream url, and the reason is that streamlink does not find http proxy

You must have misconfigured it and probably used an invalid format. Post the **entire** config file, or nobody will be able to help.

Take a look at the docs regarding the syntax:
https://streamlink.github.io/cli.html#configuration-file
