### ISSUE TITLE
"Pipe copy aborted" error when using the "best" stream

### ISSUE THREAD

**Issue by AbakumovAlexandr** [streamlink/streamlink#3625]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

When downloading a video from YouTube using the `best` quality option, I'm getting a "Pipe copy aborted" error near the end of the download:
When downloading the same video of one step lower in quality, it downloads without any errors.

### Expected / Actual behavior

No errors duing the download.

### Reproduction steps / Explicit stream URLs to test

1. Execute the following command: `streamlink https://youtu.be/Eh9Fxo-29d8 best -o "/mnt/TEMP/test.mp4"`
2. Wait until about 402MB is downloaded.
3. "Pipe copy aborted" error is displayed.

Try to execute the same command replacing `best` with `720p` and the video would be downloaded without any errors.

### Log output

```
[cli][debug] OS:         Linux-5.10.0-4-amd64-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 2.0.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin youtube for URL https://youtu.be/Eh9Fxo-29d8
[plugins.youtube][debug] Video ID from URL
[plugins.youtube][debug] Using video ID: Eh9Fxo-29d8
[plugins.youtube][debug] get_video_info - 1: Found data
[plugins.youtube][debug] MuxedStream: v 137 a 251 = 1080p
[plugins.youtube][debug] MuxedStream: v 135 a 251 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 251 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 251 = 144p
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[stream.ffmpegmux][debug] Opening http substream
[stream.ffmpegmux][debug] Opening http substream
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/ffmpeg-17511-396 -i /tmp/ffmpeg-17511-288 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-17511-396
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/ffmpeg-17511-288
[cli][debug] Pre-buffering 8192 bytes
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[download][test.mp4] Written 403.6 MB (16m47s @ 451.7 KB/s)
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/ffmpeg-17511-396
```

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/3523#issuecomment-787047891

https://github.com/streamlink/streamlink/issues/2936

**Comment by kg** [comment]
Hi @back-to , the resolution in 3523 is 'just use the 720p (http) stream' but I'm not seeing any http options in videos, just a bunch of resolutions. Is there a specific command line argument we should pass to streamlink to ensure that it picks a quality level that can be successfully downloaded? For example:

```
>streamlink https://www.youtube.com/watch?v=KCzjQ4qP124 best -o ffx.mp4
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=KCzjQ4qP124
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 720p60, 1080p60, 1440p60, 2160p60 (best)
[cli][info] Opening stream: 2160p60 (muxed-stream)
[utils.named_pipe][info] Creating pipe streamlinkpipe-6068-1-4888
[utils.named_pipe][info] Creating pipe streamlinkpipe-6068-2-679
[download][ffx.mp4] Written 2.07 GB (10m6s @ 3.5 MB/s)                                                                                                         [stream.ffmpegmux][error] Pipe copy aborted: \\.\pipe\streamlinkpipe-6068-2-679
[download][ffx.mp4] Written 2.07 GB (10m7s @ 3.4 MB/s)
<hangs indefinitely>
```

For this video 1440p60 and 1080p60 are both also muxed-stream, so I don't know how to figure out which option I should select to get a http stream.

Thanks!

**Comment by danepedersen** [comment]
For me, I coped the desired stream format and it worked.  For example, in my case the 720p stream was the "720p+a192k", so I copied that and put it in the place of "best" and now it works.

Hope that helps.
