### ISSUE TITLE
plugins.twitch: Streamlink sometimes fails to realize when a stream has ended

### ISSUE THREAD

**Issue by KynikossDragonn** [streamlink/streamlink#3628]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Most of the time, the twitch plugin in streamlink seems to not realize a streamer stopped their stream, and will attempt to reload a now non-existant m3u8 playlist up to 20 times before giving up. I say most of the time because, I can't gauge how and when this happens, it seems to occur almost 98% of the time. It doesn't matter who's stream I'm watching, nor does it matter if they have Affiliate status or Twitch Partnership. It also does not seem to matter if they have the "Stream stability" option checked either.

This is with the current latest version: 2.0.0

### Reproduction steps / Explicit stream URLs to test

1. View any streamer on twitch, doesn't matter if they're affiliate or partner as far as I know.
2. Wait for them to end the stream for any reason.
3. Streamlink will either realize the stream ended and close, or it will get stuck repeating up to 20 times to reload the m3u8 playlist.

### Log output

```
$ streamlink twitch.tv/djdarchon
[cli][info] Found matching plugin twitch for URL twitch.tv/djdarchon
[cli][info] Available streams: audio_only, 720p (worst, best)
[cli][info] Opening stream: 720p (hls)
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 1)
[cli][info] Starting player: mpv --really-quiet --cache=no
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://video-weaver.ord03.hls.ttvnw.net/v1/playlist/Co8EhAnjZ3ZXZTuH0CkzWJP3mJLQgBQSbT1KfNZn9J3UozVgvUUB-p0Yb0ylqC1F2OAZglkmiMOxqCiXh2qT9cbKgAJN3HRq51Bbmp7lLS5TNpgs-1rwV8klwaXXTJ2x0JO3-8kRmLiA0SyqGJEziXDTRbuNmFuh7CkAZZZsw6u7e3Gi3DlyxAeXsfq41BnyBvT9WUam7C7tYRqYuLYXU2ZdfiSowbPnP8LEhnK-uoKQ-bUWWtjK5cJddIQKbPtrh7THl9zBwxdiBK4ni4kAaO0Z32PRg_-WDt5iCTeXkOkCzNPTLyTcZjND-Vnvxut_nmzkD3CeVW_Y6KmbpSFXs7FB0v2P7lcorYlHG5xJg66SVk2G88x8EBtBc7MPzQnFK20LncI_6ZhnPebPNE-dVcxx4avVz1aEuQBPpnye1x6Ve_bFn327sB_nz8FX_VTJFFDf5utbeIKf24LoZ6MB4bcQJgHvjdG0-N2C9YyJTW2Bfg-tjorIG-nYLuBXCTB8UogSVN3LDl6FvPBFplWNP27yg1_QETcFLcm4rjfLTfYqAlVPyLr_vfObcUsMxdienQAF0UM87lD2phzzp29mpwaYHnJWkVfLYEJL3FEaR2fsxnHfgVrbCz_arP_jQLZiw2dLiTzWO1J1l4-jgSTTBximRmLPv4McZnVHF54QQgWUf6Bwyw7pPEv31BOJPFaFAtsSENz_2NciR2JhXsMRc1RGm7IaDGRbRjix0im5AqWuxQ.m3u8 (404 Client Error: Not Found for url: https://video-weaver.ord03.hls.ttvnw.net/v1/playlist/Co8EhAnjZ3ZXZTuH0CkzWJP3mJLQgBQSbT1KfNZn9J3UozVgvUUB-p0Yb0ylqC1F2OAZglkmiMOxqCiXh2qT9cbKgAJN3HRq51Bbmp7lLS5TNpgs-1rwV8klwaXXTJ2x0JO3-8kRmLiA0SyqGJEziXDTRbuNmFuh7CkAZZZsw6u7e3Gi3DlyxAeXsfq41BnyBvT9WUam7C7tYRqYuLYXU2ZdfiSowbPnP8LEhnK-uoKQ-bUWWtjK5cJddIQKbPtrh7THl9zBwxdiBK4ni4kAaO0Z32PRg_-WDt5iCTeXkOkCzNPTLyTcZjND-Vnvxut_nmzkD3CeVW_Y6KmbpSFXs7FB0v2P7lcorYlHG5xJg66SVk2G88x8EBtBc7MPzQnFK20LncI_6ZhnPebPNE-dVcxx4avVz1aEuQBPpnye1x6Ve_bFn327sB_nz8FX_VTJFFDf5utbeIKf24LoZ6MB4bcQJgHvjdG0-N2C9YyJTW2Bfg-tjorIG-nYLuBXCTB8UogSVN3LDl6FvPBFplWNP27yg1_QETcFLcm4rjfLTfYqAlVPyLr_vfObcUsMxdienQAF0UM87lD2phzzp29mpwaYHnJWkVfLYEJL3FEaR2fsxnHfgVrbCz_arP_jQLZiw2dLiTzWO1J1l4-jgSTTBximRmLPv4McZnVHF54QQgWUf6Bwyw7pPEv31BOJPFaFAtsSENz_2NciR2JhXsMRc1RGm7IaDGRbRjix0im5AqWuxQ.m3u8)

(Previous message repeated 19 times)

error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, etc.

I'm sorry that's not a debug log, the next time I'm watching someones stream to the end I'll have full debug verbosity enabled.

My streamlink config is as follows:
```
player=mpv --really-quiet --cache=no
player-no-close
hls-live-edge=1
hls-segment-threads=3
hls-segment-attempts=1
hls-playlist-reload-attempts=1
ringbuffer-size=1M
twitch-disable-hosting
twitch-disable-ads
twitch-disable-reruns
twitch-low-latency
default-stream=360p,480p,best
;player-passthrough=hls,http,rtmp
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
That's not a Twitch plugin issue and rather an issue with the HLS playlist.

Playlist reloads after the stream has ended only happen when there's no [`#EXT-X-ENDLIST`](https://tools.ietf.org/html/rfc8216#section-4.3.3.4) tag added to the HLS playlist. It's the responsibility of the server to let the clients know that it has ended, and if the tag is missing, then Streamlink simply isn't able to know when to stop, so it proceeds with refreshing the playlist.

From my experience, this does only happen on Twitch if the streamer hasn't shut down their stream properly, eg. when there's a connection issue between the streamer and Twitch's ingest servers, or when there's an issue somewhere in their network.

----

> If the Media Playlist contains the final Media Segment of the presentation, then the Playlist file MUST contain the EXT-X-ENDLIST tag; this allows clients to minimize unproductive Playlist reloads.

https://tools.ietf.org/html/rfc8216#section-6.2.1

**Comment by KynikossDragonn** [comment]
I wonder if OBS is the culprit somehow, if maybe "Stop streaming" isn't properly signaling to Twitch's ingest that the stream's over so it thinks there's still more to the stream than there is.

Is there a way I could atleast, tell streamlink to give up after the first 404? Those lines in my config for `hls-segment-attempts` and `hls-playlist-reload-attempts` don't seem to have any effect.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/2198
