### ISSUE TITLE
Streamlink Pixiv feature request

### ISSUE THREAD

**Issue by mythoRim** [streamlink/streamlink#3629]
## Feature Request

- [X ] This is a feature request and I have read the contribution guidelines.
- [ X] I am using the latest development version from the master branch.

### Description

I am thinking of having a feature that **makes a new video file instead of overwriting** the video file automatically.

I have been using Streamlink to leave my computer overnight or when I go to work to look over the stream on a later date. However, I find there is a discrepancy that happens when the Pixivstream service does a restart due to **server maintenance** that the "--force" would rewrite the previous stream record video (In other words, a stream that went for 3 hours only recorded the latter half like 30 minutes after the server maintenance and when the streamer ends). I use "--force" since I can't manually answer the "file exist. Overwrite {Y/N]" as I am away from the computer or concentrating  working and it would stop Streamlink from recording. 

here is what I write:
streamlink --pixiv-sessionid placeholderSI --pixiv-devicetoken placeholderDT https://sketch.pixiv.net/@placeholderUser/lives best --output output/{fileName}.mkv --force --pixiv-purge-credentials'

### Additional comments, etc.
Thanks for reading! I did attempt to solve the problem myself by doing an external check if the file exist but I think the problem is within the Streamlink code itself. Basically was trying [If file increment 1 exist, then write the new file called file increment 2]

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> Streamlink Pixiv feature request

Writing the output stream to the filesystem has nothing to do with the plugin- or stream system. It's a feature of the CLI module.

Use the shell to set custom file names. This has been answered on this issue tracker lots of times already.

macOS / Linux / BSD:
```bash
$ streamlink --output "$(date +"file_%Y%m%d%H%M%S")" URL STREAM
```

Windows:
https://superuser.com/questions/512163/using-date-and-times-in-a-batch-file-to-create-a-file-name
