### ISSUE TITLE
Gonet.TV/Lepsi.TV

### ISSUE THREAD

**Issue by staszek1503** [streamlink/streamlink#3641]
Is there anyone capable of the new Gonet.TV/Lepsi.TV plugin?
Information that I managed to get + account, interested persons please contact us by e-mail staszek1503@onet.pl

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [x] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [x] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by staszek1503** [comment]
@ mkbloke 
So what information exactly should I provide, sorry for the inconvenience but I do not understand I translate myself into Polish

**Comment by mkbloke** [comment]
https://translate.google.com/translate?sl=en&tl=pl&u=https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md%23plugin-requests

**Comment by staszek1503** [comment]
@mkbloke 138 / 5000
Wyniki tłumaczenia
Is it about exact links to streams?
If so, then in this case I cannot publish them here because they contain an individual token

**Comment by mkbloke** [comment]
Proper links to the sites and content available in a web player at least.

A quick look seems to show that these sites are TV channels, which are not live as the project maintainers deem to be properly live content.  In addition to that, it would seem like this is a subscription based service?

**Comment by staszek1503** [comment]
Hello Gonet.tv is a website with live channels, the stream with drm contains a variable token, so login is needed, it is m3u8 stream. After pasting such a link, e.g. to the decoder with E2 (Linux), the channel works only for some time. The next problem is that the channels are available only in HD (h264 codec) via the browser, while the channels are available in Full HD (h265 codec) via applications for android / ios and smart tv Due to the variable token, I cannot provide the link. Of course, the aforementioned service works as subscribers. If you are interested, I can provide an account.
W dniu 2021-03-22 00:10:52 użytkownik Ian Cameron ***@***.***> napisał:
 
Proper links to the sites and content available in a web player at least.
A quick look seems to show that these sites are TV channels, which are not live as the project maintainers deem to be properly live content. In addition to that, it would seem like this is a subscription based service?

**Comment by mkbloke** [comment]
Thanks for the update.  So, I think this means this plugin request does not meet the requirements under rules 1, 4, and 6.

**Comment by staszek1503** [comment]
@mkbloke So I am to understand that there is no chance of adding this plugin

**Comment by mkbloke** [comment]
In this case, I'm afraid not.  The only DRM currently supported by Streamlink is AES-128 in HLS streams.  On top of that, plugins based on subscription based services are hard to maintain in the long run, so these are not being added now.

**Comment by staszek1503** [comment]
@mkbloke There is no DRM on this site.
But I understand and thank you for the information
