### ISSUE TITLE
ERROR: test_plugin_not_in_removed_list (tests.test_plugins_meta.TestPluginMeta) when building

### ISSUE THREAD

**Issue by grazzolini** [streamlink/streamlink#3643]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

When building 2.1.0 on a clean chroot (Arch), I get the following build error:

ERROR: test_plugin_not_in_removed_list (tests.test_plugins_meta.TestPluginMeta)

### Expected / Actual behavior

The build to complete without errors

### Reproduction steps / Explicit stream URLs to test

Try to build streamlink 2.1.0 on a chroot

### Log output

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/streamlink/src/streamlink-2.1.0/tests/test_plugins_meta.py", line 64, in test_plugin_not_in_removed_list
    with open(os.path.abspath(os.path.join(streamlinkplugins.__path__[0], ".removed"))) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/build/streamlink/src/streamlink-2.1.0/src/streamlink/plugins/.removed'
```

### Additional comments, etc.

I'm able to get past this issue by touching the file in question before running the actual tests:

https://github.com/archlinux/svntogit-community/blob/packages/streamlink/trunk/PKGBUILD#L31

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
`src/streamlink/plugins/.removed` is not part of the sdist tarball. This didn't come up as a test failure because the CI runners are cloning the git repo. This needs to be fixed.
