### ISSUE TITLE
Automatically set Microsoft Terminal tab name

### ISSUE THREAD

**Issue by Aqualie** [streamlink/streamlink#3646]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

When launching streamlink VIA Microsoft Terminal using either Powershell or a command prompt the tab name can be renamed utilizing different control methods outlined in Microsoft's Doc https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title

This feature is implemented should dynamically set the tab's title based upon the stream name that is supplied:
1. streamlink twitch.tv/example_stream
2. Set [Powershell]$Host.UI.Raw.UI.WindowTitle = "example_stream" or [Command prompt]TITLE "example_stream"
3. During the end stream/ctrl+c event, Reset the Window title to it's former value

**Comment by mkbloke** [comment]
It could be done, I guess, although the alternative could be to just use your own wrapper batch file.  A quick look would suggest that:
```
TITLE %1
streamlink.exe %*
```
might do the job.  Admittedly, it's simple and relies on the URL always being the first in the parameter list...

**Comment by bastimeyer** [comment]
This is a feature of the shell, not the process that's being spawned by it, in Streamlink's case python. Write a wrapper script.
