### ISSUE TITLE
plugins.picarto: 405 Client Error: Not Allowed for url: https://picarto.tv/process/channel

### ISSUE THREAD

**Issue by AxleArtz** [streamlink/streamlink#3647]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Reproduction steps / Explicit stream URLs to test

1. when running the command; # streamlink picarto.tv/<streamname> best

### Log output

```
[cli][info] Found matching plugin picarto for URL picarto.tv/LukeTUGS
error: Unable to open URL: https://picarto.tv/process/channel (405 Client Error: Not Allowed for url: https://picarto.tv/process/channel)
```

### Additional comments, etc.

Picarto.tv recently updated their API.
Link to their API documents page [https://api.picarto.tv](https://api.picarto.tv)

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by KryptonicDragon** [comment]
Having this issue as well. If I had to guess it has to do with the updated frontend on Picarto.tv

**Comment by mkbloke** [comment]
I have work in progress on a rewrite.  The live side seems to be working OK, just adding back VOD support.

**Comment by zootboy** [comment]
Have you found a replacement API for extracting the CDN URL? I had a quick stare at the devtools output, but the only place I found the URL was in the body of the main page, plus a fallback hard coded URL in player.js.

For anyone desperate for a quick hack to fix it, using the hard coded fallback ( edge4-us-east.picarto.tv ) seems to work.

**Comment by zootboy** [comment]
Also note that the documented API for channel info has changed URLs slightly:

CHANNEL_API_URL = "https://api.picarto.tv/api/v1/channel/name/{channel}"

**Comment by mkbloke** [comment]
@zootboy, I hadn't realised there was documentation!

With regards to your other post, I'm just following what the web client seems to do.  I'm taking the host from the load balancer URL and using that to make a WS connection which returns the data with the streaming URL in it.

I need to get back to this and finish it - I've been sidetracked by other things over the last 2 or 3 days...
