### ISSUE TITLE
No playable streams found at any twitch URL

### ISSUE THREAD

**Issue by OnlyTunesRadio** [streamlink/streamlink#3651]
Hi all,

## Bug Report

- [X] This is a bug report and I have read the contribution guidelines.
- [X] I am using the latest development version from the master branch.

### Description

Since moving over to a newer version of streamlink on a new Ubuntu VM all streams are failing with the error "No playable streams found at this URL:" I have tested this with multiple streamers and have had the same problem with all of them (streamers: "mizkif" / "codemiko" / "ludwig") 

### Expected / Actual behavior

It should be reading the stream and actually trying to download the stream and not just failing on no playable streams.

### Reproduction steps / Explicit stream URLs to test

1. Just attempting any streamer using the "streamlink streamURL best" seems to cause the problem
2. streamers tested on were "mizkif" "codemiko" "ludwig"

### Log output

```
root@voddy:~/AutoDown# streamlink twitch.tv/mizkif best --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-140-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/mizkif
[plugin.twitch][debug] Getting live HLS streams for mizkif
error: No playable streams found on this URL: twitch.tv/mizkif
root@voddy:~/AutoDown#

```
```
voddy@voddy:~/autodown$ streamlink twitch.tv/codemiko best -l debug
[cli][debug] OS:         Linux-5.4.0-67-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/codemiko
[plugin.twitch][debug] Getting live HLS streams for codemiko
error: No playable streams found on this URL: twitch.tv/codemiko

```
```
root@voddy:~/AutoDown# streamlink twitch.tv/ludwig best --loglevel debug
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-140-generic-x86_64-with-Ubuntu-18.04-bionic
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.18.4), Socks(1.6.5), Websocket(0.44.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/ludwig
[plugin.twitch][debug] Getting live HLS streams for ludwig
error: No playable streams found on this URL: twitch.tv/ludwig
root@voddy:~/AutoDown#

```

### Additional comments, etc.

I ran these tests in both root and standard user on Ubuntu 18.04 LTS with the VM having 6cores and 6GB ram

Hope this can help, 
And i hope everyone is staying safe during these tough times. 
If there is anything else that you would require then please let me know.

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.7.0

Outdated. Use the **latest** version.
