### ISSUE TITLE
plugins.nicolive: error: No playable streams found on this URL

### ISSUE THREAD

**Issue by railannad** [streamlink/streamlink#3656]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

I want to know if this plugin can record a live (not a timeshift) to save as a file.
 I tried to run streamlink two times and the first time occurred an error, the only difference of options between two times is URL. 
The first URL is **living** and the second URL is a **timeshift**.

### Log output

1st (Living URL)
`streamlink -o test.ts --loglevel debug --niconico-email EMAIL --niconico-password PASSWORD https://live.nicovideo.jp/watch/lv330947230 best `

```
[plugins.nicolive][debug] Restored cookies: nicosid, user_session, user_session_secure
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-4.15.0-48-generic-x86_64-with-glibc2.27
[cli][debug] Python:     3.8.0
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://live.nicovideo.jp/watch/lv330947230
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=kanoko3.29.ts
[cli][debug]  --niconico-email=********
[cli][debug]  --niconico-password=********
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/lv330947230
[plugins.nicolive][info] cached session cookie is provided. Using it.
[plugins.nicolive][debug] Getting video page: https://live.nicovideo.jp/watch/lv330947230
[plugins.nicolive][error] Failed to get wss_api_url. Please check if the URL is correct, and make sure your account has access to the video.
error: No playable streams found on this URL: https://live.nicovideo.jp/watch/lv330947230
```

2nd.(timeshift URL)
`streamlink -o test.ts --niconico-email EMAIL --niconico-password PASSWORD https://live.nicovideo.jp/watch/lv330947230 best `
```
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin nicolive for URL https://live.nicovideo.jp/watch/lv331029122
[plugins.nicolive][info] cached session cookie is provided. Using it.
[cli][info] Available streams: 345k (worst), 691k, 1800k, 3600k, 5400k (best)
[cli][info] Opening stream: 5400k (hls)
[download][kanoko3.29.ts] Written 238.2 KB (5s @ 47.6 KB/s)                                                                                                       None
[download][kanoko3.29.ts] Written 315.0 KB (10s @ 31.4 KB/s)
```
### Additional comments, etc.
It is impossible I inputed mistake email or password because the second url is need to login.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by railannad** [comment]
I purged cookies and run streamlink again. Then it worked , it puzzled me.
Is there any option that can do not use cookie and use email-password to login?

**Comment by bastimeyer** [comment]
> Is there any option that can do not use cookie and use email-password to login?

If you set the purge cookies option, then it will always clear the cookies before logging in.
https://github.com/streamlink/streamlink/blob/6a30ed7524eff2cdb205e024294b187cb660e4e3/src/streamlink/plugins/nicolive.py#L83-L92
