### ISSUE TITLE
plugins.bfmtv: No playable streams found

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#3660]
Hello. for few days, the plugin isn't working anymore

/usr/local/bin/streamlink --loglevel debug  https://rmcdecouverte.bfmtv.com/mediaplayer-direct/ best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL https://rmcdecouverte.bfmtv.com/mediaplayer-direct/
error: No playable streams found on this URL: https://rmcdecouverte.bfmtv.com/mediaplayer-direct/

**Comment by campones** [comment]
I still don't understand.
On another thread you mentionned my ssl that had to be updated. 
Meanwhile I had to move because it's true my server was really getting old (2015) and they discontinued it . 
So now I m running ubuntu 20.0.4 with french ip and I still can't retrieve anything.

streamlink -l debug http://rmcdecouverte.bfmtv.com/mediaplayer-direct/ best
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=http://rmcdecouverte.bfmtv.com/mediaplayer-direct/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bfmtv for URL http://rmcdecouverte.bfmtv.com/mediaplayer-direct/
error: No playable streams found on this URL: http://rmcdecouverte.bfmtv.com/mediaplayer-direct/

**Comment by campones** [comment]
well actually they moved the url to 
https://www.rmcbfmplay.com/direct-tv/rmc-decouverte

maybe that's the reason now.

**Comment by bastimeyer** [comment]
Please stop commenting on old issues, especially those which were closed/resolved by a pull request.

> well actually they moved the url

The plugin is working fine on bfmtv.com.

The "RMC Découverte" content has been moved to rmcbfmplay.com, like you've said. I had a look at the new site, and not only does it require a login, it also protects all content via DRM, on both HLS and DASH streams it provides, so it can't be added here.

**Comment by campones** [comment]
aaa ok, I wasn't aware of that. make sense now.

**Comment by campones** [comment]
but then I m wondering , when they ll all move to drm, then what's this script is going to be good for?

**Comment by mkbloke** [comment]
If all the streams currently supported by the plugin adopt DRM, the plugin will be removed.
