### ISSUE TITLE
plugins.crunchyroll: plugin fails with Crunchyroll Beta

### ISSUE THREAD

**Issue by ryankashi** [streamlink/streamlink#3674]
## Plugin Issue

- [X] This is a plugin issue and I have read the contribution guidelines.
- [X] I am using the latest development version from the master branch.

### Description

The Crunchyroll plugin fails to find a video when opting into the Crunchyroll Beta format. Submitting Crunchyroll beta video urls results in:

`error: No plugin can handle URL: https://beta.crunchyroll.com/watch/G69XGG44R/Ryomen-Sukuna`

### Reproduction steps / Explicit stream URLs to test

1. Go to https://www.crunchyroll.com and Log into your premium account, resulting in going to the url https://beta.crunchyroll.com, and then find a video url once inside the Crunchyroll beta, i.e.
`https://beta.crunchyroll.com/watch/G69XGG44R/Ryomen-Sukuna`
2. Please note that you must be logged in from the United States or use a VPN (https://www.crunchyroll.com/anime-news/2021/03/02/crunchyroll-launches-new-website-for-us-members)
3. Enter in the video url into streamlink. Regardless of logging into your account or not, you will get the error message: 
`error: No plugin can handle URL: https://beta.crunchyroll.com/watch/G69XGG44R/Ryomen-Sukuna`

### Log output

```
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://beta.crunchyroll.com/watch/G69P9MD9Y/Asta-and-Yuno
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --crunchyroll-username=my_username@gmail.com
[cli][debug]  --crunchyroll-password=********
error: No plugin can handle URL: https://beta.crunchyroll.com/watch/G69P9MD9Y/Asta-and-Yuno

```

### Additional comments, etc.

Although it is Beta now, this change is **breaking** for all United States users who are trying to use Streamlink in the United States, especially for Crunchyroll Premium content. In addition, this change will be rolled out globally in the coming days, so it should be a priority to fix this before it affects all users.

Thanks!

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We won't make any changes to the plugin until this is out of beta since we don't know how else it might change between now and then.

**Comment by ryankashi** [comment]
Okay that's understandable. In the mean time may I ask how the plugin handles Crunchyroll URLs? If I am able to design something that can map the new URLs to the old URLs, that would work perfectly as well

**Comment by mkbloke** [comment]
It might be that you could add the beta subdomain to the `_url_re` regex in the plugin to match the URL to the crunchyroll plugin, but that alone might not be enough to get it working.  If that doesn't work, I wouldn't bother going further down the rabbit hole until things have settled down.  If you want to try that it's up to you, but I don't think any of the devs/contributors are likely to want to commit time to this until it settles down (including any other issues you might have if you can't get it working with what I've suggested).

**Comment by ryankashi** [comment]
Hmm, so far no good. After a bit of playing around I end up getting:

`error: invalid literal for int() with base 10: ''`

It appears that the media_id is required to be an int, however moving forward the match id turns to a string. I.e. for the example above the match_id should now read G69XGG44R as opposed to 797865

**Comment by ryankashi** [comment]
Quick update:

https://www.crunchyroll.com/anime-news/2021/04/27-1/new-crunchyroll-beta-now-available-to-all-us-registered-users

It looks like Crunchyroll Beta is now available for all users in the United States. It looks like they may be gearing towards a full replacement in the coming months or even weeks

**Comment by ryankashi** [comment]
Another update:

https://www.crunchyroll.com/trybeta

It looks like Crunchyroll is making the full switch to their new website starting June 15th

**Comment by bastimeyer** [comment]
If this requires a rewrite of the validation schemas (or more), then this would be the perfect oportunity to clean up and refactor the plugin module, similar to what was done to the Twitch plugin last October (#3227 / https://github.com/streamlink/streamlink/commits/master/src/streamlink/plugins/twitch.py)

**Comment by Cryptic-Sailor** [comment]
Now that registered users are forced to use beta will this be getting updated eventually? Also just a heads up apparently the new API is a little bit different with authentication [https://github.com/ytdl-org/youtube-dl/issues/29290](url)

**Comment by bastimeyer** [comment]
> will this be getting updated eventually

Sure, when someone submits a PR with a fix.

**Comment by ryankashi** [comment]
It looks like I have potentially found a (temporary) workaround for this issue. I have noticed that when I have a url, say:

`https://beta.crunchyroll.com/watch/GRNQ5DDZR/Game-Over`

If I instead omit the "beta." portion of the url and call a fetch to:

`https://crunchyroll.com/watch/GRNQ5DDZR/Game-Over`

if there are no login cookies present, the redirected url from the fetch response will be a valid streamlink url. In the case of this example, would return from the url:

`https://www.crunchyroll.com/my-hero-academia/episode-11-game-over-730753`

I am not a very strong Python coder at the moment, and no longer know how to do a simple fetch request, however with JavaScript, doing:

`response = await fetch('https://crunchyroll.com/watch/GRNQ5DDZR/Game-Over', {credentials:'omit'})`
`response.url` will equal `https://www.crunchyroll.com/my-hero-academia/episode-11-game-over-730753` which can be plugged in successfully for Streamlink.

This means that, for Streamlink, if a https://beta.crunchyroll.com/*/watch/* is passed as an argument, an initial fetch to return the default crunchyroll url followed by the current Streamlink implementation should make things work

**Comment by Trung0246** [comment]
Quick question: did crunchyroll used Widewine before? Today I saw https://castlabs.com/drmtoday/ showed up in my request log upon connecting to the new Crunchyroll beta:

![image](https://user-images.githubusercontent.com/11626920/127098216-e61d16b6-c66c-4220-b808-ae69c21ed904.png)

**Comment by jmeza-livearea** [comment]
🍿

**Comment by shelbyKiraM** [comment]
Running it with `mpv` on macOS, simply removing `beta.` from the URL works fine for playing the video. `mpv`'s using `youtube-dl` under the hood, guess I'll just edit links? Or maybe make a wrapper function for `zsh`. Idk.

**Comment by Stella-Hoshineko** [comment]
> It looks like I have potentially found a (temporary) workaround for this issue. I have noticed that when I have a url, say:
> 
> `https://beta.crunchyroll.com/watch/GRNQ5DDZR/Game-Over`
> 
> If I instead omit the "beta." portion of the url and call a fetch to:
> 
> `https://crunchyroll.com/watch/GRNQ5DDZR/Game-Over`
> 
> if there are no login cookies present, the redirected url from the fetch response will be a valid streamlink url. In the case of this example, would return from the url:
> 
> `https://www.crunchyroll.com/my-hero-academia/episode-11-game-over-730753`
> 
> I am not a very strong Python coder at the moment, and no longer know how to do a simple fetch request, however with JavaScript, doing:
> 
> `response = await fetch('https://crunchyroll.com/watch/GRNQ5DDZR/Game-Over', {credentials:'omit'})` `response.url` will equal `https://www.crunchyroll.com/my-hero-academia/episode-11-game-over-730753` which can be plugged in successfully for Streamlink.
> 
> This means that, for Streamlink, if a https://beta.crunchyroll.com/*/watch/* is passed as an argument, an initial fetch to return the default crunchyroll url followed by the current Streamlink implementation should make things work

I did exactly this, just a really dirty fix but it may help some people so I'll post it here. It's not efficient in the least, but it works, sort of:

```python
def crunchy_fix(message):
    import cloudscraper
    if 'crunchyroll.com/' in message:
        message = message.replace('beta.crunchyroll.com/','www.crunchyroll.com/')
        scraper = cloudscraper.create_scraper()
        text = scraper.get(message).text
        text = (text[text.index('<link rel="alternate" hreflang="en-gb" href="')+45:])
        message = (text[:text.index('">')])
    return message
```

It converts a beta url into a legacy one, which still works with the current plugin.

The main hurdle was bypassing the cloudfare wall, which required the use of cloudscraper in my case, as regular fetching libraries just got blocked.

I also don't really get where this should be interfaced in streamlink, so I just added this at the end of the streamlink-helper pipeline on my machine, right before feeding the fixed url to the actual streamlink, but someone with a better understanding may be able to stick this in the right place.

**Comment by mkbloke** [comment]
I have been fixing/updating the crunchyroll plugin.  In the process I have added support for beta URLs.  I have only been able to test those changes with the two URLs from this issue.  If anybody would like to help test it further, please see: https://github.com/streamlink/streamlink/issues/4453#issuecomment-1119111595 for more info.  Reports appreciated.  Thanks.
