### ISSUE TITLE
Youtube streams cut off at the end by random amount of time

### ISSUE THREAD

**Issue by SeraphSephiroth** [streamlink/streamlink#3682]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

While using streamlink to record, it cuts a random amount of time off the end of the stream. This happens with both --retry-streams, and manual start. --player-no-close has no effect.
Currently using Streamlink 2.1.1

### Expected / Actual behavior

Expect recording to complete to end of stream, but streamlink cuts an amount of time (random amount) from stream end

### Reproduction steps / Explicit stream URLs to test

1. Link used: https://www.youtube.com/watch?v=TJz5S18UQ7o
2. Command run: streamlink --player-no-close --verbose-player -o "stream.ts" https://www.youtube.com/watch?v=TJz5S18UQ7o best
3. Output is shorter than the streamed video

### Log output

LOG:

https://gist.github.com/SeraphSephiroth/8ee66295630292c2ef251caa321119b5

### Additional comments, etc.

As stated above, this happens with streams that are started with the --retry-streams option AND a manual start. Please see the attached screenshot for a timestamp comparison. This has been an ongoing issue from streamlink 2.0 to now.

Actual Stream Time: 1:33:44
Recording Time: 1:32:57

![image](https://user-images.githubusercontent.com/19712803/114274541-03c39d00-9a73-11eb-80e9-27381d3964a9.png)

**Comment by back-to** [comment]
> [stream.hls][debug] First Sequence: 48

you are not starting the stream at **0**,
of course you will miss parts from the beginning of the stream. (not the end)
