### ISSUE TITLE
picarto plugin not working

### ISSUE THREAD

**Issue by klendrop** [streamlink/streamlink#3683]
## Plugin Issue

- [x] This is a plugin issue.
- [x] I have read the contribution guidelines.

### Description

The picarto plugin does not recognize channels or streams.

### Reproduction steps / Explicit stream URLs to test

1. streamlink -l debug picarto.tv/Chalodraws
(the channel was online and streaming at the time of writing)

### Log output

```
streamlink -l debug picarto.tv/Chalodraws
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=picarto.tv/Chalodraws
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\Program Files\MPC-HC\mpc-hc64.exe"
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin picarto for URL picarto.tv/Chalodraws
[plugins.picarto][error] The channel Chalodraws does not exist
error: No playable streams found on this URL: picarto.tv/Chalodraws
```

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
Fixed in https://github.com/streamlink/streamlink/commit/1baa545ee3459564ecfeabcd4c7d9e705d585b24
