### ISSUE TITLE
Codecov: Bash Uploader Security Notice

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3691]
This email just arrived in my inbox

> Dear Codecov User
> 
> On Thursday, April 1st, we learned that someone had gained unauthorized access to our Bash Uploader script and modified it without our permission. The actor gained access because of an error in Codecov’s Docker image creation process that allowed the actor to extract the credential required to modify our Bash Uploader script.
>
> **Unfortunately, we can confirm that you were impacted by this security event.**
>
> We strongly recommend taking action by reading our security notice about this event to understand how you are impacted and next steps you should take.

https://about.codecov.io/security-update/

----

@beardypig, we need to renew all deploy/access tokens and the signing key. Could you please take a look at this as soon as you can?

Do we need to delete all recent release files as well (GH releases / PyPI)? It doesn't look like the files have been replaced with new/modified ones. A malicious code coverage uploader script can't alter the release files during the CI run, so the ones built in the last two releases should be fine, I guess.
https://api.github.com/repos/streamlink/streamlink/releases
https://pypi.org/rss/project/streamlink/releases.xml

**Comment by bastimeyer** [comment]
@beardypig Could you please also generate a new token on the streamlinkbot for the Twitch GUI's GH releases? The repo was using an OAuth token from my own account so far, which I've already updated a couple of days ago because of GH's new token formats, but I guess this needs to be renewed once again. Thanks.

**Comment by jamesweech** [comment]
Sorry @bastimeyer just checking, I've deployed the latest release to a few of my Windows boxes, Do I need to be concerned about potential malicious code? I've just yanked the binaries for now and will take these Windows VMs offline for now

**Comment by gravyboat** [comment]
> Do we need to delete all recent release files as well (GH releases / PyPI)?

While I don't think we need to due to the nature of the breach on Codecov's end we probably should just to avoid any potential issue creation on the topic. I checked my local installation and everything looks good code wise.

**Comment by bastimeyer** [comment]
As I've said, there is no way the built release assets could have been modified by a malicious code coverage uploader script, as it's running on a different CI job and the building happens afterwards.

The only thing that could have happened is a re-upload with malicious code with the stolen access tokens. This hasn't happened though, as you can see on the timestamps in the API responses I've linked above.

Since @beardypig hasn't responded so far and since I don't have access to the streamlinkbot to remove/void the tokens, I'll remove all access from the bot to the streamlink orga for now. This will prevent the stolen access tokens from replacing release assets and committing to the repos.

@gravyboat Removing the "streamlink" account from the "streamlink" package on PyPI should be fine, right?

**Comment by bastimeyer** [comment]
The bot should only have read access to all streamlink repos now.

**Comment by bastimeyer** [comment]
I've also removed the "streamlink" account from the "streamlink" package on PyPI, so that no release files can't be uploaded with the stolen PyPI password. There was no other way of preventing access.

**Comment by gravyboat** [comment]
> Removing the "streamlink" account from the "streamlink" package on PyPI should be fine, right?

@bastimeyer Yeah that should be fine, it's only used for uploading new packages I believe. I will check tonight to see if I have the creds for the bot account.

**Comment by bastimeyer** [comment]
> I will check tonight to see if I have the creds for the bot account.

The bot has 2FA enabled and only @beardypig currently has the 2FA initialization key.

**Comment by bastimeyer** [comment]
I had a discussion with @gravyboat again yesterday and we both came to the conclusion that none of streamlink's secret env vars could have been stolen by codecov's hijacked BASH script in the CI code coverage upload jobs. The reason for this is that secret env vars need to be set explicitly in the workflow config, and this is not the case here, which means everything is fine. The write permissions of the streamlink-bot and streamlink PyPI account have been restored and everything's back to normal.

**Comment by gravyboat** [comment]
@bastimeyer I heard back from GitHub yesterday, this was their response:

Job level env variables are available to their containing jobs while workflow level env variables are available to all jobs. The risk of credential leakage applies to workflow level env variables that contain secrets or job level env variables that contain secrets. So this would be any job that specifically invokes the env variable while there are secrets contained within env.

But if you used the Codecov GitHub Actions workflow or otherwise included the Bash Uploader in your own Actions workflow, the modified code executing within an Actions environment would have access to any secrets present in the workflow environment. These would include any secrets set as environment variables or inputs to the workflow job that used codecov/codecov-action or executed the modified script. It would also have access to any secrets set as workflow-level environment variables that all jobs within the workflow file receive. This would include the workflow’s GITHUB_TOKEN. For more detail regarding the GITHUB_TOKEN, see the following:

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

GitHub does not have visibility into all secrets disclosed to the attacker, but customers should assess the secrets accessible to the modified Bash Uploader and understand their capabilities. These capabilities may include broad read or write access to customer source code or CI systems, depending on customer configuration.

Please note, at this time any secrets should be considered potentially compromised and it is our recommendation that they be revoked.

**Comment by bastimeyer** [comment]
> These would include any secrets set as environment variables or inputs to the workflow job that used codecov/codecov-action or executed the modified script.

No secrets are set for the specific action
https://github.com/streamlink/streamlink/blame/44d4afaa931e0e3f525ae9ec7adcb91f1020acb2/.github/workflows/main.yml#L102-L107

> It would also have access to any secrets set as workflow-level environment variables that all jobs within the workflow file receive.

And none are set globally for the workflow
https://github.com/streamlink/streamlink/blame/44d4afaa931e0e3f525ae9ec7adcb91f1020acb2/.github/workflows/main.yml#L9-L13

> This would include the workflow’s GITHUB_TOKEN.

This is nothing we have control over. It gets set by the CI runner for being able to commit back to the repo automatically (and more) without having to add custom auth stuff. Does GH use one-time-only tokens? Do they expire? If they don't expire, then they could be used to steal the secrets by triggering a CI run with a custom workflow file.

**Comment by bastimeyer** [comment]
@gravyboat I've set the `GITHUB_TOKEN` permissions to read only now (entire orga scope). It's not being used anyway for writing, as we have custom auth data set everywhere where we push/upload. I am not sure though if this revokes any previous tokens which may not have expired (yet).

----

If you want, we can completely remove any tokens/permissions again, but this won't help if the repo secrets have indeed been read by a third party (which I haven't seen any indicators for so far though), as they would also have the data for the signing key in that case. And without @beardypig we can't restore the streamlink-bot's OAuth tokens.

A full wipe would be necessary with a new signing key (and revoking the current one) and a new release asset uploader account, as @beardypig hasn't responded to any of my emails yet.

**Comment by gravyboat** [comment]
@bastimeyer I'm not concerned at this moment, I'm just providing the update openly for transparency purposes. Once @beardypig responds I still think we should rotate for peace of mind, but I'm not stressing about it.
