### ISSUE TITLE
plugins.[afreeca]: When trying to record live streams I get "Login required"

### ISSUE THREAD

**Issue by dtanimal** [streamlink/streamlink#3693]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.
- [x ] I am using the latest development version from the master branch.

### Description

On Windows, I run cmd and type $streamlink [link to stream]. I get [plugins.afreeca][error] Login required.

It didn't do this 2 days ago, just started now. Reinstalled streamlink and still doesn't work.

### Log output
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com
[plugins.afreeca][error] Login required
error: No playable streams found on this URL: https://play.afreecatv.com

EDIT: Seems to only be affecting streams that are marked 19+ not sure why. It hasn't before.

**Comment by mkbloke** [comment]
Are you using any credentials/have any saved cookies?  Full debug log output as requested in the issue template should be provided.  Does using the `--afreeca-purge-credentials` option make any difference?

**Comment by dtanimal** [comment]
> Are you using any credentials/have any saved cookies? Full debug log output as requested in the issue template should be provided. Does using the `--afreeca-purge-credentials` option make any difference?

Hi sorry here it is. I do not have any credentials saved as I don't see anywhere to put them in. 

Debug log below:

```
C:\Users\name>streamlink --loglevel debug https://play.afreecatv.com/username/
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/username
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe

```

**Comment by back-to** [comment]
> Login required

` --afreeca-username USERNAME` ` --afreeca-password PASSWORD`

https://streamlink.github.io/cli.html#afreeca

Example:

https://streamlink.github.io/cli.html#plugin-specific-usage
