### ISSUE TITLE
Adult Swim doesn't play any streams.

### ISSUE THREAD

**Issue by stepshal** [streamlink/streamlink#370]
https://www.adultswim.com/videos/streams
https://www.adultswim.com/videos/streams/toonami
https://www.adultswim.com/videos/streams/williams-stream

**Comment by gravyboat** [comment]
Can you please provide the command you're running, as well as what the error output looks like?

**Comment by stepshal** [comment]
@gravyboat `error: No plugin can handle URL:`

**Comment by gravyboat** [comment]
What version of Streamlink are you running? Your command (minus passing the player variable) works fine for me on `0.2.0`.

**Comment by beardypig** [comment]
@stepshal that is a bug, if you drop the `s` from `https` it should work. I'm preparing a PR to fix it right now :)

**Comment by gravyboat** [comment]
@beardypig That's weird, it worked fine for me with `https`.

**Comment by beardypig** [comment]
@gravyboat agreed, very weird...
@stepshal this should be fixed if you update to the latest nightly.

**Comment by beardypig** [comment]
@stepshal is this working with the latest nightly?

**Comment by stepshal** [comment]
@beardypig 
I have this:
`[cli][error] Could not open stream: Unable to open URL: http://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer4.m3u8 (403 Client Error: Forbidden for url: http://adultswimhls-i.akamaihd.net/hls/live/249295/adultswim_6/main/1/stream_Layer4.m3u8)` 
So it's geo-restricted? But i can watch it in browser.

**Comment by beardypig** [comment]
Which URL are you trying to watch? I think some if not all are geo-restricted to the US.

**Comment by stepshal** [comment]
@beardypig i can watch all of them in browser without proxy.

**Comment by beardypig** [comment]
And do they all give the same error?

**Comment by stepshal** [comment]
@beardypig Seems that all streams work except Toonami. But i can still watch it in browser.

**Comment by beardypig** [comment]
OK. I get same error when trying from outside the US. I'll try and correct it.

**Comment by stepshal** [comment]
@beardypig and that all vods from archive doesn't work. It's showing live stream instead.

**Comment by beardypig** [comment]
VOD is not currently supported. The toonami stream is slightly weird, might take a little while to fix.

**Comment by stepshal** [comment]
@beardypig so pycryptodome is needed for VODs, that are not yet supported?

**Comment by beardypig** [comment]
I can't remember if they were just encrypted or also had DRM. I'll take a look when I fix the toonami bug...
