### ISSUE TITLE
Openrec.tv: cannot login with correct email and password

### ISSUE THREAD

**Issue by vandheerlord** [streamlink/streamlink#3712]
I'm trying to dowload by this command :

`  streamlink https://www.openrec.tv/live/replace_to_your_url source -o D:\testing.mp4 --openrectv-email='your_account@gmail.com' --openrectv-password='your_pwd'`

My email and password is correct, can login on website, but the command returned :

` Failed to login: The combination of e-mail address and the password is incorrect`

--------------------------

It turns out I should use `"` rather `'` to set the params, but even if I can login sussesfully, it still says I don't have the authority (but I can watch it on the website ):
```
[plugins.openrectv][debug] Logged in as ****
[plugins.openrectv][debug] Got valid detail response
[plugins.openrectv][debug] Found video: ****
[plugins.openrectv][error] You don't have the authority.
```

--------------------------

2021.04.30

Don‘t know much about Python, but I've tried to take a look at the code in `openrectv.py`.

Seems the error message comes from the function `_get_streams`. 
I don't know if I understand it correctly , I guess the message `You don't have the authority.`  pop up because both `mdata["media"]["url"]`  and `mdata["media"]["url_public"] `are null.

Those two comes from the function `_get_movie_data`, so I gave it a look too.
 I'm not sure but I think this function is mean to get data from the url represent by variable `api_url`, so I tried to send request to this url with the parameters it requires, and got the response. 

In the response all the fields of object `media` is `null`, so I think this is the problem. 
I've tried another video, which I can get it's information by the command, and there would be a url information in `media`. 

Maybe the one I'm trying to download just cannot be download.
So right now I'm just going to watch the video as much as possible while I still can :-)

**Comment by bastimeyer** [comment]
https://raw.githubusercontent.com/streamlink/streamlink/master/.github/ISSUE_TEMPLATE/1_plugin_issue.md

**Comment by vinyl-umbrella** [comment]
There are many types of videos in OPENREC. Special videos, subscription-only videos, archives of streaming, uploaded videos, and more.
If you are ok, please let us know your account type and which video you are trying to download.
