### ISSUE TITLE
Add variable(s) support for File output FILENAME (Author, Title etc. )

### ISSUE THREAD

**Issue by 3CannedSardines** [streamlink/streamlink#3718]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

there's already a feature that let you use certain variable in player title bar using [--title](https://streamlink.github.io/cli.html#cmdoption-title)  such as title and author. I thought it'd be great if it also works the same way with FILENAME in [File output options](https://streamlink.github.io/cli.html#file-output-options).

### Additional comments, etc.

This might cause problem if stream title contains illegal character **_<>:"/\|?*_** .

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
#791
