### ISSUE TITLE
plugins.trovo: can not send to vlc

### ISSUE THREAD

**Issue by TaoziDB** [streamlink/streamlink#3720]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

for trovo live stream, successfully gets resolutions list, but when sends to vlc, saying stream ended although the stream is still live

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Log output

```
streamlink --loglevel debug https://trovo.live/Hakmoun best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.8
[cli][debug] Streamlink: 2.1.1
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://trovo.live/Hakmoun
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin trovo for URL https://trovo.live/Hakmoun
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\VideoLAN\VLC\vlc.exe" --input-title-format https://trovo.live/Hakmoun -
[cli][debug] Writing stream to output
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [ ] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [ ] Description and/or reproduction steps are insufficiently detailed
* - [ ] Streamlink version in use not specified
* - [ ] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [x] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [x] Other (see below)
* Other: This is not an official Streamlink plugin.  You must have installed it via the code in the closed PR: #3076

Suggest you try looking to the author for support: https://github.com/TopoIogist/streamlink

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions
