### ISSUE TITLE
loco.gg

### ISSUE THREAD

**Issue by TaoziDB** [streamlink/streamlink#3723]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [x] I am using the latest development version from the master branch.

### Description

Watch India's top streamers playing and live streaming all your favorite games like Free Fire, CODM, PUBG, Valorant, GTA V and many more!

### Example stream URLs

1. stream: https://loco.gg/stream/8bf55013-84cb-491f-b186-e1dc5ef26abb
2. get other streams link from https://loco.gg/live-streams
3. vod: https://loco.gg/stream/f162bf6d-8265-46db-a0a4-186e604e7245

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Same as https://github.com/streamlink/streamlink/issues/3329#issuecomment-724153355
