### ISSUE TITLE
plugins.bbciplayer: Not working

### ISSUE THREAD

**Issue by aa146214** [streamlink/streamlink#3726]
## Plugin Issue

- [ x] This is a plugin issue and I have read the contribution guidelines.
- [ x] I am using the latest development version from the master branch.

### Description

If I try to run the plugin, for example with streamlink -p "C:\ProgramData\chocolatey\lib\mpv.install\tools\mpv" --bbciplayer-username="*USERNAME HERE*" --bbciplayer-password="*PASSWORD HERE*" bbc.co.uk/iplayer/live/bbcparliament 288p_dash, I receive the following:

```
error: Unable to parse JSON: Extra data: line 1 column 23991 (char 23990) ('{"navigation":{"items":[{"id":"cha ...)
```

### Reproduction steps / Explicit stream URLs to test

I updated Streamlink to 2.1.0 to try and resolve, but that didn't work.

1. Running using the command posted above

### Additional comments, etc.

It seems to error here: https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/bbciplayer.py#L114

I am using Windows 10

I presume it may be an issue with the JSON being returned by BBC iPlayer, as there is a semicolon after a closing bracket?

**Comment by mkbloke** [comment]
There's already a PR for this: #3725
