### ISSUE TITLE
Add Path Config for External HTTP Players

### ISSUE THREAD

**Issue by griest024** [streamlink/streamlink#3727]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

In addition to the port being configurable for external HTTP players, I would like the path to be configurable. That is, I would like streamlink to be able to host HLS streams of the form `localhost:8080/index.m3u8`.

Some external players cannot play HLS streams of the form: `localhost:8080`. For example a smart TV web browser will try and download the file. Playing HLS streams from URLs like `localhost:8080/index.m3u8` in those web browsers work as expected.

The purpose of the external HTTP player feature is to enable players to play HLS streams that they would not otherwise be able to. This feature would expand the group of enabled players.

### Additional comments, etc.

I would be willing to submit a PR if required.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
Streamlink doesn't provide HLS streams as output. All output streams are progressive/continuous data streams, regardless whether the default options (stream gets written to the player process's `stdin`), `--stdout`, `--player-fifo`, `--player{,-continuous}-http` or `--output` are being used.

HLS output streams would require implementing proxing logic. See #134 and related...

You can however use streamlink to resolve the HLS stream URL via `--stream-url`.
