### ISSUE TITLE
DIRECTV GO Latin America / Brasil

### ISSUE THREAD

**Issue by viannaricardo** [streamlink/streamlink#3729]
Implement DIRECTV GO in Streamlinke

- [ ] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.
- [X] I am using the latest development version from the master branch.

### Description

I would like to be able to use Streamlink with DIRECTV GO.

### URL Examples

https://www.directvgo.com/player/station/9e1c5fa1-b1d7-4038-82f8-b18cc8dcbaf3

**Comment by bastimeyer** [comment]
1. https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
2. https://github.com/streamlink/streamlink/issues/new/choose
