### ISSUE TITLE
Wrong Version number returned from --version command

### ISSUE THREAD

**Issue by jake2xr** [streamlink/streamlink#373]
Even though I have version 0.2.0 installed, `streamlink --version` returns:
`streamlink-script.py 0.1.0`
and the output of `streamlink --version-check` notifies me that there is a new version available.
Windows Programs and Features reports correct version number.

Minor issue, just letting you know about it. Or perhaps it's something on my end?

**Comment by Brainzyy** [comment]
Take a look at this: https://github.com/streamlink/streamlink/issues/312

**Comment by jake2xr** [comment]
Ah, didn't look at the closed issues. Thanks.
