### ISSUE TITLE
YT - Player does not exit

### ISSUE THREAD

**Issue by fruvous** [streamlink/streamlink#3731]
## Issue

- [X] This is not a bug report, feature request, or plugin issue/request.
- [X] I have read the contribution guidelines.
- [X] I am using the latest development version from the master branch.

### Description

VLC and MVP do not exit after Youtube live stream has ended

### Expected / Actual behavior

After the end of a Youtube live stream, the player should exit (like it does with twitch).  The player ends up freezing on the last frame

### Reproduction steps / Explicit stream URLs to test

1. Start Youtube stream
2. Wait until it ends
3. Player stalls on last frame

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
All log output should go between two blocks of triple backticks (grave accents) for proper formatting.
```

### Additional comments, etc.
no additional comments

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by gravyboat** [comment]
We're going to need debug logs, example live streams, etc.

**Comment by bastimeyer** [comment]
Post the **full debug log** and check the player's own output via `--verbose-player`:
https://streamlink.github.io/cli.html#cmdoption-verbose-player

**Comment by fruvous** [comment]
Please close for now, I will resubmit when I get the logs.  Streamlink currently isn't working for YT even after replacing the plugin file.

**Comment by bastimeyer** [comment]
> Streamlink currently isn't working for YT

https://github.com/streamlink/streamlink/releases/tag/2.1.2
