### ISSUE TITLE
Force specific quality

### ISSUE THREAD

**Issue by OMEGARAZER** [streamlink/streamlink#3733]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description
I have a Twitch stream that I like to archive live as some vods get deleted and are unable to be downloaded after the stream ends.
I use this before the stream starts to make sure I catch as much of the stream as possible: `streamlink --twitch-low-latency --retry-streams 30 --retry-open 5 -o /Twitch/Username.ts twitch.tv/Username 1080p60`
What happens is if it checks within the first ~15 seconds the "best" is 720p60 and causes streamlink to fail with `error: The specified stream(s) '1080p60' could not be found.
       Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60 (best)`.
So switching 1080p60 to best will always work and why I listed this as a request rather than a bug. I would rather have a wait for my requested quality than bumping down in quality though. I thought the retry-open would do what I was looking for but it sadly doesn't.

So my request is that when a specific quality is selected streamlink will wait and try again till the quality is available or have a flag to enable that behaviour.

Thanks.

**Comment by bastimeyer** [comment]
> wait and try again till the quality is available

That doesn't make sense if the user tries to select a stream name / stream quality which doesn't or never will exist. It's also not possible for every streaming provider to "refresh" the available streams, as it may require re-requesting access tokens, etc., which may depend on the user input.

If you're looking for a specific quality which for some reason is only available after a certain amount of time then use the [`--stream-sorting-excludes`](https://streamlink.github.io/cli.html#cmdoption-stream-sorting-excludes) parameter in combination with the `best` stream name synonym to be able to filter out qualities which don't match your criteria without having to use explicit stream quality names. If the desired quality is not available, then try again, eg. via a shell script loop.

**Comment by OMEGARAZER** [comment]
I will try with the excludes and hopefully that will solve this for me.


> That doesn't make sense if the user tries to select a stream name / stream quality which doesn't or never will exist.

Hence why I specifically mentioned it likely being a parameter (such as --force-quality) to use when it is known to exist.
