### ISSUE TITLE
Support for Bulgarian national TVs?

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#374]
Most of these are readily available to just input into VLC as a network stream, but are not recognized by streamlink. If possible, I'd like a few simple plugins available, as I watch TV on my PC, but I can't forward them easily to my actual TV that I use as a home entertainment system with Ubuntu and streamlink as part of its core.

Most of these channels are polythemed or News-oriented channels.

WARNING: Some of these streams, hosted by the CDN.bg company, are currently offline, probably due to the blizzards in Eastern Europe. I have marked currently offline streams with this: **|x|**, they should be fine within a few hours to days. Streams that were offline for a bit and might be offline again are marked with **|?|**.

**Available worldwide**
BNT World - available at http://tv.bnt.bg/bntworld/ || Pastebin with code: http://pastebin.com/waePCSuH

**Maybe geo-locked?**
BTV at http://www.btv.bg/live/ (requires registration) || Pastebin with code: http://pastebin.com/8nu3vwRU
**|?|** NovaTV at https://nova.bg/live || Pastebin with code: http://pastebin.com/VSaC93x8
**|?|** BiT at http://www.bitelevision.com/live/ || Pastebin with code: http://pastebin.com/2NdDBrmJ
**|?|** Eurocom at http://eurocom.bg/live || Pastebin with code: http://pastebin.com/4yEP91Vd
**|?|** Bulgaria On Air at http://www.bgonair.bg/tvonline || Pastebin with code: http://pastebin.com/5vygfuDs
**|?|** Kanal 3 at http://kanal3.bg/live || Pastebin with code: http://pastebin.com/G9rf90WD

**100% geo-locked to Bulgaria**
**|?|** BNT HD at http://tv.bnt.bg/bnthd/ || Pastebin with code: http://pastebin.com/kaxSGEXn
**|?|** BNT 2  at http://tv.bnt.bg/bnt2/16x9/ || Pastebin with code: http://pastebin.com/uBRFBQeh
**|?|** BNT 1 (HD quality) at http://tv.bnt.bg/bnt1/hd/ || Pastebin with code: http://pastebin.com/JBCZXvTu
**|?|** BNT 1 (16:9 quality) at http://tv.bnt.bg/bnt1/16x9/ || Pastebin with code: http://pastebin.com/56hMqjCu

**Update**: All of the streams seem to be live now.

**Comment by beardypig** [comment]
Apart from the geo-locked streams, and the one that requires registration they all seem fairly straightforward :-) Any chance you can provide a proxy for the geo-locked ones?

**Comment by roshavagarga** [comment]
@beardypig Yes, sorry I forgot to add some options. Here you go:
1. http://bgproxy.org/
2. https://nqma.net/
3. http://www.bgproxy.net/bg/index.php
4. http://www.php-proxy.net/

If none of these work, I have no problem setting up a proxy via TOR for you. I can also give you a registration for BTV if you give me some sort of contact.

**Comment by beardypig** [comment]
Cool I'll try with those first time. My email address is on my profile page, if you could send me details for a BTV account that would be useful too.

**Comment by roshavagarga** [comment]
@beardypig - Sent you the account details, if you need anything else hit me up here or on my email.

**Comment by gravyboat** [comment]
Closing since the associated PR is merged.
