### ISSUE TITLE
Support to raiplay.it

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#375]
They have several channels mostly geoblocked to Italy some work outside too. 
http://www.raiplay.it/dirette/
I think they provide HDS and HLS, it would be nice to cover both systems.

**Comment by beardypig** [comment]
Looks pretty straight forward and I have a suitable proxy, should be able to whip something up in a couple of days :-)

**Comment by karlo2105** [comment]
Many thanks for your contribution. ;)

**Comment by beardypig** [comment]
Closing this as #382 has be merged.
