### ISSUE TITLE
Skip existing video 

### ISSUE THREAD

**Issue by Starteer** [streamlink/streamlink#3758]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

Hi, to overwrite files I simply pass the -f command but I manually press n in order to skip the already downloaded files, please add the option to auto ignore existing files when downloading the video, something similar to the -n command in ffmpeg.

Thank you

**Comment by back-to** [comment]
seems unnecessary
