### ISSUE TITLE
Mytf1.fr : TF 1, TMC, NT 1, HD 1, LCI

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#376]
http://www.tf1.fr/direct
Channels on TF 1 site require only a free login and French proxy. They use HDS and HLS. 
LCi doesn't require login just proxy : http://www.lci.fr/direct/

But it would be of course better if you can bypass login.

**Comment by beardypig** [comment]
Can take a look, do you know any good proxy for lci? I can use unlocator for tf1 but I don't know any good http proxies for France.

**Comment by karlo2105** [comment]
You can try here : 
http://spys.ru/free-proxy-list/FR/
http://www.freeproxylists.net/?c=FR&pt=&pr=&a%5B%5D=0&a%5B%5D=1&a%5B%5D=2&u=0
https://www.proxynova.com/proxy-server-list/country-fr/

**Comment by Vangelis66** [comment]
@karlo2105 wrote: 

> LCi doesn't require login, just proxy: 
> http://www.lci.fr/direct/

@beardypig wrote: 

> do you know any good proxy for lci?

I am not inside France, but I find accessing the live (direct) stream from Greece 
does not need a French proxy; the "HDS Link detector" Firefox addon reveals 
the following HDS manifest:

`http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=st=1483822658~exp=1483824458~acl=/*~hmac=1bd7f429b37a778f80a7654e2f2db1d7a813fe5c0d050acb5279451fbd108c82&hdcore=2.11.3&g=MHIRXZLQFQZI` 

which, of course, has a limited lifespan; it contains five quality variants, with bitrates: 
240k, 496k, 896k, 1296k & 2596k

@beardypig 
I've been meaning to ask, you, of course, are not obliged in any way to reply, 
but what is your physical location?

Regards

**Comment by karlo2105** [comment]
I think through HLS, they provide 720p stream.

**Comment by Vangelis66** [comment]
@karlo2105 wrote: 

> I think through HLS, they provide 720p stream

The 2596k AdobeHDS stream is **720p**, too. 
But I have stumbled upon a problem; 
AdobeHDS.php would download streams 
from the manifest fine, 
but streamlink fails to, citing: 
`error: This manifest requires the 'pvswf' parameter to verify the SWF`

**Comment by beardypig** [comment]
```
streamlink "hds://http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=st=1483827331~exp=1483829131~acl=/*~hmac=d0f781049713946d9ce00371c599a0abec582cb6b86ab0466971958d408aeb0d&hdcore=2.11.3&g=VXPKOBLDFCWY pvswf=http://www.wat.tv/images/v70/PlayerWat.swf?rev=04.00.861" best
```
Works for me :)

**Comment by Vangelis66** [comment]
@beardypig 

Thanks! 
Where exactly in streamlink's documentation is the `pvswf parameter` detailed? 
I've searched, but to no avail :-(
BTW, this HDS parameter reminds me of the `--swfUrl` one used in RTMP streams...

**Comment by beardypig** [comment]
@Vangelis66 it's not really documented, there is a section about passing extra parameters to streams here https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly. There is an example for rtmp but it works for everything I think. You have to know the `pvswf` parameter though...

**Comment by beardypig** [comment]
LCI is only sometimes geo locked, it should be quite straightforward to make a plugin :-)

**Comment by karlo2105** [comment]
http://www.wat.tv/get/androidliveconnect/591997?getURL=1
http://www.wat.tv/get/androidlivelci/591997?getURL=1
http://www.wat.tv/get/androidlivent1/591997?getURL=1
http://www.wat.tv/get/androidlivehd1/591997?getURL=1
http://www.wat.tv/get/androidlivetmc/591997?getURL=1

**Comment by Vangelis66** [comment]
@karlo2105 wrote: 

 > Source for HDS :
> (snip)
> http://www.wat.tv/get/androidlivelci/591997?getURL=1

Hello Karlo :smile:
I have only tested LCI on a desktop browser, the manifest URIs sniffed either via 
Firefox's web console or (more easily) via "HDS Link Detector" addon are of the form 

`http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=st=1483843039~exp=1483844839~acl=/*~hmac=2afc34bd7b2a0c8c1782d4f2b48eb2732f0e99a3cb8dd7701e9e2102f727daf6&hdcore=2.11.3&g=TTSHPFEMNPXT`

Those are very short-lived (less than 30mins), but for as long as they are valid they are 
downloadable either via AdobeHDS.php script or via livestreamer/streamlink (the pvswf value 
must be supplied as per previous post in this thread). 

I don't have an android device to test, but opening 
http://www.wat.tv/get/androidlivelci/591997?getURL=1
in a desktop browser tab yields a manifest of this form: 

`http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=st=1483844264~exp=1483846064~acl=/*~hmac=e5b561cc06a10cfde5fffe135f6e16c225ce34fe6338c692cd4aa7b87c3725cc`

These ALWAYS get an **Access Denied** response when 
a download is attempted well within the manifest's validity; 
probably because the manifests generated by the link you 
posted are missing the final part of the form: 
`&hdcore=2.11.3&g=TTSHPFEMNPXT`

But if you modify a bit the manifest URI generated by your link, 
you get a valid (and downloadable) AppleHLS master playlist: 

http://www.wat.tv/get/androidlivelci/591997?getURL=1 => 

`http://lcilivhlshdslive-lh.akamaihd.net/z/lci_1@301585/manifest.f4m?hdnea=st=1483845377~exp=1483847177~acl=/*~hmac=095e53624d9d3cc9d07d9cceaf92379724fbcab66c7fab75bf76c81d370c2475` (403 Access Denied) 
If modified to
`http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/master.m3u8?hdnea=st=1483845377~exp=1483847177~acl=/*~hmac=095e53624d9d3cc9d07d9cceaf92379724fbcab66c7fab75bf76c81d370c2475` => Valid playlist
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=240000,RESOLUTION=416x234,CODECS="avc1.66.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_240_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=264000,RESOLUTION=416x234,CODECS="avc1.66.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_240_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=496000,RESOLUTION=416x234,CODECS="avc1.66.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_496_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=464000,RESOLUTION=416x234,CODECS="avc1.66.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_496_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=896000,RESOLUTION=640x360,CODECS="avc1.77.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_896_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=896000,RESOLUTION=640x360,CODECS="avc1.66.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_896_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1296000,RESOLUTION=1080x576,CODECS="avc1.77.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_1296_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1296000,RESOLUTION=1024x576,CODECS="avc1.77.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_1296_av-b.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2595000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_2596_av-p.m3u8?sd=10&rebase=on
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2595000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
http://lcilivhlshdslive-lh.akamaihd.net/i/lci_1@301585/index_2596_av-b.m3u8?sd=10&rebase=on
```
As you can see, for each resolution there exist two (or more) streams: 
234p: 240k, 264k, 464k, 496k
360p: 896k-1, 896k-2
576p: 1296k-1, 1296k-2
720p: 2595k-1, 2595k-2
so this could present a small problem in creating the plugin... 

But I am sure @beardypig knows already all this info you and I are posting, 
probably feeling a bit amused at us newbies trying to figure out how things work... 😺 

All have a nice Sunday (deep-freeze over here at -8 Celsius)

**Comment by karlo2105** [comment]
Some HDS streams are not working. 

TMC
```
livestreamer --http-header "X-Forwarded-For=185.26.239.95" "http://www.tf1.fr/nt1/direct" 840k_hds
[cli][info] Found matching plugin tf1 for URL http://www.tf1.fr/tmc/direct
[cli][info] Available streams: 440k_hds, 840k_hds, 64k (worst), 440k, 640k, 840k, 1240k (best)
[cli][info] Opening stream: 840k_hds (hds)
[stream.hds][error] Failed to open fragment 1-23649054: Unable to open URL: http://tmchdslive-f.akamaihd.net/z/live_1@72268/840_bf2d3ed44cf2b891-p_Seg1-Frag23649054 (403 Client Error: Forbidden)
```

NT 1
```
livestreamer --http-header "X-Forwarded-For=185.26.239.95" "http://www.tf1.fr/nt1/direct" 840k_hds
[cli][info] Found matching plugin tf1 for URL http://www.tf1.fr/nt1/direct
[cli][info] Available streams: 440k_hds, 840k_hds, 64k (worst), 440k, 640k, 840k, 1240k (best)
[cli][info] Opening stream: 840k_hds (hds)
[stream.hds][error] Failed to open fragment 1-23649136: Unable to open URL: http
://nt1hdslive-f.akamaihd.net/z/live_1@72464/840_487251dc402e69b8-p_Seg1-Frag2364
9136 (403 Client Error: Forbidden)
```

HD 1 
``
livestreamer --http-header "X-Forwarded-For=185.26.239.95" "http://www.tf1.fr/hd1/direct" best
[cli][info] Found matching plugin tf1 for URL http://www.tf1.fr/hd1/direct
error: Unable to open URL: http://hd1livhdsandliv-lh.akamaihd.net/z/andlive_1@90
743/manifest.f4m?hdnea=st=1483915819~exp=1483917619~acl=/*~hmac=3c8731afcfae9226
e48bffa438b86cec873bb554af367c12e33d811b3fb85108 (404 Client Error: Not Found)```

**Comment by beardypig** [comment]
Do the stream work in a browser with the proxy?

**Comment by karlo2105** [comment]
Yes it is.
Take a look. 

http://www.wat.tv/images/v70/PlayerLite.swf?videoId=L_TMC
http://www.wat.tv/images/v70/PlayerLite.swf?videoId=L_NT1
http://www.wat.tv/images/v70/PlayerLite.swf?videoId=L_HD1

**Comment by beardypig** [comment]
Looks like there is some extra verification some of the time for some of the streams. Need to work out how the `g` argument is calculated...

**Comment by beardypig** [comment]
@karlo2105 can you try out the plugin version in this branch [beardypig/streamlink/tree/tf1](https://github.com/beardypig/streamlink/tree/tf1), note that [src/streamlink/stream/hds.py](https://github.com/beardypig/streamlink/blob/tf1/src/streamlink/stream/hds.py) has also been updated to add the `g` parameter. It works for me for all the channels with HDS and HLS (except TMC, where HLS does not work - but I cannot get it to work in the browser either).

**Comment by melmorabity** [comment]
@beardypig Works like a charm from France, both HDS and HLS . Even TMC :)

**Comment by melmorabity** [comment]
@beardypig Some issues with Python 3 (Python 2 is OK)
```
$ streamlink "http://www.tf1.fr/nt1/direct"
[cli][info] Found matching plugin tf1 for URL http://www.tf1.fr/nt1/direct
Traceback (most recent call last):
[...]
  File "/home/mohamed/.local/lib/python3.5/site-packages/streamlink-0.2.0-py3.5.egg/streamlink/stream/hds.py", line 599, in <listcomp>
    return "".join([random.choice(string.uppercase) for i in range(length)])
AttributeError: module 'string' has no attribute 'uppercase'
```
string.uppercase isn't available anymore in Python 3

**Comment by beardypig** [comment]
@melmorabity thanks for testing the streams :) Also, quite right about `uppercase` :)

**Comment by karlo2105** [comment]
I confirm working fine now. Thanks for fix.

**Comment by campones** [comment]
hi, they have been changing the channel name, I thought just pointing to the new url would work but it doesn't

streamlink "https://www.tf1.fr/tfx/direct" best
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tfx/direct
error: Unable to open URL: http://www.wat.tv/get/tfxlive/591997 (403 Client Error: Invalid delivery format. for url: http://www.wat.tv/get/tfxlive/591997?getURL=1)

**Comment by hatisup** [comment]
Hi
