### ISSUE TITLE
Separate audio streams in HLS

### ISSUE THREAD

**Issue by Quaraxkad** [streamlink/streamlink#3769]
## Feature Request

- [x] This is a feature request and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

I recently have noticed more places using M3U8 playlists that contain separate video and audio tracks. In these cases, Streamlink only downloads the video, and unless there's a feature I can't find any documentation for, there's no way to make it download the audio without manually retrieving the direct audio playlist url (as opposed to using the master/hlsvariant playlist). Can support for this type of playlist be added?

### Additional comments, etc.

This is *not* in relation to any specific website plugin, I'm talking about the when you use Streamlink to download an hls:// stream "manually".

Example of this type of playlist:
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=9977000,CODECS="avc1.100.52,mp4a.40.2",RESOLUTION=3840x2160,AUDIO="aac",SUBTITLES="subt"
chunklist_b9070000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=4988500,CODECS="avc1.100.52,mp4a.40.2",RESOLUTION=2560x1440,AUDIO="aac",SUBTITLES="subt"
chunklist_b4535000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=2011900,CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac",SUBTITLES="subt"
chunklist_b1829000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=1238600,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac",SUBTITLES="subt"
chunklist_b1126000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=565400,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=854x480,AUDIO="aac",SUBTITLES="subt"
chunklist_b514000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=240900,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,AUDIO="aac",SUBTITLES="subt"
chunklist_b219000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-STREAM-INF:BANDWIDTH=166100,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=426x240,AUDIO="aac",SUBTITLES="subt"
chunklist_b151000_vo.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="es",NAME="Spanish",DEFAULT=YES,URI="chunklist_b128000_ao_sles_t64U3BhbmlzaA==.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",DEFAULT=YES,URI="chunklist_b128000_ao_slen_t64RW5nbGlzaA==.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622685600%7C098423acc31663c9964ad0160416f128"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subt",LANGUAGE="es",NAME="Spanish",DEFAULT=YES,URI="../vtt/es_subt.vtt"

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> Streamlink only downloads the video

External audio tracks are supported by Streamlink and they get muxed into the output stream, depending on which external audio track you have selected.

[`--hls-audio-select=LANG`](https://streamlink.github.io/cli.html#cmdoption-hls-audio-select)

For Streamlink to be able to mux multiple streams, ffmpeg needs to be available in your `PATH` env var or its path set via the [`--ffmpeg-ffmpeg`](https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg) argument.

**Comment by Quaraxkad** [comment]
OK, there are some issues with this.

First, having ffmpeg in the environment path is apparently not enough, it still does not download the audio. Using the exact same command line but adding --ffmpeg-ffmpeg does work.

Second, the last time I came across this issue was actually a playlist that didn't specify language and audio. How does it work in this scenario? I could not get the --hls-audio-select parameter to do anything, but that may have been because I didn't specify a path for ffmpeg.


C:\>echo %path%
BLAHBLAHBLAH;c:\programs\ffmpeg\;BLAHBLAHBLAH

C:\>ffmpeg
ffmpeg version N-93094-g7f8bfbee36 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181201
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --
enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-l
ibx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --ena
ble-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 46.100 / 58. 46.100
  libavformat    58. 26.100 / 58. 26.100
  libavdevice    58.  6.101 / 58.  6.101
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

C:\>streamlink "https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f8
9040f2d842897911f74a6fd3842d" worst --hls-audio-select=es -o test.ts
[cli][info] Found matching plugin hls for URL https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B
101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p, 1440p, 2160p (best)
[cli][info] Opening stream: 240p (hls)
[download][test.ts] Written 10.5 MB (0s @ 20.6 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...

C:\>ffprobe test.ts
ffprobe version 3.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv -
-enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --en
able-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --
enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mpegts @ 0332b0a0] start time for stream 0 is not set in estimate_timings_from_pts
Input #0, mpegts, from 'test.ts':
  Duration: 00:17:58.96, start: 0.080000, bitrate: 176 kb/s
  Program 1
    Stream #0:0[0x102]: Data: timed_id3 (ID3  / 0x20334449)
    Stream #0:1[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 426x238 [SAR 1904:1917 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
Unsupported codec with id 100358 for input stream 0

C:\>streamlink "https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f8
9040f2d842897911f74a6fd3842d" worst --hls-audio-select=es -o test2.ts --ffmpeg-ffmpeg c:\programs\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin hls for URL https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B
101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p, 1440p, 2160p (best)
[cli][info] Opening stream: 240p (hls-multi)
[download][test2.ts] Written 34.5 MB (1s @ 23.0 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...

C:\>ffprobe test2.ts
ffprobe version 3.2 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv -
-enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --en
able-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --
enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.100 / 57. 64.100
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, mpegts, from 'test2.ts':
  Duration: 00:17:58.96, start: 1.480000, bitrate: 333 kb/s
  Program 1
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(progressive), 426x238 [SAR 1904:1917 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 127 kb/s

**Comment by bastimeyer** [comment]
> having ffmpeg in the environment path is apparently not enough

It is, as you can see here:
https://github.com/streamlink/streamlink/blob/1ed85fcb24c6436f93c8e7ed9931e0266e7ee696/src/streamlink/stream/ffmpegmux.py#L146-L153

> I could not get the --hls-audio-select parameter to do anything

Use `--loglevel debug` to see which audio track has been selected.

Both languages `es` and `en` can be selected as audio track from your provided HLS URL. They appear to have the same content though, but this is not an issue Streamlink can solve.

```bash
streamlink \
  --loglevel debug \
  --stdout \
  --hls-audio-select es \
  --hls-duration 10 \
  'hls://https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d' \
  best \
  | ffprobe -v error -show_format -show_streams -print_format json - \
  | jq
```
```
[cli][debug] OS:         Linux-5.12.8-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.5
[cli][debug] Streamlink: 2.1.2+17.g05d293a
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=hls://https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --stdout=True
[cli][debug]  --hls-audio-select=['es']
[cli][debug]  --hls-duration=10
[cli][info] Found matching plugin hls for URL hls://https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d
[plugins.hls][debug] URL=https://nogeovod-fy.atresmedia.com/vsg/_definst_/assets4/2019/10/18/0A06B3DD-FD51-41C3-B6C1-6546B101ADB1/hls.smil/playlist.m3u8?pulse=assets4%2F2019%2F10%2F18%2F0A06B3DD-FD51-41C3-B6C1-6546B101ADB1%2F%7C1622689200%7C44f89040f2d842897911f74a6fd3842d; params={}
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 2160p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 1440p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 1080p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 720p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 480p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 360p (language=es, name=Spanish)
[stream.hls][debug] Using external audio tracks for stream 240p (language=es, name=Spanish)
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p, 1440p, 2160p (best)
[cli][info] Opening stream: 2160p (hls-multi)
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 107
[stream.hls][debug] Start offset: 0; Duration: 10; Start Sequence: 0; End Sequence: 107
[stream.hls][debug] Adding segment 0 to queue
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.hls][info] Stopping stream early after 10
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] First Sequence: 0; Last Sequence: 107
[stream.hls][debug] Start offset: 0; Duration: 10; Start Sequence: 0; End Sequence: 107
[stream.hls][debug] Adding segment 0 to queue
[utils.named_pipe][info] Creating pipe streamlinkpipe-130741-1-1402
[stream.hls][info] Stopping stream early after 10
[stream.segmented][debug] Closing worker thread
[utils.named_pipe][info] Creating pipe streamlinkpipe-130741-2-3059
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-130741-1-1402 -i /tmp/streamlinkpipe-130741-2-3059 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-130741-1-1402
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-130741-2-3059
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Download of segment 0 complete
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Download of segment 0 complete
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-130741-2-3059
[cli][debug] Writing stream to output
error: Error when writing to output: [Errno 32] Broken pipe, exiting
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
```json
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High",
      "codec_type": "video",
      "codec_tag_string": "[27][0][0][0]",
      "codec_tag": "0x001b",
      "width": 3840,
      "height": 2160,
      "coded_width": 3840,
      "coded_height": 2160,
      "closed_captions": 0,
      "has_b_frames": 2,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "16:9",
      "pix_fmt": "yuv420p",
      "level": 52,
      "chroma_location": "left",
      "field_order": "progressive",
      "refs": 1,
      "is_avc": "false",
      "nal_length_size": "0",
      "id": "0x100",
      "r_frame_rate": "25/1",
      "avg_frame_rate": "25/1",
      "time_base": "1/90000",
      "start_pts": 133200,
      "start_time": "1.480000",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_tag_string": "[15][0][0][0]",
      "codec_tag": "0x000f",
      "sample_fmt": "fltp",
      "sample_rate": "48000",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "id": "0x101",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 133200,
      "start_time": "1.480000",
      "bit_rate": "132864",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    }
  ],
  "format": {
    "filename": "pipe:",
    "nb_streams": 2,
    "nb_programs": 1,
    "format_name": "mpegts",
    "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
    "start_time": "1.480000",
    "probe_score": 50
  }
}
```

**Comment by Quaraxkad** [comment]
> 
> 
> > having ffmpeg in the environment path is apparently not enough
> 
> It is, as you can see here:
> 
> https://github.com/streamlink/streamlink/blob/1ed85fcb24c6436f93c8e7ed9931e0266e7ee696/src/streamlink/stream/ffmpegmux.py#L146-L153
> 

Unless I'm mistaken, that doesn't appear to check the PATH environment variable, it's looking specifically for an environment variable named ffmpeg-ffmpeg. That doesn't have anything to do with the PATH variable.
