### ISSUE TITLE
vod.walla.co.il / streaming provider Plugin request

### ISSUE THREAD

**Issue by D00oo00M** [streamlink/streamlink#3772]
Any chanse to add thats site to the plugins?
vod.walla.co.il

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by D00oo00M** [comment]
i dont understand why its not meet requirements?

**Comment by bastimeyer** [comment]
> Requests should be as detailed as possible and dedicated to only a single streaming service. Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.

> 6. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

**Comment by D00oo00M** [comment]
> > Requests should be as detailed as possible and dedicated to only a single streaming service. Information about the service as well as explicit URLs for live streams are required, as are details regarding the website, what it is, who runs it, how it adds to Streamlink, etc.
> 
> > 1. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

oh i see...
