### ISSUE TITLE
vaughnlive "error: Unable to validate response text: Minimum length is 3 but value is 1"

### ISSUE THREAD

**Issue by JourneyOver** [streamlink/streamlink#378]
Dunno when it happened exactly, but at some point today Vaughnlive must of updated something and broken streamlink, as any link to a stream I try always just results in it erroring out..

Example - 

``` 
streamlink http://vaughnlive.tv/chrisdave2 best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/chrisdave2
error: Unable to validate response text: Minimum length is 3 but value is 1
```
it pretty much does this for any stream url I use from vaughnlive, even tested with the nightly build and it does the same thing.

**Comment by gravyboat** [comment]
Unless this is a new change I believe it was fixed over here: https://github.com/streamlink/streamlink/pull/311, give the nightly build a shot: https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe

**Comment by JourneyOver** [comment]
think one of the main reasons they do it is because it circumvents their dumb ad thing that shows up on livestreams when ever you go to a livestream since as I recall livestreamer (streamlink) are the only two options that are able to show the livestreams without said ad since you can't place the ads on any media players and ad blockers don't seem to be able to block the ad without also blocking the whole video in the process. So they decide to break any functions to get around it whenever they can. :s

It's pretty much the same reason http://www.arconaitv.me/ stopped functioning in livestreamer because arconai decided he wanted to break everything so people have to view his dumb ads to watch the livestreams as well.

**Comment by thinkpad4** [comment]
There has to be a way to compensate for Vaughnlive changing the player version all the time

**Comment by Vangelis66** [comment]
Surely related, is @fadster actually proposing a fix?

https://github.com/chrippa/livestreamer/issues/1566

**Comment by beardypig** [comment]
@Vangelis66 yep, that is the new info url :)

**Comment by gravyboat** [comment]
I'm going to close this since #383 is merged. Thanks for the report @JourneyOver!

**Comment by JourneyOver** [comment]
@gravyboat yep looks like everything is working now in the nightly build *. so this can now be closed for now (going to go ahead and close it since you seemed to forget about closing it) >..< and it's not a problem at all, love that you guys have decided to fork livestreamer and keep things going ^^

*until Vaughn decides to go and break things again..

**Comment by beardypig** [comment]
@JourneyOver I'm working on a more robust fix, but I need to wait to see if it will actually work when the player version or info URL changes :-)

**Comment by JourneyOver** [comment]
@beardypig ah okay gotcha, well I'll re-open this for the time being then, and haha that would be nice if we could get something to work that'll always work even when Vaughn decides to break things again since vaughnlive is really the only place I ever watch tv show livestreams (that have shows on a loop) from much anymore since every other site I have tried since justin tv went down has sucked..

**Comment by fadster** [comment]
I haven't tested the automatic detection feature you've added but I wanted to share the latest INFO_URL in case it's not complete. Just an added underscore as of 03/10/2017:

INFO_URL = "http://mvn.vaughnsoft.net/video/edge/soon__depricated_Q2_2017-{domain}_{channel}-0?{version}_{ms}-{ms}-{random}"

**Comment by gravyboat** [comment]
There was a recent patch to account for that @fadster, thanks for the heads up.

**Comment by beardypig** [comment]
Going to close this as it has been fixed.
