### ISSUE TITLE
Zattoo: hls5: error: Unable to parse JSON: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by AdamNo** [streamlink/streamlink#3788]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [x] I am using the latest development version from the master branch.

### Description

requesting a hls5 stream results in error: error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0)

### Reproduction steps / Explicit stream URLs to test

[tvheadend@tvheadend42 /tmp]$ /home/tvheadend/.local/bin/streamlink --zattoo-email="xxxXXXxxx" --zattoo-password="xxxXXXxxx" --zattoo-stream-type hls5 -O "https://zattoo.com/watch/vox" best -o ~/tmp/out.ts
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/vox
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html><html lang="de" dat ...)

### Log output

[tvheadend@tvheadend42 /tmp]$ /home/tvheadend/.local/bin/streamlink --loglevel debug --zattoo-email="xxxXXXxxx" --zattoo-password="xxxXXXxxx" --zattoo-stream-type hls5 -O "https://zattoo.com/watch/vox" best -o ~/tmp/out.ts
[cli][debug] OS:         FreeBSD-11.3-RELEASE-p14-amd64-64bit-ELF
[cli][debug] Python:     3.6.9
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.7.0), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://zattoo.com/watch/vox
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=/home/tvheadend/tmp/out.ts
[cli][debug]  --stdout=True
[cli][debug]  --zattoo-email=*******
[cli][debug]  --zattoo-password=********
[cli][debug]  --zattoo-stream-types=['hls5']
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/vox
[plugins.zattoo][debug] _hello ...
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html><html lang="de" dat ...)

### Additional comments, etc.
does streamlink supports already hls7?
I would really like to get rid of dash because of its latency, no audio select, and so on...

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> - [x] I am using the latest development version from the master branch.

You are not using the **latest development** version.

> [cli][debug] Streamlink: 2.1.2

https://streamlink.github.io/install.html#pypi-package-and-source-code

Already fixed by:
#3780
#3773
