### ISSUE TITLE
youtube/ vlc android wrapper

### ISSUE THREAD

**Issue by tojestzart** [streamlink/streamlink#3793]
https://www.reddit.com/r/Streamlink/comments/o0fl39/android_doesnt_have_working_code/

As its said its expecting vlc as a linux distro instead of android

`streamlink https://youtu.be/mbWMBq6QnFw best                [cli][info] Found matching plugin youtube for URL https://youtu.be/mbWMBq6QnFw
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
[cli][info] Closing currently open stream...
~ $ cat ./streamlinkrc                                          player=am start -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -a android.intent.action.VIEW -d
player-http

~ $ streamlink https://youtu.be/mbWMBq6QnFw best
[cli][info] Found matching plugin youtube for URL https://youtu.be/mbWMBq6QnFw
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
[cli][info] Closing currently open stream...`

**Comment by bastimeyer** [comment]
Streamlink is expecting any player executable that can read from stdin and doesn't terminate immediately. If this doesn't work in your environment, then you have to launch the player separately and use one of the other stream transport methods mentioned in the documentation.

The default player is `vlc` on Linux and Streamlink will attempt to find this executable in one of the paths set in your `PATH` environment variable. A custom player can be set via `--player` and custom player arguments can be set via `--player-args`.

You are however not using the `--player` argument in any of your example commands and the `./streamlinkrc` file which you are trying to show is not being used as config file, as Streamlink's default config file paths on Linux are:
1. `${XDG_CONFIG_HOME:-${HOME}/.config}/streamlink/config`
2. `${HOME}/.streamlinkrc` (deprecated)
If you want to use a custom config file, then you'll have to set the `--config` argument.
