### ISSUE TITLE
How to debug what streamlink is doing? Got   urllib3/connection error

### ISSUE THREAD

**Issue by addstopbutton** [streamlink/streamlink#3796]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [-] I am using the latest development version from the master branch.

### Description

Hi guys!

Since some scared entity dropped support of a plugin, majority of streamlink fans used streamlink for,
I must ask for help in understanding streamlink action to try to figure out if I can fix it myself.

--debug= is not what I need

I need complete output of python plugins actions.

### Expected / Actual behavior

Some plugin is expected to work. Some time ago - it stopped.

### Reproduction steps / Explicit stream URLs to test

1. ...Install SL 1.7.0
2. ...Get fixed *** plugin
3. ...Receive an error, trying to open stream.

### Log output

```
[00:00:00,000][cli][debug] OS:         Linux-5.12.9-300.************-with-glibc2.33
[00:00:00,000][cli][debug] Python:     3.9.5
[00:00:00,000][cli][debug] Streamlink: 1.7.0
[00:00:00,000][cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.59.0)
[00:00:00,000][cli][info] Found matching plugin *** for URL *******.com/1234567890
error: ************** (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at ****************>: some error')))
```

### Additional comments, etc.

Looking forward for your understanding.
Cuz why one need a program, if one can't see, what's being done in case something is broken?

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by back-to** [comment]
> Streamlink: 1.7.0

update Streamlink https://streamlink.github.io/latest/install.html

> [00:00:00,000][cli][info] Found matching plugin *** for URL *******.com/1234567890

and if you want help don't censor everything

**Comment by addstopbutton** [comment]
@back-to update Streamlink https://streamlink.github.io/latest/install.html
Sideloaded plugin's support is dropped in higher versions, we both know that.
@back-to and if you want help don't censor everything
That was another bullshit, because you didn't want to answer on topic.

**Comment by back-to** [comment]
>  That was another bullshit, because you didn't want to answer on topic.

@addstopbutton
answer on what?

if you don't even share the **url** or **error**, there is nothing we can help you with.

plugin `***`
url `*******.com/1234567890` 
error `error: ************** (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at ****************>: some error')))`

is completely useless, **share some information with us if you want help.**

**Comment by addstopbutton** [comment]
@bastimeyer @beardypig @gravyboat anybody brave enough?

**Comment by addstopbutton** [comment]
@back-to 
> answer on what?
> 
> is completely useless, **share some information with us if you want help.**

If somebody stopped supporting some plugin, I can only ask for help in debugging streamlink action.
--debug don't give me this information, because it don't show, from where this problem originates - whether it's urllib's script or something with streamlink itself.
That's what I've asked for.

**Comment by bastimeyer** [comment]
You are not using the **latest version**. If a plugin got removed in an earlier version, for whatever reason, then you can sideload it, it just won't be maintained in Streamlink's master branch. And there won't be any support here for the plugin itself.

> anybody brave enough?

You also won't receive any support with that attitude. This is a free software project, not a commercial product, and support is being done by people in their free time. Nobody is obliged to help you, and by not providing actual information, nobody is even able to help.

**Comment by addstopbutton** [comment]
@bastimeyer 

> If a plugin got removed in an earlier version, for whatever reason, then you can sideload it, it just won't be maintained in Streamlink's master branch. And there won't be any support here for the plugin itself.
> 

Oh, I got it. Thank you, for pointing this out.
However, that's really strange, that no debug solution is still being existed, so I have to spotlight the problem to the site owners, so they again will brake it, **isn't that obvious?**

SL 1.7.0 is being used, because sideloading there is still allowed and something didn't like latest python - possibly, plugin.

**Everything worked fine until a few days.**


``` Found matching plugin c********e for URL **.com/****
error: Unable to open URL: https://c********e.com/get_edge_hls_url_ajax/ (HTTPSConnectionPool(host='c********e.com', port=443): 
Max retries exceeded with url: /get_edge_hls_url_ajax/ 
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at ******>: 
Failed to establish a new connection: [Errno 111] Connection refused'))) ```

It's problem with the plugin, streamlink or urllib?

Thank you!

**Comment by bastimeyer** [comment]
> SL 1.7.0 is being used, because sideloading there is still allowed

Sideloading is "still allowed" in `2.0.0`. `2.0.0` was a major version bump and APIs got updated/changed/fixed and deprecated stuff removed. Old and removed plugins may have become incompatible due to that, but that's none of Streamlink's problems. You will have to fix it yourself.

> Failed to establish a new connection: [Errno 111] Connection refused')))

This error however implies that something related to the site got changed. You will have to find another solution.

> c********e.com

NSFW plugins or any other out-of-tree plugin won't be supported. Good luck.

Also quite ironic that one of the reasons why NSFW plugins got removed was that exact attitude towards the maintainers.

**Comment by back-to** [comment]
@addstopbutton 

> It's problem with the plugin, streamlink or urllib?

**None**, the latest github version of the **old plugin** does still work (even with **1.7.0**)

if you are using the correct version, they might have blocked you.
