### ISSUE TITLE
log output with echo/grep/awk not print

### ISSUE THREAD

**Issue by MyGitHub5** [streamlink/streamlink#3822]
## Bug Report

- [x] This is a bug report and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

log output data about donwload not print with echo/grep/awk

on: Ubuntu Xenial (16.04 LTS)
streamlink 2.2.0

### Expected / Actual behavior

it's should print like normal

### Reproduction steps / Explicit stream URLs to test

any HLS http

### Log output

```
streamlink "hlsvariant://<XXX>/index.m3u8" 360p -o "test.ts"
[cli][info] Found matching plugin hls for URL hlsvariant://<XXX>/index.m3u8
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 360p (hls)
[download][..test.ts] Written 220.4 MB (7s @ 31.2 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...

echo $(streamlink "hlsvariant://<XXX>/index.m3u8" 360p -o "test.ts")
[cli][info] Found matching plugin hls for URL hlsvariant://<XXX>/index.m3u8
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
Not a bug, use [`--force-progress`](https://streamlink.github.io/cli.html#cmdoption-force-progress).

```bash
$ python -c 'import sys;print("interactive" if sys.stdout.isatty() else "non-interactive")'
interactive
$ echo "$(python -c 'import sys;print("interactive" if sys.stdout.isatty() else "non-interactive")')"
non-interactive
```

- https://docs.python.org/3/library/io.html?highlight=isatty#io.IOBase.isatty
- https://github.com/streamlink/streamlink/blob/07029669d58a835bd05029316211343eef78ddf2/src/streamlink_cli/main.py#L335-L339
