### ISSUE TITLE
mpc-hc skipped as default player, asking for vlc

### ISSUE THREAD

**Issue by stortzm** [streamlink/streamlink#3827]
small issue:
![image](https://user-images.githubusercontent.com/22046129/123467626-1b68e700-d5c7-11eb-9a18-d95dde8a8949.png)

for whatever reason, 2.2.0 is now asking for a path to MPC-HC inside config
it did not ask for it in 2.0.0 and 2.1.1

also:
this issue should be listed under
https://streamlink.github.io/players.html#known-issues-and-workarounds
'Specifying default player under configuration file'
or, just attempt to open the default player set by the system

**Comment by bastimeyer** [comment]
#3802
