### ISSUE TITLE
TF1 404 not found

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#3829]
Hi

Probably not a coincidence, but since the beginning of the euro, the tf1 stream isn't available.  all other channels from the tf1 site works though.
hard to tell if this is temporary. 

 streamlink -l debug "https://www.tf1.fr/tf1/direct"
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.5
[cli][debug] Streamlink: 2.1.2
[cli][debug] Requests(2.22.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.tf1.fr/tf1/direct
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugins.tf1][debug] Found channel tf1
[plugins.tf1][debug] Got dash stream https://tf1-das-live-ssl.tf1.fr/out/v1/0831eccf8eca417f805277549516caff/index.mpd?e=1624884962&st=ArbBGpXNM3y_J9yedQ405Q
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: und (using: und)
[plugins.tf1][debug] Got hls stream https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/master_3000000.m3u8?e=1624884962&st=vmM0cFeG886HOyc1qFt5vg
[utils.l10n][debug] Language code: en_US
error: Unable to open URL: https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/master_3000000.m3u8?e=1624884962&st=vmM0cFeG886HOyc1qFt5vg (404 Client Error: Not Found for url: https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/master_3000000.m3u8?e=1624884962&st=vmM0cFeG886HOyc1qFt5vg)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/3823#issuecomment-867113758

**Comment by campones** [comment]
thanks, didn't realize there was another release.
