### ISSUE TITLE
cdnbg: Can't load tv.bnt.bg/bnt1subs

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#3837]
## Plugin Issue

- [x] This is a plugin issue and I have read the contribution guidelines.
- [ ] I am using the latest development version from the master branch.

### Description

Streamlink can't handle the newest BNT livestream.

### Reproduction steps / Explicit stream URLs to test

1. streamlink http://tv.bnt.bg/bnt1subs
2. Failure to load

### Additional comments, etc.
This link seems to use a different player, as it runs subtitles (automatically generated ones that are fairly good). It's a very good stream for people that have a hearing disability.

**Comment by mkbloke** [comment]
**Feedback/answer (see ticked items):**

* As requested in the issue template:
* - [x] Does not meet requirements for issue or feature/plugin request [[1]] [[2]] [[3]]
* - [x] Description and/or reproduction steps are insufficiently detailed
* - [x] Streamlink version in use not specified
* - [x] Full ```--loglevel debug``` log output not provided
* - [ ] Research of prior issues/fixes appears to be insufficient [[4]]
* Other feedback:
* - [ ] Issue is out of scope and/or should be reported/help sought elsewhere
* - [ ] Issue appears to unnecessarily duplicate another issue that is open/closed
* - [ ] User appears to be using an outdated Streamlink version/plugin [[5]] [[6]]
* - [ ] Use of discussions more appropriate (admin can/will convert to discussion) [[7]]
* - [ ] Other (see below)
* Other: N/A

Please amend/close your issue accordingly and/or undertake the requested prior research before opening an issue in future.

[[1]] [Reporting issues][1]
[[2]] [Feature requests][2]
[[3]] [Plugin requests][3]
[[4]] [Search all open/closed issues/pull requests][4]
[[5]] [Install the most recent version of Streamlink][5]
[[6]] [Check the master branch for plugin updates][6]
[[7]] [Streamlink discussions][7]

[1]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#reporting-issues
[2]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#feature-requests
[3]: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
[4]: https://github.com/streamlink/streamlink/issues?q=
[5]: https://streamlink.github.io/install.html
[6]: https://github.com/streamlink/streamlink/tree/master/src/streamlink/plugins
[7]: https://github.com/streamlink/streamlink/discussions

**Comment by roshavagarga** [comment]
Log:
```C:\Users\aleks>streamlink http://tv.bnt.bg/bnt1subs --loglevel debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.2.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=http://tv.bnt.bg/bnt1subs
[cli][debug]  --loglevel=debug
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin cdnbg for URL http://tv.bnt.bg/bnt1subs
[plugins.cdnbg][debug] Found iframe: http://i.cdn.bg/live/iSj2d0XAPa
error: Unable to validate result: 'NoneType' object is not subscriptable or 'NoneType' object is not subscriptable or 'NoneType' object is not subscriptable```

**Comment by mkbloke** [comment]
Are you using a Bulgarian IP?  Does it play in the browser player?

**Comment by roshavagarga** [comment]
@mkbloke Yup, I am currently within Bulgaria and it does play through Firefox without any issues. If I remember correctly, only http://tv.bnt.bg/bnt4 plays with a foreign IP. You can think of all of these channels as the Bulgarian equivalent to BBC as far as being publicly owned, etc. I can suggest some basic proxies or run you a node if you'd like?

**Comment by roshavagarga** [comment]
Just to be clear, the stream that can not be opened is identical to one that can already be opened: http://tv.bnt.bg/bnt1

The only difference is it uses a different player and it offers subtitles that aren't hardcoded. I've never actually checked whether streamlink can forward subtitles in any manner, so if it can't, this is gonna be too much work probably.

**Comment by back-to** [comment]
> I've never actually checked whether streamlink can forward subtitles 

It will not work with Streamlink

> error: Unable to validate result: 'NoneType' object is not subscriptable or 'NoneType' object is not subscriptable or 'NoneType' object is not subscriptable```

this should work with https://github.com/streamlink/streamlink/pull/3838
