### ISSUE TITLE
Please make a plugin for (www)indostreamings(dot)com

### ISSUE THREAD

**Issue by lokmiin** [streamlink/streamlink#384]
Hello, streamlinker please help me to make a plugin for (www)indostreamings(dot)com also if possible 123movies(dot)com  thank U very much.

**Comment by back-to** [comment]
New domain _indostreamings.xyz_

I don't think it is worth it to support this website,

they use embeded `openload.co` streams

openload _"protects"_ there links with weird  java scripts
and they change it every month [(youtube-dl history)](https://github.com/rg3/youtube-dl/commits/master/youtube_dl/extractor/openload.py)

**Comment by gravyboat** [comment]
Thanks for that note @back-to, definitely looks like way too much work to maintain. I'm going to close this for now. If they get their act together and stop screwing around we can consider it at that point.
