### ISSUE TITLE
latest/current ubuntu packages stuck at v1.7.0

### ISSUE THREAD

**Issue by highflux7** [streamlink/streamlink#3851]
The current version of Streamlink is 2.2.0, however enabling the ubuntu repository via:
sudo add-apt-repository ppa:nilarimogard/webupd8
and installing the latest available from there results in version 1.7.0 being installed (1.7.0+dfsg-1~webupd8~focal).

Have emailed the package maintainer (Alin Andrei <andrew at webupd8.org>) with no response after many days.

Suggestions?

**Comment by mkbloke** [comment]
Just install master or the latest PyPI release [1] into a virtual environment [2].  I would suggest using master as it's easy to update to the latest plugin fixes.

[1] https://streamlink.github.io/install.html#pypi-package-and-source-code
[2] https://streamlink.github.io/install.html#virtual-environment

**Comment by bastimeyer** [comment]
As you can see on the PPA's package list, `2.1.2` is only available on Ubuntu "groovy" (20.10) and "hirsuite" (21.04), and `2.2.0` is not available at all. `1.7.0` is the latest available version on "bionic" (18.04 LTS) and "focal" (20.04 LTS).

http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/s/streamlink/

Packaging applications like Streamlink does not work well on Debian/Ubuntu, as you can see on the main package repos, and the PPA doesn't solve that:

- https://packages.debian.org/search?keywords=streamlink&searchon=names&suite=all&section=all
- https://packages.ubuntu.com/search?keywords=streamlink&searchon=names&suite=all&section=all

----

**Just download the latest AppImage, which is the simplest way of getting the latest version, regardless of your distro and its package management.**

Or install Streamlink via python-pip, either in the home directory of the current user or better, in a clean virtual environment.

https://streamlink.github.io/install.html#linux-and-bsd

> Please see the [PyPI package and source code](https://streamlink.github.io/install.html#pypi-package-and-source-code) or [AppImages](https://streamlink.github.io/install.html#appimages) sections down below if a package is not available for your distro or platform, or if it's out of date.
