### ISSUE TITLE
CNN Brasil website / Youtube Embed

### ISSUE THREAD

**Issue by viannaricardo** [streamlink/streamlink#3852]
## Plugin Request

- [x] This is a plugin request and I have read the contribution guidelines and plugin request requirements.
- [ ] I am using the latest development version from the master branch.

### Description

CNN Brasil is the newest news service in Brazil. They use YouTube to broadcast its live programming.

CNN Brasil uses specific YouTube URLs per live program they broadcast, which makes impossible to have one single URL added to streamlink to see CNN Brasil programming. 

I tried to point streamlink directly to CNN Brasil YouTube channel. But, because CNN Brasil also live streams its radio broadcast, adding /live to the YouTube channel website not always work. I might get CNN Brasil Radio live video, rather than the TV live broadcast.

### Example stream URLs

1. https://www.cnnbrasil.com.br/ao-vivo

Please keep in mind that CNN Brasil just broadcast its live programming in YouTube (typically from 6am to 10pm on Mon-Fri and limited times on weekends). So, if this URL is does not have YouTube video embedded, it's because there is no live programming at this time.

### Additional comments, etc.

[Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)

**Comment by bastimeyer** [comment]
> They use YouTube to broadcast its live programming.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 3. Sites which are primarily rehosting content that is available from a legitimate source

----

> But, because CNN Brasil also live streams its radio broadcast, adding /live to the YouTube channel website not always work.

Try the latest version from the `master` branch, which includes this commit 08a9f463bd8ed7240f77ddc18d4d3bb1305c93c3
