### ISSUE TITLE
Requesting the opposite of: --twitch-disable-reruns

### ISSUE THREAD

**Issue by AkitaAttribute** [streamlink/streamlink#3853]
## Feature Request

I would like to pivot on reruns to specifically place reruns into their own bucket.  Since the code already knows if it's a rerun, this shouldn't be too hard?

### Description

I think this is pretty self explanatory.

### Additional comments, etc.
Thanks :D

**Comment by bastimeyer** [comment]
Streamlink focuses on live streams, so it doesn't make much sense adding a plugin argument for disabling live streams.

----

Apart from that, **the "rerun" / "vodcast" / "playlist" / "watch_party" feature has been killed by Twitch last year**, see https://github.com/streamlink/streamlink-twitch-gui/issues/750#issuecomment-710206138

The Twitch API documentation is outdated and the error response when setting an invalid `stream_type` request parameter is invalid.

https://dev.twitch.tv/docs/v5/reference/streams#get-live-streams

> Name | Type | Description
> -- | -- | --
> stream_type | string | Constrains the type of streams returned. Valid values: `live`, `playlist`, `all`. Playlists are offline streams of VODs (Video on Demand) that appear live. Default: `live`.


```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams?stream_type=invalid&limit=1" \
  | jq
```
```json
{
  "error": "Bad Request",
  "status": 400,
  "message": "The parameter \"stream_type\" was malformed: value must be one of \"all\", \"live\", \"playlist\", \"watch_party\""
}
```


```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams?stream_type=playlist&limit=1" \
  | jq
```
```json
{
  "streams": []
}
```

```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams?stream_type=watch_party&limit=1" \
  | jq
```
```json
{
  "streams": []
}
```

----

The `stream_type` stream property still exists though and is set to `"live"` on live streams, which the `--twitch-disable-reruns` argument checks.

```bash
curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: pwkzresl8kj2rdj6g7bvxl9ys1wly3j" \
  "https://api.twitch.tv/kraken/streams?stream_type=all&limit=1" \
  | jq '.streams[] | [{_id: (._id), stream_type: (.stream_type)}]'
```
```json
[
  {
    "_id": 42766448685,
    "stream_type": "live"
  }
]
[
  {
    "_id": 42766912941,
    "stream_type": "live"
  }
]
[
  {
    "_id": 42767815117,
    "stream_type": "live"
  }
]
```

----

> into their own bucket

Not sure if that means that you're trying to query the Twitch API via Streamlink, but you shouldn't do that.
