### ISSUE TITLE
Streamlink works with newer episodes on crunchyroll but not older ones.

### ISSUE THREAD

**Issue by RobListon** [streamlink/streamlink#386]
From the CLI on a windows box "Streamlink.exe http://www.crunchyroll.com/chain-chronicle-the-light-of-haecceitas-/episode-4-the-light-of-haecceitas-726411 ultra" works fine but "Streamlink.exe http://www.crunchyroll.com/alderamin-on-the-sky/episode-1-a-stormy-encounter-715601 ultra"
The output from this command is:
[Streamlink for Windows v0.2.0 - Git b145d24]
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/alderamin-on-the-sky/episode-1-a-stormy-encounter-715601
error: Unable to open URL: https://api.crunchyroll.com/start_session.0.json (500 Server Error: Internal Server Error for url: https://api.crunchyroll.com/start_session.0.json?version=2313.8&access_token=<redacted>&session_id=uhuu0wtk33zrvsz20ljcj0rhf6ihwk0k&locale=enUS&device_id=<redacted>&device_type=com.crunchyroll.iphone&auth=sKEaPVyYxMT6V03LLlZ%2BMXCXVRpWQCgGXeAs35Lo8QvT3q4PVCEWvb6%2BdUjbADBvcqGw9OHDccAA07UyOjbjUX5L1fHtzpOYmBdFjBDuY%2BE%3D%3Ari0RUEDw4kuhIVjyKwi57A%3D%3D)
[End of Streamlink for Windows]

**Comment by gravyboat** [comment]
I actually get a similar error for both of these addresses.

**Comment by RobListon** [comment]
I'm seeing intermittent issues trying to view episodes now too. This must be some type of backend issue with crunchyroll tonight that just happened to look like a weird parsing issue.
Sorry to bug you about this.

**Comment by gravyboat** [comment]
@RobListon No worries, thanks for double checking and confirming it was on their end.
