### ISSUE TITLE
Sjonvarp.Stod2 (Iceland)

### ISSUE THREAD

**Issue by duunsupen** [streamlink/streamlink#3867]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

https://sjonvarp.stod2.is/live is a website from Iceland that offers 34 live TV channels, of which 9 can be watched without any log-in. For the remaining 25 channels a login including password is required. A Streamlink plugin would enable the audience to watch those nine free channels in excellent HD quality. They do not seem to be geo-blocked as I was able to watch them from Germany. The streams' URLs don't change.
The mentioned free channels are RÚV 1 HD, RÚV 2 HD, N4 HD, Hringbraut HD, Stöð ESport HD, Stöð 2 Kynning HD, Stöð 2 Visír HD,  Stöð 2 Sport Kynning HD and Sjónvarp Símans HD.
A plugin for this website would be a great addition to Streamlink.

### Input URLs

https://sjonvarp.stod2.is/live/1  (RÚV 1 HD)
https://sjonvarp.stod2.is/live/85 (RÚV 2 HD)
https://sjonvarp.stod2.is/live/67  (N4 HD)
https://sjonvarp.stod2.is/live/51 (Hringbraut HD)
https://sjonvarp.stod2.is/live/163  (Stöð ESport HD)
https://sjonvarp.stod2.is/live/159  (Stöð 2 Kynning HD)
https://sjonvarp.stod2.is/live/143  (Stöð 2 Visír HD)
https://sjonvarp.stod2.is/live/162 (Stöð 2 Sport Kynning HD)
https://sjonvarp.stod2.is/live/91 (Sjónvarp Símans HD)

**Comment by back-to** [comment]
**DRM**

`#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://==",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"`
