### ISSUE TITLE
blue TV Air free

### ISSUE THREAD

**Issue by putzipuh** [streamlink/streamlink#3876]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

swiss free TV streaming provider like zattoo but with better qually, 250 channels + some paytv chans if you want
its runned by swisscom. you need to register and a login to watch tv. it seems DRM free.

### Input URLs

https://tv.blue.ch/
https://tv.blue.ch/player/livetv/1221

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues/3397

**Comment by psp95** [comment]
Not possibile add plug-in blue tv?
