### ISSUE TITLE
error: This plugin does not support protected videos

### ISSUE THREAD

**Issue by 89z** [streamlink/streamlink#3877]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Using this:

https://github.com/streamlink/streamlink/releases/tag/2.2.0

### Debug log

I get this result:

~~~
PS C:\Program Files (x86)\Streamlink\bin> .\streamlink https://www.youtube.com/watch?v=1lRRWobNbU4
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=1lRRWobNbU4
error: This plugin does not support protected videos, try youtube-dl instead
~~~

I am confused, as its not a protected video, its just a normal video.

**Comment by back-to** [comment]
> I am confused, as its not a protected video, its just a normal video.

No it is not a normal video

` Licensed to YouTube by Kontor New Media Music (on behalf of A-ton)`
