### ISSUE TITLE
Change default HLS playlist reload time to 6 seconds rather than 15 to meet HLS spec recommendation

### ISSUE THREAD

**Issue by Hakkin** [streamlink/streamlink#3886]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

The current default playlist reload time for HLS is set to 15 seconds if there is no higher precedent reload time overriding it.
https://github.com/streamlink/streamlink/blob/e2c9032f9e879ca98460fa319e215b32165bd9e1/src/streamlink/stream/hls.py#L220
[It seems like this default has been in place since HLS was originally implemented 9 years ago.](https://github.com/streamlink/streamlink/commit/7909377651f8d85c76d9016b4c7e61d17a7a6d75)
[The current recommended target duration for HLS is 6 seconds](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#2969514). I think using this value as the default fallback makes more sense than 15 seconds. With 15 second reload times, it's somewhat likely for segments to expire between playlist reloads if the default reload time is selected for whatever reason.

**Comment by bastimeyer** [comment]
The default playlist reload time is derived from the `EXT-X-TARGETDURATION` tag, which is mandatory in every HLS media playlist:
https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.1

The value of 15 is the default before the actual reload time gets computed and it's a last resort value when there's no target duration (an invalid HLS media playlist) **and** when there aren't any segments in the playlist. If there are segments in the media playlist and there's no target duration or if it's zero, then the sum of segment durations from the number of segments of the current live edge value is used.
https://github.com/streamlink/streamlink/blob/e2c9032f9e879ca98460fa319e215b32165bd9e1/tests/streams/test_hls.py#L275-L354

There is no need to change this value unless it's somehow important to handle an edge case of an edge case. If you want to change it, then please send a pull request and fix up the test cases with new logical values.

**Comment by Hakkin** [comment]
I can't confirm it because I didn't have logging enabled, but I ended up changing this in my local fork because I think I hit the exact situation you talked about. When I initially requested the playlist, it returned a 404, thus setting the reload time to 15, and by the time the playlist reloaded again, the first few segments in it had already expired, so I missed the first few seconds of the stream.
In my mind, since the default is to use the playlist target duration if there is one, it makes sense to set to default if there ISN'T one to the target duration the HLS spec recommends.
