### ISSUE TITLE
eduplay

### ISSUE THREAD

**Issue by cgomesu** [streamlink/streamlink#3891]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

[**eduplay**](https://eduplay.rnp.br/portal/home) is a video and live streaming platform associated with the Brazilian Ministry of Science, Technology, and Innovation ([MCTI](https://www.gov.br/mcti/)) that provides free content related to education and research in Brazil.  Of note, their platform is used by the Brazilian public access channels [TV Brasil](https://tvbrasil.ebc.com.br/), [TV Escola](https://tvescola.org.br) e [Canal Saúde](https://www.canalsaude.fiocruz.br/), in addition to a few (State-regulated) higher education institutions (e.g., UnB, UPF, UFU) to host streams from public videoconferencing, workshops, research meetings, and lectures.

[According to the eduplay own documentation](https://ajuda.rnp.br/eduplay/), anyone can access the content for free at anytime and from anywhere.  Any other questions can be made via their service desk at [atendimento@rnp.br](mailto:atendimento@rnp.br).

- The various current **live streams** can be found at [https://eduplay.rnp.br/portal/live](https://eduplay.rnp.br/portal/live);
- Past live streams and **VODs** can be found at [https://eduplay.rnp.br/portal/videos](https://eduplay.rnp.br/portal/videos);
- **Radios** and other audios can be found at [https://eduplay.rnp.br/portal/audios](https://eduplay.rnp.br/portal/audios).

Examples URLs of live video streams:
- TV Brasil: https://eduplay.rnp.br/portal/tv/tvbrasil
- TV Escola: https://eduplay.rnp.br/portal/tv/tvescola
- Canal Saúde: https://eduplay.rnp.br/portal/tv/saude

Tested connections from the following exit nodes and successfully obtained live stream data:
- Brazil: 45.133.180.236
- Canada: 199.36.223.56
- Germany: 138.199.18.139

Finally, here's an example of live stream data as captured by Mozilla's network monitor:

![eduplay-stream-data](https://user-images.githubusercontent.com/50534116/127189466-3ab0512d-3cf1-4125-a043-ed6cd3b02a2b.png)

Example of a request for a `.m3u8`:
```json
{"GET":{"scheme":"https","host":"edge-go-01.eduplay.rnp.br","filename":"/media/ocp(r(uxqJWw)t(AAAAAAAAAAA)p(d(1V0)k(cto)m(IkN4nqHQgpo2Dnc7QMpF1Q)n(a(3SvKKEX2OOhT6h3pe_Y_EFfDaFcT3ac-)s(Q7o)'a(Kvu_4LKWWa79KhEoIpPBfg1d)s(E1o)))s(t(sQg)b(N3U2BrNIlr__FHGgSagEOxUNBPapU6wLgFdu5hPXv3n22-TGb3AbZpfiS1pTXHOIcor3Raeer_hlcpDs4U46ShP-0n7BsqnLVSk51ug78m5zYTubhun1nENFuNIPQqeswUOLV06S1NoQbXKpzW-QqrDOYlsltZ7WdhI7LCs)'t(opI)b(SlmvsQ63fGnFgfUmGie2Lo4LS_7WhRhHCyA)))/live_720_index.m3u8","remote":{"Address":"200.18.160.20:443"}}}
```

And a request for a `.ts` part:
```json
{"GET":{"scheme":"https","host":"edge-go-01.eduplay.rnp.br","filename":"/media/ocp(r(uxqJWw)t(AAAAAAAAAAA)p(d(1V0)k(cto)m(IkN4nqHQgpo2Dnc7QMpF1Q)n(a(3SvKKEX2OOhT6h3pe_Y_EFfDaFcT3ac-)s(Q7o)'a(Kvu_4LKWWa79KhEoIpPBfg1d)s(E1o)))s(t(sQg)b(N3U2BrNIlr__FHGgSagEOxUNBPapU6wLgFdu5hPXv3n22-TGb3AbZpfiS1pTXHOIcor3Raeer_hlcpDs4U46ShP-0n7BsqnLVSk51ug78m5zYTubhun1nENFuNIPQqeswUOLV06S1NoQbXKpzW-QqrDOYlsltZ7WdhI7LCs)'t(opI)b(SlmvsQ63fGnFgfUmGie2Lo4LS_7WhRhHCyA)))/live_720_20210727155404.ts","remote":{"Address":"200.18.160.20:443"}}}
```

(You can find both the `m3u8` and `ts` files I mentioned before in the following zip: [live_720_sample.zip](https://github.com/streamlink/streamlink/files/6888037/live_720_sample.zip).)

### Input URLs

1. https://eduplay.rnp.br/portal/tv/tvbrasil
2. https://eduplay.rnp.br/portal/tv/tvescola
3. https://eduplay.rnp.br/portal/tv/saude
4. https://eduplay.rnp.br/portal/tv/upftv
5. https://eduplay.rnp.br/portal/tv/TVU
6. https://eduplay.rnp.br/portal/tv/ufop
7. https://eduplay.rnp.br/portal/tv/unb-tv

**Comment by mkbloke** [comment]
Seems to meet all plugin requirements...

**Comment by mkbloke** [comment]
I've just been looking at this a bit more.  I may not have looked at all possible audio/video types available, but it seems the media source URL is available in the base HTML of the page, so I don't know if the maintainers would consider this worthy of a plugin to extract that, given that it  could be found by a browser extension and then used with Streamlink or played directly with a player like vlc or mpv.  For example:

https://eduplay.rnp.br/portal/video/142944
```
$ streamlink 'https://eduplay-maestro.prd.apps.kloud.rnp.br/route/transmission142856/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvdHJhbnNtaXNzaW9uMTQyODU2L2luZGV4Lm0zdTg_eD0xJm09RHRrV05vZnBoUVJrZjg0aDhLN0o0Zw&x=1&p=0&m=RM6ZTn3mYNm7aGe0BY3tVw'
[cli][info] Found matching plugin hls for URL https://eduplay-maestro.prd.apps.kloud.rnp.br/route/transmission142856/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvdHJhbnNtaXNzaW9uMTQyODU2L2luZGV4Lm0zdTg_eD0xJm09RHRrV05vZnBoUVJrZjg0aDhLN0o0Zw&x=1&p=0&m=RM6ZTn3mYNm7aGe0BY3tVw
Available streams: 360p (worst, best)
```
https://eduplay.rnp.br/portal/video/142248
```
$ streamlink 'https://eduplay-maestro.prd.apps.kloud.rnp.br/route/Fp7c_MurADg/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvRnA3Y19NdXJBRGcvaW5kZXgubTN1OD94PTEmbT1uY24xMWluWmcyQ0JGczA3RndHdERR&x=1&p=0&m=kTdCvsyVXHfEXt6kAJVrLQ'
[cli][info] Found matching plugin hls for URL https://eduplay-maestro.prd.apps.kloud.rnp.br/route/Fp7c_MurADg/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvRnA3Y19NdXJBRGcvaW5kZXgubTN1OD94PTEmbT1uY24xMWluWmcyQ0JGczA3RndHdERR&x=1&p=0&m=kTdCvsyVXHfEXt6kAJVrLQ
Available streams: 360p (worst), 480p (best)
```
https://eduplay.rnp.br/portal/audio/81750
```
$ mpv 'https://eduplay-maestro.prd.apps.kloud.rnp.br/route/Fi4KQSJ4p-Q/1598226498044.mp4?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvRmk0S1FTSjRwLVEvMTU5ODIyNjQ5ODA0NC5tcDQ_bT1qampKS21mU2V1cUlNLVdWdVh2UU1R&p=0&m=g3Hd9w3wzmi0F4ShhUUtQQ'
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:08 / 00:26:26 (0%) Cache: 45s/1MB
```
https://eduplay.rnp.br/portal/tv/saude
```
$ streamlink 'https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel10/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvY2hhbm5lbDEwL2luZGV4Lm0zdTg_eD0xJm09aTBDX29zanIyekRPekJSeTZCV2kxZw&x=1&p=0&m=bRFSTy3-cKxxHQWYUNL79Q'
[cli][info] Found matching plugin hls for URL https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel10/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvY2hhbm5lbDEwL2luZGV4Lm0zdTg_eD0xJm09aTBDX29zanIyekRPekJSeTZCV2kxZw&x=1&p=0&m=bRFSTy3-cKxxHQWYUNL79Q
Available streams: 360p (worst, best)
```
https://eduplay.rnp.br/portal/radio/embrapa
```
$ mpv 'https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel33337?s=aHR0cDovLzIwMC4yMDIuMTY2LjIzOTo4MDgw&p=0&m=EU2zk5kFQIzAsoIKC3T01A'
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:04 / 00:00:04 (85%) Cache: 0.4s/15KB
```

**Comment by cgomesu** [comment]
thanks for chiming in, @mkbloke .  indeed, it looks trivial to find the `m3u8` file and feed it to `streamlink` (or directly to `mpv` or any other player that supports it, as you pointed out).  I've been playing around with `curl` and `grep` for a few minutes now and the following seems to get the job done without the need of any additional plugins:

```
streamlink "$(curl -s "https://eduplay.rnp.br/portal/tv/tvbrasil" | grep -io "https://.*\.m3u8[^\']*")" best
```

I will take a closer look at this over the upcoming weekend and then report my findings here.

**Comment by cgomesu** [comment]
after further testing, I agree with @mkbloke that a plugin is not necessary because we can find the media source fairly easily via widely available cli tools. I've played with `curl` and `grep` a bit more and it looks like the regex `https://.*(m3u8|mp4|channel[0-9]+)\?s=[^\'|^\"]*` should be able to find the source of any video streams, audio streams, VODs, and static audio files from the **eduplay** platform.  here are two examples:

- (live streaming) [TV Brasil](https://eduplay.rnp.br/portal/tv/tvbrasil):
  ```
  curl -sL "https://eduplay.rnp.br/portal/tv/tvbrasil" | grep -ioE "https://.*(m3u8|mp4|channel[0-9]+)\?s=[^\'|^\"]*"
  ```
  ```
  https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel39285/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvY2hhbm5lbDM5Mjg1L2luZGV4Lm0zdTg_eD0xJm09TDNuSnB1MExfSElNUXJzcVVTU2ZCUQ&x=1&p=1&m=8xYHT-eKYjbsb_GOLzyKFQ
  ```

- (VOD) [RNP 30 Anos - evolução da rede Ipê](https://eduplay.rnp.br/portal/video/rnp-30-anos):
  ```
  curl -sL "https://eduplay.rnp.br/portal/video/rnp-30-anos" | grep -ioE "https://.*(m3u8|mp4|channel[0-9]+)\?s=[^\'|^\"]*"
  ```
  ```
  https://eduplay-maestro.prd.apps.kloud.rnp.br/route/FbBu5Z7rFuA/1562871103089.mp4?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvRmJCdTVaN3JGdUEvMTU2Mjg3MTEwMzA4OS5tcDQ_bT1hTnRWTUxucEl6UHkxbGpSY3FuZjF3&p=0&m=LtCCg4ZQjhlQ7dHniqALEA
  ```

---
from this point forward, we can use `streamlink` (or any player that supports the format) to play the media.  

live stream example using `streamlink` and `vlc`:
- (live streaming) [TV Brasil](https://eduplay.rnp.br/portal/tv/tvbrasil):
  ```
  streamlink "$(curl -sL "https://eduplay.rnp.br/portal/tv/tvbrasil" | grep -ioE "https://.*(m3u8|mp4|channel[0-9]+)\?s=[^\'|^\"]*")" best
  ```
  ```
  [cli][info] Found matching plugin hls for URL https://eduplay-maestro.prd.apps.kloud.rnp.br/route/channel39285/index.m3u8?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvY2hhbm5lbDM5Mjg1L2luZGV4Lm0zdTg_eD0xJm09TDNuSnB1MExfSElNUXJzcVVTU2ZCUQ&x=1&p=1&m=8xYHT-eKYjbsb_GOLzyKFQ
  [cli][info] Available streams: 720p (worst, best)
  [cli][info] Opening stream: 720p (hls)
  [cli][info] Starting player: /usr/bin/vlc
  [cli][info] Player closed
  [cli][info] Stream ended
  [cli][info] Closing currently open stream...
  ```

VOD example using `mpv`:
- (VOD) [RNP 30 Anos - evolução da rede Ipê](https://eduplay.rnp.br/portal/video/rnp-30-anos):
  ```
  mpv "$(curl -sL "https://eduplay.rnp.br/portal/video/rnp-30-anos" | grep -ioE "https://.*(m3u8|mp4|channel[0-9]+)\?s=[^\'|^\"]*")"
  ```
  ```
  Playing: https://eduplay-maestro.prd.apps.kloud.rnp.br/route/FbBu5Z7rFuA/1562871103089.mp4?s=aHR0cHM6Ly9tZWRpYS1wcmQuZWR1cGxheS5ybnAuYnIvbWVkaWEvRmJCdTVaN3JGdUEvMTU2Mjg3MTEwMzA4OS5tcDQ_bT1hTnRWTUxucEl6UHkxbGpSY3FuZjF3&p=0&m=LtCCg4ZQjhlQ7dHniqALEA
   (+) Video --vid=1 (*) (h264 1280x720 25.000fps)
   (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
  AO: [pulse] 44100Hz stereo 2ch float
  VO: [gpu] 1280x720 yuv420p
  AV: 00:00:05 / 00:01:48 (4%) A-V:  0.000 Cache: 16s+3MB
  ```

---
I'm satisfied with this solution, so I will go ahead and close this plugin request.
