### ISSUE TITLE
huya.com: Unable to open URL, Could not open stream

### ISSUE THREAD

**Issue by yeahjack** [streamlink/streamlink#3907]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When I use streamlink for huya.com, I got the message below

### Debug log

```text
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (HTTPConnectionPool(host="b''", port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041F34D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting
[cli][info] Found matching plugin huya for URL https://www.huya.com/25371574
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (HTTPConnectionPool(host="b''", port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04843590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting
[cli][info] Found matching plugin huya for URL https://www.huya.com/25371574
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (HTTPConnectionPool(host="b''", port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04763590>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting
Traceback (most recent call last):
  File "D:\Program Files\Streamlink\pkgs\streamlink_cli\utils\http_server.py", line 6, in <module>
    from BaseHTTPServer import BaseHTTPRequestHandler
ModuleNotFoundError: No module named 'BaseHTTPServer'
```

**Comment by bastimeyer** [comment]
Post the entire command while using the `--loglevel=debug` parameter, as requested by the issue form.
https://streamlink.github.io/latest/cli.html#cmdoption-loglevel

**Comment by yeahjack** [comment]
Sorry for not posting the log file, but there is not a folder called "streamlink" in %TEMP%\ (I am running Windows), I am a bit worried about what to do.

I am not sure whether this is useful, but these are contents printed in the command window:

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.6
[cli][debug] Streamlink: 1.6.0
[cli][debug] Requests(2.24.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin huya for URL https://www.huya.com/25371574
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream("http://b''/")> (Could not open stream: Unable to open URL: http://b''/ (503 Server Error: Service Unavailable for url: http://b''/))
error: Could not open stream <HLSStream("http://b''/")>, tried 1 times, exiting

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 1.6.0

This is not the latest version. The latest version is 2.3.0.
https://streamlink.github.io/latest/changelog.html

The stream is working fine on 2.3.0:
```
$ streamlink -l debug 'https://www.huya.com/25371574' best
[cli][debug] OS:         Linux-5.13.8-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.3.0+7.g2c8f0ba
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.huya.com/25371574
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin huya for URL https://www.huya.com/25371574
[plugins.huya][debug] QUALITY_WEIGHTS: {'source_al': -1, 'source_tx': 100, 'source_bd': 0}
[cli][info] Available streams: source_al (worst), source_bd, source_tx (best)
[cli][info] Opening stream: source_tx (http)
[cli][debug] Pre-buffering 8192 bytes
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --force-media-title=https://www.huya.com/25371574 -
[cli][debug] Writing stream to output
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by yeahjack** [comment]
omg, it's so silly of me to make this mistake... I was using the newest version and downgrade it for some reason. I am really sorry for my carelessness.
