### ISSUE TITLE
SponsorBlock integration

### ISSUE THREAD

**Issue by falcorr** [streamlink/streamlink#3914]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

SponsorBlock integration would be excellent. It's amazingly good at removing unwanted segments and customisable. 

While aimed at pre-recorded content, I think it could also be useful for streams. Perhaps by utilising a lengthy buffer, allowing these segments to be muted or their volume lowered, video dimmed, a custom watermark overlaid, or swapped out for other content, etc, or some combination of.

**Comment by bastimeyer** [comment]
If there are any ads in the output stream which disrupt Streamlink's functionality, eg. by introducing stream discontinuities, then this can/will be handled here. See the Twitch plugin for example. Postprocessing like muting or whatnot is not part of this project.
