### ISSUE TITLE
Update FFmpeg builds in Windows installer

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3931]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Motivation

Streamlink currently bundles FFmpeg builds in its Windows installer which are pulled from the [`streamlink/streamlink-assets`](https://github.com/streamlink/streamlink-assets) repo.

These FFmpeg binaries are pre-built and redistributed from [ffmpeg.zeranoe.com](https://ffmpeg.zeranoe.com/) which doesn't exist anymore. Since it's a third party source without any public build configs and logs, it has never been 100% trustworthy. The builds are also outdated by now (4.2.x).

### Solution

Streamlink should switch the source of the FFmpeg binaries and optionally build them from source.

The reason why the Zeranoe builds were chosen back then was that there was no easy to maintain build script for compiling FFmpeg on a CI platform in a stable container, and using pre-builts was simply the easiest way of bundling FFmpeg.

However, now there's the [`BtbN/FFmpeg-Builds`](https://github.com/BtbN/FFmpeg-Builds) repo available which is well maintained and organized, and it lets you select build targets with cross compilation and build variants. There are pre-built releases available, but not for x86, which Streamlink's Windows installer is currently built for. There are configs available though for x86/86_64, static/shared libs, gpl/lgpl, and master/4.4. Since it uses Github actions workflows, forking is dead simple.

**This means we have the following options available, which is why I'm opening this issue to ask for feedback:**

1. Switch the installer to x86_64 and bundle pre-built FFmpeg releases from `BtbN/FFmpeg-Builds`.
   Probably not a good idea to potentially exclude even more users considering that we've already excluded W7 a couple of days ago by switching to py39.
2. Fork `BtbN/FFmpeg-Builds` and replace the CI build config with the following options
   - `win32 gpl 4.4`
     Results in the same, but updated FFmpeg binaries
   - `win32 gpl-shared 4.4`
     The Zeranoe builds we had chosen are statically linked, which results in larger than necessary file sizes, so a switch to shared libs is very much welcome IMO.
3. Find a different source or build script
4. Keep everything as it is and ignore the issue

**Comment by back-to** [comment]
for now the best is probably `win32 gpl-shared 4.4`

**Comment by gravyboat** [comment]
I agree with @back-to that using the `win32` option is probably the best if we want to support everyone, but I'm actually in favor of option 1 with the x86_64 installer.

How many people are using 32 bit operating systems at this point? I would say the most accurate sample we can likely get is from the [Steam hardware survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=pc) which puts this number at a minuscule ~2%. They're either on an ancient system, or they're running some odd non-standard configuration. These are not paying users and we have no obligation to create more work for ourselves to support such a small fraction.

**Comment by bastimeyer** [comment]
> create more work

It's not more work if we want to build FFmpeg ourselves anyway. The only extra work is forking, removing those bits we don't need (I've already done that) and adding a different release config (which can be reused from other repos - like streamlink-appimage).

While I agree that running an x86 OS in 2021 is stupid (and using Windows itself as well), there's no reason to introduce an unnecessary breaking change.

I'll fork and push my changes tomorrow and see if it builds correctly. Then all that needs to be done is change the streamlink-assets config and bump it here in the makeinstaller script (if it's not already using the latest one anyway... need to check).

**Comment by bastimeyer** [comment]
I just realized that we're only including the statically linked ffmpeg.exe in the current installer. This means the shared libs build can be ignored.

----

I'm having a problem with the container deployment though. For some reason it doesn't have push access with the CI runner's github token. What's weird is that streamlink/appimage-buildenv does have the same setup and permissions. Could it be that repos flagged as forks don't have permissions?

- > denied: installation not allowed to Create organization package

  https://github.com/streamlink/FFmpeg-Builds/runs/3399117063?check_suite_focus=true#step:6:11
- https://github.com/streamlink/FFmpeg-Builds/blob/4064415b87cde39cb579bf9b2999650e21187dd2/.github/workflows/build.yml#L19-L31
- https://github.com/streamlink/appimage-buildenv/blob/fcce3945ab2517ca7fd062f07295fb34d42c561a/.github/workflows/main.yml#L43-L47

**Comment by bastimeyer** [comment]
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token

> Maximum access by forked repos
> read

:man_facepalming:
