### ISSUE TITLE
can you adapt to 4gtv.com

### ISSUE THREAD

**Issue by wzyxzy** [streamlink/streamlink#3968]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I like to watch TV of Taiwan , and I think this is many Chinese people's dream. Now we just watch Taiwan's TV from Youtube, but 4gtv.com has more Taiwan's TV streaming video. Would you add that host? like "https://www.4gtv.tv/channel_sub.html?channelSet_id=4&asset_id=4gtv-4gtv001&channel_id=2" it is free for everyone , and it will attract many people from Asia. Thank you.

**Comment by mkbloke** [comment]
More info (via a Google translated Wikipedia page) [here](https://translate.google.co.uk/translate?hl=en&sl=zh-TW&u=https://zh.wikipedia.org/wiki/%25E5%259B%259B%25E5%25AD%25A3%25E7%25B7%259A%25E4%25B8%258A4gTV&prev=search&pto=aue).

**Comment by mkbloke** [comment]
Not sure if rule 3 applies here.  Rule 6 might apply, but some of the channels are news, so that might be OK.  No idea about number 10...

**Comment by Trung0246** [comment]
![image](https://user-images.githubusercontent.com/11626920/134417453-2a6e495d-4d6d-4a0d-841d-ecc1e61299bc.png)
Uh geo-ip block? I'm not sure since I can't read Chinese.

**Comment by mkbloke** [comment]
> Uh geo-ip block? I'm not sure since I can't read Chinese.

Neither can I, but it translates to:

`This service is only available for viewing in Taiwan, Penghu, Jinma, and regions where you are not currently authorized, please forgive me! If you are already a user in Taiwan, Penghu, Jinma, and Matsu, please contact customer service: 02-8601-8068`
