### ISSUE TITLE
cdnwiz.com plugin req

### ISSUE THREAD

**Issue by Apollo2000** [streamlink/streamlink#397]
Hi,

If someone can make plugin for this CDN.

Example: http://live.ch20-cdnwiz.com/ch20-abr/ch20-abr/playlist.m3u8

Thank you.

**Comment by beardypig** [comment]
For HLS URLs you can use the builtin HLS support:
```sh
streamlink "hlsvariant://http://live.ch20-cdnwiz.com/ch20-abr/ch20-abr/playlist.m3u8" best 
```

**Comment by gravyboat** [comment]
Yep @beardypig is right, going to close this for now, feel free to re-open if you need to.
