### ISSUE TITLE
tests: python 3.10 issues

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#3971]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

The Linux test runner is emitting warnings:
https://github.com/streamlink/streamlink/runs/3471527885?check_suite_focus=true#step:8:220

```
tests/test_plugins.py: 160 warnings
  <frozen importlib._bootstrap_external>:572: DeprecationWarning: find_module() is deprecated and slated for removal in Python 3.12; use find_spec() instead

tests/test_plugins.py: 160 warnings
  <frozen importlib._bootstrap_external>:1514: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead

tests/test_plugins.py: 160 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
```

The Windows test runner is failing:
https://github.com/streamlink/streamlink/runs/3471527921?check_suite_focus=true#step:8:16

```
C:\hostedtoolcache\windows\Python\3.10.0-rc.1\x64\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:992: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:883: in exec_module
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
tests\plugins\__init__.py:1: in <module>
    from streamlink.plugin import Plugin
E   ModuleNotFoundError: No module named 'streamlink'
```

### Debug log

```text
-
```

**Comment by back-to** [comment]
> The Windows test runner is failing:

`Using legacy 'setup.py install' for lxml, since package 'wheel' is not installed.`

`Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?`
https://github.com/streamlink/streamlink/runs/3471527921?check_suite_focus=true#step:4:209

**lxml** issue, there is no wheel for win10 python3.10

https://pypi.org/project/lxml/4.6.3/#files
