### ISSUE TITLE
plugins.twitch: Twitch purple loading screen.

### ISSUE THREAD

**Issue by Engineer152** [streamlink/streamlink#3978]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Since there is no way to log into a twitch account, every 10 seconds I get the purple loading screen, would it be possible to run this using a twitch account? I would like to have an option to log into my account through selenium and have it save my information every time I open up a new stream.

### Debug log

```text
This is an issue from outside the plugin.
```

**Comment by bastimeyer** [comment]
Embedded ads:
- https://github.com/streamlink/streamlink/issues/3210#issue-710685043
- [`--twitch-disable-ads`](https://streamlink.github.io/cli.html#cmdoption-twitch-disable-ads)

Login:
- https://github.com/streamlink/streamlink/issues/2680#issuecomment-557605851
- [`--http-header "Authorization=OAuth YOUR_OAUTH_TOKEN_FROM_THE_TWITCH_WEBSITE_HERE"`](https://streamlink.github.io/cli.html#cmdoption-http-header)
