### ISSUE TITLE
Add streamlink to homebrew

### ISSUE THREAD

**Issue by widestm** [streamlink/streamlink#398]
It would be great to see streamlink added as a formula in homebrew as it's a very convenient way to keep everything up to date and in one place on mac osx.

**Comment by gravyboat** [comment]
This is a good idea, if you're interested in doing so or know someone who is feel free to open a PR! Looks like it requires extra work (http://docs.brew.sh/ and http://docs.brew.sh/Python-for-Formula-Authors.html) for Python because Homebrew is written in Ruby.

**Comment by widestm** [comment]
I could take a look at it myself first but cannot give any guarantees :)

**Comment by gravyboat** [comment]
@widestm Sounds good, if you don't have any luck please drop a comment here so we know you aren't working on it.

**Comment by mlindner** [comment]
FYI, generally python packages are not added to Homebrew. If you can install it with pip then it's not in Homebrew as a general rule because it adds complications with having to manage two sources of the same files which can possibly conflict with each other.

**Comment by mlindner** [comment]
Though I have seen that a couple of large packages end up in Homebrew like numpy or scipy, but smaller things likes requests or beautifulsoup don't.

**Comment by DylanSecreast** [comment]
If it's alright with everyone else, I I'm going to look into this and will open a PR when done.

**Comment by gravyboat** [comment]
@DylanSecreast If it goes against homebrew/python conventions as @mlindner noted we might not want to do it, but if you want to investigate and review those 'rules' and go from there that would be great. Just keep in mind we would definitely need to automate the release project since Streamlink is such a small team.

**Comment by DylanSecreast** [comment]
@gravyboat Sounds good. I'll look into it and report back to see if this is viable before implementing.

**Comment by bastimeyer** [comment]
Looks like streamlink has been added to homebrew a couple of days ago:
https://github.com/Homebrew/homebrew-core/blame/master/Formula/streamlink.rb

Why does the test at the bottom include an explicit youtube url to test?

**Comment by bastimeyer** [comment]
Closing the thread. A homebrew package has been added by the community and is now listed on the install page on the Streamlink website (#929).
If there are any issues regaring the package, please open a new thread or contact the creators of the package.
