### ISSUE TITLE
[META] Set up Bountysource

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#399]
I've claimed the Streamlink org page here: https://www.bountysource.com/teams/streamlink and claimed ownership of the team. They usually review these requests within 2 days and I just wanted to make a note of doing so here.

**Comment by bastimeyer** [comment]
Hm, when I click on this link, Bountysource is telling me that the team is still "maintained by the community"...

Btw, how does the Bountysource Github integration work? There must be an option somewhere that lets it modify new issues with an added footer asking the issue creator to set a bounty.

**Comment by gravyboat** [comment]
Sorry I forgot to update this, so I put in a request but they never responded (saying it takes 2 business days), so I tweeted at them: https://twitter.com/failvarez/status/823666198965387264 no response yet. I'm not sure how the integration works, I thought you had to do everything on Bountysource as I've never used it on any of my personal projects.

**Comment by gravyboat** [comment]
Still no update to the request or on Twitter, I'll try tagging here: @rappo who is managing the requests for bountysource team ownership at this point? Are you able to talk to them to review our request please?

**Comment by gravyboat** [comment]
We're all set to go now! https://www.bountysource.com/teams/streamlink/members

**Comment by rappo** [comment]
FYI the tag got my attention :)

**Comment by gravyboat** [comment]
Thanks @rappo!
