### ISSUE TITLE
Can't use streamlink2.0 on Virtual Private Server

### ISSUE THREAD

**Issue by ringtvt** [streamlink/streamlink#3996]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I use this code on Virtual Private Server
Streamlink --loglevel debug  -O "https://www.facebook.com/103101881740416/videos/305367681343983/" best --http-no-ssl-verify -o movie.mp4

### Debug log

```text
[cli][debug] OS:         Windows 2012ServerR2
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.3.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.facebook.com/103101881740416/videos/30536768134398
3/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=video.mp4
[cli][debug]  --stdout=True
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.ex
e
[cli][debug]  --http-no-ssl-verify=True
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/1031
01881740416/videos/305367681343983/
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/103101881
740416/videos/305367681343983/
```

**Comment by mkbloke** [comment]
This seems to be the same region based issue as #3615.

In this case, I can play the video via an AR IP address, but not from a UK IP address with Streamlink.

I can play the video in-browser via either IP address.
