### ISSUE TITLE
Stream error during commercial break ESPNPlayer.com

### ISSUE THREAD

**Issue by blueveno** [streamlink/streamlink#3997]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

i got m3u8 link from espn and play with hls normal. but stream error during commercial break:
streamlink "hlsvariant://https://content-aaps1-ur-fifa1.uplynk.com/channel/9abe27bd77be4cdc9a9c75012c7ac090/f.m3u8?oid=d09b16c953aa40c98dd8c513526aca5a&ad=espn_latamlive_en&ad.vast3=1&ad.vid=1332178d-9c34-45da-8534-212ad6db95c0&ad.tfcd=0&ad.adUnit=/intl_espnu/espnemea/null&ad.pp=espn-core-ssai&ad.vip=null&ad.ppid=&ad.description_url=null&ss_req=1&ad.ssss=vdms&ad.hl=en&ad.npa=0&ad.msid=null&ad.an=espnapp&ad.same_scor=1&ad.pod=enabled&ad.mridx=enabled&ad.cust_params=chan=intl_espnu%26authp=null%26nlsnAppID=null%26nlsnDevGrp=devgrp%2CUNWN%26vdm=live%26devOS=null%26devType=null%26plt=null%26swid=%26unid=null%26isDnt=0%26isAutoplay=0%26isMute=0%26vps=null%26stp=vdms%26hip=6664398dfa2f8e5b8fb7d5928baa8de1c45452cd7c7c7068628bd2b9b0342433%26lang=en%26ip=null&eid=espn_espnu_intl&ct=c&tc=1&exp=1630890577&rn=391602521&sig=04a260ac85a7fa451826f50e42871c80882177ebf8cb4f6fd35c57b434b0c213&pbs=b033cade3e5a4fdea3e73735634e0ca8" best -O   |  ffmpeg-re -i pipe:0 -video_size 1280x720 -c:v copy -c:a aac -ar 44100 -ab 128k -ac 2 -strict -2 -flags +global_header -bsf:a aac_adtstoasc -bufsize 3000k -f flv   "rtmp://x.rtmp.youtube.com/live2/0c5m-xk51-qkf6-zkf7-48372"

please how can i pass? thank you

### Debug log

```text
[flv @ 0000027ba337e700] Failed to update header with correct duration.5.7kbits/s speed=0.996x
[flv @ 0000027ba337e700] Failed to update header with correct filesize.
```

**Comment by bastimeyer** [comment]
HLS stream discontinuities are unsupported.
You're also clearly rehosting content on YT, so you won't receive any help here.
