### ISSUE TITLE
Any plans on a frontend like livestreamer-curses?

### ISSUE THREAD

**Issue by Hund** [streamlink/streamlink#40]
I've been using livestreamer and livestreamer-curses for a long time now. And I was really sad when Twitch did their thing and broke livestreamer-curses.

Would it be possible to perhaps use livestreamer-curses with streamlink somehow? Or perhaps fork and incorporate it into directly into streamlink? :)

**Comment by sbstp** [comment]
The API of livestreamer was not changed, It was only renamed. So if you contact the maintainers of `livestreamer-curses` and ask them to migrate to streamlink, it would only be a small change for them.

**Comment by Hund** [comment]
Ah! Well, the project has been dead for about 2 years now. And the developer has been inactive for over a year on GitHub now. :(

**Comment by sbstp** [comment]
Well, livestreamer wasn't updated for a year, so they don't have any reason to be active on the project. Maybe if you open an issue on their repo they'll be happy to help you.

Also, we have an [issue](https://github.com/streamlink/streamlink/issues/8) to revamp the interface, so you can share your opinion there.

**Comment by Hund** [comment]
There's two issues from jan and feb this year that's still hasn't gotten any attention. So I don't have any high hopes on that project.

I'll check out the issue! :)

**Comment by Junior1544** [comment]
Well, depending on how good you are with coding, you can try downloading the code and compiling it/running it yourself after making the changes from livestreamer to streamlink...

just a thought...

**Comment by Hund** [comment]
I'm no coder, but I could give it a shot. :)

**Comment by gravyboat** [comment]
The most active frontend project is https://github.com/bastimeyer/livestreamer-twitch-gui and the maintainer is pretty awesome, I'm going to close this for now, feel free to open it back up if you feel a need to do so.

**Comment by Hund** [comment]
I don't fancy GUIs, execpt for the web browser and GIMP. But I got it to work anyway, livestreamer-curses is using streamlink instead of livesteamer now. :)

**Comment by Junior1544** [comment]
Great job Hund!  Maybe you could make an update pull on Livestreamer-curses to work with streamlink?  Just a thought...   or, at least let them know about streamlink and that it's being worked on as a replacement for livestreamer?

**Comment by Hund** [comment]
Not a bad idéa. Will do!

**Comment by Brainzyy** [comment]
I made this, it's pretty bad and was made for personal use, but maybe someone else likes it too:
https://github.com/Brainzyy/streamlinkGUI

**Comment by Hund** [comment]
I'm getting a bit annoyed with livestreamer-curses now. Twitch allow streamers to automatically host other streamers when they're not streaming themself. This is resulting in a huge amount of streamers appearing online at all times. I want to watch the people I follow, not some random people they feel like hosting. :P

So, some kind of successor to livestreamer-curses would highly be appreciated. I really hope someone would do it, as I can't code for shit. :)

**Comment by gravyboat** [comment]
I think most of us are stretched pretty thin on Streamlink as is with our day jobs, there are a couple alternative projects which are still being maintained, maybe look into those? (I can't find the list right now but they are in some older/closed issues)

**Comment by stevek123** [comment]
Try this: https://github.com/bastimeyer/livestreamer-twitch-gui

**Comment by Hund** [comment]
I understand. :) I've been looking for new projects regularly, but I haven't found anything, yet - I hope.

But I'll try to find that list. Thanks!

**Comment by gravyboat** [comment]
@Hund https://github.com/bastimeyer/livestreamer-twitch-gui is one of them.

**Comment by Hund** [comment]
You have already tipped me about that client in this thread. ;) And my answer remain the same: I don't really fancy GUIs. If I did, I wouldn't be here bothering you guys. :D

**Comment by gravyboat** [comment]
@Hund Ahh looks like I did! Sorry about that, it's been a month or so and it appears I forgot.

**Comment by cirrusUK** [comment]
livestreamer-curses works with streamlink, just change command in livestreamer-cursesrc file. :)

**Comment by Hund** [comment]
@cirrusUK Thanks. I got it to work before. The issue know is that it shows channels as online if they host someone. :/

**Comment by cirrusUK** [comment]
@Hund  yup, same here.

**Comment by beardypig** [comment]
I've never used `livestreamer-ncurses` but maybe it works if you add `twitch-disable-hosting` to your `streamlinkrc` file, that will stop hosted channels from returning any streams.

**Comment by Hund** [comment]
Unfortunately it doesn't work, the only difference it makes is that is doesn't allow me to play the stream if it's a hosted stream.

**Comment by beardypig** [comment]
You can't have it both ways :) As far as streamlink is concerned a hosted channel is a valid stream, unless you disable hosting.

**Comment by Hund** [comment]
I know it's livestreamer-curses 'fault'. :) I have switched to streamlink-twitch-gui some time ago. And it's a great (!) GUI-client, the only issue is that I don't like GUIs. But I'm using it and I'm being happy with I have.

Perhaps this would is a golden moment for a old dog to learn some programming and eventually fork livestreamer-curses and update it.

**Comment by beardypig** [comment]
Do it! :)

**Comment by RadicalEd360** [comment]
ive written a **patch** for **livestreamer-curses**, it **makes it use streamlink** and it also adds some color, let me know what you guys think!!!
https://github.com/RadicalEd360/Patches/tree/master/livestreamer-curses-v1.5.2

**Comment by gravyboat** [comment]
@RadicalEd360 If you want to prep a PR that mirrors this one: https://github.com/streamlink/streamlink/pull/1096 we can review getting it added to the docs!

**Comment by RadicalEd360** [comment]
alright, sorry for not responding sooner, new to github, i will work on that, is there any guidelines or rules i should be aware of?

**Comment by bastimeyer** [comment]
@RadicalEd360 
See this file:
https://raw.githubusercontent.com/streamlink/streamlink/0.10.0/docs/thirdparty.rst
Example here:
https://raw.githubusercontent.com/streamlink/streamlink/0.10.0/docs/applications.rst
Or see the changes of PR #1096 @gravyboat was talking about:
https://github.com/streamlink/streamlink/pull/1096/files

Hope this helps 😃

**Comment by RadicalEd360** [comment]
thanks :D
