### ISSUE TITLE
question filmon.com HD

### ISSUE THREAD

**Issue by Apollo2000** [streamlink/streamlink#400]
Hi,

How to add account info for filmon.com HD?

Thank you.

**Comment by beardypig** [comment]
As far as I remember, logins for filmon.com are not supported. I don't have an account, so I cannot add it, maybe someone else with an account can add it. 
Unless you can donate an account for development :)

**Comment by karlo2105** [comment]
I don't think Filmon proposes HD. They air on two qualities LQ (360p) and HQ (480p). 
When their servers are not crowded, some channels air free on HQ so you can see how it looks like.

**Comment by beardypig** [comment]
@Apollo2000 do you have an example of a URL what you want supported? Does it require a login? Please provide as much information as possible.

**Comment by beardypig** [comment]
As of #508 I know of no streams that do not work, including the HQ streams, and doesn't not require a login.
