### ISSUE TITLE
plugins.schoolism: SSL certificate verify failed

### ISSUE THREAD

**Issue by fivetwelve** [streamlink/streamlink#4015]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

OS: macOS Catalina 10.15.7

I experienced the following error around Sept 8th but without issue prior to that:

`
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=376
error: Unable to open URL: https://www.schoolism.com/index.php (HTTPSConnectionPool(host='www.schoolism.com', port=443): Max retries exceeded with url: /index.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
`

My command: `streamlink https://www.schoolism.com/watchLesson.php\?type\=st\&id\=376 best -o part06.ts --schoolism-email MY_EMAIL --schoolism-password MY_PASSWORD --schoolism-part 6` 

I believe I was running v2.1.2 at the time so I upgraded (via homebrew) to 2.4.0 and continued to experience the same. The error occurs no matter what lesson or lesson part I switch.

I have no issues with my account, and am able to log in via browser. I was able to view the video in Brave and Safari. However, Chrome could not load the video file. I'm not sure if the streamlink error is related to the Chrome issue or not but Chrome displayed this in the browser's video player container:
`hlsjs: Video file not found
https://d8u31iyce9xic.cloudfront.net/28/5/part1.m3u8?Policy=CiAgICAgICAgICAgIHsgCiAgICAgICAgICAgICAgICJTdGF0ZW1lbnQiOiBbCiAgICAgICAgICAgICAgICAgIHsgCiAgICAgICAgICAgICAgICAgICAgICJSZXNvdXJjZSI6Imh0dHBzOi8vZDh1MzFpeWNlOXhpYy5jbG91ZGZyb250Lm5ldC8yOC81LyoiLAogICAgICAgICAgICAgICAgICAgICAiQ29uZGl0aW9uIjp7CiAgICAgICAgICAgICAgICAgICAgICAgICJEYXRlR3JlYXRlclRoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzMTU4Nzg1NX0sCiAgICAgICAgICAgICAgICAgICAgICAgICJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYzMTY3NDI1NX0KICAgICAgICAgICAgICAgICAgICAgfSAKICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdIAogICAgICAgICAgICB9CiAgICAgICAg&Signature=UTZMm~35SSuWGtk1TlSbobxO0yGzAD-UHZ8d2z8fdJ--8jsal8J3A2bIjYw~ZPH8euFApItvByo9GqB-GK76ThVasTo~IYCDjhO0YvJ4wqTS6yI1UXbX3f1BbvV-mvcgaIUDWVumJ4RSbvwA0S-8x2zQm8BBhqFEp1nfNdXbXZLr59elS3ow1YoAHhlEtLTMxVFdru0tTf90Yb7SR0mpZzSi6w4v0wjAAofQr2dBJgjy7zRf8nH6idv~VdFWqKMIM-x-Zdw8c-dkgt2Io~Yh57bFf966IA5wJQDkx8FB0QwMFvAzcWoxUaX06CQFQb5TJFtTNYzUy87y-5aOC96-lw__&Key-Pair-Id=APKAJHWRPDT6BGTTH7LA`

### Debug log

```text
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.schoolism.com/watchLesson.php?type=st&id=376
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="/Applications/_media/VLC.app/Contents/MacOS/VLC"
[cli][debug]  --output=part06.ts
[cli][debug]  --schoolism-email=MY_EMAIL
[cli][debug]  --schoolism-password=**********
[cli][debug]  --schoolism-part=6
[cli][info] Found matching plugin schoolism for URL https://www.schoolism.com/watchLesson.php?type=st&id=376
error: Unable to open URL: https://www.schoolism.com/index.php (HTTPSConnectionPool(host='www.schoolism.com', port=443): Max retries exceeded with url: /index.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))))
```

**Comment by bastimeyer** [comment]
> Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))

You can try [`--http-no-ssl-verify`](https://streamlink.github.io/latest/cli.html#cmdoption-http-no-ssl-verify), but if a site is using invalid TLS/SSL certificates then there's not much that can be done here.

> I was able to view the video in Brave and Safari. However, Chrome could not load the video file.

That's because some web browsers might not be using your system's TLS certificates for validating the servers and are using their own configuration. Chrome might depend on your system's config, same as python.

**Comment by fivetwelve** [comment]
Thanks for the reply. I tried the flag you suggested but ends up resulting in a `403 Client Error: Forbidden for url: https:CLOUDFRONT_URL`

So it sounds like it's a Schoolism-side issue then with their SSL cert? Just surprised that Brave (which is Chromium-based btw) and Safari negotiate it without issue while streamlink and Chrome but I confess I don't know—as you point out—what cert configurations the different clients are using.

**Comment by fivetwelve** [comment]
@bastimeyer I managed to get one success after multiple attempts, which for this plugin, is par for course. The flag allowed it to work. Testing without the flag resulted back to the initial issue. I'm going to close this issue and chalk it up to possibly Schoolism's cert wreaking havoc with user's client since Chrome was also experiencing issue.

Thanks again for your feedback and suggestion!
