### ISSUE TITLE
Plugin Request: https://dancestar.tv / https://vcndstv.teleosmedia.com

### ISSUE THREAD

**Issue by nickiman** [streamlink/streamlink#4028]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi,
I´m requesting this plugin from this page: https://dancestar.tv
Which it has a live stream for EDM videos and live sets. This WEB offers Live TV as well as an On Demand section with videos recorded.

Even having this page login credentials... this site has the Live TV stream without the need to make any login on it.

If I´m not wrong... provider for this stream is: https://vcndstv.teleosmedia.com

### Input URLs

**pageUrl**: https://www.dancestar.tv/video-player.php?streamType=L&menuGuid=167dc63e90b5e7f7568c5de7efe5e254&isByPassSrn=Y
**referrer**: https://dancestar.tv/video-player.php?streamType=L&menuGuid=167dc63e90b5e7f7568c5de7efe5e254&isByPassSrn=Y
**masterManifest** / **mediaManifest**: https://vcndstv.teleosmedia.com/stream/dstv/dstv/seglist_360p.m3u8
**masterManifest** / **mediaManifest**:https://vcndstv.teleosmedia.com/stream/dstv/dstv/seglist_720p.m3u8

Not sure if this is enough to know if it´s possible to create a new Plug-In for this page...

If you need anything else... just let me know.

Thanks and best regards

**Comment by mkbloke** [comment]
The main live stream seems to be a static URL which you can just use with Streamlink:
```
$ streamlink https://vcndstv.teleosmedia.com/stream/dstv/dstv/playlist.m3u8
[cli][info] Found matching plugin hls for URL https://vcndstv.teleosmedia.com/stream/dstv/dstv/playlist.m3u8
Available streams: 216p (worst), 360p, 540p, 720p (best)
```

**Comment by nickiman** [comment]
Oh! I didn´t know that... Thanks @mkbloke.
