### ISSUE TITLE
SRG SSR plugin

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#403]
Hello

Another challenge for beardypig. ;)
Swiss public TV includes channels in : 
- German : SRF 1, SRF 2, SRF Info : `http://www.srf.ch/play/tv/live`
- French : RTS Un, RTS Deux, RTS Info : `http://www.rts.ch/play/tv/direct`
- Italian : RSI La 1, RSI La 2 : `http://www.rsi.ch/play/tv/live`

Sometimes they air live sports events exclusively online on their website. 
Channels are of course geoblocked to CH but it can be resolved with proxy. 

Example address source for RTS Un can be found here :
`http://il.srgssr.ch/integrationlayer/1.0/ue/rts/video/play/3608506.json`

They propose HDS and HLS.

**Comment by beardypig** [comment]
I'll take a look, if I can find a decent Swiss proxy :-)

**Comment by beardypig** [comment]
@karlo2105 I had a go, I wasn't able to test it as I couldn't find a working Swiss proxy ...

**Comment by gravyboat** [comment]
This is added, if you could test it @karlo2105 and confirm we can close this.

**Comment by karlo2105** [comment]
Thanks very much I will give a try if i manage with working proxy. ;)

**Comment by karlo2105** [comment]
When I use proxy, it buffers a bit but with streamlink I got error on all channels. 
Take a look : 

`[cli][info] Found matching plugin srgssr for URL http://www.srf.ch/play/tv/live#
?tvLiveId=c4927fcf-e1a0-0001-7edd-1ef01d441651
error: Unable to open URL: http://il.srgssr.ch/integrationlayer/1.0/ue/c4927fcf-
e1a0-0001-7edd-1ef01d441651/video/play/srf.json (404 Client Error: Not Found for
 url: http://il.srgssr.ch/integrationlayer/1.0/ue/c4927fcf-e1a0-0001-7edd-1ef01d
441651/video/play/srf.json)
[End of Streamlink for Windows]`

Some additional addresses : 
----------------------------
SRF.ch
------
`http://www.srf.ch/livestream/player/srf-1`
`http://www.srf.ch/livestream/player/srf-2`
`http://www.srf.ch/livestream/player/srf-info`

Live sports events : you can find below events marked with small cam which will be broadcasted on their website
`http://www.srf.ch/sport/resultcenter/results`

RTS.ch
------
Live sports events 
`http://www.rts.ch/sport/programmes/`

RSI.ch
------
Live sports events
`http://live.rsi.ch/results.html`
Live streaming
`http://www.rsi.ch/live-streaming/`

I send you proxy on PM. 

Cheers.

**Comment by beardypig** [comment]
I have created a branch which fixes the issue with the site not working https://github.com/beardypig/streamlink/tree/srgssr. It also supports some of the live sports streams, but there is nothing streaming on rts.ch/sport/programmes/ currently.

**Comment by karlo2105** [comment]
Interesting. But as live events, sports or other are aired on channels websites could you merge it with srgssr plugin?

**Comment by beardypig** [comment]
The format of the page and the api for getting the streams are different so I think it's better to separate them rather than complicating the other plugin. It's a bit cleaner and more maintainable :-)

**Comment by karlo2105** [comment]
OK I understand your argument and I agree.  ;)
Anyway I just tested your fix on live channels, only RTS Info works, all other channels print this error. 

`"http://www.rts.ch/play/tv/direct#?tvLiveId=3608506" best
[cli][info] Found matching plugin srgssr for URL http://www.rts.ch/play/tv/direc
t#?tvLiveId=3608506
[cli][info] Available streams: 48k_alt, 288p_alt, 272p_alt, 360p_alt, 180p_alt,
48k (worst), 180p, 272p, 288p, 360p (best)
[cli][info] Opening stream: 360p (hls)
[stream.hls][error] Failed to open segment 247492385: Unable to open URL: http:/
/srgssruni9ch-lh.akamaihd.net/i/enc9uni_ch@191320/segment247492385_1200_av-p.ts?
sd=6&dw=0&rebase=on&id=AgCy0TO8TW2D5d2aglgENPPLk2QyvGRH2Hcy+hFy1gbsebw1D9wTMgeY+
0rUt2wIxlpKehgvb5Ejtg%3d%3d (403 Client Error: Forbidden for url: http://srgssru
ni9ch-lh.akamaihd.net/i/enc9uni_ch@191320/segment247492385_1200_av-p.ts?sd=6&dw=
0&rebase=on&id=AgCy0TO8TW2D5d2aglgENPPLk2QyvGRH2Hcy+hFy1gbsebw1D9wTMgeY+0rUt2wIx
lpKehgvb5Ejtg%3d%3d&hdnts=exp%3D1484954362~acl%3D%2Fi%2Fenc9uni_ch%40191320%2F%2
A~hmac%3D1faef2410bc4c1b55a47b65f5f01d51cb300e535f8a8beb50a86b0f6e6d5392c)`

I guess 360p_alt should be HDS. But I get same error as of HLS. 

If open this page with Swiss proxy you can see two addresses.
`http://il.srgssr.ch/integrationlayer/1.0/ue/rts/video/play/3608506.json`
 
`http://srgssruni9ch-lh.akamaihd.net/z/enc9uni_ch@191320/manifest.f4m`
`https://srgssruni9ch-lh.akamaihd.net/i/enc9uni_ch@191320/master.m3u8`

I think HDS is not recognized that's why I got same result with 360p and 360p_alt. 
HLS address uses HTTPS. Maybe that's the key for HLS. 

Regards.

**Comment by beardypig** [comment]
The auth parameters are already coming from that api. Unfortunately hls is the only option as the hds streams are encrypted using a method that we can't decrypt. 

I just tested `http://www.rts.ch/play/tv/direct#?tvLiveId=360850` using the proxy you gave me and it works just fine... Are you proxying all URLs both http and https?

**Comment by karlo2105** [comment]
When I just put --http-proxy switch I got this message. 

`error: Unable to open URL: https://srgssruni9ch-lh.akamaihd.net/i/enc9uni_ch@191
320/master.m3u8?dw=0 (403 Client Error: Forbidden for url: https://srgssruni9ch-
lh.akamaihd.net/i/enc9uni_ch@191320/master.m3u8?dw=0&hdnts=exp%3D1484962039~acl%
3D%2Fi%2Fenc9uni_ch%40191320%2F%2A~hmac%3D78b4297b4157da1e6dfe6220d1341099f9210f
9e8aa6004b6d6be711e281b6fd)`

With --https-proxy switch I got those messages from last post.

**Comment by karlo2105** [comment]
Now I tested live sports broadcast online for SRF and RSI I get same forbidden errors as above and for RTS.ch : 

`"http://www.rts.ch/sport/direct/8294153-tennis-daria-gavrilova-aus-timea-bacsinszky-sui.html" best
error: No plugin can handle URL: http://www.rts.ch/sport/direct/8294153-tennis-d
aria-gavrilova-aus-timea-bacsinszky-sui.html`

**Comment by beardypig** [comment]
@karlo2105 there is no support for rts sport yet. 

I don't understand why you are getting the forbidden errors. Can you PM me the exact command you are running with the proxy options you are using?

**Comment by karlo2105** [comment]
It has been solved. 
Thanks beardypig.

**Comment by beardypig** [comment]
I'll sort out rts sports when there is a live stream available and I'm on my PC at the same time.

**Comment by karlo2105** [comment]
@beardypig 
I figured out how RTS Sport works. 
There is currently live sports broadcast on : `http://www.rts.ch/sport/direct/8328501-tennis-open-daustralie.html`
This number in address `8328501` is a streaming ID. Normally it should redirect to address : `http://www.rts.ch/play/tv/tennis/video/tennis-open-daustralie?id=8328501`

**Comment by beardypig** [comment]
I'll take a look at it now.... 

(stupid close button, right next to comment)

**Comment by beardypig** [comment]
@karlo2105 I have updated the [srgsrr](https://github.com/beardypig/streamlink/tree/srgssr) branch  with support for RTS. I also renamed the plugin that supports SRF/RSI sport to `swisstxt`, as that's the streaming provide (owned by SRG SSR).

**Comment by karlo2105** [comment]
Thanks buddy everything is working. You did great job. 
Cheers ;)
