### ISSUE TITLE
plugins.viasat: Cannot play some shows

### ISSUE THREAD

**Issue by 18928172992817182** [streamlink/streamlink#4030]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Some links/streams do not work.

This works: 

https://www.viafree.se/program/underhallning/masterchef/sasong-15/avsnitt-1

This doesn't:

https://www.viafree.se/program/livsstil/lyxfallan/sasong-30/avsnitt-1

It looks like the URL pattern is similar so the problem must go deeper.

Will try and debug.

### Debug log

```text
[gustaf@tuxtop bin]$ streamlink --loglevel debug https://www.viafree.se/program/livsstil/lyxfallan/sasong-30/avsnitt-1 best
[cli][info] Loaded config from deprecated path, see CLI docs for how to migrate: /home/gustaf/.streamlinkrc
[cli][debug] OS:         Linux-5.13.4-200.fc34.x86_64-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.1.2+164.g24c59a2
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.1.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.viafree.se/program/livsstil/lyxfallan/sasong-30/avsnitt-1
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv --vf=vdpaupp=denoise=0.3:deint-mode=temporal-spatial:sharpen=0.5
[cli][info] Found matching plugin viasat for URL https://www.viafree.se/program/livsstil/lyxfallan/sasong-30/avsnitt-1
error: No playable streams found on this URL: https://www.viafree.se/program/livsstil/lyxfallan/sasong-30/avsnitt-1
```

**Comment by 18928172992817182** [comment]
When looking at the source on the page the _image_re manages to resolve both correctly: 

<meta property="og:image" content="https://playapi.viafree.tv/imagecache/1200x630/cloud/content-images/seasons/24463/1054402/0c9db60d1ad48f2e09f64f18a90d24f6.jpg">

and

<meta property="og:image" content="https://playapi.viafree.tv/imagecache/1200x630/cloud/content-images/inbox/1015687/e4002fa3368a261ddc8c5472395e73ff.jpg">

So, there must be something else.

So when I do: 

https://playapi.mtgx.tv/v3/videos/stream/1015687

I get a nice responce: 

```
{
  "streams": {
    "yospace_id": null,
    "medium": null,
    "high": null,
    "hls": "https:\/\/mtgxse04-vh.akamaihd.net\/i\/open\/20xxxxxx\/2060xxxx\/206038xx\/20603839\/7304a5579fde9d098f402ec591e277e7_20603839_572700_20200123T113826_,150,300,600,1200,2400,.mp4.csmil\/master.m3u8?__b__=300&hdnts=st=1581434985~exp=1672441200~acl=\/*~hmac=c97def68a9586a779e33207913f51e88c38357449ec7092c6c3ebc77db8bd469&cc1=name=Svenska~default=yes~forced=no~lang=sv~uri=https%3A%2F%2Fsubstitch.viafree.tv%2Fsubtitle%2Fconvert%2Fvtt%3Fsource%3Dhttps%3A%2F%2Fcdn-subtitles-mtgx-tv.akamaized.net%2Fpitcher%2F20xxxxxx%2F2060xxxx%2F206038xx%2F20603839%2F0370145710%2F20603839_sv.vtt%26output%3Dm3u8"
  },
  "is_geo_blocked": false,
  "_links": {
    "self": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/stream\/1015687"
    }
  }
}
```

but when I do:

https://playapi.mtgx.tv/v3/videos/stream/1054402

I get this:

```
{
  "streams": {
    "yospace_id": null,
    "medium": null,
    "high": null,
    "hls": null
  },
  "is_geo_blocked": false,
  "_links": {
    "self": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/stream\/1054402"
    }
  }
}
``` 

Hmm

**Comment by 18928172992817182** [comment]
Well this is interesting.

This works: 

https://playapi.mtgx.tv/v3/videos/1054402

```
{
  "id": 1054402,
  "season_id": 24463,
  "format_id": 1091,
  "channel_id": 7000,
  "yospace_id": null,
  "created_at": "2021-05-03T19:57:54+00:00",
  "updated_at": "2021-08-31T06:52:27+00:00",
  "publish_at": "2021-05-04T18:00:00+00:00",
  "unpublish_at": "2025-03-01T22:59:00+00:00",
  "is_rerun": false,
  ...
  "is_embeddable": false,
  "embed_allowed_domains": [],
  "is_geo_blocked": false,
  "age_limit": null,
  "_links": {
    "self": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/1054402"
    },
    "previous": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/1054402\/previous"
    },
    "next": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/1054402\/next"
    },
    "channel": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/channels\/7000"
    },
    "format": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/formats\/1091"
    },
    "season": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/seasons\/24463"
    },
    "stream": {
      "href": "https:\/\/playapi.mtgx.tv\/v3\/videos\/stream\/1054402"
    },
    "play_ios": {
      "href": "viafreeplaySE:\/\/video\/1054402"
    },
    ...
  }
}
```

It even links to the same stream URL that the plugin attempts to use: https://playapi.mtgx.tv/v3/videos/stream/1054402

So the plugin is doing what it should but the API responds with nothing.

**Comment by mkbloke** [comment]
On this site at least, there appears to be embedded JSON in the base HTML which contains the API links mentioned above:
```
"streamLink":{"href":"https:\u002F\u002Fviafree.mtg-api.com\u002Fstream-links\u002Fviafree\u002Fweb\u002Fse\u002Fclear-media-guids\u002F20603839\u002Fstreams","method":"get"}

"streamLink":{"href":"https:\u002F\u002Fviafree.mtg-api.com\u002Fstream-links\u002Fviafree\u002Fweb\u002Fse\u002Fclear-media-guids\u002F20670544\u002Fstreams","method":"get"}
```
I don't know about the other sites that the plugin currently supports, but looking at extracting that could be a way forward...

**Comment by mkbloke** [comment]
Also, the API gives a nice error string that can be passed to the user when they are outside the permitted region:
```
{"links":{"self":{"href":"/stream-links/viafree/web/se/clear-media-guids/20670544/streams","method":"GET","returnType":"ClearMediaResponse"}},"error":{"statusCode":403,"errorCode":1004,"name":"InvalidCountryError","description":"Client is not in a valid country"}}
```

**Comment by 18928172992817182** [comment]
> On this site at least, there appears to be embedded JSON in the base HTML which contains the API links mentioned above:
> 
> ```
> "streamLink":{"href":"https:\u002F\u002Fviafree.mtg-api.com\u002Fstream-links\u002Fviafree\u002Fweb\u002Fse\u002Fclear-media-guids\u002F20603839\u002Fstreams","method":"get"}
> 
> "streamLink":{"href":"https:\u002F\u002Fviafree.mtg-api.com\u002Fstream-links\u002Fviafree\u002Fweb\u002Fse\u002Fclear-media-guids\u002F20670544\u002Fstreams","method":"get"}
> ```
> 
> I don't know about the other sites that the plugin currently supports, but looking at extracting that could be a way forward...

I agree. I have been hesitant due to the other services. I am thinking that this could be an extra fallback case.

**Comment by mkbloke** [comment]
This plugin will likely require a full review across all its supported sites due to #4040, by the way.

**Comment by 18928172992817182** [comment]
I have started to go over this and check what needs to be done.

The following seem to be deprecated services: 

- tv6play.no
- juicyplay.dk

So we can exclude them.

**Comment by 18928172992817182** [comment]
Like you said @mkbloke viafree should be simple to implement. It is still owned by MTG.

Checking the others linked to this plugin: 

From play.tv3.ee: https://cdn6.tvplayhome.lt/vod/eds/go3_svod/20211004T0819/89352420/_/GO3_SVOD_DASH/89352420-mp4a_192000_est=1-init.mp4

From tv3play.skaties.lv:
https://cdn2.tvplayhome.lt/vod/eds/go3_svod/20211001T1850/89349635/_/GO3_SVOD_DASH/89349635-mp4a_128000_lav=5-211200000.mp4

So, they are using another underlying service than viafree. I wonder if you can find those sources from the MTG API endpoint.

The website does a request to fetch this: 

```
{
  "sources": {
    "DASH": [
      {
        "src": "//cdnlb.tvplayhome.lt/vod/eds/go3_svod/20211001T1850/89349635/_/GO3_SVOD_DASH/89349635.mpd",
        "aspectWidth": 16,
        "aspectHeight": 9
      }
    ],
    "HLS": [
      {
        "src": "//cdnlb.tvplayhome.lt/vod/eds/go3_svod/20211001T1850/89349635/_/GO3_SVOD_HLS/89349635.m3u8",
        "aspectWidth": 16,
        "aspectHeight": 9,
        "cert": "https://r.static.go3.tv/file/go3/resources/cert/fairplay/amb.cer"
      }
    ],
    "AZDIO_HLS": [
      {
        "src": "//cdnlb.tvplayhome.lt/vod/eds/go3_svod/20211001T1850/89349635/_/vHLS_VMX/89349635.m3u8",
        "aspectWidth": 16,
        "aspectHeight": 9
      }
    ],
    "SS": [
      {
        "src": "//cdnlb.tvplayhome.lt/vod/eds/go3_svod/20211001T1850/89349635/_/GO3_SVOD_SS.ism/Manifest",
        "aspectWidth": 16,
        "aspectHeight": 9
      }
    ]
  },
  "drm": {
    "FAIRPLAY": {
      "src": "https://tv3play.skaties.lv/api/products/3155236/drm/fairplay?platform=BROWSER&type=MOVIE&tenant=AVOD_LV",
      "cert": "https://r.static.go3.tv/file/go3/resources/cert/fairplay/amb.cer"
    },
    "WIDEVINE": {
      "src": "https://tv3play.skaties.lv/api/products/3155236/drm/widevine?platform=BROWSER&type=MOVIE&tenant=AVOD_LV"
    },
    "PLAYREADY": {
      "src": "https://tv3play.skaties.lv/api/products/3155236/drm/playready?platform=BROWSER&type=MOVIE&tenant=AVOD_LV"
    }
  }
}
```

If I try to do: https://playapi.mtgx.tv/v3/videos/3155236
Or: https://playapi.mtgx.tv/v3/videos/89349635

It returns nothing. So I wonder if these services are even backed by MTG?

Checking background: https://en.wikipedia.org/wiki/TV3_(Lithuania)

> TV3 Lithuania is a Lithuanian free-to-air television channel that was launched on 11 April 1993. It was owned by Modern Times Group (MTG) until 2017, when it was acquired by Providence Equity Partners for €115 million.

So I really don't think these should be the same plugin. Based on the background above those services probably haven't worked with streamlink for quite some time.

I could perhaps fix them but if nobody else has reported an issue with those services then I guess it is not used and would be unnecessary?

What do you think?

I am motivated to at least have a plugin for the viafree/MTG provided services but considering how incredibly deprecated this plugin is I might vote for just removing it altogether and replacing it with new fresh plugin.

**Comment by 18928172992817182** [comment]
Hello friends.

I have now made a new plugin for viafree that works great in the standard case. However I am having trouble with the subtitles if --mux-subtitles is provided.

This is the output I get: 

```
[cli][info] Found matching plugin viafree for URL https://www.viafree.se/program/underhallning/lyxfallan/sasong-30/avsnitt-1
[cli][info] Available streams: 98k (worst), 180p, 288p, 360p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[utils.named_pipe][info] Creating pipe streamlinkpipe-16615-1-4940
[utils.named_pipe][info] Creating pipe streamlinkpipe-16615-2-1798
[utils.named_pipe][info] Creating pipe streamlinkpipe-16615-3-7088
[utils.named_pipe][info] Creating pipe streamlinkpipe-16615-4-4797
[cli][info] Starting player: mpv
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-16615-3-7088
[file] Reading from stdin...
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-16615-1-4940
[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-16615-2-1798
[cli][info] Stream ended
[mkv] Unexpected end of file (no clusters found)

Exiting... (Quit)
[cli][info] Closing currently open stream...
```

Not sure what is wrong. Doesn't say much to me. I use the same syntax as in the svtplay plugin. Some plugins also provide some meta data to MuxedStream and I haven't figured out what that is used for yet. Well, at least I am nearly done.

**Comment by mkbloke** [comment]
>So I really don't think these should be the same plugin. Based on the background above those services probably haven't worked with streamlink for quite some time.

> I could perhaps fix them but if nobody else has reported an issue with those services then I guess it is not used and would be unnecessary?

Sorry for the delay in replying.  Personally, I agree.  Fix viasat and dump the rest due to apparent lack of use.

**Comment by 18928172992817182** [comment]
Alrighty.

I do think that we should rename the plugin to viafree though because the name viasat was/is linked to a specific service offer that has now been renamed to tv.allente.se.

This uses the same underlying features/services as viaplay, which includes services like viafree, tv4play, dplay, discovery and others which are separate plugins already in streamlink. So the viasat, or now allente, is just a concept of a collection of other services with their separate backend implementations gathered under one name.

The viasat/allente wrapper also requires authentication unlike viafree. You can authenticate with viafree to access more content from sibling services but it is not strictly necessary if you are only using the local viafree content.

So I think we should deprecate the name of the plugin as well because otherwise it is misleading. Viasat is no more. Instead this plugin is just named viafree now because that is what it supports.

It is supported in se,dk,no and fi.

**Comment by 18928172992817182** [comment]
I am really stuck with these subtitles.

```
[cli][info] Loaded config from deprecated path, see CLI docs for how to migrate: /home/gustaf/.streamlinkrc
[cli][debug] OS:         Linux-5.14.9-200.fc34.x86_64-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.1.2+183.ge255b96.dirty
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.viafree.fi/ohjelmat/entertainment/rupauls-drag-race/kausi-10/jakso-1
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --mux-subtitles=True
[cli][info] Found matching plugin viafree for URL https://www.viafree.fi/ohjelmat/entertainment/rupauls-drag-race/kausi-10/jakso-1
[plugins.viafree][debug] Subtitle=https://vod-subs-cdn1-vf-cdn-viaplay-tv.akamaized.net/b0bc145/20665028_sv-1616591650198.vtt
[plugins.viafree][debug] Subtitle=https://vod-subs-cdn1-vf-cdn-viaplay-tv.akamaized.net/182c879/20665028_no-1616591650198.vtt
[plugins.viafree][debug] Subtitle=https://vod-subs-cdn1-vf-cdn-viaplay-tv.akamaized.net/e9081ef/20665028_da-1616591650198.vtt
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 288p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 180p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 360p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 540p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 720p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 1080p (language=en, name=English)
[stream.hls][debug] Using external audio tracks for stream 98k (language=en, name=English)
[cli][info] Available streams: 98k (worst), 180p, 288p, 360p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[stream.ffmpegmux][debug] Opening hls-multi substream
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-1-2668
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-2-9898
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-12792-1-2668 -i /tmp/streamlinkpipe-12792-2-9898 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-1-2668
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-2-9898
[stream.ffmpegmux][debug] Opening http subtitle stream
[stream.hls][debug] First Sequence: 1; Last Sequence: 466
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 466
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[stream.hls][debug] First Sequence: 1; Last Sequence: 466
[stream.ffmpegmux][debug] Opening http subtitle stream
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 466
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[stream.ffmpegmux][debug] Opening http subtitle stream
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Adding segment 23 to queue
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Adding segment 23 to queue
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-3-757
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-4-7556
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-5-4386
[utils.named_pipe][info] Creating pipe streamlinkpipe-12792-6-6732
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Adding segment 24 to queue
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /tmp/streamlinkpipe-12792-3-757 -i /tmp/streamlinkpipe-12792-4-7556 -i /tmp/streamlinkpipe-12792-5-4386 -i /tmp/streamlinkpipe-12792-6-6732 -c:v copy -c:a copy -map 0 -map 1 -map 2 -map 3 -metadata:s:s:0 language=swe -metadata:s:s:1 language=nor -metadata:s:s:2 language=dan -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-3-757
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-4-7556
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-5-4386
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-12792-6-6732
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segment 3 complete
[stream.hls][debug] Adding segment 25 to queue
[stream.hls][debug] Segment 4 complete
[stream.hls][debug] Adding segment 26 to queue
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-12792-4-7556
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-12792-5-4386
[stream.ffmpegmux][debug] Pipe copy complete: /tmp/streamlinkpipe-12792-6-6732
[cli][info] Starting player: mpv
[cli.output][debug] Opening subprocess: mpv --force-media-title=https://www.viafree.fi/ohjelmat/entertainment/rupauls-drag-race/kausi-10/jakso-1 -
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gustaf/Develop/streamlink/venv/lib/python3.9/site-packages/streamlink/stream/ffmpegmux.py", line 68, in copy_to_pipe
    pipe.write(data)
  File "/home/gustaf/Develop/streamlink/venv/lib/python3.9/site-packages/streamlink/utils/named_pipe.py", line 62, in write
    return self.fifo.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

I have tried others with subtitles that I can access and that works. It seems like they all use the dash stream and not hls. However, Svtplay exposes in their API both dash and hls. So I though why not just add an HLS option there and see if it works there?

```
        for manifest in api_data['videoReferences']:
            if manifest['format'] == 'hls':
                for q, s in HLSStream.parse_variant_playlist(self.session, manifest['url']).items():
                    if self.get_option('mux_subtitles') and substreams:
                        yield q, MuxedStream(self.session, s, subtitles=substreams)
                    else:
                        yield q, s
            if manifest['format'] == 'dashhbbtv':
                for q, s in DASHStream.parse_manifest(self.session, manifest['url']).items():
                    if self.get_option('mux_subtitles') and substreams:
                        yield q, MuxedStream(self.session, s, subtitles=substreams)
                    else:
                        yield q, s
```

If I pick dash with mux_subtitles enabled it works. If I pick hls with mux_subtitles it ends up in a broken pipe. Am I doing something wrong or is it perhaps broken?

**Comment by 18928172992817182** [comment]
I started to search around and found this issue #2987: 

Adding:
```
--ffmpeg-audio-transcode aac
```

Then it works. Alright. So there must be an underlying bug here somewhere deeper than the plugins I guess since everyone using hls seem to be affected by this.

**Comment by bastimeyer** [comment]
> Viasat is no more. Instead this plugin is just named viafree now because that is what it supports.
> 
> It is supported in se,dk,no and fi.

Does viafree provide any live streams? I only see VOD content there.

**Comment by 18928172992817182** [comment]
> > Viasat is no more. Instead this plugin is just named viafree now because that is what it supports.
> > It is supported in se,dk,no and fi.
> 
> Does viafree provide any live streams? I only see VOD content there.

I believe it is only VOD content these days. But I can't say that I am checking that regularly. I did some searching and cannot see that they have had any live stream options.

**Comment by 18928172992817182** [comment]
Just going to leave this here. If anyone perhaps finds this later. 

I just realized that Youtube-dl has the same plugin: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/tvplay.py

There it is called TVPlay but it still works quite well with MTG services. Though they have not updated it either from the split and merge between NENT, MTG and the aforementioned services so only some of viafree works there right now.
