### ISSUE TITLE
roku

### ISSUE THREAD

**Issue by auburncodingclub** [streamlink/streamlink#4035]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Site has streaming TV & Film media.
Site is run by Roku?
Content is TV & film.

Should not be difficult.  Chunking mp4s -no more than user/pass should be required.  

I will gladly pay a bounty.

### Input URLs

https://therokuchannel.roku.com/watch/7ee2d6f508165430ba5baea17985a842

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 3. Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)

> 6. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

**Comment by mkbloke** [comment]
Is there any reason for leaving this open?  From what I can see, The Roku Channel on the website is pure VoD content with no livestreaming from the likes of TV news channels available.
