### ISSUE TITLE
Removal of Flash related streaming protocols

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4040]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I'm opening this thread as a proposal / checklist for the eventual removal of Flash related streaming protocols from Streamlink.

With the [official deprecation of Flash by Adobe in mid 2017](https://en.wikipedia.org/wiki/Adobe_Flash#End_of_life), streaming protocols based around Flash/RTMP have become obsolete. [Flash has already reached its end of life at the end of 2020 and has been removed from web browsers entirely](https://en.wikipedia.org/wiki/Adobe_Flash#End_of_life), meaning it has become irrelevant and so have the associated streaming protocols.

Streaming websites have switched to HLS or DASH a long time ago, and those few sites which are still using the obsolete streaming protocols are either outdated/unmaintained or located in regions where web technology doesn't move as fast (or at all).

Streamlink currently still includes `RTMP`, `HDS`, `AkamaiHD` and custom stream implementations. These either require third party binaries (RTMPdump) or libraries packaged with Streamlink ([`streamlink.packages.flashmedia`](https://github.com/streamlink/streamlink/commits/master/src/streamlink/packages/flashmedia)). Neither of these stream implementations or libraries are maintained.

At the time of writing this post, there are still a couple of plugins left which import those obsolete stream implementations. This is either because the plugins haven't been updated in the past several years and already include alternatives, or because some sites are still requiring them.

Then there are also the stream-protocol-plugins, which raises the question of how relevant these plugins are today if almost every site or application has switched to a more modern streaming protocol. For RTMP there's the exception that it's still being used for publishing streams to certain broadcasting sites, so I could see a potential use case here, but I'm not entirely sure how relevant it is for Streamlink.

----

## RTMPStream

- [x] [rtmp](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/rtmp.py) - protocol-plugin
- [x] [app17](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/app17.py) - HLS implemented
- [x] [brightcove](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/brightcove.py) - HLS implemented
- [x] [earthcam](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/earthcam.py) - HLS implemented
- [x] [okru](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/okru.py) - HLS+DASH implemented
- [x] [showroom](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/showroom.py) - HLS implemented
- [x] [tga](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/tga.py) - Plugin removed
- [x] [tv5monde](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/tv5monde.py) - HLS implemented
- [x] [viasat](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/viasat.py) - plugin removed (VODs only)

## HDSStream

- [x] [hds](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/hds.py) - protocol-plugin
- [x] [bbciplayer](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/bbciplayer.py) - HLS implemented (region locked)
- [x] [viasat](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/viasat.py) - plugin removed (VODs only)

## AkamaiHDStream

- [x] [akamaihd](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/akamaihd.py) - protocol-plugin

## Custom stream implementations

- [x] [ustreamtv](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/ustreamtv.py) - `FLVTagConcat` import removed (segmented Flash video streams), plugin completely rewritten with new fragmented MPEG4 streams

----

Removing these stream implementations would remove a lot of cruft from Streamlink and clean up lots of code, which is very much welcome since the dependencies are not maintained. The question is though whether it's possible to update every plugin and what we should do with those which can't be updated.

A removal of stream implementations would obviously require a major version bump. This could ideally be done when py36 gets dropped in the future (which will see its EOL on 2021-12-31).

There was also the attempt to add a CodeQL CI runner for analyzing code last year, which failed because the unmaintained code could not be excluded properly from the results. Removing all this unmaintained code would enable code quality/security analysis via GitHub's CodeQL. It would also help with additional code linters / linting configs, as nobody wants to touch unmaintained code, so the actually maintained code could be improved at some point.

----

Thoughts? Opinions? Concerns?

**Comment by gravyboat** [comment]
> The question is though whether it's possible to update every plugin and what we should do with those which can't be updated.

If they can't be updated they should be removed. Flash is EoL, if a site is still using it that's their problem not ours. We don't support unmaintained or EoL software.

I'm all in favor of this and have no concerns. It's the correct way forward for maintainability. If people don't like it they can fork.
