### ISSUE TITLE
error while loading shared libraries: ?: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TomArrow** [streamlink/streamlink#4055]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

(Win 7 64-bit Ultimate)

After installing 2.4.0, I get this every time I type the streamlink command in Git bash:
```
C:/Program Files (x86)/Streamlink/bin/streamlink.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
I can't post a debug log because adding any options whatsoever (including --loglevel debug) does absolutely nothing, I just get the same error.

When I type streamlink into normal CMD, I get this as a popup:
```
python.exe - System Error
The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem
```
and no other output, no matter if loglevel is set or not.

Didn't happen with the older streamlink version I had, but it's been months old. Don't remember which version it was.

### Debug log

```text
Can't because program won't even get that far.
```

**Comment by gravyboat** [comment]
Windows 7 is EoL and we're no longer supporting it as of Streamlink 2.4.0. Check the [release notes](https://github.com/streamlink/streamlink/releases)

**Comment by pboettcher** [comment]
Oh gosh! You are forcing me to buy a new laptop :)

**Comment by bastimeyer** [comment]
https://streamlink.github.io/latest/install.html#windows-stable-installers
