### ISSUE TITLE
Plugin options do not get set during plugin initialization

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4091]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Plugin options currently do not get set during plugin initialization and are only available when `Plugin.streams` is called, which is too late when certain setups are required during init which depend on the provided options (see #4080).

The reason for this is how the plugins get resolved.

This is the current `Session.resolve_url()` method, which returns a new instance of a matching plugin which it then caches for the passed input via the `lru_cache` decorator:
https://github.com/streamlink/streamlink/blob/1a1a3a06a2655f299fd718f5343799ec13ec7ce4/src/streamlink/session.py#L344-L377

The first time the plugin gets resolved is in `streamlink_cli.main.setup_config_args()`, as it needs to find a plugin config file for the input URL, so that plugin specific configs can be set:
https://github.com/streamlink/streamlink/blob/1a1a3a06a2655f299fd718f5343799ec13ec7ce4/src/streamlink_cli/main.py#L683-L694
A plugin instance is not required here, because all that's needed is the plugin name, so only the plugin class should be resolved instead.

The second time the matching plugin gets resolved (from cache) is in `streamlink_cli.main.handle_url()`:
https://github.com/streamlink/streamlink/blob/1a1a3a06a2655f299fd718f5343799ec13ec7ce4/src/streamlink_cli/main.py#L563-L565
As you can see, it resolves the plugin instance and afterwards sets up the plugin options via `setup_plugin_options(streamlink, plugin)`, which means the options are set too late.

`setup_plugin_options` however doesn't need a plugin instance. All it needs is the plugin name and its arguments, which is a class attribute.
https://github.com/streamlink/streamlink/blob/1a1a3a06a2655f299fd718f5343799ec13ec7ce4/src/streamlink_cli/main.py#L881-L913

This means that the session's `resolve_url` needs to be changed (or extended with an initialize keyword), or its calls be replaced in the cli.main module with another method which resolves plugin classes instead. Then the resolved plugin could be initialized after the options have been set.

----

What's the best solution for this?

- changing `Session.resolve_url` is a significant breaking change
- extending it with an optional keyword doesn't fix the issue for third party python projects implementing streamlink if we keep backwards compatibility
- neither does adding another method for only resolving plugin classes to `Session`

### Debug log

```text
-
```

**Comment by gravyboat** [comment]
> changing Session.resolve_url is a significant breaking change

I'm not too concerned about breaking changes. If someone is using free software in their project and they don't like it they can fork us. We are beholden to no one.

> extending it with an optional keyword doesn't fix the issue for third party python projects implementing streamlink if we keep backwards compatibility

Keeping backwards compatibility this way seems like more work without much benefit. What would we gain by doing this? Same for the third proposal.
