### ISSUE TITLE
plugins.funimationnow: Could not find experience ID

### ISSUE THREAD

**Issue by jcdark** [streamlink/streamlink#4093]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

After the last Funimation update in October 2021 the plugin stopped working reporting an error: 

**[plugins.funimationnow][error] Could not find experience ID?!**

Even passing the Cookie on http-cookie, the plugin can no longer download Episodes.

Could someone help with a solution?

### Debug log

```text
C:\Users\jcdar>streamlink -l debug --funimation-email "xxxxx@gmail.com" --funimation-password "xxxxxx" --http-cookie "incap_ses_1312_998813=XXXXX" --http-cookie "visid_incap_998813=XXXXX" --output "Deca-Dence_-_S01E11.por.mp4" "https://www.funimation.com/v/deca-dence/engine/" best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.funimation.com/v/deca-dence/engine/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=Deca-Dence_-_S01E11.por.mp4
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --http-cookie=[('incap_ses_1312_998813', 'xxxxxx'), ('visid_incap_998813', 'xxxxxx')]
[cli][debug]  --funimation-email=xxxxxx@gmail.com
[cli][debug]  --funimation-password=********
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/v/deca-dence/engine/
[plugins.funimationnow][error] Could not find experience ID?!
error: No playable streams found on this URL: https://www.funimation.com/v/deca-dence/engine/
```

**Comment by mkbloke** [comment]
It looks like things have changed quite a bit.  I think this plugin will need a complete rewrite.
