### ISSUE TITLE
Support not showing hosted streams

### ISSUE THREAD

**Issue by larryhastings** [streamlink/streamlink#41]
Streamlink has a new feature over livestreamer: if a Twitch stream isn't currently streaming, but in its metadata it's "hosting" another stream, display that stream instead.  I don't actually want this feature; if the original streamer isn't streaming, I don't want streamlink to do anything.

It looks like this feature is intended to be supported; there's a Twitch plugin configuration setting called "allow_host".  But AFAICT the setting is ignored.

**Comment by gravyboat** [comment]
Good point, we'll have to add an option for this @cdrage we'll probably want to see about adding this for the command line revamp.

**Comment by cdrage** [comment]
@gravyboat i'm going to have a look at the "click" library and see what we can do about cleaning shit up. I'd love to have a similar feature like this as well as a complete CLI revamp so it's much much easier.

I'll propose this in a later issue / PR once I have a bit of time.

**Comment by gravyboat** [comment]
@cdrage I started writing a very simple app that uses click to try and play with it: https://github.com/gravyboat/ididthis/blob/master/ididthis/idt.py, it's pretty good, though Py3 compatibility is my main concern (as noted here: http://click.pocoo.org/5/python3/)

**Comment by larryhastings** [comment]
Is streamlink Python 3 only?

**Comment by gravyboat** [comment]
@larryhastings Nope, there are just some limitations imposed by Python3 on most CLI libraries.

**Comment by sbstp** [comment]
I think what @larryhastings is saying is that `click` is Python 3 only. Using it would break compat. with Python 2.

**Comment by gravyboat** [comment]
@sbstp @larryhastings Click supports both Python 2 and Python 3. It's just worth noting the caveats on Python 3.

**Comment by sbstp** [comment]
Oups, my bad. I thought click was Python 3 only.

**Comment by sbstp** [comment]
Closed by #53. Let us know if you have issues with the new version.
