### ISSUE TITLE
vix.com 

### ISSUE THREAD

**Issue by barra51** [streamlink/streamlink#4101]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

First of all, thank all developers putting efforts for this incredible tool!

vix.com is a site that stores different series and movies. Owner of that site: "Batanga Media"
Im not really sure if the content is protected by DRM. The content hosted there is free for everyone.

### Input URLs

https://www.vix.com/tv/on-demand

(Since Im in Mexico the content could be different for people in US)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 6. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted
