### ISSUE TITLE
Openrec.tv: cannot get stream from subscription live stream

### ISSUE THREAD

**Issue by fireattack** [streamlink/streamlink#4122]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Cannot access to subscription-only live stream.

I tried the channel that I'm subscribed to (premium), or the ones that currently is on free-trial (so everyone can watch), neither worked.

### Debug log

```text
D:\>streamlink --openrectv-email="****" --openrectv-password="****" --loglevel debug --url https:/
/www.openrec.tv/live/lv81d9lm789
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.7
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.58.0)
[cli][debug] Arguments:
[cli][debug]  url=https://www.openrec.tv/live/lv81d9lm789
[cli][debug]  --loglevel=debug
[cli][debug]  --player="D:\Program Files\SMPlayer\mpv\mpv.exe" --cache=yes --demuxer-max-bytes=10000KiB
[cli][debug]  --url=https://www.openrec.tv/live/lv81d9lm789
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=D:\Program Files\!cli\ffmpeg.exe
[cli][debug]  --openrectv-email=****
[cli][debug]  --openrectv-password=********
[cli][info] Found matching plugin openrectv for URL https://www.openrec.tv/live/lv81d9lm789
[plugins.openrectv][debug] Logged in as ****
[plugins.openrectv][debug] Got valid detail response
[plugins.openrectv][debug] Found video: きどまだSeason2　＃16 (lv81d9lm789)
error: No playable streams found on this URL: https://www.openrec.tv/live/lv81d9lm789
```

**Comment by vinyl-umbrella** [comment]
Hello @fireattack 
Probably I can solve your issue, but I don't subscribe any paid channels, so I can't do the experiment.
So, I would like to know the response of `https://apiv5.openrec.tv/api/v5/movies/lv81d9lm789/detail` when you access `https://www.openrec.tv/live/lv81d9lm789` using DevTools.
In particular, I would like to know `data.items[0].media`.
Please let me know **only whether each value is null or not** because it contains sensitive information.

**Comment by fireattack** [comment]
```json
{
    "status": 0,
    "data": {
        "type": "movie_detail",
        "items": [
            {
                "media": {
                    "url": "XXX/playlist.m3u8",
                    "url_source": null,
                    "url_public": "XXX/public.m3u8",
                    "url_low_latency": null,
                    "url_ull": null,
                    "url_dvr": null,
                    "url_trailer": null,
                    "url_audio": "XXX/aac.m3u8",
                    "url_dvr_audio": null
                },
                "subs_trial_media": {
                    "url": null,
                    "url_low_latency": null,
                    "url_ull": null,
                    "url_dvr": null,
                    "url_audio": null,
                    "url_dvr_audio": null
                },
```

Keep in mind this live is already finished so it's a VOD now. Can't say if it's API return value structure stays the same while live, but it looks like so. 

From the look of it, we probably should also try `subs_trial_media` part if the first one fails, so you can still watch trial. 

Thanks for your time!

**Comment by fireattack** [comment]
Verified it works with VODs, movies on a premium channel with `streamlink 2.4.0+78.g2e6deca`. Will test livestream once I got chance. Thanks.
