### ISSUE TITLE
streamlink api age-restrict error

### ISSUE THREAD

**Issue by TaeDDin** [streamlink/streamlink#4125]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Python tried to check if the broadcast was turned on using Streamlink api, but adult-certified cannot be resolved with api. In the bat file, it becomes adult-certified normally.
This is the python code I used.

    def check_user(self):
        # 0: online, 
        # 1: offline, (unused)
        # 2: not found, 
        # 3: error
        try:
            status = 2
            session = Streamlink()

            session.set_option('http-cookie', "__Secure-3PSID=DQg2y~~~~~~")
            print(session.get_option("http-cookie"))
            s = len(session.streams("https://www.youtube.com/watch?v=FkTGPdtn_2U")) > 0
            
            if s:
                status = 0
                return status

            else:
                status = 1
                return status
        except:
            raise

The YouTube url is any streaming address you searched to verify adult-certified.

This is the bat code I used.

streamlink --http-cookie "__Secure-3PSID=DQg2y~~~~~~" http://www.youtube.com/watch?v=FkTGPdtn_2U best -o "~~~~~~.mp4"

### Debug log

```text
Could not get video info - UNPLAYABLE: Sorry, this content is age-restricted.

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.6
[cli][debug] Streamlink: 2.4.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=http://www.youtube.com/watch?v=FkTGPdtn_2U
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=~~~~~~.mp4
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --http-cookie=[('__Secure-3PSID', 'DQg2y~~~~~~')]
```

**Comment by bastimeyer** [comment]
> 2.4.0

See #4058, which hasn't made it into a new release yet. Use the latest version from the master branch to bypass Youtube's age restriction.

```py
>>> import streamlink
>>> streamlink.__version__
'2.4.0'
>>> streamlink.streams("youtube.com/watch?v=FkTGPdtn_2U").keys()
Could not get video info - LOGIN_REQUIRED: Melde dich an, um dein Alter zu bestätigen
Could not get video info - UNPLAYABLE: Sorry, this content is age-restricted.
```

```py
>>> import streamlink
>>> streamlink.__version__
'2.4.0+62.g501e4a0'
>>> streamlink.streams("youtube.com/watch?v=FkTGPdtn_2U").keys()
odict_keys(['144p', '240p', '360p', '480p', '720p', '1080p', 'worst', 'best'])
```
