### ISSUE TITLE
RTVE.es plugin broken

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#413]
Spanish public TV RTVE recently changed broadcasting address and servers which made plugin broken. 

`livestreamer -p "C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc" "http://www.rtve.es/noticias/mas-24/" best
error: No plugin can handle URL: http://www.rtve.es/noticias/mas-24/`

Below are direct addresses to channels : 

- La 1 : http://www.rtve.es/noticias/directo-la-1/
- La 2 : http://www.rtve.es/television/la-2-directo/
- TDP : http://www.rtve.es/deportes/directo/teledeporte/
- 24H : http://www.rtve.es/noticias/mas-24/

24H is not geoblocked.

**Comment by beardypig** [comment]
Thanks for spotting this :)
