### ISSUE TITLE
ltv_lsm_lv.py: Does a typo makes it non-functioning?

### ISSUE THREAD

**Issue by duunsupen** [streamlink/streamlink#4131]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

This plugin doesn't work for me on an Enigma2 receiver. When I try to open
#SERVICE 4097:0:1:22B8:446:1:C00000:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//ltv.lsm.lv/lv/tiesraide/ltv1:LTV 1
#DESCRIPTION LTV 1
I get an error message in the debug log (see below). I think this might be caused by a simple typo in the .py file. In line 13 it reads:

 r"https?://ltv\.lsm\.lv/lv/tieshraide"

I do think it should rather be 'tiesraide' instead of 'tieshraide' as the actual URLs of the TV stations are: 

[https://ltv.lsm.lv/lv/tiesraide/ltv1](url)
[https://ltv.lsm.lv/lv/tiesraide/ltv7](url)
[https://ltv.lsm.lv/lv/tiesraide/visiemltv](url)

### Debug log

```text
root@sf4008:~# /usr/sbin/streamlinksrv manualstart debug
pidfile /var/run/streamlink.pid does not exist. Daemon not running?
[streamlinksrv][info]  Sun Oct 31 08:22:04 2021 Server (1.8.2) started
[streamlinksrv][debug] Host:           sf4008
[streamlinksrv][debug] Port:           8088
[streamlinksrv][debug] OS:             Linux-4.1.20-1.9-armv7l-with-glibc2.4
[streamlinksrv][debug] Python:         2.7.18
[streamlinksrv][info]  Streamlink:     1.27.8.0.r1_mod / 2021-10-11
[streamlinksrv][debug] youtube-dl:     2021.06.06
[streamlinksrv][debug] Requests(2.26.0), Socks(1.7.1), Websocket(0.59.0)
[streamlinksrv][error] No plugin can handle URL: https://ltv.lsm.lv/lv/tiesraide/ltv1
[streamlinksrv][debug] Send Offline clip
```

**Comment by beardypig** [comment]
Looks like the website has been updated and the plugin needs to be updated to support this change. Even updating the URL matching does not fix it because the layout of the page appears to have changed.

**Comment by beardypig** [comment]
@duunsupen as you are using `streamlinksrv` you will need contact the developer (who I believe is @Billy2011) for them to update the LTV plugin.

**Comment by duunsupen** [comment]
OK. Thanks for your great work!

    Am Mittwoch, 3. November 2021, 12:13:42 MEZ hat beardypig ***@***.***> Folgendes geschrieben:  
 
 


@duunsupen as you are using streamlinksrv you will need contact the developer (who I believe is @Billy2011) for them to update the LTV plugin.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
