### ISSUE TITLE
plugins.picarto: Plugin fails to open VODS but works just fine on popout player links

### ISSUE THREAD

**Issue by dahjin** [streamlink/streamlink#4132]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Running lateast dev build, The picarto plugin does not seem to want to open Vods.
Attempting to open https://picarto.tv/Grimsby/videos/197524 results in [plugins.picarto][error] User is not online.
But opening https://picarto.tv/videopopout/197524 works just fine.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.7
[cli][debug] Streamlink: 2.4.0+63.gbf269e2
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://picarto.tv/Grimsby/videos/197524
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\mpv\mpv.exe"
[cli][debug]  --output=asdd.mkv
[cli][debug]  --rtmp-rtmpdump=rtmpdump.exe
[cli][debug]  --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin picarto for URL https://picarto.tv/Grimsby/videos/197524
[plugins.picarto][debug] Type=Live
[plugins.picarto][error] User is not online
```

**Comment by mkbloke** [comment]
It looks like they must have changed things a little bit.  Previously it wasn't possible to get a canonical URL anywhere except via the popout link for VoDs.  VoDs on profile pages now appear to link via a canonical URL though.

What is happening here is that the current URL logic is identifying the URL as live rather than VoD, so it's going via the method to handle a live stream instead of a VoD.  An update to the URL logic should fix it I think.
