### ISSUE TITLE
Discord Live Stream Recording

### ISSUE THREAD

**Issue by Syrox2** [streamlink/streamlink#4134]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

**Plugin Request**

This is a plugin request and I have read the contribution guidelines and plugin request requirements.
Description. I know this request has been made before, but things have changed.

As we all know by now, Discord is growing rapidly. The community numbers are increasing and so are the Discord servers. Also the user diversity. Not only gaming, also students and classes or universities. 

Discord introduced live streaming direct from the desktop app AND browser a while back. Meanwhile, they also have a Youtube integration, as well as xstream and OBS for streamers. 

**It would be nice to be able to send these streams to a player of your choice OR to record it, especially for the purpose of learning and sharing.** 

Example stream URLs
It is not possible to post a URL for a Discord stream as it is in-app only at this time, which is the whole point of this plugin request.

Additional comments, screenshots, etc.
Please find the link below. 

### Input URLs

https://support.discord.com/hc/de/articles/360040816151-Share-your-screen-with-Go-Live-Screen-Share

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/2768#issuecomment-581006567

Not possible without a **canonical stream URL** that can be used as input. Discord streams are part of a group chat and not suited for Streamlink.
