### ISSUE TITLE
FlexTV / flextv.co.kr

### ISSUE THREAD

**Issue by ChocolateThunder69** [streamlink/streamlink#4135]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

a livestream site similar to Twitch or afreecaTV, mainly for "just chatting" streams. Some streams require a log in due to minor protection laws (drinking, smoking etc.)

### Input URLs

https://www.flextv.co.kr/channels/92957/live
https://www.flextv.co.kr/channels/66401/live

**Comment by trietjack** [comment]
This is an adult site streaming. I don't think you can access it without a verified account which requires a korean ID

**Comment by chorong761** [comment]
> This is an adult site streaming. I don't think you can access it without a verified account which requires a korean ID

As long as the stream isn't listed as 19+, you don't need an account to access. The site also has SFW content which isn't purely an adult site

**Comment by afterdelight** [comment]
@[d222gfxx](https://github.com/d222gfxx) can you share your updated plugin? I get error with your plugin and i cant type on your issue since it limited to collaborators only.

**Comment by challi1337** [comment]
@[d222gfxx](https://github.com/d222gfxx) I'd also be interested in an updated version of your plugin since for some reason the streamlink devs don't wanna support the website themselves. Currently your plugin only puts out the same stream no matter which link you input.
