### ISSUE TITLE
Spanish Music Website HQM.es (18 live music channels)

### ISSUE THREAD

**Issue by duunsupen** [streamlink/streamlink#4158]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

https://hqm.es/ is a Spanish website offering 18 live music TV channels with a broad range of music styles (Hip Hop, Classic, Jazz, Latin, Pop, Blues, Dance...). Channels are streamed in excellent 1080p quality and are free to watch. A log in is not required. 
The stream's URLs do not seem to change (Example for the Hip Hop channel: https://hqm.es/canales/hip-hop-hqm-directo/), whereas this seems very likely to be the case for the .m3u8 address (Hip Hop channel: https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/index-f5-v1-a1.m3u8)
A plugin for this website would be a great addition to Streamlink.

### Input URLs

https://hqm.es/canales/hip-hop-hqm-directo/
https://hqm.es/canales/jazz-hqm-directo/
https://hqm.es/canales/pop-hqm-directo/
https://hqm.es/canales/classic-hqm-directo/
https://hqm.es/canales/blues-hqm-directo/
...

**Comment by mkbloke** [comment]
```
$ streamlink --http-header 'Origin=https://yowi.tv' --http-header 'Referer=https://yowi.tv/' https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8
[cli][info] Found matching plugin hls for URL https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8
Available streams: 160p (worst), 360p, 480p, 720p, 1080p (best)

$ streamlink --http-header 'Origin=https://yowi.tv' --http-header 'Referer=https://yowi.tv/' https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8 360p
[cli][info] Found matching plugin hls for URL https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8
[cli][info] Available streams: 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 360p (hls)
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[cli][error] Try 1/1: Could not open stream <HLSStream('https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/index-f2-v1-a1.m3u8', 'https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8')> (No data returned from stream)
error: Could not open stream <HLSStream('https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/index-f2-v1-a1.m3u8', 'https://livelist01.yowi.tv/lista/8327abc87895df4c76db1155435fdca6a3607bbd/master.m3u8')>, tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by mkbloke** [comment]
I think this may as well be closed.  As far as I can see, only HLS with SAMPLE-AES encryption is available, which isn't supported by Streamlink.
