### ISSUE TITLE
Plugin keep init if running too many sessions in the same time

### ISSUE THREAD

**Issue by d222gfxx** [streamlink/streamlink#4161]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Plugin:
```py
# encoding: utf-8
import re
from streamlink.plugin import Plugin, PluginArgument, PluginArguments, pluginmatcher

@pluginmatcher(re.compile(
    r'(http)?(s)?(://)?(www\.)?test.com/(?P<channel>[^/]+)'
))
class Test(Plugin):
    def __init__(self, url: str) -> None:
        self.url = url
        
        try:
            self.load_cookies()
        except RuntimeError:
            pass  # unbound cannot load

        self.lock = self.session.get_option("lock")
        with self.lock:
            print("__init__", self.url)
            
    def _get_streams(self):
        with self.lock:
            print("_get_streams", self.url)

__plugin__ = Test
```

reproduced code:
```
import streamlink
import time
import threading

lock = threading.Lock()

def GetStream(url):
    session = streamlink.Streamlink()
    session.set_option('lock', lock)
    session.options.set('lock', lock)
    while True:
        streams = session.streams(url)
        time.sleep(10)

count = 200
threading_pool = []
for i in range(count):
    thread = threading.Thread(target = GetStream, args = ('test.com/{}'.format(i) , ))
    threading_pool.append(thread)

for thread in threading_pool:
    thread.start()
    
for thread in threading_pool:
    thread.join()
```

I just found out it's because of "@lru_cache(maxsize=128)" in session.py
After I change it to 1024, everything is fine.
Anyway, there should be a warning, queue is full or what
I just upgrade Streamlink then realize some feature is broken, LOL

### Debug log

```text
```

**Comment by bastimeyer** [comment]
Related: #4091
The url resolver should return plugin classes and not plugin instances. That would fix this issue, too.

**Comment by bastimeyer** [comment]
I've removed the debug log, because it's causing massive lag with all the parsed links. Might be caused by the refined-github browser extension, but I don't care. The log's not important.
