### ISSUE TITLE
Environment variables for defining alternative dependencies in setup.py

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4170]
As mentioned in #4113, I'd prefer having dependencies defined declaratively via setup.cfg instead of defining a list and adding it to `setup(install_requires=...)` in setup.py. Optional dependencies can be added via the `extra_requires`, but this unfortunately can't be used for defining two different sets of dependencies (exclusive-or).

https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#declaring-required-dependency
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

----

**Let's take a look at the env vars in setup.py for choosing alternative dependencies:**

## STREAMLINK_USE_PYCRYPTO

The `STREAMLINK_USE_PYCRYPTO` env var and the `pycrypto` dependency was added in #713 by @mmetak due to `pycryptodome` not being in the repos of some Linux distros at that time (Arch and Fedora), but that isn't the case anymore. Everyone's switched to `pycryptodome` or `pycryptodomex` by applying patches.

This means we should remove the env var.

- **Arch Linux** (community) - 2018-08-27
  https://github.com/archlinux/svntogit-community/commit/4fa0fa3f789fbae45f8b3ecd2fee6f9450e327c6
- **Arch Linux** (AUR) - 2020-04-29
  https://aur.archlinux.org/cgit/aur.git/commit/?h=streamlink-git&id=92b1679a6616b2d89c60ba8a0e25c3b050439c17
- **Fedora** - 2019-08-20
  https://src.fedoraproject.org/rpms/python-streamlink/c/49187b8b7ce5e6836225d332a31bec5e5a30c20c?branch=rawhide
  https://src.fedoraproject.org/rpms/python-streamlink/tree/rawhide
- **Void** - 2018-06-06
  https://github.com/void-linux/void-packages/commit/0a9396a547609eeeb0972c571203beb9f23d3d80
- **Debian** / **Ubuntu** - 2019-08-23 (as always a pain to research, thanks :+1:)
  https://launchpadlibrarian.net/452638112/streamlink_1.2.0+dfsg-1~webupd8~disco2_1.3.0+dfsg-1~webupd8~disco.diff.gz
- **Gentoo** - 2017-03-05
  https://gitweb.gentoo.org/repo/gentoo.git/commit/net-misc/streamlink/streamlink-9999.ebuild?id=d377f979b7ff6cbb1185dc02b18b4770eff56a3f

## STREAMLINK_USE_PYCOUNTRY

If we remove the `STREAMLINK_USE_PYCRYPTO` env var, then `STREAMLINK_USE_PYCOUNTRY` will be the only one left for choosing alternative dependencies.

Most packages define pycountry as a dependency, but some don't. However, I think those which don't only do this because we're not using it as the default. nixos for example doesn't use it but has pycountry in its repos.

`STREAMLINK_USE_PYCOUNTRY` was added in #585 by @beardypig because of test failures on some Linux distros when using the default `iso-639` and `iso3166`.

`iso-639` however hasn't been updated anymore since April 2016, more than 5 years ago
- https://pypi.org/project/iso-639/#history
- https://pypi.org/project/iso3166/#history

`pycountry` was updated last in 2020
- https://pypi.org/project/pycountry/#history

We could default to `pycountry` and drop `iso-639`+`iso3166` if we want to remove alternative dependencies and the env var.
I think `pycountry` was made optional instead of switching dependencies back then because it's not as lightweight as `iso-639`, is that right, @beardypig ?

**Comment by beardypig** [comment]
That's right. As iso-639 appears to be unmaintained we should drop it. It would tidy up the codebase as well :)

**Comment by bastimeyer** [comment]
The pycrypto removal is trivial, so I've opened a PR for this here: #4174 

@beardypig if you want, please go ahead and do the same for pycountry after the pycrypto changes have been merged. Most packages are using pycountry and we should not depend on packages which are unmaintained.
