### ISSUE TITLE
StageIt

### ISSUE THREAD

**Issue by BlazinWings** [streamlink/streamlink#4173]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

What is the site about? It focuses on streaming live concerts from artists to fans. Fans create accounts, buy tickets, and can watch the shows exclusively as they air live. There are no archives.
Who is it run by? StageIt corporation out of California.
What content does it provide? Live streamed concerts.

### Input URLs

1. https://www.stageit.com/andy_timmons/at_plays_the_blues/102620
2. https://www.stageit.com/pianist_daniel_roberts/final_james_bond_special_of_2021_songs_and_music_from_the_series/102052
3. https://www.stageit.com/johncarey/john_carey_band_live_in_palm_springs_ca/102530

**Comment by back-to** [comment]
too difficult to maintain
