### ISSUE TITLE
Kodi module

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#419]
Is there a Kodi module like the one for livestreamer?:

http://mirrors.mit.edu/kodi/addons/jarvis/script.module.livestreamer/

https://github.com/blxd/plugin.video.livestreamer

**Comment by beardypig** [comment]
I made one just the other day: https://github.com/beardypig/plugin.video.streamlink

**Comment by unlocKing** [comment]
Cheers dude!
