### ISSUE TITLE
plugins.ard_mediathek: The ARD plugin is not loading anymore.

### ISSUE THREAD

**Issue by tmatthews5511** [streamlink/streamlink#4191]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

It seems that the ARD (German public broadcaster) has made some changes to their site. On their site, their stream is working much better. 

However, when trying to use Streamlink, the ARD stream will not open. 

[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/
error: No playable streams found on this URL: https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/

streamlink --version
streamlink 3.0.1+1.g33ccd2e

### Debug log

```text
[cli][debug] OS:         Linux-5.4.0-90-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 3.0.1+1.g33ccd2e
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/
[cli][debug]  stream=['540p']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/
error: No playable streams found on this URL: https://www.ardmediathek.de/daserste/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL0xpdmVzdHJlYW0tRGFzRXJzdGU/
```

**Comment by mkbloke** [comment]
Does the existing plugin work for VoD content?

I have a fix for the live channels within `https://www.ardmediathek.de/live/`, but it would be easier to get some info from you on what is still working (if anything), so I can look at those URLs and decide if the existing `media_id` code should be kept.

Thanks.

**Comment by tmatthews5511** [comment]
It's the exact same error for VoD:

[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/video/wataha-einsatz-an-der-grenze-europas/folge-1-anschlag-s01-e01/mdr/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy9hOWQxNTg1Yy1iMzQyLTQ3NGYtYTM2NS0wZWY2M2JjZjNhMDY/
error: No playable streams found on this URL: https://www.ardmediathek.de/video/wataha-einsatz-an-der-grenze-europas/folge-1-anschlag-s01-e01/mdr/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy9hOWQxNTg1Yy1iMzQyLTQ3NGYtYTM2NS0wZWY2M2JjZjNhMDY/

[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/video/white-sands-strand-der-geheimnisse/folge-1-warmer-empfang-s01-e01/ndr/Y3JpZDovL25kci5kZS80MmEwZmQwMC03YTYwLTQ4N2EtYWZhZC1lZDBmYjYzZjgzMDQ/
error: No playable streams found on this URL: https://www.ardmediathek.de/video/white-sands-strand-der-geheimnisse/folge-1-warmer-empfang-s01-e01/ndr/Y3JpZDovL25kci5kZS80MmEwZmQwMC03YTYwLTQ4N2EtYWZhZC1lZDBmYjYzZjgzMDQ/

Live:

[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ/
error: No playable streams found on this URL: https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ/

It works fine in the browser. The ZDF plugin is working fine.

**Comment by bastimeyer** [comment]
I've submitted a pull request here: #4200
If you want to test it, please go ahead.
