### ISSUE TITLE
Can't update from 0.1.0 to 0.2.0 using pip.

### ISSUE THREAD

**Issue by Junior1544** [streamlink/streamlink#420]
Good day!

I love Streamlink!  Thank you for everyone who maintains and works on it!

I have streamlink 0.1.0 installed on my raspberry pi.  I installed it using pip.

I am now trying to update it to the latest version, but when I run the pip update command:
`pip install -U streamlink`
it gives me the following error screen:

![image](https://cloud.githubusercontent.com/assets/20785288/21952149/fe727134-d9b8-11e6-9f0e-d7f4853bda80.png)

Any thoughts on how to fix this?  do I need to remove streamlink and reinstall it or is there another way?  If i need to remove it and reinstall it, how do I do that?

Thank you!
--James

**Comment by gravyboat** [comment]
Can you try `pip install --upgrade streamlink`? I updated using that method on my Linux machine without issue.

**Comment by Junior1544** [comment]
Thanks for the suggestions.

When I tried pip 'install --upgrade streamlink' this is what I got:
![image](https://cloud.githubusercontent.com/assets/20785288/21953590/bdb69fe0-d9df-11e6-8e9a-771e1c69d00c.png)

when I tried 'pip install --upgrade pip' this is what I got:
![image](https://cloud.githubusercontent.com/assets/20785288/21953596/eec9bd9c-d9df-11e6-87c2-fc4e38cee37d.png)

I know it has network access because I can ssh into it from my laptop and from the raspberry pi i can load web pages, that's as far as I can check with my knowledge for linux...

Any further thoughts?
--James

**Comment by Junior1544** [comment]
if I run pip with no command lines it looks like I get the same error again?  is my pip corupted maybe?

**Comment by Junior1544** [comment]
ok, i removed the pip software that I had gotten from apt-get and installed it from the website and it's now using pip version 9 and it's still giving me an error when I try to use it to upgrade streamlink, but it's a different error now and here it is:

![image](https://cloud.githubusercontent.com/assets/20785288/21953840/cf64a380-d9e5-11e6-8f8f-39ef46a9f460.png)

**Comment by back-to** [comment]
Hi,
you need to install it as an _admin(root)_

Try it with
```sh
sudo pip install -U streamlink
```

**Comment by chhe** [comment]
It's better to use ``sudo``'s ``-H`` parameter or you will run into permission issues with ``pip``'s cache:

```
sudo -H pip install -U streamlink
```

**Comment by Junior1544** [comment]
Yay!

'sudo -H pip install -U streamlink' 

worked!  I would suggest putting the information into the documentation that using apt-get to get pip working wont work with a raspberry pi and it needs to be installed another way.  and then you can update streamlink using the updated pip using the 'sudo -H pip install -U streamlink' 

I would do a pull request myself about this but I have no idea how :)

Thank you guys!

**Comment by skulblakka** [comment]
I think the original issue is caused by an outdated version of pip (the one in the repos the pi uses is from 2014). [See](http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread/27341847#27341847)
