### ISSUE TITLE
VLC player (twitch stream) crashes when Dota 2 is started/switched to in exclusive fullscreen

### ISSUE THREAD

**Issue by bot144** [streamlink/streamlink#421]
Only happens when the resolution is lower in Dota than in desktop (1080p vs 1440p). I don't know how long this issue has existed, since I started using Dota 2 in exclusive fullscreen only recently.

**Comment by garoto** [comment]
isn't this a VLC issue then?

**Comment by bot144** [comment]
@gapato Yes actually you're right, I tested it with normal VLC playback, it still crashes. Will close the thread.

**Comment by stevek123** [comment]
See: https://trac.videolan.org/vlc/ticket/15711 or try https://trac.videolan.org/vlc/ticket/11542
