### ISSUE TITLE
plugins.svtplay: Stream selection

### ISSUE THREAD

**Issue by zappepappe** [streamlink/streamlink#4217]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

SVTPlay live streams usually have 2 different 720p streams.
One of them is a h264 main profile ~2500kbit/s.
The other one is a h264 high profile ~4000kbit/s.

If I start a stream with the "best" stream selector it picks the low bitrate main profile stream. If I want the higher bitrate high profile stream I have to manually select the "720p_alt" stream.

### Debug log

```text
streamlink.exe --loglevel debug https://www.svtplay.se/video/33017618/vinterstudion/vinterstudion-28-nov-10-45 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.8
[cli][debug] Streamlink: 3.0.2
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.svtplay.se/video/33017618/vinterstudion/vinterstudion-28-nov-10-45
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\Program Files\MPC-HC\mpc-hc64.exe"
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin svtplay for URL https://www.svtplay.se/video/33017618/vinterstudion/vinterstudion-28-nov-10-45
[plugins.svtplay][debug] Path=/
[plugins.svtplay][debug] VOD ID=KqyyXXg
[utils.l10n][debug] Language code: sv_SE
[stream.dash][debug] Available languages for DASH audio streams: sv, sv-x-tal (using: sv)
[cli][info] Available streams: 234p (worst), 360p, 540p, 720p_alt, 720p (best)
[cli][info] Opening stream: 720p (dash)
[stream.dash][debug] Opening DASH reader for: 3 (video/mp4)
[stream.dash][debug] Opening DASH reader for: 5 (audio/mp4)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=0)
[stream.dash_manifest][debug] Generating segment numbers for dynamic playlist (id=1)
[utils.named_pipe][info] Creating pipe streamlinkpipe-8368-1-1664
[utils.named_pipe][info] Creating pipe streamlinkpipe-8368-2-9097
[stream.ffmpegmux][debug] ffmpeg command: C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\streamlinkpipe-8368-1-1664 -i \\.\pipe\streamlinkpipe-8368-2-9097 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\streamlinkpipe-8368-1-1664
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\streamlinkpipe-8368-2-9097
[cli][debug] Pre-buffering 8192 bytes
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-init.mp4 complete
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-init.mp4 complete
[stream.dash][debug] Waiting for segment: a0-3937.mp4 (2.9s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3936.mp4 complete
[stream.dash][debug] Waiting for segment: v3-3937.mp4 (2.8s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-3936.mp4 complete
[cli][info] Starting player: "C:\Program Files\MPC-HC\mpc-hc64.exe"
[cli.output][debug] Opening subprocess: "C:\Program Files\MPC-HC\mpc-hc64.exe" -
[cli][debug] Writing stream to output
[stream.dash][debug] Waiting for segment: a0-3938.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3937.mp4 complete
[stream.dash][debug] Waiting for segment: v3-3938.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-3937.mp4 complete
[stream.dash][debug] Waiting for segment: a0-3939.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3938.mp4 complete
[stream.dash][debug] Waiting for segment: v3-3939.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-3938.mp4 complete
[stream.dash][debug] Waiting for segment: a0-3940.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3939.mp4 complete
[stream.dash][debug] Waiting for segment: v3-3940.mp4 (3.0s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-3939.mp4 complete
[stream.dash][debug] Waiting for segment: a0-3941.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3940.mp4 complete
[stream.dash][debug] Waiting for segment: v3-3941.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-v3/v3-3940.mp4 complete
[cli][info] Player closed
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: \\.\pipe\streamlinkpipe-8368-1-1664
[stream.dash][debug] Waiting for segment: a0-3942.mp4 (3.1s)
[stream.dash][debug] Download of segment: https://svt-event-19-c.akamaized.net/se/1400840-053W/14c98a5b-0ebc-4c18-8300-6b88f0b3cc01/dash-a0/a0-3941.mp4 complete
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Pipe copy complete: \\.\pipe\streamlinkpipe-8368-2-9097
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
This is how the plugin returns streams:
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/plugins/svtplay.py#L65-L67
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/plugins/svtplay.py#L99-L105

If multiple streams get returned with the same name, then `_alt` streams will be added to the output instead, which means if there are dfferent stream qualities with the same name, then these streams either need to be renamed or returned in a different order.

**Comment by mkbloke** [comment]
The plugin only returns the one DASH manifest URL for this VoD, which is: https://svt-vod-3j.akamaized.net/d0/se/20211128/d03aafad-24cc-4fef-b3f8-5bffe8d6d6b7/dash-avc.mpd

That returns the following MPD:
```
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" mediaPresentationDuration="PT4H38M46.400390625S" minBufferTime="PT2S">
  <Period id="0">
    <AdaptationSet id="0" contentType="video" frameRate="90000/1800" scanType="progressive" par="16:9" maxWidth="1280" maxHeight="720">
      <Representation id="0" bandwidth="4316313" width="1280" height="720" codecs="avc1.640020" sar="1:1" mimeType="video/mp4">
        <SegmentTemplate initialization="cmaf-video-avc-1280x720p50-3523/cmaf-video-avc-1280x720p50-3523-init.mp4" media="cmaf-video-avc-1280x720p50-3523/cmaf-video-avc-1280x720p50-3523-$Number$.mp4" startNumber="1" timescale="90000">
          <SegmentTimeline>
            <S t="0" d="576000" r="75"/>
            <S t="43776000" d="864000"/>
            <S t="44640000" d="288000"/>
            <S t="44928000" d="576000" r="2534"/>
            <S t="1505088000" d="288000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="1" bandwidth="2814785" width="1280" height="720" codecs="avc1.4d4020" sar="1:1" mimeType="video/mp4">
        <SegmentTemplate initialization="cmaf-video-avc-1280x720p50-2221/cmaf-video-avc-1280x720p50-2221-init.mp4" media="cmaf-video-avc-1280x720p50-2221/cmaf-video-avc-1280x720p50-2221-$Number$.mp4" startNumber="1" timescale="90000">
          <SegmentTimeline>
            <S t="0" d="576000" r="2612"/>
            <S t="1505088000" d="288000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="2" bandwidth="1606428" width="960" height="540" codecs="avc1.4d401f" sar="1:1" mimeType="video/mp4">
        <SegmentTemplate initialization="cmaf-video-avc-960x540p50-1255/cmaf-video-avc-960x540p50-1255-init.mp4" media="cmaf-video-avc-960x540p50-1255/cmaf-video-avc-960x540p50-1255-$Number$.mp4" startNumber="1" timescale="90000">
          <SegmentTimeline>
            <S t="0" d="576000" r="2612"/>
            <S t="1505088000" d="288000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="3" bandwidth="998039" width="640" height="360" codecs="avc1.4d401f" sar="1:1" mimeType="video/mp4">
        <SegmentTemplate initialization="cmaf-video-avc-640x360p50-797/cmaf-video-avc-640x360p50-797-init.mp4" media="cmaf-video-avc-640x360p50-797/cmaf-video-avc-640x360p50-797-$Number$.mp4" startNumber="1" timescale="90000">
          <SegmentTimeline>
            <S t="0" d="576000" r="2612"/>
            <S t="1505088000" d="288000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="4" bandwidth="472739" width="416" height="234" codecs="avc1.42c015" sar="1:1" mimeType="video/mp4">
        <SegmentTemplate initialization="cmaf-video-avc-416x234p50-322/cmaf-video-avc-416x234p50-322-init.mp4" media="cmaf-video-avc-416x234p50-322/cmaf-video-avc-416x234p50-322-$Number$.mp4" startNumber="1" timescale="90000">
          <SegmentTimeline>
            <S t="0" d="576000" r="2612"/>
            <S t="1505088000" d="288000"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="audio" segmentAlignment="true" lang="sv">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <Label>Svenska</Label>
      <Representation id="5" bandwidth="127840" codecs="mp4a.40.2" audioSamplingRate="48000" mimeType="audio/mp4">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate initialization="cmaf-audio-aac-2ch-125/cmaf-audio-aac-2ch-125-init.mp4" media="cmaf-audio-aac-2ch-125/cmaf-audio-aac-2ch-125-$Number$.mp4" startNumber="1" timescale="48000">
          <SegmentTimeline>
            <S t="0" d="307200" r="2612"/>
            <S t="802713600" d="153600"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

So, it seems to be the case that the DASH streams are not sorted by highest bandwidth first, I think?

**Comment by bastimeyer** [comment]
> So, it seems to be the case that the DASH streams are not sorted by highest bandwidth first, I think?

The problem is how `DASHStream.parse_manifest()` returns the streams dict:
https://github.com/streamlink/streamlink/blob/0b394c22bf23c9ff05dfd8d96279aa00ced23eaf/src/streamlink/stream/dash.py#L233-L259

It renames duplicate streams here which is supposed to be done in the stream ranking logic of `Plugin.streams()` where it can take the stream weights into account:
https://github.com/streamlink/streamlink/blob/0b394c22bf23c9ff05dfd8d96279aa00ced23eaf/src/streamlink/plugin/plugin.py#L299-L429

The whole streams return logic in `Plugin` and the implementions of the various stream types is far from ideal. Ideally, it should not return dictionaries with predetermined key names (or build a dict from yielded stream names and stream instances).

What should be done is that all plugins / stream implementations should return lists / iterators of stream instances which instead store the stream name and their metadata. Then the ranking could be done on this list of streams instead, so duplicates could be figured out better with a more sophisticated ranking logic that doesn't interfere with stream names.

I've also never been a fan of how the streams are presented on the CLI. The current way is very inconsistent, non-deterministic in some cases and stream names don't include the necessary information. But that's mostly because of the stream selection names, which are supposed to be simple.

A rewrite of this would require fixing every plugin and the stream implementations, and this is why this hasn't been done yet.

----

To fix this plugin issue however, a simple rename of the stream names should be enough instead of returning the entire dict / yielding its key/value tuples.

**Comment by mkbloke** [comment]
A quick test - from the beginning of that VoD while looking at the stats (key `I` in mpv) while playing, seems to show higher running bitrates for `720p` than `720p_alt` for me.

**Comment by mkbloke** [comment]
> To fix this plugin issue however, a simple rename of the stream names should be enough instead of returning the entire dict / yielding its key/value tuples.

I'm not quite following what you mean here.

**Comment by zappepappe** [comment]
> A quick test - from the beginning of that VoD while looking at the stats (key `I` in mpv) while playing, seems to show higher running bitrates for `720p` than `720p_alt` for me.

Not saying you're wrong, but I consistently get the better stream on _alt.
Don't know how the info in mpv looks, but it's probably easier to look for the high vs main profile of the codec than a fluctuating bitrate.

**Comment by bastimeyer** [comment]
> I'm not quite following what you mean here.

@mkbloke, instead of `yield from DASHStream.parse_manifest(...).items()`, the plugin could reorder + rename the streams manually. If it's indeed an issue, which I can't say as it's geo-restricted and I don't feel like setting up a proxy/vpn for this.

Or if one wants to improve `DASHStream.parse_manifest` they could add a `name_key` argument similar to `HLSStream.parse_variant_playlist`.

> A quick test - from the beginning of that VoD while looking at the stats (key I in mpv) while playing, seems to show higher running bitrates for 720p than 720p_alt for me.

The codec information of the DASH manifest example from above suggests the same, but this doesn't mean that it's the case for every manifest returned by the site.

1. 720p
   > `<Representation id="0" bandwidth="4316313" width="1280" height="720" codecs="avc1.640020" sar="1:1" mimeType="video/mp4">`

   bandwidth = 4316313
   avc1.640020 = High Level 3.2

2. 720p_alt
   > `<Representation id="1" bandwidth="2814785" width="1280" height="720" codecs="avc1.4d4020" sar="1:1" mimeType="video/mp4">`

   bandwidth = 2814785
   avc1.4d4020 = Constrained Main Level 3.2

**Comment by zappepappe** [comment]
If it would help you fix this issue I could set up a Wireguard VPN or a FreeBSD jail for you to use for diagnostics.
There should however be a lot of content on SVTPlay that isn't geo-blocked.

**Comment by zappepappe** [comment]
After some more testing it seems to only be an issue with live content.
On VODs `720p` is the best stream and `720p_alt` is the low bitrate one. If there is a `1080p` stream that is naturally the best stream and no `720p_alt` stream will exist.
While on live channels and events `720p_alt` is the best stream and `720p` is the low bitrate one.

**Comment by mkbloke** [comment]
@bastimeyer, ah yes, thanks.  I see now that it would have been possible to sort on `s.video_representation.bandwidth` here if not fixed in `DASHStream.parse_manifest()`.

Still, thanks to back-to, it is fixed there and that seems the better solution, as most people will probably expect the sorting that is now implemented.
