### ISSUE TITLE
Plugin Request: Support for VUit

### ISSUE THREAD

**Issue by thatsysadmin** [streamlink/streamlink#4218]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

VUit (https://www.vuit.com) seems to be a fairly new streaming service run by Syncbak, Inc. They mostly provide news content around, but not limited to US stations. There isn't any paywalls or provider logins to my knowledge.

Some cursory digging in developer tools in one of the links seems to indicate they are using a service called Flowplayer (https://flowplayer.com/features/live-streaming). There doesn't seem to be any DRM in use. (At least not Google Widevine.) If there is an existing plugin for a streaming service that uses Flowplayer as a backend, this could be a relatively simple plugin to make by basing off that. Some things of interest that may help with making the plugin are that there is a link to what seems to be an HTTPS URL with a UUID to where the content is being streamed. (See highlighted line in attached photo.) 

![image](https://user-images.githubusercontent.com/65380846/143783576-b96e37d8-5c17-42d3-9a16-fad83659372d.png)

Please note that this screen shot was taken from one of the actual streaming pages.

If you need more information from me than this, just ask and I'll keep an eye out. Thanks!

### Input URLs

1. https://www.vuit.com/publishers/230/ktsf#channel:17500
2. https://www.vuit.com/publishers/318#channel:17431
3. https://www.vuit.com/publishers/380#channel:19091

**Comment by gravyboat** [comment]
This site violates [category 3 of the plugin request guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests). Closing and locking. We won't work on this. If you want to create your own plugin and side load you're welcome to do so.
