### ISSUE TITLE
crunchyroll download options

### ISSUE THREAD

**Issue by TuXEKRO** [streamlink/streamlink#422]
Hello everyone! I'm trying to download the videos with subtitles in my language (Spanish). But I do not know how to tell the program to change the language.

I hope your answers, greetings !!

**Comment by beardypig** [comment]
In the docs it explains how to change the locale https://streamlink.github.io/cli.html#cmdoption-crunchyroll-locale. This should give you the correct subtitle language. Probably you need to use `--crunchyroll locale es_ES` to get Spanish subtitles.

**Comment by TuXEKRO** [comment]
First thing, thanks for the speed @beardypig

The second, thank you very much for attaching the direct link to the section, is that I do not work the page searcher in my browser, and also for transcribirlo ^^

Fixed, how do you close the ticket?

PD: en `--crunchyroll-locale es_ES` no `--crunchyroll locale es_ES`

**Comment by TuXEKRO** [comment]
Ah, one more thing. Well two.

1. Can you download a complete directory?
Example:
Http://www.crunchyroll.com/eldlive

2. Can you rename files automatically?

Right now I am using this code:

`streamlink --crunchyroll-username=USERNAME --crunchyroll-password=PASSWORD --crunchyroll-locale es_ES -o NAME.ts LINK-VIDEO best`

**Comment by beardypig** [comment]
No, streamlink does not offer a way to download the full series or automatically name the files. Streamlink is aimed at streaming rather than downloading.

**Comment by TuXEKRO** [comment]
Ah good. I did not know, jej While it works, I'll stay jej

Thank you @beardypig !!
