### ISSUE TITLE
Ubuntu version no functionality anymore

### ISSUE THREAD

**Issue by freedom4JA** [streamlink/streamlink#4223]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

The Ubuntuversion is on 2.3.0-1 and don’t works anymore on my Linux Mint. Is there a stable version to get without first need to downloading thirdparty things like pip? thanks in advance

**Comment by bastimeyer** [comment]
https://streamlink.github.io/install.html#linux-and-bsd

> Please see the PyPI package and source code or AppImages sections down below if a package is not available for your distro or platform, or if it's out of date.

https://streamlink.github.io/install.html#appimages

> What are AppImages?
> AppImages are portable apps for Linux which are independent of the distro and package management.

> Download & Setup
> First, download the latest Streamlink AppImage which matches your system's architecture from the Streamlink AppImage releases page. Then simply set the executable flag and run the app.
> ```
> # Set the executable flag. Note that all AppImage release file names include
> # the release version, Python version, platform name and CPU architecture
> chmod +x streamlink-2.0.0-1-cp39-cp39-manylinux2014_x86_64.AppImage
> 
> # Run the Streamlink AppImage with any parameter supported by Streamlink
> ./streamlink-2.0.0-1-cp39-cp39-manylinux2014_x86_64.AppImage --version
> ```

https://github.com/streamlink/streamlink-appimage/releases
