### ISSUE TITLE
Improve Plugin: Albavisión - add Antena 7 (DO)

### ISSUE THREAD

**Issue by mpiffa** [streamlink/streamlink#4224]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

We would like to add a new channel to the Albavisión plugin (https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/albavision.py): 

- Antena 7: https://www.antena7.com.do/envivo-canal-7/

### Input URLs

https://www.antena7.com.do/envivo-canal-7/

**Comment by mkbloke** [comment]
See: https://github.com/streamlink/streamlink/issues/4228#issuecomment-992995687
