### ISSUE TITLE
htv.com.vn / htv-livecdn.fptplay.net/htvonline

### ISSUE THREAD

**Issue by nuriarh** [streamlink/streamlink#4225]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi!
I'd like to add the following plugin:
https://htv-livecdn.fptplay.net/htvonline
in order to get the following channel:
- **HTV7**: http://www.htv.com.vn/truc-tuyen

### Input URLs

http://www.htv.com.vn/truc-tuyen

**Comment by Trung0246** [comment]
Looks like we can use regex to target `iosUrl` and `iosUrl_mb` javascript variable that stores m3u8 urls. Upon using SoftEther VPN with public VPN Gate lists it kinda worked (for `iosUrl_mb` only, no idea why I got `ERR_HTTP2_PROTOCOL_ERROR`).
![image](https://user-images.githubusercontent.com/11626920/147865077-f4889387-ae32-4f25-b267-3bf5aebea70a.png)

**Comment by mkbloke** [comment]
What's the deal with adding TV channels now?  Since  #4344 was merged I'm a bit confused as to what the current situation is.  Can somebody say yes or no for this, please?

**Comment by mkbloke** [comment]
The annoying thing about this site is that there are apparently no canonical URLs for each of the 4 channels.  This means a plugin given the URL: `https://www.htv.com.vn/truc-tuyen` will only play the channel that the page starts with by default (currently HTV7).  The only way around this would be to add a plugin command line option to select the other channels.  I don't know if the Streamlink maintainers would approve of that solution though.
