### ISSUE TITLE
Windows Installer doesn't add PATH properly?

### ISSUE THREAD

**Issue by HowDoInternet** [streamlink/streamlink#423]
After installing version 0.2 I tried to start streamlink via a .bat file like this:
`set /p streamname=Stream name:%=%`
`streamlink http://www.twitch.tv/%streamname% best --player-no-close `
but cmd then says it doesn't know the command streamlink.
If I start cmd manually and start a random stream like this:
`streamlink twitch.tv/lirik best`
it works.
If I look at path in the manually started cmd then the entry pointing to the streamlink bin folder is there.
If I add path to the .bat file like this:
`set /p streamname=Stream name:%=%`
`streamlink http://www.twitch.tv/%streamname% best --player-no-close `
`path`
`pause`
then the path to the streamlink bin is missing.
I fixed this by adding `set PATH= path_to_streamlink_bin` as the first line in the .bat but it should work without me adding that.

This issues didn't exist with livestreamer.

EDIT: I am running Win 8.1

**Comment by xkbd** [comment]
How you run bat-file? From cmd.exe/double-clicking/etc?

**Comment by HowDoInternet** [comment]
I just double-click the .bat file.

**Comment by xkbd** [comment]
logoff -> logon & try again

**Comment by HowDoInternet** [comment]
Yeah that fixed it. Could have gotten that idea myself...
