### ISSUE TITLE
TypeError: Object of type TwitchHLSStream is not JSON serializable

### ISSUE THREAD

**Issue by zakdances** [streamlink/streamlink#4237]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Just trying to send `TwitchHLSStream` over json, but it's not serializing. Is `TwitchHLSStream` suppose to be calling the `__json__` function of it's superclass `HLSStream`? Because I can submit a PR for this if it is.

version: `streamlink==3.0.3`

### Debug log

```text
streamlink==3.0.3

[streamlink-getter-container][2021-12-07 22:40:12,153] error in app: Exception on / [GET]
[streamlink-getter-container]Traceback (most recent call last):
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
[streamlink-getter-container]    response = self.full_dispatch_request()
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
[streamlink-getter-container]    return self.finalize_request(rv)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1538, in finalize_request
[streamlink-getter-container]    response = self.make_response(rv)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1716, in make_response
[streamlink-getter-container]    rv = jsonify(rv)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 355, in jsonify
[streamlink-getter-container]    f"{dumps(data, indent=indent, separators=separators)}\n",
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 133, in dumps
[streamlink-getter-container]    rv = _json.dumps(obj, **kwargs)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
[streamlink-getter-container]    return cls(
[streamlink-getter-container]  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
[streamlink-getter-container]    chunks = self.iterencode(o, _one_shot=True)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
[streamlink-getter-container]    return _iterencode(o, 0)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/site-packages/flask/json/__init__.py", line 57, in default
[streamlink-getter-container]    return super().default(o)
[streamlink-getter-container]  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
[streamlink-getter-container]    raise TypeError(f'Object of type {o.__class__.__name__} '
[streamlink-getter-container]TypeError: Object of type TwitchHLSStream is not JSON serializable
```

**Comment by bastimeyer** [comment]
`Stream` and all its subclasses implement the `json` computed property which calls the `__json__` method for building the resulting JSON object. The output of the `json` property gets serialized via `json.dumps`. Just read `stream.json` on any kind of stream object if you want a serialized string of some of its data.

If you don't want to do that and instead want to pass the stream object to `json.dumps`, then you will have to implement your own JSON encoder which can handle the `Stream` class instances.
https://docs.python.org/3/library/json.html#json.JSONEncoder

- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/stream/stream.py#L34-L37
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/stream/http.py#L44-L54
- https://github.com/streamlink/streamlink/blob/3.0.3/src/streamlink/stream/hls.py#L453-L463
- https://github.com/streamlink/streamlink/blob/3.0.3/tests/test_stream_json.py
