### ISSUE TITLE
Tikilive / tikilive

### ISSUE THREAD

**Issue by UzunMuhalefet** [streamlink/streamlink#4240]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi everyone,

Could you please develop a plugin for tikilive website? The website is a platform like twitch. You can stream live content.

https://www.tikilive.com/live/category/3

### Input URLs

https://www.tikilive.com/live/category/3
https://www.tikilive.com/channel/bodrum-kent-tv
https://www.tikilive.com/channel/atv-networks

**Comment by LaneSh4d0w** [comment]
If this may help : 

One request gives the SID of the channel : 
https://tikilive.com:8080/socket.io/?c=34967&n=TIKISESSID&i=of9nf2i27nefb5eqg3eipcaafm&EIO=3&transport=polling&t=Nw7TRav (octet-stream, base64 data)

Another one, followed with the SID given before, gives all data : 
https://tikilive.com:8080/socket.io/?c=34967&n=TIKISESSID&i=of9nf2i27nefb5eqg3eipcaafm&EIO=3&transport=polling&t=Nw7TRf4&sid= *insert SID here* (same as the one above, octet-stream, base64 data)

Links are made like this
https://edge2.tikilive.com/livehttporigin_tikilive/ * insert channel ID * /amlst:mainstream/playlist.m3u8?p=local&op_id=19&userId=0&channelId= * channel ID * &stime= * actual timestamp * &etime= * actual timestamp + 2 hours it seems * &key= * key * &token= * token *

**Comment by back-to** [comment]
Small website with to many rehostet content.
