### ISSUE TITLE
plugins.plugin-name-here: A very brief summary of what's broken

### ISSUE THREAD

**Issue by cChimney** [streamlink/streamlink#4241]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Hello i am getting the following error when trying to connect to a twitch stream. Tried different users but same error.
error: No playable streams found on this URL: https://www.twitch.tv/name
please help, ty. Using streamlink 3.0.3

### Debug log

```text
error: No playable streams found on this URL: https://www.twitch.tv/name
```

**Comment by bastimeyer** [comment]
Post the **entire command you're using AND the entire debug log output**, as required by the issue template.

`--loglevel=debug`
https://streamlink.github.io/cli.html#cmdoption-loglevel
