### ISSUE TITLE
error: unrecognized arguments: best

### ISSUE THREAD

**Issue by umutbalkan** [streamlink/streamlink#4253]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

`streamlink twitch.tv/day9tv best` does not work.

stdout as follows:
```
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: best
```

did I missed a couple of updates or is quickstart misleading?

### Debug log

```text
C:\Users\umutb>streamlink twitch.tv/day9tv best
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: best

C:\Users\umutb>streamlink fb.gg/t90official best
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: best
```

**Comment by mkbloke** [comment]
What is the output of `streamlink --version`?  It seems like there's something very broken about your installation.  Have you tried completely uninstalling it (and making sure there are no traces of it, including any batch files, hanging around) then reinstalling?

**Comment by umutbalkan** [comment]
This happens when i am using the latest 3.0.3 version. previous 2.4.0 works all fine. I installed via windows installer.

**Comment by bastimeyer** [comment]
Post the **entire command with debug log output**, as requested by the issue template.
[`--loglevel=debug`](https://streamlink.github.io/cli.html#cmdoption-loglevel)

It is very likely that you either have a broken/invalid config file, or that your Streamlink install is broken. Try to **completely uninstall** Streamlink, remove any left over files (if there are any), and then install it again.

**Comment by umutbalkan** [comment]
I completely reinstalled windows 10. Now Streamlink 3.0.3 installer works all fine, worth it.

**Comment by TSIXGaming** [comment]
I think the issue is in the config file from an old version
Delete old config file in this folder
C > users > username > appdata > roaming > streamlink > 
Instal latest streamlink
Should work now
