### ISSUE TITLE
Tga.py plugin errors

### ISSUE THREAD

**Issue by prech** [streamlink/streamlink#426]
Many thanks to the developers for making Streamlink such a wonderful tool.

Would appreciate some help with the Longzhu plugin. No log-in is required.

Some test streams:
[http://longzhu.com/channels/lol](http://longzhu.com/channels/lol)

Thanks!

---
This is the error I encounter with every Longzhu attempt:

> streamlink http://star.longzhu.com/m185404
[cli][info] Found matching plugin tga for URL http://star.longzhu.com/m185404
Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\validate.py
", line 358, in validate_dict
    new[key] = validate(subschema, value[key])
  File "functools.py", line 743, in wrapper
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\api\validate.py
", line 312, in validate_any
    raise ValueError(err)
ValueError: {'game': [{'Name': '\u5fa1\u5b85', 'Id': 127, 'id': 127, 'tag': 'yuz
hai', 'name': '\u5fa1\u5b85'}], 'viewers': '30193', 'channel': {'broadcast_begin
': 1484458744000, 'url': 'http://star.longzhu.com/m185404', 'status': '\u6211\u5
0cf\u674e\u51b0\u51b0\u5417', 'flowers': 475846, '_subtype': 4, 'videos': 0, 'we
ight': 200703216, 'live_source': 2, 'grade': 16, 'stream_types': 10, 'followers'
: 118504, '_type': 1, 'id': 537278, 'tag': '', 'broadcast_duration': 417, 'h5':
'http://star.longzhu.com/m/m185404', 'domain': 'm185404', 'glamours': 8721070, '
belle': 0, 'name': '\u7231\u4e3d\u4e1delise', 'vid': 0, 'avatar': 'http://q.qlog
o.cn/qqapp/100360418/502190FFE6EB68E530BD623BB14DE17E/40'}, 'preview_auto': Fals
e, 'preview': 'http://img2.plures.net/a0735684-5572-4693-9d12-7338fab2cfb8', 'yz
cm_phase': False, 'preview2': 'http://img2.plures.net/c6552882-cee6-4e1c-b788-fe
c898cdd101'} does not equal None or Unable to validate key 'channel': {'broadcas
t_begin': 1484458744000, 'url': 'http://star.longzhu.com/m185404', 'status': '\u
6211\u50cf\u674e\u51b0\u51b0\u5417', 'flowers': 475846, '_subtype': 4, 'videos':
 0, 'weight': 200703216, 'live_source': 2, 'grade': 16, 'stream_types': 10, 'fol
lowers': 118504, '_type': 1, 'id': 537278, 'tag': '', 'broadcast_duration': 417,
 'h5': 'http://star.longzhu.com/m/m185404', 'domain': 'm185404', 'glamours': 872
1070, 'belle': 0, 'name': '\u7231\u4e3d\u4e1delise', 'vid': 0, 'avatar': 'http:/
/q.qlogo.cn/qqapp/100360418/502190FFE6EB68E530BD623BB14DE17E/40'} does not equal
 None or Unable to validate key 'id': Type of 537278 should be 'str' but is 'int
'

**Comment by fozzysec** [comment]
Got it fixed, I opened a PR #456 on it.

**Comment by gravyboat** [comment]
Closing since #456 is merged, thanks for the report!
