### ISSUE TITLE
Lost audio

### ISSUE THREAD

**Issue by vstavrinov** [streamlink/streamlink#4262]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

There are working examples, all this works well:

``
vlc https://live-hls-web-aje.getaj.net/AJE/index.m3u
``
``
youtube-dl -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -
``
``
streamlink -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc - --no-fb-hw-accel
``

But this doesn't work:

``
streamlink -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -
``

i.e. it is a silent video. The vlc statistic shows all audio buffers lost and it's log full of the error messages:

``
 main decoder error: Timestamp conversion failed
 ``
 
 Turning off hardware acceleration is not a good idea, so given the working examples, I hope streamlink could be fixed

### Debug log

```text
[cli][debug] OS:         Linux-5.15.0-2-amd64-x86_64-with-glibc2.33
[cli][debug] Python:     3.9.9
[cli][debug] Streamlink: 3.0.3+430.g2de5953
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://live-hls-web-aje.getaj.net/AJE/index.m3u8
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv --quiet
[cli][debug]  --output=-
[cli][debug]  --default-stream=['best']
[cli][info] Found matching plugin hls for URL https://live-hls-web-aje.getaj.net/AJE/index.m3u8
[plugins.hls][debug] URL=https://live-hls-web-aje.getaj.net/AJE/index.m3u8; params={}
[utils.l10n][debug] Language code: ru_RU
[cli][info] Available streams: 240p_alt (worst), 240p, 360p_alt, 360p, 420p_alt, 420p, 540p_alt, 540p, 720p_alt, 720p, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 3875749; Last Sequence: 3875754
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3875752; End Sequence: None
[stream.hls][debug] Adding segment 3875752 to queue
[stream.hls][debug] Adding segment 3875753 to queue
[stream.hls][debug] Adding segment 3875754 to queue
[cli][debug] Writing stream to output
[stream.hls][debug] Segment 3875752 complete
[stream.hls][debug] Segment 3875753 complete
[stream.hls][debug] Segment 3875754 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3875755 to queue
[stream.hls][debug] Segment 3875755 complete
```

**Comment by bastimeyer** [comment]
> 2de5953

This is not a commit from the streamlink/streamlink repo

The URL you've posted is a regular HLS stream and all that Streamlink has to do here is concat the segments, which it does.

```sh
curl -sSL 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8'
```

```m3u
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=6324320,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/01.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6324320,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/01.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3120800,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/02.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3120800,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/02.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1831872,RESOLUTION=960x540,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/03.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1831872,RESOLUTION=960x540,CODECS="avc1.64001f,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/03.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1013696,RESOLUTION=746x420,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/04.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1013696,RESOLUTION=746x420,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/04.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=813664,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/05.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=813664,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/05.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=428640,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE/06.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=428640,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
https://live-hls-web-aje.getaj.net/AJE-b/06.m3u8
```

```sh
curl -s 'https://live-hls-web-aje.getaj.net/AJE/01.m3u8'
```

```m3u
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:3875990
#EXTINF:10.0000,
20201001T013811-01-3875990.ts
#EXTINF:10.0000,
20201001T013811-01-3875991.ts
#EXTINF:10.0000,
20201001T013811-01-3875992.ts
#EXTINF:10.0000,
20201001T013811-01-3875993.ts
#EXTINF:10.0000,
20201001T013811-01-3875994.ts
#EXTINF:10.0000,
20201001T013811-01-3875995.ts
```

> `streamlink -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -`

You are not selecting any streams. And there is a video and audio stream in the MPEGTS output.

```sh
streamlink -l none --stdout 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8' best \
  | ffprobe -v error -show_format -show_streams -print_format json - \
  | jq
```
```json
{
  "streams": [
    {
      "index": 0,
      "codec_name": "h264",
      "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      "profile": "High",
      "codec_type": "video",
      "codec_tag_string": "[27][0][0][0]",
      "codec_tag": "0x001b",
      "width": 1920,
      "height": 1080,
      "coded_width": 1920,
      "coded_height": 1080,
      "closed_captions": 0,
      "has_b_frames": 2,
      "sample_aspect_ratio": "1:1",
      "display_aspect_ratio": "16:9",
      "pix_fmt": "yuv420p",
      "level": 40,
      "color_range": "tv",
      "chroma_location": "left",
      "field_order": "progressive",
      "refs": 1,
      "is_avc": "false",
      "nal_length_size": "0",
      "id": "0x121",
      "r_frame_rate": "25/1",
      "avg_frame_rate": "25/1",
      "time_base": "1/90000",
      "start_pts": 8015496250,
      "start_time": "89061.069444",
      "bits_per_raw_sample": "8",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    },
    {
      "index": 1,
      "codec_name": "aac",
      "codec_long_name": "AAC (Advanced Audio Coding)",
      "profile": "LC",
      "codec_type": "audio",
      "codec_tag_string": "[15][0][0][0]",
      "codec_tag": "0x000f",
      "sample_fmt": "fltp",
      "sample_rate": "48000",
      "channels": 2,
      "channel_layout": "stereo",
      "bits_per_sample": 0,
      "id": "0x131",
      "r_frame_rate": "0/0",
      "avg_frame_rate": "0/0",
      "time_base": "1/90000",
      "start_pts": 8015496707,
      "start_time": "89061.074522",
      "bit_rate": "130548",
      "disposition": {
        "default": 0,
        "dub": 0,
        "original": 0,
        "comment": 0,
        "lyrics": 0,
        "karaoke": 0,
        "forced": 0,
        "hearing_impaired": 0,
        "visual_impaired": 0,
        "clean_effects": 0,
        "attached_pic": 0,
        "timed_thumbnails": 0
      }
    }
  ],
  "format": {
    "filename": "pipe:",
    "nb_streams": 2,
    "nb_programs": 1,
    "format_name": "mpegts",
    "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
    "start_time": "89061.069444",
    "probe_score": 50
  }
}
```

**Comment by vstavrinov** [comment]
@bastimeyer 
> 
> This is not a commit from the streamlink/streamlink repo
> 

It is from my fork of the latest upstream commit, but there are no differences related to this issue.

> The URL you've posted is a regular HLS stream and all that Streamlink has to do here is concat the segments, which it does.

And what? That doesn't matter. It doesn't change the fact of the problem.

> 
> ```shell
> curl -s 'https://live-hls-web-aje.getaj.net/AJE/01.m3u8'
> ```

Yes, this is the default stream, and You can use it directly to reproduce the problem with the same result.

> 
> > `streamlink -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -`
> 
> You are not selecting any streams. And there is a video and audio stream in the MPEGTS output.
> 

See above: there is a default stream. You can explicitly select the stream this changes nothing, this doesn't solve the problem.

> ```shell
> streamlink -l none --stdout 'https://live-hls-web-aje.getaj.net/AJE/index.m3u8' best \
>   | ffprobe -v error -show_format -show_streams -print_format json - \
>   | jq

You don't need this debug to see there is an audio stream. You can do this with vlc. You miss my explicit statement: "The vlc statistic shows all audio buffers lost". That means the audio stream exists, but all audio buffers lost and that is why it is totally silent. 
 
And finally, you totally ignore three working examples and error messages. Could you explain why there is no problem with those examples but with the last one?

And the last question to You: did You have tried to reproduce this problem before closing this issue? I guess You didn't. If I am wrong You should hear the stream. If you don't want to investigate and solve the problem this is not the reason to close the issue. Somebody else could do this. And even if not, the opened issue serves as documented existence of the problem.

P.S. This is not a unique example of the problematic stream. There are some others. So this is not a local problem.

**Comment by bastimeyer** [comment]
This is a problem with your VLC player, not Streamlink. Try using a different player like MPV for example.

As I've already said, this is a simple HLS stream and Streamlink does its job correctly by concatenating the segments and writing the stream to the output. There's nothing more for Streamlink to do here. If you write the stream to your file system and check/validate the contents via ffmpeg/ffprobe for example, you'll see that the stream itself is fine.

VLC is known to have lots of issues. One popular issue when trying to play back MPEGTS streams is the lack of `aribb24` installed on the user's system, an optional dependency which is required by vlc for demuxing MPEGTS streams.
https://bbs.archlinux.org/viewtopic.php?id=240169

If that still doesn't work because of timestamp issues for example, then you have to remux the stream to a different container format (on the fly or after writing to the file system). But that's not Streamlink's job when you input an HLS stream via the HLS plugin.

I also don't close threads before checking, so you don't have to accuse me here.

https://github.com/streamlink/streamlink/issues/3393#issuecomment-739338353

**Comment by vstavrinov** [comment]
mpv is not the option for android or playlist. You still ignore the fact that there is no such problem with youtube-dl that does similar work as streamlink does. Even if there is a bug in vlc it doesn't prevent youtube-dl to do its work as expected. As well this stream causes no such problem with vlc itself without streamlink. So the problem was introduced by streamlink no matter how simple is the work it does. This is the fact.

> I also don't close threads before checking, so you don't have to accuse me here.

Does this mean You hear the stream?

**Comment by vstavrinov** [comment]
> One popular issue when trying to play back MPEGTS streams is the lack of `aribb24`

It is installed on my Linux, so it is not the cause.

**Comment by kikuyan** [comment]
youtube-dl uses ffmpeg by default for download if m3u8 URLs are directly specified. You won't hear audio if you add `--hls-prefer-native` to youtube-dl.

Process the stream by ffmpeg, and you'll hear audio by piping `ffmpeg -i pipe:0 -c copy -f mpegts - ` between streamlink and vlc.

**Comment by vstavrinov** [comment]
@kikuyan What for You recommend ffmpeg? Did You read this bug report? If so You should know that I can playback and hear this stream with vlc without streamlink, without youtube-dl and without ffmpeg. But this is not what this post is about. There is nothing new for me in this thread about neither youtube-dl nor ffmpeg. I know how they work and I am using both of them. But this bug report is not about them. It is about the problem with streamlink. Nevertheless, there is no one adequate response to this problem in this thread. This is not the first case where youtube-dl works while streamlink doesn't, but its authors argue it shouldn't. This is a bad style and wrong ideology. Such arguments encourage users to prefer youtube-dl instead of streamlink and the last loses the competition despite differences in their destenition (streamlink for live streams and yuotube-dl for VOD). I am still using both, but the balance drifts toward youtube-dl.

**Comment by kikuyan** [comment]
If you blame, it's vlc which doesn't play audio from the middle of this stream correctly.
Download ts of this stream directly (curl, wget or else) and feed it to vlc. You won't hear audio.

**Comment by vstavrinov** [comment]
@kikuyan, look at the top of this thread again. Did You see this:

``youtube-dl -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -``

It's working, i.e. I can hear the audio stream very well. But this one:

``streamlink -o - https://live-hls-web-aje.getaj.net/AJE/index.m3u8 | vlc -``

doesn't work, i.e. I can't hear the audio stream. If You have no ideas, no thoughts, no feeling of how to make the last option (streamlink) work, please don't waste your and our time. This is about streamlink, not about whatever other.

**Comment by back-to** [comment]
> youtube-dl
 It's working, i.e. I can hear the audio stream very well. But this one:

why it works https://github.com/streamlink/streamlink/issues/4262#issuecomment-1000636208

> This is about streamlink, not about whatever other. Make streamlink work, not vlc.

No, it is **VLC**.

use https://mpv.io/ or try https://nightlies.videolan.org/
