### ISSUE TITLE
Plugin for USTVGO -PHOTOCALLTV and Telemicro Republic Dominican

### ISSUE THREAD

**Issue by Renatovi557** [streamlink/streamlink#4279]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Good morning.
I would like to make a request to add these sites in the plugin 
ustvgo...channels tv live american Telemundo Univision etc
photocalltv channels tv live spanish
Telemicro channel live Republic Dominican

thanks

### Input URLs

https://ustvgo.tv/
https://www.photocall.tv/
https://telemicro.com.do/telemicro-en-vivo/

**Comment by gravyboat** [comment]
* ustvgo.tv is a rip off of ustvnow and will not be added: https://github.com/streamlink/streamlink/issues/2876
* photocall.tv is TV stations which we will not add as per the plugin request guidelines ([rule 3](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests)) which you explicitly noted you read when you checked the box creating this issue but didn't.
* telemicro.com.do is the same thing as above, it's just TV stations.

None of these plugins meet our requirements so I'm closing and locking this.
