### ISSUE TITLE
okru plugin - can't find metadata and don't work

### ISSUE THREAD

**Issue by linked67** [streamlink/streamlink#4280]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

There is a problem with okru plugin:

```text
streamlink https://ok.ru/live/4213665177548
[cli][info] Found matching plugin okru for URL https://ok.ru/live/4213665177548
[plugins.okru][error] Could not find metadata
error: No playable streams found on this URL: https://ok.ru/live/4213665177548
```

### Debug log

```text
streamlink https://ok.ru/live/4213665177548 --loglevel debug
[cli][debug] OS:         macOS 12.1
[cli][debug] Python:     3.10.1
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://ok.ru/live/4213665177548
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin okru for URL https://ok.ru/live/4213665177548
[plugins.okru][error] Could not find metadata
error: No playable streams found on this URL: https://ok.ru/live/4213665177548
```

**Comment by bastimeyer** [comment]
The plugin is working fine when checking your URL, as well as any other live stream on their site I've checked. Not sure if this was a temporary issue on the website or if your IP address is blocked.

```
$ streamlink https://ok.ru/live/4213665177548 --loglevel debug
[cli][debug] OS:         Linux-5.15.9-1-git-x86_64-with-glibc2.33
[cli][debug] Python:     3.10.1
[cli][debug] Streamlink: 3.0.3+30.g8eb0c74
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://ok.ru/live/4213665177548
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin okru for URL https://ok.ru/live/4213665177548
[utils.l10n][debug] Language code: en_US
Available streams: 256p (worst), 426p, 640p, 852p, 1280p (best)
```

I'm going to close the thread. If this can be reliably reproduced, please reopen.
