### ISSUE TITLE
Twitch proxy error: No playable streams found

### ISSUE THREAD

**Issue by wujekbefore** [streamlink/streamlink#4282]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When I try to watch a twitch channel using a proxy I get an error: error: No playable streams found on this URL:

Without the "http-proxy" argument it works fine. This is not the fault of the proxy, I have tested a lot of proxies

### Debug log

```text
streamlink --loglevel debug --twitch-disable-ads --player-http --http-proxy 80.48.119.28 https://www.twitch.tv/chickencamsoftexas audio_only
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.8
[cli][debug] Streamlink: 3.0.3
[cli][debug] Requests(2.27.1), Socks(1.6.7), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/chickencamsoftexas
[cli][debug]  stream=['audio_only']
[cli][debug]  --loglevel=debug
[cli][debug]  --player-http=True
[cli][debug]  --http-proxy=80.48.119.28
[cli][debug]  --twitch-disable-ads=True
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/chickencamsoftexas
[plugins.twitch][debug] Getting live HLS streams for chickencamsoftexas
error: No playable streams found on this URL: https://www.twitch.tv/chickencamsoftexas
```

**Comment by bastimeyer** [comment]
Not a plugin error or streamlink error. Your proxy server is blocked by Twitch.
