### ISSUE TITLE
plugins.foxtr: No playable streams found

### ISSUE THREAD

**Issue by fenopa** [streamlink/streamlink#4283]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Plugin does not work

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 3.0.1+61.gae63436
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.fox.com.tr/canli-yayin
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin foxtr for URL https://www.fox.com.tr/canli-yayin
error: No playable streams found on this URL: https://www.fox.com.tr/canli-yayin
```

**Comment by bastimeyer** [comment]
> Latest build from the master branch

ae63436 is not part of streamlink/streamlink@master
This is from your own fork which is not supported here...

> error: No playable streams found on this URL: https://www.fox.com.tr/canli-yayin

The site has made some changes. Extracting the HLS URLs should still be easy and is just a simple regex change in the plugin:
https://github.com/streamlink/streamlink/blob/8eb0c74aba45f09c6a8da4bf395e4ac50caebd57/src/streamlink/plugins/foxtr.py#L11

**Comment by fenopa** [comment]
Thanks.

> This is from your own fork which is not supported here...
shouldn't really matter, I had already checked with last stable and last test build from action as well. Sorry for adding wrong output.
