### ISSUE TITLE
No maintainer in Gentoo

### ISSUE THREAD

**Issue by vsvjoirwv** [streamlink/streamlink#4287]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hi, first of all thank you very much for making the app. Unfortunately there is no maintainer for Gentoo package of Streamlink for months (the lates version in the tree is 2.0.0). Here is the bug: https://bugs.gentoo.org/789771

Maybe somebody from the developers could provide a fresh ebuild? It would be very much appreciated!

**Comment by bastimeyer** [comment]
https://streamlink.github.io/install.html#linux-and-bsd

None of the maintainers here are involved with any kind of distro packaging. This is up to the distro package / repository maintainers and there's nothing that can be done here. Your issue may only raise awareness for the problem, but this is already done on the distro's own issue tracker, which is a better place for it anyway.

If a package is not available for a certain distro or if it's out of date, then you can still install Streamlink via python-pip in a separate python environment (eg. the default user environment or a virtual environment), or you can download and run the pre-built AppImage. All of that is described in the linked documentation.

Contacting and asking the distro package maintainer directly is also an option.
