### ISSUE TITLE
Parsing options is not working

### ISSUE THREAD

**Issue by ChristophKrause** [streamlink/streamlink#4293]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

After updating from 2.4 to 3.03, the recently working command lines are not working anymore
Usage before:
"C:\Program Files (x86)\Streamlink\bin\Streamlink.exe" --player-external-http --player-continuous-http --retry-streams 30 --retry-max 100 --retry-open 3 https://www.twitch.tv/doktorfroid Worst
or 
"C:\Program Files (x86)\Streamlink\bin\Streamlink.exe"  https://www.twitch.tv/doktorfroid Worst

Result:
![image](https://user-images.githubusercontent.com/10434825/149524363-47200ceb-2d39-4169-b1a5-9504d36cc72e.png)

streamlink  -l debug https://www.twitch.tv/doktorfroid Worst
Result:
![image](https://user-images.githubusercontent.com/10434825/149524413-8d1fac86-c553-4e34-9fba-4502c5a44d80.png)

The same problem appears when using youtube links

![image](https://user-images.githubusercontent.com/10434825/149524572-0684d24b-df5b-45e9-be10-9722ea640862.png)

![image](https://user-images.githubusercontent.com/10434825/149524622-0015cd43-1a19-492c-a794-156baa7ea268.png)

I tested the versions
2.4.0 => working
3.0.0 => error message
3.0.1-3.0.3 => this problem

This is happening on 3 different Windows 10 systems

### Debug log

```text
$ streamlink  --loglevel debug https://www.twitch.tv/doktorfroid Worst
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe https://www.twitch.tv/doktorfroid Worst
```

**Comment by mkbloke** [comment]
https://github.com/streamlink/streamlink/issues/4211#issuecomment-980283012
