### ISSUE TITLE
Add support for license url option for protected DRM live stream

### ISSUE THREAD

**Issue by munfaqqiha** [streamlink/streamlink#4299]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Dear Developers

I can able to watch a mpd dash manifest of the protected DRM live stream smoothly through [bitmovin](https://bitmovin.com/demos/drm). 

It would be much appreciated if you could add this option.

Thank You.
R

**Comment by mkbloke** [comment]
https://github.com/streamlink/streamlink/issues/3614#issuecomment-793006065
