### ISSUE TITLE
RTVE.es : additional addresses for channels

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#430]
On this page you can find channels with different address presentation but not included on the RTVE.es script. 

`streamlink "http://www.rtve.es/directo/canal-24h/" best
error: No plugin can handle URL: http://www.rtve.es/directo/canal-24h/`

Source : `http://www.rtve.es/directo`

`http://www.rtve.es/directo/la-1/`
`http://www.rtve.es/directo/la-2/`
`http://www.rtve.es/directo/teledeporte/`
`http://www.rtve.es/directo/canal-24h/`
`http://www.rtve.es/mas24/`
`http://www.rtve.es/deportes/mas-tdp/directo/`
`http://www.rtve.es/television/catalunya/directo/`

**Comment by gravyboat** [comment]
Are these needed? As in can you get to the same content without using these longer URLs?

**Comment by karlo2105** [comment]
Those addresses are not longer than supported ones. For instance : `http://www.rtve.es/noticias/directo-la-1/`
I thought Streamlink plugins were to be the most completed possible so far. 
I am not even Spanish speaking but my purpose was to have the most completed plugins. I hope most of members share my point of view.

**Comment by beardypig** [comment]
I only see the URLs like: http://www.rtve.es/noticias/directo-la-1/ on www.rtve.es
The site on http://www.rtve.es/directo/la-1/ looks like the old version of the site...

**Comment by karlo2105** [comment]
Thanks for support. ;)

**Comment by gravyboat** [comment]
Closing since this was fixed in #433. Thanks for the report @karlo2105.
