### ISSUE TITLE
3.1.0: streamlinkw.exe / streamlink.exe broken on Windows

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4307]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

There seems to be an issue with the Streamlink executables in the Windows installer of the Streamlink 3.1.0 release. This wasn't the case in the 3.0.3 release. See here:
https://github.com/streamlink/streamlink-twitch-gui/discussions/854#discussioncomment-2031370

For some reason, both streamlinkw.exe and streamlink.exe immediately terminate with exit code `3221225477` (`0xC0000005`) since the 3.1.0 release, but only when not launching them from a command line shell, eg. from Streamlink Twitch GUI.

If streamlinkw.exe gets executed from the MinGW bash shell, its exit code is 0 and it prints output to stdout. If it gets executed from the powershell, its exit code is 0 but there's no stdout output (which expected behavior).

This is very weird and I'm not sure what has caused this. The Python version of the Windows installer hasn't been changed between 3.0.3 and 3.1.0, and neither have the dependencies (which are pinpointed with checksums):
```
$ git diff 3.0.3..3.1.0 script/makeinstaller{.sh,-{assets,requirements}.json}
(empty)
```

Comparing the checksums of both bundled Python installs in 3.0.3 and 3.1.0 shows that both are indentical. The executable wrappers `streamlinkw.exe` and `streamlink.exe` however are not identical compared to the previous release.

This is how pynsist builds the wrappers:
https://github.com/takluyver/pynsist/blame/2.7/nsist/commands.py
(pynsist 2.7 was used for both 3.0.3 and 3.1.0)

As you can see, the wrappers get their executable code from distlib, and they append a shebang and entry script.

- 3.1.0 - distlib 0.3.4:
  https://github.com/streamlink/streamlink/runs/4909013773?check_suite_focus=true#step:5:122
- 3.0.3 - distlib 0.3.3
  https://github.com/streamlink/streamlink/runs/4342741552?check_suite_focus=true#step:5:128

Distlib had a new release in December and the changelog suggests that something has changed in regards to the launcher executables:
https://github.com/pypa/distlib/blob/master/CHANGES.rst#034

- https://github.com/pypa/distlib/commits/0.3.4
- https://github.com/pypa/distlib/commit/e9923d5af745c68affdb2c1f45d1b3f05138e245#diff-e2ab17b255bd58eedd164c4013e70168ee5441e9a93ca15a09baa2d6d912d9c0R419-R422

**Comment by bastimeyer** [comment]
Since the executable wrappers built via pip when installing the streamlink wheel from pypi are working fine, this probably means that pynsist needs to be fixed/upgraded.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/releases/tag/3.1.1

**Comment by dogbertai** [comment]
The pip install method is still broken because pip-22.0.3 uses the same broken distlib.
https://github.com/pypa/pip/issues/10875
The workaround is to downgrade pip.
The solution is to wait for the next version of pip.
