### ISSUE TITLE
pluzz.francetv.fr,  how?

### ISSUE THREAD

**Issue by Ordval** [streamlink/streamlink#431]
How is a command line supposed to be implemented  ?

Put like this it wont work:
streamlink.exe http://pluzz.francetv.fr/videos/on_nest_pas_couche_saison11_,151891332.html best
(error: No plugin can handle URL: http://pluzz.francetv.fr/videos /on_nest_pas_couche_saison11_,151891332.html)

whereas it will play in a browser (Windows 10),
and by the way, without “best” nothing will work.

**Comment by beardypig** [comment]
Do you have the latest nightly version?

**Comment by karlo2105** [comment]
I installed streamlink development through python 2.7.13. Streamlink is located here `C:\Program Files\Python27\Lib\site-packages`
The main advantage is streamlink is available from any directory. 
It's working fine. 

`streamlink "http://pluzz.francetv.fr/videos/on_nest_pas_couche_saison11_,151891332.html" best
[cli][info] Found matching plugin pluzz for URL http://pluzz.francetv.fr/videos/
on_nest_pas_couche_saison11_,151891332.html
[cli][info] Available streams: 144p_alt, 288p_alt, 180p_alt, 396p_alt, 180k (wor
st), 303k, 144p, 180p, 575k, 288p, 831k, 396p, 1467k, 576p (best)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended`

You can also find "On n'est pas couchés" here : `https://www.youtube.com/user/onpcofficielle/videos`

**Comment by Ordval** [comment]
I've put up an example karlo2105! (LoL).

Let's stay with what I have so far.
I'm a classic Plug-n-Play. If it's not an easy install, I seldom bother.

So now they're both installed because of the uncertainty of a Nightly build. 
How would a command line look ?  

C:\Program Files (x86)\Streamlink Nightly build\bin\streamlink.exe http://pluzz.francetv.fr/videos/on_nest_pas_couche_saison11_,151891332.html best
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Thanks for your quick response, beardypig.

> The main advantage is streamlink is available from any directory.
I don't really know what that means in this case. 
I would always use a MRL to play video streams through e.g. Livestreamer.

**Comment by beardypig** [comment]
@Ordval you should just be able to run 
```
streamlink "http://pluzz.francetv.fr/videos/on_nest_pas_couche_saison11_,151891332.html" best
```
But if you've got another bin directory in your PATH as I think I understand you might, then you will need the full path. You may need to use " quotes around the exe path. 
```
" C:\Program Files (x86)\Streamlink Nightly build\bin\streamlink.exe" 
```

**Comment by Ordval** [comment]
Yep, yep, that made it ! 
But not possible in the regular version then ?

**Comment by beardypig** [comment]
What does 
```
set PATH
```
return? If you used easy_install you probably have an old version (stable 0.2.0) in the PATH before the nightly.

**Comment by Ordval** [comment]
Right you are. No reason to keep it ? 

Path=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Livestreamer;C:\Users\Ordval\Documents\Spellistor\Script Loader by Darby_Crash\php\rtmpdump.exe;C:\Program Files (x86)\Streamlink\bin;C:\Program Files (x86)\Streamlink Nightly build\bin;C:\Users\Ordval\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

**Comment by Ordval** [comment]
As this seems to be the only thread; X-Forwarded-For won't work here.

**Comment by karlo2105** [comment]
@Ordval 
If you want to stick it with Livestreamer you can add manually pluzz plugin into Livestreamer directory of plugins you just have to rename "streamlink" to "livestreamer" in pluzz.py.

**Comment by beardypig** [comment]
@Ordval what do you mean X-Forwarded-For won't work here?

**Comment by Ordval** [comment]
For a while there, it was possible to use X-Forwarded-For with Pluzz if One had some appropriate MRL, 
but they've sharpened their security,....unless you know of a workaround ?
The –http-proxy could be a possibility but as it still is possible to use a free vpn I'd rather go with that.

**Comment by beardypig** [comment]
OK, have you solved the problem now?

**Comment by Ordval** [comment]
Using a free VPN, or what do you mean ? That is what I use.

**Comment by beardypig** [comment]
Alright, since you solved it I think we can close this issue :)
