### ISSUE TITLE
stream.hls: about the output of media initialization section

### ISSUE THREAD

**Issue by thisisgk** [streamlink/streamlink#4310]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

For HLS playlist which has EXT-X-MAP tag (media initialization section), streamlink currently prepends the media initialization section to each fMP4 segment and make an output.
From the explanation of PR #3828, this seems to be done intentionally, but it results in the output stream/file containing multiple 'ftyp' boxes and 'moov' boxes, which should not be correct for ISOBMFF.
It seems that the media initialization section should only be output at the beginning of the stream/file.

The output file can be handled by ffmpeg, and seems to be played in mpv and vlc, though. However, ffmpeg and mpv show the warning "Found duplicated MOOV Atom. Skipped it", and vlc shows "mp4 demux: Fragment sequence discontinuity detected 1 != 0".

I generated and tested the following HLS playlist and DASH manifest using the same media files, so as to make it easy to compare the streamlink outputs.
```
$ mkdir /tmp/test
$ ffmpeg -f lavfi -i testsrc \
-use_template 0 \
-init_seg_name 'init$RepresentationID$.$ext$' \
-media_seg_name 'seg$RepresentationID$-$Number%02d$.$ext$' \
-dash_segment_type mp4 \
-hls_playlist 1 -hls_master_name master.m3u8 \
-f dash -t 30 /tmp/test/manifest.mpd

$ ls -1 /tmp/test
init0.m4s
manifest.mpd
master.m3u8
media_0.m3u8
seg0-01.m4s
seg0-02.m4s
seg0-03.m4s
```
Then ran streamlink.
```
$ streamlink hls://file:///tmp/test/master.m3u8 best -o output-hls.mp4
$ streamlink dash://file:///tmp/test/manifest.mpd best -o output-dash.mp4
```
output-hls.mp4 with the HLS playlist matches `cat init0.m4s seg0-01.m4s init0.m4s seg0-02.m4s init0.m4s seg0-03.m4s`.
output-dash.mp4 with the DASH manifest matches `cat init0.m4s seg0-01.m4s seg0-02.m4s seg0-03.m4s`.
output-hls.mp4 should be the same as output-dash.mp4.

The following log is of `streamlink -l debug -p mpv -v --player-no-close hls://file:///tmp/test/master.m3u8 best`.

### Debug log

```text
[cli][debug] OS:         macOS 10.12.6
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=hls://file:///tmp/test/master.m3u8
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --verbose-player=True
[cli][debug]  --player-no-close=True
[cli][info] Found matching plugin hls for URL hls://file:///tmp/test/master.m3u8
[plugins.hls][debug] URL=file:///tmp/test/master.m3u8; params={}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 240p (worst, best)
[cli][info] Opening stream: 240p (hls)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 1; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: 3
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.segmented][debug] Closing worker thread
[stream.hls][debug] Segment initialization 1 complete
[cli.output][debug] Opening subprocess: mpv --force-media-title=hls://file:///tmp/test/master.m3u8 -
[stream.hls][debug] Segment 1 complete
[stream.hls][debug] Segment initialization 2 complete
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Segment initialization 3 complete
[stream.hls][debug] Segment 3 complete
[stream.segmented][debug] Closing writer thread
[file] Reading from stdin...
[cli][debug] Writing stream to output
 (+) Video --vid=1 (*) (h264 320x240 25.000fps)
[vo/gpu] opengl cocoa backend is deprecated, use vo=libmpv instead
VO: [gpu] 320x240 yuv444p
V: 00:00:08 / 00:00:10 (86%)
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Found duplicated MOOV Atom. Skipped it
[cli][info] Stream ended90%)
V: 00:00:18 / 00:00:19 (94%)
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Found duplicated MOOV Atom. Skipped it
V: 00:00:29 / 00:00:29 (100%)

Exiting... (End of file)
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
As you've already said, applying the map contents to each segment in the output was done intentionally. See here, why:
https://github.com/streamlink/streamlink/pull/3403#issuecomment-743758508

**Comment by thisisgk** [comment]
I'm not sure how to interpret RFC 8216, but based on the output file format, it seems to me that the description of how to handle media initialization section is for a parser, and indicates that when a parser processes a segment (especially from the middle), it also needs to consider media initialization section, since a segment cannot be processed solely.

**Comment by bastimeyer** [comment]
FFmpeg 6.1 now rejects streams with multiple initialization sections, which means this finally needs to be fixed now.
See #5601
