### ISSUE TITLE
MTVA

### ISSUE THREAD

**Issue by aicon** [streamlink/streamlink#4312]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

It will be useful if someone can create a plugin for MTVA or help me to update the old version created by me for python 2 to the latest streamlink.

`
import re
import json,requests

from streamlink.plugin import Plugin
from streamlink.plugin.plugin import LOW_PRIORITY, NORMAL_PRIORITY, NO_PRIORITY, parse_params
from streamlink.stream import HLSStream
from streamlink.plugin.api import useragents
from urllib.parse import urlparse
from streamlink.utils import parse_json, parse_xml

USER_AGENT = "User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"

class MTVAPlugin(Plugin):
    _url_re = re.compile(r"https?://(.+)mtva\.hu(.+)")
    @classmethod
    def priority(cls, url):
        """
        Returns LOW priority if the URL is not prefixed with hls:// but ends with
        .m3u8 and return NORMAL priority if the URL is prefixed.
        :param url: the URL to find the plugin priority for
        :return: plugin priority for the given URL
        """
        m = cls._url_re.match(url)
        if m:
            prefix, url = cls._url_re.match(url).groups()
            url_path = urlparse(url).path
            if url_path.endswith("abcd"):
                return LOW_PRIORITY
            elif prefix is not None:
                return NORMAL_PRIORITY
        return NO_PRIORITY

    @classmethod
    def can_handle_url(cls, url):
        m = cls._url_re.match(url)
        if m:
            url_path = urlparse(m.group(2)).path
            return m.group(1) is not None or url_path.endswith(".m3u8")

    def _get_streams(self):
        url, params = parse_params(self.url)
        response = requests.get(url)
        jsonData = response.json()
        Token = jsonData['token']
        M3URL = jsonData['url']
        self.session.http.headers.update({"User-Agent": USER_AGENT})
        self.session.http.cookies.update({"MTVA_overload_alert":"false","MtvaArchivumToken": Token,})
        self.session.http.verify = False
        streams = HLSStream.parse_variant_playlist(self.session, M3URL)
        return streams

__plugin__ = MTVAPlugin

`
here is a direct link to it:
https://www.dropbox.com/s/c3fptybwzhtwvtt/mtva.py

### Input URLs

https://archivum.mtva.hu/m3/stream?target=live

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
