### ISSUE TITLE
MafiaTV / mafiatv.co.kr

### ISSUE THREAD

**Issue by chorong761** [streamlink/streamlink#4315]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

a livestream site similar to Twitch or afreecaTV, mainly for "just chatting" streams. Some streams require a log in due to minor protection laws (drinking, smoking etc.). 

### Input URLs

https://mafiatv.co.kr/live/506137
https://mafiatv.co.kr/live/391

**Comment by back-to** [comment]
barely reachable with a korean vpn,
not reachable without it.

Website is not really worth to be added.
