### ISSUE TITLE
Filter By Title or Output Only Title

### ISSUE THREAD

**Issue by MrTyton** [streamlink/streamlink#4318]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

The ability to either choose to download or not a live stream based on the title, either through a regex filter or through a way to echo only the stream title so that it can be processed by outside scripts.

Regex Filter:

`--output-title-regex=.*karaoke.*`

```
streamlink https://youtube.com/../live --output-title-regex=.*karaoke.*  --default-stream=best --output="{author}/{title}-{id}-{time}.mkv"
```

when the `{title}` contains karaoke, then it records it, otherwise it just returns.

Echo only stream title:

`--output-stream-title`

Echos to stdout what the stream title is. This would let outside scripts use streamlinks to determine whether or not to download the stream.

This would make it a lot easier to download only certain kinds of streams as wanted, rather than blanket downloading everything and cleaning up afterwards. I read through all the documentation several times, and I don't see anything that fits either of these two scenarios, but if I missed them then sorry.

**Comment by mkbloke** [comment]
You can kind of do this already:
```
$ streamlink --json 'https://www.youtube.com/watch?v=UQ3K0suY1Dc' | grep '"title":'
    "title": "Exploring wireless LEDs with schematic and waveforms"

$ streamlink --json 'https://www.youtube.com/watch?v=UQ3K0suY1Dc' | perl -ne '/^.*"title": "(.*)"/ and print "$1\n"'
Exploring wireless LEDs with schematic and waveforms

$ streamlink --json 'https://www.youtube.com/watch?v=UQ3K0suY1Dc' | perl -ne '/^.*"title": "(.*)"/ and print "$1\n"' | grep -q LEDs && echo "I want this video"
I want this video
```

**Comment by mkbloke** [comment]
Here's a wrapper script that does a case-insensitive title search and downloads upon a successful match to a path/file specification as you used above:

```
$ cat sl-title-search-and-dl 
#!/bin/bash

if [ -z "$2" ]
then
  echo "Usage: $(basename $0) <URL> <regex>"
  exit 1
fi

streamlink --json "$1" | \
  perl -ne '/^.*"title": "(.*)"/ and print "$1\n"' | \
  grep -qiE "$2" && \
  streamlink --output='{author}/{title}-{id}-{time}.mkv' "$1" best

$ ./sl-title-search-and-dl 
Usage: sl-title-search-and-dl <URL> <regex>

$ ./sl-title-search-and-dl 'https://www.youtube.com/watch?v=UQ3K0suY1Dc' 'led.*schem'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=UQ3K0suY1Dc
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (muxed-stream)
[utils.named_pipe][info] Creating pipe streamlinkpipe-770627-1-8012
[utils.named_pipe][info] Creating pipe streamlinkpipe-770627-2-719
[download][..2022-01-30_00-33-16.mkv] Written 624.0 KB (4s @ 146.5 KB/s)        ^C[stream.ffmpegmux][error] Pipe copy aborted: /tmp/streamlinkpipe-770627-2-719
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...

$ ls bigclivedotcom/
Exploring wireless LEDs with schematic and waveforms-UQ3K0suY1Dc-2022-01-30_00-33-16.mkv

$ ./sl-title-search-and-dl 'https://www.youtube.com/watch?v=UQ3K0suY1Dc' 'led.*schematics'
$ 
```

**Comment by MrTyton** [comment]
Thanks a lot - that will work for my use case. I'm ok with closing this, but I still sorta feel like this functionality could be built in so that a wrapper like this isn't required.

**Comment by mkbloke** [comment]
Yes, it crossed my mind that while this works, it's not a cross-platform solution.  Although I'm sure an equivalent could be written to do a similar thing via PowerShell for Windows users, that's not necessarily ideal.

Perhaps leave this open and let the maintainers decide whether or not it's worth keeping open as a feature request that could be implemented directly within Streamlink at some point in the future.

**Comment by bastimeyer** [comment]
Here's a very simple solution for your usecase, using only `bash` and `jq`.
https://stedolan.github.io/jq/manual/#RegularexpressionsPCRE

```sh
#!/usr/bin/env bash
set -e
streamlink --json "$URL" \
  | jq -e ".metadata.title | test(\"$REGEX\")" >/dev/null \
  && streamlink "$URL" "$QUALITY"
```

----

Adding a CLI parameter for that doesn't make sense, as Streamlink is not a tool for querying and filtering metadata.

This is an arbitrary filter for a very specific thing. If we add a regex filter like this, then the next request will be for a different stream metadata attribute or maybe something else. And the next request after that will be filters for whole string comparisons, substrings, time/date comparisons, numeric comparisons, or whatever. Maybe also for adding a whole query language that can do all that. I hope you get the point.
