### ISSUE TITLE
--twitch-disable-hosting breaks VOD playback

### ISSUE THREAD

**Issue by GreyAsteroid** [streamlink/streamlink#432]
Using --twitch-disable-hosting while someone is hosting another channel causes VOD playback to break for all their VODs.

```
streamlink https://www.twitch.tv/talutha/v/114091621
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/talutha/v/114091621
[plugin.twitch][debug] Getting video HLS streams for talutha
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as GreyAsteroid
[plugin.twitch][info] talutha is hosting bwana
[plugin.twitch][info] hosting was disabled by command line option
error: No streams found on this URL: https://www.twitch.tv/talutha/v/114091621
```

**Comment by GreyAsteroid** [comment]
On another note, even after enabling hosting, streamlink seems confused and spouts out this

```
[plugin.twitch][info] cryaotic is hosting effinslowbeef
[plugin.twitch][info] switching to effinslowbeef
[plugin.twitch][debug] Getting video HLS streams for effinslowbeef
```
Then proceeds to play the VOD from the original streamer

**Comment by gravyboat** [comment]
That's odd, when I do that I get this:
```
streamlink twitch.tv/cryaotic best
[cli][info] Found matching plugin twitch for URL twitch.tv/cryaotic
[plugin.twitch][info] cryaotic is hosting effinslowbeef
[plugin.twitch][info] switching to effinslowbeef
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /usr/bin/vlc
```

For your original issue I get this:
```
 streamlink https://www.twitch.tv/talutha/v/114091621 best
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/talutha/v/114091621
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /usr/bin/vlc
```
Though that may be because the user isn't hosting. What does the command you're running for the second comment look like, and what version of Streamlink are you running? Do you have any custom configuration set?

**Comment by GreyAsteroid** [comment]
The context of my second comment is
```
streamlink twitch.tv/cryaotic/v/114852831 best
[cli][info] Found matching plugin twitch for URL twitch.tv/cryaotic/v/114852831
[plugin.twitch][info] cryaotic is hosting effinslowbeef
[plugin.twitch][info] switching to effinslowbeef
```
The weird thing being that "switching to effinslowbeef" shouldn't show up since this command is for playing a VOD (and the VOD does play).

Regarding the original issue, as I said on the first comment, the --twitch-disable-hosting command only breaks VODs when the person who's VOD you're trying to play is hosting another person. So yes you did not actually trigger this issue.

I'm using 0.2.0 and I'm able to reproduce this issue with no custom config set.

**Comment by gravyboat** [comment]
Thanks for the additional details @GreyAsteroid. Closing this since #435 was merged. Can you try out the nightly once it builds?
