### ISSUE TITLE
plugins.pluzz : Allow Beijing 2022 streams

### ISSUE THREAD

**Issue by BZHDeveloper** [streamlink/streamlink#4325]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Plugin is unable to retrieve streams from webpage

steps : 

- get the live link : https://www.france.tv/beijing-h24/direct.html
- launch `streamlink "https://www.france.tv/beijing-h24/direct.html"`

### Debug log

```text
[cli][debug] OS:         Linux-5.17.0-051700rc2-lowlatency-x86_64-with-glibc2.34
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.1)
[cli][debug] Arguments:
[cli][debug]  url=https://www.france.tv/beijing-h24/direct.html
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/beijing-h24/direct.html
[plugins.pluzz][debug] Country: FR
[plugins.pluzz][debug] Video ID: 35cdf7ed-f565-40b6-b2a7-256e1ad17965
error: Unable to validate response text: Unable to validate key 'video': Unable to validate key 'workflow': 'dai' does not equal 'token-akamai'
```

**Comment by bastimeyer** [comment]
See #4326
