### ISSUE TITLE
plugins.plugin-name-here: plugins.easyview: Not working

### ISSUE THREAD

**Issue by juri-zaitsev** [streamlink/streamlink#4340]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

streamlink --http-header "Referer=https://easyview.eu/watch.php?stream=gold" "https://uk.easyview.eu/hls/gold.m3u8" best

Not working anymore...

With streamlink -v --http-header "Referer=https://easyview.eu/" "https://hd.easyview.eu/secure/itv3.m3u8" best
error: Unable to open URL: https://hd.easyview.eu/secure/itv3.m3u8 (403 Client Error: Forbidden for url: https://hd.easyview.eu/secure/itv3.m3u8)

### Debug log

```text
error: Unable to open URL: https://hd.easyview.eu/secure/itv3.m3u8 (403 Client Error: Forbidden for url: https://hd.easyview.eu/secure/itv3.m3u8)
```

**Comment by bastimeyer** [comment]
This is not a plugin issue and not a Streamlink issue. You simply don't have access to the HLS playlist anymore, as the error message clearly indicates (error 403). You'll have to add the right headers, parameters, cookies, etc.
