### ISSUE TITLE
Download a stream from twitch by User ID

### ISSUE THREAD

**Issue by smthjhn** [streamlink/streamlink#4353]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I am running streamlink in an infinite loop so I won't miss a stream but sometimes the channel that I am checking changes their twitch username which will make the loop useless. Since user id is unique it would be nice to be able to use it instead of twitch usernames.

**Comment by bastimeyer** [comment]
Use the Twitch API to get the user name by ID.
https://dev.twitch.tv/docs/api/reference#get-users
