### ISSUE TITLE
niconico channel Plus

### ISSUE THREAD

**Issue by railannad** [streamlink/streamlink#4366]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Streamlink is a powerful and convenient soft and thanks for all developers.

From Friday, January 7, 2022, niconico will start test operation of Niconico Channel Plus, a new feature of Niconico Channel, on some channels.
And I think more owner of channel will use niconico channel Plus. So I hope developers can strengthen the plugin "niconico" so that it can get stream from niconico channel Plus.
Please visit the source page `https://blog.nicovideo.jp/niconews/162058.html` for more information.

### Input URLs

https://nicochannel.jp/olchannel/video/smq9UriUQ9PU65jTjVxh2PVo

**Comment by Trung0246** [comment]
Looks like we need to make `POST` to `https://nicochannel.jp/olchannel/video/smq9UriUQ9PU65jTjVxh2PVo/session_ids`:
```bash
curl 'https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo/session_ids' -X 'POST' --compressed
```
then get `session_id`:
```json
{"data":{"session_id":"daf74c05-8162-45a2-ab55-ee4d5ff3d23b"}}
```

From there we can make `GET` request to `https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo`:
```bash
curl 'https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo' --compressed
```
and grab `data.video_page.video_stream.authenticated_url`:
```json
{
    "data": {
        "video_page": {
            "active_video_filename": {
                "id": 2074,
                "length": 3036,
                "video_filename_type": {
                    "id": 3,
                    "value": "archived"
                }
            },
            "closed_at": null,
            "content_code": "smq9UriUQ9PU65jTjVxh2PVo",
            "description": "今日はメイド物です。\nしっかりご奉仕させていただきます。",
            "disp_number_of_play_flg": null,
            "fanclub_site": {
                "fanclub_banners": [],
                "fanclub_personal_info_policy": {
                    "nickname_display_setting": false
                },
                "id": 21
            },
            "has_archived_files": true,
            "is_test_broadcast": false,
            "live_auto_release_flg": false,
            "live_finished_at": "2022-02-25 15:19:39",
            "live_scheduled_end_at": "2022-02-25 16:00:00",
            "live_scheduled_start_at": "2022-02-25 14:30:00",
            "live_started_at": "2022-02-25 14:29:03",
            "released_at": "2022-02-25 09:08:57",
            "start_with_free_part_flg": true,
            "thumbnail_url": "https://nicochannel.jp/public_html/contents/video_pages/1511/thumbnail_path",
            "title": "【耳舐め】貴方専属の耳舐めメイド",
            "type": "vod",
            "video": {
                "allow_dvr_flg": true,
                "archive_existence_flag": true,
                "convert_to_vod_flg": true,
                "default_started_at": null,
                "id": 1501,
                "video_output_audio_bit_rate": {
                    "display_name": "128Kbps（推奨）",
                    "id": 1
                },
                "video_output_frame_rate": {
                    "display_name": "30fps（推奨）",
                    "id": 1
                },
                "video_output_resolution": {
                    "display_name": "1080p(推奨)",
                    "id": 1
                }
            },
            "video_aggregate_info": {
                "id": 600935,
                "number_of_comments": 494,
                "total_views": 3061
            },
            "video_comment_setting": {
                "accept_before_broadcasting_flg": true,
                "allow_comment_flg": true,
                "comment_group_id": "bce245c0-95a9-11ec-ab4f-9d1e1650ecaf",
                "disp_main_comment_flg": true,
                "disp_number_of_comment_flg": true,
                "disp_number_of_views_flg": true,
                "disp_rightside_comment_flg": true,
                "id": 1115,
                "video_page": {
                    "id": 1511
                }
            },
            "video_custom_targets": [],
            "video_delivery_target": {
                "display_name": "会員限定",
                "id": 1
            },
            "video_filename_transcoded_first": {
                "file_size_bytes": 1998402689,
                "id": 2075,
                "length": 3036
            },
            "video_free_periods": [{
                "elapsed_ended_time": 1932452,
                "elapsed_started_time": 0,
                "end_at": "2022-02-25 15:01:15",
                "id": 635,
                "started_at": "2022-02-25 14:29:03"
            }],
            "video_page_public_status": {
                "display_name": "公開",
                "id": 2
            },
            "video_page_stream_key": {
                "video_live_info": {
                    "player_url_abr": "https://23f747dafc91c8abb92042cbbab21d47.cdnext.stream.ne.jp/abr/wlives-masterplaylist/d08km41ykw7mg1lp/master.m3u8",
                    "player_url_abr_dvr": "https://23f747dafc91c8abb92042cbbab21d47.cdnext.stream.ne.jp/abr/wlives-masterplaylist/d08km41ykw7mg1lp/master_DVR.m3u8"
                }
            },
            "video_questionnaires": [],
            "video_stream": {
                "authenticated_url": "https://hls-auth.cloud.stream.co.jp/auth/index.m3u8?session_id={session_id}"
            },
            "video_tags": [{
                "id": 4355,
                "tag": "#耳舐め"
            }, {
                "id": 4356,
                "tag": "OLCHANNEL"
            }, {
                "id": 4357,
                "tag": "浅瀬ゆうぎ"
            }, {
                "id": 4358,
                "tag": "シチュエーション"
            }, {
                "id": 4359,
                "tag": "バイノーラル"
            }]
        }
    }
}
```
For auth-ed stream I don't know if the login flow is the same as `nicovideo` plugin.

**Comment by railannad** [comment]
> Looks like we need to make `POST` to `https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo/session_ids`:
> 
> ```shell
> curl 'https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo/session_ids' -X 'POST' --compressed
> ```
> 
> then get `session_id`:
> 
> ```json
> {"data":{"session_id":"daf74c05-8162-45a2-ab55-ee4d5ff3d23b"}}
> ```
> 
> From there we can make `GET` request to `https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo`:
> 
> ```shell
> curl 'https://nfc-api.nicochannel.jp/fc/video_pages/smq9UriUQ9PU65jTjVxh2PVo' --compressed
> ```
> 
> and grab `data.video_page.video_stream.authenticated_url`:
> 
> ```json
> {
>     "data": {
>         "video_page": {
>             "active_video_filename": {
>                 "id": 2074,
>                 "length": 3036,
>                 "video_filename_type": {
>                     "id": 3,
>                     "value": "archived"
>                 }
>             },
>             "closed_at": null,
>             "content_code": "smq9UriUQ9PU65jTjVxh2PVo",
>             "description": "今日はメイド物です。\nしっかりご奉仕させていただきます。",
>             "disp_number_of_play_flg": null,
>             "fanclub_site": {
>                 "fanclub_banners": [],
>                 "fanclub_personal_info_policy": {
>                     "nickname_display_setting": false
>                 },
>                 "id": 21
>             },
>             "has_archived_files": true,
>             "is_test_broadcast": false,
>             "live_auto_release_flg": false,
>             "live_finished_at": "2022-02-25 15:19:39",
>             "live_scheduled_end_at": "2022-02-25 16:00:00",
>             "live_scheduled_start_at": "2022-02-25 14:30:00",
>             "live_started_at": "2022-02-25 14:29:03",
>             "released_at": "2022-02-25 09:08:57",
>             "start_with_free_part_flg": true,
>             "thumbnail_url": "https://nicochannel.jp/public_html/contents/video_pages/1511/thumbnail_path",
>             "title": "【耳舐め】貴方専属の耳舐めメイド",
>             "type": "vod",
>             "video": {
>                 "allow_dvr_flg": true,
>                 "archive_existence_flag": true,
>                 "convert_to_vod_flg": true,
>                 "default_started_at": null,
>                 "id": 1501,
>                 "video_output_audio_bit_rate": {
>                     "display_name": "128Kbps（推奨）",
>                     "id": 1
>                 },
>                 "video_output_frame_rate": {
>                     "display_name": "30fps（推奨）",
>                     "id": 1
>                 },
>                 "video_output_resolution": {
>                     "display_name": "1080p(推奨)",
>                     "id": 1
>                 }
>             },
>             "video_aggregate_info": {
>                 "id": 600935,
>                 "number_of_comments": 494,
>                 "total_views": 3061
>             },
>             "video_comment_setting": {
>                 "accept_before_broadcasting_flg": true,
>                 "allow_comment_flg": true,
>                 "comment_group_id": "bce245c0-95a9-11ec-ab4f-9d1e1650ecaf",
>                 "disp_main_comment_flg": true,
>                 "disp_number_of_comment_flg": true,
>                 "disp_number_of_views_flg": true,
>                 "disp_rightside_comment_flg": true,
>                 "id": 1115,
>                 "video_page": {
>                     "id": 1511
>                 }
>             },
>             "video_custom_targets": [],
>             "video_delivery_target": {
>                 "display_name": "会員限定",
>                 "id": 1
>             },
>             "video_filename_transcoded_first": {
>                 "file_size_bytes": 1998402689,
>                 "id": 2075,
>                 "length": 3036
>             },
>             "video_free_periods": [{
>                 "elapsed_ended_time": 1932452,
>                 "elapsed_started_time": 0,
>                 "end_at": "2022-02-25 15:01:15",
>                 "id": 635,
>                 "started_at": "2022-02-25 14:29:03"
>             }],
>             "video_page_public_status": {
>                 "display_name": "公開",
>                 "id": 2
>             },
>             "video_page_stream_key": {
>                 "video_live_info": {
>                     "player_url_abr": "https://23f747dafc91c8abb92042cbbab21d47.cdnext.stream.ne.jp/abr/wlives-masterplaylist/d08km41ykw7mg1lp/master.m3u8",
>                     "player_url_abr_dvr": "https://23f747dafc91c8abb92042cbbab21d47.cdnext.stream.ne.jp/abr/wlives-masterplaylist/d08km41ykw7mg1lp/master_DVR.m3u8"
>                 }
>             },
>             "video_questionnaires": [],
>             "video_stream": {
>                 "authenticated_url": "https://hls-auth.cloud.stream.co.jp/auth/index.m3u8?session_id={session_id}"
>             },
>             "video_tags": [{
>                 "id": 4355,
>                 "tag": "#耳舐め"
>             }, {
>                 "id": 4356,
>                 "tag": "OLCHANNEL"
>             }, {
>                 "id": 4357,
>                 "tag": "浅瀬ゆうぎ"
>             }, {
>                 "id": 4358,
>                 "tag": "シチュエーション"
>             }, {
>                 "id": 4359,
>                 "tag": "バイノーラル"
>             }]
>         }
>     }
> }
> ```
> 
> But all of these is just preview, not the full content (based on what google translate told me). And since full video requires login, I don't know if the login flow is the same as `nicovideo` plugin.

Hi bro, thank you for you effort . I can not understand the code.  And I guess you need a account that joined the member,right?
Leave you email address , I will join the member and share my account with you .
