### ISSUE TITLE
https://www.cmmedia.es/en-directo/tv / https://klive.kaltura.com

### ISSUE THREAD

**Issue by nickiman** [streamlink/streamlink#4370]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi,
This is a plugin development request to include CMM Media in Streamlink. 
CMM Media is a TV Broadcaster of [Castilla La Mancha](url=https://en.wikipedia.org/wiki/Castilla%E2%80%93La_Mancha) region, in Spain.
Is run under the gobernment of the of Castilla La Mancha.
The content provided are basically news, documentaries and special programs from that region of Spain

### Input URLs

Information obtained from VideoDownload Helper:

**masterManifest:**
https://klive.kaltura.com/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8?__hdnea__=st=1646058301~exp=1646144701~acl=/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8*~hmac=3f226bcf7b99800114dff69ce810b3e3b0f36873eaf3503216917d6ba83f23c6

mediaManifest:
https://klive.kaltura.com/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8?__hdnea__=st=1646058301~exp=1646144701~acl=/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8*~hmac=3f226bcf7b99800114dff69ce810b3e3b0f36873eaf3503216917d6ba83f23c6

topUrl:
https://www.cmmedia.es/en-directo/tv/

url:
https://klive.kaltura.com/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8?__hdnea__=st=1646058301~exp=1646144701~acl=/s/env/cluster-1-b.live.nvp1/live/hls/p/2288691/e/0_xs45iy5i/tl/main/st/0/t/DznN37GHRy-bwqducFv4Xw/index-s32.m3u8*~hmac=3f226bcf7b99800114dff69ce810b3e3b0f36873eaf3503216917d6ba83f23c6

If you need anything else, just let me know.

**Comment by mkbloke** [comment]
What's the deal with adding TV channels now?  Since  #4344 was merged I'm a bit confused as to what the current situation is.  Can somebody say yes or no for this, please?
