### ISSUE TITLE
plugins.youtube: 1440p live stream not available in HLS format

### ISSUE THREAD

**Issue by kasper93** [streamlink/streamlink#4376]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Hi,

Since this commit https://github.com/streamlink/streamlink/commit/fe00d74201465cb97785b1b0a0e61efa7fd05cbd adaptive streams are excluded for youtube live streams. The problem is that HLS doesn't expose 1440p stream (there is only VP9 stream that's why), which is available as id `271`. I made the change to use muxed stream for live, but it is stuttering, so I guess there is needed more changes to make it work properly.

You can test that with any 1440p stream, just search "1440p live" on youtube.

Best Regards,
Kacper

**Comment by gravyboat** [comment]
1440p videos/streams on youtube don't work because of DASH, take a look at https://github.com/streamlink/streamlink/issues/2936. Closing this as a duplicate.
