### ISSUE TITLE
Youtube VODs stutters

### ISSUE THREAD

**Issue by RasmusJohns** [streamlink/streamlink#4378]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Somewhat recently, using Streamlink on high quality VODs from Youtube started causing stuttering. 

Streaming YT VODs with 144p works fine, whereas 1080p60 halts to almost a standstill. I have tried this from multiple computers and connections, using both VLC and mpv. I have also tried setting high network and file caches without any success.

Twitch VODs seem to be unaffected by this issue.

Is there something I can do to improve my performance, is it a limitation introduced by YT, or is it a bug in the YT plugin?

### Debug log

```text
streamlink --loglevel debug "https://www.youtube.com/watch?v=NVwEQYmy_RA" 1080p60
[cli][debug] OS:         macOS 10.15.5
[cli][debug] Python:     3.10.2
[cli][debug] Streamlink: 3.1.1
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=NVwEQYmy_RA
[cli][debug]  stream=['1080p60']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=NVwEQYmy_RA
[plugins.youtube][debug] Using video ID: NVwEQYmy_RA
[plugins.youtube][debug] MuxedStream: v 299 a 251 = 1080p60
[plugins.youtube][debug] MuxedStream: v 302 a 251 = 720p60
[plugins.youtube][debug] MuxedStream: v 135 a 251 = 480p
[plugins.youtube][debug] MuxedStream: v 133 a 251 = 240p
[plugins.youtube][debug] MuxedStream: v 160 a 251 = 144p
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 240p, 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (muxed-stream)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.ffmpegmux][debug] Opening http substream
[stream.ffmpegmux][debug] Opening http substream
[utils.named_pipe][info] Creating pipe streamlinkpipe-11921-1-4132
[utils.named_pipe][info] Creating pipe streamlinkpipe-11921-2-4843
[stream.ffmpegmux][debug] ffmpeg command: ffmpeg -nostats -y -i /var/folders/rt/87k0mcl973ggsl52c2wx1dsh0000gn/T/streamlinkpipe-11921-1-4132 -i /var/folders/rt/87k0mcl973ggsl52c2wx1dsh0000gn/T/streamlinkpipe-11921-2-4843 -c:v copy -c:a copy -map 0 -map 1 -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/rt/87k0mcl973ggsl52c2wx1dsh0000gn/T/streamlinkpipe-11921-1-4132
[stream.ffmpegmux][debug] Starting copy to pipe: /var/folders/rt/87k0mcl973ggsl52c2wx1dsh0000gn/T/streamlinkpipe-11921-2-4843
[cli][debug] Pre-buffering 8192 bytes
[cli.output][debug] Opening subprocess: /Applications/VLC.app/Contents/MacOS/VLC --input-title-format https://www.youtube.com/watch?v=NVwEQYmy_RA -
[cli][debug] Writing stream to output
```

**Comment by bastimeyer** [comment]
This is a limitation introduced by YouTube. If you take a look at [the adaptive stream URLs which the plugin resolves](https://github.com/streamlink/streamlink/blob/3.1.1/src/streamlink/plugins/youtube.py#L361) and then muxes together into video+audio streams, the 1080p60 video stream (at least) downloads at a speed of **67741 bytes per second**, which is nowhere near enough bandwidth.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 2622M    0 5855k    0     0  67741      0 11:16:34  0:01:28 11:15:06 65667
```

Youtube has already limited download speeds via youtube-dl a long time ago, so it's very likely that this is affecting Streamlink as well now.

There have already been discussions years ago here that YouTube is aggressively trying to detect tools like Streamlink by checking whether regular website assets which the web browser loads also get loaded, among other stuff. Replicating an exact web browser behavior is however almost impossible.

**Comment by RasmusJohns** [comment]
Thanks, that's what I suspected.

**Comment by kasper93** [comment]
@RasmusJohns If you want to try alternative https://github.com/jmf1988/ytdash it is working pretty good for adaptive formats.

**Comment by kasper93** [comment]
> There have already been discussions years ago here that YouTube is aggressively trying to detect tools like Streamlink by checking whether regular website assets which the web browser loads also get loaded, among other stuff. Replicating an exact web browser behavior is however almost impossible.

@bastimeyer Any proof of that? There are way better way to identify API user. Fiddling with asset loading and tracking that where those are delivered by different servers, often not related at all with each other seems very unlikely. I mean they would make it unnecessary complex and hard to maintain having to synchronize various endpoints... Anyway, sure they are rate limiting external tools, but what I'm saying the means how they do that are mostly in their player code, with additional requests, signatures, what not. 

For example 
* youtube-dl recently fixed it by generating `n` parameter same as web player does https://github.com/ytdl-org/youtube-dl/commit/af9e72507ea38e5ab3fa2751ed09ec88021260cb
* yt-dlp on the other hand is emulating the android client https://github.com/yt-dlp/yt-dlp/pull/492 which also fixed the throttling

> Replicating an exact web browser behavior is however almost impossible.

Tedious maybe, but impossible is a stretch.

**Comment by bastimeyer** [comment]
> Any proof of that? There are way better way to identify API user. Fiddling with asset loading and tracking that where those are delivered by different servers, often not related at all with each other seems very unlikely. I mean they would make it unnecessary complex and hard to maintain having to synchronize various endpoints...

I wasn't making any claims so I can't and don't have to prove it. I was merely referring to an old discussion. I've argued the same way when this came up and I don't believe it either that YT is doing something like that, but it's a possibility, considering it's Google.

> Tedious to keep it updates, maybe, but impossible is a stretch.
> very easy bypassed

You'd either have to replicate the exact behavior of YouTube's web client, which can change at any time and as you've said would be very tedious to keep updated, or it would require a fully fledged web browser environment which also executes JS, which would be ridiculous considering it could run arbitrary code. It is thus not very easily bypassed.

> youtube-dl recently fixed it by generating n parameter same as web player does

If there is a workaround that can yield adaptive stream URLs that are not rate limited, then please submit a pull request.

**Comment by kasper93** [comment]
> It is thus not very easily bypassed.

I was referring only to "asset loading" part.  The rest of course is time consuming to reverse engineer and replicate. And as you said the main problem is that is can change anytime rendering all the previous work void...

**Comment by kasper93** [comment]
> If there is a workaround that can yield adaptive stream URLs that are not rate limited, then please submit a pull request.

@bastimeyer: Ok, but before I spent my time on that. Are you ok with interpreting JS or at least limited pattern matching of transform functions to decrypt n signature? Basically we need to decrypt n parameter, else it we will be rate limited. It is actually well documented if you read through comments... 

Here is background with explanation of one of the versions: 
https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-894619419

Here is example of standalone decipher code. We could take it as is, it is pretty nice and they have permissive license :)
https://github.com/pytube/pytube/blob/master/pytube/cipher.py

youtube-dl and yt-dlp guys have full fledged JS interpreter, so they just feed the function code there.
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/jsinterp.py

Alternative is to try shuffling other client versions and find one that is not throttled atm (if any). But I'm not interested in that (someone else could di it of course), I think WEB client should be used as base...

**Comment by bastimeyer** [comment]
> Are you ok with interpreting JS

There have been discussions about adding a JS **parser** for building an AST and reading data from it in #2534, but all the relevant Python projects seem to be unmaintained / dead. That was mainly meant for replacing wonky regexes though that are/were used to extract content from web pages, but parsers are not a solution for code that can't be statically analyzed like the one here.

> YouTube's strategy to restrict downloading videos is to send a ciphered version
> of the signature to the client, along with the decryption algorithm obfuscated
> in JavaScript. For the clients to play the videos, JavaScript must take the
> ciphered version, cycle it through a series of "transform functions," and then
> signs the media URL with the output.

Adding custom interpreting solutions (on top of custom parsing solutions) that implement a subset of JS statements, arithmetic and string/array methods like the ones linked above are very much **unmaintainable** and absolutely ridiculous. One change by YouTube and the entire thing can/will break. Then figuring out what's broken, fixing it and writing tests would be a nightmare. And once the person who's implemented it is gone or has become inactive, nobody else will feel responsible for that messy code.

Apart from that, if a single plugin requires that much extra code for an abstract or generic problem, then it's probably the best to have it implemented in an external dependency and not in the project itself.

**Comment by kasper93** [comment]
While I agree, I find your answer interesting, given the context of the project.

> Adding custom interpreting solutions (on top of custom parsing solutions) that implement a subset of JS statements, arithmetic and string/array methods like the ones linked above are very much unmaintainable and absolutely ridiculous. One change by YouTube and the entire thing can/will break.

Of course. But you can say the very same thing about ever other plugin that doesn't use stable public API. Every little change to specific area of the site can/will break a plugin (remember those messy regexes or magic params hardcoded in plugins?). And the only difference is that most plugins are trivial to write/rewrite, hence they are sort of maintainable, but not for the reasons that we would like...

> Apart from that, if a single plugin requires that much extra code for an abstract or generic problem, then it's probably the best to have it implemented in an external dependency and not in the project itself.

This is little vague. What do you mean by "problem"? The problem is that the youtube plugin is not working or at least not what one would expect from streamlink. The `n` parameter issue is only one on multiple shortcomings that the current plugin has.

Anyway I replaced whole extraction code with [pytube](https://github.com/pytube/pytube) locally. Because frankly what I want to fix is live adaptive playback, but well the throttling issue is blocking.
