### ISSUE TITLE
"zattoo"plugins don t work

### ISSUE THREAD

**Issue by qwe199** [streamlink/streamlink#4382]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

This is what I typed

streamlink --zattoo-email=xxxxx@snapmail.cc --zattoo-password=xxxxx --http-proxy "socks5h://127.0.0.1:7890" https://zattoo.com/settings?channel=rai-uno

### Debug log

```text
I've made sure the site is working

He just gave the output：

error: No plugin can handle URL: https://zattoo.com/settings?channel=rai-uno
```

**Comment by bastimeyer** [comment]
> https://zattoo.com/settings?channel=rai-uno

Not a valid canonical URL recognized by the plugin, as you can see here
https://github.com/streamlink/streamlink/blob/3.1.1/src/streamlink/plugins/zattoo.py#L40-L42

zattoo.com URLs have to be in the format

- `zattoo.com/live/CHANNELNAME`
- `zattoo.com/watch/CHANNELNAME`
- `zattoo.com/channels?channel=CHANNELNAME`
- `zattoo.com/channels/TAGNAME?channel=CHANNELNAME`
- `zattoo.com/guide?channel=CHANNELNAME`

```
$ streamlink 'https://zattoo.com/live/rai-uno'
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/live/rai-uno
```

**Comment by qwe199** [comment]
`streamlink --zattoo-email=zattoo6@snapmail.cc --zattoo-password=786374648 --http-proxy "socks5h://127.0.0.1:7890" httpstream://https://zattoo.com/watch/rai-uno best `

仍然无法播放，这是输出

`[cli][info] Found matching plugin http for URL httpstream://https://zattoo.com/watch/rai-uno
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: "C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe"
[cli][info] Stream ended
[cli][info] Closing currently open stream...`

**Comment by qwe199** [comment]
`streamlink --zattoo-email=xxxxx@xxxx.cc --zattoo-password=xxxx --http-proxy "socks5h://127.0.0.1:7890" httpstream://https://zattoo.com/watch/rai-uno best`

This is the output, he recognizes it but can't play it

[cli][info] Found matching plugin http for URL httpstream://https://zattoo.com/watch/rai-uno
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (http)
[cli][info] Starting player: "C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe"
[cli][info] Stream ended
[cli][info] Closing currently open stream...
