### ISSUE TITLE
plugins: add missing "description" metadata tags

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4383]
Plugin metadata comments/tags were added via #4374 in favor of having a static plugin list/table in the docs (see #4369).
- https://streamlink.github.io/plugins.html
- https://streamlink.github.io/developing.html#plugins

The old plugin matrix didn't include any plugin descriptions due to space constraints of the table layout, and #4374 didn't add the missing metadata, because it would've delayed the implementation by a lot.

The `description` tag is therefore currently not marked as a requirement, but the goal is to have every existing plugin properly tagged with a short description text, so the tag can be made a requirement for successful builds eventually. New plugins should always include this tag and existing ones should get updated bit by bit.

As already mentioned in #4374, a couple of plugin descriptions can be found in the git history of the individual plugin files, because some old comments with descriptions were removed in the past for consistency reasons while refactoring code or while removing deprecated stuff. Other plugin descriptions can be found on the issue tracker in plugin request threads, but the rest will need to be looked up / researched.

There are about 150 built-in plugins, so if anyone feels like making a contribution by adding some of the missing metadata, please open a pull request. Thanks.

**Comment by mkbloke** [comment]
I made a bit of a start on this yesterday, putting together a manually curated list of descriptions for various plugins.

The current linting maximum line length is set at 128 characters.  Is it possible to have multiple `$description` lines?
```
"""
$description Some content here.
$description More content here.
$url ...
$url ...
"""
```
Given that some plugins cover a number of distinct sites, describing them in no more than 115 characters could be tricky for those if `$description` can only appear once.

**Comment by bastimeyer** [comment]
> I made a bit of a start on this yesterday

Thanks.

> Given that some plugins cover a number of distinct sites, describing them in no more than 115 characters could be tricky

The description text should not cover and describe each site in detail if a plugin supports multiple sites. It should simply be a short note about the site / streaming service, like for example "Live streaming service for video games, esports, IRL, etc.", "German public service broadcaster", or whatnot.

> Is it possible to have multiple `$description` lines?

The metadata parser currently splits everything into separate lines before validating the format. This could be changed with an upgraded regex and `finditer`, but I don't think it's really necessary.

**Comment by mkbloke** [comment]
Let me see how it goes.  The only plugin that this has been a problem with so far has been the `cdnbg` plugin.  If it comes to it, I can go back to that and just squeeze something into the available space without having to make this change.

**Comment by back-to** [comment]
>  The only plugin that this has been a problem with so far has been the cdnbg plugin.

`CDN Video Streaming for Bulgarian TV`
something like this, don't make it complicated

**Comment by mkbloke** [comment]
> "German public service broadcaster", or whatnot.

Yeah, that's more or less what I'm doing and the above is along the lines of a common format I'm using for a few of the plugins.

> CDN Video Streaming for Bulgarian TV

That's pretty much what I think I'll end up having to do with it.  Originally, I thought about a terse description for each site or group of sites (that could be grouped) supported by that particular plugin.
