### ISSUE TITLE
mtva.hu m3 online

### ISSUE THREAD

**Issue by gabywap** [streamlink/streamlink#4385]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Can we request that the streamlink plugin be published mtva.hu m3 online as well? Unfortunately only this one source is online and enigma2 STB would be available. Thank You!

### Input URLs

https://archivum.mtva.hu/m3/embed

**Comment by bastimeyer** [comment]
> Widevine DRM content protection

```
$ streamlink 'dash://https://stream10.nava.hu/m3_live_bdrm/_definst_/smil:m3_1080p.smil/manifest.mpd?sessid=ewXJvYRqTBBCcsVs5z7h8a5g6NR2UBTPUeIbQfTANbui9rB77eDcqDTyMAHzCcrL&lb=8V%2FEMiiK6D3Fa8lwVy1KfdguuufFdUax5nTTIBg2s1%2BDsfi08x1GTMooYqf6AMkuNNMRpEh056v2%0D%0ANOXXuqsg8w%3D%3D%0D%0A&platform=web_embed' best
[cli][info] Found matching plugin dash for URL dash://https://stream10.nava.hu/m3_live_bdrm/_definst_/smil:m3_1080p.smil/manifest.mpd?sessid=ewXJvYRqTBBCcsVs5z7h8a5g6NR2UBTPUeIbQfTANbui9rB77eDcqDTyMAHzCcrL&lb=8V%2FEMiiK6D3Fa8lwVy1KfdguuufFdUax5nTTIBg2s1%2BDsfi08x1GTMooYqf6AMkuNNMRpEh056v2%0D%0ANOXXuqsg8w%3D%3D%0D%0A&platform=web_embed
error: https://stream10.nava.hu/m3_live_bdrm/_definst_/smil:m3_1080p.smil/manifest_w1657290792_qc2Vzc2lkPWV3WEp2WVJxVEJCQ2NzVnM1ejdoOGE1ZzZOUjJVQlRQVWVJYlFmVEFOYnVpOXJCNzdlRGNxRFR5TUFIekNjckwmbGI9OFYlMkZFTWlpSzZEM0ZhOGx3VnkxS2ZkZ3V1dWZGZFVheDVuVFRJQmcyczElMkJEc2ZpMDh4MUdUTW9vWXFmNkFNa3VOTk1ScEVoMDU2djIlMEQlMEFOT1hYdXFzZzh3JTNEJTNEJTBEJTBBJnBsYXRmb3JtPXdlYl9lbWJlZA==.mpd is protected by DRM
```
