### ISSUE TITLE
Re-add Latina.pe

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#4389]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Latina (formerly Frecuencia Latina) is a southamerican television network located in Peru.
The site switched back to footprint.net, opening the stream by just using the url isn't possible any longer. 
(probably geo-blocked to Peru). 

### Input URLs

latina.pe/tvenvivo

https://live-latina-mdstrm.secure.footprint.net/live-stream-dai/319fed2157fa4c48ae2f81928b21f8a4/manifest/f624fec49dadc88894ebeff1d974eab019af7757/5ce7109c7398b977dc0744cd/9ecdb01e-f8d0-42c0-8835-c8513c68574b/3.m3u8?aid=5ce70c587398b977dc0743b5&uid=2qdmtnyxqykgaq1bhsp6m1xljughmfmp&sid=aumr1eucaiuelbxyocsdah8axbysvga4&pid=rh5pcbnrqphhxs0t47orcnhmj6zwog8f&ref=https%3a%2f%2fwww.latina.pe%2f&without_cookies=false&dnt=true&es=live-latina-mdstrm.secure.footprint.net&proto=https&pz=us&access_token=nzvx5r0h5nfbfpmwdkld4p5cdulfgsf819yqu6donwkh68no9awt63irlslj0e2hwjobzuod2fr&manifestfilter=video_height:240-720&hash=0477df08cf37282c87750

**Comment by bastimeyer** [comment]
The plugin was just removed in December because it broke when the site switched to a different streaming provider. See #4269. And now they've switched to a different provider again. Adding plugins for sites which are unstable doesn't make much sense.

**Comment by malvinas2** [comment]
In general, I fully understand your concerns. 

But if I review the development history in the plugin mentioned, a first version was created in early 2020. 
A few minor adjustments followed, but they were more of a cosmetic nature.
All of this I would consider as one version.
The plugin was discontinued at the end of 2021 because the stream could now be extracted from the website without any tools. The effort to remove a plugin should be minimal.
So the current change would be the second in two years.
