### ISSUE TITLE
installer: move to separate repo, build multiple Python versions and archs

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4390]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I'm thinking about moving Streamlink's Windows installer to a different repo, similar to the Linux Appimages. Let's discuss this.

----

The installer has been built here in this repo ever since the Livestreamer fork, because Livestreamer's installer was built in its own repo as well (using different libs), and it was the easiest solution of quickly implementing it. Since Streamlink already included Windows RTMPdump binaries on the master branch (via Livestreamer) and no external streamlink-assets repo existed, the very unfortunate mistake was made of merging a ~54MiB FFmpeg binary into the master branch, so it could be included in the installer. I wish I would've seen the PR in time to prevent this, but that can't be changed anymore, and the file will be included in the repo forever. In order to clean it all up a bit and prevent future mistakes like this, we've added the streamlink-assets repo where those 3rd party binaries could be hosted and included when building the installer. Recently we've dropped RTMPdump and switched to self-built FFmpeg binaries, so the streamlink-assets repo became obsolete. As a consequence of the old build-simplifications, Streamlink's Windows installer was always limited to x86-only.

Streamlink's installer is built via pynsist, and it downloads pre-built "embeddable" binaries for Python which are pulled from python.org. The big issue with that is that Python versions which have entered the "security" maintenance cycle don't get published as binaries anymore by the Python devs and are only distributed as source files, which means Python 3.8, the last version that still supports Windows 7, can't be included here via pynsist unless we're using old Python releases and sacrifice the security and performance for everyone else. This has been causing lots of confusion for W7 users when they need to install Python 3.8 on their own, and Streamlink via pip in this extra python environment. Some users have also gotten a bit frustrated when we announced the switch to Python 3.9 and the end of support for W7 via Streamlink's installer in the 2.4.0 release. In addition to all of that, the chocolatey and win-get packages are based on the installer, which they simply extract the files from, so the limitation also applies here. For W7 users of Streamlink Twitch GUI who obviously also need to install Streamlink, this has already caused lots of headaches, because most of them are more "casual users" and don't know how command line shells work.

We haven't switched to Python 3.10 yet, as 3.9 is still in its "bugfix" cycle, so it still has binary releases on python.org. We'll have to upgrade soon though, as the final bugfix release of 3.9 will be 3.9.12, which will be in May this year. This won't cause any compatibility issues though.

----

Now to the reason why I want to discuss switching the build- and release-config of Streamlink's Windows installer. As said, there are some unnecessary limitations which are quite simple to resolve if we change how we build and deploy the installer.

CPython 3.8 is still maintained, so it can safely be built and included in the installer, similar to what we're already doing with FFmpeg, and so are x86_64 binaries. I have already [created a test repo for building multiple CPython releases](https://github.com/bastimeyer/python-windows-embed) (3.8 and 3.10) via GitHub actions, for both x86 and x86_64. The resulting file structure differs a bit and the binaries are obviously not signed by the Python devs, but that shouldn't be a problem. One issue I had was building 3rd party libs from source too. Since I haven't managed to fix the build errors with libffi, I did what the official releases are doing as well and included pre-built 3rd party libs (Tcl/Tk, OpenSSL and libffi) which are hosted in a repo on python's GitHub orga. This is all part of the regular CPython build process on Windows.

I haven't built an installer with these custom CPython releases yet, but I will do that over the next couple of days and see if there are any issues. Building x86_64 binaries for FFmpeg is just one small switch (plus a rebase to the latest version - 5.0).

So what I'd like to do is building four or maybe only three installers, x86 + x86_64 with Python 3.10, and x86 + optionally x86_64 with Python 3.8, in a custom repo. That would mean that the installers would not be deployed via GitHub releases here in this repo. Nightly builds would also be hosted there. These can be limited to only one flavor, though.

One benefit of moving the installer is that we can publish releases with upgraded dependencies, as those are pinpointed, without having to create a new Streamlink release. One recent example is the charset-normalizer dependency of python-requests, which caused issues when parsing HLS playlists without content-type HTTP headers. The AppImages could be upgraded immediately after the charset-normalizer fix, whereas the installer could not.

The only issues I see with this is the extra work and maintenance (not a big issue), potential problems with the included CPython builds, and the move to a different repo which will probably confuse users and will require chocolatey and win-get maintainers to update.

Thoughts?

**Comment by gravyboat** [comment]
I'm in favor of this. It makes a lot of sense to handle the build elsewhere and aside from the inconvenience to the chocolatey and win-get maintainers it doesn't seem as though there are any downsides.

**Comment by bastimeyer** [comment]
I've added a test repo for the new installer build config here:
https://github.com/bastimeyer/streamlink-windows-installer
https://github.com/bastimeyer/streamlink-windows-installer/commits/master

The builds can be tested by downloading them from the CI run artifacts. Please do that.
https://github.com/bastimeyer/streamlink-windows-installer/actions

Generating lockfile data for the various builds has been unnecessarily difficult because Streamlink doesn't have its own dependency lockfile (eg. via pipenv). The Streamlink AppImage config doesn't have this problem, because the dependencies can be gathered in a dedicated python environment in the docker containers. Generating lockfiles for different platforms is currently not supported by pip (version 22) and only proposals exist for adding `pip resolve` / `pip download --release --dry-run` commands that would generate lockfile data. The solution added here is very ugly and stupid, especially because of how pynsist's config works. This should be good enough for now, though.

Once everything has been tested and validated, I will move the repo and the [bastimeyer/python-windows-embed](https://github.com/bastimeyer/python-windows-embed) repo to the streamlink orga, or I will create new repos and push again. Until then, I will force push onto the master branch if I need to fix something, so the repos can have a clean commit history before going live.

I haven't written a readme yet and a release deploy config that publishes the installers to GitHub releases also still needs to be added, but that will be done as the last step.

Differences from the current installers:

- Custom python embeddable builds for Windows
  - unsigned binaries, so this might trigger "antivirus" snake oil programs
  - different file structure with subdirs for DLLs and for standard library
  - standard library is not packed as a zip archive anymore, but included as individual files with byte-compiled versions
- x86 and x86_64
  - this changes the install location from `C:\Program Files (x86)\` to `C:\Program Files\` on x86_64
- py310 and py38
  - installers don't include the MS Visual C++ Runtime anymore. This is not required on W10, but it might be on W7 / W8. I don't care though, and users can install it themselves.
    https://pynsist.readthedocs.io/en/latest/cfgfile.html#python-section

TODO:
- create x86 and x86_64 FFmpeg 5.0 builds and include them in the installers
- fix pynsist and the removed plugin files problem (see below)
- add readme
- add deploy config

----

Additional note:

I'll be submitting a PR to pynsist once I got a response from its maintainer which will finally properly fix #1223 and will thus make the removed-plugins-file at `src/streamlink/plugins/.removed` obsolete. The current version of the installer build script still writes empty plugin files for each item in this removed plugins list. Once pynsist releases a new version, this will be removed, and then we can remove it here as well.

**Comment by gravyboat** [comment]
> The builds can be tested by downloading them from the CI run artifacts. Please do that.

I ran through an install on my Windows 10 machine this morning and it was fine. As with all Streamlink installs it triggered the "are you sure you want to install this" warning, but it was easy to bypass like normal. No configuration issues or other problems, as expected the installer just worked.

**Comment by bastimeyer** [comment]
I've published FFmpeg 5.0 builds for x86 and x86_64 on [streamlink/FFmpeg-Builds](https://github.com/streamlink/FFmpeg-Builds) earlier today and just updated the config on [bastimeyer/streamlink-windows-installer](https://github.com/bastimeyer/streamlink-windows-installer).

I'm basically only waiting for the pynsist fix now:
https://github.com/takluyver/pynsist/pull/245

If there's no response or no new pynsist release in the next couple of days, I will set my fork's branch as a build dependency.
