### ISSUE TITLE
can't open/ video stop streaming when stream change to 19+ on AfreecaTV

### ISSUE THREAD

**Issue by RubyRudy** [streamlink/streamlink#4392]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

the stream just froze when the stream change to 19+.
can't open 19+ stream.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/xxx/xxx
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --afreeca-username=********
[cli][debug]  --afreeca-password=********
[plugins.afreeca][debug] Restored cookies: _au, PdboxBbs, PdboxSaveTicket, PdboxTicket, PdboxUser, RDB, isBbs
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/xxx/xxx
[plugins.afreeca][debug] Attempting to authenticate using cached cookies
[plugins.afreeca][error] Login required
error: No playable streams found on this URL: https://play.afreecatv.com/xxx/xxx
```

**Comment by back-to** [comment]
> [plugins.afreeca][error] Login required

reset your session, you are not logged in

https://streamlink.github.io/cli.html#cmdoption-afreeca-purge-credentials

**Comment by RubyRudy** [comment]
it's fixed!!! thank you very much, didn't even know that command exist.
