### ISSUE TITLE
Twitter Spaces

### ISSUE THREAD

**Issue by archiif** [streamlink/streamlink#4399]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

https://help.twitter.com/en/using-twitter/spaces
Twitter Spaces is a new feature on Twitter that allows users to have live audio conversations on the platform. Users can host these conversations in an audio chat room called a “Space” and invite other users to participate. If someone you follow is hosting Space or a Speaker in one, it’ll show up as a purple bubble at the top of your timeline for the duration of the conversation.

### Input URLs

https://twitter.com/twitterspaces
https://twitter.com/i/spaces/1mrGmaeDLqdGy
https://twitter.com/i/spaces/1ynJOZWvzDXGR
https://twitter.com/i/spaces/1OdKrBgmDvwKX

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 7. Sites which don't provide any video streaming content

**Comment by Trung0246** [comment]
Should I resurrect this issue since Twitter/X apparent now have streaming:

https://twitter.com/elonmusk/status/1708776354597003329

Obviously it's still in beta state

**Comment by WolfganP** [comment]
> Should I resurrect this issue since Twitter/X apparent now have streaming:
> 
> https://twitter.com/elonmusk/status/1708776354597003329
> 
> Obviously it's still in beta state

Try sideloading the plugin at https://github.com/streamlink/streamlink/discussions/5296#discussioncomment-7606986
