### ISSUE TITLE
Remove faraday gem from travis.yml

### ISSUE THREAD

**Issue by martinth** [streamlink/streamlink#44]
Just noticed that the [travis.yml](https://github.com/streamlink/streamlink/blob/master/.travis.yml#L16) installs a random Ruby gem. I grepped thought the repo content but I couldn't find any mention of `faraday`, `ruby` or `rb`. Is this a leftover from livestreamer or doe anyone know what it does?

**Comment by sbstp** [comment]
[Looks like a left over](https://github.com/chrippa/livestreamer/commit/6f338866c8d08b57b02d5f8bb822156214419e79). I think it's part of livestreamer's build system, it uploads artifacts to s3. We don't use it. We're still working on our Windows build, so we haven't removed the cruft of the old build system yet.

**Comment by martinth** [comment]
Yes, I suspected that. On the topic of releases: It would probably the easiest to just use Githubs releases feature (https://docs.travis-ci.com/user/deployment/releases) since the hosting would be free (in contrast to S3 which would probably not expensive but still a few bucks each month).

**Comment by gravyboat** [comment]
I probably just missed it when I was doing the PR here: https://github.com/streamlink/streamlink/pull/6 I even noted that we don't use the functionality and removed all the S3 stuff.
