### ISSUE TITLE
ZATTOO question

### ISSUE THREAD

**Issue by qwe199** [streamlink/streamlink#4417]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

`streamlink https://zattoo.com/live/rai-uno best --zattoo-email=zattoo8@snapmail.cc --zattoo-password=786374648 --http-proxy "socks5h://127.0.0.1:7890"`
![微信截图_20220401183756](https://user-images.githubusercontent.com/84278637/161247692-ba8d107e-e910-4f8d-b4d8-6bcb4b6b4b94.png)

Currently unable to get 1080p, he only has 432p, but the website is normal 1080P,
 you can log in to my account to test and check.but you need swiss ip

### Debug log

```text
C:\Users\agang>streamlink https://zattoo.com/live/rai-uno best --zattoo-email=zattoo8@snapmail.cc --zattoo-password=786374648 --http-proxy "socks5h://127.0.0.1:7890"
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/live/rai-uno
[cli][info] Available streams: 288p_alt2 (worst), 288p_alt, 288p, 432p (best)
[cli][info] Opening stream: 432p (dash)
[cli][info] Starting player: "C:\Program Files\KMPlayer 64X\KMPlayer64.exe"
[utils.named_pipe][info] Creating pipe streamlinkpipe-10828-1-125
[utils.named_pipe][info] Creating pipe streamlinkpipe-10828-2-8678
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by back-to** [comment]
try `--zattoo-purge-credentials`

```
$ streamlink https://zattoo.com/live/rai-uno
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.1
[cli][debug] Streamlink: 3.2.0+10
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://zattoo.com/live/rai-uno
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/live/rai-uno
[stream.dash][debug] Available languages for DASH audio streams: en, it (using: it)
[stream.dash][debug] Available languages for DASH audio streams: en, it (using: it)
[cli][info] Available streams: 288p_alt2 (worst), 288p_alt, 288p, 432p, 720p_alt, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
```

**Comment by campones** [comment]
I didn't kow about this zattoo site  but when I try I get this (I have swiss ip)

 streamlink --zattoo-email campi@gmail.com --zattoo-password xxxxx https://zattoo.com/live/numero23
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/live/numero23
[plugins.zattoo][error] Unfortunately streaming is not permitted in this country or this channel does not exist.
error: No playable streams found on this URL: https://zattoo.com/live/numero23

is this available only in Germany?
