### ISSUE TITLE
Add {plugin_name} metadata variable

### ISSUE THREAD

**Issue by PAI5REECHO** [streamlink/streamlink#4418]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

`yt-dlp` has [`webpage_url_domain`](https://github.com/yt-dlp/yt-dlp#user-content-output-template) as an output template field that I use to organize my downloads by site (`youtube.com`, `twitch.tv`, `vimeo.com` etc.). It'd be nice if a `url_domain` variable could be added to have parody with that of `yt-dlp` so both tools could coexist nicely and use the same organization directory structure.

**Comment by bastimeyer** [comment]
I can only see this being useful for (custom) config files, if the output path is defined there and the user's input URL set on the CLI.

When not using a config file with a predefined output path, the input URL already implies which path you should use in the `--output` or `--record` argument value, so adding a new metadata var is not really necessary and the path can easily be set manually.

Plugins also support different domains, so adding a `{plugin}` or `{pluginname}` variable would make more sense IMO.

**Comment by PAI5REECHO** [comment]
> I can only see this being useful for (custom) config files, if the output path is defined there and the user's input URL set on the CLI.

This is indeed how I intend to use this if added.

In my `youtube-dl` config I currently have:
```
# ~/.config/yt-dlp/config
--output "~/vids/%(webpage_url_domain)s/%(uploader_id)s/%(upload_date>%Y.%m.%d)s_%(id)s_%(title)s.%(ext)s"
```
In my `streamlink` config I _wish_ to have:
```
output=~/vids/{url_domain}/{author}/{time:%Y.%m.%d}_{id}_{title}.ts
```
This would allow the two tools to both use the same directory naming scheme.

> Plugins also support different domains, so adding a `{plugin}` or `{pluginname}` variable would make more sense IMO.

This does make more sense and I also would prefer this but unfortunately `yt-dlp` & friends don't have any such counterpart I could use currently, I'll open an issue on `yt-dlp` to address this though.

**Comment by Ismailovpro** [comment]
For Bigo.tv is worked bot?
