### ISSUE TITLE
proxy set in config not work

### ISSUE THREAD

**Issue by housunzi** [streamlink/streamlink#4426]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

when I set the proxy http-proxy="http://127.0.0.1:10802" in confing file, but not work just used for this stream
streamlink -l debug https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 best
and received the below information:C:\Users\1>streamlink -l debug https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --http-proxy="http://127.0.0.1:10802"
[cli][info] Found matching plugin hls for URL https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8
[plugins.hls][debug] URL=https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8; params={}
[utils.l10n][debug] Language code: zh_CN
error: Unable to open URL: https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 (HTTPSConnectionPool(host='edge2-slc.live.mmcdn.com', port=443): Max retries exceeded with url: /live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03CC5AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))))
I find the "ProxyError('Cannot connect to proxy"
but if i use the comand:   streamlink --http-proxy "http://127.0.0.1:10802" -l debug https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 best
it can work well and play with VLC
Dear sir , could you please tel me where the wrong set is?

### Debug log

```text
streamlink -l debug https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 best
and received the below information:C:\Users\1>streamlink -l debug https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --http-proxy="http://127.0.0.1:10802"
[cli][info] Found matching plugin hls for URL https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8
[plugins.hls][debug] URL=https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8; params={}
[utils.l10n][debug] Language code: zh_CN
error: Unable to open URL: https://edge2-slc.live.mmcdn.com/live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 (HTTPSConnectionPool(host='edge2-slc.live.mmcdn.com', port=443): Max retries exceeded with url: /live-hls/amlst:innocentemmy-sd-04dd2666bd43048b0351d3fa268c76954268c2ac4fa303a9486b6b703b670445_trns_h264/playlist.m3u8 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03CC5AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))))
```

**Comment by bastimeyer** [comment]
> when I set the proxy http-proxy="http://127.0.0.1:10802/" in confing file

> [cli][debug]  --http-proxy="http://127.0.0.1:10802"

Quotations do not belong into the config file. They become part of the argument value, hence why it's not working.

See the config file docs:
https://streamlink.github.io/latest/cli/config.html#syntax
