### ISSUE TITLE
Paramount

### ISSUE THREAD

**Issue by 89z** [streamlink/streamlink#4427]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

TV

### Input URLs

https://www.paramountplus.com/shows/aeon-flux/video/PI4BXWiT3IswVrIJV3NGQxH71afjnMeA/aeon-flux-the-demiurge/

**Comment by bastimeyer** [comment]
Is there even any live streaming content? It's not accessible in my region.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 6. Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

https://en.wikipedia.org/wiki/Paramount%2B

> Paramount+ is an American subscription video on-demand over-the-top streaming service

**Comment by 89z** [comment]
> Sites which don't provide any real live streaming content, eg. only VODs or VODs being rebroadcasted

Hm. So if a site has some live content, then youll support all content on the site, even non-live content:

~~~
streamlink --output out https://www.youtube.com/watch?v=zVx65iy2GGs worst
~~~

but if a site has no live content, then you dont support the site at all? If thats the rule I respect that, but that seems kind of arbitrary.

**Comment by 89z** [comment]
Also, it seems the site does offer live content:

https://www.paramountplus.com/live-tv

**Comment by back-to** [comment]
closing, this website would be annoying to maintain.
