### ISSUE TITLE
Plugin matrix 404

### ISSUE THREAD

**Issue by 89z** [streamlink/streamlink#4428]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Here:

https://github.com/streamlink/streamlink#features

you have this link:

<https://streamlink.github.io/plugin_matrix.html>

which gives 404.

### Debug log

```text
no
```

**Comment by 89z** [comment]
I think this is the new link:

https://streamlink.github.io/plugins.html

**Comment by bastimeyer** [comment]
Yep, the readme once again did not get updated after the recent docs changes. I always forget about the readme and tbh never look at it here.

Can you open a quick PR please? Thanks

**Comment by 89z** [comment]
Sorry, I am quite busy with other tasks. Hopefully someone with more time can tackle this. Thanks for the response.
