### ISSUE TITLE
trovo.live

### ISSUE THREAD

**Issue by YxY-CHN** [streamlink/streamlink#4436]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

trovo(https://trovo.live/) is a streaming media platform launched by Tencent. I have seen the Plugin Request record in issues before(#3069 , #3076 ), but it was not considered because trovo was in the beta stage at that time. At present, trovo has removed the beta logo and ended the beta stage. Hope to re-apply for plugin support for this platform.

### Input URLs

1. https://trovo.live/BloodyTV1
2. https://trovo.live/Sibuyas
3. https://trovo.live/SpaK

**Comment by mkbloke** [comment]
It looks like it's possible to get HLS from the site, even though they are using either streamed or chunked FLV - I've not quite worked out which, the whole site is a bit weird compared to the usual...

Viewer numbers are a mixed bag - not sure what's considered worthwhile.  Looking at https://trovo.live/trending/streamers might be useful in that regard.

**Comment by YxY-CHN** [comment]
> It looks like it's possible to get HLS from the site, even though they are using either streamed or chunked FLV - I've not quite worked out which (but I think it's the latter), the whole site is a bit weird compared to the usual...
> 
> Viewer numbers are a mixed bag - not sure what's considered worthwhile. Looking at https://trovo.live/trending/streamers might be useful in that regard.

it may be chunked FLV. It is said that it will sponsor some game events to promote its own site. You can view the distribution of specific sections and the number of viewers: https://trovo.live/trending
