### ISSUE TITLE
Plugin; Facebook - Videos not loading

### ISSUE THREAD

**Issue by steffbp** [streamlink/streamlink#4448]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Facebook streams are not loading, tried multiple streams.
Judging from the log, no meta data is found.

### Debug log

```text
C:\Users\USER>streamlink -l debug https://www.facebook.com/Ramee/videos/1032350587716862
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.facebook.com/Ramee/videos/1032350587716862
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/Ramee/videos/1032350587716862
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/Ramee/videos/1032350587716862
```

**Comment by bastimeyer** [comment]
This URL requires a facebook login. The plugin hasn't been updated in a while and doesn't detect this restriction.

**Comment by mkbloke** [comment]
> This URL requires a facebook login. The plugin hasn't been updated in a while and doesn't detect this restriction.

Ah, interesting.  Tried in a private browsing window, UK IP => login required; AR IP => login not required...

**Comment by steffbp** [comment]
I guess it geo related and FB changed something in their end - I was using this 1 or 2 weeks ago without any issue from DK.

Thanks :)

**Comment by nixeo** [comment]
Hi all, do we have an update related to this issue? I couldn't streamlink facebook live stream since 3 days ago.  Weird, it just happen randomly but now cannot use it at all.
