### ISSUE TITLE
https://www.useetv.com/

### ISSUE THREAD

**Issue by BBBABUHS** [streamlink/streamlink#4451]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

LIVETV OFFCIAL BY INDONESIA , GOT ALOT OF ENGLISH CHANNELS

### Input URLs

https://www.useetv.com/livetv/seatoday
https://cdn09jtedge.useetv.com/joss/133/seatoday/chunklist_w1268139421_b844100_sleng.m3u8?enc=9Q3OzUmDj1HhXf-juvVnLA&uid=&exp=1649876868

**Comment by mkbloke** [comment]
I don't know if this is worth writing a plugin for or not - the playlist URLs seem to be embedded in the JS of the page HTML and can easily be extracted by searching for `m3u8` and then played with the link copied out:
```
$ streamlink --http-no-ssl-verify 'https://streaming.useetv.com/joss/133/seatoday/playlist.m3u8?enc=x0KVJdJswyEo8fAVod3x1w&exp=1651028204&encp=__UhcXzshmaYYIPFuJ0KVw&expp=1651036904' 540p
[cli][info] Found matching plugin hls for URL https://streaming.useetv.com/joss/133/seatoday/playlist.m3u8?enc=x0KVJdJswyEo8fAVod3x1w&exp=1651028204&encp=__UhcXzshmaYYIPFuJ0KVw&expp=1651036904
[cli][info] Available streams: 270p (worst), 360p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 540p (hls)
[cli][info] Starting player: mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
