### ISSUE TITLE
hi, can u fix to grab this?  https://iview.abc.net.au/video/NS1413V001S00

### ISSUE THREAD

**Issue by BBBABUHS** [streamlink/streamlink#4452]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

hi, can u fix to grab this?

https://iview.abc.net.au/video/NS1413V001S00

### Debug log

```text
hi, can u fix to grab this?

https://iview.abc.net.au/video/NS1413V001S00
```

**Comment by mkbloke** [comment]
DASH with CENC DRM.  Streamlink's DASH implementation does not decode CENC.
