### ISSUE TITLE
plugins.crunchyroll: Unauthenticated request error, login system may have changed ?

### ISSUE THREAD

**Issue by Stella-Hoshineko** [streamlink/streamlink#4453]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The Crunchyroll plugin worked well last Sunday. Now I get an Unauthenticated request message, even though my username/password haven't changed. I provide the log for an episode I know for a fact played well this weekend.

My best guess would be a change in the way Crunchyroll deals with logins, as I can now activate the CR app on my TV just by writing an activation code on my web browser session instead of writing the whole password, which was not an option weeks ago.

### Debug log

```text
C:\Users\Stella>streamlink --loglevel debug crunchyroll.com/fr/spy-x-family/episode-1-operation-strix-842454
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=crunchyroll.com/fr/spy-x-family/episode-1-operation-strix-842454
[cli][debug]  --loglevel=debug
[cli][debug]  --locale=en_US
[cli][debug]  --player="C:\Users\Stella\Documents\MPV\mpv.exe"
[cli][debug]  --player-args=--keep-open=yes --cache=yes
[cli][debug]  --player-no-close=True
[cli][debug]  --title={author} - {category} - {title}
[cli][debug]  --default-stream=['best']
[cli][debug]  --ringbuffer-size=134217728
[cli][debug]  --stream-segment-threads=3
[cli][debug]  --hls-segment-threads=3
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --crunchyroll-username=********
[cli][debug]  --crunchyroll-password=********
[cli][info] Found matching plugin crunchyroll for URL crunchyroll.com/fr/spy-x-family/episode-1-operation-strix-842454
[utils.l10n][debug] Language code: en_US
[plugins.crunchyroll][debug] Creating session with locale: en_US
Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1061, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 570, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 464, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 336, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 307, in _get_streams
    api = self._create_api()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 372, in _create_api
    api.start_session()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 190, in start_session
    self.session_id = self._api_call("start_session", params, schema=_session_schema)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 166, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugins.crunchyroll.CrunchyrollAPIError: Unauthenticated request
```

**Comment by neko47834** [comment]
Yes, same error here, it seems that Crunchyroll changed the access token again, tested on stable and nightly build

**Comment by locknet11** [comment]
Same error, would be great to know how streamlink devs get that access token...

**Comment by bastimeyer** [comment]
> would be great to know how streamlink devs get that access token

1. https://github.com/streamlink/streamlink/blame/e4490ad3519ff53ea53b3c8fc4356cf519dc5d1f/src/streamlink/plugins/crunchyroll.py#L102
2. https://github.com/streamlink/streamlink/commit/09f46a33b0b1918ce7e0ad0534788e0fd786caea
3. https://github.com/streamlink/streamlink/pull/2788
4. https://github.com/streamlink/streamlink/issues/2785#issuecomment-581081985

**Comment by locknet11** [comment]
> > would be great to know how streamlink devs get that access token
> 
>     1. https://github.com/streamlink/streamlink/blame/e4490ad3519ff53ea53b3c8fc4356cf519dc5d1f/src/streamlink/plugins/crunchyroll.py#L102
> 
>     2. [09f46a3](https://github.com/streamlink/streamlink/commit/09f46a33b0b1918ce7e0ad0534788e0fd786caea)
> 
>     3. [Update Crunchyroll access token. Fixes streamlink/streamlink issue #2785. #2788](https://github.com/streamlink/streamlink/pull/2788)
> 
>     4. [Can't authenticate Crunchyroll, CrunchyrollAPIError: Unauthenticated request #2785 (comment)](https://github.com/streamlink/streamlink/issues/2785#issuecomment-581081985)

yeah, I've check all stuff related to crunchyroll plugin, but haven't found where can I get the new token when they change it yet.
Seems that in June this plugin will be gone (at least login logic), since crunchyroll is migrating to the new API.

**Comment by mkbloke** [comment]
The access token comes from the Android app.  You'll need to either install the app on a phone and run it from there or perhaps it could be run via an Android emulator.  You'll need to configure a proxy and use something like mitmproxy to spy on the network requests.  Hopefully you will find a POST request with `access_token` in the payload data.

It's possible that things have changed now.  The plugin seems to be based on app version 2.1.0, but the current Crunchyroll app version appears to be 3.18.0 (I think).  It's possible they have not just changed the token value, but the whole API.  This failure could therefore be because they've turned the old API off.

**Comment by locknet11** [comment]
> The access token comes from the Android app. You'll need to either install the app on a phone and run it from there or perhaps it could be run via an Android emulator. You'll need to configure a proxy and use something like mitmproxy to spy on the network requests. Hopefully you will find a POST request with `access_token` in the payload data.
> 
> It's possible that things have changed now. The plugin seems to be based on app version 2.1.0, but the current Crunchyroll app version appears to be 3.18.0 (I think). It's possible they have not just changed the token value, but the whole API. This failure could therefore be because they've turned the old API off.

Yeah, I've installed several versions on Crunchyroll app on android emulator, I run HttpToolkit to intercept that traffic, but the token seems encrypted `fgS4DSihTXaEj0HuWiaWlr:APA91bEjq73PQC327j0T1g5c41hzbo-bCW1Q3DCYzFepsczHDIBnmAMxNg1-eu56CLa5R6AINoL0TPavBtjB9ldm06uH_lI-m187ekOwehzMGxC6IvrHaaa5oVdwPtp1TF9ahWwRobYu`
So this method wouldn't be a workaround this time.

**Comment by mkbloke** [comment]
I installed the app on my phone and looked at the traffic.  I saw a similarly long token, but that appears to be a bearer token, which is another thing.  I don't have a Crunchyroll account anyway, so that doesn't help.

My phone is 32 bit ARMv7, with Android 7.1.  I tried using the last 2.x release I could find via APKPure (version 2.5.0), but it did not appear in the app menu, so I gave up with that one.  It seems to me, having looked at both APKPure and APKMirror that the 3.x releases target Android 6.0+ while 2.5.0 targets Android 5.0+.  If you can manage to get version 2.5.0 installed and running somewhere, it might yield the token you're looking for (if it works at all).  I did manage to get version 2.3.0 from APK mirror installed and it ran, but then produced an error message.  The network traffic did yield a token, but it was an old one, so no good.

So, I'm not sure about this, but it could be that with an Android 5.1 based device you might get a 2.x version, which might have the token we're all looking for.  Or it could be that the plugin needs a rewrite to do things the way they're done in the 3.x app releases.  I'm not sure why the plugin is based on the Android app, perhaps the website uses DRM or did other stuff in JS that would have made the plugin implementation a lot harder...

**Comment by locknet11** [comment]
I had no luck , I tried v2.5.0 and v2.6.0 and both uses the old keys in the request, since v3.0.0 points to the new API so can't get the token from this point. And the new login system seems to defer a lot. So a plugin rewrite is mandatory.

**Comment by mkbloke** [comment]
That's disappointing to hear, but thanks for trying it out.

**Comment by locknet11** [comment]
There's one last chance to see if this works, seems that the 2.5.0 app version received the last update in 30th March, 2022. Just the day before this plugin stop working. I tried to download this version fom apkpure.com but this folks split the apk so I can't install it. If i could get the apk of this version and install it, maybe i'll be able to get the token. At least to make it work until June.

**Comment by mkbloke** [comment]
That is likely the same one I tried on my phone and could not get to work.  Maybe you will have better luck with it.  As I guess you may have worked out, you'll need to install the APKPure app to install the split APKs from that site.

I'm confused about the dates shown - are they release dates or simply upload dates?  I was not able determine which.

**Comment by kyldery** [comment]
One can use the token from Windows desktop client, instead of the android.

Changing these lines

https://github.com/streamlink/streamlink/blob/867b9b3b66aab57c0fcb3ab117a275f29a23b71a/src/streamlink/plugins/crunchyroll.py#L102-L103

to

``` python
_access_token = "LNDJgOit5yaRIWN"
_access_type = "com.crunchyroll.windows.desktop"
```

Seems to fix the issue. This token is not changed since at least 2020, so I think it's more stable.

### Debug log

```
[cli][debug] OS:         Windows 8.1
[cli][debug] Python:     3.10.3
[cli][debug] Streamlink: 4.0.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.crunchyroll.com/hunter-x-hunter/episode-148-past-x-and-x-future-654039
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\mpv\mpv.com
[cli][debug]  --player-args=--pause
[cli][debug]  --verbose-player=True
[cli][debug]  --player-no-close=True
[cli][debug]  --title={title} -!- {author} -!- {category}
[cli][debug]  --stream-sorting-excludes=['None', '>=1440p60']
[cli][debug]  --ringbuffer-size=67108864
[cli][debug]  --stream-segment-threads=4
[cli][debug]  --mux-subtitles=True
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/hunter-x-hunter/episode-148-past-x-and-x-future-654039
[utils.l10n][debug] Language code: pt_BR
[plugins.crunchyroll][debug] Creating session with locale: pt_BR
[plugins.crunchyroll][debug] Session created with ID: a552879f769b72538fdb60edf2945efd
[plugins.crunchyroll][warning] No authentication provided, you won't be able to access premium restricted content
[plugins.crunchyroll][debug] Loading streams from adaptive playlist
[utils.l10n][debug] Language code: pt_BR
[utils.l10n][debug] Language code: pt_BR
[utils.l10n][debug] Language code: pt_BR
Available streams: 240p_alt (worst), 240p, 360p_alt, 360p, 480p_alt, 480p, 720p_alt, 720p, 1080p_alt, 1080p (best)
```

**Comment by locknet11** [comment]
> ```python
> LNDJgOit5yaRIWN
> ```

You have saved us we are eternally grateful. I didn't know that there was a Windows app. Thanks for sharing.

**Comment by mkbloke** [comment]
@kyldery, that's excellent, thanks very much.  I did not know there was a Windows app either!

**Comment by neko47834** [comment]
Well, changing the android access token to the windows one at first works fine, but when the player is closed a "plugin-cache.json" file is created which if not cleared causes an error:

[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/es/deaimon-recipe-for-happiness/episode-1-nagomu-and-itsuka-842537

Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 212, in authenticate
    data = self._api_call("authenticate", {"auth": self.auth}, schema=_login_schema)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 167, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugins.crunchyroll.CrunchyrollAPIError: The user could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 197, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1061, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 570, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 464, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 336, in streams
    ostreams = self._get_streams()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 308, in _get_streams
    api = self._create_api()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 377, in _create_api
    login = api.authenticate()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\crunchyroll.py", line 215, in authenticate
    self.cache.set("auth", None, expires_at=0)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\cache.py", line 76, in set
    expires = mktime(expires_at.timetuple())
AttributeError: 'int' object has no attribute 'timetuple

**Comment by mkbloke** [comment]
@neko47834, is your plugin.cache looking like this (the same value as here):
```
{
  "crunchyroll:device_id": {
    "value": 31536000,
    "expires": 1652312844.9755983
  }
}
```
If so, it's something I noticed earlier.
https://github.com/streamlink/streamlink/blob/e8c7e0ff7ee8388f75e85bb47a5430528124751b/src/streamlink/plugins/crunchyroll.py#L178
The number of parameters in the call to `self.cache.set()` is incorrect.  I already fixed it in the changes I'm working on.  I'll push those to GitHub soon so that they can be tested.

**Comment by neko47834** [comment]
@mkbloke yes, it looks almost the same

> {
  "crunchyroll:device_id": {
    "value": 31536000,
    "expires": 1652376376.670161
  },

**Comment by mkbloke** [comment]
Could folks here please test out this version, which is currently a PR awaiting inclusion into Streamlink master (#4510):

https://raw.githubusercontent.com/streamlink/streamlink/08ba971f1bbd87a2da3f4a1a42cc3d0ddf2ca29c/src/streamlink/plugins/crunchyroll.py

It incorporates the `_access_token` and `_access_type` params updates; updates other params; removes Android headers and fixes the `device_id` cached value.  If you have:
```
  "crunchyroll:device_id": {
    "value": 31536000,
    "expires": 1652312844.9755983
  }
```
in your plugin.cache file you should edit it out to have a new one generated, which will now be stored correctly.

I'm particularly interested to know if the login process still works correctly, along with access to premium content streams.  I'm pretty sure it should do, but I cannot test it myself, so any confirmation will be welcome.  Thanks.

**Comment by neko47834** [comment]
@mkbloke I tried the update that you made unfortunately the same error follows after creating a "plugin-cache.json", if the file is deleted everything works very well but when the file is created it returns to show the error that I mentioned.
The "plugin-cache.json" file now shows these values:

> {
  "crunchyroll:device_id": {
    "value": "2a85b8f0-de0b-469d-b9b9-9a0c37025e82",
    "expires": 1683337008.4957318
  }

**Comment by mkbloke** [comment]
@neko47834, I have edited the link in my comment above (https://github.com/streamlink/streamlink/issues/4453#issuecomment-1119111595) to point to an updated version.  Please download that one and give it a try.  I hope it will fix your issue.  Thanks.

**Comment by mkbloke** [comment]
Note: the latest version adds support for beta URLs, so if you're trying Crunchyroll beta, any reports from testing of those URLs would also be appreciated.  Thanks.

**Comment by CanaryGold** [comment]
@mkbloke can confirm that updated plugin works for me, and does work with the beta URLs, having sideloaded it.

**Comment by skwurw** [comment]
@mkbloke I can also confirm that these changes work, along with accessing premium content

**Comment by neko47834** [comment]
@mkbloke Thank you very much, now everything works very well, tested both free and premium chapters, Normal/BETA URLS.

I will continue testing it to look for some type of error, again thank you very much

**Comment by mkbloke** [comment]
@skwurw, can you provide the full `-l debug` output if you are still seeing this, please?  Can you still log in via the website OK?

After that, you could try using `--crunchyroll-purge-credentials` once to clear the cached auth token, then run one time with `--crunchyroll-username` and `--crunchyroll-password` to cache the auth token again.

**Comment by skwurw** [comment]
@mkbloke
```
[22:07:38.684278][session][debug] Plugin crunchyroll is being overridden by C:\\Users\\-\\AppData\\Roaming\\streamlink\\plugins\\crunchyroll.py
[22:07:38.710279][cli][debug] OS:         Windows 8.1
[22:07:38.711280][cli][debug] Python:     3.10.3
[22:07:38.711280][cli][debug] Streamlink: 4.0.0
[22:07:38.711280][cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[22:07:38.711280][cli][debug] Arguments:
[22:07:38.711280][cli][debug]  url=https://crunchyroll.com/date-a-live/fairy-tale-842792
[22:07:38.711280][cli][debug]  stream=['1080p']
[22:07:38.712279][cli][debug]  --loglevel=trace
[22:07:38.712279][cli][debug]  --output=\\\\192.168.1.102\\debianshare\\Shows\\Date A Live\\Season 4\\Episode 5 - Fairy Tale.mp4
[22:07:38.712279][cli][debug]  --hls-segment-attempts=5
[22:07:38.712279][cli][debug]  --ffmpeg-ffmpeg=S:\\Programs\\ffmpeg\\ffmpeg.exe
[22:07:38.712279][cli][debug]  --crunchyroll-username=-
[22:07:38.712279][cli][debug]  --crunchyroll-password=********
[22:07:38.713280][cli][info] Found matching plugin crunchyroll for URL https://crunchyroll.com/date-a-live/fairy-tale-842792
[22:07:38.844286][utils.l10n][debug] Language code: en_US
[22:07:38.855288][plugins.crunchyroll][debug] Device ID: 571e5137-0506-400c-93bf-d807524751ca
[22:07:38.856287][plugins.crunchyroll][debug] Creating session with locale: en_US
[22:07:39.051298][plugins.crunchyroll][debug] Session created with ID: 379a8d0dac9f8faeab8359af8172316d
[22:07:39.051298][plugins.crunchyroll][debug] Attempting to login using username and password
error: Authentication error: A system error occurred. Please contact us for help.
```
Not much to the log lol. I did try the purge credentials and didn't do a thing. Also trying to log into the website and it gives the same error (tried logging in on incognito and wasn't able to log in, but still logged in on normal tab), I think this is just a rate limiting issue since I got this error by pretty much trying to run the plugin too much. After about 10 or so mins I was able to log back in again.

**Comment by mkbloke** [comment]
@skwurw, yeah, the debug log doesn't have much, but good to confirm which plugin options you where using at the time and that the device_id is in the correct format.

Rate limiting is something I wondered about.  That, or possibly a failure at their end which caused an issue with the login process.  Glad to hear you were able to log back in eventually!

**Comment by mkbloke** [comment]
Thanks for the feedback, everybody.
