### ISSUE TITLE
Remove `streamlink.plugin.api.utils.itertags`

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4455]
[`streamlink.plugin.api.utils.itertags`](https://github.com/streamlink/streamlink/blob/3.2.0/src/streamlink/plugin/api/utils.py#L16-L28) has become obsolete ever since `lxml` was added as a dependency to Streamlink for parsing HTML.

`itertags` is a hacky implementation via regexes, which is not only slow, but it's also impossible to correctly parse HTML nodes with regular expressions, so it shouldn't be used when better and much faster solutions are available. It also always requires unescaping tag values, which is annoying.

We've already updated and replaced lots of plugins which were previously using it, but there are still some left:
```
$ GIT_PAGER=cat git grep -F 'from streamlink.plugin.api.utils import' a1ce471f
a1ce471f:src/streamlink/plugins/cdnbg.py:from streamlink.plugin.api.utils import itertags
a1ce471f:src/streamlink/plugins/facebook.py:from streamlink.plugin.api.utils import itertags
a1ce471f:src/streamlink/plugins/funimationnow.py:from streamlink.plugin.api.utils import itertags
a1ce471f:src/streamlink/plugins/senategov.py:from streamlink.plugin.api.utils import itertags
a1ce471f:src/streamlink/plugins/vrtbe.py:from streamlink.plugin.api.utils import itertags
a1ce471f:tests/test_plugin_utils.py:from streamlink.plugin.api.utils import itertags
```

- [x] cdnbg
- [x] facebook
- [x] funimationnow
- [x] senategov
- [x] vrtbe

Once every last plugin has been updated, the entire `streamlink.plugin.api.utils` module can be removed, as it only contains the `itertags` function and some other useless export aliases which are not even used anymore in Streamlink's codebase.

If we care about plugin-API stability (something which has never been discussed), removing this would be considered a breaking change. Since we've just dropped py36, that's something which could be included in the 4.0.0 release.

**Comment by bastimeyer** [comment]
Regarding facebook, as I already posted on Gitter/Matrix, I have a dev branch with a plugin rewrite here:
https://github.com/streamlink/streamlink/compare/master...bastimeyer:plugins/facebook/rewrite
I lost interest though, because I don't have a FB account, and all new ones I've created got blocked pretty much immediately. That's why my rewrite is incomplete and basically just a translation and improvement of the old logic, which means that the changes are most likely not working.

----

Regarding VRTbe, this site uses DRM for both HLS and DASH streams. The last plugin update was in June 2018 via e70053511331db579e4adde085ebf049d34e4ecf, and the commit message says that it only applies to high quality streams. I can't confirm this, for both live and vod streams. And from what I can see, [the current plugin implementation](https://github.com/streamlink/streamlink/blob/3.2.0/src/streamlink/plugins/vrtbe.py#L44) is not working (no HTMLElement with a `vrtvideo` class). The livestream page also lists all live streams at once, which makes it pretty much useless.

- https://www.vrt.be/vrtnu/livestream/
- https://www.vrt.be/vrtnu/kanalen/een/

```
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://...",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```
```xml
      <!-- Common Encryption -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        xmlns:cenc="urn:mpeg:cenc:2013"
        schemeIdUri="urn:mpeg:dash:mp4protection:2011"
        value="cenc"
        cenc:default_KID="F0A275F8-F9A1-EDD5-546C-4ABB1DB127AA">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95"
        value="MSPR 2.0">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED">
      </ContentProtection>
      <!-- Marlin -->
      <ContentProtection
        xmlns="urn:mpeg:dash:schema:mpd:2011"
        schemeIdUri="urn:uuid:5E629AF5-38DA-4063-8977-97FFBD9902D4">
        <MarlinContentIds xmlns="urn:marlin:mas:1-0:services:schemas:mpd">
          <MarlinContentId>urn:marlin:kid:f0a275f8f9a1edd5546c4abb1db127aa</MarlinContentId>
        </MarlinContentIds>
      </ContentProtection>
```

**Comment by gravyboat** [comment]
For VRTbe I've merged the PR removing it. For FB there's nothing I can do either here as I don't use FB nor do I have an account. It's been broken for quite some time and the number of issues we get related to FB not working is relatively low so I'd be fine with removing it. If someone who regularly uses FB is willing to develop and maintain that plugin we can reconsider adding it in the future.
