### ISSUE TITLE
Option to get audio with video, but save do disk audio only

### ISSUE THREAD

**Issue by pboettcher** [streamlink/streamlink#4461]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

There was another ticket https://github.com/streamlink/streamlink/issues/1776, but this is a different one.

It is pretty clear to me that some sources are streaming audio with video only, but I would like to see that streamlink gets audio with video, extracts audio on the fly and writes it to audio file.

The purpose is to save disk space and SSD life.

**Comment by mkbloke** [comment]
You can already do this by piping the output into `ffmpeg` and supplying the right arguments to it.

**Comment by bastimeyer** [comment]
As @mkbloke already pointed out, use ffmpeg. This can be achieved in multiple ways via the available [file output options](https://streamlink.github.io/latest/cli.html#file-output-options). Adding CLI options for that doesn't make any sense.

One of these options could be [`--record`](https://streamlink.github.io/latest/cli.html#cmdoption-record) with the value being set to `-`, but unfortunately, [`-` does not get interpreted as `stdout` in the `--record` logic](https://github.com/streamlink/streamlink/blob/aa91920b77636be376766c12cffc1ad146c13d2a/src/streamlink_cli/main.py#L134-L135), so piping the stream into ffmpeg and remuxing it while watching it in the player that gets spawned by streamlink at the same time is not possible right now. That could be easily added though.

```sh
streamlink --record=- --player=player "$INPUT" "$QUALITY" \
  | ffmpeg -i pipe:0 -vn -c:a copy "$file.m4a"
```

For now, you'll have to use `--stdout`, clone the output stream and pipe them into both ffmpeg and the video player.

**Comment by bastimeyer** [comment]
I'm leaving this thread open the implementation of the `--record=-` value. I'll take a look at this tomorrow or so. Should be fairly simple from what it looks like.

**Comment by bastimeyer** [comment]
A workaround for `--record=-` could of course also be writing to a named pipe on the file system.

```bash
mkfifo ./foo
streamlink --record=./foo --player=player "$INPUT" "$QUALITY" &
ffmpeg -i ./foo -vn -c:a copy "$file.m4a"
```

**Comment by pboettcher** [comment]
@mkbloke , @bastimeyer , thank you for showing this capability. Could you please make it clear for me whether such a piping uses disk as an intermediate media between streamlink and ffmpeg, or the data thansfer happens entirely in RAM preventing excessive SSD wear out?

**Comment by bastimeyer** [comment]
https://en.wikipedia.org/wiki/Pipeline_(Unix)

**Comment by bastimeyer** [comment]
Why are you even worried about SSD wear if you're trying to archive media files on it. This is complete non-sense. If you're worried about wear, which is rather ridiculous in these days anyway, then write to other storage mediums.

**Comment by pboettcher** [comment]
I only use SSD as an editing medium. I then store audios on a normal HDD, on a server.
