### ISSUE TITLE
9anime.to not working again :(

### ISSUE THREAD

**Issue by bobvargas** [streamlink/streamlink#447]
Hey guys I have found another plugin bug on 9anime.to this time when I want to watch doraemon 2005 it gives me an error like this:

C:\Users\SUS>streamlink -p C:\Users\SUS\Downloads\VideoLAN\VLC\vlc.exe 9anime.to
/watch/doraemon-2005.834o/kko61v 720p
[cli][info] Found matching plugin nineanime for URL 9anime.to/watch/doraemon-200
5.834o/kko61v
error: Unable to open URL: //9anime.to/grabber-api/ (Invalid URL '//9anime.to/gr
abber-api/': No schema supplied. Perhaps you meant http:////9anime.to/grabber-ap
i/?)
what that it mean? Please help me.

**Comment by beardypig** [comment]
Looks like something has changed on the site, but it's probably an easy fix.

**Comment by bobvargas** [comment]
@beardypig I know sorry to said again that the plugin is dealing with issues with site changes but hopefully you fix the api on 9anime.to @beardypig

**Comment by beardypig** [comment]
Should be easily fixed :-)

**Comment by gravyboat** [comment]
Closing this since #449 is merged.

**Comment by sucht** [comment]
sorry for highjacking, but this is about 9anime not working so...

anyway, i'm getting

streamlink https://9anime.to/watch/detective-conan.myz/9jo760 best
[cli][info] Found matching plugin nineanime for URL https://9anime.to/watch/detective-conan.myz/9jo760
error: Unable to validate JSON: Key 'grabber' not found in {u'error': u'token'}

**Comment by gravyboat** [comment]
@sucht Can you please open a new issue?

**Comment by sucht** [comment]
done, and sorry.
