### ISSUE TITLE
FFmpeg vs. Streamlink: Output file size

### ISSUE THREAD

**Issue by CatPurrfect** [streamlink/streamlink#448]
I am able to successfully download a HLS stream from a .m3u8 file on both FFmpeg and Streamlink. However, the resulting files are of different sizes. The weird thing is that that when analyzing the elementary streams through both MediaInfo and FFmpeg, they are exactly the same. So I hypothesized that the muxing process must be different between the programs.

So, in that case I put my theory to the test. Since Streamlink uses FFmpeg as a muxer, if I were to use the same version for each they would come out identical right? Well, I downloaded the most recent build and linked a path to it in the config file. The outcome was the exact same.

So if anyone can help me I'd greatly appreciate it. I'd just like an explanation as to why the elementary streams are identical, however even when using the same build of FFmpeg within each program I get different file sizes. Thanks.

**Comment by scottbernstein** [comment]
@CatPurrfect:  streamlink does not use ffmpeg for downloading or processing in most cases.  It is only called in some very very specific cases.


ffmpeg will likely add headers to a file to make it a "properly compliant" video, whereas streamlink will generally only write exactly the bits that are passed to it.



________________________________

**Comment by CatPurrfect** [comment]
@scottbernstein I see, thanks for the clarification. So objectively then, what would be a better choice for downloading VODs and such for offline viewing, FFmpeg or Streamlink?

**Comment by beardypig** [comment]
@CatPurrfect they should be equivalent outputs (not identical), so really it's up to you and what ever you want to use or find best :-)

**Comment by CatPurrfect** [comment]
Good to know. Thanks for all the help I really appreciate it! :D

**Comment by garoto** [comment]
> what would be a better choice for downloading VODs and such for offline viewing [...]

`youtube-dl` if supported.
