### ISSUE TITLE
Streamlink 3.2.0 is working in Windows 7

### ISSUE THREAD

**Issue by pboettcher** [streamlink/streamlink#4480]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Sorry for reporting it here. I would like to add it to issue 4055: https://github.com/streamlink/streamlink/issues/4055 but you limited it to collaborators only.

Python 3.9 is working in Windows7 with this DLL:
https://github.com/nalexandru/api-ms-win-core-path-HACK

although it is not officially supported.

I managed to compile it in Visual Studio 2012 after switching platform toolset to v110.

Then I tested the Streamlink 3.2.0 with it and it worked.

**Comment by bastimeyer** [comment]
Not sure why you felt the need to post this.

As you can see here
https://streamlink.github.io/latest/install.html#windows-binaries
there are new installers added, four in total, two of them being based on Python 3.8, which fully supports your outdated and EOL Windows 7 installs.

In case you're wondering why these installers are not linked on the 3.2.0 release notes: the installers have just been added after 3.2.0, but new installers for 3.2.0 have been built.
- https://github.com/streamlink/windows-installer
- https://github.com/streamlink/windows-installer/releases
