### ISSUE TITLE
Bauer - Planet Radio UK

### ISSUE THREAD

**Issue by mpiffa** [streamlink/streamlink#4481]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Bauer media radio stations (UK) will no longer be available on third party sites: they will be available only on their new platform https://planetradio.co.uk/

### Input URLs

- Absolute Radio: https://planetradio.co.uk/absolute-radio/player/
- Kiss Radio: https://planetradio.co.uk/kiss/player/
- Magic Radio: https://planetradio.co.uk/magic/player/
- Planet Rock Radio: https://planetradio.co.uk/planet-rock/player/
- Hits Radio: https://planetradio.co.uk/hits-radio/player/?region=hit
- Greatest Hits Radio: https://planetradio.co.uk/greatest-hits/player/?region=gh0
- Scala Radio: https://planetradio.co.uk/scala-radio/player/
- Jazz FM: https://planetradio.co.uk/jazz-fm/player/

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/3.2.0/CONTRIBUTING.md#plugin-requests

> 7. Sites which don't provide any video streaming content, eg. radio stations
