### ISSUE TITLE
plugins.pulutotv: FAIED TO GARB ALL TV CHANNELS 

### ISSUE THREAD

**Issue by BBBABUHS** [streamlink/streamlink#4483]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

COULD GRAB , I USING USA IP STILL THE SAME

### Debug log

```text
COULD GRAB , I USING USA IP STILL THE SAME
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/1_plugin_issue.yml#L53-L59
https://github.com/streamlink/streamlink/blame/master/.github/ISSUE_TEMPLATE/1_plugin_issue.yml#L14-L17
