### ISSUE TITLE
plugins.youtube: --http-cookie not working anymore on members content

### ISSUE THREAD

**Issue by Benfor4** [streamlink/streamlink#4485]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I have been using streamlink for recording members-only livestreams for a while. Using Chrome I get my `--http-cookie` value by copying the cookie value in the Network tab in Dev Tools but recently this does not seem to work. I have been using the same method as before so I am unsure as to what the cause may be. I have tried other CLI utilities like yt-dlp to access locked content using the same cookie (but as a .txt file) and they perform fine. 

### Debug log

```text
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=cK_L718jsv4
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[cli][info] Waiting for streams, retrying every 1.0 second(s)
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
Interrupted! Exiting...
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.10
[cli][debug] Streamlink: 3.2.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.2.3)
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=cK_L718jsv4
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --logfile=D:\Downloads\streamlink temp\log.txt
[cli][debug]  --player=D:\Programs\VLC\vlc.exe
[cli][debug]  --output=D:\Downloads\streamlink temp\Unarchived_Stream 1.mp4
[cli][debug]  --retry-streams=1.0
[cli][debug]  --stream-segment-attempts=100
[cli][debug]  --stream-segment-threads=3
[cli][debug]  --stream-segment-timeout=600.0
[cli][debug]  --stream-timeout=600.0
[cli][debug]  --hls-segment-stream-data=True
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --http-cookie=[('omitted')]
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=cK_L718jsv4
[plugins.youtube][debug] Missing initial player response
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[cli][info] Waiting for streams, retrying every 1.0 second(s)
[plugins.youtube][debug] Missing initial player response
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[plugins.youtube][debug] Missing initial player response
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
[plugins.youtube][debug] Missing initial player response
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
```

**Comment by bastimeyer** [comment]
The youtube plugin doesn't support any kind of authentication. If you're setting custom http headers or cookies, then you're on your own, and if something changes on the site which has been working for you previously and now stopped working, then you'll have to figure it out yourself. Omitting any useful data is also not great if you're looking for help.

> [cli][debug]  --http-cookie=[('omitted')]

This log message doesn't make any sense btw. `--http-cookie` requires `key=value` argument values, and the data is stored as a list of key+value tuples, not as a list of one-element tuples.
https://streamlink.github.io/latest/cli.html#cmdoption-http-cookie

**Comment by Benfor4** [comment]
Apologies for omitting it. The log for that part is something like this:

`[cli][debug]  --http-cookie=[('VISITOR_INFO1_LIVE', 'value')]`

The command I usually enter for `--http-cookie` is usually `--http-cookie "VISITOR_INFO1_LIVE=value1; NID=value2; ..."` and so on. This is usually enough to start the recording process in the past, however this is not the case recently. Looking clearly at the debug log now, I see my mistake in entering multiple key=value pairs into one `--http-cookie`, as this would end up being stored as one tuple. But am still confused as to why this incorrect method was working in previous releases.

**Comment by bastimeyer** [comment]
> But am still confused as to why this incorrect method was working in previous releases.

Because the `Cookie` HTTP header gets set in the `key1=value1; key2=value2; key3=value3` format, so technically, you can set `value1; key2=value2; key3=value3` as the value of `key1` and it won't make a difference when making a request with this specific header. It messes up the client-side though which also stores individual cookies and their values.

**Comment by Benfor4** [comment]
I've used it correctly now. My debug log now outputs the cookies correctly but I still get the same response:

```
[cli][debug]  --http-cookie=[('VISITER_INFO1_live,'value1'),('NID','value2')]...[('__Secure-3PSIDCC','valueN')]
...
[plugins.youtube][debug] Missing initial player response
[plugins.youtube][error] Could not get video info - UNPLAYABLE: Join this channel to get access to members-only content like this video, and other exclusive perks.
```

**Comment by Kagamia** [comment]
Suggest adding the `bug` tag back here.

**Comment by bastimeyer** [comment]
> `ytInitialPlayerResponse` is not always followed by `var meta = ...`

The regex needs a rather strict anchor because of the dot-match for finding the JSON data (`.*?`) within the entire JS script tag, and this anchor is currently set to `;\s*var\s+meta\s*=`, because that matches the regular page responses from YouTube. As said, the plugin doesn't support authentication, so if you're setting custom headers which lead to the resulting page responses from YouTube differing from the expected ones, then this of course won't be handled by the plugin.
https://github.com/streamlink/streamlink/blob/c319aa445e7577134d61da587c6338730b82a4c8/src/streamlink/plugins/youtube.py#L47

The regex could be fixed by changing the `meta\s*=` part, so that it doesn't strictly expect the `meta` variable name, which should work in both cases and would still be strict enough.

**Comment by Kagamia** [comment]
The change looks good to me.

Thanks for the quick response.
