### ISSUE TITLE
Telegram live streams

### ISSUE THREAD

**Issue by DeaD3R** [streamlink/streamlink#4490]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Not sure if this is applicable. It's an app, though it does have a web version, where you can watch videos, but can't watch live streams there, only in app. Is this possible at all?

### Input URLs

https://t.me/ttteesstt12?livestream

Hard to find a live stream, but it's easy to start your own for testing purposes.

**Comment by mkbloke** [comment]
If it's not possible to watch live streams via either of the Telegram web interfaces (https://web.telegram.org/k/ or https://web.telegram.org/z/) then I don't think this is going to be feasible, as it would seem to mean effectively having to implement a Telegram client, which is far beyond the scope of a Streamlink plugin.

**Comment by mkbloke** [comment]
Just to add to this a little and somewhat correct what I said above:

> If it's not possible to watch live streams via either of the Telegram web interfaces (https://web.telegram.org/k/ or https://web.telegram.org/z/) then I don't think this is going to be feasible

That's not going to make much difference, as it appears [MTProto](https://core.telegram.org/mtproto) runs in the browser to allow E2EE.  MTProto would have to be implemented in the plugin and it does not seem likely that any of the regular contributors to Streamlink will want to spend the time doing it, given there are always existing plugins to fix.  Someone may wish to take it on as an interesting challenge though...
