### ISSUE TITLE
Upgrade failed / 2⇾ 3.2

### ISSUE THREAD

**Issue by emsanator** [streamlink/streamlink#4496]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

On Debian OS with Streamlink 2.0 installed, and I want to upgrade to version 3.2 but 2.0 is installed every time. I couldn't do the uploading. What is the problem?

I did:

```
sudo apt remove streamlink -y
sudo apt update
sudo apt install streamlink -y
streamlink --version
streamlink 2.0.0
```

python:

```
python --version
Python 2.7.16
```

Still 2.0… How can I upgrade to 3.2?

### Debug log

```text
streamlink 2.0.0
```

**Comment by skulblakka** [comment]
Your distributions package is out of date (not surprising for debian). You can install the current version either via [pip](https://streamlink.github.io/install.html#pypi-package-and-source-code) or use the [AppImage](https://streamlink.github.io/install.html#pypi-package-and-source-code).

**Comment by emsanator** [comment]
> Your distributions package is out of date (not surprising for debian). You can install the current version either via [pip](https://streamlink.github.io/install.html#pypi-package-and-source-code) or use the [AppImage](https://streamlink.github.io/install.html#pypi-package-and-source-code).

Thanks
