### ISSUE TITLE
FOX Turkey Channel

### ISSUE THREAD

**Issue by emresaracoglu** [streamlink/streamlink#4499]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hello, 

Could it be an add-on to FOX TV broadcasting in Turkey?

Thank you.

Website: [https://www.fox.com.tr/canli-yayin](https://www.fox.com.tr/canli-yayin)
FOX Turkey Channel
Live broadcast

### Input URLs

https://www.fox.com.tr/canli-yayin

**Comment by back-to** [comment]
https://streamlink.github.io/plugins.html#foxtr

**Comment by emresaracoglu** [comment]
I think you wrote a direct comment without trying it. The current plugin does not record. 
cc @back-to

**Comment by emresaracoglu** [comment]
Please record 5-10 minutes and play the recording in VLC or a different player.

An example video for you:
https://easyupload.io/5rerg0

cc @back-to
