### ISSUE TITLE
Every time I attempt to run Streamlink(GUI or CLI), I get an error about rtmp.

### ISSUE THREAD

**Issue by illegallity** [streamlink/streamlink#4500]
### Checklist

- [x] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

As said in the title, every time I attempt to run Streamlink(GUI or CLI), I get the error `streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe`

I have no idea what RTMP is. This error pops up no matter what I attempt to run with Streamlink, even just `streamlink`. I cannot run `--loglevel debug` because of this. 

Looking into the documentation, support for RTMP was apparently dropped in version 3.0. I am on version 3.2, the latest stable release. However, I'm not even attempting to use RTMP. I haven't written anything about it in the command line. 

![Screenshot](https://user-images.githubusercontent.com/104682141/166106834-7dab5bcc-76fe-45aa-8877-af4801be705a.png)

### Debug log

```text
I cannot run the debug command with this issue.
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/4211#issuecomment-980283012

This will be fixed in the next Windows installer, btw:
https://github.com/streamlink/windows-installer/commit/a44e87660168189f645b7c1f94f90d1d058551f6
