### ISSUE TITLE
source-dist is missing from GitHub release

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4502]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The source-dist tarball was uploaded to PyPI:
- https://github.com/streamlink/streamlink/runs/6243222315?check_suite_focus=true#step:10:87
- https://pypi.org/project/streamlink/4.0.0/#files

But for some reason was not uploaded to the GitHub release:
- https://github.com/streamlink/streamlink/runs/6243222315?check_suite_focus=true#step:9:11
- https://github.com/streamlink/streamlink/releases/tag/4.0.0

The GH release script has not been changed (yet - #4497) and the file name hasn't changed its format, so I wonder what's going on here...

The only change in regards to the release CI config was this, the removal of `.exe,` of the BASH brace expansion:
- https://github.com/streamlink/streamlink/blame/master/.github/workflows/main.yml#L121-L157
- https://github.com/streamlink/streamlink/commit/2dd2f35930143946afe920c084ff910912a41547#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R153

### Debug log

```text
-
```

**Comment by bastimeyer** [comment]
@gravyboat 
Are you fine with me deleting the wheels from the 4.0.1 GH release which were uploaded by mistake?
https://github.com/streamlink/streamlink/pull/4497#issuecomment-1114302021
I feel like this will cause confusion with the move of the Windows installer files, as there are two wheels for Windows due to the additional Windows-specific entry points.

**Comment by gravyboat** [comment]
@bastimeyer Yeah I am fine with it.
