### ISSUE TITLE
Upload directly to the clouds

### ISSUE THREAD

**Issue by emresaracoglu** [streamlink/streamlink#4504]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hello,

Is it possible to upload the video files directly to storage areas such as Azure, AWS, or Google Storage?

Thank you.

**Comment by bastimeyer** [comment]
You'll have to figure it out yourself. You were already told multiple times that this is not the place to ask for generic questions like this. This has literally nothing to do with Streamlink.

https://streamlink.github.io/cli.html#file-output-options

Also no comment about this
> https://github.com/emresaracoglu/streamlink-plugins

**Comment by emresaracoglu** [comment]
> Also no comment about this

You may not know, but I applied to that folder for a file called "generic.py". cc @bastimeyer

**Comment by gravyboat** [comment]
@emresaracoglu You've been warned repeatedly about this and have continued to disrespect members of this community and their time. As such I'm blocking you from this organization.
