### ISSUE TITLE
douyu.com

### ISSUE THREAD

**Issue by YxY-CHN** [streamlink/streamlink#4511]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

The plugin for douyu.com was closed in #3068 before, but recently I found that they have removed the encryption of the streaming link, and now I can get it directly through Chrome's DevTools and play it. Don't know if this will help restore past support?

### Input URLs

1. https://www.douyu.com/99999
2. https://www.douyu.com/525207
3. https://www.douyu.com/5063899

https://www.douyu.com/directory/all

**Comment by mkbloke** [comment]
You can get the playlist via a POST like:
```
curl -d 'v=220120220503&did=cbb1d8f4407ecda8b600eb9f00051601tt=1651521400sign=c2fb45f9a613c1f638f9201a12ab75be' https://www.douyu.com/lapi/live/getH5Play/10576860
```
`v` comes from the page HTML, but there doesn't appear to be a way to anchor it reliably
`did` not sure how this is computed
`tt` appears to be a timestamp - request fails if this is changed but still in the past
`sign` probably a hash of some kind, think it's probably linked to `tt` also

I haven't really looked at the JS yet, but seeing what's embedded in the page HTML makes me think it's likely to be as per https://github.com/streamlink/streamlink/pull/3068#issue-652105680.

**Comment by mkbloke** [comment]
Having just skimmed through #2328, #2943 and #2945, everything looks to be the same now as it was then, so I think this cannot be done easily at the moment.  Closing.

**Comment by YxY-CHN** [comment]
> Having just skimmed through #2328, #2943 and #2945, everything looks to be the same now as it was then, so I think this cannot be done easily at the moment. Closing.

I found a file yesterday from https://github.com/wbt5/real-url/blob/master/douyu.py, which need requirements:

aiohttp==3.7.4
async-timeout==3.0.1
attrs==20.2.0
certifi==2020.6.20
chardet==3.0.4
idna==2.10
multidict==4.7.6
protobuf==3.12.2
pycryptodome==3.9.8
PyExecJS==1.5.1
requests==2.26.0
six==1.15.0
typing-extensions==3.7.4.3
urllib3==1.26.5
yarl==1.5.1
PyExecJS
And nodejs to support javascript.

It can parse out the streaming media address, But they don't seem to know how to dynamically obtain the CDN address of Douyu streaming media to ensure smooth playback.

`python3 douyu.py
Enter Douyu Live Room ID: (Type RoomID)
525207
{'flv': 'http://dyscdnali1.douyucdn.cn/live/525207rUBsWpKrbH.flv?uuid=', 'x-p2p': 'http://tx2play1.douyucdn.cn/live/525207rUBsWpKrbH.xs?uuid ='}
`

The obtained connection only needs to replace the CDN of the header with
vplay1a.douyucdn.cn
vplay3a.douyucdn.cn
hls3-akm.douyucdn.cn
hlsa-akm.douyucdn.cn
hls1a-akm.douyucdn.cn
It can be played normally. Not sure if this method will help the problem.

**Comment by YxY-CHN** [comment]
> Having just skimmed through #2328, #2943 and #2945, everything looks to be the same now as it was then, so I think this cannot be done easily at the moment. Closing.

The address obtained in this way can be played directly without the various parameter restrictions mentioned above, and the parameters after "uuid=" can be directly ignored.

**Comment by mkbloke** [comment]
> import execjs

This is the problem.  Streamlink does not have a JS engine and will not do so any time soon, hence the comment in https://github.com/streamlink/streamlink/pull/3068#issue-652105680.

The PyPI page for the that project states: `This library is no longer maintananced. Bugs are not be fixed (even if they are trivial or essential).`

This is just one reason why such dependencies will not be added to Streamlink.
