### ISSUE TITLE
panda.tv plugin not working with some streams

### ISSUE THREAD

**Issue by JohnDoh666** [streamlink/streamlink#452]
Most streams work, but I get the following error with some:
`streamlink http://www.panda.tv/212274 best
[cli][info] Found matching plugin pandatv for URL http://www.panda.tv/312273
[cli][info] Available streams: hq (worst), ehq (best)
[cli][info] Opening stream: ehq (http)
[cli][error] Could not open stream: Unable to open URL: http://pl8.live.panda.tv
/live_panda/8db3b56f66234f09adb2c970f52f0af3.flv (403 Client Error: Forbidden fo
r url: http://183.232.212.194/pl8.live.panda.tv/live_panda/8db3b56f66234f09adb2c
970f52f0af3.flv)`

**Comment by Erk-** [comment]
There is a open pull request which fixes this problem #410 you can get the file and replace it locally.

**Comment by JohnDoh666** [comment]
Great, thanks for the input.
