### ISSUE TITLE
pbs.org

### ISSUE THREAD

**Issue by kevev** [streamlink/streamlink#4524]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

PBS.org live local channel streams are available here.
Appears to be Widevine keying.

### Input URLs

https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm.mpd
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_audio_2_0_1902600.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_video_1_0_1902600.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_audio_2_0_1902601.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm.mpd
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_video_1_0_1902601.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_audio_2_0_1902602.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm.mpd
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_video_1_0_1902602.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm_audio_2_0_1902603.mp4?m=1648507940
https://klrndt.lls.pbs.org/out/v1/2fe877a725bd4b6aaacba3a4cc54ae12/dash-drm.mpd

**Comment by mkbloke** [comment]
[Item 1](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests=
)

**Comment by kevev** [comment]
Very sorry. I missed that rule. :)
