### ISSUE TITLE
https://www.flextv.co.kr/

### ISSUE THREAD

**Issue by Skuuzy** [streamlink/streamlink#4530]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

A live game&chat platform in South Korea

### Input URLs

https://www.flextv.co.kr/channels/149134/live

**Comment by mkbloke** [comment]
Hmm, this has been requested twice before in #4135 (labeled `wontfix` for reasons unknown) and #4476 (duplicate).
