### ISSUE TITLE
chaturbate.com plugin stopped working

### ISSUE THREAD

**Issue by reasonabledoubt** [streamlink/streamlink#455]
It looks like [chaturbate.py](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/chaturbate.py) stopped working within the last twelve to twenty-four hours.

    $ streamlink chaturbate.com/[name] best
    [cli][info] Found matching plugin chaturbate for URL chaturbate.com/[name]
    error: No streams found on this URL: chaturbate.com/[name]

It was working fine earlier, but all of a sudden it broke.  And it's for any stream, I've tried several.  Several different machines attempting from different locations, etc.  I'm guessing they changed something?

I'd be happy to help test fixes or anything if you need.

**Comment by xkbd** [comment]
#457

**Comment by beardypig** [comment]
#457 has been merged and this should be fixed in master. The Windows nightly build is also available now with this fix.

**Comment by reasonabledoubt** [comment]
I updated to 0838845 and it works great, thanks @rinukkusu, @xkbd, and @beardypig.
