### ISSUE TITLE
shahid.net live streams

### ISSUE THREAD

**Issue by BountyChocolate123456** [streamlink/streamlink#4558]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

https://shahid.mbc.net

MBC Shahid, the first free video-on-demand and leading TV catch-up service in the Middle East & North Africa (MENA) region.

### Input URLs

https://shahid.mbc.net/en/livestream
https://shahid.mbc.net/ar/livestream
https://shahid.mbc.net/fr/livestream

https://shahid.mbc.net/en/livestream/MBC1/livechannel-387238
https://shahid.mbc.net/en/livestream/MBC-Masr/livechannel-387290
https://shahid.mbc.net/en/livestream/MBC-Drama/livechannel-387251
https://shahid.mbc.net/en/livestream/MBC-Iraq/livechannel-387294
https://shahid.mbc.net/en/livestream/MBC5/livechannel-387937
https://shahid.mbc.net/en/livestream/MBC-Masr2/livechannel-387293
https://shahid.mbc.net/en/livestream/MBC3/livechannel-409385

https://shahid.mbc.net/ar/livestream/MBC1/livechannel-387238
https://shahid.mbc.net/ar/livestream/MBC-Masr/livechannel-387290
https://shahid.mbc.net/ar/livestream/MBC-Drama/livechannel-387251
https://shahid.mbc.net/ar/livestream/MBC-Iraq/livechannel-387294
https://shahid.mbc.net/ar/livestream/MBC5/livechannel-387937
https://shahid.mbc.net/ar/livestream/MBC-Masr2/livechannel-387293
https://shahid.mbc.net/ar/livestream/MBC3/livechannel-409385

https://shahid.mbc.net/fr/livestream/MBC1/livechannel-387238
https://shahid.mbc.net/fr/livestream/MBC-Masr/livechannel-387290
https://shahid.mbc.net/fr/livestream/MBC-Drama/livechannel-387251
https://shahid.mbc.net/fr/livestream/MBC-Iraq/livechannel-387294
https://shahid.mbc.net/fr/livestream/MBC5/livechannel-387937
https://shahid.mbc.net/fr/livestream/MBC-Masr2/livechannel-387293
https://shahid.mbc.net/fr/livestream/MBC3/livechannel-409385

**Comment by mkbloke** [comment]
It does not look like this can be implemented due to DRM on both DASH and HLS streams.

**Comment by BountyChocolate123456** [comment]
Thankyou
