### ISSUE TITLE
plugins.twitch: Cant open url

### ISSUE THREAD

**Issue by DRTXY1** [streamlink/streamlink#4569]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hey, when I try to load a twitch stream the following error appears (debug log) It seems to be because no client id is specified.
When I try to record, the terminal immediately closes.
How i van solve this issue?

### Debug log

```text
[Streamlink for Windows v1.0.0 - Git f7ac894]
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/bobross
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (404 Client Error: Not Found for url: https://api.twitch.tv/kraken/users.json?as3=t&login=bobross)
```

**Comment by bastimeyer** [comment]
> [Streamlink for Windows v1.0.0 - Git f7ac894]
> error: Unable to open URL: https://api.twitch.tv/kraken/users.json[](https://api.twitch.tv/kraken/users.json) (404 Client Error

> How i van solve this issue?

By using the latest version and not one which is outdated by several years.
https://streamlink.github.io/install.html
https://streamlink.github.io/changelog.html

**Comment by DRTXY1** [comment]
I#m using [4.1.0-2](https://github.com/streamlink/windows-installer/releases/tag/4.1.0-2) this is the latest version

**Comment by bastimeyer** [comment]
> Streamlink for Windows v1.0.0

You are not.

**Comment by bastimeyer** [comment]
Read this, which may help you resolve your issue:
https://github.com/streamlink/streamlink/issues/4539#issuecomment-1141247448
