### ISSUE TITLE
YouTube Add support for VP9 live streams + 4k

### ISSUE THREAD

**Issue by BountyChocolate123456** [streamlink/streamlink#4570]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

YouTube has recently added 4K streams but streamlink only plays up to 1080p and it's the lower quality h264 codec instead of VP9. It would be nice to be able to play the VP9 streams as they have higher quality/resolution.

```
~$ streamlink 'https://www.youtube.com/watch?v=dRS1ejJmMbs'                  
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=dRS1ejJmMbs
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
~$ 
```

Example video https://www.youtube.com/watch?v=dRS1ejJmMbs

Thanks

**Comment by bastimeyer** [comment]
#2936

**Comment by RichardFevrier** [comment]
Is the linked issue specific to Youtube or it will apply to any stream provider (eg: Twitch)? Thanks

**Comment by bastimeyer** [comment]
This is about the YouTube plugin and how streams are extracted from there. Different sites use different plugin implementations (and/or different stream implementations) and are in the vast majority of cases not limited by the available types of streams.
