### ISSUE TITLE
New Windows portable archives

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4579]
I've been working on new portable archives for Windows
https://github.com/streamlink/windows-installer/compare/master...portable

Please see the build logs and artifacts here:
https://github.com/streamlink/windows-installer/actions/runs/2468830991

Streamlink is currently lacking official non-installer builds for Windows, which makes packaging it a bit difficult for certain package managers, because those projects don't package python properly and they rely on standalone python environments for each application. Having official portable builds fixes that, even if it's a bit silly and redundant. And I guess some people on Windows don't want to use installers.

Please test the portable builds and give feedback.

----

As you can see, the changes are added to the `streamlink/windows-installer` repo, as it already contains lots of shared code for building, and the build config is exactly the same.

This means that the repo will need to get renamed once merged into master, which isn't a big deal, since GitHub will create redirections automatically when moving/renaming repos. The docs here will need to be updated either way. Any suggestions for the new repo name? `streamlink/windows-builds`?

----

Similar to the installers, the portable archives include the `streamlink.exe` and `streamlinkw.exe` executables, which are built the same way, via pynsist's `nsist.commands` module, using the [`distlib` launcher executables](https://github.com/pypa/distlib/tree/0.3.3/distlib).

The archives also bundle ffmpeg. And here's another decision that needs to be made. Since no config file gets written, `--ffmpeg-ffmpeg` will be unset. However, the portable builds of `beardypig/streamlink-portable` have a [wrapper batch script](https://github.com/beardypig/streamlink-portable/blob/96efe8edf51106c38f688f0767a6333326f75f6a/resources/streamlink.bat), but that doesn't work well (argv issues because of `%*`).

`--ffmpeg-ffmpeg` could be added to the executables' header/preamble where it [inserts hardcoded (dynamic) args to `sys.argv` at position 1](https://github.com/streamlink/windows-installer/blob/portable/build-portable-commands.py#L32-L35). That would mean though that it would always override the value read from any config file, if one exists, and it could only be overridden via the command line, as the last argument set determines the final value. I've currently not included/hardcoded the `--ffmpeg-ffmpeg` argument. Any opinions on that? It's a portable build, so I guess it's up to the user to configure it properly.

----

~~Another thing I want to look into later is changing the packaging of the standard library, probably even for the installers. The custom python builds currently don't zip the standard library compared to the official embedded python builds. The zip file only contains compiled modules, but reading and extracting it in memory should always be slower (I guess, no idea if that's true), so I ignored that packaging step in the custom python builds. Extracting thousands of files is painfully slow on Windows/NTFS though, but since it's a one-time operation, having the standard library unpacked (with bytecode files) should be faster when running python. But as said, I don't know.~~
*edit: switched to zipped std lib*

Btw, the python packages that are not part of the standard library are not byte-compiled, because that would require running `python -m compileall -q -f -s "$pkgdir" "$pkgdir"` with the right python interpreter, and we're not building on Windows. The installers do that after extracting the files.

----

The installers also are using the LZMA compression, which yield significantly better results. For compatibility reasons though, I chose zip archives with deflate compression instead of 7zip with LZMA.

**Comment by gravyboat** [comment]
I tested the portable installation and it worked as expected, including picking up my streamlink config. Please don't take this as a negative since you've already done this work, but is this really worth the time and effort to maintain? The standalone executable was always a niche version and I don't know if it's worth the extra maintenance even if it's just updating the builds. Do we really want to deal with this?

**Comment by bastimeyer** [comment]
This is no extra maintenance, because it's based on the same packaging config as the installers, and build-wise, it's just unpacking python+assets archives, installing packages via pip for the specific platform, and assembling executables via pynsist's already existing logic. And since I am responsible for the installers anyway and don't expect anyone else to even look at it, I will include the additional builds in the repo.

As said, having official "portable" builds is helpful for third party packagers on Windows.

> including picking up my streamlink config

This is not what I was talking about in regards to the FFmpeg stuff. Of course it would pick up your config. But that's exactly the point, a missing config means that `--ffmpeg-ffmpeg` is missing, which is a problem for muxed streams. The installers make this rather transparent by always writing/updating the user's config, so everything will work right away.

The question is, what is the best user experience for portable builds and users of packages that are / will be based on thise builds? Is it hardcoding the `--ffmpeg-ffmpeg` parameter into the executables' preamble python code, so that ffmpeg works out-of-the-box but its path can only be overridden on the command line and not via config files? Or is it ignoring the problem and expecting the users to set the parameter themselves?

Either way, I'm going to merge the portable branch later today, rename the repo and publish a new release. After that, I will open a PR here with an update for the docs.

**Comment by gravyboat** [comment]
> The question is, what is the best user experience for portable builds and users of packages that are / will be based on these builds? Is it hardcoding the --ffmpeg-ffmpeg parameter into the executables' preamble python code, so that ffmpeg works out-of-the-box but its path can only be overridden on the command line and not via config files? Or is it ignoring the problem and expecting the users to set the parameter themselves?

My main concern is consideration of the fact it's a portable build. This likely means someone is running it off a USB or system they don't have full write access to. In that case it seems to make more sense to me to pick up as little on the machine itself as possible. I'm not sure if that's reasonable or a typical scenario as I've never used the portable builds in the past. I don't have a good answer to the second portion. It makes sense to me to hard code specifically because it's a portable build, but I don't know enough about the use cases to say what portable users actually need in this sense.
