### ISSUE TITLE
Pandalive username and password

### ISSUE THREAD

**Issue by Eggsmemory** [streamlink/streamlink#4588]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

What is the site about?
streaming site in South Korea

I hope it can add plugin function to login like afreecatv
https://streamlink.github.io/cli.html#afreeca

I tried add login info like streamlink --pandalive-username username --pandalive-password password https://www.pandalive.co.kr/live/play/gusthwkd best -o "/root/stream/test.ts" but respond unrecognized arguments: --pandalive-username --pandalive-password

### Input URLs

https://www.pandalive.co.kr/live/play/gusthwkd

**Comment by mkbloke** [comment]
You could effectively log the Streamlink plugin in if you know the right cookie(s) to pass.  You'd need to investigate that by examining which cookie(s) are set after login in a browser, then you could pass the name/value pair(s) to Streamlink via the [--http-cookie](https://streamlink.github.io/cli.html#cmdoption-http-cookie) option.

**Comment by mkbloke** [comment]
It looks like the pandalive plugin is broken at the moment too.  They are now using usernames rather than IDs.  The POST to https://api.pandalive.co.kr/v1/live/play also needs updating.

**Comment by Eggsmemory** [comment]
Thank you for reply, I am not pro coder. So I don't know how to do. I saw your update, but if it possible to add log in function ?

**Comment by mkbloke** [comment]
I'll look at it in the next week or so if nobody else takes it on.

**Comment by bastimeyer** [comment]
Are there even any streams which require a login? There are no examples posted in the OP.

**Comment by Eggsmemory** [comment]
Pandalive no login page, it use pop up login function. So may need beautifulsoup4 to do this login action.

**Comment by Eggsmemory** [comment]
> Are there even any streams which require a login? There are no examples posted in the OP.

Yes, some stream mark 19+ need to login and watch. Like porn, smoke, drunk.

**Comment by Eggsmemory** [comment]
If you need, just use this link:
https://www.pandalive.co.kr/live/play/wlqo1234

**Comment by Eggsmemory** [comment]
If you need, just use this link:
https://www.pandalive.co.kr/live/play/wlqo1234

**Comment by bastimeyer** [comment]
> Like porn, smoke, drunk

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by Eggsmemory** [comment]
> > 喜歡色情、抽煙、醉酒
> 
> https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

Hello, the porn not you think. The porn is like provocatively. Not nude.

**Comment by Eggsmemory** [comment]
Ok, thank you. I will develop by myself.
