### ISSUE TITLE
Windows Binary link on docs pages is broken

### ISSUE THREAD

**Issue by scottbernstein** [streamlink/streamlink#46]
Link here

resolves to:
https://github.com/chrippa/streamlink/releases/download/v0.0.1/streamlink-v0.0.1-win32-setup.exe

...which doesn't work

Same thing for "Zip Archive":
https://github.com/chrippa/streamlink/releases/download/v0.0.1/streamlink-v0.0.1-win32.zip

**Comment by martinth** [comment]
This is because the windows builds are not done yet. See PR#27.

**Comment by scottbernstein** [comment]
Ok, gotcha.  Thanks.


________________________________

**Comment by scottbernstein** [comment]
For what it's worth, I had trouble using pip to install on win7 (it installed and built fine, but the resulting binary would error out with "failed to create process".

Then I tried the easy_install method which WAS successful for me

**Comment by sbstp** [comment]
What do you mean? You used the `streamlink` program from cmd.exe and it failed?

**Comment by scottbernstein** [comment]
yes, it failed from the command line with an error that said "failed to create process" after I tried PIP install, but then it worked fine with easy_install method.

**Comment by scottbernstein** [comment]
FYI I attempted the same install steps on another machine with the same result.

With PIP install (latest Python 2.7 64 bit build installed on one Windows 7 and one Windows 10 machine), the PIP install claimed to have run successfully, but at a Windows command prompt, typing "streamlink" (which is in my PATH) "Failed to create process" was the response.

Then on both machines, I followed up with easy_install streamlink, which also claimed a successful run.  But when I type streamlink at the command prompt, I get the proper response telling me the basic usage parameters.

So something seems to be wrong with the PIP package for Windows, but not the easy_install package...?

**Comment by skulblakka** [comment]
I just tried installing streamlink via pip on Windows 10 64-bit with Python 3.5 and Windows XP 32-bit with Python 2.7 and it worked without any issues.

**Comment by skulblakka** [comment]
Just tried with Windows 7 64-bit. Worked too.

**Comment by martinth** [comment]
@scottbernstein Could you try reinstalling it with a forced download (`pip uninstall streamlink` followed by `pip install --no-cache-dir streamlink`). 

If the problem persists, please check the content of the `streamlink-script.py` file. You should be able to find it in the same directory that `where streamlink` gives to you. Please verify that the first line points to the correct `python.exe`. It also looks like there is sometimes [an issue](http://stackoverflow.com/a/35246810/20247) when the path to the `python.exe` contains spaces - in that case you need to surround the path with quotes.

**Comment by nshtg** [comment]
@martinth 
I had the same problem and installing python in a path that contains no spaces fixed the bug with `Failed to create process`.

**Comment by martinth** [comment]
Then it seem to be [pip bug #2783](https://github.com/pypa/pip/issues/2783)

**Comment by sbstp** [comment]
Yep looks like it's an issue with the scripts generated by `setuptools`. I think it can be fixed by using a recent version of `setuptools`, what I'm not sure is if that file is created when the package built and pushed to pypi or when it's installed.

**Comment by fresc81** [comment]
What about setting up [Appveyor](https://www.appveyor.com/) as Windows CI to provide binaries automatically?

**Comment by gravyboat** [comment]
@sbstp I think we can close this since the release is now available here: https://github.com/streamlink/streamlink/releases/download/0.0.2/streamlink-0.0.2.exe. The idea to use Appveyor might be a good idea just to make things more automated in the future.
