### ISSUE TITLE
Support multiple --output files

### ISSUE THREAD

**Issue by broizter** [streamlink/streamlink#4603]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I apologize in advance if there is already a way to accomplish this in a good way. I would like to record a livestream and output a file both locally and to a network share. Currently I could accomplish this with "record and pipe" but you lose some functionality doing it this way, and i would prefer to be able to specify --output file1 --output file2.

**Comment by bastimeyer** [comment]
```sh
streamlink ... --stdout | tee file1.ts file2.ts file3.ts >/dev/null
```

https://streamlink.github.io/cli.html#cmdoption-stdout
https://man.archlinux.org/man/tee.1

**Comment by bastimeyer** [comment]
This is such a niche feature that I don't think it makes sense having it implemented in Streamlink and making the CLI implementation even more messy than it already is. You'll have to find a nother solution.

**Comment by broizter** [comment]
Alright thanks!
