### ISSUE TITLE
plugins.twitcasting: Download ends abruptly with an error: string argument without an encoding

### ISSUE THREAD

**Issue by nurupo** [streamlink/streamlink#4604]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Sometimes a download would end abruptly with an error. I can't reliably reproduce it, so I don't have `--loglevel debug` logs, but I do have the error message.

### Debug log

```text
[plugins.twitcasting][error] string argument without an encoding
[plugin.api.websocket][error] cannot join current thread
```

**Comment by nurupo** [comment]
I'm running it with `--loglevel debug` now, so when I encounter this bug again I would be able to provide the logs.

**Comment by back-to** [comment]
> I'm running it with --loglevel debug now, so when I encounter this bug again I would be able to provide the logs.

it will be the same as `string argument without an encoding`
not that useful

---

if you could change this

https://github.com/streamlink/streamlink/blob/9e4a6577fa1d7efa9b828b13de18b9508b9599de/src/streamlink/plugins/twitcasting.py#L105-L110=

to

```py
    def on_message(self, wsapp, data: str) -> None:
        try:
            self.buffer.write(data)
        except Exception as err:
            log.error(err)
            print("---")
            print(data)
            print("---")
            self.close()
```

it would be more useful

**Comment by nurupo** [comment]
Ok, edited the file. Can I remove the `--loglevel debug` flag or is it required for this codepath to be hit?

**Comment by bastimeyer** [comment]
> Can I remove the `--loglevel debug` flag

Debug logging is required for posting issues because - as explained in the issue template/form - it includes the version number and your informations about your OS, which is important for diagnosing issues. The remaining debug log should be irrelevant for this issue here.

The issue seems to be related to string message data returned by `websocket-client`'s `on_message` callback. Streamlink requires binary `bytes` data in its buffer, but the websocket message data is a UTF-8 `string` which gets converted back to `bytes`, which requires an encoding parameter that's missing.

From what it looks like, the plugin should implement the `on_data` callback instead of `on_message`, because `on_data` supports both binary data and text data, according to the op-code of the websocket response frame. It's also possible that there's an issue with incomplete responses, which are handled by `on_cont_message` and `on_data`. I will have a look at this later.

**Comment by nurupo** [comment]
Here are the version numbers:

```
[cli][debug] OS:         Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.26.0), Socks(1.7.1), Websocket(1.2.3)
```

Debian 11 x86_64, using Debian's python 3.9 with streamlink installed inside a virtualenv via pip.

**Comment by nurupo** [comment]
Managed to reproduce it, here is what I got in the logs using the edit @back-to suggested (I have redacted a some identifiers):

```
[plugins.twitcasting][debug] Live stream info: {'movie': {'id':[REDACTED], 'live': True}, 'fmp4': {'host': '61-206-39-153.twitcasting.tv', 'proto': 'wss', 'source': False, 'mobilesource': False}}
[plugins.twitcasting][debug] Real stream url: wss://61-206-39-153.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][info] Available streams: base (worst, best)
[cli][info] Opening stream: base (stream)
[cli][info] Writing output to
[REDACTED]
[cli][debug] Checking file output
[plugin.api.websocket][debug] Connecting to: wss://61-206-39-153.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][debug] Pre-buffering 8192 bytes
[plugin.api.websocket][debug] Connected: wss://61-206-39-153.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][debug] Writing stream to output
[plugins.twitcasting][error] string argument without an encoding
---
{"type":"event","code":100,"text":""}
---
[plugin.api.websocket][error] cannot join current thread
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

and

```
[cli][info] Found matching plugin twitcasting for URL https://twitcasting.tv/[REDACTED]
[plugins.twitcasting][debug] Live stream info: {'movie': {'id': [REDACTED], 'live': True}, 'fmp4': {'host': '211-133-247-142.twitcasting.tv', 'proto': 'wss', 'source': False, 'mobilesource': False}}
[plugins.twitcasting][debug] Real stream url: wss://211-133-247-142.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][info] Available streams: base (worst, best)
[cli][info] Opening stream: base (stream)
[cli][info] Writing output to
[REDACTED]
[cli][debug] Checking file output
[plugin.api.websocket][debug] Connecting to: wss://211-133-247-142.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][debug] Pre-buffering 8192 bytes
[plugin.api.websocket][debug] Connected: wss://211-133-247-142.twitcasting.tv/ws.app/stream/[REDACTED]/fmp4/bd/1/1500?mode=base
[cli][debug] Writing stream to output
[plugins.twitcasting][error] string argument without an encoding
---
{"type":"status","code":504,"text":"End of Live"}
---
[plugin.api.websocket][error] cannot join current thread
error: Error when reading from stream: Read timeout, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
The issue has already been fixed. Use the latest development version.
https://streamlink.github.io/latest/install.html
