### ISSUE TITLE
Not sure where else to ask this Question

### ISSUE THREAD

**Issue by shitbub** [streamlink/streamlink#461]
My apologies if this isn't the appropriate forum to ask this question, but im having troubles getting streamlink to even work for me.  I used to use linkstreamer, but i read that it has forked into streamlink.  So installed it streamlink as well as installing the most recent Python.  

When i typed "pip install streamlink" in my command prompt, i get the following text in red.  Which i assume means the install was not successful

**Command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\dude\\appdata\\local\\temp\\pip_build_dude\\pycryptodome\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\dude\appdata\local\temp\pip-udkbkg-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\dude\appdata\local\temp\pip_build_dude\pycryptodome
Storing debug log for failure in C:\Users\dude\pip\pip.log**

I'm clueless when it comes to this stuff, any idea what im doing wrong?

I get the text below after I type the following into my command prompt

**C:\Users\dude>streamlink twitch.tv/nalcs1**

**Traceback (most recent call last):
  File "C:\Python27\Scripts\streamlink-script.py", line 5, in <module>
    from pkg_resources import load_entry_point

  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()

  File "C:\Python27\lib\site-packages\pkg_resources.py", line 432, in _build_master
    ws.require(__requires__)

  File "C:\Python27\lib\site-packages\pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))

  File "C:\Python27\lib\site-packages\pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pycryptodome==3.4.3**

**Comment by beardypig** [comment]
Which version of Windows are you using? Have you tried using the Windows installer instead of using `pip`?

**Comment by karlo2105** [comment]
I have latest Python 2.7. You need to install GIT : `https://git-scm.com/`
Then in command prompt, from git.exe folder : 

`pip install --no-cache-dir -U git+https://github.com/streamlink/streamlink.git`
Streamlink folders shall be located in `C:\Program Files\Python27\Lib\site-packages`

When you update streamlink it's better to first uninstall old version with following command : 
`pip uninstall streamlink`

**Comment by shitbub** [comment]
@beardypig, I'm on Windows 10, I've tried the installer version as well (which is this exe i assume?)
**streamlink-0.2.0.exe**

When i type this into the command prompt
**C:\Users\Dude>streamlink twitch.tv/eleaguetv**

I get
**error: No plugin can handle URL: --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe**

**Comment by shitbub** [comment]
@karlo2105, im just trying to use streamlink, i really don't have the skillset to contribute on the coding side.  Do i still need to to install GIT.   Also does my Python27 folder have to be in "Program Files"?  I currenlty just have it on my C:

**Comment by beardypig** [comment]
Have you installed a nightly version before? You shouldn't have `ffmpeg-ffmpeg` line in your streamlinkrc file (%APPDATA%\Streamlink\Streamlinkrc). You can try installing the latest build: [streamlink-latest](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe),which should work fine.

**Comment by shitbub** [comment]
yup the streamlink-latest worked!  Thanks so much for the help beardypig.  

P.S One other thing to mention, i think i saw it in another post, is that AVG keeps flagging the uninstaller.

**Comment by beardypig** [comment]
That was in #251? You can use www.virustotal.com to test the uninstaller if you want to confirm that other AV software doesn't detect it as a virus/malware. It is most likely a false positive, but you should double check none the less. 

If you think you're issue has been resolved could you close this issue? Thanks.

**Comment by gravyboat** [comment]
It's probably worth reporting to AVG that it isn't a virus, might just be they don't have it in their database yet.

**Comment by beardypig** [comment]
Seems like the original issue has been solved, so I'm going to close this.
