### ISSUE TITLE
Mega Chile

### ISSUE THREAD

**Issue by jiglesiasc** [streamlink/streamlink#4619]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Streaming website of the public Chilean TV channel Mega.

Mega belongs to Grupo Bethia and Warner Bros. Discovery Americas

Mega provides multiple types of self-made content like news, morning shows and series but also provides imported content from different countries. It is probably geo-locked to be watched only in Chile but I don't have the means to test this.

### Input URLs

1. https://www.mega.cl/senal-en-vivo/

**Comment by LaneSh4d0w** [comment]
It doesn't need a separate plugin since it seems that it uses MDSTRM.
![image](https://user-images.githubusercontent.com/30985701/185679793-c85341d9-bffd-4346-b5e8-9eaa11e4e32b.png)

**Comment by back-to** [comment]
it uses some other version of `mdstrm`,
not https://github.com/streamlink/streamlink/blob/8a7717f549b3f67fe3d596dbe1e562f17d48a8a8/src/streamlink/plugins/mdstrm.py

as it is geo blocked, I don't think we have some one who will add it.

**Comment by LaneSh4d0w** [comment]
For sure, the only way to make it work would be to use a proxy to get the link based on the country.

Good deduction nonetheless @back-to , wouldn't think they would have a special version of their streaming system for geo-blocked links, thought the main difference relied on the answer.
