### ISSUE TITLE
Mozilla & Chrome addons?

### ISSUE THREAD

**Issue by XanderGS** [streamlink/streamlink#462]
So livestreamer had some useful mozilla & chrome addons which could open twitch video links with a simple mouse2 button, select open in livestreamer and quality. Any plans to have that with streamlink too?

**Comment by gravyboat** [comment]
I don't think we've talked to whoever maintains those addons about doing so. If you want to reach out to them please feel free to do so.

**Comment by beardypig** [comment]
It sounds like it's already possible to use this addon (https://github.com/IsSuEat/open-livestreamer-firefox-addon/) with streamlink, by updating the path to livestreamer to point at streamlink. I have tried it, but it sounds like it'd work...

**Comment by roshavagarga** [comment]
@XanderGS @gravyboat @beardypig I'd recommend looking at Twitch Now, it has support for livestreamer, I think that by pointing to the streamlink folder it should work theoretically, but when I did nothing happened. Might have done it wrong.

**Comment by garoto** [comment]
Using Firefox on Windows, the "Open With..." extension with a manually created entrie and with the following command line: `cmd.exe /c start /b streamlink.exe %s`

Not very elegant perhaps, but gets the job done.

**Comment by gravyboat** [comment]
Closing this out since we don't maintain those, people can still find this issue and modify their path as needed. Thanks everyone for your input and workarounds.
