### ISSUE TITLE
plugins.rtve: live streams broken

### ISSUE THREAD

**Issue by Lordwinder** [streamlink/streamlink#4622]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Since 22 June 2022 the "live" channels have stoped working.   vod works perfect
Example
streamlink --stdout --default-stream best --url  https://www.rtve.es/play/videos/directo/canales-lineales/la-1
Error message:
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/directo/canales-lineales/la-1
error: No playable streams found on this URL: https://www.rtve.es/play/videos/directo/canales-lineales/la-1

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://www.rtve.es/play/videos/directo/canales-lineales/la-1
[cli][debug]  --loglevel=debug
[cli][debug]  --stdout=True
[cli][debug]  --url=https://www.rtve.es/play/videos/directo/canales-lineales/la-1
[cli][debug]  --default-stream=['best']
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin rtve for URL https://www.rtve.es/play/videos/directo/canales-lineales/la-1
[plugins.rtve][debug] Found content with id: 1688877
error: No playable streams found on this URL: https://www.rtve.es/play/videos/directo/canales-lineales/la-1
```

**Comment by bastimeyer** [comment]
Fixing the live streams is pretty simple. I have already done that on my local branch. I haven't had a closer look at the VODs yet though. There seem to be two kinds of VODs, regular short videos and movies with subtitles, but they all appear to be working via the regular HLS stream URL format the live streams are using.

The plugin currently implements lots of stuff which seems to be pointless now (ZTNRClient, CDN stuff, video API), but as said, I haven't had a closer look yet at the other kind of content.
https://github.com/streamlink/streamlink/blob/cc455586c55ea9bdbcd3a4c58f62b9bf9a0dddd0/src/streamlink/plugins/rtve.py

**Comment by Lordwinder** [comment]
Great, thanks, i will wait until the modification is upload to the main branch. Since the link provided only links the original one and not the modified. Thanks again.

**Comment by bastimeyer** [comment]
I had another look at this.

As said, updating the live streams is fairly easy.

The VODs and movies however are accessed differently now via their website: obfuscated HLS URLs are embedded in PNG files with custom base64 alphabets. The HLS URL obfuscation requires re-implementing lots of JS code in Python, from the `rtve/ztnrThumbnail` module of this JS file:
https://js2.rtve.es/player/pf_video.js

The old API which the plugin is currently using for getting VOD HTTP URLs seems to be still working for whatever reason, but it's likely that it won't stay available for long.

I will submit a PR for updating the live streams later today or tomorrow. It's not worth the time implementing the de-obfuscation of VOD HLS URLs. Also no idea about the available movies and their subtitles.
