### ISSUE TITLE
retries on the HLS playlist_reload?

### ISSUE THREAD

**Issue by mrawji** [streamlink/streamlink#463]
First off, THANK YOU! I was pulling HLS streams via FFMPEG before and they'd behave poorly after about 2 hours. Streamlink has been perfect on that front!

Here's my question.. I was streaming and the reload_playlist method received an timeout about 1 hour into the stream. It's most likely a transient issue with the server / network / internet / etc... this caused streamlink to basically stop. Is there a way to set retries on that?

Thanks!

**Comment by beardypig** [comment]
There is no retry code in the `reload_playlist` method, but there should be!

**Comment by scottbernstein** [comment]
+1 on adding retry code around the reload_playlist method, and making the number of retires configurable from the command line like other retries.

________________________________

**Comment by beardypig** [comment]
Since #522 this should be fixed.
