### ISSUE TITLE
No playable streams found on this URL, MacBook Pro 2017; Catalina 

### ISSUE THREAD

**Issue by warawara-utsu** [streamlink/streamlink#4631]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

30, June 2022, Twitch VOD isn't working for me on my mac Catalina version 10.15.7
Example:
% streamlink -l debug twitch.tv/waterswing
Error:
[cli][info] Found matching plugin twitch for URL twitch.tv/waterswing
error: No playable streams found on this URL: twitch.tv/waterswing

### Debug log

```text
[cli][debug] OS:         macOS 10.15.7
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/waterswing
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin twitch for URL twitch.tv/waterswing
[plugins.twitch][debug] Getting live HLS streams for waterswing
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
error: No playable streams found on this URL: twitch.tv/waterswing
```

**Comment by bastimeyer** [comment]
> Twitch VOD isn't working

> streamlink -l debug twitch.tv/waterswing

You're not trying to watch a VOD, you're trying to watch a live stream which is offline.

VODs of this channel are working perfectly fine:

```
$ streamlink -l debug 'https://www.twitch.tv/videos/1518110951'
[cli][debug] OS:         Linux-5.18.8-1-git-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.1.0+38.g1622010c
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.0
[cli][debug]  websocket-client: 1.3.2
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/videos/1518110951
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/videos/1518110951
[plugins.twitch][debug] Getting HLS streams for video ID 1518110951
[utils.l10n][debug] Language code: en_US
Available streams: audio, 160p30 (worst), 360p30, 480p30, 720p60, source (best)
```

**Comment by Kebbiin** [comment]
Oh! Thank you.
I didn't know you had to individually type the VOD of the streamer and that was for the livestreams. I'm fairly new to this, so sorry for the inconvenience. Thank you again!
