### ISSUE TITLE
plugins.trovo: API error(s): {"ret":10505,"msg":"Data not exist"} when using plugin

### ISSUE THREAD

**Issue by Floflo10** [streamlink/streamlink#4635]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When trying to use streamlink with any Trovo stream, I get a {"ret":10505,"msg":"Data not exist"}
It seems they change something when adding their Discord-Like interface

Step 
1. Get any stream URL from Trovo
2. Try streamlink https://trovo.live/s/TheALounge/221604214 

(If it can help, on another Github project, I found a similare case : https://github.com/yt-dlp/yt-dlp/issues/4135)

### Debug log

```text
streamlink https://trovo.live/s/TheALounge/221604214 best --loglevel debug -o "F:\Live\Theta di Gon %DATE:~-4%-%DATE:~-7,2%-%DATE:~-10,2% %TIME::=-% Bis.mp4" --retry-streams 4 --hls-segment-threads 4

[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.1.0
[cli][debug] Requests(2.27.1), Socks(1.7.1), Websocket(1.3.2)
[cli][debug] Arguments:
[cli][debug]  url=https://trovo.live/s/TheALounge/221604214
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=F:\Live\2022-07-03 14-18-25,94 Bis.mp4
[cli][debug]  --retry-streams=4.0
[cli][debug]  --hls-segment-threads=4
[cli][debug]  --ffmpeg-ffmpeg=F:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin trovo for URL https://trovo.live/s/TheALounge/221604214
[plugins.trovo][error] API error(s): {"ret":10505,"msg":"Data not exist"}
[cli][info] Waiting for streams, retrying every 4.0 second(s)
```

**Comment by mkbloke** [comment]
It looks like they changed the URL path a little bit for live streams.  It is now prepended with `s/` - it wasn't originally.  It's an easy fix.

Can you test or provide links to some past streams and clips, please?  It seems that Trovo no longer allows people to obtain the share URLs for these without logging in - and I do not have an account.  Thanks.

**Comment by Floflo10** [comment]
Thanks for your fast reply !

Oh yes, you're totaly true, I missed that new `s/` !
Don't know if it's a "good pratice" in this case but adding `s/` at line 20 seem working.

Link to a random VOD : https://trovo.live/s/I0I_TvinK_I0I/549793380933?vid=ltv-109321461_109321461_387702302796102819

Thanks again to you !

**Comment by mkbloke** [comment]
Thanks.
