### ISSUE TITLE
Setting login data for rtmp-proxies

### ISSUE THREAD

**Issue by Jackels** [streamlink/streamlink#464]
For http proxies you can do something like this
--http-proxy "http://USERNAME:PASSWORD@proxyhost:proxyport"

but how do you do this for rtmp-proxies?

**Comment by beardypig** [comment]
The `--rtmp-proxy` setting is passed directly to `rtmpdump` via the `-S/--socks` option. `rtmpdump` only supports SOCKS4 which does not support authentication. So long story short, you can't :-(

**Comment by beardypig** [comment]
You might be able to use something like `proxychains`, but we don't support it.

**Comment by gravyboat** [comment]
I'm going to close this one for now since it isn't something we can do, thanks for the report @Jackels and thanks for weighing in @beardypig.
