### ISSUE TITLE
plugins.vidio: streams broken

### ISSUE THREAD

**Issue by BBBABUHS** [streamlink/streamlink#4640]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello Admin Could you guys take a look vidio plugin it is broken now.

Unable to open url
403 Client Error Forbidden for url
Here is the the link 
https://www.vidio.com/live/204-sctv (403 Client Error: Forbidden for url: https://www.vidio.com/live/204-sctv)

https://www.vidio.com/

### Debug log

```text
Hello Admin Could you guys take a look vidio plugin it is broken now.

Unable to open url
403 Client Error Forbidden for url
Here is the the link 
https://www.vidio.com/live/204-sctv (403 Client Error: Forbidden for url: https://www.vidio.com/live/204-sctv)

https://www.vidio.com/
```

**Comment by mkbloke** [comment]
Please provide debug log output, as specified in the issue template and update your post accordingly.

I cannot reproduce this with the URL you have specified, the plugin is fine working for me.

**Comment by bastimeyer** [comment]
No, the plugin is broken.

The website is now using DASH streams for live streams, and HLS stream for VODs. Acquiring a token is now different, and VODs don't seem to be requiring a token at all.

I've already got a fix. Ideally, I would like to use HLS streams for live streams as well, which seems to be possible, but I don't know how to apply the token to the stream URLs. The current implementation simply sets the token as the entire query string, but that only gives access to the multivariant playlist, and media playlists stay unavailable. I've tried adding the token to the media playlist URLs, similar to how the ltv_lsm_lv plugin is doing it, either by setting the token as query string, and also in the format of the DASH token, but to no success.

**Comment by bastimeyer** [comment]
That explains why the access token wasn't working for some HLS streams. My PR #4641 fixes this by always using DASH streams for live streams, which their website is using and which are working fine. The alternative would be checking each HLS media playlist for availability and removing inaccessible streams, which is slow. The token stuff also has changed, so a rewrite of the plugin should be done anyway.

**Comment by BBBABUHS** [comment]
http://free.fullspeed.tv/iptv-query?streaming-ip=https://vidio.com/live/204-sctv

**Comment by BBBABUHS** [comment]
still the same return 403 @bastimeyer

**Comment by mkbloke** [comment]
Don't post new plugin issues on old closed issues, raise a new issue.

> http://free.fullspeed.tv/iptv-query?streaming-ip=https://vidio.com/live/204-sctv

Not a valid URL supported by any Streamlink plugin.

When you create a new issue, post DEBUG LOG output.
