### ISSUE TITLE
cli: threaded read_stream() for undelayed process termination

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4642]
[`streamlink_cli.main.read_stream()`](https://github.com/streamlink/streamlink/blame/4.1.0/src/streamlink_cli/main.py#L372-L431) is in need of an update. It's the heart of the `streamlink_cli` package and it's responsible for reading stream data and writing it to the output.

The issue is that reading stream data is single-threaded by reading from a simple `stream.read()` iterator, and the polling of the player process for termination or rather the detection of the end of the write-pipe thus depends on the stream-buffer's thread locks while reading the stream data, which is pretty bad when read calls stall for several seconds due to an empty stream buffer while waiting for new data.

What this means is that closing the player often doesn't get detected immediately, and ending the streamlink process takes an unnecessarily long time, as it's waiting for the next stream data first before it can continue exiting gracefully. This is especially noticable when reading HLS streams with long segment durations and long playlist refresh times.

The download-progress output is also tightly coupled with the current stream iterator and its updates are therefore timely inconsistent, which is bad.

----

What should be done in order to fix this is

1. Wrap the stream reader in a separate thread. This can already be done via `streamlink.stream.wrappers.StreamIOThreadWrapper`, but it'd add a secondary stream buffer, which is probably not ideal. I haven't had a closer look at this yet.
2. Poll the player process for termination in a separate thread as long as the stream reader thread is alive. Abort the stream reader when the player was closed.
3. Move the download progress output into a separate thread, so it can update in consistent time intervals instead of relying on the pace of the stream reader.

I have already experimented with that, and apart from the progress output which would need some code refactoring, streams get closed immediately which previously caused a delay of several seconds. The challenge however is implementing this so that current functionality doesn't break, because there are no tests written for that (the sparse test coverage comes as a side effect from mocked cmdline tests).

**Comment by WolfganP** [comment]
It sounds bad but it will only happen on twitch streams with ads being filtered. 
Now it's happening on every single stream no matter what site is being processed by streamlink, so for me this enhancement will be positive overall.

**Comment by bastimeyer** [comment]
> it will only happen on twitch streams with ads being filtered.

There are several other plugins which also filter out HLS segments. And there's also the CLI parameter for filtering.

> it's happening on every single stream

Yes, as explained in the OP. A fix of the `read_stream()` method would mean that closing the player gets detected "immediately", with a short delay due to the process polling. The only thing that currently can't easily get fixed are ongoing HTTP requests, which means when closing the player, the stream's `close()` call will still wait until all remaining HTTP requests have finished and all thread pool threads have terminated (the writer thread blocks on close). For segmented streams with small segments (talking about size), this is no problem, but for streams with "future segments" where the HTTP request gets made ahead of time, this still is a problem. I believe we'd need to update the `iter_content` loop of the HLS stream implementation and check whether the stream has been closed on each individual chunk iteration, which is a bit wasteful. If this doesn't work, then `requests` would need to get replaced by `httpx`.

----

I already have a local fix here that doesn't involve using the `StreamIOThreadWrapper`. That namely would mean copying data from buffer to buffer to buffer, which is stupid, and it also doesn't work with paused streams which I wasn't aware of initially.

I don't know yet though whether I want to write some tests. There are no tests for the `read_stream` method at all, and writing ones requires writing a lot of mocked code for the two additional threads, the player polling and the progress output.

I also have a commit with a refactor and cleanup of the filtering logic which abstracts it from the HLS implementation, because it actually doesn't belong there. Also not sure yet if I want to include it in a PR for this fix. It should probably be submitted as a separate pull request.
