### ISSUE TITLE
(Ubuntu 22.04) No plugin can handle URL ---

### ISSUE THREAD

**Issue by mrkapqa** [streamlink/streamlink#4661]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

hello,

link would not play with streamlink v.4.2.0 and mpv 0.34 (from Ubuntu repository) and youtube-dl (latest)

https://www.youtube.com/watch?app=desktop&v=9g4HJGFvQhY

`streamlink -p mpv https://www.youtube.com/watch?app=desktop&v=9g4HJGFvQhY
[1] 8311
rich@rich-MS-7A38:~$ error: No plugin can handle URL: https://www.youtube.com/watch?app=desktop
`

playing file directly with mpv also gives error

`mpv https://www.youtube.com/watch?app=desktop&v=9g4HJGFvQhY
[1] 8286
rich@rich-MS-7A38:~$ [ytdl_hook] ERROR: Unsupported URL: https://www.youtube.com/ 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.`

### Debug log

```text
[cli][debug] OS:         Linux-5.15.0-41-generic-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.4
[cli][debug] Streamlink: 4.2.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug]  importlib-metadata: 4.6.4
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?app=desktop
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
error: No plugin can handle URL: https://www.youtube.com/watch?app=desktop
```

**Comment by bastimeyer** [comment]
> `streamlink -p mpv https://www.youtube.com/watch?app=desktop&v=9g4HJGFvQhY`

> ```
> [cli][debug] Arguments:
> [cli][debug]  url=https://www.youtube.com/watch?app=desktop
> ```

Your command line shell is interpreting `&` as the fork operator. You need to escape it or put the entire parameter in quotes.
https://askubuntu.com/questions/50898/how-to-skip-the-evaluation-of-ampersand-in-command-line
