### ISSUE TITLE
Getting 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by kishan167** [streamlink/streamlink#4666]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Im Sorry as i didnt know where to post Question related to Streamlink giving Error 

**URL:** https://www.hotstar.com/in/tv/bigg-boss-jodigal/1260061550/demons-vs-angels/1100057455

**M3U8:** https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2

**Full CMD Used:** Proxy username and password Removed
streamlink --hls-segment-attempts 10 -l debug --hls-timeout 600000 -o "D:\Downloads\Bigg Boss JodigalS01EP0.ts" --http-proxy "http://142.93.217.61:6060" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0" --http-header "Cookie=hs_uid=9acd7dd1-e4c6-4355-a94b-687b28fef333; ajs_user_id=%22dd6958a48d114e9381ffb0c0ebf4481b%22; ajs_group_id=null; ajs_anonymous_id=%22cd686902-7a49-4f80-9af5-97b273c79f4f%22; _gcl_au=1.1.1661454995.1658201554; _ga_QV5FD29XJC=GS1.1.1658220631.2.1.1658220790.47; _ga=GA1.2.428367852.1658201555; _fbp=fb.1.1658201558664.2111183921; _gid=GA1.2.67967565.1658201559; _clck=11piuvm|1|f3a|0; _clsk=1mhb1km|1658220792147|4|0|h.clarity.ms/collect; hdntl=exp=1658288608~acl=%2f*~data=hdntl~hmac=3e52ea87225a84c18a8b7265307bf6f17b1d2a886bfde908720642a02bc0d9b2; _uetsid=6e3ddec0071311ed9f50212cce0ed0c7; _uetvid=6e3dde70071311eda0409d0a6d59fdc6; _gat_UA-53733575-1=1" --http-header "Referer=https://www.hotstar.com/" "https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2" best

**Error:**
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.6
[cli][debug] Streamlink: 4.2.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin hls for URL https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2
[plugins.hls][debug] URL=https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2; params={}
[utils.l10n][debug] Language code: en_AU
[cli][info] Available streams: 180p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[stream.hls][debug] Reloading playlist
[cli][error] Try 1/1: Could not open stream <HLSStream('https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/video_fhd_h264_sdr_1643796796827-4/index.m3u8', 'https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2')> (Could not open stream: Unable to open URL: https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/video_fhd_h264_sdr_1643796796827-4/index.m3u8 (403 Client Error: Forbidden for url: https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/video_fhd_h264_sdr_1643796796827-4/index.m3u8))
error: Could not open stream <HLSStream('https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/video_fhd_h264_sdr_1643796796827-4/index.m3u8', 'https://hses5.hotstar.com/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/master-859aabfa4b.m3u8?hdnea=st=1658220680~exp=1658221280~acl=/videos/hotstarint/1260061550/1100057455/v3/1643796796827/184d287bc9fb331d44df77fbd5cbd155/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b7d3f1449f5db4f998fbc22c7101574f772c2ac5b725522a9d24ee5b13139fb2')>, tried 1 times, exiting

**Comment by kishan167** [comment]
after reinstalling im getting new Error wwdh is going on?

C:\Users\BosS>streamlink -l debug -o "D:\Downloads\Bigg Boss JodigalS01EP0.ts" --http-proxy "http://142.93.217.61:6060" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0" --http-header "Cookie=hs_uid=9acd7dd1-e4c6-4355-a94b-687b28fef333; ajs_user_id=%22dd6958a48d114e9381ffb0c0ebf4481b%22; ajs_group_id=null; ajs_anonymous_id=%22cd686902-7a49-4f80-9af5-97b273c79f4f%22; _gcl_au=1.1.1661454995.1658201554; _ga_QV5FD29XJC=GS1.1.1658220631.2.1.1658222996.60; _ga=GA1.2.428367852.1658201555; _fbp=fb.1.1658201558664.2111183921; _gid=GA1.2.67967565.1658201559; _clck=11piuvm|1|f3a|0; _clsk=1mhb1km|1658222998079|13|0|h.clarity.ms/collect; hdntl=exp=1658288042~acl=%2f*~data=hdntl~hmac=0aaad43c00cc4c8d5b4c0d7ffcdb21fa021f11fde64e1e2b3a5c675dfe168d2c; _uetsid=6e3ddec0071311ed9f50212cce0ed0c7; _uetvid=6e3dde70071311eda0409d0a6d59fdc6" --http-header "Referer=https://www.hotstar.com/" "https://hses4.hotstar.com/videos/hotstarint/1260061550/1100054280/1620492267284/ff468f9456baf4c6ecad71e32c17ddb6/master-aae2a4f427-phone.m3u8?hdnea=st=1658222893~exp=1658223493~acl=/videos/hotstarint/1260061550/1100054280/1620492267284/ff468f9456baf4c6ecad71e32c17ddb6/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b06efeb2b705452e1bab4e66cb4b1c6c4896e28243b37ba0ed73e1561aa9476f" best
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: https://hses4.hotstar.com/videos/hotstarint/1260061550/1100054280/1620492267284/ff468f9456baf4c6ecad71e32c17ddb6/master-aae2a4f427-phone.m3u8?hdnea=st=1658222893~exp=1658223493~acl=/videos/hotstarint/1260061550/1100054280/1620492267284/ff468f9456baf4c6ecad71e32c17ddb6/*~data=ip=lkvxvRomM5KqojaFIn2ojw-userid=AOnmpIfBbrIKOKSP1kJRSMS9R8KnnQ7q4pCWLUcSm70F-did=OJb3bpx2wNqJ6lvWjQMKFkZtcpO4AcsPT04VkZyFYMFAAUA0orcBzZI-cc=in-~hmac=b06efeb2b705452e1bab4e66cb4b1c6c4896e28243b37ba0ed73e1561aa9476f best

Before it was 403 Client Error but its saying unrecognized arguments

**Comment by bastimeyer** [comment]
> Im Sorry as i didnt know where to post Question related to Streamlink giving Error

Like here, 6 hours ago? https://github.com/streamlink/streamlink/discussions/4665

> [cli][debug] Streamlink: 4.2.0
> [cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)

This is not the debug log format of Streamlink 4.2.0. You are mixing up something here.

> [cli][info] Found matching plugin hls for URL ...

No support for custom HLS streams. If the server is responding with 4xx errors, then you're probably missing some HTTP headers or the request is simply invalid.
