### ISSUE TITLE
More customizable quality

### ISSUE THREAD

**Issue by HulioEglesias** [streamlink/streamlink#4675]
If I understand correctly, I can't choose best resolution with 30fps(when available 60fps). Can you add that option?

**Comment by bastimeyer** [comment]
Post the **full debug log output** of what you're trying to do.

**Comment by HulioEglesias** [comment]
Any stream on the twitch, which has a quality 720p 60fps, I don't have a an option to choose 720p and 30fps

**Comment by bastimeyer** [comment]
> Post the **full debug log output** of what you're trying to do.

**Comment by HulioEglesias** [comment]
![image](https://user-images.githubusercontent.com/15662060/180615522-9e43bf5c-5680-4036-aeeb-814ca776e684.png)

**Comment by bastimeyer** [comment]
Twitch simply doesn't provide the stream quality. Simple as that.
