### ISSUE TITLE
plugins.vidio: streams broken & problem came again

### ISSUE THREAD

**Issue by BBBABUHS** [streamlink/streamlink#4676]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Unable to open URL: https://www.vidio.com/live/204-sctv (403 Client Error: Forbidden for url: https://www.vidio.com/live/204-sctv)

### Debug log

```text
Unable to open URL: https://www.vidio.com/live/204-sctv (403 Client Error: Forbidden for url: https://www.vidio.com/live/204-sctv)
```

**Comment by back-to** [comment]
> Latest stable release

this is outdated,
you need at least https://github.com/streamlink/streamlink/commit/e0d1273f104a63c392831225f14a2b3af47e712b

**Comment by mkbloke** [comment]
And yet again, another failure to produce a **debug log** as requested in the issue template.  Please stop wasting people's time.
