### ISSUE TITLE
itftennis

### ISSUE THREAD

**Issue by yxiao1996** [streamlink/streamlink#4693]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hi team,

I'm a tennis fan interested in recording some livestreams from the ITF website. This site is run by ITF(international tennis federation) used to provide livestream of lower-level professional tennis tournaments, which don't go on TV. Want to check if this is a good candidate for a plugin. If it's a valid one, I can try to implement it myself.

Thanks,
Yu

### Input URLs

https://live.itftennis.com/en/live-streams/video.php?vid=35064381
https://live.itftennis.com/en/live-streams/video.php?vid=35062451

**Comment by mkbloke** [comment]
It seems viable for inclusion in master to me.  These are the things that preclude plugin inclusion: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

As far as I can see, there are no problems with anything listed there, other than perhaps DRM, as there are no live streams to look at right now and check.

**Comment by yxiao1996** [comment]
Hi Ian,

Thanks for checking this, if it looks good then I could try to write the plugin. 

BTW, I also find another website streaming tennis tournaments: https://www.atptour.com/en/atp-challenger-tour/challenger-tv. This site has live streams and also past recordings of a the challenger-level professional tennis matches. Could you please also help me confirm if this one looks valid? If yes I can also try to create plugin for this one.

Thanks,
Yu

**Comment by mkbloke** [comment]
> As far as I can see, there are no problems with anything listed there, other than perhaps DRM, as there are no live streams to look at right now and check.

Had a look today - it's just HLS with the streaming URL embedded in some JS within the page.

>  https://www.atptour.com/en/atp-challenger-tour/challenger-tv

Seems OK, but I see it has CloudFlare DDoS/bot protection, so that could be difficult to get around.

**Comment by yxiao1996** [comment]
Hi Ian,

thanks for help checking. Just curious, how would ddos/bot detection affects streamlink, or in other words, would streamlink act significantly different than a normal watcher of the stream? If it's about the rate to fetch .ts segments, wonder if streamlink has a config to limit its own rate?

Thanks,
Yu

**Comment by mkbloke** [comment]
Ignore what I said above - I happened to pull the HTML page via curl from https://www.atptour.com/en/atp-challenger-tour/challenger-tv and was getting an intermediate page from CF with it.  I'm not sure why that was happening as I'd set a UA rather than the curl default, but obviously there was something about the curl request that was triggering CF to produce it.

**Comment by back-to** [comment]
This website has a small user range, not worth it.
