### ISSUE TITLE
yy.com support

### ISSUE THREAD

**Issue by JohnDoh666** [streamlink/streamlink#470]
yy.com is yet another chinese streaming site. I lack the programming skills to make a plugin myself, so it would be awesome if someone in this community could take a look at it.

Example URL: http://www.yy.com/game/lol

Thanks!

**Comment by xkbd** [comment]
Desktop (RTMP) streams: impossible to obtain using rtmpdump (playpath can be found after connection)
Mobile streams in my case didn't work.

**Comment by JohnDoh666** [comment]
Damn, does that mean that capturing the stream is impossible? Thanks for trying though.

**Comment by fozzysec** [comment]
You can look into the mobile page, the stream provided is HLS stream, but the stream url is not presented directly. By looking into the js scripts you can know that it use ajax to send request and get the HLS stream url, it is a bit more work to do dealing with the javascript algorithm in Python, after those work I will the mobile HLS stream can be retrieved easily.

**Comment by Shadesss** [comment]
yy.com support would be amazing.

**Comment by Erk-** [comment]
@back-to Any reason you have marked quite a bit of plugin requests as `wontfix`? It seems strange to me.

**Comment by back-to** [comment]
> wontfix
This will not be worked on

**so people don't expect this to work with Streamlink** when they search for this website,
as this issue is almost 3 Years old and nobody found a solution or time for it.

**Comment by Erk-** [comment]
Then you should not be closing them as well, because that will only lead to other people opening the same issue.
