### ISSUE TITLE
plugins.mitele: 403 Client Error: Forbidden token format

### ISSUE THREAD

**Issue by tvfj** [streamlink/streamlink#4726]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

New changes on API

### Debug log

```text
[cli][debug] OS:         Linux-5.4.0-122-generic-x86_64-with-glibc2.31
[cli][debug] Python:     3.10.5
[cli][debug] Streamlink: 4.2.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug] Arguments:
[cli][debug]  url=https://mitele.es/directo/telecinco
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=vlc
[cli][info] Found matching plugin mitele for URL https://mitele.es/directo/telecinco
[plugins.mitele][debug] Stream: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/web.m3u8 (hls)
[plugins.mitele][debug] Stream: https://directos.mitele.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8 (hls)
[plugins.mitele][debug] Stream: https://livek.mediaset.es/orilinear01/live/linear01/main/main.isml/web.m3u8 (hls)
[plugins.mitele][debug] Stream: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8 (hls)
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st%3D1660114575~exp%3D1660200974~acl%3D%2F%2A~hmac%3D2e0d916d43994680b72c50d5dfecadb812c920ee14a4cb918789c3aa8d803f54 (403 Client Error: Forbidden token format for url: https://livek.mediaset.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st%3D1660114575~exp%3D1660200974~acl%3D%2F%2A~hmac%3D2e0d916d43994680b72c50d5dfecadb812c920ee14a4cb918789c3aa8d803f54)
```

**Comment by bastimeyer** [comment]
> 403 Client Error: Forbidden token format

The site requires a monthly subscription to access that channel. Not sure if that's because of me trying to access it with a German IP, but other channels are showing a regular geo-protection message.

**Comment by tvfj** [comment]
> > 403 Client Error: Forbidden token format
> 
> The site requires a monthly subscription to access that channel. Not sure if that's because of me trying to access it with a German IP, but other channels are showing a regular geo-protection message.
> 
> Are other channels working fine?
Yes, and I can also access this channel for free too.

It has geoblocked for Spain.

**Comment by tvfj** [comment]
> > 403 Client Error: Forbidden token format
> 
> The site requires a monthly subscription to access that channel. Not sure if that's because of me trying to access it with a German IP, but other channels are showing a regular geo-protection message.
> 
> Are other channels working fine?

Yes, and I can also access this channel for free too.

It has geoblocked for Spain.

**Comment by Lordwinder** [comment]
The issue still continue. I am accessing from Spain, an still it gives the "Client Error: Forbidden token" reported. On the website directly "https://www.mitele.es/directo/telecinco/" , without any subscription works perfect on Chrome.
