### ISSUE TITLE
No filename displayed in HLS livestream downloading since 4.3.0

### ISSUE THREAD

**Issue by DCxDESIGN** [streamlink/streamlink#4752]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

In 4.2.0 and earlier versions, when downloading hls livestream, the destination filename is always being displayed in the latest prompted progress line.

But from 4.3.0, the filename is no longer displayed, only size/duration/speed. Like this:

![image](https://user-images.githubusercontent.com/48208459/185729234-dac6b527-ed89-4173-bd9e-1afe97b5a20c.png)

For users who need to download multiple streams in the same time, this change might make it much harder to monitor the progress of different files.

### Debug log

```text
N/A
```

**Comment by bastimeyer** [comment]
This was removed intentionally, because it was showing a truncated file name instead of the full path which already gets logged.

#4656 - cli: rewrite progress output (4.3.0)
> Output format changes:
> - Remove "prefix" from output format (full path already gets logged)

#4336 - cli: log resolved file output path (3.2.0)
> Streamlink currently doesn't log the full path when writing the output to a file. This is an issue when the output path is dynamically generated from the input argument via the stream's metadata, because the user doesn't know where the data was actually written to. The output path gets already logged if the file already exists, but that's not really helpful.

**Comment by DCxDESIGN** [comment]
> This was removed intentionally, because it was showing a truncated file name instead of the full path which already gets logged.
> 
> #4656 - cli: rewrite progress output (4.3.0)
> 
> > Output format changes:
> > 
> > * Remove "prefix" from output format (full path already gets logged)
> 
> #4336 - cli: log resolved file output path (3.2.0)
> 
> > Streamlink currently doesn't log the full path when writing the output to a file. This is an issue when the output path is dynamically generated from the input argument via the stream's metadata, because the user doesn't know where the data was actually written to. The output path gets already logged if the file already exists, but that's not really helpful.

Thank you for answering but I'm not sure I've fully understood what you mean - Would it be fixed or it's so far not considered as an issue to be adjusted?

If not, how can I customize to let the filename displayed in the progress output? It's really important to me. :-[

**Comment by bastimeyer** [comment]
> Would it be fixed or it's so far not considered as an issue to be adjusted?
> how can I customize to let the filename displayed in the progress output

You can't customize the progress output, at least not without modifying the code. Letting the user customize it via additional command line arguments - while possible and probably not even hard to implement due to the Formatter class that's already used for the `--output` stuff - would be a total overkill. The progress output is not meant as a stable interface for parsing, in case that's what you're asking for. And for humans, the old file name implementation was bad and was removed because of that (see below).

Since you posted (a screenshot) of a debug log with download progress output, I just want to mention that the current implementation still has room for improvement, as it doesn't clear the progress output when the logger writes new lines, so lots of unnecessary progress output lines remain in between the log output. Both logging/output mechanisms work independently of each other while writing to the same stdout stream, which is the reason for this.

----

This is the output of 4.3.0, and as you can see, it's reduced to the actual useful information, while the full output path already gets logged (implemented in 3.2.0). This is important when the output path contains metadata variables or when the output file has a long name.

```
$ streamlink youtube.com/hospitalrecords best -o /dev/null
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Writing output to
/dev/null
[download] Written 8.11 MiB (11s @ 720.81 KiB/s)
...

$ streamlink youtube.com/hospitalrecords best -o '/tmp/records/{author} - {title}.ts'
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Writing output to
/tmp/records/Hospital Records - Drum & Bass Non-Stop Liquid - To Chill _ Relax Too.ts
[download] Written 5.74 MiB (8s @ 733.96 KiB/s)
...
```

In the earlier versions, the same commands show this output, which is not useful at all:

```
$ streamlink youtube.com/hospitalrecords best -o /dev/null
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Writing output to
/dev/null
[download][null] Written 4.5 MB (5s @ 772.5 KB/s)
...

$ streamlink youtube.com/hospitalrecords best -o '/tmp/records/{author} - {title}.ts'
[cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Writing output to
/tmp/records/Hospital Records - Drum & Bass Non-Stop Liquid - To Chill _ Relax Too.ts
[download][..To Chill _ Relax Too.ts] Written 4.4 MB (5s @ 764.2 KB/s)
...
```

**Comment by DCxDESIGN** [comment]
> > Would it be fixed or it's so far not considered as an issue to be adjusted?
> > how can I customize to let the filename displayed in the progress output
> 
> You can't customize the progress output, at least not without modifying the code. Letting the user customize it via additional command line arguments - while possible and probably not even hard to implement due to the Formatter class that's already used for the `--output` stuff - would be a total overkill. The progress output is not meant as a stable interface for parsing, in case that's what you're asking for. And for humans, the old file name implementation was bad and was removed because of that (see below).
> 
> Since you posted (a screenshot) of a debug log with download progress output, I just want to mention that the current implementation still has room for improvement, as it doesn't clear the progress output when the logger writes new lines, so lots of unnecessary progress output lines remain in between the log output. Both logging/output mechanisms work independently of each other while writing to the same stdout stream, which is the reason for this.
> 
> This is the output of 4.3.0, and as you can see, it's reduced to the actual useful information, while the full output path already gets logged (implemented in 3.2.0). This is important when the output path contains metadata variables or when the output file has a long name.
> 
> ```
> $ streamlink youtube.com/hospitalrecords best -o /dev/null
> [cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
> [cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> [cli][info] Writing output to
> /dev/null
> [download] Written 8.11 MiB (11s @ 720.81 KiB/s)
> ...
> 
> $ streamlink youtube.com/hospitalrecords best -o '/tmp/records/{author} - {title}.ts'
> [cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
> [cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> [cli][info] Writing output to
> /tmp/records/Hospital Records - Drum & Bass Non-Stop Liquid - To Chill _ Relax Too.ts
> [download] Written 5.74 MiB (8s @ 733.96 KiB/s)
> ...
> ```
> 
> In the earlier versions, the same commands show this output, which is not useful at all:
> 
> ```
> $ streamlink youtube.com/hospitalrecords best -o /dev/null
> [cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
> [cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> [cli][info] Writing output to
> /dev/null
> [download][null] Written 4.5 MB (5s @ 772.5 KB/s)
> ...
> 
> $ streamlink youtube.com/hospitalrecords best -o '/tmp/records/{author} - {title}.ts'
> [cli][info] Found matching plugin youtube for URL youtube.com/hospitalrecords
> [cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> [cli][info] Writing output to
> /tmp/records/Hospital Records - Drum & Bass Non-Stop Liquid - To Chill _ Relax Too.ts
> [download][..To Chill _ Relax Too.ts] Written 4.4 MB (5s @ 764.2 KB/s)
> ...
> ```

Again, thank you for your patient reply. However, as a long-time Streamlink user with little development experience, I would like to state some opinions based on my situation.

As I said in the previous reply, displaying the file name in the progress output is very important for users who need to download multiple files at the same time. Once there is a network problem or some other, I can quickly find the source of the problem through the information. It may display in incomplete ways, but as long as it is distinguishable to the users from other concurrent files, it will always be useful, even it is not so in the eyes of the development team. Therefore, even if the development team thinks that it is not perfect at present, there are still users who need it.

Second, while for open source community softwares like Streamlink, the development team is not obligated to meet the needs of all users, the deprecation of a feature that involves display/output might still should be considered a breaking update. Based on your previous reply, maybe this is just "throwing away a buggy and useless feature" for the development team. However, for users like me who were used to seeing it in the previous versions, I still felt very shocked when I didn't see this deprecation reminder in the Changelog, but found it abandoned during use.

And, based on your last reply, maybe I can understand it this way: In Info-level output, the full filename record displayed before the download starts will not be flushed by the progress information in Debug-level, and it might possibly be a temporary solution to see filenames on the screen. But in contradiction to this, Streamlink is a software that is being developed at a high speed and with the help of community feedback. Users like me are used to enabling the Debug mode in default. It not only helps us to quickly locate problems, but also provides timely and useful information during feedback to you. So still, perhaps the ultimate and best solution for me, is to display filenames even in Debug mode.

It might bother you to read such a bunch of words and may you kindly excuse me for that, but please don't judge any of your work as "not useful at all" without listening to users first. We appreciate your team and your work, as much as how you love them.

**Comment by bastimeyer** [comment]
> the deprecation of a feature that involves display/output might still should be considered a breaking update

It is not, because it's not part of a stable interface. By that logic, we weren't able to change or fix anything without bumping the major version in very release. The entire `streamlink_cli` module is probably not even considered stable apart from the available CLI arguments.

But since I don't want to just decline your request and close the thread, I can take a look at appending the output path to the progress output, so that it can make use of all the available space (which it was probably not allowed to).

**Comment by DCxDESIGN** [comment]
> > the deprecation of a feature that involves display/output might still should be considered a breaking update
> 
> It is not, because it's not part of a stable interface. By that logic, we weren't able to change or fix anything without bumping the major version in very release. The entire `streamlink_cli` module is probably not even considered stable apart from the available CLI arguments.
> 
> But since I don't want to just decline your request and close the thread, I can take a look at appending the output path to the progress output, so that it can make use of all the available space (which it was probably not allowed to).

I appreciate your kindness and look forward to the upcoming updates. Thank you so much.

**Comment by bastimeyer** [comment]
> it doesn't clear the progress output when the logger writes new lines

Btw, it can't clear the lines, because the progress output writes to stderr, while the logger writes to stdout. I wasn't aware of this when I wrote the comment.
