### ISSUE TITLE
plugins.atresplayer: Live streams is not working.

### ISSUE THREAD

**Issue by heroku-miraheze** [streamlink/streamlink#4755]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

As for today, Atresplayer live streams is not working.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.6
[cli][debug] Streamlink: 4.3.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.atresplayer.com/directos/antena3/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --hls-live-edge=1
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/antena3/
error: Unable to validate response text: ValidationError(NoneOrAllSchema):
  ValidationError(type):
    Type of <generator object search_dict at 0x000002C64BA79930> should be list, but is generator
```

**Comment by bastimeyer** [comment]
The validation schema is indeed broken. However, similar to the mitele plugin #4726, the site requires a paid subscription for all channels (I checked with a local German IP as well as a Spanish proxy/VPN).

Submitting a fix for the validation schemas is thus pointless if I can't check whether the plugin is working correctly.

**Comment by Jeffade1** [comment]
@bastimeyer Neither atresplayer nor mitele requires a paid subscription as long as you have a spanish IP.
I just loaded those two pages with a spanish VPN and it works perfectly:
https://www.atresplayer.com/directos/antena3/ 
https://www.mitele.es/directo/telecinco/

**Comment by bastimeyer** [comment]
The VPN I am using gets blocked and they are showing a requirement for a paid subscription, on their site as well as on the API.
```
$ curl -s 'https://api.atresplayer.com/player/v1/live/5a6a165a7ed1a834493ebf6a'
{"error":"required_paid","error_description":"Required paid"}

$ curl -s 'https://api.atresplayer.com/player/v1/live/5a6a165a7ed1a834493ebf6a'
{"error":"vpn","error_description":"Using VPN","detail":{"ip":"redacted","time":"2022-08-20T20:07:14Z"}}
```

I can open a PR with my changes for you to test though.
