### ISSUE TITLE
Twitch: Playing vods of still recording streams dont start at the beginning

### ISSUE THREAD

**Issue by Jackels** [streamlink/streamlink#476]
Hi.
Basicially when you want to watch a vod via
streamlink twitch.tv/someguy/v/12344321 high
and the vod you are referencing is still getting recorded aka the streamer is still live and the stream is recorded to that vod ( 12344321 ) streamlink will just stream whatever is currently streamed by the streamer.
I expected that streamlink would start from the vod beginning tho. If I wanted to watch the current stream, i wouldnt specifiy the vod.

**Comment by beardypig** [comment]
The `HLSStream` class assumes that it's a live stream if the stream is incomplete. As the VOD is still recording it looks the same as a live stream to streamlink, and so plays it from the end. This is normally what you want, except of course, in this case where you are requesting a VOD and you reasonably expect it to start from the beginning. 

I'll put together a PR to offer a solution.
