### ISSUE TITLE
plugins.hiplayer not working

### ISSUE THREAD

**Issue by UltraHDR** [streamlink/streamlink#4769]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The plugin was added in https://github.com/streamlink/streamlink/pull/4507 and it has stopped working. Input URL are available on the pull request. Thanks

### Debug log

```text
~$ streamlink --version
streamlink 4.3.0
~$ 
~$ streamlink 'https://rotana.net/live-clip' best --stream-url --loglevel debug
error: Unable to validate response text: ValidationError(NoneOrAllSchema):
  ValidationError(NoneOrAllSchema):
    ValidationError(url):
      "'" is not a valid URL
~$ streamlink 'https://www.cnbcarabia.com/Pages/live' best --stream-url --loglevel debug
error: Unable to validate response text: ValidationError(NoneOrAllSchema):
  ValidationError(NoneOrAllSchema):
    ValidationError(url):
      "'" is not a valid URL
~$ streamlink 'https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTV1' best --stream-url --loglevel debug
error: Unable to validate response text: ValidationError(NoneOrAllSchema):
  ValidationError(NoneOrAllSchema):
    ValidationError(url):
      "'" is not a valid URL
~$
```

**Comment by bastimeyer** [comment]
The issue got introduced by #4702 where some named capture groups were added to regular expressions, and then the indexed capture group getters were not updated respectively. The fix is simple, but I will have to take a look at the other plugins which were affected by this as well.
