### ISSUE TITLE
plugins.plugin-name-here: A very brief summary of what's broken

### ISSUE THREAD

**Issue by SAOJSM** [streamlink/streamlink#4774]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

@mkbloke Pandalive Plugin
I think this plugin is not working again, hope you can push a new version fix this bug and add function you mentioned https://github.com/streamlink/streamlink/issues/4588. Thanks for your contribution.

### Debug log

```text
 streamlink "https://www.pandalive.co.kr/live/play/asiaoc" best -o "/root/stream/test.ts"                                                                      Failed to load plugin pandalive:                                                         File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/streamlink/plugins/pandalive.py", line 10, in <module>
    from streamlink.plugin import Plugin, pluginmatcher
ImportError: cannot import name 'pluginmatcher' from 'streamlink.plugin' (/usr/lib/python3/dist-packages/streamlink/plugin/__init__.py)

[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: https://www.pandalive.co.kr/live/play/asiaoc

**Comment by back-to** [comment]
reinstall streamlink, your version is broken

https://streamlink.github.io/latest/install.html


```
$  streamlink "https://www.pandalive.co.kr/live/play/asiaoc" -l info
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/asiaoc
[plugins.pandalive][info] Broadcast type: live
[cli][info] Available streams: 160p (worst), 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
```

**Comment by SAOJSM** [comment]
I already reinstall. The version is streamlink 4.3.0+21.g880ac1e2.
But hope @mkbloke can add function mentioned https://github.com/streamlink/streamlink/issues/4588. Thanks for your contribution.

**Comment by mkbloke** [comment]
If you're talking about adding login functionality, I don't think that will be implemented.  See: https://github.com/streamlink/streamlink/issues/4588#issuecomment-1153345851

**Comment by KOONWHITE** [comment]
I'm having this problem now.
streamlink --http-cookie "_ga_W91XDLC3YE=<GS1.1.1680342372.187.1.1680344826.0.0.0>" "https://www.pandalive.co.kr/live/play/answl0810" best -o "a.ts"

![dfa](https://user-images.githubusercontent.com/129593259/229285146-9f2f4dd2-8ebe-47bb-8ffb-323707393a63.png)
The above problem occurs. I can let you know my account for a while if you want.
