### ISSUE TITLE
cli: support for marking metadata variables in `--title` / `--output` / etc. as required

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4786]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Opening my comment from earlier today as a separate feature request thread:
https://github.com/streamlink/streamlink/issues/4411#issuecomment-1231497093
Related: #4783

There's a problem on Twitch when streams have just come online, where metadata is unavailable for a short while afterwards due to how Twitch propagates data on their GQL API.

When recording streams via `--output` (and related output arguments), missing metadata will result in empty strings in the chosen output paths. The same happens when setting a custom player title via `--title`. This is usually not a problem, as the user can see the resulting output path immediately and react accordingly.

However, when waiting for streams via `--retry-streams` / `--retry-max`, there's a high chance of the metadata being empty depending on the `--retry-streams` time interval between stream availability checks, resulting in unexpected empty output paths.

It therefore would make sense being able to mark metadata variables as required and making `streamlink_cli` keep retrying until metadata is available. When not retrying, the process should fail if required metadata variables can not be substituted with actual, non-empty data.

An alternative would be adding a new CLI argument for marking all metadata as required, but that would cause issues with formatter variables which don't depend on the plugin metadata, like `time` for example. It's also possible that users still want to have some optional metadata. And since only a few plugins provide full metadata, this makes it even more complicated.

----

I have already made some local changes which implement the necessary logic in the `Formatter`. However, the real problem is once again the terribly messy `streamlink_cli.main` module.

I'm not going into detail here now, as I've been writing and deleting stuff again multiple times for the past hour or so. Implementing this feature requires some annoying changes which I'm not happy about, but it should be possible. I'm not sure though if it'll be worth implementing.

----

Plugin metadata is very much tied to the stream fetching via the `Plugin._get_streams()` method and the state of the plugin instance after the `plugin.streams()` call. There's no API for only fetching metadata because it wouldn't even make sense for the vast majority of plugins. This means that whenever metadata is missing (which is what we're trying to solve), streams always have to get re-fetched, and the logic of `streamlink_cli` has to be updated in these parts.

When streams get fetched, which happens right after plugin resolving and initialization, the formatter hasn't been initialized yet, so checking the user's input and the variables which are marked as required is a problem. This can be worked around by moving the initialization of the formatter right after where the plugin gets initialized, as it depends on the plugin instance. Implementing a `Formatter.valid` method which checks for syntax errors and the availability of required metadata would also be a requirement (already completed).

This means that the solution looks like making the formatter instance a global (:vomiting_face:) and updating the `streamlink_cli.main.fetch_streams` function. Then exceptions for missing metadata or synax errors need to be raised and caught accordingly by `fetch_streams_with_retry`, `output_stream_http` and most importantly, `handle_url`.

**Comment by gravyboat** [comment]
> I'm not sure though if it'll be worth implementing.

I don't think it's worth implementing at all. Frankly I don't care if the metadata isn't available for a few minutes. 99.9% of users won't care either. If someone needs the metadata so bad (and let's be real the only reason you would need that metadata is because you're locally recording which isn't even the intent of Streamlink) then write a wrapper that looks for the data in the output and retries until it's there. This isn't Streamlink's job to handle.
