### ISSUE TITLE
https://web.tvplus.com.tr/ / Turkcell

### ISSUE THREAD

**Issue by omergumus** [streamlink/streamlink#4794]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

This site is a platform that makes TV live broadcasts that require membership. After logging in with my current subscription, it offers the opportunity to watch local channels broadcast in Turkey. After confirming the user and password via streamlink to this site, I want to watch the TV channel I want by selecting it.

### Input URLs

https://tvplus.com.tr/
https://tvplus.com.tr/tv-izle
https://web.tvplus.com.tr/
https://web.tvplus.com.tr/giris

**Comment by mkbloke** [comment]
If this site requires a paid subscription to access content, the Streamlink maintainers will not accept a plugin for the site (see: https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests).  Plugins for subscription-based sites are just not maintainable in the long run.

It appears to me that this site does require a paid subscription, so I'll close this issue.  If I'm wrong, please feel free to reopen it.
