### ISSUE TITLE
plugins.facebook: no playable streams found

### ISSUE THREAD

**Issue by DannyDarth** [streamlink/streamlink#4800]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When i put in a facebook link this is what it says:

```
$ streamlink https://www.facebook.com/JoblessGarrett/videos/452060846981476/ best
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/JoblessGarrett/videos/452060846981476/
error: No playable streams found on this URL: https://www.facebook.com/JoblessGarrett/videos/452060846981476/
```

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.6
[cli][debug] Streamlink: 4.3.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.3
[cli][debug] Arguments:
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Users\Daniel\AppData\Local\Streamlink\ffmpeg\ffmpeg.exe
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
```

**Comment by back-to** [comment]
might be a temporary issue,
seems to work right now.

**Comment by TaoziDB** [comment]
The error is back:

`>streamlink --loglevel debug https://www.facebook.com/100053893267852/videos/753666242400710/ best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.7.8
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.4
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodome: 3.7.3
[cli][debug]  PySocks: 1.6.8
[cli][debug]  requests: 2.26.0
[cli][debug]  websocket-client: 1.2.1
[cli][debug]  importlib-metadata: 3.10.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.facebook.com/100053893267852/videos/753666242400710/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/100053893267852/videos/753666242400710/
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/100053893267852/videos/753666242400710/`

**Comment by DannyDarth** [comment]
This issue is back:
error: No playable streams found on this URL..

**Comment by nixeo** [comment]
Same issue since yesterday

```
streamlink -l debug https://www.facebook.com/100064268522304/videos/2004370776566166
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.facebook.com/100064268522304/videos/2004370776566166
[cli][debug]  --loglevel=debug
[cli][debug]  --player-args=--cache=yes --demuxer-max-bytes=30M
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/100064268522304/videos/2004370776566166
[plugins.facebook][debug] No meta og:video:url
[plugins.facebook][debug] Falling back to playlist regex
[plugins.facebook][debug] Falling back to tahoe player
[plugins.facebook][debug] No meta og:video:url
error: No playable streams found on this URL: https://www.facebook.com/100064268522304/videos/2004370776566166
```

**Comment by DannyDarth** [comment]
Has this been looked at, at all? Not trying to pushy or anything. Was just wondering.

**Comment by gravyboat** [comment]
@DannyDarth Nope someone would have commented if they had. Feel free to troubleshoot it if you feel confident doing so, otherwise it will have to wait until someone decides they want to look at it.

**Comment by bastimeyer** [comment]
I had a go at rewriting the facebook plugin a few months ago while cleaning up lots of other plugins, and I decided that it's not worth spending any of my time on it, because you'll get blocked immediately by FB, especially when having to create an account.

So if you want this to get fixed, submit a pull request and it'll get reviewed.

As a quick hint, because I actually had a quick look at it, for VODs that were linked in the comments above, it looks like they are using a custom DASH implementation. The direct link to the mp4 file however is embedded in some JSON data and if the right byte offsets and request lengths are set, then the entire file can be requested as a single HTTPStream instance.

**Comment by DannyDarth** [comment]
> I had a go at rewriting the facebook plugin a few months ago while cleaning up lots of other plugins, and I decided that it's not worth spending any of my time on it, because you'll get blocked immediately by FB, especially when having to create an account.
> 
> So if you want this to get fixed, submit a pull request and it'll get reviewed.
> 
> As a quick hint, because I actually had a quick look at it, for VODs that were linked in the comments above, it looks like they are using a custom DASH implementation. The direct link to the mp4 file however is embedded in some JSON data and if the right byte offsets and request lengths are set, then the entire file can be requested as a single HTTPStream instance.

Yeah i wouldn't even know where to begin. It sucks this isn't working anymore, the site streams itself are so bad. But when they are played through streamlink it was nice and smooth.

**Comment by DannyDarth** [comment]
> Launching with a custom User-Agent fixed it for me `streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"`

Do i need to put all of that in for it to launch?

**Comment by PJ-The-Realest** [comment]
> > Launching with a custom User-Agent fixed it for me `streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"`
> 
> Do i need to put all of that in for it to launch?
> 
> example: streamlink https://www.facebook.com/xAcceptiion/videos/1148742532667962 "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"

It worked? I have the same problem.

**Comment by mkbloke** [comment]
Changing the `User-Agent` does not appear to work (at least now), even though the video is still available on Facebook and can be viewed without being logged in.
```
$ streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36" 'https://www.facebook.com/xAcceptiion/videos/1148742532667962'
[cli][info] Found matching plugin facebook for URL https://www.facebook.com/xAcceptiion/videos/1148742532667962
error: No playable streams found on this URL: https://www.facebook.com/xAcceptiion/videos/1148742532667962
```

**Comment by DannyDarth** [comment]
> Changing the `User-Agent` does not appear to work (at least now), even though the video is still available on Facebook and can be viewed without being logged in.
> 
> ```
> $ streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36" 'https://www.facebook.com/xAcceptiion/videos/1148742532667962'
> [cli][info] Found matching plugin facebook for URL https://www.facebook.com/xAcceptiion/videos/1148742532667962
> error: No playable streams found on this URL: https://www.facebook.com/xAcceptiion/videos/1148742532667962
> ```

the stream link i provided was just an example. Try a stream that is live and let me know. But i could never get it to work.

**Comment by Schn4pper** [comment]
> Changing the `User-Agent` does not appear to work (at least now), even though the video is still available on Facebook and can be viewed without being logged in.
> 
> ```
> $ streamlink --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36" 'https://www.facebook.com/xAcceptiion/videos/1148742532667962'
> [cli][info] Found matching plugin facebook for URL https://www.facebook.com/xAcceptiion/videos/1148742532667962
> error: No playable streams found on this URL: https://www.facebook.com/xAcceptiion/videos/1148742532667962
> ```

Changing the user agent works.

**Comment by DannyDarth** [comment]
> self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})

So i need to edit the facebook.py file and add the line you just shared?

**Comment by ringtvt** [comment]
> > self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})
> 
> So i need to edit the facebook.py file and add the line you just shared?
> 
> I changed the facebook.py script and added the line you shared and it still does not work.
> 
> Ugh i wish this still worked.

I'm using temporary: yt-dlp.exe
You can use it until someone can fix facebook.py

**Comment by Schn4pper** [comment]
> > self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})
> 
> So i need to edit the facebook.py file and add the line you just shared?
> 
> I changed the facebook.py script and added the line you shared and it still does not work.
> 
> Ugh i wish this still worked.

Can you please provide me the link you have tried ?

**Comment by DannyDarth** [comment]
> > > self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})
> > 
> > 
> > So i need to edit the facebook.py file and add the line you just shared?
> > I changed the facebook.py script and added the line you shared and it still does not work.
> > Ugh i wish this still worked.
> 
> Can you please provide me the link you have tried ? The [last one](https://www.facebook.com/xAcceptiion/videos/1148742532667962) does work. Basically I've just added the line 78: ![image](https://user-images.githubusercontent.com/75565715/229378878-3559dee4-7939-48f0-8109-fd2510d8564d.png)

try this one. its live right now 
https://www.facebook.com/LordKebun/videos/2164431453749627

**Comment by Schn4pper** [comment]
> > > > self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})
> > > 
> > > 
> > > So i need to edit the facebook.py file and add the line you just shared?
> > > I changed the facebook.py script and added the line you shared and it still does not work.
> > > Ugh i wish this still worked.
> > 
> > 
> > Can you please provide me the link you have tried ? The [last one](https://www.facebook.com/xAcceptiion/videos/1148742532667962) does work. Basically I've just added the line 78: ![image](https://user-images.githubusercontent.com/75565715/229378878-3559dee4-7939-48f0-8109-fd2510d8564d.png)
> 
> try this one. its live right now https://www.facebook.com/LordKebun/videos/2164431453749627
> 
> Sadly it does not work for me.

The video seems private, I can't watch it. As far as I know, only public VOD/livestream are supported by streamlink, and oddly enough only if the VOD duration is under a certain time. [This VOD](https://www.facebook.com/LordKebun/videos/759738198995113/) lasting 13:44 works, but not [this one](https://www.facebook.com/LordKebun/videos/991915535511967/) lasting 4 hours.

**Comment by DannyDarth** [comment]
> > > > > self.session.http.headers.update({"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"})
> > > > 
> > > > 
> > > > So i need to edit the facebook.py file and add the line you just shared?
> > > > I changed the facebook.py script and added the line you shared and it still does not work.
> > > > Ugh i wish this still worked.
> > > 
> > > 
> > > Can you please provide me the link you have tried ? The [last one](https://www.facebook.com/xAcceptiion/videos/1148742532667962) does work. Basically I've just added the line 78: ![image](https://user-images.githubusercontent.com/75565715/229378878-3559dee4-7939-48f0-8109-fd2510d8564d.png)
> > 
> > 
> > try this one. its live right now https://www.facebook.com/LordKebun/videos/2164431453749627
> > Sadly it does not work for me.
> 
> The video seems private, I can't watch it. As far as I know, only public VOD/livestream are supported by streamlink, and oddly enough only if the VOD duration is under a certain time. [This VOD](https://www.facebook.com/LordKebun/videos/759738198995113/) lasting 13:44 works, but not [this one](https://www.facebook.com/LordKebun/videos/991915535511967/) lasting 4 hours.

So basically there is no way around watching the streams? This person that i just linked, i use to watch. Guess not anymore :(

**Comment by Schn4pper** [comment]
Can you please post the output of this command ?
`streamlink https://www.facebook.com/LordKebun/videos/759738198995113/ best "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36" --loglevel=debug`

**Comment by Schn4pper** [comment]
My bad. Here's the right command:
`streamlink https://www.facebook.com/LordKebun/videos/759738198995113/ best --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"  --loglevel=debug`

**Comment by DannyDarth** [comment]
![image](https://user-images.githubusercontent.com/81840598/229452606-0955e820-7c5c-4a81-989f-9145b91b23c8.png)

**Comment by Schn4pper** [comment]
I've tried and it works.
![image](https://user-images.githubusercontent.com/75565715/229555234-f6ad0b3c-5e39-4bea-89f5-97bdcce63501.png)
Sorry, I'm clueless. I guess any other platform livestream (like YouTube) works ?

**Comment by Schn4pper** [comment]
If I get the livestream direct link and open it up with streamlink, it works too:
`streamlink "https://www.facebook.com/JackHuddo/videos/193126433468709/" best --stream-url`
https://video-zrh1-1.xx.fbcdn.net/hvideo-eag-ncg/_nc_cat-100/_nc_sr_t-4/v/rASc-pLY3qpUJiafru9FGYgegpBNdvIoawwAqikgZvOwfig/_nc_ohc-MpVcklzLMyoAX-k8Rrl/live-dash/dash-abr-ibr-audio/3506432756305484.mpd?ccb=2-4&ms=m_CTPA&sc_t=1&oh=00_AfBuo5aTYkuCujUeTH7xPENAosTkQmPWTmZZdA1BI_V9Eg&oe=642CE42B

`streamlink "https://video-zrh1-1.xx.fbcdn.net/hvideo-eag-ncg/_nc_cat-100/_nc_sr_t-4/v/rASc-pLY3qpUJiafru9FGYgegpBNdvIoawwAqikgZvOwfig/_nc_ohc-MpVcklzLMyoAX-k8Rrl/live-dash/dash-abr-ibr-audio/3506432756305484.mpd?ccb=2-4&ms=m_CTPA&sc_t=1&oh=00_AfBuo5aTYkuCujUeTH7xPENAosTkQmPWTmZZdA1BI_V9Eg&oe=642CE42B" best`

**Comment by DannyDarth** [comment]
> I've tried and it works. ![image](https://user-images.githubusercontent.com/75565715/229555234-f6ad0b3c-5e39-4bea-89f5-97bdcce63501.png) Sorry, I'm clueless. I guess any other platform livestream (like YouTube) works ?

There has to be something on my end that isnt working right but idk what to do.

**Comment by Schn4pper** [comment]
> wait it worked this time. Ill need to test the person i watch later on and see if it works with there stream. Ill keep you posted!
> 
> I tried using the just the command "streamlink https://www.facebook.com/dasMEHDI/videos/1225708991642172 best" But this does not work.

Great. Maybe you just have to insist, then. Your latest livestream works too.

**Comment by DannyDarth** [comment]
> A possible workaround for you. In your browser, open the developer tools and open the livestream page. In the network tab, all the URLs which are called by the browser are listed. Filter the list with the "mpd" value, copy any *.mpd URL you find and open it with streamlink, not forgetting the User-Agent parameter. ![image](https://user-images.githubusercontent.com/75565715/229558482-d7ad0929-9cea-4560-a804-4c5341803b62.png)

This worked! This method is really annoying but it works.

**Comment by bastimeyer** [comment]
Just in order to prevent more unnecessary comment spam in this thread:

You don't need to modify any plugin contents if you just want to override the default user agent header or any other http headers that get included in each http request. This can simply be done via the `--http-header="User-Agent=VALUE"` CLI parameter. The default UA gets set by the HTTPSession, and its value is the latest one that gets set by Firefox. Various different UAs are available for import from the `streamlink.plugin.api.useragents` module, in case you want to modify a plugin, but this is only rarely useful. The only useful cases here are when sites require specific UAs for certain features, like a downgrade to specific streaming formats on mobile devices, etc.

Changing the user agent won't fix the issues with the facebook plugin. Whatever was posted previously was simply incorrect and just a coincidence. As I have said in my previous comment, **the plugin requires a complete rewrite because it's very much outdated.** Facebook is also pretty aggressive in terms of detection of bots, fake accounts and usage of automated tools like Streamlink. User-Agent headers are arbitrary data, and Facebook surely doesn't rely on this data in order to block access. There are hundreds of other way more sophisticated ways for doing that.

If the resulting data differs from user to user (with different IP addresses and systems) while using the same Streamlink and plugin version, then this indicates that something is missing in the current plugin implementation that makes facebook return the correct and deterministic data, e.g. specific API requests, headers/cookies, etc.
