### ISSUE TITLE
Add "path to ffmpeg" in config file

### ISSUE THREAD

**Issue by Farfie** [streamlink/streamlink#481]
### Checklist
- [x] This is a feature request.

### Description
Add "path to ffmpeg" in config file for people who already have it and dont want it installed again by streamlink's installer.

**Comment by stevek123** [comment]
It should be there.

```
# FFMPEG is used to mux separate video and audio streams in to a single
# stream so that they can be played. The pull or relative path to ffmpeg
# or avconv should be specified here.
#ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
ffmpeg-ffmpeg=
```

**Comment by wlerin** [comment]
Aye but does it make any attempt to locate an existing ffmpeg? It looks like the user still has to fill in the path themselves after install before ffmpeg and rtmpdump will work.

**Comment by beardypig** [comment]
On Mac, Linux and Windows it will search the `PATH` to find `ffmpeg(.exe)` or `avconv`. However, if you do deselect the `ffmpeg` or `rtmpdump` sections during the Windows installer you _will_ need to update the streamlinkrc file to point to `ffmpeg` or `rtmpdump`. I'm working on a fix for this right now... 

fyi, for VLC is searches the `PATH` and some default install locations for `vlc.exe`

**Comment by karlo2105** [comment]
I have issues to open multiaudio stream with ffmpeg. 
Streamlink and ffmpeg are located here : `C:\Program Files\Python27\Lib\site-packages`

I copied ffmpeg folder from Streamlink portable and moved it to path above. 
I just installed VLC 3.0. Take a look on output. 
`streamlink -l debug --ffmpeg-ffmpeg "C:\Program Files\Python27\Lib\site-packages\ffmpeg\ffmpeg" "hlsvariant://https://streamingrmp-1479.kxcdn.com/vod/smil:hls-maudios-prod.smil/playlist.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://https://streamingr
mp-1479.kxcdn.com/vod/smil:hls-maudios-prod.smil/playlist.m3u8
[hls.parse_variant_playlist][debug] Using external audio track for stream 360p (
language=en)
[hls.parse_variant_playlist][debug] Using external audio track for stream 270p (
language=en)
[cli][info] Available streams: 270p (worst), 360p (best)
[cli][info] Opening stream: 360p (hls-multi)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 0 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Adding segment 0 to queue
[cli][error] Could not open stream: cannot use FFMPEG
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 0 complete
[stream.hls][debug] Download of segment 0 complete
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Download of segment 2 complete
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Download of segment 4 complete
[stream.hls][debug] Download of segment 5 complete
[stream.hls][debug] Download of segment 6 complete
[stream.hls][debug] Download of segment 7 complete
[stream.hls][debug] Download of segment 8 complete`

**Comment by Farfie** [comment]
Thanks @beardypig. I should have checked the docs but you were smart enough to figure out a preemptive from my needs anyway, which I'm sure others would want in the future regardless. Long live streamlink, imo.
