### ISSUE TITLE
Orange TV FR

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#4811]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Recently I finally got the home fiber with Orange. 
so I went naturally to their tv site. there is no login at all, but you need to be a customer of orange I assume. 

https://chaines-tv.orange.fr/

I get dash streaming url like this 
https://cdn.ott-na-live-rti.cdnfr.orange.fr/E-l2PjrW_MXVmYFjPXXIXNPN6fM/1-64/1/1662741148/OTV-28bea189-0174-46b3-8315-90a4322f7937/bpk-tv/livetv_tf1_ctv/DASH-CE/index.mpd?bpk-service=Live&device=pc&delay=0&minrate=416000&maxrate=3200000&subtitle=allin

So I tried on my android device, and sniffing with fiddler, but I get the same dash streaming urls.. and I don't have any iOS , but there should be hls url available too right? 

Also are those url drm'ed?   If not, that would be nice to make a plugin to support that website

### Input URLs

https://cdn.ott-na-live-rti.cdnfr.orange.fr/E-l2PjrW_MXVmYFjPXXIXNPN6fM/1-64/1/1662741148/OTV-28bea189-0174-46b3-8315-90a4322f7937/bpk-tv/livetv_tf1_ctv/DASH-CE/index.mpd?bpk-service=Live&device=pc&delay=0&minrate=416000&maxrate=3200000&subtitle=allin

**Comment by back-to** [comment]
> Also are those url drm'ed?

yes, won't work with streamlink

```xml
      <!-- Common Encryption -->
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="">
      </ContentProtection>
      <!-- PlayReady -->
      <ContentProtection schemeIdUri="urn:uuid:" value="MSPR 2.0">
      </ContentProtection>
      <!-- ViaccessOrca -->
      <ContentProtection schemeIdUri="urn:uuid:3">
      </ContentProtection>
      <!-- Widevine -->
      <ContentProtection schemeIdUri="urn:uuid:">
      </ContentProtection>
```

Ref https://github.com/streamlink/streamlink/issues/588

**Comment by Niks4925** [comment]
I know this issue is closed, but here is an implementation for the drm handling:
https://github.com/remzouille/plugin.video.orange.fr/blob/e951449c54a45e0f8f761795112e1796cd04d8f3/resources/lib/provider_templates/orange.py#L87
And how to get auth token:
https://github.com/remzouille/plugin.video.orange.fr/blob/e951449c54a45e0f8f761795112e1796cd04d8f3/resources/lib/provider_templates/orange.py#L33

**Comment by campones** [comment]
it would be amazing  to have this working with streamlink..  but they don't handle streams that are drm'ed

**Comment by bastimeyer** [comment]
Streamlink doesn't support DRM.
