### ISSUE TITLE
Support easybroadcast.fr

### ISSUE THREAD

**Issue by UltraHDR** [streamlink/streamlink#4815]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

live TV CDN used in Arabic countries

### Input URLs

https://ionkhaleej.easybroadcast.fr/category/tv
https://ionkhaleej.easybroadcast.fr/content/3-l-4-maxoe-5-tdreowid-1-ndwsto-4-u-1750-ve
https://ionkhaleej.easybroadcast.fr/content/sdzlmb-3-p-2-tmqs-2-fu-0-jqv-0-uezvnz-7-vbs-6
https://ionkhaleej.easybroadcast.fr/content/nhn-9-e-3-ctnz-13-xlepbuam-9-whtj-8-ywdx-1-a
https://ionkhaleej.easybroadcast.fr/content/mfm
https://ionkhaleej.easybroadcast.fr/content/ion-kuwait-live
https://ionkhaleej.easybroadcast.fr/content/1-ocw-ja-8-tx-p-4-xp-n-er-q-4-ax-fh-tn-4-vd-fe-zm-v
https://ionkhaleej.easybroadcast.fr/content/bawaditv-live
https://ionkhaleej.easybroadcast.fr/content/k-qfaou-oe-zw-ta-9-tm-0-je-vcphwf-56-h-pl-n-vh
https://ionkhaleej.easybroadcast.fr/content/t-ij-9-u-1-ay-rj-6-gp-w-mb-yjz-kn-vi-i-ek-q-bdxp-s
https://ionkhaleej.easybroadcast.fr/content/njk-2-m-05-o-3-btyv-69-ja-1-v-9-upxvenh-7-x-6-kw

**Comment by gravyboat** [comment]
This doesn't meet the [plugin request requirements](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests). It violates #3.

**Comment by UltraHDR** [comment]
Hi @gravyboat This is the official CDN for https://www.bawaditv.com . If you go to the link you will find https://ionkhaleej.easybroadcast.fr iframed in.
