### ISSUE TITLE
plugins.raiplay: Malformed HLS Playlist

### ISSUE THREAD

**Issue by Jeffade1** [streamlink/streamlink#4816]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Plugin stopped working.

### Debug log

```text
streamlink https://www.raiplay.it/dirette/rai1 best
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[stream.hls_playlist][warning] Malformed HLS Playlist. Expected #EXTM3U, but got <Mediapolis>
error: Failed to parse playlist: Missing #EXTM3U header
```

**Comment by bastimeyer** [comment]
Post the entire **debug log**, as requested by the plugin issue form.

Thesite is geo-blocked and it also blocks popular VPN services, so I can't access its streams.

The plugin requests the correct API endpoint and then tries to access the resolved stream URL, which appears to be
`https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803`
for the `rai1` channel.

If it's geo-blocked, then the returned content is not an HLS playlist, but a video instead, which the plugin handles correctly.
```
$ curl -sIL "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803"
HTTP/1.1 302 Moved Temporarily
Date: Sat, 10 Sep 2022 14:37:54 GMT
Server: Apache
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, OPTIONS, HEAD
Vary: X-Forwarded-Proto
Location: https://download-rai-it.akamaized.net/video_no_available.mp4
Content-Type: text/html

HTTP/1.1 200 OK
Accept-Ranges: bytes
ETag: "51a83016a9c866c8213e52cdbcd19d3d:1415293655"
Last-Modified: Thu, 06 Nov 2014 17:07:35 GMT
Server: AkamaiNetStorage
Content-Length: 1687158
Cache-Control: max-age=29673477
Date: Sat, 10 Sep 2022 14:37:55 GMT
Connection: keep-alive
Akamai-Mon-Iucid-Del: 631717
Alt-Svc: h3-Q050=":443"; ma=93600,quic=":443"; ma=93600; v="46,43"
Content-Type: video/mp4
Access-Control-Max-Age: 86400
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del
Access-Control-Allow-Headers: origin,range,hdntl,hdnts
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: *
```

Please post the output of the `curl` command shown above.

**Comment by bastimeyer** [comment]
> `Expected #EXTM3U, but got <Mediapolis>`

Btw, this looks like there's some XML or another custom HTTP response instead of the HLS playlist content. Either way, I can't access it, and I've checked several different VPN services.

**Comment by Jeffade1** [comment]
Here are the debug logs for rai1, rai2 and the curl:

```text
streamlink -l debug https://www.raiplay.it/dirette/rai1 best
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/rai1.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803
[utils.l10n][debug] Language code: en_US
[stream.hls_playlist][warning] Malformed HLS Playlist. Expected #EXTM3U, but got <Mediapolis>
error: Failed to parse playlist: Missing #EXTM3U header
```

```text
streamlink -l debug https://www.raiplay.it/dirette/rai2 best
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai2
[plugins.raiplay][debug] Found JSON URL: https://www.raiplay.it/dirette/rai2.json
[plugins.raiplay][debug] Found stream URL: https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718
[utils.l10n][debug] Language code: en_US
[stream.hls_playlist][warning] Malformed HLS Playlist. Expected #EXTM3U, but got <Mediapolis>
error: Failed to parse playlist: Missing #EXTM3U header
```

```text
curl -sIL "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803"
HTTP/1.1 200 OK

HTTP/1.1 200 OK
Date: Sat, 10 Sep 2022 19:05:11 GMT
Server: Apache
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, OPTIONS, HEAD
Vary: X-Forwarded-Proto
X-Powered-By: JSP/2.2
Set-Cookie: JSESSIONID=vIbyMqx1bQc4ofepIrde1voL; Path=/relinker
Cache-Control: private
Expires: Sat, 10 Sep 2022 19:05:31 GMT
Content-Language: it-IT
Content-Length: 27
Content-Type: text/xml
```

**Comment by bastimeyer** [comment]
If you want, you can post the XML output of
```
$ curl -sL "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=2606803"
```
but I don't think that debugging it this way makes sense. As said, the result can be anything, but if I have to ask someone else for any server responses, then this is just stupid. Fixing and potentially re-implementing the plugin requires being able to see and understand all the HTTP responses.

**Comment by duunsupen** [comment]
Rai News24 is normally not geo blocked, if that is if any helo.
https://www.raiplay.it/dirette/rainews24

**Comment by bastimeyer** [comment]
> Rai News24 is normally not geo blocked, if that is of any help.

Had another look at the plugin and the site's JS player implementation.

Could you please test my dev branch?
https://github.com/streamlink/streamlink/compare/master...bastimeyer:streamlink:plugins/raiplay/fix-4816

Install via `pip`
```
pip install git+https://github.com/bastimeyer/streamlink.git@plugins/raiplay/fix-4816
```
Or sideload the plugin from here:
- https://raw.githubusercontent.com/bastimeyer/streamlink/52ed21ee7e261a47bf172d45e68c6529d1bbe63f/src/streamlink/plugins/raiplay.py
- https://streamlink.github.io/cli/plugin-sideloading.html

----

The rainews24 channel is working, but I can't test any other channels
```
$ streamlink https://www.raiplay.it/dirette/rainews24 best
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rainews24
[cli][info] Available streams: 432p (worst), 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

```
$ streamlink https://www.raiplay.it/dirette/rai1 best
[cli][info] Found matching plugin raiplay for URL https://www.raiplay.it/dirette/rai1
[plugins.raiplay][error] Geo-restricted content
error: No playable streams found on this URL: https://www.raiplay.it/dirette/rai1
```

The rainews24 channel requests the `content_url` (relinker API) with the `cont=1` query string parameter, but according to the JS, this also requires adding the `output=64` parameter with `64` being the `defaultMediapolisOutput` value (embedded in the JS), otherwise the response is empty. The same `output=64` parameter should apparently also get added to relinker API URLs from other channels, but those have a different `cont` value, and this is geo-restricted for me, so I can't validate this.

**Comment by Jeffade1** [comment]
@bastimeyer Just checked on rai1 & rai2. It works👍
