### ISSUE TITLE
plugins.ard_mediathek: audio delay

### ISSUE THREAD

**Issue by tmatthews5511** [streamlink/streamlink#4832]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

ARD: the audio is not in sync in Streamlink Version 5. 

### Debug log

```text
streamlink --http-proxy "xxxxxxxxxxxxxxxxxxxxxxxx" https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ 720p --loglevel debug
[cli][warning] Loaded config from deprecated path, see CLI docs for how to migrate: /home/timsan/.streamlinkrc
[cli][debug] OS:         Linux-5.4.0-125-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.0.0
[cli][debug] Dependencies:
[cli][debug]  PySocks: 1.7.1
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.4
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodome: 3.9.8
[cli][debug]  requests: 2.26.0
[cli][debug]  websocket-client: 1.2.1
[cli][debug]  importlib-metadata: 4.11.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ
[cli][debug]  stream=['720p']
[cli][debug]  --loglevel=debug
[cli][debug]  --player="/snap/vlc/2344/usr/bin/vlc"
[cli][debug]  --player-no-close=True
[cli][debug]  --http-proxy=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[cli][info] Found matching plugin ard_mediathek for URL https://www.ardmediathek.de/live/Y3JpZDovL2Rhc2Vyc3RlLmRlL2xpdmUvY2xpcC9hYmNhMDdhMy0zNDc2LTQ4NTEtYjE2Mi1mZGU4ZjY0NmQ0YzQ
```

**Comment by bastimeyer** [comment]
Why are you opening a new issue? You've already opened #4687, and there you can see that it's caused by "HLS packed audio", which is currently unsupported by Streamlink: #4721

**Comment by tmatthews5511** [comment]
Why was it working (so I thought) before Version 5?

**Comment by bastimeyer** [comment]
This was not working in earlier versions. The plugin is still includes, because this only affects some streams (if you had read the previous thread):
https://github.com/streamlink/streamlink/issues/4687#issuecomment-1200081520
