### ISSUE TITLE
Tiktok live streaming Capture

### ISSUE THREAD

**Issue by forceware680** [streamlink/streamlink#4844]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Tiktok now is most popular platform for LIVE STREAMING, creating, sharing and discovering short videos. The app is used by young people as an outlet to express themselves through singing, dancing, comedy, and lip-syncing, and allows users to create videos and share them across a community. I hope dev can make this best amazing plugin. thanks

### Input URLs

https://www.tiktok.com/@redi.44/live

**Comment by LaneSh4d0w** [comment]
It seems the stream goes through a websocket, here's the type of link when a stream is live : 
wss://webcast16-ws-useast1a.tiktok.com/webcast/im/push/?app_name=tiktok_web&version_code=180800&webcast_sdk_version=1.3.0&update_version_code=1.3.0&compress=gzip&imprp=u4wP7CtlXaCTd&internal_ext=fetch_time:1664015375883|start_time:0|flag:0|seq:1|next_cursor:1664015375883_7146891615666201185_1_1|wss_info:0-1664015375884-0-0&cursor=1664015375883_7146891615666201185_1_1&host=https://webcast.tiktok.com&aid=1988&live_id=12&debug=false&app_language=fr&device_platform=web&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=fr&browser_platform=Win32&browser_name=Mozilla&browser_version=5.0%20(Windows)&browser_online=true&tz_name=Europe/Paris&identity=audience&room_id=7146880571213449990&heartbeatDuration=0

**Comment by back-to** [comment]
you need an account, which is annoying to create.

There was already an issue, but nobody created a new plugin.
Ref https://github.com/streamlink/streamlink/issues/3705

closing
