### ISSUE TITLE
logger: custom trace() log level has incorrect module name on Python 3.11

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4862]
Python 3.11 has changed how the call stack gets read when creating a new log record:
https://github.com/python/cpython/commit/5ca6d7469be53960843df39bb900e9c3359f127f

This causes the log record's module name to be set to Streamlink's `logger` module where the custom `trace()` method is defined, which is incorrect.

Example:
https://github.com/streamlink/streamlink/actions/runs/3168863166/jobs/5160366442#step:5:285
https://github.com/streamlink/streamlink/pull/4861#issuecomment-1264654242

Is this worth of a Python but report, or do we need to change how the custom `trace()` method is defined?

- `Logger._log()`
  https://github.com/python/cpython/blob/v3.11.0rc2/Lib/logging/__init__.py#L1610-L1634
- `Logger.findCaller()`
  https://github.com/python/cpython/blob/v3.11.0rc2/Lib/logging/__init__.py#L1561-L1593

Since there's no way to pass a custom call stack to the `Logger._log()` method, the `stacklevel` needs to be increased from 1 to 2 on py311 from what it looks like, so that it skips the `logger` module at the beginning of the call stack:

```py
class StreamlinkLogger(_BaseLoggerClass):
    if sys.version_info < (3, 11):
        def trace(self, message, *args, **kws):
            if self.isEnabledFor(TRACE):
                self._log(TRACE, message, args, **kws)
    else:
        def trace(self, message, *args, **kws):
            if self.isEnabledFor(TRACE):
                kws["stacklevel"] = 2
                self._log(TRACE, message, args, **kws)
```

**Comment by gravyboat** [comment]
> Is this worth of a Python bug report, or do we need to change how the custom trace() method is defined?

I'll merge #4863 for now but it definitely seems like a bug.

**Comment by gravyboat** [comment]
@bastimeyer Thanks for following up to double check.
