### ISSUE TITLE
Feature Request: port livestreamer-curses over to streamlink-curses

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#488]
I like to work in shell, i found livestreamer-curses to be real handy, i wonder how hard it would be to port to streamlink-curses as livestreamer now appears defunct.
i not programmer , my 5 line shell scripts wont cut it, maybe someone with the skills can consider this.
regards.

**Comment by gravyboat** [comment]
Hey not sure if you meant to close this, but we discussed this a while back: https://github.com/streamlink/streamlink/issues/40

**Comment by cirrusUK** [comment]
i closed it as all one needs to do is change command from livrstreamer to streamlink in thr livesttreamer-cursesrc and it works splendid.

**Comment by RadicalEd360** [comment]
ive written a patch for livestreamer-curses, it makes it use streamlink and it also adds some color, let me know what you guys think!!!
https://github.com/RadicalEd360/Patches/tree/master/livestreamer-curses-v1.5.2
