### ISSUE TITLE
plugins.pixiv: No playable streams found

### ISSUE THREAD

**Issue by gyeolls** [streamlink/streamlink#4883]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

If you put the profile of the streamer you want to record in streamlink, it doesn't work. Even if it's online, it says it's offline
![1234](https://user-images.githubusercontent.com/109460459/195501387-dd273aac-75c2-4d66-bedd-8d09cac99f9a.png)

### Debug log

```text
C:\Users\ici>C:\Users\ici\Desktop\recordtest.bat
[cli][info] Found matching plugin pixiv for URL https://sketch.pixiv.net/@user_hpfw5388/lives/1965804384984715302
[cli][info] Waiting for streams, retrying every 1.0 second(s)
```

**Comment by bastimeyer** [comment]
Post the entire debug log (`--loglevel=debug`), as requested by the plugin issue template.

The stream you're trying to access requires being logged in.
https://streamlink.github.io/plugins.html#pixiv

**Comment by back-to** [comment]
you need to copy 2 cookies from your browser and use this commands.

```
--pixiv-sessionid SESSIONID

    The pixiv.net sessionid that's used in pixiv's PHPSESSID cookie.

--pixiv-devicetoken DEVICETOKEN

    The pixiv.net device token that's used in pixiv's device_token cookie.

```

```
[plugins.pixiv][info] Successfully set sessionId and deviceToken
```
