### ISSUE TITLE
plugins.okru: m3u8 doesn't work

### ISSUE THREAD

**Issue by skizoDUR** [streamlink/streamlink#4888]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Input:
`streamlink --stream-url video_url`
Expected output:
a valid link for playing the video
Actual output
A link that does point to a m3u8 file but doesn't play anywhere, (tried vlc, firefox) the file seems to have timestamps but no links to a stream, so to speak

comments:
It does allow me to play the video on vlc if I just run streamlink with no arguments, but that doesn't help my use case. --loglevel debug doesn't print any errors

### Debug log

```
[cli][debug] OS:         Linux-5.4.0-125-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug]  importlib-metadata: 1.5.0
[cli][debug] Arguments:
[cli][debug]  url=https://ok.ru/video/3741307243140
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin okru for URL https://ok.ru/video/3741307243140
[utils.l10n][debug] Language code: es_AR
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)


```

**Comment by bastimeyer** [comment]
> Use the [--loglevel debug](https://streamlink.github.io/latest/cli.html#cmdoption-loglevel) parameter **and avoid using parameters which suppress log output.**
> Debug log includes important details about your platform. **Don't remove it.**

Post the debug log output.

The plugin is working correctly. Make sure that you are using the **latest version**

```
$ streamlink -l debug https://ok.ru/video/3741307243140
[cli][debug] OS:         Linux-5.17.0-rc6-1-git-01758-gb3c76814ce5b-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.8
[cli][debug] Streamlink: 5.0.1+18.g411ec7a9
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.1
[cli][debug]  importlib-metadata: 5.0.0
[cli][debug] Arguments:
[cli][debug]  url=https://ok.ru/video/3741307243140
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin okru for URL https://ok.ru/video/3741307243140
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
```

**Comment by skizoDUR** [comment]
log updated

@bastimeyer 

indeed the plugin works with vlc or mpv, but `--stream-url` doesn't output a usable stream url

**Comment by mkbloke** [comment]
The plugin sets the `Referer` header, so maybe you'll need to set that within VLC.  I don't know how you do that and it's not supported by this project, so you'll need to figure out what else might need setting or correcting (e.g. the `User-Agent` header) by yourself.  The plugin is working; using the streaming URL correctly outside of the plugin is not something this project can support.

**Comment by bastimeyer** [comment]
```
$ streamlink -j https://ok.ru/video/3741307243140 best | jq .headers
{
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0",
  "Accept-Encoding": "gzip, deflate",
  "Accept": "*/*",
  "Connection": "keep-alive",
  "Referer": "https://ok.ru/video/3741307243140",
  "Cookie": "tstc=p"
}
```
