### ISSUE TITLE
launch attempts

### ISSUE THREAD

**Issue by skapytek** [streamlink/streamlink#489]
Hello,
Is it possible to increase the launch attempts?
Actually the maximum is 10.
Is it possible to increase this to a user specified setting?
Sometimes the streamer have a problem with his internet connection and this will last for some minutes.
![2017-01-26 00_49_35-streamlink twitch gui](https://cloud.githubusercontent.com/assets/11317488/22314415/96559ede-e361-11e6-92fe-d65042166e9e.png)

best regards

**Comment by gravyboat** [comment]
Where is this interface coming from? Streamlink-twitch-gui?

**Comment by skapytek** [comment]
Hi, yes its from the streamlink-twitch-gui.
I already reported it there, but i was not sure if this is function is limited by streamlink or streamlink-twitch-gui.
So streamlink isnt limiting the launch attempts?

regards

**Comment by gravyboat** [comment]
I would have to look at the code, I'm not sure. I'll try to make time to take a look this evening.

**Comment by bastimeyer** [comment]
It's not limited...
https://github.com/streamlink/streamlink/blob/0.3.0/src/streamlink_cli/argparser.py#L460-L470

**Comment by stevek123** [comment]
The limitation is in the GUI: https://github.com/streamlink/streamlink-twitch-gui/issues/401

**Comment by skapytek** [comment]
Thanks guys for the answers.
