### ISSUE TITLE
Name of the webspeeks.comite / streaming provider

### ISSUE THREAD

**Issue by ovladuk** [streamlink/streamlink#4894]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

peeks is a live streaming social website

### Input URLs

https://www.peeks.com/channel/channel?id=1

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
