### ISSUE TITLE
plugins.atresplayer: error on geoblocked URL

### ISSUE THREAD

**Issue by tvfj** [streamlink/streamlink#4895]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Decoding problem on geoblocked URL

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.atresplayer.com/directos/atreseries/
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/atreseries/
[plugins.atresplayer][debug] API URL: https://api.atresplayer.com/client/v1/page/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][debug] Player API URL: https://api.atresplayer.com/player/v1/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][debug] Stream source: https://directo.atresmedia.com/b1034a56122970fb8a21aef56eae996ba1d5b049_1666228065/geoa3series/master.m3u8 (application/vnd.apple.mpegurl)
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://directo.atresmedia.com/b1034a56122970fb8a21aef56eae996ba1d5b049_1666228065/geoa3series/master.m3u8 (('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check')))
```

**Comment by mkbloke** [comment]
Can you say from which country you are accessing this URL?

I presume you know it's geo-blocked because you have visited this URL with a web browser?

The content is geo-blocked for me, but the detection seems to be working:
```
$ streamlink -l debug 'https://www.atresplayer.com/directos/atreseries/'
[cli][debug] OS:         Linux-5.4.0-125-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.0.1+20.g55649ecc
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  importlib-metadata: 4.11.4
[cli][debug] Arguments:
[cli][debug]  url=https://www.atresplayer.com/directos/atreseries/
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/atreseries/
[plugins.atresplayer][debug] API URL: https://api.atresplayer.com/client/v1/page/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][debug] Player API URL: https://api.atresplayer.com/player/v1/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][error] Player API error: geoblocked - Content is geoblocked
error: No playable streams found on this URL: https://www.atresplayer.com/directos/atreseries/

```
It would appear that nothing relevant to your issue has changed since the release of Streamlink 5.0.1.

**Comment by tvfj** [comment]
```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.atresplayer.com/directos/atreseries/
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --http-header=[('Accept-Encoding', 'identity')]
[cli][info] Found matching plugin atresplayer for URL https://www.atresplayer.com/directos/atreseries/
[plugins.atresplayer][debug] API URL: https://api.atresplayer.com/client/v1/page/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][debug] Player API URL: https://api.atresplayer.com/player/v1/live/5a6a189a7ed1a834493ebf70
[plugins.atresplayer][debug] Stream source: https://directo.atresmedia.com/e8b5345c1528500eeaec63dce968fe158703f1fd_1666254064/geoa3series/master.m3u8 (application/vnd.apple.mpegurl)
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://directo.atresmedia.com/e8b5345c1528500eeaec63dce968fe158703f1fd_1666254064/geoa3series/master.m3u8 (404 Client Error: Not Found for url: https://directo.atresmedia.com/e8b5345c1528500eeaec63dce968fe158703f1fd_1666254064/geoa3series/master.m3u8)
```

**Comment by bastimeyer** [comment]
> 404 Client Error: Not Found for url

As you can see [here](https://github.com/streamlink/streamlink/blob/55649ecc2a5185fe1f0cfe4a9b8b51c35c8cedb4/src/streamlink/plugins/atresplayer.py#L51-L73), the geo-block detection happens when querying the player API. If they don't return an error and instead return regular HLS playlist URLs, then this is not the plugin's fault if the playlist requests result in a 404 response.

We could set the `Accept-Encoding: identity` header on the HLSStream stuff though in order to fix their broken server config. It shouldn't matter for regular HLS streams, because content won't be compressed anyway and m3u8 compression doesn't matter.

**Comment by Jeffade1** [comment]
Just checked. The stream source url changed.

Before:
https://directo.atresmedia.com/7b313a4743e0a4693b6ca91ae6b86c91be3bf6ec_1666286194/geomega/master.m3u8

Now:
https://atres-live.atresmedia.com/6f94320bfc55f056912fe9244a1ff2e2842d770f_ES_1666257486_1666286226/h264/live/mega/master.m3u8

**Comment by bastimeyer** [comment]
> The stream source url changed.

I guess you mean that the player API now returns the correct stream URL, right? If that's the case (and the plugin is working), then this thread should be closed.

**Comment by Jeffade1** [comment]
No.
If we load the stream via streamlink it will open the old m3u8 starting by "https://directo.atresmedia.com/" where the stream isn't anymore
If I we load the stream normally via the browser it will open the new m3u8 starting by "https://atres-live.atresmedia.com/"

**Comment by Jeffade1** [comment]
The old m3u8 that was down these last days started to work again today. Let's be attentive and see if it's temporary or find a solution. On the website it still load the new url.
