### ISSUE TITLE
R channel japan

### ISSUE THREAD

**Issue by japanXXX** [streamlink/streamlink#4900]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

C:\WINDOWS\system32>streamlink https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazonaws.com/v1/mas
ter/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8
[cli][info] Found matching plugin hls for URL https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazo
naws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8
Available streams: 216p_alt2 (worst), 216p_alt, 216p, 360p_alt2, 360p_alt, 360p, 540p_alt2, 540p_alt, 540p, 720p_alt2,
720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p (best)

C:\WINDOWS\system32>streamlink https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazonaws.com/v1/mas
ter/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8 best
[cli][info] Found matching plugin hls for URL https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazo
naws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8
[cli][info] Available streams: 216p_alt2 (worst), 216p_alt, 216p, 360p_alt2, 360p_alt, 360p, 540p_alt2, 540p_alt, 540p,
 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls-multi)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[utils.named_pipe][info] Creating pipe streamlinkpipe-3680-1-9064
[utils.named_pipe][info] Creating pipe streamlinkpipe-3680-2-3288
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[cli][error] Try 1/1: Could not open stream <MuxedHLSStream ['hls-multi', 'https://bdbc7cd4986249dfa0a07512dc10f48a.med
iatailor.ap-northeast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playl
ist.m3u8']> (No data returned from stream)
error: Could not open stream <MuxedHLSStream ['hls-multi', 'https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-nor
theast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8']>, tr
ied 1 times, exiting
[cli][info] Closing currently open stream...

C:\WINDOWS\system32>streamlink https://216c8080fdd94c0c825ef7ae7b4debfd.mediatailor.ap-northeast-1.amazonaws
.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation1/playlist.m3u8 best
[cli][info] Found matching plugin hls for URL https://216c8080fdd94c0c825ef7ae7b4debfd.mediatailor.ap-northeast-1.amazo
naws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation1/playlist.m3u8
[cli][info] Available streams: 216p_alt2 (worst), 216p_alt, 216p, 360p_alt2, 360p_alt, 360p, 540p_alt2, 540p_alt, 540p,
 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls-multi)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[utils.named_pipe][info] Creating pipe streamlinkpipe-4428-1-7810
[utils.named_pipe][info] Creating pipe streamlinkpipe-4428-2-696
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[cli][error] Try 1/1: Could not open stream <MuxedHLSStream ['hls-multi', 'https://216c8080fdd94c0c825ef7ae7b4debfd.med
iatailor.ap-northeast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation1/playl
ist.m3u8']> (No data returned from stream)
error: Could not open stream <MuxedHLSStream ['hls-multi', 'https://216c8080fdd94c0c825ef7ae7b4debfd.mediatailor.ap-nor
theast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation1/playlist.m3u8']>, tr
ied 1 times, exiting
[cli][info] Closing currently open stream...

C:\WINDOWS\system32>streamlink -l debug https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.
amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8 best
[cli][debug] OS:         Windows 8.1
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazonaws.com/v1/master/44f73ba4d
03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin hls for URL https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazo
naws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8
[plugins.hls][debug] URL=https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-northeast-1.amazonaws.com/v1/master/44
f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8; params={}
[utils.l10n][debug] Language code: en_US
[stream.hls][debug] Using external audio tracks for stream 360p (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 360p_alt (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 360p_alt2 (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 1080p (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 1080p_alt (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 1080p_alt2 (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 216p (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 216p_alt (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 216p_alt2 (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 540p (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 540p_alt (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 540p_alt2 (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 720p (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 720p_alt (language=und, name=und)
[stream.hls][debug] Using external audio tracks for stream 720p_alt2 (language=und, name=und)
[cli][info] Available streams: 216p_alt2 (worst), 216p_alt, 216p, 360p_alt2, 360p_alt, 360p, 540p_alt2, 540p_alt, 540p,
 720p_alt2, 720p_alt, 720p, 1080p_alt2, 1080p_alt, 1080p (best)
[cli][info] Opening stream: 1080p (hls-multi)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[stream.ffmpegmux][debug] Opening hls substream
[stream.hls][debug] Reloading playlist
[utils.named_pipe][info] Creating pipe streamlinkpipe-4148-1-1017
[utils.named_pipe][info] Creating pipe streamlinkpipe-4148-2-6608
[stream.ffmpegmux][debug] ffmpeg command: C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe -nostats -y -i \\.\pipe\streaml
inkpipe-4148-1-1017 -i \\.\pipe\streamlinkpipe-4148-2-6608 -c:v copy -c:a copy -map 0:v? -map 0:a? -map 1:a -f mpegts p
ipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\streamlinkpipe-4148-1-1017
[stream.ffmpegmux][debug] Starting copy to pipe: \\.\pipe\streamlinkpipe-4148-2-6608
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 2018437; Last Sequence: 2018446
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2018444; End Sequence: None
[stream.hls][debug] Adding segment 2018444 to queue
[stream.hls][debug] Adding segment 2018445 to queue
[stream.hls][debug] Adding segment 2018446 to queue
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 2018437; Last Sequence: 2018446
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2018444; End Sequence: None
[stream.hls][debug] Adding segment 2018444 to queue
[stream.hls][debug] Adding segment 2018445 to queue
[stream.hls][debug] Adding segment 2018446 to queue
[stream.hls][error] Failed to create decryptor: Unable to decrypt cipher SAMPLE-AES
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.ffmpegmux][debug] Pipe copy complete: \\.\pipe\streamlinkpipe-4148-1-1017
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.ffmpegmux][debug] Closed all the substreams
[cli][error] Try 1/1: Could not open stream <MuxedHLSStream ['hls-multi', 'https://bdbc7cd4986249dfa0a07512dc10f48a.med
iatailor.ap-northeast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playl
ist.m3u8']> (No data returned from stream)
error: Could not open stream <MuxedHLSStream ['hls-multi', 'https://bdbc7cd4986249dfa0a07512dc10f48a.mediatailor.ap-nor
theast-1.amazonaws.com/v1/master/44f73ba4d03e9607dcd9bebdcb8494d86964f1d8/RakutenJP-web_Animation2/playlist.m3u8']>, tr
ied 1 times, exiting
[cli][info] Closing currently open stream.
　
animation1 animation2 Not downloadable...........

I ask you to respond(*´ω｀)

![WS000003](https://user-images.githubusercontent.com/116476721/197461225-ddbd2f2e-0ae5-4aac-9fe8-fbbef222f5df.JPG)
![WS000004](https://user-images.githubusercontent.com/116476721/197461254-770de494-a1a2-49e2-b47b-95d054cb0e70.JPG)

### Input URLs

https://channel.rakuten.co.jp/  　
https://channel.rakuten.co.jp/_next/static/chunks/pages/_app- ().js =all_get m3u8_URL
https://channel.rakuten.co.jp/programs/2022-XX-XX.json = m3u8 of past deliveries

https://ja.wikipedia.org/wiki/R%E3%83%81%E3%83%A3%E3%83%B3%E3%83%8D%E3%83%AB  R channel wiki

Request the creation of a plug-in that enables downloads('ω')

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
