### ISSUE TITLE
dependencies: missing cp311 lxml wheels (Python 3.11 based Windows builds & Linux AppImages)

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#4903]
Opening this thread on the main Streamlink issue tracker since I don't want to open multiple threads on different issue trackers... This is also related to
- #4806
- #4810

----

[Python 3.11 has finally been released yesterday](https://docs.python.org/release/3.11.0/whatsnew/changelog.html#python-3-11-0-final) and [`lxml` still hasn't published any cp311 wheels](https://pypi.org/project/lxml/4.9.1/#files) for

- macosx_10_15_x86_64
- manylinux2014_aarch64
- manylinux2010_i686
- win32
- win_amd64

According to their issue tracker, the reason for this seems to be the lack of CPython 3.11 builds on AppVeyor, which their build infrastructure depends on:
https://bugs.launchpad.net/lxml/+bug/1977998

Once this is resolved and all missing official lxml wheels have been published by the lxml developer, I will

- [ ] remove the custom lxml wheel build from the CI runner setup which was added by #4810
- [x] replace the CI test runners based on "3.11-dev" with "3.11" ones (they are currently still allowed to fail which I forgot to change when the custom lxml wheel was added - don't want to change this now, even though it should be fine)  
  (Python 3.11 for GitHub actions has just been made available four hours ago: https://github.com/actions/python-versions/blob/0d8f04f6f88c74ab964d44f4b04dd5d8c9ebce1a/versions-manifest.json)
- [x] update and publish new Windows builds and AppImages based on Python 3.11 with only offically built wheels. I've already updated the [Python Windows-embed builds](https://github.com/streamlink/python-windows-embed/releases/tag/20221025-1) and [AppImage buildenv docker images](https://github.com/streamlink/appimage-buildenv/releases/tag/20221025-1) earlier today.

We can also have a look at publishing a new Streamlink release later this week.

**Comment by sreenivasulureddysura** [comment]
@bastimeyer Windows install is failing for lxml 4.9.1 version.

**Comment by bastimeyer** [comment]
@sreenivasulureddysura 
The issue you've linked doesn't look like it has anything to do with Streamlink, so I guess you must've found this issue thread here by googling. Your issue is not related to Streamlink at all and you'll have to wait for the lxml dev to finally merge the opened PRs (for building the missing lxml wheels) and publish a new release. Streamlink is just another project which depends on lxml, like python3-saml.

See lxml/lxml#356

Also, as you can see in the OP, I've built a custom lxml 4.9.1 cp311 wheel for Windows which Streamlink is using since two and a half months, so we can have cp311 CI runners without build failures. This custom wheel is however not meant as an alternative for production use due to how libxml2 and libxslt are built (the dependencies of lxml).

**Comment by bastimeyer** [comment]
Status update of the AppImages with other changes like nightly builds, etc:
https://github.com/streamlink/streamlink-appimage/issues/2
