### ISSUE TITLE
plugins.crunchyroll: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by ZacharyArthur** [streamlink/streamlink#4908]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Crunchyroll plugin no longer works as the beta site has now become the default Crunchyroll site with the old site gone., at least in the US. This happens for free content as well as premium. Used a free episode for the example here.

### Debug log

```text
C:\Users\*****\Desktop\MPV>streamlink https://www.crunchyroll.com/watch/GYNV4DD0R/rent-a-girlfriend --loglevel=debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.crunchyroll.com/watch/GYNV4DD0R/rent-a-girlfriend
[cli][debug]  --loglevel=debug
[cli][debug]  --player="C:\Users\zaart\Desktop\MPV\mpv.exe"
[cli][debug]  --player-no-close=True
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin crunchyroll for URL https://www.crunchyroll.com/watch/GYNV4DD0R/rent-a-girlfriend
error: Unable to open URL: https://www.crunchyroll.com/watch/GYNV4DD0R/rent-a-girlfriend (403 Client Error: Forbidden for url: https://www.crunchyroll.com/watch/GYNV4DD0R/rent-a-girlfriend)
```

**Comment by gravyboat** [comment]
Similar to https://github.com/streamlink/streamlink/issues/4790 but a slightly different output. Seems like crunchyroll may be done with the beta version of the site?

**Comment by NicholasLefave** [comment]
The beta does seem to be over. It no longer auto-redirects for me  to the subaddress while I was in beta.

**Comment by neko47834** [comment]
I just tried Crunchyroll premium with Streamlink and it does give an error with the new Links:
before [WORKS]:
https://www.crunchyroll.com/es/twin-star-exorcists/episode-6-benio-and-mayura-girls-party-702567

After [ERROR 404]: https://www.crunchyroll.com/es/watch/GR75KX8ZY/benio-and-mayura---girls-party

Streamlink seems to work without problems with the Links from before, the problem is that there is no way to see how those links were before since the beta is already the default template of the page

**Comment by neko47834** [comment]
Link new:
![e2](https://user-images.githubusercontent.com/40369442/210294244-ae1cb587-d45e-4a5a-911a-abdfccd2f921.png)
Link old:
![img1](https://user-images.githubusercontent.com/40369442/210294245-0b2a53ac-b765-4324-8f90-19abf85ff412.jpg)

**Comment by yyolk** [comment]
As of the latest 5.4.0 release this still seems to be an issue. I'm hoping this context may be useful for anyone looking into this.

What appears to be happening in my testing is a `HTTP: 403` occurs before any page can be grabbed. 

It could be just my rapid testing but it appears to happen if the proper cloudfront cookies aren't set and you're hit with cloudfront throttling. I believe I'm able to get the same results if I curl the video page without logging in or even providing the `session_id` I was sent to the CloudFlare waiting room. I'm also not sure if this would work to begin with, but I tried it) you're sent to a waiting room.

I naively attempted to extract all cookies from my logged-in-session on crunchyroll.com and evoked a `streamlink.Streamlink()` instance like:

```python
sl = streamlink.Streamlink()
sl.set_option("http-cookies", "...<long serialized cookie string>...")
```
however that didn't help, and resulted in the same error when invoking it without.
either setting `username` & `password` or `session_id` results in the same result (getting stopped at `HTTP: 403`), same as with just `curl`'ing the URL directly

I was trying a happy path with both (mutually exclusively set) options which again resulted in the same `HTTP: 403`:
```python
sl.set_plugin_option("crunchyroll", "username", "my_username@example.com")
sl.set_plugin_option("crunchyroll", "password", "my_password")
```
or
```python
sl.set_plugin_option("crunchyroll", "session_id", "<session_id_extracted_from_browser_cookie>")
```
then invoking `.streams(...)` on the `Streamlink()` instance:

```python
sl.streams("https://www.crunchyroll.com/watch/<vid>/<slug>")
```

**Comment by kjjk10** [comment]
yt-dlp works with CrunchyRoll, maybe worth looking into their implementation

**Comment by feeaghdoo** [comment]
I experimented with making HTTPSession a child of CloudScraper rather than Session, and that seems to have gotten past the Cloudflare page. Probably not actually suitable given the complicated stuff you all are doing with HTTPSession. After that though, it looks like the media ID pulled from the web page and used in the CR desktop application API is no longer supplied in the web page.
