### ISSUE TITLE
TV Republika - private polish tv

### ISSUE THREAD

**Issue by Irek7** [streamlink/streamlink#4911]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Polish commercial news channel

### Input URLs

https://tvrepublika.pl/live

**Comment by mkbloke** [comment]
This site seems to use a static playlist URL, so no plugin is really required:
```
$ streamlink 'https://redir.cache.orange.pl/jupiter/o1-cl7/ssl/live/tvrepublika/live.m3u8'
[cli][info] Found matching plugin hls for URL https://redir.cache.orange.pl/jupiter/o1-cl7/ssl/live/tvrepublika/live.m3u8
Available streams: 288p_alt (worst), 288p, 404p, 576p, 720p, 1080p (best)
```
