### ISSUE TITLE
Feat for Title rename or Help

### ISSUE THREAD

**Issue by Dan-Y89** [streamlink/streamlink#4913]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Hello,

I have a request concerning the data output.
I have now read/searched the Streamlink Command Line Interface and the Helpsection here a thousand times and unfortunately did not find anything.
If this should exist somewhere, I'm sorry, but as I said, I haven't found anything helpful where I'm really helped or told how to solve the problem.
So: There are things that you record more often in a day with the same titles but at different times and I only found an option to overwrite the output, but the problem is: You don't want to constantly delete the old recording or manually rewrite it.
But now I hope for help or a solution that allows you to record existing titles anyway. eg. auto rename file, which automatically writes a 1_2_3_4 at the end of the title and the recording continues, even though the title already existed. I'm hoping for a solution or implementation or a tutorial on the solution if there is one.
PS: Forgive me my English is not the best.
Greetings from Germany and thanks for your work.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/metadata.html
