### ISSUE TITLE
TV8,5

### ISSUE THREAD

**Issue by kaypoush** [streamlink/streamlink#4925]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

It's a Turkish TV channel owned by Acun Medya Group from the same family as TV8 which has already a plugin. This could be added in that existing plugin. Streams can be extracted from HTML/JS:

```                
function getgeoip(isTurkey){
                        var configPlayer = {
                            autoplay: true,
                            fullscreen: true,
                            id: 'acnpl',
                            container: document.getElementById('AcunnPlayerContainer'),
                            ima:{
                                swf:"//img.tv8bucuk.com/s/template/v2/player/swf/IMAFlashSdk.swf"
                            },
                            source: {
                                videoid: '0',
                                media: []
                            },
                            ads:  [
                            ]
                        };
                        if(isTurkey)
                        {
                            configPlayer.source.media.push({'src':  "https://tv8-tb-live.ercdn.net/tv8bucuk/tv8bucuk.m3u8?st=U94PKDb_DqABuJnEnnp9Fw&e=1667760706", type: "application/x-mpegURL"});
                            
                            ply.push(new acunn.player(configPlayer));
                            triggerStatics();
                            //triggerAds();
                        }
                        else
                        {
                            configPlayer.source.media.push({'src':  "https://tv8-tb-live.ercdn.net/tv8bucuk/tv8bucuk.m3u8?st=U94PKDb_DqABuJnEnnp9Fw&e=1667760706", type: "application/x-mpegURL"});
                                
                                ply.push(new acunn.player(configPlayer));
                                triggerStatics();
                                //triggerAds();
                        }
                    }
```

It seems that there are two separate streams depending on if you live in Turkey or not but as you can see from this example both streams are the same. I tested from France. I think that maybe in some occasions these streams are not the same (e.g. when they don't have the rights to show a content outside of Turkey). But I guess it doesn't matter because both streams will still be present in the code and the Turkish stream should be preferred as it should always work (?).

Regex draft: `'src':\s\s([\"])(https?://.*?\.m3u8.*?)([\"])`

### Input URLs

1. https://www.tv8bucuk.com/tv8-5-canli-yayin

**Comment by bastimeyer** [comment]
Updating the plugin is pretty straightforward and should be okay according to the plugin request guidelines. However, the site has a broken TLS certificate, so when requesting the address, this error gets raised:

```
$ streamlink 'www.tv8bucuk.com/tv8-5-canli-yayin'
[cli][info] Found matching plugin tv8 for URL www.tv8bucuk.com/tv8-5-canli-yayin
error: Unable to open URL: https://www.tv8bucuk.com/tv8-5-canli-yayin (HTTPSConnectionPool(host='www.tv8bucuk.com', port=443): Max retries exceeded with url: /tv8-5-canli-yayin (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)'))))
```

https://www.ssllabs.com/ssltest/analyze.html?d=www.tv8bucuk.com&hideResults=on

```
$ openssl s_client -connect www.tv8bucuk.com:443 -brief
depth=0 CN = *.tv8bucuk.com
verify error:num=20:unable to get local issuer certificate
depth=0 CN = *.tv8bucuk.com
verify error:num=21:unable to verify the first certificate
CONNECTION ESTABLISHED
Protocol version: TLSv1.2
Ciphersuite: AES256-SHA
Peer certificate: CN = *.tv8bucuk.com
Verification error: unable to verify the first certificate
```

Setting the HTTPS adapter to [`TLSSecLevel1Adapter`](https://github.com/streamlink/streamlink/blob/5.0.1/src/streamlink/plugin/api/http_session.py#L202-L207) doesn't have any effect, which means `verify` would need to be set to `False`, which is bad.

```
$ streamlink 'www.tv8bucuk.com/tv8-5-canli-yayin' --http-no-ssl-verify
[cli][info] Found matching plugin tv8 for URL www.tv8bucuk.com/tv8-5-canli-yayin
/home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.tv8bucuk.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'tv8-tb-live.ercdn.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Available streams: 360p (worst), 576p (best)
```

**Comment by kaypoush** [comment]
Yes I saw that error too. Maybe it's temporary. Anyway I contacted them about this issue and I hope they will fix it.

**Comment by omergumus** [comment]
Where exactly do I add this code? I want to run it and try it. System: Ubuntu server.

**Comment by mkbloke** [comment]
The code above is JS from the website.  The code for the modified plugin that bastimeyer is testing is not available yet.

**Comment by kaypoush** [comment]
> Where exactly do I add this code? I want to run it and try it. System: Ubuntu server.

You can use this for now until it's properly implemented:
```
mkdir plugins
wget -P plugins 'https://gist.githubusercontent.com/kaypoush/0f5efa50373012901985c18d1bcb1f7a/raw/1d88c830edf7b2a6ed082713ea7ab11de7f0a01a/tv8bucuk.py'
streamlink 'https://www.tv8bucuk.com/tv8-5-canli-yayin' best --plugin-dirs plugins --http-no-ssl-verify
```

**Comment by omergumus** [comment]
> > Where exactly do I add this code? I want to run it and try it. System: Ubuntu server.
> 
> You can use this for now until it's properly implemented:
> 
> ```
> mkdir plugins
> wget -P plugins 'https://gist.githubusercontent.com/kaypoush/0f5efa50373012901985c18d1bcb1f7a/raw/1d88c830edf7b2a6ed082713ea7ab11de7f0a01a/tv8bucuk.py'
> streamlink 'https://www.tv8bucuk.com/tv8-5-canli-yayin' best --plugin-dirs plugins --http-no-ssl-verify
> ```

thank you very much. It worked successfully.

**Comment by HalowTV** [comment]
Hi i run Ubuntu 18.4 
How is run i mean  
Putt on plugin is on root and white ssh  run
streamlink 'https://www.tv8bucuk.com/tv8-5-canli-yayin' best --plugin-dirs plugins --http-no-ssl-verify

How i get Link like m3u8 Whit My ip work on vlc?

**Comment by mkbloke** [comment]
Any thoughts on what to do with this?

On the one hand, the OP has already implemented their own private plugin, so it could just be closed.

On the other hand, I have a modified tv8 plugin that works for both sites.  It does, as noted above, require the used of `--http-no-ssl-verify` because it would appear `tv8bucuk.com` doesn't bundle an intermediate certificate.  This isn't great, but given there are probably going to be hardly any users of this site/plugin, it might not be such an issue.

**Comment by mkbloke** [comment]
Closing.  See #5098 for further discussion.
