### ISSUE TITLE
Add Support for VLC Media Sources in OBS

### ISSUE THREAD

**Issue by Serenmew** [streamlink/streamlink#4931]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I run a lot of online events on Twitch and every person I know that does the same uses streamlink with either VLC or MPV. This works great and is fantastic, but is a bit clunky, and ends up with many windows making it difficult to control syncing streams with each other, adjusting volume levels etc. Being able to directly open streams using streamlink into VLC media sources would make things infinitely better and open up a lot of avenues for stream automation and improvements.

I'm currently using a python script within OBS to load direct twitch links from streamlink into OBS media sources (not vlc media sources as they cannot be paused). However this is a bit of a clunky solution, and causes a lot of issues because OBS media source is not great at playing back live content. VLC media source however is.

I'm not sure what percentage of us event hosts really make up in the grand scheme of streamlink, but this would be a huge improvement for us. I'm not sure how hard this would be to implement or if it's within the scope of the project but thank you for considering it.

**Comment by bastimeyer** [comment]
What you're asking for has nothing to do with Streamlink. Streamlink's sole purpose is to output a media stream from a given input URL. How this output stream is then read depends on the application that's being used in the next step afterwards. Streamlink CLI by default opens a video player, as it's the most common use case, but that's about it. If you're looking for any integration into other applications, then this is not the place to ask for it.
