### ISSUE TITLE
myvideo.ge

### ISSUE THREAD

**Issue by bidalote** [streamlink/streamlink#4933]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

What is the site about? - Video streaming site
Who is it governed by? - ITDC
What content does it provide? - It provides video and TV channels
Are there any access restrictions such as logging in or checking the region? - No

### Input URLs

https://tv.myvideo.ge
https://myvideo.ge
https://tv.myvideo.ge/vendor.html?lang=en&epg=true&ads=false&watermark=false&channels=true&forceDesktop=false

**Comment by mkbloke** [comment]
I see the live section of this website indicates that it's still undergoing testing, so rule 9 may apply here.

As it is, the site offers VODs and TV.  Pure VOD sites are not supported (rule 6).  The question of TV based sites is still under discussion, although it would have to meet rules 2 and 3.

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

It seems straightforward enough to write a plugin for this site, but it would be better to wait until it properly supports live streams before doing so.

**Comment by bidalote** [comment]
Hello.I have been watching the site in this form for 2 years now, no changes or interruptions have occurred.Sent from my iPhoneOn 9. Nov 2022, at 18:20, Ian Cameron ***@***.***> wrote:﻿
I see the live section of this website indicates that it's still undergoing testing, so rule 9 may apply here.
As it is, the site offers VODs and TV.  Pure VOD sites are not supported (rule 6).  The question of TV based sites is still under discussion, although it would have to meet rules 2 and 3.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests
It seems straightforward enough to write a plugin for this site, but it would be better to wait until it properly supports live streams before doing so.
