### ISSUE TITLE
stream.hls: Exception in HLSStreamWriter

### ISSUE THREAD

**Issue by jenlunds** [streamlink/streamlink#4938]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

This started happening in the last 24h on twitch streams and is probably related to the the other twitch issue posted. The problem here appears on most streams i try to play with **--twitch-disable-ads** set. Without it it works fine. (I removed the last part of the log, the part after _https://video-weaver_, because my IP was shown and maybe something more I don't know about. If that's not OK feel free to close this.)

### Debug log

```text
$ streamlink https://www.twitch.tv/alanzoka 360p --twitch-disable-hosting --twitch-disable-ads --loglevel debug
[cli][debug] OS:         Linux-5.4.0-131-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.6.4
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodome: 3.10.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.26.0
[cli][debug]  websocket-client: 1.2.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/alanzoka
[cli][debug]  stream=['360p']
[cli][debug]  --loglevel=debug
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-disable-hosting=True
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/alanzoka
[plugins.twitch][debug] Getting live HLS streams for alanzoka
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 360p (hls)
[cli][info] Starting player: /usr/bin/vlc
[plugins.twitch][info] Will skip ad segments
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][debug] First Sequence: 0; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
Exception in thread Thread-TwitchHLSStreamWriter:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python3.8/site-packages/streamlink/stream/segmented.py", line 209, in run
    self.write(segment, result, *data)
  File "/home/user/.local/lib/python3.8/site-packages/streamlink/stream/hls.py", line 217, in write
    result.raw.drain_conn()
AttributeError: '_HTTPResponse' object has no attribute 'drain_conn'
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 22 to queue
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <TwitchHLSStream ['hls', 'https://video-weaver... 

------REDACTED-------

tried 1 times, exiting
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
`--twitch-disable-ads` triggers a different code path in the `HLSStreamWriter` when writing or filtering out HLS segments. The writer was updated a while ago with a bugfix to clean up stalled HTTP requests in the HTTP connection pool when filtering. To do this, a method from `urllib3` gets called, which was only added in `1.26.0`. While `1.26.0` was released more than two years ago, it's still supported by the specified version ranges of Streamlink and the `requests` library, which defines `urllib3` as a transitive dependency.

According to your log output, you have installed Streamlink via pip in your local user's python environment (via the `--user` flag, or implicitly installed there) at `~/.local/`. If `urllib3` is not part of that user environment, then it'll be looked up by the Python interpreter in your system's python environment at `/usr/share/`. Depending on your distro, this can be outdated. You should however be able to install or update it in your user environment. Just run `pip install --user --upgrade urllib3` or install all the latest dependencies of Streamlink via `pip install --user --upgrade --upgrade-strategy=eager streamlink`. However, it's always better to install python projects in separate environments via the `virtualenv` library, so you don't risk introducing dependency conflicts with other applications:
https://streamlink.github.io/install.html#virtual-environment

**Comment by bastimeyer** [comment]
The reason why you're only seeing this issue now is that Twitch simply didn't embed any ads for Streamlink to filter out. Now that ads are embedded once again, the filtering code path is used.

**Comment by mk-pmb** [comment]
I have the same error message using current master (0bda6e1f "release: 5.1.0"). I upgraded because I got those messages starting last week, when I was still on some 3.?? branch.

**Comment by bastimeyer** [comment]
You can't use old packages of point-release distros and expect new releases of software to work on those distros. There's also a reason why we don't include Ubuntu anymore in Streamlink's install docs, because it is not worth it confusing users with outdated Ubuntu packages or making them use PPAs which don't get upgraded anymore and potentially cause conflicts with other packages installed on the system.

Use the AppImages or install Streamlink via pip, either in the user environment or in a virtual environment.
https://streamlink.github.io/install.html

**Comment by bastimeyer** [comment]
Btw, Streamlink depends on `requests >=2.26.0,<3` since version `2.4.0` (via ac47d04e7cbe0be71fddf0977d20e07af4a04205). Ubuntu Focal (which I believe you're referring to) is stuck on [`python3-requests 2.22.0`](https://packages.ubuntu.com/focal/python3-requests) and [`python3-urllib3 1.25.8`](https://packages.ubuntu.com/focal/python3-urllib3).

**Comment by mk-pmb** [comment]
Yeah. I guess I was just lucky that it worked until last week. It was a nice time. Maybe one day a stream will be important enough to wrangle pip or AppImage.

**Comment by mk-pmb** [comment]
@jenlunds
> The problem here appears […] with --twitch-disable-ads set. Without it it works fine.

Thanks for reminding me! Without that, the stream starts much more reliably, but it seems that the 360p "preparing your stream" pre-show uses a different audio codec, making the audio of the real stream sound pitched up and stuttering every second or so. Did you experience that as well? Did you find a remedy?

**Comment by mk-pmb** [comment]
I managed to upgrade [streamlink-ubuntu-native](https://github.com/mk-pmb/streamlink-ubuntu-native) to do just enough of what pip would do.
