### ISSUE TITLE
plugins.twitch: OAuth token of account with turbo does not prevent pre-roll ads

### ISSUE THREAD

**Issue by kuon** [streamlink/streamlink#4939]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I have twitch turbo on my account and get no ads with the browser. I took the OAuth token with the technique explained in the doc (with the JS snippet). I replaced the token with `1234` in the logs, but I triple checked it and it correspond to the JS console output.

When I run streamlink with the `twitch-api-header` header, streamlink will wait for pre-roll ads to finish. But as I have turbo, I expect the stream to open right away.

I know that twitch ad skip is out of scope of streamlink and has been removed, but my current understanding is that passing a token with the `twitch-api-header` flags should work.

If this is expected behaviour, I apologize and you can close this.

My config:

```
default-stream=best
player=mpv
twitch-low-latency
twitch-disable-ads
twitch-api-header=Authentication=OAuth 1234
```

### Debug log

```text
$ streamlink --twitch-api-header="Authentication=OAuth 1234" --loglevel=debug twitch.tv/antoinedaniel 
[cli][debug] OS:         Linux-6.0.7-arch1-1-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.8
[cli][debug] Streamlink: 5.0.1
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.1.10
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  websocket-client: 1.4.2
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/antoinedaniel
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --default-stream=['best']
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][debug]  --twitch-api-header=[('Authentication', 'OAuth 1234'), ('Authentication', 'OAuth 1234')]
[cli][info] Found matching plugin twitch for URL twitch.tv/antoinedaniel
[plugins.twitch][debug] Getting live HLS streams for antoinedaniel
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Starting player: mpv
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][debug] First Sequence: 0; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2; End Sequence: None
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][info] Filtering out segments and pausing stream output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7 to queue
^CInterrupted! Exiting...
[cli][info] Closing currently open stream...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
-> Ctrl-C
```
```

**Comment by bastimeyer** [comment]
Please try with the `Authorization` header name instead of `Authentication`. That's what Twitch's web player is sending, just had a look again. Looks like the docs are wrong and nobody noticed because no ads were embedded until yesterday after Twitch stopped embedding them earlier this year after their leak...
https://github.com/streamlink/streamlink/pull/4156

`--twitch-api-header` allows you to set arbitrary headers. This is because we can't implement proper authentication flows and also can't react to any tiny change in a timely manner on Twitch's side. The parameter is meant as a workaround, so that users can apply authentication data or other ad-prevention headers on their own. Every time we added known ad-prevention headers in the past, those stopped working after a few days again, and then they caused other issues and had to be removed, which is a real pain when publishing software releases that are not web-applications.

This is just an extra feature and pretty much unsupported and success is not guaranteed.

**Comment by kuon** [comment]
Yes you are right, the header name was misspelled and I didn't notice. I confirm it works with `Authorization=OAuth=<token>`. So I guess just a documentation update is required.
