### ISSUE TITLE
TVCatchup login for premium channels

### ISSUE THREAD

**Issue by yhs4260** [streamlink/streamlink#494]
- [x ] This is a feature request.

### Description

Support logins from tvcatchup.com to enable access to premium channels for paid subscribers.

### Expected / Actual behavior

Currently I cannot login using my credentials on the command line. I can supply a login to test if required.

### Reproduction steps / Stream URLs to test

~/streamlink# streamlink http://tvcatchup.com/watch/eurosport1 -v --loglevel DEBUG
error: Unable to open URL: http://tvcatchup.com/watch/eurosport1 (404 Client Error: Not Found)

### Environment details (operating system, python version, etc.)

Debian Jessie 3.14.32-xxxx-grs-ipv6-64
Python 2.7.9

### Comments, logs, screenshots, etc.

...

**Comment by beardypig** [comment]
Does tvcatchup.com even have premium channels? You don't mean tvplayer.com?

**Comment by yhs4260** [comment]
oh god. yes you are right, its tvplayer.com. not sure how I was confused between the two. in that case, the same questions applies, but to tvplayer.com!

**Comment by beardypig** [comment]
Looks like TVPlayer.com use DRM to protect their premium content, it is unlikely that streamlink will ever support this. Sorry.

**Comment by gravyboat** [comment]
Closing since they use DRM.
