### ISSUE TITLE
Twitch VOD URL Changed

### ISSUE THREAD

**Issue by wastrel333** [streamlink/streamlink#496]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

It seems like the video links for Twist's VOD content has changed.

Previously, the VOD URL would be nested within the creator's channel, now it looks like all videos are within a "videos" folder.

For instance, previously, I would use the following command prompt to launch a VOD:
streamlink --twitch-oauth-token **token here*** --player-passthrough=hls twitch.tv/northernlion/v/117563643 best

Now, the VOD link would be:
streamlink --twitch-oauth-token **token here*** --player-passthrough=hls twitch.tv/videos/117563643 best

At least according to the links displayed on this creator's content page: https://www.twitch.tv/northernlion/videos/all

It appears there is some behind the scene resolving of URL that were borked with this change in hierarchy, the error I receive when using the URL form the VOD is:

C:>streamlink --twitch-oauth-token **token here*** --player-passthrough=hls  twitch.tv/videos/117563643 best
[cli][info] Found matching plugin twitch for URL twitch.tv/videos/117563643
error: Unable to open URL: https://clips.twitch.tv/api/v1/clips/videos/117563643/status (404 Client Error: Not Found for url: https://clips.twitch.tv/api/v1/clips/videos/117563643/status?as3=t)

**Comment by beardypig** [comment]
Looks like a new URL format that is not currently supported, but it will be soon.

As a work around you can transform it into an old style URL.
You need to know the channel name for it to work though.

twitch.tv/videos/**117563643** => twitch.tv/**northenlion**/v/**117563643**
twitch.tv/videos/**<video_id>** => twitch.tv/**<channel_name>**/v/**<video_id>**

**Comment by CoDEmanX** [comment]
Encountered the exact same problem: https://github.com/chrippa/livestreamer/issues/1574

**Comment by beardypig** [comment]
This has been fixed in #484. Installing the latest [nightly](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe)/dev will get you the fix for this.
