### ISSUE TITLE
beam.pro FTL support

### ISSUE THREAD

**Issue by GoaLitiuM** [streamlink/streamlink#497]
Please add support for beam.pro FTL (low latency) streams. Currently the existing beam.pro plugin is only able to retrieve the non-FTL stream, which does not represent the highest available quality stream (it's often transcoded to 30fps with baseline h264 profile which makes the streams look quite blocky when compared to low latency stream).

**Comment by beardypig** [comment]
Can you provide some example URLs please.

**Comment by beardypig** [comment]
The FTL streams use WebRTC (via Janus WebRTC Gateway) which is used for peer2peer media transmission. This is not something that is currently supported in Streamlink, and it would be quite a lot of work to support it. It will probably be awhile before this type of stream is supported, if it ever is.

**Comment by gravyboat** [comment]
I'm going to close this for now, no reason to leave it open and stagnant since it isn't on the roadmap for quite some time.

**Comment by h1z1** [comment]
Closed request I know, updating for posterity .. This site is hilarious.  Not entirely sure it's legal given it's entirely a rip of Twitch (some streams are direct copies), and now owned by Microsoft after they bought Beam, which is now Mixer.

All standard HLS, nothing about p2p which would have been neat at least.

**Comment by gravyboat** [comment]
It's absolutely legal and is part of the Beam network and has been from the start before Microsoft bought Beam, it just redirects to Mixer now and this request was from before the acquisition, I'm not sure what the purpose of your comment was.

**Comment by h1z1** [comment]
?  Not sure what the point of your comment was either, as I said it's now owned by Microsoft.  No need to get defensive.

**Comment by gravyboat** [comment]
This issue simply popped up in my notifications because you commented, I wasn't sure if you were saying this is something we shouldn't try to support at some point. Here's the other issue if you're interested in discussing support there: https://github.com/streamlink/streamlink/issues/957
