### ISSUE TITLE
Ask for Libreelec Kodi Matrix streamlink addon

### ISSUE THREAD

**Issue by ccontrolled** [streamlink/streamlink#4975]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Is there anyone who is able to make a streamlink addon for Libreelec with Kodi Matrix?

### Input URLs

Is there anyone who is able to make a streamlink addon for Libreelec with Kodi Matrix? (Like there is a good working ffmpeg Addon for Libreelec with Kodi Matrix)

**Comment by malvinas2** [comment]
[](https://github.com/jairoxyz/script.module.streamlink)

**Comment by ccontrolled** [comment]
It makes the following error on Libreelec-Matrix
ERROR <general>: CAddonInstallJob[script.module.streamlink]: Die Abhängigkeit auf xbmc.python in Version 2.24.0 konnte nicht aufgelöst werden.
