### ISSUE TITLE
plugins.twitch playback resuming from filtered ad segment is faster than normal

### ISSUE THREAD

**Issue by hadu-boired** [streamlink/streamlink#4978]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I remember this same issue last time twitch messed with embedded ads, never saw it mentioned and was eventually resolved somehow - playback directly following an ad break resumes at a slightly faster speed. I only know this because familiar voices sound very noticeably an octave higher, manually reloading the playlist fixes this.

### Debug log

```text
C:\net\Streamlink\bin>streamlink -p "c:\media\mpc\mpc-hc64.exe /nofocus" twitch.tv/jinnytty 720p60 -l=debug
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.15
[cli][debug] Streamlink: 5.1.0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.4.2
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/jinnytty
[cli][debug]  stream=['720p60']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=c:\media\mpc\mpc-hc64.exe /nofocus
[cli][debug]  --player-passthrough=['hls']
[cli][debug]  --player-no-close=True
[cli][debug]  --ringbuffer-size=33554432
[cli][debug]  --hls-live-edge=12
[cli][debug]  --hls-playlist-reload-attempts=5
[cli][debug]  --hls-segment-attempts=5
[cli][debug]  --hls-segment-threads=3
[cli][debug]  --ffmpeg-ffmpeg=C:\net\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][info] Found matching plugin twitch for URL twitch.tv/jinnytty
[plugins.twitch][debug] Getting live HLS streams for jinnytty
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: c:\media\mpc\mpc-hc64.exe /nofocus
[cli.output][debug] Calling: c:\media\mpc\mpc-hc64.exe /nofocus "https://video-weaver.jfk06.hls.ttvnw.net/v1/playlist/CpkEdC3LfF7Y5E1lXqj5qGsU-w-1c6cS91pYsyRVWnRsl0NhDyruKCkmTugQtdEfGU7ApLHzflwVJI2twUzK_7-VJrnsXaqjLvS0pMruxE0S58mQeZSsjiTIVITO-KcFAjm0hBrkCPXJOp_1_-kh_Cvr5BxqdTpV1sK26CwjGYrGDBCkqgwJAJZyoHngSGAAOrC4QBXHW0khreWDsj4XHxpeV_qrRgdumS_udj4oDjuhW8UKA3LhOpVByu7WuOYj9YmjND0Iiofa59YBnBQkvlVP4FhfUW_04d3v659j6U4XBAqIpCsDk1UGXLO18m0WkTHsBlKfWfQnXuy85Gl-pUD0F25hiRMDTD8S-4ylzo4Hx0uEAI9Xf772pEZq-UOVWDyRqdWuucNRWxWHEIuSQ8tf_uvLvq0-vaU7bIcc9hpwqiAJsuqhYMF5VaksW4w9ghXPvk0-pyd15PDpgwT7CjZtP5I8kALVohH5Hjtzj4zGvTfETmY4rRfpPkwo7D8MsRRvS03lY1JfUbLGe84vLMFpuSlYZWBK4NFnJvyZzOZzmIKhReKn_n5mXXKKK9Uq_dyIdAVPwc3iKVXVvgmXaYm1LyqTXPNuua8_JnosT2xs9Vr2Odlno9zdZL163VieidPYm9C0mBZh3RffB4MXw60e0pNhWu-oUbh6S0vZoV0RLCdiExyj8tGUYwaPssoHQVdNunJz0SiBHf5PGgwdOJp3R9Itijkxu1MgASoJdXMtd2VzdC0yMJUF.m3u8"
```

**Comment by bastimeyer** [comment]
What your player does is completely unrelated to Streamlink.

As thoroughly and sufficiently explained in the sticky thread #4949, there is nothing that Streamlink can do. There will be stream discontinuities no matter what, even when filtering out ads. Let me say it again, there is nothing that can be done when ads are embedded into the stream and stream discontinuities happen. Stream discontinuities are unsupported by Streamlink: #4535

If you're having issues with that, then try to authenticate, as explained in the docs
https://streamlink.github.io/cli/plugins/twitch.html

Or use a different/better player. I recommend MPV.
