### ISSUE TITLE
Vaughnlive on VLC using Livestreamer

### ISSUE THREAD

**Issue by SAMYEL06** [streamlink/streamlink#499]
Hello,

I need your experience with an issue I have with Livestreamer.

I'm not into coding or IT Techs but I searched for a way to play a livestream from Vaughnlive on VLC and found that Livestreamer could do it.

When I run it with my url, it says that it has found a matching plugin for Vaughnlive and then the command invite immediately closes up.

Also, if I don't put "best", it tells me "error: Unable to validate response text: Minimum length is 2 but value is 1"..

Can you check for me if it's just me or if you can't run it too ? Can you guide me into making it work ?

Thanks

URL : http://vaughnlive.tv/sherming66

**Comment by beardypig** [comment]
Are you using livestreamer or streamlink? It works fine for me with the latest version of Streamlink.

**Comment by SAMYEL06** [comment]
I used Livestreamer but I will try with Streamlink then. Just hope it works and that it won't be too hard for me to use it... 
Thanks!!  vendredi, 27 janvier 2017, 11:33PM +01:00 de beardypig  notifications@github.com :

**Comment by SAMYEL06** [comment]
Okay so it works fine now with streamlink, thanks A LOT !

But just to be sure.. is that a permanent solution to stream vaughnlive on VLC or will I need to update it often ?

Also, is it a permanent project or is there risks that the devs stop it ? (which left me with no other solution to stream it.. :/)

Thanks again ! (and sorry about my english, I'm french..)

**Comment by beardypig** [comment]
You may need to update for it to keep working. We are working on a more robust plugin for vaughnlive.

We are trying to ensure the future of the project, we have more than one person with access to the repo and to the PyPi page.

**Comment by SAMYEL06** [comment]
Thank you ! I wish it will work forever but I know it's a hard work to do... Thaaaanks again !!!! :D

**Comment by beardypig** [comment]
I got it to work once before on a different stream. I had to use the `--player-external-http` option in Streamlink, then open the HTTP stream with VLC and cast that.

**Comment by SAMYEL06** [comment]
Hum, I'm not good enough to find how to make it work the way you told me :/ but no problem, I will satisfy myself with VLC :'(
Thanks again !!! 

    Le Samedi 28 janvier 2017 15h31, beardypig <notifications@github.com> a écrit :
 

 I got it to work once before on a different stream. I had to use the --player-external-http option in Streamlink, then open the HTTP stream with VLC and cast that.—

**Comment by beardypig** [comment]
@SAMYEL06 I'm going to close this as you seem to have solved your original problem :)
