### ISSUE TITLE
plugins.abematv: live-event url not recognized

### ISSUE THREAD

**Issue by darkred3** [streamlink/streamlink#4993]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Doesn't recognize live-event links.
Example: https://abema.tv/live-event/650b34c2-2203-44cd-875c-94039e5a5e28

### Debug log

```text
C:\Users\XXXX\Desktop>streamlink --loglevel=debug https://abema.tv/live-event/650b34c2-2203-44cd-875c-94039e5a5e28
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 5.1.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2020.12.5
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.10.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.3
[cli][debug]  websocket-client: 1.4.2
[cli][debug] Arguments:
[cli][debug]  url=https://abema.tv/live-event/650b34c2-2203-44cd-875c-94039e5a5e28
[cli][debug]  --loglevel=debug
error: No plugin can handle URL: https://abema.tv/live-event/650b34c2-2203-44cd-875c-94039e5a5e28
```

**Comment by back-to** [comment]
VPN is blocked, which wasn't in the past.
I don't think we have someone who will create this in the next time.

closing
