### ISSUE TITLE
plugins.tvp: Unable to validate value of key 'result'

### ISSUE THREAD

**Issue by HappyPlotter** [streamlink/streamlink#4996]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

When trying TVP plugin an error occurs
"error: Unable to validate response text: ValidationError(dict):"

### Debug log

```text
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-132-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.1.1+2.g29d1f392
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.6.15
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.6.5
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.9.9
[cli][debug]  PySocks: 1.6.8
[cli][debug]  requests: 2.27.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.3.2
[cli][debug]  importlib-metadata: 1.5.0
[cli][debug] Arguments:
[cli][debug]  url=https://stream.tvp.pl/?channel_id=63759349
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin tvp for URL https://stream.tvp.pl/?channel_id=63759349
[plugins.tvp][debug] video ID: 63759349
error: Unable to validate response text: ValidationError(dict):
  Unable to validate value of key 'result'
  Context(type):
    Type of None should be dict, but is NoneType
```

**Comment by bastimeyer** [comment]
> https://stream.tvp.pl/?channel_id=63759349

The player JSON data includes `null` for the requested ID. The ID that's being used by the plugin is the one from the URL. Their website however is not using this ID, it's using the first item of the channels JSON data that's embedded in the site of the input URL and this does only get read when no channel ID was provided by the user. When the plugin was rewritten by me last month in #4905, this issue did not come up, so I'm a bit surprised here. Let me have a look...

**Comment by HappyPlotter** [comment]
Indeed I took the id from inside the html page (14812849) and it works, but from the url the 1455 does not work

**Comment by HappyPlotter** [comment]
I changed the order of ```video_id = video_id or self._get_video_id()``` to ```video_id = self._get_video_id() or video_id``` to force it to retrieve the video id from the json and it works

**Comment by bastimeyer** [comment]
The fix is to look up the ID in the channels JSON and return the first one if no ID could be found. I'll open a PR with a fix in a bit.
