### ISSUE TITLE
Streamlink cannot find the installed VLC player

### ISSUE THREAD

**Issue by kitce** [streamlink/streamlink#501]
I am getting this error.
`error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.`

until I used
`--player "S:\Program Files (x86)\VideoLAN\VLC\vlc.exe"`

I installed streamlink in `C:\` and VLC in `S:\`, does it matter?

**Comment by beardypig** [comment]
Streamlink only searches in the `%PROGRAMFILES%`, `%PROGRAMFILES(X86)%`, and `%PROGRAMW6432%`. If you install VLC to a different drive (even if it's the same directory structure) then Streamlink won't be able to find it and you'll have to specify it using `--player`. The good news is you can set it in your `streamlinkrc` file so you don't have to specify it on the command line every time. See the docs: https://streamlink.github.io/cli.html#configuration-file, you'll just need to add 
```
player=S:\Program Files (x86)\VideoLAN\VLC\vlc.exe
```

**Comment by kitce** [comment]
Thank you!
