### ISSUE TITLE
CNN Go

### ISSUE THREAD

**Issue by joaquinito2070** [streamlink/streamlink#5010]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

CNN Go is an CNN live streaming website. I cannot give the Stream URLs because i am from Spain.

### Input URLs

https://go.cnn.com/

**Comment by back-to** [comment]
```
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

https://tve-live-lln.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8
```
