### ISSUE TITLE
plugins.ustreamtv: Warning No valid FFmpeg binary was found, Error No playable streams on this URL 

### ISSUE THREAD

**Issue by dsrushton** [streamlink/streamlink#5016]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

I'm trying to stream from https://video.ibm.com/channel/live-iss-stream but keep encountering:

No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!
error: No playable streams found on this URL: https://video.ibm.com/channel/live-iss-stream

I've installed ffmpeg using pip install ffmpeg, also pip install ffmpeg-python, and added to my Path environment variables. 

Relative N00b here, hope I'm not missing something easy. 

### Debug log

```text
streamlink https://video.ibm.com/channel/live-iss-stream best --loglevel debug 
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.8
[cli][debug] Streamlink: 5.1.2+2.gfba7d934
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.9.24
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://video.ibm.com/channel/live-iss-stream
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin ustreamtv for URL https://video.ibm.com/channel/live-iss-stream
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!
error: No playable streams found on this URL: https://video.ibm.com/channel/live-iss-stream
```

**Comment by bastimeyer** [comment]
https://streamlink.github.io/install.html#dependencies
https://streamlink.github.io/install.html#windows-binaries
https://github.com/streamlink/windows-builds#streamlinkwindows-builds
https://github.com/streamlink/FFmpeg-Builds/releases
