### ISSUE TITLE
lookcam.pl

### ISSUE THREAD

**Issue by regrepl** [streamlink/streamlink#5018]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Multimedial platform with various cameras from Poland and Slovakia,
This site provides live webcams, cities, animals, mountains, traffic.
No. There are no restrictions, no registration, no geo block.

Stream url is protected only by token with expires data. HLS format.

### Input URLs

Webpage
https://lookcam.pl/
Sample stream format
https://cdn.hexstream.pl/stream/CONSTANT_CAM_ID/manifest.m3u8?token=VARIABLE_1&expires=VARIABLE_2

**Comment by mkbloke** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

11, Sites which are static cameras of a physical location

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 11. Sites which are static cameras of a physical location
