### ISSUE TITLE
standalone exe setup fails on windows 7 64

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#503]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Stream URLs to test

1. ...
2. ...
3. ...

### Environment details (operating system, python version, etc.)

...

### Comments, logs, screenshots, etc.

...
![untitled](https://cloud.githubusercontent.com/assets/25414991/22403692/159fe2a0-e617-11e6-976c-bd6138c5e30e.jpg)

C:\streamlink-portable-master\Streamlink for Windows (Compiled)\Releases>streamlink.exe
[Streamlink] Extracting program ...
[Streamlink] Program successfully extracted
[Streamlink for Windows v0.3.0 - Git 2cc12ec]
Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Temp\\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\Streamlink.py", line 4, in <module>
    from streamlink_cli.main import main
  File "C:\Users\J\AppData\Local\Temp\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\streamlink_cli\main.py", line 14, in <module
>
    from streamlink import (Streamlink, StreamError, PluginError,
  File "C:\Users\J\AppData\Local\Temp\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\streamlink\__init__.py", line 73, in <module
>
    from .api import streams
  File "C:\Users\J\AppData\Local\Temp\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\streamlink\api.py", line 1, in <module>
    from .session import Streamlink
  File "C:\Users\J\AppData\Local\Temp\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\streamlink\session.py", line 9, in <module>
    from streamlink.utils.l10n import Localization
  File "C:\Users\J\AppData\Local\Temp\RTV_STREAMLINK_FOR_WINDOWS\Streamlink\streamlink\utils\l10n.py", line 2, in <modul
e>
    from iso639 import languages
ImportError: No module named 'iso639'
[End of Streamlink for Windows]

C:\streamlink-portable-master\Streamlink for Windows (Compiled)\Releases>

**Comment by johnthecracker** [comment]
Streamlink is command line application.

I find it weird that installation program works in win 7 64, and portable or standalone setup fails.

Cannot it be one 7z file to unpack, set up path and run ?

**Comment by karlo2105** [comment]
Since ffmpeg library and related commits have been merged to streamlink, portable needs to be adapted with those changes but main developer Rosadin is currently on vacation so you can try with beardypig version ; https://s3.amazonaws.com/streamlink-portable/nightly/streamlink-portable-latest-amd64.zip

**Comment by johnthecracker** [comment]
I did not come accross this link before,

https://github.com/beardypig

**Comment by johnthecracker** [comment]
Thank you.

Will close this after official distro has portable and standalone setup working.
With Livestreamer I installed it once and later packed it and unpacked it, set path and it worked.
With Streamlink does not work making "self portable", unless you are beardypig.

**Comment by beardypig** [comment]
You should report this on https://github.com/streamlink/streamlink-portable so that the relavant people see it.

**Comment by johnthecracker** [comment]
posted link to here from

 https://github.com/streamlink/streamlink-portable

**Comment by gravyboat** [comment]
I'm going to close this since it's over in the portable repo now, thanks @johnthecracker.
