### ISSUE TITLE
Support mutiple streams and switch if one goes down

### ISSUE THREAD

**Issue by Kryptortio** [streamlink/streamlink#5030]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I think it could be a nice feature to have multiple streams so that if one goes down or gets interrupted then anther stream could be used immediately instead so that there is no interruption. I realize this feature might not give a perfect result since the streams might not be completely in sync so some parts could get cut out but something is still much better than nothing.

Multiple streams could be picked up automatically by a plugin if possible or provided by the user. It doesn't have to be the same stream, it could also work if there are multiple angles. Even similar streams with different content could possibly be useful in some cases (e.g. two people streaming the same game). So the urls provided by the user could be urls for a plugin to use to find the actual streams.

Ideally entirely different sources should be supported since then it could be used in cases where a steam is available on multiple sites for example if someone is streaming to YouTube and Twitch at the same time. This might require that on the fly encoding is available so that the stream does not get interrupted because the source is of a different format.

The order of streams should probably be taken into account, the first one should be seen as the best stream. So if the first one cuts out and there is a switch it would be nice if there was an option to keep track of the first one to be able to switch back if it returns.

A nice way to expand the feature further would be to also allow using a proxy for one of the streams but not the others (or even use the same stream but try with a proxy if it stops working without).

Sorry if this has already been suggested I was not able to find an issue for it, although it could possibly help with [this one](https://github.com/streamlink/streamlink/issues/4949). If the plugin can switch to an alternative stream when ads are detected.

**Comment by bastimeyer** [comment]
Outputting multiple streams is unsupported due to how the stream output of Streamlink works. Related: #4535
