### ISSUE TITLE
tvp.py  plugin issue with some links started with master.m3u8

### ISSUE THREAD

**Issue by maanich** [streamlink/streamlink#5037]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

tvp plugin issue in playing stream which ends with master.m3u8 index.m3u8 works perfect

streamlink --player-continuous-http --player-external-http --player-external-http-port=9105 https://stream.tvp.pl/?channel_id=51121199 best &  gives error

error: Error when writing to output: [Errno 32] Broken pipe, exiting
[cli][info] Stream ended

### Debug log

```text
streamlink  https://stream.tvp.pl/?channel_id=51121199 best --player-no-close --stdout | ffmpeg -y -i -nostdin -loglevel panic pipe:0 -vcodec copy -acodec copy -flags -global_header -hls_flags delete_segments -hls_time 10 -hls_list_size 6 /var/www/html/HLS/TVPKULTURA2.m3u8
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tvp for URL https://stream.tvp.pl/?channel_id=51121199
[cli][info] Available streams: vod (worst, best)
[cli][info] Opening stream: vod (http)
error: Error when writing to output: [Errno 32] Broken pipe, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
> [cli][info] Stream ended
