### ISSUE TITLE
Support providing a custom Crunchyroll session ID

### ISSUE THREAD

**Issue by aritsune** [streamlink/streamlink#505]
The documentation suggests using an HTTP proxy to access region-locked content in Crunchyroll. However this isn't necessary, as all you need to do so is a session ID belonging to the region you want. Now I'm not asking for streamlink to generate one for you, as nice as that would be -- simply that it lets you specify it with an argument (it's only a 32 character string).

**Comment by beardypig** [comment]
How do you set the token? In a cookie?

**Comment by starchivore** [comment]
Could that be done like this?

[http://www.crunblocker.com/sess_id.php](http://www.crunblocker.com/sess_id.php)
[https://github.com/jerryteps/Crunchyroll-Unblocker/tree/master/Crunchyroll%20Unblocker](https://github.com/jerryteps/Crunchyroll-Unblocker/tree/master/Crunchyroll%20Unblocker)

> [https://chrome.google.com/webstore/detail/crunchyroll-unblocker/dldddkdajilplfikaadakojgjocbnjim](https://chrome.google.com/webstore/detail/crunchyroll-unblocker/dldddkdajilplfikaadakojgjocbnjim)
> This extension works by opening a http connection to a php script which obtains a us session id. The extension then copies the id so Crunchyroll believes you are from the US.
> 
> In case the extension no longer works, you can manually access the US site instead, just find a proxy, clear your cookies (reloading your browser will do), since it saves a US session id, you can just quit out of the proxy and you'll still remain on the US site, even on your own connection, since you still have the US cookies.

**Comment by beardypig** [comment]
You can do that already using the command line arguments in streamlink adding something like `--http-cookie "sess_id=rthgyx5gg3lwlcfr2zj5gueooloxxy0u"` should do it.
