### ISSUE TITLE
plugins.euronews: 404 Client Error

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#5062]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello I m facing an issue with euronews

### Debug log

```text
/usr/local/bin/streamlink --loglevel debug  "https://fr.euronews.com/live"
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.15.0-56-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.1.2
[cli][debug] Dependencies:
[cli][debug]  certifi: 2019.11.28
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.8.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.9.9
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  urllib3: 1.26.13
[cli][debug]  websocket-client: 1.3.2
[cli][debug] Arguments:
[cli][debug]  url=https://fr.euronews.com/live
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin euronews for URL https://fr.euronews.com/live
error: Unable to open URL: https://fr.euronews.com/api/watchlive.json (404 Client Error: Not Found for url: https://fr.euronews.com/api/watchlive.json)
```

**Comment by mkbloke** [comment]
Seems like it's broken on their website.  It's not loading via a web browser either.  Neither is `https://www.euronews.com/live` for that matter.

**Comment by campones** [comment]
yes,  https://www.euronews.com/live is loading for me actually?

**Comment by mkbloke** [comment]
Ah, one of my add-ons seemed to be stopping it.

**Comment by bastimeyer** [comment]
Why does this plugin even exist? It's just a wrapper for YouTube live streams and HTTPStream VODs. The API stuff for non-embedded live streams doesn't seem to exist anymore. At least I can't find anything. This means that the plugin should be removed, even though a fix would be trivial for the current issue where the youtube stream ID has been moved to a different data- tag with a small JSON string.

Live streams can be found here:
https://www.youtube.com/@euronews/streams

**Comment by bastimeyer** [comment]
Apparently, some languages are not available on YT and they are using a third party streaming service with an HLS stream that's retrieved from a different API endpoint.
