### ISSUE TITLE
Name of the website / streaming provider

### ISSUE THREAD

**Issue by jungle-boogie** [streamlink/streamlink#5066]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hello,

[NRBTV](https://nrbtv.org/about/) was founded in 2005 for the purpose of broadcasting Christian content.
The channel is available on cable, satellite networks, and on devices like Roku and AppleTV.

Thanks for the consideration to support NRBTV.

Thanks!

### Input URLs

1. https://nrbtv.org/live/

**Comment by mkbloke** [comment]
This appears to have a static playlist URL, so it can just be played with:
```
$ streamlink https://uni10rtmp.tulix.tv/nrbtvlive/nrbtvlive.stream/playlist.m3u8
```
No plugin necessary

**Comment by jungle-boogie** [comment]
Thank you!
