### ISSUE TITLE
FilmOn: "no streams found"?

### ISSUE THREAD

**Issue by jabhq** [streamlink/streamlink#507]
Possible plugin "bug" report?
(or new user problem! - no other reports?)
FilmOn failed using Livestreamer a week ago. Discovered Streamlink! No change!

FilmOn plugin is found but "no streams found" for *any* channels like
http://www.filmon.com/channel/bbc-one

Windows 7 / Streamlink Win install 0.3.0 29/1/17 

C:\Users\jb\xD\Portbl\FilmOnHack>"C:\Program Files (x86)\Streamlink\bin\streamlink.exe" http://www.filmon.com/channel/bbc-one high
[cli][info] Found matching plugin filmon for URL http://www.filmon.com/channel/bbc-one
error: No streams found on this URL: http://www.filmon.com/channel/bbc-one

No problems with TVPlayer

**Comment by beardypig** [comment]
Looks like they might have changed the page or streaming URLs or something similar. I'll take a look at it now.
