### ISSUE TITLE
Can't find 'Crypto.Util.Padding' when running from unpriveleged user on linux.

### ISSUE THREAD

**Issue by corvus1** [streamlink/streamlink#5083]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Here's what happens:

```
$ streamlink --version
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 5, in <module>
    from streamlink_cli.main import main
  File "/usr/lib/python3.10/site-packages/streamlink_cli/main.py", line 22, in <module>
    from streamlink.stream.stream import Stream, StreamIO
  File "/usr/lib/python3.10/site-packages/streamlink/stream/__init__.py", line 3, in <module>
    from streamlink.stream.hls import HLSStream, MuxedHLSStream
  File "/usr/lib/python3.10/site-packages/streamlink/stream/hls.py", line 11, in <module>
    from Crypto.Util.Padding import unpad
ModuleNotFoundError: No module named 'Crypto.Util.Padding'
```

But then:
```
$ sudo streamlink --version
streamlink 5.1.2
```

### Debug log

```text
$ streamlink --version --loglevel=debug
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 5, in <module>
    from streamlink_cli.main import main
  File "/usr/lib/python3.10/site-packages/streamlink_cli/main.py", line 22, in <module>
    from streamlink.stream.stream import Stream, StreamIO
  File "/usr/lib/python3.10/site-packages/streamlink/stream/__init__.py", line 3, in <module>
    from streamlink.stream.hls import HLSStream, MuxedHLSStream
  File "/usr/lib/python3.10/site-packages/streamlink/stream/hls.py", line 11, in <module>
    from Crypto.Util.Padding import unpad
ModuleNotFoundError: No module named 'Crypto.Util.Padding'
```

**Comment by bastimeyer** [comment]
> Latest stable release
> /usr/bin/streamlink

Which distro are you using? How did you install Streamlink?

> ModuleNotFoundError: No module named 'Crypto.Util.Padding'

You are missing Streamlink's pycryptodome dependency.

**Comment by corvus1** [comment]
> > Latest stable release
> > /usr/bin/streamlink
> 
> Which distro are you using? How did you install Streamlink?

Using Gentoo Linux, Streamlink is installed with the package manager, from the repo. 

> > ModuleNotFoundError: No module named 'Crypto.Util.Padding'
> 
> You are missing Streamlink's pycryptodome dependency.

Yeah, I get that. But why am I not missing it, when running streamlink with sudo? Pycryptodome is installed in the system, and totally available. Streamlink just can't seem to get to it with no root access, but it's incredibly weird. I even checked the file permissions and everything `-rw-r--r-- 1 root root 4313 дек 31 18:38 /usr/lib/python3.10/site-packages/Crypto/Util/Padding.py` 
It's totally readable. I seriously don't know what to think.

**Comment by bastimeyer** [comment]
This is either a [packaging issue on Gentoo](https://packages.gentoo.org/packages/net-misc/streamlink) and you'll need to ask for support there, or you've messed up your system's python environment by mixing up packages of the system package manager and another package manager, like pip, etc. In either case, that's nothing that we can support here, and you'll have to figure this out on your own. This is not a Streamlink bug.

Never run any application with root privileges unless you have to. Running Streamlink as root is a bad idea in 99% (actually 100%) of all cases and you certainly shouldn't do that, and neither shouldn't the system python environment be mixed with packages from external/additional/third-party package managers.

Check how python environments work and how module paths are resolved
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME

and preferrably install Streamlink in a user environment or virtual environment if you're having issues with your system's python environment:
https://packaging.python.org/en/latest/tutorials/installing-packages/
https://streamlink.github.io/install.html#virtual-environment

**Comment by corvus1** [comment]
> This is either a [packaging issue on Gentoo](https://packages.gentoo.org/packages/net-misc/streamlink) 

That's what I thought at first, but then turns out it works with streamlink version 4.

> you've messed up your system's python environment by mixing up packages of the system package manager and another package manager, like pip

No, I've never used pip for anything. 

> In either case, that's nothing that we can support here, and you'll have to figure this out on your own. This is not a Streamlink bug.

> Never run any application with root privileges unless you have to. 

I think I'll be fine running `streamlink --version` to check if it works. It's not going to eat my cat or anything. :-D

> and neither shouldn't the system python environment be mixed with packages from external/additional/third-party package managers.

I don't do that.
