### ISSUE TITLE
globoplay.com

### ISSUE THREAD

**Issue by guiworldtv** [streamlink/streamlink#5084]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

hey friends, how are you? I would like you to include access to Globoplay (Brazil's main streaming service) in the streamlink
this streaming works outside brazil, as most owners here must be in the united states
some contents needs a vpn
globoplay need a subscription, make a option do put a login and password to acess the content
thanks

### Input URLs

https://globoplay.globo.com/tv-globo/ao-vivo/9909627/
https://globoplay.globo.com/
https://globoplay.globo.com/globonews/ao-vivo/6461772/

**Comment by back-to** [comment]
> some contents needs a vpn
globoplay need a subscription

ref https://github.com/streamlink/streamlink/issues/1229
