### ISSUE TITLE
MEDIASET INFINITY 

### ISSUE THREAD

**Issue by guiworldtv** [streamlink/streamlink#5086]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

what's up guys
I would like to include this site in the sites that the streamlink accepts, it is a streaming from Italy, which needs vpn to be accessed, and the video they export is in mpd format

### Input URLs

https://mediasetinfinity.mediaset.it/
https://mediasetinfinity.mediaset.it/video/grandefratellovip/giorno-1-canale-5_F310235501000101
https://mediasetinfinity.mediaset.it/video/grandefratellovip/giorno-8-italia-1_F310233501000601
https://mediasetinfinity.mediaset.it/video/grandefratellovip/terza-puntata_F310172801000301
https://mediasetinfinity.mediaset.it/video/grandefratellovip/lunedi-9-gennaio-puntata-27_F310294001002701
https://mediasetinfinity.mediaset.it/diretta/canale5_cC5
https://mediasetinfinity.mediaset.it/diretta/grandefratellovip_cB7

**Comment by back-to** [comment]
they use static urls,
just search for `https://live3.msf.cdn.mediaset.net/content`

**Comment by fmigliorato** [comment]
I searched for `streamlink https://live3.msf.cdn.mediaset.net/content` but I get `error: No plugin can handle URL: https://live3.msf.cdn.mediaset.net/content`

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/protocols.html

```
$ streamlink 'https://host/path/playlist.m3u8'
```
or
```
$ streamlink 'hls://https://host/path/playlist'
```

**Comment by fmigliorato** [comment]
Found It. It was MPEG-DASH: `https://live3.msf.cdn.mediaset.net/content/dash_d0_clr_vos/live/channel(b7)/manifest.mpd`

Thank You 🙂

**Comment by petciro** [comment]
Did u manage to get it and the channel? Any key or id to use?

**Comment by fmigliorato** [comment]
> Did u manage to get it and the channel? Any key or id to use?

Yes, You have to open the network tab from the developer tools and search for "manifest.mpd" Then copy the link and use streamlink with that link. And You get something like this:
`[cli][info] Found matching plugin dash for URL https://live3t.msf.cdn.mediaset.net/content/dash_d0_cls_vos/live/channel(c5)/manifest.mpd?hdnts=st=1681902888~exp=1681917318~acl=/content/dash_d0_cls_vos/live/channel(c5)*~hmac=0c9afb9cd5e65e26a30a19d7ec42e2a58a8629fc5eee4cd23065c7ee7115eaf6
Available streams: 288p (worst), 432p, 576p_alt, 576p, 720p, 1080p_alt, 1080p (best)`

Now You just need to postpone the resolution You want to the original link: `streamlink https://live3t.msf.cdn.mediaset.net/content/dash_d0_cls_vos/live/channel(c5)/manifest.mpd?hdnts=st=1681902888~exp=1681917318~acl=/content/dash_d0_cls_vos/live/channel(c5)*~hmac=0c9afb9cd5e65e26a30a19d7ec42e2a58a8629fc5eee4cd23065c7ee7115eaf6 720p`

**Comment by petciro** [comment]
Thanks. And how do i play it ? sorry

**Comment by fmigliorato** [comment]
No problem. Install VLC (VideoLAN). It uses it as the default player and will open the video with it. You can change the player if you want, it is explained in the documentation

**Comment by petciro** [comment]
Thanks i typed it on CMD and i have this back [cli][info] Found matching plugin dash for URL https://live3t.msf.cdn.mediaset.net/content/dash_d0_cls_vos/live/channel(c5)/manifest.mpd?hdnts=st=1681902888~exp=1681917318~acl=/content/dash_d0_cls_vos/live/channel(c5)*~hmac=0c9afb9cd5e65e26a30a19d7ec42e2a58a8629fc5eee4cd23065c7ee7115eaf6
error: Unable to open URL: https://live3t.msf.cdn.mediaset.net/content/dash_d0_cls_vos/live/channel(c5)/manifest.mpd?hdnts=st=1681902888~exp=1681917318~acl=/content/dash_d0_cls_vos/live/channel(c5)*~hmac=0c9afb9cd5e65e26a30a19d7ec42e2a58a8629fc5eee4cd23065c7ee7115eaf6 (403 Client Error: Forbidden for url: https://live3t.msf.cdn.mediaset.net/content/dash_d0_cls_vos/live/channel(c5)/manifest.mpd?hdnts=st=1681902888~exp=1681917318~acl=/content/dash_d0_cls_vos/live/channel(c5)*~hmac=0c9afb9cd5e65e26a30a19d7ec42e2a58a8629fc5eee4cd23065c7ee7115eaf6)

**Comment by fmigliorato** [comment]
> You have to open the network tab from the developer tools and search for "manifest.mpd" Then copy the link and use streamlink with that link.

Copy that link later while you are watching mediaset from the website, don't use the link i used above. It was just to an example

**Comment by petciro** [comment]
@workserv waiting for u in case i will delete this later on

**Comment by guiworldtv2** [comment]
the streamlink is still not working with these links https://mediasetinfinity.mediaset.it/
https://mediasetinfinity.mediaset.it/video/grandefratellovip/giorno-1-canale-5_F310235501000101
https://mediasetinfinity.mediaset.it/video/grandefratellovip/giorno-8-italia-1_F310233501000601
https://mediasetinfinity.mediaset.it/video/grandefratellovip/terza-puntata_F310172801000301
https://mediasetinfinity.mediaset.it/video/grandefratellovip/lunedi-9-gennaio-puntata-27_F310294001002701
https://mediasetinfinity.mediaset.it/diretta/canale5_cC5
https://mediasetinfinity.mediaset.it/diretta/grandefratellovip_cB7

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/5086#issuecomment-1383120460
https://github.com/streamlink/streamlink/issues/5086#issuecomment-1407388774
