### ISSUE TITLE
Filmon.us broken

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#509]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Filmon.us is community streaming website. 

### Expected / Actual behavior

It's expected to open stream with player. 

### Reproduction steps / Stream URLs to test

```
streamlink "https://www.filmon.us/bongrip"
[cli][info] Found matching plugin filmon_us for URL https://www.filmon.us/bongrip
error: No streams found on this URL: https://www.filmon.us/bongrip
```

### Environment details (operating system, python version, etc.)

Win 7 PRO -> Python 2.7.13

**Comment by johnthecracker** [comment]
I can answer this but it won't be Streamlink.

This stream looks different than most other streams on filmon.


HttpFox, extension for Firefox:

00:04:26.659	1.078	274	(0)	GET	(Cache)	text/html	https://www.filmon.us/bongrip

Content Tab: ( put this together from <!doctype html> )

rtmp://198.179.31.76/battlecam/mp4:bc_3195397

Here is more about about Livestreamer ( Streamlink ) and Filmon,
different flavour but about the same topic:

http://stream-recorder.com/forum/can-somebody-help-get-filmon-rtmp-code-t22496.html

**Comment by back-to** [comment]
website is not reachable and got removed in https://github.com/streamlink/streamlink/pull/1766
