### ISSUE TITLE
plugins.dash: Manifest URLs including extra path after .mpd are parsed incorrectly

### ISSUE THREAD

**Issue by jhelgert** [streamlink/streamlink#5095]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

There are some (very) rare cases where the Dash Manifest URL doesn't end with .mpd and requires some extra path (no query parameters), i.e. think of `http://somedomain.tld/dummy_manifest.mpd/ExtraPath`. As far as I can tell, the Dash plugin's regex matching pattern assumes that each Manifest ends with .mpd and only contains optional query parameters. Consequently, the aforementioned URL will be parsed incorrectly as  `http://somedomain.tld/dummy_manifest.mpd`.

PS: The URL posted in the debug log below is no longer valid but illustrates the problem. It belongs to Sky CH and is **not** DRM-protected, see #3397 .

### Debug log

```text
[cli][debug] OS:         macOS 13.1
[cli][debug] Python:     3.10.9
[cli][debug] Streamlink: 5.1.2
[cli][debug] Dependencies:
[cli][debug]  certifi: 2021.10.8
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.16.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  urllib3: 1.26.9
[cli][debug]  websocket-client: 1.4.2
[cli][debug]  importlib-metadata: 6.0.0
[cli][debug] Arguments:
[cli][debug]  url=https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin dash for URL https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest
[plugins.dash][debug] URL=https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd; params={}
error: Unable to open URL: https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd (400 Client Error: Bad Request for url: https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd)
```

**Comment by bastimeyer** [comment]
Use the `dash://` protocol prefix
https://streamlink.github.io/cli/protocols.html#supported-streaming-protocols

The URL you've posted however results in a 404 response:
```
$ streamlink -l debug 'dash://https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest'
[cli][debug] OS:         Linux-6.1.4-1-git-x86_64-with-glibc2.36
[cli][debug] Python:     3.10.9
[cli][debug] Streamlink: 5.1.2+37.g871f7f7b
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  websocket-client: 1.3.1
[cli][debug]  importlib-metadata: 5.0.0
[cli][debug] Arguments:
[cli][debug]  url=dash://https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin dash for URL dash://https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest
[plugins.dash][debug] URL=https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest; params={}
error: Unable to open URL: https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest (404 Client Error: Not Found for url: https://tvhosa-pez0413.sctv.ch/dash/JPAGPKAALHEEEMDG.mpd/Manifest)
```
