### ISSUE TITLE
How to exit streamlink if source is no longer available

### ISSUE THREAD

**Issue by digitalcelery** [streamlink/streamlink#510]
Is there a way to kill streamlink if source is no longer available(expired token, link down)? Sometimes script just needs to request new token for example but streamlink keeps running and returns 403: Forbidden

**Comment by beardypig** [comment]
Ctrl-C? Have you set the retries to a very large number?

**Comment by johnthecracker** [comment]
How to kill 403:Forbidden and keep the stream going ?

http://stream-recorder.com/forum/showpost.php?p=89387&postcount=57

**Comment by beardypig** [comment]
@digitalcelery is this related to filmon?

**Comment by johnpolite** [comment]
HRTV is on Filmon.

There may be somebody on the internet who will click on the link in previus post.

**Comment by beardypig** [comment]
Relating to HRTV I have opened a PR that provides a solution #508. You can replace the [filmon.py](https://raw.githubusercontent.com/beardypig/streamlink/1e347edef947442db9da6381b63e14dea62e3f1a/src/streamlink/plugins/filmon.py) from this PR and it should play HRTV in both high and low qualities.

**Comment by digitalcelery** [comment]
@beardypig Nope, does not relate to filmon

**Comment by beardypig** [comment]
Pressing Ctrl-C will stop streamlink. But it will only retry a few times by default, unless you changed the settings to retry many times.

**Comment by digitalcelery** [comment]
If you input is a curl command $(curl www.hello.com | grep m3u) and if token expires there is no way to grab new link if token expires and input dies. Fffmpeg for example shuts down in this case and and process monitoring tool will kick it in again triggering curl command and greping new url. Livestreamer on the other hand continues working and proving 403 responses from dead links.

**Comment by beardypig** [comment]
You'll have to be more specific, what command are you running exactly?

**Comment by digitalcelery** [comment]
Pretend that stream url with token is located here: www.helloworld.com/live.php

> /usr/local/bin/streamlink -lsvariant://$(curl www.helloworld.com/live.php | grep m3u ) best --player-external-http --player-external-http-port 12344

When token dies, streamlink doesn't close hence it wont use curl to get a new link. In such case, ffmpeg shuts down, and if you use monit it will kick in the process again and get a new input link.

**Comment by TVGPlayer** [comment]
@beardypig Replace filmon.py and HRTV plays in low quality with "Failure to reload playlist" warning. High quality plays with the same warning then cuts off. Is there any solution? Thanks for your hard work with streamlink!

**Comment by beardypig** [comment]
@TVGPlayer can you continue discussing this separate issue over on https://github.com/streamlink/streamlink/pull/508 instead.

**Comment by beardypig** [comment]
@digitalcelery this is the expected behaviour of [--player-external-http](https://streamlink.github.io/cli.html#cmdoption-player-external-http). It would probably be more suitable in this case to create a plugin to extract the m3u8 URL.

**Comment by digitalcelery** [comment]
What if there was an additional switch in the app to stop the program in case stream becomes unavailable?

**Comment by flyser** [comment]
I am running into this issue as well. I wanted to use streamlink to dump a twitch stream to a file. I thought running it in an endless loop would be enough, but it always stops at some point. It would be nice to see this fixed.

**Comment by gravyboat** [comment]
I'm going to close this, we've gotten way off topic with too many unrelated concerns and edge cases. The comment by @flyser is most likely related to https://github.com/streamlink/streamlink/issues/1058 which isn't our problem.
