### ISSUE TITLE
mixch.tv

### ISSUE THREAD

**Issue by Waldemar7-giga** [streamlink/streamlink#5106]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

mixch.tv is a japanese live streaming website similar to showroom. The site does not require login and has no geo block. The individual m3u8 links are working fine with streamlink.

### Input URLs

streamer main page:
https://mixch.tv/u/14575618
streamer livestream url:
https://mixch.tv/u/14575618/live
example m3u8 url:
https://d2ibghk7591fzs.cloudfront.net/hls/torte_14575618.m3u8

**Comment by mkbloke** [comment]
Looks simple enough to implement.

What are the thoughts on more plugins for this kind of site?  There have been comments before, e.g.: https://github.com/streamlink/streamlink/issues/4588#issuecomment-1153345851.

**Comment by bastimeyer** [comment]
> There have been comments before, e.g.: [#4588 (comment)](https://github.com/streamlink/streamlink/issues/4588#issuecomment-1153345851).

This. It's exactly the same use case and just another plugin for being able to download from a camsite, not for watching live streams in a video player.
