### ISSUE TITLE
Globoplay Brazil

### ISSUE THREAD

**Issue by televisivo** [streamlink/streamlink#5126]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

**What is the site about?**
Globoplay is the streaming website of TV Globo, Futura and other channels from Globo, a Brazilian media company. This website is similar to BBC iPlayer of BBC UK.

**Who is it run by?**
This website is run by Globo, the owner of the content it broadcasts in Globoplay website.

**What kind of content does it provide?**
Globoplay has many content options. It offers 4 free TV channels: TV Globo (open-to-air TV), Futura (educational), Receitas Fast (food/culinary) and GE Fast (sports).

**Are there any access restrictions like logins or region checks?**
To access the free channels, the user has to be registered with a Globo Account (also free). TV Globo content is regionalized (by Brazil state and internationally) and the other 3 channels are not regionalized.

### Input URLs

1. Homepage: https://globoplay.globo.com/
2. TV Globo: https://globoplay.globo.com/tv-globo/ao-vivo/6120663/
3. Futura: https://globoplay.globo.com/futura/ao-vivo/7420604/
4. Receitas Fast: https://globoplay.globo.com/receitas-fast/ao-vivo/11134191/
5. GE Fast: https://globoplay.globo.com/ge-fast/ao-vivo/11134179/

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/issues?q=is%3Aissue+globoplay
https://github.com/streamlink/streamlink/issues/1229
