### ISSUE TITLE
Problem with the version 0.3

### ISSUE THREAD

**Issue by Romsh** [streamlink/streamlink#513]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Hi, after having an error code 2 with the Streamlink GUI 1.0.1&Streamlink 0.1.0 i decided to update all of that for the latest version.
But, even with a full, clear and clean installation, i have some "drops" now on source. Like little buffering i hadn't before and i don't know why.

### Expected / Actual behavior

Using RTMP protocol, i want to know why i have this "drops" and how can i fix that ?

### Reproduction steps / Stream URLs to test

1. Latest version of Streamlink GUI
2. Latest version of Streamlink (0.3)
3. RTMP protocol

### Environment details (operating system, python version, etc.)

Windows 10 64 bits
Python 3.6

### Comments, logs, screenshots, etc.

My speedtest : https://puu.sh/tIBD1/41e66ece7c.png
My configuration of streamlink: https://puu.sh/tIC4d/9503dd51ec.png

**Comment by gravyboat** [comment]
Can you see if you get the drops using Streamlink directly off the command line?

**Comment by Romsh** [comment]
Sorry but i don't succeed to find the right command.
I tried : "streamlink.exe -p "C:\Program Files\MPC-HC\mpc-hc64.exe" http://www.twitch.tv/zerator best

**Comment by beardypig** [comment]
@Romsh what is printed to the console if you just run streamlink from the command line?

**Comment by DarkWiss** [comment]
Hi, I had the same buffering/lag issue when I went to the 0.2.0 and 0.3.0. So I had to come back to the 0.1.0 and all was great again.

**Comment by beardypig** [comment]
Have you tried `0.3.1`? Or [streamlink-latest](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe)?

**Comment by gravyboat** [comment]
Are you both using MPC-HC? Does this issue occur when using other video players? Does this occur on all streams you've tried at best (to rule out changes by the streamer in regards to bit rate)? I think we'll need more troubleshooting details before we can really start to dig into this one.

**Comment by DarkWiss** [comment]
So, Yeah I was using MPC-HC. I deleted everything and cleaned the remaining folders. I installed the 0.3.0 and I had the same issue on every stream I tried even with other players. 
So I installed the Latest version (0.3.1) and everything was great :). and even better with MPV.

Thanks guys :)

**Comment by beardypig** [comment]
Cool, I'll close this issue then. If you think that this issue hasn't been resolved just reopen it :-)

**Comment by gravyboat** [comment]
@Romsh Can you give `0.3.1` a shot as well?

**Comment by Romsh** [comment]
Hmm. It's a little better with 0.3.1 but i have some little freeze. 
With MPV it's some little microcut of stream. 
I HAVEN'T those with 0.1.0. 
Can't help you more.

**Comment by beardypig** [comment]
This is just on twitch? Through the twitch gui? It must be HLS streams, if you enable player pass through for hls does it work any better. `0.1.0` might stop working soon as I think it uses an older version of the Twitch API, but maybe it'll keep working :-)

**Comment by gravyboat** [comment]
Any updates when running `0.3.2` or an answer to beardypig's question @Romsh?

**Comment by bastimeyer** [comment]
Going to close the thread since it's been inactive for a while. Please feel free to reopen if this issue persists.

The latest Streamlink version is `0.6.0`:
https://streamlink.github.io/install.html
