### ISSUE TITLE
plugins.youtube: New URL formats are unsupported

### ISSUE THREAD

**Issue by tp0** [streamlink/streamlink#5136]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest build from the master branch

### Description

Trying to open these URL formats lead to same `error: No plugin can handle URL` error.

Affected URL formats are at least:
```
https://www.youtube.com/live/<id>'
https://www.youtube.com/@<handle>/streams
```

### Debug log

```text
$ streamlink -l debug https://www.youtube.com/live/21X5lGlDOfg
[cli][debug] OS:         Linux-5.15.0-58-generic-x86_64-with-glibc2.35
[cli][debug] Python:     3.10.6
[cli][debug] Streamlink: 5.2.1+7.gfbb9ed64
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.6.15
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.8.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.5
[cli][debug]  websocket-client: 1.3.3
[cli][debug]  importlib-metadata: 4.6.4
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/live/21X5lGlDOfg
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv --cache
[cli][debug]  --default-stream=['best']
error: No plugin can handle URL: https://www.youtube.com/live/21X5lGlDOfg
```

**Comment by bastimeyer** [comment]
Thanks. Please take a look at #5137
