### ISSUE TITLE
Slovakian public TV : rtvs.sk

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#519]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

rtvs.sk is a Slovak public TV service including 4 channels. RTVS 1 and RTVS 2 are mostly geoblocked it depends on TV rights. TVNRSR is a parliament channel. 

### Reproduction steps / Stream URLs to test

1. RTVS 1 : `https://www.rtvs.sk/televizia/live-1`
2. RTVS 2 : `https://www.rtvs.sk/televizia/live-2`
3. RTVS O : `https://www.rtvs.sk/televizia/live-o`
4. TVNRSR : `https://www.rtvs.sk/televizia/live-nr-sr`

### Comments, logs, screenshots, etc.

They use HLS and DASH for streaming. 
Here is a source for a stream : 
`https://www.rtvs.sk/json/live5.json?c=4&b=mozilla&p=win&v=51&f=0&d=1`
Cookies are used.

**Comment by intact** [comment]
You can adapt https://github.com/intact/livestreamer/blob/rtvs/src/livestreamer/plugins/rtvs.py

**Comment by karlo2105** [comment]
@intact 
I just tested, working fine. 
Thanks.
