### ISSUE TITLE
omlet.gg

### ISSUE THREAD

**Issue by TaoziDB** [streamlink/streamlink#5190]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

game streaming site
it uses websocket link to wss://omlet.gg/readonlydevice to handle functions such as: listing streams, listing games, fetching live urls, chat, notification, etc
the live streaming uses 2 live formats: rtmp and m3u8, you can get both urls from websocket above.

### Input URLs

http://omlet.gg/stream/megaradio
pick any live link from http://omlet.gg/streams

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blame/master/CONTRIBUTING.md#L54

Junk mobile gaming site without any actual viewers.
