### ISSUE TITLE
plugins.tv5monde: broken

### ISSUE THREAD

**Issue by ROBGagn** [streamlink/streamlink#5202]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The TV5Monde is completely outdated and useless with the actuel website and urls. I have to remove it completely after every streamlink update, otherwise i'm not able to use any of the TV5 hls links from the website. So I think it's better to remove it or update it if possible. Thanks.

### Debug log

```text
N/A
```

**Comment by bastimeyer** [comment]
> i'm not able to use any of the TV5 hls links from the website

https://streamlink.github.io/cli/protocols.html#playing-built-in-streaming-protocols-directly
```
streamlink 'hls://https://...' best
```

**Comment by bastimeyer** [comment]
Post a full debug log please, as requested by the issue form

**Comment by ROBGagn** [comment]
> > i'm not able to use any of the TV5 hls links from the website
> 
> https://streamlink.github.io/cli/protocols.html#playing-built-in-streaming-protocols-directly
> 
> ```
> streamlink 'hls://https://...' best
> ```

"**otherwise** i'm not able to use any of the TV5 hls links from the website" = which means that with the plugin installed in Streamlink, it will start instantly when trying to watch any TV5 channels and stop any attempt to watch the direct HLS links from the TV5 website. This is why it must be removed OR updated in the next Streamlink update in order to avoid this problem...

**Comment by bastimeyer** [comment]
No, it does not if you use the `hls://` prefix for any HLS playlist input URLs. The **HLS plugin** [does have two matchers](https://github.com/streamlink/streamlink/blob/5.3.1/src/streamlink/plugins/hls.py#L13-L18), one with the `hls://` prefix and normal priority (which is obviously not used by any other plugin), and one with `.m3u8` URL path suffixes and the low priority. If the **tv5monde plugin** matches first because you're not using the special `hls://` prefix, then this won't work of course.

If the **tv5monde plugin** is broken and can't resolve the right HLS URLs, then it needs fixing. It should only get removed if it can't be fixed or if it violates the plugin requirement rules. As said, post the full debug log when trying to use the tv5monde plugin.

**Comment by ROBGagn** [comment]
Here is the log, only TV5Monde Europe is not working and need to be update in the plugin (https://europe.tv5monde.com/fr/direct - hls direct link: https://ott.tv5monde.com/Content/HLS/Live/channel(europe)/index.m3u8). The rest is working fine.

TV5Monde France Belgique Suisse Monaco
[cli][info] Found matching plugin tv5monde for URL https://live.tv5monde.com/fbs.html?
[cli][info] Available streams: 216p (worst), 270p, 360p, 540p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.15:129/
[cli][info]  http://127.0.0.1:129/
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 1080p (hls-multi)
[utils.named_pipe][info] Creating pipe streamlinkpipe-14200-1-6511
[utils.named_pipe][info] Creating pipe streamlinkpipe-14200-2-2045

TV5Monde Europe
[cli][info] Found matching plugin tv5monde for URL https://europe.tv5monde.com/fr/direct
error: No playable streams found on this URL: https://europe.tv5monde.com/fr/direct

TV5Monde Maghreb-Orient
[cli][info] Found matching plugin tv5monde for URL https://maghreb-orient.tv5monde.com/fr/direct
[cli][info] Available streams: 216p (worst), 270p, 360p, 540p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.15:129/
[cli][info]  http://10.34.93.116:129/
[cli][info]  http://127.0.0.1:129/
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 1080p (hls-multi)
[utils.named_pipe][info] Creating pipe streamlinkpipe-14384-1-8345
[utils.named_pipe][info] Creating pipe streamlinkpipe-14384-2-4766

TV5Monde Info
[cli][info] Found matching plugin tv5monde for URL https://maghreb-orient.tv5monde.com/fr/direct-tv5monde-info
[cli][info] Available streams: 216p (worst), 270p, 360p, 540p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.15:129/
[cli][info]  http://10.34.93.116:129/
[cli][info]  http://127.0.0.1:129/
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 1080p (hls-multi)
[utils.named_pipe][info] Creating pipe streamlinkpipe-3372-1-6004
[utils.named_pipe][info] Creating pipe streamlinkpipe-3372-2-7378

Tivi5
[cli][info] Found matching plugin tv5monde for URL https://maghreb-orient.tv5monde.com/fr/direct-tv5-jeunesse
[cli][info] Available streams: 216p (worst), 270p, 360p, 540p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.15:129/
[cli][info]  http://10.34.93.116:129/
[cli][info]  http://127.0.0.1:129/
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 1080p (hls-multi)
[utils.named_pipe][info] Creating pipe streamlinkpipe-8452-1-2605
[utils.named_pipe][info] Creating pipe streamlinkpipe-8452-2-4004

TV5Monde Style
[cli][info] Found matching plugin tv5monde for URL https://maghreb-orient.tv5monde.com/fr/direct-style-hd
[cli][info] Available streams: 216p (worst), 270p, 360p, 540p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.15:129/
[cli][info]  http://10.34.93.116:129/
[cli][info]  http://127.0.0.1:129/
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 1080p (hls-multi)
[utils.named_pipe][info] Creating pipe streamlinkpipe-9144-1-4944
[utils.named_pipe][info] Creating pipe streamlinkpipe-9144-2-4297
