### ISSUE TITLE
plugins.mitele: not working anymore for all channels

### ISSUE THREAD

**Issue by ROBGagn** [streamlink/streamlink#5203]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Started a few days ago. And it's not working anymore on all channels.

### Debug log

```text
Channel = Cuatro
"[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/cuatro/
error: Unable to open URL: https://directos.mitele.es/orilinear21/live/linear21/playlist/playlist.isml/ctv.m3u8?hdnts=st=1677436035~exp=1677436214~acl=/*~hmac=abf7c67309839ee28cec8fb256dd835d76dc8067d223f9479d19b635f3c87d1c (403 Client Error: Forbidden for url: https://directos.mitele.es/orilinear21/live/linear21/playlist/playlist.isml/ctv.m3u8?hdnts=st=1677436035~exp=1677436214~acl=/*~hmac=abf7c67309839ee28cec8fb256dd835d76dc8067d223f9479d19b635f3c87d1c)"
Channel = Telecinco
"[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco/
error: Unable to open URL: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/main.m3u8?hdnts=st=1677436216~exp=1677436396~acl=/*~hmac=5d6dc18fe9aa0ce5e287b25e425f0f14b56528fed691c559a617f1635cabbafb (403 Client Error: Forbidden for url: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/main.m3u8?hdnts=st=1677436216~exp=1677436396~acl=/*~hmac=5d6dc18fe9aa0ce5e287b25e425f0f14b56528fed691c559a617f1635cabbafb)"
etc...
```

**Comment by ROBGagn** [comment]
Hello, I found out that adding the proper header for each mitele channel, it's back so I don't know if you can fix the actual plugin with this.
example for telecinco :
--http-header "Referer=https://www.mitele.es/directo/telecinco/" --http-header "Origin=https://www.mitele.es" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"

But there is also something I noticed before : there are annoying ads on the website. They create "[stream.hls_playlist][warning] Discarded invalid attributes list".
Here is the log : 
c:\Program Files\Streamlink\bin>streamlink.exe --http-header "Referer=https://www.mitele.es/directo/telecinco/" --http-header "Origin=https://www.mitele.es" --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" https://www.mitele.es/directo/telecinco/ best --ffmpeg-copyts --hls-audio-select "*" --locale es_ES --http-proxy "http://AsTJems3WD4V4HgrSTWWkJm9:ROBgagn2021@es-mad.pvdata.host:8080/" --player-external-http --player-external-http-port 5
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco/
[cli][info] Available streams: none_150k, 360p_620k_alt (worst), 360p_620k, 360p_1100k_alt, 360p_1100k, 576p_1900k_alt2, 576p_1900k_alt, 576p_1900k, 720p_3400k_alt, 720p_3400k, 720p_4800k_alt, 720p_4800k (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://10.10.20.45:5/
[cli][info]  http://127.0.0.1:5/
[cli][info]  http://192.168.56.1:5/
[cli][info] Got HTTP request from VLC/3.1.21-rc2 LibVLC/3.1.21-rc2
[cli][info] Opening stream: 720p_4800k (hls)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from VLC/3.1.21-rc2 LibVLC/3.1.21-rc2
[cli][info] Opening stream: 720p_4800k (hls)
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 720p_4800k (hls)
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[cli][info] HTTP connection closed
[cli][info] Stream ended
[cli][info] Got HTTP request from VLC/3.0.18 LibVLC/3.0.18
[cli][info] Opening stream: 720p_4800k (hls)
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[stream.hls_playlist][warning] Discarded invalid attributes list
[cli][info] HTTP connection closed
[cli][info] Stream ended

You have to disconnect, reconnect your player many times in order to get the proper stream back. It is quite random.

Is there any way to bypass or filter these ads ?

Thanks.

Robert

**Comment by joaquinito2070** [comment]
please fix this plugin!!!

**Comment by joaquinito2070** [comment]
[plugins.mitele][error] Error getting pdata: 4001

**Comment by mkbloke** [comment]
Please include a full debug log with `-l debug`.

**Comment by leagueofperez** [comment]
streamlink -l debug  https://www.mitele.es/directo/telecinco best
Not working for me
```

[cli][debug] OS:         Linux-5.4.0-148-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.4.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.12.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.3.3
[cli][debug]  importlib-metadata: 5.1.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.mitele.es/directo/telecinco
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/main.m3u8?hdnts=st=1682799982~exp=1682800161~acl=/*~hmac=5c12a138ed756096649f85ef6df7078ab800c74961143d4e541a3a6161447986 (403 Client Error: Forbidden for url: https://directos.mitele.es/orilinear01/live/linear01/main/main.isml/main.m3u8?hdnts=st=1682799982~exp=1682800161~acl=/*~hmac=5c12a138ed756096649f85ef6df7078ab800c74961143d4e541a3a6161447986)


```

**Comment by mkbloke** [comment]
> [cli][debug] Streamlink: 5.4.0

Have you side-loaded the new plugin?  If you had it should say at the top that it has been done, which is not shown in the log you have provided.  The updated plugin has not been included in any official Streamlink release yet.

Download the new plugin from this link: https://raw.githubusercontent.com/mkbloke/streamlink/b5cc27a75d0870de181ed337692492f10d23d20c/src/streamlink/plugins/mitele.py

and put it into `~/.local/share/streamlink/plugins` (create the directory structure if necessary).

**Comment by leagueofperez** [comment]
ls -l ~/.local/share/streamlink/plugin/mitele.py

```
-rw-rw-r-- 1 user user 4074 abr 29 22:39 /home/user/.local/share/streamlink/plugin/mitele.py
```

streamlink -l debug  https://www.mitele.es/directo/telecinco best

```
[cli][debug] OS:         Linux-5.4.0-148-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.4.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.12.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.3.3
[cli][debug]  importlib-metadata: 5.1.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.mitele.es/directo/telecinco
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/telecinco
[utils.l10n][debug] Language code: es_ES
error: Unable to open URL: https://directos.mitele.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st=1682800973~exp=1682801153~acl=/*~hmac=bded0c4b09c3e24ca66a751018484e29bfe58dff911c542ca683dcbd49f0686b (403 Client Error: Forbidden for url: https://directos.mitele.es/orilinear17/live/linear17/playlist/playlist.isml/ctv.m3u8?hdnts=st=1682800973~exp=1682801153~acl=/*~hmac=bded0c4b09c3e24ca66a751018484e29bfe58dff911c542ca683dcbd49f0686b)
```

**Comment by mkbloke** [comment]
So you are not seeing:
```
[session][debug] Plugin mitele is being overridden by /home/user/.local/share/streamlink/plugins/mitele.py
```
at the top of the debug output then?  What is the output of `echo ${XDG_DATA_HOME:-${HOME}}`?  You could have `XDG_DATA_HOME` set perhaps.

**Comment by mkbloke** [comment]
> `-rw-rw-r-- 1 user user 4074 abr 29 22:39 /home/user/.local/share/streamlink/plugin/mitele.py`

`plugins` not `plugin`.

**Comment by leagueofperez** [comment]
> > `-rw-rw-r-- 1 user user 4074 abr 29 22:39 /home/user/.local/share/streamlink/plugin/mitele.py`
> 
> `plugins` not `plugin`.

it works! tested for about 5 minutes without problems

Shame on me.
I guess i  am not able to copy/paste correctly a simple line of text :disappointed:

**Comment by mkbloke** [comment]
It happens!

Don't forget to delete the side-loaded plugin when you next upgrade Streamlink.
