### ISSUE TITLE
Cyprus tv channels

### ISSUE THREAD

**Issue by ROBGagn** [streamlink/streamlink#5205]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hello,
If anyone can make a plugin for the main national Cyprus tv channels (greek side of Cyprus - public and private ones), that would be really appreciated.
You'll find a list of the available channels in the input URLs section.
Thanks to all.
There is a geo-restriction that could be by-passed using a vpn or a proxy.

### Input URLs

RIK 1
http://cybc.com.cy/live-tv/%cf%81%ce%b9%ce%ba-1/
HLS: https://l6.cloudskep.com/rikcy/rik1/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTM6MDggUE0maGFzaF92YWx1ZT1xaE50RURjV3ZNcmdLeWthdEhaRHd3PT0mdmFsaWRtaW51dGVzPTMw

RIK 2
http://cybc.com.cy/live-tv/%cf%81%ce%b9%ce%ba-2/
HLS: 
https://l6.cloudskep.com/rikcy/rik2/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTM6MzkgUE0maGFzaF92YWx1ZT1HQmNFL0drZC9GeTE2dXExRkQ1dC9BPT0mdmFsaWRtaW51dGVzPTMw

RIK HD
http://cybc.com.cy/live-tv/%cf%81%ce%b9%ce%ba-hd/
HLS: 
https://l6.cloudskep.com/rikcy/rikhd/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTQ6MTIgUE0maGFzaF92YWx1ZT1wNUtVVENzeTNHZVAxNEtyL2o5cWhnPT0mdmFsaWRtaW51dGVzPTMw

RIK SAT
http://cybc.com.cy/live-tv/%cf%81%ce%b9%ce%ba-sat/
HLS: 
https://l3.cloudskep.com/cybcsat/abr/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTQ6NTAgUE0maGFzaF92YWx1ZT0rYzJTbjJmZ2hya1R4bStuS3ZSYlZRPT0mdmFsaWRtaW51dGVzPTMw

SIGMA
https://sigma.com.cy/live
HLS:
https://l10.cloudskep.com/sigmatv/stv/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTY6MjEgUE0maGFzaF92YWx1ZT1LMWpnVG9wbVlDcnhmWXMvTEN2ZTlBPT0mdmFsaWRtaW51dGVzPTYw

ANT1
https://www.ant1live.com/webtv/live
HLS: 
https://l2.cloudskep.com/ant1cm2/abr/playlist.m3u8

ALPHA TV
https://www.alphacyprus.com.cy/live
HLS:
https://l4.cloudskep.com/alphacyp/acy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MTg6NTMgUE0maGFzaF92YWx1ZT05aVNaSHFhd3NqN3J0eHYyZ1oyMGdnPT0mdmFsaWRtaW51dGVzPTMw

OMEGA TV
http://www.omegatv.com.cy/live/
HLS: 
https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDk6MjQ6MDUgUE0maGFzaF92YWx1ZT0vNEZGVlJLVjBrU0VDQmFreVgyanhnPT0mdmFsaWRtaW51dGVzPTY2MA==

**Comment by gravyboat** [comment]
Am I missing something? These look like TV channels which we won't add. I'm also confused because you opened another issue asking for Argentinian channels and now you're asking for channels based in Cyprus. This seems like you're asking us to add everything under the sun which we're not going to do.

**Comment by ROBGagn** [comment]
I'm Argentinian, my wife is Cypriot. That is the reason why...

**Comment by ROBGagn** [comment]
??? You guys make many plugins for many countries even small ones like Cyprus. Why should you avoid this one ?

**Comment by bastimeyer** [comment]
I have no problem with adding a plugin for that, as we have similar plugins from other countries.

The streaming provider however has a broken TLS configuration, and we're not going to disable TLS verification for plugins as a whole, similar to certain streams from Turkey.

```
$ streamlink 'https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA=' best
[cli][info] Found matching plugin hls for URL https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA=
error: Unable to open URL: https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA= (HTTPSConnectionPool(host='l1.cloudskep.com', port=443): Max retries exceeded with url: /omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA= (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)'))))
```

**Comment by ROBGagn** [comment]
Thanks for your answer. Is there any way to add this SSL certificate
verification using Streamlink ?


Le dim. 26 févr. 2023 à 23:43, Sebastian Meyer ***@***.***> a
écrit :

**Comment by bastimeyer** [comment]
This is a server misconfiguration due to negligence or incompetence of the site's maintainers. HTTP clients would need to ignore this (if possible - sometimes it's not just a certificate issue but a TLS version issue), and as said, plugins where TLS verification gets disabled as a whole won't be added.

You are free to write a plugin for yourself, which should be simple enough, and then set `--http-no-ssl-verify` / `self.session.set_option("http-verify", False)`.
https://streamlink.github.io/cli.html#cmdoption-http-no-ssl-verify

```
$ streamlink --http-no-ssl-verify 'https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA=' best
[cli][info] Found matching plugin hls for URL https://l1.cloudskep.com/omegatv/omcy/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yNi8yMDIzIDEwOjM5OjU2IFBNJmhhc2hfdmFsdWU9SWhYemlLTlFFVHAyQnc4elR6MlN0Zz09JnZhbGlkbWludXRlcz02NjA=
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'l1.cloudskep.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  /home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045
[cli][info] Available streams: 288p (worst), 504p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: mpv
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'am4.cloudskep.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  /home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'am4.cloudskep.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  /home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'am4.cloudskep.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  /home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'am4.cloudskep.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  /home/basti/venv/streamlink-311/lib/python3.11/site-packages/urllib3/connectionpool.py:1045
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by ROBGagn** [comment]
Thanks for all the info. I'm a newbie on this, so I will have to learn how
to do it. :-)

Le dim. 26 févr. 2023 à 23:53, Sebastian Meyer ***@***.***> a
écrit :

**Comment by gravyboat** [comment]
> You guys make many plugins for many countries even small ones like Cyprus. Why should you avoid this one ?

It has nothing to do with the country but the quantity of issues/requests you have created in a short period of time. The reason I bring up TV channels is because we don't create plugins for [Sites which are primarily rehosting content that is available from a legitimate source (TV shows, sports, news, etc.)](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests).

**Comment by ROBGagn** [comment]
I'm only using streamlink for PERSONAL USE AND NOTHING ELSE ! So please
stop accusing me of something I'm not doing ! Thank you.
