### ISSUE TITLE
Kick.com

### ISSUE THREAD

**Issue by xch6nce** [streamlink/streamlink#5238]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

About: Kick.com is a jab at modern live streaming site, twitch.
Ran by: unknown
Type of content: Unhinged twitch content
Restrictions: Cloudflare turnstile (bypassable via TLS, [this package works](https://github.com/FlorianREGAZ/Python-Tls-Client))

### Input URLs

https://kick.com

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> 9. Sites which are unmaintained, **are in beta** or are undergoing heavy amounts of development and may change rapidly

----

And on a personal note, it's just another Twitch clone which will be dead in a couple of months, just like the countless other ones.

**Comment by Sethox** [comment]
@bastimeyer, you should have said:
_Only if Trainwrecks himself provides code will I accept the Twitch clone_
Because of the irony of the nickname...

Sorry for the useless At you.
