### ISSUE TITLE
I can't record videos on youtube

### ISSUE THREAD

**Issue by ringtvt** [streamlink/streamlink#5260]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

streamlink -o https://www.youtube.com/watch?v=keqhxqu6PNM
error: No plugin can handle URL: --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

streamlink -debug

### Debug log

```text
streamlink -o https://www.youtube.com/watch?v=keqhxqu6PNM
error: No plugin can handle URL: --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe
```

**Comment by bastimeyer** [comment]
https://streamlink.github.io/changelog.html#streamlink-3-0-0-2021-11-17

> BREAKING: removed the following CLI arguments (and respective session options)
> - `--rtmp-rtmpdump`, `--rtmpdump`, `--rtmp-proxy`, `--rtmp-timeout`
>   Users of Streamlink’s Windows installer will need to update their [config file](https://streamlink.github.io/cli/config.html).

**Comment by ringtvt** [comment]
Can you show me the steps in detail?
I don't use the computer often

**Comment by ringtvt** [comment]
I used: streamlink --config %APPDATA%\streamlink\config
debug:
error: No plugin can handle URL: --rtmpdump=C:\Program Files (x86)\Streamlink\rtmpdump\rtmpdump.exe

**Comment by bastimeyer** [comment]
You have an **outdated** config file with **invalid** options from a **previous install**. You'll have to **fix your old config file** to be able to run a recent version of Streamlink.

Read the documentation.
https://streamlink.github.io/cli/config.html

Read the changelog of the 3.0.0 release from November 2021:
https://streamlink.github.io/changelog.html#streamlink-3-0-0-2021-11-17

And read what Streamlink's Windows installer actually does in regards to the config file:
https://github.com/streamlink/windows-builds#notes

**Comment by bastimeyer** [comment]
> error: No plugin can handle URL: --rtmpdump=...

And this suggests that your config file is completely messed up and not just outdated.

If you can't figure this out, then delete the config file and reinstall Streamlink.

Good luck. This isn't difficult.

**Comment by ringtvt** [comment]
Thank you very much. I made it

**Comment by ringtvt** [comment]
I used the command
streamlink https://www.facebook.com/100089145930280/videos/3709772295929933/
debug: 
No playable streams found on this URL: https://www.facebook.com/100089145930280/videos/3709772295929933/
Is this a plugin error or is it my installation?

**Comment by bastimeyer** [comment]
#4800
