### ISSUE TITLE
Japanese internet radio sites(FMPlapla / JCBA Simul radio)

### ISSUE THREAD

**Issue by blackdan-team-leader** [streamlink/streamlink#5261]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hello.

- What is the site about?
  - Streaming site for [community radio stations](https://en.wikipedia.org/wiki/Community_radio) active in Japan.
- Who is it run by?
  - Japanese private company.
- What kind of content does it provide?
  - Internet radio streaming via WebSocket.
- Are there any access restrictions like logins or region checks?
  - There is no login check, but it checks whether the accessed country is Japan.
  - If you are not accessing from Japan, you will hear a voice guidance such as "This station cannot be heard from outside Japan". (Confirmed with a VPN service using an American IP address operated by [VPNGate](https://www.vpngate.net/))

Others have scripts that support FMPlapla and JCBA Simul radio, but I made a request to use them with streamlink.
- https://kemasoft.net/?scr/fmplapla
- https://kemasoft.net/?scr/jcba

Please consider support for FMPlapla / JCBA Simul radio.

### Input URLs

- https://fmplapla.com/yesfm 
- https://fmplapla.com/fmnishitokyo
- https://fmplapla.com/radioodate 
- https://www.jcbasimul.com/fmshonan
- https://www.jcbasimul.com/iruka
- https://www.jcbasimul.com/fmgaiya

**Comment by gravyboat** [comment]
Violates rule 7 from the [plugin requests](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests): `7. Sites which don't provide any video streaming content, eg. radio stations`
