### ISSUE TITLE
Streamlink's Open Collective account has been archived

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#5265]
Let me quickly post this here, too, for transparency reasons.
https://opencollective.com/streamlink/updates/streamlinks-open-collective-account-is-being-archived

----

Thank you to everyone who backed the Streamlink project or made one or more donations on Open Collective over the past couple of years.

We've decided to close Streamlink's Open Collective account for reasons stated here:
- https://streamlink.github.io/donate.html
- https://github.com/streamlink/streamlink/pull/5143

The donated money has been split among the project maintainers according to an internal team discussion. Once the transactions are completed, which will be in the coming days, we're going to archive Streamlink's Open Collective account, so that any recurring donations get cancelled.

For those of you who want to keep supporting the project, please take a look at the donations page on Streamlink's online documentation. Your financial support is very much appreciated!
https://streamlink.github.io/donate.html

Once again, thank you very much!

**Comment by campones** [comment]
I feel a little sorry that the team has been dismantled . hoping you can keep up with the good work, solo
