### ISSUE TITLE
0.3.1 Windows installer missing

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#527]
The Windows installer is missing from the releases, I _think_ this is due to the docs build failing. See the travis build logs: https://travis-ci.org/streamlink/streamlink/jobs/198033954 

```
Warning, treated as error:
../CHANGELOG.rst:2: WARNING: Title underline too short.
streamlink 0.3.1 (2017-02-03)
----------
make: *** [html] Error 1
make: Leaving directory `/home/travis/build/streamlink/streamlink/docs'
```

**Comment by gravyboat** [comment]
Good catch, thanks @beardypig.

**Comment by cdrage** [comment]
@beardypig Yup, this is my fault, I just got the travis ci notification too. I'll go ahead and fix it.

**Comment by cdrage** [comment]
#529 and #530 should fix this ^^

**Comment by gravyboat** [comment]
@cdrage I think we're all set to go for the rebuild.
