### ISSUE TITLE
plugins.pandalive: identity verification

### ISSUE THREAD

**Issue by KOONWHITE** [streamlink/streamlink#5271]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I'm having this problem now.
streamlink --http-cookie "_ga_W91XDLC3YE=<GS1.1.1680342372.187.1.1680344826.0.0.0>" "https://www.pandalive.co.kr/live/play/answl0810" best -o "a.ts"
![dfa](https://user-images.githubusercontent.com/129593259/229285280-95a738ce-aaa5-49c6-9d4f-411eb2fe6da3.png)
My account is a identity verification account.
Even if I change the cookie information I got, the result is the same.

### Debug log

```text
PS E:\PANDATV_FLEXTV\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin> streamlink --http-cookie "_ga_W91XDLC3YE=<GS1.1.1680342372.187.1.1680344826.0.0.0>" "https://www.pandalive.co.kr/live/play/answl0810" best -o "a.ts"
[cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/answl0810
[plugins.pandalive][error] 본인인증이 필요합니다..
error: No playable streams found on this URL: https://www.pandalive.co.kr/live/play/answl0810
PS E:\PANDATV_FLEXTV\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin>
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/pull/4064#issuecomment-1014713077

**Comment by SAOJSM** [comment]
> ### Checklist
> * [x]  This is a plugin issue and not a different kind of issue
> * [x]  [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
> * [x]  [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
> * [x]  [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)
> 
> ### Streamlink version
> Latest stable release
> 
> ### Description
> I'm having this problem now. streamlink --http-cookie "_ga_W91XDLC3YE=<GS1.1.1680342372.187.1.1680344826.0.0.0>" "https://www.pandalive.co.kr/live/play/answl0810" best -o "a.ts" ![dfa](https://user-images.githubusercontent.com/129593259/229285280-95a738ce-aaa5-49c6-9d4f-411eb2fe6da3.png) My account is a identity verification account. Even if I change the cookie information I got, the result is the same.
> 
> ### Debug log
> ```
> PS E:\PANDATV_FLEXTV\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin> streamlink --http-cookie "_ga_W91XDLC3YE=<GS1.1.1680342372.187.1.1680344826.0.0.0>" "https://www.pandalive.co.kr/live/play/answl0810" best -o "a.ts"
> [cli][info] Found matching plugin pandalive for URL https://www.pandalive.co.kr/live/play/answl0810
> [plugins.pandalive][error] 본인인증이 필요합니다..
> error: No playable streams found on this URL: https://www.pandalive.co.kr/live/play/answl0810
> PS E:\PANDATV_FLEXTV\ffmpeg-6.0-full_build\ffmpeg-6.0-full_build\bin>
> ```

Because you copy the wrong value. Just login and open dev mode, Network, search login, then copy cookie value. I can't tell more, try to do yourself

**Comment by KOONWHITE** [comment]
Thank you.
As you said, I tried again and got the result I wanted.
Thank you.
