### ISSUE TITLE
Filtered stream getting closed when resuming with `--player-continuous-http`

### ISSUE THREAD

**Issue by templateK** [streamlink/streamlink#5286]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Twitch.tv stream is getting closed even though the stream hasn't been ended when the streamlink is executed with combination of `--twitch-disable-ads` and `--player-continuous-http`

if pre-roll ads is running, we have to start the streamlink few times repeatedly until ad roll segment has been passed through. 
if mid-roll ads is running, the streamlink session is getting closed immediately. 

### Debug log

```text
[cli][debug] OS:         macOS 10.14.5
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.1.0+3.gf17c2fa0
[cli][debug] Dependencies:
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/nl_kripp
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --logfile=/ram/nl_kripp.log
[cli][debug]  --player=/tools/mpv/bin/mpv
[cli][debug]  --player-continuous-http=True
[cli][debug]  --retry-streams=1.0
[cli][debug]  --stream-segment-threads=1
[cli][debug]  --hls-live-edge=3
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][info] Found matching plugin twitch for URL twitch.tv/nl_kripp
[plugins.twitch][debug] Getting live HLS streams for nl_kripp
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60 (best)
[cli][info] Starting player: /tools/mpv/bin/mpv
[cli.output][debug] Opening subprocess: /tools/mpv/bin/mpv --force-media-title=twitch.tv/nl_kripp http://127.0.0.1:61990/
[cli][info] Got HTTP request from libmpv
[cli][info] Opening stream: 720p60 (hls)
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Discarding segment 1
[stream.hls][info] Filtering out segments and pausing stream output
[stream.hls][debug] Discarding segment 2
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Discarding segment 3
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Discarding segment 4
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Discarding segment 5
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Discarding segment 6
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Discarding segment 7
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[plugins.twitch][info] This is not a low latency stream
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Writing segment 8 to output
[cli][debug] Writing stream to player
[stream.hls][debug] Segment 8 complete
[stream.hls][info] Resuming stream output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Writing segment 9 to output
[stream.hls][debug] Segment 9 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Writing segment 10 to output
[stream.hls][debug] Segment 10 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Writing segment 11 to output
[stream.hls][debug] Segment 11 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Writing segment 12 to output
[stream.hls][debug] Segment 12 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Writing segment 13 to output
[stream.hls][debug] Segment 13 complete

...

[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 557 to queue
[stream.hls][debug] Discarding segment 557
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 558 to queue
[stream.hls][debug] Writing segment 558 to output
[stream.hls][debug] Segment 558 complete
[stream.hls][info] Resuming stream output
[cli][info] HTTP connection closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by templateK** [comment]
I cannot reproduce reliably pre-roll ads case. Most of the time, streamlink session continues normally after pre-roll ads filtering, but other times it won't.

**Comment by bastimeyer** [comment]
> Streamlink: 5.1.0+3.gf17c2fa0

Please update to the latest version. 5.1.0 is using an outdated implementation for feeding data to the player.
https://streamlink.github.io/install.html

> [stream.hls][info] Resuming stream output
> [cli][info] HTTP connection closed

This is not related to any plugin or even stream implementation.

This is the StreamRunner reacting to the HTTP server connection being closed while trying to write the read stream data to the HTTP connection where your player will read from.

Implementation from the current release:
https://github.com/streamlink/streamlink/blob/5.4.0/src/streamlink_cli/streamrunner.py#L145

The log message suggests that one of these errors was encountered, which is not the fault of Streamlink

- https://docs.python.org/3/library/exceptions.html#BrokenPipeError
- https://docs.python.org/3/library/exceptions.html#ConnectionResetError

**Comment by templateK** [comment]
I apologize for not carefully reading issue filing requirement of using latest or master branch version of streamlink.

Anyway, I tested with latest streamlink again. The behavior is same as earlier tests except an additional log message.
```
[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.
```

these mid-roll ads log has nothing more interesting compared to previous log.

[mid-roll ads log case 1](https://gist.github.com/templateK/197d9d4cd282fb5058ff6e336cbdd421)
[mid-roll ads log case 2](https://gist.github.com/templateK/d60bfa41eaa8ca68614963fd6eef91d1)

Log of the pre-roll ads case. The player even didn't started.

```text
[cli][debug] OS:         macOS 10.14.5
[cli][debug] Python:     3.10.7
[cli][debug] Streamlink: 5.4.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.9.14
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.1
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.15.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/cohhcarnage
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --logfile=/ram/cohhcarnage.log
[cli][debug]  --player=/tools/mpv/bin/mpv
[cli][debug]  --player-args=--demuxer-termination-timeout=360
[cli][debug]  --player-continuous-http=True
[cli][debug]  --twitch-disable-ads=True
[cli][info] Found matching plugin twitch for URL twitch.tv/cohhcarnage
[plugins.twitch][debug] Getting live HLS streams for cohhcarnage
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60 (best)
[cli][info] Starting player: /tools/mpv/bin/mpv
[cli.output][debug] Opening subprocess: /tools/mpv/bin/mpv --force-media-title=twitch.tv/cohhcarnage --demuxer-termination-timeout=360 http://127.0.0.1:51935/
[cli][info] Got HTTP request from libmpv
[cli][info] Opening stream: 720p60 (hls)
[plugins.twitch][info] Will skip ad segments
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][debug] First Sequence: 0; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Discarding segment 1
[stream.hls][info] Filtering out segments and pausing stream output
[stream.hls][debug] Discarding segment 2
[stream.hls][debug] Discarding segment 3
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Discarding segment 4
[stream.hls][debug] Discarding segment 5
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Discarding segment 6
[stream.hls][debug] Discarding segment 7
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Writing segment 8 to output
[stream.hls][debug] Segment 8 complete
[cli][debug] Writing stream to player
[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.
[stream.hls][info] Resuming stream output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Writing segment 9 to output
[stream.hls][debug] Segment 9 complete
[cli][info] HTTP connection closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Writing segment 10 to output
[stream.hls][debug] Segment 10 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

I tried extend player timeout settings  but had no luck apparently.

**Comment by bastimeyer** [comment]
> [cli][debug] OS:         macOS 10.14.5
> [cli][debug]  --logfile=/ram/cohhcarnage.log
> [cli][debug]  --player=/tools/mpv/bin/mpv

What environment is this?

As I explained earlier, "HTTP connection closed" means that `streamlink_cli` couldn't write to the socket connection of its HTTP server after reading the downloaded stream contents from its ringbuffer. This specific log message does only get shown if the error code is either `ECONNRESET`, `EPIPE` or `EINVAL`. Other errors get logged differently.

Since you're only encountering this issue after the stream output resumed from filtering out ads, this suggests that the socket connection has timed out, e.g. the player has disconnected. I can't see any issue like that on my Arch Linux system using MPV.

I do however see a different issue using MPV when resuming the stream output while using `--player-continuous-http`. I've only seen this just now, but MPV wrapped back to the beginning of its buffered content (I have set a large back-buffer for timeshifting reasons) and it kept playing from the beginning. This then led to it not fetching any more data from Streamlink, so Streamlink's buffer got filled after a bit and the stream paused due to that. The HTTP connection was kept alive by MPV however. It only got closed when I closed the player instance (`ECONNRESET` / "Connection reset by peer").

This seems like an issue with MPV and how it behaves when reading from network streams, aka. HTTP streams.
https://mpv.io/manual/stable/#protocols

You can apply the following diff to be able to see the full error message:
```diff
diff --git a/src/streamlink_cli/streamrunner.py b/src/streamlink_cli/streamrunner.py
index 868081fc..fe47e5ff 100644
--- a/src/streamlink_cli/streamrunner.py
+++ b/src/streamlink_cli/streamrunner.py
@@ -142,7 +142,7 @@ class StreamRunner:
             if self.playerpoller and err.errno in ACCEPTABLE_ERRNO:
                 self.playerpoller.playerclosed()
             elif self.is_http and err.errno in ACCEPTABLE_ERRNO:
-                log.info("HTTP connection closed")
+                log.info(f"HTTP connection closed: {err}")
             else:
                 raise OSError(f"Error when writing to output: {err}, exiting") from err
```

**Comment by bastimeyer** [comment]
> MPV wrapped back to the beginning of its buffered content

Setting MPV's `--network-timeout=0` parameter fixes that.
https://mpv.io/manual/stable/#options-network-timeout

```
streamlink --player mpv --player-args '--network-timeout=0' ...
```

Does that help with your HTTP connection issue?

**Comment by templateK** [comment]
I can confirm that this issue caused by mpv /os environment of mine.

VLC don't have this problem and mpv with `--network-timeout=0` solves this issue.

I thought the default value `network-timeout=60` of mpv is enough because it disconnects immediately from http server but the value was relevant because mpv uses default value of `ffmpeg` when the `network-timeout=0`.

I think this information doesn't matter at this point but nonetheless the error code for network timeout is
`[cli][info] HTTP connection closed: [Errno 32] Broken pipe`

Thank you for patiently guiding me and solving this issue.
