### ISSUE TITLE
plugins.afreeca: Connection aborted / ConnectionResetError 10054

### ISSUE THREAD

**Issue by vztpfkb** [streamlink/streamlink#5308]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Version: streamlink 5.4
The afreecatv plugin cannot be called correctly. It seems that some internal execution methods of the plugin were understood as attacking the server and causing the connection to be closed. My technical and English skills are not very good, and I have been unable to use the program on afreecatv. Can someone help answer this question?

### Debug log

```text
C:\Users\Administrator\Desktop>streamlink --loglevel=debug https://play.afreecat
v.com/kcphy0909rk/246112603
[cli][debug] OS:         Windows 7
[cli][debug] Python:     3.8.16
[cli][debug] Streamlink: 5.4.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.12.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/kcphy0909rk/246112603
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/kcp
hy0909rk/246112603
error: Unable to open URL: http://live.afreecatv.com/afreeca/player_live_api.php
 (('Connection aborted.', ConnectionResetError(10054, 'The remote host forced a shutdown of an instance
Some connections.', None, 10054, None)))
```

**Comment by bastimeyer** [comment]
> `'Connection aborted.', ConnectionResetError(10054`

The error is already telling you what's happened. Your system's connection to their servers was aborted while trying to access the player-live-API.

No issues here, but the connection is very poor/slow.

Not a plugin issue.

```
$ streamlink -l debug 'https://play.afreecatv.com/kcphy0909rk/246112603' best
[cli][debug] OS:         Linux-6.2.11-1-git-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.4.0+10.gf9bcdbca
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.12.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/kcphy0909rk/246112603
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/kcphy0909rk/246112603
[cli][info] Available streams: sd (worst), hd, original (best)
[cli][info] Opening stream: original (hls)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 2136; Last Sequence: 2141
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 2139; End Sequence: None
[stream.hls][debug] Adding segment 2139 to queue
[stream.hls][debug] Adding segment 2140 to queue
[stream.hls][debug] Adding segment 2141 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Writing segment 2139 to output
[stream.hls][debug] Segment 2139 complete
[cli.output][debug] Opening subprocess: mpv --force-media-title=https://play.afreecatv.com/kcphy0909rk/246112603 -
[cli][debug] Writing stream to output
[stream.hls][debug] Adding segment 2142 to queue
[stream.hls][debug] Adding segment 2143 to queue
[stream.hls][debug] Writing segment 2140 to output
[stream.hls][debug] Segment 2140 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 2144 to queue
[stream.hls][debug] Adding segment 2145 to queue
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by vztpfkb** [comment]
But when I access afreecatv from a browser, there is no problem, and my Win10 system can also access afreecatv, but streamlink cannot work. Is it possible that my system is missing some dependency environment?

Or is it related to your IP address? After I replaced and used the VPN line in Los Angeles, the error prompt changed to:

error: Unable to open URL: http://livestream-manager.afreecatv.com/broad_stream_assign.html (404 Client Error: Not Found for url: http://livestream-manager.afreecatv.com/broad_stream_assign.html?return_type=gs_cdn_pc_web&broad_key=246115740 -common-original-hls)

**Comment by mkbloke** [comment]
Try uninstalling Streamlink completely and re-installing.  If that doesn't help there's nothing that can be done here.  

Windows 7 isn't really supported and the issue appears to be specific to your installation.

**Comment by vztpfkb** [comment]
> Try uninstalling Streamlink completely and re-installing. If that doesn't help there's nothing that can be done here.
> 
> Windows 7 isn't really supported and the issue appears to be specific to your installation.

I reinstalled streamlink, but Win7 and Win11 still showed error 10054.

At present, it can only work on another laptop (ubunt22 system and using Los Angeles line), but the experience is poor, with an average speed of around 200k. Moreover, after recording for 30 seconds, it will appear: Failed to open fetch segment, Unable to open URL&400 Client Error, and then stop working.

This seems to have a lot to do with the IP line.
