### ISSUE TITLE
plugins.twitch: Unable to open URL: https://api.twitch.tv/kraken/user.json

### ISSUE THREAD

**Issue by k2helix** [streamlink/streamlink#5311]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

When using streamlink to play any kind of twitch stream, it returns the following error: `error: Unable to open URL: https://api.twitch.tv/kraken/users.json (410 Client Error: Gone for url: https://api.twitch.tv/kraken/users.json?as3=t&login=illojuan)`

### Debug log

```text
[cli][debug] OS:         Linux-5.4.0-1105-azure-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 1.3.1
[cli][debug] Requests(2.22.0), Socks(1.6.7), Websocket(0.53.0)
[cli][info] Found matching plugin twitch for URL https://twitch.tv/illojuan
[plugin.twitch][debug] Getting live HLS streams for illojuan
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (410 Client Error: Gone for url: https://api.twitch.tv/kraken/users.json?as3=t&login=illojuan)
```

**Comment by mkbloke** [comment]
> [cli][debug] Streamlink: 1.3.1

This is an ancient release.  Consult the docs and upgrade to the latest release.

**Comment by k2helix** [comment]
> > [cli][debug] Streamlink: 1.3.1
> 
> This is an ancient release. Consult the docs and upgrade to the latest release.

true lmao
I installed it via apt so idk why it is wrong.

**Comment by bastimeyer** [comment]
> I installed it via apt so idk why it is wrong.

- https://streamlink.github.io/install.html#package-availability
- #4670
