### ISSUE TITLE
Allente.se

### ISSUE THREAD

**Issue by Jimpan81** [streamlink/streamlink#5318]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Nordic ( Sweden) legal tv provider https://tv.allente.se/ 
The channels look like this : https://tv.allente.se/channels/5470/tv/asset/live/4091441/svt1-hd

its a payed service with login / password 

### Input URLs

https://tv.allente.se/asset/live/4091441/svt1-hd

https://tv.allente.se/channels/5470/tv/asset/live/4091442/svt2-hd

https://tv.allente.se/channels/5470/tv/asset/live/5366303/tv3

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md

> 4. Sites which require any sort of cable login **or subscription**

No one will be able to maintain a plugin for this site.
