### ISSUE TITLE
Can you consider joining Douyu Live?

### ISSUE THREAD

**Issue by emmIsabella** [streamlink/streamlink#5329]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

https://www.douyu.com

**Comment by mkbloke** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

**Comment by bastimeyer** [comment]
Duplicate of #4511
