### ISSUE TITLE
Streamlink to vlc this stream

### ISSUE THREAD

**Issue by devwhatsapp** [streamlink/streamlink#533]
- [x] This is a plugin request.
- [x] This is a feature request.

### Description

Stream link - http://nbastreams.pw/fox.php?title=73a28b73543c4fe7c22ef24532315015

Hi would like to get the stream downloaded or piped to vlc

It has some aes encryption

How to go about it ?

Thank you

**Comment by beardypig** [comment]
It's doesn't just work if you do

```
streamlink hlsvariant://http://nbastreams.pw/cache4/73a28b73543c4fe7c22ef24532315015.m3u8 best
```
?

**Comment by beardypig** [comment]
This works 
```
streamlink --http-cookie "access=true" hlsvariant://http://nbastreams.pw/cache4/73a28b73543c4fe7c22ef24532315015.m3u8 best
```

**Comment by gravyboat** [comment]
Thanks for answering this one @beardypig! Going to close for now.

**Comment by devwhatsapp** [comment]
@beardypig Sorry for not trying on my own with the manual. But really grateful that you still did it for me,

Thanks again , cheers
