### ISSUE TITLE
Plugin for ludo.fr

### ISSUE THREAD

**Issue by Surfoo** [streamlink/streamlink#534]
Hello,

Could you add a new plugin for ludo.fr, it's almost the same plugin like the pluzz plugin (same french TV)

Thanks!

**Comment by gravyboat** [comment]
Can we see some examples URLs and so forth?

**Comment by Surfoo** [comment]
for example: 
  - http://www.ludo.fr/heros/il-etait-une-fois-la-vie

**Comment by gravyboat** [comment]
Closing since the associated PR is merged.
