### ISSUE TITLE
--ffmpeg-fout not working with mpegts/mp4 on twitch

### ISSUE THREAD

**Issue by CrazyWolf13** [streamlink/streamlink#5349]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello there
I'm downloading Twitch Livestreams via Streamlink and then streaming them with jellyfin. Recently I noticed some very high load when streaming a file from my jellyfin server, and after investigating I found out that the video gets transformed because the container is mpegts which is not supported by the browser. This is a huge problem to me because my server crashes on the load of transcoding.

streamlink --twitch-disable-ads --output "/${name^} ({time:%Y.%m.%d.%H.%M}).mp4" "[https://www.twitch.tv/${name}](https://www.twitch.tv/$%7Bname%7D)" best

But if I get info about the file with ffprobe it shows container format mpegts even if I use --ffmpeg-fout "mp4"
 
Some general note, I use a RaspberryPi for this so heavy transcoding may not be the best solution.

### Debug log

```text
$streamlink --twitch-disable-ads --ffmpeg-fout "mp4"  --output "/mnt/Seagate/Musik/Test ({time:%Y
.%m.%d.%H.%M}).mp4" "https://www.twitch.tv/Crazy_Wolf_ahuuu" best


[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/Crazy_Wolf_ahuuu
[cli][info] Available streams: audio_only, 1080p60 (worst, best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Writing output to
/mnt/Seagate/Musik/Test (2023.05.18.20.19).mp4
[plugins.twitch][info] Will skip ad segments
[download] Written 11.57 MiB to /mnt/Seagate/Musik/Test (2023.05.18.20.19).mp4 (37s @ 320.28 KiB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-fout

> **When** muxing streams, set the output format to OUTFORMAT.

Streamlink doesn't support arbitrary muxing of its output streams. The CLI parameter only affects instances of `MuxedStream`.
https://streamlink.github.io/api.html#module-streamlink.stream

The output of Streamlink Twitch plugin are simple `HLSStream`s, not `MuxedStream`s/`MuxedHLSStream`s

```sh
streamlink --json twitch.tv/gorgc | jq -r '.streams | to_entries | map({(.key): (.value.type)}) | add'
```
```json
{
  "audio_only": "hls",
  "160p": "hls",
  "360p": "hls",
  "480p": "hls",
  "720p60": "hls",
  "1080p60": "hls",
  "worst": "hls",
  "best": "hls"
}
```

Pipe the stream into ffmpeg and remux manually.

```
streamlink --stdout ... | ffmpeg -i pipe:0 ...
```

**Comment by CrazyWolf13** [comment]
> 

Oh I see, so this is "intended". Thank you for claryfing.

**Comment by CrazyWolf13** [comment]
> https://streamlink.github.io/cli.html#cmdoption-ffmpeg-fout
> 
> > **When** muxing streams, set the output format to OUTFORMAT.
> 
> Streamlink doesn't support arbitrary muxing of its output streams. The CLI parameter only affects instances of `MuxedStream`.
> https://streamlink.github.io/api.html#module-streamlink.stream
> 
> The output of Streamlink's Twitch plugin are simple `HLSStream`s, not `MuxedStream`s/`MuxedHLSStream`s
> 
> ```sh
> streamlink --json twitch.tv/gorgc | jq -r '.streams | to_entries | map({(.key): (.value.type)}) | add'
> ```
> ```json
> {
>   "audio_only": "hls",
>   "160p": "hls",
>   "360p": "hls",
>   "480p": "hls",
>   "720p60": "hls",
>   "1080p60": "hls",
>   "worst": "hls",
>   "best": "hls"
> }
> ```
> 
> Pipe the stream into ffmpeg and remux manually.
> 
> ```
> streamlink --stdout ... | ffmpeg -i pipe:0 ...
> ```

Hello
Sorry for asking again, but is there any way to do this on a raspberrypi? 
Copying the the single audio/video inputs without id3_subtitle only gives me around 1.05x speed which just isn't enough.

Id3 subtitle index is what is making problems with the media player.
