### ISSUE TITLE
plugins.dash: partial URL gets matched

### ISSUE THREAD

**Issue by pfer-95** [streamlink/streamlink#5366]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Hello.
First of all, I must say that I'm not a programmer, I'm, at most, tech savy, so forgive if I'm making something stupid or not seing the obvious. I also tried to google the issue, but I got no results.
Recently, my provider changed the url scheme and I'm unable to get the manifests/streams using Streamlink (I would like to note that there's no DRM involved whatsoever).

Previously, my provider had links with the following scheme, that worked great:
`https://hostname/sdash/channel,token=XXXXXXXXXXXXXXXX/index.mpd?device=PC`
But now they have the following scheme:
`https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC`

This seems to be some regex problem, because Streamlink gets the link up to .mpd and seems to discard the rest of the link (it gets the "https://hostname/sdash/channel/index.mpd", but discards the ",token=XXXXXXXXXXXXXXXX/Manifest?device=PC"), making it unable to get the manifest/stream.
If I open the same https://hostname/sdash/channel/index.mpd (without the rest of the link) in the browser, I get the same error code 400. Also, I piped the same links (https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC), with the same data, through ffmpeg and it's working.
I read the cli documentation and I did't see anything that could help me to solve this, so I'm reporting this possible issue.

Lastly, I would like to thank to all Streamlink contributers, because it's an amazing piece of software.

PS: I had to redact most of the link, because it contains personaly identifiable data. The streams are also geoblocked.

### Debug log

```text
[cli][debug] OS:         Linux-6.3.3-artix1-1-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.2
[cli][debug] Arguments:
[cli][debug]  url=https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC
[cli][debug]  --loglevel=debug
[cli][debug]  --logfile=/home/PC/log.log
[cli][debug]  --player=mpv
[cli][debug]  --http-header=[('User-Agent', 'PC')]
[cli][info] Found matching plugin dash for URL https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC
[plugins.dash][debug] URL=https://hostname/sdash/channel/index.mpd; params={}
error: Unable to open URL: https://hostname/sdash/channel/index.mpd (400 Client Error: Bad Request for url: https://hostname/sdash/channel/index.mpd)
```

**Comment by bastimeyer** [comment]
> This seems to be some regex problem

No, you're just not using your command line shell correctly. It interprets `?` as a special character.
https://streamlink.github.io/cli/tutorial.html#shell-syntax

**Comment by pfer-95** [comment]
> > This seems to be some regex problem
> 
> No, you're just not using your command line shell correctly. It interprets `?` as a special character. https://streamlink.github.io/cli/tutorial.html#shell-syntax

I always escape the links using single quotes.

**Comment by bastimeyer** [comment]
The debug log shows the exact arguments it has received. If you get a 4xx or 5xx HTTP response, then you're missing headers or query parameters, or your access is restricted otherwise.

It's also possible that you need to set the explicit `dash://` prefix to your input URL because of how the DASH plugin receives its (implicit / low-priority) input URL.
```sh
streamlink 'dash://https://...' best
```

**Comment by bastimeyer** [comment]
Apologies, let's re-tag this as plugin issue, because the implicit URL matchers of the HLS and DASH plugins should be made more strict. #5367

**Comment by pfer-95** [comment]
@bastimeyer Hello again, thank you for point me in the right direction and sorry for the late reply.

You were spot on and the `dash://` prefix works and now Streamlink uses the complete url to get the manifest/stream.
The problem now is that it doesn't open the selected video player (I tried with MPV and VLC). Do i have to add something more to my cli command to open this kind of stream?

`streamlink --loglevel debug --logfile=/home/PC/log.log --ffmpeg-verbose --player=mpv --http-header "User-Agent=PC" 'dash://https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC'`

Log:
```
[cli][debug] OS:         Linux-6.3.3-artix1-1-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.5.2
[cli][debug] Arguments:
[cli][debug]  url=dash://https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --logfile=/home/PC/log.log
[cli][debug]  --player=mpv
[cli][debug]  --ffmpeg-verbose=True
[cli][debug]  --http-header=[('User-Agent', 'PC')]
[cli][info] Found matching plugin dash for URL dash://https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC
[plugins.dash][debug] URL=https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC; params={}
[utils.l10n][debug] Language code: en_US
[stream.dash][debug] Available languages for DASH audio streams: eng (using: eng)
[cli][info] Available streams: 576p (worst), 720p, 1080p (best)
[cli][info] Opening stream: 1080p (dash)
[cli][info] Starting player: mpv
[stream.dash][debug] Opening DASH reader for: ('1', '1', 'dzEAAFBg') - video/mp4
[stream.dash][debug] Opening DASH reader for: ('1', '3', 'dyHhAZ9.') - audio/mp4
[stream.dash][debug] video/mp4 segment initialization: downloading (1970-01-01T00:00:00.000000Z / 2023-05-30T10:33:10.001840Z)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash][debug] audio/mp4 segment initialization: downloading (1970-01-01T00:00:00.000000Z / 2023-05-30T10:33:10.008350Z)
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] video/mp4 segment 5399: waiting 150.0s (2023-05-30T10:35:40.000000Z / 2023-05-30T10:33:10.012086Z)
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] video/mp4 segment initialization: completed
[stream.dash][debug] audio/mp4 segment 5399: waiting 150.0s (2023-05-30T10:35:39.994367Z / 2023-05-30T10:33:10.034397Z)
[stream.dash][debug] audio/mp4 segment initialization: completed
[stream.ffmpegmux][debug] ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
[stream.ffmpegmux][debug]  built with gcc 13.1.1 (GCC) 20230429
[stream.ffmpegmux][debug]  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
[stream.ffmpegmux][debug]  libavutil      58.  2.100 / 58.  2.100
[stream.ffmpegmux][debug]  libavcodec     60.  3.100 / 60.  3.100
[stream.ffmpegmux][debug]  libavformat    60.  3.100 / 60.  3.100
[stream.ffmpegmux][debug]  libavdevice    60.  1.100 / 60.  1.100
[stream.ffmpegmux][debug]  libavfilter     9.  3.100 /  9.  3.100
[stream.ffmpegmux][debug]  libswscale      7.  1.100 /  7.  1.100
[stream.ffmpegmux][debug]  libswresample   4. 10.100 /  4. 10.100
[stream.ffmpegmux][debug]  libpostproc    57.  1.100 / 57.  1.100
[utils.named_pipe][info] Creating pipe streamlinkpipe-4406-1-4252
[utils.named_pipe][info] Creating pipe streamlinkpipe-4406-2-1919
[stream.ffmpegmux][debug] ffmpeg command: /usr/bin/ffmpeg -nostats -y -i /tmp/streamlinkpipe-4406-1-4252 -i /tmp/streamlinkpipe-4406-2-1919 -c:v copy -c:a copy -copyts -f matroska pipe:1
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-4406-1-4252
[stream.ffmpegmux][debug] Starting copy to pipe: /tmp/streamlinkpipe-4406-2-1919
[cli][debug] Pre-buffering 8192 bytes
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash][debug] Reloading manifest ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.dash][debug] Reloading manifest ('1', '3', 'dyHhAZ9.')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
[stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '3', 'dyHhAZ9.')
[stream.ffmpegmux][error] Error while reading from substream: Read timeout
[stream.ffmpegmux][error] Error while reading from substream: Read timeout
[cli.output][debug] Opening subprocess: mpv --force-media-title=dash://https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC -
[cli][debug] Writing stream to output
[stream.ffmpegmux][debug] Closing ffmpeg thread
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.segmented][debug] Closing worker thread
[stream.dash][debug] video/mp4 segment 5399: cancelled
[stream.segmented][debug] Closing writer thread
[stream.dash][debug] audio/mp4 segment 5399: cancelled
[stream.ffmpegmux][debug] Closed all the substreams
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```


With the same url/headers used directly in ffmpeg and piping to mpv works great:
`ffmpeg -headers "User-Agent: PC" -i 'https://hostname/sdash/channel/index.mpd,token=XXXXXXXXXXXXXXXX/Manifest?device=PC' -c:v copy -c:a copy -f matroska pipe:1 | mpv -`

Again, thank you very much for looking into this.

**Comment by bastimeyer** [comment]
> it doesn't open the selected video player

streamlink_cli will only launch the player process once it has received the first 8 KiB of data.

Without knowing the actual DASH manifest, nobody can really help.

Streamlink's DASH implementation is also still lacking lots of features and some other cases are not covered properly by what's currently implemented. Some timing issues are also not 100% resolved yet.

> [stream.dash_manifest][debug] Generating segment timeline for dynamic playlist: ('1', '1', 'dzEAAFBg')
> [stream.dash][debug] video/mp4 segment 5399: waiting 150.0s (2023-05-30T10:35:40.000000Z / 2023-05-30T10:33:10.012086Z)
> [stream.ffmpegmux][error] Error while reading from substream: Read timeout

You're trying to watch a "dynamic" DASH stream with a "SegmentTimeline", which means that segments are not explicitly listed and instead based on time (in UTC, so your local system time needs to be correct). You can see that Streamlink wants to wait 150 seconds for the availability of the first segment, but since the default timeout value when reading the stream buffer is 60 seconds, the process ends.
https://streamlink.github.io/cli.html#cmdoption-stream-timeout

It's possible that this particular DASH manifest can't be played because of a bug in the segment availability time calculation. Knowing the actual DASH manifest would be needed in order to fix that. That shouldn't be discussed in this thread though.

**Comment by pfer-95** [comment]
> You're trying to watch a "dynamic" DASH stream with a "SegmentTimeline", which means that segments are not explicitly listed and instead based on time (**in UTC, so your local system time needs to be correct**). You can see that Streamlink wants to wait 150 seconds for the availability of the first segment, but since the default timeout value when reading the stream buffer is 60 seconds, the process ends.

@bastimeyer  Absolutely amazing insight, that was my problem.
My system time was behind about 5 minutes and that was what was causing the error.
I didn't know that Streamlink dash protocol was so time sensitive (ffmpeg happily gave me the stream, despide having wrong time).
Is there something in the horizon to solve this timing issues, inside Streamlink?
Anyways, now it's working great as always, thank you very much for your amazing help and I'm sorry if my questions were stupid (I really tried to find the answers on my own, but I couldn't really find anything that fitted my usecase).

**Comment by bastimeyer** [comment]
> SegmentTimeline

Just as a quick correction, I misread and confused SegmentTimeline with SegmentTemplate (there are a couple of different segment definition styles in DASH streams, even combinations of those). SegmentTimelines explicitly list DASH segments, hence why it's a dynamic DASH manifest which needs to be reloaded periodically, similar to HLS playlists. These segments are annotated with durations and availability times in the timelines.

> ffmpeg happily gave me the stream, despide having wrong time

This is a bit complicated, because as said, the SegmentTimeline defines a range of segments and their availability times. This means that you can access lots of different segments back in time, if they are still available on the server. That however also means that your output stream will be delayed by a certain amount. Streamlink tries to access segments relatively near the stream's live-edge while respecting the manifest's `suggestedPresentationDelay` value, so if your system time isn't synced correctly, then you'll have to wait for the availability of the segments.

**Comment by pfer-95** [comment]
I think I understood @bastimeyer 
In a simplified view, ffmpeg seems more permissive with timed streams (at expense of being behind the live transmission), Streamlink tries to be as close to the live transmission as possible, that's the reason why it failed, due to my system being about 5 minutes behind.
Is there a way to turn Streamlink a little bit more permissive?

**Comment by bastimeyer** [comment]
I spent lots of time recently and refactored, rewrote, fixed and improved the entire DASH implementation in the [5.3.0...5.4.0](https://github.com/streamlink/streamlink/compare/5.3.0...5.4.0) releases, but a variable presentation delay override is currently still unsupported:
https://github.com/streamlink/streamlink/blob/34fa502f4416531e45b02fb49a13d55f07d7efb0/src/streamlink/stream/dash_manifest.py#L384-L390
