### ISSUE TITLE
Crunchyroll plugin fails on Python 2.6 (string.format)

### ISSUE THREAD

**Issue by scottbuettner** [streamlink/streamlink#538]
### Checklist

- [x] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.
(didn't actually find any, but I looked)

### Description
The Crunchyroll plugin contains the following format string:
`API_USER_AGENT = "Mozilla/5.0 (iPhone; iPhone OS 8.3.0; {})"`
which fails on Python 2.6, which requires format placeholders to be explicitly numbered. See https://docs.python.org/2.7/library/string.html#formatstrings : 

> Changed in version 2.7: The positional argument specifiers can be omitted, so '{} {}' is equivalent to '{0} {1}'.

### Expected / Actual behavior
Expected: Crunchyroll plugin is able to load stream
Actual:
```
>>> streamlink.streams("http://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-the-man-possessed-by-an-evil-spirit-652155")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/streamlink/api.py", line 13, in streams
    return session.streams(url, **params)
  File "/usr/lib/python2.6/site-packages/streamlink/session.py", line 423, in streams
    return plugin.streams(**params)
  File "/usr/lib/python2.6/site-packages/streamlink/plugin/plugin.py", line 240, in streams
    raise PluginError(err)
streamlink.exceptions.PluginError: zero length field name in format
```

### Reproduction steps / Stream URLs to test
```
>>> import streamlink
>>> streamlink.streams("http://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-the-man-possessed-by-an-evil-spirit-652155")
```
(Also fails on CLI)
My testing failed identically with or without my Crunchyroll credentials, so I believe they are not required to verify this.

### Environment details (operating system, python version, etc.)
CentOS 6, Python 2.6

> Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
> [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2

### Comments, logs, screenshots, etc.
I'll be submitting a (very trivial) pull request shortly. If I have time I'll go through some other plugins and see if they have similar issues.

**Comment by scottbuettner** [comment]
I have just noticed Python 2.6 doesn't seem to work on Crunchyroll anyway given lack of SNI support, which causes SSL/TLS validation errors. Is anyone aware of a workaround for this in 2.6?

**Comment by beardypig** [comment]
You can install `pyOpenSSL` and `idna` and you'll need to install a more recent version of `requests`. `pip install requests>=2.2` should do it. 

Python 2.6 is no longer supported and is not receiving security patches (no idea if CentOS/RHEL are patching security issues in 2.6). I would recommend upgrading to 2.7 if possible and you can avoid breaking `yum` :)

**Comment by scottbuettner** [comment]
The prospect of breaking `yum` is pretty frightening, so I've generally just set up a side by side install of 2.7 or 3.3, which I can certainly still do in this case. It was more that I noticed your docs still said 2.6 was supported, which I see you're now correcting :) So I'll close this as it's pretty irrelevant.
