### ISSUE TITLE
Is there a command to select specific resolution (i.e. 720p) with best bitrate when there are multiple?

### ISSUE THREAD

**Issue by Truanifan** [streamlink/streamlink#540]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Forgive me if I don't make enough sense, but I'll try to explain the best I can... I'm trying to write a batch file to grab a selected resolution at the best bitrate, but not sure what commands to use. The m3u8 has multiple bitrates for the same resolution. Example: 720p at 5996k and 720p at 7795k. From using livestreamer I know I can use name_key=bitrate to select the stream based on the bitrate, but I don't know how to tell the difference between the resolutions based on bitrates and the bitrates vary based on the different videos on the site. When I get a list of the available streams via streamlink I see 720p_alt and 720p, but don't know which has the better bitrate.

Is there a way to make streamlink grab the best bitrate when selecting the 720p stream quality in the command? (example: "hlsvariant://....m3u8" best -o "output.ts")

I know this isn't so much an issue as it is a question, but I hope it's still alright to ask. Thank you in advance for any advice.

**Comment by scottbernstein** [comment]
Yes, @truanifan, the way to format your command line for selecting the best bitrate when there are multiple streams of the same bitrate is as follows:

"hlsvariant://....m3u8 name_key=bitrate" best -o "output.ts")

________________________________

**Comment by Truanifan** [comment]
I think I messed up in my explanation before. I'm not looking for just the best bitrate out of all the available resolutions (which is what I get when I use the command you suggested), but the best bitrate of the 720p resolutions or whatever specific size I choose from the available streams. The resolutions go all the way up to 1080p from 234p, but I'm asking what I can do if I want to grab the best bitrate of the two streams available for a specific resolution.

When I use name_key=bitrate it renders the 720p selection option moot and when I use "best" (as you suggest) it just chooses the best of the best which is 1080p. I'm looking for something that will in essence let me select the best bitrate based on the resolution selection and not specifically the bitrate since the bitrates vary from video to video. 

Is there a way to select the best bitrate of multiple bitrates for a specific resolution?

**Comment by scottbernstein** [comment]
If you're savvy enough to use the CURL command to hit the same .m3u8 URL then you can see the list of all of streams, find the resolution / bit rate combination that you want, pick it manually, and then use hls:// (instead of hlsvariant://) to stream the specific bitrate you want.

________________________________

**Comment by beardypig** [comment]
Can we see the m3u8, it might be possible to give higher priority to the better bitrates at the same resolution when sorting.

**Comment by scottbernstein** [comment]
I had an idea back in the livestreamer days (when it was still being supported by Chrippa) before I found key_name=bitrate option that would solve this problem in a slick manner.  I actually started working on coding it myself but gave up after I found out about the key_name option, which solved my particular issue.


The best solution, IMO would be for streamlink to operate exactly as it does now if there is only one bitrate for each resolution.  But if more than one bitrate is found for any resolution, then it would go back and rename the quality options, appending the bitrate to the resolution like this:

1080p_4300k

1080p_2300k

720p_3000k

720p_1200k


etc


This allows for maximal user choice when there are multiple quality options for each resolution.  And the implementation (given my previous take on coding it) is not difficult at all.  It seemed like under 20 lines of code would need to be changed or created.

________________________________

**Comment by Truanifan** [comment]
@scottbernstein Thanks for the advice. I'm not very savvy enough (yet) to use the CURL command, but I'll try to read up on it and maybe be able to use it properly someday.

As for appending the bitrate to the resolution that would be ideal. I don't know about coding, but if it's possible it really would be immensely helpful. Maybe this can turn into a feature request?

For now, I'll just work around it somehow and read up on CURL.

Thanks for the help so far.

@beardypig The m3u8 needs to be refreshed other wise just pasting it is pointless. If I still run into issues I'll try posting it here. For now I'll just try to work out a work around.

**Comment by scottbernstein** [comment]
@truanifan -- CURL is super easy.  Just download a binary build for your OS.  Then just open a command prompt and type:

curl "http://sitename.com/path/master.m3u8" <- the full exact HLS endpoint you would have entered into streamlink.  (If your URL uses HTTPS you might need to use it in the form of curl -k "https://sitename.com/path/master.m3u8" to get it to bypass the certificate check)


The output returned to your command prompt window will be the HLS manifest which will be explicit in resolutions and bitrates.  Each resolution/bitrate combination will have its own corresponding .m3u8 link.  Just copy the particular stream link that you care about and use the individual bitrate/resolution manifest m3u8 URL as your streamlink input.  The only difference is that instead of using the hlsvariant:// protocol, you will just use the hls:// protocol.


Super easy.


Got it?

________________________________

**Comment by Truanifan** [comment]
@scottbernstein Got it. Thanks a lot for the quick instructions! That does sound super easy. I can't wait to try it out. Thanks again!

**Comment by gravyboat** [comment]
Looks like this is resolved so I'm going to close it for now. Thanks for the detailed response @scottbernstein.

**Comment by beardypig** [comment]
I think there is some enhancement that could come out of this discussion. @scottbernstein's suggestion is good.

**Comment by gravyboat** [comment]
@beardypig Do you want to make a new issue for it? If not we can just open this one back up.

**Comment by beardypig** [comment]
Let's just reopen this one, I'll take a look at implementing a fix now :-)

I have some general thoughts about changing the way streams are described which would solve this and some other issues that I have drempt up, but I'll make a dedicated issue for that :-)

**Comment by back-to** [comment]
looks like this is solved in #675, **Closing**.
there is some similar issue at #1048 with more discussion.
