### ISSUE TITLE
TV Perú

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#5423]
### Checklist

- [X] This is a plugin request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

_TV Perú_ is the public television network of Peruvian state broadcaster IRTP. It is Peru's first channel and the one to have the widest coverage area in the country. 
_Canal IPe_ is a Peruvian open television channel of cultural and educational programming for children and youth audiences.

The website's source code contains a link to _iblups.com_ (e.g. [https://iblups.com/e_tvperuHD](https://iblups.com/e_tvperuHD)) , whose code in turn contains the address of a _cloudfront_ server under the tag `const source = ....`. This address changes every week or two.
At times there is no broadcast over the Internet due to the lack of rights (this is especially true for Canal IPe). 

### Input URLs

TV Peru
[https://www.tvperu.gob.pe/play](https://www.tvperu.gob.pe/play)

TVpe Noticias
[https://www.tvperu.gob.pe/noticias/play](https://www.tvperu.gob.pe/noticias/play)

TVpe Internacional
[https://www.tvperu.gob.pe/internacional/play](https://www.tvperu.gob.pe/internacional/play)

Canal IPe 
[https://www.canalipe.tv/streaming](https://www.canalipe.tv/streaming)

**Comment by NeftaliYagua** [comment]
No necesitas un plugin para utilizar streamlink para TV Perú, puedes simplemente ejecutar:
streamlink https://d6vls0u25arys.cloudfront.net/out/v1/777b4d4cc0984575a7d14f6ee57dbcaf/index.m3u8 best
o también puedes acceder directamente
colocando esta URL en tu reproductor: https://d6vls0u25arys.cloudfront.net/out/v1/777b4d4cc0984575a7d14f6ee57dbcaf/index.m3u8 
o mediante http
https://iblups.com/e_tvperuHD

**Comment by bastimeyer** [comment]
Thanks, but please keep it in English.

----

https://streamlink.github.io/cli/protocols.html

----

> tvperu.gob.pe/play

https://d6vls0u25arys.cloudfront.net/out/v1/777b4d4cc0984575a7d14f6ee57dbcaf/index.m3u8

> tvperu.gob.pe/noticias/play

https://d10tjjjvbn1fcu.cloudfront.net/out/v1/902c1a0395264f269f1160efa00660e4/index.m3u8

> tvperu.gob.pe/internacional/play

https://dy8y8vcruqztn.cloudfront.net/out/v1/ee2450c81e554f4cae0e6292106993c2/index.m3u8

> canalipe.tv/streaming

https://d16467quqotqb8.cloudfront.net/out/v1/3f2cb1658d114f2693eff18d83199e67/index.m3u8

**Comment by malvinas2** [comment]
Reading the addresses from Cloudfront was the first thing I did. But as written in my first post, these change from time to time.
In a rough draft I'm trying to read the address of `iblups.com`. After `https://regex101.com`, `<url>` should be assigned the correct URL, e.g. https://d6vls0u25arys.cloudfront.net/out/v1/777b4d4cc0984575a7d14f6ee57dbcaf/index.m3u8. 
But for some reason this doesn't work. 
Any ideas why not?


`streamlink http://iblups.com/e_tvperu72 --http-no-ssl-verify`


```
"""
$description iblups.com
$url iblups.com
$type live
$region various
"""

import logging
import re
import time

from streamlink.plugin import Plugin, pluginmatcher
from streamlink.plugin.api import validate
from streamlink.stream.hls import HLSStream
from streamlink.utils.url import update_qsd


log = logging.getLogger(__name__)


@pluginmatcher(re.compile(r"""
    https?://(?:www\.)?
    (
        iblups\.com
    )
""", re.VERBOSE))
class TVPeru(Plugin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._page = None

    @property
    def page(self):
        print("page-function")
        if self._page is None:
            self._page = self.session.http.get(self.url, schema=validate.Schema(
                validate.parse_html(),
            ))
        print("page-function_ENDE")
        return self._page


    def _get_live_url(self):
        print("get_live_url-function")
        schema = validate.Schema(
            validate.xml_xpath_string(".//script[contains(text(), 'LIVE_URL')]/text()"),
            validate.none_or_all(
                re.compile(r"""const source\s*=\s*(?P<q>['"])(?P<url>.+?)(?P=q)"""),
                validate.none_or_all(
                    validate.get("url"),
                    validate.url(),
                ),
            ),
        )
        #print(url)
        #print(live_url)
        live_url = schema.validate(self.page)
        log.debug(f"live_url={live_url}")
        print(live_url)
        print("get_live_url-function-ENDE")
        return live_url


    def _get_streams(self):
        print("get-streams")
        live_url = self._get_live_url()
        if not live_url:
            log.info("This stream may be off-air or not available in your country")
            print("get-streams-ENDE1")
            return

        print("get-streams-ENDE2")
        return HLSStream.parse_variant_playlist(self.session, live_url)

__plugin__ = TVPeru
```
