### ISSUE TITLE
Unexpected FFmpeg version output while running ['/usr/bin/ffmpeg', '-version']

### ISSUE THREAD

**Issue by WuvorWenda** [streamlink/streamlink#5461]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

FFmpeg binary not validated.
Streamlink version 6.0.0.0 Linux Appimage x86_64
Got this error message:

[stream.ffmpegmux][error] Could not validate FFmpeg!
[stream.ffmpegmux][error] Unexpected FFmpeg version output while running ['/usr/bin/ffmpeg', '-version']
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!

ffmpeg output:
ffmpeg -version
ffmpeg version 6.0-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)

ffmpeg is in /usr/bin

### Debug log

```text
[utils.l10n][debug] Language code: en_US
[stream.ffmpegmux][error] Could not validate FFmpeg!
[stream.ffmpegmux][error] Unexpected FFmpeg version output while running ['/usr/bin/ffmpeg', '-version']
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!
[cli][info] Available streams: 234p_alt (worst), 234p, 360p_alt2, 360p_alt, 360p, 540p, 720p_alt, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 22258880; Last Sequence: 22259722
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 22259720; End Sequence: None
[stream.hls][debug] Adding segment 22259720 to queue
[stream.hls][debug] Adding segment 22259721 to queue
[stream.hls][debug] Adding segment 22259722 to queue
[stream.hls][debug] Writing segment 22259720 to output
[stream.hls][debug] Segment 22259720 complete
```

**Comment by WuvorWenda** [comment]
`[cli][debug] OS:         Linux-3.10.0-1062.4.1.el7.x86_64-x86_64-with-glibc2.17
[cli][debug] Python:     3.11.4
[cli][debug] Streamlink: 6.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.3
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=XXX
[cli][debug]  --loglevel=debug
[cli][debug]  --player=hidconwaitmpv.exe
[cli][debug]  --player-no-close=True
[cli][debug]  --output=/dev/null
[cli][debug]  --default-stream=['720p', 'best', 'vod']
[cli][debug]  --ringbuffer-size=33554432
[cli][debug]  --stream-segment-attempts=4
[cli][debug]  --stream-segment-timeout=30.0
[cli][debug]  --stream-timeout=60.0
[cli][debug]  --hls-playlist-reload-attempts=4
[cli][debug]  --hls-playlist-reload-time=segment
[cli][debug]  --ffmpeg-ffmpeg=/usr/bin/ffmpeg
[cli][debug]  --http-header=[('User-Agent', '"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.66"'), ('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; rv:114.0) Gecko/20100101 Firefox/114.0')]
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-disable-hosting=True
[cli][info] Found matching plugin hls for URL XXX
[plugins.hls][debug] URL=private
[utils.l10n][debug] Language code: en_US
[stream.ffmpegmux][error] Could not validate FFmpeg!
[stream.ffmpegmux][error] Unexpected FFmpeg version output while running ['/usr/bin/ffmpeg', '-version']
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!
[cli][info] Available streams: 234p_alt (worst), 234p, 360p_alt2, 360p_alt, 360p, 540p, 720p_alt, 720p, 1080p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Writing output to
/dev/null
[cli][debug] Checking file output
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 4946541; Last Sequence: 4947172
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 4947170; End Sequence: None
[stream.hls][debug] Adding segment 4947170 to queue
[stream.hls][debug] Adding segment 4947171 to queue
[stream.hls][debug] Adding segment 4947172 to queue
[stream.hls][debug] Writing segment 4947170 to output
[stream.hls][debug] Segment 4947170 complete
[stream.hls][debug] Writing segment 4947171 to output
[stream.hls][debug] Segment 4947171 complete
[stream.hls][debug] Writing segment 4947172 to output
[stream.hls][debug] Segment 4947172 complete
[cli][debug] Writing stream to output
[download] Written 1.36 MiB to /dev/null (4s @ 303.87 KiB/s)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 4947173 to queue
[stream.hls][debug] Writing segment 4947173 to output
[stream.hls][debug] Segment 4947173 complete
[download] Written 1.83 MiB to /dev/null (6s @ 292.90 KiB/s)
^C
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
Interrupted! Exiting...
[cli][info] Closing currently open stream...`

this is de info Url is a paid service with my personal info...

**Comment by bastimeyer** [comment]
This looks like an issue with your ffmpeg binary and not with Streamlink. As I've shown in the link above, Streamlink reads the first line of the stdout stream and tries to match it with the version string regex, which is `^ffmpeg version (\S+)`. In order for the ffmpeg binary to be considered valid, it must exit with status code 0 and the version string must have matched.

Post the full stdout and stderr output when running ffmpeg (using the absolute path)
```bash
/usr/bin/ffmpeg -version
```
and post its status/exit code
```bash
echo $?
```

----

There's also `--ffmpeg-no-validation` for skipping the validation step:
https://streamlink.github.io/cli.html#cmdoption-ffmpeg-no-validation

**Comment by WuvorWenda** [comment]
/usr/bin/ffmpeg -version
ffmpeg version 5.1.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2022 the FFmpeg developers

#echo $?
0
i tried --ffmpeg-no-validation and its now working.

Thank you for the help.

**Comment by bastimeyer** [comment]
> /usr/bin/ffmpeg -version
> ffmpeg version 5.1.1-static [johnvansickle.com/ffmpeg](https://johnvansickle.com/ffmpeg/) Copyright (c) 2000-2022 the FFmpeg developers

There is no way that `-version` doesn't also output the ffmpeg build options. You're either leaving this out, or something else is going on here. I have checked the 5.1.1 build and 6.0 build from that site in my docker container and both behave as I'm expecting.

Please check the FFmpeg builds from here as well, because `--ffmpeg-no-validation` is not a solution:
https://github.com/BtbN/FFmpeg-Builds

----

It's possible that there is an async issue with the spawned child process in python where it processes the termination task first before processing the stdout task, hence why it doesn't validate an exit code of 0. If your ffmpeg binary only spits out one line, then this could explain the async timing issue.
https://github.com/streamlink/streamlink/blob/6.0.0/src/streamlink/utils/processoutput.py#L32

I will have a look at rewriting the `ProcessOutput` class using `trio` at some point though because the code would be much cleaner. This could fix a potential issue like this.

**Comment by WuvorWenda** [comment]
> Please check the FFmpeg builds from here as well, because `--ffmpeg-no-validation` is not a solution: https://github.com/BtbN/FFmpeg-Builds

I have checked the ffmpeg build.
I think my VPS is to old.
On my other local  (@ home) linux system it works fine. No --ffmpeg-no-validation. That system is newer. Unfortunately i  can at the moment not upgrade my VPS.
The nightly ffmpeg build works also fine on my local system.
Thank you.

**Comment by campones** [comment]
i have met this issue too , don't ask me what static build I was using  I don't remember.

**Comment by bastimeyer** [comment]
> It's possible that there is an async issue with the spawned child process in python where it processes the termination task first before processing the stdout task, hence why it doesn't validate an exit code of 0. If your ffmpeg binary only spits out one line, then this could explain the async timing issue.

Please have a look at #5480 and build streamlink from the branch of that pull request (and unset `--ffmpeg-no-validation`)
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback
