### ISSUE TITLE
Beyond Live if Possible

### ISSUE THREAD

**Issue by srinac** [streamlink/streamlink#5462]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

What is it? https://beyondlive.com/
How would you expect it to work? Record Live streams
What value does it bring to Streamlink? Another variety to record if can't use another platform (such as Abema, personally)
Does it fit into the scope and aims of the project? Unsure what the scope and project aim.

Is it possible to add this?

I don't use github, other than a higher image res search so I don't really have a full understanding of github. I am trying to find a recording software I can use instead OBS since that blurs my screen recordings (even with one of the highest quality recording option given in OBS).

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/issues/new/choose

**Comment by srinac** [comment]
This wasn't posted in the wrong section was it?
It says not planned, will it be possible to add it in the future?
What requirements doesn't this meet? What would there have to be to make it meet the requirements?
