### ISSUE TITLE
AttributeError: 'Streamlink' object has no attribute 'set_plugin_option'

### ISSUE THREAD

**Issue by horsaen** [streamlink/streamlink#5468]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

hello !! while trying to write something which allows for logging in on afreeca's plugin, i receive an 'AttributeError: 'Streamlink' object has no attribute 'set_plugin_option'' error, with the following code:

```python
    session = streamlink.Streamlink()
    session.set_option("stream-segment-threads", 10)
    session.set_plugin_option("afreeca", "username", user)
    session.set_plugin_option("afreeca", "password", password)
```

which is odd as in other issues it was said to use that for logins, it also worked a few days ago, any ideas ? thanks :))

### Debug log

```text
Traceback (most recent call last):
  File "/ssd/Code/downloader/main.py", line 101, in <module>
    downloadStream(username, streamUrl, qualityName, user, password)
  File "/ssd/Code/downloader/main.py", line 31, in downloadStream
    session.set_plugin_option("afreeca", "username", user)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Streamlink' object has no attribute 'set_plugin_option'
```

**Comment by bastimeyer** [comment]
`Streamlink.{g,s}et_plugin_option()` got removed in 6.0.0. You'll have to set plugin options on the respective `plugin.options` instance instead.
https://streamlink.github.io/api/plugin.html#streamlink.plugin.Plugin.options

Looks like I forgot to include it in the changelog, damn...
https://streamlink.github.io/changelog.html#streamlink-6-0-0-2023-07-20

See #5033

**Comment by horsaen** [comment]
ohhh i see !! however i'm not entirely sure i understand how to migrate the code :(

what would it look like in v6 ? :O

**Comment by bastimeyer** [comment]
The docs will be updated accordingly, but what you're looking for is this

```py
session = streamlink.session.Streamlink()
pluginname, pluginclass, resolved_url = session.resolve_url(url)

# either like this
options = streamlink.options.Options()
options.set("key", "value")
plugin = pluginclass(session, resolved_url, options)

# or like that (plugin constructor won't receive the pre-initialized options)
plugin = pluginclass(session, resolved_url)
plugin.options.set("key", "value")
```

Example:
https://github.com/streamlink/streamlink/blob/6.0.0/src/streamlink_cli/main.py#L533-L535

----

The [`Streamlink.streams()`](https://github.com/streamlink/streamlink/blob/6.0.0/src/streamlink/session.py#L606-L619) method also needs to be updated, so that an options instance can be passed to the plugin constructor. Little oversight here. :disappointed:

**Comment by horsaen** [comment]
i did my best, but i'm not quite sure i follow, here's what i used

```python
    session = streamlink.session.Streamlink()
    pluginname, pluginclass, resolved_url = session.resolve_url(streamUrl)

    options = streamlink.options.Options()
    options.set("stream-segment-threads", 10)
    options.set("username", user)
    options.set("password", password)
    plugin = pluginclass(streamlink, resolved_url, options)

    streams = session.streams(streamUrl)
    stream = streams[qualityName]
```

returns this:

```
File "/ssd/Code/downloader/main.py", line 36, in downloadStream
    plugin = pluginclass(streamlink, resolved_url, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/streamlink/plugins/afreeca.py", line 87, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/streamlink/plugin/plugin.py", line 286, in __init__
    self.load_cookies()
  File "/usr/lib/python3.11/site-packages/streamlink/plugin/plugin.py", line 545, in load_cookies
    self.session.http.cookies.set_cookie(cookie)
    ^^^^^^^^^^^^^^^^^
AttributeError: module 'streamlink' has no attribute 'http'
```

fairly certain this isn't how it should go as 'plugin' isn't even used, any ideas ? :)

**Comment by bastimeyer** [comment]
> AttributeError: module 'streamlink' has no attribute 'http'

You are confusing the `Streamlink` session object with the `streamlink` package name. Read the API docs and/or take a look at the source code, this isn't difficult. I can't help you with your confusion.
https://streamlink.github.io/api.html

**Comment by vstavrinov** [comment]
@bastimeyer :
> 
> ```python
> 
> # either like this
> options = streamlink.options.Options()
> options.set("key", "value")
> plugin = pluginclass(session, resolved_url, options)
> 
> # or like that (plugin constructor won't receive the pre-initialized options)
> plugin = pluginclass(session, resolved_url)
> plugin.options.set("key", "value")
> ```
Please, give a more detailed explanation of use cases for both variants. Which of them is more appropriate in which cases. In particular, could we consider the first variant  as universal, i.e. applicable in all cases?
