### ISSUE TITLE
plugins.pluto: No playable streams found on this URL

### ISSUE THREAD

**Issue by klack** [streamlink/streamlink#5475]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Unable to open any streams on Pluto

### Debug log

```text
streamlink --loglevel=debug "https://pluto.tv/en/live-tv/5a4d3a00ad95e4718ae8d8db" best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.4
[cli][debug] Streamlink: 6.0.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=https://pluto.tv/en/live-tv/5a4d3a00ad95e4718ae8d8db
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin pluto for URL https://pluto.tv/en/live-tv/5a4d3a00ad95e4718ae8d8db
[plugins.pluto][debug] slug=5a4d3a00ad95e4718ae8d8db
[plugins.pluto][debug] app_version=7.4.2-50c72df610dfe1b89e4c5110547c8da17584191d
error: No playable streams found on this URL: https://pluto.tv/en/live-tv/5a4d3a00ad95e4718ae8d8db
```

**Comment by DeltaEpsilon19498** [comment]
This has been happening to me this entire year. I have been getting around it by using the old pluto tv urls with streamlink, which still work for now. For example, https://pluto.tv/en/live-tv/5a4d3a00ad95e4718ae8d8db corresponds to https://pluto.tv/en/live-tv/pluto-tv-comedy . If you use https://pluto.tv/en/live-tv/pluto-tv-comedy instead, the plugin does work.

However, this issue has lasted for a long time, and I am afraid that the old links like pluto-tv-comedy could be deprecated at some point in favor of 5a4d3a00ad95e4718ae8d8db . At that point, streamlink would not work at all. Therefore, I support fixing this plugin to accommodate these newer channel links. If I knew how to code, I would do it myself.

**Comment by bracarino** [comment]
I have this issue for the last 3 days, using the URL with channel name.

Strealink does not even arrive in the error that didn't find no playable streams for me. It get stuck in app_version line.

**Debug Log:**

`streamlink --loglevel=debug https://www.pluto.tv/en/live-tv/smithsonian-channel
[cli][debug] OS:         Linux-5.15.0-78-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 6.0.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.pluto.tv/en/live-tv/smithsonian-channel
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin pluto for URL https://www.pluto.tv/en/live-tv/smithsonian-channel
[plugins.pluto][debug] slug=smithsonian-channel
[plugins.pluto][debug] app_version=7.4.2-50c72df610dfe1b89e4c5110547c8da17584191d`

**Comment by DeltaEpsilon19498** [comment]
> I have this issue for the last 3 days, using the URL with channel name.
> 
> Strealink does not even arrive in the error that didn't find no playable streams for me. It get stuck in app_version line.
> 
> **Debug Log:**
> 
> ```
> streamlink --loglevel=debug https://www.pluto.tv/en/live-tv/smithsonian-channel
> [cli][debug] OS:         Linux-5.15.0-78-generic-x86_64-with-glibc2.29
> [cli][debug] Python:     3.8.10
> [cli][debug] Streamlink: 6.0.1
> [cli][debug] Dependencies:
> [cli][debug]  certifi: 2023.7.22
> [cli][debug]  isodate: 0.6.1
> [cli][debug]  lxml: 4.9.3
> [cli][debug]  pycountry: 22.3.5
> [cli][debug]  pycryptodome: 3.18.0
> [cli][debug]  PySocks: 1.7.1
> [cli][debug]  requests: 2.31.0
> [cli][debug]  trio: 0.22.2
> [cli][debug]  trio-websocket: 0.10.3
> [cli][debug]  typing-extensions: 4.7.1
> [cli][debug]  urllib3: 2.0.4
> [cli][debug]  websocket-client: 1.6.1
> [cli][debug] Arguments:
> [cli][debug]  url=https://www.pluto.tv/en/live-tv/smithsonian-channel
> [cli][debug]  --loglevel=debug
> [cli][info] Found matching plugin pluto for URL https://www.pluto.tv/en/live-tv/smithsonian-channel
> [plugins.pluto][debug] slug=smithsonian-channel
> [plugins.pluto][debug] app_version=7.4.2-50c72df610dfe1b89e4c5110547c8da17584191d
> ```

try "streamlink https://pluto.tv/en/live-tv/smithsonian-channel-selects" instead

**Comment by bastimeyer** [comment]
Please check #5910 and see if there are any channels which aren't working
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback
