### ISSUE TITLE
stream.hls: Could the "No new segments in playlist" judgment be longer or customizable?

### ISSUE THREAD

**Issue by DCxDESIGN** [streamlink/streamlink#5476]
### Checklist

- [X] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

The SHOWROOM plugin in Streamlink seems to have been updated from 6.0.0 and a new feature has been introduced: to check if the segments in the playlist are exhausted or not to determine to stop streaming. Like this:

```
[download] Written 272.81 MiB to [Filename].ts (29m39s @ 145.41 KiB/s)
[stream.hls][debug] Writing segment 896 to output
[stream.hls][debug] Segment 896 complete
[download] Written 273.10 MiB to [Filename].ts (29m41s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m42s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m43s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m44s @ 129.23 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m45s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m46s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m47s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m47s @ 99.49 KiB/s)
[stream.hls][warning] No new segments in playlist for more than 8.00s. Stopping...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread

[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

As far as I have observed, the time above (8.00s) is not a fixed number, it could be 6/8/10s in other runs. And I have two questions:

1. I didn't see any instruction to let users to configure the time value, so could it be able to customize? I'd be very grateful if you could make this possible in further updates.

2. If you don't have the plan to make it open to customization, could you please make it a bit longer? One minute might be better for SHOWROOM, because it is not rare that SHOWROOM broadcasters happen to have network problems, which will make a short period of stop in updating playlist. And the current time can easily cause Streamlink to stop recording before the stream restarts.

### Debug log

```text
...
[download] Written 272.81 MiB to [Filename].ts (29m39s @ 145.41 KiB/s)
[stream.hls][debug] Writing segment 896 to output
[stream.hls][debug] Segment 896 complete
[download] Written 273.10 MiB to [Filename].ts (29m41s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m42s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m43s @ 143.74 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m44s @ 129.23 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m45s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m46s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m47s @ 114.84 KiB/s)
[stream.hls][debug] Reloading playlist
[download] Written 273.10 MiB to [Filename].ts (29m47s @ 99.49 KiB/s)
[stream.hls][warning] No new segments in playlist for more than 8.00s. Stopping...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread

[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
As you can see in the [6.0.0 changelog](https://github.com/streamlink/streamlink/releases/tag/6.0.0), this behavior was added in #5367, and it stops the streams if no new segment was queued for a while. The intention here is to stop early when the `EXT-X-ENDLIST` tag is missing, meaning the server didn't announce the end of the stream properly. In this case, Streamlink would need to wait until the stream's read-timeout gets triggered.

The max time of missing segments depends on the playlist's targetduration. Streamlink waits for at most twice this duration for new segments to be queued while polling the playlist.

We can make it customizable though.

**Comment by sbernsteinWurl** [comment]
+1 for this change request to make the timeout customizable/able to be overriden.  This issue bit me 4x already when watching live youtube streams that had some latency.

**Comment by bastimeyer** [comment]
This has nothing to do with latency. If you're having issues with your own connection to the server, then `--stream-timeout` is what you're looking for. The segment-queuing in regards to the playlist's targetduration is only relevant when the server doesn't queue new segments and thus violates the HLS protocol. This can happen when the stream ingestion from the streamer/broadcaster is unstable and the server doesn't push any filler segments

**Comment by Lytexx** [comment]
> This can happen when the stream ingestion from the streamer/broadcaster is unstable

that happens quite often in the streams that i usually watch, i had streamlink quit without the stream actually ending a few times already. an option to disable it or change the time it waits would be appreciated.

**Comment by sbernsteinWurl** [comment]
@bastimeyer I have stream_timeout set to 1200, and have never had a youtube live stream timeout before the upgrade to 6.0

**Comment by sbernsteinWurl** [comment]
And I'm definitely not having connectivity issues with youtube.  My computer has an ethernet connection directly into my FIOS (1G symmetrical) router, and any temporary connection issues would not be present over several days.  Let me see if I can find debug output or not.  If not I will share the next time it happens.

**Comment by sbernsteinWurl** [comment]
(Sadly my debug output is gone as my computer has rebooted for required security updates)

**Comment by bastimeyer** [comment]
This has nothing to do with `--stream-timeout` or any other local connectivity issues. I have already explained that.

Read #5330.

As I've said, I will add an option later to configure the new behavior.

**Comment by sbernsteinWurl** [comment]
Thanks for the pointer to the change.  Yes, that has definitely hit me in a negative way, stopping the stream before the end 4x for me so far on youtube live streams.

**Comment by bastimeyer** [comment]
See #5478.

Feedback appreciated.
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

**Comment by DCxDESIGN** [comment]
Thank you for your great work.

> See #5478.

 I'm a Windows user so... Does this PR mean that it would be available in the next nightly build? Or should I manually download those changed files?

**Comment by koreyoshi95** [comment]
streamlink config add : hls-segment-queue-threshold=0
