### ISSUE TITLE
youtube 60fps is not available

### ISSUE THREAD

**Issue by Brainzyy** [streamlink/streamlink#548]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I was trying out the windows installer (both 0.3.1 and latest) with VLC 3.0. I am trying to play this stream: https://gaming.youtube.com/watch?v=ipO-TDt7bJs . There are 60fps options available but they don't show up with streamlink. I have searched previous issues and I saw that 1080p60 is DASH and not supported yet, but AFAIK the 720p60 option should be available.

### Expected / Actual behavior

The 720p60 option is available.

### Reproduction steps / Stream URLs to test

1. Install streamlink with windows installer.
2. streamlink https://gaming.youtube.com/watch?v=ipO-TDt7bJs

### Environment details (operating system, python version, etc.)

Windows 7 64bit, Python 3.5 (or whatever version is packaged with the windows installer), both latest and 0.3.1.

### Comments, logs, screenshots, etc.

ffmpeg is installed for sure, because I used the windows installer.

**Comment by gravyboat** [comment]
60 FPS on youtube isn't support currently as far as I know because it uses dash (https://github.com/streamlink/streamlink/pull/225#issuecomment-263821938). We've discussed this a few times in the past: https://github.com/streamlink/streamlink/issues/200

**Comment by Brainzyy** [comment]
@gravyboat I know, but I thought that was only 1080p60? and not 720p60 as well?

**Comment by gravyboat** [comment]
No worries, I think it's all 60 fps streams. @beardypig can you confirm?
