### ISSUE TITLE
--player-args shouldn't override player-args in config file

### ISSUE THREAD

**Issue by trunc88** [streamlink/streamlink#5482]
### Checklist

- [X] This is a feature request and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Now that --player doesn't support adding arguments to it, using --player-args on the command line should not override any player-args the user may have set in the config file. For example, I currently have `player=mpv` and `player-args=--profile=low-latency --cache=no` in my streamlink config, and sometimes I want to watch a stream with audio disabled. I can't just use `streamlink -a '--no-audio'`, because that overrides the arguments I have set in the config file. I have to add all the arguments that are set in the config as well.

**Comment by bastimeyer** [comment]
The way you did this with the old implementation was just an unintended side-effect.

We could set the argparse action of `--player-args` to `append`, but I'm not sure if this is ideal, because that would prevent people from actually overriding player args, which IMO is a valid use case. We could also add a dedicated option for appending player args, e.g. `--player-args-append`, but I'm not sure if that makes sense, because we'd overload the CLI with options like this.

Your use case can be achieved by using a secondary config file:
https://streamlink.github.io/cli.html#cmdoption-config

This needs a decision...

**Comment by gravyboat** [comment]
@bastimeyer Definitely not a fan of `--player-args-append`. As you noted it's overloading the CLI with options that could be confusing. I don't think the behavior should append either. I can't think of many utilities or tools I've used where passing an option would add those arguments to existing arguments. Then you can't run one off commands without updating your config file? Pretty annoying. If you're passing an argument you expect the command to only use that argument, nothing more.

**Comment by bastimeyer** [comment]
> If you're passing an argument you expect the command to only use that argument, nothing more.

Exactly this.

Unless there's a convincing argument that can be made in favor of adding another option for appending, I'm going to close this.

**Comment by trunc88** [comment]
In my opinion the best solution would be to leave the `--player` option the way it was. I don't really understand why it was changed or why you think it was an "unintended side effect". With the `--config` option I would need to have extra config files, and type / tab complete the path to them, which I could create aliases for, but then I might as well just use aliases for setting the options as well instead of needing a bunch of extra config files. It seems suboptimal when there was already a way to do it without any of the problems mentioned.

**Comment by bastimeyer** [comment]
> I don't really understand why it was changed

Read this #5305

**Comment by trunc88** [comment]
I read that before I opened this issue. It doesn't make sense to me to remove that ability when you are unwilling to add an option to append arguments to those in the config file, and the alternative solutions are significantly more annoying. Any confusion can be cleared up with good documentation
