### ISSUE TITLE
plugins.twitch: Stream falling behind, constant buffering after 5 to 10 minutes of playback

### ISSUE THREAD

**Issue by amakea** [streamlink/streamlink#5483]
### Checklist

- [x] This is a plugin issue and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

Twitch plugin began acting unusual this evening. A stream will play fine for about 5 to 10 minutes, then after that time it seems to "catch up" and begins to buffer almost constantly. No issues when playing the stream in a web browser. I played a Trovo stream through streamlink and that worked fine as well.

### Debug log

```text
streamlink https://twitch.tv/awesomestreamer best --loglevel=debug 
[cli][debug] OS:         Linux-6.1.39-3-lts-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.3
[cli][debug] Streamlink: 6.0.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.2
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.6.1
[cli][debug] Arguments:
[cli][debug]  url=https://twitch.tv/awesomestreamer
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --twitch-api-header=[('Authorization', 'OAuth [redacted]')]
[cli][info] Found matching plugin twitch for URL https://twitch.tv/awesomestreamer
[plugins.twitch][debug] Getting live HLS streams for awesomestreamer
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 432p (best)
[cli][info] Opening stream: 432p (hls)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 0; Last Sequence: 3
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1; End Sequence: None
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Writing segment 1 to output
[stream.hls][debug] Segment 1 complete
[cli.output][debug] Opening subprocess: ['/usr/bin/mpv', '--force-media-title=https://twitch.tv/awesomestreamer', '-']
[stream.hls][debug] Writing segment 2 to output
[stream.hls][debug] Segment 2 complete
[stream.hls][debug] Writing segment 3 to output
[stream.hls][debug] Segment 3 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Writing segment 4 to output
[stream.hls][debug] Segment 4 complete
[stream.hls][debug] Writing segment 5 to output
[stream.hls][debug] Segment 5 complete
[stream.hls][debug] Writing segment 6 to output
[stream.hls][debug] Segment 6 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Writing segment 7 to output
[stream.hls][debug] Segment 7 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Writing segment 8 to output
[stream.hls][debug] Segment 8 complete
[stream.hls][warning] Encountered a stream discontinuity. This is unsupported and will result in incoherent output data.
[stream.hls][debug] Writing segment 9 to output
[stream.hls][debug] Segment 9 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Writing segment 10 to output
[stream.hls][debug] Segment 10 complete
[stream.hls][debug] Writing segment 11 to output
[stream.hls][debug] Segment 11 complete
...
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 297 to queue
[stream.hls][debug] Adding segment 298 to queue
[stream.hls][debug] Adding segment 299 to queue
[stream.hls][debug] Writing segment 297 to output
[stream.hls][debug] Segment 297 complete
[stream.hls][debug] Writing segment 298 to output
[stream.hls][debug] Segment 298 complete
[stream.hls][debug] Writing segment 299 to output
[stream.hls][debug] Segment 299 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
What you have posted is way too vague. That could've been caused by literally any kind of issue, e.g. a local connection issue, a connection issue between the streamer and Twitch, your player recovering from a stream discontinuity (ad break), your player actin weird otherwise, or something else.

This is not actionable and I also don't see any issues with the HLS playlist and the Twitch plugin implementation. Streams are working fine. Otherwise, we'd see lots of other people reporting the same.

Going to close... If you can **reliably / deterministically** reproduce this, then reopen and post a log file using `--loglevel=all --logfile=...`.

Remember that playback issues in your video player are entirely unrelated to Streamlink. Streamlink's sole purpose is delivering the stream data to the player.

**Comment by tkozybski** [comment]
Enabling "No Player Cache" and disabling Seeking in the player settings fixed it for me. Using VLC also fixes the problem. I also noticed it yesterday.

**Comment by bastimeyer** [comment]
Not a Streamlink issue.

> Linux-6.4.7-arch1-3-x86_64-with-glibc2.38
> '--cache=no' setting prevents the issue from occurring

glibc 2.38 has introduced some changes in `posix_memalign()` which causes issues in mpv's playback cache (and lots of other applications, e.g. ffmpeg).

See

- https://bugs.archlinux.org/task/79300
- https://github.com/mpv-player/mpv/issues/12076#issuecomment-1666892864
- https://sourceware.org/bugzilla/show_bug.cgi?id=30723
- https://sourceware.org/pipermail/libc-alpha/2023-August/150653.html
- https://www.reddit.com/r/archlinux/comments/15jxaop/glibc_238_core_repo_20230802_and_after_as_of/

Use this mpv wrapper script to override glibc's `posix_memalign` with an alternative provided by `jemalloc`

```bash
#!/usr/bin/env bash
export LD_PRELOAD="$(jemalloc-config --libdir)/libjemalloc.so.$(jemalloc-config --revision)"
exec /usr/bin/mpv "$@"
```
