### ISSUE TITLE
Streamlink report error when I use it to generate youtube live m3u8 url

### ISSUE THREAD

**Issue by egg1234** [streamlink/streamlink#5488]
### Checklist

- [X] This is a bug report and not a different kind of issue
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Latest stable release

### Description

I use below command to generate youtube live m3u8 url, and streamlink report error.
~$ streamlink https://www.youtube.com/watch?v=FoBfXvlOR6I best --stream-url

There is no problem when I use yt-dlp to generate same youtube live m3u8 url.
~$ ./yt-dlp_linux -f best -g https://www.youtube.com/watch?v=FoBfXvlOR6I

### Debug log

```text
~$ streamlink https://www.youtube.com/watch?v=FoBfXvlOR6I best --stream-url
error: Unable to open URL: https://youtube.com/get_video_info (410 Client Error: Gone for url: https://www.youtube.com/get_video_info?video_id=FoBfXvlOR6I&el=detailpage)
```

**Comment by bastimeyer** [comment]
> get_video_info

You are using an ancient version of Streamlink.
You've also ignored the plugin issue template, which would've made you aware of this.

https://streamlink.github.io/install.html
