### ISSUE TITLE
filmon.com #EXTM3U error

### ISSUE THREAD

**Issue by Aylon1** [streamlink/streamlink#549]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

When running any filmon.com streaming with quality worst it comes up with the following error: 
Could not open stream: missing #EXTm3u header

### Expected / Actual behavior

stream free video

### Reproduction steps / Stream URLs to test

streamlink http://www.filmon.tv/channel/channel-4 worst

### Environment details (operating system, python version, etc.)
Win 10 pro

...

### Comments, logs, screenshots, etc.

...

**Comment by Ordval** [comment]
Could it be as easy as the advise I got down below this thread: 
 [https://github.com/streamlink/streamlink/pull/508](url)

> The plugin should work correctly in the latest nightly. It Works For Me™ with the latest dev version. Do you have both stable and nightly versions of Streamlink installed? If so, I'd recommend uninstalling both and just installing one - the nightly/latest if you want the latest filmon fixes. (**beardypig**) 

As I had two installed; but my conclusion;

> So to conclude, not only do we need to “close all other applications” but also uninstall.

(before reinstall) didn't get contested.

**Comment by beardypig** [comment]
I am unable to recreate this using `0.3.1` on Windows 10.

**Comment by Aylon1** [comment]
Thanks for the comments and just removed the current installation as well as a previous liverstreamer installation. Reinstalled fresh and works as expected. Superb!
