### ISSUE TITLE
Propose switching to codecov

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#55]
We've been getting a lot of spam recently from coveralls, and it doesn't seem like they plan to resolve the issue (https://github.com/lemurheavy/coveralls-public/issues/491), as such I'm proposing we consider moving to codecov.

**Comment by TheSneakySniper** [comment]
I would very much dislike the idea of moving. Please don't :(

**Comment by cdrage** [comment]
+1 for codecov integration instead of coveralls

**Comment by gravyboat** [comment]
@TheSneakySniper What is your reasoning for not wanting to use codecov instead of overalls? It's just coverage reporting for the tests.

**Comment by TheSneakySniper** [comment]
Oh, I see. Carry on then.. If it will allow more efficient coverage reporting for tests, then why not.

**Comment by gravyboat** [comment]
Resolved in #54
