### ISSUE TITLE
Winget provides old version

### ISSUE THREAD

**Issue by Aspenpaw** [streamlink/streamlink#5505]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

N/A

### Description

When I attempt to install or update Streamlink using wpm, I'm given 5.5.1-1. Checking the [https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/Streamlink/Streamlink](url) repository that wpm feeds from shows that there is no fault with wpm or git, rather the latest version apparently hasn't been submitted to the wpm repo.

### Debug log

```text
N/A
```

**Comment by bastimeyer** [comment]
1. https://github.com/streamlink/streamlink/blob/6.1.0/.github/ISSUE_TEMPLATE/2_bug_report.yml?plain=1#L57
2. https://streamlink.github.io/install.html#package-availability
3. https://github.com/microsoft/winget-pkgs/issues

**Comment by Hope-IT-Works** [comment]
https://github.com/microsoft/winget-pkgs/issues/117883
