### ISSUE TITLE
webRTC support

### ISSUE THREAD

**Issue by Ro-Den** [streamlink/streamlink#5510]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

I understand that it's too much work, but nevertheless
1. Is webRTC support possible and realistic in the near future?
2. Would it require some additional tool like rtmpdump/rtmpsuck?

**Comment by bastimeyer** [comment]
WebRTC is meant for p2p communication. I haven't seen any non-p2p streaming site which implements WebRTC for video(+audio) stream transmission.

Unless this changes in the future, it doesn't make sense for Streamlink to implement WebRTC-based streaming, so I'm going to close this thread.

> 2\. Would it require some additional tool

No, but it would require another tree of Python dependencies
