### ISSUE TITLE
plugins.nicolive: plugin does not support stream metadata

### ISSUE THREAD

**Issue by SecondaryH** [streamlink/streamlink#5515]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

latest

### Description

Current behaviour: Author folder is not created nor is the title grabbed properly. All streams have titles on the site so not sure whats going wrong here.

Current output: -20230825200547.ts (right in the recordings folder, no author folder, no title)

Expected behaviour/output: Create Author folder and filename consisting of title-timestuff.ts

### Debug log

```text
streamlink --output "~/recordings/{author}/{title}-{time:%Y%m%d%H%M%S}.ts" https://live.nicovideo.jp/watch/co1992508 best
```

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/metadata.html

> The availability of each variable depends on the used plugin and whether that plugin supports this kind of metadata. If a variable is unsupported or not available, then its substitution will either be a short placeholder text ([--title](https://streamlink.github.io/cli.html#cmdoption-title)) or an empty string ([--output](https://streamlink.github.io/cli.html#cmdoption-output), [--record](https://streamlink.github.io/cli.html#cmdoption-record), [--record-and-pipe](https://streamlink.github.io/cli.html#cmdoption-record-and-pipe)).

The plugin does not support any metadata:
https://github.com/streamlink/streamlink/blob/6.1.0/src/streamlink/plugins/nicolive.py#L173-L205
