### ISSUE TITLE
streamlink pipe

### ISSUE THREAD

**Issue by paramec** [streamlink/streamlink#552]
Issue :

$ streamlink -O http://www.filmon.com/tv/film-4 high | ffmpeg -re -v quiet -fflags +genpts+igndts -i pipe:0 -bsf h264_mp4toannexb -vcodec libx264 -tune zerolatency -acodec ac3 -f mpegts pipe:1
[cli][info] Found matching plugin filmon for URL http://www.filmon.com/tv/film-4
[cli][info] Available streams: low (worst), high (best)
[cli][info] Opening stream: high (hls-filmon)
[cli][error] Error when writing to output: [Errno 32] Broken pipe
[cli][info] Stream ended
[cli][info] Closing currently open stream...

### Environment details (operating system, python version, etc.)
Arch Linux with the latest kernel 

I used in the past livestreamer and everything was fine. 
Is there a different way how to use ffmpeg with streamlink? Or is it a issue from  program?

**Comment by beardypig** [comment]
`-O` seems to work fine. It might be a problem with `ffmpeg` invocation, I get
```
[AVBSFContext @ 0x7f8fc3700f60] Codec 'ac3' (86019) is not supported by the bitstream filter 'h264_mp4toannexb'. Supported codecs are: h264 (28)
Error initializing bitstream filter: h264_mp4toannexb
```

**Comment by paramec** [comment]
Thank you very much. You are right.
I have to use : -vbsf h264_mp4toannexb. Everythink it's fine now :).
