### ISSUE TITLE
plugins.dailymotion: Add option to pass credentials 

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink#5522]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 5.5.1

### Description

Hello

I have noticed to my own surprise that recently some channels require a login from the user.  here is the output (I know it's not the latest streamlink version but I doubt it matters in this particular case) 

### Debug log

```text
/usr/local/bin/streamlink --loglevel debug https://www.dailymotion.com/video/x2lefik 477p
[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.15.0-79-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] Streamlink: 5.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2019.11.28
[cli][debug]  isodate: 0.6.0
[cli][debug]  lxml: 4.8.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.9.9
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  urllib3: 1.26.13
[cli][debug]  websocket-client: 1.3.2
[cli][debug] Arguments:
[cli][debug]  url=https://www.dailymotion.com/video/x2lefik
[cli][debug]  stream=['477p']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin dailymotion for URL https://www.dailymotion.com/video/x2lefik
[plugins.dailymotion][debug] Found media ID: x2lefik
[plugins.dailymotion][error] Failed to get stream: Contenu privé.
error: No playable streams found on this URL: https://www.dailymotion.com/video/x2lefik
```

**Comment by bastimeyer** [comment]
> Private video
> The publisher has marked this video as private

I'm not familiar with DM, but this looks more like it's inaccessible for everyone, if they use the same terminology as YouTube

**Comment by campones** [comment]
yea, even with an account and french residential ip, it is still private. so..  kinda pointless

**Comment by campones** [comment]
my feeling is that the player is only allowed on their site.   in the old times with rtmpdump and flash you could get around this, but those were old time indeed..
