### ISSUE TITLE
Jordan TV

### ISSUE THREAD

**Issue by andaluspc** [streamlink/streamlink#5523]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

This is official TV of Jordan live broadcast of Jordan official channel. It broadcasts for free. It is owned and maintained ty Jordan TV itself. It broadcasts entertainment and news content.

It must have no regional restrictions and it doesn't need login.

When I use the official channel live stream page with streamlink it says there is no matching plugin.

website with steam:  https://www.jrtv.gov.jo/live-tv/%d8%a7%d9%84%d9%82%d9%86%d8%a7%d8%a9-%d8%a7%d9%84%d8%a3%d9%88%d9%84%d9%89/1

### Input URLs

https://www.jrtv.gov.jo/live-tv/%d8%a7%d9%84%d9%82%d9%86%d8%a7%d8%a9-%d8%a7%d9%84%d8%a3%d9%88%d9%84%d9%89/1

https://www.jrtv.gov.jo/live-tv/%d8%a7%d9%84%d9%82%d9%86%d8%a7%d8%a9-%d8%a7%d9%84%d8%b1%d9%8a%d8%a7%d8%b6%d9%8a%d8%a9/2

**Comment by bastimeyer** [comment]
Static stream URLs, so no plugin is required:
https://streamlink.github.io/cli/protocols.html

- https://jrtv-live.ercdn.net/jordanhd/jordanhd.m3u8
- https://jrtv-live.ercdn.net/jordansporthd/jordansporthd.m3u8

The sports stream returns 401 for me though, probably because it's geo restricted. Same on their site.

**Comment by andaluspc** [comment]
Thanks bastimeyr for your quick response. Now I checked the sports channel and, yes, it doesn't work over proxy. 
Thanks for sharing the doc link which I now correctly undrestand.

A question thought: I am not able to retrieve the URL with streamlink! I used protocol as httpstream, but --stream-url option doesn't seem to retrieve the m3u8 link. would you give me a hint here? have you retrieved the aforementioned m3u8 URLs from streamlink? if yes, then how?

**Comment by bastimeyer** [comment]
> I am not able to retrieve the URL with streamlink

Streamlink can't figure out stream URLs on its own. This is why plugins are needed for specific sites, so input URLs can be translated to actual stream URLs. The purpose of the `--stream-url` CLI argument is to write the resolved stream URL to `stdout` in those cases. If you already have the stream URL, then you don't need this CLI argument.

Technically, a new generic plugin could be added in the future using the newly added webbrowser API (6.0.0 release) which could look for recognizable streaming protocols like HLS or DASH in a specific time frame, but nothing like that is implemented right now.

This means if you want to check whether a site uses static stream URLs (or if you're going to implement a plugin for a site with non-static stream URLs), then you open your web browser's dev tools and look for stream URLs, either in the HTML of the initial HTTP response if it's a simple case like this, or in the network requests being made by your browser during runtime and figure out how the site has made those requests.

> I used protocol as httpstream

The `httpstream://` protocol prefix is for direct media files served via HTTP and has nothing to do with what you've just said.
