### ISSUE TITLE
Anyway to Increase Download speeds of VOD's from CMD?

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink#553]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Hey guys.

I use CMD and the following command to download VODS using livestreamer or streamlink:
```
streamlink openrec.tv/live/kjASDadme40 source -o D:\savedfile.mp4   
```
BUT it downloads way too slow. I have around 150-200Mbps download speed and I normally get around 15-20MBps download per second. However with CMD the speeds fluctuate and it's between 200 kbps - 1MB .   Is there any kind of coding I can add to increase my download speed when downloading vods from openrec.tv?

Many thanks

**Comment by beardypig** [comment]
You can increasing the download threads using [--hls-segment-threads](https://streamlink.github.io/cli.html#cmdoption-hls-segment-threads), eg. `--hls-segment-threads 5`. However, the link you posted is for a live stream, which would only be able to download as fast as it streams it cannot go any faster. 

VOD support actually appears to be broken on openrec.tv, but we'll fix that...

**Comment by beardypig** [comment]
@jstrat231 did you try out my suggestions? VOD has been fixed in the latest dev/nightly version.

**Comment by jstrat231** [comment]
seems much better thank you beardypig

**Comment by beardypig** [comment]
You can add it to your [streamlinkrc](https://streamlink.github.io/cli.html#configuration-file) file. 

```cfg
hls-segment-threads=5
```

**Comment by gravyboat** [comment]
Going to close this since @beardypig has answered the associated questions. Thanks!
