### ISSUE TITLE
Allow setting environment variables when launching the player

### ISSUE THREAD

**Issue by kuon** [streamlink/streamlink#5530]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

There is currently the `--player-arg`  that allows to pass argument to the player.

It would be very handy to have another one, `--player-env` to enable setting environment variables when the player is launched.

I currently have only a single use case:

- I use pipewire, and I want to hint pipewire to connect a specific node, this is done via the `PIPEWIRE_NODE` environment variable.

I can set the environment variable before launching streamlink, but this requires editing all my launchers, instead of setting it in the config file.

**Comment by bastimeyer** [comment]
Child processes inherit the environment of the parent process unless it gets explicitly overridden, which Streamlink does not:
https://github.com/streamlink/streamlink/blob/79b8497add48a7068ece0a0b2bf538db2a7d61aa/src/streamlink_cli/output/player.py#L264-L270

Just set the env var(s) on the streamlink/python process.

**Comment by kuon** [comment]
@bastimeyer Yes I know as I said at the bottom of my initial issue, but the idea was to be able to use streamlink own config file. I guess I can work around by wrapping my launchers.

**Comment by bastimeyer** [comment]
Ah, sorry, apparently I didn't finish reading the whole post :/

A new CLI arg could be added, similar to how `--http-header` works (multiple CLI args with `key=value` values that get appended), but I fear that we'd very likely see requests for adding such args for every other kind of child process Streamlink spawns, not just the player.

IMO, adding specific env vars just for the player is kind of an edge case, so writing a player wrapper script or streamlink wrapper script is probably the better idea.

I can see having a specific CLI arg being useful from the perspective of a config file though.
