### ISSUE TITLE
plugins.nicolive: Add option to record livestreams/vods with comments on screen

### ISSUE THREAD

**Issue by SecondaryH** [streamlink/streamlink#5533]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

(Please add plugin enhancement as label, I couldn't set it on my end.)

One of Nicolive's unique feature is that comments/games are shown on the livestream itself. This results in a more immersive watching experience. 

[Comments example](https://i.imgur.com/vewlINN.png)
[Comments sliding](https://streamable.com/5cqs8f)

These comments are shown on both vods and livestreams.

**Comment by bastimeyer** [comment]
This is not how Streamlink works.

If there's any client-side rendering in the web browser, then this can't be done. The text needs to be part of the actual video stream.

The chat is rendered onto a `canvas` DOM node in your web browser.
