### ISSUE TITLE
0.3.2 Release

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#554]
There have been a couple of bug fixes that would be useful to release, specifically #522 and #543. 

It seems like it's quite straightforward to cut a release now? What do you think @cdrage, @gravyboat ?

**Comment by cdrage** [comment]
@beardypig I agree, release should be a lot more straight-forward this time with the updated script.

**Comment by gravyboat** [comment]
Sounds like a plan to me!

**Comment by cdrage** [comment]
Done! :+1:

**Comment by beardypig** [comment]
Seems like it was pretty smooth getting this done. Excellent :D

**Comment by nxtreaming** [comment]
Good job!
