### ISSUE TITLE
build-and-sign script currently broken

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#5548]
Two issues:

1. Streamlink's version is currently determined by running `python setup.py --version`. This has been deprecated by setuptools a while ago and broke in `68.2.1`. [`68.2.2` has just fixed it](https://setuptools.pypa.io/en/stable/history.html#v68-2-2), but the proper way of getting the version string is by running

    ```sh
    python -m versioningit
    ```

    which is a simple fix.

2. Windows-specific wheels (`streamlinkw` "gui_scripts" entry point) are broken since [`build>=1.0.0` (2023-09-01)](https://pypa-build.readthedocs.io/en/stable/changelog.html#id2)

    The build script still uses the deprecated `--build-option=--plat-name=${platform}` argument which gets passed to setuptools via `build`'s `--config-setting` argument. `--build-option` was a flag for setuptools's deprecated CLI and its `build` command. `--plat-name` sets the platform for the wheel to be built.
    https://setuptools.pypa.io/en/stable/deprecated/distutils/builtdist.html#cross-compiling-on-windows

    With PEP517 / PEP518, this is all a bit different now.

    I'll need to have a deeper look into setuptools's build backend in order to fix this. This may require overriding and subclassing it (according to some comments on their issue tracker), which would be annoying.

    Thinking about downgrading `build` in the CI config in the mean time...

**Comment by gravyboat** [comment]
> Thinking about downgrading build in the CI config in the mean time...

👍 from me on this course of action. No reason to create stress.
