### ISSUE TITLE
A very brief summary of what's broken

### ISSUE THREAD

**Issue by LinuxOpa** [streamlink/streamlink#5554]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.2.0 zip

### Description

virustotal reports virus
![streamlink](https://github.com/streamlink/streamlink/assets/41851582/f3dbf1c8-9e9d-45e1-916b-69bcbaeeeece)
 

### Debug log

```text
virustotal reports virus
```

**Comment by bastimeyer** [comment]
This zip file is generated by GitHub from the tagged commit.

Your "anti virus" snake oil software is showing a false positive.

We can't do anything about that. Closing...
