### ISSUE TITLE
plugins.huya

### ISSUE THREAD

**Issue by unknownUser99999** [streamlink/streamlink#5571]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

[cli][info] Your Streamlink version (6.2.0) is up to date!

### Description

It won't play, or it plays for a while and then backs out in a second

### Debug log

```text
streamlink.exe --player=PotPlayerMini64.exe https://www.huya.com/257085 best --loglevel=debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.0.9 30 May 2023
[cli][debug] Streamlink: 6.2.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.4
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.huya.com/257085
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=PotPlayerMini64.exe
[cli][info] Found matching plugin huya for URL https://www.huya.com/257085
[plugins.huya][debug] QUALITY_WEIGHTS: {'source_al': 15, 'source_tx': 20, 'source_hw': 65}
[cli][info] Available streams: source_al (worst), source_tx, source_hw (best)
[cli][info] Opening stream: source_hw (http)
[cli][info] Starting player: PotPlayerMini64.exe
[cli][debug] Pre-buffering 8192 bytes
[cli.output][debug] Opening subprocess: ['PotPlayerMini64.exe', '-']
[cli][debug] Writing stream to output
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
Not a plugin issue. This site uses progressive HTTP streams instead of using proper streaming procotols like HLS or DASH, and the plugin resolves those stream URLs correctly compared to what their website is doing. See the `--stream-url` CLI argument.

The streams I've tested were all working fine for several minutes until I decided to stop watching. Make sure that your connection to their servers is stable and that your player doesn't stop when there's a lag spike due to buffering, etc. The debug log you've posted doesn't tell anything useful of what actually happened.

Going to close this one until it can be deterministically shown that there's indeed a plugin issue here.

**Comment by unknownUser99999** [comment]
> 不是插件问题。 该网站使用渐进式 HTTP 流，而不是使用 HLS 或 DASH 等适当的流协议，并且与网站正在执行的操作相比，该插件可以正确解析这些流 URL。 请参阅 `--stream-url`CLI 参数。
> 
> 我测试过的流媒体在几分钟内都工作正常，直到我决定停止观看。 确保您与服务器的连接稳定，并且当由于缓冲等原因出现延迟峰值时，您的播放器不会停止。您发布的调试日志不会告诉您实际发生的情况。
> 
> 将关闭此问题，直到可以确定地表明此处确实存在插件问题。

streamlink https://www.huya.com/majiajia  best  --stream-url
Can this fetch the stream address, but I feel like the address I'm getting is incomplete, I'm getting https://hw.flv.huya.com/src/813535483-813535483-3494108293620563968-1627194422-10057-A-0-1- imgplus.flv?wsSecret=ff994a9bd70ffc890d001098180767d3&wsTime=65192cbc&fm=RFdxOEJjSjNoNkRKdDZUWV8kMF8kMV8kMl8kMw%3D%3D&ctype=huya_ live&fs=bgct&sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&sphdDC=huya&sphd=264_*-265_*&exsphd=264_500,264_2000,264_4000,264_10000, but I feel like the comma There should be something after it, for example, I used other tools to get http://al.flv.huya.com/src/813535483-813535483-3494108293620563968-1627194422-10057-A-0-1-imgplus.flv?& sphdcdn=al_7-tx_3-js_3-ws_7-bd_2-hw_2&uid=1466370364591&uuid=2448879941&wsTime=651a7dcc&ctype=tars_mobile&exsphd=264_500,264_2000, 264_4000,264_10000,&sphdDC=huya&fs=bgct&sphd=264_*-265_*&seqid=1697614917443591&t=103&sv=2110211124&wsSecret= e8666cc51633392951eabb732e6db527&ver=1


Translated with www.DeepL.com/Translator (free version)

**Comment by bastimeyer** [comment]
> do you have parameters to select different cdn

The plugin returns streams for each available CDN. Just don't use `best`.

```
streamlink https://www.huya.com/majiajia
[cli][info] Found matching plugin huya for URL https://www.huya.com/majiajia
Available streams: source_tx (worst), source_hs, source_al, source_hy, source_hw (best)
```
