### ISSUE TITLE
Add Ability to have youtube livestream act as a video file not url so that its compatible with video file only players

### ISSUE THREAD

**Issue by Pickymarker** [streamlink/streamlink#5572]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Add Ability to have youtube livestream act as a video file not url so that its compatible with video file only players

**Comment by bastimeyer** [comment]
- https://streamlink.github.io/cli.html#player-options
- https://streamlink.github.io/cli.html#file-output-options

Stream data is fed to the player either via

- the stdin pipe (default behavior)
- a named pipe (`--player-fifo`)
- a locally spawned HTTP server where the player will read from (`--player-http` / `--player-http-continuous`)
- a locally spawned HTTP server where an external player can read from (`--player-external-http`)
- the passed-through stream URL, which bypassed Streamlink's stream implementations and lets the player do the work instead (`--player-passthrough=...`)

Alternatively, you can make Streamlink write the stream data to

- stdout and pipe it into a different process directly (`--stdout`)
- the filesystem or any other resource and optionally make the player read it on-the-fly (`--output` / `--record` / `--record-and-pipe`)
