### ISSUE TITLE
plugins.youtube: Cannot check age restricted streams even with provided cookie - LOGIN_REQUIRED

### ISSUE THREAD

**Issue by cnekmp** [streamlink/streamlink#5573]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.0

### Description

Recently I've spotted that I cannot check streams that are age restricted. Providing debug log (cookies data has been edited)

### Debug log

```text
$ streamlink --loglevel all --config cookies.txt https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live

[14:22:11.990552][cli][debug] OS:         Linux-6.5.5-arch1-1-x86_64-with-glibc2.38
[14:22:11.990645][cli][debug] Python:     3.11.5
[14:22:11.990694][cli][debug] OpenSSL:    OpenSSL 3.1.3 19 Sep 2023
[14:22:11.990738][cli][debug] Streamlink: 6.2.0
[14:22:11.991118][cli][debug] Dependencies:
[14:22:11.994843][cli][debug]  certifi: 2023.7.22
[14:22:11.995179][cli][debug]  isodate: 0.6.1
[14:22:11.995463][cli][debug]  lxml: 4.9.2
[14:22:11.995913][cli][debug]  pycountry: 22.3.5
[14:22:11.996161][cli][debug]  pycryptodome: 3.14.1
[14:22:11.996490][cli][debug]  PySocks: 1.7.1
[14:22:11.996789][cli][debug]  requests: 2.26.0
[14:22:11.997055][cli][debug]  trio: 0.22.2
[14:22:11.997311][cli][debug]  trio-websocket: 0.10.4
[14:22:11.997548][cli][debug]  typing-extensions: 4.8.0
[14:22:11.998420][cli][debug]  urllib3: 1.26.15
[14:22:11.998717][cli][debug]  websocket-client: 1.6.3
[14:22:11.998814][cli][debug] Arguments:
[14:22:11.998858][cli][debug]  url=https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[14:22:11.998908][cli][debug]  --config=['cookies.txt']
[14:22:11.998954][cli][debug]  --loglevel=all
[14:22:11.999018][cli][debug]  --http-cookie=[('LOGIN_INFO', 'AFmmF2swRAIgWstWw3qI-ohVEEhHMpvctVF9b1QpSm5qM1dYWEdWTUc0TWlZTThBbU9YbkxSSEtnZUJkQ1NRpS0ZR'), ('VISITOR_INFO1_LIVE', 'h28AAAAAOaro'), ('VISITOR_PRIVACY_METADATA', 'CgJBWhICGgA%3D'), ('__Secure-1PSID', 'bggxxZM-Qp2hz7gE9tpFS3AsSLPM-Iw.'), ('__Secure-3PSID', 'bggxxZbZ2ZX0cHM-Qp2hz7gEWfQbiA.'), ('HSID', 'ARX6PvcjX6HXzNthy'), ('SSID', 'Al58xoxGgsRHFVp4C'), ('APISID', 'ML1TLIttVcHeZ-yALcVglz'), ('SAPISID', 'CYkNkaoXbt8C1uwB/AUSmAE'), ('__Secure-1PAPISID', 'CYkNkaoXbt8C1uwB/AihSmAE'), ('__Secure-3PAPISID', 'CYkNkaoXhSmAE'), ('__Secure-1PSIDTS', 'sidts-CjIB3e41hQxY5F5oeE_SMc0hAXFJnhAA'), ('SIDCC', 'ACA-OxP7826RhwI78QLhtsksdWq6H4FAM1I3'), ('__Secure-1PSIDCC', 'ACA-OxMCdB2zLfAFv2-8_Wd5eoeVFl-qzcdno1noo'), ('__Secure-3PSIDCC', 'ACA-OxN_I_wP4QbNDVxnAQfSo15z12Q')]
[14:22:11.999260][cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[14:22:12.884943][plugins.youtube][error] Could not get video info - LOGIN_REQUIRED: Sign in to confirm your age
error: No playable streams found on this URL: https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
```

**Comment by bastimeyer** [comment]
Can't confirm this. The video plays fine when all the required cookies are set. Just copy **everything** from your browser session.

My Chromium session sends these headers on `https://www.youtube.com/`

```
VISITOR_INFO1_LIVE
CONSENT
LOGIN_INFO
HSID
SSID
APISID
SAPISID
__Secure-1PAPISID
__Secure-3PAPISID
PREF
VISITOR_PRIVACY_METADATA
SID
__Secure-1PSID
__Secure-3PSID
__Secure-1PSIDTS
__Secure-3PSIDTS
SIDCC
__Secure-1PSIDCC
__Secure-3PSIDCC
```

```
$ streamlink \
  --config cookies.txt \
  -l debug \
  -p mpv \
  'https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live' \
  best
[cli][debug] OS:         Linux-6.5.5-1-git-dirty-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.1.3 19 Sep 2023
[cli][debug] Streamlink: 6.2.0+11.gaa08d5a1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.4
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.0.5
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[cli][debug]  stream=['best']
[cli][debug]  --config=['cookies.txt']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --http-cookie=[('VISITOR_INFO1_LIVE', '...'), ('CONSENT', '...'), ('LOGIN_INFO', '...'), ('HSID', '...'), ('SSID', '...'), ('APISID', '...'), ('SAPISID', '...'), ('__Secure-1PAPISID', '...'), ('__Secure-3PAPISID', '...'), ('PREF', '...'), ('VISITOR_PRIVACY_METADATA', '...'), ('SID', '...'), ('__Secure-1PSID', '...'), ('__Secure-3PSID', '...'), ('__Secure-1PSIDTS', '...'), ('__Secure-3PSIDTS', '...'), ('SIDCC', '...'), ('__Secure-1PSIDCC', '...'), ('__Secure-3PSIDCC', '...')]
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[plugins.youtube][debug] Using video ID: lr_4xN_nyAQ
[plugins.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: mpv
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 9810; Last Sequence: 9825
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 9823; End Sequence: None
[stream.hls][debug] Adding segment 9823 to queue
[stream.hls][debug] Adding segment 9824 to queue
[stream.hls][debug] Adding segment 9825 to queue
[stream.hls][debug] Writing segment 9823 to output
[stream.hls][debug] Segment 9823 complete
```

**Comment by cnekmp** [comment]
> Can't confirm this. The video plays fine when all the required cookies are set. Just copy **everything** from your browser session.
> 
> My Chromium session sends these headers on `https://www.youtube.com/`
> 
> ```
> VISITOR_INFO1_LIVE
> CONSENT
> LOGIN_INFO
> HSID
> SSID
> APISID
> SAPISID
> __Secure-1PAPISID
> __Secure-3PAPISID
> PREF
> VISITOR_PRIVACY_METADATA
> SID
> __Secure-1PSID
> __Secure-3PSID
> __Secure-1PSIDTS
> __Secure-3PSIDTS
> SIDCC
> __Secure-1PSIDCC
> __Secure-3PSIDCC
> ```
> 
> ```
> $ streamlink \
>   --config cookies.txt \
>   -l debug \
>   -p mpv \
>   'https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live' \
>   best
> [cli][debug] OS:         Linux-6.5.5-1-git-dirty-x86_64-with-glibc2.38
> [cli][debug] Python:     3.11.5
> [cli][debug] OpenSSL:    OpenSSL 3.1.3 19 Sep 2023
> [cli][debug] Streamlink: 6.2.0+11.gaa08d5a1
> [cli][debug] Dependencies:
> [cli][debug]  certifi: 2023.7.22
> [cli][debug]  isodate: 0.6.1
> [cli][debug]  lxml: 4.9.3
> [cli][debug]  pycountry: 22.3.5
> [cli][debug]  pycryptodome: 3.19.0
> [cli][debug]  PySocks: 1.7.1
> [cli][debug]  requests: 2.31.0
> [cli][debug]  trio: 0.22.2
> [cli][debug]  trio-websocket: 0.10.4
> [cli][debug]  typing-extensions: 4.8.0
> [cli][debug]  urllib3: 2.0.5
> [cli][debug]  websocket-client: 1.6.3
> [cli][debug] Arguments:
> [cli][debug]  url=https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
> [cli][debug]  stream=['best']
> [cli][debug]  --config=['cookies.txt']
> [cli][debug]  --loglevel=debug
> [cli][debug]  --player=mpv
> [cli][debug]  --http-cookie=[('VISITOR_INFO1_LIVE', '...'), ('CONSENT', '...'), ('LOGIN_INFO', '...'), ('HSID', '...'), ('SSID', '...'), ('APISID', '...'), ('SAPISID', '...'), ('__Secure-1PAPISID', '...'), ('__Secure-3PAPISID', '...'), ('PREF', '...'), ('VISITOR_PRIVACY_METADATA', '...'), ('SID', '...'), ('__Secure-1PSID', '...'), ('__Secure-3PSID', '...'), ('__Secure-1PSIDTS', '...'), ('__Secure-3PSIDTS', '...'), ('SIDCC', '...'), ('__Secure-1PSIDCC', '...'), ('__Secure-3PSIDCC', '...')]
> [cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
> [plugins.youtube][debug] Using video ID: lr_4xN_nyAQ
> [plugins.youtube][debug] This video is live.
> [utils.l10n][debug] Language code: en_US
> [cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p (best)
> [cli][info] Opening stream: 720p (hls)
> [cli][info] Starting player: mpv
> [stream.hls][debug] Reloading playlist
> [cli][debug] Pre-buffering 8192 bytes
> [stream.hls][debug] First Sequence: 9810; Last Sequence: 9825
> [stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 9823; End Sequence: None
> [stream.hls][debug] Adding segment 9823 to queue
> [stream.hls][debug] Adding segment 9824 to queue
> [stream.hls][debug] Adding segment 9825 to queue
> [stream.hls][debug] Writing segment 9823 to output
> [stream.hls][debug] Segment 9823 complete
> ```

Can you give me an advice how to import these cookies in a fast way? Copy-paste from Dev mode is too much time consuming. Saving cookies as a Netscape format means that you need manually edit file. Any faster options so I could migrate them in a format that streamlink accept?

**Comment by bastimeyer** [comment]
You can try the following JS snippet, but this will only return a subset of the cookies actually sent. No idea if this will work.

```js
document.cookie.split("; ").reduce((a,i)=>(a.push(`http-header=${i}`),a),[]).join("\n")
```

**Comment by cnekmp** [comment]
> You can try the following JS snippet, but this will only return a subset of the cookies actually sent. No idea if this will work.
> 
> ```js
> document.cookie.split("; ").reduce((a,i)=>(a.push(`http-header=${i}`),a),[]).join("\n")
> ```

Seems I've found the issue. Previously I've been using only `__Secure-1PSID` cookie value and it was working without issues. Now YouTube requires (?) that all other cookies has been set also. I've set them all and it worked. Regarding JS snippet, it didn't export all values so I've found an easier method.

I've downloaded cookies via "Cookie Quick Manager" (Firefox extension) in a Netscape format and then I've run this command:
`awk '{ print "http-cookie="$6"="$7 }' output.txt > cookie.txt`

Just posted if anyone will need it in a future

Thanks for the support

**Comment by cnekmp** [comment]
@bastimeyer could you please check once more, seems YouTube has set cookie expiration? It works with the same cookies for 5 minutes, then I get the same

`[cli][debug] OS:         Linux-6.5.5-arch1-1-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.1.3 19 Sep 2023
[cli][debug] Streamlink: 6.2.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.14.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.26.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.4
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 1.26.15
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[cli][debug]  --config=['cook.txt']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live
[plugins.youtube][error] Could not get video info - LOGIN_REQUIRED: Sign in to confirm your age
error: No playable streams found on this URL: https://www.youtube.com/channel/UCs7ywlQh-NbzvefX87FGQAw/live`

**Comment by cnekmp** [comment]
YouTube constantly updates following cookies: 
__Secure-1PSIDCC
__Secure-3PSIDCC
SIDCC
