### ISSUE TITLE
Twitch error

### ISSUE THREAD

**Issue by Smalceson** [streamlink/streamlink#558]
```
 [cli][info] Found matching plugin twitch for URL http://twitch.tv/######
[plugin.twitch][info] Attempting to authenticate using OAuth token
error: Unable to open URL: https://api.twitch.tv/kraken/user.json (401 Client Error: Unauthorized for url: https://api.twitch.tv/kraken/user.json?oauth_token=############################=t)
```

Someone have a similar problem?

I have oauth token in my streamlinkrc `twitch-oauth-token=#########################`

**Comment by beardypig** [comment]
Are you using a livestreamer token or did you generate the token recently? Are you using the latest version of streamlink? 

You can try generating a new oauth token using [--twitch-oauth-authenticate](https://streamlink.github.io/cli.html#authenticating-with-twitch). 
```
streamlink --twitch-oauth-authenticate
```

**Comment by Smalceson** [comment]
With `twitch-oauth-authenticate` finally work. Thanks for help.
