### ISSUE TITLE
"Could not open stream: Unable to find rtmpdump.exe"

### ISSUE THREAD

**Issue by fishscene** [streamlink/streamlink#56]
On Windows in CMD, Ran:
pip install streamlink
Then attempted to join a beam.pro stream and got the following error:
[cli][error] Could not open stream: Unable to find rtmpdump.exe command

Copied livestreamer file and renamed it to: %AppData%\streamlink\streamlinkrc
I believe the _actual_ fix is 1 line: rtmpdump=C:\Program Files (x86)\Livestreamer\rtmpdump\rtmpdump.exe
This fixed the issue. 

Is there a way to generate this file automatically? It wasn't present with a fresh install.
Reference: https://github.com/chrippa/livestreamer/issues/228

**Comment by Brainzyy** [comment]
+1 rtmpdump should be added to the PATH by the streamlink installer.

**Comment by sbstp** [comment]
When installing the package via pip, it doesn't go through the installer I'm working on. We need to add rtmpdump to setup.py.

**Comment by seagull** [comment]
I'm getting this error using the 0.0.2 installer.

**Comment by gravyboat** [comment]
This has been fixed in a couple of ways since the issue was created so I'm going to close this, should be addressed once we push out 0.0.3. If not open it back up.
