### ISSUE TITLE
plugins.twitch: is_bad_bot=true in headless mode (forced integrity-token acquirement)

### ISSUE THREAD

**Issue by altansnl** [streamlink/streamlink#5600]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

in the latest version client integrity token fetching is disabled, this is a specific version.

### Description

i have a specific version of streamlink that tries to fetch integrity tokens regardless. same exact commands used to work, now suddenly i am getting bad integrity tokens. 

i am guessing they might have changed something in their protocol so that the current solution (https://github.com/streamlink/streamlink/issues/5380) might not work when enabled.

### Debug log

```text
streamlink --loglevel=debug https://www.twitch.tv/thebausffs best    
[cli][debug] OS:         macOS 12.4
[cli][debug] Python:     3.10.5
[cli][debug] OpenSSL:    OpenSSL 1.1.1n  15 Mar 2022
[cli][debug] Streamlink: 0.0.0+unknown
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.9.14
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.28.1
[cli][debug]  trio: 0.22.0
[cli][debug]  trio-websocket: 0.10.2
[cli][debug]  typing-extensions: 4.3.0
[cli][debug]  urllib3: 1.26.12
[cli][debug]  websocket-client: 1.4.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.twitch.tv/thebausffs
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/thebausffs
[plugins.twitch][debug] Getting live HLS streams for thebausffs
[plugins.twitch][info] Acquiring new client-integrity token...
[webbrowser.webbrowser][info] Launching web browser: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[webbrowser.webbrowser][debug] Waiting for web browser process to terminate
[plugins.twitch][debug] Client-Integrity token: {"client_id":"<redacted>","client_ip":"<redacted>","device_id":"<redacted>","exp":"2023-10-10T00:56:42Z","iat":"2023-10-09T08:56:42Z","is_bad_bot":"true","iss":"Twitch Client Integrity","nbf":"2023-10-09T08:56:42Z","user_id":""}
[plugins.twitch][info] Is bad bot? True
[plugins.twitch][warning] No client-integrity token acquired
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: en_US
error: No playable streams found on this URL: https://www.twitch.tv/thebausffs
```

**Comment by Hakkin** [comment]
Kasada has seemingly started detecting Chrome's new headless mode, it was previously undetected. Visiting Twitch directly in headless mode also results in a bad bot token, so it doesn't have anything to do with streamlink's implementation.
Acquiring a token still works with `--webbrowser-headless false`.

**Comment by altansnl** [comment]
alright, did not know i had headless true by default. yeah only headless seems to be detected 👍 following worked:
```
streamlink --loglevel=debug --webbrowser-headless false https://www.twitch.tv/thebausffs best
```
