### ISSUE TITLE
plugins.ntv:  it have dead today 

### ISSUE THREAD

**Issue by vstavrinov** [streamlink/streamlink#5602]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.1+23.ga39816fb

### Description

Yet yesterday it was working but now it has reached its end of life due to site changing. Fortunately, it works with static URL:

`http://cdn.ntv.ru/ntv-msk_hd/index.m3u8`

I have constructed this URL from very similar URLs taken from under the hood of the site.

So, we have 3 options:

1. Remove the plugin.
2. Mark it as broken.
3. Incorporate this static URL into plugin code as what to be  returned.

I guess all of those decisions would be temporary.

### Debug log

```text
streamlink --loglevel=debug http://www.ntv.ru/air/
[cli][debug] OS:         Linux-6.5.0-2-amd64-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.2.1+23.ga39816fb
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.16.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 1.26.17
[cli][debug]  websocket-client: 1.2.3
[cli][debug] Arguments:
[cli][debug]  url=http://www.ntv.ru/air/
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --player-args=--quiet
[cli][debug]  --default-stream=['best']
[cli][info] Found matching plugin ntv for URL http://www.ntv.ru/air/
error: No playable streams found on this URL: http://www.ntv.ru/air/
```

**Comment by bastimeyer** [comment]
> a39816fb

This is not a valid hash on Streamlink's master branch. Forks are not supported here.

**Comment by vstavrinov** [comment]
This issue is not about the fork. But OK, to satisfy Your pedantry take a look at the same result with upstream branch:

```
streamlink --loglevel=debug http://www.ntv.ru/air/
[cli][debug] OS:         Linux-6.5.0-2-amd64-x86_64-with-glibc2.37
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.2.1+23.g0490c4ef
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.16.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 1.26.17
[cli][debug]  websocket-client: 1.2.3
[cli][debug] Arguments:
[cli][debug]  url=http://www.ntv.ru/air/
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][debug]  --player-args=--quiet
[cli][debug]  --default-stream=['best']
[cli][info] Found matching plugin ntv for URL http://www.ntv.ru/air/
error: No playable streams found on this URL: http://www.ntv.ru/air/

```
And it's interesting, why have you chosen the first option of all three available.

**Comment by bastimeyer** [comment]
I know it's not about your fork, otherwise I wouldn't have checked the site and already opened a PR for the plugin removal.
The reason why I am being pedantic is that forks can completely alter the code base, and nobody here wants to deal with random side effects, hence the explicit version string requirement, because it wastes everyone's time.

Broken plugins get removed if a fix is impossible or not necessary. In this case it's not necessary, because the site uses static stream URLs. This is surely not the first time we've done that. If you want to complain, then implement a plugin fix in your fork.

**Comment by vstavrinov** [comment]
Besides, at some moment static  link could become dynamic and in this case the plugin could be adjusted accordingly rather than add new one.
