### ISSUE TITLE
Username and Password proxy support

### ISSUE THREAD

**Issue by keharv** [streamlink/streamlink#5609]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Can you add support for proxies that have a username and password? I attempted this syntax, and it was not able to route the connection https://username:proxy@ip:8080

Thank you.

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/proxy.html
`--http-proxy "scheme://user:pass@address:port"`

This is handled by `requests`, not Streamlink.
https://requests.readthedocs.io/en/latest/user/advanced/#proxies
