### ISSUE TITLE
plugins.plugin-name-here: A very brief summary of what's broken

### ISSUE THREAD

**Issue by ROBGagn** [streamlink/streamlink#5627]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

Mitele plugin not working anymore

### Description

None of the Mitele channel work since today.

### Debug log

```text
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.5
[cli][debug] OpenSSL:    OpenSSL 3.0.9 30 May 2023
[cli][debug] Streamlink: 6.2.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.0.6
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.mitele.es/directo/cuatro/
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --locale=es_ES
[cli][debug]  --player-external-http=True
[cli][debug]  --player-external-http-port=304
[cli][debug]  --hls-audio-select=['*']
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --ffmpeg-copyts=True
[cli][debug]  --http-proxy=http://AsTJems3WD4V4HgrSTWWkJm9:ROBgagn2021@es-mad.pvdata.host:8080/
[cli][debug]  --http-header=[('Referer', 'https://www.mitele.es/directo/cuatro/'), ('Origin', 'https://www.mitele.es'), ('User-Agent', 'Mozilla/5.0'), ('X-Forwarded-For', '213.0.87.10')]
[cli][info] Found matching plugin mitele for URL https://www.mitele.es/directo/cuatro/
[plugins.mitele][error] Could not get stream tokens: 4034 (unknown error)
error: No playable streams found on this URL: https://www.mitele.es/directo/cuatro/
```

**Comment by bastimeyer** [comment]
> - [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

> [cli][debug] Streamlink: 6.2.1

This was fixed yesterday already:
- #5624
- e2ebaa1202c187beaca83468230e477b1b03ac45
