### ISSUE TITLE
plugins.dlive: no longer works

### ISSUE THREAD

**Issue by seba11** [streamlink/streamlink#5628]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.2.1

### Description

DLive plugin is no longer works. The stream is correctly found but dlive make a some security changes and the video always looks like this:
![image](https://github.com/streamlink/streamlink/assets/7965273/f23947de-95bf-4d50-8062-ad6788c3cd1d)

### Debug log

```text
.\streamlink.exe https://dlive.tv/NPTVPL best
[cli][info] Found matching plugin dlive for URL https://dlive.tv/NPTVPL
[cli][info] Available streams: 360p (worst), 480p, 720p, src (best), 1080p
[cli][info] Opening stream: src (hls)
[cli][info] Starting player: D:\Programy na SSD\VLC\vlc.exe
[stream.hls][error] Failed to fetch segment 79790: Unable to open URL: https://videos.prd.dlivecdn.com/dlive/0000079790.ts (403 Client Error: Forbidden for url: https://videos.prd.dlivecdn.com/dlive/0000079790.ts)
[stream.hls][error] Failed to fetch segment 79791: Unable to open URL: https://videos.prd.dlivecdn.com/dlive/0000079791.ts (403 Client Error: Forbidden for url: https://videos.prd.dlivecdn.com/dlive/0000079791.ts)
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by bastimeyer** [comment]
> * [x]  [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22+sort%3Aupdated-desc)
> * [x]  [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

This has already been fixed on the master branch
- #5622
- #5623
