### ISSUE TITLE
Localization tests fail

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#567]
### Checklist

- [x] This is a bug report.

### Environment details (operating system, python version, etc.)

Archlinux, python-3.6, streamlink latest git

### Comments, logs, screenshots, etc.
http://pastebin.com/hEdvRRxJ

**Comment by beardypig** [comment]
Are you running this via some kind of build script? Can you link to it, or post it in a gist? The tests actually require that you have `pycountry` installed as well.

**Comment by mmetak** [comment]
Standard build `makepkg -s` in archlinux. I maintain both streamlink packages in AUR and I've update the latest to `0.3.2` which builds fine and this test fail appears later when testing latest git. I already added `python-pycountry` to `checkdepends` as soon as it was merged. ;-)

[Here is also a build log in my repo.](https://build.opensuse.org/build/home:metakcahura/Arch_Extra/x86_64/streamlink-git/_log)

**Comment by beardypig** [comment]
I take it that means you don't have the `iso639` and `iso3166` packages? They are also required for the tests...

**Comment by mmetak** [comment]
I've added `python-iso639` and `python-iso3166` as dependencies, made new packages for them as they weren't packaged in aur and I've also added `python-pycountry` to `checkdepends` in pkgbuild file. Long story short, they're all in there. ;-)

**Comment by gravyboat** [comment]
Awesome @mmetak, thanks so much!

**Comment by beardypig** [comment]
@mmetak If you'd rather not have those 2 extra packages I can make it skip the tests depending on which packages are available. Would be cleaner for the arch package without the extra deps, I guess?

**Comment by beardypig** [comment]
Does it still not build with the iso modules installed? If not I have updated the tests in a PR so they get skipped if those modules are not there. 

Did you get the right iso639 module? It's actually `iso-639` in PyPi... Confusing I know.

**Comment by mmetak** [comment]
@beardypig Those two extra packages are not a problem at all especially for `-git` package I maintain. You write tests and it would be a waste if I didn't enable them to check for issues and report them. ;-) So, I'll leave them all for both sets of tests.

It appears your merged tests work and there's no error now. If I try to build it  without `python-pycountry` it just skips those tests.

**Comment by beardypig** [comment]
OK cool. The tests before assumed that you always have `iso639/3166` available. Which gives misleading errors if you don't, because the `Localization` falls back to `pycountry`, I've fixed this now in that PR.

**Comment by beardypig** [comment]
@mmetak can you share the link to the latest build log?

**Comment by bastimeyer** [comment]
@mmetak 
You have set `python-pycountry` in the PKGBUILD's [`checkdepends`](https://wiki.archlinux.org/index.php/PKGBUILD#checkdepends), which requires the user to install this package for building `streamlink-git`, unless the check hook is not being run by the user's AUR helper. This means that the tests are always being run with `python-pycountry` installed and the package turns into an orphan after that.

@beardypig 
There is no link to *the* latest build log, since it's an AUR package. I can post you mine, if you want:
https://gist.github.com/bastimeyer/b4d863b2d0ccf081927bcbbf3051798a

**Comment by beardypig** [comment]
Thanks @bastimeyer, last time @mmetak posted an opensuse build link, I was wondering if there was an updated build on opensuse build services. 

So all 3 packages are included, either pycountry or the iso639/3166 packages are redundant (as @bastimeyer pointed out).

**Comment by mmetak** [comment]
@beardypig @bastimeyer 
The link above is the [same](https://build.opensuse.org/public/build/home:metakcahura/Arch_Extra/x86_64/streamlink-git/_log), but it builds streamlink almost daily in clean environment. You can check which packages are installed in there as well.

`python-iso3166` and  `python-iso639` are also runtime dependencies beside the localization tests, streamlink won't run without them. `python-pycountry` is only needed for tests and is removed after the package is built. Maybe I wasn't clear enough.

So, yes, all 3 packages present at build time and after that `python-pycountry` is removed since it was only installed for tests. Users who don't want to install this package can skip the check part (tests), but they'll still need those zwo iso python packages to actually run streamlink.

**Comment by beardypig** [comment]
OK. I'm not super familiar with AUR packages - it's been a few years since I used Arch. To clarify about which modules are required; Streamlink will run with either `pycountry` or `iso639, iso3166`, as will the tests now. If you install it vian`pip` then `iso639, iso3166` is preferred :-)

**Comment by mmetak** [comment]
@beardypig are you sure it's either? If I remove `iso639, iso3166` python packages and have only `pycountry` it fails to start?

```
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'iso3166' distribution was not found and is required by streamlink
```

**Comment by beardypig** [comment]
Ah, it's installed with setuptools/pip then? Yeah, pkg_resources will enforce that requirement.

**Comment by beardypig** [comment]
@mmetak would you prefer to use `pycountry` instead of the combination of `iso639` and `iso3166`. It would be very simple to conditionally set which modules are required based on an environment variable. eg. `env STREAMLINK_USE_PYCOUNTRY=1 pip install streamlink` could set the `pycountry` module in the `requires` instead of `iso639` and `iso3166`.

**Comment by mmetak** [comment]
@beardypig I think that would be a good idea from a maintainers pov.
Most distros already have `pycountry` packaged in their main repositories and it would make it easier for them to keep streamlink up to date.

**Comment by beardypig** [comment]
That's what I was thinking too. The big decision is what the environment variable should be...?
`USE_PYCOUNTRY` or `STREAMLINK_USE_PYCOUNTRY` or other? There is already a `NO_DEPS` variable left over from the `livestreamer` days.

**Comment by Techwolf** [comment]
I left a comment on #585 and found this one later. Even when I built with pycountry, I still get a run time error of missing iso3166. The distro I am using supplies only pycountry, not iso3166 nor iso639.
