### ISSUE TITLE
plugins.bilibili: Some live streams cannot be obtained

### ISSUE THREAD

**Issue by hack11112** [streamlink/streamlink#5692]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.4.1

### Description

Some live broadcast browsers on station B can be watched, but cannot be obtained using streamlink. Some even have a black screen when viewed through browsers. I guess it may be a CDN problem.

### Debug log

```text
streamlink https://live.bilibili.com/24022841 best --loglevel=debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.4.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.1
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.8.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.6.4
[cli][debug] Arguments:
[cli][debug]  url=https://live.bilibili.com/24022841
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/24022841
error: Unable to validate JSON: ValidationError(dict):
  Unable to validate value of key 'data'
  Context(AnySchema):
    ValidationError(equality):
      <{'current_quality': 0, 'accept_quality': None, 'current...> does not equal None
    ValidationError(dict):
      Key 'durl' not found in <{'current_quality': 0, 'accept_quality': None, 'current...>
```

**Comment by bastimeyer** [comment]
The plugin requires a full rewrite...

The stream URLs are now embedded as JSON on the live URL itself. I have already a working re-implementation of the plugin in my local git repo. However, they only appear to have low-quality streams for regular users. The streamer's input stream and re-encoded high-quality streams all require a login, and creating a new account requires a phone number or some Chinese social media accounts, so this is a dead end for me.
