### ISSUE TITLE
remove dependency of python-librtmp for some streams (ustream, etc.)

### ISSUE THREAD

**Issue by gverm** [streamlink/streamlink#57]
Streams like ustream depend on it for desktop streams, but the install package for it is broken. I tried to install it using pip (2.7) and pip3, but both encountered an error.

**Comment by TheSneakySniper** [comment]
I agree with this

**Comment by beardypig** [comment]
@Brainzyy do you mean `python-librtmp`? 
Which error do you get? 
I was able to install fine using pip2.7 on a both a Debian7 box and macOS box.

**Comment by Brainzyy** [comment]
@beardypig Yes, I meant that. The weird thing is, it worked now for me too. But last time it didn't work, weird.

**Comment by Brainzyy** [comment]
This is the error I get on windows using pip 8.1.2 (python 3.5.2): http://imgur.com/a/QKFDH

**Comment by beardypig** [comment]
OK. `python-librtmp` uses some C extensions that need to be compiled, for them to be compiled you need the correct version of MSVC++ and the `librtmp` libraries - which is kind of a pain in the butt. 
For Python2.7, Python3.3 and Python3.4 there are wheels on PyPi that include the compiled binaries for `python-librtmp`, so I think it would work (I have no way to test it) if you could use Python 2.7, 3.3 or 3.4. If not, you gotta compile it. 
`python-librtmp` is also maintained by @chrippa and it doesn't look like it has been updated for over a year, so it seems unlikely that a Windows wheel version will get built for Python 3.5. 

From what I can see, only the ustream plugin uses the `librtmp` package for desktop streams which are broken (see #58) at the moment anyway. Someone will need to fix the ustream plugin to see if librtmp can be replaced with something that everyone can install.

**Comment by Brainzyy** [comment]
Ah, I see, maybe rtmpdump.exe can be used?

Op 7-okt.-2016 18:41 schreef "Beardypig" <notifications@github.com>:

**Comment by TheSneakySniper** [comment]
We might have to rewrite the ustream plugin...

**Comment by xkbd** [comment]
It may be useful:
I make wheels for cp35, cp36 (win32): https://github.com/xkbd/python-librtmp/tree/master/wheels
