### ISSUE TITLE
How i can extract audio stream from video streaming???

### ISSUE THREAD

**Issue by Dizzman** [streamlink/streamlink#571]
I need  get http streaming (localhost:port/name.mp3) from some video streaming
How i can do this?

**Comment by bastimeyer** [comment]
> How i can extract audio stream from video streaming

You can do this by using the `-O` streamlink parameter and piping the data into ffmpeg and extracting/encoding (any of the) the audio channels of the video stream. Here's a simple example:

```
streamlink -O STREAM best | ffmpeg -i pipe:0 -c:v none -c:a libmp3lame -b:a 320k -joint_stereo 0 -y -format mp3 "$(date +"recording_%Y%m%d%H%M%S.mp3")"
```

I'm not sure what you mean with http streaming and "localhost:port/name.mp3", though. Do you mean as a stream input or output? If you want to output the mp3 on a local http server, then you should be fine with the example above, which writes the mp3 file to your filesystem and a local http server can simply read from it. If the data should not be written to the file system, then it's a bit more complicated and you probably need to write a script (python, nodejs, etc.) that launches a http server, runs the (modified) command above, reads from ffmpeg's stdout and serves the data to all connections of the server.

**Comment by Dizzman** [comment]
thank you for answer
I need analyze of audio stream from TV streaming.
task is extraction audio and analyze it in online not from dowloaded audio file.
Not necessarily only from port
![default](https://cloud.githubusercontent.com/assets/25510074/22857837/a832c040-f0be-11e6-9a5c-0413d1f4eae4.png)

**Comment by beardypig** [comment]
@Dizzman this doesn't really seem to be streamlink related? @bastimeyer gave you a good answer for extracting an audio stream on-the-fly using streamlink and ffmpeg.

**Comment by gravyboat** [comment]
Yep I'm going to close this for now since it's getting outside of the realm of Streamlink. Thanks for your detailed answer @bastimeyer.
