### ISSUE TITLE
python3-trio-websocket: Package pythons-trio-websocket is not available

### ISSUE THREAD

**Issue by max11** [streamlink/streamlink#5717]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

5.1.2

### Description

I'm trying to update version 5.1.2 to 6.4.2 via Debian backports and I'm having a problem with the python3-trio-websocket plugin missing:
Package python3-trio-websocket is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source.
How can I update?

### Debug log

```text
some packages could not be installed this may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
following packages have unmet dependencies: python3-streamlink: depends: python3-trio-websocket but it is not installable
```

**Comment by bastimeyer** [comment]
Follow the instructions here:
https://streamlink.github.io/install.html#linux-and-bsd
