### ISSUE TITLE
cli: please remove deprecated warning messages

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#573]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Since livestreamer 1.11.0 was released, deprecated warning have been added to following switches : 

```
Deprecated the --http-cookies option.
Deprecated the --http-headers option.
Deprecated the --http-query-params option.
```
Fortunatelly those switches haven't been removed. But sometimes they don't allow to use full features that's why switches which allow repeating functions have also been added. 

### Expected / Actual behavior

Switches above are very useful because they allow to add several informations on one line using only one switch and features are separated by ";"
For instance : 

```
streamlink --http-headers "User-Agent=android;X-Forwarded-For=0.0.0.0;Cookies=4545s4fsfsf4s;X-Requested-With=;Referer=;X-Do-Not-Track=" 
streamlink --http-query-params "video_id=100;authority_instance_id=spectar-prd-cgt;token=74n8mnSREdQ4X-anI1rCXw" "hlsvariant://http://
[cli][warning] The option --http-query-params is deprecated since version 1.11.0
, use --http-query-param instead.
```

### Environment details (operating system, python version, etc.)

Python 2.7.13

### Comments, logs, screenshots, etc.

So it will be useful to keep both features as each one provide advantages. They are complementary. 
That's why I would like to ask if you could please remove deprecated warning messages because I hope they are not intended to be removed.

**Comment by beardypig** [comment]
Having two command line arguments that do the same thing is generally not a good idea. I would say that `http-header` is superior to `http-headers`. With `http-header` you can specify multiple Headers in different places, for example in `streamlinkrc` and in the command line, with those on the command line taking precedence over those in the config. `http-headers` will overwrite all of the headers and cannot be combined from the config file. 

You can load configuration options for a file too. For example, for the stream you give in your example you could create `stream.cfg`:
```conf
http-header=User-Agent=android
http-header=X-Forwarded-For=0.0.0.0
http-header=X-Requested-With=
http-header=Referer=
http-header=X-Do-Not-Track=
http-cookie=authToken=4545s4fsfsf4s
http-query-param=video_id=100
http-query-param=authority_instance_id=spectar-prd-cgt
http-query-param=token=74n8mnSREdQ4X-anI1rCXw
```
And then load it on the command line using the `@` syntax (which might not be documented):
```shell
$ streamlink @stream.cfg "hlsvariant://http://test.se/example" 
```
And then, if you wish to override the cookie or one of the query params you can just add those on the command line too:
```shell
$ streamlink @stream.cfg --http-cookie "authToken=aNewToken" --http-query-param "token=otherNewToken" "hlsvariant://http://test.se/example" 
```

Much cleaner, and more manageable I think...

**Comment by karlo2105** [comment]
Hi Beardypig

I use batch file with channels and for instance I put general query on one line as it's used on all channels : 

`set "query_channelname=video_id=95;authority_instance_id=spectar-prd-hrt;token=utS3Py8Fg8B0ZmzTdi6oZg"`

I call it simply by 
`streamlink --http-query-params "%query_channelname%" "hlsvariant://server:port/HLS/channelname"`

 With --http-query-param switch I would be obliged to repeat it for each part of query above as that : 

`streamlink --http-query-param "video_id=95" --http-query-param "authority_instance_id=spectar-prd-hrt"  --http-query-param "token=utS3Py8Fg8B0ZmzTdi6oZg" "hlsvariant://server:port/HLS/channelname"`

As you can see it's much longer with repeatable switch and I can't make one general line by setting full query replaced by %query_channelname%.

Second example : 

`set "headers_test=User-Agent=android;X-Forwarded-For=0.0.0.0;Cookies=4545s4fsfsf4s;X-Requested-With=;Referer=;X-Do-Not-Track="
`

It's much simplier : 
`streamlink --http-headers "%headers_test%" "hlsvariant://server:port/sub/channelname" `

than to repeat it for each part. 

At least please don't remove them those three general commands in future development, because it will be pain in the arse for me. In documentation, you can add examples for general switches I think people will not mixed up it with each others when they see examples. 

Thanks.

**Comment by beardypig** [comment]
I don't seem those options being removed any time soon, but I don't see them been un-deprecated either. 
Surely if it's in a batch script then it doesn't matter if it's longer? Or do you run the batch script, then run the streamlink command? If it's the latter, I'd look at using the `@`syntax to import config files instead.

**Comment by karlo2105** [comment]
I have plenty examples used in my batch file and they take just one line by example, that's why for me general switch is much more interesting otherwise I will be obliged to make small files with headers for every example. 

I made shortcut on desktop to my batch file from where I run streamlink  with all headers and queries required so making for 6 different networks will not be as transparent as it's now.

**Comment by beardypig** [comment]
Could do that... best of both worlds.
