### ISSUE TITLE
 CHZZK, Naver‘s new Korean streaming plateform

### ISSUE THREAD

**Issue by daspryJ** [streamlink/streamlink#5730]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

A new streaming plateform from the Korean company Naver called "[CHZZK](https://chzzk.naver.com/)" is likely to quickly receive traction from Korean streamers that can‘t stay on Twitch.
It‘s still in beta though, so it might change a little, but it would be nice to explore the possibility to have a plugin started for this streaming plateform.

### Input URLs

https://chzzk.naver.com/live/17f0cfcba4ff608de5eabb5110d134d0
https://chzzk.naver.com/live/c68b8ef525fb3d2fa146344d84991753
https://chzzk.naver.com/live/4b2f27574a2e60d15bd53f94cbfc4066

**Comment by daspryJ** [comment]
Thank you @fml09 and @bastimeyer for working on this plugin even though the site is still in beta. 
Originally I wanted to know if there was any major obstacles preventing entirely streamlink to work with CHZZK :
Well, you made a working plugin in a few hours, very impressive!
Of course I understand the need for CHZZK to come out of beta for you to include the plugin to the streamlink stable release, but I just tried to add the chzzk.py plugin of @fml09 branch to my install, and it works great! 
Playing it in my video player is cutting off the stream a little, but still less than on their webplayer. And the .ts file is perfectly fine when I record it. Awesome!

**Comment by bastimeyer** [comment]
Let's keep this thread open until the plugin gets merged.

**Comment by bastimeyer** [comment]
> I just tried to add the chzzk.py plugin to my install

https://streamlink.github.io/cli/plugin-sideloading.html
