### ISSUE TITLE
Updated Twitch Email

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#574]
I've updated the Twitch email account to use a protonmail address (streamlink@protonmail.com). I've sent the creds to @beardypig currently just in case I get hit by a bus, if anyone else would like them please let me know.

**Comment by beardypig** [comment]
Received. Hope you don't get hurt by a bus though...

**Comment by gravyboat** [comment]
I look both ways when I cross the street, just wanted to make sure we were at buss factor +1.

**Comment by fishscene** [comment]
Requesting the credentials for Bus+2.
