### ISSUE TITLE
hakuna.live

### ISSUE THREAD

**Issue by poggieslol** [streamlink/streamlink#5743]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Hakuna is a Korean/Arab streaming platform that some of the korean twitch streamers are moving to. The website is owned by Movefast Company. The website supports livestreaming and "Hits" which are the equivalent to clips or tiktok/shorts. There isn't any region restrictions and the website is also avalaible in english. Some streams are only accessible when logged in but not all of them.

### Input URLs

https://hakuna.live/en/liveroom/139077882
https://hakuna.live/ko/liveroom/139077882
https://hakuna.live/en/liveroom/139082689

**Comment by bastimeyer** [comment]
There's barely any content on that site, and the channels I can see have at most only 8 viewers. It's also very questionable if anything that is shown there is actually real content. The google search results also suggest this.

There is no value in adding a plugin for this site, at least in this current state.

**Comment by chorong761** [comment]
I've seen some bigger korean twitch streamers move to this site, it's probably just at the time when @bastimeyer accessed the site (midnight/morning korean time)?

**Comment by bastimeyer** [comment]
Most popular channel right now has 8 viewers, and there are a ton of fake profiles listed.

**Comment by chorong761** [comment]
> Most popular channel right now has 8 viewers, and there are a ton of fake profiles listed.

Well.....like I just mentioned, it's not a good time tom access the site at. Try accessing the sit during the evening or night (KST)

**Comment by bastimeyer** [comment]
20:40 KST on a Saturday... Top channel: 14 viewers

**Comment by chorong761** [comment]
> 20:40 KST on a Saturday... Top channel: 14 viewers

https://hakuna.live/en/profile/ledx8dx91cg8n22

**Comment by bastimeyer** [comment]
Posting a random channel doesn't change what I've said.

The "most popular" **LIVE** channel right now has 8 viewers, at least when accessing from my German IP address.

On top of that, this site uses WebRTC which Streamlink does not support.
