### ISSUE TITLE
Output error, despite specified output ?

### ISSUE THREAD

**Issue by Dan-Y89** [streamlink/streamlink#5746]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

[cli][info] Your Streamlink version (6.5.0) is up to date!

### Description

Hello, sorry for the disruption just before the New Year. 
I'm only reporting here because everything worked until yesterday and since today I've been having problems.
In general, I have to say that I NEVER change anything because I always use everything via a CMD (.batch).
Only since today I have the mentioned problem and I don't know why? 
Because as I said, I never change anything in the CMD (batch).
I hope someone can help me with this.
Thank you very much
![error](https://github.com/streamlink/streamlink/assets/28935869/bae68d3a-340d-4a6f-8ad1-0c54c7203582)

### Debug log

```text
C:\Windows\system32>streamlink --loglevel=debug  --twitch-disable-ads -o "C:\Users\m-say\Documents\TOOLS\CMD\xREC\boesesjuju.mp4" twitch.tv/boesesjuju best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.7
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.5.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=twitch.tv/boesesjuju
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=C:\Users\m-say\Documents\TOOLS\CMD\xREC\boesesjuju.mp4
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][debug]  --twitch-disable-ads=True
[cli][info] Found matching plugin twitch for URL twitch.tv/boesesjuju
[plugins.twitch][debug] Getting live HLS streams for boesesjuju
[plugins.twitch][debug] {'adblock': False, 'geoblock_reason': '', 'hide_ads': False, 'server_ads': True, 'show_ads': True}
[utils.l10n][debug] Language code: de_DE
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 936p60 (best)
[cli][info] Opening stream: 936p60 (hls)
[cli][info] Writing output to
C:\Users\m-say\Documents\TOOLS\CMD\xREC\boesesjuju.mp4
[cli][debug] Checking file output
[plugins.twitch][info] Will skip ad segments
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] First Sequence: 1359; Last Sequence: 1372
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 1370; End Sequence: None
[stream.hls][debug] Adding segment 1370 to queue
[stream.hls][debug] Adding segment 1371 to queue
[stream.hls][debug] Adding segment 1372 to queue
[stream.hls][debug] Writing segment 1370 to output
[stream.hls][debug] Segment 1370 complete
error: Failed to open output: C:\Users\m-say\Documents\TOOLS\CMD\xREC\boesesjuju.mp4 ([Errno 2] No such file or directory: 'C:\\Users\\m-say\\Documents\\TOOLS\\CMD\\xREC\\boesesjuju.mp4')
[cli][info] Closing currently open stream...
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Writing segment 1371 to output
[stream.hls][debug] Segment 1371 complete

C:\Windows\system32>
```

**Comment by Dan-Y89** [comment]
Microfsoft Defender has recognized python as a "trojan" -.- therefore... WTF. 
You can Delete it. 
Sorry

**Comment by bastimeyer** [comment]
> error: Failed to open output: C:\Users\m-say\Documents\TOOLS\CMD\xREC\boesesjuju.mp4 ([Errno 2] No such file or directory

Same issue as #5727:

Before Streamlink is able to write the output to a file on the filesystem, it first needs to create the file's parent directories. The `Failed to open output` error when opening a file descriptor in (binary-)write mode can only occur if the parent directories do not exist, or if you don't have write permission.

Apparently, there's an issue with that on Windows when using the special directories in the user's home dir, like "Documents", "Pictures", "Videos", etc. The reason for this hasn't been figured out due to lack of feedback from users who are running into this issue. I can't reproduce this in my Windows 10 VM.
