### ISSUE TITLE
How to get it to work ??

### ISSUE THREAD

**Issue by dom39fr** [streamlink/streamlink#575]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Hello, I simply can't get this to work. I have everything required.
Windows 7, Python 3.6 freshly installed (upgraded to see if that was the cause.. obv not)
4.6 .NET, VC++ 2015 redist...
I have shutdown antivirus, firewall, ran as administrator.

What is happening is when I start "Streamlink for Windows.exe" I have that 3 Steps thing popping.
STEP 1 : I can choose whatever flavor, it does the same.  ... doing nothing
STEP 2 : "Start downloading" results in "Loading (1/1) appearing for 1 to 2 seconds", then it comes back to "Start downloading")
STEP 3 : Build release ... Pending ... nothing else, I can click how many times I want it just does nothing.

so, anyone has any idea ? I used Livestreamer without issue and it seems I can't use Streamlink..

### Expected / Actual behavior

I don't know.. something happening maybe ?

**Comment by beardypig** [comment]
This seems to be an issue with `streamlink-portable`, you can post an issue for that on the [streamlink-portable issues page](https://github.com/streamlink/streamlink-portable). 

If you are not set on using a portable version I recommend you use the Windows installer, downloadable from the [releases page](https://github.com/streamlink/streamlink/releases), `streamlink-0.3.2.exe` currently. However, if you want to use a portable version, I provide an alternative [streamlink-portable](https://github.com/beardypig/streamlink-portable) version.

**Comment by dom39fr** [comment]
Thanks for the link, exactly what I needed but https://github.com/streamlink/streamlink "Windows" link only link to a page with that "windows portable" version... I couldn't find the exe you have linked to me, thanks.

**Comment by dom39fr** [comment]
actually, on streamlink page : https://github.com/streamlink/streamlink
we have "Installers for windows" and two links for windows , "Windows" and "Windows Portable", I don't want portable, I click on the first and it sends me to a page with both... "binaries" and "portable" ...I have to figure out (now I understand) that "binaries" is what I need... and in that binaries part I have a link that sends me back to https://github.com/streamlink/streamlink/releases/latest  ....
Totally confusing, putting that link directly in the first place would have been more clear for average users.

**Comment by beardypig** [comment]
On the page linked to by the Windows link it says "You can download the latest stable Windows installer from the [GitHub Releases Page](https://github.com/streamlink/streamlink/releases)"... Which take you back to the Github releases pages, in a bit of a roundabout way...

**Comment by dom39fr** [comment]
Your help solved my problem on getting Streamlink to work, though there's still an issue with that portable version. Thanks beardypig.

**Comment by beardypig** [comment]
No problem. Would you mind posting the issue over on the [streamlink-portable issues page](https://github.com/streamlink/streamlink-portable), so the right people see it?
