### ISSUE TITLE
ard_mediathek plugin fails with 403 error

### ISSUE THREAD

**Issue by moritzheiber** [streamlink/streamlink#576]
### Description

Whenever I try to watch the ARD livestream I can use neither of the available plugins. However, the most promising solutions seems to be the `ard_mediathek` plugin. Unfortunately, I'm getting a `403 Client error` when trying to use it.

### Reproduction steps / Stream URLs to test

```
$ streamlink http://www.ardmediathek.de/tv/Das-Erste/live?kanal=208 best
[cli][info] Found matching plugin ard_mediathek for URL http://www.ardmediathek.de/tv/Das-Erste/live?kanal=208
[plugin.ard_mediathek][error] Failed to extract SMIL streams: Unable to open URL: http://live-lh.daserste.de/z//daserste_de@446299/manifest.f4m?hdcore?hdcore=3.3.0 (403 Client Error: Forbidden for url: http://live-lh.daserste.de/z//daserste_de@446299/manifest.f4m?hdcore?hdcore=3.3.0)
[cli][info] Available streams: auto (worst, best)
[cli][info] Opening stream: auto (http)
[cli][info] Starting player: mpv
[cli][info] Stream ended
[cli][info] Closing currently open stream...
$
```

Opening the URL in any modern browser (Firefox, Chrome et al) works out of the box.

### Environment details (operating system, python version, etc.)

- Ubuntu 16.10
- Streamlink 0.3.2

```
$ cat .config/streamlink/config 
twitch-oauth-token=secret
player=mpv
hls-live-edge=60
hds-live-edge=60
hls-segment-attempts=10
hds-segment-attempts=10
hls-segment-threads=4
hds-segment-threads=4
```

### Comments, logs, screenshots, etc.

Notice how I wouldn't be be able to use the `ard_live` plugin either since its URL schema (`live.daserste.de`) redirects to `http://www.daserste.de/live/index.html`, which the plugin doesn't recognize.

Additionally, the redirection URL (`http://live-lh.daserste.de`) is not covered by any plugin at all yet.

**Comment by beardypig** [comment]
@moritzheiber I have created a PR that should fix this issue: #579
