### ISSUE TITLE
plugins.bigo: Unable to parse JSON

### ISSUE THREAD

**Issue by ashlesss** [streamlink/streamlink#5763]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

root@workspace:~# streamlink --no-config --version-check [cli][info] streamlink is running as root! Be careful! [cli][info] Your Streamlink version (6.5.0) is up to date!

### Description

Hello,

the bigo.py is not working again at the moment.

I know there is a closed issue regarding this problem. Issue #5753

It seems Bigo made some changes on their end which causing this problem.

It is giving a parse JSON error.

Debug log is following...

### Debug log

```text
$ streamlink --loglevel=debug https://www.bigo.tv/954321825

[cli][info] streamlink is running as root! Be careful!
[cli][debug] OS:         Linux-5.4.0-169-generic-x86_64-with-glibc2.29
[cli][debug] Python:     3.8.10
[cli][debug] OpenSSL:    OpenSSL 1.1.1f  31 Mar 2020
[cli][debug] Streamlink: 6.5.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2019.11.28
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.19.1
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.23.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.bigo.tv/954321825
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bigo for URL https://www.bigo.tv/954321825
error: Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html>\n<html lang="en" s ...)
```

**Comment by mkbloke** [comment]
Seems to work fine if you [sideload](https://streamlink.github.io/cli/plugin-sideloading.html#plugin-sideloading) the fixed plugin.

**Comment by ashlesss** [comment]
Ahh, Thanks. That works fine!
