### ISSUE TITLE
Url failover

### ISSUE THREAD

**Issue by syco** [streamlink/streamlink#5775]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Would it be possible to pass multiple urls for failover?
The description for the url parameter says: `A URL to attempt to extract streams from.`
I would like to pass multiple urls, so that if the first one fails, it attempts to extract streams from the second (or third).

**Comment by bastimeyer** [comment]
Make use if the non-zero exit code and loop through the input URLs until the exit code is not zero.
