### ISSUE TITLE
plugins.olympicchannel: Unable to stream Young Olympic Games

### ISSUE THREAD

**Issue by Facy5** [streamlink/streamlink#5796]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.5.1

### Description

The Olympics Channel plugin can't retrive the live from the Young Olympic Games pages, and seems to read the HTML file instead (see log).

Be careful, the lives are online only during sports events (starting at 11.30 P.M. UTC+1) and the stream page changes everyday (see URL given in the log)..
I don't know if it worth to fix it (for only ~2 weeks), or if it can be a base for futher fixes.

### Debug log

```text
streamlink --loglevel=debug https://olympics.com/en/gangwon-2024/video/day-5-winter-youth-olympic-games-gangwon-2024 best
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.1
[cli][debug] OpenSSL:    OpenSSL 3.0.11 19 Sep 2023
[cli][debug] Streamlink: 6.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.1.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://olympics.com/en/gangwon-2024/video/day-5-winter-youth-olympic-games-gangwon-2024
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player-args=--file-caching=5000
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin olympicchannel for URL https://olympics.com/en/gangwon-2024/video/day-5-winter-youth-olympic-games-gangwon-2024
error: Unable to validate response text: ValidationError:
  Unable to parse JSON: Expecting value: line 1 column 1 (char 0) ('<!DOCTYPE html><html lang="en"><he ...)
```

**Comment by bastimeyer** [comment]
Considering that the site makes hardcoded API requests to endpoints specific to that event, I don't think it's worth rewriting the plugin, because it'd require fixes or a complete rewrite every time there is a new event. The current plugin implementation completely differs from what the site is doing now.

The plugin has already been rewritten multiple times:
https://github.com/streamlink/streamlink/commits/6.5.1/src/streamlink/plugins/olympicchannel.py

Those rewrites were based on https://olympicchannel.com, which is now a redirection to https://olympics.com, so this is probably the reason why it's completely different now.

I'd say the plugin should be removed, and if there is a desire to re-implement it (for the next main event), it should be done using the `olympics` name, and not `olympicchannel`.

**Comment by bastimeyer** [comment]
Some (old) URLs are still working though, so I guess only the streams of the current event don't work.

```
$ ./script/test-plugin-urls.py olympicchannel
:: Finding streams for URL: https://olympics.com/en/original-series/episode/how-fun-fuels-this-para-taekwondo-world-champion-unleash-the-new
:: Found streams: 192p, 216p, 288p, 360p, 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://olympics.com/en/sport-events/2021-fiba-3x3-olympic-qualifier-graz/?slug=final-day-fiba-3x3-olympic-qualifier-graz
!! Error while fetching streams
:: Finding streams for URL: https://olympics.com/en/video/spider-woman-shauna-coxsey-great-britain-climbing-interview
:: Found streams: 192p, 216p, 288p, 360p, 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://olympics.com/tokyo-2020/en/news/videos/tokyo-2020-1-message
!! Error while fetching streams
:: Finding streams for URL: https://www.olympicchannel.com/de/original-series/detail/body/body-season-season-1/episodes/treffen-sie-aaron-wheelz-fotheringham-den-paten-des-rollstuhl-extremsports/
:: Found streams: 192p, 216p, 288p, 360p, 432p, 576p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.olympicchannel.com/de/video/detail/stefanidi-husband-coach-krier-relationship/
!! Error while fetching streams
:: Finding streams for URL: https://www.olympicchannel.com/en/live/
:: Found streams: 270p, 360p, 540p, 720p, 1080p, worst, best
:: Finding streams for URL: https://www.olympicchannel.com/en/live/video/detail/olympic-ceremonies-channel/
!! Error while fetching streams
:: Finding streams for URL: https://www.olympicchannel.com/en/video/detail/stefanidi-husband-coach-krier-relationship/
:: Found streams: 192p, 216p, 288p, 360p, 432p, 576p, 720p, 1080p, worst, best
```
