### ISSUE TITLE
Streamlink is broken since c2f0626 commit on enigma2 platform

### ISSUE THREAD

**Issue by jeepcook** [streamlink/streamlink#5825]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink_6.5.1-git5008+eb901bb_0.0-git15+00ac6e40+eb901bbc9e_00ac6e405b-r0_cortexa15hf-neon-vfpv4

### Description

Streamlink doesn't work anymore still 5004 version, commit c2f0626 on enigma2 platform

I don't know how to generate a log but after downgrade from 5008 to 5003 version, the streamlink streams are now working (version streamlink_6.5.1-git5003+503df3e_0.0-git15+00ac6e40+503df3e15a_00ac6e405b-r0_cortexa15hf-neon-vfpv4)

script which execute streamlink: /usr/bin/python /etc/rc3.d/S50streamlinksrv start

[S50streamlinksrv.zip](https://github.com/streamlink/streamlink/files/14248018/S50streamlinksrv.zip)

### Debug log

```text
Unable to generate a log. need help for this.
```

**Comment by mkbloke** [comment]
As said before:

> Downstream forks are also not supported here.

You'll need to find the right owner of this fork and ask them for help.

**Comment by bastimeyer** [comment]
Right there at the top of this file

> ```
> # Linux Python2/3 Streamlink Daemon
> #
> # Copyright (c) 2017 - 2021 Billy2011 @vuplus-support.org
> # Copyright (c) 2021 jbleyel (python3 mod)
> # License: GPLv2+
> ```

And btw, this very much violates Streamlink's license, because there's a lot of (old) code from the Streamlink project which has been copied there, without including [Streamlink's license](https://github.com/streamlink/streamlink/blob/master/LICENSE).

**Comment by bastimeyer** [comment]
Without running this even once and without checking anything else, and also ignoring all the countless of other code issues, this is probably what you're looking for:

```diff
diff --git a/./S50streamlinksrv.old b/./S50streamlinksrv
index 38408a4..efe1794 100644
--- a/./S50streamlinksrv.old
+++ b/./S50streamlinksrv
@@ -916,32 +916,6 @@ def Stream(streamlink, http, url, argstr, quality):
             LOGGER.info("Closing currently open stream...")
 
 
-class Streamlink2(Streamlink):
-    _loaded_plugins = None
-
-    def load_builtin_plugins(self):
-        if self.__class__._loaded_plugins is not None:
-            self._update_loaded_plugins()
-        else:
-            self.load_plugins(plugins.__path__[0])
-            if os.path.isdir(PLUGINS_DIR):
-                self.load_ext_plugins([PLUGINS_DIR])
-            self.__class__._loaded_plugins = self.plugins.copy()
-
-    def _update_loaded_plugins(self):
-        self.plugins = self.__class__._loaded_plugins.copy()
-        for plugin in itervalues(self.plugins):
-            plugin.session = self
-
-    def load_ext_plugins(self, dirs):
-        dirs = [os.path.expanduser(d) for d in dirs]
-        for directory in dirs:
-            if os.path.isdir(directory):
-                self.load_plugins(directory)
-            else:
-                LOGGER.warning("Plugin path {0} does not exist or is not a directory!".format(directory))
-
-
 class StreamHandler(BaseHTTPRequestHandler):
 
     def do_HEAD(s):
@@ -961,7 +935,8 @@ class StreamHandler(BaseHTTPRequestHandler):
 
         with warnings.catch_warnings():
             warnings.simplefilter("ignore")
-            streamlink = Streamlink2()
+            streamlink = Streamlink()
+            streamlink.plugins.load_path(PLUGINS_DIR)
 
         return Stream(streamlink, s, url[0].strip(), url[1:2], quality)
```

This is as much as I'm willing to help you here, as this is not part of Streamlink.

This script apparently attempted to cache loaded plugins between session initializations, as it acts as a daemon script. It had a flawed way of importing plugins by overriding one of the now deprecated methods, namely `Streamlink.load_builtin_plugins()`.

**Comment by jeepcook** [comment]
@bastimeyer , 
Thanks for this analyse and fix, but the daemon doesn't start after implementing your mods.
For information, another dev made a script which is a streamlink daemon too. Here is the code, there is no problem with it, it works with the last streamlink version.
[streamlinkproxy_6.5.3.zip](https://github.com/streamlink/streamlink/files/14249575/streamlinkproxy_6.5.3.zip)

I know you don't like this kind of port but for this one the code is cleaner I think.

**Comment by gravyboat** [comment]
I'm going to close and lock this. @bastimeyer Already went above and beyond. We're not supporting this fork or helping troubleshoot it further, nor are we taking suggestion for improvements via issues. The people building these forks which violate our license requirements. @bastimeyer If we know the repos associated with these projects we should report them to GitHub to be shut down for violating our licensing requirements.
