### ISSUE TITLE
Add Plugin for Akibapass.de

### ISSUE THREAD

**Issue by Lucain872** [streamlink/streamlink#583]
I've forgot to add an label. Please forgive me.

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

Hello,

is it possible to add an plugin for Akibapass.de? It is an Website for animes like Crunchyroll, so I thought about adding an plugin, where you have to log in and then grab the (i think it is an HLS stream) stream. You can't watch the video without an subscription, so it would fail if you don't have an subscription. (I hope I could make my request understandable enough.

Is there a possibility to make an plugin? 

Thanks in advance! 
#
Examples for the URL's: 

http://www.akibapass.de/de/v2/catalogue/episode/2656/wwwworking-omu-episode-01
http://www.akibapass.de/de/v2/catalogue/episode/2460/sword-art-online-ii-omu-episode-01

**Comment by Lucain872** [comment]
When you register, you get a month for free - you don't have to enter a credit card or a PayPal account and it ends automatically.

**Comment by beardypig** [comment]
Well that makes it possible, I'll take a look when I get a chance.

**Comment by Lucain872** [comment]
Thanks for that! :-)

**Comment by beardypig** [comment]
I have a semi-working plugin. Somehow the audio and video and not in-sync... But i'm working on it :)

**Comment by Lucain872** [comment]
That was fast! Hoping for the best ;)

**Comment by back-to** [comment]
closing, website does not contain videos anymore.
