### ISSUE TITLE
plugins.afreeca : Could not find broadcast number.

### ISSUE THREAD

**Issue by daspryJ** [streamlink/streamlink#5845]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.6.1

### Description

The plugin is no longer working for me, as it seems to no longer be able to find the broadcast number, as if the stream was off, when I tested on multiple online Afreeca broadcasts.
I tried with both https://play.afreecatv.com/user and https://play.afreecatv.com/user/number url format, and it was working fine yesterday.
I had an old streamlink/python version, but updating both did not change anything.

### Debug log

```text
streamlink.exe -o "C:\Users\...\{time:%y%m%d_%Hh%Mm%Ss}_{title}_test.ts" https://play.afreecatv.com/ecvhao best --retry-streams 60 --stream-segment-threads 10 --loglevel=debug 


[session][debug] Loading plugin: afreeca
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.2
[cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[cli][debug] Streamlink: 6.6.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 2.2.0
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/ecvhao
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=C:\Users\...\{time:%y%m%d_%Hh%Mm%Ss}_{title}_test.ts
[cli][debug]  --retry-streams=60.0
[cli][debug]  --stream-segment-threads=10
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/ecvhao
[plugins.afreeca][error] Could not find broadcast number.
[cli][info] Waiting for streams, retrying every 60.0 second(s)
```

**Comment by NormanMises** [comment]
I'm having the same problem

**Comment by daspryJ** [comment]
They have already solved the issue and probably very soon will update it. If you want to use now, you can download this file : https://github.com/B4TT3RY/streamlink/blob/plugins/afreeca/fix-find-broadcast-number/src/streamlink/plugins/afreeca.py
In your streamlink plugin folder (https://streamlink.github.io/cli/plugin-sideloading.html)

**Comment by bastimeyer** [comment]
Open a new plugin issue if authentication is not working. The regular streams have been fixed by the linked PR.

**Comment by bastimeyer** [comment]
Don't forget to set `--afreeca-purge-credentials` once, so old cookies get removed.

I unfortunately can't help if there are indeed any auth issues, because I don't have an account. I'm unable to create a new one either because of their phone number requirements.

As said, 6.6.2 will be published later today, so if anyone could check this and squeeze in a plugin fix, now is the right time.

**Comment by B4TT3RY** [comment]
I'm working normally. I don't think it's a bug.

```
[session][debug] Plugin afreeca is being overridden by /home/b4tt3ry/.local/share/streamlink/plugins/afreeca.py
[cli][debug] OS:         Linux-6.5.11-8-pve-x86_64-with-glibc2.38
[cli][debug] Python:     3.11.6
[cli][debug] OpenSSL:    OpenSSL 3.2.1 30 Jan 2024
[cli][debug] Streamlink: 6.5.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.11.17
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.24.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 1.26.18
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.afreecatv.com/djwls7400/255389088
[cli][debug]  --loglevel=debug
[cli][debug]  --afreeca-username=********
[cli][debug]  --afreeca-password=********
[cli][info] Found matching plugin afreeca for URL https://play.afreecatv.com/djwls7400/255389088
[plugins.afreeca][debug] Attempting to login using username and password
[plugins.afreeca][debug] Saved cookies: AbroadChk, AbroadVod, _au, _au3rd, _ausa, _ausb, PdboxTicket, PdboxBbs, PdboxUser, isBbs, RDB, PdboxSaveTicket
[plugins.afreeca][info] Login was successful
Available streams: sd (worst), hd, original (best)
```

**Comment by pulbitz** [comment]
It was my mistake.
Age verification for afreeca accounts is required once a year, and it just so happened to be the day I was testing it.
There's nothing wrong with the plugin.
Thanks for the fix!
