### ISSUE TITLE
plugins.hiplayer: new plugin for kuwait tvs changes

### ISSUE THREAD

**Issue by ipstreet312** [streamlink/streamlink#5846]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.6.1

### Description

Hello,

After few days offlines, change from 'hibridcdn' to 'mangomolo' is noticed for kuwait tv channels.

src/streamlink/plugins/hiplayer.py is no more suitable for : "media.gov.kw" entry

- Still Call page : https://www.media.gov.kw/LiveTV.aspx?PanChannel=KTV1
- Same Channel variants : `KTV1` value could be also : `KTV2, KTVArabe, KhallikBilbait, KTVEthraa, KTVPlus, KTVSports, KTVSportPlus, KTVSportExtra`

Below reported new gathering method details :

- New master src host page : https://player.mangomolo.com/v1/live?id=xxxxxx
- src synthax : https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/playlist.m3u8?xxx
- id ch. variant values : `tv2, tva, kb, eth, ktvaq, sp, spl, alm`

- chunk structure : https://kwtktv1ta.cdn.mangomolo.com/ktv1/smil:ktv1.stream.smil/chunklist_bXXXXX_xyxy==.m3u8

Could someone adapt related plugin please ? Thanks a lot, regards

### Debug log

```text
Currently : Could not find JS URL
```

**Comment by bastimeyer** [comment]
https://media.gov.kw is now using a different stream host, namely https://mangomolo.com.

This requires a separate plugin implementation and the hiplayer plugin needs to be updated accordingly with a removal of the unsupported matcher.
