### ISSUE TITLE
Rumble.com

### ISSUE THREAD

**Issue by bermudi** [streamlink/streamlink#5859]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Rumble is an online video platform founded in October 2013 by Chris Pavlovski as an alternative to YouTube for independent vloggers and smaller content creators.

According to the platform's terms and conditions, Rumble forbids pornography, harassment, racism, antisemitism, and copyright infringement. The platform also prohibits illegal content.

As of August 15, 2022, Rumble reported 78 million monthly active users (MAU). According to an August 2022 Reuters article, Rumble is 'better-funded' and 'more mainstream' than its competitors BitChute and Odysee.

According to a May 2022 Pew Research Center study, 20% of American adults have heard of Rumble, while 2% regularly got their news from Rumble.

In early 2023, Rumble began hosting live broadcasts for sports leagues owned by Thrill One Sports & Entertainment such as Nitrocross, Street League Skateboarding, and Power Slap.

### Input URLs

https://rumble.com/v4do2zn-2024-sls-paris-womens-and-mens-knockout-rounds.html

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/pull/6077#issuecomment-2220858720
