### ISSUE TITLE
Don't abuse the discussion forum for plugin issues. The rules are stated very clearly here.

### ISSUE THREAD

**Issue by serseri0690** [streamlink/streamlink#5864]
Don't abuse the discussion forum for plugin issues. The rules are stated very clearly here.

In #5855 you failed to provide a full debug log. What you have posted is useless information because we don't even know which version of Streamlink you're running and whether you have made any other modifications. A full debug log (`--loglevel=debug`) without doing any other stuff like piping into ffmpeg would show this.

I have also clearly demonstrated that the plugin is working fine using the latest version of Streamlink.

And as you can see in the [plugin code](https://github.com/streamlink/streamlink/blob/6.6.2/src/streamlink/plugins/bigo.py#L29), all the plugin does is query a single API endpoint with the expectation of a JSON response. The error you're receiving is caused by a HTML response, which indicates that you're either blocked and they simply respond with different kind of data, or you're running some different/modified version of Streamlink.

Closing and locking this thread... If you want actual help, then start reading the plugin issue requirements we've set up here and adhere to them.

_Originally posted by @bastimeyer in https://github.com/streamlink/streamlink/discussions/5863#discussioncomment-8584513_

**Comment by serseri0690** [comment]
[Streamlink for Windows]
[session][debug] Plugin abematv is being overridden by C:\Users\90538\Desktop\B1go\plugins\abematv.py
[session][debug] Plugin abweb is being overridden by C:\Users\90538\Desktop\B1go\plugins\abweb.py
[session][debug] Plugin adultswim is being overridden by C:\Users\90538\Desktop\B1go\plugins\adultswim.py
[session][debug] Plugin afreeca is being overridden by C:\Users\90538\Desktop\B1go\plugins\afreeca.py
[session][debug] Plugin akamaihd is being overridden by C:\Users\90538\Desktop\B1go\plugins\akamaihd.py
[session][debug] Plugin albavision is being overridden by C:\Users\90538\Desktop\B1go\plugins\albavision.py
[session][debug] Plugin aljazeeraen is being overridden by C:\Users\90538\Desktop\B1go\plugins\aljazeeraen.py
[session][debug] Plugin animelab is being overridden by C:\Users\90538\Desktop\B1go\plugins\animelab.py
[session][debug] Plugin app17 is being overridden by C:\Users\90538\Desktop\B1go\plugins\app17.py
[session][debug] Plugin ard_live is being overridden by C:\Users\90538\Desktop\B1go\plugins\ard_live.py
[session][debug] Plugin ard_mediathek is being overridden by C:\Users\90538\Desktop\B1go\plugins\ard_mediathek.py
[session][debug] Plugin artetv is being overridden by C:\Users\90538\Desktop\B1go\plugins\artetv.py
[session][debug] Plugin atresplayer is being overridden by C:\Users\90538\Desktop\B1go\plugins\atresplayer.py
[session][debug] Plugin bbciplayer is being overridden by C:\Users\90538\Desktop\B1go\plugins\bbciplayer.py
[session][debug] Plugin bfmtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\bfmtv.py
[session][debug] Plugin bigo is being overridden by C:\Users\90538\Desktop\B1go\plugins\bigo.py
[session][debug] Plugin bilibili is being overridden by C:\Users\90538\Desktop\B1go\plugins\bilibili.py
[session][debug] Plugin bloomberg is being overridden by C:\Users\90538\Desktop\B1go\plugins\bloomberg.py
[session][debug] Plugin brightcove is being overridden by C:\Users\90538\Desktop\B1go\plugins\brightcove.py
[session][debug] Plugin btsports is being overridden by C:\Users\90538\Desktop\B1go\plugins\btsports.py
[session][debug] Plugin btv is being overridden by C:\Users\90538\Desktop\B1go\plugins\btv.py
[session][debug] Plugin canalplus is being overridden by C:\Users\90538\Desktop\B1go\plugins\canalplus.py
[session][debug] Plugin cdnbg is being overridden by C:\Users\90538\Desktop\B1go\plugins\cdnbg.py
[session][debug] Plugin ceskatelevize is being overridden by C:\Users\90538\Desktop\B1go\plugins\ceskatelevize.py
[session][debug] Plugin cinergroup is being overridden by C:\Users\90538\Desktop\B1go\plugins\cinergroup.py
[session][debug] Plugin clubbingtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\clubbingtv.py
[session][debug] Plugin cnews is being overridden by C:\Users\90538\Desktop\B1go\plugins\cnews.py
[session][debug] Plugin crunchyroll is being overridden by C:\Users\90538\Desktop\B1go\plugins\crunchyroll.py
[session][debug] Plugin cubetv is being overridden by C:\Users\90538\Desktop\B1go\plugins\cubetv.py
[session][debug] Plugin cybergame is being overridden by C:\Users\90538\Desktop\B1go\plugins\cybergame.py
[session][debug] Plugin dailymotion is being overridden by C:\Users\90538\Desktop\B1go\plugins\dailymotion.py
[session][debug] Plugin dash is being overridden by C:\Users\90538\Desktop\B1go\plugins\dash.py
[session][debug] Plugin delfi is being overridden by C:\Users\90538\Desktop\B1go\plugins\delfi.py
[session][debug] Plugin deutschewelle is being overridden by C:\Users\90538\Desktop\B1go\plugins\deutschewelle.py
[session][debug] Plugin dingittv is being overridden by C:\Users\90538\Desktop\B1go\plugins\dingittv.py
[session][debug] Plugin dlive is being overridden by C:\Users\90538\Desktop\B1go\plugins\dlive.py
[session][debug] Plugin dogan is being overridden by C:\Users\90538\Desktop\B1go\plugins\dogan.py
[session][debug] Plugin dogus is being overridden by C:\Users\90538\Desktop\B1go\plugins\dogus.py
[session][debug] Plugin dommune is being overridden by C:\Users\90538\Desktop\B1go\plugins\dommune.py
[session][debug] Plugin douyutv is being overridden by C:\Users\90538\Desktop\B1go\plugins\douyutv.py
[session][debug] Plugin drdk is being overridden by C:\Users\90538\Desktop\B1go\plugins\drdk.py
[session][debug] Plugin earthcam is being overridden by C:\Users\90538\Desktop\B1go\plugins\earthcam.py
[session][debug] Plugin egame is being overridden by C:\Users\90538\Desktop\B1go\plugins\egame.py
[session][debug] Plugin ellobo is being overridden by C:\Users\90538\Desktop\B1go\plugins\ellobo.py
[session][debug] Plugin eltrecetv is being overridden by C:\Users\90538\Desktop\B1go\plugins\eltrecetv.py
[session][debug] Plugin euronews is being overridden by C:\Users\90538\Desktop\B1go\plugins\euronews.py
[session][debug] Plugin europaplus is being overridden by C:\Users\90538\Desktop\B1go\plugins\europaplus.py
[session][debug] Plugin facebook is being overridden by C:\Users\90538\Desktop\B1go\plugins\facebook.py
[session][debug] Plugin filmon is being overridden by C:\Users\90538\Desktop\B1go\plugins\filmon.py
[session][debug] Plugin foxtr is being overridden by C:\Users\90538\Desktop\B1go\plugins\foxtr.py
[session][debug] Plugin funimationnow is being overridden by C:\Users\90538\Desktop\B1go\plugins\funimationnow.py
[session][debug] Plugin galatasaraytv is being overridden by C:\Users\90538\Desktop\B1go\plugins\galatasaraytv.py
[session][debug] Plugin gardenersworld is being overridden by C:\Users\90538\Desktop\B1go\plugins\gardenersworld.py
[session][debug] Plugin garena is being overridden by C:\Users\90538\Desktop\B1go\plugins\garena.py
[session][debug] Plugin goltelevision is being overridden by C:\Users\90538\Desktop\B1go\plugins\goltelevision.py
[session][debug] Plugin goodgame is being overridden by C:\Users\90538\Desktop\B1go\plugins\goodgame.py
[session][debug] Plugin googledrive is being overridden by C:\Users\90538\Desktop\B1go\plugins\googledrive.py
[session][debug] Plugin gulli is being overridden by C:\Users\90538\Desktop\B1go\plugins\gulli.py
[session][debug] Plugin hds is being overridden by C:\Users\90538\Desktop\B1go\plugins\hds.py
[session][debug] Plugin hitbox is being overridden by C:\Users\90538\Desktop\B1go\plugins\hitbox.py
[session][debug] Plugin hls is being overridden by C:\Users\90538\Desktop\B1go\plugins\hls.py
[session][debug] Plugin http is being overridden by C:\Users\90538\Desktop\B1go\plugins\http.py
[session][debug] Plugin huajiao is being overridden by C:\Users\90538\Desktop\B1go\plugins\huajiao.py
[session][debug] Plugin huomao is being overridden by C:\Users\90538\Desktop\B1go\plugins\huomao.py
[session][debug] Plugin huya is being overridden by C:\Users\90538\Desktop\B1go\plugins\huya.py
[session][debug] Plugin idf1 is being overridden by C:\Users\90538\Desktop\B1go\plugins\idf1.py
[session][debug] Plugin ine is being overridden by C:\Users\90538\Desktop\B1go\plugins\ine.py
[session][debug] Plugin invintus is being overridden by C:\Users\90538\Desktop\B1go\plugins\invintus.py
[session][debug] Plugin itvplayer is being overridden by C:\Users\90538\Desktop\B1go\plugins\itvplayer.py
[session][debug] Plugin kingkong is being overridden by C:\Users\90538\Desktop\B1go\plugins\kingkong.py
[session][debug] Plugin kugou is being overridden by C:\Users\90538\Desktop\B1go\plugins\kugou.py
[session][debug] Plugin latina is being overridden by C:\Users\90538\Desktop\B1go\plugins\latina.py
[session][debug] Plugin linelive is being overridden by C:\Users\90538\Desktop\B1go\plugins\linelive.py
[session][debug] Plugin live_russia_tv is being overridden by C:\Users\90538\Desktop\B1go\plugins\live_russia_tv.py
[session][debug] Plugin liveedu is being overridden by C:\Users\90538\Desktop\B1go\plugins\liveedu.py
[session][debug] Plugin liveme is being overridden by C:\Users\90538\Desktop\B1go\plugins\liveme.py
[session][debug] Plugin livestream is being overridden by C:\Users\90538\Desktop\B1go\plugins\livestream.py
[session][debug] Plugin lrt is being overridden by C:\Users\90538\Desktop\B1go\plugins\lrt.py
[session][debug] Plugin ltv_lsm_lv is being overridden by C:\Users\90538\Desktop\B1go\plugins\ltv_lsm_lv.py
[session][debug] Plugin mediaklikk is being overridden by C:\Users\90538\Desktop\B1go\plugins\mediaklikk.py
[session][debug] Plugin metube is being overridden by C:\Users\90538\Desktop\B1go\plugins\metube.py
[session][debug] Plugin mitele is being overridden by C:\Users\90538\Desktop\B1go\plugins\mitele.py
[session][debug] Plugin mjunoon is being overridden by C:\Users\90538\Desktop\B1go\plugins\mjunoon.py
[session][debug] Plugin n13tv is being overridden by C:\Users\90538\Desktop\B1go\plugins\n13tv.py
[session][debug] Plugin nbc is being overridden by C:\Users\90538\Desktop\B1go\plugins\nbc.py
[session][debug] Plugin nbcnews is being overridden by C:\Users\90538\Desktop\B1go\plugins\nbcnews.py
[session][debug] Plugin nbcsports is being overridden by C:\Users\90538\Desktop\B1go\plugins\nbcsports.py
[session][debug] Plugin nhkworld is being overridden by C:\Users\90538\Desktop\B1go\plugins\nhkworld.py
[session][debug] Plugin nicolive is being overridden by C:\Users\90538\Desktop\B1go\plugins\nicolive.py
[session][debug] Plugin nos is being overridden by C:\Users\90538\Desktop\B1go\plugins\nos.py
[session][debug] Plugin nownews is being overridden by C:\Users\90538\Desktop\B1go\plugins\nownews.py
[session][debug] Plugin nrk is being overridden by C:\Users\90538\Desktop\B1go\plugins\nrk.py
[session][debug] Plugin ntv is being overridden by C:\Users\90538\Desktop\B1go\plugins\ntv.py
[session][debug] Plugin okru is being overridden by C:\Users\90538\Desktop\B1go\plugins\okru.py
[session][debug] Plugin olympicchannel is being overridden by C:\Users\90538\Desktop\B1go\plugins\olympicchannel.py
[session][debug] Plugin oneplusone is being overridden by C:\Users\90538\Desktop\B1go\plugins\oneplusone.py
[session][debug] Plugin onetv is being overridden by C:\Users\90538\Desktop\B1go\plugins\onetv.py
[session][debug] Plugin openrectv is being overridden by C:\Users\90538\Desktop\B1go\plugins\openrectv.py
[session][debug] Plugin orf_tvthek is being overridden by C:\Users\90538\Desktop\B1go\plugins\orf_tvthek.py
[session][debug] Plugin pandatv is being overridden by C:\Users\90538\Desktop\B1go\plugins\pandatv.py
[session][debug] Plugin periscope is being overridden by C:\Users\90538\Desktop\B1go\plugins\periscope.py
[session][debug] Plugin picarto is being overridden by C:\Users\90538\Desktop\B1go\plugins\picarto.py
[session][debug] Plugin piczel is being overridden by C:\Users\90538\Desktop\B1go\plugins\piczel.py
[session][debug] Plugin pixiv is being overridden by C:\Users\90538\Desktop\B1go\plugins\pixiv.py
[session][debug] Plugin playtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\playtv.py
[session][debug] Plugin pluzz is being overridden by C:\Users\90538\Desktop\B1go\plugins\pluzz.py
[session][debug] Plugin powerapp is being overridden by C:\Users\90538\Desktop\B1go\plugins\powerapp.py
[session][debug] Plugin qq is being overridden by C:\Users\90538\Desktop\B1go\plugins\qq.py
[session][debug] Plugin radiko is being overridden by C:\Users\90538\Desktop\B1go\plugins\radiko.py
[session][debug] Plugin radionet is being overridden by C:\Users\90538\Desktop\B1go\plugins\radionet.py
[session][debug] Plugin raiplay is being overridden by C:\Users\90538\Desktop\B1go\plugins\raiplay.py
[session][debug] Plugin reuters is being overridden by C:\Users\90538\Desktop\B1go\plugins\reuters.py
[session][debug] Plugin rotana is being overridden by C:\Users\90538\Desktop\B1go\plugins\rotana.py
[session][debug] Plugin rtbf is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtbf.py
[session][debug] Plugin rtlxl is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtlxl.py
[session][debug] Plugin rtmp is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtmp.py
[session][debug] Plugin rtpplay is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtpplay.py
[session][debug] Plugin rtve is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtve.py
[session][debug] Plugin rtvs is being overridden by C:\Users\90538\Desktop\B1go\plugins\rtvs.py
[session][debug] Plugin ruv is being overridden by C:\Users\90538\Desktop\B1go\plugins\ruv.py
[session][debug] Plugin sbscokr is being overridden by C:\Users\90538\Desktop\B1go\plugins\sbscokr.py
[session][debug] Plugin schoolism is being overridden by C:\Users\90538\Desktop\B1go\plugins\schoolism.py
[session][debug] Plugin senategov is being overridden by C:\Users\90538\Desktop\B1go\plugins\senategov.py
[session][debug] Plugin showroom is being overridden by C:\Users\90538\Desktop\B1go\plugins\showroom.py
[session][debug] Plugin skai is being overridden by C:\Users\90538\Desktop\B1go\plugins\skai.py
[session][debug] Plugin sportal is being overridden by C:\Users\90538\Desktop\B1go\plugins\sportal.py
[session][debug] Plugin sportschau is being overridden by C:\Users\90538\Desktop\B1go\plugins\sportschau.py
[session][debug] Plugin srgssr is being overridden by C:\Users\90538\Desktop\B1go\plugins\srgssr.py
[session][debug] Plugin ssh101 is being overridden by C:\Users\90538\Desktop\B1go\plugins\ssh101.py
[session][debug] Plugin stadium is being overridden by C:\Users\90538\Desktop\B1go\plugins\stadium.py
[session][debug] Plugin startv is being overridden by C:\Users\90538\Desktop\B1go\plugins\startv.py
[session][debug] Plugin steam is being overridden by C:\Users\90538\Desktop\B1go\plugins\steam.py
[session][debug] Plugin streamable is being overridden by C:\Users\90538\Desktop\B1go\plugins\streamable.py
[session][debug] Plugin streamingvideoprovider is being overridden by C:\Users\90538\Desktop\B1go\plugins\streamingvideoprovider.py
[session][debug] Plugin streamme is being overridden by C:\Users\90538\Desktop\B1go\plugins\streamme.py
[session][debug] Plugin streann is being overridden by C:\Users\90538\Desktop\B1go\plugins\streann.py
[session][debug] Plugin stv is being overridden by C:\Users\90538\Desktop\B1go\plugins\stv.py
[session][debug] Plugin svtplay is being overridden by C:\Users\90538\Desktop\B1go\plugins\svtplay.py
[session][debug] Plugin swisstxt is being overridden by C:\Users\90538\Desktop\B1go\plugins\swisstxt.py
[session][debug] Plugin tamago is being overridden by C:\Users\90538\Desktop\B1go\plugins\tamago.py
[session][debug] Plugin teamliquid is being overridden by C:\Users\90538\Desktop\B1go\plugins\teamliquid.py
[session][debug] Plugin teleclubzoom is being overridden by C:\Users\90538\Desktop\B1go\plugins\teleclubzoom.py
[session][debug] Plugin telefe is being overridden by C:\Users\90538\Desktop\B1go\plugins\telefe.py
[session][debug] Plugin tf1 is being overridden by C:\Users\90538\Desktop\B1go\plugins\tf1.py
[session][debug] Plugin tga is being overridden by C:\Users\90538\Desktop\B1go\plugins\tga.py
[session][debug] Plugin theplatform is being overridden by C:\Users\90538\Desktop\B1go\plugins\theplatform.py
[session][debug] Plugin tigerdile is being overridden by C:\Users\90538\Desktop\B1go\plugins\tigerdile.py
[session][debug] Plugin tlctr is being overridden by C:\Users\90538\Desktop\B1go\plugins\tlctr.py
[session][debug] Plugin trt is being overridden by C:\Users\90538\Desktop\B1go\plugins\trt.py
[session][debug] Plugin trtspor is being overridden by C:\Users\90538\Desktop\B1go\plugins\trtspor.py
[session][debug] Plugin turkuvaz is being overridden by C:\Users\90538\Desktop\B1go\plugins\turkuvaz.py
[session][debug] Plugin tv360 is being overridden by C:\Users\90538\Desktop\B1go\plugins\tv360.py
[session][debug] Plugin tv3cat is being overridden by C:\Users\90538\Desktop\B1go\plugins\tv3cat.py
[session][debug] Plugin tv4play is being overridden by C:\Users\90538\Desktop\B1go\plugins\tv4play.py
[session][debug] Plugin tv5monde is being overridden by C:\Users\90538\Desktop\B1go\plugins\tv5monde.py
[session][debug] Plugin tv8 is being overridden by C:\Users\90538\Desktop\B1go\plugins\tv8.py
[session][debug] Plugin tvibo is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvibo.py
[session][debug] Plugin tvp is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvp.py
[session][debug] Plugin tvplayer is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvplayer.py
[session][debug] Plugin tvrby is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvrby.py
[session][debug] Plugin tvrplus is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvrplus.py
[session][debug] Plugin tvtoya is being overridden by C:\Users\90538\Desktop\B1go\plugins\tvtoya.py
[session][debug] Plugin twitcasting is being overridden by C:\Users\90538\Desktop\B1go\plugins\twitcasting.py
[session][debug] Plugin twitch is being overridden by C:\Users\90538\Desktop\B1go\plugins\twitch.py
[session][debug] Plugin ustreamtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\ustreamtv.py
[session][debug] Plugin ustvnow is being overridden by C:\Users\90538\Desktop\B1go\plugins\ustvnow.py
[session][debug] Plugin vaughnlive is being overridden by C:\Users\90538\Desktop\B1go\plugins\vaughnlive.py
[session][debug] Plugin viasat is being overridden by C:\Users\90538\Desktop\B1go\plugins\viasat.py
[session][debug] Plugin vidio is being overridden by C:\Users\90538\Desktop\B1go\plugins\vidio.py
[session][debug] Plugin vimeo is being overridden by C:\Users\90538\Desktop\B1go\plugins\vimeo.py
[session][debug] Plugin vinhlongtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\vinhlongtv.py
[session][debug] Plugin viutv is being overridden by C:\Users\90538\Desktop\B1go\plugins\viutv.py
[session][debug] Plugin vk is being overridden by C:\Users\90538\Desktop\B1go\plugins\vk.py
[session][debug] Plugin vlive is being overridden by C:\Users\90538\Desktop\B1go\plugins\vlive.py
[session][debug] Plugin vrtbe is being overridden by C:\Users\90538\Desktop\B1go\plugins\vrtbe.py
[session][debug] Plugin vtvgo is being overridden by C:\Users\90538\Desktop\B1go\plugins\vtvgo.py
[session][debug] Plugin wasd is being overridden by C:\Users\90538\Desktop\B1go\plugins\wasd.py
[session][debug] Plugin webcast_india_gov is being overridden by C:\Users\90538\Desktop\B1go\plugins\webcast_india_gov.py
[session][debug] Plugin webtv is being overridden by C:\Users\90538\Desktop\B1go\plugins\webtv.py
[session][debug] Plugin welt is being overridden by C:\Users\90538\Desktop\B1go\plugins\welt.py
[session][debug] Plugin willax is being overridden by C:\Users\90538\Desktop\B1go\plugins\willax.py
[session][debug] Plugin wwenetwork is being overridden by C:\Users\90538\Desktop\B1go\plugins\wwenetwork.py
[session][debug] Plugin youtube is being overridden by C:\Users\90538\Desktop\B1go\plugins\youtube.py
[session][debug] Plugin yupptv is being overridden by C:\Users\90538\Desktop\B1go\plugins\yupptv.py
[session][debug] Plugin zattoo is being overridden by C:\Users\90538\Desktop\B1go\plugins\zattoo.py
[session][debug] Plugin zdf_mediathek is being overridden by C:\Users\90538\Desktop\B1go\plugins\zdf_mediathek.py
[session][debug] Plugin zeenews is being overridden by C:\Users\90538\Desktop\B1go\plugins\zeenews.py
[session][debug] Plugin zengatv is being overridden by C:\Users\90538\Desktop\B1go\plugins\zengatv.py
[session][debug] Plugin zhanqi is being overridden by C:\Users\90538\Desktop\B1go\plugins\zhanqi.py
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.6.8
[cli][debug] Streamlink: 1.5.0+e049645
[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.44.0)
usage: Streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io
[End of Streamlink for Windows with ExitCode 0]

Type another command or EXIT to end:


The current information looks like this. Could you please make your own downloader .zip/.rar and add it? Or can you explain in detail what the problem is?

**Comment by bastimeyer** [comment]
You are using a Streamlink fork, and an ancient version of that, too. This is very much unsupported.
https://streamlink.github.io/install.html
