### ISSUE TITLE
plugins.bloomberg: error: unmatched '{' in format spec

### ISSUE THREAD

**Issue by chaoyic** [streamlink/streamlink#5868]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.6.2

### Description

It's quite a strange error. Seems like there is a change to the JSON data return from Bloomberg, or it is corrupted.

### Debug log

```text
$ streamlink --loglevel=debug https://www.bloomberg.com/live/us
[session][debug] Loading plugin: bloomberg
[cli][debug] OS:         macOS 10.16
[cli][debug] Python:     3.9.12
[cli][debug] OpenSSL:    OpenSSL 1.1.1n  15 Mar 2022
[cli][debug] Streamlink: 6.6.2
[cli][debug] Dependencies:
[cli][debug]  certifi: 2021.10.8
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.8.0
[cli][debug]  pycountry: 22.3.5
[cli][debug]  pycryptodome: 3.19.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.27.1
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.1.1
[cli][debug]  urllib3: 1.26.9
[cli][debug]  websocket-client: 1.6.3
[cli][debug] Arguments:
[cli][debug]  url=https://www.bloomberg.com/live/us
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin bloomberg for URL https://www.bloomberg.com/live/us
error: unmatched '{' in format spec
```

**Comment by chaoyic** [comment]
Thanks @bastimeyer . Very sorry that I forgot to update the title. :(

**Comment by bastimeyer** [comment]
All good... In regards to the issue, there are two JSON payloads embedded in their site now, while the regex capture group was greedy, unintentionally matching the second one that comes right after the first one, including the JavaScript code, hence the JSON parsing issue of the data.
