### ISSUE TITLE
TV d'Orange support

### ISSUE THREAD

**Issue by kalimeroo** [streamlink/streamlink#588]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Support of TV d'Orange (if connected to Orange network)

### Expected / Actual behavior
Orange TV streams with the silverlight technologies. It sends a f4m Manifest file and then chunks of video to the end user. I can play some of the streams with VLC but it keeps on resizing the video.
My python is way too bad to write a plugin but I would be happy to provide further informations if needed.

**Comment by beardypig** [comment]
How do you recieve the streams? Is there a website or app or what? Do you have to be connected Orange network (in France I assume?) or do you just need a login? 
This will probably be a very difficult plugin to make because I don't suppose many people have access to the service. If you know anyway that someone outside of France, without Orange can access it that would help a lot.

**Comment by kalimeroo** [comment]
The streams are availble from a web browser if you have an internet subscription with Orange network through login and password.
I guess the streams are georestricted to France as there is a /user/idzone.js script.
The streams are available at http://chaines-tv.orange.fr/
I can provide any file/infoormations if needed.

**Comment by karlo2105** [comment]
French proxy gives access to login field. Beardypig can't do anything without user and password. 
Could you post here an example of one stream from Orange TV ?

**Comment by kalimeroo** [comment]
I retrieve the stream from chrome cache Manifest file. For example I can play the following stream in VLC 
http://cdn.webtv4.cdnfr.orange.fr/mss/HALO3/ss/france2live-12471/mss/france2live.isml/Manifest?IS=0&ET=1487259981&CIP=194.254.245.85&KO=1&KN=4&US=63c306886517bb5fa5fe3ff7d953090e&SID=OTV-a5db7304-a1d0-4a93-91ac-3144e1cae9c9

**Comment by karlo2105** [comment]
That's HSS smooth streaming currently not supported by streamlink. 
Most of the time HLS is also provided along HSS. Try to sign in to Orange with changed User-Agent. You can do it through Modify Headers add-on : 

`https://addons.mozilla.org/fr/firefox/addon/modify-headers/`
`https://chrome.google.com/webstore/detail/modify-headers-for-google/innpjfdalfhpcoinfnehdnbkglpmogdi`

User-Agents
-------------

1. Ipad
--------
```
Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53
Mozilla/5.0 (iPad; U; CPU OS 3_2_2 like Mac OS X; de-de) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B500 Safari/531.21.10
```

2. Iphone
----------
`Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/546.10 (KHTML, like Gecko) Version/6.0 Mobile/7E18WD Safari/8536.25`

3. Android
-----------
`https://developer.chrome.com/multidevice/user-agent`

Streams are hidden mainly in **json**, **xml**, **ajax** pages and seldom in page source code . 
Only access is geolocked not stream itself. 
If you can't do it on your own maybe it's better to send user and pass to beardypig on PM.

**Comment by kalimeroo** [comment]
Thanks for the hints. I tried with fake user-agent but the stream is always in HSS smooth streaming format.
I'll try sniffing from mobile device.

**Comment by karlo2105** [comment]
One more Firefox Add-on for HTTP monitoring : 
`https://addons.mozilla.org/fr/firefox/addon/httpfox/`

You can sniff stream addresses with following programs : 

1. URL Snooper : Windows Only
---------------------------------
`https://www.donationcoder.com/Software/Mouser/urlsnooper/`

2. Wireshark : multiplatform 
-----------------------------
`https://www.wireshark.org/`

Wireshark is open source multiplatform powerful software for traffic monitoring. 
Here you can find some tips to retrieve live streams with : 

- `https://ask.wireshark.org/questions/29730/wireshark-filter-for-finding-url-of-live-stream-video`
- `https://ask.wireshark.org/questions/34703/how-to-capture-video-streaming-url`

I managed to launch HSS stream from Orange TV in VLC, which means it's not geoblocked nor encrypted.
They stream in 720p. VLC doesn't manage well multibitrate streams that's why HSS is not watchable in this player.

**Comment by kalimeroo** [comment]
Hi,

I sniffed the http requests (with https://portswigger.net/) from my mobile phone but aaparently the app does not play videos when behind a proxy. 
However the app sends a GET request for the following m3u8 file (I am able to download the m3u8 nut access authorization seems limited in time)

https://tvsl21.orange.fr/t1/live/Arte_Live/index.m3u8?authKey=PMbVmDUSfRSbZ6qqCG0WNbbBqNtjoiXYgCSIFgKNo8dl07jRYo0d_B7gI9K8npx8zS4tDF2GZZIaoKi321hqRUucw65ySeeez5vHhrFqjdZSbKS8IDkqA0HJH_T626JqQmu1BlKKz81X7aG2fxkYmbzv3HBQo7hjM7xlDeHtPmaeS1v-fK3JxmJGC1WpwYf6iq8VA8zr5LCo4fQ6GBrQxAM7RyBuC4nYuJ0SIcnkXhXvSHBqQ8PvORx0HRf2fwDmGVuoQsnCyJCuSibtMH3hHhztCzyZwEgVDEtkenEMqd8nlJDfu6KGjtqfPFbrJwUiPCpu2TcTyeVUo0gYRPSqUCD6Q7htJbVvrdVqpTdNmiYtLq6JpvhqczBNWShOaZd2&bearer=WIFI&sid=OTV-8df8f0b3-092b-4727-89c4-d6374f6c55a0__1256932__livetv_arte__97E7520D-8A62-BE9F-8B7F-ACA8283572F3-0B1ADEA6&catalog=OTV&deviceModel=MOB_ANDROID&AuthPolicy=2

I cannot play this file with vlc and Burp gives me alert "Failed to auto-select SSL parameters for tvsl21.orange.fr"

I'll try and solve this issue.

**Comment by WazZ87** [comment]
Hi,
It is interesting !

@kalimeroo, did you find something else ?

Imho, the "key" here is to find out how the `authKey` is generated !

When you generate a link like this one above, you should try a curl command to find if there are some interesting cookies that allows you to do some extra things that you can't do through the mobile/tablet app.

This specific command `~$curl -D - 'link orange'
`
I found a lot of interesting things with another isp but my skills in php are low so i can't really use them properly.

**Comment by kalimeroo** [comment]
Hi,

When I curl the address it gives me a 401 error.  But there indeed seems to be a cookie involved as a GET request is sent with Cookie: wassup=4564532.....
I tried several things but always ended up with errors. I guess this is way above my poor skills.

**Comment by WazZ87** [comment]
Hi @kalimeroo,

Well, back to "square one" i guess.

Did you try a packet capture like this one available on android
`https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=fr`

I'm not a big fan of that kind of app. if you didn't use it yet and you plan to do, i suggest you to take some preventive measures.

Like using a smartphone that you don't really care with a fresh install without any data, with a fresh or a existant gmail account that you don't care too.

Then change your password account (orange) with a temporary one before using the packet capture.

Not very comfortable with this app but it's really powerful, i can tell you that.

With this app, you'll found out how the whole authentification process works.

Let me know if it helps you.

**Comment by kalimeroo** [comment]
I indeed used the app to sniff the network traffic.
-

**Comment by WazZ87** [comment]
Hi,

No problem Sir !
I'm not here to bothered you, at all !

Just to let you know that i found how the authentification process works.

There is 9 steps before using the cookie wassup + another one (only wassup cookie to request a channel and get a valid link)

Anyway, sorry and good luck.

**Comment by kalimeroo** [comment]
Oops. Sorry It was not intended to be bold and offensive (I sent it from my phone), I thank you for your hints and advices.
Bravo for finding how the authentification process works. I certainly could not figure out those 9 steps.

**Comment by amurzeau** [comment]
As a side note, orange use Play Ready protected content.
VLC 3 seems to understand HSS streams but not encrypted ones (so it does not work here)

I have made tests on orange stream and made a [small script](https://gist.github.com/amurzeau/5923059ccf97a022ba6295d8f2aac780) to dump audio but this is not working as the stream is encrypted.
This might help one who would want to support un-encrypted HSS streams.

**Comment by campones** [comment]
i could sniff on my android phone hls link but you need to login on their app (and be on their network) and anyway, links are pretty well encrypted like 

`https://tvsl18.orange.fr/t1/live/France2_Live/06.m3u8?bearer=WIFI&sid=OTV-a67e0f09-9e46-409e-98a7-0980827c1b9a__87949441__livetv_france2__E4EB1676-2517-C82D-02CF-38FA0B5E58B6-A6288AA9_7125a8cd521a00010000196f_MOB_ANDROID_DRM-SW`

**Comment by sweetsugarh** [comment]
The problem as amurzeau said is so Orange.tv uses PlayReady DRM from Microsoft and to decrypt it you need the key. They encrypt the file before the stream then I don't know how you can get their key to decrypt it. I think will be hard to get a solution for this

**Comment by back-to** [comment]
seems like all the last answer mention DRM,
as this won't work with Streamlink, I close this issue.

**Comment by amidevous** [comment]
> 
> 
> I retrieve the stream from chrome cache Manifest file. For example I can play the following stream in VLC
> http://cdn.webtv4.cdnfr.orange.fr/mss/HALO3/ss/france2live-12471/mss/france2live.isml/Manifest?IS=0&ET=1487259981&CIP=194.254.245.85&KO=1&KN=4&US=63c306886517bb5fa5fe3ff7d953090e&SID=OTV-a5db7304-a1d0-4a93-91ac-3144e1cae9c9

just convert url to hsl

http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/france2live-12471/hls/index.m3u8

**Comment by campones** [comment]
> > I retrieve the stream from chrome cache Manifest file. For example I can play the following stream in VLC
> > http://cdn.webtv4.cdnfr.orange.fr/mss/HALO3/ss/france2live-12471/mss/france2live.isml/Manifest?IS=0&ET=1487259981&CIP=194.254.245.85&KO=1&KN=4&US=63c306886517bb5fa5fe3ff7d953090e&SID=OTV-a5db7304-a1d0-4a93-91ac-3144e1cae9c9
> 
> just convert url to hsl
> 
> http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/france2live-12471/hls/index.m3u8

could you please share all the links as I m not in france and not able to actually convert them without accessing the francetv site

**Comment by campones** [comment]
I don't get an mss streaming url when using chrome, instead a dash url. (using ubuntu 14 and some old chrome release)

Request URL: https://livefrancetv.akamaized.net/simulcast/France_3/dash/ZXhwPTE2MDA3NDQ3OTZ+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8zJTJmZGFzaCp+aG1hYz00Y2I4MTU2OGUwYTg1NGUyYzFmMTUzOWM5Mzg5ZTUyYzRmZGY1MjM2MzYyY2ZiMmYyZjEzOTBhNzA4ZDNmOTUy/France_3.mpd

**Comment by campones** [comment]
Hi 
Now it looks like this so I guess..  nothing can be done! 

https://cdn.ott-na-live-rti.cdnfr.orange.fr/TrYS2EaBKiv-bm6xZGlDgx_KZs8/1-64/1/1672457003/OTV-967ad91d-6a7f-4cdf-aa7b-66bdaf845e08/bpk-tv/livetv_france2_ctv/DASH-CE/index.mpd?bpk-service=Live&device=pc&delay=0&minrate=416000&maxrate=3400000&subtitle=allin

error: https://cdn.ott-na-live-rti.cdnfr.orange.fr/TrYS2EaBKiv-bm6xZGlDgx_KZs8/1-64/1/1672457003/OTV-967ad91d-6a7f-4cdf-aa7b-66bdaf845e08/bpk-tv/livetv_france2_ctv/DASH-CE/index.mpd?bpk-service=Live&device=pc&delay=0&minrate=416000&maxrate=3400000&subtitle=allin is protected by DRM
