### ISSUE TITLE
tvr.by : Belarus public service

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#589]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Belarus public service consists of 5 channels aired on their website : `http://www.tvr.by`
RTMP and HLS protocol are used. Belarus 1 and Belarus 24 are available abroad, for others it's Belarus only. 

- Belarus 1 : `http://www.tvr.by/televidenie/belarus-1/`
- Belarus 2 : `http://www.tvr.by/televidenie/belarus-2/`
- Belarus 3 : `http://www.tvr.by/televidenie/belarus-3/`
- Belarus 5 : `http://www.tvr.by/televidenie/belarus-5/`
- Belarus 24 : `http://www.tvr.by/televidenie/belarus-24/`

### Expected / Actual behavior

Stream addresses are located in page source : 

- Belarus 1 : 
`http://live.streaming.hoster.by:1935/belarus1/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDI6MTcgUE0maGFzaF92YWx1ZT1zUXJ3OElLWXk4ZUhkOXpSM0I0K3lRPT0mdmFsaWRtaW51dGVzPTEyMA==`

- Belarus 2 : 
`http://live.streaming.hoster.by:1935/belarus2/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDY6MDkgUE0maGFzaF92YWx1ZT12K3pOK2JQSGRYR3hhcFBkQ3Q4NmxRPT0mdmFsaWRtaW51dGVzPTEyMA==`

- Belarus 3 : 
`http://video.tvr.by:1935/belarus3/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDc6MjQgUE0maGFzaF92YWx1ZT1QVUYwSCtiVFBNSUtpOTdESUJMbHRBPT0mdmFsaWRtaW51dGVzPTEyMA==`

- Belarus 5 : 
`rtmp://live.streaming.hoster.by:1935/belarus5?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDg6MDAgUE0maGFzaF92YWx1ZT0vRnZDQXRIY3c2TGNGWlJUOU1PNEVnPT0mdmFsaWRtaW51dGVzPTEyMA==///live&amp;debug=1&amp;m=video&amp;st=6N9MnjRHG54ZkxsHvC9j0IoN0FJ5GxW8nj7pn5w5kHnenjEHvC91UaF8kSnetSlNvC97UaJBnjRHtS9JvC9BUxz4GdFI31EHOHnsk5JBGCAD3a4ekQbLtQTLPjWHPHn8n5hLGdM46SnetCVHGNneyQAVvC9j0azMkxmbU5Gh0iuRUQnHOjA8n59zk5k43Iy4UNnetNVHUamb35WXG5J8U5FN0d4BkSne6N9cnjRatib8n5yL0IoN0aW1njRH3dWh6SWb2xz4fcu8UfZ80d4BkSWa0aWz0xY8G5J8U5FN0d4BkSW5GxW8viybUf9bvd9zk5k43HWNGxmXG5J8Gxz4nHVH05JbkfyHkayL0dJNnjRHtCn8n5DHOjTbyCVH3ayNkxwBUaJ80cnHOHnWy19HOSn8n5Wh053HOH9NGSn8n5yBGi98fcybUf9bnj7pn59IfcyRnjRHtSn8n59InjRHtSn8n59IfaEHOjABtQwJvC912dJc05FMkSnetSVH3i9LnjRWvC9j0IoN0d9IUaJ80cnHOHnVXgAHvC9BUxz4GdFI31nHOHnsvan+PCJ50ambPHn8n5yBGi98fc9z04Ja0aWz0xYHOI8HUaJ80cnHOH95k5k5k5UHXSVH3a4ZnjRHtjtlvQDbtHn8n59IUaJ80cnHOH95k5k5k5UHXTrr`

In the past Belarus 5 also used HLS streaming method, I wonder why did they switch to rtmp. 

- Belarus 24 : 
`http://video.tvr.by:1935/belarus24/live/playlist.m3u8`

### Reproduction steps / Stream URLs to test

RTMP
------
```
rtmpdump -r "rtmp://live.streaming.hoster.by:1935/belarus1" -a "belarus1?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDg6MDk6MDkgUE0maGFzaF92YWx1ZT1Rc1FETXhZYkFQRkIxV1BpN0c2eXpBPT0mdmFsaWRtaW51dGVzPTEyMA==" -f "WIN 24,0,0,221" -W "http://www.tvr.by/plugines/uppod/uppod.swf" -p "http://www.tvr.by/televidenie/belarus-1/" -y "live" | %systemdrive%\progra~1\videolan\vlc\vlc -
RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: You haven't specified an output file (-o filename), using stdout
Connecting ...
INFO: Connected...
Starting download at: 0.000 kB
INFO: Metadata:
INFO: trackinfo:
INFO:   language                und
INFO:   timescale               12800.00
INFO:   length                  46715904.00
INFO: sampledescription:
INFO:   sampletype              avc1
INFO:   language                und
INFO:   timescale               44100.00
INFO:   length                  160957440.00
INFO: sampledescription:
INFO:   sampletype              mp4a
INFO:   audiochannels           2.00
INFO:   audiosamplerate         44100.00
INFO:   videoframerate          25.00
INFO:   aacaot                  2.00
INFO:   avclevel                31.00
INFO:   avcprofile              100.00
INFO:   audiocodecid            mp4a
INFO:   videocodecid            avc1
INFO:   width                   788.00
INFO:   height                  576.00
INFO:   frameWidth              788.00
INFO:   frameHeight             576.00
INFO:   displayWidth            788.00
INFO:   displayHeight           576.00
INFO:   framerate               25.00
INFO:   moovposition            524272534.00
8768.223 kB / 62.42 sec
ERROR: Download: Failed writing, exiting!
```

HLS
----
```
streamlink "hlsvariant://http://live.streaming.hoster.by:1935/belarus1/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDI6MTcgUE0maGFzaF92YWx1ZT1zUXJ3OElLWXk4ZUhkOXpSM0I0K3lRPT0mdmFsaWRtaW51dGVzPTEyMA==" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://live.streaming.hoster.by:1935/belarus1/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDc6NDI6MTcgUE0maGFzaF92YWx1ZT1zUXJ3OElLWXk4ZUhkOXpSM0I0K3lRPT0mdmFsaWRtaW51dGVzPTEyMA==
[cli][info] Available streams: 576p (worst, best)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
```

### Environment details (operating system, python version, etc.)

Windows 7 PRO/Python 2.7.13

### Comments, logs, screenshots, etc.

RTMP command was sniffed with rtmpdumphelper : `http://www.nirsoft.net/utils/rtmp_dump_helper.html`

**Comment by gravyboat** [comment]
@karlo2105 Do you actually end up watching all these channels that are filed as plugin requests? Your viewing experience is far more broad than my own if so!

**Comment by karlo2105** [comment]
In the past when Adobe flash was spreaded i was hunting for rtmp streams, it used to be my hobby how to dump rtmp. I used to spend more time to dump rtmp than to watch channels. 
After i discovered livestreamer which provided pipe to vlc and i was after m3u8. I managed to find pycrypto for windows and chrippa included decoding support.
Honestly I don't watch much TV only sports sometimes football mostly. French ans Swiss plugins are very valuable to me.
But i thought that it could interest somebody that's why i filled up form for those plugins. :)
I am grateful to developers for plugins and enhancements.
When i have spare time i make different tests.

**Comment by gravyboat** [comment]
@karlo2105 Thanks for the history! I appreciate you putting these in and providing so many details to make plugin development easier for us. Know that your contributions are greatly appreciated and just as valuable as the work anyone else is doing.

**Comment by beardypig** [comment]
Again @karlo2105, a very good plugin request :) 

I have created a plugin to extract the streams. However, the `rtmp` streams don't play in the latest `VLC 3.0.0-beta`, but they do play in `VLC 2.2.4`, and `mpv`.

**Comment by karlo2105** [comment]
Do you mean vlc 3.0.0 beta can't pipe rtmp through rtmpdump ?

**Comment by beardypig** [comment]
I mean, those specific rtmp streams don't play video when they are piped in to VLC 3.0.0. 

```
rtmpdump -r "rtmp://live.streaming.hoster.by:1935/belarus1" -a "belarus1?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNS8yMDE3IDg6MDk6MDkgUE0maGFzaF92YWx1ZT1Rc1FETXhZYkFQRkIxV1BpN0c2eXpBPT0mdmFsaWRtaW51dGVzPTEyMA==" -f "WIN 24,0,0,221" -W "http://www.tvr.by/plugines/uppod/uppod.swf" -p "http://www.tvr.by/televidenie/belarus-1/" -y "live"  | vlc  -
```

Just plays the audio, not the video. There are loads of repeated errors in the VLC console:
```
videotoolbox decoder error: decoder failure: bad data (-12909)
videotoolbox decoder error: decoder failure: bad data (-12909)
videotoolbox decoder error: decoder failure: bad data (-12909)
```

**Comment by karlo2105** [comment]
If it works with VLC 2.2.4, it's ok. 
VLC 3.0 is not yet ready to be released. ;)

**Comment by beardypig** [comment]
I suppose... PR en route.

**Comment by gravyboat** [comment]
Closing since https://github.com/streamlink/streamlink/pull/591 is now merged.
