### ISSUE TITLE
Rewind or "--hls-live-restart" with Twitch to save live streams from the beginning

### ISSUE THREAD

**Issue by superbonaci** [streamlink/streamlink#5891]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.7.0

### Description

Source issue: https://github.com/mrwnwttk/livestream_scripts/issues/4
Using https://formulae.brew.sh/formula/streamlink#default

Using the script to save a Twitch stream that has been live for some time does save the stream from that point, but doesn't save it entirely from the beginning.

Maybe it's not possible to use the rewind feature with Twitch?

### Debug log

```text
not needed.
```

**Comment by gravyboat** [comment]
This isn't a bug. You're starting the stream from whatever the currently being streamed segment is. If you want to download from the start you need to use the VOD URL (and even then I don't know if Twitch updates the VOD any more as the stream continues onwards so you may have to wait till the stream is over if you want to watch everything). Closing.

**Comment by superbonaci** [comment]
To download the BOD once the stream has finished, I use this tool: https://github.com/lay295/TwitchDownloader but the issue is those streams that are not saved to Twitch once the stream finishes and at the same time you start recording the stream once it's been live for a while. that portion is lost.
