### ISSUE TITLE
Should we disable CLI version check by default?

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#590]
### Checklist

- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Prior to upgrading to streamlink `0.3.2` I noticed on Windows when I was launching a stream from the CLI there's a short pause while Streamlink is checking for a new version where this message pops up:
`[cli][info] A new version of Streamlink (0.3.2) is available!`. I think we should discuss removal of this notice, or allow users to decide if they want to enable it for privacy purposes. I know it's not a huge deal but some users may not wish to ping an external service other than the site they are trying to load.

### Reproduction steps / Stream URLs to test

1. Install an older version of Streamlink.
2. Load a stream up via the CLI.

**Comment by beardypig** [comment]
Would you want a flag to enable the automatic version checking? 
Currently there is `--no-version-check`, which disable the automatic checking, and `--version-check` which checks for a new version and exits. Do we add a new flag `--auto-version-check`? and always set `no_version_check=True`?

**Comment by bastimeyer** [comment]
Can't `--no-version-check` be turned into a boolean parameter, so it can be turned off by setting `--no-version-check=false` or `--no-version-check false`, so that a new parameter is not required?
Then I'd suggest setting `--no-version-check` to true on *nix systems (when installed via a package manager) and adding a checkbox to the windows installer and writing it to the config file.

**Comment by beardypig** [comment]
It's a bit tricky to modify `--no-version-check` as it currently expects no arguments, could cause some issues.

**Comment by fishscene** [comment]
Just a thought:

- On embedded systems such as RPI, version-checking on startup isn't necessary unless something goes wrong or there's a security issue (which should probably be manually updated anyway). Overall, it just adds a delay to getting to the requested content every time it is called.
- On actively maintained systems, it's nice to know when there's an update, but if other applications depend on streamlink (such as streamlink-gui), they may not support the newest version yet. When they update, they can then run a version check on streamlink to see if a supported one is installed, if not, they can request the user for an updated version.

With this in mind,
What if we disabled the version check on startup on all platforms and if a plugin fails to tap into a stream or there's another error, it either:
A) Automatically runs a version check to see if there's an update to possibly fix the error. We can also spit out the currently installed version number to make it easier - just in case something goes wrong with the version check. Would need some kind of gated version checking so a quick succession of failures doesn't spam the update servers.
or
B) Let the end-user manually check for an update if there's an error tapping into the stream or another error, by suggesting to run <commands: pip/linux/windows/update website> to see if there's an update. We can also spit out the currently installed version number to make it easier.

Thoughts?

**Comment by paramec** [comment]
I also see 2 thing here: 
1. Leave the things as they are at the moment. If somebody (like me for example) wants to execute with no waiting time, then you should use the option  --no version-check.
2. For the future builds maybe the "creator" should think to implement the version check feature in a parallel process not to delay the program execution.

**Comment by karlo2105** [comment]
I added in beardypig streamlink portable **streamlink.bat** following switch `--no-version-check` which disables version check by default. 
I guess it should also work in streamlinkrc. If it works there too, then the only trick should be to update it and no need for deep modifications. 
What do you think ?

**Comment by gravyboat** [comment]
https://github.com/streamlink/streamlink/pull/611 is proposed as a possible option here.

**Comment by beardypig** [comment]
#611 covers the case for the Windows installer and possibly the portable Windows version. However, it doesn't cover the pip (Linux/macOS/Windows) installation methods. It also means that the line has to be removed from the configuration to re-enable the auto version check. 

I'm more in favour of suppressing the current `no-version-check` option and adding an explicit `auto-version-check=yes|no` option, which defaults to `no`.  That way if we want to change the default back to `yes` we can do so without a new option (like now). If the default if `no` then `no-version-check` will have no effect, or we could make `no-version-check` an alias for `auto-version-check=no`,  for continued future compatibility but still removing `no-version-check` for help/docs.

**Comment by gravyboat** [comment]
@beardypig Yeah I should have been more explicit in my note, was busy and just wanted to make sure it was mentioned here. I like your option idea.

**Comment by gravyboat** [comment]
Closing this since #630 was merged.
