### ISSUE TITLE
plugins.mangomolo: error: No plugin can handle URL

### ISSUE THREAD

**Issue by andaluspc** [streamlink/streamlink#5924]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

[cli][info] Your Streamlink version (6.7.2) is up to date!

### Description

Unable to get stream for Kuwaiti channels.. error message: "error: No plugin can handle URL:"
sample URLs:
 https://www.media.gov.kw/LiveTV.aspx
 https://www.media.gov.kw/LiveTV.aspx?PanChannel=Drama

### Debug log

```text
user@desktop:~ $ streamlink https://www.media.gov.kw/LiveTV.aspx --loglevel=debug
[cli][debug] OS:         Linux-6.1.21+-armv6l-with-glibc2.31
[cli][debug] Python:     3.9.2
[cli][debug] OpenSSL:    OpenSSL 1.1.1w  11 Sep 2023
[cli][debug] Streamlink: 6.7.2
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.7.22
[cli][debug]  exceptiongroup: 1.1.3
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.3
[cli][debug]  pycountry: 20.7.3
[cli][debug]  pycryptodome: 3.18.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.2
[cli][debug]  trio-websocket: 0.10.3
[cli][debug]  typing-extensions: 4.7.1
[cli][debug]  urllib3: 2.0.4
[cli][debug]  websocket-client: 1.6.2
[cli][debug] Arguments:
[cli][debug]  url=https://www.media.gov.kw/LiveTV.aspx
[cli][debug]  --loglevel=debug
error: No plugin can handle URL: https://www.media.gov.kw/LiveTV.aspx
```

**Comment by bastimeyer** [comment]
Remove the `www.`

https://github.com/streamlink/streamlink/blob/d396db4588a8adf5ef5ca4e1268b23851cc89fdb/src/streamlink/plugins/mangomolo.py#L27

> [cli][debug] Streamlink: 6.7.2

Outdated. The plugin was updated the the missing `Referer` header in #5923, which isn't part of a stable release yet.
