### ISSUE TITLE
API ,streams attribute dosen't exist when run in the py  

### ISSUE THREAD

**Issue by CN-CODEGOD** [streamlink/streamlink#5927]
### Checklist

- [X] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

6.7.1
### Description

i want to use the  streamlink.streams( URL ) api to get the link ,it work well when i using it in the python session ,but when i use 
& "F:\streamlink\venvs\streamlink\Scripts\python.exe" streamlink.py ,it occured that the streams attribute dosen't exist,and i couldn't figure out why 

### Debug log

```text
Traceback (most recent call last):
  File "C:\Users\34683\py\streamlink.py", line 1, in <module>
    import streamlink
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\34683\py\streamlink.py", line 2, in <module>
    streams = streamlink.streams("hls://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8")
              ^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'streamlink' has no attribute 'streams' (most likely due to a circular import)
```

**Comment by bastimeyer** [comment]
> partially initialized module

Not a Streamlink issue.

Literally [the first result on google](https://www.google.com/search?q=AttributeError%3A+partially+initialized+module):
https://stackoverflow.com/questions/59762996/how-to-fix-attributeerror-partially-initialized-module
