### ISSUE TITLE
plugins.NimoTV: only watched for a very short time

### ISSUE THREAD

**Issue by prpjzz** [streamlink/streamlink#5928]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.7.2+13.gf43d0eb

### Description

Specifically, the steps I took:

1. Open Terminal
2. run command: `streamlink https://www.nimo.tv/tuitenbo 480p,best,worst --config=C:/mpv/streamlink.conf`
3. MPV open, but I watched it in less than 10 seconds and it ended and didn't go on.

My streamlink config:

> title={author} - {category} - {title} - {url}
#http-header=User-Agent=Mozilla/5.0 (Nintendo Switch; WebApplet) AppleWebKit/609.4 (KHTML, like Gecko) NF/6.0.2.21.3 NintendoBrowser/5.1.0.22474
http-header=User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
#twitch-api-header=Client-ID=ue6666qo983tsx6so1t0vnawi233wa
http-no-ssl-verify
#twitch-proxy-playlist=https://as.luminous.dev,https://lb-as.cdn-perfprod.com,https://eu.luminous.dev,https://eu2.luminous.dev,https://lb-eu.cdn-perfprod.com,https://lb-eu2.cdn-perfprod.com,https://lb-eu3.cdn-perfprod.com,https://lb-eu4.cdn-perfprod.com,https://lb-eu5.cdn-perfprod.com,https://lb-na.cdn-perfprod.com
#,https://api.ttv.lol
#twitch-ttvlol
#twitch-reexec-on-ad
twitch-disable-ads
twitch-low-latency
#loglevel=none
#player-fifo
stream-segment-attempts=1
stream-segment-threads=5
stream-segment-timeout=10.0
#stream-timeout=10.0
#mux-subtitles
player-no-close
player=C:\mpv\mpv.exe

### Debug log

```text
[session][debug] Loading plugin: nimotv
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.18+
[cli][debug] OpenSSL:    OpenSSL 1.1.1w  11 Sep 2023
[cli][debug] Streamlink: 6.7.2+13.gf43d0eb
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  exceptiongroup: 1.2.0
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.1.0
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.25.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.10.0
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.nimo.tv/tuitenbo
[cli][debug]  stream=['480p', 'best', 'worst']
[cli][debug]  --config=['C:/mpv/streamlink.conf']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\mpv\mpv.exe
[cli][debug]  --player-no-close=True
[cli][debug]  --title={author} - {category} - {title} - {url}
[cli][debug]  --stream-segment-attempts=1
[cli][debug]  --stream-segment-threads=5
[cli][debug]  --stream-segment-timeout=10.0
[cli][debug]  --http-header=[('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'), ('Referer', 'https://www.nimo.tv/')]
[cli][debug]  --http-no-ssl-verify=False
[cli][debug]  --twitch-disable-ads=True
[cli][debug]  --twitch-low-latency=True
[cli][info] Found matching plugin nimotv for URL https://www.nimo.tv/tuitenbo
[warnings][insecurerequestwarning] Unverified HTTPS request is being made to host 'm.nimo.tv'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  C:\mpv\streamlink\pkgs\urllib3\connectionpool.py:1103
[plugins.nimotv][debug] URL=http://tx.flv.nimo.tv/backsrc/su1629511896446r325d3b91acf6afd222f53d5ee8c02b04.flv
[cli][info] Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 480p (http)
[cli][info] Starting player: C:\mpv\mpv.exe
[cli][debug] Pre-buffering 8192 bytes
[cli.output][debug] Opening subprocess: ['C:\\mpv\\mpv.exe', '--force-media-title=TUITÊNBÔ - GTA5 - A Lớn Cao Lãnhhhhhhhhhhh - https://www.nimo.tv/tuitenbo', '-']
[cli][debug] Writing stream to output
[cli][info] Stream ended
```

**Comment by mkbloke** [comment]
Try the [`--player-no-close`](https://streamlink.github.io/cli.html#cmdoption-player-no-close) option.

**Comment by mkbloke** [comment]
Not the problem I thought it was - I assumed this was a short video clip.

**Comment by prpjzz** [comment]
It seems that they changed the mode of streaming in February or March this year.

**Comment by nhathoang24** [comment]
same issue here!

**Comment by prpjzz** [comment]
I found this in Developer Console:
![image](https://github.com/streamlink/streamlink/assets/89702898/5da040e9-9092-492e-bf5c-1b1c9e2d26bb)

Link video like this:
`https://al.flv.nimo.tv/backsrc/su1599517287247r6ddf0a381e4e0fa45a5392ec0ff74b4d.flv?wsSecret=1e93ad4f0218c61180a5e98523e97752&wsTime=661d4217&seqid=3352622084967&ctype=nimo_web&ver=1&appid=81&tp=1713107095174&needwm=1&sphd=1&ratio=1000&dMod=mseh-0&sdkPcdn=1_1&u=1638999155386&t=100&sv=2310101948&sdk_sid=1713108754816`

Specifically, some more fields will be needed to be able to run normally and without unexpected stops.

**Comment by thanhlouis** [comment]
> I found this in Developer Console: ![image](https://private-user-images.githubusercontent.com/89702898/322286006-5da040e9-9092-492e-bf5c-1b1c9e2d26bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTU3MjksIm5iZiI6MTcxMzExNTQyOSwicGF0aCI6Ii84OTcwMjg5OC8zMjIyODYwMDYtNWRhMDQwZTktOTA5Mi00OTJlLWJmNWMtMWIxYzllMmQyNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE3MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlYjkwNzFjOTJjOTM2ZTNjMTk3OTdiMjJmNTk1MDhkMzQ2ZDI1MTRlNGQ0NzY3OWJiNGVhYjcwMmRiMjEyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4_lo6trQTJ4jpLW4py6y0tVG6aShQ-6KHI_1QGJ6uZw)
> 
> Link video like this: `https://al.flv.nimo.tv/backsrc/su1599517287247r6ddf0a381e4e0fa45a5392ec0ff74b4d.flv?wsSecret=1e93ad4f0218c61180a5e98523e97752&wsTime=661d4217&seqid=3352622084967&ctype=nimo_web&ver=1&appid=81&tp=1713107095174&needwm=1&sphd=1&ratio=1000&dMod=mseh-0&sdkPcdn=1_1&u=1638999155386&t=100&sv=2310101948&sdk_sid=1713108754816`
> 
> Specifically, some more fields will be needed to be able to run normally and without unexpected stops.

Nó cần thêm thông số như u= với cái gì nữa bữa mò mà quên rồi, nó lấy trong javascript ấy, phải khớp cả 2 thông số đó lúc bắt đầu lấy link mới được nhưng t lại k đọc hiểu js nên chịu. Bữa giờ coi toàn lấy bằng tay không :))))

**Comment by bastimeyer** [comment]
Please keep the comments in English. This is an international community of users. If you don't speak English or if you're having trouble posting, then use a translation service like Google Translate, DeepL, etc.

**Comment by bastimeyer** [comment]
Closing this issue in favor of #5870
