### ISSUE TITLE
Feature : Proxy for api access only

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#594]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Some streaming services restrict geographically only access to their live/vod videos but streams themselves remain unblocked. 
It would be interesting to add feature such as : 

```
--http-proxy-api
--https-proxy-api
```

### Expected / Actual behavior

It should apply only to bypass geographical restriction to access cookies or tokens for those streams which would allow to use maximum speed and avoid proxies flaws on streaming. 

### Reproduction steps / Stream URLs to test

For instance : 

Without proxy but TS is unblocked
------------------------------------

```
streamlink "hlsvariant://http://live3.msf.ticdn.it/Content/HLS/Live/Channel(CH09HA)/index.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://live3.msf.t
icdn.it/Content/HLS/Live/Channel(CH09HA)/index.m3u8
[cli][info] Available streams: 122k (worst), 144p, 288p, 432p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[stream.hls][error] Failed to create decryptor: Unable to open URL: http://lic.m
ediaset.net/IOS/IOSLicenser?kid=7a440bb3-9716-4792-88e5-ac1dcdf3523c (403 Client
 Error: Forbidden for url: http://lic.mediaset.net/IOS/IOSLicenser?kid=7a440bb3-
9716-4792-88e5-ac1dcdf3523c)
```

With proxy
------------
```
streamlink --http-proxy "94.177.198.64:8080" "hlsvariant://http://live3.msf.ticdn.it/Content/HLS/Live/Channel(CH09HA)/index.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://live3.msf.t
icdn.it/Content/HLS/Live/Channel(CH09HA)/index.m3u8
[cli][info] Available streams: 122k (worst), 144p, 288p, 432p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

As you can see only access to decryption server is geoblocked.

**Comment by gravyboat** [comment]
Hmm, I think this feature would require some discussion. I'm not sure we want to directly support proxies in this manner. It could lead us down a path where organizations come after us for bypassing their geo-restrictions (as stupid as all that nonsense is).

**Comment by karlo2105** [comment]
General proxy switch also bypass restrictions. All services developed in plugins are available free and bypassing geo-restriction has never been illegal.

**Comment by back-to** [comment]
@karlo2105  
i'm not geo blocked to your `.m3u8` url, so i can't test it.

**Don't try this with streams where you need an authentication,
they might ban you for different ips.** 

---

here is just a testcode

change in **src/streamlink/stream/hls.py**

```diff
diff --git a/src/streamlink/stream/hls.py b/src/streamlink/stream/hls.py
index e3c8fe1..a5e5eac 100644
--- a/src/streamlink/stream/hls.py
+++ b/src/streamlink/stream/hls.py
@@ -75,11 +75,16 @@ class HLSStreamWriter(SegmentedStreamWriter):
 
         try:
             request_params = self.create_request_params(sequence)
-            return self.session.http.get(sequence.segment.uri,
+
+            temp_proxys = self.session.http.proxies
+            self.session.http.proxies = {}
+            res = self.session.http.get(sequence.segment.uri,
                                          timeout=self.timeout,
                                          exception=StreamError,
                                          retries=self.retries,
                                          **request_params)
+            self.session.http.proxies = temp_proxys
+            return res
         except StreamError as err:
             self.logger.error("Failed to open segment {0}: {1}", sequence.num, err)
             return
```

**Comment by karlo2105** [comment]
@back-to 
Those Italian channels work now without proxy as server with aes keys is not geoblocked anymore. 
If I find another example I shall test it with your patch and post results here.

**Comment by back-to** [comment]
It's to rare and not really worth it,
just use the normal proxy for everything.

Closing.

**Comment by Cohinem** [comment]
this is sad..
