### ISSUE TITLE
https://tvbanywherena.com/cantonese/live/tvb-j1

### ISSUE THREAD

**Issue by WaiRachL** [streamlink/streamlink#5940]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

TVB J1
https://tvbanywherena.com/cantonese/live/tvb-j1

NO Geo Block Actually, USA, Malaysia can watch

### Input URLs

https://bcovlive-a.akamaihd.net/e360e3f9895c4fae99b133ec8dc20f01/us-west-2/5324042807001/4a3bca5b047b4564b18bb12dfa26ba62/playlist_ssaiM.m3u8?givn=AQzzBGQEGHJZUX7qqv84kmyifONZTBlXjIjc1ZqqtrtW4DXYLULdpGQTdFpuaUzMUuLNekkL7_xNnmxo-6tzD_4SD3OPSw-CjqXG4fAxVmqCg95OElQP9Tzdn6-x4ocAfU2U_wt-A_wry92DT2J96imitqdRg_-y8NHWidK32rYZEsyzilPfMXVFO0Mk8d7PIkzubyC-Km2ojTGeP_8y92p9SWG4d0LgmKcRmDd1OYaAkRW0g0_BPJBdIFsdLo1TS1WR9Yrq4hPXCTwkWAnX9dhaeGLrYeU_VDc6iWmMkSMYrQcu8k-iq1A1Mm899xF7U8Cc66OnTmStf9_BVefwkjZjBXYdNQW0t2BiQCF74_pNW-TsvjjvrwvN0d7yiF1Nw-u1WfAc-mwTKk3i6FNxGt4eSceqPxj-m3MBRpC0q-vn6GXA5UpE6ngs5aVkobXfSTnoeLt_4R1EmR0hS0ncHx9xayUvd2_3iSbH4GRRJwQIoft5sp_fQoTwjR13UO8-pa99ocDI7XEEuxi3qalAYnmIi6G4GUNy9vmJDwsr9Rk3AYTWqpcqWgq1f_oRvtVkFUxWIES7Yc9mdp4eS6A8QTOyW_lvdHYUBT0smM6YOgXimYWQRheIgFAB1uwBHBoftTKTvtcLm-zzrvU0tdPUpELJRUtwQheE_b8B0MhZEOTzXq_Gw0yBYFOkWydmt1Js3S_DJpFVbetyzKJdogKe7FDTLTMBDnCF3xyHaGq_Qw8NVvieiK8-IlHVHGzjlUsiIGIaIpjBkoUuL6zGstXwQnJkVZEahMdeuu3KujGydGWG_o5rtkzYPV9iyegJp28c-ZGVCwV3uXx5kfkRf6TSN4LRxEnjOlsJxrreNq16ayE3KHKEV9w9yCx92Og2v7WsrvGE0IuxUU-dNFMQkZgjETMhyxSlmlixWX-EaZMGa8ngKxWSr8RfAfF-_1H4aOOwvvOgxkNoR75wj8RUxoevTAzkKqe5ezL_GzcYcjAOk9yXiUCvRDvrn_GJD8By-FKXpuIgsrDtkP-sDiZvhGEsjDNGYwl6yg5W19Ikj8jDClGP1tvQAyHn3IUtnhl5ggGTP0iJ0jv03tfD6Y0bKUXgBCjUWZL4PkPfUWYngraXAv-0m_xHrZvNWf4Ls-c9Gd9Bydl-GG5nmWP7JUWE4G1GSib7bD1zlwrp1LnjBHqrXQtXyZgnJ4DvxxYKyJ-QukZIfs448jedhkMBUmqVXJUyTy1CLnxSbb146xNaclEI_5Os5I-3YMqb

**Comment by bastimeyer** [comment]
Static HLS URL
```
https://bcovlive-a.akamaihd.net/e360e3f9895c4fae99b133ec8dc20f01/us-west-2/5324042807001/4a3bca5b047b4564b18bb12dfa26ba62/playlist_ssaiM.m3u8
```
