### ISSUE TITLE
plugins.youtube: `Could not get video info`

### ISSUE THREAD

**Issue by Puyodead1** [streamlink/streamlink#5941]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.7.3

### Description

Unable to watch live stream even though there is a live stream available.

I first tried `streamlink "https://www.youtube.com/watch?v=2sv7SA2Ybgg"` which results in `Could not get video info - OK: We're experiencing technical difficulties.`.

However removing this check https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py#L370-L373 it works fine 

### Debug log

```text
[session][debug] Loading plugin: youtube
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.3
[cli][debug] OpenSSL:    OpenSSL 1.1.1t  7 Feb 2023
[cli][debug] Streamlink: 6.7.3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  exceptiongroup: 1.1.1
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.0
[cli][debug]  trio-websocket: 0.10.2
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 1.26.18
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=2sv7SA2Ybgg
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=ffmpeg.exe
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=2sv7SA2Ybgg
[plugins.youtube][error] Could not get video info - OK: We're experiencing technical difficulties.
error: No playable streams found on this URL: https://www.youtube.com/watch?v=2sv7SA2Ybgg
```

With Modification to remove check:
```
[session][debug] Loading plugin: youtube
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.11.3
[cli][debug] OpenSSL:    OpenSSL 1.1.1t  7 Feb 2023
[cli][debug] Streamlink: 6.7.3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2023.5.7
[cli][debug]  exceptiongroup: 1.1.1
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 4.9.2
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.17
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.22.0
[cli][debug]  trio-websocket: 0.10.2
[cli][debug]  typing-extensions: 4.9.0
[cli][debug]  urllib3: 1.26.18
[cli][debug]  websocket-client: 1.5.1
[cli][debug] Arguments:
[cli][debug]  url=https://www.youtube.com/watch?v=2sv7SA2Ybgg
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=ffmpeg.exe
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=2sv7SA2Ybgg
[plugins.youtube][debug] Using video ID: 2sv7SA2Ybgg
[plugins.youtube][debug] This video is live.
[utils.l10n][debug] Language code: en_US
Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
```

**Comment by Puyodead1** [comment]
okay apparently that specific live stream really is having issues and was just replaying the last few seconds before dying. Sorry.

**Comment by bastimeyer** [comment]
Duplicate of #5350

That stream returns the following data:

```json
"playabilityStatus": {
    "status": "OK",
    "reason": "We're experiencing technical difficulties.",
    ...
},
```

See this relevant line which was added intentionally in #5351:
https://github.com/streamlink/streamlink/blame/6.7.3/src/streamlink/plugins/youtube.py#L351

> However removing this check [master/src/streamlink/plugins/youtube.py#L370-L373](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/youtube.py?rgh-link-date=2024-04-14T19%3A59%3A03Z#L370-L373) it works fine

No, it does not work, because the stream is broken. No new segments get added to the HLS playlist and the stream ends after 15 seconds. The stream is marked as online incorrectly. This is also the case on their website.
