### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by digitalcelery** [streamlink/streamlink#595]
Is there a way to unbind the port once streamlink is stopped? It takes sometimes up to a minute before the port can be used by some other process.

**Comment by gravyboat** [comment]
How are you exiting Streamlink?

**Comment by digitalcelery** [comment]
CTRL+c or kill -9 PID

**Comment by beardypig** [comment]
I take it you mean when using the http player option?

**Comment by digitalcelery** [comment]
Correct.

**Comment by beardypig** [comment]
There you go, I took a stab at it :)
