### ISSUE TITLE
Cannot install on Ubuntu 16.04

### ISSUE THREAD

**Issue by philiprenich** [streamlink/streamlink#596]
### Checklist

- [x] This is a bug report.

### Description

Cannot install Streamlink on Ubuntu 16.04 because python-cryptodomex is not available on this version. Apparently that dependency has unmet dependencies or was not updated to allow itself to get onto 16.04, just 14.04.

**Comment by beardypig** [comment]
Which method are you using to install streamlink?

**Comment by philiprenich** [comment]
Using the instructions from the site:


`add-apt-repository ppa:nilarimogard/webupd8`
`apt update`
`apt install streamlink`

I did not expect a response so quickly! Thanks!

**Comment by beardypig** [comment]
Ah OK, I think that package is maintained andrew@webupd8.org. I'm not sure why it depends on `python-cryptodomex` as it's not used, `cryptodomex` provides the `Cryptodome` module. `python-crypto` should be sufficient. Probably it's our fault for not updating the debian control files in our repo. I'll drop andrew an email and ask :)

**Comment by philiprenich** [comment]
@beardypig Thanks. If I'm understanding correctly, it's a simple fix, but there is _not_ an immediate work around I can implement at the moment?

**Comment by beardypig** [comment]
Should be a relatively simple fix for Andrew to do, but I'm not sure how their system is setup so it maybe be more complex. You could try (assuming you're after the Python 2.7 version):
```shell
# apt-get install python-backports-shutil-get-terminal-size python-backports-shutil-which python-concurrent.futures python-iso-639 python-iso3166 python-requests python-singledispatch
# apt-get install --nodeps python-streamlink streamlink
```

**Comment by gravyboat** [comment]
If you don't want to do the back porting you could also install via pip. That's what I've done for my Linux system, though I know not everyone prefers that method.

**Comment by hotice** [comment]
I cannot reproduce this issue. @philiprenich what exactly happens when you try to install ``streamlink``, and what if you try to install ``python-cryptodomex`` separately (``sudo apt install python-cryptodomex``)?

 ``python-cryptodomex`` is available in the WebUpd8 PPA.  Here's a screenshot that shows installing streamlink from the WebUpd8 PPA in Ubuntu 16.04 should work: http://i.imgur.com/ErhIjeW.jpg

**Comment by beardypig** [comment]
I was also unable to reproduce this, `streamlink` installed fine on a clean xenial VM.

**Comment by philiprenich** [comment]
@hotice Thanks for the help. Here is my command and output (I've already added the repo and updated)

```
$ sudo apt install streamlink
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 streamlink : Depends: python-streamlink (= 0.3.2-1~webupd8~xenial) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Similarly:
```
$ sudo apt install python-cryptodomex
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-cryptodomex is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-cryptodomex' has no installation candidate
```

Correct me if I'm wrong, but my Python looks to be within the acceptable range?
```
$ python --version
Python 2.7.12
```

While I do see streamlink using `apt-cache policy` I do not see python-cryptodomex
```
$ apt-cache policy python-cryptodomex
python-cryptodomex:
  Installed: (none)
  Candidate: (none)
  Version table:
```

I'm happy to keep helping with this if indeed it is a bug, but if you deem it to just be something on my end, no worries - I was able to patch the `livestreamer` Twitch plugin with an updated .py file so am able to accomplish what I was going for.

I did just get `pip` installed today for something else, so I may give that a go just to see what happens.

Thanks for all the help and responses!

**Comment by hotice** [comment]
@philiprenich could you try readding the PPA? Like this:
```
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt update
```

 ``python-cryptodomex`` is available in the PPA as you can see here: https://launchpad.net/~nilarimogard/+archive/ubuntu/webupd8/+packages?field.name_filter=python-cryptodomex&field.status_filter=published&field.series_filter=

So whatever is causing this issue, it is not related to the PPA packages.

**Comment by bastimeyer** [comment]
Does this issue still persist or can this be closed?

**Comment by philiprenich** [comment]
Let's close it. I never resolved it per day but my ubuntu box isn't working ATM. I'll create a new ticket if needed

Philip
