### ISSUE TITLE
cablecast.tv sites

### ISSUE THREAD

**Issue by glenviewjeff** [streamlink/streamlink#5965]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Description

Many government agencies use the cablecast.tv platform for streaming live and recorded video. The video is broken up into four-second .ts file chunks.

### Input URLs

https://wctv.wilmette.com/CablecastPublicSite/show/532
https://reflect-wctv-village-willmette.cablecast.tv/cablecastapi/embed?show_id=532

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-rules

> 6. **Sites which don't provide any real live-streaming content**
>
> For example VOD-only content or VODs being re-broadcasted.

**Comment by glenviewjeff** [comment]
I am not sure this plugin rule applies here. The site provides live streaming as well as re-broadcasted VOD.

https://wctv.wilmette.com/CablecastPublicSite/watch-now?site=1

**Comment by bastimeyer** [comment]
The live stream URL is hardcoded and doesn't require a plugin
```
$ streamlink 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8' best
[cli][info] Found matching plugin hls for URL https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8
[cli][info] Available streams: 540p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: /usr/bin/mpv
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by glenviewjeff** [comment]
I am actually in the process of using VLC to do the same at the moment; I didn't know that this tool and its plugins were not expected to find and use the existing m3u8 playlist given an http URL. That is the intended design and behavior of the tool, that users use devtools to manually find the playlist?

**Comment by bastimeyer** [comment]
https://streamlink.github.io/plugins.html

> The purpose of having plugins is to allow users of Streamlink to input URLs from specific websites or streaming services without knowing the actual stream URLs or implementations, while also automatically setting up certain HTTP session parameters or providing additional features via [CLI arguments](https://streamlink.github.io/cli.html#plugin-options), like authentication, skipping ads, enabling low latency streaming, etc.
> 
> In addition to the plugins listed below, any of the supported [streaming protocols](https://streamlink.github.io/cli/protocols.html#streaming-protocols) can be played directly, like for example HLS and DASH.

----

https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Before you request a plugin, please be aware that this will merely be a suggestion for the project maintainers (or anyone else) to have a look at the website and implement a new plugin for it. In the vast majority of cases, no one except you will initially have an interest in such a plugin, so you should think about whether it will be useful for other users of Streamlink.

Also

> 10. **Sites which have no way to determine viewership numbers**
> 
>     Plugins must not implement websites which are unused or which only have a handful of real/actual users.

**Comment by glenviewjeff** [comment]
I get that this is simply a suggestion/request and was under no impression that anyone is in any way obligated to adopt a site. Re: the numbers, I doubt I can find anything specific, but it seems to me that this cablecast.tv platform is almost certainly widely used by municipal governments in the US. https://www.cablecast.tv/blog-categories/customer-stories

**Comment by glenviewjeff** [comment]
Incidentally, I tried the command you suggested and instead got this output. Is there a setting to enable hls, or is this a sideloaded plugin?

```
streamlink 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8' best
error: No plugin can handle URL: 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8'
```

> The live stream URL is static/hardcoded and doesn't require a plugin
> 
> ```
> $ streamlink 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8' best
> [cli][info] Found matching plugin hls for URL https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8
> [cli][info] Available streams: 540p (worst), 1080p (best)
> [cli][info] Opening stream: 1080p (hls)
> [cli][info] Starting player: /usr/bin/mpv
> [cli][info] Player closed
> [cli][info] Stream ended
> [cli][info] Closing currently open stream...
> ```

**Comment by bastimeyer** [comment]
Check your streamlink install and make sure you're using the latest version (use `--loglevel=debug`). This is a regular HLS link with a `.m3u8` suffix in the URL's `path` part which gets mached by the `hls` plugin.

**Comment by glenviewjeff** [comment]
No big deal; I am using yt-dlp just fine and have no use for this tool, but for your own benefit, this was with a fresh install.

```
>streamlink --version
streamlink 6.7.3

> streamlink 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8' best --loglevel=debug
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.8.19+
[cli][debug] OpenSSL:    OpenSSL 1.1.1w  11 Sep 2023
[cli][debug] Streamlink: 6.7.3
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.2.2
[cli][debug]  exceptiongroup: 1.2.0
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.2.1
[cli][debug]  pycountry: 23.12.11
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.31.0
[cli][debug]  trio: 0.25.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.11.0
[cli][debug]  urllib3: 2.2.1
[cli][debug]  websocket-client: 1.7.0
[cli][debug] Arguments:
[cli][debug]  url='https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8'
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
error: No plugin can handle URL: 'https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8'
```

**Comment by bastimeyer** [comment]
> [cli][debug]  url='https://reflect-wctv-village-willmette.cablecast.tv/live-3/live/live.m3u8'

You have set `'` as part of the URL **value**, which is caused by your command line shell on Windows.
https://streamlink.github.io/cli/tutorial.html#shell-syntax
