### ISSUE TITLE
streamlink execution is taking very long time

### ISSUE THREAD

**Issue by paramec** [streamlink/streamlink#599]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
I'm typing  "streamlink" in the terminal and it's returning the expected output, but after more that 1 minute of waiting time. This is happening randomly. 
Sometimes after a computer restart, sometimes after a very long time of usability of the program.

After this, when I use again the program in the same manner everything is working fine. 

Any idea why I have this issue? 
Somebody can support me to discover what is the reasons for this big waiting time? 

This is not happening with other programs.  

### Environment details (operating system, python version, etc.)
Archlinux x86_64 with the latest  kernel
Python 2.7 and 3.6  

Many thanks in advance.

**Comment by beardypig** [comment]
Thanks for the well formatted report :) 

Could you try
```bash
rm ~/.cache/streamlink/cli.json
streamlink
```
and see if it goes slow every time you remove the `~/.cache/streamlink/cli.json` file? If it does, then can you try:
```bash
rm ~/.cache/streamlink/cli.json
streamlink --no-version-check 
```
and see if that goes fast?

**Comment by paramec** [comment]
Yes, it's happening exactly as you described. 
I will use the application over the weekend to see if --no-version-check will speed the execution every time.
I will come with the feedback later.
Thank you for the moment and for your quick answer.

**Comment by beardypig** [comment]
Cool. This is related to #590 and a 👍 in its favour.

**Comment by paramec** [comment]
I can confirm now that with --no-version-check option the program is running fast and with no delay in execution, no waiting time. 
From my perspective the topic can be closed.

**Comment by beardypig** [comment]
I'm going close this. Dear future readers please make any further comments on #590.
