### ISSUE TITLE
Support all audio tracks

### ISSUE THREAD

**Issue by Dinesh-Shrestha** [streamlink/streamlink#5993]
### Checklist

- [X] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Description

Can we have all audio tracks from the source in the pipe?

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#cmdoption-hls-audio-select

For DASH, it's currently not possible. See #4902 / #5764
