### ISSUE TITLE
Plugin : seetv.tv

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#600]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

It's a video platform with a bunch of channels. 

### Expected / Actual behavior

Example of address : 

This address : `http://seetv.tv/vse-tv-online/rossiya-1-online` 
redirects to 
`http://seetv.tv/vse-tv-online/rossiya-1-online#link=11030`

### Reproduction steps / Stream URLs to test

```
streamlink -p "%homedrive%\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc" "hlsvariant://http://stream3.seetv.tv:8081/livetv/ru1/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNy8yMDE3IDEyOjA5OjEzIFBNJmhhc2hfdm
FsdWU9MVpac3R5eG1rM1gyNVNJbUpiMmJaUT09JnZhbGlkbWludXRlcz0yMCZzdHJtX2xlbj0xMA=="
best
[cli][info] Found matching plugin stream for URL hlsvariant://http://stream3.see
tv.tv:8081/livetv/ru1/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8xNy8yMDE3IDEy
OjA5OjEzIFBNJmhhc2hfdmFsdWU9MVpac3R5eG1rM1gyNVNJbUpiMmJaUT09JnZhbGlkbWludXRlcz0y
MCZzdHJtX2xlbj0xMA==
[cli][info] Available streams: 576p (best, worst)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Environment details (operating system, python version, etc.)

Streamlink portable on Windows 7 Professional. 

### Comments, logs, screenshots, etc.

No geo restriction.

**Comment by beardypig** [comment]
Some of the streams are available as HLS on `seetv.tv`, but some are embedded as `<iframe />` or `<object />`. I think the streams that are HLS should be fine, but the embedded ones are just links to other sites and should not be supported by a `seetv` plugin (also, it would require much more maintenance). 
For example: `seetv.tv/vse-tv-online/eurosport` should work fine, but `seetv.tv/vse-tv-online/autoplustv` will not.

**Comment by karlo2105** [comment]
Embedded streams aren't relevant for plugin support. ;)
