### ISSUE TITLE
plugins.twitch: Can ads be removed?

### ISSUE THREAD

**Issue by flowerseacar** [streamlink/streamlink#6000]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Streamlink version

streamlink 6.7.4

### Description

alternate player for twitch.tv, this browser plug-in can remove ads, can you use their API interface to remove ads?

### Debug log

```text
no
```

**Comment by bastimeyer** [comment]
#4949
