### ISSUE TITLE
Plugin : sportgol1.org

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#603]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Various sports channels from Eastern Europe and Balkans aired directly from website.

### Expected / Actual behavior

Example : 
`http://sportgol1.org/football1ua` 
- > `http://cdn.sportlive.ws/hls/a1ypTXlW7qQzMMXye2Tjhg/1487370098/football1ua.m3u8`

Streams are protected by timestamp cookie and page Referer. 

### Reproduction steps / Stream URLs to test

```
streamlink --http-header "Referer=http://sportgol1.org/football1ua" "hls://http://cdn.sportlive.ws/hls/a1ypTXlW7qQzMMXye2Tjhg/1487370098/football1ua.m3u8" best
[cli][info] Found matching plugin stream for URL hls://http://cdn.sportlive.ws/hls/a1ypTXlW7qQzMMXye2Tjhg/1487370098/football1ua.m3u8
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Environment details (operating system, python version, etc.)

Windows 7 Professional, Python 2.7.13

### Comments, logs, screenshots, etc.

Streams are directly aired from website without any restriction. 
They have mirror site : `http://2streamking.co/`
- > `http://cdn.smotrimult.com/hls/X7CKd_h1kPXVESw1nYOyMg/1487378147/football1ua.m3u8`

Channels idents from mirror site work on original site too, as with referer.

**Comment by back-to** [comment]
Are the streams some kind of geo blocked or are they dead?

> smotrimult.com
> **This Domain Name Has Expired**
> https://archive.is/8LOQO

**Comment by karlo2105** [comment]
I checked both pages above and streaming are working fine on both of them. 
Streams are not geoblocked.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 2 - Sites which are hosting stolen content as their main source of content
