### ISSUE TITLE
plugins.pluzz: live or replay from francetv doesn't work anymore

### ISSUE THREAD

**Issue by uNouss** [streamlink/streamlink#6047]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

[cli][info] Your Streamlink version (6.8.1) is up to date!

### Description

I've noticed that this plugin hasn't been working for a week now. Neither on live broadcasts nor on replays.

### Debug log

```text
[session][debug] Loading plugin: pluzz
[cli][debug] OS:         Linux-6.8.0-35-generic-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.3
[cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[cli][debug] Streamlink: 6.8.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.6.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.2.2
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.25.1
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.2
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.france.tv/france-2/planete-terre/5875566-le-prix-de-la-survie.html
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=mpv
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-2/planete-terre/5875566-le-prix-de-la-survie.html
[plugins.pluzz][debug] Country: FR
[plugins.pluzz][debug] Video ID: c7833bef-2639-466d-b96f-3dbae6222c4c
error: Unable to validate response text: ValidationError(dict):
  Unable to validate value of key 'video'
  Context(dict):
    Unable to validate value of key 'workflow'
    Context(AnySchema):
      ValidationError(equality):
        None does not equal 'token-akamai'
      ValidationError(equality):
        None does not equal 'dai'
```

**Comment by uNouss** [comment]
Perhaps related to this issue https://github.com/yt-dlp/yt-dlp/issues/10197

The workaround given in the issue seems to work for `yt-dlp` but not for `streamlink`:

```
python3 -m pip install -U --pre "yt-dlp[default]"
```

_Originally posted by @bashonly in https://github.com/yt-dlp/yt-dlp/issues/10197#issuecomment-2172114541_

**Comment by uNouss** [comment]
@bastimeyer this revision https://github.com/streamlink/streamlink/pull/6048 fix the issue 

Thanks

**Comment by bastimeyer** [comment]
Thanks for testing, but I asked for any streams which I might have missed in the tests (posted in the PR comment). It's merged now though, so if there are any further issues, please open a new issue thread.
