### ISSUE TITLE
I can't delete the installer (Windows)

### ISSUE THREAD

**Issue by KeksamPC** [streamlink/streamlink#605]
- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

Hey, so first of all, I am not an expert at this whole thing, so please excuse me if I come across incredibly stupid. 
So I downloaded the streamlink-latest.exe installer from here https://streamlink.github.io/install.html#windows-binaries , because the Twitch GUI I use said so. 

When I tried to delete the setup file (streamlink-latest.exe), it didn't delete, I got an error saying I needed Administrator rights even though I do have them. When I try to open it with Notepad++ for testing, it says the file could not be found. I also tried deleting or renaming it through cmd.exe with administrator rights, but it said 'Access denied'. I tried every way I could think of for 2 hours now, but failed.

Now, this isn't a very big issue, but I would like to have an explanation/solution/whatever.

Thank you

**Comment by gravyboat** [comment]
Hmm this is very odd. I just downloaded and reinstalled the latest release to test it myself and I'm not having any issues removing the file (Windows 7 64 bit). Can you see if the issue persists after restarting your computer?

**Comment by KeksamPC** [comment]
Okay, now I restarted (again, I tried that before), but now the file is gone. Strang

So that solves it, thank you for your response!

**Comment by gravyboat** [comment]
No problem, sometimes Windows is weird with deleting files. I'm going to close this for now.
