### ISSUE TITLE
plugins.pluzz: Unable to read streams from all live

### ISSUE THREAD

**Issue by Facy5** [streamlink/streamlink#6061]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

[cli][info] Your Streamlink version (6.8.1) is up to date!

### Description

The Pluzz plugin seems unable to read streams from all live (Akamai related ?).

### Debug log

```text
PS C:\Users\Orion> streamlink --loglevel=debug https://www.france.tv/france-2/direct.html best
[session][debug] Loading plugin: pluzz
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.4
[cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[cli][debug] Streamlink: 6.8.1
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.6.2
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.2.2
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.25.1
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.2
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.france.tv/france-2/direct.html
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player-args=--file-caching=5000
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin pluzz for URL https://www.france.tv/france-2/direct.html
[plugins.pluzz][debug] Country: FR
[plugins.pluzz][debug] Video ID: 006194ea-117d-4bcf-94a9-153d999c59ae
error: Unable to validate response text: ValidationError(dict):
  Unable to validate value of key 'video'
  Context(dict):
    Unable to validate value of key 'workflow'
    Context(AnySchema):
      ValidationError(equality):
        None does not equal 'token-akamai'
      ValidationError(equality):
        None does not equal 'dai'
```

**Comment by bastimeyer** [comment]
> [cli][debug] Streamlink: 6.8.1

d4b2945e809e1e98176b0fd77a5697c6750e0c28 / #6048
