### ISSUE TITLE
Proper portable version

### ISSUE THREAD

**Issue by Kein** [streamlink/streamlink#607]
I swear to go I saw this request here and even tracked it and commented on it. Where did it go?

Someone already requested a proper portable version instead of, basically, mini web-installer that DOWLOADS and INSTALLS stuff. I just want to unpack the files it where I want to and configure myself like it was done with **livestreamer**.

I have no idea why are web-installer even called portable.

**Comment by gravyboat** [comment]
You mean like this? https://github.com/streamlink/streamlink-portable

**Comment by Kein** [comment]
Not proper portable. Ask for the installation type, asks to download snapshots, has installer.

That's not **portable**, that's custom installer.

**Comment by beardypig** [comment]
@Kein is there more what you're after [beardypig/streamlink-portable](https://github.com/beardypig/streamlink-portable#streamlink-portable)?

**Comment by Kein** [comment]
@beardypig le perfecto.

This should be default portable version since it is, well, portable.

thanks BP.

**Comment by karlo2105** [comment]
@Kein 
Both portable versions are complementary. Rosadin includes script which builds latest commits, so no need to visit github website for updating.  
Beardypig is more classical way for people who don't update often. ;)

**Comment by gravyboat** [comment]
Going to close this out then, thanks @beardypig. @Kein please consider being a bit more understanding and empathetic when you create issues like this and the tone you use. We are spending our free time (unpaid at that) to work on this project.

**Comment by Kein** [comment]
I understand that gravy and I'm glad someone finally brought livestreamer back to life but I will be honest - your portable installation is utter crap :P

Consider adopting the classic one @beardypig provides.

**Comment by RosadinTV** [comment]
@Kein It's a matter of taste but i agree that adding the @beardypig portable version to documentation would be a really great idea.
