### ISSUE TITLE
Plugin TVPC.us

### ISSUE THREAD

**Issue by paramec** [streamlink/streamlink#610]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Various Entertainment, Movies, Sports channel's from all over the  world.
Have a look.

**Comment by gravyboat** [comment]
Can you provide us with details regarding what a request looks like, what the URLs would be for channels, etc.?

**Comment by karlo2105** [comment]
TV streams source from third party sites.
