### ISSUE TITLE
Plugin: rtve.es VOD

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#612]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Would it be possible to add VOD streams for rtve.es ? 

### Reproduction steps / Stream URLs to test

short-URL: http://www.rtve.es/drmn/embed/video/{id}
short-URL: http://www.rtve.es/drmn/embed/video/3886778
long-URL:  http://www.rtve.es/alacarta/videos/cuentame-como-paso/cuentame-como-paso-t18-capitulo-313-amigo-americano/3886778/

### Comments, logs, screenshots, etc.

I don't know if it helps, but one can get information about the video using the API, described by Ulises Gascon at http://ulisesgascon.github.io/RTVE-API/
For example 
http://www.rtve.es/api/videos/{id}.json
http://www.rtve.es/api/videos/3886778.json

**Comment by malvinas2** [comment]
Thank you very much for your quick response. 
I tried the example given in my first post, video-id 3886778, which according to the JSON-information should be available in three different qualities. But when I call the link within python I receive three links with the identical URL, is this correct ? 

`Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (
AMD64)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import streamlink`
`>>> streams = streamlink.streams("http://www.rtve.es/drmn/embed/video/3886778")`
`>>> streams['worst']`
`<HLSStream('http://hlsvod.lvlt.rtve.es/resources/TE_GL13/mp4/4/6/**1485475369464.mp4**/1485475369464-audio=64000-video=919000.m3u8')>`
`>>> streams['540p']`
`<HLSStream('http://hlsvod.lvlt.rtve.es/resources/TE_GL13/mp4/4/6/**1485475369464.mp4**/1485475369464-audio=64000-video=919000.m3u8')>`
`>>> streams['best']`
`<HLSStream('http://hlsvod.lvlt.rtve.es/resources/TE_GL13/mp4/4/6/**1485475369464.mp4**/1485475369464-audio=64000-video=919000.m3u8')>`

**Comment by beardypig** [comment]
I have added the missing qualities in another PR. Now you should get all these qualities:
```python
['540p', '540p_alt', '360p', '360p_alt', '540p_http', '540p_http_alt', '360p_http', '360p_http_alt', '270p', '270p_alt', 'best', 'worst']
```

**Comment by malvinas2** [comment]
Well, I don't know if it is possible to re-open an already closed issue, just trying it....

For some old videos rtve.es seems to use quicktime (*.mov)-files. 
Is it possible to add this to streamlink ? 

Example: 
http://www.rtve.es/alacarta/videos/cantares/marife-triana-cantares-1978/1692684/
http://www.rtve.es/drmn/embed/video/1692684
