### ISSUE TITLE
plugins.nicolive: Community has been deprecated

### ISSUE THREAD

**Issue by cykac04** [streamlink/streamlink#6125]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

6.8.3

### Description

The static room url format is changed as nico community has been deprecated.

before: https://live.nicovideo.jp/watch/co3618724
now: https://live.nicovideo.jp/watch/user/16128426

### Debug log

```text
/
```

**Comment by bastimeyer** [comment]
Plugin is fixed now. Please don't post any NSFW links in the future, thanks.
