### ISSUE TITLE
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option. [stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!

### ISSUE THREAD

**Issue by jumuzerg** [streamlink/streamlink#6134]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

 streamlink-6.9.0-1-py312-x86_64

### Description

I'm sorry guys, it's very inconvenient to contact, I know that the problem has already been discussed, but I don't have enough acquaintances to solve it

when I want to launch a random video from YouTube it doesn't want to launch, I suspect that the problem appeared after PC optimization

### Debug log

```text
C:\Users\El Arsenio>D:\matebeats\soft\network\streamlink-6.9.0-1-py312-x86_64\bin\streamlink.exe https://www.youtube.com/watch?v=P-rFO3eyc_o best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=P-rFO3eyc_o
[stream.ffmpegmux][warning] No valid FFmpeg binary was found. See the --ffmpeg-ffmpeg option.
[stream.ffmpegmux][warning] Muxing streams is unsupported! Only a subset of the available streams can be returned!
[cli][info] Available streams: audio_mp4a, audio_opus, 360p (worst, best)
[cli][info] Opening stream: 360p (http)
[cli][info] Starting player: D:\matebeats\soft\media\VLC\vlc.exe
[cli][error] Try 1/1: Could not open stream <HTTPStream [many incomprehensible symbols
```

**Comment by bastimeyer** [comment]
1. https://streamlink.github.io/install.html#windows-binaries
2. https://github.com/streamlink/windows-builds#notes
3. https://streamlink.github.io/cli.html#cmdoption-ffmpeg-ffmpeg

**Comment by jumuzerg** [comment]
Launching streamlink....
'streamlink.exe --player-passthrough hls https://www.youtube.com/watch?v=ljciE4juWQQ Best'
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=ljciE4juWQQ
[cli][info] Available streams: audio_mp4a, audio_opus, 144p (worst), 360p (best)
[cli][info] Opening stream: 360p (http)
[cli][info] Starting player: "D:\matebeats\soft\media\VLC"
[cli][error] Try 1/1: Could not open stream <HTTPStream ['http', 'https://rr4---sn-q5u5bgv02-3c26.googlevideo.com/videoplayback?expire=1724178925&ei=jY3EZpCUK6fti9oP86OdgAs&ip=176.111.177.17&id=o-AK7-gBIH6G0eHcDJa6GZN_qhjdIS1A_gdaJ1SO3HgFGK&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=OQ&mm=31%2C29&mn=sn-q5u5bgv02-3c26%2Csn-8vap5-3c2d&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1461250&bui=AQmm2ewwxHxEhVgcnIJza-SLMiLUQqhWyqkidixFJbb4BH7NTeXSY1wOMp3FuxkCYNvMvd0tU38AtM2L&spc=Mv1m9idH1iZSwGskLg32yD2LFOMSdUl63EzoEd4FEDRHxoZS15T1jGFd_uRu7_g&vprv=1&svpuc=1&mime=video%2Fmp4&ns=gv_0aa26S04mL91gbbcL5boQ&rqh=1&gir=yes&clen=38662862&ratebypass=yes&dur=1583.949&lmt=1724132050917243&mt=1724156968&fvip=8&c=WEB&sefc=1&txp=6209224&n=_-fbg2-aVzUhs2zHpdz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAIY1BUgxttcBJ4jd3AHwH5AXW_3iR46xmzJU-NVZw8RXAiEAjDu-KUSy3MunC_R33H8s1HMtnnW1B8EzFz8BhXNuYK4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgW8_kOeJ52yO6EALHggMQpKZJSDKpWmsykc1GQeTv2TYCIEOjiAWCXxqPN46csBpyZdOsAom9ZzpIq2tLBI6GAYAk']> (Could not open stream: Unable to open URL: https://rr4---sn-q5u5bgv02-3c26.googlevideo.com/videoplayback?expire=1724178925&ei=jY3EZpCUK6fti9oP86OdgAs&ip=176.111.177.17&id=o-AK7-gBIH6G0eHcDJa6GZN_qhjdIS1A_gdaJ1SO3HgFGK&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=OQ&mm=31%2C29&mn=sn-q5u5bgv02-3c26%2Csn-8vap5-3c2d&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1461250&bui=AQmm2ewwxHxEhVgcnIJza-SLMiLUQqhWyqkidixFJbb4BH7NTeXSY1wOMp3FuxkCYNvMvd0tU38AtM2L&spc=Mv1m9idH1iZSwGskLg32yD2LFOMSdUl63EzoEd4FEDRHxoZS15T1jGFd_uRu7_g&vprv=1&svpuc=1&mime=video%2Fmp4&ns=gv_0aa26S04mL91gbbcL5boQ&rqh=1&gir=yes&clen=38662862&ratebypass=yes&dur=1583.949&lmt=1724132050917243&mt=1724156968&fvip=8&c=WEB&sefc=1&txp=6209224&n=_-fbg2-aVzUhs2zHpdz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAIY1BUgxttcBJ4jd3AHwH5AXW_3iR46xmzJU-NVZw8RXAiEAjDu-KUSy3MunC_R33H8s1HMtnnW1B8EzFz8BhXNuYK4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgW8_kOeJ52yO6EALHggMQpKZJSDKpWmsykc1GQeTv2TYCIEOjiAWCXxqPN46csBpyZdOsAom9ZzpIq2tLBI6GAYAk (403 Client Error: Forbidden for url: https://rr4---sn-q5u5bgv02-3c26.googlevideo.com/videoplayback?expire=1724178925&ei=jY3EZpCUK6fti9oP86OdgAs&ip=176.111.177.17&id=o-AK7-gBIH6G0eHcDJa6GZN_qhjdIS1A_gdaJ1SO3HgFGK&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=OQ&mm=31%2C29&mn=sn-q5u5bgv02-3c26%2Csn-8vap5-3c2d&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1461250&bui=AQmm2ewwxHxEhVgcnIJza-SLMiLUQqhWyqkidixFJbb4BH7NTeXSY1wOMp3FuxkCYNvMvd0tU38AtM2L&spc=Mv1m9idH1iZSwGskLg32yD2LFOMSdUl63EzoEd4FEDRHxoZS15T1jGFd_uRu7_g&vprv=1&svpuc=1&mime=video%2Fmp4&ns=gv_0aa26S04mL91gbbcL5boQ&rqh=1&gir=yes&clen=38662862&ratebypass=yes&dur=1583.949&lmt=1724132050917243&mt=1724156968&fvip=8&c=WEB&sefc=1&txp=6209224&n=_-fbg2-aVzUhs2zHpdz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAIY1BUgxttcBJ4jd3AHwH5AXW_3iR46xmzJU-NVZw8RXAiEAjDu-KUSy3MunC_R33H8s1HMtnnW1B8EzFz8BhXNuYK4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgW8_kOeJ52yO6EALHggMQpKZJSDKpWmsykc1GQeTv2TYCIEOjiAWCXxqPN46csBpyZdOsAom9ZzpIq2tLBI6GAYAk))
error: Could not open stream <HTTPStream ['http', 'https://rr4---sn-q5u5bgv02-3c26.googlevideo.com/videoplayback?expire=1724178925&ei=jY3EZpCUK6fti9oP86OdgAs&ip=176.111.177.17&id=o-AK7-gBIH6G0eHcDJa6GZN_qhjdIS1A_gdaJ1SO3HgFGK&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=OQ&mm=31%2C29&mn=sn-q5u5bgv02-3c26%2Csn-8vap5-3c2d&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1461250&bui=AQmm2ewwxHxEhVgcnIJza-SLMiLUQqhWyqkidixFJbb4BH7NTeXSY1wOMp3FuxkCYNvMvd0tU38AtM2L&spc=Mv1m9idH1iZSwGskLg32yD2LFOMSdUl63EzoEd4FEDRHxoZS15T1jGFd_uRu7_g&vprv=1&svpuc=1&mime=video%2Fmp4&ns=gv_0aa26S04mL91gbbcL5boQ&rqh=1&gir=yes&clen=38662862&ratebypass=yes&dur=1583.949&lmt=1724132050917243&mt=1724156968&fvip=8&c=WEB&sefc=1&txp=6209224&n=_-fbg2-aVzUhs2zHpdz&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAIY1BUgxttcBJ4jd3AHwH5AXW_3iR46xmzJU-NVZw8RXAiEAjDu-KUSy3MunC_R33H8s1HMtnnW1B8EzFz8BhXNuYK4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgW8_kOeJ52yO6EALHggMQpKZJSDKpWmsykc1GQeTv2TYCIEOjiAWCXxqPN46csBpyZdOsAom9ZzpIq2tLBI6GAYAk']>, tried 1 times, exiting

ERROR occurred in streamlink: Manually close this window when you've finished reading the streamlink output.

**Comment by bastimeyer** [comment]
#6060
