### ISSUE TITLE
Support for Twitch VOD timestamps

### ISSUE THREAD

**Issue by Roiginbag** [streamlink/streamlink#614]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I am trying to download VODs from Twitch using timestamps to avoid downloading the whole video, but I have been unable to do so even using the `--player-passthrough hls` option.
I would be interested in knowing the current state of this feature and whether if it will support beginning and ending timestamps (-ss hh:mm:ss -ee hh:mm:ss).

Thanks for the awesome work.

**Comment by gravyboat** [comment]
I believe this is covered in https://github.com/streamlink/streamlink/issues/134

**Comment by beardypig** [comment]
While it would be covered by #134, I think that might be a way off... VOD HLS streams are pretty easy to skip around in, a possible solution: [beardypig/streamlink@ce9b8b6](https://github.com/beardypig/streamlink/commit/ce9b8b6500c5901b4a6967faced0d07606557029).

**Comment by Fironet** [comment]
Issue #134 is about player seeking, but it doesn't address VOD URLs that have timestamps, such as:

`https://www.twitch.tv/videos/156074788?t=12h14m25s`

PotPlayer doesn't support seeking in streamlink's current state anyway but having at least a way of launching at the desired timestamp for viewing would make it at least usable.

**Comment by X1011** [comment]
chrippa/livestreamer#1210 added support for starting at a beginning timestamp with a flag "--hls-start-time", and then you could pipe to ffmpeg to stop the download at your desired point, too.

**Comment by beardypig** [comment]
Oops, keep forgetting to PR my suggested solution.

**Comment by Fironet** [comment]
> chrippa/livestreamer#1210 added support for starting at a beginning timestamp with a flag "--hls-start-time", and then you could pipe to ffmpeg to stop the download at your desired point, too.

This appears to have been over a year ago and for the no longer maintained livestreamer repo. Sorely wish these PRs could be merged into streamlink, as livestreamer has issues for me.

**Comment by beardypig** [comment]
I think I will add negative start offsets (as per #884) for live streams, and add a duration option to my existing start offset code. That way you can watch a 20 minute segment from the middle of a stream, or skip back 45 minutes in a live stream.

**Comment by back-to** [comment]
would be covered by #1303

**Comment by gravyboat** [comment]
Closing since I've merged #1303, please test the nightly, we can reopen if needed.

**Comment by beardypig** [comment]
Now that #1303 is merged, we could support the timestamp in URL format for twitch, with `t=12h14m25s` for example in the URL.
