### ISSUE TITLE
Feature: Generic geo restriction bypass mechanism based on faking X-Forwarded-For

### ISSUE THREAD

**Issue by starchivore** [streamlink/streamlink#615]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

[Wrangling the X-Forwarded-For Header](https://r.va.gg/2011/07/wrangling-the-x-forwarded-for-header.html)

[Story behind X-Forwarded-For and X-Real-IP headers](http://distinctplace.com/infrastructure/2014/04/23/story-behind-x-forwarded-for-and-x-real-ip-headers/)

[X-Forwarded-For Header :: Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/x-forwarded-for-header/)

[sqlmap/xforwardedfor.py at master · sqlmapproject/sqlmap · GitHub](https://github.com/sqlmapproject/sqlmap/blob/master/tamper/xforwardedfor.py)

[GitHub - codetry/xff: Django X-Forwarded-For Properly](https://github.com/codetry/xff/)

[GitHub - allo-/django-xforwardedfor-middleware: Use the X-Forwarded-For header to get the real ip of a request](https://github.com/allo-/django-xforwardedfor-middleware)

This one looks like fun stuff to me, could we implement something similar by any chance?

[youtube-dl 2017.02.21](https://github.com/rg3/youtube-dl/releases/tag/2017.02.21)

> 

- [extractor/common] Allow calling _initialize_geo_bypass from extractors

https://github.com/rg3/youtube-dl/pull/11970

So basically we've got a few scenarios:

1. No need for geo restriction bypass whatsoever, worldwide access is available for everyone.
2. Faking XFF header for the extractor part only
3. Faking XFF header for the both extractor part **and** the CDN part

Let's borrow something from this KODI add-on below:

[script.video.funimationnow/funimationnow.py at master · Protocol-X/script.video.funimationnow](https://github.com/Protocol-X/script.video.funimationnow/blob/master/resources/lib/modules/funimationnow.py)

[Get physical position of device with Python?](http://stackoverflow.com/questions/11787941/get-physical-position-of-device-with-python)

Retrieve the country code of the host first:

[http://freegeoip.net/json/](http://freegeoip.net/json/)

If that weren't matching the requirement, then fake XFF header for the extractor part and/or CDN part.

Obviously it ain't bulletproof since some servers might not be "fooled" so easily, or they might "fix" something like that XFF thingy down the road.

It is still worth giving it a shot? An example for 2nd scenario (extractor part) would be:

http://www.crunchyroll.com (show-specific geo restriction, usually US/CA are good to go)
CDN:
https://v.vrv.co
https://cloudfront-hls-media-vod-ellation-fallback.vip1-lga1.dlvr1.net
https://cloudfront-hls-media-vod-ellation-fallback.vip1-mia1.dlvr1.net
https://cloudfront-hls-media-vod-ellation-fallback.vip2-iad1.dlvr1.net
https://cloudfront-hls-media-vod-ellation-fallback.vip2-lga1.dlvr1.net
https://cloudfront-hls-media-vod-ellation-fallback.vip3-ord1.dlvr1.net
(Old) CDN:
http://serve.cxcdn.net

Examples for 3rd scenario (both extractor part and CDN part) as follows:

https://www.funimation.com (US/CA/maybe UK?)
CDN:
https://d132fumi6di1wa.cloudfront.net
(Old) CDN:
http://wpc.8c48.edgecastcdn.net

https://www.animelab.com (AU/NZ)
CDN:
https://d1pnza0erna1im.cloudfront.net

Not sure about this one since it's kinda special, it could be either the 2nd or 3rd scenario:

http://www.daisuki.net (Show-specific geo restriction, usually US/CA are good to go)
CDN:
https://bngn-vh.akamaihd.net (Videos)
http://bngnwww.b-ch.com (Subtitles)

**Comment by gravyboat** [comment]
I think this is something we would have to discuss, not sure we want to support bypassing geo-restriction even though it is stupid.

**Comment by 10mins** [comment]
You can use --http-header "X-Forwarded-For=123.123.123.123"

**Comment by starchivore** [comment]
XFF turned out to be not THAT useful?

[https://github.com/rg3/youtube-dl/issues/4738](https://github.com/rg3/youtube-dl/issues/4738)

`--geo-bypass-country US` itself is complete solution and there is nothing to tweak. If it does not work then it's technically impossible to bypass geo restriction this way for this site.

No. `--geo-bypass-country` is not a universal solution. It works for only a few websites.

I tried a few sites here and there, so far they wouldn't accept a simple '--http-header' "trick" followed by XFF. Therefore only VPN, proxy, or DNS unblocking project like this one would be more practical:

[https://github.com/trick77/dockerflix](https://github.com/trick77/dockerflix)

**Comment by back-to** [comment]
Because XFF doesn't work all the time,
it is not worth to change the url-resolve behavior of streamlink

just use the `http-header` with a config file

---

use

```
--http-header "X-Forwarded-For=333.333.333.333"
```

which can also be saved in the config file if this plugin is used very often

https://streamlink.github.io/cli.html#plugin-specific-configuration-file

IP's can be found here https://www.nirsoft.net/countryip/

---

closing
