### ISSUE TITLE
Acestream Compatibility

### ISSUE THREAD

**Issue by Euskalgaming** [streamlink/streamlink#6153]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Collaboration

- [X] My request is genuine, in the best interest of the project, and I have access to the stream(s) in my web browser
- [X] [I will provide feedback should a pull request be opened with a new plugin implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)
- [X] I will help with reporting future plugin issues should the new plugin be merged and then stop working

### Description

I am currently using this [acestream](https://github.com/martinbjeldbak/acestream-http-proxy) docker.
This generates http links for me which I can use with vlc.
Since I use streamlink together with [tvhlink](https://github.com/cgomesu/tvhlink) for integration into tvheadend.
I would love for these types of links to be used in streamlink.
The links it generates are of this type:
http://127.0.0.1:6878/ace/manifest.m3u8?id=dd1e67078381739d14beca697356ab76d49d1a2
http://127.0.0.1:6878/ace/getstream?id=dd1e67078381739d14beca697356ab76d49d1a2

### Input URLs

http://127.0.0.1:6878/ace/manifest.m3u8?id=dd1e67078381739d14beca697356ab76d49d1a2
http://127.0.0.1:6878/ace/getstream?id=dd1e67078381739d14beca697356ab76d49d1a2

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli/protocols.html
