### ISSUE TITLE
plugins.tiktok: error 'stream_url' not found

### ISSUE THREAD

**Issue by mdk56** [streamlink/streamlink#6159]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.9.0

### Description

When I try to record a Tiktok live sometime this error happened : Key 'stream_url' not found in {'prompts': ''} it happens about one time in three.

### Debug log

```text
streamlink -o "/home/user/Tiktok/username-{time:%Y%m%d%H%M%S}.flv" tiktok.com/@user/live best --loglevel=debug
[session][debug] Loading plugin: tiktok
[cli][debug] OS:         Linux-6.8.0-41-generic-x86_64-with-glibc2.39
[cli][debug] Python:     3.12.3
[cli][debug] OpenSSL:    OpenSSL 3.0.13 30 Jan 2024
[cli][debug] Streamlink: 6.9.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.7.4
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.26.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.2
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=tiktok.com/@user/live
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --output=/home/user/Tiktok/username-{time:%Y%m%d%H%M%S}.flv
[cli][info] Found matching plugin tiktok for URL tiktok.com/@user/live
error: Unable to validate response text: ValidationError(dict):
  Unable to validate value of key 'data'
  Context(dict):
    Key 'stream_url' not found in {'prompts': ''}
```

**Comment by bastimeyer** [comment]
> it happens about one time in three

Post **actual input URLs** without any redacted usernames. I can't reproduce this with any randomly picked channel.

**Comment by mdk56** [comment]
This is the command line I used 30 minutes ago to create the commit : `streamlink -o "/home/midk/Tiktok/weemonloup-{time:%Y%m%d%H%M%S}.flv" tiktok.com/@weemonloup/live best --loglevel=debug` Now it works, but if I stop recording and try again in ten minutes, maybe it will display the error again.

**Comment by bastimeyer** [comment]
Watching this channel requires a login, which is unsupported by the plugin.

The plugin successfully gets the `room_id`, but when using the room ID in order to get the stream URL from their API, the API response is empty, hence the missing `stream_url` error in the validation schema.

That's the API response:
```
$ curl -sSL https://webcast.tiktok.com/webcast/room/info/?aid=1988&room_id=7410865239404645153
{"data":{"prompts":""},"extra":{"now":1725477611840},"status_code":4003110}
```

So all that can be done here is fix the validation error and handle inaccessible streams accordingly.

You can try adding HTTP authentication headers/cookies (`--http-header` / `--http-cookie`), but you'll have to figure this out on your own by using your web browser's dev tools.
