### ISSUE TITLE
plugins.okru: Enigma 2 box not working offline

### ISSUE THREAD

**Issue by Ansee0216** [streamlink/streamlink#6167]
### Checklist

- [X] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [X] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

6.10.0

### Description

plugins.okru: Enigma 2 box not working, Other Streamlink 6.7 yes,,,6.10.0 offline example.:::#SERVICE 5002:0:1:6:521:d:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//mobile.ok.ru/video/3574052691599:Rossiya 24*
#DESCRIPTION Rossiya 24*
#SERVICE 5002:0:1:0:0:0:0:0:0:0:http%3a//127.0.0.1%3a8088/https%3a//mobile.ok.ru/video/351615524467:78 НОВОСТИ Live
#DESCRIPTION 78 НОВОСТИ Live

OFFLINE ENIGMA2,PLEASE HELP.

### Debug log

```text
File "/usr/lib/python3.12/site-packages/streamlink/utils/module.py", line 34,
in exec_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3. File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/usr/lib/python3.12/site-packages/streamlink/plugins/vtvgo.py", line 13
in <module>
from streamlink.plugin.api.webbrowser.aws_waf import AWSWAF
File "/usr/lib/python3.12/site-packages/streamlink/plugin/api/webbrowser/aws_
af.py", line 6, in <module>
import trio
import trio
ModuleNotFoundError: No module named 'trio'
[streamlinksrv][debug] Arguments:
[streamlinksrv][debug] url=https://mobile.ok.ru/video/351615524467
[streamlinksrv][debug] stream=['best']
[streamlinksrv][info] Found matching plugin for URL https://mobile.ok.ru/video
351615524467
351615524467
[streamlinksrv][error] Unable to validate response text: ValidationError(xml_fin
d):
ElementPath query './/a[@data-video]' did not return an element
[streamlinksrv][debug] Send Offline clip
```

**Comment by bastimeyer** [comment]
> streamlinksrv

This is a third party project which is not supported here. You have to ask the project maintainers.
