### ISSUE TITLE
https://catcast.tv

### ISSUE THREAD

**Issue by Ansee0216** [streamlink/streamlink#6168]
### Checklist

- [X] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [X] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Collaboration

- [X] My request is genuine, in the best interest of the project, and I have access to the stream(s) in my web browser
- [X] [I will provide feedback should a pull request be opened with a new plugin implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)
- [X] I will help with reporting future plugin issues should the new plugin be merged and then stop working

### Description

catcast.tv - live broadcasting and radio. ... Descriptions. descriptions off, selected. Captions. captions settings, opens captions settings dialog; captions ..

### Input URLs

1. ...https://catcast.tv/cinemaster2
2. ...https://catcast.tv/horrorchannel
3  ,,,https://catcast.tv/сити-эдем-кинодетектив

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-rules

rule 6

All HLS stream URLs are also static, so all you need is to get the stream URLs once from your web browser's dev tools. No plugin is required for that. Only one additional HTTP header is needed here.
https://streamlink.github.io/cli/protocols.html#streaming-protocols

Example
```
$ streamlink --http-header=x-access-token=6eb1b021862e21e818c5e0b7b62658a6 https://v2.catcast.tv/content/41170/index.m3u8
[cli][info] Found matching plugin hls for URL https://v2.catcast.tv/content/41170/index.m3u8
Available streams: live (worst, best)
```
