### ISSUE TITLE
Plugin: funimation.com VOD

### ISSUE THREAD

**Issue by starchivore** [streamlink/streamlink#617]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

[Funimation Downloader NX (nodejs based funimation.com downloader)](http://kametsu.com/topic/54534-funimation-downloader-nx-nodejs-based-funimationcom-downloader/?page=4#comment-527466)

[FunimationNOW Kodi Add-on](http://forum.kodi.tv/showthread.php?tid=304479)

This one seems to be fairly straightforward and we could get what we need here:

[script.video.funimationnow/funimationnow.py at master · Protocol-X/script.video.funimationnow](https://github.com/Protocol-X/script.video.funimationnow/blob/master/resources/lib/modules/funimationnow.py)

Easier to give an example right off the bat, go for the `iframe` part @ line 427:

[https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu/](https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu/)

Grab that link to their Brightcove player first:

[https://www.funimation.com/player/256245/?bdub=0](https://www.funimation.com/player/256245/?bdub=0)

Either grab these guys @ line 33 directly:

`"alphaExternalId": "DBSSIM0079", "screenshots": ["https://d132fumi6di1wa.cloudfront.net/exp/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06.m3u8"], "huluId": "", "textTracks": [{"src": "https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2930c000-f9d1-e611-80c5-0017a4776c06.vtt", "kind": "subtitle", "type": "Full", "language": "en", "label": "English"},`

Or go for the `url` @ line 48 instead since that's even neater, we could simply get all `m3u8` links to the **entire season** by replacing `256245` with the corresponding `"experienceId"` for each episode:

[https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/)

Getting pretty much the same stuff afterwards:

`"sources":[{"purchase":"","huluId":"","screenshots":["https://d132fumi6di1wa.cloudfront.net/exp/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06.m3u8"],"alphaExternalId":"DBSSIM0079","showAds":false,"textTracks":[{"src":"https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2930c000-f9d1-e611-80c5-0017a4776c06.vtt","kind":"subtitle","type":"Full","language":"en","label":"English"}`

Strip `/exp` whenever we see that:

> https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06.m3u8

Add anywhere between `_Layer1` and `_Layer9` right before `.m3u8`

![image](https://cloud.githubusercontent.com/assets/19405280/23214423/9f708ce2-f949-11e6-80dc-3eb27316921f.png)

> https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06_Layer1.m3u8

.
.
.

> https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06_Layer9.m3u8

Either download `mp4` with `ffmpeg`:

`ffmpeg -i https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2a30c000-f9d1-e611-80c5-0017a4776c06_Layer9.m3u8 -c copy DBSSIM0079.mp4`

Or mux `vtt` subtitles with `ffmpeg` before transporting to the player and that's it.

I did see a particular series that's going from `_Layer1` to **only** `_Layer8` but I'll have to keep looking for an example.

BTW, maybe we could also borrow something here for switching between layers?

[script.video.funimationnow/utils.py at master · Protocol-X/script.video.funimationnow](https://github.com/Protocol-X/script.video.funimationnow/blob/master/resources/lib/modules/utils.py)

**Comment by beardypig** [comment]
Would be useful to have some example URLs, particularly cut vs uncut, dub only (if this exists), and sub only (if this exists) :)

**Comment by beardypig** [comment]
Got the basic plugin working, but still some room to improve it. Need to tidy up the code, and improve error handling, etc.

**Comment by starchivore** [comment]
> Dub only

Only 3 episodes for now, is that cool?

https://www.funimation.com/shows/masamune-kuns-revenge/
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/264467/

> Sub only

Season 13 of [_One Piece_](https://www.funimation.com/shows/one-piece/):
https://www.funimation.com/shows/one-piece/to-the-reverie-princess-vivi-and-princess-shirahoshi/
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256238/

So far they're all hard-subbed since they explicitly stated that:

`"burnedInSubs": true,`

And then [_Dragon Ball Super_](https://www.funimation.com/shows/dragon-ball-super/) (dub only) should be a bit "funny" almost all episodes are hard-subbed so far, the only exceptions are episodes 41 to 46 plus 79:

[41](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/209746/)
[42](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/209744/)
[43](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/209750/)
[44](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/211848/)
[45](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/209747/)
[46](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/209748/)
[79](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/)

**Comment by beardypig** [comment]
Cool, that's perfect. Thanks.

**Comment by beardypig** [comment]
@starchivore I have a basic version in a branch if you want to give it a go and give some early feedback: https://github.com/beardypig/streamlink/tree/funimation

It defaults to Japanese with subtitles muxed in, I haven't added the command line options yet.

**Comment by starchivore** [comment]
Nice job and thanks again, just a few things for now:

### 1. From `funimationnow` to `funimation`

Changing `https?://(?:www\.)funimationnow.(com|uk)` @ line `100` to `https?://(?:www\.)funimation.(com|uk)` by removing `now` and it's good to go.

### 2. Subtitle language (`OSD` showed `Subtitles: (1) unknown`)

Running `mpv` just fine:

```
streamlink -p "C:\D\mpv\mpv.exe --hwdec=yes --slang=English" https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu 234p
```

It would be good to pass the language of `vtt` subs to the player so that `OSD` of `mpv` or `VLC` could display that accordingly, no biggie at all so please kindly consider working on that feature whenever you get a chance.

### 3. Display all `URL`(s) of `vtt`/`dfxp`/`srt` subs just like the way `daisuki.net` plugin is behaving

It's just me being lazy to find the `URL`(s) manually , nothing more than a "nice-to-have" so that's up to you:
```
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu

[cli][info] Available streams: 360p_alt, 1080p_alt, 720p_alt, 234p (worst), 270p, 360p, 480p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 234p (muxed-stream)
[cli][info] Starting player: C:\D\mpv\mpv.exe --hwdec=yes --slang=English
```
It's shown right above `[cli][info] Available streams:` as follows:
![8panbmp](https://cloud.githubusercontent.com/assets/19405280/22966961/5f6aeeda-f39f-11e6-9509-0fcb8f0e8236.png)

It should be a piece of cake and let's go back to previous example:

> [https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/)

```
"textTracks":[
{"src":"https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2930c000-f9d1-e611-80c5-0017a4776c06.vtt","kind":"subtitle","type":"Full","language":"en","label":"English"},
{"src":"https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2b30c000-f9d1-e611-80c5-0017a4776c06.dfxp","kind":"subtitle","type":"Full","language":"en","label":"English"},
{"src":"https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2c30c000-f9d1-e611-80c5-0017a4776c06.srt","kind":"subtitle","type":"Full","language":"en","label":"English"}
],
```
I don't wanna bother you with stuff like switching between sub and dub audio on the fly, it's gotta be a good idea to save your time for [`streamlink-server`](https://github.com/beardypig/streamlink-server) since that should be a mighty interesting project. :)

**Comment by beardypig** [comment]
1. I'll make `now` optional :-) `funimation(?:now)?`
2. I was too lazy to do that in the first go ;-)
3. Ditto 2

Thanks for the feedback :-)

**Comment by beardypig** [comment]
@starchivore I have updated that branch with some new features, and your suggestions :)

**Comment by starchivore** [comment]
Fantastic, items 1 to 3 are good now and many thanks again.

Their `mp4` files turned out to be quarter-HD but it's really no biggie:

https://github.com/beardypig/streamlink/blob/funimation/src/streamlink/plugins/funimationnow.py#L103

`mp4_quality = "480p"`

`mp4_quality = "540p"`

For switching from one language to another, it should be quite straightforward since both languages do share the same `versionId` for obvious reasons. Let's pick this one as an exmaple:

https://www.funimation.com/shows/yu-yu-hakusho/surprised-to-be-dead/

`English` dub = `"experienceId":119661` = `"versionId":11244`
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/119661/

From the `API` of `English` flavor, we could retrieve both `"experienceId":119738` and `"experienceKey":"1401840_Japanese"` easily:

```
"japanese":{"alpha":{"uncut":{"sources":[],"poster":"https://res.cloudinary.com/sfp/image/upload/oth/FunimationStoreFront/1401840/English/1401840_English_KeyArt-OfficialVideoImage_7826b3d5-8da0-e611-80c5-0017a4776c06.jpg","versionId":11244,"avodOnly":false,"svodOnly":false,"duration":1424,"experienceId":119738,"experienceKey":"1401840_Japanese"}}},
```

`Japanese` raw = `"experienceId":119738` = `"versionId":11244`
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/119738/

Same deal with the `Japanese` flavor again, `"experienceId":119661` followed by `"experienceKey":"1401840_English"` could be found:

```
"english":{"alpha":{"uncut":{"sources":[],"poster":"https://res.cloudinary.com/sfp/image/upload/oth/FunimationStoreFront/1401840/English/1401840_English_KeyArt-OfficialVideoImage_7826b3d5-8da0-e611-80c5-0017a4776c06.jpg","versionId":11244,"avodOnly":false,"svodOnly":false,"duration":1424,"experienceId":119661,"experienceKey":"1401840_English"}}}},
```

Another example:

https://www.funimation.com/shows/dragon-ball-z/the-new-threat/

`English` dub = `"experienceId":25814` = `"versionId":3095`
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/25814/

```
"japanese":{"alpha":{"uncut":{"sources":[],"poster":"https://res.cloudinary.com/sfp/image/upload/oth/FunimationStoreFront/1327320/English/1327320_English_KeyArt-OfficialVideoImage_161868aa-30be-e611-80c5-0017a4776c06.jpg","versionId":3095,"avodOnly":false,"svodOnly":false,"duration":1478,"experienceId":25769,"experienceKey":"1327320_Japanese"}}},
```

`Japanese` raw = `"experienceId":25769` = `"versionId":3095`
https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/25769/

```
"english":{"alpha":{"uncut":{"sources":[],"poster":"https://res.cloudinary.com/sfp/image/upload/oth/FunimationStoreFront/1327320/English/1327320_English_KeyArt-OfficialVideoImage_161868aa-30be-e611-80c5-0017a4776c06.jpg","versionId":3095,"avodOnly":false,"svodOnly":false,"duration":1478,"experienceId":25814,"experienceKey":"1327320_English"}}}},
```

Finally it's about muxing subtitles by default or otherwise.

[_Dragon Ball Super_ episode 79](https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu/) (`sub` only) seemed to be OK with the line `[cli][info] Opening stream: 234p (muxed-stream)`:

```
C:\D\streamlink>streamlink -p "C:\D\mpv\mpv.com --hwdec=yes" "https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu" 234p
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/dragon-ball-super/universe-9s-basil-the-kicker-vs-universe-7s-majin-buu

[plugin.funimationnow][info] Switching language to: english
[plugin.funimationnow][warning] Requested language english is not available, continuing with japanese
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2930c000-f9d1-e611-80c5-0017a4776c06.vtt
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2b30c000-f9d1-e611-80c5-0017a4776c06.dfxp
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1590221/Japanese/1590221_Japanese_2c30c000-f9d1-e611-80c5-0017a4776c06.srt
[cli][info] Available streams: 360p_alt, 720p_alt, 1080p_alt, 234p (worst), 270p, 360p, 480p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 234p (muxed-stream)
[cli][info] Starting player: C:\D\mpv\mpv.com --hwdec=yes
```

Then I tried two more examples mentioned above, all 3 links to the `English` Close Captions were displayed accordingly:

```
C:\D\streamlink>streamlink -p "C:\D\mpv\mpv.com --hwdec=yes" "https://www.funimation.com/shows/dragon-ball-z/the-new-threat/" 234p
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/dragon-ball-z/the-new-threat/
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_221868aa-30be-e611-80c5-0017a4776c06.vtt
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_241868aa-30be-e611-80c5-0017a4776c06.srt
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_251868aa-30be-e611-80c5-0017a4776c06.dfxp
[cli][info] Available streams: 360p_alt, 1080p_alt, 720p_alt, 234p (worst), 270p, 360p, 480p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 234p (hls)
[cli][info] Starting player: C:\D\mpv\mpv.com --hwdec=yes
```

Since the line `[cli][info] Opening stream: 234p (hls)` was shown while pressing the `J` key would gimme `Subtitles: no`, the `vtt` wasn't getting muxed by default and I guess maybe that's the default behavior because they're Closed Captions?

Then I also saw this line of code for disabling subtitles:

https://github.com/beardypig/streamlink/blob/funimation/src/streamlink_cli/argparser.py#L1120

Just wondering if the default behavior should be something like "muxing the `vtt` anyways" and "turn subtitles off" right off the bat since they're Closed Captions?

**Comment by beardypig** [comment]
Yeah resolution on funimation.com appears to be `540p` and funimationnow.uk is `480p`. I have a TODO, to fix that hehe. 

Language switching is already implemented, but you have to choose beforehand with `--funimation-language`. 

It currently doesn't mux close caption subs because I couldn't find a good way to turn them off by default. I'll try and work that out, but I didn't have much time to work on it :-)

**Comment by starchivore** [comment]
OK, maybe `funimationnow.uk` is closer to `animelab.com` since the latter one seemed to serve hard-subbed `mp4` streams in `480p` for free accounts.

I tried them all for the examples mentioned above before posting previous comment, somehow it's still showing all 3 links to Close Captions while giving me `dub` in English:

`--funimation-language ja`
`--funimation-language=ja`
`--funimation-language japanese`
`--funimation-language=japanese`

I wasn't exactly sure if `--funimation-language` were ready yet, or maybe for some reasons the specific show you tried was indeed working while my examples might behave somewhat differently?

Anyways it ain't that important (at least for me) since they've got the horrible HE-AAC v2 audio codecs while streaming anything higher than `234p` through SOCKS5 proxy would result in frequent buffering. I also tried `--http-header "X-Forwarded-For=AA.BB.CC.DD"` but their CDN wouldn't be fooled so easily.

It's only good for my seed box and that's all I need for that "specific task" right now.

Thankfully we've got `--crunchyroll-session-id` so I'm able to stream their hard-subbed ones without having to go through SOCKS5 proxy, it's just nice to keep `funimation.com` as a backup plan of some sort.

**Comment by beardypig** [comment]
Ah so with `https://www.funimation.com/shows/dragon-ball-z/the-new-threat/` and `--funimation-language ja` you expect to get Japanese but get English dub? Can you run it again with `-ldebug` and give me the output?

**Comment by starchivore** [comment]
It's supposed to grab `25814` and then switch to `25769` afterwards, somehow it wasn't behaving the way it's meant to:

```
C:\D\streamlink>streamlink -ldebug -p "C:\D\mpv\mpv.com --hwdec=yes" --funimation-language ja "https://www.funimation.com/shows/dragon-ball-z/the-new-threat/" 234p
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/dragon-ball-z/the-new-threat/
[plugin.funimationnow][debug] Found experience ID: 25814
[plugin.funimationnow][debug] Found episode: The New Threat
[plugin.funimationnow][debug]   has languages: japanese, english
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_221868aa-30be-e611-80c5-0017a4776c06.vtt
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_241868aa-30be-e611-80c5-0017a4776c06.srt
[plugin.funimationnow][info] Subtitles: https://d132fumi6di1wa.cloudfront.net/FunimationStoreFront/1327320/English/1327320_English_251868aa-30be-e611-80c5-0017a4776c06.dfxp
[cli][info] Available streams: 1080p_alt, 360p_alt, 720p_alt, 234p (worst), 270p, 360p, 480p, 540p, 720p, 1080p (best)
[cli][info] Opening stream: 234p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[cli][info] Starting player: C:\D\mpv\mpv.com --hwdec=yes
```

**Comment by beardypig** [comment]
Hmm weird :-) OK I'll take a look when I get the chance. 

Have you tried using the `--stream-url` option to get the M3U8 URL and see if you can play that without a proxy? 

Did you want a plugin for animelab too?

**Comment by starchivore** [comment]
I've been getting the `URL` of `M3U8` manually since they switched to the new CDN in January and they're definitely blocking my location, though the old CDN is still accessible without proxy.

Maybe it takes time to write something for `--animelab-username` and `--animelab-password` since they're restricting everything for logged on (free and paid) users in AU/NZ only, at least it's SUPER easy to grab the direct links to `mp4` files afterwards but they're still serving hard-subbed episodes:

https://www.animelab.com/player/dragon-ball-super-episode-79

That's really up to you since it's yet another backup for me just in case other streaming providers are getting smarter or something, and it's also slow beyond imagination to get something via free proxy servers. Maybe some Aussies do appreciate a plugin and that could be done without having to spend much time.

**Comment by beardypig** [comment]
@starchivore there was a bug :) I'm opening a PR now to get this merged.

**Comment by gravyboat** [comment]
Closing since #629 is merged. Thanks for fixing this up @beardypig, and thanks for the detailed reporting @starchivore.
