### ISSUE TITLE
Crunchyroll authentication.

### ISSUE THREAD

**Issue by MeowMeowKins** [streamlink/streamlink#619]
There's a problem with crunchyroll authentication.
----
Whenever I use streamlink -p mpv --crunchyroll-username -Artesia-, it says that it is unable to because it expected one argument.

streamlink: error: argument --crunchyroll-username: expected one argument

It seems to work if I use anything other than my name but that doesn't really seem all that great to use a different account just for this feature (especially crunchyroll premium stuff), I think the relation to it is that it doesn't handle the - well.

**Comment by beardypig** [comment]
Does you username start with `-`?   Literally `-Artesia-`? You could try putting the username in quotes:
```
--crunchyroll-username "-Artesia-" 
```

It parses -Artesia- as `-A=rtesia`, not sure what happens to the last `-`... Doesn't really matter though :-)

**Comment by MeowMeowKins** [comment]
I forgot to mention that I have tried that too , yet with no avail have I still gotten the same, but yes, my name is literally -Artesia- with the minuses.

`streamlink -p mpv --crunchyroll-username "-Artesia-" http://www.crunchyroll.com/rezero-starting-life-in-another-world-/rezero-starting-life-in-another-world-the-end-of-the-beginning-and-the-beginning-of-the-end-part-1-702401
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: argument --crunchyroll-username: expected one argument`

**Comment by Lucain872** [comment]
Try `streamlink -p mpv --crunchyroll-username=-Artesia-`, that should work. At least it doesn't says that you need to enter an additional argument.

**Comment by MeowMeowKins** [comment]
Thanks a lot, that helped me. :), you can consider this issue solved.
