### ISSUE TITLE
Output stream delay of Twitch.tv streams

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink#620]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Original feature request: streamlink/streamlink-twitch-gui#416

I'm not entirely sure if this is part of the HLS/m3u8 specs, but Twitch includes stream timestamps in their HLS playlists, so that a playback delay to the broadcaster can be calculated by their web player (see the [`created_at`](https://dev.twitch.tv/docs/v5/reference/streams/#get-stream-by-user) property of stream records from the Twitch API). I'm aware that there still can be an additional delay added by the local player when using Streamlink.

It would be useful for applications using Streamlink to read the current timestamp or even the calculated delay, if possible. This could be outputted as debug log message or a pipe (specified by a parameter) whenever a new playlist file (or stream chunk?) is being read.

If this data can't be used, maybe all unrecognized m3u8 tags could be written as debug messages.

### Example

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#ID3-EQUIV-TDTG:2017-02-23T01:56:22
#EXT-X-MEDIA-SEQUENCE:21823
#EXT-X-TWITCH-ELAPSED-SYSTEM-SECS:87306.456
#EXT-X-TWITCH-ELAPSED-SECS:87299.595
#EXT-X-TWITCH-TOTAL-SECS:87330.456
#EXTINF:4.000,
index-0000021824-ZIka.ts
#EXTINF:4.000,
index-0000021825-7IPc.ts
#EXTINF:4.000,
index-0000021826-QQ9O.ts
#EXTINF:4.000,
index-0000021827-Outt.ts
#EXTINF:4.000,
index-0000021828-hT92.ts
#EXTINF:4.000,
index-0000021829-yrgH.ts
```

Stats of Twitch's web player:
![screenshot from 2017-02-23 02-40-38](https://cloud.githubusercontent.com/assets/467294/23242728/d3accab2-f97a-11e6-8b6b-01791e0f0bab.png)

**Comment by beardypig** [comment]
If you know how to calculate the stats from the hls tags/api calls then I'm sure we can work something out. The simplest thing might be to just print out some stats as json to the debug log or a twitch stats pipe.

**Comment by bastimeyer** [comment]
It looks like this is a bit more complicated than I first thought. Well, at least what the Twitch web player is doing. It's a bit of a pain debugging this, since the player code is quite large, is minified and contains compiled asm-js code.

From what it looks like, it is reading metadata of each mpeg-ts chunk and is then subtracting the offset time of the metadata from the current time + server time delta. I've reformatted and rewritten the part that sets the latency properties before it updates the DOM of the player stats menu:

When the `SEGMENT_CHANGED` event gets triggered, some parsing is being done (asm-js, incomprehensible) and the function below gets called with a metadata object as the first parameter:

```js
function onID3Tag( data ) {
  var time = new Date().getTime() + this.serverTimeDelta;
  data.ID3.forEach( item => {
    if ( item.id === "TDEN" ) {
      this.latencyBroadcaster = time - new Date( item.info[0] ).getTime();
    } else if ( item.id === "TDTG" ) {
      this.latencyTranscoder = time - new Date( item.info[0] ).getTime();
    }
  });
```

I'm not sure what the "TDEN" and "TDTG" values mean and how they are extracted. I've tried reading the metadata of some mpeg-ts chunks with ffmpeg, but there's nothing included other than the time offsets which are already included in the playlist (I think).

The server time delta is calculated from the `EXT-X-TWITCH-INFO` tag of the hls master playlist. Example:

```
#EXT-X-TWITCH-INFO:NODE="video-edge-c2aa38.fra02",MANIFEST-NODE-TYPE="weaver",MANIFEST-NODE="video-edge-c2aa38.fra02",SUPPRESS="true",SERVER-TIME="1487918069.54",USER-IP="xxx.xxx.xxx.xxx",SERVING-ID="a5c80608153e4fb39356a8976e2beee8",CLUSTER="fra02",ABS="false",BROADCAST-ID="24612292992",STREAM-TIME="18439.5420401",MANIFEST-CLUSTER="fra02"
```
```js
serverTimeDelta = 1000 * Number( data["SERVER-TIME"] ) - new Date().getTime()
```

-----

Is parsing the stream data really necessary here? The metadata included in the hls playlist doesn't seem to be used by the web player, but I'm not entirely sure.

[I've created a nodejs script](https://gist.github.com/bastimeyer/619de2563612f8251760366d4b524559) that reads the `created_at` property of a stream record from the Twitch API and reads all twitch related tags from the most recent hls playlist when using the source stream quality. I don't know what exactly the `EXT-X-TWITCH-ELAPSED-SYSTEM-SECS`, `EXT-X-TWITCH-ELAPSED-SECS` and `EXT-X-TWITCH-TOTAL-SECS` tags represent, but a calculation similar to what the web player is doing always yields ~30s, ~30s and ~4-8s (without using the server time delta, since I'm not reading the master playlist). Maybe the total-secs value could mean the offset time of the latest chunk. If this is the case, then it would be quite easy calculating the delay when the data of a specific chunk has been downloaded by streamlink and when it is being read by the video player.

**Comment by whytheheckme** [comment]
Did you manage to get anywhere with this? I'm very interested in getting the total latency (to encoder and then to me), as I'm trying to sync up live video data with recorded time triggers.

**Comment by bastimeyer** [comment]
No, I haven't done anything in that regard after posting this last year. Let me try to recap this...

In order to get the streaming delay, you have to get the server time delta, as described above, the stream creation date from the Twitch API and the HLS segment time, which can be found in the mpeg-ts container metadata. You can extract this data manually via `ffprobe` and `jq`, like this:
```bash
ffprobe -v error -show_format -show_streams -print_format json ${CHUNK} | jq ".format.start_time"
```

Streamlink would have to extract this information for each mpeg-ts chunk and do the calculation once the segment's content gets sent to the player. However, all segments are being concatenated by Streamlink and it needs to know when the segment's data is being read by the player. Then there's the additional player cache, of course.

The calculation itself should be something like this (just guessing here)
```
delay = localTime - ( streamCreationTime + serverTimeDelta + segmentOffsetTime )
```

**Comment by back-to** [comment]
to complicated for no real value
