### ISSUE TITLE
Crunchyroll switching subtitle languages on the fly

### ISSUE THREAD

**Issue by starchivore** [streamlink/streamlink#621]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Could it be done with a simple option like `--crunchyroll-mux-subtitles` that's similar to `--daisuki-mux-subtitles` by any chance?

Let's pick [Dragon Ball Super episode 79](http://www.crunchyroll.com/dragon-ball-super/episode-79-universe-9s-basil-the-kicker-vs-universe-7s-majin-buu-727867) as an example, I got `mpv` up and running **(without `streamlink`)** as first test:
```
C:\D\mpv\mpv.com --hwdec=yes http://www.crunchyroll.com/dragon-ball-super/episode-79-universe-9s-basil-the-kicker-vs-universe-7s-majin-buu-727867
```
Then it's showing 3 subtitle languages and I could press `J` key to switch between subtitle languages:
```
Playing: http://www.crunchyroll.com/dragon-ball-super/episode-79-universe-9s-basil-the-kicker-vs-universe-7s-majin-buu-727867
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
     Subs  --sid=1 --slang=ptBR 'ass' (ass) (external)
     Subs  --sid=2 --slang=enUS 'ass' (ass) (external)
     Subs  --sid=3 --slang=esLA 'ass' (ass) (external)
[vo/opengl] Couldn't initialize EGL
[vo/opengl] The OpenGL driver does not support OpenGL 3.x
AO: [wasapi] 44100Hz stereo 2ch float
Using hardware decoding (dxva2-copy).
VO: [opengl] 848x480 => 853x480 nv12
[osd/libass] PlayResX undefined, setting to 384
AV: 00:00:10 / 00:23:22 (0%) A-V:  0.000 Cache:  4s+98KB
```

It's going through SOCKS5 proxy and the speed ain't good for streaming at all, that's why I've gotta go for `streamlink` with `--crunchyroll-session-id` instead:
```
streamlink -p "C:\D\mpv\mpv.exe --hwdec=yes" --crunchyroll-session-id %sess_id% "www.crunchyroll.com/dragon-ball-super/episode-79-universe-9s-basil-the-kicker-vs-universe-7s-majin-buu-727867" 480p
```

The 3rd line is `[cli][info] Opening stream: 480p (hls)` as shown below:
```
[cli][info] Found matching plugin crunchyroll for URL www.crunchyroll.com/dragon-ball-super/episode-79-universe-9s-basil-the-kicker-vs-universe-7s-majin-buu-727867
[cli][info] Available streams: 720p_alt2, 360p_alt, 1080p_alt2, 480p_alt2, 360p_alt2, 240p_alt2, 240p_alt, 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: C:\D\mpv\mpv.exe --hwdec=yes
```

Once `mpv` was started, I pressed the `J` key but the `OSD` was displaying `Subtitles: no` instead of switching to next available subtitle language. Pressing the `v` key and the OSD would alternate between `Subtitles hidden` and `Subtitles visible (but no subtitles selected)` while there's no way to turn off the English (soft ones in `ass` format) subtitles.

Now let's take a look at the [same episode @ daisuki.net](http://www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16280.html) and see how it goes:
```
streamlink -p "C:\D\mpv\mpv.exe --hwdec=yes --slang=English" --daisuki-mux-subtitles "www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16280.html" 480p
```

The 3rd line is `[cli][info] Opening stream: 480p (muxed-stream)` as follows:
```
[cli][info] Found matching plugin daisuki for URL www.daisuki.net/us/en/anime/watch.DRAGONBALLSUPERUniverseSurvivalsaga.16280.html
[cli][info] Available streams: 360p (worst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 480p (muxed-stream)
[cli][info] Starting player: C:\D\mpv\mpv.exe --hwdec=yes --slang=English
```

So Crunchyroll was showing `(hls)` and Daisuki was showing `(muxed-stream)` respectively, the latter one was done by muxing `srt` and `hls` with `ffmpeg` while the former one should be simply showing both `ass` and `hls` simultaneously or something?

Maybe they've got the code written already and it should be quite straightforward to borrow something?

[youtube-dl/crunchyroll.py at master · rg3/youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py)

**Comment by beardypig** [comment]
Do the subtitles show when using streamlink? I assumed  the subs were "hardsubs" for crunchyroll, but you know what they say about assumptions... 

It should be quite straightforward to add generic external subtitles for `hls`, unless they're doing something special. 

I'll take a look ;-)

**Comment by starchivore** [comment]
Awesome, many thanks for your help as usual.

Both `crunchyroll.com` and `daisuki.net` are soft-subbed for pretty much everything, that's why I could play with `--crunchyroll-locale en_US` or `--crunchyroll-locale es_LA` or `--crunchyroll-locale pt_BR` or `--crunchyroll-locale ja_JP` for the corresponding subtitle language.

For some reasons `--crunchyroll-locale ja_JP` would gimme Portuguese instead of raw / no subs at all, that made me LOL.

Obviously English subs were shown with `--crunchyroll-locale en_US` but not exactly sure why it's still showing English subs when I got rid of all `--crunchyroll-locale` options, basically that didn't give me any choices to turn the subs off whatsoever and I just ended up with two "competing" sets of English subs on the screen after loading another set of external English subs (`mks` format from one of those Fansub groups and they're doing fancy stuff like Karaoke style for the lyrics) with much better translation.

**Comment by beardypig** [comment]
Looks like the streams that `streamlink` uses have hardsubs. I also got Portuguese when using `--locale ja_JP` lol indeed, but the stream info had `'hardsub_lang': ''` - which is strange. 

Looks like `youtube-dl` use an alternative stream source, `youtube-dl` uses the Desktop xml API and `streamlink` uses the mobile `json` API. With the `json` API you can access some `1080p` content without having to login, but you cannot disable the subtitles as far as i can tell. 

We could add an XML API version for those who either want no subs or have a subscription anyway...

**Comment by starchivore** [comment]
OK, that's it and I wasn't really getting dumber / older (or a little bit of both) when I saw Portuguese with `--crunchyroll-locale ja_JP` then. That almost scared me for nothing.

I wasn't expecting them to put so many different flavors of the same episode on their servers, maybe that shouldn't be such a surprise since they've got more than a million paid subscribers already.
