### ISSUE TITLE
[META] Issues disappearing 

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#622]
Has anyone else noticed that a few issues have disappeared? 

Both #617 and #547 have disappeared... is it possible for users to delete their own issues? Maybe it's because the user that created them has been deleted/banned/flagged? I remember that @starchivore created #617, and that account is 404ing. Possibly @starchivore was flagged for spam or as a bo, which can cause the account to 404t?!

Quite annoying that issues can just disappear. 

Hey, @github don't delete issues please!

**Comment by cdrage** [comment]
Odd... seems that one of the issues is back and @starchivore haha. GitHub issues?

**Comment by beardypig** [comment]
Flagged for spam/bot is my guess... @starchivore?

**Comment by beardypig** [comment]
It happened to me a few weeks back, my profile was 404ing. Not sure if my issues disappeared or not. I sent them an email and it was sorted in 30 mins or so. Still, kind of a pain if the issues disappear... I was trying to reference it will working on #617 :-D

**Comment by starchivore** [comment]
Yeah, that's exactly what happened to other accounts as well:

http://a-habakiri.hateblo.jp/entry/20161208accountflagged

**Comment by beardypig** [comment]
Seems like posting loads of URLs sets off the github police. I think mine was flagged when posting loads of Turkish streams hehe

**Comment by gravyboat** [comment]
I noticed this with another issue down in the 400 range that @beardypig was working on. It's pretty annoying. I'm not sure why @github is flagging us or removing these, we have over 700 stars on this project now so it's not as though it is someone abusing github.

**Comment by beardypig** [comment]
I think it's when people post a bunch of URLs on issues/PRs it flags that user as a spambot, which in turn hides all their "spam" (aka issues). Rather than targeting the project.

**Comment by gravyboat** [comment]
Yeah I can see that since a lot of people who are posting these issues are from new accounts but there should still be some kind of confirmation or automated review to see if they continue to spam. It seems ridiculous to get an issue removed when the user posts 3 links.

**Comment by beardypig** [comment]
Oh definitely, it really is a case of bots gone wild... Not much @github will do about it though, I believe it has been reported to them multiple times...

**Comment by WazZ87** [comment]
Hi,

Yep ! Account has been flagged, just a little message to the support team, now it's ok !

**Comment by beardypig** [comment]
@back-to looks like you got hit with this too?

**Comment by starchivore** [comment]
Oh no, looks like they could use some botty training again?

**Comment by back-to** [comment]
```
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
```

well this account is only ~3 months old, so its easy to get false flagged as a bot.

**Comment by bastimeyer** [comment]
Interesting... Most of your comments don't even include external links.
https://github.com/search?utf8=%E2%9C%93&q=commenter%3Aback-to

If we knew what is causing accounts to be flagged, we could include a message about this for new(ish) accounts in the contributing guide.

**Comment by back-to** [comment]
Well it happened again,
did I mention his Issue to often and got him banned? Funny if true ...

https://github.com/Ordval

https://github.com/streamlink/streamlink/issues/859

**Comment by beardypig** [comment]
Looks like @Ordval needs to drop an email to github ... blame the bots again...
