### ISSUE TITLE
Auto detect Twitch (and other services?) VODs and enable the --player-passthrough hls option when using them

### ISSUE THREAD

**Issue by denizgenc** [streamlink/streamlink#624]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I use Streamlink to watch Twitch VODs as well as live streams, but it's a bit tiring to always have to include the (quite long) `--player-passthrough hls` option to enable seeking through the VOD.  
I'm not sure if there's any use case for watching Twitch VODs with the default options (though I'd be happy to learn of reasons why).

Because of this I suggest auto-detecting Twitch VOD URLs and enabling the `--player-passthrough hls` option automatically. Usually when I introduced Livestreamer (and now Streamlink) to friends with less experience with the command line (and even less with reading documentation), it would be kind of awkward to explain that an extra option was needed to enable what is to the user basic functionality when watching VODs. It would streamline the user experience not to have to do that.

### Reproduction steps / Stream URLs to test

1. Run `streamlink [Twitch VOD url]` - can't seek
2. Run `streamlink [Twitch VOD url] --player-passthrough hls` - can seek 

Here's a highlight that should stay up for a while: https://www.twitch.tv/videos/13075086  
Here's a past broadcast that is active as of writing this post (will expire within 2 weeks, as per Twitch's policy): https://www.twitch.tv/videos/124130684  
(I do remember that Twitch used to have a different URL convention for VODs, something like twitch.tv/c/xxxx or twitch.tv/v/xxxxx - I don't have any examples of these URLs. I think they were all changed recently, but I'm not sure.)

### Environment details (operating system, python version, etc.)

Windows 7 Professional 64 bit, Service Pack 1  
Python 3.6.0  
mpv 0.24.0

**Comment by bastimeyer** [comment]
There's a discussion about rewriting the passthrough logic in #134 (or see https://github.com/streamlink/streamlink/issues/134#issuecomment-264744116).

I don't think that it's a good idea to automatically choose the passthrough option based on the input url. There are players that don't support HLS for instance.

You could write an alias for Twitch vods, so that streamlink uses certain parameters or a certain config file.

**Comment by gravyboat** [comment]
I agree with @bastimeyer. I don't want to pass through any additional options that could potentially impact users without their knowledge. While passing through the option is annoying, Streamlink not working on a VOD because of player support seems far more problematic to me.

**Comment by dojima** [comment]
With Livestreamer, you could make a plugin-specific config file by appending .[plugin name] to a config file in the config directory.  For example, I have specific options for Twitch in the configuration file livestreamerrc.twitch.  I assume the same thing works if you make a streamlinkrc.twitch file with the "player-passthrough=hls" flag.

**Comment by gravyboat** [comment]
There hasn't been much discussion on this and I think we've come to a general conclusion so I'm going to close this.
