### ISSUE TITLE
plugins.afreeca: The afreeca domain has changed to https://www.sooplive.co.kr/

### ISSUE THREAD

**Issue by xueli12** [streamlink/streamlink#6246]
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

6.11.0

### Description

The afreeca domain has changed to https://www.sooplive.co.kr/. The website has also been rebranded as "sooplive". Although https://www.afreecatv.com/?hash=bora is still accessible, visiting this link will redirect you to https://www.sooplive.co.kr/. The afreeca plugins are still functioning normally, but it is uncertain when they will cease to work.

### Debug log

no log

**Comment by B4TT3RY** [comment]
For now, simply changing the `afreecatv.com` domain in the code to `sooplive.co.kr` should work fine.

![Image](https://github.com/user-attachments/assets/01cd58d0-7e11-4701-b3cf-48ce9fb01886)

**Comment by xueli12** [comment]
@minibox24 @bastimeyer Since Afreeca rebranded to Soop, I noticed that the CDN used for live streams has changed. Using the original CDN, I tested and found that downloads are not possible. I recommend changing return_type to gcp_cdn:

def _get_stream_info(self, broadcast, quality, rmd):
    params = {
        "return_type": "gcp_cdn",
        "broad_key": f"{broadcast}-common-{quality}-hls",
    }
    res = self.session.http.get(f"{rmd}/broad_stream_assign.html", params=params)
    return self.session.http.json(res, schema=self._schema_stream)

**Comment by bastimeyer** [comment]
No, the `return_type` should be what's been returned by the `_get_channel_info()` response, which includes the `CDN` attribute in its JSON data. I'll have a look at this later today with a quick refactor of the plugin.
