### ISSUE TITLE
Amazon Cloud HLS Stream?

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#625]
- [x] This is a bug report.
### Description
I am attempting to watch a stream with the following URL:

http://hlsserver.metv.com/HLSStream?channelId=metv&affilId=1&offset=1

### Expected / Actual behavior
Play the stream as normal.
...

### Reproduction steps / Stream URLs to test

1. ... streamlink "hlsvariant://http://hlsserver.metv.com/HLSStream?channelId=metv&affilId=1&offset=1" best
2. ... OR streamlink "hlsvariant://http://hlsserver.metv.com/HLSStream?channelId=metv&affilId=1&offset=1 verify=no" best
3. ...

### Environment details (operating system, python version, etc.)
Windows 10 & Mythbuntu 16.04
...

### Comments, logs, screenshots, etc.

Windows 10:

[cli][info] Found matching plugin stream for URL hls://http://hlsserver.metv.com/HLSManagedFile/01.m3u8?affilId=1 verify=no
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[stream.hls][error] Failed to open segment 235671: Unable to open URL: https://video.metv.com/metv/20170128T020331-01-4497517.ts ([Errno 2] No such file or directory)

WITHOUT verify=no:

[cli][info] Closing currently open stream...
[stream.hls][error] Failed to open segment 235677: Unable to open URL: https://video.metv.com/metv/20170128T020331-01-4497523.ts ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645))

Mythbuntu:

[cli][error] Could not open stream: Unable to open URL: https://hlsserver.metv.com/HLSManagedFile/01.m3u8?affilId=1 (__str__ returned non-string (type Error))

WITHOUT verify=no:

[cli][error] Could not open stream: Unable to open URL: https://hlsserver.metv.com/HLSManagedFile/01.m3u8?affilId=1 (("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",))

...

**Comment by beardypig** [comment]
Can you load any of those URLs in your browser? When I try it asks for a certificate, you can use the [`--http-ssl-cert-crt-key`](https://streamlink.github.io/cli.html#cmdoption-http-ssl-cert-crt-key) option to specify it if you need to, you will need the cert and key.

**Comment by RedPenguin2** [comment]
I can't seem to open any links in browser.

I found the URL in an Android/iOS App and decompiled the Android App but seem to not be able to find anywhere I can find the cert.

**Comment by beardypig** [comment]
Maybe if you share the name of the app, or apk someone else can take a look?

**Comment by RedPenguin2** [comment]
It's the MeTV Network App (The Classic TV Channel) app.

**Comment by RedPenguin2** [comment]
I did find a client.p12 file in both the iOS and Android version as the only certificate files at all.

I did try converting them to PEM and CRT & Key but still no luck.

The file seems to be the exact same size on both iOS and Android.

**Comment by beardypig** [comment]
Interesting, I'll take a look when I get time :-)

**Comment by RedPenguin2** [comment]
I have the client.p12 file and password I gathered from the apk but wasn't sure if that was the type of thing I should post here publicly.

**Comment by beardypig** [comment]
Don't post it here, if you want you can email to me, my address is on my profile page.

**Comment by RedPenguin2** [comment]
Just as a quick test to make sure I 100% had the correct certs, I found a Chrome Add-On that allows m3u8 files to play directly in Chrome.

The stream appears to be playing perfectly so I at least know it's possible to play then.

**Comment by beardypig** [comment]
Alright, sounds promising. I will take a look at it, probably in the next couple of days :-)

**Comment by beardypig** [comment]
Solved out of band; it involved extracting the `crt` and `key` from the `apk` and using the [`--http-ssl-cert-crt-key`](https://streamlink.github.io/cli.html#cmdoption-http-ssl-cert-crt-key) option to supply them to `streamlink`.

**Comment by RedPenguin2** [comment]
Just a quick question before closing this issue, what is Streamlink doing differently to download the HLS stream compared to ffmpeg? At first I used ffmpeg to test because it could use WIndows's SSL cert collection.

ffmpeg's copy was riddled with more errors in the audio then I could count yet streamlink once I got the certs working, recorded a perfect copy of the stream free of any known errors.

I noticed streamlink has ffmpeg in it's installer.

**Comment by karlo2105** [comment]
ffmpeg is only used for audio muxing where audio is separated from video.

**Comment by beardypig** [comment]
It's as @karlo2105 said, we include ffmpeg but only use it in a handful of specific cases. I guess that if you used ffmpeg to download the stream it might not be as robust as streamlink, it's not really designed for downloading streams :-) Depending on the options you used it might transcode the stream or try to fix errors. 

In summary, not sure :-D

**Comment by beardypig** [comment]
I'm going to close this as the original request was solved. I don't think a plugin for this site will be included as it requires some private data that we probably don't want to include :-)

**Comment by 27hectormanuel** [comment]
@RedPenguin2 would you share the client.p12 with me. I'm trying to access the metv stream
