### ISSUE TITLE
plugins.vidio: 403 Client Error

### ISSUE THREAD

**Issue by nextux** [streamlink/streamlink#6252]
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 6.11.0

### Description

Error unable to open url 403 client error.

### Debug log

[cli][debug] OS:         macOS 15.0
[cli][debug] Python:     3.13.0
[cli][debug] OpenSSL:    OpenSSL 3.3.2 3 Sep 2024
[cli][debug] Streamlink: 6.11.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.6.1
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.20.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.26.2
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://www.vidio.com/live/205-indosiar
[cli][debug]  --loglevel=debug
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/205-indosiar
[plugins.vidio][debug] self.id='205' has_token=False
[utils.l10n][debug] Language code: en_AU
error: Unable to open URL: https://etslive-v3-vidio-com-tokenized.akamaized.net/drm/hls/205/master.m3u8 (403 Client Error: Forbidden for url: https://etslive-v3-vidio-com-tokenized.akamaized.net/drm/hls/205/master.m3u8)

**Comment by bastimeyer** [comment]
> https://www.vidio.com/live/205-indosiar

Acquiring a stream-token for watching this specific stream requires authentication, which is not supported by the plugin. You can already see on their site that a login is required. Other streams are working fine.

I've tried 10 different temporary/disposable email services for creating a test account. All of them were rejected. No interest from my side to implement authentication for that plugin. It's not worth my time battling with their user account system...

If you want authentication, then please open a pull request with the necessary plugin changes, including login data for others to test, and it'll be reviewed.

Closing...
