### ISSUE TITLE
How to get it done like the way he doing?

### ISSUE THREAD

**Issue by umarimtiaz11** [streamlink/streamlink#626]
hello all, have a look at the URL http://sasastreams.pw/fox.php?title=4d93d2b4f041a55045c612608a6562d7

What exactly he is doing to stream all NBA & NHL Games, how is he getting direct m3u8 from official fox sports and embedding m3u8 on his own server to provide stream? any suggestions please

**Comment by gravyboat** [comment]
This isn't something we'll be able to investigate or help with as this person is definitely breaking some rules/laws they've agreed to with this provider (as stupid as those rules/laws may be). As such I'm going to close this.
