### ISSUE TITLE
plugins.soop: Adding plug-ins in py3.11 environment does not work

### ISSUE THREAD

**Issue by small05** [streamlink/streamlink#6263]
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

plugins.soop: Adding plug-ins in py3.11 environment does not work

### Description

I installed streamlink version 6.11 and py3.11 in the new Debian system. After creating the new plug-in soop.py, it did not work. It prompted that the matching plug-in could not be found. After deleting afreeca.py, execute streamlink --plugins will still show the name of the afreeca plug-in, but there will be no soop plug-in name.

In another ubuntu22 system, py3.10 version and streamlink6.5 version can work normally after adding new soop.py and deleting afreeca.py.

Is the problem related to py3.11? I've been debugging for 2 days and still haven't solved the problem. Please help me.

### Debug log

$ streamlink --loglevel=debug https://play.sooplove.co.kr/xxxx
[cli][debug] OS:         Linux-6.1.0-26-amd64-x86_64-with-glibc2.36
[cli][debug] Python:     3.11.2
[cli][debug] OpenSSL:    OpenSSL 3.0.14 4 Jun 2024
[cli][debug] Streamlink: 6.11.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2022.9.24
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://play.sooplove.co.kr/xxxx
[cli][debug]  --loglevel=debug
error: No plugin can handle URL: https://play.sooplove.co.kr/xxxx

$ streamlink --plugins
Available plugins: abematv, adultswim, afreeca, albavision, aloula, app17, ard_live, ard_mediathek, artetv, atpchallenger, atresplayer, bbciplayer, bfmtv, bigo, bilibili, blazetv, bloomberg, brightcove, btv, cbsnews, cdnbg, ceskatelevize, chzzk, cinergroup, clubbingtv, cmmedia, cnbce, cnews, dailymotion, dash, delfi, deutschewelle, dlive, dogan, dogus, douyin, drdk, earthcam, euronews, filmon, goltelevision, goodgame, googledrive, gulli, hiplayer, hls, http, htv, huajiao, huya, indihometv, invintus, kick, kugou, livestream, lnk, lrt, ltv_lsm_lv, mangomolo, mdstrm, mediaklikk, mediavitrina, mitele, mixcloud, mjunoon, mrtmk, n13tv, nasaplus, nhkworld, nicolive, nimotv, nos, nowtvtr, nrk, okru, olympicchannel, oneplusone, onetv, openrectv, pandalive, piaulizaportal, picarto, piczel, pixiv, pluto, pluzz, radiko, raiplay, reuters, rtpa, rtpplay, rtve, rtvs, ruv, sbscokr, showroom, sportal, sportschau, ssh101, stadium, steam, streamable, streann, stv, svtplay, swisstxt, telefe, telemadrid, tf1, tiktok, trovo, turkuvaz, tv360, tv3cat, tv4play, tv5monde, tv8, tv999, tvibo, tviplayer, tvp, tvtoya, twitcasting, twitch, ustreamtv, ustvnow, vidio, vimeo, vinhlongtv, vk, vkplay, vtvgo, welt, wwenetwork, youtube, yupptv, zattoo, zdf_mediathek, zeenews

**Comment by bastimeyer** [comment]
> Adding plug-ins in py3.11 environment

Which is 100% intended, as you're not supposed to edit any Python distribution unless you know exactly what you're doing.

Streamlink loads plugins lazily unless it's installed in an editable distribution from git. This means that plugin matchers and plugin arguments are pre-computed and stored outside of the plugin modules.

Loading custom plugins, either new ones or overriding existing ones, must be done by sideloading them, which is explained in the documentation:
https://streamlink.github.io/latest/cli/plugin-sideloading.html

However, if you'd a look at the commit log on the master branch, or if you'd searched on the issue tracker before opening this thread, you'd seen that the afreeca plugin was already turned into the new soop plugin. All you had to do was install Streamlink from the master branch, either via pip or by using the nightly AppImage builds. Also explained in the docs:
https://streamlink.github.io/latest/install.html
