### ISSUE TITLE
Plugin: Add support for showroom-live.com

### ISSUE THREAD

**Issue by wlerin** [streamlink/streamlink#627]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Showroom is a Japanese streaming site, used by artists, entertainers, and amateur streamers. It does not provide VOD services.

### Expected behaviour:

For this code:

    >>> import streamlink
    >>> streams = streamlink.streams("https://www.showroom-live.com/48_Tomu_Mutou")

To return a list of streams (or None if she's not streaming)

### Actual behaviour

Raises `streamlink.exceptions.NoPluginError`

### [Working Plugin](https://github.com/streamlink/streamlink/compare/master...wlerin:master?diff=unified&name=master)

I have written a Showroom plugin, and tested that it correctly returns the desired streams. Some additional testing is required before I create a pull request, but I thought I'd open an issue first and maybe get general feedback or even help resolving some of the issues below.

### API Urls
More (mostly API) urls besides those used in the proposed plugin:

- [Sample Event Room List](https://www.showroom-live.com/event/all_rooms?event_id=1364)
- [Live broadcasts w/ streaming links](https://www.showroom-live.com/api/live/onlives)
- [Upcoming lives in the Idol genre](https://www.showroom-live.com/api/live/upcoming?genre_id=102)
- [Next live for a room](https://www.showroom-live.com/api/room/next_live?room_id=61576)
- [Video Caption](https://www.showroom-live.com/api/live/telop?room_id=61627)
- [Comment Log](https://www.showroom-live.com/api/live/comment_log?room_id=61627)
- [Ranking Summary](https://www.showroom-live.com/api/live/summary_ranking?room_id=61627)

(anything with "room_id" in the url will probably not be interesting unless the room is live)

#### 1. Caption
Live rooms usually have a "telop" or caption, that displays at the top of the video and usually describes whatever's going on in the room that day. The plugin stores this, but does nothing with it. Possibly it could be muxed with the stream like a subtitle? More investigation required.

edit: It appears that I need to support both text and NoneType values for this. For the moment I'm fudging with validate.transform(validate.text).

#### 2. Stream Title
In relation to Hubcapp's title-related work, there are five options for determing a room's title:
1. The "room_url_key", taken either from _get_stream_info, or the first url pattern. This key is meaningful for official rooms, but random and meaningless for amateur rooms.
2. The actual page title. This is almost always in Japanese.
3. The "telop" or caption, displayed at the top of a live video. Also almost always in Japanese.
4. A translation of the title or telop. Providing this in streamlink itself is unfeasible.
5. The numerical room_id. This is as meaningless to humans as the amateur room titles.

Currently, the plugin uses 1., although in one specific case (when the second url pattern is used and the stream title is requested before _get_streams is called) this requires fetching the same data from the api twice.

#### 3. VR Streams
Showroom provides no support for VR on PC. There are VR streams viewable on their mobile app, but even if it could capture the necessary streaming urls, the raw video needs to be remapped to a different projection.

#### 4. HLS Support
~~The one time I attempted to record the HLS sources with FFmpeg, the result was a catastrophe (vast majority of every video recorded was missing). The problem was probably on my end but I did not investigate further. I have not tested them at all using this plugin.~~

HLS streams will not be supported.

#### 5. Unstable RTMP Streams
Using FFmpeg or MPV to record/view the rtmp streams results in frequent disconnections for some less stable streams. It would be useful to keep restarting these until the API reports the live has finished, but this is probably not a job for the Showroom plugin. It already won't return streams once the live ends, but in my experiments with FFmpeg a recording started exactly when the stream ends sometimes hangs indefinitely. Occasionally during a particularly bad stream it also enters a "ping loop of death", where it just keeps pinging the server and never receives any data. I handle this manually in another script I wrote specifically for Showroom, but I don't think this plugin can do anything about it.

#### 6. The 720p Mystery
On very rare occasions, a Showroom stream will be available in 720p. I never had the foresight to check the api data when that happens, and it's impossible to tell from the web player when this is the case. To account for this...

#### 7. Stream Weighting
I know of no way to accurately determine the height of an rtmp stream. All the API provides is "original spec" and "low spec"--usually 360p and 198p. However, because of the mystery 720p streams, which are almost certainly "original spec", I have set the weighting for "original spec" to 720, and that for "low spec" to 198. This may cause difficulties with the accurately-reported HLS frame heights (or not-so-accurately: low for HLS reports as 160p)

#### 1. Events, Campaigns, Schedule, Onlive
[Event pages](https://www.showroom-live.com/event/daruma_big), [Campaign pages](https://www.showroom-live.com/campaign/akb48_sr), and the [Schedule](https://www.showroom-live.com/timetable) and [Onlive](https://www.showroom-live.com/onlive) pages all provide lists of rooms, almost like a playlist.

#### 2. Comments
Recording comments along with the video.

**Comment by beardypig** [comment]
Real nice looking plugin you got there, looks good. 

If the HLS streams are not working maybe you should leave them out until you determine what is stopping them for working correctly.

**Comment by wlerin** [comment]
@beardypig The HLS stream seems to play alright so far, but I'll try a few more things.

In the meantime, is there a way to have a schema validate with either a str or NoneType? [This line](https://github.com/wlerin/streamlink/blob/master/src/streamlink/plugins/showroom.py#L53) fails when the stream has no telop set (presumably it's `null`). I can fudge it with `validate.transform(validate.text)` but that seems overkill.

**Comment by beardypig** [comment]
There is `validate.any`, so you could do:
```python
validate.any(None, validate.text)
```
```python
>>> s = validate.Schema(validate.any(None, validate.text))
>>> s.validate(None)
>>> s.validate("hello")
'hello'
>>> s.validate(1)
    raise exception("Unable to validate {0}: {1}".format(name, err))
streamlink.exceptions.PluginError: Unable to validate result: 1 does not equal None or Type of 1 should be 'str' but is 'int'
```

**Comment by wlerin** [comment]
Ah! Excellent, just what I needed. Thanks.
