### ISSUE TITLE
Filtering "screen" instead of black screen?

### ISSUE THREAD

**Issue by Chris230291** [streamlink/streamlink#6283]
### Checklist

- [x] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Collaboration

- [x] My request is genuine and in the best interest of the project
- [x] [I will provide feedback should a pull request be opened with a new feature implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Description

In my testing, the ad filtering seems to be working well with Pluto TV, thanks!
Could we have the option to show some sort of splash screen, perhaps with sound, instead of just a black screen/nothing?
I am using Streamlink with TVHeadend to watch Pluto TV channels, and while it has been working well (after I increased the TVH timeout), a blank screen isn't ideal.

**Comment by bastimeyer** [comment]
This is not how it works. Ad filtering means simple segment discarding in segmented streams like HLS or DASH. Replacing content means reencoding, which isn't done here. And inserting a different bitstream is a discontinuity, which just as ad segments needs to be avoided (ignoring the fact that the transition from ad filtering to regular stream content is also a discontinuity).
