### ISSUE TITLE
Conflicting option string --afreeca-username

### ISSUE THREAD

**Issue by MistressSaeko** [streamlink/streamlink#6315]
### Checklist

- [x] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the problem](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 7.0.0

### Description

I try to open up any stream in StreamLink and am greeted with this error:

> argparse.ArgumentError: argument --afreeca-username: conflicting option string: --afreeca-username

This also happens when StreamLink is run without any arguments.

### Debug log

```text
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "C:\Streamlink\pkgs\streamlink_cli\main.py", line 967, in main
    setup(parser)
  File "C:\Streamlink\pkgs\streamlink_cli\main.py", line 922, in setup
    setup_plugin_args(streamlink, parser)
  File "C:\Streamlink\pkgs\streamlink_cli\argparser.py", line 1488, in setup_plugin_args
    group.add_argument(parg.argument_name(pname), **parg.options)
  File "argparse.py", line 1495, in add_argument
  File "argparse.py", line 1696, in _add_action
  File "argparse.py", line 1509, in _add_action
  File "argparse.py", line 1645, in _check_conflict
  File "argparse.py", line 1654, in _handle_conflict_error
argparse.ArgumentError: argument --afreeca-username: conflicting option string: --afreeca-username
```

**Comment by bastimeyer** [comment]
That should not be happening on 7.0.0 unless you've modified Streamlink's plugins or did something else weird with your config file.

The `afreeca` plugin was renamed to `soop` and old plugin arguments (with the `afreeca` prefix) were added as a fallback.
https://streamlink.github.io/changelog.html#streamlink-7-0-0-2024-11-04

So, did you modify any plugins, or are you sideloading/overriding plugins?
https://streamlink.github.io/cli/plugin-sideloading.html

Please also post the full content of your config file and/or plugin config file (with redacted auth data).
https://streamlink.github.io/cli/config.html

----

```
$ mkdir /tmp/streamlink-7.0.0
$ cd /tmp/streamlink-7.0.0
$ python -m venv .
$ source ./bin/activate
$ pip install streamlink==7.0.0
$ streamlink --no-config --afreeca-username foo -l debug
[cli][debug] OS:         Linux-6.12.1-1-git-x86_64-with-glibc2.40
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.4.0 22 Oct 2024
[cli][debug] Streamlink: 7.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  --no-config=True
[cli][debug]  --loglevel=debug
[cli][debug]  --afreeca-username=********
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io/
```

**Comment by MistressSaeko** [comment]
No. I have not modified or sideloaded any plugins. I was using StreamLink through the Twitch GUI front-end. I first tried to open a stream through it, but it errored out. So I decided to try StreamLink directly to see what the error was and that's what it spit out at me.

> # The format is option=value
> # Lines starting with a # are considered comments and are ignored.
> 
> # Please see the Streamlink CLI documentation for all available options
> # and their descriptions. All leading dashes need to be ignored,
> # e.g. --default-stream=STREAM becomes default-stream=STREAM
> # https://streamlink.github.io/cli.html#command-line-usage
> 
> 
> # By default, Streamlink will attempt to locate VLC on your system
> # and use that, but you can also specify the location of a player yourself.
> 
> # Important: You must use a quoted path if there are spaces in it. This
> # is because the player command is parsed like a shell command, to allow
> # parameters to be passed to the player when not using the player-args option.
> 
> # Here are a couple of player examples:
> 
> # VLC
> #player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
> #player="C:\Program Files\VideoLAN\VLC\vlc.exe"
> # Using --file-caching is recommended, but is only supported in VLC 2.0+
> #player="C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=5000
> #player="C:\Program Files\VideoLAN\VLC\vlc.exe" --file-caching=5000
> 
> # MPC-HC, must be at least version 1.7 to be used
> #player="C:\Program Files (x86)\MPC-HC\mpc-hc.exe"
> #player="C:\Program Files\MPC-HC\mpc-hc64.exe"
> 
> # MPV
> #player="C:\Program Files\mpv-x86_64\mpv.exe"
> 
> # Alternatively, player arguments can also be set via the player-args option.
> # Please see the documentation of the used player for its available arguments.
> 
> # VLC
> #player-args=--no-one-instance --play-and-exit
> #player-args=--qt-minimal-view
> #player-args=--file-caching=5000
> 
> # MPC-HC
> #player-args=/new /play /close
> 
> # MPV
> #player-args=--keep-open=no --force-window=yes
> #player-args=--no-border
> #player-args=--cache=yes --demuxer-max-bytes=2M
> 
> 
> # Custom player window titles can automatically be set when a supported player
> # and plugin are used. The title option has several variables available, which
> # can show the stream's author, category/game, title, URL, etc.
> #title={author} - {category} - {title}
> 
> 
> # Use this if you want to transport the stream to the player via a named pipe.
> #player-fifo
> 
> # Use one of these if you want to transport the stream to the player via HTTP.
> # The continuous option will allow the player to stop and resume the output.
> #player-http
> #player-continuous-http
> 
> # Use player-passthrough if you want Streamlink to only pass the resolved URL
> # to your player and let it handle the transport of the stream itself.
> # Please note that the player needs to support the streaming protocol
> # and that custom stream implementations in plugins will become unavailable,
> # same as buffering options and those which change the network behavior.
> #player-passthrough=http,hls
> 
> # By default, Streamlink will close the player when the stream is over.
> # Use this option to let the player stay or close itself instead.
> #player-no-close
> 
> # Show the player's console output
> #verbose-player
> 
> # FFMPEG is used to mux separate video and audio streams in to a single
> # stream so that they can be played. The full or relative path to ffmpeg
> # or avconv should be specified here.
> #ffmpeg-ffmpeg=C:\Program Files (x86)\Streamlink\ffmpeg\ffmpeg.exe
> ffmpeg-ffmpeg=C:\Streamlink\ffmpeg\ffmpeg.exe
> 
> # Log level, default is info
> #loglevel=debug
> 
> # Number of threads to use when streaming HLS streams
> #hls-segment-threads=1

**Comment by bastimeyer** [comment]
> No. I have not modified or sideloaded any plugins

That doesn't make sense. You don't have a clean 7.0.0 install.

> argparse.ArgumentError: argument --afreeca-username: conflicting option string: --afreeca-username

This error message implies that there's a custom `afreeca` plugin being loaded first, so the official `soop` plugin's fallback plugin-arguments (with the `afreeca` prefix) conflict with the ones that were already initialized by the custom plugin.

Check your plugin sideloading path (see the linked docs) and make sure that you are indeed using Streamlink 7.0.0 in a **clean** install directory.

This is not a Streamlink bug.

----

Btw, this config file is outdated and "incompatible" with recent versions of Streamlink. It's the default config file of `<6.0.0`:
- https://github.com/streamlink/windows-builds/blob/5.5.1-2/files/config
- https://github.com/streamlink/windows-builds/blob/6.0.0-1/files/config
- https://github.com/streamlink/windows-builds/blob/7.0.0-1/files/config

The installer gives you the option to overwrite it with a newer one when installing.

**Comment by MistressSaeko** [comment]
Deleting the afreeca.py plugin from the plugins folder fixed it. It's now working as it should.
