### ISSUE TITLE
stream.dash: can`t play live DASH with no MPD@publishTime attribute

### ISSUE THREAD

**Issue by zhenyahacker** [streamlink/streamlink#6322]
### Checklist

- [x] This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the problem](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

7.0.0+22.g7c2940c

### Description

Live manifest URL: https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd
Copy of manifest: https://gist.github.com/zhenyahacker/b4525bbd9203dde87041532e295d49fa

Streamlink can`t parse this manifest because "publishTime" attribute is absent.

I`ve investigated a bit: this manifest has SegmentTimeline sheme of generating sengment filename and thus no "publishTime" needed to access media.

For example, yt-dlp easily downloads all momentary available segments:

```
yt-dlp "https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd" --allow-un -f video_1920x1080_avc1_video-v1
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[generic] Extracting URL: https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd
[generic] manifest: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] manifest: Extracting information
[info] manifest: Downloading 1 format(s): video_1920x1080_avc1_video-v1
[dashsegments] Total fragments: 10
[download] Destination: manifest [manifest].mp4
[download] 100% of   30.67MiB in 00:00:01 at 15.61MiB/s
```

### Debug log

```text
streamlink "https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd" best --loglevel=debug



[session][debug] Loading plugin: dash
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.12.7
[cli][debug] OpenSSL:    OpenSSL 3.0.15 3 Sep 2024
[cli][debug] Streamlink: 7.0.0+22.g7c2940c
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --ffmpeg-ffmpeg=C:\Program Files\Streamlink\ffmpeg\ffmpeg.exe
[cli][info] Found matching plugin dash for URL https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd
[plugins.dash][debug] URL=https://s25617.cdn.ngenix.net/mdrm/CH_TNTHD/manifest.mpd; params={}
error: Failed to parse MPD manifest: Could not find required attribute MPD@publishTime
```

**Comment by bastimeyer** [comment]
See #6324

That won't help you with accessing the stream though, as Streamlink doesn't support any kinds of DRM schemes, as noted in the contributing guidelines. This DASH stream is DRM protected, so you won't be able to access it.
