### ISSUE TITLE
plugins.bilibili: HLSStream links obtained via cookies could not open

### ISSUE THREAD

**Issue by k3bc999** [streamlink/streamlink#6331]
### Checklist

- [x] This is a [plugin issue](https://streamlink.github.io/plugins.html) and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)

### Collaboration

- [x] [I will provide feedback should a pull request be opened with a fix for the plugin](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Streamlink version

streamlink 7.0.0

### Description

streaming links obtained via cookies could not open.
(My cookies are masked in the log)

I'm not sure if this question can be referenced.
[https://github.com/streamlink/streamlink/issues/1438](url)

### Debug log

```text
streamlink https://live.bilibili.com/22718321 best --loglevel=debug
[session][info] Plugin bilibili is being overridden by C:\Users\k3bc999\AppData\Roaming\streamlink\plugins\bilibili.py (sha256:800869a29a3df9cb6f0c296425e1595bd33de91e2ebb7c2aa3b8efe63b41d6f0)
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.11
[cli][debug] OpenSSL:    OpenSSL 1.1.1t  7 Feb 2023
[cli][debug] Streamlink: 7.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  exceptiongroup: 1.2.2
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://live.bilibili.com/22718321
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\MPC-HC\mpc-hc64.exe
[cli][debug]  --http-cookie=[('DedeUserID', '**********'), ('DedeUserID__ckMd5', '***************'), ('SESSDATA', '*************************'), ('bili_jct', '*******************')]
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/22718321
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: C:\Program Files\MPC-HC\mpc-hc64.exe
[stream.hls][debug] Reloading playlist
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][error] Attempted to play a variant playlist, use 'hls://https://d1--cn-gotcha204-2.bilivideo.com/live-bvc/703959/live_371468054_35317034_2500/index.m3u8?expires=1733839134&len=0&oi=1881802099&pt=web&qn=250&trid=10076f84148303dda1033468971fa167583b&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha204&sign=a7def8a56fb6e19143256adfacdfb236&site=ec8f9b1768185164e3e1f93e26a63005&free_type=0&mid=641002&sche=ban&bvchls=1&trace=64&isp=cm&rg=NorthEast&pv=Liaoning&source=puv3_onetier&deploy_env=prod&sl=3&p2p_type=1&flvsk=d223acf28f6e6cb30a29e9b00dcdb4f9&pp=srt&sk=f6e5e48296ead121166ea0f143b25bb8&info_source=cache&hot_cdn=57353&origin_bitrate=621972&suffix=2500&score=1&vd=bc&src=puv3&order=1' instead
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][error] Try 1/1: Could not open stream <HLSStream ['hls', 'https://d1--cn-gotcha204-2.bilivideo.com/live-bvc/703959/live_371468054_35317034_2500/index.m3u8?expires=1733839134&len=0&oi=1881802099&pt=web&qn=250&trid=10076f84148303dda1033468971fa167583b&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha204&sign=a7def8a56fb6e19143256adfacdfb236&site=ec8f9b1768185164e3e1f93e26a63005&free_type=0&mid=641002&sche=ban&bvchls=1&trace=64&isp=cm&rg=NorthEast&pv=Liaoning&source=puv3_onetier&deploy_env=prod&sl=3&p2p_type=1&flvsk=d223acf28f6e6cb30a29e9b00dcdb4f9&pp=srt&sk=f6e5e48296ead121166ea0f143b25bb8&info_source=cache&hot_cdn=57353&origin_bitrate=621972&suffix=2500&score=1&vd=bc&src=puv3&order=1']> (No data returned from stream)
[cli][info] Closing currently open stream...
error: Could not open stream <HLSStream ['hls', 'https://d1--cn-gotcha204-2.bilivideo.com/live-bvc/703959/live_371468054_35317034_2500/index.m3u8?expires=1733839134&len=0&oi=1881802099&pt=web&qn=250&trid=10076f84148303dda1033468971fa167583b&sigparams=cdn,expires,len,oi,pt,qn,trid&cdn=cn-gotcha204&sign=a7def8a56fb6e19143256adfacdfb236&site=ec8f9b1768185164e3e1f93e26a63005&free_type=0&mid=641002&sche=ban&bvchls=1&trace=64&isp=cm&rg=NorthEast&pv=Liaoning&source=puv3_onetier&deploy_env=prod&sl=3&p2p_type=1&flvsk=d223acf28f6e6cb30a29e9b00dcdb4f9&pp=srt&sk=f6e5e48296ead121166ea0f143b25bb8&info_source=cache&hot_cdn=57353&origin_bitrate=621972&suffix=2500&score=1&vd=bc&src=puv3&order=1']>, tried 1 times, exiting
```

**Comment by bastimeyer** [comment]
> [session][info] Plugin bilibili is being overridden by C:\Users\k3bc999\AppData\Roaming\streamlink\plugins\bilibili.py (sha256:800869a29a3df9cb6f0c296425e1595bd33de91e2ebb7c2aa3b8efe63b41d6f0)

**Comment by k3bc999** [comment]
> The stream output is working perfectly fine in the current plugin version, without any required authentication:
> 
> ```
> $ streamlink -l debug https://live.bilibili.com/22718321 best
> [cli][debug] OS:         Linux-6.12.1-1-git-x86_64-with-glibc2.40
> [cli][debug] Python:     3.12.7
> [cli][debug] OpenSSL:    OpenSSL 3.4.0 22 Oct 2024
> [cli][debug] Streamlink: 7.0.0+28.g53ac068d
> [cli][debug] Dependencies:
> [cli][debug]  certifi: 2024.8.30
> [cli][debug]  isodate: 0.7.2
> [cli][debug]  lxml: 5.3.0
> [cli][debug]  pycountry: 24.6.1
> [cli][debug]  pycryptodome: 3.21.0
> [cli][debug]  PySocks: 1.7.1
> [cli][debug]  requests: 2.32.3
> [cli][debug]  trio: 0.22.0
> [cli][debug]  trio-websocket: 0.12.0.dev0
> [cli][debug]  typing-extensions: 4.12.2
> [cli][debug]  urllib3: 2.2.3
> [cli][debug]  websocket-client: 1.8.0
> [cli][debug] Arguments:
> [cli][debug]  url=https://live.bilibili.com/22718321
> [cli][debug]  stream=['best']
> [cli][debug]  --loglevel=debug
> [cli][debug]  --player=/usr/bin/mpv
> [cli][debug]  --webbrowser-headless=True
> [cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/22718321
> [cli][info] Available streams: live_alt, live (worst, best)
> [cli][info] Opening stream: live (hls)
> [cli][info] Starting player: /usr/bin/mpv
> [stream.hls][debug] Reloading playlist
> [cli][debug] Pre-buffering 8192 bytes
> [stream.hls][debug] First Sequence: 92871900; Last Sequence: 92871904
> [stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 92871902; End Sequence: None
> [stream.hls][debug] Adding segment 92871902 to queue
> [stream.hls][debug] Adding segment 92871903 to queue
> [stream.hls][debug] Adding segment 92871904 to queue
> [stream.hls][debug] Writing segment 92871902 to output
> [stream.hls][debug] Segment initialization 92871902 complete
> [cli.output][debug] Opening subprocess: ['/usr/bin/mpv', '--force-media-title=https://live.bilibili.com/22718321', '-']
> [stream.hls][debug] Writing segment 92871902 to output
> [stream.hls][debug] Segment 92871902 complete
> [stream.hls][debug] Writing segment 92871903 to output
> [stream.hls][debug] Segment 92871903 complete
> [stream.hls][debug] Writing segment 92871904 to output
> [stream.hls][debug] Segment 92871904 complete
> [stream.hls][debug] Reloading playlist
> [cli][debug] Writing stream to output
> [stream.hls][debug] Reloading playlist
> [stream.hls][debug] Adding segment 92871905 to queue
> [stream.hls][debug] Adding segment 92871906 to queue
> [stream.hls][debug] Adding segment 92871907 to queue
> [stream.hls][debug] Writing segment 92871905 to output
> [stream.hls][debug] Segment 92871905 complete
> [stream.hls][debug] Writing segment 92871906 to output
> [stream.hls][debug] Segment 92871906 complete
> [stream.hls][debug] Writing segment 92871907 to output
> [stream.hls][debug] Segment 92871907 complete
> [stream.hls][debug] Reloading playlist
> [cli][info] Player closed
> [stream.segmented][debug] Closing worker thread
> [stream.segmented][debug] Closing writer thread
> [cli][info] Stream ended
> [cli][info] Closing currently open stream...
> ```

We can only get 480p without cookies in bilibil, so I set --http-cookie in configuration.
I referenced this issue [(https://github.com/streamlink/streamlink/issues/5700#issuecomment-1896263241)](url)

**Comment by bastimeyer** [comment]
There has been no feedback in #5782 for almost a year now. That PR attempts to return progressive HTTP streams with FLV containers, rather than HLS streams, but as I mentioned there, since I am unfamiliar with this website, I'm not going to merge that PR without feedback from users.

**Comment by k3bc999** [comment]
> There has been no feedback in [#5782](https://github.com/streamlink/streamlink/pull/5782) for almost a year now. That PR attempts to return progressive HTTP streams with FLV containers, rather than HLS streams, but as I mentioned there, since I am unfamiliar with this website, I'm not going to merge that PR without feedback from users.

OK, I understand, thank you for your help.

I hope that subsequent people who also encounter this problem will be able to find a more appropriate solution.

**Comment by bastimeyer** [comment]
I've rebased #5782 to master now with some few additional modifiations.

Instead of waiting for others, how about testing the updated plugin yourself and providing feedback? It's not that difficult...
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

**Comment by k3bc999** [comment]
> I've rebased [#5782](https://github.com/streamlink/streamlink/pull/5782) to master now with some few additional modifiations.
> 
> Instead of waiting for others, how about testing the updated plugin yourself and providing feedback? It's not that difficult... https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

What I should be doing is using bastimeyer:plugins/bilibili/v1-api-httpstream for bilibili.py?
If so, I've done the download and deleted the content in the about cookie and the new log looks like this

C:\Users\k3bc999\Works\datebase_test>streamlink https://live.bilibili.com/22718321 best --loglevel=debug
[session][info] Plugin bilibili is being overridden by C:\Users\k3bc999\AppData\Roaming\streamlink\plugins\bilibili.py (sha256:c5a4377b98e5f926d8965c4e678d3c7009ff1991302cafa1df17536a268d8a3b)
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.11
[cli][debug] OpenSSL:    OpenSSL 1.1.1t  7 Feb 2023
[cli][debug] Streamlink: 7.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  exceptiongroup: 1.2.2
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://live.bilibili.com/22718321
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Program Files\MPC-HC\mpc-hc64.exe
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/22718321
[cli][info] Available streams: hls_alt (worst), hls, httpstream_alt, httpstream (best)
[cli][info] Opening stream: httpstream (http)
[cli][info] Starting player: C:\Program Files\MPC-HC\mpc-hc64.exe
[cli][debug] Pre-buffering 8192 bytes
[cli.output][debug] Opening subprocess: ['C:\\Program Files\\MPC-HC\\mpc-hc64.exe', '-']
[cli][info] Closing currently open stream...
error: Failed to start player: C:\Program Files\MPC-HC\mpc-hc64.exe (Process exited prematurely)

I'm going to switch to VLC for testing.

**Comment by k3bc999** [comment]
Amazing, it really doesn't need cookie info to play in 1080P
Here's the new log (the previous room is offline)
streamlink https://live.bilibili.com/24158116 best --loglevel=debug
[session][info] Plugin bilibili is being overridden by C:\Users\k3bc999\AppData\Roaming\streamlink\plugins\bilibili.py (sha256:c5a4377b98e5f926d8965c4e678d3c7009ff1991302cafa1df17536a268d8a3b)
[cli][debug] OS:         Windows 10
[cli][debug] Python:     3.10.11
[cli][debug] OpenSSL:    OpenSSL 1.1.1t  7 Feb 2023
[cli][debug] Streamlink: 7.0.0
[cli][debug] Dependencies:
[cli][debug]  certifi: 2024.8.30
[cli][debug]  exceptiongroup: 1.2.2
[cli][debug]  isodate: 0.7.2
[cli][debug]  lxml: 5.3.0
[cli][debug]  pycountry: 24.6.1
[cli][debug]  pycryptodome: 3.21.0
[cli][debug]  PySocks: 1.7.1
[cli][debug]  requests: 2.32.3
[cli][debug]  trio: 0.27.0
[cli][debug]  trio-websocket: 0.11.1
[cli][debug]  typing-extensions: 4.12.2
[cli][debug]  urllib3: 2.2.3
[cli][debug]  websocket-client: 1.8.0
[cli][debug] Arguments:
[cli][debug]  url=https://live.bilibili.com/24158116
[cli][debug]  stream=['best']
[cli][debug]  --loglevel=debug
[cli][debug]  --player=C:\Users\k3bc999\Software\VideoLAN\VLC\vlc.exe
[cli][info] Found matching plugin bilibili for URL https://live.bilibili.com/24158116
[cli][info] Available streams: hls_alt (worst), hls_alt2, hls, httpstream_alt, httpstream (best)
[cli][info] Opening stream: httpstream (http)
[cli][info] Starting player: C:\Users\k3bc999\Software\VideoLAN\VLC\vlc.exe
[cli][debug] Pre-buffering 8192 bytes
[cli.output][debug] Opening subprocess: ['C:\\Users\\k3bc999\\Software\\VideoLAN\\VLC\\vlc.exe', '--input-title-format', 'https://live.bilibili.com/24158116', '-']
[cli][debug] Writing stream to output

Here's the info from the vlc
![Image](https://github.com/user-attachments/assets/eac2ce1d-d6c0-403d-a7f1-3241d09a4394)

**Comment by k3bc999** [comment]
> I've rebased [#5782](https://github.com/streamlink/streamlink/pull/5782) to master now with some few additional modifiations.
> 
> Instead of waiting for others, how about testing the updated plugin yourself and providing feedback? It's not that difficult... https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback

Is there anything else I need to do?

**Comment by bastimeyer** [comment]
When asking for feedback, I'm mainly looking for streams which might fail being resolved by the new plugin implementation. I've already observed one channel which didn't support the progressive httpstream. This was broken in the previous PR revision, but I've fixed it with the rebase. I think it's good now though. Going to merge that one. You can keep sideloading the plugin until the next Streamlink release (or nightly build).

**Comment by k3bc999** [comment]
> When asking for feedback, I'm mainly looking for streams which might fail being resolved by the new plugin implementation. I've already observed one channel which didn't support the progressive httpstream. This was broken in the previous PR revision, but I've fixed it with the rebase. I think it's good now though. Going to merge that one. You can keep sideloading the plugin until the next Streamlink release (or nightly build).

Ok, thank you so much for your work, it really helps me a lot!
