### ISSUE TITLE
chaturbate broadcaster is using OBS

### ISSUE THREAD

**Issue by polymath614** [streamlink/streamlink#634]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
so Chaturbate has started a beta with OBS apparently when they started doing this it as stopped streamlink from working. i am looking to see what has changed but have not seen anything yet.
...

### Expected / Actual behavior
so it should open VLC with the stream going but all you get is black like when there is a ticket show.
...

### Reproduction steps / Stream URLs to test

1. ...this was today on https://chaturbate.com/blazefyre/ but will have to ask if the broadcaster is using OBS and they may not know what you are talking about.
2. ...
3. ...

### Environment details (operating system, python version, etc.)

...

### Comments, logs, screenshots, etc.
will try and update with what i find
...

**Comment by gravyboat** [comment]
I'm not very familiar with how chaturbate works, what makes a 'ticket show' different than a normal live stream? Does this work for streams that are not a 'ticket show' but the broadcaster is using OBS?

**Comment by polymath614** [comment]
i think ticket shows and privates require account verification i have not looked to see what is different with the stream or site. compared 2 cams one worked other did not could not find what was different between them.
