### ISSUE TITLE
Widevine Alpha Support

### ISSUE THREAD

**Issue by lutfijw** [streamlink/streamlink#6355]
### Checklist

- [x] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Collaboration

- [x] My request is genuine and in the best interest of the project
- [x] [I will provide feedback should a pull request be opened with a new feature implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Description

Streamlink is great to play DRM protected content with clearkey, however it has no support to play widevine DRM protected content.
More providers are now moving to widevine DRM, it will be great if streamlink can support this.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/7.0.0/CONTRIBUTING.md#plugin-rules
