### ISSUE TITLE
WWEN plugin?

### ISSUE THREAD

**Issue by whitetop** [streamlink/streamlink#636]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
WWEN works on kodi but i'm asking can we get this on streamlink as a fully active py? i tried using it on livestreamer but it has a few py files one for setting and others for logins since its for kodi. streamlink has a bug so i can't get it to start up but read its a problem a dev was going to fix.

Edited: (missing info) this plugin is a WWE Network plugin for kodi url is ( http://network.wwe.com ) Plugin url ( http://forum.kodi.tv/showthread.php?tid=233467 ), some info can be found on that site with the download links for the plugin.

When using on kodi if temp bans your account after 15min so be careful, atres is used for the lower resolutions but it is hidden for some 4500K files like live PPV you have to wait a week for it to show up.

WWE uses the master m3u8 file with the 500k to 4500k m3u8 links.
### Expected / Actual behavior
AIO py to catch 1280x720p files on wwe and not the 3000k 720p, after 4500k ones (they are there but just hidden for a week)

### Reproduction steps / Stream URLs to test

1. Above

### Environment details (operating system, python version, etc.)

win 7 and server 03, all updated.

### Comments, logs, screenshots, etc.

Any more info say it simple of what you need, not cutting corners and thinking i'm a mind reader like below. (not rude but even a child can see what i'm on about below)

**Comment by beardypig** [comment]
@whitetop github seems to be flagging a lot of users lately, particularly people that create accounts and create and issue right away - seems they have an over zealous spam detection system, I doubt anyone reported for you creating this issue :) 

I'm not familiar with WWEN could you provide some URLs that you would like to see supported.

**Comment by whitetop** [comment]
@beardypig I run a site with others and our spam detectors don't do this but i did email them and they sorted the problem out.

The WWEN is here, it works good on kodi but gets flagged after 15 min and keeps breaking on the live stream. http://forum.kodi.tv/showthread.php?tid=233467

**Comment by beardypig** [comment]
It would be more useful for you to provide us with some link that you expect to work, the more information you give the more likely someone will write a plugin.

**Comment by whitetop** [comment]
@beardypig Like what link? asking for a link but not saying what for does not help.

The link in the above post is to the kodi plugin, anyone with a WWE network account can get the m3u8 file with inspect page (console).

**Comment by beardypig** [comment]
`streamlink` requires an URL argument, I am asking which URLs you expect to be supported.

**Comment by whitetop** [comment]
Sorry but if you looked at the plugin script it tells you there, the plugin files are there, we just need it in one py for steamlink so it can be used for live stream recording or getting the real 720p (4500k) files,

as stated if one looks after clicking the kodi link your have all your info.

**Comment by beardypig** [comment]
The more information you include the more likely someone will give up _their_ spare to make a plugin for _you_. Posting a link to a KODI plugin is not the most direct way to give that information and it's not always that useful as KODI is quite different from Streamlink.

**Comment by whitetop** [comment]
@beardypig Sorry but are you a bot? everything is within that links, the files and the coding of others that helped fix a few problems, if you looked within that link it will open a web page with ALL INFO.

I'm not rude or anything but my replies to you are making it look like it and could be the reason of no real help from coders.

**Comment by gravyboat** [comment]
@whitetop No he isn't. It is up to the person reporting the issue to provide us with as many details as possible to make implementation as simple as possible. We are not going to review and research how a KODI plugin works then determine how that can be implemented inside of Streamlink. It is up to you to provide us with URLs and other data that allow us to review how something could be implemented inside of Streamlink, not inside of KODI.

**Comment by beardypig** [comment]
All I wanted was a link to the actual website. Googling for wwen doesn't actually find it. What would have been useful would have been for you to say, here's the website  http://network.wwe.com. Instead to find out what you were asking for I had to look at a kodi forum post. The forum thread doesn't actually have all the info, it's in the source code which requires some investigation. All I wanted was http://network.wwe.com...

**Comment by whitetop** [comment]
@gravyboat Not sure of all that what you posted is really anything to do with what i was saying. if @beardypig said what he really wanted and not the "so many posts of post link, post link" then i would have known i forgot to add what the plugin is for but no he/she did not ask for this, they only asked for a link and a urls? how can anyone know what he/she was on about!!!!

@beardypig If you did state this and not what i just said to @gravyboat then i would have fixed the problem and gave links and fixed my main post, but not once did you ask for what the plugin is for or of why the main post does not state the url of the site or what the plugin was for.

as said above i am not rude or one of them guy's requesting and demanding anything but your posts are not very understanding to of what you really wanted.

**Comment by beardypig** [comment]
I'm not familiar with WWEN could you provide some URLs that you would like to see supported.

**Comment by whitetop** [comment]
So now with out the trolling,

In what kind of url do you need if you two are even remotely going to help? links to the master m3u8 files or 4500k m3u8?

link to atres or even a pirated site showing how to get the links to the urls, WWEN page link was posted that has links to the files needed, if you can't bother going there to get the files then i don't even think you bothered to look on what that page had or even the 11 pages and a working pack one did.

**Comment by gravyboat** [comment]
We're asking for publicly available stream URLs. If I wanted to stream this (legally) for a free or openly available event they were streaming on the site, what would the url look like for such an event?

**Comment by whitetop** [comment]
That is one i can't help with as i have never since the network start have seen, the only free thing i have seen if the free first month.

I got this off atres http://hlsvod-akc.media.net.wwe.com/wwe/2016/07/20/948585283_m3u8/4500/wwe_948585283_4500k.m3u8

**Comment by gravyboat** [comment]
Is it possible to pass login credentials to view a stream? What does that kind of URL request look like?

**Comment by beardypig** [comment]
This would have been a suitable list of URLs 

- http://network.wwe.com/ (live) 
 - http://network.wwe.com/video/v1223512583?contextType=wwe-show&contextId=elimination_chamber&contentId=215822516&watchlistAltButtonContext=series (ppv) 
 - http://network.wwe.com/video/v1223844083?contextType=wwe-show&contextId=wwe_nxt&contentId=216089474&watchlistAltButtonContext=series (show) 
 
Those are the sort of URLs you will have to give to streamlink for it to find the streams for the event you wanna watch.

**Comment by whitetop** [comment]
@gravyboat No sorry as the login is a friend of mine, i use it now and then.

The file requests the 4500K version of the show. the files all come in .ts files but it asks for a encryption key to decrypt, but some how if one uses LetMeAtIt it is meant to take the files directly from the server.

show link
http://network.wwe.com/video/v1210420383

master m3u8
http://hlsvod-akc.media.net.wwe.com/wwe/2016/10/31/1210420383_m3u8/master_wired.m3u8

it shows this in it 
#EXTM3U
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="captions",LANGUAGE="en",INSTREAM-ID="CC1",NAME="CC1"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=895400,CODECS="avc1.42001e,mp4a.40.2",RESOLUTION=512x288,CLOSED-CAPTIONS="captions"
800/wwe_1210420383_800k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1315600,CODECS="avc1.42001e,mp4a.40.2",RESOLUTION=640x360,CLOSED-CAPTIONS="captions"
1200/wwe_1210420383_1200k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1975600,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=960x540,CLOSED-CAPTIONS="captions"
1800/wwe_1210420383_1800k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2635600,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=960x540,CLOSED-CAPTIONS="captions"
2400/wwe_1210420383_2400k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3295600,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=960x720,CLOSED-CAPTIONS="captions"
3000/wwe_1210420383_3000k.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=4945600,CODECS="avc1.640028,mp4a.40.2",RESOLUTION=1280x720,CLOSED-CAPTIONS="captions"
4500/wwe_1210420383_4500k.m3u8


Just before the .ts files how on inspect this link shows
https://ws.media.net.wwe.com/ws/media/mf/op-generateKey/v-2.3?kid=5c8a19f6-8d40-4a84-85b7-2b5ecda2c119&contentId=1210420383

**Comment by beardypig** [comment]
Closing this as #651 was merged, @whitetop have you tried it out?

**Comment by whitetop** [comment]
Tried what out

**Comment by beardypig** [comment]
The support for WWE Network that you requested, it has been added to `streamlink`. You can download the [latest installer](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe).

**Comment by beardypig** [comment]
You need to supply your `email` and `password` for `streamlink` to login to WWE Network for you: eg.

```shell
streamlink --wwenetwork-email your@email.com --wwenetwork-password youpassword http://network.wwe.com/video/v1210420383 best 
```

**Comment by whitetop** [comment]
it fails, plus when i got to select all to copy the log to here it auto closes, even with timeout 600 to pause the cmd.

**Comment by beardypig** [comment]
How did you install the `wwenetwork.py` file? Looks like an html file, did you do it manually?

**Comment by whitetop** [comment]
I got a copy from [url=https://codecov.io/gh/streamlink/streamlink/commit/563a5cb3c3548111880a8a6886c5b7f494cd901c?src=pr&el=desc]here[/url]

its the portable version i used.

**Comment by beardypig** [comment]
If you used the portable version you can just update as the plugin is merged in to the master branch.

**Comment by whitetop** [comment]
ok got it to work but get this but i have vlc as its my main player?

C:\Users\john\Desktop\streamlink-portable-master\Streamlink for Windows (Compile
d)\Releases>streamlink --wwenetwork-email ******* --wwenetwork-passwor
d ******** http://network.wwe.com/video/v1228654883 best
[Streamlink for Windows v0.3.2 - Git 468e9ca]
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/vide
o/v1228654883
[cli][info] Available streams: 720p_alt, 540p_alt, 288p (worst), 360p, 540p, 720
p (best)
[cli][info] Opening stream: 720p (hls)
error: The default player (VLC) does not seem to be installed. You must specify
the path to a player executable with --player.
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]

C:\Users\john\Desktop\streamlink-portable-master\Streamlink for Windows (Compile
d)\Releases>timeout 600

Waiting for 598 seconds, press a key to continue ...

**Comment by beardypig** [comment]
There are two 720p versions returned, the 3000k one and the 4500k one. It's a limitation of streamlink that these are not sorted in the correct order. I could update the plugin so that the list of available streams are given by bitrate instead of resolution.

**Comment by whitetop** [comment]
well i tried 720p_alt and 720p and best all took the 3000k one.

**Comment by beardypig** [comment]
What method did you use to determine that they were 3000k and not 4500k?

**Comment by whitetop** [comment]
Mediainfo, checked the bitrate and its was 3000k no where near the 4500k bitrate

**Comment by beardypig** [comment]
Mediainfo in VLC? The bit rates as reported in the HLS playlists are not the actual bit rates, they are the average bit rate targets. While the target average bit rate may be 4500k or 3000k, they are variable and may not be reached.

You can look at the stream URLs (using `--stream-url`) to see which version is which, eg.
```shell
$ streamlink --stream-url "http://network.wwe.com/video/v1228654883" 720p_alt
http://hlsvod-akc.media.net.wwe.com/wwe/2017/03/02/1228654883_m3u8/4500/wwe_1228654883_4500k.m3u8

$ streamlink --stream-url "http://network.wwe.com/video/v1228654883" 720p
http://hlsvod-akc.media.net.wwe.com/wwe/2017/03/02/1228654883_m3u8/3000/wwe_1228654883_3000k.m3u8
```

In this case `720p_alt` is `4500k` and `720p` is `3000k`. 

In the master playlist for this video (http://hlsvod-akc.media.net.wwe.com/wwe/2017/03/02/1228654883_m3u8/master_wired.m3u8) you can see that the bit rates are reported as `3295600` (`3295k`) and `4945600` (`4945k`), which also differ from `3000k` and `4500k. You may also notice that the resolution is different, but in reality both stream have the same 1280x720 resolution.

**Comment by whitetop** [comment]
Sorry the 4500k is 1280 - 3000k is 960, its the 960 that is downloaded or streamed, i tried the 720p_alt stuff and it did not change

**Comment by beardypig** [comment]
Downloaded or streamed will make no difference. The reported resolution is 1280x720 for 4500k and 960x720 for 3000k, they are both actually 1280x720 - the information is not 100% accurate. `720p_alt` and `720p` have different target bit rates but the same resolution, `720p_alt` (in this case) has a higher target bit rate. 

I will rename the streams to include their bit rates so they can be more easily distinguished.

**Comment by whitetop** [comment]
Oh ok i get you now, is there anyway to force 4500k? just asking now i know all is above but what if its hidden like the PPV's where its there but not in the options.

**Comment by beardypig** [comment]
In this case `720p_alt` is `4500k`. There don't appear to be any other streams.
I'm not familiar with the other programmes you have used before and if they hide streams or not, maybe to get you to pay for a "pro" version? As best I can tell streamlink will give you access to the same streams as you'd get on the website, and it won't hide any if it can find them

**Comment by whitetop** [comment]
So alt means the next one up but 720p just means the lowest of then 720p.

**Comment by whitetop** [comment]
Ok just tested any to get the 4500k one its a 50/50 chance that it will detect it, out of 5 tries it used the 4500k one 3 times but 3000k 2 times.

**Comment by beardypig** [comment]
I have created a patch that will show both resolution and bit rate, you'll probably have to wait a  it got it to be available though.

**Comment by beardypig** [comment]
Has been merged now (thanks to @gravyboat). You can download the latest version and it will list the resolution with bitrate.

**Comment by whitetop** [comment]
C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Co
mpiled)\Releases>streamlink --wwenetwork-email Oliversb89@me.com --wwenetwork-pa
ssword Music@89 http://network.wwe.com/video/v1229274583 best -o best.ts
[Streamlink for Windows v0.3.2 - Git 468e9ca]
Failed to load plugin wwenetwork:
  File "imp.py", line 234, in load_module
  File "imp.py", line 172, in load_source
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Win
dows (Compiled)\Releases\Streamlink\streamlink\plugins\wwenetwork.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

error: No plugin can handle URL: http://network.wwe.com/video/v1229274583
[End of Streamlink for Windows]

C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Co
mpiled)\Releases>timeout 30

Waiting for 29 seconds, press a key to continue ...

**Comment by beardypig** [comment]
Exactly the same error as before, how did you fix it last time?

**Comment by whitetop** [comment]
Re-downloaded the installer and made a new portable exe but i have tried it and got the same error?

**Comment by beardypig** [comment]
Wierd ... OK.

Download this file: https://raw.githubusercontent.com/streamlink/streamlink/master/src/streamlink/plugins/wwenetwork.py and replace the existing here "C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Compiled)\Releases\Streamlink\streamlink\plugins\wwenetwork.py".

Then download this file: https://raw.githubusercontent.com/streamlink/streamlink/master/src/streamlink/stream/hls.py and replace the existing on here "C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Compiled)\Releases\Streamlink\streamlink\stream\hls.py".

That should fix it...

**Comment by bastimeyer** [comment]
> Streamlink for Windows v0.3.2 - Git 468e9ca

You are using an older build from two days ago. You need to run Streamlink built from at least 3059cd1 (which is currently the head of the master branch)

**Comment by whitetop** [comment]
C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Co
mpiled)\Releases>streamlink --wwenetwork-email ******** --wwenetwork-pa
ssword ******** http://network.wwe.com/video/v1229635883 720p_4945 -o best.ts
[Streamlink for Windows v0.3.2 - Git 468e9ca]
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/vide
o/v1229635883
error: The specified stream(s) '720p_4945' could not be found.
       Available streams: 720p_4945k, 288p_895k, 540p_2635k, 540p_1975k, 360p_13
15k, 720p_3295k
[End of Streamlink for Windows]

C:\Users\nexttimer\Desktop\streamlink-portable-master\Streamlink for Windows (Co
mpiled)\Releases>timeout 30

Waiting for 29 seconds, press a key to continue ...

@bastimeyer I know, i'm using the portable version, i have already re-downloaded the files from the setup twice now.

**Comment by beardypig** [comment]
I get different results
```shell
streamlink "http://network.wwe.com/video/v1229274583"
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/video/v1229274583
Available streams: 224p_650k (worst), 288p_990k, 360p_1450k, 504p_2100k, 540p_2700k, 720p_3500k (best)
```
There is no `4500k` stream available for this video. 

If you always want the best quality available then you can use the quality name `best`, rather than manually picking the best. 
```
streamlink "http://network.wwe.com/video/v1229274583" best
```

**Comment by whitetop** [comment]
The thing is the 4500k.m3u8 is there but never shows on the master, as i said above its hidden on PPV's till the next sunday and it shows in the master.

Is there no way to find this hidden part?

Thanks for the help so far, its really helping.

**Comment by beardypig** [comment]
I don't think it's hidden, I think it just doesn't exist. 
The pattern for the files is quite simple, 
```
http://hlslive-akc.med1.net.wwe.com/ls01/wwe/2017/03/06/WWE_GHOST_VIDEO_WWE_PayPerViews_20170306_1488566112070/2400K/2400_complete-trimmed.m3u8
http://hlslive-akc.med1.net.wwe.com/ls01/wwe/2017/03/06/WWE_GHOST_VIDEO_WWE_PayPerViews_20170306_1488566112070/3000K/3000_complete-trimmed.m3u8
```

Only the bitrate part changes, so I expect the 4500k URL to be http://hlslive-akc.med1.net.wwe.com/ls01/wwe/2017/03/06/WWE_GHOST_VIDEO_WWE_PayPerViews_20170306_1488566112070/4500K/4500_complete-trimmed.m3u8, but that doesn't exist. Older videos follow that same pattern. It looks like it's not possible to get it without waiting...

**Comment by whitetop** [comment]
Dam so the early 4500k are fakes then,

Its a pity but all is working now and is better than atres thanks to you.

**Comment by beardypig** [comment]
Where did you see the early 4500k streams?

**Comment by whitetop** [comment]
xwt, i go there for audio podcasts of wrestling but notice a uploader called heel puts up 4500k rips after the PPV has stopped (live feed).

**Comment by beardypig** [comment]
Perhaps the live feed broadcasts in 4500k, but the VOD is not available in 4500k until later?

**Comment by whitetop** [comment]
No if i'm right the live feed's are 3000k and below,

**Comment by tanyaharber0321** [comment]
Wooow! This could be one of the most useful blogs We have ever come across on the subject. Actually excellent info! https://wrestlingonlinematches.com
