### ISSUE TITLE
DOUYU

### ISSUE THREAD

**Issue by loboque** [streamlink/streamlink#637]
hi dont work douyu.com ,

C:\Windows\System32>streamlink.exe douyu.com/th000
[cli][info] Found matching plugin douyutv for URL douyu.com/th000
error: Unable to open URL: https://www.douyu.com/lapi/live/getPlay/11017 (403 Cl
ient Error: Forbidden for url: https://www.douyu.com/lapi/live/getPlay/11017)

but morning work((

**Comment by fozzysec** [comment]
Douyu have changed their API, currently I haven't found the new LAPI and authkey, you can use MAPI url to get hls stream but the quality is very low. Unfortunately the swf file is encrypted and it is not easy to decrypt and find the API and key.
Wait if someone else can find the new LAPI address and key, maybe @steven7851 can help.

**Comment by steven7851** [comment]
API is no change, I think the key has been blocked.
Need someone provides a new one.

**Comment by yan12125** [comment]
I have a partial fix at https://github.com/yan12125/streamlink/commit/0c822ee4edda54b70df7898ee6086e9079907a91

Issues:

* Playing via --player=mpv is quite laggy
* As reported in https://github.com/rg3/youtube-dl/issues/12316, the HLS link gets expired every 5 minutes. I guess it can be resolved by requesting a new HLS url every 5 minutes. But I don't know how to do that

**Comment by fozzysec** [comment]
@brlala I skimmed the code, the biggest broblem is the modified MD5 algorithm which is copied directly from swf file, it is hard to implement it in Python easily. I tried some converting tools to generate Python code but none works. I will try to rewrite the algorithm in Python.

**Comment by brlala** [comment]
This may work https://gist.github.com/debugzxcv/85bb2750d8a5e29803f2686c47dc236b
@debugzxcv

**Comment by fozzysec** [comment]
@brlala got it fixed and i will open a PR later.

**Comment by loboque** [comment]
how to run it ??? im newbie can you send me worked plugins ??

**Comment by fozzysec** [comment]
@loboque First find your corresponding python site-packages location(in windows usually Users/username/AppData/Roaming/Python/PythonXX/site-packages or \AppData\Local\Programs\Python\Python36\Lib\site-packages, in linux usually /usr/lib/pythonXX/site-packages/). then find the streamlink folder, download the following files into streamlink/plugins/ to replace the origin one. then it will work.
https://raw.githubusercontent.com/fozzysec/streamlink/cc06ca9f4deb13a1bc8b21a13b46986d92c8ad9f/src/streamlink/plugins/douyutv_blackbox.py
https://raw.githubusercontent.com/fozzysec/streamlink/ce234fc0ce9f74a3dab997db94f62dec85c1bbec/src/streamlink/plugins/douyutv.py

You can also download the project source code, place the files under src/streamlink/plugins/, then run `pythonXX setup.py install ` to install it.

**Comment by loboque** [comment]
omg man site-packages folder i find. now where to shove it ??

**Comment by fozzysec** [comment]
@loboque you should be able to find folder named something like `streamlink-0.3.1-py3.6.egg`, enter `streamlink-0.3.1-py3.6.egg/streamlink/plugins/` then copy you downloaded file into the `plugins` folder to replace existing file. then it works.

**Comment by loboque** [comment]
i don't have this file .egg . i have 0.3.2 version and i have no streams found on url

**Comment by loboque** [comment]
you can download a working version ???  I will always help you boy!!

**Comment by fozzysec** [comment]
@loboque alternatively you can download this [file](https://github.com/fozzysec/streamlink/archive/douyutv_637.zip), unzip it and run `python setup.py install `

**Comment by fozzysec** [comment]
Also with the PR merged into the master branch, you can also re-install the new streamlink to get douyu plugin to work.

**Comment by beardypig** [comment]
Just merged #666 so you can now download the [latest version](https://streamlink-builds.s3.amazonaws.com/nightly/windows/streamlink-latest.exe) and it will have this fix :)

**Comment by beardypig** [comment]
Closing at #666 has been merged.

**Comment by loboque** [comment]
ok im install last version, but

C:\Users\loboque>streamlink.exe douyu.com/douyunai/
[cli][info] Found matching plugin douyutv for URL douyu.com/douyunai/
error: No playable streams found on this URL: douyu.com/douyunai/

**Comment by fozzysec** [comment]
@loboque It is a bit strange, it works when I try it.
```
streamlink http://douyu.com/douyunai/
[cli][info] Found matching plugin douyutv for URL http://douyu.com/douyunai/
[cli][info] Available streams: low (worst), middle, source (best)
[cli][info] Opening stream: source (http)
[cli][info] Starting player: mpv --cache 2048
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

I also tried the streamlink on a VPS that located on Tokyo, it also works, so I think it is not a geo-strict problem, it seems that your network has some problem or you didn't have the latest version installed.

**Comment by beardypig** [comment]
@loboque how did you originally install `streamlink`? With the installer or with `pip`?

Perhaps you have multiple versions installed and you need to uninstall all of them and re-install the latest one.

**Comment by fozzysec** [comment]
@steven7851 @yan12125 @brlala 
I found a new API from [youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/douyutv.py), just post the url here for later use, and should we change to that API now or keep the current one that with the magic blackboxed md5 algorithm?

**Comment by beardypig** [comment]
@fozzysec that looks much simpler, the simpler the better in my opinion :)

**Comment by fozzysec** [comment]
@beardypig I will work on it to use the new api, notifying @debugzxcv @spacemeowx2 here for the new douyu api from [youtube-dl](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/douyutv.py) may be helpful to you.

**Comment by yan12125** [comment]
I'd like to clarify it: the API I use is done by @spacemeowx2 https://gist.github.com/spacemeowx2/629b1d131bd7e240a7d28742048e80fc

**Comment by fozzysec** [comment]
@yan12125 @spacemeowx2 thanks for the new API, I will work on streamlink to use the new API

**Comment by loboque** [comment]
thx boys understood, the problem was that configuration file streamlinkrc had at the end
stream-types=hls
hls-segment-threads=4
default-stream=best
sorry my shortcoming im add his for livestreamer long, 
I want to say goodgame.py Plugin not work for me , 
C: \ Users \ loboque> streamlink.exe goodgame.ru/channel/happy/
error: No plugin can handle URL: goodgame.ru/channel/happy/
but i download his from this and he work fine! 
https://github.com/chrippa/livestreamer/issues/1518#issuecomment-257083200
