### ISSUE TITLE
Zee5.com plugin

### ISSUE THREAD

**Issue by jackchoui** [streamlink/streamlink#6371]
### Checklist

- [x] This is a plugin request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)

### Collaboration

- [x] My request is genuine, in the best interest of the project, and I have access to the stream(s) in my web browser
- [x] [I will provide feedback should a pull request be opened with a new plugin implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)
- [x] I will help with reporting future plugin issues should the new plugin be merged and then stop working

### Description

**What is the site about?**
Asian channels

**Who is it owned and run by?**
don't know

**What kind of content does it provide?**
news and entertainment channels

**Are there any access restrictions, like logins or region checks?**
yes, there is login needed, some channles are region bounded

**Further relevant information**
The streaming implementation of this zee5 lokks like Yupptv. For Yupptv there is already a streamlink plugin. 

### Input URLs

1. https://z5ak-cmaflive.zee5.com/cmaf/live/2105550/ZeeCinemaUKELE/master.m3u8?hdnts=st=1735559729~exp=1735562729~acl=/cmaf/live/2105550/ZeeCinemaUKELE/master.m3u8*~hmac=9b0b9da8ba274cca9edd6804dfe47412256c07a2c5e4395ca069bc0aa8008f90&req_id=f9213e32-4cef-4ssb-a8d2-50fdd79ddfab
2. ...
3. ...

**Comment by jackchoui** [comment]
There is no drm voor the live channels. Please check again.

**Comment by bastimeyer** [comment]
All live channels required paid access. The videos I could access require DRM.

**Comment by jackchoui** [comment]
Yes live channels need paid acces but are non drm. Like yupptv also need paid access. 
So the feature request is for the live channels. 

Movies are drm protected. Not needed.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink/blob/7.1.1/CONTRIBUTING.md#plugin-requests

> **Plugins which fall under the following categories will not be implemented and any requests will be rejected.** Depending on the case, already existing plugins which don't meet these plugin criteria, may be kept.

> **4\. Sites which require paid logins or subscriptions**
> Plugin implementations and maintenance must be possible by everyone. Paid access prevents this.

**Comment by jackchoui** [comment]
Thats clear, thanks. Sorry
