### ISSUE TITLE
Streamlink Installation Package for Synology DSM 7.2

### ISSUE THREAD

**Issue by srinath1965** [streamlink/streamlink#6374]
### Checklist

- [x] This is a feature request and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)
- [x] [I have checked the list of open and recently closed feature requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22feature+request%22)

### Collaboration

- [x] My request is genuine and in the best interest of the project
- [x] [I will provide feedback should a pull request be opened with a new feature implementation](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)

### Description

Can you provide a Streamlink Installation Package for Synology DSM 7.2?

**Comment by bastimeyer** [comment]
This is not how this works. Streamlink is a Python-based project that's licensed under the BSD-2-clause license. Anybody can package it as long as the license and the licenses of its dependencies are respected.

You'll have to ask the people who maintain packages for this NAS (?) system. This is not in our hands.

Apart from that, you can always install Streamlink in any supported Python environment using the PyPI package or this git repository.
https://streamlink.github.io/install.html#pypi-package-and-source-code

According to their website, they have a Python 3.9 package available (which is the only one that would support Streamlink >= 7.0.0):
https://www.synology.com/en-us/dsm/packages?search=python
