### ISSUE TITLE
plugin for npo.nl stoppped working.

### ISSUE THREAD

**Issue by sophof** [streamlink/streamlink#638]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Trying to play any url at npo.nl/live results in an error.

### Expected / Actual behavior

expecting a stream, error is: 
```
[cli][info] Found matching plugin npo for URL npo.nl/live/npo-1
error: Unable to open URL: http://ida.omroep.nl/npoplayer/i.js?s=http%3A//npo.nl/live/npo-1 (410 Client Error: Gone for url: http://ida.omroep.nl/npoplayer/i.js?s=http%3A//npo.nl/live/npo-1)
```
### Reproduction steps / Stream URLs to test
```
streamlink -l debug npo.nl/live/npo-1
```
### Environment details (operating system, python version, etc.)

Multiple systems, all using streamlink 0.3.2, Python 2.7.12

**Comment by karlo2105** [comment]
I confirm.
I guess this is new api address : 

`http://ida.omroep.nl/app.php/LI_NEDERLAND1_221673?adaptive=no&token=9crle63s98c55jdn3nt1vuuqs6`

or this

`http://e.omroep.nl/metadata/LI_NEDERLAND1_221673?callback=jsonpCallback1488358731362547`

**Comment by sophof** [comment]
There's a fix for youtube-dl at https://github.com/rg3/youtube-dl/issues/12311
Sadly I don't understand the streamlink code enough to fix this myself.

**Comment by beardypig** [comment]
I have created a PR with an updated version of the plugin, would be good if you could test it out @sophof :)

**Comment by sophof** [comment]
Thanks, tested and confirmed to work :)

**Comment by sophof** [comment]
Btw, do you have a link to a good howto or something how to do this myself? I'd love to add horizon go support (dunno if that's even possible since it uses silverlight), but I have no clue where to start. I've been playing around with wireshark and can see the links to m3u8 files and ts files (for npo.nl), but had no clue how to tie this together. Googling doesn't really give me anything useful.

**Comment by beardypig** [comment]
Are you familiar with Python programming? If so, it's fairly straightforward... I have been meaning to write some docs on write a plugin, maybe I'll do that :]

**Comment by sophof** [comment]
I am familiar with Python yes, the problem is more in the fundamentals of online streaming I suppose. If I go through the code for the npo plugin for example I'm quickly lost.

**Comment by beardypig** [comment]
Cool. [tvcatchup.py](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/tvcatchup.py) is a pretty basic plugin.

To make a `Plugin` you have to subclass `Plugin` and set the module level variable `__plugin__` to that class (`__plugin__ = TVCatchup`). Then you have to implement the two required methods, `can_handle_url` (a classmethod) and `_get_streams`. 

`can_handle_url` is super simple, you just return `True`/`False` if this plugin can handle the supplied URL. Normally this is done wit a regex, (`r"http://(?:www\.)?tvcatchup.com/watch/\w+"`). 

`_get_streams` is also pretty simple, you have either return a `list`, `iterable`, or `dict` containing the streams. The `dict` must have the quality name (eg. `540p`) as the key and an instance of `Stream` as the value, likewise with the `list`/`iterable` it must be a `tuple` of `(quality, stream)`. There are a number of different `Stream` classes in the [stream module](https://github.com/streamlink/streamlink/tree/master/src/streamlink/stream). The most common one now is probably `HLSStream` (as in tvcatchup). 
There is a special global `http` which is a [`requests.Session`](http://docs.python-requests.org/en/master/) instance (with some extra methods for json/xml), which has been set up with the users preferences, you should use this to do all http requests. You can see in the `tvcatchup` plugin, the page (`self.url`) is requested and an `m3u8` URL is searched for, if it is found then it is parsed with `HLSStream.parse_variant_playlist` if the URL contains `_adp`. `HLSStream.parse_variant_playlist` returns a properly formatted `dict` with all the streams. In the other case (`_adp` not in the URL) it assumes it's `576p` and returns a `dict` with one `HLSStream` instance.

If you fire up a python shell and do
```python
import streamlink
streamlink.streams("http://tvcatchup.com/watch/bbcone")
```
you will see what the plugin returns :) In this case the quality keys are in bitrate (`550k`, etc). Streamlink sorts the qualities returned by the `Plugin` (see [`stream_weight`](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L35) to see how the weights are compared). 

To write your own plugin you need to work out how the site works, and how it gets it stream urls (m3u8/f4m/etc.). Then it's just a case of getting your `Plugin` to replicate it :)

**Comment by sophof** [comment]
Thanks, I got as far as the first part on my own, but couldn't figure out that http was an instance of requests.Session.
Hopefully by reverse engineering the tvcatchup plugin I'll be able to figure out the difficult part (figuring out how to figure out how a site works :P)

**Comment by beardypig** [comment]
That's the real trick :) I can give you a list of pretty simple sites (with plugins) you want some more examples?

**Comment by gravyboat** [comment]
Closing since #642 is merged.
