### ISSUE TITLE
rtmpdump AMF data

### ISSUE THREAD

**Issue by ppsspp213** [streamlink/streamlink#640]
How do I apply the same in streamlink???
```
−−conn −C type:data
Append arbitrary AMF data to the Connect message. The type must be
B for Boolean, N for number, S for string, O for object, or Z for
null. For Booleans the data must be either 0 or 1 for FALSE or TRUE,
respectively. Likewise for Objects the data must be 0 or 1 to end or
begin an object, respectively. Data items in subobjects may be named,
by prefixing the type with 'N' and specifying the name before the value,
e.g. NB:myFlag:1. This option may be used multiple times to construct
arbitrary AMF sequences.
E.g. −C B:1 −C S:authMe −C O:1 −C NN:code:1.23 −C NS:flag:ok −C O:0
```

**Comment by gravyboat** [comment]
Please review the docs: https://streamlink.github.io/cli.html#playing-built-in-streaming-protocols-directly the second example in that section shows how to pass extra options to an rtmp stream.

**Comment by beardypig** [comment]
This should work:
```shell
streamlink "rtmp://streaming.server.net/playpath conn=B:1 conn=S:authMe conn=O:1 conn=NN:code:1.23 conn=NS:flag:ok conn=O:0"
```
But it will only take one value for conn, the last value. It's a simple fix, so I'll create PR to fix it... 
Meanwhile, I'll reopen this and use it to track the bug.

**Comment by beardypig** [comment]
For multiple `conn` value the following syntax can be used: 
```shell
streamlink "rtmp://streaming.server.net/playpath  conn=['B:1','S:authMe','O:1','NN:code:1.23','NS:flag:ok','O:0']"
```

**Comment by ppsspp213** [comment]
'conn' is not recognized as an internal or external command
operable program or batch file.

Does it work for m3u8 links too?

"hlsvariant://http://???/playlist.m3u8 conn=['S:??? ','S:??? ','S:??? ']"

**Comment by beardypig** [comment]
`conn` is only applicable to `RTMPStream`. What exactly are you trying to do?

**Comment by beardypig** [comment]
@ppsspp213 can you show us the command you ran where you got the error, so we can help you debug it?

**Comment by ppsspp213** [comment]
No I can't sorry, it contains paid for material.
I need to send the amf data back to the host otherwise it won't stream the content, opening the .m3u8 link in vlc just gives a 30 second error message.

Tells me the stream is 360p
streamlink "hlsvariant:// /playlist.m3u8" best --http-header "Referer= .swf" --http-header "Accept-Encoding=gzip, deflate" --http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"

error: No plugin can handle URL
streamlink "rtsp:// conn=['S: ','S: ','S: ']" best --http-header "Referer= .swf" --http-header "Accept-Encoding=gzip, deflate" --http-header "User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"

**Comment by ppsspp213** [comment]
Ok changed to rtsp to rtmp 

[cli][info] Found matching plugin stream for URL rtmp://
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][error] Could not open stream: Error while executing subprocess

**Comment by beardypig** [comment]
Can you run it again with `--cmdline` (`streamlink --cmdline "rtmp://..."`) to see what `rtmpdump` arguments are being passed?

**Comment by beardypig** [comment]
What does it output if you try to run that command? (put `-o test.flv` on the end, otherwise you might a load of junk on the console).

**Comment by ppsspp213** [comment]
Same 
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][error] Could not open stream: Error while executing subprocess

**Comment by beardypig** [comment]
I mean the `rtmpdump.exe` that it spit out before.

**Comment by ppsspp213** [comment]
Nothing it just shows C:\Users\user> on the next line.

**Comment by ppsspp213** [comment]
oops you meant input the actual code my bad.

It gives me the following error
ERROR: rtmp server requested close

**Comment by beardypig** [comment]
OK. Try it again, but put `-V` on the end too, to get the verbose output log.

**Comment by ppsspp213** [comment]
DEBUG: Protocol : RTMP
DEBUG: Hostname : 
DEBUG: Port     : 1935
DEBUG: Playpath : 
DEBUG: tcUrl    : rtmp://
DEBUG: app      : 
DEBUG: live     : no
DEBUG: timeout  : 30 sec
DEBUG: Setting buffer time to: 36000000ms
Connecting ...
DEBUG: RTMP_Connect1, ... connected, handshaking
DEBUG: HandShake: Type Answer   : 03
DEBUG: HandShake: Server Uptime : 96850052
DEBUG: HandShake: FMS Version   : 3.0.1.1
DEBUG: HandShake: Handshaking finished....
DEBUG: RTMP_Connect1, handshaked
DEBUG: Invoking connect
INFO: Connected...
DEBUG: HandleServerBW: server BW = 2500000
DEBUG: HandleClientBW: client BW = 2500000 2
DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
DEBUG: HandleCtrl, Stream Begin 0
DEBUG: HandleChangeChunkSize, received: chunk size change to 4096
DEBUG: RTMP_ClientPacket, received: invoke 18 bytes
DEBUG: (object begin)
DEBUG: Property: NULL
DEBUG: (object end)
DEBUG: HandleInvoke, server invoking <close>
ERROR: rtmp server requested close
DEBUG: Closing connection.

**Comment by beardypig** [comment]
I don't know, maybe you can find information elsewhere about using rtmpdump to capture that particular stream. Without knowing more about the stream and its required parameters, it's impossible for me to debug it I'm afraid. Sorry.

**Comment by gravyboat** [comment]
Closing since we already provided a lot of help.
