### ISSUE TITLE
areena.yle.fi : Finnish broadcasting service

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#644]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

YLE is broadcasting service of Finland. There are 5 channels : 

- YLE TV 1 : `http://areena.yle.fi/tv/suorat/yle-tv1`
- YLE TV 2 : `http://areena.yle.fi/tv/suorat/yle-tv2#autoplay=true`
- YLE Fem : `http://areena.yle.fi/tv/suorat/yle-fem#autoplay=true`
- YLE Teema : `http://areena.yle.fi/tv/suorat/yle-teema#autoplay=true`
- YLE Areena : `http://areena.yle.fi/tv/suorat/yle-areena/1-4009219#autoplay=true`

HLS and HDS are used for streaming. 

### Expected / Actual behavior

This is API address : `http://cdnapi.kaltura.com/api_v3/index.php?service=liveStream&apiVersion=3.1&expiry=86400&clientTag=kwidget%3Av2.52&format=1&ignoreNull=1&action=islive&id=0_xxdtnjgg&protocol=hls&partnerId=1955031&kalsig=bd8ba6c7602538a961905b839c0fd404`

### Reproduction steps / Stream URLs to test

```
streamlink "hlsvariant://http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8" best
[cli][info] Found matching plugin stream for URL hlsvariant://http://yletvhdlive
world-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8
[cli][info] Available streams: 576p_alt, 396p_alt, 720p_alt, 360p_alt, 270p_alt,
 180p_alt, 180p (worst), 270p, 360p, 396p, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Environment details (operating system, python version, etc.)

W7 PRO/Streamlink portable

### Comments, logs, screenshots, etc.

Channels are geolocked but they provide broadcasting message abroad.

**Comment by LoneFox78** [comment]
There is an implementation of this as a separate program at https://github.com/aajanki/yle-dl .
It does require both python2 and php though, and is a bit clunky to use for live streaming, because it is made mainly for downloading videos and not watching them live...

**Comment by beardypig** [comment]
WIP branch: https://github.com/beardypig/streamlink/tree/yle_areena

**Comment by karlo2105** [comment]
Working fine. HDS is also freely available. ;)

**Comment by tp0** [comment]
`yle-dl` is great for downloading (not live, only the on-demand videos), but not so good for viewing as only way to open a stream directly in a player is to pipe it and seeking works badly (even with this: `yle-dl --pipe "URL" | mpv --force-seekable=yes -`).

Until the plugin is complete and added one can just use these URLs directly as they do not change often:

    TV1: http://yletvhdliveworld-lh.akamaihd.net/i/yletv1hdworld_1@187592/master.m3u8
    TV2: http://yletvhdliveworld-lh.akamaihd.net/i/yletv2hdworld_1@187593/master.m3u8
    Teema: http://yletvhdliveworld-lh.akamaihd.net/i/yleteemahdworld_1@187591/master.m3u8
    Fem: http://yletvhdliveworld-lh.akamaihd.net/i/ylefemfihdworld_1@187589/master.m3u8

**Comment by tp0** [comment]
Tested the WIP plugin. Works. What about the on-demand videos though?

**Comment by eeehhh** [comment]
Two channel, Teema and Fem, were combined into one.

The new Teema&Fem channel live stream:

in Finnish audio:
http://yletv-lh.akamaihd.net/i/yleteemafemfi_1@490775/master.m3u8

in Swedish audio:
http://yletv-lh.akamaihd.net/i/yleteemafemse_1@490776/master.m3u8

**Comment by back-to** [comment]
Not worth for a new plugin,
some of the direct urls are still working and can be used.
