### ISSUE TITLE
Plugin: animelab.com VOD

### ISSUE THREAD

**Issue by starchivore** [streamlink/streamlink#645]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Both [animelab.com](https://www.animelab.com) and [https://dcgm6i50yfgtk.cloudfront.net](https://dcgm6i50yfgtk.cloudfront.net) are definitely AU/NZ only so either VPN or proxy should be required, though they're doing stuff like this here:

https://github.com/mczub/because-moe/blob/feature/animelab-fix/generate/au.py#L28
https://github.com/mczub/because-moe/blob/feature/animelab-fix/generate/animesources.py#L227

Not really sure about how their API is supposed to work, maybe these links could help?

https://github.com/edpenz/holo/blob/master/src/services/stream/animelab.py

https://github.com/mczub/because-moe/blob/feature/animelab-fix/generate/au.py#L28
https://github.com/mczub/because-moe/blob/feature/animelab-fix/generate/animesources.py#L227

https://github.com/arkenthera/Chiika/blob/master/src/main_process/stream-services.coffee#L27

https://github.com/khloke/play-to-xbmc-chrome/blob/master/js/modules.js#L27
https://github.com/khloke/play-to-xbmc-chrome/blob/master/js/content_scripts/animelab-content-scripts.js

This is how we're getting the latest and greatest:

https://www.animelab.com/api/shows/all?limit=100&page=0
https://www.animelab.com/api/shows/all?limit=100&page=1
https://www.animelab.com/api/shows/all?limit=100&page=2

As usual I'm picking _[Dragon Ball Z](https://www.animelab.com/shows/dragon-ball-z)_ as an example, English dub is only available for paid members and subbed episodes are free:

https://www.animelab.com/player/dragon-ball-z-episode-1/subtitles
https://www.animelab.com/player/dragon-ball-z-episode-2/subtitles
https://www.animelab.com/player/dragon-ball-z-episode-3/subtitles
https://www.animelab.com/player/dragon-ball-z-episode-4/subtitles
https://www.animelab.com/player/dragon-ball-z-episode-5/subtitles

API didn't show us anything helpful except for `"episodeCount"` etc.

https://www.animelab.com/api/shows/271

This is `forward=true`:

```
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10070&position=0&forward=true&_=1488385408682
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10072&position=1&forward=true&_=1488385408682
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10074&position=2&forward=true&_=1488385408682
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10076&position=3&forward=true&_=1488385408682
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10078&position=4&forward=true&_=1488385408682
```

This is `forward=false`:
```
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10070&position=0&forward=false&_=1488385443976
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10072&position=1&forward=false&_=1488385443976
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10074&position=2&forward=false&_=1488385443976
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10076&position=3&forward=false&_=1488385443976
https://www.animelab.com/api/videos/show/271/subtitles?videoId=10078&position=4&forward=false&_=1488385443976
```

And then _[Dragon Ball Super](https://www.animelab.com/shows/dragon-ball-super)_ is only hard-subbed (i.e. `"hardSubbed":true`) for all episodes, let's pick episodes 76 to 80 then:

https://www.animelab.com/player/dragon-ball-super-episode-76
https://www.animelab.com/player/dragon-ball-super-episode-77
https://www.animelab.com/player/dragon-ball-super-episode-78
https://www.animelab.com/player/dragon-ball-super-episode-79
https://www.animelab.com/player/dragon-ball-super-episode-80

Same deal:

https://www.animelab.com/api/shows/312

```
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12059&position=75&forward=true&_=1488383158879
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12060&position=76&forward=true&_=1488383158879
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12897&position=77&forward=true&_=1488383158879
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12898&position=78&forward=true&_=1488383158879
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12899&position=79&forward=true&_=1488383158879
```

```
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12059&position=75&forward=false&_=1488383220942
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12060&position=76&forward=false&_=1488383220942
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12897&position=77&forward=false&_=1488383220942
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12898&position=78&forward=false&_=1488383220942
https://www.animelab.com/api/videos/show/312/subtitles?videoId=12899&position=79&forward=false&_=1488383220942
```

Obviously we've got:
https://www.animelab.com/api/videos/show
/`"showId"`/
subtitles
?videoId=`"id"`
&position=`"episodeNumber"`-1 (for `sub` only) or something else like `"episodeNumber"`-2 (for `sub`+`dub`)?
&forward=`true` or `false`
&_=`UNIX Epoch Time`

Finally getting the direct link to `mp4` files @ `360p` and `480p` should be extremely easy:

https://www.animelab.com/api/videos/show/312/subtitles?videoId=12899&position=79&forward=true&_=1488383158879

```
[{"id":12899,"customId":null,"language":{"id":94,"name":"Japanese","languageCode":"ja-JP"},"aspectRatio":{"id":2,"name":"16:9"},"hardSubbed":true,"videoInstances":
[{"id":60049,"customId":null,"videoQuality":{"id":1,"name":"360p","description":"360p"},"bitrate":370,"filename":"epx_60049_2d7cb99ad53744d.mp4","rtmpUrl":null,"httpUrl":"https://dcgm6i50yfgtk.cloudfront.net/epx_60049_2d7cb99ad53744d.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vZGNnbTZpNTB5Zmd0ay5jbG91ZGZyb250Lm5ldC9lcHhfNjAwNDlfMmQ3Y2I5OWFkNTM3NDRkLm1wNCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQ4ODM5NTI5OH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiI0NS42My4yNS4xNzcvMzIifSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0ODgwNzA4MDB9fX1dfQ__&Signature=VMZLNAOiBYuoLMivDj2toC1diSJdah8~HANCrDLZZdMUQrOaYAJbxYLOlV8MiwqK3bPzLxtAGZIpyzmPs0FUFMl5tjjbYDVqXEks8xpy3-nefZHTGPRS~lGi6I56jNRyjJNIUp8e9vDS0hfNORWoSb1O5blOHd4JAuGZ-2xS~yGfjMae7M4aM~1f~YWaQL8Dc8btntYDh6KhUIGtyB1Hef0pqiuPaTs9xtlY0SG3UhcFkEecmghDDPtDMyKfzoOg1d4oobRqXdFw9u~F-AxxT260Zvmju3BYHliBgN-yoAvLhR43U0~Ht9h~aZ0m2GbxiDtK-XTqZ7lafysLLhF4FA__&Key-Pair-Id=APKAIBVNY4D2OGLVFK6A"},
{"id":60050,"customId":null,"videoQuality":{"id":2,"name":"480p","description":"480p"},"bitrate":500,"filename":"epx_60050_8ed6910d5e0e4b6.mp4","rtmpUrl":null,"httpUrl":"https://dcgm6i50yfgtk.cloudfront.net/epx_60050_8ed6910d5e0e4b6.mp4?Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vZGNnbTZpNTB5Zmd0ay5jbG91ZGZyb250Lm5ldC9lcHhfNjAwNTBfOGVkNjkxMGQ1ZTBlNGI2Lm1wNCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQ4ODM5NTI5OH0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiI0NS42My4yNS4xNzcvMzIifSwiRGF0ZUdyZWF0ZXJUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0ODgwNzA4MDB9fX1dfQ__&Signature=GFWuAyxxN8GmMnb3Ahdwtb~8Bt2HJ7ie951gJA~oYIuWwdkI~SyzotAxvwOGGecEicP2sKROPB6tZ0G30jApUlHuiOxHQuQNvsrNJeJhMq2CHPPtYPygtwrmS2bus3wwgN7O2ZZ2S7hKRTgRI2yatMyMHHBtHWTFENu2KyMSI-D3Upx~wh3-0aqFyDunlzE7Kk1DjywFZUjpJxm7pXZqz4bs8yRUPTIhX9NmZVQIiQiZP360n8u5uRAOrZWChNqnYuEXwRIvFAKDKjbZV~GYn3MuNUr23BRIAyD95qobO~81pH21RaA5IPkoibDx-LUsfOurQijMrRN4jUohehxiKQ__&Key-Pair-Id=APKAIBVNY4D2OGLVFK6A"},
```

**Comment by gravyboat** [comment]
Closing this out since #648 is merged.
