### ISSUE TITLE
Plugin: mytv.tvb.com VOD

### ISSUE THREAD

**Issue by starchivore** [streamlink/streamlink#655]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Hong Kong proxy / VPN required:

https://addons.mozilla.org/en-US/firefox/addon/zenmate-security-privacy-vpn/
https://chrome.google.com/webstore/detail/zenmate-vpn-best-cyber-se/fdcgdnkidjaadafnichfpabhfomcebme?hl=en

This is what they did for that:

https://github.com/alvinhkh/unblock-mytv
https://github.com/zllikey/Mytv/blob/master/MYTV去除地区限制

Let's start with an easy one:

http://news.tvb.com/local/58b8dc396db28cd037ed21f2/

Direct links to grab `mp4`:

http://token.tvb.com/stream/vod/news/http/content1/export/20170303/entries_58b8dc396db28cd037ed21f2_ed5dbdd2da9881c10dc1a37f4472042f_cht_1024_576_500k_v3.mp4

http://token.tvb.com/stream/vod/news/http/content1/export/20170303/entries_58b8dc396db28cd037ed21f2_ed5dbdd2da9881c10dc1a37f4472042f_cht_1280_720_1500k_v2.mp4

However, it's quite tricky to get anything via `rtmpe` or `hls` since September 2016:

http://mytv.tvb.com/tc/ch_inews/ed_inewscatchup/newswatchenglish/299019

Link to `json`:

http://api.mytv.tvb.com/rest_user_subscription_api/video_path/format/json?id=299019

Change `rtmpe` to `hls`:

http://token.tvb.com/stream/vod/hls/he9/988754/000001372676.mp4?feed
http://token.tvb.com/stream/vod/hls/he9/988754/000001372677.mp4?feed
http://token.tvb.com/stream/vod/hls/he9/988754/000001372679.mp4?feed

Similar one with subtitles:

http://mytv.tvb.com/en/ch_j2/ed_foodtravel/hipstertourusa/297002
http://api.mytv.tvb.com/rest_user_subscription_api/video_path/format/json?id=297002

Examples of subtitles:

http://img.tvb.com/he/subtitle/1504/150363_tc.xml
http://img.tvb.com/he/subtitle/1854/185303_tc.xml
http://img.tvb.com/he/subtitle/2544/254360_tc.xml

Related threads:

http://forum.videohelp.com/threads/311893-How-to-download-flash-video-RTMP-RTMPE-streams-using-free-software?p=2392467&viewfull=1#post2392467

http://forum.videohelp.com/threads/377011-seeking-help-with-rtmpdump?p=2433467&viewfull=1#post2433467

http://forum.videohelp.com/threads/377354-%5BHELP%5D-Capture-embedded-stream

http://forum.videohelp.com/threads/380693-How-to-get-subtitles-in-MyTV-%28TVB%29

http://forum.videohelp.com/threads/381194-seek-help-in-using-rtmpdump

Right now only [TubeDigger](http://www.tubedigger.com) and [RTMPDumpHelper](http://www.nirsoft.net/utils/rtmp_dump_helper.html) seem to work but no luck with anything else.

**Comment by gravyboat** [comment]
Thanks for the detailed issue!

**Comment by lakb8** [comment]
when  open http://api.mytv.tvb.com/rest_user_subscription_api/video_path/format/json?id=299019

I found this:

> {"profiles":{"low":{"Cantonese":"rtmpe:\/\/wowza.stream.tvb.com\/vipo\/_definst_\/mp4:vipo\/mytvsuper12\/9888\/988754\/000001372676.mp4?ts=1488652899&sig=fdc5c8abe1706298a834eddda18bdada&audioindex=0"},"high":{"Cantonese":"rtmpe:\/\/wowza.stream.tvb.com\/vipo\/_definst_\/mp4:vipo\/mytvsuper12\/9888\/988754\/000001372677.mp4?ts=1488652899&sig=084b3b10912c524fe72fb4e0004f8d2a&audioindex=0"},"hd":{"Cantonese":"rtmpe:\/\/wowza.stream.tvb.com\/vipo\/_definst_\/mp4:vipo\/mytvsuper12\/9888\/988754\/000001372679.mp4?ts=1488652899&sig=ae5467e595192ef6086f6ce368761b98&audioindex=0"},"auto":{"Cantonese":"rtmpe:\/\/wowza.stream.tvb.com\/vipo\/_definst_\/mp4:vipo\/mytvsuper12\/9888\/988754\/988754_mobile_auto.mp4?ts=1488652899&sig=3be72faf70089e2a3ee267c89c1cf62b&audioindex=0"}},"is_drm":false,"protocol":"hls","breakpoints":[],"opening_start_at":["0"],"subtitle":{},"is_pay":0,"duration":92.04,"chapters":[]}

how can i find the real url?

**Comment by starchivore** [comment]
> how can i find the real url?

I just found this today:

http://stream-recorder.com/forum/rtmpdump-camfuze-t20403.html

So I downloaded that and grep as well:

http://downloads.sourceforge.net/gnuwin32/grep-2.5.4-dep.zip
http://downloads.sourceforge.net/gnuwin32/grep-2.5.4-bin.zip

Then I tried this:

http://img.tvb.com/mytv4/swf/supertv_r2-1.swf

Running `swfdump -a supertv_r2-1.swf | grep -C 3 secureToken` would gimme this for the `--token` parameter:

`00083) + 2:1 pushstring`

**Comment by schtroumpfs** [comment]
do you know how to download from mytvysuper?

**Comment by renwokuang** [comment]
现在所有代码都失效了

**Comment by gravyboat** [comment]
@renwokuang Please try to keep things in English when possible! We're a pretty international team so it makes things a bit easier for everyone.

**Comment by renwokuang** [comment]
ok

**Comment by renwokuang** [comment]
Can someone download mytvsuper?

**Comment by popolihu123** [comment]
Ask God to provide super code

**Comment by back-to** [comment]
the original website got already replaced with a different one.

The new website is not really accessible,
so I don't see someone adding support for this website in the near future.

closing
