### ISSUE TITLE
Streams close after about 20 seconds

### ISSUE THREAD

**Issue by briminator** [streamlink/streamlink#656]
### Description
I tried opening some livestream.com streams, some hlsvariant streams and an hls streams extracted from the hlsvariant. Both hls types were from livestream.com, so this is a livestream problem.

### Expected / Actual behavior
I expected the stream to continue playing until I stopped it
What happened is it just stopped after a certain amount of time

- [x] This is a feature request
- [x] This is a bug report

### Reproduction steps / Stream URLs to test

1. type streamlink https://livestream.com/URL_REMOVED_AS_ITS_NOT_LIVE_ANYMORE 720p_hls (hls_alt does the same)
2. It opens the player and then closes it down after about 20 seconds

Note: not selecting an hls stream is not an option for me. It didn't work properly anyway.

### Environment details (operating system, python version, etc.)

Running Windows 10 Preview Build 15046 - Also tested on 14393 (latest Win10 release) same result)
Latest nightly build as at 9AM UTC 3/3/17

### Comments, logs, screenshots, etc.

C:\Users\REMOVED>streamlink --loglevel debug https://livestream.com/REMOVED 720p_hls_alt
[cli][info] Found matching plugin livestream for URL https://livestream.com/REMOVED
[cli][info] Available streams: 216p_hls, 576p_hls, 720p_hls_alt, 576p_hls_alt, 720p_hls, 432p_hls_alt, 216p_hls_alt, 432p_hls, 216p (worst), 432p, 576p, 720p (best)
[cli][info] Opening stream: 720p_hls_alt (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 148853104 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 148853105 to queue
[stream.hls][debug] Adding segment 148853106 to queue
[stream.hls][debug] Adding segment 148853107 to queue
[stream.hls][debug] Adding segment 148853108 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 148853104 complete
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 148853105 complete
[stream.hls][debug] Download of segment 148853106 complete
[stream.hls][debug] Download of segment 148853107 complete
[stream.hls][debug] Download of segment 148853108 complete
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

From what I can see, it is only loading the 4 segments it finds when looking for the hls stream and does not search for any others in future.

**Comment by karlo2105** [comment]
Could you give a try with this stream ?

`https://livestream.com/accounts/3161248/rabbitohsvtigers2017`

**Comment by briminator** [comment]
I was actually trying the previous stream from NRL when I noticed this problem. I tried this one, however and it lasted a bit longer, but still, it closed.

C:\Users\REMOVED>streamlink --loglevel debug https://livestream.com/accounts/3161248/rabbitohsvtigers2017 720p_hls
[cli][info] Found matching plugin livestream for URL https://livestream.com/accounts/3161248/rabbitohsvtigers2017
[cli][info] Available streams: 216p_hls_alt, 576p_hls_alt, 720p_hls, 216p_hls, 432p_hls, 720p_hls_alt, 432p_hls_alt, 576p_hls, 216p (worst), 432p, 576p, 720p (best)
[cli][info] Opening stream: 720p_hls (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 148853331 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 148853332 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 148853333 to queue
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[stream.hls][debug] Download of segment 148853331 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 148853332 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 148853333 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 148853334 to queue
[stream.hls][debug] Adding segment 148853335 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 148853334 complete
[stream.hls][debug] Download of segment 148853335 complete
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by karlo2105** [comment]
Same here. I think it's related to their choppy servers.

**Comment by briminator** [comment]
Is there some way to tell streamlink to keep looking for new available segments or is there some other fix?

**Comment by beardypig** [comment]
Which region is that stream geo-blocked to?

**Comment by briminator** [comment]
Basically any country that does not have a broadcast deal with the NRL will be able to access it. So, basically  from what I can see Australia, US, UK and Canada all do not work. There may be others that do not work as well. Apart from that, I think most other countries work

**Comment by beardypig** [comment]
Ah OK. That explains why it didn't work from those countries, Germany didn't work either though.

**Comment by briminator** [comment]
Getting a new error when I try to load up a stream from the same account:

streamlink --loglevel debug https://livestream.com/nrl/seaeaglesveels2017 720p_hls_alt
[cli][info] Found matching plugin livestream for URL https://livestream.com/nrl/seaeaglesveels2017
error: Unable to open URL: http://api.new.livestream.com/accounts/3161248/events/6990842/broadcasts/150981469.m3u8?dw=100&hdnea=st=1488687506~exp=1488689306~acl=/i/3161248_6990842_lsikuj64egps4ekxegt_1@305457/*~hmac=5291092fa4361e8734f8b3aa91d4305abe12c57faf8eb837996626d0fbe55427 (404 Client Error: Not Found for url: http://livestream-f.akamaihd.net/i/3161248_6990842_lsikuj64egps4ekxegt_1@305457/master.m3u8?__b__=728&dw=100&hdnea=st=1488687506~exp=1488689306~acl=/i/3161248_6990842_lsikuj64egps4ekxegt_1@305457/*~hmac=5291092fa4361e8734f8b3aa91d4305abe12c57faf8eb837996626d0fbe55427&__a__=off)

Visiting the links directly for the 404 errors brings this up:

An error occurred while processing your request.
Reference #216.4f508795.1488687531.4815674

**Comment by briminator** [comment]
Under further investigation, it seems that the NRL is somehow using dynamic links with its streaming, meaning that the link will change in some way at some point in time. From what I've seen Streamlink does not properly support this. This is the first time I've seen this happen. I've tried many other links on Livestream.com, but their links seem to stay constant.

**Comment by briminator** [comment]
Early indications suggest that this issue was an issue of livestream.com. This can now be closed
