### ISSUE TITLE
How bind all traffic to specific interface ip

### ISSUE THREAD

**Issue by roneyrogerio** [streamlink/streamlink#66]
My first need is this, specify the IP interface through which the traffic must pass, trying to solve this question came many others.

Correct me if I'm wrong, this functionality does not exist, then my first idea was to create a custom proxy where I would spend the interface ip on the link and pass the proxy by command line --http(s)-proxy, ex:
http://127.0.0.1:8080/proxy/10.0.0.1/http(s)/

I expected the livestreamer call something like:
http://127.0.0.1:8080/proxy/10.0.0.1/http(s)/my.requested.link.com/streaming/playlist.m3u8

But that's not what happened, it ignores all directories and I get something like this:
http://127.0.0.1:8080/http(s)://my.requested.link.com/streaming/playlist.m3u8

Ie is totally impractical to use the proxy command to try to pass the traffic through a specific interface.

The second idea would be to pass the link .m3u8 directly with the proxy link, but would not work for other livestremer plugins and also not work with hls streams where each segment has the full file path and not just the name.

Some solution for this?

**Comment by beardypig** [comment]
If you are using Linux or similar you might be able to use https://tinyproxy.github.io which provides an HTTP(S) proxy that you can bind to a specific ip for outgoing connections while allowing you to listen on a different interface. Then you should just be able to use it with the - - http-proxy option.

**Comment by gravyboat** [comment]
Closing this one out since there hasn't been discussion in a while and an answer has been provided.
