### ISSUE TITLE
ARD Live outdated

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#660]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

ARD is German PBS. 

### Reproduction steps / Stream URLs to test

```
streamlink "http://www.daserste.de/live/index.html"
error: No plugin can handle URL: http://www.daserste.de/live/index.html
```

### Environment details (operating system, python version, etc.)

As usual ;)

**Comment by gravyboat** [comment]
Closing since #661 is merged.
