### ISSUE TITLE
Question About Tvplayer

### ISSUE THREAD

**Issue by willbrow** [streamlink/streamlink#664]
Hi i have two questions please forgive me as i am new to streamlink:

Ive noticed that after a few hours that the stream stops piping to VLC player and in CLI it is showing by the looks of it that the KEY has expired by the looks of it ofwitch makes sence for them to expire your session after a certain amount of time.

Anyway my question - Is there anyway to set streamlink so that if a connection fails or expires to run the CLI command again that was entered to get a new keyid and start the pipe again to VLC with same port number.I have seen option where if connection is lost to keep trying but not one to submit the streamlink --tvplayer-email --tvplayer-password tvplayer.com/watch/bbc best and pipe the stream on the same port.

My second question is if i had other devices in my house on the same network and wanted to watch the stream on them via restreaming is there anyway to do this,  I have tried VLC setting source as IP:PORT but does not seem to work so maybe there is setting i need to change or different player will re-stream better.I have also tried connection the devies directly to 127.0.0.1:port 

Thanks for everyones help

**Comment by beardypig** [comment]
We can create a new `Stream` implementation that refreshes the URL when it expires. Alternatively `--player-continuous-http` might work for you. 

VLC supports creating an RTSP for streaming video to multiple clients, there is a lot of documentation online about doing that :)

**Comment by willbrow** [comment]
Hi 

Is it possible to create new stream implementation automatically when the old one expires or is the only way manually ?
With VLC you need to select the source to stream via rtsp or other protocols and when you enter the source IP:Port it is not able to stream maybe this is becuase the video is being piped im not sure but i will keep trying to find a solution 

thanks

**Comment by beardypig** [comment]
By new `Stream` implementation, I mean write some new code to handle it automatically :) 

I thought there was a way to start a stream while it was playing, but seems like I am mistaken.

**Comment by willbrow** [comment]
I have tried everything i can think off to stream through vlc .

It must be something to do with rtmpdump or whatever pipes the video to vlc

**Comment by back-to** [comment]
#2626
