### ISSUE TITLE
Youtube Live doesn't work with VLC

### ISSUE THREAD

**Issue by ethanhlc** [streamlink/streamlink#67]
So, I found that Youtube Live doesn't work with VLC.
The stream open up fine, but the video stays frozen after opening.
Normal videos on youtube, however, work fine.

I've tried youtube live with a different video player (Daum Pot Player) which worked, so I'm not sure if it's a problem with streamlink, or something else.

If any more details are needed please tell me how to get it and I'll try my best to post them.

**Comment by sbstp** [comment]
This is a known bug with VLC.

**Comment by gravyboat** [comment]
Going to close this for now since we can't fix it, if there are any updates please let us know @ethanhlc!

**Comment by cdrage** [comment]
@gravyboat So this is an upstream issue with VLC and we can't do anything about it, correct?

**Comment by scottbernstein** [comment]
It is also known that if you update your VLC Player to the 3.0 beta, it works fine.  So that can be your solution ethanhlc

________________________________

**Comment by gravyboat** [comment]
@cdrage Correct.

**Comment by c769214** [comment]
check my response of the following post ... there is a temporary solution for youtube live issue....

[https://github.com/chrippa/livestreamer/issues/1314](url)

See this will help....

**Comment by gravyboat** [comment]
Thanks for the workaround @c769214, this is the comment in question: https://github.com/chrippa/livestreamer/issues/1314#issuecomment-219377531

**Comment by Kevin-** [comment]
What is the workaround?  Link above is 404.
