### ISSUE TITLE
Notifications are very delayed (40 mins) and grouped up

### ISSUE THREAD

**Issue by vohzi** [streamlink/streamlink#676]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Instead of showing the notification at the time the stream starts it shows them grouped with other notifications about 40 minutes later.

...

### Expected behavior
Instant notification

...

### Reproduction steps / Stream URLs to test

Any stream
1. ...
2. ...
3. ...

### Environment details (operating system, python version, etc.)
Windows 7 64 bits python 3.5.2
...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
Is this in relation to the GUI? If so can you please close this and open an issue there: https://github.com/streamlink/streamlink-twitch-gui
