### ISSUE TITLE
Add argument for duration of streams

### ISSUE THREAD

**Issue by Marocco2** [streamlink/streamlink#68]
Hi!
Like the title says, I'd like have a command line to stop watching the stream after an hour or so, even if the stream is not ended.

**Comment by scottbernstein** [comment]
I like this feature request!

________________________________

**Comment by bastimeyer** [comment]
You could just write a simple bash script that terminates the streamlink process after X seconds (first parameter):

```bash
#!/bin/bash

pid=0

function finish {
	[ ${pid} -gt 0 ] && kill ${pid} 2>/dev/null
}
trap finish EXIT

streamlink ${@:2} &
pid=$!

sleep "${1}"
finish
```

**Comment by scottbernstein** [comment]
Yes, that would of course do it, but it's not as friendly nor is it portable between operating systems.

________________________________

**Comment by Marocco2** [comment]
@bastimeyer but this method will corrupt any output file from the stream, doesn't it?

**Comment by bastimeyer** [comment]
Why would it corrupt it? It's just sending a TERM signal after X seconds to the streamlink process. Everything that happens after this is up to streamlink.

You can check the integrity of stream recordings with ffmpeg, like this:
```bash
./watch.sh 30 -o recording.ts -f URL QUALITY
ffmpeg -v error -i recording.ts -f null - 2>&1
```

**Comment by arpit1997** [comment]
I agree to @bastimeyer his solution of a bash  script is perfect
```

pid=0

function finish {
    [ ${pid} -gt 0 ] && kill ${pid} 2>/dev/null
}
trap finish EXIT

streamlink ${@:2} &
pid=$!

sleep "${1}"
finish
```
you can cur=tomize this script to listen and then stop the streamlink after  your specfied time

**Comment by priyavadan** [comment]
can you provide an example of this bash script will be used?

**Comment by beardypig** [comment]
Alternative `ffmpeg` solution to stop the stream after a given number of seconds (3600 in this case)
```shell
streamlink "http://www.ustream.tv/nasahdtv" best -O | ffmpeg -i pipe:0 -t 3600 -f mpegts -c copy - | mpv -
```

**Comment by gravyboat** [comment]
This is extremely old so I'm closing it, plenty of workarounds have been proposed here and in the linked issues.
