### ISSUE TITLE
Question about multi audio streams (hls live streams)

### ISSUE THREAD

**Issue by WazZ87** [streamlink/streamlink#681]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

When i try to play a live stream with more than one audio stream, i can't.

This issue is exactly what i need #485 

In my case, the english audio stream is named "qaa" and the french one "fra"

However i can play separately the "qaa" and "qad" audio streams.

Thanks

### Expected / Actual behavior

Playing any audio stream when it is possible.

### Reproduction steps / Stream URLs to test

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="fra",NAME="fra",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="qaa",NAME="qaa",AUTOSELECT=NO,DEFAULT=NO,URI="http://ncdn-sr.adam.sfr.fr/iphone/tf1_audio_qaa/tf1.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",LANGUAGE="qad",NAME="qad",AUTOSELECT=NO,DEFAULT=NO,URI="http://ncdn-sr.adam.sfr.fr/iphone/tf1_audio_qad/tf1.m3u8"
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=364050,RESOLUTION=320x180,CODECS="mp4a.40.5,avc1.42c01e",AUDIO="audio"
http://ncdn-sr.adam.sfr.fr/iphone/tf1_299968/tf1.m3u8
```

### Environment details (operating system, python version, etc.)

Python 2.7 on Debian 8

### Comments, logs, screenshots, etc.

**Comment by beardypig** [comment]
@WazZ87 I've created a PR that should solve your problem :)

**Comment by WazZ87** [comment]
Hi @beardypig,
It's all good now !
Thanks.

**Comment by beardypig** [comment]
Glad to hear it worked for you :-)
