### ISSUE TITLE
twitch streams only show white screen

### ISSUE THREAD

**Issue by Crazy-KSK** [streamlink/streamlink#682]
### Checklist
- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
it was working fine 12 hours ago
now if I open any twich stream vlc only shows a [white screen](http://i.imgur.com/rKBM8so.jpg), sound is working fine

I redid the config file and reset vlc to default settings and tried the nightly version with no success 

### Reproduction steps / Stream URLs to test
open any twich stream

### Environment details (operating system, python version, etc.
win 7
streamlink 0.3.2 installer
streamlink latest installer
neither works

**Comment by beardypig** [comment]
Have you tried saving the stream to a file to see if it is also white or just when streaming?

**Comment by Crazy-KSK** [comment]
how do I do that?

**Comment by beardypig** [comment]
Just add `-o twitch-test.ts` when you run streamlink, the stop it with ctrl-c :-)

**Comment by Crazy-KSK** [comment]
thanks!
yes just as white as the stream but mpc-hc plays it fine 
I guess vlc is broken somehow

**Comment by Crazy-KSK** [comment]
turns out it was my graphics driver(amd), resetting that to default fixed it

**Comment by gravyboat** [comment]
Thanks for the update @Crazy-KSK! I'm going to close this now.
