### ISSUE TITLE
Sinclair Broadcast Channels (Charge!, Comet, and TBD).

### ISSUE THREAD

**Issue by RedPenguin2** [streamlink/streamlink#687]
- [x] This is a bug report.
### Description
Sinclair Broadcast Group has 3 separate channels that are free to live stream online.

They use an m3u8 file and show the stream as expected but where the problem seems to lie is in commercial breaks.

They will show the TV shows as usual online but then jump to a screen saying "We're Be Right Back!" which some users of devices like the Fire TV said it causes their players to really use CPU.

### Expected / Actual behavior

I expect to have an mp4 outputted that I can watch or edit in any software just like any other stream I've ever recorded with streamlink.

### Reproduction steps / Stream URLs to test

1. ... streamlink -f --hls-segment-threads 10 --hls-segment-attempts 25 "hlsvariant://http://content.uplynk.com/channel/c1c931fb16184c9391bd0b0c91f30354.m3u8?tc=1&exp=1614631202&rn=1318676852&ct=c&cid=c1c931fb16184c9391bd0b0c91f30354&ad=charge&ad.adUnit=%2FCHARGE%2FLivestream_midroll&ad._debug=CHARGE_ssai_livestream_midroll&ad.ad_rule=1&ad.pmad=12&ad.output=xml_vmap1&sig=28e5dcf3f704effb0e8c5dea5f718bb00d79abc2d2c7b8d2552b1fd94eddaecd" best

### Environment details (operating system, python version, etc.)

Windows 10 Home

### Comments, logs, screenshots, etc.

streamlink appears normal when recording, counting the size and time.

Yet when you look at the file afterwards, it appears to be the correct size based on 720P resolution but Kodi, ffmpeg, VLC, and other software have an extremely tough time seeking it and today's file the players think is only a few seconds long even though it's at least 4 hours long.

A repair tool I have just completely crashed while trying to repair the mp4.

**Comment by RedPenguin2** [comment]
It seems while ffmpeg failed to fix the output file it appears that avconv is able to fix it.

Though I wonder if there is a way to have it record a file that isn't already a convoluted mess that plays right off the bat.

I know it has to be something on Sinclair or Uplynk's end as no other stream I've used through streamlink has ever done this.

**Comment by beardypig** [comment]
What's the site with the actual player on it? Might be easier to make a plugin or atleast understand the context.

**Comment by beardypig** [comment]
After having a quick look at the HLS playlist and waiting for an ad, you can see that `#EXT-X-DISCONTINUITY` is the likely cause of your issue. The `#EXT-X-DISCONTINUITY` tag is meant to tell the player that a differently formatted stream is now playing, ie. a discontinuity. 

With regards to supporting this, I'm not sure.

**Comment by RedPenguin2** [comment]
It doesn't look very promising but the websites are:

http://watchcharge.com/watch-live
http://comettv.com/watch-live/
http://www.tbd.com

Just in case anything can be done.

**Comment by amurzeau** [comment]
I found that using VLC 3.0, the stream works, using latest version 2.x it freeze at first frame.
There is a vlc 3.0 warning "ts warning: No PCR received for program 1, set up workaround using pid 258", maybe that's the cause of the freeze on vlc 2.x.
