### ISSUE TITLE
[0.4.0] beam.pro VODs don't work

### ISSUE THREAD

**Issue by Tharn** [streamlink/streamlink#688]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

When inputting a beam.pro VOD link into streamlink, you get a 404 Client Error. API problem?

### Expected / Actual behavior

The VOD plays as normal.

### Environment details (operating system, python version, etc.)

Windows 8.1 64bit, MPC-HC, Streamlink 0.4.0.

### Comments, logs, screenshots, etc.

``````
'streamlink.exe --player-passthrough hls https://vodcdn.beam.pro/content_e613c2b1-c3b3-4bb9-9014-7a73b60f8f75/16845301-5961-4442-aeb7-82214480fa71/ best'
[cli][info] Found matching plugin beam for URL https://vodcdn.beam.pro/content_e613c2b1-c3b3-4bb9-9014-7a73b60f8f75/16845301-5961-4442-aeb7-82214480fa71/
error: Unable to open URL: https://beam.pro/api/v1/channels/content_e613c2b1-c3b3-4bb9-9014-7a73b60f8f75 (404 Client Error: Not Found for url: https://beam.pro/api/v1/channels/content_e613c2b1-c3b3-4bb9-9014-7a73b60f8f75)
``````

Going by the straight URL from beam.pro website, I get:

``````
'streamlink.exe --player-passthrough hls https://beam.pro/revocane?vod=1079377 best'
[cli][info] Found matching plugin beam for URL https://beam.pro/revocane?vod=1079377
error: No playable streams found on this URL: https://beam.pro/revocane?vod=1079377
``````

**Comment by gravyboat** [comment]
Did this work previously? From what I recall beam.pro has never worked (VODs or livestreams) because they use WebRTC which is a lot of work to implement. We had some discussion on it here: https://github.com/streamlink/streamlink/issues/497 and closed it out, it's just too big to tackle right now.

**Comment by Tharn** [comment]
I'm honestly not sure. I just saw the 'matching plugin' line and assumed that it was supposed to.

Livestreams from beam.pro work by the way, using rmtp and with the best quality possible. Tested with 1080p.

**Comment by gravyboat** [comment]
@Tharn I'm thinking of the low latency streams. My bad.

**Comment by beardypig** [comment]
Previously VOD was not supported, it says so in the docs (https://streamlink.github.io/plugin_matrix.html).

**Comment by Tharn** [comment]
Damn you guys are fast. I appreciate it.
