### ISSUE TITLE
Retry Persistence

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#69]
Can we add an option that allows changing retry persistence? e.g --retry-persistance=10 or something along those lines.

**Comment by scottbernstein** [comment]
What exactly would retry persistance do?  There are already a TON of retry options available to livestreamer/streamlink:  --retry-streams, --retry-open, --stream-segment-attempts, --hls-segment-attempts, --hds-segment-attempts

________________________________

**Comment by TheSneakySniper** [comment]
Oh, i had no idea there was a --retry-open command..
