### ISSUE TITLE
vaughnlive error: Unable to validate response text: '' does not equal '<error></error>' or Minimum length is 3 but value is 1

### ISSUE THREAD

**Issue by mighty825** [streamlink/streamlink#690]
Using latest nightly and this plugin

https://github.com/streamlink/streamlink/pull/383/files/4f7d4f683ce61c0d10908d71603e8df40d744a27..0de2ede40755ee4b76fac8b2d9c8d3204f649b0a

Thank you

**Comment by mmetak** [comment]
https://github.com/streamlink/streamlink/pull/691

**Comment by beardypig** [comment]
Looks like it's time for me to submit a PR for the ultimate vaughnlive fix... 

_NB. May not be the ultimate fix, terms and conditions apply, consult your medical professional before using._

**Comment by gravyboat** [comment]
@beardypig So you're going to delete the vaughnlive plugin then?

**Comment by c769214** [comment]
#691 fixed the issue, can close this ticket
