### ISSUE TITLE
youtube-dl?

### ISSUE THREAD

**Issue by alphapapa** [streamlink/streamlink#7]
Since the project is being forked, this seems like a good opportunity to discuss how this project may relate to `youtube-dl`.  There is some duplicated functionality and purpose between the two projects, and `youtube-dl` is a vibrant project.  Would it make sense to consider porting the functionality exclusive to livestreamer/streamlink to `youtube-dl` instead of carrying this project forward as its own project?

**Comment by gravyboat** [comment]
So I looked at their issues and it seems like the CLI (unless I am missing something) is still somewhat complex for doing what streamlink does. I use this exclusively for streaming, not downloading (https://github.com/rg3/youtube-dl/issues/2124), and I like that it is exclusively used for this purpose. I looked at using `youtube-dl` originally but wasn't really happy with the implementation or ease of use to just stream content.

**Comment by alphapapa** [comment]
Hm, well, I'm watching a Twitch stream in VLC through youtube-dl right now.  All I did was run `youtube-dl -o - twitch.tv/streamer | vlc -`.

So, a few issues:

1.  It doesn't automatically launch a player when using STDOUT.  This would probably be easy to implement.

2.  It uses `ffmpeg` to remux (not reencode) the audio/video streams into one stream for the player.  On one hand, I guess this isn't optimal.  On the other, i) it works, ii) it lets `ffmpeg` handle downloading the audio and video streams, meaning one less thing the Python program has to do, and iii) it can be a useful ability.  Of course, it can also output the playlist URLs directly to the player, just like `livestreamer`, in which case a player like VLC can handle everything from that point.

3.  The `-o - ... | vlc -` part seems messy, although it's very straightforward.  So it seems like it should be relatively easy to enhance `youtube-dl`'s support for loading streams in external players, making it more user-friendly.

Benefits that would come with "switching" to `youtube-dl` would include:

* Being part of a vibrant project.  youtube-dl is used by far more people and is constantly updated by a variety of contributors.
* Supporting more sources.  As far as I know, youtube-dl already supports far more streaming sources than livestreamer.
* Easy distribution.  youtube-dl's `-U` option makes it easy to keep it up-to-date on both Unix and Windows systems.  `livestreamer` requires `pip` and, at least in my experience, the use of `virtualenv`, making it far more complex to use.

As far as I can tell, the only advantage that livestreamer has over youtube-dl is its ability to download streams and serve them through its own HTTP server to players, which seems to work very reliably.  But I'm not sure how this is useful or why it's necessary since the STDOUT/STDIN support also works fine.  In fact, youtube-dl could probably do something similar on supported streams, passing the data directly through a pipe instead of remuxing with ffmpeg.

Food for thought.  :)

**Comment by CowCowCowCow** [comment]
I've used ls since very early on in the project's life and I'm also an avid yt-dl user of many years (for downloads & streaming), one thing that people don't seem to mention when making comparisons is how they handle caching. Not only is ls superior in how it handles stream caches (greatly reducing drops as a result) but also in my experience yt-dl requires more overhead in terms of bandwidth and cpu than ls does. 

yt-dl isn't designed for streaming and that's what this project is about.

**Comment by alphapapa** [comment]
> Not only is ls superior in how it handles stream caches (greatly reducing drops as a result) but also in my experience yt-dl requires more overhead in terms of bandwidth and cpu than ls does.

Now that's a really good point.  Could you explain a bit more how livestreamer does it and how it reduces drops?  I spent a few minutes looking through the code the other day, and while I don't claim to have a good grasp of it, it might be relatively easy to add it to yt-dl.

**Comment by scottbernstein** [comment]
Livestreamer has a ton of options that we can configure in terms of stream retries, segment retries, timeouts, thread count, the *-live-edge options etc., all of which can help a TON with reducing dropouts....

________________________________

**Comment by WolfganP** [comment]
Most of the richness of these projects is in the plugins' area (the sauce that make different sites to work with the main agnostic tool).
Maybe there's a way to adapt youtube-dl sites' plugins to streamlink and help cross-polination and broad of supported sites?

**Comment by scottbernstein** [comment]
Livestreamer works GREAT with YouTube and other sites, so long as you tweak your command line parameters properly.

________________________________

**Comment by alphapapa** [comment]
> Livestreamer has a ton of options that we can configure in terms of stream retries, segment retries, timeouts, thread count, the *-live-edge options etc., all of which can help a TON with reducing dropouts....

youtube-dl also has many options, though I don't know if it has all of those.

I think there are two ways of looking at these projects:

1.  As some kind of all-in-one approach that can not only get the stream links from the web sites, but also download them and pass them through to players, etc.
2.  As simple tools to get the URL to the actual stream data and pass that to a player like VLC.

I think--hope, anyway--that as players like VLC improve, these projects can move more toward the second approach, delegating downloading and playing to VLC.  (VLC is also extremely configurable; just have a look at `vlc --full-help`).  It's a lot of work just keeping up with the streaming sites' churn, so letting VLC handle as much as possible seems like a good idea.

> Most of the richness of these projects is in the plugins' area (the sauce that make different sites to work with the main agnostic tool).

Yes, I think you're absolutely right about that.  That's the point I've been trying to make, but you made it more succinctly.  :)

> Maybe there's a way to adapt youtube-dl sites' plugins to streamlink and help cross-polination and broad of supported sites?

I'm not sure exactly what you mean.  If you mean to port plugins that only exist in livestreamer to youtube-dl, this could be done, but they would need to be rewritten in the process.  Of course, I think it would be worth it in the long-term, and that's the point I've been trying to make.  :)

If you mean to make some kind of bi-directional plugin API layer that translates between each project's plugins, that would not be practical.  The way the projects are written is wildly different.  youtube-dl is also a much, much larger, more complex project.

What I've been trying to do is show why it would be better for the long-term if the efforts put in here were simply moved to youtube-dl.  There is a huge community over there, and there's no risk of the authors disappearing or going idle like has happened with livestreamer.  There may be some features that only exist in livestreamer, but they could be added to youtube-dl.  

The projects are fundamentally similar in purpose--that one has historically focused on "downloading videos" while the other has focused on "streaming video" is an implementation detail that is already blurring, since youtube-dl has some support for Twitch and other streaming sites.  Already I can run something like `vlc $(youtube-dl -g twitch.tv/streamer)` and open streams directly in VLC, getting the URL with youtube-dl, and it handles Twitch VODs too.  And youtube-dl's distribution system makes it so easy to update to keep up with site churn...

As great as livestreamer has been, I struggle to see what its purpose and niche are in the long-term.  I'd just hate to see effort go to waste when it could be put into something that would have more value and longevity.

It would help if we could more clearly define why livestreamer needs to exist as compared to youtube-dl, and then we could talk about whether it makes sense to keep livestreamer going or port features to youtube-dl.

Of course, if y'all want to keep working on livestreamer, it's up to you.  :)

**Comment by flijloku** [comment]
@alphapapa It does youtube-dl as fast as the ls loader for hls? Aria2c does not support loading hls. Maybe there is another quick loader  hls for youtube-dl?

**Comment by alphapapa** [comment]
@flijloku I don't understand your question.  I've never used Aria2c.

**Comment by flijloku** [comment]
@alphapapa Which command do you use to fast download Twitch VOD  through yotube-dl and what is the maximum download speed? Through ffmpeg or native hls downloader in yd download speed (for me) is typically less than 1 MB / s. Maybe you know commands increase the speed? Like "-hls-segment-thread" command in ls?

**Comment by alphapapa** [comment]
I don't download Twitch VODs very often, but when I do, now that they are HLS-based, I just let `youtube-dl` use  `ffmpeg` to do it.  I guess a program could be written to download segments in parallel and then run `ffmpeg` on the resulting files.  Of course, that would either require downloading the entire VOD before processing, or would require downloading batches of segments and running `ffmpeg` on them repeatedly to produce larger files from the segments.

Do you mean that `livestreamer` downloads segments in parallel, like Aria2c does for non-HLS URLs?

**Comment by flijloku** [comment]
> Do you mean that livestreamer downloads segments in parallel, like Aria2c does for non-HLS URLs?
Yes. They can increase the rate of several times.

**Comment by scottbernstein** [comment]
Yes, Livestreamer downloads segments in parallel if you provide the right command-line arguments:

--hds-segment-threads

--hls-segment-threads

--stream-segment-threads

________________________________

**Comment by alphapapa** [comment]
Thanks, that's a good example of a feature that distinguishes livestreamer from youtube-dl.

**Comment by Junior1544** [comment]
I just want to say something here...  i don't use the youtube dl...  The reason I don't is that I don't use this for youtube at all...  I use it for livestream.com.  This is what was recommended to me to use (livestreamer really, but streamlink is the next step)...

Just my thoughts...

**Comment by tp0** [comment]
@Junior1544 youtube-dl may be the name, but it supports [a huge list of sites](https://rg3.github.io/youtube-dl/supportedsites.html) and much more than Livestreamer does.

**Comment by Junior1544** [comment]
@tp0 I'm sure, but with the name being youtube dl, i didn't know that before I started using livestreamer and am now here :)

Thanks!

**Comment by MrLint** [comment]
Just noting here that there seems to be several commercial variants of 'streamlink' Perhaps to avoid future headache something other name might want to be looked into.

**Comment by L2501** [comment]
ffmpeg is very bad at downloading HLS streams, it doesn't support http keep-alive and bitrate selection which make it unusable on anything other than a 100/100 fiber internet.

**Comment by alphapapa** [comment]
@L2501 You may be right about ffmpeg lacking some specific features, but I have found it to work quite well for downloading HLS streams in my limited experience, and my connection speed is not high.  It depends on the bitrate of the stream; if it's lower than the available bandwidth, it should work fine.  I don't think you'll find any 100mbps HLS streams on the Internet right now.  ;)

**Comment by nfdisco** [comment]
In my experience watching the entire Tour de France 2016 through online streaming, ffmpeg does not work well even with very low bitrate streams due to cache issues, whereas livestreamer had no problem. With livestreamer+mplayer you can pause the stream for several minutes, which is a technique I use to sync audio and video streams from different sources. I don't know any other software that allows that.

**Comment by alphapapa** [comment]
@nfdisco ffmpeg has a bewildering variety of options, so without knowing exactly how you were using ffmpeg in comparison to livestreamer+mplayer, it's hard to say whether ffmpeg is inferior.  

For example, did you have ffmpeg download the file to disk?  If so, did you have it copy or reencode the streams?  Did you have it rewrite the timestamps to fix sync issues?  Did you enable fragmentation to allow seeking before the download finished?  Did you rewrite the file afterward without fragmentation to allow faster seeking?  Or did you have ffmpeg pass-through the data to a player program?  (In which case the player might be the one at fault; even VLC has issues with seeking incomplete files, especially older versions that are still in common use.)

My point is that, you might be right, that ffmpeg is simply inferior at the moment.  But it might be that ffmpeg already has the capability to perform just as well with the right settings; after all, it's practically a swiss-army-knife of video (de|en)coding, (de)muxing, and even (down|up)loading.

And then there is the issue of avconv vs. ffmpeg, and their differing abilities and command-line arguments...

**Comment by nfdisco** [comment]
@alphapapa ffmpeg is great, I use it occasionally, but I'm in this case it didn't work for me as a backend for mplayer, while livestreamer did. Maybe some livestreamer code could be moved to ffmpeg, sure. The plugins, I think not, though. Then again I'm not an expert, so I may be wrong.

**Comment by nfdisco** [comment]
@MrLint it's a good point. Some ideas: streamgrabber, streamforwarder, streamdispatcher, streamhandler, streamtool.

**Comment by bastimeyer** [comment]
I have opened a new thread for this: #65 
Please discuss this over there

**Comment by gravyboat** [comment]
Going to close this for now since there hasn't been discussion in a while.
