### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by atulodra** [streamlink/streamlink#700]
When changing the location of the directory path of MPC-HC player in the streamlinkrc and running the command in the terminal, I always get this error message and the process closes. The directory path is correct.

`[cli][info] Starting player: mpc-hc
error: Failed to start player: mpc-hc ([WinError 2] The system cannot find the file specified)`
`[cli][info] Closing currently open stream...`

I am using a windows 8.1 x64 machine with a x64 version of MPC-HC.

**Comment by gravyboat** [comment]
What does your actual command look like?

**Comment by beardypig** [comment]
Did you put the full path to the `mpc-hc.exe` file?

**Comment by atulodra** [comment]
The command looks like this:
`streamlink <link> --player=mpc-hc`
Is the command wrong?

And yeah I added the full path to the `mpc-hc.exe` (actually `mpc-hc64.exe`)
It runs with MPC-HC if I add the pull path:
`--player="path/mpc-hc64.exe"`

**Comment by atulodra** [comment]
The command looks like this:
`streamlink <link> --player=mpc-hc`
Is the command wrong?

And yeah I added the full path to the `mpc-hc.exe` (actually `mpc-hc64.exe`)
It runs with MPC-HC if I add the pull path in the command:
`--player="path\mpc-hc64.exe"`

**Comment by bastimeyer** [comment]
> Is the command wrong?

Yes, unless "mpc-hc" can be resolved by using your system's `PATH` environment variable (see [here](https://en.wikipedia.org/wiki/PATH_(variable)) or [here](https://superuser.com/a/284351)).

**Comment by beardypig** [comment]
@atulodra did you solve this by setting the full path to `mpc-hc` in your `streamlinkrc` file?

**Comment by bastimeyer** [comment]
Going to close the thread. Please take a look at Streamlink's CLI documentation. There are enough player examples for this question to be answered.
