### ISSUE TITLE
Plugin request: https://live.fc2.com

### ISSUE THREAD

**Issue by theredmanor** [streamlink/streamlink#701]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Ability to grab livestreams from https://live.fc2.com

**Comment by brachna** [comment]
They had maintenance yesterday and new changes broke my script, damn. They still use Flash, no HLS.
They also use WebSocket now and I don't see any call to play() in WireShark captures, however there is a call to connect() still.
Any ideas?

**Comment by panhartstuff** [comment]
Any hope for this feature?

**Comment by johnthecracker** [comment]
@brachna, how did you figure it out?

Why not post solution here? Looks a bit selfish from your side.

You ask for solution on international forum, and when you find it don't post for others to see.

jadran1@mail.com

**Comment by back-to** [comment]
will probably not be added.
