### ISSUE TITLE
Never feel bad about taking time for yourself

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#703]
Hello everyone,

This is primarily for maintainers but I wanted to make sure everyone was aware of this: https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/

If for any reason you are feeling this way working on this project no one will blame you for taking a break, working on something else, or stepping back/working less. This is a big project with a lot of requests and issues and I want to make sure people don't get burned out. All the work by contributors, bug reporters, and maintainers is appreciated, but your mental health and general well being are more important than any project. 

This is probably not the right place to put this, but this is the easiest way to get the attention of everyone who regularly contributes. NEVER let this project negatively impact you, if it is I am behind you 100% doing what you need to do to maintain your own well being. Open source is tough, and taking care of yourself is the most critical aspect of any project.

**Comment by beardypig** [comment]
FYI, I'm going on vacation until 1st April and I've had flu this last week. Expect reduced interactions from me until then 🌞

**Comment by gravyboat** [comment]
Sounds good, have a great trip @beardypig!

**Comment by karlo2105** [comment]
@beardypig 
I wish you to get cured as soon as possible and to enjoy your holidays. ;)
