### ISSUE TITLE
Need help with a stream and command line

### ISSUE THREAD

**Issue by mikhoul** [streamlink/streamlink#705]
Hi, 

I use Streamlink mainly to record stream from TV station and I have a problem finding the "right" command line to record  a program.

Here's my command line I use:

`streamlink --http-header "X-Forwarded-For=207.179.146.70" "hls://http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729" worst -f -o "H:\Telechargement\TVA_TopModeles_%date%_%time:~0,2%.%time:~3,2%.%time:~6,2%.ts"`

Here's the result I have from the console windows: 

```
[cli][info] Found matching plugin stream for URL hls://http
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][error] Could not open stream: Missing #EXTM3U header
```

I know for sure **the stream is fine** because when I use a program/script that use livestreamer it work fine and record the stream. I used to  build my "command line" the "template" the program use to call livestreamer:

Here's the template where it work, the only difference seem to be the "variables":

`<comeflux3>livestreamer\livestreamer.exe --http-header "X-Forwarded-For=207.179.146.70" "hlsvariant://[URL]" best -o "[CHEMIN]"</comeflux3>`

I even tried with the "old" livestreamer in to test my command line and I receive the same error (_Missing #EXTM3U header_) so it's not a regression with streamlink.

At this point I'm pretty sure it's an error in my command line that I can't figure, so I need help from a more advanced user to help me to build a command line that work.  :smiley: 

Best Regards !  :octocat:

**Comment by beardypig** [comment]
The URL that you posted for the stream (`http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729`) doesn't actually link to the stream. It returns another URL which is the actual stream. If you request the URL you posted in your browser and use the URL displayed then for the stream, it should work. 

Eg. Loading `http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729`
Returns `http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8?hdnea=st=1489531791~exp=1489531881~acl=/i/tvago_1@410563/*~hmac=0f1064b1cd77723b43218635d4b43a088286dc3322a6cd0ac76382093de4d5f9`

And if you use that in your original command line (except `hlsvariant` instead of `hls`) it should work. Note that the URL returned may expire quite quickly, so you'd have to be quick about it. 

Alternatively, someone could try to make a plugin for `racacaxtv.ga`.

**Comment by mikhoul** [comment]
@beardypig  Thanks for the quick reply !


First what is the difference between HLS and HLSVARIANT ?  I did not found any difference in the [doc](https://streamlink.github.io/cli.html#supported-streaming-protocols)

I already tried with HLSVARIANT since the "template" was using it but sadly it returned the same error.

I know about not being the direct URL  it's because it need a token so `http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729`  it return the real URL with the token (which is only valid for ~30-60 seconds but it's enough to start a script of even test it with VLC).

I've even looked in the `livestreamerrc`  file to see if there was an "hidden" plugin but there is nothing.


What amaze me is that when I use the **AllFRTV**  that is mainly an interface interface for for "livestreamer" Livestreamer record fine.

I was under and I'm always under the impression that Streamlink/Livestreamer was able to handle `http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729` URL directly without plugin. 

Let me show it to you via a **Screencast** maybe you will understand better since english is not my first language: http://screencast-o-matic.com/watch/cbe20L6AOX

Here's a link for AllFrTV if you want to take a look: https://drive.google.com/file/d/0B6RFGgEO3_mHS0FxdnNmSFB3QXc/view No need to install it, it's portable. If you test it jUSE TVA for the channel to Record (Enregistrer) and in the drop down menu on the main interface use the third option "3. Haute Qualité [CFTM]"  

The template file used by the program to start Livestreamer is located in the **\AllTVFr\pls\** folder under the name of "**Francophones.xml**" .

**I'm not a programmer** but I,m a curious guy so just to know the process/use of the plugins: If a plugin was needed would it make more sense to make the plugin directly for http://chaine_tva_uls-lh.akamaihd.net/i/tvago_1@410563/master.m3u8 and the plugin would scrap itself the token and insert it in the URL or having a server like "Racaca" that "generate a token so make a plugin for the Racaca server ?  

_Best Regards and thanks again for the help and sharing your knowledge_  :octocat:

**Comment by beardypig** [comment]
The difference between `hls` and `hlsvariant` is subtle, it's more for plugin authors or power users to know the difference. Personally, I'd like to remove the difference for the end-user so they don't have to know what it means. The `hlsvariant` type is where the stream describes a list of different qualities (variants) for the same stream, which is how HLS works in general. A `hls` is used for when the stream is a direct link to one of those variants. 

It looks like `AllFrTV` is more than just a launcher for `livestreamer`, it does do some work to find the streams then uses `livestreamer` to play them.

**Comment by mikhoul** [comment]
> It looks like AllFrTV is more than just a launcher for livestreamer, it does do some work to find the streams then uses livestreamer to play them.

So could you make a simple plugin  @beardypig to be able to save/play the stream ?


Regards !  :octocat:

**Comment by mikhoul** [comment]
@beardypig 

I found a way to do it without "plugin" by scripting with WGET so I leave it here in case someone have the same kind of problem to resolve in the future:

**Here's the batch file to do it:**

```
wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt


set url=
for /F "delims=" %%i in (tva.txt) do set url=%%i

del tva.txt

streamlink.exe "hlsvariant://%url%" 360p -f -o "H:\Telechargement\TVA_TopModeles_%date:~-4,4%-%date:~-7,2%-%date:~-10,2%_%time:~0,2%.%time:~3,2%.%time:~6,2%.ts"
```

Regards :octocat:

**Comment by gravyboat** [comment]
@mikhoul Thanks for posting that batch file! I'm going to close this out for now since I think we're all set to go.

**Comment by Bjorp** [comment]
> @beardypig
> 
> I found a way to do it without "plugin" by scripting with WGET so I leave it here in case someone have the same kind of problem to resolve in the future:
> 
> **Here's the batch file to do it:**
> 
> ```
> wget -q http://racacaxtv.ga/tva.php?token=ece27dec6af929f4aa52f2347056434d7de0f729 -O  tva.txt
> 
> 
> set url=
> for /F "delims=" %%i in (tva.txt) do set url=%%i
> 
> del tva.txt
> 
> streamlink.exe "hlsvariant://%url%" 360p -f -o "H:\Telechargement\TVA_TopModeles_%date:~-4,4%-%date:~-7,2%-%date:~-10,2%_%time:~0,2%.%time:~3,2%.%time:~6,2%.ts"
> ```
> 
> Regards :octocat:

@mikhoul I also have issue.. can you provide your email where we can discuss?
