### ISSUE TITLE
Stream frozen all the time with Youtube Live, frozen image, no audio

### ISSUE THREAD

**Issue by Akandesh** [streamlink/streamlink#708]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

When I watch a youtube livestream and try to use streamlink then it opens it in VLC like normal but it's just a frozen image with no audio.

### Expected / Actual behavior

Livestream plays with audio and image.

### Reproduction steps / Stream URLs to test

1. Right now this one: https://www.youtube.com/watch?v=rkpiOya8vKk

### Environment details (operating system, python version, etc.)

Windows 10, not using python.

### Comments, logs, screenshots, etc.

Could this be a problem with some VLC setting? All twitch streams work with no problem.

**Comment by johnthecracker** [comment]
I can play this with streamlink and VLC 3:

http://nightlies.videolan.org/


C:\>streamlink https://www.youtube.com/watch?v=rkpiOya8vKk worst
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=rkpiOya8vKk
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 144p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe





youtube-dl, if you want as well...


see all streams:


C:\>youtube-dl.exe -v -F --no-check-certificate https://www.youtube.com/watch?v=rkpiOya8vKk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', '--no-check-certificate', 'https://www.youtube.com/watch?v=rkpiOya8vKk']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.03.15
[debug] Python version 3.4.4 - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 3.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] rkpiOya8vKk: Downloading webpage
[youtube] rkpiOya8vKk: Downloading video info webpage
[youtube] rkpiOya8vKk: Extracting video information
[youtube] rkpiOya8vKk: Downloading formats manifest
[youtube] rkpiOya8vKk: Downloading MPD manifest
[info] Available formats for rkpiOya8vKk:
format code  extension  resolution note
91           mp4        144p       HLS , h264, aac  @ 48k
92           mp4        240p       HLS , h264, aac  @ 48k
93           mp4        360p       HLS , h264, aac  @128k
94           mp4        480p       HLS , h264, aac  @128k
95           mp4        720p       HLS , h264, aac  @256k
96           mp4        1080p      HLS , h264, aac  @256k (best)




play 480p, for example:


C:\>youtube-dl.exe --no-check-certificate -f 94 "https://www.youtube.com/watch?v=rkpiOya8vKk" -o - | vlc.exe -
[youtube] rkpiOya8vKk: Downloading webpage
[youtube] rkpiOya8vKk: Downloading video info webpage
[youtube] rkpiOya8vKk: Extracting video information
[youtube] rkpiOya8vKk: Downloading formats manifest
[youtube] rkpiOya8vKk: Downloading MPD manifest
[download] Destination: -
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-
avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libb
luray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-l
ibmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libope
njpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enabl
e-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable
-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zli
b
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'https://manifest.googlevideo.com/api/manifest/hls_playlist/id/rkpiOya8vKk.0/itag/94/sourc
e/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dy
es%3Bitag%3D135/hls_chunk_host/r7---sn-cu-auoz.googlevideo.com/gcr/gb/playlist_type/DVR/mm/32/mn/sn-cu-auoz/ms/lv/mv/m/p
l/25/dover/6/upn/TE1xR9nAdhk/mt/1489611728/ip/86.176.228.139/ipbits/0/expire/1489633469/sparams/ip,ipbits,expire,id,itag
,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,gcr,playlist_type,mm,mn,ms,mv,pl/signature/55
7994FA62CEF6ACF0293C3A9A998E5FF4080B2C.080CA8E20B9A8A6F7A9A1B9619F3FB926AE6F901/key/dg_yt0/playlist/index.m3u8':
  Duration: N/A, start: 11745.016000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 854x480 [SAR 1:1 DAR 427:240], 30 fps,
 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
Output #0, mpegts, to 'pipe:':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 854x480 [SAR 1:1 DAR 427:240], q=2-31,
 30 fps, 30 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  900 fps= 50 q=-1.0 size=    2810kB time=00:00:30.00 bitrate= 767.1kbits/s speed=1.68x

**Comment by johnthecracker** [comment]
Or, you can play that with VLC 3 only.

Works for me.

**Comment by Akandesh** [comment]
What is VLC 3? 

https://i.gyazo.com/313e73046be1c1c1e341b9639910ba3a.mp4 

This is all I get, you can see the youtube in the background moving but not through VLC.

**Comment by Akandesh** [comment]
I installed the nightlies build instead and now it works, interesting. Maybe it was a bug with VLC or an old setting that messed it up?

**Comment by johnthecracker** [comment]
Your problem is not related to streamlink.

I can play the stream with streamlink which uses player I have installed, VLC 3,
and I can play the stream with youtube-dl and VLC, or with player only.

Please learn your homework before asking me what is VLC 3:

https://en.wikipedia.org/wiki/VLC_media_player

**Comment by johnthecracker** [comment]
http://nightlies.videolan.org/build/win32/

vlc-3.0.0-20170315-0250    15-Mar-2017 06:05

**Comment by Akandesh** [comment]
Ah I see now, haven't had reason to follow the development of VLC. Thanks.
