### ISSUE TITLE
Inconsistent configuration file location on portable version

### ISSUE THREAD

**Issue by karlsson3** [streamlink/streamlink#716]
### Checklist

- [] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Not really a feature request but the configuration for the portable version is kinda inconsistent.
I put the portable installation here C:/streamlink/
And the default configuration file is in there aswell: C:/streamlink/streamlinkrc
But when I want to specify settings for each plugin I have to put the streamlinkrc.twitch in %AppData%/streamlink/streamlinkrc.twitch otherwise it won't work.
The regular streamlinkrc configuration file won't work if it is with the rest of the plugin specific files in %AppData%/streamlink/

For the portable version the plugin specific configuration files should be at the same place the streamlinkrc is.

And maybe you should add the information about the portable version here aswell: https://streamlink.github.io/cli.html#configuration-file
Took me some time to figure out why streamlink ignored my configuration in %appData%

### Environment details (operating system, python version, etc.)
Windows 10, portable up to date streamlink version

**Comment by gravyboat** [comment]
Are you talking about this portable version: https://github.com/streamlink/streamlink-portable ? If so could you please open the issue over there so it gets the proper eyes on it?

**Comment by karlsson3** [comment]
Oh looks like you are right, I didn't notice they were different projects. I am going to submit this issue over there!

**Comment by gravyboat** [comment]
No worries @karlsson3! We just try to keep it split so it's easier to manage. Thanks!
