### ISSUE TITLE
LookupError: Invalid language code: en_150

### ISSUE THREAD

**Issue by Ackmard** [streamlink/streamlink#718]
Can anyone help me with that? Just installed it and i can't figure what's wrong.

![livestream error 2](https://cloud.githubusercontent.com/assets/26508542/24074514/fc6a051e-0c12-11e7-8398-e5e7b8e12f9d.jpg)

**Comment by beardypig** [comment]
I'll have to take a closer look as to why that is happening. You are work around it by doing 
```shell
streamlink --locale en_US twitch.tv/quill18
```
That will set your locale to US English. If you don't mind me asking, what language (English by the looks of it) and Country/Region do you have set up in Windows?

**Comment by Ackmard** [comment]
Country/Region is United States, i'm using 2 input languages US English and Greek.

**Comment by beardypig** [comment]
This should be fixed in the latest night version (as #725 was merged).
