### ISSUE TITLE
Feature request: Add support for refererLocked ustreams

### ISSUE THREAD

**Issue by Mattwmaster58** [streamlink/streamlink#719]
### Checklist

- [x] This is a feature request.
- [x] This is a plugin request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

There are some ustream's that do not work unless you provide them with a refferal URL. In firefox, you can just install the extension "RefControl", and it works great....only problem being that this program isn't firefox.

I've found no way to provide a refferal URL, and I doubt one exists. It would be beneficial if this program could provide refferal urls

### Reproduction steps / Stream URLs to test

Try to download https://www.ustream.tv/embed/22802513 (or just go to the site. It will give you an error. Unless you have RefControl installed and properly ) 

### Comments, logs, screenshots, etc.

```
C:\Users\Somebody>streamlink https://www.ustream.tv/embed/22802513
[cli][info] Found matching plugin ustreamtv for URL https://www.ustream.tv/embed/22802513
[plugin.ustreamtv][warning] python-librtmp is not installed, but is needed to access the desktop streams
error: No playable streams found on this URL: https://www.ustream.tv/embed/22802513
```

PS Why can't I open the plugins in Npp? It shows a bunch of gibberish in between text.

**Comment by karlsson3** [comment]
You can set http header fields manually:
https://streamlink.github.io/cli.html#cmdoption-http-header

And you are probably looking at compiled files so you text editor can't display the actual source code

**Comment by Mattwmaster58** [comment]
Could you go into a little more detail on how to add a referral URL? I tried `--http-header referer=http://www.sportscanada.tv/` and got the same error.

**Comment by tp0** [comment]
Are the headers supposed to work with site-specific plugins at all?

**Comment by beardypig** [comment]
@tp0 generally it should work - unless the plugin overwrites the header you set, or removes all the headers, or doesn't use the standard `HTTPSession` to make the request.

**Comment by beardypig** [comment]
@Mattwmaster58 It looks like this is a `ustream` API specific thing so it won't work with the `--http-header` option. Embedded streams can be `referrerLocked`, meaning they'll only work when embedded in the correct site (without browser trickery, which you already worked out). The referrer URL has to be sent in the ustream API request, unfortunately setting the Referer header won't do that in the plugin - I couldn't get it to work in the browser either... 

I've been working on a new [UStream plugin](https://raw.githubusercontent.com/beardypig/streamlink/c3b57a2f6c9086fe27ebd9faff7cd285e080cf06/src/streamlink/plugins/ustreamtv.py) which should support those `referrerLocked` streams.

**Comment by Mattwmaster58** [comment]
@beardypig I don't think that this stream is `referrerLocked` because the refcontrol addon for firefox fixes that and I am pretty sure that it just modifies the request headers. Am I using the right syntax for a http header?

**Comment by beardypig** [comment]
They are definitely `referrerLocked`, the ustream api says as much. Perhaps RefControl also intercepts JavaScript requests for the referrer? 

That line for the referrer option is no longer used, I was testing that before but I found a way to do it automatically (I will remove the line before creating a PR). It should work with no extra options.

**Comment by Mattwmaster58** [comment]
@beardypig  Ok that make sense. So is this plugin working right now? If not is there any alternative routes I could take?

**Comment by bastimeyer** [comment]
> --http-header "Referer": http://www.sportscanada.tv/

In case you still want to try using the http header, you need to set the parameter this way:
`--http-header "Referer: http://www.sportscanada.tv/"`

**Comment by Mattwmaster58** [comment]
@bastimeyer  I get this when I try that : `--http-header: invalid keyvalue value: 'Referer: http://www.sportscanada.tv/'`.

**Comment by Mattwmaster58** [comment]
@beardypig I also found this on the page w/ embedded video:

`blob:https://www.ustream.tv/eb2316ab-61b2-403e-a06f-89f505107931`

and in the network tab:

`https://vod-cdn.ustream.tv/sjc/omega/vod/p2-7d1acfa0-592f-4acf-bf8b-ca1b74ac0de2/0/71496499008000/plain/improved/1/[chunk-name-here].m4a/m4v`

Is there anything I can do with those URLs?

**Comment by bastimeyer** [comment]
The correct format is `--http-header "key=value"`.
I was not thinking and had just moved the quotation marks, because the line you have posted gets tokenized differently.

**Comment by beardypig** [comment]
@Mattwmaster58 what issues did you experience with the plugin?

**Comment by Mattwmaster58** [comment]
@beardypig  It **seemed** like it was inconsistent (ie couldn't find playable stream). I would try the URL in quotes, then not in quotes, then in quotes and then it would seem to work. This wasn't the only thing I changed, so I'm wondering if it was maybe just me not being able to type.

**Comment by gravyboat** [comment]
Closing this since #754 was merged.
