### ISSUE TITLE
Build a package and get it upstreamed into Debian

### ISSUE THREAD

**Issue by gravyboat** [streamlink/streamlink#72]
Currently livestreamer is available as a package which can be easily installed on Debian/Ubuntu, this is not the case for streamlink. If we want to get this packaged up and ready for the next release we need to move quickly. as @javiercantero mentions [here]https://github.com/chrippa/livestreamer/issues/1427#issuecomment-249653892) they'll be freezing the the release in the beginning of January. While I'm familiar with building RPMs and am okay at building debs I'm not very familiar with building debs that go into the upstream repo. If we have anyone who is an expert working on the project I would love to get your help with this. I don't think we'll be able to get this sort of coverage (http://docs.livestreamer.io/install.html#linux-and-bsd-packages), but having it be available for at least Debian and Ubuntu would be nice.

There is some existing stuff related to the builds that chrippa put in place (https://packages.debian.org/sid/video/livestreamer), but I think we'll have to do some clean up to get everything prepared.

 Is this something that we want to do? Or should we wait on a package till we've rebuilt the CLI, then hope we can get it in at a later date?

**Comment by javiercantero** [comment]
Maybe it's more straightforward to open a RFP (Request for Package) first and see if any Debian maintainer is willing to do the packaging for you. Ubuntu also [recommends to talk to a Debian maintainer teams](https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages) in order to accelerate the process (the relevant one here would be [Python Applications Packaging Team](https://wiki.debian.org/Teams/PythonAppsPackagingTeam))

**Comment by amurzeau** [comment]
Hi,

I managed to get an updated Debian package working in Debian without additional dependencies to package (but that's my first real Debian package).
I used a separate Debian repository with its very own history as it seemed easier to handle (for example, the released source is not just a git archive of the tag).

The source package is at https://github.com/amurzeau/streamlink-debian and based on @breunigs work in #80. Changes I have made are available here: https://github.com/amurzeau/streamlink-debian/compare/95712f7d71417079fde126fc210352f9c259f475...master

Some indications :
* I choose to only make python3 packages as some of the python-backport dependencies are not available at all in Debian (like `backports.shutil_which`)
* I removed copyright information about non existing file `src/streamlink/packages/pbs.py` and added one for `src/streamlink/packages/requests_file.py` and some specific files in the sphinx rtd theme
* I updated quilt patches to the 0.5.0 streamlink version and changed a bit the patches headers so gbp pq keep them
* I changed the `debian/rules` file to enable usage of `pycountry` and `pycrypto` as these libs are the only alternative available currently in debian (`iso3166` and `pycryptodome` are not available)
* I added a patch to `src/streamlink/utils/l10n.py` so older pycountry that does not have the `lookup` method works too (the python3-pycountry package in Debian doesn't have this method)
* I added a `.travis.yml` file so travis build and test packages using sbuild
* I disabled compression on font files so the font-awesome icons works when browsing the locally installed doc in the `python3-streamlink-doc` package

@breunigs or others, let me know if I got something wrong in my changes but everything should be Ok :)

Additionally, I've put binary and source packages in a github repo using gh-pages so it can be used like a normal apt repository: https://github.com/amurzeau/streamlink-apt-repo.
These binary package are generated with sbuild. deb files are the same exact file as the one built by travis as the build is reproducible.

I've found bintray to be a possible alternative, but it requires to give it a private GPG key to have a secure APT repo (bintray itself manages the automatic signature of Release file and maybe other).

**Comment by javiercantero** [comment]
> I choose to only make python3 packages ...

@amurzeau As you should. The current [Debian Python Policy](https://www.debian.org/doc/packaging-manuals/python-policy/) says in [chapter 1](https://www.debian.org/doc/packaging-manuals/python-policy/ch-python3.html):

> Packages in Debian should use Python 3 if Python 3 is supported. New packages should use Python 3 from the initial upload, new upstream versions for existing packages should use Python 3 if the new upstream version supports it.

And:

> Programs should use Python 3, and should not be packaged for Python 2 as well.

**Comment by gravyboat** [comment]
Closing this out since it's resolved.

**Comment by javiercantero** [comment]
@gravyboat How is this solved? There is not official Debian package yet. Or I am missing something?

**Comment by gravyboat** [comment]
@javiercantero You're right I thought I read Debian last night but I didn't. Opened back up.

**Comment by javiercantero** [comment]
Now that livestreamer is going [to be removed from Debian testing](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877485), is anyone working on this?

**Comment by gravyboat** [comment]
@javiercantero Not as far as I know.

**Comment by amurzeau** [comment]
As I have done an unofficial package I can share it to Debian as an official one.

The package source is here: https://github.com/amurzeau/streamlink-debian, if you want to do any check.

Some notes before going on:
- In debian/copyright, upstream contact is  `Forrest Alvarez <forrest.alvarez+streamlinkdebian@gmail.com>`, is this still true ?
- I propose a package description based on README.md and the github repo title:
```
CLI for extracting video streams from various websites to a video player
 Streamlink is a CLI utility that pipes flash videos from online streaming
 services to a variety of video players such as VLC, or alternatively, a
 browser.
 The main purpose of streamlink is to convert CPU-heavy flash plugins to a
 less CPU-intensive format.
 .
 Streamlink is a fork of the Livestreamer project.
 .
 Please note that by using this application you're bypassing ads run by sites
 such as Twitch.tv. Please consider donating or paying for subscription
 services when they are available for the content you consume and enjoy.
```
I added `video` before `streams` to the title to precise what type of streams is handled by streamlink.

And these titles for the python library package: `Python module for extracting video streams from various websites`
And documentation package: `streamlink CLI and Python API documentation files`

Plus a line in the extended description for the difference between the Python library and documentation binary packages.

**Comment by gravyboat** [comment]
@amurzeau I'd really rather not be the contact for the package. I already get too many emails for Streamlink (some of which are extremely rude), and would rather not get more. I agreed originally because someone had to accept the responsibility but don't want that going forward.

**Comment by bastimeyer** [comment]
@amurzeau 

> I propose a package description based on README.md and the github repo title

You're using a description of an old version of the README.md.

> 58 commits

Why didn't you fork the repo? Would be easier to merge changes back here...

@gravyboat 
Do you get support questions from users via email or are these emails from streaming services? That doesn't sound good. 😦

**Comment by gravyboat** [comment]
@bastimeyer It's just users who have questions or people who want to hire me to do shady stuff (though that is super rare). It doesn't happen often, but it's pretty lame when it does.

**Comment by amurzeau** [comment]
@bastimeyer
> You're using a description of an old version of the README.md.

The proposed description is from https://github.com/streamlink/streamlink/blob/master/README.md#streamlink
The current one is unmodified from https://github.com/streamlink/streamlink/blob/master/debian/control

> Why didn't you fork the repo? Would be easier to merge changes back here...

I find easier to handle the Debian packaging outside, with git-buildpackage and the streamlink release tarball as the original source (this is also what @breunigs was doing with livestreamer).
So I think its better to keep upstream and Debian packaging kept separated.

Maybe it's possible to have everything at the same place but I think there will be conflicts as dpkg-source will expect files outside of /debian to be the same as the ones in the original tarball.

**Comment by amurzeau** [comment]
@gravyboat 
Upstream-Contact can be an URI instead, so the github issue page URL is the best I think.

I you're ok with this and description changes using up to date README.md, I can start an intent to package streamlink on Debian side.

**Comment by gravyboat** [comment]
@amurzeau That works for me, @bastimeyer are you good with this?

**Comment by bastimeyer** [comment]
Sounds good.

**Comment by amurzeau** [comment]
Debian associated bugs: 
ITP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878029
RFS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878268

**Comment by javiercantero** [comment]
Thanks @amurzeau

**Comment by gravyboat** [comment]
Thanks @amurzeau and Paul Wise!

**Comment by lillet23** [comment]
Great news!!! Thanks for the hard work!!!
