### ISSUE TITLE
Crunchyroll new video format is getting corrupted by streamlink when streaming or outputting to file

### ISSUE THREAD

**Issue by mlindner** [streamlink/streamlink#720]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Reproduction steps / Stream URLs to test

Any Crunchyroll video less than 24 hours old.

Follow the instructions in the title to produce corrupted output.

**Comment by gravyboat** [comment]
What about videos between the 24-48 hour window? There have been some major concerns over video streaming quality lately at Crunchyroll and I thought they just backed out their bitrate downgrade (they said they had new infra but that has been in place for a year). Can you paste in the output when you run your command with the addition of `-l debug` so we can see the debug output?

**Comment by mlindner** [comment]
Your information is slightly out of date. The infrastructure bug has been fixed and they're now producing videos even higher quality than they were (each episode is around 800mb instead of the normal quality ~500mb or the lower quality ~250mb). The problems appeared with the new 800mb stream and they also switched up their CDN. It's quite different now.

**Comment by mlindner** [comment]
The debug output is below but it doesn't show any problems. The problem occurs when the video is attempted to be played.

Genshiken:~ mlindner$ streamlink http://www.crunchyroll.com/saga-of-tanya-the-evil/episode-10-the-path-to-victory-727479 -l debug -o foo.mkv
[cli][info] Found matching plugin crunchyroll for URL http://www.crunchyroll.com/saga-of-tanya-the-evil/episode-10-the-path-to-victory-727479
[plugin.crunchyroll][debug] Creating session with locale: en_US
[plugin.crunchyroll][debug] Session created
[plugin.crunchyroll][debug] Using saved credentials
[plugin.crunchyroll][debug] Loading streams from adaptive playlist
[cli][info] Available streams: 360p_alt, 360p_alt2, 240p_alt, 240p_alt2, 480p_alt, 480p_alt2, 720p_alt, 720p_alt2, 1080p_alt, 1080p_alt2, 240p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Adding segment 13 to queue
[stream.hls][debug] Adding segment 14 to queue
[stream.hls][debug] Adding segment 15 to queue
[stream.hls][debug] Adding segment 16 to queue
[stream.hls][debug] Adding segment 17 to queue
[stream.hls][debug] Adding segment 18 to queue
[stream.hls][debug] Adding segment 19 to queue
[stream.hls][debug] Adding segment 20 to queue
[stream.hls][debug] Adding segment 21 to queue
[stream.hls][debug] Adding segment 22 to queue
[cli][debug] Checking file output
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Adding segment 23 to queue
[stream.hls][debug] Download of segment 2 complete
[stream.hls][debug] Adding segment 24 to queue
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Adding segment 25 to queue
[download][foo.mkv] Written 14.1 MB (0s @ 14.2 MB/s)                            [stream.hls][debug] Download of segment 4 complete
[stream.hls][debug] Adding segment 26 to queue
[stream.hls][debug] Download of segment 5 complete
[stream.hls][debug] Adding segment 27 to queue
[download][foo.mkv] Written 23.5 MB (1s @ 13.0 MB/s)                            [stream.hls][debug] Download of segment 6 complete
[stream.hls][debug] Adding segment 28 to queue
[stream.hls][debug] Download of segment 7 complete
[stream.hls][debug] Adding segment 29 to queue
[download][foo.mkv] Written 32.6 MB (2s @ 12.4 MB/s)                            [stream.hls][debug] Download of segment 8 complete
[stream.hls][debug] Adding segment 30 to queue
[download][foo.mkv] Written 38.2 MB (3s @ 11.6 MB/s)                            [stream.hls][debug] Download of segment 9 complete
[stream.hls][debug] Adding segment 31 to queue
[download][foo.mkv] Written 45.8 MB (4s @ 10.8 MB/s)                            [stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Adding segment 32 to queue
[download][foo.mkv] Written 56.0 MB (5s @ 10.4 MB/s)                            [stream.hls][debug] Download of segment 11 complete
[stream.hls][debug] Adding segment 33 to queue
[download][foo.mkv] Written 64.8 MB (5s @ 10.6 MB/s)                            [stream.hls][debug] Download of segment 12 complete
[stream.hls][debug] Adding segment 34 to queue
[download][foo.mkv] Written 74.9 MB (6s @ 11.0 MB/s)                            [stream.hls][debug] Download of segment 13 complete
[stream.hls][debug] Adding segment 35 to queue
[download][foo.mkv] Written 84.1 MB (7s @ 11.0 MB/s)                            [stream.hls][debug] Download of segment 14 complete
[stream.hls][debug] Adding segment 36 to queue
[download][foo.mkv] Written 95.1 MB (8s @ 12.1 MB/s)                            [stream.hls][debug] Download of segment 15 complete
[stream.hls][debug] Adding segment 37 to queue
[download][foo.mkv] Written 104.2 MB (8s @ 12.5 MB/s)                           [stream.hls][debug] Download of segment 16 complete
[stream.hls][debug] Adding segment 38 to queue
[download][foo.mkv] Written 114.1 MB (9s @ 11.8 MB/s)                           [stream.hls][debug] Download of segment 17 complete
[stream.hls][debug] Adding segment 39 to queue
[download][foo.mkv] Written 125.0 MB (10s @ 12.2 MB/s)                          [stream.hls][debug] Download of segment 18 complete
[stream.hls][debug] Adding segment 40 to queue
[download][foo.mkv] Written 132.2 MB (11s @ 12.2 MB/s)                          [stream.hls][debug] Download of segment 19 complete
[stream.hls][debug] Adding segment 41 to queue
[stream.hls][debug] Download of segment 20 complete
[stream.hls][debug] Adding segment 42 to queue
[download][foo.mkv] Written 143.2 MB (12s @ 10.8 MB/s)                          [stream.hls][debug] Download of segment 21 complete
[stream.hls][debug] Adding segment 43 to queue
[download][foo.mkv] Written 149.2 MB (13s @ 9.8 MB/s)                           [stream.hls][debug] Download of segment 22 complete
[stream.hls][debug] Adding segment 44 to queue
[download][foo.mkv] Written 152.1 MB (14s @ 8.4 MB/s)                           [stream.hls][debug] Download of segment 23 complete
[stream.hls][debug] Adding segment 45 to queue
[stream.hls][debug] Download of segment 24 complete
[stream.hls][debug] Adding segment 46 to queue
[download][foo.mkv] Written 162.6 MB (16s @ 6.6 MB/s)                           [stream.hls][debug] Download of segment 25 complete
[stream.hls][debug] Adding segment 47 to queue
[stream.hls][debug] Download of segment 26 complete
[stream.hls][debug] Adding segment 48 to queue
[download][foo.mkv] Written 175.0 MB (17s @ 7.5 MB/s)                           [stream.hls][debug] Download of segment 27 complete
[stream.hls][debug] Adding segment 49 to queue
[stream.hls][debug] Download of segment 28 complete
[stream.hls][debug] Adding segment 50 to queue
[download][foo.mkv] Written 185.6 MB (18s @ 7.9 MB/s)                           [stream.hls][debug] Download of segment 29 complete
[stream.hls][debug] Adding segment 51 to queue
[download][foo.mkv] Written 191.6 MB (18s @ 8.2 MB/s)                           [stream.hls][debug] Download of segment 30 complete
[stream.hls][debug] Adding segment 52 to queue
[stream.hls][debug] Download of segment 31 complete
[stream.hls][debug] Adding segment 53 to queue
[download][foo.mkv] Written 201.2 MB (19s @ 9.8 MB/s)                           [stream.hls][debug] Download of segment 32 complete
[stream.hls][debug] Adding segment 54 to queue
[download][foo.mkv] Written 208.9 MB (19s @ 12.9 MB/s)                          [stream.hls][debug] Download of segment 33 complete
[stream.hls][debug] Adding segment 55 to queue
[stream.hls][debug] Download of segment 34 complete
[stream.hls][debug] Adding segment 56 to queue
[download][foo.mkv] Written 216.1 MB (20s @ 11.5 MB/s)                          [stream.hls][debug] Download of segment 35 complete
[stream.hls][debug] Adding segment 57 to queue
[stream.hls][debug] Download of segment 36 complete
[stream.hls][debug] Adding segment 58 to queue
[download][foo.mkv] Written 225.9 MB (21s @ 12.2 MB/s)                          [stream.hls][debug] Download of segment 37 complete
[stream.hls][debug] Adding segment 59 to queue
[download][foo.mkv] Written 229.9 MB (21s @ 11.5 MB/s)                          [stream.hls][debug] Download of segment 38 complete
[stream.hls][debug] Adding segment 60 to queue
[download][foo.mkv] Written 237.4 MB (22s @ 11.7 MB/s)                          [stream.hls][debug] Download of segment 39 complete
[stream.hls][debug] Adding segment 61 to queue
[stream.hls][debug] Download of segment 40 complete
[stream.hls][debug] Adding segment 62 to queue
[download][foo.mkv] Written 246.2 MB (23s @ 11.4 MB/s)                          [stream.hls][debug] Download of segment 41 complete
[stream.hls][debug] Adding segment 63 to queue
[download][foo.mkv] Written 250.7 MB (23s @ 11.6 MB/s)                          [stream.hls][debug] Download of segment 42 complete
[stream.hls][debug] Adding segment 64 to queue
[download][foo.mkv] Written 260.3 MB (24s @ 12.4 MB/s)                          [stream.hls][debug] Download of segment 43 complete
[stream.hls][debug] Adding segment 65 to queue
[download][foo.mkv] Written 265.2 MB (24s @ 12.9 MB/s)                          [stream.hls][debug] Download of segment 44 complete
[stream.hls][debug] Adding segment 66 to queue
[stream.hls][debug] Download of segment 45 complete
[stream.hls][debug] Adding segment 67 to queue
[download][foo.mkv] Written 274.4 MB (25s @ 12.3 MB/s)                          [stream.hls][debug] Download of segment 46 complete
[stream.hls][debug] Adding segment 68 to queue
[download][foo.mkv] Written 277.9 MB (26s @ 10.6 MB/s)                          [stream.hls][debug] Download of segment 47 complete
[stream.hls][debug] Adding segment 69 to queue
[stream.hls][debug] Download of segment 48 complete
[stream.hls][debug] Adding segment 70 to queue
[download][foo.mkv] Written 290.9 MB (26s @ 12.4 MB/s)                          [stream.hls][debug] Download of segment 49 complete
[stream.hls][debug] Adding segment 71 to queue
[download][foo.mkv] Written 295.7 MB (27s @ 10.7 MB/s)                          [stream.hls][debug] Download of segment 50 complete
[stream.hls][debug] Adding segment 72 to queue
[download][foo.mkv] Written 303.4 MB (28s @ 11.5 MB/s)                          [stream.hls][debug] Download of segment 51 complete
[stream.hls][debug] Adding segment 73 to queue
[stream.hls][debug] Download of segment 52 complete
[stream.hls][debug] Adding segment 74 to queue
[download][foo.mkv] Written 311.8 MB (28s @ 11.4 MB/s)                          [stream.hls][debug] Download of segment 53 complete
[stream.hls][debug] Adding segment 75 to queue
[download][foo.mkv] Written 317.2 MB (29s @ 12.5 MB/s)                          [stream.hls][debug] Download of segment 54 complete
[stream.hls][debug] Adding segment 76 to queue
[download][foo.mkv] Written 322.2 MB (29s @ 10.9 MB/s)                          [stream.hls][debug] Download of segment 55 complete
[stream.hls][debug] Adding segment 77 to queue
[download][foo.mkv] Written 333.2 MB (30s @ 13.3 MB/s)                          [stream.hls][debug] Download of segment 56 complete
[stream.hls][debug] Adding segment 78 to queue
[download][foo.mkv] Written 334.8 MB (30s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 57 complete
[stream.hls][debug] Adding segment 79 to queue
[download][foo.mkv] Written 341.0 MB (31s @ 10.6 MB/s)                          [stream.hls][debug] Download of segment 58 complete
[stream.hls][debug] Adding segment 80 to queue
[download][foo.mkv] Written 348.0 MB (32s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 59 complete
[stream.hls][debug] Adding segment 81 to queue
[download][foo.mkv] Written 354.5 MB (32s @ 11.9 MB/s)                          [stream.hls][debug] Download of segment 60 complete
[stream.hls][debug] Adding segment 82 to queue
[stream.hls][debug] Download of segment 61 complete
[stream.hls][debug] Adding segment 83 to queue
[download][foo.mkv] Written 366.4 MB (33s @ 10.2 MB/s)                          [stream.hls][debug] Download of segment 62 complete
[stream.hls][debug] Adding segment 84 to queue
[download][foo.mkv] Written 372.5 MB (34s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 63 complete
[stream.hls][debug] Adding segment 85 to queue
[stream.hls][debug] Download of segment 64 complete
[stream.hls][debug] Adding segment 86 to queue
[download][foo.mkv] Written 384.3 MB (35s @ 12.4 MB/s)                          [stream.hls][debug] Download of segment 65 complete
[stream.hls][debug] Adding segment 87 to queue
[download][foo.mkv] Written 389.1 MB (35s @ 10.9 MB/s)                          [stream.hls][debug] Download of segment 66 complete
[stream.hls][debug] Adding segment 88 to queue
[download][foo.mkv] Written 397.6 MB (36s @ 10.6 MB/s)                          [stream.hls][debug] Download of segment 67 complete
[stream.hls][debug] Adding segment 89 to queue
[stream.hls][debug] Download of segment 68 complete
[stream.hls][debug] Adding segment 90 to queue
[download][foo.mkv] Written 413.4 MB (37s @ 11.1 MB/s)                          [stream.hls][debug] Download of segment 69 complete
[stream.hls][debug] Adding segment 91 to queue
[download][foo.mkv] Written 422.2 MB (38s @ 12.1 MB/s)                          [stream.hls][debug] Download of segment 70 complete
[stream.hls][debug] Adding segment 92 to queue
[download][foo.mkv] Written 427.3 MB (38s @ 11.0 MB/s)                          [stream.hls][debug] Download of segment 71 complete
[stream.hls][debug] Adding segment 93 to queue
[download][foo.mkv] Written 438.1 MB (39s @ 13.6 MB/s)                          [stream.hls][debug] Download of segment 72 complete
[stream.hls][debug] Adding segment 94 to queue
[download][foo.mkv] Written 440.2 MB (40s @ 12.1 MB/s)                          [stream.hls][debug] Download of segment 73 complete
[stream.hls][debug] Adding segment 95 to queue
[download][foo.mkv] Written 448.2 MB (40s @ 12.0 MB/s)                          [stream.hls][debug] Download of segment 74 complete
[stream.hls][debug] Adding segment 96 to queue
[download][foo.mkv] Written 454.6 MB (41s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 75 complete
[stream.hls][debug] Adding segment 97 to queue
[stream.hls][debug] Download of segment 76 complete
[stream.hls][debug] Adding segment 98 to queue
[download][foo.mkv] Written 465.0 MB (42s @ 11.5 MB/s)                          [stream.hls][debug] Download of segment 77 complete
[stream.hls][debug] Adding segment 99 to queue
[download][foo.mkv] Written 471.1 MB (43s @ 9.2 MB/s)                           [stream.hls][debug] Download of segment 78 complete
[stream.hls][debug] Adding segment 100 to queue
[download][foo.mkv] Written 479.4 MB (43s @ 10.4 MB/s)                          [stream.hls][debug] Download of segment 79 complete
[stream.hls][debug] Adding segment 101 to queue
[stream.hls][debug] Download of segment 80 complete
[stream.hls][debug] Adding segment 102 to queue
[download][foo.mkv] Written 493.9 MB (44s @ 11.1 MB/s)                          [stream.hls][debug] Download of segment 81 complete
[stream.hls][debug] Adding segment 103 to queue
[download][foo.mkv] Written 500.1 MB (45s @ 10.3 MB/s)                          [stream.hls][debug] Download of segment 82 complete
[stream.hls][debug] Adding segment 104 to queue
[download][foo.mkv] Written 508.6 MB (46s @ 10.9 MB/s)                          [stream.hls][debug] Download of segment 83 complete
[stream.hls][debug] Adding segment 105 to queue
[stream.hls][debug] Download of segment 84 complete
[stream.hls][debug] Adding segment 106 to queue
[download][foo.mkv] Written 520.6 MB (47s @ 12.2 MB/s)                          [stream.hls][debug] Download of segment 85 complete
[stream.hls][debug] Adding segment 107 to queue
[download][foo.mkv] Written 525.6 MB (47s @ 12.4 MB/s)                          [stream.hls][debug] Download of segment 86 complete
[stream.hls][debug] Adding segment 108 to queue
[download][foo.mkv] Written 531.1 MB (48s @ 11.1 MB/s)                          [stream.hls][debug] Download of segment 87 complete
[stream.hls][debug] Adding segment 109 to queue
[stream.hls][debug] Download of segment 88 complete
[stream.hls][debug] Adding segment 110 to queue
[download][foo.mkv] Written 541.6 MB (49s @ 12.3 MB/s)                          [stream.hls][debug] Download of segment 89 complete
[stream.hls][debug] Adding segment 111 to queue
[download][foo.mkv] Written 549.9 MB (49s @ 12.5 MB/s)                          [stream.hls][debug] Download of segment 90 complete
[stream.hls][debug] Adding segment 112 to queue
[download][foo.mkv] Written 553.5 MB (50s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 91 complete
[stream.hls][debug] Adding segment 113 to queue
[stream.hls][debug] Download of segment 92 complete
[stream.hls][debug] Adding segment 114 to queue
[download][foo.mkv] Written 562.0 MB (50s @ 11.8 MB/s)                          [stream.hls][debug] Download of segment 93 complete
[stream.hls][debug] Adding segment 115 to queue
[stream.hls][debug] Download of segment 94 complete
[stream.hls][debug] Adding segment 116 to queue
[download][foo.mkv] Written 571.1 MB (51s @ 10.9 MB/s)                          [stream.hls][debug] Download of segment 95 complete
[stream.hls][debug] Adding segment 117 to queue
[download][foo.mkv] Written 581.3 MB (52s @ 11.8 MB/s)                          [stream.hls][debug] Download of segment 96 complete
[stream.hls][debug] Adding segment 118 to queue
[stream.hls][debug] Download of segment 97 complete
[stream.hls][debug] Adding segment 119 to queue
[download][foo.mkv] Written 592.1 MB (53s @ 11.0 MB/s)                          [stream.hls][debug] Download of segment 98 complete
[stream.hls][debug] Adding segment 120 to queue
[stream.hls][debug] Download of segment 99 complete
[stream.hls][debug] Adding segment 121 to queue
[download][foo.mkv] Written 601.5 MB (54s @ 12.0 MB/s)                          [stream.hls][debug] Download of segment 100 complete
[stream.hls][debug] Adding segment 122 to queue
[download][foo.mkv] Written 605.5 MB (54s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 101 complete
[stream.hls][debug] Adding segment 123 to queue
[download][foo.mkv] Written 611.4 MB (55s @ 11.5 MB/s)                          [stream.hls][debug] Download of segment 102 complete
[stream.hls][debug] Adding segment 124 to queue
[download][foo.mkv] Written 619.7 MB (56s @ 10.3 MB/s)                          [stream.hls][debug] Download of segment 103 complete
[stream.hls][debug] Adding segment 125 to queue
[stream.hls][debug] Download of segment 104 complete
[stream.hls][debug] Adding segment 126 to queue
[download][foo.mkv] Written 631.9 MB (56s @ 11.1 MB/s)                          [stream.hls][debug] Download of segment 105 complete
[stream.hls][debug] Adding segment 127 to queue
[download][foo.mkv] Written 637.4 MB (57s @ 9.6 MB/s)                           [stream.hls][debug] Download of segment 106 complete
[stream.hls][debug] Adding segment 128 to queue
[download][foo.mkv] Written 646.3 MB (58s @ 11.0 MB/s)                          [stream.hls][debug] Download of segment 107 complete
[stream.hls][debug] Adding segment 129 to queue
[download][foo.mkv] Written 652.9 MB (59s @ 11.2 MB/s)                          [stream.hls][debug] Download of segment 108 complete
[stream.hls][debug] Adding segment 130 to queue
[download][foo.mkv] Written 663.4 MB (59s @ 12.0 MB/s)                          [stream.hls][debug] Download of segment 109 complete
[stream.hls][debug] Adding segment 131 to queue
[download][foo.mkv] Written 673.9 MB (1m0s @ 12.6 MB/s)                         [stream.hls][debug] Download of segment 110 complete
[stream.hls][debug] Adding segment 132 to queue
[download][foo.mkv] Written 676.3 MB (1m0s @ 12.3 MB/s)                         [stream.hls][debug] Download of segment 111 complete
[stream.hls][debug] Adding segment 133 to queue
[stream.hls][debug] Download of segment 112 complete
[stream.hls][debug] Adding segment 134 to queue
[download][foo.mkv] Written 690.7 MB (1m1s @ 12.3 MB/s)                         [stream.hls][debug] Download of segment 113 complete
[stream.hls][debug] Adding segment 135 to queue
[stream.hls][debug] Download of segment 114 complete
[stream.hls][debug] Adding segment 136 to queue
[download][foo.mkv] Written 701.3 MB (1m2s @ 12.4 MB/s)                         [stream.hls][debug] Download of segment 115 complete
[stream.hls][debug] Adding segment 137 to queue
[download][foo.mkv] Written 711.3 MB (1m3s @ 12.9 MB/s)                         [stream.hls][debug] Download of segment 116 complete
[stream.hls][debug] Adding segment 138 to queue
[download][foo.mkv] Written 716.8 MB (1m4s @ 10.9 MB/s)                         [stream.hls][debug] Download of segment 117 complete
[stream.hls][debug] Adding segment 139 to queue
[download][foo.mkv] Written 725.0 MB (1m4s @ 12.8 MB/s)                         [stream.hls][debug] Download of segment 118 complete
[stream.hls][debug] Adding segment 140 to queue
[download][foo.mkv] Written 730.8 MB (1m5s @ 11.6 MB/s)                         [stream.hls][debug] Download of segment 119 complete
[stream.hls][debug] Adding segment 141 to queue
[stream.hls][debug] Download of segment 120 complete
[stream.hls][debug] Adding segment 142 to queue
[download][foo.mkv] Written 744.2 MB (1m6s @ 12.5 MB/s)                         [stream.hls][debug] Download of segment 121 complete
[stream.hls][debug] Adding segment 143 to queue
[download][foo.mkv] Written 751.1 MB (1m7s @ 10.9 MB/s)                         [stream.hls][debug] Download of segment 122 complete
[download][foo.mkv] Written 757.9 MB (1m7s @ 11.4 MB/s)                         [stream.hls][debug] Download of segment 123 complete
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 124 complete
[download][foo.mkv] Written 772.8 MB (1m8s @ 11.2 MB/s)                         [stream.hls][debug] Download of segment 125 complete
[download][foo.mkv] Written 780.8 MB (1m9s @ 12.1 MB/s)                         [stream.hls][debug] Download of segment 126 complete
[download][foo.mkv] Written 786.4 MB (1m10s @ 10.5 MB/s)                        [stream.hls][debug] Download of segment 127 complete
[download][foo.mkv] Written 796.1 MB (1m10s @ 11.7 MB/s)                        [stream.hls][debug] Download of segment 128 complete
[download][foo.mkv] Written 802.6 MB (1m11s @ 11.9 MB/s)                        [stream.hls][debug] Download of segment 129 complete
[download][foo.mkv] Written 811.8 MB (1m12s @ 12.6 MB/s)                        [stream.hls][debug] Download of segment 130 complete
[download][foo.mkv] Written 814.1 MB (1m13s @ 9.5 MB/s)                         [stream.hls][debug] Download of segment 131 complete
[download][foo.mkv] Written 824.8 MB (1m13s @ 12.5 MB/s)                        [stream.hls][debug] Download of segment 132 complete
[stream.hls][debug] Download of segment 133 complete
[download][foo.mkv] Written 836.5 MB (1m14s @ 11.1 MB/s)                        [stream.hls][debug] Download of segment 134 complete
[download][foo.mkv] Written 843.0 MB (1m15s @ 10.8 MB/s)                        [stream.hls][debug] Download of segment 135 complete
[stream.hls][debug] Download of segment 136 complete
[download][foo.mkv] Written 854.9 MB (1m15s @ 11.2 MB/s)                        [stream.hls][debug] Download of segment 137 complete
[stream.hls][debug] Download of segment 138 complete
[download][foo.mkv] Written 863.0 MB (1m16s @ 12.7 MB/s)                        [stream.hls][debug] Download of segment 139 complete
[stream.hls][debug] Download of segment 140 complete
[download][foo.mkv] Written 872.2 MB (1m17s @ 11.6 MB/s)                        [stream.hls][debug] Download of segment 141 complete
[stream.hls][debug] Download of segment 142 complete
[download][foo.mkv] Written 881.6 MB (1m18s @ 12.4 MB/s)                        [stream.hls][debug] Download of segment 143 complete
[stream.hls][debug] Closing writer thread

[cli][info] Stream ended
[cli][info] Closing currently open stream...

**Comment by mlindner** [comment]
Here is the mpv output when I play the resultant file: https://gist.github.com/mlindner/f19e1f9f81404f4c8a532ab4ea7e35b9

**Comment by mlindner** [comment]
Similar results occur if simply streaming directly from streamlink into mpv though the errors are somewhat different.

**Comment by gravyboat** [comment]
Hmm okay. I saw https://medium.com/ellation-tech/improving-video-quality-for-crunchyroll-and-vrv-dd587261a364 earlier this week, but that appears to be utter bullshit according to https://www.reddit.com/r/anime/comments/5zrlbh/improving_video_quality_for_crunchyroll_and_vrv/ which goes into discussion regarding the HLS/DASH standards. Thanks for the detailed Streamlink output and the MPV output. Do you get similar results with other players?

**Comment by mlindner** [comment]
I only have mpv installed and updated so I haven't tried testing it with other players. You're more than welcome to give it a try as it should be reproducible easily. Can you please re-tag this as a bug? It's not a question.

**Comment by beardypig** [comment]
I just tested out that episode and it plays fine with `mpv 0.21.0`.
```console
$ mpv tanya10.ts --untimed --ao=null --vo=null --no-audio
Playing: tanya10.ts
[ffmpeg/demuxer] mpegts: start time for stream 2 is not set in estimate_timings_from_pts
 (+) Video --vid=1 (h264)
     Audio --aid=1 (aac)
VO: [null] 1920x1080 yuv420p
V: 00:23:40 / 00:23:40 (99%)

Exiting... (End of file)
```

**Comment by mlindner** [comment]
Odd... I just tried it again and it's working now, maybe this was a bug somewhere else in the chain or something else along those lines. Guess it's not a bug, or at least not a consistent bug.

**Comment by beardypig** [comment]
I would think that it is most likely an issue on crunchyroll's side, rather than a software bug in streamlink :-)

**Comment by beardypig** [comment]
Tested it again on a gundam episode that had been released less than an hour ago, that worked fine also. Perhaps it was a transient error in crunchyroll :)

**Comment by gravyboat** [comment]
@mlindner I'm going to close this for the time being, if it happens again can you re-open the issue and we'll tag it appropriately at that time? @beardypig I could definitely see some issue on Crunchyroll's end, it's been a few crappy weeks for them.
