### ISSUE TITLE
Play video from this url ? 

### ISSUE THREAD

**Issue by devwhatsapp** [streamlink/streamlink#721]
Hi

How can we play videos from this url in vlc ?

http://cyro.se/watch/homeland/s6/e9

The page loads iframe of google video player.

The videos are stored in google drive or google docs.

Please if anyone can make a plugin to play video on vlc from such url which uploads video on google video servers.

Regards

**Comment by beardypig** [comment]
This is a [work-in-progress plugin](https://github.com/beardypig/streamlink/tree/googledocs) for playing videos hosted on Google Docs - needs more testing :)

**Comment by back-to** [comment]
the regex needs an update
```
https://docs.google.com/file/d/--ID--/edit
https://docs.google.com/file/d/--ID--/view
```
you can watch videos with this aswell.

----

and maybe a check for `fmt_list` in `data`
to avoid `KeyError: 'fmt_list'` for files without a video or dead links

```python
data = dict(parse_qsl(res.text))
if "fmt_list" in data:
    fmts = dict([s.split('/')[:2] for s in data["fmt_list"].split(",")])
```

**Comment by beardypig** [comment]
Thanks for the extra info @back-to and for testing it out :)
