### ISSUE TITLE
bigoweb.co / bigolive.tv plugin no longer works

### ISSUE THREAD

**Issue by kalmalone** [streamlink/streamlink#722]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
error: No plugin can handle bigoweb.co addressess as of 10 minutes ago

### Expected / Actual behavior

10 minutes ago it worked fine and now it gives an error.
...

### Reproduction steps / Stream URLs to test

1. ...http://www.bigoweb.co/ (any stream)
2. ...
3. ...

### Environment details (operating system, python version, etc.)

...

### Comments, logs, screenshots, etc.

...

**Comment by back-to** [comment]
Regex doesn't match the `www`
https://github.com/streamlink/streamlink/blob/b540375ce17575121a09dd292701efdc81370876/src/streamlink/plugins/bigo.py#L50

Remove the `www` from the url

From
`streamlink http://www.bigoweb.co/show/00000000 best`
to
`streamlink http://bigoweb.co/show/00000000 best`

```
streamlink http://bigoweb.co/show/00000000 best
[cli][info] Found matching plugin bigo for URL http://bigoweb.co/show/00000000
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (stream)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by gravyboat** [comment]
Thanks for the report, I've merged the associated PR that fixes this.
