### ISSUE TITLE
Vaughnlive.tv streams get this error angain [Resolved]

### ISSUE THREAD

**Issue by Maralexbar** [streamlink/streamlink#723]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

## EDIT: Please close this issue, update vaughnlive.py and get works

  
Any streams of vaughnlive.tv get this error

Error: Unable to validate response text: u'' does not equal u'' or Minimum length is 3 but value is 1

### Expected / Actual behavior

The problem started 10 days ago

### Reproduction steps / Stream URLs to test

1. ... http://vaughnlive.tv/sherming66
2. ... http://vaughnlive.tv (any online stream)
3. ...

### Environment details (operating system, python version, etc.)

Linux Mint 18 Cinnamon 64bit
Python 2.7.11+

### Comments, logs, screenshots, etc.

This is for testing Available streams
$ streamlink http://vaughnlive.tv/sherming66
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/sherming66
error: Unable to validate response text: u'' does not equal u'<error></error>' or Minimum length is 3 but value is 1

This is my original command line usually use

streamlink http://vaughnlive.tv/sherming66 live -o=rec.flv

**Comment by beardypig** [comment]
@Maralexbar thanks for solving it yourself :D
