### ISSUE TITLE
Some links on viafree.no (viasat plugin) not working (updated with correct error message)

### ISSUE THREAD

**Issue by kmyhre** [streamlink/streamlink#727]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Some links on Viafree does work, other gives an error.

### Expected / Actual behavior

Expected behavior:
```
user$ streamlink https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5 best
[cli][info] Found matching plugin viasat for URL https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5
[cli][info] Available streams: 48k (worst), 180p, 270p, 432p, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
```

Actual behavior:
```
user$ streamlink https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5 best
error: No plugin can handle URL: https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5
```

### Stream URLs to test

URLs:
1. https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5 (not working)
2. https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/817236 (working)

**Comment by gravyboat** [comment]
Can you please run the request with the `-v` and `-l  debug` options? Then we'll get more output to see if there's something missing.

**Comment by kmyhre** [comment]
Sure, but it doesn't seem to give any more information:

```
user$ streamlink -v https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1 best
error: No plugin can handle URL: https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1

```
```
user$ streamlink -l debug https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1 best
error: No plugin can handle URL: https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-1

```

**Comment by kmyhre** [comment]
While the working links looks like this:
```
user$ streamlink -l debug https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/816551 best
[cli][info] Found matching plugin viasat for URL https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/816551
[cli][info] Available streams: 48k (worst), 180p, 270p, 432p, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 1 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Download of segment 1 complete
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[stream.hls][debug] Download of segment 2 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Download of segment 4 complete
```

**Comment by Yetangitu** [comment]
I ran into this problem as well when trying to download something from the Swedish equivalent of this site. You'll notice that the working links all end in a numerical program id ('817236' in the working url above) while the non-working ones end in some textual description ('episode-5' in the one above). `streamlink` needs a numerical *program id* to be able to find the streams associated with the url, without this *id* it will complain as seen above. What you need to do is find the *program id* somewhere in the page referenced by the url. As *viafree* uses `react` the page source comprises of a chunk of JSON with an HTML header attached to it, making it harder to scrape than necessary. Fortunately you can get the data you need from the header as the *program id* is also used to get the thumbnail images. You can extract it from e.g. the 'og:image' `meta` tag using the following incantation:

```bash
id=$(xidel -s -e "//meta[@property='og:image']/@content" "$url" | cut -d '/' -f 9)
```

This uses [xidel](http://www.videlibri.de/xidel.html) (make sure to use the latest version which supports the *xpath* syntax and other parameters used in this example) to extract the contents of the relevant `meta` tag, the results of which are piped through `cut` to get at the correct path component. This might not be the most robust way to get at the data but for now it works. If you want to save the stream to a file you can do the same for the file name to which the data should be written:

```bash
filename=$(xidel -s -e "//meta[@property='og:title']/@content" "$url" | iconv -t ASCII//TRANSLIT|tr -d -c '[:alnum:][:blank:]'|tr -s '[:blank:]' _).mp4
```

Now you just need to modify the original url by adding the program id and streamlink will know how to handle it:

```bash
url=https://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-9/episode-5
id=$(xidel -s -e "//meta[@property='og:image']/@content" "$url" | cut -d '/' -f 9)
url="${url}/${id}"
streamlink "$url"
```
