### ISSUE TITLE
Streams failing / "Failed to reload playlist: Unable to open URL"

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink#728]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Streams frequently breaking down. 

### Expected / Actual behavior

Streams fail randomly, can happen after a few minutes, or several hours. Happens at least a few times per week.

When the stream breaks down VLC goes black, as if it was just launched and nothing is playing.

### Reproduction steps / Stream URLs to test

Seeing the issue with plenty of Twitch streams, haven't seen a pattern. Just start a stream and wait.

Example - twitch.tv/starladder_cs_en - 720p@60fps

### Environment details (operating system, python version, etc.)

Win7 SP1 x64, VLC 2.2.4, Streamlink 0.2.0, normally using Streamlink-Twitch-GUI for launching streams.

### Comments, logs, screenshots, etc.

Originally posted this as a [Streamlink-Twitch-GUI](https://github.com/streamlink/streamlink-twitch-gui/issues/425#issuecomment-288519049) issue.

[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe"
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://vid
eo-edge-c2a548.arn03.hls.ttvnw.net/v0/CtcBnxSlJG9nFL9SKomIY5PJf6XumqhviK9tGbA15J
gpPgQKMJKk-o4CcHCHdpgGssHthacZEsDtRy1quKjjWc9L-uRdnjhh7DtiRzcdB1HO88VPomMI5huRFp
uCRzHgszX20aZC6U31Z7c_2KuctmWPv4mRNuMV7eXgmmL4W8r0yn9UzlFrDIntje4TxyLuqLE4Vt8t4o
AxStecnZ-MqwYLVU-SusxBG0oUPrCmyJeTAETDiyec9bYW9oFc35MJD2_yLJ85JeaFSyyE1W-dCLC_04
mFTYVsTwMSEAN5GEo3SJoP0HsYEm_CVhwaDHXn26JQ6HG_TDNnOA/index-live.m3u8 (('Connecti
on aborted.', ConnectionResetError(10054, 'An existing connection was forcibly c
losed by the remote host', None, 10054, None)))
Exception in thread Thread-1:
Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 298, in _error_catcher
yield
File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 380, in read
data = self._fp.read(amt)
File "http\client.py", line 448, in read
File "http\client.py", line 488, in readinto
File "socket.py", line 575, in readinto
File "ssl.py", line 929, in recv_into
File "ssl.py", line 791, in read
File "ssl.py", line 575, in read
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 703, in
generate
for chunk in self.raw.stream(chunk_size, decode_content=True):
File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 432, in stream
data = self.read(amt=amt, decode_content=decode_content)
File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 397, in read
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
File "contextlib.py", line 77, in exit
File "C:\Program Files (x86)\Streamlink\pkgs\requests\packages\urllib3\respons
e.py", line 303, in _error_catcher
raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=
'video-edge-c2a548.arn03.hls.ttvnw.net', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "threading.py", line 914, in _bootstrap_inner
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py",
line 160, in run
self.write(segment, result)
File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 1
11, in write
for chunk in res.iter_content(chunk_size):
File "C:\Program Files (x86)\Streamlink\pkgs\requests\models.py", line 710, in
generate
raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='video-edge-c2a548
.arn03.hls.ttvnw.net', port=443): Read timed out.

[cli][error] Error when reading from stream: Read timeout
[cli][info] Stream ended

**Comment by gravyboat** [comment]
We've fixed several issues related to similar errors recently (#475, #547), can you please update to the latest version of streamlink to see if you still get the exceptions? There's been a good number of improvements since `0.2.0`.

**Comment by sfkpmr** [comment]
Thanks! Updated to 0.4.0 and will update with results.

**Comment by sfkpmr** [comment]
Looks like the update fixed it.

**Comment by gravyboat** [comment]
Good stuff, thanks for the update @sfkpmr.
