### ISSUE TITLE
Order of qualities returned by API/CLI

### ISSUE THREAD

**Issue by enzanki-ars** [streamlink/streamlink#729]
### Checklist

- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Instead of using a `Dict`, it might be better to use an `OrderedDict` object to store the stream URLs, allowing for easier viewing of the available qualities and control of the selected quality from the API side.  

For example, this change could allow this...

```
Available streams: 540p_alt2, 720p_alt, 1080p_alt, 236p_alt, 360p_alt, 236p_alt2, 236p (worst), 
360p, 540p, 720p, 1080p (best)
```

...to instead be displayed as this...

```
Available streams: 236p (worst), 236p_alt, 236p_alt2, 360p, 360p_alt, 540p, 540p_alt2, 720p, 
720p_alt, 1080p (best), 1080p_alt
```

...or even...

```
Available streams: 
 - 236p (worst)
 - 236p_alt
 - 236p_alt2
 - 360p
 - 360p_alt
 - 540p
 - 540p_alt2
 - 720p
 - 720p_alt
 - 1080p (best)
 - 1080p_alt
```

**Comment by gravyboat** [comment]
I think this is a pretty good idea. It wasn't such a major issue for livestreamer as it originally functioned because there were so few options (usually just 3 when I started using it), but as more options show up this could definitely benefit users. Let's see what kind of discussion this issue generates. Thanks @enzanki-ars.

**Comment by enzanki-ars** [comment]
I was poking through the source code to try and see if I could make a simple PR for it, but there is a lot to read through.  In theory, this should be a one line change, but I just need to find the one line (such as changing a `{}` to an `OrderedDict()`).  Also, in theory, this change should be backwards compatible.

**Comment by enzanki-ars** [comment]
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L257 should be the line.  Changing it from `{}` to `OrderedDict()` should work.  Testing locally now...

**Comment by enzanki-ars** [comment]
I have made a couple of modifications to get this idea to work, and I might have discovered another bug:

Sorting the streams based on the [`stream_weight_only` function](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L297) (which uses the [`stream_weight` function](https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugin/plugin.py#L39) on a certain HLS url produces the following.  This does not effect the best/worst, as all the `alt` streams are ignored, but the `alt` streams are not sorted properly.  

`['576p_alt', '360p_alt', '64k_alt', '270p_alt', '540p_alt', '64k', '270p', '360p', '540p', '576p']`

I will open a PR with the changes though so everyone can see how I came to this conclusion.

**Comment by gravyboat** [comment]
Closing this since #731 is merged.
