### ISSUE TITLE
Streamlink.exe suggestion

### ISSUE THREAD

**Issue by Zero3K** [streamlink/streamlink#730]
### Checklist

- [] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

It should be used to transfer the stream to the media player instead of having both it and python.exe running.

**Comment by gravyboat** [comment]
This would be impossible. Streamlink is an application written in Python so we have to invoke Python to run it.
