### ISSUE TITLE
showup.tv plugin request

### ISSUE THREAD

**Issue by compaqhp** [streamlink/streamlink#734]
- [x ] This is a plugin request.
- [x ] This is a feature request.

### Description
would be great if someone could create a plugin for website showup.tv 

### Reproduction steps / Stream URLs to test

1.   http://showup.tv/

**Comment by gravyboat** [comment]
Could you please provide some more details? For example what does a request look like for an actual channel on this website, is it geo restricted? Can you provide us with any other information that would potentially help create a plugin?

**Comment by compaqhp** [comment]
showup is a polish website similar to chaturbate. it would be helpful play the streams on showup on a simple movieplayer like VLC or MPV. the way like the chaturbaute-plugin does.

**Comment by gravyboat** [comment]
Okay but I mean what does a URL look like for a channel? Is it geo-restricted? Have you reviewed how the requests look at all, etc.?

**Comment by wiemar7** [comment]
little info 
url to profile like: https://showup.tv/user123
someone making java script:
`javascript:(function(){window.prompt("Gotowa komenda :) Skopiuj CTRL+C",'rtmpdump -r "rtmp://5.135.128.167/liveedge/'+transmission.streamID+'" -o "'+document.location.pathname.replace(/\//g,"")+"_"+(+(new Date/1e3)).toFixed(0)+'.flv"')})()`
when user123 start streaming we use this script to get:
rtmpdump -r "rtmp://5.135.128.167/liveedge/771d3722f1a6778a46269eb2bf9023d7" -o "file.flv"
this ip is permanent. only id was generated

**Comment by gravyboat** [comment]
I'm going to close this. A while back we decided we don't want to add any more cam sites.
