### ISSUE TITLE
Twitch.tv memory leak

### ISSUE THREAD

**Issue by hannesfrank** [streamlink/streamlink#736]
- [x] This is a bug report.

### Description

When streaming from twitch.tv my memory fills up with a rate of about 100MB/s until all RAM and Swap is used and my system crashes (see screenshots below).

I did not had this issue a few days/weeks ago. I do not remember installing any updates that could break it. I do not have this issue with Daily Motion right now.

### Expected / Actual behavior

Do not make my computer crash - obviously :grin:. 

### Reproduction steps / Stream URLs to test

```
$ streamlink twitch.tv/bobross best
```

### Environment details (operating system, python version, etc.)

```
$ streamlink -V
streamlink 0.4.0

$ vlc --version     
VLC media player 2.2.2 Weatherwax (revision 2.2.2-0-g6259d80)
```

![systeminfo_small](https://cloud.githubusercontent.com/assets/4137110/24330876/a4790af0-1228-11e7-9e4f-1f3a211605c6.png)

### Comments, logs, screenshots, etc.

![twitch_running](https://cloud.githubusercontent.com/assets/4137110/24330846/f3d4b51e-1227-11e7-8cbb-7d2fde66a524.png)
![twitch_stopped](https://cloud.githubusercontent.com/assets/4137110/24330849/f8d08408-1227-11e7-8f61-785aba70e34c.png)

Some log output:
```
$ streamlink twitch.tv/bobross best -l debug
[cli][info] Found matching plugin twitch for URL twitch.tv/bobross
[plugin.twitch][debug] Getting live HLS streams for bobross
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30409 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 30410 to queue
[stream.hls][debug] Adding segment 30411 to queue
[stream.hls][debug] Download of segment 30409 complete
[cli][info] Starting player: /usr/bin/vlc
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 30410 complete
[stream.hls][debug] Download of segment 30411 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30412 to queue
[stream.hls][debug] Download of segment 30412 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30413 to queue
[stream.hls][debug] Download of segment 30413 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30414 to queue
[stream.hls][debug] Adding segment 30415 to queue
[stream.hls][debug] Download of segment 30414 complete
[stream.hls][debug] Download of segment 30415 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30416 to queue
[stream.hls][debug] Download of segment 30416 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 30417 to queue
[cli][info] Player closed
[stream.hls][debug] Closing worker thread
[stream.hls][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by beardypig** [comment]
Does it do the same if you save the stream to a file using `-o test.ts`?

**Comment by hannesfrank** [comment]
No, when saving to a file it stays at about 37MB RAM usage.

I just noticed that the used memory above is not associated to any process (at least I don't find it). So maybe it's a problem with my system after all. Any idea how to debug/profile that? I had not luck with `system-monitor`/`htop`/`glances`.

**Comment by beardypig** [comment]
OK. Sounds like it could be to do with piping the video to vlc. Could you try using the [--player-http](https://streamlink.github.io/cli.html#cmdoption-player-http) and then with [--player-fifo](https://streamlink.github.io/cli.html#cmdoption-player-fifo) options to see if either uses a lot of memory?

**Comment by hannesfrank** [comment]
I tried the following:

- `--player-http`: still happens.
- `--player-fifo`: still happens (and vlc does not autoplay).
- `-p 'vlc --file-caching=5000'`: see screenshot left side (60-52s: file-caching effect, 52-45s: increase as before).
- `-p 'vlc --file-caching=30000'`: see screenshot right side (23-2s: file-caching effect, 2-0s: increase as before).
- `-p mplayer`: **No memory issues!** But mplayer is often buffering.

With `--file-caching` the slope of the memory consumption seems lower at first:
![file-caching](https://cloud.githubusercontent.com/assets/4137110/24331623/618d5fec-1238-11e7-8639-3ff478f52437.png)

**Comment by bastimeyer** [comment]
> I just noticed that the used memory above is not associated to any process
> -p mplayer: No memory issues!

What happens when you disable or change the VLC renderer?
`streamlink -p vlc -a "--no-video {filename}" twitch.tv/bobross best`

https://wiki.videolan.org/Documentation:Command_line/#Modules_selection

**Comment by hannesfrank** [comment]
Without video the memory usage seems to be stable.

**Comment by hannesfrank** [comment]
Sorry for wasting your time and thank you very much for your help. I found the issue **and it has nothing to do with streamlink**:

A few days ago VLC was complaining about a missing `.so` ...

```
Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
```

... and I wanted to get rid that complaint and installed the lib with `sudo apt install libvdpau-va-gl1`. This [somehow caused the leak](https://github.com/i-rinat/libvdpau-va-gl/issues/58).

A simple `sudo apt purge libvdpau-va-gl1` solved the issue for me.

**Comment by gravyboat** [comment]
Thanks for the update and detailed resolution @hannesfrank!
