### ISSUE TITLE
Saving Outputs

### ISSUE THREAD

**Issue by mikktsu** [streamlink/streamlink#737]
I would like to know how to change it so instead of asking if I want to overwrite an existing file, it will automatically add a number, a letter or even a "-" at the end of the new file.

Example:

file.flv file1.flv  file2.flv file3.flv 

file.flv file(1).flv file(2).flv  file(3).flv

file.flv file_a.flv  file_b.flv  file_c.flv  

file.flv file-.flv       file--.flv          file---.flv

**Comment by bastimeyer** [comment]
What you're describing is a feature of your operating system's file manager, like Windows Explorer, Finder, Nautilus, Dolphin, Thunar, etc.

If you want unique file names, you have to set them yourself as a parameter. Usually, this is being done by using a timestamp in a certain format (that can be sorted).

```bash
streamlink -o "$(date +"file_%Y%m%d%H%M%S.flv")" URL QUALITY
```

If you want the file names to have an unique ID included instead, you will need to write a script that reads all the file names of the target directory and generates a new one that doesn't exist yet depending on the existing ones.

**Comment by mikktsu** [comment]
This is very helpful. Thank you. Now I am trying to research how to write the output as the filename "playpath + date". Would I have to modify the "streamlinkrc" file to tell it which directory I want the files to go or would I need to make changes to the actual code? Any help is greatly appreciated.

**Comment by gravyboat** [comment]
You would have to modify your command, other users are saving into specific directories without issue. There are a good number of examples online talking about how to do this as well as in older issues if you look through some of them. I'm going to close this out since the original question is resolved, and file paths are something you can easily find.
