### ISSUE TITLE
Taking snapshots

### ISSUE THREAD

**Issue by allchemist** [streamlink/streamlink#738]
Hello!

In my program, i'd like to work with each video frame as an image, could you please add a python example how to end up with snapshots instead of visual playbin?

**Comment by bastimeyer** [comment]
You can do this with ffmpeg. Just write the stream data to your filesystem and read it with ffmpeg or pipe it directly into the ffmpeg process.

https://www.google.com/#q=ffmpeg+export+image+sequence

**Comment by allchemist** [comment]
I tried same approach with opencv VideoCapture, but unfortunately it does not allow jumping to desired frame number at non-finalized video file.

If i can do that with ffmpeg, thats good. Thanks for answer!

**Comment by allchemist** [comment]
Right now i inderstood that i do not need full stream record, but need to get the latest available frame by request (approx 3-4 times per second). Could you please suggest solution for this?

**Comment by beardypig** [comment]
If you just want the latest frame (updated 4 times a second) you could try this
```
streamlink "http://test.com/stream" best -O | ffmpeg -i pipe:0 -filter:v fps=4 -updatefirst 1 live.jpeg
```
Which will update `live.jpeg` 4 times per second with the latest frame.

**Comment by allchemist** [comment]
Thanks

I tried this solutoin. It works, but real fps is about 0.5-1, meaning live.jpg is not being updated in more than a second, never mind what fps value i set.

I tried source and low quality, the problem stays. Internet connection quality is wonderful (amazon server)

**Comment by beardypig** [comment]
Probably best to ask around in some `ffmpeg` or `opencv` forums about extracting the latest frame from a streaming video. It's not really something that is covered by `streamlink`, I think we've answered to the best our limited abilities.

**Comment by bastimeyer** [comment]
Going to close the thread, since the question has been answered.
