### ISSUE TITLE
Support for Seasons/Multiplier Episodes on Crunchyroll/Daisuki

### ISSUE THREAD

**Issue by nwgat** [streamlink/streamlink#740]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Support for Seasons/Multiplier Episodes
...

### Expected / Actual behavior
Play one episode after another

### Reproduction steps / Stream URLs to test

1. `streamlink http://www.crunchyroll.com/miss-kobayashis-dragon-maid --player=mpv`
2. `streamlink http://www.daisuki.net/no/en/anime/detail.GRANBLUEFANTASY.html --player=mpv`

### Environment details (operating system, python version, etc.)
v0.4.0 - Git fb81b65
Portable
...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
Streamlink isn't designed to do this and it would be outside the scope of our implementation (we're not building this sort of page scraper). You might want to look at writing some kind of wrapper using BeautifulSoup or some other tool that scrapes the pages and them passes them to Streamlink while monitoring the process to determine when an episode finishes. I'm going to close this for now as it's outside the scope of Streamlink's intended usage.

**Comment by nwgat** [comment]
youtube-dl crunchyroll plugin does this you can look at their code here
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/crunchyroll.py

thanks for streamlink, keep up the good work 👍
