### ISSUE TITLE
RTMPDUMP update

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#741]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

I have carried out tests with 3 different rtmpdump distros.
One packed with streamlink-latest.exe fails and should be replaced, really,
if not with KSV one, then with ZERANOE one at least.

### Expected / Actual behavior

Expected to download / Actually fails ( RTMPDUMP on its own tested )

### Reproduction steps / Stream URLs to test

1. ImLive
2. Logged in as a member ( freeloader )
3. Params from RTMPSUCK, any before K-S-V 2.4. 
K-S-V 2.4 RTMPSUCK crushes.

### Environment details (operating system, python version, etc.)

WIN 7 64

### Comments, logs, screenshots, etc.

RTMPDUMP from:

streamlink-latest.exe 0.4.0.1082:
```
These binaries have been compiled from the unmodified source
available at git://git.ffmpeg.org/rtmpdump (commit: df6c51884243ef2bd12931e6c617b2be7520ca26).
Cross-compiled using MinGW32 and statically linked with
PolarSSL v1.2.7 and zlib v1.2.3 on a Linux host.
```
```
C:\>rtmpdump -v -r "rtmp://926-f70bcbc608.c.hibcdn.net/live" -a "live" -f "WIN 25,0,0,127" -W "https://imlive.com/swf/genericguestapp.swf" -p "https://imlive.com/flash_sdk/freevideochatguest.aspx?hostnick=greeneyesgirl&roomid=10" -y "coolvisionrtmp3_greeneyesgirl" -o "greeneyesgirl_2017-03-29_01-07-03.flv"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting Live Stream
15.523 kB / 1677.56 sec
WARNING: HandleInvoke, Sanity failed. no string method in invoke packet
WARNING: HandleInvoke, Sanity failed. no string method in invoke packet
15.523 kB / 1677.56 sec
Download complete
```
```
C:\>rtmpdump -v -r "rtmp://926-f70bcbc608.c.hibcdn.net/live" -a "live" -f "WIN 25,0,0,127" -W "https://imlive.com/swf/genericguestapp.swf" -p "https://imlive.com/flash_sdk/freevideochatguest.aspx?hostnick=greeneyesgirl&roomid=10" -y "coolvisionrtmp3_greeneyesgirl" -o "greeneyesgirl_2017-03-29_01-07-35.flv"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting Live Stream
15.239 kB / 1708.96 sec
```
_________________________________________________________________________________________________

RTMPDUMP from:

https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=1024

rtmpdump-20140302-git-79459a2-win32.7z

```
C:\>rtmpdump -v -r "rtmp://926-f70bcbc608.c.hibcdn.net/live" -a "live" -f "WIN 25,0,0,127" -W "https://imlive.com/swf/genericguestapp.swf" -p "https://imlive.com/flash_sdk/freevideochatguest.aspx?hostnick=greeneyesgirl&roomid=10" -y "coolvisionrtmp3_greeneyesgirl" -o "greeneyesgirl_2017-03-29_01-09-00.flv"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting Live Stream
1157.213 kB / 1806.44 sec
```
______________________________________________________________________________________________________

RTMPDUMP from:

https://github.com/K-S-V/Scripts/releases/download/v2.4/rtmpdump-2.4.zip
```
C:\>rtmpdump -v -r "rtmp://926-f70bcbc608.c.hibcdn.net/live" -a "live" -f "WIN 25,0,0,127" -W "https://imlive.com/swf/genericguestapp.swf" -p "https://imlive.com/flash_sdk/freevideochatguest.aspx?hostnick=greeneyesgirl&roomid=10" -y "coolvisionrtmp3_greeneyesgirl" -o "greeneyesgirl_2017-03-29_01-11-26.flv"
RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting Live Stream
830.071 kB / 1946.74 sec
```

**Comment by beardypig** [comment]
What's the difference between the first two requests using the bundled `rtmpdump`?

**Comment by johnthecracker** [comment]
That was all one request.

First one failed, next one started and get stuck.

I pasted it here as I copied it from CMD window, here it looks like 2 things, but it is one.

It does not look the same here today as I pasted it yesterday, yesterday weas all one request
and today it is somehow edited by who knows who or what so it looks like 2 different requests.

**Comment by johnthecracker** [comment]
Here is batch file I ran:


@set model=greeneyesgirl
@title IMLIVE %model%
:start
@FOR /f %%b IN ('DT') DO @set d=%%b

rtmpdump -v -r "rtmp://926-f70bcbc608.c.hibcdn.net/live" ^
-a "live" ^
-f "WIN 25,0,0,127" ^
-W "https://imlive.com/swf/genericguestapp.swf" ^
-p "https://imlive.com/flash_sdk/freevideochatguest.aspx?hostnick=%model%&roomid=10" ^
-y "coolvisionrtmp3_%model%" ^
-o "%model%_%d%.flv"

@goto start

**Comment by johnthecracker** [comment]
Looking at this:

Starting Live Stream
830.071 kB / 1946.74 sec

says how much is downloaded in what time.

Comparing the same thing from 3 different tests, shows the difference.

**Comment by beardypig** [comment]
Got it, thanks for clarifying @johnthecracker. I don't see any reason _not_ to include a more up-to-date/compatible version of `rtmpdump` with the `streamlink` installer. Other people might have different opinions, let's see :) @gravyboat? @bastimeyer?

**Comment by johnthecracker** [comment]
KSV distro may be better option than ZERANOE.

ZERANOE fails on CHATURBATE.


KSV:


C:\>rtmpdump -v -r "rtmp://edge56.stream.highwebmedia.com/live-edge" -a "live-edge" -f "WIN WIN 23,0,0,207" -W "https://
chaturbate.com/static/flash/CBV_2p650.swf" -p "https://chaturbate.com/ginna_xx/" -C S:pauld8 -C S:ginna_xx -C S:2.650 -C
 S:pbkdf2_sha256$24000$NuzrMx7Kj36T$p41r2tfgSRVGvcclVaHW1Qm1Lq3MJMuB5wPSfoMfpMw= -C S:504c1b6370b64935b3438b040614458195
e506e5297070643b54f74268ac3fbf -y "mp4:rtmp://origin19.stream.highwebmedia.com/live-origin/ginna_xx-sd-c9eedd2cf326e3229
cdf8fb21de6c142c6e9bd0c71da6f6efe83b5cafe324d9b" -o "c:\ginna_xx_2017-03-29_16-48-52.flv"
RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
Starting Live Stream
1356.843 kB / 6.04 sec


ZERANOE:


C:\>rtmpdump -v -r "rtmp://edge56.stream.highwebmedia.com/live-edge" -a "live-edge" -f "WIN WIN 23,0,0,207" -W "https://
chaturbate.com/static/flash/CBV_2p650.swf" -p "https://chaturbate.com/ginna_xx/" -C S:pauld8 -C S:ginna_xx -C S:2.650 -C
 S:pbkdf2_sha256$24000$NuzrMx7Kj36T$p41r2tfgSRVGvcclVaHW1Qm1Lq3MJMuB5wPSfoMfpMw= -C S:504c1b6370b64935b3438b040614458195
e506e5297070643b54f74268ac3fbf -y "mp4:rtmp://origin19.stream.highwebmedia.com/live-origin/ginna_xx-sd-c9eedd2cf326e3229
cdf8fb21de6c142c6e9bd0c71da6f6efe83b5cafe324d9b" -o "c:\ginna_xx_2017-03-29_16-49-55.flv"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.Failed

**Comment by gravyboat** [comment]
@beardypig Honestly both of these look shady to me in terms of support and openness. k-s-v hasn't pushed a commit in nearly a year to any of their code. The other one is from 2013, and they don't have any details for the source. To me it's not really worth it so people can download content from flash based cam sites and a few filmon addresses (our tool is primarily for streaming, not downloading, plus screw flash support, let it die).

**Comment by beardypig** [comment]
Fair enough @gravyboat. People can use KSV's `rtmpdump` if they want to watch those streams, as is suggested in the docs already :)

**Comment by gravyboat** [comment]
If anyone else has has reasoning I'm open to discussing it, but since we let people use whatever version they want it's not a huge priority to me. Also I thought you were on vacation @beardypig? Please stop reviewing the repo and go back to your vacation!

**Comment by johnthecracker** [comment]
This is like Windows XP, say that 5% of websites still use RTMP.

One of them is vaughnlive.com ( fox news ).

If small improvement that could be made is not worth the effort, let's close this.

**Comment by gravyboat** [comment]
Cool, thanks for understanding @johnthecracker!
