### ISSUE TITLE
Support for Gathering Twitch VOD ID once a stream is live

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#742]
- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

Let's say someone uses the streamlink option to download a video live from someones username, e.g twitch.tv/twitch

When the stream goes live, I want to be able to get the VOD ID (and pipe that to a text file, but this can be done with bash), as soon as it is possible for it to be determined. 

Thanks

**Comment by beardypig** [comment]
_I_ think this is beyond the scope of streamlink. @gravyboat @bastimeyer got an opinion?

**Comment by bastimeyer** [comment]
Yeah, this has pretty much nothing to do with the intended purpose of Streamlink.

If you want to find a specific VOD of a Twitch channel, then check the Twitch API by using curl, etc, and write a script that downloads the VOD via Streamlink as soon as it is available.
https://dev.twitch.tv/docs/v5/reference/channels/#get-channel-videos

**Comment by gravyboat** [comment]
I agree that this is outside of scope. It would be pretty easy to write a little bash script up that opens the stream then hits the api if that succeeds. Marking as out of scope and closing.
