### ISSUE TITLE
Ustream watch more than 30 seconds will stop.

### ISSUE THREAD

**Issue by Andy8r0X** [streamlink/streamlink#747]
----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
I have upgraded the new UStream plugin.
https://raw.githubusercontent.com/beardypig/streamlink/c3b57a2f6c9086fe27ebd9faff7cd285e080cf06/src/streamlink/plugins/ustreamtv.py
But when I see more than 30 seconds will stop.

### Expected / Actual behavior
Streams are protected by timestamp json.
http://socialstream.ustream.tv/socialstream/get.json/23113057/timeslice/{unixtimestamp}/10?jsoncallback=sscb&networks=ustream

### Reproduction steps / Stream URLs to test
 ```
streamlink http://www.ustream.tv/channel/suWQAFCPUkx 1080p
 [cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/suWQAFCPUkx
 [cli][info] Available streams: 1080p (best, worst)
 [cli][info] Opening stream: 1080p (hls)
 [cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"`
 [stream.hls][warning] Failed to reload playlist: Unable to open URL: https://c74
2ece7-lp-omega.ums.ustream.tv/playlist/channel/23113057/1/playlist.m3u8?token=61
83394_1491002830405&appType=11&appVersion=2&chunkingType=improved&sgn=47179032d3
8412a54bc4905b53b5da4331cc0ab3&cdnHost=uhsakamai-a.akamaihd.net/ (403 Client Err
or: Forbidden for url: https://c742ece7-lp-omega.ums.ustream.tv/playlist/channel
/23113057/1/playlist.m3u8?token=6183394_1491002830405&appType=11&appVersion=2&ch
unkingType=improved&sgn=47179032d38412a54bc4905b53b5da4331cc0ab3&cdnHost=uhsakam
ai-a.akamaihd.net/)
```

```
C:\>streamlink http://www.ustream.tv/channel/suWQAFCPUkx 1080p -o C:\test.ts
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/channel/suWQAFCPUkx
[cli][info] Available streams: 1080p (worst, best)
[cli][info] Opening stream: 1080p (hls)
[download][test.mkv] Written 29.1 MB (26s @ 984.0 KB/s)                        
[stream.hls][warning] Failed to reload playlist: Unable to open URL: https://c742
ecf7-lp-omega.ums.ustream.tv/playlist/channel/23113057/1/playlist.m3u8?token=615
4405_1491003037626&appType=11&appVersion=2&chunkingType=improved&sgn=303d55ca9f8
1f0fad073eae7cb94fee12d5721ab&cdnHost=uhsakamai-a.akamaihd.net/ (403 Client Erro
r: Forbidden for url: https://c742ecf7-lp-omega.ums.ustream.tv/playlist/channel/
23113057/1/playlist.m3u8?token=6154405_1491003037626&appType=11&appVersion=2&chu
nkingType=improved&sgn=303d55ca9f81f0fad073eae7cb94fee12d5721ab&cdnHost=uhsakama
i-a.akamaihd.net/)
```

### Environment details (operating system, python version, etc.)
Windows XP, Python 3.4.0

### Comments, logs, screenshots, etc.
Stream source site: http://www.news520.net/dantv.html
https://www.ustream.tv/embed/23113057?html5ui

**Comment by beardypig** [comment]
I'll take a look. There seem to be a few variations with the embedded streams. Probably in this case they update the playlist URL via the websocket/polling API.

**Comment by beardypig** [comment]
Looks like you just gotta stay connected/polling the API for the stream URL to stay valid. I'm updating the plugin, and I will post the URL to the new `py` file once I'm done testing. Hopefully it'll be ready for a PR soon.

**Comment by beardypig** [comment]
This is the latest greatest [ustreamtv.py](https://raw.githubusercontent.com/beardypig/streamlink/ustreamnew/src/streamlink/plugins/ustreamtv.py) file. 

It should work using any player mode, including `--player-passthrough hls`, however the URL generated by `--stream-url` will expire in 30 seconds as `streamlink` is needed to keep the polling the API to keep the URL valid.

**Comment by Andy8r0X** [comment]
Thank you very much!

**Comment by gravyboat** [comment]
Closing this since #754 was merged.
