### ISSUE TITLE
liveedu.tv usage

### ISSUE THREAD

**Issue by RuKeBo** [streamlink/streamlink#750]
I am not sure if I am using the syntax for the liveedu.tv plugin wrong or not but I get "no playable stream found" for any stream I try to view.

An example stream would be:
https://www.liveedu.tv/learntoprogram/RdeQa-javascript-fundamentals/ZB5w3-javascript-fundamentals-2/

Command I am using:
call streamlink https://www.liveedu.tv/learntoprogram/RdeQa-javascript-fundamentals/ZB5w3-javascript-fundamentals-2/ best

But it does this for any stream I try so wondering if it is broke or I am doing something wrong.

Thanks,

Russell

**Comment by beardypig** [comment]
I don't think `livedu.tv` is a supported site. We'd need a plugin to support the site.

**Comment by johnthecracker** [comment]
Works like this.

Thank you for good link, I should be watching that types of video.

C:\>streamlink "hlsvariant://https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/learntoprogram-1435863787.mp4/pla
ylist.m3u8?t=anonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40xEQx4hxTBT1UP70GPw" worst
[cli][info] Found matching plugin stream for URL hlsvariant://https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/
learntoprogram-1435863787.mp4/playlist.m3u8?t=anonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40
xEQx4hxTBT1UP70GPw
[cli][info] Available streams: 720p (best, worst)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe

**Comment by RuKeBo** [comment]
It believe it is the new "livecodingtv.py" plugin.

That works but where did you get that URL?

**Comment by johnthecracker** [comment]
You get m3u8 with the sniffer. The simplest one is firefox extension "HLS stream detector".

My VLC is latest VLC nightly:

vlc-3.0.0-20170331-0310-git-win32.7z

http://nightlies.videolan.org/build/win32/last/

This VLC can play m3u8 on its own ( no streamlink ).

I tried to save it with FFmpeg, came half the way and crushed.

ffmpeg-3.2.4-win64-static.zip, Zeranoe one, not Streamlink FFmpeg.

Youtube-dl saves it with this argument:

youtube-dl.exe -v -F --no-check-certificate %url%

playlist-playlist.m3u8t=anonymous -learntoprogram-1435863787_81.151.111.mp4

https://yt-dl.org/latest/youtube-dl.exe

**Comment by johnthecracker** [comment]
In batch files in windows argument looks different than in CMD window.

You use double quotes if there are empty spaces, but sometimes this is not enough.

This is because some special characters have to be typed 2 times in batch file, 
and then you see only one character in CMD window.

For example, empty spaces are not allowed in FFmpeg arguments, and where is empty space in 
batch file you replace it with %%20, in CMD window you see %20.

You know that you got it right if you see command "as is" in CMD window.

http://www.robvanderwoude.com/escapechars.php

If you post your command that didn't work here, we might find out why it didn't work.

**Comment by johnthecracker** [comment]
In batch files some special characters have to be typed 2 times, and than you see them on command line
as one character, "as is"

Forr example, % you see in CMD window has to be typed %% in batch file.

http://www.robvanderwoude.com/escapechars.php

**Comment by beardypig** [comment]
@RuKeBo you're right (need to update the plugins list!). It does seem to be broken, I'll fix it tomorrow unless someone does it before :-)

**Comment by johnthecracker** [comment]
Streamlink downloads this 1hr video in 7.44 minutes:

`C:\MISC\STREAMLINK>streamlink "hlsvariant://https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/learntoprogram-143
5863787.mp4/playlist.m3u8?t=anonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40xEQx4hxTBT1UP70GPw
" worst -o javascript-fundamentals-2.mp4
[cli][info] Found matching plugin stream for URL hlsvariant://https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/
learntoprogram-1435863787.mp4/playlist.m3u8?t=anonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40
xEQx4hxTBT1UP70GPw
[cli][info] Available streams: 720p (best, worst)
[cli][info] Opening stream: 720p (hls)
[download][..ript-fundamentals-2.mp4] Written 568.5 MB (7m42s @ 1.2 MB/s)
[cli][info] Stream ended
[cli][info] Closing currently open stream...

C:\MISC\STREAMLINK>pause
Press any key to continue . . .
`

Zeranoe FFmpeg comes to  111,445 KB and stops and hangs.

Congratulations to Streamlink this time.

This is Zeranoe FFmpeg:

`
C:\>ffmpeg -i "https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/learntoprogram-1435863787.mp4/playlist.m3u8?t=a
nonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40xEQx4hxTBT1UP70GPw" -c copy javascript-fundamen
tals-2.mp4
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-
avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libb
luray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-l
ibmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libope
njpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enabl
e-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable
-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zli
b
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, hls,applehttp, from 'https://eumedia12.livecoding.tv/vod/_definst_/mp4:vod2_us/learntoprogram-1435863787.mp4/p
laylist.m3u8?t=anonymous%3Alearntoprogram-1435863787%3A81.151.111.49%3A1cuRNo%3AOSl_KGI40xEQx4hxTBT1UP70GPw':
  Duration: 00:59:30.88, start: 0.000000, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 2042789
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 2042789
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      variant_bitrate : 2042789
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 2042789
Output #0, mp4, to 'javascript-fundamentals-2.mp4':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (High) ([33][0][0][0] / 0x0021), yuv420p(tv, bt709), 1280x720, q=2-31, 30 tbr, 90k tbn, 90k
 tbc
    Metadata:
      variant_bitrate : 2042789
    Stream #0:1: Audio: aac (LC) ([64][0][0][0] / 0x0040), 44100 Hz, stereo
    Metadata:
      variant_bitrate : 2042789
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:2 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=21572 fps=184 q=-1.0 size=  111245kB time=00:12:01.46 bitrate=1263.1kbits/s speed=6.17x`
