### ISSUE TITLE
Default Stream quality to best? (documentation improvement)

### ISSUE THREAD

**Issue by Germandrummer92** [streamlink/streamlink#751]
### Checklist

- [ ] This is a bug report.
- [ ] This is a plugin request.
- [x] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
I personally use streamlink for all my stream needs (mostly twitch), so I type a lot of streamlink commands into the terminal so any less typing would be appreciated. 

This would only require a minimal change (see [my fork](https://github.com/streamlink/streamlink/compare/master...Germandrummer92:master)) and would as far as I can see it not break anything, as even if someone just wanted to print the available qualities they are still printed and you can just exit the source stream immediately as you will most likely type into the same terminal window again.

If someone actually wants the behavior of just printing the stream qualities I could implement a separate option for that although I'm not sure anyone actually uses that.

### Expected / Actual behavior

`streamlink twitch.tv/pgl_dota`

defaults to
`streamlink twitch.tv/pgl_dota best` 
instead of just printing the stream qualities

Let me know if this makes sense and I would open a pull request with my one-line change!

**Comment by skulblakka** [comment]
You can already specify a default quality. See [--default-stream](https://streamlink.github.io/cli.html#cmdoption-default-stream). Just add it to your config file and you wont have to enter a quality every time.

**Comment by gravyboat** [comment]
As @skulblakka this is something users can set via their config file. We don't want to default to `best` without a user specifying it as `best` typically requires a large amount of bandwidth which may negatively impact the end user if they have any sort of limitation or cap in place. I'm going to close this out for now since it's easy to work around via existing settings.

**Comment by gravyboat** [comment]
I went through the docs related to --default-stream and I think we could definitely improve them. They're super bare bones right now and not very useful. It doesn't really explain how to set ti and use it.

**Comment by tp0** [comment]
> so I type a lot of streamlink commands into the terminal so any less typing would be appreciated.

I guess the --default-stream option is the solution already, but if you want to shorten the command even more, use aliases/functions (bash? you said terminal).

```
function sl() {
	streamlink "$1" best
	}
```

I use many functions like that for diferent purposes and many different sites. I'd go insane by typing them all the time or even just copy-pasting from a text file.

**Comment by bastimeyer** [comment]
Your function is not ideal and only takes one argument. This is a better one:

```bash
function sl() {
	streamlink --default-stream best "$@"
}
```

**Comment by Germandrummer92** [comment]
Actually, if you put the default-stream into the streamlinkrc you don't have to retype the argument for every function you define (if you're like me and have different ones for example and are even too lazy to type the argument in your zshrc/bashrc :smile: ).

Also, for completeness sake here is the function I use. It also autocompletes my stream names to twitch if it doesnt include a "/" (e.g. any other url will just be passed through).
`wt() {
     url="$1"
     if [[ "$url" =~ ".*twitch.*" || "$url" =~ ".*/.*" ]]; then
         streamlink "$url" "${@:2}"
     else
         streamlink "twitch.tv/$url" "${@:2}"
     fi
 }`

This means, that
`wt twitch.tv/ppd` and
`wt ppd` will work.

Thanks for all the help though :+1:
