### ISSUE TITLE
Fails to open pycrypto

### ISSUE THREAD

**Issue by Gfurst** [streamlink/streamlink#755]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

Streamlink on Arch, fails to open even thought package dependencies are met.
Version 0.3.0-3 from the official Arch repos.

### Reproduction steps / Stream URLs to test

Opening a stream, happens on all I've tried, not twitch exclusive:
 ```
guiu@guidesk ~ % streamlink -p mpv twitch.tv/yogscast                                                                                                                                                                                         :(
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycrypto' distribution was not found and is required by streamlink
```

### Environment details (operating system, python version, etc.)

Expected package dependencies are installed, at least related to the error:
```
local/python-pycryptodome 3.4.3-3
    Collection of cryptographic algorithms and protocols, implemented for use from Python 3.
local/python-pycryptodomex 3.4.5-2
    A self-contained Python package of low-level cryptographic primitives
local/python2-crypto 2.6.1-5
    Collection of cryptographic algorithms and protocols, implemented for use from Python 2.
local/python2-pycryptodomex 3.4.5-2
    A self-contained Python package of low-level cryptographic primitives
```
also:
```
local/python-pycountry 17.1.8-1
    ISO country, subdivision, language, currency and script definitions and their translations
```
Also tried suggested env variable to use pycrypto, doesn't help either way.

**Comment by mmetak** [comment]
Version in arch community repo is `streamlink 0.4.0-2` and uses `python-crypto`.
If you want to use official package from community repo then first remove `python-pycryptodome` package and install `python-crypto` to replace it.

**Comment by Gfurst** [comment]
You're right, for some reason my package wasn't updating (guess stuck on old aur version), and there seems to be an issue in migrating from the aur package where cryptodome doesn't remove. Doing it manually seems to do the trick. Was able to build the new one from aur as well.

**Comment by Brottweiler** [comment]
Just want to add my solution where I had this error, I couldn't remove `python-pycryptodome` with pacman for some reason, so I did `-Rs` on streamlink, to remove all dependencies including `python-pycryptodome`, and then I installed streamlink again. Works.
