### ISSUE TITLE
Plugin request(s): Deutsche Welle, Al Jazeera

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#756]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
If possible, a link for two of the more famous news TV channes - Deutsche Welle's live TV and Al Jazeera.
The tricky part is that the former uses this link (http://www.dw.com/en/media-center/live-tv/s-100825) but you can switch between languages that are on the same link for some reason. Al Jazeera can be found on this link - http://www.aljazeera.com/live/. Both should be available worldwide.

**Comment by gravyboat** [comment]
Closing since #758 and #759 are merged.
