### ISSUE TITLE
Bug: Youtube Live never plays

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#757]
### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
When a youtube live link (i.e. sky news for instance) is initiated, I just get 1x picture and nothing else.

### Expected / Actual behavior
When I load it, I should hear audio and see video, not just the one "screenshot" and no video or audio.

### Reproduction steps / Stream URLs to test

1. Run "https://www.youtube.com/watch?v=y60wDzZt8yg" in any quality
2. Wait for VLC to start up
3. Experience bug

### Environment details (operating system, python version, etc.)

Windows 7 64-bit, nightly version from 23rd of March 2017.

### Comments, logs, screenshots, etc.
This might be a very specific bug only for me, but I can't be sure, so I decided to check anyway.

**Comment by beardypig** [comment]
Works for me. Have you tried a different player, or tried using VLC3 beta? - some YouTube stream don't work with VLC2.

**Comment by roshavagarga** [comment]
@beardypig - you were right. MPC-HC works, so does VLC 3 Nightly. I guess the 2.2.4 version of VLC has a problem with this stream (both 32 bit and 64 bit versions). Maybe add an automatic warning when opening a youtube livestream? 

Example:
Found plugin ...
Available streams...
Opening stream...
Starting player...
WARNING: If the Youtube Live video does not play, please consider using another player or upgrading to a newer version of your current one.

**Comment by bastimeyer** [comment]
This is already documented here:
https://streamlink.github.io/players.html#youtube-live-does-not-work-with-vlc

**Comment by beardypig** [comment]
Going to close this as it is a known issue and documented, as @bastimeyer pointed out.

**Comment by gravyboat** [comment]
We might want to update the docs so the installation guide has a link to known issues, and I would suggest we do the same for releases as well. This question has come up at least half a dozen times in the last month or two, clearly our documentation is failing somewhere.

**Comment by bastimeyer** [comment]
Good idea. Maybe the issue template should also be updated. There's some stuff missing like the used Streamlink version or explicit stream URLs for plugin requests.
