### ISSUE TITLE
Possible to add plugin for Viz.com/watch?

### ISSUE THREAD

**Issue by Truanifan** [streamlink/streamlink#764]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

I was wondering if it's possible to add a plugin for https://www.viz.com/watch like there are plugins for Funimation and Daisuki? I'm not sure how their player works exactly so I don't know how possible it is.

**Comment by beardypig** [comment]
Seems all the videos are provided by Hulu. As I'm not in the US it is hard to say if it possible to support these videos (Hulu blocks most proxies). I believe that Hulu use DRM so that reduces the likelihood of streamlink being able to support Viz.

**Comment by ghajini** [comment]
Node script by jspenguin 2017 here
`https://github.com/jspenguin2017/uBlockProtector/issues/398`



//Temporary DNS redirector
"use strict";

/**
 * Custom DNS servers.
 * @const {Array.<DNSServer>}
 */
const DNS_SERVERS = ["185.37.37.37", "185.37.39.39"]; //https://unlocator.com/

/**
 * Load modules.
 * @const {Module}
 */
const http = require("http");
const https = require("https");
const url = require("url");
const dns = require("dns");
const net = require("net");

/**
 * Regular expression to test if a string is filled with digits.
 * @const {RegExp}
 */
const reIsAllDigits = /^\d+$/;

//Set DNS server
dns.setServers(DNS_SERVERS);

//Start server
http.createServer().listen(12345).on("request", (req, res) => {
    //HTTP requests do not go though custom DNS for now, and insecure WebSocket does not work
    console.log("REQUEST", req.url);

    let option;
    try {
        option = url.parse(req.url);
    } catch (err) {
        res.writeHead(400, "Bad Request");
        res.end();
        return;
    }

    if (option.protocol !== "http:" && option.protocol !== "https:") {
        res.writeHead(400, "Bad Request");
        res.end();
        return;
    }

    delete req.headers["proxy-authorization"];
    if (req.headers["proxy-connection"]) {
        req.headers["connection"] = req.headers["proxy-connection"];
        delete req.headers["proxy-connection"];
    }

    option.method = req.method;
    option.headers = req.headers;

    const remote = (option.protocol === "http:" ? http : https).request(option, (rres) => {
        res.writeHead(rres.statusCode, rres.statusMessage, rres.headers);
        rres.pipe(res);
    });
    req.pipe(remote);

    remote.on("error", () => {
        res.destroy();
    });
    req.on("error", () => {
        remote.destroy();
    });
}).on("connect", (req, socket, head) => {
    //Everything works as expected in HTTPS mode
    console.log("CONNECT", req.url);

    let port = 443;
    let domain = "";
    {
        let parts = req.url.split(':');
        if (reIsAllDigits.test(parts[parts.length - 1])) {
            port = parseInt(parts.pop());
            if (port < 0 || port > 65535) {
                port = 443;
            }
        }
        domain = parts.join(':');
    }

    dns.resolve(domain, (err, address) => {
        let ip;
        if (err) {
            ip = domain;
        } else {
            ip = address[0];
            console.log(`\t${domain} -> ${ip}`);
        }

        const remote = net.connect({
            host: ip,
            port: port,
            servername: domain,
        }, () => {
            socket.write("HTTP/" + req.httpVersion + " 200 Connection Established\r\n");
            if (req.headers["proxy-connection"] === "keep-alive") {
                socket.write("Connection: keep-alive\r\n");
            }
            socket.write("\r\n");

            remote.write(head);

            socket.pipe(remote);
            remote.pipe(socket);
        });

        remote.on("error", () => {
            socket.destroy();
        });
        socket.on("error", () => {
            remote.destroy();
        });
    });
});

//Start up log
console.log("Server started on http://localhost:12345/");



Start it and use http://localhost:12345/ as proxy.

**Comment by ghajini** [comment]
Here for develepers see jspenguin2017 comment( last 2nd) about node.js ,it may solve your proxy detection problem....
`https://github.com/jspenguin2017/uBlockProtector/issues/398`

**Comment by back-to** [comment]
Closing: **DRM**
