### ISSUE TITLE
wiiz.tv plugin

### ISSUE THREAD

**Issue by karlo2105** [streamlink/streamlink#765]
### Checklist

- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

wiiz.tv is a platform which broadcasts live channels sorted by countries. 

### Expected / Actual behavior

Plugin shall allow to generate cookies in order to launch channel. 

### Reproduction steps / Stream URLs to test

LCI 
----

`http://www.wiiz.tv/regarder-lci.php`
```
streamlink "hlsvariant://http://167.114.65.183:8080/lci/index.m3u8?token=5bfaddd94979af9c4bd2b3efcf68cda1f6699330-2f50f1041979
836263de9e1818d3185a-1491397761-1491383361"  best
[cli][info] Found matching plugin stream for URL hlsvariant://http://167.114.65.
183:8080/lci/index.m3u8?token=5bfaddd94979af9c4bd2b3efcf68cda1f6699330-2f50f1041
979836263de9e1818d3185a-1491397761-1491383361
[cli][info] Available streams: 540p (worst, best)
[cli][info] Opening stream: 540p (hls)
[cli][info] Starting player: C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Environment details (operating system, python version, etc.)

W7 Pro/Streamlink portable

### Comments, logs, screenshots, etc.

Channels are not geolocked.

**Comment by beardypig** [comment]
Bit of a mixed bag, some of the channels are embedded filmon streams, some are HLS streams, some are embedded hds streams. Mostly check the French, Spanish, US, and UK streams.

**Comment by karlo2105** [comment]
Yeah indeed there are some embedded channels from official or third party sources but most sources come from wiiz.tv.

**Comment by beardypig** [comment]
Wanna test out [wiiztv.py](https://raw.githubusercontent.com/beardypig/streamlink/wiiz/src/streamlink/plugins/wiiztv.py)? :)

**Comment by karlo2105** [comment]
Sure ;)

**Comment by karlo2105** [comment]
After review, I dig up two issues related to HDS on two different channels. On both channels HLS works. 

1. Failed to update boostrap
-------------------------------

```
streamlink "http://www.wiiz.tv/la-2.php" best
[cli][info] Found matching plugin wiiztv for URL http://www.wiiz.tv/la-2.php
http://167.114.103.31:8080/la2/manifest.f4m?dvr=false&token=f73a8db180c55d2d2c6b
95d38744f1151ab7cb4c-27a317060cf77a182e04c54e40d7c20f-1491409073-1491394673
[cli][info] Available streams: 576p (worst), 2320k (best)
[cli][info] Opening stream: 2320k (hds)
[cli][info] Starting player: C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc
[stream.hds][warning] Failed to update bootstrap: Unable to open URL: http://167
.114.103.31:8080/la2/bootstrap?token=f73a8db180c55d2d2c6b95d38744f1151ab7cb4c-27
a317060cf77a182e04c54e40d7c20f-1491409073-1491394673 (('Connection aborted.', Re
moteDisconnected('Remote end closed connection without response',)))
```

2. Failed to open fragment 1-23325
--------------------------------------

```
streamlink "http://www.wiiz.tv/mega.php" best
[cli][info] Found matching plugin wiiztv for URL http://www.wiiz.tv/mega.php
http://167.114.209.157:8080/mega/manifest.f4m?dvr=false&token=385c5aaa7676e25d52
631bb5ba6d4fce7b41e957-626a052ade89dbbb78a50c6e5cd67c34-1491409762-1491395362
[cli][info] Available streams: 576p (worst), 3373k (best)
[cli][info] Opening stream: 3373k (hds)
[stream.hds][error] Failed to open fragment 1-23325: Unable to open URL: http://
167.114.209.157:8080/mega/hds/token=385c5aaa7676e25d52631bb5ba6d4fce7b41e957-626
a052ade89dbbb78a50c6e5cd67c34-1491409762-1491395362/tracks-v1a1/Seg1-Frag23325 (
404 Client Error: Not Found for url: http://167.114.209.157:8080/mega/hds/token=
385c5aaa7676e25d52631bb5ba6d4fce7b41e957-626a052ade89dbbb78a50c6e5cd67c34-149140
9762-1491395362/tracks-v1a1/Seg1-Frag23325)

```

**Comment by melmorabity** [comment]
```
$ streamlink "http://www.wiiz.tv/mega.php" best
[cli][info] Found matching plugin wiiztv for URL http://www.wiiz.tv/mega.php
error: Unable to open URL: http://192.99.47.139:8080/mega/index.m3u8?token=0752fd2bcd10923e81a2c0d850419309b08b497d-c70d379896f1d2b58c6f4117b6005fe4-1493078480-1493064080 (403 Client Error: Forbidden for url: http://192.99.47.139:8080/mega/index.m3u8?token=0752fd2bcd10923e81a2c0d850419309b08b497d-c70d379896f1d2b58c6f4117b6005fe4-1493078480-1493064080)
```

By adding a Referer to headers when retrieving HLS streams (see https://github.com/melmorabity/streamlink/commit/8d580c0c1f6380c3a0f7700cdcff780f7ee5e7a9):
```
$ streamlink "http://www.wiiz.tv/mega.php" best
[cli][info] Found matching plugin wiiztv for URL http://www.wiiz.tv/mega.php
[cli][info] Available streams: 576p (worst, best)
[cli][info] Opening stream: 576p (hls)
[cli][info] Starting player: ffplay
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
http://www.wiiz.tv/la-2.php is working also.

By the way it looks like there's no more embed streams (for most of the channels I tested).

**Comment by back-to** [comment]
an old issue

> Yeah indeed there are some embedded channels from official or third party sources but on French speaking TV most sources come from wiiz.tv.

I only see embed sources now, some use wrong embedded URLs.

**closing** as the direct website can simply be used instead of a 3rd party.
