### ISSUE TITLE
Chaturbate plugin down, no stream found

### ISSUE THREAD

**Issue by kyle1058** [streamlink/streamlink#767]
Chaturbate plugin down , i have tried the latest compilation of streamlink as well as the modified livestreamer plugin from January when the hlstream changed.

*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Stream URLs to test

1. ...
2. ...
3. ...

### Environment details (operating system, python version, etc.)

...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
There are nowhere near enough details in this for us to even begin troubleshooting. https://github.com/streamlink/streamlink/issues/685 is the most recent related report and noted that only some streams have issues. You'll need to provide more details related to specific URLs, what your setup looks like (verbose Streamlink output on your command, details regarding your player, OS, etc.) before we can review anything since as far as I'm aware from that previous issue the plugin works fine minus certain streams.

**Comment by kinprize** [comment]
1 hour ago all records with chaturbate stopped. Can be changed the thread of the stream. RegEx in the plugin does not work.

**Comment by back-to** [comment]
They changed it two weeks ago, but they changed it back after ~1 day.

chrippa/livestreamer#1600

Now they changed it again,
maybe it's just a test, it could be possible that they will change it back again tomorrow.

---

you can try this `chaturbate.py` it should work for now.

https://raw.githubusercontent.com/back-to/streamlink/dc95ccf7cf7392d59a4adcce3b5fee6e27e86fdf/src/streamlink/plugins/chaturbate.py

---

https://github.com/back-to/streamlink/commit/dc95ccf7cf7392d59a4adcce3b5fee6e27e86fdf

**Comment by kinprize** [comment]
Thanks. It works:

https://raw.githubusercontent.com/back-to/streamlink/dc95ccf7cf7392d59a4adcce3b5fee6e27e86fdf/src/streamlink/plugins/chaturbate.py

**Comment by kyle1058** [comment]
Both work fantastic. I haven't done enough python coding to really explore much of what wasn't working, simply seeing a stream not found. The livestreamer python line change (line 8) in the first post at that chrippa/livestreamer#1600 link does work great, as well as the streamlink chaturbate.py file. Also, changing the streamlink file by editing the "from streamlink" import calls at the top to "from livestreamer" works great as well. There are many differences and additions in the streamlink one, but both technically work right now that i can see.  Thanks again!

**Comment by mashken** [comment]
When I replace the existing .py file I get the following error:
`Traceback (most recent call last):
  File "C:\Program Files (x86)\Streamlink\bin\streamlink-script.py", line 15, in <module>
    main()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 1010, in main
    handle_url()
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 479, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink_cli\main.py", line 391, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 325, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugin\plugin.py", line 240, in streams
    ostreams = list(ostreams)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\plugins\chaturbate.py", line 31, in _get_streams
    CSRFToken = str(uuid.uuid4().get_hex().upper()[0:32])
AttributeError: 'UUID' object has no attribute 'get_hex'`

**Comment by karlo2105** [comment]
You shall rename all "livestreamer" into "streamlink" and save it into chaturbate.py.

**Comment by mashken** [comment]
I am using the Streamlink file, there are no mentions of livestreamer in that

**Comment by karlo2105** [comment]
Uninstall and try with the latest nightly.

**Comment by mashken** [comment]
Replaced line 8 in file with this: `_playlist_url_re = re.compile("html \+= \"src='(?P<url>[^']+)\?")` which works

**Comment by mltr15** [comment]
not working with latest nightly.

**Comment by back-to** [comment]
Fixed the `AttributeError: 'UUID' object has no attribute 'get_hex'`

It should work for **python 3.5** now

https://raw.githubusercontent.com/back-to/streamlink/277d064051e9166f61df315ae04cc71011a61e98/src/streamlink/plugins/chaturbate.py

**Comment by Krendall** [comment]
Working for me. Thank you so much!

**Comment by makedir** [comment]
Nightly not working, where do I put that py file into so it works?

**Comment by compaqhp** [comment]
working for me too. thanks much!

**Comment by Fnarb** [comment]
Initially it works fine, but there seems to be an issue with the playlist generation when it times out.

I keep getting errors similar to:
stream.hls][warning] Failed to reload playlist: Unable to open URL: https://edge34.stream.highwebmedia.com/live-edge/redacted-acbc80345f073505e343500497374461665e017143dada68e4eb9344c952e976_fast_aac/chunklist_w1086126634.m3u8?rp=783f2c45190f2f857dc94fa48be5c4815f107a174f8c796d88bbdeebeae91296&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1491633904%2C%22sig%22%3A%225c6ac4babaa65e71d46d63ec492af8fc21c6453f5263fffa7e6a9835df87ceaf%22%2C%22room%22%3A%22redacted%22%7D (404 Client Error: Not Found for url: https://edge34.stream.highwebmedia.com/live-edge/redacted-sd-acbc80345f073505e343500497374461665e017143dada68e4eb9344c952e976_fast_aac/chunklist_w1086126634.m3u8?rp=783f2c45190f2f857dc94fa48be5c4815f107a174f8c796d88bbdeebeae91296&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1491633904%2C%22sig%22%3A%225c6ac4babaa65e71d46d63ec492af8fc21c6453f5263fffa7e6a9835df87ceaf%22%2C%22room%22%3A%22redacted%22%7D)

**Comment by back-to** [comment]
`[stream.hls][warning] Failed to reload playlist`
well this is not an issue **it's a feature**

if you don't like it, i think it's `--hls-segment-timeout 1` to turn it down
https://streamlink.github.io/cli.html#cmdoption-hls-segment-timeout

**Comment by Fnarb** [comment]
I think you misunderstood. The issue isn't the timeout, it's the fact that it doesn't recover from it. 
As it is, it only seems to load the playlist once, but after a time-out I get errors and it quits. 
This didn't happen previously.

I am no coder but I would hazard a guess that the issue that was corrected in pass one, wasn't corrected for pass 2.

**Comment by Zarkoob** [comment]
Fnarb I think you just need to increase hls-segment-timeout value so it will recover.

**Comment by TVGPlayer** [comment]
Still working for me too. Thanks!!!

**Comment by dswoop** [comment]
getting this error... anyone able to help?

error: Unable to open URL: https://edge15.stream.highwebmedia.com/live-edge/amlst:lucy_robert-ws-65f96fa7e6de57474e26cf860b11a5e5089fcd09a24b8e1320f1de1ba8506c0c_trns_h264/playlist.m3u8?rp=befb789a9e6e87ebc7dfa88054d66152bd06e1b365d8e618f1efb305eee41e76&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%22expire%22%3A1511131086%2C%22sig%22%3A%22046869323a86521779dd1ec3f7a32b52fb99e1cd4bcb61509b10a43892392413%22%2C%22room%22%3A%22lucy_robert%22%7D ([Errno 1] _ssl.c:504: error:14092073:SSL routines:SSL3_GET_SERVER_HELLO:bad packet length)
