### ISSUE TITLE
vaughnlive.tv plugin issue

### ISSUE THREAD

**Issue by c769214** [streamlink/streamlink#768]
- [x] This is a bug report.
- [X] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description
Error Generated :  
error: Unable to validate response text: Minimum length is 3 but value is 1

user@linux:~$ streamlink http://vaughnlive.tv/sherming00 best
[cli][info] Found matching plugin _backup_vaughnlive for URL http://vaughnlive.tv/sherming00
error: Unable to validate response text: Minimum length is 3 but value is 1

**Comment by karlo2105** [comment]
I get static picture with the latest nightlies. 

```
streamlink "http://vaughnlive.tv/sherming00" best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/sherming00
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (rtmp)
[cli][info] Starting player: C:\Users\Ddr\Downloads\VLCPortable\App\vlc\vlc
[cli][info] Player closed
[cli][info] Stream ended
```
[cli][info] Closing currently open stream...

**Comment by beardypig** [comment]
@c769214 You need to install the latest version, if you've already done that make sure you uninstall the old version and reinstall :)
@karlo2105 That stream worked after a couple of tries for me.

**Comment by c769214** [comment]
@karlo2105  the version should be the latest one , streamlink 0.5.0 
@beardypig  usually is the key issue, which vaughnlive always change, i have tried another link (eg: newzviewz) and the same error comes out. 

FYI, I'm currently using Ubuntu

**Comment by gravyboat** [comment]
I'm using Streamlink 0.5.0 on Ubuntu 16 and it works fine for me:
```
streamlink http://vaughnlive.tv/sherming00 best
[cli][info] Found matching plugin vaughnlive for URL http://vaughnlive.tv/sherming00
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (rtmp)
[cli][info] Starting player: /usr/bin/vlc
```

Can you try again with the `-l debug` and `-v` options for more verbose output?

**Comment by mmetak** [comment]
@beardypig @gravyboat Yep, also works fine on arch, both latest stable version 0.5.0 and latest git. I tried all the channels mentioned above and they all play.

**Comment by c769214** [comment]
user@user-Sys:~$ streamlink -l debug http://vaughnlive.tv/sherming00 best
[cli][info] Found matching plugin _backup_vaughnlive for URL http://vaughnlive.tv/sherming00
error: Unable to validate response text: Minimum length is 3 but value is 1

user@user-Sys:~$ streamlink -v http://vaughnlive.tv/sherming00 best
[cli][info] Found matching plugin _backup_vaughnlive for URL http://vaughnlive.tv/sherming00
error: Unable to validate response text: Minimum length is 3 but value is 1

I know , this works fine before but no idea why it changes sudden like this.

**Comment by c769214** [comment]
I found this issue.....

in the /usr/local/lib/python2.7/dist-packages/streamlink/plugins directory 
I have make the backup of the original vaughnlive.py into _backup_vaughnlive.py and install the new vaughnlive.py from github.

But the program will grub the old .py file (that is _backup_vaughnlive.py) 
What I have do is delete all _backup_vaughnlive.* and then the program "know" how to redirect to correct vaughnlive.py file. 

be reminded, need to delete the .py and .pyc file  and install the new .py file from github
