### ISSUE TITLE
Odd behavior with Streamlink and MPC-HC

### ISSUE THREAD

**Issue by Dalonomus** [streamlink/streamlink#769]
- [x] This is a bug report.
- [ ] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

I just recently switched to streamlink from livestreamer mostly so i can get at 60fps YouTube videos.  But Ive been encountering an odd problem with my player of choice (MPC-HC).  As of late when I open a twitch stream that runs at 60fps after about 7 or 8 minutes the frame rate will drop to 30fps and slow the stream down.  This behavior lasts about a minutes then the frame rate jumps up to 90fps till the stream resynces and then drop back to 60fps.  This will happen repeatedly then sometimes just not happen anymore or alternate until I close the stream.  This behavior doesn't happen on streams that run at 30fps at all and if I don't full screen MPC it wont happen either unless I force it be fast forwarding or something silly.  This behavior did not happen for the 2 years that I used Livestreamer at all but now since installing streamlink it happens on livestreamer as well.  To note it doesn't Always happen but it happens most for the time.  Ive had streamlink installed since last Thursday and none of the streams that  watched on the night before via Livestreamer did this. Im Kinda puzzled as to whats causing this so if you guys have any ideas or suggestions I would appreciate it 

### Environment details (operating system, python version, etc.)

This machine is dirt old
AMD Athlon 62 4200+ 2.2 ghz
Windows 7 Ultimate

**Comment by beardypig** [comment]
I would guess it is something to do with MPC-HC rather than Streamlink/Livestreamer, have you tried a different player? If it only happens when you fullscreen the video then it could be something to do with your graphic card driver/settings, do you have the most up-to-date drivers?

**Comment by Dalonomus** [comment]
VLC isnt affected but it does weird stuff like strange colour blocks will pop up while watching plus playback on vlc has always been choppy.  Like i said this Just started happening on Thursday past when I installed streamlink but ill definitely try to update my drivers.

**Comment by karlo2105** [comment]
Check your CPU Usage in MPC-HC fullscreen. 
CTRL+Shift+ESC to get task manager.

**Comment by Dalonomus** [comment]
Its only 10 percent higher than Windowed and my drivers were  up to date mind you this comp and Grfx card are OLD!!.  To note when its the frames cut down to half it also uses less cpu so ehhhh??

**Comment by karlo2105** [comment]
I have Intel integrated graphic card on Intel® Xeon® Processor E7330 Dual Core with 4 GB RAM.
In full screen only I get choppy picture on 1080p 50fps videos with VLC as 50% of CPU is used, I guess it is related to integrated graphic card then. 
With resized video to fit screen, no choppy at all.

**Comment by Dalonomus** [comment]
No integrated video on this mother board its a gefocre 6600 GT

**Comment by WolfganP** [comment]
To isolate the issue I suggest get a local video at 60fps (longer that 8 minutes to replicate the same conditions, you may use youtube-dl to even use the same source) and play it with VLC and MPC-HC and compare. 
Other problem point may be the interconnection between apps? (ie chocking a system pipe or http buffer)

**Comment by Dalonomus** [comment]
hmm i can snag a 60fps twitch archive a little later and see whats happening but for now sleep beckons. Thanks for the suggestions guys.  Hell ill use the archive of the very stream i was using to test this out when i initially posted.

**Comment by Dalonomus** [comment]
Aright Here's an update.  I grabbed a 60 fps twitch archive and a YouTube track and field video that was recorded at 60fps and tested those out.  Perfectly normal playback for the duration (25 and 32 minutes) on both videos.  So I loaded up a stream that was giving me issues just yesterday and so far after 3 attempts I was unable to replicate the problem.  I even restarted the PC ( i hadn't since the last post) to see if the problem would reappear.  it hasn't.  Solved??  Eh probably not but Ill leave this stream running till they close down for the morning to see if anything happens.  Once again thanks for listening guys.

**Comment by gravyboat** [comment]
@Dalonomus Any update on this? If not I would like to close the issue.

**Comment by Dalonomus** [comment]
yea its not consistent enough for me to pin down but so far it hasn't been popping up so yea lets close.

**Comment by gravyboat** [comment]
Okay thanks @Dalonomus!
