### ISSUE TITLE
a-pac.tv (ustream) ?

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#775]
- [x] This is a plugin request.
- [x] This is a feature request.

### Description

The stream from http://a-pac.tv is from ustream but does not play via streamlink, does this need something extra?

### Reproduction steps / Stream URLs to test

1. ... streamlink http://a-pac.tv
2. ... streamlink http://www.ustream.tv/channel/20848756 best

Thanks.

**Comment by johnthecracker** [comment]
http://a-pac.tv

This is good one.

Somebody might have to write new rtmpdump ( rtmpsuck ) to get rtmp stream.

**Comment by johnthecracker** [comment]
http://a-pac.tv

One step ahead of ImLive.com.

**Comment by unlocKing** [comment]
https://github.com/beardypig/streamlink/blob/a8d2f826a6537b4436f3a1331d320337f854ffe7/src/streamlink/plugins/ustreamtv.py

This only works as:
streamlink http://www.ustream.tv/channel/20848756 best

And not with http://a-pac.tv

Is that correct, or is there a different command for this?

Thanks.

**Comment by beardypig** [comment]
Yes, that's correct. Once the new ustream plugin is merged we can add a little apac wrapper to get the ustream URL.

**Comment by unlocKing** [comment]
@beardypig Thanks dude!

**Comment by back-to** [comment]
already added in #875

**Comment by beardypig** [comment]
Yep, this should be resolved now. Thanks for pointing that out @back-to :-)
