### ISSUE TITLE
Plugin(s) request

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#776]
- [] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [ ] I used the search function to find already opened/closed issues or pull requests.

---

If possible I would welcome the addition of these news channels at any point in time.

1. Bloomberg (English) - https://www.bloomberg.com/live/ - different regional editions available
2. RTE News (English) - http://www.rte.ie/news/player/live/7/
3. CNews (French) - http://www.cnews.fr/direct 
4. Africanews (English, French) - http://www.africanews.com/live/

**Comment by melmorabity** [comment]
Hi,

for CNews, this is actually a Dailymotion stream, supprted by streamlink, and available at http://www.dailymotion.com/video/x3b68jn

**Comment by roshavagarga** [comment]
Hey @melmorabity, thank you for that info :+1: 
You've made my life a whole lot easier.

**Comment by gravyboat** [comment]
Closing since #807 is merged, thanks for the report!

**Comment by roshavagarga** [comment]
@gravyboat Number 2 and 3 are still relatively hard to open unless you know that 3 is a dailymotion stream. Should I start new threads for those separately? :)

**Comment by beardypig** [comment]
@roshavagarga each of these should have their own issue. One plugin request/bug/question per issue please :-)
