### ISSUE TITLE
Twitch Videos do not work

### ISSUE THREAD

**Issue by hodor22** [streamlink/streamlink#782]
- [x] This is a bug report.

### Description
Streamlink cannot parse these kind of URLs form Twitch Viedeos / past broadcasts
example: http://player.twitch.tv/?video=v133805360

### Expected / Actual behavior
Opening VLC player and running the streamvideo

### Reproduction steps / Stream URLs to test
streamlink http://player.twitch.tv/?video=v133805360 best

### Environment details (operating system, python version, etc.)
Win7 SP1 x64, VLC 2.2.4, Streamlink 0.5.0

### logs
error: Unable to open URL: https://api.twitch.tv/kraken/users.json (400 Client Error: Bad Request for url: https://api.twitch.tv/kraken/users.json?as3=t&oauth_t
oken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&login=%3Fvideo%3Dv133805360)

_token was hidden_

**Comment by beardypig** [comment]
Was this a token generated by `livestreamer` or are you a new user? If you were using `livestreamer` before you may have an old token - try updating your token using:
```
streamlink --twitch-oauth-authenticate
```

**Comment by bastimeyer** [comment]
The issue here is that the URL is being interpreted as a regular stream URL (see the login parameter: `login=%3Fvideo%3Dv133805360`).

The VOD URL from above is from Twitch's "popout player" window. The regular URLs work flawlessly:
https://www.twitch.tv/videos/133805360

**Comment by beardypig** [comment]
@bastimeyer is correct - I didn't read the stream url correctly, I jumped to conclusions based on the error :) As recompense I have created a PR which should fix the issue.
