### ISSUE TITLE
Plugin request: VRT NU

### ISSUE THREAD

**Issue by lillet23** [streamlink/streamlink#788]
- [ ] This is a bug report.
- [x] This is a plugin request.
- [ ] This is a feature request.
- [x] I used the search function to find already opened/closed issues or pull requests.

Please add support for the VRT NU live video streams (Belgian Flemish Television):
https://www.vrt.be/vrtnu/kanalen/een/
https://www.vrt.be/vrtnu/kanalen/canvas/
https://www.vrt.be/vrtnu/kanalen/ketnet/

Many thanks!

**Comment by back-to** [comment]
@lillet23 

Here, you can try it.

https://raw.githubusercontent.com/back-to/streamlink/vrtbe/src/streamlink/plugins/vrtbe.py

**Comment by lillet23** [comment]
Works perfectly with all three channels!
Many thanks! ;-)

**Comment by karlo2105** [comment]
Could you please push it for merging ?
