### ISSUE TITLE
Funimation Login

### ISSUE THREAD

**Issue by kyutie** [streamlink/streamlink#789]
- [X] This is a feature request.

### Description
Is it possible to add a login feature for funimation, like in the crunchyroll plugin?

**Comment by Truanifan** [comment]
I'd like to second this if possible.

**Comment by beardypig** [comment]
Ah, was going to work on but forgot... I'll take a look :-)

**Comment by beardypig** [comment]
I have created a branch on my fork which supports logins for Funimation - it could do with some real world testing: https://github.com/beardypig/streamlink/tree/funimation

**Comment by vinnyA3** [comment]
@beardypig Has this addition been merged yet?  If not, are there any plans to merge the funimation login functionality any time soon (I just want to be sure before I create an AUR package of your fork)?

**Comment by gravyboat** [comment]
@vinnyA3 I just checked the master branch and those changes are not in there.

**Comment by beardypig** [comment]
@vinnyA3 yeah, I plan to merge it. But, I haven’t done any proper testing and no one reported back if they tried it. Have you tested it?

**Comment by vinnyA3** [comment]
@gravyboat Thanks for the response.  Hopefully we can get this feature merged soon.  However, I think there might have been an update to the funimation api.  Whenever I try to stream something from funimation, I'm getting:
```
[plugin.funimationnow][error]: could not find experience ID?!
error: No playable streams found on this URL: <funimation url here>
``` 
Some more information down below.

---

@beardypig I got to testing your feature.  The additional funimation login options are recognized, but there might have been an change to the funimation API?  I'm not sure, maybe I'm doing something wrong ...

I was looking through [issue#617](https://github.com/streamlink/streamlink/issues/617), and tried hitting the API to get the appropriate metadata (ex:  [https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/](https://prod-api-funimationnow.dadcdigital.com/api/source/catalog/title/experience/256245/)), but all that's returned an empty JSON object.

---

**python version:**  3.6.5
**proxy**:  no

**Comment by beardypig** [comment]
@vinnyA3 thanks for the info, I was just rebasing the old code with the new code and trying to fix the issues this afternoon. Then I found an issue with the new logging changes, so I was fixing that first. I'll submit a PR today.

**Comment by vinnyA3** [comment]
@beardypig You're welcome; I wish I could help out a bit more.  I updated my previous comment with some more information (maybe it'll be useful).

**Comment by beardypig** [comment]
@vinnyA3 for the logging to work you need to update to the latest nightly/dev version of streamlink. I think I have worked out why it is not working though, needed to set an extra cookie. I will tidy the code up a bit and update the PR with the fix.

**Comment by beardypig** [comment]
@vinnyA3, sorry was slow to push the fix - just done it :)

**Comment by vinnyA3** [comment]
@beardypig No, please.  Wish I could've helped a bit more.

I just tried the new auth, it's working great!  Premium content is now accessible :)

Now, the only issue I'm running into is with the `mpv` player--the stream closes after a couple of minutes.  This is definitely an issue with `mpv` since `vlc` is working just fine, so I am going to debug this myself.

I appreciate the work you put into making this happen

**Comment by vinnyA3** [comment]
Hi again!

I've been gone for a bit, but after checking back with streamlink & premium funimation videos, I am getting the *no experience id* error again:

```
[cli][info] Found matching plugin funimationnow for URL https://www.funimation.com/shows/fairy-tail/turbulent-showdown-natsu-vs-laxus/uncut/?lang=english
[plugin.funimationnow][info] Attempting to by-pass Incapsula...
[plugin.funimationnow][error] Could not find experience ID?!
error: No playable streams found on this URL: https://www.funimation.com/shows/fairy-tail/turbulent-showdown-natsu-vs-laxus/uncut/?lang=english

```

I am currently running the latest streamlink available in the official Arch repo ...

**version:**  0.14.2

**Comment by beardypig** [comment]
@vinnyA3 could you open a new issue and provide debug logs.
