### ISSUE TITLE
Why stdout is printed to stderr?

### ISSUE THREAD

**Issue by mcaldas** [streamlink/streamlink#794]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Why does info output is sent to stderr instead of stdout? Is there a way to config this?

### Expected / Actual behavior
info and warn outputs should be sent to stdout

### Environment details

Operating system and version: ubuntu 16
Streamlink and Python version: latest

**Comment by bastimeyer** [comment]
Log output is always written to stderr because stream data can be written to stdout by using the `-O` parameter. If the info and warn log channels would write to stdout instead, they would need to write to stderr once this parameter gets used, which would be confusing and inconsistent.

See here:
https://github.com/streamlink/streamlink/blob/0.5.0/src/streamlink_cli/main.py#L609-L612

If you want log output to appear in stdout, you can simply redirect the pipes like this in bash:
```bash
streamlink --loglevel debug URL QUALITY 2>&1
```

Btw, ffmpeg does the same and always logs to stderr, too:
https://ffmpeg.org/ffmpeg.html

> By default the program logs to stderr.

**Comment by mcaldas** [comment]
Understood now :) thanks!!
So if I'm using the -o to write the stream to a file, how can I redirect
the "console" prints to a file? Using the ">" would work?

**Comment by bastimeyer** [comment]
```bash
streamlink -o file.ts URL QUALITY 2>log.txt
```

See here if you want to learn how to redirect I/O in bash:
http://tldp.org/LDP/abs/html/io-redirection.html

**Comment by mcaldas** [comment]
Yeah in normal bash I know how to do it, but as you mentioned Stdout is the
stream I got confused. In ffmpeg I use the internal "log to file" option,
so I avoid output messing around.

Anyway, thank you very much, it's clear now!

**Comment by bastimeyer** [comment]
You are confusing `-o` with `-O`:
https://streamlink.github.io/cli.html#file-output-options

**Comment by bastimeyer** [comment]
Closing the thread since the question has been answered.

**Comment by gravyboat** [comment]
Thanks @bastimeyer!

**Comment by mcaldas** [comment]
Hi guys! thanks for the help earlier! much appreciated.
Any chance on getting some help with a plugin for this site? http://telefe.com/capitulos-completos/
It's akamai, so should be easy.
Thanks!

**Comment by gravyboat** [comment]
@mcaldas Can you please make a new issue for that plugin request? The new issue template should make it pretty easy, especially if you can provide us with details regarding example stream URLS and akamai, etc.

**Comment by mcaldas** [comment]
@gravyboat sure, will do. Thanks!

**Comment by mcaldas** [comment]
@gravyboat just one question, i am talking about VOD straming, is that fine?

**Comment by gravyboat** [comment]
Should be! If you make the issue and note the details if someone is interested in working on it they'll respond as much. We already support VODs for a variety of sites.

**Comment by mcaldas** [comment]
cool, on it now, thanks again :)

**Comment by mcaldas** [comment]
@gravyboat is this ok? #805

**Comment by gravyboat** [comment]
@mcaldas Yeah that's fine! if someone decides to work on it they may ask for more details, I'll tag it as a plugin request.
