### ISSUE TITLE
I'm writing a plugin for teamliquid.net but need some help

### ISSUE THREAD

**Issue by jacobmalmberg** [streamlink/streamlink#797]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.
- [x] This is a help request

### Description

I'm writing a plugin for teamliquid.net. Their stream pages (ie http://www.teamliquid.net/video/streams/nalra82) just contains a HTML5/flash plugin that loads a stream that is hosted on (usually) twitch.tv or afreeca, so what I have done is just extract the stream url from the teamliquid.net page and then I think it would make sense to just "call" for the afreeca/twitch.tv plugin...but I don't know how. Below is the code as I wrote it (tl.py), obviously the "real" version will contain some code for Twitch.tv too.

...

tl.py

import streamlink
import sys
import urllib2
import re

#User inputs the teamliquid.net url to the stream
urlIn=sys.argv[1]
#urlIn="http://www.teamliquid.net/video/streams/nalra82"

#gives us the user name of the user on afreeca
afreecaUserName=urlIn.rsplit('/', 1)[-1]

def readUrl(urlIn):
    #input is url
    #output is byte object that contains the content of the page

    response= urllib2.urlopen(urlIn)
    content = response.read()
    return content

content=readUrl(urlIn)

urlBaseOut="http://play.afreeca.com/"

url=urlBaseOut+afreecaUserName

#???
streams=streamlink.streams(url)

### Environment details

Operating system and version: ... xubuntu 17.04
Streamlink and Python version: ... Streamlink 0.5, python 2.7 (and 3.6)

**Comment by gravyboat** [comment]
Did you mean to close this?

**Comment by jacobmalmberg** [comment]
Yes!
