### ISSUE TITLE
VLC Nightly has issues with streamlink+twitch

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#798]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
When using any VLC nightly after the one from the 4th of April 2017, any opened twitch stream shows video for 1-3 seconds and then the video freezes, while the audio continues.

### Expected / Actual behavior
Video should continue working in sync with audio.

### Reproduction steps / Explicit stream URLs to test

1. Any twitch stream should work, I experienced the problem on twitch.tv/eulcs1, quality 1080p. 
2. Basic VLC presets, not even DXVA is enabled. 100% Default.

### Environment details

Operating system and version: Windows 7 Service Pack 2 64bit
Streamlink and Python version: 11th April nightly of Streamlink for Windows, non-portable version.

### Comment

This MIGHT be a VLC-only problem, but since I can not determine whether it is or isn't, I'm still raising this ticket. If it's a VLC problem, ignore and close this ticket.

**Comment by beardypig** [comment]
If it works with an earlier version of VLC or any other player then it's definitely a regressio

**Comment by roshavagarga** [comment]
@beardypig Yes, it does work with earlier versions and other players. Since it's a regression, whomever can - please close this ticket as it's not a streamlink problem :+1:

**Comment by beardypig** [comment]
Maybe you (or someone else) can produce a copyright-free `ts` file from a twitch stream that works in an older version of VLC but not in a new version to send to the VLC team. Did the problem only occur with a live stream, or did it also happen with VOD? What about saving file and playing the saved file?

**Comment by gravyboat** [comment]
Agreed @beardypig, it would be nice to pass this on to the VLC team in the event they aren't already aware.

**Comment by voltagex** [comment]
Can't reproduce on the June 12 nightly of VLC 3.
