### ISSUE TITLE
Dynamic youtube live url

### ISSUE THREAD

**Issue by limiteddi** [streamlink/streamlink#799]
Is there a way to get the URL of live stream on a certain channel?
For example: https://www.youtube.com/user/studionchannel/
The live stream which right now is https://www.youtube.com/watch?v=OLPon9rQzY8 - keeps changing frequently.

**Comment by gravyboat** [comment]
@limiteddi Not as far as I know. We don't do any sort of tracking, and as far as I remember the youtube livestreams don't do any sort of redirect or notification that Streamlink could use to track this somehow. The best thing I can think to do is write a wrapper script that queries the user's channel page for the URL, then launches streamlink again when it detects that the live URL has changed. Usually the live URL changes when the person streaming ends the stream and starts a new one so that youtube has a record that can be watched later. The one you linked however started streaming in January which leads me to believe that Youtube may be periodically modifying it so that they can split the archive as they can't handle streams over 4 hours very well.

**Comment by back-to** [comment]
You could try to use this url
- `https://www.youtube.com/user/studionchannel/videos?live_view=501&view=2`
- `https://www.youtube.com/user/studionchannel/videos?view=2`
It works for now, but i'm not sure what will happen if they add a different live stream

```
streamlink "https://www.youtube.com/user/studionchannel/videos?live_view=501&view=2" best

[Streamlink for Windows v0.4.0 - Git bc3cf3a]
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/studionchannel/videos?live_view=501&view=2
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]
```

**Comment by karlo2105** [comment]
Nominative address stream is supported on Youtube : 

```
streamlink "https://www.youtube.com/user/studionchannel" best
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/user/s
tudionchannel
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by limiteddi** [comment]
karlo2105, but it doesnt seem to work for https://www.youtube.com/user/etv2india

**Comment by karlo2105** [comment]
@limiteddi 
Because this channel ETV2 India is off air.

**Comment by Svekla** [comment]
Adding `live_view=501&view=2` or `view=2` doesn't work for me:
```
[cli][info] Found matching plugin youtube for URL https://www.youtube.com/channel/UCNArdo_iHMiRBbFvFk_e--w/videos?live_view=501&view=2
error: No streams found on this URL: https://www.youtube.com/channel/UCNArdo_iHMiRBbFvFk_e--w/videos?live_view=501&view=2
```

**Comment by back-to** [comment]
@Svekla 
it should work if you add `/live`

---

```
Streamlink https://gaming.youtube.com/channel/UCQvTDmHza8erxZqDkjQ4bQQ best
[Streamlink for Windows v0.5.0 - Git b09e2ac]
[cli][info] Found matching plugin youtube for URL https://gaming.youtube.com/channel/UCQvTDmHza8erxZqDkjQ4bQQ
error: No playable streams found on this URL: https://gaming.youtube.com/channel/UCQvTDmHza8erxZqDkjQ4bQQ
[End of Streamlink for Windows]
```
with `/live`
```
Streamlink https://gaming.youtube.com/channel/UCQvTDmHza8erxZqDkjQ4bQQ/live best
[Streamlink for Windows v0.5.0 - Git b09e2ac]
[cli][info] Found matching plugin youtube for URL https://gaming.youtube.com/channel/UCQvTDmHza8erxZqDkjQ4bQQ/live
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]
```

**Comment by cirrusUK** [comment]
Maybe using the you tube channels RSS feed would help ?   youtube-dl allows windows users (and the rest of us) to open youtube urls, streamlink not needed here.

**Comment by gravyboat** [comment]
I'm going to close this for now since @back-to has been kind enough to provide a thorough explanation for this. Thanks!

**Comment by cirrusUK** [comment]
maybe try the channels RSS feed
IE:
    https://www.youtube.com/feeds/videos.xml?user=H4x0r18

or 

    https://www.youtube.com/feeds/videos.xml?channel_id=UCYlQCaZmNIoryxNKv4UwuZw

channel ID can be gotten from channels page, good luck.

PS. i do this is linux using newsbeuter rss reader,  and with macro's hitting the 'p' key opens the you tube url up in mpv.
