### ISSUE TITLE
Plugin request: ifriends.net [NSFW]

### ISSUE THREAD

**Issue by Ptibouc77** [streamlink/streamlink#800]

**Comment by gravyboat** [comment]
Do you have any further examples? Such as what a URL looks like, whether you've looked into what the requests look like network traffic wise, etc.?

**Comment by Ptibouc77** [comment]
Actually im able to reccord using this with streamlink

`streamlink hlsvariant://http://STREAM01.ifriends.net:1935/LSFlashVCH/%stream_username%/%stream_username%%sessionid%/playlist.m3u8`

For STREAM01 part this also can be STREAM02 STREAM03 or STREAM04

Example url:
For this url `https://www.ifriends.net/membrg/showclub_v2_custom.dll?pclub=CHLOE-SWIFT&pstyle=home`
CHLOE-SWIFT = stream_username

The difficult part is to find the SessionID, since latest update we can no longer find the SessionID on ifriends model page, we will use a mirror website for this.

Example with the old ifriends:
Go to https://www.ifriends.net/membrg/showclub_v2_custom.dll?pclub=CHLOE-SWIFT&pstyle=home
Use inspect element and search for SessionID you will find something like this `input id="f_hid_SessionID_ExSignIn" name="f_hid_SessionID_ExSignIn" value="6314587" type="hidden"`
6314587 = SessionID

Example with mirror website:
Go to http://www.sizzlingcams.com/membrg/showclub_v2_custom.dll?pclub=CHLOE-SWIFT&pStyle=Home
Use inspect element and search for SessionID you will find something like this `input id="f_hid_SessionID_ExSignIn" name="f_hid_SessionID_ExSignIn" value="6314587" type="hidden"`
6314587 = SessionID

Hope this can help if you have other question ask me :)

**Comment by Ptibouc77** [comment]
Can someone give this a try?

**Comment by gravyboat** [comment]
@Ptibouc77 If someone feels like working on a plugin request they will add a comment saying as much, there's no need to bump a request. You're free to post a [bounty](https://www.bountysource.com/issues/44182172-plugin-request-ifriends-net-nsfw) if you want to pay someone to work on it. Please keep in mind that we are a group of unpaid volunteers spending our free time to work on this project.

**Comment by back-to** [comment]
https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests

> Plugins which fall under the following categories will not be implemented or considered and the request will be closed:
> - 5 - NSFW sites of a pornographic nature (cam sites, porn sites, etc.)
