### ISSUE TITLE
Wrote a plugin for teamliquid.net, but need some help

### ISSUE THREAD

**Issue by jacobmalmberg** [streamlink/streamlink#802]
----

### Checklist

- [] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Well, I wrote a plugin for teamliquid.net. Essentially it just gets the afreeca/twitch.tv stream url that is embedded on a teamliquid.net "stream" page. For example http://www.teamliquid.net/video/streams/jaedong23 really just contains a stream from afreecaTV, http://play.afreeca.com/jaedong23. 

Anyway, I wrote some code for this and then tried to do a plugin by pasting my code into the example on the API guide page, https://streamlink.github.io/api_guide.html#examples. If I write "python2.7 tl.py http://www.teamliquid.net/video/streams/Classic%20BW%20VODs best" it works just fine, but if I put tl.py into my $HOME/.config/streamlink/plugins and type "streamlink URL_HERE best" it just says 
"error: No plugin can handle URL: http://www.teamliquid.net/video/streams/Classic%20BW%20VODs
".

I dont really know where to go from here, so any pointers would be welcome. I have attached two files, one file that just contains my code and another (tl.txt) that contains my efforts when it comes to pasting it into the example and doing some modifications.

[tl.txt](https://github.com/streamlink/streamlink/files/924281/tl.txt) 
[myCode.txt](https://github.com/streamlink/streamlink/files/924282/myCode.txt)

### Reproduction steps / Explicit stream URLs to test

1. http://www.teamliquid.net/video/streams/Classic%20BW%20VODs

### Environment details

Operating system and version: xubuntu 17.04
Streamlink and Python version: Streamlink 0.50, python 2.7 (and 3.6 if that matters)

...

**Comment by back-to** [comment]
If you want a plugin, you don't need this API stuff

based on
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/viasat_embed.py

this should work, if you create a `teamliquid.py` in your plugins folder

```py
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http


_url_re = re.compile(r'''https?://(?:www\.)?teamliquid\.net/video/streams/''')
# REGEX https://regex101.com/r/vEROtt/2
_embed_re = re.compile(r'''<iframe class="videoplayer" src="([^\"]+)"''')
# REGEX https://regex101.com/r/vEROtt/1

class Teamliquid(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        res = http.get(self.url)

        match = _embed_re.search(res.text)
        if match:
            url = match.group(1)
            return self.session.streams(url)


__plugin__ = Teamliquid

```

works only with the latest `twitch.py` version

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py

**Comment by jacobmalmberg** [comment]
Thanks for your quick reply!

I modified your code a little a now it works as I wanted. Thanks!

```
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http


_url_re = re.compile(r'''https?://(?:www\.)?teamliquid\.net/video/streams/''')
_embed_re = re.compile(r'''<iframe class="videoplayer" src="([^\"]+)"''')
_afreecaRe = re.compile('View on Afreeca')
_twitchRe = re.compile('View on Twitch.tv')


class Teamliquid(Plugin):
    @classmethod
    def can_handle_url(cls, url):
        return _url_re.match(url)

    def _get_streams(self):
        res = http.get(self.url)
        #print(res.text)
        ## Res.text gives us the html stuff
        afreeca= _afreecaRe.findall(res.text)
        twitch= _twitchRe.findall(res.text)
        #match = _embed_re.search(res.text)
        if afreeca:
            streamAddressRe=re.compile('http://play.afreeca.com/[^">/]+')
            url=streamAddressRe.findall(res.text)[0]
            return self.session.streams(url)
        
        elif twitch:
            streamAddressRe=re.compile('http://www.twitch.tv/[^">/]+')
            url=streamAddressRe.findall(res.text)[0]
            return self.session.streams(url)
            
__plugin__ = Teamliquid

```
