### ISSUE TITLE
Plugin for zattoo.com

### ISSUE THREAD

**Issue by JulianM03** [streamlink/streamlink#804]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Could You please add a plugin for https://zattoo.com, a livestreaming platform on which many TV stations are streamed. There are about 70 channels on the free version and about 90 channels in the premium version.

Sorry for grammatic mistakes if done and thanks a lot.
...

**Comment by JulianM03** [comment]
Heres is the URL for getting a session-ID: https://sandbox.zattoo.com/zapi/session/token?app_tid=driess&format=json

**Comment by beardypig** [comment]
Last time I checked the streams were only available as dash streams, this might have changed though. Dash is not yet supported, but will be soon :-)

**Comment by back-to** [comment]
They support hls and hds aswell,
just change the `stream_type` in the POST parameter

from `dash` to `hls` or `hds`

https://github.com/kodinerds/repo/blob/master/service.iptv.proxy/resources/lib/zapisession.py#L74

**Comment by JulianM03** [comment]
Thank you for your quick answer. Can I also use the plugin in streamlink or can i otherwise stream the content from zattoo.com directly into a file?
I would like to save some tv shows or films as video files, so i can watch them again later.

Thank you for your help.

**Comment by back-to** [comment]
@JulianM03 

If you want you can test this files, with this live streams and vods should work.

https://github.com/back-to/streamlink/commit/7979e12b489e73a3963d653e28e7d5658c4d2b2c

**Comment by JulianM03** [comment]
@back-to 
I downloaded your version and it worked fine for me.
Thank you very much, your solution helps me a lot. :-)

**Comment by karlo2105** [comment]
```
[cli][info] Found matching plugin zattoo for URL http://zattoo.com/watch/sf-1
Traceback (most recent call last):
  File "C:\Users\Ddr\Downloads\streamlink\\streamlink-script.py", line 12, in <m
odule>
    main()
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink_cli\main.py", line
 1036, in main
    handle_url()
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink_cli\main.py", line
 482, in handle_url
    streams = fetch_streams(plugin)
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink_cli\main.py", line
 394, in fetch_streams
    sorting_excludes=args.stream_sorting_excludes)
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink\plugin\plugin.py",
 line 325, in get_streams
    return self.streams(*args, **kwargs)
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink\plugin\plugin.py",
 line 240, in streams
    ostreams = list(ostreams)
  File "C:\Users\Ddr\Downloads\streamlink\packages\streamlink\plugins\zattoo.py"
, line 133, in _watch
    params, watch_url = self._watch_live(channel, cookies)
TypeError: 'NoneType' object is not iterable
```

Streamlink portable has been used.

**Comment by back-to** [comment]
I added better debug/error messages, it should work now. @karlo2105 

But make sure the channel is available in your country.
_example of available channels in CH vs DE_
https://gist.github.com/back-to/df2c7b650732ed549a20da4f0c927490

**zattoo.py**
https://raw.githubusercontent.com/back-to/streamlink/a3659158eda42320e1737abb2644efa24e2fff38/src/streamlink/plugins/zattoo.py

**Comment by karlo2105** [comment]
@back-to 
Thanks very much it's working fine now. ;)

**Comment by karlo2105** [comment]
@back-to
Thanks very much it's working fine now. ;)
Is there any chance to implement removal of  "plugin-cache.json" from appdata directory once stream is closed?

**Comment by Ordval** [comment]
Exactly where are the login identifiers (e-mail and password) supposed to be set ? 
I'd rather someone give an exact example than posting all my errors 
made both in the .py and on the command line.

**Comment by karlo2105** [comment]
You can set E-Mail and Password credentials in streamlinksrc config file or directly. 

`streamlink --zattoo-email="email" --zattoo-password="password" "https://zattoo.com/watch/srf1" best`

Don't forget to add suitable proxy. ;)

**Comment by back-to** [comment]
@karlo2105 
does zattoo have dual audio channels?
like for France24 i got two channels there is one in EN and one in FR
if they got dual audio channels, it's not supported yet

@Ordval 
you need to change this three files, to be able to login.
- src/streamlink/plugins/zattoo.py
- src/streamlink_cli/argparser.py
- src/streamlink_cli/main.py

https://github.com/streamlink/streamlink/compare/master...back-to:zattoo

**Comment by karlo2105** [comment]
@back-to 
According to this source, dual audio is available : `https://support.zattoo.com/hc/en-us/articles/204448257-Dual-channel-audio-on-Android-devices`

**Comment by back-to** [comment]
@karlo2105 
it works as an **alt** stream already,
the different language maybe doesn't work always because its the same language for me on some other streams, but **arte** works for me

`best` is german
`alt` is french
```
streamlink https://zattoo.com/watch/DE_arte best
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/DE_arte
[cli][info] Available streams: 600k_alt2, 900k_alt, 600k_alt, 5000k_alt, 3000k_alt, 1500k_alt, 600k (worst), 900k, 1500k, 3000k, 5000k (best)
[cli][info] Opening stream: 5000k (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

streamlink https://zattoo.com/watch/DE_arte 5000k_alt
[cli][info] Found matching plugin zattoo for URL https://zattoo.com/watch/DE_arte
[cli][info] Available streams: 600k_alt2, 900k_alt, 600k_alt, 5000k_alt, 3000k_alt, 1500k_alt, 600k (worst), 900k, 1500k, 3000k, 5000k (best)
[cli][info] Opening stream: 5000k_alt (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
local@ubuntu:~/Desktop/git/streamlink$ 
```

**Comment by karlo2105** [comment]
@back-to 
I confirm you are right alt is used for original audio on several channels. ;)

**Comment by Ordval** [comment]
I did finally find the "streamlinksrc" file but there was no difference with the free VPN's I've used.
