### ISSUE TITLE
Plugin request - Telefe VOD

### ISSUE THREAD

**Issue by mcaldas** [streamlink/streamlink#805]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Would be very grateful if someone can help making a plugin for http://telefe.com/capitulos-completos/

they use akamai streaming, so should be straightforward. The only issue is that it's geoblocked to argentina only (but i can help debug if needed)
The stream url looks something like this:

http://telefe-vh.akamaihd.net/i/TOK/Amar_Despues_de_Amar/201702/AR/TLF6367307-AMAR_DESPUES_DE_AMAR-ARGENTINA_,1000k,200k,.mp4.csmil/master.m3u8?hdnea=st=1492466426~exp=1492473626~acl=/i/TOK/Amar_Despues_de_Amar/201702/AR/TLF6367307-AMAR_DESPUES_DE_AMAR-ARGENTINA_,1000k,200k,.mp4.csmil/*~hmac=f10ff8c2da31e40a014112edc9c569327a67cfb48f75f753eeb5379931fd3ec3

Thanks in advance!

**Comment by RosadinTV** [comment]
Yo también soy de Argentina, Python no es mi fuerte pero probablemente pueda lograr crear un Plugin 😄

**Comment by mcaldas** [comment]
@RosadinTV si queres te ayudo, tampoco es mi fuerte, pero algo capaz sale

**Comment by RosadinTV** [comment]
@mcaldas No lo probe a fondo pero parece funcionar bien:

**telefe.py**

```
import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http, useragents, validate
from streamlink.stream import HLSStream


class Telefe(Plugin):
    _url_re = re.compile(r'https?://telefe.com/.+')

    @classmethod
    def can_handle_url(cls, url):
        return Telefe._url_re.match(url)

    def _get_streams(self):
        TELEFE_UA = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1218"
        res = http.get(self.url, headers={'User-Agent': TELEFE_UA})
        busqueda_videoID = res.content.decode()
        busqueda_videoID = busqueda_videoID[busqueda_videoID.index('"PlayerContainer","model":{"id":') + 32 :]
        busqueda_videoID = busqueda_videoID[: busqueda_videoID.index(',')]
        #print('ID encontrado: ' + busqueda_videoID)

        hls_streams = HLSStream.parse_variant_playlist(
            self.session,
            "http://telefe.com/Api/Videos/GetSourceUrl/" + busqueda_videoID + "/0/HLS",
            headers={'Referer': self.url,
            'User-Agent': TELEFE_UA,
            'X-Requested-With': 'ShockwaveFlash/25.0.0.148'}
        )
        for s in hls_streams.items():
            yield s       


__plugin__ = Telefe

```

**Comment by malvinas2** [comment]
Que significa '_but i can help debug if needed_' ? Conoces una manera de verlo en Europa sin usar algo como VPN o un proxy ?

**Comment by RosadinTV** [comment]
@malvinas2 Se referia a que podia ayudar a conseguir informacion util para hacer el plugin (logs de las solicitudes y respuestas HTTP principalmente supongo).
En cuanto a usarlo fuera de Argentina veo muy dificil que se pueda llegar a lograr sin usar un Proxy o VPN.

**Comment by mcaldas** [comment]
@malvinas2 usando VPN nada mas

**Comment by mcaldas** [comment]
@RosadinTV como puedo probar tus cambios?

**Comment by mcaldas** [comment]
@RosadinTV pude hacerlo correr sideloading el plugin, pero me da error:
`error: 'ascii' codec can't decode byte 0xc3 in position 4316: ordinal not in range(128)`

Tenes idea q puede ser?

**Comment by bastimeyer** [comment]
I don't know what's going on here, but can we stick to **English** on this issue tracker please?
Even if you're from Argentina and you're discussing a plugin for an Argentinian streaming service, this is an international place with people from around the world, so the language should be English at all times.

People who are watching this repo are all being notified whenever someone is posting something. Please be aware of this. I can imagine that most of them are not happy about receiving texts in a language that they don't speak.

Thanks

**Comment by mcaldas** [comment]
@bastimeyer sorry about that. Lets move to english.
Translating, i managed to run @RosadinTV plugin, but i get the above error.
I've been searching and seems to be something related to encoding, that could be fixed by python3, but my streamlink installation runs on python 2.7, is there a way to force python 3?

**Comment by mcaldas** [comment]
@RosadinTV i think i found a solution, you can force utf-8 on decode, not sure its the right approach, but it works.
Just decode like this:
`busqueda_videoID = res.content.decode('utf-8')`

**Comment by beardypig** [comment]
@mcaldas are you using the latest version? `res.text` should work in the same way as `res.content.decode('utf-8')` in this instance (it should detect the correct encoding to use).

**Comment by mcaldas** [comment]
@beardypig latest version of streamlink? then yes, latest dev
I took `res.content.decode()` from @RosadinTV , you suggest using `res.text` instead?

**Comment by beardypig** [comment]
I mean the latest version of the plugin from @RosadinTV, it was switched to `res.text` :-)

**Comment by mcaldas** [comment]
Mmm, that was my confusion then, where do I get the latest version?

**Comment by beardypig** [comment]
No problem, you can get the latest version here: [telefe.py](https://raw.githubusercontent.com/RosadinTV/streamlink/69ca75d56d4da3549554495ccb6747673d9ce2bb/src/streamlink/plugins/telefe.py) :-)

**Comment by mcaldas** [comment]
Thanks!! This will be merged into the main release?

**Comment by beardypig** [comment]
Most likely today or tomorrow, would be good have your feedback on it too.

**Comment by mcaldas** [comment]
just tested with the manual change to `res.text` and it worked.
I'll try this latest version a little more and give some feedback.
Would also like to suggest changing the variables and names to english, @RosadinTV i can do it if you want

**Comment by RosadinTV** [comment]
@mcaldas Done, thanks for testing :)

**Comment by mcaldas** [comment]
@RosadinTV and thank you for writing the plugin!
Next: Canal 13 ;)

**Comment by RosadinTV** [comment]
@mcaldas Sure, currently the Canal 13 videos give me the error "We're sorry, this content is currently unavailable.".
The same happens to you?
(Although maybe we should talk about about this in a new issue, i mean "Plugin request - El Trece VOD " for example)

**Comment by mcaldas** [comment]
Maybe better yes, havent tried canal 13 yet, but its the next one on the list :)

**Comment by malvinas2** [comment]
_"We're sorry, this content is currently unavailable."_ I believe this message appears because some videos are just available for three days. At least I could watch other videos without problems, so they don't seem to use some kind of geo-blocking. Which doesn't surprise me, because there content is by far not that interesting as the content of Telefe, jajaja ;-)

**Comment by RosadinTV** [comment]
@malvinas2 I just tried again and now it works for me.
I also think that Telefe has better content, but creating a Plugin for "El Trece" would be a good idea.
I guess I'll have it ready in a couple of days.
