### ISSUE TITLE
On Windows, no "streamlinkrc" file found after installation 

### ISSUE THREAD

**Issue by fireattack** [streamlink/streamlink#81]
Despite [it said so in the document](https://streamlink.github.io/cli.html#configuration-file).

**Comment by TheSneakySniper** [comment]
Could you give us a little more information?

**Comment by fireattack** [comment]
I just use `pip install streamlink` to install it today, but it doesn't have that file "streamlinkrc" under "%APPDATA%\streamlink\". The folder itself, exists.

**Comment by gravyboat** [comment]
A bunch of the Windows documentation is out of date since we're working on rebuilding how the installer works. Documentation changes and other notes are being mentioned over in https://github.com/streamlink/streamlink/issues/78

**Comment by sbstp** [comment]
`pip install streamlink` doesn't use the installer, so I don't think it ever created the `livestreamerrc` file. Nothing in the `setup.py` indicates that it did. Now the installer should create that file, so I'll work on doing that.

**Comment by veludo32** [comment]
I'm from Brazil, as I install streamlink in windows 7? 
someone help me install streamlink?
I did not understand how to install it ...
anyone can make a video plz?

**Comment by Skibicki** [comment]
livestreamerrc can renamed and placed in \AppData\Roaming\streamlink
This config works but needs a little editing. http://pastebin.com/Q5KbgRpj

**Comment by gravyboat** [comment]
@sbstp It might be worth reviewing this note from @Skibicki for a config.

**Comment by thinkpad4** [comment]
So all I need to so is rename livestreamerrc to streamlinkrc and place it in the roaming/streamlink folder?
