### ISSUE TITLE
[Question] Support for Synology NAS

### ISSUE THREAD

**Issue by mcaldas** [streamlink/streamlink#814]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Does anyone tried to run streamlink on synology NAS? I am trying to install it there and get some weird errors, i installed manually ccache, glib, gcc and optware-devel, but i get the following error:

```
unable to execute '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc': Permission denied
    error: command '/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc' failed with exit status 1
Command "/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-woQVtU/pycryptodome/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Hz529i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-woQVtU/pycryptodome/
```

But the permission on /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc is 777.

So maybe someone already solved this and can give some input.

### Environment details

Operating system and version: Synology DSM 6
Streamlink and Python version: Python 2.7.12

### Comments, logs, screenshots, etc.
I attach the full log just in case
[streamlink-syno.txt](https://github.com/streamlink/streamlink/files/934811/streamlink-syno.txt)

**Comment by beardypig** [comment]
What do the following commands report? 
```shell
uname -a
file /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
```

Pirates of the 777 seas! 755 is probably sufficient :)

**Comment by mcaldas** [comment]
Was 644, moved to 755 and then 777 just in case :)
Here is what i get:

`uname -a
Linux DiskStation2 2.6.32.12 #15047 Tue Feb 14 02:38:24 CST 2017 armv5tel GNU/Linux synology_88f6281_212j`

`file /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
-sh: file: command not found`

**Comment by beardypig** [comment]
OK. What if you just run 
```shell
/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
```

**Comment by mcaldas** [comment]
`-sh: /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc: Is a directory`

**Comment by beardypig** [comment]
Well that explains the error. Seems like ccache is not install correctly, did you use `ipkg` (or whatever it is)?

**Comment by mcaldas** [comment]
i had to install manually, but that is a simlink (or however is called to ccache):
`ls -l /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
total 0
lrwxrwxrwx 1 root root 21 Apr 18 23:09 ccache -> /usr/local/bin/ccache`

Maybe got it wrong?

**Comment by beardypig** [comment]
You could try:
```shell
rm -rf /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc
ln -s /usr/local/bin/ccache /usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc 
```
and see if that fixes it .

**Comment by mcaldas** [comment]
That solved it! Thanks!
Now im getting another issue, probably some *nix problem due to my limited knowledge on that, maybe you can suggest something?
The error i get now is `ccache: FATAL: Could not find compiler "arm-marvell-linux-gnueabi-ccache-gcc" in PATH`
But i dont completely understand what needs to be in the path... 
gcc and ccache are on PATH..

**Comment by beardypig** [comment]
Assuming it's bash, try:
```shell
export PATH=$PATH:/usr/local/arm-marvell-linux-gnueabi/bin/
```
Then install it again. 
If that fails what does 
```shell
ls -la /usr/local/arm-marvell-linux-gnueabi/bin/
```
print out?

**Comment by mcaldas** [comment]
Running `/usr/local/arm-marvell-linux-gnueabi/bin/arm-marvell-linux-gnueabi-ccache-gcc`
i still get:
`ccache: FATAL: Could not find compiler "arm-marvell-linux-gnueabi-ccache-gcc" in PATH`

Running `ls -la /usr/local/arm-marvell-linux-gnueabi/bin/` i get:
```
drwxrwxrwx 2 root    root  4096 Apr 19 17:40 .
drwxrwxrwx 3 root    root  4096 Apr 18 23:08 ..
lrwxrwxrwx 1 mcaldas users   21 Apr 19 17:40 arm-marvell-linux-gnueabi-ccache-gcc -> /usr/local/bin/ccache
```

**Comment by beardypig** [comment]
Seems like it's not installed correctly. Was there a particular reason not to use `ipkg`?

**Comment by mcaldas** [comment]
ccache its not available in ipkg :/

**Comment by beardypig** [comment]
OK. How about trying this:
```shell
sudo env CC=/usr/local/bin/gcc pip install streamlink
```
Assuming you installed `gcc` to `/usr/local/bin/`.

**Comment by mcaldas** [comment]
It's installed in `/opt/bin/gcc`, and running what you suggest (changing the path obviously) gives a different error:

```
gcc: error: unrecognized argument in option '-mcpu=marvell-f'
  gcc: note: valid arguments to '-mcpu=' are: arm1020e arm1020t arm1022e arm1026ej-s arm10e arm10tdmi arm1136j-s arm1136jf-s arm1156t2-s arm1156t2f-s arm1176jz-s arm1176jzf-s arm2 arm250 arm3 arm6 arm60 arm600 arm610 arm620 arm7 arm70 arm700 arm700i arm710 arm7100 arm710c arm710t arm720 arm720t arm740t arm7500 arm7500fe arm7d arm7di arm7dm arm7dmi arm7m arm7tdmi arm7tdmi-s arm8 arm810 arm9 arm920 arm920t arm922t arm926ej-s arm940t arm946e-s arm966e-s arm968e-s arm9e arm9tdmi cortex-a12 cortex-a15 cortex-a15.cortex-a7 cortex-a17 cortex-a17.cortex-a7 cortex-a5 cortex-a53 cortex-a57 cortex-a57.cortex-a53 cortex-a7 cortex-a72 cortex-a72.cortex-a53 cortex-a8 cortex-a9 cortex-m0 cortex-m0.small-multiply cortex-m0plus cortex-m0plus.small-multiply cortex-m1 cortex-m1.small-multiply cortex-m3 cortex-m4 cortex-m7 cortex-r4 cortex-r4f cortex-r5 cortex-r7 ep9312 exynos-m1 fa526 fa606te fa626 fa626te fa726te fmp626 generic-armv7-a iwmmxt iwmmxt2 marvell-pj4 mpcore mpcorenovfp native strongarm strongarm110 strongarm1100 strongarm1110 xgene1 xscale
  error: command '/opt/bin/gcc' failed with exit status 1
```

If this is taking too long dont worry, i'll keep running on my laptop, but wanted to have it on the NAS to make some automation and was hoping someone already traveled this path on synology

**Comment by mcaldas** [comment]
btw, is there a way to install wihtout pycryptodome? as thats the one making problems 
But maybe there will be other things failing later... just asking as I saw on the docs i can use pycrypto instead

**Comment by beardypig** [comment]
You can use pycrypto.
```shell
sudo env STREAMLINK_USE_PYCRYPTO=1 pip install streamlink
```
However, you'll likely encounter the same errors.

**Comment by mcaldas** [comment]
running that still tries to install pycryptodome for some reason, so it fails.
But if you say I will have issues further, then not worth the try.
Thanks anyway for your help!

**Comment by beardypig** [comment]
Easy to see if `pycrypto` will work, just do `pip install pycrypto` and see if it fails :)

**Comment by mcaldas** [comment]
i get the same error :/

**Comment by mcaldas** [comment]
last shot, maybe the problem is that `ccache` is installed in `/usr/local/bin/ccache` and `gcc` in `/opt/bin/`

**Comment by beardypig** [comment]
Seems like it's not the version of `gcc` that `distutils` (`pip`) is expecting.

**Comment by mcaldas** [comment]
i have this: `gcc version 5.3.0 (GCC) `

**Comment by gravyboat** [comment]
I'm going to close this since there hasn't been any discussion in a while and we have provided a lot of non-Streamlink related support.
