### ISSUE TITLE
Plugin request: RTE News

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#819]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

A plugin for the live broadcast available at http://www.rte.ie/news/player/live/7/

**Comment by melmorabity** [comment]
I'm working on it ;) https://github.com/melmorabity/streamlink/tree/rte

Just one blocking issue before submitting a PR:
https://github.com/streamlink/streamlink/issues/817

**Comment by roshavagarga** [comment]
Thank you a lot, @melmorabity

**Comment by karlo2105** [comment]
@melmorabity 
Could you please add HLS as primary choice because HDS is encrypted for channels Rte 1 and Rte 2?

**Comment by gravyboat** [comment]
Closing since the associated PR is merged.

**Comment by roshavagarga** [comment]
@melmorabity Downloaded today's nightly, when I try to open the rte link I gave, I still get "no plugin can handle this link".

**Comment by melmorabity** [comment]
@roshavagarga the plugin supports all stream on www.rte.ie/player/. Using http://www.rte.ie/player/fr/live/7/ should work.

**Comment by back-to** [comment]
@melmorabity i think the problem here is https

```
streamlink https://www.rte.ie/player/de/live/7/ best
error: No plugin can handle URL: https://www.rte.ie/player/de/live/7/

streamlink http://www.rte.ie/player/de/live/7/ best
[cli][info] Found matching plugin rte for URL http://www.rte.ie/player/de/live/7/
[cli][info] Available streams: 256k (worst), 300k, 512k, 600k, 1024k, 1200k, 2048k, 2400k (best)
[cli][info] Opening stream: 2400k (hls)
[cli][info] Starting player: /usr/bin/vlc
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```
https://github.com/streamlink/streamlink/blob/3ad3da008b189122cf37fe82fa58e7a3a1461728/src/streamlink/plugins/rte.py#L10-L13

the regex needs a small change and the api url should be changed to https aswell.
