### ISSUE TITLE
retry-streams overrides twitch-disable-hosting

### ISSUE THREAD

**Issue by plneappl** [streamlink/streamlink#82]
When using both arguments `--retry-streams DELAY` and `--twitch-disable-hosting`, on the first retry streams are switched to the hosted stream anyway.  Instead, streamlink should keep retrying without streaming the hosted stream.

**Comment by veludo32** [comment]
I'm from Brazil, as I install streamlink in windows 7?

**Comment by gravyboat** [comment]
@veludo32 Please don't spam multiple issues/unrelated issues.

**Comment by beardypig** [comment]
@plneappl I have submitted a fix for this bug, sorry it took so long - but hopefully it will make it in to streamlink 0.0.3 :)
