### ISSUE TITLE
Plugin request: CNews

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#820]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
A simple plugin for the broadcast available at http://www.cnews.fr/direct, which is a dailymotion stream available at http://www.dailymotion.com/video/x3b68jn

**Comment by karlo2105** [comment]
It's already covered by Dailymotion. ;)

**Comment by roshavagarga** [comment]
@karlo2105 Yes, technically it is, but specifically speaking dailymotion at least for me is very cumbersome to navigate on a Linux-based OS that's got an older CPU. The pages don't load well, browsing is very hard, even finding categories is a bit awkward. I thought we already have multiple plugins that basically tell streamlink "Yes, this page is actually a dailymotion stream, get the link and load it via the dailymotion plugin we already have", since a lot of users may not know how to find out the exact link - due to their OS not supporting Flash at all, not knowing how to browse source, etc.

**Comment by roshavagarga** [comment]
@gravyboat This should be closed, correct?

**Comment by gravyboat** [comment]
Yep, thanks for the reminder!
