### ISSUE TITLE
Bloomberg Plugin - No Plugin can handle URL ERROR

### ISSUE THREAD

**Issue by mkelly299** [streamlink/streamlink#823]
streamlink ""https://www.bloomberg.com/live/us"

results in ... 

error : no plugin can handle URL ""https://www.bloomberg.com/live/us" 

How do you get it to work?

Version 0.5.0

**Comment by RosadinTV** [comment]
Make sure you have the latest version of Streamlink since this Plugin was introduced 3 days ago (https://github.com/streamlink/streamlink/commit/9844f5612881753b32cbeb3c440187d61989e59e)

**Comment by unlocKing** [comment]
This works if you have the plugin as advised:

streamlink https://www.bloomberg.com/live/us best

**Comment by bastimeyer** [comment]
Closing this thread, since the plugin has been added in the 0.6.0 release a couple of weeks ago.
