### ISSUE TITLE
Feature request: Bitrate information

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#827]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
I would like any way to check how much worse an alt stream is compared to the best stream.

### Expected / Actual behavior
One option would be to add a command --showbitrate that adds the bitrate after each stream.
So it would be 720p (4400kbps), 720p60 (5000kbps), 720p_alt (3000kbps), 720p60_alt (3600kbps).

It would technically be pretties if it was just a percentage. Like streamlink finds the highest bitrate for quality X, all alt streams are represented as Xalt (%ofXbitrate). So 720p (5000) and 720p_alt (4000) would show 720p (best), 720p_alt (80%), since the alt stream has 80% of the bitrate of the best stream in that quality.

**Comment by back-to** [comment]
#540

---

If you want a **quick solution**,
change your `twitch.py` file here (or any other plugin with `HLSStream.parse_variant_playlist`)

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/twitch.py#L580

from
```py
            streams = HLSStream.parse_variant_playlist(self.session, url,
                                                       force_restart=not stream_type == "live")
```
to
```py
            streams = HLSStream.parse_variant_playlist(self.session, url,
                                                       force_restart=not stream_type == "live",
                                                       name_fmt="{pixels}_{bitrate}")
```
---

BEFORE

```
Streamlink https://www.twitch.tv/twitch best
[Streamlink for Windows v0.5.0 - Git 8bfae3d]
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/twitch
[cli][info] Available streams: audio_only, 720p60_alt, 160p (worst), 360p, 480p, 720p, 720p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]
```

AFTER

```
Streamlink https://www.twitch.tv/twitch best
[Streamlink for Windows v0.5.0 - Git 8bfae3d]
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/twitch
[cli][info] Available streams: none_162k, 160p_359k (worst), 360p_747k, 480p_1430k, 720p_2375k, 720p_3425k, 720p_4112k (best)
[cli][info] Opening stream: 720p_4112k (hls)
[cli][info] Starting player: "C:\Program Files\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]
```

**Comment by roshavagarga** [comment]
Oh, if it can be done like that, I'd prefer having the option to just switch between the two with a --command. It's nothing I really need right now, just useful because of the many alts :)

**Comment by back-to** [comment]
same issue as #1048, you can find more discussion there.
Closing.
