### ISSUE TITLE
Feature request: Consolidating stream qualities under common names

### ISSUE THREAD

**Issue by BullHorn7** [streamlink/streamlink#828]
### Checklist

- [ ] This is a bug report.
- [X] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Currently, when trying to start a stream, a quality must be specified. In some cases, the qualities are 'low', 'medium', 'high' and 'source'. In other cases they are '240p', '360p', '480p', '720p' and '720p60'. In some cases they might slightly deviate and be even further more different.

### Expected / Actual behavior

I'd like to choose a 'default' quality so I don't have to choose a quality each time, as well as make Streamlink automatically use the correct quality, for example: If 'high' is not available, I'd expect it to launch '480p' automatically.

### Environment details

Operating system and version: Win10 64 Pro Anniversary
Streamlink and Python version: 0.5.0 (using the .exe installer) and Python 3.5

### Comments, logs, screenshots, etc.

http://i.imgur.com/O3J8HSp.png

**Comment by bastimeyer** [comment]
These quality names are specific to Twitch. This doesn't work for other streaming services.

In the Streamlink Twitch GUI I'm going to change the mapping of the old quality names in the next release from explicit values to quality ranges. Maybe you want to write a shell wrapper script that does the same. See my comment here https://github.com/streamlink/streamlink-twitch-gui/issues/434#issuecomment-291055484 and the [`--stream-sorting-excludes`](https://streamlink.github.io/cli.html#cmdoption-stream-sorting-excludes) parameter documentation.

**Comment by roshavagarga** [comment]
@BullHorn7 You could just go with "best", which automatically chooses the highest quality available.

**Comment by bastimeyer** [comment]
`high` means second best quality (or best re-encoded quality) on Twitch, if it is available. They've added new explicit quality names in summer last year (and a couple more this february), but those are only being used by big channels. So you've got `source`, `high`, `medium`, `low`, `mobile`, `audio`, `audio_only` and the explit qualities like `1080p`, `1080p30` or `1080p60`.

You can either list all qualities explicitly (which is/was being done by the Twitch GUI), or you can do what I've linked above. The first method is not future-proof, though, which is the reason I mentioned the second method, which defines (parsable) quality ranges that are then selected via the `best` quality alias.

**Comment by gravyboat** [comment]
Hmm, this doesn't resolve the issue entirely, but https://streamlink.github.io/cli.html#cmdoption-default-stream is another possible option, though it won't do the fall back like you want. I'm not sure if we would want to implement such functionality either as I know some people are recording content and that could negatively impact them. Maybe we should consider adding some logic where --default-stream accepts a list of qualities, or implement a new option for the config file.

**Comment by bastimeyer** [comment]
@gravyboat 
A quality range selection via the normal quality list would be a nice-to-have feature, but you can already filter out unwanted qualities and select the `best` one out of the remaining ones while still having a fallback, [like I've described above in the linked comment](https://github.com/streamlink/streamlink-twitch-gui/issues/434#issuecomment-291055484). If desired, different config files containing these parameters can be set up, so that loading a specific config file becomes the quality selection.

```bash
# "source"
streamlink --default-stream "best" twitch.tv/CHANNEL
# "high"
streamlink --default-stream "high,best" --stream-sorting-excludes ">720p30,<540p" twitch.tv/CHANNEL
# "medium"
streamlink --default-stream "medium,best" --stream-sorting-excludes ">540p30,<480p" twitch.tv/CHANNEL
# "low"
streamlink --default-stream "low,best" --stream-sorting-excludes ">360p30" twitch.tv/CHANNEL
# "audio"
streamlink --default-stream "audio,audio_only" twitch.tv/CHANNEL
```

If you want to add a new parameter, being able to set aliases for parsable qualities and quality ranges would make sense, so that those can be whitelisted instead of blacklisted (`--stream-sorting-excludes`). Something like this would be easier to understand, I think:
```bash
# multiple alias-params could be allowed here
streamlink --stream-alias "high_alias:<=720p30,>=540p" twitch.tv/CHANNEL high,high_alias
```
Without adding a new parameter (or just using the `--default-stream` param), this would require a new quality selection format, since commas can't be used for both boolean ORs and ANDs at the same time:
```bash
# how to interpret the commas here?
streamlink twitch.tv/CHANNEL high,<=720p30,>=540p
# this format would require quotation marks and would not be backwards compatible
streamlink twitch.tv/CHANNEL "high||<=720p30&&>=540p"
```

**Comment by gravyboat** [comment]
@bastimeyer In that case I think we're good to go on this issue. @BullHorn7 can you please take a look at what @bastimeyer posted and see if it addresses your concerns?

**Comment by BullHorn7** [comment]
My specific case is that viewing a stream on 'Best' (aka Source) is impossible due to Twitch buffering - so I always have to guess whether a stream will be 'high' or '720p' or '720p60', etc. 

A fall-back mechanism like explained above seems to address my issue well.

**Comment by roshavagarga** [comment]
@BullHorn7 Out of pure curiosity, what streams are you viewing? I've been getting 720p30/720p60, etc on all of the streams I frequently watch for the last few weeks. I thought all the Twitch streams had migrated to this. Have smaller ones not been migrated?

**Comment by bastimeyer** [comment]
@roshavagarga 
https://github.com/streamlink/streamlink/issues/828#issuecomment-296390217

> Have smaller ones not been migrated?

no

@BullHorn7 
I'm closing the thread then, since the issue can be fixed by using already available parameters.
