### ISSUE TITLE
Bug: Youtube video pipe issue

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#829]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
A youtube video stopped working 12~ minutes after being started up.

### Expected / Actual behavior
The video should have continued working

### Reproduction steps / Explicit stream URLs to test

1. Open https://www.youtube.com/watch?v=ijqKJJ7lyqY at best (1080p60) quality available.
2. Wait until 12th minute~
3. VLC stops responding, Pause/Play does not do anything/

### Environment details

Operating system and version: Windows 7 64bit SP2, VLC 3 beta, 4th of April nightly.
Streamlink and Python version: Nightly from around the 20th of April, installed version for Windows. 

...

### Comments, logs, screenshots, etc.
This comes out in the command prompt:
[stream.mp4mux-ffmpeg][error] Pipe copy aborted: \\.\pipe\ffmpeg-4404-552

**Comment by gravyboat** [comment]
Couple things here. Can you try the latest VLC beta to confirm it isn't a VLC issue? If not can you run the command with the `-v` and `-l debug` options, then paste the output here please?

**Comment by roshavagarga** [comment]
@gravyboat I started up the same link and 16 minutes into it >> no bugs. It might have been a one-off problem. I did check my internet connection when it happened and pings to youtube were entirely all right without any hiccups. I'll continue for a bit more but I'm viewing this as a one-off for unknown reasons. I'm using the same version of VLC, as a lot of the newer nightlies had a bug I mentioned earlier - on VLC's side - that gave only audio with video being frozen on the first frame.

**Comment by gravyboat** [comment]
Sounds good, thanks for the update!

**Comment by bastimeyer** [comment]
Can this thread be closed then or are there any further issues?

**Comment by gravyboat** [comment]
Going to close it for now.
