### ISSUE TITLE
Channel4 incorrect aes length

### ISSUE THREAD

**Issue by unlocKing** [streamlink/streamlink#836]
- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

Channel4 gives incorrect aes key length error:

streamlink hlsvariant://http://csm-e.cds1.yospace.com/csm/extlive/channelfour01,c4-web.m3u8 best

[cli][info] Found matching plugin stream for URL hlsvariant://http://csm-e.cds1.yospace.com/csm/extlive/channelfour01,c4-web.m3u8
[cli][info] Available streams: 404p_alt, 180p (worst), 288p, 360p, 404p (best)
[cli][info] Opening stream: 404p (hls)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\segmented.py", line 160, in run
    self.write(segment, result)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 91, in write
    sequence.num)
  File "C:\Program Files (x86)\Streamlink\pkgs\streamlink\stream\hls.py", line 52, in create_decryptor
    return AES.new(self.key_data, AES.MODE_CBC, iv)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\AES.py", line 260, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\__init__.py", line 130, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\_mode_cbc.py", line 232, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "C:\Program Files (x86)\Streamlink\pkgs\Crypto\Cipher\AES.py", line 130, in _create_base_cipher
    raise ValueError("Incorrect AES key length (%d bytes)" % len(key))
ValueError: Incorrect AES key length (8705 bytes)

### Environment details

Operating system and version: ... Win 10 Pro
Streamlink and Python version: ... 0.5

...

### Comments, logs, screenshots, etc.

Changing from web to ios gives:

streamlink hlsvariant://http://csm-e.cds1.yospace.com/csm/extlive/channelfour01,c4-ios.m3u8 best

[cli][info] Found matching plugin stream for URL hlsvariant://http://csm-e.cds1.yospace.com/csm/extlive/channelfour01,c4-ios.m3u8
[cli][info] Available streams: 360p_alt2, 70k (worst), 144p, 216p, 288p, 360p, 576p (best)
[cli][info] Opening stream: 576p (hls)
[stream.hls][error] Failed to create decryptor: ('Unable to decrypt cipher {0}', 'SAMPLE-AES')
[cli][error] No data returned from stream
[cli][info] Closing currently open stream...

**Comment by Vangelis66** [comment]
The error generated with the iOS HLS encrypted stream is just a duplicate of https://github.com/streamlink/streamlink/issues/354 you have previously filed...
streamlink doesn't support, AFAIK, SAMPLE-AES decryption.

As for your first "web" variant playlist, I can't really comment, but a simple examination has revealed that: 

1. The best variant of http://csm-e.cds1.yospace.com/csm/extlive/channelfour01,c4-web.m3u8 is 

http://csm-e-ces1eurxaws101-6o64xqtcasf.cds1.yospace.com/csm/live/103582442/5.m3u8;jsessionid=6B54FA3C3B83670AA45AB1419E739137.csm-e-ces1eurxaws101-6o64xqtcasf.cds1.yospace.com?externalId=c4-web

(#EXT-X-STREAM-INF:BANDWIDTH=1650000,CODECS="avc1.4d001f,mp4a.40.2",RESOLUTION=720x404)

2. This one downloads AES-128 encrypted fragments from a "hds" type of stream, 
domain is "ak.live.hds.c4assets.com" and the key URL is 

`#EXT-X-KEY:METHOD=AES-128,URI="http://ak.live.hds.c4assets.com/c4/hds/95_4_m1488468336.drmmeta",IV="0x0"`

It is again very probable that the hls plugin can't handle that flavour of AES-128 encryption ;-( 
You'll have to wait for the final word from @beardypig, our decryption expert...

**Comment by beardypig** [comment]
@Vangelis66 is correct. The streams are protected by DRM. Unfortunately it is not currently possible for streamlink to support these streams, and it likely never will be possible.

**Comment by unlocKing** [comment]
Well, that's a shame..

Thanks for your replies chaps!
