### ISSUE TITLE
Plugin request: TV1

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#839]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
A plugin to watch http://www.tv1channel.org/index.php/livetv

**Comment by karlo2105** [comment]
They use external video hosting Livestream which is already covered by Streamlink : 

```
streamlink "http://original.livestream.com/tv1channelnormal" best
[cli][info] Found matching plugin oldlivestream for URL http://original.livestream.com/tv1channelnormal
[cli][info] Available streams: 0, 198k (worst), 678k (best)
[cli][info] Opening stream: 678k (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by roshavagarga** [comment]
@karlo2105 Yes, I noticed that. Is there a standing rule that websites that are hosted through another service that's covered can't get their own plugin? It's no problem for me or you to find the stream source, but your average user won't be able to :)

**Comment by gravyboat** [comment]
@roshavagarga There isn't, we have some proposed usage of that already. I think @karlo2105 is just providing a workaround.
