### ISSUE TITLE
Windows installer documentation

### ISSUE THREAD

**Issue by cdrage** [streamlink/streamlink#84]
We need to update the documentation on the streamlink site in regards to the Windows build.

It would also be nice to include this build in new releases (download the binary :)). :+1:

**Comment by gravyboat** [comment]
Details for doing the build starts here. @cdrage Do we want to make a new repo under the streamlink org for releases? We should also discuss how to ensure the build is 'safe' for usage by end users depending on where it gets built.

**Comment by beardypig** [comment]
Is the releases feature of Github not suitable? Can you not add the binaries to the release. 

On a related note, I don't know if you have plans to add a develop branch and merge all PRs to that and keep master as the stable release branch?

**Comment by gravyboat** [comment]
@beardypig The releases is fine, we could definitely build and then just add it to that page. I just want to make sure we're building in a secure environment. Regarding the develop branch we discussed that here: https://github.com/streamlink/streamlink/issues/12

**Comment by veludo32** [comment]
I'm from Brazil, as I install streamlink in windows 7?

**Comment by thinkpad4** [comment]
I can't find the Windows installer link?  https://github.com/streamlink/streamlink/releases/download/v0.0.2/streamlink-v0.0.2-win32-setup.exe doesn't work

**Comment by gravyboat** [comment]
@thinkpad4 It hasn't been built yet so it still needs to be added to the release page and the docs updated.

**Comment by thinkpad4** [comment]
Ok, thanks.

**Comment by veludo32** [comment]
@gravyboat installing with pip? a favor video of how to install via pip? the windows ...

**Comment by Brainzyy** [comment]
@veludo32 Install python, open cmd.exe and type in: pip install streamlink

**Comment by cdrage** [comment]
@gravyboat We can build manually each-time we do a release :) I can add it to the release script. Some sanity checks would be nice though too.

**Comment by veludo32** [comment]
@Brainzyy 
installed python 3.2.5 64-bit: open cmd.exe with permissions and enter pip install streamlink and hit enter.

appeared the following error message: 'pip' is not recognized as an internal or external command, operable program or batch file.

**Comment by Junior1544** [comment]
@veludo32 
You should probably make sure that Python is included in the Path statement...

**Comment by veludo32** [comment]
I'm from Brazil, I can not speak English I'm talking about by google translator, you could make a video installing is easier for me if you can appreciate it.

**Comment by flijloku** [comment]
@veludo32  I read, that needed Python 3.4+. For example this: https://www.python.org/downloads/release/python-352/

**Comment by veludo32** [comment]
I found the way, but nothing related the streamlink

**Comment by veludo32** [comment]
@flijloku 
I managed to install but streamlinkrc file does not appear in the AppData \ Roaming \ streamlink

**Comment by flijloku** [comment]
Use search for streamlink.exe and then add the path to them in system variable "path" or in bat-file(cmd-line).I do not know what else to help you.

**Comment by veludo32** [comment]
@flijloku 
thank you, good will go using livestreamer for now, when they arrumarem everything right I start using streamlink :) thanks for trying to help!

**Comment by flijloku** [comment]
If you use "Customize installation" and install Python as I write above  (in "C\Python35) I think you find streamlink.exe in C\Python35\Scripts\. If not, it's amazing to me :)

**Comment by RosadinTV** [comment]
Soon i will be posting a Windows Portable version of Streamlink release 2 base on Python 3.5.2

**Comment by gravyboat** [comment]
@RosadinTV How do you want to handle those portable builds? Do you want an invite to the organization to manage those?

**Comment by RosadinTV** [comment]
@gravyboat I think i will make a portable .EXE (in VB.NET) that download the latest Streamlink-master.zip and convert the package to run on Windows.
The build will be in Python 3.5.2 but i have some ideas of a Python 2.7.x support without a big file-size Python folder.
The idea is to update the build to the latest commit with a few clicks.
In my personal Project (the one that is filled with mpv-ytdl and livestreamer) i made a updater that find the latest commit of streamlink, extract the plugins, convert them to livestreamer imports, add some modules patches and with this i have a livestreamer build with working and updated plugins.
But with the program to build portable streamlink builds i will be focus on a 100% streamlink build.

**Comment by gravyboat** [comment]
This is documented, going to close it out.
