### ISSUE TITLE
fix for bigo.tv plugin

### ISSUE THREAD

**Issue by leov30** [streamlink/streamlink#843]
In line 50, the plugin works better like this.
 
`_url_re = re.compile(r"https?://(?:www\.)?(bigo\.tv/\w+|bigoweb\.co/show/\w+)")`

This change allows user names mixed with letters and numbers.

**Comment by gravyboat** [comment]
Could you open a PR with this enhancement if you have time please?

**Comment by beardypig** [comment]
@leov30 do you have some example URLs to valid the regex? 
We'll add/update some tests. Can the show ID not be integers only? `bigoweb.co/show/\d+`.

**Comment by leov30** [comment]
In bigo.tv most user account are made of just numbers, but there are some with alphabet characters also.
`http://www.bigo.tv/music`
`https://bigo.tv/abiydekji`

**Comment by lki2019** [comment]
http://www.bigo.tv/jakhash

http://124.95.181.66:7778/list_3682981499_2171155155.m3u8

![qq 20170815140720](https://user-images.githubusercontent.com/30022431/29303996-36fafa78-81c3-11e7-9e99-65f8c0cf31a3.png)

**Comment by back-to** [comment]
originale solved with #1053
