### ISSUE TITLE
Add already-created facebook plugin

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#845]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Add an already-created plugin for facebook videos (non-Dash, 360p quality). A link can be found in #226, the original creator left if there and allowed anybody to work on it and use it. Since we have no way of viewing facebook videos, I think this would be a very good addition for the upcoming 0.6 version.

**Comment by DawgNewb** [comment]
It would be great If sombody could add sign-in stuff (-username/-password) for zp's plugin.
