### ISSUE TITLE
Plugin request: Bulgaria 24

### ISSUE THREAD

**Issue by roshavagarga** [streamlink/streamlink#846]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [X] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
A plugin to view the stream found at this link: http://bulgaria24.tv/%D1%82%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%B8%D1%8F-%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D0%B8%D1%8F-24-%D0%BD%D0%B0-%D0%B6%D0%B8%D0%B2%D0%BE/ (link looks this way due to cyrillic). 

The video/player is actually hosted on this link: http://46.249.82.226:82/vmro/player.php

**Comment by lki2019** [comment]
rtmp   stream

rtmp://46.249.82.226/live/vmro

**Comment by back-to** [comment]
It's a static url and changes very rarely,

not really worth  to create a new plugin for a static url without any session id requirements.

Just use the hls plugin with

```
streamlink hls://http://46.249.82.226:82/streams/bulgaria24/stream.m3u8 best
```

or the rtmp stream above

Closing.
