### ISSUE TITLE
broadcast over http from custom rtmpdump command output?

### ISSUE THREAD

**Issue by mailinglists35** [streamlink/streamlink#847]
well this is more a question than a feature request or bug
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
I use this command line to dump a radio stream (technically it is a video stream but I only listen to audio)
`rtmpdump -r rtmp://89.238.207.219/live -W http://www.romania-actualitati.ro/flash/player.swf --playpath RRActualitati1 | mplayer -quiet -`

How can I use streamlink to also broadcast this stream (--player-external-http / player-http / player-continuous-http) so other devices on same LAN can listen to the same stream broadcasted by streamlink?

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by mailinglists35** [comment]
ok, so I've managed to run this

`C:\Program Files (x86)\Streamlink\bin> .\streamlink.exe --player-external-http "rtmp://89.238.207.219/live/RRActualitati1 live=1 swfVfy=http
://www.romania-actualitati.ro/flash/player.swf" best`

it works, but only 1 http client can connect at any time. After the currently connected client disconnects, only then another client can connect.

How can I serve multiple clients?

**Comment by beardypig** [comment]
That's the way to do it. Currently only one client is supported, see #180.

**Comment by mailinglists35** [comment]
thank you.
