### ISSUE TITLE
Plugin Request: girlfriendsfilmsvod.com [NSFW]

### ISSUE THREAD

**Issue by Merlin7x** [streamlink/streamlink#848]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Is it possible to have a plugin for girlfriendsfilmsvod.com (NSFW)? 

### Reasoning
To be perfectly honest, I have a limited understanding of how exactly this works, I'm still learning. Please forgive me if I use the incorrect terminology.

Until recently, RTMP Dump Helper sufficed for my stream capture needs, until I discovered that HD films from this studio are not readily available for download. Other than low-res DVD's, VOD is the only alternative with these folks. Once a scene is purchased from this site you find out that the advertised (perfectly legal and allowed) download is low resolution, and can only be streamed in HD. I've tried a few different ways of saving a copy of that stream, all of which failed. I even tried other VOD sites, to see if I could catch their streams, but they all offered the low-res download, and none had the HD stream. Short of screen capture _(shudders)_ you gentlemen/ladies are my last best hope.

I don't think DRM would have to be violated, but the plugin might have to support username and password authentication, or cookie sniffing. I think the streaming method being used is called Dash. The stream is avc mp4 video, with a bitrate of 4994kbps. Audio is mp4a.

### Explicit stream URLs to test

1. This is the address in the browser (Firefox 54.0b1) - https://www.girlfriendsfilmsvod.com/_player.php?video_id=330360&ps_id=3464715&bitrate_index=5
The value for bitrate index changes depending on whether or not HD streaming quality was selected. Ranges from 1 (low) to 5 (max).

2. I believe this is the... manifest? file, or something important - https://astream.hotmovies.com/stream/330/330360/330360.ism/330360.mpd?ssauth=26816865-330360|0|2681-20170426050258-41d82fd468355b82ef6dbbb6c5c6f2ed&min_bitrate=350

3. I think this is it reaching out for video - https://astream.hotmovies.com/stream/330/330360/330360.ism/dash/330360-video=4994000.dash?ssauth=26816865-330360|0|2681-20170426050258-41d82fd468355b82ef6dbbb6c5c6f2ed

4. And this is audio - https://astream.hotmovies.com/stream/330/330360/330360.ism/dash/330360-audio=62000.dash?ssauth=26816865-330360|0|2681-20170426050258-41d82fd468355b82ef6dbbb6c5c6f2ed

### Comments, logs, screenshots, etc.
These are the variables (that I think could be relevant) that appear in inspector - 

```var jump_start = 0;
var dash_available = true,
video_player = 'silver',
video_id  = '330360',
video_stamp = '1493199519',
video_hash  = '7202e653a20d9c1d7cbc99132c9c31d1',
user_id  = '26816865',
is_not_owner = true,
var BASE_URL  = 'https://www.girlfriendsfilmsvod.com/';
var SECURE_URL  = 'https://secure.vod.com/secure/';
var OWNED_SCENES = '1';
var HAS_PURCHASES = 1;
var is_user_purchased_scene = 0;
var d2o_available = 0
is_user_purchased_scene = 1; 
```

Please let me know if I can provide any additional information, or if there's already a solution and I've just missed it. Thank you!

**Comment by beardypig** [comment]
Should be possible once DASH support is added (I'm working on it).

**Comment by Merlin7x** [comment]
Fantastic! Just knowing there's a chance of success in the future is encouraging. Thank you very much!

**Comment by back-to** [comment]
@Merlin7x 
if you change your User-Agent to an IPhone User-Agent, you will get m3u8 instead of dash urls.

**Comment by gravyboat** [comment]
I'm closing this, we're not adding more NSFW plugins.
