### ISSUE TITLE
tvplayer.com site update

### ISSUE THREAD

**Issue by nicr4wks** [streamlink/streamlink#849]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

The website tvplayer.com has recently undergone an update and now the tvplayer plugin is not able to stream video.

streamlink http://tvplayer.com/watch/clubland best
[cli][info] Found matching plugin tvplayer for URL http://tvplayer.com/watch/clubland
error: No playable streams found on this URL: http://tvplayer.com/watch/clubland

### Expected / Actual behavior

Prior to the website update streamlink found the video stream and played without issue.

### Reproduction steps / Explicit stream URLs to test

1. streamlink http://tvplayer.com/watch/clubland

### Environment details

Operating system and version: ...
Debian Jessie

Streamlink and Python version: ...
streamlink 0.5.0
Python 2.7.9

...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
Closing since #850 is merged.

**Comment by nicr4wks** [comment]
Thankyou @beardypig !

I've updated to latest git and built but now getting `error: Unable to validate JSON: Unable to validate key 'tvplayer': Unable to validate result: Unable to validate key 'response': Unable to validate result: Unable to validate key 'stream': Unable to validate URL attribute 'scheme': u'https' does not equal 'http'`

Is there something extra required for the new plugin?

**Comment by beardypig** [comment]
Looks like they upgraded to https since the PR was created. I have created a new PR to resolve this.

**Comment by ppsspp213** [comment]
How do I use the login?
streamlink https://tvplayer.com/watch/4seven best --tvplayer-email/ bugmenot@mailinator.com --tvplayer-
password bugmenot123

usage: streamlink-script.py [OPTIONS] <URL> [STREAM]
streamlink-script.py: error: unrecognized arguments: --tvplayer-email/ bugmenot@
mailinator.com

**Comment by nicr4wks** [comment]
Try: streamlink --tvplayer-email bugmenot@mailinator.com --tvplayer-password bugmenot123 https://tvplayer.com/watch/4seven

**Comment by ppsspp213** [comment]
error: Unable to open URL: http://api.tvplayer.com/api/v2/stream/live (401 Clien
t Error: Unauthorized for url: http://api.tvplayer.com/api/v2/stream/live)

I know it works with login but it uses 
https://tvplayer.com/watch/565 instead of https://tvplayer.com/watch/4seven once you've logged in.

**Comment by beardypig** [comment]
@ppsspp213 you should have made a new issue for this, it makes the problem more visible. I have created a fix though, in #941.
