### ISSUE TITLE
Remove warning --yes-run-as-root

### ISSUE THREAD

**Issue by TheSneakySniper** [streamlink/streamlink#85]
I feel like this is an easy change, and that it would be beneficial if this message would be replaced with something like:
streamlink is not supposed to be run as root. Are you sure?
(y/n)
The original output is 

`streamlink is not supposed to be run as root. If you really must you can do it by passing --yes-run-as-root.
`
Or just remove it.

**Comment by cdrage** [comment]
Honestly, IMO at least, we should assume the user knows what he's doing.

I find it strange that I purposely do `sudo streamlink` and yet this error pops up.

No Linux program out there I know / have used has done this.

This should be a warning / logging out, rather than explicitly stopping the program.

**Comment by TheSneakySniper** [comment]
I agree.

**Comment by fishscene** [comment]
@cdrage cvlc/vlc specifically denies being run as root. It's quite annoying to work around when creating scripts that run on startup - but I reckon my system is safe and secure.

I see no reason to run this as root, and the fewer things running as root, the less that can go wrong.

Might I propose that not only do we remove the sudo check, but to include instructions to work around running as root in scripts? I'll look through my old scripts and see if I can dig up a practical solution - maybe we can get it posted on the main page after installation instructions or something.

This way, we aren't condoning bad security practice and also giving a practical solution, but at the same time allowing it to be run as root.

**Comment by gravyboat** [comment]
Closing.
