### ISSUE TITLE
Plugin Request: Pluto.tv

### ISSUE THREAD

**Issue by techmouse** [streamlink/streamlink#854]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*
*Also check the list of known issues before reporting an issue!*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I would like to request a plugin for Pluto.tv. It looks like a pretty good site with good content. Unfortunately it would be a pain for weak/old computers to view the content, which would make it great for streamlink.

**Comment by gravyboat** [comment]
Looks like this is via some sort of desktop app? I'm not sure if we've ever added a plugin for something like this before.

**Comment by back-to** [comment]
i can see channel 1000 to 1049, every stream/video is a **youtube/vimeo** video

url for a channel `https://pluto.tv/watch/news-rack`

there are channels like `https://pluto.tv/watch/katy-perry` where it plays a playlist with music,
so every ~5 minutes there would be a new video id from youtube.

this won't really work well with `streamlink`

---
this website won't work with uBlock or uMatrix in the browser ...

> Unfortunately it would be a pain for weak/old computers to view the content,

the best way is just to use youtube, it has a better design than this website 🔨

**Comment by RedPenguin2** [comment]
I would not mind having this site also. It's basically a site that while at times it can do Live like The Young Turks 6-8PM EST or Newsy 24/7 but most of the time it simply plays YouTube videos one after another.

It basically turns YouTube into a more linear type of programming to make watching videos online a lot easier.

**Comment by enzanki-ars** [comment]
The desktop app is an electron app that just shows http://pluto.tv/watch in a window. 

It doesn't seem too difficult to get the M3U8 urls, but the biggest problem is syncing those to Pluto's live timing.  If the stream is not live, but instead using VOD (most channels are like this), then it queues up a full M3U8 file, starting it at XX:XX to match the time.  I did not look into it too hard, but I did not see an easy way to find the start time.  

I may continue looking into getting pluto.tv to work and create a PR for it.

**Comment by techmouse** [comment]
Wow I completely forgot about this.

For clarification, it's not just a program. You can watch streams in your browser, such as this one:
http://pluto.tv/watch/rifftrax

Though I would recommend using Chrome/Chromium because it doesn't seem to play well with Firefox on Linux. Which is another reason why projects like Streamlink are valuable and why a Pluto.tv plugin would be useful.

**Comment by beardypig** [comment]
The main problem I see if that some channels are made up of a series of VOD shows (like @enzanki-ars pointed out). After each show finishes a new stream is loaded, this means that streamlink would only be able to play the current show for those channels.
