### ISSUE TITLE
Can't decode piped data

### ISSUE THREAD

**Issue by aharris02** [streamlink/streamlink#857]
Hi - I'm trying to decode the piped data and seem to be coming up empty.

I've tried piping directly from streamlink-->OpenCV  and I've tried streamlink -> ffmpeg -> OpenCV. Neither works.

streamlink->opencv:
```
pipe = Popen(["streamlink -O --twitch-oauth-token " + self.oauth_token + " -Q twitch.tv/" + self.username + " " + self.quality], stdout = PIPE, bufsize=10**8, shell=True)
```

streamlink->ffmpeg->opencv:
```
pipe = Popen(["streamlink --twitch-oauth-token " + self.oauth_token + " -Q twitch.tv/" + self.username + " " + self.quality + " | ffmpeg -i pipe:0 -c:v rawvideo -r 1 -f image2pipe -"], stdout = PIPE, bufsize=10**8, shell=True)
```

Decoder:
```
raw_image = pipe.stdout.read()
frame = cv2.imdecode(np.frombuffer(raw_image, np.uint8), 1)`
```

Error:
```
File "recorder.py", line 114
    frame = cv2.imdecode(np.frombuffer(raw_image, np.uint8), 1)
cv2.error: /home/user/opencv-3.1.0/modules/imgcodecs/src/loadsave.cpp:490: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_
```

Really appreciate any help you can provide on this.

**Comment by aharris02** [comment]
Logfile from ffmpeg.

[ffmpeg-20170427-164454.txt](https://github.com/streamlink/streamlink/files/962875/ffmpeg-20170427-164454.txt)

**Comment by beardypig** [comment]
Assuming you're using Linux, this might get you in the right direction.
You can use `cv2.VideoCapture` to read from a named pipe. If you create a named pipe and write the twitch stream to that pipe.
```
mkfifo /tmp/stream
streamlink twitch.tv/legema best -o /tmp/stream
```
Then the data will be streamed to /tmp/stream and you can read it from a separate process.

```python
import cv2
import numpy


def extract(path):
    cap = cv2.VideoCapture(path)
    fnum = 0

    try:
        while True:
            # Capture frame-by-frame
            ret, frame = cap.read()
            if ret:
                average_color_per_row = numpy.average(frame, axis=0)
                average_color = numpy.average(average_color_per_row, axis=0)
                print(average_color)
    finally:
        # When everything done, release the capture
        cap.release()


if __name__ == "__main__":
    extract("/tmp/stream")
```

That script will read from the pipe and print the average color per frame :)

Not exactly what you're after, but hopefully it'll point you in the right direction.

**Comment by aharris02** [comment]
Thanks for the tip! That gets me much closer, however seems like it repeatedly loads just the first frame, then everything else sits in the buffer.

What am I missing to bring it full circle?

**Comment by beardypig** [comment]
Change the loop to
```python
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret:
       cv2.imshow('frame', frame)
```
and see if that plays the video stream.

**Comment by bastimeyer** [comment]
I'm going to close the thread since there hasn't been any activity in the past month.
@beardypig also kindly answered the question with some python code examples.

**Comment by Werror** [comment]
@aharris02 @beardypig I know this is closed topic, but when I am using opencv from python I get, 
`Unable to stop the stream: Inappropriate ioctl for device`
I have been searching solution on opencv related threads for a while, but not going anywhere, it would great to share some insight now to make this work...

**Comment by aharris02** [comment]
Sorry, I never ran into that.
I barely recall, but my problem turned out to be a codec issue. Good luck!  





On Tue, Mar 13, 2018 8:22 PM, Werror notifications@github.com  wrote:
@aharris02  @beardypig  I know this is closed topic, but when I am using opencv
from python I get,
Unable to stop the stream: Inappropriate ioctl for device
I have been searching solution on opencv related threads for a while, but not
going anywhere, it would great to share some insight now to make this work...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




Founder/CEO|xSync TechnologiesP: 832.819.0820
E:alan@xsync.com
