### ISSUE TITLE
NRK + DR plug-ins in need of a brush-up.

### ISSUE THREAD

**Issue by Ordval** [streamlink/streamlink#859]
- [x]  This is a plugin (improvement) request.
### Description
The NRK + DR plug-ins seem to be in need of a brush-up.
### Reproduction steps / Explicit stream URLs to test
C:\Users\Ordval>streamlink.exe "https://radio.nrk.no/serie/ren-60/DMPO45004516/10-11-2016" best
[cli][info] Found matching plugin nrk for URL https://radio.nrk.no/serie/ren-60/DMPO45004516/10-11-2016
error: Unable to open URL: mediaelement/DMPO45004516 (Invalid URL 'mediaelement/DMPO45004516': No schema supplied. Perhaps you meant http://mediaelement/DMPO45004516?)
... 
C:\Program Files (x86)\Streamlink Nightly build\bin>streamlink.exe "https://radio.nrk.no/serie/ren-60/DMPO45004516/10-11-2016" best
[cli][info] Found matching plugin nrk for URL https://radio.nrk.no/serie/ren-60/DMPO45004516/10-11-2016
error: Unable to open URL: mediaelement/DMPO45004516 (Invalid URL 'mediaelement/DMPO45004516': No schema supplied. Perhaps you meant http://mediaelement/DMPO45004516?)
  
Valid until  11/05 -17

C:\Users\Ordval>streamlink.exe "https://tv.nrk.no/serie/martin-og-mikkelsen/MUHH49000517/sesong-1/episode-5#" best
[cli][info] Found matching plugin nrk for URL https://tv.nrk.no/serie/martin-og-mikkelsen/MUHH49000517/sesong-1/episode-5#
error: Unable to open URL: mediaelement/MUHH49000517 (Invalid URL 'mediaelement/MUHH49000517': No schema supplied. Perhaps you meant http://mediaelement/MUHH49000517?)

No limitation in time.

### Actual behavior: Can't extract a streams MRL with X-Forwarded-For.
C:\Program Files (x86)\Streamlink Nightly build\bin>streamlink.exe --http-header X-Forwarded-For=159.20.6.38 "https://www.dr.dk/tv/se/kongehuset-2/-/kongehuset-4-4" best
[cli][info] Found matching plugin drdk for URL https://www.dr.dk/tv/se/kongehuset-2/-/kongehuset-4-4
error: No playable streams found on this URL: https://www.dr.dk/tv/se/kongehuset-2/-/kongehuset-4-4
### Actual behavior: Works if an MRL previously been extracted.
C:\Program Files (x86)\Streamlink Nightly build\bin>streamlink.exe --http-header X-Forwarded-For=83.221.132.154 hds://"http://drod03e-vh.akamaihd.net/z/dk/clear/streaming/2a/58f93432a11fa0112c32df2a/Kongehuset--4-4-_7da31e9db2b04323a3614c843e1cfe6f_,1124,562,2389,362,.mp4.csmil/manifest.f4m?g=SRVBGMNWNJLS&hdcore=3.10.0&plugin=aasp-3.10.0.29.28" best
[cli][info] Found matching plugin stream for URL hds://http://drod03e-vh.akamaihd.net/z/dk/clear/streaming/2a/58f93432a11fa0112c32df2a/Kongehuset--4-4-_7da31e9db2b04323a3614c843e1cfe6f_,1124,562,2389,362,.mp4.csmil/manifest.f4m?g=SRVBGMNWNJLS&hdcore=3.10.0&plugin=aasp-3.10.0.29.28
[cli][info] Available streams: 362k (worst), 561k, 1123k, 2386k (best)
[cli][info] Opening stream: 2386k (hds)
[cli][info] Starting player: "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --file-caching=50500

Valid until  4/05 -17

### Environment details
Operating system and version: Win. 10 Home, 64-bit O.S., x64-based processor.
Streamlink 0.5.0, Python version: 3.5.1150.1013
### Comments: 
I have a vague memory that the DR plug-in _could_ extract an MRL with X-Forwarded-For.  
In the DR examples I've limited the tries to only the Nightly build.

**Comment by back-to** [comment]
### NRK.NO

you can find a fix here #881

### DR.DK

_this is some kind of duplicate issue_

#615 X-Forwarded-For works only for the playlist here.
This doesn't work for the api url, you need a proxy for the api #594
