### ISSUE TITLE
Streamlink for Windows (Release)

### ISSUE THREAD

**Issue by RosadinTV** [streamlink/streamlink#86]
**Edit: New more solid version available:**
Download: https://1drv.ms/u/s!AteNlrENG5PD9WVnN1ie5KY8uwIK
*You need Windows Vista SP2 or later with Visual C++ Redistributable for Visual Studio 2015  installed ( https://www.microsoft.com/en-us/download/details.aspx?id=48145 )

-------
Original post (dont recommended):
Hi, i dont know if this is the right place to post this, but i have compiled a portable build of Streamlink (0.0.2) for Windows based on Python 3.5
Some bugs may be present.
Usage is streamlink.exe
Download: https://1drv.ms/u/s!AteNlrENG5PD9WNNY_brnbGTp7dT

**Comment by gravyboat** [comment]
What type of system did you build this on? @cdrage Are we cool with adding this to the release list or do we want to continue investigating the idea of building it in an automated fashion somewhere else? Thanks either way @RosadinTV!

**Comment by RosadinTV** [comment]
I did it with pyinstaller on Windows 10 with trial and error method (i mean keep fixing when a error appears)
Here i made a little guide of how i builded it, but of course is not a really good build method, probably should be a better way to do this. (Also i didnt know any of Python)
Download: https://1drv.ms/u/s!AteNlrENG5PD9WQ0z1RZO7J5Lv1-

**Comment by gravyboat** [comment]
The build should be pretty easy to do thanks to what @sbstp built. @sbstp would you be willing to do a build with your installer method today or tomorrow so we can add it to the release page and have a single executable available?

**Comment by sbstp** [comment]
I've been busy with mid terms so I don't have as much time. I'll try to do it tomorrow. Anyone should be able to produce the installers though, all you need is NSIS and a couple of python packages. It can also be made from Linux. I'll document how to make the installer.

**Comment by gravyboat** [comment]
@sbstp Thanks and good luck with the mid terms!

**Comment by sbstp** [comment]
Ran into issues setting up the `streamlinkrc` file in app data. Might just publish the thing without it for now.

**Comment by sbstp** [comment]
Turns out `pynsist` doesn't have access to the user's appdata folder, only the system one. So we need to rethink how we handle the config file. We could make streamlink copy the file in appdata or change the location of the config file to put it in the installation folder.

**Comment by gravyboat** [comment]
@sbstp Let's just put it in the installation folder. Easy enough to configure from there.

**Comment by Shaaah** [comment]
@gravyboat That's just a quick fix. Ideally, you would want a rc file per user, in the AppData folder.

**Comment by gravyboat** [comment]
@Shaaah Feel free to prep a PR that addresses this issue if you would like to work on it, for now though we need a Windows release available to download.

**Comment by scottbernstein** [comment]
Installation folder may be problematic for people who do not have Admin access under Windows

________________________________

**Comment by sbstp** [comment]
Alright, for now let's just ignore it. People will have to set it up manually for now.

**Comment by thinkpad4** [comment]
This, to build the installer, you need to have NSIS and pynsist installed on your
 system, is a pain in the ass to do.  No chance of pre-making it and listing that on the website.  Cause this, You can download the latest Windows installer `here <https://github.com/streamlink/streamlink/releases is deceiving

**Comment by gravyboat** [comment]
@thinkpad4 We're working on it. Please keep in mind this is an open source project and people who contribute to it are extremely busy with their paying jobs/school/other responsibilities. As soon as we can we'll have a release available on the releases page. We have to make sure everything works as intended and there are as few bugs as possible that a user might encounter.

**Comment by thinkpad4** [comment]
yeah, sorry, I'm just excited to try it.

**Comment by gravyboat** [comment]
@thinkpad4 I totally understand, a lot of us are!

**Comment by sbstp** [comment]
I'm gonna publish it right now based on master.

**Comment by sbstp** [comment]
Ok it's there. Try it and let me know how it goes.

**Comment by gravyboat** [comment]
Sounds good, thanks @sbstp! I'll try it out tonight.

**Comment by gravyboat** [comment]
Okay tested it out and everything seems to work fine minus the path to VLC being incorrectly set so it just bombs out. I didn't see any sort of config that's set to modify the default player (it doesn't detect where VLC is installed obviously) so I adapted my existing Livestreamer powershell script to handle it (https://github.com/gravyboat/streamlink-powershell). I assume most people are just calling the executable via the powershell command line, or basic command line manually right now? Either way it's currently working as long as you pass through the appropriate options. If I missed where the config exists let me know @sbstp.

**Comment by sbstp** [comment]
On my machine it finds VLC without having to specify the path. Did you install VLC in a non standard location?

**Comment by gravyboat** [comment]
@sbstp Yeah I did, I store applications on a secondary hard drive.

**Comment by sbstp** [comment]
Yeah that's probably why. I don't think there's an easy way of detecting where VLC is installed, maybe there's something in the registry.

**Comment by dojima** [comment]
Will it be possible to just get a ZIP file containing all of the necessary files similar to Livestreamer in the future?

Thanks.

**Comment by gravyboat** [comment]
@sbstp Yeah it's no big deal. I would use the powershell script no matter what, so unless we have a config strictly for Streamlink it doesn't really matter. I'm not sure how this was configured previously for Livestreamer. @dojima We have some archived releases here: https://github.com/streamlink/streamlink/releases but I don't think there's a version for Windows if that's what you are asking.

**Comment by gravyboat** [comment]
@RosadinTV I would like to close this issue if you're cool with it now that a release is available.

**Comment by dojima** [comment]
@gravyboat Yes, was referring to a Windows version.  Basically something exactly like what @RosadinTV created.

**Comment by RosadinTV** [comment]
@gravyboat  Yes, i think that now is time to close this issue 😉
