### ISSUE TITLE
Ustream plugin been failing past few days

### ISSUE THREAD

**Issue by highflux7** [streamlink/streamlink#862]
Past few days Ustream plugin has been failing like so:

``streamlink http://www.ustream.tv/decoraheagles
[cli][info] Found matching plugin ustreamtv for URL http://www.ustream.tv/decoraheagles
[plugin.ustreamtv][error] Unable to fetch desktop streams: Unable to validate result: Unable to validate key 'stream': Unable to validate result: Unable to validate key 'streams': Unable to validate result: Type of ScriptDataReference(reference=7) should be 'dict' but is 'ScriptDataReference' or Type of ScriptDataReference(reference=7) should be 'list' but is 'ScriptDataReference' or Key 'varnishUrl' not found in ScriptDataObject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'streams', ScriptDataReference(reference=7)), (u'streamType', u'flv/segmented')]) or [ScriptDataObject([(u'name', u'uhs_akamai'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-akamai.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'url', u'http://uhs-akamai.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'streams', [ScriptDataObject([(u'chunkTime', 5000.0), (u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1493386770', u'1833acdea1'), (u'1493386760', u'47e3e540de'), (u'1493386780', u'8c82758c8f')])), (u'offset', 0.0), (u'isTranscoded', False), (u'width', 1920.0), (u'bitrate', 3899.0), (u'chunkId', 1493386767.0), (u'streamName', u'1/chunk_%_%.flv'), (u'height', 1080.0), (u'videoCodec', u'H264')]), ScriptDataObject([(u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1493386770', u'1833acdea1'), (u'1493386760', u'47e3e540de'), (u'1493386780', u'8c82758c8f')])), (u'offset', 0.0), (u'description', u'720p'), (u'bitrate', 1952.0), (u'preset', u'viewer_720p'), (u'chunkId', 1493386767.0), (u'streamName', u'2/chunk_%_%.flv'), (u'chunkTime', 5000.0), (u'resolutionFromPreset', u'720p'), (u'isTranscoded', True), (u'width', 1280.0), (u'height', 720.0), (u'videoCodec', u'H264')]), ScriptDataObject([(u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1493386770', u'1833acdea1'), (u'1493386760', u'47e3e540de'), (u'1493386780', u'8c82758c8f')])), (u'offset', 0.0), (u'description', u'480p'), (u'bitrate', 969.0), (u'preset', u'viewer_480p'), (u'chunkId', 1493386767.0), (u'streamName', u'5/chunk_%_%.flv'), (u'chunkTime', 5000.0), (u'resolutionFromPreset', u'480p'), (u'isTranscoded', True), (u'width', 854.0), (u'height', 480.0), (u'videoCodec', u'H264')]), ScriptDataObject([(u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1493386770', u'1833acdea1'), (u'1493386760', u'47e3e540de'), (u'1493386780', u'8c82758c8f')])), (u'offset', 0.0), (u'description', u'360p'), (u'bitrate', 762.0), (u'preset', u'viewer_360p'), (u'chunkId', 1493386767.0), (u'streamName', u'4/chunk_%_%.flv'), (u'chunkTime', 5000.0), (u'resolutionFromPreset', u'360p'), (u'isTranscoded', True), (u'width', 640.0), (u'height', 360.0), (u'videoCodec', u'H264')]), ScriptDataObject([(u'offsetInMs', 0.0), (u'chunkRange', ScriptDataObject([(u'1493386770', u'1833acdea1'), (u'1493386760', u'47e3e540de'), (u'1493386780', u'8c82758c8f')])), (u'offset', 0.0), (u'description', u'240p'), (u'bitrate', 501.0), (u'preset', u'viewer_240p'), (u'chunkId', 1493386767.0), (u'streamName', u'3/chunk_%_%.flv'), (u'chunkTime', 5000.0), (u'resolutionFromPreset', u'240p'), (u'isTranscoded', True), (u'width', 426.0), (u'height', 240.0), (u'videoCodec', u'H264')])])]), ScriptDataObject([(u'name', u'uhs_comcast'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-comcast.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'url', u'http://uhs-comcast.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'streams', ScriptDataReference(reference=7))]), ScriptDataObject([(u'name', u'uhs_llnw'), (u'streamType', u'flv/segmented'), (u'varnishUrl', u'http://uhs-llnw.ustream.tv/a/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'url', u'http://uhs-llnw.ustream.tv/a/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'streams', ScriptDataReference(reference=7))]), ScriptDataObject([(u'name', u'uhs_tcdn'), (u'url', u'http://uhs-live-default.ustream.tv/dal09/dal09-uhs-omega01/live/3064708/1493381081518/plain/uhs/'), (u'streams', ScriptDataReference(reference=7)), (u'streamType', u'flv/segmented')])] does not equal 'offline'
error: No playable streams found on this URL: http://www.ustream.tv/decoraheagles
``

(Same results with old livestreamer.)
Have tried different ustream streams/urls with same results.  Possible they're using a new flash player?  (new/change? idn..)

Running ubuntu 16.04, streamlink 0.5.0

tks,

**Comment by beardypig** [comment]
This has been fixed in the latest development builds, which you can install using `pip` from the git repo, or wait until next week for the `0.6.0` release :)

**Comment by gravyboat** [comment]
Thanks for the report! As @beardypig noted this has been resolved so I'm going to close this out for now.
