### ISSUE TITLE
Windows package without installer

### ISSUE THREAD

**Issue by ukoz** [streamlink/streamlink#863]
- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

Hello.
Is it possible to make livestreamer-like Windows distro?
Or, please, can someone post correct post-install directory structure so I can unpack installer and make it work?
You can get it with `dir /a /s /O:GN` command.
Thanks.

**Comment by ukoz** [comment]
There is whole additional program to make no-install version of streamlink.
Problem solved.

**Comment by beardypig** [comment]
There is also a zip file version: https://github.com/beardypig/streamlink-portable (created by me) :-)
