### ISSUE TITLE
WWE Network plugin error

### ISSUE THREAD

**Issue by djflakf1** [streamlink/streamlink#864]
im getting this error when i tried to use stream link 

C:\Program Files (x86)\Streamlink\bin>streamlink --wwenetwork-email xxxxx --wwenetwork-password xxxx http://network.wwe.com/video/v1252266383 best
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/vide
o/v1252266383
error: Could not load streams: Sign-on restriction: Too many usage attempts (-35
00)

**Comment by beardypig** [comment]
I saw that error when developing the plugin when I requested a stream too many times in a short period of time. Leave it for 10 mins and try again. 

Does it work in the browser? Are you sharing a username/password with someone else?

**Comment by djflakf1** [comment]
now is working but can you say me how can i download the video?

**Comment by beardypig** [comment]
Please read the documentation, particularly this part: https://streamlink.github.io/cli.html#file-output-options

**Comment by djflakf1** [comment]
to be honest im so noob in this, im trying to understand what i must to do sorry

**Comment by beardypig** [comment]
Like this `streamlink <url> <quality> -o output.ts`

**Comment by djflakf1** [comment]
i did this :) and this is the result 

C:\Program Files (x86)\Streamlink\bin>streamlink --wwenetwork-email aggiecto@gmail.com --wwenetwork-password rouges04 http://network.wwe.com/video/v1331577883 best -o output.ts
[cli][info] Found matching plugin wwenetwork for URL http://network.wwe.com/video/v1331577883
[cli][info] Available streams: 224p_650k (worst), 288p_990k, 360p_1450k, 504p_2100k, 540p_2700k, 720p_3500k (best)
[cli][info] Opening stream: 720p_3500k (hls)
error: Failed to open output: output.ts ([Errno 13] Permission denied: 'output.ts')
[cli][info] Closing currently open stream...

**Comment by beardypig** [comment]
That means you cannot write to that directory, try another. 
`streamlink --wwenetwork-email xxx@gmail.com --wwenetwork-password xxx http://network.wwe.com/video/v1331577883 best -o c:\output.ts`

You should not have to run streamlink.exe from that directory either, unless you have it installed more than once.

**Comment by djflakf1** [comment]
Thanks a lot @beardypig  you are the best in the whole world !

**Comment by beardypig** [comment]
@djflakf1 I take that means you worked it out :)
