### ISSUE TITLE
Plugin request: streannlive-lh.akamaihd.net

### ISSUE THREAD

**Issue by skilleek** [streamlink/streamlink#869]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

A simple plugin to open the stream available at http://www.ellobo106.com/index.php/vivo/solo-3audio

**Comment by gravyboat** [comment]
Closing since #887 is merged.
