### ISSUE TITLE
vaughnlive.tv new INFO_URL

### ISSUE THREAD

**Issue by mmetak** [streamlink/streamlink#87]
I had to replace line 8 in:
"/usr/lib/python3.5/site-packages/streamlink/plugins/vaughnlive.py"
with:
`PLAYER_VERSION = "0.1.1.765"`
`INFO_URL = "http://mvn.vaughnsoft.net/video/edge/mzn-{domain}_{channel}?{version}_{ms}-{ms}-{random}"`
to make it work again.

btw: I also maintain streamlink AUR packages. ;-)
https://aur.archlinux.org/packages/streamlink/
https://aur.archlinux.org/packages/streamlink-git/

**Comment by gravyboat** [comment]
Do you want to prep a PR for that vaughnlive change?

**Comment by mmetak** [comment]
#88

**Comment by gravyboat** [comment]
Closing as this is fixed. @cdrage @mmetak has linked some archlinux packages, do you want to add these to the docs?
