### ISSUE TITLE
Plugin request: oneplay.tv

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink#874]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

Hello all,

I was wondering if it was possible to create a pluging for the following website:
http://oneplay.tv

It is a great site with many live channels.

Thank you for the consideration :)

**Comment by RosadinTV** [comment]
The biggest problem I encounter in this is legality, that page has streams of paid channels (such as FOX, Space, A&E, etc.) that are probably probably illegally retransmitted.

**Comment by back-to** [comment]
OP is already a **ghost** and the official source should be used for tv channels
