### ISSUE TITLE
Nightly Hosting Costs

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#877]
I have been reviewing the costs for hosting the nightly builds of streamlink on S3. For the month of April, `streamlink-lastest.exe` was downloaded 11,228 times and used 133GB of transfer bandwidth. The cost of transfers was $11.98 and the cost of storage and HTTP requests was $0.69, with a total cost of $12.67+tax. With the gaining popularity of `streamlink` I can only see that cost increasing, I would like to reduce the cost a bit ($15 a month is fairly expensive for me.) 

With the addition of `ffmpeg` we added some nice features, and the possibility for further future enhancements, but we also bloated the installer (and the git repo, as discussed on other issues.) The installer is approx. 38MB including the `ffmpeg.exe`, and approx. 15MB without `ffmpeg.exe`. 

I was thinking we could remove `ffmpeg` from the installer and either allow the user to install it themselves, or download the `ffmpeg.exe` on demand in the installer. I prefer the download during the installer option as it means the user doesn't have to install it manually but the installer is smaller (we can download `ffmpeg.exe` from github). 

Alternatively we could set up a different repo with scheduled builds on travis, to build the nightly periodically and automatically add a release to that repo. 

Thoughts @gravyboat, @bastimeyer, @cdrage?

**Comment by dehesselle** [comment]
Is storage space (how much?) and bandwidth (133 GB/month) offered by a 3rd party something that would help you / you might consider?

**Comment by cdrage** [comment]
@beardypig Totally agree with regards to removing ffmpeg.exe

Any form of binary removal would be great..

Off-topic, but instead of S3, would hosting on something like Vultr (2.50$ instances) with a streamlink.io domain work better in the long-run?

**Comment by unlocKing** [comment]
I have unlimited bandwith and plenty of space on my server which I use to provide EPG data to various tv guides.

If you're interested I can give you space there at no cost as I'm already paying for unlimited bandwith.

**Comment by cdrage** [comment]
Only problem is implementation. 

Perhaps similar to how we have it setup with syncing with docs, we can have an encrypted SSH key and do an scp upload from Travis to the aforementioned hosting service

**Comment by beardypig** [comment]
Storage space is small (<5GB, I only keep the last 60 days worth of builds around). A VPS would work, but it's not always 100% reliable and will require maintenance, and a domain name is another thing that would have to be managed, I would rather keep it as low maintenance as possible. I'm starting to think that GitHub releases on a separate repo might be the least troublesome...

**Comment by bastimeyer** [comment]
I'd say that we should see if we can use a free service of a real hosting provider before going the route of using a private server.

On Bintray you can get 1TB/m of bandwidth and 10GB/m of storage for free in their open-source plan.
https://bintray.com/account/pricing?tab=account&type=pricing
This should be enough for now and can be easily set up in travis. I have tested this a couple of times in the past months and it worked quite well. I was using it for custom DEB and RPM repos though and custom code was required for signing the repos (due to a bug of Travis' deploy module), but this isn't required here, since we'd only upload binaries for Windows anyway.

If this isn't enough and paid servers/services are required, I'd recommend the dedicated servers of OVH, which all have unlimited bandwidth and start at 5€. You can even get a dedicated server for a couple of bucks (https://www.kimsufi.com/en/). I'm using dedicated OVH servers since 2008 and it's a much better idea than S3, at a fixed cost.

And as another alternative, we could still use a separate repo on github and upload nightlies by using Github's release API, like I've mentioned in the other thread a couple of days ago.

Btw, I like the idea of building real nightlies. This saves storage space, computation time in the CI env and is a better scheme overall. Even if it comes at the cost of not being able to let people test newly committed code, those people can still use git, pip or other methods instead, which should be okay for those who are interested in "real-time development" here.

**Comment by gravyboat** [comment]
Jeez that's a lot of downloads on the nightly! I feel like our best bet is to keep everything centralized on GitHub and just create another repo then use the release API. All we have to do is set up Travis with push access to the repository and we should be set to go. Bastimeyer also proposes some good solutions. @beardypig What have your total costs been for all S3 hosting in the past few months?

**Comment by beardypig** [comment]
Maybe $40-50 total, last month was almost twice the previous month. Bintray looks interesting and cleaner than doing it on github; I'm in favour of the least maintenance, lowest cost solution. I will take a look at migrating to bintray, @bastimeyer do you have an example travis config for deploying to bintray?

**Comment by bastimeyer** [comment]
@beardypig 
It's fairly easy, you just need to create a repo and a package on the Bintray website. To upload files via Travis, you need to build a JSON descriptor file that's being used by the Travis deploy config.
See the docs here:
https://docs.travis-ci.com/user/deployment/bintray/
https://github.com/travis-ci/dpl#bintray

Here's an example:
https://github.com/streamlink/streamlink-twitch-gui/blob/packages/.travis.yml#L56-L71
https://github.com/streamlink/streamlink-twitch-gui/blob/packages/build/resources/package/deb/bintray.json

**Comment by beardypig** [comment]
Thanks @bastimeyer, it is pretty easy. Just need to pick a suitable repo and package name...

I have created an organisation called `streamlink`. I added a repo called `streamlink` with a `streamlink-nightly` package. However, I'm not sure about the naming for the repo, perhaps it should be `streamlink-windows`? I don't really know what the BinTray convention is. 

I have tested it out with the `streamlink/streamlink/streamlink-nightly` package deploying from travis and it appeared to work OK, just need to finalise the repo name. 

Also, if @bastimeyer, @gravyboat, and @cdrage could ping me your bintray account name I'll add you as admins, (you'll probably have to sign up, I did it via Github.)

**Comment by beardypig** [comment]
We can always add release docs later :) I just wanna get the hosting off S3 first :)

I have updated the repo name to `streamlink-nightly` and the package name to `streamlink`, the URL is better as you say :) 

I think I will also move my `streamlink-portable` package over there too, not sure about putting it in the `streamlink` org as the name conflicts with @RosadinTV's portable version :)

**Comment by cdrage** [comment]
@beardypig Account name same as here :)

**Comment by thinkpad4** [comment]
Will the nightly on the new repo still be called streamlink-latest.exe?  So when I explain to people how to download it they don't get confused

**Comment by beardypig** [comment]
@thinkpad4 I'm trying to work out how to retain that functionality :)

**Comment by bastimeyer** [comment]
How does bintray sort this list?
https://dl.bintray.com/streamlink/streamlink-nightly/
If it's in descending order, I'd say that there's no need for a "-latest" file.

**Comment by bastimeyer** [comment]
Btw, the files need a different name, something like `git describe` (`streamlink-0.5.0-1337+gdeadbee`), so they can be ordered.

**Comment by beardypig** [comment]
It's easier to directly link to the latest version in the docs, @thinkpad4 makes a good point - it's better for our users. I have managed to do that by creating a "latest" version which gets updated (https://dl.bintray.com/streamlink/streamlink-nightly/streamlink-latest.exe). Bintray seems to sort the list in ascending order too, as it's just a list of files in this case - latest at the bottom. 

I am going to rename the files to include the date (`streamlink-0.5.0-20170505.exe`), and configure the builds to be updated only **once** per day (in true nightly fashion). The Bintray version numbers will be the date (`2017.05.05`), with the description containing the short commit hash. Only updating once per day will help us keep under the storage limit for a while, but I'd also like to push forward with removing the `ffmpeg.exe` from the installer and get it downloading on-demand during the installation.

**Comment by beardypig** [comment]
All done. No more S3 nightlies :)
