### ISSUE TITLE
[Question] Download youtube live stream from the start(seek)

### ISSUE THREAD

**Issue by SergioLuisBerto** [streamlink/streamlink#878]
Hi, is there a way to download a live video from youtube from the start instead of from the current time (i.e. seek to the start)?

I am able to download with the command line **streamlink "URL" best -o out.ts**, but it starts downloading from the current time but i want the complete video.

I've read the command-line documentation and i couldn't find any "seek like" option. Am I missing something here or there's no way to do this using this software?

**Comment by gravyboat** [comment]
Not as far as I'm aware. You might want to give youtube-dl a shot: https://rg3.github.io/youtube-dl/

**Comment by flijloku** [comment]
@SergioLuisBerto I think yes!
https://github.com/rg3/youtube-dl/issues/11618
https://streamlink.github.io/cli.html#cmdoption-hls-live-edge

**Comment by gravyboat** [comment]
@flijloku Good find, I didn't think that the live-edge option would work for that!

**Comment by SergioLuisBerto** [comment]
Thanks a lot! Will give it a try on the next opportunity.

**Comment by beardypig** [comment]
There is an option in the HLS stream parser to restart from the start of the stream, if possible. It's not exposed as a command line option, but we could easily expose it.

**Comment by scottbernstein** [comment]
+1 for adding that as a CLI option

________________________________

**Comment by back-to** [comment]
`--hls-live-restart`
would be covered by #1303

**Comment by gravyboat** [comment]
Going to close since I merged #1303, please give the nightly a shot once it builds.

**Comment by tp0** [comment]
> @SergioLuisBerto Did you find a solution for this

The solution is `--hls-live-restart`.

**Comment by darajava** [comment]
Anyone facing a problem with getting live stream segments - Make sure you are using the most recent version of streamlink. For some reason the version in the Ubuntu archives is quite old and doesn't work properly (though has the same options). The newer version works well.

**Comment by ohhai** [comment]
There is no `--hls-live-restart` option for now.
Is it deleted?
I see nothing which might be related in options list.

**Comment by bastimeyer** [comment]
> There is no `--hls-live-restart` option

https://streamlink.github.io/cli.html#cmdoption-hls-live-restart

----

YT live stream rewinding is currently not possible. See #2936

Locking, as this thread is almost 4 years old
