### ISSUE TITLE
Plugin request : vk.com streams

### ISSUE THREAD

**Issue by solham** [streamlink/streamlink#879]
----

### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

vk.com have introduced live streams, hereby requesting a plugin for this if possible

### Reproduction steps / Explicit stream URLs to test

https://vk.com/video-9944999_456239622
The stream on this page should be accessible without needing to login to vk, the embed code follows:
`<iframe src="https://vk.com/video_ext.php?oid=-9944999&id=456239622&hash=5ee41bc00ebc765a" width="640" height="360" frameborder="0" allowfullscreen></iframe>`

Further examples that should be live at all times:
https://vk.com/video-24136539_456239830
https://vk.com/video-34453259_456240574

**Comment by azes** [comment]
Another example: https://vk.com/user?z=video46662242_456240009

**Comment by gravyboat** [comment]
Closing since #1063 is merged.
