### ISSUE TITLE
How to download a specific time period of youtube livestream video 

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#884]
### Checklist

- [] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I am downloading this video https://www.youtube.com/watch?v=1EiAdUWJ4yg
Using this cmd line: streamlink --hls-live-edge 99999 --hls-segment-threads 5 -o "C:\Users\=i\Videos\ok.ts" https://www.youtube.com/watch?v=1EiAdUWJ4yg best
But it downloads the whole video from the starting.
The video I am downloading is channel stream and it is always streaming. The last 3hrs of the live stream are available on youtube.  How can I download a specific time period from that 3hr live video clip?
For example, I want to download from -2 hours 30min  to -1 hour 30 min where 0 hours 0 mins is the current time. 

Thanks

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by ukoz** [comment]
Please, add same feature for Twitch, example URL
http://www.twitch.tv/jcarverpoker/v/17258524?t=1h56m0s
or in new format
https://www.twitch.tv/videos/17258524?t=1h56m0s

**Comment by X1011** [comment]
I believe #614 would cover this.

**Comment by janemaydaily** [comment]
You may also try this method http://www.allavsoft.com/how-to/download-livestream-video.html

**Comment by bastimeyer** [comment]
I've edited this comment, since I think it is spam (linking to a proprietary "stream capture" software that looks like it's a SEO fake site, posted by a fresh account)... If I see it again, I'll use the report function.

**Comment by back-to** [comment]
would be covered by #1303

**Comment by gravyboat** [comment]
Closing since I merged #1303, please give the nightly a shot once it builds, we can reopen if needed.
