### ISSUE TITLE
zengatv

### ISSUE THREAD

**Issue by rusty148** [streamlink/streamlink#890]
The site is :http://www.zengatv.com/live/f132cc60-7635-4b74-b4e9-ce8c43727635.html
I can not download this using this cmd line command: streamlink --o Filename http://www.zengatv.com/live/f132cc60-7635-4b74-b4e9-ce8c43727635.html

Please help me regarding this.
Thanks

----

### Checklist

- [ ] This is a bug report.
- [ x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
We don't currently support downloading video from that site. Feel free to submit a plugin request (with additional details regarding how the site works) and someone will take a look if they're interested in doing so.

**Comment by johnthecracker** [comment]
set url=http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD251L720P/playlist.m3u8
streamlink.exe --http-header "Referer=http://www.zengatv.com/live/f132cc60-7635-4b74-b4e9-ce8c43727635.html" hlsvariant://%url% best

[url=https://postimg.org/image/obc5k28yf/][img]https://s15.postimg.org/8puu03x0b/Untitled.png[/img][/url][url=https://postimage.io/]image hosting no registration[/url][url=https://certificity.com]certificity.com[/url]

**Comment by johnthecracker** [comment]
Here is CNN on zengatv:

No need to get right referer, yesterday's from another zenga channel works:


C:\MISC\STREAMLINK>set url=http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD177L720P/playlist.m3u8

C:\MISC\STREAMLINK>streamlink.exe --http-header "Referer=http://www.zengatv.com/live/f132cc60-7635-4b74-b4e9-ce8c43727635.html" hlsvariant://http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD177L720P/playlist.m3u8 best
[cli][info] Found matching plugin stream for URL hlsvariant://http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD177L720P/playlist.m3u8
[cli][info] Available streams: 144p (worst), 240p, 360p, 480p (best)
[cli][info] Opening stream: 480p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe --file-caching=5000

**Comment by rusty148** [comment]
Hey, Thank you so mych, it works

Please also help me with this one: http://www.zengatv.com/ddnational.html

I was trying this : --http-header "http://www.zengatv.com/ddnational.html" --player "C:\Program Files (x86)\Windows Media Player\wmplayer.exe" -o "C:\Users\p00055705\Videos\Rec\dd1.mp4" hlsvariant://http://d1hya96e2cm7qi.cloudfront.net/Live/_definst_/amlst:sweetbcha1novD251L720P/playlist.m3u8 best

but it did not help

**Comment by johnthecracker** [comment]
@rusty

I tried:  http://www.zengatv.com/ddnational.html

and player displays: "This content is currently unavailable"

**Comment by Rusty** [comment]
I think you have the wrong rusty. Sorry I can't help.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gravyboat** [comment]
I'm going to close this. I looked at the site today and it's all a bunch of stolen TV streams and so forth.
