### ISSUE TITLE
How to edit the this rtmp link in Bongacams plugin

### ISSUE THREAD

**Issue by horacio9a** [streamlink/streamlink#891]
I added a line 135 in bogacams.py:
rtmp_params = {stream_source_info['localData']['NC_ConnUrl']}

I got for example:
rtmp_params = set([u'rtmp://66.254.97.130:1935/bongacams'])

My desire is to get only a link without brackets like this:
rtmp_params = rtmp://66.254.97.130:1935/bongacams

How to edit the this rtmp link? I try get ip address only with:
ipa_ = stream_params.split("rtmp://")[1]
ipa = ipa_.split(":1935")[0]

But it doesn't work in this case:(

----

### Checklist

- [ ] This is a bug report.
- [x ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

Operating system and version: Windows 7
Streamlink and Python version: Python 2.7.13

### Comments, logs, screenshots, etc.

https://s20.postimg.org/oahajex4t/BC_py.jpg

**Comment by back-to** [comment]
@horacio9a 
you don't need the brackets here
`rtmp_params = {stream_source_info['localData']['NC_ConnUrl']}`
use it like
`rtmp_params = stream_source_info['localData']['NC_ConnUrl']`

result should be
`rtmp_params = rtmp://123.123.123.123:1234/abc`

**Comment by horacio9a** [comment]
Now I'm laughing at myself as I did not remember it. In any case, thank you very much. The result is this:

https://s20.postimg.org/kj7px3jgd/BC_py1.jpg

My ultimate goal is now very close ... stretch a little ;)
