### ISSUE TITLE
tmi.twitch.tv is down, streamlink doesnt work

### ISSUE THREAD

**Issue by Herny64** [streamlink/streamlink#893]
tmi.twitch.tv is down and because of that streamlink doesnt work
```

$streamlink https://www.twitch.tv/summit1g best --player mpv -l debug
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/summit1g
[plugin.twitch][debug] Getting live HLS streams for summit1g
^[4error: Unable to open URL: https://tmi.twitch.tv/hosts (HTTPSConnectionPool(host='tmi.twitch.tv', port=443): Max retries exceeded with url: /hosts?as3=t&include_logins=1&host=26490481 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcce5ebda20>, 'Connection to tmi.twitch.tv timed out. (connect timeout=20.0)')))
```

Should this break streamlink ? I thought tmi.twitch.tv is only for chat and hosting.
http://tmi.twitch.tv/
http://isdown.me/tmi.twitch.tv

**Comment by beardypig** [comment]
The `tmi` host is used to check for hosted channels. However, I'm not having any trouble playing that stream.

**Comment by gravyboat** [comment]
I can't duplicate this either, stream loads fine for me.

**Comment by Herny64** [comment]
is it possible to catch that exception, so streamlink would play the video instead of crashing ?

**Comment by beardypig** [comment]
http://tmi.twitch.tv/ isn't down for me. It's reporting a 404, which sounds normal for a non-existent API endpoint. Are you sure it's not an issue on your end? Maybe you are using a proxy that is not working or something similar?

**Comment by Herny64** [comment]
i did a traceroute and its aborting after 10 hops. its my ISP.

**Comment by gravyboat** [comment]
@Herny64 Thanks for confirming! I'm going to close this for now.
