### ISSUE TITLE
How do I use a different video player for youtube streams??

### ISSUE THREAD

**Issue by Dompyre** [streamlink/streamlink#895]
By default it opens up VLC, how do I make it open up MPC-HC instead?

**Comment by gravyboat** [comment]
Please considering reviewing the documentation as this is covered thoroughly over there: https://streamlink.github.io/cli.html#player-options I'm going to close this.

**Comment by Dompyre** [comment]
I read it and didn't really understand anything, not a coder all I see is text

**Comment by gravyboat** [comment]
@Dompyre I've proposed a PR to add some additional notes to the documentation to ensure things are clear.
