### ISSUE TITLE
How to save each .ts segment while twitch broadcast is live?

### ISSUE THREAD

**Issue by trygog** [streamlink/streamlink#900]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

-o option only saves into 1 file. Instead of piping each segment to vlc, can it be piped to just the hard disk folder and each segment be saved?

**Comment by beardypig** [comment]
`streamlink` is not designed to work this way, it is designed to produce a single, often continuous, video stream. You could write a custom HLS stream downloader to do this yourself though :)

**Comment by trygog** [comment]
I just recently learned how to extract m3u8 but I don't know how to extract links for .ts files. It only shows the file segment filenames. Can you please direct me to a thread/source where I can learn how to make one? I'm a beginner in C# but I can always learn other languages. Thank you.

**Comment by beardypig** [comment]
The file names are normally listed as relative URLs, relative to the m3u8 URL. If the m3u8 URL is `http://example.com/tv1/master.m3u8` and it contains the names of the segments `001.ts, 002.ts, etc.` they will be located at `http://example.com/tv1/001.ts, etc.`. There is quite a lot of documentation about how HLS works, particularly on the Apple Developer website.

**Comment by trygog** [comment]
It worked! Thank you beardypig!

**Comment by bastimeyer** [comment]
Going to close the thread, since the question has been answered by @beardypig. Thanks!
