### ISSUE TITLE
Plugin request for NEW SmashCast TV (merger of Azubu and Hitbox)

### ISSUE THREAD

**Issue by HerbertEttore** [streamlink/streamlink#904]
This week finally came the result of the merger between Azubu and Hitbox.
The new [Smashcast TV.](https://www.smashcast.tv/)
Now, we need a plugin for this new platform. :)

Thanks to all the Streamlink developers.

**Comment by TaoziDB** [comment]
the old hitbox plugin still works, you just need change the current smashcast.tv link to hitbox.tv link, for example: from "https://www.smashcast.tv/aravingloon" to "https://www.hitbox.tv/aravingloon"

**Comment by HerbertEttore** [comment]
It's true, I had not tried it, it really works.
So I think it's easy to create a new plugin, basically swap the url from hitbox to smachcast in the plugin.
I'll try to change that.

**Comment by HerbertEttore** [comment]
DONE! 👍 
[smashcast.zip](https://github.com/streamlink/streamlink/files/988560/smashcast.zip)
