### ISSUE TITLE
How can i convert broadcast to m3u8 ? (ustream.tv)

### ISSUE THREAD

**Issue by noyoof** [streamlink/streamlink#908]
How do I convert the broadcast to m3u8? (ustream)

www.ustream.tv/channel/23193829

Please Help

**Comment by noyoof** [comment]
Please Help

**Comment by back-to** [comment]
@noyoof 
If you want to watch the link with streamlink.

Install the last nightly version
- Windows
https://dl.bintray.com/streamlink/streamlink-nightly/

- linux / pip
`pip install -U git+https://github.com/streamlink/streamlink.git`

---

But you won't get just the m3u8 link, it works only with streamlink.

**Comment by noyoof** [comment]
@back-to
I don't understand much English.

But can you tell me, can you help me?

**Comment by noyoof** [comment]
Where are the experts in the field?

**Comment by back-to** [comment]
If you can't understand english well, just use https://translate.google.com/

---

You  can play the ustream video with 'streamlink'

- for windows install this EXE file ~40MB
https://dl.bintray.com/streamlink/streamlink-nightly/streamlink-latest.exe

or

- for linux use pip
`pip install -U git+https://github.com/streamlink/streamlink.git`

---

the m3u8 link will only work with 'streamlink'
 @noyoof

**Comment by noyoof** [comment]
Do you have a video explanation of how I can convert the broadcast to m3u8? (ustream.tv)

**Comment by noyoof** [comment]
@back-to
Do you have a video explanation of how I can convert the broadcast to m3u8? (ustream.tv)

**Comment by beardypig** [comment]
@noyoof why do you _need_ the m3u8 URL? What is wrong with using Streamlink to pipe the video to VLC?

**Comment by noyoof** [comment]
I want to extract the direct link, and run it on my site ( m3u8 _ ustream.tv ).

Such a link when it was working days ago:
http://sjc-uhls-frontproxy.ustream.tv/uhls/23193829/streams/live/iphone/playlist.m3u8

> www.ustream.tv/channel/23193829

**Comment by noyoof** [comment]
@beardypig 
I need m3u8 and put it on my site
Is very important to me, please help and extract the new link

**Comment by beardypig** [comment]
Anything wrong with using the standard embed feature from ustream.tv?

**Comment by noyoof** [comment]
@beardypig
Quality can not be selected for viewers over the phone (embed)

> I apologize for the English language I have weak.

**Comment by noyoof** [comment]
@beardypig
Is there a way to extract the broadcast and convert it to m3u8?

**Comment by beardypig** [comment]
Not that I am aware of. @ebanafea might have a way, but I do not understand how.

**Comment by noyoof** [comment]
@beardypig
Is it possible to edit on embed and enable quality selection for viewers over the phone?

**Comment by beardypig** [comment]
No idea, that is something that you should raise with ustream.tv.

**Comment by noyoof** [comment]
@beardypig
Ok, thank you.

_
We wait for the experts

-
This link was working days ago but UStream stopped m3u8:
 http://sjc-uhls-frontproxy.ustream.tv/uhls/23193829/streams/live/iphone/playlist.m3u8

**Comment by beardypig** [comment]
M3U8 URLs are still available, but you have to request them via the UStream API and they are tied to a token. The token only stays valid while you are connected to the UStream API. You could write a small web application that does the same thing as streamlink except provides an M3U8 URL.

**Comment by noyoof** [comment]
@beardypig
Do you have a link to a page, where I can request m3u8?

Or can you request me a m3u8 link to this channel? www.ustream.tv/channel/23193829

**Comment by beardypig** [comment]
I could, but by the time you read the message it will no longer work. It requires a token that expires very quickly unless you maintain a connection to the UStream API.

**Comment by noyoof** [comment]
@beardypig
No problem, you can send the method or direct link.
We will try to find a radical solution to this problem.

**Comment by beardypig** [comment]
The URLs are like this: http://c742ecf9-lp-omega.ums.ustream.tv/playlist/auditorium/channel/23193829/playlist.m3u8?token=xxxxxx_1494517110483&appType=11&appVersion=2&ts=1494517111&chunkingType=improved&geo=XX&sgn=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&cdnHost=uhs-akamai.ustream.tv/ but it will do you little good. You can find your own temporary stream URL by using the developer tools in your web browser.

**Comment by noyoof** [comment]
@beardypig
Is there a video explanation of how this method works?

I hope help please, I'm a little novice I need a little of your time.

**Comment by gravyboat** [comment]
I'm going to close this. @noyoof @beardypig has gone above and beyond to answer as much as they can related to your question. It is not our job (nor will we make it our job) to support your reuse of broadcasts from ustream for embedding on your own site. If you do not understand how tokens work within the ustream infrastructure this is something you will have to research and understand yourself, we are not the personal support for people who wish to re-host content from the sites we support. We do not have any videos on the subject, nor do we intend to make any.

**Comment by Drack0550** [comment]
http://jazztv.pk/jazzlive/index.php/services/index/allChannels

Can you tell me how we decode it.....

**Comment by Drack0550** [comment]
Friends when I capture link from jazz tv application by the NetCapture. I get link in this format 

https://cdn2.jazztv.pk:8087/jazzl/Filmworld-126/live/126M/chunks.m3u8

But friends Now  I capture from jazz tv 
application by using HTTPCanery. I get link in this format 

http://jazztv.pk/jazzlive/index.php/services/index/allChannels

Can you tell me what is the matter??
