### ISSUE TITLE
Choose Twitch Server

### ISSUE THREAD

**Issue by gyvess** [streamlink/streamlink#91]
References:
https://github.com/chrippa/livestreamer/issues/94
https://github.com/bastimeyer/livestreamer-twitch-gui/issues/250

-----
The ability to choose which server you connect to when launching a twitch stream should allow for improved individual performance.

**Comment by hallcp** [comment]
This is firmly against Twitch ToS.

**Comment by gravyboat** [comment]
@hallcp I'm not doubting you, for the record can you please link the appropriate section? I don't have time to look at it right now.

**Comment by hallcp** [comment]
Section 13 is what you should refer to when you have a moment.  I don't think there are hrefs in the doc, so you'll need to scroll down. https://www.twitch.tv/p/terms-of-service

**Comment by gravyboat** [comment]
I would say doing this falls under the following sections:
q:
```
interfere with or disrupt the Twitch Service or servers or networks connected to the Twitch Service, or disobey any requirements, procedures, policies or regulations of networks connected to the Twitch Service; use the Twitch Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Twitch Service, or that could damage, disable, overburden or impair the functioning of the Twitch Service in any manner;
```
s:
```
attempt to circumvent any content filtering techniques we employ, or attempt to access any service or area of the Twitch Service that you are not authorized to access; or 
```
So yeah, it's pretty obvious doing this is frowned upon so I'm going to close this. Thanks @hallcp.
