### ISSUE TITLE
Plugin request: USTVnow

### ISSUE THREAD

**Issue by hpmueller1971** [streamlink/streamlink#911]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hi, i would like to request a plugin for [USTVnow](https://www.ustvnow.com/). They offer [free](https://www.ustvnow.com/register.php?sub=7) access to [7 US TV Channels](https://support.ustvnow.com/hc/en-us/articles/214145143-What-plans-channels-are-available-) and paid access to 30 channels, [some in HD](https://support.ustvnow.com/hc/en-us/articles/214145203-What-USTVnow-channels-are-available-in-HD-on-the-paid-plans-).

Access-URL:
http://m.ustvnow.com/iphone (iStuff)
http://www.ustvnow.com/gtv/ (SmartTVs)
http://watch.ustvnow.com/guide (Webbrowsers)

The direct links are javascript-obfuscated and i can't see deep-links to the programs

They use various protocols, including HLS and RTMP, **but HLS access only works for 30 days on the free account**. HLS seems to offer a bit more quality (even on the SD-Only free account)

There are already several projects in python that can produce an m3u playlist (the urls are only valid for about 30mins):

https://github.com/mathsgrinds/ustvnow-iptv-m3u-playlist (HLS playlist, worked a week ago)
https://github.com/guilleiguaran/ustvnow-m3u-server (RTMP playlist, stopped working about a year ago).

A choice of the protocol(s) would be great (as mentioned, HLS only works for 30 days for free), but i would be happy with anything that "just works" :)

Thanks :D

**Comment by gravyboat** [comment]
Hmm this one might be a bit questionable, if they're obfuscating links or doing any sort of encryption it might be difficult to support, looking at that script that was working a week ago, it looks like they were specifically pulling it as a mobile stream, so that's probably fixed whatever mechanic was allowing that bypass. Thanks for the request, we'll see if someone wants to investigate it.

**Comment by hpmueller1971** [comment]
Hiya, i'm not sure obfuscating was the right term, i meant they are not simply using www.ustvnow.com/abc etc links in the browser but some javascript-links, but i'm pretty sure they don't use encryption, at least when i was testing it a year ago, the rtmp links where standard rtmp (not rtmps etc)... Also, the hls playlists worked fine last week (before my trial expired) with tvheadend, which does NOT support encrypted hls-stream...

But then again, you can probably see more from the two python-examples than i can ever tell you ;). Just one thing i forgot, they also offer access via Roku, so there has to be a (relativly) stable api... In any case, thanks for your time :)

**Comment by beardypig** [comment]
Sounds cool, I'll take a look :)

**Comment by markosjal** [comment]
Just FYI I am using https://github.com/mathsgrinds/ustvnow-iptv-m3u-playlist in termux on android and generating a playlist that works beautfully. 

What I have been unable to detgermine is how long the links are valid  it seems somewhat random

You probably should try the mathgrinds USTVNow code
