### ISSUE TITLE
Issue with Twitch and MPC

### ISSUE THREAD

**Issue by kianparsa** [streamlink/streamlink#912]
Hi,

I am currently trying to use streamlink to watch twitch. Here is a screen shot of where I have gotten.

![4962ac64-368d-11e7-9422-eec5fd34e890](https://cloud.githubusercontent.com/assets/15823241/25980903/0eed1b12-368f-11e7-8cda-032ea3dd621c.PNG)

Once I execute this, MPC pops up, but it says, "Failed to Render."

Any ideas? Do I have to pass any additional parameters?

**Comment by kianparsa** [comment]
I was able to download the streamlink twitch gui, and it works. Awesome! Thank You guys

**Comment by gravyboat** [comment]
@kianparsa Thanks for continuing to troubleshoot, do you mind if I close this?

**Comment by kianparsa** [comment]
Yes please.
