### ISSUE TITLE
ImportError: No module named 'streamlink'

### ISSUE THREAD

**Issue by TomJerry12** [streamlink/streamlink#914]
Hello when I run the .py file, it does not find the streamlink module
C:\Program Files (x86)\streamlink\tests>test_buffer.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\streamlink\tests\test_buffer.py", line 3, in <module>
    from streamlink.buffers import Buffer, RingBuffer
ImportError: No module named 'streamlink'

When you run any file, an error occurs: No module named 'streamlink'
Installed streamlink-0.6.0.exe
----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

...

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by beardypig** [comment]
The python files installed by the Windows installer are not intended to be executed directly. You need to ensure your PATH is set up specifically to do that - which I don't recommend. If you want to use the `streamlink` API you should install Python separately and use `pip` to install the `streamlink` package from pypi.

**Comment by bastimeyer** [comment]
Going to close the thread, since the question has been answered by @beardypig. Thanks
