### ISSUE TITLE
[Feature-Request] HTTP-Access

### ISSUE THREAD

**Issue by hpmueller1971** [streamlink/streamlink#915]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hi all,

there are a lot of mediaplayers that can access http-streams (like DumpTVs™, or DumbIPTVBoxes™ from our favourite OEM in china, or almost any commercial Software Player for Windows or Mac), but cannot [directly] run python or use pipes

I would like to request a feature to be able to use streamlink with such players.

### Expected
I could imagine ~~three~~ one way to do this:

- A python wrapper for Apache
- ~~A Daemon-Mode for streamlink (opens a small http-server to access a stream)~~ edit: [already supported](https://streamlink.github.io/cli.html#cmdoption-player-external-http)
- ~~A url_rewrite_program for squid~~

With the first two i would imagine something to access

https://www.youtube.com/watch?v=dQw4w9WgXcQ

would become something like

http://my-very-badass-server/best/s/www.youtube.com/watch?v=dQw4w9WgXcQ

best would be the quality, s wheter the url is https or p for plain

~~The third would probably a bit more complex, where a [transparent] Squild in the network would intercept supported urls and change them [dynamically](http://www.funkypenguin.co.nz/how-to/april-fools-pranks-with-a-squid-proxy-server/) from a website to a simple http-video-stream...~~

### Reproduction steps

The ~~three~~ ONE way would be
- Apache Wrapper: Most pragmatic (and probably pretty easy to implement for someone who already uses apache and can code python)
- ~~Daemon-Mode: Easiest for endusers~~
- ~~Squid-Mode: Most cool for network admins to show off ;)~~

~~I will try to implement an apache wrapper myself (in bash or php, i don't "do" python ;)), in the unlikely case that i get this working before someone else does, i will update this feature-request...~~

Thanks :D

**Comment by gravyboat** [comment]
I guess I'm confused why we need a wrapper like this, we already support streaming data through http: https://streamlink.github.io/cli.html#cmdoption-player-external-http

**Comment by hpmueller1971** [comment]
I didnt know about that option, that's already pretty close to what i meant, thanks! But, it requires that you start streamlink from the console, with an already known url, so if you had a number of channels, it would mean to start one for each channel, any of which opens a dynamic port...

In the meantime, i already got something working in php, was a lot easier than i expected:

into /var/www/streamlink/index.php
```
<?php
$queryString = $_SERVER['REQUEST_URI'];
$url=str_replace("/streamlink/","",$queryString);
$cmd = "/usr/bin/streamlink -O $url best";
header('Content-type: video/mpeg');
header("Content-Type: application/octet-stream");
passthru($cmd);
?>
```

into apache config/virtual-host (/etc/apache2/sites-enabled/000-default.conf on ubuntu)
```
Alias /streamlink /var/www/streamlink/index.php
```

...then you can access a stream with something like

http://server/streamlink/https://www.youtube.com/watch?v=13WQzJT_BkM

Not really elegant, and i'm not sure if it's technically legal to have a full link including https:// inside a url, but it's working ;)

But, if the code for a http-server is already there, wouldn't it be very easy to open a (static) port and wait for a request, and take the url like i'm doing, if streamlink is started with --player-external-http but without an url...?

Anyways, for me the options are good enough, i'll leave it up to you if you want to leave it open or close it, thanks for your answer :D

**Comment by gravyboat** [comment]
Thanks for continuing to work on this and your detailed response @hpmueller1971! I'm going to leave this open for now in case anyone else wants to weigh in. From what I remember in previous discussions along this line it was something that we felt was out of scope for Streamlink itself, but we'll see what other people think. If no on responds in a few days I'll close it out.

**Comment by bastimeyer** [comment]
@gravyboat This is out of scope and it should be easy to write a wrapper program that translates http queries to streamlink parameters. 

@hpmueller1971 No, your server won't be streaming a lot of stuff, because your script can potentially execute anything and depending on the user privileges, this is extremely dangerous. This is similar to sql injections, but much worse. You should always validate user input.

**Comment by hpmueller1971** [comment]
@bastimeyer Yeah, no question, i was developing (yes, i'm using that term loosly, i don't qualify as a developer ;)) this just for usage for me, on a loopback-only apache on an internal network; after reading your comment i quickly understood that my script is basically an escapable shell... I'm going to edit my original comment and the original feature-request (most of what i want can already be done with streamlink, and i don't want to give more dump ideas to people like me who don't know that they are doing ;)

**Comment by gravyboat** [comment]
@hpmueller1971 On that note I think I'm going to close this out for now, thanks again for the detailed issue!

**Comment by bachoo786** [comment]
> I didnt know about that option, that's already pretty close to what i meant, thanks! But, it requires that you start streamlink from the console, with an already known url, so if you had a number of channels, it would mean to start one for each channel, any of which opens a dynamic port...
> 
> In the meantime, i already got something working in php, was a lot easier than i expected:
> 
> into /var/www/streamlink/index.php
> 
> ```
> <?php
> $queryString = $_SERVER['REQUEST_URI'];
> $gurl=str_replace("/streamlink/","",$queryString);
> $cmd = "/usr/bin/streamlink -O $url best";
> header('Content-type: video/mpeg');
> header("Content-Type: application/octet-stream");
> passthru($cmd);
> ?>
> ```
> 
> into apache config/virtual-host (/etc/apache2/sites-enabled/000-default.conf on ubuntu)
> 
> ```
> Alias /streamlink /var/www/streamlink/index.php
> ```
> 
> ...then you can access a stream with something like
> 
> http://server/streamlink/https://www.youtube.com/watch?v=13WQzJT_BkM
> 
> Not really elegant, and i'm not sure if it's technically legal to have a full link including https:// inside a url, but it's working ;)
> 
> But, if the code for a http-server is already there, wouldn't it be very easy to open a (static) port and wait for a request, and take the url like i'm doing, if streamlink is started with --player-external-http but without an url...?
> 
> Anyways, for me the options are good enough, i'll leave it up to you if you want to leave this feature-request open or close it, thanks for your answer :D
> 
> edit: Obviously, my little script makes an open proxy, this is on an internal server that can't be accessed from the internet, if someone wants to do this on a server in the internet, take precautions, or your server _will_ start streaming a lot of pr0n ;)
> 
> edit2: Well, obviously to real developers, this is much worse, my script would allow to execute any shell commands if propperly escape. **DONTDOTHAT**. If someone is willing to write a proper wrapper, that woud be great, but don't use my script, or at least validatey $url before executing it in (what could be a root-) shell...

@hpmueller1971 thanks for this php script.  I tried using but didn't work for me. Quick question where in your php script do I have to define the known url that I want to stream using streamlink? Thanks
