### ISSUE TITLE
Plugin request: tvnow.de (RTL, VOX, RTL II, RTLplus etc.)

### ISSUE THREAD

**Issue by malvinas2** [streamlink/streamlink#918]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Is it possible to add streams from www.tvnow.de to streamlink ? 
It just works with Adobe Flash Player. 

### Reproduction steps / Explicit stream URLs to test
http://www.tvnow.de/rtl2/the-walking-dead/folge-24-anruf/player
http://www.tvnow.de/vox/goodbye-deutschland/trauriges-schicksal-auf-koh-samui/player

**Comment by back-to** [comment]
Not possible, everything is DRM protected.

**Comment by malvinas2** [comment]
Ok, thank you.
