### ISSUE TITLE
BBC iPlayer plugin cannot find VPID

### ISSUE THREAD

**Issue by kachelaqa** [streamlink/streamlink#922]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

The BBC IPlayer plugin cannot find the VPID for valid urls.

### Reproduction steps / Explicit stream URLs to test

The following command:

`streamlink -l debug 'http://www.bbc.co.uk/iplayer/episode/b013pnv4/horizon-20112012-2-seeing-stars' best`

produces this output:

```
[cli][info] Found matching plugin bbciplayer for URL http://www.bbc.co.uk/iplayer/episode/b013pnv4/horizon-20112012-2-seeing-stars
[plugin.bbciplayer][debug] Loading streams for episode: b013pnv4
[plugin.bbciplayer][debug] Looking for vpid on http://www.bbc.co.uk/iplayer/episode/b013pnv4/horizon-20112012-2-seeing-stars
[plugin.bbciplayer][error] Could not find VPID for episode b013pnv4
error: No playable streams found on this URL: http://www.bbc.co.uk/iplayer/episode/b013pnv4/horizon-20112012-2-seeing-stars

```

and the same goes for any other valid iplayer url.

### Environment details

Operating system: arch linux
Streamlink and Python versions: streamlink-0.6.0 and python-3.6.1

### Comments, logs, screenshots, etc.

AFAICS, the page downloaded from the iplayer url does not contain the string "vpid".

**Comment by beardypig** [comment]
I'll take a look :-)
