### ISSUE TITLE
About Vaughn link

### ISSUE THREAD

**Issue by djflakf1** [streamlink/streamlink#923]
@beardypig 
Guys in this channel for example https://vaughnlive.tv/chespirito_mania 

1. Until yesterday i was using the port 1337 and was working perfect to put in a html site

http://i.imgur.com/fL4VcrV.png

 but now show the error that you can see in the picture, and using the port 1935 show the next error 

http://i.imgur.com/gKzxh0P.png

im using the next code 

```
<script src="http://jwpsrv.com/library/SakQCEfSEeOHhRIxOQfUww.js"></script>
<div id="playerjxJRqLMFuJaA_wrapper" style="position: relative; display: block; width: 700px; height: 470px;"><a id="beforeswfanchor0" href="#playerjxJRqLMFuJaA" tabindex="0" title="Flash start" style="border:0;clip:rect(0 0 0 0);display:block;height:1px;margin:-1px;outline:none;overflow:hidden;padding:0;position:absolute;width:1px;" data-related-swf="playerjxJRqLMFuJaA"></a><object type="application/x-shockwave-flash" data="http://p.jwpcdn.com/6/12/jwplayer.flash.swf" width="100%" height="100%" bgcolor="#000000" id="playerjxJRqLMFuJaA" name="playerjxJRqLMFuJaA" class="jwswf swfPrev-beforeswfanchor0 swfNext-afterswfanchor0" tabindex="0"><param name="allowfullscreen" value="true"><param name="allowscriptaccess" value="always"><param name="seamlesstabbing" value="true"><param name="wmode" value="opaque"></object><a id="afterswfanchor0" href="#playerjxJRqLMFuJaA" tabindex="0" title="Flash end" style="border:0;clip:rect(0 0 0 0);display:block;height:1px;margin:-1px;outline:none;overflow:hidden;padding:0;position:absolute;width:1px;" data-related-swf="playerjxJRqLMFuJaA"></a><div id="playerjxJRqLMFuJaA_aspect" style="display: none;"></div><div id="playerjxJRqLMFuJaA_jwpsrv" style="position: absolute; top: 0px; z-index: 10;"><div class="afs_ads" style="width: 1px; height: 1px; position: absolute; background: transparent;"></div></div></div><script type="text/javascript">
    jwplayer('playerjxJRqLMFuJaA').setup({
    file: "rtmp://198.255.17.66:1935/live?PXx0fvzKnu5sduos9VNPQHD9iNgYLAso/live_chespirito_mania",
        controls: 'true',
        title: 'My Stream',
        width: '728',
        height: '440',
        aspectratio: '16:9',
        stretching: 'exactfit',
        skin: 'bekle',
        autostart: 'true',
        primary: 'flash',

       
        
    });
</script>
```

2. using streamlink i can see the video in VLC but there is some way to play the channel like i did before in my site with the code that i have in the test site?

**Comment by beardypig** [comment]
All the information you need to play the stream with `rtmpdump` (`librtmp`) can be found by using the `--stream-url` option. I personally have no idea how to set up jwplayer to play rtmp, so cannot be of any help. 

You should ask elsewhere for support on jwplayer, this is for issues to do with streamlink and I cannot see an issue with streamlink here.

**Comment by djflakf1** [comment]
sorry @beardypig  i don't wanted to disturb u, i just trying to make that works and tried to ask you because you a big expert in this. just a little question do you know some player for a site to put the link extracted from streamlink?

**Comment by beardypig** [comment]
As I said, I do not. You should direct your question to either a more general forum, or a specific JWPlayer forum for advice on how to configure it.

**Comment by gravyboat** [comment]
I'm going to close this issue out, there's not much we can do support wise in this case.
