### ISSUE TITLE
Problem with livestream

### ISSUE THREAD

**Issue by vpontin** [streamlink/streamlink#930]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description and Actual behavior

Hi! I want to parse this url (http://original.livestream.com/chbrtv) in streamlink, but it only gives me this error:

`[cli][info] Found matching plugin oldlivestream for URL http://original.livestream.com/chbrtv
error: No playable streams found on this URL: http://original.livestream.com/chbrtv`

### Reproduction steps / Explicit stream URLs to test

1. I've downloaded the streamlink via the releases page (https://github.com/streamlink/streamlink/releases/tag/0.6.0)
2. pass via command line: `streamlink http://original.livestream.com/chbrtv`

### Environment details

Operating system and version: Windows 10 Creators Update x64
Streamlink and Python version: streamlink-script.py 0.6.0 w/ python included.

**Comment by karlo2105** [comment]
Either channel is offline or they use rtmp protocol which is not currently covered by livestream plugin.

**Comment by vpontin** [comment]
Oh then is the RMTP thing.

Thanks for the tip!
