### ISSUE TITLE
I need a working vod command line pls

### ISSUE THREAD

**Issue by Arzack** [streamlink/streamlink#931]
I searched here and googled it, I use vlc, thank you.

**Comment by beardypig** [comment]
You'll have to provide more information. What VOD are you trying to download, etc. There was an issue template that you appear to have ignored, please provide the information that was requested in the issue template.

**Comment by Arzack** [comment]
I want to watch vods with vlc, it's not an issue but I didn't know where to put this. Any vod, from windows cmd.

**Comment by beardypig** [comment]
The documentation is available online: https://streamlink.github.io/cli.html

**Comment by beardypig** [comment]
@Arzack did you find what you needed in the documentation?

**Comment by Arzack** [comment]
No, I did search there both pre and after writing this post.

**Comment by beardypig** [comment]
What is it that you didn't understand? Maybe we need to make the instructions clearer. Playing a VOD is the same as playing a livestream. You should be able to do `streamlink <vod_url> <quality>`, eg.
```
streamlink https://www.twitch.tv/videos/139928794 best
```

**Comment by Arzack** [comment]
Ah thank you, I'm just bad at 'anything programming'. Do I have to add anything to be able to search through the vod on vlc?

**Comment by beardypig** [comment]
What do you mean search, like seek in the video? You can add the `--player-passthrough http,hls` option, but it might not work for all streams, or in all players. `player-passthrough` tells streamlink to give the URL of the stream to your player.

**Comment by gravyboat** [comment]
As @beardypig has been kind enough to answer this, and it's noted that some streams/players don't currently have seeking support I'm going to close this. If anything we obviously need to make the documentation clearer, or ensure users have reviewed the docs prior to opening issues.
