### ISSUE TITLE
How to download stream from pscp.tv?

### ISSUE THREAD

**Issue by Truanifan** [streamlink/streamlink#936]
----

### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

This is more or a question than a bug or feature request. I'm trying to download the stream from pscp.tv, but I'm not sure how. This is the first time I've encountered the error "401 Client Error: replay requires cookie auth for url" from streamlink and I'm not sure how to add the cookie auth. I looked at the command-line documentation, but I've no idea how to add it. If it's possible to add support for pscp.tv that'd be great, but I'll settle for help downloading this one video. Thanks in advance.

### Reproduction steps / Explicit stream URLs to test

1. Find and copy m3u8 url from https://www.pscp.tv/atomtb_anime/1YqKDwbqXLNxV
2. streamlink "hls://https://prod-video-eu-central-1.pscp.tv/78ra98MLq2QPXE9nNztM_VnIM60ax7vhGBgN9e8esaAuwe0GH3J1zJ6-3wLtpZCJY0m1plZBkq-gGPRRgZh1ug/replay/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/playlist_16951451490713662630.m3u8" best -o "file.ts"

(I don't think you need a VPN connection...)

### Environment details

Operating system and version: Windows 7 64-bit
Streamlink and Python version: Streamlink ver. 0.40; Python ver. 2.7.12

### Comments, logs, screenshots, etc.

streamlink "hls://https://prod-video-eu-central-1.pscp.tv/78ra98M
Lq2QPXE9nNztM_VnIM60ax7vhGBgN9e8esaAuwe0GH3J1zJ6-3wLtpZCJY0m1plZBkq-gGPRRgZh1ug/
replay/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/playlist_16
951451490713662630.m3u8" best -o "video.ts"
[cli][info] Found matching plugin stream for URL hls://https://prod-video-eu-cen
tral-1.pscp.tv/78ra98MLq2QPXE9nNztM_VnIM60ax7vhGBgN9e8esaAuwe0GH3J1zJ6-3wLtpZCJY
0m1plZBkq-gGPRRgZh1ug/replay/eu-central-1/periscope-replay-direct-prod-eu-centra
l-1-public/playlist_16951451490713662630.m3u8
[cli][info] Available streams: live (best, worst)
[cli][info] Opening stream: live (hls)
[cli][error] Could not open stream: Unable to open URL: https://prod-video-eu-ce
ntral-1.pscp.tv/78ra98MLq2QPXE9nNztM_VnIM60ax7vhGBgN9e8esaAuwe0GH3J1zJ6-3wLtpZCJ
Y0m1plZBkq-gGPRRgZh1ug/replay/eu-central-1/periscope-replay-direct-prod-eu-centr
al-1-public/playlist_16951451490713662630.m3u8 (401 Client Error: replay require
s cookie auth for url: https://prod-video-eu-central-1.pscp.tv/78ra98MLq2QPXE9nN
ztM_VnIM60ax7vhGBgN9e8esaAuwe0GH3J1zJ6-3wLtpZCJY0m1plZBkq-gGPRRgZh1ug/replay/eu-
central-1/periscope-replay-direct-prod-eu-central-1-public/playlist_169514514907
13662630.m3u8)

**Comment by zp** [comment]
You can either upgrade to version 0.5.0 (or higher) for pscp.tv link support, or just use the old periscope url

````streamlink https://www.periscope.tv/atomtb_anime/1YqKDwbqXLNxV best -o file.ts````

**Comment by bastimeyer** [comment]
Going to close the thread, since this the question has been answered (thanks @zp) and the plugin 
has been fixed in one of the recent streamlink releases.
