### ISSUE TITLE
mplayer standard input pipe crashes streamlink

### ISSUE THREAD

**Issue by edwinjue** [streamlink/streamlink#944]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

I issue the following command and crashes:
  streamlink https://www.twitch.tv/stormen best | mplayer

I get the following error:
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 9, in <module>
    load_entry_point('streamlink==0.6.0', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1027, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 477, in handle_url
    plugin.module, args.url)
  File "/usr/lib/python2.7/dist-packages/streamlink/logger.py", line 55, in info
    self.manager.msg(self.module, 3, msg, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/streamlink/logger.py", line 40, in msg
    self.output.flush()
IOError: [Errno 32] Broken pipe
...

### Expected / Actual behavior

Expected not to crash and actually play the stream

...

### Reproduction steps / Explicit stream URLs to test

1. ... open terminal
2. ... type text after colon: streamlink https://www.twitch.tv/stormen best | mplayer
3. ... press enter

### Environment details

Operating system and version: ...
Linux MyNameIs 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Streamlink and Python version: ...
streamlink 0.6.0
Python 2.7.12

...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
Have you tried using the `--player` option? I've never even considered piping to mplayer like that and as far as I'm aware piping in that fashion isn't supported. Did you see that in the docs somewhere? If so can you link it?

**Comment by edwinjue** [comment]
Hi, that works. Thanks for the fast response!

**Comment by gravyboat** [comment]
No problem, thanks for the heads up that this resolved it!
