### ISSUE TITLE
Plugin request: Caster.fm 

### ISSUE THREAD

**Issue by skilleek** [streamlink/streamlink#946]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hi, I would like to request a plugin for the radio stream found in http://magnificat.caster.fm/
As always, thank you for all your help!

**Comment by beardypig** [comment]
Did you mean to close this?

**Comment by skilleek** [comment]
Hi @beardypig, yeah sorry. It ended up being really easy to extract the stream parameters. It is just displayed in the source code of the webpage.

Thank you anyway!
