### ISSUE TITLE
vidio(dot)com plugin not working

### ISSUE THREAD

**Issue by lokmiin** [streamlink/streamlink#949]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Hello Admin, Please checking vidio(dot)com plugin no longer working.
Could you fix it please..
Thank You.

### Expected / Actual behavior

...

### Reproduction steps / Explicit stream URLs to test

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by gravyboat** [comment]
We're going to need more output from you. What do you get from Streamlink when you try to use the plugin? Can you run with the `-v` and `-l debug` options please?

**Comment by lokmiin** [comment]
@gravyboat 
Thanks for replied..
Here is the error output run both on versions 0.5.0 and 0.6.0
C:\Program Files\Streamlink\bin>streamlink -v https://www.vidio.com/live/777-met
ro-tv-stream best
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/777-m
etro-tv-stream
error: No playable streams found on this URL: https://www.vidio.com/live/777-met
ro-tv-stream

Thank You So Much

All The Best

**Comment by lokmiin** [comment]
C:\Program Files\Streamlink\bin>streamlink -l debug https://www.vidio.com/live/7
77-metro-tv-stream best
[cli][info] Found matching plugin vidio for URL https://www.vidio.com/live/777-m
etro-tv-stream
error: No playable streams found on this URL: https://www.vidio.com/live/777-met
ro-tv-stream

**Comment by gravyboat** [comment]
Closed since #1066 is merged.
