### ISSUE TITLE
kijktvonline support

### ISSUE THREAD

**Issue by Wqrld** [streamlink/streamlink#951]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Can you add a plugin for the dutch website http://www.kijktvonline.nl/ ? it includes a lot of dutch tv and it seems to use the npo player like the npo plugin

### Reproduction steps / Explicit stream URLs to test

1. streamlink http://www.kijktvonline.nl/

**Comment by horacio9a** [comment]
I'm not from Holland so I cann't get this streams but you can try with @johnthecracker method:

set url=http://adaptive-e10c1a.npostreaming.nl/urishieldv2/l27m75e1b80f436521e700592a01f0000000.45801b1eb09aa955a2380d37a6d25f56/u/npo/status/vodgeodenied/vodgeodenied.ism/vodgeodenied-video=700000.m3u8
streamlink.exe --http-header "Referer=http://www.kijktvonline.nl/Nieuws%20zenders/242/Nederland_3/" hlsvariant://%url% best

**Comment by aycgit** [comment]
i dont know if that works for you but it doesnt seem to work for me

**Comment by horacio9a** [comment]
Second jpg is with NL proxy ;)
Link was: https://smoote1f.omroep.nl/urishieldv2/l2cm667558003500592a7ab7000000.6eb26e50436a5600/live/npo/tvlive/npo3/npo3.isml/npo3-audio_nld=128000-video=1400000.m3u8

It should streamlink to make it also use NL proxy!

![2242](https://cloud.githubusercontent.com/assets/17076459/26526922/72d47d9e-4389-11e7-9aa8-2fe71e824030.jpg)
![2243](https://cloud.githubusercontent.com/assets/17076459/26526923/72dcc33c-4389-11e7-9961-238c6a1aae20.jpg)

**Comment by aycgit** [comment]
i guess this wont work and ill just have to use the specialized website, keep this open as a suggestion but all npo vids can be viewed on npo.nl on streamlink so ill use that.

**Comment by back-to** [comment]
all of the channels are just embedded,
some of them are **already** **working** with **streamlink**.

Most of them won't work because there is **no plugin** or the embed **url** is **not uptodate**,
if you want a none working channel of it.

just open a new **plugin request** for the original website with example urls.
