### ISSUE TITLE
no gui in mpv using --vo=drm

### ISSUE THREAD

**Issue by nycko123** [streamlink/streamlink#954]
As stated in the title.

Everything works fine except there's no gui in mpv (ex. time info under O-key, volume control 9- 0-keys)

tried to force gui with no luck there:
1. `streamlink twitch_url quality --player="mpv --vo=drm --hwdec=vdpau --player-operation-mode=cplayer"`
2. `streamlink twitch_url quality -p mpv -a " --vo=drm --hwdec=vdpau --player-operation-mode=cplayer"`

### No issues under xserver, gui pops up by default, with no parameters needed.
-----------------------------------------------------------------------------------------------------------------------------------------------------------
When i run streams directly in mpv, everything works ok:
`mpv https://www.twitch.tv/stream --vo=drm --hwdec=vdpau`

Tech stuff:
Arch Linux 4.11.2-1-ARCH
Streamlink 0.6.0-1
Mpv 1:0.25.0-3
Youtube-dl 2017.05.23-1

**Comment by bastimeyer** [comment]
To me this sounds like a mpv issue. What happens when you pipe a video file from the file system into mpv in a non-x env, so that streamlink can be excluded?
`cat file | mpv --vo=drm --hwdec=vdpau -`

I don't know how mpv works in combination with yt-dl, but streamlink just spawns the mpv child process and pipes the data into mpv's stdin in its default configuration. Maybe that's the issue here.

Btw, the correct command when using the `-a` param would be:
`streamlink twitch_url quality -p mpv -a "--vo=drm --hwdec=vdpau --player-operation-mode=cplayer {filename}"`

There's also the `--force-window` mpv param, but I'm not sure if this can help here.

**Comment by nycko123** [comment]
This is what i get with
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto -`
`Playing: -
[file] Reading from stdin...
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
Using hardware decoding (vaapi-copy).
VO: [drm] 1280x720 nv12
AO: [pulse] 44100Hz stereo 2ch float`
Mpv gui doesn't work.

And that's what i get in x-server env
`cat testfile.mp4 | mpv --hwdec=auto`
`Playing: -
[file] Reading from stdin...
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
Using hardware decoding (vaapi).
VO: [vaapi] 1280x720 vaapi[nv12]
AO: [pulse] 44100Hz stereo 2ch float
AV: 00:00:06 / 00:03:09 (3%) A-V:  0.000 Cache:  9s+37MB`
Mpv GUI works fine

Also i've tried with --force-window param, no luck.
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto --force-window -`

> Btw, the correct command when using the -a param would be:
`streamlink twitch_url quality -p mpv -a "--vo=drm --hwdec=vdpau --player-operation-mode=cplayer {filename}"`

You're right sir, doesn't work anyway.

So, piping works in x-es, but not in tty's with drm.

**Comment by bastimeyer** [comment]
Ok, closing the thread then. Thanks for the follow up.

**Comment by bastimeyer** [comment]
As an addition, you could try using the `--player-passthrough` parameter. See the docs for available passthrough methods. The stream data will then be read by the player from streamlink's proxy server instead of being piped into the player.

**Comment by nycko123** [comment]
Thanks for your effort but i'll leave it as it is. It's not bothering me so much, i just wanted to point out a bug, which we both agreed is not in streamlink.
So I started a thread on mpv git page [HERE](https://github.com/mpv-player/mpv/issues/4459).
Let's see if/when they'll be willing to come up with solution.
Sorry for wasting your time Sir.
