### ISSUE TITLE
http://www.euronews.com/live bug

### ISSUE THREAD

**Issue by johnthecracker** [streamlink/streamlink#955]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

streamlink-0.6.0-20170525.exe

```
streamlink.exe http://www.euronews.com/live

[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
error: Unable to validate JSON: Unable to validate key 'backup': Type of 'http://euronews-fr-b7-cdn.hexaglobe.net/408a8175f58832bfce904f010908c600/5927fd60/euro
news/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8' should be 'dict' but is 'str'
```

streamlink-0.6.0.exe

```
streamlink.exe http://www.euronews.com/live

[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
error: Unable to validate JSON: Unable to validate key 'primary': Type of 'http://euronews-fr-p7-cdn.hexaglobe.net/9e822152542bcfe9a210aada3c14a345/5927fdd7/euronews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8' should be 'dict' but is 'str'
```

### Expected / Actual behavior

This works:

```
set m3u8=http://euronews-fr-b7-cdn.hexaglobe.net/408a8175f58832bfce904f010908c600/5927fd60/euronews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8 

streamlink hlsvariant://%m3u8% 540p

[cli][info] Found matching plugin stream for URL hlsvariant://http://euronews-fr-b7-cdn.hexaglobe.net/408a8175f58832bfce904f010908c600/5927fd60/euronews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8
[cli][info] Available streams: 90p (worst), 180p, 224p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 540p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
```

### Reproduction steps / Explicit stream URLs to test

1. That m3u8 is french and I try to get english m3u8:

    streamlink --stream-url http://www.euronews.com/live

    error: Unable to validate JSON: Unable to validate key 'backup': Type of 'http://euronews-fr-b7-cdn.hexaglobe.net/3d46191fc31e06a11e8c7d554d20dae5/5928023f/euronews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m3u8' should be 'dict' but is 'str'

2. http://www.euronews.com/live

    m3u8 with httpfox:

    http://euronews-en-p7-cdn.hexaglobe.net/d5be505f52f37cd9e44016f63d0ce1d0/59280121/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8

3. ...

### Environment details

Operating system and version:  win7 64
Streamlink and Python version: ...

...

### Comments, logs, screenshots, etc.

...

**Comment by roshavagarga** [comment]
I'm running an earlier version of streamlink, but one that is a nightly after the 0.6 version. 
I don't have any problem with euronews on it, BUT using the stable 0.6 version on Ubuntu doesn't let me open euronews in the same way as john described.

There are also no plugins found for DW and TVN.bg

**Comment by johnthecracker** [comment]
rosha, we're getting closer to solution, once we have m3u8 eny streamlink might work:

@beardypig,

what other command line utility apart from streamlink would return m3u8 url like httpfox does:

http://euronews-en-p7-cdn.hexaglobe.net/d5be505f52f37cd9e44016f63d0ce1d0/59280121/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8

**Comment by roshavagarga** [comment]
Upon updating to today's version of the nightly, I get an even bigger problem when trying to open Euronews or DW: https://pastebin.com/UmtLWZTf

**Comment by johnthecracker** [comment]
this works for now:

set url=https://tvplayer.com/watch/euronews
start /min streamlink.exe -p ffplay.exe %url% 1969k

**Comment by karlo2105** [comment]
```
streamlink "http://www.euronews.com/live" best
[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
[cli][info] Available streams: 90p (worst), 180p, 224p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Latest nightly build installed from pip along Python 2.7.x ;)

**Comment by roshavagarga** [comment]
@karlo2105 Are you running it on a Linux-based OS or on Windows 7 64bit like me and John?

**Comment by johnthecracker** [comment]
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"

**Comment by karlo2105** [comment]
Windows 7 32bit ;)

**Comment by horacio9a** [comment]
I have also Windows 7 32bit and used command: 

pip install --upgrade streamlink==0.6.0

but not help ... received this:

error: Unable to validate JSON: Unable to validate key 'primary': Type of u'http://euronews-en-p9-cdn.hexaglobe.net/ee2a014526f10847762865073a86437a/59290e19/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8' should be 'dict' but is 'unicode'

Can you explain how 'Latest nightly build installed from pip along Python 2.7.x'? ... I have Python 2.7.13

**Comment by back-to** [comment]
@horacio9a 
could you try
`pip install -U git+https://github.com/streamlink/streamlink.git`

euronews is not fixed in 0.6.0 you need the dev version from github.

old version was dict
https://github.com/streamlink/streamlink/commit/f167d292d3ac526676585250094eaaf6eb4a7dc6#diff-eb0b628a5109eebdf074e050672358e1L18

same for @johnthecracker check if your local `euronews.py` is the last version

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/euronews.py

---

```
streamlink "http://www.euronews.com/live" best
[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
[cli][info] Available streams: 90p (worst), 180p, 224p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: /usr/bin/vlc
```

**Comment by horacio9a** [comment]
@back-to
Many thanks for your help.

pip install -U git+https://github.com/streamlink/streamlink.git (failed with error code 3328 in None)

but fixed euronews.py working fine also on my streamlink 0.6.0

**Comment by johnthecracker** [comment]
@back-to

I tried streamlink-0.6.0-20170527.exe as-is and with plugin from your link.

result is the same,

[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
error: Unable to validate JSON: Unable to validate key 'primary': Type of 'http:
//euronews-fr-p9-cdn.hexaglobe.net/8329df0a68b2a281ea9e3a2d17d136af/592a06b5/eur
onews/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.
m3u8' should be 'dict' but is 'str'


Would you know to tell me what other command line utility apart from streamlink 
would return m3u8 from euronews.com/live ?

http://euronews-en-p7-cdn.hexaglobe.net/d5be505f52f37cd9e44016f63d0ce1d0/59280121/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8


Streamlink works with this m3u8.

**Comment by horacio9a** [comment]
While I did not yet know thanks to you that there is a corrected version for the euronews plugin:

https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/euronews.py

I was trying to fix it and find some fix.

For english link must be 'fr' replaced with 'www'

_live_api_url = "http://www.euronews.com/api/watchlive.json"

when start in browser 'res = http.get(self._live_api_url)' link, this is what gets:

Link: http://euronews-en-p-api.hexaglobe.net/d3bcf8b54606896be7aa1e194d7744af/5929a153/euronews/euronews-euronews-website-web-responsive-2/en/stream_info.php?format=hls

Response: {"status":"ok","protocol":"hls","primary":"http:\/\/euronews-en-p7-cdn.hexaglobe.net\/1b28d0d0e1122d2929353ead21ee1808\/5929a1e5\/euronews\/euronews-euronews-website-web-responsive-2\/ewnsabrenpri_eng.smil\/playlist.m3u8","backup":"http:\/\/euronews-en-b7-cdn.hexaglobe.net\/1b28d0d0e1122d2929353ead21ee1808\/5929a1e5\/euronews\/euronews-euronews-website-web-responsive-2\/ewnsabrenpri_eng.smil\/playlist.m3u8"}

'primary' and 'backup' links are same and good for english streaming of course after decoding.

At least I didn't know at least some help, because maybe I didn't understand exactly what you are looking for :)

**Comment by back-to** [comment]
@johnthecracker 

http://www.euronews.com/api/watchlive.json
```
{
  "url": "http://euronews-en-p-api.hexaglobe.net/.../.../euronews/euronews-euronews-website-web-responsive-2/en/stream_info.php?format=hls"
}
```
http://euronews-en-p-api.hexaglobe.net/.../.../euronews/euronews-euronews-website-web-responsive-2/en/stream_info.php?format=hls
```
{
  "status": "ok",
  "protocol": "hls",
  "primary": "http://euronews-en-p7-cdn.hexaglobe.net/.../.../euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8",
  "backup": "http://euronews-en-b7-cdn.hexaglobe.net/.../.../euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8"
}
```

_removed session ids_

---

**maybe the nightly version is broken**,
you should try to create a folder on `C:\` call it `plug` and paste a `euronews.py` in this folder

try this file
https://github.com/streamlink/streamlink/blob/master/src/streamlink/plugins/euronews.py

or with json debug
https://gist.github.com/back-to/9c08c64caf84370921d9fadccea25a7a

run in your cmd
`streamlink --plugin-dirs C:\plug http://www.euronews.com/live best`

**Comment by johnthecracker** [comment]
@horacio9a, @back-to, your replies helped.

I am not familiar with the situation and will have to do some reading.

This is how this will work with me after some scripting: 



curl http://www.euronews.com/api/watchlive.json

{"url":"http:\/\/euronews-en-p-api.hexaglobe.net\/9fc62224bd153374cb2de89df10dc780\/592a9ed8\/euronews\/euronews-euronews-website-web-responsive-2\/en\/stream_info.php?format=hls"}


http://euronews-en-p-api.hexaglobe.net/9fc62224bd153374cb2de89df10dc780/592a9ed8/euronews/euronews-euronews-website-web-responsive-2/en/stream_info.php?format=hls



curl http://euronews-en-p-api.hexaglobe.net/9fc62224bd153374cb2de89df10dc780/592a9ed8/euronews/euronews-euronews-website-web-responsive-2/en/stream_info.php?format=hls

{"status":"ok","protocol":"hls","primary":"http:\/\/euronews-en-p7-cdn.hexaglobe.net\/512ceb679260091f527c39f2a93a22f7\/592aa098\/euronews\/euronews-euronews-website-web-responsive-2\/ewnsabrenpri_eng.smil\/playlist.m3u8","backup":"http:\/\/euronews-en-b9-cdn.hexaglobe.net\/512ceb679260091f527c39f2a93a22f7\/592aa098\/euronews\/euronews-euronews-website-web-responsive-2\/ewnsabrenpri_eng.smil\/playlist.m3u8"}



http://euronews-en-p7-cdn.hexaglobe.net/512ceb679260091f527c39f2a93a22f7/592aa098/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8

http://euronews-en-b9-cdn.hexaglobe.net/512ceb679260091f527c39f2a93a22f7/592aa098/euronews/euronews-euronews-website-web-responsive-2/ewnsabrenpri_eng.smil/playlist.m3u8


There is small difference between "primary" and "backup", VLC can play both.



References:

https://stackoverflow.com/questions/21326397/curl-get-request-with-json-parameter

**Comment by johnthecracker** [comment]
@back-to,

streamlink-0.6.0-20170527.exe, default plugin:

works explicitly with --plugin-dirs,

streamlink.exe --plugin-dirs C:\P\STREAMLINK\pkgs\streamlink\plugins http://www.euronews.com/live best

[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
[cli][info] Available streams: 90p (worst), 180p, 224p, 360p, 540p, 720p (best)
[cli][info] Opening stream: 720p (hls)
[cli][info] Starting player: C:\P\VLC\vlc.exe
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
Press any key to continue . . .


This does not work:

streamlink.exe http://www.euronews.com/live best

[cli][info] Found matching plugin euronews for URL http://www.euronews.com/live
error: Unable to validate JSON: Unable to validate key 'backup': Type of 'http:/
/euronews-fr-b9-cdn.hexaglobe.net/9dc8fbcbf2d91e61952bfb8941738d34/592abfa8/euro
news/euronews-euronews-website-web-responsive-2/ewnsabrfrpri_fre.smil/playlist.m
3u8' should be 'dict' but is 'str'
Press any key to continue . . .


So, not a plugin issue, to me it looks like it is a streamlink issue.

**Comment by back-to** [comment]
this should work now with the last version `streamlink-0.6.0-20170605.exe`, at least it works for me.

my update was `streamlink-0.6.0.exe` to `streamlink-0.6.0-20170605.exe`

https://dl.bintray.com/streamlink/streamlink-nightly/

---

I got the same error on **ubuntu**,

the issue was i wanted to build `streamlink`
but it did not overwrote the streamlink version from `pip install streamlink`

after i removed it from pip `pip remove streamlink`,
i could build a newer version without issues.

**Comment by johnthecracker** [comment]
@back-to ,

I can confirm euronews works with release streamlink-0.6.0-20170606.exe.

I don't want to close this issue because streamlink team is working on it
so they will probably close it when they see fit.

If I was as good as you, I would call myself johnthehacker.

**Comment by johnthecracker** [comment]
Here is backup euronews script if streamlink's plugin comes to a halt.

requirements:

autoit to compile euro.au3 to euro.exe

vlc.exe on the path, if not, specify path in script.

euro.au3

RunWait('cmd.exe /c curl http://www.euronews.com/api/watchlive.json | CLIP','',@SW_HIDE)
$sData = ClipGet()
$sData = StringTrimLeft($sData,StringInStr($sData,'"http:'))
$sData = StringTrimRight($sData,StringLen($sData)-StringInStr($sData,'s"}'))
$sData = StringReplace($sData, "\/", "/")
RunWait('cmd.exe /c curl ' & $sData & ' | CLIP','',@SW_HIDE)
$sData2 = ClipGet()
$sData2 = StringTrimLeft($sData2,StringInStr($sData2,'"http:'))
$sData2 = StringTrimRight($sData2,StringLen($sData2)-StringInStr($sData2,'8","backup"'))
$sData2 = StringReplace($sData2,"\/","/")
$sData2 = StringReplace($sData2,"playlist.m3u8","ewnsabrenpri_eng_540p.m3u8")
ShellExecute('vlc.exe',$sData2)

**Comment by johnthecracker** [comment]
Euronews works with release 0.7.0
