### ISSUE TITLE
Mixer.com / Beam.pro

### ISSUE THREAD

**Issue by LufiaSelan** [streamlink/streamlink#957]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description
Greetings. It seems beam.pro changed to mixer.com over the past day and mixer.com links are not currently recognized by streamlink as a valid plugin. Additionally, streamlink requests for beam.pro seem to currently have three behaviors upon attempting to load a stream:
1. stream loads as expected
2. streamlink request returns no data from stream
3. error produced (below)

Error:
[Streamlink for Windows v0.6.0 - Git f286765]
[cli][info] Found matching plugin beam for URL beam.pro/channelone
[cli][info] Available streams: 720p_hls, 480p_hls, 480p (worst), 720p (best)
[cli][info] Opening stream: 720p (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rt
mp://dist4-rtmp.mixer.com:1935/beam//58717_source.mp4'}, redirect=False> (No dat
a returned from stream)
error: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rtmp://dist4-rtmp
.mixer.com:1935/beam//58717_source.mp4'}, redirect=False>, tried 1 times, exitin
g
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]

[Streamlink for Windows v0.6.0 - Git f286765]
[cli][info] Found matching plugin beam for URL beam.pro/cliffordakamiku
[cli][info] Available streams: 720p_hls, 480p_hls, 480p (worst), 720p (best)
[cli][info] Opening stream: 720p (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rt
mp://dist5-rtmp.mixer.com:1935/beam//201348_source.mp4'}, redirect=False> (No da
ta returned from stream)
error: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rtmp://dist5-rtmp
.mixer.com:1935/beam//201348_source.mp4'}, redirect=False>, tried 1 times, exiti
ng
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]

I picked some random streams that were on the front page for this report.

### Environment details

Operating system and version: Windows 7 Pro x64
Streamlink and Python version: Streamlink v0.6.0 - Git f286765, Packaged Python version 'Python 3.5.2'

...

### Comments, logs, screenshots, etc.
This is my first bug submission. Thanks for the wonderful project and support.
...

**Comment by gravyboat** [comment]
Thanks for the detailed report! At this point I don't think we've even started looking at what has changed between Beam and Mixer after they swapped over the name so we'll use this issue for that.

**Comment by maop** [comment]
Hello i did this plugin for livestreamer 2yrs ago!... i just reallized it was abandoned and forked :+1: 
AFAIK they are just redirecting everything from beam.pro to mixer.com, so, i don't remember much but i think the transition should be easy and just rename file beam.py to mixer.py and the url regexp changed to something like:

`_url_re = re.compile(r"http(s)?://(\w+.)?(beam.pro|mixer.com)/(?P<channel>[^/?]+)")`

and `s/beam.pro/mixer.com` to everything else. right?

noticing @beardypig who seems to be the one maintaining this plugin now ;)

best regards and thnx for keeping alive this amazing tool !

**Comment by tylerswagar** [comment]
I tried simply replacing Beam with Mixer and recompiling streamlink and it worked fine for me.  So evidently they haven't changed much.

**Comment by gravyboat** [comment]
Awesome, thanks for testing that out @tylerswagar!

**Comment by LufiaSelan** [comment]
Greetings. I made the change in _url_re that maop suggested and did some testing. Occasionally it will work, and on certain streams I still get this:

[Streamlink for Windows v0.6.0 - Git f286765]
[cli][info] Found matching plugin mixer for URL mixer.com/microsoftstore
[cli][info] Available streams: 1080p_hls, 480p_hls, 480p (worst), 1080p (best)
[cli][info] Opening stream: 1080p (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rt
mp://dist4-rtmp.mixer.com:1935/beam//406326_source.mp4'}, redirect=False> (No da
ta returned from stream)
error: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rtmp://dist4-rtmp
.mixer.com:1935/beam//406326_source.mp4'}, redirect=False>, tried 1 times, exiti
ng
[cli][info] Closing currently open stream...
[End of Streamlink for Windows]

I believe the microsoftstore stream that I keep testing this on has never succeeded in opening the stream thus far. I think this stream might be a 24/7 stream so it should be available for testing on.

Thanks again.

**Comment by gravyboat** [comment]
@LufiaSelan Any chance it could potentially be a routing issue for you that your friend isn't running into?

**Comment by LufiaSelan** [comment]
There's a chance, but I'm not sure how to diagnose it. I get nice and steady pings to the addresses that are referenced to not being able to be opened and tracerts do not seem to have anything dropped either.

**Comment by dojima** [comment]
I have this same issue when I don't use player-passthrough=rtmp.  When I do use player-passthrough=rtmp, I don't get an error, but MPC-HC fails the render the file unless I choose to watch one of the HLS streams.  If I simply have streamlink output the stream URL via --stream-url and paste the resulting URL into MPC-HC, it works just fine.

**Comment by LufiaSelan** [comment]
Thanks for the helpful reply. I had not realized that HLS seem to always work so far, yet the other ones behave seemingly randomly. At least that means it is not a personal routing issue and there is something going on here.

**Comment by Uriei** [comment]
I think I know what's the problem with non-HLS streams, the DNS server can't locate most of Mixer's RTMP servers, so I made my own workaround, in the mixer.py file I replaced
`                "rtmp": "{0}/{1}".format(assets["base"], video["src"])
` with
`                "rtmp": "rtmp://dist1-rtmp.mixer.com:1935/beam//{1}".format(assets["base"], video["src"])
`
and for now it seems to be working, until Mixer solves their DNS problems or whatever.

**Comment by beardypig** [comment]
@Uriei is correct, they appear to be generating junk `rtmp` URLs. Hardcoding the `rtmp` base URL seems to work, but they might be removing support for `rtmp` - as it isn't returned via the API as standard. They tend to favour `hls` or their own custom streaming format, `ftl`. We could remove `rtmp` support from the `beam/mixer` plugin and just return`hls`, or as a work around users can set `--stream-priority=hls` for `beam/mixer`. 

I don't really see any advantage favouring `rtmp` over `hls` in general, in fact I have my `stream-priority` option set to `http,hls,hds,akamaihd,*,rtmp` - `rtmp` is last... the default puts `rtmp` at the top 🥇

**Comment by Uriei** [comment]
@beardypig `rtmp` has one big advantage (for me at least) over `hls`, on non-FTL streams, `hls` has a 10-20 secs delay (exactly like watching from the website) and `rtmp` only has 2-4 secs (not quite like a FTL stream but really god for non-FTL streams).

**Comment by beardypig** [comment]
Ah, that's a good point @Uriei :) I hadn't considered the delay. 

`dist{1,2,3,4,5,6}-rtmp.mixer.com` all have dns records, but only `{1,2,3,4,6}` actually work for rtmp streams (for the ones I tried at least).

**Comment by LufiaSelan** [comment]
Thanks so much @Uriei ! The change that you suggested is working great! The short delay is the main reason that my friends and myself use beam/mixer for our streaming activities.

**Comment by AnsgarMans** [comment]
I'm getting the same issue @LufiaSelan was earlier even after the change made by @Uriei 

[Streamlink for Windows v0.6.0 - Git f286765]
[cli][info] Found matching plugin beam for URL beam.pro/revocane
[cli][info] Available streams: 720p_hls, 240p_hls, 480p_hls, 1080p_hls, 240p (wo
rst), 480p, 720p, 1080p (best)
[cli][info] Opening stream: 1080p (rtmp)
[cli][error] Try 1/1: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rt
mp://dist1-rtmp.mixer.com:1935/beam//429527_source.mp4'}, redirect=False> (No da
ta returned from stream)
error: Could not open stream <RTMPStream({'flv': '-', 'rtmp': 'rtmp://dist1-rtmp
.mixer.com:1935/beam//429527_source.mp4'}, redirect=False>, tried 1 times, exiti
ng
[cli][info] Closing currently open stream...

**Comment by beardypig** [comment]
@AnsgarMans if you add `--retry-open 10` to your streamlink command does it fail 10 times? ie. If you try again, does it eventually work?

**Comment by AnsgarMans** [comment]
Still fails to open. I've also discovered that Mixer has a status site: https://status.mixer.com/#

Which doesn't list RTMP in their video distribution. Is it possible they've phased it out?

**Comment by beardypig** [comment]
They are definitely phasing it out, they like their ftl distribution method now :-)

**Comment by AnsgarMans** [comment]
Guess I'm stuck with HLS then, or using the browser version and dealing with Firefox eating all of my RAM.

**Comment by beardypig** [comment]
Sorry @AnsgarMans, that's the best we can do for now. I did look at implementing their ftl protocol but it's quite involved and would probably take a while :-)

**Comment by LufiaSelan** [comment]
Super sadface, it stopped working for me too. With the phasing out RTMP, HLS is the only answer. Thanks for all the help with this.

**Comment by sigmap** [comment]
Will Mixer be included in a future update?

**Comment by gravyboat** [comment]
@sigmap It's going to take a lot of work to get Mixer working correctly. We would like to support it though.

**Comment by AnsgarMans** [comment]
is there a way to get a plugin for Mixer to use HLS? For some reason the Beam plugin no longer works for me anymore, even with HLS, and I have no knowledge as to how to make my own plugin.

**Comment by gravyboat** [comment]
@AnsgarMans They changed things a while back when they modified the site to be mixer instead of beam. I'm pretty sure it hasn't worked since then.

**Comment by back-to** [comment]
@sigmap @AnsgarMans for HLS livestreams
https://raw.githubusercontent.com/back-to/streamlink/mixer_com/src/streamlink/plugins/mixer.py
