### ISSUE TITLE
Non issue: user contributed arconai.tv plugin 

### ISSUE THREAD

**Issue by cirrusUK** [streamlink/streamlink#964]
Hi, user @intact wrote an [arconai.tv](https://www.arconaitv.me/) plugin for livestreamer, i edited 4 or 5 lines to make it comaptible with streamlink, get it [here](https://paste.xinu.at/amdB3X/ )
enjoy + props to the author @intact

**Comment by gravyboat** [comment]
Can you or @intact make a PR? If so we can add it to streamlink so it's available as a plugin by default and credit is properly attributed. I'm not willing to click on a shady looking paste URL.

**Comment by cirrusUK** [comment]
@gravyboat  ok i done that, thanks for the pointer, sorry i forgot windows users need to be wary of hyperlinks  ;P
joking aside,  thanks to you and the team for this splendid software.

**Comment by gravyboat** [comment]
@cirrusUK Hah, I'm running Windows and Linux and wouldn't click on it either way! NP, we'll see about getting that reviewed and added: https://github.com/streamlink/streamlink/pull/970 for posterity.
