### ISSUE TITLE
Enable certificate verification for Twitch

### ISSUE THREAD

**Issue by beardypig** [streamlink/streamlink#966]
### Description

Certificate verification is disable when making API calls in the Twitch plugin. According to comments in the code, "The certificate used by Twitch cannot be verified on some OpenSSL versions." The commit to disable verification was done 3 years ago during Livestreamer development, but the specifics are unclear. 

It might be risky to re-enable it and wait for people to complain that it doesn't work. The issue could be limited to Python 2.6 or perhaps Windows? I have no problems enabling certificate verification on Python 2.7/3.5/3.6 under Linux or macOS.

The question is how should we go about re-enabling the verification?

### Expected / Actual behaviour

Streamlink should _always_ verify SSL certificates, but it does not.

### Environment details

Streamlink and Python version: `streamlink<=0.6.0`

Related to #963

**Comment by Mirclus** [comment]
I did some digging:

- The commit that added it: https://github.com/chrippa/livestreamer/commit/5f6a3d3fe24f50b161be66e711db2989eea1e378
- The issue describing the problem: https://github.com/chrippa/livestreamer/issues/255

Seemed to be two problems:
1. A specific version of `ca-certificates` for Arch Linux
2. MITM-proxies

I don't think the first issue is still relevant. However, the second part should be investigated.

**Comment by bastimeyer** [comment]
I don't think there are any reasons for keeping this disabled.
