### ISSUE TITLE
Plugin request: TV2 Player Denmark

### ISSUE THREAD

**Issue by skilleek** [streamlink/streamlink#973]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I would appreciate if you could develop a plugin to catch the stream found in this TV2 Denmark Player: https://play.tv2.dk/live/

As always, many thanks for all your support!

**Comment by back-to** [comment]
> Når du afspiller indhold fra vores live-kanaler, TV 2 NEWS undtaget, er de beskyttet af DRM filer. Din browser skal således være indstillet til at tillade disse filer.

https://play.kundeservice.tv2.dk/hc/da/articles/217490977-DRM-guiden-Windows-Mac-

there website says they use **DRM**,
I assume it's true, so it **won't work with streamlink**.

_Closing._
