### ISSUE TITLE
Streamlink sometimes closing stream after closing HTTP connection

### ISSUE THREAD

**Issue by x-traxion** [streamlink/streamlink#975]
### Checklist

- [x] This is a bug report.
- [x] I have read the contribution guidelines.

### Description
Hi,
Im using Streamlink to get Twitch Streams in my Bouquet of my Linux Reciever (VU+ Solo4k).
Long time i dont use Streamlink or Livestreamer.
Yesterday i started Streamlink with a batch File on my PC as usual. It works fine till i zapped to another Channel (Sat) and zapped back to the Stream but it dont work.
On my PC i got an Error in the cmd Window and i have to restart the batch file.
I get this in 9 out of 10 tries.

Operating system and version: Windows 7 x64 pro, Marusys VU+ Solo4K
Streamlink version: 0.6.0

### Comments, logs, screenshots, etc.
```
C:\Streamlink\bin\streamlink.exe" --player-external-http --player-external-http-port 9999 --player-continuous-http twitch.tv/rocketbeanstv best
[cli][info] Found matching plugin twitch for URL twitch.tv/rocketbeanstv
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 1080p (best)
[cli][info] Starting server, access with one of:
[cli][info]  http://127.0.0.1:9999/
[cli][info]  http://192.168.124.200:9999/
[cli][info] Got HTTP request from Vu+ STB HbbTV/1.1.1 (+PVR+RTSP+DL;VTi;;;)
[cli][info] Opening stream: 1080p (hls)
error: Error when writing to output: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert durch den Hostcomputer abgebrochen, exiting
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

**Comment by horacio9a** [comment]
I don't know how much it will help my experience.
Operating system and version: Windows 7 x32 Ultimate
Streamlink version: 0.6.0

Started this link in last Firefox: http://twitch.tv/rocketbeanstv

With last IDM received https://video-edge-c2b008.fra02.hls.ttvnw.net ... ffplay has no problems with it
Same is with streamlink!
![2250](https://cloud.githubusercontent.com/assets/17076459/26734952/4527965c-47c0-11e7-93bf-3013d264bf80.jpg)
![2251](https://cloud.githubusercontent.com/assets/17076459/26734965/4e028d40-47c0-11e7-8eac-cd547c0ceb69.jpg)

**Comment by beardypig** [comment]
This is almost certainly the same issue as reported in #916.

**Comment by skulblakka** [comment]
I can reproduce this problem on my machine using mpv and VLC. Using VLC it seems to work most of the time as expected while it always fails using mpv.

OS: Win10 Pro x64
streamlink: 0.7.0 (build using e6db411)
Python: 3.6.2
mpv: 0.26.0
VLC: 2.2.4
