### ISSUE TITLE
Handle different YouTube live links

### ISSUE THREAD

**Issue by ahtcx** [streamlink/streamlink#978]
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

Currently handles `/c/<channel>/live` but YouTube also supports that link without the `/c` part. Too small for a pull request.

### Expected / Actual behavior

Now able to match YouTube links without the `/c` prefix.

### Reproduction steps / Explicit stream URLs to test

1. `youtube.com/c/<channel>/live`
2. `youtube.com/<channel>/live`
3. `gaming.youtube.com/<channel>/live`

**Comment by ahtcx** [comment]
Here's a patch

```
diff --git a/src/streamlink/plugins/youtube.py b/src/streamlink/plugins/youtube.py
index 7907aca..23a15c8 100644
--- a/src/streamlink/plugins/youtube.py
+++ b/src/streamlink/plugins/youtube.py
@@ -107,7 +107,7 @@ _url_re = re.compile(r"""
         )
         |
         (?:
-            /c/(?P<liveChannel>[^/?]+)/live
+            /(c/)?(?P<liveChannel>[^/?]+)/live
         )
     )
 """, re.VERBOSE)
```

**Comment by beardypig** [comment]
Looks good, do you want to open a PR for it?

**Comment by beardypig** [comment]
No fix is too small for a PR! Well done for fixing your own issue @ahtcx ;)
