### ISSUE TITLE
hitbox.tv is now smashcast.tv

### ISSUE THREAD

**Issue by azes** [streamlink/streamlink#981]
### Checklist

- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

http://blog.hitbox.tv/smashcast-emerges/

**Comment by beardypig** [comment]
I think this was fixed after 0.6.0, the nightly version supports it. You download the nightly version or wait for 0.7.0 to be released :-)

**Comment by HerbertEttore** [comment]
I modified the original Hitbox plugin to support the new Smashcast.
Download the attached ".zip" file and place "smashcast.py" file in the pluguin folder.
It's working perfectly.
[Download "smashcast.zip"](https://github.com/streamlink/streamlink/files/1049987/smashcast.zip)

**Comment by gravyboat** [comment]
This was the existing issue: https://github.com/streamlink/streamlink/issues/935

**Comment by gravyboat** [comment]
This was the existing issue: https://github.com/streamlink/streamlink/issues/935
