### ISSUE TITLE
tvplayer.com 404 Client Error

### ISSUE THREAD

**Issue by nicr4wks** [streamlink/streamlink#988]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

tvplayer.com has started returning 404 client error:

streamlink https://tvplayer.com/watch/chilled
[cli][info] Found matching plugin tvplayer for URL https://tvplayer.com/watch/chilled
error: Unable to open URL: http://tvplayer.com/watch/context (404 Client Error: Not Found)

### Expected / Actual behavior

Available video qualities are detected and if one has been selected the video begins to play.

### Reproduction steps / Explicit stream URLs to test

streamlink https://tvplayer.com/watch/chilled

### Environment details

streamlink 0.6.0-47-g695cc35
Python 2.7.9

**Comment by beardypig** [comment]
@nicr4wks thanks for the bug report, I have submitted a PR to fix the issue.

If you want to manually replace the plugin file (`tvplayer.py`) it should be relatively straight-forward. You should be able to download [tvplayer.py](https://raw.githubusercontent.com/beardypig/streamlink/d60314c7c14abecf118a0f9ceaca382df371286d/src/streamlink/plugins/tvplayer.py) and replace the existing one (likely in `C:\Program Files\Streamlink\pkgs\streamlink\plugins`).

**Comment by nicr4wks** [comment]
Thanks @beardypig  ! Working well.
