### ISSUE TITLE
Add support for looch.tv 

### ISSUE THREAD

**Issue by azes** [streamlink/streamlink#991]
- [x] This is a feature request.
- [x] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description
Any chance of getting a plugin for this?

https://looch.tv/channels

**Comment by gravyboat** [comment]
Do you have any additional details? An example channel, what requests look like, etc.? Anything would be appreciated.

**Comment by azes** [comment]
Example:
https://looch.tv/channel/KofyeinTV
