### ISSUE TITLE
Feature request: allow playing *and* archiving a stream simultaneously

### ISSUE THREAD

**Issue by larryhastings** [streamlink/streamlink#994]
- [X] This is a feature request.
- [X] I have read the contribution guidelines.

### Description

The documentation for the `-o FILENAME` flag says: `Write stream data to FILENAME instead of playing it.`.

It's frequent that I want to *both* play *and* write a stream.  Right now this means I run two instances of streamlink, which uses 2x my incoming bandwidth, 2x the bandwidth for the streaming service, etc.

It'd be nice if there was an additional flag that told streamlink "save the stream to disk *and* also play it live via VLC".

Thanks!

**Comment by bastimeyer** [comment]
This has been asked in #105 and there's also a PR for this: #920. 

Right now you can use the `-O` parameter and save the additional bandwidth like this:
```
streamlink -O url stream | tee recording.ts | vlc - 
```
This uses the standard output, pipes it into the tee process, which writes its input into a file and also outputs it again and pipes it into the vlc process which again reads from stdin.

https://github.com/streamlink/streamlink/issues/105#issuecomment-256678800

**Comment by larryhastings** [comment]
Sorry--I did look for an existing issue, honest.  I guess my google-fu was not up to the task.
