### ISSUE TITLE
Only the first frame of video is shown in VLC

### ISSUE THREAD

**Issue by voltagex** [streamlink/streamlink#997]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [x] I have read the contribution guidelines.

### Description

streamlink opens fd://0 in VLC, but I only get the first frame of video

### Expected / Actual behavior

Stream plays correctly

### Reproduction steps / Explicit stream URLs to test

1. pip install streamlink on Windows 10
2. streamlink --default-stream best https://www.youtube.com/watch?v=IS9rnShRytc
3. Get one frame only

### Environment details

Operating system and version: Microsoft Windows [Version 10.0.15063]
Streamlink and Python version: streamlink.exe 0.6.0, Python 3.5.2 :: Anaconda 4.2.0 (64-bit)

...

### Comments, logs, screenshots, etc.

```
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5247 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 5248 to queue
[stream.hls][debug] Adding segment 5249 to queue
[stream.hls][debug] Download of segment 5247 complete
[cli][info] Starting player: "C:\Program Files\VideoLAN\VLC\vlc.exe"
[cli][debug] Writing stream to output
[stream.hls][debug] Download of segment 5248 complete
[stream.hls][debug] Download of segment 5249 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5250 to queue
[stream.hls][debug] Download of segment 5250 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 5251 to queue
[stream.hls][debug] Download of segment 5251 complete
```
Download seems to work - python.exe is using ~300kb/s of bandwidth, but no further video is displayed after the first frame. Seems to be a VLC issue as if I use ffplay it works fine.

**Comment by gravyboat** [comment]
Thanks for the detailed report @voltagex! This is actually an issue with VLC that we've seen before so you were definitely on the right track there (https://github.com/streamlink/streamlink/issues/883) if you upgrade to VLC 3 that should resolve it.

**Comment by voltagex** [comment]
Ah, sorry for the duplication. I'll use ffmpeg until VLC 3 is a little more
stable.

**Comment by gravyboat** [comment]
@voltagex Are you using the VLC nightly currently? This issue should only be occurring if you're using the stable VLC install.

**Comment by beardypig** [comment]
There was a similar issue with VLC 3, #798. 

@voltagex if you are able to test it, then it would be nice to know if it works with an earlier VLC3 nightly :)

**Comment by voltagex** [comment]
Confirming the stream works as expected with a VLC 3 nightly: e.g. 

```PS C:\Users\Adam> streamlink.exe --default-stream best https://www.youtube.com/watch?v=RU3srXqYAO0 -p "C:\Users\Adam\Dow
nloads\vlc-3.0.0-20170612-0453-git-win64\vlc-3.0.0-git\vlc.exe"``` but fails if I launch it in VLC 2. 
Another interesting thing I noticed is that non-live streams seem to work fine in both VLC versions - e.g. the URL I originally reported with is now an archive of the livestream.

**Comment by gravyboat** [comment]
Thanks for the additional testing and details @voltagex, are you okay with me closing this since we've confirmed it's a VLC issue?

**Comment by voltagex** [comment]
Yep, no worries @gravyboat, thanks for the help. If you come across another thing where VLC is choking on the TS file, let me know and we can work together to get a sample / report for VLC
