### ISSUE TITLE
Issue with Chaturbate streams

### ISSUE THREAD

**Issue by Zero3K** [streamlink/streamlink#998]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] This is a plugin (improvement) request.
- [ ] I have read the contribution guidelines.

### Description

I am getting an error trying to play a Chaturbate stream.

### Expected / Actual behavior

I expect it the stream to load in the media player I have configured it to use. Instead, the following error is shown:

error: Unable to open URL: https://edge35.stream.highwebmedia.com/live-edge/lola
shemale-sd-d61a3168b3263bfadb87bae58899302a056dd3b9f99378f4a7e38bf35aebb690_fast
_aac/playlist.m3u8?rp=d0f4ef1897b8169c49011747cc136358b17e0337e31a8ad741433d6fb4
3129e1&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22org%22%3A%22PHX%22%2C%2
2expire%22%3A1497302736%2C%22sig%22%3A%2224d879be8bf112422f6f0ad1d87c6d11f94040d
ef4ee6258fcfef16de9d99420%22%2C%22room%22%3A%22lolashemale%22%7D (HTTPSConnectio
nPool(host='edge35.stream.highwebmedia.com', port=443): Max retries exceeded wit
h url: /live-edge/lolashemale-sd-d61a3168b3263bfadb87bae58899302a056dd3b9f99378f
4a7e38bf35aebb690_fast_aac/playlist.m3u8?rp=d0f4ef1897b8169c49011747cc136358b17e
0337e31a8ad741433d6fb43129e1&u=AnonymousUser&t=%7B%22username%22%3A%22%22%2C%22o
rg%22%3A%22PHX%22%2C%22expire%22%3A1497302736%2C%22sig%22%3A%2224d879be8bf112422
f6f0ad1d87c6d11f94040def4ee6258fcfef16de9d99420%22%2C%22room%22%3A%22lolashemale
%22%7D (Caused by NewConnectionError('<requests.packages.urllib3.connection.Veri
fiedHTTPSConnection object at 0x04002D70>: Failed to establish a new connection:
 [WinError 10061] No connection could be made because the target machine activel
y refused it',)))

### Reproduction steps / Explicit stream URLs to test

I ran it with https://chaturbate.com/lolashemale/ as the parameter.

### Environment details

Operating system and version: Windows 7 Home SP1
Streamlink Version: 0.6.0

**Comment by back-to** [comment]
the **plugin itselt works fine**, tested on win7/win10/linux

---

- does the stream load in your browser? _(not the flash stream)_
- does other plugins work for you?
- is your internet connection ok?

**Comment by gravyboat** [comment]
Probably related to this yeah @back-to? https://github.com/streamlink/streamlink/issues/685 Seems like some streams just have issues based on previous reports.

**Comment by bastimeyer** [comment]
Can this be closed? There hasn't been a response in over 16 days and the plugin should still be working fine.

**Comment by gravyboat** [comment]
@bastimeyer Yep I'm closing it.
